### ISSUE TITLE
Realtime subscriptions aren't working in supabase v2

### ISSUE THREAD

**Issue by mayooear** [supabase/supabase#10026]
# Bug report

## Describe the bug

Whilst using Next.js in local development, the v2 supabase realtime doesn't log a new connection in the supabase dashboard, changes to events, or console log the payload.

Replication and realtime have been enabled for the tables. There is currently no RLS enabled on tables and next.js strict mode is "false."

## To Reproduce

1. Create two tables: a posts and likes table. Enable realtime on both tables. In the posts table create a uuid `id` and column `likes` as an integer. 
2. In the likes table, link the id as a foreign key linked to the id in the posts table, and create columns for `user_id` and `post_id` .
3.  Create remote procedure calls to increment and decrement the likes count in the posts table.
```js
create function increment (row_id uuid)
    returns void as
    $$
      update "posts"
      set likes = likes + 1
      where id = row_id;
    $$ 
    language sql volatile;

```
4. In Next.js, Initialize supabase with "createClient" by copying the project url and project api key (anon public) from settings > api.
5. Use the supabase client to create the realtime subscription as a side effect within a `post` component:

```js

useEffect(() => {

    const userListener = supabase
      .channel("public:likes")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "likes" },
        (payload) => {
          console.log("Change received!", payload);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(userListener);
    };
  }, []);

```
5. Create a `handleLike` function that handles a 'likes' button clicks to insert or delete a row from the likes table AND incement/decrement likes count in the posts table.

```js

const handleLike = async (id) => {
    const { data, error } = await supabase
      .from("likes")
      .select()
      .match({ user_id: user.id, id: id });

    if (data.length > 0) {
      const { data, error } = await supabase
        .from("likes")
        .delete()
        .match({ user_id: user.id, id: id })
        .select();
        
      decrementLikes(id);
    } else {
      const { data, error } = await supabase
        .from("likes")
        .insert({ user_id: user.id, id: id })
        .select();
      console.log("handle insert like data", data);

      incrementLikes(id);
    }
  };

  const incrementLikes = async (id) => {
    const { data, error } = await supabase.rpc("increment", {
      row_id: id,
    });
  };

  const decrementLikes = async (id: string) => {
    const { data, error } = await supabase.rpc("decrement", {
      row_id: id,
    });
  };

```
6. Create jsx elements to display the ui realtime likes changes when the handlelike function is called.

```jsx
{user && hasLiked ?  (
                      <div
                        onClick={() =>
                          handleLike(postId)
                        }
                      >
                        <HeartFilled>
                        <span>{likesCount}</span>
                      </div>
                    ) : (
                      user && (
                        <div
                        >
                          <EmptyHeart>
                          <span>
                            {likesCount}
                          </span>
                        </div>
                      )
                    )}

```

## Expected behavior

When a like button for a post is clicked, the UI should immediately display a different `likesCount` integer and `HeartIcon` filled color to indicate that it's been Liked or Unliked.

Right now, the ui doesn't change until the page is refreshed.

<img width="120" alt="likesIncrement" src="https://user-images.githubusercontent.com/107035552/199450129-5a111e5a-573a-4435-95d7-927195af0051.PNG">

## Screenshots

The state of the RealTimeChannel object is "joined."

<img width="559" alt="websocketheaders" src="https://user-images.githubusercontent.com/107035552/199453829-730716af-d757-4afd-b1d7-339ad52251cd.PNG">

<img width="546" alt="websocketPayload" src="https://user-images.githubusercontent.com/107035552/199453844-a3fd56ae-b3ad-4767-85f1-400d9c548bb9.PNG">

<img width="566" alt="supabasenolog" src="https://user-images.githubusercontent.com/107035552/199454304-68e61d2e-c189-4354-a7d5-80ac57a372c3.PNG">

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: "@supabase/supabase-js" 2.0.4
- Version of Node.js: 16.17.0

## Additional context

Every other use of the supabase client works apart from realtime events.

**Comment by xxRockOnxx** [comment]
I think this is another case of this issue: https://github.com/supabase/realtime/issues/309

**Comment by mayooear** [comment]
> I think this is another case of this issue: [supabase/realtime#309](https://github.com/supabase/realtime/issues/309)

Thanks. I'm not sure how this is related to docker or CLI upgrades though?

The titles are similar but i'm not sure the issues are.

**Comment by mayooear** [comment]
> You say this "Whilst using Next.js in local development". If you are not running realtime to a Supabase hosted instance, according to the linked issue v2 is not supported yet.

Thanks Gary. I am not familiar with running realtime on a Supabase hosted instance, can you provide guidance or docs on how to do this? Everything else works in local development apart from realtime. Cheers

**Comment by GaryAustin1** [comment]
The linked issue https://github.com/supabase/realtime/issues/309 talks about Supabase needing to get realtime v2 working locally.  So you may need to wait for that for local development.

I don't think realtime would do you much good if your project/database was not on the hosted instance as you would have no data to monitor.

This presumes I'm understanding you correctly that you are running Supabase locally and did not just mean your source code locally.

**Comment by mayooear** [comment]
Thanks Gary. Bare with me here as I'm new to working with supabase. But I'm not sure I understand what you mean by "hosted instance", "supabase locally"  and "source code locally."

As per my setup above, all I did was follow the docs instructions: start a development server on my computer in Next.js, create realtime tables in supabase, npm install npm install @supabase/supabase-js, copy anon key and url from supabase dashboard to initialize new client, then use the new v2 syntax for realtime listening i.e. `const userListener = supabase.channel("public:likes").on(...`

Is this what you're referring to as "supabase locally"? 

If so, how do I created this "hosted instance" to test realtime changes in UI before deployment? 

Thanks a lot

**Comment by GaryAustin1** [comment]
Sounds like you are using a Supabase hosted instance (your URL looks like this `https://qbfxxxxxxxxxxxqr.supabase.co`.  The database is management by Supabase in the cloud.

You can try this tool Supabase is working on to verify your instance is running correctly: https://realtime.supabase.co/inspector/new

You can also put some code in `.subscribe(status=>console.log(status)) ` that will give you more info on what the connection is doing.

**Comment by mayooear** [comment]
Hi Gary,

Yes you're correct the url looks like that. The `console.log` status shows `subscribed` and the realtime state shows `joined.`

However, when i used realtime inspector i saw the following in my log:

```
Error polling replication: %Postgrex.Error{
  message: nil,
  postgres: %{
    code: :invalid_name,
    file: "wal2json.c",
    line: "655",
    message: "could not parse value \"public.profiles,public.user,public.user annotations,public.likes\" for parameter \"add-tables\"",
    pg_code: "42602",
    routine: "pg_decode_startup",
    severity: "ERROR",
    unknown: "ERROR",
    where: "slot \"supabase_realtime_replication_slot\", output plugin \"wal2json\", in the startup callback"
  },
  connection_id: 56105,
  query: nil
}

```

Based on this assessment I assume I am already using a hosted instance, if so what is the fix here?

Kind regards

**Comment by GaryAustin1** [comment]
You may need to contact support.  Are any of your tables using capital letters?

**Comment by mayooear** [comment]
All tables are in lower case. I just contacted support. Thank you for your support.

**Comment by w3b6x9** [comment]
@mayooear I think the problem is that Realtime doesn't handle tables with spaces in their names.

**Comment by mayooear** [comment]
> @mayooear I think the problem is that Realtime doesn't handle tables with spaces in their names.

Hi Thanks. As per the "reproduce" section above, the table is simply "likes" so there is no spacing. However, the id is a foreign key linked to the id of `user annotations`, so I have now changed the foreign table to userAnnotations. But this didn't fix the issue.

So I went back to https://realtime.supabase.co/inspector/new to test and here's the logs:

```

CONNECTED TO RealtimeWeb.UserSocket in 52ms
  Transport: :websocket
  Serializer: Phoenix.Socket.V1.JSONSerializer
  Parameters: %{"log_level" => "info", "vsn" => "1.0.0"}

JOINED realtime:likes in 1ms
  Parameters: %{"config" => %{"broadcast" => %{"self" => true}, "postgres_changes" => [%{"event" => "*", "schema" => "public", "table" => "likes"}], "presence" => %{"key" => ""}}}

Subscribed to PostgreSQL

```

However, when I send a test payload via broadcast an event nothing happens in supabase logs or in local console.log . I also tried to use a different table called "profiles" and the same issue reoccured.

Further, please note that if i try to subscribe from my local dev environment without using the inspector, none of the above logs show up at all.

Await feedback

Many thanks

**Comment by mayooear** [comment]
Hi,

Thanks.

I addressed this on the issue already but no reply in 3 days.

Shall I reopen this on support again?

**Comment by w3b6x9** [comment]
We were able to resolve this issue via support ticket. Issue here was that the `likes` table had an incorrect primary key / unique index.
