### ISSUE TITLE
Full responsive support for app.supabase.com on mobile devices

### ISSUE THREAD

**Issue by vhpx** [supabase/supabase#10028]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, all features of app.supabase.com cannot be accessed normally when using iphones (even with request desktop web version on Google Chrome)

## Describe the solution you'd like

A responsive UI overhaul to make Supabase web application fully featured and easy to navigate on all devices.

**Comment by saltcod** [comment]
Hi @vhpx 

We agree completely. Sadly, with the current team size, we've got to prioritize the experience on desktop-sized screens. We definitely hope in the future to have parity between the mobile and desktop experiences. Thanks for the feedback and appreciate you using Supabase.

**Comment by emillinden** [comment]
> Hi @vhpx 
> 
> 
> 
> We agree completely. Sadly, with the current team size, we've got to prioritize the experience on desktop-sized screens. We definitely hope in the future to have parity between the mobile and desktop experiences. Thanks for the feedback and appreciate you using Supabase.

Any change of plans now @saltcod, 2 years later?

I'm often interested in checking various data related to my Supabase instances on the run.

As mentioned, requesting desktop version doesn't work either. Making this work would be an okay fix (at least for me) if no resources are available for a fully responsive experience.
