### ISSUE TITLE
Error in realtime container replication slot supabase_realtime_rls is active for PID 358141 - selfhost supabase

### ISSUE THREAD

**Issue by gopal1996** [supabase/supabase#10045]
Hi Team,

I have been using supabase self-host for a few days. Not sure when the issue was occurring, but after some time of idle state,
supabase real-time container getting the error "replication slot supabase_realtime_rls is active for PID 358141".

Once this error comes, WebSocket is not getting the real-time data.

please find the attached screenshot

<img width="1527" alt="Screenshot 2022-11-01 at 9 03 59 AM" src="https://user-images.githubusercontent.com/22369081/199593101-f07ebef9-02ff-47b9-9d62-91a3f7a5a6ca.png">

please help me to fix the issue

**Comment by sweatybridge** [comment]
We have updated self-hosted realtime to v2 recently which should resolve a lot of these issues. Feel free to re-open if this is still reproducible.
