### ISSUE TITLE
.auth.updateUser vs. .auth.admin.updateUserById - Doc improvement

### ISSUE THREAD

**Issue by bobmolgui** [supabase/supabase#10058]
# Improve documentation

## Link 

- https://supabase.com/docs/reference/javascript/auth-updateuser#:~:text=auth.users.user_metadata
- https://supabase.com/docs/reference/javascript/auth-admin-updateuserbyid#:~:text=users.user_metadata%20column.-,Only%20a%20service%20role%20can%20modify.,-The%20user_metadata%20should

## Describe the problem

I'm a bit confused about the documentation of the above two named functions. For .admin.updateUserById it says that auth.users.user_metadata can only be modified by the service role. However, in .auth.updateUser it is also possible for the user to modify auth.users.user_metadata. Which is not 100% correct or I probably miss something here.

## Describe the improvement

In my opinion it would be better if .auth.admin.updateUserById would clearly state that user_metadata can also be changed by the user via .auth.updateUser and not only with the service role. For such examples you should rather use app_metadata.

**Comment by J0** [comment]
Addressed by [this PR](https://github.com/supabase/gotrue-js/pull/618#pullrequestreview-1315892447)
