### ISSUE TITLE
Storage docs responding with 500.

### ISSUE THREAD

**Issue by keer4n** [supabase/supabase#10070]
# Bug report

## Describe the bug

Storage docs link https://supabase.com/docs/guides/storage throws Internal Server Error.

## To Reproduce

Visit the above link.

## Expected behavior

Should show docs webpage.

## Screenshots

<img width="759" alt="Screen Shot 2022-11-03 at 11 57 39 AM" src="https://user-images.githubusercontent.com/8868294/199799021-965d3ef3-76b5-45a3-a068-798c03ebd119.png">

## System information

Browser: chrome 107.0.5304.87

**Comment by GaryAustin1** [comment]
Also https://supabase.com/docs/guides/auth/row-level-security
returning 500.
There are also many formatting issues in the reference docs.

**Comment by Hallidayo** [comment]
Hi both, I seem to be able to access the two links you have sent. Are you able to access?

**Comment by GaryAustin1** [comment]
Yes, Supabase rolled out a fix about an hour or so ago.

**Comment by Hallidayo** [comment]
@GaryAustin1 - Have you got any examples of the formatting issues on the reference docs?

**Comment by GaryAustin1** [comment]
They are fixed also.

**Comment by saltcod** [comment]
Thanks for the catches here all!
