### ISSUE TITLE
Javascript reference pages with multiple code selection blocks don't show if using url fragment (#)

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#10096]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/select#getting-your-data
Note the hash to `getting-your-data`

## Describe the problem
The code panels will not show.
![image](https://user-images.githubusercontent.com/54564956/200046750-d619b74d-5e19-4019-8092-66163fa2aeaa.png)

## Describe the improvement
If you don't use a hash it works as expected, but pointing users to exact part of a page is very useful for discussion and Discord answers.
![image](https://user-images.githubusercontent.com/54564956/200046899-7554d18a-8132-412c-8a2e-d1e2d99773f1.png)

**Comment by saltcod** [comment]
Thanks @GaryAustin1 we resolved this earlier this week.
