### ISSUE TITLE
Email links redirecting back to site are canceled by browser

### ISSUE THREAD

**Issue by Ben-BAP** [supabase/supabase#10114]
# Bug report

## Describe the bug

(Not sure where the problem is on this)

All email's sent by Supabase (eg: Confirm signup, Reset password, etc..) with a link that redirects back to my website are blocked / canceled (by my browser I think?). This was working for me at one point. I am not sure what changed.

### Sample screenshots
The two requests
![image](https://user-images.githubusercontent.com/113811656/200141860-6b568365-45f6-4b3a-8e15-835df8593b89.png)

The canceled request to my site
![image](https://user-images.githubusercontent.com/113811656/200141883-10b4633c-3638-4c80-9284-33e5f3ba710a.png)

## To Reproduce

1. Trigger an email to be sent by Supabase (such as a Password Reset).
2. Click on the `Reset password` link in the email
3. In the browser console, notice in the Network tab that the redirect to the site is canceled by the browser.

## Expected behavior

The redirect to successfully go through Supabase and eventually land on my `redirectTo` URL on my site.

## System information

- **OS:** Windows 10
- **Browser:** Chrome Version 106.0.5249.119 (Official Build) (64-bit)
- **Version of supabase-js:** Not sure? Hosted at app.supabase.com
- **Version of Node.js:** v16.15.1

## Additional information

1. I am using a custom SNMP server. I did disable this momentarily but I see the same issue.
2. Auth > URL configuration 
![image](https://user-images.githubusercontent.com/113811656/200142103-281f3592-51a6-401b-be4a-d99f83a6016f.png)

I also can reproduce this on my other device (a Windows laptop) with:

- **Browser:** Chrome Version 107.0.5304.88 (Official Build) (64-bit)
- **Version of Node.js:** v16.18.0

**Comment by vpuonti** [comment]
I tried to signup to my own Supabase app. 

The email I received shows "You have been invited to create a user on http://localhost:3000. Follow this link to accept the invite:"
<img width="653" alt="image" src="https://user-images.githubusercontent.com/25032592/200651719-47667dc7-5ac2-4ab4-a909-9f3bddcc5a2b.png">

The "Accept the invite"-link does not work, since it contains a redirect to http://localhost:3000.
```
https://{project-id}.supabase.co/auth/v1/verify?token={token}&type=invite&redirect_to=http://localhost:3000 
```
Obviously the link should redirect back to the Supabase URL my project is hosted on, not localhost.

**Comment by GaryAustin1** [comment]
Did either of you solve your issues?
If not you will need to provide more information as these flows in general work.

**Comment by Ben-BAP** [comment]
I have not been able to resolve it. I am not sure what the next steps to try are. I would really appreciate the help!

What do you recommend I try? What more information can I share?

**Comment by GaryAustin1** [comment]
@Ben-BAP you normally need the FULL url including http or https for redirect settings and the siteURL...
![image](https://user-images.githubusercontent.com/54564956/217936661-0e490870-f54a-489f-9a5f-d4f77a87fd86.png)
Not sure if that could cause your error.

**Comment by Ben-BAP** [comment]
Thanks for the suggestion! I added `http://localhost:3000` as you suggested. It doesn't seem to have worked.
![image](https://user-images.githubusercontent.com/113811656/217998677-d5ee51aa-158a-49d7-a6df-026737bdb3ac.png)

The interesting thing I noticed is that if I copy the URL provided in the Password Reset email...
![image](https://user-images.githubusercontent.com/113811656/217998851-ac579b17-11c8-4fdf-9464-102fb406a9e7.png)
```
https://qrurgwmqblahblah.supabase.co/auth/v1/verify?token=blahblahtokenblahblah&type=recovery&redirect_to=localhost:3000
```
And I manually tweak the `&redirect_to=localhost:3000` query parameter to be `&redirect_to=http://localhost:3000` it works! For some reason, it is chopping off the URL scheme in the `redirect_to` param?

---
Just to show I am not crazy, I can show here I am sending the `redirectTo` parameter to Supabase as `http://localhost:3000/app/password-reset`.

![image](https://user-images.githubusercontent.com/113811656/217998640-19a8f0f2-465c-4413-b525-e74139b863ad.png)

**Comment by GaryAustin1** [comment]
What is your siteURL setting?  It looks like you are adding /app/password-reset to the redirect to... that has to also be in the redirect settings list, or it goes to siteURL.  There are wildcard setting options in the redirect settings, but I've not used them, so can't advise on that.  But I think at a minimum you need the entire URL http all the way to password-reset there (if you can't figure out wildcards)

**Comment by Ben-BAP** [comment]
Ah I think that was it! My old Site URL setting was `localhost:3000`. Now it is set to `http://localhost:3000` and it is working!

Thank you very much @GaryAustin1!
