### ISSUE TITLE
Policies only work for lowercase column names 

### ISSUE THREAD

**Issue by danvoyce** [supabase/supabase#10121]
# Bug report

## Describe the bug

I'm getting the following error when I create a new policy.

`Error adding policy: failed to create pg.policies: column "userid" does not exist`

## To Reproduce

I've camel cased all my column names, e.g `userId`. 

I write a new policy e.g 

```
CREATE POLICY "policy_name"
ON public.user-trips
FOR UPDATE USING (
  auth.uid() = userId
) WITH CHECK (
  auth.uid() = userId
);
```

I get the error as stated above.

## Additional context

The solution is to ensure my column names are lowercased. 

I'm admittedly a bit of a noob when it comes to Postgres. However, I'd prefer to use camel case unless anyone can convince me its a bad idea?

Anyways, this feels like a bug of some sort.

**Comment by GaryAustin1** [comment]
You should not use camel case in Postgres, it is discouraged if you have a choice.   The only way it works is if you remember to always use double quotes around it when you create it in SQL or use it.   So you need "userId" in your code above and for any column or table name with caps.   All non double quoted names get converted to lowercase.

It will work with the double quotes, but you will forget at some point and waste time trying to figure out why something is not working.

**Comment by danvoyce** [comment]
Thanks @GaryAustin1. I was kinda thinking that might be the case. 

It feels to me that when naming the table columns maybe we should be warned about the consequences of using any uppercase chars, or simply not be able to add them?
