### ISSUE TITLE
Confirmation email being sent after auth.update() even with email confirmation disabled

### ISSUE THREAD

**Issue by juanantoniosantanamedina** [supabase/supabase#1013]
Afternoon from the UK,

I have disabled the email confirmation in the authentication settings, but when running the code to change the email or password the confirmation email is being sent

Thanks in advance
Juan Antonio Santana

**Comment by awalias** [comment]
very strange, could you send your project ref (the one in your supabase url) to beta@supabase.io along with a link to this issue 🙏

**Comment by HashiW** [comment]
Same Issue here. Disabled email confirmation however error field reads  "Email not confirmed".

**Comment by juanantoniosantanamedina** [comment]
> very strange, could you send your project ref (the one in your supabase url) to [beta@supabase.io](mailto:beta@supabase.io) along with a link to this issue 🙏

I know it's been a while, sorry. 

My project id is ykrxgyvolgibksnsrghd

Thanks

**Comment by kiwicopple** [comment]
this was due to a race condition in the Dashboard, which is now solved 👍
