### ISSUE TITLE
Documentation is broke

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#10157]
# Improve documentation

## Link 

https://supabase.com/docs/reference/cli/usage

## Describe the problem

It looks like the documentation is missing a lot of things. See here:
![](https://cdn.discordapp.com/attachments/881820293298016276/1039272064277807208/image.png)

## Describe the improvement

/

## Additional context

/

**Comment by saltcod** [comment]
Thanks @Olyno I think this is addressed now. I believe the info is there, but agree the styling could be better. We're making some improvements there as we speak!
