### ISSUE TITLE
New vague error on every table save in the Dashboard `Unable to update realtime for <table_name>: Missing publication`

### ISSUE THREAD

**Issue by brentrobbins** [supabase/supabase#10159]
# Bug report

## Describe the bug
Using the Supabase dashboard I recently created a new (pretty basic table) and every time I try to save it I receive the following error: `Unable to update realtime for completed_courses: Missing publication`. This happen if I make a change or not to the table. 

This is also preventing me from enabling Realtime on any new tables as well.

## To Reproduce

While using the Supabase dashboard I tried deleting the table and I didn't make any changes other than giving it a title and when I save it (after the initial save and not making any changes) it shows me the same error.

## Expected behavior

I would expect to save a table and not see this very vague message from showing every time and to be able to enable Realtime on any table. 

## Screenshots
This is what I see after I save the table (with or without any changes)
<img width="393" alt="CleanShot 2022-11-06 at 10 33 08@2x" src="https://user-images.githubusercontent.com/727491/200413785-0174d7a4-2798-481e-88cf-3e050277ad5a.png">

**Comment by chasers** [comment]
@brentrobbins run this query: `select * from pg_publication`

Is there a `supabase_realtime` in the results?

**Comment by w3b6x9** [comment]
@brentrobbins I doubt you did this but just wanted to check. Did you run something like `DROP PUBLICATION IF EXISTS "supabase_realtime"`?

Also, did you recently unpause this project that's missing the publication? If not, can you please detail the significant changes you made to this project in the last few days?

**Comment by w3b6x9** [comment]
@brentrobbins you can try unblocking by creating the publication via the SQL editor: `create publication supabase_realtime;`

**Comment by brentrobbins** [comment]
@chasers 
No results from this query and it looks like `supabase_realtime`  doesn't exist.

@w3b6x9 I did not run that command and no recent changes to this project either. 

Thanks for the advice and I ran `create publication supabase_realtime;` and now I am able to save tables without seeing any errors! Thank you for your help 🙏🏻
