### ISSUE TITLE
.is() in v2 filter reference no longer mentions true,false

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#10160]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/is

## Describe the problem
It is getting somewhat frustrating that the v2 documents keep seeming to drop correct and useful information that was in the v1 reference for no apparent reason.  It is like they were written from scratch, when most could have been copied over.

.is() is used for null, true, false filtering and the new v2 docs only mention null.   
![image](https://user-images.githubusercontent.com/54564956/200429820-f8a71573-35a7-4747-ba23-0a4a2db658ca.png)

## Describe the improvement
Like the old v1 document:

![image](https://user-images.githubusercontent.com/54564956/200429573-bf67fbef-5766-492e-a6f8-ac0190fd6845.png)

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by soedirgo** [comment]
For context: there was a bug in some of the autogenerated parts of our docs - it was missing the description of the methods. It should be fixed now, the description for `.is()` does contain a note on `true` and `false`:

<img width="937" alt="Screenshot 2022-11-14 at 2 56 01 PM" src="https://user-images.githubusercontent.com/31685197/201594647-1973893f-47cd-4428-8b17-7e32a711b469.png">
