### ISSUE TITLE
Custom schema selection on database policies page

### ISSUE THREAD

**Issue by timreibe** [supabase/supabase#10177]
# Custom schema selection on database policies page

## Problem

I created a custom schema named `admin`, for which I'd like to add policies from the dashboard. On the database policies page in the authorization tab, I cannot select the schema and only tables in `public` are shown.

_Edit: Screenshot of policies page_

<img width="1019" alt="Screenshot 2022-11-08 at 15 13 01" src="https://user-images.githubusercontent.com/38082956/200587566-1519fa98-7e78-4eed-9ce9-6264a9b1dd0c.png">

## Solution

I'd suggest to have a dropdown to select from existing schemas as on the database tables pages to configure policies (https://github.com/supabase/supabase/pull/9252).

This is how it can look like (screenshot of database tables page):
![](https://user-images.githubusercontent.com/19742402/193202661-114f4412-d69d-484f-95bc-f37f18f7d5cf.png)

**Comment by Hallidayo** [comment]
Hi @timreibe - Can you not select different schemas from the dropdown? I've had a look and I am able to do so on the policies page?

**Comment by GaryAustin1** [comment]
Did this ever start working for you?  If not is the hosted or local?
Sometimes if a feature is add you have to ctrl f5 to reload the app, but by now you should have had new code if that was something new at the time.  If it is working can you close the issue?  Thanks

![image](https://user-images.githubusercontent.com/54564956/216650265-5755a57b-7b89-4a83-b3a0-c3a5cb7e5bcc.png)

**Comment by timreibe** [comment]
@GaryAustin1 it appears now, I'll close the issue. Thank you! 👍
