### ISSUE TITLE
Incorrect help text

### ISSUE THREAD

**Issue by stevepeak** [supabase/supabase#10196]
https://github.com/supabase/supabase/blob/98b518843dbb2235e36d80ef647e8691cb477cd9/studio/components/interfaces/Auth/Policies/PolicyEditor/PolicyRoles.tsx#L35

I found this to be not true. It defaults to the `public` role and not all roles.

<img width="1139" alt="Screen Shot 2022-11-08 at 12 56 21 PM" src="https://user-images.githubusercontent.com/2041757/200662341-2c52c6b3-bf65-4f69-a0ea-bb90b2fb4bff.png">
<img width="1126" alt="Screen Shot 2022-11-08 at 12 56 25 PM" src="https://user-images.githubusercontent.com/2041757/200662345-b5f122c3-ec3d-44f5-90a4-6bd6bf1a6ba0.png">

> Notice how it says `TO public`

I discovered this because I wanted to create RLS for authenticated users. Therefore needed to change the role to the `authenticated` not "all" or the true default of `public`. Thanks!

**Comment by saltcod** [comment]
Nice one, thanks @Hallidayo
