### ISSUE TITLE
Custom Column Datatype Render Error on Table Editor View

### ISSUE THREAD

**Issue by pavlovcik** [supabase/supabase#10207]
# Bug report

I set the datatype of the column to be char(42) manually using the SQL editor. Now when I want to edit it in the table editor view, it renders in an unexpected way.

## Screenshots

![supabase-error](https://user-images.githubusercontent.com/4975670/200761841-fb1fbc6f-de69-42d4-ae67-f6e2b3030b80.jpg)

## System information

- OS: [e.g. macOS, Windows]
`macOS 13.0 (22A380)`
- Browser (if applies) [e.g. chrome, safari]
`[Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)](https://brave.com/latest/)`
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by saltcod** [comment]
I think we need to check for this field type here and handle it explicitly:

https://github.com/supabase/supabase/blob/master/studio/components/interfaces/TableGridEditor/SidePanelEditor/RowEditor/RowEditor.utils.ts#L158

@pavlovcik could you provide a sql snippet so we can quickly reproduce this one?  Thanks!

**Comment by pavlovcik** [comment]
Here is the wallet snippet that I used

```SQL
ALTER TABLE "Ubiquity Metadata"
ADD wallet_address char(42);
```
