### ISSUE TITLE
BUG: All SQL Queries are gone and cannot be saved anymore

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#10236]
# Bug report

## Describe the bug

I just went to my Supabase (Pro) project and found that all saved queries are gone. Also when creating a new Snippet it says "cannot be saved as you do not have sufficient rights".

What went wrong?

<img width="293" alt="image" src="https://user-images.githubusercontent.com/9058762/201041863-fab6761a-df14-4fc8-88c0-9f1a8c644e4c.png">

**Comment by saltcod** [comment]
Thanks @activenode. This was related to an issue with our infrastructure last week.
