### ISSUE TITLE
Bug: Table Column Sorting Rule

### ISSUE THREAD

**Issue by bricesuazo** [supabase/supabase#10258]
# Bug report

## Describe the bug
Initially, my table column is sorted by "name". But when I renamed the name of that same column from "name" to "role_name", it was still sorted by "name".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Table Editor'
2. Click on 'Create tables'
3. Add column named "column_1" or any column name
4. Add 1 or 2 rows to that column.
5. Sort the table by "column_1"
6. Rename the "column_1" to "column_2"
7. The table is still sorted by "column_1" instead of "column_2"
8. I can't remove the rule.

## Expected behavior
The sorting rule should change or remove if the affected column is changed. The table should now be sorted by "role_name".

## Screenshots
![image](https://user-images.githubusercontent.com/74240706/201243146-7e4855c9-8ff0-4de6-bfcb-f4f60acbb85b.png)
![image](https://user-images.githubusercontent.com/74240706/201243983-eef4a672-4be5-4bbf-ba47-3c59f018c453.png)

## Update: It's fixed when I manually remove my cookies from the browser.
![image](https://user-images.githubusercontent.com/74240706/201244788-b6257cf0-8357-4b01-9176-abb4a3ad7a58.png)

**Comment by raph941** [comment]
This would be resolved as part of this PR #10532

**Comment by MildTomato** [comment]
As mentioned above, PR probably fixed this. Feel free to reopen if it's still an issue. @bricesuazo
