### ISSUE TITLE
Cannot enable extensions after using pgsodium

### ISSUE THREAD

**Issue by nfcampos** [supabase/supabase#10266]
# Bug report

## Describe the bug

Hi, I'm unable to enable any extensions, with the following error "Failed to toggle PG_NET: failed to create pg.extensions: cannot drop view pgsodium_masks.warehouses because extension pg_cron requires it"

I have set up a table (called warehouses) with Transparent Column Encryption enabled for one column.

But surely that shouldn't prevent me from using other extensions?

<img width="1605" alt="Screenshot 2022-11-11 at 14 00 50" src="https://user-images.githubusercontent.com/56902/201355697-893d12c5-458c-49ad-9d5c-b7fb7ac07fba.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use pgsodium as described above
2. Attempt to enable an unrelated extension

## Expected behavior

I expect to be able to enable extensions

## Screenshots

See above

## System information

- OS: macOS
This happens both running supabase locally as well as on the cloud

**Comment by michelp** [comment]
Hello,

The error reported in your description and and the error on your screenshot are not the same, are there any foreign key references from your cron table or pg_net tables to your TCE table?  

There is no really such thing as "togging" an extension in postgres (this is IMO poor wording of the UI), extensions are not stateless switches, they are objects that are `CREATE`ed or `DROP`ed and postgres will not let you drop an extension (or any other object) if other objects depend on it (the first error) or if dropping your extension tries to drop an object that does not belong to the extension (the second error).  Are you triggering DDL operations from either pg_net or pg_cron?  This may cause those extensions to own or attempt to drop objects they don't own.  In either case you'll need to remove the dependency if you want to create or drop those extensions.  This is likely something you'll have to investigate with psql.  Using meta-commands to examine the ownership and dependencies of the objects in question.

**Comment by nfcampos** [comment]
Hi,

No there are no foreign keys between these tables

I can also confirm I'm not triggering any DDL ops from pg_net or go_cron. Note the issue is I'm not able to enable (or in your parlance, `CREATE` it) the extension pg_net, I've reattached a new screenshot, which clearly shows the error message (along with pg_net in state disabled in the UI, thus the "toggle" action is to enable it, not to disable it).

Therefore, let me summarise, I'm unable to enable pg_net because doing so attempts to drop something related to pgsodium? Surely that doesn't sound quite right, enabling one extension shouldn't drop anything I'd hope

<img width="1605" alt="Screenshot 2022-11-11 at 19 18 23" src="https://user-images.githubusercontent.com/56902/201414606-432e4736-12d5-40f4-b582-24206b3dac5f.png">

**Comment by michelp** [comment]
Ok I've investigated this further and can reproduce it, the issue is an unexpected intersection between the desuperusing work and an overly broad event trigger in pgsodium that is firing too aggressively.  The short term fix would be to disable the event trigger so that it does not fire when extensions create objects.  I'm not 100% certain why pg_cron is involved, but I suspect you created pg_cron before the desuperuser changes, and that ended up owning the view when it inadvertently fired the trigger, but now that you are not superuser and creating pg_net is firing the trigger, which causes that specific error.  I'll investigate a bit further and get back to you on this thread.

**Comment by nfcampos** [comment]
@michelp thanks for looking into this, fyi if it helps I get a similar error when running the following command 

```
alter table model_metrics
  drop constraint model_metrics_operation_valid;
```

```ERROR: cannot drop view pgsodium_masks.warehouses because extension pg_cron requires it Hint: You can drop extension pg_cron instead. Where: SQL statement " DROP VIEW IF EXISTS pgsodium_masks.warehouses; CREATE VIEW pgsodium_masks.warehouses AS SELE ...```

**Comment by michelp** [comment]
We disabled your event trigger, can you try again?  I'm rolling a fix this week so that this does not occur again, for now I'll keep this bug open until we confirm the prod fix.  Thanks for catching this!

**Comment by nfcampos** [comment]
great, thank you, I was able to run the above now

**Comment by michelp** [comment]
Customer reports issue resolved.
