### ISSUE TITLE
auth.email() function not exist in row-level security policy

### ISSUE THREAD

**Issue by d-mok** [supabase/supabase#1028]
# Bug report

## Describe the bug

When I set a row-level security policy using the function auth.email(), it says:
function auth.email() does not exist

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a table
2. set a row-level security policy for that table
3. set the definition to be "right(auth.email(), 13) = '@blizzard.com'" for example
4. click 'save'
5. see error: function auth.email() does not exist

## Expected behavior

no error, policy saved successfully

## Screenshots

![image](https://user-images.githubusercontent.com/49301824/113321280-053fe780-9346-11eb-91c2-616393447157.png)
![image](https://user-images.githubusercontent.com/49301824/113321380-1c7ed500-9346-11eb-93cd-44fd1faa0b53.png)

## System information

- OS: Windows 10
- Browser: chrome

**Comment by steve-chavez** [comment]
For now you can create the function yourself:

```sql
create or replace function auth.email() returns text as $$
  select nullif(current_setting('request.jwt.claim.email', true), '')::text;
$$ language sql;
```

**Comment by kiwicopple** [comment]
If anyone else is experiencing this, it's likely because you're on a very old database. We didn't run this as a migration across all of the projects. 

I will transfer this over to Discussions so that it's easy to find in the future
