### ISSUE TITLE
Auth Custom SMTP Error

### ISSUE THREAD

**Issue by ccostes** [supabase/supabase#10294]
# Bug report

## Describe the bug

`/otp` fails to send new user validation emails when Custom SMTP server configured with error indicating an extra `:` is being added after the port number.
```
Error sending confirmation email: dial tcp: address http://smtp.gmail.com:587: too many colons in address
```

## To Reproduce

1. In Auth Settings, enable Custom SMTP and set `Host` to `http://smtp.gmail.com` and `Port number` to `587`
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1827332/201529935-465569b0-249d-4252-82fa-4b9e798efe36.png">
2. Attempt to sign up as a new user - results in `Error sending confirmation mail` alert.

## Expected behavior

Verification email sent to new user email.

## System information

- Using Managed Supabase
- Version of supabase-js: `2.0.5`
- Version of Node.js: `18.11.9`

**Comment by GaryAustin1** [comment]
Try without `http://`

**Comment by ccostes** [comment]
That worked, thanks!
