### ISSUE TITLE
deleteUser not fire USER_DELETED event in onAuthStateChange #3049

### ISSUE THREAD

**Issue by kav** [supabase/supabase#10309]
# Bug report

## Describe the bug

No `USER_DELETED` event is fired when a user is deleted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Listen to `supabase.auth.onAuthStateChange`
2. Delete a user.
3. No event is triggered

## Expected behavior

`USER_DELETED` event is fired when a user is deleted.

## Additional context

`USER_DELETED` exists on `AuthChangeEvent` here:
https://github.com/supabase/gotrue-js/blob/a441eef4d7291ec20b756cde99ccee87329594d0/src/lib/types.ts#L34

This a re-activation per https://github.com/supabase/supabase/issues/3049#issuecomment-1312936597

**Comment by j4w8n** [comment]
There is no code which notifies of a USER_DELETED event. To my knowledge, nothing done with the GoTrueAdminApi triggers events - only GoTrueClient. The type doc [here](https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/lib/types.ts#L21) is wrong.

https://github.com/supabase/gotrue-js/pull/530#issuecomment-1306913333

**Comment by kangmingtay** [comment]
Hey @j4w8n, thanks for catching this, yeah we should be emitted the "USER_DELETED" event on the `auth.admin.deleteUser` method

**Comment by j4w8n** [comment]
Wait... @kangmingtay, your wording is confusing me. I'm guessing you meant to say "emitting" but want to clarify. Should this event get sent or no?

**Comment by kangmingtay** [comment]
yeah @j4w8n i meant emitting 😅

**Comment by kangmingtay** [comment]
Was just thinking how to do this in `GoTrueAdminApi.ts` since the `_notifyAllSubscribers` method and the session is only available in `GoTrueClient.ts`. 

Also, since the `deleteUser` method can only be called on the server-side by an admin, i don't really see a use case in emitting the "USER_DELETED" event since one can immediately handle any side-effects after `deleteUser` is called. 

Lmk what you think!

**Comment by kav** [comment]
Is there not a way to notify the client that the user it is associated with has been deleted? This is the expectation I'd have given the current incorrect docs and is a fairly important use case with respect to terminating things client side and cleaning up

**Comment by j4w8n** [comment]
@kangmingtay, I can take a look tomorrow; but what you said is why I initially assumed the docs were wrong, rather than the feature just not being coded.

**Comment by j4w8n** [comment]
@kav, the server doesn't have that type of relationship with the client - at least not that I know of. Even when the server is pushing info to the client, it's because the client initiated the communication in some way.

I need to think about this a bit more tomorrow.

**Comment by kangmingtay** [comment]
@kav  

> Is there not a way to notify the client that the user it is associated with has been deleted?

You can already do this by looking at the response returned. The `deleteUser` method returns the details of the deleted user if it's successful.

**Comment by kav** [comment]
Assuming the delete was triggered by the user themselves on the only client with which they are connected but neither of those assumptions hold in general.

**Comment by j4w8n** [comment]
@kav I've run through a few scenarios in my head; but none of them required emitting this event in order to tidy up on the client-side afterward.

Can you clarify your scenario(s) where emitting a `USER_DELETED` event would help you out?

**Comment by alaister** [comment]
I'm going to go ahead and close this. Please don't hesitate to reopen if you have more to add to the conversation.

**Comment by kav** [comment]
@alaister could you remove the enum value and update the documentation. This is a footgun since everything appears to work from the enum and docs but does not.
