### ISSUE TITLE
column names getting changed to lowercase

### ISSUE THREAD

**Issue by topperspal** [supabase/supabase#10304]
I created a table with column names in camelcase but supabase converts it to smallcase.

for example-
```sql
create table someTable (
  id bigint generated by default as identity primary key,
  insertedAt timestamp with time zone default timezone('utc'::text, now()) not null -- converted to insertedat
);
```

Please also check it for table names.
ThannkU:)

**Comment by GaryAustin1** [comment]
You should not use capital letters in Postgres for column, table, or function names  (has nothing specific to do with Supabase).  If you must have capital letters then you must always surround them with double quotes.  “myName”

You will forget to do this and waste time debugging.
