### ISSUE TITLE
Migration following documentation results in error:  cannot drop constraint sessions_pkey on table auth.sessions because other objects depend on it

### ISSUE THREAD

**Issue by jopfre** [supabase/supabase#10312]
# Improve documentation

## Link 

https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects

## Describe the problem

I am following this guide, which I believe is the most current (correct me if I'm wrong). I am trying to migrate dev to staging. Dev has had a few weeks development on it with some public tables, auth users, rls policies, db functions. Staging is a clean supa base install.

When I run the commands in the docs I get the error:

```
psql:dump.sql:70: ERROR:  cannot drop constraint sessions_pkey on table auth.sessions because other objects depend on it
DETAIL:  constraint sso_sessions_session_id_fkey on table auth.sso_sessions depends on index auth.sessions_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

Ok so I add 

`ALTER TABLE IF EXISTS ONLY "auth"."sessions" DROP CONSTRAINT IF EXISTS "sessions_pkey" CASCADE;`

Then I get:

`psql:dump.sql:193: ERROR:  must be member of role "supabase_admin"`

So I comment out the line:

`--ALTER TYPE "public"."app_permission" OWNER TO "supabase_admin";`

And then there is another of the same error a few lines down.

I'm wondering if you have more sed rules to adjusts for this or if this method of migration is out of date and now there is a new method? Otherwise I will just write some more sed rules myself but feels quite clunky.

## Describe the improvement

Adjust the commands in the docs so that migrations can run without error or suggest a different method.

## Additional context

N/A

**Comment by jopfre** [comment]
I got this working in the end by running

`ALTER ROLE postgres SUPERUSER`

on the db being migrated to (in my case staging)

Adding an extra sed replace

`| sed 's/ALTER TABLE IF EXISTS ONLY "auth"."sessions" DROP CONSTRAINT IF EXISTS "sessions_pkey";/ALTER TABLE IF EXISTS ONLY "auth"."sessions" DROP CONSTRAINT IF EXISTS "sessions_pkey" CASCADE;/' \`

to the pgdump

```
pg_dump --clean \
  --if-exists \
  --quote-all-identifiers \
  --exclude-table-data 'storage.objects' \
  --exclude-schema 'extensions|graphql|graphql_public|net|pgbouncer|pgsodium|pgsodium_masks|realtime|supabase_functions|pg_toast|pg_catalog|information_schema' \
  --schema '*' \
  -d postgres -h db.[YOUR_DB_URL].supabase.co -p 5432 -U postgres \
  | sed 's/^DROP SCHEMA IF EXISTS "auth";$/-- DROP SCHEMA IF EXISTS "auth";/' \
| sed 's/^DROP SCHEMA IF EXISTS "storage";$/-- DROP SCHEMA IF EXISTS "storage";/' \
| sed 's/^CREATE SCHEMA "auth";$/-- CREATE SCHEMA "auth";/' \
| sed 's/^CREATE SCHEMA "storage";$/-- CREATE SCHEMA "storage";/' \
| sed 's/^ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/' \
| sed 's/ALTER TABLE IF EXISTS ONLY "auth"."sessions" DROP CONSTRAINT IF EXISTS "sessions_pkey";/ALTER TABLE IF EXISTS ONLY "auth"."sessions" DROP CONSTRAINT IF EXISTS "sessions_pkey" CASCADE;/' \
> dump.sql
```

running `psql` as documented

then running

`ALTER ROLE postgres NOSUPERUSER`

on the db being migrated to (in my case staging)

If this is the correct procedure please update the docs with the above (I can submit a pr if you prefer)

**Comment by anngbaum** [comment]
I encountered the exact same issues outlined here when trying to follow the docs.

for what it's worth, the docs also recommend for `pg_dump` to use:
`--dbname "$OLD_DB_URL" `

though I was only able to make that work with the same command as you did:
`-d postgres -h db.[YOUR_DB_URL].supabase.co -p 5432 -U postgres \`

somehow my personal credentials as a user were getting looped in, so at a minimum the `-U postgres` seems worth specifying in the code sample documentation (unless I'm really misunderstanding something).

**Comment by jopfre** [comment]
Yes I also had the same issue and needed to specify each part separately. Perhaps an example of the form of the old_db_url would be helpful as copying and pasting from supabase ui didn't seem to work.

**Comment by jopfre** [comment]
I figured out the usage with --dbname.

The issue was my db password contained `@` characters. These need to be encoded otherwise pg_dump thinks it is the start of the host. You can encode here https://www.urlencoder.org/ if needed.

Perhaps the connection string in the UI could be changed form [YOUR-PASSWORD] to [YOUR-URI-ENCODED-PASSWORD] and make a mention of this gotcha in the docs.
