### ISSUE TITLE
Sign In GitHub - Failed

### ISSUE THREAD

**Issue by TuColegaDev** [supabase/supabase#10316]
# Error when I try to login with my GitHub account

## Describe the bug

I tried to login on my existing supabase account with my GitHub, but recently I changed my GitHub default email. I think maybe that be the problem.
 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'github.com' 
2. Click on 'Settings'
3. Change your default login email
4. Go to 'supabase.com'
5. Try to Sign In with Github

## Expected behavior

The app is loading for a while, and then show the login page again. I don't know if this a general error or only to my account. But I think its an important bug to report.

**Comment by yeganathan18** [comment]
Hey @AMDevelopOB 

Thanks for reporting the bug, can you please look up the `network` tab after sign-in? And provide the screenshot of the same here.

Maybe we can check which request is getting failed, and what's the error more precisely.

**Comment by pucke-uninow** [comment]
<img width="1511" alt="Screenshot 2022-11-23 at 11 05 15" src="https://user-images.githubusercontent.com/64527676/203519690-0a4109c8-49c5-4859-af68-326693e0a2af.png">

Response:
```json
{
    "message":"Failed to update user's profile",
    "errorEventId":"c26cd216c0ab409eade2112a08f76138"
}
```

**Comment by kiwicopple** [comment]
Hey all, if you experience this issue, please reach out to our support team: https://supabase.com/support
