### ISSUE TITLE
Function task timeout error on create or update

### ISSUE THREAD

**Issue by mimranzulkfal** [supabase/supabase#10337]
Hi there!

I'm using graphql functions and supabase db. One thing is weird, When I set reminder time or update it, only one field isn't updating. Also not getting data from endpoint (https://api.morningselfapp.com/.netlify/functions/graphql) as timeout error occoured which is stated below:

Task timed out after 10.01 seconds

**Comment by awalias** [comment]
thanks for the report @mimranzulkfal ! We'll need some more details on your setup and code so we can help debug. Do you have an example so we can reproduce the bug on our side?

**Comment by awalias** [comment]
oh I see you've already opened an issue for this one: https://github.com/supabase/supabase/issues/10311

feel free to reopen with details if this is a separate issue
