### ISSUE TITLE
Table editor filter operator changes back to first option (equals) when entering filter value

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#10334]
https://user-images.githubusercontent.com/19742402/201868423-97d6a0b9-4930-4b3f-b67e-a1908e4198ae.mov

**Comment by TMisiukiewicz** [comment]
hello @joshenlim, is it still available to work on? if yes, i'd like to try and fix it :)

**Comment by joshenlim** [comment]
@TMisiukiewicz oh yes! still available to work on :) thank you so much! 🙏
