### ISSUE TITLE
Table editor: filter on date not workign sometimes

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#1036]
# Bug report
Table editor > Filter > Add a filter > Select a date column > GT or GTE > paste a date > "Apply" button is disabled

Workaround: switch filter type from GT / GTE to EQ (while the date is still populated) > switch back to GT / GTE > "Apply" is enabled now

**Comment by phamhieu** [comment]
Hi @peachp, we updated the dashboard app recently. Table editor filter will be applied automatically on create/update.

**Comment by peachp** [comment]
@phamhieu thanks!
