### ISSUE TITLE
Most settings not available on selfhosted instance?

### ISSUE THREAD

**Issue by FOREVEREALIZE** [supabase/supabase#10386]
# Bug report

## Describe the bug

For some reason, I cannot access most of the settings on my Docker Selfhosted instance

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a selfhosted instance
2. Notice that most options are not available
![imatge](https://user-images.githubusercontent.com/60579848/202518425-3753188f-0d1b-45b0-9107-7d15143201c0.png)

## Expected behavior

Many more options being available (screenshot from Supabase docs)
![imatge](https://user-images.githubusercontent.com/60579848/202518700-f84916df-3235-43b6-9216-f677e3216c79.png)

## System information

- OS: Docker Linux
- Version of supabase containers: as listed in the docker-compose.yml

**Comment by globemediaofficial** [comment]
This sin't new, it's been an issue for a while. Almost all configurations have to be added manually in `.env`.

**Comment by FOREVEREALIZE** [comment]
How would I go about doing that? Is there another GH Issue explaining it? Maybe a wiki entry?

**Comment by globemediaofficial** [comment]
Unfortunately Supabase documentation for self-hosting doesn’t explain all the variables. By default, mail config is in the `.env`, and not much else. For every configuration you want to set, you’ll have to search through issues on her to find the variables to add. You can also say what you want to add here and I’ll try to find it.

**Comment by FOREVEREALIZE** [comment]
Well, pretty much I would like to enable as many things as possible. So OAuth providers, analytics and everything else. Basically I would like to get it as close as possible to the Hosted Supabass

**Comment by globemediaofficial** [comment]
For OAuth here is what you need:

> We support apple, azure, bitbucket, discord, facebook, github, gitlab, google, keycloak, linkedin, notion, spotify, slack, twitch, twitter and workos for external authentication.
> 
> Use the names as the keys underneath external to configure each separately.
> 
> GOTRUE_EXTERNAL_GITHUB_ENABLED=true
> GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=myappclientid
> GOTRUE_EXTERNAL_GITHUB_SECRET=clientsecretvaluessssh
> GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=http://localhost:3000/callback

You just replace `GITHUB` in each of those lines with the provider you are trying to set up and replace the values with your keys. 

I'm not sure about analytics but it's important to understand that you will not be able to perfectly recreate the hosted service. You cannot setup functions, storage is difficult to get going (because they don't have it in the studio, and settings are not as easy to change.

**Comment by FOREVEREALIZE** [comment]
Okay thanks
