### ISSUE TITLE
404 in today's blog post

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#1040]
# Bug report

## Describe the bug

In the "Workflows are coming to Supabase" blog post, the link at the end that leads to Hex results in a 404 error.

https://hexdocs.pm/workflows/readme.html

## To Reproduce

1. Go to https://supabase.io/blog/2021/04/02/supabase-workflows
2. Scroll down to the very end of the post
3. Click on the link "It's built with Elixir, so you can find it on Hex here".
4. See the 404 on HexDocs.

## Expected behavior

Should not be a 404.

## Screenshots

<img width="910" alt="Screen Shot 2021-04-02 at 8 54 12 AM" src="https://user-images.githubusercontent.com/5659171/113431712-021e1900-9391-11eb-9fb2-37d83e5b67a1.png">

## System information

- OS: macOS 11.2
- Browser: Brave 1.22.70

## Additional context

Really like the concept of workflows!

**Comment by inian** [comment]
Thanks for the report @Nick-Mazuk Fix going out now
