### ISSUE TITLE
Module not found - functions serve

### ISSUE THREAD

**Issue by Huge-Puppy** [supabase/supabase#10403]
# Bug report

## Describe the bug
When trying to serve my edge function locally, I get the following error.

<img width="524" alt="Screen Shot 2022-11-18 at 8 12 55 AM" src="https://user-images.githubusercontent.com/32687987/202737355-8c52dcf3-ceb9-447f-a48c-4c2f6d4f75f0.png">

## To Reproduce

1. Clone repo from https://github.com/Huge-Puppy/personal-website-1
2. Run `supabase start`
3. Run `supabase functions serve ai-request --debug`

## Expected behavior

Edge function should be served locally for testing.

## System information

- OS: macOS 12.6
- Version of supabase: 1.14.0
- Version of Node: 18.9.0
- Docker version 20.10.21, build baeda1f

**Comment by Nash0x7E2** [comment]
Also running into this issue albeit with a slightly different use-case. 

For me, the error occurs when deploying an Edge Functions containing an NPM package (Express in my case). 

Logs:
```shell 
❯ supabase functions deploy api --debug
Bundling api
Error: Error bundling function: exit status 1
file:///src/index.ts
error: Uncaught (in promise) Error: Module not found "npm:express".
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)

**Comment by laktek** [comment]
@Huge-Puppy I tried to reproduce the bug, the function in the provided repo is named `ai-response`, while you try to serve `ai-request`. I guess that's the issue?

@Nash0x7E2 Deploying functions with `npm` modules are currently not supported. Unfortunately, we cannot provide an ETA for npm support at the moment.

**Comment by Huge-Puppy** [comment]
Make sure you are using the correct name for your function! haha.
Thank you so much for the help @laktek ! Not sure how I missed that.
