### ISSUE TITLE
`ilike` examples show `like` instead of `ilike`

### ISSUE THREAD

**Issue by N00nDay** [supabase/supabase#10417]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/reference/javascript/ilike)

## Describe the problem

Examples show `like(...` when they should show `ilike(...`

## Describe the improvement

Update the filter name

## Additional context

I would have made the changes and submitted a PR myself as it is a simple fix but I could not find where the documentation for that page is located. Where is this located in the future and I would be happy to contribute.

**Comment by Hallidayo** [comment]
Hi @N00nDay - Thankyou for submitting the issue, for reference the v2 documentation is located in `spec/supabase_js_v2.yml`
