### ISSUE TITLE
Newest supabase docker image (0.22.11) requires login

### ISSUE THREAD

**Issue by thilojaeggi** [supabase/supabase#10434]
I just setup supabase self-hosted with the docker image 0.22.11 and using the example .env file.
If I now access studio, it requires a login but I'm unable to create an user or sign in with the error message "Failed to fetch".

Is there any default login or do I have to define it somewhere?

Thanks.

**Comment by Hallidayo** [comment]
Yeah I'm having the same issue with the recent changes.

**Comment by mats16** [comment]
It seams that newest Supabase Studio works with Supabase Auth.

You need to configure env `SUPABASE_URL`. If you want to use GitHub federation, need to configure   env`GOTRUE_EXTERNAL_GITHUB_XXX` at gotrue.

**Comment by thilojaeggi** [comment]
But how after registering would I assign the necessary permissions?

**Comment by vbylen** [comment]
I'm getting an ```invalid authentication credentials``` error when signing up users locally. 

This is on supabase/cli `v1.15`

**Comment by princemaple** [comment]
> I'm getting an `invalid authentication credentials` error when signing up users locally.
> 
> This is on supabase/cli `v1.15`

Same. Getting the error when trying to `signUp` and `signInWithOtp` on a fresh start. `enable_signup` is `true` for both `[auth]` and `[auth.email]`. Please take a look, thanks!

**Comment by vincelwt** [comment]
I'm also having `failed to fetch` with the newest image & supabase-js@2.1, but on the backend with the service key. Trying the http queries in curl with the same url/headers works fine.

**Comment by vbylen** [comment]
hi @sweatybridge, would you like to move this issue to https://github.com/supabase/cli?

**Comment by sweatybridge** [comment]
Our frontend team is aware of this issue and is currently working on a fix. 

We will update here when a new version is ready. The last working version is still `0.22.08`. 

Thank you all for your patience.

**Comment by point-source** [comment]
@sweatybridge I am also having this issue preventing sign up / sign in. What is the best way to downgrade the image? Will downgrading my version of supabase-cli work or do I need to do something in docker?

**Comment by sweatybridge** [comment]
@point-source Both the [CLI](https://github.com/supabase/cli/blob/main/internal/utils/misc.go#L36) and [self-hosted](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L12) are currently on version `0.22.08` of Studio. If you have upgraded the image yourself, you can downgrade by reverting any local changes to match our main/master branch.

**Comment by princemaple** [comment]
Confirm that updating the anon key fixes it. Didn't expect that to change.

**Comment by sweatybridge** [comment]
If you don't want to hardcode the anon key, you can also let the CLI generate an env file dynamically

```bash
supabase status -o env --override-name auth.anon_key=CUSTOM_ANON_KEY
```

`--override-name` is used to change the [default variable](https://github.com/supabase/cli/blob/main/internal/status/status.go#L25) names.

**Comment by ScarVite** [comment]
while being on `0.22.11` and trying to register, while having email auth enabled i do not get `invalid authentication credentials` like everybody else, i am getting a 404, with the default 404 html page being returned at `http://localhost:3000/api/signup` when clicking "Sign up".

So updating anon key, does not help my issue at all, which means i am forced to downgrading for now.

Looking forward to a fix 😄

**Comment by Hallidayo** [comment]
Has anyone found a work around for this issue whilst running the studio on port 8082(http://localhost:8082/)?

I used to be able to just go to http://localhost:8082/project/default without ever signing in but now I just get redirected back to http://localhost:8082/sign-in, Then I get the same as others have mentioned where I can not use Github sign in or create a local user?
