### ISSUE TITLE
Buckets are gone after pausing

### ISSUE THREAD

**Issue by paranoyakfotografci** [supabase/supabase#10439]
When project are paused and then restarted, all bucket, policies and even data is gone. At the right top of the screen, internal server error  message is displayed.

**Comment by saltcod** [comment]
Hi @paranoyakfotografci sorry for the delay in reply on this one. When you refresh those pages do things restore back to normal?

**Comment by paranoyakfotografci** [comment]
nope, gives same error message every time I refresh

Terry Sutton ***@***.***>, 20 Ara 2022 Sal, 18:09 tarihinde
şunu yazdı:

**Comment by saltcod** [comment]
Are you self-hosting this or is it on the hosted studio?

**Comment by paranoyakfotografci** [comment]
I assume hosted studio means vanilla Supabase storage. If so yes, it was
Supabase, I can share project details if it helps but I deleted
everything and set it up from scratch



Terry Sutton ***@***.***>, 20 Ara 2022 Sal, 22:06 tarihinde
şunu yazdı:

**Comment by saltcod** [comment]
Sorry @paranoyakfotografci — I mean are you hosting Supabase yourself using Docker and all, or are you using our hosted version at app.supabase.com?

**Comment by paranoyakfotografci** [comment]
Sorry for late response, it was app.supabase.com

20 Ara 2022 Sal 23:14 tarihinde Terry Sutton ***@***.***>
şunu yazdı:

**Comment by GaryAustin1** [comment]
Sounds like the OP deleted the instance and started over.  There have been no ongoing reports of storage missing after pause restore in the user forums, although I don't know about support channel.
I'm going to close this, but if you think it should be left open (OP and saltcod) please add a comment here.
