### ISSUE TITLE
Hidden buckets are exist even tough Supabase says "No buckets"

### ISSUE THREAD

**Issue by paranoyakfotografci** [supabase/supabase#10440]
# Bug report

## Describe the bug  - and Produce

After reviving project from pausing, buckets are seems to be gone and it says "No buckets available". Then  when I try to create a new bucket named exactly old missing bucket, it says "Resource is already exists".

## Expected behavior

After reviving paused project, my buckets shouldn't have gone.

## Screenshots

![image](https://user-images.githubusercontent.com/45828466/203120161-55fc9d26-da8e-4ceb-bc41-a18aa28bc1bf.png)
![image](https://user-images.githubusercontent.com/45828466/203120354-b294e8fe-b717-4850-b7c3-a3727ee28b9b.png)

## System information

- Win10
- Chrome
- Flutter dart

**Comment by GaryAustin1** [comment]
You can verify if all your storage stuff is still there by using the table UI and selecting the storage schema.  You should see buckets and objects tables with the data.

This does not resolve the issue on why storage UI is not seeing them, but should mean you have not really lost anything.

You would probably have to contact support to resolve why you can't see them with the normal method.

**Comment by GaryAustin1** [comment]
Did you resolve this?  I'm going to close this for now as I assume it was a glitch at the time and support resolved or you figured it out as not response since then.
Feel free to comment if it needs to be reopened.  Thanks
