### ISSUE TITLE
docker-compose run doesn't work

### ISSUE THREAD

**Issue by randomloops** [supabase/supabase#10453]
I was trying to run supabase for the first time, but I am unable to run it via `docker-compose up`

### ERROR
`ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/`

I didn't changed anything inside `docker-compose.yml`

`docker-compose version 1.25.0, build unknown`
`Docker version 20.10.21, build baeda1f`

**Comment by TobiasGrether** [comment]
Try to run it using `docker compose up -d`.
