### ISSUE TITLE
emailRedirectTo on generateLink() not working

### ISSUE THREAD

**Issue by bzmillerboy** [supabase/supabase#10469]
# Bug report

## Describe the bug
When including `emailRedirectTo` value in the `generateLink()` of type 'signup', the returned 'action_link' and 'redirect_to' values contain my site url instead of the specified `emailRedirectTo` value. Even when this url is whitelisted (listed in the Redirect URLs) in the dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
```
  const { data, error } = await supabase.auth.admin.generateLink({
    type: "signup",
    email: email,
    options: {
      password: "password",
      data: {
        first_name: firstName,
        last_name: lastName,
      },
      emailRedirectTo: "https://portal.my-domain.com",
    },
  });
```

## Expected behavior

The response to use the emailRedirectTo value instead of my site url.

This is what I get:
```
generateLink data {
  properties: {
    action_link: 'https://alkdjflskdjflwemnfoijsnelfk.supabase.co/auth/v1/verify?token=c575asda4fa3sd54gad35f4ad35f1asd3f1a3d5f1a3sd5&type=signup&redirect_to=https://www.my-domain.com',
    email_otp: '313413584',
    hashed_token: 'c575asda4fa3sd54gad35f4ad35f1asd3f1a3d5f1a3sd5',
    redirect_to: 'https://www.my-domain.com',
    verification_type: 'signup'
  },
     ...
```

This is what I expect:
```
generateLink data {
  properties: {
    action_link: 'https://alkdjflskdjflwemnfoijsnelfk.supabase.co/auth/v1/verify?token=c575asda4fa3sd54gad35f4ad35f1asd3f1a3d5f1a3sd5&type=signup&redirect_to=https://portal.my-domain.com',
    email_otp: '313413584',
    hashed_token: 'c575asda4fa3sd54gad35f4ad35f1asd3f1a3d5f1a3sd5',
    redirect_to: 'https://portal.my-domain.com',
    verification_type: 'signup'
  },
     ...
```

## System information

- OS: macOS
- Version of supabase-js: "@supabase/supabase-js": "^2.1.0",
- Version of Node.js: 18.12.1

**Comment by GaryAustin1** [comment]
I think the parameter is named redirectTo for generatelink()
From the source in gotrue-js:
@param options.redirectTo The redirect url which should be appended to the generated link

**Comment by bzmillerboy** [comment]
Thanks for the tip @GaryAustin1. I can confirm this code now works as expected.

```
  const { data, error } = await supabase.auth.admin.generateLink({
    type: "signup",
    email: email,
    options: {
      password: "password",
      redirectTo: "https://portal.my-domain.com",
      data: {
        first_name: firstName,
        last_name: lastName,
      },
    },
  });
```
