### ISSUE TITLE
"session_user" value is inconsistent between hosted and local versions

### ISSUE THREAD

**Issue by point-source** [supabase/supabase#10470]
# Bug report
I have a psql function which references the "session_user" variable to differentiate between being called by an authenticated user and a trigger. The function is "is_claims_admin()" from [this guide](https://github.com/supabase-community/supabase-custom-claims);

I noticed my rls policies were passing on local and failing on dev. After [troubleshooting this on discord](https://discord.com/channels/839993398554656828/1044658084624212038), I noticed that my hosted production isntance is returning "authenticator" for the session_user value while my local dev is returning "postgres".

## Steps to reproduce:

1. Create a local supabase instance: `supabase init` (for local)
2. Create a function which can be used to get the value of session_user with an authenticated session:
```
CREATE OR REPLACE FUNCTION public.sesh()
	RETURNS text
	LANGUAGE plpgsql
AS $function$
	BEGIN
		return session_user;
	END;
$function$
```
4. Create a user on the supabase instance:
```
curl -X POST 'http://localhost:54321/auth/v1/signup' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "eORzCgpVRYTyIVmipLnY"
}'
```
6. Sign in as the user and get the jwt:
```
curl -X POST 'http://localhost:54321/auth/v1/token?grant_type=password' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "eORzCgpVRYTyIVmipLnY"
}'
```
8. Issue a rest api call with the jwt and call the function:
```
curl -X POST 'http://localhost:54321/rest/v1/rpc/sesh' \
-H "Content-Type: application/json" \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs" \
-H "Authorization: Bearer ${USER_JWT_HERE}"

```
9. Observe that the output is "postgres"
10. Repeat steps with a hosted isntance of supabase
11. Observer that the output is "authenticator"

## Expected behavior

Supabase hosted and local versions should behave the same in order for local dev environments to be useful.

## System information

- OS: macOS 13.0.1
- Version of supabase-cli: 1.14.3

**Comment by GaryAustin1** [comment]
@steve-chavez 
Was just working on this with the op.  What is the implication of PostgREST running as postgres instead of authenticator.  Sort of worried that will bypass all RLS in addition to the problem the op mentions...

**Comment by GaryAustin1** [comment]
It looks like this was "fixed" 22 days ago and has always been postgres user up until this point?

[chore: update self hosted to use latest postgres image (https://github.com/supabase/supabase/pull/9973)](https://github.com/supabase/supabase/commit/eae6905d428cc071a4dc458f3a49656c4353d18d)

![image](https://user-images.githubusercontent.com/54564956/203422983-d2eff97d-2535-43f0-ba36-78947c26a1ff.png)

I'm going to assume then that RLS must still work if Postgrest role was `postgres` instead of `authenticator` as it has been that a way a long time.  Otherwise that would have been really bad news.

But the OP's use of another Supabase employee's guide (linked in their post) for custom claims has not been used on local hosting because it relied on `authenticator` as the session user, other wise bypasses it's RLS check.

**Comment by steve-chavez** [comment]
> I'm going to assume then that RLS must still work if PostgREST role was postgres instead of authenticator as it has been that a way a long time.

Yes, because the role would be changed to `anon` or `authenticated` for every request.

> Was just working on this with the op. What is the implication of PostgREST running as postgres instead of authenticator.

It shouldn't use the `postgres` role(as mentioned on the [docs](https://postgrest.org/en/stable/auth.html#authentication-sequence)).

**Comment by GaryAustin1** [comment]
Thanks Steve
> It shouldn't use the `postgres` role(as mentioned on the [docs](https://postgrest.org/en/stable/auth.html#authentication-sequence)).

If I followed the source code correctly, the Docker version has been using `postgres` up until 22 days ago.  Sounds like only an application using the session_user like @burggraf 's claims code would have been impacted all this time.

**Comment by point-source** [comment]
Would that new docker image be released already or is it still in a pipeline somewhere? I pulled latest yesterday and am still getting "postgres" as the session_user

**Comment by point-source** [comment]
@barbinbrad Well you can sort of workaround it by changing the $POSTGRES_USER env variable on the db container but that's not particularly streamlined vs running the supabase cli

**Comment by burggraf** [comment]
So is this fixed?  I just tested in the hosted version of Supabase:

```sql
CREATE OR REPLACE FUNCTION get_session_user() RETURNS text
  LANGUAGE plpgsql 
  AS $$
  BEGIN
    return session_user;
  END;
  $$;
```      
In hosted Supabase, when calling this via `.rpc()` from the javascript client, it always returns `authenticator` whether or not the user is logged in (roles AUTH or AUTHENTICATED).

Does this return `postgres` if run on a self-hosted project (and called via .rpc() from the javascript client?)

**Comment by GaryAustin1** [comment]
Can someone on this thread confirm if this issue has been resolved in self-hosted/local dev?
Based on this line I believe it has https://github.com/supabase/supabase/blob/79528dfabcc44b56775834fa468be5937104f141/docker/docker-compose.yml#L108 but I don't do local development.

The change... 
![image](https://user-images.githubusercontent.com/54564956/217976357-56e9136f-478a-437c-a9bb-74ef386de953.png)


Would be good to close this issue if so.

**Comment by sweatybridge** [comment]
Yes, I believe it is resolved. Feel free to reopen if the problem persists.

**Comment by barbinbrad** [comment]
Hey guys, sorry for the late update. I think this is still a problem, but I'm not sure why. I suspect I'm doing something wrong.

I deleted my docker images, installed the newest CLI (1.42.5), pulled the latest images, and ran the script from Mark above with `console.log(await client.rpc("get_session_user"));`. 

It returns: 

```js
{
  data: 'postgres',
  error: null,
}
```

I don't think this should matter, but I am running Postgrest image version 10.1.1 where the current docker compose uses 10.1.2 https://github.com/supabase/supabase/blob/b2625c96d8b64855696f6d2e13518362a4701bd2/docker/docker-compose.yml#L103

![Screenshot 2023-03-11 at 6 41 04 AM](https://user-images.githubusercontent.com/64510427/224482318-6a1d61f2-5104-4a2d-a072-6f507078d181.jpg)

You can see that my `PGRST_DB_URI` is wrong, but it looks right in the CLI code:

https://github.com/supabase/cli/blob/c1c7ff5d923ab46da1aea25237e5009285846595/internal/start/start.go#L308

**Comment by barbinbrad** [comment]
This is fixed, thank you!
