### ISSUE TITLE
Can't create organization

### ISSUE THREAD

**Issue by randomloops** [supabase/supabase#10502]
BUG:
* I don't have create new project button
* If I manually go to http://IP:3000/new I cannot create a project ( see screenshort)
![image](https://user-images.githubusercontent.com/41739275/203685374-de4914ae-d912-4f64-be66-7d6e54c57db3.png)
![image](https://user-images.githubusercontent.com/41739275/203685393-b74f21ad-6919-4f82-a153-27519923f998.png)

**Comment by GaryAustin1** [comment]
If this self hosted or docker you only get the default project per setup.

**Comment by GaryAustin1** [comment]
No.
From the launch blog of studio:
`Studio is designed to work with existing deployments - either the local hosted, docker setup, or our CLI. It is not intended for managing the deployment and administration of projects - that's out of scope.`
https://supabase.com/blog/supabase-studio
