### ISSUE TITLE
When users fill in the password field with their account email, they could be signing in

### ISSUE THREAD

**Issue by ardyanrizki** [supabase/supabase#10508]
# Bug report

## Describe the bug

[CRITICAL]  This bug happens when using Supabase client (@supabase/auth-helpers-react) auth API signInWithPassword. When users fill in the password field with their account's email, they could be signing in and pass the auth verification.

## To Reproduce

1. With React Supabase client helper, use signInWithPassword API to call the sign-in service.
2. In docs, we need to send account email and password. So, fill in the email and password fields with ONLY your registered account email, in both, and send it. E.g.: **email**: *youremail@mail.com* **password**:  *youremail@mail.com*
4. Magically, you are just signed in with only your email. No password required.

## Expected behavior

User could be signed in with only their real password

## System information
- Version of supabase-js: ^2.1.0
- Version of @supabase/auth-helpers-nextjs: ^0.5.2
- Version of @supabase/auth-helpers-react: ^0.3.1
- Version of Node.js: 18.12.1

**Comment by vincentjflorio** [comment]
I happen to have your exact versions of everything in my project and couldn't reproduce this.

I got

```
error : "invalid_grant"
error_description : "Invalid login credentials"
```

My first thought was the possibility that there's something wonky about the fields themselves, or the approach to saving state, but that wouldn't make a ton of sense as the password would still need to come from somewhere. 

Is there a chance that there's an autofill going? What was the means by which you arrived at finding out this was happening in the first place? Is it common for users to try this? Or were you testing for the confusion that they might think it was a confirmation email field?
