### ISSUE TITLE
Docs: auth.onAuthStateChange() docs missing for supabase-js  v1 docs-reference

### ISSUE THREAD

**Issue by 404Xavier** [supabase/supabase#10526]
# Bug report

## Describe the bug
The `auth.onAuthStateChange` docs missing for supabase-js `v1` reference  but they are available in the [spec](https://github.com/supabase/supabase/blob/master/spec/supabase_js_v1.yml)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/docs/reference/javascript/v1/auth-onauthstatechanged](https://supabase.com/docs/reference/javascript/v1/auth-onauthstatechanged)

## Screenshots

The docs are missing on the website here

![supabase-v1-missing](https://user-images.githubusercontent.com/97474001/203930976-098d8851-e2c5-484e-a7ba-efdd40158138.png)

But they available on the spec

![supabse-docs-available-in-spec](https://user-images.githubusercontent.com/97474001/203931034-b22a47a5-e016-4254-963d-e93b196ef49c.png)

**Comment by MagnusHJensen** [comment]
The new docs has this, so this issue is no longer valid.
https://supabase.com/docs/reference/javascript/v1/auth-onauthstatechange

**Comment by saltcod** [comment]
Totally missed this from last month @404Xavier. Apologies. But it is indeed fixed on the new site.
