### ISSUE TITLE
redirectTo not working in Reset Password E-mail

### ISSUE THREAD

**Issue by pablocubico** [supabase/supabase#10534]
# Bug report

## Describe the bug

Due diligence disclaimer: I already search through the issues both in supabase and gotrue... I think this is an issue.

When using: 
```js
const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
  redirectTo: getRootURL() + '/resetPassword',
});
```

I added `https://localhost:3000` to the `Redirect URLs`:

![imagen](https://user-images.githubusercontent.com/340766/204032324-b502a42e-4319-4088-8d3e-4451969dbaf6.png)

(Tried with and without trailing slash)

But the link in the e-mail redirects to my `Site URL`:

![imagen](https://user-images.githubusercontent.com/340766/204032614-1e2de4e5-f0e9-4e4d-9cf0-b813e311617c.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Assuming you're using `http://localhost:3000` to develop locally:

1. Go to: https://app.supabase.com/project/.../auth/url-configuration
2. Add your local URL (`http://localhost:3000`) to the `Redirect URLs` list.
3. Open your app in `localhost` and use the JS snippet above to trigger a reset password e-mail (`getRootURL()` is just a wrapper for my URL, you can use `window.location.origin` or whatever).
4. Check the e-mail. The `redirectTo` param in the link from the e-mail template `{ .ConfirmationURL }` will have the `Site URL`.

## Expected behavior

The `redirectTo` param in the e-mail should have the argument provided in the function call.

## Screenshots

Screenshots already shared in the bug description.

## System information

- OS: any
- Browser: any
- Version of supabase-js: ^2.0.5 
- Version of Node.js: v14.18.2

## Additional context

Related issues/PRs:

https://github.com/supabase/supabase/issues/8903
https://github.com/supabase/supabase/pull/5999/files
https://github.com/supabase/gotrue-js/issues/144

**Comment by GaryAustin1** [comment]
The redirect URL's in the dashboard need to match the redirect URL including the path.

**Comment by hf** [comment]
As @GaryAustin1 mentioned, you need to have the correct Redirect URL added in the dashboard.

Make sure you use `**` to match any path. Typically this suffices for many use cases `https://your-app.com/**`

If you need direct assistance please [open a support ticket](https://app.supabase.com/support/new) as issues are meant for library bugs or feature requests.

**Comment by Julio-Campos-Swork** [comment]
I'm trying to do it, I've read the documentation and some errors from other users, but I can't get an answer, any other ideas?[
![resetpass](https://user-images.githubusercontent.com/112442652/210117448-7e7ea2d9-7364-4188-90d0-7eb019584107.png)
![consola](https://user-images.githubusercontent.com/112442652/210117454-e020391a-1227-45f8-ac65-3a23e7edbadc.png)
![supa](https://user-images.githubusercontent.com/112442652/210117456-a6b679d6-1fb9-41de-bc7b-5976a4bf3228.png)

no data, no response, no error

**Comment by GaryAustin1** [comment]
Is local host https?

**Comment by Julio-Campos-Swork** [comment]
> Is local host https?

Oops, Sorry, my mistake, I fixed it but still no response, I tried domains like 'https://google.com', but still not working

**Comment by GaryAustin1** [comment]
You are not going to get a response after calling that unless there is an error.  It is going to come back to the redirectTo URL after the user clicks on the link and your app will start again.  Putting google.com will never come back to your site.

**Comment by Julio-Campos-Swork** [comment]
> You are not going to get a response after calling that unless there is an error. It is going to come back to the redirectTo URL after the user clicks on the link and your app will start again. Putting google.com will never come back to your site.
> 
> Are you getting the email?

I have solved the problem, I added the IP address and now it sends me the email with the address where I redirected it, thanks for answering me, regards.
![resetpass](https://user-images.githubusercontent.com/112442652/210263721-baeaeca7-f413-4eac-ab89-23e2ab88163f.png)
![supa](https://user-images.githubusercontent.com/112442652/210263729-58896bc6-5736-40e0-a87e-01e6fe8ceac6.png)
![mail](https://user-images.githubusercontent.com/112442652/210263735-0d7dabfe-6159-47f0-b334-d7ea14b50a80.png)

**Comment by JHaberlsz** [comment]
It seems that I am experiencing an issue with my self-hosted Supabase setup. When accessing my website locally, the redirectTo link is included correctly in the email. However, when I access the website from the public internet, the redirectTo parameter is ignored, and the link in the email redirects me to my domain root instead.

The only difference I can think of between the local and public setups is the Nginx Proxy Manager I use:[]( https://nginxproxymanager.com/). I suspect the proxy might be interfering with the requests or headers, but I am unsure where the configuration might be causing this behavior.

I would appreciate any help or insights into this issue, as I am currently at a loss on how to resolve it.
