### ISSUE TITLE
Storage API is not working

### ISSUE THREAD

**Issue by wahlforss** [supabase/supabase#10535]
We cannot upload images to storage. **This bug is costing us $30k per day**

Please help. Project is BeFake.

# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by anikait1** [comment]
Hi @wahlforss, can you please add more detail about the issue you're facing. How are you trying to upload images, using the web-ui, supabase client, what environment you're running your application in and what error are you facing.

**Comment by saltcod** [comment]
Hey @wahlforss any update on the symptoms on this one?  Happy to investigate.

**Comment by kiwicopple** [comment]
I'll close this one until more details are provided
