### ISSUE TITLE
Can't deploy Supabase Edge Function (Stripe) - Relative import path "http" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by MIPB** [supabase/supabase#10543]
# Bug report

## Describe the bug

Hello! 

I am trying to connect to Stripe through Supabase's Edge Functions, but I keep getting this error:
`
Relative import path "http" not prefixed with / or ./ or ../
`
I've been digging and it seems related to the bundling from Typescript to Javascript, but I have not found a solution yet.

My code is the same as the official: [Repo](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/stripe-webhooks/index.ts
)

I noticed that I can deploy if I delete the Stripe import, so I guess it could be related, but I can't understand why since other imports (like the Supabase import for Deno) work correctly.

Thanks!!

## To Reproduce

Create an Edge Function that calls Stripe just like the one in the Repo.

## Expected behavior

I should be able to deploy the function

## Screenshots

![image](https://user-images.githubusercontent.com/47779064/204100320-991a86a2-d1dc-4c91-8a68-635f9df1a91a.png)

## System information

- OS: Windows
Versions:
 "supabase": "^1.14.1",
 "@supabase/supabase-js": "^2.0.5",
  npm: '8.19.2',
  node: '16.13.0'

**Comment by laktek** [comment]
@MIPB Can you try importing the module from the following  URL? `https://esm.sh/stripe@11.0.0?target=deno&no-check`

Need to add `no-check` query param to prevent type checks during imports.

**Comment by MIPB** [comment]
Works correctly thank you :)

**Comment by pimvanderheijden** [comment]
I've got a very similar issue but fail to see how this solution applies to my case.

![image](https://user-images.githubusercontent.com/22522186/212101631-3ec49718-f69f-406a-a2e7-477bdba44a53.png)

Nowhere in my own code do I have import "buffer". However, I do have "buffer" in my deno.lock file as "https://deno.land/std@0.162.0/io/buffer.ts". I tried to append "?target=deno&no-check" there but that didn't help obviously.

What causes this and what solves it?

**Comment by laktek** [comment]
@pimvanderheijden You can run `deno info YOUR_FUNCTION/index.ts` to see the dependency graph. That should show which import depends on `buffer`. Then you can probably try adding `?target=deno&no-check` to that dependency.

**Comment by pimvanderheijden** [comment]
It worked, thanks!!

**Comment by drewbietron** [comment]
I am not getting this same error when deploying an Edge Function to a live environment.  Adding `no-check` to the import will make the deploy succeed, but adding that will also not enforce any of the types from the library. 

Stripe types aren't working in Deno and as a workaround you have to declare them in an import-map ([discussed in this issue on the Stripe Deno example repo](https://github.com/stripe-samples/stripe-node-deno-samples/issues/2)) -- however adding `no-check` to the import-map statement results in Stripe being cast to any 🤕

**Comment by Semines** [comment]
Hi guys, I'm trying to configure FluxGPT app but when using **_supabase functions deploy completion_**, I'm getting error : 
Error: Error bundling function: exit status 1
Error: Cannot access "completion". Check if directory exists and has read permissions. 
I've found info to add '--legacy-bundle' and now I'm getting : 
Error: Error bundling function: exit status 1
error: Module not found "file:///Users/*********/completion/index.ts".
I opened this index file in 'completion' and I have a problem : 
Cannot find module 'https://deno.land/std@0.132.0/http/server.ts'
What should I do?

**Comment by Semines** [comment]
I added  '// @ts-nocheck' before import in index.ts and open_ai.ts and hardcoded my openAI key instead of Deno.env.get("OPENAI_API_KEY") ?? "", in open_ai.ts file. After that I deployed function completion and everything working fine ;)

**Comment by justinekatebe** [comment]
> Hi guys, I'm trying to configure FluxGPT app but when using **_supabase functions deploy completion_**, I'm getting error : Error: Error bundling function: exit status 1 Error: Cannot access "completion". Check if directory exists and has read permissions. I've found info to add '--legacy-bundle' and now I'm getting : Error: Error bundling function: exit status 1 error: Module not found "file:///Users/*********/completion/index.ts". I opened this index file in 'completion' and I have a problem : Cannot find module 'https://deno.land/std@0.132.0/http/server.ts' What should I do?

I think the reason why you were getting this error is because inside the supabase directory, you need to put your folder for completion inside a functions folder. Something like this supabase > functions > completion > index.ts
