### ISSUE TITLE
Docs: Unable to search docs with query: anon key

### ISSUE THREAD

**Issue by jerrylususu** [supabase/supabase#10542]
I just learned about supabase and am exploring more about it. When checking some examples I noticed `anon-key`, but when trying to search it in the document site using the built-in search, nothing was returned. So I turned back to google and found it appears in the following page: https://supabase.com/docs/guides/api . 

I guess the built-in search is not a full-text search, and only includes the page titles in its index. Still this is kind of frustrating, and it would be great if this problem can be fixed.

The following search terms has been tried, yet none of them returns the expected page:
- `anon key`
- `anonkey`
- `anon-key`
- `anon_key`
- `anon`
- `key`

**Comment by saltcod** [comment]
Hey @jerrylususu thanks for the report. You're right, we're currently only searching on title and description fields. We're looking to make this much more robust, hopefully soon. Thanks!
