### ISSUE TITLE
Paused database doesn't prompt to restart / table data missing after restart

### ISSUE THREAD

**Issue by AvidDabbler** [supabase/supabase#10553]
# Bug report

## Describe the bug

I have a testing database that was recently paused after 5 days. I went to restart the database and it seems to have been restarted on its own (not sure if this is part of the problem). 

When I looked at all of my tables the data in the tables had all been cleared out, but my functions are still there.

I was able to restore from a recent local backup, but this has happened to me before and I saw other post about it on discord.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. pause an instance
3. check data tables

## Expected behavior

I expected that when I went into the console that it would prompt me to restart the instance and then on restart my tables would be populated with the data. Neither was true.

## System information

- OS: osx
- Browser (if applies) firefox, chrome
- Version of supabase-js: NA
- Version of Node.js: NA

**Comment by saltcod** [comment]
Hi @AvidDabbler — just noticed this as well. I paused a project, unpaused it, noticed my tables were not there. However, when I refreshed the table editor, I could see my missing tables and their data again. Might be a case of needing to refetch the list of tables at that point. 

Does refreshing this page fix the issue for you, or do you never see the tables come back?

**Comment by chriscarrollsmith** [comment]
My table was listed, but could not be opened, edited, or deleted. I am going to have to delete the whole project and recreate it, which is a real pain.

**Comment by saltcod** [comment]
@chriscarrollsmith could you confirm that this is still happening?

**Comment by saltcod** [comment]
kk I'll close this issue then. Apologies again for the delay. If the issue pops up again, feel free to reopen.
