### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by MBeggiato** [supabase/supabase#10574]
# Bug report
When trying to use docker compose on stack, the build fails with the following error:
`services.meta.depends_on must be a list`

## Describe the bug
When trying to use docker compose, the build fails with the following error:
`services.meta.depends_on must be a list`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

`git clone --depth 1 https://github.com/supabase/supabase`

Go to the docker folder
`cd supabase/docker`

Copy the fake env vars
`cp .env.example .env`

Start
`docker stack deploy --compose-file docker-compose.yml supabase`

## Expected behavior
The service should start.

## System information

- OS:  Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Docker:  Docker version 20.10.21, build baeda1f
- Docker-Compose: Docker Compose version v2.12.2

**Comment by sstopkin** [comment]
@MBeggiato Actually I don't see any issues in compose file syntax https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L159. (docs https://docs.docker.com/compose/compose-file/#depends_on). Please try to update docker/docker-compose and check it again.

**Comment by ahwelp** [comment]
I was having the same problem. So I changed the yml file and converted the problematic sections to arrays.

[docker-compose.diff.txt](https://github.com/supabase/supabase/files/10147826/docker-compose.diff.txt)

This is not a solution, jut changed so I could run the service. The changes will prevent the containers from checking the health of the dependencies.

I am also having problems with the docker-compose versions.

docker-compose version 1.23.2 complains about the yml version
docker-compose version 1.25.0 complains about the yml version
docker-compose version 1.26.0 has the same problem as the OP issue

1.25.0  seems to be the latest docker-compose on Ubuntu 20.04.5 LTS, so in my VM I am still not able to run Supabase.

**Comment by ahwelp** [comment]
I downloaded the 1.29.2 docker-compose. Now it is working fine.

https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
