### ISSUE TITLE
iOS Sign in with Apple "Invalid_client"

### ISSUE THREAD

**Issue by thilojaeggi** [supabase/supabase#10591]
So, I've followed the official Docs to setup Sign in with Apple but if I try to use it on a device the error "invalid_client" comes up.

Is the documentation outdated?
![image](https://user-images.githubusercontent.com/20727326/204392315-2a77234c-0299-48ec-b4a2-1c149a6904a4.png)

**Comment by heyaware** [comment]
I'm getting the same invalid_client error. How long ago did you create your Apple Developer account? And how long ago did you create your App ID and Service ID? I saw elsewhere online that it took others 48 hours before Apple services recognized their client_id

**Comment by thilojaeggi** [comment]
Well seeing as it still doesn't work the 48 Hours are over. My Developer Account is like a year old.

**Comment by heyaware** [comment]
I'm going to share and ask for more details to see if we can help each other debug.

So you have a Services ID, and that is attached to an App ID. Do you have an app published to the App Store with that App ID?

I'm attempting to implement "Sign in with Apple" in my web app only. I currently do not have a live iOS app under this developer account. 

Not sure if that matters, but I believe Apple pulls the App Icon from the App ID, and perhaps without an app causes an issue.

**Comment by thilojaeggi** [comment]
I have a bundle id for the App but the app isn't yet registered in App Store Connect.

**Comment by heyaware** [comment]
Actually it might not matter. Here is an app built using Supabase. It appears Apple defaults to the black and white Apple logo if it can't pull an App Icon. 

https://kanji.plus/sign-in

**Comment by heyaware** [comment]
I bring all of this up, because, while looking at Twitter's "Sign in with Apple" option, Apple is pulling their App Icon from the app with the top-level App ID. 

<img width="746" alt="" src="https://user-images.githubusercontent.com/103811786/204904316-8b93436d-dd36-43a6-b893-64b094e49081.png">

**Comment by heyaware** [comment]
@thilojaeggi Are you using a custom domain on the Supabase project?

**Comment by thilojaeggi** [comment]
No, in fact I dont have that option.

**Comment by thilojaeggi** [comment]
I've added the app in App Store Connect now though but didn't add any builds, idk if that's needed.

**Comment by kangmingtay** [comment]
hey @thilojaeggi, are you still experiencing difficulties setting this up? The apple developer account usually expires after a year so if your account is a year old, you might want to check that the credentials created are still valid. I also noticed that you are using this on iOS which has a slightly different setup from web. Your client id should be your app's bundle id and not the `Services Id` mentioned in this guide: https://supabase.com/docs/guides/auth/social-login/auth-apple

**Comment by J0** [comment]
Going to close the issue now as it seems stale but feel free to revert back/re-open if there are still issues.

Thanks!

**Comment by bilalkumrani** [comment]
Why this issue is closed without any solution?
PLEASE OPEN THIS ISSUE

**Comment by chanmathew** [comment]
I'm getting same issue here, did a fresh setup today. Developer account has been open for a month, so it's not on Apple's end waiting for approval. Followed the docs exactly...

**Comment by mateipavel-github** [comment]
Same problem, no clue how to fix

**Comment by zaini** [comment]
Currently experiencing as well. I have set this up before and it worked. I _think_ I have to just wait? I've already waited 24 hours but I guess I can wait more.

**Comment by bsheikh** [comment]
experiencing the same issue as well, i've done it before and it worked previously. now it's failing

**Comment by azegallo** [comment]
Same issue here

**Comment by azegallo** [comment]
Could be an apple issue:
https://developer.apple.com/forums/thread/789011

**Comment by mateipavel-github** [comment]
I used Apple's JS solution and then used the resulting token to sign into Supabase - worked like a charm, took 2 minutes using Cursor.

**Comment by azegallo** [comment]
> I used Apple's JS solution and then used the resulting token to sign into Supabase - worked like a charm, took 2 minutes using Cursor. 

You did this with a newly created Service Id / Key?

**Comment by azegallo** [comment]
It seems to be working for me now. Even with brand new app/service/keys. Looks like it was an Apple issue

**Comment by oskar-makarov** [comment]
A note for people arriving here from search years later: there are two very different causes of `invalid_client` with Supabase + Apple.

1. **Misconfiguration** (wrong Services ID / Team ID / Key ID) — fails from day one. Check those first.
2. **Expired client secret** — worked fine, then broke after ~6 months. Apple's client secret is a JWT with a hard 6-month max lifetime, and it expires silently. Note this only affects web/OAuth flows; native iOS `signInWithIdToken` doesn't use the client secret.

For case 2, I automated the rotation with a GitHub Action that regenerates the JWT from the `.p8` and updates Supabase via the Management API on a schedule: https://github.com/oskar-makarov/apple-client-secret-rotator (I'm the author; MIT, zero dependencies).
