### ISSUE TITLE
All links in Supabase.com/partners/integrations are 404ing for me

### ISSUE THREAD

**Issue by chalzzzzz** [supabase/supabase#10609]
# Bug report

## Describe the bug

I am getting a 404 error for all of the links on this page https://supabase.com/partners/integrations

## To Reproduce

https://supabase.com/partners/integrations
* Click some links. I've tried about ten. I got a 404 on all.

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [Supabase Partners Integrations](https://supabase.com/partners/integrations)
2. Click on any link
3. See 404 error

## Expected behavior

I expected some links. 

## System information

- OS: MacOS 13.0.1 
- Browser (if applies) Firefox

**Comment by Hallidayo** [comment]
Hi @chalzzzzz - Seems okay now, is this okay for you now?

**Comment by chalzzzzz** [comment]
Yeah, it works now!
