### ISSUE TITLE
How do I use Filter() in supabase-csharp?

### ISSUE THREAD

**Issue by dimunyo** [supabase/supabase#10600]
### Discussed in https://github.com/supabase/supabase/discussions/10598

<div type='discussions-op-text'>

<sup>Originally posted by **dimunyo** November 29, 2022</sup>
![image](https://user-images.githubusercontent.com/55717823/204438451-844d6c7d-a9b0-497b-a27e-cba2fdf558ca.png)
Hi, I`m trying to get the username with the filter function, I don't know the right syntax.</div>

**Comment by PartyKarty** [comment]
Have you tried removing await?

**Comment by MagnusHJensen** [comment]
@dimunyo You marked the response in that linked discussion as the answer, if so did that work for you? If that worked please close this issue.

**Comment by kiwicopple** [comment]
Hey @dimunyo - could you please open this one in the C# repo?
https://github.com/supabase-community/supabase-csharp

Thanks! I can't transfer it there because it's in the community org.
