### ISSUE TITLE
Database error could not save new user

### ISSUE THREAD

**Issue by outstager** [supabase/supabase#10611]
### Discussed in https://github.com/supabase/supabase/discussions/10610

<div type='discussions-op-text'>

<sup>Originally posted by **outstager** November 29, 2022</sup>
I'm getting database error - could not save new users. I need to save the id as busadminuserid rather than id.

create table busadmin(
  busadminuserid uuid,
  email varchar(120),
  
  primary key(busadminuserid)
);

ALTER TABLE public.busadmin
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY
  "Can only view own profile data."
  ON public.busadmin
  FOR SELECT
  USING ( auth.uid() = busadminuserid );

CREATE FUNCTION
  public.create_profile_for_new_user()
  RETURNS TRIGGER AS
  $$
  BEGIN
    INSERT INTO public.busadmin (busadminuserid,email)
    VALUES (NEW.busadminuserid,NEW.email);
    RETURN NEW;
    END IF;
  END;
  $$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER
  create_profile_on_signup
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE
    public.create_profile_for_new_user();</div>

**Comment by GaryAustin1** [comment]
I answered the likely thing in discussions.  You really should not double post in both places.

**Comment by saltcod** [comment]
Thanks both. Going to close this one in favour of the discussion.
