### ISSUE TITLE
docs: 2nd level nav arrows status change incorrect

### ISSUE THREAD

**Issue by burmecia** [supabase/supabase#10628]
# Improve documentation

https://supabase.com/docs

## Describe the problem

The 2nd level indication arrows under `Integrations` on the left nav cannot show correctly when open/closed status changed.

To reproduce:

Go to https://supabase.com/docs and click `Integrations`, the arrow icon before it is correctly showing 'down', but the arrow icons of its sub-items like 'Auth' and 'Caching / Offline-first' show incorrectly, they even don't change if you open or close the sub-items.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/19306324/204681035-973bff05-b2ac-4eb2-8d74-f8603460a448.png">

## Describe the improvement

The arrow icons on the 2nd level nav items should show correctly when the item is opened or closed.

## Additional context

Tested on latest version of Chrome and Firefox.

**Comment by enesinan** [comment]
![sup](https://user-images.githubusercontent.com/72499839/205875176-cf5d6c8e-b211-43a8-8c61-bc1c169ffcd8.png)

Hi @burmecia, how is look like?

**Comment by MagnusHJensen** [comment]
This is no longer a valid issue with the new next-js docs.
