### ISSUE TITLE
POSTGIS_TIGER_GEOCODER Extension Functions Don't Exist

### ISSUE THREAD

**Issue by mreky** [supabase/supabase#10631]
I'm trying to use reverse geocodes on my project, so I run this code in the sql editor which successfully installs the extensions I need. I already have Postgis installed.

```
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;
CREATE EXTENSION address_standardizer;
```
Returns success.

But then whenever I try to use a simple function of the extension to verify it has been installed successfully which is like:
`SELECT na.address, na.streetname,na.streettypeabbrev, na.zip
	FROM normalize_address('1 Devonshire Place, Boston, MA 02109') AS na;`
Returns the error: "Failed to run sql query: function normalize_address(unknown) does not exist"

I tried installing the required extensions manually from the dashboard but that doesn't help either I keep getting the error that the functions don't exist. I tried running different functions, but none of them work. I would appreciate any help, thank you.

**Comment by GaryAustin1** [comment]
Normally you have to either prefix you function with the schema you installed it in, or add that schema to your search path (either UI default settings, function settings, or user settings).

**Comment by mreky** [comment]
> SELECT na.address, na.streetname,na.streettypeabbrev, na.zip FROM normalize_address('1 Devonshire Place, Boston, MA 02109') AS na;

Thank you for responding, I'm new to Postgres but when I use 'tiger.'  before the function it returns the error: "Failed to run sql query: type "norm_addy" does not exist" using the same function in the question, is that still related to the same issue?

**Comment by GaryAustin1** [comment]
https://www.postgresonline.com/article_pfriendly/279.html
You can also set the search path defaults for API requests here:
![image](https://user-images.githubusercontent.com/54564956/204701810-c3cab766-c708-4624-9717-d5f5afba3cb9.png)

**Comment by mreky** [comment]
> https://www.postgresonline.com/article_pfriendly/279.html You can also set the search path defaults for API requests here: ![image](https://user-images.githubusercontent.com/54564956/204701810-c3cab766-c708-4624-9717-d5f5afba3cb9.png) Edit: sorry, email and other link go mixed up: Could be. I've seen cases where you can't just use the schema in front of the function if it is a SQL function and calls another function without the schema (which it does not know).

I added tiger to the extra search path in API settings of Supabase, but still if I don't prefix with tiger. before the function I get the same error, but then whenever I prefix it myself I get this error again. I can't tell what's wrong I read the docs for the extension too. 
<img width="1103" alt="Screen Shot 2022-11-29 at 10 42 01 PM" src="https://user-images.githubusercontent.com/118037596/204702417-affed847-1f8d-4d8b-b4e9-b2f26d84e59b.png">

**Comment by GaryAustin1** [comment]
The API settings don’t help when you are using the SQL editor. You have to use SQL to set the search path either for the role running the SQL code or for the session. The link I provided might help.  ……I’m out for the night.

**Comment by mreky** [comment]
Thank you for trying to help, I did use "ALTER DATABASE postgres SET search_path" to set the search path for tiger in the SQL Editor, I am able to see tiger functions when I use tiger. in the sql editor but I still get the same error.

**Comment by GaryAustin1** [comment]
The search path would also likely have to contain extensions as the default schema for your other two extensions is … extensions.

**Comment by mreky** [comment]
<img width="1103" alt="Screen Shot 2022-11-30 at 9 40 47 AM" src="https://user-images.githubusercontent.com/118037596/204825077-74283c9b-f5ab-4cf9-aadc-fa5d058f3514.png">
Is this what you are talking about? I didn't quite understand what you are saying, sorry.

**Comment by GaryAustin1** [comment]
I'm not really sure without digging into where norm_addy is getting called.  
Where you supposed to install the "address_standardizers" in tiger?  Their default is extensions.  
When you set your search_path you need to include all the schemas you need so likely public, tiger, extensions at least.
"norm_addy" appears to be a type set up by one of the "postgis" related extensions, but I've only use postgis and not these features.

**Comment by mreky** [comment]
I changed them to tiger schema after they didn't work in the extensions, but that didn't work either. I'll look more deeper into it, thank for trying to help.

**Comment by GaryAustin1** [comment]
@mreky Is this still an open issue for you?

**Comment by GaryAustin1** [comment]
Going to close this for now.  If it is still an issue please feel free to comment.

**Comment by kylewill** [comment]
having this same issue. 

1. create a new database
2. enable the postGIS and postgis_tiger_geocoder extensions

run:
SELECT *
        FROM tiger.reverse_geocode(ST_GeomFromText('POINT(-71.093902 42.359446)',4269),true) As r;
        
error:
Failed to run sql query: type "norm_addy" does not exist

**Comment by tadeegan** [comment]
I resolved this with:

```
SET search_path TO tiger, extensions, public;

select tiger.reverse_geocode(x), * from ...;
```

**Comment by lpg0** [comment]
Running into the same issue as @mreky and I tried @tadeegan's solution, but still recieve the issue "norm_addy" type does not exist. I set the search path, certified that "tiger" is an extension, and prefaced the command with "tiger." and still the same issue @GaryAustin1

**Comment by GaryAustin1** [comment]
@lpg0 If you are calling this from the REST API check the attached suggested doc change file here: https://github.com/supabase/supabase/pull/32944
Postgis gis extension needed to have grants applied to it.
May be related.

**Comment by lpg0** [comment]
@GaryAustin1 I am not, I am calling it from a Postgres trigger [https://supabase.com/docs/guides/database/postgres/triggers](url)

I opened the following issue: [https://github.com/supabase/supabase/issues/33053#issue-2807883374](url)

**Comment by GaryAustin1** [comment]
Is the postgres trigger function coming from a REST API operation and not security definer type?

**Comment by lpg0** [comment]
To my knowledge the Supabase Postgres Trigger does not come from a REST API operation, but rather is automatically invoked by PostgreSQL when a specified event (like INSERT, UPDATE, DELETE, or TRUNCATE) occurs on a table with the privileges of the user that invokes it. In Supabase -> Database Management -> Triggers, the Post GIS Tiger is via the Extensions tab. If I am talking past you, let me know how I can clarify @GaryAustin1 .

**Comment by GaryAustin1** [comment]
Whatever user did the insert/update/etc is the role that will be running.  So if the insert came from the REST API then it would be anon/authenticed/service_role UNLESS your function is security definer type.  If so the grants may be needed on your Tiger schema.

**Comment by lpg0** [comment]
Okay gotcha, so I initiated the error by manually tripping the trigger via editing the database table from the Supabase web UI. So I should be looking to give the tiger schema edit access to my public schema? This does not make sense if the error is saying "does not exist" rather than "permission denied" @GaryAustin1

**Comment by GaryAustin1** [comment]
The PR I linked you to was from this discord: https://discord.com/channels/839993398554656828/1330854767777288353/1331028827685523579
With the exact same message and adding the grants to gis fixed it.

**Comment by lpg0** [comment]
@GaryAustin1 I tried running:
`GRANT USAGE ON SCHEMA tiger TO anon, authenticated, service_role;
`
This did not fix the issue, but still threw the norm_addy DNE error.

**Comment by GaryAustin1** [comment]
K.  Then no idea then.
Have to see if someone answers your new issue or ask in discussions or Discord and see if someone else has an idea.
