### ISSUE TITLE
Renaming table in UI loses delete cascade fk constraint

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#10668]
# Bug report

## Describe the bug

If you create a delete cascade constraint on a table with SQL and then later use the UI to rename the table, the rename succeeds without error.  Then if you delete an item in the "parent" table you get:

![image](https://user-images.githubusercontent.com/54564956/205074815-edbdd62f-6f9c-4120-b293-1709792e421c.png)

The problem is no error was generated during the rename and if you start testing deletes much later, there is little evidence to suggest the problem was the rename.  This has cost users much time in debugging in Discord.

## To Reproduce
Create a table called profiles with a foreign key to auth.users and delete cascade:

```
create table profiles
(
    id  uuid  not null
        constraint profiles_pkey   primary key
        constraint profiles_id_fkey references auth.users on delete cascade,
    username   varchar(24)  not null
        constraint profiles_username_key unique
        constraint usernamevalidation
            check ((username)::text ~* '^[A-Za-z0-9]{3,24}$'::text),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
```
Deleting a user  from auth.users works.

Rename the table in the UI to profile.

This is the SQL now for the table when examined by Datagrip:
```
create table profile
(
    id  uuid  not null
        constraint profiles_pkey  primary key constraint profile_id_fkey references auth.users
    username   varchar(24)  not null
        constraint profiles_username_key unique
        constraint usernamevalidation
            check ((username)::text ~* '^[A-Za-z0-9]{3,24}$'::text),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
```
The delete cascade is missing.
Delete a user from auth.users and an error occurs.

## Expected behavior
Either convert constraints correctly, or at least flag a message about the risk of renaming a table with the UI if you have custom constraints.

Related Discord link:  https://discord.com/channels/839993398554656828/1047551552728084571

**Comment by silentworks** [comment]
I can confirm this is a issue for sure. @GaryAustin1 sorry for taking so long to test this out.

**Comment by silentworks** [comment]
The code causing the issue can be found here https://github.com/supabase/supabase/blob/master/studio/stores/pgmeta/MetaStore.ts#L279-L302, it seems we don’t take into consideration the ON UPDATE and ON DELETE options a foreign key can have on them.

**Comment by ivasilov** [comment]
I tried to replicate this but it looks like it's fixed. The second `ALTER TABLE ... ADD CONSTRAINT` had the correct cascades attached to it. @silentworks @GaryAustin1 can you confirm?

**Comment by saltcod** [comment]
Going to to mark this one as closed. Please reopen if that's not the case. Thanks all.
