### ISSUE TITLE
Dashboard error ui overflow

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#10689]
# Bug report

## Describe the bug

When getting a long error in the dashboard it overflows.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to app.supabase.com
3. get a long error name

## Expected behavior

The error with a long to line wrap

## Screenshots

![image](https://user-images.githubusercontent.com/70828596/205331913-574f6a69-3209-4901-bab3-17fac4b2cbf5.jpeg)![image](https://user-images.githubusercontent.com/70828596/205331915-2ec74ce4-46d0-4ac2-805d-bccb8e2c3431.jpeg)

## System information

- OS: any
- Browser: any
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by joeshajan** [comment]
Hey, @Isaiah-Hamilton I would like to fix this issue. Can you assign this to me or can I start working on it?
