### ISSUE TITLE
Working with documents

### ISSUE THREAD

**Issue by zhangpengchen** [supabase/supabase#107]
* **I'm submitting a feature request**

* **Summary**
PostgreSQL's JSONB functionality is incredible powerful. Store fields in a JSONB column, adding index/duplicated columns for searching/filtering ofters the flexibility and best performance.

* **Other information**
massivejs had something in place
https://massivejs.org/docs/working-with-documents

**Comment by kiwicopple** [comment]
Thanks for the request @zhangpengchen 

We already support JSONB quite extensively (since we are "just" Postgres). If you create a table with a JSONB column you can do things like this:

```js
supabase
.from('your_table')
.select(`
  json_data->>blood_type,
  json_data->phones
`)
```

Also, in our next version of the UI (next week) we are starting to support JSON editing in our table view.

Is this what you had in mind? Let me know if there is something else you're looking for.

**Comment by zhangpengchen** [comment]
@kiwicopple right, i am kind of missing that information in the docs https://supabase.io/docs 

So i can insert a record by following?

```
let cities = await supabase
      .from('cities')
      .insert([
        { name: 'The Shire', country_id: 554, json_data: { blood_type: 'o', phones: ['0123456789'] } }
      ])
```

**Comment by kiwicopple** [comment]
Yeah we could be a bit more explicit about this in the docs. I'll keep this issue open as a reminder to update them. We are also working on the auto-generated docs in your Supabase dashboard - from here we will be able to detect the `json` data type

> So i can insert a record by following?

That's exactly right. For more docs, our JS client wraps PostgREST, so you have a lot of functionality at your disposal: http://postgrest.org/en/v7.0.0/api.html#json-columns

**Comment by zhangpengchen** [comment]
Thanks @kiwicopple for an amazing project.
