### ISSUE TITLE
external pg15 and posgrest9 issue

### ISSUE THREAD

**Issue by wibrt** [supabase/supabase#10707]
# Bug report

## external pg15 and posgrest9

There is a know issue of postgrest 9 and postgresql 15:
https://github.com/PostgREST/postgrest/issues/2410

So if you use an decoupled external postgresql-15 database,
then the docker image of the current supabase-rest won't work,
since it uses version 9 of postgrest
(solution: upgrade supabase-rest to version 10 of postgrest)

the error shown will be:
"UNION types \"char\" and text cannot be matched"

**Comment by kiwicopple** [comment]
hey @wibrt - thanks for flagging this. this is now closed in PostgREST, so I'll close this issue
