### ISSUE TITLE
Improve insert docs to cover behavior change: >v1.x returns empty response by default

### ISSUE THREAD

**Issue by clounie** [supabase/supabase#10718]
# Improve documentation
## Link 
https://supabase.com/docs/reference/dart/insert

## Describe the problem
With the behavior change from v0.x --> v1, database inserts no longer return a response by default.

I could not find this explained in documentation, and had to fall back on a [github discussion](https://github.com/supabase/supabase/discussions/4054) to understand what was happening + a different [reddit post](https://www.reddit.com/r/Supabase/comments/x20aqc/insert_works_but_does_not_return_data_or_error/) to finally figure the solution for Dart APIs.

## Describe the improvement

Add an example along the lines of..
```
## Create a record and return the result
final data = await supabase
    .from('cities')
    .insert({'name': 'The Shire', 'country_id': 554}).select('*');
```

And while we're at it - please remove the misleading variable assignments for the other examples since they _always_ return null now.

## Additional context
N/A

**Comment by dshukertjr** [comment]
Closing as it has been fixed in the reference docs.
https://github.com/supabase/supabase/pull/10932
