### ISSUE TITLE
localhost:3001 page not found error

### ISSUE THREAD

**Issue by enesinan** [supabase/supabase#10711]
# Bug report

## Describe the bug

According to https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#running-turborepo
I want to setup local environment, but I cant access to /docs
After 'npm run dev' from console 
I saw the page not found

## To Reproduce

1. Go to http://localhost:3001/
4. See error  GET http://localhost:3001/ 404 (Not Found)

## Screenshots

![1](https://user-images.githubusercontent.com/72499839/205455665-e528494a-cc4f-45e6-9896-efcd35c3979f.png)

## System information

- OS: Windows
- Browser: Chrome, Edge

**Comment by Hallidayo** [comment]
Hi @enesinan - If you go to http://localhost:3001/docs you should get the Introduction page appearing.

I'll create a pull to change the DEVELOPERS.md file.
