### ISSUE TITLE
Database egress not correctly displaying on usage page

### ISSUE THREAD

**Issue by mqp** [supabase/supabase#10715]
Right now on my 2 projects, which I both upgraded to $25/mo Pro yesterday, I see accurate-looking data for "Database space" on my usage page, but 0 for "Database egress" (which is definitely false.) The other fields are 0 but I actually haven't used those features yet so I have no idea whether they are working or not.

I have observed this consistently not displaying data for the past day, during which I was regularly calling the API and using the dashboard.

Tested with Firefox and Chrome on Linux.

My Supabase project IDs are `pxidrgkatumlvfqaxcll` and `mfodonznyfxllcezufgr`.

![image](https://user-images.githubusercontent.com/428637/205465692-c49addae-12a3-4a2b-99e3-a7f8e30adf80.png)

**Comment by saltcod** [comment]
Hi @mqp this is probably best handled with a support request (Help button in the top right of the dashboard) if this persists beyond 24 hours. Thank you!
