### ISSUE TITLE
buster>bullseye (docker)

### ISSUE THREAD

**Issue by wibrt** [supabase/supabase#10728]
# docker image supabase-meta using buster

the latest supabase-meta docker image uses debian buster (oldstable), which is still ok for now (eg securitywise); bullseye is the current stable of debian

--

(the same for some other supabase images:
* realtime
* studio
* ..

or some alpine versions in for example auth

::off topic for this repository)

**Comment by KevinBrolly** [comment]
This issue has become stale, so I am going to close it. 

If it should be actioned and reopened please do so.
