### ISSUE TITLE
Running Studio Gives Error `Module parse failed: Unexpected token (15:5)`

### ISSUE THREAD

**Issue by globemediaofficial** [supabase/supabase#10736]
# Bug report

## Describe the bug

I am self-hosting Supabase and have been waiting for Storage UI to be added to the studio. It's been over 2 weeks since these changes were made but the latest docker image still doesn't have Storage UI. Someone suggested that I run the studio by itself until the docker image is updated so I tried. First, it worked but opened to a `sign-in` page. I tried to use my Supabase account to sign in and it gave me an error saying no API key found. I tried to find where I am meant to find my login credentials but gave up. Now I'm trying again when when I run the commands shown in the instructions of the `studio` directory, not even the `sign-in` UI is shows and and I get this error:
```
ready - started server on 0.0.0.0:8082, url: http://localhost:8082
info  - Loaded env from G:\Supabase\supabase\studio\.env
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - automatically enabled Fast Refresh for 1 custom loader
error - ../packages/ui/src/components/Accordion/Accordion.tsx
Module parse failed: Unexpected token (15:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| //   Pick<AccordionProps, 'onChange'>
|
> type Type = 'default' | 'bordered'
| type Size = 'tiny' | 'small' | 'medium' | 'large' | 'xlarge'
| type Align = 'left' | 'right'
wait  - compiling...
error - ../packages/ui/src/components/Accordion/Accordion.tsx
Module parse failed: Unexpected token (15:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| //   Pick<AccordionProps, 'onChange'>
|
> type Type = 'default' | 'bordered'
| type Size = 'tiny' | 'small' | 'medium' | 'large' | 'xlarge'
| type Align = 'left' | 'right'
(node:5228) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```

## Screenshots

![Screenshot 2022-12-05 184317](https://user-images.githubusercontent.com/109893647/205797278-188b8a11-6628-4786-a2a5-42fb0563cf4a.png)

## System information

- OS: Windows
- Browser: chrome
- Version of Node.js: 14.17.3

**Comment by saltcod** [comment]
Hi @globemediaofficial 

Could you:  rm -rf node_modules && npm i and see if that clears things up?

**Comment by sweatybridge** [comment]
Also, our compose file has been updated to the latest studio image with Storage UI support. https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L12

I will close this as completed but feel free to open if you run into other issues.
