### ISSUE TITLE
Realtime demo at multiplayer.dev not working

### ISSUE THREAD

**Issue by alexkreidler** [supabase/supabase#10742]
1. Go to https://multiplayer.dev/
2. Open DevTools
You will see the error:
```
WebSocket connection to 'wss://nixfbjgqturwbakhnwym.realtime.abc3.dev/socket/websocket?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5peGZiamdxdHVyd2Jha2hud3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDc5NTk1ODksImV4cCI6MTk2MzUzNTU4OX0.YZMe4JJxd7SsB3__cLPg1ykGCG3krqc7sDKHQnlb4I4&vsndate=2022&vsn=1.0.0' failed: 
```

**Comment by kiwicopple** [comment]
this one seems to be fixed now, so I'm closing it
I think this would have been during a migration that we were doing

**Comment by w3b6x9** [comment]
Can confirm that multiplayer.dev was briefly down during one of our deployments but it's fully back up.
