### ISSUE TITLE
404 page not found after clicking on `developers guide` in DEVELOPERS.md

### ISSUE THREAD

**Issue by Gautam-Arora24** [supabase/supabase#10748]
# Bug report

## Describe the bug
There seems to be a wrong url present in DEVELOPERS.md under `Local Development` section. The developers guide url is broken.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'DEVELOPERS.md'
2. Scroll down to 'Local Development`
4. Click on Developers Guide

## Screenshots
![Screenshot 2022-12-06 at 3 59 56 PM](https://user-images.githubusercontent.com/53913514/205887097-8d7a6e78-fdbf-4f55-9454-3effa81e26bd.png)

**Comment by AniruddhaSoni** [comment]
Hey, can I contribute to this bug?

**Comment by Gautam-Arora24** [comment]
Yes @AniruddhaSoni! Before making PR, please confirm what should be the correct URL?

**Comment by AniruddhaSoni** [comment]
@Gautam-Arora24, year ofcourse 😓

**Comment by Hallidayo** [comment]
Hi @Gautam-Arora24 & @AniruddhaSoni - I think the .md file for the link has been removed as I believe the docs are now part of the monorepo. So I think you can just remove the following line from DEVELOPERS.md:

If you are working on the docs site, please refer to this developers guide.
