### ISSUE TITLE
extended attributes not supported on macos on local

### ISSUE THREAD

**Issue by ScarVite** [supabase/supabase#10745]
# Bug report

## Describe the bug

When trying to upload a file/image using the supabase-js client to a locally hosted supabase instance, i get the error 
```
The file system does not support extended attributes or has the feature disabled
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Launch Supabase locally
2. Create a Bucket
3. Try to upload a picture
```javascript
await supabase.storage.from('certificates').upload(path, file);
```

## Expected behavior

The upload works
## System information

- OS: macOs 12.6.1
- Browser: Chrome 108.0.5359.94
- Version of supabase-js: 2.1.0
- Version of Node.js: 19.1.0 (local version)

## Additional context

same problem as in #9539

**Comment by burmecia** [comment]
To make Storage work on macOS, you need to choose `VirtioFS` for file sharing implementation in Docer. See details: https://supabase.com/docs/guides/resources/self-hosting/docker#file-storage-backend-on-macos
