### ISSUE TITLE
Cannot connect anymore to realtime broadcast

### ISSUE THREAD

**Issue by JSmithOner** [supabase/supabase#10743]
# Bug report

## Describe the bug

WebSocket connection fails

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

try to connect to any realtime channel

## Expected behavior

should connect

## System information

- OS:MacOs Monterey
- Browser CHROME
- Version of supabase-js:"@supabase/supabase-js": "^2.0.0-rc.8"

## Additional context

```
Log ID
dadf89f2-50e6-4d2d-bc72-928cb4cb8a93

Log Timestamp (UTC)
2022-12-06T06:41:55.447Z

Log Event Message
Auth error: {:error, :signature_error}
```

```
Log Metadata
[
  {
    "callers": [],
    "context": [
      {
        "application": "realtime",
        "domain": [
          "elixir"
        ],
        "file": "lib/realtime_web/channels/user_socket.ex",
        "function": "connect/3",
        "gl": "<0.2725.0>",
        "line": 72,
        "mfa": [
          "Elixir.RealtimeWeb.UserSocket",
          "connect",
          "3"
        ],
        "module": "Elixir.RealtimeWeb.UserSocket",
        "pid": "<0.23367.176>",
        "time": 1670308915447202,
        "vm": [
          {
            "node": "realtime-prod@fdaa:0:cc:a7b:c07e:953a:a823:2"
          }
        ]
      }
    ],
    "depth": null,
    "error_logger": [],
    "error_string": null,
    "external_id": "project-id",
    "formatter_error_params": [],
    "level": "error",
    "logger_pubsub_backend": [],
    "project": "project-id",
    "request_id": null,
    "stacktrace": [],
    "tenant_params": []
  }
]

```

**Comment by xerod** [comment]
I have the same error here. Do you use a custom JWT for your app authentication? I'm using a custom JWT on my app, so I assume that would be a problem.

**Comment by JSmithOner** [comment]
@xerod  Yes I saw that but back in the days I rememeber the demo wasn't working too so I don't know if it's related. Thanks for your comment I feel less alone. I don't think I use a custom JWT even though I think I might have my anon key.

**Comment by JSmithOner** [comment]
@otaux I'm using the v2 so I don't think it's related to v1.
