### ISSUE TITLE
Self hosting with docker essentially broken

### ISSUE THREAD

**Issue by wunderkind2k1** [supabase/supabase#10785]
# Bug report

&TLDR:
docker-compose aka self hosting with docker is essentially broken as the studio docker image doesn't work together with the .env file for docker-compose from the documentation.

## Describe the bug

https://supabase.com/docs/guides/hosting/docker states that everything necessary to be done for using supabase selfhosted with docker is to change the local .env file for docker-compose and then run.
This is not true and leads to an annoying bug situation: Given you change the password ```POSTGRES_PASSWORD```  in .env
to some individual password like stated in the above link your studio will immediately refuse to connect like so:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/552617/206242522-bbe42b6e-fae5-4dff-a6a1-14fc533eaedc.png">

Reason is this file https://github.com/supabase/supabase/blob/master/studio/.env which contains a statically set  ```POSTGRES_PASSWORD```. This leads to a static default password directly baked into the docker image of _studio_ during docker build leading to it to being published and used within docker-compose-yml at https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L11

_One possible workaround is to change the .env file in studio and build the studio docker image on you own._

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Checkout repo as stated at https://supabase.com/docs/guides/hosting/docker
2. Change ```POSTGRES_PASSWORD``` in the .env file to something you like
3. Start with ```docker-compose up (-d if you want)```
4: Access ```http://localhost:3000```
5: See <img width="422" alt="image" src="https://user-images.githubusercontent.com/552617/206242522-bbe42b6e-fae5-4dff-a6a1-14fc533eaedc.png">

## Expected behavior

There should only be one config file that is used. Studio should not have one of its own. Especially this should not be put into its docker image. It could maybe move into the ```/volumes``` subfolder and be mounted in the container. Plus: the documentation needs updates then.

## Screenshots

see above

## System information

- OS: doesn't apply because of docker
- Browser doesn't apply because its a 'backend' thing
- Version of supabase-js: for studio: this docker image: 0.22.08
- Version of Node.js: not relevant

**Comment by kiwicopple** [comment]
Hi all - this should be fixed with the latest docker images. Are you still experiencing the issue?

**Comment by wunderkind2k1** [comment]
It's working again. See this image (.env file with individual password and vscode with postgress access and configuration file with the invidual password).

![image](https://user-images.githubusercontent.com/552617/208708149-81ffa327-3492-4aa2-b87a-bd8c7d08f2e9.png)

studio on localhost:3000 works too.

![image](https://user-images.githubusercontent.com/552617/208708252-b10f80b8-989e-4c7f-a6bd-83e9dfccb596.png)

Thank you for your support. Would you mind pointing to the fixing commit?

**Comment by kiwicopple** [comment]
that's great news - thanks for taking the time to check again @wunderkind2k1 

I don't have the exact commit, but it would have been one from last week in the studio branch:
https://github.com/supabase/supabase/compare/master...studio

**Comment by darmie** [comment]
I can't even access the dashboard it's not opening
