### ISSUE TITLE
Phone auth with textlocal is not working

### ISSUE THREAD

**Issue by MeetChaudhari** [supabase/supabase#10820]
Could not find any documentation regarding with textlocal integration,

Filled all the necessary details 
I.e API key, SENDER and the message template,
but it does not work.

It keep throwing this error whenever i try it.
`textlocal error: Internal Error`

I tried their native api it seems to work just fine.

But having serious issues with supabase intergration.

**Comment by acetrondi** [comment]
It appears that there might be an issue with the Textlocal integration in the supabase/gotrue codebase. When attempting to send a request to their endpoint, it results in an internal error:
``` json
{
	"code": 400,
	"msg": "Error sending confirmation sms: textlocal error: Internal Error"
}
```
However, sending a request to the same Textlocal endpoint through a REST client seems to work fine. I would recommend the Supabase team to investigate this matter further and look into the integration code to identify and address the internal error.
