### ISSUE TITLE
Postgresql port 5432 is already in use error.

### ISSUE THREAD

**Issue by hwr12** [supabase/supabase#10837]
# Bug report

## Describe the bug

I get postgresql port 5432 is already in use error.  I am currently running docker on synology NAS and I am aware of that other packages in synology(plex server, photo station etc. ) already uses postgresql.
I don't want stop those packages for supabase rather I want my supabase to work without killing other process that use postgresql. 

## To Reproduce
`sudo docker-compose up -d`

## Expected behavior

localhos:3000 opens up supabase studio with table editing function

## Screenshots
<img width="1124" alt="Termius-2022 12 11 00 08-000408" src="https://user-images.githubusercontent.com/54504396/206862058-aac55a16-dd52-4018-9276-d14370feeaf5.png">
<img width="1614" alt="Google Chrome-2022 12 11 00 15-000410" src="https://user-images.githubusercontent.com/54504396/206862165-c86141dc-a8ca-44d6-808e-80ef680c048a.png">

## System information

- Synology NAS DS220+
- OS : DSM 7.1.1-42962 Update 1

**Comment by burmecia** [comment]
A workaround is to replace [this line](https://github.com/supabase/supabase/blob/26d3c30cf1bab7d41878f0a17626ae7609302417/docker/docker-compose.yml#L200), with port number `6432` or port number other than `5432`.

From
```
      - ${POSTGRES_PORT}:5432
```

To
```
      - 6432:5432
```

**Comment by Hallidayo** [comment]
Hi @burmecia - I was having the same issue as @hwr12 but your workaround has worked to get docker running. However when I connect onto localhost:8082 I get the following in the console:

<img width="1297" alt="Screenshot 2022-12-13 at 17 30 01" src="https://user-images.githubusercontent.com/22655069/207403531-4ba049bc-bb8f-4477-8352-328b8bdd37f4.png">

Do you know what might be causing this?

**Comment by burmecia** [comment]
@Hallidayo , that error looks like the ssl cert issue, may not related to this issue.

**Comment by burmecia** [comment]
see solution at https://github.com/supabase/supabase/issues/10837#issuecomment-1345828080.

**Comment by OrhanTozan** [comment]
The above solution is a bit outdated.

New solution: in supabase/docker/.env, set the POSTGRES_PORT constant from 5432 to 6432.
