### ISSUE TITLE
Reset Password for Email documentation for React uses deprecated function

### ISSUE THREAD

**Issue by MIPB** [supabase/supabase#10834]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/v1/auth-api-resetpasswordforemail#reset-password-react

## Describe the problem

In the section Reset Password React, the function "update" is called, when in reality the function is "updateUser".

Current state of the docs:

`await supabase.auth.update({
        password: newPassword,
      })
`

**Comment by GaryAustin1** [comment]
You are looking at v1 docs.  Note the select at the top of screen and v1 in your link.
![image](https://user-images.githubusercontent.com/54564956/206863910-25d5af58-98d8-457c-b93e-38d305d9c0f2.png)

**Comment by MIPB** [comment]
Indeed, I did not see that dropdown.

thank you @GaryAustin1

**Comment by MIPB** [comment]
Closing issue
