### ISSUE TITLE
Storage: Internal server error on upload

### ISSUE THREAD

**Issue by itschip** [supabase/supabase#10845]
# Bug report

## Describe the bug

When I try to upload a object an public bucket, I get "Internal server error" back. 
Using React Native with Expo

## To Reproduce
Select an image from the image picker and upload it with the code below

```ts
export async function uploadImageAsync(
  uri: string,
  fileName: string
): Promise<string> {
  const blob: any = await new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.onload = function () {
      resolve(xhr.response);
    };
    xhr.onerror = function (e) {
      console.log(e);
      reject(new TypeError("Network request failed"));
    };
    xhr.responseType = "blob";
    xhr.open("GET", uri, true);
    xhr.send(null);
  });

  const { data, error } = await supabase.storage
    .from("images")
    .upload(`public/${fileName}`, blob, { cacheControl: "3600", upsert: true });

  if (error) {
    // Internal server error
    console.error(`Failed to upload to storage. Error: ${error.message}`);
  }

  // We're done with the blob, close and release it
  blob.close();

  const { data: url } = supabase.storage.from("images").getPublicUrl(fileName);

  return url.publicUrl;
}
```

## Expected behavior
Image being uploaded to my public bucket

## System information

- OS: macOS
- Version of supabase-js: 2.1.3
- Version of Node.js: 18.12.1

**Comment by GaryAustin1** [comment]
I know nothing about react native... but did you read this note...
`For React Native, using either Blob, File or FormData does not work as intended. Upload file using ArrayBuffer from base64 file data instead, see example below.`
https://supabase.com/docs/reference/javascript/storage-from-upload#notes

**Comment by itschip** [comment]
Of course I failed to read that, jfc. Thanks.

**Comment by karuzo17** [comment]
For me the example does not work. I am always getting corrupted files uploaded in the storage.
