### ISSUE TITLE
Having e-mail auth provider enabled rate limiting other auth providers usage

### ISSUE THREAD

**Issue by rohanmayya** [supabase/supabase#10850]
# Bug report

Having e-mail auth provider enabled gives a 429 rate limit exceeded, despite using only Phone auth provider.

## Describe the bug

We had e-mail auth provider and phone auth provider enabled. (With e-mail auth not being used.) Once we started getting a spike in traffic for our SMS OTPs, we started getting a 429 rate limit exceeded, despite Twilio looking fine on our end. Once we disabled e-mail auth as a provider, everything was working normally again. 

## To Reproduce

1. Enable e-mail and phone auth providers,
2. Try hitting rate limits that you would normally hit, but with phone SMSs,
3. Get a 429 - Rate Limit Exceeded.
4. Disable E-mail auth, and check that everything is working again.

## Expected behavior

Did not expect any rate limit issues.

## System information

- Browser: Chrome,
- Version of "@supabase/supabase-js": "^2.1.1",
- Version of Node.js: [e.g. 16.13.1]

**Comment by kiwicopple** [comment]
this was probably during the migration - fixed now.

Thanks for reporting it @rohanmayya

**Comment by Ivaylo-Korakov** [comment]
I am developing my app and I am getting rate limited no matter what email I use

**Comment by Axiom0599** [comment]
same problem. Whenever I hit the submit button, I get this error that says Email rate limit exceeded.

**Comment by joshuarice** [comment]
AuthApiError {
    __isAuthError: true,
    name: 'AuthApiError',
    status: 429,
    stack: 'AuthApiError: Email rate limit exceeded\n' +
      '    at eval (webpack-internal:///(app-client)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:49:20)',
    message: 'Email rate limit exceeded'
  }

**Comment by aryankush25** [comment]
I am also facing the same issue while using Supabase in Flutter.

**Comment by shamil-aliev** [comment]
Same here

**Comment by Noitham** [comment]
Getting this issue too 🤔

**Comment by jessedoka** [comment]
I also have the same issue?

**Comment by thedatingapp2023** [comment]
same error since yesterday..

**Comment by sgarchavada** [comment]
first time using supabase today. 
just created demo projec in supabase and follow user management app tutorial and try to signup new user, and get this error in Expo app.

My client want me to decide and pick database myself.
I am trying to decide which database is good for a frontend developer who do not have backend experience, . I always used firebase and hasura-graphql and first time trying Supabase today, but find no hope moving forward with.

**Comment by ogzcode** [comment]
I just encountered a similar problem
(Supabase + Vue.js)
code: 429
msg: "Email rate limit exceeded"

**Comment by shamil-aliev** [comment]
UPD. Now it seems to work 🎉

**Comment by thedatingapp2023** [comment]
It was working for a while today, but now it fails again. same error message

**Comment by aleskozelsky** [comment]
Same issue here

**Comment by adityaptikao** [comment]
same error for me it was working just now and now it doesn't

**Comment by sarbjot-14** [comment]
same issue

**Comment by bennik88** [comment]
I'm having the same issue

**Comment by sarbjot-14** [comment]
@bennik88 . They are limiting it for because they are getting spammed. Just use your own smpt by going to the project settings -> auth. I used Brevo, but you can use aws or sendgrid I think

**Comment by ranggabadrus** [comment]
i thought i was the only who suffer this problem.
any solution for this except use custom smtp?

**Comment by oldbettie** [comment]
same issue running locally. weirdly using the production project works fine just not `localhost:4321`

**Comment by minj2me** [comment]
having same issue too..

**Comment by bennik88** [comment]
> @bennik88 . They are limiting it for because they are getting spammed. Just use your own smpt by going to the project settings -> auth. I used Brevo, but you can use aws or sendgrid I think

Thank you for the insights, I also now found more information about it. But at the moment I'm not even sending four emails but always getting the "error: AuthApiError: Email rate limit exceeded" Error message (four per hour should be allowed). This makes local development when prototyping impossible. So it's nearly unusable at the moment without buying and setting up a temporary email SMTP client. I can see their side of things and it's sad that it had been abused. I hope they will find a better approach to that problem without suffering. As for the moment, this feature is not usable.

**Comment by secret-username** [comment]
I just ran into this problem during some sign-up flow testing. Pausing, then un-pausing the project fixed it for me.

**Comment by jakequade** [comment]
> I just ran into this problem during some sign-up flow testing. Pausing, then un-pausing the project fixed it for me.

Worked for me - thanks a lot @secret-username .

**Comment by shadowdom24** [comment]
> I just ran into this problem during some sign-up flow testing. Pausing, then un-pausing the project fixed it for me.

This worked for me. I also restarted my project under `settings > general`

Also if testing with email CHECK YOUR SPAM FOLDER

**Comment by hyezoprk** [comment]
> I just ran into this problem during some sign-up flow testing. Pausing, then un-pausing the project fixed it for me.

Pause and restart working for me too!

**Comment by dallinmoak** [comment]
> Thank you for the insights, I also now found more information about it. But at the moment I'm not even sending four emails but always getting the "error: AuthApiError: Email rate limit exceeded" Error message (four per hour should be allowed). This makes local development when prototyping impossible. So it's nearly unusable at the moment without buying and setting up a temporary email SMTP client. I can see their side of things and it's sad that it had been abused. I hope they will find a better approach to that problem without suffering. As for the moment, this feature is not usable.
@bennik88,  thanks for sharing. This explains exactly the issues i'm seeing. would you mind sharing where you found the 4/hour rate limit documented? i've been trying hard to find it in writing, and your post is the only reference to their rate limit i've found.

**Comment by ProfiroiuMihai** [comment]
I have a paid membership with a custom smtp enabled and still have the problem. I t was working yesterday today is not working.
Giving me :
{code: 429, msg: "Email rate limit exceeded"}

I have mailjet premium configured that has 50000 emails but still does not work.

Please reopen this thread.

**Comment by sbatururimi** [comment]
Same problem today. Getting 
{code: 429, msg: "Email rate limit exceeded"}
during the testing of sign up. What is the solution?

**Comment by claudio-bizzotto-zupit** [comment]
@sbatururimi the solution should be setting a custom SMTP as shown by @ProfiroiuMihai but for me the problem persists

**Comment by monicakh** [comment]
Sorry for the inconvenience you're experiencing. We've already notified our Auth team, and they have a fix lined up in the queue.

**Comment by monicakh** [comment]
The fix has been rolled out to all affected projects.

**Comment by avert-admin** [comment]
@monicakh sorry but I am also experiencing this issue on a new project I have set up. I have serveral projects using the same code base and never experienced it until now.

**Comment by monicakh** [comment]
Hey @avert-admin, can you submit a support ticket and we will follow up with you from there?

**Comment by coryetzkorn** [comment]
I'm still experience this issue. Adding custom SMTP didn't help. Seeing `{"code":429,"msg":"Email rate limit exceeded"}`

**Comment by jeslyw** [comment]
Still getting this error intermittently with email confirmation while testing auth.signUp, running supabase-js 2.31.0 

Waiting around 15 min between requests works, could this be a rate limit setting issue?

**Comment by hichana** [comment]
I'm getting this save `{code: 429, msg: "Email rate limit exceeded"}` error when trying password reset. It worked previously but now happened to me on the first time I tried it today.

**Comment by onurusluca** [comment]
Still getting this today. I only have one other email registered. What is going on?

**Comment by notflip** [comment]
<img width="342" alt="Screenshot 2023-07-30 at 12 31 42" src="https://github.com/supabase/supabase/assets/4146384/e308f18f-4bf5-437d-a87f-448050fa7587">

I'm seeing an unusual high amount of Auth requests, I've tried logging in using OTP 5 times, how can there be this many requests? Also getting this error, it might be due to the abnormal amount of reqs. How does that look for you guys?

**Comment by jeslyw** [comment]
@notflip from what i understand, those are total requests to all auth endpoints including background health checks etc ! 

found this in the docs which might explain the issue when not using a custom smtp https://supabase.com/docs/guides/auth/auth-smtp : 

> At present, you can trial the Supabase platform by sending up to 4 emails per hour via the built-in service. The default email service as a whole is offered on a best effort basis: we will do our best to maintain it and will review usage of the service on a regular basis to see if the email service should be continued.

**Comment by notflip** [comment]
@jesslyw That makes sense! Thanks for this, I'm going to couple it to my Sendgrid.

**Comment by XDCoder3289** [comment]
AuthApiError: Email rate limit exceeded

Getting this error.

**Comment by DennisWanjiru** [comment]
Getting the same error. Email rate limit exceeded

**Comment by monicakh** [comment]
For everyone that's still facing issues, can you please submit a support ticket? We will help you resolve it.

**Comment by lamroger** [comment]
If you're developing locally, you can use a dockerized version to avoid these limits https://supabase.com/docs/guides/cli/local-development

**Comment by MincePie** [comment]
is there a solution to this. i just added email and the first time i tried to use it in local - i get this error

**Comment by carljustineoyales** [comment]
> > I just ran into this problem during some sign-up flow testing. Pausing, then un-pausing the project fixed it for me.
> 
> This worked for me. I also restarted my project under `settings > general`
> 
> Also if testing with gmail CHECK YOUR SPAM FOLDER

Restarting the project works for me

**Comment by cesswhite** [comment]
I have the same problem
![Captura de Pantalla 2023-08-25 a la(s) 19 07 32](https://github.com/supabase/supabase/assets/44076866/912834ba-7dc1-4a3c-9f6a-53ee9ced8281)

**Comment by engageintellect** [comment]
Same here. It was working shortly. However, the links that is were sending weren't working for me. I tried spinning up a new db, connected to that, changed redirect url to localhost:5173 (for sveltekit), than got the 429.

![image](https://github.com/supabase/supabase/assets/61082194/b19baaf8-0bf1-43a2-bd30-a27998d5bcd1)

**Comment by luisdoc19** [comment]
To all people that have been getting this error, just go to **Authentication** > **Provideres** > **Email**, and disable **confirm Email** or if you want to get email confirm, just configure a your stmp

**Comment by engageintellect** [comment]
> To all people that have been getting this error, just go to **Authentication** > **Provideres** > **Email**, and disable **confirm Email** or if you want to get email confirm, just configure a your stmp

this doesn't solve my 429

**Comment by Malki** [comment]
Got the same error today. Restarting the project worked for me

**Comment by glody007** [comment]
> Same problem today. Getting {code: 429, msg: "Email rate limit exceeded"} during the testing of sign up. What is the solution?

read this [article](https://medium.com/@techalchimiste/how-to-increase-supabase-signup-rate-limit-3000-emails-mo-261289882cf4)

**Comment by brave881** [comment]
same problem

**Comment by enlguy** [comment]
Jesus, doesn't look like much hope here unless I use custom SMTP, or simply use Firebase instead...  I mean, when you can't even test your app in development because of this crap, it just puts a real damper on usage.  First time trying Supabase, might just leave it alone.

**Comment by arslanDev1526** [comment]
getting the same error 429

**Comment by alexwhb** [comment]
I'm having this issue as well.

**Comment by nestorbfgo** [comment]
@aleskozelsky  Hi, A solution is to change your smtp, if you are testing you can use mailtrap https://mailtrap.io/?gad_source=1&gclid=CjwKCAjwg8qzBhAoEiwAWagLrPBEOa2MYCVno91aSA1pgSfaW9LcmuxHEA4EOtQJ6eiMnVRVrlI5qxoC80IQAvD_BwE or you can use resend https://resend.com/ unnafortunally, supabase has rate limit https://supabase.com/docs/guides/auth/rate-limits and you want not deal with this use a smtp service.

**Comment by HenryTorres** [comment]
I solved it by setting up a free SMTP like SendGrid - https://app.sendgrid.com/ - and setting the rate limits to 20 or more per hour.

**Comment by JesacaLin** [comment]
I don't know how helpful or realistic it is but when I got the error, I ended my development environment and restarted it and it seemed to work. Not sure if it reset or something!

**Comment by tsboh** [comment]
The solution I found, is simple and gives enough room to **test supabase out, without having to have an SMTP account** (or get one @resend, or somewhere else).

**Just turn off 'Confirm email'.**

In your Supabase dashboard under Authentication > Providers > Email > Confirm email

So, if you want to register a user without having them confirm the email address, you can just turn off the Confirm email setting from your Supabase dashboard. That's it.

**Comment by alexlozdev** [comment]
![1](https://github.com/user-attachments/assets/2a2b5759-ed7d-4339-a769-b380667d325d)
Error fixed after changing [Rate limit for sending emails]
Default is 2, I changed it to 50

**Comment by tonnoz** [comment]
I'm not following here, shouldn't Supabase use my custom smtp server since I set that up?

**Comment by tonnoz** [comment]
> ![1](https://github.com/user-attachments/assets/2a2b5759-ed7d-4339-a769-b380667d325d) Error fixed after changing [Rate limit for sending emails] Default is 2, I changed it to 50

this is the right answer (if you are already using a smtp server)
