### ISSUE TITLE
"import supabase" snippet in the auto-docs is incorrect

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#109]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Import snippet in the docs is incorrect

![image](https://user-images.githubusercontent.com/10214025/85839491-938ea800-b7cd-11ea-9e69-4088940fde70.png)

This is supposed to say `import { createClient } from '@supabase/supabase-js'`. It's possible that `{ createClient }` is getting clobbered as part of the JS build upon deployment (looks fine on local development)

**Comment by soedirgo** [comment]
Looks like this issue is on the infra side, and @phamhieu already identified and made the [fix](https://github.com/supabase/infrastructure/commit/46345a101bfeb99d3aa9fb1e4fe976cf476845fd).

**Comment by kiwicopple** [comment]
Nice, will close this one tmr once we deploy
