### ISSUE TITLE
Error 500 Supabase CLI Docs

### ISSUE THREAD

**Issue by abarcod** [supabase/supabase#10900]
# Bug report

## Describe the bug
Internal Server Error when visiting Supabase CLI docs.

## To Reproduce

1. Go to '[Supabase CLI](https://supabase.com/docs/reference/cli/usage)'

## Screenshots

![Unbenannt](https://user-images.githubusercontent.com/96572110/207280025-e6ac8b42-b977-4011-8803-e729ae5f1b46.PNG)

## System information

- OS: Windows
- Browser (if applies) chrome

**Comment by MagnusHJensen** [comment]
Can't reproduce.

**Comment by Hallidayo** [comment]
Hi @abarcod & @MagnusHJensen -  This was fixed in #10923
