### ISSUE TITLE
Cannot Enable Any Extension

### ISSUE THREAD

**Issue by iwootten** [supabase/supabase#10928]
# Bug report

## Describe the bug

Cannot enable any extensions for any project. Includes old (over 1 year) and a brand new instance.

Every time I go to enable the http extension within my hosted db I get asked which schema to enable it for? 

When I select "extensions", it errors with "Failed to create schema: Invalid SQL query"

This step doesn't appear in the docs for extensions as far as I can tell. I've tried for multiple extensions with the same issue present.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database'
2. Click on 'Extensions'
3. Scroll down to an extension and enable it
4. See error in top right

## Expected behavior

The extension is enabled

## Screenshots

![Xnapper-2022-12-13-17 03 44](https://user-images.githubusercontent.com/3598161/207402256-bc608b5d-f67b-44f9-9419-9c36eaa13798.png)

![Xnapper-2022-12-13-17 27 11](https://user-images.githubusercontent.com/3598161/207402500-9f4b1b1f-0018-4865-b9f8-b0854bce9356.png)

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: latest hosted

**Comment by MagnusHJensen** [comment]
I would love to help you, but apparently the local development setup does not work with just installing and then running `npm run dev` so they need to re-look their CONTRIBUTE.md file.

Anyways, for anyone investigating this, this error happens here: https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Database/Extensions/EnableExtensionModal.tsx#L66

**Comment by iwootten** [comment]
Can confirm this is issue is fixed and no longer present in the hosted version.
