### ISSUE TITLE
Description of examples is missing in Flutter docs

### ISSUE THREAD

**Issue by Vinzent03** [supabase/supabase#10929]
# Bug report

## Describe the bug

The [description](https://github.com/supabase/supabase/blob/master/spec/supabase_dart_v1.yml#L540) of the second example is missing on the docs website.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/reference/dart/update
2. Click on the json example
3. See the missing description

## Expected behavior

See the description, because it contains useful information.

**Comment by Hallidayo** [comment]
I can look into this?

**Comment by Vinzent03** [comment]
@Hallidayo Sorry I'm not sure what you mean. Are you just asking for trying to solve this, or do you need more information?

**Comment by Hallidayo** [comment]
@Vinzent03 Yeah sorry should have been more clear, I'll create a pull for this.
