### ISSUE TITLE
The file system does not support extended attributes on windows server

### ISSUE THREAD

**Issue by pckimlong** [supabase/supabase#10977]
# Bug report

## Describe the bug

I got this error when trying to host supabase on windows server 2019 docker

`The file system does not support extended attributes or has the feature disabled`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start Supabase docker locally
2. Open studio at localhost:3000
4. Create bucket in storage UI
5. Upload a file

## Expected behavior

Upload work

## System information

- OS:  Windows Server 2019

## Additional context

I saw there others has the same problem but they are on MacOS, but I am Windows OS

**Comment by pckimlong** [comment]
I try do it on docker windows 11, Everything work find. Seem like only docker on MacOS and Windows Server has this issue

**Comment by JiangXin-1215** [comment]
same problem,os windows 11

the log is

2023-02-09 09: 07: 09 {
    "level": "info",
    "time": "2023-02-09T01:07:09.742Z",
    "pid": 18,
    "hostname": "a04d50663e28",
    "reqId": "req-7",
    "tenantId": "stub",
    "project": "stub",
    "req": {
        "method": "GET",
        "url": "/bucket",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_real_ip": "172.18.0.1",
            "x_client_info": "supabase-js/2.1.1",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
            "accept": "*/*",
            "referer": "http://localhost:3000/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "172.18.0.5",
        "remotePort": 50318
    },
    "res": {
        "statusCode": 200
    },
    "responseTime": 7.564552999800071,
    "msg": "GET | 200 | 172.18.0.5 | req-7 | /bucket | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}
2023-02-09 09: 07: 09 {
    "level": "info",
    "time": "2023-02-09T01:07:09.807Z",
    "pid": 18,
    "hostname": "a04d50663e28",
    "reqId": "req-8",
    "tenantId": "stub",
    "project": "stub",
    "results": [],
    "msg": "results"
}
2023-02-09 09: 07: 09 {
    "level": "info",
    "time": "2023-02-09T01:07:09.808Z",
    "pid": 18,
    "hostname": "a04d50663e28",
    "reqId": "req-8",
    "tenantId": "stub",
    "project": "stub",
    "req": {
        "method": "POST",
        "url": "/object/list/brand",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_real_ip": "172.18.0.1",
            "content_length": "89",
            "x_client_info": "supabase-js/2.1.1",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
            "content_type": "application/json",
            "accept": "*/*",
            "referer": "http://localhost:3000/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "172.18.0.5",
        "remotePort": 50318
    },
    "res": {
        "statusCode": 200
    },
    "responseTime": 11.368531999876723,
    "msg": "POST | 200 | 172.18.0.5 | req-8 | /object/list/brand | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}
2023-02-09 09: 07: 15 {
    "level": "info",
    "time": "2023-02-09T01:07:15.518Z",
    "pid": 18,
    "hostname": "a04d50663e28",
    "reqId": "req-a",
    "tenantId": "stub",
    "project": "stub",
    "msg": "content-type is multipart/form-data; boundary=----WebKitFormBoundaryoBksykU7pbNEmEvT"
}
2023-02-09 09: 07: 15 {
    "level": "info",
    "time": "2023-02-09T01:07:15.571Z",
    "pid": 18,
    "hostname": "a04d50663e28",
    "reqId": "req-a",
    "tenantId": "stub",
    "project": "stub",
    "req": {
        "method": "POST",
        "url": "/object/brand/aboluo.png",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_real_ip": "172.18.0.1",
            "content_length": "4856",
            "x_client_info": "supabase-js/2.1.1",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
            "content_type": "multipart/form-data; boundary=----WebKitFormBoundaryoBksykU7pbNEmEvT",
            "accept": "*/*",
            "referer": "http://localhost:3000/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "172.18.0.5",
        "remotePort": 50318
    },
    "res": {
        "statusCode": 500
    },
    "responseTime": 54.098706000018865,
    "error": {
        "name": "Error",
        "httpStatusCode": 500,
        "originalError": {
            "code": "ENOTSUP",
            "errno": 95
        }
    },
    "msg": "POST | 500 | 172.18.0.5 | req-a | /object/brand/aboluo.png | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}

**Comment by DenisBessa** [comment]
I have the same problem using a NFS server

**Comment by tanelainla** [comment]
Same issue on MacOS 13.2.1 with Docker 4.16.2 (95914)

**Comment by GabrielRozendo** [comment]
> Same issue on MacOS 13.2.1 with Docker 4.16.2 (95914).
> 
> Update: Setting Docker to use **VirtioFS** solved the issue.

Thanks @tanelainla 
it worked for me as well

**Comment by somebodyawesome-dev** [comment]
@morandalex  did find any solution on ubuntu ?

**Comment by thedarkknight197** [comment]
Same issue on Docker MacOS using web interface

**Comment by thedarkknight197** [comment]
> Setting Docker to use **VirtioFS** solved the issue.

sny guide?

**Comment by ayush0402** [comment]
Having this problem on Linux (PopOS 22.04), any solutions for this?

**Comment by lopes221** [comment]
Hi @mart-so did you manage to fix it ?

**Comment by lopes221** [comment]
Ive got the same issue but no solution found so far

**Comment by Crayon-ShinChan** [comment]
> > Setting Docker to use **VirtioFS** solved the issue.
> 
> sny guide?

In Mac, Go to docker desktop, setting -> General -> Choose VirtioFS

**Comment by ethicnology** [comment]
> > ny guid
> 
> This is only for MAC users, right?!

I face the same issue
Supabase self-hosted container is running on Debian 12 through an SSH tunnel to my Apple M2

**Comment by lopes221** [comment]
Hi @ethicnology , I managed to fix by reinstalling docker.
Actually I got rid of docker desktop, removed everything and reinstalled the Docker engine normally on my UBuntu 22.04

https://docs.docker.com/desktop/uninstall/
and then reinstall
https://docs.docker.com/engine/install/

**Comment by ethicnology** [comment]
> Hi @ethicnology , I managed to fix by reinstalling docker. Actually I got rid of docker desktop, removed everything and reinstalled the Docker engine normally on my UBuntu 22.04
> 
> https://docs.docker.com/desktop/uninstall/ and then reinstall https://docs.docker.com/engine/install/

Thank you, but unfortunately I don't have docker desktop installed, it's already docker engine latest on a server (Debian 12)
I'm communicating to it through an SSH tunnel

**Comment by ethicnology** [comment]
**Error: The file system does not support extended attributes or has the feature disabled**
<details><summary>Logs</summary>
supabase-storage                | {"level":30,"time":"2023-12-17T15:43:26.619Z","pid":1,"hostname":"227d3cf9dd6b","reqId":"req-g","tenantId":"stub","project":"stub","reqId":"req-g","type":"request","req":{"traceId":"req-g","method":"POST","url":"/object/cover/2.webp","headers":{"host":"storage:5000","x_forwarded_proto":"http","x_forwarded_host":"localhost","x_forwarded_port":"8000","x_real_ip":"10.19.117.1","content_length":"160272","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0","accept":"*/*","referer":"http://localhost:8000/project/default/storage/buckets/cover","x_client_info":"supabase-js-web/2.38.3","x_upsert":"false","content_type":"multipart/form-data; boundary=---------------------------3057375370816069312558379801"},"hostname":"storage:5000","remoteAddress":"172.19.0.10","remotePort":32770},"res":{"statusCode":500,"headers":{"content_type":"application/json; charset=utf-8","content_length":"130"}},"responseTime":241.9572240114212,"error":{"raw":"{\"name\":\"Error\",\"httpStatusCode\":500,\"userStatusCode\":500,\"originalError\":{\"code\":\"ENOTSUP\",\"errno\":95}}","name":"Error","message":"The file system does not support extended attributes or has the feature disabled.","stack":"Error: The file system does not support extended attributes or has the feature disabled.\n    at StorageBackendError.fromError (/app/dist/storage/errors.js:46:16)\n    at FileBackend.uploadObject (/app/dist/storage/backend/file.js:74:48)\n    at async Uploader.upload (/app/dist/storage/uploader.js:55:36)\n    at async ObjectStorage.uploadNewObject (/app/dist/storage/object.js:29:35)\n    at async Object.<anonymous> (/app/dist/http/routes/object/createObject.js:42:46)"},"msg":"stub | POST | 500 | 172.19.0.10 | req-g | /object/cover/2.webp | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"}
supabase-kong                   | 172.19.0.7 - - [17/Dec/2023:15:43:26 +0000] "POST /storage/v1/object/list/cover HTTP/1.1" 200 2 "-" "node"
supabase-storage                | {"level":30,"time":"2023-12-17T15:43:26.867Z","pid":1,"hostname":"227d3cf9dd6b","reqId":"req-h","tenantId":"stub","project":"stub","reqId":"req-h","type":"request","req":{"traceId":"req-h","method":"POST","url":"/object/list/cover","headers":{"host":"storage:5000","x_forwarded_proto":"http","x_forwarded_host":"kong","x_forwarded_port":"8000","x_real_ip":"172.19.0.7","content_length":"165","content_type":"application/json","x_client_info":"supabase-js-node/2.38.3","accept":"*/*","user_agent":"node"},"hostname":"storage:5000","remoteAddress":"172.19.0.10","remotePort":60986},"res":{"statusCode":200,"headers":{"content_type":"application/json; charset=utf-8","content_length":"2"}},"responseTime":40.00315898656845,"msg":"stub | POST | 200 | 172.19.0.10 | req-h | /object/list/cover | node"}

<p>



</p>
</details>

**Comment by lopes221** [comment]
@ethicnology Then start it as sudo or clean it up and re-install it with sudo, then it should solve the problem, this issue is related to Docker permission on writing, then sudo privileges should resolve it, I honestly didn't investigate much since I had other priorities, but the short period I have seem, that was my understood of the issue.

**Comment by ethicnology** [comment]
**sudo** didn't help, but I will try to redeploy on a fresh server

<details><summary>Logs</summary>
<p>

supabase-storage                | {"level":30,"time":"2023-12-18T15:12:17.946Z","pid":1,"hostname":"499a4c8948ab","jodId":"","type":"event","event":"ObjectAdminDelete","payload":"{\"name\":\"Untitled.jpg\",\"bucketId\":\"test\",\"tenant\":{\"ref\":\"stub\",\"host\":\"localhost\"},\"version\":\"e7f8e9ac-ad0e-4313-9495-427374438526\",\"reqId\":\"req-y\",\"$version\":\"v1\"}","objectPath":"stub/test/Untitled.jpg","tenantId":"stub","project":"stub","reqId":"req-y","msg":"[Admin]: ObjectAdminDelete stub/test/Untitled.jpg"}
supabase-kong                   | 10.19.117.1 - - [18/Dec/2023:15:12:18 +0000] "POST /storage/v1/object/test/Untitled.jpg HTTP/1.1" 500 130 "http://localhost:8000/project/default/storage/buckets/test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"
supabase-storage                | {"level":30,"time":"2023-12-18T15:12:18.018Z","pid":1,"hostname":"499a4c8948ab","reqId":"req-y","tenantId":"stub","project":"stub","reqId":"req-y","type":"request","req":{"traceId":"req-y","method":"POST","url":"/object/test/Untitled.jpg","headers":{"host":"storage:5000","x_forwarded_proto":"http","x_forwarded_host":"localhost","x_forwarded_port":"8000","x_real_ip":"10.19.117.1","content_length":"5825","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0","accept":"*/*","referer":"http://localhost:8000/project/default/storage/buckets/test","x_client_info":"supabase-js-web/2.38.3","x_upsert":"false","content_type":"multipart/form-data; boundary=---------------------------84013450922543696563518664756"},"hostname":"storage:5000","remoteAddress":"172.20.0.7","remotePort":50720},"res":{"statusCode":500,"headers":{"content_type":"application/json; charset=utf-8","content_length":"130"}},"responseTime":340.11541399359703,"error":{"raw":"{\"name\":\"Error\",\"httpStatusCode\":500,\"userStatusCode\":500,\"originalError\":{\"code\":\"ENOTSUP\",\"errno\":95}}","name":"Error","message":"The file system does not support extended attributes or has the feature disabled.","stack":"Error: The file system does not support extended attributes or has the feature disabled.\n    at StorageBackendError.fromError (/app/dist/storage/errors.js:46:16)\n    at FileBackend.uploadObject (/app/dist/storage/backend/file.js:74:48)\n    at async Uploader.upload (/app/dist/storage/uploader.js:55:36)\n    at async ObjectStorage.uploadNewObject (/app/dist/storage/object.js:29:35)\n    at async Object.<anonymous> (/app/dist/http/routes/object/createObject.js:42:46)"},"msg":"stub | POST | 500 | 172.20.0.7 | req-y | /object/test/Untitled.jpg | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"}

</p>
</details>

**Comment by KevinBrolly** [comment]
Hey all, I am going to close this issue in favour of #20096 so that we do not have multiple issues open for the same bug/problem.

There is an open (as of writing yet-to-be-merged) change that should alleviate this issue more broadly - https://github.com/supabase/supabase/pull/17779

If you feel this issue should not be closed yet please let us know and we can re-examine.
