### ISSUE TITLE
Permission error when backing up the database with `pg_dump`

### ISSUE THREAD

**Issue by amr3k** [supabase/supabase#10982]
# Bug report

## Describe the bug

I have a project that I need to make a local backup of, I have database triggers and functions.

When I tried this command `pg_dump 'postgresql://postgres:password@db.id.supabase.co:5432/postgres' > backup.sql`
It gave me this error:
```sql
pg_dump: error: query failed: ERROR:  permission denied for table hooks
pg_dump: error: query was: LOCK TABLE supabase_functions.hooks IN ACCESS SHARE MODE
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a database function with trigger type
2. Create a database trigger that fires that function
3. Try `pg_dump`

## Expected behavior

Backup to be completed

## System information

- OS: Linux
- Browser Firefox
- Version of supabase-js: 2.2.0
- Version of Node.js: v19.2.0

## Additional context

I did **NOT** mess with permissions, I also tried DBeaver and faced the same issue

**Comment by sweatybridge** [comment]
Hello, could you try granting the following permissions through the SQL Editor to fix this issue?

```sql
GRANT ALL ON ALL TABLES IN SCHEMA supabase_functions TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA supabase_functions TO postgres;
GRANT ALL ON ALL ROUTINES IN SCHEMA supabase_functions TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON ROUTINES TO postgres;
GRANT supabase_functions_admin TO postgres;
```

Let me know if pg_dump works after that.

**Comment by Geczy** [comment]
> ```sql
> GRANT ALL ON ALL TABLES IN SCHEMA supabase_functions TO postgres;
> GRANT ALL ON ALL SEQUENCES IN SCHEMA supabase_functions TO postgres;
> GRANT ALL ON ALL ROUTINES IN SCHEMA supabase_functions TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON TABLES TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON SEQUENCES TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON ROUTINES TO postgres;
> GRANT supabase_functions_admin TO postgres;
> ```

i have this same issue and can report this did not work

![image](https://user-images.githubusercontent.com/1036968/209259674-eb78d1ab-014c-4eab-909e-6590d9ee40c2.png)

**Comment by abhay187** [comment]
Hey, @sweatybridge isn't that script messing up my database permissions for the future? 
Will I have to change some permission if I want to restore the backup in the future?

**Comment by Geczy** [comment]
This comment solved it for me:

https://github.com/supabase/supabase/issues/1856#issuecomment-1194013448

Adding -N supabase_functions

```
➜  ~ pg_dump -d "postgresql://postgres:<pass>@db.<projectid>.supabase.co:5432/postgres" --no-comments -N supabase_functions -N auth -N realtime > out.sql
```

**Comment by amr3k** [comment]
> This comment solved it for me:
> 
> [#1856 (comment)](https://github.com/supabase/supabase/issues/1856#issuecomment-1194013448)
> 
> Adding -N supabase_functions
> 
> ```
> ➜  ~ pg_dump -d "postgresql://postgres:<pass>@db.<projectid>.supabase.co:5432/postgres" --no-comments -N supabase_functions -N auth -N realtime > out.sql
> ```

Thanks @Geczy , but for a better approach, I used these extra options `-F c -v -f db.dump` to be able to restore it with `pg_restore`

**Comment by Geczy** [comment]
awesome, then i changed my dump to

```bash
pg_dump -d "${DATABASE_URL%\?*}" \
    --no-comments \
    -F c -v \
    -N supabase_functions \
    -f "$backup_file"
```

**Comment by bzmillerboy** [comment]
The SQL that @sweatybridge posted did not work, permissions denied. However, the following ran successfully and allowed me to run `npx supabase db dump -f supabase/data.sql --data-only` successfully.


```
GRANT ALL ON ALL TABLES IN SCHEMA supabase_functions TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA supabase_functions TO postgres;
GRANT ALL ON ALL ROUTINES IN SCHEMA supabase_functions TO postgres;
GRANT supabase_functions_admin TO postgres;
```

**Comment by Akash187** [comment]
> ```sql
> GRANT ALL ON ALL TABLES IN SCHEMA supabase_functions TO postgres;
> GRANT ALL ON ALL SEQUENCES IN SCHEMA supabase_functions TO postgres;
> GRANT ALL ON ALL ROUTINES IN SCHEMA supabase_functions TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON TABLES TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON SEQUENCES TO postgres;
> ALTER DEFAULT PRIVILEGES IN SCHEMA supabase_functions GRANT ALL ON ROUTINES TO postgres;
> GRANT supabase_functions_admin TO postgres;
> ```

@sweatybridge 
<img width="1132" alt="Screenshot 2023-10-30 at 4 00 58 PM" src="https://github.com/supabase/supabase/assets/21134455/1db02f76-81b9-4c3d-9c3d-fd5da0a9c0c2">
 Getting Error ERROR:  42501: permission denied for table hooks
