### ISSUE TITLE
Intermittent image resizing API errors

### ISSUE THREAD

**Issue by madeleineostoja** [supabase/supabase#10990]
# Bug report

## Describe the bug

I'm getting intermittent 422 errors when requesting images using the new image resizing API on Supabase storage. The error message is `Invalid source image`, but requesting the image directly (with no transforms) is successful.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Using an example image that is currently erroring for me:

1. Go to https://api.bokeh.photo/storage/v1/render/image/public/images/7dde4921-196e-45d1-b5db-6a8c5a25b88b/4abe1db4-2cd4-491b-86bf-1829a78207ea.jpg
2. See it succeed
3. Add a transform, eg: https://api.bokeh.photo/storage/v1/render/image/public/images/7dde4921-196e-45d1-b5db-6a8c5a25b88b/4abe1db4-2cd4-491b-86bf-1829a78207ea.jpg?width=100

## Expected behavior

Image resizing API should not randomly fail with images that have valid sources

## Screenshots

<img width="590" alt="Screenshot 2022-12-15 at 2 56 06 PM" src="https://user-images.githubusercontent.com/6374876/207754310-9c36fb97-4275-4e3c-a56b-981135e37d60.png">

**Comment by madeleineostoja** [comment]
Fixed after contacting supabase support about, thanks team!

**Comment by ozum** [comment]
@madeleineostoja, could you please explain to others looking for the same issue?
