### ISSUE TITLE
Unable to search docs with SQL functions and types like query: array_remove for example

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/supabase#11028]
The new docs don't allow me to find out how I do many basic Postgres operations with the JS library.

For example how do I append to an array? How do I remove from an array? If I'm writing SQL I should cast a string to a more precise type like UUID for example, how do I do the with the JS library?

I understand if this example is impossible. I just think that the Docs should be searchable with common SQL operations and at least explain to the user that something is impossible to do with the JS client library and suggest how it could be done. 

Many answers are already there somewhat in the discussions area but this knowledge should be copied to the documentation.

**Comment by saltcod** [comment]
Hey @fergusmeiklejohn!   Thanks for the report. We agree — the search could be much better. We're currently searching on article title and description fields. We're looking to add a much more robust set of results, hopefully soon.
