### ISSUE TITLE
Order foreign key has the wrong syntax

### ISSUE THREAD

**Issue by volkandkaya** [supabase/supabase#1103]
# Bug report

## Describe the bug

Ordering by foreign key has the wrong syntax in docs.

## To Reproduce

const { data, error } = await supabase
  .from('countries')
  .select('name, cities(name)')
  .eq('name', 'United States')
  .order('cities.name')

## Expected behavior

const { data, error } = await supabase
  .from('countries')
  .select('name, cities(name)')
  .eq('name', 'United States')
  .order('name', {foreignTable: 'cities'})

**Comment by kiwicopple** [comment]
Thanks @volkandkaya - you're absolutely right. Looks like we need to updates:

https://github.com/supabase/supabase/blob/c8892d83bb3f2eea88886c9237f2116aadaa1050/web/spec/supabase.yml#L1062

**Comment by iamayushdas** [comment]
Going to fix this, assign me

**Comment by inian** [comment]
Go ahead @iamayushdas!
