### ISSUE TITLE
Monitoring & Alert/Notifications of errors/downtime

### ISSUE THREAD

**Issue by atnegrete** [supabase/supabase#1105]
# Feature request

## Is your feature request related to a problem? Please describe.

I just ran into an issue yesterday where the Realtime aspect of supabase stopped working for my project. Even within the web's Table Editor, when I would edit a row, it was not reflecting on the table. And it was also not picking up any subscriptions at all on my application.

No idea if the issue can be found, as I ended up deleting the project and creating a new one and it's working 100% now.

## Describe the solution you'd like

Possibly add some basic monitoring for the services, and I'm guessing there's something in place already or some heartbeat checks, but it'd be great if the Web UI had a notification when it detected downtime or an error. 

Even if the error message can't be accurate, at least seeing that there is an error would be a huge help!

Thanks!

**Comment by kiwicopple** [comment]
> it'd be great if the Web UI had a notification when it detected downtime or an error.

We've started adding Logs into the Dashboard.

I'll close this, and if there are any specific logs you'd like to see just let us know
