### ISSUE TITLE
Unable to search docs with query: getUser()

### ISSUE THREAD

**Issue by icapochi** [supabase/supabase#11055]

**Comment by burmecia** [comment]
The doc is here: https://supabase.com/docs/reference/javascript/auth-getuser. I think the doc only indexed page title, so you might want to use `Retrieve a user` as the search keywords.

**Comment by saltcod** [comment]
Hey @icapochi, Bo is correct there. We're currently indexing titles and descriptions. Hoping to move to fill text search of this soon.

**Comment by gregnr** [comment]
For future people coming across this thread - we now do full text indexing via the new [embeddings-based search approach](https://github.com/supabase/supabase/issues/11208). In this case `getUser()` should pull up what you expect now.
