### ISSUE TITLE
Missing example for select() + "Query foreign tables"

### ISSUE THREAD

**Issue by fichince** [supabase/supabase#11051]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/select

## Describe the problem

In the examples panel, when I choose "Query foreign tables", it shows "undefined".

## Describe the improvement

Please add an example for how to use foreign tables.

## Additional context

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/4640794/208142493-67feffcb-f63e-461d-8cf8-fa54b1022bad.png">

**Comment by fichince** [comment]
Thank you @Hallidayo @dannykng

**Comment by dannykng** [comment]
@Hallidayo did all the work! 😄 

Thanks for flagging the issue @fichince!

**Comment by Hallidayo** [comment]
@dannykng @fichince - It was a team effort 😂
