### ISSUE TITLE
jsonb does not render properly when viewed as a relation in the sidebar

### ISSUE THREAD

**Issue by churichard** [supabase/supabase#1108]
# Bug report

## Describe the bug

I have a table with a column that stores `jsonb`. It renders properly in the table view:

<img width="413" alt="Screen Shot 2021-04-08 at 7 49 43 PM" src="https://user-images.githubusercontent.com/4218237/114109598-6d348780-988a-11eb-8ead-2ee5d8c54444.png">

But not in the sidebar view that pops up when viewing it as a relation from another table:

<img width="556" alt="Screen Shot 2021-04-08 at 7 50 21 PM" src="https://user-images.githubusercontent.com/4218237/114109636-82a9b180-988a-11eb-9ad5-70b9fbb67ce7.png"> 

## To Reproduce

1. Create a table `A` that has a column `C1` that stores `jsonb`.
2. Create another table `B` that has a column `C2` that references table `A`.
3. Add some data
4. View the data in table `A` from table `B` through the link that pops up the sidebar

## Expected behavior

I would expect the proper json values to show, not `[object Object]`.

## Additional context
Probably it's being stringified incorrectly (e.g. using `toString` instead of `JSON.stringify`).

**Comment by phamhieu** [comment]
Hi @churichard, we updated the dashboard app recently. Let me know if you are still facing the issue.
