### ISSUE TITLE
supabase-js auth interface

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#111]
issue to discuss the specification of methods in supabase-js to invoke auth endpoints on `auth/v1`

the endpoints that will be targeted are:
- `auth/v1/signup`
- `auth/v1/login` (actually makes a claim on `auth/v1/token` endpoint)
- `auth/v1/logout`
- `auth/v1/token`? (used to fetch refresh tokens)
- `auth/v1/recover`? (sends recovery email)
- `auth/v1/user`? (returns current user details)
- `auth/v1/verify`? (verifies a token sent over email to activate an account)
- `auth/v1/invite`? (sends invite email)

more details regarding the function of the endpoints found [here](https://github.com/netlify/gotrue) (you'll have to scroll past the env vars to the relevant section)

initial idea discussed with @kiwicopple was to allow the user to create a single client and call methods on an auth namespace like:

```javascript
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(URL, KEY)

await supabase.auth.signup(new_email, new_password)
await supabase.auth.login(email, password) // might also return jwt so it can be managed manually 
await supabase.auth.logout()
```

`signup` (if not requiring email confirmation) and `login` will set a cookie containing the auth-token, which will then be sent in a header for any call to `logout`, or calls to `rest` or `realtime` methods (`subscribe()`, `select()` etc.)

**Comment by kiwicopple** [comment]
Nice one @awalias - I'll start on this piece tomorrow. 

@dragarcia is working on the Postgres [JWT extension](https://github.com/supabase/postgres/issues/27), so once we have that I believe we have all the moving pieces, apart from [email](https://github.com/netlify/gotrue#e-mail), which we can set up with SES

**Comment by awalias** [comment]
there's also an option to disable email and auto-confirm signups - but I think it's a fairly easy to connect up so will keep aiming for email for now

**Comment by awalias** [comment]
just linking this here https://github.com/netlify/gotrue/issues/255 as the gotrue `/token` interface may change

**Comment by awalias** [comment]
closing for https://github.com/supabase/supabase-js/issues/3
