### ISSUE TITLE
Update link for disabling email confirmations in auth-signup docs

### ISSUE THREAD

**Issue by hoqqanen** [supabase/supabase#11141]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)
https://supabase.com/docs/reference/javascript/auth-signup

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?
"By default, the user needs to verify their email address before logging in. To turn this off, disable Confirm email in [your project](https://app.supabase.com/project/_/auth/settings)." is out of date, confirm email is now under the "email" under provider settings, i.e. https://app.supabase.com/project/_/auth/providers 

## Describe the improvement

A clear and concise description of the improvement.
Change the link to https://app.supabase.com/project/_/auth/providers  and mention that the toggle is under "email"

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by fzybb** [comment]
Anyone knows how to disable the email confirmation in local supabase?
