### ISSUE TITLE
Storage UI in Studio fails to fetch/load buckets (Self-Hosted)

### ISSUE THREAD

**Issue by globemediaofficial** [supabase/supabase#11153]
# Bug report

## Describe the bug

Opening the `storage` tab in the studio gives an error notification `Failed to fetch`. No buckets are shown.

In the network console, I can see that the request is made to `http://api.example.com/storage/v1/bucket` instead of `https://api.example.com/storage/v1/bucket`. Everything in `.env` is `https` so I don't know why that is happening. Other than that, there are no errors that I can see. The storage still works behind the scenes (in code), it just doesn't show the buckets or objects in the studio. I can upload a file, get the public URL, and open that URL to get the uploaded file.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow guide to start self-hosting
2. Replace all `URLs` with `HTTPS` subdomains that point to the corresponding ports
3. Go to storage in the dashboard

## Expected behavior

Buckets should be fetched and the UI should show them.

## System information

- OS: Windows (WSL 2.0 for docker)
- Browser chrome

**Comment by quangtd95** [comment]
same issue!

**Comment by itisnajim** [comment]
already reported 
https://github.com/supabase/supabase/issues/11136

you can solve using nginx for now.

**Comment by kiwicopple** [comment]
I'll close this as a duplicate for now - thanks @itisnajim
