### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by 0xPratik** [supabase/supabase#11171]
# Bug report
I have used twitter auth with nextjs and supabase and i didnt get any error using it on localhost but when i deployed it using vercel then it throws this error.

## Screenshots

These are the screenshot of logs that i get from vercel
<img width="762" alt="Screenshot 2022-12-21 at 8 42 36 PM" src="https://user-images.githubusercontent.com/62953475/208938222-124f6059-4932-45b2-a76b-20ff736ee8dc.png">

## System information

- OS: Mac
- Version of Node.js: 18

**Comment by kiwicopple** [comment]
hey @0xPratik - is this using the CLI? 

can you please provide some steps to replicate the issue?
