### ISSUE TITLE
Realtime channel subscription with more than one filter

### ISSUE THREAD

**Issue by onurbamaro** [supabase/supabase#11190]
# Bug report

## Describe the bug

Hello! 

I am able to subscribe to a channel with one filter like isOpen=eq.true, but can't with more than one filter like isOpen=eq.true&status=eq.preparing

I would like to know if it's possible to achieve that. 

PS: I am using the template schema:table:filter for the channel name. 

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 2.2.1
- Version of Node.js: 16.17.0

**Comment by GaryAustin1** [comment]
That is not supported currently.  Only a single eq,gt,lt,gte,lte,neq filter can be done.

**Comment by onurbamaro** [comment]
Thank you for replying so fast! 

I am looking forward for this update.

In the meantime would be nice a heads-up in the docs about this restriction

**Comment by sunilguptasg** [comment]
I believe the documentation is clear on that.
