### ISSUE TITLE
pgsodium's decrypted view are not being dynamically created

### ISSUE THREAD

**Issue by scalemaildev** [supabase/supabase#11209]
# Bug report

## Describe the bug

TCE for Supabase is supposedly to create a decrypted_<table_name> view for each table that utilizes pgsodium's encryption. This is documented here (https://supabase.com/blog/transparent-column-encryption-with-postgres#using-an-encrypted-table). However, this decrypted view is not being created for me and there is an issue on pgsodium's repo (https://github.com/michelp/pgsodium/issues/31) with several users complaining specifically about Supabase.

## To Reproduce

Use pgsodium's security label to create a pg table with an encrypted column.
Try to run a query against the decrypted_<table_name> view that's meant to be dynamically created (there is no such table).

## Expected behavior

When using a security label with pgsodium to encrypt a table's column, it should generate a decrypted view for that table.

**Comment by scalemaildev** [comment]
I deleted my project and rebuilt it from scratch and now the views are available.

**Comment by fabricior** [comment]
> I deleted my project and rebuilt it from scratch and now the views are available.

Thanks @scalemaildev 
Your comment gave me the hint that the issue could be related to `major_version`  I was using. In my case, I had created the project time ago so it was using `major_version = 14` in my config.toml.
However, I had noticed that new projects ship with `major_version = 15`.
So in my case, I did:
- supabase stop
- updated config.toml to use `major_version = 15`
- supabase start

The new images do generate the views dynamically as expected.

**Comment by nfcampos** [comment]
I'm suffering the same issue after updating from 14 to 15 in config

**Comment by timreibe** [comment]
I'm using the Supabase Cloud and face the same issue, any solution for this? Maybe you can reopen the issue @scalemaildev

**Comment by iwasrobbed** [comment]
One thing I've noticed is the `decrypted_` virtual table / view takes some time to be created during the initial creation of the encrypted column

If you try to revoke access to the table too soon after creating the security label then it will fail with `decrypted_blah not exist`

I ended up having to run my migrations one at a time rather than via CI/CD which wasn't ideal. Even a `pg_sleep(10)` didn't work
