### ISSUE TITLE
Unable to search docs with query: onauthstatechange

### ISSUE THREAD

**Issue by jfeaver** [supabase/supabase#11208]
I expect the query to yield this result: https://supabase.com/docs/reference/javascript/auth-onauthstatechange

**Comment by Hallidayo** [comment]
Hi @jfeaver - The docs are currently searching on the page title and description (see issue #11055).

Searching for `auth events` brings up the following:

<img width="771" alt="Screenshot 2022-12-22 at 23 12 27" src="https://user-images.githubusercontent.com/22655069/209240620-da7a2f39-6e63-461e-b822-92c75928f136.png">

**Comment by jfeaver** [comment]
I see the referenced issue is closed. Does that mean that there aren't plans to index search by method names or URLs? I, personally, don't think of "Auth Events" when I want to remember details about onauthstatechange even though I understand that's where the documentation lives. The current search seems broken (for more searches than the one mentioned here). I have often left Supabase docs to search Google to find the Supabase docs page that I'm looking for.
