### ISSUE TITLE
docs: critical typo in auth docs

### ISSUE THREAD

**Issue by radihuq** [supabase/supabase#11238]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/phone-login/twilio#using-otp-as-a-passwordless-sign-in-mechanism

## Describe the problem

The example code is incorrect: 
```
let { session, error } = await supabase.auth.verifyOTP({
  phone: '+13334445555',
  token: '123456',
  type: 'sms',
})
```

## Describe the improvement

The function should actually be `supabase.auth.verifyOtp({...})`. (Note: camelCase, not all caps)

**Comment by alaister** [comment]
Fixed via #11244. Thank you @radihuq for reporting and @pratik-codes for the fix!
