### ISSUE TITLE
Created custom role and i try to Create user and login failed 

### ISSUE THREAD

**Issue by RamPolineni2021** [supabase/supabase#11279]
# invalid user name password
## i created own Roles for my application client Admin, Client normal, Admin_Admin , Admin_normal, entire admin, i used 
this code let { data, error } = await supabase.auth.admin.createUser({
        email: useremail.current?.value,
        password: password.current?.value,
        role: 'entire_admin',
        aud:'entire_admin',
        email_confirm: true,
        phone_confirm: true,
        email_confirmed_at: new Date(),
        confirmed_at: new Date()
      })

## success full 200 responce get the data after i try to login the page Invalid login credentials it showing 

  const { data:{user}, error } = await supabase.auth.signInWithPassword({
        email: useremail.current?.value,
        password: password.current?.value
      })
   
## based on rloes creating profile table i created 2 polices 
1. every one read the data 
2. onely admin can add, update, delete the data

### Roles based creating users and login....?

**Comment by GaryAustin1** [comment]
I'm going to go ahead and close this in favor of this discussion https://github.com/supabase/supabase/discussions/11948.
It appears you are trying to do what is covered in that.
