### ISSUE TITLE
Table editor and custom schama (non public)

### ISSUE THREAD

**Issue by ISIGest** [supabase/supabase#1129]
# Bug report

## Describe the bug

Table with non public schema does not work in Table Editor

## To Reproduce

Create a simple table with SQL Script adding a custom schema to PG:

`CREATE SCHEMA simple_schema;`

Now creating a simple table:

```
CREATE TABLE simple_schema.my_table (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  my_col int4
);
```

Now if we go to "Table editor" we got this error:

![image](https://user-images.githubusercontent.com/82315177/114417980-5f487480-9bb2-11eb-9bb7-57e177a2d5e5.png)

## Additional context

Before edit a table we need to know what is the table schema and after that open it with full table schema name.

**Comment by kiwicopple** [comment]
Thanks for opening @ISIGest . We currently leverage your database's API for the table view (which is only scoped to the `public` schema). We are working on some ideas to improve this (either you can expose more schemas via PostgREST config, or some sort of super-admin interface).

I'll drop more details when we have figured out the best approach

**Comment by oliver3** [comment]
My use case would be to have a "private" schema that is visible in the table editor, but is not visible for the rest of the world, i.e. it should also not show up in the OpenAPI output, so if I understand correctly, exposing more schemas via PostgREST would not work?
