### ISSUE TITLE
Storage Container not starting (macos)

### ISSUE THREAD

**Issue by lukkaempf** [supabase/supabase#11305]
# Bug report

## Describe the bug
When I start the docker-compose file, the storage container gave an error.
Problem only in Docker container, if I run storage API manually it works.
see the screenshot below.

## To Reproduce

git clone --depth 1 https://github.com/supabase/supabase

cd supabase/docker

cp .env.example .env

docker compose up

## Expected behavior

The storage api should start without a error.

## Screenshots
![image](https://user-images.githubusercontent.com/64331815/209707488-61fbae6a-60cc-4692-8b76-3ac5effa1d20.png)

## System information

- OS: macOS Ventura 13.0
- Version of supabase-js: every version
- Version of Node.js: v18.12.1

**Comment by sweatybridge** [comment]
Hey, I couldn't reproduce this but it prompted me to make the storage `depends_on` more robust. Could you `rm -rf docker/volumes/db/data` and try again?
