### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by carmas123** [supabase/supabase#1130]
# Feature request

Please add the ability to export table row to JSON.
For now is only to CSV.

**Comment by marcelobarreto** [comment]
There is anyone working on this one? I'd like to work at this, is it possible @kiwicopple ?

**Comment by joshenlim** [comment]
hey there @carmas123! you should be able to export rows to JSON from the table editor as such after selecting the rows which you want
![image](https://user-images.githubusercontent.com/19742402/135043595-6fa4cef7-7dcb-4638-9709-f58830dd5af7.png)

i'm going to close the ticket for now but feel free to reopen if you do run into any other issues!

**Comment by carmas123** [comment]
Thank you so much
