### ISSUE TITLE
Wrong code in Storage docs

### ISSUE THREAD

**Issue by TruePadawan** [supabase/supabase#11300]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/storage-from-update

## Describe the problem
The code that is associated with the **replace an existing file** section of the storage docs is a bit wrong.

## Describe the improvement
```upsert``` should be set to true not false

## Additional context
![image](https://user-images.githubusercontent.com/71678062/209676685-3a615857-209e-4f2d-81c6-cd59442cfd15.png)

Add any other context or screenshots that help clarify your question.

**Comment by Devkant21** [comment]
@TruePadawan Can I take up the issue?

**Comment by TruePadawan** [comment]
@Devkant21 what do you mean by take up? I don't really know how stuff works here. If taking it up corrects that error then sure

**Comment by J0** [comment]
@Devkant21  - if you're still keen feel free to go for it - the relevant section file to edit [is here](https://github.com/supabase/supabase/blob/master/spec/supabase_js_v2.yml#LL4397C3-L4397C3)

**Comment by J0** [comment]
Closing as it’s resolved by #12186
