### ISSUE TITLE
`undefined` suggested when you search docs with query: <anything that doesn't return a result>

### ISSUE THREAD

**Issue by MaxLeiter** [supabase/supabase#11307]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/8675906/209722244-71522aa0-baa6-425c-b54e-eeb3dbc43350.png">

It suggests I "try searching for `undefined`" if I search anything with no results

**Comment by aaadryyy** [comment]
Looks like this issue is not relevant anymore.

<img width="813" alt="Screenshot 2023-03-09 at 00 20 17" src="https://user-images.githubusercontent.com/20040637/223874803-94440684-919d-4724-90b3-0bb2d2be9f3c.png">

**Comment by gregnr** [comment]
Thanks @MaxLeiter and @aaadryyy! Yes the new [embeddings-based search](https://github.com/supabase/supabase/pull/12506) has updated this interface.
