### ISSUE TITLE
Auth.Signup Not checking for duplicate email addresses.

### ISSUE THREAD

**Issue by j-Kode** [supabase/supabase#11311]
# Bug report

## Describe the bug

When I am using the `Auth.signUp` function with an email address that already exists and has been verified in my users table, it returns a response indicating a new user has been created. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. call supabase.auth.signup with the same email address that has already signed up and verified then console.log(data)

## Expected behavior

Should probably return an error indicating this user already exists, try logging or click forgot password

## Screenshots

existing email address
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/21285530/209754687-91af77cb-64cf-4acb-9b81-9a47f0284b5f.png">

calling signup with the same email address
<img width="850" alt="image" src="https://user-images.githubusercontent.com/21285530/209754657-c0539a79-7d4b-490f-8dc0-ffc5b4edef80.png">

## Additional context

This only seems to happen when a user has been verified and you try and sign up with the same email address, if I try and sign up with the same email address for a user that has not been verified the same user data is return in the console. 

The createdAt Timestamp can be used to check if the user was just created. But Ideally I think there should be some parameter you can pass into the function to return a error message if the email already exists.

**Comment by alaister** [comment]
Hi @j-Kode,

Thanks for the detailed report!

This isn't actually a bug and is part of the way Gotrue sign-up works. From the [`signUp` method docs](https://supabase.com/docs/reference/javascript/auth-signup):
> If Confirm email is enabled in your project, an obfuscated/fake user object is returned

If you need to detect if an email address is already in use, you can create an RPC function that searches `auth.users` by a given email address. However, I would advise against doing this for the same reason Gotrue doesn't return if a user is registered: it exposes information about your users to everyone.

I'll pass your feedback to the auth team about adding a parameter not to return an error message if the user already exists.

**Comment by j-Kode** [comment]
Thanks for the info @alaister
