### ISSUE TITLE
GraphQL API responds with PGRST202 error

### ISSUE THREAD

**Issue by davidaventimiglia** [supabase/supabase#11310]
# Bug report

## Describe the bug

The supabase GraphQL API responds with this error:

```shell
{"code":"PGRST202","details":null,"hint":"If a new function was created in the database with this name and parameters, try reloading the schema cache.","message":"Could not find the graphql_public.graphql({ \"query\":\"{ accountCollection(first: 3) { edges { node { id } } } }\" }) function in the schema cache"}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new project in supabase.
2. Create a data model with tables.
3. Follow [the instructions](https://supabase.com/docs/guides/api#graphql-api) for accessing the GraphQL API with `curl`.
4. See error.

## Expected behavior

Expected it not to respond with a cryptic error.

## System information

- OS: Ubuntu 22.04
- Browser (if applies): NA (`curl`)
- Version of supabase-js: NA (`curl`)
- Version of Node.js: NA (`curl`)

## Additional context

This is the curl command I used (with keys redacted):

```shell
# Append /graphql/v1/ to your URL, and then use the table name as the route
curl --request POST 'https://ditmiatcthxyiassgamu.supabase.co/graphql/v1' \
-H 'apikey: <redacted>' \
-H 'Authorization: Bearer <redacted>' \
-d '{ "query":"{ account(first: 3) { edges { node { id } } } }" }'
```

**Comment by alaister** [comment]
Hi @davidaventimiglia,

I'm sorry you ran into this. I was able to reproduce the issue.

The docs seem to be missing a `Content-Type: application/json` header for the cURL command. I have created a PR: #11321, which updates the command in the docs.

I have also sent this through to the PostgREST team so they can add a better error message for this case.

Feel free to reopen this if adding the header to your cURL command didn't fix it for you. Thanks!

**Comment by davidaventimiglia** [comment]
Thanks!
