### ISSUE TITLE
Invalid parameter in MFA docs

### ISSUE THREAD

**Issue by hkamran80** [supabase/supabase#11315]
# Improve documentation

## Link 

[https://supabase.com/docs/reference/javascript/auth-mfa-challengeandverify](https://supabase.com/docs/reference/javascript/auth-mfa-challengeandverify)

## Describe the problem

The current code example includes the `challengeId` parameter, which doesn't exist in the `challengeAndVerify` function.

```js
const { data, error } = await supabase.auth.mfa.challengeAndVerify({
  factorId: '34e770dd-9ff9-416c-87fa-43b31d7ef225',
  challengeId: '4034ae6f-a8ce-4fb5-8ee5-69a5863a7c15',
  code: '123456'
})
```

## Describe the improvement

Remove the `challengeId` parameter

**Comment by alaister** [comment]
Thanks again for the fix – your changes are now live!

**Comment by hkamran80** [comment]
No problem, glad to help!
