### ISSUE TITLE
Query is not being called if response is not awaited.

### ISSUE THREAD

**Issue by rromikas** [supabase/supabase#11322]
The query bellow is not being called, request is not being sent to the server.
supabase.from("collection_name").delete().eq("id", "1")

The queries bellow work perfectly.
await supabase.from("collection_name").delete().eq("id", "1")
supabase.from("collection_name").delete().eq("id", "1").then(({data}) => {})

Expected
Queries should be executed even when response is not awaited. 

Library
"@supabase/supabase-js": "^2.2.0",

**Comment by alaister** [comment]
Hi @rromikas,

This is expected behaviour. It allows us to have a fluid API where you can chain as many operators (`eq`, `gte`, etc) as you like before sending a query.

If you want the query to be sent without awaiting the response, I'd suggest using an empty `.then(() => {})` or `Promise.all()`.

**Comment by rromikas** [comment]
Okay, Thanks
