### ISSUE TITLE
Project/Api Docs - Views show "Subscribe to changes" which is not possible. 

### ISSUE THREAD

**Issue by planetmall** [supabase/supabase#11320]
# Improve documentation

## Link 

https://app.supabase.com/project/**project**/api?resource=**view**

## Describe the problem

You are unable to subscribe to changes with views. 

## Describe the improvement

Remove this section or update to "Not available with Views" on any view that was created in the DB. 

Examples from others on how to overcome: 
https://github.com/supabase/supabase/discussions/5152

## Additional context

![Screenshot 2022-12-28 at 9 49 36 AM](https://user-images.githubusercontent.com/33105141/209837806-049e3579-5dce-41d9-bec7-fe1620dea952.png)

**Comment by kiwicopple** [comment]
thanks @planetmall - I've tagged this one for contributors first. We'll need to update this file to detect whether the endpoint is a View:
https://github.com/supabase/supabase/blob/master/studio/pages/project/%5Bref%5D/api/index.tsx

I'm not sure how we'd do that yet, hopefully there is something in the OpenAPI spec which can indicate this
