### ISSUE TITLE
INSERT INTO Returning in http

### ISSUE THREAD

**Issue by Samsonov0** [supabase/supabase#11337]
# Feature request

## Is your feature request related to a problem? Please describe.

when writing INSERT requests via http, I want to be able to get the record created in the table. Now this logic is implemented in JS and Dart, but I would like to have it when working with the http protocol

## Describe the solution you'd like

receiving the created record in response to a POST request with JSON transmission in the body via the url https://<project_ref>.supabase.co/rest/v1/MyTable

## Describe alternatives you've considered

one of the alternatives is the use of edge functions, but we refused this, due to the need to use http communication.

**Comment by alaister** [comment]
Hi @Samsonov0,

This is possible right now! See the [PostgREST docs for inserts](https://postgrest.org/en/stable/api.html#insertions).

In short, you'll need to add the header: `Prefer: return=representation` to your request.

**Comment by Samsonov0** [comment]
sorting by multiple fields also works as stated in the documentation? this function does not work on my project

**Comment by Samsonov0** [comment]
sorting by multiple fields also works as stated in the documentation? this function does not work on my project

**Comment by alaister** [comment]
Can you post some code snippets so we can work out what may not be working for you?

If it's working for you with the Supabase client, you can run the query in your browser and inspect the query params and headers that are sent so you can reuse them in your HTTP call.

**Comment by Samsonov0** [comment]
https://<project_ref>.supabase.co/rest/v1/MainTable?select=*,FirstTable(*,SecondTable(*))&order=FirstTable(Date).asc,SecondTable(time_start).asc
headers : {apikey: anon_key}.

I dont know what also meta i can give. sorter works only on first field.
P.s i know what ordering on relations work only in local projects but this problem not about it
