### ISSUE TITLE
Filter issue with column named "version

### ISSUE THREAD

**Issue by SharifElfouly** [supabase/supabase#11339]
# Bug report

## Describe the bug

Filtering does not work on the frontend with a column named version. I know version is a reserved keyword but there is no hint of that while creating a column named version.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create version column
2. filter by version column

**Comment by raph941** [comment]
@SharifElfouly, I had previously encountered this issue, but it appears to have been resolved. Please take a look at the demonstration I've included below. Can you confirm if the issue has been resolved on your end as well?

https://user-images.githubusercontent.com/45232708/211489515-80520fea-499b-42a3-b539-577c36b9d319.mov

**Comment by GaryAustin1** [comment]
I'm going to close the issue for lack of response to a suggestion it has been fixed.
Please feel free to comment if it is still an issue.
