### ISSUE TITLE
Foreign Table working not properly

### ISSUE THREAD

**Issue by putheng** [supabase/supabase#1134]
# Bug report
Foreign Table not working

## Describe the bug
I have table 
- `products(id, name, price)`
- `product_variations`(id, `product_id` (foreign id of `products` table), name, price)

My code
```js
const { data, error } = await database.from('products').select('*, product_variations:id(id,name,price)')
```
I try it working fine but after a few hours, it shows a null result.
I didn't change any value in the database.
I don't know Supabase update or what.

**Comment by kiwicopple** [comment]
Hi @putheng - i'm sorry this isn't working for you. Can you please share some steps to replicate this?

**Comment by kiwicopple** [comment]
I'll close this for now because we're doing a bit of an issue cleanup. If you're still facing this issue and you can provide some steps for use to replicate the issue, feel free to reopen :)
