### ISSUE TITLE
404's in /docs

### ISSUE THREAD

**Issue by stavares843** [supabase/supabase#11375]
# Improve documentation

## Link 

Links below

## Describe the problem

| Status  | URL | Source link |
| ------------- | -------------     | ------------- |
| 404 Not Found  | https://github.com/supabase/supabase-admin-api/blob/master/optimizations/postgres.go  | https://supabase.com/docs/guides/platform/performance (clickable text: the default configuration used by the Supabase platform)  |
| 404 Not Found  | https://github.com/stytchauth/stytch-react | https://supabase.com/docs/guides/integrations/stytch (clickable text: React library)  |
| 404 Not Found  | https://supabase.com/docs/getting-started/quickstarts/reactjs | https://github.com/supabase/supabase/blob/master/apps/docs/pages/index.mdx?plain=1#L66  |
| 404 Not Found  | https://supabase.com/docs/getting-started/quickstarts/nextjs | https://github.com/supabase/supabase/blob/master/apps/docs/pages/index.mdx?plain=1#L71 |

## Describe the improvement

Fixing the 404's

## Additional context

Added above

**Comment by stavares843** [comment]
note - there are still some 404's considering one of the PR's was closed and wasn't merged

**Comment by dannykng** [comment]
Hi @stavares843,

- The first one seems to be a false positive—[the link](https://supabase.com/docs/guides/platform/performance#allowing-higher-number-of-connections) is working for me.
- Second 404 addressed in https://github.com/supabase/supabase/pull/11426.
- The last two links were technically never live (hidden div) but updated in https://github.com/supabase/supabase/pull/11455.

Thanks for flagging!

**Comment by stavares843** [comment]
🎉
