### ISSUE TITLE
auth.setSession fails in React Native with a ReferenceError

### ISSUE THREAD

**Issue by everylittlefox** [supabase/supabase#11382]
# Bug report

## Describe the bug

I'm trying to setup Github OAuth with Supabase in my React Native app. First, the code example from the docs, `supabase.auth.signInWithOAuth({ provider: 'github' })`, didn't work, so I had to use a workaround. It required that I get the access and refresh tokens manually and set them with `setSession({ access_token, refresh_token })`. Doing this, however, throws a `ReferenceError: Can't find variable: Buffer`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create Github OAuth app
2. enable Github OAuth in Supabase with client id and secret from Github
3. create Supabase JS client
4. call `[client].auth.setSession()`

## Expected behavior

`setSession()` should run with `Buffer` defined in React Native.

## Additional Context
I traced the specific file (and function) that throws the error to gotrue-js: in lib/helpers.ts. I imported Buffer at the top of the file, but even this didn't solve it.

**Comment by j4w8n** [comment]
I believe others are using rn-notify to fix this.

https://www.npmjs.com/package/rn-nodeify

**Comment by mchennupati** [comment]
I have the same issue when try to set session in expo as in the issue thread [here](https://github.com/supabase/gotrue-js/issues/406#issuecomment-1279697950), as supabase.auth.signInWithOAuth('provider' : 'github') etc  doesn't work out of the box in expo. 
Unfortunately, nodeify suggested by @j4w8n  doesn't work for me.
