### ISSUE TITLE
Unable to search docs with query: api response codes

### ISSUE THREAD

**Issue by dhurbhat** [supabase/supabase#11394]
Where can I find specs on API response codes?

**Comment by saltcod** [comment]
Hey @dhurbhat — do you mean responses like these? 
https://supabase.com/docs/reference/api/list-all-organizations

**Comment by dhurbhat** [comment]
Yes like that but on crud operations on project tables. I wanted to know
why I was getting some error code when doing a get (select) or patch
(update).

**Comment by GaryAustin1** [comment]
There is quite a bit of documentation on the database REST API (not auth or storage) here:  https://postgrest.org/en/stable/errors.html#http-status-codes

**Comment by aaadryyy** [comment]
Looks like this issue is not relevant anymore!
<img width="791" alt="Screenshot 2023-03-09 at 00 22 22" src="https://user-images.githubusercontent.com/20040637/223875232-2341e61c-3773-4cf5-8730-ec3c3bd9ef64.png">

**Comment by gregnr** [comment]
Yep - looks like the new [embeddings based search](https://github.com/supabase/supabase/pull/12506) has solved this. Closing this - @dhurbhat let me know if this wasn't what you were looking for.
