### ISSUE TITLE
Secret 'SUPABASE_URL' and 'SUPABASE_DB_URL' missing in  edge function secrets

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#11396]
# Bug report
Secret 'SUPABASE_URL' and 'SUPABASE_DB_URL' missing in  edge function secrets. Image attached.
<img width="678" alt="Screenshot 2023-01-01 at 11 54 17 PM" src="https://user-images.githubusercontent.com/21134455/210181556-80c78987-f630-4f44-a5ed-d9bcc7eaffe4.png">

## To Reproduce
Add the below code to any edge function and run.
```
console.log('SUPABASE_URL : ', Deno.env.get('SUPABASE_URL'))
console.log('SUPABASE_ANON_KEY : ', Deno.env.get('SUPABASE_ANON_KEY'))
console.log('SUPABASE_SERVICE_ROLE_KEY : ',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'))
console.log('SUPABASE_DB_URL : ', Deno.env.get('SUPABASE_DB_URL'))
```

## Expected behavior
Should print all the default secrets mentioned in the docs https://supabase.com/docs/guides/functions/quickstart#default-secrets.

## Screenshots
<img width="593" alt="Screenshot 2023-01-02 at 12 10 47 AM" src="https://user-images.githubusercontent.com/21134455/210181611-e7ac53fb-819f-4528-a214-43e67a337ed5.png">

**Comment by laktek** [comment]
@Akash187 Can you try redeploying your function via the CLI? If the issue persists can you try upgrading to the latest version of the CLI?

**Comment by Akash187** [comment]
@laktek thanks for the suggestion sadly updating cli did not work.
Any update @alaister?
<img width="597" alt="Screenshot 2023-01-03 at 4 42 17 PM" src="https://user-images.githubusercontent.com/21134455/210346619-04a3a67f-f555-4932-ac28-755af0367239.png">

**Comment by Akash187** [comment]
Day 3:- Any update @alaister?

**Comment by laktek** [comment]
@Akash187 It looks like an issue specific to your project. Can you open a support ticket from the Supabase dashboard with your project details so we can have a look?

**Comment by Akash187** [comment]
Ok, @laktek will open a ticket. Yes, it seems to be a problem only with my project. I want to update you that I recently upgraded my project from postgres14 to postgres15 using the guide mentioned in the documentation.

I tested a new project on postgresql15 seems to work fine with all the environment variables
<img width="803" alt="Screenshot 2023-01-04 at 8 05 45 PM" src="https://user-images.githubusercontent.com/21134455/210578456-c4324fca-85c4-4e6a-b850-beac0d87f71f.png">
.

**Comment by laktek** [comment]
@Akash187 Interesting, so after you upgraded to postgres 15 do you get all your edge function secrets?

**Comment by Akash187** [comment]
@laktek I have 2 projects. One I upgraded from v14 to v15 other I created a fresh v15 project. I am facing this issue with 1st project. 2nd is working fine. Also, I didn't build functions on v14 so  I have no idea if it was working on v14 or not.

**Comment by laktek** [comment]
Closing this, since it was handled via a support ticket.

**Comment by dhurbhat** [comment]
oh - what was the resolution?

#newbie 
I've just created a new Edge Function and am trying to execute a simple select from a table.  I'm running the function in VSCode which appears to have `--allow-env` in the `launch.json` file.
'SUPABASE_URL' is not being initialized.

**Comment by adriengibrat** [comment]
Same issue here after project pause & restoration.

Is there any workaround ? or opening a support ticket is the only solution?

**Comment by adriengibrat** [comment]
deleting the function & re-deploy, has fixed my issue (SUPABASE_URL env var is defined again).

**Comment by Nashtronaut** [comment]
Is this still a known issue? 

function log.
```
ReferenceError: EP_API_BASE_URL is not defined
```

function
```ts
...
const url = Deno.env.get(EP_API_BASE_URL);
...
```

Deleting and redeploying secrets/function didn't seem to work! 😢
