### ISSUE TITLE
Error creating table: Failed to fetch

### ISSUE THREAD

**Issue by CodeATneeraj** [supabase/supabase#11416]
# Bug report
## Describe the bug
![Screenshot from 2023-01-03 12-15-15](https://user-images.githubusercontent.com/114344464/210310888-69e46cf0-7925-47e9-ad2b-4f885961c6ec.png)

I am trying to create a table with enabled RLS but it throws an error 
(An error has occurred: Failed to fetch) and tried to add new RLS policy but it is not applies on table

**Comment by CodeATneeraj** [comment]
Hello Supabase/Supabase Team,
I tried to add new policies also but the same error is happening for all
the tables.

Regards,

*Neeraj Bhaskar*
*Junior Software **Engineer*


Unit no. 126, 1st Floor, Shivkrupa Industrial Estate, Opp. Raj Legacy,
Vikhroli (W), Mumbai 400 083
M: +917715068549 ***@***.***>
E: ***@***.*** | W:www.cateina.com
<https://www.facebook.com/cateinatech/> <https://twitter.com/cateinatech>
<https://www.linkedin.com/company/cateina/>
<https://plus.google.com/107906527056100097303?hl=en-GB>
The company accepts no liability for the content of this email, or for the
consequences of any actions taken on the basis of the information provided,
unless that information is subsequently confirmed in writing. If you are
not the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.

**Comment by GaryAustin1** [comment]
@CodeATneeraj 
Did you resolve this?  Occasionally have seen similar errors if there is a connection issue or the dashboard loses its signin.  It usually goes away with a refresh or re signin.

**Comment by GaryAustin1** [comment]
Going to close this as likely was an intermittent issue and no response to follow up.

**Comment by GaryAustin1** [comment]
Another user just encountered this issue.  Turns out this part of the dashboard code does a Patch request.
There is an browser extension that disables Patch.  

![image](https://github.com/supabase/supabase/assets/54564956/424e82f5-b70f-454d-88f2-828386983b79)


This is a related topic where it was discovered: https://github.com/supabase/postgrest-js/issues/286#issuecomment-1165213335

**Comment by NahanaBanahnah** [comment]
> Another user just encountered this issue. Turns out this part of the dashboard code does a Patch request. There is an browser extension that disables Patch.
> 
> ![image](https://user-images.githubusercontent.com/54564956/264791806-424e82f5-b70f-454d-88f2-828386983b79.png)
> 
> This is a related topic where it was discovered: [supabase/postgrest-js#286 (comment)](https://github.com/supabase/postgrest-js/issues/286#issuecomment-1165213335)


Was having the same issue; turning off CORS extension fixed it.

**Comment by adityaslyf** [comment]
yes turning off Allow CORS extension works .

**Comment by Sachin7397** [comment]
Try to use https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en
 enable it and try

**Comment by Tanishq510** [comment]
> Another user just encountered this issue. Turns out this part of the dashboard code does a Patch request. There is an browser extension that disables Patch.
> 
> ![image](https://github.com/supabase/supabase/assets/54564956/424e82f5-b70f-454d-88f2-828386983b79)
> 
> This is a related topic where it was discovered: [supabase/postgrest-js#286 (comment)](https://github.com/supabase/postgrest-js/issues/286#issuecomment-1165213335)

this here was my culprit

**Comment by darshsingh116** [comment]
> Another user just encountered this issue. Turns out this part of the dashboard code does a Patch request. There is an browser extension that disables Patch.
> 
> ![image](https://github.com/supabase/supabase/assets/54564956/424e82f5-b70f-454d-88f2-828386983b79)
> 
> This is a related topic where it was discovered: [supabase/postgrest-js#286 (comment)](https://github.com/supabase/postgrest-js/issues/286#issuecomment-1165213335)

works
