### ISSUE TITLE
Long running RPC functions timeout instead of responding

### ISSUE THREAD

**Issue by KirioXX** [supabase/supabase#11420]
# Bug report

## Describe the bug

We have an RPC function that takes around 4s to finish on a Postgres client 
but when we try to run it via supabase it times out when it reaches the session timeout.
We already increased the timeout to 20s and the session timeout to 60s with the same result.

## To Reproduce

We have noticed this behaviour only on one function that needs quite a bit of time 
because it has to do a lot of comparisons to determine which records it needs to delete, add or remove.

The function itself has no response type and is only triggering other functions.

## Expected behaviour

The function response is successful or with an exception when it fails.

## Screenshots

~If applicable, add screenshots to help explain your problem.~

## System information

- OS: macOS
- Browser: chrome, firefox
- Flutter version: 3.3.10
- Version of supabase_flutter: 1.2.2

## Additional context

What I have not tried is executing the function via the rest endpoint I will do that too.

**Comment by KirioXX** [comment]
I tried to trigger the function via the rest API with the same result:
<img width="680" alt="Screenshot 2023-01-03 at 12 02 12" src="https://user-images.githubusercontent.com/11646702/210344924-a086534f-196e-422f-844c-2102af801ae7.png">

**Comment by GaryAustin1** [comment]
One difference is you will have to meet (and process) all RLS on any tables your function uses unless you are calling with service_role or it is "security definer".  Just a shot in the dark as you really don't say much about what you are doing.

**Comment by KirioXX** [comment]
Thank you for the quick response @GaryAustin1. 
Sorry, I meant with "run via supabase" that we have a flutter app that uses the flutter supabase package.

But you are completely right, I have not considered that the RLS checks could also slow down the execution. 
What also makes sense now is why it is so much quicker via the Postgres client, I use the postgres user that bypasses the RLS and the app user is an authenticated user with RLS. 
I will try to disable RLS table by table and see if I can find the bottleneck.

**Comment by KirioXX** [comment]
@GaryAustin1 you were spot on, the RLS policies slowed the execution so down so that it hit the session timeout.
I made the RLS policies a bit leaner and they are still a bit slow (without RLS 4s, with RLS 9s) but they succeed.
Thank you very much! 🙏

**Comment by GaryAustin1** [comment]
https://github.com/supabase/supabase/discussions/9311
Might be useful to you.  I was doing some research into RLS and there are some things to watch out for.  It is a paused effort at getting some better guidelines for RLS, but some of the gotchas found might help.

**Comment by KirioXX** [comment]
Hi @GaryAustin1,

I have a new problem that fits in the same frame.
I disabled the RLS for the function that is running to long but instead of getting a quicker response I get a new error.

This is the error:
```json
{
	"code":"XX000",
	"details":null,
	"hint":null,
	"message":"Signal caught"
}
```

What is curious is that the timeout occurs before the timeout that is set on the server.
Is there a way to check if this is an error in my code or with the API?

Thanks!

**Comment by GaryAustin1** [comment]
Did you resolve this?
Did you happen to look in the dashboard Postgres logs?
I don't find anything on that error.   Sorry just now getting back to look at this.

**Comment by KirioXX** [comment]
Thanks for the response @GaryAustin1.

It looks like we created a deadlock with our updates.
I use now an edge function to run the updates in batches. 
It is not perfect and still a bit slow but I'm investigating a better solution 
for our event triggers to do updates in the background.

Thanks again. 🙌
