### ISSUE TITLE
Self-hosting Supabase through docker compose not working

### ISSUE THREAD

**Issue by KevinHamonApp** [supabase/supabase#11444]
# Bug report
I'm encountering several problems when running the docker compose file from the repo, following the procedure with an external database. 

### 1 Database connection failed because of POSTGRES_USER 
You provide a POSTGRES_USER variable in .env which is not used in docker compose.yaml. There are two users written in the file. "Authenticator" for Posgrest service, and "supabase_admin" for realtime service.
This is very unclear in process. Either specify in documentation to create those two users with same password, either use the POSTGRES_USER  variable in docker compose file.

### 2 Realtime service keeps crashing, with the error : 
After resolving the first issue, I observe those logs in realtime service : 
```
The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "realtime" does not exist
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (realtime 0.0.0-automated) lib/realtime/release.ex:9: anonymous fn/2 in Realtime.Release.migrate/0
2023-01-04 13:34:35.174 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :realtime, Realtime.RLS.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Copy docker folder from supabase repository
2. Copy env file
3. Replace with your database credentials in .env
4. In docker-coompose comment the db service, and comment the depends_on statements for db
5. docker-compose up -d
6. => 1 : Check logs : db authentication problem
7. Replace in docker-compose in postgrest and realtime service the user with the PORSGRES_USER variable
8. docker compose up -d
9. => 2 : Check logs from realtime service

## Expected behavior
Should run without problem

## System information

- OS: Debian 10
- Database : Postgre 12 from OVH

**Comment by sweatybridge** [comment]
Hello @KevinHamonApp, there are additional schemas that need to be created on your external database for postgrest, realtime, storage, and gotrue to work. You can find these migrations in [supabase/postgres](https://github.com/supabase/postgres/tree/develop/migrations) repo. However, we have not tried migrating on Postgres 12 so your mileage may vary.

I will update the docs to be clearer about various roles required by these services. In addition to `authenticator` and `supabase_admin`, you would also need `supabase_storage_admin` and `supabase_auth_admin` as specified in [this script](https://github.com/supabase/supabase/blob/master/docker/volumes/db/roles.sql).

**Comment by KevinHamonApp** [comment]
@sweatybridge Thanks for your answer and for having updated the docs !
I understand that the database need more specifications, and that "any PostgreSQL provider" does not correspond. 
For example, I use to work with OVH, and their products does not allow new schemas creation.
Is it a deal blocker to use this database with supabase ?

**Comment by sweatybridge** [comment]
> does not allow new schemas creation, and logical replication

I think new schema creation is necessary because a lot of our authentication functionalities is hardcoded to use the `auth` schema. Afaik, logical replication is only required for realtime, not other services.

Also, we kinda assumed that users have full superuser access to their self-hosted database. There are [event triggers](https://github.com/supabase/postgres/blob/develop/migrations/db/init-scripts/00000000000003-post-setup.sql#L42) in our internal migrations that require superuser to create.

> Maybe do you have a specifications list for the database provider?

I'm not aware of any specification list unfortunately. May be @silentworks has some ideas?

**Comment by silentworks** [comment]
@KevinHamonApp I don't we have a list of database providers as most VPS hosts allow you to install your own Postgres on their server which gives you full access to the database and the server. I think from what you mention about OVH would be with managed Postgres and not one that you install on your own VPS.
