### ISSUE TITLE
Clarify listUsers() example

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase#11463]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-admin-createuser

## Describe the problem

The default example code will return the first 50 users, not the full list.

## Describe the improvement

Should clarify that it will only return 50.

## Additional context

![Screenshot_20230105_071214_Firefox~2.jpg](https://user-images.githubusercontent.com/25783093/210780114-fc8c36bd-3d99-47a9-9e35-efc348411aa7.jpg)

**Comment by juzhiyuan** [comment]
Yes, maybe the "full" confuses developers:)

**Comment by Hallidayo** [comment]
Hi @j4w8n - I've created a pull for this to change the title of the example.

I did see their is a note in the docs to say: `Defaults to return 50 users per page.`
