### ISSUE TITLE
Can't connect to database through cmd or pgadmin

### ISSUE THREAD

**Issue by vincent0426** [supabase/supabase#11465]
# Bug report
always get failed: Connection refused Is the server running on that host and accepting TCP/IP connections?
## To Reproduce
Follow the instructions in https://supabase.com/docs/guides/database/connecting-to-postgres
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior
should connect properly

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by m3ggle** [comment]
I have the same problem -_-, but before that it work just fine
