### ISSUE TITLE
Ambiguous error handling

### ISSUE THREAD

**Issue by szmarczak** [supabase/supabase#11500]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit

## Describe the problem

```js
  async function signOut() {
    try {
      loading = true
      let { error } = await supabase.auth.signOut()
      if (error) throw error
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      loading = false
    }
  }
```

The error is handled twice: `if (error) ` and `catch (error)`. It is not clear if `await signOut()` can throw even without the `if`.

## Describe the improvement

If the `error` is not an `Error` but an object with metadata, the above should look like this:

```js
  async function signOut() {
    loading = true
    const { errorDetails: error } = await supabase.auth.signOut()
    if (errorDetails) {
        // handle error here, assuming the handler does not throw
    }
    loading = false
  }
```

If the `error` is an instance of `Error`, then it should look like this:

```js
const throwable = async (promise) => {
    const result = await promise;
    if (result?.error) {
        throw result.error;
    }
    return result?.data ?? result;
};

  async function signOut() {
    loading = true
    try {
        await throwable(supabase.auth.signOut())
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message)
      }
    } finally {
      loading = false
    }
  }
```

If the original is still desired, it should be documented whether `signOut()` (or any other async function) throws or not.

**Comment by silentworks** [comment]
You are correct indeed that this can be simplified. The `supabase-js` library doesn't throw errors, it just returns them so we could follow your first suggestion with this one.

**Comment by szmarczak** [comment]
I do not understand the idea behind returning the error and not throwing instead. Consider the following:

```js
await supabase.from('example').insert({
	user_id: (await supabase.auth.getUser()).data?.user?.id,
});
```

Here, if `getUser()` fails, it will still try to make an insert. If `user_id` is nullable, then it will be `NULL` instead of the expected actual user id.

Can you please explain the rationale behind returning the error?

**Comment by szmarczak** [comment]
Could you clarify if the [following](https://supabase.com/docs/guides/auth/server-side-rendering) throws or is the example outdated:

```js
const refreshToken = req.cookies['my-refresh-token']
const accessToken = req.cookies['my-access-token']

if (refreshToken && accessToken) {
  await supabase.auth.setSession({
    refresh_token: refreshToken,
    access_token: accessToken,
  })
} else {
  // make sure you handle this case!
  throw new Error('User is not authenticated.')
}

// returns user information
await supabase.auth.getUser()
```

**Comment by charislam** [comment]
Closing as complete because the SvelteKit guide has been updated and the original code has been replaced

If you'd like to see a `supabase/throwable`, please open a Discussion under Feature Requests
