### ISSUE TITLE
Database returns an empty array

### ISSUE THREAD

**Issue by Bigmancozmo** [supabase/supabase#11522]
I need to get information from the database, but it's just returning an empty array.
[] is the array, **null** is the error.
![image](https://user-images.githubusercontent.com/67850768/211198905-a19f9494-9080-497a-8a9a-aa05e7e3a285.png)
Here's my code:
![image](https://user-images.githubusercontent.com/67850768/211198937-63bba90b-7f74-4f82-a975-7d5f6075586a.png)
I'm using the key that can bypass RLS.

**Comment by GaryAustin1** [comment]
Did you ever figure out the situation here?  Sure seems like RLS or now rows in public.users.

**Comment by Bigmancozmo** [comment]
Yes, I thought I closed this.

**Comment by Bigmancozmo** [comment]
turns out i  had forgotten i had posted this and made a new one
