### ISSUE TITLE
jobinfoscheddulerservice - Transportregistrar -firebaseapp leaked,

### ISSUE THREAD

**Issue by haohz1987** [supabase/supabase#11534]
FirebaseApp.initializeApp(this)
    firebaseApp.initializeAllApis();
     private static class UserUnlockReceiver extends BroadcastReceiver {}
unable to unregister()

**Comment by haohz1987** [comment]
com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService instance
                                                                                                    ​     Leaking: YES (ObjectWatcher was watching this because com.google.android.datatransport.runtime.scheduling.
                                                                                                    ​     jobscheduling.JobInfoSchedulerService received Service#onDestroy() callback and Service not held by
                                                                                                    ​     ActivityThread)

**Comment by GaryAustin1** [comment]
Deleting this as makes no sense in context of Supabase.
