### ISSUE TITLE
POSTGIS_TIGER_GEOCODER "tiger" schema not added to search path

### ISSUE THREAD

**Issue by jaredramirez** [supabase/supabase#1154]
# Bug report

## Describe the bug

After adding the extension `POSTGIS_TIGER_GEOCODER`, the schema it adds all it's tables under is not part of the postgres search path by default.

## To Reproduce

1. Enabled `POSTGIS_TIGER_GEOCODER`
2. Try to use any function from it, such as `pagc_normalize_address`

This results in the error:
```
function pagc_normalize_address(unknown) does not exist
```

If we prefix it with `tiger`, like `tiger.pagc_normalize_address`, then it errors with:
```
type "norm_addy" does not exist
```
Because the function definition references `norm_addy`, a type in the `tiger` schema.

Lastly, if we add `SET search_path = "$user", public, auth, extensions, tiger;`, then using the original, non-prefixed `pagc_normalize_address`, it works as expected!

## Expected behavior

Supabase should auto add the `tiger` schema to the postgres search path so users don't have to use `SET search_path` directly.

## System information

- Browser: Brave

**Comment by kiwicopple** [comment]
Hey @jaredramirez - I believe we have fixed this but not rolled out the patch to everyone. Can you please try running this and let me know if it works afterwards?

```
grant usage  on schema extensions to postgres, anon, authenticated, service_role;
```

**Comment by jaredramirez** [comment]
That didn't work for me. After running that, any query using any `tiger` stuff fails without including
```
SET search_path = "$user", public, auth, extensions, tiger;
```

For good measure, I also tried
```
grant usage on schema tiger to postgres, anon, authenticated, service_role; 
```
But no luck

**Comment by jaredramirez** [comment]
I'm not getting any `permission to access schema tiger` errors, only that it's not accessible in the default scope. Once I added `tiger` to the search path, it work perfectly!

**Comment by burmecia** [comment]
The schema `tiger` is specific to extension `POSTGIS_TIGER_GEOCODER` and seems we cannot change its name, so you'll have to specify it in `search_path`, which can be set in `Settings -> API -> Settings -> Extra search path`. Note that only applies to REST API, for direct db connection you still need to set it manually.

**Comment by jaredramirez** [comment]
We migrated to a new supabase to update our postgres version and where able to enable & use postgis_tiger successfully. Not sure that the original issue was but seems it works for new projects
