### ISSUE TITLE
Error in "PostGIS: Geo queries" Documentation

### ISSUE THREAD

**Issue by aaronksaunders** [supabase/supabase#11546]
# Bug report
- https://supabase.com/docs/guides/database/extensions/postgis

## Describe the bug
The documentation states

_Another thing to watch for is that there is no comma between the two values, just a single space._

indicating that when adding the location to the database one should not use a comma in the statement

`st_point(-73.946823 40.807416)`

when following those instructions I am getting an error that is only resolved when I add the commas

## To Reproduce

```
insert into public.chargers_v2
(name, location, description)
values ('Arlington, VA', st_point(-77.1629328 38.8875442), '')
```
will generate the error
```
Failed to validate sql query: syntax error at or near "38.8875442"
```
@dshukertjr

**Comment by dshukertjr** [comment]
@aaronksaunders Thanks for reporting this. You are right! It's was only for inserting values directly from the client libraries that the comma is not necessary. Will compose a PR to fix this right now!
