### ISSUE TITLE
Cannot sign in with nodejs

### ISSUE THREAD

**Issue by tw1t611** [supabase/supabase#11559]
# Bug report

## Describe the bug

I am trying to signIn an `auth.user` with email/password using this setup:
https://supabase.com/docs/guides/auth/row-level-security#policies-with-joins

Teams`team1` and `team2` were created.
A user `info@polyma.io` was created and added to `team1` with `user_id` matching `auth.user.id`.
Email confirmation was disabled.

All teams and members are returned with rls enabled using the service key.
However, using the anon_public_key nothing gets returned after login. The session is `null`.
Adding target roles on teams policy "anon, authenticated" does not change the behavior.

## To Reproduce

```js
  import { createClient } from "@supabase/supabase-js";

  // 1. create client with public key
  const supabase = createClient(
    "https://raaelzawgpcwukzilwmt.supabase.co",
    "anon_public_key"
  );

  // No difference in behavior if signed up here
  // const { data, error } = await supabase.auth.signUp({
  //   email: "info@polyma.io",
  //   password: "<pw>",
  // });

  // 2. sign in member
  const { data, error } = await supabase.auth.signInWithPassword({
    email: "info@polyma.io",
    password: "<pw>",
  });
  console.log(1, JSON.stringify(data, null, 2), error);

  const {
    data: { session },
  } = await supabase.auth.getSession();
  console.log("session returns null after sign in", session);

  // 3. no teams or members are returned if client was created with anon_public_key
  const { data: testData, error: testError } = await supabase
    .from("teams")
    .select("*,members(*)");
  console.log(JSON.stringify(testData, null, 2), testError);
```

## Expected behavior

Teams ans members data get returned if member is part of the team.

## System information

- OS: fedora
- Version of supabase-js: 2.2.3 (latest)
- Version of supabase-gotrue-js: 2.6.1 (latest)
- Version of Node.js: 18.12.1

**Comment by hefler** [comment]
I'm facing similar issues as @tw1t611. Although, in my application I use `supabase.auth.signInWithOtp` (with token). Checking the Auth logs I see `"msg": "401: Token has expired or is invalid"` when I run `verifyOtp`. I'm relative new to Supabase so I'm not sure if this is a bug, an implementation failure, or something else.

**Comment by GaryAustin1** [comment]
@tw1t611 Please look at this issue https://github.com/supabase/gotrue-js/issues/539, if you have not resolved this.  If you are in an environment without local storage you need to createClient with persistSession:false or you will get null on the session.

If you have resolved please respond so this can be closed.

@hefler  I would start a different issue if it is still a problem.  Could be you were using the wrong token type in the verifyOtp.

**Comment by tw1t611** [comment]
@GaryAustin1 Ty, that worked for me.

```js
  import { createClient } from "@supabase/supabase-js";

  // 1. create client with public key
  const supabase = createClient(
    "https://<projectId>.supabase.co",
    "<anon_public_key>",
    {
      auth: {
        persistSession: false,
      },
    }
  );

  // 2. sign in member
  const { data, error } = await supabase.auth.signInWithPassword({
    email: "<email>",
    password: "<pw>",

  });
  console.log(data.session.access_token);

**Comment by Wamy-Dev** [comment]
> @GaryAustin1 Ty, that worked for me.
> 
> ```js
>   import { createClient } from "@supabase/supabase-js";
> 
>   // 1. create client with public key
>   const supabase = createClient(
>     "https://<projectId>.supabase.co",
>     "<anon_public_key>",
>     {
>       auth: {
>         persistSession: false,
>       },
>     }
>   );
> 
>   // 2. sign in member
>   const { data, error } = await supabase.auth.signInWithPassword({
>     email: "<email>",
>     password: "<pw>",
> 
>   });
>   console.log(data.session.access_token);
> ```

this doesnt seem to return anything when I console.log the data.session.

**Comment by GaryAustin1** [comment]
@Wamy-Dev you are probably using this with confirm email set in the dashboard.  If so it will not return session but instead redirect from the email.

**Comment by Wamy-Dev** [comment]
so if a users email IS confirmed, then it WONT return a session? When I tried the code, it returned nothing and in the Auth logs, nothing appeared.

**Comment by GaryAustin1** [comment]
Sorry I was thinking of signUp.  Yes A session or error should be returned.

**Comment by Wamy-Dev** [comment]
any reason for it not?

**Comment by nestorbfgo** [comment]
I facing same problem here I using verifyOtp like this

`export const verifyOTP = async (formData: FormData) => {
    
    const email = formData.get("email") as string;
    const token = formData.get("otp") as string;
    console.log("email",email)

    console.log("token:",token)
    console.log("token:",token.length)

    const supabase = createClient();
  
    const { error } = await supabase.auth.verifyOtp({
      email: email,
      token: token,
      type: "magiclink",
    });

    console.log("mensaje")
  
    if (error) {
      console.error(error);
      return redirect("/error");
    }
  
    return redirect("/catalog");
  };`

and intializing createClient like this `
mport { createServerClient, type CookieOptions } from '@supabase/ssr'
import { cookies } from 'next/headers'

export function createClient() {
  const cookieStore = cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options })
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options })
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  )
}
`

I'm not sure why Im getting this error **AuthApiError: Token has expired or is invali**
 Is there a way to solve it?
