### ISSUE TITLE
Unable to search docs with query: sql editor

### ISSUE THREAD

**Issue by rdela** [supabase/supabase#11571]
no hits for `sql editor` which would be nice to document at least a little, plus the only hit for `sql` is [Converting SQL to JavaScript API](https://supabase.com/docs/guides/database/sql-to-api)

**Comment by gregnr** [comment]
@rdela Thanks for the issue. This is fixed now that we've switched to an embeddings-based search:

https://github.com/supabase/supabase/pull/12506

Unfortunately the result doesn't appear first:
![image](https://user-images.githubusercontent.com/4133076/226468612-2132e57e-dc8e-4f0c-aa05-2d68aec1cb46.png)

But this'll get fixed as we continuously improve the new search.
