### ISSUE TITLE
"Quickstart: Vue 3 - Bonus: Profile photos" leaks images

### ISSUE THREAD

**Issue by tvogel** [supabase/supabase#11587]
The code in [Quickstart: Vue 3 - Bonus: Profile photos](https://supabase.com/docs/guides/getting-started/tutorials/with-vue-3#bonus-profile-photos) does not care to clean up the previous photo when repeatedly uploading photos. As the filenames are random, a zoo of orphan files will accumulate in the `avatars` bucket.

It would be super instructive to see how to properly deal with this. As a newbie, I could just add code in the client that stores the previous `avatar_url` and after the replacement would delete it but from a database point of view, I would much prefer to see how I can install update/delete triggers which will delete any superseded avatar_url automatically. This would also make the "Delete User" function in the dash-board work which currently fails as long as the user to be deleted still owns storage objects! Currently, I need to clean them out by hand before I can delete the user.

I saw some posts that suggest to use the Postgres HTTP extension to issue the necessary deletes. If that's the route to go, it feels like the quickstarts are a good place to introduce this concept as it seems to be a core functionality for keeping storage and database consistent.

**Comment by GaryAustin1** [comment]
Looks like this was added.
https://supabase.com/docs/guides/getting-started/tutorials/with-vue-3#storage-management
