### ISSUE TITLE
Wrong age of Postgres in several READMEs

### ISSUE THREAD

**Issue by 0xflotus** [supabase/supabase#11615]
Sorry guys,

there is one thing I discovered and have to tell you. In several READMEs I found the following sentence in different languages, the following one is the english one:

> [PostgreSQL](https://www.postgresql.org/) is an object-relational database system with __**over 30 years**__ of active development [...]

But if I go to the [official Postgres Website](https://www.postgresql.org/) and look at the footer, I find a copyright entry of:

> Copyright © 1996-2023 The PostgreSQL Global Development Group

There is also a [blog post from Postgres](https://www.postgresql.org/about/news/happy-birthday-postgresql-978/) that says the birth date of Postgres is July, 8th 1996.

$$
2023 - 1996 = 27
$$

$$ 27 < 30 $$

Postgres turns 27 this July...
So it's not true, that Postgres has a history of over 30 years of active development.

**Comment by GaryAustin1** [comment]
Not sure you are correct either...
Postgres has been around almost 10 years longer than PostgreSQL which was a renaming and broadening of the original Postgres.
https://www.postgresql.org/docs/current/history.html
So it may be valid to argue PostgreSQL is 27 years old, but then you say Postgres has a history of over 30 years which is true.

**Comment by 0xflotus** [comment]
Wow, this is a very confusing topic I guess.
Ok, so Postgres (the Database) is over 30 years old and PostgreSQL is nearly 27 years old?

**Comment by GaryAustin1** [comment]
@0xflotus can you close this issue unless you are looking for other info?
Supabase is trying to get more focus on issues but there are many still floating open after being answered.  (I can't close the issue)
Thanks!

**Comment by 0xflotus** [comment]
Sure.
