### ISSUE TITLE
When misstyping auth-domains you can add an empty entry which cannot be deleted

### ISSUE THREAD

**Issue by dennisdenk** [supabase/supabase#11639]
# Bug report

## Describe the bug

When adding a new domain to auth redirects and you add "https://exampledomain.com, "  exampledomain.com as well as an empty entry gets created. That empty entry cannot be deleted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to  https://app.supabase.com/project/PROJECT_ID/auth/url-configuration
2. "Add URL"
3. Type "https://exampledomain.com, "

## Screenshots

![image](https://user-images.githubusercontent.com/19978270/212324625-1b035aec-5fbb-412d-b5b7-47c9509a7da1.png)

**Comment by hf** [comment]
Thanks! Should be getting fixed soon!
