### ISSUE TITLE
Move LW6 link from menu to footer

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#11641]
Some menu updates:

Need to remove Launch Week 6 from the header menu and add it to the footer under Product. 
<img width="1222" alt="CleanShot 2023-01-13 at 10 47 36@2x" src="https://user-images.githubusercontent.com/105593/212340936-65b0ed94-d0a1-4e0c-bed7-3bf65466d7ef.png">

Also need to remove this Beta item:
<img width="571" alt="CleanShot 2023-01-13 at 10 48 30@2x" src="https://user-images.githubusercontent.com/105593/212341182-76ce8f6e-0bdd-4c3e-b38e-d9c634ebf591.png">

**Comment by c00kie123** [comment]
Hey, I can help with this!

**Comment by saltcod** [comment]
Yeah @c00kie123, exactly!   Appreciated!

**Comment by c00kie123** [comment]
Hey @saltcod, I have a question. In `supabase/apps/www/components/Footer/index.tsx`, one of the lines is `import Link from 'next/link'`, may I ask where is this `next/link` is located?

**Comment by MildTomato** [comment]
@c00kie123 it's an npm package.

https://nextjs.org/docs/api-reference/next/link

**Comment by alaister** [comment]
Resolved by #11688
