### ISSUE TITLE
Returning Secret with ":" in it returns INVALID_KEY

### ISSUE THREAD

**Issue by MerlinChiodo** [supabase/supabase#11642]
# Bug report

## Describe the bug

Returning Secret with ":" in it returns INVALID_KEY

## To Reproduce

1. supabase secrets set TEST_KEY=VERYLOGKEYkeykeyseperatedwith:KEY
2. functions serve ...
4. as soon as the Function calls Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
 (which normally returns the key)
It returns this: 

```
key=undefined
<HTML>
<HEAD>
<TITLE>INVALID_KEY</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>INVALID_KEY</H1>
<H2>Error 401</H2>
</BODY>
</HTML>
```

The key is 153 chars long.

## Expected behavior

Should work

## System information

- OS: [Windows 11]
- Windows PowerShell
- Version of supabase-flutter: newest

**Comment by KevinBrolly** [comment]
We have made lots of changes to edge functions since this was opened and it appears this issue is now stale, I am going to close the issue but if it should still be actioned please do leave a comment and we can re-open.

Thank you again for the bug report!
