### ISSUE TITLE
Can not delete project and organization

### ISSUE THREAD

**Issue by marina1017** [supabase/supabase#11644]
# Bug report

## Describe the bug

I can not delete project and organization.

## To Reproduce
1. Go to Project Settings
2. Click on Delete Project button

## Expected behavior
I expect to delete the organization and the project

## Screenshots
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/10338059/212354134-8d0a0342-6b9f-400f-9974-f6f05ce7df4d.png">
<img width="1678" alt="スクリーンショット 2023-01-13 23 50 51" src="https://user-images.githubusercontent.com/10338059/212355123-45e2f9ab-d919-4d06-912b-4a81780f3ddf.png">

## System information

- OS:  macOS
- Browser chrome

**Comment by Auroratide** [comment]
I just tried to delete a project and ran into the same error.

In case it is helpful to the team, this was my `errorEventId` that I got from inspecting the DELETE request: `55097cda278f40f0b1567e7c91fd2a7c`.

**Comment by MildTomato** [comment]
@phamhieu maybe issue with our API

**Comment by EugeneGohh** [comment]
Can I try take on this bug? 

@MildTomato @phamhieu

**Comment by saltcod** [comment]
Closing as outdated. Please feel free to reopen if issue persists. Thanks!
