### ISSUE TITLE
Indicate Realtime enabled for tables

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#11647]
Add a column to the database tables view that indicates if the table has Realtime enabled
<img width="1210" alt="CleanShot 2023-01-13 at 12 30 43@2x" src="https://user-images.githubusercontent.com/105593/212364500-401430ac-934d-45c2-8a5c-f8ae5e822242.png">
 
Not sure about header length there — might be best if it's just "Realtime" instead of "Realtime enabled"

**Comment by animeshdas2000** [comment]
Hey,
I am a new contributor. This seems a good issue to just setup the codebase on local and do the changes. Can you please assign this issue to me so that I can start working on it. Thanks!

**Comment by ruggi99** [comment]
@animeshdas2000 there is already a open PR for this issue. You see it linked just above your comment
