### ISSUE TITLE
sign out supabase does not clear the current session

### ISSUE THREAD

**Issue by devalensio** [supabase/supabase#11664]
# Bug report

## Describe the bug

Sign out supabase does not clear the current session in v1.0.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. execute auth.signOut
2. hard refresh the flutter app
3. go to splash page
4. on the splash page, the auth.currentSession still exists

## Expected behavior

current session should be cleared after signing out

## Screenshots

-

## System information

- OS: IOS, Android
- Browser (if applies) -
- Version of supabase-js: v.1.3.0
- Version of Node.js: -

## Additional context

-

**Comment by GaryAustin1** [comment]
You are running a very old supasbase-js.   Version 2 is long out now and the last 1 version was something like 1.35.7 or higher.
