### ISSUE TITLE
fkey relationship wasn't dropped when deleting a column

### ISSUE THREAD

**Issue by nasiscoe** [supabase/supabase#1166]
# Bug report

## Describe the bug

I had an issue querying in a `select` statement because there was more than one fkey relationship and my database wasn't sure which one to use. Turns out that a foreign key relationship hadn't been dropped when I had deleted an old column.

I had to manually drop the old foreign key relationship to fix the issue i.e. `ALTER TABLE inventories DROP CONSTRAINT product_locations_product_fkey`

## To Reproduce

Unsure how to produce, but the issue occurred for me after dropping a column with a fkey relationship and creating a new column with the same fkey relationship.

## Expected behavior

I would expect relationships to be dropped with the columns.

## System information

- OS: macOS
- Browser: Chrome

**Comment by kiwicopple** [comment]
Hey @nasiscoe - without steps to replicate this, it's a bit hard for us to debug this one. Supabase projects are literally just Postgres databases, we don't do anything special to the database or modify it (beyond adding some extensions).

The default behaviour of Postgres is to drop any constraints when a column is dropped. You should be able to replicate this - a good tutorial here:

https://www.postgresqltutorial.com/postgresql-drop-column/

<img width="832" alt="image" src="https://user-images.githubusercontent.com/10214025/114992244-1f90ce00-9ecd-11eb-874b-ab4fa20fea02.png">


I'll close this now, but if you can find a way to replicate then I'll be happy to jump in again 👍

**Comment by albertkimdev** [comment]
@kiwicopple can you provide a code example of how to implement that delete example you posted with Supabase code?

**Comment by kiwicopple** [comment]
Sure @albertkimdev, just to clarify one thing: 

> with Supabase code

There is only SQL (specifically PostgreSQL) code involved, since Supabase projects are Postgres databases. There isn't really any "supabase code" (unless you're referring to our APIs?)

Specifically to OP's question:

```sql
CREATE TABLE categories (
    id serial PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE books (
    id serial PRIMARY KEY,
    title VARCHAR NOT NULL,
    category_id INT NOT NULL REFERENCES categories
);
```

Behind the scenes Postgres will create a Foreign key constraint for the `books.category_id` column. 

If then you call:

```sql
ALTER TABLE books 
DROP COLUMN category_id;
```

Postgres will also remove the constraint.
