### ISSUE TITLE
Cookie not set when using the Sveltekit Auth helper and Server-Side forms

### ISSUE THREAD

**Issue by gkatsanos** [supabase/supabase#11663]
# Bug report

## Describe the bug

I followed the guide under https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit and was able to login with magic link + login with email/password succesfully, as long as the form submission JS stayed in the component (client side?).

As Sveltekit leverages a server as well, I moved the two login methods I had created, inside a `+page.server.ts` file and added an action name in my form, as shown in the [SvelteKit docs](https://kit.svelte.dev/docs/form-actions). 

```html
<form method="POST" action="?/login-with-password" use:enhance class="max-w-lg mb-4">
 the form..
</form>
```
```ts
export const actions: Actions = {
  'login-with-password': async ({ request }) => {
    const formData = await request.formData();
    const email = formData.get('email');
    const password = formData.get('password');
    console.log(email, password);
    const { error } = await supabaseClient.auth.signInWithPassword({ email, password });
    if (error) {
      return {
        status: 500,
        body: {
          error: error.message
        }
      };
    }
    throw redirect(302, '/');
    return { success: true };
  }
}
```

Confirming with the logs, the authentication happens succesfully on the supabase side, but the Cookie with the Token is not set in my app.
My initial assumption was that the `@supabase/auth-helpers-sveltekit` takes care of that:

https://github.com/supabase/auth-helpers/blob/b2046950dd846f6f52f17482caccd25a2f393581/packages/sveltekit/src/createClient.ts#L11

I assume that in order for this to work, I need to somehow follow the [Server Side Rendering](https://supabase.com/docs/guides/auth/server-side-rendering) guide? (the magic link works I guess as it provides for the redirect for me so the cookie is created succesfully)

Is the redirect logic missing on my end or is the auth helper having a bug? 

## To Reproduce

I've added my project to [stackblitz](https://stackblitz.com/~/github.com/gkatsanos/client) (naturally it won't run as it'll be missing my project/auth credentials and schemas/tables..) but at least someone could verify if the setup for the auth helper library is done as it should.

**Comment by david-plugge** [comment]
Make sure you use the `getSupabase` helper. The returned supabase instance is tied to the request and can set cookies accordingly

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#protecting-actions

**Comment by gkatsanos** [comment]
> Make sure you use the `getSupabase` helper. The returned supabase instance is tied to the request and can set cookies accordingly
> 
> https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#protecting-actions

I am using it in my layout as per the guidelines:
```
import type { LayoutLoad } from './$types';
import { getSupabase } from '@supabase/auth-helpers-sveltekit';

export const load: LayoutLoad = async (event) => {
  const { session } = await getSupabase(event);
  return { session };
};
```

**Comment by gkatsanos** [comment]
@david-plugge adding ` +  const { session, supabaseClient } = await getSupabase(event);` this line before my `signInWithPassword` call seems to have done the trick, but this actually confused me more as to why this works.

**Comment by silentworks** [comment]
This is written in the guides. Maybe we need to write somewhere in there explicitly that you should not import the client from the createClient instance anywhere in your server side code. 

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#protecting-actions
