### ISSUE TITLE
Extremely high memory usage despite few queries

### ISSUE THREAD

**Issue by davidwitten** [supabase/supabase#11677]
# Bug report
I am seeing extraordinarily high memory usage, despite rarely using my DB. I even upgraded to double my RAM (paid $5/mo extra for this), but if anything, I've seen more errors.

## Describe the bug

![Screen Shot 2023-01-15 at 3 41 08 PM](https://user-images.githubusercontent.com/3642085/212573873-7738bfcb-d2ae-4e55-bc0d-990f889a2650.png)

## Expected behavior
A low amount of memory is used, considering I'm not making many queries. Any help debugging this? What should I be looking at to help find the source of this high usage?

**Comment by GaryAustin1** [comment]
Normally Postgres will use memory for caching (tables, disk, etc) and can free those as needed for critical things.

I'm used to seeing mid 90's on a test system with 10 access a day. 

Are you seeing any errors or slow down of your queries?

I believe there are 3rd party tools that can look at what the memory is being used for, but I can't point you there.

**Comment by GaryAustin1** [comment]
Then sounds like it is an issue, have you contacted support?

**Comment by GaryAustin1** [comment]
Did this ever get resolved for you?  If so can you close the issue.  Thanks.

**Comment by steve-chavez** [comment]
Maybe it could be related to https://github.com/PostgREST/postgrest/issues/2638. 

A fix is still pending but this is mitigated on the latest postgREST version(v10.1.2, new Supabase projects have it and existing can be paused/unpaused), which restarts pool connections when you make a schema change.

**Comment by davidwitten** [comment]
Update:

I did the following:
```
SELECT count(1) FROM pg_stat_activity where state='idle'
```
and it returned 33, which made little sense, as I was barely using the DB. I contacted supabase support, and they set the max number of connections to 10, which resolved the issue.

**Comment by GaryAustin1** [comment]
Going to close this.  Feel free to comment here, or better start a new issue if it arises again.
