### ISSUE TITLE
improve Realtime docs for `anon` role applications.

### ISSUE THREAD

**Issue by whymidnight** [supabase/supabase#11707]
# Improve documentation

## Link 

[Enable Realtime for database tables](https://supabase.com/docs/guides/auth/row-level-security#enable-realtime-for-database-tables)

## Describe the problem

the Supabase UI nor docs make it clear that enabling Realtime for an application that wants to listen for table `update` events using an `anon` key requires two policies of `select` and `update` with the `anon` role on that table. i naively presumed the following -

```sql
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime with (publish = 'update');
commit;

alter publication supabase_realtime add table foo;

create policy "anon_foo_update_policy"
on public.foo
for update
to anon
using (
  true
) with check (
  true
);
```

## Describe the improvement

i was however able to resolve the issue by adding an additional policy to my migration -

```sql
create policy "anon_foo_select_policy"
on public.foo
for select
to anon
using (
  true
);
```

## Additional context

i use Supabase's postgres db natively via `psql` and through a rust backend using [`sqlx`](https://github.com/launchbadge/sqlx). my entire db schema gets imported/migrated with `psql` and queried using `sqlx`.

i [describe my issue in #4342](https://github.com/supabase/supabase/discussions/4342#discussioncomment-4706194) where:
> basically if you want to scope the anon role with rls and realtime, you need to pair the update policy with a select policy. otherwise with just an update policy on an rls+realtime enabled table, realtime update events will not propagate to the client.

in retrospect this makes sense - an `update` event is emitted and the row needs to be _selected_ so that the data can be read and transmitted to the client. though it wasn't immediately obvious. just wanted to share my feedback.

**Comment by w3b6x9** [comment]
@whymidnight thanks, this is good feedback. I'll make changes so it is clear that Realtime RLS requires a SELECT policy.

**Comment by GaryAustin1** [comment]
Closing this as this is documented.
