### ISSUE TITLE
What does user!.id mean? 

### ISSUE THREAD

**Issue by sroussey** [supabase/supabase#11716]
https://github.com/supabase/supabase/blob/132022225fe4123fdb96f3a5ad6714f87eaf61fd/examples/user-management/nextjs-ts-user-management/components/Account.tsx#L83

What does `user!.id` mean? Should be `user?.id` perhaps?

**Comment by andrewschmidgit** [comment]
It's the [non-null-assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)

Basically the developer is saying "I am sure `user` is not null in this context, and I'm trying to access the `id` property"

**Comment by sroussey** [comment]
Damn. I stop using typescript for a while but that feature train didn’t stop. Thanks.
