### ISSUE TITLE
Deleting a table and recreating same to change int/uuid columns requires a database restart.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#11714]
# Bug report

## Describe the bug
Changing a column from int to uuid, or the opposite in SOME cases requires a restart of the database to avoid this error 
`"message": "invalid input syntax for type bigint"`

Doing a PostgREST cache flush does not work.
I am unable to reproduce this, but we now have at least 5 users with this happening over the past few weeks and not before...
EDIT:   I WAS ABLE TO REPRODUCE BELOW.

https://github.com/supabase/supabase/discussions/11684#discussioncomment-4709174
The first link below has the most detail.
https://discord.com/channels/839993398554656828/1057225488071921714/1057225488071921714
 https://discord.com/channels/839993398554656828/1044987353766297650/1063200411743428731
https://discord.com/channels/839993398554656828/1062454638793723944/1062454638793723944
https://discord.com/channels/839993398554656828/1058597805217824788/1058603135859437578

## To Reproduce

Most of the cases involve wanting to change a primary or foreign key from uuid to int, or the opposite.  

This is not doable in the UI, so as a way to get it done these users delete the table and create a new table with the same name.
I believe all of the links describe what they did. 

I've tried doing that on one instance (pg15) and do not encounter the error.

## Expected behavior

Deleting and recreating a table does not require a restart of the database.

**Comment by GaryAustin1** [comment]
Adding another from today...
https://discord.com/channels/839993398554656828/1065343808486768750/1065343808486768750

**Comment by enriquemorenotent** [comment]
Yeah, that happened to me.

**Comment by GaryAustin1** [comment]
I have been able to reproduce this.

Create a table with a uuid primary key in the UI and populate a row.
![image](https://user-images.githubusercontent.com/54564956/213295987-774ae75f-fc24-4822-a6a4-705b41602260.png)
Select from the UI with UUID
![image](https://user-images.githubusercontent.com/54564956/213296127-0e05f4b0-b261-4140-ae58-b2abe6dd45c4.png)
Works.

Delete the table using the UI.
Create a new table with same name with a primary column of bigint with is identity and populate a row.
![image](https://user-images.githubusercontent.com/54564956/213296612-30885b0f-f761-4791-98dd-4251dda0f2b5.png)
Change the client call to use int 1.
![image](https://user-images.githubusercontent.com/54564956/213296877-1af4f017-c67e-463c-87b4-45b55a0ceac9.png)
Run as many times as you want and get error...
![image](https://user-images.githubusercontent.com/54564956/213297006-53949a10-cf1e-41c2-b771-f26eefb369f3.png)

SQL read of table works...
![image](https://user-images.githubusercontent.com/54564956/213297151-986bce2b-bea1-400c-b141-656ec53241d4.png)
SQL dump of table structure seems correct.
![image](https://user-images.githubusercontent.com/54564956/213297382-04a5cea2-a3b5-40eb-a635-c32d2da3507d.png)

Flushing PostgREST cached does not work.

Restarting database works.

This is on an instance with Postgres15.1, PostgREST 10 and the new postgres user (not superadmin) for SQL.

**Comment by steve-chavez** [comment]
```json
{{"code":"22P02","details":null,"hint":null,"message":"invalid input syntax for type bigint: \"1\""}}
```

Very strange, the above 22P02 error code comes from PostgreSQL. See [error codes](https://www.postgresql.org/docs/current/errcodes-appendix.html#ERRCODES-TABLE).

**Comment by GaryAustin1** [comment]
I can no longer see the SQL in the logs that PostgREST generates (because I can't set pgaudit without super user), but as shown a simple SQL works at same time REST API is not.
I also just ruled out the UI as I created, dropped and created the table with SQL and get same result.

**Comment by GaryAustin1** [comment]
@steve-chavez  any chance a prepared statement could cause this if the table changes column types, but not names at all?
That is one difference between PostgREST and just the SQL call.  Also I don't believe the error happens if you do not do the request thru the API in between the changes.

**Comment by GaryAustin1** [comment]
Not sure this is related, but certainly prepared statements get confused if the table changes out from under them.
```
drop table cat1;
create table public.cat1
(
    id         uuid not null primary key,
    created_at timestamp with time zone default now(),
    test       text
);
alter table public.cat1owner to postgres;
grant delete, insert, references, select, trigger, truncate, update on public.cat to anon;
grant delete, insert, references, select, trigger, truncate, update on public.cat to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.cat to service_role;

PREPARE fooplan (unknown) AS
    SELECT from cat1 where id = $1;
EXECUTE fooplan('dea27321-f988-4a57-93e4-8eeb38f3cf1e');

drop table cat1;
create table public.cat1
(
    id         bigint GENERATED ALWAYS AS IDENTITY not null primary key,
    created_at timestamp with time zone default now(),
    test       text
);
alter table public.cat owner to postgres;
grant delete, insert, references, select, trigger, truncate, update on public.cat to anon;
grant delete, insert, references, select, trigger, truncate, update on public.cat to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.cat to service_role;

EXECUTE fooplan(1);
```
Generates a `Failed to run sql query: parameter $1 of type integer cannot be coerced to the expected type uuid`

**Comment by steve-chavez** [comment]
@GaryAustin1 Thanks a lot for your help :pray:. I've managed to reproduce the issue on https://github.com/PostgREST/postgrest/issues/2620.

**Comment by steve-chavez** [comment]
FYI, this was recently fixed and released on Supabase on https://github.com/supabase/postgres/pull/523.

All new projects should come with postgREST v10.1.2, for existing projects you can pause/unpause and your postgREST will get upgraded.

**Comment by enriquemorenotent** [comment]
Much appreciated
