### ISSUE TITLE
File upload `fileBody` type needs explanation

### ISSUE THREAD

**Issue by adamzerner** [supabase/supabase#11723]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/storage-from-upload

## Describe the problem

The type of `fileBody` just says `object`.

## Describe the improvement

Describe the type in more detail.

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
