### ISSUE TITLE
Unable to change organization name

### ISSUE THREAD

**Issue by mstade** [supabase/supabase#1172]
# Bug report

## Describe the bug

In the organization settings you can supposedly change the name of the organization. Nothing happens when clicking the save button however.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log in to Supabase
2. Click on the organization you want to change settings for
3. Type a new name for the organization
4. Click save
5. Watch and amaze while nothing happens 🤪

## Expected behavior

I expect the organization name to change when clicking save.

**Comment by mstade** [comment]
I invited my colleague to the team and he was able to change the name, oddly enough, and now that I tried it again it works. I'm going to chalk this one up to solar flares or something – apologies for the unnecessary noise!

**Comment by kiwicopple** [comment]
This is actually a valid error - it's because the form validation isn't showing properly (the billing address is also a required field)

We're fixing ..
