### ISSUE TITLE
Generating types Github Action depreciated Node version 

### ISSUE THREAD

**Issue by Stan-l-e-y** [supabase/supabase#11721]
# Improve documentation

## Link 

[Generating types, update types github action](https://supabase.com/docs/guides/api/generating-types#update-types-automatically-with-github-actions)

## Describe the problem

The Github Actions workflow script provided in this link is slightly outdated. As of recently Node.js 12 actions are deprecated, the following errors are displayed when running the build
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2.1.5. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

## Describe the improvement

As mentioned in the links provided by the errors as well as this issue [here](https://github.com/actions/checkout/issues/959#issuecomment-1342479774), the versions need to be changed to ``actions/checkout@v3`` and ``actions/setup-node@v3``. However, I currently still receive the same errors and it might be due to not updating the ``set-output`` command as described in the error warning link mentioning the upgrade to Environment files.

**Comment by charislam** [comment]
Closing as completed
