### ISSUE TITLE
Postgres version upgrade documentation only works for Free tier

### ISSUE THREAD

**Issue by kav** [supabase/supabase#11744]
# Bug report

## Describe the bug

https://app.supabase.com/project/qtrzyzcvkevkmayocdka/settings/general describes upgrading your Postgres version by pausing and restoring your project but pause and restore are not shown on the General Setting page for paid projects.

## To Reproduce

1. Create a new paid project
2. Go to General Settings
3. Observe no option to Pause or Restore

## Expected behavior

I'm not particularly concerned about the ability to pause and restore paid projects, that seems like it could be a major invoicing pain but it would be nice if I could upgrade to PG15 without downgrading to free and then upgrading back up.

**Comment by d-e-h-i-o** [comment]
@kav You can email the support, and they will do the upgrade for you. I just did it, and it worked very well. Maybe they should mention that in the docs.

**Comment by J0** [comment]
Hey,

Thanks for the query! As @d-e-h-i-o mentioned please email support if you'd like a postgres version upgrade
