### ISSUE TITLE
.textSearch is not a function

### ISSUE THREAD

**Issue by gomflo** [supabase/supabase#1175]
# Bug report

## Describe the bug

Im using Next.js with supaabse and im getting the following error:

```
TypeError: _utils_sb__WEBPACK_IMPORTED_MODULE_3__.default.from(...).textSearch is not a function
    at getStaticProps (webpack-internal:///./pages/index.js:105:74)
    at renderToHTML (/Users/hugo/code/futbolfeed-v2/node_modules/next/dist/next-server/server/render.js:28:1743)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/hugo/code/futbolfeed-v2/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/Users/hugo/code/futbolfeed-v2/node_modules/next/dist/lib/coalesced-function.js:1:330)
```

This is my very basic code

```javascript
const { data, error } = await supabase
    .from('posts')
    .textSearch('catchphrase', `'fat' & 'cat`, {
      config: 'english'
    })
```

With the latest supabase-js version ```"@supabase/supabase-js": "^1.11.0",```

**Comment by kiwicopple** [comment]
I believe this one might be missing a `select` ?

```js
const { data, error } = await supabase
    .from('posts')
    .select('id') // <----------------- add this first
    .textSearch('catchphrase', `'fat' & 'cat`, {
      config: 'english'
    })
```

**Comment by gomflo** [comment]
> I believe this one might be missing a `select` ?
> 
> ```js
> const { data, error } = await supabase
>     .from('posts')
>     .select('id') // <----------------- add this first
>     .textSearch('catchphrase', `'fat' & 'cat`, {
>       config: 'english'
>     })
> ```

My bad, thanks @kiwicopple you are right.

**Comment by kennethacohen** [comment]
FYI I think the issue here is just that the docs are also missing a select:

https://supabase.io/docs/reference/javascript/textsearch
