### ISSUE TITLE
Table Editor: Renaming a column that the table is being sorted on doesnt update the sort parameter + cannot remove the sort parameter

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#11761]
# Bug report

## To Reproduce
1. Open an existing table (or create the `countries` table through the SQL editor first) in the table editor
2. Apply a sort on one of them columns
3. Rename the column was sorted on
4. The URL param doesn't update and the table editor shows 0 rows with an error message
5. User is also unable to remove the sort from the sort dropdown

## Expected behavior
If the column that's being renamed is being used in a sort, update the name in the URL params as well

**Comment by ratika-12** [comment]
Hey @joshenlim I want to work on this issue. please assign me :-)

**Comment by gitstart** [comment]
Hello @joshenlim,
I believe this issue may be related to #10306. We submitted a pull request addressing it in #10532. Would you be able to review it again and let us know if any additional modifications are needed for it to fully align with the desired behavior?

**Comment by pratik-codes** [comment]
hi @ratika-12 If you wont pick it up let me know and @joshenlim can assign it to me

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source, this is my first time can you assign me this task.

**Comment by joshenlim** [comment]
hey there @Gingaaa! thanks for reaching out - but i'm afraid this issue has already been resolved actually, apologies that we've left it open! I'll be closing the issue now 🙏
