### ISSUE TITLE
2 foreign keys in separate tables referring to the another table's column creates error

### ISSUE THREAD

**Issue by SauceArgente** [supabase/supabase#1177]
# Bug report

## Describe the bug

When I have only one row pointing to a foreign key my guery works, but, when I add another ( on another table ) pointing to the same table it doesn't work anymore.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create two separate tables : a / b ( or comments / posts in my case )
2. Create a third table user
3. Make the author column of the tables a / b have a foreign key with the column user_id of the table user

## Screenshots

My query:
`    final questions = await client.from('question').select('''
        *,
        comments(
          *
        ),
        user(
          *
        ),
        likes(
          *
        )''')
        .order('id', ascending: true)
        .execute();`

The table containing all the posts
![image](https://user-images.githubusercontent.com/45178251/115067770-a8216580-9ef1-11eb-97f8-1c3b379742c6.png)

The comments table when it works
![image](https://user-images.githubusercontent.com/45178251/115067871-c71ff780-9ef1-11eb-96e3-d0443673a5cc.png)

The comments after I added the foreign key to user_id in the user table which creates the bug
![image](https://user-images.githubusercontent.com/45178251/115067964-e74fb680-9ef1-11eb-8899-f3469f929e35.png)

User table
![image](https://user-images.githubusercontent.com/45178251/115068029-f898c300-9ef1-11eb-8c00-dd2451afe39f.png)

## System information

- OS: Windows
- Browser : Running my app on Android 10
- Version of supabase-dart:  ^0.0.1-dev.11

**Comment by steve-chavez** [comment]
> My query:
> final questions = await client.from('question').select(''' *, comments( * ), user( * ), likes( * )''') .order('id', ascending: true) .execute();

The error is related to the `supabase-js` library right? Or is it related to the Table Editor GUI?

If it's about the library, check this discussion for a solution: https://github.com/supabase/supabase/discussions/809

**Comment by SauceArgente** [comment]
> > My query:
> > final questions = await client.from('question').select(''' *, comments( * ), user( * ), likes( * )''') .order('id', ascending: true) .execute();
> 
> The error is related to the `supabase-js` library right? Or is it related to the Table Editor GUI?
> 
> If it's about the library, check this discussion for a solution: #809

I don't what the bug is caused by ....  but I don't think it's library realted cause my guery doesn't change, the error occurs on the client once I added the second foreign key
If you don't understand what the error is please tell me but like I really don't understand why it's happening ...

**Comment by steve-chavez** [comment]
> the error occurs on the client once I added the second foreign key

Can you print(and share) the error when that happens? Try:

```js
const { questions, error } = await client
  .from('question')
  .select('*, comments( * ), user( * ), likes( * )')
  .order('id', ascending: true)
  .execute();

console.log(error);
```

**Comment by SauceArgente** [comment]
> > the error occurs on the client once I added the second foreign key
> 
> Can you print(and share) the error when that happens? Try:
> 
> ```js
> const { questions, error } = await client
>   .from('question')
>   .select('*, comments( * ), user( * ), likes( * )')
>   .order('id', ascending: true);
> 
> console.log(error);
> ```

I think it's actually a library error but I don't get why it happens though : `type 'List<dynamic>' is not a subtype of type 'String?' in type cast`

**Comment by SauceArgente** [comment]
> > the error occurs on the client once I added the second foreign key
> 
> Can you print(and share) the error when that happens? Try:
> 
> ```js
> const { questions, error } = await client
>   .from('question')
>   .select('*, comments( * ), user( * ), likes( * )')
>   .order('id', ascending: true);
> 
> console.log(error);
> ```

now by digging into the dart code I found the actual error : ```json
{"hint":"By following the 'details' key, disambiguate the request by changing the url to /origin?select=relationship(*) or /origin?select=target!relationship(*)","details":[{"relationship":"question_author_fkey[author][user_id]","origin":"public.question","cardinality":"m2o","target":"public.user"},{"relationship":"public.comments[comments_parent_fkey][comments_author_fkey]","origin":"public.question","cardinality":"m2m","target":"public.user"}],"message":"More than one relationship was found for question and user"}
```

so naturally I tried your first solution : ```*,
        comments(
          *
        ),
        user!user_id(
          *
        ),
        likes(
          *
        )```
        
 but I still get the same error for some reason

**Comment by SauceArgente** [comment]
> > the error occurs on the client once I added the second foreign key
> 
> Can you print(and share) the error when that happens? Try:
> 
> ```js
> const { questions, error } = await client
>   .from('question')
>   .select('*, comments( * ), user( * ), likes( * )')
>   .order('id', ascending: true);
> 
> console.log(error);
> ```

Nevermind I didn't quite catch how to use the '!' notation thanks for your help ! The dart library's error system is still very hard to understand so I couldn't figure out the answer !
