### ISSUE TITLE
Can't get data

### ISSUE THREAD

**Issue by Bigmancozmo** [supabase/supabase#11774]
I've been facing this problem for weeks, and I'm finally posting about it. Don't get mad at me if there's a solution I simply couldn't find.
Data:
![image](https://user-images.githubusercontent.com/67850768/213561982-974a74ef-7da5-41f0-9b10-414992608c01.png)
Console:
![image](https://user-images.githubusercontent.com/67850768/213562103-66ca0855-c40f-4339-9361-cf4c48daeb9b.png)
Code:
![image](https://user-images.githubusercontent.com/67850768/213562174-ab560b88-25fa-4b8f-8991-5e1bb33f5f5a.png)

**Comment by GaryAustin1** [comment]
An empty array is almost always you have RLS and no policy or don't meet policy or a bad filter.  You don't have a filter so check your RLS settings.

**Comment by Bigmancozmo** [comment]
How do I check my RLS settings?

**Comment by GaryAustin1** [comment]
![image](https://user-images.githubusercontent.com/54564956/213943096-4adf4a66-c0fa-4cc8-9fa4-1487e9d8bcca.png)

**Comment by Bigmancozmo** [comment]
Thanks!
