### ISSUE TITLE
"url argument is missing" - unable to create new users via both the Supabase UI and client library

### ISSUE THREAD

**Issue by nakulthebuilder** [supabase/supabase#11789]
# Bug report

## Describe the bug

I am using signup with email and password creds and using both the supabase UI (user invite) and the javascript library supabaseClient.auth.signUp({email, password}) I am getting a 500 error url argument is missing. I am guessing this is related to the SITE_URL, which is currently set to a subdomain I am using for development, however I've tried a number of different ways and updated the redirect urls with wildcards and nothing seems to work. I have also tried restarting the Supabase server to no avail. Any guidance would be very much appreciated. Note: It's working fine when using my local supabase db.

Client-side code (serverside on nextjs):

```
const supabasePublicSchemaClient = createClient<Database, "public">(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  {
    global: { fetch: fetch as any },
  }
  const {
      data: { user },
      error,
    } = await supabasePublicSchemaClient.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${process.env.APP_BASE_URL}`,
      },
    });
);
```
`APP_BASE_URL=https://dev.<domain>`

## Screenshots

SITE_URL setup:
<img width="921" alt="supabase_siteurl" src="https://user-images.githubusercontent.com/26181282/213677097-3d9bd2f2-d7fb-45a4-ad3f-f1d13e644e84.png">

Response when inviting new users from the Supabase UI:

<img width="587" alt="Screenshot 2023-01-19 at 12 20 27" src="https://user-images.githubusercontent.com/26181282/213677369-6efc90df-ed91-4d38-af5f-c683b4c99868.png">

<img width="532" alt="Screenshot 2023-01-19 at 12 20 36" src="https://user-images.githubusercontent.com/26181282/213677467-a853ae7a-ac5f-49e9-94b1-b15be65c629b.png">

**Comment by hf** [comment]
Can you please make sure the SUPABASE_URL environment variable is set?

**Comment by nakulthebuilder** [comment]
Do you mean in the environment where i'm using the client library? It is set as i am getting the 500 error from my project endpoint. Additionally, the problem is occurring when I try to invite users from the Supabase UI itself on app.supabase.com. As shown above call is being made to `api.supabase.io/platform/auth/<my-project-id>/invite` and returning a 500 error

**Comment by GaryAustin1** [comment]
Can you look in the dashboard postgres logs right after the error?
Also do you have an insert trigger functions on auth.users table that might be trying to make an http call (or call a function that does)?
Both conditions here I believe would generate 500 if an insert trigger failed and it or function it called generated that message.

**Comment by GaryAustin1** [comment]
Going to close this is likely insert trigger unless more info is available.  Please feel free to comment if you are still having issues.

**Comment by TheLexoPlexx** [comment]
I solved it: Use the SQL Query in the Dashboard.

List all triggers:
```sql
SELECT  event_object_table AS table_name ,trigger_name         
FROM information_schema.triggers  
GROUP BY table_name, trigger_name 
ORDER BY table_name, trigger_name 
```
and then delete the desired one simply with
```sql
`DROP TRIGGER "<trigger_name>" ON auth."<table_name>";`
```
for me, it was auth.users, which led to the Error mentioned above.
