### ISSUE TITLE
Setting text column value to empty string vs NULL in the Dashboard UI is confusing

### ISSUE THREAD

**Issue by moroshko** [supabase/supabase#11782]
# Bug report

## Describe the bug

I have a table with a nullable text column. After the value is set to some string I'd like to set it back to NULL via the UI.
Trying to double click the cell, and clear the text, results in an empty string. And, there is no explicit option to set it to NULL.
Trying to click the "Update row" arrows icon, and clear the text there, results in NULL. And, there is no option to set it to an empty string, if that's what I wanted it to be.

<img width="811" alt="Screenshot 2023-01-20 at 3 07 01 pm" src="https://user-images.githubusercontent.com/259753/213615853-8c707b82-605e-4a7e-a937-d8596025c718.png">

## Expected behavior

In both editing places, having an explicit "Set to NULL" checkbox would be great!
If the user just clears the text (and the checkbox is unchecked), it should set it to an empty string.

**Comment by imPradhyumn** [comment]
A feature for the same could be added?

**Comment by saltcod** [comment]
We have a SET TO NULL button now on the inline and side panel editors:
![CleanShot 2023-08-28 at 15 37 09@2x](https://github.com/supabase/supabase/assets/105593/6add50c3-cd6e-4890-a3a1-febd6456bc49)
