### ISSUE TITLE
Supabase + Blitz.js does not work when using with the Connection Pooling (pgbouncer)

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#1178]
I am trying to use Supabase with Blitz.js. It works perfectly find if I use the regular PostgresDB (with the port 5432). However, whenever I am trying to switch to the connection pool (port 6543) connection fails.

The only thing I am changing is one line in `.env.local`

`postgres://postgres:XXX@YYY:6543/postgres` (XXX is my password and YYY my db name)

I've also tried:
`postgres://postgres:XXX@YYY:6543/postgres?pgbouncer=true` as Blitz.js documentation suggests.

For the context, I am creating a brand new project in supabase and fresh install of Blitz.js

Let me know if any more info I should provide.

**Comment by edgarasben** [comment]
Error message:
```
Error: Database error: Error querying the database: db error: ERROR: unexpected response from login query
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:270
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:57
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:97
```

**Comment by kiwicopple** [comment]
This one might be worth opening inside the Blitz repo since it's not specific to Supabase. From a wild guess:

> unexpected response from login query
> sql-migration-connector

I think the _migration_ script wants a full connection rather than using pgbouncer. Blitz uses prisma under the hood right? Is there a way to specify a different connection for migrations? It's probably related to this:

https://github.com/prisma/prisma/issues/6485

**Comment by kiwicopple** [comment]
I'll close this for now, but feel free to reopen if it's something we need to change/improve.

**Comment by edgarasben** [comment]
Thank you! You are absolutely right, it works fine when switching to a regular one for a migration and then switching back to pgbouncer for running the project.
