### ISSUE TITLE
Add OR logic

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#118]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

pgrst has [support for OR logic](http://postgrest.org/en/v7.0.0/api.html#horizontal-filtering-rows), it would be good to expose this or document it

`GET /people?or=(age.gte.14,age.lte.18)`

I think in our case we can either: 

1. Add documentation, suggesting that developers add database views
2. Add OR, as a basic text input. For example:

eg: Get female people between the ages 14 and 18:

```
supabase
.from('people')
.select('name')
.eq('gender', 'female')
.or('age.gte.14,age.lte.18')
```

This will get interpreted to:

`GET /people?and=(gender.eq.female,or=(age.gte.14,age.lte.18))`

Changes are required in `postgrest-js` and `supabase-js`. Note that possibly the easiest way to do this is to *always* wrap the filters in `and`, even if there is no `or`. For example, to get all females, we would change our `postgrest-js` library from this:

`GET /people?gender.eq.female`

to this:

`GET /people?and=(gender.eq.female)`

**Comment by soedirgo** [comment]
Related issue: https://github.com/supabase/postgrest-js/issues/44.

[postgrest-rs](https://github.com/supabase/postgrest-rs/blob/8a514e57eec51d9cf2521b0d14340a1ce0a94e81/src/filter.rs#L90-L102) implements this the way your example above works (or/1 & and/1 taking one string), but we might need smarter ways to handle edge cases in the future (e.g. ignore whitespaces except when inside quotes, allow commas when inside quotes).
