### ISSUE TITLE
chore: consolidate and remove unused props

### ISSUE THREAD

**Issue by richardwardza** [supabase/supabase#11805]
# Chore

## Describe the chore

Based off https://github.com/supabase/supabase/issues/11806, this issue is to clean up the components props. 
Remove any unused props and consolidate some of the existing props as per https://github.com/supabase/supabase/issues/11806

## Additional context

Origional comment:
> @MildTomato I was going to remove the unused props from the components but that's a big piece of scope creep to introduce and would lead to a bigger PR.
I'm happy to do this as a new issue though?

Reply:
> yea perhaps do that in a separate one. also, feel free to tidy up types anyway - there are probably a lot of [interface extends](https://github.com/supabase/ui/blob/335d73a79df9c3f4924dbdd8825f05ea7989f1ad/src/components/Input/Input.tsx#L11) that could of been used, and then there are props like `disabled` that shouldn't be below it.

**Comment by MildTomato** [comment]
This is for the UI package

**Comment by KevinBrolly** [comment]
It appears this issue may have become stale, so I am going to close it.

If this is still relevant and should be reopened, please do so.

**Comment by MildTomato** [comment]
Yea it's become redundant now we are migrating the UI components to this [new set](https://github.com/supabase/supabase/tree/master/packages/ui/src/components/shadcn/ui).
