### ISSUE TITLE
bug: validateDOMNesting with Dropdown component and Button child

### ISSUE THREAD

**Issue by Ziinc** [supabase/supabase#11803]
Using the `<Dropdown />` component with a button as per the examples in the docs results in the following console error:
```
console.error
      Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
          at button
          at RenderedButton (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/ui/dist/cjs/components/Button/Button2.js:96:5)
```
seems like the implementation wraps the inner child with a button, so this:

```jsx
<Dropdown {...rest}>
  <Button>...</Button>
</Dropdown>
```
will result in this:
```html
<button>
  <button>...</button>
</button>
```

Not sure if this is expected behaviour, as docs example shows Dropdown wrapping a Button

<img width="645" alt="image" src="https://user-images.githubusercontent.com/22714384/149737771-f596b691-e939-4509-9bb7-ab0f82097ed6.png">

Non-critical bug, just making issue to track.

**Comment by KevinBrolly** [comment]
@Ziinc @MildTomato Trying to cut down on Github Issues, this one is two years old and does not look relevant to me anymore, can we close 🙏 ?

**Comment by MildTomato** [comment]
Yea this is no longer an issue, we have been migrating to new Dropdown component

**Comment by MildTomato** [comment]
in case anyone is wondering what the new one is consumed like...

```
<DropdownMenu>
  <DropdownMenuTrigger asChild>
    <button variant="outline">Open</button>
  </DropdownMenuTrigger>
  <DropdownMenuContent className="w-56" align="center">
    //
  </DropdownMenuContent>
</DropdownMenu>
```
