### ISSUE TITLE
chore: exporting component types

### ISSUE THREAD

**Issue by richardwardza** [supabase/supabase#11806]
# Chore

## Describe the chore

Some of the components in the UI library have their types exported ( eg [Button](https://github.com/supabase/ui/blob/335d73a79df9c3f4924dbdd8825f05ea7989f1ad/src/components/Button/Button.tsx#L7) ) while others do not, eg [Modal](https://github.com/supabase/ui/blob/335d73a79df9c3f4924dbdd8825f05ea7989f1ad/src/components/Modal/Modal.tsx#L13)

I feel it would be helpful to go through all the components and do this update, as well as remove any unused imports at the same time.

Two questions are:
- should it be split into multiple tickets
- which branch should the work happen from? (possibly `alpha`?)

The components in `alpha` are:

- [x] ./components/Accordion/Accordion.tsx
- [x] ./components/Alert/Alert.tsx
- [x] ./components/Auth/Auth.tsx
- [x] ./components/Auth/Icons.tsx
- [x] ./components/Avatar/Avatar.tsx `maybe deprecating - not used anywhere in supabase`
- [x] ./components/Badge/Badge.tsx
- [x] ./components/Breadcrumb/Breadcrumb.tsx `maybe deprecating - not used anywhere in supabase`
- [x] ./components/Button/Button.tsx
- [x] ./components/Card/Card.tsx `deprecating`
- [x] ./components/Checkbox/Checkbox.tsx
- [x] ./components/Collapsible/Collapsible.tsx
- [x] ./components/ContextMenu/ContextMenu.tsx
- [x] ./components/Divider/Divider.tsx `deprecating`
- [x] ./components/Dropdown/Dropdown.tsx
- [x] ./components/Form/examples/AuthForm.tsx
- [x] ./components/Form/Form.tsx
- [x] ./components/Icon/Icon.tsx
- [x] ./components/Icon/IconBase.tsx
- [x] ./components/Icon/IconImportHandler.tsx
- [x] ./components/Image/Image.tsx `deprecating`
- [x] ./components/Input/Input.tsx
- [x] ./components/InputNumber/InputNumber.tsx
- [x] ./components/Listbox/Listbox2.tsx
- [x] ./components/Loading/Loading.tsx
- [x] ./components/Menu/Menu.tsx
- [x] ./components/Modal/Modal.tsx
- [x] ./components/Popover/Popover.tsx
- [x] ./components/Radio/Radio.tsx
- [x] ./components/Select/Select.tsx
- [x] ./components/SidePanel/SidePanel.tsx
- [x] ./components/Space/Space.tsx `deprecating`
- [x] ./components/Tabs/Tabs.tsx
- [x] ./components/ThemeProvider/ThemeProvider.tsx
- [x] ./components/Toast/Toast.tsx `this might need refactoring to use radix toast`
- [x] ./components/Toggle/Toggle.tsx
- [x] ./components/Typography/Link.tsx  `deprecating`
- [x] ./components/Typography/Text.tsx  `deprecating`
- [x] ./components/Typography/Title.tsx  `deprecating`
- [x] ./components/Typography/Typography.tsx  `deprecating`
- [x] ./components/Upload/Upload.tsx  `this was never actually used or finished`

Items with existing `Props` exported:
- Auth/UserContext.tsx
- Auth/Auth.tsx
- Input/Input.tsx
- InputNumber/InputNumber.tsx
- Listbox/Listbox2.tsx
- Typography/Text.tsx

edit - some edits above were authored by @MildTomato

**Comment by MildTomato** [comment]
sorry late reply @agrittiwari 

The auth component is already moved out
https://github.com/supabase/auth-ui

**Comment by MildTomato** [comment]
I'm closing this for now, it's getting outdated.
Feel free to open if you feel strongly about it
