### ISSUE TITLE
Documentation related to all available Database Extensions with examples of each one atleast, to understand them well

### ISSUE THREAD

**Issue by rahul3v** [supabase/supabase#11837]
There are only few things mentioned about Database Extensions. 
So its batter to have  some example(s) related to all available Database Extensions. to understand well enough, when to use them and if so how to !!

**Comment by gefgu** [comment]
Current database extensions page: https://supabase.com/docs/guides/database/extensions (for reference)

**Comment by KevinBrolly** [comment]
Thanks for the suggestion, we have updated the extension page with some more information about the extensions. I am going to close this issue now as it has gone stale. If it should be reopened just let us know.
