### ISSUE TITLE
Delete folder in right-click context menu not working

### ISSUE THREAD

**Issue by handre-dev** [supabase/supabase#11835]
# Bug report

## Describe the bug

When you right click on a folder and try to delete it, the client does nothing.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open a storage bucket
2. Right click on a folder
3. Click delete

## Expected behavior

The folder is deleted

## System information

- OS: Windows 10
- Firefox

**Comment by chandhuDev** [comment]
@joshenlim can we collaborate on this issue , I am fresher and enthusiast about open source . I would like to start my open source journey with supabase like projects . I want to learn things really badly . I would be thankful to learn things from you

**Comment by joshenlim** [comment]
hey there @chandhuDev! sure thing really - this issue should be pretty small and easy to pick up for anyone fresh into the supabase dashboard code base. I'd say try take a stab at this and open a PR + assign me as the reviewer :)

**Comment by handre-dev** [comment]
You may want to edit the style of this menu as well for consistency
![image](https://user-images.githubusercontent.com/96829602/215558038-1ec9ac1c-e959-40bf-a6d4-ad4d7574bff5.png)
