### ISSUE TITLE
Error 422 when resize image during local development

### ISSUE THREAD

**Issue by ozum** [supabase/supabase#11860]
# Bug report

## Describe the bug

I'm assuming image resizing is available for local development.

I get the following error when I try to resize the image during local development. However standard images are shown as expected. 

**Works as expected:** `http://localhost:54321/storage/v1/object/public/menu-images/public/avatar1.jpg`

**Returns 422:** `http://localhost:54321/storage/v1/render/image/public/menu-images/public/avatar1.jpg?width=100&height=100`

```js
{
statusCode: "422",
error: "ImageProcessingError",
message: "Invalid source image"
}
```

## To Reproduce

1. Create bucket `menu-images`
```sql
INSERT INTO storage.buckets (id, name, public) VALUES ('menu-images', 'menu-images', true);
CREATE POLICY "Anyone can view menu images" ON "storage"."objects" FOR SELECT TO authenticated USING ((bucket_id = 'menu-images'));
CREATE POLICY "Anyone can add menu images" ON "storage"."objects" FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'menu-images'));
```
2. Upload a file
```js
const { error } = await supabase.storage.from("menu-images").upload(`public/avatar1.jpg`, fileItem.file);
```

3. Get transformed public URL:
```js
const { data } = supabase.storage.from("menu-images").getPublicUrl("public/avatar1.jpg", {
  transform: {
    width: 100,
    height: 100,
  },
});
```

4. Go to `http://localhost:54321/storage/v1/render/image/public/menu-images/public/avatar1.jpg?width=100&height=100`

## Expected behavior

Get resized image.

## System information

- OS: macOS
- Version of supabase-js: 2.2.2
- Version of Node.js: 19.4.0

**Comment by drewbietron** [comment]
I'm seeing something similar, and it seems to be happening with images over a certain dimension / size.  I can confirm that the asset is saved to storage, but hitting the URL returns 
```json
{"statusCode":"422","error":"ImageProcessingError","message":"Invalid source image"}
```

Removing the transformation params shows the image fine, so not sure what is invalid with the source image.  I am saving images via an ArrayBuffer from base64.

I'm also noticing that images ~> 2mb are shown as being saved as `text/plain;charset=UTF-8` in the Studio UI while images ~< 2mb are being shown as saved as `application/octet-stream` -- same code saving the same images to Storage, both rendering fine without the image transformation params.

**Comment by iamchubko** [comment]
Can confirm the same on `"@supabase/supabase-js": "^2.11.0"`

Honestly, I don't quite understand if this isn't working because it's a [paid feature](https://supabase.com/docs/guides/storage/image-transformations) or not and whether this affects local development

**Comment by xlukasfrana** [comment]
Any progress on this? The error is still there for me. Only some images does not work. Not sure if its because of their size, dimensions or encoding.

```
OS: macOS
Version of supabase-js: 2.36.0
Version of Node.js: 20.7
```

**Comment by KevinBrolly** [comment]
It has been some time since this issue was first reported, is it only affecting images over a certain size?

Is this issue only happening during local development/self hosting, but is fine on the hosted platform?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity, but feel free to reopen if you’re still having issues here.

**Comment by FantixX** [comment]
got the same issue today with a "large" file (5408x3605, 1.8MB jpeg)

**Comment by Bazeloth** [comment]
Kinda reopen this. Im having this issue too. @Hallidayo

**Comment by luishugoooo** [comment]
upgrading to the latest imageproxy container fixes this btw

**Comment by Bazeloth** [comment]
> upgrading to the latest imageproxy container fixes this btw

I've been reading and i found this:
- https://supabase.com/docs/guides/storage/serving/image-transformations#limits

Right now i'm only allowing uploads of max 2500px (width or height) as stated in the mentioned links, but i'd like to be able to create thumbnails for each upload. What imageproxy container are you talking about? What did you update?

**Comment by luishugoooo** [comment]
> > upgrading to the latest imageproxy container fixes this btw
> 
> I've been reading and i found this:
> 
>     * https://supabase.com/docs/guides/storage/serving/image-transformations#limits
> 
> 
> Right now i'm only allowing uploads of max 2500px (width or height) as stated in the mentioned links, but i'd like to be able to create thumbnails for each upload. What imageproxy container are you talking about? What did you update?

I am self-hosting using docker-compose and I changed the imgproxy docker image version to 'ghcr.io/imgproxy/imgproxy:v3.28.0'. Now my self hosting instance does 5000px images without issues, I don't really know the limit.

I don't know if this works for local dev environment

**Comment by harshsimplifygenai** [comment]
Any solution?
