### ISSUE TITLE
Update User - invalid JWT: unable to parse or verify signature

### ISSUE THREAD

**Issue by sommye-ctr** [supabase/supabase#11873]
# Bug report

## Describe the bug

When calling the update user endpoint, it results in following response
`
{
    "code": 401,
    "msg": "invalid JWT: unable to parse or verify signature, invalid character '(' looking for beginning of object key string"
}
`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Call the endpoint `https://<project-ref>.supabase.co/auth/v1/user`
2. Pass user access token and anon-key
3. Pass data to be updated 

This is the relevant code snippet
```js
const result = await fetch(
      "https://<project-ref>.supabase.co/auth/v1/user", {
      method: "POST",
      body: {
        "password": password,
      },
      headers: {
        "Content-Type": "application/json",
        "apikey": <anon-key>,
        "Authorization": "Bearer " + token
      }
    }
```

**Comment by GaryAustin1** [comment]
Did you resolve this?  Seems like your anon_key or token are invalid. 
Is anon-key in quotes?  Is the user token expired?

You could check token and anon_key here https://jwt.io/ To insure they are correct.

To change the password you also have to have just signed in, but not sure the error would be the one you get.

**Comment by GaryAustin1** [comment]
Closing this for now.  If the suggestions did not work please comment or maybe ask for help in the discussions or in Discord.  This call works in general.
