### ISSUE TITLE
Valid Deno code causes TS errors when deployed to edge function

### ISSUE THREAD

**Issue by renodesu** [supabase/supabase#11880]
# Bug report

## Describe the bug

Deploying a fully functioning Deno app (with certain imports) to Supabase Edge Functions (local dev) causes ~80 TypeScript errors.
- This does NOT happen when running locally (manual `deno run ...`)
- This happens ONLY when served in Edge Function

When running the script locally with Deno, this does NOT happen. Tested with Deno versions 1.29.4 (latest), and 1.28.0 (the one Edge Functions use).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/renodesu/supabase-edge-function-deno-error-demo (or minimally replicate a local supabase env - the relevant part is the import of `graphgl-yoga` at https://github.com/renodesu/supabase-edge-function-deno-error-demo/blob/main/supabase/functions/error-test/index.ts#L6)
2. Run `npm install` to install deps
3. Verify the code works when running locally with Deno: `deno run supabase/functions/error-test/index.ts` (`Hello from Functions!` is printed)
4. Run `npx supabase start` to get the local supabase up
5. Run `npx supabase functions serve error-test`
6. Observe multiple TS errors on conflicting types
7. Bonus: Comment out the import to verify the import is the source.

## Expected behavior

Valid code should work without errors as expeted.

This seems to only an issue when running in an Edge Function. All `graphql-yoga` examples work out of the box on plain Deno, which leads me to think this is most likely a supabase/Edge Function issue, since the types are not conflicting when running locally.

## Screenshots

No screenshots.

## System information

- OS: Win11, WSL2
- supabase CLI: 1.34.5

**Comment by KevinBrolly** [comment]
Hey @renodesu Could you confirm if you are still having this issue? In the time that has passed since now we have made many changes to the edge runtime and it is likely that this issue is no longer relevant.

I will close the issue as stale, however if you are still seeing problems please do let us know and we will reopen the issue and investigate.
