### ISSUE TITLE
Supabase storage local development error trying to connect: tcp connect error: Cannot assign requested address (os error 99)

### ISSUE THREAD

**Issue by crushingCodes** [supabase/supabase#11905]
# Bug report

## Describe the bug
After updating supabase cli I get the following when trying to upload an image to the supabase storage via a supabase edge function. This used to work without any issue with an older cli version, its the only thing that I can think of that has changed. I am trying to run this as my local development environment.

```sh
TypeError: error sending request for url (http://localhost:54321/storage/v1/object/my-bucket/262c2575-531a-4277-b292-dcdb06435151_p-0.jpeg): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    at async mainFetch (deno:ext/fetch/26_fetch.js:247:14)
    at async fetch (deno:ext/fetch/26_fetch.js:464:9)
```

Any help much appreciated

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```sh
supabase -v
1.34.5

supabase start
```

Create the bucket my-bucket in the dashboard.

I have tried with 2 versions of supabase js client, both with the same error.
```ts
import {createClient} from "https://esm.sh/@supabase/supabase-js@^2.4.1";

const supabase = createClient(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY
)
const image_url = 'some aws s3 url'
const imageData = await (await fetch(image_url)).arrayBuffer();

const {data: storageData, error: storageError} =
    await supabase.storage
        .from('my-bucket')
        .upload(`${card_id}_p-${position}.jpeg`, imageData)
```

Then I get the error

## Expected behavior

No error and image uploaded to bucket.

## System information

- OS: [e.g. macOS, Windows]
macOS
- Version of supabase-js: [e.g. 6.0.2]
2.4.1

- Supabase cli
1.34.5

- Version of Node.js: [e.g. 10.10.0]
Deno

## Additional context

```sh
supabase status
supabase local development setup is running.

         API URL: http://localhost:54321
          DB URL: postgresql://postgres:postgres@localhost:54322/postgres
      Studio URL: http://localhost:54323
    Inbucket URL: http://localhost:54324
      JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
        anon key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

```

**Comment by crushingCodes** [comment]
I will have a go at downgrading the supabase cli to see if the issue goes away and report back

**Comment by crushingCodes** [comment]
I worked it out, I was using a custom url for supabase, but the new version works by just using the env variables passed into deno function
```
        SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? ''
        SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '']
```

**Comment by famu1hundred** [comment]
I am having the same issue. I tried using 

`import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.20.0';`

and I still get the error:
```
FetchError: error sending request for url (http://localhost:54321/rest/v1/account?select=*): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
```

Any ideas?
@crushingCodes  what version did you end up going with?
