### ISSUE TITLE
After updating project to Postgres 15 pgsodium TCE views are not being created as expected

### ISSUE THREAD

**Issue by nfcampos** [supabase/supabase#11902]
# Bug report

## Describe the bug

After updating project to Postgres 15 pgsodium TCE views are not being created as expected

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Take an existing Postgres 14 project with a table using TCE
2. Change config to postgres 15
3. Restart the project
4. Try to use the view in pgsodium_masks, it doesn't exist

## Expected behavior

The view should be created as per the pgsodium docs

**Comment by encima** [comment]
@nfcampos is this issue still impacting you? If yes, can you please ensure your project is running the latest version.

As PG14 is no longer deployed (PG15 is the default), I will close this.

Please do comment if this still occurs and I can reopen.
