### ISSUE TITLE
url and headers props are protected on Storage

### ISSUE THREAD

**Issue by kennethacohen** [supabase/supabase#1191]
# Bug report
I get an error when trying to access protected props on the storage object (`url` and `headers`)

## Describe the bug
I'm trying to do server-side file uploads (via this comment https://github.com/supabase/supabase/discussions/1002#discussioncomment-560098), and seeing the error above when accessing these props.

## To Reproduce
```ts
import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_API_KEY,
)

// this shows an error
console.log(supabase.storage.url)

export default supabase
```

## Screenshots
![image](https://user-images.githubusercontent.com/2354611/115153315-e7a79900-a03a-11eb-9ef2-55034818dcba.png)

## System information
- Version of supabase-js: 1.11.6

**Comment by inian** [comment]
Hey @kennethacohen, you can the storage url is `https://xxx.supabase.co/storage/v1`. So you can do something like this
```
const storageEndpoint = `${process.env.SUPABASE_URL}/storage/v1`
```

**Comment by inian** [comment]
Hi @kennethacohen, I believe the above suggestion should fix your issue. Please reopen if this doesn't solve your problem.
