### ISSUE TITLE
`varchar` no longer selectable when creating or updating a column

### ISSUE THREAD

**Issue by cindrmon** [supabase/supabase#11910]
# Bug report

## Describe the bug

`varchar` cannot be selected in the dropdown when creating a new column in the Table Editor. If editing an existing table with `varchar` as the set type, it doesn't show `varchar` at all.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database > Tables > New table
2. Create a new column with `Add column`
3. Click on the Type dropdown
4. `varchar` cannot be found in the dropdown menu.

## Expected behavior

`varchar` should be selectable in the dropdown menu when creating tables, or at least visible when editing an existing table.

## Screenshots

![varchar is not listed alongside `text` and `uuid`](https://user-images.githubusercontent.com/37018771/214557074-a682ba4b-e185-4a14-a355-281cd195b207.png)

![there is no data type for `varchar` when updating column](https://user-images.githubusercontent.com/37018771/214557228-8d9e0953-9d45-4d70-8b13-1e4f3487c197.png)

## System information

- OS: Windows 11
- Browser (if applies): Firefox

## Additional context

This issue is only applicable for supabase cloud and the supabase dashboard.

**Comment by Hallidayo** [comment]
Hi @cindrmon - Looks like `varchar` was removed recently in [this](https://github.com/supabase/supabase/pull/11294) pull request.

**Comment by actenys** [comment]
Hi @cindrmon - A work around is to use the sql editor to add or alter table with a varchar column

**Comment by cindrmon** [comment]
> Hi @cindrmon - A work around is to use the sql editor to add or alter table with a varchar column

i see. i'll just do that thanks.

i still don't understand why they remove `varchar`.

**Comment by jpbulbulian** [comment]
The varchar type is a SQL standard from the early days, any beginner learn it in the first class at college or in any tutorial. IMHO it has no sense to remove it from the dashboard.

**Comment by kiwicopple** [comment]
this was fixed in this commit: https://github.com/supabase/supabase/pull/12121/files

Thanks for the feedback @cindrmon !
