### ISSUE TITLE
app.supabase.io: "TableName"has no attribute "TableName"

### ISSUE THREAD

**Issue by Polyterative** [supabase/supabase#1196]
# Bug report

## Describe the bug

I can't edit my table from the UI.

## To Reproduce
See video.

Not really sure if it's something about my particular tables that is wrong. 
I haven't done any fancy SQL stuff in this one.

## Expected behavior
Should work 
## Screenshots

https://user-images.githubusercontent.com/16295552/115215415-c494ec00-a103-11eb-9457-52fc53eff26c.mp4

## System information

- OS: Windows
- Browser chrome

## Additional context

I can provide my account info if needed. Contact me vlady.y@live.it

**Comment by kiwicopple** [comment]
Can you please send through your project ref (in the URL) to beta@supabase.io?

**Comment by Polyterative** [comment]
Sent

**Comment by steve-chavez** [comment]
This one is related to a before update trigger that referenced the a non-existent column(that had the same TableName).

```sql
EXECUTE FUNCTION moddatetime('manufacturers')
```

@Polyterative Dropping and correcting the trigger should fix the issue.

(I've sent an email with a snippet)

**Comment by Polyterative** [comment]
I was able to delete the trigger following your input.
I must have created it while doing some tests.

I am very sorry to have wasted your time by reporting a bug even if I couldn't really  understand that it was related to the trigger. unfortunately my experience with postgres is relatively limited

Thank you so much for solving the issue.
I hope this issue wasn't entirely a waste of time for you but it is somehow useful to improve the service.

**Comment by steve-chavez** [comment]
@Polyterative No worries! It's definitely useful to know that `moddatetime` can cause these kind of errors.

Glad to help :slightly_smiling_face:
