### ISSUE TITLE
supabase-image-loader docs are incorrect

### ISSUE THREAD

**Issue by rtman** [supabase/supabase#11960]
# Improve documentation

## Link 

https://supabase.com/docs/guides/storage/image-transformations

## Describe the problem

Docs recommend this function for supabase-image-loader:

```
const projectId = '' // your supabase project id

export default function supabaseLoader({ src, width, height, quality }) {
  return `https://${projectId}.supabase.co/storage/v1/render/image/public/${src}?width=${width}&height=${
    height || 0
  }&quality=${quality || 75}`
}
```

However according to nextjs docs, loaders only take src, width and quality as props.

https://nextjs.org/docs/api-reference/next/image#loader

```
A loader is a function returning a URL string for the image, given the following parameters:

src
width
quality
```

## Describe the improvement

Modify the docs to show the correct loader to use.

```
const projectId = '' // your supabase project id

export default function supabaseLoader({ src, width, quality }) {
  return `https://${projectId}.supabase.co/storage/v1/render/image/public/${src}?width=${width}&quality=${quality || 75}`
}
```

## Additional context

The height was always undefined if you used the loader suggested.

**Comment by alexandregiordanelli** [comment]
https://github.com/supabase/supabase/issues/11981
