### ISSUE TITLE
Supabase thinks uuid column is a bigint column

### ISSUE THREAD

**Issue by omarcodes98** [supabase/supabase#11969]
# Bug report

I have a column in the gigs table called chosen_id that has a foreign key relation to the id column on my profiles table. The column is a uuid and so when querying the database for gigs with a certain uuid in the chosen_id column it should return the data. The bug is that it only works 20% of the time and the other 80% is sends an error message that says {code: '22P02', details: null, hint: null, message: 'invalid input syntax for type bigint: "b0ffot1f-4b03-46da-815f-335945bd324b"'}. The column being queried is definitely a uuid so I'm not sure why this error would occur.

This the query:

 try {
            let { data: userBookedGigs, error } = await supabase
                .from("gigs")
                .select("*")
                .eq("chosen_id", user.id)
}

The user.id is the uuid in the error message.

This should return the rows in the gigs table where the chosen_id is the uuid shown but that only works on a fraction of attempts.

**Comment by GaryAustin1** [comment]
You may need to restart your database in settings.

Sounds like this bug, but the random part seems strange, so could be something else.
https://github.com/supabase/supabase/issues/11714

**Comment by alexandregiordanelli** [comment]
https://github.com/supabase/supabase/issues/11981

**Comment by alexandregiordanelli** [comment]
you need to be careful in use this service, mainly in production, cause the free tier is not enough to scale and if you put your credit card, you cant remove after that, there is no option.. and you cant downgrade/cancel their services..

**Comment by steve-chavez** [comment]
Closing as this was solved on https://github.com/supabase/supabase/issues/11714
