### ISSUE TITLE
bug when trying to downgrade 

### ISSUE THREAD

**Issue by alexandregiordanelli** [supabase/supabase#11981]
<img width="1031" alt="Captura de Tela 2023-01-27 às 14 17 41" src="https://user-images.githubusercontent.com/1518223/215151961-60f9d3ce-f15a-4cec-ac79-d2824ae4be1c.png">

<img width="1385" alt="Captura de Tela 2023-01-27 às 14 15 34" src="https://user-images.githubusercontent.com/1518223/215152027-3a6fdc8e-a025-4f75-be64-ff2c8951ffe4.png">

IM TRYING TO CANCEL IT FOR MONTHS..!!! PLEASE HELP ME!!!

**Comment by alexandregiordanelli** [comment]
it is not a scalable product, it lives out of air, if you have a minimum traction, your site will be down and to make matters worse they say that you need a heavy machine and even then your system crashes again, I had less than 250,000 users and I gave up on the project because of how bad the support was. Now after taking a lot of money from venture capital, they want to pay this millionaire account with my credit card that I can't get out of this crap on this site.

**Comment by kiwicopple** [comment]
Hey @alexandregiordanelli - don't worry, we're make sure you're refunded if there are any incorrect charges.

But please - don't spam our github with links to this issue. 

Can you please reach out to support here: [app.supabase.com/support/new](https://app.supabase.com/support/new). We'll help you to cancel your project, and we'll fix any bugs along the way with your help to figure out why it's happening. We're humans, and we make mistakes. It's nothing malicious, and we're always happy to rectify our mistakes with suitable compensation.

**Comment by alexandregiordanelli** [comment]
<img width="939" alt="Captura de Tela 2023-01-27 às 15 25 37" src="https://user-images.githubusercontent.com/1518223/215165273-3d0e85e1-a233-45be-8bc9-4820f96c49fc.png">

Supabase refused to chargeback!! The bank is saying: 
We saw in the documentation sent that the establishment refused to make the reversal.

It is not possible to cancel my account, and no one answers me by email!!

**Comment by alexandregiordanelli** [comment]
THERE IS NO OPTION TO REMOVE YOUR CREDIT CARD!!! DONT PUT IT ON IN THIS WEBSITE!!!

**Comment by awalias** [comment]
Hey Alex, as @kiwicopple mentioned please **don't worry**, we will make sure you're refunded any incorrect charges. We need some time to investigate exactly what happened. Please be patient.

**Comment by alexandregiordanelli** [comment]
<img width="1023" alt="Captura de Tela 2023-01-27 às 16 04 19" src="https://user-images.githubusercontent.com/1518223/215172950-088d219f-889e-4e11-ad77-27ea5f1af9c5.png">

Are you investigating? Send the link that Im saying it has problems for months.. Months ago I did the same and I THOUGHT it was canceled.. for my surprise, and checking my bills.. WTF..

**Comment by alexandregiordanelli** [comment]
![WhatsApp Image 2023-01-27 at 16 06 38 (1)](https://user-images.githubusercontent.com/1518223/215173884-01d5fa24-1f86-4f25-b276-6148c44d4e6e.jpeg)
![WhatsApp Image 2023-01-27 at 16 06 38](https://user-images.githubusercontent.com/1518223/215173887-11bef68f-cb5e-4089-ae84-42752c2002ed.jpeg)

**Comment by alexandregiordanelli** [comment]
https://youtu.be/UuSYL0rMx-8

**Comment by alexandregiordanelli** [comment]
<img width="1006" alt="Captura de Tela 2023-01-27 às 16 13 42" src="https://user-images.githubusercontent.com/1518223/215175901-87194c26-ea2c-4eed-9d48-d93d501e00a9.png">

I sent the bug, I recorded this bug, and I need to explain in 3 channels the same fucking problem, and my money was not refunded it.. 

It is a huge bug.. !!

**Comment by alexandregiordanelli** [comment]
I WAS BLOCKED IN DISCORD FOR THEM CAUSE I WAS JUST TALKING ABOUT MY PROBLEM!!

**Comment by GaryAustin1** [comment]
> I WAS BLOCKED IN DISCORD FOR THEM CAUSE I WAS JUST TALKING ABOUT MY PROBLEM!!
I see nothing indicated you have been banned in Discord.  You spammed a bunch of threads with the exact same message which is against terms and all but your original post were removed.  You posted a second time with different info and that is still there.
You then used extremely foul language and threatened a moderator (who are not employees, not that it makes it right) with a graphic physical attack and the system automatically removed that post.   This likely will get you banned, but the moderators have not discussed it yet.

**Comment by kiwicopple** [comment]
Because this was raised publicly, we are going to respond publicly as well now

> Hi Alexandre,
> 
> Thank you for reaching out to our support team and I am glad we have been able to resolve this issue for you.
>
> Anytime a bug or billing issue occurs the best way to achieve a speedy and satisfactory outcome is to contact our [support team]([app.supabase.com/support/new](http://app.supabase.com/support/new)) who will be able to advise.
>
> Your account had been running for several months with failed payments. Recent improvements to our billing processes meant we have been more active in contacting users who had persistent failed payments.
>
> At the time of contacting yourself there was a bug which caused users with certain PAYG configurations to be unable to successfully downgrade, which has now been fixed and we are grateful to you for highlighting this to us.
>
> We have voided the last 5 months of unclaimed payments and additionally in a gesture of goodwill refunded your previous Pro usage.
> In future we would encourage you to reach out to our [support team]([app.supabase.com/support/new](http://app.supabase.com/support/new)) directly if you have any issue with billing or the platform more generally.
