### ISSUE TITLE
Get Url in Storage doesn't work in Safari

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#11983]
# Bug report

## Describe the bug

In Storage, copy url to clipboard doesn't work in Safari

To reproduce:
— open Storage
— add a bucket
— add an item to the bucket 
— click the item to expand its panel
— Click get url then one of the options
— doesn't get copied to the clipboard

![CleanShot 2023-01-27 at 14 41 19@2x](https://user-images.githubusercontent.com/105593/215162747-72294333-61f6-4016-9059-e7e3df82eee7.png)

**Comment by alexandregiordanelli** [comment]
you need to be careful in use this service, mainly in production, cause the free tier is not enough to scale and if you put your credit card, you cant remove after that, there is no option.. and you cant downgrade/cancel their services..

**Comment by Gautam-Arora24** [comment]
Wanted to work on this issue.

**Comment by Isaiah-Hamilton** [comment]
I can't seem to reproduce. Which OS version and safari version are you running?

**Comment by BikashSah999** [comment]
The root issue is that safari doesn't allow write to clipboard async, it should be called in user event (click) handler sync.
There are some NPM packages for it, normally they just create a temp element with copy needed text and trigger event to copy. I think we can use [https://www.npmjs.com/package/copy-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard). What's your opinion on it?

**Comment by raph941** [comment]
@Isaiah-Hamilton,
I think you can reproduce this issue on Safari `v14.x`, it seam to work fine on Safari `v16.x` though.

**Comment by saltcod** [comment]
I'm still seeing this bug in Safari 16.3 (18614.4.6.1.5).

**Comment by raph941** [comment]
Ah okay, I tested on Safari `v16.1` and `v14`.

**Comment by raph941** [comment]
Hi @saltcod Any thoughts [on this comment](https://github.com/supabase/supabase/issues/11983#issuecomment-1413136959) for resolving this issue?

**Comment by speedtreammanga** [comment]
I'm having this bug.

Chip `Apple M1 MAX`
OS `Sonoma 14.1.1`
Safari `17.1`

**Comment by codingiswhyicry** [comment]
A bug I just found too, on Safari 16.5.

**Comment by kutovoy** [comment]
i have same issue in both Safari [Version 17.1 (19616.2.9.11.7)] and in Chrome [120.0.6099.71 (Official Build) (x86_64)] on Mac OS X [14.1.1]. Clicking on "Get URL" makes 4 API calls but nothing is copied to the clipboard.

**Comment by kutovoy** [comment]
I just downloaded and tested supabase v0.24.03 (I deleted containers and recreated them) and I still have same problem as I described in the previous post
