### ISSUE TITLE
[UI] sql editor syntax highlighting fail

### ISSUE THREAD

**Issue by stuartcrobinson** [supabase/supabase#11996]
would be nice if this could just be disabled for now, it's pretty distracting as is for me

<img width="243" alt="image" src="https://user-images.githubusercontent.com/12928716/215237753-8db22193-c8e2-4317-b94d-2ae564bed309.png">

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/12928716/215237815-dfbac5c9-a083-434e-8cc5-f6aed2053730.png">

**Comment by Hallidayo** [comment]
Hi @stuartcrobinson - Have you got steps to recreate this (Could you send over an example query)? I've tried to recreate on my end but I have not been able to.

**Comment by ruggi99** [comment]
I also experience the same problem.
Syntax highlighting is broken and it is shifted randomly by x lines down.
Will investigate if have some time.
I have not found any reproducible steps so far

**Comment by GaryAustin1** [comment]
Basically if you highlight some text that exists in other spots it attempts to show you the same text in other spots... But it is all one line below the actual text...

Here I dragged my cursor over a `u` character...
![image](https://user-images.githubusercontent.com/54564956/217381281-8d980f53-8b90-4514-bd20-b228271ada08.png)

**Comment by ruggi99** [comment]
![image](https://user-images.githubusercontent.com/25064808/217460747-0023402f-afc4-4dec-9096-8094b0bc3def.png)

For me is not one line but 3 this time (the fifth line is selected).
Other times may be more or less. It's random
