### ISSUE TITLE
flutter Supabase magic link/redirect link not working on emulator

### ISSUE THREAD

**Issue by swaxolez** [supabase/supabase#11995]
### Discussed in https://github.com/supabase/supabase/discussions/9870

<div type='discussions-op-text'>

<sup>Originally posted by **ujaiahmad** October 26, 2022</sup>
Hi,

I'm trying to follow the [flutter quickstart](https://supabase.com/docs/guides/with-flutter) example. Everything seems to be working fine for the authentication when I run it on a browser like Chrome or Edge. But when I run it on an android emulator, it runs fine until I click on the magic link from my email. It won't redirect to the application in the emulator. I also tried this on my device but still the same problem. 
<img src=https://user-images.githubusercontent.com/25504609/198094323-86efa4cd-a811-4293-b4bc-bd5f4f0d1919.jpg width=350 height=600/>
<img src="https://user-images.githubusercontent.com/25504609/198094338-571c9c57-4a28-4d63-8ff6-3c6d7e015a5e.jpg" width=350 height=600/>
Anyone can help me please, thanks. 
</div>

I'm having the same problem.  Tried the accepted answer but it's not working.  Web app works fine with localhost redirect but using io.supabase.flutterquickstart://login-callback/ is not working?

**Comment by swaxolez** [comment]
Ok this seems to be an issue solely with the emulator.  iPhone is fine and so is web app.

**Comment by dshukertjr** [comment]
Hi @swaxolez ,

Sorry for the late response here.

If it's not working just on Android, it might be a Android configuration issue. [Here](https://github.com/supabase/supabase/blob/master/examples/user-management/flutter-user-management/android/app/src/main/AndroidManifest.xml#L33) is a sample of what the AndroidManifest.xml file could look like, but would you be able to check if you have the configuration correctly on your app? If possible, would you be able to share your AndroidManifest.xml file?

**Comment by Chin-ma** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="user_manage"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that begin with YOUR_SCHEME://YOUR_HOST -->
                <data
                    android:scheme="io.supabase.usrmng"
                    android:host="login-callback" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by dshukertjr** [comment]
@Chin-ma With this manifest file, how are you calling `signInWithOtp()` method? If you could share the code, that would be great. 
Also, have you added the deep link in your Supabase dashboard? If you could share a screenshot of the `auth > RedirectURLs` of the dashboard, that would be great. Remember, what you have in the dashboard has to match what you pass to the `redirectTo` parameter of  `signInWithOtp`  exactly. No extra spaces, no extra slashes are allowed.

**Comment by Chin-ma** [comment]
```
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:user_manage/main.dart';

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});

  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  bool _isLoading = false;
  bool _redirecting = false;
  late final TextEditingController _emailController = TextEditingController();
  late final StreamSubscription<AuthState> _authStateSubscription;

  Future<void> _signIn() async {
    try {
      setState(() {
        _isLoading = true;
      });
      await supabase.auth.signInWithOtp(
        email: _emailController.text.trim(),
        emailRedirectTo:
            kIsWeb ? null : 'io.supabase.usrmng://login-callback/',
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Check your email for a login link!')),
        );
        _emailController.clear();
      }
    } on AuthException catch (error) {
      SnackBar(
        content: Text(error.message),
        backgroundColor: Theme.of(context).colorScheme.error,
      );
    } catch (error) {
      SnackBar(
        content: const Text('Unexpected error occurred'),
        backgroundColor: Theme.of(context).colorScheme.error,
      );
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  void initState() {
    _authStateSubscription = supabase.auth.onAuthStateChange.listen((data) {
      if (_redirecting) return;
      final session = data.session;
      if (session != null) {
        _redirecting = true;
        Navigator.of(context).pushReplacementNamed('/account');
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    _authStateSubscription.cancel();
    _emailController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Sign In')),
      body: ListView(
        padding: const EdgeInsets.symmetric(vertical: 18, horizontal: 12),
        children: [
          const Text('Sign in via the magic link with your email below'),
          const SizedBox(height: 18),
          TextFormField(
            controller: _emailController,
            decoration: const InputDecoration(labelText: 'Email'),
          ),
          const SizedBox(height: 18),
          ElevatedButton(
            onPressed: _isLoading ? null : _signIn,
            child: Text(_isLoading ? 'Loading' : 'Send Magic Link'),
          ),
        ],
      ),
    );
  }
}
```
![image](https://github.com/supabase/supabase/assets/50634176/910a55dc-6600-4895-88b1-dbdf002a29d9)

**Comment by dshukertjr** [comment]
@Chin-ma 
In your code you are redirecting to `io.supabase.usrmng://login-callback/`, but you have `io.supabase.usrmng://login-callback` in your Supabase dashboard. Again, they have to be the exact match for the redirect to work.  A slash at the end counts as a difference.

**Comment by Chin-ma** [comment]
@dshukertjr Yeah this worked thanks for your kind support, but when i did it according to tutorial they added a forward slash to the link.

**Comment by dshukertjr** [comment]
@Chin-ma You're right! Thanks for letting me know! Will fix the tutorial right now!

**Comment by FelixOz13** [comment]
I'm having this exact same problem with iOS simulator, , I tried adding and removing the forward slash on both my code and the dashboards and it redirects to the browser instead of the simulator, anybody have any different solutions?

**Comment by dshukertjr** [comment]
@FelixOz13 The key is to match the `redirectTo` string and what yo have in your Supabase dashboard match exactly. What do you have in your Flutter code, and what do you have in the Supabase dashboard?

**Comment by FelixOz13** [comment]
Nevermind I was verifying my email from my macbook email and expecting to clear on the simulator,  it's not until I opened my email from my simulator however I still get the parse JSON error I try to remove .single() but no solution yet, if you have a link to that solution it would be appreciated!

**Comment by wojciechowskip** [comment]
Same problem I have :(

  Future<void> sendPasswordResetEmail({required String email}) async {
    return _authClient.resetPasswordForEmail(email,
        redirectTo: 'io.supabase.myprojecto.link://reset-password/');
  }
  
  in redirect urls:
  io.supabase.myprojecto.link://reset-password/
  
  in reset password email template:
 
 <h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .RedirectTo }}">Reset Password</a></p>

and in android manifest:
<data
                    android:host="reset-password"
                    android:scheme="io.supabase.myprojecto.link" />
                    
and nothing...
app is not opened on emulator neither on real device. Any help?

**Comment by dshukertjr** [comment]
@wojciechowskip 
`href="{{ .RedirectTo }}"` doesn't work. Take a look at the following example, which is the default template for every Supabase project.

```html
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}">Reset Password</a></p>
```
