### ISSUE TITLE
Storage: Error moving file into folder causes error "body should have required property 'bucketName'"

### ISSUE THREAD

**Issue by solvemon-vh** [supabase/supabase#1199]
# Bug report

## Describe the bug

When moving a file into an existing folder, I am presented with the error "body should have required property 'bucketName'". If the folder is empty, this is deleted.

## To Reproduce

1. Go to storage, and create a new bucket 'testbucket'
2. create a new folder 'testdir
3. upload a file to the root of testbucket
![image](https://user-images.githubusercontent.com/78966842/115242829-8e1a9980-a122-11eb-864f-96780ac73dd4.png)

4. in the context menu of the uploaded file, select 'move'
5. type in 'testdir/' as the destination
![image](https://user-images.githubusercontent.com/78966842/115243039-c4581900-a122-11eb-82ad-93f2ac5c64ad.png)

## Expected behavior

The file should be moved from the root to the directory 'testdir'

## Screenshots

![image](https://user-images.githubusercontent.com/78966842/115243223-fe291f80-a122-11eb-8e0d-498a1e9d158f.png)

## System information

- Browser: Vivaldi 3.7.2218.55 (64-bit)
- Using managed / web based bucket interface

## Additional context

Browser dev-tools request POST:

```json
{"bucketId":"testbucket","sourceKey":"test.jpg","destinationKey":"testdir/test.jpg"}
```

response:
```json
{"statusCode":"400","error":"Bad Request","message":"body should have required property 'bucketName'"}
```

After the error message, the new directory I created, `testdir` is gone.

I am assuming (part of) the bug here is the `bucketName` != `bucketId`?

**Comment by inian** [comment]
Hi @solvemon-vh , this bug is fixed and it is rolling out now. Should be fixed in an hour or so.

**Comment by solvemon-vh** [comment]
Thanks for the quick fix @inian , I tested it and it is working now!
