### ISSUE TITLE
Failed to create a Webhook

### ISSUE THREAD

**Issue by jkazimierczak** [supabase/supabase#12008]
# Bug report

## Describe the bug
Creating a Webhook results in the following error:
```
Failed to create hook: failed to create pg.triggers: schema "supabase_functions" does not exist
```
Turning on `PG_NET` for manually created schema `supabase_functions` results in different error:
```
Failed to create hook: failed to create pg.triggers: function supabase_functions.http_request() does not exist
```

The order of operation doesn't matter. Either turning `PG_NET` on first, or "Enabling Webhooks" via the button gives the same results.

## To Reproduce

1. Create new Supabase instance
1. Go to Database > Webhooks
2. Click on "Enable Wehooks", and then "Create Webhook"
3. Fill in the name, select (all) events, select "HTTP Request" and fill the rest accordingly
4. Click "Confirm"
5. See the failure message in top-right corner popup

## Expected behavior

A Webhook is created with all the name, events and actions provided. It should be visible in the Webhooks submenu.

## Screenshots

When trying to submit the Webhook:
```
Failed to create hook: failed to create pg.triggers: schema "supabase_functions" does not exist
```
![image](https://user-images.githubusercontent.com/77862767/215288087-880ba852-ff41-46d5-b512-564187e191ea.png)

After turning `PG_NET` and creating the `supabase_functions` schema, the error changes to:
```
Failed to create hook: failed to create pg.triggers: function supabase_functions.http_request() does not exist
```
![image](https://user-images.githubusercontent.com/77862767/215287966-e586d588-731c-4bab-95f0-ffeeb39f5fd2.png)

## System information

- OS: Windows 10
- Browser Firefox 109.0

## Additional context
This was done on freshly created instance as well as on a few days old one.

**Comment by GaryAustin1** [comment]
I can confirm this bug on new instances.  One difference is the new instances have pg_net version .7 which I believe was just released a few days ago....
https://github.com/supabase/pg_net/pull/81

**Comment by pcnc** [comment]
Hi @jkazimierczak - we just rolled out a fix targeting this issue, everything should work as expected now.

Could you give it another try?

**Comment by jkazimierczak** [comment]
Just tried it out and I created the Webhook without any problems. Thanks to the Supabase team and to GaryAustin, who put his time to verify this behavior.

**Comment by filippo-brigati** [comment]
Have the same issue while creating webhook in my local enviroment

`Failed to create hook: failed to create pg.triggers: schema "supabase_functions" does not exist`
