### ISSUE TITLE
Storage client lets you create folders using invalid characters as folder name

### ISSUE THREAD

**Issue by handre-dev** [supabase/supabase#12021]
# Bug report
Storage client lets you create folders using invalid characters as folder name, but then gives you an invalid character error when uploading files inside of them

## To Reproduce
1. Using the browser client, create or access a bucket and click on "Create folder".
2. Enter a folder name that contains invalid characters like "à".
3. Access the folder and upload a file via drag-n-drop

## Expected behavior
The client shouldn't let you create folders that have invalid characters in their name

## System information
- OS: Windows
- Browser: Chrome

**Comment by oxenprogrammer** [comment]
Looks like it's a temp folder because when you navigate away the folder won't exist anymore.
