### ISSUE TITLE
The app does not allow to select varchar as column type

### ISSUE THREAD

**Issue by wimvanhouts** [supabase/supabase#12027]
# Bug report

## Describe the bug

When I create a new table at the time of writing in the supabase app, it is no longer possible to create columns of type varchar. Only of type text

## To Reproduce

Go to the supabase UI
Create a new table
Add a new column
Select a type. Varchar is not in the list

## Expected behavior

Varchar should be possible to select. There is a difference on database level between varchar and text

## System information

Cloud app hosted by supabase

**Comment by GaryAustin1** [comment]
If you searched issues you would find this from 4 days ago...
https://github.com/supabase/supabase/issues/11910
