### ISSUE TITLE
`auth users` table not visible in `Edit foreign key relation` until visiting the `auth` schema

### ISSUE THREAD

**Issue by szmarczak** [supabase/supabase#12031]
# Bug report

## Describe the bug

The title says it all.

## To Reproduce

1. If you're already on a supabase project page, refresh.
2. Press `New Column`
3. Press `Add foreign key relation`
4. There's no `auth users` table.
5. Press `Cancel`
6. Switch the schema to `auth` and then back to `public`.
7. Press `New Column`
8. Press `Add foreign key relation`
9. The table now lists `auth users`.

## Expected behavior

![image](https://user-images.githubusercontent.com/36894700/215350301-b10a1ec5-ed8a-46c0-824d-59bdc46bdb46.png)

## Screenshots

![image](https://user-images.githubusercontent.com/36894700/215350275-fbe23310-3848-48e5-9fb1-f369b640f022.png)

## System information

- OS: Supabase free project
- Browser: Chrome 109
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by manish0707** [comment]
+1

**Comment by ruggi99** [comment]
Maybe related: https://github.com/supabase/supabase/pull/12283
