### ISSUE TITLE
Generated API documentation uses wrong filtering syntax

### ISSUE THREAD

**Issue by akselw** [supabase/supabase#1205]
# Bug report

## Describe the bug

In the generated API documentation (at `/project/{id}/api/default?resource={table_name}`), under the heading "SUBSCRIBE TO SPECIFIC ROWS", the following example is shown:

```js
const table_name = supabase
  .from('table_name:column_name.eq.someValue')
  .on('*', payload => {
    console.log('Change received!', payload)
  })
  .subscribe()
```

But according the documentation [here](https://supabase.io/docs/reference/javascript/subscribe#listening-to-row-level-changes) (and actually trying it out), the proper syntax should be:

```js
const table_name = supabase
  .from('table_name:column_name=eq.someValue')
  .on('*', payload => {
    console.log('Change received!', payload)
  })
  .subscribe()
```

With a `=` separating the table name and `eq`, instead of a period.

## System information

- Browser (if applies): Chrome
- Version of supabase-js: @supabase/supabase-js@1.11.6
- Version of Node.js: v12.22.1

**Comment by kiwicopple** [comment]
Thanks for the bug report @akselw - this is now fixed 👍
