### ISSUE TITLE
Self-Hosted SMTP Invite user

### ISSUE THREAD

**Issue by Samsonov0** [supabase/supabase#12075]
# Bug report

## Describe the bug

I getting "Failed to invite user: Error inviting user" if try send invite from self-hosted supabase studio (Docker-compose)

## To Reproduce

1. Up a self-hosted supabase
2. go to Authentication page
3. try invite a new user
4. see a problem

## Screenshots

![image](https://user-images.githubusercontent.com/52374669/215702607-310efc8d-2cf5-4ae7-bbc2-9e0c2ea4d4b9.png)
![image](https://user-images.githubusercontent.com/52374669/215702807-a07537b9-c50e-480b-b7b8-b42a9a908ce5.png)

**Comment by 0xRenshaw** [comment]
Did you manage to resolve this?

**Comment by reutopiaer** [comment]
POST http://localhost:8000/auth/v1/signup 500 (Internal Server Error)

{user: null, session: null} AuthApiError: Error sending confirmation mail
