### ISSUE TITLE
No option for "varchar" when creation column

### ISSUE THREAD

**Issue by dreamid27** [supabase/supabase#12070]
# Bug report

Hi, thanks for your awesome platform, but when i want to create table, i cannot see the option for varchar. it is bug ? because in some column, i have varchar type.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.com/ with your account
2. Click on Table Editor
3. select some table, and click New Column
4. Scroll down, until you see Data Type, and click that
5. **varchar** type doesnt include in option.

## Expected behavior

Varchar is common data type in postgress. so it's should include in option.

## Screenshots
<img width="483" alt="Screen Shot 2023-01-31 at 14 05 58" src="https://user-images.githubusercontent.com/22621375/215690223-83a25daf-746b-4c96-9b68-208410c81cde.png">

## System information

- OS: MACOS
- Browser Chrome

**Comment by oxenprogrammer** [comment]
@dreamid27 Checkout this [comment](https://github.com/supabase/supabase/issues/11910#issuecomment-1403718698) on a related [issue](https://github.com/supabase/supabase/issues/11910#issuecomment-1403718698).

**Comment by kiwicopple** [comment]
this was fixed in this commit: https://github.com/supabase/supabase/pull/12121/files

Thanks for the feedback @dreamid27 !
