### ISSUE TITLE
storage policies not work

### ISSUE THREAD

**Issue by songhn233** [supabase/supabase#12083]
# Bug report

## Describe the bug

I'm curious what the authentication mechanism is for the storage, is the default for private buckets with full permissions turned on for `anon`? 

when I create a policy for the specified bucket:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/47357585/215856474-ce59fb1a-70d2-4782-af46-ddaa336d9997.png">

It doesn't actually work, the client created by `anon_key` in the browser can CRUD at will, and I've tried other policies, including returning false directly for the public role, but none of them have any effect on the anonymous list or upload action.

**Comment by GaryAustin1** [comment]
I did a quick test and cannot access a bucket with select policy set to authorized with the anon_key and no user signed in.

Are you sure you don't have another policy (maybe in the "other policies" section that applies to all buckets?

**Comment by GaryAustin1** [comment]
@songhn233 Do you have anymore info on this?  I was not able to replicate it.

**Comment by GaryAustin1** [comment]
I'm going to close this for lack of follow up as it seems to work and is not an obvious bug.

If you are still having the issue feel free to comment with more info.

**Comment by bitdictator** [comment]
I am experiencing the same issue. I create a new project, created a private bucket named "test", uploaded an image to it, added a select policy for the bucket only for anon and authenticated roles (by using the UI for creating policies), cant access the image from my app or browser, made the bucket public and had access.

**Comment by GaryAustin1** [comment]
@bitdictator Did you ask this somewhere else today?
How are you trying to access the bucket?
Normally you set the select policies and then use createSignedUrl to get a url to access a private bucket?
What URL or storage-api are using to "access" the image?

**Comment by bitdictator** [comment]
@GaryAustin1 I did try to ask [here](https://www.reddit.com/r/Supabase/comments/1dwciu3/rls_not_working_for_anon_role/) and on the discord server. But as you pointed the issue was that I was storing the entire image url in a column in view and was fetching the table from my client and then passed the url to src param of the next/image component. I will try to use createSignedUrl on the private bucket with select rls for anon and authenticated roles and see it it works.
