### ISSUE TITLE
Policy from storage.objects can't access table in public schema

### ISSUE THREAD

**Issue by thisisbintang** [supabase/supabase#12098]
# Bug report

## Describe the bug

I want to create a policy on an object table in the storage schema that requests data from a table in the public schema, but the supabase's storage policy automatically deletes the public schema. So the table data from the public schema is always empty. I hope I can explain the problem well.

## To Reproduce

1. Go to Storage
2. Click policies
3. Create a new policy in one of the buckets
4. Write queries calling data from a table in the public schema
5. The supabase automatically deletes that table schema (public schema)

## Expected behavior

Public schemes remain in the policy

## Screenshots

![Screenshot from 2023-02-01 17-22-09](https://user-images.githubusercontent.com/25783133/216016961-2edd7732-8e60-4c10-b610-231a418868ea.png)
![Screenshot from 2023-02-01 17-22-49](https://user-images.githubusercontent.com/25783133/216016987-332d5622-059e-4762-8d76-d149dd9319f7.png)

## System information

- OS: Linux
- Browser Brave
- Version of supabase-js: ^2.4.0
- Version of Node.js: v19.4.0

**Comment by GaryAustin1** [comment]
I've seen the policy editors tend to "clean up" schema names that by default would be used.  For instance auth.uid() becomes uid() in the cases I've seen.   Are you sure this is not working because of the lack of schema name, or could they just not be needed as they will use public tables by default?

**Comment by GaryAustin1** [comment]
@thisisbintang 
Did you confirm if this is a real issue with the code running, or just the policy editor cleaning up stuff in its display?

**Comment by thisisbintang** [comment]
thank you for replying. I don't think it's a real problem just that the storage policy editor removed the public schema.

**Comment by GaryAustin1** [comment]
I'm going to close the issue as I believe that is the way it is intended to work and it is not causing issues with the policy.

**Comment by NikolaiDokken** [comment]
I am having the same issue. How should one check if the user performing an upload is admin based on whether its uid exists in a table in the public schema?

**Comment by prabhatCH** [comment]
> I am having the same issue. How should one check if the user performing an upload is admin based on whether its uid exists in a table in the public schema?

you can check `auth.uid()` in your list of admins from `public.users` or whereever you have stored admins.

If the Policy editor gives problems then you can directly create a policy in the SQL editor as well like 
```
CREATE POLICY
  "Policy Name" ON storage.objects FOR
SELECT
  TO authenticated USING (
    (bucket_id = 'bucket_name'::text)
    AND (Your query to check auth.uid() in list of public.admins)
```
