### ISSUE TITLE
Be Able to Listen to changes on a particular column

### ISSUE THREAD

**Issue by YohanWadia** [supabase/supabase#12106]
Hi,
I couldnt find it in the docs... and couldnt manage to do it... but I think it would be very efficient to have a listener... that besides listening to a particular record... it can also listen and return only the field(column) you are interested in.
for eg.

```

supabase.from('countries')
  .stream(primaryKey: ['id'])
  .eq('id', '120')
  .listen((List<Map<String, dynamic>> data) {
  // >>>>> and this returns the entire row from the table... that could be even 10 columns long
});
```

but what if I was only interested in seeing the changes in the "population" field.... in that case Im stuck with getting an entire row of details with which i cant do anything... so something like....

```

supabase.from('countries')
.select('population') // <<<<<<this line
  .stream(primaryKey: ['id'])
  .eq('id', '120')
  .listen((List<Map<String, dynamic>> data) {
  // >>>>> and this returns only the field I need to listen to
});
```

will be nice to hear your thoughts on the same
YOhan

**Comment by chasers** [comment]
@YohanWadia I think [this](https://github.com/supabase/realtime/issues/243) is what you're looking for. 

Going to close this for now, please feel free to reopen something in the Realtime repo add a comment for your use case on that issue.
