### ISSUE TITLE
Access realtime tables

### ISSUE THREAD

**Issue by kjell-van-straaten** [supabase/supabase#12129]
# Bug report

## Describe the bug

Hi, For an application I would like to monitor the number of subscriptions on my tables through the realtime.subscription table. However, any attempt so far resulted in the following APIerror: `permission denied for schema realtime`

I already added an endpoint for the realtime schema through the interface. I did not find any option to give access to the schema through queries.
I also tried to give access rights through postgresql commands `GRANT USAGE ON SCHEMA realtime TO postgres, anon, authenticated, service_role, dashboard_user, authenticator, supabase_auth_admin, supabase_admin, ` This did not seem to help.
How to continue?

## To Reproduce

add realtime to exposed schemas in api
fire query to subscription table

## Expected behavior

Query is authorized

## Additional context

Supabase cloud environment

**Comment by GaryAustin1** [comment]
Also answered on Discord...

You should not allow access the realtime schema from the API if that is what you are trying to do.  You could use an rpc security definer function to READ it only.  BUT Supabase schemas can change at anytime (and have).

As far as the client getting to other schemas you need to have a separate client set up with createClient and specify the schema and set up the API setting to allow the schema to have access.  The instructions are normally here: https://supabase.com/docs/reference/javascript/initializing but missing at the moment.

**Comment by kjell-van-straaten** [comment]
RPC security definer worked, thanks!
