### ISSUE TITLE
Style context menu, to be similar to the three dots menu

### ISSUE THREAD

**Issue by raph941** [supabase/supabase#12130]
# Chore

Style context menu, to be similar to the three dots menu in storage and table editor.

## Additional context

This is a follow-up issue from #11835, for unaddressed styling concerns as mentioned in

https://github.com/supabase/supabase/issues/11835#issuecomment-1403224375
https://github.com/supabase/supabase/issues/11835#issuecomment-1409080016

<img width="896" alt="Screenshot 2023-02-02 at 4 37 32 PM" src="https://user-images.githubusercontent.com/45232708/216370341-ff3d4b27-22f3-49e5-a81a-9434538db61b.png">

**Comment by pratik-codes** [comment]
@raph941  you can assign it to me ill pick it up

**Comment by raph941** [comment]
Hi @pratik-codes, thanks for offering. 
I see a PR has already been created for it already: #12131
