### ISSUE TITLE
this should work: `delete from mytable  where (id1, id2) = ANY(Array [(1,3)])`

### ISSUE THREAD

**Issue by stuartcrobinson** [supabase/supabase#12158]
# summary

this command [works w/ postgres](https://dbfiddle.uk/ZeUNdEns) but [not using supabase](https://stackoverflow.com/questions/75341609/batch-delete-rows-matching-multiple-columns-in-postgres-using-an-array)

```
delete from mytable  where (id1, id2) = ANY(Array [(1,3), (1,4)])
```

# steps to reproduce:

- use the online sql and table editor.  local or supabase.com
- make a new table `mytable` with 2 columns, id1 and id2, both int8.  both primary keys
- fill it with some values
- run this `delete from mytable  where (id1, id2) = ANY(Array [(1,3)])`

## expected

it works

## actual:

error: cannot compare dissimilar column types bigint and integer at record column 1

<img width="914" alt="image" src="https://user-images.githubusercontent.com/12928716/216729261-1d9a229b-b5ca-41a2-9133-7b1d402b9a11.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/12928716/216729978-7dbdd0a8-2e39-4ed4-8c87-97ca5d2b25a0.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/12928716/216729316-5be50429-f594-4005-a11f-7f1e25c75637.png">

https://dbfiddle.uk/ZeUNdEns
<img width="826" alt="image" src="https://user-images.githubusercontent.com/12928716/216730127-bb0bccdb-0ca0-418f-b9c9-8408e8a52005.png">

**Comment by GaryAustin1** [comment]
You use int in your table that works, but bigint in the supabase table.  The default in your Array [....] will be int unless you type them bigint.   

bigint (8bytes) is not the same as int (4bytes) in Postgres and you have to correct for typing to intermix them.

This might work in your bigint column table...  `Array[(1,2)]::bigint[];` but not positive with embedded arrays.

**Comment by GaryAustin1** [comment]
@stuartcrobinson if that was your issue can you close this.  I don't have ability to do that.
