### ISSUE TITLE
Broken blog post codeblock highlighting

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#12182]
# Bug report

## Describe the bug

Code highlighting in code blocks not always highlighting correctly.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

example can be seen at https://supabase.com/blog/fetching-and-caching-supabase-data-in-next-js-server-components#static

## Expected behavior

to highlight correctly.

## Screenshots
<img width="816" alt="Screenshot 2023-02-05 at 7 00 23 PM" src="https://user-images.githubusercontent.com/8291514/216815111-68d46496-9061-4e09-92f0-59ec040a0c2d.png">

Ignoring the specific colors, but we should be highlighting more like this:
<img width="842" alt="Screenshot 2023-02-07 at 1 40 18 PM" src="https://user-images.githubusercontent.com/8291514/217158165-c3be99f2-9c5d-400b-b49b-9bfd0d580515.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by ImBIOS** [comment]
@MildTomato, Can you give a reference screenshot of the expected result of this issue?

**Comment by MildTomato** [comment]
I don't I'm afraid. But i think the GitHub highlighting below shows what should be getting highlighting in that same code block, rather than just showing white for a lot of it.

example:
```js
import Link from 'next/link'
import supabase from '../../utils/supabase'

export default async function Posts() {
  const { data: posts } = await supabase.from('posts').select('id, title')

  if (!posts) {
    return <p>No posts found.</p>
  }

  return posts.map((post) => (
    <p key={post.id}>
      <Link href={`/static/${post.id}`}>{post.title}</Link>
    </p>
  ))
}
```

cc @saltcod - maybe we just migrate to using [CodeHike](https://codehike.org/) and then the highlighting is then probably improved for free at the same time.

**Comment by ruggi99** [comment]
Similar issue in #11996
Is it related?

**Comment by adamulan** [comment]
@MildTomato I noticed that it highlights more when running in dev and less when running a built version and I found [this issue](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/263) in react-syntax-highlighter. I tried [this comment](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/263#issuecomment-1255662994) and a slight css change and it works and looks like this: 
![image](https://user-images.githubusercontent.com/84980432/221334054-2ca7fffb-f0be-4037-a83b-73ce62a0e055.png) 
I can make a pull request for this but I am not sure if you want to use dynamic import for this or migrate to CodeHike. The tokenization in react-syntax-highlighter isn't great for things like ```<Link href={`/static/${post.id}`}>{post.title}</Link>```.

**Comment by fsansalvadore** [comment]
> I can make a pull request for this but I am not sure if you want to use dynamic import for this

Hi @adamulan, feel free to create that PR with the dynamic import. 👍 Thanks!

**Comment by dotarjun** [comment]
Hey, is this issue still open? I would love to give this a shot

**Comment by saltcod** [comment]
go for it @dotarjun !

**Comment by gregnr** [comment]
Fixed via https://github.com/supabase/supabase/pull/14787
