### ISSUE TITLE
TypeScript Support?

### ISSUE THREAD

**Issue by CoLdAs1cE** [supabase/supabase#122]
* **I'm submitting a ...**
- [x] feature request
- [ ] question about the decisions made in the repository
- [ ] bug report
- [ ] question about how to use this project

* **Summary**
i only use typescript,
there was no d.ts included and no @types in npm,
is it possible to add?

**Comment by kiwicopple** [comment]
Hey @CoLdAs1cE thanks for the patience - end of month so we've been busy releasing.

Surprisingly you're the first person to ask for this. We're trying to ship fast, so we've been very focused on some of the bigger features. Regardless, I think this is a good idea. I'll keep it open and see if anyone in the community is keep to contribute, but if it isn't picked up, we can add it soon

Thanks for taking the time to stop in!

**Comment by CoLdAs1cE** [comment]
^^, i did search around but didn't see any issue for it or any solution. So i tough since u guys are actively updating, this was not noticed or in any ones thoughts at all. So since many use typescript i though i should let you guys know :)

**Comment by hgranthorner** [comment]
I wouldn't doing this for the supabase-js library, I've been using it a fair bit.

**Comment by kiwicopple** [comment]
That would be amazing @hgranthorner, thanks for offering. If you need any help just let us know. Happy to add you to our slack if you have anything to discuss

**Comment by awalias** [comment]
https://github.com/manifoldco/swagger-to-ts postgrest open-api spec to TS shared by @thorsten-stripe

**Comment by awalias** [comment]
adding link to [Supabase-js source](https://github.com/supabase/supabase-js/) for anyone willing to take this on

**Comment by thorwebdev** [comment]
Might also be helpful to look at how knex.js is doing this:

- http://knexjs.org/#typescript-support
- https://github.com/knex/knex/blob/master/types/index.d.ts

**Comment by thorwebdev** [comment]
@CoLdAs1cE @hgranthorner we've started work on type definitions [here](https://github.com/supabase/supabase-js/pull/18) that should be in a pretty usable state. We'd love for you to test it out and provide feedback. You can just copy the content from the [`index.d.ts`](https://raw.githubusercontent.com/supabase/supabase-js/feat/add-type-definitions/src/index.d.ts) file into your project at `node_modules/@supabase/supabase-js/lib/index.d.ts`. 

Feel free to provide feedback directly on the PR: https://github.com/supabase/supabase-js/pull/18. Thanks :)

Here the preliminary docs: https://deploy-preview-141--supabase.netlify.app/docs/library/getting-started/#usage-with-typescript

**Comment by kiwicopple** [comment]
❤️  . new docs

![image](https://user-images.githubusercontent.com/10214025/90391415-b2b80080-e0bf-11ea-8a9b-9917b265d45c.png)
