### ISSUE TITLE
500 error when trying to login to supabase

### ISSUE THREAD

**Issue by TWAH** [supabase/supabase#1220]
# Bug report

## Description

Clicking "Sign in" returns a blank page. The network tab in devtools shows a request to https://supabase.auth0.com/authorize returning a 500 error.

I've tried this on Firefox, initially with multiple extensions, but after trying again in incognito I get the same issue. Same in edge and iOS Safari too.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.io/
2. Click on 'Sign in'
3. See error

## Expected behavior

Presented with next step of login

## Screenshots

Screen is blank. I'll share the request/response  headers if required - I'm not sure if any of it is sensitive though.

## System information

- OS: Windows 10 Pro 2004, IOS (Latest)
- Browser: Firefox, Edge, Safari (IOS)

**Comment by TWAH** [comment]
Looks like it could be on auth0's side: https://status.auth0.com/incidents/zvjzyc7912g5?u=scp3y32hkxqk

**Comment by kiwicopple** [comment]
Thanks @TWAH - you're right it was caused by an Auth0 outage. We're in the process of migrating to Supabase Auth, so hopefully less of these issues in the future :)
