### ISSUE TITLE
Supabase Storage: Tenant config for ID not found. #3351 - If anyone else has this issue, please open a support ticket.

### ISSUE THREAD

**Issue by JasonChiu-dev** [supabase/supabase#12206]
If anyone else has this issue, please open a support ticket.

_Originally posted by @inian in https://github.com/supabase/supabase/issues/3351#issuecomment-1217438621_

**Comment by JasonChiu-dev** [comment]
Having the same issue. Tenant config for ID not found.

At first, I got "Internal Server Error" error message. I report to supabase technical team two days ago: Support Ticket ID: 1412931335.
I'm still waiting for a solution to this problem.

I try to do a project restore, and get "Tenant config for ID not found" error message.

How can I solve this problem??

**Comment by inian** [comment]
Closed via the support ticket. For posterity, please open a support ticket as mentioned on the dashboard for this particular error than a Github issue since it is an error specific to your project.

**Comment by JasonChiu-dev** [comment]
> Closed via the support ticket. For posterity, please open a support ticket as mentioned on the dashboard for this particular error than a Github issue since it is an error specific to your project.

It works very well. Thank you so much for your help.
