### ISSUE TITLE
Prisma integration guide is outdated

### ISSUE THREAD

**Issue by dannykng** [supabase/supabase#12215]
## Link 

https://supabase.com/docs/guides/integrations/prisma

## Describe the problem

From @rogadev:
- Location of database connection string is now different. The UI has changed since the screenshot was added into these docs (see first screenshot on the page).
- I didn't see any mention of `npx prisma init` which could be helpful. If readers already have a project setup, they're likely not going to want to generate a new project to follow this tutorial. It would be good to show them how to plug Prisma & Supabase into their existing project.
- In the docs it says to run `prisma dev --name init` which I'm pretty sure is supposed to say run `npx prisma dev --name init`. In either case it seems this is no longer the correct command, as doing so creates the following error: "Prisma CLI does not include a `dev` command any more right now."
- I'm fairly certain it would be a good idea to make sure to add the `auth` table, so that users can use a User ID as a foreign key on tables they create. This is a popular design pattern. Nothing that I can see in this documentation handles that.

## Additional context

https://github.com/supabase/supabase/pull/12212

**Comment by inian** [comment]
Hi Danny, these issues are all addressed in the latest Prisma integration page
