### ISSUE TITLE
Vue 3 Client Wrap

### ISSUE THREAD

**Issue by DidoMarchet** [supabase/supabase#1221]
# Improve documentation

## Link 

[https://github.com/DidoMarchet/vue-3-supabase](https://github.com/DidoMarchet/vue-3-supabase)

## Describe the problem

I haven't seen a Vue 3 wrapper for Supabase Client yet (only for Vue 2).

## Describe the improvement

I've do it.

Hope you enjoy,

have a nice day and regards,

Davide

**Comment by tylermercer** [comment]
@DidoMarchet Have you considered providing a `useSupabase` hook so that users of your library don't have to `inject` it?

**Comment by DidoMarchet** [comment]
Hi!
This is a good suggestion!
I think to rewrite it in a "Hook" way and in .ts to.

Have a nice day and regards,

Davide

**Comment by DidoMarchet** [comment]
Hi!
I've checked the Vue 3 hook and I love it.
But in this case I think is more confortable use a plugin giving access to the client in the whole application because:
- we don't need to import it every time
- it easy to setup inserting our credential one time and not each time we use the client (otherwise we need to create a nested hook)

Maybe I've not familiarity with hooks but this is my impressions
and I appreciate clarifications in case!

btw I rewrite it in ts :D

Have a nice day and regards,

Davide

**Comment by kiwicopple** [comment]
Hey @DidoMarchet - this is awesome! Thanks for building it. 

Perhaps you want to do a PR to our Docs? You can add it to our Examples page: https://supabase.io/docs/guides/examples

I'll close this issue, but just add a comment if you need help :)

**Comment by DidoMarchet** [comment]
Hi @kiwicopple I do it :)
I'm very glad to contribute!

Have a nice day and regards,

Davide

**Comment by tylermercer** [comment]
@DidoMarchet, I just meant something like the following:

```js
export const useSupabase = ()  => import('supabase');
```

Hope this helps 🙂

**Comment by tylermercer** [comment]
@DidoMarchet, I just meant something like the following:

```js
export const useSupabase = ()  => inject('supabase');
```

That way they don't have to type out the inject call themselves.

I would also recommend using a `Symbol` as the injection key instead of `'supabase'`.

```
const supabaseInjectionKey = Symbol()

// Now use supabaseInjectionKey instead of 'supabase' throughout your library.
```

Note that the symbol is not exported for the library user to use. This means that users cannot accidentally override the Supabase client by doing `provide('supabase', someGarbageValue)`

Hope this helps 🙂

**Comment by tylermercer** [comment]
@DidoMarchet I made [a PR](https://github.com/DidoMarchet/vue-3-supabase/pull/) with the changes I suggested 🙂

Thanks for creating this!

**Comment by DidoMarchet** [comment]
> @DidoMarchet I made [a PR](https://github.com/DidoMarchet/vue-3-supabase/pull/1) with the changes I suggested 🙂
> 
> Thanks for creating this!

Hi thanks,
I found your solution smart and then I updated the library and changed the version ;)

If you glad want I add a "thanks" section quoting you!

Thanks,
Davide

**Comment by tylermercer** [comment]
@DidoMarchet glad I could help!
