### ISSUE TITLE
Restoring hanging for hours

### ISSUE THREAD

**Issue by Gabriel416** [supabase/supabase#12237]
# Bug report

## Describe the bug
Tried restoring to a previous day and the UI says it's been restoring for hours. My database is only a couple of gigs

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to you back up versions
2. Click to restore any version
3. See if it hangs

## Expected behavior

Not sure this was my first time trying to restore to a previous version. I assume the dashboard should operate as normal.

## System information

- OS: macOS Big Sur
- Browser: chrome
- Version of supabase-js: N/A but ^2.1.2
- Version of Node.js:N/A but v16.13.1

## Additional context

I was adding indexes of my own in a SQL GUI which seemed to mess up performance so I decided to just restore to yesterday's version

**Comment by Hallidayo** [comment]
Hi @Gabriel416 - it my be worth contacting support through the dashboard on this one.

**Comment by kiwicopple** [comment]
thanks for reporting this @Gabriel416. definitely as @Hallidayo mentions - can you please reach out to support? https://app.supabase.com/support/new
