### ISSUE TITLE
Fix mobile width/ratio issue on all blog post YouTube video iframe embeds

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#12234]
# Bug report

## Describe the bug

On mobile view, youtube iframes are forcing the site layout to be too wide when not using corrective classNames or using the `<div className="video-container">` hack [like this](https://github.com/supabase/supabase/blob/2579f1339b3eb855a20aaa225bb930d95bf80ffe/apps/www/_blog/2023-02-07-chatgpt-supabase-docs.mdx?plain=1#L57-L65)

To resolve this issue, update all the youtube iframes in `/apps/www/_blog/*.mdx` so they display with consistent size ratio and also 100% of the container they are in.

**Comment by onkarhanchate14** [comment]
Added a PR - https://github.com/supabase/supabase/pull/12418
Added tags with proper formatting.
Review please

**Comment by dishant0406** [comment]
Hi @MildTomato I worked with supabase and I found it very interesting and helpful and now I would like to contribute to supabase repo, if possible, please assign me some issues.

**Comment by aaadryyy** [comment]
Looks like this issue is closable thanks to @onkarhanchate14 👌 
(maybe you could add a "Resolves #12234" in your PR message to retroactively resolve this issue?)
