### ISSUE TITLE
pgvector <=> is cosine distance, not cosine similarity

### ISSUE THREAD

**Issue by coyotespike** [supabase/supabase#12244]
# Improve documentation

## Link 

https://supabase.com/blog/openai-embeddings-postgres-vector

## Describe the problem

It's an excellent guide. There are 1-2 typos with openAI. It really gets only one thing wrong: cosine distance and cosine similarities are not the same. As a result the provided `match_documents` function is incorrect, which I discovered after tearing my hair out for a few hours when I wasn't getting any documents returned.

## Describe the improvement

Cosine Distance = 1 — Cosine Similarity

So you have two options. You can change similarity and similarity_threshold to be distance, instead.

Or you can do like so:
```
create or replace function match_documents (
  query_embedding vector(1536),
  similarity_threshold float,
  match_count int
)
returns table (
  id int4,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    "Documents".id,
    "Documents".content,
    (1 - ("Documents".embedding <=> query_embedding)) as similarity
  from "Documents"
  where (1 - ("Documents".embedding <=> query_embedding)) > similarity_threshold
  order by "Documents".embedding <=> query_embedding
  limit match_count;
end;
$$;
```

and invert the math. (My table has an upper case name, hence in quotes, but that part doesn't matter)

Many thanks for such a cool demo!

**Comment by jonra1993** [comment]
In my case change order by similarity DESC make it work as expected

**Comment by zdm** [comment]
> In my case change order by similarity DESC make it work as expected

Order DESC disables usage of index, be careful.
