### ISSUE TITLE
Edit function on website doesn't show advanced settings

### ISSUE THREAD

**Issue by gydence** [supabase/supabase#12243]
# Bug report

## Describe the bug

When you create a new function with Database > Functions > Create a new function, the Advanced Settings show up.  You can also select the return type and add arguments.  When you edit a function after creating it, the dialog says you can "Change the language in the Advanced Settings below", but the Advanced Settings aren't there, and you also can't change the arguments or the return type.

## To Reproduce

1. Database > Functions > Edit function
2. Unable to edit return type, arguments, or advanced settings.

## Expected behavior

The Edit function options should expose the full configuration options.

## Screenshots

Create a new function:
![image](https://user-images.githubusercontent.com/120065079/217420509-da71665f-25a4-401c-8f32-4ef099009928.png)

Edit function:
![image](https://user-images.githubusercontent.com/120065079/217420798-0e8ea09b-07a3-4e78-b604-bc05bd3f1276.png)

## System information

- OS: Windows
- Browser Chrome
- Version of supabase-js: NA
- Version of Node.js: NA

**Comment by GaryAustin1** [comment]
Basically once you define a function in Postgres you can not change/alter the parameters or return type and I believe security definer without creating a new function.  I assume that is why the UI works the way it does.  

At any rate this would not be a bug, but an enhancement to allow the ability to automatically delete and redefine the function in the UI.

**Comment by gydence** [comment]
@GaryAustin1 thank you for the response!  That makes total sense, but yeah if the UI could make this a little easier it would be super helpful.  At the very least, the text should be updated to not reference the Advanced Settings when they don't appear.

**Comment by tmcw** [comment]
This seems like a bug to me. The UI says "Change the language in the Advanced Settings below." Below that UI, there are no Advanced Settings.

**Comment by MildTomato** [comment]
Reading through this, seems like we have a bug and an opportunity to improve our communication in Studio.
So adding the bug label back.

Thanks @brandongregoryscott for dropping a PR on this, we'll take a look.

**Comment by leafleaf90** [comment]
Still not possible to edit advanced after creating the function.

**Comment by ivandamyanov** [comment]
I also tried and couldn't find  a way in the UI. I'm new to Postgres so don't do this in production but you can easily change your function (I wanted to add another argument) by getting your function definition code in SQL Editor:
```
select pg_get_functiondef(oid)
from pg_proc
where proname = 'yourFuncName';
```

This will conveniently return you the CREATE OR REPLACE script for your function where you can add arguments and replace the old one.
