### ISSUE TITLE
Unable to search docs with query: confirmation

### ISSUE THREAD

**Issue by peppermintbunny** [supabase/supabase#12259]
I am having great difficulty finding where to configure my project that email confirmation is NOT required for new sign ups

**Comment by GaryAustin1** [comment]
If hosted:
One Doc link I know of.
![image](https://user-images.githubusercontent.com/54564956/217662283-9edbd698-df5f-4c78-baad-67e92eed19af.png)

![image](https://user-images.githubusercontent.com/54564956/217662114-befca70c-5ce3-4bec-af44-027aac8250b5.png)
