### ISSUE TITLE
Miner virus found on self hosting ubuntu VPS

### ISSUE THREAD

**Issue by Waytoon** [supabase/supabase#1227]
# Bug report

Miner virus found on self hosting ubuntu VPS
- Miner virus: kdevtmpfsi

## Describe the bug
I would like to test self hosting for supabase on Aliyun, but after I settle it following self hosting instruction on my VPS, I found my VPS's CPU loading is always 100%!!!
I used 'top' to check all PIDs, I fount this miner guy...

I don't know this miner come from, but it is a new VPS I bought for supabase self hosting newly .
Anyone found the same thing ??

**Comment by inian** [comment]
I guess postgres was started with the default password which lead to this. Did you change the defaults when running @Waytoon ? 
@soedirgo is there a way to change the defaults on `supabase init` without ejecting?

**Comment by Waytoon** [comment]
Not change postgres pwd when I init it..., I just run supabase init....and start the service of supabbase..

**Comment by kiwicopple** [comment]
HI @Waytoon 

> Not change postgres pwd when I init it

The default password for our database  `postgres`. It is highly recommended that you update all of the passwords and secrets before running this in productions (I have added this note to the self hosting docs: https://github.com/supabase/supabase/commit/d2e2db1eae8f0ab365db5f60ed6ed3098e5f552a).

There are a lot of miners online that poll public IP addresses on port 5432 with default `postgres/postgres` credentials. You can consider disabling port for public access too.

Our self-hosting docs still need improvement. If you are going through the process of hardening your VPS, can you please keep a list of instructions and we can add them to the docs? THanks
