### ISSUE TITLE
Unable to submit support requests

### ISSUE THREAD

**Issue by timfee** [supabase/supabase#12285]
# Bug report

## Describe the bug

When I try to submit a support request, I get this error:
```

Failed to submit support ticket:
invalid_attachments

````

Even with attachments, this fails

## To Reproduce

https://user-images.githubusercontent.com/3246342/217756182-54584f76-1c1a-4aba-be1d-df1e9695e18f.mp4

## Expected behavior

Ticket should be submitted

## Screenshots

See video above

**Comment by saltcod** [comment]
Hi @timfee — thanks for reporting this. We fixed this last evening. Should be good to go for you know.
