### ISSUE TITLE
Failed to send a request to the Edge Function

### ISSUE THREAD

**Issue by gaodeng** [supabase/supabase#12293]
Why is the edge function so unstable? Almost more than half of the calls report an error 
"Failed to send a request to the Edge Function"
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-02-08 at 15 48 14](https://user-images.githubusercontent.com/1118249/217968467-00b53bd0-e741-40ab-b757-db7616b7d8c3.png)

**Comment by thorwebdev** [comment]
@gaodeng do you have any more information you can add, e.g.

1. what's the code of your function
2. What's your project id and your function name
3. Any logs you are seeing, both in your dev environment and your supabase dashboard?

If you're not able to share this information publicly, please click Help > Contact support in your project dashboard. Thanks.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/5748289/218362128-f52cf931-68f6-4ad5-b54e-5f96e25c4dd0.png">

**Comment by gaodeng** [comment]
@thorwebdev 

Intermittent Issues: We've been experiencing issues with Supabase Edge Functions that seem to occur intermittently, regardless of the user's physical location or network connectivity. This has led us to believe that the issue is not related to local network conditions.

Multiple Edge Functions Affected: While these issues are occurring, we have noticed that other Supabase APIs are functioning normally. However, it's not just one specific Edge Function that is experiencing issues. In fact, multiple Edge Functions are experiencing the same problems. This suggests that the issue may be related to Supabase infrastructure or platform-wide changes.

As a workaround to address the issue, we have decided to migrate and replace all Edge Functions. 

I previously reached out through the dashboard, but I didn't receive a response, Could you please check if you can find my previous message through the dashboard

**Comment by thorwebdev** [comment]
@gaodeng I'm afraid I'm not able to locate your ticket with your GitHub profile information. Could you help me by providing your project reference?

**Comment by rafayahmed123** [comment]
Did you end up finding a solution to this one? If so, please explain how you were able to achieve it.

**Comment by Mykyta-Chernenko** [comment]
I experience the same issue, some requests, around 10% just fail with this error, different locations, different functions, different time, it's especially painful to see that users cannot subscribe to premium because of it

**Comment by flogy** [comment]
Same here...

**Comment by KOoba1** [comment]
Also having the same issue, very scary that edge functions can just arbitrarily not work

**Comment by yuriyyakym** [comment]
The very likely reason for the problem is that you are using http protocol.
Not sure about macOS, but iOS requires connection to be secure by default.

Possible solutions:
- use your local IP address. Note: `http://127.0.0.1:54321` does not work for me, whereas  `http://192.168.1.3:54321` does
- use tool like ngrok in order to expose your local server via https
- update your app config in order to allow macOS/iOS to establish insecure connections

**Comment by sebestindragos** [comment]
Recently launched a product on Supabase and having this problem too. Just as others have mentioned, pretty much arbitrary failures with no obvious pattern.

@yuriyyakym You're providing a fix for edge functions running locally in a docker container while developing. Most people here have this problem in production with the real supabase API. Interestingly enough, it doesn't happen with the development env on my local machine.

**Comment by flogy** [comment]
Could it be that Cloudflare blocks some of the requests for some reason? 🤔

**Comment by antonioglass** [comment]
same issue here
