### ISSUE TITLE
type "http_request" does not exist when set tigger with `auth` schema

### ISSUE THREAD

**Issue by y0zong** [supabase/supabase#12309]
# Bug report

## Describe the bug

Im try to use http extension, it work fine with `public` schema, but failed with `auth` schema, is this design to for maybe some protection or a bug? (I have set `search_path`)

## To Reproduce

``` sql
create or replace function notice_when_user_created() returns trigger as $$ 
begin 
    PERFORM from http(
        (
            'POST',
            'https:/domain',
            ARRAY [http_header('Authorization','Bearer token')],
            'application/json',
            jsonb_build_object(
                'foo',
                'bar'
            )
        )::http_request
    );
    return null;
end;
$$ language plpgsql security definer;
SET search_path = extensions, public, auth, pg_temp;
drop trigger if exists after_user_insert on auth.users;
create trigger after_user_insert
after insert on auth.users 
for each row execute procedure notice_when_user_created();
```

## Expected behavior

should work just as `public` schema do maybe?

## System information

- supabase cloud

**Comment by GaryAustin1** [comment]
I think your set search_path is after the function create is closed.  

Also this is not the best approach.  Gotrue has a timeout set on the insert completing of a few seconds.   Between 2 and 5, don’t remember exactly.  If your http does not respond in time you will get an error and no user will be created.  You might look at pg_net which is async or writing to a table and using cron to do the net call.

**Comment by y0zong** [comment]
> I think your set search_path is after the function create is closed

I'm not professional with **postgresql**, but same code just work on `public` schema. I have tried to `set search_path` before function create, even add `auth` to **Extra search path**(project setting -> API setting) with UI but still hit `http_request` error 

> Gotrue has a timeout set on the insert completing of a few seconds. Between 2 and 5, don’t remember exactly. If your http does not respond in time you will get an error and no user will be created

Thanks for pointing it out ! and I just tried `pg_net` just works well ! although I don't know what happened to my case but I think my problem is solved so I close this issue.
