### ISSUE TITLE
Spreadsheet import incomplete on upload

### ISSUE THREAD

**Issue by nuotsu** [supabase/supabase#12308]
# Bug report

## Describe the bug

On the web version, uploading a spreadsheet (copy paste from Google Sheets, 8000+ rows, ~2.3 MB in size) completes and shows a green success notification with column headers imported, but no cell data.

Testing the same sheet, but reduced to 5 rows, shows the same success notification and success results with the cell data.

## To Reproduce

1. Create new table
2. Import data via spreadsheet > Paste text
3. Select primary
4. See results
5. Refreshing table after a while still shows an empty table

## Expected behavior

Show appropriate cell data (all 8000+ rows, or however many there are) populated.

## Screenshots

<img width="1552" alt="Screenshot 2023-02-09 at 5 25 55 PM" src="https://user-images.githubusercontent.com/24799299/217976971-73201216-4921-4511-86b3-ec697c0380dd.png">

## System information

- OS: macOS Ventura, MB Air M1
- Firefox

**Comment by saltcod** [comment]
Hi there @nuotsu  — any chance you could open a support ticket and attach a csv so we can try and reproduce? 
(Please scrub of any personal info if you do)  

Thank you!

**Comment by nuotsu** [comment]
Just sent filed a support ticket @saltcod

**Comment by joshenlim** [comment]
hey there @nuotsu - we've just pushed some improvements to the CSV import, would you mind trying once more to see if you might still be running into this issue? I've just tried with the sample CSV you've provided to us via the support ticket and it went through okay!
![image](https://user-images.githubusercontent.com/19742402/229730870-9eb3d278-f05a-4105-add4-243d06a5abeb.png)

**Comment by saltcod** [comment]
Marking as resolved, but feel free to reopen if you're still experiencing an issue here.
