### ISSUE TITLE
An error has occurred: Failed to fetch

### ISSUE THREAD

**Issue by spyriaev** [supabase/supabase#12334]
# Bug report

## Describe the bug

Can't update a db with DDL operations.  An error is being occurred  "An error has occurred: Failed to fetch".

## To Reproduce

1. Go to 'https://app.supabase.com/project/[my project]'
2. Click on 'Database-Tables-[Table name]-Edit'
3. Change a default value of a column and press Save
4. See error "An error has occurred: Failed to fetch"

## Expected behavior

Default value will be changed

## System information

- OS: MacOS Monterey
- Browser Chrome

**Comment by GaryAustin1** [comment]
You probably will need to provide more info or narrow down.
I just tested Firefox and Chrome (windows) and have no issues changing several defaults on different tables.
You might also hard refresh your browser and possibly restart your instance.

**Comment by spyriaev** [comment]
> You probably will need to provide more info or narrow down.
> 
> I just tested Firefox and Chrome (windows) and have no issues changing several defaults on different tables.
> 
> You might also hard refresh your browser and possibly restart your instance.

I recreate a new db with the same structure, the error doesn't appear.

Most likely the error relates with my db. I don't understand how to debug it or get more more logs.

**Comment by awalias** [comment]
hey @spyriaev you can query the postgres logs using the log explorer in the dashboard: https://supabase.com/docs/guides/platform/logs#logs-explorer figure out what is going on

I will close for now, but feel free to reopen if you gain any more insight into the issue. Hopefully then we can reproduce the bug.

**Comment by DhruvDh** [comment]
This is occurring for me also and I am unable to use Auth at all, I suspect this is the cause -

```
Log ID
5c663d87-fe21-4055-87ec-49348918f89d

Log Timestamp (UTC)
2023-02-21T20:50:43.000Z

Log Event Message
{"level":"fatal","msg":"running db migrations: error executing migrations/20221215195500_modify_users_email_unique_index.up.sql, sql: -- this change is relatively temporary\n-- it is meant to keep database consistency guarantees until there is proper\n-- introduction of account linking / merging / delinking APIs, at which point\n-- rows in the users table will allow duplicates but with programmatic control\n\nalter table only auth.users\n  add column if not exists is_sso_user boolean not null default false;\n\ncomment on column auth.users.is_sso_user is 'Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.';\n\ncreate unique index if not exists users_email_partial_key on auth.users (email) where (is_sso_user = false);\n\ncomment on index auth.users_email_partial_key is 'Auth: A partial unique index that applies only when is_sso_user is false';\n\nalter table only auth.users\n  drop constraint if exists users_email_key;\n: ERROR: cannot drop constraint users_email_key on table users because other objects depend on it (SQLSTATE 2BP01)","time":"2023-02-21T20:50:43Z"}

Log Metadata
[
  {
    "message": null,
    "timestamp": null,
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": null,
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": null,
    "_COMM": null,
    "duration": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": null,
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": null,
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": null,
    "component": null,
    "project": "uyancztmzjlekojeproj",
    "user_id": null,
    "auth_event": [],
    "referer": null,
    "factor_id": null,
    "provider": null,
    "remote_addr": null,
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [
      {
        "action": null,
        "auth_event": [],
        "component": null,
        "duration": null,
        "error": null,
        "host": "db-uyancztmzjlekojeproj",
        "instance_id": null,
        "level": "fatal",
        "login_method": null,
        "metering": null,
        "method": null,
        "msg": "running db migrations: error executing migrations/20221215195500_modify_users_email_unique_index.up.sql, sql: -- this change is relatively temporary\n-- it is meant to keep database consistency guarantees until there is proper\n-- introduction of account linking / merging / delinking APIs, at which point\n-- rows in the users table will allow duplicates but with programmatic control\n\nalter table only auth.users\n  add column if not exists is_sso_user boolean not null default false;\n\ncomment on column auth.users.is_sso_user is 'Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.';\n\ncreate unique index if not exists users_email_partial_key on auth.users (email) where (is_sso_user = false);\n\ncomment on index auth.users_email_partial_key is 'Auth: A partial unique index that applies only when is_sso_user is false';\n\nalter table only auth.users\n  drop constraint if exists users_email_key;\n: ERROR: cannot drop constraint users_email_key on table users because other objects depend on it (SQLSTATE 2BP01)",
        "path": null,
        "provider": null,
        "referer": null,
        "remote_addr": null,
        "status": null,
        "timestamp": null,
        "user_id": null
      }
    ],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": null
  }
]
```

**Comment by GaryAustin1** [comment]
@DhruvDh There was a change to Supabase instances involving the auth.users email column and constraint on it.
If you used that column as a foreign key in another table that will no longer work as it is not unique.
The migration running also may mean one you are migrating between two instances one with the change and one without.
OR something is going wrong in the upgrade process on your instance and you need to contact support.

**Comment by DhruvDh** [comment]
Thank you, I also added an edit. What you say makes sense.

**Comment by darkomking** [comment]
I'm also running into an issue where trying to alter and insert into a table using sql is giving me "An error has occurred: Failed to fetch" error. This is a query that worked well previously. I have tried restarting and even updating my instance from postgres 14.1 to 15.1. 

The only relevant error log I can locate is as follow: 
error_severity
ERROR

event_message
canceling statement due to statement timeout

timestamp
2023-02-27T20:16:15.202000

**Comment by jstdk** [comment]
This issue also happened to me, because supabase.io was not loading (in my case because it was stopped by the NoScript extension).

**Comment by sedhha** [comment]
Any resolutions? I am facing the same for reading data from Supabase.

**Comment by RFlintstone** [comment]
I'm facing the same issue. Would also like to hear of a possible solution.

**Comment by GaryAustin1** [comment]
Anyone posting they have the same issue on 'failed to fetch' should generate a new post with specifics of their case.  Failed to fetch is very generic and can be caused by dozens of different things.

**Comment by RFlintstone** [comment]
> Anyone posting they have the same issue on 'failed to fetch' should generate a new post with specifics of their case. Failed to fetch is very generic and can be caused by dozens of different things.

I just made an issue for my specific case (see above).

**Comment by Angus-Moore-Dev** [comment]
> There was a change to Supabase instances involving the auth.users email column and constraint on it.
If you used that column as a foreign key in another table that will no longer work as it is not unique.
The migration running also may mean you are migrating between two instances one with the change and one without.
OR something is going wrong in the upgrade process on your instance and you need to contact support.

This was it. Maybe a more appropriate notification is needed? Something to tell the user that emails can't be used as foreign keys?

That saved my arse too, since we're setting up SSO and obvs that opens the flood gate for non-unique emails for accounts.

**Comment by Sachin7397** [comment]
Try to use https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en
 enable it and try
