### ISSUE TITLE
Supabase site not loading

### ISSUE THREAD

**Issue by odafeaggreh** [supabase/supabase#12349]
# Bug report

## To Reproduce visit supabase.com

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'supabase.com'
2. See error 'site can't be reached' 

## Additional context

If it's any help, I'm visiting the site from Nigeria, West Africa. I also tried it on other devices and it gave the same error.

**Comment by GaryAustin1** [comment]
Did this resolve for you?  I've not seen any other reports of issues with their main site.

**Comment by awalias** [comment]
@odafeaggreh will close for now - feel free to reopen if you're still experiencing issues

**Comment by awalias** [comment]
I've asked the question here to see if other users are facing difficulties: https://twitter.com/AntWilson/status/1625049895450333184?s=20&t=4H9WdmmZOLigoAlPKDyIjA

**Comment by Cavdy** [comment]
I am currently experiencing this... For the past 2 days, it has not been loading for me

**Comment by boldrack** [comment]
This happens to me randomly. including right now ... Had a connection reset while on the platform, when connection was restored, I couldn't load the platform again . 

Same thing happened with a friend sometime last week.

**Comment by Xyzeebit** [comment]
I don't know why; but it is happening right now. I have experienced it multiple times, and I have checked if the site is down but it isn't. I am visiting the site from Nigeria.

**Comment by Lexx813** [comment]
Anybody figured out why this is happening its happening to me right now I can't get on only with a VPN

**Comment by boldrack** [comment]
> Anybody figured out why this is happening its happening to me right now I can't get on only with a VPN

Actually, It's not you. It's Supabase .

**Comment by jigmeloday** [comment]
Hi, currently my supabase dashboard projects are not loading, when i check network log it's showing CORS error and some pending API calls

**Comment by okoyedavid** [comment]
2024 and am experiencing same from nigeria seems supabase is intentionally preventing access from here and it started yesterday i think this is so weird and i hope its not what am thinking

**Comment by GaryAustin1** [comment]
> 2024 and am experiencing same from nigeria seems supabase is intentionally preventing access from here and it started yesterday i think this is so weird and i hope its not what am thinking

Vercel (hosts Supabase.com) is/was having an issue with a provider in Nigeria blocking them.
![image](https://github.com/user-attachments/assets/58028558-3624-47eb-bd48-8c076631a9bc)
https://discord.com/channels/839993398554656828/1301879559863533620

**Comment by aidyai** [comment]
same here 
I am also having the same issue, i hope it gets fixed ASAP

**Comment by dev-muhammad** [comment]
I have same problem.
supabase.com is not available for last 4 days (or more) from Tajikistan. But Supabase APIs are working well.

**Comment by bensonarafat** [comment]
Having this issue. 
Supabase not reachable for more than a week now

**Comment by codeBaron-dev** [comment]
I'm also experiencing this issue, does anyone have any resources on how to migrate from Supabse to Firebase. There's just so much work we’ve done with Supabase and this blocker isn't helping our team's productivity.

**Comment by amazinng-blib** [comment]
I'm having same issue. This site can’t be reached

**Comment by danielishakutv** [comment]
Still doesn't work from Nigeria. I have been able to access supabase only with a VPN for the past few days.

**Comment by Jibril14** [comment]
Same here from Nigeria, You can't browse Supabase website except with vpn

**Comment by mojoblanco** [comment]
Noticed this too but I think it has to do with specific ISPs. For example it doesn't work when I connect with MTN but it does when I connect with my fibre network.

**Comment by Jibril14** [comment]
> Noticed this too but I think it has to do with specific ISPs. For example it doesn't work when I connect with MTN but it does when I connect with my fibre network.

I suspected this too and tried Airtel still same error. By fibre you mean Star link?

**Comment by Iconicmike** [comment]
use Opera. it works.

**Comment by bensonarafat** [comment]
> use Opera. it works.

Yeah, With a VPN

**Comment by AprilPolubiec** [comment]
I am unable to reach supabase from Colombia, ISP is CaribeTech. Haven't tried a VPN yet but will try
