### ISSUE TITLE
Edge function - 500: Internal Server Error (INTERNAL_SERVER_ERROR_5) 

### ISSUE THREAD

**Issue by gaodeng** [supabase/supabase#12348]
50% of calls failed with error.

500: Internal Server Error (INTERNAL_SERVER_ERROR_5)

An error has occurred inside of a Deno Deploy system (code 5).

**Comment by awalias** [comment]
is this still occurring @gaodeng ? I've added @laktek who may have some insight on this one

**Comment by laktek** [comment]
@gaodeng Are you still experiencing issues? Do you see any specific error messages in your function logs?

**Comment by gaodeng** [comment]
Dear @awalias and @laktek,

Thank you for following up on my issue. I'm not sure if the problem still exists because I migrated and replaced all my edge functions yesterday. I apologize for the lack of information on my end.

If you are unable to reproduce the issue, you can go ahead and close this issue. I appreciate your time and assistance in trying to resolve the problem.

If there is anything else that I can assist you with, please let me know, and I will be happy to help.

**Comment by awalias** [comment]
ok will close for now! Feel free to reopen if you find any more issues / info!

**Comment by Waba-tron** [comment]
Im having this same issue when i try to make a insert, delete or update request on my edge functions.

**Comment by laktek** [comment]
@Waba-tron Can you open a [support ticket](https://supabase.com/dashboard/support/new) so we can take a look on our end? Also, check the Edge Function logs from the Supabase Dashboard if it shows any errors.
