### ISSUE TITLE
using function in policy is not working

### ISSUE THREAD

**Issue by pradeep-mishra** [supabase/supabase#12357]
# Bug report

## Describe the bug

I am using a function to validate if a user can add a row in a specific table or not.
the function seems to be working fine in the SQL editor and returns the expected result in a boolean
but using the same function in policy is not working as expected.

here is how I am using a function in policy

```js
(can_user_add_widget(uid()) = true)

```

and in the can_user_add_widget function, I am checking if the user plan allows more number of row to be created in this specific table or not.

here is a screenshot of the same function I am running on the SQL editor

<img width="925" alt="ss" src="https://user-images.githubusercontent.com/1678791/218284229-79126d2f-3030-4ba9-80be-2615d777937c.png">

and here is the screenshot of the policy i am using on the table for insert query

<img width="1145" alt="Screenshot 2023-02-12 at 4 17 22 AM" src="https://user-images.githubusercontent.com/1678791/218284301-f96b2555-8742-407d-8490-805f8fa81510.png">

**Comment by GaryAustin1** [comment]
Functions work fine in RLS.

You don't show your function but if not a "security definer" type it has to meet all RLS for the user when run from the API (but not from SQL editor).

You also may not really have a signed in user.  You could check that with TO option being `authenticated` and `true` for the policy and see if it works.

You really should be seeking help in discussions or better the Discord channel before concluding something is a bug especially if it is native Postgres.  You might get more interactive help that way. IMO.

**Comment by pradeep-mishra** [comment]
I didn't know about the Discord channel.

Here is the list of all policies applied to the widgets table

<img width="1449" alt="Screenshot 2023-02-12 at 2 24 42 PM" src="https://user-images.githubusercontent.com/1678791/218301826-66076406-111c-4fb1-8da1-c80c4cf1ef54.png">

There is only one policy that deals with insert query.

and if i remove that policy insert work as expect (obviously without limitation i want to put on)

**Comment by pradeep-mishra** [comment]
I didn't know about the Discord channel.

Here is the list of all policies applied to the widgets table

<img width="1449" alt="Screenshot 2023-02-12 at 2 24 42 PM" src="https://user-images.githubusercontent.com/1678791/218301826-66076406-111c-4fb1-8da1-c80c4cf1ef54.png">

There is only one policy that deals with insert queries.

And if i remove that policy, insert work as expected (obviously without limitation i want to put on)

**Comment by GaryAustin1** [comment]
I am saying you have not shown your function.   If it accesses another table the user has to be able to read that table.

**Comment by pradeep-mishra** [comment]
Security definer thing worked.
Thanks :)
next time will use Discord
