### ISSUE TITLE
Type errors occurs when I build the app with typescript, vite, vue3

### ISSUE THREAD

**Issue by donghoon-song** [supabase/supabase#12350]
# Bug report

## Describe the bug

Type errors occur when I build the app with vite, vue3, typescript. 
If I change the values of "preserveValueImports" to false, "importsNotUsedAsValues" to "remove" in tsconfig file, the errors dont occur but I think I can't edit tsconfig because their values are requirements for vite + vue3 + typescript app.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```bash
gh repo clone donghoon-song/supabase-ts-issue-reproduction
npm install
npm run build
```

## Expected behavior

Build succeeds.

## Screenshots

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/32301380/218266609-688313b4-f9da-43b5-8341-35a605fc33ec.png">

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 2.7.1
- Version of Node.js: 16.13.1

**Comment by awalias** [comment]
@donghoon-song what happens if you use [`import type`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) instead of `import`?

**Comment by donghoon-song** [comment]
@awalias If I use that, it works but those codes are in the package. If the changes make sense, may I create a PR?

**Comment by donghoon-song** [comment]
@awalias

**Comment by saltcod** [comment]
@alaister you run into anything like this with vite?

**Comment by alaister** [comment]
Tried to reproduce after updating to the latest supabase-js version, and it no longer seems to be an issue.
Feel free to reopen this if you can still reproduce.
