### ISSUE TITLE
supabase db remote commit does not apply remote changes to new project

### ISSUE THREAD

**Issue by StefanVDWeide** [supabase/supabase#12353]
# Bug report

## Describe the bug

When running the `supabase db remote commit` command in a project which I just initialised, I expect the 7 remote changes to be applied to my local development environment. Instead I get the following error:

```
Error: The remote database's migration history is not in sync with the contents of supabase/migrations. Resolve this by:
- Updating the project from version control to get the latest supabase/migrations,
- Pushing unapplied migrations with supabase db push,
- Or failing that, manually editing supabase_migrations.schema_migrations table with supabase migration repair.
``` 

I was under te impression that when you have an empty `/migrations` folder (or no migrations folder), the remote migrations will be applied. 

Running the `supabase migration list` command shows the expected migrations:

```
    LOCAL │     REMOTE     │     TIME (UTC)
  ────────┼────────────────┼──────────────────────
          │ 20221015154708 │ 2022-10-15 15:47:08
          │ 20221018164830 │ 2022-10-18 16:48:30
          │ 20230105123901 │ 2023-01-05 12:39:01
          │ 20230105125254 │ 2023-01-05 12:52:54
          │ 20230107120832 │ 2023-01-07 12:08:32
          │ 20230107124039 │ 2023-01-07 12:40:39
          │ 20230211161612 │ 2023-02-11 16:16:12
```

## Expected behavior

When running the `supabase db remote commit` in a new project, for the local changes to be applied in accordence with the documentation [here](https://supabase.com/docs/guides/cli/local-development#database-migrations).

## System information

- OS: macOS Monterey
- Version of Nuxt-Supabase: 0.3.1
- Version of supabase-js: 2.7.1
- Version of Node.js: 19.6.9

**Comment by StefanVDWeide** [comment]
Answer I got on Discord for anyone running into the same issue:


> This is because remote commit writes to the remote database the first migration entry as the one its about to pull down. Go to the remote project and go to the table editor then supabase_migrations > schema_migrations and remove the entry from there for the previous supabase db remote commit migration that was created.

**Comment by farzadali3** [comment]
For anyone coming here in 2024, the schema_migrations table is read-only when accessed from the Table Editor. But, you can interact with it from the SQL editor. The following command will clear the schema_migrations table.
`delete from supabase_migrations.schema_migrations;`

**Comment by diogomwbdv** [comment]
Hey farzadali3, that worked for me! thanks
