### ISSUE TITLE
Sidebar is not mobile responsive

### ISSUE THREAD

**Issue by thara003** [supabase/supabase#12396]
# Bug report

The sidebar in `docs/guides` section is not mobile responsive.

## Describe the bug

The sidebar in the guides pages ([link](https://supabase.com/docs/guides/database)) acts weird. It tends to reduce the whole screen size while open which makes the design inconsistent.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/database or any other docs from [here](https://supabase.com/docs#product-documentation)
2. Click on the hamburger icon
3. You can see the bug

## Expected behavior

The sidebar should be consistent and responsive in all websites pages. The design should not break for any circumstances.

## Screenshots

https://user-images.githubusercontent.com/79561774/218554046-5dfe32ec-36bd-4313-86f1-db354b2d18b2.mov

## System information

- OS: macOS
- Browser: Brave

**Comment by msaini0r** [comment]
@GaryAustin1 @thara003 I would like to work on this issue.

**Comment by saltcod** [comment]
Yes please @msaini0r! thank you!
