### ISSUE TITLE
Realtime is not enabled when it was enabled by migration on remote server

### ISSUE THREAD

**Issue by itog** [supabase/supabase#12409]
# Bug report

## Describe the bug

To enable Realtime on migration, I write the alter statement in migration file like below.
```
alter publication supabase_realtime add table <table name>;
```

This works ok with local  development server.
But when I push the db on the remote server, it looks Realtime is enabled on the web console, but it is not working.

Once I disabled and re-enabled Realtime on the web console, it works as expected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new project
2. link the project with CLI
3. push the db
4. add or edit a row with client app
5. see error

## Expected behavior

Realtime should work.
Or the Realtime checkbox on the table edit on the web console should be unchecked.

## System information

- OS: Android with Flutter
- Version of supabase_flutter: ^1.2.2

**Comment by dshukertjr** [comment]
@itog I'm sorry to hear that you were having trouble with this. Would you be able to check if this still happens with the latest Supabase CLI?

**Comment by mansueli** [comment]
closed as stale/no response from OP
