### ISSUE TITLE
Edge Functions: SUPABASE_DB_URL secret not up-to-date

### ISSUE THREAD

**Issue by cohlar** [supabase/supabase#12415]
# Bug report

## Describe the bug

When I update my database password, the `SUPABASE_DB_URL` secret in the edge functions' Deno environment is not updated.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Update your project database password from the Supabase dashboard
2. Call an edge function that uses the `SUPABASE_DB_URL` secret
3. The password in the `SUPABASE_DB_URL` secret is not up-to-date

## Expected behavior

Since `SUPABASE_DB_URL` is provided by Supabase by default (and that great!), I would expect it to be in sync with the actual database properties, and not to have to maintain it manually.

## Additional context

For now my work around is to set `SUPABASE_DB_URL` manually through `supabase secrets set`.

**Comment by uier** [comment]
went through a long way to get to this issue, I feel like if this bug does exist, reference the issue in the doc would be very helpful! 😄 
(I finally found this issue in Discord)

and BTW, now we cannot manually set secrets beginning with `SUPABASE_` since I got this error
```
Unexpected error setting project secrets: {"message":"Secret name must not start with the SUPABASE_ prefix."}
```
so using other names without this prefix

**Comment by soedirgo** [comment]
This should be fixed now - thanks for the patience! You can try resetting the DB password using the same password as before, and the `SUPABASE_DB_URL` should get updated accordingly.

**Comment by parketh** [comment]
Hi - I'm running unto a similar issue where `SUPABASE_DB_URL` is not  being updated for the newly introduced connection pooling URLs. Is there a way to manually set the DB URL?

**Comment by riyamittal009** [comment]
I am also running into this issue with SUPABASE_URL and SUPABASE_ANON_KEY, which Deno is loading incorrectly to create the supabase client. is this still a bug?
