### ISSUE TITLE
Port UI Storybook setup to packages/ui

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#12417]
Back when Supabase UI was a stand-alone package, we had a proper Storybook setup:
https://github.com/supabase/ui/blob/master/package.json#L15

Would be great to port this its new home in `packages/ui `
https://github.com/supabase/supabase/tree/master/packages/ui

**Comment by Gautam-Arora24** [comment]
Working on this!

**Comment by Gautam-Arora24** [comment]
Working on this!

**Comment by Ziinc** [comment]
@Gautam-Arora24 this issue is resolved in https://github.com/supabase/supabase/pull/12427 which would have better development flow for studio, as opposed to having an out-of-sight dev/documentation environment
