### ISSUE TITLE
supabase start keeps redownloading docker images

### ISSUE THREAD

**Issue by 72L** [supabase/supabase#12441]
# Bug report

## Describe the bug

When I run `supabase start`, it re-downloads docker images every time.

## To Reproduce

1. Run `supabase start`
2. Wait for it to complete
3. Run `supabase stop`
4. Run `supabase start`
5. See that it redownloads all docker images, causing a long wait.

## Expected behavior

It should cache or save the images so that it does not have to download them every time I start local supabase. 

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 2.7.1
- Version of Node.js: v16.15.1

**Comment by irfandyj** [comment]
Why is this completed when no solutions provided?
I still have same problem.
