### ISSUE TITLE
Add integration/partner pages to sitemap

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#12461]
# Chore

## Describe the chore

Integration pages are currently missing from the sitemap

Index pages:
https://supabase.com/partners/integrations
https://supabase.com/partners/experts

individual pages:
https://supabase.com/partners/ory

on another note, these urls are perhaps not good.
Could be: https://supabase.com/partners/*integrations*/ory for more clarity in url as to what it is

## Additional context

The sitemap is generated [here](https://github.com/supabase/supabase/blob/chore/case-studies/apps/www/internals/generate-sitemap.mjs).

The sitemap can be updated from here, and it runs on build (ie, `npm run build`)

Add any other context or screenshots that help clarify the task.

**Comment by Aditya83-byte** [comment]
Hello, I am new to Open Source as well as GitHub, could you please explain the task to me.

**Comment by MildTomato** [comment]
Hey @Aditya83-byte 👋 

I've updated the description with more information

**Comment by vozmi** [comment]
Hello! 

I managed to split the partners page from _/partners/:slug_ to _/partners/integrations/:slug_ and _/partners/experts/:slug_, but couldn't add sitemap to one that you linked in the description (sitemap_www.xml). Instead, I added another sitemap for this page (sitemap_www-partners.xml).

If you have any ideas how to do it in [_generate_sitemap.mjs_](https://github.com/supabase/supabase/blob/chore/case-studies/apps/www/internals/generate-sitemap.mjs) I can try it :slightly_smiling_face:

**Comment by MildTomato** [comment]
missing integration pages still

**Comment by vozmi** [comment]
@MildTomato, my PR #12709 has both integrations and experts pages and generates sitemap the same way as in #12738. Should I add or change something in it?

**Comment by MildTomato** [comment]
Nice @vozmi added comment on PR
