### ISSUE TITLE
supabaseUrl Required

### ISSUE THREAD

**Issue by ethanfox** [supabase/supabase#12493]
# Bug report

## Describe the bug

**`Uncaught Error: supabaseUrl Required`**

I keep getting this error after I deploy my app with npm run preview and when I deploy through Vercel. I get no error when the app is "building"

The problem isn't the .env variables being used in Vercel's environment as it successfully builds.

The problem is somewhere in my code as it also happens in localhost when previewing.

**npm run dev works fine.**

I have also rebuilt my app as well - meaning I started a new svelte-kit project, reinstalled supabase, and set everything up from scratch, and still no luck.

## To Reproduce

No Idea

## Expected behavior

My app connects to supabase

## Screenshots

<img width="563" alt="Screenshot 2023-02-16 at 6 10 36 PM" src="https://user-images.githubusercontent.com/22962600/219519404-df8ad9a5-8004-460c-b538-a2b3c582e482.png">

**Comment by GaryAustin1** [comment]
Can you console.log right before your createClient call to see if the url is there?   Or even console.log your Supabase client log object after and see what is there.
You don't show any code so hard to offer anything else.

**Comment by ethanfox** [comment]
> Can you console.log right before your createClient call to see if the url is there? Or even console.log your Supabase client log object after and see what is there. You don't show any code so hard to offer anything else.

This is my code. STraight from the supabasedocs

    `import { createClient } from '@supabase/auth-helpers-sveltekit';
    import { env } from '$env/dynamic/public';
    // or use the static env

    // import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public';

    export const supabaseClient = createClient(env.PUBLIC_SUPABASE_URL, env.PUBLIC_SUPABASE_ANON_KEY);
`

**Comment by GaryAustin1** [comment]
So you don't have a console.log of it?
Supabase url should look like `https://ugcxxxxxxxxxxxxxxxq.supabase.co` right before your `export const.....`

If it does not then you need to figure out why the environment setting/s are not making it to your code.

You might get more help in Supabase Discord or even discussions here to sort this.   But unlikely a bug in createClient,

It could be something in the docs of the repository that is from (I'm guessing here https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md based on a google text search).  BUT there are no issues I see there on supabaseUrl.

**Comment by ethanfox** [comment]
# Solution
Use the static env option shown below.

        import { createClient } from '@supabase/auth-helpers-sveltekit';
        //import { env } from '$env/static/public';
        // or use the static env
        import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public';
        
        export const supabaseClient = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
