### ISSUE TITLE
Error when downloading file from bucket

### ISSUE THREAD

**Issue by A-L-M** [supabase/supabase#12497]
# Bug report

## Describe the bug

I have a bucket named assets which contains two images. After clicking the bucket and selecting one of the images and clicking "Download", the file is downloaded and everything works fine. The problem occurs if I click on the other file and then click the original one. When clicking the download button, an error message appears and the file is not downloaded. I haven't added any policies to the bucket.

It appears that going back to the original file strips the "t" parameter from the download url the Download button provides.

## To Reproduce

1. Go to any bucket with two files.
2. Select one file
3. Click on the other
4. Select the first one again
5. Click download

## Expected behavior

The image is downloaded
## Screenshots

![image](https://user-images.githubusercontent.com/20939910/219530703-6f1f48fd-35cd-4a6e-a242-72edbefdee0a.png)
![screenshot](https://user-images.githubusercontent.com/20939910/219531343-f8751b44-c70c-43f9-a922-663871ddda02.png)

## System information

- OS: Windows
- Browser: Chrome

**Comment by GaryAustin1** [comment]
I can confirm it is an issue, but not sure the steps shown are not enough.  Seems like you have to be clicking around really fast to get the 404.

bad URL on download:  `https://xxx.supabase.co/storage/v1/object/public/test2/2.0.5.JPG&download`
which clearly won't work with out a ? after file name.

good URL `https://xxx.supabase.co/storage/v1/object/public/test2/2.0.5.JPG?t=2023-02-17T04:31:56.465Z&download=`

**Comment by saltcod** [comment]
Couldn't reproduce this across a couple of projects. Going to close as it may be outdated. Please feel free to reopen if this is still the case for you.
