### ISSUE TITLE
Permissions dropdown css bug

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#12507]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/458736/219579055-4c8d368e-8dc6-4e28-b3d8-a52603854883.png">

on org permissions

using Firefox 109.0.1 on Mac 13.2.1

**Comment by haszankauna** [comment]
hello @awalias can you please assign this issue to me?

**Comment by MildTomato** [comment]
@haszankauna feel free to just PR changes

**Comment by Pcmyclo** [comment]
Flag
