### ISSUE TITLE
PGVector missing

### ISSUE THREAD

**Issue by eddysalzmann** [supabase/supabase#12519]
In the current version there is no Vector extension. Is that something that will come in the future? If yes, when? Or is it something we have to install by ourselves? Can't find it in the official site nor the self hosted version...

**Comment by GaryAustin1** [comment]
If you have a free instance just do pause then restore to load latest software.  If pro you have to contact support currently.

**Comment by eddysalzmann** [comment]
But shouldn't it be part of the self hosted version too?

**Comment by GaryAustin1** [comment]
Sorry, did not understand that was your primary concern.  Usually the latest image Supabase/Postgres https://github.com/supabase/postgres has the same as Supabase hosted, but I don’t use selfhosting, so  am not sure on status there.   

You’ll have to wait for someone with knowledge of that or check that repository to see if installed.

**Comment by jjhbw** [comment]
Same here. Getting `Error: ERROR: could not open extension control file "/usr/share/postgresql/14/extension/vector.control"` after pulling all images from scratch.

```
supabase --version
1.41.3
```

**Comment by sweatybridge** [comment]
The pgvector extension is currently available on pg15 only. If you are using self-hosted it is already listed on extensions page http://localhost:3000/project/default/database/extensions.

If you are using CLI, make sure to update your postgres major version in `supabase/config.toml` to 15.
