### ISSUE TITLE
Heroku to Supabase Importer not working

### ISSUE THREAD

**Issue by adamzerner** [supabase/supabase#12527]
The first time I tried I got stuck on this screen. The "Review import" button never did anything when I clicked it.

Then after doing various things that I don't remember (wait a long time, open the dev console, remove the string and re-enter it...) the button did work. I went through the migration process and it said that it was successful. But after about 20 minutes I still don't see databases in the table editor (none in the `public` schema; other schemas have tables but they're the predefined ones, not the ones I attempted to import from Heroku).

So I went back to try the import again and now the "Review import" button won't work.

It's a small database. `pg_dump` yielded a file with 16134 lines.

Following the directions in [Migrate from Heroku to Supabase](https://supabase.com/docs/guides/resources/migrating-to-supabase/heroku) -- ie. using `pg_dump` and `psql` -- looks like it worked for me.

<img width="1440" alt="Screenshot 2023-02-18 at 4 30 33 PM" src="https://user-images.githubusercontent.com/3144254/219906394-06efa869-0fa8-410f-8863-42a376603f1b.png">

**Comment by adamzerner** [comment]
@burggraf I have moved on from the relevant project, sorry. I am not sure whether this same issue affects other or not though.

**Comment by saltcod** [comment]
Sorry for this one falling through the cracks @adamzerner.   Going to mark this one as closed as it's quite out of date by now..
