### ISSUE TITLE
NextJs 13 appDir issue: Can't resolve 'encoding' module

### ISSUE THREAD

**Issue by shahradelahi** [supabase/supabase#12534]
# Bug report

```
Module not found: Can't resolve 'encoding' in '-\node_modules\node-fetch\lib'  

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@supabase/supabase-js/dist/main/lib/fetch.js      
./node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js 
./node_modules/@supabase/supabase-js/dist/main/index.js
./libs/supabase.ts
./app/page.tsx
```

## Describe the bug

I recently started using the `appDir` and I'm facing an issue and a bit confused about it.

Seems like the data are not fetched from the database. And it's static even when I'm using the `revalidate` option.

## To Reproduce

```tsx
import { supabase } from "@libs/supabase";

export const revalidate = 10;

async function getData() {
   const { data, error } = await supabase
       .from('todos') // the table is not empty
       .select('*')

   if (error) {
      console.log('error', error)
      return { error: true }
   }

   console.log('data:', data) // data: []
   return data // The data is always an empty array
}

export default async function Page() {
   const data = await getData()
   return <pre>{JSON.stringify(data, null, 2)}</pre>;
}
```

## Expected behavior

I expect the data to be fetched from the database.

## System information

- `OS`: `Windows`
- `Browser`: `chrome`
- `@supabase/supabase-js`: `2.8.0`
- `next`: `13.1.6`
- `react`: `18.2.0`

**Comment by shahradelahi** [comment]
For the error `Can't resolve 'encoding' module`:

I guess the packages weren't installed properly. And I just removed `node_modules` and reinstalled the packages.

And for the data issue, the problem was the `RLS` policy. I was totally forgotten about it.

**Comment by jaitaiwan** [comment]
@harshcut Old issue still open for this: https://github.com/supabase/supabase-js/issues/612
