### ISSUE TITLE
Web UI not working on Firefox 101 on Linux

### ISSUE THREAD

**Issue by palfrey** [supabase/supabase#12537]
# Bug report

## Describe the bug

Logging in with Firefox now gets "Application error: a client-side exception has occurred (see the browser console for more information)" with a console error of "ReferenceError: TransformStream is not defined" in "57476 crc32-stream.js:33"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/
2. Click on Sign-in
3. See error

## Expected behavior

A logging

## Screenshots

![image](https://user-images.githubusercontent.com/38532/219963049-67782b92-c4cf-41bf-bb66-af9fb3916d48.png)
![image](https://user-images.githubusercontent.com/38532/219963060-1d3dbea2-d26a-47d1-8b73-331c9b9444fb.png)

## System information

- OS: Debian Linux
- Browser (if applies): Firefox 101.0.1

## Additional context

This was definitely working a couple of months ago. 101.0.1 was released June 2022, so probably still the same browser version.

**Comment by palfrey** [comment]
Upgrading to 109.0 fixed this

**Comment by GaryAustin1** [comment]
![image](https://user-images.githubusercontent.com/54564956/219964895-4eb9e9ce-cf08-418b-9773-d6d7b8d7ca37.png)
Firefox added this in June of 2022.
I'll leave open for now in case Supabase devs want to support older Firefox versions.
