### ISSUE TITLE
`gt` doesn't work when column name is "order"

### ISSUE THREAD

**Issue by adamzerner** [supabase/supabase#12539]
[`gt`](https://supabase.com/docs/reference/javascript/gt) doesn't work when column name is "order". This code:

```
const { data, error } = await supabase
      .from("metric_categories")
      .select()
      .gt("order", 1);
```

Gives me this error:

```
{
  code: 'PGRST100',
  details: 'unexpected "1" expecting "asc", "desc", "nullsfirst" or "nullslast"',
  hint: null,
  message: '"failed to parse order (gt.1)" (line 1, column 4)'
}
```

But it works as expected when I replace `"order"` with a different column name like `"id"` or `"user_id"`.

**Comment by GaryAustin1** [comment]
Ordering(https://postgrest.org/en/stable/api.html#ordering)
"The **reserved word order** reorders the response rows. It uses a comma-separated list of columns and directions:"

Also an SQL reserved word.
https://www.postgresql.org/docs/current/sql-keywords-appendix.html
"ORDER  reserved, requires AS"

Not sure this is Documented in the Supabase API though.

**Comment by adamzerner** [comment]
It worked in Prisma FWIW:
```
const metricCategoriesToUpdateOrder = await prisma.metricCategory.findMany({
  where: {
    order: {
      gt: oldOrder,
    },
  },
});
```

**Comment by GaryAustin1** [comment]
It can work in SQL as long it is always referred to with double quotes "order" and it is in general recommend not to use reserved words.  It seems though the API does have it reserved, just not well documented in Supabase, or at least I've never run across it.

**Comment by GaryAustin1** [comment]
@adamzerner 
I did some testing and this works....
`.gt(' "order" ', 3)`

**Comment by adamzerner** [comment]
@GaryAustin1 Ah that works, thanks!

**Comment by GaryAustin1** [comment]
Yeah,  that was just to make clear '" , should have previewed the block and seen it added enough space to see.

**Comment by GaryAustin1** [comment]
I'm changing this to documentation/enhancement at this point as it should be mentioned and a better error might be possible.

**Comment by adamzerner** [comment]
Makes sense to me.

**Comment by Hallidayo** [comment]
Hi @adamzerner @GaryAustin1 - I've create a pull for this issue but just checking does this change need to be on all filters?

**Comment by GaryAustin1** [comment]
@Hallidayo Yes it applies to most filters.  It might be better in the general filter section.
