### ISSUE TITLE
Prisma with row level security

### ISSUE THREAD

**Issue by dheerajsarwaiya** [supabase/supabase#12549]
# Improve documentation

I am using prisma with supabase. However, I am unable to find documentation on how to use prisma with supabase row level security.
Is it possible? If yes, is there a documentation? 

## Link 
https://supabase.com/docs/guides/integrations/prisma

Add a link to the page which needs improvement (if relevant)

## Describe the problem

There is no documentation on how to use row level security with prisma. 

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

Add a section with some examples.

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by GaryAustin1** [comment]
I don't know much about Prisma, but this seems to be something from the Prisma side of things.  To Prisma, Supabase is just a Postgres database as it comes in the database port.  

https://www.prisma.io/blog/client-extensions-preview-8t3w27xkrxxn   This mentions something about using RLS with Prisma.

Can you clarify what you are trying to do or want documented from Supabase versus Prisma?

Also Supabase Discord are a great place to talk to other Prisma/Supabase users.

**Comment by GaryAustin1** [comment]
This seems like a Prisma issue as RLS is a Postgres thing and not specific to Supabase.
https://github.com/prisma/prisma/issues/12735
Seems to be an active topic there.
Going to close this.
