### ISSUE TITLE
Sveltekit tutorial - hiccups with deploying with Vercel

### ISSUE THREAD

**Issue by jdshaeffer** [supabase/supabase#12556]
# Bug report

## Describe the bug

After completing the [getting started tutorial with Sveltekit](https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit), and confirming everything was working locally, I chose to deploy the project in Vercel. First, I followed the [integration tutorial](https://supabase.com/docs/guides/integrations/vercel) and added my env vars to the project settings in Vercel. It deployed successfully but the `PUBLIC_` env vars returned `undefined` in production. A small change to the `supabaseClient.ts` mitigated that:
```typescript
import { createClient } from '@supabase/auth-helpers-sveltekit';
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';

export const supabase = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
```
> The above could be a proposed change to [the tutorial docs](https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/getting-started/tutorials/with-sveltekit.mdx), L52-55. The change: instead of importing the `env` object from `$env/dynamic/public`, import the env vars directly from `$env/static/public`. This then allowed the env vars to be defined correctly once deployed. PR: https://github.com/supabase/supabase/pull/12557

All was smooth until clicking the magic link sign in / sign up that was sent to the test user's email. When clicking the link in the email to sign in, it produces a successful `access_token` but it does not redirect to the deployed domain, instead to `localhost:3000`. Manually changing this in the url to the deployed domain solves this and arrives to the authenticated page correctly. The main issue here lies in the incorrect domain in a production environment. Is there a setting or a configuration I'm missing? I apologize if this was too long-winded or if there's a naive solution to this. Thank you.

## To Reproduce

1. Complete the [getting started tutorial with Sveltekit](https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit)
2. Follow the code change described above by directly importing the public env vars from `$env/static/public` instead of importing the env object from `$env/dynamic/public`
3. Prepare deployment environment in Vercel by loosely following the [integration tutorial](https://supabase.com/docs/guides/integrations/vercel) and by adding the env vars to the project's settings
4. Deploy
5. Send magic link from form
6. Go to email, click on link
7. Arrive at the unexpected `http://localhost:3000/#access_token=...`, not being redirected to the authenticated page on the app

## Expected behavior

Click on the magic link to login to the deployed environment and arrive directly on the authenticated page, not the unexpected localhost page.

## System information

- OS: macOS
- Browser (if applies): brave (chromium)
- Version of supabase-js: 2.8.0
- Version of Node.js: v16.17.0

**Comment by GaryAustin1** [comment]
It would be better if you asked questions in discussions or Supabase Discord on these types of issues as more people available to help debug what you are doing.

I'm going to guess your siteURL is still set in the dashboard to localhost.  If you do not provide a redirectTo url in your OTP call, the system will redirect to siteURL.

If you use redirectTo then you can have the url go to different places depending on your setting based on production versus dev.  SiteURL is not involved if you have the redirectTo set, and set redirect URLs in the Auth settings of the dashboard...
https://supabase.com/docs/reference/javascript/auth-signinwithotp

**Comment by jdshaeffer** [comment]
@GaryAustin1 thank you for the suggestion, sorry for the wrong comms. The redirect via the Site URL setting was news to me, and that answered my main issue, thank you. I still think the improvement suggested for the docs in the Sveltekit tutorial could be made so that people trying to deploy won't run into the undefined `PUBLIC_` env vars. I've attached a PR to the issue (#12557). Let me know if you don't think it's necessary and I can close, no worries.
