### ISSUE TITLE
Document -d flag for starting docker compose in the background

### ISSUE THREAD

**Issue by mauricev** [supabase/supabase#12560]
# Bug report

## Describe the bug

1. postgrest/postgrest never reports itself as healthy
2. supabase-imgproxy keeps running a health check over and over

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. On a Linux x64 system, follow the instructions at https://supabase.com/docs/guides/self-hosting/docker
2. This results in a broken docker installation that can’t get past the two issues above.

## Expected behavior

Docker installation should complete successfully and run.

## System information

- OS: Linux Mint 21

## Additional context

[env.txt](https://github.com/supabase/supabase/files/10786775/env.txt)

**Comment by ruggi99** [comment]
Hi @mauricev 
Postgrest doesn't have healthcheck at the moment so it never reports healthy as you noted.
Strange that imgproxy reports unhealthy.

Can you please post a screenshot of this command?
```sh
docker compose ps
```

Thanks

**Comment by mauricev** [comment]
```
CONTAINER ID   IMAGE                              COMMAND                  CREATED       STATUS                    PORTS                                                                                                      NAMES
471c77975af7   supabase/storage-api:v0.28.2       "docker-entrypoint.s…"   2 hours ago   Up 16 seconds (healthy)   5000/tcp                                                                                                   supabase-storage
0ed3be032161   supabase/realtime:v2.5.1           "/usr/bin/tini -s -g…"   2 hours ago   Up 17 seconds (healthy)                                                                                                              realtime-dev.supabase-realtime
be04d8a93502   supabase/postgres-meta:v0.60.7     "docker-entrypoint.s…"   2 hours ago   Up 17 seconds (healthy)   8080/tcp                                                                                                   supabase-meta
6cfd3ebe4156   postgrest/postgrest:v10.1.2        "/bin/postgrest"         2 hours ago   Up 17 seconds             3000/tcp                                                                                                   supabase-rest
84f0fc786bdd   supabase/gotrue:v2.47.0            "gotrue"                 2 hours ago   Up 18 seconds (healthy)                                                                                                              supabase-auth
fb061de423d4   darthsim/imgproxy:v3.11            "imgproxy"               2 hours ago   Up 24 seconds (healthy)   8080/tcp                                                                                                   supabase-imgproxy
1d37236966d3   supabase/postgres:15.1.0.42-rc2    "docker-entrypoint.s…"   2 hours ago   Up 24 seconds (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                  supabase-db
cbbd02af5d5e   kong:2.8.1                         "/docker-entrypoint.…"   2 hours ago   Up 24 seconds (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 8444/tcp   supabase-kong
4ebe28afe250   supabase/studio:20230216-e731b77   "docker-entrypoint.s…"   2 hours ago   Up 24 seconds (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                  supabase-studio
```
As you can see it’s not that it is reporting unhealthy, it’s just that the healthcheck attempts just keeps repeating: 
```
supabase-imgproxy | INFO    [2023-02-20T19:27:08Z] Started /health  request_id=pfzubX80NgvsHkk1--4G- method=GET client_ip=127.0.0.1
supabase-imgproxy | INFO    [2023-02-20T19:27:08Z] Completed in 135.587µs /health  request_id=pfzubX80NgvsHkk1--4G- method=GET status=200 client_ip=127.0.0.1
```

**Comment by ruggi99** [comment]
I don't get what you are stating.
I don't see anything wrong in the logs provided. I have the same logs and containers works perfectly.

Maybe you are meaning that the `/health` endpoint is called multiple times?
In that case it's normal because every about 10 seconds docker checks the health of its containers.

If they are not healthy then a error is reported.
As said Docker checks periodically not only when the container is started

**Comment by mauricev** [comment]
Are you suggesting that when I run sudo docker-compose up, it is normal for it to enter a loop forever? This means I need a foreground window open forever. Something just doesn’t seem right about this.

**Comment by mauricev** [comment]
Also, should I be able to reach the database from the command line of the host? I can’t.

**Comment by ruggi99** [comment]
Again, I can't understand for you are talking about.

As said, when healthcheck is enabled for a container, docker periodically checks if that container is responsive.
In that case it calls `/health` endpoint and if there's a response, the container is healthy.
Also from your logs there is no issue with healthchecks.

Don't understand what a foreground window open forever is for you, but maybe you are missing `-d` flag after `docker compose` that works in detached mode. If that's the issue you are facing, healthchecks have nothing to do with it.

You should provide more context if you're facing a particular issue. We can't help you if you only say "I can't".
Please provide screenshot or logs of the command you tried.

**Comment by mauricev** [comment]
Ah-ah, that’s funny, the minus d flag is missing. The page at https://supabase.com/docs/guides/self-hosting/docker is missing the -d flag next to “ docker compose up”, so that I would have never realized. Thank you for your help.

**Comment by ruggi99** [comment]
Not necessary missing in the code snippet but should be at least mentioned in the docs.

Please change the title of the issue to give the right context.

Also I hope you have fixed the issue with the connection with Postgres.

I suggest you next time to ask for help on discord. More people can help you that here in issues

**Comment by mauricev** [comment]
Thanks. I think the issue with postgres is that I’m trying to access with mysql and it needs psql instead.
