### ISSUE TITLE
CORS error in the Supabase Dashboard

### ISSUE THREAD

**Issue by FacuBozzi** [supabase/supabase#12563]
# Bug report

## Describe the bug
Can't add a Google Provider in the Supabase dashboard. Getting a CORS error on the request when I'm trying to save the changes.

## To Reproduce

1. Go to 'https://app.supabase.com/project/[project_url]/auth/providers'
2. Click to enable Google Provider
3. Insert Client ID and Client Secret
4. Save the changes

## Expected behavior

Changes should be saved and the google provider should be added.

## Screenshots

[Check this screenshot](https://user-images.githubusercontent.com/72771544/220184911-5aa1377b-cbe1-4fb0-a019-d323403e7f7e.png) that shows the error.

## System information

- Windows 11
- Google Chrome

## Additional context

I tried using 2 chrome CORS browser extensions but they didn't help.

**Comment by GaryAustin1** [comment]
No other users are reporting anything like this and I can enter info and save the Google auth info.
This likely a much more special case than your steps or your something unique to your environment.
Normally it is better to seek help in Discussions or Supabase Discord as more users are around to help out.
Not clear why you are using CORS extensions, but they have been known to cause issues if not set up correctly.

Are you having any other issues with the dashboard and CORS?  Anything else to narrow this down?

**Comment by FacuBozzi** [comment]
Just disabled the CORS extensions and everything works good! Guess that was the issue. Thank you very much. Closing now.
