### ISSUE TITLE
Auth race condition

### ISSUE THREAD

**Issue by TheBuilderJR** [supabase/supabase#12574]
# Bug report

## Describe the bug

Sometimes after login, Supabase auth will return null for the session

## To Reproduce

1. Login
2. Have some server side code that looks like this
```
    const supabase = createServerSupabaseClient({ req, res });
    const {
        data: { session }
    } = await supabase.auth.getSession();
```
3. Notice that session is sometimes (maybe 20%) null immediately after login

## Expected behavior

For step 3) I expect session to not be null

**Comment by GaryAustin1** [comment]
You might get more help in Supabase Discord on something like this.  It appears you are using auth-helpers and don’t show your browser client side code init and login.   Not much can be done to help with what you have shown.  Many auth-helpers issues are resolved there.

**Comment by TheBuilderJR** [comment]
Supabase discord is really hard to keep track of =/ I've posted 2 questions there already and can't find them anymore!

**Comment by TheBuilderJR** [comment]
Posted here https://discord.com/channels/839993398554656828/1006358244786196510/threads/1077886117036179458

**Comment by jonathanwilke** [comment]
I had the same problem and for me the solution was to invalidate the cache of the next.js router before navigating after signin.

https://github.com/supabase/auth-helpers/issues/446#issuecomment-1435720009

**Comment by bericyb** [comment]
I was having this same problem. getSession() was returning `null null`

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
