### ISSUE TITLE
Allow uploading base64 Images to Storage

### ISSUE THREAD

**Issue by NiketanG** [supabase/supabase#1257]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, for uploading a file (specifically Images)  to Supabase Storage, we have to use the File object. In some environments like React-Native, this isn't possible. 
This limits us from using Supabase Storage in React-Native Projects.

## Describe the solution you'd like

Allowing both File and String parameter in `upload()` method of storage can be used to upload files using both ways. 

```
const avatarFileBase64 = "data:image/png;base64,BASE_IMAGE"
const { data, error } = await supabase
  .storage
  .from('avatars')
  .upload('public/avatar1.png', avatarFileBase64)
```

**Comment by inian** [comment]
Hi @NiketanG, I haven't used React Native before but it seems to allow using File objects right - https://aboutreact.com/file-uploading-in-react-native/ ? This example shows using FormData to upload a file which is exactly [what supabase-js does](https://github.com/supabase/supabase-js/blob/e632f79156cc6e499db62e0f6b3e861856c90489/src/lib/storage/StorageFileApi.ts#L44) as well

**Comment by NiketanG** [comment]
My bad. I was using [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) which returns a path of the Image or the base64 equivalent. I couldn't find a way to obtain the File Object from the path or convert the base64 into File, thus the Feature Request. 

Although, I still think base64 support would be helpful in some cases, if not all. I might submit a PR to do so, if thats fine. But, for now my issue is resolved. Thank you.

**Comment by inian** [comment]
We will keep this in mind Niketan. Our first goal is to make storage uploads interoperable with Node by accepting Node streams or a Blob and look into base64 if there is still a need for it.

**Comment by Danieltech99** [comment]
Hey @NiketanG, I stumbled upon this thread while I was looking to do the same thing. I am using Ionic React with a platform native and web-native photo-picker plugin and needed to upload without a file object to Supabase. I also found this article: [https://devdactic.com/ionic-nest-image-upload-capacitor/](https://devdactic.com/ionic-nest-image-upload-capacitor/).

You can use a Base64 to Blog conversion function and then upload the blob and it works fine.

I used the conversion function listed in the blog article (which references the StackOverflow post):
```typescript
// https://devdactic.com/ionic-nest-image-upload-capacitor/
// https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript
function b64toBlob(b64Data: string, contentType = '', sliceSize = 512) {
  const byteCharacters = atob(b64Data);
  const byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    const slice = byteCharacters.slice(offset, offset + sliceSize);

    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  const blob = new Blob(byteArrays, { type: contentType });
  return blob;
}
```

**Comment by frpericacho** [comment]
Hi! I'm also trying to upload images to a bucket, using Expo, and like plain react native, expo doesn't have File objects. I tried the method that @Danieltech99 said, and from a blob create a File like this:

```ts
function b64toBlob(b64Data: string, contentType = "", sliceSize = 512) {
  const byteCharacters = decode(b64Data);
  const byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    const slice = byteCharacters.slice(offset, offset + sliceSize);

    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  const blob = new Blob(byteArrays, { type: contentType });

  return blob;
}

function getInfo(image: ImageInfo) {
  const filename = image.uri.split("/").pop()!;
  const ext = filename.split(".").pop()!.toLowerCase();

  return { mime: `image/${ext}`, ext, filename };
}

function base64ToFile(image: ImageInfo) {
  const { filename, ext, mime } = getInfo(image);

  const blob: any = b64toBlob(image.base64!, mime);
  
  return new File([blob], filename, { type: mime });
}
```
With this workaround I can have a File object, but when I upload the image, what happens is that an object is created in the bucket with the correct filename and extension but the size is 0. Doing a console.log before uploading I can see that the File size is different from 0. Any idea what may be happening? Thx

**Comment by alexandregiordanelli** [comment]
Buffer.from(variableWithData64.replace('data:image/png;base64,', ''), 'base64') on nodejs

**Comment by NiketanG** [comment]
> Buffer.from(variableWithData64.replace('data:image/png;base64,', ''), 'base64') on nodejs

Thanks, but the question is only for react-native environments, where Buffer is not available

**Comment by thebengeu** [comment]
Hey @Danieltech99, could you elaborate a bit on how you were able to get your method to work please?

I tried your method and I got a corrupted file uploaded on web, whereas on iOS I got an error `{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'fields' of undefined"}`. When I tried the method from @frpericacho, I got a corrupted file uploaded on web, whereas on iOS I got a size 0 file as @frpericacho mentioned.

We think that there's some interaction between `File` (or `Blob`) and/or `FormData` and/or `Fetch` that doesn't work as intended in React Native environments: the file data isn't being sent in the `multipart/form-data` body even with something as simple as `new File(['foo'], 'foo.png', {type: 'image/png'})`, while that works perfectly fine in browsers.

However, we added support for `ArrayBuffer` and other types earlier this week so there's an alternative. I've tested that the following works on both web and iOS in React Native environments:

```
import {decode} from 'base64-arraybuffer'

const { data, error } = await supabase.storage
  .from('avatars')
  .upload('test.jpg', decode('base64string'), {contentType: 'image/jpg'})
```

**Comment by NiketanG** [comment]
Thank you @thebengeu . It worked. In case anyone else is having the same issue where you have a file path on React Native, you can do this to upload to supabase storage.

Tldr: Use `rn-fetch-blob` to obtain base64 of Local File from path, and then convert it to Array Buffer using `base64-arraybuffer`

```
import RNFetchBlob from "rn-fetch-blob";
import { decode } from "base64-arraybuffer";

const imagePath = "file://0/cache/com.xyz/image.jpg";
const base64Image = await RNFetchBlob.fs.readFile(imagePath, "base64");

const arrayBuffer = decode(base64Image);
const { data, error } = await supabase.storage
	.from("avatars")
	.upload("image1.jpg", base64Image, { contentType: "image/jpg" });
```

You can obtain the Extension of File by taking the last 3 characters using `imagePath.slice(-3)` and passing this in the `contentType` for supabase storage when working with other file types.

**Comment by danielolamide** [comment]
Hey @NiketanG , I tried your sample code above but I keep getting 
`No such file file:///Users/xxxxx/Library/Developer/CoreSimulator/Devices/AA8A54A4-20BA-4E16-A847-5057BD3AAF8D/data/Containers/Data/Application/5A100B1C-5044-49AC-B3C4-F3AA9802068D/tmp/research.mp4'` and when I use the fileURI provided by `react-native-image-picker` I get the error `Cannot read property 'fields' of undefined`

**Comment by danielolamide** [comment]
I've been able to get over the no such error that `RNFetchBlob` was catching, I was looking in the wrong directory 😭. Although the `Cannot read propery 'fields' of undefined` has still persisted.

**Comment by thebengeu** [comment]
Hey @danielolamide, are you using @supabase/supabase-js 1.20.0? If so, I'm not sure why you'd be receiving that error if using `ArrayBuffer`, could you include a sample of your code please?

**Comment by danielolamide** [comment]
Hey @thebengeu, just updated my version I was on 1.18. So it's alright now. Thank you.

**Comment by mrmurphy** [comment]
I'm running into this again with `@supabase/supabase-js 1.20.0`, as well as `@supabase/supabase-js 1.22.6`. I've removed node modules and re-installed a number of times, deleted the expo client from my phone, and tried multiple different libraries for working with ArrayBuffers. I tried uploading Uint8Array, ArrayBuffer, and string, but I got the same error:

`{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'fields' of undefined"}` on all of them.
Anything I could be missing here?

**Comment by mrmurphy** [comment]
Ahh, I think this was a case of the project using Yarn, while I was using npm. When I ran `yarn` the new package was successfully installed, and my uploads started working.

**Comment by 10000multiplier** [comment]
Would be nice too if converting base64 wasn't necessary at all 😄

**Comment by stoplion** [comment]
I'm trying to upload from the camera. It's not working. I've tried to use something like this..

```
const reponse = await fetch(capturedPhoto.uri);
const photoImageBuffer = await reponse.arrayBuffer();

const { error: uploadError } = await supabase.storage
      .from("stuff")
      .upload(`/content_uploads/${fileName}`, photoImageBuffer);
```

and 

```
const reponse = await fetch(capturedPhoto.uri);
const blob = await reponse.blob();

const { error: uploadError } = await supabase.storage
      .from("fr8s")
      .upload(`/content_uploads/${fileName}`, blob);
```

`capturedPhoto.uri` is a `File:` path. 

When using array buffer, getting this..
`FileReader.readAsArrayBuffer is not implemented`

When using blob, error is..
```
Object {
  "error": "Internal Server Error",
  "message": "Cannot read property 'fields' of undefined",
  "statusCode": 500,
}
```

Is there examples out there, that use RN, camera  and supabase?

**Comment by vbylen** [comment]
@stoplion https://github.com/NiketanG/instaclone/blob/99aef86f5d8815c1caea6afcd0437350a95c02ca/src/hooks/useImageUpload.tsx

**Comment by jamesthesken** [comment]
Sorry to be resurrecting this old discussion.... The documentation you pointed to @Muntasir2001 was great and helped solve my issue for uploading the files. In the Supabase dashboard, the images are uploaded and I can view them. 

However, downloading these images are not working. Is there a better way to debug the image metadata in the storage buckets?

I ask because I have a web-app version of this application:

* Uploading images from the web-app can be downloaded again both on the web and mobile 
* Uploading images from the mobile-app _cannot_ be downloaded from either web or mobile
* Uploaded images from mobile appear in the storage buckets

Below is some relevant code showing how I pick and upload images from Expo:

```
const [imageFile, setImageFile] = useState<ImagePicker.ImagePickerAsset[]>(null)

// .....

const selectImage = async () => {
      let result = await ImagePicker.launchImageLibraryAsync({
        base64: true,
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1, 1],
        quality: 1,
      })

      if (!result.canceled) {
        setImageFile(result.assets)
      }
    }

// .....

 const blob = await uriToBlob(imageFile[0].uri)

        const fileExt = imageFile[0].uri.split(".").pop()
        const filePath = `${Date.now()}-test.${fileExt}`
        console.log(filePath)

        const { data, error: imageError } = await supabase.storage
          .from("photos")
          .upload(filePath, decode(imageFile[0].base64), {
            contentType: blob.type, // Pass the content type
          })
        if (data) {
          const url = data.path
          console.log("Upload url: ", url)
        }
        if (imageError) {
          console.log(imageError)
        }
```

Any ideas? Thank you for any help or guidance! @inian

**Comment by alipiopereira** [comment]
My solution: how to upload base64 image with supabase + nextjs 13
It has worked for me. If you find something that can be improved I'll be happy.🔥

```js
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";
import { Database } from "@/types/supabase";

const generateFileID = (): string => {
  let id = "";
  for (let i = 0; i < 6; i++) {
    id += Math.floor(Math.random() * 10) + 1;
  }
  return id;
};

const removeDataImagePrefix = (base64RemovePrefix: string): string => {
  return base64RemovePrefix.replace(/data:image\/png;base64,/i, "");
};

const base64ToImage = async (base64: string): Promise<string> => {
  const supabase = createClientComponentClient<Database>();

  const base64StringWithoutPrefix = removeDataImagePrefix(base64);

  const buffer = Buffer.from(base64StringWithoutPrefix, "base64");
  const fileID = generateFileID();

  const filePath = `avatar_${fileID}.png`;

  try {
    await supabase.storage.from("avatars").upload(filePath, buffer, {
      cacheControl: "3600",
      upsert: true,
      contentType: "image/png",
    });

    return filePath;
  } catch (error) {
    throw error;
  }
};

export default base64ToImage;
```
