### ISSUE TITLE
`postgres` role should have `select` permissions on tables created/managed by extensions

### ISSUE THREAD

**Issue by jaredramirez** [supabase/supabase#12588]
# Bug report

## Describe the bug

Hey there, I'm trying to create a table of normalized address using the extensions `address_standardizer`, `address_standardizer_data_us`, and `postgis` in the `extensions` schema and `postgis_tiger_geocoder` in the `tiger` schema. I can access the schemas & functions, but not tables in the schema.

For example, with the following query:
```sql
> SELECT tiger.pprint_addy(tiger.pagc_normalize_address('710 E Ben White Blvd, Austin, TX 78704'));

ERROR:  permission denied for table street_type_lookup
CONTEXT:  SQL function "is_pretype" statement 1
PL/pgSQL function pprint_addy(norm_addy) line 9 at assignment
```

And indeed, if I try to select directly from the table in question I do not have permissions.
```sql
> select * from tiger.street_type_lookup;

ERROR:  permission denied for table street_type_lookup
```

I'm connected to the database as the `postgres` user. And, as there is no access to the DB superuser, I cannot grant `postgres` select access to the tables.

This problem does not occur on local setup using supabase-cli, only on cloud supabase instances.

Also, this issue occurs with tables created by `address_standardizer_data_us`. One of these tables is called `us_lex`.

## To Reproduce

Create a new supabase project, connect via psql, then run:

```plpgsql
BEGIN;

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE SCHEMA IF NOT EXISTS private;
CREATE SCHEMA IF NOT EXISTS tiger;

CREATE EXTENSION IF NOT EXISTS address_standardizer WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS address_standardizer_data_us WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;

SELECT tiger.pprint_addy(tiger.pagc_normalize_address('710 E Ben White Blvd, Austin, TX 78704'));

ROLLBACK;
```

## Expected behavior

I expect to have select permissions on tables in added extensions.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by burggraf** [comment]
If I create the extensions using the Supabase Dashboard toggles here: [https://app.supabase.com/project/_/database/extensions](https://app.supabase.com/project/_/database/extensions) I seem to have select access to the tables.  So using the Supabase CLI to create the extensions seems to be the problem here.
