### ISSUE TITLE
SQL Editor - Can't Rename or Delete SQL snippets with very long names

### ISSUE THREAD

**Issue by gefgu** [supabase/supabase#12603]
# Bug report

## To Reproduce

1. Create an SQL snippet with a very long name
2. Try to Edit
3. You will not find the edit dropdown.

## Expected behavior

I want the edit/delete dropdown to appear.

## Screenshots

![image](https://user-images.githubusercontent.com/53129852/220618326-bf83a5ab-9fd4-465f-baaf-ffe67a8af113.png)

## System information

- OS: Ubuntu
- Browser (if applies) Firefox

## Additional context

I would like to fix this issue.

It looked like a typo: `w-fullw-44`
![image](https://user-images.githubusercontent.com/53129852/220621810-2ce5aa2d-b107-476c-8003-126b7f63ff23.png)

**Comment by JulienLecoq** [comment]
Following that, it would be a very good addition to be able to expand the sidebar. I find it annoying to have to put the cursor on the sidebar items and wait a few seconds to know the name of my tables for example (for the tables that have a long name).

**Comment by Hallidayo** [comment]
Hi @JulienLecoq - Could you send a screenshot or video of what you are experiencing?

**Comment by JulienLecoq** [comment]
On the sidebar on the left, you can see that the table name is cropped. When you have multiple tables with similar name (the start of the name), you can't differentiate the tables visually. You have to put your cursor on the table name and wait something like 2/3 seconds for the full table name to appears in a popup.

<img width="1728" alt="screenshot_supabase_ui" src="https://user-images.githubusercontent.com/54070985/221001441-961e877a-f68a-4099-bf4c-5d018d8c9c50.png">

I would like to have the possibility to stretch the sidebar as some website/application does, for example the prontonmail website allows to do that. That would allows to see the full table name without having to do the manipulation I mentioned earlier. (while stretching the "bar" of the sidebar becomes pink on my Protonmail instance)

<img width="1725" alt="proton_ui" src="https://user-images.githubusercontent.com/54070985/221003610-2ab8839a-397a-4636-b736-3e87e08d1bbd.png">

**Comment by gefgu** [comment]
@JulienLecoq maybe you can add this as a feature request in the discussions tab - I think creating an issue is better for bugs. I will close this issue now because it is solved :)

**Comment by JulienLecoq** [comment]
@gefgu Done, I created a feature request :)
