### ISSUE TITLE
Auto-generated id after bulk insertion

### ISSUE THREAD

**Issue by donghoon-song** [supabase/supabase#12628]
# Bug report

## Describe the bug

I has inserted 3000 data using csv file when I created the table. After that, when I insert a new data into table, auto-generated id starts with 1. I think it should be 3001.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

Auto-generated id starts with 3001.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by madsbuch** [comment]
Why has this been closed without a comment?

It appears ti still be happening?
