### ISSUE TITLE
Supabase Edge Function not supporting Hono.js

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#12629]
I tried using [Hono.js](https://hono.dev/) with the edge function but it failed to work.

Function Code:
```
import { Hono } from 'https://deno.land/x/hono@v3.0.1/mod.ts'
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

console.log('Notion Parser Method Functions!')

const app = new Hono()

app.get('/', (c) => c.text('Hello Deno 123!'))

serve(app.fetch)
```
The code is building but giving a `404 Not Found` error both locally and after deployment.

While same code is working fine on deno deploy.
<img width="1440" alt="Screenshot 2023-02-23 at 5 31 55 PM 1" src="https://user-images.githubusercontent.com/61496865/220902784-cd802cb0-da6d-4380-bd1a-a351a0f2b0f2.png">

One more question I have "I assume that supabase use deno deploy under the hood then if something works on deno deploy then it should work edge functions also" Does my assumption incorrect? Does supabase work slightly differently from deno deploy?

**Comment by laktek** [comment]
@Akash187 You cannot match the root path inside edge functions. You must prefix the path with your function name.

Try, this instead:

```
app.get('/your-function-name', (c) => c.text('Hello Deno 123!'))
```

**Comment by Akash187** [comment]
Thanks, @laktek it worked.
One more question I have "I assume that supabase use deno deploy under the hood then if something works on deno deploy then it should work edge functions also". Does my assumption correct?

**Comment by laktek** [comment]
it uses Deno Deploy to run functions but there may be differences in the runtime APIs.

Closing this issue since it works.
