### ISSUE TITLE
Error on try to set auth token 

### ISSUE THREAD

**Issue by YaroslavKharchenko0** [supabase/supabase#12636]
# Bug report

## Describe the bug

On my platform, authorization is done through firebase, I use supabase as a database and I want to use the rls, but in order for the rls to work correctly, I need to insert a token. When I do this I get the user not found error. Is there any way I can get around this problem or do I have to register the user in supabase ? 

## Expected behavior

I want to get access to supabase without register user in supabase

## Screenshots
![image](https://user-images.githubusercontent.com/82085991/220987647-7a293ad1-49f3-4573-a0b6-b00e4bcf808c.png)
![image](https://user-images.githubusercontent.com/82085991/220987702-ab3106ea-f038-4f00-bf4d-14aaa2f69a5f.png)
![image](https://user-images.githubusercontent.com/82085991/220988467-dd650877-cbc6-47a2-b5c4-69d4efd89686.png)
![image](https://user-images.githubusercontent.com/82085991/220989097-120b974e-a7aa-436d-98ea-86536a9878aa.png)

## System information
- OS: [Windows]
- Version of supabase-js: 2.8.0

**Comment by YaroslavKharchenko0** [comment]
Okay, sorry

**Comment by MbeleLebohang-uct** [comment]
@YaroslavKharchenko0 Did you get the answer? I am having the same issue
