### ISSUE TITLE
Clippy (OpenAI/GPT) search gives a link that returns 404

### ISSUE THREAD

**Issue by rohan-kadkol** [supabase/supabase#12663]
# Improve documentation

## Link 

N/A

## Describe the problem

When trying the below query into the Clippy (OpenAI/GPT) search, it gives a link with more information. But clicking on that link returns a 404 error.

```
What curl command to use to perform reads on table
```

![image](https://user-images.githubusercontent.com/45748283/221321359-8ef1f169-5ebf-482c-8bd3-575021cad689.png)
![image](https://user-images.githubusercontent.com/45748283/221321434-ae3555d7-79dc-4a1f-83eb-6f9fa85c525e.png)

## Describe the improvement

The provided link for this prompt should be correct.

## Additional context

N/A

**Comment by SJ-Kumar** [comment]
Please let me know if I can handle this update in docs.

**Comment by gregnr** [comment]
@rohan-kadkol Thanks for the submission. We've taken a look and it appears this is caused by a stale data issue when generating the embeddings. Will keep this thread updated as we make progress!

**Comment by gregnr** [comment]
@SJ-Kumar Thanks for offering! This one is going to take a bit more thought than normal as it involves a bunch of moving pieces including stale DB data. I'll let you know if anything comes up that you can jump on!
