### ISSUE TITLE
Unable to bypass RLS from a Next.js API route (Supabase Webhooks)

### ISSUE THREAD

**Issue by sambowenhughes** [supabase/supabase#12667]
# Bug report
## Describe the bug

`Apologies if this in not a bug and is expected behaviour. `

I'm triggering my Next.js API/route using Supabase webhooks whenever there's been an insert into my profiles table. My API/route takes the user ID and email from the profiles table and creates a customer in my Stripe dashboard. Once the Stripe customer has been returned by Stripe in my API/route, I'm then wanting to update the stripe_customer column in the profiles table with my Stripe customer ID.

The problem is that I have RLS set on my table. I'm trying to use the createSupabaseServerClient() helper to get my session, but because the request is coming in from the Supabase webhook, there is no active session information.

Is this expected behavior? And if so, how do I bypass the RLS within a Next.js server component to update my profiles table?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Call a Next.js API route using the Supabase HTTP webhooks
2. Within the Next.js API route use the `createSupabaseServerClient()` method to get the current session
3. Notice the session is coming back as null

## Expected behavior

I expect to be able to at least get the active session, or use the service key to bypass any RLS.

## System information

N/A

## Code Snippet
<img width="716" alt="Screenshot 2023-02-25 at 10 20 29" src="https://user-images.githubusercontent.com/23152623/221331166-a5095eaa-85fa-4ce1-9a30-73c9c9ceeedd.png">

**Comment by GaryAustin1** [comment]
You can just use Supabase.js normal client with service role. On server set persistSession to false when you creat the client.

**Comment by sambowenhughes** [comment]
Thanks @GaryAustin1 that works. For anybody interested this is my code:


<img width="435" alt="Screenshot 2023-02-26 at 10 50 34" src="https://user-images.githubusercontent.com/23152623/221389568-2923aad5-5416-484d-ac79-a03c56df61d0.png">
