### ISSUE TITLE
Unable to Bypass RLS with Service Role

### ISSUE THREAD

**Issue by devinshoemaker** [supabase/supabase#12669]
# Bug report

## Describe the bug

I am attempting to write an e2e test using Cypress that deletes a user after testing signup. In the `afterEach` of my e2e test I configure a Supabase client with the service role key, but when I query my `user` table with RLS enabled then no results are returned. If I disable RLS then it works as expected. I also tried to add a policy to this table for selecting that would always be true for `service_role` and `anon` roles and I still get no results with RLS enabled.

## To Reproduce

```
git checkout https://github.com/devinshoemaker/cube-trainer
git switch auth-bak
npm install
npx supabase start
nx e2e cube-trainer-e2e
```

## Expected behavior

The Supabase client should bypass RLS and return the user in the database.

## System information

- OS: macOS
- Browser: Electron (Cypress)
- Version of supabase-js: 2.8.0
- Version of Node.js: 16.19.0

## Additional context

I have tried this against local and hosted Supabase and get the same result. I feel like I'm likely doing something wrong here, so any help would be appreciated. This setup is so close to a great testing experience, and I appreciate all the work from the team!

**Comment by devinshoemaker** [comment]
I was able to solve my issue with a different approach using Cypress (`cy.exec(npx ts-node <my-file.ts>)` if anyone is curious) and things seem to be working as expected. I'm not sure why running these Supabase commands directly in the Cypress tests causes problems, but I'll leave this issue up in case anyone wants to take a look.

**Comment by GaryAustin1** [comment]
I'm going to close this.  I commented on your Discord discussion on a likely issue in your code and the fact it does not work on both self hosted and a Supabase hosted instance points to your code as the issues as service_role seems to be working fine else where.

If you have more info, this can be re-opened or dealt with in Discord.
