### ISSUE TITLE
[Cloud] Application Storage does not clear when switching users

### ISSUE THREAD

**Issue by lalalune** [supabase/supabase#12670]
# Bug report
I use Supabase with multiple accounts on the cloud.

When I switch from one user to the other, my workspaces are corrupted. The only way to uncorrupt is to delete my local application storage and log back in.

Steps to reproduce:
To go cloud
Log in with one account using Github, then log out
Log in with another account, using email -- still seeing the org for the first account, with access errors

Tested on Chrome and Safari, the bug is consistent

**Comment by matthewwong525** [comment]
Potential related Issues / PRs:

- [Corrupted account settings prevent normal functioning across the whole account](https://github.com/supabase/supabase/issues/2432): This issue describes a similar problem where the account settings are corrupted and causing various errors and preventing normal functioning. It provides steps to reproduce the behavior and includes screenshots of the errors. Understanding how the account settings can become corrupted may help in diagnosing and resolving the issue with application storage not clearing when switching users.

This message was generated by AI from www.triagetickets.com

**Comment by saltcod** [comment]
What pages are you experiencing this issue on @lalalune ?

**Comment by encima** [comment]
Closing this as there has not been a response. 

Please do comment if this still occurs for you and we will reopen. Alternatively, please contact support with screenshots and your Project refs
