### ISSUE TITLE
Wrong name for Prisma datasource property

### ISSUE THREAD

**Issue by Aaron3219** [supabase/supabase#12674]
# Improve documentation

## Link 

[Docs](https://supabase.com/docs/guides/integrations/prisma#connection-pooling-with-supabase)

## Describe the problem

In your [documentation](https://supabase.com/docs/guides/integrations/prisma#connection-pooling-with-supabase) you write:

> Update your Prisma schema by setting the directUrl in the datasource block:
> ```
> datasource db {
>   provider          = "postgresql"
>   url               = env("DATABASE_URL")
>   directURL         = env("DIRECT_URL")
>   shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
> }
> ```

However, this leads to errors when migrating:
> `error: Property not known: "directURL".`

This is because according to the [Prisma documentation](https://www.prisma.io/docs/getting-started/quickstart), `directURL` is actually `directUrl`.

## Describe the improvement

Updated documentation:

> Update your Prisma schema by setting the directUrl in the datasource block:
> ```
> datasource db {
>   provider          = "postgresql"
>   url               = env("DATABASE_URL")
>   directUrl         = env("DIRECT_URL")
>   shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
> }
> ```

**Comment by SJ-Kumar** [comment]
Please let me know if I can handle this update.
