### ISSUE TITLE
Image transformations not working properly

### ISSUE THREAD

**Issue by rtman** [supabase/supabase#12728]
# Bug report

## Describe the bug

Image transformations that were working fine across browsers a few days ago are now being being cropped weirdly.

See the attached images.

I'm using the supabaseLoader:
```
export default function supabaseLoader({ src, width, quality }) {
  return `https://${
    process.env.NEXT_PUBLIC_SUPABASE_STORAGE_HOSTNAME
  }/storage/v1/render/image/public/${src}?width=${width}&quality=${quality || 75};
}
```

Here is how I'm rendering the image:

```
            <Image
              alt="logo"
              height={0}
              priority={true}
              src={`${getOrgAssetsUrl(orgId)}/org-logo.png`}
              width={LOGO_WIDTH}
            />
```

## To Reproduce

Try using image optimization with the supabase loader in any browser

## Expected behavior

Image optimization should not crop images like this but retain their shape.

## Screenshots
![Screen Shot 2023-02-27 at 2 24 42 PM](https://user-images.githubusercontent.com/20849135/221962834-ab8cb524-decf-476c-b914-9f35029390a0.png)

![Screen_Shot_2023-02-27_at_2 28 23_PM (1)](https://user-images.githubusercontent.com/20849135/221963255-86471486-d400-4234-a033-a447807b7979.png)

## System information

- OS: 12.5 (21G72)
- Browser: 
     Safari: Version 15.6 (17613.3.9.1.5), 
     Chrome: Version 110.0.5481.177 (Official Build) (arm64) 
     Brave: [Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (arm64)](https://brave.com/latest/)
- Version of supabase-js:   "@supabase/supabase-js": "2.3.0",
- Version of Node.js:v16.16.0

**Comment by rtman** [comment]
Updated the description from just being a safari issue, because after forcing our app to pull fresh resources from supabase it is happening in all browsers.

**Comment by rtman** [comment]
It looked like a resize issue so we tested adding `&resize=contain` to the url query params that fixed it. Maybe supabase started enforcing the default resize param of cover recently? This wasnt needed for the last few weeks.

**Comment by rtman** [comment]
to clarify I mean this

```
export default function supabaseLoader({ src, width, quality }) {
  return `https://${
    process.env.NEXT_PUBLIC_SUPABASE_STORAGE_HOSTNAME
  }/storage/v1/render/image/public/${src}?width=${width}&quality=${quality || 75}&resize=contain`;
}

```

**Comment by fenos** [comment]
Glad you found the `resize=contain` option, we always defaulted to cover.
Probably you had images that were still able to keep the correct aspect ratio even with using the `cover` default method

Closing for now! 👍
