### ISSUE TITLE
Can't access to my supabase database.

### ISSUE THREAD

**Issue by tom-laplace** [supabase/supabase#12737]
# Bug report

## Describe the bug

Prisma or PGAdmin can't access to my Supabase database.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase and deploy a Postgres database
2. Try to access to your database with Prisma or PGAdmin

## Expected behavior

Expected: can connect
Actually: can't connect

```Error: P1001: Can't reach database server at `db.ctvmbxpqktlctvdeypss.supabase.co`:`6543`

Please make sure your database server is running at `db.ctvmbxpqktlctvdeypss.supabase.co`:`6543`.```

## System information

- OS: Windows using WSL2 (Ubuntu 22.04)
- Version of Node.js: 19.6.0
- Version of Prisma: 4.10.1

**Comment by aaadryyy** [comment]
Are you in Europe ? Looks like there is an issue with the auth service https://status.supabase.com/.

**Comment by tom-laplace** [comment]
Nop, us-east-1

**Comment by tom-laplace** [comment]
lmao it was because I was using my school wifi
