### ISSUE TITLE
Supabase dashboard not loading on Chrome

### ISSUE THREAD

**Issue by itsthesteve** [supabase/supabase#12733]
# Bug report

## Describe the bug

Loading either app.supabase.com or locally results in an endless progress load. I wish I had more information, but my pinned tab with the local dashboard stopped loading sometime between a few days ago and today (Feb 28). The dashboard on app.supabase.com has also since stopped loading. Just the supabase logo progress indicator.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Load either local or supabase dashboards on Chrome 110.0.5481.100

## Expected behavior

Dashboard should load.

## Screenshots

Some warnings from app.supabase.com

<img width="715" alt="Screen Shot 2023-02-28 at 9 48 14 PM" src="https://user-images.githubusercontent.com/2624740/222047750-ddaa7372-06a6-4fef-9fda-7e0df27d515c.png">

Firefox seems to load locally, however.

## System information

```
  System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 44.20 MB / 16.00 GB
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.4.2 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.0
  npmPackages:
    supabase: ^1.40.1 => 1.40.1
```

**Comment by aaadryyy** [comment]
Are you in Europe ? Looks like there is an issue with the auth service https://status.supabase.com/.

**Comment by itsthesteve** [comment]
Thanks @aaadryyy, I should have added some more info. I'm in US central.

I've tried clearing all cookies, logging out/back in, etc. 

The localhost supabase (`supabase start`) dashboard loads fine in Firefox, but app.supabase.com and the local supabase localhost refuse to load in Chrome with the warnings in the above screenshot.

**Comment by aaadryyy** [comment]
No problem @itsthesteve.
Maybe this issue #12724 can help you then.

>From support:
"Thank you for contacting Supabase Support. Recently we had to modify the type of the phone and phone_change columns in auth.users which requires any triggers or views dependent on those columns to be recreated. You can fix this problem by recreating (dropping then adding again) the triggers that were using these columns."

**Comment by MildTomato** [comment]
The configcat warnings are probably unrelated

**Comment by MildTomato** [comment]
@itsthesteve have you had any problems since. I think new versions of studio have been released since this issue was first created.

**Comment by itsthesteve** [comment]
Yep, no more issues. This can be closed.

**Comment by ndvalkov** [comment]
In my case what fixed it was clearing browser data with Auto-fill form data and Site settings checked. Recreating all triggers from another browser did nothing.

**Comment by harshalone** [comment]
I am facing the same issue today 20 august 2024

**Comment by MarkTheRobloxGuy** [comment]
Facing the same issue also

**Comment by MarkTheRobloxGuy** [comment]
Nevermind, fixed with a quick reinstall of Chrome
