### ISSUE TITLE
Unable to search docs with query: pagination

### ISSUE THREAD

**Issue by Frontend-io** [supabase/supabase#12765]
Hi! i think the recommendation section of the search is broken. Sorry I haven't got lots of information at this time. 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/32682002/222394512-735b3df0-0946-47ce-807c-4610f382abf2.png">

**Comment by saltcod** [comment]
Hi all, thanks for this report. Improvement is coming here very soon! Please stay tuned =)

**Comment by Frontend-io** [comment]
Thanks all
