### ISSUE TITLE
Docs: Javascript client's setSession page has a few issues

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase#12777]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-setsession

## Describe the problem

- There's some wording which implies you only need a `refresh_token` to use this method - which is the legacy way. This is also in the Notes section drop-down.
- This sentence - `setSession` takes in a refresh token and uses it to get a new session. - is probably not correct. I don't believe this method exists to get a new session, as that's what `refreshSession` now does, but literally sets the session for the supabase client. Any session refresh which happens from `setSession` is almost more of a sidebar courtesy, rather than the main purpose of the method.

## Describe the improvement

Just clear up a few inconsistencies.

**Comment by pratik2204** [comment]
@j4w8n can you assign this to me

**Comment by j4w8n** [comment]
@pratik2204 I don't have those kinds of powers here 🙂

**Comment by gregnr** [comment]
Thanks for reporting @j4w8n.

cc @supabase/auth for comments/confirmation
