### ISSUE TITLE
Error with supabase-db container (docker, self-hosting)

### ISSUE THREAD

**Issue by gab-luz** [supabase/supabase#12788]
# Bug report

## Describe the bug

Supabase UI is forever trying to connect to default project. When I check the supabase-db (a docker container) logs  I get the following error:

194.62.19.78 2023-03-03 08:48:07.956 UTC [791] postgres@postgres DETAIL:  Connection matched pg_hba.conf line 91: "host  all  all  0.0.0.0/0     scram-sha-256"
194.62.19.78 2023-03-03 08:48:08.843 UTC [792] postgres@postgres FATAL:  password authentication failed for user "postgres"

I've correctly edited the .env file with my external ip address where it was necessary.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to docker container supabase-db's logs
2. See the error above

## Expected behavior

My supabase ui should connect to supabase-db

## System information

- OS: ubuntu 22.04
- Browser: firefox
- Version of supabase-js: latest, from git
- Version of Node.js: not using it yet

**Comment by homanp** [comment]
Experiencing the same issue. Removed all docker images and pulled them again but still the same. 

Did you find any solution to this @gab-luz?

**Comment by Battlelamb** [comment]
did you config the kong.yml too?

You must pass the same anon_key and SERVICE_ROLE_KEY. hope it helps :)

**Comment by clonecorp** [comment]
Same here. Restarted my VM, and tried to modify the postgres user password as well to match the one in the .env file but the error persists.

I can still access the Supabase studio and connect to my database with a connection string (which uses the exact same password I have set) but the errors in the log that OP wrote are still appearing.

**Comment by sweatybridge** [comment]
For those who tried restarting / fresh install, do you see these logs from the supabase_db container?
```
supabase-db                     |
supabase-db                     | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db                     |
```

If so, perhaps the migration that sets the postgres password was skipped during startup. You need to reset the pgdata directory by `rm -rf docker/volumes/db/data`. Note that it will erase any data currently stored in your self-hosted postgres database. But if you are already doing a fresh install, I assume this wouldn't be problem.

**Comment by gab-luz** [comment]
> Experiencing the same issue. Removed all docker images and pulled them again but still the same.
> 
> Did you find any solution to this @gab-luz?

So far no luck. I've ended up using postgresql directly. If someone fixes that, I'll try supabase again.

**Comment by gab-luz** [comment]
> did you config the kong.yml too?
> 
> You must pass the same anon_key and SERVICE_ROLE_KEY. hope it helps :)

Yes. I did that.

**Comment by clonecorp** [comment]
> If so, perhaps the migration that sets the postgres password was skipped during startup. You need to reset the pgdata directory by `rm -rf docker/volumes/db/data`. Note that it will erase any data currently stored in your self-hosted postgres database. But if you are already doing a fresh install, I assume this wouldn't be problem.

This happens when restarting the db with ```sudo docker-compose down``` and ```sudo docker-compose up```
I have data in my database so clearing the data folder is definitely not the solution. The ```postgres``` user has the correct password since I can access the database with a psql connection string, something is wrong with the docker. What's triggering this message in the first place to start with? Even after trying to reset the password using ```ALTER USER postgres WITH PASSWORD 'new_password';``` the error messages keep appearing over and over.

**Comment by NickEdinburgh** [comment]
October '23 and same problem. No solution?

**Comment by mschinis** [comment]
I have the same issue. is there any workaround for this?
