### ISSUE TITLE
Copy cell content not working - Dashboard

### ISSUE THREAD

**Issue by gabrielsestrem** [supabase/supabase#12791]
# Bug report

When navigating in the table editor, if I want to copy a specific cell content, the ctrl + c command it's not working. Even if I do right click and click on "Copy cell content" it does not work.

Open any table in the table editor. Pick any cell, right click and choose: "Copy cell content". The content it's not being copied to the clipboard.

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open any table in the table editor
2. Pick any cell, right click and choose: "Copy cell content"
3. The content it's not being copied to the clipboard

## Screenshots

![image](https://user-images.githubusercontent.com/26584189/222713743-d10a1d66-7c01-42b5-a185-6284d841e970.png)

## System information

- OS: macOS and Windows
- Browser: chrome

**Comment by Gautam-Arora24** [comment]
@gabrielsestrem Have you tried with multiple browsers because I can easily copy the content using `Copy Cell Content` button on both Chrome and Safari.

**Comment by gabrielsestrem** [comment]
Now it's working again. I think they fixed pretty quick
