### ISSUE TITLE
Unable to search docs with query: sveltekit

### ISSUE THREAD

**Issue by sbrennan213** [supabase/supabase#12795]
I can find an example for using supabase with sveltekit via Google, but the internal search returns no results.

**Comment by aaadryyy** [comment]
Can you give more details @sbrennan213?

Working fine to me:
<img width="790" alt="Screenshot 2023-03-09 at 00 29 58" src="https://user-images.githubusercontent.com/20040637/223876312-f5c0eabc-264f-49da-a067-177e835be8ad.png">

**Comment by gregnr** [comment]
@sbrennan213 This should be solved with the [latest improvements](https://github.com/supabase/supabase/pull/12506) to search. Closing this now, but feel free to reopen if you're still experiencing issues.
