### ISSUE TITLE
Running prisma migration against supabase throws error(with multiSchema)

### ISSUE THREAD

**Issue by samuel-antwi** [supabase/supabase#12799]
<img width="385" alt="supabase-error" src="https://user-images.githubusercontent.com/29069653/222798002-b053a5b0-ff31-4090-a809-4cde78b45087.png">

Are there any settings I am missing inside supabase? I am NOT using a shadow database just the Connection string.

**Comment by GaryAustin1** [comment]
You would probably be better off asking for help in discussions or Supabase Github.
I'm going to guess you are using the bouncer port for migrations and you are supposed to use the standard database port for that, but I don't use Prisma.

https://supabase.com/docs/guides/integrations/prisma
