### ISSUE TITLE
Dropdown menu UI icon overlapping text in dashboard

### ISSUE THREAD

**Issue by SeansC12** [supabase/supabase#12804]
# Bug report

## Describe the bug

In a dropdown menu UI icon, there is an overlap of the text and the arrow icon.

## To Reproduce

1. Go to a new project
2. Go to user auth section
3. Click "Users"

## Expected behavior

There is no overlap

## Screenshots

<img width="94" alt="image" src="https://user-images.githubusercontent.com/88256324/222892326-7a0401d7-a5c2-4956-b02f-cbde5bf436f7.png">

<img width="1440" alt="Screenshot 2023-03-04 at 5 48 04 PM" src="https://user-images.githubusercontent.com/88256324/222892398-ac38181d-1fff-4318-b035-86b772a0366f.png">

## System information

- OS: macOS

**Comment by Hallidayo** [comment]
Hi @SeansC12 - Just had a check and this seems resolved now:

<img width="234" alt="Screenshot 2023-03-29 at 20 46 30" src="https://user-images.githubusercontent.com/22655069/228650831-6256fc9a-6b31-4e1f-ab3b-e4431001f024.png">

**Comment by SeansC12** [comment]
That is great. Thanks for notifying me @Hallidayo.
