### ISSUE TITLE
One of the quick-start examples for using Supabase with NextJS is broken

### ISSUE THREAD

**Issue by aelsaman** [supabase/supabase#12805]
# Improve documentation

## Link 

https://github.com/supabase/supabase/tree/master/examples/user-management/nextjs-ts-user-management

## Describe the problem

One of the quick-start examples for using Supabase with NextJS is broken as below. 

Basically, there are two options to follow the steps. The first option is by clicking on the "Deploy" button to automatically deploy the example on Vercel. The second option, which is broken, is to clone/build/deploy locally which is broken at the step of `npx create-next-app -e with-supabase`.  Apparently `create-next-app` is no longer maintaining this template `with-supabase` in their [repo](https://github.com/vercel/next.js/tree/canary/examples)

## Describe the improvement

Either maintain this starter template on NextJS side`create-next-app` or, update Supabase docs related to this example step to clone this example [subdirectory](https://github.com/aelsaman/supabase-nextjs-quickstart#build-locally) manually instead of using NextJS cli `create-next-app` 

## Additional context
<img width="710" alt="CleanShot 2023-03-04 at 16 35 08@2x" src="https://user-images.githubusercontent.com/1544585/222908369-9f8ed37f-ddfe-4a07-8ace-fe1ee6f4fe9f.png">

**Comment by lritter79** [comment]
Still broken as off writing this

**Comment by gregnr** [comment]
@silentworks any ideas/background on the `with-supabase` example?

**Comment by aelsaman** [comment]
the quick start example has been updated/replaced in Supabase docs. Thnx
