### ISSUE TITLE
getSession() returns the user even if the user is deleted

### ISSUE THREAD

**Issue by ItayElgazar** [supabase/supabase#12815]
# Bug report

Using server-side components in my Next.js project, I am using `supabase.auth.getSession()` at the layout level to verify that the user is not null (I access the `.data.session.user`.  However, I noticed that even after deleting the user from the supabase dashboard, the user was still present in the session. As a temporary solution, I switched to supabase.auth.getUser(), which appears to have resolved the issue.

## Describe the bug

Deleting the user from Supabase dashboard doesn't seem to remove the user object from `getSession()`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to supbase dashboard, Authentication page
2. delete a logged in user

## Expected behavior

`supabase.auth.getSession().session.user` needs to be `null`

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 2.0.4
- Version of Node.js: 16.10.0

**Comment by GaryAustin1** [comment]
There is no communication to your client from the server.  So the client does not know you have deleted the user until you make a call to the server.  getSession() normally does not go to the server unless the jwt is expired.  getUser() DOES call the server every time.

**Comment by ItayElgazar** [comment]
So, it means that currently, there is no way to logout of the user if the user was deleted without a refresh?

**Comment by GaryAustin1** [comment]
Supabase is a REST API.  There is no communication back to the client, unless you set up something thru realtime.

**Comment by ItayElgazar** [comment]
Makes total sense now. Thanks for the clarification.
