### ISSUE TITLE
Enhance the <title> tag on dashboard pages

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#12818]
We could enhance the <title> tag with more useful & contextual information. 

1. We could probably add the org name  everywhere 
2. Add the current table name when in the editor 
<img width="938" alt="CleanShot 2023-03-05 at 20 36 37@2x" src="https://user-images.githubusercontent.com/105593/222994047-fa581412-849f-4035-9b7e-c3c2ffcd9af4.png">

Per a great suggestion from https://twitter.com/blackevilgoblin/status/1632412048733663232

**Comment by Vishruta-Patil** [comment]
Can I work on this issue ?

**Comment by saltcod** [comment]
Yeah sure @Vishruta-Patil ! Thanks!

**Comment by Vishruta-Patil** [comment]
@saltcod On local, default project is not getting connected. Due to which I'm not able to access table editor.

**Comment by Vishruta-Patil** [comment]
![supabase-error](https://user-images.githubusercontent.com/72292532/223361175-556dcefe-485b-494b-b22f-1be71cfde189.PNG)

Permissions is disabled

**Comment by aaadryyy** [comment]
I asked for help [here](https://discord.com/channels/839993398554656828/1083334583384297562).

**Comment by saltcod** [comment]
@gitstart going to tackle this one — thanks @gitstart !

**Comment by gitstart** [comment]
Thanks @saltcod.

**Comment by gitstart-supabase** [comment]
Thanks @saltcod.
