### ISSUE TITLE
Bucket column issues

### ISSUE THREAD

**Issue by mosnicholas** [supabase/supabase#12825]
# Bug report

I'm trying to add a new bucket, and constantly getting the following error:
<img width="404" alt="Screenshot 2023-03-06 at 2 16 58 AM" src="https://user-images.githubusercontent.com/3606778/223043404-c12ef4ee-0a60-49bf-a42c-9f5dacb79d00.png">

I've tried restarting the project to no avail.

## To Reproduce
Simply try and add a new bucket to the storage.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
Does not seem like a policy issue.
There was a recent change that added some new rows to the storage.objects table.
![image](https://user-images.githubusercontent.com/54564956/223156668-cff7dc25-1ea3-4ded-80bd-652e7a09e4c5.png)

Not sure though how you are caught up in the change.  I am able to create buckets with the new table format on an older instance and a newer instance in the dashboard UI.

Maybe ctrl-f5 your dashboard to make sure it is latest code.  

Is this local or Supabase hosted?

**Comment by mosnicholas** [comment]
@GaryAustin1 this is on staging — hosted instance. 

Fwiw for some reason I saw this on my latest migrations file
![9807642B-3856-4F16-BCC3-834FA86EA106](https://user-images.githubusercontent.com/3606778/223159803-ca640ee5-0d15-4a45-ab8c-ec13a6e4c325.png)

**Comment by GaryAustin1** [comment]
So I am going to guess you are migrating from an instance that does not have those columns yet and it is removing them on the other instance.  Are you supposed to migrate auth and storage?  Sorry I don't use migration.

**Comment by mosnicholas** [comment]
@GaryAustin1 got it. I didn’t write that migration file, it came out of running supabase db diff —use-migra. :(

thanks for your help
