### ISSUE TITLE
Supabase ignores additions to raw_app_metadata

### ISSUE THREAD

**Issue by ChrisPaliqaw** [supabase/supabase#12823]
# Bug report

## Describe the bug

Supabase ignores additions to raw_app_metadata, failing to insert them into the app_metadata of the JWT - only provider and providers are inserted.

## To Reproduce

1. Follow the installation instructions for Supabase for my project https://github.com/ChrisPaliqaw/robot-window-redwood
2. Checkout robot-window-redwood
3. Go into robot-window-redwood
4. Run `yarn install`
5. Run `yarn rw dev`
6. Login using username dev@email.io and password Pa55word!
7. Use F12 to see the browser console. Drill down in the data object that was logged: data -> user -> app_metadata
8. When using the current version of Supabase (as of March 6, 2022), only provider and providers are present, but if tag 0.22.11 is used, any additional custom claims will be present as well.

## System information

- OS: Ubuntu 22
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: commit 8c2aee12ecba60ce5b31d36ea8d766127a1d5f5d (bug) vs 0.22.11 (no bug)
- Version of Node.js: 18.14.2

**Comment by GaryAustin1** [comment]
I realize this is old, but the jwt will not immediately reflect changed to the auth.users table raw_app_meta_data column.  The jwt has to be refreshed or getUser called after a change.

Could this have been the issue?

Closing this for now, but can reopen if still an issue.
