### ISSUE TITLE
Supabase Studio buckets fail loading studio.de/api/storage/default/buckets

### ISSUE THREAD

**Issue by supermar1010** [supabase/supabase#12835]
# Bug report

## Describe the bug

When trying to load the buckets (aka going to 'http://localhost:3000/project/default/storage/buckets')  a request is being made to: `http://localhost:3000/api/storage/default/buckets`, which returns http

```
<!DOCTYPE html><html><head><meta charSet="utf-8"/><title>Supabase</title><meta name="viewport" content="initial-scale=1.0, width=device-width"/><meta name="next-head-count" content="3"/><link rel="stylesheet" type="text/css" data-name="vs/editor/editor.main" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.css"/><link rel="stylesheet" type="text/css" href="/css/fonts.css"/><link rel="preload" href="/_next/static/css/561e6059bf18e5cb.css" as="style"/><link rel="stylesheet" href="/_next/static/css/561e6059bf18e5cb.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-8b474084417a88e3.js" defer=""></script><script src="/_next/static/chunks/framework-88c3fab5a4d30eea.js" defer=""></script><script src="/_next/static/chunks/main-4518d572b1ff7494.js" defer=""></script><script src="/_next/static/chunks/pages/_app-9709af9fa5a7f6b0.js" defer=""></script><script src="/_next/static/chunks/pages/404-8abc8d189339f8c7.js" defer=""></script><script src="/_next/static/YYlqGy41GF6Z7x-CI_lFm/_buildManifest.js" defer=""></script><script src="/_next/static/YYlqGy41GF6Z7x-CI_lFm/_ssgManifest.js" defer=""></script><script src="/_next/static/YYlqGy41GF6Z7x-CI_lFm/_middlewareManifest.js" defer=""></script></head><body class="dark"><div id="__next" data-reactroot=""><div class="min-h-full flex flex-col"><div class="relative mx-auto flex h-screen w-full flex-col items-center justify-center"><div class="absolute top-0 mx-auto w-full max-w-7xl px-8 pt-6 sm:px-6 lg:px-8"><nav class="relative flex items-center justify-between sm:h-10"><div class="flex flex-shrink-0 flex-grow items-center lg:flex-grow-0"><div class="flex w-full items-center justify-between md:w-auto"><a href="/projects"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%27120%27%20height=%2724%27/%3e"/></span><img alt="supabase" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%"/><noscript><img alt="supabase" srcSet="/img/supabase-dark.svg 1x, /img/supabase-dark.svg 2x" src="/img/supabase-dark.svg" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" loading="lazy"/></noscript></span></a></div></div></nav></div><div class="absolute select-none opacity-[5%] filter transition duration-200 blur-none"><h1 style="font-size:28rem">404</h1></div><div class="flex flex-col items-center justify-center space-y-6 transition opacity-0"><div class="flex w-[380px] flex-col items-center justify-center space-y-3 text-center"><h3 class="text-xl">Looking for something? 🔍</h3><p class="text-scale-1100">We couldn&#x27;t find the page that you&#x27;re looking for!</p></div><div class="flex items-center space-x-4"><a href="/projects"><button class=" relative cursor-pointer inline-flex items-center space-x-2 text-center font-regular transition ease-out duration-200 rounded outline-none transition-all outline-0 focus-visible:outline-4 focus-visible:outline-offset-1   bg-brand-fixed-1100 hover:bg-brand-fixed-1000 text-white bordershadow-brand-fixed-1000 hover:bordershadow-brand-fixed-900 dark:bordershadow-brand-fixed-1000 dark:hover:bordershadow-brand-fixed-1000 focus-visible:outline-brand-600  shadow-sm text-sm leading-4 px-3 py-2" type="button"><span class="truncate">Head back</span></button></a></div></div></div></div><div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/404","query":{},"buildId":"YYlqGy41GF6Z7x-CI_lFm","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup new supabase docker install
2. Click on Storage tab (`http://localhost:3000/project/default/storage/buckets`)
3. Observe error message and network tab in browser 

## Expected behavior

Should load buckets json

## System information

- OS: fedora
- Browser (if applies) firefox, chrome
- Version of supabase-js: idk, latest supabase/studio:20230228-029c7bd
- Version of Node.js: [e.g. 10.10.0]

**Comment by supermar1010** [comment]
I found the culprit. It is commit ec932267316fe9233ab2aa025d84af8bc624b755 
Which now uses: `export const API_URL = IS_PLATFORM ? process.env.NEXT_PUBLIC_API_URL : '/api'` Which apparently is `api` in my case instead of localhost:8000. I guess it is a similiar bug to this one: https://github.com/supabase/supabase/pull/11740

**Comment by squallsama** [comment]
Yeah. Have to use old docker image `supabase/studio:20230216-e731b77` to avoid this issue...

**Comment by supermar1010** [comment]
I looked at the code a bit more, it seems the fix is not as easy as using `SUPABASE_PUBLIC_URL` instead of `NEXT_PUBLIC_API_URL`. There seem to have been some other changes. Right now I also reverted to an earlier version.

**Comment by Rid** [comment]
Also seeing this on self-hosted, but also in `20230216-e731b77` buckets are also broken in studio due to https://github.com/supabase/supabase/issues/11692 https://github.com/supabase/supabase/issues/11153 https://github.com/supabase/supabase/issues/11136

**Comment by squallsama** [comment]
> Also seeing this on self-hosted, but also in `20230216-e731b77` buckets are also broken in studio due to #11692 #11153 #11136
With 20230216-e731b77 studio I'm able to retrieve buckets in studio self-hosted

**Comment by Rid** [comment]
@squallsama are you running self-hosted studio without https?

**Comment by squallsama** [comment]
> @squallsama are you running self-hosted studio without https?

Self hosted with nginx as a reverse proxy inside of a docker compose and with https

**Comment by Rid** [comment]
> > @squallsama are you running self-hosted studio without https?
> 
> Self hosted with nginx as a reverse proxy inside of a docker compose and with https

Does your nginx config have `add_header Content-Security-Policy "upgrade-insecure-requests";`?

**Comment by squallsama** [comment]
> > > @squallsama are you running self-hosted studio without https?
> > 
> > 
> > Self hosted with nginx as a reverse proxy inside of a docker compose and with https
> 
> Does your nginx config have `add_header Content-Security-Policy "upgrade-insecure-requests";`?

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
```

**Comment by GaryAustin1** [comment]
This issue is stale.  Not clear if you all were able to work around it at end or a fix took care of it.  But I assume a resolution happened as this was 8 months ago.

Closing unless comments warrant reopening (although a new issue might be better if problem still exists).
