### ISSUE TITLE
Supabase User Management App Dark Theme bug and fix

### ISSUE THREAD

**Issue by RoboTums** [supabase/supabase#12840]
# Bug report
Following the instructions https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs here, leads you to import `ThemeSupa` from `'@supabase/auth-ui-react'`

## Describe the bug
This leads to a bug when setting the theme="dark" in the <Auth/> component because the dark theme is undefined in `'@supabase/auth-ui-react'`

However it is defined in `'@supabase/auth-ui-shared'`.

## To Reproduce
```
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'

import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

const Home = () => {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!session ? (
        <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa  }} theme="dark" />
      ) : (
        <p>Account page will go here.</p>
      )}
    </div>
  )
}

export default Home

```

with env.local having the anon and URL for a project. 

## Fix:
Change the imports in the tutorial to the following: 
```
import { Auth } from '@supabase/auth-ui-react'
import { ThemeSupa } from '@supabase/auth-ui-shared'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

``` 
And the rest of the snippets will work fine.

**Comment by GaryAustin1** [comment]
This would be better posted as an issue in https://github.com/supabase/auth-ui/issues
But I don't have ability to transfer it there.
