### ISSUE TITLE
extension plpython3u

### ISSUE THREAD

**Issue by feedmaker** [supabase/supabase#1285]
# Feature request

is it possible to activate the python language?

**Comment by inian** [comment]
Hi @feedmaker, [plpython3u](https://www.postgresql.org/docs/9.1/plpython.html) is an untrusted extension (extensions which give full file system access) and we are not planning to enable untrusted extensions just yet. Once we are confident that an untrusted extension can't be used to do something malicious, we will enable it :) 

Meanwhile you can vote for the extension [here](https://github.com/supabase/supabase/discussions/679#discussioncomment-346350)
