### ISSUE TITLE
og image github action not deploying

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#12870]
# Bug report

## Describe the bug

The og images github action doesn't deploying when code is pushed to `master` branch.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

2. merge code into `master` branch
4. what for all github action to run and finish
5. see no new deploy in Supabase dashboard

## Expected behavior

That the github action deploys the function when code is pushed to `master branch` and only when editing `og-images` files.

## Screenshots

n/a

## System information

- OS: n/a
- Browser: n/a
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by sambhavgupta0705** [comment]
hey can I work on this issue?

**Comment by gregnr** [comment]
Hey @Isaiah-Hamilton was the action not triggering at all, or was it triggering & failing? Last week I updated some env vars to fix the deployment:

https://github.com/supabase/supabase/actions/workflows/og_images.yml

So this might be fixed now.

**Comment by Isaiah-Hamilton** [comment]
The action was triggering but failed instantly. It seems to be working now, but I think we should keep this issue open till we know for sure its working properly.

**Comment by gregnr** [comment]
@Isaiah-Hamilton thanks for confirming. Could you find a way to verify this so we can close?

**Comment by Isaiah-Hamilton** [comment]
I don't think we can verify without pushing og image code to master branch
