### ISSUE TITLE
Update operation does not have code documentation

### ISSUE THREAD

**Issue by MarioLegenda** [supabase/supabase#12880]
# Improve documentation

Update documentation is `undefined`

## Link 

https://supabase.com/docs/reference/dart/v0/insert

## Describe the problem

The documentation code example is missing

## Describe the improvement

Nothing much to say. Just put the example there and that is it.

## Additional context

No context

**Comment by GaryAustin1** [comment]
Just going to point out that is v0 code v1 code has the info.
