### ISSUE TITLE
Nested policy does not give any results

### ISSUE THREAD

**Issue by yurivangeffen** [supabase/supabase#12896]
# Bug report

## Describe the bug

Policy using IN does not seem to work.

## To Reproduce

Create a Policy like this:

```sql
(owned_by IN (
   SELECT membership.organisation
   FROM membership
   WHERE (membership."user" = auth.uid())
))
```
on SELECT in a schema `entries` which has a column `owned_by` which is a FK to a row in the `organisation` table. This organisation table is connected to a `membership` table which connects `user` and `organisation`.

## Expected behavior

Note; not sure this is a bug or my mistake.

A user that is connected to the organisation through a membership that "owns" the entry should be able to fetch it using the endpoint `https://XXX.supabase.co/rest/v1/entries?select=*`. However, an empty array is returned.

If I simply use a direct ownership column (to `uid`) the policy works fine, it's only wrong in nested policies. Note; I have tried many different permutations of the query but this is the simplest form that I would expect to work ^.

## Screenshots

<img width="1160" alt="Screenshot 2023-03-08 at 17 34 24" src="https://user-images.githubusercontent.com/4107720/223773443-44f925b4-6b15-4c0e-a7a1-ed8ddc610d45.png">

<img width="1187" alt="Screenshot 2023-03-08 at 17 34 47" src="https://user-images.githubusercontent.com/4107720/223773556-5bb32348-5ae9-4236-9a88-01bf1d2001e2.png">

<img width="1186" alt="Screenshot 2023-03-08 at 17 34 56" src="https://user-images.githubusercontent.com/4107720/223773565-d11e6221-67cb-41da-ab07-b7250184126f.png">

<img width="1188" alt="Screenshot 2023-03-08 at 17 35 04" src="https://user-images.githubusercontent.com/4107720/223773567-fd6307a9-1f91-43c1-89cd-56f016aec988.png">

<img width="972" alt="Screenshot 2023-03-08 at 17 35 19" src="https://user-images.githubusercontent.com/4107720/223773571-14c819cb-aa23-4b99-8b69-0cdc60a45d98.png">

<img width="678" alt="Screenshot 2023-03-08 at 17 40 55" src="https://user-images.githubusercontent.com/4107720/223774596-bc824b21-5674-40b0-b00d-6b28783f3ac7.png">

## System information

- OS: MacOS
- Browser: FF
- Version of supabase-js: Cloud
- Version of Node.js: -

## Additional context

I just want to limit access to `entries` based on a `owned_by` field and an `organisation` `membership`.

**Comment by GaryAustin1** [comment]
You really should post this type of issue in Supabase Discord https://discord.com/invite/R7bSpeBSJE or discussions here to get more help than flagging it as a bug.

You likely can't use your other tables because you have to meet RLS select policies on all that are used and your pictures show no policies for tables like membership.

**Comment by yurivangeffen** [comment]
@GaryAustin1 thanks for the suggestion, that indeed seems to be the issue! I will make an improvement PR/proposal for a documentation change.
