### ISSUE TITLE
Connection Issues Between PostgREST and Database

### ISSUE THREAD

**Issue by kevinmlong** [supabase/supabase#12918]
# Bug report

## Describe the bug

I'm seeing intermittent connection issues when making requests with `supabase-js` which seem to look like connection issues between the `postgrest` container and the `postgres` container. 

## To Reproduce

I'm running a self-hosted docker instance of Supabase. Some requests come back with the following errors:

```
{ code: '', details: null, hint: null, message: '' }
```
```
{
  code: 'PGRST001',
  details: 'no connection to the server\n',
  hint: null,
  message: 'Database client error. Retrying the connection.'
}
```
Looking at the logs for PostgREST I saw the following:
```
09/Mar/2023:13:12:17 +0000: Attempting to connect to the database...
10.0.12.24 - service_role [09/Mar/2023:13:12:17 +0000] "POST /foo_table HTTP/1.1" 503 - "" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

## Expected behavior

Intermittent connection issues shouldn't happen

## System information

- OS: Alpine Linux / Docker
- Version of supabase-js: 2.10.0
- Version of Node.js: 16

## Additional context

FWIW - I've also seen some console errors in the UI portion of the app that also have 503 codes related to supabase queries/operations. I suspect these are related.

**Comment by kevinmlong** [comment]
@GaryAustin1 - saw you added a label to this. Do you have any inklings into what may be causing these errors?

**Comment by GaryAustin1** [comment]
Sorry, I don't really do local dev.  You would probably get more help in discussions or the Supabase Discord if you are not sure this is a bug (which is what you marked it as), so presumed to be an issue for a dev.

**Comment by kevinmlong** [comment]
Thanks @GaryAustin1. I posted to the Discord back when I submitted this issues. https://discord.com/channels/839993398554656828/1083464648319316031

**Comment by kevinmlong** [comment]
I also posted a new one this morning with more details/context. https://discord.com/channels/839993398554656828/1087748279229497415

**Comment by GaryAustin1** [comment]
Yeah, hopefully the new one will get some attention as it has more info.

**Comment by steve-chavez** [comment]
I suggest isolating the problem first. Try a simple docker compose as shown [here](https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose).

If it works then the error likely resides somewhere in your docker network config.

**Comment by kiwicopple** [comment]
this one looks stale, so I'll close for now. Feel free to re-open if there is any way we can reproduce this issue (without steps for reproduction it's quite hard to help)

> posted a new one this morning with more details/context

fwiw, it's very useful to keep the details on GitHub where possible! (or copy them to both locations)
