### ISSUE TITLE
Supabase Dashboard - Hidden Project Settings

### ISSUE THREAD

**Issue by Butch78** [supabase/supabase#12937]
# Bug report

## Describe the bug

When I have my resolution at 100% in Chrome I can't see the Project Settings button. While at 80% I can.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Chrome and change the zoom level of your browers
2. See error hidden button

## Expected behavior

The buttons down the left side become scrollable? 

## Screenshots
100%
<img width="947" alt="image" src="https://user-images.githubusercontent.com/19205392/224303865-2d80abc3-4a19-4bc7-b166-ebccf57e463b.png">
80%
<img width="946" alt="image" src="https://user-images.githubusercontent.com/19205392/224304693-656b476d-d523-418b-978c-8fb3b669d8b8.png">

## System information

- OS: [Windows]
- Browser (if applies) [chrome, safari]

**Comment by saltcod** [comment]
Hey @Butch78 thanks for the report. We definitely have some work to do about better responsiveness in the Dashboard. I'll add this one to the list of related feedback. Appreciated!
