### ISSUE TITLE
Unable to update "Enforce JWT Verification" for edge functions

### ISSUE THREAD

**Issue by tombailey** [supabase/supabase#12938]
# Bug report

## Describe the bug

Unable to update "Enforce JWT Verification" for an edge functions.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Deploy an edge function
2. Go to **https://app.supabase.com/project/{{my-project}}/functions/{{my-function}}/details**
3. Toggle "Enforce JWT Verification"
4. Press "Save"
5. Refresh the page
6. Observe the change to "Enforce JWT Verification" was not saved

## Expected behavior

After pressing "Save", the change to the "Enforce JWT Verification" flag should be saved and reflected when the page is refreshed.

## Additional context

This seems to happen because the submitted form uses camelCase attribute names but the API uses snake_case attribute names. See [this line](https://github.com/supabase/supabase/blob/77b0cff3a26f13d65c306f920e37b3ddae7431bd/studio/components/interfaces/Functions/EdgeFunctionDetails/EdgeFunctionDetails.tsx#L130). The API expects the attribute name to be `verify_jwt` but the form submits `verifyJwt`. If you manually edit and resend the request with `verify_jwt` instead of `verifyJwt`, the changes are saved and the form reflects the desired state when refreshed.

**Comment by laktek** [comment]
@tombailey Thanks for reporting this issue. We will apply a fix for it soon.

**Comment by laktek** [comment]
@tombailey A fix for this issue has been deployed. Thanks @joshenlim for the fix.
