### ISSUE TITLE
Flutter VerifyOTP Not Working

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#12948]
# Bug report

## Describe the bug

I'm using Supabase & Flutter and cannot verify the OTP

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Try to sign in with phone number using Twilio. 
I receieve the text with the verification code. 
I enter the code 

Get this error:
Exception has occurred.
AuthException (AuthException(message: Token has expired or is invalid, statusCode: 401))

## Expected behavior

Sucessfully verify the phone number and sign in

## System information

iOS

**Comment by GaryAustin1** [comment]
Is this a bug because it was working and now it is not?
If first time using it, you should show some code.  What does your verifyOtp() call look like?

**Comment by nimafarzaneh** [comment]
Hello

I have the same issue using the Javascript 2.0. 
I get the OTP code via email , however when I call the **supabase.auth.verifyOtp()** with the email and the OTP code received from the email, I get **"error: AuthApiError: Token has expired or is invalid"**
Can somebody help if it's a bug or I'm doing sth wrong?

This is the code I'm using to verify the OTP
`  const { data, error } = await supabase.auth.verifyOtp({
    email: 'aaaaa@bbb.com',
    token:'xxxxxx',
    type: 'signup'
  })`

**Comment by jtkeyva** [comment]
> Is this a bug because it was working and now it is not?
> If first time using it, you should show some code. What does your verifyOtp() call look like?

@GaryAustin1 
i have never been able to get it to work using phone number.

here is my code:
`onPressed: () async {
                  await supabase.auth.signInWithOtp(phone: '1XXXXXXXXXX');
                },`

it works with magic links using this code:

`Future<void> _signIn() async {
    setState(() {
      _isLoading = true;
    });
    try {
      await supabase.auth.signInWithOtp(
        email: _emailController.text,
        emailRedirectTo:
            kIsWeb ? null : 'com.mywebsite.app://login-callback/',
      );
      if (mounted) {
        context.showSnackBar(message: 'Check your email for login link!');
        _emailController.clear();
      }
    } on AuthException catch (error) {
      context.showErrorSnackBar(message: error.message);
    } catch (error) {
      context.showErrorSnackBar(message: 'Unexpected error occurred');
    }

    setState(() {
      _isLoading = false;
    });
  }`

**Comment by jtkeyva** [comment]
@GaryAustin1 is there anything i'm missing? can you confirm twilio phone auth works with flutter?
thanks

**Comment by GaryAustin1** [comment]
What are you using for the token type when you call verifyOtp?   It could be signup (if a new user) or magiclink (if an existing user).

**Comment by jtkeyva** [comment]
not sure what you mean
i'm just using the above code and also tried with signUp as seen below

`await supabase.auth
                      .signUp(phone: '15555555555', password: 'password');
                },`

i cannot figure this out. am i doing something wrong? has this been verified working OTP + Twilio + Flutter ?

it's starting to get urgent on my end. let me know if there is anything i can do to help.

thanks

**Comment by GaryAustin1** [comment]
You have filed a bug report, not a request for help in discussions or Discord.   Not sure when a flutter Dev might see this (I can't move it the supabase flutter github) and not sure it is a bug.

Sorry for the confusion in my last response also as I did not realize another user had jumped with with email question.

For phone you have to use `type:'sms'` in verifyOtp.
For email you use `type: 'signup'` for an existing user you use `type:'magiclink'`.   

The error is you get is for wrong type or expired.

**Comment by jtkeyva** [comment]
thanks. even when i send verification token from supabase.com i get the error. my program is "crashing" and stopping at this. does that provide any clues? i'm going nuts over here trying to get this working. 

`unawaited(xhr.onLoad.first.then((_) {
      var body = (xhr.response as ByteBuffer).asUint8List();
      completer.complete(StreamedResponse(
          ByteStream.fromBytes(body), xhr.status!,
          contentLength: body.length,
          request: request,
          headers: xhr.responseHeaders,
          reasonPhrase: xhr.statusText));
    }));`

**Comment by jtkeyva** [comment]
Ok I overlooked a simple mistake in my code.

i had
token: tokenInputController.toString(),

it should be
token: tokenInputController.text,
