### ISSUE TITLE
Transparent Column Encryption does not work (permission/ownership issue)

### ISSUE THREAD

**Issue by jstdk** [supabase/supabase#12952]
# Bug report

## Describe the bug
I followed the Supabase tutorial: https://supabase.com/blog/transparent-column-encryption-with-postgres to encrypt the password field in the email table. I tried this:

CREATE TABLE emails (
	id bigserial primary key,
        email text,
  	password text,
	key_id uuid not null DEFAULT 'e348034b-3f07-4878-aad6-000511d12826'::uuid,
  	nonce bytea default pgsodium.crypto_aead_det_noncegen()
);

This succeeds, then I move on to:

SECURITY LABEL FOR pgsodium
	ON COLUMN emails.password
  	IS 'ENCRYPT WITH KEY COLUMN key_id NONCE nonce';

Error: **Failed to run sql query: must be owner of event trigger pgsodium_trg_mask_update**

Then I tried to Google and change the owner as suggested by other users and tutorials. For example https://www.postgresql.org/docs/current/sql-altereventtrigger.html

Problem is that I cannot find this trigger in Triggers. I tried: 

ALTER EVENT TRIGGER pgsodium_trg_mask_update OWNER to postgres

Error: Failed to run sql query: must be owner of event trigger pgsodium_trg_mask_update

I am out of options, How did the writer of the tutorial make this work?

## To Reproduce

Follow https://supabase.com/blog/transparent-column-encryption-with-postgres

## Expected behavior

Password column encrypted

## Screenshots

See code examples above

## System information

Linux (Fedora 37) + Supabase Dashboard in Chromium

**Comment by james2doyle** [comment]
Having the same issue. Also tried to use an RPC call and that also failed

**Comment by james2doyle** [comment]
You need to grant the user the permissions to use the function:

`GRANT EXECUTE ON FUNCTION pgsodium.crypto_aead_det_decrypt (bytea, bytea, uuid, bytea)
TO authenticated;`

**Comment by jstdk** [comment]
Thanks. Unfortunately, I keep getting this error: Failed to run sql query: must be owner of event trigger pgsodium_trg_mask_update

**Comment by james2doyle** [comment]
You're running it on the supabase SQL editor? Are you using self hosted or
platform?

I ran it on a client connected as the postgres user on platform and it
worked fine for me. My function and my view that had that error both worked
after

**Comment by jstdk** [comment]
I ran it in the SQL editor indeed. Will try as client. Thanks for the extra info

**Comment by radulescuandrew** [comment]
I have the same issue while trying to alter a table on a recently restored project. 

```must be owner of event trigger pgsodium_trg_mask_update```

I tried the above but it is not working. Any other guidance?

**Comment by gregnr** [comment]
cc @michelp in case you have any insight.

**Comment by michelp** [comment]
Hi @radulescuandrew , the issue is that in an older version of our software stack, there was a dump/restore bug that introduced this ownership issue. If you start through the same tutorial with a fresh project, it will work properly.

Fixing it for an existing database depends on if you have encrypted data you want to preserve.  If you do, you'll have to temporarily copy or dump that data to the side so you can reinser it.  then disabling and then renabling the extensions will initialize them with the correct privledges:

```sql
drop view vault.decrypted_secrets;
drop extension supabase_vault;
drop extension pgsodium;
create extension pgsodium;
create extension supabase_vault;
```

**Comment by jstdk** [comment]
That explains why it did not even work with the new toggle in the edit column page in my existing project

**Comment by SamMakesThings** [comment]
Tried both the dropping view/extensions thing and manually granting execute thing - neither worked ☹️

Ran both the above SQL scripts in the hosted Supabase SQL editor, to no avail.

Any ideas on what might work if the above fails?

**Comment by jacktho** [comment]
I was able to fix the lack of permissions for `crypto_aead_det_encrypt` and `crypto_aead_det_decrypt` by doing GRANT `pgsodium_keyiduser TO authenticated;`

As mentioned here:
https://supabase.com/docs/guides/database/column-encryption#granting-api-access-to-encrypted-columns

**Comment by jstdk** [comment]
Finally implemented it today for all databases and nuked out various crypto npm packages. What a relieve. It works great without any SQL code needed, except for querying a view instead of the tables directly. 

Thanks everyone, this solution is what I was hoping for. Will close the ticket.

**Comment by tsboh** [comment]
This one-line by @SamMakesThings saved my day, much appreciated! Thank you
