### ISSUE TITLE
Fix User Management Starter SQL Script

### ISSUE THREAD

**Issue by storialp** [supabase/supabase#12985]
# Bug report

## Describe the bug

The User Management Starter SQL script is wrong. It is clearly meant to set the id primary key equal to that of auth.uid(). However, it generates a completely new UUID creating a data inconsistency.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'The SQL editor inside your project dashboard'
2. Click on 'Welcome'
3. Scroll down to 'Quick start and select User Management Starter '

## Expected behavior

When the query is triggered, new profiles should be assigned auth.uid() as id and primary key. 

## Additional context

Related to it, in the [Next tutorial ](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs), you're asked to select the query and run it as is which makes it clear it is not the desired behavior. To fix this I had to use this snippet provided in [this example](https://supabase.com/docs/guides/auth/managing-user-data)

**Comment by GaryAustin1** [comment]
Can you verify you are talking about this code:
```
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
```
That creates the new profile row with the ID the user gets when they are being created for the first time by gotrue/auth.  
`new.id` is the id from auth.users id column, which is what will normally be referred to by `auth.uid()` in database calls later.  
There is no value for `auth.uid()` in auth calls, that is only for database calls.

**Comment by storialp** [comment]
Yes, I am. The problem is, at least in my case (using Google OAuth), it did not assign the ID the user has in the auth.users column. Instead it generated a new UUID.  
This code
```
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);
```
With this trigger
``` 
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```
Assigned a UUID and primary key that did not match the auth.users id column.

This code with the same trigger did assign the same id
```
create table profiles (
  id uuid not null references auth.users on delete cascade,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  primary key (id),

  constraint username_length check (char_length(username) >= 3)
);
```

**Comment by GaryAustin1** [comment]
The two create table SQL pieces of code you show generate the same table with the same primary uuid key.

I don't see how that would impact what the trigger does.

**Comment by GaryAustin1** [comment]
Going to close this out as no further responses.  Please feel to comment if there is still an issue.
