### ISSUE TITLE
setAuth() function missing in supabase-flutter

### ISSUE THREAD

**Issue by renushreeg** [supabase/supabase#12994]
# Bug report

`setAuth()` function is missing in the supabase-flutter 1.0.0.

## Describe the bug

`setAuth()` function is missing in the supabase-flutter 1.0.0.

## To Reproduce

Going through the functions & docs, there are no mentions of this function being removed. It throws an error because it's not a defined function.

## Expected behavior

Expecting that `supabaseClient.auth.setAuth(cookie)` to be an available function.

## System information
- OS: Windows
- Version of supabase-js: ^1.0.0
- Version of Node.js: 18.14.0

## Additional context

`setAuth` function is missing in supabase 1.0.0. `setAuth` is depricated, but is there any workaround for that. There is workaround in supabase-js [link](https://github.com/supabase/supabase/issues/8490).

**Comment by GaryAustin1** [comment]
Would that method of workaround not work for flutter?  Seems like it is just using createClient with options.
setAuth is deprecated and I believe that applies to all clients.
