### ISSUE TITLE
SSL connection timeout in hosted Supabase

### ISSUE THREAD

**Issue by magick93** [supabase/supabase#13007]
# Bug report

We have started to getting an error - `SSL connection timeout` - and only in the hosted supabase.

#### Postman to API
Same as the team. Works consistently and as expected both on the local and hosted API endpoints.

#### Supabase to API

This shows success when going directly (using Postman) to the external api. This is the same api that is being called from within supabase / postgres via the use of the `http` extension, specifically using `http_put`.

When calling the `private.connect_accounting_contact(contactName, contactEmail)`  from within the Supabase SQL editor: 

Supabase Instance | Accounting API | Status | Result
-- | -- | -- | --
Local | Local | OK | Works consistently and as expected. Returns an id string on success, and a null value when the user name has already been taken.
Local | Hosted | OK | As above
Hosted | Local | OK | As above
Hosted | Hosted | FAIL | Inconsistent behaviour. Initially would allow some contacts to be created, and return null for already created contacts. Then started to throw the Failed to run sql query: SSL connection timeout error consistently. On further testing, only throws this error now, so no contacts are being created at all.

## To Reproduce

The postgres function body is using `http_put`.

## Expected behavior

Expect to get a http 200 status, and for it to work consistently across the different environments. 

## Screenshots

From the Supabase console:
![image](https://user-images.githubusercontent.com/2173213/225121150-d037dfc1-bdbb-4114-8d80-341e03b14844.png)

And using Postman
![image](https://user-images.githubusercontent.com/2173213/225121236-54395381-cccd-44ce-9d27-092c6b102c72.png)

## System information

Supabase hosted _only_.

**Comment by burggraf** [comment]
@magick93 is this still occurring for you?
