### ISSUE TITLE
Storage bucket does not allow uploaded files when created through seed.sql

### ISSUE THREAD

**Issue by zhawtof** [supabase/supabase#13016]
# Bug report

## Describe the bug

During local development, a bucket created from a `seed.sql` will reject files that are uploaded manually or through the API

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a `seed.sql` file containing the following:
```sql
-- Create a new bucket in the Supabase storage
INSERT INTO storage.buckets (id, name, public)
VALUES (uuid_generate_v4(), 'recordings', TRUE);
```
2. Run `supabase start` or `supabase db reset` to initiate seed file
3. Go to http://localhost:54323/project/default/storage/buckets/recordings and notice that the bucket has been created what seems properly.
4. Try and upload any file.
5. Will see the following errors:
<img width="369" alt="Screenshot 2023-03-15 at 2 10 02 AM" src="https://user-images.githubusercontent.com/4521335/225221949-cd513507-59ad-4a0f-bc55-82d90630302e.png">

## Expected behavior

I would expect to be able to add a file to Supabase storage.

## Screenshots

Screenshots added inline above.

## System information

- OS: MacOS M1 chip
- Browser (if applies) Chrome
- Version of supabase-js: 1.42.5
- Version of Node.js: v19.8.0

## Additional context

When creating the bucket manually, it allows me to add a file manually and through the API

**Comment by GaryAustin1** [comment]
Bucket id is the same string  as the bucket name and not a uuid.
