### ISSUE TITLE
Supabase sql problem showing

### ISSUE THREAD

**Issue by Junaed122** [supabase/supabase#13014]
For some reason the database schema which should be pasted into the SupaBase SQL Editor gives me an error. ```Failed to run sql query: must be member of role "supabase_admin"```

**Comment by saltcod** [comment]
hey @Junaed122!   Could you paste in the sql you tried to use?

**Comment by rohanA6** [comment]
give the full context, the query, and the problem statement

**Comment by MildTomato** [comment]
I'm closing this issue for now until we get more information.

@Junaed122 feel free to open a support ticket as well, especially if it's something sensitive you don't wish to share publicaly.
https://app.supabase.com/support/new

**Comment by MildTomato** [comment]
I'm closing this issue for now until we get more information.

@Junaed122 feel free to open a support ticket as well, especially if it's something sensitive you don't wish to share publicaly.
https://app.supabase.com/support/new
