### ISSUE TITLE
Using ALTER FUNCTION from SQL Editor

### ISSUE THREAD

**Issue by EskelCz** [supabase/supabase#13010]
# Bug report

## Describe the bug

I'm trying to use ALTER FUNCTION from SQL editor UI in Supabase, to change function parameter names, like so:
`ALTER FUNCTION "has_contact"(profile_id uuid, contact_profile_id uuid) RENAME TO "has_contact"(identity_id uuid, contact_identity_id uuid);`
and getting this error:
`Failed to validate sql query: syntax error at or near "("`

The PostgreSQL version is 15.1, so I think ALTER FUNCTION should be available, is that correct?
https://www.postgresql.org/docs/current/sql-alterfunction.html

Thanks for looking into this.

**Comment by GaryAustin1** [comment]
The SQL editor last I checked a few weeks ago is not handling syntax yet for 15.   Neither is my Datagrip editor, but that is another story.

**Comment by GaryAustin1** [comment]
Your issue is I believe RENAME TO expects just the new name, no parameters.  You cannot modify the parameter names or types.

**Comment by GaryAustin1** [comment]
Closing unless as dropping parameters passes syntax.

**Comment by EskelCz** [comment]
@GaryAustin1 Ok thanks, it works without the parameters. Unfortunately that's the change I really needed. I used the function in RLS policies and it's a pain to change the parameter names, especially through the UI.

**Comment by GaryAustin1** [comment]
Yeah that is a postgres thing.
`To replace the current definition of an existing function, use CREATE OR REPLACE FUNCTION. It is not possible to change the name or argument types of a function this way (if you tried, you would actually be creating a new, distinct function). Also, CREATE OR REPLACE FUNCTION will not let you change the return type of an existing function. To do that, you must drop and recreate the function. (When using OUT parameters, that means you cannot change the types of any OUT parameters except by dropping the function.)`
https://www.postgresql.org/docs/current/sql-createfunction.html#SQL-CREATEFUNCTION-DESCRIPTION
