### ISSUE TITLE
Use trim() method to validate text field entry like email.

### ISSUE THREAD

**Issue by AKR-2803** [supabase/supabase#13025]
# Improve documentation

## Link 
[Build a User Management App with Flutter](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter)

## Describe the problem
I want to suggest a minor improvement.
 
In [Set up a Login page](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#set-up-a-login-page) code, inside try catch block,  
```dart
//current code
try {
      await supabase.auth.signInWithOtp(
        email: _emailController.text,
        emailRedirectTo:
```
```_emailController.text``` might be replaced with ```_emailController.text.trim()```. 

*Why* :
- In most cases the email will be typed using autocomplete, which leads to an empty space character ``` ``` in the end.
- When pressed on ```Send Magic Link``` button, the code throws a snackbar error ```Unable to validate email address: invalid format```
- This can especially be confusing for beginners, or anyone who is trying to follow the documentation.

Same applies to [Set up Account page](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#set-up-account-page)
```dart
 //current code
 Future<void> _updateProfile() async {
    setState(() {
      _loading = true;
    });
    final userName = _usernameController.text;
    final website = _websiteController.text;
    final user = supabase.auth.currentUser;
```
## Describe the improvement

[Set up a Login page](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#set-up-a-login-page)
```dart
//improvement suggested
 try {
      await supabase.auth.signInWithOtp(
        email: _emailController.text.trim(),
        emailRedirectTo:
```

[Set up Account page](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#set-up-account-page)
```dart
//improvement suggested
 Future<void> _updateProfile() async {
    setState(() {
      _loading = true;
    });
    final userName = _usernameController.text.trim();
    final website = _websiteController.text.trim();
    final user = supabase.auth.currentUser;
```

## Additional context

- It is a good practice to always trim the trailing(and leading) spaces from controller.text, as it can be crucial in later stages, like storing/fetching data, or naming constraints.
- Unnecessary spaces should always be removed.  
- Clip for reference : 

https://user-images.githubusercontent.com/109909231/225262590-3dd2bfd0-5272-411a-a138-374852a584ea.mp4

**Comment by dshukertjr** [comment]
Thanks for the amazing suggestion! Closing as fix has been merged!
