### ISSUE TITLE
Wrong values for pricing page

### ISSUE THREAD

**Issue by liflovs** [supabase/supabase#1303]
# Improve documentation

## Link 

https://supabase.io/pricing

## Describe the problem

I see some confirmation email limits (dunno if daily or monthly) See db size is 200 mb. Storage - 2Gb

While on the front page it is 500 Mb and no confirmation limit. But storage is lower (1Gb)

This blocks the decision to pay as pricing seems still floating a lot.

## Describe the improvement

Advertisement and actual data should match. Right now advertisement seems to be overpromoting the service. (I guess there might be even more caveats undocumented neither on the website nor inside supabase

## Additional context

![image](https://user-images.githubusercontent.com/27358804/116409706-c6b22580-a83c-11eb-9b2c-0649f3a4f97e.png)

**Comment by inian** [comment]
Hi @liflovs, this is a frontend error. Your database does have 500 MB space. The fix for this should get deployed by tomorrow.

**Comment by liflovs** [comment]
@inian so basically all the values are wrong there, right? Same for users (it shows 100 000)

Then still auth confirmation should be pointed on website, as its pretty important (lets say - how much I will get on higher tiers?)

**Comment by kiwicopple** [comment]
@liflovs - the pricing page is the most accurate. The Dashboard will be updated to match the pricing page. We have some blockers for shipping the Dashboard changes, so they will be deployed tomorrow (or once we clear the blockers)

**Comment by liflovs** [comment]
@kiwicopple thanks, so not to create a new ticket - saw this in website docs:
"We are committing to the following initiatives:
All Beta Users (new users from December 2020) will receive 1 year of base tier usage for free.
The Supabase Base Tier is now called the Supabase Pro tier as per the pricing page: https://supabase.io/pricing"

As I understand - beta ended or some "new beta" started? Or the 1 year of usage will be entitled after product goes to "final" version.
In any case message is either outdated or misleading.

**Comment by roryw10** [comment]
Hi @liflovs,

I believe you could have missed a later blog hence the confusion. For reference please see below with updated information. We released this post on day one of launch week. 

https://supabase.io/blog/2021/03/29/pricing

Specifically i would draw your attention to the point "We will issue credits for those who signed up during alpha, beta, and those who sign up through to the end of Launch Week." 

To give some more context, when we initially announced the credits scheme in December we didn't intend to offer a free tier. The intention was that credits would give users the ability to try Supabase at zero cost in a pricing structure that had every tier as a paid tier.

As we progressed our discussions with users, and as developers ourselves, we felt that having a free tier was important and updated our strategy around pricing. Despite the free tier being now part of our pricing strategy, we still want to honour the commitment we made to our early adopters to give credits to those who signed up early. 

Alpha or beta users who signed up before the end of launch week will therefore get enough credits for the value of 2 years pro tier usage (alpha users $600 credits) and 1 year pro tier usage (beta users $300 credits).  As we are now including a free tier, everyone benefits from being able to try Supabase out for free. The goal is to make Supabase as accessible as possible for everyone and we think this approach honours the earlier announcement and gives broader access to Supabase. 

I hope this clarifies things,

Rory.

**Comment by liflovs** [comment]
Yep, I guess I haven't read everything. Hope this works out as it really seems a surprisingly good offer even just for a managed database itself (guess there are tradeoffs in CPUs or RAM), comparing to Heroku 50$ first offer converting to pay-as-you-go you offer 64*0.125 + 25 = 33 if I understood correctly.

**Comment by dipu7111** [comment]
https://www.fiverr.com/share/X7oKeG
