### ISSUE TITLE
Edge function on local can not connect to database

### ISSUE THREAD

**Issue by nico-wrappt** [supabase/supabase#13045]
# Bug report
Edge function on local can not connect to database

## Describe the bug
Following the example from https://supabase.com/docs/guides/functions/auth I get this error

orker thread panicked ReferenceError: _eventHandlers is not defined
    at get ([js_worker]: bootstrap.js:144:19)
    at Window.get [as onerror] (https://esm.sh/v111/es5-ext@0.10.62/esnext/global.js:15:19)
    at https://esm.sh/v111/es5-ext@0.10.62/esnext/global.js:55:23

## To Reproduce
Follow this steps https://supabase.com/docs/guides/functions/auth 

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: 2
- Version of Node.js: v16.14.0

**Comment by burggraf** [comment]
I can't reproduce this.  If this is still an issue with the current version of edge functions please open a new issue.  Thank you!
