### ISSUE TITLE
Show return value for "Confirmation Email Sent" in guide

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#1304]
it's not clear from the [Client Libary Guide](https://supabase.io/docs/guides/client-libraries) that the default behavior of `signUp` when used with the hosted platform is to send an email confirmation,

we should:

1) include this as a note [here](https://supabase.io/docs/guides/client-libraries) 
2) add an example showing the return value when this happens
3) update any auth [examples](https://github.com/supabase/supabase/tree/master/examples) to handle this scenario

there is a debate whether to have email confirmations on or off by default but I believe having them on is more secure, open to opinions however

**Comment by allstargaurav** [comment]
If this issue is not taken, I would like to work on it.

**Comment by kiwicopple** [comment]
go for it @allstargaurav !
