### ISSUE TITLE
Change docker compose DB exposed ports

### ISSUE THREAD

**Issue by LaurenceJJones** [supabase/supabase#13064]
https://github.com/supabase/supabase/blob/755409c0c8eeca2ca83c5ea13986e0f6f79d44b4/docker/docker-compose.yml#L229

Wouldn't it be best to default for the compose to bind to `127.0.0.1` instead of potentially exposing the port to the internet? as most of the communication is done through docker networking unless the user knows they will be exposing the database to the internet.

This is presuming the user is not deploying with a firewall infront (which is rare) but I don't see why we need to expose it.

```
    ports:
      # Pass down internal port because it's set dynamically by other services
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
```

OR in the secure section we can mention it there https://supabase.com/docs/guides/self-hosting/docker?

Let me know your thoughts

**Comment by squallsama** [comment]
I did the same in my configuration
