### ISSUE TITLE
latest sveltekit framework quickstarts, +layout.svelte error

### ISSUE THREAD

**Issue by wravoc** [supabase/supabase#13082]
# Bug report
## Build a User Management App with SvelteKit

<pre>
  Internal server error: /src/routes/+layout.svelte:6:16 Unexpected token
  Plugin: vite-plugin-svelte
  File: /src/routes/+layout.svelte:6:16
   4 |    import { invalidate } from '$app/navigation';
   5 |    import { onMount } from 'svelte';
   6 |    import type { LayoutData } from './$types';
                        ^
   7 |    
   8 |     (x3)
</pre>

## Describe the bug
Vite build failure, error 500

## To Reproduce

Build Failure in the Quickstart guide after adding +layout.svelte, after `npm run dev` type generation

## System information
MacOS, latest sveltekit build
<pre>
"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0",
		"vitest": "^0.25.3"
	},
	"type": "module",
	"dependencies": {
		"@supabase/auth-helpers-sveltekit": "^0.9.0",
		"@supabase/auth-ui-shared": "^0.1.3",
		"@supabase/auth-ui-svelte": "^0.1.4",
		"@supabase/supabase-js": "^2.11.0"
	}
</pre>

## Additional context
[Relevant TypeScript changes 4.7>4.9](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/)

### lib.d.ts Updates
While TypeScript strives to avoid major breaks, even small changes in the built-in libraries can cause issues. We don’t expect major breaks as a result of DOM and lib.d.ts updates, but there may be some small ones.

### Better Types for Promise.resolve
Promise.resolve now uses the Awaited type to unwrap Promise-like types passed to it. **This means that it more often returns the right Promise type, but that improved type can break existing code if it was expecting `any` or unknown instead of a Promise.** For more information, [see the original change](https://github.com/microsoft/TypeScript/pull/33074).

`supabase: SupabaseClient<any, "public", any>;`

### JavaScript Emit No Longer Elides Imports
When TypeScript first supported type-checking and compilation for JavaScript, it accidentally supported a feature called import elision. In short, if an import is not used as a value, or the compiler can detect that the import doesn’t refer to a value at runtime, the compiler will drop the import during emit.

This behavior was questionable, especially the detection of whether the import doesn’t refer to a value, since it means that TypeScript has to trust sometimes-inaccurate declaration files. In turn, TypeScript now preserves imports in JavaScript files.

## $types.d.ts
`export type LayoutData = Expand<Omit<LayoutParentData, keyof Kit.AwaitedProperties<Awaited<ReturnType<typeof import('./proxy+layout.js').load>>>> & OptionalUnion<EnsureDefined<Kit.AwaitedProperties<Awaited<ReturnType<typeof import('./proxy+layout.js').load>>>>>>;`

**Comment by soonann** [comment]
I'm by no means a Svelte or TS expert. Understand that you'll want a proper fix as per your Additional Context, but if you just need it to work for now, I've referenced the repo of what I got to work below (not sure if it actually works on ur side too):

https://github.com/soonann/supabase-sveltekit

Hope this helps in some way :)

**Comment by wravoc** [comment]
This was fixed [here](https://github.com/supabase/supabase/commit/534b39befd7cdb3e9dc7077cd64cc0dc1da387b7) by updating the '@supabase/auth-helpers-sveltekit' TypeScript just like I said. 

Finally! Thanks for commenting on this issue letting me know it was fixed... ><

**Comment by KevinBrolly** [comment]
I am going to close this issue as it appears to have been fixed, and the issue is now quite stale.

If you are still affected by this issue let us know and we can re-open.
