### ISSUE TITLE
Supabase studio don't allow uploads after change of the digitalocean token & sapces key

### ISSUE THREAD

**Issue by anasfik** [supabase/supabase#13088]
# Bug report

## Describe the bug

I was having a fully working supabase instance in my digital ocean droplet, However I did faced a previous issue that I didn't know where I should point, so I thought that I should update/edit the digitalocean token & spaces key, I deleted previous ones from dashboard, then created the new ones, then opened the console UI of my droplet.

`digitalocean.ini` file where i did updated the digitalocean token:
![image](https://user-images.githubusercontent.com/25140579/226147550-e7993070-64b9-4ee3-a84e-3fcd12b4466f.png)

`.env` file where I did updated the spaces keys:
![image](https://user-images.githubusercontent.com/25140579/226147629-f4f3712d-620a-4f60-9c89-a1dc8cb02095.png)

 
I'am sure the keys which are there does exists in the dashboard of digitalocean!

After that I runned `docker-compose.yml up -d` to apply updates.

and other supabase studio aspects such database and auth still works fine, but in the storage when I do try to upload a file it shows me :
![image](https://user-images.githubusercontent.com/25140579/226147786-3f2c685d-9a1a-4b93-a82c-1f07cdc52c0e.png)

it shows me "accessDenied" but I don't seem to specify what is wrong exactly and what I did wrong or is it even related the leys or other thing, please help me, supabase resources are very limited.  

**update:**
when I do check the console of the browser at this point, I see those permissions 404 errors:

![image](https://user-images.githubusercontent.com/25140579/226150615-24489cc5-b808-4fdb-9d2b-3f566b7a047f.png)
 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Deploying a supabase instance with docker with custom `.env`
2. using the instance, asd ensuring all things working as expected
3. updating `.env` and other keys.
4. running `docker-compose up -d`, to apply changes0

## Expected behavior

At this point, I expect that the while supabase instance got updated with new changes, but the issue happens.
I don't changed anything related to authentication or permissions, I did changed keys related tp storage, which don't work and don't allow for uploading files either from studio or by SDK clients.

## System information

- droplet OS: ubuntu
- Browser   chrome.

## Additional context

I don't know exactly where to look in order to get some debugging logs to point the main issue so it can give more context, I'am sure that the supabase instance did worked fine before, I appreciate any kind of informations that can help me or guide me.

**Comment by anasfik** [comment]
Update 2:
when I check the logs of the storage-api container, I get this log about this log about the request:
```json
{
   "level":"info",
   "time":"2023-03-19T11:08:29.057Z",
   "pid":18,
   "hostname":"b08d1e21d305",
   "reqId":"req-4pl",
   "tenantId":"stub",
   "project":"stub",
   "req":{
      "method":"POST",
      "url":"/object/audibles/my_file.mp3",
      "headers":{
         "host":"storage:5000",
         "x_forwarded_proto":"http",
         "x_real_ip":"172.18.0.6",
         "content_length":"2148787",
         "x_client_info":"supabase-js/2.4.1",
         "user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
         "content_type":"multipart/form-data; boundary=----WebKitFormBoundaryMEtP6MFMq7j2edmB",
         "accept":"*/*",
         "referer":"https://supabase.example.com/project/default/storage/buckets/audibles"
      },
      "hostname":"storage:5000",
      "remoteAddress":"172.18.0.4",
      "remotePort":56762
   },
   "res":{
      "statusCode":400
   },
   "responseTime":137.87750700116158,
   "error":{
      "name":"UnknownError",
      "httpStatusCode":403,
      "originalError":{
         "name":"AccessDenied",
         "$fault":"client",
         "$metadata":{
            "httpStatusCode":403,
            "attempts":1,
            "totalRetryDelay":0
         },
         "Code":"AccessDenied",
         "BucketName":"supabase-e27eaa78a1bd838c",
         "RequestId":"tx000000000000008e8f48b-006416ed2d-3852c4b5-ams3c",
         "HostId":"3852c4b5-ams3c-ams3-zg03",
         "message":"UnknownError"
      }
   },
   "msg":"POST | 400 | 172.18.0.4 | req-4pl | /object/audibles/combined_phrases_week_298_b95f.mp3 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}
```

please, any help or guides throgh this ?

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
