### ISSUE TITLE
Can't sign up users NextJS. Getting invalid claim: missing sub claim

### ISSUE THREAD

**Issue by ismailghedamsi** [supabase/supabase#13095]
# Bug report

## Describe the bug
When using signUp I get an 401 error: invalid claim: missing sub-claim error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
const { error } = await supabase.auth.signUp({
      email: data.email,
      password: data.password,
      options: {
        data: {
          username: data.username
        }
      }
    })
```

## Expected behavior

The user is added to the authentication table and can signIn

## System information

- OS: Ubuntu 20.4
- Version of supabase-js: ^2.11.0

**Comment by ronneldavis** [comment]
Im facing the same issue using the supabase auth UI, for facebook login and google login

**Comment by Nezteb** [comment]
I have this same issue while following the Next.js starter guide: https://supabase.com/docs/guides/auth/quickstarts/nextjs

Even with a fresh new project.

**Comment by swissonid** [comment]
Same Issue here!

I created first a local environment, everything works then I deployed the local one to my supebase account I didn't work at all. Just spent the last 6h trying to fix it. - It seams there is an issue with gotrue but I have no Idea what is cause

**Comment by arthuryeti** [comment]
Same issue here!

**Comment by mendrinos** [comment]
Same here with Nuxt when I upgraded from 0.3.x to 1.0.x

**Comment by adaptivetech-sp** [comment]
I'm also having a similar issue with creating a user from the server side in next.js. 
This works locally, in dev/vercel deployed environment getting the following error 401 - missing sub claim

**Comment by farefray** [comment]
same issue here, weird thing that SOMETIMES it works... Is thats really still has no reaction/solution?

**Comment by Nezteb** [comment]
cc @kiwicopple 😅

**Comment by farefray** [comment]
FYI I replaced auth implementation into the one from NextJS examples, to handle sign in via /app/auth/callback/route, like in here: https://github.com/vercel/next.js/tree/canary/examples/with-supabase and now its working fine, but the original example is not working, indeed.

**Comment by dijonmusters** [comment]
When using a server-side framework - like Next.js - we recommend using the `@supabase/ssr` package to configure `supabase-js` to use cookies, making the user's session available server-side. This package also configures the PKCE auth flow, meaning you need the `/auth/callback` route mentioned above to exchange the user's auth code for a session. The original code snippet for signing up should redirect the auth flow to this route:

```
const { error } = await supabase.auth.signUp({
    email: data.email,
    password: data.password,
    options: {
      data: {
        username: data.username
      },
      emailRedirectTo: 'http://localhost:3000/auth/callback'
    }
  })
```

To ensure all of this in configured properly, I recommend running this command as a starting point, as it has all the server-side auth and cookies stuff setup already! 🚀

```
npx create-next-app -e with-supabase
```

**Comment by Nezteb** [comment]
> To ensure all of this in configured properly, I recommend running this command as a starting point, as it has all the server-side auth and cookies stuff setup already! 🚀
> 
> ```
> npx create-next-app -e with-supabase
> ```

[When I commented on this issue five months ago](https://github.com/supabase/supabase/issues/13095#issuecomment-1635184549), I had tried exactly that and it did not work. 😅 

No one on my team has tried since though, as we had to choose a tool other than Supabase because of this. 😭

**Comment by supreme** [comment]
Still having issues with this creating a fresh copy via:

```
npx create-next-app -e with-supabase
```

**Comment by PiessensLander** [comment]
I'm having the exact same issue on my project. Signing in for the first time works fine, but after logging out and trying to log in again the server responds with 401: missing sub claim. Works fine locally but as soon as I deploy it somewhere it breaks.

**Comment by ItaiAxelrad** [comment]
Started a new project with `npx create-next-app -e with-supabase` and still getting the same `403: invalid claim: missing sub claim` error
