### ISSUE TITLE
Editing a columns Default values does not work.

### ISSUE THREAD

**Issue by pnadj** [supabase/supabase#13103]
I believe there is a bug with changing the default values of a column in UI. As seen below I have created the default value 'USER' in user_roles with allow nullable switched off:

<img width="395" alt="Screen Shot 2023-03-20 at 9 05 44 pm" src="https://user-images.githubusercontent.com/93848479/226309290-434725ec-f2e0-4336-a0a7-fc484b8f001b.png">

This causes the error as shown below when trying to add a new user:

<img width="357" alt="Screen Shot 2023-03-20 at 9 06 16 pm" src="https://user-images.githubusercontent.com/93848479/226309327-952c9a87-65d4-4d7b-a140-5aff137c3add.png">

After switching on 'allow nullable' the default value is not set as USER but as NULL

<img width="357" alt="Screen Shot 2023-03-20 at 9 06 45 pm" src="https://user-images.githubusercontent.com/93848479/226309329-d7499029-d8a9-4e1f-b79e-d4ff80758ab0.png">

**Comment by GaryAustin1** [comment]
Is the row with null already existing?  Or are you creating a new row and the new default is not working?  Default is not going to change existing rows.

**Comment by pnadj** [comment]
@GaryAustin1 New row, but I tried again today without making any changes and it works now.

**Comment by GaryAustin1** [comment]
I tried a few things and could not replicate an issue.
I'm going to move this to closed for the moment, but certainly post here if you see this again.

**Comment by pnadj** [comment]
@GaryAustin1 Unfortunately I created a new table where one field 'account_type' cannot be null but default set to 'STAFF'. And on creation with a trigger + function it still causes this error that it breaks the null constaint. If it has a default value this shouldn't happen

<img width="357" alt="Screen Shot 2023-03-22 at 10 07 07 pm" src="https://user-images.githubusercontent.com/93848479/226886022-7d267297-2fe2-497e-ad74-7ab968e43724.png">

**Comment by GaryAustin1** [comment]
You can't provide that column with null if you are doing that, it will replace the default value with null.   You have to not set the column at all.

**Comment by pnadj** [comment]
`
begin
  insert into public.profiles (id, account_type, full_name)
  values (new.id, new.raw_user_meta_data->>'account_type', new.raw_user_meta_data->>'full_name');
  return new;
end;
`
        
I see, so the user creation trigger function was setting it as null and causing the error. Thanks that makes sense, my fault for copying the trigger example without thought lol
