### ISSUE TITLE
Bounty: $50 /auth/v1/token?grant_type=id_token is always returning oidc: id token issued by a different provider

### ISSUE THREAD

**Issue by ZeroHans4** [supabase/supabase#13113]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Make a post request to https:// your url.supabase.co/auth/v1/token?grant_type=id_token directly setting your apikey in the headers or use the signInWithIdToken methods in JS or Dart.

The parameters id_token is the access_token from google oauth response
provider is set tot "google"

## Expected behavior

Return valid auth / sign the user in on js / dart

## Additional context

Tested on Dart, JS and directly via Insomnia Post request

Paying $50 bounty (if that is allowed) to anyone that can help me solve this and successfully implement google login for flutter desktop using the signInWithIdToken (Or any other way)

**Comment by GaryAustin1** [comment]
This might be relevant for you (towards the end) https://github.com/supabase/supabase-flutter/issues/5

**Comment by ZeroHans4** [comment]
bumping this

**Comment by dshukertjr** [comment]
With Flutter, you can sign in a user With Google natively on a MacOS with the following code. We will create a shorter method for this in the near future so that developers don't have to go through this process manually.

```dart
import 'dart:convert';
import 'dart:math';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_appauth/flutter_appauth.dart';

Future<AuthResponse> signInWithGoogle(String clientId) {
  // Just a random string
  final rawNonce = _generateRandomString();
  final hashedNonce =
      sha256.convert(utf8.encode(rawNonce)).toString();
    
  /// bundle ID of the app
  const bundleId = 'com.supabase.authflow';
  
  /// fixed for google login
  // const redirectUrl = '$bundleId:/google_auth';
  const redirectUrl = '$bundleId:/google_auth';
  
  /// fixed for google login
  const discoveryUrl =
      'https://accounts.google.com/.well-known/openid-configuration';
  
  // authorize the user by opening the concent page
  final result = await appAuth.authorize(
    AuthorizationRequest(
      clientId,
      redirectUrl,
      discoveryUrl: discoveryUrl,
      nonce: hashedNonce,
      scopes: [
        'openid',
        'email',
      ],
    ),
  );
  
  if (result == null) {
    return;
  }
  
  // Request the access and id token to google
  final tokenResult = await appAuth.token(
    TokenRequest(
      clientId,
      redirectUrl,
      authorizationCode: result.authorizationCode,
      discoveryUrl: discoveryUrl,
      codeVerifier: result.codeVerifier,
      nonce: result.nonce,
      scopes: [
        'openid',
        'email',
      ],
    ),
  );
  
  final idToken = tokenResult?.idToken;
  
  if (idToken == null) {
    throw 'No idToken';
  }
  
  return supabase.auth.signInWithIdToken(
    provider: Provider.google,
    idToken: idToken,
    nonce: rawNonce,
  );
}
```

**Comment by dshukertjr** [comment]
I'm going to close this issue as a solution has been presented, but there hasn't been any response. Please feel free to reopen it if you need further assistance.
