### ISSUE TITLE
Unable to view Foreign Tables unless one or more real table exisits

### ISSUE THREAD

**Issue by AdamKearn** [supabase/supabase#13173]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi,  I have noticed that if you have a Postgres database with only `Foreign Tables` and zero "normal" tables it will show say there are zero tables in the studio page.

However, adding a single table then allows the Foreign Tables to be viewed.  (see screenshots below)

In my testing I have noticed that if you copy the URL of the view for the `Foreign Table` and then delete the "normal" table it still lets you view the data inside while still listing that there is no clickable view.

## Expected behavior

Superbase should be listing the `Foreign Tables` (providing there is 1 or more) without needing at least one normal table.

## Screenshots

Before:
![image](https://user-images.githubusercontent.com/30593259/227351841-5e315191-38eb-4e61-b989-eb77832ae402.png)

After adding a single table it then shows both Foreign Tables and also normal tables.
![image](https://user-images.githubusercontent.com/30593259/227352412-00e52bfb-0559-470e-a534-731b29780ccb.png)

Deleting the temporary table and going to the URL:
![image](https://user-images.githubusercontent.com/30593259/227355277-0ca6453c-c6da-4d73-8976-b4958a576a6f.png)

## System information

- OS: Linux/Docker
- Browser (if applies) Chrome
- Version of supabase-js: (docker image supabase/studio:20230216-e731b77)

**Comment by tiwari-ai-harsh** [comment]
Hi, can I start working on this issue?

**Comment by AdamKearn** [comment]
> Hi, can I start working on this issue?

Hi if you are able to look into this issue it would be much appreciated.

We are only using supabase for GraphQL integration with our Existing SQL database.

**Comment by tiwari-ai-harsh** [comment]
> > Hi, can I start working on this issue?
> 
> Hi if you are able to look into this issue it would be much appreciated.
> 
> We are only using supabase for GraphQL integration with our Existing SQL database.

Hi, I'm new to this project and was not able to setup the development environment correctly sorry for the inconvinence I'm gonna pass on this issue.

**Comment by burmecia** [comment]
Is this still an issue as I cannot reproduce it? I created a whole new project with only one foreign table, it shows correctly on the table list. Could you check it again?

**Comment by AdamKearn** [comment]
> Is this still an issue as I cannot reproduce it? I created a whole new project with only one foreign table, it shows correctly on the table list. Could you check it again?

Hi thanks for looking into this.
How do you have your environment setup?   I am currently using docker (supabase/studio:20230216-e731b77)

I'm unsure if the issue is related  to the specific docker image I'm using.

Regards
Adam

**Comment by burmecia** [comment]
> How do you have your environment setup? I am currently using docker (supabase/studio:20230216-e731b77)

I am using the latest version docker image (supabase/studio:20230328-a8e41fc), in which it should already be fixed.

**Comment by saltcod** [comment]
Going to mark this one as resolved as we've changed the handling of tables here. Please feel free to open it back up if you're still experiencing issues.
