### ISSUE TITLE
Non matching Border Radii

### ISSUE THREAD

**Issue by aayusharyan** [supabase/supabase#1319]
# Bug report

On the homepage, for the code examples, the border radii are not equal. For most of the developers, this will be fine, but for some select few, honestly. This feels like a nightmare. (Specially for Frontend folks who land on the homepage).

## To Reproduce

1. Go to [the homepage](https://supabase.io/auth).
2. Check the code editor examples.
3. See error

## Expected behavior

Both the inner border radius and the outer border radius needs to look seamless.

## Screenshots

<img width="1248" alt="Screenshot 2021-04-29 at 11 53 13 PM" src="https://user-images.githubusercontent.com/16634228/116599744-1af4fc80-a946-11eb-9b20-e5ff6aab8cbb.png">

## System information

NA

## Additional context

I couldn't find the CSS file, otherwise I would've created the PR. (If someone from the team can guide me to the file, It'll be awesome).
Otherwise, to fix this, need to change `border-radius` to `.275rem` for `.CodeBlock_code-block__jahvg` selector in `14919cd3beef7d326136.css` (Which is possibly a generated file).
But after fixing, will look like this which will not trigger OCD of some engineers.
<img width="1248" alt="Screenshot 2021-04-29 at 11 56 53 PM" src="https://user-images.githubusercontent.com/16634228/116600150-9ce52580-a946-11eb-8d4b-089eb8aafea6.png">

**Comment by kiwicopple** [comment]
Well spotted @aayusharyan 👍 

@MildTomato might be able to point you towards the right file here

**Comment by MildTomato** [comment]
Yea this is a bit of a mess, it also triggers me a bit 😅 
@aayusharyan I think all the styling is just tailwind classes - might be why you couldn't find anything in a stylesheet.

I think I left fixing it because we use the code example component inside other components that also have borders and we got slammed with other work. I'll have a quick look now, might be quite easy to fix.
