### ISSUE TITLE
Auth not correctly passed with foreign key relationships

### ISSUE THREAD

**Issue by quick007** [supabase/supabase#13198]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I've been having this really weird error where it seems like auth isn't passed correctly. For example, a simple request like this:
```ts
//...
.select(`
  *,
  users_groups (
    *
  )
`)
//...
```

Assuming that the users_groups table has a rls policy like this:
![image](https://user-images.githubusercontent.com/69743171/227733990-c1cb7fa1-f089-4f16-af7a-23b66fb69da5.png)
When fetched, it won't return the correct data. When the authenticated role is removed (which sets it to public), the correct data is fetched. Note that when fetching the table by itself (not using fkey relationships) with the authenticated role on, the correct data is fetched.

## Expected behavior

I expect that the correct data is returned. 

## Screenshots

Screenshots above, I (and @Illgive) can provide more info if helpful

## System information

- OS: macOS
- Browser (if applies) Chrome
- Version of supabase-js: 
```
"@supabase/auth-helpers-nextjs": "^0.5.6",
"@supabase/auth-helpers-react": "^0.3.1",
"@supabase/supabase-js": "^2.12.1",
```
- Version of Node.js:  v16.17.0

**Comment by GaryAustin1** [comment]
Can you link where you asked for help on this in Discord or Discussions with more detail?
This seems like something that needs to be worked out in your code as this is a very common case that works.

**Comment by quick007** [comment]
We haven't asked on the discord yet, I'll temporarily close this and then reopen it if we can't find a fix to the issue
