### ISSUE TITLE
.match filter not using quotes for keys unlike all other filters.

### ISSUE THREAD

**Issue by Zebnastien** [supabase/supabase#13201]
[X] I confirm this is a bug with Supabase, not with my own application.
[X] I confirm I have searched the [Docs](https://docs.supabase.com/), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com/).

**Here are some examples of filters from the Supabase documentation:**
https://supabase.com/docs/reference/javascript/filter

```
.eq('name', 'Albania')
.like('name', '%Alba%')
.in('name', ['Albania', 'Algeria'])
.rangeLt('during', '[2000-01-01 15:00, 2000-01-01 16:00)')
.not('name', 'is', null)
```

As you can see, both keys and values are quoted.
**But here is the "match" filter:**
https://supabase.com/docs/reference/javascript/match

`.match({ id: 2, name: 'Albania' })`

**Values are quoted, but keys are not. This is a problem for coherence.**
For example, in my specific case, it makes the .match filter difficult to use with Nuxt api server because the getQuery() function automatically convert query params to a quoted keys object, so Supabase does not recognize the quoted column name.

This is a sad because .match filter is an awsome feature, more convenient than .eq filter.
At your disposal for more information if needed.

**Comment by GaryAustin1** [comment]
The only reason I don't close this is you mention Nuxt which I don't know about.   The .match filter is taking a Javascript object with key value pairs.   You should be able to use `{'id': 2,'name':'Albania'}` with quotes or not.   It is just JS.

**Comment by Zebnastien** [comment]
Right, I will investigate more and provide more information this afternoon.

**Comment by Zebnastien** [comment]
Ok you are totally right, I found the problem:

Nuxt provide $fetch function where I pass my filter object with the "query" props.
Then, I get this object on Nuxt 3 server thanks to Nuxt's getQuery( ) method providedby https://github.com/unjs/h3.

What I didn't realise is query object is automatically stringified with getQuery( ). Parsing the data made it right.
Sorry for false alarm. I am not very experienced and I was abused by the lack of quotes only on match filters. I though I had better checked my code.

Thanks for answering so quickly.
