### ISSUE TITLE
New tables don't generate id for rows

### ISSUE THREAD

**Issue by akselw** [supabase/supabase#1321]
# Bug report

## Describe the bug

When I created some tables in the table editor last week I could specify that the primary key was a uuid, and when I created a row, the id field said:

![image](https://user-images.githubusercontent.com/5320566/116616844-71117200-a93d-11eb-96a6-11b451d92b91.png)

However, when I try to create tables today, it seems that all the tables are created without the id being generated automatically, even though I think I did the exact same thing:

![image](https://user-images.githubusercontent.com/5320566/116617033-b170f000-a93d-11eb-979b-0c42d2dd9032.png)

When I check the information shema, I see that the tables I made last week have a `column_default` of `uuid_generate_v4()`, while the schemas I made today have a blank `column_default`.

## To Reproduce

1. Go to the Table Editor at `/project/{id}/editor/table`
2. Click "New table"
3. Type a name
4. Select "Include primary key"
5. Choose "uuid" from the dropdown menu
6. In the newly created table, click "Add row"

The id field does not say that it will be automatically generated, and you can't save the row unless you type in a uuid.

![image](https://user-images.githubusercontent.com/5320566/116617932-b4201500-a93e-11eb-864e-7cb5107bca53.png)

## Expected behavior

That new tables created with a uuid primary key should be have a `column_default` of `uuid_generate_v4()`.

## System information

- OS: macOS
- Browser: Safari

**Comment by sinedie** [comment]
While they fix it. You still can go to database -> tables -> yourTable and set the default value for the row:

![image](https://user-images.githubusercontent.com/43920544/118383075-74089580-b5c0-11eb-87d0-50a83d329d6e.png)

![image](https://user-images.githubusercontent.com/43920544/118383088-91d5fa80-b5c0-11eb-877a-963684df6657.png)

![image](https://user-images.githubusercontent.com/43920544/118383094-9e5a5300-b5c0-11eb-9290-bf910c26da5e.png)

It'll take a while (seems like it doesnt update) but in a few minutes -maybe 10, idk, didnt count- you can create a row and test if it worked. 

![image](https://user-images.githubusercontent.com/43920544/118383139-ebd6c000-b5c0-11eb-827b-b0a93d0c6a6b.png)

![image](https://user-images.githubusercontent.com/43920544/118383123-d82b5980-b5c0-11eb-88f5-e1a9c2a3753c.png)

**Comment by kiwicopple** [comment]
This is now fixed on the table editor as well as the Database > Tables section
