### ISSUE TITLE
Error from UUID column returned as data

### ISSUE THREAD

**Issue by justin-gurtz** [supabase/supabase#13243]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When matching a UUID column with a malformed UUID or a value that doesn't exist, the `error` is returned as `data`. In the example below, I'm essentially trying to force a 404 error in my application by using a fake `public_id`.

## To Reproduce

```
// Code example
const { data, error } = await supabase
  .from('members')
  .select()
  .eq('public_id', ...)
  .single()
```
```
// Successful response ✔️
{
  error: null,
  data: {
    id: ...,
    created_at: ...,
    email: ...,
    name: ...,
    public_id: ...,
    organization_id: ...
  },
  count: null,
  status: 200,
  statusText: ''
}
```
```
// Error responses from valid – but not found – UUIDs ✔️/❌
// I've seen both and I don't know how to trigger one or the other
{
  error: {
    code: 'PGRST116',
    details: 'Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row',
    hint: null,
    message: 'JSON object requested, multiple (or no) rows returned'
  },
  data: null,
  count: null,
  status: 406,
  statusText: ''
}
{
  error: null,
  data: {
    code: 'PGRST116',
    details: 'Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row',
    hint: null,
    message: 'JSON object requested, multiple (or no) rows returned'
  },
  count: null,
  status: 200,
  statusText: ''
}
```
```
// Error response from malformed UUID ❌
{
  error: null,
  data: {
    code: '22P02',
    details: null,
    hint: null,
    message: 'invalid input syntax for type uuid: "123"'
  },
  count: null,
  status: 200,
  statusText: ''
}
```

## System information

- Version of supabase-js: 2.11.0
- Version of Node.js: 18.12.1

**Comment by nith2001** [comment]
Can you example of a malformed UUID? Not sure what that means.

**Comment by nith2001** [comment]
Assuming this is what you were referring to, I ran the necessary tests locally with correct UUIDs, incorrect UUIDs, and invalid UUIDs and I never got the response that you got.

**Comment by justin-gurtz** [comment]
> Can you example of a malformed UUID? Not sure what that means.

Malformed UUID meaning a string that doesn't match the UUID v4 format, which is something like `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx`. In my example I tested using the string `"123"`, as well as a valid UUID in which I deleted the final character so it would no longer match the v4 format.

The problem column is set up like this:

<img width="541" alt="Screenshot 2023-04-09 at 15 48 18" src="https://user-images.githubusercontent.com/40037115/230793587-557874ba-5b08-483b-bc8c-09b87c574cb9.png">

**Comment by justin-gurtz** [comment]
That being said, I'm having trouble recreating the error as `data`. I'm using the Next.js 13 app directory (React 18 server components) and I realized the bug was cached. But I'm not sure what originally caused it, and whether or not it was fixed.

```
// app/page.tsx

const page = async () => {
  const supabase = createServerComponentSupabaseClient<Database>({
    headers,
    cookies,
  })

  const test = await supabase
    .from('members')
    .select()
    .eq('public_id', '123')
    .single()

  console.log(test)
}
```
```
// console

{
  error: null,
  data: {
    code: '22P02',
    details: null,
    hint: null,
    message: 'invalid input syntax for type uuid: "123"'
  },
  count: null,
  status: 200,
  statusText: ''
}
```

Then I add `export const revalidate = 0` and the error is returned as `error` as expected

```
// app/page.tsx

export const revalidate = 0

const page = async () => {
  const supabase = createServerComponentSupabaseClient<Database>({
    headers,
    cookies,
  })

  const test = await supabase
    .from('members')
    .select()
    .eq('public_id', '123')
    .single()

  console.log(test)
}
```
```
// console

{
  error: {
    code: '22P02',
    details: null,
    hint: null,
    message: 'invalid input syntax for type uuid: "123"'
  },
  data: null,
  count: null,
  status: 400,
  statusText: 'Bad Request'
}
```

**Comment by nith2001** [comment]
Strange. The issue must definitely be Next.js specific because I ran all of the examples from above at supabase-js version 2.11.0 with a regular NodeJS script and didn't face any of the data-error swapping issues. Here's some of the testing I did:

```
// Correct UUID
const response = await supabase
.from('test_uuid')
.select()
.eq('id', '7a2eabc4-adf0-47a2-a44f-12417bf3f29a')
.single()

console.log(`Correct UUID: ${JSON.stringify(response, null, 2)}`)

// Incorrect UUID
const response = await supabase
.from('test_uuid')
.select()
.eq('id', '7a2eabc4-adf0-47a2-a44f-12417bf3f29b')
.single()

console.log(`Incorrect UUID: ${JSON.stringify(response, null, 2)}`)

// Malformed UUID
const response = await supabase
.from('test_uuid')
.select()
.eq('id', '123')
.single()

console.log(`Malformed UUID: ${JSON.stringify(response, null, 2)}`)

```
Ran it about ~50 times, always the got the following response:
```
Correct UUID: {
  "error": null,
  "data": {
    "id": "7a2eabc4-adf0-47a2-a44f-12417bf3f29a",
    "created_at": "2023-04-09T23:59:10.987228+00:00"
  },
  "count": null,
  "status": 200,
  "statusText": "OK"
}
Incorrect UUID: {
  "error": {
    "code": "PGRST116",
    "details": "Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row",
    "hint": null,
    "message": "JSON object requested, multiple (or no) rows returned"
  },
  "data": null,
  "count": null,
  "status": 406,
  "statusText": "Not Acceptable"
}
Malformed UUID: {
  "error": {
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for type uuid: \"123\""
  },
  "data": null,
  "count": null,
  "status": 400,
  "statusText": "Bad Request"
}
```
My guess is the error is something specific to Next.js, maybe related to the `createServerComponentSupabaseClient` function and how function calls are made from it. Might have to do more investigation into that.

**Comment by nith2001** [comment]
@justin-gurtz Okay, I just duplicated what you described above with a Next app, here's my setup and what I got:

Supabase-related package.json dependencies: 
```
"@supabase/auth-helpers-nextjs": "^0.6.0",
"@supabase/supabase-js": "2.11.0",
"next": "13.3.0",
"postcss": "8.4.21",
"react": "18.2.0",
"react-dom": "18.2.0",
"supabase": "^1.50.2",
  }
```

Function to make Postgres call:
```
const page = async () => {
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  })

  const test = await supabase
    .from('test')
    .select()
    .eq('id', '123')
    .single()

  console.log(JSON.stringify(test, null, 2))
}
```

Whether I included the `export const revalidate = 0` line or not, here was my output:
```
{
  "error": {
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for type uuid: \"123\""
  },
  "data": null,
  "count": null,
  "status": 400,
  "statusText": "Bad Request"
}
```

The only thing left to check might be your version number of the `@supabase/auth-helpers-nextjs` dependency. Any thoughts?

**Comment by justin-gurtz** [comment]
My version of `@supabase/auth-helpers-nextjs` is 0.5.6, but since the bug was cached it's possible it occurred in an even earlier version. Since even I'm having trouble replicating the bug I'm tempted to close this issue.

For what it's worth, these are my Supabase-related dependencies:
```
"@supabase/auth-helpers-nextjs": "^0.5.6",
"@supabase/auth-helpers-react": "^0.3.1",
"@supabase/supabase-js": "^2.14.0",
"next": "^13.2.4",
"react": "^18.2.0",
"react-dom": "18.2.0",
```

**Comment by nith2001** [comment]
Yeah, I'm inclined to agree with you on closing this issue but feel free to ping me if it resurfaces since it seems quite interesting!
