### ISSUE TITLE
Cannot access storage tab in dashboard

### ISSUE THREAD

**Issue by bokub** [supabase/supabase#13259]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have 2 projects on Supabase.

For only one of them, I get the following error every time I try to access the "storage" tab from the dashboard:

> permission denied for schema storage

## Screenshots

![image](https://user-images.githubusercontent.com/17952318/228246198-f25922cd-2da7-4110-bfda-cdd14eec9e0d.png)
![image](https://user-images.githubusercontent.com/17952318/228246385-341afd9c-f5a9-42a5-89d9-387dd1f51402.png)

![image](https://user-images.githubusercontent.com/17952318/228246106-37680dcd-3c80-4c79-8920-599e3c1bb154.png)

## System information

- OS: Ubuntu
- Browser (if applies): Chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by GaryAustin1** [comment]
For some reason your permissions on the storage schema are messed up.  A migration or perhaps Prisma has changed the grants?

**Comment by bokub** [comment]
Yeah, it's possible that I broke the storage schema while trying to restore a backup... :confused: 

Is there any way to reset these permissions, or event better, replicate the permissions from my other "healthy" supabase project?

Thanks!

**Comment by MildTomato** [comment]
@bokub could you open a support ticket on https://app.supabase.io/support/new ?

Looks like this might be a project specific issue.

**Comment by saltcod** [comment]
Going to close this one in the meantime as it looks project specific.
