### ISSUE TITLE
`provider_refresh_token` is missing with google auth provider

### ISSUE THREAD

**Issue by mathix420** [supabase/supabase#13266]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`provider_refresh_token` is missing from the url parameters in the callback after logging-in with google auth provider.

Redacted callback url:
```
http://localhost:3000/#access_token=x.x.x&expires_in=3600&provider_token=x.x&refresh_token=x&token_type=bearer
```

## To Reproduce

Blank `nuxt@3.3.2` app with `@nuxtjs/supabase@0.3.1`.

**app.vue**
```vue
<script setup lang="ts">
const client = useSupabaseAuthClient();

// Login method using providers
async function login() {
  const { error } = await client.auth.signInWithOAuth({
    provider: "google",
    options: {
      scopes: "https://www.googleapis.com/auth/youtube.readonly"
    },
  });
  if (error) {
    return alert("Something went wrong !");
  }
}
</script>

<template>
  <main>
    <h1>Login page</h1>

    <button @click="login">Login with google</button>
  </main>
</template>
```

1. **Inspect** the page, go to **Network** tab, tick **Preserve log**
2. Click on the **Login with google** button
3. Give google & youtube permissions
4. After the callback occurs, you can see in the network tab that `provider_refresh_token` is missing

## Expected behavior

`provider_refresh_token` should be present.

## System information

- OS: archlinux
- Browser (if applies) chrome-stable
- Version of supabase-js: 2.7.1
- Version of Node.js: v16.19.1

**Comment by gumybit** [comment]
@mathix420 
Is this help you?
https://supabase.com/docs/guides/auth/social-login/auth-google#add-login-code-to-your-client-app

>Google OAuth2.0 doesn't return the provider_refresh_token by default. If you need the provider_refresh_token returned, you will need to add additional query parameters:

**Comment by mathix420** [comment]
@gumybit exactly what I was looking for 😅
Idk why I missed it, ty!
