### ISSUE TITLE
The "See documentation" button links to a 404 page on the auth page of the main site

### ISSUE THREAD

**Issue by shareefhadid** [supabase/supabase#13262]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The "See documentation" button links to a 404 page on the [auth page](https://supabase.com/auth) of the main site. Appears to have the correct URL, but is triggering a redirect to a 404.

## To Reproduce

1. Go to https://supabase.com/auth
2. Click the "See documentation" button
3. See 404

## Expected behavior

Should go to https://supabase.com/docs/guides/auth

### 1. https://supabase.com/auth
![image](https://user-images.githubusercontent.com/40722223/228281018-b7315766-0dd4-4437-ade2-e68395ffd501.png)
### 2. Leads to https://supabase.com/docs/guides/auth/overview
![image](https://user-images.githubusercontent.com/40722223/228281196-19af60cf-e955-401f-99c2-9926b56129d1.png)

## System information

- OS: Windows
- Browser (if applies) Chrome

## Additional context

Sorry if there is a separate repo where this should be directed, I could not find it.

**Comment by MildTomato** [comment]
fixed in #13275
