### ISSUE TITLE
Deleting a user on the /auth/users page shows null

### ISSUE THREAD

**Issue by apuchitnis** [supabase/supabase#13268]
# Bug report
- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I have a trigger on auth.user row deletion, and I go to https://app.supabase.com/project/ID/auth/users and select "delete user", I get the following modal referencing 'null' -- the copy should probably display an ID instead.

![image](https://user-images.githubusercontent.com/10189197/228313467-8ab786ae-e748-408e-8772-7723731af641.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.com/project/ID/auth/users
2. Hover over '...' on a user
3. Click on 'delete user'
4. View pop up

## Expected behavior

I don't see null.

## Screenshots

See above.

**Comment by dsukruth** [comment]
![image](https://user-images.githubusercontent.com/43529945/228336630-96fbedc6-41c1-4d53-9e07-42cc185280af.png)
Could not replicate it, working fine!

**Comment by apuchitnis** [comment]
CC @burggraf - we discussed this on slack! Seems like he wasn't able to repro, but I still am able to repro myself.

**Comment by nith2001** [comment]
Is there a Supabase Slack server for community open-source devs?

**Comment by saltcod** [comment]
Can't reproduce. Going to mark as resolved, but feel free to reopen if you still see this.
