### ISSUE TITLE
Next.js 13 (app dir) docs incomplete

### ISSUE THREAD

**Issue by y-nk** [supabase/supabase#13280]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components

## Describe the problem

1. Some of the code example are missing pieces necessary to make it work. For example the provider is missing router import, and accessToken state.

    <details>
    
    ```tsx
    'use client'

    // import { useRouter } from 'next/navigation' ← MISSING
    import { createContext, useContext, useState } from 'react'
    import { createClient } from '../utils/supabase-browser'
    
    const Context = createContext() // ← INVALID IN TS. should be: createContext<{ supabase?: ReturnType<typeof createClient> }>({})
    
    export default function SupabaseProvider({ children }) {
      // const router = useRouter() ← MISSING
      // const [accessToken, setAccessToken] = useState() ← MISSING

      const [supabase] = useState(() => createClient())
    
      useEffect(() => {
        const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
          if (session?.access_token !== accessToken) { // ← accessToken is undefined
            router.refresh() // ← router is undefined
          }
        })
    
        return () => subscription.unsubscribe()
      }, [accessToken])
    
      return (
        <Context.Provider value={{ supabase }}>
          <>{children}</>
        </Context.Provider>
      )
    }
    
    export const useSupabase = () => useContext(Context)
    ```

    </details>

2. Overall the boilerplate could be all packaged in the nextjs-helper package. I mean, if this code is generic enough to be copy/pasted from a tutorial and that there is already a nextjs-helper, it feels it should go there and cut to the chase instead.

## Describe the improvement

1. Test the doc/tutorial before publishing it
2. Maybe publish the content of this tutorial as part of nextjs-helper package

## Additional context

Nothing, just thank you, supabase is awesome.

**Comment by ThanosDodd** [comment]
useEffect also not imported in the docs

**Comment by Hallidayo** [comment]
Hi @y-nk - Just had a look and it seems the docs have been updated now?

**Comment by breadadams** [comment]
There are a few missing in [this](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components#:~:text=Modify%20layout.jsx%20to%20wrap%20the%20application%20with%20the%20%3CSupabaseProvider%3E%20component) section, for instance `session`:

<img width="963" alt="image" src="https://github.com/supabase/supabase/assets/5795227/c845674c-f6bd-4a3f-8a0a-65b16c4a3ebc">

**Comment by gregnr** [comment]
Thanks for reporting this @y-nk! And thank you @breadadams for the fixes/improvements.

It looks like everything here has now been updated, so I'll close this now. Feel free to re-open if you feel anything else is missing.
