### ISSUE TITLE
fix: match_threshold

### ISSUE THREAD

**Issue by kagia** [supabase/supabase#13318]
# Improve documentation

## Link 

https://supabase.com/blog/openai-embeddings-postgres-vector

## Describe the problem

The example does not work because there is a parameter mismatch.

The signature of the postgres function is `match_documents(match_count, query_embedding, similarity_threshold)`

but the rpc call looks for `match_documents(match_count, match_threshold, query_embedding)`

## Describe the improvement

replace mentions of `match_threshold` with `similarity_threshold`

I prefer "similarity" because conveys inexactness.

## Additional context

It's a small fix so if you're happy with my suggestions I can file a PR right away.

**Comment by KevinBrolly** [comment]
>It's a small fix so if you're happy with my suggestions I can file a PR right away.

@kagia Would love a PR for this if you could!

**Comment by Hallidayo** [comment]
Hi all, just checking is this an issue still as I can't seem to find any issues?

**Comment by kagia** [comment]
@Hallidayo  seems to be fixed
