### ISSUE TITLE
Auth Github Bug

### ISSUE THREAD

**Issue by ejscf** [supabase/supabase#1332]
# Bug report

## Describe the bug

When I use 'supabase.auth.signIn ({provider:' github '})' he keeps restarting the page several times without stopping.

**Comment by kiwicopple** [comment]
Hey @ejscf thanks for trying out Supabase!

For us to help we will need to see some code which is replicates the problem. If you can share a repo, or set up a small sample we can help out :)

I'll close this for now, but feel free to reopen if you have a testable example
