### ISSUE TITLE
Broken link (404) for "Edge Functions -> Connect to Postgres" example

### ISSUE THREAD

**Issue by rohan-kadkol** [supabase/supabase#13328]
# Improve documentation

## Link 

https://supabase.com/docs/guides/functions has a button called `Connect to Postgres`.

![image](https://user-images.githubusercontent.com/45748283/228995859-c1d4aa8a-4721-4f7c-97cd-03db7a69bab6.png)

Clicking on it gives a 404 error (https://supabase.com/docs/guides/functions/examples/connect-to-postgres).

![image](https://user-images.githubusercontent.com/45748283/228995896-d18b210e-310c-42ae-a24b-367971bc2405.png)

## Describe the problem

Broken link

## Describe the improvement

Should point to the correct link

## Additional context

N/A

**Comment by dhavall13** [comment]
Hello, can I get this issue assigned to myself if it is open?

**Comment by gregnr** [comment]
Hey @dhavall13, thanks for offering to help! This issue is already nearly resolved in this PR: https://github.com/supabase/supabase/pull/13335, so we should be good here.

**Comment by dhavall13** [comment]
Okay thanks

**Comment by sambhavgupta0705** [comment]
Hey @gregnr ,the mentioned PR has been closed so can I work on this issue.

**Comment by gregnr** [comment]
Hey @sambhavgupta0705! That was closed due to an accidental dupe: https://github.com/supabase/supabase/pull/13831.

Closing this now as complete.
