### ISSUE TITLE
Shortcut for search (ctrl/k) opens Chrome search bar along with desired search function

### ISSUE THREAD

**Issue by hirwaaldo1** [supabase/supabase#13339]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When attempting to use the shortcut for search (ctrl/k) in Google Chrome, the intended search function works as expected. However, at the same time, the search bar for Google Chrome also opens up, which may cause confusion and inconvenience for users. This bug needs to be addressed to ensure a smooth and streamlined search experience for Chrome users.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase docs](https://supabase.com/docs)
2. Press ctrl/k 

## Expected behavior
When using the shortcut, only the superbase search bar will be activated, not the Chrome search bar.
## Screenshots
![Supabase Docs - Google Chrome 3_31_2023 11_30_28 AM](https://user-images.githubusercontent.com/51756396/229082974-e59ee5aa-cc33-4bac-a37e-2432e0812352.png)
You can see that it opens both search bars.
## System information

- OS:  Windows
- Browser: chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
I believe that fixing this error involves preventing the default behavior.

**Comment by MildTomato** [comment]
Think this has been fixed now, i saw a fix get merged before.
Please reopen if you still see the issue

**Comment by hirwaaldo1** [comment]
Hello @MildTomato it is currently working. If I see any other bugs, I will try to make another issue.

**Comment by aairey** [comment]
I seem to be facing this issue on Ubuntu 22.04 after updating `google-chrome-stable` from `126.0.6478.61-1` to `126.0.6478.126-1`.
