### ISSUE TITLE
OneSignal Example leads to Ambiguous TS Error in Edge Functions Webhook Execution

### ISSUE THREAD

**Issue by bmalumphy** [supabase/supabase#13358]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Math and Coffee would like to integrate our Supabase instance with OneSignal for a Mobile project we're rapidly approaching MVP for. When integrating with OneSignal we seem to be hitting a crash on the Edge Functions side where the stack trace reveals an unknown file on our CLI side (which leads us to believe it is a server side bug).

`Failed to create OneSignal notification TypeError: (0 , Fa.default) is not a function`

The above error is happing with no real stack trace on the index.ts code. I'm just using the tutorial code from the OneSignal integration guide here:

`https://supabase.com/docs/guides/integrations/onesignal`

with just the message changed to use my table's properties instead of the tutorials.

Full trace:
```
Failed to create OneSignal notification TypeError: (0 , Fa.default) is not a function
    at e.send (file:///src/main.ts:396:87)
    at file:///src/main.ts:8163:48
    at file:///src/main.ts:378:20
    at async Server.<anonymous> (file:///src/main.ts:8774:33)
    at async Server.#respond (file:///src/main.ts:190:24)```

```
My `.env` appears to be in good shape and my code does as well. Here's my code for the CLI function though:
```ts
import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import * as OneSignal from 'https://esm.sh/@onesignal/node-onesignal@1.0.0-beta9'

const _OnesignalAppId_ = Deno.env.get('ONESIGNAL_APP_ID')!
const _OnesignalUserAuthKey_ = Deno.env.get('USER_AUTH_KEY')!
const _OnesignalRestApiKey_ = Deno.env.get('ONESIGNAL_REST_API_KEY')!
const configuration = OneSignal.createConfiguration({
  userKey: _OnesignalUserAuthKey_,
  appKey: _OnesignalRestApiKey_,
})

const onesignal = new OneSignal.DefaultApi(configuration)

serve(async (req) => {
  try {
    const { record } = await req.json()

    // Build OneSignal notification object
    const notification = new OneSignal.Notification()
    notification.app_id = _OnesignalAppId_
    notification.contents = {
      en: `${record.post_text}`,
    }
    notification.headings = {
      en: "Gig'em Ags"
    }

    const onesignalApiRes = await onesignal.createNotification(notification)

    return new Response(JSON.stringify({ onesignalResponse: onesignalApiRes }), {
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('Failed to create OneSignal notification', err)
    return new Response('Server error.', {
      headers: { 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I would imagine following the steps in the above guide would reproduce, but just in case here's what we're doing
1. Create a Client side app along with a OneSignal application and integrate them together
2. Create a function through Supabase CLI that will web hook over to OneSignal. To do this follow the steps in the above outline
3. Insert a row into your table, either through your client app, or through the SQL editor (We're doing it through the SQL editor for now).
4. The Edge Function's logbook will show the error above.

## Expected behavior

A push notification should be triggered on One Signal's side and pushed to the mobile or web client appropriately.

## System information

- OS: [macOS]
- Version of supabase-cli [1.46.4]
- Version of OneSignal Node package [1.0.0-beta9] (The tutorial uses 7 but this also fails)

## Additional context

Please note that our integration with OneSignal on the client appears complete and functional. We are able to see in our OneSignal logs that the API is not getting hit. Which means something in:

```
const onesignalApiRes = await onesignal.createNotification(notification)
```

Appears to be failing. This is OneSignal's code, however, there doesn't appear to be a reference to any `Fa` function in their code besides the language code for their `StringMap.ts` file.

It may very well be that this is a OneSignal issue, however, we thought it odd that the reference to the crash was in a `main.ts` file that doesn't appear in their repository anywhere for OneSignal's node package.

**Comment by iAmWillShepherd** [comment]
@bmalumphy, regarding the issue you're experiencing, I'm curious if you've tried setting the intended recipients on your notification object. You can do this by setting the `included_segments` or `include_external_user_ids` properties. If you can try that out and report back if that helps, that'd be great

**Comment by bmalumphy** [comment]
@iAmWillShepherd including the following line doesn't seem to effect the error:
```typescript
notification.include_external_user_ids = [record.creator_id]
```

**Comment by iAmWillShepherd** [comment]
@bmalumphy, this is indeed strange. I'll try to see if I can reproduce this on my end and get some input from the engineering team who owns the Node.js SDK. 

FYI, I'm from OneSignal and happy to help out here 😁

**Comment by bmalumphy** [comment]
@iAmWillShepherd this is an odd one yeah. Thanks for putting in the time.

If you need access to my project I did allow permission in the support ticket I filed so feel free to poke around. No sensitivity there as of yet.

**Comment by dorage** [comment]
Hello, try to check your dotenv. it might be undefined.

check this document: https://supabase.com/docs/guides/functions/secrets

**Comment by bmalumphy** [comment]
> 

My env is set correctly and they are logging as the correct keys on server. This is not the issue.

**Comment by bmalumphy** [comment]
@dorage @iAmWillShepherd It turns out that in Reno if you don't have the query parameter at the end of the import for a node sdk of `?target=deno&no-check` that the import essentially fails. That solved the issue. The no-check property might not be necessary, but I haven't tried it and now I'm on a roll so here we go.

**Comment by iAmWillShepherd** [comment]
> @dorage @iAmWillShepherd It turns out that in Deno if you don't have the query parameter at the end of the import for a node sdk of `?target=deno&no-check` that the import essentially fails. That solved the issue. The no-check property might not be necessary, but I haven't tried it and now I'm on a roll so here we go.

Wow! I wouldn't have guessed that. I definitely thought this was on our end because when I tested with our last beta it worked; however when switching to your version it didn't. I'm now wondering if I dropped that bit from my import.
