### ISSUE TITLE
Protecting multiple routes using SvelteKit is not working as expected

### ISSUE THREAD

**Issue by Chemchu** [supabase/supabase#13378]
## Hello! 

I'm starting a new project using SvelteKit and Supabase. Pretty standard stuff to be honest. 
I am currently adding authentication and authorization to my application. I've followed the Supabase documentation and got stuck in the "protecting multiple routes" part because the app didn't run as expected. 

## The problem
If you follow the Supabase documentation and then try to check the protected route, the browser won't redirect you as stated in the example.  
The docs I am talking about: 
https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#protecting-multiple-routes

## Solution?
I've spent all the afternoon trying to find the problem... and I think I found it!!
By default, SvelteKit prerender every single page you create. That means SvelteKit is creating the HTML at build time. I am not an expert on the subject but I think prerendering protected routes might be the problem. To solve this issue, I just had to set prerendering to false. I created a "+layout.server.ts" file inside the route folder I wanted to protect and added the next line:

```typescript
// src/routes/dashboard/+layout.server.ts
export const prerender = false;
```
After that, the app behaved like I wanted from the start. If I try to go to "/dashboard" I get redirected to the landing page. That's fantastic. 

## Improvement

To be honest, I don't know why changing the prerender value to false solves my issue, but I think it is important to acknowledge this weird behavior. I am sure the Supabase team is able to figure it out. 
By now, I think the best thing to do is to update the docs and inform the developer about this problem. 

I hope this helps!

**Comment by KevinBrolly** [comment]
Hey there,

Thank you so much for your feedback and suggestion. Since the auth-helpers is being deprecated in favour of the @supabase/srr package I believe this issue may now be stale. I am going to close the issue but if it is still relevant let us know and we can re-open.
