### ISSUE TITLE
Use a fixed time for RSS files

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#13381]
# Chore

## Describe the chore

<img width="1393" alt="Screenshot 2023-04-03 at 10 23 09 AM" src="https://user-images.githubusercontent.com/8291514/229397308-b7ce49b6-17f4-4aa8-b12d-a9c95aeb7e5c.png">

Update the RSS generators so that a consistent timezone is used. 
This will stop so many .xml file changes creeping through on PRs.

A clear and concise description of what the chore is.

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by MildTomato** [comment]
Main file to change is here
https://github.com/supabase/supabase/blob/master/apps/www/internals/generate-sitemap.mjs

**Comment by MildTomato** [comment]
GMT-0 would be great

**Comment by subhajit20** [comment]
hey @MildTomato do I have to add
```
dayjs(posts[0].date).utc().tz("Asia/Taipei").local().format('ddd, DD MMM YYYY HH:hh:mm ZZ')
```

**Comment by MildTomato** [comment]
>hey @MildTomato do I have to add

>dayjs(posts[0].date).utc().tz("Asia/Taipei").local().format('ddd, DD MMM YYYY HH:hh:mm ZZ')

Think it would make more sense to use GMT0 / UTC0 - Supabase doesn't recognize "Asia/Taipei" as it's central timezone. It doesn't have a main timezone.

**Comment by MildTomato** [comment]
@subhajit20 not sure 😄 it'll be explained in the [dayjs docs](https://day.js.org/docs/en/installation/installation)

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source, this is my first time can you assign me this task.

**Comment by RipulHandoo** [comment]
@MildTomato This issue has been resolved.
Please close this issue.
Thank you.
