### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by lqmanh** [supabase/supabase#134]
- **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project

- **Summary**
Currently how should I handle database migrations with Supabase? Or is there any plan to support it yet?

**Comment by awalias** [comment]
hey @lqmanh . We plan to build git integrations which will handle migrations and two-way syncing between git and postgres

in the meantime if you go to the settings page on the dashboard you will find your postgres db details which you can use to run any existing postgres migration tools
