### ISSUE TITLE
NextJs 13 appDir issue: Can't resolve 'encoding' module

### ISSUE THREAD

**Issue by JustKira** [supabase/supabase#13403]
# Bug report

- [Cant Decide] I confirm this is a bug with Supabase, not with my own application. 
- [YES ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Module not found: Can't resolve 'encoding' in 'E:\NEW\VS_PROJECTS\ieee-cis-nu\node_modules\node-fetch\lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
./node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
./node_modules/@supabase/supabase-js/dist/main/index.js
./utils/supabase.ts
./app/api/news/route.ts

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

[repo](https://github.com/JustKira/ieee-cis-nu)

## Expected behavior

what i expect it to get data back from supabase.

## System information

- OS: [Windows]
- Browser (if applies) [chrome]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. v16.17.1]

## Additional context

note is im using next 13 with app dir.

**Comment by JustKira** [comment]
there was issue with that error in supabase github but its closed i tried what he did but didnt work [issue link](https://github.com/supabase/supabase/issues/13280)

**Comment by JustKira** [comment]
ok i found fix just run it should work just fine
```console
npm i -d encoding
```

**Comment by Cannibalhulk** [comment]
@JustKira thanks👍🏼, it solved my problem too.

**Comment by aleczratiu** [comment]
It didn't resolve the issue just installing the encoding, any other solutions?
