### ISSUE TITLE
Translate our readme

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#1341]
Are you capable of translating our readme?

Add a translation to the `i18n` folder! https://github.com/supabase/supabase/tree/master/i18n

**Comment by enesinan** [comment]
Can I improve for the translate to turkish this readme file

**Comment by J0** [comment]
I can do the chinese translation but will probably need to find a native speaker to review.

**Comment by gomflo** [comment]
did a pr for spanish translation

**Comment by mkiisoft** [comment]
I can do Spanish and no issues with Spanish from Spain and from general LATAM.

**Comment by leonardomerlin** [comment]
PR ready with PT-BR translation :v: https://github.com/supabase/supabase/pull/1365

**Comment by M4Tdev** [comment]
PR for Polish is ready.

**Comment by carlosstenzel** [comment]
I would like to know if the translation will be done in the documentation and on the website?

**Comment by kiwicopple** [comment]
Yes eventually. We are using the Readme as a good starting-point to figure out our processes and the level of work involved

**Comment by saileshbro** [comment]
Hi, @kiwicopple  I have added PR for Nepali language #1381

**Comment by joneidejohnsen** [comment]
Added PR for Norwegian bokmål (nb-no) #1382

**Comment by zunkelty** [comment]
I improved the translations for German. PR is ready.

**Comment by YazeedAlKhalaf** [comment]
I just added the Arabic translation for the `README.md`! 🚀

**Comment by didier** [comment]
Just updated the Dutch🇳🇱  translations.

**Comment by gvasilakiss** [comment]
PR for Greek translation is ready!🚀

**Comment by fabianmossberg** [comment]
PR for Swedish translation is ready! 🇸🇪 #1642

**Comment by PhoenixCreation** [comment]
Can I take responsibility for Hindi(India). I can also go for Gujarati(India) if you want afterwards. Please let me know if I can.

**Comment by MasterBrian99** [comment]
PR for sinhala translation #2240

**Comment by phucvo0708** [comment]
Vietnamese translation is ready to be launched ;) #2632
