### ISSUE TITLE
Improve collapsible animation

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#13414]
# Chore

## Describe the chore

/packages/ui/src/components/collapsible

A clear and concise description of what the chore is.

Make sure the contents animates in and out seamlessly. Currently the content just fades in.

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by pratik-codes** [comment]
@MildTomato just a little help with where can I find using collapsible from the UI
I can see it used in certain forms but not sure where they appear

**Comment by MildTomato** [comment]
One of the examples is here 
https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Auth/AuthProvidersForm/ProviderForm.tsx/#L76

**Comment by NiazMorshed2007** [comment]
Hey there, can you assign this issue to me if anyone isn't working on this? @MildTomato

**Comment by MildTomato** [comment]
hi @NiazMorshed2007 - we don't really assign issues in this repo as issues tend to get picked up all the time.
If you submit a pull request I can review though 🚀

**Comment by NiazMorshed2007** [comment]
@MildTomato got it. But I'm having some issues with setting up the project. After running `npm install` it throws a bunch of errors. Any solution to solve it?
![image](https://user-images.githubusercontent.com/77217706/230505430-f9fa4a26-59a2-42a5-a7d2-37254c3ca7e7.png)

**Comment by MildTomato** [comment]
@NiazMorshed2007 what command did you run after `npm install` ?

**Comment by NiazMorshed2007** [comment]
@MildTomato I didn't run any other commands. It throws these error while I run `npm install` . Here is a sequence of screenshots of errors 👇. Do you know any solutions?

![image](https://user-images.githubusercontent.com/77217706/230538259-dc2a9f27-1364-4081-a90d-c950662f6f64.png)
![image](https://user-images.githubusercontent.com/77217706/230538291-2a42541b-c210-42f1-aab3-6d8f33e5a781.png)
![image](https://user-images.githubusercontent.com/77217706/230538326-66781cc8-0656-404f-8895-cb31ff11c434.png)
![image](https://user-images.githubusercontent.com/77217706/230538412-28277d1d-6c28-4057-aa57-a423185fe659.png)

**Comment by MildTomato** [comment]
@pratik-codes not sure what is wrong here. maybe someone else will recognize these errors.

**Comment by MildTomato** [comment]
Also, also maybe check npm version is >= 8.x.x

Might be worth checking around the `Error: Could not find any Python installation to use` error message, might be isolated to your npm version and/or operating system.

**Comment by pratik-codes** [comment]
@NiazMorshed2007 could be your local environment doesn't have correct/any python installed. Nodejs require python as dependency if I am not wrong - [see here](https://www.google.com/search?q=does+node+require+python&oq=does+node+req&aqs=chrome.0.0i512l2j69i57j0i22i30l4j0i390i650l3.3440j0j1&sourceid=chrome&ie=UTF-8)

**Comment by NiazMorshed2007** [comment]
I installed python and checked my `npm` and `node` version. Everything looks fine but still doesn't work :(

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue?

**Comment by Sudhanva-Nadiger** [comment]
@NiazMorshed2007 try `npm install -f` or `npm install --legacy-peer-deps` and check

**Comment by NiazMorshed2007** [comment]
@Sudhanva-Nadiger still doesn't work

**Comment by pratik-codes** [comment]
@MildTomato This is the component you want to be worked on correct?
[Screencast from 12-04-23 11:07:25 PM IST.webm](https://user-images.githubusercontent.com/64960569/231539025-2bdf1c40-82eb-4ec6-9c22-054c97a81762.webm)

**Comment by patelmilanun** [comment]
@NiazMorshed2007 the thing is that with windows 1 particular library needs to be build. I had faced same issue while installing it 2nd time. What I mean by this is that I had the required setup for building these packages using node-gyp. Then I did something with node js installation using nvm and I got messed up and my project was no longer working.

So, I tried to do setup 2nd time with node-gyp and spent like 2-3 days with no luck. 

So, I decided to not go with this thing in windows as windows for development is trash everything else is good. So, I found this thing called WSL. U can search and setup it up. U will get ubuntu/Linux terminal with native Linux support inside windows machine without need of dual boot or virtual machine. Just right now I finished setting the project up using WSL and it runs without any error or anything like buttery smooth.

**Comment by MildTomato** [comment]
I'm going to close this issue, as It probably makes sense that animation is done by using something like https://github.com/supabase/supabase/blob/master/packages/ui/ui.config.js/#L242-L243 in the collapsible and I forgot we are meant to add these tailwind classes like [this](https://github.com/supabase/supabase/blob/master/apps/docs/components/reference/RefDetailCollapse.tsx/#L36).
