### ISSUE TITLE
[ui] active tabs not showing correctly

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#13464]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Tabs component not showing active text highlighted
probably need important on tailwind ie. `!class-name` 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots
<img width="324" alt="Screenshot 2023-04-06 at 12 11 26 AM" src="https://user-images.githubusercontent.com/8291514/230140602-876f1659-aebd-497a-ab5e-73444744026d.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
@MildTomato - A bit random but on local development the tabs focus appears to show?

<img width="280" alt="Screenshot 2023-04-05 at 17 34 19" src="https://user-images.githubusercontent.com/22655069/230145922-24a0ea48-f66b-4dc7-9519-5c18efc10486.png">

**Comment by MildTomato** [comment]
@Hallidayo probably different version of tailwind running locallt
