### ISSUE TITLE
Webhooks doesn't work with supabase/studio:20230330-99fed3d image

### ISSUE THREAD

**Issue by squallsama** [supabase/supabase#13480]
# Bug report

## Describe the bug

Can't even show Webhook menu

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Juse use docker-compose from repo with a new supabase-image version

## Expected behavior
http://localhost:3000/project/default/database/hooks - should works fine, but instead if just shows error with a new supabase studio image

## Screenshots

![image](https://user-images.githubusercontent.com/4921200/230265672-a7c6a6e1-ae37-4e65-a8ed-62124231a568.png)

## System information

- OS: macOS, Windows
- Browser - chrome

## Additional context

Works fine with supabase/studio:20230216-e731b77

**Comment by reteps** [comment]
Is this because supabase is running in a docker container, and docker containers by default don't have access to localhost?

**Comment by squallsama** [comment]
Nope. As I mentioned - everything fine using supabase/studio:20230216-e731b77 docker image. New one is broken.

**Comment by squallsama** [comment]
> Is this because supabase is running in a docker container, and docker containers by default don't have access to localhost?

Nope. As I mentioned - everything fine using supabase/studio:20230216-e731b77 docker image. New one is broken.

**Comment by nicetomytyuk** [comment]
Having the same issue, the solution is hosted by using a VPS, the studio image used is: supabase/studio:20230330-99fed3d

![image](https://user-images.githubusercontent.com/30237552/231105559-85fce19b-4042-4113-bd4c-2939c954839d.png)

**Comment by Donokami** [comment]
> Having the same issue, the solution is hosted by using a VPS, the studio image used is: supabase/studio:20230330-99fed3d
> 
> ![image](https://user-images.githubusercontent.com/30237552/231105559-85fce19b-4042-4113-bd4c-2939c954839d.png)

Same issue here.

**Comment by silentworks** [comment]
Thanks for bringing this issue to light, we are aware of this and are working to fix this. However this week is launch week for us and we are working on getting other features out. But this is on our radar for sure, I'll keep you updated on this issue as we get closer to fixing the issue.

**Comment by numisman** [comment]
following this

**Comment by arshamg** [comment]
Are all webhooks broken or just the Studio UI for them? We're trying to debug an issue and running into this.

**Comment by Donokami** [comment]
> Are webhooks completely broken or just the Studio UI for them? We're trying to debug an issue and running into this.

It looks more like its due to the Studio UI, the calls aren't made to the meta API correctly. If you have any update on this, I'd be happy to ear it!

**Comment by tholder** [comment]
also wondering about this, it's my first time using the local setup and assumed it was me not doing something.
