### ISSUE TITLE
Getting 500 issue on storage page

### ISSUE THREAD

**Issue by ali-faiz-brainx** [supabase/supabase#13489]
## Describe the bug

Getting 500 internal server error when open storage section of the supabase site. It won't allow me to create new bucket.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. SignIn with your supabase account
2. Go to the storage section from sidebar.
3. See the internal server error on top-right

**Comment by Hallidayo** [comment]
Hi @ali-faiz-brainx - Just tried on my account and the storage section seems fine. It may be worth contacting support:

https://app.supabase.com/support/new

**Comment by saltcod** [comment]
Closing as outdated.
