### ISSUE TITLE
[docs] og image title name rendering wrong

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#13487]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

og images for docs sometimes showing wrong product title
for example. https://supabase.com/docs/guides/realtime/channels
<img width="583" alt="Screenshot 2023-04-06 at 5 01 59 PM" src="https://user-images.githubusercontent.com/8291514/230328745-a9fbc89b-d761-4b74-b666-0e7eede1c409.png">

possibly a mix of sending wrong params to og image function, and also maybe function needs updating

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Isaiah-Hamilton** [comment]
Production just needed a redeploy.
