### ISSUE TITLE
correction in readme.md

### ISSUE THREAD

**Issue by atharvtek** [supabase/supabase#13493]
# Improve documentation
correction required in readme.md

## Link 
https://github.com/supabase/supabase/tree/master/examples/auth/nextjs

## Describe the problem
it is mentioned that "This endpoint can be edited in pages/api/hello.ts."
but this example code is for next.js 13.2, where "pages/api" is moved to "app/api"

## Describe the improvement
edit the text "pages/api" to "app/api"

**Comment by patelmilanun** [comment]
can i get assigned to this ?

**Comment by MildTomato** [comment]
looks like it was closed in #13499
