### ISSUE TITLE
slack clone example documentation improvement

### ISSUE THREAD

**Issue by sw-yx** [supabase/supabase#135]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

hi! in here: https://github.com/supabase/supabase/tree/master/examples/slack-clone#how-to-use

it is not at all clear which is the NEXT_PUBLIC_SUPABASE_URL and which is the NEXT_PUBLIC_SUPABASE_KEY. worse still, the example image shows something in the URL which is NOT a URL

recommend clarifying a little.

**Comment by awalias** [comment]
thanks for the heads up @sw-yx 

added some clarification 274b413293942719e00007e96b4bf57c8fc27204
