### ISSUE TITLE
It will lose the login status once deleted the auth user

### ISSUE THREAD

**Issue by gaminglifex** [supabase/supabase#13504]
# Bug report

- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I was attempting to delete a user from the auth.users table, and although the deletion process was successful, it unexpectedly resulted in the loss of my current login session. I am unsure as to what could have caused this.

## Expected behavior

It is expected to complete the delete without losing my current login status.

## Screenshots
I am using the following code:
![image](https://user-images.githubusercontent.com/72642816/230526035-2b3e2af3-a4e2-4fad-aea3-5f46cc12a76c.png)

the result as shown in the image below:
![image](https://user-images.githubusercontent.com/72642816/230526108-540a5d22-432c-413c-809e-49a0eefcea12.png)

## System information

- OS: Windows
- Browser (if applies) : Chrome
- Version of supabase-js: @nuxt/supabase 0.3.5
- Version of Node.js: v18.15.0

## Additional context

I will provide a reproduction if it is needed. Thank you :)

**Comment by gaminglifex** [comment]
More info:

It will lose the user's login status immediately:
![image](https://user-images.githubusercontent.com/72642816/230529143-7cc4cb1e-da97-427f-86e0-29a7dd96496f.png)

![image](https://user-images.githubusercontent.com/72642816/230528991-31c01fd2-3de6-406d-8cc8-fabdc0372438.png)

**Comment by GaryAustin1** [comment]
Can you explain more about what is wrong with the process?
If you delete a user and then try and get the user why would you not expect a 404?

The admin call is supposed to be done with service_role and there should be no user context in the session of that client.

**Comment by gaminglifex** [comment]
I apologize for any inconvenience I may have caused. I will explain what I want to achieve and the problem I am encountering below:

I am trying to create a feature on the "User management" page that allows the deletion of a user from the "auth.users" database.

I have created an "API" for deleting a user with "service_role" under the server directory.

I logged in as "User A" and attempted to delete "User B".

However, when "User B" is deleted, the login status of "User A" is lost immediately.

Could you please advise on what I am doing wrong?

**Comment by GaryAustin1** [comment]
You should have a separate client with service role do the user delete.  You can set persistSession:false and/or use a different storage key when you createClient for the service role client.

**Comment by gaminglifex** [comment]
I am sorry to tell you that I am still unable to make it work using your suggestions. The problem will also occur when I manually delete a user from the auth.users table on Supabase. :(

**Comment by gaminglifex** [comment]
Thank you for your inspiration. I mixed up the usage of signUp() & auth.admin.createUser().
Thanks a lot
