### ISSUE TITLE
Create Access Token on selfhosted returns html as an error

### ISSUE THREAD

**Issue by gregpalaci** [supabase/supabase#13508]
# Bug report

When I naviagate to /account/tokens and create a token on a self hosted instance this is what I get

At the very least the error shouldnt render out in html.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/1177690/230560181-42dd9981-3aec-4f7d-930f-4247d2374438.png">

`Failed to create token: <!DOCTYPE html><html><head><meta charSet="utf-8"/><title>Supabase</title><meta name="viewport" content="initial-scale=1.0, width=device-width"/><meta name="next-head-count" content="3"/><link rel="stylesheet" type="text/css" data-name="vs/editor/editor.main" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.css"/><link rel="stylesheet" type="text/css" href="/css/fonts.css"/><link rel="preload" href="/_next/static/css/688e5457ffb526ad.css" as="style"/><link rel="stylesheet" href="/_next/static/css/688e5457ffb526ad.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-7edcfa0dd61f6659.js" defer=""></script><script src="/_next/static/chunks/framework-88c3fab5a4d30eea.js" defer=""></script><script src="/_next/static/chunks/main-4518d572b1ff7494.js" defer=""></script><script src="/_next/static/chunks/pages/_app-9045f33443b356a2.js" defer=""></script><script src="/_next/static/chunks/pages/404-b1d202b28d30f581.js" defer=""></script><script src="/_next/static/XaWrXABFsIkGzSQRXw4Kj/_buildManifest.js" defer=""></script><script src="/_next/static/XaWrXABFsIkGzSQRXw4Kj/_ssgManifest.js" defer=""></script><script src="/_next/static/XaWrXABFsIkGzSQRXw4Kj/_middlewareManifest.js" defer=""></script></head><body class="dark"><div id="__next" data-reactroot=""><div class="min-h-full flex flex-col"><div class="relative mx-auto flex h-screen w-full flex-col items-center justify-center"><div class="absolute top-0 mx-auto w-full max-w-7xl px-8 pt-6 sm:px-6 lg:px-8"><nav class="relative flex items-center justify-between sm:h-10"><div class="flex flex-shrink-0 flex-grow items-center lg:flex-grow-0"><div class="flex w-full items-center justify-between md:w-auto"><a href="/projects"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%27120%27%20height=%2724%27/%3e"/></span><img alt="supabase" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%"/><noscript><img alt="supabase" srcSet="/img/supabase-dark.svg 1x, /img/supabase-dark.svg 2x" src="/img/supabase-dark.svg" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" loading="lazy"/></noscript></span></a></div></div></nav></div><div class="absolute select-none opacity-[5%] filter transition duration-200 blur-none"><h1 style="font-size:28rem">404</h1></div><div class="flex flex-col items-center justify-center space-y-6 transition opacity-0"><div class="flex w-[380px] flex-col items-center justify-center space-y-3 text-center"><h3 class="text-xl">Looking for something? 🔍</h3><p class="text-scale-1100">We couldn&#x27;t find the page that you&#x27;re looking for!</p></div><div class="flex items-center space-x-4"><a href="/projects"><button class=" relative cursor-pointer inline-flex items-center space-x-2 text-center font-regular transition ease-out duration-200 rounded outline-none transition-all outline-0 focus-visible:outline-4 focus-visible:outline-offset-1 bg-brand-fixed-1100 hover:bg-brand-fixed-1000 text-white bordershadow-brand-fixed-1000 hover:bordershadow-brand-fixed-900 dark:bordershadow-brand-fixed-1000 dark:hover:bordershadow-brand-fixed-1000 focus-visible:outline-brand-600 shadow-sm text-sm leading-4 px-3 py-2" type="button"><span class="truncate">Head back</span></button></a></div></div></div></div><div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/404","query":{},"buildId":"XaWrXABFsIkGzSQRXw4Kj","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>

`

**Comment by poorna-prakash-sr** [comment]
I am working on this can anybody assign this to me

**Comment by gregpalaci** [comment]
@poorna-prakash-sr would you be working on just the error fix or implementing the token functionality on self hosted out of curosity?

**Comment by RGdevz** [comment]
how to create access token on selfhosted supabase? i inited with the supabase cli start command

**Comment by nikoma** [comment]
Did anyone solve this?

**Comment by saltcod** [comment]
Hi there — sorry for missing this one. 
The tokens page shouldn't be shown in the self-hosted environment as its meant for creating tokens to access the hosted infrastructure. 

Did you have specific use case for needing tokens in self-hosted? We might be able to suggest an alternative.

**Comment by akyllus** [comment]
The issue you're facing is due to the tokens page being accessible in self-hosted environments. This page is meant for creating tokens to access the hosted infrastructure.

To restrict access to the tokens page in self-hosted environments, you can modify the pages/api/auth/[...supabase].js file. You can add a middleware function to check if the environment is self-hosted and if so, return a 404 status.

Here's an example of how you can modify the file:


import { supabase } from '../lib/supabaseClient';
import { NextApiRequest, NextApiResponse } from 'next';

const handler = async (req, res) => {
  const { user } = req;

  if (!user) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  if (process.env.NEXT_PUBLIC_SELF_HOSTED) {
    return res.status(404).json({ error: 'Not Found' });
  }

  const { email } = user;
  const { data: userRole, error: userRoleError } = await supabase
    .from('users')
    .select('role')
    .eq('email', email)
    .single();

  if (userRoleError) {
    return res.status(500).json({ error: 'Error fetching user role' });
  }

  // ... rest of the code
};

export default handler;




In this example, we added a condition to check if the NEXT_PUBLIC_SELF_HOSTED environment variable is set. If it is, we return a 404 status, indicating that the page is not found.

You can set the NEXT_PUBLIC_SELF_HOSTED environment variable in your .env.local file:

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
