### ISSUE TITLE
Carrier Page is broken

### ISSUE THREAD

**Issue by learnuidev** [supabase/supabase#13543]
# Bug report

## Describe the bug

Career  page is broken 

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Go to https://supabase.com/careers page, you can see that the page is broken (screenshot below)

<img width="1512" alt="Screenshot 2023-04-09 at 4 17 41 AM" src="https://user-images.githubusercontent.com/67298065/230752294-ac7c4718-f02a-4204-b721-1d0510c0e609.png">

## Expected behaviour: 

You should see this ui:

<img width="1512" alt="Screenshot 2023-04-09 at 4 19 15 AM" src="https://user-images.githubusercontent.com/67298065/230752334-f54ddf67-363a-490b-8c80-1b736c01b100.png">

## Problem:

https://github.com/supabase/supabase/blob/master/apps/www/components/Globe.tsx#L15

<img width="1506" alt="Screenshot 2023-04-09 at 4 21 17 AM" src="https://user-images.githubusercontent.com/67298065/230752400-cea572b4-4e92-426d-be62-5078fb28684d.png">

## Quick fix

Disabling line 9 -55 seem to do the trick

<img width="703" alt="Screenshot 2023-04-09 at 4 25 53 AM" src="https://user-images.githubusercontent.com/67298065/230752539-9616b18c-c6b6-4594-90f6-9698b8c5189a.png">

<img width="1512" alt="Screenshot 2023-04-09 at 4 26 59 AM" src="https://user-images.githubusercontent.com/67298065/230752558-60df6095-4515-4958-80ed-0e3dc827f80b.png">

**Comment by nith2001** [comment]
Looks like it's working, unless it got fixed in the past hour.
