### ISSUE TITLE
As a user I cannot see the full list of tables in the edit relation modal

### ISSUE THREAD

**Issue by zigavidmar** [supabase/supabase#13555]
# Bug report
- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When trying to apply **foreign key relation** to a column inside any table I sometimes don't get the full list of all tables that I created inside a project. I have 26 tables but only 1 is being rendered in the "Select a table to reference to" list box.

## To Reproduce
1. Open Table editor inside your Supabase project.
2. Open a table
3. Edit column
4. Add Foreign key relation
5. Open **Select a table to reference to** list box.

## Expected behavior
The list box should always provide all my created public tables.

## Screenshots
![image](https://user-images.githubusercontent.com/40399282/230790711-a3c71755-9c7d-4498-a040-5ab6a3fcc069.png)

## System information

- OS: Windows
- Browser: Chrome

## Additional context
Issue is located in 
https://github.com/supabase/supabase/blob/3a9ac9048a708e1b4f09089c71a38031b5942089/studio/components/interfaces/TableGridEditor/SidePanelEditor/ForeignKeySelector/ForeignKeySelector.tsx file(211 row).

This is 50/50. Sometimes I get the whole list, but sometimes not. I can reproduce it however everytime if i refresh the page.

**Comment by saltcod** [comment]
Hey @zigavidmar thanks for the report! 

This is a known issue, a fix should go out for this tomorrow. 

https://github.com/supabase/supabase/pull/13515
