### ISSUE TITLE
Request died after use single in flutter

### ISSUE THREAD

**Issue by Dicoders** [supabase/supabase#13567]
# Bug report

If once use method `single()` all other request waiting response one row.

## Work correct:

`List<dynamic> data1 = await supabase.from('recipes').select();`

`List<dynamic> data2 = await supabase.from('ingredients').select();`

## Worked not correct:

But if used 'single()' in request, then all next request die

`Map<String, dynamic> data1 =
      await supabase.from('recipes').select().eq('id', 1).single();`

`List<dynamic> data2 = await supabase.from('ingredients').select();` <--- die
 
ERROR:
`Unhandled Exception: PostgrestException(message: JSON object requested, multiple (or no) rows returned, code: PGRST116, details: Results contain 4 rows, application/vnd.pgrst.object+json requires 1 row, hint: null)`

And it doesn't depend on the time between requests

**Comment by GaryAustin1** [comment]
I don't use Flutter, but you probably need to handle the errors.  Your .single() request is getting an error because you are returning more than 1 row.  This results in an error.

From the flutter starter guide:
```
  try {
      final userId = supabase.auth.currentUser!.id;
      final data = await supabase
          .from('profiles')
          .select()
          .eq('id', userId)
          .single() as Map;
      _usernameController.text = (data['username'] ?? '') as String;
      _websiteController.text = (data['website'] ?? '') as String;
      _avatarUrl = (data['avatar_url'] ?? '') as String;
    } on PostgrestException catch (error) {
      context.showErrorSnackBar(message: error.message);
    } catch (error) {
      context.showErrorSnackBar(message: 'Unexpected exception occurred');
    }
```

**Comment by Dicoders** [comment]
> I've helped someone with similar issue today and it seems to happen when the user hasn't been signed in fully as yet and requests are being made. Temporarily turn off RLS on all your tables used in these requests and test to see if the error persists.

I disabled RLS in start development for all tables. All request above execute with disabled RLS.
I tried execute with RLS enabled + user auth, but the result was the same unsuccessful.

I see only one way - not use `single()` 😞

**Comment by dshukertjr** [comment]
@Dicoders 
This was a bug on an earlier version of supabase_flutter. If you could update your supabase_flutter version to the most recent one and retry it, it would be great.
