### ISSUE TITLE
public_url of uploaded image in storage is not right when self hosted

### ISSUE THREAD

**Issue by dfang** [supabase/supabase#13569]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

on self hosted supabase, when click a uploaded picture, you can't get the right url of the image

<img width="1413" alt="Screen Shot 2023-04-10 at 17 18 07" src="https://user-images.githubusercontent.com/1277047/230872990-11a13493-9e9e-4557-9439-5993c20506b7.png">
<img width="1429" alt="Screen Shot 2023-04-10 at 17 18 27" src="https://user-images.githubusercontent.com/1277047/230873056-cb042fed-488e-4f23-af94-e15ea077b9e1.png">
<img width="1421" alt="Screen Shot 2023-04-10 at 17 18 46" src="https://user-images.githubusercontent.com/1277047/230873104-d4c53315-9bb7-4077-b53a-c34c38f43682.png">

my .env:
<img width="603" alt="Screen Shot 2023-04-10 at 17 20 58" src="https://user-images.githubusercontent.com/1277047/230873474-abdaa331-9cdd-4c10-a993-14c3b80c9501.png">

original docker-compose.yml
<img width="745" alt="Screen Shot 2023-04-10 at 17 21 49" src="https://user-images.githubusercontent.com/1277047/230873631-8172de29-9abc-4b26-ac83-432bd01207ce.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

the return url should read SUPABASE_PUBLIC_URL not SUPABASE_URL

## System information

- OS: centos 7
- Browser: Safari on macOS 11.6.6

**Comment by caolixiang** [comment]
supabase/studio:20230512-ad596d8 already solved this problem. Try to update your docker-compose.yml

**Comment by saltcod** [comment]
Duplicate. Closing in favour of 
https://github.com/supabase/supabase/issues/14232
