### ISSUE TITLE
Missing default grants defined in your database after running Prisma migrate dev

### ISSUE THREAD

**Issue by samuel-antwi** [supabase/supabase#13579]
## Describe the bug
If you run prisma migrate dev and it detects schema drift, it asks you if you want to reset the database. If you choose yes, it will reset the database and from there, **it is no longer possible to create new users either from supabase dashboard or via your application.** The auth schema is pretty much got messed up from here.

**I found this in the documentation:**
According to the documentation, when this happens, all you need to do is create a draft migration like this: prisma migrate dev --create-only and  add the following helper SQL:

```sql
grant usage on schema public to postgres, anon, authenticated, service_role;

grant all privileges on all tables in schema public to postgres, anon, authenticated, service_role;
grant all privileges on all functions in schema public to postgres, anon, authenticated, service_role;
grant all privileges on all sequences in schema public to postgres, anon, authenticated, service_role;

alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;
alter default privileges in schema public grant all on functions to postgres, anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to postgres, anon, authenticated, service_role;

```

**ERROR** when you try to invite a new user.
![user-error](https://user-images.githubusercontent.com/29069653/230944752-31581053-c98d-4986-b919-83390aa60271.png)

I can confirm this doesn't fix the missing default grant issues.

**Comment by josh803316** [comment]
I'm running into the same issue after cloning the supabase community t3-turbo [repo](https://github.com/supabase-community/create-t3-turbo). I tried following the same steps listed above (that are also in the supabase prisma integration [guide](https://supabase.com/docs/guides/integrations/prisma) ) to no avail. I still have the same issue that @samuel-antwi reported.

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
