### ISSUE TITLE
Filtering by a bigint id column in studio doesn't work for large ints

### ISSUE THREAD

**Issue by andyk** [supabase/supabase#13612]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm using int8 as my primary key and when I have large values of it, the filter feature in studio fails to work.

https://user-images.githubusercontent.com/228998/231234620-4b636e3c-7dfb-496f-a77a-7d0c98c0ca74.mp4

## To Reproduce

I've done this with a clean new table (which is what I show in the screen capture).

Create a table with a bigint column 'id' as primary key as follows:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/228998/231235235-eb60e198-c68d-44e4-a737-ee8d4576253d.png">

Then add a row with id 1702292043303580221. then filter for that value using the built in filter UI. the row won't show.

This bug might also show up for non primary key columns. I didn't try that.

I did some searching of existing issues/docs/discussions. It might be related to https://github.com/supabase/supabase/issues/7150

I'm also seeing the supabase javascript client (which i believe uses `postgrest` under the hood) return a rounded value of the same key so it might be an issue with javascript rounding/truncating/overflowing with postgres's 64bit bigint. I'm trying to work-around this 2nd issue with https://stackoverflow.com/questions/74549311/how-to-use-bigint-safely-with-supabase-js -- i.e. by casting the column to `id::text` in my `.select(...)` function call.

## Expected behavior

The row exists and should be shown when the filter is applied.

## Screenshots

see above

## System information

- OS: macOS
- Browser (if applies) firefox 111.0.1 (64-bit); Chrome Version 111.0.5563.146 (Official Build) (arm64)

**Comment by saltcod** [comment]
fixed with https://github.com/supabase/supabase/pull/14385
