### ISSUE TITLE
Webhook stopped firing. Instead, indefinitely queuing in http_request_queue

### ISSUE THREAD

**Issue by bryceAebi** [supabase/supabase#13613]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have two webhooks. One that triggers upon an insert and one that triggers upon an update. When I insert or update a record on the relevant table, the webhooks are not firing. I am testing by passing the webhooks an ngrok url. When I hit this ngrok url with `curl`, it runs as expected so this appears to be an issue with Supabase.

When I look in the `net` table, I am noticing that each webhook request that _should_ have fired, is just sitting in the `http_request_queue` table. I do see a single record in the `_http_response` table.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up a webhook
2. Trigger the webhook
3.  Check the http_request_queue table

## Expected behavior

Webhook should hit provided url

## System information

We spun up this Supabase instance within the past 2 weeks.
Both HTTP and PG_NET extensions are enabled.

## Additional Context
We also spun up a Supabase instance before the current one, and as far as I know it had more or less the same configuration. The webhooks _were_ working with this instance.

**Comment by marcusarnfast** [comment]
My webhooks where also not triggering/firing, but after a server restart it started working again but now i get the following error_msg in "http_repsonse"

"Failed sending data to peer"
"Timeout was reached"

When i then try to do a curl post request in the terminal the api seems to work fine, but the webhook in supabase does not seem to work... 

Don't know if it's related 🤷‍♂️

**Comment by silentworks** [comment]
This is likely related to the fix this PR has https://github.com/supabase/supabase/pull/13556. This should be available on the next dashboard deployment.

**Comment by gaborhadhazy** [comment]
I'm having the exact same issue

**Comment by GaryAustin1** [comment]
Going to close out as seems resolved.
