### ISSUE TITLE
ERROR: function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by gonta1026** [supabase/supabase#13650]
# Bug report

I get an error in my local docker environment.

```bash
$ supabase db diff --use-migra hoge -f hoge

Connecting to local database...
Creating shadow database...
Applying migration 20230325212123_add_table_stores.sql...
Error: ERROR: function uuid_generate_v4() does not exist (SQLSTATE 42883)
At statement 0: create table "public"."stores" (                                
    "id" uuid not null default uuid_generate_v4(),              
    "name" character varying not null,                          
    "image" character varying,                                  
    "description" text,                                         
    "created_at" timestamp with time zone not null default now()
)                                                               
Try rerunning the command with --debug to troubleshoot the error.
make: *** [migrate] Error 1

```
`20230325212123_add_table_stores.sql` is the very first migration file.

## To Reproduce

1. supabase start 
2. Adding columns to tables in the dashboard
3. supabase db diff --use-migra hoge -f hoge
4. function uuid_generate_v4() does not exist (SQLSTATE 42883)

## Expected behavior

no error

## Screenshots

My understanding is that the creation of uuid is enabled by the following.

<img width="582" alt="スクリーンショット 2023-04-12 22 16 50" src="https://user-images.githubusercontent.com/45672476/231494666-11956edb-0ece-45cc-b547-e8350a50261e.png">

## System information
- OS: Apple M2
- Version of supabase-js: [e.g. 2.2.3]
- Version of Node.js: [e.g. v18.12.0]

## Additional context
I recently changed pc's and the first pc I created the project on did not have the error. However, I am using the same project on the same System information, so I don't know why I am getting the error.

**Comment by GaryAustin1** [comment]
https://github.com/orgs/supabase/discussions/9251
Maybe this searchpath setup issue?

**Comment by gonta1026** [comment]
@GaryAustin1 

Thanks, I checked the issue. I am in the following state of understanding.
- My local seed file does not describe anything.
- The signup and login are also working fine.
- The extension appears to be set up automatically for pgcrypto as well.

<img width="426" alt="スクリーンショット 2023-04-13 7 53 57" src="https://user-images.githubusercontent.com/45672476/231603790-bfd4656e-f60f-4f6c-adbe-0f0390f9c987.png">

**Comment by GaryAustin1** [comment]
If you use extensions.uuid_generate_v4() does it work?

**Comment by gonta1026** [comment]
> If you use extensions.uuid_generate_v4() does it work?

Yes, the following uses uuid with uuid_generate_v4() to generate the id automatically. So uuid_generate_v4() seems to work. But for some reason, uuid_generate_v4() is giving me an error during migration.

<img width="745" alt="スクリーンショット 2023-04-13 10 31 22" src="https://user-images.githubusercontent.com/45672476/231622652-eab96a72-98b5-45f0-95b5-29d2bcb6cdf4.png">

<img width="584" alt="スクリーンショット 2023-04-13 10 29 04" src="https://user-images.githubusercontent.com/45672476/231623159-c9081fba-03f0-4c9b-b833-8a82a54f0d31.png">

**Comment by GaryAustin1** [comment]
Yes but the issue I linked is that migration did not have the search path set to include extensions schema.  So either the search path has to be set, or you have to put extensions.uuid_generate_v4() in the schema.

The UI role likely has search path set to include extensions.

**Comment by gonta1026** [comment]
Okay, I see what you mean a little bit about the problem.

> So either the search path has to be set, or you have to put extensions.uuid_generate_v4() to include the schema.

What exactly should we do about this one? I couldn't understand the specific action to be taken even after looking at this [disscussion](https://github.com/orgs/supabase/discussions/9251) you gave me....

**Comment by GaryAustin1** [comment]
Yeah, sorry I have not used migrations.  Just makes sense you need to either have the search path set or just use extensions.xxxx when you need it in migrations.
Did not close the issue as maybe it needs looking at, but seems you can work around it.

**Comment by gonta1026** [comment]
I have solved the problem by doing this investigation.

On my old pc I had installed supabase from homebrew to use supabase cli and the version of supabase was `1.27.10`.
Now on my new pc, the version of supabase is `1.47.3`. I thought it might be a version problem, so I changed the version of supabase to `1.50.4`, which is the latest version at the moment, and the migration succeeded in the docker environment without any problem. So I recognized that it was a bug hidden in the version.

**Comment by gonta1026** [comment]
The issue has been resolved and we will close it.

**Comment by ilyabo** [comment]
If you experience this issue it might actually have to do with this setting in `supabase/config.toml`: 
```
extra_search_path = ["public","extensions"]
```

**Comment by teamclouday** [comment]
I ran into the same issue and was able to resolve it by replacing `uuid_generate_v4()` with `extensions.uuid_generate_v4()` in the migration file.

**Comment by zhzhang** [comment]
I'm getting this error on `db push`, and have checked that my local config.toml as well as the supabsae project itself have `extensions` in the extra search path. I have `extensions` prepended to every use of `uuid_generate_v4` in my declarative schema, and am a little annoyed that the DB diff command strips them off, and I have to manually add them back in.

**Comment by juanleondev** [comment]
Same here, I'm using the latest CLI version 2.65.5, and I'm getting this error when running `supabase db push`

```
ERROR: function uuid_generate_v4() does not exist (SQLSTATE 42883)
At statement: 1                                                   
create table "public"."users" (                                   
    "id" uuid default uuid_generate_v4() not null, 
```
