### ISSUE TITLE
Unexpected value of non-null column when edit

### ISSUE THREAD

**Issue by hieuwu** [supabase/supabase#13658]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Given that I have a table, I want to add a mandatory column (not nullable). When I add the column with default value is `""`. I created successfully. However, when I edit the column, the default value display unexpected text which is `'""'::text`. See 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Precondition: Create a table
1. Go to the table, add a column
2. Make that column not nullable
3. Make its type is `text` and default value is `""`
4. Save and close, Then edit table
5. See error

## Expected behavior
When I edit the table's default value, it should display exactly the value that I input

## Screenshots

https://user-images.githubusercontent.com/43868345/231519841-70f05576-c13e-4e1d-8635-ce3ecebece80.mov

## System information

- OS: macOS
- Browser (if applies) Edge
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Dashboard

**Comment by GaryAustin1** [comment]
If you want empty text then you use single quotes `''`.   Double quotes `""` are not string delimiters in postgres.  So the editor is setting your general purpose string `""` to be the default string by enclosing it in single quotes.  You would get the same result if you had entered `abc` it would have turning it to `'abc'::text`.

You really should ask for help on discord or in discussions before reporting errors.

**Comment by GaryAustin1** [comment]
Closing unless you feel I missed what you were trying to do.

**Comment by hieuwu** [comment]
> Closing unless you feel I missed what you were trying to do.

Thanks Gary. My bad for not reading much enough 😄
