### ISSUE TITLE
Closing toast in function edit errors is triggering the form closure 

### ISSUE THREAD

**Issue by akashsharma99** [supabase/supabase#13713]
# Bug report

- ✅ I confirm this is a bug with Supabase, not with my own application. 
- ✅ I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After submitting a function from UI , if there is any error in the function a toast appears with the error message. Problem is that if i click on the X icon to close the toast I am getting a dialog asking me if i am sure I want to close the panel? My changes will be lost.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.com/project/{PROJECT_ID}/database/functions)`
2. Click on the Edit fucntion option from the 3 dots menu for any of your existing.
3. make some modifications in the function definition that can result in a error like an sql error.
4. Click on Confirm button
5. You will get a toast on the top right of your screen with the SQL error.
6. Click on the little X icon on the toast to close the toast
7. This results in showing the dialog box for closing the entire form.

## Expected behavior

after step 6 just the toast should be removed and it should not show a dialog as if user wants to close the form.

## Screenshots

X icon on the toast
![image](https://user-images.githubusercontent.com/22654711/231962656-0d7853d7-01fc-4f55-ab65-0c1e69c8de25.png)

Dialog that its showing
![image](https://user-images.githubusercontent.com/22654711/231962744-6402a6e4-53fb-4b03-afed-7526873e997c.png)

## System information

- OS: Windows
- Browser chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by gregnr** [comment]
Thanks for reporting @akashsharma99. This should be fixed as of https://github.com/supabase/supabase/pull/13947. Let me know if not and we'll reopen!
