### ISSUE TITLE
Image upload returns 500 with resumable uploads enabled

### ISSUE THREAD

**Issue by drewbietron** [supabase/supabase#13739]
Our account was enabled for resumable uploads and we're now getting a 500 error when trying to upload images to Storage.

Error from logs
```json
"rawError": "{\"_error\":{\"name\":\"KnexTimeoutError\"},\"name\":\"KnexTimeoutError\",\"message\":\"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\",\"stack\":\"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\\n    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)\\n    at runNextTicks (node:internal/process/task_queues:60:5)\\n    at listOnTimeout (node:internal/timers:538:9)\\n    at process.processTimers (node:internal/timers:512:7)\\n    at async Transaction_PG.acquireConnection (/app/node_modules/knex/lib/execution/transaction.js:250:28)\"}",
```

This happened after asking to be enabled in the resumable uploads beta but it appears as if theres a breaking change for existing uploads?

We're on Supabase 2.10.0 but have tried updating the JS client but still with no luck.

**Comment by dong-qian** [comment]
@drewbietron I have the similar issue and found the temp solution by save the config on the bucket again without any changes fix the bucket.
![solution](https://user-images.githubusercontent.com/24208956/232338353-fd3273a7-da31-41aa-b0c3-e95868690aed.gif)

**Comment by drewbietron** [comment]
> @drewbietron I encountered a similar issue and discovered a temporary solution by re-saving the bucket configuration without making any changes, which resolved the problem.
> 
> 
> 
> ![solution](https://user-images.githubusercontent.com/24208956/232338353-fd3273a7-da31-41aa-b0c3-e95868690aed.gif)
> 
> 

I wasn't able to see the buckets in Studio, it would just return an error. 

I had the have the resumable uploads feature flag turned off on the account that was effected and it's back to normal. Still haven't determined what the issue was but will report back here once it's figured out.

**Comment by GaryAustin1** [comment]
Closing this as no other comments after success.
