### ISSUE TITLE
Typo in supabase/apps/docs/pages/guides/auth/auth-helpers/auth-ui.mdx

### ISSUE THREAD

**Issue by AndyUGA** [supabase/supabase#13747]
# Improve documentation

## Link 
[Link to Supabase React Auth UI documentation](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui#predefined-themes)

## Describe the problem
On the React Auth UI documentation page, the sentence `We recommend using one of the predefined themes to style the UI. Import the theme you want to use and pass it to the appearence.theme prop.` and `Import the theme you want to use and pass it to the appearence.theme prop.` have the word `appearence` but it should be spelled `appearance`

## Describe the improvement
This will improve the documentation to use the correct spelling of `appearance`.

**Comment by Thisisaarush** [comment]
@AndyUGA Didn't see your PR LMAO 🤪
