### ISSUE TITLE
Typo in supabase/apps/docs/pages/guides/auth/managing-user-data.mdx

### ISSUE THREAD

**Issue by AndyUGA** [supabase/supabase#13758]
# Improve documentation

## Link 
[Link to Supabase Managing User Data Documentation](https://supabase.com/docs/guides/auth/managing-user-data)

## Describe the problem
In the sentence, `Should you wish to immediately revoke access for a user, do considering making use of a Row Level Security policy as described below.`, it should say `do consider` instead of `do considering`.

## Describe the improvement

Update the wording from `do considering` to `do consider`

**Comment by SunnyKr77** [comment]
Hello, I would like to fix this issue. Can you assign it to me?
Thanks
