### ISSUE TITLE
[Potential deleterious bug] SQL Editor: If "Run" is pressed before green check mark appears, it runs the code that used to be in the SQL Editor, not the code that is visible.

### ISSUE THREAD

**Issue by sachio222** [supabase/supabase#13757]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using SQL Editor, there is a small green check mark next to the Run button. 
Normally, it spins after content is edited.
Once check mark is green, it is safe to press the run button. 
If Run is pressed before green check mark appears, it runs the code that used to be in the SQL Editor, not the code that is visible.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to SQL Editor, click on existing query
2. Paste in valid code edits
3. Click Run button before green check mark appears
4. Get status returned for whatever was in the SQL editor before edits were made.

## Expected behavior

1. Go to SQL Editor, click on existing query. 
2. Paste in valid code edits
3. Run button is disabled until green check mark appears. 
4. Click Run when it becomes active
5. Get status returned for code that is currently visible in SQL editor.

## Screenshots

<img width="238" alt="Screenshot 2023-04-16 at 08 25 44" src="https://user-images.githubusercontent.com/9384977/232309824-9a7f13c9-80cd-4d81-bfb1-c891c20740ba.png">
<img width="260" alt="Screenshot 2023-04-16 at 08 25 28" src="https://user-images.githubusercontent.com/9384977/232309826-adf4022e-7d46-4a85-9072-341ceee73985.png">

## System information

- OS: MacOS
- Browser (if applies) Firefox
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Being able to paste code and run is becoming commonplace with GPT suggestions. I accidentally set an entire column to null because I pasted in code over an old query and pressed run. I lost a ton of data because I plasted and clicked run too quickly.

**Comment by GaryAustin1** [comment]
Try hard refreshing your browser.
Should be fixed.    
https://github.com/supabase/supabase/issues/13717

**Comment by sachio222** [comment]
Tested with an example table "checkouts" with a column "checked_in", with the following 4 queries in different permutations and combinations, trying to be as quick as possible. Each query created the expected response after pasting and smashing the cmd+enter key. Everything seems to be in order!

-- #1
ALTER TABLE checkouts
ADD COLUMN test VARCHAR(255);

-- #2
UPDATE checkouts SET checked_in = TRUE;

-- #3
UPDATE checkouts SET checked_in = NULL;

-- #4
ALTER TABLE checkouts
DROP COLUMN test;
