### ISSUE TITLE
some text is not visible in cli docs

### ISSUE THREAD

**Issue by delgado3d** [supabase/supabase#13795]
# Improve documentation

## Link 

https://supabase.com/docs/reference/cli/supabase-completion-zsh

## Describe the problem

text not visible

## Additional context

![image](https://user-images.githubusercontent.com/27228526/232676572-d6c682ca-bd30-42b2-8d07-7ad7226671d2.png)
![image](https://user-images.githubusercontent.com/27228526/232676687-51b7a92c-42b0-4a42-873e-d22b89522a3a.png)

**Comment by gregnr** [comment]
Thanks for reporting this @delgado3d! Looks like this affects desktop breakpoints (1024px+).

**Comment by MildTomato** [comment]
these are not correctly marked up right?

should be using markdown 3 backticks ?
