### ISSUE TITLE
Ability to create users without triggering emails (i.e admin/internal users)

### ISSUE THREAD

**Issue by garylake** [supabase/supabase#13809]
I have a use case where I have public end users who are signing in with signInWithOtp and this is fine. However my app is a B2B/B2C hybrid (I have a mobile app for B2C end users and web app for my B2B customers) so I have users who are admins of my B2B customers, not B2C end users. 

For this later group, you can't just sign up and you need to be invited and I have to add the supabase account to an org+users table. I really need the ability to just create new users programmatically (invite user to manage an org) and ultimately not send them the default email or anything. I can then let them know their account is ready or I can send my own emails via postmark, but at the moment they're getting the end user's signIn email which makes no sense in this context. 

If the supabase-js library had either a flag in the options to suppress sending email when signing-up/in, or simply a new auth.createUser() function that just silently set up a new account without the comms or creating the session yet, this would be perfect.

**Comment by GaryAustin1** [comment]
From a server you can do this with auth.admin.createUser...
The email_confirm flag controls whether you send confirmation email or not.
![image](https://user-images.githubusercontent.com/54564956/233092325-57a3bcd1-54b7-4727-abc9-8a9371fc6732.png)

**Comment by garylake** [comment]
Hi Gary,

Perhaps I haven't been clear, these admin users aren't supabase admins, but admins of my app, so they still need to be regular supabase end users, and I have complimentary tables that gives those users extra access to a different app. 

In your example, I'm assuming the supabase.auth.admin.createUser is creating a supabase admin user, which I don't want...

**Comment by GaryAustin1** [comment]
It is not creating an admin user, but it does require it be run securely on serverside with the service role key.  So you would have to use an edge function or other server side approach to use that.

**Comment by garylake** [comment]
"Also it is not clear how allowing a non server side only API method to create a user could be secured. Anyone could call the API method without using your app specifically and create users as they desire."

Ah yep, that's a fair point. It would be nothing more than a nuisance as I have other tables to populate to make these accounts actually work, but yes, it makes sense. 

But thanks for this, it's given me something to think about. Presumably I could do the auth.admin approach you suggest safely in an edge function with the service role key?

I'm not too worried about protecting that from abuse as I'm already calling an rpc to make my complimentary tables and that does some checks to make sure that the auth.uid() calling it actually has the right permissions to even do this, based on other tables I have. 

I could lock the edge function down by requiring some kind of secret from Supabase vault that only the rpc and edge function would know about...

**Comment by GaryAustin1** [comment]
Edge function is the way to go as you can also use https://supabase.com/docs/reference/javascript/auth-admin-generatelink to get confirmation links and send your own custom email based on client type if you desired they actually confirm.

**Comment by garylake** [comment]
Thanks, as always, Gary!
