### ISSUE TITLE
[Github actions] UI tests action is unreliable when changes in PR are not /studio based

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#13844]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Studio Tests GitHub action keeps getting stuck if there are no changes in /studio directory.
The test is stuck in "waiting for status to be reported".

Action in question : https://github.com/supabase/supabase/blob/master/.github/workflows/studio-tests.yml
Possibly something wrong with the rules regarding when to run the github action.

Ideally we want this action to be 'required' on all PRs.

<img width="937" alt="Screenshot 2023-04-20 at 3 14 09 PM" src="https://user-images.githubusercontent.com/8291514/233289010-878a0e03-9e79-423e-aa58-0f564a909847.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Bayyana-kiran** [comment]
hey @MildTomato Can work on this issue?

**Comment by MildTomato** [comment]
@Bayyana-kiran we don't directly assign issues in this repo. 
You can submit a PR though and we'll review it 🚀

**Comment by KevinBrolly** [comment]
Hey @Bayyana-kiran were you able to make progress on this issue?

**Comment by Bayyana-kiran** [comment]
Sorry I'm not working on this

**Comment by Ziinc** [comment]
This doesn't look like it is happening anymore
