### ISSUE TITLE
Blog tags should update url

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#13857]
Clicking the nav items here just does filtering. Clicking these should filter the posts and update the url.

https://supabase.com/blog

![CleanShot 2023-04-20 at 13 09 16@2x](https://user-images.githubusercontent.com/105593/233417267-89786958-f683-4748-a2b0-4d79e46f7451.png)

Tag url example: 
https://supabase.com/blog/tags/auth

**Notes**
useUrlState hook might be helpful.
https://github.com/supabase/supabase/blob/master/studio/hooks/ui/useUrlState.ts

If used, we should probably move this hook into packages/common/hooks https://github.com/supabase/supabase/tree/master/packages/common/hooks

**Comment by saltcod** [comment]
Hey @sambhavgupta0705 this issue might be a good one!

**Comment by sambhavgupta0705** [comment]
Thanks @saltcod . I will be working on this one soon :)

**Comment by shashankdaima** [comment]
Is this issue active?

**Comment by sambhavgupta0705** [comment]
Hey I am working on it ,I was a little busy with my exams

**Comment by kisankumavat85** [comment]
PR added - #14086 
Please review it
