### ISSUE TITLE
auth.function will not show in Supabase Studio

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#13854]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I thought i had this bug (feature?) created already but I did search all the places so here we go:

Quite simple: In Supabase Studio sometimes you need to create Functions in the auth schema. However they will not show up in `/database/functions` . This ofc could be intentional because of the search paths but then again: If you can create something in the UI it is expected to show in the UI as well.

Currently I am using dbeaver to list them which is not as convenient.

## Reproduction:
Create a function in the AUTH schema -> will not show in the function overview

**Comment by alaister** [comment]
Hey @activenode,

Thanks for the report here. As I mentioned in #13866, the `auth` schema should be modified with care, as any modifications to it potentially make upgrades difficult.

Is there a reason that you want to add the functions to the `auth` schema specifically? I'd recommend creating a new schema for these functions and storing them in there. Then you'll be able to interact with them via the `/database/functions` page.

**Comment by activenode** [comment]
Hi @alaister. Very much open for suggestions.  So the problem is rooted in this scenario:

We have a function that is called `auth.handle_new_user()` which is triggered when a new user in `auth.user` is added. Now that function however reads from `auth.user` table. That isn't possible if I add it in the `public` schema because then it cannot find / access `auth.user` even if spelled out `auth.user` (not just `user` because then it would anyway assume we mean `public.user`). 

That's essentially the problem. Any good suggestion that doesn't feel like a workaround?

**Comment by alaister** [comment]
@activenode thank you for the details!

You should be able to access the `auth.users` table anywhere in your SQL functions (provided they have the correct privileges) when you reference it with the `auth` schema in front. For functions like `handle_new_user()`, I have a schema called `app` where I store everything that isn't "public".

Let me know if that works for you. Also, feel free to share a simplified version of your `handle_new_user()` function if you like.

**Comment by activenode** [comment]
Thanks. Will check and come back.

**Comment by alaister** [comment]
Hey @activenode,

How'd you go? Am I okay to close this?

**Comment by activenode** [comment]
Okay, coming back to this now. Sorry, had to do a bit of research for it why we did it.

For most of the things you wanna do across auth you cannot have people access `auth.*` data when the function has `SECURITY INVOKER` instead of `SECURITY DEFINER` (as it doesnt belong to them, especially when it's an "unknown" new user).

So we have a `auth.handle_new_user` function that, for obvious reasons, shall not be publicly accessible -> not part of `public` schema. Otherwise you could call it with `supabase.rpc('handle_new_user')` and it has `SECURITY DEFINER` for it to have all rights.


However you are right that it might be solved with adding another schema e.g. `private` .

I think it would solve my current underlying issue. Thanks for the hint. Any good reads to recommend on creating a new protected schema?

**Comment by alaister** [comment]
You might find the [Supabase dbdev repo](https://github.com/supabase/dbdev/blob/master/supabase/migrations/20220117141359_app_schema.sql) a helpful reference, as most tables are stored in a schema called `app`. Here's the SQL that is used to create the `app` schema:

```sql
create schema app;

grant usage on schema app to authenticated, anon;

alter default privileges in schema app grant select on tables to authenticated, anon;
```
