### ISSUE TITLE
Update the year in the footer

### ISSUE THREAD

**Issue by CharlesKasasira** [supabase/supabase#13859]
# Improve documentation

[https://supabase.com/docs](https://supabase.com/docs) - not so relevant, it's on the footer of the documentation

## Describe the problem

The year on the documentation was hard-coded, and it still says 2022, I would like to make a PR to generate it dynamically and the performance cost is negligible.

## Additional context

Screenshot of current footer year
![image](https://user-images.githubusercontent.com/59878203/233425885-9a76ede9-960c-4dde-a4d6-f03f019e7f21.png)

**Comment by faithoyebode** [comment]
@CharlesKasasira Please assign this to me. I would love to work on this.

**Comment by MildTomato** [comment]
This doesn't need to be here.
It can just say "Supabase" and link to the marketing page?

Ok to change @CharlesKasasira ?

**Comment by CharlesKasasira** [comment]
Yes, I would love to work on that.
@MildTomato  is the homepage the marketing page "[https://supabase.com/](https://supabase.com/)"?
