### ISSUE TITLE
Clarify that deleting a Storage bucket will delete all items in bucket 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#13873]
We should be extra explicit in this modal:

"Your bucket named test and all its contents will be deleted."

<img width="1133" alt="CleanShot 2023-04-20 at 21 24 17@2x" src="https://user-images.githubusercontent.com/105593/233510060-ed14cf29-e6bf-448f-b752-655664f9aaa1.png">

**Comment by sambhavgupta0705** [comment]
Hey can I work on it ✋

**Comment by saltcod** [comment]
Sure @sambhavgupta0705 ! Go for it! Any questions let us know!

**Comment by sambhavgupta0705** [comment]
Hey @saltcod I got a notification from you

**Comment by saltcod** [comment]
Sorry @sambhavgupta0705  — I saw you ask and replied to go for it, but then after saw that it was already done. Sorry about that!

**Comment by sambhavgupta0705** [comment]
Ok @saltcod ,I thought we get assigned the issue first then work on it.
Can you please suggest some good first issues to work upon

**Comment by saltcod** [comment]
Hey @sambhavgupta0705 — tagged you in this one https://github.com/supabase/supabase/issues/13857
could be a good one to start on
