### ISSUE TITLE
Live subscriptions are not working

### ISSUE THREAD

**Issue by nuurdev** [supabase/supabase#1389]
# Bug report

## Describe the bug

Live subscriptions don't seem to be working in the slack-clone example.

## To Reproduce

1. Clone the slack-clone repository: [Repo](https://github.com/supabase/supabase/tree/master/examples/nextjs-slack-clone)
2. Follow the instructions in the link above to get everything running
3. Run the app locally
4. Create an account and try sending a message on one of the channels

## Expected behaviour

The new message should appear after it's sent

## Current behaviour

You have to refresh the page to see the new message

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 1.1.2
- Version of Node.js: v14.15.1

## Additional context

Live subscriptions seem to be working on the [live demo](http://supabase-slack-clone-supabase.vercel.app/) that is shared on the slack clone README

**Comment by kiwicopple** [comment]
Hi @nuurdev - it's possibly because you haven't turned on Replication for this table:

https://supabase.io/docs/guides/api#managing-realtime

I'll close this now, but if it is something else, fee free to comment here and I'll reopen

**Comment by johnsonchandra** [comment]
The realtime subscription does not work, although everything is setup correctly, and Realtime subscription is checked too in table messages.
You can try at [my deployment](https://supabase-slack-clone-ashen.vercel.app)
or even at your [live demo](http://supabase-slack-clone-supabase.vercel.app/)

**Comment by johnsonchandra** [comment]
It seems like the DELETE subscription works, but INSERT subscription not working for no obvious reason
