### ISSUE TITLE
API autodocs adjustments

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#13904]
Goal of this one is to make API autodocs more discoverable and usable. 

**Table Editor adjustments:** 
In the top right of the table editor, in the side panel after you click on the `<>API`  button

![CleanShot 2023-04-19 at 14 04 26@2x](https://user-images.githubusercontent.com/105593/233789168-5d456cf0-9299-4bdc-9a81-d8405b4ee93d.png)
1. Remove all of the top section (the stuff that's X'd out)
2. Keep API Url but move it down to the api keys section  
 
**Database/tables adjustments**
![CleanShot 2023-04-19 at 13 38 17@2x](https://user-images.githubusercontent.com/105593/233789318-43931ecb-e4a5-455b-bf38-f62c1e932b27.png)
1. Add a new button here (`<>API`) so we can toggle the side panel open here, like we can on the Table Editor page
2. That table is already a little cramped. We should probably change the text in a few places — "estimated" could become "est" and "Realtime enabled" could become just "Realtime"  
3. Note that this table is responsively showing / hiding content. We'd want the API button to always show when possible. At the smallest breakpoint, the API button should show instead of the "6 columns" button, as the API panel will have this info as well.

**Comment by CatherineKiiru** [comment]
Hi @saltcod, I'd like to work on this issue. Is it still available?

**Comment by saltcod** [comment]
Hey @CatherineKiiru yup looks like! Thanks! Any questions, please let us know.

**Comment by CatherineKiiru** [comment]
Thanks @saltcod, I will work on this issue.

**Comment by CatherineKiiru** [comment]
Hi @saltcod, a clarification: would I need to clone the whole project to work on this issue, or can I just work with a specific file?

**Comment by saltcod** [comment]
@CatherineKiiru yeah you'd want to clone the entire repo. The developer getting started instructions are here
https://github.com/supabase/supabase/blob/master/DEVELOPERS.md
