### ISSUE TITLE
Improve v1.2 project upgrade and blog post release documentation

### ISSUE THREAD

**Issue by richardhyesungo** [supabase/supabase#13905]
# Improve documentation

## Link 

https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects
https://supabase.com/blog/whats-new-in-pg-graphql-v1-2#like-ilike-and-startswith

## Describe the problem

The documentation doesn't inform users who are on the pro tier for their projects that upgrading to v1.2.0 needs to be done through support. There is only a note (under where it states pausing and restoring the project for upgrades) that states:

> NOTE
> This is only available for projects on the Free plan.

I was only made aware of this after already having sent a support ticket and discussing on the discord.

I first found that the features for the like, ilike, and startswith operators were made available for graphql via the blog post. But the blog post itself doesn't hint that upgrading are necessary to access these features.

## Describe the improvement

For this page - https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects
add a note stating: "For users with projects on the pro tier, please contact support for assistance with upgrading."

For this blog post - https://supabase.com/blog/whats-new-in-pg-graphql-v1-2
Add a note stating: "Note: These features are only available to projects after upgrading your project to v1.2.0. For help with upgrading, please review the documentation here: 'https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects'"

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by gregnr** [comment]
Hey @richardhyesungo! You're right - this needs to be clearer. Thanks for taking the time to make this suggestion.
