### ISSUE TITLE
iOS apps cannot use Supabase with 3rd party Authentication providers

### ISSUE THREAD

**Issue by Seanmclem** [supabase/supabase#1391]
# Bug report

I consider this a bug. Apple has required you to use Apple Authentication within your app, if you use any other 3rd part authentication. 

Since Supabase does not support Apple Authentication -then iOS apps which use Supabase cannot be distributed if they use any 3rd part Auth Providers. Which is a very large use-case and instantly makes the platform unusable for many

This has been an Apple requirement for over a year. 

See firebase workaround. [HERE](https://stackoverflow.com/questions/59940378/sign-in-by-apple-and-firebase-x-plugin-ionic-4). Basically you can use a Library to auth with Apple and get a generic Oauth token, and pass that to a generic function that accepts those and good to go.

**Comment by inian** [comment]
Closing as duplicate https://github.com/supabase/gotrue/issues/37

**Comment by Seanmclem** [comment]
> Closing as duplicate [supabase/gotrue#37](https://github.com/supabase/gotrue/issues/37)

Is it a duplicate -if this is a bug and that is a feature-request? 3rd party auth is effectively broken on iOS.
