### ISSUE TITLE
Clicking copy button return undefined in project settings

### ISSUE THREAD

**Issue by yeganathan18** [supabase/supabase#13913]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I was trying to copy the `Refference ID` by clicking the copy button, but it returns `undefined` after coping, looks like the button is broken

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [app.supabase.com](https://app.supabase.com/)
2. Open any project and visit Project Settings
4. Click copy button
5. Try pasting, you will see `undefined` 

## Expected behavior

The button should copy the `Reference ID` as intended

## Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63534555/233833511-d403d50d-169b-467f-8d2c-d1ae1ba2e7b4.png">

## System information

- OS: macOS
- Browser (if applies) Chrome v.1.50.121
- Version of supabase-js: ^2.7.1
- Version of Node.js: v16.19.0

## Additional context

None

**Comment by AshishBarvaliya** [comment]
@yeganathan18 Not able to reproduce

![CPT2304251513-1389x653](https://user-images.githubusercontent.com/49753983/234379671-a68c2171-3b9c-47c7-b801-98118be9ae67.gif)

**Comment by yeganathan18** [comment]
@AshishBarvaliya Thanks for hopping in! I too couldn't reproduce the bug now, and it might have probably fixed

Closing this issue since it no longer exist.
