### ISSUE TITLE
Creating multiple constraints on a column generates x amount of columns in the edit table view and types

### ISSUE THREAD

**Issue by mypalvikram** [supabase/supabase#13970]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating multiple constraints on a column, the dashboard edit table view will show that column twice (or more) depending on the number of constraints applied to it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create a column
Add two or more constraints to that column separately
Go to the tables view and hit edit table, you will see multiple columns with that name

Removing a constraint will remove one of the extra columns 

## Expected behavior

There should always be one column with a unique name and never multiple based on the amount of constraints

## Screenshots

<img width="645" alt="Screenshot 2023-04-25 at 1 33 36 PM" src="https://user-images.githubusercontent.com/6226652/234402421-2b51e6a3-9ee1-4153-a541-642866c5b0fd.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by gregnr** [comment]
Thanks for reporting this @mypalvikram. We'll take a look and let you know what we find out. cc @supabase/frontend

**Comment by mypalvikram** [comment]
I am no longer experiencing this. Looks like it may have been fixed in a recent update.

**Comment by mypalvikram** [comment]
> no. it's not fixed.
> 
> 
> 
> ![image](https://github.com/supabase/supabase/assets/133625693/981749d2-a86c-43c1-a6a9-50e59baa890d)
> 
> 

Thanks for sharing.

**Comment by colemilne54** [comment]
I am also experiencing this issue so far it seems to cause more than an issue visual bugs in the dashboard as running:
`npx supabase gen types etc.`
for Typescript will create issues as the duplicates carry over into this generated code.

It should also be mentioned that the duplicated item is set as `unique`.

**Comment by soedirgo** [comment]
Thanks all! This should be fixed with this PR: https://github.com/supabase/postgres-meta/pull/602

**Comment by soedirgo** [comment]
The fix has been deployed. Thanks for the wait!
