### ISSUE TITLE
Suggest gen_random_uuid() as the default 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#13999]
When creating a new table and selecting a uuid as the primary key, we should suggest `gen_random_uuid()` as the default function.

1.  Currently we suggest `uuid_generate_v4()` which requires an external extension and is thus less portable to other non-Supabase environments.
2. `gen_random_uuid()` is a native Postgres function, we should use that instead.

**Comment by saltcod** [comment]
Hah yes you're right. Thanks @GaryAustin1

**Comment by fire** [comment]
I also encountered this and believe this should be default for the uuid field.
