### ISSUE TITLE
docs: link to optimizations 404s

### ISSUE THREAD

**Issue by bensalilijames** [supabase/supabase#13998]
# Improve documentation

## Link 

URL: https://supabase.com/docs/guides/platform/performance#allowing-higher-number-of-connections
GitHub: https://github.com/supabase/supabase/blob/b656e3c54bdae6176c0db8692cc0efe3987c4ae8/apps/docs/pages/guides/platform/performance.mdx?plain=1#L210

## Describe the problem

The link ("[the default configuration used by the Supabase platform](https://github.com/supabase/supabase-admin-api/blob/master/optimizations/postgres.go)") 404s (perhaps the repo has been deleted/moved)?

## Describe the improvement

Fix where the link points to, or remove the link entirely. I did search through a number of repos in the supabase org in order to make a PR, but couldn't find anything promising!

Related: https://github.com/supabase/supabase/issues/11375

**Comment by gregnr** [comment]
Thanks for reporting this @bensalilijames.

That would be great @dhavall13 🙌 Let's remove the link.

**Comment by dhavall13** [comment]
> Thanks for reporting this @bensalilijames.
> 
> That would be great @dhavall13 🙌 Let's remove the link.

> Could you review this #14005

**Comment by gregnr** [comment]
Closed in #14005
