### ISSUE TITLE
Indexes documentation does not exist

### ISSUE THREAD

**Issue by TipTopSailor** [supabase/supabase#14001]
# Improve documentation

Getting 404 error for following page

## Link 

https://supabase.com/docs/guides/resources/postgres/indexes

## Describe the problem

Documentation is missing

**Comment by gregnr** [comment]
@TipTopSailor thanks for reporting. These pages were moved and links didn't get updated. Will be fixed in https://github.com/supabase/supabase/pull/13972.

**Comment by gregnr** [comment]
In the mean time, here is where it went:
https://supabase.com/docs/guides/database/postgres/indexes

**Comment by saltcod** [comment]
Updated:
https://supabase.com/docs/guides/database/postgres/cascade-deletes
