### ISSUE TITLE
When granting a role to another user, permissions don't seem to work

### ISSUE THREAD

**Issue by thisisgoldman** [supabase/supabase#14004]
### Discussed in https://github.com/orgs/supabase/discussions/13896

<div type='discussions-op-text'>

<sup>Originally posted by **thisisgoldman** April 21, 2023</sup>
Hi there,

We're hitting an error granting permissions in our Supabase database. Here is the scenario:

We create a new user in our Supabase database: `user_a` 

With that user, we create a new schema (i.e., `schema_a`) and a table (i.e., `table_a`) in the database. `user_a` is the owner of both the schema and table with permission to select, insert, and delete.

Initially, the new tables cannot be accessed by the Supabase client (i.e., the `anon` / `service_role` database users). So we grant `user_a`'s permissions to `anon`, etc:

```sql
grant user_a to anon;
```

We'd expect this grant to allow the `anon` user to also have usage on the new schema and tables - just as it works in Postgres. But this doesn't seem to be the case. Instead, we need to run a more explicit permission grant:

```sql
grant select on schema_a.table_a to anon;
```

The inability to pass permissions by granting a role to another role/user feels like a bug. Is this intentional, or are we missing a step?

</div>

**Comment by steve-chavez** [comment]
Sorry for the late reply on the discussion. Let's continue there https://github.com/orgs/supabase/discussions/13896.

**Comment by steve-chavez** [comment]
@thisisgoldman This is now being fixed on https://github.com/supabase/postgres/pull/651.
