### ISSUE TITLE
Please document manually restoring from a backup

### ISSUE THREAD

**Issue by evelant** [supabase/supabase#14039]
# Improve documentation

## Link 

https://supabase.com/docs/guides/platform/backups

## Describe the problem

The docs mention that backups are created with `pg_dumpall` but doesn't specify the options used or the options needed to restore from one of these backups.

Attempting to do the obvious thing to restore a backup to a local postgres `psql -f my_backup_downloaded_from_backups_page.backup` seems to partially work. There are a lot of `[\N ](error: invalid command \N)` and other warnings emitted.

## Describe the improvement

1. A section about _exactly_ how the backups are created. 
2. A section about _exactly_ the commands used to restore a backup, and any other relevant information needed to restore a backup to a local db

**Comment by gregnr** [comment]
This is good feedback @evelant, thanks.

**Comment by iamchubko** [comment]
Facing the same problem at the moment.
A lot of errors like this:
```
ERROR:  grant options cannot be granted back to your own grantor
```

**Comment by encima** [comment]
We have a detailed page about [backups](https://supabase.com/docs/guides/platform/backups) and the process of creating them now. I will close this as answered for now but, if you want docs on manual restores, please comment and we can revisit
