### ISSUE TITLE
Can't delete a project with a space in the name

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#14057]
# Bug report

If you create a project with a space at the front, it won't be obvious when you go to delete it:

Here, I've created a project called ` space`, that has a space at the beginning: 

<img width="738" alt="CleanShot 2023-05-01 at 10 02 03@2x" src="https://user-images.githubusercontent.com/105593/235452058-eff25cb5-0148-497f-b086-cc921098766d.png">

On the delete screen, it isn't obvious that I need to put a space in the input field to delete it

![CleanShot 2023-05-01 at 10 03 37@2x](https://user-images.githubusercontent.com/105593/235452901-3281aeec-3193-400b-911f-afcfa91341f1.png)

**Proposed solution**
We should make sure to trim any whitespace from the front of the project name upon creation.

**Comment by saltcod** [comment]
Thanks @vladutvoicu ! We don't really have an assigning process here. More first come first served. Feel free to give it a go though. Thanks for the help!

**Comment by gregnr** [comment]
Fixed in https://github.com/supabase/supabase/pull/14061
