### ISSUE TITLE
Twitter Logins doesn't work anymore

### ISSUE THREAD

**Issue by delzennejc** [supabase/supabase#14087]
## Describe the bug

When my users try to Login using Twitter, It shows me this, while the API key, secret and Callback are the correct ones.

Do anyone have this issue or know how to solve it? Here's a screen of what it tells me when I try to login with Twitter.

![image](https://user-images.githubusercontent.com/8841718/235751861-d11b80b9-ead9-4202-b07f-cf5489bfc0d5.png)

**Comment by altryne** [comment]
@delzennejc hey, the same happened to me at https://targum.video, have you checked that your twitter API credentials are still valid? 

Twitter just reset and invalidated most of the previous API credentials, and are urging folks to open new twitter API apps on either the basic or paid tiers. 

What worked for me was, reconfigure the twitter API credentials from scratch (IE, create a new app, configure the app per instructions with the supabase redirect, and then regenerate credentials on twitter developer page) and then add them to supabase again.

**Comment by delzennejc** [comment]
@altryne Thanks a lot ! I deleted everything, even the Twitter v1.1 in their developer platform, recreated the at from the app clean slate, and it worked! thanks :)

**Comment by Developer27149** [comment]
FK.We can use OAuth 2.0 client ID and Client Secret.Just use Consumer keys is ok.And we must checked Request email from users options in app permissions.
![image](https://github.com/supabase/supabase/assets/23721611/4edd59ac-1f0c-40fb-90a3-49c0fe412dcf)
