### ISSUE TITLE
Error copying Storage object url to clipboard on Windows / Chrome

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#14090]
# Bug report

## Describe the bug

Sentry is reporting this error, starting after [this commit](https://github.com/supabase/supabase/commit/f0bb294) that fixed the copy to clipboard issue in Safari:

`Failed to construct 'ClipboardItem': Failed to convert value to 'Blob'.`

<img width="687" alt="CleanShot 2023-05-02 at 16 59 59@2x" src="https://user-images.githubusercontent.com/105593/235766559-2e329972-abc5-4238-868b-9fd64d02b6c7.png">

## System information

- OS: Windows
- Chrome 97.0.4692

@gitstart any chance someone's got a Windows machine?

**Comment by Shivam-9236** [comment]
it mainly depends on the data type u r using ,u can try  MIME type for the data, or browser up to date might resolve the problem.
