### ISSUE TITLE
A possible bug in the schema example sql code

### ISSUE THREAD

**Issue by NeatFastro** [supabase/supabase#14095]
# Improve documentation

## Link 

https://supabase.com/docs/guides/database/tables#schemas

## Describe the problem

I'm not very familiar with postgres db but I think the example sql for "how to create a table within a specific schema is incorrect.

## Describe the improvement

I have a PR ready which fixes the described problem by prefixing the table name (salaries) with the schema name (private) separated by a dot (.)

I have also included an 'Admonition' of type 'note' to ensure that users learn the about the prefixing of the schema name with a dot syntax.

**Comment by gregnr** [comment]
Hey @NeatFastro, would you be able to link the PR so we can take a closer look? Thanks!

**Comment by NeatFastro** [comment]
Sorry for the late response.

here you go: [PR](https://github.com/supabase/supabase/pull/14751)
