### ISSUE TITLE
Clarify Team ID source for Sign in with Apple

### ISSUE THREAD

**Issue by RMcGhee** [supabase/supabase#14129]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/social-login/auth-apple

## Describe the problem

In the linked page, the directions indicate that your Team ID is:
team_id = "Your Team ID". This is found at the top right of the Apple Developer site (next to your name).

The default Apple developer website (developer.apple.com/account) has your Team Name here, not Team ID. I unfortunately did not register the difference, and spent quite a bit of time debugging my mistake.

## Describe the improvement

I think it would be clearer and more reliable to change the documentation to read:
team_id = "Your Team ID". This is found at the Apple Developer website, under Membership details, a 10-character alphanumeric string called "Team ID". Alternatively, this can be seen next to your name in the upper right when viewing your Certificates, Identifiers & Profiles.

## Additional context

Appreciate all your hard work!

**Comment by RMcGhee** [comment]
@gregnr PR up: https://github.com/supabase/supabase/pull/14137

**Comment by gregnr** [comment]
#14129 merged. Thanks @RMcGhee!
