### ISSUE TITLE
Reduce RLS warning clutter

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#14130]
In the Table Editor, if you have RLS disabled, you'll see both of these warnings — a badge and a banner: 
In this case, the banner is sufficient. To reduce clutter there, we shouldn't show the badge. 

<img width="689" alt="CleanShot 2023-05-04 at 12 27 01@2x" src="https://user-images.githubusercontent.com/105593/236246887-c4e1322e-46f6-4eed-9af0-869c3a1b8c5b.png">

**Comment by suryansh-malik** [comment]
please assingn the issue

**Comment by Shaurysingh716** [comment]
Can I work on this issue?
