### ISSUE TITLE
Docs: CORS handling when invoking edge function from the browser

### ISSUE THREAD

**Issue by gregnr** [supabase/supabase#14135]
# Improve documentation

## Link 

https://supabase.com/docs/guides/functions/quickstart#invoking-remote-functions

## Describe the problem

Edge function docs don't currently account for the fact that invoking edge functions from the browser will require CORS handling.

## Describe the improvement

Include a basic working example in docs, eg:
```ts
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

console.log('Hello from Functions!')

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  return new Response(JSON.stringify(data), {
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/json',
    },
  })
})
```

**Comment by charislam** [comment]
There is a guide here https://supabase.com/docs/guides/functions/cors but it should be linked from Getting Started as well
