### ISSUE TITLE
deleting a column causes studio to fail

### ISSUE THREAD

**Issue by AdditionAddict** [supabase/supabase#14141]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've deleted a column internal_note_2 from my "procurement.orders" table. Quotes needed (will migrate to schema later but the table is prefixed "procurement." for now).

I'm getting 400 logs in the https://app.supabase.com/project studio 

`{"message":"Failed to run sql query: column \"internal_note_2\" does not exist"}`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

delete `internal_note_2` to get table,
```
create table
  public.procurement.orders (
    id integer not null default nextval(
      '"purchase_order_PurchaseOrderNumber_seq"'::regclass
    ),
    order_date date null,
    total_value numeric(10, 2) null,
    supplier_note text null default ''::text,
    internal_note text null default ''::text,
    delivery_to_external_person text null default ''::text,
    delivery_instruction text null default ''::text,
    delivery_required_by date null,
    awaiting_prices boolean null,
    all_items_received boolean not null,
    created_at timestamp without time zone null default now(),
    updated_on timestamp without time zone null default now(),
    supplier_id uuid null,
    employee_id uuid null,
    delivery_recipient_id uuid null,
    delivery_location_id uuid null,
    constraint purchase_order_pkey primary key (id),
    constraint procurement.orders_delivery_location_id_fkey foreign key (delivery_location_id) references "procurement.delivery_locations" (id),
    constraint procurement.orders_employee_id_fkey foreign key (employee_id) references staff_members (id),
    constraint procurement.orders_supplier_id_fkey foreign key (supplier_id) references "procurement.suppliers" (id)
  ) tablespace pg_default;
```

## Screenshots

The table is blank after 400 console.log error

![image](https://user-images.githubusercontent.com/48436581/236293106-de8fff35-f6d8-48b8-8b2b-bd23334f6140.png)

## System information

- OS: [e.g. macOS, Windows] Windows
- Browser (if applies) [e.g. chrome, safari] chrome
- Version of supabase-js: [e.g. 6.0.2] N/A
- Version of Node.js: [e.g. 10.10.0] N/A

## Additional context

400 from endpoint `https://api.supabase.io/platform/pg-meta/<project-id>/query?key=public-procurement.orders`

**Comment by saltcod** [comment]
Hi @AdditionAddict — sorry you're running into this — could you please open a support ticket? You can do so via the Help button in the top right of the Dashboard. 

Thanks!

**Comment by MildTomato** [comment]
@AdditionAddict could we see the table definition of `procurement.orders` before you deleted `internal_note_2` column ?

as @saltcod said, this might be better solving via our support ticket channel, as some of your schema might be sensitive and you might not want to share it in public here.

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
