### ISSUE TITLE
Error when trying to upload files to Storage thru the Studio [Self-hosted]

### ISSUE THREAD

**Issue by kaibeckers** [supabase/supabase#14164]
# Studio cannot upload files to Storage [Self-hosted]

- [x] I confirm this is a bug with Supabase, not with my application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Uploading a file to a storage bucket in the Studio will not work. An "ERR_CONN_REFUSED" error will appear in the console. This error isn't forwarded to the frontend GUI aswell: the user won't see the upload has failed.

Creating folders doesn't work either: they appear, but once you refresh, they disappear. 

 All tables in the 'storage' schema can be accessed, as evident by the fact I can create a bucket & there are migrations, except for the 'objects' tables.

## Workaround

As of right now, using the Supabase SDK (for NodeJS) works fine, here's an example;

```js
const filePath = './source/images/adecal';
const fileData = fs.readFileSync(filePath);

supabase.storage
  .from('abucket')
  .upload('adecal.png', fileData, {
    contentType: 'image/png'
  })
```

## To Reproduce

1. Create a VPS that is running on Ubuntu 22.04, with Docker & Docker-Compose installed
2. Follow the self-hosting guide: clone repo, set all ENV's, etc.
3. Enter the Studio
4. Create a bucket
5. Try to upload a file or create a folder

## Expected behavior

The image is uploaded and there are no errors in the console.

The folder will stay and not disappear once refreshed.

## Screenshots
<img width="358" alt="Schermafbeelding 2023-04-27 om 16 19 06" src="https://user-images.githubusercontent.com/53176455/234891288-79492ce7-b36f-48a5-95b3-6f7660e7d432.png">
<img width="921" alt="Schermafbeelding 2023-04-27 om 16 19 20" src="https://user-images.githubusercontent.com/53176455/234891315-5e9f2eb6-12ff-4554-9a27-ae115ff5f6a4.png">

https://user-images.githubusercontent.com/53176455/234891615-1b8b8dfb-a7d7-412f-8c76-e6c831e91592.mov

## System information

- OS: Ubuntu 22.04
- Docker Version: v23.0.4, build f480fb1
- D-Compose Version: v2.17.3

- Chrome
- macOS 12.6.5

## Additional context

Other features like Authentication are broken as well: fetching errors (?)

**Comment by saltcod** [comment]
Apologies for the long delay on this one.  Is this still an issue @kaibeckers?

**Comment by kaibeckers** [comment]
Hey! No worries.

I've restarted & installed my instance, and it seems like the issue persists. I'll do some more testing later today to see if it is isolated to my machine, but, I'll drop the Droplet IP down below so you can test aswell (credentials are at default)

http://68.183.208.101:8000/project/default

<img width="417" alt="Schermafbeelding 2023-08-30 om 13 54 30" src="https://github.com/supabase/supabase/assets/53176455/cf6b63d2-f216-4f5f-8ddc-a577b3341e8e">

**Comment by kiwicopple** [comment]
I'm able to reproduce here using a "clean" setup (docker compose up)

It starts successfully by requesting all buckets `http://localhost:8000/api/storage/default/buckets`

And the data looks good:

```json
[
  {"id":"test","name":"test","owner":"","public":true,"file_size_limit":null,"allowed_mime_types":null,"created_at":"2023-08-30T19:09:44.164Z","updated_at":"2023-08-30T19:09:44.164Z"},  
  {"id":"test2","name":"test2","owner":"","public":false,"file_size_limit":null,"allowed_mime_types":null,"created_at":"2023-08-30T19:11:14.290Z","updated_at":"2023-08-30T19:11:14.290Z"}
]
```

then the next request is odd:

```
http://localhost:8000/project/default/storage/buckets/undefined/projects/default/custom-hostname
```

specifically "undefined" in this part `buckets/undefined/projects`, which seems the same in @kaibeckers 's instance

**Comment by saltcod** [comment]
@ivasilov this one can be closed I think?

**Comment by crapthings** [comment]
same here

i hosted supabase with another ubuntu server with local network
it looks url is using localhost which should be 192.168.50.105

<img width="2497" alt="image" src="https://github.com/supabase/supabase/assets/1147704/d9718c61-dc10-4781-8db8-084ed0838d4c">

<img width="2122" alt="image" src="https://github.com/supabase/supabase/assets/1147704/5a19a484-2a31-4951-ab75-b78ed50fb8d3">

**Comment by ivasilov** [comment]
> same here
> 
> i hosted supabase with another ubuntu server with local network
> it looks url is using localhost which should be 192.168.50.105

Hey @crapthings I tried using your config (it's incomplete btw) and I can't replicate this on latest `supabase/supabase/master`. Are you running the latest versions of all supabase containers? Can you post the output of `docker container ps | grep supabase` ?


As a sidenote, you can force Docket to pull the latest images by running `docker-compose down && docker-compose build --pull && docker-compose up -d`

**Comment by ivasilov** [comment]
I found the culprit, it's a mismatch between two environment variables. Should be fixed by https://github.com/supabase/supabase/pull/17587. 

Edit the `docker-compose.yml` and update to the latest docker image which should be out next Tuesday, you can check [here](https://hub.docker.com/r/supabase/studio/tags).

Please reopen and ping me if the issue still persists.
