### ISSUE TITLE
update docs to fix error in react native 0.70.1 and expo 47

### ISSUE THREAD

**Issue by kaioenzo** [supabase/supabase#14185]
# Improve documentation

## Link 

[Page of documentation with error](https://supabase.com/docs/guides/getting-started/tutorials/with-expo)

## Describe the problem

The documentation has a error that not includes a import in section `building the app` where when using react native >= 0.70 and expo version compatible an error is thrown in initialization of app. To fix this is just necessary to add the import of 'react-native-url-polyfill/auto' before all imports once.

```
import 'react-native-url-polyfill/auto';
```

## Describe the improvement

Add the import missmatch to fix the error.

**Comment by faizanraso** [comment]
Hi @kaioenzo  just wanted to clarify this is the fix you are suggesting correct?

<img width="1512" alt="Screenshot 2023-05-08 at 10 39 14 AM" src="https://user-images.githubusercontent.com/59986120/236853538-0fe34446-c234-4adb-9fa7-a7b6515c115a.png">

**Comment by kaioenzo** [comment]
Yes, @faizanraso that's it!
I started a new project using Expo and tested this tutorial to learn about the integration I faced a crash of my app without this line.

**Comment by faizanraso** [comment]
Sounds good. I submitted a PR thats awaiting review.
