### ISSUE TITLE
Outdated Login with Zoom documentation

### ISSUE THREAD

**Issue by anas-araid** [supabase/supabase#14199]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/social-login/auth-zoom

## Describe the problem

After following the current documentation on "Login with Zoom", on my app I'm redirected back to the homepage with `?error=server_error&error_description=Error+getting+user+email+from+external+provider` appended to the URL.

This is because the Zoom OAuth app requires a `user:read` scope to be able to access email addresses. And Supabase relies on the assumption that users signing in with Oauth providers have an email linked to their account, which isn't always the case. However, this is not mentioned in the documentation. 

It should be also mentioned that you need to add your redirect and application url in the Zoom OAuth allow list and in the Supabase "URL Configuration > Site url"

## Describe the improvement

Update the documentation with the missing informations:
- Clarify that the `user:read` scope is needed if you want integrate Zoom OAuth.
- Add Supabase callback url in the Zoom OAuth allow list
![Screenshot 2023-05-08 at 10 54 44](https://user-images.githubusercontent.com/23257651/236781651-4f4dc79e-cf23-4981-a4bb-919d35b04db4.png)
- Add your application url in Supabase Site URL Configuration
![Screenshot 2023-05-08 at 10 52 58](https://user-images.githubusercontent.com/23257651/236780987-2b63e2b0-043d-4898-b6e8-fd821852852b.png)

## Additional context

Probably this is related somehow to this issue: https://github.com/supabase/gotrue/issues/214

**Comment by gregnr** [comment]
This is good feedback @anas-araid. Would you be interested in opening a small PR for this?

https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/auth/social-login/auth-zoom.mdx
