### ISSUE TITLE
How to enable edge functions and projects to start simultaneously and self manage

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#14212]
How to enable edge functions and projects to start simultaneously and self manage

**Comment by gregnr** [comment]
Hey @jijkbird thanks for the issue. Could you provide more details on what you're looking for help with? ie. are you asking about running the edge functions locally via CLI? What issues or pain points are you experiencing?

**Comment by jijkbird** [comment]
I saw a cloud function label on the console, but the project I started using Docker myself did not have this label. There is code for cloud functions in the Docker directory. What are the rules for these codes? I am trying to access them http://localhost:8000/functions/main Get prompt {"message": "no Route matched with those values"}
@gregnr

**Comment by gregnr** [comment]
Just to confirm, are you referring to edge functions? The best way to run the Supabase stack with edge functions locally is via the `supabase` CLI. Have you tried following this guide?

https://supabase.com/docs/guides/functions/local-development

**Comment by jijkbird** [comment]
I want to use Docker to run

@gregnr

**Comment by rohaanhamid** [comment]
Same problem here. 

Shouldn't the local supabase studio be showing a page for functions?

![image](https://user-images.githubusercontent.com/2194272/237009053-5a58e5d4-a5ea-49c8-aa1b-85033e2d6efe.png)

**Comment by gregnr** [comment]
@rohaanhamid Edge functions are still in beta for [self hosting](https://supabase.com/docs/reference/self-hosting-functions/introduction) (we just recently released [`edge-runtime`](https://supabase.com/blog/edge-runtime-self-hosted-deno-functions)), but the goal is to bring that in there.

@jijkbird Worth noting the `supabase` CLI uses Docker under the hood, though it is typically used for dev. I assume you are looking to self-host edge functions in Docker.

cc @laktek who may have more insight on running self-hosted edge functions in Docker.
