### ISSUE TITLE
All modules in the log report an error of 500

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#14210]
All modules in the log report an error of 500

{
  "code": 500,
  "message": "An error has occurred: request to http://localhost:54329/api/endpoints/query/name/logs.all?project=default&sql=select+id%2C+storage_logs.timestamp%2C+event_message+from+storage_logs%0A++%0A++limit+100%0A++&iso_timestamp_start=2023-05-08T16%3A00%3A00.000Z&ref=default&project_tier=ENTERPRISE failed, reason: connect ECONNREFUSED 127.0.0.1:54329",
  "requestId": "cdb911cb-ccc5-4c87-941b-77c8befd2086"
}

**Comment by jijkbird** [comment]
jack@jack-System-Product-Name:~/api/maichi$ docker compose -f docker-compose.yml -f docker-compose-logging.yml up
WARN[0000] The "MFA_ENABLED" variable is not set. Defaulting to a blank string. 
[+] Running 3/2
 ✔ Container supabase-imgproxy   Created                                                                                                                                                                                                                         0.1s 
 ✔ Container supabase-vector     Created                                                                                                                                                                                                                         0.1s 
 ✔ Container supabase-db         Created                                                                                                                                                                                                                         0.1s 
 ⠋ Container supabase-analytics  Creating                                                                                                                                                                                                                        0.0s 
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/jack/api/maichi/gcloud.json

**Comment by Ziinc** [comment]
Hi @jijkbird , you can follow the setup instructions for the self-hosted analytics server [here](https://supabase.com/docs/reference/self-hosting-analytics/introduction)
