### ISSUE TITLE
og image description undefined

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#14229]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When a Docs og images has a description that is undefined the og image generator displays the undefined description.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [obuldanrptloktxcffvn.functions.supabase.co/og-images?site=docs&type=getting-started&title=Use%20Supabase%20with%20NextJS&description=undefined](https://obuldanrptloktxcffvn.functions.supabase.co/og-images?site=docs&type=getting-started&title=Use%20Supabase%20with%20NextJS&description=undefined)

## Expected behavior

If the description is undefined Don't render the description.

## Screenshots

<img src="https://obuldanrptloktxcffvn.functions.supabase.co/og-images?site=docs&type=getting-started&title=Use%20Supabase%20with%20NextJS&description=undefined" alt="supabase docs og image"/>

## System information

- OS: Any
- Browser: Any
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by tarunsamanta2k20** [comment]
I would like to wok on it.
