### ISSUE TITLE
supabase/studio:20230330-99fed3d ignoring SUPABASE_PUBLIC_URL and using http://kong:8000 instead in the Storage section

### ISSUE THREAD

**Issue by andreystavitsky** [supabase/supabase#14232]
# Bug report

## Describe the bug
after upgrading from supabase/studio:20230216-e731b77 to supabase/studio:20230509-e3eac96, studio is ignoring value set in the SUPABASE_PUBLIC_URL variable. 

For example, in the supabase/studio:20230216-e731b77 when I pressing Get URL in the Storage section, I'm receiving url like **http://kong:8000/** storage/v1/object/public/place-images/2ba3b0e2-8b16-11eb-89aa-0242c0a85004/01079d14-af78-414d-8294-e6abfdd9faea_thumb.webp instead of **https://my_api_url.com/** storage/v1/object/public/place-images/2ba3b0e2-8b16-11eb-89aa-0242c0a85004/01079d14-af78-414d-8294-e6abfdd9faea_thumb.webp

## To Reproduce
upgrade Studio from supabase/studio:20230216-e731b77 to supabase/studio:20230509-e3eac96 and try to copy URL from storage

## Expected behavior

Url should follow the value from .env

**Comment by andreystavitsky** [comment]
After releasing studio supabase/studio:20230512-ad596d8 there's correct url, but incorrect port (it uses port 8000 wihtout ability to overwrite it to 443), like  https://my_api_url.com:8000/storage/v1/object/public/place-images/2ba3b0e2-8b16-11eb-89aa-0242c0a85004/01079d14-af78-414d-8294-e6abfdd9faea_thumb.webp

**Comment by andreystavitsky** [comment]
Issue still persist in the supabase/studio:20230601-aa640ee

**Comment by andreystavitsky** [comment]
Issue still present in the studio 0.23.05_amd64 (for about 3 months for now)

**Comment by snsnf** [comment]
Me too I'm facing this problem, I'm searching for a solution since yesterday, and even after updating to the last Supabase version the bug is still present, it's a priority to solve it.

**Comment by sweatybridge** [comment]
@andreystavitsky have you tried setting `SUPABASE_PUBLIC_URL=https://my_api_url.com:443`? The [code](https://github.com/supabase/supabase/blob/master/studio/pages/api/storage/%5Bref%5D/buckets/%5Bid%5D/objects/public-url.ts#L27) for rewriting public url seems correct to me.

**Comment by sweatybridge** [comment]
Feel free to reopen if anyone still faces this problem.

**Comment by andreystavitsky** [comment]
I'm still receiving 
https://my.supabase.url:**8000**/storage/v1/object/public/chat_images/Sgl5wXTwiLdiS5CazciE65tVDDx2_cll13ioqr0021rk01e8qxvrce_be8ec9e1-be37-46e7-877c-2ce0d771c6e7.webp
with supabase/studio:20230803-15c6762

**Comment by ivasilov** [comment]
Should be fixed by https://github.com/supabase/supabase/pull/17587. 

Edit the `docker-compose.yml` and update to the latest docker image which should be out next Tuesday, you can check [here](https://hub.docker.com/r/supabase/studio/tags).

Please reopen and ping me if the issue still persists.
