### ISSUE TITLE
Locahost supabase refresh tokens cannot be used after jwt has expired

### ISSUE THREAD

**Issue by DevOfManyThings** [supabase/supabase#14234]
# Bug report

- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On localhost supabase if `client.auth.refreshSession({refresh_token});` is called using a refresh_token which is older than the `jwt_expiry` time configured in `config.toml`, you get the following error:

`
Invalid Refresh Token: Already Used
    at E:\...\node_modules\@supabase\gotrue-js\dist\main\lib\fetch.js:41:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  __isAuthError: true,
  status: 400
}
`
I've tested my login flow on an officially hosted Supabase instance, and the `refresh_token` can create a new `access_token` even after the expiration time (the expected behaviour) the error only occurs on localhost supabase.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Configure `jwt_expiry` to a small number to make testing easier, eg 120.
2. Login as a user on Supabase
3. Wait for the jwt to expire
4. On the server the code should detect that no `access_token` has been sent, and attempt to refresh using `client.auth.refreshSession({refresh_token});`
5. The above error occurs

## Expected behavior

Behaviour on localhost supabase should be the same as hosted supabase, the refresh token should not expire or display the erranous error message that it has already been used.

## Screenshots

N/A

## System information

- OS: Windows
- Browser: N/A
- Version of supabase-js: 2.10.0
- Version of Node.js: 18.13.0

## Additional context

In my use case the supabase client doesn't run on the users machine, it only runs on the server so I can't rely on the client auto refreshing the token. The `access_token` and `refresh_token` are stored in cookies, so when a user submits a request to the server if the `access_token` is expired, I need to generate a new one.

This is a redacted version of my hooks.ts sveltekit application which performs the check on every request to the server:
```
    const options = {
      auth: {
        persistSession: false,
      },
    }
    const userClient = createClient(
      SUPABASE_URL,
      SUPABASE_ANON_KEY,
      options
    );
    let access_token = event.cookies.get('access_token');
    let refresh_token = event.cookies.get('refresh_token');
    if(refresh_token) {
      if(!access_token) {
        const {data, error} = await userClient.auth.refreshSession({refresh_token});
        if(error) {
          console.log("error refreshing access token: ", error);
        }
        access_token = data.session.access_token;
        refresh_token = data.session.refresh_token;
      }
      await userClient.auth.setSession({access_token, refresh_token});
    }
```

**Comment by j4w8n** [comment]
In your client options, you'll want to add `autoRefreshToken: false`. Otherwise, even on the server, the client will try to refresh the token. This is likely the cause of your problem. If you're waiting until after the jwt expires, the client will have already tried to use the refresh token. Although I'm not sure why your experience would be different on hosted.

Personally, I also set `detectSessionInUrl` to false for server-side clients.

**Comment by DevOfManyThings** [comment]
@j4w8n I set both of those options and it worked as expected! I'm not sure why supabase hosting has different behaviour to localhost, but thanks for the help!

**Comment by j4w8n** [comment]
> @j4w8n I set both of those options and it worked as expected! I'm not sure why supabase hosting has different behaviour to localhost, but thanks for the help!

Good to hear!

**Comment by vhpx** [comment]
I'm having this issue as well, where do I set `autoRefreshToken: false`? I'm using the supabase-auth-helper library for a Next.js project.

**Comment by j4w8n** [comment]
> I'm having this issue as well, where do I set `autoRefreshToken: false`? I'm using the supabase-auth-helper library for a Next.js project.

@vhpx 
Checkout the "with additional options" tab
https://supabase.com/docs/reference/javascript/initializing

**Comment by remorses** [comment]
The auth helpers libraries already disable this option on the server
https://github.com/supabase/auth-helpers/blob/9715901658e0925136b9c8c015b6d5c22a7ce6a7/packages/shared/src/createClient.ts#L31

**Comment by j4w8n** [comment]
> The auth helpers libraries already disable this option on the server
> https://github.com/supabase/auth-helpers/blob/9715901658e0925136b9c8c015b6d5c22a7ce6a7/packages/shared/src/createClient.ts#L31

Yep, you're right. I must've glazed over the fact that the person mentioned they were using auth helpers.

If I remember correctly, auth helpers set this based on whether the client is created in a browser context, so it should be set to `false` when on the server-side.

If you're having a problem, you might create a new issue for it.

**Comment by toniengelhardt** [comment]
Hey @kiwicopple, I'm still getting this error with the following code: 

`utils/supabse/client.ts`
```ts
import { createBrowserClient } from '@supabase/ssr';

export const createClient = () =>
	createBrowserClient(
		process.env.NEXT_PUBLIC_SUPABASE_URL!,
		process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
	);
```

`utils/supabase/server.ts`
```ts 
import { cookies } from 'next/headers';

import { type CookieOptions, createServerClient } from '@supabase/ssr';

export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
	return createServerClient(
		process.env.NEXT_PUBLIC_SUPABASE_URL!,
		process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
		{
			cookies: {
				get(name: string) {
					return cookieStore.get(name)?.value;
				},
				set(name: string, value: string, options: CookieOptions) {
					try {
						cookieStore.set({ name, value, ...options });
					} catch (error) {
						// The `set` method was called from a Server Component.
						// This can be ignored if you have middleware refreshing
						// user sessions.
					}
				},
				remove(name: string, options: CookieOptions) {
					try {
						cookieStore.set({ name, value: '', ...options });
					} catch (error) {
						// The `delete` method was called from a Server Component.
						// This can be ignored if you have middleware refreshing
						// user sessions.
					}
				},
			},
			// Experimental fix for "token already used".
			// See https://github.com/supabase/supabase/issues/14234
			auth: {
				autoRefreshToken: false,
			},
		},
	);
};
```

`utils/supabase/middleware.ts`
```ts
import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { type NextRequest, NextResponse } from 'next/server';

export const createClient = (request: NextRequest) => {
	// Create an unmodified response
	let response = NextResponse.next({
		request: {
			headers: request.headers,
		},
	});

	const supabase = createServerClient(
		process.env.NEXT_PUBLIC_SUPABASE_URL!,
		process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
		{
			cookies: {
				get(name: string) {
					return request.cookies.get(name)?.value;
				},
				set(name: string, value: string, options: CookieOptions) {
					// If the cookie is updated, update the cookies for the request and response
					request.cookies.set({
						name,
						value,
						...options,
					});
					response = NextResponse.next({
						request: {
							headers: request.headers,
						},
					});
					response.cookies.set({
						name,
						value,
						...options,
					});
				},
				remove(name: string, options: CookieOptions) {
					// If the cookie is removed, update the cookies for the request and response
					request.cookies.set({
						name,
						value: '',
						...options,
					});
					response = NextResponse.next({
						request: {
							headers: request.headers,
						},
					});
					response.cookies.set({
						name,
						value: '',
						...options,
					});
				},
			},
			auth: {
				autoRefreshToken: true,
				// debug: true,
			},
		},
	);

	return { supabase, response };
```

I'm also using the following middleware to redirect between auth and non-auth views:

`middleware.ts`
```ts
import { type NextRequest, NextResponse } from 'next/server';

import { createClient } from '@/utils/supabase/middleware';

export async function middleware(request: NextRequest) {
	const { supabase, response } = createClient(request);

	const authRoutes = ['/login'];
	const isAuthRoute = authRoutes.includes(request.nextUrl.pathname);

	try {
		const supabaseSession = await supabase.auth.getSession();
		const isAuthenticated = !!supabaseSession.data.session;

		// Redirect to login if the user is not authenticated,
		// otherwise redirect to root if applicable.
		if (isAuthenticated && isAuthRoute) {
			return NextResponse.redirect(new URL('/', request.url));
		} else if (!isAuthenticated && !isAuthRoute) {
			return NextResponse.redirect(new URL('/login', request.url));
		}
	} catch (error) {
		// Experimental temp fix for "AuthApiError: Invalid Refresh Token: Already Used".
		// This is suboptimal as it will log the user out.
		console.log('Error in auth middleware', request.url, error);
		return NextResponse.redirect(new URL('/login', request.url));
	}

	return response;
}
```
