### ISSUE TITLE
Creating/installing custom extensions are not documented

### ISSUE THREAD

**Issue by jquesada2016** [supabase/supabase#14235]
# Improve documentation

## Link 

[Link here](https://supabase.com/docs/guides/database/extensions)

## Describe the problem

The documentation mentions the possibility of being able to install extensions that are not already included, but does not menttion how to achieve this, nor what type can be installed. For example, can I install an extension written in Rust using `pgrx`? How do I get the files up into the database? Etc. I've seen a couple unanswered questions like these in the discord help channel, so having this documented would be very nice.

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Provide documentation and/or instructions, or references on how to create a custom extension and how to get it installed. Are only extensions written with `PL/pgsql` supported? Or is it possible to compile an extension and use it?

**Comment by GaryAustin1** [comment]
Yes only SQL extensions can be added with the SQL editor.
`Supabase is pre-configured with over 50 extensions. You can also install your own SQL extensions directly in the database through our SQL editor.`

Supabase is also working on another concept for customization, but this does not directly address your issue.  
https://supabase.com/blog/dbdev

**Comment by neilpoulin** [comment]
I came across [this blog post on Supabase's](https://supabase.com/blog/choosing-a-postgres-primary-key#benchmarking-id-generation-with-uuid-ossp-and-pg_idkit) site about generating different types of UUIDs and it mentions an extension, `pg_idkit` that looks pretty great, and I wanted to use it. However, it doesn't seem possible to install this extension, or at least I haven't figured out how to do it. 

Is there any way to use this extension?

**Comment by KevinBrolly** [comment]
Hey there,

As Gary mentioned, the ability to install custom extensions will come from [TLE](https://github.com/aws/pg_tle) and https://database.dev/ 

The PR #14600 covers this improvement to the documentation.

@neilpoulin For `pg_idkit` you can intstall it using database.dev, as documented here - https://database.dev/kiwicopple/pg_idkit
