### ISSUE TITLE
Docs sidebar not highlighting current section 

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#14231]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When scrolling through the docs when you get to the sub section the sidebar doesn't indicate where you are in the docs.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/docs/guides/database/full-text-search](https://supabase.com/docs/guides/database/full-text-search)
3. Scroll down

## Expected behavior

When scrolling through the docs the sidebar indicating where you are located should update in the sub sections.

## Screenshots

https://github.com/supabase/supabase/assets/70828596/a9f828ca-8927-4a5d-a20e-ff08e8401e42

## System information

- OS: macOS 13.2.1
- Browser: FireFox 111.01
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by reeveng** [comment]
Another issue but related, when clicking on 1 of the side items that are broken 
![image](https://github.com/supabase/supabase/assets/36441093/2b026636-1c85-48eb-8848-caaea7c94893)
![image](https://github.com/supabase/supabase/assets/36441093/1d61e313-60c6-4438-b4eb-7ce2fc58a0c1)
you don't go to that section either.
I think it is either the `backslashes` in the title or the [#link_generating] thing after it that's causing issues, at the bottom of the page there are also links that have the same issues (namely proximity and negation).

On the same page the [search-using-the-new-column](https://supabase.com/docs/guides/database/full-text-search#search-using-the-new-column) link item has neither of these 2 (the backslashes or the link generating) and works flawlessly.
