### ISSUE TITLE
Clean up frontmatter in `./apps/docs/docs/ref/.../*.mdx` pages

### ISSUE THREAD

**Issue by gregnr** [supabase/supabase#14272]
# Chore

## Describe the chore

Clean up frontmatter in `./apps/docs/docs/ref/.../*.mdx` pages.

Eg. Do we still use `custom_edit_url`? Should we? If not, let's remove. If so let's come up with a task.

**Comment by saltcod** [comment]
@gregnr is this out of date? 
was it fixed by the merged pr?

**Comment by gregnr** [comment]
Looks like this is out of date now - closing now.
