### ISSUE TITLE
supabase start, Error: missing signature key for v0.60.7: Pulling from public.ecr.aws/supabase/postgres-meta

### ISSUE THREAD

**Issue by yren** [supabase/supabase#14283]
# Bug report

when first run supabase start , it show Error: missing signature key for pull docker image
 v0.60.7: Pulling from public.ecr.aws/supabase/postgres-meta

supabase version : v1.57.4/supabase_linux_amd64.tar.gz

----------------error msg

Trying to pull repository public.ecr.aws/supabase/postgres-meta ... 
v0.60.7: Pulling from public.ecr.aws/supabase/postgres-meta
missing signature key10/15)
Retrying after 4s: public.ecr.aws/supabase/postgres-meta:v0.60.7
Trying to pull repository public.ecr.aws/supabase/postgres-meta ... 
v0.60.7: Pulling from public.ecr.aws/supabase/postgres-meta
missing signature key10/15)
Retrying after 8s: public.ecr.aws/supabase/postgres-meta:v0.60.7
Trying to pull repository public.ecr.aws/supabase/postgres-meta ... 
v0.60.7: Pulling from public.ecr.aws/supabase/postgres-meta
Error: missing signature key

**Comment by gregnr** [comment]
Hey @yren, sorry to hear you're experiencing this. I'm having trouble reproducing this - the image seems to pull without issue from my end:
```shell
$ docker pull public.ecr.aws/supabase/postgres-meta:v0.60.7    
v0.60.7: Pulling from supabase/postgres-meta
934ce60d1040: Pull complete 
9af47de66563: Pull complete 
cc2c0c39bbcd: Pull complete 
13b24b9ead39: Pull complete 
44ed386cc4a5: Pull complete 
22154d4adc41: Pull complete 
3dba6237eb42: Pull complete 
3add50c0eb38: Pull complete 
0cf38f6eef4f: Pull complete 
Digest: sha256:c816ae12c3ca785934cf19935c91c08edea6af1488c290fe3b34096e17e23812
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.60.7
public.ecr.aws/supabase/postgres-meta:v0.60.7
```

Could you please provide:
- Docker version
- OS & version

Are you aware of any other special configuration applied to your Docker setup (ie. `~/.docker/config.json` or `/etc/docker/daemon.json`)?

**Comment by yren** [comment]
I can reproduce this issue on 
OS: Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS (Hunting Beagle) , (in essence it's centos7 )
docker: Docker version 1.13.1, build 7d71120/1.13.1
supabase cli: v1.5.81 supabase_linux_amd64.tar.gz


But It woks fine on 
OS: Alibaba Cloud Linux release 3 (Soaring Falcon) (in essence it's centos8)
docker: podman version 4.2.0
supabase cli: v1.5.81 supabase_linux_amd64.tar.gz

I think it's not a common issue, only reproduce on some specific version docker.  
I'll close this.
