### ISSUE TITLE
Add autocomplete/search feature for inputs

### ISSUE THREAD

**Issue by marcelobarreto** [supabase/supabase#1428]
# Feature request

## Is your feature request related to a problem? Please describe.

When creating resources we might be able to filter the exact name of the type we want.

![image](https://user-images.githubusercontent.com/1276556/117073094-d1226280-ad07-11eb-9a9a-bd11bb383768.png)

When adding a varchar column type I have to scroll down until the final of the select.

## Describe the solution you'd like

Add a filter/autocomplete feature to this inputs/selects.

**Comment by tylermercer** [comment]
I've run into this too. Even just using the native select element (styled nicely, of course) would work better here--it natively supports type-to-select.
