### ISSUE TITLE
Document error handling for `supabase.auth.*` methods.

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#143]
* **I'm submitting a ...**
- docs request for https://supabase.io/docs/library/user-management

* **Summary**
As per https://github.com/supabase/supabase-js/pull/18#issuecomment-674840678 we should document how to handle the errors that are thrown by the auth methods.

**Comment by malobre** [comment]
Here's a snippet of how I'm handling errors:

```ts
import type { ResponseError } from 'superagent'; // Type definition for typescript

await supabase
  .auth
  .login('test@mail.com', 'password')
  .then(() => {
    // Success
  }, (error: ResponseError) => {
    // An error occured
    if (error.response === undefined) {
      // No response from server
    } else {
      // Here you can further process the response ..
    }

    if (error.status === undefined) {
      // No HTTP status code
    } else {
      const http_code = error.status;
      // Further processing ..
    }
  });
```
See [`ResponseError`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/superagent/index.d.ts#L90) and [`Response`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/superagent/index.d.ts#L102) for more details.

**Comment by kiwicopple** [comment]
This is very helpful @malobre, thanks!

**Comment by kiwicopple** [comment]
Since we are now all-in on TS, we will have to add tabs to our library docs: 
https://v2.docusaurus.io/docs/markdown-features/#tabs

We already have tabs in the dashboard auto-docs, so I will add this snippet their first. 

I think the library docs will need to be revisited to make it multi-lingual in another task (possible hacktoberfest task)

**Comment by malobre** [comment]
Are the server responses format documented ? If they are I couldn't find them otherwise they should definitely be added to the doc at some point. It would make it easier to display accurate errors to the user (e.g. this mail address is already used, password too short, etc).

**Comment by kiwicopple** [comment]
I'm going to close this with a PR that resolves the docs. 

At some point I investigate using [gotrue-js](https://github.com/netlify/gotrue-js) which is more feature-rich own JS library and then improving errors further. Unfortunately it will mean yet another "http" library (superagent + micro-api-client).

> Are the server responses format documented

Migrated this here: https://github.com/supabase/gotrue/issues/5

**Comment by thorwebdev** [comment]
@kiwicopple thanks for the error handling docs! However, we should probably improve the shape of the error being thrown. 

As it stands today, you have to do 
```js
...} catch (error) {
      console.log('Error message:', error.response.body.error_description);
    } 
```
to get to the error message.
We might even want to consider not throwing an error at all to not stop the rest of the javascript from executing. E.g. my preferred DX would be 

```js
const { error, user } = await supabase.auth.signup(
  'someone@email.com',
  'password'
);
if (error) alert(error);
```

However, I know that @awalias is a big fan of returning the whole response object, which I personally find rather distracting. Maybe we can do something like

```js
const { error, user, raw_response } = await supabase.auth.signup(
  'someone@email.com',
  'password'
);
if (error) alert(error);
```

To give folks the option to access the raw object, but not overload folks who don't care about most of the stuff in the raw response. Wdyt? This probably warrants a new issue?

**Comment by kiwicopple** [comment]
thanks for opening the new issue - I agree with you on the DX needing improvement here. let's chat over there
