### ISSUE TITLE
Bug in docs: duplicated content and TOC removed

### ISSUE THREAD

**Issue by andrewcoelho** [supabase/supabase#14314]
# Improve documentation

## Describe the problem

All pages have duplicated content caused by this PR: https://github.com/supabase/supabase/pull/14267 and this commit specifically: https://github.com/supabase/supabase/commit/693305ee9538a6fc36a7e6d0ea3c25fddd9cdcf3

cc @fsansalvadore

**Comment by fsansalvadore** [comment]
Thanks @andrewcoelho 👍 this is being fixed in this PR: #14317
