### ISSUE TITLE
2FA via an authenticator app with TOTP

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [supabase/supabase#1432]
# Feature request

## Is your feature request related to a problem? Please describe.

My app only has 1FA which can be insecure if the user reuses their password.

## Describe the solution you'd like

I want an API for supporting 2FA with an authenticator app, including the easy QR code thing.

## Describe alternatives you've considered

A janky setup where my own server would connect to supabase to interact with the user which would require a lot of unnecessary complexity.

**Comment by awalias** [comment]
hey @TheBlueOompaLoompa thanks for the request! tracking this one here: https://github.com/supabase/gotrue/issues/14
