### ISSUE TITLE
Local realtime issue

### ISSUE THREAD

**Issue by joshmarnold** [supabase/supabase#14338]
Hello, I'm trying to get realtime working locally. Was not able to with a simple realtime setup. Initially was having trouble with an older version of CLI so upgraded to the latest and am now getting the following error. It seems that the subscription table is not in the realtime schema in my project. I believe that this is a supabase managed thing as I don't see it mentioned anywhere in the docs to setup. Therefore, there's not too much I can do here I feel like.

`"Subscribing to PostgreSQL failed: {:error, "Subscription insert failed with error: ERROR 42P01 (undefined_table) relation \"realtime.subscription\" does not exist\n\n    query: with sub_tables as (\n\t\t    select\n\t\t\t    rr.entity\n\t\t    from\n\t\t\t    pg_publication_tables pub,\n\t\t\t    lateral (\n\t\t\t\t    select\n\t\t\t\t\t    format('%I.%I', pub.schemaname, pub.tablename)::regclass entity\n\t\t\t    ) rr\n\t\t    where\n\t\t\t    pub.pubname = $1\n\t\t\t  and pub.schemaname like (case $2 when '' then '%' else $2 end)\n\t\t\t  and pub.tablename like (case $3 when '' then '%' else $3 end)\n\t    )\n\t    insert into realtime.subscription as x(\n\t\t    subscription_id,\n\t\t    entity,\n        filters,\n        claims\n      )\n      select\n        $4::text::uuid,\n        sub_tables.entity,\n        $6,\n        $5\n      from\n        sub_tables\n        on conflict\n        (subscription_id, entity, filters)\n        do update set\n        claims = excluded.claims,\n        created_at = now()\n      returning\n         id. Check that tables are part of publication supabase_realtime and subscription params are correct: %{\"event\" => \"UPDATE\", \"schema\" => \"public\", \"table\" => \"layers_properties\"}"}"`

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

CLI: 1.58.1
"@supabase/supabase-js": "^2.21.0",

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. chrome]

**Comment by GaryAustin1** [comment]
You mentioned running an earlier version of the CLI.
I've seen comments on Discord about needing to init the project again after updating the CLI.
Did you do that?

**Comment by chasers** [comment]
Yeah somehow the realtime.subscription table got dropped.

**Comment by possibilities** [comment]
I learned that when I call supabase db reset (using 1.82.6) that I get this error even if I do it on a new project just before running the migrations for the first time. I assume it's a misconception on part that that should be possible but in my case I was trying to reset to iterate on a new migration. If anyone has a suggestion of a better way to do this I appreciate it.
