### ISSUE TITLE
Undifined/ incomplete components in docs

### ISSUE THREAD

**Issue by abedshaaban** [supabase/supabase#14349]
1. Go to https://github.com/supabase/supabase/blob/7c55446707a6e8ea1b795aa91a8a6fa99357a85f/apps/docs/pages/guides/auth/auth-helpers/nextjs-server-components.mdx?plain=1#L294

2. `SupabaseListener` and `session` are not defined in the docs

please add types for ts when you add the missing documentation,

**Comment by maximilianschmidt** [comment]
duplicate of #14327

**Comment by gregnr** [comment]
Thanks for reporting @abedshaaban! This does look like a dupe of https://github.com/supabase/supabase/issues/14327. Going to close this one - feel free to reopen if you think otherwise.
