### ISSUE TITLE
Add uploadBinary function to the flutter reference docs

### ISSUE THREAD

**Issue by FatumaA** [supabase/supabase#14352]
# Improve documentation

## Link 

[Link to the relevant docs](https://supabase.com/docs/reference/dart/storage-from-upload)

## Describe the problem

The function uploadBinary() is missing

## Describe the improvement

Document the function

**Comment by FatumaA** [comment]
@dshukertjr - is this ok to add?

**Comment by dshukertjr** [comment]
@FatumaA Thanks for the amazing catch! Yup, would be great to add it in. Would you be able to do it?

**Comment by FatumaA** [comment]
Linked the PR. Added it within the upload file section examples, didn't seem like it needed its own section. 
@dshukertjr

**Comment by dshukertjr** [comment]
Thanks @FatumaA ! A member from the frontend team will authorize a deploy to the vercel preview in a minute.
