### ISSUE TITLE
Unable to search docs with query: 自定义角色

### ISSUE THREAD

**Issue by rjl-cli** [supabase/supabase#14353]

**Comment by gregnr** [comment]
@rjl-cli thanks for reporting! Supabase search isn't multi-lingual yet, though it will be great to support this eventually.

In the mean time you can try using Supabase AI to help answer non-English questions:

![image](https://github.com/supabase/supabase/assets/4133076/6ed85a3f-f0b2-466a-a059-3c4a4234134c)

This functionality was just merged moments ago: https://github.com/supabase/supabase/pull/14372

Let me know if this helps!

**Comment by rjl-cli** [comment]
yarn create rjl
