### ISSUE TITLE
SDK'S for ios and android

### ISSUE THREAD

**Issue by Nike682631** [supabase/supabase#1436]
#SDK'S SIMILAR TO FIREBASE FOR IOS AND ANDROID

## Supabase is a firebase alternative so an important feature would be to have SDK'S for android and ios like firebase 

Below are some links regarding the same.
https://github.com/firebase/firebase-ios-sdk
https://github.com/firebase/firebase-android-sdk

## Would like to have  supabase sdk's for ios and android

It would be more justice to call supabase a firebase alternative if we have SDK'S for android and ios compatible with supabase
Would be happy to work on this issue if some guidance is provided.

**Comment by kiwicopple** [comment]
Hey @Nike682631 - this is a broad feature request so I'll drop some notes here.

You can vote on more client libraries here: https://github.com/supabase/supabase/discussions/5

The community have these ones in progress 

For ios:

- Swift: https://github.com/supabase/?q=swift&type=&language=&sort=

For Android:

- Kotlin: https://github.com/supabase/?q=kt&type=&language=&sort=
- Java: https://github.com/supabase/?q=java&type=&language=&sort=

Cross platform:

- Dart: https://github.com/supabase/?q=dart&type=&language=&sort=
- Expo/react native (use our official JS libraries)


We'd love to have more client libraries! Feel free to upvote in the Discussion - or (even better) help contribute by building one with us :)

**Comment by Nike682631** [comment]
@kiwicopple Can you give me the link for the supabase discussion group?

**Comment by kiwicopple** [comment]
Hi @Nike682631. We use GitHub Discussions as our community Forum (the tab at the top of the page): https://github.com/supabase/supabase/discussions
