### ISSUE TITLE
Unit tests periodically failing in Github action

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#14463]
We noticed around May 15th that our studio unit tests action would fail periodically due to a heap size error.

Info here:
https://github.com/supabase/supabase/pull/13580#issuecomment-1548454444
https://github.com/supabase/supabase/actions/runs/4896703579/jobs/8922622104#step:5:365

Tests are also failing locally now on `master`, suggesting a memory leak.

Tests around the logs-query-test and api-report are probably worth investigating. 

cc @brandongregoryscott — any insights you might have would be much appreciated!

**Comment by saltcod** [comment]
cc @gitstart as well as you all are pretty deep into unit tests I think :^)

**Comment by brandongregoryscott** [comment]
Additional investigation notes in this PR: https://github.com/supabase/supabase/pull/13916#issuecomment-1550375357

I'll keep looking. The `api-report` test suite allocates a huge amount of memory for seemingly simple test arrangements.
