### ISSUE TITLE
Home page video swiper is overflowing

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/supabase#1446]
# Bug report

## Describe the bug

On the home page, in the section "Build your app without leaving the dashboard", the videos are supposed to be sliding when clicking on tabs. But depending of the selected tabs, there can be overflow.

## Expected behavior

Video should be sliding without seeing any scrollbar.

## Screenshots

![image](https://user-images.githubusercontent.com/69633530/117180461-7c98e900-add4-11eb-9132-149d2e15c0f0.png)

## System information

- OS: Windows 10
- Browser (if applies) Opera GX (73 ?)

**Comment by MildTomato** [comment]
@florian-lefebvre  @carlosstenzel  thanks folks 💯  🚀
