### ISSUE TITLE
Generate entity relationship diagrams

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#1449]
# Feature request

## Is your feature request related to a problem? Please describe.

When working with a large database with dozens of tables and foreign key relationships, entity relationship (ER) diagrams really help with understanding how the database operates.

## Describe the solution you'd like

Generate an ER diagram automatically, and keep it up-to-sync with actual database.

For instance, in the dashboard in the Database section, add a new tab called "Diagram." This would then be the visual representation of the database.

Does not need to be editable.

## Describe alternatives you've considered

You could always create one by hand, but automatic documentation like this is always better than manual documentation (assuming the quality is the same)

## Additional context

While it would be helpful, I do think functions and local development migrations are a higher priority, personally. Would not be disappointed if this feature is never added, but incredibly excited it if is.

**Comment by awalias** [comment]
closing for spring cleaning. there is a cool unofficial one that someone made here: https://supabase-schema.vercel.app/
