### ISSUE TITLE
Cannot access Webhooks page

### ISSUE THREAD

**Issue by remi2257** [supabase/supabase#14501]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Section Database > Webhooks is not accessible (https://app.supabase.com/project/<id>/database/hooks)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database
2. Click on Webhooks

## Expected behavior

See the page containing Webhooks

## Screenshots

![image](https://github.com/supabase/supabase/assets/39727257/50516fae-6246-4bc7-9a2a-7ad87c67a84c)
![image](https://github.com/supabase/supabase/assets/39727257/966b1340-73f4-4942-be8f-c12cb4072b48)
![image](https://github.com/supabase/supabase/assets/39727257/70165b2e-917a-4084-8d2f-da8d4dee666e)

## System information

- OS: Ubuntu
- Browser : Chrome & Firefox
- Version of supabase-js: last ?

## Additional context

- I created another project and I didn't have the problem
- I succeed recreating the project in this empty project
  1. Go on trigger
  2. Create a condition which fire on INSERT of a table
  3. Set 'function to trigger' to "http_request" 

NB : If only this function is problematic, can you, as a quick fix, delete all the hooks in my 2 projects please ?

**Comment by rmill2016** [comment]
+1, came here to report same issue, I'm unable to access webhooks as well!

**Comment by saltcod** [comment]
Hey @remi2257 and @rmill2016 — would you mind creating a support ticket for this issue? We'll be able to check your actual projects. You can do this via the Help button in the top right of the dashboard.

**Comment by pcnc** [comment]
Hey @remi2257 , @rmill2016  - we think we've managed to reproduce the issue and are working on a fix.

This seems to be happening when a trigger is created through the Triggers list within the dashboard with `http_request` as a trigger function, targeting a table in the `net` schema.

Webhooks uses triggers under the hood, but it also provides URL-specific parameters to the trigger definition, which we then use when displaying the hook list - this is why the UI crashes.

**Comment by remi2257** [comment]
Hey,

I just sent a support ticket ! Can you clean this bad trigger so that I can continue to work on my app :) ?

Thanks

**Comment by saltcod** [comment]
@remi2257 this should be fixed now, but please let us know if you see otherwise. Thanks!
