### ISSUE TITLE
Inconsistent store recommendations for React Native auth

### ISSUE THREAD

**Issue by MorningLit** [supabase/supabase#14523]
# Improve documentation

## Link 
https://supabase.com/docs/guides/getting-started/tutorials/with-expo#initialize-a-react-native-app
https://supabase.com/docs/reference/javascript/initializing

## Describe the problem
In the starter guide for Expo, it was demonstrated using Expo SecureStore for the auth store, however, in the Javascript client docs, it said that it recommends using AsyncStorage as the store for the auth store.

Also, I started my project with the SecureStore setup and I encountered this warning, 
**Provided value to SecureStore is larger than 2048 bytes. An attempt to store such a value will throw an error in SDK 35.**
My related issue: https://github.com/orgs/supabase/discussions/14306

Not sure if the best way forward for Expo development is to use SecureStore, since there is a size limit.

## Describe the improvement
In the starter guide for Expo, replace the use of Expo's SecureStore with AsyncStorage to avoid confusion.

## Additional context
![image](https://github.com/supabase/supabase/assets/57279935/b57038b7-c537-4911-9830-e75297132f97)
From the getting started with Expo tutorial
![image](https://github.com/supabase/supabase/assets/57279935/e4f5539f-eea6-4b12-8259-ee718d2c6260)
From the Supabase Javascript client docs

**Comment by gregnr** [comment]
Thanks for reporting @MorningLit. Looks like we used to use `AsyncStorage` in the expo tutorial and [switched to `SecureStorage`](https://github.com/supabase/supabase/pull/13351) (based on [this PR](https://github.com/supabase/supabase/pull/11402)) for better security.

It's interesting that your values are greater than 2048 bytes - are you using `SecureStorage` only for Supabase auth, or for other storage as well? Maybe someone from @supabase/auth has insight into this.

**Comment by stoickeyboard** [comment]
I'm getting a `Provided value to SecureStore is larger than 2048 bytes...` error as well

**Comment by kevinhu** [comment]
@gregnr I am seeing this warning as well, and the cause seems to be the `value` in the `setItem` call, which has a length of 2600. I'm only using `SecureStorage` for Supabase auth.

**Comment by gregnr** [comment]
@kevinhu thanks for reporting. Which auth provider are you using?

**Comment by kangmingtay** [comment]
Hey @kevinhu and @stoickeyboard, it seems like this is a current limitation of using [expo's `SecureStorage`](https://docs.expo.dev/versions/latest/sdk/securestore/). We'll look into how we can reduce the size of the session such that it fits within the limits. In the meantime, can `AsyncStorage` be used instead for your usecase?

**Comment by danbovey** [comment]
I have set up native login with Google on my React Native app, instead of using supabase redirects in a web view. I get back a long ID token containing user metadata which I post back to supabase with `supabase.auth.signInWithIdToken`. I also got the `Provided value to SecureStore is larger than 2048 bytes` error, so I decided to make my secure store adapter chunk the string up to avoid the warning/store the Google ID token in full, securely.

Here's my hacky solution: https://gist.github.com/danbovey/74d2710be876fa7691274fd4a20b426e

**Comment by kevinhu** [comment]
@gregnr I'm using the Apple and Google OAuth providers. I can give `AsyncStorage` a try, but are there any security concerns over using `SecureStorage`?

**Comment by daniel-xyz** [comment]
Just wanted to add that I encountered the size limit as well while just using apple or mail sign-in (can't remember) - anyway, I ran into this size limit issue without any custom metadata.

**Comment by stoickeyboard** [comment]
Hi @kangmingtay any update on this? I prefer to store login info securely :). Thanks @danbovey for the workaround. I'll give it a shot 🙏🏽

**Comment by hf** [comment]
I will update the docs to include a suggestion if you're required or wish to use SecureStorage. It would require adding a crypto library to React Native / Expo, though.

**Comment by hf** [comment]
Need some help in reviewing this as I'm not able to spin up an Expo project right now. https://github.com/supabase/supabase/pull/17643

**Comment by thorwebdev** [comment]
We've clarified SecureStore usage and outlined an option for encrypting the session data here: https://supabase.com/docs/guides/getting-started/tutorials/with-expo?auth-store=secure-store#initialize-a-react-native-app
