### ISSUE TITLE
 Failed to upload 灯泡.jpeg: The object name contains invalid characters

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#14524]
Failed to upload 灯泡.jpeg: The object name contains invalid characters

**Comment by saltcod** [comment]
Hey @jijkbird sorry you're running into this. I assume you're uploading to a storage folder or somewhere else?

**Comment by GaryAustin1** [comment]
https://github.com/supabase/storage-api/issues/133#issuecomment-1098845258
Only a subset of s3 valid characters for names are allowed.
