### ISSUE TITLE
There are no issues with file upload and download, but there are issues with previewing and obtaining links

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#14525]
There are no issues with file upload and download, but there are issues with previewing and obtaining links
![WX20230523-112010](https://github.com/supabase/supabase/assets/20245625/687a2087-0e6c-4f3f-99ea-4b9595ecd5cd)

**Comment by supermar1010** [comment]
I have the same issue.
In the docker-compose.yml I noticed this line.`SUPABASE_URL: http://kong:8000` 
The issue seems to be that this url is also used for calls in the frontend instead of the `SUPABASE_PUBLIC_URL`.

**Comment by socramm9** [comment]
What is your Supabase version? I hade the same issue. This should be fixed in newer versions. 

https://github.com/supabase/cli/issues/1079

**Comment by MildTomato** [comment]
Going to go ahead and close this as the [above answer seems to resolve this](https://github.com/supabase/supabase/issues/14525#issuecomment-1571925109)
