### ISSUE TITLE
impossible to use the operator <=> for vector with a selfhosted supabase with docker

### ISSUE THREAD

**Issue by balasta75** [supabase/supabase#14560]
Hi,

I host myself supabase with docker and for postgres, i use supabase/postgres:15.1.0.84
I'm able to add the extension vector and add vector data on table.
But when i want to use a rpc with the operator <=>, i have this error :

{
code: '42883',
details: null,
hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
message: 'operator does not exist: extensions.vector <=> extensions.vector'
}

and on SQL editor, when i try to install pg_vector with command :
"create extension pg_vector with schema extensions;"

I have this error : "extension "pg_vector" is not available"

my rpc work on online supabase.

Someone can help me ?

Thanks

**Comment by kiwicopple** [comment]
in case anyone wants to help with this, the solution is to update this one to the latest version:

https://github.com/supabase/supabase/blob/1dfee2b2d57850695e531dd3ae3087580fa4da02/docker/docker-compose.yml#LL267C43-L267C43

**Comment by balasta75** [comment]
It doesn't work for me, i download supabase project 2 days ago and already have this version of the docker-compose file.

**Comment by gregnr** [comment]
Hey @balasta75, within Postgres the extension is just called `vector` (not `pg_vector`). Can you try this:

```sql
create extension vector with schema extensions;
```

**Comment by balasta75** [comment]
I found the problem. 
i have to deactivate vector extension and reactive it on public schema. 

Thanks
