### ISSUE TITLE
Add explanation of what triggers updates to `Stream`

### ISSUE THREAD

**Issue by caseycrogers** [supabase/supabase#14579]
# Improve documentation

## Link 

[https://supabase.com/docs/reference/dart/stream](https://supabase.com/docs/reference/dart/stream)

## Describe the problem

Nowhere does it explain how Supabase determines whether or not a change to a table will issue an update.

Most importantly, `primaryKeys` is entirely undocumented. What does it mean to specify `primaryKeys`?

Also, what is the difference between listening to database changes and subscribing to a channel???

## Describe the improvement

Explain what updates to the underlying data will trigger events. Explain what `primaryKeys` does in context.

## Additional context

Discord thread where I'm confused and trying to work through how to use stream:
https://discord.com/channels/839993398554656828/1110762400812105858/1110762400812105858

**Comment by Vinzent03** [comment]
Every update/insert call to a row you are listening to issues a realtime event. The raw channel method from the realtime package emits these realtime events via callbacks. The stream method build on top of it, by keeping the state of an initial postgrest call and updating that state according to realtime events. The stream method has to know which row in its state to update, so we need the columns of the primary key to properly identify it. All other rows could change or could be the same across multiple rows.


> what is the difference between listening to database changes and subscribing to a channel?

What exactly do you mean? Under channel I guess you mean this api:
```dart
supabase.channel('*').on(...).subscribe(...);
```
but what do you mean with listening to database changes exactly?

**Comment by caseycrogers** [comment]
Sorry I'm getting back to this right as you closed it. 

>> what is the difference between listening to database changes and subscribing to a channel?
>
> What exactly do you mean? Under channel I guess you mean this api:

@Vinzent03 I was just quoting the docs word for word. They pose a dichotomy: "listen to database changes" or "subscribe to channel". From talking to you guys here and on Discord, my current understanding is that the `stream` API is just a convenience wrapper on top of channels that issues a one-time request to get the current value and then issues a realtime request to get future changes in the value. If so, shouldn't that be in the docs?

> The stream method has to know which row in its state to update, so we need the columns of the primary key to properly identify it. All other rows could change or could be the same across multiple rows.

Okay I think I understand. It's to disambiguate between a given row being modified vs that row having been deleted and a new row being inserted? 

@dshukertjr Thanks a lot! What do you think about also putting explanations about the above two points in the web docs as well? This also feels like stuff that should be in the dart docs in the source code as well?
