### ISSUE TITLE
Hacktoberfest Prep

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#146]
Long running issue to plan and ideate for Hacktoberfest: https://hacktoberfest.digitalocean.com

## What

Hacktoberfest encourages participation in the open source community, which grows bigger every year. Supabase wants to make it easy for the community to get involved and get rewarded for the contributions.

## Initial tasks

- [x] Create `.github` repo for our org, which can house all the key templates/docs: https://github.com/supabase/.github
- [x] Add issue templates. Good examples: https://github.com/stripe-samples/.github | https://github.com/stripe/stripe-firebase-extensions/issues/new/choose
- [x] Add contributing.md 
- [x] Add Code of conduct
- [x] Create Hacktoberfest label

## Potential Ideas

- Contribute examples repos -> frontend and backend repos, built with Supabase
- Add some tasks for Designers -> logos, icons, branding guidelines?
- Create a swag store. We could use github login to determine free swag for contributors (inspiration: [Gatsby Store](https://store.gatsbyjs.org/), [DEV store](https://shop.dev.to/collections/2018-new-merch))

## Next steps

Any other ideas how we can make it easy for contributors to dive in?

**Comment by thorwebdev** [comment]
## More tasks

- [ ] Submit our Hacktoberfest meetup to https://hacktoberfest.digitalocean.com/events (done, waiting on approval from MLH)
- [ ] Create HF project board and add issues from brainstorming session
- [ ] Create blogpost to explain HF and our involvement

**Comment by kiwicopple** [comment]
Marking this as closed! All tasks done, we just need to blast it out @thorwebdev . Maybe tonight?
