### ISSUE TITLE
Auth setup using Google isn't working for non-web clients

### ISSUE THREAD

**Issue by Andrewngabriel** [supabase/supabase#14605]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to set up Supabase auth to use Google as one of the authentication providers. However, I was disappointed to find out that I needed to have my own web server implementation to handle the Google callback and then deep-link back into the app on my own. The whole point of using Supabase for authentication is that it should handle that for me. Similar to Firebase.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

The expected behavior is to be able to authenticate directly within the app either by launching a web view or native view overlay to handle the authentication without needing to implement a server endpoint to handle callbacks from Google and deep-link the user back into the app. Firebase's SDK allows you to do this without the need to set up a back-end server for handling callbacks. Same should apply here for non-web clients such as Flutter, React Native, etc.

## System information

- OS: macOS

**Comment by Vinzent03** [comment]
A custom server shouldn't be necessary. Please try again with native Google sign in available now. https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter#native-google-sign-in
