### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by bobmolgui** [supabase/supabase#14614]
## Describe the bug

When visiting the following [link](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#authentication) and clicking on **_supabase-js authentication strategies_**, you are redirected to http://localhost:3001/docs/reference/javascript/auth-api.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/auth/auth-helpers/nextjs#authentication
2. Click on supabase-js authentication strategies
3. See error

## Expected behavior

Normally, you should not be redirected to localhost in this case.

## Screenshots
<img width="1265" alt="Screenshot 2023-05-26 at 16 36 24" src="https://github.com/supabase/supabase/assets/2773063/f3905a1a-efc6-4178-95ae-727659a8a51e">

## System information

- OS: macOS
- Browser: chrome, safari, firefox, brave

**Comment by Aashish-Upadhyay-101** [comment]
Hey, I want to work on this issue !

**Comment by gregnr** [comment]
Closed via #14618
