### ISSUE TITLE
createSignedUploadUrl - The parent resource is not found on selfhosted

### ISSUE THREAD

**Issue by craftycatz** [supabase/supabase#14621]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Creating a pre signed url for storage bucket fails on selfhosted 
When trying to create a pre signed url like this:
```js
const { data: url, error } = await supabase.storage
      .from("test")
      .createSignedUploadUrl("test.jpg")
```

either on back- or frontend it fails with status of `404 The parent resource is not found`.
The logs for supabase-storage display the following:
```js
{
    "level": "info",
    "time": "2023-05-26T16:27:59.055Z",
    "pid": 18,
    "hostname": "86d56526f041",
    "reqId": "req-2e",
    "tenantId": "stub",
    "project": "stub",
    "req": {
        "method": "POST",
        "url": "/object/upload/sign/test/test.jpg",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_real_ip": "172.18.0.1",
            "content_length": "2",
            "x_client_info": "@supabase/auth-helpers-nextjs@0.6.1",
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "content_type": "application/json",
            "accept": "*/*",
            "referer": "http://localhost:3000/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "172.18.0.5",
        "remotePort": 42394
    },
    "res": {
        "statusCode": 400
    },
    "responseTime": 17.081000000005588,
    "error": {
        "status": 409,
        "postgresError": {
            "code": "23503",
            "details": "Key is not present in table \"buckets\".",
            "hint": null,
            "message": "<EUGPSCoordinates>insert or update on table \"objects\" violates foreign key constraint \"objects_bucketId_fkey\""
        },
        <EUGPSCoordinates>"metadata":{
            <EUGPSCoordinates>"bucketId":"upload",<EUGPSCoordinates>"name":"sign/test/test.jpg"
        }
    },
    <EUGPSCoordinates>"msg":"POST | 400 | 172.18.0.5 | req-2e | /object/upload/sign/test/test.jpg | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
}
```

this
```xml
 <EUGPSCoordinates>"metadata":{
            <EUGPSCoordinates>"bucketId":"upload",<EUGPSCoordinates>"name":"sign/test/test.jpg"
        }
```

 seems to be the culprit, creating a bucket called upload and trying the same thing yields the following `200` response:

```js
{"Key":"upload/sign/test/test.jpg"}
```

## To Reproduce

1. Follow the self-hosting guide with docker
2. docker-compose up
3. navigate to studio 
4. create a bucket named test
5. set the correct storage policies
6. try to get get a pre signed url form nextjs as per the supabase docs.

## Expected behavior

It should return a correct pre signed url for the requested bucket.

## Screenshots

<img width="1368" alt="image" src="https://github.com/supabase/supabase/assets/89729786/c2a1cbe4-2997-400e-8c5b-0ab861838151">

<img width="1141" alt="image" src="https://github.com/supabase/supabase/assets/89729786/7499954b-6568-40db-b303-5659168fd1f5">

## System information

- OS: MacOS Ventura 13.3.1
- Browser: Chrome
- Version of supabase-js: 2.20.0
- Version of Nextjs: 13.3.0

**Comment by ivasilov** [comment]
Should be fixed by https://github.com/supabase/supabase/pull/17587. 

Edit the `docker-compose.yml` and update to the latest docker image which should be out next Tuesday, you can check [here](https://hub.docker.com/r/supabase/studio/tags).

Please reopen and ping me if the issue still persists.
