### ISSUE TITLE
What about self-hosting?

### ISSUE THREAD

**Issue by ImaCrea** [supabase/supabase#1465]
Hello and thank you for this promising project!

Do you consider facilitating also the self-hosting side of this solution please?

It seems crucial as one aspect that refrain more and more people about using firebase is gaining back control over their data. Hosting it on another tier provider, even though based on open source components, seems to be half of the way.

Woud love to know your plans on that side :)

Thanks!

**Comment by kiwicopple** [comment]
Thanks for dropping in @ImaCrea ! Check this out 😎 https://supabase.io/docs/guides/self-hosting
