### ISSUE TITLE
Allow user data to be saved on signUp

### ISSUE THREAD

**Issue by Saunved** [supabase/supabase#1469]
# Feature request

## Is your feature request related to a problem? Please describe.
When creating users in Supabase, it should be possible to send the user's other info too. Currently, only email and password are accepted.

## Describe the solution you'd like

A possible solution would be to allow this:
```js
const { user, session, error } = await supabase.auth.signUp({
  email: 'example@email.com',
  password: 'example-password',
  data: { name: 'John Doe' }
})
```

## Describe alternatives you've considered

* A possible solution to this is to save the user's info in localStorage and propagate it in an "update" call once the user logs in. There are various issues with this approach, right from knowing whether this is the user's "first-ever login" to relying on the assumption that the user will confirm their email on the same device
* Another approach is to store this data in a Supabase table by associating the user ID with it, but this is unnecessary duplication
* This Github issue https://github.com/supabase/supabase/issues/681 is closed and suggests using a service key on the server-side to take care of this issue, which seems a bit overkill again to me for such a simple task.

## Additional context
None

I am really impressed by Supabase so far and excited about the upcoming developments!

**Comment by Saunved** [comment]
@gomflo Yes, this is what I ended up doing. However, it would be really nice if Supabase could handle this use case within the registration flow itself :v:

**Comment by kylemod** [comment]
> The actual recommendation is to create a `public.users` table.
> 
> https://supabase.io/docs/guides/auth#create-a-publicusers-table

Is there any example on how to execute this codes? Or on how to do it in js?

**Comment by kiwicopple** [comment]
We have created a simple guide here: https://supabase.io/docs/guides/with-react

It should be even easier than the recommendation from your link, because there are no triggers. The pattern we are suggesting now:

- store user data in the `public` schema (for example, using a table called `profiles`
- you don't need to insert a row for every user, so there is no need for the trigger
- you can restrict the table to allow only 1 row per user

For example:

```
create table profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  name text,

  primary key (id)
);
``` 

I'll update the recommendation in your link in the next few days

**Comment by james0r** [comment]
Seems to be a lot of people running into this pain point.

**Comment by kiwicopple** [comment]
we have docs for this one here: https://supabase.com/docs/guides/auth/managing-user-data
