### ISSUE TITLE
Client & server side method for validating user auth token

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#147]
**I'm submitting a ...**
- feature request

**Summary**
It would be great to be able to validate that a user is currently authenticated and for example has a specific role (admin) etc.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

This is how Firebase handles this:
- server admin SDK: https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients
- client web SK: https://firebase.google.com/docs/auth/admin/verify-id-tokens#web

Here an example how that is being used with Next.js: https://github.com/vercel/next.js/blob/canary/examples/with-firebase-authentication/pages/api/getFood.js#L8

**Comment by kiwicopple** [comment]
Let me know if I have this one correct - based on the next.js [example](https://github.com/vercel/next.js/blob/canary/examples/with-firebase-authentication/pages/api/getFood.js#L8) the scenario would be:

1. grab the current cookie (either from the browser or the `req`)
2. send to GoTrue
3. GoTrue needs to validate that the JWT is still valid
4. If it is valid, give back the user data (including UID)

@awalias it looks like this could already be solved by `supabase.auth.user()` right? 
https://github.com/supabase/supabase-js/blob/108579d064179043dbee0199aa2ddb4e4cb8e567/src/Auth.js#L104

Assuming that is true: 

- We would need to do something to pull the cookie out of the `req` (?).
- We may need to add a `forceRefresh` param to bypass the `this.currentUser` check (consistent with Firebase)

**Comment by thorwebdev** [comment]
@kiwicopple the workflow I'd want to do is:

1. client: get current authenticated user token
2. client: send request to backend with user token
3. server: validate the user token and get their uid (now I know that they are correctly authenticated)
4. server: update their customer details in Stripe or other action we only want to perform for authenticated users.

**Comment by phamhieu** [comment]
Supabase-js does exactly like your workflow @thorsten-stripe with this method `supabase.auth.user()`

We should expose auth api on the docs https://supabase.io/docs/library/user-management. Right now, User Management docs seems magical and limited with only supabase-js how-to.

**Comment by thorwebdev** [comment]
Thanks @phamhieu, yes, we'll need to document the server-side side of things. And potentially should think about "admin" auth methods that can be used in a server context, because `supabase.auth.user()` relies on the client-side cookies/localStorage, right?

**Comment by phamhieu** [comment]
`because supabase.auth.user() relies on the client-side cookies/localStorage, right?`
--> yes, you're right

supabase gotrue api endpoint is at `{SUPABASE_UR}/auth/v1`. While waiting for Supabase document to be updated, you can try https://github.com/netlify/gotrue

**Comment by thorwebdev** [comment]
Quick papertrail update from yesterday:

This issue relates to: https://github.com/supabase/supabase-js/issues/20

We've made the decision to allow passing of the JWT to the `user` method which will allow validating and retrieving a user server-side based on a JWT sent from the client:

```js
const response = await supabase.auth.user({ jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xxx" })
```
success response:
```
{
  "error": null,
  "user": {
    "id": "25a3ef18-fe11-483a-ab89-60936b95a3eb",
    "aud": "authenticated",
    "role": "authenticated",
    "email": "testr@test.de",
    "confirmed_at": "2020-09-05T08:54:29.881642986Z",
    "last_sign_in_at": "2020-09-05T08:54:29.887012586Z",
    "app_metadata": {
      "provider": "email"
    },
    "user_metadata": null,
    "created_at": "2020-09-05T08:54:29.877021Z",
    "updated_at": "2020-09-05T08:54:29.88178Z"
  }
}
```
error response:
```
{
  "error": {
    "code": 400,
    "message": "Could not read User ID claim"
  },
  "user": null
}
```

@kiwicopple can you link the forked "gotrue-js" spec once ready?

This also relates to the general supabase-js DX change: https://github.com/supabase/supabase-js/issues/32

**Comment by shellscape** [comment]
@thorwebdev @kiwicopple what happened to the function signature shown here? https://github.com/supabase/supabase/issues/147#issuecomment-687579946 #50 doesn't appear to add that signature and I can't find a blame trail for when that was added. We're in need of validating a JWT serverside and I'm not coming up with any other options.
