### ISSUE TITLE
Status Site dropdown background-color is same as text

### ISSUE THREAD

**Issue by vaibhav111tandon** [supabase/supabase#1471]
# Bug report

## Describe the bug

Status Site dropdown background-color is same as the color of the text

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1:Go to page https://status.supabase.io/uptime
2:Click the dropdown.
3:List in the dropdown has same color as its background due to which it is not visible.

## Expected behavior
Dropdown list should be visible

## Screenshots

![chrome-capture](https://user-images.githubusercontent.com/32813114/117454930-45f1d880-af64-11eb-9113-36dc3b7d642c.gif)

## System information

- OS: Windows
- Browser (if applies): chrome

**Comment by MildTomato** [comment]
I don't think statuspage works very well in a 'dark mode', and if I remember right there isn't much custom CSS that can be added - might be better if we just revert this back to a normal white background and we won't get the odd issues like this.

**Comment by vaibhav111tandon** [comment]
@MildTomato do we have access to this page code? I haven't found any related to this.

**Comment by MildTomato** [comment]
No it's just a supabase admin account on statuspage.io
just reverted it to a light mode, seemed to have fixed it now 👍
