### ISSUE TITLE
tus: unexpected response while creating upload, originated from request, The parent resource is not found

### ISSUE THREAD

**Issue by PiXeL16** [supabase/supabase#14754]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am playing with resumable uploads, TUS and UPPY. My code was working pretty OK one or two days ago, but today every upload request is failing with:

"tus: unexpected response while creating upload, originated from request (method: POST, url: https://**projectid**.supabase.co/storage/v1/upload/resumable, response code: 404, response text: The parent resource is not found, request id: n/a)"

Was just wondering if someone is experience the same, or if the endpoint changed lately.

**Comment by PiXeL16** [comment]
This had to do with Access Policies and the way they were setup in the object table. The parent resource is not found message is super misleading.

**Comment by avlok** [comment]
@PiXeL16 - how did you fix this?

**Comment by rares-lupascu** [comment]
+1 same issue

**Comment by avlok** [comment]
I reached out to support and they mentioned that they haven't rolled it out to everyone yet. They enabled access for my account and it worked.

**Comment by PiXeL16** [comment]
As I described, my issue was related to access policies. Meaning that I had data constrains that were not satisfied when attemting to insert something in the Storage Tables. If you are using resumable upload, the feature is still in beta, so you need to reach out to support for it.

**Comment by m3hari** [comment]
This is quite annoying. So resumable upload is still in beta, and to enable it to contact support (based on this thread), and to reach support, you must be on a paid plan. So basically, resumable upload is paid. 

At least make the error code/message descriptive. I wasted my time debugging `404`

**Comment by jonathanlal** [comment]
hmmm is it still not rolled out to everyone? Implementing it now and if it's a paid feature or not available yet then will have to do it another way...

**Comment by wkuye** [comment]
hello , i'm self hosting and i keep getting this error :Failed to upload 300(10).pdf: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8000/storage/v1/upload/resumable, response code: 500, response text: Something went wrong with that request The file system does not support extended attributes or has the feature disabled. , request id: n/a)

**Comment by Leo-WL** [comment]
same problem here while self-hosting supabase
Failed to upload robot.jpeg: tus: failed to create upload, caused by [object ProgressEvent], originated from request (method: POST, url: http://localhost:8000/storage/v1/upload/resumable, response code: n/a, response text: n/a, request id: n/a)

**Comment by DavidNR21** [comment]
This problem appeared with self-hosting  tus: failed to create upload, caused by [object ProgressEvent], originated from request (method: POST, url: http://localhost:8000/storage/v1/upload/resumable, response code: n/a, response text: n/a, request id: n/a)
