### ISSUE TITLE
React native with expo, oAuth redirect is broken

### ISSUE THREAD

**Issue by Johnrobmiller** [supabase/supabase#14769]
In short, I'm using React Native with Expo. I'm trying to sign in via google. Redirect simply does not happen. When I click the sign in button, I see a seeminly successful sign in with a provider and URL returned by supabase. However, I was never redirected to a google page that allowed me to choose a google account to sign in with.

I followed all the steps, including creating a google cloud oAuth client, providing all the right keys and URLs to google and supabase, and I followed this guide. https://supabase.com/docs/guides/getting-started/tutorials/with-expo

I did a search, and didn't find any issues that were a duplicate of this.

**Comment by Johnrobmiller** [comment]
So, this is definitely not a bug, it's just difficult to do.

A short term solution could be to update docs or write a blog article explaining how to do it. A long term solution might be to build a whole new feature to streamline it.

**Comment by Johnrobmiller** [comment]
Here is the solution for any poor soul that got stuck on this like I did.

When you sign-in with oAuth, you might be using a block of code like this:
```
const { error, data } = await supabase.auth.signInWithOAuth({
      provider: 'google',
    })
```
The `data` variable contains a `data.url`.

You need to open a WebBrowser using `data.url`.

Here are the docs that instruct you on how to do this: https://docs.expo.dev/versions/latest/sdk/webbrowser/

**Comment by Johnrobmiller** [comment]
Once you go through the steps above, `auth.getUser()` and `auth.getSession()` are broken and return null always regardless of any timing or context.

This might actually be a bug, I don't know. There's no documentation about this so it's hard to know

**Comment by Johnrobmiller** [comment]
The session token is not being stored following this guide https://supabase.com/docs/guides/getting-started/tutorials/with-expo

I tried switching to AsyncStorage, but that made no difference. I checked the redirect URI, no problems there.

It is impossible to debug why the session storage is not being stored because the error is happening in a library I have no access to.

I spent approximately four hours trying to debug this because I want to continue using supabase, but I could not solve this. I will admit to feeling angry and sad because that article deceived me into thinking Supabase was a good backend solution for React Native, but in reality, it has a tons of issues and it simply not ready yet.

**Comment by twang905** [comment]
+1

**Comment by hevar** [comment]
The docs regarding RN (expo) feels so lackluster, keep seeing posts/comments from developers (including myself) that find it rather frustrating to implement oauth. Something that one would think should be rather trivial.

Please add an example where oauth is implemented with some providers.

**Comment by BennetLeff** [comment]
Hi I'm having the same issue. In my Supabase dashboard I can view I've 'logged in' in the last minute but the session isn't updated on mobile. With this code:

```
const [req, _res, promptAsync] = Google.useAuthRequest({
    expoClientId: '',
    iosClientId: '***.apps.googleusercontent.com',
    androidClientId: '***.apps.googleusercontent.com',
    redirectUri: AuthSession.makeRedirectUri({
      scheme: 'com.***',
    }),
  });

  const handleGoogleSignIn = () => {
    promptAsync({
      url: `${SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${req?.redirectUri}`,
    })
      .then(async (res) => {
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: 'google',
        });

        console.log(res.authentication.accessToken);
        console.log(res.authentication.refreshToken);
      })
      .catch((error) => {
        console.log(`====== error: ${error} ===== `);
      })
      .finally(() => {
        WebBrowser.maybeCompleteAuthSession();
      });
  };
```

I get an accessToken and a refreshToken console logged as well. So it seems like supabase is making all the right connections with google. Just that the session isn't stored/updated. Fwiw I followed the expo tutorial in the supabase docs and the email + password login works fine. So something about signInWithOAuth isn't storing the session. Here's my supabase client def:

```
const SUPABASE_URL = '***';
const SUPABASE_ANON_KEY ='***'

import 'react-native-url-polyfill/auto';
import * as SecureStore from 'expo-secure-store';
import { createClient } from '@supabase/supabase-js';

const ExpoSecureStoreAdapter = {
  getItem: (key) => {
    return SecureStore.getItemAsync(key);
  },
  setItem: (key, value) => {
    SecureStore.setItemAsync(key, value);
  },
  removeItem: (key) => {
    SecureStore.deleteItemAsync(key);
  },
};

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: ExpoSecureStoreAdapter,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});

export default supabase;

```

**Comment by BennetLeff** [comment]
I don't have time to make a PR atm but I just got this working. The solution is simple, call `setSession`
```
const handleGoogleSignIn = () => {
    promptAsync({
      url: `${SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${req?.redirectUri}`,
    })
      .then(async (res) => {
        await supabase.auth.signInWithOAuth({
          provider: 'google',
        });

        const access_token = res.authentication.accessToken;
        const refresh_token = res.authentication.refreshToken;

        const { data, error } = await supabase.auth.setSession({
          access_token,
          refresh_token,
        });

        console.log(data, error);
      })
      .catch((error) => {
        console.log(`====== error: ${error} ===== `);
      })
      .finally(() => {
        WebBrowser.maybeCompleteAuthSession();
      });
  };
```

Feel free to respond if you need more context on my solution.

**Comment by john-sungjin** [comment]
Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:

1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`

2. Set your Authentication URL Configuration. This was the biggest issue I was stuck on - the Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.

3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:

```typescript
// import * as WebBrowser from 'expo-web-browser'
// const SUPABASE_URL = your-url
const handleGoogleSignIn = async () => {
    try {
      // whatever route you want to deeplink to; make sure to configure in dashboard
      const redirectUri = "your-scheme://login"; 
      const provider = "google";
      const response = await WebBrowser.openAuthSessionAsync(
        `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
        redirectUri
      );

      if (response.type === "success") {
        const url = response.url;
        const params = url.split("#")[1];
        const accessToken = params.split("&")[0].split("=")[1];
        const refreshToken = params.split("&")[2].split("=")[1];

        const { data, error } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken
        });
        if (error) {
          // handle error
        }
      }
    } catch (error) {
      // handle error
    } finally {
      WebBrowser.maybeCompleteAuthSession();
    }
  };
```
Not sure if this is recommended - pretty new to Expo - but it seems to work.

**Comment by twang905** [comment]
> Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:
> 
> 1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`
> 2. Set your Authentication URL Configuration. The Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.
> 3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:
> 
> ```ts
> // import * as WebBrowser from 'expo-web-browser'
> // const SUPABASE_URL = your-url
> const handleGoogleSignIn = async () => {
>     try {
>       // whatever route you want to deeplink to; make sure to configure in dashboard
>       const redirectUri = "your-scheme://login"; 
>       const provider = "google";
>       const response = await WebBrowser.openAuthSessionAsync(
>         `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
>         redirectUri
>       );
> 
>       if (response.type === "success") {
>         const url = response.url;
>         const params = url.split("#")[1];
>         const accessToken = params.split("&")[0].split("=")[1];
>         const refreshToken = params.split("&")[2].split("=")[1];
> 
>         const { data, error } = await supabase.auth.setSession({
>           access_token: accessToken,
>           refresh_token: refreshToken
>         });
>         if (error) {
>           // handle error
>         }
>       }
>     } catch (error) {
>       // handle error
>     } finally {
>       WebBrowser.maybeCompleteAuthSession();
>     }
>   };
> ```
> 
> Not sure if this is recommended - pretty new to Expo - but it seems to work.

This works like a charm for facebook and google. Having a bit of trouble for apple though because it isn't done through the browser

**Comment by kevinhu** [comment]
@twang905 we got Apple OAuth working on iOS using this quick example: https://github.com/supabase-community/create-t3-turbo/blob/main/apps/expo/src/utils/auth.ts

**Comment by twang905** [comment]
> ```ts
> se.auth.setSession({
>           access_token: accessToken,
> ```

Thanks for this - Getting stuck on the part where we use the apple credential to set a supabase auth session though. Do you have any pointers for this?

**Comment by twang905** [comment]
> @twang905 we got Apple OAuth working on iOS using this quick example: https://github.com/supabase-community/create-t3-turbo/blob/main/apps/expo/src/utils/auth.ts

This works great! Thank you so much 🎉

**Comment by Vladimir-Ciuculescu** [comment]
> Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:
> 
> 1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`
> 2. Set your Authentication URL Configuration. The Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.
> 3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:
> 
> ```ts
> // import * as WebBrowser from 'expo-web-browser'
> // const SUPABASE_URL = your-url
> const handleGoogleSignIn = async () => {
>     try {
>       // whatever route you want to deeplink to; make sure to configure in dashboard
>       const redirectUri = "your-scheme://login"; 
>       const provider = "google";
>       const response = await WebBrowser.openAuthSessionAsync(
>         `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
>         redirectUri
>       );
> 
>       if (response.type === "success") {
>         const url = response.url;
>         const params = url.split("#")[1];
>         const accessToken = params.split("&")[0].split("=")[1];
>         const refreshToken = params.split("&")[2].split("=")[1];
> 
>         const { data, error } = await supabase.auth.setSession({
>           access_token: accessToken,
>           refresh_token: refreshToken
>         });
>         if (error) {
>           // handle error
>         }
>       }
>     } catch (error) {
>       // handle error
>     } finally {
>       WebBrowser.maybeCompleteAuthSession();
>     }
>   };
> ```
> 
> Not sure if this is recommended - pretty new to Expo - but it seems to work.

Could you explain what exactly is the scheme ?

**Comment by kishansripada** [comment]
> Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:
> 
> 1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`
> 2. Set your Authentication URL Configuration. The Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.
> 3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:
> 
> ```ts
> // import * as WebBrowser from 'expo-web-browser'
> // const SUPABASE_URL = your-url
> const handleGoogleSignIn = async () => {
>     try {
>       // whatever route you want to deeplink to; make sure to configure in dashboard
>       const redirectUri = "your-scheme://login"; 
>       const provider = "google";
>       const response = await WebBrowser.openAuthSessionAsync(
>         `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
>         redirectUri
>       );
> 
>       if (response.type === "success") {
>         const url = response.url;
>         const params = url.split("#")[1];
>         const accessToken = params.split("&")[0].split("=")[1];
>         const refreshToken = params.split("&")[2].split("=")[1];
> 
>         const { data, error } = await supabase.auth.setSession({
>           access_token: accessToken,
>           refresh_token: refreshToken
>         });
>         if (error) {
>           // handle error
>         }
>       }
>     } catch (error) {
>       // handle error
>     } finally {
>       WebBrowser.maybeCompleteAuthSession();
>     }
>   };
> ```
> 
> Not sure if this is recommended - pretty new to Expo - but it seems to work.

How would this work in dev. my issue is that everytime I spin up a new dev server, the redirect URL changes, for example right now it is exp://192.168.1.6:19000/--/auth/callback. So i have to keep updating this in my supabase dashboard for me to work on my project in dev. How can i make the redirect url constant in dev. Thanks!

**Comment by MSohailMemon** [comment]
> Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:
> 
> 1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`
> 2. Set your Authentication URL Configuration. The Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.
> 3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:
> 
> ```ts
> // import * as WebBrowser from 'expo-web-browser'
> // const SUPABASE_URL = your-url
> const handleGoogleSignIn = async () => {
>     try {
>       // whatever route you want to deeplink to; make sure to configure in dashboard
>       const redirectUri = "your-scheme://login"; 
>       const provider = "google";
>       const response = await WebBrowser.openAuthSessionAsync(
>         `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
>         redirectUri
>       );
> 
>       if (response.type === "success") {
>         const url = response.url;
>         const params = url.split("#")[1];
>         const accessToken = params.split("&")[0].split("=")[1];
>         const refreshToken = params.split("&")[2].split("=")[1];
> 
>         const { data, error } = await supabase.auth.setSession({
>           access_token: accessToken,
>           refresh_token: refreshToken
>         });
>         if (error) {
>           // handle error
>         }
>       }
>     } catch (error) {
>       // handle error
>     } finally {
>       WebBrowser.maybeCompleteAuthSession();
>     }
>   };
> ```
> 
> Not sure if this is recommended - pretty new to Expo - but it seems to work.

Thnks! This solution is working great. Though, there is one problem with this solution. In popup it say, ```<YourAppName> Wants to Use "xxxxxx.subabase.co"```. Is there a way for it to say ```google.com``` instead of supabase.co?

**Comment by gwendall** [comment]
> > Also wanted to add a solution for anyone else who comes across this! Came across a lot of complex solutions while trying to figure this out and wanted something simpler. Only for iOS, but I'm sure Android is similar enough:
> > 
> > 1. Make sure to configure your scheme in `app.json` since we'll need the deeplinking. Deeplink urls will start with `your-scheme://`
> > 2. Set your Authentication URL Configuration. The Supabase authentication route takes a `redirect_to` parameter, but will default to something like `http://localhost:3000` if the input is invalid/not whitelisted. You can find the setting on the Dashboard -> Authentication -> URL Configuration page. Since, after authentication, we want to deeplink back to the app, you can set the redirect url to something like `your-scheme://login`.
> > 3. It turns out the `redirect_to` url gets appended with the access and refresh tokens, so we can parse those out and use them to set the session. Here's the handler that does all of this:
> > 
> > ```ts
> > // import * as WebBrowser from 'expo-web-browser'
> > // const SUPABASE_URL = your-url
> > const handleGoogleSignIn = async () => {
> >     try {
> >       // whatever route you want to deeplink to; make sure to configure in dashboard
> >       const redirectUri = "your-scheme://login"; 
> >       const provider = "google";
> >       const response = await WebBrowser.openAuthSessionAsync(
> >         `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${redirectUri}`,
> >         redirectUri
> >       );
> > 
> >       if (response.type === "success") {
> >         const url = response.url;
> >         const params = url.split("#")[1];
> >         const accessToken = params.split("&")[0].split("=")[1];
> >         const refreshToken = params.split("&")[2].split("=")[1];
> > 
> >         const { data, error } = await supabase.auth.setSession({
> >           access_token: accessToken,
> >           refresh_token: refreshToken
> >         });
> >         if (error) {
> >           // handle error
> >         }
> >       }
> >     } catch (error) {
> >       // handle error
> >     } finally {
> >       WebBrowser.maybeCompleteAuthSession();
> >     }
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if this is recommended - pretty new to Expo - but it seems to work.
> 
> Thnks! This solution is working great. Though, there is one problem with this solution. In popup it say, `<YourAppName> Wants to Use "xxxxxx.subabase.co"`. Is there a way for it to say `google.com` instead of supabase.co?

Use a custom domain: https://supabase.com/docs/guides/platform/custom-domains

**Comment by thorwebdev** [comment]
We now have official documentation for this: 

1. Native Apple / Google sign in: https://supabase.com/docs/guides/auth/native-mobile-login
1. OAuth / Magic link & deep linking: https://supabase.com/docs/guides/auth/native-mobile-deep-linking
