### ISSUE TITLE
Db Trigger and Function stopped working

### ISSUE THREAD

**Issue by mousindev** [supabase/supabase#14786]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We have a Db Function and Trigger that work together to replicate into `public.users` every user that signs up. It suddently stopped working without any change on them, RLSs or anything else.We just deleted them and recreated them again running the specific part of the code from the migrations, and it worked back again (meaning users were created again in `public.users` and receiving the verification email again)

## To Reproduce

Unfortunately we don't know how to reproduce it. We suddenly found it. We wonder if there was any update to Supabase that could have cause this?

## Expected behavior

If due to any update in the platform, to ensure these kind of critical things won't break whenever new versions are released

## Screenshots

n/a

## System information

- OS: [e.g. macOS, Windows]: Windows
- Browser (if applies) [e.g. chrome, safari] Chrome
- Version of supabase-js: [e.g. 6.0.2] 2.2.3
- Version of Node.js: [e.g. 10.10.0]: 18.12.1

## Additional context

n/a

Raising it just in case someone else is facing it or it is caused due to an upgrade and the issue went unnoticed. Thanks, we love Supabase!!

**Comment by gregnr** [comment]
Thanks for reporting @nereolopez and glad you were able to find a work around. Someone from the @supabase/auth team can help debug/confirm this.

**Comment by kangmingtay** [comment]
hi @nereolopez, did you notice any errors in your postgres logs?

**Comment by nereolopez** [comment]
Thanks for coming back to us. Unfortunately I did not, I was on the go and testing from the phone so I just re-run everything from the phone but did not check. As this is not in prod yet I cannot check older logs now :(

**Comment by GaryAustin1** [comment]
Closing this as working and no further info.
Please feel free to comment if it needs to be reopened.
