### ISSUE TITLE
Issue with Types When Querying Data from Multiple Tables

### ISSUE THREAD

**Issue by bkyerv** [supabase/supabase#14798]
encountered an issue where the types are not correctly generated when performing a query that fetches data from more than one table.

Details of the issue
I've used the following query to fetch data from two tables: 'message' and 'conversation':

```
const { data, error } = await supabaseClient.from("message").select('
    id,
    conv_id,
    message,
    conversation:conv_id (
      subject,
      priority
    )
  ');
```

Problem is the type inference does not match the expected result. Specifically, the relationship fields are generated as an array type, even when a single object is expected.

```
{
    id: number;
    conv_id: number;
    message: string;
    conversation: {
        subject: unknown;
        priority: unknown;
    }[];
}[]
```
However, since conv_id implies a single conversation, conversation was expected to be a single object instead of an array and its properties should have types inferred properly:

```
const data: {
    id: number;
    conv_id: number;
    message: string;
    conversation: {
        subject: string;
        priority: string;
    };
}[] | null

```
Proposed solution

The type generation should take into account the relationships between the tables in the query and correctly infer whether the returned objects should be an array or a single object.

Thanks for considering this issue. Please let me know if there's any more information I can provide to help resolve it.

**Comment by gregnr** [comment]
Hey @bkyerv thanks for reporting. I've encountered this myself - I believe this issue is being tracked here:
https://github.com/supabase/postgrest-js/issues/408

Closing this in favour of that - but definitely reopen/let me know if you think they're unrelated!
