### ISSUE TITLE
Dashboard Bug:- Edge function not showing Successful Invocation

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#14837]
I realize the Edge Function dashboard is not showing `metrics` and `invocations` for successful invocations but showing failed invocations. `logs` is working fine.
Below is the screen recording of two different functions.

https://github.com/supabase/supabase/assets/21134455/dc3ab797-daab-49dd-b6ef-b977300abc92

https://github.com/supabase/supabase/assets/21134455/30e691b3-56a1-4e93-8b8b-0b39fbf386a6

**Comment by haszankauna** [comment]
hello @gregnr I'll love to work on this.

**Comment by gregnr** [comment]
@haszankauna thanks for volunteering! This issue may be a bit more involved - I'll let @supabase/frontend chime in here.

**Comment by Ziinc** [comment]
@Akash187 can you contact us via the support email so that we can investigate your project 

https://supabase.com/dashboard/support/new

The stated issue is not reproducible without additional project-specific information. Closing.

**Comment by SkeltalFlamingo** [comment]
I'm having the same issue.

**Comment by RevenueDealerAI** [comment]
<img width="1159" height="731" alt="Image" src="https://github.com/user-attachments/assets/da7ed73f-5d5e-4348-acc7-bf42a068a5ea" />

<img width="475" height="461" alt="Image" src="https://github.com/user-attachments/assets/4338ba4a-801a-4b48-ba94-58f32f9f0d34" />

<img width="492" height="461" alt="Image" src="https://github.com/user-attachments/assets/94c6aed1-95ae-482a-be7f-fb7b7f8b796e" />

<img width="1411" height="778" alt="Image" src="https://github.com/user-attachments/assets/b7b46d87-111a-431d-9c59-b1a11e2c4b43" />

<img width="1146" height="740" alt="Image" src="https://github.com/user-attachments/assets/d7abcd56-41cd-4e30-b490-e605c703c6e4" />

I am facing the same issue with supabase
