### ISSUE TITLE
Website is crashing

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#14839]
I forgot the count of how many times I encountered the error `Application error: a client-side exception has occurred (see the browser console for more information).` Probably have seen the dashboard crashing more than 1000 times in the past weeks.

Below is the screenshot of console.log
<img width="1440" alt="Screenshot 2023-06-06 at 4 11 32 PM" src="https://github.com/supabase/supabase/assets/21134455/a27fb4b5-f78d-4d44-b66b-80896232fa54">

**Comment by saltcod** [comment]
Hey @Akash187 — sorry you're running into this. Could you give us some extra details on where/how this is happening? Which routes, what are some project database size details, etc.

**Comment by Akash187** [comment]
@saltcod I see the dashboard has been working fine for the last few days. It seems people have pushed some changes.

**Comment by MildTomato** [comment]
@Akash187 good to hear! I'm going to go ahead and close this one.

**Comment by invig** [comment]
This is happening for me whenever I try and switch to any schema that is not the public one in the table editor :(
