### ISSUE TITLE
NextJS - Getting Started can't find types

### ISSUE THREAD

**Issue by Deveesh-Shetty** [supabase/supabase#14842]
# Improve documentation
There is no reference given to get the database types in NextJS Getting Started Docs for Typescript

## Link 
[Getting Started - NextJS](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs)

## Describe the problem
I was trying the `Getting Started` guide on NextJS with Typescript and I came across a database type that is not mentioned anywhere in the guide.

![Database types missing](https://github.com/supabase/supabase/assets/89470104/f3110ac4-e7a3-4e2b-be89-bbd78222003e)

 But after some research, I found the page in the docs

## Describe the improvement
To mention in the docs that if you are using TypeScript refer to the link to [generate Database types](https://supabase.com/docs/guides/api/rest/generating-types)

So searching for the types won't be a hassle for new learners.

## Additional context
I want to work on the issue and improve the documentation.

**Comment by Deveesh-Shetty** [comment]
![Note to refer genreate types](https://github.com/supabase/supabase/assets/89470104/4e796388-da00-4cd5-b46e-e9835109fe0c)
Made a commit with this note line is it fine to send a PR?

## It comes after "Add the `AuthForm` component to your home page"
![Where the changes was made](https://github.com/supabase/supabase/assets/89470104/057f1fb8-b6bc-4e75-b5dc-6eac11f4437b)

**Comment by gregnr** [comment]
@Deveesh-Shetty yes please, we would love to review the PR 😃

**Comment by Deveesh-Shetty** [comment]
Created a PR to address the documentation fix

Thanks and Welcome!
