### ISSUE TITLE
Issue with toasts at RLS creation dialog

### ISSUE THREAD

**Issue by f11y11** [supabase/supabase#14872]
# Chore

## Chore description

Toasts in RLS creation dialog have no expiry and if you try to close them manually, the RLS editor is also closed which led me to restart writing my RLS policy countless times. After several toasts, they cover half the page and you can't just ignore them.

**Comment by faizanraso** [comment]
It seems that the error messages have a timeout of 4 seconds, except for when no policy name is provided. Can you confirm which error message you were receiving?

<img width="864" alt="Screenshot 2023-06-07 at 10 53 45 AM" src="https://github.com/supabase/supabase/assets/59986120/2d190312-7932-4d9b-9cf9-14eb27b5ed99">

**Comment by f11y11** [comment]
it is the syntax error messages when you provide an invalid RLS @ https://supabase.com/dashboard/project/.../auth/policies?search=...

**Comment by faizanraso** [comment]
I have been trying to contribute to supabase and I run across the issue that I am unable to access some features when doing so. For example, If I try creating a table in my locally running version I get the error: "An error has occurred: fetch failed". When I check the log it says it's error 400 (POST http://localhost:8082/api/pg-meta/default/tables 400 (Bad Request)).

What am I missing?

**Comment by saltcod** [comment]
Hey @faizanraso — posting in Discord might be the best way to get some eyes on this one.

**Comment by Hallidayo** [comment]
Hi @faizanraso - I've just messaged on your Discord thread as I've had this issue a while back.

**Comment by saltcod** [comment]
Best @Hallidayo thank you!

**Comment by faizanraso** [comment]
I have just submitted a PR that fixes these bugs, once again thanks @Hallidayo for all your help!

**Comment by saltcod** [comment]
Fixed in https://github.com/supabase/supabase/pull/15137
