### ISSUE TITLE
textSearch should return result with specific characters

### ISSUE THREAD

**Issue by indahud** [supabase/supabase#1488]
# Feature request

## Is your feature request related to a problem? Please describe.

`textSearch()` only returns the result if it contains full word. It would be really amazing if it returns all the rows which matches the characters.

For example database contains three rows with fireleet, firetrip, fireclip.
If we use

```JavaScript
.textSearch('name', `'fire'`, {
        type: 'phrase',
        config: 'english'
    })
```
it returns nothing. 

## Describe the solution you'd like
Results should return all the rows containing specific characters.

**Comment by devdev-dev** [comment]
This would be a great feature. Why did you close this Issue @indahud . Did you find another solution?

**Comment by monicakh** [comment]
@indahud Just pushed a PR for this: https://github.com/supabase/supabase/pull/22602
