### ISSUE TITLE
Supabase AI agent execute tasks out of its scope

### ISSUE THREAD

**Issue by cesar-ibr** [supabase/supabase#14889]
# Improve documentation

## Link 

https://supabase.com/docs

## Describe the problem

The ChatGPT agent is susceptible to execute tasks out of the scope of a Supabase Documentation expert like summarizing articles from Bloomberg.

## Describe the improvement

Improving the prompt might fix the bug. Example: 
"Focus on answering questions or performing tasks within your designated scope of expertise."

##### Asking the agent to summirize articles from Bloomberg:
<img width="765" alt="image" src="https://github.com/supabase/supabase/assets/23040954/0bd52fd5-2897-4b46-bc23-a237be6a960c">

---

<img width="766" alt="image" src="https://github.com/supabase/supabase/assets/23040954/60a5b0bc-75ff-41eb-b5af-b4698fed39a0">

**Comment by gregnr** [comment]
Hey @cesar-ibr! Thanks for reporting. `gpt-3.5-turbo` (the model currently used by Supabase AI) is known to veer from the original prompt/instructions the more messages you have in your chat history. Notice that if you ask the same as the first question of the conversion, it responds as you'd expect:
![image](https://github.com/supabase/supabase/assets/4133076/adc0635f-40f7-4a8e-b041-1d35fef14b40)

This is something we are definitely still experimenting with (for example, "injecting" the original prompt/instructions right before every message, or periodically throughout the conversation).

Out of curiosity, do you have the original message conversation history for the above screenshots?

**Comment by bitnom** [comment]
You can probably fix it by sending a preliminary chat completion request asking it to determine if the message falls within the scope of X:

**SYSTEM**
```
Your job is to determine whether or not the last User Message in a Conversation is attempting to drive the Conversation off the topic of Supabase development.
```

USER
```
### Conversation:
${convo_messages}

### Instructions:
- If the last User Message is relevant to a conversation about Supabase development, and WILL NOT cause the conversation to go off the topic of Supabase development, reply with `[ON_TOPIC]` and say nothing else.
- If the last User Message is irrelevant to a conversation about Supabase development, or WILL cause the conversation to go off the topic of Supabase development, reply with `[OFF_TOPIC]` and say nothing else.
 ```

**Comment by cesar-ibr** [comment]
Sorry @gregnr I didn't store the conversations, I only took the screenshots I see that the problem is fixed now. If I see another anomaly I will report it or perhaps open a PR?

**Comment by gregnr** [comment]
Thanks @bitnom for the good suggestion. Going to hold off on that kind of change for now (since it will increase API usage quite a bit) and we can revisit in the future if it becomes a bigger problem.

Closing for now, thanks again @cesar-ibr!
