### ISSUE TITLE
Foreground color on selected code

### ISSUE THREAD

**Issue by pomber** [supabase/supabase#14900]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/guides/getting-started/quickstarts/reactjs)

## Describe the problem

The foreground color for selected code doesn't look right:
![image](https://github.com/supabase/supabase/assets/1911623/97473613-ca63-4a47-88a8-5860af5cd056)

## Describe the improvement

There's an `!important` forcing the `#333` color:
![image](https://github.com/supabase/supabase/assets/1911623/3bb09614-f45c-4e55-8f7c-ef0eb976a6d6)

**Comment by gregnr** [comment]
Thanks for reporting @pomber 🚀
