### ISSUE TITLE
Incorrect types for data when querying foreign tables from js client (supabase-js 2.24)

### ISSUE THREAD

**Issue by benrbowers** [supabase/supabase#14920]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create table with foreign key
2. Gen types
3. Using supabase-js client, query the table and request info from foreign table (in this case `city` is the foreign item):
```
const { data, error } = await supaClient
	.from('profiles_with_activities')
	.select('*, city (google_place_id, formatted_address)')
	.neq('user_id', user.user_id)
	.order('user_id', { ascending: true });
```
4. When hovering over profilesQuery for the return type, the city property has an odd, incorrect type:
```
city: string & {
    google_place_id: string;
    formatted_address: string;
}[]
```
(extra string type, and should NOT be an array)
## Expected behavior

The type for the city property should be the following:
```
city: {
    google_place_id: string;
    formatted_address: string;
}
```
This is the shape of the data that's ACTUALLY RETURNED from the client.

This is creating very annoying type errors in my application that I'm currently working around with very hacky `as` statements.

## System information

- OS: Windows 10
- Version of supabase-js: ^2.24.0
- Version of Node.js: 16.19.0

## Additional context

🙌 Thanks in advance

**Comment by GaryAustin1** [comment]
Duplicate of this?
https://github.com/supabase/postgrest-js/issues/303

**Comment by benrbowers** [comment]
> Duplicate of this? [supabase/postgrest-js#303](https://github.com/supabase/postgrest-js/issues/303)

Ah, I think so. Thanks!
