### ISSUE TITLE
On mobile for the doc site, scrolling up doesn't work once you've scrolled to the bottom

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase#14939]
# Improve documentation

## Link 

https://supabase.com/docs/guides/platform

## Describe the problem

I haven't noticed this on the main site, or even on the /docs root. But if you tap on Platform, for example, and scroll to the bottom, if you try to scroll back up it only tries to do a page refresh. If you do a scroll down motion and release - even though there is no more room to scroll down - scrolling up will work.

## Additional context

Firefox on Android

**Comment by Isaiah-Hamilton** [comment]
@j4w8n do you have a screenshot or screen recording of this issue?

**Comment by j4w8n** [comment]
@Isaiah-Hamilton yes. Was on my mobile when I created the issue and couldn't figure out how to attach it - then forgot aboit it.

**Comment by j4w8n** [comment]
https://github.com/supabase/supabase/assets/25783093/b15feff2-ad05-45c4-8cae-315d37f8aba4

Here is a video

**Comment by rahul0x00** [comment]
@j4w8n Hi, the issue is with the firefox itself, it's very prone to refreshing when trying to scroll to the top of the page

**Comment by j4w8n** [comment]
Guess I should've done some tests on other browsers 🤦‍♂️. Doesn't happen on Chrome or Samsung Internet
