### ISSUE TITLE
Confusing filter-through-join behavior should be clarified

### ISSUE THREAD

**Issue by ankrgyl** [supabase/supabase#14956]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/select

<img width="1315" alt="Screenshot 2023-06-10 at 2 42 01 PM" src="https://github.com/supabase/supabase/assets/565363/cfcb34c1-c386-4977-8159-a08774c19f01">

## Describe the problem

When you join (e.g. `countries(*)`) and then filter (`eq`, `countries.name`, `"Estonia"`), the filter gets placed into the join condition of a `LEFT LATERAL JOIN` by postgrest, which means that rows whose `countries.name` is not `Estonia` will still be returned, but their entire `countries` object will be null. This behavior is not what I think most people expect, and is certainly not what the documentation suggests ("Filtering through foreign tables").

At least one user [got confused by this](https://stackoverflow.com/questions/69137919/filtering-in-join-in-supabase), but generally I struggled to find documentation on this topic.

## Describe the improvement

At the very least, the example should be updated to use `countries!inner(*)` as the join. I would also recommend adding a strong/big disclaimer about this behavior.

## Additional context

I personally find this behavior so confusing, that it might even warrant a compiler warning forcing the user to provide a more explicit syntax (e.g. `countries!left(*)`) if they choose to do a join + filter without specifying the join type.

**Comment by pjhartin** [comment]
I'm extremely confused and stuck for hours trying to filter on an embedded resource via an `!inner` join. Still getting results returned to me where a `not.in` condition is met, but the matching objects are simply null. 

Painful to say the least.

**Comment by ankrgyl** [comment]
@pjhartin what helped me debug this issue was looking at the actual SQL generated from the command (and noticing where the predicate was placed in the left lateral join). Have you tried that?

**Comment by gregnr** [comment]
Great feedback @ankrgyl & @pjhartin. Going to let @supabase/postgrest chime in w.r.t. defaults/warnings around `inner`.

I think we should add an `inner` example regardless (I see we actually do for some languages, but not others). Tracking that task here https://github.com/supabase/supabase/issues/15053.

**Comment by soedirgo** [comment]
I agree that "Filtering through foreign tables" should really mean using `!inner`, and we should update the example. Though I'm not exactly sure why this was in the docs for fetching data instead of using filters.

**Comment by encima** [comment]
Closing as issue was addressed in #15053 and the example referenced has been removed
