### ISSUE TITLE
Docs: pgAdmin connection docs need updating

### ISSUE THREAD

**Issue by gregnr** [supabase/supabase#14992]
# Improve documentation

## Link 

https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-pgadmin

## Describe the problem

Step 4 of **Connecting with pgAdmin** has screenshots that are out of date. Specifically as of pgAdmin 6.20 there is no longer an **SSL** tab:
![image](https://github.com/supabase/supabase/assets/4133076/4409bde6-bb91-48cd-b3cf-fddfc49ca520)

Instead you need to enter that information in **Parameters**:
![image](https://github.com/supabase/supabase/assets/4133076/71f317db-e997-40a7-88e9-907fda0d5cb5)

## Other info
We should update the screenshots in steps 2 & 3 as well to show that the SSL tab is no longer there.

**Comment by sambhavgupta0705** [comment]
So we need to remove SSL tab from the screenshot?

**Comment by gregnr** [comment]
@sambhavgupta0705 that's right! And refer to the correct inputs in the new Parameters tab for step 4

**Comment by gregnr** [comment]
Closed via #15011
