### ISSUE TITLE
Docs: Extension search returns incorrect links

### ISSUE THREAD

**Issue by gregnr** [supabase/supabase#14990]
## Describe the bug

The [extensions search component](https://supabase.com/docs/guides/database/extensions#full-list-of-extensions) in the docs return incorrect links for some of the extensions.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/database/extensions#full-list-of-extensions
2. Type 'cron' in the extension search box
3. Click on the `pg_cron` card
4. See 404 error

## Expected behavior

We expect the links to navigate to valid pages. In the above example, the real page lives on `/pgcron`, not `pg_cron`.

## Additional context

There are a number of other extensions that have the same problem. We're pretty inconsistent with naming (ie. some extensions use snake case, others are all lowercase with no separator).

**At a minimum:** Fix the broken links
**Also consider:** If it is worth bringing some consistency to our extension names. Will need to add redirects in `www` if we decide to rename URL paths.

**Comment by mdjohns** [comment]
I'd like to take this on!

It looks like there are quite a few extensions listed in [`extensions.json`](https://github.com/supabase/supabase/blob/master/apps/docs/data/extensions.json)) that don't have pages in [`/pages/guides/database/extensions`](https://github.com/supabase/supabase/tree/master/apps/docs/pages/guides/database/extensions). 

How should we handle those? Should we only create links for extensions with a `link` property? It looks like the commented-out code [here](https://github.com/supabase/supabase/blob/master/apps/docs/components/Extensions.tsx#L121-L126) took a similar approach.

**Comment by gregnr** [comment]
Hey @mdjohns, sorry for the delay. Working on this behind the scenes with some team members to try to track down which extensions to keep in there and their relevant links. Will keep you posted!

**Comment by gregnr** [comment]
Thanks for your patience! Settling on this list of extensions which now all include a URL:

Name | Description | Proposed Link
-- | -- | --
address_standardizer | Used to parse an address into constituent elements. Generally used to support geocoding address normalization step. | https://postgis.net/docs/manual-2.5/Address_Standardizer.html
address_standardizer_data_us | Address Standardizer US dataset example | https://postgis.net/docs/manual-2.5/Address_Standardizer.html
amcheck | functions for verifying relation integrity | https://www.postgresql.org/docs/current/amcheck.html
autoinc | functions for autoincrementing fields | https://www.postgresql.org/docs/current/contrib-spi.html#id-1.11.7.50.6
bloom | bloom access method - signature file based index | https://www.postgresql.org/docs/current/bloom.html
btree_gin | support for indexing common datatypes in GIN | https://www.postgresql.org/docs/current/btree-gin.html
btree_gist | support for indexing common datatypes in GiST | https://www.postgresql.org/docs/current/btree-gist.html
citext | data type for case-insensitive character strings | https://www.postgresql.org/docs/current/citext.html
cube | data type for multidimensional cubes | https://www.postgresql.org/docs/current/cube.html
dblink | connect to other PostgreSQL databases from within a database | https://www.postgresql.org/docs/current/contrib-dblink-function.html
dict_int | text search dictionary template for integers | https://www.postgresql.org/docs/current/dict-int.html
dict_xsyn | text search dictionary template for extended synonym processing | https://www.postgresql.org/docs/current/dict-xsyn.html
earthdistance | calculate great-circle distances on the surface of the Earth | https://www.postgresql.org/docs/current/earthdistance.html
fuzzystrmatch | determine similarities and distance between strings | https://www.postgresql.org/docs/current/fuzzystrmatch.html
hstore | data type for storing sets of (key, value) pairs | https://www.postgresql.org/docs/current/hstore.html
hypopg | Hypothetical indexes for PostgreSQL | https://supabase.com/docs/guides/database/extensions/hypopg
http | HTTP client for PostgreSQL, allows web page retrieval inside the database. | https://supabase.com/docs/guides/database/extensions/http
insert_username | functions for tracking who changed a table | https://www.postgresql.org/docs/current/contrib-spi.html#id-1.11.7.50.7
old_snapshot | utilities in support of old_snapshot_threshold | https://www.postgresql.org/docs/current/oldsnapshot.html
intarray | functions, operators, and index support for 1-D arrays of integers | https://www.postgresql.org/docs/current/intarray.html
isn | data types for international product numbering standards | https://www.postgresql.org/docs/current/isn.html
lo | Large Object maintenance | https://www.postgresql.org/docs/current/lo.html
ltree | data type for hierarchical tree-like structures | https://www.postgresql.org/docs/current/ltree.html
moddatetime | functions for tracking last modification time | https://www.postgresql.org/docs/current/contrib-spi.html#id-1.11.7.50.8
pg_cron | Job scheduler for PostgreSQL | https://supabase.com/docs/guides/database/extensions/pgcron
pg_freespacemap | examine the free space map (FSM) | https://www.postgresql.org/docs/current/pgfreespacemap.html
pg_graphql | pg_graphql: GraphQL support | https://supabase.com/docs/guides/database/extensions/pg_graphql
pg_hashids | pg_hashids | https://supabase.com/docs/guides/database/extensions/pg_hashids
pg_jsonschema | pg_jsonschema | https://supabase.com/docs/guides/database/extensions/pg_jsonschema
pg_net | Async HTTP | https://supabase.com/docs/guides/database/extensions/pgnet
pg_prewarm | prewarm relation data | https://www.postgresql.org/docs/current/pgprewarm.html
pg_stat_monitor | The pg_stat_monitor is a PostgreSQL Query Performance Monitoring tool, based on PostgreSQL contrib module pg_stat_statements. pg_stat_monitor provides aggregated statistics, client information, plan details including plan, and histogram information. | https://supabase.com/docs/guides/database/extensions/pg_stat_monitor
pg_stat_statements | track execution statistics of all SQL statements executed | https://supabase.com/docs/guides/database/extensions/pg_stat_statements
pg_surgery | extension to perform surgery on a damaged relation | https://www.postgresql.org/docs/current/pgsurgery.html
pg_trgm | text similarity measurement and index searching based on trigrams | https://www.postgresql.org/docs/current/pgtrgm.html
pgaudit | provides auditing functionality | https://supabase.com/docs/guides/database/extensions/pgaudit
pg_walinspect | functions to inspect contents of PostgreSQL Write-Ahead Log | https://www.postgresql.org/docs/current/pgwalinspect.html
pgcrypto | cryptographic functions | https://www.postgresql.org/docs/current/pgcrypto.html
pgjwt | JSON Web Token API for Postgresql | https://supabase.com/docs/guides/database/extensions/pgjwt
pgroonga | Super fast and all languages supported full text search index based on Groonga | https://supabase.com/docs/guides/database/extensions/pgroonga
pgroonga_database | PGroonga database management module | https://pgroonga.github.io/reference/modules/pgroonga-database.html
pgrouting | pgRouting Extension | https://supabase.com/docs/guides/database/extensions/pgrouting
pgrowlocks | show row-level locking information | https://www.postgresql.org/docs/current/pgrowlocks.html
pgsodium | Postgres extension for libsodium functions | https://supabase.com/docs/guides/database/extensions/pgsodium
pgstattuple | show tuple-level statistics | https://www.postgresql.org/docs/current/pgstattuple.html
pgtap | Unit testing for PostgreSQL | https://supabase.com/docs/guides/database/extensions/pgtap
plcoffee | PL/CoffeeScript (v8) trusted procedural language | https://github.com/plv8/plv8/blob/master/doc/plv8.md#coffeescript-extension
pljava | PL/Java procedural language (https://tada.github.io/pljava/) | https://tada.github.io/pljava/
plls | PL/LiveScript (v8) trusted procedural language | https://github.com/plv8/plv8/blob/master/doc/plv8.md#livescript-extension
plpgsql | PL/pgSQL procedural language | https://www.postgresql.org/docs/current/plpgsql.html
plpgsql_check | extended check for plpgsql functions | https://supabase.com/docs/guides/database/extensions/plpgsql_check
plv8 | PL/JavaScript (v8) trusted procedural language | https://supabase.com/docs/guides/database/extensions/plv8
postgis | PostGIS geometry and geography spatial types and functions | https://supabase.com/docs/guides/database/extensions/postgis
postgres_fdw | foreign-data wrapper for remote PostgreSQL servers | https://www.postgresql.org/docs/current/postgres-fdw.html
refint | functions for implementing referential integrity (obsolete) | https://www.postgresql.org/docs/current/contrib-spi.html#id-1.11.7.50.5
rum | GIN-like index for text search | https://supabase.com/docs/guides/database/extensions/rum
seg | data type for representing line segments or floating-point intervals | https://www.postgresql.org/docs/current/seg.html
sslinfo | information about SSL certificates | https://www.postgresql.org/docs/current/sslinfo.html
supautils | Supabase standard library | https://supabase.github.io/supautils/
tablefunc | functions that manipulate whole tables, including crosstab | https://www.postgresql.org/docs/current/tablefunc.html
tcn | Triggered change notifications | https://www.postgresql.org/docs/current/tcn.html
timescaledb | Enables scalable inserts and complex queries for time-series data | https://supabase.com/docs/guides/database/extensions/timescaledb
tsm_system_rows | TABLESAMPLE method which accepts number of rows as a limit | https://www.postgresql.org/docs/current/tsm-system-rows.html
tsm_system_time | TABLESAMPLE method which accepts time in milliseconds as a limit | https://www.postgresql.org/docs/current/tsm-system-time.html
unaccent | text search dictionary that removes accents | https://www.postgresql.org/docs/current/unaccent.html
uuid-ossp | generate universally unique identifiers (UUIDs) | https://supabase.com/docs/guides/database/extensions/uuid-ossp
pgvector | vector data type with similarity search | https://supabase.com/docs/guides/database/extensions/pgvector
pg_repack | Optimize physical storage and remove bloat from tables and indexes | https://supabase.com/docs/guides/database/extensions/pgrepack
wrappers | Foreign data wrappers developed by Supabase | https://supabase.com/docs/guides/database/extensions/wrappers

Particularly this removes these extensions:
- `address_standardizer-3`
- `address_standardizer_data_us-3`
- `adminpack`
- `file_fdw`
- `intagg`
- `pageinspect`
- `pg_buffercache`
- `pg_visibility`
- `postgis-3`
- `postgis_raster`
- `postgis_raster-3`
- `postgis_sfcgal`
- `postgis_sfcgal-3`
- `postgis_tiger_geocoder`
- `postgis_tiger_geocoder-3`
- `postgis_topology`
- `postgis_topology-3`
- `xml2`

**Comment by mdjohns** [comment]
Whoa, thanks for gathering that up @gregnr!

PR is up! :tada:
