### ISSUE TITLE
Add husky lint-staged

### ISSUE THREAD

**Issue by carlosstenzel** [supabase/supabase#1499]
can we use husky lint-staged to force formatting?

**Comment by kiwicopple** [comment]
Hey @carlosstenzel - that sounds awesome. Would it be something you're willing to implement?

**Comment by carlosstenzel** [comment]
https://github.com/supabase/supabase/pull/1659

@kiwicopple  . 

I created an action to format, it was the best solution I found

**Comment by carlosstenzel** [comment]
all push added in brach master, automatically formats

**Comment by carlosstenzel** [comment]
https://github.com/supabase/supabase/pull/1660 test format

**Comment by inian** [comment]
Hey @carlosstenzel, keeping this issue open till the generated files are ignored from prettier.

**Comment by carlosstenzel** [comment]
https://github.com/supabase/supabase/pull/1740
@inian 

I left it for just a few folders. But we can adjust if necessary.

**Comment by inian** [comment]
Looks good @carlosstenzel. Thanks a lot ❤️
