### ISSUE TITLE
Unable to filter ManyToMany RelationShip with id

### ISSUE THREAD

**Issue by lambdina** [supabase/supabase#15082]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I cannot filter a row with its id.
Note that the table in question is in a many to many relationship described in another table.

I :
- [x] Tried to restart the database twice as suggested.
- [x] Manually deleted and re creating the tables.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Here are my tables:
```sql
create table
  public.variants (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    images array null,
    sizes array null,
    nb_stock integer null,
    product bigint null,
    constraint p_variable_pkey primary key (id),
    constraint variants_product_fkey foreign key (product) references products (id)
  ) tablespace pg_default;

create table
  public.products (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    price real null,
    weight real null,
    is_food boolean null default false,
    is_customisable boolean null default true;
    name text null,
    constraint products_pkey primary key (id),
  ) tablespace pg_default;
  
  create table
  public.category (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    name text null,
    description text null,
    images array null,
    parent bigint null,
    constraint category_pkey primary key (id),
    constraint category_parent_fkey foreign key (parent) references category (id)
  ) tablespace pg_default;

create table
  public.categories (
    created_at timestamp with time zone null default now(),
    variants_id bigint not null,
    category_id bigint not null,
    constraint categories_pkey primary key (variants_id, category_id),
    constraint categories_category_id_fkey foreign key (category_id) references category (id),
    constraint categories_variants_id_fkey foreign key (variants_id) references variants (id)
  ) tablespace pg_default;
```

and here is the query I made:

```javascript
                const { data: category, error } = await supabase
                        .from('category')
                        .select(`variants(id,images,nb_stock), id, name, parent)`)
                        .eq(`id, 1`)
                /* I also tried this one: */
                const { data: variants, error } = await supabase
                        .from('variants')
                        .select(`id,images,nb_stock, category!inner(id, name, parent)`)
                        .eq(`category.id, 1`)
```

## Expected behavior

You will encounter the following mistake:
{"code":"22P02","details":null,"hint":null,"message":"invalid input syntax for type bigint: \"undefined\""}

Also, the query log if you're interested:
      "query": "WITH pgrst_source AS ( SELECT \"public\".\"category\".\"id\", \"public\".\"category\".\"fr_name\", \"public\".\"category\".\"parent\", COALESCE( \"category_variants_1\".\"category_variants_1\", '[]') AS \"variants\" FROM \"public\".\"category\" INNER JOIN LATERAL ( SELECT json_agg(\"category_variants_1\") AS \"category_variants_1\"FROM (SELECT \"public\".\"variants\".\"id\", \"public\".\"variants\".\"images\", \"public\".\"variants\".\"nb_stock\" FROM \"public\".\"variants\", \"public\".\"categories\"  WHERE \"public\".\"categories\".\"variants_id\" = \"public\".\"variants\".\"id\" AND \"public\".\"categories\".\"category_id\" = \"public\".\"category\".\"id\"  LIMIT $1 OFFSET $2 ) AS \"category_variants_1\" ) AS \"category_variants_1\" ON \"category_variants_1\" IS NOT NULL WHERE  \"public\".\"category\".\"id\" = $3  LIMIT $4 OFFSET $5 )  SELECT null::bigint AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, coalesce(json_agg(_postgrest_t), '[]')::character varying AS body, nullif(current_setting('response.headers', true), '') AS response_headers, nullif(current_setting('response.status', true), '') AS response_status FROM ( SELECT * FROM pgrst_source ) _postgrest_t",

## System information

- OS: Linux
- Version of supabase-js: ^2.22.0
- Version of Node.js: 18.16.0

**Comment by GaryAustin1** [comment]
```
.eq(`category.id, 1`)
```
You have a syntax error here.  Should be `.eq('category.id',1)`

This seems more like a help question than a bug report.

**Comment by lambdina** [comment]
@GaryAustin1 I'm sorry I really didn't saw it, and as I was following all of the advices of previous people encountering the same error message, I was pretty sure it was a bug.
Have a nice day!
