### ISSUE TITLE
nuxt3 todo examples

### ISSUE THREAD

**Issue by stlbucket** [supabase/supabase#15095]
all examples for nuxt todo are out of date and don't work as there appear to have been some breaking changes since they were authored.

i have created a current nuxt3 version alongside the next and svelte examples and will make a pull request.

**Comment by KevinBrolly** [comment]
Hey @stlbucket I am going to close this issue in favour of your in-progress PR #15096 as there is no need to have both. Thank you for your suggestions and contribution.
