### ISSUE TITLE
Example: Blitz.js

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#151]
# Feature request

## Describe the solution you'd like

Example app that shows usage of Supabase with [Blitz.js](https://blitzjs.com/).

## Additional context

Blitz ships with Prisma by default but is backend agnostic. Here an example of Blitz with Knex: https://github.com/blitz-js/blitz/tree/canary/examples/no-prisma. We should send a PR to add a Supabase + Blitz example in that folder as well.

**Comment by kiwicopple** [comment]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).
