### ISSUE TITLE
bug: flyout menu no longer full width

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#1511]
# Bug report

## Describe the bug

Flyout menu is not full width.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to homepage
2. click on 'Product' in navbar

## Expected behavior

To be full width

## Screenshots

![Screenshot 2021-05-10 at 17 34 46](https://user-images.githubusercontent.com/8291514/117638989-04f10280-b1b6-11eb-91e0-860797214c19.png)

**Comment by MildTomato** [comment]
Go for it 😃

**Comment by florian-lefebvre** [comment]
Oh I juste made #1519 which includes that but not only 😅
