### ISSUE TITLE
Group based Access Control Example

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#1513]
- [ ] it would be useful to extend one of our examples ([slack clone?](https://github.com/supabase/supabase/tree/master/examples/nextjs-slack-clone)) or make a new one, to show an example of how you can have different user types.

For example, admin, mod, or regular-user. Where an admin and mod can delete messages/channels, but a user can only delete their own.

- [ ] We can also add this to the [Auth docs](https://supabase.io/docs/guides/auth) to show an example of a policy and corresponding table that checks the user group/role present in the access_token (jwt)

**Comment by kiwicopple** [comment]
> how you can have different user types.

eg: a RBAC schema (with some access control lists)? This was requested on the [Redwood forum](https://community.redwoodjs.com/t/redwood-and-supabase-auth-example/2022/9) too. 

> checks the user group/role present in the access_token (jwt)

I think for best-practice we should keep access controls out of the JWT. It's fine(ish) for AuthN, but not great for AuthZ - the main problem being that if you revoke a role it's still valid until the JWT expires. Perhaps we can come up with an RBAC schema which shows how to do it entirely withing the schema/policies? 

This article with specifies a few strategies:

https://cazzer.medium.com/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945
