### ISSUE TITLE
Hydration errors in NextJS User Auth guide

### ISSUE THREAD

**Issue by aleciavogel** [supabase/supabase#15145]
# Improve documentation

## Link 
https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs

([Here's a link to the markdown file to edit](https://github.com/supabase/supabase/blob/114fd72c13c5b1c18f11a5bad71cea25e33ccff7/apps/docs/pages/guides/getting-started/tutorials/with-nextjs.mdx?plain=1#L4) for your convenience)

## Describe the problem

Following the tutorial exactly results in hydration errors where `supabase/auth-helpers-nextjs` is used on the client. This may actually require an improvement in that particular library, but there is a pretty easy workaround in the meanwhile.

You also get an error in your terminal if you don't run `npm install encoding` (again, might have to do with a different library that needs improvement, but it's a simple fix).

## Describe the improvement

Add something about running `npm install encoding`.

In `app/auth-form.tsx`:

```typescript
import { useState, useEffect } from 'react';

export default function AuthForm() {
  const supabase = createClientComponentClient<Database>()
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) {
    return null;
  }

  // ...
}
```

And then follow the same pattern for `app/account/account-form.tsx`.

## Additional context

Screenshots of the issues after following the tutorial in a fresh project where I'm using the latest version of NextJS (13.4.6)

<img width="1438" alt="Auth form error" src="https://github.com/supabase/supabase/assets/11688080/816f6458-0cbf-4056-9cd7-c6c54f5611e2">

<img width="1438" alt="Account form error" src="https://github.com/supabase/supabase/assets/11688080/0ea5a696-4bd7-4de5-b5f9-899bcc22b0ce">

![encoding dependency error](https://github.com/supabase/supabase/assets/11688080/f10f4c12-2e0a-41a1-a813-356803995e87)

**Comment by gregnr** [comment]
Thanks for reporting @aleciavogel!

I found a related Firebase SDK issue https://github.com/firebase/firebase-js-sdk/issues/7280 which mentions that `node-fetch` v3 might fix the problem. For [`@supabase/supabase-js`](https://github.com/supabase/supabase-js/tree/master), `node-fetch` comes from [`cross-fetch`](https://github.com/lquixada/cross-fetch), which is [still using](https://github.com/lquixada/cross-fetch/issues/146) `node-fetch` v2 unfortunately.

I agree that an update to the docs is the best short-term solution. Update to install `encoding`, probably here:
https://github.com/supabase/supabase/blob/114fd72c13c5b1c18f11a5bad71cea25e33ccff7/apps/docs/pages/guides/getting-started/tutorials/with-nextjs.mdx?plain=1#L53-L55

@aleciavogel would you be interested in opening a small PR for this?

**Comment by aleciavogel** [comment]
Certainly! I'll get it done after work tonight.

**Comment by saltcod** [comment]
Addressed on the library side. Marking this one as closed.
