### ISSUE TITLE
Infinite loading while trying to create a new policy

### ISSUE THREAD

**Issue by Ahmed-Abou-Emran** [supabase/supabase#15141]
# Bug Report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), [GitHub Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Bug Description
I am encountering an issue while trying to create a new policy that allows me to insert data into a table. The problem arises with the CHECK expression, as it leads to infinite loading and prevents me from entering any data.

## Steps to Reproduce

1. Go to the 'Authentication' page.
2. Click on 'Policies'.
3. Select a table with "RLS enabled" and click on "Create a new policy".
4. The screen displays a loading indicator at "Policy SQL template".
5. Click on "Use this template".
6. Select "INSERT".
7. At this stage, I am unable to add a check expression due to the persistent loading screen.

## Expected Behavior
I expect to be able to add a check policy and proceed with the process.

## Screenshots
![Screenshot](https://github.com/supabase/supabase/assets/64327685/67312523-3140-406e-b295-ecaabae7b802)

## System Information
- OS: Windows
- Browser: Chrome

**Comment by saltcod** [comment]
Hey @Ahmed-Abou-Emran sorry you're running into this one. 

Could you provide the statement you're putting into the with check expression box? 

Also, does this happen for all projects / tables or just this one?


<img width="1223" alt="CleanShot 2023-06-19 at 12 05 13@2x" src="https://github.com/supabase/supabase/assets/105593/76d68e1e-9a12-4cc6-a0ae-937ae253dccb">

**Comment by Ahmed-Abou-Emran** [comment]
hey @saltcod 
I haven't put any statement. The loading screen appears directly after I click create a new policy.
This happens for all projects / tables and it also appears in the the select template screen.
![image](https://github.com/supabase/supabase/assets/64327685/48c04be9-765a-499e-8a00-fd12e7fab9e8)

**Comment by saltcod** [comment]
aah kk great. Sorry you ran into this one, appreciate the followup!

**Comment by Ahmed-Abou-Emran** [comment]
Hi @saltcod ,
It seems that the problem appears again and I cannot access the database unless I disable the RLS which is very sad, and when I try connecting to a VPN as previously, I get disconnected from the website.

This is a problem, since it might not be obvious from the original image that I attached:
![Reporting Issues](https://github.com/supabase/supabase/assets/64327685/4591fc69-670b-422c-812e-bab6100a279a)

and this what happens  when I try to connect to a VPN:
![using a VPN](https://github.com/supabase/supabase/assets/64327685/2251db59-fdd9-46d9-8b1f-32d9bac5d501)

**Comment by Belal95** [comment]
I ran into the same issue and it was fixed by your solution 🎉
