### ISSUE TITLE
CLI: supabase link return password authentication failed for user "postgres" (SQLSTATE 28P01)

### ISSUE THREAD

**Issue by RobertB4** [supabase/supabase#15184]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When I try to use the cli to execute `supabase link`, I get the error message: password authentication failed for user "postgres" (SQLSTATE 28P01)

Command I tried to executed:
supabase link --project-ref **********
supabase link --project-ref ********** --password ********

I copied the value listed under Reference ID in the screenshot below.
![projectsettings](https://github.com/supabase/supabase/assets/33457563/5f08d35f-b283-4549-a1e6-d8017cf5f30f)

## Expected behavior
I expect to be able to successfully link my local to my remote project.

## System information

- OS: macOS Monterey 12.1
- Version of supabase-cli: 1.68.6

## Additional context

Potentially related: My project was paused for a few months. I restored it around 2-3 days ago.

**Comment by saltcod** [comment]
Hey @RobertB4 – does linking work for any of your other projects or just this one?

**Comment by RobertB4** [comment]
Hey @saltcod , I only had this one project, so I just tried to create a new one to test it. I get the same error:
```
supabase link --project-ref **********
Retrying... db.**********.supabase.co 5432
Error: failed to connect to `host=db.**********.supabase.co user=postgres database=postgres`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

**Comment by saltcod** [comment]
Have you tried resetting your database password here? 
https://app.supabase.com/project/_/settings/database

**Comment by RobertB4** [comment]
Yes, I tried resetting my database password, didn't work.
I also tried generating a new access token to log in with the cli, didn't work either.
I am still getting the same error message.

Any other ideas what the problem could be? The only idea I have left is trying to create a new supabase account.

**Comment by RobertB4** [comment]
@saltcod I tried creating a new supabase account. I am still getting an error, though slightly different this time:
```
Error: failed to connect to `host=db.*****.supabase.co user=postgres database=postgres`: failed SASL auth (FATAL: SASL authentication failed (SQLSTATE 08P01))
```

When I run the command with --debug, I get:
```
2023/06/26 02:01:34 PG Recv: {"Type":"ErrorResponse","Severity":"FATAL","SeverityUnlocalized":"FATAL","Code":"28P01","Message":"password authentication failed for user \"postgres\"","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"auth.c","Line":326,"Routine":"auth_failed","UnknownFields":null}
```

I also tried using supabase link on a different computer. I get the same error message.

I  am out of ideas. Different computer + new account with new project did not work.

Either this is a bug, or I am not using the right project ref?
Is supabase link working for you or do you have any pointers what else I could try?

**Comment by saltcod** [comment]
Hey @RobertB4 —sorry you're having a terrible time here! I'll ask the CLI team to have a look and see if they have any ideas!

**Comment by saltcod** [comment]
@RobertB4 just to be sure...

Would be extremely weird if this wasn't the case, but could you confirm that the project ref in the url matches the one in the database settings that you've screenshot'd? 

https://supabase.com/dashboard/project/_/settings/general

Should be 20 chars & look like `elarqxgkbjegrvuaungu`

**Comment by sweatybridge** [comment]
Another alternative you could try is by setting the db password env var. For eg. 

```bash
SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>
```

May be there's a special character that messed up bash. Let me know!

**Comment by RobertB4** [comment]
@sweatybridge Thanks, setting the password worked. I tried executing supabase link without setting the password to make sure that's what the issue was, and yep it was. Appreciate the help!

```
SUPABASE_DB_PASSWORD=********** supabase link --project-ref **********
Finished supabase link.
supabase link --project-ref **********
Error: failed to connect to `host=db.**********.supabase.co user=postgres database=postgres`: failed SASL auth (FATAL: SASL authentication failed (SQLSTATE 08P01))
```

**Comment by RoyNyaga** [comment]
Hello guys, I have almost the same issue but mine comes up when pushing my migrations through supabase CLI using the command `pnpm supabase db push`.

I am able to link my local project with the one on cloud using the command `supabase link --project-ref **********`
but yet the `pnpm supabase db push` fails with the error message `failed to connect to `host=db.dszdioldqhzlbqutsjyp.supabase.co user=postgres database=postgres`: dial error (dial tcp [64:ff9b::36c1:896b]:5432: connect: no route to host)`

The server response descriptive error message says `"Message":"password authentication failed for user \"postgres\"`

I tried setting an environment variable as I have read in the above comments using the command (NB: I am on zsh terminal on MacOs)
```
export SUPABASE_DB_PASSWORD=********** supabase link --project-ref **********
```
This time around, I am not promoted to enter a password when I use the command `pnpm supabase db push` but I still have the same error.

Please any help on this will highly be appreciated. Thanks.
@RobertB4 @sweatybridge

**Comment by caroguerrerosilvera** [comment]
@RoyNyaga I got the same result as you. If you check the settings, in the Database section, you will notice that your IP has been baned for security reasons, that's why the error has changed.

**Comment by RoyNyaga** [comment]
@caroguerrerosilvera I think you are right cus my team added restrictions to some countries, I asked them and they confirmed it. Thanks so much @caroguerrerosilvera .

**Comment by createev** [comment]
Having the same issue when trying to do supabase db pull or supabase migration list. project links successfully. 

tried setting password in the command line, still getting this: 

`failed to connect to `host=db.<project id>.supabase.co user=postgres database=postgres`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))`

Anyone faced and resolved this?

**Comment by caroguerrerosilvera** [comment]
@createev for me, the issue was resolved by resetting the database password. I still don't understand what the problem was, as the password was correct (I was using the same password for migrations with Prisma). The only thing I noticed is that my new password didn't contain certain special characters. After resetting it, everything worked normally.

**Comment by createev** [comment]
Thank you. Reseting password for database helped.

**Comment by sablair** [comment]
Experienced the same issue today on a fresh installation. Everything was fine after resetting the database password.

**Comment by stargt** [comment]
Resetting the database password is not working for my case even there is no special character in the password. But explicitly declaring SUPABASE_DB_PASSWORD worked.

> Another alternative you could try is by setting the db password env var. For eg.
> 
> ```shell
> SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>
> ```
> 
> May be there's a special character that messed up bash. Let me know!

**Comment by santhonydo** [comment]
this worked for me as well. weird

> ```shell
> project-ref 
> ```

**Comment by bobiboMC** [comment]
I have similar Issue but my problem is I can't even enter a password in cmd / terminal in Visual Code in windows 11 when it ask me to enter a password, and this is the error I get:
![problem_supabase](https://github.com/supabase/supabase/assets/61916959/967854e9-9001-4674-94f5-b8aa14031f1b)

I set the password using set `SUPABASE_DB_PASSWORD=<pass>` before running the linking and reseting commands.

**Comment by JTCorrin** [comment]
None of the above works for me. I get 

`{"Type":"AuthenticationSASLFinal","Data":"e=Wrong password"}`

when I try to link my project. I've set my SUPABASE_DB_PASSWORD env var.

If I try to link another project, an older one, it works fine. I assume my env var is being ignored and somewhere its simply reading my other project password.

How do I fix this?

**Comment by Slyracoon23** [comment]
I am also experience the same issue but actually this error
```
2024/03/25 18:14:48 PG Recv: {"Type":"AuthenticationOK"}
2024/03/25 18:14:57 Connect Start: tcp 44.208.221.186:5432
2024/03/25 18:14:58 Connect Done: tcp 44.208.221.186:5432
2024/03/25 18:14:58 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.lrlfxhthocoopwfwvdbb"}}
2024/03/25 18:14:58 PG Recv: {"Type":"AuthenticationSASL","AuthMechanisms":["SCRAM-SHA-256"]}
2024/03/25 18:14:58 PG Send: {"Type":"SASLInitialResponse","AuthMechanism":"SCRAM-SHA-256","Data":"n,,n=,r=S7yXaIQVrl1QU1YjTkeD/N6f"}
2024/03/25 18:14:58 PG Recv: {"Type":"AuthenticationSASLContinue","Data":"r=S7yXaIQVrl1QU1YjTkeD/N6fRUxuVUNCdlVtV0NBSDlSZGJhL0kwQmtDc1dyTVNRPT0=,s=prBh4YU4AV9JG0RHUbXnHA==,i=4096"}
2024/03/25 18:14:58 PG Send: {"Type":"SASLResponse","Data":"c=biws,r=S7yXaIQVrl1QU1YjTkeD/N6fRUxuVUNCdlVtV0NBSDlSZGJhL0kwQmtDc1dyTVNRPT0=,p=VgQtG7LDbgUskA0XBCaWF79d6DByuBS9FEiwfZ1TFRs="}
2024/03/25 18:14:58 PG Recv: {"Type":"ParameterStatus","Name":"server_version","Value":"15.1 (Ubuntu 15.1-1.pgdg20.04+1)"}
panic: io: read/write on closed pip
```

Using CLI `1.151.1`

I can not link to supabase

**Comment by beardedlinuxgeek** [comment]
> Another alternative you could try is by setting the db password env var. For eg.
> 
> ```shell
> SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>
> ```
> 
> May be there's a special character that messed up bash. Let me know!

I had to do this on Windows recently. The command is:

```shell
$env:SUPABASE_DB_PASSWORD="<pass>"; pnpx supabase link --project-ref <ref>
```

**Comment by huynamboz** [comment]
> ```shell
> $env:SUPABASE_DB_PASSWORD="<pass>"; pnpx supabase link --project-ref <ref>
> ```

It worked for me

**Comment by sangkyuleeKOR** [comment]
why supabase team never fix this problem? I spent whole day to fix this issue.

**Comment by arnelamo** [comment]
> why supabase team never fix this problem? I spent whole day to fix this issue.

How did you fix it? I have the same problem. 
I have reset the DB password, several times - no special characters.

Works:
supabase link --project-ref <ref>
supabase link --project-ref <ref> --password <pass>
supabase status

Does NOT work:
supabase db push

`failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))`

**Comment by sangkyuleeKOR** [comment]
> > Another alternative you could try is by setting the db password env var. For eg.
> 
> > 
> 
> > ```shell
> 
> > SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>
> 
> > ```
> 
> > 
> 
> > May be there's a special character that messed up bash. Let me know!
> 
> 
> 
> I had to do this on Windows recently. The command is:
> 
> 
> 
> ```shell
> 
> $env:SUPABASE_DB_PASSWORD="<pass>"; pnpx supabase link --project-ref <ref>
> 
> ```

it workted for me as well.

**Comment by sangkyuleeKOR** [comment]
> > Another alternative you could try is by setting the db password env var. For eg.
> 
> > 
> 
> > ```shell
> 
> > SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>
> 
> > ```
> 
> > 
> 
> > May be there's a special character that messed up bash. Let me know!
> 
> 
> 
> I had to do this on Windows recently. The command is:
> 
> 
> 
> ```shell
> 
> $env:SUPABASE_DB_PASSWORD="<pass>"; pnpx supabase link --project-ref <ref>
> 
> ```

it workted for me as well.

**Comment by Rodrigolmti** [comment]
Sharing an insight that might help some people, it seems that you can fix this issue by running the following command:
> SUPABASE_DB_PASSWORD=<pass> supabase link --project-ref <ref>

But don't forget to restart your terminal after that, at least for me this was the missing piece.

**Comment by jsundy** [comment]
This was my root cause analysis on the authentication failure:

#### Root Cause Analysis: psycopg2-binary Auth Failure with Supabase Pooler
Summary: psycopg2-binary fails SCRAM-SHA-256 authentication against Supabase's Supavisor pooler. The same credentials succeed with psycopg2 (compiled against system libpq) and with psql.

## Environment:
 - macOS (Apple Silicon)
 - Supabase session pooler (`aws-1-us-east-1.pooler.supabase.com:5432`)
 - `psycopg2-binary==2.9.11`, bundled `libpq` version `170006` (`17.0.6`)
 - Auth method: `SCRAM-SHA-256`

## Symptoms:
- FATAL: password authentication failed for user "postgres" on every connection attempt
- Error is consistent regardless of password, `sslmode`, or `gssencmode` settings
- TCP connection to the pooler succeeds (ports reachable via nc)
- Password verified correct in `pg_authid` via separate MCP connection
- Failed attempts never appear in Postgres server logs — rejection happens entirely within Supavisor before reaching Postgres

## Root Cause:
`psycopg2-binary` bundles its own `libpq` (`17.0.6`) which has an incompatibility with how Supabase's Supavisor implements the `SCRAM-SHA-256` challenge-response handshake. The bundled `libpq` fails at the auth negotiation layer in a way that is silently surfaced as a password failure by the pooler.

## Evidence:
- `psql` (Homebrew `libpq`) → connects successfully with identical credentials
- `asyncpg` (independent Postgres wire protocol implementation) → also fails, suggesting the issue may be in how both clients respond to Supavisor's specific SCRAM challenge format
- `psycopg2` compiled against Homebrew system libpq → connects successfully

## Fix:
Replace `psycopg2-binary` with `psycopg2` compiled against the system `libpq`:

```toml
# pyproject.toml — before
"psycopg2-binary>=2.9.0"

# after
"psycopg2>=2.9.0"
```

## Build with Homebrew libpq paths:
```
LDFLAGS="-L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/libpq/lib" \
CPPFLAGS="-I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/libpq/include" \
uv sync
```
