### ISSUE TITLE
Bucket policy not working in edge functions

### ISSUE THREAD

**Issue by vladgardus** [supabase/supabase#15189]
## Describe the bug

I'm trying to setup the policies for a private bucket so that a user only has access to his bucket so I used the following policy which I found in the access control for buckets tutorial:` ((bucket_id = 'inputImages'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))`

Then I created two folders in my bucket, one for each user:
![image](https://github.com/supabase/supabase/assets/43858789/ea1ff635-a248-4f7d-81b9-b5e807748a4a)

And then, in an edge function I'm creating my supabase client as follows: 
```
const supabaseClient = createClient<Database>(supabaseConfig.SB_URL, supabaseConfig.SB_ANON_KEY, {
          global: { headers: { Authorization: ctx.request.headers.get('Authorization')! } },
});
```
I can confirm that `ctx.request.headers.get('Authorization')` returns the actual token for a user and that the second param in the createClient method is the anon key, not the admin one.

Then, when I try to create a signed URL for a given file, I do not get any error, even though the policy should have prevented it: `await supabaseClient.storage.from('inputImages').createSignedUrl('7fd17337-35f6-43d5-944d-011c1018aa8f/epoc.jpg', 120);`

I also tried adding something like this to the select policy so that it should always fail, but it does not: `((bucket_id = 'inputImages'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text) AND false)`

Is something broken with my bucket policies?

**Comment by GaryAustin1** [comment]
You probably should be seeking help in discussions or Discord as you do not mentioning do that, before declaring a bug.

![image](https://github.com/supabase/supabase/assets/54564956/50161fc6-8651-47ec-95fa-2ecc4a3e45d0)

Not sure that is your issue, but bucket names need to be lowercase.

**Comment by vladgardus** [comment]
Well, then it should not have let me create the bucket if I did not follow the naming guidelines.

Regardless, I also tried creating a folder called "input-images" and the result is the same.

And I browsed the past github issues and discussions, but did not find something similar to my use case.

**Comment by GaryAustin1** [comment]
Well, my recommendation is to seek user help (I'm a user) but filing a bug usually means you wait for a Supabase employee to examine if it is a bug or not.

Lots of things can go wrong with policies.   You don't show exactly how you set this policy (select policy on **storage.objects** is where it should go, not storage.buckets but there is now way to know from your input so far).  

The policy you show in general does work.

If you have any select policy in your storage.objects table that does not have the bucket_id part that will also get evaluated for all buckets so might always allow access.

**Comment by vladgardus** [comment]
@GaryAustin1 Here are the bucket policies I have set up:
![image](https://github.com/supabase/supabase/assets/43858789/256e1659-6569-4016-828f-485c58f83946)
All of them are under the inputImages bucket.

I have tried it out and the insert policy does actually prevent me from inserting data in another users bucket, it is just that the select RLS does not work.

I also don't have any other generic policies:
![image](https://github.com/supabase/supabase/assets/43858789/b87e0c2f-6d96-46b7-a3e0-5b5eeee5e94b)

**Comment by GaryAustin1** [comment]
If you have other buckets,  I would double check their select policies to make sure they all have bucket_id test in them.  I don't think the UI actually parses that and just relies on you doing that for each different bucket policy, but have not messed with it enough to know for sure.

Otherwise try just making the select policy false (nothing else).  If that works then there is another RLS select policy applying to the bucket that is evaluating true.

**Comment by vladgardus** [comment]
Thanks Gary, you were right, there was another select policy that always returned true for all buckets and was overriding my actual policy I was working on. Going to close this.
