### ISSUE TITLE
Sigout issue for nextjs canary example 

### ISSUE THREAD

**Issue by gon250** [supabase/supabase#15193]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I think there is an issue on the example you have at https://github.com/vercel/next.js/tree/canary/examples/with-supabase 
Basically Ive downloaded the code and followed all the step and when logout I get the below error on the console, I get redirected to the login page but the cookie still there and I can access directly to the http://localhost:3000 (home page where you have the checking if the user exist to redirect to the login) and I can go to the home after clicking on the logout.

```
Error: NEXT_REDIRECT
    getRedirectError redirect.js:47
    serverActionReducer server-action-reducer.js:128
    clientReducer router-reducer.js:49
    devToolReducer use-reducer-with-devtools.js:63
    updateReducerImpl react-dom.development.js:11456
    updateReducer react-dom.development.js:11294
    useReducer react-dom.development.js:13070
    useReducer react.development.js:1789
    useReducerWithReduxDevtoolsImpl use-reducer-with-devtools.js:102
    Router app-router.js:121
    renderWithHooks react-dom.development.js:10807
    updateFunctionComponent react-dom.development.js:15900
    beginWork$1 react-dom.development.js:18110
    beginWork react-dom.development.js:26457
    performUnitOfWork react-dom.development.js:25308
    workLoopConcurrent react-dom.development.js:25294
    renderRootConcurrent react-dom.development.js:25250
    performConcurrentWorkOnRoot react-dom.development.js:24124
    workLoop scheduler.development.js:261
    flushWork scheduler.development.js:230
    performWorkUntilDeadline scheduler.development.js:537
lockdown-install.js:1:103865

```

## To Reproduce

1. Go to https://github.com/vercel/next.js/tree/canary/examples/with-supabase and follow the `How to use` section
2. When the up is running locally after finish the step 6, signup 
3. When you are logged in the home page, open de browser console and click the logout button
4. you will see the error, and also check the cookie still there.
5. Also if you try to go to the home page where you have the auth check to redirect is not working because the issue loging out.
```
export default async function Index() {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  // This is a Protected Route that can only be accessed by authenticated users
  // users who are not signed in will be redirected to the `/login` route
  if (!user) {
    redirect('/login')
  }
// ....
```

## Expected behavior

1. We should not get an error in the console
2. Cookie should get expired
3. We should not be able to access to home screen without login

## Screenshots

https://github.com/supabase/supabase/assets/1652286/5e1b3167-5d32-4d32-ac45-889c15703bc9

## System information

- OS: macOS
- Browser: Firefox
- packages: https://github.com/vercel/next.js/blob/canary/examples/with-supabase/package.json
- Version of Node.js: v19.5.0

**Comment by dijonmusters** [comment]
Thanks for the Supa fast bug spotting! 🐛 

This should be fixed in this one: https://github.com/vercel/next.js/pull/51442

The Server Action is not removing the cookie properly. This PR refactors the `logout` functionality to use a Client Component 👍 

Let is know if you're still having this issue with the Client Component version 🙂
