### ISSUE TITLE
OAuth using using 3rd party providers happen but on redirecting, session is not present

### ISSUE THREAD

**Issue by danger-ahead** [supabase/supabase#15217]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

While implementing third party Sign in, Sign in is successful.
But when I console logged this in the redirect URL page:
```
const { data, error } = await supabase.auth.getSession();

const {
  data: { user },
} = await supabase.auth.getUser();

console.log(user);
console.log(data);
console.log(error);
```
I get this message in the console: 
```
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
null
{ session: null }
null

-  ┌ GET /workspace?code=59bf8de1-019d-4c99-b007-5129ac2a9515 200 in 1852ms
   │
   └──── GET https://ovgkukhwdvlkjcqq../auth/v1/user 401 in 1554ms (cache: MISS)
```
When I googled, this result comes up:
https://github.com/supabase/gotrue-js/blob/b3a6ff4f676b8b6209fac9b82d752d1b5923d63c/src/GoTrueClient.ts#L180

## Screenshots
In this call, I can see the access token of supabase post sign in.
![image](https://github.com/supabase/supabase/assets/55531939/93b61078-e543-40e7-9b86-2753a869d345)
However, it is not present in the call to fetch the redirect page:
![image](https://github.com/supabase/supabase/assets/55531939/8040fb37-fd62-4247-8fdd-daee6b7d1d23)

## System information

- OS: Linux
- Browser: Firefox 114
- Version of supabase-js: 2.25.0
- Version of Node.js: 18.16.0
- Frontend using: Next.js 13.4.5 `/app` based routing

## Additional context

Things I've verified:
- Site URL is set to: https://localhost:3000
- Redirect URL is set to: https://localhost:3000/workspace
- I'm calling the `signInWithOAuth` function from client side. The `redirectTo` field under `options` is also properly set and matches the redirect URL set in supabase. 
- `Middleware.ts` is exactly the same and copied from [this page - Supabase Auth with the Next.js App Router](https://supabase.com/docs/guides/auth/auth-helpers/nextjs).
- `app/auth/callback/route.ts` is exactly the same and copied from the above page as well.

**Comment by danger-ahead** [comment]
> The warning message talks about need a storage provider. That is local storage. You need to provide that if your environment does not have local storage OR like the messages says turn persistSession:false in createClient. If you don't some calls involving the session will clear it.

I'm using Firefox without any settings modifications.

I did clear cookies and data of localhost from Firefox just before trying to sign in with the redirect URL. Could this be the cause?

**Comment by GaryAustin1** [comment]
You mention node.js.   The warning would be typical of running a createClient in that environment.
It may not be the cause of your issue if all your other code is running on the browser, but for some reason you have createClient on a serverside call.

**Comment by danger-ahead** [comment]
> You mention node.js and next.js. The warning would be typical of running a createClient in that environment. It may not be the cause of your issue if all your other code is running on the browser, but for some reason you have createClient on a serverside call.

Both the pages involved, `/login` and `/workspace` are marked as "use client";
I have initiated the supabase client outside the `/app` directory in a separate `utils` folder at the root of the project.

**Comment by silentworks** [comment]
I think this issue is related to a bug we discovered yesterday where the encoded URL isn't allowing redirects to happen. I will update you on this issue when we have a fix in place.

**Comment by silentworks** [comment]
Actually this issue is unrelated to the bug we discovered yesterday.

**Comment by danger-ahead** [comment]
The bug was in my implementation!
