### ISSUE TITLE
Tutorial react-user-management example profile updated without avatar_url

### ISSUE THREAD

**Issue by jwhits** [supabase/supabase#15225]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
In the [Build a User Management App with React](https://supabase.com/docs/guides/getting-started/tutorials/with-react) tutorial [Accounts.jsx](https://github.com/supabase/supabase/blob/master/examples/user-management/react-user-management/src/Account.jsx)
When you upload a avatar picture, the picture is uploaded to storage as expected however onUpload also calls updateProfile and the profile is updated before setAvatarUrl state is set so updateProfile updates the user profile with a null avatar_url

`return (
    <form onSubmit={updateProfile} className="form-widget">
      <Avatar
        url={avatar_url}
        size={150}
        onUpload={(event, url) => {
          setAvatarUrl(url)
          updateProfile(event)
        }}
      />`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the react-user-management example
2. Upload avatar picture
3. Check storage bucked for uploaded avatar picture
4. Check profile table avatar_url will be null

## Expected behavior

profile table avatar_url should contain url to avatar picture

## System information

- OS: macOS
- Browser Safari
- Version of supabase-js: 2.25.0
- Version of Node.js: 18.16.0

**Comment by gregnr** [comment]
Good catch @jwhits. Probably we should just pass the `url` directly to `updateProfile()`.

Would you be interested in opening a small PR for this?

**Comment by gitryder** [comment]
@gregnr I'd like to work on this, please

**Comment by gregnr** [comment]
That would be great @gitryder 👍

**Comment by gitryder** [comment]
Opened a PR for this

**Comment by GaryAustin1** [comment]
This was fixed.
