### ISSUE TITLE
Migration repair crashes

### ISSUE THREAD

**Issue by blueneogeo** [supabase/supabase#15243]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running migration repair crashes

## To Reproduce

First tried to create a list of migrations:

❯ supabase migration list 

```
    LOCAL │     REMOTE     │     TIME (UTC)
  ────────┼────────────────┼──────────────────────
          │ 20230617153135 │ 2023-06-17 15:31:35
          │ 20230617154033 │ 2023-06-17 15:40:33
          │ 20230617155319 │ 2023-06-17 15:53:19
          │ 20230617160157 │ 2023-06-17 16:01:57
          │ 20230617161203 │ 2023-06-17 16:12:03
          │ 20230617161914 │ 2023-06-17 16:19:14
```

Then tried to apply the remote change to local:

❯ supabase migration repair 20230617153135 --status applied

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1056f7a80]

goroutine 1 [running]:
github.com/supabase/cli/internal/migration/repair.UpdateMigrationTable({0x105ca8818, 0x140002526c0}, 0x1400068e000, {0x16b2d3322, 0xe}, {0x16b2d333a, 0x7}, {0x105cab730, 0x106514ee8})
	/home/runner/work/cli/cli/internal/migration/repair/repair.go:54 +0xe0
github.com/supabase/cli/internal/migration/repair.Run({0x105ca8818, 0x140002526c0}, {{0x14000130720, 0x23}, 0x198f, {0x10574e9ee, 0x8}, {0x10574e9ee, 0x8}, {0x140005125e8, ...}, ...}, ...)
	/home/runner/work/cli/cli/internal/migration/repair/repair.go:39 +0xf0
github.com/supabase/cli/cmd.glob..func43(0x1064b35c0, {0x14000305620, 0x1, 0x3?})
	/home/runner/work/cli/cli/cmd/migration.go:69 +0x130
github.com/spf13/cobra.(*Command).execute(0x1064b35c0, {0x140003055c0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x1064b8ee0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/supabase/cli/cmd.Execute()
	/home/runner/work/cli/cli/cmd/root.go:95 +0x2c
main.main()
	/home/runner/work/cli/cli/main.go:8 +0x20
```

## Expected behavior

Expect either a migration error message or a successful migration repair

## System information

- OS: MacOS / M1Max
- Version of supabase-js: "@supabase/supabase-js": "^2.25.0"
- Version of Node.js: v16.20.0

**Comment by saltcod** [comment]
Hi @blueneogeo — real quick, want to check if this a bug report or a support request — or both? 

If it's just a bug report, happy to forward to the CLI team. If you're currently stuck by this, please submit a support ticket via the dashboard and we can help get you unstuck!

**Comment by blueneogeo** [comment]
Hi @saltcod , I meant it as a bug report, since this seems unwanted behaviour and I could not find it reported elsewhere. But thank you, I will also put in a support ticket since I am actually stuck due to this.

**Comment by saltcod** [comment]
Thanks @blueneogeo let's track it in a support ticket.

**Comment by blueneogeo** [comment]
Ok, but should it not be noted as a bug that a command line tool returns a segfault?
