### ISSUE TITLE
Authentication Flow Redirection Issue on iOS with signInWithOAuth Button

### ISSUE THREAD

**Issue by brocchirodrigo** [supabase/supabase#15245]
### Discussed in https://github.com/orgs/supabase/discussions/15220

<div type='discussions-op-text'>

<sup>Originally posted by **brocchirodrigo** June 20, 2023</sup>

Good afternoon, everyone! I stumbled upon a problem and I need some help, but first of all, I would like to say that I found Supabase services fantastic!

Regarding the issue:
I'm using the latest version of NextJS and the Next Helpers package from Supabase.
I have an authentication page that uses the Auth package buttons (signInWithOtp and signInWithOAuth).
The email authentication button works perfectly on all platforms.
The problem I'm facing is with the signInWithOAuth button on iPhones and iPads. When the user tries to authenticate using Google or Twitter providers on Android or the web, the redirection and authentication flow work normally. However, on iOS, the redirection doesn't happen.
I've tried a few approaches, but without success, and I need help with this case.

Versions:
"@supabase/auth-helpers-nextjs": "^0.7.2",
"@supabase/supabase-js": "^2.26.0" (not currently in use on the pages),
"next": "13.4.6" (using the app folder).</div>

**Comment by brocchirodrigo** [comment]
I tested a new NextJS package using the Helpers started from scratch with the same versions mentioned above, and the same problem occurred. As the problem may have originated from the Supabase Helpers package, I converted the discussion into an issue for evaluation by the responsible team.

**Comment by brocchirodrigo** [comment]
Not yet...

**Comment by KevinBrolly** [comment]
Hey @brocchirodrigo I am going to close this issue in favour of your discussion #15220 as that is the best place to discuss and resolve your issue.
