### ISSUE TITLE
NextJS Auth Helpers Documentation needs update

### ISSUE THREAD

**Issue by biggeye** [supabase/supabase#15264]
# Improve documentation

[## Link ](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-pages)

Add a link to the page which needs improvement (if relevant)

making references to module functions that no longer exist:

example:
import { **createPagesBrowserClient** } from '@supabase/auth-helpers-nextjs'
...

upon looking in the module I realized that it seems the functions needed are now:

createBrowserSupabaseClient 

and 

createServerSupabaseClient

thank you for an awesome product..
cheers

**Comment by CarlosZBent** [comment]
By looking at the module's code I think the actual functions that should be used are `createPagesServerClient` and `createPagesBrowserClient`, so the docs page seems correct.

![image](https://github.com/supabase/supabase/assets/72584905/70840b40-235f-4d21-a959-cac450a1a407)

The docs were updated recently to accommodate this in commit [update Next.js (pages) guide to use new createClient functions (03ca71a)](https://github.com/supabase/supabase/commit/03ca71a6489c8138bdae8d9690317dfed138f352)

If any actual change is needed I'm happy to help :)

**Comment by gregnr** [comment]
Thanks for the issue @biggeye.

@CarlosZBent is right! Closing this, but feel free to reopen/clarify @biggeye if you feel this is still incorrect.

**Comment by PalliateAi** [comment]
Hi, 

I was on https://supabase.com/docs/guides/auth/auth-helpers/nextjs page and following the "If you are using the pages directory, check out [Auth Helpers in Next.js Pages Directory](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-pages)." , the documentation is saying to import createPagesBrowserClient from from '@supabase/auth-helpers-nextjs' . 

From  "@supabase/auth-helpers-nextjs": "^0.5.6" - there's no createPagesBrowserClient exported. 

Let me know if you have the same issue?
