### ISSUE TITLE
Docs footer icon spacing

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#15282]
Icons are ever so slightly off in spacing on https://supabase.com/docs

<img width="1292" alt="CleanShot 2023-06-22 at 14 42 23@2x" src="https://github.com/supabase/supabase/assets/105593/a02bfff1-5a95-4ad0-b98c-a09867fff173">

**Comment by CarlosZBent** [comment]
Hey @saltcod , since this is a *good first issue* I'd like to tackle it
