### ISSUE TITLE
Docs footer icons links not working

### ISSUE THREAD

**Issue by YuriCodes** [supabase/supabase#15284]
# Improve documentation footer icons

The discord icon sends to our Supabase twitter page and the twitter icon is not a link/ not clickable. 

https://supabase.com/docs

<img width="212" alt="Screenshot 2023-06-22 at 1 17 23 PM" src="https://github.com/supabase/supabase/assets/80093500/3ac84b9a-7148-418f-9e71-39dfcf0024ca">

**Comment by Isaiah-Hamilton** [comment]
https://github.com/supabase/supabase/pull/15285
