### ISSUE TITLE
Number input not showing increment buttons, overlapping validation warning

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#15308]
In Firefox, warning icon overlaps the increment buttons. 

![CleanShot 2023-06-23 at 10 12 26@2x](https://github.com/supabase/supabase/assets/105593/0976f9e6-6f64-4694-9f9b-5fdccda9d2a3)

In Chrome, increment buttons aren't visible — this is input type=number, so they should be visible.

![CleanShot 2023-06-23 at 10 13 53@2x](https://github.com/supabase/supabase/assets/105593/c946fe8d-f121-4787-ac98-2958b2d002a4)

**Comment by brendef** [comment]
Could I maybe have a go at this? Seems like a great place to start contributing? 🤔

**Comment by gregnr** [comment]
@brendef you bet! Feel free to open an PR and link to this issue 😃

**Comment by brendef** [comment]
Hey any idea how I can get passed this, sorry if it is something obvious, just wondering if anybody has maybe dealt with this before. 

<img width="1439" alt="Screenshot 2023-07-07 at 22 53 58" src="https://github.com/supabase/supabase/assets/20247351/937a6a00-2ffb-4e81-a5a5-1ab633209c2e">

@gregnr @saltcod @neiled @laktek

**Comment by SuhelMakkad** [comment]
hi @saltcod, created PR #16518 to fix this issue
