### ISSUE TITLE
Typo in Bangla README

### ISSUE THREAD

**Issue by SoumyadeepOSD** [supabase/supabase#15319]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/i18n/README.bn.md

## Describe the problem

![image](https://github.com/supabase/supabase/assets/115442240/67030a5a-16be-4200-a800-75ee76e9570a)

Just follow the last line. The word `রিপুর` will be exchanged with `রেপোর`

## Describe the improvement

Change the spelling from `রিপুর` to `রেপোর`

## Additional context

![image](https://github.com/supabase/supabase/assets/115442240/a4e1a7fe-d3dd-41a1-8a64-0f445942daad)

**Comment by mehboobali98** [comment]
Hi, can I work on this? Thanks.

**Comment by SoumyadeepOSD** [comment]
@Isaiah-Hamilton  As Contributors should get chance in hierarchical order, please assign me this issue so that I can work on it

**Comment by gregnr** [comment]
Thanks @SoumyadeepOSD, feel free to create a PR for these, no need for permission 👍

**Comment by SoumyadeepOSD** [comment]
Thanks @gregnr for giving me this issue, I will create a PR ASAP✅

**Comment by postmeback** [comment]
I think this issue is good to close

**Comment by gregnr** [comment]
Fixed in #15370
