### ISSUE TITLE
Fail to load SQL editor, report ERR_BLOCKED_BY_THE_CLIENT

### ISSUE THREAD

**Issue by Arorio** [supabase/supabase#15328]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Fail to load SQL editor, which continuously shows "Loading" with an error. I have tried different browsers and different networks, but I remains the same.

<img width="1512" alt="image" src="https://github.com/supabase/supabase/assets/92929085/2178e60b-d59b-4040-94c2-6bd1e0cc9010">

I would appreciate a lot if you could tell me how to solve this problem. Many thanks!

## To Reproduce

Simply open the SQL Editor

## System information

- OS: macOS
- Browser (if applies) chrome

**Comment by GaryAustin1** [comment]
This is not a general issue with the SQL editor as far as I can tell.  It works for me and no other reports of this error message.
Do you have a common ad blocker, browser extension, anti-virus software in all of your tests?

**Comment by devarsh-mavani-19** [comment]
@Arorio not sure but maybe u have CORS extension installed. Could you open that error Message drop-down? It will help

**Comment by Bedwey** [comment]
Same!!!
![image](https://github.com/supabase/supabase/assets/101520540/6337b3eb-126d-447a-bd6f-2f0a8b4ca4bc)
![image2](https://github.com/supabase/supabase/assets/101520540/012d8fab-45c9-43cf-8b6d-ed195d471d41)

**Comment by Arorio** [comment]
The problem has been solved. It happened because the CDN `https://cdn.jsdelivr.net` has been blocked in my country, and it goes well when I switch to a nice network. Thank you everyone for your help!~ ❤️

<img width="704" alt="image" src="https://github.com/supabase/supabase/assets/92929085/e6de9ebb-2e6b-4a12-ba75-f9d70c04db0a">

**Comment by gregnr** [comment]
Thanks for following up @Arorio! Closing this, @Bedwey feel free to open a new issue if you think you're issue is different!

**Comment by bwkam** [comment]
I'm having the exact same issue.
