### ISSUE TITLE
Main Site pricing page: nested button in anchor [a11y]

### ISSUE THREAD

**Issue by GrahamTheDevRel** [supabase/supabase#15359]
## Describe the bug

On the pricing page there are `<button>` elements nested within `<a>` elements.

This is a big accessibility issue as it will cause confusion for screen reader users around expected behaviour as a button indicates an action on the same page, an anchor indicates a change of page and they will encounter a link, then a button, both with the same text.

It also means that each "button" is now 2 tab stops for keyboard users instead of 1, which can be annoying.

It can also mean that on voice navigation (with something like Dragon Naturally Speaking), commands may not work as expected.

## Expected behaviour

As the "buttons" in question lead to another page, these should just be anchors (`<a>`) to avoid confusion. 

Then transfer all the styling from the `<button>` onto the `<a>`.

## Additional context

This appears to be a site wide issue. Therefore there are numerous instances on this page, not just in the pricing table.

Note for beginner devs: the `<button>` element appears to be a custom element on the site, so you will have to bear that in mind if you decide to tackle this issue as you will need to grab all the styles from that element.

**Comment by Arindam200** [comment]
I would like to work on this issue!

**Comment by GrahamTheDevRel** [comment]
@MildTomato WIthout seeing outputted HTML I always struggle, but does this not have the same issue but in reverse?

The issue is nested interactive elements, on my understanding the above fixes the handlers, but won't fix the accessibility tree / other issues?

I would have expected the fix to be more like:

`<a href="https://..." class="all the button classes via @apply or something?">hello there</a>` and nothing else?

I may not be understanding though as I am vanilla HTML, CSS so apologies if I misunderstood! 💗

**Comment by MildTomato** [comment]
The `asChild` prop is a bit odd to get your head around, but perhaps best explained [here](https://www.radix-ui.com/docs/primitives/guides/composition) on radix docs.


The following:
```
<Button asChild className="button-class">
  <a href="https://...">hello there</a>
</Button>
```

would output this:

```
<a href="https://..." className="button-class">hello there</a>
```

**Comment by GrahamTheDevRel** [comment]
@MildTomato that makes perfect sense. Also the `asChild` prop is clear, I just wasn't familiar and thanks for my "Today I Learned (TIL)" moment! Looks like the perfect solve.

**Comment by MildTomato** [comment]
@GrahamTheDevRel I can guarantee it took me a lot longer for me to understand that one 😂
