### ISSUE TITLE
Textlocal sms otp not getting sent from Supabase |  supabase.auth.signInWithOtp api | OTP authentication

### ISSUE THREAD

**Issue by vasanth-ravisankar** [supabase/supabase#15351]
### Discussed in https://github.com/orgs/supabase/discussions/15350

<div type='discussions-op-text'>

<sup>Originally posted by **vasanth-ravisankar** June 26, 2023</sup>
I'm trying to integrate textlocal sms service for phone number otp authentication. But the otp is not getting sent to the user when we trigger the supabase.auth.signInWithOtp api. 

But when I hit the textlocal api to send SMS with the same textlocal account and configurations, the SMS is getting sent as expected.

Supabase documentation on textlocal integrations is also very limited.

Have anyone faced this or similar issue already. Please help me to solve this issue. Giving the error message I found in Supabase auth logs.

{"auth_event":{"action":"user_recovery_requested","actor_id":"3725fc5e-6839-4e44-a982-06dd0e4ee6ee","actor_username":"919487073472","actor_via_sso":false,"log_type":"user","traits":{"channel":"sms"}},"component":"api","error":"400: Error sending sms OTP: \u003cnil\u003e","level":"info","method":"POST","msg":"400: Error sending sms OTP: \u003cnil\u003e","path":"/otp","referer":"","remote_addr":"103.87.106.7","time":"2023-06-26T07:41:41Z","timestamp":"2023-06-26T07:41:41Z"}</div>

**Comment by Srini-B** [comment]
is the message body formatted according to supabse standard, can't use what you see on textlocal
