### ISSUE TITLE
Keep getting logged out (browser admin dashboard)

### ISSUE THREAD

**Issue by Filsommer** [supabase/supabase#15355]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I get logged out too often from the browser admin dashboard, is that normal? At irregular intervals too - sometimes 3 times within 20 minutes, sometimes the sessions last much longer.
@silentworks mentioned that I'm not alone on this. He suggested that I should open a ticket/issue.

## To Reproduce

1. Go to https://supabase.com/ 
2. Sign in to your project and go the Table Editor (open any table)
3. Do stuff, and occasionally change tabs to work on other stuff
4. Come back to supabase tab and often get logged out.

## Expected behavior

Sessions should last longer (at least one hour) and be more consistent. Ideally we could configure the session time.

## System information

- OS: macOS
- Browser (if applies): Chrome 114.0.5735.133
- Version of supabase-js: Not relevant, issue is in browser
- Version of Node.js: Not relevant, issue is in browser

**Comment by hf** [comment]
We're aware and trying to find the underlying issue. Would you mind sharing your physical location or your primary Interner location if using a VPN (continent, country or region in country)?

**Comment by renrut** [comment]
> We're aware and trying to find the underlying issue. Would you mind sharing your physical location or your primary Internet location if using a VPN (continent, country or region in country)?

@hf I'm experiencing this as well

Location: Western North Carolina, USA
Browser: Chrome 114.0.5735.134 (64-bit)
OS: Windows 10

I do have uBlock Origins installed which I just disabled and can report back if that makes a difference...

**Comment by Filsommer** [comment]
@renrut that's a good observation! I also use uBlock Origin.
Location: Saarland, Germany

I'm not using VPN when this happens

**Comment by renrut** [comment]
Seems much better for me with uBlock disabled. Haven't had to re-login today.

**Comment by Filsommer** [comment]
After testing for 1 entire day, I can also confirm that disabling uBlock Origin seems to solve the issue. 
FYI @silentworks

**Comment by Filsommer** [comment]
We can close this issue - eventually add this info to the docs?

**Comment by hf** [comment]
Yeah let's close the issue, but I'm installing uBlock Origin to see why this is the case. We've also seen logouts happen _very rarely_ with team members internally that don't use uBlock Origin, so there's something going on.
