### ISSUE TITLE
Main site: [a11y] concerns: Excessive use of <div> elements on homepage

### ISSUE THREAD

**Issue by Olaleye-Blessing** [supabase/supabase#15380]
## Describe the bug
The homepage currently relies heavily on `div` elements for structuring its content. This excessive use of `div` elements poses significant accessibility concerns and can hinder the optimal experience for users relying on assistive technologies.

Semantic HTML elements play a vital role in ensuring accessibility for users.

By replacing some of the `div` elements with appropriate semantic elements, such as `header` and `section`, and others, the homepage can provide a clearer and more meaningful structure for assistive technologies.

## Expected behavior
The homepage should be structured with semantic HTML tags.

## Additional context

Other pages like the [blog page](https://supabase.com/blog) have this problem.

**Comment by gitryder** [comment]
@MildTomato I'd like to work on this

**Comment by gregnr** [comment]
Good call out @Olaleye-Blessing! @gitryder feel free to open a PR and link back to this issue

**Comment by gitryder** [comment]
I've started working on this. Will open a PR once done

**Comment by MildTomato** [comment]
Closing for now as the pages are getting redone fairly regularly.
