### ISSUE TITLE
Email templates: Unable to use `<head>` tag

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/supabase#15408]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When submitting an email template using the `<head>` tag, the `<head>` tag and all elements within are stripped.

## Expected behavior

The email template should not be modified when submitted at all.

## Additional context

There is much more widespread support for usage of `<style>` elements in the [`<head>` tag](https://www.campaignmonitor.com/css/style-element/style-in-head/) than in the [`<body>` tag](https://www.campaignmonitor.com/css/style-element/style-in-body/).

The behavior of email templates validation seems to have changed: it didn't use to strip the `<head>` tag and other inner tags. Is there any reason for the change?

Related: https://github.com/supabase/supabase/issues/13764

**Comment by ivanbrykov** [comment]
Same problem with <html> tag which actually affects deliverability. I'm getting this problem with my emails: HTML_MIME_NO_HTML_TAG. Which results in increased spam scores.

**Comment by martinparets** [comment]
really frustrating. having full control over the email's HTML is critical to producing nicely-designed emails that work in the myriad of available email clients.

**Comment by kangmingtay** [comment]
hi @martinparets. @ivanbrykov, @bnjmnt4n, just an update, we've recently deployed a change that makes this possible now!
