### ISSUE TITLE
Add links to all of our client libs from Dashboard project home screen

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#15420]
We only list these 3 client libs on the project home screen now. We should add 

<img width="1381" alt="CleanShot 2023-06-28 at 12 26 30@2x" src="https://github.com/supabase/supabase/assets/105593/2339c404-e3fd-4f6a-8233-f065d69aaa4d">

We should add the rest from https://supabase.com/docs
<img width="280" alt="CleanShot 2023-06-28 at 12 27 30@2x" src="https://github.com/supabase/supabase/assets/105593/580e6dcf-5cf0-4539-bddb-1ccc56962610">

Likely need to change this to a 2-up grid.

**Comment by saltcod** [comment]
@Hallidayo gonna grab this one!

**Comment by Hallidayo** [comment]
@saltcod - Cheers
