### ISSUE TITLE
Wrong navigating on Google Auth Page

### ISSUE THREAD

**Issue by PatrykKuniczak** [supabase/supabase#15459]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When i click on "Configuration" (Watch video} on:
https://supabase.com/docs/guides/auth/social-login/auth-google#configuration

I was navigated every time to the same section, although i click other "Configuration" button, and all of that had effect after click, like animation on text, i think all of this buttons have the same effect.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Go on:
https://supabase.com/docs/guides/auth/social-login/auth-google#configuration

And see this video:

https://github.com/supabase/supabase/assets/64608510/3f70b435-f33e-4646-aff9-f18cf5e21d90

For next steps.

## Expected behavior

Navigate properly.

## System information

- OS: Windows 11
- Browser: Chrome 114.0.5735.198
- Version of supabase-js: Probalby latest, that's your side :)
- Version of Node.js: Like above

**Comment by gregnr** [comment]
This is a good find @PatrykKuniczak. I'm a bit surprised that our slugifier isn't making these unique (usually would add a number suffix for each duplicate slug, eg `overview-2`, `overview-3`, etc).

For now the best solution is probably to add a custom slug to each overview based on their section, like we do here:
https://github.com/supabase/supabase/blob/cb28597e77f71f7f9939ec8a537d9c5b439314ec/apps/docs/pages/guides/api.mdx#L29

eg. something like:
```markdown
### Configuration [#configuration-web]
```

Would you be interested in creating a small PR for this?
https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/auth/social-login/auth-google.mdx#L58

**Comment by PatrykKuniczak** [comment]
> This is a good find @PatrykKuniczak. I'm a bit surprised that our slugifier isn't making these unique (usually would add a number suffix for each duplicate slug, eg `overview-2`, `overview-3`, etc).
> 
> For now the best solution is probably to add a custom slug to each overview based on their section, like we do here:
> 
> https://github.com/supabase/supabase/blob/cb28597e77f71f7f9939ec8a537d9c5b439314ec/apps/docs/pages/guides/api.mdx#L29
> 
> eg. something like:
> 
> ```
> ### Configuration [#configuration-web]
> ```
> 
> Would you be interested in creating a small PR for this? https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/auth/social-login/auth-google.mdx#L58

I'm extremally busy now, cause i staring my first job, as a full stack dev and for now i can't help, but i'm open to participate on open source projects, like this, on near future :)

**Comment by takpen** [comment]
Hi @gregnr @PatrykKuniczak, 

I have created a PR to address this issue. 

I also found that the Apple Auth page (https://supabase.com/docs/guides/auth/social-login/auth-apple) had the same navigation problem. So, I made the same changes to fix the navigation on the Apple Auth page as well.

Please review the PR and provide any feedback or suggestions. Thank you!

**Comment by gregnr** [comment]
Fixed in #15503
