### ISSUE TITLE
The same code。  bug？？

### ISSUE THREAD

**Issue by shiliu2023** [supabase/supabase#15473]
def get_user_brains(self, user_id):
        print("1111:",user_id)
        print("11118:",self)
        response = (
            self.commons["supabase"]
            .from_("brains_users")
            .select("id:brain_id, brains (id: brain_id, name)")
            .filter("user_id", "eq", user_id)
            .execute()
        )
        print("11119:",response)
        return  response.data 

The same code, when executed with Supabase SaaS version, prints "11119" as expected. However, when executed with the Docker version of Supabase, it does not reach the line "print("11119:", response)". Both versions of the code print "11118: id=None name='Default brain' status='public' model='gpt-3.5-turbo-0613' temperature=0.0 max_tokens=256 max_brain_size=1569852428800 files=[]". What could be the reason for this difference?

**Comment by gregnr** [comment]
Hey @shiliu2023! Some more details will help here. Can you provide your table schema and steps to reproduce?

**Comment by KevinBrolly** [comment]
Hey there,

Looks like this issue has gone stale, so I am going to close it. If you are still having issues let us know and we can re-examine.
