### ISSUE TITLE
Doc for count doesn't work

### ISSUE THREAD

**Issue by mankuthimma** [supabase/supabase#15478]
# Improve documentation

This should be the actual query which works for count 

const { error, data, count } = await supabase
    .from('table')
    .select('*', { count: 'exact' })

whereas the doc shows this currently

(Refer https://supabase.com/docs/reference/javascript/select)

<img width="1090" alt="image" src="https://github.com/supabase/supabase/assets/220319/47281816-ea33-4f25-b40e-18e2245a84eb">

This is answered in this issue 
https://github.com/orgs/supabase/discussions/517

**Comment by GaryAustin1** [comment]
Actually both are correct.  The example in the doc is if you just want the count returned with no data.  Your approach returns data and the count.

**Comment by lalitkumawat1m** [comment]
Hey @mankuthimma,
I have created pr for this issue. Could you please review it and give feedback to me? Thanks

**Comment by burggraf** [comment]
As the linked PR has been closed we can also close this thread.  Thanks.
