### ISSUE TITLE
Examples points to the outdated and archived examples

### ISSUE THREAD

**Issue by joshdance** [supabase/supabase#15483]
# Improve documentation

## Link 

https://supabase.com/docs/guides/resources/examples

## Describe the problem

The examples link to the wrong Github repo.

## Describe the improvement

The example for a Nextjs Todo list should point to this repo: 
https://github.com/supabase/supabase/tree/master/examples/todo-list/nextjs-todo-list

but is linked to the old archieved one: https://github.com/supabase/examples-archive/tree/main/supabase-js-v1/todo-list/nextjs-todo-list

**Comment by mughalfrazk** [comment]
Hey @joshdance, I am interested in this issue

**Comment by gregnr** [comment]
Go ahead @mughalfrazk!

**Comment by joshdance** [comment]
@mughalfrazk nice! I didn't see your message until after I made a PR as well. 😅 https://github.com/supabase/supabase/pull/15488 

Don't know how it works, should I close mine?

**Comment by mughalfrazk** [comment]
@joshdance Its your call i guess, but i'd say let me have this. 😅

**Comment by joshdance** [comment]
closed mine. :)
