### ISSUE TITLE
From Discussions - Where to find (or create) Site urls and Additional Redirect URLs - Flutter

### ISSUE THREAD

**Issue by nejat-njonjo** [supabase/supabase#15486]
### Discussed in https://github.com/orgs/supabase/discussions/5947

<div type='discussions-op-text'>

<sup>Originally posted by **devberkay** March 17, 2022</sup>
Hey, i am newbie on Supabase and following the official documents for authentication procedures for flutter and i couldn't understand how to find (or create) site urls and additional redirect urls for my mobile app : 

![image](https://user-images.githubusercontent.com/81699676/158809768-2cbf0de4-168e-4c64-a226-049220203f97.png)

here is the official flutter example on authentication via deeplinks and it edits **additional redirect urls** but doesn't explain where to find : [https://supabase.com/docs/guides/with-flutter](url)

here is another official document that explains how to  authenticate via email & password and it edits **site urls** 
but doesn't explain where to create & find : https://supabase.com/docs/guides/auth/auth-email 
</div>

**My Work around to this problem**
[You can Read My answer Here](https://github.com/orgs/supabase/discussions/5947#discussioncomment-6327847)

**Comment by nejat-njonjo** [comment]
I think the problem is with Redirect URLs

**Comment by GaryAustin1** [comment]
You probably should provide more info on what this post is about.  If you have question then discussions or Supabase Discord it the best place.   Normally issues is used for reporting issues and not seeking help.

SiteUrl and redirectURLs have to be set in the dashboard.  Then in your code you use the redirectUrl's to redirect back to your app as needed.   The SiteUrl is actually not that relevant to the process and is just used as a default if your redirect URL's in the dashboard do not match those coming from your app.
