### ISSUE TITLE
Filter Related list to not show current blog post 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#15484]
supabase.com/blog/[post] is recommending the current post in the Related Posts sidebar. We should filter this list to not include the current post.

Example post
https://supabase.com/blog/chatgpt-plugins-support-postgres

Showing up in the sidebar
![CleanShot 2023-06-30 at 13 18 55@2x](https://github.com/supabase/supabase/assets/105593/658fbc40-e85e-4457-89d5-a23d9ea10d2a)

**Comment by ddanielcruzz** [comment]
Hey I'm interested in contributing to the project, can I take this?

**Comment by gregnr** [comment]
Yes please @ddanielcruzz!

**Comment by ddanielcruzz** [comment]
Done! @gregnr 😀 -> https://github.com/supabase/supabase/pull/15491

**Comment by NIKHILNAIR21** [comment]
is it still open? I'm interested in contributing to the project,

**Comment by Shaurysingh716** [comment]
I want to contribute in this, is this still open?

**Comment by ddanielcruzz** [comment]
@NIKHILNAIR21 @Shaurysingh716 I already took this and have an open PR -> https://github.com/supabase/supabase/pull/15491

**Comment by Nikhil743** [comment]
Hey, @saltcod would like to work on this issue.
could you assign it to me?

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source, this is my first time can you assign me this task.
