### ISSUE TITLE
Generate and download types feature does not work in self-hosted version of Supabase

### ISSUE THREAD

**Issue by senguendk** [supabase/supabase#15502]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the "Generate and download types" button, a toast pops up with the HTML content of a 404 page (see screenshow below). No types are being generate nor downloaded.

<img width="1271" alt="Bildschirmfoto 2023-07-01 um 19 46 45" src="https://github.com/supabase/supabase/assets/1299807/82cf6766-a222-48a6-ab73-dbae5d2e9452">

Investigating further it looks like the GET path/URI is malformed:

<img width="597" alt="Bildschirmfoto 2023-07-01 um 19 51 40" src="https://github.com/supabase/supabase/assets/1299807/21db3797-fb20-4405-b9b9-b3a937498673">

## To Reproduce

1. Install Supabase through git
2. Run docker compose up -d
3. Create table
4. Go to "API" section
5. Scroll down to "Generating types"
6. Hit "Generate and download types" button

## Expected behavior

I would expect to be able to download generated types.

## Screenshots

<img width="1271" alt="Bildschirmfoto 2023-07-01 um 19 46 45" src="https://github.com/supabase/supabase/assets/1299807/82cf6766-a222-48a6-ab73-dbae5d2e9452">

<img width="597" alt="Bildschirmfoto 2023-07-01 um 19 51 40" src="https://github.com/supabase/supabase/assets/1299807/21db3797-fb20-4405-b9b9-b3a937498673">

## System information

- macOS and Linux
- Firefox
- Version of supabase-js: Latest git master
- Version of Node.js: Which ever version the docker images use

## Additional context

Nothing to add.

**Comment by NINNiT** [comment]
We are experiencing the same problem. 
``FYI, as a workaround, the CLI allows passing the --db-url flag for certain commands, including type generation.

npx supabase gen types typescript --db-url  postgres://<user>:<password>@<host>:<port>/<db>

**Comment by kiwicopple** [comment]
this one is closed by https://github.com/supabase/supabase/pull/16863 🎉 

(it will roll out in the next Docker image)
