### ISSUE TITLE
Outdated React Turnstile captcha documentation

### ISSUE THREAD

**Issue by pschaub** [supabase/supabase#15517]
The [documentation to integrate Turnstile captcha into a react project](https://supabase.com/docs/guides/auth/auth-captcha#add-the-captcha-frontend-component) is outdated.

The documentation explains to use the `onVerify` prop to receive the captcha token.
But the [current documentation of the used library](https://docs.page/marsidev/react-turnstile/props) does not provide any prop named `onVerify`.

**Comment by gregnr** [comment]
Fixed in #15586
