### ISSUE TITLE
local cli guide supabase stop

### ISSUE THREAD

**Issue by megacherry** [supabase/supabase#15512]
# Improve documentation

## Link 

1. https://supabase.com/docs/guides/getting-started/local-development
2. https://supabase.com/docs/reference/cli/supabase-stop

## Describe the problem

The first link says: "You can use the [supabase stop](https://supabase.com/docs/reference/cli/usage#supabase-stop) command at any time to stop all services and reset your local database. Use supabase stop --backup to stop all services without resetting your local database."

The second link says: "All Docker resources are maintained across restarts. Use --no-backup flag to reset your local development data between restarts."

## Describe the improvement

The default behavior should be described the same in both places.

**Comment by gregnr** [comment]
@supabase/cli my understanding is that the CLI no longer resets your DB on `stop` + `start`, is that correct?

**Comment by encima** [comment]
Closing as this was done (although not linked to a PR)
