### ISSUE TITLE
Different behaviour in self-hosted docker & platform -- Unable to upsert

### ISSUE THREAD

**Issue by ludwigHoon** [supabase/supabase#1552]
# Bug report

## Describe the bug
Unable to upsert in self-hosted version

## To Reproduce
// Self-hosted --> error
let result = await  s_hosted.from('todos').select()
console.log(result)
result.body[0].done = false
result.body[0].task = 'asdasd'
let reply = await s_hosted.from('todos').insert(result.data, {upsert:true})
let resul2 = await s_hosted.from('todos').select()

## Expected behavior
Similar behaviour in self-hosted & platform

## Screenshots
![image](https://user-images.githubusercontent.com/30918181/118099439-d23e4880-b407-11eb-94ce-5b0b1ec2fec3.png)

## System information

- OS: Ubuntu
- from docker: "supabase_db:latest"
   "Metadata": {
            "LastTagTime": "2021-05-13T07:39:04.169578651Z"
        }

**Comment by kiwicopple** [comment]
Hey @ludwigHoon - can you please share the table schema that you're using on both of these?

I assume also that this using the same supabase-js library for both self-hosted and remote too?

**Comment by ludwigHoon** [comment]
Hey @kiwicopple, this is the table schema for the self-hosted
create table public.todos (
  id serial primary key,
  done boolean not null default false,
  task text not null,
  due timestamptz
);
On the platform, I used the UI to define the table, used text for 'id' and date for 'due'.

**Comment by soedirgo** [comment]
I think this has to do with the [schema cache](https://postgrest.org/en/stable/api.html#upsert), once I restart the container the upsert went through. Alternatively you could do [schema reloading](https://postgrest.org/en/stable/admin.html#schema-reloading), though it just timeouts all consequent PostgREST requests when I tried it, but maybe that's just me.

**Comment by ludwigHoon** [comment]
Hi @soedirgo, thanks! I restarted and it worked. I am quite new to docker, though, can you tell me how I can send a SIGUSR1 signal to postgrest? I used the supabase-cli to start my instance.

**Comment by soedirgo** [comment]
You can try the command in the schema reloading link:

```sh
docker kill -s SIGUSR1 supabase-rest
```

There's an open issue about schema reloading on the CLI repo https://github.com/supabase/cli/issues/26 but I'm not sure yet how this should be done. (A dedicated command? On every migration? Etc.)

**Comment by ludwigHoon** [comment]
@soedirgo Ah, great. Thanks a lot, I will follow the cli enhancement.
