### ISSUE TITLE
Supabase AUTH verifying email issues

### ISSUE THREAD

**Issue by gabrielsestrem** [supabase/supabase#15532]
Supabase Auth on the email verify redirection URL (confirming signup) it's giving an error.

Confirm URL: https://PROJECTID.supabase.co/auth/v1/verify?redirect_to=https://www.myurl.com.br&token=TOKEN&type=signup/dashboard

Redirected to: https://myurl.com.br#error=invalid_request&error_code=400&error_description=Invalid+email+verification+type

## To Reproduce

1. Signup
2. Click in the {{ .ConfirmationURL }} from the confirm signup email

## Expected behavior

It should validate and redirect correctly

**Comment by KevinBrolly** [comment]
@GaryAustin1 FYI we added a PR which ensures the order of query parameters is maintained here - https://github.com/supabase/gotrue/pull/1161

**Comment by gabrielsestrem** [comment]
I already fixed in my side altering the order of the parameters
