### ISSUE TITLE
Local studio does not show buckets created with SQL and cannot create new buckets

### ISSUE THREAD

**Issue by isaacfink** [supabase/supabase#15534]
- [x] I confirm this is a bug with Supabase, not with my own application. 
I don't have any rls rules or anything touching buckets in my migrations
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions]

## Describe the bug

I have a local supabase project I am using for local development before deploying to supabase, it was working fine until recently (don't remember which version) but it recently started causing issues with buckets in studio, there are two problems when I create a bucket in a migration using this
```sql
INSERT INTO storage.buckets(id, name, public) VALUES ('music-tracks', 'music-tracks', TRUE);
```
I get the row in SQL but not in the buckets ui, it just shows No buckets availableAnd when I try to create a bucket in the studio UI I get the rls error `new row violates row-level security policy`

Additionally when I go to the storage page in studio I get a toast with a 500 error, the UI works but the request to localhost:54323/api/storage/default/buckets fails and there is no error code just the message

I am using the cli through npx and I ran the following commands before opening the studio link

```bash
npx supabase@latest stop
npx supabase@latest db reset
npx supabase@latest start
```

## Screenshots

![image](https://github.com/supabase/supabase/assets/46644190/81a88334-c593-4ab8-85c3-ad62930fc2f0)

## System information

- OS: macos
- Browser: brave (chromium)
- Version of supabase-js: cli version `1.75.3`

## Additional context

There is an open issue about this but it seems like it works for other people and the exact error was different, might be related though
https://github.com/supabase/supabase/issues/15385

I am getting this in the container logs for rest

```
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
```

<details>
  <summary>And this in the storage container</summary>
  
  ```
DBError: new row violates row-level security policy
    at DBError.fromDBError (/app/dist/storage/database/knex.js:416:16)
    at Function.<anonymous> (/app/dist/storage/database/knex.js:350:31)
    at Function.emit (node:events:513:28)
    at Function.emit (node:domain:489:12)
    at Client_PG.<anonymous> (/app/node_modules/knex/lib/knex-builder/make-knex.js:299:10)
    at Client_PG.emit (node:events:525:35)
    at Client_PG.emit (node:domain:489:12)
    at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:300:14) {
  statusCode: 403,
  error: 'Unauthorized',
  originalError: error: 
          SELECT
            set_config('role', $1, true),
            set_config('request.jwt.claim.role', $2, true),
            set_config('request.jwt', $3, true),
            set_config('request.jwt.claim.sub', $4, true),
            set_config('request.jwt.claims', $5, true),
            set_config('request.headers', $6, true),
            set_config('request.method', $7, true),
            set_config('request.path', $8, true);
       - permission denied to set role "service_role"
      at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 110,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'guc.c',
    line: '11538',
    routine: 'call_string_check_hook'
  },
  metadata: undefined
}
```
</details>

**Comment by sweatybridge** [comment]
Could you try `npx supabase@latest stop --no-backup`? This flag removes any existing db volumes so start can work with a clean state.

Otherwise I'm unable to reproduce locally.

**Comment by isaacfink** [comment]
@sweatybridge That fixed it, thanks
