### ISSUE TITLE
Python library ModuleNotFoundError

### ISSUE THREAD

**Issue by uncarlo** [supabase/supabase#15544]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

When trying to run supabase from Python3 I get this error:
ModuleNotFoundError: No module named 'supabase'

Even right after installing with pip3 install supabase
I also tried with pip3 install supabase-py

but that seemed to cause even more problems

## To Reproduce

Simply install and add this line:

from supabase import create_client, Client

## Expected behavior

It should get the library after I install it.

## Screenshots

![image](https://github.com/supabase/supabase/assets/6371158/c77769d1-43ca-4405-8743-90e223aaf1c4)

## System information

- OS: macOS
- Version of Node.js: 20.2.0
- Python: 3.11.4

**Comment by gregnr** [comment]
cc @J0 in case you have any ideas

**Comment by J0** [comment]
Hey,

Thanks for the query!  could you try creating a block in Jupyter and then run `!pip3 install supabase` ? The notebook might be in a different `virtualenv` or similar.

Let me know!

**Comment by KevinBrolly** [comment]
Hi there,

It appears this issue has gone stale, so I am going to close it. If you are still having issues do let us know and we can re-open.

**Comment by TahseenSust** [comment]
I faced the same issue and it was fixed after I restarted my PC 🤔
