### ISSUE TITLE
is there a security issue in the storage management example provided by supabase?

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#15555]
### Discussed in https://github.com/orgs/supabase/discussions/15554

<div type='discussions-op-text'>

<sup>Originally posted by **devhandler** July  4, 2023</sup>
in the example provided by supabase, the delete_storage_object is created in the public space, which means it can be called via rpc.

the pg extension uses the service role key to do the deletion, meaning it can bypass all the rls checks and the function security level is "definer". if users know urls of storage files and the existence of this rpc, they can directly rpc call this method and delete whatever files they want?

am i missing sth here or is it a real risk?

https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs#create-an-upload-widget
![image](https://github.com/supabase/supabase/assets/133625693/da00b3f4-b535-4eee-8fc1-4d8d9bfd7c04)
</div>

**Comment by GaryAustin1** [comment]
Was trying to move a user's discussion over here as an issue...
Did not know it would just create a new issue in my name.
@devhandler

**Comment by encima** [comment]
Hi @devhandler,
This is potentially an issue if improperly handled. The service key needs to be used for the API to be called successfully but you can revoke/limit the ability to call the function to select roles in order to prevent it being called.
