### ISSUE TITLE
Default self-hosting setup studio app doesn't support api url with path (for example fails to create users from studio)

### ISSUE THREAD

**Issue by devidw** [supabase/supabase#15553]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Self-hosting with Docker as documented with the default configuration will host the studio at the root domain and the other services under the `/proxy/` path.

However, the studio app itself doesn't seem to correctly respect the api endpoint to be a path and instead uses the origin/host of the URL set in `.env` for `SUPABASE_PUBLIC_URL`.

When I configure `SUPABASE_PUBLIC_URL=https://abc.com/proxy/` this will be parsed as `https://abc.com/` by the supabase studio app when the studio makes api calls.

Reference: https://github.com/supabase/supabase/blob/cef5f45d66d5360e05fa22af102d427ae8a39f0e/studio/pages/api/constants.ts#L6-L7

I noticed this behavior for the "add user" functionality, which - with the default, documented setup - will fail to post to `https://abc.com/auth/v1/admin/users` since the api is hosted under `https://abc.com/proxy/auth/v1/admin/users`

To workaround this issue we can separate the api and studio domains, so we end up with the api being hosted on a bare domain instead of under a path.

## To Reproduce

1. Setup self-hosted supabase as documented with studio under `abc.com` and rest under `apc.com/proxy`, configure the .env to point to the "correct" url endpoints
2. Go to '/project/default/auth/users' on self-hosted studio app
3. Click on 'add user' and fill in user details
4. See how the operation fails since the apps makes a req to the wrong url

## Expected behavior

- Studio app to understand paths in the api endpoint
- Or documentation that says that you can't use paths and don't suggest to host with paths as the api endpoint

**Comment by vincelwt** [comment]
Can confim, it seems the Studio ignores the external URL path set in `.env`
