### ISSUE TITLE
Changing Site URL sets hCaptcha as captcha provider

### ISSUE THREAD

**Issue by afermon** [supabase/supabase#15565]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I got captcha enabled on my project and Turnstile is configured as the provider. However, if I change my Site URL in the Auth configuration it automatically switches the captcha provider to hCaptcha automatically.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `Project Settings \ Auth`
2. Enable Captcha protection and Turnstile as the provider and save the changes.
3. Go to `Authentication \ URL Configuration`
4. Update the Site URL and save changes
5. Go to `Project Settings \ Auth` and the captcha provider will now be hCaptcha

## Expected behavior

The captcha provider should remain the same after a Site URL change

## Screenshots
NA

## System information
NA

## Additional context
NA

**Comment by J0** [comment]
Hey  @afermon ,

This probably arises from hcaptcha being the default on submission 
 - https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Auth/SiteUrl/SiteUrl.tsx#L56
We'll look into a fix, apologies for the inconvenience caused.
