### ISSUE TITLE
Doesn't work with Windows via npm

### ISSUE THREAD

**Issue by Sawtaytoes** [supabase/supabase#15562]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I installed the Supabase CLI via node (`yarn add supabase`) from version `1.68.6` to `1.75.3`. None have worked with Windows because the executable in Windows is named `/bin/supabase.exe`, not `/bin/supabase`.

I've had this issue myself when writing Unix-compatible Node.js apps on Windows. Look for `"win32"` in the OS type, and then look for `.exe` if that's true.

```sh
PS D:\server> yarn supabase  
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\server\node_modules\supabase\bin\supabase'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)    
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.15.0
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Be on a Windows machine.
2. Install the Supabase CLI `yarn add supabase`.
3. Run `yarn supabase`.
4. See error.

## Expected behavior

It should do whatever it's supposed to. I've never seen this work, and I only have Windows, so I don't know what it's supposed to actually do.

In my case, I wanna generate types for my Postgres tables. I would assume it does this when you run `supabase gen types typescript --project-id '$PROJECT_ID' --schema public` with the correct project ID.

## Screenshots

N/A

## System information

- OS: Windows
- Browser (if applies): Node.js
- Version of supabase-js: `1.75.3`
- Version of Node.js: `18.15.0`

## Additional Context

I'm on Yarn v3.

**Comment by CarlosBalladares** [comment]
I have the same issue with yarn 3.6.1. On a nextjs project.
```
  "devDependencies": {
    ... 
    "supabase": "^1.77.9"
  },
```

my .yarnrc.yml
```
yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: node-modules
```

```
$ yarn supabase start
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\code2\project_name\node_modules\supabase\bin\supabase'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by CarlosBalladares** [comment]
I think this could be an issue with the way yarn resolves supabase.  

```
$ yarn dlx supabase start
```

results in the same error but using npx works.


```
$ npx supabase start
supabase start is already running.
Run supabase status to show status of local Supabase containers.
```

**Comment by adamstoffel** [comment]
This is also an issue for me on yarn v4.0.2

```
> npx supabase
1.112.0
```

```
> yarn supabase -v
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'C:\Users\adam\Projects\pioneer_ai\web\node_modules\supabase\bin\supabase'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0
```

**Comment by encima** [comment]
This issue title is incorrect as Supabase CLI does work with `npm` on Windows (as does `npx`). This seems to be an issue with `yarn` and how it resolves executables. If this is occurring for you, please open an issue on the `yarn` repo 🙏

**Comment by TimMensch** [comment]
This is totally something you guys could fix. It might even be a bug on your end that npm/npx works around.

Just ran into this bug today. You're wasting the time of users who use yarn, which is a lot of us. Please fix.
