### ISSUE TITLE
Whatsapp code vertification no longer works

### ISSUE THREAD

**Issue by Nielsien** [supabase/supabase#15575]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I tried to create a vertification code login with Whatsapp and Twillio.
Only I ran into some problems.

The first problem is that Whatsapp rejects all authentication templates due to recent changes, unless it complies exactly with their requirements.

https://support.twilio.com/hc/en-us/articles/15596541039771-New-WhatsApp-Authentication-Template-Requirements-May-2023 

Which is why you now have to use the twillio Beta API to create templates and are you no longer able to create one on their dashboard.

https://www.twilio.com/docs/content/whatsappauthentication

So all code authentication with Whatsapp now looks like this:
![image](https://github.com/supabase/supabase/assets/15873069/acb6c9be-5968-465b-96d3-0056f8ccf0fa)

After creating a whatsapp template and getting it approved, I ran into this sentence in the docs.

![image](https://github.com/supabase/supabase/assets/15873069/7a75b4d2-3643-4abb-b7b2-6bca61b7c04d)

Note that the message template submitted to Twilio must exactly match the SMS Body entered on the Supabase
dashboard.

If I take take my format which twillio generated:

`{ "whatsapp/authentication": {
            "body": "{{1}}",
            "add_security_recommendation": true,
            "code_expiration_minutes": 40,
            "actions": [
                {
                    "type": "COPY_CODE",
                    "copy_code_text": "Copy Code"
                }
            ]
        }}`

And then set the format of supabase like this:

![image](https://github.com/supabase/supabase/assets/15873069/f171167a-7375-41c6-95ee-e91f6dc095df)

I get the following error when asking for a login code using the supabase client:

AuthApiError: Error sending sms OTP: nil

I don't really know how to connect this new Beta format to supabase and supabase can't seem to find the whatsapp template.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create Whatsapp account on twillio
2. Add beta auth format
3. Set format in supabase
4. Login with code using channel whatsapp

## System information

- OS: Windows
- Browser chrome
- Version of supabase-js: 6.0.2

**Comment by Nielsien** [comment]
Also worth noting that at this given date old vertification formats are still working on Whatsapp.
But after Oct. 2nd (Sep. 1st for formats with emoji's/urls) all Whatsapp formats must comply to this new format or will get rejected.

**Comment by J0** [comment]
Hey @Nielsien,

Auth team here - thanks for reporting the issue and for patiently waiting. The message body needs to exactly match what's on the Supabase dashboard only when using the `Body` field. If you are using a Content Template like `whatsapp/authentication` you can register the [`ContentSID`](https://supabase.com/docs/guides/auth/phone-login/twilio#whatsapp-otp-logins) field without much regard for the Message field. The Message field will be disregarded when using Twilio Programmable Messaging via the WhatsApp channel.

Note that Twilio will only support Content Templates for WhatsApp after 1st November so we advise users to move over to use Content Templates if they haven't done so. More information can be found [in this article](https://support.twilio.com/hc/en-us/articles/19816296822299-Upgrading-WhatsApp-Templates-to-Content-Templates)

Hope this helps and let us know if there are any questions
