### ISSUE TITLE
Password weak messages need to be friendlier and shorter

### ISSUE THREAD

**Issue by Saunved** [supabase/supabase#1557]
# Bug report
This is not as much a bug as it is a user experience issue, but this seems like the best label to pick out of the available ones.

## Describe the bug
The messages for weak passwords are a little too condescending and can be made to sound friendlier. E.g. For a weak password, this is the message shown:

![ux_language_supabase](https://user-images.githubusercontent.com/16450673/118167958-ed7b7900-b444-11eb-885d-d3e633087d9a.png)

I can understand the intent behind doing this, but I feel like this is not necessary and the hints can be made much friendlier and easier to read.

## To Reproduce

(1) Create a new project 
(2) In the database password field, type in a weak password, such as "hello" or "abcabc"

## Expected behavior
(1) The messages should be friendlier instead of being so overtly critical of the user. Although I can see why this could be seen as helpful or funny, it doesn't really create a good impression on the user.
(2) The length of the hint is too long. Nobody wants to read so much when setting a password
(3) In the example above, the text should most definitely not say "Pathetic". **A product's language should always be forgiving and understanding of the user. It should nudge them in the right direction instead of harshly pointing out their mistakes.** Also, all of Supabase's users are developers. They understand the importance of strong passwords.
(4) E.g. The messages could look like this: 
(a) _Avoid repeating words in your password._
(b) _This is a common password and easy to guess. Try something stronger._
(c) _You should mix up letters, numbers, and symbols in your password to make it stronger._
(d) _Your password needs to be more than 8 characters long._

## System information
NA

## Additional context
NA

**Comment by MildTomato** [comment]
thanks for the issue write up @Saunved 👍 

I reviewed some of the language and amended it.
the warning messages are a bit more clearer now but we may need to keep improving this in the future, with more specific instructions on how to make a stronger password.

changes should go live later today or tomorrow.
