### ISSUE TITLE
sms Provider twilio-verify could not be found

### ISSUE THREAD

**Issue by Kypsis** [supabase/supabase#15570]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to use the new Twilio Verify feature in Supabase the following error message gets returned when attempting to sign in with OTP: `error: AuthException(message: Error sending sms: sms Provider twilio-verify could not be found, statusCode: 400)`

## To Reproduce

Try to sign in in Flutter with `client.auth.signInWithOtp(phone: phoneNumber)`

## Expected behavior

The method succeeds and OTP SMS is sent.

**Comment by J0** [comment]
Hey @Kypsis,

Thanks for flagging this, the frontend should be sending over twilio_verify instead of twilio-verify. Putting in a fix now

**Comment by mrjackdavis** [comment]
For posterity (I mentioned this in the PR), since the PR removed the option for Twilio Verify, I manged a HTTP request and manually set `twilio_verify`. But now I get the error

```
AuthApiError: Error sending confirmation sms: sms Provider twilio_verify could not be found
```

So seems like `twilio_verify` isn't supported on Supabase backend either 🤔 

I'm wondering if it ever worked... but there is docs for it 🤔

**Comment by J0** [comment]
Hey all,

Apologies for the late update - we temporarily removed the provider as  we realized the Auth service has yet to be updated to support the change. I'm really sorry for the inconvenience caused - the Auth service should be updated this week and it should be reinstated early next week.

**Comment by Kypsis** [comment]
What is status with the Twilio Verify now that you seem to have merged all of the supporting features?

**Comment by J0** [comment]
Thanks for the patience everyone - It is released on prod and good to go. Please let me know if there are any issues. Thanks!

**Comment by Kypsis** [comment]
I can confirm that the Twilio Verify now works but with a caveat, no way to send the **appHash**. Created a new bug ticket [https://github.com/supabase/supabase/issues/16041](https://github.com/supabase/supabase/issues/16041).

From my pov this current ticket is resolved.

**Comment by J0** [comment]
@Kypsis Thanks for the confirmation! We'll take a look at the issue surrounding appHash when a slot frees up

**Comment by J0** [comment]
Hey @shawnmclean,

This is a good point 

You may wish to set it to:

```
[auth.sms.twilio_verify]
enabled = true
account_sid = ""
message_service_sid = ""
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_VERIFY_AUTH_TOKEN)"
```
More generally, you'll want to  substitute TWILIO with TWILIO_VERIFY for any env var you use (e.g. SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN would become `SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN`)

**Comment by jijkbird** [comment]
Have you found a solution?

**Comment by luisfontes** [comment]
Does anyone have succeeded in making Twilio verify work in the local environment?

I've made it work in one of my supabase accounts but no luck while running on local, same credentials.

**Comment by djshubs** [comment]
> Does anyone have succeeded in making Twilio verify work in the local environment?
> 
> I've made it work in one of my supabase accounts but no luck while running on local, same credentials.

@luisfontes I haven't tested it recently, but I was able to get it working using the following settings in my config.toml file:

```
# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio_verify]
enabled = true
account_sid = "env(SUPABASE_AUTH_TWILIO_ACCOUNT_SID)"
message_service_sid ="env(SUPABASE_AUTH_TWILIO_MESSAGE_SERVICE_SID)"
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_TWILIO_AUTH_TOKEN)"
```

My environment variables are in `.env` file to get it to work. Didn't work by putting them `.env.local` 

Next, make sure you update your supabase images. 

I haven't tested recently, so mine might not work either but just wanted to provide some insights.

**Comment by luisfontes** [comment]
Thanks for answering @djshubs!

I couldn't make it work so I created #19814.
