### ISSUE TITLE
Schema visualizer 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#15585]
You can use https://supabase-schema.vercel.app/ to visualize your table schemas. 
It would be amazing to have this in the dashboard, probably at the https://supabase.com/dashboard/project/_/database/schemas route.  

Looks like this original version was built with Vue. 
We could leverage https://reactflow.dev/ for this. 

If anyone is interested in working on this, reach out. We'd love to help make it happen. 

<img width="539" alt="CleanShot 2023-07-05 at 16 47 30@2x" src="https://github.com/supabase/supabase/assets/105593/80320545-5565-40c6-aaeb-2754b9def13a">

**Comment by AdityaTD** [comment]
I may not be able to take full control, but happy to help if someone wants to start and needs help with parts of the PR.

This would be an amazing addition! 😍

**Comment by pedrovrima** [comment]
Hey @AdityaTD @saltcod I am up for it as well

**Comment by saltcod** [comment]
We don't have a specific assignment process, so if someone wants to "claim" it as they get started, please feel free!

**Comment by pedrovrima** [comment]
Cool - I am starting to take a look at that then. @saltcod is there an easy way to get a table schema data on my local run of dashboard? I see the john doe user and the default org/project, but no databases or tables. Thx

**Comment by rbkayz** [comment]
Happy to collaborate on this. Can we use the PgAdmin ERD tool for this? It's quite elegant (see example below)

![image](https://github.com/supabase/supabase/assets/62215539/1df4c643-8af8-44dd-aa23-5bc8495be8aa)

Some feature requests:

- Support for multiple schemas
- Default tables included (auth.users, storage.objects)
- Show nullable columns
- Show unique indexes
- Show composite primary keys

**Comment by saltcod** [comment]
Hey @rbkayz thanks for this — looks quite cool. 

But where this will live in the Dashboard,  it would need to be built with React. 

https://reactflow.dev/  looks promising for this.

**Comment by AdityaTD** [comment]
Think we could ask @zernonia to help with this since they are who built https://github.com/zernonia/supabase-schema?

**Comment by pedrovrima** [comment]
agree @AdityaTD

**Comment by pedrovrima** [comment]
For those interested, I started working on this in this [branch](https://github.com/pedrovrima/supabase/tree/feat/add-schema-diagram). Got react-flow working, and am getting the payload structure and data transformation from supabase-schema to work with.


@saltcod this is the data structure fetched by supabase-schema (among other objects):

`{
    "author": {
        "required": [
            "id"
        ],
        "properties": {
            "id": {
                "description": "Note:\nThis is a Primary Key.<pk/>",
                "format": "bigint",
                "type": "integer"
            },
            "created_at": {
                "default": "now()",
                "format": "timestamp with time zone",
                "type": "string"
            },
            "name": {
                "format": "character varying",
                "type": "string"
            }
        },
        "type": "object"
    },
    "posts": {
        "required": [
            "id"
        ],
        "properties": {
            "id": {
                "description": "Note:\nThis is a Primary Key.<pk/>",
                "format": "bigint",
                "type": "integer"
            },
            "created_at": {
                "default": "now()",
                "format": "timestamp with time zone",
                "type": "string"
            },
            "title": {
                "format": "character varying",
                "type": "string"
            },
            "content": {
                "format": "text",
                "type": "string"
            },
            "author_id": {
                "description": "Note:\nThis is a Foreign Key to `author.id`.<fk table='author' column='id'/>",
                "format": "bigint",
                "type": "integer"
            }
        },
        "type": "object"
    }
}`

would we get something similar in the dashboard?

**Comment by pedrovrima** [comment]
So, react flow does not have a sql-schema-like visualization out of the box. I found [this project](https://github.com/sqlhabit/sql_schema_visualizer/tree/main) that uses React Flow to create this sort of visualization. 
I will explore its implementation.

**Comment by Lan-Hekary** [comment]
@pedrovrima , this an awesome Idea!!
I can't wait for it to be integrated. Keep up the good work!

**Comment by kamilogorek** [comment]
I also got it working within a few hours locally. The only 2 missing pieces are:
- auto-layout, which is detailed in the pro version of react-flow - https://reactflow.dev/docs/examples/layout/auto-layout/
- positioning edges from foreign keys, but this one is not too complex to get, as the `/tables` store exposes all relationships in a very digestible way

That was fun to hack on, but the amount of flying store requests for every single page is terrifying 😅

https://github.com/supabase/supabase/assets/1523305/a12a5419-ea4c-428d-9ae7-cff2b3006235

**Comment by pedrovrima** [comment]
Nice job @kamilogorek - have you looked at the [sql_schema_visualizer](https://github.com/sqlhabit/sql_schema_visualizer) code for getting the edges in the right place?

**Comment by pedrovrima** [comment]
@kamilogorek 
(This is an implementation of auto-layout using Dagre library) [https://reactflow.dev/docs/examples/layout/dagre/]. There are other options as well, but this seems to be the most used one.

The PRO auto-layout example you shared is for adding new nodes, which I don't think is the case for this implementation.

**Comment by pedrovrima** [comment]
Ok! I will set this aside and wait to see what you share and what is left to do so we don't overlap in functions!

**Comment by kamilogorek** [comment]
<img width="1405" alt="image" src="https://github.com/supabase/supabase/assets/1523305/eb6ab73e-5f74-454c-a6b8-cb0c2812406a">

Only some layouting is left and it should be ready for polishing. Although might be a good idea to handle cases like foreign keys for external schemas in the future.

**Comment by rbkayz** [comment]
This is marvellous

**Comment by AdityaTD** [comment]
It appears that @kamilogorek has made quite a lot of progress on their end, maybe we can help them instead and speed up the process?

![image](https://github.com/supabase/supabase/assets/9266227/46d91b6d-20f4-4a4c-be77-e157fed9246c)
Source: https://twitter.com/kamilogorek/status/1678478856594808832

**Comment by pedrovrima** [comment]
I would hope so

Em ter., 11 de jul. de 2023 às 11:26, Aditya Tripathi <
***@***.***> escreveu:

**Comment by pedrovrima** [comment]
Hey @kamilogorek, any updates on this? You said you are leaving for vacations tomorrow, right?

**Comment by kamilogorek** [comment]
That's correct. I have all the pieces in place, will clean it up after I'm done with my own work and send the PR within next 6-8h :)

**Comment by kamilogorek** [comment]
@pedrovrima @AdityaTD there it is https://github.com/supabase/supabase/pull/15739

**Comment by rbkayz** [comment]
This is simply incredible work

One suggestion - I can see this is currently restricted to showing the relationships between tables in a single schema

But should we consider adding auth.users table as well by default?

A lot of times, the id column in that table is used as a FK in public. So might be worth showing that relationship in this ERD

What do you think?

**Comment by kamilogorek** [comment]
@rbkayz Thanks! It does show relationships to foreign tables as well, but the node is rendered as the `schema.table.column`  now, not as a whole table - https://github.com/supabase/supabase/pull/15739/files#diff-f5b900e6c6e71b1d7299c3c595ddce3af30bcaf6c520700a628ff3e0ccb550e0R77

eg. here `public` schema is pointing to `storage` schema.
<img width="486" alt="image" src="https://github.com/supabase/supabase/assets/1523305/e5a77d16-0929-4d62-a725-b363757eac3e">

Rendering a whole foreign table is doable by calculating relationships first and then querying for required tables, but I didn't want to overcomplicate it in the initial version.

**Comment by rbkayz** [comment]
My bad. This is excellent. Thank you

**Comment by AdityaTD** [comment]
> @pedrovrima @AdityaTD there it is https://github.com/supabase/supabase/pull/15739

Awesome, I'll test it tomorrow with a highly complex schema I have. In the meanwhile, is there anything specific you'd like us to work on and get this to the finish line?

**Comment by kamilogorek** [comment]
Hmm, I believe mostly UI-based stuff:
- better styling overall
- adding indicators
  - primary key (right now its just a colored border)
  - foreign key
  - is nullable
  - is identity
  - unique
- show truncated column names on hover (right now it shows as a native `title` attribute but would be nice to make it instant as a "floating" label
- a more complex addition would be to render a foreign table as a full node (although not sure if it's a good idea tbh, maybe just upgrade that node to be shown as a 3-line node with schema/table/column rows + column type and same indicators as above
- adding `<Controls />` component with matching styles - https://reactflow.dev/docs/api/plugin-components/controls/; I had it in the initial implementation but didn't find it that useful tbh, but maybe with just a custom "force layout" button and "center" it might be actually helpful, it'd have to be a design UX decision

**Comment by pedrovrima** [comment]
Awesome work @kamilogorek ! It is truly fantastic.

I suggest that if someone is willing to work on something Kamil suggested, we just call it here to avoid overlap in work like before.

I would like to take a shot in adding the Controls - I think that for large Schemas that will be very useful.

As for styling, I think  using bg-brand-fixed-1100 as default green would be more inline with the Supabase theming (not so bright).

**Comment by AdityaTD** [comment]
> Awesome work @kamilogorek ! It is truly fantastic.
> 
> I suggest that if someone is willing to work on something Kamil suggested, we just call it here to avoid overlap in work like before.
> 
> I would like to take a shot in adding the Controls - I think that for large Schemas that will be very useful.
> 
> As for styling, I think  using bg-brand-fixed-1100 as default green would be more inline with the Supabase theming (not so bright).

I agree, I'll start working on floating labels and then take a go at indicators.

**Comment by AdityaTD** [comment]
@saltcod I'm thinking to use MySQL Workbench type legends for indicating primary, primary foreign, null, not null & unique keys. My reasoning for going with MySQL Workbench-type indicators is that they've been industry standards for years on years now, and are well-known even with ER Diagrams.

They're indicated by Key, Diamond Outline, and Diamond Solid icons of different colors, however since Supabase uses `react-feather`, there's no diamond shape. Could you suggest where we should source this icon, or if you have any better idea to indicate these constraints?

Sidenote, we should probably have a contributors channel on Discord to speed things up, what do you think?

**Comment by Hallidayo** [comment]
@AdityaTD - I think the UI package also has `lucide-react`, is it possible to use icons from that package?

**Comment by AdityaTD** [comment]
> @AdityaTD - I think the UI package also has `lucide-react`, is it possible to use icons from that package?

Thanks for pointing it out, I must've missed it. Anyway, lucide has an empty diamond but not a solid one which is a variant we would need for those legends.

**Comment by Hallidayo** [comment]
@AdityaTD - You could ask tailwind classNames onto the icons, e.g. for this:

<img width="44" alt="Screenshot 2023-07-14 at 11 40 49" src="https://github.com/supabase/supabase/assets/22655069/ab887d5a-0cf5-4401-9235-57c2ffad5fcb">

The following I used: `<Diamond className="fill-red-500"/>|`

**Comment by AdityaTD** [comment]
> @AdityaTD - You could add tailwind classNames onto the icons, e.g. for this:
> 
> <img alt="Screenshot 2023-07-14 at 11 40 49" width="44" src="https://user-images.githubusercontent.com/22655069/253549187-ab887d5a-0cf5-4401-9235-57c2ffad5fcb.png">
> The following I used: `<Diamond className="fill-red-500"/>|`

Sure, I can do it this way, thanks. Will PR @kamilogorek's branch.

**Comment by AdityaTD** [comment]
Added primary icon and switched the node to a grid for even spacing in https://github.com/kamilogorek/supabase/pull/1#issue-1806542602
![image](https://github.com/supabase/supabase/assets/9266227/0da50b48-e4d4-4353-9067-6435aa65a0a9)

---

I do require some help though, since I'm new to the codebase, I want other constraints as the property for each node but I'm unsure where to get this data from. If someone can suggest, I can finish the other ones as well.

The function `getGraphDataFromTables` only seems to have the following properties per column.
```ts
    id: string
    isPrimary: boolean
    name: string
    format: string
```

Thanks!

**Comment by pedrovrima** [comment]
Nice job @AdityaTD . I am having a hard time getting any schema to show up. Is this a db from your personnal account? If so, how did you connect it to local?

**Comment by AdityaTD** [comment]
> Nice job @AdityaTD . I am having a hard time getting any schema to show up. Is this a db from your personnal account? If so, how did you connect it to local?

Hey, you need to follow the instructions under the docker directory of root and run it locally, there are better ways but this worked best for me.

**Comment by pedrovrima** [comment]
Awesome, will try that later! Thanks @AdityaTD !
