### ISSUE TITLE
Studio: User deletion shows success even when it fails

### ISSUE THREAD

**Issue by probablykasper** [supabase/supabase#15605]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Let's say you have a table `public.profiles` with a foreign key to `auth.users`. If you try to delete a user, it will fail when the user has a row in `public.profiles`.

However, if you try to delete a user in the Supabase Studio Users page, it will look like it succeeded:
<img width="385" alt="image" src="https://github.com/supabase/supabase/assets/11315492/b55aa70f-9afe-4eca-a4e2-2e853cfbe764">

Then when you reload, the user re-appears.

## To Reproduce

1. Create a table `public.profiles` with a foreign key to `auth.users`. In my case, I have this definition:
    ```pgsql
    create table
      public.profiles (
        id uuid not null,
        first_name text null,
        last_name text null,
        email text null,
        constraint profiles_pkey primary key (id),
        constraint profiles_id_fkey foreign key (id) references auth.users (id)
      ) tablespace pg_default;
    ```
2. Create a user and a `profile` for the user
3. Go to Supabase Studio > `Users` and delete the user
4. Reload to see the user still there

## Expected behavior

An error message should show up when the user deletion fails

## System information

- OS: macOS
- Browser: Brave
- Version of supabase-js: 2.26.0
- Version of Node.js: 18.14.2

## Additional context

Related:
- https://github.com/supabase/supabase/issues/4841

**Comment by mdjohns** [comment]
I tried to recreate this, but was unable to (kept getting the "Failed to delte user" modal). 

Based on the comments in #4841, it seems like others are having trouble with reliable recreation as well.

I took a quick peek at the API route being called:
https://github.com/supabase/supabase/blob/35011f56c075afd020b489e03e024ee7c895c302/studio/pages/api/auth/%5Bref%5D/users.ts#L118

The `post` util is `async`:
https://github.com/supabase/supabase/blob/35011f56c075afd020b489e03e024ee7c895c302/studio/lib/common/fetch/post.ts#L5

But we are calling it without `await`, which could be why this is not reliably reproduceable.

**Comment by probablykasper** [comment]
For me it never shows an error modal. What does that look like?

**Comment by mdjohns** [comment]
This is the modal I see:
<details>
  <summary>Screenshot</summary>

![image](https://github.com/supabase/supabase/assets/13648640/63faf128-d88d-483d-9840-dfe05c58ad83)

</details>


I followed your instructions, but I haven't been able to reproduce. Any other details?

**Comment by probablykasper** [comment]
Not really anything more. These exact steps reproduce it for me:

1. `supabase init`
2. `supabase start`
3. Create `profiles` table with an `id` column linked to `auth.users.id`
4. Create user
5. Add the user to the `profiles` table
6. Delete the user

https://github.com/supabase/supabase/assets/11315492/c62505f4-7168-46f5-9e74-a269fb6cb133

**Comment by Bhavyawahie** [comment]
> [#4841 ](https://github.com/supabase/supabase/issues/4841) - This is still very much an issue on the self-hosted/local environment. On deleting a record of the type `protected schema` (such as auth) with a foreign key relation to our table yields a `200 OK `Response on deletion of that record even though it hasn't really been deleted.
> 
> **Current Behavior**
> 
> Screen Recording for reference
> 
>  ezgif.com-gif-maker.3.mp4 
> **Expected Behavior**
> 
> ![image](https://user-images.githubusercontent.com/34278282/263694540-036fd07f-333b-4352-8a9d-cd42743a1bd8.png)

**Update**

On traversing the logs of the supabase-meta container, the following is logged on performing the above operation:

`{"level":"error","time":"2023-08-28T09:04:33.000Z","pid":19,"hostname":"1be15c64e27a","reqId":"req-291","error":{"message":"update or delete on table 
\"users\" violates foreign key constraint \"profiles_id_fkey\" on table \"profiles\""},"request":{"method":"POST","url":"/query","pg":"db","opt":""}}`

**Comment by Bhavyawahie** [comment]
> [#4841 ](https://github.com/supabase/supabase/issues/4841) - This is still very much an issue on the self-hosted/local environment. On deleting a record of the type `protected schema` (such as auth) with a foreign key relation to our table yields a `200 OK `Response on deletion of that record even though it hasn't really been deleted.
> 
> **Current Behavior**
> 
> Screen Recording for reference
> 
>  ezgif.com-gif-maker.3.mp4 
> **Expected Behavior**
> 
> ![image](https://user-images.githubusercontent.com/34278282/263694540-036fd07f-333b-4352-8a9d-cd42743a1bd8.png)

**Update**

On traversing the logs of the supabase-meta container, the following is logged on performing the above operation:

`{"level":"error","time":"2023-08-28T09:04:33.000Z","pid":19,"hostname":"1be15c64e27a","reqId":"req-291","error":{"message":"update or delete on table 
\"users\" violates foreign key constraint \"profiles_id_fkey\" on table \"profiles\""},"request":{"method":"POST","url":"/query","pg":"db","opt":""}}`

**Comment by joshenlim** [comment]
hey guys! this issue should now be fixed with the latest studio image, which should go out to the [CLI](https://github.com/supabase/cli) around 19th Sept!
It's available on the beta version of the CLI. nonetheless for those who might want to use it first, but i'll go ahead to close the issue 🙏
