### ISSUE TITLE
Improve local Postgres logging

### ISSUE THREAD

**Issue by probablykasper** [supabase/supabase#15610]
# Improve documentation

## Where 

- https://supabase.com/docs/guides/getting-started/local-development#enabling-local-logging
- Supabase Studio > Logs

## Describe the problem

I had a hard time figuring out how local logging with Postgres. After Googling, it seemed like `RAISE NOTICE` was the way to log from plpgsql, but that didn't show up when I checked the logs from the Docker container. I checked [the documentation which says to configure Google BigQuery for this](https://supabase.com/docs/guides/getting-started/local-development#enabling-local-logging), but that seemed really excessive to me. In the end I realized that Supabase is configured to only at minimum log from `RAISE WARNING`.

## Describe the improvement

It would be great to document how to log from Postgres SQL, and how to see the logs without having to set up Google Cloud/BigQuery.

This would be nice to explain on the Logs page as well, instead of just showing this error:
<img width="1272" alt="image" src="https://github.com/supabase/supabase/assets/11315492/df0c14bb-3a63-429b-9d5b-4daa2597ec31">

**Comment by probablykasper** [comment]
@gregnr Would just like to clarify that this isn't about self-hosting (since you added that label), it's about local development

**Comment by gregnr** [comment]
Thanks @probablykasper - this probably applies to both, but I'll remote the label since it's not specific to self-hosting. Thanks for clarifying!

**Comment by Ziinc** [comment]
Hi @probablykasper , this is currently in the works.
As for configuring postgres log levels, you can refer to the [documentation on logging](https://supabase.com/docs/guides/platform/logs#configuring-pgauditlog).

**Comment by Ziinc** [comment]
@probablykasper By default, RAISE at EXCEPTION level will be automatically logged to the default logging driver.

For example:
<img width="610" alt="Screenshot 2023-07-31 at 5 04 48 PM" src="https://github.com/supabase/supabase/assets/22714384/2e3ec097-5597-4dc6-8646-c1310bd746e3">
This will be shown in docker (assuming cli is used out of the box without logging setup)
<img width="1001" alt="Screenshot 2023-07-31 at 5 04 43 PM" src="https://github.com/supabase/supabase/assets/22714384/9aa5c562-0407-4791-a350-f6c5c1ae5338">

**Comment by Ziinc** [comment]
To further clarify, if you want to `RAISE NOTICE 'my message'`, then you will need to set the pg_audit log level to notice:
```
set pgaudit.log_level = notice;
```
https://github.com/pgaudit/pgaudit/blob/master/README.md#configuration
By default, ERROR, FATAL, PANIC levels are automatically logged by postgres, as I demonstrated above.

**Comment by johannesjo** [comment]
I am still having trouble to get any useful log information on local dev. Enabling the pg_audit extension doesn't seem to do much. I tried manually configuring postgres.conf but I am unable to restart from within the docker container. `/var/log/postgresql/` exists within the container but is always empty. Any pointers?

**Comment by Ziinc** [comment]
Hi @johannesjo it isn't quite clear what exactly you are trying to get out of the logs. pg_audit can be quite extensively configured to fit most if not all needs.
logs are currently directed to the docker logging driver, hence default log locations will be empty.
