### ISSUE TITLE
Invalid HTML on the Documentation homepage

### ISSUE THREAD

**Issue by nick-krantz** [supabase/supabase#15637]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running the documentation site, Next is throwing invalid HTML errors because there are instances of a `<p>` being the descendant of a `<p>`.

## To Reproduce

1. Clone the supabase repo
2. Run `npm install` from the root
3. Run `npm run dev:www` to start the documentation site
4. Navigate to `http://localhost:3001` & open the dev tools console

## Expected behavior

The HTML/MDX should be structured properly, i.e. a `<p>` should not appear as a descendant of another `<p>`

## Screenshots

Error message:
![image](https://github.com/supabase/supabase/assets/19392291/65f585d8-60ac-499d-9f76-3f909b7ba4fc)

Example within the HTML:
![image](https://github.com/supabase/supabase/assets/19392291/9fdd5e6a-252b-4f63-a62b-34b6c312e261)

## Additional context

From my initial search it looks like it is caused by the way MDX handles newlines and using `<p>` within the MDX. I'll see if I can determine a root cause and raise a PR.

**Comment by bright258** [comment]
@nick-krantz Have you fixed this yet? I'll look into it right away.

**Comment by bright258** [comment]
@nick-krantz What do you think will be the best approach to solving it?

**Comment by nick-krantz** [comment]
@bright258 Hi! Yes, I'm working on a fix now!

**Comment by nick-krantz** [comment]
@bright258 I have had some time to dig into this and it seems to be caused by code blocks rendered by Code Hike. They have a set width that can be wider than the viewport. I haven't found a way to fix as of yet. It's possible it could be a bug in that package.

![set-width](https://github.com/supabase/supabase/assets/19392291/ceccaa0c-199f-4377-8eaa-4b06aecef94b)

**Comment by vibhaw1904** [comment]
hey @gregnr  did a slight  change i code wrapping the Testlink in to div ,I think thaat works fine
<img width="602" alt="opensrc" src="https://github.com/supabase/supabase/assets/98641357/0853f460-86ab-488d-8c78-326c41120ac8">

**Comment by alaister** [comment]
I believe this has now been fixed since https://github.com/supabase/supabase/pull/17839 merged. Please feel free to re-open if that's not the case 🙌🏻
