### ISSUE TITLE
I can't login to my account on supabase

### ISSUE THREAD

**Issue by RafoPetrosyan** [supabase/supabase#15640]
I can't login to my account on supabase

This site can’t be reachedauth.supabase.io took too long to respond.

![Screenshot_1](https://github.com/supabase/supabase/assets/94311876/bf74e68b-64d6-4f76-9f90-1c7bed33f36b)

**Comment by bright258** [comment]
@RafoPetrosyan Was this your first time trying to login?

**Comment by bright258** [comment]
It should be a problem with your network connection. I just tried  logging in now and it worked very well.

**Comment by RafoPetrosyan** [comment]
> @RafoPetrosyan I am interested in fixing this. How do I contribute?



> @RafoPetrosyan Was this your first time trying to login?
not the first time, I've already logged in several times, but today I can't, I logged in via github

**Comment by j4w8n** [comment]
I was able to login at https://supabase.com/dashboard/sign-in

**Comment by RafoPetrosyan** [comment]
@j4w8n it still doesn't work for me, I also tried with other browsers, I even tried to open a new account with a different email, I can't log in that way

**Comment by GaryAustin1** [comment]
It also works for me, and not seeing any other reports in the forums.
Some sort of firewall?  Maybe try a vpn or from a different network.

**Comment by RafoPetrosyan** [comment]
@GaryAustin1 
tried it all, no result

**Comment by MildTomato** [comment]
It appears it might just be you experiencing the issue @RafoPetrosyan 
Could you email support@supabase.io using the email you use for GitHub account (assuming you log into Supabase with GitHub)

**Comment by MildTomato** [comment]
Closing as the issue seems to be a one off
