### ISSUE TITLE
Supabase Swift Realtime client not working after deploying to Local HTTP Server

### ISSUE THREAD

**Issue by AsifSyeed** [supabase/supabase#15659]
### Discussed in https://github.com/orgs/supabase/discussions/15658

<div type='discussions-op-text'>

<sup>Originally posted by **AsifSyeed** July 10, 2023</sup>
I am using supabase for one of my Swift projects. While I was using a free module from supabase, it was working perfectly. Now I have deployed it in our local development server. After deploying to local server, it is not listening to the insert, update, delete from the tables of supabase while the queries are working fine. I have connected to realtime client properly and also subscribing to the channels properly.

Please note that out local server is on HTTP while the module from Supabase is on HTTPS. Will it make any issue??

I have also enabled Allow Arbitrary Loads from Info.plist</div>

**Comment by KevinBrolly** [comment]
Hey @AsifSyeed I am going to close this issue as the discussion is the better place to resolve your problem.
