### ISSUE TITLE
"Self-Hosting" URL on docs homepage links to the wrong page

### ISSUE THREAD

**Issue by jackmerrill** [supabase/supabase#15654]
# Improve documentation

## Link 

https://supabase.com/docs#self-hosting

## Describe the problem

Click on the "More on self-hosting" link, and reload (or open the link in a new tab). Appears to 404.

## Describe the improvement

Seems like a link is wrong: https://github.com/supabase/supabase/blob/2bc385cbb6da08521cfca54cf8a849d3e961c6aa/apps/docs/pages/index.mdx#L162

## Additional context

I'll try to open a pull request to fix this.

**Comment by gregnr** [comment]
Fixed via #15655
