### ISSUE TITLE
Flutter RPC does not work with select and filter at the same time

### ISSUE THREAD

**Issue by iKreateCode** [supabase/supabase#15686]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am implementing the following function as seen in the picture that works in JS but not in Flutter dart. I am not able to use the equals filter alongside select() function. It will only let me select either of the two at the same time.

## Screenshots

Flutter error:
![image](https://github.com/supabase/supabase/assets/44262516/3ce7c44c-9ed8-4afb-b8fa-ae22538138b5)

Working JS implemention:
![image](https://github.com/supabase/supabase/assets/44262516/59cc2f26-f97a-4e3e-83a9-5a6622a987fe)

## System information

- OS: macOS
- Version of supabase-dart: 1.9.6

**Comment by gregnr** [comment]
cc @dshukertjr in case you have any ideas

**Comment by dshukertjr** [comment]
@iKreateCode 
Thanks for opening this issue. 

I believe we don't support chaining filters like `eq()` or `lte()` on `select()` that is chained on an `rpc()` call on our js SDK either. You can confirm by using typescript and observing an error on `eq()` filter similar to how you are getting it on Dart. 

```typescript
supabase.rpc('func').select().eq('', '')
```

**Comment by iKreateCode** [comment]
Will you have support for this in the future?

**Comment by dshukertjr** [comment]
At the moment we don't have any plans of adding support for syntax like this, but you could easily work around it by adding the joins and filters in the database function definitions!
