### ISSUE TITLE
The remote database's migration history is not in sync with the contents of supabase/migrations

### ISSUE THREAD

**Issue by fvkramer** [supabase/supabase#15695]
# Bug report
- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

I am following the local development documentation here: https://supabase.com/docs/guides/getting-started/local-development

I developed the remote db through the UI interface first, and am trying to sync the remote schema to local.
I have run

`supabase link --project-ref <project-id>`

Running:

`supabase db remote commit`

causes the following error:

```
The remote database's migration history is not in sync with the contents of supabase/migrations. Resolve this by:
- Updating the project from version control to get the latest supabase/migrations,                               
- Pushing unapplied migrations with supabase db push,                                                            
- Or failing that, manually editing supabase_migrations.schema_migrations table with supabase migration repair.  
```

I have found these two issues related to this error:

https://github.com/orgs/supabase/discussions/6907
https://github.com/supabase/supabase/issues/12353

Each suggest the solution was deleting conflicting records in the remote db schema_migrations table, but I don't see an option to do so in the UI. The tabled is marked as "Locked".

This issue suggests deleting the local `migrations/` table:

https://github.com/orgs/supabase/discussions/6577

Doing so does not resolve the above error. Running `supabase db remote commit` still has the same error message.

Any suggestions?

**Comment by marinhojess** [comment]
same issue here

**Comment by AyushSehrawat** [comment]
I once ran db pull and deleted supabase folder (was testing), and that was the issue. I didn't see delete option when deleting the row in supabase_migrations schema table, but then i duplicated it, delete with cascade the original one and rename the duplicated one back to default one, fixed it.

**Comment by indiechatdev** [comment]
This is what I did to resolve: On remote hosted Supabase, go to schema_migrations table in supabase_migrationcs schema and duplicate the migration row. Then delete the original with cascade then rename the new one by removing _duplicate text. Next go to CLI and attempt supabase db pull which will probably work but you'll notice that when you go to your local hosted supabase your schema still won't be transferred. Here is where it get's interesting. I then did supabase db reset and got an error about the primary keys migration text blabla. Then i went into my local supabase directory, to migration folder and opened the migration sql file. I scrolled and found a line: ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
    ADD CONSTRAINT "schema_migrations_duplicate_pkey1" PRIMARY KEY ("version"); and straight up deleted it and saved the file. Called supabase db reset yet one more time. This time successfully completes. Opened up the locally hosted supabase in browser, and sure enough, my schema and tables were finally there.

**Comment by mtin79** [comment]
Thanks @indiechatdev !
i ran into a similar issue when running first:

```
> supabase db pull --linked
> supabase db reset

Resetting local database...
Recreating database...
Setting up initial schema...
Applying migration 20240113201955_remote_schema.sql...
ERROR: multiple primary keys for table "schema_migrations" are not allowed (SQLSTATE 42P16)
At statement 37: ALTER TABLE ONLY "supabase_migrations"."schema_migrations"                
    ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version")                        
Try rerunning the command with --debug to troubleshoot the error.
```
I just deleted two similar lines of code in the initial migration file and the the `supabase db reset` worked,
i guess this is still a bug somehow!

**Comment by encima** [comment]
Running the latest version of the CLI (1.136.3) resolves this for me,
1. `supabase start`
2. `supabase link` (relink to existing project and update local images)
3. `supabase db reset`
4. `supabase db pull` (can also run again with --schemas auth,storage, you may be prompted to run a migration repair command, do that)

No need to delete or edit migration files. Let us know if you still see issues!

**Comment by eRuaro** [comment]
@encima I'm running into the issue again. Used the steps you provided on version 1.64.8.

**Comment by colemilne54** [comment]
@encima Same as @eRuaro, followed steps and still hitting the issue

**Comment by colemilne54** [comment]
> @encima Same as @eRuaro, followed steps and still hitting the issue

After 'db reset' I deleted the migration files and then 'db pull' grabbed the remote schema I needed without conflicts. Seeded data from remote and reset again and all seems well.

**Comment by Zurigan** [comment]
https://github.com/supabase/supabase/issues/12353#issuecomment-1974768203

> For anyone coming here in 2024, the schema_migrations table is read-only when accessed from the Table Editor. But, you can interact with it from the SQL editor. The following command will clear the schema_migrations table.
> delete from supabase_migrations.schema_migrations;

helped me un-break this after I'd done a pull and then deleted the local folder after I realized I was in the wrong directory. @encima your steps didn't help, sadly.
