### ISSUE TITLE
pgcrypto functions are not usable in a function declaration

### ISSUE THREAD

**Issue by dogukanakkaya** [supabase/supabase#15707]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```sql
create extension if not exists pgcrypto SCHEMA public; /* unnecessary since enabled by default but i tried this as well */
create or replace function public.user_keys()
returns trigger as
$$
begin
  insert into public.user_keys (user_id, key) values (new.id, encode(gen_random_bytes(32), 'base64'));
  return new;
end;
$$
language plpgsql volatile;
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the user_keys table
2. Create the above function
3. Create a trigger for after inserts to auth.users

## Expected behavior

`gen_random_bytes(count integer)` should be available in function context as well.

## Additional context

Below select works.
```sql
select encode(gen_random_bytes(32), 'base64');
```

**Comment by GaryAustin1** [comment]
auth.users triggers do not have access to public schema.  You need to possibly set the search path but will need to  make your function `security definer` type.
From the user management starter SQL guide...
![image](https://github.com/supabase/supabase/assets/54564956/ddcc1974-2b5b-49a2-85aa-150e46087b8d)

**Comment by dogukanakkaya** [comment]
I remember I tried to set `security definer` but it didn't work.
Anyways I've changed the structure of my app & tables and choose some other way for my needs. Anyone having the same issue can retry that solution. Hence closing this issue.
