### ISSUE TITLE
Cannot Create, Modify, or Alter table schema on an existing table in the Supabase dashboard.

### ISSUE THREAD

**Issue by Shawns2759** [supabase/supabase#15712]
# Bug report

- [ y] I confirm this is a bug with Supabase, not with my own application. 
- [y] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When I try to add a column to one of my tables I get this error `"Failed to pg.columns: must be owner of table <table_name>".` 
This seems to be like a permission issue but I'm not sure what has to be done to fix this.

I have also tried to run the SQL script to ALTER the table, but I still get the same error saying I must be the owner of the table.

Failed to run sql query: must be owner of table customers
This project is hosted on Supabase cloud and I'm not self-hosting this project. I run into the same issue when i try to disable RLS for the table.

I have tried granting permissions using these commands that I found on other similar permission issues for Supabase. But even these commands return the following errors -

`GRANT supabase_admin TO postgres;`
`"Failed to run sql query: must be superuser to alter superusers"`

`ALTER USER postgres WITH superuser;`
`"Failed to run sql query: must be superuser to alter superuser roles or change superuser attribute"`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `Table Editor`
2. Click on `add column`
3. Enter new Column name and data type
4. See error alert

## System information

- OS: MAC

**Comment by gregnr** [comment]
Hey @Shawns2759 - sounds like this might be something specific to your database. Could you open a support ticket?
