### ISSUE TITLE
Problem with email validation when creating a new user

### ISSUE THREAD

**Issue by akash1412** [supabase/supabase#15725]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When creating a new user, the email validation is not functioning correctly. I am able to add an invalid email address, which should be restricted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior
When an invalid email address is entered during user creation, an error should be thrown

## Screenshots

https://github.com/supabase/supabase/assets/41125658/a5a3e4eb-0590-4cf1-9aea-75d112913f3d

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by sh3rlock97** [comment]
Akchually these are valid emails according to the email protocol.

**Comment by saltcod** [comment]
Closing as we likely want to allow such emails in this case. 

Comment:
https://github.com/supabase/supabase/pull/15726#issuecomment-1637364174
