### ISSUE TITLE
Add Update, Upsert, and Delete examples to Python reference docs

### ISSUE THREAD

**Issue by AdamGEmerson** [supabase/supabase#15741]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)
[Python Docs](https://supabase.com/docs/reference/python/select)

## Describe the problem

The Python documentation only has examples for Fetch and Insert in the "Database" section, i'd like to improve the Python documentation by bringing more inline with the JS docs and adding example sections for Update, Upsert, and Delete.

This has been requested in the issues of the supabase-py repo [here](https://github.com/supabase-community/supabase-py/issues/486).

## Describe the improvement

I believe this should be accomplished by editing the[ python yml file](https://github.com/supabase/supabase/blob/master/spec/supabase_py_v2.yml ) to include the additional API endpoints.

## Additional context

I see that there has been some movement on the python docs with #15053, but I think that is only expanding on the INSERT documentation, not adding additional endpoints for UPDATE, UPSERT, etc.

**If this is something that anyone on the team deems worthwhile then I would love to take a crack at it.**

Thanks!

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like writing documentation) by writing pull requests. This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by gregnr** [comment]
@AdamGEmerson that would be great! Feel free to open a PR and we'll take a look!

**Comment by AdamGEmerson** [comment]
@gregnr Great! I'll see what I can whip up.

Regarding implementation, I've noticed that the [existing Python INSERT](https://supabase.com/docs/reference/python/insert) documentation is pulling in the parameter data from the `postgrest-js` typedocs, which isn't precisely a one to one match with the `postrgest-py` library.  

I think we should probably emulate the Flutter (and other community library) docs and remove the `postgrest-js` references from the Python docs.

That said, in lieu of the rich typing information afforded by typedocs, I could provide a direct link to the `postgrest-py` endpoint in the descriptions of the supabase-py endpoints.

Something like this: 
![Python INSERT w/ postgrest link](https://github.com/supabase/supabase/assets/35545129/3b1a6e0e-f453-469b-8628-07fd8c1a8a29)

Which would link to: 
[postgrest-py: insert()](https://postgrest-py.readthedocs.io/en/latest/api/request_builders.html#postgrest.AsyncRequestBuilder.insert)

Do you have any concerns about this approach?

**Comment by gregnr** [comment]
Hey @AdamGEmerson, good catch. Ideally everything is available on the Supabase docs without having to jump back and forth from somewhere else.

Looks like the docs you linked to are [dynamically](https://github.com/supabase-community/postgrest-py/blob/c56878f37b3be9638b403b6d35a52514c6a81f63/docs/api/request_builders.rst) generating [type/parameter](https://github.com/supabase-community/postgrest-py/blob/c56878f37b3be9638b403b6d35a52514c6a81f63/postgrest/_async/request_builder.py#L260-L269) information  (using Sphynx [autodoc extension](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html)). Ideally if we could do something similar to extract this info and feed that into Supabase docs, that'd be great.

Digging deeper, looks like the docstring is formatted as reStructuredText, which isn't super ideal. Thoughts on LOE to extract this info?

**Comment by AdamGEmerson** [comment]
@gregnr, wanting all the documentation to be collocated on the same page makes sense. 

The generated parameter data being pulled in as referred to internally as an enrichment, is that correct?

Let me make sure I understand the Supabase documentation pipeline correctly: 
 
It looks to me like the typings for each library are being downloaded by the `/spec/Makefile`  and parsed into json by `/spec/parser/tsdoc.ts` where they get stored in `/spec/enrichments/`.  These files for each library are then merged into one file, `combined.json`.  

Then, is the `$ref` tag in the `.yml` files being used as a key for the relevant information in `combined.json`?  Where does the business logic for this happen?  

I see the components used for the reference in `/apps/docs/components/` and `/apps/docs/layouts/` but I'm not clear on where the data from `combined.json` is being passed to React.

It seems like the path of least resistance would be to write a second parser for the python docs that converts them into a format mirroring the output of `tsdoc.ts`?  Then the python docs could also be merged in with `combined.json` and we wouldn't need to worry about making adjustments to the rendering logic on the React side of things.

It might be best for me to go ahead and create a PR with basic documentation for the missing routes and then work on implementing a parser in a separate PR.  

What are your thoughts?

**Comment by gregnr** [comment]
Hey @AdamGEmerson thanks for digging into that. Let me get back to you on the pipeline logic - in the mean time I agree let's add those missing routes. Thanks!

**Comment by J0** [comment]
Hey team,

Circling back on this - let us know if there's any way we can be of help. Please feel free to remove the typedocs

**Comment by AdamGEmerson** [comment]
@J0 Thanks for following up. 

I got busy with other things and never got back to this.

Good news is, my time just opened back up a bit so I'll see about getting these routes added in the next few days.

**Comment by anand2312** [comment]
> Digging deeper, looks like the docstring is formatted as reStructuredText, which isn't super ideal. Thoughts on LOE to extract this info?
@gregnr @AdamGEmerson  I've used [pytkdocs](https://mkdocstrings.github.io/pytkdocs/) to extract data from reST docstrings, but if it turns out to be a problem we can switch the docstrings to some other style.

**Comment by AdamGEmerson** [comment]
Been updating the python YML this afternoon to be more in line with the JS docs. Hoping to get a PR in tonight.

I updated the existing python code examples for `Fetch Data` and `Insert` to be more pythonic.  If you copied and pasted some of them as they were you would get a syntax error.

I'm omitting the typedoc stuff for now, but if @anand2312 wants to write a parser we should be able to just add a `$ref` key back in for each entry where relevant.

RPC currently has a lot of issues in `supabase-py`, but they should be fixed soon.  I'll wait to add a section on that until they have it fixed.  See [this issue.](https://github.com/supabase-community/supabase-py/issues/405)

I'm working through the filters now.

**Comment by AdamGEmerson** [comment]
@gregnr @J0 

I have generated a PR but was unsure how to proceed with the Vercel checks.  If that is something I can take care of then I'm happy to read up on them but it seemed like an official member of the team may need to handle them?

Thanks!

**Comment by silentworks** [comment]
Closing this out as the PR's opened by @AdamGEmerson were merged in. Thanks again @AdamGEmerson for your contributions.
