### ISSUE TITLE
Broken Usage average database size per day

### ISSUE THREAD

**Issue by OpenGrid** [supabase/supabase#15763]
# Bug report

- [yes] I confirm this is a bug with Supabase, not with my own application. 
- [yes] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I look at Billing usage I see growing average database size chart reaching for example 450MB. At the same time my real database reported by `pg_database_size(pg_database.datname))` shows stable 86MB. 
I'm confused why the chart is growing while Average in period is stable

## To Reproduce

1. Go to Project Settings -> Usage -> Database size

## Expected behavior

Database average size per day to reflect database size 

## Screenshots

Average chart:
https://cdn.discordapp.com/attachments/1128807432357949541/1128807943853318274/average.png

Database size:
https://media.discordapp.net/attachments/1128807432357949541/1129047461667807313/image.png

## System information

- Database studio 
- All browsers

**Comment by saltcod** [comment]
Hey @OpenGrid sorry for the delay on this one. You're charts are actually correct, hinting at an underlying bug. We're looking into it.  Apologies again for the delay.

**Comment by OpenGrid** [comment]
@saltcod so any ideas where these stats come from and how to identify what may impact this chart?

**Comment by ivasilov** [comment]
Hey @OpenGrid, this issue is scheduled to be fixed this week, @kevcodez is on it.

**Comment by OpenGrid** [comment]
I found a solution that was due to old database in a Supabase organization that I deleted but the replication slot remained somehow.
First find replications slots:

```
SELECT slot_name,
       pg_wal_lsn_diff(
          pg_current_wal_lsn(),
          restart_lsn
       ) AS bytes_behind,
       active,
       wal_status
FROM pg_replication_slots
WHERE wal_status <> 'lost'
ORDER BY restart_lsn;

```

If there's one inactive then drop replication slot 

`SELECT pg_drop_replication_slot('name_of_the_slot');`

**Comment by dmoranf** [comment]
After the slot deletion, dashboard shows that the usage is over 1Gb, but the database size is only 112 ... so it seems that it didn't work for me :(

![image](https://github.com/supabase/supabase/assets/7201665/1bb17f5c-dea8-4053-9861-840a2ec15bea)

![image](https://github.com/supabase/supabase/assets/7201665/798b4bf7-f1bc-4628-b2fd-aa09bb3e9b6b)

**Comment by kevcodez** [comment]
For the absolute majority of users, this should already be fixed and it shouldn't matter whether you have the test slot or not.

@dmoranf could you please open a support ticket so we can assist you there?
