### ISSUE TITLE
Types generation for Deno

### ISSUE THREAD

**Issue by dogukanakkaya** [supabase/supabase#15797]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am not able to generate Typescript types in Deno project. I tried with Deno's npm specifiers but no success.

```json
"supabase:generate": "deno run --node-modules-dir npm:supabase@1.77.9 gen types typescript --project-id 'my-project-id' --schema public > supabase.types.ts"
```

## System information

- Version of Deno: `1.35.1` which is latest at the moment.

## Additional context

When i try the above solution i have the below error:
> error: Uncaught Error: Cannot find module '/.../node_modules/.deno/supabase@1.77.9/node_modules/supabase/bin/supabase'
    at Function.Module._resolveFilename (node:module:617:17)
    at Function.Module._load (node:module:497:29)
    at Object.loadCjsModule (ext:deno_node/02_init.js:58:22)
    at loadCjsModule ([ext:ext/node/lib.rs:563:29]:2:32)
    at [ext:ext/node/lib.rs:563:29]:3:7
    
I've logged in and linked my project in a Frontend app before so it will probably not ask for those even if i pass that error but still for Deno only projects we need a way to run supabase cli in Deno. Global installation is not an option as well since it's not allowed.

**Comment by encima** [comment]
Thanks for opening! This is a known issue with [deno](https://github.com/denoland/deno/issues/20474).

Current workaround is to: go into the directory of the package, run `npm install` and then deno may be able to run it.

Please watch the linked ticket for updates!
