### ISSUE TITLE
KeyCloak Provider - 500: Error getting user email from external provider

### ISSUE THREAD

**Issue by chrisciszak** [supabase/supabase#15790]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After successful authentication with Keycloak Supabase is throwing an error in the logs and the user is not logged in.

## To Reproduce

Connect to the latest version of Keycloak v21.1.2

## Expected behavior

User is successfully logged in

## Screenshots

![image](https://github.com/supabase/supabase/assets/11364221/987b2265-39fe-4534-87db-f08b45b7b792)

## System information

Hosted Supabase

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!

**Comment by nisarg2023** [comment]
@encima i stell face this issue
the same issue I get when I try to sign up with Facebook when my account is made using just my mobile number and not my email address. 
it is mandatory add email to signup with facebook in to supabase ?

**Comment by encima** [comment]
@nisarg2023 yes, email is needed when using any oauth provider with Supabase so your facebook users will require an email to be associated with their account
