### ISSUE TITLE
JWT expiry limit not updated in the Database.

### ISSUE THREAD

**Issue by Lan-Hekary** [supabase/supabase#15791]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The `app.settings` configuration in my Database contain 2 Keys:
- `app.settings.jwt_secret` which contains the JWT secret and according to the [docs](https://postgrest.org/en/stable/references/configuration.html#app-settings) of PostgREST it's set there.
- `app.settings.jwt_exp` and as the name implies, it's the JWT expiry limit that is set for the Go-True.

Changing the JWT secret from Dashboard reflects in the database and `app.settings.jwt_secret` updates as expected after the project restart.

but changing the JWT expiry limit in Auth Settings does not reflect in the database.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Run the query `select * from pg_db_role_setting where setrole=0;` to get the database settings or `select current_setting('app.settings.jwt_exp');`
- Note that Number in new projects is equal to JWT expiry limit at https://app.supabase.com/project/_/settings/auth
- Change the number in https://app.supabase.com/project/_/settings/auth to anything else.
- Run the query again, now the database have the old value.
- Restart the Project.
- Run the Query again.

## Expected behavior

`app.settings.jwt_exp` should reflect the values in the dashboard even if not instantly at least after a full project restart!

## Screenshots
This worked before because I extended my JWT from 3600 to 259200 when I first started the my project.
But now it does not update any more.
![image](https://github.com/supabase/supabase/assets/13420623/c8e58f73-b58e-4784-9c9e-969d37e6c862)

**Comment by Lan-Hekary** [comment]
After I made this issue I tried pausing and unpausing the project and to my surprise it updated correctly.
So I Guess that's the solution for now. but I am curious if it's the expected behavior.

**Comment by encima** [comment]
Hi @Lan-Hekary,

Hopefully the docs [here](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects) answer your question.
1. Pause and restore - This removes your project instance and recreates it
2. Upgrade - This will attempt to perform an in place upgrade and keep the same resources running

Always good practice to ensure your project is running the latest version! Will close this for now but please comment if you have issues or more questions
