### ISSUE TITLE
[doc] PostGIS installation is not working out of the box

### ISSUE THREAD

**Issue by Maxwell2022** [supabase/supabase#15801]
# Improve documentation

## Link 

https://supabase.com/docs/guides/database/extensions/postgis

## Describe the problem

When enabling the extension in the UI, it installed it in the tiger schema by default (instead of extensions) and so the example is not working

## Describe the improvement

Explain the if you enable the extension in the UI, you most likely need to add the `tiger` schema to your `search_path` in the Supabase settings.

Maybe recommend creating the extension using the SQL syntax that will install it in the `extensions` schema without the need to update the `search_path`

## Additional context

<img width="657" alt="image" src="https://github.com/supabase/supabase/assets/670701/8038b01c-b67f-40bb-8bed-0a81bf34ae48">

**Comment by Hallidayo** [comment]
Hi @Maxwell2022 - Just having a check through this issue and I can see now that when you enable the extension now that you can get prompted to select which schema to add to and this should solve the issue now.

**Comment by Hallidayo** [comment]
We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
