### ISSUE TITLE
Cannot fetch data after restarting(upgrading) server that disabled pgaudit extension.

### ISSUE THREAD

**Issue by pitzcarraldo** [supabase/supabase#15803]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After upgrading server (Pause and Restore), it seems that postgres version is updated to 11.1.0. And api stopped to work. Every reponses failed with 403 with below errors.

`permission denied to set parameter "pgaudit.log"`
`permission denied to set parameter "pgaudit.log_level"`

You could find more information from below discord thread.
https://discord.com/channels/839993398554656828/1127950183305588857

I enabled pgaudit before, but disabled it later. And haven't used until now. And after server upgraded, i got this issue.

I could get it to work after enabling pgaudit and running below sql.

```
alter role anon reset pgaudit.log;
alter role authenticated reset pgaudit.log;
alter role authenticator reset pgaudit.log;
alter role service_role reset pgaudit.log;
```

## To Reproduce

I think to reproduce, the version of postgrest need to be lower than 11.1.0.

1. Enable pgaudit from supabase.com database > extension dashboard of the project that using postgrest version < 11.1.0.
2. Disable pgaudit from supabase.com database > extension dashboard.
3. Pause and Restore project.
4. Request any data through Javacript client.

## Expected behavior

Fetching data through Javascript should work.

## System information

- OS: macOS 13.4.1 (22F82) (Apple Silicon)
- Browser (if applies): Crhome 114.0.5735.198
- Version of supabase-js: 2.22.0
- Version of Node.js: 16.19.0

**Comment by qunash** [comment]
Hi, I'm facing the same issue. Have you been able to solve it?

**Comment by pitzcarraldo** [comment]
@qunash I could solve with below step.

1. enabled pgaudit again.
2. ran below queries.

```sql
alter role anon reset pgaudit.log;
alter role authenticated reset pgaudit.log;
alter role authenticator reset pgaudit.log;
alter role service_role reset pgaudit.log;
```

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
