### ISSUE TITLE
can not edit too long postgres function name on admin ui

### ISSUE THREAD

**Issue by matart15** [supabase/supabase#15819]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

if postgres function name is too long, admin ui's hover icon now showing

## To Reproduce

1. create sql function on admin
2. give function really long nae
3. edit button ( small arrow ) is not visible. don't show up on hover

## Screenshots

![image](https://github.com/supabase/supabase/assets/17027219/8eb9cbf6-1cac-41bb-9c95-e8bc71a85b1f)

## System information

- OS: windows
- Browser chrome

**Comment by Hallidayo** [comment]
Hi @matart15 - Are you still experiencing this? I can't seem to get the same behaviour:

<img width="220" alt="Screenshot 2023-07-19 at 21 07 03" src="https://github.com/supabase/supabase/assets/22655069/d8489bbe-4452-432d-9386-9b63902b2f09">

**Comment by matart15** [comment]
looks like tour query name have spaces. mine was single long word

**Comment by SuhelMakkad** [comment]
hey, just create a PR #16507 to fix this issue.
