### ISSUE TITLE
storage upload with upsert or update causes ERR_FS_EISDIR error on self-host environment

### ISSUE THREAD

**Issue by xshadowlegendx** [supabase/supabase#15824]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

fail to migrate storage objects from supabase cloud to self host server by replacing objects using supabase-js client sdk file upload api

## To Reproduce

migrate storage objects from supabase cloud to self host according to the [the doc](https://supabase.com/docs/guides/storage/uploads)

## Expected behavior

all storage object from supabase cloud successfully upload to self host

## Screenshots

<img width="855" alt="Screenshot 2023-07-17 at 16 31 50" src="https://github.com/supabase/supabase/assets/21999889/454d6263-5117-442f-837d-66f740a8c4fb">

logs from storage service

```
{"level":"info","time":"2023-07-17T09:07:52.233Z","pid":1,"hostname":"450ad9f8ea0d","job":"{\"id\":\"\",\"name\":\"object:admin:delete\",\"data\":{\"name\":\"cc606c59-33f9-4569-8de1-583d5474cbc2/profile-pic.png\",\"bucketId\":\"users\",\"tenant\":{\"ref\":\"stub\",\"host\":\"supabase.mysite.com\"},\"version\":\"5cf3682f-f97b-4edb-b543-693bfe2955f0\",\"$version\":\"v1\"}}","msg":"Handling ObjectAdminDelete"}
SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) /var/lib/storage/stub/stub/users/cc606c59-33f9-4569-8de1-583d5474cbc2/profile-pic.png
    at new SystemError (node:internal/errors:250:5)
    at new NodeError (node:internal/errors:361:7)
    at node:internal/fs/utils:803:17
    at FSReqCallback.oncomplete (node:fs:209:5) {
  code: 'ERR_FS_EISDIR',
  info: {
    code: 'EISDIR',
    message: 'is a directory',
    path: '/var/lib/storage/stub/stub/users/cc606c59-33f9-4569-8de1-583d5474cbc2/profile-pic.png',
    syscall: 'rm',
    errno: 21
  },
  errno: [Getter/Setter: 21],
  syscall: [Getter/Setter: 'rm'],
  path: [Getter/Setter: '/var/lib/storage/stub/stub/users/cc606c59-33f9-4569-8de1-583d5474cbc2/profile-pic.png']
}
```

## System information

- OS: ubuntu 22.04.2 lts
- Browser: nodejs, supabase client
- Version of supabase-js: @supabase/supabase-js@^2.26.0
- Version of Node.js: 18.15.0

NOTE: self host os is ubuntu and self host using docker, the browser and version of node and supabase are in local machine running the migration script

## Additional context

I also tried creating new bucket and upload one file to it, the upload was a success but the file was created within directory under the name of the object not sure if this is expected behavior and the studio wasnt able to show the preview(image file) but able to download the file back and open it to be the same file I uploaded

we just deploy the supabase by today and migrating everything over to self host, the deployment guide we follow is from [official doc](https://supabase.com/docs/guides/self-hosting/docker), the only things we changed are api keys, postgres password and max file size env var on storage service

<img width="2192" alt="Screenshot 2023-07-17 at 16 35 59" src="https://github.com/supabase/supabase/assets/21999889/0d05cc0d-f05c-4d3e-b98f-111433c4e67f">

according to storage service logs, it seems like storage api expect it to be file type instead of a directory that is why issuing `rm` fails when replacing those files

the `testxx` bucket was the test bucket I created from the studio and uploaded one test file

update0: So I checkout to v0.23.05 and use that version instead then upload works as expected now and migration run successfully but preview wasnt shown on studio, inspecting the network saw that it is getting the preview or thumbnail from `http://kong:8000`, so I went and change the `SUPABASE_URL` from `http://kong:8000` to `https://supabase.mysite.com` and now the preview also working now.

**Comment by ivasilov** [comment]
@xshadowlegendx is this issue fixed? Can we close it?

**Comment by xshadowlegendx** [comment]
hello @ivasilov I have not yet test the latest version, will let you know when I do

**Comment by xshadowlegendx** [comment]
hello @ivasilov the issue seems to still be there, and I tried the master branch and latest release `v0.23.09` now it has this [issue](https://github.com/supabase/supabase/issues/10977) which I could not upload anything

**Comment by encima** [comment]
Closing as update in initial description shows fixed
