### ISSUE TITLE
This is not solving the issue, on Coolify, simple docker deploy is not working

### ISSUE THREAD

**Issue by miguelgargallo** [supabase/supabase#15856]
Issues with Self-hosted have been resolved, the initial setup using the guides works out of the box. Would you mind if we move this BYO security talk to a GH discussion? We could work on a community guide if these issues can be resolved on a discussion.

_Originally posted by @pucho in https://github.com/supabase/supabase/issues/10074#issuecomment-1357999752_

**Comment by silentworks** [comment]
I'm closing this out as you haven't stated any issue here. The original issue you are linking to was resolved as stated in that issue.
