### ISSUE TITLE
Can't Reset Supabase account

### ISSUE THREAD

**Issue by HaseaGhebyon** [supabase/supabase#15851]
I can't reset my password account from forgot password. In this case my account is organization account

**Comment by gregnr** [comment]
Hey @HaseaGhebyon! This is probably a good candidate for a support ticket, feel free to open one to help resolve. If you feel this is truly bug, some more details to help reproduce would help a lot. Thanks!

**Comment by dawinsor** [comment]
We have just noticed the same problem - the password reset link (that was working previously) is now behaving like a magic link. The password reset is not prompting a password reset.

**Comment by jigz** [comment]
not sure if this is related, I tried to reset the password on a github linked account hoping it will just let me add a password like in most cases. if it's not a feature, perhaps make a ticket for it.

**Comment by J0** [comment]
Hey team, 

Auth team here- thanks for reporting the issue! I'm trying on my end and unfortunately can't replicate the issue which surfaces doing a password reset on supabase.com. If the issue persists could we trouble y'all to reach out to support via [our support form](https://supabase.com/dashboard/support/new) as @gregnr mentioned?

Thanks!
