### ISSUE TITLE
Self-hosted with docker: Where in the config do I allow CORS requests for the auth server?

### ISSUE THREAD

**Issue by Ddfulton** [supabase/supabase#15867]
Am up and going on Docker with no problems and trying to make an "MVP" for self-hosted auth within my company.

Trying to run a vanilla JS auth:
```
var SUPABASE_URL = 'http://10.195.246.14:3000/';
var SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE';
var supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY)


window.userToken = null

document.addEventListener('DOMContentLoaded', function (event) {
  var signUpForm = document.querySelector('#sign-up')
  signUpForm.onsubmit = signUpSubmitted.bind(signUpForm)

  var logInForm = document.querySelector('#log-in')
  logInForm.onsubmit = logInSubmitted.bind(logInForm)

  var userDetailsButton = document.querySelector('#user-button')
  userDetailsButton.onclick = fetchUserDetails.bind(userDetailsButton)

  var logoutButton = document.querySelector('#logout-button')
  logoutButton.onclick = logoutSubmitted.bind(logoutButton)
})

const signUpSubmitted = (event) => {
  event.preventDefault()
  const email = event.target[0].value
  const password = event.target[1].value

  supabase.auth
    .signUp({ email, password })
    .then((response) => {
      response.error ? alert(response.error.message) : setToken(response)
    })
    .catch((err) => {
      alert(err)
    })
}
```

Was hit with the classic CORS error

<img width="551" alt="image" src="https://github.com/supabase/supabase/assets/12734718/68ea97d7-6c86-406d-b30e-923da2306170">

I stumbled upon [this tutorial](https://dev.to/the_cozma/kongplugin-cors-fixing-access-control-allow-origin-header-missing-error-iao) which suggested a modification to `kong.yml` but it did not work at all.

Where in the config can I specify to allow cors for the auth server?

**Comment by weykon** [comment]
+1 subscribe this topic

Not only self-host, but also when I was in local-development testing the edge functions

**Comment by osener** [comment]
I am getting CORS errors when I'm trying to use Supabase Local setup with Github Codespaces. How can I set the CORS headers in my `supabase/config.toml`?

**Comment by encima** [comment]
Closing the issue as it seems to be solved by the port visibility. Also, see the documentation for setting the [OPTIONS](https://supabase.com/docs/guides/functions/cors) and, locally, you can use a CORS extension for the browser.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
