### ISSUE TITLE
Issue with nuxt.js auth example with gotrue-js regression

### ISSUE THREAD

**Issue by hedefalk** [supabase/supabase#15887]
# Bug report
Trying to follow the example at https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3 didn't work for me. 
## Describe the bug

There is a log warning:

>Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.

I tried to pinpoint by cloning this repo and running the example from within supabase/examples/user-management/nuxt3-user-management and there it worked fine.

It turns out that I got @supabase/gotrue-js@2.44.1 in my own testing while the main repo example got @supabase/gotrue-js@2.29.0.

## To Reproduce
Just use main repo example over at

supabase/examples/user-management/nuxt3-user-management

add 

```
  "overrides": {
    "@supabase/gotrue-js": "2.44.1"
  }
```

in package.json (for npm)

npm install
npm run dev

Go through the email login form and hit the link you get in the email

## Expected behavior
Coming back from mail otp link should render 
## Screenshots
Success with @supabase/gotrue-js@2.29.0:
<img width="1218" alt="image" src="https://github.com/supabase/supabase/assets/116520/38593b1e-7a8d-4bd2-ab68-4cff08778450">

Failure with @supabase/gotrue-js@2.44.1:

<img width="1231" alt="image" src="https://github.com/supabase/supabase/assets/116520/389537a0-e31c-4306-9627-cffe82a03161">

<img width="1440" alt="image" src="https://github.com/supabase/supabase/assets/116520/a6bc2fd5-e6ea-4cd3-b6d3-dc18c50c0f4c">

## System information

- OS: macOS
- Browser chrome

@supabase/supabase-js@"2.24.0

🐟 node --version
v18.16.0

**Comment by trueter** [comment]
Probably related: 
The latest `@supabase/gotrue-js` updates have broken my login page. Using Google sign in and the below snippet, user.value does not seem to update. Pinning the override to `"@supabase/gotrue-js": "2.42.0"` circumvents the problem:


```js
const user = useSupabaseUser()
watch(
  () => user.value,
  async () => {
    // handle login
  }
)
```

**Comment by staniboy** [comment]
Thank you for reporting, I was wondering why I'm getting this.

**Comment by Hallidayo** [comment]
Hi all, due to the recent upgrades to the nuxt modules, I'm going to close this one but feel free to re-open if still an issue.
