### ISSUE TITLE
supabase.auth.api.setAuthCookie() doesn't work in Next.JS

### ISSUE THREAD

**Issue by laurencebedford** [supabase/supabase#15942]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the Docs, GitHub Discussions, and Discord.

## To Reproduce

1. Use the following code snippet in my Next.js API route:

```javascript
import { supabase } from 'src/libs/supabase';

const handler = async (req, res) => {
  await supabase.auth.api.setAuthCookie(req, res);
};

export default handler;
```

Then in my auth provider every time my user object auth state changes with supabase we run this code:
```
// Use the `session` object from `onAuthStateChange`
      axios.post('/api/stripe/set-supabase-cookie', {
        event: updatedUser ? 'SIGNED_IN' : 'SIGNED_OUT',
        session: session, // Use the session object directly
      });

```

Now the page /api/stripe/set-supabase-cookie is responding with an error 500 stating that the auth.api.setAuthCookie() is not a valid function. I understand that this may be right but your docs doesn't state what function replaced it or how to fix this.
 
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [this](https://egghead.io/courses/build-a-saas-product-with-next-js-supabase-and-stripe-61f2bc20) egghead course by Jon Meyers
2. Download his [repository](https://github.com/dijonmusters/build-a-saas-with-next-js-supabase-and-stripe/tree/master/26-configure-stripe-for-production-and-deploy-next-js-application-with-vercel) by cloning this GitHub
3. Set it up and you'll get the issue with the API route.

## Expected behavior

The api should give a response 200 and not error on that function.

## Screenshots

N/A

## System information

- OS: [macOS]
- Browser: [chrome]
- Version of supabase-js: ["@supabase/supabase-js": "^2.26.0",]

## Additional context

I never usually jump straight to the GitHub however, im completely stuck now there's nothing mentioned online about this. I look forward to hearing a response. Thanks for your help!

**Comment by saltcod** [comment]
Hey @lawrencecchen sorry you've run into this 
That course is a little outdated in its NextJS implementation. 

This one would reflect the current latest thinking: 
https://egghead.io/courses/build-a-twitter-clone-with-the-next-js-app-router-and-supabase-19bebadb

If you're starting from scratch, might be good to run 
`$ npx create-next-app -e with-supabase` 

to see how all the pieces fit together now. 

Hope this helps!
