### ISSUE TITLE
Error when running "npx supabase db diff" - Unexpected EOF while connecting to remote database

### ISSUE THREAD

**Issue by mrTorb** [supabase/supabase#15960]
### Discussed in https://github.com/orgs/supabase/discussions/15140

<div type='discussions-op-text'>

<sup>Originally posted by **Hamzah-syed** June 17, 2023</sup>
Issue Description:
When attempting to run the command "npx supabase db diff" on Windows with Docker, an error is encountered stating "Error: failed to connect to host=localhost user=postgres database=postgres: failed to receive message (unexpected EOF)". This error occurs while trying to connect to the remote database and create a shadow database. It is worth noting that Supabase Studio is working fine without any issues.

Steps to Reproduce:

Install Supabase CLI using npm.
Set up a Supabase project and obtain the necessary connection parameters.
Ensure Docker is running on the Windows machine.
Open a terminal or command prompt and navigate to the project directory.
Run the command "npx supabase db diff".
Expected Behavior:
The "npx supabase db diff" command should connect to the remote database, create a shadow database, and display any pending database schema changes.

Actual Behavior:
The command fails with the following error message:
"Error: failed to connect to host=localhost user=postgres database=postgres: failed to receive message (unexpected EOF)"

Additional Information:

Supabase Studio is working correctly, indicating that the issue is specific to the "npx supabase db diff" command.
The Windows operating system and Docker are being used.
Running the command with the "--debug" flag may provide more detailed information for troubleshooting.
Possible Solutions:</div>

**Comment by mibacode** [comment]
I have run into the same issue.  However if I run the command with the `--debug` flag, it works.

**Comment by mibacode** [comment]
I was able to successfully run it today without `--debug`.  I believe it might have been because I had corrected some issues in my migration file which was preventing me from running `db reset`.  After correcting the issues and running reset, it worked.

**Comment by akshitgautam42** [comment]
I have run into the same issue. However if I run the command with the --debug flag, it works. Also if not try to change shadow_port = 54320 it will start working

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
