### ISSUE TITLE
[Database] .order is not giving correct results

### ISSUE THREAD

**Issue by TommyDong1998** [supabase/supabase#15966]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```
    const { data } = await supabase
      .from('table1')
      .select('*')
      .eq('booleanTest', false)
      .order('created_at', { ascending: false });
```
       
Is not returning all the false results. When I remove the .order it looks to be working fine. I got around this by using

const data =
      await sql`select * from table1 where booleanTest=false order by created_at DESC`;

and it gives the correct results.

## To Reproduce

Create a table with booleanTest(bool) and created_at(timestamptz) and populate it.

run this:

  ```
  const { data } = await supabase
      .from('table1')
      .select('*')
      .eq('booleanTest', false)
      .order('created_at', { ascending: false });
```

## Expected behavior

.order will sort the results instead of deleting some of them

## System information

- OS: Windows 11
- Version of supabase-js: 2.26.0
- Version of Node.js: v18.14.1

**Comment by GaryAustin1** [comment]
Can you try .is instead of .eq?  I can never remember if .eq works with boolean or not in the client code.
Also is your column name showing with the capital letter in the table UI?

**Comment by TommyDong1998** [comment]
Thanks for the reply. It is working fine now.
