### ISSUE TITLE
Twitter auth documentation lacks clear instruction for local setup. 

### ISSUE THREAD

**Issue by sarojregmi200** [supabase/supabase#15972]
# Problem
The documentation part of the login with twitter is great but it lacks one key information when developing application if we are in development mode and which means we don't yet have a valid web URL and `localhost:port` is not considered as a valid website URL by the twitter developer console. And we cannot continue without the website URL.

## Link 
https://supabase.com/docs/guides/auth/social-login/auth-twitter

## Solution
when we are in development mode we can use `www.localhost:port` as a valid URL. 
This is a simple piece of information but many of the beginners don't know this, and have to wonder around like I did while I tried login with twitter for the first time.

PS: I will be more than happy to add the following piece of information to the documentation

**Comment by sarojregmi200** [comment]
I got mine working, I was saying it would be great if we could add it to the docs it will be more clear.

**Comment by gregnr** [comment]
Agreed - would love to see a PR for this (preferring `127.0.0.1` over `www.localhost` if possible)

**Comment by sarojregmi200** [comment]
On my way 🚀

**Comment by sarojregmi200** [comment]
Hey, @gregnr 
I just gave `127.0.0.1` a try but it looks like it is not accepted as a valid web URL by twitter.
![image](https://github.com/supabase/supabase/assets/94213188/875761f6-03f3-44a9-a244-82bb58a73bcd)
![image](https://github.com/supabase/supabase/assets/94213188/2acccecf-349b-4e66-9bfd-a3cb1f7ad550)

And I have also tried `http://www.localhost:port` and it works fine.
I have also tried running it with my project and the auth goes fine.
Here, is the developer screen.
![image](https://github.com/supabase/supabase/assets/94213188/96a5c0d2-c7cd-4dc9-831f-71bc8172fa14)

And let me show it in action to verify if the auth works fine or not.
![image](https://github.com/supabase/supabase/assets/94213188/daa1f246-fca9-4e3b-b993-508679e868bb)
Auth btn:
![image](https://github.com/supabase/supabase/assets/94213188/6a182b7a-9ce7-46e8-857d-45b66f9fe20c)

Auth api redirect:
![image](https://github.com/supabase/supabase/assets/94213188/efef273d-cdbf-4285-8292-f76224f38127)

And finally redirect back to the home page with the access token.
![image](https://github.com/supabase/supabase/assets/94213188/581c5328-e8ca-4e46-9188-dfd8a5d80652)


It took me a while to get this results cause I saw yet another error, which is provided in #4677 I was able to solve that by turning on 
![image](https://github.com/supabase/supabase/assets/94213188/ac95aa10-c861-4e5d-a982-cb93c1fb5bc4)
This in the developer settings, and after that it was a compulsion to provide a privacy policy and terms of services.

Anyways as of my research, your suggestion is correct theoretically but does not work in practice, So, after verification I conclude that using `www.localhost:port` is the best option so far and will submit a pull request updating the docs as soon as possible.

**Comment by sarojregmi200** [comment]
Hey @gregnr,
I have fixed the problem in my PR.
Can you please review it?
