### ISSUE TITLE
\\u0000 cannot be converted to text.

### ISSUE THREAD

**Issue by samueladriantrif** [supabase/supabase#15995]
### Discussed in https://github.com/orgs/supabase/discussions/2264

<div type='discussions-op-text'>

<sup>Originally posted by **indahud** July  7, 2021</sup>
I don't understand why I am getting this error. I am trying to insert some data. I don't have anything like `\\u0000` in my data. 
Here's error code and message.
```JavaScript
details: "\\u0000 cannot be converted to text."
code: "22P05"
message: "unsupported Unicode escape sequence"
```

Any ideas how I can resolve this issue? I am not able to understand what is causing the error. 
```Javascript
const InsertData = async (req, res) => {
  try {
    const { data, error } = await supabase.from('testdb').insert([])  
    return res.status(200).json({
      messgae: "Data Inserted",
      data: data,
      error: error,
    });
  } catch (error) {
    console.log(error);
  }
}
```
</div>

**Comment by markthepixel** [comment]
i am running into the same error on the python side

**Comment by burggraf** [comment]
`.insert([])`
This looks like you're trying to insert an empty array into the table.  Can you describe what you're trying to do here?  Inserting "nothing" doesn't make sense here, unless I'm missing something.
