### ISSUE TITLE
Typescript type check 'SupabaseQueryClient' for '.eq' is failing

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#160]
# Bug report

## Describe the bug

I am running a type check on my class and it is throwing a type error on the '.eq' call.

Here is my class:
```
import SupabaseService from '../services/SupabaseService';

import { Invitation } from '../interfaces/invitation.interface';

class InvitationRepository {
  eventId: string;
  constructor(eventId) {
    this.eventId = eventId;
  }

  async update(invitationId, invitation) {
    return await SupabaseService
      .from<Invitation>('invitation')
      .eq('id', invitationId)
      .update(invitation);
  }

  async remove(invitationId) {
    return await SupabaseService
      .from<Invitation>('invitation')
      .eq('id', invitationId)
      .delete();
  }
}

export default InvitationRepository;
```

The typecheck is throwing: `Property 'eq' does not exist on type 'SupabaseQueryClient<Invitation>'.`

<img width="1049" alt="Screen Shot 2020-08-30 at 8 29 29 PM" src="https://user-images.githubusercontent.com/6392501/91673037-fd923900-eaff-11ea-963a-7352faf237ed.png">

## Expected behavior

Based on the [documentation](https://supabase.io/docs/library/delete#eq) this syntax should work.

## System information

- OS: macOS
- Version of supabase-js: 0.36.4
- Version of Node.js: v12.12.0

**Comment by thorsten-stripe** [comment]
@zlwaterfield thanks for reporting this, with TypeScript support we've decided to enforce a method chaining hierarchy, meaning you will have to switch the chaining sequence to put the `delete/update` operation before the filter method:

```js
await SupabaseService
      .from<Invitation>('invitation')
      .delete()
      .eq('id', invitationId);
```

@kiwicopple it looks like we missed to update the docs for `delete` and `update`.

**Comment by zlwaterfield** [comment]
@thorsten-stripe, great thanks for the clarification. I can make a PR to update the documentation.

**Comment by zlwaterfield** [comment]
Here is a PR for the documentation fix: https://github.com/supabase/supabase/pull/161

**Comment by kiwicopple** [comment]
Fixed by https://github.com/supabase/supabase/pull/161
