### ISSUE TITLE
Cannot reset local Supabase DB with CLI

### ISSUE THREAD

**Issue by jeanmatthieud** [supabase/supabase#16002]
# Bug report
I'm trying to get my local environment in line with the production.

## Describe the bug

- [Supabase.com] Database created and schema edited
- [Local] Create and link the supabase project with CLI
- [Local] `supabase start`
- [Local] `supabase db remote commit`: the first migration file is created
- [Local] `supabase db reset` produces an error:

```
ERROR: schema "extensions" already exists (SQLSTATE 42P06)
At statement 10: CREATE SCHEMA "extensions" 
```

## System information

- OS: Windows + Docker => Debian
- Supabase CLI: 1.81.1

**Comment by bejoyfuuul** [comment]
This bug is the same for me.
After `db reset` getting an error when through the `migration` again. how fix it?

**Comment by valentinceaprazaru** [comment]
I have the same issue.

**Comment by makaliifernandez** [comment]
same here

**Comment by kishanhitk** [comment]
Did you try using the new `supabase db pull` command, instead of `db remote commit`?

**Comment by ZetiMente** [comment]
the migrations with supabase never seems to work.

**Comment by encima** [comment]
`db remote commit` has been deprecated and `db pull` is the new command to use.
I have verified this is working using supabase CLI 1.127.4 and 1.131.1:
- `supabase link`
- `supabase start`
- `supabase db pull`
- `supabase db reset`

Please comment if this still occurs and we will reopen
