### ISSUE TITLE
When reload setting > Auth page, it shows smtp setting off even though it is on.

### ISSUE THREAD

**Issue by hawkcookie** [supabase/supabase#16042]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When reload setting > Auth page, it shows smtp setting off even though it is on.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'dashboard'
2. Click on 'Settings > Auth'
3. Scroll down to 'SMTP Settings'
4. it shows toggle on and if you reload the page, it shows toggle off.

## Expected behavior

it keeps toggle on.

## Screenshots

https://github.com/supabase/supabase/assets/29660904/00d20a98-38fd-4a8a-a772-0deb5d577850

## System information

- OS: [macOS]
- Browser (if applies) [chrome]

**Comment by GaryAustin1** [comment]
https://github.com/supabase/supabase/pull/16044
