### ISSUE TITLE
supabase-js rpc call error:  message: 'a column definition list is required for functions returning "record"'

### ISSUE THREAD

**Issue by bbagherian** [supabase/supabase#16058]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Following this documentation leads to an error on `rpc` call: https://supabase.com/docs/guides/database/extensions/postgis 

```js
{
    "code": "42601",
    "details": null,
    "hint": null,
    "message": "a column definition list is required for functions returning \"record\""
}
```

## To Reproduce

SQL on the website dashboard: 

```sql
create table if not exists public.restaurants (
	id int generated by default as identity primary key,
	name text not null,
	location geography(POINT) not null
);

create index restaurants_geo_index
  on public.restaurants
  using GIST (location);

insert into public.restaurants
  (name, location)
values
  ('Supa Burger', st_point(-73.946823, 40.807416)),
  ('Supa Pizza', st_point(-73.94581, 40.807475)),
  ('Supa Taco', st_point(-73.945826, 40.80629));


create or replace function nearby_restaurants(lat float, long float)
returns setof record
language sql
as $$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.restaurants
  order by location <-> st_point(long, lat)::geography;
$$;

```

and now in the app:
```js
const { data, error } = await supabase.rpc('nearby_restaurants', {
  lat: 40.807313,
  long: -73.946713,
})

console.log('rpc restaurant', data, error);
```

## Expected behavior

List of results

## Screenshots

![image](https://github.com/supabase/supabase/assets/19957924/0b44f4c9-fa5a-42a2-8aec-0c19c6eb1168)

## System information

- OS: [windows]
- Browser (if applies) [chrome]
- Version of supabase-js: [2.26.0]
- Version of Node.js: [18.16.1]

**Comment by bbagherian** [comment]
when I run it as query it's ok by the way:

![image](https://github.com/supabase/supabase/assets/19957924/6d471bdb-2c2d-4291-9ea2-b5fca2a8c107)

**Comment by qwerqy** [comment]
having this issue as well. running it on SQL works, but when running it on javascript, it shows that error.

**Comment by stevenkeezer** [comment]
I was able to solve this by modifying the provided example for creating the function in supabase to return a table:

Supabase Example: 
`create or replace function nearby_restaurants(lat float, long float)
returns setof record
language sql
as $$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.restaurants
  order by location <-> st_point(long, lat)::geography;
$$;`

Modified: 
`CREATE OR REPLACE FUNCTION nearby_restaurants(long double precision, lat double precision)
RETURNS TABLE (id integer, name text, location text, dist_meters double precision)
AS $$
  SELECT id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  FROM public.restaurants
  ORDER BY location <-> st_point(long, lat)::geography;
$$ LANGUAGE sql;`

**Comment by qwerqy** [comment]
Hey @stevenkeezer , thanks for the reply. I have resorted to return a table for my use case as well. 😄

**Comment by steve-chavez** [comment]
This is the same issue as https://github.com/supabase/postgrest-js/issues/453, will close and move the discussion there. 

Note that it's already fixed upstream, but not yet deployed to Supabase.
