### ISSUE TITLE
Used sign up link not redirecting

### ISSUE THREAD

**Issue by jaredramirez** [supabase/supabase#1607]
# Bug report

## Describe the bug

If you open a sign in link twice, the second time it is invalid. Even though it's invalid, it should still redirect to the sign in URL rather than showing the cryptic error: `{"code":404,"msg":"User not found"}`

## To Reproduce

1. Sign up as an new user with the magic link method
2. Open your email and press the sign in link
3. Go back to your email and press the sign in link again
4. See error page with `{"code":404,"msg":"User not found"}`

## Expected behavior

Supabase should still redirect to the URL in the project's config and it should be the supabase user's (me in this case) responsibility to display an error message to my user that this link is invalid.

## Additional context

**Comment by ymilhahn** [comment]
Hello @jaredramirez,
apparently a fix is already on the way: #504 

Best
Yannick

**Comment by jaredramirez** [comment]
Ah got it! Closing in favor of https://github.com/supabase/supabase/issues/504
