### ISSUE TITLE
by using npx supabase login terminal get stuckes i m expecting to write access token there but after this comand terminal is not working properly

### ISSUE THREAD

**Issue by Uamirfarooq** [supabase/supabase#16088]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
If you are filing a bug report please add more info.  You have nothing but a title.  This might be better off as a discussion otherwise.  Thanks.
