### ISSUE TITLE
Unable to log into Supabase Dashboard with Github

### ISSUE THREAD

**Issue by alexrabin** [supabase/supabase#16083]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Attempting to log in with Github on the supabase dashboard results in a "upstream request timeout" error message in the browser.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase Dashboard sign in https://app.supabase.com/sign-in
2. Click on Continue with Github
3. The browser times out shows the error: "upstream request timeout"

## Expected behavior

I should be able to sign into the supabase dashboard

## Screenshots

https://github.com/supabase/supabase/assets/15949910/87eb679b-bb22-40dd-b3be-fc2535252f9f

## System information

- OS: macOS
- Browser: Safari and Chrome

**Comment by gabrielcerono** [comment]
I am having the same problem!

**Comment by albertshih3** [comment]
Same here! It seems to be more of a general problem as I was already logged in but I could no longer edit my tables and heading to the dashboard caused the page to loop indefinitely.

**Comment by jcornil** [comment]
Same and I'm getting 'upstream request timeout' error from alt.supabase.io domain.

**Comment by alexrabin** [comment]
I'm able to login again. @jcornil  @albertshih3 @gabrielcerono  are you guys able to as well?

**Comment by albertshih3** [comment]
Yup! Looks like I can log in as well :D

**Comment by jcornil** [comment]
> I'm able to login again. @jcornil @albertshih3 @gabrielcerono are you guys able to as well?

It works now.

**Comment by alexrabin** [comment]
Closing this issue.
