### ISSUE TITLE
Updating a row with composite primary key updates unnecessary columns

### ISSUE THREAD

**Issue by Polyterative** [supabase/supabase#1610]
# Bug report

## Describe the bug

Updating a row with composite primary key updates unnecessary columns.
I guess the problem is there but I'm not super sharp with SQL

## To Reproduce

Create a table like this
![image](https://user-images.githubusercontent.com/16295552/118726697-f8ae1a80-b831-11eb-8a61-f9bfd2779400.png)

## Expected behavior

Updating a single row should not affect the others
## Screenshots

https://streamable.com/cjzol3

## System information

- OS: Windows
- Browser chrome 90

## Additional context
if you wanna look at it:
app.supabase.io/project/sozmatmywjpstwidzlss/

**Comment by kiwicopple** [comment]
Definitely a bug. Thanks for reporting @Polyterative - we're about to release an updated datagrid and I'll add this to the testing check list

**Comment by joshenlim** [comment]
hey there @Polyterative! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
