### ISSUE TITLE
OTP fails in local dev environment with v2.31.0

### ISSUE THREAD

**Issue by stlbucket** [supabase/supabase#16100]
https://github.com/nuxt-modules/supabase/issues/216

The above link is to an issue in the nuxt/supabase plugin.

The following link is to a reproduction of the problem:
https://github.com/stlbucket/supabase-cli-bug

That is a clone of the nuxt/supabase plugin repo, update of the supabase-js lib to 2.31.0, and addition of OTP login.  Just follow the directions and you will see the bug.

<img width="1110" alt="image" src="https://github.com/supabase/supabase/assets/2467892/4aa39207-e1ba-46c4-ad77-2eefbce51730">

**Comment by stlbucket** [comment]
I have verified this is an issue with the latest local dev setup.  supabase 1.82.2 was released 10 hours ago.  I deleted all my local docker images and upgraded them.  The error still happens.

**Comment by stlbucket** [comment]
from the @nuxt/supabase module:

```
    // Transpile @supabase/go-true package only on client side
    // TODO: Remove when packages fixed with valid ESM exports
    // https://github.com/nuxt-community/supabase-module/issues/54
    nuxt.options.build.transpile.push(
      ({ isServer }) => !isServer && '@supabase/gotrue-js'
    )

    // Transpile websocket only for non dev environments (except cloudflare)
    if (!nuxt.options.dev && !['cloudflare'].includes(process.env.NITRO_PRESET as string)) {
      nuxt.options.build.transpile.push('websocket')
    }

    // Optimize @supabase/ packages for dev
    // TODO: Remove when packages fixed with valid ESM exports
    // https://github.com/supabase/gotrue/issues/1013
    extendViteConfig((config) => {
      config.optimizeDeps = config.optimizeDeps || {}
      config.optimizeDeps.include = config.optimizeDeps.include || []
      config.optimizeDeps.exclude = config.optimizeDeps.exclude || []
      config.optimizeDeps.include.push(
        '@supabase/functions-js',
        '@supabase/gotrue-js',
        '@supabase/postgrest-js',
        '@supabase/realtime-js',
        '@supabase/storage-js',
        '@supabase/supabase-js'
      )
    })
```

would these be causing the problem?

**Comment by stlbucket** [comment]
this is my config.toml file:

```
[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3025"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:3025","http://localhost:3025/my-profile","http://localhost:3000/confirm"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
```

off-topic, but seems odd that there are two enable_signup entries?

**Comment by j4w8n** [comment]
So is it just that the email link isn't inserting the port after `localhost`?

**Comment by stlbucket** [comment]
@j4w8n - you mean it should be:

localhost:54321/auth...

??

**Comment by AnkushSarkar10** [comment]
I am having same issue

**Comment by stlbucket** [comment]
https://github.com/stlbucket/vue-supabase-initialize

i have made another test repository here that excludes nuxt - just uses vue

it appears to NOT have the same issue...   https://github.com/nuxt-modules/supabase/issues/216

so i think we are back to the nuxt module

**Comment by stlbucket** [comment]
the bug happens here - maybe someone can verify they get the same behavior with this repo?

https://github.com/stlbucket/supabase-cli-bug

this is a sanity check to take nuxt out of the loop - i think this verifies it's a problem with the nuxt plugin:

https://github.com/stlbucket/vue-supabase-initialize

**Comment by stlbucket** [comment]
sorry - closing was an accident

i have done a couple of other tests, and i think this is actually due to the state of my local supabase project.

isolating vue/supabase and nuxt/supabase in the above projects, and building fresh supabase environments for each seems to make the issues go away.

i am still trying to isolate the problem, though.

**Comment by stlbucket** [comment]
I have done enough reduction of the problem that I am pretty sure it is a problem with my local supabase project - i must have corrupted the configuration somehow

I am happy to help diagnose this further, but as far as I am concerned, this can be closed.

Others may have differing opinions

**Comment by silentworks** [comment]
I can replicate this when doing email change requests locally, I will check with the team what changed as this was working before.

**Comment by coryvirok** [comment]
Related - https://github.com/orgs/supabase/discussions/15936

**Comment by silentworks** [comment]
A fix for this was merged in yesterday and will be out on the next CLI release. You should be able to test this out using the beta channel of the CLI.

```sh
npx supabase@beta start
```

**Comment by madooei** [comment]
I kept searching for this issue with keywords such as "magic link" or "passwordless." I didn't try OTP. I'm leaving this comment here for others' sake! Thanks for the fix @silentworks !

**Comment by stlbucket** [comment]
I am now getting this error when using the OTP link:
```
PKCE flow is not supported on signups with autoconfirm enabled
```
I've built a new repository from scratch and am getting

my code:
```
  const supUser = useSupabaseUser()
  const supabase = useSupabaseClient()
  const email = ref('')

  const handleLogin = async () => {
    const { error } = await supabase.auth.signInWithOtp({
      email: email.value,
      options: {
        emailRedirectTo: 'http://localhost:3025/my-profile'
      }
    })
    if (error) {
      alert(error.message)
    }
    alert('Check your email inbox for the magic link!')
  }
```

**Comment by stlbucket** [comment]
is this a new setting?  i already had to figure out the auto-redirect...

**Comment by stlbucket** [comment]
https://supabase.nuxtjs.org/get-started#clientoptions

the cause was the new default of pkce flowType in nuxt/supabase
