### ISSUE TITLE
Unable to start supabase/studio:v0.23.06 on docker (exit code 139)

### ISSUE THREAD

**Issue by mangott** [supabase/supabase#16122]
# Bug report

While following the tutorial on [self-hosting with docker](https://supabase.com/docs/guides/self-hosting/docker), I had a problem with the Docker instance supabase/studio. I could not start it and it keeps restarting and exiting with the following error:

```
supabase-studio                 | info  - Loaded env from /app/studio/.env
supabase-studio                 | Listening on port 3000
supabase-studio                 | No storage option exists to persist the session, which may result in unexpected behavior when using auth.
supabase-studio                 |         If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
supabase-studio exited with code 139
```

## Describe the bug

supabase/studio Docker instance keeps restarting and exit with code 139

## To Reproduce

```
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Start
docker compose up
```

## Expected behavior

A running supabase/studio docker instance

## System information

- OS: macOS 13.2.1 Intel i5
- Docker: 24.0.2

## Additional context

I was able to fix the problem by changing to the latest version of supabase/studio docker image in the docker/docker-compose.yml file instead of the v0.23.06 version.

**Comment by kiwicopple** [comment]
fwiw, I didn't encounter this problem on Friday (Ubuntu) while debugging someone else's issue:

https://share.descript.com/view/oDcpJGnFwRo

@mangott can you try this sequence instead:

```
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Pull images
docker compose pull

# Pull start
docker compose up -d

# Show status
docker compose ps
```

That's the exact sequence I used in the video. In theory it shouldn't make a difference, but I wonder if somehow the `docker compose up` is failing while waiting for images to download

**Comment by mangott** [comment]
Thank you for your reply and support @kiwicopple

Unfortunately I have the same problems as in my first report. I deleted all Docker containers and images before running your commands. Docker was freshly installed on my computer yesterday.

The output of `docker compose ps` is:

```
NAME                             IMAGE                            COMMAND                   SERVICE             CREATED              STATUS                            PORTS
realtime-dev.supabase-realtime   supabase/realtime:v2.10.1        "/usr/bin/tini -s -g…"    realtime            About a minute ago   Up 49 seconds (healthy)           
supabase-auth                    supabase/gotrue:v2.62.1          "gotrue"                  auth                About a minute ago   Up 49 seconds (healthy)           
supabase-db                      supabase/postgres:15.1.0.90      "docker-entrypoint.s…"    db                  About a minute ago   Up About a minute (healthy)       0.0.0.0:5432->5432/tcp
supabase-edge-functions          supabase/edge-runtime:v1.6.6     "edge-runtime start …"    functions           About a minute ago   Up About a minute                 
supabase-imgproxy                darthsim/imgproxy:v3.8.0         "imgproxy"                imgproxy            About a minute ago   Up About a minute (healthy)       8080/tcp
supabase-kong                    kong:2.8.1                       "bash -c 'eval \"echo…"   kong                About a minute ago   Up About a minute (healthy)       0.0.0.0:8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, 8444/tcp
supabase-meta                    supabase/postgres-meta:v0.66.3   "docker-entrypoint.s…"    meta                About a minute ago   Up 49 seconds (healthy)           8080/tcp
supabase-rest                    postgrest/postgrest:v11.1.0      "/bin/postgrest"          rest                About a minute ago   Up 49 seconds                     3000/tcp
supabase-storage                 supabase/storage-api:v0.40.4     "docker-entrypoint.s…"    storage             About a minute ago   Up 48 seconds (healthy)           5000/tcp
supabase-studio                  supabase/studio:v0.23.06         "docker-entrypoint.s…"    studio              About a minute ago   Restarting (139) 25 seconds ago   
```

<img width="989" alt="grafik" src="https://github.com/supabase/supabase/assets/77860693/fd966506-b7c3-4225-87be-9e1aa3c921ef">

There are, unfortunately, no more log messages than the ones I have already posted. The command `docker compose up -d` executed without any failures.

Since this is probably a one-off error on my mac computer, you can close this issue. I assume that it will work again automatically with the next release of supabase/studio. I am currently using the latest version of supabase/studio docker image, where I do not face this problem. I just wanted to document the error in case other people have the same problem. 

Thank you!

**Comment by darmie** [comment]
I still have this problem

**Comment by mangott** [comment]
> I still have this problem

Open file docker/docker-compose.yaml and replace line `supabase/studio:v0.23.06` with `supabase/studio`. Then delete all of your docker instances and re-run the comand above.
