### ISSUE TITLE
Supabase Realtime Replication Managment

### ISSUE THREAD

**Issue by UnRealReincarlution** [supabase/supabase#1613]
# Bug report

## Describe the bug

When attempting to enable realtime replication through the web client in Database > Replication, when clicking on the All Tables button, the page redirects to an unexpected error occurs
with:

`TypeError: Cannot read property 'find' of null`

logged to the client console.
This error occurred after I selected the 'all tables' option for replication, after the changes took effect - I can no longer visit this page.

## To Reproduce

1. Go to **Supabase Web Client (in a project)**
2. Click on **Database**
3. Click on  **Replication**
4. Click on **All Tables**
5. Error Page Shown

## Expected behavior

A page showing a list of all possible tables that can be replicated to supabase_realtime

## Screenshots

It just says **An unexpected error occurred.** - template nextjs error page.

console:
![bug_report](https://user-images.githubusercontent.com/37007079/118789386-d62b0880-b8e8-11eb-9cea-d7ce669baf8b.PNG)

## System information

- OS: **Windows**
- Browser **Brave (fairly certain this is a non-browser specific issue)**

## Additional context

I believe this is likely a common Javascript bug with displaying values from an object that do not exist so simply a ?.find() or checking if the object exists will likely solve the issue.

**Comment by kiwicopple** [comment]
Thanks for the bug report @UnRealReincarlution - fixing this now

**Comment by kiwicopple** [comment]
This is fixed now. thanks again for the bug report !
