### ISSUE TITLE
webhook with bigint

### ISSUE THREAD

**Issue by neves** [supabase/supabase#16147]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

ids like 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://webhook.site and create a test url
2. create a table with a bigint id
3. create a webhook on this table pointing to the generated url above
4. insert a record with a id = 9_123_456_789_654_321
5. Check the webhook, you'll see that the id is different (lost precision)

## Expected behavior

The best option for those cases is to convert all bigints into string

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
Are you sure the webhook site is not javascript and can handle bigint properly?
Normally javascript numbers can't handle large bigint values, it drops precision. 
https://www.smashingmagazine.com/2019/07/essential-guide-javascript-newest-data-type-bigint/
