### ISSUE TITLE
Failed to send a request to the Edge Function

### ISSUE THREAD

**Issue by patrickinminneapolis** [supabase/supabase#16146]
Here is my edge function 

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

console.log("Hello from Functions!")

serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  }
  return new Response(JSON.stringify(data), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' }, // Be sure to add CORS headers here too
    status: 200,
  })
})

here I invoke it 

let res = await supabase.functions.invoke("hello3", {
         body: { name: 'patrick' },
       });

Access to fetch at 'https://xxxxxx.supabase.co/functions/v1/hello3' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Don't know what else to try.

**Comment by GaryAustin1** [comment]
CURL does not use CORS.  Browser clients do.
I don't see any handling of the OPTIONS call in your function.
https://supabase.com/docs/guides/functions/cors
Shows handling the CORS option call and also the regular request.

**Comment by patrickinminneapolis** [comment]
Thank you.

Yes, I needed this bit at the top 

```
 if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }
```
