### ISSUE TITLE
Wrong Order by Foreign table syntax

### ISSUE THREAD

**Issue by Kamahl19** [supabase/supabase#16172]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/reference/javascript/order)

## Describe the problem

Documentation says:
`.order('name', { foreignTable: 'cities' })`

## Describe the improvement

The correct syntax is:
`.order('cities(name)')`

**Comment by alaister** [comment]
Hi,

The documentation contains the correct syntax: https://supabase.com/docs/reference/javascript/order?example=on-a-referenced-table

For reference:
```ts
const { data, error } = await supabase
  .from('countries')
  .select(
    `
      name,
      cities (
        name
      )
    `
  )
  .order('name', { referencedTable: 'cities', ascending: false })
```
