### ISSUE TITLE
Magic Link - 400: No associated flow state found

### ISSUE THREAD

**Issue by cacosandon** [supabase/supabase#16181]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After sending an OTP code (or magic link) with `supabase.auth.signInWithOtp`, the link expires after 5 (?) minutes, ignoring the configuration (screenshot below). I see this error on Supabase logs: 

`"msg": "400: No associated flow state found. 400: Flow state is expired",`

<img width="400" alt="Screenshot 2023-08-02 at 20 20 05" src="https://github.com/supabase/supabase/assets/30879716/32504884-eb28-464e-88e2-62b2c62c7451">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a project with Email provider activated
2. Send a mail with `supabase.auth.signInWithOtp`
3. Wait 5 minutes

## Expected behavior

I expect to use the configuration and not expire before the configured duration.

## System information

- Version of supabase-js: 2.29.0

**Comment by cacosandon** [comment]
Seems related to https://github.com/orgs/supabase/discussions/3961

And so related to https://supabase.com/docs/guides/auth/auth-email-templates#limitations

**Comment by ameer-clara** [comment]
+10
Noticing this behavior with our app too with an even less time and at random - this is pretty huge - expecting users to sign up to our app in production and them resulting in not being able to register (when clicked on magic link), is a pretty big miss, hampering our efforts to onboard new users.

Manifests in the Authentication dashboard, under 'Last Sign In' column as Never. I couldn't find any documentation on the statuses for Last Sign In?

My understanding understanding of the statuses of Last Sign In:
- 'Waiting for Verification'  - magic link sent, but not clicked on
- '<date-time>' -  magic link clicked on successfully, and user logged in
- 'Never' - does this mean that the user clicked on the magic link but was not successfully able to login?

Please advise

@gregnr @madx @laktek @neiled

<img width="565" alt="Screen Shot 2023-08-06 at 1 35 13 PM" src="https://github.com/supabase/supabase/assets/60880191/f4ccf259-747b-42b6-b569-7ae1113a67ab">

**Comment by aviadmini** [comment]
I've noticed this happens on my local development setup (updated today). Should I ignore it?
