### ISSUE TITLE
Storage will not display buckets in Supabase UI, nor can a bucket be created

### ISSUE THREAD

**Issue by hichana** [supabase/supabase#16185]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This error occurs when I try to create a storage bucket in the Supabase UI:
`Failed to create bucket: Unexpected token < in JSON at position 0`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the 'Storage' page in the Supabase UI for a given project
2. Try to view or create storage buckets

## Expected behavior
Buckets should show up and buckets should be able to be created.

## Screenshots
![Screenshot 2023-08-03 at 3 47 49 PM](https://github.com/supabase/supabase/assets/8943047/cfe267a4-af6c-46ef-80a0-c8d6355daf46)

## System information

- OS: Chrome

**Comment by andy5090** [comment]
I have same issue.
OS: MacOS, Android
Browser: Chrome, Safari, Samsung Internet
