### ISSUE TITLE
on().subscribe() grammar fixes

### ISSUE THREAD

**Issue by ggarnhart** [supabase/supabase#1620]
# Improve documentation

## Describe the problem

[This paragraph](https://supabase.io/docs/reference/javascript/subscribe#listening-to-deletes) is missing the word "does."
Commas are also missing in a few sentences.

## Describe the improvement

"By default Supabase not send deleted records." should be "**By default,** Supabase does not send deleted records.

## Additional context

I'm happy to create a PR to fix these issues! Thanks for building an awesome product.

**Comment by w3b6x9** [comment]
@ggarnhart thanks for appreciating an awesome product! 

> By default, Supabase does not send deleted records.

Much better! Please create the PR and we'll get it merged.

**Comment by ggarnhart** [comment]
Awesome! I'll send over tomorrow.

**Comment by ggarnhart** [comment]
Resolved [here](https://github.com/supabase/supabase/pull/1630)! Happy to close this issue whenever, but would also be more than happy for anyone else to close it when they deem appropriate :)

**Comment by w3b6x9** [comment]
@ggarnhart merged #1630! Thanks again!
