### ISSUE TITLE
Linkedin Auth asks for my password every time even if I am logged in there already

### ISSUE THREAD

**Issue by sashchukalex** [supabase/supabase#16217]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have connected Linkedin Auth using Supabase. It asks for my password every time even if I am logged in to Linkedin already.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up LinkedIn Auth following [this guide](https://supabase.com/docs/guides/auth/social-login/auth-linkedin)
2. Go to Linkedin and make sure that your profile is authorized there
3. Open the `/login` page in the application
4. Click the `SignIn with Linkedin`
5. The consent screen is opened
6. Email field is prefilled with email
7. Password field is empty. It asks me each time to enter my password. but if I just navigate to LinkedIn (separately) I'm already logged in.

## Expected behavior
It would be nice to have the same behavior as Google has. If you're not logged in the first time, you log in to Linkedin auth as well without providing the password.

## Screenshots
<img width="1627" alt="image" src="https://github.com/supabase/supabase/assets/103134656/27cb5aa2-a966-4473-9ac7-e1ad157810a0">

## System information
- OS: [macOS]
- Browser: Chrome, safari
- @supabase/supabase-js": "^2.26.0",
- @supabase/auth-helpers-nextjs": "^0.7.2"

**Comment by gregnr** [comment]
Hey @sashchukalex, we'll just need to wait for a member of the auth team to take a look. Thanks for your patience!

**Comment by elmaester** [comment]
Bump, please fix this 🙃

**Comment by sashchukalex** [comment]
@gregnr hello 👋 do you have any updates on it?

**Comment by jbcallv** [comment]
@gregnr, I can look into this. Has this been taken already?

**Comment by jonnicholson94** [comment]
@gregnr - also happy to look into this, let me know if still needed!

**Comment by encima** [comment]
Hello @elmaester , @jbcallv , @jonnicholson94 , please do take a look at it and update with your findings.

It is my understanding that this is on the provider side but I could be wrong. Can you confirm this occurs with LinkedIn's OIDC method that will replace the original version?

Thanks!

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by schreon** [comment]
Still happening. The flow always asks for email/password, regardless if my browser is already signed in to LinkedIn.

**Comment by Nikita-Goncharov** [comment]
> Still happening. The flow always asks for email/password, regardless if my browser is already signed in to LinkedIn.

Hi, i have this issue now too. Did you find solution ? Or maybe someone else can help me ? 

On device which already logged in linkedin when i am using linkedin api to sign in it  always ask about email and password

**Comment by wit221** [comment]
Issue still present. Any workarounds?
