### ISSUE TITLE
Text center-aligned instead of left-aligned in dropdown menu

### ISSUE THREAD

**Issue by SeansC12** [supabase/supabase#16243]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The text in the dropdown menu is center-aligned instead of left-aligned

## To Reproduce

1. Go to a Supabase project
2. Go to the "Authentication" tab
3. Click on Users
4. Click on the 3 dots next to a user to trigger the dropdown

## Expected behavior

The text is left-aligned

## Screenshots

<img width="256" alt="image" src="https://github.com/supabase/supabase/assets/88256324/56ba382a-bd99-46b4-a317-0b4df1a78678">

<img width="265" alt="image" src="https://github.com/supabase/supabase/assets/88256324/9b832090-03c6-48ad-a78e-1b5fdff8b075">

## System information

- OS: [macOS]
- Brave Browser (if applies)

**Comment by finsoncoutinho** [comment]
Hey, I want to work on this issue. Can you please guide me on how to go about it?

**Comment by finsoncoutinho** [comment]
I followed the steps from the DEVELOPERS.md file, set up the repo, and ran it on my local system.

I ran it on port http://localhost:8082/

but when I navigate to authentication ie. http://localhost:8082/project/default/auth/users

I get Error: [500] An error has occurred: fetch failed

##Screenshots
<img width="718" alt="Screenshot 2023-08-05 at 4 05 42 PM" src="https://github.com/supabase/supabase/assets/69283994/b970c52d-54e2-4aea-92d5-8777d59530bc">

**Comment by hellofaizan** [comment]
Shouldn't this issue to closed
