### ISSUE TITLE
Docker self-hosted instance not working well with Studio

### ISSUE THREAD

**Issue by darmie** [supabase/supabase#16258]
# Bug report

While following the tutorial on [self-hosting with docker](https://supabase.com/docs/guides/self-hosting/docker), I had a problem with the Docker instance supabase/studio. I could not start it and it keeps restarting and exiting with the following error:

```
studio:dev: No storage option exists to persist the session, which may result in unexpected behavior when using auth.
studio:dev:         If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
```
`localhost:3000` and `localhost:8000` are not reachable with browser.  This may be affecting all the features of the studio

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After running running docker compose and `npm run dev:studio`, I tried to access `http://localhost:8082/project/default/auth/users` and `http://localhost:8082/project/default/editor`

The studio page keeps spinning

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow instructions at https://supabase.com/docs/guides/self-hosting/docker
2. Run `npm install` and `npm run dev:studio`

## Expected behavior

Should be able to view all the project specific pages like authentication, tables, database, storage etc..

## Screenshots

![Screenshot 2023-08-06 at 15 40 42](https://github.com/supabase/supabase/assets/848002/6bf037c8-c4b5-45ed-9394-bdbe261eccfa)

![Screenshot 2023-08-06 at 15 52 49](https://github.com/supabase/supabase/assets/848002/94b86d4c-adab-4a48-bb4b-dd6c1eaa2219)

## System information

- OS: macOS
- Browser: Chome
- Version of supabase-js: ^2.23.0
- Version of Node.js: n/a

**Comment by darmie** [comment]
`http://localhost:3000/` keeps loading forever, though all docker services are running

**Comment by saputradharma** [comment]
Hi @darmie, I think your issue is fixed in this [PR](https://github.com/supabase/supabase/pull/16097).

The steps in the [self-hosting documentation](https://supabase.com/docs/guides/self-hosting/docker) are also updated.
