### ISSUE TITLE
Update README images

### ISSUE THREAD

**Issue by tomoyukiy** [supabase/supabase#16294]
# Chore
Update two images.

- [i18n/README.ar.md](https://github.com/supabase/supabase/blob/master/i18n/README.ar.md)
- [i18n/README.bn.md](https://github.com/supabase/supabase/blob/master/i18n/README.bn.md)
- [i18n/README.ca.md](https://github.com/supabase/supabase/blob/master/i18n/README.ca.md)
- [i18n/README.fa.md](https://github.com/supabase/supabase/blob/master/i18n/README.fa.md)
- [i18n/README.gr.md](https://github.com/supabase/supabase/blob/master/i18n/README.gr.md)
- [i18n/README.gu.md](https://github.com/supabase/supabase/blob/master/i18n/README.gu.md)
- [i18n/README.he.md](https://github.com/supabase/supabase/blob/master/i18n/README.he.md)
- [i18n/README.hi.md](https://github.com/supabase/supabase/blob/master/i18n/README.hi.md)
- [i18n/README.jp.md](https://github.com/supabase/supabase/blob/master/i18n/README.jp.md)
- [i18n/README.ms.md](https://github.com/supabase/supabase/blob/master/i18n/README.ms.md)
- [i18n/README.nb-no.md](https://github.com/supabase/supabase/blob/master/i18n/README.nb-no.md)
- [i18n/README.ne.md](https://github.com/supabase/supabase/blob/master/i18n/README.ne.md)
- [i18n/README.pt.md](https://github.com/supabase/supabase/blob/master/i18n/README.pt.md)
- [i18n/README.si.md](https://github.com/supabase/supabase/blob/master/i18n/README.si.md)
- [i18n/README.sq.md](https://github.com/supabase/supabase/blob/master/i18n/README.sq.md)
- [i18n/README.sr.md](https://github.com/supabase/supabase/blob/master/i18n/README.sr.md)
- [i18n/README.ta.md](https://github.com/supabase/supabase/blob/master/i18n/README.ta.md)
- [i18n/README.th.md](https://github.com/supabase/supabase/blob/master/i18n/README.th.md)
- [i18n/README.vi-vn.md](https://github.com/supabase/supabase/blob/master/i18n/README.vi-vn.md)
- [i18n/README.zh-cn.md](https://github.com/supabase/supabase/blob/master/i18n/README.zh-cn.md)

### Top image
Before
<img width="1018" alt="supabase_readme_top_2" src="https://github.com/supabase/supabase/assets/38880175/8f2236f5-ba01-41ac-943b-d8ec6ebe47b6">

After
<img width="896" alt="supabase_readme_top_1" src="https://github.com/supabase/supabase/assets/38880175/abb9fd2f-a7fc-4fe1-bb5c-3486f2bdcdd5">

### Architecture
Before
<img width="1013" alt="supabase_readme_architecture_2" src="https://github.com/supabase/supabase/assets/38880175/f3e988c6-c285-45f2-a067-1a4a84c5b090">

After
<img width="805" alt="supabase_readme_architecture_1" src="https://github.com/supabase/supabase/assets/38880175/229633bf-7a4f-4f59-83ed-b68ebf9966fc">

**Comment by avi1737** [comment]
can I take this up ?

**Comment by tomoyukiy** [comment]
Thanks for confirming this issue.
Sorry, it was addressed in pull request #16296.

**Comment by CBID2** [comment]
Hi @tomoyukiy! I’m @CBID2. A colleague of mine mentioned that this repo is a great way to learn about customer support and other skills for a skill in IT HelpDesk, so here I am! :) Anyway, I would like to help in adding some of the images in this issue as a way to get started.

**Comment by tomoyukiy** [comment]
Hi @CBID2!.
Thanks for confirming this issue.
But, this issue was addressed in pull request #16296.

**Comment by tomoyukiy** [comment]
The PR for the change has not been merged, but once this issue is closed.

**Comment by tomoyukiy** [comment]
The PR for the change has not been merged, but once this issue is closed.
