### ISSUE TITLE
Request to change unauthenticated dashboard root to be the login screen

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#163]
# Question

I found it a bit odd to have a 'homepage' on the root of the dashboard when the user is logged out. Currently, when you click login on https://supabase.io/ it goes here:
![Screen Shot 2020-08-31 at 9 49 42 AM](https://user-images.githubusercontent.com/6392501/91727324-8a281000-eb6f-11ea-963b-59feeb5bc526.png)

Issues with this:
 - Requires managing two static homepages (app.supabase.io and supabase.io)
 - Requires user to click login twice in order to get to the login screen

## Proposed solution
Change the root of the unauthenticated dashboard to be the login screen (or auto-redirect to the login screen)

**Comment by kiwicopple** [comment]
Seems sensible, less to maintain. 

I'll rethink this one

**Comment by kiwicopple** [comment]
Adding this one to Hacktoberfest - we're welcoming any design suggestions for our "log in" page on app.supabase.io 🎨

**Comment by kiwicopple** [comment]
We trimmed down the screen now so that it only has some very basic info :)
