### ISSUE TITLE
Carousal on community tab cuts off text/posts on first and last item. Bug or functioning as intended?

### ISSUE THREAD

**Issue by HoldUpFjord** [supabase/supabase#16309]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Carousal on community tab of home webpage cuts off text/posts on first and last item. Happens on larger screens, does not happen on mobile or tablet devices. Not sure if this is a small bug or intended functionality. Happy to take it on if it turns out to be a bug :)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to (https://supabase.com/)
2. Scroll down to Community tab with carousal 
3. See carousal overflowing. z
4.) Open inspect tools and switch to mobile or tablet devices.
5.) See carousal items not overflowing. 

## Expected behavior

Mobile and desktop views having the same layout, either overflowing the first and last item or not. 

## Screenshots
Desktop view: 
![supabasePotentialUIBug](https://github.com/supabase/supabase/assets/93451889/5d42297c-221e-4260-9e78-8c1850be02dd)

Mobile view: 
![supabasePotentialUIBugMobile](https://github.com/supabase/supabase/assets/93451889/fa015ce7-7445-43da-8b16-f6d48a3ae14f)

## System information
- OS: [ Windows]
- Browser (if applies) [firefox]

**Comment by HoldUpFjord** [comment]
To the reviewer, thank you for your time! If this turns out to be a valid bug I'd be happy to work on it :)

**Comment by fsansalvadore** [comment]
@HoldUpFjord thanks for pointing this out! It's not "intentional" but also not a big issue since it's a scrollable carousel.

If you want to suggest an improvement, go for it! 👍

**Comment by HoldUpFjord** [comment]
Yeah of course! I figured it would be a good first issue since I'm new around here :) 

I was thinking something like this:
result was achieved by setting the total width of the container to 80% of the viewport on desktop screens. It stops the overflow of the next item in the carousal. 
https://github.com/supabase/supabase/assets/93451889/ddce6dab-0569-44e2-a027-ffc0bb602035
The other option that springs to mind is adjusting the width of all the item cards. How do those options

**Comment by khaled4dev** [comment]
@HoldUpFjord, I checked this issue it's only not showing correctly in the 1300px viewport, after that, it's working properly.
![image](https://github.com/supabase/supabase/assets/30053753/f0b82866-3776-4753-87ad-19b5d1f5f4e8)

**Comment by fsansalvadore** [comment]
@HoldUpFjord how about a max-width of 100vw to the carousel?
This should keep the current layout and also fix the described bug.

**Comment by HoldUpFjord** [comment]
@fsansalvadore I like that solution a lot. Cool if I go ahead and make the change / open a PR?

**Comment by fsansalvadore** [comment]
Thanks for the effort @HoldUpFjord, but we'll most likely go with [this implementation](https://github.com/supabase/supabase/pull/16729) which also solves this issue.

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
