### ISSUE TITLE
SQL Editor freezes on "loading..."

### ISSUE THREAD

**Issue by alieldeba** [supabase/supabase#16306]
when I open any SQL editor file it freezes at loading I waited for it so much and tried to use another browser and also tried to use VPN and the issue remains how to deal with that?

![image](https://github.com/supabase/supabase/assets/88302640/b0376596-66ad-44f4-abf9-fef6efc3d443)

**Comment by alieldeba** [comment]
@kiwicopple

**Comment by destrex271** [comment]
I'll be happy to solve this issue.

**Comment by alieldeba** [comment]
btw i have this error in my console: Monaco initialization: error

![image](https://github.com/supabase/supabase/assets/88302640/e2de4f2c-6458-4ea1-a256-bf314a326e34)

**Comment by saltcod** [comment]
Hey @alieldeba — are you running a query there and it stalls or this is a first load? 
Mind deleting all your local storage items there and trying again?

**Comment by alieldeba** [comment]
Hey @saltcod I have deleted all my local storage items and it remains the same I called a friend to try to make a new query for his project and he faces the same issue please any help 🥹.

**Comment by alieldeba** [comment]
Yup i tried and it is the same :(

**Comment by saltcod** [comment]
Quite strange! Same in all your projects? In all browsers? Any console errors there you can share?

**Comment by alieldeba** [comment]
Yes I tried to make new projects and it is the same and this is all my console errors:

![image](https://github.com/supabase/supabase/assets/88302640/338b2879-bee2-45e0-9268-2a0739d2dbe4)
![image](https://github.com/supabase/supabase/assets/88302640/31beff17-ab25-4a68-bb03-143442809119)

@saltcod

**Comment by alieldeba** [comment]
It might be that you are initializing the Monaco editor and you did not handle the errors and showing loading... even if there is an error.

**Comment by alieldeba** [comment]
btw the same issue when I try creating a policy in the storage

![image](https://github.com/supabase/supabase/assets/88302640/489ffe4c-eb20-4069-aed4-77098a5bbc65)

**Comment by alieldeba** [comment]
Chrom is the same 

![image](https://github.com/supabase/supabase/assets/88302640/025b28de-5d17-40de-a8b6-1bbd5721ba3b)
![image](https://github.com/supabase/supabase/assets/88302640/cc1e0160-7287-4612-b383-8fafbb4e1748)

**Comment by saltcod** [comment]
@alieldeba it looks like your system might be blocking resources from jsdelivr. 
Are you able to access anything else from there? 
Any special firewall settings setup on your system that you know of?

**Comment by alieldeba** [comment]
oh, you are using jsdeliver now I know what is the problem :)

jsdeliver is blocked in Egypt and do not ask me why 😢 
I will try enabling vpn hoping that works

**Comment by alieldeba** [comment]
Hey, @saltcod @kiwicopple after searching a lot some VPNs do not work, and also some VPNs were blocked by Egypt, so I read articles about Egypt blocking cdn.jsdeliver.net and found a solution that you can replace "cdn.jsdeliver.net" with "https://fastly.jsdelivr.net/". and it will work in Egypt

Hopefully, someone do that as quickly as possible because I want to use supabase storage for my projects and I cannot right now ☹️

**Comment by alieldeba** [comment]
The loading state has finally gone and the editor worked after installing Cloudflare from here: https://1.1.1.1/

**Comment by ahmeds189** [comment]
@alieldeba thx bro i was facing the same problem and this is the only vpn that worked

**Comment by silvanet** [comment]
I don't see any resolution. I'm having the same problem in May 30, 2025, and I'm in the U.S.
