### ISSUE TITLE
ERROR: cannot drop view public.[view-name] because other objects depend on it (SQLSTATE 2BP01)

### ISSUE THREAD

**Issue by hichana** [supabase/supabase#16353]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I have replaced the table name in the below error text with "[view-name]".

`ERROR: cannot drop view public.[view-name] because other objects depend on it (SQLSTATE 2BP01)`

This error happens when I try to use the cli command ['supabase link'](https://supabase.com/docs/reference/cli/supabase-link). Without being able to run the link command successfully I cannot use the CLI fully and I cannot work locally using the cli features. I have a view that shows the decrypted data from a table in the database. The data was encrypted using the Supabase (TCE Process)[https://supabase.com/blog/transparent-column-encryption-with-postgres].

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go through the steps to enable TCE on a table
2. Follow the steps to link a supabase project

## Expected behavior

The CLI should properly link.

- OS: macOS
- Version of supabase-cli: Beta version 1.83.7

Edit:
Also happens on non-beta CLI version 1.82.6

**Comment by laubonghaudoi** [comment]
I have this issue too

**Comment by gerzarko** [comment]
Did anyone find a work around this issue?

**Comment by sweatybridge** [comment]
I find this strange because `supabase link` doesn't drop views. Could you share more detailed logs with `--debug` flag?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by m-sadegh-sh** [comment]
I have the same issue with supabase db reset --linked

**Comment by pbsullOptima** [comment]
I am having this issue with `supabase db reset --linked`

It looks like its because I have a View that references the storage schema.

**Comment by yuannan** [comment]
As a work around I've just delete the supabase dir in my local project, then just linked and pull the db schema again. It's a bit of a hack, but it works if as long as you won't miss the data.
