### ISSUE TITLE
Error init with docker - Solved

### ISSUE THREAD

**Issue by sailarg** [supabase/supabase#16356]
An error is occurring when launching docker images, when I run docker-compose up I have these problems

WARNING: The MFA_ENABLED variable is not set. Defaulting to a blank string.
supabase-imgproxy is up-to-date
supabase-vector is up-to-date
supabase-db is up-to-date
supabase-analytics is up-to-date

ERROR: for kong  Container "de8f18e873f7" is unhealthy.

ERROR: for meta  Container "de8f18e873f7" is unhealthy.

ERROR: for studio  Container "de8f18e873f7" is unhealthy.

ERROR: for functions  Container "de8f18e873f7" is unhealthy.

ERROR: for rest  Container "de8f18e873f7" is unhealthy.

ERROR: for auth  Container "de8f18e873f7" is unhealthy.

SO info: ubuntu 22.04
Docker version 23.0.6, build ef23cbc

Solved

**Comment by itseliev** [comment]
Hello! I faced with this error too.

**Comment by sailarg** [comment]
> Hello! I faced with this error too.

Just clone from here git clone --depth 1 https://github.com/supabase/supabase

 Go to the docker folder copy  the .env.example to .env and then execute docker compose pull

**Comment by gregnr** [comment]
Closing this as it appears to be solved!
