### ISSUE TITLE
Issue with creating a new Migration

### ISSUE THREAD

**Issue by marcfrankel** [supabase/supabase#16388]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

For whatever reason using the Supabase CLI I cannot create a new migration.

When I run the command I get this cryptic error: unknown shorthand flag: 'b' in -b

I have tried using the --debug flag and no new output is produced. Seems to happens no matter the name of the new migration

## To Reproduce

running the command 
```
supabase migration new test_migration
```

## Expected behavior

Creates a new migration

## System information

- OS: [e.g. macOS, Windows] MacOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Supabase cli: 1.83.7
- Version of Node.js: [e.g. 10.10.0] 16.20.1

## Additional context

I acknowledge this is probably a mistake on my part since I am rather new to supabase, but given the cryptic error, the fact that I couldn't find any help by googling it, and the recent changes to local database stuff I figured it was

**Comment by encima** [comment]
hey @marcfrankel, thanks for reporting!
Is this still an issue for you? Are you using `zsh` or another shell?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
