### ISSUE TITLE
Subscribing to materialized views (like Hasura, RethinkDB and Firebase Realtime DB)

### ISSUE THREAD

**Issue by baderdean** [supabase/supabase#16386]
Wrappers are now available, which is great, but realtime on our own data when it's a view is still not possible. In real life, data streamed to the front end is often the result of a "join" somehow. A view/materialized view is the most obvious choice here for performance and design.

I understand that the current realtime implement doesn't enable to do so, but we could have an alternative for materialized views/views, based on a listen/notify or trigger mechanism. It's not perfect but better than nothing! Without realtime on materialized views, we need to do a listen/notify mechanism to update a real table OR to join data in the front end which is even worst.

### Discussed in https://github.com/orgs/supabase/discussions/3824

<div type='discussions-op-text'>

<sup>Originally posted by **jamieflorence** November  7, 2021</sup>
Howdy. I’ve been searching for a plausible Firebase alternative for a while now, and am delighted to have stumbled across this.

Before I get too excited, I have one quick question: is there any way to subscribe to a materialized view, rather than a table?

For context, I currently receive real time data which I put through a long computational pipeline to produce a summary table. The data comes in large packets at irregular intervals. I only care about the summary output in real time, not the individual data inputs, so I just want to be able to subscribe over websockets so I can build a dashboard.

Is this, or something like this, possible with supabase?

Hasura is able to, but their model uses live queries, and the computational model I have is far too intensive for that; I want to be able to trigger the refresh rate as data comes in.</div>

**Comment by encima** [comment]
Hi @baderdean 

As you noted, realtime is not available with wrappers as they query the data source on-demand. One option you have is to use the `pg_cron` extension to refresh the materialized view every X interval, see [here](https://supabase.com/docs/guides/database/extensions/wrappers/overview#batch-etl-with-wrappers).
The job could also send a notification/alert etc when triggered.
