### ISSUE TITLE
On data request when using both .order and .range, no matter the offset+limit combination i get the same element as last element

### ISSUE THREAD

**Issue by LavaGolem** [supabase/supabase#16409]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I have a regular table in superbase that I'm query-ing. Here is a example of a call: 

```
const request = supabase.from('elements').select('*')
    const { data, error } = await request
      .order('element_start_date', { nullsFirst: false })
      .range(start_index, end_index)
```

The issue I have is no matter which start_index and end_index I set I get the same element as a lest element returned form a request. 

I also tried CURL instead of a Supabase syntax, where I would manually set offset and limit. And any combination of ∫ and **limit**
that I set, I get the same element in the return. Some of the combinations: 0-30, 30-30, 60-30, 100-30.

Additionally, some conclusions I've had: 
1. In the database and this specific element is the first element in the table. 
2. When I remove **.order()** everything is working as expected
3. When I remove **.range()** this element is the first one returned

## To Reproduce
- I can't reproduce it on every data set 

## Expected behavior
- i would expect not to get this element except when I query offset:0, limit:30

## System information

- OS: macOs, supabase is running in docker
- Browser Chrome
- Version of supabase-js: 1.82.2

**Comment by GaryAustin1** [comment]
Is element_start_date unique?  .order need a unique column.  If there are any duplicates then you are not guaranteed any order at all for the duplicates and likely will get repeats as you step thru range as it can change on each request.
