### ISSUE TITLE
onAuthStateChange

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#1640]
# Bug report

## Describe the bug

`supabase.auth.onAuthStateChange` is not triggered when the auth event occurs in another tab.

For instance, let's say I have two tabs of my app open. A user signs out on tab 2. I'd expect the function to be triggered on tab 1. Then I could redirect the user on both tabs to the sign-in page. However, the function doesn't fire, so the user is not signed out on both tabs.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the bare minimum app for a user to sign in
2. Add this code to the page
```ts
supabase.auth.onAuthStateChange((event, session) => {
    console.log('changed!')
})
```
3. Open up the dev consoles for both tabs
4. Sign out on one tab
5. `changed!` will be logged to the tab you signed out on, but not the other

## Expected behavior

The function runs on both tabs.

## System information

- OS: macOS 11.3.0
- Browser: Brave Version 1.24.85 running Chromium: 90.0.4430.212
- Version of supabase-js: 1.11.14
- Version of Node.js: 16.1.0

## Additional context

in the meantime, I'm just going to listen to localStorage changes to get the updates across all tabs.

```ts
window.addEventListener('storage', () => {
    const token = localStorage.getItem('supabase.auth.token')
    // do what I want with the token
})
```

**Comment by awalias** [comment]
thanks for the report @Nick-Mazuk we'll take a look asap

**Comment by kiwicopple** [comment]
Thanks for this @Nick-Mazuk - closing in favor of the earlier issue!

https://github.com/supabase/gotrue-js/issues/79
