### ISSUE TITLE
Supabase Vercel template demo is broken 

### ISSUE THREAD

**Issue by 0xc00010ff** [supabase/supabase#16400]
Just an FYI, the [Supabase template on Vercel](https://vercel.com/templates/next.js/supabase) demo is broken. 

https://demo-nextjs-with-supabase.vercel.app/

<img width="1129" alt="Screen Shot 2023-08-09 at 11 03 04 PM" src="https://github.com/supabase/supabase/assets/4950729/012b88cb-9a22-4825-a5f7-29d8898adf6b">

**Comment by gregnr** [comment]
@0xc00010ff thanks for the heads up! cc @dijonmusters

**Comment by saltcod** [comment]
https://demo-nextjs-with-supabase.vercel.app/

Appears fixed. Marking this as closed. Thanks for the report!
