### ISSUE TITLE
Wrapper Documentation in Studio Links to 404'd Page

### ISSUE THREAD

**Issue by michaelcooke** [supabase/supabase#16425]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Documentation link in "Database > Wrappers" in supabase.com Studio instance links to [dead link](https://supabase.com/docs/guides/database/extensions/wrappers)

## To Reproduce

1. Visit https://supabase.com/dashboard/project/<project id>/database/wrappers
2. Click "Documentation"

## Expected behavior

"Documentation" button links to [Wrappers overview](https://supabase.com/docs/guides/database/extensions/wrappers/overview) or other relevant documentation.

**Comment by gregnr** [comment]
Fixed in https://github.com/supabase/supabase/pull/16448
