### ISSUE TITLE
Wrong documentation link for Google auth provider

### ISSUE THREAD

**Issue by Rahilsiddique** [supabase/supabase#16437]
# Improve documentation
In Supabase -> Dashboard -> authentication -> Google provider -> callback URL (OAuth) 
The text below the input links to https://supabase.com/docs/guides/auth/social-login/auth-apple#configure-your-services-id
which should be rather https://supabase.com/docs/guides/auth/social-login/auth-google#configure-your-services-id

## Link 
this url needes to be updated to link `auth-google` instead of `auth-apple`
https://github.com/supabase/supabase/blob/4bd7f5bb49406110be4546d6dbe7588a3abbe3c0/studio/stores/authConfig/schema/AuthProviders/AuthProvidersFormValidation.tsx#L884

**Comment by gregnr** [comment]
Good catch @Rahilsiddique. Would love to see a PR to fix this!

**Comment by Abhishek-90** [comment]
Can I fix it?

**Comment by kiranvarma01** [comment]
Is this issue still open..?

**Comment by aum99** [comment]
I've fixed the issue please check @gregnr

**Comment by rakeshpedavalli4** [comment]
Hi,
I want to work on this project, please let me know if it is still open, if so Please asign it to me

**Comment by KSSaiTeja** [comment]
could you please assgn this to me?

**Comment by AbhijeetBiswalCodes** [comment]
#16581

**Comment by alaister** [comment]
Fixed in #16437
