### ISSUE TITLE
auth.uid() is not working or not getting requested user.

### ISSUE THREAD

**Issue by MickyLaitkor** [supabase/supabase#16441]
# Bug report

I am creating a policy for my products table that allows reading/access only for users who are members of the product. The policy ensures that a user can read/access the products only if their user ID is present in the product_members table.

```

create policy "Read Products only for members" on products for
select
  using (
    exists (
      select
        1
      from
        product_members
      where
        user_id = auth.uid ()
    )
  );

```
However, I am facing an issue where the auth.uid() function is not returning the user ID of the current user, preventing me from fetching the products.

when I check on frontend, the requested user also authenticated. 

![Screenshot 2023-08-11 165331](https://github.com/supabase/supabase/assets/132438556/f4d57e9a-3096-4624-8caa-69a8aa58156e)
 
working on  
Nextjs 13.4
"@supabase/supabase-js": "^2.32.0",
"@supabase/auth-helpers-nextjs": "^0.7.4",

**Comment by GaryAustin1** [comment]
No known issues with auth.uid() and jwt's as that would bring almost everyone down.
https://github.com/orgs/supabase/discussions/12895 has a few tips on debugging this.
It seems that you don't actually have a session in the supabase client when you make the call.  auth-helpers has lots of moving parts and it is not uncommon to have code missing/wrong that causes this.

You would be better off using the Supabase Discord and showing some of your client code for users to help, than reporting a bug at this point.  IMO.
