### ISSUE TITLE
When pressing the up or down arrow keys while entering input in Supabase AI, the input element gets cleared

### ISSUE THREAD

**Issue by hawkcookie** [supabase/supabase#16471]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When pressing the up or down arrow keys while entering input in Supabase AI, the input element gets cleared.
Especially, when word prediction appears, I use the cursor keys, which causes the text being entered to get cleared.

https://github.com/supabase/supabase/assets/29660904/74c8dc9b-c7f2-4d98-bef0-e9841b645817

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Click on 'command K'
2. Click on 'ask supabase ai'
3. entering some chars in input form 
4. press down the up or down arrow keys

## Expected behavior

the input element is not cleared.

## System information

- OS: macOS
- Browser (if applies) chrome

**Comment by faizanraso** [comment]
I've submitted a PR to resolve this issue - https://github.com/supabase/supabase/pull/16482

**Comment by hawkcookie** [comment]
> I've submitted a PR to resolve this issue - #16482

thanks!
