### ISSUE TITLE
docker-compose not builded on ubuntu 22.04

### ISSUE THREAD

**Issue by xsa-dev** [supabase/supabase#16504]
# Bug report

- [+] I confirm this is a bug with Supabase, not with my own application. 
- [-] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'supabase/docker' on ubuntu 22.04
2. Type 'docker-compose up'
3. See error
```
(venv) ➜  docker git:(docker-not-build) docker-compose pull
WARNING: The MFA_ENABLED variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.analytics.environment.LOGFLARE_SINGLE_TENANT contains true, which is an invalid type, it should be a string, number, or a null
services.studio.environment.NEXT_PUBLIC_ENABLE_LOGS contains true, which is an invalid type, it should be a string, number, or a null
```

## Expected behavior

Command execute without exceptions

## Screenshots
![image](https://github.com/supabase/supabase/assets/16959353/7011b810-e49f-4a7f-8077-5faffec0c428)

## System information

- OS: [Ubuntu 22.04]
- Commit to reproduce: [297584a0dd175c41bb0cd17175b51600dc468e00]

## Additional context

Fixed with replace bolean values to integer (1).

**Comment by Lightning-Dev** [comment]
I also experienced this error and actually fixed it by replacing the LOGFLARE_SINGLE_TENANT and NEXT_PUBLIC_ENABLE_LOGS
with a value of 1. However, even though this fixed the error there were other follow-on installation errors that I could not resolve on my Ubuntu 22.04 server.

**Comment by Hybiekay** [comment]
am also having the same issues what did you do to fix it

**Comment by xsa-dev** [comment]
> Fixed with replace bolean values to integer (1).

Fixed with replace boolean values to integer (1).
```
LOGFLARE_SINGLE_TENANT=1
NEXT_PUBLIC_ENABLE_LOGS=1
```
etc..

**Comment by Hybiekay** [comment]
Where will i find to change it LOGFLARE_SINGLE_TENANT=1
NEXT_PUBLIC_ENABLE_LOGS=1

**Comment by fabiobeoni** [comment]
Same here... 

By replacing few vars with "true" to 1, as  suggest above...

```
      LOGFLARE_SINGLE_TENANT: 1
      LOGFLARE_SUPABASE_MODE: 1
      LOGFLARE_MIN_CLUSTER_SIZE: 1
```

the start process continue but only 4 services are live:

![Screenshot from 2023-08-19 14-19-42](https://github.com/supabase/supabase/assets/16882089/14371ae1-5b67-4560-b06c-b0459311f21a)

Console output:

```
[+] Running 3/4
 ⠿ Container supabase-vector     Healthy                                                                                                                           0.5s
 ⠿ Container supabase-db         Healthy                                                                                                                           1.5s
 ⠿ Container supabase-imgproxy   Running                                                                                                                           0.0s
 ⠿ Container supabase-analytics  Waiting                                                                                                                           0.5s
**container for service "analytics" is unhealthy**  <<----- :(:(

```
Note: I first replaced "true" to 1 only for the env vars listed above in the post, then I did it for every "true" value in the docker-compose file. No results.

Thanks.

**Comment by rammsesgit** [comment]
Hello everyone.

I had all the problems listed in this issue using the unofficial packages `docker.io` (version 20.X.X) and `docker-compose` in my ubuntu 22.04. But by installing docker engine and having version 23.X.X I was able to run the project without problems.

https://docs.docker.com/engine/install/ubuntu/

**Comment by yoavmlotok** [comment]
I have also encountered this error when using docker and docker-compose.
Both in a clean Fedora 38 server install and clean Ubuntu 23.04 server install.

To make docker work I had to install docker engine, following [this](https://docs.docker.com/engine/install/ubuntu/) guide.

After making sure docker works I encountered another problem relating to #16777 .
running `sudo docker compose restart` fixed the problem.

**Comment by xsa-dev** [comment]
@Lan-Hekary 
`docker -v`
Docker version 24.0.5, build ced0996
`docker-compose -v`
docker-compose version 1.29.2, build unknown

Yes, apparently this is due to the fact that I used the version with docker.io, and not the latest version of **_docker compose._**

Thank you!
