### ISSUE TITLE
Generation new secret api tokens and old images links

### ISSUE THREAD

**Issue by smartfox87** [supabase/supabase#16529]
I generated new secret api tokens and my old images urls stoped to work, because they include old public token. I tried to replace old token in image url on new public token, but it didn't help, bcause I got an error:
`  "statusCode": "400",
  "error": "InvalidSignature",
  "message": "The url do not match the signature"`

**Comment by Hallidayo** [comment]
Hi @smartfox87 - I'm just checking in here as its been a wild. Did you resolve this issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
