### ISSUE TITLE
Add info that flutter app needs android config to access internet

### ISSUE THREAD

**Issue by coolusaHD** [supabase/supabase#16548]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/quickstarts/flutter

## Describe the problem

It took me a while to find out out that the only thing that was missing was a line in the AndroidManifest that my app can access the internet, because it worked locally and after i published it on the internal track of google play it doesn't worked.

## Describe the improvement

Add a section for using in Prod environment or a small hint on the getting started page

**Comment by kiranvarma01** [comment]
is this issue still open

**Comment by gregnr** [comment]
Good suggestion @coolusaHD. Would love to see a PR adding this note to a "Going to Production" section at the bottom of that page.

**Comment by krmayur** [comment]
please assign this to me @coolusaHD

**Comment by gregnr** [comment]
Closed via #16672
