### ISSUE TITLE
Example/VueJS verification email domain is wrong

### ISSUE THREAD

**Issue by yusufpapurcu** [supabase/supabase#1661]
# Bug report

## Describe the bug

When I tried run this example is worked without problem but user signin email verification link is broken.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run Vue js example
2. Sign in
3. Check your mailbox for verification email
4. Click verification email's link

## Expected behavior

I think vue example must send verification message with true domain name.

## Screenshots

![image](https://user-images.githubusercontent.com/41443083/119132788-cd027e80-ba43-11eb-823a-6c6a833cfb86.png)
![image](https://user-images.githubusercontent.com/41443083/119132810-d4298c80-ba43-11eb-8a97-cc7911c7f669.png)
The problem is this link locates you to localhost. (I know this token not exist. If I wrote my vercel domain instead of local host it works without problem)
## System information

- OS: Windows 10
- Browser (if applies) Chrome
- Version of supabase-js: Same as example/vuejs

**Comment by kiwicopple** [comment]
@yusufpapurcu - could you please confirm what the Auth settings show in your Project (under Auth > Settings)?

**Comment by yusufpapurcu** [comment]
Oh I understand now. I don't know this setting. So there is no bug 😄
