### ISSUE TITLE
[fect] improve navbar active link  

### ISSUE THREAD

**Issue by mohitmk007** [supabase/supabase#16615]
# Improve documentation

## Describe the problem

after click on navbar (product and developers) they didn't active 

## Describe the improvement

we should active the link after click on it (Product and Developers)

**Comment by Masood-ul-Rehman** [comment]
@mohitmk007 can you please explain further on which page you are facing this issue that link is not active after clicking

**Comment by thevgseven** [comment]
It's Working Properly @mohitmk007

**Comment by amintai** [comment]
Hi @thevgseven please refer to the attached video for better understanding. 

https://github.com/supabase/supabase/assets/50178043/d1c31067-c026-498b-b919-1ca13df2e7d7

**Comment by amintai** [comment]
Hi @mohitmk007 Could you please assign this issue to me, so that i can start working on this and we can close this issue ASAP.
