### ISSUE TITLE
Supabase Docs consume more time to get loaded and Supabase AI also.

### ISSUE THREAD

**Issue by vgsvn** [supabase/supabase#16622]
I have been traveling through docs since last one week but almost every time I tried to navigate through one section to another docs takes a lot time and eventually browsers suggest me to close a tab. This happens Also with Supabase AI..

The Docs section needs to be improved, How we should convert our Supabase Docs into design like Vercel and Next.js Docs ??

**Comment by gregnr** [comment]
Thanks for reporting @thevgseven. This is the first I've heard of the docs behaving like this. Can you provide a way to reproduce this (steps, browser, OS, any other helpful information).
