### ISSUE TITLE
Failed to run sql query: query returned no rows

### ISSUE THREAD

**Issue by sumatoken** [supabase/supabase#16634]
### Discussed in https://github.com/orgs/supabase/discussions/16633

<div type='discussions-op-text'>

<sup>Originally posted by **sumatoken** August 20, 2023</sup>
I have a project on Supabase and I've wanted to implement TCE to encrypt a certain column.

I am running into errors when trying to insert into my table which has an encrypted column.

Here is my table definition:
```sql
create table
  public.user_databases_tce (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    database_string text null,
    user_id text null default requesting_user_id (),
    uuid uuid not null,
    show_sample boolean null default false,
    constraint user_databases_pkey_tce primary key (id, uuid),
    constraint user_databases_uuid_key_tce unique (uuid),
    constraint user_databases_uuid_fkey foreign key (uuid) references user_schemas (uuid) on delete cascade
  ) tablespace pg_default;

create trigger user_databases_tce_encrypt_secret_trigger_database_string before insert
or
update of database_string on user_databases_tce for each row
execute function user_databases_tce_encrypt_secret_database_string ();
```
And here is how I activated column encryption for the *database_string* column:

```sql
SECURITY LABEL FOR pgsodium
	ON COLUMN user_databases.database_string
  	IS 'ENCRYPT WITH KEY COLUMN uuid';
```

FYI, the **user_databases_tce_encrypt_secret_trigger_database_string** function is defined automatically after I run the security label query:

```sql
CREATE OR REPLACE FUNCTION 
public.user_databases_tce_encrypt_secret_database_string()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
        BEGIN
                new.database_string = CASE WHEN new.database_string IS NULL THEN NULL ELSE
            CASE WHEN new.uuid IS NULL THEN NULL ELSE pg_catalog.encode(
              pgsodium.crypto_aead_det_encrypt(
                pg_catalog.convert_to(new.database_string, 'utf8'),
                pg_catalog.convert_to(('')::text, 'utf8'),
                new.uuid::uuid,
                NULL
              ),
                'base64') END END;
        RETURN new;
        END;
        $function$
```

Now, when I try to insert in the table using the JavaScript Supabase client or even the Supabase dashboard GUI, I get this error:
```json
{
    "error": {
        "code": "P0002",
        "details": null,
        "hint": null,
        "message": "query returned no rows"
    }
}
```

I don't know if I'm doing something wrong or if I need to configure some type of policy.

I'd appreciate your guys' help.</div>

**Comment by saltcod** [comment]
Prob one for @GaryAustin1

**Comment by GaryAustin1** [comment]
This appears to be an error in the SQL code for the insert based the error message.  As there is a discussion open on this, commented there and closing this for now.
If it turns out to be a bug it can be reopened.
