### ISSUE TITLE
Bug: Not able to add data from supabase table UI when having referense with multiple keys from another same table

### ISSUE THREAD

**Issue by rahul3v** [supabase/supabase#16638]
# Bug report

As an example :

## Screenshots
![image](https://github.com/supabase/supabase/assets/24385409/30175ead-d779-4b9f-88d4-0802a7e78b0f)

the project is referenced from "workspaces" table's `id` and `userId` columns to a table "projects", but in here detecting only one `id`

## Expected
reference should be showing 
`userId` as `public.workspaces.userId` and
 `workspaceId` as `public.workspaces.id`

and selecting the referenced data from `workspaces` table will fill the expected inputs and can able to add the data

**Also :** in this case the **schema visualizer** is showing only one column link to another instead should be showing with multiple columns to the referenced columns in another table

**Comment by devwithsubhrajit2002** [comment]
@rahul3v I may help in fixing the bug so you can assign me this issue so that I fix it as soon as possible.

**Comment by shashankdaima** [comment]
Ayo @rahul3v👋, Thanks for being this issue to community, it would appreciated if you restate your requirement.
but can you confirm that you want this type of behavior?
If your `workspace` table is this 👇,
| id | name |
|-----------------|-----------------|
| 1| Rahul's Workspace|
| 2| Shashank's Workspace |
| 3| David's Workspace|

and your `projects` table is like this 👇, 
| id | userId |workspaceId|
|-----------------|-----------------|-----------------|
| 1| 1(pk of Rahul's workspace)|2(pk of Shashank's Workspace)|

Let me know this true or not.
Shashank, 
Community Member 💚

**Comment by saltcod** [comment]
Could you provide your table definitions @rahul3v? That might help debug quicker

**Comment by rahul3v** [comment]
Sample Example:
projects table is linked with multiple keys of workspaces table

```prisma
modal workspaces {
 userId   @db.Uuid
 id       @id @db.Uuid
 projects projects[]

}

modal projects { 
id          @id @db.Uuid
userId      @db.Uuid
workspaceId @db.Uuid
workspace   workspaces @relation(fields: [workspaceId, userId], references: [id, userId], onDelete: Cascade)
}
```

**Comment by shashankdaima** [comment]
@saltcod @rahul3v  is this still an active issue? If yes, can I take this?

**Comment by saltcod** [comment]
yup still active @shashankdaima

**Comment by shashankdaima** [comment]
@saltcod can you assign me, I am taking it.

**Comment by saltcod** [comment]
Thanks @shashankdaima!

We don't have an assignment process. Feel free to throw up a draft PR to "claim" it as you're working on it.

**Comment by shashankdaima** [comment]
Hey, I tried to replicate the issue, but couldn't get anywhere. I am attaching the video. Let me know I am missing anything.

https://github.com/supabase/supabase/assets/64317542/e07c6668-2537-404b-9458-2e094909d615

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
