### ISSUE TITLE
The storage UI allows a trailing space for bucket name, but this does not work.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#16641]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you accidentally enter a trailing space in a new bucket name (spaces are supposedly not allowed according to the UI message) the bucket is created but cannot be accessed at all from the UI.  Because it is a space it is impossible to see this in the UI.  It cost a user many hours tracking this down even with help in Discord.  You can not access or delete the bucket.  Finally had them try do delete with SQL and their bucket name with trailing space and the bucket was deleted.

The UI should not allow invalid names for buckets.

## Steps to reproduce

Create a bucket with the name `cat-videos ` (note the trailing space)
Try to do anything with it in the UI after.

Note the UI also seems to take `cat videos` with the middle space and it works even though space is not a valid character according to:
![image](https://github.com/supabase/supabase/assets/54564956/4afa860e-a4a6-47c6-b294-5abc557be8b7)

## Expected behavior

The UI should not allow invalid bucket names.

**Comment by suveshmoza** [comment]
I'm a newcomer to Supabase and I'm eager to make contributions. This particular issue appears to be a suitable starting point for me, and I'm interested in taking it on.

**Comment by GaryAustin1** [comment]
@suveshmoza  this was from one of the Supabase devs a few days ago:
_Hey kishanhitk! We don't really have an assignment process. You can feel free to work on it though — adding an in-progress PR here often helps, even if it's very-very in-progress!_

**Comment by GaryAustin1** [comment]
So that means two possible things.
1) The UI should handle trailing spaces correctly and not say they are invalid.
2) If spaces are not allowed then the Storage API should flag them as invalid.
![image](https://github.com/supabase/supabase/assets/54564956/e74d254f-8526-49b9-b079-cdb98772bdc9)
I'll for now add storage tag to this.  Not clear to me which is the correct answer as even though space is not safe it seems to work.

**Comment by SuhelMakkad** [comment]
That makes sense

**Comment by nwaliaez** [comment]
Given this context, my question is: Should we disallow spaces altogether or consider modifying the description to something like "Only lowercase letters, numbers, dots, hyphens, and spaces"?
