### ISSUE TITLE
Broken link in Dashboard

### ISSUE THREAD

**Issue by quicksnap** [supabase/supabase#1667]
There's no link here :) `database/pooling` section. "Click here" is just text.

![image](https://user-images.githubusercontent.com/1199742/119182519-dc73ce80-ba27-11eb-8c30-10240313f2dc.png)

**Comment by MildTomato** [comment]
hi @quicksnap 👋 

thanks for raising this, we've updated the dashboard and the link will be fixed in the next release 😄
