### ISSUE TITLE
Twitter logo may be need to update as new 'X' logo

### ISSUE THREAD

**Issue by EngHasanSabbir** [supabase/supabase#16671]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On July 23, 2023, the social media platform twitter has been updated their logo in new abstract 'X' shape after that most of online site who used Twitter traditional bird logo they have changed their logo to new 'X' shape but superbase did not update it yet. I think that is important to aware them about this. 

 ## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com/'
2. In home page  Scroll down to 'Join the community'
3. You can see the old bird logo with People Avatar
4. You can find the similar issue in footer icon.

## Expected behavior
![image](https://github.com/supabase/supabase/assets/60088050/bd0e4e19-866f-482d-823c-fbea49cd8889)

## Screenshots
![image](https://github.com/supabase/supabase/assets/60088050/a904917d-bfdb-4817-a1b0-053c8903b0f8)
![image](https://github.com/supabase/supabase/assets/60088050/b34c5ee2-aaf0-4a71-a3ab-18a94bd547f4)

## Additional context

It's also important to regularly update the site frontend as well as backend.

**Comment by rishabhbizzle** [comment]
hey, can you assign this issue to me I would like to work on it

**Comment by rishabhbizzle** [comment]
The project is using react-feather package for icons but the new X logo is not yet available in this package so what should we do now?

**Comment by AbhijeetBiswalCodes** [comment]
#16688

**Comment by Aakash-Rajbhar** [comment]
hello can you assign this issue to me, I want to contribute in it passionately

**Comment by fsansalvadore** [comment]
Fixed by:
- #16688
- #16768
- #16805
