### ISSUE TITLE
Unable to Create Organisation on Old as well as on New Accounts

### ISSUE THREAD

**Issue by myselfprincee** [supabase/supabase#16693]
**I just Logged in with my Account to start a Project. But, Found an issue that I am unable to create Organisation on my Old as well as on my New Accounts. I think this is a Bug. I am attaching the Video. Please have a look 👇**

https://github.com/supabase/supabase/assets/114233864/d1d563a3-e573-4376-a911-9d092996a951

**Comment by saltcod** [comment]
Hey @myselfprincee could you open a ticket for that from the "Help" button in the top right of the dashboard? We'll have a look right away, thanks!

**Comment by myselfprincee** [comment]
Ok Sure 👍

**Comment by saltcod** [comment]
Actually @myselfprincee  — we had a known issue this morning that may have caused this. Has this resolved for you in the past hour or so?

**Comment by myselfprincee** [comment]
Let me Check..

**Comment by myselfprincee** [comment]
# Yes, It is working totally fine..

**Thank You**

**Comment by saltcod** [comment]
woooo hoo! great news thanks!
