### ISSUE TITLE
Database schema relations undefined after restoring from backup

### ISSUE THREAD

**Issue by alienzz** [supabase/supabase#1670]
I'm not 100% sure this is the problem but it seems to be this way. 

In my nodejs app, I've connected to the supabase postgres db with the credentials given and ran a simple query

```SELECT * FROM products```

This worked being connected directly to the db with credentials, throughout my development, until I had to restore to a previous backup of my db. Now when I run this query I get this error:

```error: relation "products" does not exist```

I can run the same query inside the SQL editor on the supabase web client, and I can also run a `supabase.from('products').select('*')` just fine as well, but I cannot get any query to work from connecting directly to the db.

This problem happened immediately after restoring from backup.

**Comment by dragarcia** [comment]
Hi @alienzz! Checking on this now

**Comment by dragarcia** [comment]
Alright, I believe I've found the problem and solved it. Would you mind helping me check once more if you can run `SELECT * FROM products`?

**Comment by alienzz** [comment]
And we're back!! Working just as before. 

Did I make a mistake when restoring? What should I do to prevent this in the future? I just want to know if it was on my end, or at least know if I can fix it manually next time.

Thank you!

**Comment by dragarcia** [comment]
No mistakes on your side, it was a small bug on ours in the restoration process. Sorry about that. There is already a solution to it and a fix should be on its way in the next few days. 

I'll leave this open for now until the fix goes live. Till then, if you are performing any more restores, just ping here so that we can manually fix the last step for you.

Thanks!

**Comment by alienzz** [comment]
Thanks, that sounds great! I really appreciate the help 👍

**Comment by alienzz** [comment]
I may have found a somewhat related bug as well. All of my public tables I've created can no longer 'see' any other table when trying to create a foreign key. The only table this currently works on is `products`

Example of my dropdown menu for `distribution_order_items`. 
![19108508aed38de78e29bc9182e3115e](https://user-images.githubusercontent.com/5201977/119398626-71cbc880-bc9d-11eb-8395-0cf641ce7af7.png)

**Comment by dragarcia** [comment]
That's odd, I wasn't able to replicate this when restoring my own project, unfortunately. Nevertheless, we'll look more into it. Just wondering, were all your tables made through the Supabase web client?

**Comment by alienzz** [comment]
Yes, all tables and columns were made inside the Supabase web client. It might be a clientside issue because if I refresh my tables page, sometimes it works and, other times, no keys are visible or able to be selected. I'll keep inspecting but it doesn't seem to be related to the issue above. Thank you

**Comment by dragarcia** [comment]
Hey @alienzz! So we've pushed the changes recently so the bug should be squished. You should now be able to restore your project without that issue. I will be closing this. Do just re-open it if your restorations are still running into trouble.

As for the other issue, if it does persist, feel free to open up another issue on it.

Thanks! 😄
