### ISSUE TITLE
Failed to load configuration: required key API_EXTERNAL_URL missing value during supabase db reset

### ISSUE THREAD

**Issue by vduseev** [supabase/supabase#16702]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

After linking a newly created local development setup to a project created via supabase.com, the local development stops working due to the following error:

```shell
$ supabase db reset
Resetting local database...
{"level":"fatal","msg":"Failed to load configuration: required key API_EXTERNAL_URL missing value","time":"2023-08-22T12:45:18Z"}
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

Tested this behavior today (Aug 22, 2023) with a fresh project by following the steps below.

## To Reproduce

1. Create new directory `mkdir api-external-url`
2. Initialize git repo in it `git init`
3. Initialize supabase in it `supabase init`
4. Start supabase `supabase start`

   List of the containers started by `supabase start`

   | Image | Port | Name |
   | - | - | - |
   | public.ecr.aws/supabase/studio:v0.23.06 | 0.0.0.0:54323->3000/tcp | supabase_studio_api-external-url |
   | public.ecr.aws/supabase/postgres-meta:v0.66.3 | 8080/tcp | supabase_pg_meta_api-external-url |
   | public.ecr.aws/supabase/edge-runtime:v1.6.6 | 8081/tcp | supabase_edge_runtime_api-external-url |
   | public.ecr.aws/supabase/imgproxy:v3.8.0 | 8080/tcp | storage_imgproxy_api-external-url |
   | public.ecr.aws/supabase/storage-api:v0.40.4 | 5000/tcp | supabase_storage_api-external-url |
   | public.ecr.aws/supabase/postgrest:v11.1.0 | 3000/tcp | supabase_rest_api-external-url |
   | public.ecr.aws/supabase/realtime:v2.10.1 | 4000/tcp | realtime-dev.supabase_realtime_api-external-url |
   | public.ecr.aws/supabase/inbucket:3.0.3 | 1100/tcp, 2500/tcp, 0.0.0.0:54324->9000/tcp | supabase_inbucket_api-external-url |
   | `public.ecr.aws/supabase/gotrue:v2.62.1` | `9999/tcp` | `supabase_auth_api-external-url` |
   | public.ecr.aws/supabase/kong:2.8.1 | 8001/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp | supabase_kong_api-external-url |
   | public.ecr.aws/supabase/postgres:15.1.0.90 | 0.0.0.0:54322->5432/tcp | supabase_db_api-external-url |

5. Create a test migration `supabase migration new first`

   ```sql
   CREATE TABLE profiles (
     id uuid PRIMARY KEY NOT NULL,
     user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
     username text UNIQUE NOT NULL,
     avatar_url text,
     updated_at timestamp with time zone NOT NULL DEFAULT now()
   );
   ```

6. Apply this migration

   ```shell
   $ supabase db reset
   Resetting local database...
   Restarting containers...
   Applying migration 20230822110704_first.sql...
   Seeding data supabase/seed.sql...
   Finished supabase db reset on branch main.
   ```

7. Create a free project at supabase.com

8. Link the Supabase.com project to the local environment

   ```shell
   $ supabase link -p $SUPABASE_DB_PASSWORD --project-ref $SUPABASE_REF
   Finished supabase link.
   ```

9. New files appear in the `supabase/.temp/` directory:

   | File name | Contents |
   | - | - |
   | `gotrue-version` | v2.92.1 |
   | `project-ref` | xxxxxxxxxxxxxxxx |

10. Invoke `supabase db reset` again

**This causes the error: `Failed to load configuration: required key API_EXTERNAL_URL missing value`**

```shell
$ supabase db reset
Resetting local database...
{"level":"fatal","msg":"Failed to load configuration: required key API_EXTERNAL_URL missing value","time":"2023-08-22T12:45:18Z"}
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

## Expected behavior

The command `supabase db reset` works the same way it did before linking to
the supabase.com project.

It appears that the new version of `gotrue` container causes this behavior
after updating from `v2.62.1` to `v2.92.1`.

## System information

- OS: macOS Ventura 13.4.1 (c) (22F770820d)
- Version of supabase CLI: 1.77.9

## Additional context

Possibly related: https://github.com/supabase/gotrue/issues/1194 

### Changing the version in the `gotrue-version` file

1. Change the version in `supabase/.temp/gotrue-version` from `v2.92.1` to `v2.62.1` using any kind of editor

2. Make sure the file is no longer than exactly 7 bytes otherwise the following error is thrown

   ```shell
   $ supabase db reset
   Resetting local database...
   invalid reference format
   Retrying after 4s: public.ecr.aws/supabase/gotrue:v2.62.1

   invalid reference format
   Retrying after 8s: public.ecr.aws/supabase/gotrue:v2.62.1

   invalid reference format
   Try rerunning the command with --debug to troubleshoot the error.
   ```

3. Truncate the file to 7 bytes

   ```shell
   $ truncate -s -1 supabase/.temp/gotrue-version
   $ cat supabase/.temp/gotrue-version
   v2.62.1%
   ```

4. Execute db reset

   ```shell
   $ supabase db reset
   Resetting local database...
   Restarting containers...
   Applying migration 20230822110704_first.sql...
   Seeding data supabase/seed.sql...
   Finished supabase db reset on branch main.
   ```

   Works perfectly fine!

### Removing the `gotrue-version` file completely

1. Remove the `supabase/.temp/gotrue-version` file

2. Try to reset db

   ```shell
   $ supabase db reset
   Resetting local database...
   Restarting containers...
   Applying migration 20230822110704_first.sql...
   Seeding data supabase/seed.sql...
   Finished supabase db reset on branch main.
   ```

   Works fine!

3. Check if the link is still working and we can push db changes to the supabase.com project

   ```shell
   supabase db push
   Applying migration 20230822110704_first.sql...
   Finished supabase db push.
   ```

   Seems to work as well and is an acceptable fix for me 👍

**Comment by sweatybridge** [comment]
This has been fixed in the latest cli stable release.

**Comment by wilfred-py** [comment]
Thanks - changing the `gotrue-version` worked for me.

**Comment by julortiz** [comment]
I think the fist step is update the CLI: 

- MacOS: brew upgrade supabase
- Windows: scoop update supabase

Now: 
- supabase start

That update all local stack.

**Comment by djbowers** [comment]
Deleting `./supabase/.temp/gotrue-version` and restarting supabase worked for me!
