### ISSUE TITLE
Chore: add pgbouncer guide

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#1672]
# Chore

## Describe the chore

We have PGBouncer guides/explanations in a blog post, but we don't seem to have a dedicated guide in the docs.

For instance, we currently link to this from the dashboard pooling page - when it perhaps should be an educational guide.
https://supabase.io/blog/2021/04/02/supabase-pgbouncer#pool-modes

**Comment by kiwicopple** [comment]
Added: https://supabase.io/docs/guides/database/connecting/connection-pooling
