### ISSUE TITLE
Self-hosted Supabase instance cannot generate Typescript types.

### ISSUE THREAD

**Issue by lino-levan** [supabase/supabase#16793]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Self-hosted Supabase is unable to generate types. Clicking this button:
<img width="568" alt="image" src="https://github.com/supabase/supabase/assets/11367844/179db73e-a2b1-4097-916b-0db1fe204ee7">

Generates this error:
> Failed to generate types: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><title>Supabase</title><meta name="viewport" content="initial-scale=1.0, width=device-width"/><link rel="apple-touch-icon-precomposed" sizes="57x57" href="/favicon/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon-precomposed" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon-precomposed" sizes="72x72" href="/favicon/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon-precomposed" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon-precomposed" sizes="60x60" href="/favicon/apple-touch-icon-60x60.png"/><link rel="apple-touch-icon-precomposed" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png"/><link rel="apple-touch-icon-precomposed" sizes="76x76" href="/favicon/apple-touch-icon-76x76.png"/><link rel="apple-touch-icon-precomposed" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png"/><link rel="icon" type="image/png" href="/favicon/favicon-196x196.png" sizes="196x196"/><link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96"/><link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32"/><link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16"/><link rel="icon" type="image/png" href="/favicon/favicon-128.png" sizes="128x128"/><meta name="application-name" content=" "/><meta name="msapplication-TileColor" content="#1E1E1E"/><meta name="msapplication-TileImage" content="mstile-144x144.png"/><meta name="msapplication-square70x70logo" content="mstile-70x70.png"/><meta name="msapplication-square150x150logo" content="mstile-150x150.png"/><meta name="msapplication-wide310x150logo" content="mstile-310x150.png"/><meta name="msapplication-square310x310logo" content="mstile-310x310.png"/><meta name="theme-color" content="#1E1E1E"/><link rel="shortcut icon" href="/favicon/favicon.ico"/><link rel="icon" type="image/png" href="/favicon/favicon.ico"/><link rel="manifest" href="/favicon/site.webmanifest"/><link rel="alternate" type="application/rss+xml" href="/feed.xml"/><link rel="apple-touch-icon" href="/favicon/favicon.ico"/><meta name="msapplication-config" content="/favicon/browserconfig.xml"/><meta name="next-head-count" content="30"/><link rel="stylesheet" type="text/css" data-name="vs/editor/editor.main" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.37.0/min/vs/editor/editor.main.css"/><link rel="stylesheet" type="text/css" href="/css/fonts.css"/><link rel="preload" href="/_next/static/css/24862156fbf6a92b.css" as="style"/><link rel="stylesheet" href="/_next/static/css/24862156fbf6a92b.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script defer="" src="/_next/static/chunks/9411-866ffac3c178cdb3.js"></script><script defer="" src="/_next/static/chunks/1213-d5e543bd24b62cff.js"></script><script defer="" src="/_next/static/chunks/2621-2533718c36324bc8.js"></script><script defer="" src="/_next/static/chunks/7606-847615b8cb82a463.js"></script><script defer="" src="/_next/static/chunks/5512.90fe7a453c6d7791.js"></script><script defer="" src="/_next/static/chunks/5652.641b8a11fadaeb97.js"></script><script src="/_next/static/chunks/webpack-5037b67e32c966db.js" defer=""></script><script src="/_next/static/chunks/framework-88c3fab5a4d30eea.js" defer=""></script><script src="/_next/static/chunks/main-3ca6fb5daa80fdb7.js" defer=""></script><script src="/_next/static/chunks/pages/_app-0ece61f4ad55c89e.js" defer=""></script><script src="/_next/static/chunks/pages/404-2f82b58972bef958.js" defer=""></script><script src="/_next/static/bRoWrWoHz9lnNF5l0AqYQ/_buildManifest.js" defer=""></script><script src="/_next/static/bRoWrWoHz9lnNF5l0AqYQ/_ssgManifest.js" defer=""></script></head><body class="dark"><div id="__next" data-reactroot=""><div class="min-h-full flex flex-col"><div class="relative mx-auto flex h-screen w-full flex-col items-center justify-center"><div class="absolute top-0 mx-auto w-full max-w-7xl px-8 pt-6 sm:px-6 lg:px-8"><nav class="relative flex items-center justify-between sm:h-10"><div class="flex flex-shrink-0 flex-grow items-center lg:flex-grow-0"><div class="flex w-full items-center justify-between md:w-auto"><a href="/projects"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%27120%27%20height=%2724%27/%3e"/></span><img alt="supabase" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%"/><noscript><img alt="supabase" srcSet="/img/supabase-dark.svg 1x, /img/supabase-dark.svg 2x" src="/img/supabase-dark.svg" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" loading="lazy"/></noscript></span></a></div></div></nav></div><div class="absolute select-none opacity-[5%] filter transition duration-200 blur-none"><h1 style="font-size:28rem">404</h1></div><div class="flex flex-col items-center justify-center space-y-6 transition opacity-0"><div class="flex w-[380px] flex-col items-center justify-center space-y-3 text-center"><h3 class="text-xl">Looking for something? 🔍</h3><p class="text-scale-1100">We couldn&#x27;t find the page that you&#x27;re looking for!</p></div><div class="flex items-center space-x-4"><a href="/projects"><button type="button" class="relative justify-center cursor-pointer inline-flex items-center space-x-2 text-center font-regular ease-out duration-200 rounded-md outline-none transition-all outline-0 focus-visible:outline-4 focus-visible:outline-offset-1 border bg-brand-600 dark:bg-brand/70 hover:bg-brand-600/80 dark:hover:bg-brand text-white border-brand dark:border-brand focus-visible:outline-brand-600 shadow-sm text-sm leading-4 px-3 py-2"> <span class="truncate">Head back</span> </button></a></div></div></div></div><div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/404","query":{},"buildId":"bRoWrWoHz9lnNF5l0AqYQ","nextExport":true,"autoExport":true,"isFallback":false,"dynamicIds":[15652],"scriptLoader":[]}</script></body></html>

Which is just the 404 page. If I look at the network requests, it seems to be making a request to 

```
http://localhost:8000/project/default/undefined/projects/default/types/typescript
```

which looks like a pretty broken URL.

## To Reproduce

1. Set up a self-hosted instance with docker
2. Open up the studio
3. Click the "generate types" button

## Expected behavior

I expect it to download the typescript definitions.

## System information

- OS: Debian Linux
- Browser: Chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

I'm also completely unable to generate these types through the CLI. This essentially makes Supabase unusable for me. Checkout https://discord.com/channels/839993398554656828/1144328675601432636 for context.

**Comment by kishanhitk** [comment]
I am also having a similar issue on the local supabase instance. The error message is different, though. 
<img width="1680" alt="image" src="https://github.com/supabase/supabase/assets/41117038/0b73cc11-133a-45e9-b590-34e6ce19f6cc">

Also, I don't think this is directly related to CLI, but CLI is affected.
