### ISSUE TITLE
Blog mp4's not working 

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#168]
# Bug report

## Describe the bug

When i visit https://supabase.io/blog/2020/08/05/supabase-auth on my iPhone, the auto-playing videos don't work. I'm curious if this is because my phone is too old, or if all iPhones are affected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.io/blog/2020/08/05/supabase-auth
2. Check if the gif/videos are visible

## Expected behavior

Pretty videos

## Screenshots

![IMG_D0D03FECDD1C-1](https://user-images.githubusercontent.com/10214025/91829259-d2c8f180-ec73-11ea-9bc2-f5ae4dc531a7.jpeg)

## System information

- iPhone 6
- iOS 12.4 ish

**Comment by soedirgo** [comment]
In my phone & Mac, the first video worked fine in Safari, but not the rest. FWIW, the native iOS/macOS video player has always been pretty janky for me, so this felt like an iOS/macOS problem.

All the videos worked fine on Firefox.

System info:

iPhone SE (iOS 13.6.1)
MBP 15 (macOS 10.15, Safari 13)

**Comment by kiwicopple** [comment]
Looks like react was dropping `playsinline`. Had to convert it to `playsInline`

**Comment by kiwicopple** [comment]
Strange

Works on the preview deploy - https://5f4e3f77df51c60008dccc9f--supabase.netlify.app/blog/2020/08/05/supabase-auth

Doesn't work on new deploy - https://supabase.io/blog/2020/08/05/supabase-auth/

Could a cloudflare/caching issue now?

**Comment by kiwicopple** [comment]
Possible cloudflare issue: https://community.cloudflare.com/t/mp4-videos-not-working-on-safari/50818/2

except that cloudflare is acting as a DNS only

<img width="185" alt="image" src="https://user-images.githubusercontent.com/10214025/91852891-04ea4b80-ec94-11ea-9da3-0f7cae0c1a73.png">


SO discussion: https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari

**Comment by kiwicopple** [comment]
Not sure why it would be different between the preview deploy and prod (certificates?), but perhaps we can add a [header to netlify](https://docs.netlify.com/routing/headers) with the corrections outlined here:

https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server/32998689#32998689

**Comment by phamhieu** [comment]
@kiwicopple can you try to rename the video files (adding number suffix...) and deploy again? 
i often do that to bypass caching issue.

**Comment by kiwicopple** [comment]
Looks like that worked @phamhieu 🎉 

Thanks!
