### ISSUE TITLE
bug: Dashboard gets stuck if user deletion fails.

### ISSUE THREAD

**Issue by kishanhitk** [supabase/supabase#16830]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you try to delete a user from the dashboard, and if the deletion fails for some reason, the confirmation popup does not go away, and the user can't interact with the page. The only option is refreshing the page from the browser/

## To Reproduce

1. Go to Auth Dashboard
2. Try deleting a user, that will cause an error
3. You see the error message, and the confirmation popup does not dismiss.

## Expected behavior

The confirmation popup should be dismissed if the deletion fails.

## Screenshots

https://github.com/supabase/supabase/assets/41117038/80f5fd3c-f747-494a-b117-08f5a11dafc6

## System information

- OS: macOS
- Browser: Arc (Chromium)

**Comment by shashankdaima** [comment]
hey @kishanhitk👋  , is your PR complete solution to this issue? 🤔
Do you need any help in this issue? I also faced this particular issue. 
Let me know.
