### ISSUE TITLE
Created image bucket and getting error 

### ISSUE THREAD

**Issue by MariuzM** [supabase/supabase#16861]
I've just created image bucket on supabase, once created i get this error

`Failed to retrieve folder contents from "images": An error has occurred: The operation was aborted. ` 

<img width="373" alt="image" src="https://github.com/supabase/supabase/assets/36937039/64b64879-d8bf-46ee-9306-37435c481394">

I can use the bucket and upload images with no issues so not sure what this error is about

**Comment by GaryAustin1** [comment]
Duplicate  https://github.com/supabase/supabase/issues/16413
