### ISSUE TITLE
Self-hosted Supabase Studio does not work without Internet

### ISSUE THREAD

**Issue by BaccS** [supabase/supabase#16880]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With up-to-date repo from supabase git, when you run _docker compose up_ and then disconnect from Internet and trying to load Studio page, you get the following error:

GET https://js.hcaptcha.com/1/api.js?render=explicit&onload=hcaptchaOnLoad net::ERR_INTERNET_DISCONNECTED 

## To Reproduce

1. Clone supabase repo
2. Configure according to Self hosting instructions
3. Run docker compose up
4. Disconnect machine from Internet
5. Try to open http://localhost:8000
6. 
## Expected behavior

Supabase Studio UI should appear

## Screenshots

<img width="676" alt="image" src="https://github.com/supabase/supabase/assets/39173294/c210e9c9-1a6b-47f2-b455-29793cd43f68">

## System information

- OS: macOS
- Browser: Chrome, Safari
- Version of Node.js: 18.16

**Comment by saltcod** [comment]
Curious what version you're on @BaccS

**Comment by BaccS** [comment]
> Curious what version you're on @BaccS

Studio: supabase/studio:20230803-15c6762
And just in case here are all versions:
<img width="1422" alt="image" src="https://github.com/supabase/supabase/assets/39173294/363803b2-ba70-4f5f-af2f-13c3bd7f9231">
