### ISSUE TITLE
Improving typing in documentation

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#16889]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-verifyotp

## Describe the problem

The documentation specifies a ``VerifyOtpParams`` type, but we don't know what this type corresponds to. We don't know which fields are possible, and this can make it confusing to use.

![image](https://github.com/supabase/supabase/assets/25107942/09cfc226-85ec-490d-ae39-0c463b2025d3)
)

## Describe the improvement

We could add a "hover" effect to display the content of the type as in the Svelte kit documentation:

![Record_select-area_20230828054917](https://github.com/supabase/supabase/assets/25107942/497cfa5f-0ca8-4808-af66-3dfaf43539c9)

## Additional context

/

**Comment by burggraf** [comment]
@charislam If the UI is a solved problem for now is there anything else you feel we need to do here, or can we close this?

**Comment by charislam** [comment]
Yes I think we can close. The type extraction bug has a separate issue somewhere (though I can't remember what it's called right now), so we can track that there.
