### ISSUE TITLE
Built with Supabase Site

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#169]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

We need a "Built with Supabase" showcase site

A showcase of sites and services that are built on Supabase with 

## Details

Some ideas:

- create a new website (Next.js)
- add a section to our current Docusaurus site
- an indicator of whether they are open source and a link to source code if available
- Create an easy way for people to add their site (PR or via a form?)

**Comment by kiwicopple** [comment]
Some inspiration

- Docusaurus https://v2.docusaurus.io/showcase/
- Next.js https://nextjs.org/showcase
- Bulma: https://bulma.io/expo/
- Gatsby: https://www.gatsbyjs.com/showcase/

My vote would be on a PR system

**Comment by kiwicopple** [comment]
Another possibility is to use GitHub Discussions since we now have access: 
https://github.com/supabase/supabase/discussions?discussions_q=category%3A%22Show+and+tell%22

**Comment by awalias** [comment]
having it a part of the supabase.io site would be my preference in the long run, good discoverability and more motivation to include your own site, but still worth building the catalogue first in discussions

**Comment by ephelsa** [comment]
Hey @awalias! I can help. 

Give me some time to be free. 😁

**Comment by ephelsa** [comment]
Hello! 👀

![Supabase showcase](https://user-images.githubusercontent.com/25624035/97086483-1ba08500-15e9-11eb-96f2-a30625a777c5.gif)
