### ISSUE TITLE
settings not found 

### ISSUE THREAD

**Issue by sanba-anass** [supabase/supabase#16903]
![image](https://github.com/supabase/supabase/assets/83970851/b6e6d403-918d-43cf-8837-eded61b3fd44)
can't find any gear icon in the hosted version of supabase

**Comment by kishanhitk** [comment]
The settings in the hosted version is controlled by the `config.toml` file.

**Comment by saltcod** [comment]
What @kishanhitk said! 
Here's some more documentation to get started: 
https://supabase.com/docs/guides/cli/local-development
