### ISSUE TITLE
Getting "global is not defined" after configuring supabase

### ISSUE THREAD

**Issue by MhL5** [supabase/supabase#16921]
## Title
 Global Not Defined Error When Using Vite React Template 

## Description
An issue has been identified where the `global not defined` error arises when we use the command `npm create vite@latest my-app -- --template react`, as recommended in the Getting Started documentation. However, the error does not occur when using `npm create vite@latest`.

## Steps to reproduce

1. Follow the getting started documentation for react
2. `npm run dev`

## Expected behavior
The command should run without any errors, and we should see the list of countries.

## Current behavior
Running the command results in a global not defined error in the browser dev tool console.
![Alt Text](https://i.stack.imgur.com/M9pXh.png)

## Possible Solution
using `npm create vite@latest` instead solved this issue for me and my friends.

## Additional context
This issue has been reproduced by myself and two of my friends. We hope this information proves helpful in resolving the bug.

**Comment by jacob-8** [comment]
This is presumably happening because of https://github.com/supabase/postgrest-js/issues/465#issuecomment-1844407289

**Comment by encima** [comment]
This seems to be resolved when using Vite 5 with SvelteKit 2, please comment and we can reopen if this is still occurring.
