### ISSUE TITLE
supabase-analytics container fail to start

### ISSUE THREAD

**Issue by liuyu1996** [supabase/supabase#16962]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

docker-compose up -d prompt "<<EOF: line 0: syntax error: EOF in backquote substitution" error

## Screenshots

![image](https://github.com/supabase/supabase/assets/42428054/48471d86-bdbb-4018-8837-b33bf1bcd2cb)

## System information

- OS: [linux, macOS]

**Comment by kiwicopple** [comment]
hey @liuyu1996 - can you please provide some steps to replicate? As you can see here, all the systems seem to be working fine:

https://www.youtube.com/watch?v=FqiQKRKsfZE&embeds_referring_euri=https%3A%2F%2Fsupabase.com%2F

If there is a way we can replicate your issue then we can help, but at this stage it's difficult to know what you're doing differently from the video above

**Comment by liuyu1996** [comment]
> hey @liuyu1996 - can you please provide some steps to replicate? As you can see here, all the systems seem to be working fine:
> 
> https://www.youtube.com/watch?v=FqiQKRKsfZE&embeds_referring_euri=https%3A%2F%2Fsupabase.com%2F
> 
> If there is a way we can replicate your issue then we can help, but at this stage it's difficult to know what you're doing differently from the video above



> hey @liuyu1996 - can you please provide some steps to replicate? As you can see here, all the systems seem to be working fine:
> 
> https://www.youtube.com/watch?v=FqiQKRKsfZE&embeds_referring_euri=https%3A%2F%2Fsupabase.com%2F
> 
> If there is a way we can replicate your issue then we can help, but at this stage it's difficult to know what you're doing differently from the video above

I followed the steps on the document：
1. git clone --depth 1 https://github.com/supabase/supabase
2. cd supabase/docker
3. cp .env.example .env
4. docker-compose pull
5. docker-compose up -d
and then this problem arises

**Comment by liuyu1996** [comment]
> hey @liuyu1996 - can you please provide some steps to replicate? As you can see here, all the systems seem to be working fine:
> 
> https://www.youtube.com/watch?v=FqiQKRKsfZE&embeds_referring_euri=https%3A%2F%2Fsupabase.com%2F
> 
> If there is a way we can replicate your issue then we can help, but at this stage it's difficult to know what you're doing differently from the video above

I followed the steps on the document：

1、git clone --depth 1 https://github.com/supabase/supabase
2、cd supabase/docker
3、cp .env.example .env
4、docker-compose pull
5、docker-compose up -d
and then this problem arises

**Comment by kiwicopple** [comment]
I'm not 100% sure tbh because I can't replicate this one on either a Mac or a Linux machine. Can you share more details about your environment? Linux, mac, windows? Docker versions, etc?

**Comment by liuyu1996** [comment]
> I'm not 100% sure tbh because I can't replicate this one on either a Mac or a Linux machine. Can you share more details about your environment? Linux, mac, windows? Docker versions, etc?

Mac: MacBook Pro M2, docker version is 20.10.14
Linux: Ubuntu 18.04.6, docker version is 20.10.7
need me to provide any other information？

**Comment by jasgeo75** [comment]
I get the similar results as @liuyu1996 .

```
See DBConnection.start_link/2 for more information

    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
Kernel pid terminated (application_controller) ({application_start_failure,logflare,{{shutdown,{failed_to_start_child,'Elixir.Cainophile.Adapters.Postgres',invalid_password}},{'Elixir.Logflare.Application',start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done
sh: 18:13:10.091: not found
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10982ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

```


Linux: Manjaro (Plasma), docker version is 24.0.5

**Comment by ChangwooLim** [comment]
for me,
docker-compose up -d did not work but docker compose up -d worked

**Comment by liuyu1996** [comment]
I use docker compose up -d, now is worked

**Comment by flavienbwk** [comment]
You must upgrade to [Docker's compose plugin](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually) instead of the default docker-compose binary.

**Comment by pouyababaie** [comment]
Faceing the same issue here :

Docker version 24.0.6
Docker Compose version v2.21.0
![Screenshot from 2023-09-19 15-03-15](https://github.com/supabase/supabase/assets/21077272/d569cbce-6be6-419c-8433-df004a598225)


i went through the installation process just like the video. but i don't know where i am  being wrong

**Comment by ventsyv** [comment]
I'm seeing the same issue in my own logflare based image.

```
supabase-analytics  | 17:02:46.585 [info] Migration finished
supabase-analytics  | 
supabase-analytics  | 17:02:47.690 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
supabase-analytics  | 
supabase-analytics  | 17:02:47.724 [info] Elixir.Logflare.SigtermHandler is being initialized...
supabase-analytics  | 
supabase-analytics  | 17:02:47.733 [error] GenServer #PID<0.4871.0> terminating
supabase-analytics  | ** (stop) :sock_closed
supabase-analytics  | Last message: {:tcp_closed, #Port<0.20>}
supabase-analytics  | 
supabase-analytics  | 17:02:47.735 [notice] Application logflare exited: Logflare.Application.start(:normal, []) returned an error: shutdown: failed to start child: Cainophile.Adapters.Postgres
supabase-analytics  |     ** (EXIT) :sock_closed
supabase-analytics  | 
supabase-analytics  | 17:02:47.748 [notice]     :alarm_handler: {:clear, :system_memory_high_watermark}
supabase-analytics  | Kernel pid terminated (application_controller) ({application_start_failure,logflare,{{shutdown,{failed_to_start_child,'Elixir.Cainophile.Adapters.Postgres',sock_closed}},{'Elixir.Logflare.Application',start,[normal,[]]}}})
supabase-analytics  | 
supabase-analytics  | Crash dump is being written to: erl_crash.dump...done
```

I'm building logflare from source. The environment is identical, the beams are in the same locations, the permissions looks the same... 
Seems to be working with the latest image from github, so it seems it's a local problem, but it sure looks suspicious that people are experiencing the same issue.
[erl_crash.txt](https://github.com/supabase/supabase/files/12769719/erl_crash.txt)

Attaching the coredump.

**Comment by peter-ergisi** [comment]
There is something wrong with the authentication. Analytics fails to start when unable to connect the database.

To rectify follow steps here
https://github.com/supabase/supabase/issues/11957

Namely this command to clear data. Afterwards docker compose/restart should work now.
sudo rm -rf docker/volumes/db/data

**Comment by Akash187** [comment]
I am facing the same issue. How come this issue is closed without any solution?

**Comment by ventsyv** [comment]
> I am facing the same issue. How come this issue is closed without any solution?

I think there are a couple of different issues that are manifesting the same (or similar) way.
Mine was similar to @jasgeo75 reported, but not necessarily what OP @liuyu1996 reported. @liuyu1996 closed the ticket because his issue was resolved. 
@Akash187 Is your issue like that of @liuyu1996 or like mine? If it's like mine, maybe try opening a new ticket.

**Comment by Akash187** [comment]
@ventsyv my issue is sorted. I think we need to fix documentation it is nowhere mentioned on the docs that we need to enable analytics in `config.toml` file for logs to work instead opposite is mentioned **Local logs rely on the Supabase Analytics Server, and are available in the Studio automatically.**

<img width="1440" alt="Screenshot 2023-11-01 at 12 25 30 AM" src="https://github.com/supabase/supabase/assets/21134455/c57c92ad-d3e3-4c26-8ea9-6c7fde9ceb02">

**Comment by jonra1993** [comment]
I had same problem and the cause was that I just copy docker-compose file and no other files in volume I solved it cloning the project

**Comment by thawri1** [comment]
I has same issue and fixed by running this:
`# Stop docker and remove volumes:
docker compose down -v

# Remove Postgres data:
rm -rf volumes/db/data/`

**Comment by duan-zhou** [comment]
I noticed this issue occurred when the container was started initially, and then the POSTGRES_PASSWORD in the .env file was changed.

**Comment by DWilly92** [comment]
@duan-zhou that's exactly it. I was following the self host guide, which has you start the containers before hardening the various credentials in the .env file, and when I changed the POSTGRES_PASSWORD and restarted the services, supabase-analytics failed to start. As I had no data yet I simply deleted the `./volumes/db/data` folder (per @thawri1 ), and re-ran `docker compose up -d`, and it started successfully.

**Comment by cjfagerstrom** [comment]
@PROMCz11 Yes. 

># Remove Postgres data:
>`rm -rf volumes/db/data/`
>
>This will destroy all data in the database and storage volumes, so be careful!

[https://supabase.com/docs/guides/self-hosting/docker#uninstalling](url)

**Comment by madmaxaus** [comment]
if you're running on truenas, you'll need to give the correct ACL permissions to the dataset (in addtion to the above)

**Comment by angusfungayi** [comment]
For me this worked:
# Stop everything
docker compose down -v

# Remove broken volumes
sudo rm -rf volumes/

# Re-copy volumes from the repo
git checkout -- volumes/

ls -la volumes/db/
You should see all files are .sql and there is init folder
