### ISSUE TITLE
A part of document of auth-helpers for nextjs, API router name convention is wrong.

### ISSUE THREAD

**Issue by shuent** [supabase/supabase#16984]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In example on [this page](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-side), file path name is wrong. Next.js 13 app directory must use `$pathName/router.js` for API router. It confused me when I use the library.

cf. https://nextjs.org/docs/app/building-your-application/routing/route-handlers

**Comment by kishanhitk** [comment]
Thanks @shuent for pointing this out.

I have raised a PR that fixes this.
