### ISSUE TITLE
Auth Callback is returned as anchor and not as query

### ISSUE THREAD

**Issue by PaulRennerbs** [supabase/supabase#1698]
# Bug report

## Describe the bug

The URL that's you get redirected to when using a magic link looks like this:

http://IP:3000/#access_token=

Instead of

http://IP:3000/?access_token=

This makes the server unable to get the data (Or at least I can't find a way to access that)

Also, the path specified in your auth settings doesn't care if I change it to mydomain.com/test or mydomain.com/admin it will always take mydomain.com which is pretty bad. I sadly cannot use the auth like this at all. Does anyone have a solution for this?

## To Reproduce

Send a magic link to an Email via the widget of supabase/ui

## Expected behavior

http://IP:3000/?access_token=

**Comment by PaulRennerbs** [comment]
Also tested it without port or on a real domain it always uses # instead of ?

**Comment by kiwicopple** [comment]
Hey @PaulRennerbs - this URL fragments implementation is part of the original codebase from Netlify (presumably because they are so "Jamstack" focused). We're a bit reluctant to change it since it's a core piece of their tech and it would make our fork quite divergent.

> This makes the server unable to get the data (Or at least I can't find a way to access that)

See this helper function: https://github.com/supabase/gotrue-js/blob/4312f53411dc6fdf963f8adb48200cddf9905bd9/src/lib/helpers.ts#L16

> Also, the path specified in your auth settings doesn't care if I change it to mydomain.com/test or mydomain.com/admin

Perhaps the `redirectTo` param will help here? 
https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect

**Comment by kiwicopple** [comment]
Just adding a bit more info from the Supabase team - the URL fragments is part of the OAuth standard:

https://stackoverflow.com/questions/16733863/oauth2-0-implicit-grant-flow-why-use-url-hash-fragments/40999805#40999805

> The URI Fragment is used instead of query parameter , from security point of view. The URI segment will never be sent over the network to the redirect url.

This is a security feature, so we don't plan on changing it

**Comment by PaulRennerbs** [comment]
> Hey @PaulRennerbs - this URL fragments implementation is part of the original codebase from Netlify (presumably because they are so "Jamstack" focused). We're a bit reluctant to change it since it's a core piece of their tech and it would make our fork quite divergent.
> 
> > This makes the server unable to get the data (Or at least I can't find a way to access that)
> 
> See this helper function: https://github.com/supabase/gotrue-js/blob/4312f53411dc6fdf963f8adb48200cddf9905bd9/src/lib/helpers.ts#L16
> 
> > Also, the path specified in your auth settings doesn't care if I change it to mydomain.com/test or mydomain.com/admin
> 
> Perhaps the `redirectTo` param will help here?
> https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect

Ah okay that helper funtion is what i was looking for. 

The redirecTo parameters doesnt work tho i have tried it multiple times. I always get sent to the main / url no matter what

**Comment by awalias** [comment]
`redirectTo` URL either has to be on the `Site URL` domain or has to be included in the Additional redirect URLs *exactly* (including params and protocol)

![image](https://user-images.githubusercontent.com/458736/119591926-1408bf00-be0a-11eb-99c6-59204042f00d.png)

some examples here are:
`https://localhost:4000` not allowed (wrong protocol on secondary domain)
`http://localhost:4000/something` not allowed
`http://localhost:4000?foo=bar` not allowed

`http://localhost:3000?foo=bar` allowed
`http://localhost:3000/something` allowed
`http://localhost:4000/welcome` allowed

**Comment by awalias** [comment]
closing for now, feel free to reopen @PaulRennerbs 👍

**Comment by carlomigueldy** [comment]
Hi Hi @awalias have you guys tried this on Flutter Web?

**Comment by binajmen** [comment]
In NextJS, you can (client side) do this hacky stuff (you should add some tests around):
```js
  useEffect(() => {
    const urlSearchParams = new URLSearchParams(router.asPath.split('#')[1]);
    const params = Object.fromEntries(urlSearchParams.entries());
    // do stuff with params
  }, [])
```

**Comment by arpitdalal** [comment]
I know I'm late to the party but maybe this can help someone someday.

I do this when using [remix](https://remix.run).

Let's say that the link in the email takes the user to `localhost:3000/#access_token=...`, I check if the user has a session in my loader, if they don't, I throw a `Response` which I catch in my `CatchBoundary`, in it's `useEffect` I manipulate the `document.location.href` to replace `/#` with `/?`, then using the `useNavigate` hook from `remix`, I navigate the URL to the new search params and then trigger the reload of the page using `location.reload()`.
```tsx
// CatchBoudary in the index route

export function CatchBoundary() {
  const caught = useCatch();
  const navigate = useNavigate();

  useEffect(() => {
    const modifiedUrl = document.location.href.replace("/#", "/?");
    const url = new URL(modifiedUrl);
    if (
      url.searchParams.get("access_token") &&
      url.searchParams.get("refresh_token")
    ) {
      navigate(`/?${modifiedUrl.split("?")[1]}`);
      location.reload();
    }
  }, []);

  if (caught.status === 401) {
    return (
      <div>
        <p>You must be logged in.</p>
        <Link to='/login?redirectTo=/'>Login</Link>
      </div>
    );
  }

  throw new Error(`Unexpected caught response with status: ${caught.status}`);
}
```
As it reloads, my loader function runs again and at the beginning of the loader, I check if the URL has `access_token` and `refresh_token` as search params, in this case, there will be, so now it will set a new auth session using the session from `request` and setting `access_token` and `refresh_token` to that session and then I return a redirect (provided by remix) with committing that altered session.
```tsx
// loader function in the index route

export const loader: LoaderFunction = async ({ request }) => {
  const url = new URL(request.url);
  const accessToken = url.searchParams.get("access_token");
  const refreshToken = url.searchParams.get("refresh_token");
  if (accessToken && refreshToken) {
    const session = await setAuthSession(request, accessToken, refreshToken);

    return redirect("/", {
      headers: {
        "Set-Cookie": await commitSession(session),
      },
    });
  }
  // other code
}
```
```tsx
// setAuthSession function in utils

export const setAuthSession = async (
  request: Request,
  accessToken: string,
  refreshToken: string
): Promise<Session> => {
  const session = await getSession(request.headers.get("Cookie"));
  session.set("access_token", accessToken);
  session.set("refresh_token", refreshToken);

  return session;
};
}
```
`commitSession` and `getSession` are provided by the `createCookieSessionStorage` provided by remix.
