### ISSUE TITLE
Bad formatting in infrastructure page

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#17008]
# Bug report

## Describe the bug

Looks like markdown is badly formatted.

<img width="721" alt="Screenshot 2023-08-30 at 8 18 33 AM" src="https://github.com/supabase/supabase/assets/8291514/eca391a4-7e5d-4bdb-a809-2d717b4f521f">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/dashboard/project/_/settings/infrastructure

## Expected behavior

<img width="753" alt="Screenshot 2023-08-30 at 8 20 06 AM" src="https://github.com/supabase/supabase/assets/8291514/dd67d56a-ca89-49f9-aca1-aa7aa0bc503d">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by nwaliaez** [comment]
Hello @NabeelAyubee , based on what I know, there isn't a formal assignment process, and you can start working on the issue even without being assigned.

**Comment by MildTomato** [comment]
@NabeelAyubee - exactly what @nwaliaez said, there is no formal process.

Feel free to open a PR and we'll be happy to review.

**Comment by MildTomato** [comment]
@Bhavyawahie I've just realized there isn't a way to work on this.

One of the supabase team members will need to pick up this issue I think.
Sorry for the confusion! Thanks for taking a look though 🙌

**Comment by akoolarni** [comment]
I am eager to contribute. Please let me contribute to any of the good first issues please.

**Comment by KSSaiTeja** [comment]
I would like to work to fix this issue..

**Comment by Moazzum786** [comment]
I would like to contribute. Help needed ,to make my first open source contribution.

**Comment by SAGARSINGH-1** [comment]
Request to Close Repo Issue: Issue #17008 has already been Resolved.

![image](https://github.com/supabase/supabase/assets/81561733/65ec0514-196f-45b1-86c8-f8cc986792c7)

Hey, @MildTomato
I hope this message finds you well. I'm writing regarding issue #17008. Although this issue isn't assigned to me, I noticed that it has already been resolved and would like to request its closure.

**Comment by Omsoni06** [comment]
![Screenshot (5)](https://github.com/supabase/supabase/assets/92720665/4e51b158-08fd-4db0-b734-eeed0361dc1a)
![Screenshot (4)](https://github.com/supabase/supabase/assets/92720665/4c179651-c4c8-45d2-a622-49feca16c20a)

This issue is already solved, but not closed yet

**Comment by saltcod** [comment]
Sorry all! Didn't realize this one had gotten fixed. Apologies.
