### ISSUE TITLE
$ in front of column name causes issue with definition tab

### ISSUE THREAD

**Issue by rs-nikic** [supabase/supabase#17013]
**Issue:** $ symbol in front of a column name breaks the UI

<img width="1317" alt="image" src="https://github.com/supabase/supabase/assets/143053594/cf686322-e4b9-4b15-b31d-3ada50cf06c3">

**Steps to reproduce:**
1. Create a new table with multiple columns
2. Make sure one of the column contains $ symbol in front of the name. (In my case $age - Check image attached below)
3. Go to table definition and the UI breaks as in image attached before.

<img width="1110" alt="image" src="https://github.com/supabase/supabase/assets/143053594/0ce86f96-2618-4336-8b12-57c22884e137">

**Comment by abhinav-18max** [comment]
Can you please provide more info on this issue

**Comment by encima** [comment]
This is sort of a bug but Postgres (or any db afaik) should not have special characters in their column names. Additional info can be added as comments on the table / column. I will leave this open as we should prevent these naming conventions or sanitize them
