### ISSUE TITLE
getSession() does not properly retrieve session in React Native

### ISSUE THREAD

**Issue by lockieluke** [supabase/supabase#17016]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

```typescript
const {data: {session}, error} = await supabase.auth.getSession();
if (error) {
    console.error(`Error fetching session: ${error.message}`);
    return;
}
```
`getSession()` throws `Invalid Refresh Token: Already Used, signing out`

This is how I initialise `supabase`:
```typescript
import {createClient} from "@supabase/supabase-js";
import AsyncStorage from "@react-native-async-storage/async-storage";

export const supabase = createClient(SUPABASE_URL, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYXpicmFuemJqd3dwb2JkbnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMyMzA4NTUsImV4cCI6MjAwODgwNjg1NX0.rtexsFScSEt5EWd8_N-7eVZrkaCdtsktcYcjJe8_AGU', {
    auth: {
        storage: AsyncStorage,
        persistSession: true
    }
});
```

## Expected behavior

Refresh token should not expire after just a day.

Current workaround:
```typescript
const {data: {session}, error} = await supabase.auth.getSession();
const user = session?.user;
if (error) {
    console.error(`Error fetching session: ${error.message}, signing out`);
    const {error: signOutError} = await supabase.auth.signOut();
    if (signOutError) {
        console.error(`Error signing out: ${error.message}`);
    }
    navigation.current?.navigate('Auth');
    return;
}
```
Sign out if error is thrown

## System information

- OS: iOS
- Framework: React Native
- Version of supabase-js: 2.33.1

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!

**Comment by joycexjiang** [comment]
Have you found a solution for this?
