### ISSUE TITLE
Unable to delete a trigger created in the wrong table

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17027]
### Discussed in https://github.com/orgs/supabase/discussions/16975

<div type='discussions-op-text'>

<sup>Originally posted by **srowe0091** June 20, 2023</sup>
I have a feeling this might be a bug with permissions. I accidentally created a trigger in the wrong table, the `_http_response` was selected by default when I was testing a trigger, but once I realized where that trigger was created, I went to delete it, but I can't delete it because im getting this error `ERROR: must be owner of relation _http_response`

How was I able to add a trigger to the table, but not be able to delete it? 

It doesn't appear in the dashboard, and I can't delete it manually with SQL editor.

How can I delete this trigger?
</div>

**Comment by RichieBotteri93** [comment]
Same for me.  If you go to the database menu under "triggers" on the Supabase dashboard, The three dotted menu button (edit/delete) is not visible in the right corner on each trigger you create. It was there 2 months ago so something has happened in the newer updates.

**Comment by gabrielchristo** [comment]
Got a similar situation here.
I've wrongly created a trigger in the audit_log_entries table from auth schema. Now i can't delete it.
Besides the problem itself, one way to avoid this would be to leave the table drop-down unselected by default, this way the user would be forced to verify the table he is creating the trigger.

**Comment by RichieBotteri93** [comment]
Even though there should be an edit button for protected schemas I have a solution. You can delete the trigger from the SQL editor. you just type: 

`drop trigger [add name of trigger function] on auth.users. ` than click on run. 

If you cannot delete it, try deleting all database functions connected to it.

**Comment by RichieBotteri93** [comment]
> Got a similar situation here. I've wrongly created a trigger in the audit_log_entries table from auth schema. Now i can't delete it. Besides the problem itself, one way to avoid this would be to leave the table drop-down unselected by default, this way the user would be forced to verify the table he is creating the trigger.

Even though there should be an edit button for protected schemas, I have a solution. You can delete the trigger from the SQL editor. Just type:

DROP TRIGGER [add the name of the trigger function] ON auth.users.

Then click on 'Run.'

If you cannot delete it, try deleting all database functions connected to it.

**Comment by shahid-0** [comment]
@RichieBotteri93 Thank you man `DROP TRIGGER [add the name of the trigger function] ON auth.users.` this works for me.

**Comment by clickclickcode** [comment]
@RichieBotteri93 Thank you very much!

Just in case someone needs a bit more information to solve this issue or would like to see some documentation, here you go:

https://supabase.com/docs/guides/database/postgres/triggers

Personally, I have very little experience, if any, with sql and took the example in the documentation a bit too literal and included the quotations in the example when trying to apply it. Obviously, that was not the way. The example shows:

drop trigger "trigger_name" on "table_name";

I wrote (in the context of my issue):

drop trigger "on_auth_user_created" on "auth_users";

This clearly does not work. With the help of @RichieBotteri93's input I realised that the syntax is instead:

drop trigger on_auth_user_created on auth.users;

(NO quotations)

I hope this helps.

**Comment by TheOtherBrian1** [comment]
@saltcod This has been a problem with Supabase for a while. Triggers in PostgreSQL are a bit strange. They're not owned by the database roles that created them, but by the tables they're attached to. Whenever a user adds a trigger to a table owned by supabase_admin, they lose the privileges to delete or edit the trigger. 

However, the function attached to the trigger is still owned by the user. They can delete the trigger by deleting the corresponding function with a CASCADE modidfer:
```sql
DROP FUNCTION <function name>(<arguments>) CASCADE;
```

**Comment by joshenlim** [comment]
hey everyone! apologies for the confusion in UI behaviour here, but we've since prevented users from creating triggers on protected schemas through the GUI - the only way to do so (create, update, delete etc) will be through the SQL editor (using the query as mentioned [here](https://github.com/supabase/supabase/issues/17027#issuecomment-1731112453)

i'll go ahead to close this ticket since the original issue was about this, but please do feel free to let me know otherwise! 🙏
