### ISSUE TITLE
Dashboard keep showing loading for a long time when import data with wrong format

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17029]
### Discussed in https://github.com/orgs/supabase/discussions/16948

<div type='discussions-op-text'>

<sup>Originally posted by **hieuwu** April 11, 2023</sup>
### Discussed in https://github.com/orgs/supabase/discussions/13528

<div type='discussions-op-text'>

<sup>Originally posted by **hieuwu** April  8, 2023</sup>
# ⚙️ Summary
Currently, when I import data from CSV file, I notice that if we set the value of a column on Supabase is float4 and the data of this column is a string, the platform will stop working without any response.
For example, my column is `price` with type is `float4`. I import a data set with a row containing value at price column is "this is a string". The platform keep showing loading message forever

<img width="720" alt="Screen Shot 2023-04-08 at 14 33 58" src="https://user-images.githubusercontent.com/43868345/230711338-f1a51f0c-4460-426d-a938-7d775b6bcea0.png">

# 💡 Suggestion
It would be nice if we have some mechanism to verify the format of data for number before performing any operation.

I imported the file below
[product.csv](https://github.com/supabase/supabase/files/11182812/product.csv)
</div></div>

**Comment by Hallidayo** [comment]
@saltcod - On importing the example spread sheet the studio now gives feedback to the user about issues about the data in the spreadsheet. I seem to get warnings on both `Import` and `Paste` and I get really good feedback for changes. Seems okay to close?

**Comment by saltcod** [comment]
thanks @Hallidayo !
