### ISSUE TITLE
Enter not working in filter popup

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17025]
### Discussed in https://github.com/orgs/supabase/discussions/16971

<div type='discussions-op-text'>

<sup>Originally posted by **probablykasper** June 14, 2023</sup>
# Bug report

In the filter popup, `Enter` does not apply the filter:

![SCR-20230612-egci](https://github.com/supabase/supabase/assets/11315492/ea4a744b-027c-49e4-b1a0-f11cb46171c9)

## System information

- OS: macOS
- Browser (if applies) Brave</div>

**Comment by ZainAli104** [comment]
okay, I will fix this issue. Assign to me

**Comment by VedantKale08** [comment]
> okay, I will fix this issue. Assign to me

Is this issue fixed?

**Comment by ZainAli104** [comment]
> > okay, I will fix this issue. Assign to me
> 
> Is this issue fixed?

Not yet, But I am working on it to fix this :)

**Comment by nachomglz** [comment]
> > > okay, I will fix this issue. Assign to me
> > 
> > 
> > Is this issue fixed?
> 
> Not yet, But I am working on it to fix this :)

Have you fixed it already?

**Comment by ZainAli104** [comment]
> > > > okay, I will fix this issue. Assign to me
> > > 
> > > 
> > > Is this issue fixed?
> > 
> > 
> > Not yet, But I am working on it to fix this :)
> 
> Have you fixed it already?

No, I don't fix this issue yet.

**Comment by Bibhavshah** [comment]
If no one is working on this issue than can I get this issue assigned?
