### ISSUE TITLE
Table Editor: Grid fails to load cells if cell value is extremely large

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17030]
### Discussed in https://github.com/orgs/supabase/discussions/16931

<div type='discussions-op-text'>

<sup>Originally posted by **joshenlim** February  3, 2023</sup>
We're currently actively looking into this - creating an issue here to track progress
Can reproduce by creating a table with a jsonb column, then inserting a row with a really large JSON</div>

**Comment by Bhavyawahie** [comment]
I tried replicating the same on Supabase platform and the application froze for a good few minutes displaying nothing but a white screen and consequently yielded into the following error.
JSON blob used: https://github.com/json-iterator/test-data/blob/master/large-file.json

> ![image](https://github.com/supabase/supabase/assets/34278282/01f523d3-4747-4072-a6d4-4688dc9ffa76)

**Comment by encima** [comment]
@supabase/frontend is this one still on the radar?

**Comment by Hallidayo** [comment]
@encima - Just did a test with a large jsonb array in the table editor and I get the following error:

<img width="403" alt="Screenshot 2024-09-15 at 18 25 06" src="https://github.com/user-attachments/assets/5b642286-3893-48de-9cea-5db64df049dd">

This gives the user a bit more of a clearer error/warning, What do you thnk?

**Comment by saltcod** [comment]
👨‍🍳  perfect thanks @Hallidayo !
