### ISSUE TITLE
403: Signups not allowed for this instance

### ISSUE THREAD

**Issue by onmyway133** [supabase/supabase#17031]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I could sign in with Twitter before. But today I'm adding profiles table and trigger as guided here https://supabase.com/docs/guides/auth/managing-user-data, I can no longer login. In the logs/auth-logs page I see 403 error

Now, even if I try to delete `profiles` table, remove function and triggers, the 403 error is still there

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow this guide https://supabase.com/docs/guides/auth/managing-user-data to add profiles, trigger function
2. We can no longer login / sign up
3. See log

```
{"component":"api","error":"403: Signups not allowed for this instance","level":"info","method":"GET","msg":"403: Signups not allowed for this instance","path":"/callback","referer":"http://localhost:3000","remote_addr":"171.230.112.255","time":"2023-08-30T13:04:44Z","timestamp":"2023-08-30T13:04:43Z"}

```

## Expected behavior

We should be able to login like before

## System information

- OS: macOS
- Browser: chrome 116.0
- Version of supabase-js: 2.32.0
- Version of Node.js: 18.15

**Comment by GaryAustin1** [comment]
Any chance this setting got toggled off?
![image](https://github.com/supabase/supabase/assets/54564956/c79462c8-eadb-4070-8b47-02d3314fc1a9)

**Comment by onmyway133** [comment]
@GaryAustin1 that is in fact the issue, not sure how it was turned of after I used trigger

**Comment by onmyway133** [comment]
@GaryAustin1 @joshenlim thanks for the prompt fix 👍

**Comment by joshenlim** [comment]
No worries @onmyway133 - thank you so much for reporting it to us! 🙏

**Comment by davehowson** [comment]
I've turned sign ups on but I still keep getting
`403: Signups not allowed for this instance` when I try to sign a user up using Google OAuth.
Any idea why?

**Comment by joshenlim** [comment]
Hey there @MilesV64! Gotcha on this - are you able to provide a set of reproducible steps for me to investigate with?

**Comment by MilesV64** [comment]
Hey @joshenlim thanks for the reply, I tried again with a fresh browser where I had never used Supabase dashboard before to try to replicate it for you, and this time it's actually sticking! So maybe despite refreshing in my usual browser, I hadn't gotten the new code. But it seems to be working well, thank you :)

**Comment by joshenlim** [comment]
Ahh gotcha on this @MilesV64! Glad to hear that all's working for you :) feel free to reach out again if you do run into this nonetheless! 🙏🙏

**Comment by AlexIsMaking** [comment]
> I'm going to reopen this as a potential general issue. I've now seen another case today and one last week in Discord where the user says they did not turn it off and at least one case was working.... https://discord.com/channels/839993398554656828/1146514509704478780 https://discord.com/channels/839993398554656828/1143641761256845452/1144019688448331816
> 
> Hopefully helps if someone else encounters it. Will close again if no one else reports an issue in a week or Supabase identifies and fixes an issue.

I also had this issue - the toggle switched itself off and the only changes that I've made to my auth settings were disabling email signups and enabling OAuth signups via Notion.

I've switched the toggle back on now but I can see from my logs that some users are still running into this 403 error, while others are not. My only policies apply row level security and allow authenticated users to read their records. I also have a trigger on the Auth database, which runs after insert, to copy new users to a public users table. Users are not being created in the public table which they hit this error.

Needless to say, it's not great to be losing users because they can't signup to my service.

**Comment by TDucille** [comment]
I'm getting the same error as @AlexIsMaking. I created a webhook that fires when a user is inserted into the auth table to copy them into another table. The toggle automatically switched off.

**Comment by joshenlim** [comment]
hey guys! hmm webhooks/triggers should not be affecting the auth sign ups at all as these 2 are mutually exclusive. If you're able to provide some steps to reproduce I'd really appreciate that as nothing stands out code-wise at the moment 🙏 

I've also tried to enable/disable email/notion signups as @AlexIsMaking mentioned but i couldn't reproduce it either

**Comment by AlexIsMaking** [comment]
Supabase support recommended disabling the allow signups toggle, saving and re-enabling it, which solved the issue for me 😅
