### ISSUE TITLE
Astro support for auth-helpers

### ISSUE THREAD

**Issue by AceCodePt** [supabase/supabase#17099]
### Discussed in https://github.com/orgs/supabase/discussions/17003

<div type='discussions-op-text'>

<sup>Originally posted by **AceCodePt** August 30, 2023</sup>
Hi!
I already implemented the Astro needed support including the examples.
The support is for both server and client.
Truth to be told it's almost identical to some of NextJS implementations except different types.
</div>

**Comment by saltcod** [comment]
Thanks @AceCodePt — going to close this one in favour of the discussion.
