### ISSUE TITLE
User can't scroll vertically or horizontally in the TABLE Tab when inputing data to the table.

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#171]
# Bug report
User can't scroll vertically or horizontally in the TABLE Tab when inputing data to the table.

## Describe the bug
When trying to add or view data in the Table format, user can't scroll vertically or horizontally to see all the data. It seems to be disabled.

## To Reproduce

FOR VERTICAL SCROLLING ISSUE:

1. Choose the Lightning Icon in the menu on the left side bar.
2. Select the 'TABLE' on the tabs between TABLE | SQL.
3. Add a new row to a Table
4. View coming from the right side of the screen with field shows up.
5. Vertical scrolling seems to be disabled. **Can't scroll to see all the fields available.** 

-----------------
FOR HORIZONTAL SCROLLING ISSUE:

If no row of data is available:

1. Choose the Lightning Icon in the menu on the left side bar.
2. Select the 'TABLE' on the tabs between TABLE | SQL.
3. Choose an empty table
4. Try scrolling horizontally to see all the field name **(You cannot do this.)**

## Expected behavior

You can scroll horizontally or vertically to see all the table field name so you can add the input as needed.

## System information

- OS: MacOS
- Browser: Chrome and Safari

**Comment by kiwicopple** [comment]
Hey @inbytesdevteam! I can't seem to replicate this on my Mac (chrome). Am I looking in the same place as you?

![Sep-02-2020 18-48-13](https://user-images.githubusercontent.com/10214025/91972283-0b88c980-ed4d-11ea-9614-c96266fe0244.gif)

**Comment by inbytesdevteam** [comment]
Hi @kiwicopple 

Here's a demo of the actual bugs. GIF divided into 4 parts:

**WITH DATA IN TABLE**
1. With data/row - horizontal scrolling - OK
2. Adding a new row - vertical scrolling on the left side view - NOT OK

**WITHOUT DATA IN TABLE**
3. Without data/row - horizontal scrolling - NOT OK
4. Adding a new row - vertical scrolling on the left side view - NOT OK


![Supabase bug](https://user-images.githubusercontent.com/70461143/92008672-0aba5c80-ed7a-11ea-8a1e-fbd797a46b18.gif)

**Comment by kiwicopple** [comment]
Aha! The gif is perfectly clear - thanks @inbytesdevteam 

@joshenlim FYI

**Comment by kiwicopple** [comment]
Fixed by @joshenlim !
