### ISSUE TITLE
Can't delete json data from side panel of Table Editor

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17102]
## Describe the bug

You can't delete all of a json field's data from the side panel editor.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new table in the Table Editor, with a json field
2. Add some dummy json to this field
3. Open the expanded json editor (the side panel)
4. Try and delete the entire field
5. See error

![screenshot-2023-09-01-at-12 07 15](https://github.com/supabase/supabase/assets/105593/1c3d4a51-a7c3-4647-9a84-4f53c29f589a)
![screenshot-2023-09-01-at-12 06 11](https://github.com/supabase/supabase/assets/105593/293b4376-2438-467b-b7f2-8f2a5e473280)
![screenshot-2023-09-01-at-12 06 31](https://github.com/supabase/supabase/assets/105593/ff74a25e-74a3-47a0-a4f1-ea1bb0307640)

**Comment by subhradwip01** [comment]
if you do not mind can I give a try on that?
