### ISSUE TITLE
supabase.upsert doesn't return data that was inserted

### ISSUE THREAD

**Issue by cwwmbm** [supabase/supabase#17118]
Over here: https://supabase.com/docs/reference/javascript/upsert

The documentation says the response will have data component that will look like this:
```
{
  "data": [
    {
      "id": 1,
      "name": "Albania"
    }
  ],
  "status": 201,
  "statusText": "Created"
}
```

In reality data is returned null:
```
{
  error: null,
  data: null,
  count: null,
  status: 201,
  statusText: 'Created'
}
```

I'm executing the following:
`await supabase.from('table').upsert(data, {onConflict: 'conflict_field'});`

**Comment by GaryAustin1** [comment]
Maybe you are looking at v1 documentation?

v2 shows you need to use .select() to get back data...

![image](https://github.com/supabase/supabase/assets/54564956/a079b21b-be08-4d0a-8608-34dae51fcc8d)

**Comment by cwwmbm** [comment]
You're right, my bad!

**Comment by Gwened** [comment]
Why doesn't Supabase support the Returning pattern?
Upser (a combination of select and insert) is less useful if you can't get the result of the select

**Comment by ibrahim-mousa** [comment]
> Why doesn't Supabase support the Returning pattern? Upsert (a combination of select and insert) is less useful if you can't get the result of the select.

@Gwened its a combination of Update and Insert so it makes sense having to call `.select` after
