### ISSUE TITLE
"JWSError JWSInvalidSignature" Error on Self-hosted Supabase

### ISSUE THREAD

**Issue by yekta** [supabase/supabase#17164]
## Describe the bug

We're self-hosting Supabase. I'm getting "JWS Invalid Signature" error on requests made through an admin client instance. Service key is valid, we are using that same key with the GoTrue library in our GO server.

## To Reproduce

```
const supabaseAdmin = createClient(
	supabaseUrl,
	supabaseServiceKey,
	{
		auth: {
			autoRefreshToken: false,
			persistSession: false
		}
	}
)
const { data, error } = await supabaseAdmin.from("some_table").select("*").limit(50)
```

That results in this error:
```
{
  code: 'PGRST301',
  details: null,
  hint: null,
  message: 'JWSError JWSInvalidSignature'
}
```

Any idea why this happens? It wasn't happening with the hosted version.

**Comment by mrkpatchaa** [comment]
@yekta you rock !!!

**Comment by yekta** [comment]
> @yekta you rock !!!

Happy to see that it helped. I remember seeing that suggestion somewhere but couldn’t remember where.

**Comment by pjhartin** [comment]
@yekta, I'm going to look stupid asking this — But how did you set the JWT secret?

**Comment by yekta** [comment]
> @yekta, I'm going to look stupid asking this — But how did you set the JWT secret?

We are using k8s using the community provided helm chart. So it’s a k8s secret. I’m not familiar with other methods of deployment but in any case it would end up being an environment variable I’m guessing because of how GoTrue expects it.

https://github.com/supabase/gotrue#json-web-tokens-jwt

**Comment by pjhartin** [comment]
Thanks @yekta.

In my case I'm using the Supabase CLI on my local machine - https://supabase.com/docs/guides/cli/getting-started

I've tried using a `.env` and trying the following keys, but no luck yet.

```
JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-basic"
GOTRUE_JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-gotrue"
SUPABASE_JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-supabase"
```

**Comment by jason1610** [comment]
> Thanks @yekta.
> 
> In my case I'm using the Supabase CLI on my local machine - https://supabase.com/docs/guides/cli/getting-started
> 
> I've tried using a `.env` and trying the following keys, but no luck yet.
> 
> ```
> JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-basic"
> GOTRUE_JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-gotrue"
> SUPABASE_JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long-supabase"
> ```
> 
> ![CleanShot 2023-09-21 at 14 06 46@2x](https://user-images.githubusercontent.com/1385026/269481860-548cec97-5f41-4b71-84ba-a6b452e5f615.png)

Any luck solving the issue? Ran into the exact same problem.

**Comment by yekta** [comment]
The version that caused the problems might’ve been generated with the generator on their website I don’t recall. The one I got working, I generated locally.

**Comment by kiwicopple** [comment]
Closing the issue, as it seems like the original issue has been resolved in the latest version - the cli newest version is postgres:15.1.0.117 already

Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by clwater** [comment]
@kiwicopple 
I found the same issues in My Edge Function local develop.

I try develop a Edge Function. And run ` supabase start` in docker env.

I write a ts code like:
```
  const authHeader = req.headers.get('Authorization')!
  const supabaseClient = createClient(
      Deno.env.get('NEXT_PUBLIC_SUPABASE_URL') ?? '',
      Deno.env.get('NEXT_PUBLIC_SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
  )

  const { data, error } = await supabaseClient.from('table').select('*')
```
as Example demo.

I get the anon key in `supabase status`. But when try this edge function in curls.
The supabaseclient retuen '{"code":"PGRST301","details":null,"hint":null,"message":"JWSError JWSInvalidSignature"}' this error

**Comment by clwater** [comment]
> @kiwicopple I found the same issues in My Edge Function local develop.
> 
> I try develop a Edge Function. And run ` supabase start` in docker env.
> 
> I write a ts code like:
> 
> ```
>   const authHeader = req.headers.get('Authorization')!
>   const supabaseClient = createClient(
>       Deno.env.get('NEXT_PUBLIC_SUPABASE_URL') ?? '',
>       Deno.env.get('NEXT_PUBLIC_SUPABASE_ANON_KEY') ?? '',
>       { global: { headers: { Authorization: authHeader } } }
>   )
> 
>   const { data, error } = await supabaseClient.from('table').select('*')
> ```
> 
> as Example demo.
> 
> I get the anon key in `supabase status`. But when try this edge function in curls. The supabaseclient retuen '{"code":"PGRST301","details":null,"hint":null,"message":"JWSError JWSInvalidSignature"}' this error

If i reomve  `{ global: { headers: { Authorization: authHeader } } }`, this supabase get is success.

In my think, If use this, supabase  will replace edge function ANON_KEY. 
But if use jwt in curls params, this edge function is error.

so, what scene I need used what key?
(Database RLS is set auth user can select)

**Comment by MGX-CODING** [comment]
@kiwicopple confirming this is still an issue. 

I am running Supabase with Docker compose locally : I can sign up to the application (auth) without any issue, so the anon key works as expected. 

But I cannot interact with the DB : 

```
curl 'http://localhost:8000/rest/v1/profiles?select=*' \
  -H 'Accept: */*' \
  -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:4200' \
  -H 'Referer: http://localhost:4200/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'apikey: myvalidapikey' \
  -H 'authorization: Bearer myvalidsessiontoken' \
  -H 'content-profile: public' \
  -H 'content-type: application/json' \
  -H 'prefer: return=representation' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'x-client-info: supabase-js-web/2.43.5' \
  --data-raw '{"username":"some username","birthday":"2006-06-25"}'
```

Do you have any quick solution for this issue ?

**Comment by adamhospodka** [comment]
In my case the 🐛 was that I did not use a secret with "at least 32 chars" ([source](https://postgrest.org/en/stable/tutorials/tut1.html#step-2-make-a-secret))

**Comment by rizhangdev** [comment]
+1 I'm seeing this as an issue. Is there an alternative to be able to locally develop?

**Comment by rizhangdev** [comment]
I just noticed the curl function given when initializing an edge function adds an Authorization header with the aforementioned token that obviously won't work for my production DB. I see that I have a JWT Secret that is supposed to help me generate a token, but when I use it with jwt.io to generate one, I get a "JWSSignatureVerificationFailed: signature verification failed" error when I try to use it with the curl. There's obviously a gap in my knowledge of how these tokens work so I'll keep learning about it, but it would be nice to be able to test these edge functions with curl.

**Comment by chaserswe** [comment]
after 2 days of searching and try every solution i just used the jwt code from supabase and made my own script to create anon and secure role key:

`
import { KJUR } from 'jsrsasign'

const JWT_HEADER = { alg: 'HS256', typ: 'JWT' }
const now = new Date()
const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
const fiveYears = new Date(now.getFullYear() + 5, now.getMonth(), now.getDate())

const anonToken = `
{
  "role": "anon",
  "iss": "supabase",
  "iat": ${Math.floor(today.valueOf() / 1000)},
  "exp": ${Math.floor(fiveYears.valueOf() / 1000)}
}
`.trim()

const serviceToken = `
{
  "role": "service_role",
  "iss": "supabase",
  "iat": ${Math.floor(today.valueOf() / 1000)},
  "exp": ${Math.floor(fiveYears.valueOf() / 1000)}
}
`.trim()

const generateRandomString = (length) => {
    const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    let result = ''
    const MAX = Math.floor(256 / CHARS.length) * CHARS.length - 1
    const randomUInt8Array = new Uint8Array(1)
    for (let i = 0; i < length; i++) {
      let randomNumber
      do {
        crypto.getRandomValues(randomUInt8Array)
        randomNumber = randomUInt8Array[0]
      } while (randomNumber > MAX)
  
      result += CHARS[randomNumber % CHARS.length]
    }
    return result
  }
  
const jwt_secret_key = generateRandomString(128);
const anonTokenSigned = KJUR.jws.JWS.sign(null, JWT_HEADER, anonToken, jwt_secret_key);
const serviceTokenSigned = KJUR.jws.JWS.sign(null, JWT_HEADER, serviceToken, jwt_secret_key);
console.log(`JWT_SECRET=${jwt_secret_key}`);
console.log(`ANON_KEY=${anonTokenSigned}`);
console.log(`SERVICE_ROLE_KEY=${serviceTokenSigned}`);
`

now everything works fine and i can just copy paste into .env file.

**Comment by Shooteger** [comment]
Using a local Supabase CLI version and getting too the error:
```
Error inserting: { code: 'PGRST301',
  details: null,
  hint: null,
  message: 'JWSError (JSONDecodeError "Not valid base64url")' }
```

when interacting with the supabase local database. All works, even login but not select, insert or anything else which interacts with the database directly.
What can I do? I have a correctly long JWT Secret and correct keys in my frontend .env. Supabase status shows all correct and running.

**Comment by rusakovic** [comment]
Ok. Got the same error.
Using local CLI.
Ran with 'supabase start'
Logs:
```
       API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
  S3 Storage URL: http://127.0.0.1:54321/storage/v1/s3
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
      ```
      
      Is 'JWT secret:' is not correct? Where/how to change it? Thank you

**Comment by erichsdb** [comment]
> 54321

I'm using the docker compose setup [from here](https://supabase.com/docs/guides/self-hosting/docker) where I can set my JWT secret in the .env file. 

My mistake was, that I generated and changed the ANON- and SERVICE-keys but didn't change the JWT secret in my .env.

**Comment by alessandrojcm** [comment]
Happening to me here too, locally using the Supabase CLI, when trying to use the client's `auth.admin.createUser` from a Node script. Tried a 120-long alphabetic secret and no dice, jwt.io verifies the token alright so not sure what is going on here.

**Comment by gbusto** [comment]
SUPER annoying problem. Used the tool Supabase provided and kept getting this error over and over. Wracking my brain for hours trying to figure out the problem.

Had Claude 3.7 write a script to generate new keys, and it worked. Script is here:
```js
const crypto = require('crypto');
const base64url = require('base64url');

function generateSupabaseKey(role, jwtSecret) {
  // Create the header
  const header = {
    alg: 'HS256',
    typ: 'JWT'
  };
  
  // Create the payload with required claims
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    role: role,
    iss: "supabase",
    iat: now,
    exp: now + (60 * 60 * 24 * 365 * 5) // 5 years expiration
  };
  
  // Base64Url encode the header and payload
  const encodedHeader = base64url(JSON.stringify(header));
  const encodedPayload = base64url(JSON.stringify(payload));
  
  // Create the content to be signed
  const signatureContent = `${encodedHeader}.${encodedPayload}`;
  
  // Create the signature
  const signature = crypto
    .createHmac('sha256', jwtSecret)
    .update(signatureContent)
    .digest();
  
  // Base64Url encode the signature
  const encodedSignature = base64url(signature);
  
  // Combine to create the JWT token
  return `${signatureContent}.${encodedSignature}`;
}

// Example usage
const JWT_SECRET = process.env.SUPABASE_JWT_SECRET || 'your-jwt-secret-here';

const serviceRoleKey = generateSupabaseKey('service_role', JWT_SECRET);
const anonKey = generateSupabaseKey('anon', JWT_SECRET);

console.log('SERVICE_ROLE Key:');
console.log(serviceRoleKey);
console.log('\nANON Key:');
console.log(anonKey);
```

Run this beforehand: `npm install crypto base64url`
And make sure the secret is set: `export SUPABASE_JWT_SECRET='your-jwt-secret-here'`

Then run this file: `node generate-supabase-keys.js`.

Solved the problem for me. Hope it helps someone else.

**Comment by Shreyasbhat03** [comment]
Thank you , it worked

**Comment by quangthien27** [comment]
If you need a quick fix for your local dev, just disable the `verify_jwt` for that edge function endpoint in config.toml
<img width="666" height="212" alt="Image" src="https://github.com/user-attachments/assets/a13d98e2-14f0-4453-ad73-a40358cca2e2" />

**Comment by febrd** [comment]
@yekta . MUCH OBLIGED!!!
