### ISSUE TITLE
Database error creating new user with trigger on auth.users

### ISSUE THREAD

**Issue by jollygreenegiant** [supabase/supabase#17186]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a trigger set up on the `auth.users` table for when a user is created that's defined as follows:

```
begin
  insert into public.accounts (id, email)
  values (new.id, new.email);
  return new;
end;
```

When I have this function enabled, creating a new auth account in any manner (through the Kotlin SDK and also through the dashboard) gives the following error:

```
{
  "component": "api",
  "error": "failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: permission denied for table accounts (SQLSTATE 42501)",
  "level": "error",
  "method": "POST",
  "msg": "500: Database error creating new user",
  "path": "/admin/users",
  "referer": "http://localhost:3000",
  "remote_addr": "136.54.134.118",
  "time": "2023-09-05T22:18:36Z",
  "timestamp": "2023-09-05T22:18:36Z"
}
```

RLS is not enabled on the accounts table, and **when I disable the function trigger, things work as expected** (without the new row being added to the accounts table of course)

Why would this function and/or trigger be causing 500 errors when creating a new user account?

Possibly related to #563 but I haven't been able to get it working with the solutions shown there

**Comment by GaryAustin1** [comment]
You should ask for help in discussions or Discord if you are not sure it is a bug.

Your trigger function must be `security definer` type as shown in the User Management starter template in the SQL editor, or in most of the starter guides.

Auth user does not have public schema access.
