### ISSUE TITLE
Table sizes are confusing

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#172]
# Bug report

## Describe the bug

We've had a lot of feedback on the `/database/tables` page

> I'm a bit confused about the %s here. Do I have a max size on my DB? If so where do I see that? How do I increase it? Am I going to run out of space?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a project
2. Click on the database icon

## Expected behavior

We should make the graphs a % of 15 GB (we can hard code this for now). This is approximately the size of each server (20GB - postgres + extensions)

## Screenshots

![image](https://user-images.githubusercontent.com/10214025/91918289-16b00b00-ecf5-11ea-905f-67256c76085b.png)

## Additional context

In the future we will need to improve the hardcoded 15GB to be the actual space on the server

**Comment by kiwicopple** [comment]
This is now released. There is still some feedback that it is confusing: 

![image](https://user-images.githubusercontent.com/10214025/93417661-3c373a00-f8db-11ea-9bc2-b1731b840c4b.png)

**Comment by phamhieu** [comment]
Then I will remove individual bar chart on table row item. When users hover on the storage header, I can show a pie chart popup which has detail of each table sizes.

**Comment by kiwicopple** [comment]
Let's remove the individual bar charts, but don't add the pie chart - that will need some design work to make it fit with the branding. At the moment, less is more

**Comment by awalias** [comment]
I think this is solved, closing for now
