### ISSUE TITLE
[chore] update www homepage with new videos/guides/podcasts

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#1722]
# Chore

## Describe the chore

Add new and updated links to podcasts, youtube guides, interviews that supabase has appeared in recently.

Also - start to catalog in a json file all of these so they can be indexed / searched through in the future.

## Additional context

Suggestion from @sw-yx
https://twitter.com/swyx/status/1397221084760576008?s=12

**Comment by sw-yx** [comment]
yes i am the king of chores lol

btw i [have been thinking](https://twitter.com/swyx/status/1337519894644940802) this would be a nice small saas to build... does supabase/postgres have a recommender feature?

**Comment by kiwicopple** [comment]
Love the way it's laid out in the "External Resources" with link + quote/snippet @sw-yx 

Could split out some of the resources in this page to their own page now:
https://supabase.io/docs/guides/examples

Current podcasts:

- https://softwareengineeringdaily.com/2020/10/15/supabase-open-source-firebase-with-paul-copplestone/
- https://www.heavybit.com/library/podcasts/jamstack-radio/ep-71-open-source-firebase-alternative-with-paul-copplestone-of-supabase/
- https://podrocket.logrocket.com/9
- https://fsjam.org/episodes/episode-33-supabase-with-paul-copplestone

Also could include the [Fireship](https://www.youtube.com/watch?v=WiwfiVdfRIc) video which is comprehensive and impartial
