### ISSUE TITLE
No Reset Email for Supabase login

### ISSUE THREAD

**Issue by raphaelniederer** [supabase/supabase#17248]
Hello

A year or two ago I registered on Supabase. Now I want to test Supabase again - I think it has now all functions for my app.

I tried to login with my email - failed - I tried to use forgot password function - get a message/toast notification in browser that Supabase send me a reset email - I never received an email.

Can anyone help me?

Thank you

**Comment by saltcod** [comment]
Hi! Sorry you're running into this @raphaelniederer — are you able to submit a support ticket from the dashboard or can you not even get that far?

**Comment by raphaelniederer** [comment]
I'm not able to log in - that is my problem. I don't know my password and the function forgot password doesn't send me an email (I looked also in my spam folder). And when i try to register I get a message - it already exists a user with this email.

**Comment by GaryAustin1** [comment]
The reset email won't work as you likely signed in with Github if that long ago.  You need to use that account.

**Comment by madhurgupta10** [comment]
I think there should be an option to unlink Github profile and use classic Username/Password method.

**Comment by raphaelniederer** [comment]
Sorry for my late answer. Nice, I needed to give Github again access for Supabase - now it works. I see my old projects. Thank you.

And I am also interested to unlink my Github profile.
