### ISSUE TITLE
Supabase Main/Auth Site Not Loading

### ISSUE THREAD

**Issue by Complexlity** [supabase/supabase#17254]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I navigate to the [official Supabase site](https://supabase.com/) it throw DNS_... error. After many refreshes, it eventually worked but my projects don't load. 
I logged out and tried to login again and now the auth page after I clicked the `Continue with GitHub` button doesn't load (throws DNS_....error)

![image](https://github.com/supabase/supabase/assets/105590967/72ea4fea-ba7d-4da8-add4-67ea870a0705)
![image](https://github.com/supabase/supabase/assets/105590967/05981459-7e9e-4f91-83b3-50f654009e95)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

The auth page loading up content so I can sign in

## System information

- OS: Windows
- Browser (if applies) chrome, firefox, edge, all
- Location: Nigeria

## Additional context
This had been happening for some days now. I always had to use VPN but the VPN started making sites that work before fail without using it and I had stopped using it and reset my conection. But still supabase does not work

**Comment by saltcod** [comment]
Hey there @Complexlity are you able to go to the Help button in the top right and submit a support ticket? We can try and sort you out from there! Please let us know if you're unable to access that.

**Comment by Complexlity** [comment]
> Hey there @Complexlity are you able to go to the Help button in the top right and submit a support ticket? We can try and sort you out from there! Please let us know if you're unable to access that.

Okay. I'll do that

**Comment by GaryAustin1** [comment]
I assume from comments this was a one off problem and not a currently open issue.
Closing unless further comments come in.

**Comment by Classic-The-Demigod** [comment]
This issue is also noticeable from my end I have to use a VPN to access the site I don't know why

**Comment by GaryAustin1** [comment]
Where you located?
There is/was a known issue with an ISP being blocked and Vercel (hosts supabase.com) in Nigeria... https://discord.com/channels/839993398554656828/1301879559863533620

Otherwise posting on a year old post is not likely to get  much attention.
