### ISSUE TITLE
Supabase Swift Client Libraries

### ISSUE THREAD

**Issue by satishbabariya** [supabase/supabase#1726]
Hey there @kiwicopple,

I've started working on supabase client lib's for swift language. I've completed GoTrue and Storage Lib's. and will start working on other lib's soon. So I was wondering what will be the process for the contributors. 

Implementations:
[https://github.com/satishbabariya/supabase-swift](https://github.com/satishbabariya/supabase-swift)
[https://github.com/satishbabariya/storage-swift](https://github.com/satishbabariya/storage-swift)
[https://github.com/satishbabariya/gotrue-swift](https://github.com/satishbabariya/gotrue-swift) 

Documentation and tests are remain. will work on that once I get time.

**Comment by kiwicopple** [comment]
wow this is awesome @satishbabariya - can you please dm me on twitter with your email? I'll invite you into our team slack and then we can coordinate the rest.

**Comment by satishbabariya** [comment]
@kiwicopple, sure I've send you dm on twitter.
