### ISSUE TITLE
Missing documentation for Auth Ui Component for Svelte and SolidJs

### ISSUE THREAD

**Issue by Stranger-771** [supabase/supabase#17279]
# Improve documentation
The Auth UI component documentation for Svelte and SolidJs does exist in npm but are missing in the official documentation on the website 

## Link 
https://supabase.com/docs/guides/auth/auth-helpers/auth-ui

## Describe the improvement

The documentation for Svelte and SolidJs must be added for the user to access the libraries on npm

**Comment by code-withAshish** [comment]
@saltcod Is this intentionally not documented or it's missing?

**Comment by saltcod** [comment]
This is a React-only component for the moment.
