### ISSUE TITLE
Query to select a row of table returns null and undefined

### ISSUE THREAD

**Issue by JS-Mechanic** [supabase/supabase#17289]
### Discussed in https://github.com/orgs/supabase/discussions/17265

<div type='discussions-op-text'>

<sup>Originally posted by **JS-Mechanic** September  8, 2023</sup>
I have a react app which uses supabase as its database.
this is my table:
![Settings_Table](https://github.com/supabase/supabase/assets/57490926/ad2bf0b3-dbb0-489d-8f83-0785da35dabb)
I have set the RLS policies to read and update for all users.
In the other hand, this is my react app codes:
Query function:
![getSettings](https://github.com/supabase/supabase/assets/57490926/1ce5a589-fe03-4e90-b7f2-4287bb6bdaec)
Custom hook:
![useSettings](https://github.com/supabase/supabase/assets/57490926/874ca5a4-419e-49c4-9e6b-506f5c415574)
and my functional component:
![UpdateSettingsForm](https://github.com/supabase/supabase/assets/57490926/cacec4d7-bb44-46c9-b16e-a4901b33c452)
But i get this error:
![error](https://github.com/supabase/supabase/assets/57490926/19c04748-5b4b-4f63-b76b-89a4abe7e05e)

</div>

**Comment by JS-Mechanic** [comment]
@joshenlim @MildTomato @kiwicopple 
Please help me 🙏🏻🙏🏻🙏🏻

**Comment by MildTomato** [comment]
Let's continue this in the discussion link you provided. It looks like react query is being used incorrectly on 1st glance of this.
