### ISSUE TITLE
Only "with check" expression allowed for insert

### ISSUE THREAD

**Issue by Aschen** [supabase/supabase#17299]
# Improve documentation

## Link 

https://supabase.com/docs/guides/database/postgres/row-level-security#insert-policies

## Describe the problem

I think the documentation about RLS Insert Policies have some issues since the example [here](https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/database/postgres/row-level-security.mdx#L108) is not working

![image](https://github.com/supabase/supabase/assets/4447392/9f3ba484-e52e-43ca-bfe3-aa6780a8e792)

## Describe the improvement

Since it's not possible to use the `using` keyword when defining a policy for `insert`, I changed the policy and created a trigger instead:

```
create policy "Users can insert an asset."
on public.assets for insert
to authenticated
with check ( true );

CREATE OR REPLACE FUNCTION set_user_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.user_id= auth.uid();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trigger_set_user_id"
  BEFORE INSERT ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION set_user_id();
```

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by burggraf** [comment]
@charislam is there anything holding up https://github.com/supabase/supabase/pull/17225?

**Comment by charislam** [comment]
we haven't heard back from the contributor in response to our reviews, but we can push this one over the line ourselves to close out the issue

**Comment by marcospgp** [comment]
I just ran into this today running a drizzle ORM generated migration:

```
  query: '\n' +
    'CREATE POLICY "owner can insert" ON "api"."project_history" AS PERMISSIVE FOR INSERT TO public USING (auth.uid() is not null);',
  params: [],
  cause: error: only WITH CHECK expression allowed for INSERT
```
