### ISSUE TITLE
Getting empty array instead of an error with RLS Policies

### ISSUE THREAD

**Issue by marcustut** [supabase/supabase#1730]
# Bug report

## Describe the bug

Let's say I have a listings table, and I enabled RLS (Row level security) on that table, when I fetch the endpoint at `https://<supabase_url>/rest/v1/listings`, I should get an error instead of empty array. This happens the same regardless of I'm using curl or the JS client library.

Something like this (taken from [Auth Deep Dive Part 3](https://supabase.io/docs/learn/auth-deep-dive/auth-policies))
![image](https://user-images.githubusercontent.com/59773847/119780309-3aa72280-befc-11eb-90de-3ddad210122f.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase
2. Create a new table
3. Enable RLS
4. Fetch the API Endpoint

## Expected behavior

A HTTP 403 error like the image above.

## Screenshots

**Before enabling RLS**
![image](https://user-images.githubusercontent.com/59773847/119780652-abe6d580-befc-11eb-8eb5-c348ff3564b7.png)

**After enabling RLS**
![image](https://user-images.githubusercontent.com/59773847/119780688-b6a16a80-befc-11eb-97ba-8a749c04b174.png)

## System information

- OS: Manjaro Linux
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

I used [dbmate](https://github.com/amacneil/dbmate) as a migration tool where I create the schema and enable RLS within the .sql file instead of using the UI in the dashboard.

**Comment by soedirgo** [comment]
Hi @marcustut, this is expected behavior. Think of RLS when retrieving the table as adding a `WHERE` clause to `SELECT * FROM listings` - by default no row passes through the RLS (no rows are "visible"), so no rows are returned.

The error from that video is when you do an `INSERT`, in this case an error is returned (it doesn't make sense to silently drop the inserts return an OK).

**Comment by soedirgo** [comment]
Yup! Though it's a bit different for `INSERT` and the updated values for `UPDATE` - the checks apply for the new/updated rows instead of rows already in the database.

**Comment by marcustut** [comment]
Okay, I think this issue can be closed now then. Thanks for the response! @soedirgo
