### ISSUE TITLE
RLS not showing in the header row of tables anymore

### ISSUE THREAD

**Issue by andwrobs** [supabase/supabase#17339]
Hi team Supabase,

What happened to the RLS tag in the header of tables to indicate that RLS policies were applied to that table? I found it very helpful to be able to view the table and then click the RLS policy directly from there, as opposed to the new UI update that has users go through Authentication -> Policies -> Click on RLS policy.

Also in the new flow:
- if you press back—the scroll state isn't preserved
- clicking the card takes you to the _table_, not the RLS policy.. so in the below screenshot "user" takes you to the user table and not the RLS policies I have associated with the user table. paired with non-preserved scroll state, that's a really annoying gotcha.
<img width="956" alt="Screenshot 2023-09-11 at 2 49 59 PM" src="https://github.com/supabase/supabase/assets/101012384/1d7162fa-1d3a-4193-977c-3fd38e1347a4">

  
All in all, I found these updates to cause the new GUI experience around RLS to feel clunkier and disjointed than what you had previously :(

---
P.S.
Excuse me if this isn't the correct way to file this sort of log, I really wasn't sure which bucket was best. I think it's a disjointed enough experience to constitute a UX bug (especially w.r.t. not preserved scroll state), but I'm happy to repost elsewhere if appropriate.

**Comment by saltcod** [comment]
Fixed, will go out tomorrow morning
https://github.com/supabase/supabase/pull/17278

Thanks for the report!

**Comment by andwrobs** [comment]
insane turnaround, very cool!

**Comment by andwrobs** [comment]
💚 keep cooking
