### ISSUE TITLE
GraphQL: cannot pass more than 100 arguments error

### ISSUE THREAD

**Issue by PhilippS93** [supabase/supabase#17332]
## Describe the bug

I am using quite big GraphQL queries, which query more than 50-60 fields directly and ~10 associated relationships. I have added an additional field and now, I get the GraphQL response "cannot pass more than 100 arguments ".

<img width="480" alt="image" src="https://github.com/supabase/supabase/assets/11447121/9147dd9f-eedb-4cf5-9f20-1467a7d6b4b1">

When I remove a random field, the query works again. It seems that in the background, the GraphQL query is deconstructed and an SQL query is build by using some DB functions which e.g. concat the string fields or constructing a json for the final query. One of these functions seem to not respect this edge case.

Maybe, thisis helpful: https://stackoverflow.com/questions/53376451/cannot-pass-more-than-100-arguments-to-a-function-to-json-build-object

Ihave worked around the issue by splitting my query into two parts like:

```
query MyQuery {
    my_tableCollection {
        edges {
            node {
                ...FragmentProject
            }
        }
    }
    # supabase does not allow to "cannot pass more than 100 arguments", so we have to split the call
   rest_of_queried_fields:  my_tableCollection {
        edges {
            node {
                profit_margins {
                    edges {
                        node {
                            ..OtherFragment
                        }
                    }
                }
            }
        }
    }

}
```

## To Reproduce

1) Create a table with many fields (~60 or more) and many relationships (~10 or more) to other tables (one to many).
2) query all fields in GraphQL
3) get the error

## Expected behavior

There should be no error 

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
I think this is a limitation rather than a bug but I am happy to be wrong here! Your workaround is perfectly valid, as is calling a  function within the database to handle this.
Closing for now but please comment if you think this is a bug that should have a fix implemented.
