### ISSUE TITLE
error[E103]: unhandled fallible assignment

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#17343]
✔ Container supabase-imgproxy               Created                                                                                               1.6s 
 ✔ Container supabase-vector                 Created                                                                                               1.6s 
 ✔ Container supabase-db                     Created                                                                                               0.0s 
 ✔ Container supabase-analytics              Created                                                                                               0.0s 
 ✔ Container supabase-kong                   Created                                                                                               0.0s 
 ✔ Container supabase-rest                   Created                                                                                               0.0s 
 ✔ Container supabase-edge-functions         Created                                                                                               0.0s 
 ✔ Container supabase-meta                   Created                                                                                               0.0s 
 ✔ Container realtime-dev.supabase-realtime  Created                                                                                               0.0s 
 ✔ Container supabase-studio                 Created                                                                                               0.0s 
 ✔ Container supabase-auth                   Created                                                                                               0.0s 
 ✔ Container supabase-storage                Created                                                                                               0.0s 
Attaching to realtime-dev.supabase-realtime, supabase-analytics, supabase-auth, supabase-db, supabase-edge-functions, supabase-imgproxy, supabase-kong, supabase-meta, supabase-rest, supabase-storage, supabase-studio, supabase-vector
supabase-vector                 | 2023-09-11T22:20:33.080717Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
supabase-vector                 | 2023-09-11T22:20:33.081051Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
supabase-vector                 | 2023-09-11T22:20:33.081156Z  INFO vector::app: Loading configs. paths=["etc/vector/vector.yml"]
supabase-vector                 | 2023-09-11T22:20:33.115612Z  WARN vector::config::loading: Transform "router._unmatched" has no consumers
supabase-vector                 | 2023-09-11T22:20:33.116111Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::sources::docker_logs: Capturing logs from now on. now=2023-09-11T22:20:33.116008237+00:00
supabase-vector                 | 2023-09-11T22:20:33.116268Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::sources::docker_logs: Listening to docker log events.
supabase-imgproxy               | WARNING [2023-09-11T22:20:33Z] No keys defined, so signature checking is disabled 
supabase-imgproxy               | WARNING [2023-09-11T22:20:33Z] No salts defined, so signature checking is disabled 
supabase-imgproxy               | WARNING [2023-09-11T22:20:33Z] Exposing root via IMGPROXY_LOCAL_FILESYSTEM_ROOT is unsafe 
supabase-imgproxy               | INFO    [2023-09-11T22:20:33Z] Starting server at :5001 
supabase-vector                 | 2023-09-11T22:20:33.336016Z ERROR vector::topology: Configuration error. error=Transform "db_logs": 
supabase-vector                 | error[E103]: unhandled fallible assignment
supabase-vector                 |    ┌─ :15:35
supabase-vector                 |    │
supabase-vector                 | 15 │ .metadata.parsed.error_severity = upcase(.metadata.parsed.error_severity)
supabase-vector                 |    │ --------------------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supabase-vector                 |    │ │                                 │
supabase-vector                 |    │ │                                 this expression is fallible
supabase-vector                 |    │ │                                 update the expression to be infallible
supabase-vector                 |    │ or change this to an infallible assignment:
supabase-vector                 |    │ .metadata.parsed.error_severity, err = upcase(.metadata.parsed.error_severity)
supabase-vector                 |    │
supabase-vector                 |    = see documentation about error handling at https://errors.vrl.dev/#handling
supabase-vector                 |    = learn more about error code 103 at https://errors.vrl.dev/103
supabase-vector                 |    = see language documentation at https://vrl.dev
supabase-vector                 |    = try your code in the VRL REPL, learn more at https://vrl.dev/examples
supabase-vector                 | 
supabase-vector exited with code 78
dependency failed to start: container supabase-vector exited (78)

**Comment by EnochT14** [comment]
I've got the same issue, followed the official installation guide for docker. Running Docker on ARM64, 
Ubuntu-22.04-Minimal-aarch64

**Comment by franzvezuli** [comment]
Same here.

On the latest master branch, at least as of hash [b5ec8cbdb22334fd308e6437be999b161957f74a](https://github.com/supabase/supabase/commit/b5ec8cbdb22334fd308e6437be999b161957f74a) (this is the HEAD hash at time of writing, not saying this is what introduced the issue), `docker compose up` seems broken.

even after stopping & removing all containers and deleting all images
```
docker stop $(docker ps -aq)  
docker rm -f $(docker ps -a -q)
 docker rmi $(docker images -a -q) -f
```

This is happening on a fresh pull of `master`.  In case you need logs, running on Fedora 38 x64:

```
 docker version                      
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:33:40 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by franzvezuli** [comment]
The issue seems to be introduced in this PR: https://github.com/supabase/supabase/pull/16717/files

Any hash before hand works just fine.

**Comment by jay-jjwu** [comment]
same here, any solution?

**Comment by EnochT14** [comment]
> same here, any solution?

I made a pull before that merge, works now. 

```
~$ git clone https://github.com/supabase/supabase
~$ cd supabase
~/supabase$ git checkout f55bad23907bea9a93a8793dd85f343aea915c1a
~/supabase$ git pull origin f55bad23907bea9a93a8793dd85f343aea915c1a
~/supabase$ cd docker
~/supabase/docker$ docker compose up -d
```

**Comment by jay-jjwu** [comment]
> > same here, any solution?
> 
> I made a pull before that merge, works now.
> 
> ```
> ~$ git clone https://github.com/supabase/supabase
> ~$ cd supabase
> ~/supabase$ git checkout f55bad23907bea9a93a8793dd85f343aea915c1a
> ~/supabase$ git pull origin f55bad23907bea9a93a8793dd85f343aea915c1a
> ~/supabase$ cd docker
> ~/supabase/docker$ docker compose up -d
> ```

Hi, thanks.
i tried and it did work when docker compose up via CLI bash.
But when i tried to add a new stack in potainer, it still shows the error, any idea?

Error message below --------
Deployment error
failed to deploy a stack: Network superbase_default Creating Network superbase_default Created Container supabase-imgproxy Creating Container supabase-vector Creating Container supabase-imgproxy Created Container supabase-vector Created Container supabase-db Creating Container supabase-db Created Container supabase-analytics Creating Container supabase-analytics Created Container supabase-edge-functions Creating Container realtime-dev.supabase-realtime Creating Container supabase-studio Creating Container supabase-meta Creating Container supabase-kong Creating Container supabase-auth Creating Container supabase-rest Creating Container supabase-edge-functions Created Container supabase-rest Created Container supabase-storage Creating Container supabase-kong Created Container supabase-studio Created Container supabase-meta Created Container realtime-dev.supabase-realtime Created Container supabase-auth Created Container supabase-storage Created Container supabase-imgproxy Starting Container supabase-vector Starting Container supabase-vector Started Container supabase-imgproxy Started Container supabase-vector Waiting Container supabase-vector Error dependency failed to start: container supabase-vector exited (78)
------

**Comment by jm-bh** [comment]
I got it to work by changing [/docker/volumes/logs/vector.yml, L156](https://github.com/supabase/supabase/blob/master/docker/volumes/logs/vector.yml#L156) to `.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)` (adding the `!`). 

See #17344

**Comment by jay-jjwu** [comment]
> Your Portainer stack is most likely pulling the latest image. What does your stack look like? @jay-jjwu

i think i was using the old tag images, because the docker-compose file are exactly copy-paste from the old pulling.

![image](https://github.com/supabase/supabase/assets/78014320/8e4a8b1b-9e0d-4346-a155-d9d6894b7f1a)
![image](https://github.com/supabase/supabase/assets/78014320/98c70fdc-97b1-4caa-8862-3f68b5a57e31)

**Comment by Ziinc** [comment]
This bug has since been fixed, please pull the latest changes with `git pull origin master` and all should be working as expected 🙇 
thanks again @jm-bh
