### ISSUE TITLE
502 error for edge function template from the Supabase dashboard

### ISSUE THREAD

**Issue by WebShapedBiz** [supabase/supabase#17355]
- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Stuck at 502 invocation error by simply following "terminal instructions" for edge functions from the Supabase dashboard.

## To Reproduce

I did as told...

> Create a function
$ supabase functions new hello-world 
> Deploy your function
$ supabase functions deploy hello-world --project-ref hciwxvlgvypfmxxkinfj 
> Invoke your function
$ curl -L -X POST 'https://hciwxvlgvypfmxxkinfj.supabase.co/functions/v1/hello-world' -H 'Authorization: Bearer [YOUR ANON KEY]' --data '{"name":"Functions"}' 

... replacing of course '[YOUR ANON KEY]' with my anon key and got:

1. In terminal:
```
502: Bad Gateway (ORIGIN_RPC_ERROR)

The subhoster origin returned a failure status for the boot RPC call. Status: 500 Internal Server Error
```
2. In Edge Functions dashboard -> Invocations:
```
"status_code": 502
```

3. In Edge Functions dashboard -> Logs - nothing

## System information

- OS: elementaryOS 6.1 based on Ubuntu 20.04.6 LTS
- Version of supabase CLI: 1.96.4
- Version of curl: 7.68.0

Thank you for your time and effort.

**Comment by TalMikey** [comment]
Happens to me too for all edge functions in my app. Might be region related. Waiting for Supabase team to response and resolve.

**Comment by dansomrack** [comment]
Were you able to get any support?

We are hitting the same issue on our Edge Functions but it is intermittent. No response from Supabase support after 5 days. We'll create another ticket.

**Comment by TalMikey** [comment]
Hi,
I did. There are some issues with edge functions but I don’t know the
relevance for this time. When I had this issue it was on the time Supabase
team changed the edge functions infrastructure.
Also, I had an issue with my dependencies file that one of the dependencies
(“axiod”) was deprecated and for some reason it failed to work with it.

Hope you will work this out,
Tal

On Thu, 26 Oct 2023 at 5:30 Dan Somrack ***@***.***> wrote:
Were you able to get any support?

**Comment by flogy** [comment]
This happens for me too from time to time. Most requests works but then suddenly one of them gets a 502... It is not clear to me why it happens, it seems to be an issue with the Supabase infrastructure to me. Did anyone get some feedback from support yet?

**Comment by KevinBrolly** [comment]
Hey @flogy @dansomrack - we were seeing some intermittent 502 errors and other networking related errors several months ago, when this issue was first created, as we were rolling out edge functions infrastructure changes. You should not be seeing appreciable intermittent 502 errors and if you still are I would encourage you to contact support as they can look more closely at the networking conditions on your particular instance/edge function while the problem is occurring.

I am going to close this issue as it is not reporting an actionable issue that we can solve, and is now quite stale. If I am mistaken please let us know and we can re-open this issue.
