### ISSUE TITLE
Nextjs example SSR doesnt work.

### ISSUE THREAD

**Issue by PaulRennerbs** [supabase/supabase#1735]
# Bug report

## Describe the bug
In the nextjs-supabase-auth example the SSR functionality doesn't work. I can't get it to work either.
In the API where the cookie is set there is just nothing set. If you log it is return null. The profile page will redirect you to login as well. The non SSR version works fine tho.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone repository
2. change env values
3. npm install & run
4. login
5. click SSR example

## Expected behavior
Set a cookie for SSR

## Additional context

I've been trying to get this to work for a straight week, and now I see that in the example it's not working either :/

**Comment by PaulRennerbs** [comment]
thanks

**Comment by i-pip** [comment]
Hi @PaulRennerbs

I'm attempting to reproduce this issue but it's working as expected on my side. just for clarity, am I looking at the right example ([nextjs-with-supabase-auth](https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth))? 

Here's an animated gif of my attempt at reproducing the issue: 

![nextjs-example-ssr](https://user-images.githubusercontent.com/15890505/120191527-54a57580-c21a-11eb-9f5c-daff78d023e0.gif)

**Comment by PaulRennerbs** [comment]
Yes exactly thanks for your effort. The issue occurs for me once i visit the /ssr page, the profile page works fine as its done with fetching the api on the clientside 


Again, thanks for your time.

**Comment by i-pip** [comment]
Hoping this might help, 

I created a nextjs project from scratch following the [Supabase Next.js Quickstart](https://supabase.io/docs/guides/with-nextjs) and here's what I found: 

After walking through the guide, I added a server-rendered page (called mine profile but could have been anything really). 

Added 
```javascript 
const { user } = await supabase.auth.api.getUserByCookie(req);
``` 
in the `getServerSideProps` function of this page (profile), but this page didn't work - just redirected to '/' (expected behavior).

Next I added _auth_ api route (_pages/api/auth.js_) with only these contents: 

```javascript
import { supabase } from "../../utils/supabaseClient";

export default function handler(req, res) {
  supabase.auth.api.setAuthCookie(req, res);
}
``` 

and called this api endpoint posting the authStateChange event and session as the json body from _pages/index.js_ - the key method here being: 

```javascript
supabase.auth.onAuthStateChange((event, session) => {
      setSession(session);
      fetch("/api/auth", {
        method: "POST",
        headers: new Headers({ "Content-Type": "application/json" }),
        credentials: "same-origin",
        body: JSON.stringify({ event, session }),
      }).then((res) => res.json());
    });  
```

With this done, I could get the session in my profile page's `getServerSideProps` 

[I created a repo with these bare minimum config here](https://github.com/i-pip/supabase-nextjs-ssr-example)

**Comment by kiwicopple** [comment]
This is great @i-pip - I think I might even add this as an note inside the Next.js example. Thanks a lot!

**Comment by i-pip** [comment]
> This is great @i-pip - I think I might even add this as an note inside the Next.js example. Thanks a lot!

Thanks @kiwicopple, happy to help. @PaulRennerbs, hopefully the above helps

**Comment by PaulRennerbs** [comment]
Appreciate that 👍

**Comment by carlosstenzel** [comment]
If you want you can look at my example

https://github.com/carlosstenzel/nextjs-auth-tailwind

**Comment by monsieurBoutte** [comment]
SSO is still busted atm for `getServerSideProps` w/r/t SSR gated pages
```js
React.useEffect(() => {
    const { data: authListener } = supabase.auth.onAuthStateChange(
      (event, session) => {
        fetch('/api/auth', {
          method: 'POST',
          headers: new Headers({ 'Content-Type': 'application/json' }),
          credentials: 'same-origin',
          body: JSON.stringify({ event, session }),
        }).then(res => res.json())
      }
    )
    return () => {
      authListener?.unsubscribe()
    }
  }, [])
```

gated page
```ts
export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const data = await supabase.auth.api.getUserByCookie(req)

  if (!data.user) {
    // If no user, redirect to sign-in.
    return {
      props: {},
      redirect: { destination: '/member/sign-in' },
    }
  }

  // If there is a user, return it.
  return { props: { user: data.user } }
}

export default DashboardPage
```

the sign-in code
```ts
  const handleSso = async (provider: SupportedProvider) => {
    try {
      await supabase.auth.signIn(
        {
          provider,
        },
        {
          redirectTo: 'http://localhost:3000/member/dashboard',
        }
      )
    } catch (error) {
      console.error(error)
    }
  }
```

regular sign-in flow with email and password work just fine. But with SSO, here's the weird thing — the user has to log in twice. 
1. The first time the user does SSO (the cookie gets set)
2. But on the first time, SSR (getServerSideProps) doesn't see the cookie in the header
3. On the next sign-in attempt, the cookie is already set and there for the `redirectTo: 'http://localhost:3000/member/dashboard',` is successful

Any thoughts on how I might fix this so that the sign-in flow behaves as expected for SSO and there's not this double attempt workaround?

**Comment by wottpal** [comment]
(First, I think https://github.com/supabase/supabase/issues/347 is related.)

I have the same problem @monsieurBoutte described. Even though you can circumvent it by listening on `onAuthStateChange` and push a new route when a `SIGN_IN` event occurs. But this still feels like a "workaround" and not an ideal solution. I want to redirect directly to my protected, server-side rendered profile/dashboard page – without detours.

One idea I had (but got stuck during execution) was redirecting to an API route instead of a Next.js-page. And on that route, you (1.) set the auth cookie and (2.) redirect to the protected page of your choice. This might be even possible today, I just don't know how to create the `event` & `session` objects on the server-side without the help of `onAuthStateChange`...

Supabase Sign-In Callback (server-side):
```ts
import { NextApiRequest, NextApiResponse } from 'next'
import { supabase } from '../../../shared/supabase_client'

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  // TODO Create event and session objects
  supabase.auth.api.setAuthCookie(req, res)
  // TODO Somehow pass the event down to the client (maybe just pass the exact same URL parameters as received (refresh_token, access_token, token_type)?
  res.redirect('/dashboard')
}
```

Any ideas? Am I getting something completely wrong here?

**Comment by wottpal** [comment]
Update: I was very close to getting it to work (see attached example) but unfortunately supabase attaches the sign in-callback parameters with an `#` and not with an `&` (I could only extra the latter with my server example, I even try the dynamic next.js routing to catch-all parameters, but it didn't work out).

```ts
import { Session } from '@supabase/supabase-js'
import Cookies from 'cookies'
import { NextApiRequest, NextApiResponse } from 'next'
import { supabase } from '../../../../shared/supabase_client'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { user_auth: slug } = req.query
  const path = (slug as string[] || []).join('/')

  switch (path) {
    case 'callback':
      return await handleSupabaseCallback(req, res)
    default:
      return res.status(404).end()
  }
}


export const handleSupabaseCallback = async (req: NextApiRequest, res: NextApiResponse) => {
  const url = req?.url || ''
  if (!url) console.error("NO URL")

  const url_params = ' :( '

  const session = await getSessionFromUrl(url)
  const cookies = new Cookies(req, res)
  cookies.set(
    'sb:token',
    session.access_token,
    {
      maxAge: 60 * 60 * 8 * 1000,
      sameSite: 'lax',
      httpOnly: false,
    })

  return res.redirect(`/dashboard${url_params}`).end()

}


export function getParameterByName(name: string, url?: string) {
  if (!url) url = window.location.href
  name = name.replace(/[\[\]]/g, '\\$&')
  var regex = new RegExp('[?&#]' + name + '(=([^&#]*)|&|#|$)'),
    results = regex.exec(url)
  if (!results) return null
  if (!results[2]) return ''
  return decodeURIComponent(results[2].replace(/\+/g, ' '))
}


export async function getSessionFromUrl(url: string): Promise<Session> {
  const error_description = getParameterByName('error_description', url)
  if (error_description) throw new Error(error_description)

  const provider_token = getParameterByName('provider_token', url)
  const access_token = getParameterByName('access_token', url)
  if (!access_token) throw new Error('No access_token detected.')
  const expires_in = getParameterByName('expires_in', url)
  if (!expires_in) throw new Error('No expires_in detected.')
  const refresh_token = getParameterByName('refresh_token', url)
  if (!refresh_token) throw new Error('No refresh_token detected.')
  const token_type = getParameterByName('token_type', url)
  if (!token_type) throw new Error('No token_type detected.')

  const timeNow = Math.round(Date.now() / 1000)
  const expires_at = timeNow + parseInt(expires_in)

  const { user, error } = await supabase.auth.api.getUser(access_token)
  if (error) throw error

  return {
    provider_token,
    access_token,
    expires_in: parseInt(expires_in),
    expires_at,
    refresh_token,
    token_type,
    user: user!,
  } as Session
}
```

**Comment by joshua-isaac** [comment]
any update on this? having a blast using supabase so far but this is holdin' me back :(

**Comment by ruucm** [comment]
Here is my finding for who wants to access the RLS table on serverside in Nextjs.

1. Call Auth API with `supabase.auth.onAuthStateChange`
```typescript
export default function PricingPage({ products }) {
  useEffect(() => {
    const { data: authListener } = supabase.auth.onAuthStateChange(
      (event, session) => {

        console.log('session', session)
        fetch('/api/auth', {
          method: 'POST',
          headers: new Headers({ 'Content-Type': 'application/json' }),
          credentials: 'same-origin',
          body: JSON.stringify({ event, session })
        }).then((res) => res.json())
      }
    )

    return () => {
      authListener.unsubscribe()
    }
  }, [])

  return <Pricing products={products} />
}
```


2. Save Cookies.

```typescript
import { supabase } from '@/utils/supabase-client'

export default function handler(req, res) {
  supabase.auth.api.setAuthCookie(req, res)
}

```


3. Using it with access_token. (It finally allows you to read RLS tables.)

```typescript
export async function getServerSideProps({ req }) {
  // @ts-ignore
  supabase.auth.session = () => ({
    access_token: req.cookies['sb:token']
  })

  const { data, error } = await supabase.from('products').select('*')
  return {
    props: {
      products: data || []
    }
  }
}

```

**Comment by joaogarin** [comment]
Even adding these lines to set te session with the existing token for me requests inside an API route to a protected table does not seem to work.

It looks uid() is not really getting picked up correctly (which I guess corresponds to something not corectly set in terms of token). I can get the current user like this : 

`  const { user } = await supabase.auth.api.getUserByCookie(req);`this works fine but then doing a request to a table does not yield any result. on the client it works fine.

Same thing happens inside a getServerSideProps. I have also the same code in `onAuthStateChange` setting the token against the /api/auth

any ideas? is the previous comment working for other people?

Thanks in advance,

**Comment by revskill10** [comment]
Same issue. What's the solution without hack setCookie ?

**Comment by wottpal** [comment]
Is there a (working) boilerplate solution with the new nextjs 12 middlewares planned? This should be an extra ticket, I guess?

**Comment by johnhforrest** [comment]
The `session` patch that @ruucm provided works great for me. RLS protected tables don't work without it.

**Comment by HarryPeach** [comment]
Also experiencing this error, and nothing except including @ruucm's session hack *before* the select request worked for me.

**Comment by wottpal** [comment]
FYI @kiwicopple this issue is more than half a year old and still a hack is needed as a workaround. Would you please prioritize the integration of that into the supabase core? Maybe as a little Christmas surprise ❤️🎄😛

**Comment by kiwicopple** [comment]
> session hack before the select

There is an official method to support this: https://github.com/supabase/gotrue-js/pull/80/files#diff-3522461172efd6058d6b8da62fc2d30d8b524d2b64894ea2c67218c52f7fdff5R258

eg:

```js
supabase.auth.setSession(refresh_token)
```

Does that work? 

> Maybe as a little Christmas surprise 

😄  I'll see what we can do but tbh the team are crazy busy with our migration from Auth0 and an ongoing pentest before xmas. We definitely need to do a spring clean of all the old issues - I'll make this a task when everyone is back from their holidays

**Comment by brunoalano** [comment]
Any updates on this @kiwicopple?

**Comment by thorwebdev** [comment]
Hey all, some good news, we've released a new helpers library that provides a more robust auth strategy for Nextjs: https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md

Would love for you all to test it out and let us know if that resolves the above mentioned issues for you. 

The [`nextjs-with-supabase-auth` example](https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth) has been updated to use it, and also https://github.com/vercel/nextjs-subscription-payments/pull/101

Hope this is helpful. Please also watch this library as we're working to included the same functionality for Nuxt, Remix, and Sveltekit 👍
