### ISSUE TITLE
WebApp-Tutorial with SvelteKit: Couple of issues that need to be improved

### ISSUE THREAD

**Issue by Blackwidow-sudo** [supabase/supabase#17375]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit

## Describe the problem

There are multiple issues in the code examples, which can be confusing (especially for new users).

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#supabase-auth-helpers
- tells you to install `@supabase/supabase-js` again. Which you just did 2 steps before.
- `+layout.server.ts` code has no type for load function (Inconsistent with other code snippets)
- `+layout.ts` code imports `invalidate` for no reason. Also no type for the load function.
- `+layout.svelte` code has this weird snippet:
```svelte
<script lang="ts">
  // ...
  let { supabase, session } = data
  $: ({ supabase, session} = data )
  // ...
</script>
```

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#set-up-a-login-page
- `src/routes/+page.svelte` code gives a type error `Property 'additionalData' is missing in type '{ supabaseClient: SupabaseClient<any, "public", any>`
- `src/routes/auth/callback/+server.ts` is missing type

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#account-page
- `src/routes/account/+page.svelte` doesn't import `SubmitFunction` type correctly. Also has this weird double declaration of `{ session, supabase, profile } = data` like the one in `+layout.svelte`
- `src/routes/account/+page.server.ts` is missing type for load & actions.

## Describe the improvement

Correct the described issues in the docs.

## Additional context

Supabase has changed since i used it. So i wanted to get a refresher with the WebApp-Tutorial. But my experience with the docs was not that great.

**Comment by Blackwidow-sudo** [comment]
Update:
The type error from the `<Auth />` component i mentioned, seems like an issue from the `@supabase/auth-ui-svelte` package.
The `Auth.svelte.d.ts` file from the dist folder doesn't have `additionalData` as a optional prop. But looking at the type declarations on [@supabase/auth-ui-shared](https://github.com/supabase/auth-ui/blob/main/packages/shared/src/types.ts) it should be optional.

**Comment by Psypher1** [comment]
And I thought I was the one doing something wrong... Thank you for this.

**Comment by Blackwidow-sudo** [comment]
> And I thought I was the one doing something wrong... Thank you for this.

If you're talking about the type error:
I just saw that there was already a PR made here https://github.com/supabase/auth-ui/pull/217.
Hopefully it will get merged soon.

**Comment by ZetiMente** [comment]
This would be very helpful.

**Comment by silentworks** [comment]
I've just merged a PR for this and it will be available on the next patch release shortly.

**Comment by GaryAustin1** [comment]
PR generated so this can be closed.
