### ISSUE TITLE
Custom Domain Configuration Not Reflecting on Docker Self-Hosted Environment

### ISSUE THREAD

**Issue by nicetomytyuk** [supabase/supabase#17418]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Currently, configuring a custom domain on a Docker self-hosted environment proves to be unfeasible. Despite modifying the parameters within the .env file, the studio and REST API remain exclusively accessible via http://<your.ip>:8000/.

## To Reproduce

1. Initialize a new self-hosted project on Docker.
2. Attempt to configure a custom domain for both the studio and REST API calls. To do this, update the respective values in the .env file to your custom domain as illustrated below:  `SITE_URL=https://example.com/ SUPABASE_PUBLIC_URL=https://example.com/ API_EXTERNAL_URL=https://example.com/`
3. Restart the compose.

## Expected behavior

Following the adjustments in the .env file, the anticipation is that the studio and REST API will be reachable through the newly configured custom domain. Consequently, accessing https://example.com/ should display the Supabase studio interface. Moreover, executing any request to https://example.com/rest/v1 ought allow the REST calls.

**Comment by nicetomytyuk** [comment]
For a temporary solution I've been able to set a custom domain by using the Caddy reverse-proxy.

To do so, ensure to have Caddy installed on your server and then just run the following command by replacing `example.com`  with your domain.

`caddy reverse-proxy --from example.com --to localhost:8000`

**Comment by encima** [comment]
Thank you for reporting!

I will close this as you have provided a workaround. Due to the self-hosted nature, Supabase does not make changes to the DNS of your system so these changes would need to be made manually (either through Caddy, nginx etc or by modifying your `/etc/hosts` file)
