### ISSUE TITLE
Different results from SQL query and PostgREST

### ISSUE THREAD

**Issue by marcustut** [supabase/supabase#1743]
# Bug report

## Describe the bug

I wrote a function for using it in policies but the function is not behaving correctly, hence failing policies. Further debugging shows that when I test the function in Supabase's SQL Query editor returns `true` whereas when I do it over the REST api it returns `false`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to SQL Query Editor
2. Write a function
3. Execute it at the editor and from curl

## Expected behavior

Both returns `true`

## Screenshots

**The sql function**
```sql
create or replace function public.brands_have_user(uid uuid) returns boolean as $$
  declare
    num integer;
  begin
    select COUNT(brand_id) into num from brands where user_id = uid;

    if num = 0 then
      return false;
    else
      return true;
    end if;
  end
$$ language plpgsql;
```

**Executing the function at Supabase's SQL Query Editor**
![image](https://user-images.githubusercontent.com/59773847/119933904-89fe5900-bfb7-11eb-9e99-6632379c4871.png)

**Executing the function over REST**
![image](https://user-images.githubusercontent.com/59773847/119933985-ac907200-bfb7-11eb-832f-a6c69fe98908.png)

## System information

- OS: Manjaro Linux
- Browser Chrome 90
- Version of Node.js: 16.1.0

## Additional context

I then re-written the function to further test it
```sql
create or replace function public.brands_have_user(uid uuid) returns integer as $$
  declare
    num integer;
  begin
    select COUNT(brand_id) into num from brands where user_id = uid;

    -- if num = 0 then
    --   return false;
    -- else
    --   return true;
    -- end if;
    return num;
  end
$$ language plpgsql;
```

The result is still same, where postgREST is not returning the accurate result.

**Executing the function from Supabase's SQL Query Editor**
![image](https://user-images.githubusercontent.com/59773847/119934256-16a91700-bfb8-11eb-99dc-1743a883c575.png)

**Executing the function from REST**
![image](https://user-images.githubusercontent.com/59773847/119934129-e6fa0f00-bfb7-11eb-9658-d53b3aefdce7.png)

**Comment by steve-chavez** [comment]
@marcustut Does the `brands` table have RLS policies applied?

**Comment by marcustut** [comment]
> @marcustut Does the `brands` table have RLS policies applied?

Yes, the brands table has RLS policies applied.

![image](https://user-images.githubusercontent.com/59773847/120059128-fd6c9d00-c081-11eb-9784-5f26381367ae.png)

these are the policies applied to the `brands` table but will these policies affect the results to be different through posgREST though?

**Comment by kiwicopple** [comment]
Hey @marcustut - yes, these policies are applied whenever a request is made through your API. If you need to elevate priveleges for your function you can also use `security definer` when creating your [function](https://www.postgresql.org/docs/9.5/sql-createfunction.html) - (rather than the default `security invoker`)

> [EXTERNAL] SECURITY INVOKER
> [EXTERNAL] SECURITY DEFINER
>
>    SECURITY INVOKER indicates that the function is to be executed with the privileges of the user that calls it. That is the default. SECURITY DEFINER specifies that the function is to be executed with the privileges of the user that created it.

I'll close this for now but feel free to comment if you have any other problems and we can reopen!

**Comment by steve-chavez** [comment]
> these are the policies applied to the brands table but will these policies affect the results to be different through posgREST though?

@marcustut Yes, because the admin dashboard runs with a highly privileged user while postgREST runs with the role defined in your JWT; if no role is defined here, it will default to the **anon**(anonymous) role, which might not pass your RLS policies.
