### ISSUE TITLE
width of search card in docs needs to fixed on the mobile view

### ISSUE THREAD

**Issue by AbhijeetBiswal** [supabase/supabase#17437]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

when we write a long query on the search card in the docs on the mobile view the width of the card increases and goes out of the screen.

https://github.com/supabase/supabase/assets/144774379/055a6303-b7ab-4779-8530-b04073820e3b

## Expected behavior

The width of the search card should not go out of the screen when we write a long query in the input.

**Comment by nwaliaez** [comment]
I believe it's not extending beyond the screen; instead, it's matching the screen width.

**Comment by AbhijeetBiswal** [comment]
yes you are right but if we have some space from right and left it will look more align. i have fixed this issue in the above PR. in which i have added a max width to the card which makes the card more align.
