### ISSUE TITLE
"containsBy()" (`cd`) always returns empty array

### ISSUE THREAD

**Issue by ChuckJonas** [supabase/supabase#17438]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When executing a `containsBy()` filter (`cd`), rows with empty arrays are returned.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table (`example`) with a `text[]` field (`tags`)
2. Populate 1 row with a value of `starred` in `tags`
3. Populate another row with a empty array `[]` in `tags`
4. Run the following `superbasejs` query or api query

```ts
await supabase.from('example').containsBy('tags', ['starred']).select('*');
```

```
select=*&tags=cd.%7Bstarred%7D&order=last_update_at.desc
```

## Expected behavior

Only the row with the value of `starred` should show up in tags

## Screenshots

<img width="572" alt="Vite___React___TS" src="https://github.com/supabase/supabase/assets/5217568/70021577-4f6d-4ff2-86f9-90684ec4de96">

<img width="868" alt="Vite___React___TS" src="https://github.com/supabase/supabase/assets/5217568/b7bc8a5b-cf1c-4bf5-bc41-be2006e8b609">

## System information

- OS: macOS
- Version of supabase-js: 1.93.0

**Comment by GaryAustin1** [comment]
`containsBy` is not a valid filter and should error in the JS client.  `containedBy` is the filter name.

In your URL stuff, you show a good URL, but in the request seems to put everything in payload.  The filters and select info is part of the URL itself and not payload for a get.  Not sure what you are up to there.

**Comment by GaryAustin1** [comment]
Sorry on 2nd part.  I now see it was query parameters you sent.

**Comment by GaryAustin1** [comment]
Finally, that is the way contained by `<@` works in Postgres for empty arrays.   There was a 4th row that contained ["cat"] that was excluded.

![image](https://github.com/supabase/supabase/assets/54564956/afdf80c8-e7f5-4025-8838-2396553a9240)

Shows doing the SQL directly.

**Comment by GaryAustin1** [comment]
Add this extra filter to your query:  `.neq('tags','{}'`
