### ISSUE TITLE
onAuthStateChange() does or does not work across tabs?

### ISSUE THREAD

**Issue by kjhughes** [supabase/supabase#17449]
# Improve documentation

## Link 

The [Auth: Listen to auth events](https://supabase.com/docs/reference/javascript/auth-onauthstatechange
) documentation says:

> Currently, onAuthStateChange() does not work across tabs. For instance, in the case of a password reset flow, the original tab which requested for the password reset link will not receive the SIGNED_IN and PASSWORD_RECOVERY event when the user clicks on the link.

## Describe the problem

On the other hand,  [issue](https://github.com/supabase/auth-helpers/issues/65) [history](https://github.com/supabase/supabase/issues/2739) appears to end with [resolution](https://github.com/supabase/gotrue-js/pull/184).

**Is there another unresolved issue, or is the documentation out-of-date?**

## Describe the improvement

Remove the noted limitation, or link to the live issue so that it's clear whether the issue remains unresolved.

**Comment by Hallidayo** [comment]
Hi @kjhughes - It seems that the docs have been updated for this so going to close but thank you for opening the issue.
