### ISSUE TITLE
Dashboard table editor empty message is dark-on-dark

### ISSUE THREAD

**Issue by gregnr** [supabase/supabase#17446]
# Bug report

## Describe the bug

When dark mode is enabled in the studio dashboard and you navigate to an empty table, the text "This table is empty" is dark-on-dark:

![image](https://github.com/supabase/supabase/assets/4133076/8162334a-1b6f-4fe2-bdcc-346b95356456)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Login to the dashboard
2. Navigate to the [table editor](https://supabase.com/dashboard/project/_/editor) and create a new empty table
3. Select the new empty table
4. Empty table message appears

## Task
Fix this so that the top text is light-on-dark.

**Comment by imsoumya18** [comment]
@gregnr I want to work on this. Can you please assign me

**Comment by imsoumya18** [comment]
while building locally, I am getting this error
![fetch](https://github.com/supabase/supabase/assets/50456734/74f52d4e-b8d0-41db-aa41-75c500ea81af)

**Comment by imsoumya18** [comment]
please close this issue, it's already fixed IG

**Comment by gregnr** [comment]
Hey @imsoumya18! I'm still seeing this in production - was this fixed recently in a PR? Mind sharing the link?

**Comment by HarshDeswal** [comment]
Yes, the bug is still there in production.
![image](https://github.com/supabase/supabase/assets/94471009/588e1e93-eadb-4d75-887d-f59d46598f77)

**Comment by imsoumya18** [comment]
I am not facing the issue
![image](https://github.com/supabase/supabase/assets/50456734/bcd64c3b-93d5-4796-838e-44f77607fbd2)

**Comment by devesh711** [comment]
yes its working fine can you specify your environment details -

**Comment by devesh711** [comment]
yes its working fine can you specify your environment details -
![image](https://github.com/supabase/supabase/assets/113835041/aa3dbbe6-aa3a-482d-b152-2607ec1b02df)

**Comment by natedevxyz** [comment]
I'm using the table editor right now and it's still there:

![image](https://github.com/supabase/supabase/assets/100222439/1e07d14c-bd4a-47d8-9cc9-d5ffbb89645b)
![image](https://github.com/supabase/supabase/assets/100222439/32a9c70b-6527-48dd-abad-c5bc82167990)

**Comment by devesh711** [comment]
hey @natedevxyz can you specify your environment details such as -
which browser are you using ?
which os ?

**Comment by natedevxyz** [comment]
> hey @natedevxyz can you specify your environment details such as - which browser are you using ? which os ?

Chrome Version 116.0.5845.188 (Official Build) (64-bit)
Windows 11 Version 22H2

**Comment by pragyamishra56** [comment]
@gregnr Sir could assign me this issue it would be my first contribution

**Comment by botxboom** [comment]
Hi @natedevxyz, can you confirm the theme of your chrome browser. 
As I have investigated, it is **working fine** If your browser's theme is in **dark mode**. I suppose you are facing this issue because of Light theme of your browser.

**Comment by ratnaraj7** [comment]
this issue is fixed here #17521

**Comment by gregnr** [comment]
Closed via https://github.com/supabase/supabase/pull/17521
