### ISSUE TITLE
Delete table failed from dashboard

### ISSUE THREAD

**Issue by chhpt** [supabase/supabase#1744]
# Bug report

## Describe the bug

When i try to delete a table from app.supabase.io project dashboard, it display the error:

Deleting table failed: column "nan" does not exist

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to project database tab
2. Click on delete table icon

## Expected behavior

Delete table success

## Screenshots

![Xnip2021-05-28_15-10-01](https://user-images.githubusercontent.com/19288423/119944386-102f8680-bf49-11eb-93ec-b84a3365ecb2.jpg)

**Comment by awalias** [comment]
hey @chhpt thanks for the report will check it out, thanks for reporting

do you know does this table have a primary key?

**Comment by chhpt** [comment]
@awalias Yes, it has a uuid primary key

**Comment by phamhieu** [comment]
The issue should be fixed now. @chhpt let us know if you still face the issue
