### ISSUE TITLE
Update `supabase/postgres` image in `docker-compose.yml`

### ISSUE THREAD

**Issue by marbor3** [supabase/supabase#17465]
# Chore

Update `supabase/postgres` image in `docker-compose.yml`

## Describe the chore

When running dev service it runs on `supabase/postgres:15.1.0.117`
While using `Supabase CLI` locally I'm getting `supabase/postgres:15.1.0.103`

that wouldn't be a huge issue but there's seems to be an issue with some postgres stuff that has been fixed somewhere between 103 that we have locally and 117 on dev.

Could we also have 117 here?

## Additional context

original issue: https://github.com/PostgREST/postgrest/issues/2881
supabase/postgres fix: https://github.com/supabase/postgres/pull/720
issue I'm observing: https://github.com/supabase/postgrest-js/issues/453
Discussion about updating images process: https://github.com/orgs/supabase/discussions/17074

**Comment by tranhoangvuit** [comment]
Hi @marbor3 , could you please recheck the `Supabase CLI` again? on my local it's `postgres:15.1.0.117`

<img width="846" alt="image" src="https://github.com/supabase/supabase/assets/21276822/f320ebef-dc7a-49ba-b105-4f53fde88aa1">

**Comment by marbor3** [comment]
Hello @tranhoangvuit Just checked, 117 also on my local!

Thank you
