### ISSUE TITLE
Does supabase js bulk upsert work when mixing inserts and updates with different formats?

### ISSUE THREAD

**Issue by sangonzal** [supabase/supabase#17473]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a table with the following columns:
id (PK), has default value
created_at, has default value
updated_at, has default value
worksite_task
name
description
number

I'm bulk upserting multiple values into this table via the supabase js SDK:

```
const updatedTasks = []; // this array contains multiple objects
 const { error: insertCheckpointErrors } =
            await supabaseClientComponentClient
                .from('inspection_checkpoints')
                .upsert(updatedTasks);
        if (insertCheckpointErrors) {
            throw insertCheckpointErrors;
        }
```

This works fine when:
All rows are being updated, and contain values for a required columns
Ex:
* created_at: "2023-09-13T20:18:05.120152+00:00"
* description: "Fifth"
* id: "f8061f65-a89e-4635-9a73-1cdeaa2716b6"
* name: "Checkpoint 5"
* number: 5
* updated_at: "2023-09-13T20:18:05.120152+00:00"
* worksite_task_id: "3e27fa51-fbc4-4f4b-b175-f46a5721957a

All rows being in inserted, when they don't contain columns with default values.
Ex:
* description: "Last endpoint"
* name: "Last"
* number: 4
* worksite_task_id: "3e27fa51-fbc4-4f4b-b175-f46a5721957a"

However, when I mix rows that are being inserted for the first time and rows that are being updated in the same upsert operation, I get the following error:

{
"code": "23502",
"details": "Failing row contains (null, null, null, 3e27fa51-fbc4-4f4b-b175-f46a5721957a, Last, Last endpoint, null, null, null, null, 4, null).",
"hint": null,
"message": "null value in column "id" of relation "inspection_checkpoints" violates not-null constraint"
}

I would expect that upsert would allow you to mix both, and reading postgres documentation my understanding is that it's allowed, but I wasn't able to find any information about whether this is supported in supabase. Is this expected?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1) Create a table with several columns with default values. 
2) Insert multiple rows
3) Bulk upsert multiple rows that: 
- Include new rows without columns that have default values
- Include updates to rows already present in the table

## Expected behavior
New rows are inserted, rows that are already present are updated.

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: ^2.33.1
- Version of Node.js: v19.7.0

**Comment by GaryAustin1** [comment]
![image](https://github.com/supabase/supabase/assets/54564956/2056fc6f-5baf-45c2-be01-ed5b548d34a7)

**Comment by GaryAustin1** [comment]
https://github.com/PostgREST/postgrest/issues/1118

**Comment by saltcod** [comment]
Going to mark this one as closed as it looks like Gary's answered the question.
