### ISSUE TITLE
supabse-vector Fails to Start w/Docker Compose

### ISSUE THREAD

**Issue by collier-watkins** [supabase/supabase#17478]
# Bug report

![image](https://github.com/supabase/supabase/assets/28796133/9bd981b6-d5b7-4ecf-8329-45db17c53986)

Tried pulling the master branch and running `docker compose up -d` with the example environment variables, docker couldn't start `supabase-vector` for this reason. I see some PRs went in recently in this area @Ziinc so just wanted to let y'all know. Thanks so much.

I'm running this with `docker compose up -d` on a pretty standard Ubuntu 20.04 LTS install, FYI

**Comment by ArseniyX** [comment]
happening to me as well
<img width="533" alt="image" src="https://github.com/supabase/supabase/assets/41956571/24a9f7ec-f336-4d52-971b-717d3e203fe7">

**Comment by Ziinc** [comment]
This has been fixed in https://github.com/supabase/supabase/pull/17344#pullrequestreview-1630590778

**Comment by markbara-git** [comment]
> @Ziinc pulling latest changes did't fix the issue with docker-compose -up:

![Screenshot 2023-09-18 135043](https://user-images.githubusercontent.com/83405406/268637764-eb199e16-04cb-4266-a5ad-ff6cb0beea6f.png)
