### ISSUE TITLE
"Enforce JWT Verification" re-enabled on deploy

### ISSUE THREAD

**Issue by davidchalifoux** [supabase/supabase#17476]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When redeploying a function, `Enforce JWT Verification` is automatically set to `true` even if it was previously set to `false`.

## To Reproduce

1. Deploy function
2. Set `Enforce JWT Verification` to `false` in the dashboard
3. Re-deploy function
4. See that `Enforce JWT Verification` is set to `true`

## Expected behavior

This configuration should not be changed after a re-deploy.

## System information

- OS: macOS
- Version of Supabase CLI: 1.93.0

**Comment by joshenlim** [comment]
This is likely on edge functions when deploying, not dashboard - removing dashboard tag

**Comment by sweatybridge** [comment]
Hello @davidchalifoux, our recommendation is to specify each edge function's verify jwt flag via `supabase/config.toml` and commit the file to git. https://supabase.com/docs/guides/cli/config#edge-functions-config

This ensures a single source of truth for function config changes. It is especially useful keeping the state in sync between multiple projects (staging, prod, etc) or multiple developers in a team.

**Comment by sweatybridge** [comment]
Feel free to reopen this issue if the above suggestion doesn't work for your use case.

**Comment by pricejordan41** [comment]
Hello, was anyone able to figure out a solution to this? I am running into the same issue with JWT keys being re-enabled even when config is set to false.. Driving me up a wall 🙃

**Comment by kallebysantos** [comment]
Hey @pricejordan41 💚
I do recommend to define it at your `config.toml` file, this way it won't affect your next deployments.

**Comment by aantti** [comment]
https://supabase.com/docs/guides/functions/function-configuration#skipping-authorization-checks 🤔

**Comment by pricejordan41** [comment]
Thanks for the quick reply! I do have these defined in each of my function config.toml files as False - but I can’t place within the main supabase function config file as it returns that its not a valid key for the main supabase config.toml. 

I confirmed these are individually set within each config.toml file still. Im seeing this is a wide issue from online searching with the verify JWT being reapplied upon deployments. 

The only way I can get this to not update is to include this in my deployment command - "supabase functions deploy export-user-data --no-verify-jwt" - but worried I will forget to do this on future deployments and won’t catch it auto turned on until Ive got someone complaining of a bug lol. So, there is NO way to define this as a global setting or anything to stop this from happening? 

Thanks,
JP

**Comment by pricejordan41** [comment]
> https://supabase.com/docs/guides/functions/function-configuration#skipping-authorization-checks 🤔

Thanks so much! I did check this out, and this is my current work around to deploying without them reapplying - but was wondering if this was something that has been implemented into config.toml files etc so I don't have to remember to apply the no force command..

**Comment by kallebysantos** [comment]
> but I can’t place within the main supabase function config file as it returns that its not a valid key for the main supabase config.toml

Please double check if your config file is matching the same as [from docs](https://supabase.com/docs/guides/functions/function-configuration#skipping-authorization-checks).
If possible can you share an example snippet with your current config?

It must be defined like:
```toml
[functions.stripe-webhook]
verify_jwt = false
```

**Comment by pricejordan41** [comment]
This worked! But had to be placed at the very bottom of my main config.toml file - was able to deploy without it overriding the JWT settings turning back ON in supabase dashboard. 

Thanks for the super quick turnarounds here - very appreciative!
