### ISSUE TITLE
An error has occurred: Failed to fetch

### ISSUE THREAD

**Issue by ashusnapx** [supabase/supabase#17487]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

A clear and concise description of what the bug is while creating a table, a toast notification comes with text written as "An error has occurred: Failed to fetch"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Create a new table under public'
2. Click on 'Save'
3. Scroll down to ''
4. See error "An error has occurred: Failed to fetch"

## Expected behavior

A clear and concise description of what you expected to happen is a table created with mentioned rows and columns

## System information

- OS: [macOS]
- Browser (if applies) [chrome]
- Version of supabase-js: 2.33.2
- Version of Node.js: 20.6.1

**Comment by GaryAustin1** [comment]
Might be this: https://github.com/orgs/supabase/discussions/17296

**Comment by ashusnapx** [comment]
> Might be this: https://github.com/orgs/supabase/discussions/17296

it worked! Thanks.

**Comment by ashusnapx** [comment]
Thanks to @GaryAustin1 for help!
