### ISSUE TITLE
config.toml env not being recognized

### ISSUE THREAD

**Issue by emmyduruc** [supabase/supabase#17505]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

i added this to my .env files for twilo phoneAuth and when trying to signup i do not get an sms rather i get an error like user unrecognied but when i copy in the SID directly an tokn that worked like charm so i can assume that the config.toml file is not recognizing the env 

## To Reproduce

does not work: "env(SUPABASE_AUTH_SMS_TWILIO_ACCOUNT_SID)"
works: "ksmdskdskdmdsdmsdd" token

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by saltcod** [comment]
Hi there @emmyduruc —  what version are you using? Have you updated in a while?

**Comment by emmyduruc** [comment]
> Hi there @emmyduruc — what version are you using? Have you updated in a while?

Hi @saltcod  i am using  "@supabase/supabase-js": "^2.10.0",

**Comment by GaryAustin1** [comment]
Not clear what supabase-js has to do with the .toml file not being read.
saltcod may have been asking about your cli version.

I'm going to close this as it is pretty stale.

If this is still an issue please comment and maybe add some more info.
Thanks
