### ISSUE TITLE
Layout Shift on Supabase homepage Login Button gets annoying

### ISSUE THREAD

**Issue by theonlydaleking** [supabase/supabase#17512]
# Bug report

## Describe the bug

Not so much a bug but an improvement request: 
When you're already logged in to supabase, if you head to supabase.com you'll get a flash of unauthenticated content for about 1s (In Australia at least) which is just enough time to click on the "Login" problem is, this often is the perfect time for it to switch to authenticated and you accidentally click on the "Star us on GitHub" button 

Nice feature to get more stars, but super annoying otherwise. Annoying enough for me to open a bug report 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to supabase.com
2. Click on login 
3. Sucked in you hit the GitHub link by accident 
4. ...
5. Swearing practice 

## Expected behavior

Just move the auth'd interface to align with the un-authed interface so buttons don't move 

## Screenshots

NA

## System information

any browser

**Comment by yashnirmal** [comment]
working on it

**Comment by yashnirmal** [comment]
Anyone maintainers here?
I can think of couple of ways to do this
1. Move the "Star us on github" link to end ( like shown below), so it does not shift when the layout changes
<img width="468" alt="Screenshot 2023-09-18 at 7 00 55 PM" src="https://github.com/supabase/supabase/assets/78169683/e70d701e-ebbe-4a1f-bc0a-2c2f184a7469">

2. make a new useIsUserLoading() hook. 
So wherever is the useIsUserLoading() hook return true, we don't show anything, and when the user state is loaded we can show the correct layout

Which option should I go with?

**Comment by saltcod** [comment]
Thanks @yashnirmal — the issue here is that we're [redirecting](https://github.com/supabase/supabase/blob/chore/add-branch-dropdown-in-nav-v1/studio/next.config.js/#L35-L39).  

 /dashboard redirects to /dashboard/sign-in which then redirects again because you’re already signed in. 
 
We're planning on changing this to redirect to /dashboard/projects instead, as at least that page has a proper loading state. Feel free to give that a go if you wish!

**Comment by yashnirmal** [comment]
Ohk @saltcod , I thought the issues was regarding the shift in Navigation Bar buttons on the `/` page
Should I go ahead and solve the navigation bar shifting issues or drop it for now?

**Comment by saltcod** [comment]
Totally misread this @yashnirmal sorry. 

The issue I posted about is still an issue, though not the one being mentioned here. 
For this one, yeah we should wait for loading to finish before we render that button if we can.
