### ISSUE TITLE
error at docker-compose up -d Container is unhealthy

### ISSUE THREAD

**Issue by markbara-git** [supabase/supabase#17523]
# Bug report

- [ * ] I confirm this is a bug with Supabase, not with my own application. 
- [ * ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When following the guide at: https://supabase.com/docs/guides/self-hosting/docker
when running the command "docker-compose up -d" the output reads:
"ERROR: for functions  Container "bd6d22a70cef" is unhealthy.

ERROR: for auth  Container "bd6d22a70cef" is unhealthy.

ERROR: for meta  Container "bd6d22a70cef" is unhealthy.

ERROR: for realtime  Container "bd6d22a70cef" is unhealthy.

ERROR: for studio  Container "bd6d22a70cef" is unhealthy.

ERROR: for rest  Container "bd6d22a70cef" is unhealthy.

ERROR: for kong  Container "bd6d22a70cef" is unhealthy.
ERROR: Encountered errors while bringing up the project.".
I did copied the .env.example into .env and run 'docker-compose pull'.

## To Reproduce

Go to 'https://supabase.com/docs/guides/self-hosting/docker' and fallow the steps:
Get the code 'git clone --depth 1 https://github.com/supabase/supabase'
Go to the docker folder 'cd supabase/docker'
Copy the fake env vars 'cp .env.example .env'
Pull the latest images 'docker compose pull'
Start the services (in detached mode) 'docker compose up -d'
See error

## Expected behavior

I was expecting composing of the docker image.

## Screenshots

![Screenshot 2023-09-18 135043](https://github.com/supabase/supabase/assets/83405406/2fc4c79f-098d-43f0-8c5c-512d44fbf48f)

## System information

- OS: Debian 12 amd64
- Version of supabase-js: current from the day of this post
- Version of Node.js: current from the day of this post

## Additional context
Previous bug raport:
https://github.com/supabase/supabase/issues/17421
@Ziinc - pulling the latest changes did not fixed the issue with supabase docker compose

**Comment by markbara-git** [comment]
Tried this again today on a fresh OS installation and latest repos:
![image](https://github.com/supabase/supabase/assets/83405406/6a780d10-8feb-4ee6-8e4c-ee425b6a3e6f)

same errors :(

**Comment by kamilogorek** [comment]
See https://github.com/supabase/supabase/issues/16777 for similar issue, maybe the solutions there will work for your case as well.

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup. There's a large chance that this issue has been solved with some of the updates to our docker images

I recommend starting again (using [these](https://github.com/supabase/supabase/blob/5fed762d1fcb7ed060439f0fb4c85f2cf3b5bdd6/docker/docker-compose.yml#L5) commands)

Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
