### ISSUE TITLE
[Info] TypeError: Cannot read properties of undefined (reading 'protocol')

### ISSUE THREAD

**Issue by jijkbird** [supabase/supabase#17544]
import { serve } from "https://deno.land/std@0.177.1/http/server.ts";
import Core from "https://esm.sh/@alicloud/pop-core@1.7.13";

serve(async () => {
  const client = new Core({
    accessKeyId: "",
    accessKeySecret: "",
    endpoint: "https://dysmsapi.aliyuncs.com",
    apiVersion: "2017-05-25",
  });
  const params = {
    "PhoneNumbers": "",
    "SignName": "",
    "TemplateCode": "",
    "TemplateParam": '{"number":"1234"}',
  };
  const requestOption = {
    method: "POST",
    formatParams: false,
  };
  client.request('SendSms', params, requestOption).then((result) => {
    console.log(JSON.stringify(result));
  }, (ex) => {
    console.log(ex);
  })
  return new Response(
    `"Hello from Edge Functions!"`,
    { headers: { "Content-Type": "application/json" } },
  );
});

docker compose restart functions --no-deps

wall clock duration reached. isolate: 9517434353123966400
event loop error: Uncaught Error: execution terminated
main function started
serving the request with /home/deno/functions/hello
[Info] Listening on http://localhost:9999/

[Info] TypeError: Cannot read properties of undefined (reading 'protocol')
    at Object.d.request (https://esm.sh/v132/stream-http@3.2.0/esnext/stream-http.mjs:11:9422)
    at Object.d.request (https://esm.sh/v132/https-browserify@1.0.0/esnext/https-browserify.mjs:5:1024)
    at https://esm.sh/v132/httpx@2.2.7/esnext/httpx.mjs:9:2077
    at new Promise (<anonymous>)
    at Object.$.request (https://esm.sh/v132/httpx@2.2.7/esnext/httpx.mjs:9:2049)
    at M.request (https://esm.sh/v132/@alicloud/pop-core@1.7.13/esnext/pop-core.mjs:16:5078)
    at Server.<anonymous> (file:///home/deno/functions/hello/index.ts:27:10)
    at Server.#respond (https://deno.land/std@0.177.1/http/server.ts:220:37)
    at Server.#serveHttp (https://deno.land/std@0.177.1/http/server.ts:258:20)
    at eventLoopTick (ext:core/01_core.js:183:11)

**Comment by bombillazo** [comment]
Does anyone know why the `event loop error: Uncaught Error: execution terminated` occurs?

**Comment by encima** [comment]
Gonna need some more info here please. Can you edit the issue with additional info using the template plz 🙏 

Does this occur when deployed to Supabase cloud? Does this occur when you run `supabase functions serve`?

**Comment by Alexa-Green** [comment]
I'm also getting this when using amplitude.track(), even if even after it has been amplitude.init()

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
