### ISSUE TITLE
Flow for creating webhooks appears to be broken in web app

### ISSUE THREAD

**Issue by buzzli-ai** [supabase/supabase#17560]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to set up a web hook to trigger an edge function in Supabase Web App.

## To Reproduce

1. I've a edge function deployed.
2. I wanted to set up a webhook on new insertions in the `auth.users` table that would trigger this web hook
3. After setting up the details, clicking on **Create webhook** does nothing. I get the following warning in the console as well:
```js
Warning: An unhandled error was caught from submitForm() Error: projectRef is required
    e table-query.ts:23
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    r asyncToGenerator.js:3
    s asyncToGenerator.js:25
    i asyncToGenerator.js:32
    i asyncToGenerator.js:21
    m table-query.ts:18
    e EditHookPanel.tsx:196
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    r asyncToGenerator.js:3
    s asyncToGenerator.js:25
    i asyncToGenerator.js:32
    i asyncToGenerator.js:21
    xe EditHookPanel.tsx:188
    K formik.esm.js:948
    gn formik.esm.js:1266
    Y formik.esm.js:862
    promise callback*34090/dn/Y< formik.esm.js:838
    gn formik.esm.js:1266
    X formik.esm.js:926
    gn formik.esm.js:1266
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    i helpers.js:74
    onClick EditHookPanel.tsx:284
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    i helpers.js:74
```

## Screenshots

![image](https://github.com/supabase/supabase/assets/138873596/4297054f-2048-4a9c-9554-ac068431063c)

## System information

- OS: Linux
- Browser: Tested on Firefox & Chrome

**Comment by buzzli-ai** [comment]
I could not find a way to add triggers through the Supabase CLI. If it can be done, please let me know. Would be of great help.

**Comment by buzzli-ai** [comment]
Suddenly it's working. Still keeping this open to report the issue.

**Comment by saltcod** [comment]
Hi there — we deployed a fix for this earlier today. Thanks for the report!
