### ISSUE TITLE
Stacking issue in the docs styling

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#1756]
In firefox here: https://supabase.io/docs/reference/javascript/auth-signin

![image](https://user-images.githubusercontent.com/458736/120074539-e6549c00-c0cf-11eb-8318-8e705d8b6ecd.png)

**Comment by enesinan** [comment]
who will solve this issue

**Comment by kiwicopple** [comment]
You can if you want @enesinan !

We need to update the `custom.css` file: https://github.com/supabase/supabase/blob/master/web/src/css/custom.css

**Comment by enesinan** [comment]
👍 👍
