### ISSUE TITLE
Bug Report: OTP Verification Issue with Twilio Verify on Test Numbers (Works on Real Numbers)

### ISSUE THREAD

**Issue by pduggi-cf** [supabase/supabase#17573]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

**Description:**

I have encountered a peculiar issue related to OTP verification when using Twilio Verify as the phone authentication provider. This issue only seems to affect test numbers, as OTP verification works perfectly fine with real numbers. When I initially switched from Vonage to Twilio Verify, OTP verification failed consistently with test numbers, showing an error message indicating that the token had either expired or was invalid. However, OTP verification with real numbers using Twilio Verify works without any problems.

**Steps to Reproduce:**

1. Switch phone authentication provider from Vonage to Twilio Verify.
2. Attempt to sign up with a test phone number using the `signUpWithPhone` function.
3. Enter OTP set and attempt to verify the OTP using the `verifyOTP` function.
4. Observe the error message indicating that the token has expired or is invalid for the test number.

**Expected Behavior:**

OTP verification should work consistently, whether with test numbers or real numbers, when using Twilio Verify as the phone authentication provider. Users should be able to sign up and verify their phone numbers successfully.

**Actual Behavior:**

OTP verification consistently fails with an error message indicating that the token has expired or is invalid when using Twilio Verify with test numbers. However, OTP verification works as expected with real numbers.

**Code Snippets:**

I am using the following code snippets for OTP sign-up and verification:

```javascript
import { supabase } from "../supabase";
import { AuthOtpResponse, VerifyMobileOtpParams } from "@supabase/supabase-js";

export const signUpWithPhone = async (phone: string) => {
  const response: AuthOtpResponse = await supabase.auth.signInWithOtp({
    phone,
  });

  if (response.error) {
    return {
      status: "failed",
      data: response.error.message,
    };
  }
  return { status: "success", data: response.data.user };
};

export const verifyOTP = async (phone: string, token: string) => {
  const verificationData: VerifyMobileOtpParams = {
    phone,
    token,
    type: "sms",
  };

  const response = await supabase.auth.verifyOtp(verificationData);

  if (response.error) {
    return {
      status: "failed",
      data: response.error.message,
    };
  }
  return { status: "success", data: response.data.user };
};
```

**Additional Information:**

- Real phone numbers work as expected.
- I have verified that the issue persists even after switching back and forth between phone authentication providers (Vonage and Twilio Verify).
- I have checked it with multiple device
- This behavior is critical as it affects the reliability of the testing process and may lead to confusion when assessing the functionality of the OTP verification system.

**Environment:**

- Operating System: Mobile (Ios/Android)
- Browser (if applicable):  
- Supabase SDK Version: 2.32.0

![image](https://github.com/supabase/supabase/assets/76139304/acbc3f0b-5141-49a9-9b0e-e19263ce9fa3)
![image](https://github.com/supabase/supabase/assets/76139304/4eba1e57-fdd3-4bbb-871f-edbc163baa88)

**Comment by zkSoju** [comment]
Getting the same issue as well. I can't seem to authenticate without using a real number

**Comment by Aris-ngoy** [comment]
i am getting the same error i can not send my update for review in appstore because of this

**Comment by encima** [comment]
Just to confirm, the test numbers you provide in the dashboard are the numbers used in the example? The settings screenshot for this issue shows a different number to the one in the app screenshot.

Also worth making sure that your Test OTPs are valid and the expiration date is correct.

Let us know if this is still occurring 🙏

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
