### ISSUE TITLE
Can't Get Docker file to install

### ISSUE THREAD

**Issue by SerenityNrrd** [supabase/supabase#17604]
I have followed the directions a few times but I keep getting an error when trying to install Supabase locally...

**Comment by HartmannJonas** [comment]
I think I got the same issue. 
When trying to use `supabase start`, I get the error:

```
Error response from daemon: manifest for public.ecr.aws/supabase/postgrest:v10.2.0 not found: manifest unknown: Requested image not found
```

**Comment by encima** [comment]
Closing due to the age, please comment @SerenityNrrd if you are still having issues and we can reopen!
