### ISSUE TITLE
Comments cause syntax errors in RLS policies

### ISSUE THREAD

**Issue by mmkal** [supabase/supabase#17600]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). (I found this discussion: https://github.com/orgs/supabase/discussions/16922. But it got no responses, and this is a bug so I think belongs here in Issues not in Discussions).

## Describe the bug

Aside from the bad reformatting that gets applied to RLS policies being a bit annoying, it can also cause syntax errors. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the dashboard
2. Click on a table
3. Add a policy
4. Put in the below policy:

```sql
1 = 1
-- and 2 = 2
```

## Expected behavior

The clause is formatted exactly as is into the full policy/policy update statement. Newlines should be added above and below to ensure no funny business with `--` comments.

## Actual behavior

The clause is flattened into a single line which means the comment removes some of the parentheses/scaffolding around the clause:

```sql
BEGIN;
  ALTER POLICY "public anon access 1d3ntpo_0" ON "storage"."objects" USING (1 = 1 -- and 2 = 2);
COMMIT;
```

Also, if you try to work around it by using `/* block comments */`, the policy saves successfully but my precious block comments, the result of lots of tinkering, are deleted! 😭 

## Screenshots

<img width="1139" alt="image" src="https://github.com/supabase/supabase/assets/15040698/f0262dcf-fa91-4578-9315-7f1806761240">

## System information

err it's on the dashboard, on supabase.com. Am I filing this in the wrong repo?

## Additional context

I agree with the suggestion in https://github.com/orgs/supabase/discussions/16922 - the policy should be unaltered if at all possible. The ugly parentheses, indentation and alignment make it very hard to debug policies.

**Comment by faizanraso** [comment]
<img width="1512" alt="Screenshot 2023-09-21 at 6 59 03 PM" src="https://github.com/supabase/supabase/assets/59986120/18d2f738-94e1-47bd-8d31-329b365234aa">

Looks like the formatting is done through some api request. If anyone on the supabase team could advise on how I could contribute to this issue that would be great.

**Comment by burggraf** [comment]
@saltcod Is there a status on this?  Perhaps we should just update the documentation and just state that comments are not support in RLS policies from the dashboard?

**Comment by Hallidayo** [comment]
@burggraf - happy to update the docs if needed?

**Comment by burggraf** [comment]
@Hallidayo that would be great!  Let me know once you've made the PR.

**Comment by Hallidayo** [comment]
Hi @burggraf, I've just create a pull and added a warning in the RLS deep dive.

**Comment by mmkal** [comment]
@burggraf @charislam @Hallidayo I don't think this should be closed as completed. There's still a bug, which is that RLS policies can break despite being written in valid SQL. Even once this is "worked around" by removing comments, that's still quite a big loss because we are now forced to have no explanations of _why_ RLS policies are what they are.

It's great that the bug is acknowledged in the website, though.
