### ISSUE TITLE
No access to create roles on dashboard on self hosted docker

### ISSUE THREAD

**Issue by Mats-Hjalmar** [supabase/supabase#17629]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to create, delete or patch a role using the dashboard when logged in as `supabase` and example password.

## To Reproduce

1. Download this repository.
2. Use example env as env.
3. run the docker container.
4. open localhost:8000
5. log in as `supabase`
6. try create a role and observe the error that pops up saying `Failed to update role "[ROLE]": Method POST Not Allowed`.

## Expected behavior

A role should be able to be created, just as with the official hosted version.

## Screenshots

<img width="656" alt="image" src="https://github.com/supabase/supabase/assets/111428992/54e61ff2-12b5-4c1c-b5f7-7215623049f4">
<img width="656" alt="image" src="https://github.com/supabase/supabase/assets/111428992/56ddbed0-42a4-430b-a119-66285e66391a">

## System information

- OS: [e.g. macOS, Windows]: macOS, linux (ubuntu)
- Browser (if applies) [e.g. chrome, safari]: chrome
- Version of supabase-js: [e.g. 6.0.2]: unsure
- Version of Node.js: [e.g. 10.10.0]: unsure

**Comment by kishanhitk** [comment]
This has been fixed by #16842, and will be available soon.

Ref:
> The studio version in the CLI is a bit behind what we release here. The CLI has a new release every two weeks, so this should be included soon. For now, this might be in the beta version of the CLI (`npm i supabase@beta`).


_Originally posted by @alaister in https://github.com/supabase/supabase/issues/16842#issuecomment-1708567989_

**Comment by rackaracka123** [comment]
Do you know how i can assign a user a specific role? That is a bit unclear to me

**Comment by rackaracka123** [comment]
When i create a custom role and make it select access on a table. it does not work... it works when i have a clean postgres and create a role but not on supabase. when i use Intellij IDEA database manager i can edit with a GUI and when i click save it doesnt save... but it says it does?

**Comment by rackaracka123** [comment]
its like its granting the wrong thing

**Comment by burggraf** [comment]
Custom roles shouldn't/can't be used in RLS policies since the only roles the auth system uses are `anon` and `authenticated`.  Use something like custom claims or db_pre_request for this instead.

https://github.com/supabase-community/supabase-custom-claims 
https://github.com/point-source/supabase-tenant-rbac
https://github.com/burggraf/postgrest-request-processing
https://github.com/burggraf/postgrest-request-processing/tree/main/examples/RBAC
https://lasse-skaalum.medium.com/implementing-rbac-with-next-js-and-supabase-5dd20adaaeba
