### ISSUE TITLE
Error running Supabase with a local Postgres instance

### ISSUE THREAD

**Issue by Zyles** [supabase/supabase#17630]
I read the install instructions on https://supabase.com/docs/guides/self-hosting/docker from top to bottom but am unable to launch supabase on my server.

```
$ curl 127.0.0.1:8000

curl: (7) Failed to connect to 127.0.0.1 port 8000 after 0 ms: Connection refused
```

```
$ sudo docker ps -a

CONTAINER ID   IMAGE                              COMMAND                   CREATED          STATUS                                    PORTS                                            NAMES
d03fc1a71222   supabase/storage-api:v0.40.4       "docker-entrypoint.s…"    45 minutes ago   Up 6 seconds (health: starting)           5000/tcp                                         supabase-storage
e0eb9539142b   kong:2.8.1                         "bash -c 'eval \"echo…"   45 minutes ago   Created                                                                                    supabase-kong
57b8bd9eae11   supabase/gotrue:v2.92.1            "gotrue"                  45 minutes ago   Created                                                                                    supabase-auth
e8210b2ae26c   supabase/studio:20230912-748fd33   "docker-entrypoint.s…"    45 minutes ago   Created                                                                                    supabase-studio
2de6217bb308   supabase/edge-runtime:v1.18.1      "edge-runtime start …"    45 minutes ago   Created                                                                                    supabase-edge-functions
c873bc2db4e6   timberio/vector:0.28.1-alpine      "/usr/local/bin/vect…"    45 minutes ago   Up 45 minutes (healthy)                                                                    supabase-vector
2a26e9d1e94e   darthsim/imgproxy:v3.8.0           "imgproxy"                45 minutes ago   Up 45 minutes (healthy)                   8080/tcp                                         sse-imgproxy
b42b7450b18d   supabase/logflare:1.4.0            "sh -c '`cat <<EOF >…"    45 minutes ago   Restarting (127) Less than a second ago                                                    sse-analytics
a2a64e373493   supabase/postgres-meta:v0.68.0     "docker-entrypoint.s…"    45 minutes ago   Up 45 minutes (healthy)                   8080/tcp                                         sse-meta
4d2e67b1d113   supabase/realtime:v2.10.1          "/usr/bin/tini -s -g…"    45 minutes ago   Up 12 seconds (health: starting)                                                           rme-dev.supabase-realtime
a078b8701db1   postgrest/postgrest:v11.2.0        "postgrest"               45 minutes ago   Up 45 minutes                             3000/tcp                                         sse-rest
```

PostgreSQL is hosted locally on the server.

It seems supabase can not connect to an external server. Even tho I uncommented all the postgresql stuff in docker compose file.

**Comment by Zyles** [comment]
I added `network_mode: host` to all services in docker compose file so they can access the locally hosted postgres.

But they will still not start:
```
{"level":"fatal","msg":"running db migrations: Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to `host=127.0.0.1 user=supabase_auth_admin database=test`: server error (FATAL: password authentication failed for user \"supabase_auth_admin\" (SQLSTATE 28P01))","time":"2023-09-21T19:47:47Z"}
```

**Comment by Zyles** [comment]
Giving up for today. Getting supabase to run on external database seems to be impossible. Please improve your docs.

I installed all pg_jwt, pg_net extensions, ran all the migration scripts and still unable to get an instance running.

Endless problems.

```
fe25c253387a   supabase/storage-api:v0.40.4     "docker-entrypoint.s…"   5 hours ago    Restarting (1) 50 seconds ago                                                      supabase-storage
```

```$ sudo docker logs fe25c253387a

running migrations
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
finished migrations
Error: listen EADDRINUSE: address already in use 0.0.0.0:5000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 5000
}
```

**Comment by Zyles** [comment]
`dcc189c5269b   supabase/studio:20230912-748fd33   "docker-entrypoint.s…"    5 hours ago    Exited (0) 27 minutes ago supabase-studio`

```
$ sudo docker logs dcc189c5269b

Listening on port 3000
This browser does not support the Navigator Locks API. Please update it.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
This browser does not support the Navigator Locks API. Please update it.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
```

**Comment by semanser** [comment]
I'm currently having the same issue. `supabase start` command fails due to an error
```
This browser does not support the Navigator Locks API. Please update it.
info  - Loaded env from /app/studio/.env
Listening on port 3000
This browser does not support the Navigator Locks API. Please update it.
service not healthy: [supabase_studio_supabase]
```
It seems like it fails to run the studio container.

**Comment by kiwicopple** [comment]
Hi @Zyles -

> I read the install instructions from top to bottom
> ...
> Getting supabase to run on external database

I hope you don't mind but I've renamed this to "Docker instructions do not work". The docs do not give any instructions for running with an external Postgres database. The docker instructions _do_ work if you follow them - I have just tested again myself and there is no regression that I can see.

> Error: listen EADDRINUSE: address already in use 0.0.0.0:5000

The error looks reasonably clear here - are you are running something already on port 5000?

> This browser does not support the Navigator Locks API. Please update it.

I'll check with the Frontend team on this one. It's an obscure error

**Comment by MCYouks** [comment]
Any update on this issue?

**Comment by semanser** [comment]
I ended up disabling the supabase dashboard and just using some external postgres client to access the database. Also, this issue appeared not that long time ago since I was able to run the dashboard some weeks ago.

**Comment by titouancreach** [comment]
Same problem on macOS, working with docker on M1 chip but no on intel chip. With a "just created" project and:
  - supabase login
  - supabase init
  - supabase start

Even when the studio starts (M1), I can see the log:
```
info  - Loaded env from /app/studio/.env
Listening on port 3000
This browser does not support the Navigator Locks API. Please update it.
This browser does not support the Navigator Locks API. Please update it.
```

We followed the documentation: https://supabase.com/docs/guides/cli/local-development

**Comment by sweatybridge** [comment]
For those on intel macs, we ran into similar problems before where the nodejs crashes due to incompatible virtualisation settings for docker. Could you check if the following solution work for you https://github.com/supabase/cli/issues/1083#issuecomment-1691431279

**Comment by flo-tech** [comment]
> For those on intel macs, we ran into similar problems before where nodejs crashes due to incompatible virtualisation settings for docker. Could you check if the following solution work for you [supabase/cli#1083 (comment)](https://github.com/supabase/cli/issues/1083#issuecomment-1691431279)

This solution work for me, I am on intel macs

**Comment by titouancreach** [comment]
It works, sorry for the noise. Fell free to remove our comments if it pollutes the original issue. 
Thanks

**Comment by semanser** [comment]
Yes, I can confirm that disabling the virtualization (as described [here](https://github.com/supabase/cli/issues/1083#issuecomment-1691431279)) solves the issues even on Intel.
