### ISSUE TITLE
Exporting CSV exports jsonb as `[object Object]`

### ISSUE THREAD

**Issue by nstrelow** [supabase/supabase#1764]
# Bug report

## Describe the bug

Exporting rows from a table with jsonb columns, exports those as a JavaScript `[object Object]`
## To Reproduce

1. Select rows from a table with jsonb
2. Click Export CSV

## Expected behavior

The JSON string instead of `[object Object]`

Please tell me if additional info is needed.

**Comment by joshenlim** [comment]
hey there @nstrelow ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
