### ISSUE TITLE
Copy cell content not working reliably

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#17658]
In the Table Editor, this right click copy action fails every 2nd or 3rd time you do it. 

![screenshot-2023-09-22-at-16 01 13](https://github.com/supabase/supabase/assets/105593/6b3baf6c-0e3e-4ae9-b2ee-722e899640fb)

**Comment by yurimutti** [comment]
Hi, I would like to work in this issue.

**Comment by faizanraso** [comment]
> Hi, I would like to work in this issue.

Hi @yurimutti, there's no assigning process for supabase as far as I know. You can submit a PR if you'd like to contribute and someone from their team will review it.

**Comment by yurimutti** [comment]
> > Hi, I would like to work in this issue.
> 
> Hi @yurimutti, there's no assigning process for supabase as far as I know. You can submit a PR if you'd like to contribute and someone from their team will review it.

Great! I'm working to fix this.

**Comment by aikins01** [comment]
PR #17686 was merged, this issue should be closed right?

**Comment by yurimutti** [comment]
I tested in production and looks ok to me but is interesting other people test too.
