### ISSUE TITLE
JWSInvalidSignature error

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#177]
# Bug report

## Describe the bug

I am seeing an odd error that I was not seeing before. All my authenticated requests are 401ing with: "JWSError JWSInvalidSignature". It was working and I have not changed anything that would affect this, I even reset my code back to when I know it was working to confirm I didn't break it. The only change I made was updating the name of my project in the Supabase dashboard, I change it back to the original name and it is still broken. It is possible the name change made the anon JWT invalid?

## To Reproduce

1. Signup as a new user
2. Use the session from the new user to try and `POST` to any table
3. The request fails with a 401

#### Signup -> 200
<img width="549" alt="Screen Shot 2020-09-02 at 3 40 48 PM" src="https://user-images.githubusercontent.com/6392501/92045343-23ecea00-ed35-11ea-9d9d-2407be0286fe.png">

#### Create row is user data table -> 401
<img width="542" alt="Screen Shot 2020-09-02 at 3 40 54 PM" src="https://user-images.githubusercontent.com/6392501/92045344-25b6ad80-ed35-11ea-9ef9-9942ada3c2ff.png">
<img width="430" alt="Screen Shot 2020-09-02 at 3 40 57 PM" src="https://user-images.githubusercontent.com/6392501/92045348-26e7da80-ed35-11ea-89c3-2f3770b30f66.png">
(confirmed the jwt access token from the signup response is in the request header)
<img width="649" alt="Screen Shot 2020-09-02 at 3 41 04 PM" src="https://user-images.githubusercontent.com/6392501/92045567-b9887980-ed35-11ea-8ec4-25aba2dcc2a3.png">

## System information

- Version of supabase-js: v0.36.4

**Comment by kiwicopple** [comment]
So sorry about this @zlwaterfield, digging now.

> It is possible the name change made the anon JWT invalid?

This seems like a good lead. Is your service key working still? A few other possibilities we are investigating:

- Your JWT secret was changed - it is definitely still there, so I can only think that it might have been changed.
- The JWT has been dropped/changed in the middleware - @awalias any updates rolled out to KPS last night ? 

Interesting I can't find any errors for this on gotrue: https://github.com/netlify/gotrue/search?q=jwsinvalidsignature&unscoped_q=jwsinvalidsignature

**Comment by kiwicopple** [comment]
Follow up, looks like the JWT is encoding a stringified JSON object

```
eyJhbGciOiJIUzIlNiIsInR5cCI6IkpXVCJ9.eyJhdWQi0iJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNTk5MDg5ODYOLCJzdWIi0iI3MWIONmE00505ZDYyLTRhYjYtYmZ1MyOxY2Q2YTIwNGV1NjciLCJ1bWFpbCI6Inpsd2FOZXlmaWVsZCsxMjMOQGdtYW1sLmNvb5IsImFwcF9tZXRhZGFOYSI6eyJwcm92aWR1ciI6ImVtYW1sInOsInVzZXJfbWVOYWRhdGEi0m51bGwsInJvbGUiOilhdXRoZW50aWNhdGVkInO.fpxP78mU7QulZRBoVfd3Un0Yh7RCea_vLOpmfoIYVyY
```

![image](https://user-images.githubusercontent.com/10214025/92068323-36b8fa80-edd9-11ea-896d-a4eee6ba7971.png)

Still investigating how/where this one came from

**Comment by awalias** [comment]
this was actually quite an elusive bug. thanks for catching @zlwaterfield . The issue was that when the disable email confirmation switch was toggled, the auth api server config was getting overwritten but the jwt_secret was not being set and was therefore falling back to a default value silently. This has now been patched in prod, thanks for investigative work all.

**Comment by zlwaterfield** [comment]
Amazing thank you @awalias, I've confirmed it is working on my project.

**Comment by junedkhatri31** [comment]
I just got this bug replicated. Unfortunately, I deleted the project and created new one. I realized it is Supabase issue only after I deleted the project. Just wanted to inform that this bug still exists.

**Comment by fletchertyler914** [comment]
I believe I just hit this issue as well. Service key and Anon key are the same, but both are suddenly getting 401's. We had a public table column name value change recently but thats the only thing thats been changed recently.

**Comment by rajan-personal** [comment]
this helped me.

https://www.reddit.com/r/Supabase/comments/v8kefr/401_error_jwserror_jwsinvalidsignature_even_when/

**Comment by ethanfox** [comment]
I am having this problem as well when trying to make API calls on the server. Client-side works fine.

**Comment by davidtranjs** [comment]
For anyone experiencing this painful issue, the official documentation will not work, and I don't know why they haven't updated it. You can use supabase-tools.davidtran.dev to generate the correct keys

**Comment by italobarbagelata** [comment]
not work https://supabase-tools.davidtran.dev/ error: {
    "error": {
        "message": "invalid JWT: unable to parse or verify signature, token is malformed: could not base64 decode claim: illegal base64 data at input byte 111"
    }
}

**Comment by syliontech** [comment]
> For anyone experiencing this painful issue, the official documentation will not work, and I don't know why they haven't updated it. You can use https://supabase-tools.davidtran.dev to generate the correct keys

I got this error JSONDecodeError "Not valid base64url" ,  when I use new generate key , can you help fix

**Comment by aozeel** [comment]
i tried re-create service-anon-secret keys with davidtranjs's tool and fix the issue
