### ISSUE TITLE
Supabase console for storage not accessible

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#1770]
# Bug report

## Describe the bug

Console page for storage has unexpected error when I try to open it. 
https://app.supabase.io/project/${project_id}/editor/table

My project with project id of `uolvtdzkvkolsynuhmzh` had this error, but `ucvdfmhwjjomlpgavbow` did not have any errors. The first project has some files stored, and the later one is a blank bucket, so that might be the cause. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/uolvtdzkvkolsynuhmzh/storage`
2. Wait for everything to load. 
3. Wait for another few seconds. 
4. See the error. 

## Screenshots

<img width="1440" alt="Screen Shot 2021-05-29 at 8 25 30" src="https://user-images.githubusercontent.com/18113850/120122372-5c95f300-c1e3-11eb-9061-f89f4dbecea6.png">
<img width="1440" alt="Screen Shot 2021-05-31 at 7 40 17" src="https://user-images.githubusercontent.com/18113850/120122397-77686780-c1e3-11eb-84ed-22cd6a12cd97.png">

## System information

- OS: [macOS]
- Browser (if applies) [chrome]

**Comment by inian** [comment]
I was just looking into reproducing this report from some users. Thanks for the screenshots Tyler! Looking into this now.

**Comment by dshukertjr** [comment]
Thank you @inian ! Let me know if I can help in any ways!
