### ISSUE TITLE
Supabase REST API is returning error 'The result contains 0 rows' even when using .maybeSingle()

### ISSUE THREAD

**Issue by vivianedias** [supabase/supabase#17711]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've recently launched successfully an application using Supabase, but recently I've been getting this error when the `select` method returns no rows:

{ "code": "PGRST116", "details": "The result contains 0 rows", "hint": null, "message": "JSON object requested, multiple (or no) rows returned"}

## To Reproduce

This code, when returns no rows, the error obj returns with the previous error:

```
    const { data, error } =
      await supabase
        .from("booking_policy_recurring_min_stay")
        .select("min_stay")
        .eq("listing_id", listingId)
        .limit(1)
        .maybeSingle();
```

## Expected behavior

When using `maybeSingle()` it shouldnt throw an error.

## System information

- Version of supabase-js: ˆ2.21.0
- Version of Node.js: +16

## Additional context

This issue wasn't happening in the previous weeks, I think it started last week. We had a successful launch and the API was returning correctly. It seems something changed in the supabase API and this query started to throw an error when no rows returned.

**Comment by GaryAustin1** [comment]
Is the supabase-js error actually sending back something in the error variable or are you looking at the network request.  I believe supabase-js hides the error in the response even though PostgREST API always generates the error.

**Comment by GaryAustin1** [comment]
It looks like the change above was rolled in to supabase-js  in v2.23.0

**Comment by GaryAustin1** [comment]
@vivianedias can you confirm upgrading solves your issue?

**Comment by GaryAustin1** [comment]
I'm going to close this issue unless you have feedback that should re-open it.  Thanks.

**Comment by SquareGraph** [comment]
Hey, guys, any updates regarding this issue?

I'm trying to update one table based on the changes from another table (+ additional calls, that why I'm using edge functions with webhook), but I'm getting null user no matter how I'm authenticating. I tested every approach above, also what's in official docs + [https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/select-from-table-with-auth-rls/index.ts](url)
Nothing works so far.
