### ISSUE TITLE
Cron Job Timezone Issue

### ISSUE THREAD

**Issue by vongohren** [supabase/supabase#17736]
### Discussed in https://github.com/orgs/supabase/discussions/7892

Now that this is acctually supported: https://github.com/citusdata/pg_cron/issues/16#issuecomment-1415947296 
How can I get this configuration set in the database?

**Comment by GaryAustin1** [comment]
Going to close this in favor of the one with several links to this and other comments.

**Comment by GaryAustin1** [comment]
Yeah, I was thinking of the cron issue in supabase/postgres as that is where the fix needs to occur.
