### ISSUE TITLE
error status "UNKNOWN" for analytics

### ISSUE THREAD

**Issue by AmsellemJoseph** [supabase/supabase#17750]
Hey,

I deployed supabase with docker-compose as you describe here https://github.com/supabase/supabase/tree/master/docker
everything seems fine, but when I want to access the logs, I always get this error:

        {
         "code": 502,
         "Errors": [],
         "message": "Something went wrong! Unknown error. If this continues, please contact support.",
         "status unknown"
        }

I think I missed something, but I don't know what.

I added parsing and vector containers, changed the password in each line of vector.yml,

It's pretty simple, my project is exactly the same as yours and the other containers work fine.

Thanks a lot for your help. 😊

![Screenshot 2023-09-21 184516](https://github.com/supabase/supabase/assets/79039145/845926d7-ba5a-4e0b-a3f4-fe23b95b7bcf)

**Comment by Kevinlzs** [comment]
I am working on this

**Comment by amitshuklabag** [comment]
Hey,
@Kevinlzs Any updates about these?

**Comment by flyvoid** [comment]
If you try the code `Select timestamp,`  instead of `select
 cast(timestamp as datetime) as timestamp,`, it will not generate error. But still, there might be some issues for supabase to use SQL correctly, since I've tried other SQL functions, they will cause error in Log Explorer.

**Comment by flyvoid** [comment]
It might be helpful to look up Supabase's sql query file and how supabase uses Logflare as  log management to solve this issue.

**Comment by Kevinlzs** [comment]
@amitshuklabag Me and a team of other students were working on trying to fix this open-source issue but unfortunately, we were unable to actually locate were the issue is actually occurring.

**Comment by BenHerbst** [comment]
Same issue here at devsfordevs.com

**Comment by BenHerbst** [comment]
fdsfs

**Comment by tranhoangvuit** [comment]
Hi @AmsellemJoseph, can you take a look at this comment: https://github.com/supabase/supabase/issues/18891#issuecomment-1852347504?. Hope it can help you.

**Comment by riccardolardi** [comment]
Same issue here on self hosted Supabase. Any news on this?

**Comment by kaumac** [comment]
Honestly I feel like there's a lack of interest from supabase on the selfhosted stack. You can tell from the lack of features that you have on the hosted app. 

This would be totally understandable (after all the selfhosted app doesn't bring in any money), except that the self hosted stack is a critical part of a mature/production app.

I develop locally and afterwards deploy to staging and production which are cloud (paid for) apps.

Supabase is such a great platform, you can tell there's a lot of hard work done on the cloud app, but I must say that the local development feels unpolished and somewhat painful to work with.

**Comment by tranhoangvuit** [comment]
Hi @riccardolardi , can you check this comment? https://github.com/supabase/supabase/issues/18891#issuecomment-1864662408. I think by default, we don't enable `analytic`.

**Comment by BenHerbst** [comment]
There is a workaround, you can just use a 3rd party service like datadog or check the container logs via a service like portainer

**Comment by agaitan026** [comment]
> Honestly I feel like there's a lack of interest from supabase on the selfhosted stack. You can tell from the lack of features that you have on the hosted app.
> 
> This would be totally understandable (after all the selfhosted app doesn't bring in any money), except that the self hosted stack is a critical part of a mature/production app.
> 
> I develop locally and afterwards deploy to staging and production which are cloud (paid for) apps.
> 
> Supabase is such a great platform, you can tell there's a lot of hard work done on the cloud app, but I must say that the local development feels unpolished and somewhat painful to work with.

sure do, they dont care self host :( even not answer in forum on discord, so sad :(

**Comment by encima** [comment]
Hello all, 

thank you for opening this and we appreciate the feedback. We have done a lot of work on improving the self-hosted experience and we will continue to do so. Issues like this are vital for us to identify and address those problems.

Some of you are running supabase from the main repo and others are using the CLI.

First, can you confirm that you have `analytics` enabled please.
Second, if you do get this error, you can still see individual logs by clicking on:
- Kong API
- Postgres
- etc

in the side menu.

**Comment by CarlosBranty** [comment]
same problem here, when i try to create new user from studio panel 
{
  "code": 502,
  "errors": [],
  "message": "Something went wrong! Unknown error. If this continues please contact support.",
  "status": "UNKNOWN"
}

**Comment by encima** [comment]
@CarlosBranty have you enabled `analytics`? See docs [here](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started)

**Comment by RyanClementsHax** [comment]
Hopefully this helps https://github.com/supabase/supabase/issues/18707#issuecomment-1918196532

**Comment by lukkaempf** [comment]
I had the same issue after I renamed my containers. I needed to update the container names in vector.yml

**Comment by GaushJMeta** [comment]
I am still getting this error while trying to self host. I tried pasting both, the logflare API access token as well as the api-key in the .env file as well as vector file but still getting this error. Please help . I followed the self hosting with docker documentation then followed this link for setting up logs https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started

**Comment by Akash187** [comment]
Getting same error https://github.com/supabase/supabase/issues/26785
