### ISSUE TITLE
add pg_idkit support

### ISSUE THREAD

**Issue by Monu18765** [supabase/supabase#17757]
This is really not a bug but a feature request which is pending for a long time there is a discussion thread for this https://github.com/orgs/supabase/discussions/9500.

Hope someone from Supabase team will answer why this extension is not available till now.

**Comment by GaryAustin1** [comment]
This is already an open issue in supabase/postgres.  And there have been several discussions and issues generated.
https://github.com/supabase/postgres/issues/318

**Comment by GaryAustin1** [comment]
Your issue is now linked there.  So will close this one.
