### ISSUE TITLE
Table Editor Bug: clicking outside of a Jsonb cell popover results in an UPDATE for the row

### ISSUE THREAD

**Issue by nate-oo** [supabase/supabase#17760]
## Describe the bug

In the Dashboard Table Editor, an UPDATE for the row is performed when you double-click to open the Jsonb cell popover (to see the formatted Json) and click outside of the popover EVEN IF you did not perform any changes to the cell content.

## To Reproduce

1. Go to the Table Editor
2. Find a table that contains Jsonb columns
3. Find a Jsonb column that has data in it
4. Double click the Jsonb cell to open the popover that displays the value as nicely formatted Json
5. Don't make any changes to the cell as you only wanted to view the nicely formatted Json
6. Now click outside of the popover to close it
7. **The Bug**: when you click outside of the popover it closes it but performs an update on the row even if you did not edit it

## Expected behavior?

1. Only when you hit enter on your keyboard should an update be performed on the row.
2. When you click outside of the popover it should close it/escape and shouldn't perform an update on the row even if you made changes.

At least this behavior makes sense to me :)

## Screenshots

<img width="566" alt="Screenshot 2023-09-27 at 2 10 16 PM" src="https://github.com/supabase/supabase/assets/123698607/b0e44388-6afb-46f1-b721-b3348f098ef5">

## System information

- OS: [macOS]
- Browser [Chrome Version 116.0.5845.187 (Official Build) (arm64)]
- On the paid Supabase PRO version

**Comment by faizanraso** [comment]
<img width="1512" alt="Screenshot 2023-09-27 at 10 22 21 PM" src="https://github.com/supabase/supabase/assets/59986120/62d437d1-82c1-4d7e-a5f3-79ab2142e1da">

Looks like it was intended to be this way. If a member of the supabase team would like, I could submit a PR removing this useEffect and thus disabling the autosave when an area outside the editor is clicked.

**Comment by nate-oo** [comment]
@faizanraso There very well could be good reasons for the way it currently works that I am not aware of. 

I was thinking from the perspective of when people just want to open the popover to only view the json (which probably happens a lot) and not change it. In this scenario, it seems like an update shouldn't occur for the row because nothing changed.

My thought was this could unintentionally cause database triggers to fire when in reality nothing changed in the row. 

Maybe something in the middle is the solution? Some additional logic to see if the value has changed? If it has changed, then perform a save/update? Otherwise, if there is no change, then escape and do not update the row?

Just some thoughts here :)

**Comment by faizanraso** [comment]
Hey @nate-oo, just submitted a PR implementing your suggestion!

**Comment by nate-oo** [comment]
@faizanraso Awesome! That was quick

**Comment by alaister** [comment]
As per this comment: https://github.com/supabase/supabase/pull/17792#issuecomment-1809302119 I'm making this as resolved.
