### ISSUE TITLE
Ending JSON Data With a Comma Leads to an Error

### ISSUE THREAD

**Issue by faizanraso** [supabase/supabase#17794]
## Describe the bug

When writing JSON data, sometimes a comma is left at the end of the last value in the object, like this:

{
  "id": 3,
  "title": "Test Title 1"**,** <- (here)
}

Most code editors are able to detect this and remove this comma when saving. When using the JSON editor in supabase, it throws an error and does not allow the user to save.

https://github.com/supabase/supabase/assets/59986120/29b6e901-7124-4d60-ada7-e75d581340ff

## Expected behavior

The editor should detect the trailing comma, remove it, and save the updated data.

**Comment by Bayyana-kiran** [comment]
@faizanraso Can i work on this issue?

**Comment by faizanraso** [comment]
> @faizanraso Can i work on this issue?
> 
> 

A PR has already been submitted for this issue, it's awaiting review
