### ISSUE TITLE
Schema Visualiser "System" theme issue when using dark mode

### ISSUE THREAD

**Issue by permpkin** [supabase/supabase#17793]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When theme is set to "System" ( and my system theme is dark ), the Schema Visualiser has incorrect grid color.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set System theme to "dark"
2. Set Supabase theme to "System"
3. Goto "Schema Visualiser"
4. See issue

## Expected behavior

Expect dark theme for grid background.

## Screenshots

<img width="731" alt="Screenshot 2023-09-29 at 11 38 52 am" src="https://github.com/supabase/supabase/assets/20786368/4aeb42b0-d340-431b-af33-904238bda48f">

## System information

- OS: macOS
- Browser Chrome

**Comment by selvedge** [comment]
I can confirm, the Bug exists:

**System information**
OS: macOS
Browser Chrome, and Safari

**Comment by saltcod** [comment]
Hi there – deployed a fix for this today. Please reopen if you experience any more issues here. Thanks for the report!
