### ISSUE TITLE
Tooltip Background Missing for Search Icon in Supabase Dashboard

### ISSUE THREAD

**Issue by ShinanTc** [supabase/supabase#17802]
**Chore: Tooltip Background Adjustment**

**Describe the chore**
The chore involves adjusting the background of the tooltip for the search icon in the Supabase Dashboard.

**Current Behavior**
When hovering over the search icon within a project in the Supabase dashboard, the tooltip with the shortcut "CTRL K" appears without a background, unlike other elements within the dashboard.

![Edge Functions _ Supabase - Google Chrome 9_27_2023 11_16_29 AM](https://github.com/supabase/supabase/assets/64408653/89e271a0-c31e-4b8b-8df9-d24e756b8e9f)

**Expected Behavior**
The search icon should display a tooltip with a distinct background, consistent with the behavior of other elements that show a tooltip with a black background badge.

![Edge Functions _ Supabase - Google Chrome 9_27_2023 11_17_12 AM](https://github.com/supabase/supabase/assets/64408653/ce1e14a9-79a8-435f-ac5d-1d5ea8ddfe66)

**Additional context**

***Steps to Reproduce***
Log in to your Supabase account.
Access the Supabase dashboard.
Open a project.
Hover over the search icon within the project.

**Environment**
***Browser:*** Chrome
***OS:*** Windows 10

**Note**
Ensure that you are using the latest version of the Supabase dashboard to confirm that the issue is not already resolved in a subsequent release.

This chore is aimed at enhancing the user experience by providing a more consistent and visually informative tooltip background for the search icon in the Supabase Dashboard.

**Comment by ashukumar2001** [comment]
I think some tooltip background class is missing.

**Comment by ShinanTc** [comment]
> I think some tooltip background class is missing.

Yeah, maybe.
