### ISSUE TITLE
Getting { session:null } when using getSession()

### ISSUE THREAD

**Issue by retr0cube** [supabase/supabase#17810]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to retrieve user sessions after login using the following function `getSession()`, but I'm getting `{ "session":null }`.

## To Reproduce

github.com/Msharfin/app 
or this discord [thread](https://discord.com/channels/839993398554656828/1006358244786196510) for more info.

## Expected behavior

Receive a JSON like the following: 
```
{
    access_token: 'token',
    token_type: 'bearer',
    expires_in: 3600,
    expires_at: 1696011481,
    refresh_token: 'abcdefghijklmnop',
    user: {
      id: 'x-x-x-x',
      aud: 'authenticated',
      role: 'authenticated',
      email: 'example@gmail.com',
      email_confirmed_at: '2023-09-17T15:33:45.075673Z',
      phone: '',
      confirmed_at: '2023-09-17T15:33:45.075673Z',
      last_sign_in_at: '2023-09-29T17:18:02.125123713Z',
      app_metadata: [Object],
      user_metadata: {},
      identities: [Array],
      created_at: '2023-09-17T15:33:45.070669Z',
      updated_at: '2023-09-29T17:18:02.12738Z'
    }
  }
```

## System information

- OS: Windows 10
- Brave Browser
- Version of supabase-js: 2.33.1

## Additional context

I looked up this issue, but nothing has helped resolve it; so this isn't a duplicate!

**Comment by GaryAustin1** [comment]
I commented on your issue in github which you did not successfully link here.
Looks like you are trying to use supabase-js servers side and did not set persistSession:false as the warning you get suggests.
Adding a link.
https://discord.com/channels/839993398554656828/1157349127634554982

I'm going to close this for now and defer to Discord to see if resolved or you have more questions there.
Not also for sveltekit there is auth-helpers which deals with browser and serverside auth working together.
