### ISSUE TITLE
Edge functions select-from-table-with-auth-rls

### ISSUE THREAD

**Issue by Jonatthu** [supabase/supabase#17825]
https://supabase.com/docs/guides/functions/auth
https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/select-from-table-with-auth-rls/index.ts

I am able to successfully read tables on behalf of a user using this method on an edge function, but how about calling the auth api to update an auth user on his behalf without using service key as the user itself like:

Calling:
const updateRls = await ctx.supabase.auth.update user({
phone: '+16574568825',
});

Returns AuthSessionMissingError: Auth session missing!

Which is okay we know we can call:
ctx.supabase.auth.setSession({
accesstoken, refreshtoken
})

But on edge function best of my knowledge we should not send refresh tokens on the headers.

What's my work around when I want to update an users email from the edge function without using service keys?
The use case of this is when you want to update the user emails and also call additional business logic that in case of failure on the backend we roll back that email change easily. 

<img width="664" alt="image" src="https://github.com/supabase/supabase/assets/3742176/c36b8919-dce8-4d2e-9410-7cdf04070824">

https://supabase.com/docs/guides/functions/auth
https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/select-from-table-with-auth-rls/index.ts

**Comment by encima** [comment]
Hi @Jonatthu,

Did you manage to solve this issue? You could authenticate from the edge function using your service key without exposing it to the user (i.e. not using the Anon key but setting it to the service key). This will only use the service key from the function to the Supabase API and not to whatever triggered the function.

See [here](https://supabase.com/docs/guides/functions/secrets) for the env variable that the function has access to. Let us know if that does not solve the issue and we can re-open!
