### ISSUE TITLE
SQL Functions with Multiple JOINs Fail to Execute in Supabase SQL Editor

### ISSUE THREAD

**Issue by Slyracoon23** [supabase/supabase#17822]
## Bug report
 I confirm this is a bug with Supabase, not with my own application.
 I confirm I have searched the [Docs](https://docs.supabase.com/), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com/).
## Describe the bug
When attempting to create a SQL function within Supabase that contains multiple JOIN operations, the function fails to execute properly. However, the same SQL query with multiple JOINs runs successfully when executed outside of a SQL function.

## To Reproduce

Go to the Supabase SQL editor.
Create a SQL function with the following code:
```
CREATE OR REPLACE FUNCTION discord_messages(p_org_id BIGINT)
RETURNS TABLE (
    message_id INT,
    content TEXT,
    channel_id INT,
    channel_name TEXT,
    author_id INT,
    author_username TEXT,
    timestamp TIMESTAMP
)
LANGUAGE SQL AS $$
BEGIN
    RETURN QUERY
    WITH org_messages AS (
        SELECT message_id
        FROM public.junc_orgs_discord_messages
        WHERE org_id = p_org_id
    )
    SELECT 
        dm.id AS message_id,
        dm.content,
        dm.channel_id,
        dc.name AS channel_name,
        dm.author_id,
        dmem.username AS author_username,
        dm.timestamp
    FROM public.discord_messages AS dm
    JOIN org_messages AS om ON dm.id = om.message_id
    JOIN public.discord_channels AS dc ON dm.channel_id = dc.id
    JOIN public.discord_members AS dmem ON dm.author_id = dmem.id;
END;
$$;
```
Try executing the function.
Observe the failure or error message.
Now, run a similar SQL query (with multiple JOINs) directly in the SQL editor (outside of the function).
Observe that the query executes successfully.
## Expected behavior
SQL functions containing multiple JOIN operations should execute without errors, just as they do when run outside of a function.

## Screenshots
(Attach any screenshots or error messages you might have here.)

##System information
OS: [Your Operating System, e.g. macOS]
Browser (if applies): [Your Browser, e.g. Chrome]
Version of supabase-js: [Your version, e.g. 6.0.2]
Version of Node.js: [Your Node.js version, e.g. 10.10.0]
Additional context
This issue hinders the creation of more complex SQL functions within Supabase, limiting the flexibility and capabilities for developers.

**Comment by GaryAustin1** [comment]
How do you execute the function and what is the error?
The SQL editor should just be running Postgres SQL with no "Supabase" specifics unless it is a syntax error or requires superuser, which would also apply to the joins directly.

**Comment by Slyracoon23** [comment]
![image](https://github.com/supabase/supabase/assets/33297016/ac80141c-bd22-424e-b072-05e851ae004c)
This is when I want to create the function.

![image](https://github.com/supabase/supabase/assets/33297016/57867f9f-30db-40ac-988e-a07aa2ea7ca6)
This works

**Comment by Slyracoon23** [comment]
Interesting. Are you connecting directly to the Postgres. @GaryAustin1  will see if that is what is causing the issues

**Comment by GaryAustin1** [comment]
I ran it in both the SQL editor and my IDE with Datagrip (which gives more detailed error messages like the one shown.  Both worked with the quotes.  It is a semi-reserved word according the the Postgres docs, but only in certain cases.  So putting it in double quotes makes sure to say it is a name.

**Comment by Slyracoon23** [comment]
That solved it! I changed to ` "timestamp" TIMESTAMP `

Might checkout Datagrip too

**Comment by GaryAustin1** [comment]
DBeaver is another Database IDE people seems to use alot and is free.
