### ISSUE TITLE
Boolean Column Incorrectly Defaults to true Despite Setting Default Value to false in Supabase

### ISSUE THREAD

**Issue by SamuraiT** [supabase/supabase#17836]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to set the default value of a Boolean column in Supabase to false, it unexpectedly defaults to true. Despite attempting various inputs to set it to false, such as false, FALSE, and (FALSE), the default value remains true.

## To Reproduce

1. Go to Supabase dashboard.
2. Navigate to the relevant table.
3. Try to modify the Boolean column by setting its default value to false.
4. Add a new row to the table.
5. Observe that the default value for the Boolean column is set to true instead of false.

## Expected behavior

When setting the default value of the Boolean column to false, new rows added should have their respective Boolean value set to false by default.

## System information

- OS: macOS
- Version of supabase-js: latest
- Version of Node.js: 18

## Additional context

This behavior seems inconsistent with expected database functionality, as setting default values should reflect accurately in the data entries. It's essential for the platform to respect the desired default settings to prevent data inconsistencies.

**Comment by shareef99** [comment]
I am able to reproduce the bug.

**Comment by ivasilov** [comment]
Fixed by https://github.com/supabase/supabase/pull/17844.

**Comment by SamuraiT** [comment]
thank you !
