### ISSUE TITLE
React-Native (Expo) Error: URL.hostname is not implemented, js engine: hermes

### ISSUE THREAD

**Issue by Crael94** [supabase/supabase#17834]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm facing an issue when trying to use Supabase in my React Native application with the Hermes engine enabled. Every time I use Supabase functionality, I encounter the following errors:
`ERROR Error: URL.hostname is not implemented, js engine: hermes
`

and this

```
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

At the moment I try to use Supabase instance I have this error.

Here is how I create my Supabase instance:

```
import { createClient, SupabaseClient } from '@supabase/supabase-js';

const supabaseUrl: string = 'https://ufrjvp...c.supabase.co';
const supabaseKey: string = 'eyJ...WBU';
const supabase: SupabaseClient = createClient(supabaseUrl, supabaseKey);

export default supabase;
```

## To Reproduce

Here is a function I wan't to use:

```
const forgotPassword = async (email: string) => {
    const { error } = await supabase.auth.resetPasswordForEmail(email);
    if (error) throw error;
  };
```

If I don't use it my app works well.

According to this issue #8464 I try to import `react-native-url-polyfill` but it just add more error:
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

## System information

- OS: macOS
- "@supabase/supabase-js": "^2.37.0",
- "expo": "~49.0.10",
- "react": "18.2.0",
- "react-native": "0.72.5",
- "react-native-url-polyfill": "^2.0.0"

Please if someone can help me with this !

Thanks

**Comment by armyofda12mnkeys** [comment]
Have the same issue. I was following this tutorial by Supabase (https://www.youtube.com/watch?v=vojHmGUGUGc) and the last step is adding Supabase to Google Auth. Wondering if anyone solved?

I thought maybe the Youtube tutorial didn't mention that need to install maybe this:
`npx expo install react-native-url-polyfill; `
In addition to what he installed:
`npx expo install @react-native-async-storage/async-storage @supabase/supabase-js`
But that didn't help

**Comment by armyofda12mnkeys** [comment]
Hmmm, I manually uninstalled the app from within the android emulator. 
and re-ran the 'npx expo run:android'. I think it worked after that.

**Comment by encima** [comment]
If this issue still occurs for people after trying the workaround please let us know. This seems like a React issue or an issue with how the bundle and install is made so I will close this for now.

**Comment by faiqahmed02** [comment]
my package.json

 "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-brands-svg-icons": "^6.4.2",
    "@fortawesome/free-regular-svg-icons": "^6.4.2",
    "@fortawesome/free-solid-svg-icons": "^6.4.2",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-picker/picker": "2.4.10",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.14",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^1.9.7",
    "@stripe/stripe-js": "^3.0.0",
    "@stripe/stripe-react-native": "^0.37.0",
    "expo": "~49.0.15",
    "expo-camera": "~13.4.4",
    "expo-file-system": "~15.4.5",
    "expo-gl": "~13.0.1",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-location": "~16.1.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-three": "^7.0.0",
    "firebase": "^10.8.0",
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.7.0",
    "react": "18.2.0",
    "react-firebase-hooks": "^5.1.1",
    "react-native": "0.72.10",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.7.1",
    "react-native-paper": "^5.11.1",
    "react-native-purchases": "^7.22.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-sectioned-multi-select": "^0.10.0",
    "react-native-svg": "13.9.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-redux": "^8.1.3",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "three": "^0.145.0",
    "typescript": "^5.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/three": "^0.161.2"
  },
  "private": true
}
![Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 22 25 02](https://github.com/supabase/supabase/assets/83992708/fb2c3334-8fdc-44a5-b530-f4c3c2e40d6e)

I am getting Error: URL.protocol is not implemented, js engine: hermes in my expo project

**Comment by encima** [comment]
> Hmmm, I manually uninstalled the app from within the android emulator. and re-ran the 'npx expo run:android'. I think it worked after that.

@faiqahmed02 did you try the above recommendation?

**Comment by faiqahmed02** [comment]
No, but I Tried deleting the node_modules and package-lock, It Still did not work for me so I upgraded the packages after that issue was resolved.

**Comment by stas44812** [comment]
> my package.json
> 
> "version": "1.0.0", "main": "node_modules/expo/AppEntry.js", "scripts": { "start": "expo start", "android": "expo run:android", "ios": "expo run:ios", "web": "expo start --web" }, "dependencies": { "@babel/plugin-proposal-export-namespace-from": "^7.18.9", "@expo/vector-icons": "^13.0.0", "@fortawesome/fontawesome-svg-core": "^6.4.2", "@fortawesome/free-brands-svg-icons": "^6.4.2", "@fortawesome/free-regular-svg-icons": "^6.4.2", "@fortawesome/free-solid-svg-icons": "^6.4.2", "@fortawesome/react-native-fontawesome": "^0.3.0", "@react-native-async-storage/async-storage": "1.18.2", "@react-native-picker/picker": "2.4.10", "@react-navigation/drawer": "^6.6.6", "@react-navigation/native": "^6.1.14", "@react-navigation/stack": "^6.3.20", "@reduxjs/toolkit": "^1.9.7", "@stripe/stripe-js": "^3.0.0", "@stripe/stripe-react-native": "^0.37.0", "expo": "~49.0.15", "expo-camera": "~13.4.4", "expo-file-system": "~15.4.5", "expo-gl": "~13.0.1", "expo-image-picker": "~14.3.2", "expo-linear-gradient": "~12.3.0", "expo-location": "~16.1.0", "expo-splash-screen": "~0.20.5", "expo-status-bar": "~1.6.0", "expo-three": "^7.0.0", "firebase": "^10.8.0", "firebase-admin": "^12.0.0", "firebase-functions": "^4.7.0", "react": "18.2.0", "react-firebase-hooks": "^5.1.1", "react-native": "0.72.10", "react-native-gesture-handler": "~2.12.0", "react-native-gifted-chat": "^2.4.0", "react-native-keyboard-aware-scroll-view": "^0.9.5", "react-native-maps": "1.7.1", "react-native-paper": "^5.11.1", "react-native-purchases": "^7.22.0", "react-native-reanimated": "~3.3.0", "react-native-reanimated-carousel": "^3.5.1", "react-native-safe-area-context": "4.6.3", "react-native-screens": "~3.22.0", "react-native-sectioned-multi-select": "^0.10.0", "react-native-svg": "13.9.0", "react-native-url-polyfill": "^2.0.0", "react-redux": "^8.1.3", "redux-persist": "^6.0.0", "redux-thunk": "^2.4.2", "three": "^0.145.0", "typescript": "^5.1.3" }, "devDependencies": { "@babel/core": "^7.20.0", "@types/three": "^0.161.2" }, "private": true } ![Simulator Screenshot - iPhone 15 Pro - 2024-03-18 at 22 25 02](https://private-user-images.githubusercontent.com/83992708/313777924-fb2c3334-8fdc-44a5-b530-f4c3c2e40d6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyODEyOTMsIm5iZiI6MTcxMjI4MDk5MywicGF0aCI6Ii84Mzk5MjcwOC8zMTM3Nzc5MjQtZmIyYzMzMzQtOGZkYy00NGE1LWI1MzAtZjRjM2MyZTQwZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDAxMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjY2YwNmIzMjA4YzVhZDg4MzBiZjA2YjYzYzAyMjM3NmM5ZWFlNTVkYTVkYmMwNjk3YmNmN2NhZTU4MWQ4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VDg3BxpRNPtnPfbYYlv4A4wcgAJ1pFNOH2tmqPkLRKc)
> 
> I am getting Error: URL.protocol is not implemented, js engine: hermes in my expo project

Hey man, did you fix it?

**Comment by krishna1r** [comment]
@faiqahmed02 what are the packages did you upgraded

**Comment by wallynm** [comment]
Still having this issue, installing the package doesnt solved my case.
When i disable the supabase packages everything works.

**Comment by durango** [comment]
You will most likely need a polyfill for this issue:

```sh
npm i react-native-url-polyfill
```

Place this in the same file as your supabase client. If this does not work, you may need to explicitly call the polyfill in the same file (there's an exposed/public function in the library).

```js
import 'react-native-url-polyfill/auto';
```

**Comment by shrikulk83** [comment]
> You will most likely need a polyfill for this issue:
> 
> ```shell
> npm i react-native-url-polyfill
> ```
> 
> Place this in the same file as your supabase client. If this does not work, you may need to explicitly call the polyfill in the same file (there's an exposed/public function in the library).
> 
> ```js
> import 'react-native-url-polyfill/auto';
> ```
> 
> Example with the exposed function:
> 
> ```js
> import { Platform } from 'react-native';
> import { setupURLPolyfill } from 'react-native-url-polyfill';
> 
> if (Platform.OS !== 'web') {
>   setupURLPolyfill();
> }
> ```

This solution worked like magic, thanks a ton

**Comment by Craigy101** [comment]
Adding import 'react-native-url-polyfill/auto';

To the top of the supabase client file helped solve the problem for me

import 'react-native-url-polyfill/auto';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl  = process.env.EXPO_PUBLIC_SUPABASE_URL!;
const supabaseAnon = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnon, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
