### ISSUE TITLE
Null values cannot be imported via CSV into Date or Time type columns

### ISSUE THREAD

**Issue by 415matt** [supabase/supabase#17835]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Previously, Supabase allowed null values to be imported into Date/Time type columns via csv simply by not specifying any data, eg `,,`.
Unfortunately this feature seems to no longer work.

## To Reproduce
1. Set up a table with a time type column and allow nullable.
![image](https://github.com/supabase/supabase/assets/22831508/215dffcd-9d6c-47e0-b016-567b0afd7e2c)

2. Select "import data via csv" and paste in a row with a null value
![image](https://github.com/supabase/supabase/assets/22831508/8d3aa24f-a568-4269-af10-6197b5061866)

## Expected behavior
The row is inserted with the time type column containing Null.

## Actual Behavior
The following error is raised: `Failed to import data: Failed to run sql query: invalid input syntax for type time: "" `

## Reproducibility
At least 2 other people have voiced this bug on discord: 
- https://discord.com/channels/839993398554656828/1155138294003273768
- https://discord.com/channels/839993398554656828/1154385685881561118

## Additional context

Current Workaround:
- set date/time columns to text
- import csv
- convert empty strings in column to NULL
- change column back to date/time

**Comment by ishita2411** [comment]
Hi, I would like to take this issue. This will be my first contribution. Can someone please assign this to me? I will get started on working on this.

**Comment by GaryAustin1** [comment]
The Supabase devs have said here there is no assign, just go for it if you think you can.

**Comment by saltcod** [comment]
What @GaryAustin1 said @ishita2411 !   Go for it, thanks!

**Comment by 415matt** [comment]
Was this fixed? I'm no longer seeing issues on my end 👍

**Comment by GaryAustin1** [comment]
I'm going to close this based on the last comment.
If it is still open then please feel free to ask for it to be reopened.

**Comment by JBhrayn** [comment]
@GaryAustin1 please reopen this issue. Apparently, it hasn't been resolved yet. 
![supabasebug](https://github.com/supabase/supabase/assets/110586557/7e6efbea-797e-45c1-8dbc-0ed5e3ffe835)

**Comment by codybrom** [comment]
> @GaryAustin1 please reopen this issue. Apparently, it hasn't been resolved yet. ![supabasebug](https://private-user-images.githubusercontent.com/110586557/296824030-7e6efbea-797e-45c1-8dbc-0ed5e3ffe835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzkwNjAsIm5iZiI6MTcwNTkzODc2MCwicGF0aCI6Ii8xMTA1ODY1NTcvMjk2ODI0MDMwLTdlNmVmYmVhLTc5N2UtNDVjMS04ZGJjLTBlZDVlM2ZmZTgzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxNTUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjk2NDY3NjJiZmVjYzdhMzNhNzczYjcxNWM0ZjZlOTBjZGFiMWZiMGQ0ZGQzYmZjNzJmOGI5NWNiMmExZjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HdHXh-75j29w-ciUes2U5e-CDvIGqQD2ZXQQKbZBpQ8)

+1 to this issue. Couldn't figure out why it wasn't working and found my way here.

**Comment by marccharton** [comment]
the same with dates here 👋 

# Examples 

## With NULL
![image](https://github.com/supabase/supabase/assets/3276889/91fe8da3-93f6-4b72-9c2a-f4b53a1e6c23)
![image](https://github.com/supabase/supabase/assets/3276889/1e748183-a5a9-4f46-ba39-6ad01b7c688a)

## With {nothing}
![image](https://github.com/supabase/supabase/assets/3276889/6ccac8d6-5b12-47b0-8332-f5a02a8e2bc4)
![image](https://github.com/supabase/supabase/assets/3276889/d3fbfc74-df4e-441b-8ea2-cffb7647b8ca)

## With  null
There's no way to import the "null" value to me
![image](https://github.com/supabase/supabase/assets/3276889/473d40cd-3b50-4f82-a9b4-c4a4c4e91bc0)

# Configuration
Nullable is activated 😄 
![image](https://github.com/supabase/supabase/assets/3276889/d088468a-877c-4be3-92d2-bd722958cbb8)

**Comment by dragonworx** [comment]
Any news on this? Still a blocker for basic CSV data importing, which should be a pretty common task.

f it's been resolved can anyone pls list the versions for either npm packages and/or docker images?

**Comment by qispark** [comment]
I'm afraid that I'm still encountering this issue:
<img width="366" alt="Screenshot 2024-04-17 at 9 31 43 am" src="https://github.com/supabase/supabase/assets/31749903/97824dd4-2132-41f3-b32a-96242c6a49f3">

My steps to repro:
1. Create table with timestamp column, ensure it is nullable
2. Upload CSV which contains `NULL` for the timestamp column

**Comment by ethicnology** [comment]
I had the same problem, after trying with `null` and `NULL`, seems to work with an empty string `''` as value

**Comment by FakeJoe** [comment]
Same issue, I migrating from MSSQL to Supabase and I copied results directly from SQL Management Studio (SELECT statement view, "Copy with headers" action on a data).
Overcame this issue by replacing all "NULL" values in the result set with nothing via notepad. It works, but it would be nice if it also works with NULL values written explicitly.

**Comment by JBhrayn** [comment]
@GaryAustin1 Just wondering if this should be reopened. Thanks!
