### ISSUE TITLE
Supabase is unbearably slow the last few days

### ISSUE THREAD

**Issue by Empirome** [supabase/supabase#17846]
Not sure if it's just me but Supabase performance has really been annoying for a few days. It seems that every fifth click seems an eternity to process, whether it's creating a new table, running a query. And when it happens i usually see the error message "failed to fetch data". Running the query a second time and I see the results in under a second.

**Comment by saltcod** [comment]
Hey @Empirome — mind submitting a support ticket for this? We can see if there's something up with your instance.  Nothing's really changed lately on a more global level to have caused this.

**Comment by Empirome** [comment]
Thank you for your quick response. How can I submit one?

**Comment by Empirome** [comment]
I'm giving up on Supabase. It's become a nightmare. Simple queries run over a minute. Yes, I'm on the free plan but how do I know it's better when I pay for it?
