### ISSUE TITLE
 Unsupported scheme "npm" for module

### ISSUE THREAD

**Issue by Jonatthu** [supabase/supabase#17891]
Does edge function support this?
{
  "imports": {
    "lodash": "npm:lodash@^4.17"
  }
}

**Comment by saltcod** [comment]
Need some more detail to be able to help with this one @Jonatthu

**Comment by encima** [comment]
Support for npm modules was added during Launch Week X, read the full post [here](https://supabase.com/blog/edge-functions-node-npm) or checkout the [video](https://youtu.be/eCbiywoDORw)
