### ISSUE TITLE
Odd Looking NavBar Button color when the screen size is reduced (hamburger)

### ISSUE THREAD

**Issue by Pavan-Rajesh** [supabase/supabase#17903]
# Improve documentation

## Link 
https://supabase.com/

Add a link to the page which needs improvement (if relevant)

## Describe the problem
The hamburger icons color is looking odd
Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement
The color of it should be green or white
![supabasecolor2](https://github.com/supabase/supabase/assets/90332218/8d8b82b4-7028-4fdb-a442-5f65be451698)

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by PavanaSakethaRam** [comment]
I would like to work on this issue. Can u pl assign this to me

**Comment by MildTomato** [comment]
@PavanaSakethaRam feel free to submit a PR, we don't assign issues currently.

**Comment by shishiro26** [comment]
Is this issue still open , I would like to work on this
