### ISSUE TITLE
Filter stuck with deleted column

### ISSUE THREAD

**Issue by gusvd** [supabase/supabase#17964]
## Describe the bug

There's a small bug on Supabase's UI where if I delete a column that happened to be used to Sort or Filter the whole table UI becomes inaccessible.

There's no way to reset the filters. And the only workaround I found was to create a new column using the exact same name as the one used by the ghost filter and remove it from the filter before deleting it again. That assumes you remember which column was used in the filter, the filter UI doesn't show it after you delete the column.

## To Reproduce

Order or Filter by a column
Delete the column

## Expected behavior

I'd expect it to remove the Order or Filter automatically once the column is deleted.
Alternatively, a button to reset the filter/order would help.

**Comment by Manuel-DaSilva** [comment]
You can delete the filter (which should appear blank if the column does not exist) and click the "Apply Filter" button as a workaround for the bug

**Comment by joshenlim** [comment]
Hey there! I've just checked on production and this seems to have been fixed now!

https://github.com/supabase/supabase/assets/19742402/729cf917-c313-4522-8ee5-6557a508e940

I'll go ahead to close this issue but please feel free to let us know otherwise! 🙏
