### ISSUE TITLE
Table editor column input field got blocked by suggested expression icon

### ISSUE THREAD

**Issue by likendev** [supabase/supabase#17969]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In table editor, create new table, the table column input field for default value got blocked by suggested expression icon. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Table Editor
2. Click on New Table
3. Scroll down to the column settings
4. Notice under the default column, type a longer text until the suggested expression icon blocking the input text.

## Expected behavior

The suggested expression icon inside the input field should not block the input text.

## Screenshots

![image](https://github.com/supabase/supabase/assets/15458805/02a544e2-5198-4b01-8b06-2850b21fd06b)

## System information

- OS: Windows
- Browser (if applies): Edge

**Comment by likendev** [comment]
![image](https://github.com/supabase/supabase/assets/15458805/0f31424c-fb36-480e-a8b0-6f5cd89fffaf)

#17970

**Comment by encima** [comment]
Closing this as it has been merged now.
