### ISSUE TITLE
Error: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by sanghanihimanshu** [supabase/supabase#17971]
Error: self-signed certificate in certificate chain
 Drizzle+super base

**Comment by kevcodez** [comment]
Hi there, have you followed https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-drizzle?

Would need some additional info/reproducible example to help here

**Comment by sanghanihimanshu** [comment]
Complete 💯

**Comment by HigherOrderLogic** [comment]
Hi, sorry for necro-post this issue but did you find any solution for this one?

I'm using `db0` with `pg` underneath to connect, but I always get `SELF_SIGNED_CERT_IN_CHAIN`:

```ts
import type { Connector, Database } from 'db0'
import { createDatabase } from 'db0'
import pgConnector from 'db0/connectors/postgresql'
import type { Client as PgClient } from 'pg'

export type PgDatabase = Database<Connector<PgClient>>

let pgInstance: PgDatabase

export function useUsersDb(): PgDatabase {
  if (!pgInstance) {
    // eslint-disable-next-line node/prefer-global/process
    const pgUrl = globalThis.process?.env?.POSTGRES_URL

    if (!pgUrl) {
      throw new Error('No Postgres url environment variable')
    }
    pgInstance = createDatabase(pgConnector({ connectionString: pgUrl, ssl: false }))
  }

  return pgInstance
}
```

**Comment by marcospgp** [comment]
> Hi, sorry for necro-post this issue but did you find any solution for this one?
> 
> I'm using `db0` with `pg` underneath to connect, but I always get `SELF_SIGNED_CERT_IN_CHAIN`:
> 
> import type { Connector, Database } from 'db0'
> import { createDatabase } from 'db0'
> import pgConnector from 'db0/connectors/postgresql'
> import type { Client as PgClient } from 'pg'
> 
> export type PgDatabase = Database<Connector<PgClient>>
> 
> let pgInstance: PgDatabase
> 
> export function useUsersDb(): PgDatabase {
>   if (!pgInstance) {
>     // eslint-disable-next-line node/prefer-global/process
>     const pgUrl = globalThis.process?.env?.POSTGRES_URL
> 
>     if (!pgUrl) {
>       throw new Error('No Postgres url environment variable')
>     }
>     pgInstance = createDatabase(pgConnector({ connectionString: pgUrl, ssl: false }))
>   }
> 
>   return pgInstance
> }

I'm getting the same issue, unable to connect to supabase with SSL enabled using drizzle
