### ISSUE TITLE
Wrong navigation link when click on Open Collective Profile item

### ISSUE THREAD

**Issue by hieuwu** [supabase/supabase#17977]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Wrong navigation link when click on Open Collective Profile item

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to  https://supabase.com/open-source
2. In Sponsored Project section, click on Open Collective Profile item
3. The browser open new tab with https://github.com/PostgREST/postgrest

## Expected behavior

It should open open collective profile url of Supabase

## Screenshots

<img width="720" alt="Screenshot 2023-10-06 at 17 21 35" src="https://github.com/supabase/supabase/assets/43868345/3494accf-5880-4f2c-ac0b-c839f50c3105">
<img width="720" alt="Screenshot 2023-10-06 at 17 22 22" src="https://github.com/supabase/supabase/assets/43868345/6aaa2332-4590-4d91-aa6a-fbcc9e0c6511">

## System information

- OS: macOS
- Browser (if applies) chrome

**Comment by shishiro26** [comment]
I would like to work on this ! can u please assign it to me
