### ISSUE TITLE
Realtime timestamp different format

### ISSUE THREAD

**Issue by dragarcia** [supabase/supabase#18]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
https://github.com/PostgREST/postgrest/issues/177

**Comment by kiwicopple** [comment]
good catch @dragarcia - it looks like PostgREST isn't actually adding the "T" based on the linked issue perhaps they have added it later in another issue? Couldn't find it from an initial skim

Either way, we need to be consistent. I think the best option is to remap this in the `ChangeMapper` of the JS client.

**Comment by kiwicopple** [comment]
@dragarcia just want to double check - this one is solved right? Can you please close if no more work required?

**Comment by dragarcia** [comment]
Tested with 0.1.24 and everything looks right. Proceeding to close this.
