### ISSUE TITLE
two menu items are referring to same link (in supabase docs)

### ISSUE THREAD

**Issue by Alirezaaraby** [supabase/supabase#18019]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This bug is about a tiny bug in the documentation in the functions part.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/functions/examples/screenshots
2. Have a look at the sidebar menu
3. Then you can see that the `browserless.io` and `Taking Screenshots with Puppeteer` on the menu are highlighted (like the below image).

![image](https://github.com/supabase/supabase/assets/45128978/50ad2e87-2a97-4cad-8994-5e07b3a4e9c9)

## Expected behavior

each of the items in the menu should connect to different links.

## Screenshots

![image](https://github.com/supabase/supabase/assets/45128978/05987657-5a28-46a4-b3a8-c54bdaecefda)

## System information

- OS | Windows 10 Version 22H2 (Build 19045.3448)
- Google Chrome | 117.0.5938.149 (Official Build) (64-bit) (cohort: M117 Rollout)

**Comment by mirchandani-mohnish** [comment]
Hey, 
I am a new contributer, this could be a good first issue for me. Can I give it a shot?

**Comment by shishiro26** [comment]
Hi @Alirezaaraby 
I'm wondering if you could please provide more information about which page you think the browserless.io link should direct to.

One option would be to direct the link to the Browserless.io documentation: https://docs.browserless.io/. This is because the Taking Screenshots with Puppeteer example on the Supabase documentation page is already using the Browserless.io API.

Another option would be to create a new page on the Supabase documentation website that specifically covers using the Browserless.io API with Supabase. This page could include the existing Taking Screenshots with Puppeteer example, as well as additional examples and information.
Please let me know your thoughts.

**Comment by M0hitReddy** [comment]
The "Browserless.io" and " Taking Screenshots with Puppeteer " are referring to same link .that is " [https://supabase.com/docs/guides/functions/examples/screenshots](https://supabase.com/docs/guides/functions/examples/screenshots) ".

**Comment by Alirezaaraby** [comment]
Thanks to @M0hitReddy for summarizing the issue.

**Comment by Alirezaaraby** [comment]
> Hey, I am a new contributer, this could be a good first issue for me. Can I give it a shot?

I think first, a maintainer of this project should provide a link for `Browserless.io` menu item or decide whether it should be there or not, and then you can go through it

**Comment by Alirezaaraby** [comment]
> Hi @Alirezaaraby I'm wondering if you could please provide more information about which page you think the browserless.io link should direct to.
> 
> One option would be to direct the link to the Browserless.io documentation: https://docs.browserless.io/. This is because the Taking Screenshots with Puppeteer example on the Supabase documentation page is already using the Browserless.io API.
> 
> Another option would be to create a new page on the Supabase documentation website that specifically covers using the Browserless.io API with Supabase. This page could include the existing Taking Screenshots with Puppeteer example, as well as additional examples and information. Please let me know your thoughts.

first, two menu options could not refer to the same link and I think it's better to remove this item from the menu,

**Comment by thorwebdev** [comment]
This is intentional. This specific docs page covers both these topics. The reason it has different menu items is so that folks who are searching for different things still find their relevant content.
