### ISSUE TITLE
Web dashboard fails to open a dialogue to edit a database column – send api request to /custom-hostname instead

### ISSUE THREAD

**Issue by SmebdyNbdy** [supabase/supabase#18025]
# Bug report

- [+] I confirm this is a bug with Supabase, not with my own application. 
- [+] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using the free plan of Supabase Dashboard, and I have never used changed it to paid plan, and so I have never used a custom domain for my project. The problem is, in the database editor, when I try to edit a column (not the whole table), the dialogue does not open. I checked the web inspector, and it turns out that the browser sends a request to `https://api.supabase.io/v1/projects/MYPROJECTID/custom-hostname`
which obviously fails.

I've tried anonymous browsing mode, using another browser, signing in again, and nothing seems to help. Same goes for "new column" button, which fails and sends the same request.

## To Reproduce

1. Go to "Databases" in a project on the free plan
2. Click on the columns button of any table in the public schema
3. Click "New column" or a pencil icon on an existing column

I've created a new profile on supabase.com, created a new organization and project there, and the bug reproduces

## Expected behavior

A dialogue should open on the right allowing me to edit the table

## System information

- OS: macOS 13
- Browser: chrome 177, safari 16.1
- Version: current dashboard version available

**Comment by SmebdyNbdy** [comment]
Apparently, the request is to /custom-domain is not the issue. I have been able to open the dialogue in safari, but the results are inconsistent and it is unclear what can affect the behaviour. In chrome, however, the dialogue didn't open even once.

**Comment by GaryAustin1** [comment]
Try hard refreshing your browser on that page.  I saw the issue, but after ctrl-f5 seems to be working.

**Comment by saltcod** [comment]
I think this was related to a bug from late last week. Closing, but please reopen if this persists for you.
