### ISSUE TITLE
Foreign Data Wrappers with UPDATE'able foreign tables not working and crashing studio

### ISSUE THREAD

**Issue by Unkn0wn0x** [supabase/supabase#18022]
# Bug report

- [/] I confirm this is a bug with Supabase, not with my own application. 
- [/] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Hello there,

I tried to work with supabase wrappers, especially with the stripe wrapper and I'm running into some issues.

First of all, I've tried to setup the striper wrapper through the guided tour under https://supabase.com/dashboard/project/myproject/database/wrappers.

Everything works fine so far until I want to update some data (which also is allowed to be [updated](https://supabase.com/docs/guides/database/extensions/wrappers/stripe#creating-foreign-tables) and **should** have a `rowid_column` reference). I've created all tables which are available in the guided tour. Lets use `stripe_dev.customers` as an example.

I'm able to read the data in my supabase table (`stripe_dev.customers`). If I want to update the data like following:
`UPDATE stripe_dev.customers SET description = 'SPDW API Test' WHERE id ='cus_ABC123';`

I'm getting the error, that there's no `rowid_column` set for this table. If I check the docs [here](https://supabase.com/docs/guides/database/extensions/wrappers/stripe#customers) and [here](https://supabase.github.io/wrappers/stripe/#customers) (which are almost the same), there's the `rowid_column` referenced if created manually. 

So I think that the guided tour is missing to create the `rowid_column` reference for UPDATE'able foreign tables.

Now I removed the `customers` foreign table from the Foreign Data Wrappers and tried to add it manually again (from the docs mentioned above):
```
create foreign table stripe.customers (
  id text,
  email text,
  name text,
  description text,
  created timestamp,
  attrs jsonb
)
  server stripe_dev_server
  options (
    object 'customers',
    rowid_column 'id'
  );

```

Now I'm able to update the data also within stripe, cool so far. But now my Forgein Data Wrappers Stripe Section is buggy and does not allow any modification and sometime crashes with a client side error in supabase studio:
`Application error: a client-side exception has occurred (see the browser console for more information).`

## Expected behavior
- The missing `rowid_column` reference is created also within the guided tour.
- Manually created foreign tables are working within the Foreign Data Wrappers section.
- Supabase Studio does not crash anymore if modifying the data.

**Comment by Kfelts** [comment]
I am experiencing this exact same error. I'm using the hosted Supabase and every time I try to access api documentation it's crashing.
