### ISSUE TITLE
Authentication redirect url for mobile apps?

### ISSUE THREAD

**Issue by farzd** [supabase/supabase#1802]
# Bug report

## Describe the bug

Redirect URL should allow for alternative protocols to facilitate opening of mobile apps, e.g: expo/react native 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'supabase app'
2. Click on 'Authentiction > settings'
3. Change site url to 

## Expected behavior

Allows for alternative protocols for redirect urls

## Screenshots

![image](https://user-images.githubusercontent.com/1423413/120526076-b90a3580-c3d0-11eb-95f3-cc7eacb70222.png)

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari] chrome/expo ?
- Version of supabase-js: [e.g. 6.0.2]:    @supabase/supabase-js: ^1.13.1
- Version of Node.js: [e.g. 10.10.0]: v14

**Comment by kiwicopple** [comment]
Thanks for the bug report @farzd 🙏 

As a temporary workaround, you can list the expo URL in the `Additional Redirect URLs` section, then you can use the `redirectTo` option listed here: https://supabase.io/docs/reference/javascript/auth-signin

![image](https://user-images.githubusercontent.com/10214025/120586614-6da26680-c466-11eb-90ff-2daefc57bda6.png)

**Comment by Saunved** [comment]
@kiwicopple I'd like to report that the additional redirect URLs don't actually work (or they haven't worked for me in the tests that I tried). Could someone confirm that this actually works for them?
Thanks!

**Comment by farzd** [comment]
I haven't tried it, i just set the primary url to be my website and put some JS to get the token and forward to expo etc

```
<html>
  <body>
    <script>
    const url = window.location.href;
    const split = url.split('#');    
    const queryP = split[1];    
    const redirect = split[0].split('/?redirect=')[1];
    window.location.href = redirect + '?' + queryP;
    </script>
  </body>
</html>

```
so the redirect url would look something like this, that opens expo
```        'http://www.seemapp.co.uk/?redirect=exp://127.0.0.1:19000#access_token=xxxx&expires_in=3600&refresh_token=xxxx&token_type=bearer&type=magiclink';```

**Comment by awalias** [comment]
@Saunved could you please open an issue with repro instructions in https://github.com/supabase/gotrue and we'll take a look at your issue

@farzd does the workaround above work for you? I'm closing this issue and I've opened an issue for scheme extension in the gotrue repo so we can track it there:  https://github.com/supabase/gotrue/issues/117
