### ISSUE TITLE
Error in generated documentation for each endpoint API in Filtering => Array

### ISSUE THREAD

**Issue by foufrix** [supabase/supabase#18036]
# Improve documentation

The documentation is not up to date on the API page of one's database using JS SDK.

You can see at Filtering : 
![image](https://github.com/supabase/supabase/assets/16646581/0410217b-c19c-441d-8cb9-e6697857a1ef)

Unfortunately the `.cs` and `.cd` does not exist from the import (thank you Typescript)

## Link 

https://supabase.com/dashboard/project/projectid/api?resource=tablename

## Describe the problem

The documentation is not up to date and is referring to old methods that does not exist anymore. New methods are `contains` and `containedBy` (I think?)

## Describe the improvement

For Array filtering, change to methods up to date.

## Additional context

Don't hesitate to ask if you need more info.

**Comment by encima** [comment]
Good catch, thanks for this!

`cs` and `cd` are exposed but they are `contains` and `containedBy` so we should update the generation, yep.
