### ISSUE TITLE
Unable to generate access token or submit issues to Supabase support

### ISSUE THREAD

**Issue by TheKeveloper** [supabase/supabase#18048]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm not sure if this is the right place to submit this bug, but part of the bug is that I cannot submit issues using the [Supabase support dashboard](https://supabase.com/dashboard/support/new) so this seemed like the next best place.

I discovered this issue when attempting to generate a new access token. When attempting to generate a new token, I enter the name of the new token, then click "Generate token" and nothing seems to happen.

I took a look at the chrome network calls and it doesn't seem like all that happens after clicking "Generate Token" is a series of GET requests.

Existing access tokens seem to work fine and I was able to revoke an access token earlier.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/dashboard/account/tokens
2. Click "Generate new token"
3. Enter a name for the token, e.g. "Test Token"
4. Click "Generate token"

Similar behavior when attempting to submit a support issue.

## Expected behavior

A new access token is generated.

## Screenshots

Screenshot of network tab after making request.
<img width="1512" alt="Screenshot 2023-10-09 at 1 27 33 PM" src="https://github.com/supabase/supabase/assets/3794259/0a4ad32a-d4e4-4d28-8115-a4d151773d20">

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

I'm using GitHub signin for my Supabase account, so it's possible that this is some sort of auth issue? But I don't see any requests indicating unauthorized, and I was able to revoke a token so this doesn't seem like the likely issue.

Thank you!

**Comment by saltcod** [comment]
Hey there — have you tried logging out/in? You might also want to delete everything in localStorage.

**Comment by TheKeveloper** [comment]
I tried logging out and back in. I'll try clearing local storage, but I did try signing in from Safari instead of Chrome (first time signing in on Safari) and that didn't work either, so I would be a bit surprised if the issue was due to local storage

**Comment by TheKeveloper** [comment]
It looks like this issue has since been resolved!
