### ISSUE TITLE
The save button is disabled even when I want to add the new row into my table

### ISSUE THREAD

**Issue by Pavan-Rajesh** [supabase/supabase#18049]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Sohailsaifi** [comment]
Can you assign this issue to me?

**Comment by Pavan-Rajesh** [comment]
@Sohailsaifi  yes you can work on it

**Comment by GaryAustin1** [comment]
What exactly is the issue?  There was a general issue with the dashboard about 6 hours ago that was resolved.
It involved buttons working.
But you show no example here of what is wrong or what to do to reproduce.

I'm going to close this for now.  If it was not resolved by the bug fix, please supply some of the fields in an issue besides a title.
Thanks
