### ISSUE TITLE
Edge function - 500: Internal Server Error when Calling the Function

### ISSUE THREAD

**Issue by manishionc** [supabase/supabase#18043]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Calling any Edge Function is giving Internal Server Error 500

## To Reproduce
Just create Default  Basic Hello world Edge function and Deploy it . Then Try to Call the function .

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots
![image](https://github.com/supabase/supabase/assets/84983048/88a9e4b4-5136-4d36-8657-5e1531d43f16)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
You are not providing much info here.  What is your code?  What does the function do?  Any errors in the dashboard logs?

You might be better off with this as a discussion or in Discord to get some help before generating a bug report.

**Comment by manishionc** [comment]
> You are not providing much info here.  What is your code?  What does the function do?  Any errors in the dashboard logs?
> 
> You might be better off with this as a discussion or in Discord to get some help before generating a bug report.

The Default Function. Hello is Also giving .
Internal Server Error .
Status code - 500

**Comment by saltcod** [comment]
If you could provide some more info @manishionc that'd be helpful.

**Comment by encima** [comment]
@manishionc Can you also confirm this happens when you disable authentication for the function as well?

**Comment by manishionc** [comment]
The issue is solved . 
It was authenticatation problem .

**Comment by burgmike** [comment]
Are you able to share specifically how you resolved the authentication issue? 
I'm currently experiencing the same problem

Thanks!

**Comment by abid365** [comment]
Anyone encountering this issue, if you want to test your edge function disable the JWT verification ,make the request method from GET to POST, and make the request with a payload. Mine works magically. 
P.S: Don't disable JWT in production.

**Comment by stickey1968** [comment]
Is JWT required in production or can you use Service Role authentication?  I have been getting the 500 error for a couple of weeks. The edge function calls a database function and I can see the log repeatedly authenticating and authorizing.

Our use case is calling Edge from a browser and building JWT might not be possible.
