### ISSUE TITLE
Autoincrement not updating

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase#1804]
# Bug report

## Describe the bug

This _seems to_ have only started occurring in the last couple of days.

When I seed a table during a migration (below), upon insertion the autoincrement id of the table does not seem to trigger. 

The first two `INSERT` calls to this table from the frontend client return a duplicate key error:
```js
{
code: "23505",
details: null,
hint: null,
message: "duplicate key value violates unique constraint \"api_keys_pkey\""
}
```

However, upon the third insert attempt - the row is created successfully.

```pgsql
-- CreateTable
CREATE TABLE api_keys
(
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id     bigint REFERENCES teams ( id ) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
  creator_id  uuid REFERENCES accounts ( id ) ON DELETE CASCADE ON UPDATE CASCADE DEFAULT auth.uid( ),
  token       uuid NOT NULL UNIQUE DEFAULT uuid_generate_v4( ),
  created_at  timestamp WITH TIME ZONE DEFAULT timezone( 'utc'::text, NOW( ) ) NOT NULL,
  updated_at  timestamp WITH TIME ZONE DEFAULT timezone( 'utc'::text, NOW( ) ) NOT NULL,
  disabled_at timestamp WITH TIME ZONE
);

-- InsertInto
INSERT INTO api_keys ( id, team_id, creator_id )
VALUES ( 1, 1, '2bc32eba-533d-42fc-9402-b12b9af79c75' );
INSERT INTO api_keys ( id, team_id, creator_id )
VALUES ( 2, 2, '8cb12f23-533d-4032-ab1d-946d530eda69' );

```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Define a table with an autoincrementing `id` column, followed by two `INSERT` queries to the new table.
2. Execute SQL via the Supabase GUI.
3. Attempt to insert a new row either from the frontend client or direct SQL connection.
4. See `duplicate key value violation` first two attempts and success on the third attempt.

## Expected behavior

Autoincrement should not care how the row is inserted (via Supabase GUI SQL script or remote access).

## Screenshots

![image](https://user-images.githubusercontent.com/65471523/120571092-bc4b0300-c45c-11eb-9f7d-90d0e7949c99.png)

![image](https://user-images.githubusercontent.com/65471523/120570973-9160af00-c45c-11eb-91b9-557a872c60b9.png)

## System information

- OS: `N/A`
- Browser (if applies): `Edge`
- Version of supabase-js: `"@supabase/supabase-js": "^1.13.1"`
- Version of Node.js: `14`

**Comment by soedirgo** [comment]
Hey @prescience-data, identity columns like `id` here are sequences, so if you insert a value manually it'll clash with the sequence (more info [here](https://stackoverflow.com/questions/787722/postgresql-autoincrement)). Unfortunately, AFAIK there is no way for it to detect already existing values (unlike, say, MySQL's auto_increment).

You might consider using `DEFAULT` in place of `1` and `2` above, or alternatively you can sync them after seeding with:
```sql
SELECT setval('api_keys_id_seq', COALESCE((SELECT MAX(id)+1 FROM api_keys), 1), false);
```

**Comment by kiwicopple** [comment]
Yeah I would strongly recommend letting Postgres handle the ID generation. If you plan on doing a lot of this though @prescience-data you can also use a `serial` type, and then you can check the `currval()` of the sequence. Here is a good article on serials: https://www.postgresqltutorial.com/postgresql-serial/

I'll close this for now @prescience-data, but feel free to comment and we can reopen if required.

**Comment by prescience-data** [comment]
Ah, I must have been mistaken that it was working previously and assumed that a `mysql` `auto_increment` style operation was occurring. Thanks for clearing that up!

**Comment by amirhosein5858** [comment]
hi ,i create a table and import data from excel file to it 
culumns are id , name and ...
i set id as identity ,
<img width="634" alt="Screen Shot 2022-03-15 at 3 26 02 AM" src="https://user-images.githubusercontent.com/44944288/158279775-d2ab82b8-dc80-481b-a707-c489c715d6ec.png">

when i want to insert one row (data object without id) i get this error:


`{
    "data": null,
    "error": {
        "message": "duplicate key value violates unique constraint \"workoutDetail_pkey\"",
        "code": "23505",
        "details": "Key (id)=(4) already exists.",
        "hint": null
    }
}`

i have 'X' rows in that table
and every time i try to insert , value of id in "Key (id)=(4) already exists." increased
should i try to insert 'X' times to pass this error... ?

what should i do?

**Comment by steve-chavez** [comment]
@amirhosein5858 Try changing the sequence current value to the max id of your table. Like:

```sql
ALTER SEQUENCE <your_sequence> RESTART WITH 1500 -- 1500 is the max id here;
``` 

You can find your sequence name with:

```sql
select sequence_schema, sequence_name
from information_schema.sequences;
```

It usually contains the table name as a prefix.

**Comment by amirhosein5858** [comment]
> ```sql
> ALTER SEQUENCE <your_sequence> RESTART WITH 1500
> ```

thanks to you
i try `SELECT PG_GET_SERIAL_SEQUENCE('table', 'id');` to find right seq
and then run `ALTER SEQUENCE <your_sequence> RESTART WITH 453 ` as you say and it worked
thank you very much

**Comment by DerekRein** [comment]
If it helps anyone else, make sure to not include your id key on your object before inserting. 
```
var object = { 'id': undefined, 'b': '2', 'c': 3 };
lodash.omit(object, ['id']);
```

**Comment by DerekRein** [comment]
Better to use (select nextval('<table_name>_id_seq'))
