### ISSUE TITLE
Unable to Login to the Dashboard

### ISSUE THREAD

**Issue by conseromarketing** [supabase/supabase#18050]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When navigating to the Dashboard login or trying to login to the SupaBase Dashboard I am getting this error message in the console (no UI errors):

`"message": "No authorization token was found"`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to: https://supabase.com/dashboard/sign-in?
2. Inspect the developer tools of your browser
3. See error in the console and also in the network tab

## Expected behavior

I would expect to see no error or API call the the /projects endpoint and to have the ability to submit my login username and password

## Screenshots
<img width="2560" alt="Screenshot 2023-10-09 at 12 29 28 PM" src="https://github.com/supabase/supabase/assets/21713053/c1e7ca84-9da0-452d-91ff-3cf1a8469441">

<img width="842" alt="Screenshot 2023-10-09 at 12 28 40 PM" src="https://github.com/supabase/supabase/assets/21713053/60b4c712-b132-4e0f-b9d4-0171406561f8">

## System information

- OS: macOS
- Browser: Brave, Chrome, Safari
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Thank you for the help!

**Comment by saltcod** [comment]
Hey there! Have you tried deleting your localStorage items and logging in again?

**Comment by conseromarketing** [comment]
Hi @saltcod, yes and all cookies as well.

**Comment by adobbs** [comment]
Also cannot log in to dashboard using email/pw. 
![400](https://github.com/supabase/supabase/assets/333310/5d5a52ed-e0ca-4dd1-aaae-d21721ce92e8)
![UserObject missing](https://github.com/supabase/supabase/assets/333310/917fac56-8d95-4628-a6e3-ae4dcd307f5d)

**Comment by conseromarketing** [comment]
Here is a quick loom to further illustrate what I am seeing:
https://www.loom.com/share/12c00be8baef40618ed322d1e3fef743?sid=46e0b260-aca0-4883-84f8-f1f5c21a31d3

**Comment by creative-tutorials** [comment]
> Here is a quick loom to further illustrate what I am seeing: https://www.loom.com/share/12c00be8baef40618ed322d1e3fef743?sid=46e0b260-aca0-4883-84f8-f1f5c21a31d3

I'm getting the same thing too, but this only affects when using email and password, not the GitHub sign-in button.

**Comment by viniciusvasti** [comment]
I'm facing the exact same issue

**Comment by SethDamiani** [comment]
I'm also seeing the same issue.

**Comment by pjborowiecki** [comment]
Having the same issue. I tried clearing cookies, cache, different browsers, incognito mode, you name it. It works fine with GitHub, but I am unable to log in or create a new account with email and password. Getting 401 errors in the console, but also "UserObject missing! You should pass a UserObject to getValue()"

![image](https://github.com/supabase/supabase/assets/27385980/ebf7a839-15e6-480a-8996-1597adf1e8a9)

**Comment by creative-tutorials** [comment]
> Having the same issue. I tried clearing cookies, cache, different browsers, incognito mode, you name it. It works fine with GitHub, but I am unable to log in or create a new account with email and password. Getting 401 errors in the console, but also "UserObject missing! You should pass a UserObject to getValue()"
> 
> ![image](https://user-images.githubusercontent.com/27385980/273678283-ebf7a839-15e6-480a-8996-1597adf1e8a9.png)

This feels like a frontend connecting to the backend issue, maybe a change in their APIKEY 🤔

**Comment by pjborowiecki** [comment]
All working again for me

**Comment by creative-tutorials** [comment]
> All working again for me

Its working again, like for real?

**Comment by viniciusvasti** [comment]
> I'm facing the exact same issue

Now working here too

**Comment by conseromarketing** [comment]
Working here now too!

**Comment by creative-tutorials** [comment]
> > I'm facing the exact same issue
> 
> Now working here too

Refresh your browser, It should work now :)
