### ISSUE TITLE
From the Table Editor, the API documentation layout is "broken"

### ISSUE THREAD

**Issue by JulienLecoq** [supabase/supabase#18054]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

From the Table Editor of the Supabase dashboard, the API documentation layout is broken.

## To Reproduce

1. Go to the Supabase dashboard
2. Open the Table Editor
3. Click on the API button in the top right of the page.
4. See the broken layout

ps: I only tried on Brave Browser and Safari

## Expected behavior

The layout should not be broken.

## Screenshots

![api_broken_layout](https://github.com/supabase/supabase/assets/54070985/b5e412f5-3cfa-4111-a4bf-69a2894935e4)

## System information

- OS: macOS 14.0 (Sonoma 23A344)
- Browser: Brave Browser and Safari

**Comment by Prathamk07** [comment]
Cannot reproduce. I think the issue is fixed

**Comment by saltcod** [comment]
Yep fixed yesterday. Sorry about this! Thanks for the report.
