### ISSUE TITLE
Can't create INSERT policy

### ISSUE THREAD

**Issue by alexturpin** [supabase/supabase#1806]
# Bug report

## Describe the bug

I am unable to create new `INSERT` policies. It complains of a missing definition even though it's set.

## To Reproduce

1. Create a new insert policy
2. Enter a definition
3. Click save

## Expected behavior

Policy should be created, instead we get an error asking for a definition or a check.

## Screenshots

<img width="341" alt="firefox_g2zve2JpXr" src="https://user-images.githubusercontent.com/134339/120601235-af57f080-c417-11eb-8c79-00b807d90592.png">

## System information

Firefox 89
Windows 10

## Additional context

Without going to "Advanced" for `INSERT`, you can't actually set a definition ("with check" is the only thing that shows). Related?

**Comment by alexturpin** [comment]
I am trying to allow inserts only by all.

**Comment by kiwicopple** [comment]
Hey @alexturpin - this one is because the Postgres database is expecting a "with check" policy for `inserts`.

If you move your `true` to the `check` field it should pass.

![image](https://user-images.githubusercontent.com/10214025/120642219-330cee00-c4a7-11eb-8afe-3e81c62c3ef4.png)

We realise this policy editor isn't very intuitive - we are actually about to release a new version - should be ready in about week.

I'll close this now, but if you have any other problems feel free to comment and I can reopen.

**Comment by alexturpin** [comment]
@kiwicopple thanks for the quick answer! I was under the impression that it was buggy because I also wasn't able to do an `INSERT` despite the policy. Here's my policy and code:

<img width="348" alt="firefox_ebhWn0lYbx" src="https://user-images.githubusercontent.com/134339/120660485-6030b080-c455-11eb-9458-5a445b2161fa.png">

```
    await supabase.from("mailing_list").insert({
      email: email.trim(),
    })
```

Getting back

```{"hint":null,"details":null,"code":"42501","message":"new row violates row-level security policy for table \"mailing_list\""}```

Can you tell if I'm doing anything obviously wrong? First experience with Supabase but super excited about this project!

**Comment by easy-street** [comment]
> I also wasn't able to do an `INSERT` despite the policy:
> 
> ```
> await supabase.from("mailing_list").insert({
>   email: email.trim(),
> })
> ```
> 
> Getting back
> 
> ```
> {"hint":null,"details":null,"code":"42501","message":"new row violates row-level security policy for table \"mailing_list\""}
> ```

@alexturpin there is a note in the [insert docs](https://supabase.io/docs/reference/javascript/insert#notes) that describes this issue:
> By default, every time you run insert(), the client library will make a select to return the full record. This is convenient, but it can also cause problems if your Policies are not configured to allow the select operation. If you are using Row Level Security and you are encountering problems, try setting the returning param to minimal.

So, two options:
- add a policy allowing `SELECT`
- set the `returning` param to `minimal`:
```
await supabase.from("mailing_list").insert(
  {
    email: email.trim(),
  },
  { returning: "minimal" }
)
```

**Comment by alexturpin** [comment]
Thank you so much @easy-street, totally glossed over that 🤦‍♂️

**Comment by jstansbe** [comment]
I also glossed over this and wasted a bunch of time spinning my wheels... thank goodness I found this issue. I hope more attention can be brought to this "gotcha" detail so others don't go down the same path. Maybe add a warning on the policies section that a table only has an insert setup and this will cause the automatic select (of the inserted row) to be returned.

**Comment by spencerbart** [comment]
Ran into the same problem

**Comment by futbotism** [comment]
I'm having a similar issue, for graphql based requests it says that i am violating RLS policies for row inserts... When i use  `@supabase/supabase-js` lib it works as expected. ive triple checked all my RLS policies.
