### ISSUE TITLE
Add await block to the docs

### ISSUE THREAD

**Issue by creative-tutorials** [supabase/supabase#18096]
# Improve documentation

## Link 

[creating-signed-url](https://supabase.com/docs/reference/javascript/storage-from-createsignedurl?example=create-signed-url-with-download)

[retrieve-public-url](https://supabase.com/docs/reference/javascript/storage-from-getpublicurl)

## Describe the problem

There seems to be a missing await block. When you add the code for the mentioned links, you will receive an error message that says, "Property data does not exist on type".

```tsx
Promise<{ data: { signedUrl: string; }; error: null; } | { data: null; error: StorageError; }>'.
```

## Describe the improvement

Adding the await block to the documentation can resolve this issue and prevent future bugs.

## Additional context

Screenshot of the error

![image](https://github.com/supabase/supabase/assets/68476321/8bdb9ae7-8701-4ee9-8bf5-d0612a8e7aa5)

**Comment by GaryAustin1** [comment]
You are correct on signed URL but GetPublicUrl is just a helper function that does string concatenation and does not make an API call.  So await is not needed for that.

**Comment by creative-tutorials** [comment]
> o await is not needed for that.

Okay, my bad, thanks for letting me know 👍

**Comment by creative-tutorials** [comment]
> You are correct on signed URL but getPublicUrl is just a helper function that does string concatenation and does not make an API call. So await is not needed for that.

Okay, my bad, thanks for letting me know 👍
