### ISSUE TITLE
Is it necessary to use `using` and `check` both in Row Level Security

### ISSUE THREAD

**Issue by Monu18765** [supabase/supabase#18091]
I was about to write a security rule and show below code in Supabase Template.
```
CREATE POLICY "policy_name"
ON public.invitations
FOR INSERT USING (
  auth.uid() = user_id
)  WITH CHECK (
  auth.uid() = user_id
);
```

I am very confused and wondering why would we need both `using` and `check` for insert?

<img width="1440" alt="Screenshot 2023-10-11 at 2 43 13 AM" src="https://github.com/supabase/supabase/assets/144263406/787d603d-9b51-4164-9786-48d43883b681">

**Comment by encima** [comment]
Hi @Monu18765 ,
Thanks for reporting this, this is not a bug but I understand the confusion. `using` applies to read operations and `with check` applies to write operations (if you do not specify a `with check` then Postgres will use the same value as the `using` clause. 

It may not be necessary in all cases but it is good practise to make the policies as explicit as possible. See more info [here](https://www.postgresql.org/docs/current/ddl-rowsecurity.html)
