### ISSUE TITLE
No able to upload to a Bucket on self-hosted

### ISSUE THREAD

**Issue by CarlosIVI** [supabase/supabase#18092]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After creating a bucket and uploading a simple file, the page keep showing "Uploading file ... 0.00%" with no progress, on console we got the following errors:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://X.X.X.X:8000/api/integrations/default-org-slug?expand=true:1 
```

```
Access to fetch at 'http://localhost:8000/storage/v1/object/test/test' from origin 'http://X.X.X.X:8000' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space local
```

```
Failed to load resource: net::ERR_FAILED  localhost:8000/stora…/object/test/test:1 
```

```
Uncaught (in promise) TypeError: Failed to fetch                    localhost:8000/..._app-884f6ab5f656753e.js:1 
    at _app-884f6ab5f656753e.js:1:59622
    at _app-884f6ab5f656753e.js:1:59962
    at Generator.next (<anonymous>)
    at a (_app-884f6ab5f656753e.js:1:59334)
```

Also Kong shows this error log:

```
supabase-kong  | 128.4.85.47 - - [10/Oct/2023:21:10:20 +0000] "GET /api/integrations/default-org-slug?expand=true HTTP/1.1" 404 2272 "http://X.X.X.X:8000/project/default/storage/buckets/test" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36"
```

All Docker containers are healthy

## To Reproduce

Security group allow traffic from my network.

Steps to reproduce the behavior, please provide code snippets or a repository:

```sh
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Pull the latest images
docker compose pull

# Start the services (in detached mode)
docker compose up -d
```

Go to http://X.X.X.X:8000/project

Replace X.X.X.X with the public IP of the EC2 Instance

## System information

- EC2 Instance on AWS
- Ubuntu 22.04
- Opera (The same with Chrome and Edge)
Docker Images
`
supabase/realtime:v2.10.1
supabase/logflare:1.4.0
supabase/gotrue:v2.99.0
supabase/postgres:15.1.0.117
supabase/edge-runtime:v1.18.1
darthsim/imgproxy:v3.8.0
kong:2.8.1
supabase/postgres-meta:v0.68.0
postgrest/postgrest:v11.2.0
supabase/storage-api:v0.41.8
supabase/studio:20230921-d657f29
timberio/vector:0.28.1-alpine
`

## Additional context

I tried adding a Domain name on the env, and put it on my /etc/hosts/, but after that, the app refuses all connections, so I don't think buying a DNS will solve the problem

**Comment by CarlosIVI** [comment]
This issue were solved registering a DNS on the IP and using it in the .env, including ports

**Comment by kutovoy** [comment]
I have same issue using supabase 0.24.03 and unfortunately I was not planning to use a DNS server in a LAN but rather was expecting supabase to work over IP. what is even more interesting that uploads over IP did work for quite some time and then suddenly stopped with this exact error. ill see if I can find out why.

**Comment by kutovoy** [comment]
very weird. problem suddenly is gone quickly. I haven't modified any configuration files. I only accessed supabase server using another ip and a port (which were port forwarded to the original supabase IP) via router.
