### ISSUE TITLE
Boolean value not showing in the table unless the cell is double clicked

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#181]
# Bug report
Boolean value not showing in the table unless the cell is double clicked.

## Describe the bug
Boolean value not showing in the table. The value is actually there and would only be visible if you double clicked the cell.

## To Reproduce

1. Push code to supabase db with a boolean data type. 
2. Data will be pushed.
3. Go to the Table and check the value
4. No value is shown unless you double clicked it.

_Same behavior if you add directly using the add row feature (+)._

## Expected behavior

Values should show up without the need of double clicking the cell.

## Screenshots

![Screen Shot 2020-09-06 at 12 59 19 AM](https://user-images.githubusercontent.com/70461143/92310022-e611ef00-efdc-11ea-810f-37bc524f9863.png)

## System information

- OS: macOS
- Browser: chrome, safari
- Version of supabase-js: ^0.36.5 and latest web app
- Version of Node.js: v12.18.2

## Suggestion

Since this is a boolean type, maybe a drop down select field with fix values of **true, false, or null** during editing on the table view to prevent people from typing a wrong value.

**Comment by kiwicopple** [comment]
thanks @inbytesdevteam ! Fixing in the next release

**Comment by kiwicopple** [comment]
Fixed!
