### ISSUE TITLE
Docs sidebar icon improvements

### ISSUE THREAD

**Issue by marijanasimag** [supabase/supabase#18115]
# Chore

## Describe the chore

- GraphQL icon seems broken, attaching new one.

![Screenshot 2023-10-11 at 19 11 24](https://github.com/supabase/supabase/assets/46031252/9a229ca9-d47f-4158-93e3-ce11da919ab0)

- Generally we rounded our icon set to fit better with the Feather icons set, and we made them subtly more balanced, but we havent yet updated some of the icons in the sidebar. I marked which ones need updating on the screenshot below.

- A divider is missing before the _Resources_ section.

## Additional context

Add any other context or screenshots that help clarify the task.
![image](https://github.com/supabase/supabase/assets/46031252/8edc0c65-e3a3-44e4-88c0-a2f2a79f70eb)
New icons below:
![CLI-commands](https://github.com/supabase/supabase/assets/46031252/1f5f1d55-bd93-4ea7-b162-3c200e5bf480)
![CLI](https://github.com/supabase/supabase/assets/46031252/dc84717b-4fa6-4940-b38a-279938410c08)
![database](https://github.com/supabase/supabase/assets/46031252/9faef6eb-9ff9-4876-8898-02b8791e3406)
![edge-functions](https://github.com/supabase/supabase/assets/46031252/7676c64c-e6b7-45e3-8809-6435024dcc11)
![getting-started](https://github.com/supabase/supabase/assets/46031252/47ced44b-a95f-46ab-a8c7-628a2db5c8bc)
![graphQL](https://github.com/supabase/supabase/assets/46031252/846a9c40-891a-4030-a1e5-515f42da2455)
![Guides](https://github.com/supabase/supabase/assets/46031252/9276c9c4-b72a-4449-ba91-c188ba4a90f6)
![home](https://github.com/supabase/supabase/assets/46031252/664e85ee-84c0-47ff-b442-406b54152673)
![integrations](https://github.com/supabase/supabase/assets/46031252/c6f8da8b-bcdc-4807-b57f-9be7b9ad20f6)
![management-API](https://github.com/supabase/supabase/assets/46031252/e8b7c75c-f399-4124-b72e-f1905c3923db)
![platform](https://github.com/supabase/supabase/assets/46031252/f6a7a254-ee7b-4bfd-a2e8-93df4e106456)
![realtime](https://github.com/supabase/supabase/assets/46031252/90f6487f-1e86-4027-9826-1b3f2d895191)
![self-hosting](https://github.com/supabase/supabase/assets/46031252/e0a90748-b8c7-4870-a789-015550fe9c07)

**Comment by shishiro26** [comment]
Hi @marijanasimag I would like to work on this issue. can u please assign this to me

**Comment by Jitulteron7** [comment]
@marijanasimag  could u assigne me this issue

**Comment by vashukashyap** [comment]
@marijanasimag can I work on this issue?

**Comment by DhairyaMajmudar** [comment]
@marijanasimag pls. Assign this issue to me I vae gobe through the codebase and found out the location where error is taking place.

**Comment by saltcod** [comment]
Hey all! We don't have an assignment process. Please feel free to throw up a PR and we'd love to take a look!

**Comment by Jitulteron7** [comment]
@marijanasimag could u look into my pr https://github.com/supabase/supabase/pull/18134

**Comment by shishiro26** [comment]
Hey @saltcod @marijanasimag , how does the pull request process work? Is it based on a first-come, first-served basis, or is there another method in place?"
