### ISSUE TITLE
Error sending confirmation email

### ISSUE THREAD

**Issue by digitaldrreamer** [supabase/supabase#18153]
# Bug report
Error sending confirmation email

## Describe the bug

I've been building a site and I've completed the authentication logic & flow. It all worked perfectly and all tests were passed. Today, I was implementing a toast notification (completely unrelated) and after a test, I realized the signup no longer works.

In my web console, I got the following error: 
`
{
    "code": 500,
    "msg": "Error sending confirmation mail",
    "error_id": "81508b2cd6db5351-LOS"
}
`
I then tried the login (email & OAuth2) methods. It worked (as you would expect).

The reset password, on the other hand, gives this error: 
`{"code":500,"msg":"Unable to process request","error_id":"8150b1ac969a534e-LOS"}`

The magic link login also gives an error:
`{"code":500,"msg":"Error sending magic link","error_id":"8150bb8c5583534a-LOS"}`

I also tried sending an invitation in the Supabase CLI. I got this:
![Supabase Error Screenshot](https://github.com/supabase/supabase/assets/39851596/5c898f94-ede6-40c8-814b-fdae91f70c0f)

The supabase logs also show similar errors to these aforementioned.

## To Reproduce

1. Use any email-sending-related method.
2. See error

## Expected behavior

API call should return response with status code '200'. User should receive an email.

## Screenshots
Password Reset Error
![Password Reset Error](https://github.com/supabase/supabase/assets/39851596/b7d94fd2-68b3-49e5-a6a6-57ddcffbbeb8)

Sign Up Error
![Sign Up Error](https://github.com/supabase/supabase/assets/39851596/00e6fd8d-25a8-42ef-9e18-cc6028ad6ca5)

Magic Link Error
![Magic Link Error](https://github.com/supabase/supabase/assets/39851596/e1c72769-b644-4564-bd1c-7913ac397ee5)

Supabase Dashboard Error (While trying to send invitation in the GUI)
![Supabase Error Screenshot](https://github.com/supabase/supabase/assets/39851596/e8f03ab8-d7d0-450a-bf78-de85226e01eb)

## System information

- OS: Windows
- Browser: Chrome Version 118.0.5993.71
- Version of supabase-js: 1.99.5
- Version of Node.js: 18.17.1

## Additional context

It seems to be an issue with the email delivery system in supabase. Note that I just changed my email config in my project settings. And yes, I triple checked the email config. Right now, "Enable Custom SMTP" is off, so it has nothing to do with my email SMTP config.

**Comment by GaryAustin1** [comment]
Can you look in the Auth and Postgres logs?  
Also you were getting this error with both a custom SMTP and the rate limited (4 per hour) default SMTP?

Not seeing anyone else hitting this so either it is something wrong with your instance (which means support needs to be involved) or you have a setup issue of some sort.   

Note there was an issue with SMTP settings from custom being set wrong and then switching back to default, but that was awhile back.

**Comment by digitaldrreamer** [comment]
> Can you look in the Auth and Postgres logs?  
> Also you were getting this error with both a custom SMTP and the rate limited (4 per hour) default SMTP?
> 
> Not seeing anyone else hitting this so either it is something wrong with your instance (which means support needs to be involved) or you have a setup issue of some sort.   
> 
> Note there was an issue with SMTP settings from custom being set wrong and then switching back to default, but that was awhile back.
> 

Tried all possible fixes except ditching the project. I forgot to mention that I restarted my supabase project instance. 

This isn't the first time I've had an issue like this, though those were issues shown on the status page.

Supabase is great, but I think I'm going to work on my own in-house system from now on.

Thanks 👍
