### ISSUE TITLE
Password Recovery event keeps coming even after password has been reset

### ISSUE THREAD

**Issue by muezz** [supabase/supabase#18158]
### Discussed in https://github.com/orgs/supabase/discussions/18133

<div type='discussions-op-text'>

<sup>Originally posted by **muezz** October 12, 2023</sup>
In flutter, I have the following piece of code that listens to the Auth events and redirects to the reset page:
```dart
Supabase.instance.client.auth.onAuthStateChange.listen(
      (data) async {
        if (data.event == AuthChangeEvent.passwordRecovery) {
          // redirect user to password recovery page
          iucRouter.push(const ResetPasswordRoute());
        }
      },
    );
```
This code sends the password recovery email:
```dart
await spClient.auth.resetPasswordForEmail(
        email,
      );
```
This code resets the password once the user is taken to the password reset page:
```dart
await spClient.auth.updateUser(
        UserAttributes(
          password: newPassword,
        ),
      );
```

Once the password is reset, the user is automatically logged in (as the next event is `signedIn`). 

If I close the app and restart it, I receive the `passwordRecovery` event again and that keeps happening if I keep trying to restart the app.

What is causing this? Am I making some mistake?</div>

### This is quite urgent for me and I was not getting a response in the discussion. I am sure it is a mistake on my end since I cannot find any other posts/issues that mention this problem. And there is practically no documentation for this (especially in flutter).

**Comment by dshukertjr** [comment]
This behavior only happens on emulators, and will not happen in production environments. You can find a summary of why this happens here. 
https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807
