### ISSUE TITLE
Outdated method to subscribe to database changes in Supabase docs

### ISSUE THREAD

**Issue by nathantew14** [supabase/supabase#18162]
### Discussed in https://github.com/orgs/supabase/discussions/18147

<div type='discussions-op-text'>

<sup>Originally posted by **nathantew14** October 12, 2023</sup>
The [realtime docs overview](https://supabase.com/docs/guides/realtime) shows this method to subscribe to changes:
```
// Initialize the JS client
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

// Create a function to handle inserts
const handleInserts = (payload) => {
  console.log('Change received!', payload)
}

// Listen to inserts
const { data: todos, error } = await supabase.from('todos').on('INSERT', handleInserts).subscribe()
```

However, in the [usage guide for Postgres Changes](https://supabase.com/docs/guides/realtime/postgres-changes#usage), there is a completely different method:
```
supabase
    .channel('schema-db-changes')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
      },
      (payload) => console.log(payload)
    )
    .subscribe()
```

And in fact, I can't seem to find the first method anywhere else. How are they different? When should each be used? Thanks.</div>

I've been told the former is outdated, and that I should raise an issue here.

**Comment by GaryAustin1** [comment]
Looks like the docs where updated.  Closing this.
