### ISSUE TITLE
Signup error (Verify requires a verification type)

### ISSUE THREAD

**Issue by snsnf** [supabase/supabase#18177]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This error occurs when clicking on the confirmation email
```json
{
    "code": 400,
    "msg": "Verify requires a verification type"
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a signup (or resend) function 
```js
const { data:{user}, error } = await supabase.auth.signUp({ email, password});

// OR

const { data, error } = await supabase.auth.resend({
    type: 'signup',
    email: 'email@example.com'
    })
```

2. Call the function and wait for the confirmation email
3. Open the email and click on the confirmation email

## Expected behavior

To redirect to https://example.com and confirm the email

## System information

- OS: iOS, Android
- Version of supabase-js: 2.38.1
- Version of Node.js: 18.17.1

## Additional context

I tried the two methods, with the default SMTP and with the custom SMTP and both didn't work.

**Comment by hhsecond** [comment]
Facing this in production. Signup verification is failing but I found a manual work around. Sending a magic link from the dashboard manually trigger an email with a link (token is not pkce in this case). This link doesn't have issue in doing the verification. I can confirm both links have and go true is checking the type cases properly. So I assume its a bug on supabase's layer before calling go true?

```json
type=signup
```

**Comment by hf** [comment]
Usually this error is because of some misconfiguration of the client libraries. `Verification type` here refers to Implicit Flow or PKCE flow, so I suppose that is not being properly sent.

Would you mind:

1. Updating to the latest version of `@supabase/supabase-js` and its dependencies? In any case please state the version of libraries you're using (ideally by uploading a package-lock.json file).
2. Please share any code about how you create the Supabase client.

If you'd rather share this over a private channel please open a support issue and mention this GitHub issue: https://supabase.com/dashboard/support/new

**Comment by hhsecond** [comment]
Okey, I have raised a support ticket and will upload the asked details but let me make sure I understand this! You guys have decided to update the package (kudos) but also decided to break backward compatibility? That isn't very nice! Supabase has been very dev friendly and we love everything you do! but ...

**Comment by J0** [comment]
Hey team,

As discussed the error here arose from a malformed redirect URL `<redirect_url>?&utm=` which had an additional & parameter. This resulted in a truncation to `https://<ref>.supabase.co/auth/v1/verify?token=pkce_<token>&type=signup&redirect_to=<url>?`

which meant that the  params were not parsed leading to `type` being interpreted as an empty field

We'll look into better ways to guard against this on the server level as well.

Appreciate y'all taking the time to flag this - going to close for now but  let us know if there are further issues.

Thanks!

**Comment by nicollegah** [comment]
I also have this problem now all of a sudden after running stable for a year and nothing changed, as far as I know. Any idea why?

**Comment by pearcircuitmike** [comment]
@J0 this should be reopened I think

**Comment by simonwst** [comment]
Can we please re-open this? We're facing the same issue every now and then... which is really weird, the redirect results in the following hash being attached to the redirect URL:

> #error=invalid_request&error_code=400&error_description=Invalid+email+verification+type

Unfortunately I can't really reproduce it, It'd be great to have more in the docs about this kind of error that we can at least assume what might cause and and build workarounds.
