### ISSUE TITLE
[Dashboard]: The new page showing enumerated types also shows composite types

### ISSUE THREAD

**Issue by JulienLecoq** [supabase/supabase#18180]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The new page showing enumerated types also shows composite types. This page can be found in ``dashboard -> Database -> Enumerated Types``.

## To Reproduce

1. Create a composite type with the following SQL query:

```SQL
CREATE TYPE test_composite_type AS (
  id int8,
  name text
);
```

2. Go to the page at : dashboard -> Database -> Enumerated Types
3. See the newly created composite type.

## Expected behavior

I expect to only see enumerated types.

## Screenshots

<img width="1191" alt="Screenshot 2023-10-13 at 18 50 50" src="https://github.com/supabase/supabase/assets/54070985/97549bbf-e22c-4342-84ea-e61be5c8b511">

## System information

- OS: macOS
- Browser: safari

**Comment by Legitbunny** [comment]
Hi ,

I can see something like this - 
![image](https://github.com/supabase/supabase/assets/121758817/6580da60-6199-421b-ab5a-680d03e1dee0)

What is the expected behaviour ? @JulienLecoq @saltcod

**Comment by Nabhag8848** [comment]
Hey @encima I have been going through the issue and found out following:
- I believe and i just checked that when creating composite types with current implementation it doesn't create and assumes that as a enumerated types, we are sure that.
- problem is around: get query for enumerated types is also querying the composite types. 

is there any documentation for endpoints ? i'm currently not able to figure out what does GET endpoint /platform/pg-meta/{ref}/types 

https://github.com/supabase/supabase/blob/master/apps/studio/data/enumerated-types/enumerated-types-query.ts#L25

**Comment by JulienLecoq** [comment]
Hi, if there are nothing else to differentiate a type from an enum it looks good to me to use the length of the enums array to determine if a given record is an enum or a type.

**Comment by Nabhag8848** [comment]
Cool Thanks @JulienLecoq , Working Fine Now. Opening PR. 🚀

https://github.com/supabase/supabase/assets/65061890/98a7eb60-4e34-4cc6-8761-5426da456661
