### ISSUE TITLE
Code examples in api panel should use const, not let

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18184]
We use `const` everywhere, we should use it here instead of `let`.
Applies to all these code examples in the api docs side panel.

![screenshot-2023-10-13-at-16 17 59](https://github.com/supabase/supabase/assets/105593/4dc4771a-26ef-4989-b6c1-a9c2d0ab1fa6)

**Comment by shishiro26** [comment]
Hey @saltcod can you check my pr .

**Comment by IbraheemHaseeb7** [comment]
is this done?

**Comment by Mohammed-Yasin-Mulla** [comment]
I will be picking this up please assign it to me
I am working on this

**Comment by saltcod** [comment]
addressed, thanks all!
