### ISSUE TITLE
Unable to empty the supabase IP blacklist; unable to directly connect to the DB

### ISSUE THREAD

**Issue by Pictor13** [supabase/supabase#18204]
### Discussed in https://github.com/orgs/supabase/discussions/14929

Thanks to the discussion linked I found out that my ip was banned, preventing me to connect to the project DB.

List the banned IPs:
```
% supabase network-bans get --project-ref <project_reference_id> --experimental
```
Unban the IPs:
```
% supabase network-bans remove --db-unban-ip <ip_address> --project-ref <project_reference_id> --experimental
```
-----

The problem is that after doing `supabase link` to the correct project, I am allowed to list the network bans and see my IP there, but.... I am not allowed to remove the ban, becase:
```
failed to remove network bans: {"message":"Forbidden resource"}
```

Why would that be the case?  
Given I've been using the main password for the project, why doesn't it work as expected?

**Comment by saltcod** [comment]
Hey @Pictor13 could you submit a support request for this one so we can look into it please?
