### ISSUE TITLE
filters on json columns in js api shows incorrect operator

### ISSUE THREAD

**Issue by MattpaulKing** [supabase/supabase#18208]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/neq

## Describe the problem
The documentation around filters on json columns shows col_name->prop_name, but the working operator is col_name->>prop_name

## Describe the improvement
The change suggested would prevent a google search.

## Additional context
None

**Comment by GaryAustin1** [comment]
Your link does not go to anything about json.

Normally you use -> to get json or numbers and ->> for text.

**Comment by saltcod** [comment]
Happy to help with some more detail @MattpaulKing

**Comment by MattpaulKing** [comment]
Hi sorry I must have clicked something else before copying the link. 
The correct link is https://supabase.com/docs/reference/javascript/using-filters?example=filter-by-value-within-json-column

I didn't realize there were different operators for text vs. numbers thanks for letting me know.
