### ISSUE TITLE
Storage policies don't link to docs

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18277]
The Auth Policies modal has a link to documentation, but Storage policies modal does not. 

In the Storage Policies modal, we should add a "Documentation" link, and link to this guide:
https://supabase.com/docs/guides/storage/access-control

link: https://supabase.com/dashboard/project/_/storage/policies

![screenshot-2023-10-17-at-15 18 59](https://github.com/supabase/supabase/assets/105593/eff3153b-e709-4478-bedd-5564beb8189e)

**Comment by YugBhanushali** [comment]
Added the storage policies link to the modal #18279

**Comment by alaister** [comment]
Fixed in #18284
