### ISSUE TITLE
Improve Supabase Auth with the Next.js App Router Docs

### ISSUE THREAD

**Issue by marcusarnfast** [supabase/supabase#18285]
# Improve documentation

## Link 

Check out: [Supabase Auth with the Next.js App Router](https://supabase.com/docs/guides/auth/auth-helpers/nextjs)

## Describe the problem
So, after using Supabase in production, some pages felt like they took ages to load. And after some digging it turns out, that the middleware was being called more than necessary. 

Take a product list page, for example. Next.js pre-fetches all the links, this causes the middleware to be called multiple times, for no reason, sometimes leading to a 400 error.

I did a test on the "with-supabase" template and here's what I found:

| Before fix | After fix |
| ------------- | ------------- |
| <img width="482" alt="image" src="https://github.com/supabase/supabase/assets/99841792/dd0d9626-1f65-484b-9c18-0b72681eeb85">  | <img width="313" alt="image" src="https://github.com/supabase/supabase/assets/99841792/1d4fe876-f9e6-4341-9264-2f3c3b21b649">  |
| Middleware is called 9 times per page load.  |  The middleware is called once per. page load   |

I referred to the [Next.js Middleware Docs](https://nextjs.org/docs/app/building-your-application/routing/middleware) and found that we can use a matcher to decide when the middleware runs. And i feel like this should be part of the Supabase guide, since It substantially enhances performance, and there's no logical reason to invoke the middleware for resources like favicons, images, and CSS files.

## Describe the improvement
```ts filename="middleware.ts"
import { createMiddlewareClient } from "@supabase/auth-helpers-nextjs";
import { NextResponse } from "next/server";

import type { NextRequest } from "next/server";

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();

  // Create a Supabase client configured to use cookies
  const supabase = createMiddlewareClient({ req, res });

  // Refresh session if expired - required for Server Components
  // https://supabase.com/docs/guides/auth/auth-helpers/nextjs#managing-session-with-middleware
  await supabase.auth.getSession();

  return res;
}

// Ensure the middleware is only called for relevant paths.
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!_next/static|_next/image|favicon.ico).*)',
  ],
}

```

I hope this helps others as much as it helped me :v:

## Additional context

No

**Comment by JavascriptMick** [comment]
100% agree and can confirm, simply loading the home page of the 'with-supabase' example app loads the middleware client and refreshes the user session 7 times!  I think though, rather than a documentation fix here, could be a direct PR against the actual next.js example here (https://github.com/vercel/next.js/blob/e5c082418de35e065649a6c26bfdfdd7535e9bf3/examples/with-supabase/middleware.ts)

**Comment by h8f1z** [comment]
Why hasn't this been applied yet? 🤔
Just now I saw the Auth Rate Limit Error on my console for the same reason.
```
[AuthApiError: Rate limit exceeded] {
  __isAuthError: true,
  name: 'AuthApiError',
  status: 429
}
```
When I checked the supabase log, it was taking several requests for every Next.js page load.

Thanks @marcusarnfast for the fix.

**Comment by SubhoYadav** [comment]
I am a new contributor here. Please tell me whether I can pick the issue or not ?

**Comment by charislam** [comment]
@SubhoYadav, feel free to pick this up! We'd appreciate the help

**Comment by SubhoYadav** [comment]
Please help me getting started with the project cause, inspite of having the compatible node and npm versions, I am not been able to fire up the dev server of studio

**Comment by charislam** [comment]
You shouldn't need to fire up studio dev for this fix, the docs site alone should be enough. 🤔 

If you clone the repo and run `npm run dev:docs`, then try going to `localhost:3001`, what error are you getting?

**Comment by RaghavBhat02** [comment]
@SubhoYadav are you still taking this? If not, I can do it real quick.
