### ISSUE TITLE
Supabase Auth URL Configuration Issue (Chrome Extension/Redirect URLs)

### ISSUE THREAD

**Issue by OrangeDev2** [supabase/supabase#18290]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

URL Configuration Settings is not redirecting user to chrome-extension:// (as Redirect URLs) correctly.  It's a Redirect URL problem with chrome-extension:// where http/https domains work just fine.

For example:
Using same Project URL and Anon key.  You have an Web App [A] and an Chrome Extension [B] where user should sign in either via Social Login.

**Scenario 1:** Default Site is set to A URL.  B is set as an Redirect URL (Which I want)
-- User signs in A.  Logs in in as A user via Website.  Works fine.
-- User signs in B, Logs in as an A user via Website in Extension popup. Weird behavior.

**Scenario 2:** Default Site is set to B URL.   A is set as an Redirect URL.  
-- User signs in B.  Logs in as B user via Chrome Popup.  Works fine.
-- User signs in A but gets redirected to B URL (404 page if extension is not installed).  Otherwise, User can sign in A. Weird behavior.

## To Reproduce

*: Instructions in Repo README.MD
1. Go to https://github.com/OrangeDev2/SupaLogin-Chrome-Extension/tree/popup-redirect
2. Fork repo
3. Plug in your Project URL and Anon Key*
4. Load unpacked at chrome://extensions/*
5. Follow either Scenario above (need an http/https to test)*
6. See Error

## Expected behavior

I expect User to signs in A as A user.  User signs in B as B. Where A is Site URL and B is Redirect URL.
Notice: B Site URL solely extension works fine.

## Screenshots
URL Configuration Settings
![image](https://github.com/supabase/supabase/assets/47803678/fa438b24-3102-4ab5-99b0-e9941bbae688)
-- Signing in via Website, redirected to extension instead.
![image](https://github.com/supabase/supabase/assets/47803678/1695f7ee-6642-4fb9-a97b-38cb2e4eb82c)

## System information

- OS: Windows
- Browser Chrome
- Version of supabase-js: [e.g. 6.0.2]/Latest
- Version of Node.js: [e.g. 10.10.0]/Latest

## Additional context
N/A

**Comment by OrangeDev2** [comment]
popup-redirect branch is the alternative/potiental solution which almost works, see bug/reason above.

main branch is the implementation following https://supabase.com/docs/guides/auth/social-login/auth-google?platform=chrome-extensions which seems to have impossible error, no matter what I do (double checking Google Console, Supabase Provider Client ID/Chrome ID/Client Secret/URL config) can't seems to get past this screen.
![image](https://github.com/supabase/supabase/assets/47803678/1f92166e-abb6-4fdf-b173-98bbe9530e04).  
I just don't have any hope for this branch but figured I should bring it up.

**Comment by bhagawatDongre** [comment]
<img width="985" alt="image" src="https://github.com/supabase/supabase/assets/22837315/90ea2ee1-68a4-481a-87f6-78f1fb60cfa3">

not sure why but worked for me with wildcard

**Comment by encima** [comment]
Interesting, thanks @bhagawatDongre for confirming this. 
Plamso extension framework also has an [example extensions](https://docs.plasmo.com/quickstarts/with-supabase) using Supabase Auth. 
I will close for now but please comment if you want this added to the docs or think it should be re-opened!

**Comment by bhagawatDongre** [comment]
Just in case if some one still facing issue confirm this configuration in manifast file its important to make file accessible.

https://docs.plasmo.com/quickstarts/with-supabase#:~:text=Now%20we%20need%20to%20make%20it%20so%20that%20the%20browser%20doesn%27t%20block%20access%20to%20our%20options%20page.%20To%20do%20this%2C%20we%20must%20add%20it%20to%20our%20web_accessible_resources%20in%20our%20manifest%3A

**Comment by kirkwat** [comment]
@bhagawatDongre When you did this, is your site url a website or just the chrome extension? because I still have the issue described above when doing this with a website as a site url.

> <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/22837315/301148261-90ea2ee1-68a4-481a-87f6-78f1fb60cfa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjUwNzIsIm5iZiI6MTczMDkyNDc3MiwicGF0aCI6Ii8yMjgzNzMxNS8zMDExNDgyNjEtOTBlYTJlZTEtNjhhNC00ODFhLTg3ZjYtNzhmMWZiNjBjZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDIwMjYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGRmODI2MTk4NDE5YTU5YjgyYmE1OWQyYjU4YTdhOTQxYzAzOWU5NGY1ODUyZTY4OWI5ZjYxNjVhYjVmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3lufr3OGTsH1iD8ZMFr2FVzHGcU9s-kFVZJjH-nFnmE">
> not sure why but worked for me with wildcard
