### ISSUE TITLE
Edit page link on wrappers page leads to 404

### ISSUE THREAD

**Issue by kamilogorek** [supabase/supabase#18310]
On https://supabase.com/docs/guides/database/extensions/wrappers/airtable and any other wrapper page "Edit this page on GitHub" leads to 404, as those pages are pulled from a separate wrappers docs page.

Ref: https://github.com/supabase/supabase/blob/master/apps/docs/pages/guides/database/extensions/wrappers/%5Bslug%5D.tsx

**Comment by yousseefben** [comment]
Hello, I tried to fix it in a better way, feel free to review it, thanks :)

**Comment by charislam** [comment]
Closing as fixed, thanks @yousseefben!
