### ISSUE TITLE
Defaults not working when adding data in Supabase web UI

### ISSUE THREAD

**Issue by k-milktooth** [supabase/supabase#18316]
## Describe the problem

For example, the `created_at` column is supposed to default to `now()` but whenever I add new rows in the web UI the value is null. This problem applies to all columns that have a specified default value. This used to not be an issue.

**Comment by saltcod** [comment]
Hi @k-milktooth 

Do you mean here? 

<img width="698" alt="screenshot-2023-10-18-at-16 18 04" src="https://github.com/supabase/supabase/assets/105593/f9f485ba-38c0-4bc6-be37-11b26a6463ba">


This must be a recent change in Chrome, agreed it wasn't like this. And pretty sure we haven't changed anything here recently. 

In the meantime, it does save and display `now()` in the row after. Does it do that for you as well? 


<img width="524" alt="screenshot-2023-10-18-at-16 18 58" src="https://github.com/supabase/supabase/assets/105593/7d4d3dc2-7b40-4d1c-94f4-5b1d46f46724">

**Comment by k-milktooth** [comment]
So I click "Insert", leave everything blank, and then "Save":

![Screenshot 2023-10-18 at 11 50 54](https://github.com/supabase/supabase/assets/11021334/79ff0097-d57d-438c-9364-b84f98085685)
![Screenshot 2023-10-18 at 11 51 10](https://github.com/supabase/supabase/assets/11021334/7052aacb-3d90-45ee-8852-429bac68a01d)

`created_at` is still null even for the row after. 

![Screenshot 2023-10-18 at 11 51 46](https://github.com/supabase/supabase/assets/11021334/69d5eac0-5389-4b06-9dc4-84f53569b72b)

For reference I'm not using Chrome; using Firefox right now.

**Comment by GaryAustin1** [comment]
Just verified in Chrome...
![image](https://github.com/supabase/supabase/assets/54564956/7bcb2894-bd52-4fe4-8c36-40cb6899d543)

**Comment by GaryAustin1** [comment]
Well I just looked at another table and it has been broken for at least a week or two.  I see a last row I set testing last week and it is bad also.  I don't have the date of course as it replaced it with null.  Two dates with now() set to null and an array field set to default to empty array is also coming back null.

![image](https://github.com/supabase/supabase/assets/54564956/fbe07521-b939-4a23-97f5-1e58f54b27e7)

Guess it means this is not as critical as I thought as no one reported it... but I have bad data in this table and did not even notice it.  A

All data inserted thru the UI.

**Comment by GaryAustin1** [comment]
https://github.com/supabase/supabase/pull/17844
Maybe this change as it messes with defaults and null.

**Comment by ivasilov** [comment]
Thank you for your report. From what I investigated, It only happens with nullable (optional) fields which have a default value.

**Comment by GaryAustin1** [comment]
I changed a column to not allow nulls and the default value comes thru for that case.
So yes it is only nullable columns where the error is occurring.
