### ISSUE TITLE
 Auth Starter with Nextjs App Router "Could not Authenticate User"

### ISSUE THREAD

**Issue by absolutegravitas** [supabase/supabase#18325]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Starter App using nextjs app router doesnt work.

## To Reproduce

1. Go to 'https://supabase.com/docs/guides/auth/auth-helpers/nextjs?language=ts'
2. Follow instructions under Automatic Configuration
3. Run yarn dev (with correct environment variables)
4. Attempt sign up with new user (email) and password
5. Page reloads with message "could not authenticate user" no browser console errors, no terminal errors

## Expected behavior

1 - supabase user is created in auth schema
2 - user creation is confirmed.

## Screenshots
![image](https://github.com/supabase/auth-helpers/assets/124488796/6a597024-c333-46d3-8a40-bed1da6807d8)

![image](https://github.com/supabase/auth-helpers/assets/124488796/8204a9cb-8bcf-468b-b6e0-80caca67c096)
![image](https://github.com/supabase/auth-helpers/assets/124488796/9dd53027-ca9e-4247-9977-87bfad3bc9c6)

## System information
@supabase/auth-helpers-nextjs": "^0.8.1",
@supabase/supabase-js": "^2.38.1",
node 20.8.0

**Comment by chmuzamil** [comment]
Working Fine
Edge - Win 11
Chrome - ParrotOS

Node v21.0.0
@supabase/auth-helpers-nextjs": "^0.8.1",
@supabase/supabase-js": "^2.38.1",

![chrome_parrotOS](https://github.com/supabase/supabase/assets/11614484/e9d42885-c159-4408-8b84-070921642d47)

![edge-windows](https://github.com/supabase/supabase/assets/11614484/8633aef3-c1e5-47fc-9903-74777bf9a226)


However Signup Button is not visible in Dark Mode
Please Let me know more information

**Comment by absolutegravitas** [comment]
maybe a node version issue? that's all i've got -- above is from the clean install via `npx create-next-app -e with-supabase`

will report back -- for dark button yeah i was going to fix that after the fact once the actual hello world actually worked

**Comment by absolutegravitas** [comment]
marking resolved -- issue was with incorrect SMTP password in Supabase config -- for some reason that breaks sign in / sign up completely causing the "could not authenticate user"

**Comment by Dey-Sumit** [comment]
> marking resolved -- issue was with incorrect SMTP password in Supabase config -- for some reason that breaks sign in / sign up completely causing the "could not authenticate user"

Can you please explain this? I am getting the same issue
