### ISSUE TITLE
DELETE doesn't delete database record

### ISSUE THREAD

**Issue by retr0cube** [supabase/supabase#18337]
# Bug report

- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 
- [x] I confirm this is a bug with Supabase, not with my own application. 

## Describe the bug
When trying to delete a post in supabase (svelte-kit), the request is shown in logs explorer but the "delete" action is not! the post is still in the database!
## To Reproduce

Executing the following code that deletes a post using the ID:
```js
        const deletePost = await supabase.from("posts").delete().eq("id", postId)
        // console.log("I'm Here")
        if (deletePost.error !== null) {
            return deletePost.error
        }

```
yields the following results:
```json
{
  error: null,
  data: null,
  count: null,
  status: 204,
  statusText: 'No Content'
}
``` 
And in logs explorer (UI), I get:
![image](https://github.com/supabase/supabase/assets/61835816/9d93ed18-dc9b-4690-a297-fc53cac3297a)

## Expected behavior
The post to be deleted

## System information
Unnecessary in this case

**Comment by GaryAustin1** [comment]
Do you meet select and delete RLS?
