### ISSUE TITLE
A case error in doc page, click MySQL returned a 404. I

### ISSUE THREAD

**Issue by PaddyPang** [supabase/supabase#18345]
# Bug report

In section "Migrate to Supabase" of this page "https://supabase.com/docs#migrate-to-supabase"

- [ ] Click MySQL returned a 404. It should be a case error. 

The current link is  "/guides/resources/migrating-to-supabase/MySQL", 
and the right link is "/guides/resources/migrating-to-supabase/mysql"

file: /apps/docs/pages/index.mdx
![image](https://github.com/supabase/supabase/assets/18202902/e463157c-1084-4a14-adfc-ff1a2d3c00e1)

**Comment by gregnr** [comment]
Fixed in #18357
