### ISSUE TITLE
The background color of the drop-down is incorrect when choosing an default enum form the Supabase dashboard

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [supabase/supabase#18374]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When choosing a default value for a created enum, the dropdown background colour is white and the text is also white, white hovering over the list the background  color of the text is black

## To Reproduce
Steps to reproduce the behaviour,

1. Create a new column, by clicking on Insert a column form the dashboard
2. Chose  the type of column to be an enum type you have already created
3. Select one of the default type 

## Screenshots

![image](https://github.com/supabase/supabase/assets/55092280/dc047c38-7d78-466e-9635-4f9509486dbb)

## System information

- OS: [Linux Ubuntu]
- Browser: Chrome

**Comment by rohitverma007** [comment]
may i attempt this?

**Comment by saltcod** [comment]
Absolutely @rohitverma007!

**Comment by Mohammed-Yasin-Mulla** [comment]
@saltcod ,
could you please help me out here, I am super exited to get this issue fixed but unable to do so because of this
https://github.com/orgs/supabase/discussions/18376

**Comment by EskinderAbera** [comment]
Mohammed-Yasin-Mulla,
issues fixed.
![Screenshot (194)](https://github.com/supabase/supabase/assets/81253006/0c0f8341-b91c-460f-9ec0-ac24c59bc771)

**Comment by EskinderAbera** [comment]
How can I help you?

**Comment by Mohammed-Yasin-Mulla** [comment]
@EskinderAbera  I am un-able to run the project locally, I have mentioned all the steps I have taken.
could you please check it out and let me know if I have missed something.

**Comment by shishiro26** [comment]
> @EskinderAbera  I am un-able to run the project locally, I have mentioned all the steps I have taken.
> could you please check it out and let me know if I have missed something.
> 

I am having the same problem I am unable to run the project locally the dependencies are not getting installed

**Comment by EskinderAbera** [comment]
Hello @Mohammed-Yasin-Mulla, you need to run Supabase using Docker.
please follow the steps from the docs. check the following link
https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#running-docker

**Comment by EskinderAbera** [comment]
> Reference
Hello @shishiro26, are you trying to run the project on the Windows operating system?

**Comment by shishiro26** [comment]
> > Reference
> Hello @shishiro26, are you trying to run the project on the Windows operating system?

Yes I am running it in the windows.

**Comment by EskinderAbera** [comment]
can you provide more details about the error messages you are encountering?

**Comment by encima** [comment]
This is currently fixed in the latest version as the dropdown follows the system theme and mode so I will close for now.
Please comment if this is still impacting you and we can revisit it

<img width="853" alt="image" src="https://github.com/supabase/supabase/assets/517923/2f4b150c-9875-4787-8406-781cb4cbe25b">
