### ISSUE TITLE
Discord Authentication

### ISSUE THREAD

**Issue by dawnofmidnight** [supabase/supabase#1838]
# Feature request

## Is your feature request related to a problem? Please describe.
I'd love if Supabase were able to have support for Discord OAuth2 authentication.

Discord's documentation for this can be found at https://discord.com/developers/docs/topics/oauth2.

## Describe the solution you'd like

While it is possible to implement Discord OAuth2 yourself and insert it into the database, it's much easier to have it integrated into the service (Supabase) that I'm already using for the rest of my authentication.

## Describe alternatives you've considered

As I stated above, I could implement this myself, but it would be nice to have it integrated.

## Additional context

I'd love to attempt to implement this myself, but I'd like to know if anyone else would find it useful. 

(Also, I can't exactly find the place in the repository where third party authentication is handled.)

**Comment by soedirgo** [comment]
Hey @dawnofmidnight, this is being tracked here: https://github.com/supabase/gotrue/issues/93, so

> I'd love to attempt to implement this myself, but I'd like to know if anyone else would find it useful

is a yes :)

**Comment by dawnofmidnight** [comment]
Oh, I didn't realize Auth was handled in gotrue. I'll go ahead and close this issue then. 

Also, I don't know go, so I won't be able to implement it.
