### ISSUE TITLE
Tutorial results in error: You are assigning to a const

### ISSUE THREAD

**Issue by jjoelio91** [supabase/supabase#18393]
Fairly new to Svelte and some of its syntax, but was following the [linked tutorial](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit?language=js#:~:text=const%20%7B%20supabase%2C%20session%20%7D%20%3D%20data) and it gives an error in VSCode: "You are assigning to a const"

The particular piece giving the error is:

```
const { supabase, session } = data
$: ({ supabase, session } = data)
```

Looks to have been [a commit](https://github.com/supabase/supabase/commit/b09243b628c4f47c98fff0d89c08f561865ae56b) changing it from "let" to "const", and when I switch it back, it seems to work. Whilst it would appear that commit was changing a lot of other let references to const, would like to understand if that is the correct thing to do in this scenario, or if it should be handled in another way?

**Comment by Creative-Difficulty** [comment]
Can confirm with SvelteKit v4

**Comment by danielhardy** [comment]
I can confirm this as well

**Comment by old-rob** [comment]
I would also like to know what should be done about it. Is using let the standard approach? I'm new to both sveltekit and supabase

**Comment by Creative-Difficulty** [comment]
Just do let instead of const.
```

let { supabase, session } = data
$: ({ supabase, session } = data)

```
I'm going to quickly send in a PR to fix this.
