### ISSUE TITLE
Supabase "createClient" sending too many requests in network tab

### ISSUE THREAD

**Issue by GreatHayat** [supabase/supabase#18391]
### Discussed in https://github.com/orgs/supabase/discussions/18390

<div type='discussions-op-text'>

<sup>Originally posted by **GreatHayat** October 23, 2023</sup>
Hello everyone!

I just started with supabase in `nextjs 13` (App Directory) and I used `createClient` in a `client component`. But I noticed it is sending too many requests in network tabs. below is my code

```"use client";

import { createClient } from "@supabase/supabase-js";

const supabaseBaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.NEXT_PUBLIC_SUPABASE_SERVICE_KEY!;

export default async function Testing() {
  const supabaseClient = createClient(supabaseBaseUrl, supabaseServiceKey);

  const { data: files, error: filesError } = await supabaseClient
    .from("files")
    .select("id, file_name");
  return (
    <>
     <p>{JSON.stringify(files)}</p>
    </>
  );
}
```

You can also see in the image attached, there are more than **250 requests** in the network tab and it is continuously growing. 
I don't know what's the issue and I couldn't find any solution on Google. Please help me if you know the solution.

I'm also getting the following warning in the conosle

`Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.`

<img width="1436" alt="Screenshot 2023-10-23 at 1 04 39 AM" src="https://github.com/supabase/supabase/assets/30028457/efe5440f-5ec9-4cb7-ac74-e43ec9e306bc">
</div>

**Comment by GaryAustin1** [comment]
I'm going to close this for the moment.  This is likely something in your code causing this section of code to run multiple times.   I've commented in your discussion and probably some more debugging there or seeking help from users in Supabase Discord should occur before posting here (which is mainly for bugs).
Thanks
