### ISSUE TITLE
Auth only works on localhost with SvelteKit

### ISSUE THREAD

**Issue by Creative-Difficulty** [supabase/supabase#18404]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

supabase doesn't set sessions and overall just doesn't work.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the repo: https://github.com/Creative-Difficulty/marc-plan
2. Run it with Bun (IMPORTANT): `bun --bun run dev --host`
3. View it on http://localhost:5173/ and see that it works
4. View it from your network IP and see that supabase doesn't set sessions and overall jusT doesn't work

## Expected behavior

Your product works.

## System information

- OS: macOs Sonoma
- Version of "@supabase/auth-helpers-sveltekit": "^0.10.3", "@supabase/supabase-js": "^2.38.2",
- Version of Bun: 1.0.7

## Additional context

This breaks my app completely pls fix very soon @joshenlim @kiwicopple @MildTomato @saltcod @gregnr

**Comment by Creative-Difficulty** [comment]
Can anybody (@joshenlim)confirm this or am i setting something up wrong, it doesn't work with pnpm and Node.js either, so it's just a general issue with supabase and SvelteKit

**Comment by joshenlim** [comment]
Hey there @Creative-Difficulty! Apologies that you're running into this - I'm checking in with the auth team about this, hopefully we'll be able to give you an update soon 🙏

**Comment by Creative-Difficulty** [comment]
> Hey there @Creative-Difficulty! Apologies that you're running into this - I'm checking in with the auth team about this, hopefully we'll be able to give you an update soon 🙏

Thank you so much for the swift response! I really hope i'm just doing something wrong.

**Comment by silentworks** [comment]
This is a cookie related issue, when using cookies on a domain or an ip besides localhost you have to set `secure` to false if the IP doesn't have `https` configured. I have attached a video showing this working once you set the cookie option in your config.

```ts
event.locals.supabase = createSupabaseServerClient({
	supabaseUrl: PUBLIC_SUPABASE_URL,
	supabaseKey: PUBLIC_SUPABASE_ANON_KEY,
	event,
	cookieOptions: {
		secure: false
	}
});
```

https://github.com/supabase/supabase/assets/79497/531cfce1-5d56-4e32-bf6d-334f4c8f350a

**Comment by Creative-Difficulty** [comment]
Thanks very much!
I think it would be very beneficial to mention this in the docs.
