### ISSUE TITLE
Slack clone example project steps to start project fail because example not found

### ISSUE THREAD

**Issue by inorganik** [supabase/supabase#18406]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Following the steps here fail because the example is not found: https://github.com/supabase/supabase/tree/master/examples/slack-clone/nextjs-slack-clone

## To Reproduce

with the `npx` command you get this error:

```bash
% npx create-next-app --example with-supabase-auth-realtime-db realtime-chat-app
Need to install the following packages:
  create-next-app@13.5.6
Ok to proceed? (y) y
Could not locate an example named "with-supabase-auth-realtime-db". It could be due to the following:
 1. Your spelling of example "with-supabase-auth-realtime-db" might be incorrect.
 2. You might not be connected to the internet or you are behind a proxy.
 ```
with the curl command you get this error:

```bash
 % curl https://codeload.github.com/vercel/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-supabase-auth-realtime-db
cd with-supabase-auth-realtime-db
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36.4M    0 36.4M    0     0  9296k      0 --:--:--  0:00:04 --:--:-- 9309k
tar: next.js-canary/examples/with-supabase-auth-realtime-db: Not found in archive
tar: Error exit delayed from previous errors.
cd: no such file or directory: with-supabase-auth-realtime-db
```

## Expected behavior

Should be able to create the project following the steps provided.

## System information

- OS: macOS 14.0
- Browser (if applies): n/a
- Version of supabase-js: n/a
- Version of Node.js: 20.5.1

**Comment by dijonmusters** [comment]
Good catch! This template has been removed from the Next.js repo - have opened a PR to remove this section: https://github.com/supabase/supabase/pull/18600
