### ISSUE TITLE
i got bug dashboard error jwt, please help me

### ISSUE THREAD

**Issue by craftgirlsss** [supabase/supabase#18423]
i cant open my dashboard after setup template email for magic link. please help me
![reportissue2](https://github.com/supabase/supabase/assets/146034705/f73f7779-576d-4799-a461-01acc9061d94)

**Comment by Creative-Difficulty** [comment]
wtf is this. Please provide a minimal reproduceable example

**Comment by saltcod** [comment]
Hi @craftgirlsss looks like you need to log back in. Let us know if that doesn't fix it.

**Comment by hf** [comment]
Hi @craftgirlsss can you please go to https://time.is and let us know if there's a significant deviation in your computer's clock?

**Comment by craftgirlsss** [comment]
> Hi @craftgirlsss looks like you need to log back in. Let us know if that doesn't fix it.i was try to logout and login again, but sometimes every 5-10 minutes will error again.. my computer clock is the same, and when i try to get request from phone still the same show error jwt

**Comment by hf** [comment]
@craftgirlsss Would you mind sending an email to support@supabase.com with a link to this discussion and details about your account so we can look into this?
