### ISSUE TITLE
Example public url on storage docs is outdated?

### ISSUE THREAD

**Issue by Olyvar** [supabase/supabase#18429]
# Improve documentation

## Link 

[https://supabase.com/docs/guides/storage/image-transformations#nextjs-loader](url)

## Describe the problem

The example public url is the following: https://project_id.supabase.co/storage/v1/render/image/public/bucket/image.jpg?width=500&height=600

When using this url and changing the relevant dynamic values, I was still getting a 403 response despite my bucket being public. When I got the public url via the helper method, it then showed me that 'render/image' needed to be 'object' (e.g.:  https://project_id.supabase.co/storage/v1/object/public/bucket/image.jpg?width=500&height=600). 

I know it's mentioned as an example url so I'm not sure if it's different for different circumstances but if not it would be good to update it!

## Describe the improvement

In the two example urls on this page, sub out 'render/image' for 'object'.

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me

**Comment by prathameshpowar1910** [comment]
Hey I see that no has been assigned to this issue so if could you assign this issue to me

**Comment by ayan15888** [comment]
i want to work on this

**Comment by charislam** [comment]
Hi @Olyvar! Are you on a Pro Plan? Image Transformations is only available on the Pro Plan and above

I just tested the render URL on a Pro Plan and it worked, so I'm guessing that might be the issue
