### ISSUE TITLE
Change link route in serverless APIs

### ISSUE THREAD

**Issue by dmnkhvl** [supabase/supabase#18427]
# Change link route in serverless APIs

## Link 

[https://supabase.com/docs/guides/database/connecting-to-postgres](https://supabase.com/docs/guides/database/connecting-to-postgres)

## Describe the problem

When user clicks on the REST / GraphQL / Realtime links they all lead to the REST API page,

## Describe the improvement

Change the links to the corresponding pages:
[https://supabase.com/docs/guides/api#graphql-api-overview](https://supabase.com/docs/guides/api#graphql-api-overview)
[https://supabase.com/docs/guides/graphql](https://supabase.com/docs/guides/graphql)

**Comment by davfre** [comment]
I just checked, and this appears to have been fixed 
https://github.com/supabase/supabase/pull/18771
