### ISSUE TITLE
verifyBeforeUpdateEmail

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#1845]
# Feature request

## Is your feature request related to a problem? Please describe.
User creates an account using a magic link. For some reason user wants to update their email address on the account. At this point there is no way to do it as far as I know

## Describe the solution you'd like

It would be great to have an updateEmail method (maybe similar to resetPasswordForEmail) where verification email is sent to a new requested email address. After the new email is verified, the old email is replaced with the new one.

## Describe alternatives you've considered
At the moment user could change their email directly without confirmation, but this is not ideal, because they might make a mistake, and if they log out, they would loose their access to account, as now their account is associated with wrong email. So magic links are sent to nowhere.

## Additional context

Firebase has a [similar feature](https://firebase.google.com/docs/reference/js/firebase.User#verifybeforeupdateemail) `verifyBeforeUpdateEmail()`.

**Comment by edgarasben** [comment]
@i-pip no way! Awesome, how did you discover this?

**Comment by i-pip** [comment]
I forked the repo, cloned it and just did a lot of `go-to-definition` in vim (also built into vscode I believe) until I stumbled upon [this line in gotrue-js](https://github.com/i-pip/gotrue-js/blob/99a11bbdc62700dc2621f522ac1fea5d905c6cc6/src/GoTrueClient.ts#L244), then I followed it all the way down to [gotrue's user.go](https://github.com/supabase/gotrue/blob/0d2c0b8e5470ed783e3c450a0cedb514840799e2/api/user.go#L119) and found that there is a `validateEmail` method call and [sendEmailChange](https://github.com/supabase/gotrue/blob/0d2c0b8e5470ed783e3c450a0cedb514840799e2/api/user.go#L133)... So I tried em out 😝

**Comment by i-pip** [comment]
Hi @edgarasben So regarding customizing the email template, I had a look under `Authentication/Templates` in the Supabase dashboard and at first it appeared that only "Confirm Signup", "Reset Password", "Magic Link" and "Invite User" were customizable but then I looked at the http request made by changing any of these and noticed `MAILER_TEMPLATES_EMAIL_CHANGE_CONTENT` amongst `MAILER_TEMPLATES_MAGIC_LINK_CONTENT` and the others from above. 

So although it's not implemented in the Supabase dashboard, the api for it already is in place - just a matter of implementing it in the dashboard I guess - the dashboard isn't open sourced yet but @kiwicopple [mentioned that they're working on opening it up in future though](https://youtu.be/a2r-GGILQiA?t=2685). I wouldn't be surprised to see it popup very soon considering the speed at which the Supabase team is building

**Comment by edgarasben** [comment]
Thanks for looking into that! Sending templates through API is even more useful in some cases.

**Comment by jpstrikesback** [comment]
@kiwicopple is it currently possible to update the email change verification template via the API?

**Comment by edgarasben** [comment]
Looks like [the documentation was recently updated](https://github.com/supabase/supabase/commit/029228c18446e8eb46b2d31c0b13e4655c962ebe#diff-dd435bf2fed20073bbd3ac745435bc829493f1d5c5f5130375daff8e5b934430) and now this is supported:

> User email: email updates will send an email to both the user's current and new email with a confirmation link.

**Comment by edgarasben** [comment]
@jpstrikesback seems like this is possible using GoTrue server which is automatically deployed with Supabase:
> When you deploy a new Supabase project, we deploy a new instance of this server alongside your database, and also inject your database with the required auth schema.

Here is the documentation for this GoTrue server: https://supabase.io/docs/gotrue/server/about. Which includes email change template variable: `MAILER_TEMPLATES_EMAIL_CHANGE`. Seems like you can use this GoTrue server API after configuring it in your environmental variables.
