### ISSUE TITLE
The `[+ new column]` button in tables view dashboard does nothing

### ISSUE THREAD

**Issue by mationai** [supabase/supabase#18477]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Clicking the `[+ new column]` button in tables view dashboard does nothing. All adblock has been turned off for the supabase dashboard page.

## To Reproduce

1. Go to https://supabase.com/dashboard/project/<name>/database/tables
2. Click on [n columns] button
3. Click [+ new column] button
4. Nothing happens

## Expected behavior

Able to add new column. To do so, I now have to do so via [...] | edit table.

## System information

- OS: macOS 13.3
- Browser: Chrome 116.0.5845.140
- Version of supabase-js: version on supabase
- Version of Node.js: n/a

**Comment by AprajitKatiyar** [comment]
This works fine on my system:


![Animation](https://github.com/supabase/supabase/assets/86497507/c55722a3-1db5-4e89-a5b7-ef58e9371954)


**System Information**

- OS: Windows 10
- Browser: Brave

**Comment by mationai** [comment]
It now works for me too. Nothing has changed on my end. Possible unrelated commits fixed it? 

You can close if there's nothing to investigate.

**Comment by saltcod** [comment]
This was fixed back when it was reported, but we missed this issue. Thanks for the report!
