### ISSUE TITLE
Partners link hover invisible

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18498]
https://supabase.com/partners/experts/robkendal

On these pages, these two links don't have a proper hover state. 

![screenshot-2023-10-26-at-09 23 32](https://github.com/supabase/supabase/assets/105593/4f9584ee-b7e8-4d8c-93c7-b9b571266074)

**Comment by ayush02dev** [comment]
I wanna work on it please assign to me work on it @saltcod
