### ISSUE TITLE
P1001: Can't reach database server at `db.xytjdgekhpkszazxuoro.supabase.co`:`5432`

### ISSUE THREAD

**Issue by mr-sazzad** [supabase/supabase#18490]
Subject: Issue with Connecting to Supabase Database Server

Dear Supabase Support Team,

I am writing to seek assistance with an issue I am encountering while attempting to connect to my Supabase database server. I am receiving the following error message:

Error: P1001: Can't reach database server at `db.xytjdgekhpkszazxuoro.supabase.co`:`5432`

I have already tried the following troubleshooting steps without success:

- Checked network connectivity and verified that other websites are accessible.
- Verified the firewall settings and ensured that the necessary ports are open.
- Confirmed that the DNS resolution is working correctly.

Despite these efforts, I am still unable to establish a connection to the database server. I believe that the issue might be related to [specify any suspicions or relevant information you might have].

Please provide guidance on how to resolve this issue as soon as possible, as it is impacting my ability to [mention the specific task or project affected by the issue].

Thank you for your prompt attention to this matter. I look forward to your assistance and resolution.

Sincerely,
sazzad karim

**Comment by pileroniel** [comment]
I'm also facing the same issue at times, and I have to restart my server again. 

NB: I'm using prisma to connect to my database

**Comment by VladBrok** [comment]
Hi @mr-sazzad, could you please tell, have this issue been resolved?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
