### ISSUE TITLE
Account access tokens layout broken

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18501]
https://supabase.com/dashboard/account/tokens

The alert here should always be full-width. It needs to be moved out of the flex container.

![screenshot-2023-10-26-at-11 39 27](https://github.com/supabase/supabase/assets/105593/31d353fb-f8f7-4d26-9fef-78eaea4612e3)
![screenshot-2023-10-26-at-11 41 18](https://github.com/supabase/supabase/assets/105593/a6361641-53ac-4293-9918-730e35cb19e2)

**Comment by AbhijeetBiswal** [comment]
Hey @saltcod i am facing this issue. i am not able to login into my account on my local system, please help. 

https://github.com/supabase/supabase/assets/144774379/161dd32d-b782-4995-8bc3-e94001efc5d4
