### ISSUE TITLE
Fields in primary table returned as null in deeply nested query when using .single() and wildcard * in .select()

### ISSUE THREAD

**Issue by Jordaneisenburger** [supabase/supabase#18530]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When performing a deeply nested query using supabase-js to select data from a table (company_profiles) and its related tables, some fields in the primary table are returned as null even though they have values in the database. This issue specifically occurs when using a wildcard * in the .select() method to fetch all columns from the products related table and when the .single() method is used.
## To Reproduce

Here's the problematic query and the corresponding Prisma schema to reproduce the issue:
```sql
model company_profiles {
    company_id  String  @id @db.Uuid
    quote       String? @db.VarChar(230)
    quote_fullname String?
    // ... other fields
    products    products[]
}
model products {
    product_id  String  @id @db.Uuid
    // ... other fields
    company_id  String  @db.Uuid
    company_profile company_profiles @relation(fields: [company_id], references: [company_id])
}
```
```js
  const { data } = await supabase
      .from('company_profiles')
      .select('*, products(*)')
      .eq('url', slug);
```

Steps to reproduce the behavior, please provide code snippets or a repository:

- Define a table company_profiles with fields including quote and quote_fullname.
- Define a related table products that has a relation back to company_profiles.
- Execute the above query with the .single() method.
- Observe that the quote and quote_fullname fields are returned as null even though they have values in the database.

it could be that you need to add more fields to the company_profiles table to it to happen but it seems that random fields that actually have data are set to null. The issue seems to stem from the usage of products(*) in the .select() query. When I specify the fields explicitly like products(name), the problem does not occur. Interestingly, the issue also goes away when the .single() method is not used.

## Expected behavior

All the fields from the company_profiles table should be returned with their actual values, not as null, when performing the nested query, even when using .single()

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) Chrome
- Version of supabase-js: ~2.38.4
- Version of Node.js: [e.g. 18.17.0

**Comment by GaryAustin1** [comment]
I just created the two tables with the table UI.
![image](https://github.com/supabase/supabase/assets/54564956/de30465e-2319-4b63-bb5b-0a1045185a3d)
![image](https://github.com/supabase/supabase/assets/54564956/d720ca4d-6d4a-4ec5-9b6a-e677f2357b41)
And ran:
```
    const { data } = await supabase1
        .from('company_profiles')
        .select('*, products(*)')
        .eq('slug','a')
        .single()
    console.log(data)
    ```
    And it works as long as slug is not duplicated in rows.  When duplicated data it returns just null and there is an error as expected.

**Comment by Jordaneisenburger** [comment]
Mhh that's odd as I don't have duplicate slugs. What happens when there are no rows in the `products` table ? So that `products(*)` will return null as that's my case, sorry didn't mention that.

Anyways It's not blocking as I can still request without the `.single()` method and having it return an array with 1 items. Which also proves the slug is not duplicate. Obviously my `company_profile` table has way more fields which might also cause the issue.

**Comment by GaryAustin1** [comment]
.single() with no row in products and unique slugs.
![image](https://github.com/supabase/supabase/assets/54564956/aa54d2cf-f63e-43b3-81ce-fc3580d2ae40)

I can't imagine that more columns would impact anything.

**Comment by Jordaneisenburger** [comment]
So I just tried to reproduce it myself and somehow it's not happening anymore.. I'll try some more but the issue is probably existing between my keyboard and chair :)
