### ISSUE TITLE
The text in input of new column's default feild is overlapped by the "suggested expressions" menu.

### ISSUE THREAD

**Issue by M0hitReddy** [supabase/supabase#18539]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

while creating an new table-  In new column, a part of the 'default value' field's input text is overlapped by the "suggested expressions" menu. So while typing in the input field the last 6 characters are hidden behind the suggested expressions menu.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'table editor'
2. Click on 'new table'
3. Scroll down to 'columns' and click 'add column'
4. Type in the 'default value' field
5. Observe that the ending part of the text will be hidden

## Expected behavior

While typing in 'default value' field the last 5 to 6 characters of text should not be hidden.

## Screenshots
![Screenshot 2023-10-28 001939](https://github.com/supabase/supabase/assets/114643178/79c3f13c-273d-4bec-839b-3b6b57eaadaa)

## System information

- OS: [Windows]
- Browser (if applies) [chrome]

**Comment by encima** [comment]
Closing as it seems to be resolved in the latest version of the dashboard, please comment if this issue occurs for you (with the latest version) and we will re-open.

<img width="209" alt="image" src="https://github.com/supabase/supabase/assets/517923/188cba95-a828-4150-843f-e5cf306b029f">
