### ISSUE TITLE
SvelteKit ssr documentation is missing Layout Server Load tab

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase#18556]
# Improve documentation

## Link 

[Creating a Supabase client for SSR](https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit)

## Describe the problem

After following the new docs, I get a typescript error in the layout load code.

![image](https://github.com/supabase/supabase/assets/25783093/194e5234-0ec2-4b5d-8714-60cb3b6b098e)

This is throwing because we need a `+layout.server.ts` file which returns the session.

![image](https://github.com/supabase/supabase/assets/25783093/b3bf1a7a-d93d-4004-988d-baf8f581632b)

## Describe the improvement

Add a tab between `Hooks` and `Layout Load`, which adds the needed code.

**Comment by silentworks** [comment]
Good catch, will get this added shortly.

**Comment by thibistaken** [comment]
Yes, thank you. Had the same issue and it fixed it. I spent quite some time on it.

**Comment by silentworks** [comment]
We've merged a PR that addresses this issue. Thanks again for reporting this.
