### ISSUE TITLE
`supabase link` connection fail (`db.*.supabase.co` hostname resolving error)

### ISSUE THREAD

**Issue by d9k** [supabase/supabase#18561]
```
> npm exec supabase link --project-ref=qotvissymxndwpcjsmmk
Enter your database password (or leave blank to skip): ********
failed to connect to `host=db.qotvissymxndwpcjsmmk.supabase.co user=postgres database=postgres`: hostname resolving error (lookup db.qotvissymxndwpcjsmmk.supabase.co on 8.8.8.8:53: read udp 10.0.0.107:48636->8.8.8.8:53: i/o timeout)
```

**Comment by d9k** [comment]
Was okay several hours ago

**Comment by d9k** [comment]
Found [Supavisor | Connecting to your database | supabase doc](https://supabase.com/docs/guides/database/connecting-to-postgres#supavisor)
		
> On 15th January 2024 PgBouncer will be disabled. Additionally, your Supabase database domain (db.projectref.supabase.co) will start resolving to an IPv6 address. No changes are required if your network supports communicating via IPv6. Otherwise, update your applications to use Supavisor which will continue to support IPv4 connections.
> [Full details here](https://github.com/orgs/supabase/discussions/17817).

> `postgres://user.[YOUR-PROJECT-ID]:[YOUR-PASSWORD]@aws-0-[REGION].pooler.supabase.com:6543/postgres`

How to configure supabase CLI to work with Supavisor instead of

**Comment by d9k** [comment]
Works with another internet connection.

Probably was a problem with IPv6 hostnames resolution with the first internet connection.

But question remains

**Comment by encima** [comment]
Hey @d9k 

That URL: `db.<PROJECT-REF>.supabase.co` is pointing directly to your DB, no pgBouncer or Supavisor.

The Supavisor URL format is the one you suggested above. The CLI will use the DB URL to connect to your instance and not go through a pooler.

**Comment by shadibarhoumi** [comment]
For those struggling with this `npm install supabase` to update supabase to the latest version.
