### ISSUE TITLE
function auth.email() does not exist

### ISSUE THREAD

**Issue by chhpt** [supabase/supabase#1857]
# Bug report

When i try to create a user policy that contain [built-in helper function `auth.email()`](https://supabase.io/docs/learn/auth-deep-dive/auth-policies#resources) on app.supabase.io, i got the follow error

```
function auth.email() does not exist
```

SQL

```
create policy "Users can update own email"
  on profiles for update
  using ( auth.email() = email );
```

![image](https://user-images.githubusercontent.com/19288423/121048138-1f37f380-c7e9-11eb-973f-dcfae8995c91.png)

PS: Can supabase support more build-in functions for getting more userinfo like username and so on?

**Comment by inian** [comment]
Hey @chhpt, this function does not exist by default. But you can create it with this
```
create or replace function auth.email() returns text as $$
  select nullif(current_setting('request.jwt.claim.email', true), '')::text;
$$ language sql;
```

**Comment by nstrelow** [comment]
That is very nice, I needed that snippet a while ago.

Thanks

**Comment by inian** [comment]
Cool, closing the issue. Re-open if there are any other issues.
