### ISSUE TITLE
Prisma documentation is missing (404)

### ISSUE THREAD

**Issue by Xananax** [supabase/supabase#18570]
The url https://supabase.com/partners/integrations/prisma leads to a 404.

The link still exists in the list on https://supabase.com/partners/integrations, so this doesn't seem to be purposeful.

**Comment by Hallidayo** [comment]
Hi @Xananax - The links seems to be okay now. Is it okay on your side now?

**Comment by Xananax** [comment]
Yes, I confirm the link works for me now.

**Comment by wontondon** [comment]
I'm still seeing the 404 when accessing the prisma link from the documentation.  This is returning a  404 when clicking prisma on the integrations page - https://supabase.com/partners/prisma.

**Comment by GaryAustin1** [comment]
I'll re-open as I can't see it now either.

**Comment by fernandosmither** [comment]
Off for me too!

**Comment by charislam** [comment]
Odd, I'm seeing it now: https://supabase.com/partners/integrations/prisma

Is it still not working for you?

**Comment by IzaakPrats** [comment]
fwiw I've been following along for a few days since I also saw a 404 page. It's working now -- wonder what the root cause is? Seems like it's been off/on for past two weeks.

**Comment by fernandosmither** [comment]
yeah,, it's back on again...

Issued a [today-up-to-date](https://web.archive.org/web/20231115180130/https://supabase.com/partners/integrations/prisma) backup for future reference on the wayback machine

**Comment by fernandosmither** [comment]
I think we shouldn't close this issue until the team gets to the root cause, weird that a static link has been unreliable

**Comment by charislam** [comment]
@kamilogorek I think you're in charge of integrations so maybe you have some idea why this is being flaky?

**Comment by encima** [comment]
Closing due to age; it seems to be have been working for the past few months. Confirm that both links currently work.
