### ISSUE TITLE
allow access tokens to be generated for a specific org or a project

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#18584]
Hi,
I just realized that "Personal access tokens can be used to control your whole account and use features added in the future. Be careful when sharing them!". I am worried about possible security risks since users can access my full account with Access Token **even projects that I don't want him to access**.

I would like to have the option to generate an Access Token per organization/Project.

@kiwicopple @MildTomato @awalias @gregnr

<img width="1046" alt="Screenshot 2023-10-30 at 3 09 59 PM" src="https://github.com/supabase/supabase/assets/21134455/ceeec9e5-f1b6-4827-a5dd-1f593bf9462f">

**Comment by kangmingtay** [comment]
Hi @Akash187, you shouldn't sharing your personal access tokens with other users. Personal access tokens are designed to only be shared with trusted parties like the Supabase CLI. 

The team does plan on having some form of scoped access in the future but it is not actively being worked on in view of other priorities.

**Comment by Akash187** [comment]
Hello @kangmingtay, thank you for updating the title. I initially assumed that I had to generate an access token as the Owner for every invited member. However, upon review, I discovered that each member can create their own access token. It seems I was a bit confused. 

Please feel free to mark this as resolved or delete it. 
Thank you.

**Comment by x0good** [comment]
@kangmingtay as I see, it's still security issue. If some user generate https://supabase.com/dashboard/account/tokens
it give access to all projects user has access and *it's not possible to set scope for specific projects (like test or production)*

should be New Token with drop down for ALL project/organisation or for specific only
