### ISSUE TITLE
Rate limit with custom SMTP

### ISSUE THREAD

**Issue by matart15** [supabase/supabase#18589]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
    Because i was recieving email. suddenly rate limit error. nothing chaged on code
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 
    All discussion suggest to setup custom SMTP. then it is solved. But I already setup custom SMTP

## Describe the bug

I setup custom SMTP.
![image](https://github.com/supabase/supabase/assets/17027219/f7f0690c-4a9d-4e30-8cdb-cfd0b0dd2ccb)

My email was coming from my custom address.

Still in middle of development it started giving me `429: Email rate limit` error.
![image](https://github.com/supabase/supabase/assets/17027219/d2408793-e5e6-4066-a9ce-259bc5b2f863)

I thought it is unrestricted on custom SMTP
https://github.com/orgs/supabase/discussions/15896

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

not sure. maybe call this multiple times
```ts
   const redirectTo = `${origin}/update-password`;
      const passwordResetEmailResponse =
        await supabase.auth.resetPasswordForEmail(data.email, {
          redirectTo,
        });
```
## Expected behavior

there should not be rate limit on custom SMTP

## Screenshots

wrote on description above

## System information

- OS: windows
- Browser chrome
- Version of supabase-js: "@supabase/supabase-js": "2.38.4",
- Version of Node.js: v18.17.1

**Comment by matart15** [comment]
Looks like I have sent 88 message in last hour then hit the rate limit 

![image](https://github.com/supabase/supabase/assets/17027219/686267e1-f02c-4076-a386-f0a0a41e7ebf)

142 for last day
![image](https://github.com/supabase/supabase/assets/17027219/15bebf75-609f-445b-8c85-d03d726d6eb8)

**Comment by matart15** [comment]
Currently our app is in development.

I am very concerned if this is going to happen when client releases the app to public.
App is using email registration. If rate limit happens client will lose users.

**Comment by kiwicopple** [comment]
hey @matart15 - could you please reach out to support here so that we can identify the project ID? https://supabase.com/dashboard/support/new

this is more likely a support/platform issue - we can reopen if it turns out to be soemthing in the Auth server (https://github.com/supabase/gotrue)

**Comment by matart15** [comment]
@kiwicopple 
Thank you. I will send support issue

**Comment by GaryAustin1** [comment]
There is a email rate limit setting even for custom here:
![image](https://github.com/supabase/supabase/assets/54564956/d24df7b6-99fe-4d0e-aaf6-1dd127a0c2c4)
That was just moved from the SMTP provider screen to this new rate limit screen.
Is this possibly involved?
