### ISSUE TITLE
"ALTER SYSTEM" command permission denied error

### ISSUE THREAD

**Issue by ShanArosh** [supabase/supabase#18585]
### Discussed in https://github.com/orgs/supabase/discussions/18581

<div type='discussions-op-text'>

<sup>Originally posted by **ShanArosh** October 30, 2023</sup>
I'm in a problem where I need to change timescale-db extension license to community license from apache license.
otherwise their core functionalities wouldn't work like ,
 - create materialized view

I tried running
 ```
ALTER SYSTEM SET timescaledb.license_key = 'timescale'; 
```
and got permission denied error 

```
ERROR:  42501: permission denied to set parameter "timescaledb.license_key"
```
</div>

**Comment by encima** [comment]
I am afraid that cannot be done as the [Community License](https://github.com/timescale/timescaledb/blob/main/tsl/LICENSE-TIMESCALE) is prohibited to database providers, such as Supabase.

If you're using the self-hosted version, you could change this as your database super user but I would confirm this with Timescale first (I am not a lawyer!)

**Comment by mansueli** [comment]
It is against the Timescale license for us to host the community version in our cloud.

https://docs.timescale.com/about/latest/timescaledb-editions/#timescaledb-community-edition

> You cannot sell TimescaleDB Community Edition as a service, even if you are the main contributor.

Full license:


https://github.com/timescale/timescaledb/blob/main/tsl/LICENSE-TIMESCALE
