### ISSUE TITLE
Resending confirmation email (supabase.auth.resend) gives error "email must be provided for type email"

### ISSUE THREAD

**Issue by Jonny1987** [supabase/supabase#18595]
When running the following code in dart:

```
supabase.auth.resend(
          type: OtpType.email,
          email: 'me@email.com',
    )
```

I get the error:

`Unhandled Exception: 'package:gotrue/src/gotrue_client.dart': Failed assertion: line 555 pos 14: '[OtpType.signup, OtpType.emailChange].contains(type)': email must be provided for type email`

And looking at the resend function function in the supabase code, the following lines don't seem to make sense:
```
    if (email != null) {
      assert([OtpType.signup, OtpType.emailChange].contains(type),
          'email must be provided for type ${type.name}');
    }
```

At the assert statement email can't be null, but the error is asking the email to be provided. Also, if email is not null it should be allowing OtpType.email to be one of the types I think.

**Comment by jbcallv** [comment]
Has this issue been taken? I can take a stab at it.

**Comment by luhart** [comment]
@Jonny1987 You're missing a closing ' here `email: 'me@email.com,`

**Comment by encima** [comment]
Feel free to open a PR for this if you are still experiencing the issue!

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by JHaberlsz** [comment]
For anybody finding this, this happens because the wrong OtpType was used. To resend a confirmation email OtpType.signup has to be used.
