### ISSUE TITLE
Incorrect default DB password for local development: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by mrcgj** [supabase/supabase#18603]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The DB string given by the documentation (e.g. [here](https://supabase.com/docs/guides/functions/connect-to-postgres) and [here](https://supabase.com/docs/guides/cli/local-development)) to connect from an edge function to the local postgres instance seems to be incorrect.

## To Reproduce

1. Start a local instance of Supabase
2. Create an edge function importing deno-postgres to connect directly to the DB
3. Create a client (in my case I'm creating a pool with `const pool = new postgres.Pool(databaseUrl, 20, true);` then grabbing a connection with `const connection = await pool.connect();`)
4. For `databaseUrl` use the string given in the local dev instructions: `postgresql://postgres:postgres@host.docker.internal:54322/postgres`
5. Call the function and see it fail on the `connect()` line with **password authentication failed for user "postgres"**.

## Expected behavior

The edge function should successfully connect to the DB with these default credentials, since I haven't changed them.

## System information

- OS: WSL2 on Windows 11
- Version of supabase-js: 2.33.1
- Version of Node.js: v18.17.0

## Additional context

- I'm able to connect to the DB through psql via `docker exec`, and it doesn't require any password in that case.
- I've also checked that there aren't any special options set in the DB section of config.toml. This is all I have there:

```
[db]
port = 54322
major_version = 15
```

**Comment by soedirgo** [comment]
Can you share which version of deno-postgres you're using? I was able to reproduce this on 0.16.1 but not 0.17.0.

**Comment by mrcgj** [comment]
In the meantime, I tentatively upgraded to 1.17.0 and the password issue does seem to go away. 👍
