### ISSUE TITLE
Undefined webhook name

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18615]
When you edit → update a webhook, the toast has undefined as the name. It should use the name of the webhook instead.
<img width="610" alt="screenshot-2023-10-31-at-09 54 05" src="https://github.com/supabase/supabase/assets/105593/fe454ffd-edb8-4237-ac17-8ea9f2fcc60c">

**Comment by yousseefben** [comment]
hello @saltcod , I just pushed a new PR that fixes the issue, we can discuss further more about the approach, as this marks my first contribution to the project. Thanks for the opportunity! :)

**Comment by yousseefben** [comment]
hello @saltcod, I just pushed a new PR that fixes the issue, we can discuss further more about the approach, as this marks my first contribution to the project. Thanks for the opportunity! :)

**Comment by saltcod** [comment]
fixed
