### ISSUE TITLE
SvelteKit Quickstart

### ISSUE THREAD

**Issue by dawnofmidnight** [supabase/supabase#1863]
# Improve documentation

## Describe the problem

There isn't exactly a problem, it's a suggestion for a new resource

## Describe the improvement

Similar to the [Next.js Quickstart page](https://supabase.io/docs/guides/with-nextjs), it would be nice if there was one for [SvelteKit](https://kit.svelte.dev). I would envision this as if it were the same as the Next.js, just tailored toward SvelteKit

## Additional context

I'd love to write this myself, but I want to make sure that this would be okay and that people would be interested.

**Comment by kiwicopple** [comment]
we have this PR open: https://github.com/supabase/supabase/pull/1855

Would that work for you @dawnofmidnight ?

**Comment by dawnofmidnight** [comment]
Oh, I didn't see that. Thank you, that's wonderful!

**Comment by yustarandomname** [comment]
#1855 is for regular svelte, but since the quickstart does not use routing it is practically the same for Sveltekit. If you would like an in-depth tutorial on supabase with Sveltekit, I would recommend you to watch [this video](https://www.youtube.com/watch?v=j4AV2Liojk0)
