### ISSUE TITLE
Views deleted from public schema after a few hours

### ISSUE THREAD

**Issue by jonesmo** [supabase/supabase#18649]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the SQL Editor in the Supabase dashboard in Chrome, I've created and run several queries beginning with `CREATE view
  public.view_name AS ...`.  I can then see my views in the Table Editor under the `public` schema.  However, after a few hours, these views disappear from the Table Editor, and my downstream application can no longer access them and throws an error.  It seems the views are getting deleted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to SQL Editor
2. Click on New query
3. Paste:
```
CREATE view
  public.view_name AS
SELECT
  prj.col1,
  prj.col2 AS project_name,
  lt.hours
FROM
  service_float.logged_time AS lt
  join service_float.projects AS prj ON lt.project_id = prj.project_id
WHERE
  prj.col3=0
```

## Expected behavior

A view called `view_name` is visible as a table in the Table Editor under the `public` schema.  This view persists unless explicitly deleted.

## System information

- OS: macOS Sonoma 14.0
- Browser (if applies) Chrome version 118.0.5993.117

**Comment by MildTomato** [comment]
@jonesmo have you contacted Supabase Support ?

This sounds like it could be an isolated issue.

https://supabase.com/dashboard/support/new

**Comment by jonesmo** [comment]
Thanks, filed a support request.  I don't know if it's intentional, but filing a GitHub ticket is the first suggested way to get help listed at https://supabase.com/support

**Comment by jonesmo** [comment]
It did!  It turned out to be a dbt/Airbyte issue.
