### ISSUE TITLE
Error message not properly displayed in schemas error

### ISSUE THREAD

**Issue by maxfornacon** [supabase/supabase#18647]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Currently there is an issue with loading the schemas on the Table Editor Page. I'm not reporting the issue itself since it's already under investigation but how the error is displayed. Seems the error is not rendered as HTML properly as you can see in the screenshot.

## To Reproduce

Go to 'Table Editor' Page when there is an error loading the schemas.

## Expected behavior

Either render the HTML of the error or display just plain text without the HTML tags.

## Screenshots

<img width="313" alt="Screenshot 2023-11-01 at 18 49 37" src="https://github.com/supabase/supabase/assets/27596468/f1805685-4057-4359-965c-c7bb6b749c46">

**Comment by saltcod** [comment]
https://github.com/supabase/supabase/pull/18648
