### ISSUE TITLE
supabase: TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by jexroid** [supabase/supabase#18668]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

i used supabase CLI to create a local hosted for myself and in **SQL Editing** I tried to enable vector extension and this happened:
![Capture](https://github.com/supabase/supabase/assets/87432211/833e00e7-1a65-423a-9d2c-b6a18c5f65d7)

this happens for some commends but common commands like:
```sql
select * from
  (select version()) as version,
  (select current_setting('server_version_num')) as version_number;
```
works just fine.

running on:
OS: windows
supabase CLI: 1.110.1
chrome: 119.0.6045.105
node: 18.17.1

on WSL with supabase version: 1.106.1 this will happened:
`Error running SQL: Connection terminated unexpectedly`
then database gets into recovery mode : `Error running SQL: the database system is in recovery mode`

**Comment by AlpacaAlgo** [comment]
I am also facing similar issue with self hosted docker instance. Do we have any resolution to fix this issue.

**Comment by jexroid** [comment]
Im pretty sure that i dont have any error in this command @megacherry :
```sql
create extension if not exists vector
```
im sure that vector extention was never enabled before and I'm also using docker.

**Comment by jexroid** [comment]
hey @mlukasik-dev,
actually, SQL errors lead to dashboard crashes!
according to what @megacherry mentioned:
[https://github.com/supabase/supabase/issues/18708](https://github.com/supabase/supabase/issues/18708)

**Comment by jexroid** [comment]
I was advised by the Supabase Discord server to contact support to solve this issue. because it may take time until supabase team reaches out.

Perhaps this could assist individuals with the problem temporarily.

**Comment by Akash187** [comment]
I have same issue opened a bug report https://github.com/supabase/supabase/issues/18708

**Comment by smoothclose** [comment]
Confirm I also have the same issue. Anytime an exception is raised in SQL editor it crashes. Simple test to reproduce:

```sql
create or replace function raise_exception()
    returns void 
as $$
begin
    
    raise exception using message = 'Crash, crash baby!';

end;
$$ language plpgsql security definer
set search_path = public;

select raise_exception(); -- crashes

```

**Comment by saltcod** [comment]
Thanks all. This issue should be addressed in the latest release. Please let us know if you still experience this after updating.
