### ISSUE TITLE
Need to be able to add caching options on supabase requests.

### ISSUE THREAD

**Issue by The-Code-Monkey** [supabase/supabase#18693]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the latest version of NextJs it caches the endpoints assuming they won't change, if the endpoints are cached it won't refire them meaning my data never updates, it also is caching the pages meaning any updates i make to them even on local do not change.

**Comment by GaryAustin1** [comment]
I'm not sure how this is a Supabase bug.  There are methods in next.js to turn off the caching.  
Here are two of several Discord discussions on it with ways the users turned it off.
https://discord.com/channels/839993398554656828/1141610708224708689
https://discord.com/channels/839993398554656828/1165278643539415070/1165290825513717880

Going to close for now as does not seem like a Supabase bug.
