### ISSUE TITLE
Supabase Local Development Dashboard Crash on Error

### ISSUE THREAD

**Issue by Akash187** [supabase/supabase#18708]
# Bug Report

The dashboard crashes when there is an error. It leads to a loss in queries written in the Editor.

https://github.com/supabase/supabase/assets/21134455/f9c2e671-5b68-43a2-a9b8-b91b731f5d0e

**Comment by Kiran1689** [comment]
Hi, 
Please share your table structure.

**Comment by Akash187** [comment]
@Kiran1689 Yes, you got it right that is my issue why does the UI crash if the function is not defined? Why can I just get the error? Similar to what we see in remote Studio.

**Comment by Akash187** [comment]
@megacherry I Hope so.

**Comment by saltcod** [comment]
Thanks all. This issue should be addressed in the latest release. Please let us know if you still experience this after updating.
