### ISSUE TITLE
Error when creating database trigger for `user auth` table locally in supabase

### ISSUE THREAD

**Issue by kyle1373** [supabase/supabase#18712]
## Describe the bug

When creating a database trigger for the `users auth` table locally via supabase localhost, the trigger does not get created and instead throws an error after refreshing the page

<img width="1449" alt="image" src="https://github.com/supabase/supabase/assets/59634395/04fad3ae-fc95-4757-b085-29a2a6d7849c">

## To Reproduce

1. Follow local supabase initialization https://supabase.com/docs/guides/cli/local-development
2. Create a database trigger for `users auth` table through Database -> Triggers
3. Refresh page
4. Error occurs

## Expected behavior

The database trigger should be created

## System information

- macOS
- Chrome
- supabase v1.106.1

**Comment by GaryAustin1** [comment]
This is odd as you should not be allowed to use auth for triggers in the UI.  On hosted it won't offer the auth schema as an option to create a trigger.  It also has this warning when you select auth.
![image](https://github.com/supabase/supabase/assets/54564956/90c1d5d5-6964-47d5-b4ee-19bed83f5658)

**Comment by kyle1373** [comment]
> This is odd as you should not be allowed to use auth for triggers in the UI. On hosted it won't offer the auth schema as an option to create a trigger. It also has this warning when you select auth. ![image](https://user-images.githubusercontent.com/54564956/280479808-90c1d5d5-6964-47d5-b4ee-19bed83f5658.png)

According to [this discussion](https://github.com/orgs/supabase/discussions/226#discussioncomment-89148), you're able to create a trigger on the auth table to add additional values to a user (such as a name) since it's more secure and on the server. I originally did two calls to supabase (one to signup the user and the other to fill a separate profile table for this new information), but on the client I'm afraid of its security.

**Comment by GaryAustin1** [comment]
You can create a trigger on auth.users.  You just have to do it with the SQL editor.  There an example of the code in the Quickstarts there for user management.

**Comment by kyle1373** [comment]
Yeah just got the trigger to work. Interesting how users aren't able to create the trigger in the supabase ui but are able to create it in the SQL editor. Would be a great feature to add since I know many users use two supabase calls on the client instead of using a db trigger.

**Comment by GaryAustin1** [comment]
I'm going to close this.  If you want to suggest an enhancement  I would do that as with a feature enhancement request in discussions.
