### ISSUE TITLE
Right sidebar with topic outline not scrollable

### ISSUE THREAD

**Issue by martypdx** [supabase/supabase#18736]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
On a docs page like [CLI config](https://supabase.com/docs/guides/cli/config) with a lot of topics that overflow the vertical height. The right side bar scrolls a small amount until the content hits the top of container, then doesn't scroll

## To Reproduce
Go to a docs page like [CLI config](https://supabase.com/docs/guides/cli/config) with a lot of topics that overflow the vertical height. Try and scroll down on the right side bar.

## Expected behavior

The outline topics scroll

## System information

- OS: macOS
- Browser: chrome, safari, firebox

**Comment by yousseefben** [comment]
Fixed it, feel free to review it :)

**Comment by martypdx** [comment]
@yousseefben I opened the dev tools on the live site and made that change and can confirm it fixes the issue.

**Comment by jonshung** [comment]
Following up on @yousseefben 's fix, I've modified it to align with the page's current expected behavior.

**Comment by gregnr** [comment]
Fixed via https://github.com/supabase/supabase/pull/18746
