### ISSUE TITLE
I can't set 'ignoreUnknownKeys = true' in Kotlin Sdk

### ISSUE THREAD

**Issue by MohamedRejeb** [supabase/supabase#18778]
Hi,
I'm trying to set 'ignoreUnknownKeys = true' so I can get data without specifying all the fields in the Dto.

```kotlin
httpConfig {
    install(ContentNegotiation) {
        json(Json {
            ignoreUnknownKeys = true
        })
    }
}
```

But this doesn't work.

**Comment by dshukertjr** [comment]
Hi @MohamedRejeb,

Thanks for opening this issue with us. The issue seems specific to the Kotlin library, but would you be able to open an issue there where the maintainer should be able to assist you?
https://github.com/supabase-community/supabase-kt
