### ISSUE TITLE
Issue with Theme Toggle Button on the Homepage

### ISSUE THREAD

**Issue by Kiran1689** [supabase/supabase#18773]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The theme toggle button on the homepage is non-functional and is not clickable.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Visit the Supabase homepage [https://supabase.com/](https://supabase.com/)
2. Scroll down to bottom of the page.
3. Attempt to click on the theme toggle button.

## Expected behavior

The theme toggle button should be clickable, allowing users to switch between themes 

## System information

- OS: [Windows]
- Browser [chrome, MS Edge]

**Comment by yousseefben** [comment]
@Kiran1689 I checked this point, and I found that the behavior is forced for the homepage when the path is '/', I don't know if it's something wanted or outdated, waiting for the confirmation from the team so I can work on it.

**Comment by saltcod** [comment]
Yup that's on purpose. Homepage currently locked to dark mode.
