### ISSUE TITLE
resumable-upload-uppy example not working as expected

### ISSUE THREAD

**Issue by RilDev** [supabase/supabase#18788]
# Improve documentation

## Link 

https://github.com/supabase/supabase/tree/master/examples/storage/resumable-upload-uppy

## Describe the problem

The resumable upload doesn't work. It looks like the bearer token key is missing.

## Describe the improvement

The resumable upload should work once all indicated keys have been given.

## Additional context

I have a fix, please consider merging it to master.

**Comment by burggraf** [comment]
@saltcod will this fix be merged?

**Comment by saltcod** [comment]
Build was stuck! Merged! Thanks @RilDev!
