### ISSUE TITLE
Storage right click menu on buckets has wrong background color

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18800]
To reproduce:

1. create a bucket 
2. right click to view context menu
3. see white background

<img width="687" alt="screenshot-2023-11-07-at-16 18 15" src="https://github.com/supabase/supabase/assets/105593/50f308b1-0bb0-4811-a832-f6e1c9ac2ef5">

**Comment by AlexMNet** [comment]
Hi @saltcod I am interested on fixing this issue. I went through the contributing guide and got the project running but keep getting a 400 fetch failed error when trying to create a bucket. Wondering if I am missing something in the env files?

**Comment by saltcod** [comment]
https://github.com/supabase/supabase/pull/18802
