### ISSUE TITLE
GraphiQL IDE is in light mode

### ISSUE THREAD

**Issue by ClemCa** [supabase/supabase#18806]
# Bug report

- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The GraphiQL IDE is in light mode instead of the supabase base dark theme.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com/dashboard/project/[your project]/database/graphiql)'
2. After the page loaded, the IDE is white and light grey

## Expected behavior

The IDE should be consistent with the theme of the overall website

## Screenshots

Screenshot in a fresh incognito session (no extensions):

![image](https://github.com/supabase/supabase/assets/26848693/7c60e126-fd80-410d-ae27-d0bef5ff0f42)

- OS: Windows
- Browser (if applies): Chrome

## Additional context

This seems to be related to the recent move of the IDE from the API Docs tab to the Database tab.

**Comment by fsansalvadore** [comment]
I can't seem to replicate. @ClemCa can you confirm this is still happening? 
What if you switch to light mode and back to dark mode?

**Comment by ClemCa** [comment]
@fsansalvadore Not home so can't confirm, but it seems to have been fixed by https://github.com/supabase/supabase/pull/18802 , which has been merged.

**Comment by fsansalvadore** [comment]
I found out this was happening when selecting "System" theme option. Fixing it now!
