### ISSUE TITLE
`supabase.auth.verifyOtp` triggers error when validating local development generated code

### ISSUE THREAD

**Issue by cacosandon** [supabase/supabase#18834]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When you use Supabase Local Development as a server locally, OTP codes sent to email (as shown below in the screenshots section) raises error as invalid or expired.

## To Reproduce

Steps:

1. Follow steps on https://supabase.com/docs/guides/cli/local-development to setup the Supabase Local Environment
2. Generate a code with:
```typescript
const response = await supabase.auth.admin.generateLink({
    type: "magiclink",
    email,
    options: {
      redirectTo,
    },
  });

  const otpCode = response.data.properties?.email_otp;
```
4. Use the code and validate with `supabase.auth.verifyOtp`
5. See error of invalid or expired

## Expected behavior

Should behave as the same as using Supabase hosted environment.

## Screenshots

<img width="462" alt="Screenshot 2023-11-08 at 18 14 12" src="https://github.com/supabase/supabase/assets/30879716/fac2aec3-64c6-4a4e-b741-6a7436192903">
<img width="979" alt="Screenshot 2023-11-08 at 18 14 36" src="https://github.com/supabase/supabase/assets/30879716/9de64296-0e3a-49e6-89bf-671fe4f20be6">

## System information

- macOS
- Chrome
- Version of supabase-js: 2.29.0
- Version of Node.js: 18.15.0

**Comment by tranhoangvuit** [comment]
Hi @cacosandon, is the issue persistent? Could you try with the latest version?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
