### ISSUE TITLE
Not Installing Node Modules

### ISSUE THREAD

**Issue by loat007** [supabase/supabase#18842]
![Screenshot 2023-11-09 093743](https://github.com/supabase/supabase/assets/101885228/36ba5b4a-e0a0-4b00-a937-4a1c336d57d9)
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by saltcod** [comment]
Hey @loat007 — could you provide some more details about what you're trying to do here?

**Comment by Bayyana-kiran** [comment]
@loat007 can u please provide more details?

**Comment by Bayyana-kiran** [comment]
i got the error fixed....just download new verison node.js and install the dependencies.

**Comment by Bayyana-kiran** [comment]
u have to install new version of node.js ...thats it

**Comment by encima** [comment]
So....closing this 🤷
