### ISSUE TITLE
How to integrate clerk org role based auth with supabase row level security in database and storage.

### ISSUE THREAD

**Issue by codergigachad** [supabase/supabase#18858]
# Improve documentation

## Link 
https://supabase.com/partners/integrations/clerk

## Describe the problem
I am using t3-stack along with clerk as auth and supabase for database and storage. Can you please update the docs and add how to implement clerk org roles in supabase RLS correctly. Currently both the supabase and clerk docs doesn't mention user roles.

## Describe the improvement
Please make it seamless to integrate clerk auth with supabase storage. I think the main issue is that supabase doesn't have the user data of clerk in the database, for that I think you should add webhooks to the docs as well. RLS policies are currently not working with clerk.

## Additional context
A workaround solution can be to create a users table and add clerk data to it through webhooks and use it for RLS policies. Since adding the clerk data directly to auth table looks impossible. If this solutions sound good please give a tutorial for it in docs.
This video might help what I am trying to say:- https://youtu.be/NgBxrIC1eHM?si=4uFFWNLku_L9qFTU

**Comment by GaryAustin1** [comment]
I'm not sure who maintains the guide but it is also outdated and uses auth.setAuth() Supabase call which is old v1 supabase-js code.

**Comment by sumosp** [comment]
I think I can't use supabase now for the ai sass I am building. BTW thanks @GaryAustin1 for replying me twice first in the discord then here aswell.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
