### ISSUE TITLE
Query explain fails on storage rpc function list_objects 

### ISSUE THREAD

**Issue by goszczynskip** [supabase/supabase#18856]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I can't run explain on storage rpc call copied from supabase docs. 

## To Reproduce

- Initialize local supabase instance via npx supabase init
- Create list_objects function to allow quering storage more efficiently following [docs](https://supabase.com/docs/guides/storage/production/scaling#optimize-listing-objects)
- Allow explaining queries by granting role to authenticator
```
alter role authenticator set pgrst.db_plan_enabled to true;
notify pgrst, 'reload config';
```
- run rpc call 
```
    const result = await supabaseClient.rpc('list_objects', {
      bucketid: 'bucketid',
      prefix: image,
      limits: 1,
      offsets: 0,
    }).explain();
```
- Error is returned
```
error: {
    code: '42883',
    details: null,
    hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
    message: 'function string_agg(record, unknown) does not exist'
  }
```

## Expected behavior

I can see query plan returned by postgrest

## System information

- OS: [e.g. macOS]
- Version of supabase-js: 2.38.4
- Version of supabase: 1.110.1
- Version of postgrest: 11.2
- Version of Node.js: 18.17.1

**Comment by isaacharrisholt** [comment]
I'm having the same issue when running `.explain()` on a stanrdard select query.

**Comment by steve-chavez** [comment]
This was fixed on https://github.com/supabase/postgrest-js/pull/506, we'll be making a new `supabase-js` release soon.

**Comment by steve-chavez** [comment]
- Make sure to use supabase-js v2.38.5 https://github.com/supabase/supabase-js/releases/tag/v2.38.5
- `explain()` is disabled by default, enable it with: https://supabase.com/docs/guides/api/rest/debugging-performance#enabling-explain
