### ISSUE TITLE
Cannot run SQL to create any unique constraints

### ISSUE THREAD

**Issue by michaelminhvo** [supabase/supabase#1886]
# Bug report

## Describe the bug

I am adding a unique constraint on multiple columns. I get generic error message `could not create unique index "test_constraint"

I've tried multiple types of commands.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

In the SQL editor, run the raw SQL command
```
ALTER TABLE sub_product 
    ADD CONSTRAINT test_constraint UNIQUE (product_id, business_id);
```

OR 

```
ALTER TABLE sub_product ADD UNIQUE (product_id, business_id);
```

## Expected behavior

It should return `success`

## Screenshots

<img width="964" alt="Screen Shot 2021-06-08 at 2 07 55 PM" src="https://user-images.githubusercontent.com/1610756/121235532-fb18f880-c862-11eb-9a6e-a0c82f9a6850.png">

## System information

The supabase online UI

**Comment by steve-chavez** [comment]
Can you try running the same statement with `psql` or other database client? It's possible that the UI is not showing the error message details, which should give a hint as to why the constraint cannot be created (it's usually due to a duplicate row).

**Comment by liaujianjie** [comment]
Try creating a unique index and then creating a unique constraint from that index?

```psql
CREATE UNIQUE INDEX sub_product 
ON sub_product_product_id_business_id_idx (product_id, business_id);

ALTER TABLE sub_product
ADD CONSTRAINT test_constraint
UNIQUE USING INDEX sub_product_product_id_business_id_idx;
```

**Comment by michaelminhvo** [comment]
> Can you try running the same statement with `psql` or other database client? It's possible that the UI is not showing the error message details, which should give a hint as to why the constraint cannot be created (it's usually due to a duplicate row).

Correct, I did not delete the bad data before running the constraint. 

Thanks! Yeah the UI is not displaying the complete error messages. The CSV download is also broken - was hoping more details were in there. Here's what the CSV shows when opened:

<img width="358" alt="Screen Shot 2021-06-08 at 3 18 27 PM" src="https://user-images.githubusercontent.com/1610756/121244383-cca01b00-c86c-11eb-8773-36a7c179b4f1.png">
