### ISSUE TITLE
User Management App with React example has a bug

### ISSUE THREAD

**Issue by vincenzon** [supabase/supabase#18884]
This line:

https://github.com/supabase/supabase/blob/8c03a625effd7163e006a101fa0fc2dcc9518569/apps/docs/pages/guides/getting-started/tutorials/with-react.mdx#L172

The reference to `avatarUrl` should be: `avatar_url`.

```
const updates = {
      id: user.id,
      username,
      website,
      avatarUrl, 
      updated_at: new Date(),
    }
```

should be:

```
const updates = {
      id: user.id,
      username,
      website,
      avatar_url, 
      updated_at: new Date(),
    }
```

**Comment by hgseo16** [comment]
It seems to me that there should be an input box for `avatar_url` just like for `username` and `website` states.

```js
      <div>
        <label htmlFor="avatar_url">Avatar Url</label>
        <input
          id="avatar_url"
          type="text"
          required
          value={avatar_url || ''}
          onChange={(e) => setAvatarUrl(e.target.value)}
        />
      </div>
```

Only then, will the function `updateProfile` no longer need an argument `avatarUrl` and the changes suggested by @vincenzon would make sense contextually.
