### ISSUE TITLE
Deploying GraphQL Database Function using graphql.resolve() with SQL Editor

### ISSUE THREAD

**Issue by EmersonFJ** [supabase/supabase#18889]
- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the Bug & Steps to Reproduce

I am unsure if this is a bug, or a documentation issue. Paul Copplestone suggested that I post this here to dig into it: https://twitter.com/kiwicopple/status/1723324090356748533 Thus, I am doing so. Thank you @kiwicopple . 

I am wanting to deploy GraphQL database functions to return sets of records, which I currently do simply as follows for SQL / PLPG SQL:

```
create or replace function getFunction(param text)
returns setof record language sql  as $$

[SQL Function]

$$;
```

I understand that I can use graphql.resolve through plpgsql to run graphql queries in Supabase. I have proven this by just running graphql.resolve in the SQL editor, which works well. I now want to deploy that function from the SQL editor to a database function, the same as I do above. So, I assumed I could do something like this:

```
create or replace function graphQLFunction(param text)
returns setof record language plpgsql as $$

select graphql.resolve ($$
     { <-- ERROR HERE
      postsCollection(
        first: 5
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$$);

$$;
```

However, this then returns a syntax error "at or near '{'", which I have highlighted with caps above.

Any ideas or hints on what I might be doing wrong here? The function itself using select graphql.resolve works in the SQL Editor as intended; its moving it to a deployed database function that is causing challenges. Thank you!

## Expected behavior

I would expect the graphql.resolve() to deploy normally, like any other plpgsql function. Alternatively, if the syntax above is wrong, I would expect there to be documentation that describes how to deploy database functions from the SQL Editor.

## Additional context

Thank you - love Supabase

**Comment by imor** [comment]
Hi @EmersonFJ 

Two changes are needed for this function to work. The immediate problem is that there are two sets of [dollar quotes](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) which need to be disambiguated by using a tag for one of them. So use $query$ instead of $$ for the inner set. The second is that the language of the function is SQL not plpgsql. With these change the function looks like this:

```sql
create or replace function graphQLFunction(param text)
returns setof record language sql as $$

select graphql.resolve ($query$
     {
      postsCollection(
        first: 5
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$);

$$;
```

Although the above will work in that the function will return the result of calling the graphql query, it is a bit unusual to use graphql like this. It is mainly a client side language and you'd be much better off by writing your functions in plpgsql or sql. E.g. the above function could look like this in pure sql:

```sql
create or replace function graphQLFunction()
returns setof record language sql as $$

select id from posts limit 5;

$$;
```

**Comment by EmersonFJ** [comment]
> Hi @EmersonFJ
> 
> Two changes are needed for this function to work. The immediate problem is that there are two sets of [dollar quotes](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) which need to be disambiguated by using a tag for one of them. So use query instead of $$ for the inner set. The second is that the language of the function is SQL not plpgsql. With these change the function looks like this:
> 
> ```sql
> create or replace function graphQLFunction(param text)
> returns setof record language sql as $$
> 
> select graphql.resolve ($query$
>      {
>       postsCollection(
>         first: 5
>         ){
>         edges {
>           node {
>             id
>           }
>         }
>       }
>     }
> $query$);
> 
> $$;
> ```
> 
> Although the above will work in that the function will return the result of calling the graphql query, it is a bit unusual to use graphql like this. It is mainly a client side language and you'd be much better off by writing your functions in plpgsql or sql. E.g. the above function could look like this in pure sql:
> 
> ```sql
> create or replace function graphQLFunction()
> returns setof record language sql as $$
> 
> select id from posts limit 5;
> 
> $$;
> ```

Thank you for taking the time to write that all out. That is helpful and so this isn't a bug, its just a way to translate graphql through the SQL Editor - an issue on my end thank you.

If we can keep this open for a couple questions longer... hopefully to help others like me... @imor do you have to provide your perspectives on the below?

1. Understanding that you say GraphQL is more a client-side language... is there any negative to using GraphQL like this as a database function? I do have all my APIs working in SQL or PLPGSQL database functions, and I was going to experiment with using GraphQL to see the impact... in short, GraphQL seems to give me a lot more flexibility with changes to the database backend over time, almost working like an interpretation layer. 
2. Do you know of a way to deployment fragments into database functions as well? 

Thank you again for the education here!

**Comment by EmersonFJ** [comment]
@imor - Apologies for the follow-up question, but do you know how you use the parameters from the sql function within the deployed graphql.resolve query? So, how you reference the "param text" part...

When I try to use the parameters within the graphql function itself, they don't actually get pulled through... so a simple version of what I am trying would be....

 create or replace function graphQLFunction(param text)
returns setof record language sql as $$

```
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve ($query$
     {
      postsCollection(
        first: first_param
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$);

$$;
```

In the above, the first_param is not passed through to the function and then you get an error related to the fact that there is no integer in the "first: []" line.

and if you do the below, adding the $ ahead of the parameter like graphQL likes, the parameter is treated as null. You cannot call the parameter "$first_param" in the create or replace function.

```
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve ($query$
     {
      postsCollection(
        first: $first_param
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$);

$$;
```

Thank you for all the help!
