### ISSUE TITLE
Footer links on supabase.com not rendering as links

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18882]
Many of the links in the footer of https://supabase.com/ aren't rendering as links

<img width="1164" alt="screenshot-2023-11-11-at-09 01 39" src="https://github.com/supabase/supabase/assets/105593/ff82696e-56f5-4ea8-8217-72d9713cc1ed">

**Comment by nav302004** [comment]
what it suppose to look like a cursor pointer or an anchor tag

**Comment by nav302004** [comment]
@saltcod what it suppose to look like a cursor pointer or an anchor tag

**Comment by Kunjshah20** [comment]
Hey @saltcod. I have opened a PR #18899 . Please review it and feel free to point me out if further changes are required. Thank you.

**Comment by alaister** [comment]
Fixed in https://github.com/supabase/supabase/pull/18885
