### ISSUE TITLE
Local Supabase Studio development shows 500 errors when trying to view logs

### ISSUE THREAD

**Issue by kaumac** [supabase/supabase#18891]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Supabase Studio for local development flow is not reliable at all.
1) I can't see logs. If I try to see Postgres logs (or any other logs) I get a 500 error.
2) When you go to Triggers and refresh the page I see a "Failed to retrieve database triggers" error.
3) If I create a trigger through SQL query I can't see it listed on the dashboard (although it is created and it does work). If I create a trigger through the dashboard I can see it on the dashboard.

It's really hard to develop on a development/staging/production environment when the local development environment is so unstable. I'll need to either develop directly on production or look for a different solution.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run supabase with `supabase start`
2. Open the dashboard.
3. Create a trigger through a sql query
4. Go to Triggers on the dashboard and look for the trigger, it won't be there.
5. Go to the Logs page. There will be a 500 error.

## Expected behavior

I should be able to see all triggers, no matter if I create it through a query or through the dashboard/ui.
I should be able to see the postgres logs on the dashboard.

## Screenshots

<img width="1680" alt="Captura de Tela 2023-11-11 às 21 25 53" src="https://github.com/supabase/supabase/assets/1170740/df45498a-6878-4f9c-92f4-fb46faa6a9bf">
<img width="1680" alt="Captura de Tela 2023-11-11 às 21 26 41" src="https://github.com/supabase/supabase/assets/1170740/72e2ab9d-1324-4633-ac82-a4171f9300e3">

## System information

- OS: MacOS Sonoma 14.0 (Intel Chipset)
- Edge and Chrome
- Version of supabase-js: 2.38.4
- Version of Node.js: 20.6.1

**Comment by AndreMiras** [comment]
I'm impacted by both bugs described here.
While I have been having the log page 500 error for a long while (at least since supabase CLI 1.93.0 and still to this day 1.106.1), the issue with the trigger page returning an error after refresh is something that I didn't see in previous versions

**Comment by kaumac** [comment]
> I'm impacted by both bugs described here. While I have been having the log page 500 error for a long while (at least since supabase CLI 1.93.0 and still to this day 1.106.1), the issue with the trigger page returning an error after refresh is something that I didn't see in previous versions. Edit, the refresh bug on the trigger page seems to be solved in 1.110.1

Honestly I think the logs are more critical than the triggers not showing. We can still see the triggers through SQL queries (even though this is not an ideal solution/experience).
Logs on the other hand are critical to development. I'm getting errors and I have no way to debug them.

**Comment by christian-ledesma** [comment]
I'm also getting error 500 on logs page. Is this currently being worked on?

**Comment by Hallidayo** [comment]
Hi guys - Are you having issues creating tables from using the Table Editor as well locally?

**Comment by christian-ledesma** [comment]
> Hi guys - Are you having issues creating tables from using the Table Editor as well locally?

Not in my case. I can perform every other action except for logs.

**Comment by kaumac** [comment]
> Hi guys - Are you having issues creating tables from using the Table Editor as well locally?

I also have no issues creating tables and rows. Even the trigger erros seem to have been fixed in one of the latest versions.

I only have issues viewing the logs which are still showing a 500 error

**Comment by joshling1919** [comment]
We're also running into this issue. @kaumac, curious if you (or anyone else) have figured out a solution for this. Thanks!

**Comment by tranhoangvuit** [comment]
Hi @kaumac, @joshling1919, Can I know to which port of `analytic` you are connecting?
During local development, we will need to make some adjustments to the `port` and `API key` of `LOGFLARE`
Here is my configuration; I hope it can be helpful.
<img width="1487" alt="image" src="https://github.com/supabase/supabase/assets/21276822/fd8bed3f-a6a3-4e59-a6ad-7779ed68ce33">
<img width="1438" alt="image" src="https://github.com/supabase/supabase/assets/21276822/f9226b46-ad64-44dc-8ae6-55be84042bc8">
<img width="1666" alt="image" src="https://github.com/supabase/supabase/assets/21276822/68c91721-a281-4e43-8fcd-36a053162ef2">

**Comment by kaumac** [comment]
> Hi @kaumac, @joshling1919, Can I know to which port of `analytic` you are connecting? During local development, we will need to make some adjustments to the `port` and `API key` of `LOGFLARE` Here is my configuration; I hope it can be helpful. <img alt="image" width="1487" src="https://private-user-images.githubusercontent.com/21276822/289924620-fd8bed3f-a6a3-4e59-a6ad-7779ed68ce33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5MjQ2MjAtZmQ4YmVkM2YtYTZhMy00ZTU5LWE2YWQtNzc3OWVkNjhjZTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODg3ZDgwNjE3ZjM4NmFiNzE5Mzk3ZGY5ZDhkYzViMzU3OWJiMGU0Y2JhNDM3Y2I1YTYxMzYzZGRkOTY0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bw5j38VH3ouXd25XXKDn7RzO53zDnQ6lDcfM_T8m-NA"> <img alt="image" width="1438" src="https://private-user-images.githubusercontent.com/21276822/289924922-f9226b46-ad64-44dc-8ae6-55be84042bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5MjQ5MjItZjkyMjZiNDYtYWQ2NC00NGRjLThhZTYtNTViZTg0MDQyYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYWE3NjFmYmY0NWFlNTg1ODQ3Y2M2Yzc5MzJhNmY5OTJkZTUzMjRiNDAxZjQ3YTZjZThjOGQ4Yzc3OGZmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wARTanj923P1STK-D-dX18iIb7j5_D2XqoNxadcre1Y"> <img alt="image" width="1666" src="https://private-user-images.githubusercontent.com/21276822/289927516-68c91721-a281-4e43-8fcd-36a053162ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5Mjc1MTYtNjhjOTE3MjEtYTI4MS00ZTQzLThmY2QtMzZhMDUzMTYyZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTRmMzMyYWFjMDU3YzI2NTJlYmUyMjJkYmU1YTJiOGQyOWU2ZjdhOTY4MzUyZDc0OTljMmQxOTc3OWM4NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jDZw8XaGq_U93o60LKYsl6Zsv3MT0tDiA4rtWloRMl4">

Not sure I understand, do I need to make those changes on Docker?
The only thing I did was run `supabase start`

**Comment by kaumac** [comment]
Also do I need to get an api key for this? Or "api-key" string works?

> > Hi @kaumac, @joshling1919, Can I know to which port of `analytic` you are connecting? During local development, we will need to make some adjustments to the `port` and `API key` of `LOGFLARE` Here is my configuration; I hope it can be helpful. <img alt="image" width="1487" src="https://private-user-images.githubusercontent.com/21276822/289924620-fd8bed3f-a6a3-4e59-a6ad-7779ed68ce33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5MjQ2MjAtZmQ4YmVkM2YtYTZhMy00ZTU5LWE2YWQtNzc3OWVkNjhjZTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ODg3ZDgwNjE3ZjM4NmFiNzE5Mzk3ZGY5ZDhkYzViMzU3OWJiMGU0Y2JhNDM3Y2I1YTYxMzYzZGRkOTY0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bw5j38VH3ouXd25XXKDn7RzO53zDnQ6lDcfM_T8m-NA"> <img alt="image" width="1438" src="https://private-user-images.githubusercontent.com/21276822/289924922-f9226b46-ad64-44dc-8ae6-55be84042bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5MjQ5MjItZjkyMjZiNDYtYWQ2NC00NGRjLThhZTYtNTViZTg0MDQyYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYWE3NjFmYmY0NWFlNTg1ODQ3Y2M2Yzc5MzJhNmY5OTJkZTUzMjRiNDAxZjQ3YTZjZThjOGQ4Yzc3OGZmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wARTanj923P1STK-D-dX18iIb7j5_D2XqoNxadcre1Y"> <img alt="image" width="1666" src="https://private-user-images.githubusercontent.com/21276822/289927516-68c91721-a281-4e43-8fcd-36a053162ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQyNDYsIm5iZiI6MTcwMzAxMzk0NiwicGF0aCI6Ii8yMTI3NjgyMi8yODk5Mjc1MTYtNjhjOTE3MjEtYTI4MS00ZTQzLThmY2QtMzZhMDUzMTYyZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTRmMzMyYWFjMDU3YzI2NTJlYmUyMjJkYmU1YTJiOGQyOWU2ZjdhOTY4MzUyZDc0OTljMmQxOTc3OWM4NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jDZw8XaGq_U93o60LKYsl6Zsv3MT0tDiA4rtWloRMl4">
> 
> Not sure I understand, do I need to make those changes on Docker? The only thing I did was run `supabase start`

**Comment by kaumac** [comment]
Hmm I don't even have "supabase_analytics_test", see screenshot
<img width="774" alt="Captura de Tela 2023-12-19 às 16 31 43" src="https://github.com/supabase/supabase/assets/1170740/19c26e53-020b-4e4d-96d7-ac48ecf4cb7f">

**Comment by kaumac** [comment]
Honestly I feel like there's a lack of interest from supabase on the selfhosted stack. You can tell from the lack of features that you have on the hosted app.

This would be totally understandable (after all the selfhosted app doesn't bring in any money), except that the self hosted stack is a critical part of a mature/production app.

I develop locally and afterwards deploy to staging and production which are cloud (paid for) apps.

Supabase is such a great platform, you can tell there's a lot of hard work done on the cloud app, but I must say that the local development feels unpolished and somewhat painful to work with.

**Comment by kaumac** [comment]
I have just written a Function and Trigger that was not working. Even the error message was blank in development/local.

I had to create a migration, deploy the migration to production (cloud/hosted app) just to see the error message and logs, then fix it on my local stack and create a migration with the fix.

The logs are very critical and I feel like they are not being given the attention they should 🙁

**Comment by kaumac** [comment]
Local:
<img width="714" alt="Captura de Tela 2023-12-19 às 16 53 10" src="https://github.com/supabase/supabase/assets/1170740/cde00709-d17a-4e89-8e2d-432ddf7a4c96">
Production (cloud/hosted):
<img width="660" alt="Captura de Tela 2023-12-19 às 16 52 27" src="https://github.com/supabase/supabase/assets/1170740/fe84be72-9077-4b80-b14d-aae06ade8ffe">

**Comment by tranhoangvuit** [comment]
> Hmm I don't even have "supabase_analytics_test", see screenshot

In the `config.toml` file, you can enable it as shown in this image:

<img width="620" alt="image" src="https://github.com/supabase/supabase/assets/21276822/15b26202-f57b-43a7-82bc-72339576c4ec">

**Comment by tranhoangvuit** [comment]
>Honestly I feel like there's a lack of interest from supabase on the selfhosted stack. You can tell from the lack of features that you have on the hosted app.

Feel free to create an issue in this repo. We will check and update it soon.

>I have just written a Function and Trigger that was not working. Even the error message was blank in development/local.

Can you create another ticket for this issue?

----
>

> Local: <img alt="Captura de Tela 2023-12-19 às 16 53 10" width="714" src="https://private-user-images.githubusercontent.com/1170740/291698720-cde00709-d17a-4e89-8e2d-432ddf7a4c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODUyNjEsIm5iZiI6MTcwMzA4NDk2MSwicGF0aCI6Ii8xMTcwNzQwLzI5MTY5ODcyMC1jZGUwMDcwOS1kMTdhLTRlODktOGUyZC00MzJkZGY3YTRjOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTUwOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUwZDNmYjBkZDcyMjBmOTNkMTJmOGY2NGQ2NmFmNTJlZmI5MmNiYWQ3MDcwMDU0MjU0NzdlZjlkZmJiNGJhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.edcHriyO3VZz6Y1j1oPWfc8EzkU27UMtjO12CyIljW0"> Production (cloud/hosted): <img alt="Captura de Tela 2023-12-19 às 16 52 27" width="660" src="https://private-user-images.githubusercontent.com/1170740/291698811-fe84be72-9077-4b80-b14d-aae06ade8ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODUyNjEsIm5iZiI6MTcwMzA4NDk2MSwicGF0aCI6Ii8xMTcwNzQwLzI5MTY5ODgxMS1mZTg0YmU3Mi05MDc3LTRiODAtYjE0ZC1hYWUwNmFkZThmZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTUwOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ5OTNiZTI0Y2EyOTlmNDhiNDU2NDhhMTllMmY4ZmUxNjhiODEyNDdkM2ViYTAzOTRiMDBlNGM5MDk3MWIyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hg9awzgpsI87WziOnJomPZ4audSiQZNo9FhZoNZScE8">

I'm working on this issue, will update you soon on it.

**Comment by dallastjames** [comment]
> > Hmm I don't even have "supabase_analytics_test", see screenshot
> 
> In the `config.toml` file, you can enable it as shown in this image:
> 
> <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/21276822/291937187-15b26202-f57b-43a7-82bc-72339576c4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTg1NzEsIm5iZiI6MTcwNDI5ODI3MSwicGF0aCI6Ii8yMTI3NjgyMi8yOTE5MzcxODctMTViMjYyMDItZjU3Yi00M2E3LTgyYmMtNzIzMzk1NzZjNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE2MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTg3NTIyN2IxYTIyNGU1ZWQ0YWFhZTE1MWUwYzY3ZmE3NGFmMDc2MTBjMWVlMDA2ZjAwZjViZjgyM2IxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SYSR19dUGuI_oM2hrWUStNie3rB-6iO6d1PefCw-ds">

I was running into this same error and I needed to enable analytics in my config.toml file, but I had to add the entire analytics entry manually, likely because I was running an older project that was created before analytics were supported in the local studio. Doing that and restarting supabase, it pulled the logging containers and works correctly for me.

**Comment by balazss** [comment]
If it helps anybody... As mentioned above, to have logs, you need to edit config.toml and enable analytics:

`[analytics]
enabled = false  <-- Set this to true
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"`

Important! After enabling, you need to restart supabase:
`npm supa stop`
`npm supa start`

**Comment by encima** [comment]
I will close this as it is answered here and in the [documentation](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started).

Please comment (or open a PR) if you think it could be made clearer and we can re-evaluate!

**Comment by stefanstidlffg** [comment]
> I will close this as it is answered here and in the [documentation](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started).

in the documentation there it is called: LOGFLARE_SINGLE_TENANT_MODE and in the example docker-compose it is called LOGFLARE_SINGLE_TENANT
please adapt the documentation or docker-compose example depending which is the correct one.

**Comment by danrasmuson** [comment]
Can someone explain why `enabled` is not the default option?

```
[analytics]
enabled = true
```

**Comment by encima** [comment]
@danrasmuson because it does take additional resources and startup time. Those wanting to use self-host can enable but those just trying Supabase or testing a feature locally may not want the additional overhead. Feel free to start a Discussion or open a PR if you think it should be different!

**Comment by rafadpedrosa** [comment]
Hi guys so, I'm having the same problem and, the way I see it, we - new superbase users :D - are missing:

- [enable true](https://github.com/supabase/supabase/issues/18891#issuecomment-1886134722) 

But, I would like to popUp the [this comment](https://github.com/supabase/supabase/issues/18891#issuecomment-1852347504) from @tranhoangvuit  that helped me to get more insights about my problem. Even tho I'm still not sure what should I do to fix it yet :(

Running on cli: `docker exec 4a6873e8ba3c env ` I can't see the LOGFLARE_URL set.

![image](https://github.com/supabase/supabase/assets/2192220/7c4e94b8-c607-45b0-a497-4475244d5179)

I added the `enabled = true` in toml file but the error was still there. Because of that comment - thanks again - I realized that this variable does not exist on my logflare docker. Is this just happening with me? 

My question here is simple, did I miss something? Or did I have to config it manually?

ps. In my head it should be like 1) enable true 2) supabase start. 3) log works.

**Comment by jacobcoccari** [comment]
Finally figured this one out. A few helpful resources. Currently referring to configuration in local environment:

1) There are a number of different confirmations that can be sent. Find the lisf of them below. Each individual email needs to be configured, pointing to a specific template:
https://supabase.com/docs/guides/cli/customizing-email-templates

2) Make sure you verify the sender information with your SMTP. In Sendgrid, which I was using, this is contained under Settings > Sender Authentication

3) Make sure to update your config.toml to reflect the correct email. If you are adding an email template that is not included in the config.toml, you'll have to add it. 

4) You can see the detailed logs in your Supabase dashboard under Logs > Auth

Not 100% sure if this answers your exact question, but might be helpful for future people who run into this error.
