### ISSUE TITLE
Issue with showing code section in Supabase docs for mobile

### ISSUE THREAD

**Issue by strange2x** [supabase/supabase#18908]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When browsing the Supabase docs from mobile phone (using iphone 13 mini), the code section that shows like commands are being cut off at half. Have to scroll in the small section to see the content.

## To Reproduce

Goto Supabase docs from the phone and it will happen in any secoon

## Screenshots

![image](https://github.com/supabase/supabase/assets/10759731/c6491a02-869b-43bf-b837-9e68a385b877)

## System information

- OS: iOS
- Browser (if applies): Safari

**Comment by saltcod** [comment]
Hey @strange2x — not able to reproduce this one. is it still happening for you?

**Comment by AbhijeetBiswal** [comment]
Hey @strange2x its looking good on me their is no issue

**Comment by charislam** [comment]
Thanks for the report, @strange2x! This seems to be an intermittent error that pops up every so often when size measurement for the code blocks doesn't kick in quickly enough, a simple refresh will usually do the trick!

Let me know if the issue persists for you and I can dig deeper

**Comment by strange2x** [comment]
Yes this issue is still there for me

**Comment by strange2x** [comment]
I can confirm this is still happening on phone

**Comment by encima** [comment]
Tested this with the link provided by @saltcod 
- iPhone SE - emulated on Chrome with mid-tier throttling
- iPhone XR - emulated on Chrome with mid-tier throttling
- iPhone 15 Pro Max - Safari

and not able to reproduce.

@strange2x I assume you are using Safari, is your Mini running iOS 16 or 17?

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
