### ISSUE TITLE
Vue warning: onScopeDispose() is called when there is no active effect scope to be associated with

### ISSUE THREAD

**Issue by sdr0x07b6** [supabase/supabase#18920]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm encountering a Vue warning in the console every time I reload any page in my Nuxt 3 project that uses the Supabase library, after logging in. The warning message is:

`[Vue warn] onScopeDispose() is called when there is no active effect scope to be associated with.`

This warning does not appear on the login screen, but it does appear on all pages after logging in. Each page reload triggers two identical warnings.

## To Reproduce

1. Log in to the application.
2. Navigate to any page.
3. Reload the page.
4. Observe two identical Vue warnings in the console.

## Expected behavior

I expect no Vue warnings to be triggered by the Supabase library.

## Screenshots

![onScopeDispose](https://github.com/supabase/supabase/assets/1102138/38bc5472-a3c6-4b45-8d7c-984de0dd32d2)

## System information

- OS: macOS 14.1.1
- Browser (if applies) Chrome 119.0.6045.123
- Version of supabase-js: @nuxtjs/supabase v1.1.3
- Version of Node.js: v18.18.0

## Additional context

The stack trace points to the Supabase library as the source of the warning. I will attach the relevant part of the stack trace in a follow-up comment.
```
cookie.js:111 [Vue warn] onScopeDispose() is called when there is no active effect scope to be associated with.
warn @ reactivity.esm-bundler.js:4
onScopeDispose @ reactivity.esm-bundler.js:101
cookieRef @ cookie.js:111
useCookie @ cookie.js:25
(anonymous) @ supabase.client.mjs?v=354b09b1:23
(anonymous) @ GoTrueClient.ts:1770
_notifyAllSubscribers @ GoTrueClient.ts:1768
_recoverAndRefresh @ GoTrueClient.ts:1694
await in _recoverAndRefresh (async)
_initialize @ GoTrueClient.ts:319
await in _initialize (async)
(anonymous) @ GoTrueClient.ts:266
(anonymous) @ GoTrueClient.ts:875
lockNoOp @ GoTrueClient.ts:104
_acquireLock @ GoTrueClient.ts:869
(anonymous) @ GoTrueClient.ts:265
initialize @ GoTrueClient.ts:268
_GoTrueClient @ GoTrueClient.ts:240
SupabaseAuthClient @ SupabaseAuthClient.ts:6
_initSupabaseAuthClient @ SupabaseClient.ts:282
SupabaseClient @ SupabaseClient.ts:112
createClient @ index.ts:38
setup @ supabase.client.mjs?v=354b09b1:13
(anonymous) @ client.mjs?t=1699886702121:41
executeAsync @ index.mjs?v=354b09b1:111
setup @ client.mjs?t=1699886702121:41
(anonymous) @ nuxt.js:110
fn @ nuxt.js:153
runWithContext @ runtime-core.esm-bundler.js:3873
callWithNuxt @ nuxt.js:158
(anonymous) @ nuxt.js:31
run @ reactivity.esm-bundler.js:38
runWithContext @ nuxt.js:31
applyPlugin @ nuxt.js:110
applyPlugins @ nuxt.js:125
await in applyPlugins (async)
initApp @ entry.js:42
(anonymous) @ entry.js:59
```

% yarn nuxi info
```
------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, devtools, srcDir, modules, imports, runtimeConfig, app, vuetify, vite, nitro
- Runtime Modules:  vuetify-nuxt-module@0.6.7, nuxt-icon@0.6.5, @vueuse/nuxt@10.6.1, @pinia/nuxt@0.5.1, @nuxtjs/supabase@1.1.3, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/i18n@8.0.0-rc.5, @vee-validate/nuxt@4.11.8
- Build Modules:    -
------------------------------
```

**Comment by tim3ks** [comment]
Hello. Strange situation, cuz i was making my with yarn, change with pnpm then this warn was show.

**Comment by samdickerman** [comment]
I am seeing the same error with the same setup (Nuxt, SupabaseAuth)

**Comment by Ragura** [comment]
Same warning on my side with the exact same configuration and cause.

**Comment by AlbertBrand** [comment]
This is a `nuxt/supabase` module problem. I made a PR to fix it here:
https://github.com/nuxt-modules/supabase/pull/309

**Comment by samdickerman** [comment]
Great!  Thanks very much for taking the time to address this!

**Comment by AlbertBrand** [comment]
Fixed in https://supabase.nuxtjs.org/changelog#v1.1.4 !

**Comment by sdr0x07b6** [comment]
Confirmed resolved! @AlbertBrand You do great work! Thank you so much!
