### ISSUE TITLE
Deleting a sorted column crashes the Table Editor

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#18955]
If a table is sorted by column, and you delete that column, the table will crash.

To reproduce: 

1. create a table in the Table Editor
2. sort by a column, doesn't matter which one 
3. open a new tab (important), go to the SQL Editor 
4. delete that column via sql:  `ALTER TABLE your_table DROP COLUMN your_column`
5. go back to the original tab and hit refresh, see error since the sort column no longer exists

<img width="773" alt="screenshot-2023-11-14-at-11 21 19" src="https://github.com/supabase/supabase/assets/105593/fe267964-1126-4804-89ba-8e9b1a37b448">

**Comment by Akash187** [comment]
@saltcod Dashboard is crashing on the Development Environment when you run an incorrect query.

**Comment by saltcod** [comment]
what do you mean @Akash187 ?

**Comment by SubhoYadav** [comment]
I am a new contributor to the project . Please tell me if I can pick this issue up ?

**Comment by saltcod** [comment]
Thanks @SubhoYadav — looks like @tranhoangvuit already has it nabbed.

**Comment by SubhoYadav** [comment]
@saltcod Can u please help me getting started with the project, though I have the compatible node and npm versions as the documentation suggests, I cannot have my dependencies installed its saying "next" not found . Thanks for the help.

**Comment by alexwhitmore** [comment]
I see this issue is currently being worked on, but I had a question about creating tables. I have set up the project locally and Docker is up and running with seemingly no issues. When trying to create a table I get `Error: Failed to fetch` but no hint into where the issue is.

Is something else required to enable this functionality? @saltcod

**Comment by botxboom** [comment]
> I see this issue is currently being worked on, but I had a question about creating tables. I have set up the project locally and Docker is up and running with seemingly no issues. When trying to create a table I get `Error: Failed to fetch` but no hint into where the issue is.
> 
> Is something else required to enable this functionality? @saltcod

Hi @alexwhitmore , I was facing similar issue and found my containers were not running properly. just make sure each and every container is up and running.

**Comment by SubhoYadav** [comment]
Are you guies running the project entirely in docker?

**Comment by saltcod** [comment]
@alexwhitmore that issue should be resolved now if you update to the latest one. 
@SubhoYadav discord might be the best way to  get help getting up running
