### ISSUE TITLE
docs: add installation to python library docs

### ISSUE THREAD

**Issue by finnala** [supabase/supabase#18954]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/reference/python/introduction)

## Describe the problem

The library documentation for Python doesn't include any installation intstructions.

Some of the other client libraries, e.g. for Flutter and C# do have a section on installation.

## Describe the improvement

Adding an installation section to the Python documentation with some simple instructions like `pip install`. 

## Additional context

It seems that some people are either installing the wrong package or getting confused sometimes between the Python packages supabase and supabase-py. This might also help with that, even though the README for the linked file in the Python documentation is clear about it being supabase.

**Comment by troytomasch** [comment]
Hey @finnala! Just want to clarify the issue a little. 

I see the install section on the page you linked. Are you looking for more clarifying information or more detailed instructions on this page?
![image](https://github.com/supabase/supabase/assets/55467325/064504d3-2550-4f82-83a1-937d09d44900)

**Comment by finnala** [comment]
Hey @troytomasch, looks like someone made a PR shortly after I opened this issue so this can be probably be closed now.

**Comment by charislam** [comment]
> Hey @troytomasch, looks like someone made a PR shortly after I opened this issue so this can be probably be closed now.

Thanks for catching that! Closing as resolved.
