### ISSUE TITLE
redirectTo option not respected (Google sign-in)

### ISSUE THREAD

**Issue by Saunved** [supabase/supabase#1895]
# Bug report

## Describe the bug
When signing up a user, using the `redirectTo` option has no effect.

## To Reproduce
1. In Supabase Auth settings, add the redirect URL
2. In Google, add the redirect URL to the list of allowed redirect URLs
3. Add the sign in with Google function to your UI, with the redirect URL set in the `redirectTo` option
4. Try signing in with Google

E.g. 
```js
  const { user, session, error } = await this.$supabase.auth.signIn(
    { provider: 'google' },
    { redirectTo: 'http://localhost:3000/account' }
  )
```

## Expected behavior
1. The user should be redirected to the redirect URL after they are logged in
2. Google's login screen should say "Continue to `redirect URL`" instead of "Continue to supabase.co"

## Screenshots
NA

## System information
NA

## Additional context
These are the Github issues I have explored so far to figure out a solution, but I can't figure out why "redirectTo" is not working:
> My original concern: https://github.com/supabase/supabase/issues/1798
> Similar bug report filed on 8 Mar 2021: https://github.com/supabase/supabase/issues/832
> #832 was then moved over here: https://github.com/supabase/gotrue-js/issues/65

**Comment by ragnorc** [comment]
I suspect that the `supabase@gotrue-js `dependency does not get updated when updating `supabase-js`. Try `npm install @supabase/gotrue-js@latest` and the `redirectTo` option should work.

**Comment by Saunved** [comment]
Hi, this seems to have worked. Does the SIte URL option in Supabase affect this behavior in any way or do the Redirect URLs control what is allowed? There is some confusion regarding this on my part.
Thanks!

**Comment by Saunved** [comment]
I experimented with the redirectTo option and these are my findings. I hope this helps someone who is trying to figure out how the redirectTo works:
*  It doesn't matter if you set the redirect URL in Supabase settings as long as you pass in a valid URL in the "redirectTo" option
* The site URL option in Supabase settings has no effect on where the user will get redirected. That is controlled by you in the "redirectTo" option
* If using email + password sign in, the `redirectTo` option **does not work**. The user is kept on the same page. It is up to you to handle the redirect after the XHR request.

This code snippet taken from the [docs](https://supabase.io/docs/reference/javascript/auth-signup) throws an error
```js
const { user, session, error } = await supabase.auth.signUp({
  provider: 'github'
}, {
  redirectTo: 'https://example.com/welcome'
})
```
Error (422)
```json
{"code":422,"msg":"Signup requires a valid password"}
```
The docs should change the `signUp` method to `signIn` and it will work correctly.
* * *
Mentioning @kiwicopple because we had a back and forth on this two weeks ago. My original issue https://github.com/supabase/supabase/issues/1798 is still unresolved. Using `redirectTo` has no effect on what the Google prompt shows (Continue to supabase.co)

**Comment by inian** [comment]
Hi @Saunved, 

> The docs should change the signUp method to signIn

Yeah, this was wrong and I just fixed the docs

**Comment by harshcut** [comment]
There a few more changes that @kiwicopple suggested. Take a look at #1873.

**Comment by inian** [comment]
Ah just seeing that PR @harshcut. Looks like there is [one more issue](https://github.com/supabase/supabase/pull/1873#issuecomment-858593639) that needs to be resolved before it can be merged in.

**Comment by kiwicopple** [comment]
I'll have a look now - working on the docs today

**Comment by rsdavis** [comment]
Thanks @Saunved for posting those findings, they were helpful for me.

I also wanted to add that the "Additional Redirect URLs" in the console does come into play if you want to redirect to another domain. It seems the "redirectTo" parameter checks the domain of the of both the "Site URL" and the "Additional Redirect URLs". 

In my tests, "redirectTo" will work for one of the following situations using provider oauth ... 
1) redirectTo domain matches the domain of "Site URL"  
2) redirectTo url matches the entire url in "Additional Redirect URLs"

So for example, I set up mine using the following parameters in the console. This way, my redirect will work for my local environment and in the staging environment.
```
Site URL = https://dev.example.com
Additional Redirect URLs = http://localhost:3000/welcome
```

I couldn't find this info in the docs, please correct me if I am mistaken. Hope this helps.

**Comment by Saunved** [comment]
@rsdavis I'm glad I could be of help! In the tests that I have done so far, if the redirect URL domain and site URL domain doesn't match, then the redirect does not work. I will test this out again in a few hours to see if that is still the case (I'll also try installing the latest gotrue dependency if I haven't already) and report back here.

**Comment by talmr-k** [comment]
@Saunved were you able to get the google login screen to say "continue to {your app/site name}"?

**Comment by reswitchtech** [comment]
@talmr-k I haven't been able to get that message yet. I'm not sure if I'm doing something wrong or if someone from Supabase needs to look into this issue.

**Comment by heysailor** [comment]
The "continue to {your app/site name}" message is because the underlying callback used _before_ redirection is _always_ supabase.[ I've made a new issue here about that.](https://github.com/supabase/supabase/issues/2226)

**Comment by awalias** [comment]
I think this one is now fixed @Saunved if you set `http://localhost:3000/account` as an additional redirect URL

we will address the `continue to {your app/site name}` issue [here](https://github.com/supabase/supabase/issues/2226)

thanks for your input @ all

**Comment by tennysonp** [comment]
For deployments with Vercel, set the SITE_URL to your official site URL. Add the following additional redirect URLs for local development and deployment previews:

http://localhost:3000/**
https://*-username.vercel.app/**

It seems that /** is the key

https://supabase.com/docs/guides/auth/concepts/redirect-urls

**Comment by mnai01** [comment]
> Thanks @Saunved for posting those findings, they were helpful for me.
> 
> I also wanted to add that the "Additional Redirect URLs" in the console does come into play if you want to redirect to another domain. It seems the "redirectTo" parameter checks the domain of the of both the "Site URL" and the "Additional Redirect URLs".
> 
> In my tests, "redirectTo" will work for one of the following situations using provider oauth ...
> 
> 1. redirectTo domain matches the domain of "Site URL"
> 2. redirectTo url matches the entire url in "Additional Redirect URLs"
> 
> So for example, I set up mine using the following parameters in the console. This way, my redirect will work for my local environment and in the staging environment.
> 
> ```
> Site URL = https://dev.example.com
> Additional Redirect URLs = http://localhost:3000/welcome
> ```
> 
> I couldn't find this info in the docs, please correct me if I am mistaken. Hope this helps.

I also recently discovered in Supabase, the Site URL primarily focuses on the domain rather than the port. So, if your Site URL setting in supabase is set to localhost:3000, you can still work locally on a different port, like localhost:3001. So the default redirectTo param (which is site URL with domain check only) thats set when redirectTo is missing in the signInWithOAuth will handle it appropriately. Essentially, it's the domain that's key, not the port. Also, with Google OAuth, the redirect_to query parameter in the URL isn't as crucial as it appears. Even if you change it, the redirection follows the settings specified in the signInWithOAuth function via redirectTo , not the URL parameter. Probably some internal state handling the redirect, beyond what's visible in the URL. 

It seems some of this information is also missing from the documentation.
