### ISSUE TITLE
postgres upgrade appears to not migrate schema to newest version

### ISSUE THREAD

**Issue by fx** [supabase/supabase#18968]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When upgrading to newest postgres, it appears a migration is missed, resulting in logins failing until the project is restarted (fast database reboot did not do the trick) due to the `ip` column missing on `auth.sessions`

## To Reproduce

1. Have project w/ postgres that does not yet have `ip` on `auth.sessions`
2. Upgrade database
3. Profit!

## Expected behavior

Should add `ip` to `auth.sessions` 😄

## Screenshots

n/a

## System information

- `supabase/postgres` migrated to is `15.1.0.133`, unsure what the previous version has been.

## Additional context

See discord:
- https://discord.com/channels/839993398554656828/1173690046243668069
- https://discord.com/channels/839993398554656828/1174129270122098738

**Comment by MaseCodes20** [comment]
I'm currently facing the same problem

![1 aaError](https://github.com/supabase/supabase/assets/95643884/be5e7696-7e1d-40f3-9dda-bba25d6cbd1f)

**Comment by fx** [comment]
@MaseCodes20 a full project restart applies the necessary migrations. Give that a go.

**Comment by encima** [comment]
Closing as this seems to be fixed, please let us know if this is still occurring for you and we will reopen!
