### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by eposha** [supabase/supabase#18971]
# Improve documentation

## Link 

https://supabase.com/dashboard/project/*/settings/auth

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

Rcommendation

## Additional context

Add any other context or screenshots that help clarify your question.
<img width="690" alt="image" src="https://github.com/supabase/supabase/assets/54452472/4b3f5a09-7081-421c-93de-1708219dbb2d">

**Comment by alaister** [comment]
Fixed in #18976
