### ISSUE TITLE
Refresh token errors in @supabase/ssr 

### ISSUE THREAD

**Issue by cipriancaba** [supabase/supabase#18981]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you use the serverClient on multiple layouts in the nextjs app, this will trigger a race condition on who gets to refresh the token first. The request that refreshes the token first will get the correct token, but if another refresh request is initiated from another route, this will cause the app to error with `AuthApiError: Invalid Refresh Token: Already Used`

## To Reproduce

This happens randomly, I have the new `@supbase/ssr` in the next 14 app router, use it in the middleware for auth and also on various layout components to display user specific content

## Expected behavior

App doesn't crash :)

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of @supabase/ssr: 0.0.10
- Version of Node.js: v18.17.1
- Next 14.0.1

**Comment by eposha** [comment]
@cipriancaba I found the source of the problem

The thing is that when getSession updates the session because JWT expired, the cookies remain the same and are not overwritten with the new data from the updated session.

`  const {
    data: { session },
  } = await supabase.auth.getSession();
  
  console.log('session', session?.refresh_token);`

After session revalidation we get a new refresh_token but the cookies remain the same

**Comment by eposha** [comment]
So this code in middleware resolve problem for me

You should set session in the cookies every time when middleware was called

    ```
response.cookies.set({
      name: 'sb-{YOUR_ID}-auth-token',
      value: JSON.stringify(session),
      path: '/',
    });
```

**Comment by bernatfortet** [comment]
Thanks @eposha would you mind sharing the entire middleware file as a reference? This way other people can full clarity on the solution (including myself!). A gist would do wonders. There's lot of people in https://github.com/supabase/auth-helpers/pull/347 dealing with this issue.

**Comment by eposha** [comment]
```
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { createClient } from 'src/utils/supabase/middleware';

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;
  const { supabase, response } = createClient(req);
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const sessionCookies = {
    name: 'sb-{YOUR_ID}-auth-token',
    value: JSON.stringify(session),
    path: '/',
    expires: new Date(new Date().getTime() + 60 * 60 * 1000 * 24 * 365), // 1 year,
  };

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    if (pathname.startsWith('/auth')) {
      const response = NextResponse.redirect(new URL('/', req.url));

      response.cookies.set(sessionCookies);
      return response;
    }

    const subscribePath =
      user.user_metadata.subscription === 'subscribed'
        ? '/subscription+subscribed-user+auth'
        : '/subscription+notSubscribed-user+auth';

    const newPathname = `${subscribePath}${pathname
      .replace('/subscription+subscribed-user+auth', '')
      .replace('/subscription+notSubscribed-user+auth', '')
      .replace('/subscription+notSubscribed-user+notAuth', '')}`;

    const response = NextResponse.rewrite(new URL(newPathname, req.url));

    response.cookies.set(sessionCookies);
    return response;
  }

  if (!user && !pathname.startsWith('/auth')) {
    const response = NextResponse.rewrite(
      new URL(
        `/subscription+notSubscribed-user+notAuth${pathname
          .replace('/subscription+subscribed-user+auth', '')
          .replace('/subscription+notSubscribed-user+notAuth', '')
          .replace('/subscription+notSubscribed-user+auth', '')}`,
        req.url,
      ),
    );

    response.cookies.set(sessionCookies);
    return response;
  }

  return response;
}

export const config = {
  matcher: [
    '/',
    '/:path((?!_next/static|favicon.ico|_next/image|icons|manifest|api).*)',
  ],
};

```

@bernatfortet

**Comment by eposha** [comment]
```
import type { NextRequest } from 'next/server';
import { createClient } from '@/utils/supabase/middleware';

export async function middleware(request: NextRequest) {
  const { supabase, response } = createClient(request);

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const sessionCookies = {
    name: 'sb-{YOUR_ID}-auth-token',
    value: JSON.stringify(session),
    path: '/',
    expires: new Date(new Date().getTime() + 60 * 60 * 1000 * 24 * 365), // 1 year,
  };

  response.cookies.set(sessionCookies);

  return response;
}

export const config = {
  matcher: [
    '/',
    '/:path((?!_next/static|favicon.ico|_next/image|icons|manifest|api).*)',
  ],
};

```

**Comment by cipriancaba** [comment]
That's a very interesting find @eposha . It feels like there's definitely a problem with the ssr library not initiating the `set` method on refreshed tokens. It would also be nice for the `getSession` to notify you if the token has refreshed so you don't do a `set` cookie if nothing changed, since that basically invalidates the cache on nextjs side of things.

That being said, I tried to manually set the cookie as in your example, but for some reason, after doing that, my session data is null, which is really interesting

**Comment by eposha** [comment]
> That's a very interesting find @eposha . It feels like there's definitely a problem with the ssr library not initiating the `set` method on refreshed tokens. It would also be nice for the `getSession` to notify you if the token has refreshed so you don't do a `set` cookie if nothing changed, since that basically invalidates the cache on nextjs side of things.
> 
> That being said, I tried to manually set the cookie as in your example, but for some reason, after doing that, my session data is null, which is really interesting

This is expected behavior since the session is null due to the fact that getSession doesn't update cookies,we see an irrelevant session in cookies

**Comment by eposha** [comment]
And one more interesting fact, 

> @bernatfortet
> 
> I use @supabase/ssr
> 
> and **api**/auth/callback directory instead **app**/auth/callback
> 
> YOUR_ID can be taken from the supabase url
> 
> ```
> import type { NextRequest } from 'next/server';
> import { createClient } from '@/utils/supabase/middleware';
> 
> export async function middleware(request: NextRequest) {
>   const { supabase, response } = createClient(request);
> 
>   const {
>     data: { session },
>   } = await supabase.auth.getSession();
> 
>   const sessionCookies = {
>     name: 'sb-{YOUR_ID}-auth-token',
>     value: JSON.stringify(session),
>     path: '/',
>     expires: new Date(new Date().getTime() + 60 * 60 * 1000 * 24 * 365), // 1 year,
>   };
> 
>   response.cookies.set(sessionCookies);
> 
>   return response;
> }
> 
> export const config = {
>   matcher: [
>     '/',
>     '/:path((?!_next/static|favicon.ico|_next/image|icons|manifest|api).*)',
>   ],
> };
> ```

One more interesting fact.  The request includes the session update in cookies after the first request when getSession updated the session, but on the second call to the middleware the request has the old cookies. For this reason I can't compare previous and new session

**Comment by kavish-p** [comment]
I am using NextJS: 14.0.3 and @supabase/ssr: 0.0.10.
Recently I noticed several `AuthApiError: Rate limit exceeded` errors. Adding the `response.cookies.set` snippet as suggested above in my middleware resolved the issue.

**Comment by nobu-sh** [comment]
I am getting: `AuthApiError: missing destination name refreshed_at in *models.Session` causing a re-login.

**Comment by bernatfortet** [comment]
@eposha can you share the code that does that? Thanks!

**Comment by dijonmusters** [comment]
The only reason middleware is required is to refresh the session before hitting the Server Component route, as this only has read access to cookies.

Another solution could be to create a Route Handler to do this refresh:

``` app/auth/refresh-session
import { createClient } from '@/utils/supabase/server';
import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';

export async function GET(request: Request) {
    const cookieStore = cookies()
    const supabase = createClient(cookieStore);
    await supabase.auth.getSession();
}
```

Then make a fetch call to this route in the root layout:

``` app/layout.ts
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await fetch('/auth/refresh-session')

  return (
    <html
      lang="en"
    >
      <body>{children}</body>
    </html>
  );
}
```

I haven't had a chance to test this properly yet, but feels like it could be a better pattern than using middleware, since this is only required for Server Component routes - middleware will automatically run for every Server Component, Route Handler, asset fetch etc

**Comment by vinhnguyen3455** [comment]
> So this code in middleware resolve problem for me
> 
> You should set session in the cookies every time when middleware was called
> 
> ```
> response.cookies.set({
>       name: 'sb-{YOUR_ID}-auth-token',
>       value: JSON.stringify(session),
>       path: '/',
>     });
> ```

This seems to fix the problem for me.

**Comment by dijonmusters** [comment]
Okay awesome, glad it's fixed 👍

I need to revisit creating a supabase client in middleware docs! Thanks for letting us know!

Quick one to call out from your above example, `autoRefreshToken` should not be set to `true` if creating a client server-side. This sets up a timer to refresh the session, which should only be run in the browser 👍

**Comment by muhaimincs** [comment]
Hi @dijonmusters where can I find about this in the docs?

**Comment by SeanNFT** [comment]
Any updates regarding this? Updated docs?

**Comment by charislam** [comment]
You can take a look at our most recently updated Next.js Auth guide that describes how to set up middleware: https://supabase.com/docs/guides/auth/server-side/nextjs

The key points are:
1. The middleware is responsible for refreshing the token (by calling `supabase.auth.getUser`)
2. This refreshed token needs to be passed to Server Components, so they don't attempt to refresh the token themselves (since refreshing twice will terminate your session as a security measure) -- this is accomplished with `request.cookies.set`
3. The refreshed token also needs to be passed to the browser, so that it replaces the old token (otherwise the browser will have a stale token, and the next call to the server will trigger the refreshing twice problem) -- this is accomplished with `response.cookies.set`

**Comment by SeanNFT** [comment]
Also make sure you have **supabase/auth-helpers-nextjs uninstalled**

**Comment by gencaysyn** [comment]
> Ok, just found this issue in the other repo, [supabase/auth-helpers#347](https://github.com/supabase/auth-helpers/pull/347)
> 
> I'm trying the following fix for `createServerClient` and keeping that to true on the middleware server client
> 
> ```
> auth: {
>         autoRefreshToken: false,
>       },
> ```

I encountered the same issue in my .NET backend service. The same approach solved my problem. Thanks
```
var options = new SupabaseOptions
        {
            AutoRefreshToken = false,
            AutoConnectRealtime = true
        };

services.AddScoped<Client>(_ => new Client(url, key, options));
```
