### ISSUE TITLE
On local dev, can't generate SQL statements from storage bucket RLS policies 

### ISSUE THREAD

**Issue by thibistaken** [supabase/supabase#18996]
# Bug report

## Describe the bug

I am running Supabase in local development. I've added RLS policies to INSERT, SELECT and DELETE files in a storage bucket but when I run `supabase db diff`, I get: `No schema changes found`. I've had correct SQL statements that were generated on the Supabase Studio UI in local dev, but it seems they are not detected for the migrations. I've ran other successful `supabase db diff` commands prior, so I know this works on the public schema for instance. 

Is it a problem with the storage schema in local dev?

I wanted to take the generated SQL statements for the storage bucket, and add them manually in migrations I would then run but in Storage > Configuration > Policies, when I click edit > review, I get this message: `There are no changes made to this policy` so I cannot even view the previously generated SQL statements for the RLS policies.

Any help? Thanks!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'http://127.0.0.1:54323/project/default/storage/policies' and make sure to have one storage bucket created (public)
2. Click on 'Storage > Configuration > Policies > New Policy'
3. Create one RLS policy 
4. Run `supabase db diff`
5. You should get the command to run successfully but return `No schema changes found`

## Expected behavior

SQL statements generated by the `supabase db diff` to then include in a migration. 

## System information

- OS: 13.2.1 (22D68)
- Browser (if applies) Arc, Firefox

**Comment by Akash187** [comment]
Yes, I don't know why they don't include storage schema by default.
Till then use can use the below code
```
supabase db diff --use-migra -f storage --schema storage
```
[Documentation](https://supabase.com/docs/reference/cli/supabase-db-diff?example=supabase-db-diff-specific-schema)

**Comment by thibistaken** [comment]
Yes, exactly. FWIW I'd expect local dev (self-hosted) to behave similarly to hosted instances. And thanks @Akash187, that is very helpful.

**Comment by thibistaken** [comment]
Btw, I created a similar discussion [here](https://github.com/orgs/supabase/discussions/18993), which sounds more appropriate than an issue for this topic. Apologies for the duplicated but you may consider closing this issue now.
