### ISSUE TITLE
Replacing a column with one of the same name and changing the new one's type leads to an error

### ISSUE THREAD

**Issue by polooner** [supabase/supabase#18992]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using the UI to add or edit columns, if I add a column of an existing name but change it's values (eg. type and Is Unique) and delete it's predecessor, no new column will be created and the original will be deleted, an error will be shown.

## To Reproduce

1. Create a Table
2. Create a Column
3. In the tables list on the left side, click on the new table's options dropdown (the down arrow)
4. Click "Edit Table"
5. Delete a column and create a new one with a different type
6. Click "Save"

## Expected behavior

New column with new configurations added

## System information

- OS: macOS
- Browser: chrome

## Additional context

I did not simply change the type of the existing column because I did not have the option to configure it to be unique anymore. But when I added a new one and named it the same way, I was able to make it unique as well, so I chose to add a new one of the same name and change its type and Is Unique value. Maybe making it unique also had an impact?

**Comment by saltcod** [comment]
Hey @polooner — think I'm missing something. I'm able to change a column successfully. Is there a step missing?

![screenshot-2023-11-17-at-09 01 40](https://github.com/supabase/supabase/assets/105593/071cb4e6-79fd-4681-8cb7-c4514f8529e7)

**Comment by encima** [comment]
Closing. Please add clear reproduction steps (or a video!) if this is occurring for you and we will reopen.
