### ISSUE TITLE
Delete storage sub-folders issue

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#19031]
Deleting a top level folder (with a folder in it, with images in that) only results in the images being deleted, not the 2 parent folders. You have to delete the top level folder again for that to happen.

![screenshot-2023-11-16-at-22 00 17](https://github.com/supabase/supabase/assets/105593/7dab3bbb-a9f6-4d64-b7f7-209afc383d13)
![screenshot-2023-11-16-at-22 01 56](https://github.com/supabase/supabase/assets/105593/4b3977fa-5ee3-446c-a215-26b17ba41087)

**Comment by anonymous4561** [comment]
@saltcod can i work on this?

**Comment by saltcod** [comment]
Yes, sure @anonymous4561!

**Comment by anonymous4561** [comment]
@everyone it is open
