### ISSUE TITLE
SQL Editor errors handling is broken

### ISSUE THREAD

**Issue by igorlanko** [supabase/supabase#19035]
**Describe the bug**
When entering some potentially failing SQL query into the Editor an entire page errors out with Next's component showing `Application error: a client-side exception has occurred (see the browser console for more information).` message.

**To Reproduce**
1. Go to the SQL Editor.
2. Enter a query that's going to fail. For example, for me it was creating a view and selecting a column that doesn't exist. 
```sql
CREATE VIEW collection_page_artifacts AS
SELECT
	artifacts.*,
	collection_artifact.collection_id,
	collections.title,
	collections.user_id,
	collections.access,
        -- 'profiles' doesn't exist under 'collections', it's a separate table
	collections.profiles
FROM
	artifacts
INNER JOIN
	collection_artifact ON artifacts.id = collection_artifact.artifact_id
INNER JOIN
	collections ON collection_artifact.collection_id = collections.id
INNER JOIN
	profiles ON collections.user_id = profiles.id;
```
But I have this issue with literally every possible SQL query that's incorrect, even if it's just syntax error.

3. Run the query.

**Expected behavior**
- A query is run and the error is visible in the Results section.
- If that failed, I'd expect to go to Logs/Postgres and see the error log there, but as you can see in the second screenshot, the error/warning message looks scattered and broken down into other events with the same time stamp.

**Screenshots**
![image](https://github.com/supabase/cli/assets/31314207/21986679-6e45-4efc-a2a4-651f879d0f8a)
![image](https://github.com/supabase/cli/assets/31314207/b423e72b-d43e-4f08-a326-4cf48c216f1d)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1.1
 - Browser: Arc (Chromium) / Safari
 - Version of CLI: 1.112.0

**Additional context**
Worth mentioning that upon opening the SQL Editor page and entering some query, I have the “Failed to save” warning in the bottom right.
![image](https://github.com/supabase/cli/assets/31314207/fd6c9763-26bd-4c00-9f77-bf788e77a8c4)

**Comment by sweatybridge** [comment]
Since this issue is related to studio, you will be able to get quicker help from frontend repo.

**Comment by saltcod** [comment]
Hey @igorlanko that should fail like this: 
https://share.cleanshot.com/qYLKhWK0

Could you share the errors in your console? Curious about that failed to save warning

**Comment by igorlanko** [comment]
Hey @saltcod!

Oh right, should've included that as well! So this is what's in the console when I open the Editor and then add SQL code:

![CleanShot 2023-11-17 at 10 28 47](https://github.com/supabase/supabase/assets/31314207/4e3a67af-d2c6-446c-92c0-4ad66f16f641)

**Comment by jacob-8** [comment]
I'm getting the same thing. An SQL error causes a crash, and queries cannot save.

**Comment by leerobert** [comment]
I'm also getting an error as well:

It tends to happen whenever I try delete commands like: delete function xyz;

<img width="1212" alt="Screenshot 2023-11-21 at 9 14 50 AM" src="https://github.com/supabase/supabase/assets/6231418/6ac809d2-3404-44cf-864d-17ac4d341916">

**Comment by igorlanko** [comment]
Yeah makes it difficult to experiment with SQL writing it in the blind.

Is there anything we can try to provide to help address this?

**Comment by Stevbreu** [comment]
Hallo everyone,
i've got the same error like the others and I have no idea what's going wrong. Not every sql request shows an error. This statemant will execute sucessfully:
`select * from
  (select version()) as version,
  (select current_setting('server_version_num')) as version_number;`
  
  But this sql request went wrong:
`  select * from auth`

<img width="1437" alt="Bildschirmfoto 2023-11-27 um 19 53 12" src="https://github.com/supabase/supabase/assets/15010128/3b892e1a-8932-4ac6-9e81-316dea1ec536">
<img width="1339" alt="Bildschirmfoto 2023-11-27 um 19 55 31" src="https://github.com/supabase/supabase/assets/15010128/5a266c4a-c2bc-4a47-9045-cb7a1635c38e">

Thank's and regards 
Steven

**Comment by morandalex** [comment]
same here

Application error: a client-side exception has occurred (see the browser console for more information).
![image](https://github.com/supabase/supabase/assets/9484568/5cbbd2ac-c07a-4e3e-87a0-bfa8a0f7664a)

**Comment by saltcod** [comment]
Hi all — this should be fixed with the latest update. Could you report back if it's still not fixed for you?

**Comment by igorlanko** [comment]
Hey @saltcod, updated to `1.115.4` via brew and unfortunately still seeing the same error when for example trying to `SELECT *` from a nonexistent table.

**Comment by igorlanko** [comment]
Shouldn't this issue be in @supabase/cli? This is related to the cli, right?

**Comment by JunsikChoi** [comment]
I am having the same issue too with "supabase": "1.123.4".

**Comment by morandalex** [comment]
news on that?

**Comment by saltcod** [comment]
Thanks all — investigating

**Comment by Stevbreu** [comment]
Happy new year everyone 🙋‍♂️,

is there any news on this issue? 
The links above don't show any solutions. 

Greetings Steven

**Comment by alphvsn** [comment]
@Stevbreu 

Hey happy new year! Ive been experimenting with the 2024-01-01 version of studio and it works like a charm, but please note im still testing for things i use it for :) try using that for the docker-compose and get back with results

**Comment by igorlanko** [comment]
> @Stevbreu
> 
> Hey happy new year! Ive been experimenting with the 2024-01-01 version of studio and it works like a charm, but please note im still testing for things i use it for :) try using that for the docker-compose and get back with results

What version are you on? It's still reproducible for me on `1.127.4`.

**Comment by sweatybridge** [comment]
Please try the beta version to see if the problem persists: `npx supabase@beta start`

**Comment by JasonColeyNZ** [comment]
> Please try the beta version to see if the problem persists: `npx supabase@beta start`

The beta fixed the issue for me

**Comment by Stevbreu** [comment]
Hello everyone!

> > Please try the beta version to see if the problem persists: `npx supabase@beta start`
> 
> The beta fixed the issue for me, although now I'd really like the error window that appears to go away :)

Ok, I am using the docker package, but I don't know how to install the npx supabase@beta start? I used the following command :
`docker exec -it supabase-studio bash` 

But I see an error in the command line:

> cannot read config in /app: open supabase/config.toml: no such file or directory. Have you set up the project with supabase init?

How can I install the beta? Thanks for your help an teaching :-)

**Comment by saltcod** [comment]
sounds like you're in the wrong directory @Stevbreu

**Comment by joshenlim** [comment]
Hey everyone! This fix should already be out and I can verify on the dashboard as well from OP's sample SQL
<img width="1210" alt="image" src="https://github.com/supabase/supabase/assets/19742402/b7207615-e5ae-46fc-a1a2-ee335d04d0fe">

I'll be going ahead to close this issue but please do let us know otherwise! Thank you all once again for the help here to debug as well - we really appreciate it! 🙏
