### ISSUE TITLE
Dashboard broken/bugged unable to edit individual cells

### ISSUE THREAD

**Issue by hadescorporation** [supabase/supabase#19078]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My first ever issue.. plx be kind :3

Logging in and trying to edit a cell as usual doesn't do what it is supposed to do, ie, open up the editor. However, it is still possible to edit a row by selecting it and then editing it as a whole.

The issue came out of nowhere and I suspect it is a supabase change because of this console warning 

`ConfigCat - WARN - Evaluating getValue('navigationLayoutV2'). UserObject missing! You should pass a UserObject to getValue(), in order to make targeting work properly
`
`Failed to load resource: the server responded with a status of 400 ()`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Login
2. Go to a table
3. Try double clicking on a cell

Similar issue on even a new project on a new account. Tried on brave, thorium, and firefox browsers, getting the same error.

## Expected behavior

You should be able to edit the contents of the cell while double clicking it

## System information

- OS: Ubuntu 22
- Browser: Brave, Firefox
- Version of supabase-js: idk whichever version supabase.com runs 

## Additional context

I also get the below error in the browser console

"message": "Project ############### is not allowed to set up custom domain; please contact Supabase support."

As I said, this is happening even for a completely new account.

**Comment by GaryAustin1** [comment]
This is an issue and several users have encountered it.

**Comment by erfolgsleiter** [comment]
I can confirm this is an issue.

**Comment by saltcod** [comment]
Hi there

This issue was resolved earlier today. Thanks for the report!
