### ISSUE TITLE
Can't signUp email because logged in through OAuth

### ISSUE THREAD

**Issue by dattt117** [supabase/supabase#19088]
My email already exists because I signed in with google. I want to add additional login methods using email and password. I use the function `supabase.auth.signUp()` but because the email already exists it fails

**Comment by nikitastryuk** [comment]
same

**Comment by VeronikaKosa** [comment]
up pls

**Comment by encima** [comment]
If the email exists, can you try triggering a password reset and then logging in once that has been set?

**Comment by burggraf** [comment]
Triggering a password is indeed the proper way to do this.

**Comment by tranminhquang4421** [comment]
how man @burggraf ?
