### ISSUE TITLE
user_public and auth.users Entry has no e-mail-adress (Apple Auth)

### ISSUE THREAD

**Issue by benemanu** [supabase/supabase#19099]
Hi everyone,

we are using Sign-in with Apple in a Flutter app and it usually works fine but we suddenly have 51 users in our auth.users table where the email fields are blank.

Usually when someone signs in with Apple, the data in the raw_user_meta_data column looks like this (data censored by me):

{
  "aud": "com.mycompany.censored”,
  "exp": 1686234658,
  "iat": 1686148258,
  "iss": "https://appleid.apple.com",
  "sub": “censored_sub”,
  "email": “anonymous@emailaddress.com”,
  "nonce": “censored_nonce,
  "c_hash": “censored_c_hash”,
  "auth_time": 1686148258,
  "provider_id": “censored_provider_id,
  "custom_claims": {
    "auth_time": 1696848817,
    "is_private_email": true
  },
  "email_verified": true,
  "nonce_supported": true,
  "is_private_email": "true",
  "real_user_status": 2
}

But in the 51 cases where they also signed in with apple, the data in the raw_user_meta_data column looks like this:

{
  "iss": "https://appleid.apple.com",
  "sub": “censored_sub”,
  "name": “John Doe”,
  "full_name": “John Doe”,
  "provider_id": "censored_provider_id",
  "custom_claims": {
    "auth_time": 1695736510
  },
  "email_verified": true
}

There is no email key in the raw_user_meta_data. Has anyone had that problem and how do we fix this?

**Comment by Hallidayo** [comment]
Hi @benemanu - Just checking are you still experiencing this issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
