### ISSUE TITLE
Bug in website: organization name not appearing

### ISSUE THREAD

**Issue by Immortalin** [supabase/supabase#191]
When creating a new project and selecting a pre existing Organization, the organisation shows up as undefined (top left hand corner of the nav/crumb trail) in the project password input screen. (Safari, iPadOS)

**Comment by kiwicopple** [comment]
Good one @Immortalin !

![image](https://user-images.githubusercontent.com/10214025/92674851-c407cc00-f350-11ea-93f0-c8786962b4e0.png)

@phamhieu can I get you to look at this one?

**Comment by kiwicopple** [comment]
@phamhieu has fixed this now @Immortalin 🚢 

Thanks for spotting it
