### ISSUE TITLE
Create column side panel doesn't reset 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#19109]
When you create a column, save it an then create another column right away. 
The data type from the first column is "prefilled" the second time, but isn't actually selected.
If you don't explicitly select it again, it'll fail.  

On success, the side panel should reset to a clean slate.

https://share.cleanshot.com/0gXC77Xr
https://share.cleanshot.com/vfWhQCJP

**Comment by faizanraso** [comment]
> I'd love to take this one if no one else has picked it up yet

Hey @jk1551, from what I've seen, there's no formal process of issues being assigned. You can go ahead and submit a PR for it, and someone from the supabase team reviews it.

**Comment by jk1551** [comment]
So far what I've found on this is the state of the previous column opened is being saved somehow and when the next column is opened some of the state is carried over. I also discovered it is not only when you create a new column but also if you click to edit an existing column and the try to create a new one as well

**Comment by learner-mohit** [comment]
@saltcod kindly review my PR

**Comment by alaister** [comment]
Appears to be fixed.
