### ISSUE TITLE
Not logging back in on login -> sign out -> login on the same page using 3 party provider google.

### ISSUE THREAD

**Issue by TimDR-1356** [supabase/supabase#19113]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I have a react application for now it is fairly simple I have a home page and on that page it shows a Google login button if you are not already logged in and a sign out button if you are logged in. Now when I'm not logging in and I hit the Google login button the hash value changes and I'm logging in but "/#" still remains in the URL. Now it shows the sign out button and if I hit it I'm logged out and still "/#" remains in the URL. Now when I try to log back in I get a dubbele hash (#) character and it looks like it is trying to log me back in but the complete hash with values and the dubbele hash character is still visible and noting happens.

I think it has something to do with the hash character still remaining on the first Google login. Because when I switch pages after I first login I don't have "/#" anymore in the URL and then when I sign out and login again it does work because it doesn't say "/#" before hitting the Google login button again.

## To Reproduce
Create a react project,
Make a Google login and a sign out button,
Show sign out button when user is logged in and a Google login button when user is not logged in.
Now hit the Google login button. Then the sign out button and then the Google login button.

## Expected behavior
The user is logged back in on the second login time.

**Comment by encima** [comment]
Hey @TimDR-1356 
Thanks for opening!
Did you manage to solve your issue? This seems more like an issue with the routing in the React app but we can look deeper if you have not yet resolved this.

**Comment by encima** [comment]
Closing the issue due to it being inactive.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen it.
Cheers!
