### ISSUE TITLE
Deploying an edge function through Dockerfile gives an error

### ISSUE THREAD

**Issue by heinsenberg82** [supabase/supabase#19154]
I'm trying to deploy an edge function through Dockerfile. This is the relevant piece of code:

```
WORKDIR /app
COPY . .
ENV SUPABASE_ACCESS_TOKEN sbp_......
RUN npx supabase link --project-ref xxxxxxxxx
RUN npx supabase functions deploy my-edge-function
```

However, I get this error: `Error bundling function: fork/exec /root/.supabase/deno: no such file or directory`

I have no idea about what cause this error, would this be a bug?

**Comment by encima** [comment]
Closing due to no response, please comment if you are still experiencing this and we will re-open.
