### ISSUE TITLE
Failed to create user: An error has occurred: Failed to fetch 

### ISSUE THREAD

**Issue by Sabahsaeedi7** [supabase/supabase#19155]
# Bug report
  during create user got this error Failed to create user: An error has occurred: Failed to fetch on selfhosted

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
You have not really provided any information as to what you are doing with what code when you get this message. 
Failed to fetch is a very generic error.
You might be better off starting with a discussion or going to the Supabase Discord and seek help before declaring it a bug.

**Comment by boardmain** [comment]
I have te same issue, new self hosted server, invitation of a user work, if i try to create one user from studio i have the same error, to reproduce just follow the documentation for the self hosted solution

**Comment by GaryAustin1** [comment]
@boardmain 
Have you checked your logs for any useful information?
Also there are cases where a CORS browser extension can cause PATCH requests to fail.  I don't know that they would impact that particular features, but the error is failed to fetch.
https://github.com/orgs/supabase/discussions/17296

**Comment by lxbxinwei** [comment]
> @boardmain Have you checked your logs for any useful information? Also there are cases where a CORS browser extension can cause PATCH requests to fail. I don't know that they would impact that particular feature, but the error is failed to fetch. https://github.com/orgs/supabase/discussions/17296

When I use Edge/chrome in Windows10 without any browser extension, it still turns out this error when I create a user in dashboard.

**Comment by GaryAustin1** [comment]
You get an error or failed to fetch?  It is common when adding or making changes to any auth.users trigger function to get a database error on creating a user.  Please check your Postgres log in the dashboard.

Also clear local storage and flush the browser cache.

**Comment by lxbxinwei** [comment]
> You get an error or failed to fetch? It is common when adding or making changes to any auth.users trigger function to get a database error on creating a user. Please check your Postgres log in the dashboard.
> 
> Also clear local storage and flush the browser cache.

I checked. There is no any Postgres log in the dashboard, I just follow [doc](https://supabase.com/docs/guides/self-hosting/docker), and did nothing else.

**Comment by GaryAustin1** [comment]
Well I suggest you start a new post or generate a Discord post to with more info and see if someone can help you.  Not enough info without seeing error code, call, framework info, etc.
Failed to fetch is very generic so adding on to an existing issue that has not had any info in 2 months is not going to get much attention from users who might have ideas for you.

**Comment by emmyduruc** [comment]
any solution to this? creating a user in auth via the studio in locally running supbase leads t this error 
![image](https://github.com/supabase/supabase/assets/82957750/5b9c4d08-f7a2-4586-90a3-dc2580a68d90)

**Comment by alsherif-khalaf** [comment]
> any solution to this? creating a user in auth via the studio in locally running supbase leads t this error ![image](https://private-user-images.githubusercontent.com/82957750/328570486-5b9c4d08-f7a2-4586-90a3-dc2580a68d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDQ5NzAsIm5iZiI6MTcxNzUwNDY3MCwicGF0aCI6Ii84Mjk1Nzc1MC8zMjg1NzA0ODYtNWI5YzRkMDgtZjdhMi00NTg2LTkwYTMtZGMyNTgwYTY4ZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEyMzc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOTc5ZDNhNWQ4NjcxNGIzZmQyM2E0NGYzNzk0MmU2OTBkY2Y5NjZlZGFhM2FjMDNmN2RkNGZiMzU0ZWI5ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mn16T9kKpIRm-6Eagl2LKHZOPs3OymSqfXmnsS6u32I)

any solution ?

**Comment by srsquare** [comment]
I have latest version installed via docker, the port I use to get into the gui is 8080. When I tried to add a user I noticed in console network tab that its calling localhost port 8000 localhost:8000/auth/v1/admin/users ... I am still digging so may have more info to share soon.
