### ISSUE TITLE
redirectTo works but cuts the "and" params "&param2=val2&param3=val3"

### ISSUE THREAD

**Issue by alexandregiordanelli** [supabase/supabase#1915]
# Bug report
redirectTo works but cuts the "and" params "&param2=val2&param3=val3"..

## Describe the bug

when the page that user do the login has 1 parameter only, it is fine, but, when put more parameters, the supabase cuts it.

## To Reproduce

https://user-images.githubusercontent.com/1518223/121587242-f2632680-ca0a-11eb-9eb3-dd5b7ae7f899.mov

```typescript
    let { user, error } = await supabase.auth.signIn({
      provider: 'google'
    }, {
      redirectTo: window.location.href
    });
```

## Expected behavior

not cutting the url to reproduce the entire state of the website when user start the login..

**Comment by saampotter** [comment]
It looks this is still an issue when signing in with an email magiclink. To reproduce, call the following method

```jsx
await supabase.auth.signIn({ email: 'sam@univo.app' }, { redirectTo: window.origin + '/dashboard?test1=1&test2=2' })
```

You'll notice that the generated link in the email fails to properly encode the redirect url. 
```
https://{project_id}.supabase.co/auth/v1/verify?token=...&type=magiclink&redirect_to=http://localhost:3000/dashboard?test1=1&test2=2
```

Causing the api to read the query params as `token=...`, `redirect_to=...`, and `test2=2`. Therefore causing the `test2` param (and any subsequent `&` query params) to be omitted from redirect url.
