### ISSUE TITLE
Can we use our existing postgres sql databse with supabase

### ISSUE THREAD

**Issue by prohith14** [supabase/supabase#19187]
### Discussed in https://github.com/orgs/supabase/discussions/19096

<div type='discussions-op-text'>

<sup>Originally posted by **prohith14** November 20, 2023</sup>
- We want to use supabase with our futter application for the real time data updates, how ever we want to use our own postgres sql database</div>

**Comment by prohith14** [comment]
When im trying to attach my postgres sql database , im facing error regarding creating schemas .
although im able to connect to my databse im getting basic authentication error
![MicrosoftTeams-image (3)](https://github.com/supabase/supabase/assets/20105628/b1400e79-6781-4228-b71d-0341bfe747bf)

**Comment by saltcod** [comment]
(closing in favour of the discussion)
