### ISSUE TITLE
All connection attempts from Metabase are banned

### ISSUE THREAD

**Issue by mjp0** [supabase/supabase#19228]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I try to add Supabase database as Postgres connection in Metabase, all connection attempts result in IP banning. Manually removing the ban doesn't fix this, it will just ban it again.  Adding Metabase server IP as allowed IP in restrictions doesn't fix this either. I currently have my IP as allowed in restricted and banned at the same time, I'm guessing this shouldn't happen.

I also tried resetting the password but that didn't work either.

## To Reproduce

1. Install Metabase
2. Add Supabase Postgress as database

## Expected behavior

Metabase is able to connect and query postgres.

## System information

Not relevant as I'm using supabase.com hosted.

**Comment by mjp0** [comment]
just fyi, redash also gets banned, so looks like your system is messed up and unusable.

**Comment by encima** [comment]
I can confirm I am able to connect from 2 separate projects (existing and new) from Redash and Metabase (self hosted).

Can you confirm you have:
- enabled access
- unblocked the IP
- Set the SSL mode to `prefer` or `require` (without verifying the client cert)
- Set the port to 5432
- If you still have issues, you can set the schema to `only these` and use `public`

Let us know if it works!

**Comment by encima** [comment]
Closing this as it was not reproducible and may have been a bug at the time. 
Please do comment if this still occurs and we can re-open!
