### ISSUE TITLE
SwiftUI logo visibility issue in light more. 

### ISSUE THREAD

**Issue by shashankdaima** [supabase/supabase#19223]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
![image](https://github.com/supabase/supabase/assets/64317542/49f4c74c-1dec-45fb-9c8f-f1e9274e9825)
The SwiftUI logo above is not visible in light mode.

**Comment by shashankdaima** [comment]
If this is a valid bug then i would like to fix this issue.

**Comment by saltcod** [comment]
go for it please @shashankdaima !

**Comment by FrostyDog** [comment]
@shashankdaima u r working on this issue, right?
I would like to tackle this one, if its available.

**Comment by junsupark94** [comment]
I went to supabase.com/docs and this is how the section looks to me currently.

![Client Libraries](https://github.com/supabase/supabase/assets/97586064/294ef253-5771-49aa-8c32-b4ced6448cc1)

@shashankdaima Is this still an issue? Could you tell me where this issue occurs?

**Comment by alexwhitmore** [comment]
I just opened up Supabase studio locally and can confirm that this is still an issue. @shashankdaima are you still working on this or is it okay for me to take on?

**Comment by FrostyDog** [comment]
@souloper I belive it was fix with the PR above from @deeksharungta.

**Comment by FrostyDog** [comment]
@deeksharungta confirm please, if the issue can be resolved and closed?

**Comment by deeksharungta** [comment]
> @deeksharungta confirm please, if the issue can be resolved and closed?

hey, I've fixed the issue and raised a PR but it hasn't got merged yet!

**Comment by Nayanchandrakar** [comment]
Its not an  issue bro working fine i checked it out
