### ISSUE TITLE
Issue with supabase local with latest version 1.113.2

### ISSUE THREAD

**Issue by ripuser** [supabase/supabase#19226]
# Bug report
I updated to the latest version 1.113.2 via homebrew.
It seemed to cause a problem with rendering Functions and Triggers in the console. Go to Database > Functions or Triggers (see screenshot)
I found someone else with the same issue on Discord and someone else had said to roll back to 1.110.1
I managed to do this with brew, albeit a bit painful, now its working again
The other guy with the issue installed 1.110.1 using npx as he coudnt get it right with brew and it worked for  him too.

![image](https://github.com/supabase/supabase/assets/137481357/59c6a003-f01a-404e-927d-01f874d31634)

![image](https://github.com/supabase/supabase/assets/137481357/c11bfff4-6eab-4980-b70c-d97ee28151bf)

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by ripuser** [comment]
Now seeing this when trying to run a sql query on 1.110.1 which is what I downgraded to:

<img width="1505" alt="image" src="https://github.com/supabase/supabase/assets/137481357/3d198ffd-341b-4034-9bb2-a1a97a6d69df">

**Comment by saltcod** [comment]
Should be fixed in the latest release. Please reopen if the issue persists.
