### ISSUE TITLE
Leading the user to the proper installation guide

### ISSUE THREAD

**Issue by ibilalkayy** [supabase/supabase#19230]
# Chore

## Describe the chore

In the Getting Started [page](https://supabase.com/docs/guides/getting-started), the local development should lead us to the [Overview page](https://supabase.com/docs/guides/cli) or more appropriately to the [Getting Started page](https://supabase.com/docs/guides/cli/getting-started).

#### Why I am saying this?

Because if the person wants to install supabase for the first time, it is really difficult to find the required resource for that. I also found it difficult to find that resource when I first started installing Supabase.

#### There are two suggestions

1. Either lead the user to the [Overview](https://supabase.com/docs/guides/cli) or more appropriately to the [Getting Started page](https://supabase.com/docs/guides/cli/getting-started) as I mentioned above.
2. Create a new menu by the name of **_Installation_** with Features, Architecture and Local Development so that it becomes easy for the user to easily find the installation guide.

Please let me know whether you find it useful or not. If yes, then I can work on this issue.

Thank you!

## Additional context

![Screenshot from 2023-11-26 14-21-08](https://github.com/supabase/supabase/assets/64713734/b9ef264d-74e9-49b3-ae19-80b1def73c3b)

**Comment by GuillemGarciaDev** [comment]
Hello!

Is this issue still open?

If so I would like to take it to make the feature, thank you!

**Comment by saltcod** [comment]
Probably want a quick look from @charislam on direction first @GuillemGarciaDev — thanks for the offer!

**Comment by GuillemGarciaDev** [comment]
> Probably want a quick look from @charislam on direction first @GuillemGarciaDev — thanks for the offer!

Perfect! I'll keep an eye out for news. Thank you! @saltcod

**Comment by charislam** [comment]
This is good feedback! I think it makes sense to change the link for the `Local Development` card to the [Getting Started page](https://supabase.com/docs/guides/cli/getting-started).

Feel free to open a PR!

**Comment by charislam** [comment]
Thanks! Looks good
