### ISSUE TITLE
Persistent ECONNREFUSED Error with Supabase Cloud Database Connection

### ISSUE THREAD

**Issue by immocalcul** [supabase/supabase#19232]
### Discussed in https://github.com/orgs/supabase/discussions/19231

<div type='discussions-op-text'>

<sup>Originally posted by **immocalcul** November 26, 2023</sup>
Hello, we are panicked, it has been more than 24 hours since all our services have been offline and supabase cloud technical support is not keeping us informed of the situation. We have tried to update Postgres from their interface and since then nothing has happened, here is an overview of what we are encountering as if the remote server was no longer accessible. I was able to download a backup that we had. we created a new project is there a way to import this backup and restore it in a new project? in backup we only see a way to download it locally but not to import it
![supabase](https://github.com/supabase/supabase/assets/50158038/f82d00d7-13d2-43d2-ad7e-fe6cfbe8cdec)
</div>

**Comment by saltcod** [comment]
closing in favour of discussion
