### ISSUE TITLE
Realtime Connection in Android

### ISSUE THREAD

**Issue by MrAndroi** [supabase/supabase#19268]
Hello, 👋 

I was trying to observe for events in my table called "test" I added all required dependencies and here is my code,

`
    private val supabase = createSupabaseClient(
        supabaseUrl = "https://yrhfsbaucrjivrncjtnv.supabase.co",
        supabaseKey = "my_key"
    ) {

        install(Postgrest)
        install(Realtime) {
            reconnectDelay = 5.seconds
        }
    }

    override fun <T> readData(path: String, type: Class<T>): Flow<DbResult<T>> = callbackFlow {
        val channel = supabase.realtime.createChannel("channelId")
        val changeFlow = channel.postgresChangeFlow<PostgresAction>(schema = "public") {
            table = "test"
        }

        changeFlow.collect {
            when (it) {
                is PostgresAction.Delete -> {
                    trySend(DbResult.Success(null))
                }

                is PostgresAction.Insert -> {
                    trySend(DbResult.Success(convertRecordToType(it.record, type)))
                }

                is PostgresAction.Select -> {
                    trySend(DbResult.Success(convertRecordToType(it.record, type)))
                }

                is PostgresAction.Update -> {
                    trySend(DbResult.Success(convertRecordToType(it.record, type)))
                }
            }
        }

        supabase.realtime.connect()
        channel.join()

        awaitClose {
            launch {
                channel.leave()
                supabase.realtime.removeChannel(channel)
            }
        }

    }

`

Is there any issues with my code?

i got this error when i try to connect for table.

`
     Error while trying to connect to realtime websocket. Trying again in 5s
                                                                                                    URL: wss://yrhfsbaucrjivrncjtnv.supabase.co/realtime/v1/websocket?apikey=myKey=1.0.0
                                                                                                    java.lang.IllegalArgumentException: Engine doesn't support WebSocketCapability
                                                                                                    	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.checkExtensions`

and here is dependencies
` 
  //SupaBase

    implementation(platform("io.github.jan-tennert.supabase:bom:1.4.7"))
    implementation("io.github.jan-tennert.supabase:postgrest-kt")
    implementation("io.github.jan-tennert.supabase:realtime-kt")
    implementation "io.ktor:ktor-client-android:2.3.6"
    implementation "io.ktor:ktor-client-core:2.3.6"
    implementation "io.ktor:ktor-utils:2.3.6"
    implementation("org.jetbrains.kotlin:kotlin-serialization:$kotlin_serialization")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlin_serialization_json")
    implementation("org.jetbrains.kotlinx:kotlinx-collections-immutable:$kotlin_serialization_collections")

`

Can anyone help ?

**Comment by jan-tennert** [comment]
@MrAndroi Ktor's Android Client Engine doesn't support Websockets. Use OkHttp or CIO. See [limitations](https://ktor.io/docs/http-client-engines.html#limitations)

**Comment by jan-tennert** [comment]
@jan-tennert If you mean using the OkHttp Engine, just add this dependency:
```kotlin
implementation("io.ktor:ktor-client-okhttp:$ktor_version")
```

**Comment by akardas16** [comment]
adding ktor okhttp and Android engine dependency both also doesn't work. you have to remove android engine dependency
