### ISSUE TITLE
Webhook disappeared from the Database Local?

### ISSUE THREAD

**Issue by polidario** [supabase/supabase#19274]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The webhook is no longer in the local database menu. But in supabase.com, it is present.

## Expected behavior

Upon opening the database page, there should be a webhook sublink.

## Screenshots

![image](https://github.com/supabase/supabase/assets/71621723/726f030c-e825-4213-b768-1d7510682abd)

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of supabase-js: ^2.38.5
- Version of Node.js: 18.17.1

**Comment by polidario** [comment]
> This still happening on the latest release @polidario ? Working as expected on my end.

Yes this is still happening on my end, but it's just a menu link bug. What I mean is, when I go directly to the link: [http://localhost:54323/project/default/database/hooks](http://localhost:54323/project/default/database/hooks), it displays the webhook page. So yes, it's just the link missing which is odd.

**Comment by Hallidayo** [comment]
@polidario - Just tried this locally and I can see the Webhooks menu on the nav:

<img width="1440" alt="Screenshot 2023-11-30 at 18 57 52" src="https://github.com/supabase/supabase/assets/22655069/f705572e-5037-42cb-ae37-08583e57b28f">
