### ISSUE TITLE
Realtime broadcast event not fired on Vercel

### ISSUE THREAD

**Issue by GuysmoB** [supabase/supabase#19301]
Hey,

I'm working on a chat feature and I recently switched from Pusher to Supabase Realtime. I've encountered inexplicable bugs in the past with Realtime, but I decided to give it another shot.

Everything works fine in localhost with a dev or prod build. However, once I deploy the app on Vercel, I encounter a bug when sending an event. The event isn't fired except when I refresh client A (the one who sent it). Sometimes, it also triggers when I refresh client B (the receiver).

I've inspected the Realtime Inspector, and I notice the event is displayed only when client B receives it, which happens when I refresh client A and absolutely no logs are triggered inside the channel subscription.

Next.js: 13.5.6,
Supabase: @supabase/auth-helpers-nextjs@0.8.7

Thanks for any help !

![image](https://github.com/supabase/supabase/assets/42407006/662f4d11-6a0b-4332-9a86-105010709bd1)

**Comment by MrWinbush** [comment]
I am also having a similar issue on a Nuxt app.  Have you found any solutions?

**Comment by GuysmoB** [comment]
Not yet. The problem is i have no logs or informations to share on this bug :/

**Comment by GuysmoB** [comment]
I switched to server actions and the problem seems to be gone.

**Comment by janek** [comment]
I had some trouble switching to server actions in my case, but managed to solve it by switching to Netlify - the events seem to fire there without issues

**Comment by davidystephenson** [comment]
> I switched to server actions and the problem seems to be gone.

How did you implement this with server actions?

**Comment by latifs** [comment]
Hey guys, did anybody figured it out?
I have the same problem on a deployed nextJS app on Vercel.
Thanks
