### ISSUE TITLE
Supabase Image Transformer Messing with image color channels?

### ISSUE THREAD

**Issue by kkukshtel** [supabase/supabase#19335]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

An image being server over supabase with a transformer is returning an inverted color version of the image.

## To Reproduce

I'm not sure — the attached image, when uploaded and served to storage, is returning an inverted color version of itself (see screenshot)

## Expected behavior

The image should look "normal"

## Screenshots

base image:
![image_b1f9OGPS](https://github.com/supabase/supabase/assets/7715279/9171ff3b-a49a-4798-a8bd-9193ac305444)

once uploaded and served back via supabase:
<img width="714" alt="Screen Shot 2023-11-30 at 11 11 41 AM" src="https://github.com/supabase/supabase/assets/7715279/c15791d1-de27-4df0-ac78-f5f392a50ab4">

## System information

- OS: macOS/PC
- Browser (if applies) safari
- Version of supabase-js: latest
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Here's the transformer call I use for the return from the server:
```
.createSignedUrl(`${folderPath}/${file.name}`, 60 * 60, ext == "gif" ? null : {
            transform: {
              quality : 40
            }});
```

This image specifically seems to be the weird one. I've never seen this in my app before at all so wondering if the bit encoding of the jpeg itself is weird? Not sure

**Comment by GaryAustin1** [comment]
Did you just upload and download the image?
Has that image worked before or is it a new image?

**Comment by kkukshtel** [comment]
I had gotten the image from this twitter thread, specifically this tweet:

https://x.com/dieworkwear/status/1729621211456446694?s=46

It displays fine in twitter and as you can see looks fine when uploaded normally (GitHub doesn't munge it), but when it is returned from storage something is happening. Also worth noting that the "correct" image in GitHub above is the image downloaded from storage inside the supabase dashboard, and that image got into storage there through my site upload (not from my desktop). Which is to say that I think the point of failure is the last place it travels through, which is the supabase transformer.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
