### ISSUE TITLE
db-password flag falsely marked as optional in doc for supabase projects create cli command

### ISSUE THREAD

**Issue by maxfornacon** [supabase/supabase#19342]
# Improve documentation

## Link 

https://supabase.com/docs/reference/cli/supabase-projects-create

## Describe the problem

The `db-password` flag is marked as `optional`. Which it isn't, since you need to provide a password on setup.
I received an error message saying: `required flag(s) "db-password" not set`, which is correct.

## Describe the improvement

Either mark the flag as required in the documentation or generate a password like you can do in Supabase Studio when creating a project manually.

**Comment by junsupark94** [comment]
Here is the PR: https://github.com/supabase/supabase/pull/19364

Also I'm having issues trying to run the docs locally. Ran `npm install` and `npm run dev`. 
Says module 'shared-data' can't be resolved. 
Ran `npm install shared-data`. 
Says module 'reactflow' can't be resolved. 
Ran `npm install reactflow`. 
Says document is not defined in node_modules/lottie-light-react/build/index.js:42:5

**Comment by charislam** [comment]
Thanks @junsupark94!

Just checked quickly on my machine and not having any problems with local dev. Perhaps this is a trivial suggestion, but is your Node version correct? If the problem persists, feel free to open a separate issue for tracking. I'll mark this one as closed once your PR merges!
