### ISSUE TITLE
Can't update foreign key in a table view

### ISSUE THREAD

**Issue by obetomuniz** [supabase/supabase#1935]
# Bug report

## Describe the bug

Trying to update a foreign key to another in a given table column stuck in infinite loading when pressing "Save"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a Table Column with the foreign key format of UUID and press to edit
2. Change that Table Column with the foreign key format of UUID to another valid UUID foreign key
3. Press "Save" button in the form
4. See the infinite loading

## Expected behavior

It should update the foreign key to a new value when edited and not stuck in infinite loading.

## System information

- OS: macOS
- Browser: All Browsers

**Comment by kiwicopple** [comment]
Thanks for the bug report here @obetomuniz - fix is on it's way 🚢

**Comment by EdgarBarrantes** [comment]
Not reporter, but awesome! Thanks!

For the next person who sees this, you can just create the relationship manually by creating new query in the SQL tab and run something like:
```
ALTER TABLE public.users_projects ADD constraint users foreign key (user_id) references auth.users (id);
```

**Comment by joshenlim** [comment]
hey there @obetomuniz ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
