### ISSUE TITLE
Edit row not possible due to spurious table field "idx"

### ISSUE THREAD

**Issue by styxlab** [supabase/supabase#1939]
# Bug report

## Describe the bug

When I want to update a row in the supabase admin dashboard, a new field is shown with the name "idx" which is not part of my table schema. This spurious filed inhibits saving the record.

## To Reproduce

1. Go to a table that contains rows
2. Click on Edit row
3. Notice a new field called "idx" which is not part of the table
4. Save and see error.

## Expected behavior

Able to edit /change rows. No fields should appear that are not part of the table schema:

![image](https://user-images.githubusercontent.com/19638263/121776364-b8219280-cb8c-11eb-8664-93944439aa80.png)

## Screenshots

![image](https://user-images.githubusercontent.com/19638263/121776672-80b3e580-cb8e-11eb-9c6f-fa6cad339667.png)

This problem appeared a couple of days/weeks ago.

## Additional context
Problem could be related to a new Prisma schema that uses camel case fields. However, everything works expected when I use direct SQL in the supabase CLI.

**Comment by kiwicopple** [comment]
Very odd - seems like Prisma has added something to the table. How did you generate the first screenshot? I'm guessing it was something like this?

```
select column_name, data_type from information_schema.columns
where table_name = 'User';
```

If not, could you please run this and let us know the results? I'm not able to replicate this on any of my own projects (although none of them are using Prisma.

**Comment by styxlab** [comment]
Yes, I had a similar query, The output of yours is the same:
![image](https://user-images.githubusercontent.com/19638263/121801220-8402ac00-cc36-11eb-8ee5-93f9ef414449.png)

**Comment by kiwicopple** [comment]
Odd, because if I search for `idx` anywhere in your schema I can't find it "https://github.com/styxlab/supabase_issues/blob/main/supabase_schema.sql".

Must be a problem with an iterator in our Dashboard, although I don't know why it's only appearing in this case. Does it appear on your other tables too?

**Comment by styxlab** [comment]
Yes, it appears on all my tables.

**Comment by styxlab** [comment]
I managed to reproduce this as well. First start with exactly the same steps as in #1940. Then

1. add a new row in table users over the CLI
`INSERT INTO public."User" (id, email) values (1,'a@a.de')`

Once the entry is the database click on the row and select

2. 'Edit row'

Now the "idx" field appears in the side screen:

![image](https://user-images.githubusercontent.com/19638263/122554247-09bc9800-d039-11eb-8d43-369b6205d9e5.png)

**Comment by phamhieu** [comment]
@styxlab, we updated the dashboard app recently. Please let me know if you are still facing the issue.

**Comment by styxlab** [comment]
The problem still exists or do I need to delete the database and start over?

**Comment by phamhieu** [comment]
Hi @styxlab as i can't replicated the issue on my side. 

It will be very helpful if you can try with a new org and project. If the bug appears again, can you add my account to the new org team `phamhieu1998@gmail.com`. I can debug the issue from there. Thank you very much.

**Comment by styxlab** [comment]
Running
```
grant all on all tables in schema public to anon;
```
as suggested on #1940 also fixes this issue. Could you explain the reason behind this?

**Comment by phamhieu** [comment]
I don't know why running that SQL will fix this issue. The 2 issues are not related at all.

**Comment by joshenlim** [comment]
will be closing this ticket as it seems like the issue has been resolved but feel free to reopen otherwise

**Comment by styxlab** [comment]
It's resolved. Thanks you!
