### ISSUE TITLE
Studio crashes when SQL error in SQL editor

### ISSUE THREAD

**Issue by dreinon** [supabase/supabase#19399]
**Describe the bug**
Supabase studio crashes when a query in SQL editor returns an error

**To Reproduce**
1. Go to 'SQL editor in the local Studio'
2. Run 'select random_non_existing_column'
3. See error

**Expected behavior**
The studio showing the error in a pretty way, like the cloud version of the studio.

**Screenshots**
![image](https://github.com/supabase/cli/assets/67071425/32d9e5f0-d93b-4a15-86b0-2a48b894a27c)

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL2 with Windows 11)
 - Browser: Chrome
 - Version of CLI: 1.115.4

**Additional context**
Once the crash happens, you cannot reenter the SQL editor page by the frontend because it crashes again. When refreshing the SQL editor url, it opens but the query that was causing the error disappears.

**Comment by gimdongwoo** [comment]
@saltcod This error is not resolved.

I tested `create or replace view` statement in studio at master branch now.

**Comment by leerobert** [comment]
As of `1.123.4` issue is still not resolved in studio.

**Comment by zedeus** [comment]
Still not fixed as of 1.127.3

**Comment by encima** [comment]
Closing this in favour of #19035, please add discussions or feedback there
