### ISSUE TITLE
Issue finding docker image when starting local DB

### ISSUE THREAD

**Issue by brandonbrown4792** [supabase/supabase#19392]
# Bug report

I'm having an issue when trying to start local development via supabase start. It appears that the remote docker image cannot be found:

```bash
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.76 not found: manifest unknown: Requested image not found
```

What I've done:
Ran supabase init command to intialize the supabase folder in the root of my project
Ran supabase login - went through succesfully
Linked supabase project via supabase link - Linked successfully
Ran supabase start - Got manifest not found error

I was about to get around this by changing my postgres version in `supabase/.temp/postgres-version` from `14.1.0.76` to `15.1.0.117`.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to start local supabase development server due to docker image not being found

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go through the Supabase local development guide [here](https://supabase.com/docs/guides/cli/local-development)
2. Get to the `supabase start` step
3. See that an error is returned for the postgres container saying that the image could not be found

## Expected behavior

I should see the postgres container installed as expected and the supabase development server start

## Screenshots

Sorry, don't have a screenshot anymore, but this is the message that was thrown:
```bash
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.76 not found: manifest unknown: Requested image not found
```

## System information

- OS: Windows
- Browser (if applies) N/A
- Version of supabase-js: 2.0.5
- Version of Node.js: 18.16.1
- Supabase CLI version: 1.115.4

**Comment by Sergii-Shpak-072422** [comment]
I have the same issue.

**Comment by Sergii-Shpak-072422** [comment]
The workaround mentioned in the bug description works for me as well. Thank you.

**Comment by 0Howwise** [comment]
I also had the same issue and change from 14.1.0.76 to 15.1.0.117 worked

**Comment by dhurbhat** [comment]
I have the same issue as of this AM and the workaround **DOES NOT** work for me.

Additional info:
1. Doing a db pull caused errors on an existing project
2. I created a new local dir and initialized with `supabase init`
3. Checked the `supabase/.temp/postgres-version` and it was at: 15.1.0.19 
4. Changed the version to 15.1.0.117 and now I get the following error:
```invalid reference format
Retrying after 4s: public.ecr.aws/supabase/postgres:15.1.0.117```
I looked for the version number in aws ecr and found that the latest appears to be no 15.1.0.19, but the one's mentioned here or even 15.1.0.22 (which is in the ECR) give the same error.

I'm stuck :( as I wanted to migration 'cause I had many schema changes to make.

**Comment by dhurbhat** [comment]
Oh - figured it out.  My use of `vim` was adding a newline which was causing the CLI to report `invalid reference format`.

If you are using VI (or VIM) then make sure you edit `.temp/postgres-version` in binary mode and `set noeol` in VI so that the newline doesn't get recorded with your save.

Also AWS ECR link for supabase is here: https://gallery.ecr.aws/supabase/postgres and you can use this to verify which versions are available.

**Comment by encima** [comment]
Thanks for opening, this has been resolved with the CLI now and 15 is the default postgres version.

This can be resolved by:
- Ensuring you are using the latest CLI version
- Check available versions here: https://gallery.ecr.aws/supabase/postgres (and modify if needed, although you should not need to)

**Comment by talamaska** [comment]
I just installed on a fresh PC. The supabase cli installed with brew in wsl is 1.148.6, which seems to be the same in npm. And I got the error with the postgres image version 
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/postgres:15.1.0.19 not found: manifest unknown: Requested image not found

The actual latest version of posgres is 15.1.1.26 in https://gallery.ecr.aws/supabase/postgres.
Just fyi.

**Comment by JNuno007** [comment]
Had the same issue.

Solution for me: 

* Unlink any project reference with "supabase unlink"
* Logout with "supabase logout"
* Remove the supabase folder from your local project
* Update the supabase cli
* "Supabase init" and then "supabase start"

Only after that log in again and link with your remote project

**Comment by Nciso** [comment]
Hi this worked for me


check first the official docker image tag  in the aws repository  -> https://gallery.ecr.aws/supabase/postgres

then in the `.temp `folder in the supabase directory of your local setup, change the version in the file called `postgres-version`

> I fixed the issue by doing the following:
> 
> checking which postgres version is used: `docker ps` -> public.ecr.aws/supabase/postgres:15.1.0.147
> 
> and then running:
> 
> `echo -n "15.1.0.147" > .temp/postgres-version`
