### ISSUE TITLE
Enum values are not selectable and manually selected values cannot be saved

### ISSUE THREAD

**Issue by styxlab** [supabase/supabase#1941]
# Bug report

I am sure this was working some weeks ago, but I cannot select the enum values in the dashboard anymore. The enums are correctly defined:

![image](https://user-images.githubusercontent.com/19638263/121776564-e5bb0b80-cb8d-11eb-9f74-66aadb4be783.png)

## To Reproduce

1. Go to table view
2. Click on a column where an enum type was defined
3. Click to see values for selection
4. See that only the current value and [null] is shown for selection, not the expected enum values

![image](https://user-images.githubusercontent.com/19638263/121776626-2e72c480-cb8e-11eb-977b-594500469770.png)

## Expected behavior

Enums should work like intrinsic types.

## Additional context
Problem could be related to a new Prisma schema that uses camel case fields. However, everything works expected when I use direct SQL in the supabase CLI.

**Comment by kiwicopple** [comment]
I think you might be correct about the Prisma set up again, because it seems to be working fine on my projects: 

![image](https://user-images.githubusercontent.com/10214025/121798319-326b1900-cc58-11eb-9e0f-984c1b1bf8b6.png)

Once we have your schema requested [here](https://github.com/supabase/supabase/issues/1940#issuecomment-860163946) we should be able to debug this

**Comment by styxlab** [comment]
Now able to consistently reproduce the issue with the following steps:

1. Create new database on supabase.io
2. `git clone https://github.com/styxlab/supabase-prisma-issue.git`
3. `cd supabase-prisma-issue`
4. npx prisma migrate dev --name init
5. Add a user with "Insert row" in the admin interface.

Observe that the `enum` values `USER` and `ADMIN` cannot be selected:

![image](https://user-images.githubusercontent.com/19638263/122551938-f0feb300-d035-11eb-9f4a-38634f06ce26.png)

**Comment by styxlab** [comment]
Turns out this is *not* a prisma issue and I can reproduce it with direct SQL as follows:

1. Create new database on supabase.io
2. Execute the following script:
```
-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" "Role" NOT NULL DEFAULT E'USER',

    PRIMARY KEY ("id")
);
```
3. Add a user with "Insert row" in the admin interface.
4. Observe that the enum values USER and ADMIN cannot be selected.

**Comment by phamhieu** [comment]
Thanks @styxlab for the details. We are working on the fix now.

**Comment by phamhieu** [comment]
This happens because of an issue on `postgres-meta` https://github.com/supabase/postgres-meta/issues/119. It has been fixed. When the new version is deployed to prod, i will update you @styxlab. 

Thanks for reporting the issue.

**Comment by styxlab** [comment]
Seems to work now. Thanks for fixing this issue!
