### ISSUE TITLE
Documentation: Migration Guide - Creating a client improvements 

### ISSUE THREAD

**Issue by theonlydaleking** [supabase/supabase#19444]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=server-component#creating-a-client

## Describe the problem

When upgrading - specifically from the auth-helpers package, it wasn't immediately obvious as to how to implement the new methods. 
It seemed to be that it was recommended you put the whole code block in every file that would use Supabase Auth. 

It wasn't until I tried the create-next-app with-supabase and inspected that code, that I realised these should actual be in a utils folder. 

## Describe the improvement

something along the lines of: 

"it is recommended to create these functions in a /utils/supabase folder and import them as necessary:" 

```ts
// /utils/supabase/client.ts
import { createBrowserClient } from '@supabase/ssr'

export const createClient = () =>
  createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
```
usage: 
```ts
// /SomeComponent.tsx
"use client" 

import {createClient} from '@/utils/supabase/client.ts'

const Component = () => {
    const supabase = createClient()
    ...
}
```

**Comment by encima** [comment]
Hi @theonlydaleking ,

thanks for reporting this, what you suggest certainly makes sense to call it out and make it clearer. If you wanted, feel free to modify the documentation directly and open a PR! If not, lemme know and I can update next week.

**Comment by j4n-e4t** [comment]
Is anyone working on this? If not, then I’d linke to update the docs. @encima Could you assign me?

**Comment by encima** [comment]
@j4n-e4t assigned you for this, thanks! note: we don't normally assign issues and they can be picked up by anyone so feel free to just open a PR and tag the issue in the future 😄

**Comment by j4n-e4t** [comment]
Thanks! Ok, I'll do this in the future 😉

**Comment by j4n-e4t** [comment]
That might be a stupid question, but I am just trying to get the dev server of the docs site up and running.

![Screenshot 2024-01-28 at 23 33 21](https://github.com/supabase/supabase/assets/130256240/939934d6-c7d2-49c2-b596-3899103a8600)
owever, the Nextjs dev server seems to crash all the time. What am I doing wrong?

**Comment by Hallidayo** [comment]
@j4n-e4t - from the root `supabase` directory try running:  `npm run dev:docs`

You should then be able to run the docs site on localhost.

**Comment by j4n-e4t** [comment]
Thank you. I've tried that in GitHub Codespaces. It may be the config of this specific cloud instance. I'll try on my local machine this evening.
