### ISSUE TITLE
Can not delete users

### ISSUE THREAD

**Issue by silverwolfdoc** [supabase/supabase#1948]
# Bug report
Can not delete users

## Describe the bug
calling 
```
supabase.auth.api.deleteUser(id, SUPABASE_SERVICE_KEY) 
```
on the sever side returns an error with
```
{ message: 'Database error deleting user', status: 500 }
```
## System information

- OS: [Windows]
- Browser  [chrome]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 16.2.0]

**Comment by silverwolfdoc** [comment]
Resolved, had to remove all other rows linked with the user in foreign tables before deleting the user

**Comment by cwooldridge1** [comment]
This is kinda annoying. If I have delete on cansade I should not have to first delete all the users stuff, deleting the user should delete all the stuff. Maybe theres something more technical im not getting...

**Comment by snettah** [comment]
> This is kinda annoying. If I have delete on cansade I should not have to first delete all the users stuff, deleting the user should delete all the stuff. Maybe theres something more technical im not getting...

From the ui it work like that, I don't know why we can't du the same thing from the sdk
