### ISSUE TITLE
Inconsistent recommendations around adding filters and RLS

### ISSUE THREAD

**Issue by timobehrens** [supabase/supabase#19506]
# Improve documentation

## Link 
https://supabase.com/docs/guides/auth/managing-user-data#private-access
Here it says
>The nice thing about this pattern? We can now query this table via the API and we don't need to include data filters in our API queries - the Policies will handle that for us:

https://supabase.com/docs/guides/database/postgres/row-level-security#add-filters-to-every-query
While here you recommend
>Policies are "implicit where clauses", so it's common to run select statements without any filters. This is a bad pattern for performance. Instead of doing this (JS client example):

## Describe the problem
The docs should be consistent with proposed best practices and not encourage new users to use RLS policies as data filters.

## Describe the improvement
Don't suggest we don't need to include data filters when we have RLS policies.

**Comment by charislam** [comment]
fair point about the inconsistency, I've made a PR to address it

**Comment by timobehrens** [comment]
> hmmm but if the data you're querying is designed to be read by only the user that 'owns' it, then isn't this completely valid?

Yes it seems to work, but performance can be vastly improved apparently. (I'm not an expert, just quoting the docs about best practices):

<img width="844" alt="image" src="https://github.com/supabase/supabase/assets/15941188/420f7d5f-6886-4dc3-ad6d-edd3dceed6bc">
