### ISSUE TITLE
Unable to use array column of type `text`

### ISSUE THREAD

**Issue by liaujianjie** [supabase/supabase#1952]
# Bug report

## Describe the bug

Unable to use array column of type `text`. I can neither:
1. create a new array column of type `text`, nor
2. update an existing column to an array column of type `text.

### Adding new array column of type `text`

1. Create a new column
2. Select type `text`
3. Check "Define as array"
4. Save
5. Refresh the page
6. Observe that the column is not defined as an array

### Updating existing column to array column of type `text`

1. Edit existing column
2. Select type `text`
3. Check "Define as array"
4. Save
5. Refresh the page
6. Observe that the column is not defined as an array

## Expected behavior

Column should be defined as an array. (or `string[]`).

### Adding new array column of type `text`

https://user-images.githubusercontent.com/3143132/121801850-238e6180-cc6c-11eb-8101-91d360b94e8b.mp4

### Updating existing column to array column of type `text`

https://user-images.githubusercontent.com/3143132/121801922-67816680-cc6c-11eb-959e-d01f90f9a524.mp4

### Seems like checking the "Define as array" option isn't firing the `PATCH` request as expected

https://user-images.githubusercontent.com/3143132/121802039-17ef6a80-cc6d-11eb-912f-208eed5935b0.mp4

## Temporary workaround

Manually alter column to type `text[]`:

```sql
alter table cool_beans alter column tags type text[];
```

**Comment by awalias** [comment]
thanks a lot @liaujianjie ! adding the videos like this is a huge help! will see what we can do 👍

**Comment by joshenlim** [comment]
hey there @liaujianjie! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
