### ISSUE TITLE
Application error when changing default permissions of functions

### ISSUE THREAD

**Issue by akarshghale** [supabase/supabase#19546]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When trying to change default database function permissions from the SQL Editor in locally hosted supabase studio I am getting this error when I run this command: `alter default privileges in schema public revoke all on functions to  anon, authenticated; `

Error: `Application error: a client-side exception has occurred (see the browser console for more information).`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
In locally hosted environment (Docker on OrbStack)

1. Go to SQL Editor
2. Click on New query
3. Add the command: `alter default privileges in schema public revoke all on functions to  anon, authenticated; `

## Expected behavior

It should return either success or failure in the SQL Editor instead of crashing!

## Screenshots

<img width="1462" alt="Screenshot 2023-12-09 at 1 03 09 AM" src="https://github.com/supabase/supabase/assets/7480878/3b817632-16b9-428a-9035-efb9a8b91ae5">

## System information

- MacOS M2 8GB
- Chrome Browser 
- Running locally (OrbStack)

## Additional context

When I click back on the browser I can access the studio back but when I click on Untitled Query where the SQL was used it throws the error again.
<img width="1462" alt="Screenshot 2023-12-09 at 1 05 13 AM" src="https://github.com/supabase/supabase/assets/7480878/1fd507ae-eaa4-4ec2-bf6e-dc2077bc5c9b">

**Comment by saltcod** [comment]
This should be fixed — could you try updating your local instance?

**Comment by akarshghale** [comment]
> This should be fixed — could you try updating your local instance?

Updated and tried but still causing issues

**Comment by botxboom** [comment]
Hi @akarshghale , as checked, this issue seems to be fixed. I am not getting this error.

**Comment by akarshghale** [comment]
> Hi @akarshghale , as checked, this issue seems to be fixed. I am not getting this error.

I updated the supabase CLI and then ran "supabase start"

Is this the correct way?

I might be updating it the wrong way.

**Comment by leerobert** [comment]
I'm still getting editor errors as of `1.123.4`

**Comment by encima** [comment]
This should be fixed (tested from `v1.31.0`) so I will close for now. Please comment if this is still occurring and we will re-open. If it does persist, be sure to clear any temporary images after upgrading the CLI
