### ISSUE TITLE
Unscrollable vertical sidebar on my laptop

### ISSUE THREAD

**Issue by panchalbhavya2210** [supabase/supabase#19567]
- [✔️] I confirm this is a bug with Supabase, not with my own application. 
- [✔️] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
the sidebar doesn't seem to scroll on my screen.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to supabase/dashboard
2. Scroll down on sidebar
3. See error

## Expected behavior

sidebar doesn't scroll down that's it.

## Screenshots
<img width="257" alt="Screenshot 2023-12-10 120810" src="https://github.com/supabase/supabase/assets/94476517/a3b7a5bb-6066-4c1f-99cb-01bac0b5ddbb">

## System information

- OS: Windows
- Browser Vivaldi browser(chromium based)
- Version of supabase-js: doesn't relate
- Version of Node.js: doesn't relate

**Comment by ZainAli104** [comment]
Is this issue solved or I can do this?

**Comment by panchalbhavya2210** [comment]
no it's not yet solved , i tried to do it myself but for some reason i can't you can go ahead and try it.
