### ISSUE TITLE
Create a Supabase Component Library

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#196]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

[Component Libraries](https://sunscrapers.com/blog/when-to-use-a-ui-component-library-in-a-react-project/) give products a consistent look & feel, and give developers a quick way to build. While there are some great component libraries out there (like Ant Design and Bootstrap), we decided from the start that we wanted to use [Tailwind](https://tailwindcss.com/) because we needed something versatile and with good performance. 

Right now we just implement components from scratch, without much consistency. It would be even better if we created a Component Library using something like [Storybook](https://storybook.js.org/) or just a Figma board.

## Additional Context

- We use React
- We only have a basic design system (https://github.com/supabase/supabase/issues/195), which means that the library should be flexible
- This is a big task! Not for the feint of heart

**Comment by MildTomato** [comment]
https://bit.dev/
Might be useful if wanting to reuse components across different projects - I was meaning to check this out myself.

**Comment by kiwicopple** [comment]
This looks cool, but the per-user pricing might make it hard for us to make it available to the whole community :(

Have you used any other tools @MildTomato ? Maybe storybook?

**Comment by mikqi** [comment]
hello @kiwicopple I have experience before using Storybook with react or vue. Maybe I can help you with integrate with Storybook + React.

**Comment by kiwicopple** [comment]
That would be awesome @mikqi - is there some very small feature-set that we can get started with, just to play around and see how we can integrate it into our website?

**Comment by thorwebdev** [comment]
Creating a signup/login widget component could be a good way to seed this library as it includes input fields, buttons, spinners, etc. It will be useful for app.supabase.io but also for the community.

**Comment by mikqi** [comment]
noted. maybe first iterate I will integrate supabase/web with storybook and sample component that we can play around. so the others can help with components.

**Comment by mikqi** [comment]
Little bit confuse about project structure repo. The end goal of this issue is to create component library that use tailwindcss, am I right? And then the web folder is documentation folder.

Do we need another folder or make this project as monorepo so we can easily when we need to publish the component library to npm registry.

**Comment by kiwicopple** [comment]
> Do we need another folder or make this project as monorepo so we can easily when we need to publish the component library to npm registry.

Yes, this is a good approach. This is already becoming a bit of a monorepo, so it makes sense to put it here as a subfolder - perhaps `supabase-ui`?

> The end goal of this issue is to create component library that use tailwindcss, am I right? 

Correct - we use tailwind everywhere, so this would be ideal. This is a fairly open task, so feel free to do it however you want and we can start iterating. Ideally this component library can be used in all the `/examples`, so Thor's suggestion of a 
signup/login widget component is a great idea (almost all of them will need auth)

**Comment by mikqi** [comment]
Oke noted @kiwicopple 👍

**Comment by mikqi** [comment]
hi @kiwicopple, I've just added form components and improvement for the button component. Maybe next I will add more components that supabase use on the web. Any request?

**Comment by kiwicopple** [comment]
Hey @mikqi - I saw all your PR's they are awesome. Thank you. 

> Maybe next I will add more components that supabase use on the web. Any request?

Icons are always useful, if they are easy to do in storybook? We are currently using [Feather Icons](https://feathericons.com/) on our website

**Comment by mikqi** [comment]
You can check it here https://github.com/supabase/supabase/pull/266 @kiwicopple 
I've added integration with react-feather from Feather Icons.

**Comment by kiwicopple** [comment]
That's awesome, thanks @mikqi !

**Comment by kiwicopple** [comment]
@mikqi you've done amazing work here. @MildTomato is going to start adding some new components for our dashbaord, starting with modals. 

Let us know if you would like to continue contributing - we can add a few ideas/issues. The work you did gives us an amazing head start, and I hope you received enough PR's for Hacktoberfest prizes. 

Also it looks like you're in Jakarta, so hi from SEA 👋 🇸🇬 . Drop me an email some time if you want to catch up
