### ISSUE TITLE
Error: Browser not detected

### ISSUE THREAD

**Issue by SuecoMarcus** [supabase/supabase#1962]
# Bug report

## Describe the bug

Hi! I'm trying to upload a file (image) to Supabase storage from an **Express** application but I'm getting the following error:
`Error: Browser not detected`

If I use the same code from a front-end application (form a browser), it works fine and the file gets uploaded.

## To Reproduce

1. Create a public bucket called "files".
2. Create an INSERT policy for that bucket.
```
(
  (bucket_id = 'files':: text)
  AND (role() = 'service_role':: text)
)
```

3. In the Express application I have the following code:
```
const { createClient } = require("@supabase/supabase-js");

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

const { data, error } = await supabase.storage
  .from("files")
  .upload("randomName.png", image);

```
where `image` is a `File` object.

4. I get `Error: Browser not detected` in the Node console.

## Expected behavior

The file (image) should be uploaded to Supabase.

## System information

- OS: macOS.
- Browser: Does not apply.
- Version of supabase-js: 1.14.0.
- Version of Node.js: 14.15.5.

---

Thanks in advance!

**Comment by inian** [comment]
Hi @SuecoMarcus we are working on this issue here https://github.com/supabase/storage-js/issues/5 Any help appreciated!
