### ISSUE TITLE
Supabase OAuth Session Object Showing Previous Provider While Working With OAuth 

### ISSUE THREAD

**Issue by AnasSiddiqui18** [supabase/supabase#19648]
I am working with React Vite and using Supabase for OAuth. Initially when the user enter's in the application and when he log's in with the OAuth for example with Github so after login successfully the session object contains Github in the provider because we are logging with Github and when the user logs out and now when the user logs in with another OAuth provider for example with Google so after login in the session object we are getting the previous provider name i dont know how to solve it. 

![code](https://github.com/supabase/supabase/assets/111227461/012e5257-e088-4b88-bc8d-c214ac70e74f)

**Comment by ayussh-cod** [comment]
hi can you check if you have cleared cache after logging out like anything on local storeage.

**Comment by encima** [comment]
Hi @AnasSiddiqui18 
Is this still occurring for you? Can you provide the package versions you are using and a minimal example to reproduce (I am not able to reproduce using the latest version).

**Comment by AnasSiddiqui18** [comment]
Hi, I notice that this is the default behavior like if you login with an account using gmail provider so when you use the same account for the email login so you encounter this behavior. This is a default behavior in any auth application. By the way thanks for your comment 💐
