### ISSUE TITLE
Database function example `hello_world` does not work anymore

### ISSUE THREAD

**Issue by JunsikChoi** [supabase/supabase#19683]
# Bug report

- [v] I confirm this is a bug with Supabase, not with my own application. 
- [v] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The basic example `hello_world` from supabase doc (https://supabase.com/docs/guides/database/functions) does not work.

## To Reproduce

1. from SQL editor in supabase dashboard, define same function from docs.
```
create or replace function hello_world() -- 1
returns text -- 2
language sql -- 3
as $$  -- 4
  select 'hello world';  -- 5
$$; --6
```
2. Execute function in SQL editor
3. Error occurs with the message below
```
ERROR:  42601: query has no destination for result data
HINT:  If you want to discard the results of a SELECT, use PERFORM instead.
CONTEXT:  PL/pgSQL function hello_world() line 3 at SQL statement
```

## Screenshots

![image](https://github.com/supabase/supabase/assets/16640149/9cb45c3f-d431-4228-90a2-6d9cdf264177)

## Additional context

This is resolved by using `return`, not `select` in the function.
So, I assume that maybe the docs should be updated?
Or did I do something wrong during the above procedure?

```
create or replace function hello_world()
returns text
language plpgsql
security definer set search_path = public
as $$
begin
  return 'hello world';
end;
$$;

```

**Comment by GaryAustin1** [comment]
I just copied your first lines for the SQL version of the function and ran those, then ran select hello_world() and it returned hello_world.

Your error message though implies you somehow changed SQL language to plpgsql language.
