### ISSUE TITLE
Is there a way to upload files by RESTful API?

### ISSUE THREAD

**Issue by leadream** [supabase/supabase#1973]
I'd like to upload files by API because it'll reduce code size, but I haven't found it in docs. Is there a way to implement it?

**Comment by inian** [comment]
Hi @leadream, check [this out](https://github.com/supabase/supabase/discussions/1002#discussioncomment-560098). The API docs [here](https://supabase.github.io/storage-api/#/)

**Comment by leadream** [comment]
Thanks @inian, that's helpful.
