### ISSUE TITLE
Signup with credentiasl/github providers fails

### ISSUE THREAD

**Issue by gubatenkov** [supabase/supabase#19753]
# Bug report

- Docs: https://docs.supabase.com
- Discussions: https://github.com/supabase/supabase/discussions
- Discord: https://discord.supabase.com

Before opening a bug report, please verify the following: 

-->

-  I confirm this is a bug with Supabase, not with my own application. Server responses are 500-codes.
-  I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Internal problems with auth.

## To Reproduce

Try to login via Credentials or Github provider in latest Chrome on MacOS Sonoma 14.1.2 to receive app state described on the screenshots below.

## Expected behavior

Success auth.

## Screenshots

<img width="1512" alt="Screenshot 2023-12-14 at 22 35 02" src="https://github.com/supabase/supabase/assets/58951553/465a3544-c58e-4835-93f9-fecd7bbd90d6">
<img width="1512" alt="Screenshot 2023-12-14 at 22 34 54" src="https://github.com/supabase/supabase/assets/58951553/3a8f1667-f061-4bc9-9f7d-5a8123b513e7">
<img width="1512" alt="Screenshot 2023-12-14 at 22 34 23" src="https://github.com/supabase/supabase/assets/58951553/4228946e-1863-468e-a584-0d7be78349b5">

## System information

- OS: [MacOS Sonoma 14.1.2]
- Browser [Chrome latest]

**Comment by Nicolasvegam** [comment]
same happened to me right now :/

**Comment by saltcod** [comment]
Hi there — sorry, you're saying you're unable to login via Github to supabase.com/dashboard? 
Is this still happening? We've no known outages happening at the moment.

**Comment by gubatenkov** [comment]
> Hi there — sorry, you're saying you're unable to login via Github to supabase.com/dashboard? Is this still happening? We've no known outages happening at the moment.

Сan't reproduce the problem under the same conditions. Can we close the issue ?
