### ISSUE TITLE
Enhancement - Docs Homepage Sidenav Scrolllbar 

### ISSUE THREAD

**Issue by Prasad-Katkade** [supabase/supabase#19768]
# Chore
Updated the sidenav scrollbar from default to custom styling for more engagging feel.

## Describe the chore
The default side navigation scrollbar on the [Supabase Documentation](https://supabase.com/docs) website may appear bulky and dull, especially when positioned at the center of the screen. To enhance the user experience, I have implemented a refined styling for the scrollbar, **ensuring compatibility with both dark and light themes and optimizing it for mobile responsiveness.**

- **Sleek Design:** A stylish scrollbar that seamlessly integrates with both dark and light themes.
  
- **Focused Emphasis:** Highlights "Supabase Documentation" word for a more engaging look.

- **Clear Distinction:** Provides a clean separation between main content and side navigation for improved readability.

## Screenshots
![Screenshot 2023-12-13 172701](https://github.com/supabase/supabase/assets/41871409/f9541295-4f9a-4e6a-9a25-77fe00992fe3)
![Screenshot 2023-12-13 172908](https://github.com/supabase/supabase/assets/41871409/ed323f2d-27d2-4570-b833-dcc0aa5a44cc)

**Comment by Prasad-Katkade** [comment]
I have updated the code to add `custom-scrollbar` class inside `apps/docs/layouts/SiteLayout.tsx`. Please suggest if anyone has any suggestions [Twitter](https://twitter.com/_prasadd_/status/1734940803133313435). Happy to contribute !

**Comment by Prasad-Katkade** [comment]
@saltcod can you please advice ?

**Comment by fsansalvadore** [comment]
@Prasad-Katkade thanks for the suggestion.

We're actually tending towards a cleaner look and feel, and a green scrollbar in the middle feels too dominant. It probably would distract the user.

We're open to improving the scrollbar experience, but if we do it in one place we would need to propagate that look and feel to all other scrollbars.

Could you try an alternative with a transparent scrollbar track and a more subtle scrollbar, such as `text-foreground-muted` or `border-strong`?

**Comment by Prasad-Katkade** [comment]
@fsansalvadore, thanks, I'll try that.

Although I've experimented with a transparent option, meaning only a thin green line, it didn't look nice. I mean, the scrollbar track acts as a distinguisher between main content and the sidenav.

I added the green color to match our theme. If you look at the above images, it nicely complements the 'Supabase Docs' word in the sidenav and the 'Supabase Documentation' heading on the main page (the larger one). But if you have any other shade for the scrollbar thumb please suggest !

**Comment by MildTomato** [comment]
Hey @Prasad-Katkade - thanks for the suggestion (and contribution!).

I think for this one we'd rather not implement a custom scroll bar. Although I've tried to outline what I'm thinking about below as I imagine that isn't what you (or others) want to hear.

They're a bit of a controversial subject (If anyone is interested, here's a [big debate on HN](https://news.ycombinator.com/item?id=36302002)) since by implementing a custom scroll bar it takes away some of the a11y control of the browser (or the user I suppose).

There's also a decision on what kind of behavior it should inherit. For example, wether it should be 'on hover'. The codesandbox example below works quite well since it requires the user to hover in the scroll area to see the scroll bar. But then we also need to check wether this works well on touch devices / cross browsers and so on.

<img width="220" alt="Screenshot 2023-12-19 at 11 03 48 PM" src="https://github.com/supabase/supabase/assets/8291514/9288b8ee-476d-419e-b914-8de9b444c5d2">

For some balance, there are plenty of websites that don't bother with this, and are fine with native browser scroll bars.

<img width="220" alt="Screenshot 2023-12-19 at 11 03 36 PM" src="https://github.com/supabase/supabase/assets/8291514/7b15c05a-a1ed-4c42-95ff-c4687d3e33dd">

There's probably some good reasons to maybe implement custom scroll bars, like on situations you need to reliably always see the state of the scroll; like a code editor or a spreadsheet. But even those examples are subjective, and perhaps some users like or dislike that.

For this use case, I'm not sure it's worth the effort of implementing and testing across a bunch of browsers and touch devices for what is probably a fairly low return on investment, especially since native scroll bars for sidebar menus are not amazing, but also not terrible.

**Comment by MildTomato** [comment]
Also worth echoing what @fsansalvadore - We have a visual principle the designers at Supabase follow in which we are starting to use more neutral colors, especially for things like this. 
For that alone we'd have to reject the design change.

Probably worth using the colors @fsansalvadore mentioned (or something similar) if you want us to re-review the PR.

**Comment by Prasad-Katkade** [comment]
Hey @MildTomato ,

Firstly, thanks for such detailed insights. However, I want to clarify that I am not a professional designer. From what I gathered after reading an [accessibility](https://developer.mozilla.org/en-US/docs/Web/Accessibility) (a11y) article, the goal is to make the web accessible to everyone on all devices.

In the case of this PR, I didn't tamper with the scroll functionality; I simply updated the colors of the scroll and its width. I'm not sure how this would impact accessibility.

My primary motivation for making this change was that t**he default scroll in the middle of the screen of a home page felt a little weird to me.** I experimented with colors locally for customization. I've also tested it with both dark and light themes on three different browsers:

1] Chrome (on desktop and mobile)
2] Firefox (on desktop)
3] Microsoft Edge (on desktop)

I made these changes out of curiosity and a desire to learn and explore. I'll definitely try the colors suggested by @fsansalvadore 
as well.

**Comment by MildTomato** [comment]
> In the case of this PR, I didn't tamper with the scroll functionality; I simply updated the colors of the scroll and its width. I'm not sure how this would impact accessibility.

It's one of the oddities of setting the properties of `::-webkit-scrollbar`, it changes it's behavior. You can see in your preview that now the scroll bar is always active when the content overflows; which is not the normal behavior for most browser scroll bars - so you have, even if not deliberately, changed the scroll functionality.

Worth pointing out like [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) does, `::-webkit-scrollbar` is not really a standard accepted by all browsers. Scroll bars are definitely one of the most oddest things in browsers :)

**Comment by MildTomato** [comment]
@Prasad-Katkade What browser are you using here? And what operating system?

![image](https://github.com/supabase/supabase/assets/8291514/601f1371-fca4-4071-b048-6428bb6ee82a)

**Comment by Prasad-Katkade** [comment]
@MildTomato I am using windows and chrome

**Comment by MildTomato** [comment]
@Prasad-Katkade I take it when you enlarge the browser window (or zoom out) your scroll bar disappears ?

**Comment by Prasad-Katkade** [comment]
@MildTomato I tested with your suggestion to zoom-out and the scorllbar disappers, similar behavior happens on prod site as well 

1] Local dev -
![image](https://github.com/supabase/supabase/assets/41871409/92fb6972-7b46-49e7-b7d0-06d4bd3aff33)

2] Prod supabase/docs
![image](https://github.com/supabase/supabase/assets/41871409/93b61c3c-ba0d-4a50-80f2-d76080fe0717)

**Comment by MildTomato** [comment]
>The ::-webkit-scrollbar CSS pseudo-element is primarily designed for styling the appearance of scrollbars and does not directly control the default functionality or behavior of scrollbars.

this doesn't seem accurate, see video attached.

https://github.com/supabase/supabase/assets/8291514/05911785-3a43-4379-8969-aaade37ae090

I think the team here are comfortable with the system scroll bar defaults for now.
There's also some drawbacks with using custom colors like the scroll area and scroll thumb can't use any background opacity so we won't be able to implement the scroll bars how we would like without using some sort of scroll bar npm package (can't remember the name of the one used in react-grid), but it's not really worth it for this use case really.

**Comment by Prasad-Katkade** [comment]
@MildTomato Really appreciate you taking the time to analyze things. Definitely learned a lot about scrollbars here, and now I totally agree with your statement that scrollbars are weird. 😃🙌

**Comment by Prasad-Katkade** [comment]
Hey @MildTomato , I'm asking out of curiosity: what matters more, (in overall design scenario) having a consistent design across all platforms and operating systems, or having different designs tailored to each platform?

I introduced a change that keeps the scrollbar active (consistent) across all platforms. However, based on the video you provided, on Mac (Safari), it appears on scroll/hover, and on Windows (Chrome), it's based on the size.

I would really appreciate your opinion on this.

**Comment by MildTomato** [comment]
> Hey @MildTomato , I'm asking out of curiosity: what matters more, (in overall design scenario) having a consistent design across all platforms and operating systems, or having different designs tailored to each platform?

I think in this case it makes sense to rely on browser native default. 

> I introduced a change that keeps the scrollbar active (consistent) across all platforms. However, based on the video you provided, on Mac (Safari), it appears on scroll/hover, and on Windows (Chrome), it's based on the size.

Same as above, let's just keep the native scroll bars. I think our point here is that we respect the browser native behaviour. 

I'm going to close out this issue now as I think we've concluded internally to not use custom scroll bars for this.
