### ISSUE TITLE
Supabase ui is down

### ISSUE THREAD

**Issue by Nicolasvegam** [supabase/supabase#19788]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

All our team can't access to the supabase ui

<img width="1393" alt="image" src="https://github.com/supabase/supabase/assets/26209122/a8bfe87d-d131-4e35-ad2c-496b9b686bd6">
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to supabase.com/dashboard/projects'

**Comment by saltcod** [comment]
Hi there — please submit a support ticket (Help in the top right) if you're still experiencing issues. We've got no known issues happening at the moment.
