### ISSUE TITLE
Community Chat

### ISSUE THREAD

**Issue by rishavs** [supabase/supabase#198]
Does Supabase have any community chat server like Discord/Gitter/Slack etc?
Essentially a place where we can talk about the project and can have a real time discourse among the users?

**Comment by kiwicopple** [comment]
We're patiently waiting for GitHub to give us access to [GitHub discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)..

We plan to center everything around our GitHub org. However, if you're already building a project with Supabase let us know and we can do a Shared Org on slack, or invite you into our internal slack as a guest

**Comment by rishavs** [comment]
Thanks. Closing this item then. Right now I am just playing with hello world projects. If I feel I need more help and would need to get into the slack, i will drop a separate ping.

**Comment by kiwicopple** [comment]
Nice one, thanks @rishavs . Let us know if you build anything cool - we'll release a showcase soon

**Comment by thorwebdev** [comment]
Quick note that we now have launched the community discussions forum: https://github.com/supabase/supabase/discussions

**Comment by zzterrozz** [comment]
> Quick note that we now have launched the community discussions forum: https://github.com/supabase/supabase/discussions

We still need a real chat! It is important, especially during a beta period.
As users, we really need this easy talks to support the risk we are taking with a new born technology

**Comment by rishavs** [comment]
+1. Having a real time chat is very important for a community to spring around nowadays and should not take more than a few minutes to set it up.

Discussions and forums are important but they simply do not work as well s a community chat as far as getting quick help goes.

**Comment by roryw10** [comment]
Hi @rishavs @zzterrozz  

We do have a community slack channel, at the moment it's invitation only and we would be more than happy to hook you up with an invitation. 

If you can drop me a note at rory@supabase.io with the email address you would like me to use i will sort out an invitation for you ASAP. Also let me know if you want some Supabase stickers and we can get the swag team to send some out your way :)

**Comment by zzterrozz** [comment]
> Hi @rishavs @zzterrozz
> 
> We do have a community slack channel, at the moment it's invitation only and we would be more than happy to hook you up with an invitation.
> 
> If you can drop me a note at [rory@supabase.io](mailto:rory@supabase.io) with the email address you would like me to use i will sort out an invitation for you ASAP. Also let me know if you want some Supabase stickers and we can get the swag team to send some out your way :)

Email sent! Thank you @roryw10

**Comment by roryw10** [comment]
Folks, the slack channel is no longer active and has been archived as we are now using discord. 

You can find us at discord.supabase.com and get involved from there :)

**Comment by Iccr** [comment]
is there any invitation link for discord? the ones I found in twitter are all expired.

**Comment by Isaiah-Hamilton** [comment]
@Iccr here is the discord invite link [discord.supabase.com](https://discord.supabase.com).
