### ISSUE TITLE
CORS enabled Edge function example from the Supabase docs throwing error when invoked

### ISSUE THREAD

**Issue by PaulMacinic** [supabase/supabase#19815]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Since a couple of days we are getting a CORS error when invoking an Edge function. Worked before. 

Invoking the function from the app sometimes works, but sometimes it throws a CORS error, even though it then returns the data. 

I created a new empty Supabase project following the Supabase docs and can confirm the issue persists even with the code from the docs.

## To Reproduce

1. create an empty app following the Vite + React quick start [guide](https://supabase.com/docs/guides/getting-started/quickstarts/reactjs).
2. create a hello-world Edge function and use the code in the CORS [guide](https://supabase.com/docs/guides/functions/cors).
3. deploy the function using the Supabase [CLI](https://supabase.com/docs/guides/functions/deploy).
4. refresh the main page of the React app a couple of times until the error is thrown.

Please see:
[Link](https://github.com/PaulMacinic/supabase-demo-cors) to repo containg the code causing the error.
[Link](https://supabase-demo-cors.vercel.app/) to a Vercel deployed version of the code in the repo reproducing the error.

## Expected behavior
The function should be invoked and return the data without throwing a CORS error.

## Screenshots
<img width="1920" alt="Screenshot 2023-12-17 at 00 56 15" src="https://github.com/supabase/supabase/assets/11924116/6272aa18-066f-4f8a-943b-1cf62cbc413a">
<img width="1917" alt="Screenshot 2023-12-17 at 00 54 13" src="https://github.com/supabase/supabase/assets/11924116/a8e8740f-5086-41f0-a508-1735d4496478">
<img width="1908" alt="Screenshot 2023-12-17 at 00 51 13" src="https://github.com/supabase/supabase/assets/11924116/0693f2e4-a86b-4c48-9d0c-c9dd1e6643b9">

## System information

- OS: macOS 13.5.2 
- Browser: Chrome 120.0.6099.109 on macOS
- Version of supabase-js: 2.39.0
- Version of Node.js: 20.10.0

**Comment by haschu** [comment]
We're experiencing the exact same error (and as well some folks on the discord server).

The problem is, that edge function executions are broken and throwing frequent 500 responses. So it's not a CORS issue but worse...
