### ISSUE TITLE
Table UI reports total policies for all tables instead of for 1 table.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#19887]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the table UI with a table with RLS enable shows a wildly inaccurate total of RLS policies.  The number seems to be the total of all policies and is the same no matter which RLS enabled table you picked.

The policy views work fine though.

![image](https://github.com/supabase/supabase/assets/54564956/d0c124b2-5520-4520-b0a0-f13e976a9f70)

Multiple users are reporting this.

## To Reproduce

Have multiple tables with RLS enabled and policies.
Go to Table UI.

## Expected behavior

Report policies on table.

## Screenshots
See above

## System information
Latest Dashboard

**Comment by Hallidayo** [comment]
Hi @GaryAustin1 - Are you still having the above? My dashboard seems to be okay now.

**Comment by GaryAustin1** [comment]
Looks good now.
