### ISSUE TITLE
When using Supabase Auth, how do you relate to other tables using Drizzle?

### ISSUE THREAD

**Issue by HassanDev13** [supabase/supabase#19883]
# Improve documentation

https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-drizzle

## Describe the problem

When using Supabase Auth, how do you relate to other tables using Drizzle?

**Comment by encima** [comment]
Hi @HassanDev13 ,

does the documentation on [Drizzle's site](https://orm.drizzle.team/docs/joins) cover this? What additional information would you like to see?

**Comment by HassanDev13** [comment]
No they not. 

we solve this problem by using a trigger function so you may start from here, don't know if it best practice but it works well 👌

Tell me if you need more details information.

**Comment by encima** [comment]
@HassanDev13 More information would be good. What is the schema you have? What are you trying to achieve and what is the current approach you are using?

**Comment by encima** [comment]
Closing the issue due to it being inactive and/or outdated.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen it.
Cheers!

**Comment by andresmarpz** [comment]
Would love more examples/docs on this, using Supabase Auth with other ORMs in general 👍🏼

**Comment by creadevv** [comment]
> Would love more examples/docs on this, using Supabase Auth with other ORMs in general 👍🏼

+1.

Using Supabase + Drizzle and Supabase auth, but my app has a lot of custom user data. So i need a drizzle schema to reference the auth.users table somehow..

**Comment by prodkt** [comment]
+1, not finding a solution to reference the auth schema users table columns within drizzle table column references.

**Comment by ironbyte** [comment]
Why not using drizzle kit's introspection tool to pull up both the public (yours) and Supabase auth schemas?

**Comment by DomNidy** [comment]
> @creadevv
> 
> Why not using drizzle kit's introspect tool to pull up both the public (yours) and Supabase auth schemas?
> 
> https://orm.drizzle.team/kit-docs/overview#introspecting-with-db-pull
> 
> https://orm.drizzle.team/kit-docs/commands#introspect--pull

That method almost works, but you need to do some manual work as there is an issue with how drizzle generates the schema.

(For anyone reading this: you would want to run the `drizzle-kit introspect:pg` command, just make sure to configure `drizzle.config.ts` first)

The schema it will generate for supabases `auth.users` table has syntax errors. (This is not just a problem with auth.users schema, there are other issues with other schemas).

Example of **some** of the syntax errors in question:
```typescript
phone: text("phone").default(NULL::character varying)
phoneChange: text("phone_change").default(''::character varying),
emailChangeTokenCurrent: varchar("email_change_token_current", { length: 255 }).default(''::character varying),
...
```
`NULL::character varying` as we know is not valid typescript / js syntax, and is sql. In order to manually fix these syntax errors you need to change those properties to the following:

```typescript
phone: text("phone").default(sql`NULL::character varying`),
phoneChange: text("phone_change").default(sql`''::character varying`),
emailChangeTokenCurrent: varchar("email_change_token_current", { length: 255 }).default(sql`''::character varying`),
```

Note the usage of the `sql` method from `drizzle-orm` library.

#### A few things to keep in mind:
1. Be careful when you try to push your schema, drizzle will warn you with the statements you are about to execute like:
```sql
"Warning  You are about to execute current statements:

ALTER TABLE "auth"."users" ALTER COLUMN "phone" SET DEFAULT NULL::character varying;"
```
Make sure to review this first.

**Comment by nianiam** [comment]
@DomNidy May I suggest the [tables filter](https://orm.drizzle.team/kit-docs/config-reference#tablesfilters) to skip pushing those tables.

**Comment by keanan-meier** [comment]
If all you are looking for is a way to reference the auth tables for foreign key in your own schema this method seems to work:

For a quick example - extending the user table with a custom accounts table in the public schema:

**Schema (schema.ts):**
```
const authSchema = pgSchema('auth');

const users = authSchema.table('users', {
	id: uuid('id').primaryKey(),
});

export const accounts = pgTable('accounts', {
	id: serial('id').primaryKey(),
	fullName: text('full_name').notNull(),
	user_id: uuid('user_id').references(() => users.id).notNull()
});
```

**drizzle.config.ts:**
```
export default {
  schemaFilter: ["public"],
  //other config here
} satisfies Config;

```

This way you have the reference for your own tables to generate the proper foreign key relations and since you filter schemas it will only push your custom schemas (in this case public)

**Comment by Mriganka5137** [comment]
@keanan-meier CAN YOU SHARE ME THE CODE. I WANT TO REFERENCE AUTH.USERS TABLE FROM ANOTHER PUBLIC TABLE WITH DRIZZLE SCHEMA

**Comment by trevorpfiz** [comment]
> @keanan-meier CAN YOU SHARE ME THE CODE. I WANT TO REFERENCE AUTH.USERS TABLE FROM ANOTHER PUBLIC TABLE WITH DRIZZLE SCHEMA

he did share the code... you just use the accounts/profile table for relations with other tables.

`schema.ts`
```ts
const authSchema = pgSchema("auth");

export const Users = authSchema.table("users", {
  id: uuid("id").primaryKey(),
});

export const Profile = createTable("profile", {
  // Matches id from auth.users table in Supabase
  id: uuid("id")
    .primaryKey()
    .references(() => Users.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 256 }).notNull(),
  email: varchar("email", { length: 256 }),
});

export const Post = createTable("post", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: varchar("title", { length: 256 }).notNull(),
  content: text("content").notNull(),
  profileId: uuid("profile_id")
    .notNull()
    .references(() => Profile.id),
  createdAt: timestamp("created_at")
    .default(sql`now()`)
    .notNull(),
  updatedAt: timestamp("updatedAt", {
    mode: "date",
    withTimezone: true,
  }).$onUpdateFn(() => sql`now()`),
});

export const ReportRelations = relations(Post, ({ one }) => ({
  profile: one(Profile, {
    fields: [Post.profileId],
    references: [Profile.id],
  }),
}));
```

`drizzle.config.ts`
```ts
export default {
  schemaFilter: ["public"],
  //other config here
} satisfies Config;

```

**Comment by Mriganka5137** [comment]
Thank you

**Comment by kareulo-DEVGO-Studio** [comment]
> > @keanan-meier CAN YOU SHARE ME THE CODE. I WANT TO REFERENCE AUTH.USERS TABLE FROM ANOTHER PUBLIC TABLE WITH DRIZZLE SCHEMA
> 
> he did share the code... you just use the accounts/profile table for relations with other tables.
> 
> `schema.ts`
> ```ts
> const authSchema = pgSchema("auth");
> 
> export const Users = authSchema.table("users", {
>   id: uuid("id").primaryKey(),
> });
> 
> export const Profile = createTable("profile", {
>   // Matches id from auth.users table in Supabase
>   id: uuid("id")
>     .primaryKey()
>     .references(() => Users.id, { onDelete: "cascade" }),
>   name: varchar("name", { length: 256 }).notNull(),
>   email: varchar("email", { length: 256 }),
> });
> 
> export const Post = createTable("post", {
>   id: uuid("id").primaryKey().defaultRandom(),
>   title: varchar("title", { length: 256 }).notNull(),
>   content: text("content").notNull(),
>   profileId: uuid("profile_id")
>     .notNull()
>     .references(() => Profile.id),
>   createdAt: timestamp("created_at")
>     .default(sql`now()`)
>     .notNull(),
>   updatedAt: timestamp("updatedAt", {
>     mode: "date",
>     withTimezone: true,
>   }).$onUpdateFn(() => sql`now()`),
> });
> 
> export const PostRelations = relations(Post, ({ one }) => ({
>   profile: one(Profile, {
>     fields: [Post.profileId],
>     references: [Profile.id],
>   }),
> }));
> ```
> 
> `drizzle.config.ts`
> ```ts
> export default {
>   schemaFilter: ["public"],
>   //other config here
> } satisfies Config;
> 
> ```

Noob question but do I still need to do the database trigger `on_user_create` or something like that. Or, can I achieve the same functionality with drizzle?

**Comment by trevorpfiz** [comment]
@kareulo-DEVGO-Studio you are going to want to add this database trigger.

```sql
-- inserts a row into public.profile
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.t3turbo_profile (id, email, name, image)
  values (
    new.id,
    new.email,
    COALESCE(
      new.raw_user_meta_data ->> 'name',
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'user_name',
      '[redacted]'
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update set
    email = excluded.email,
    name = excluded.name,
    image = excluded.image;
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- trigger the function when a user signs in/their email is confirmed to get missing values if any
create trigger on_auth_user_verified
  after update on auth.users
  for each row when (
    old.last_sign_in_at is null
    and new.last_sign_in_at is not null
  ) execute procedure public.handle_new_user();
```

**Comment by EduartePaiva** [comment]
> If all you are looking for is a way to reference the auth tables for foreign key in your own schema this method seems to work:
> 
> For a quick example - extending the user table with a custom accounts table in the public schema:
> 
> **Schema (schema.ts):**
> 
> ```
> const authSchema = pgSchema('auth');
> 
> const users = authSchema.table('users', {
> 	id: uuid('id').primaryKey(),
> });
> 
> export const accounts = pgTable('accounts', {
> 	id: serial('id').primaryKey(),
> 	fullName: text('full_name').notNull(),
> 	user_id: uuid('user_id').references(() => users.id).notNull()
> });
> ```
> 
> **drizzle.config.ts:**
> 
> ```
> export default {
>   schemaFilter: ["public"],
>   //other config here
> } satisfies Config;
> ```
> 
> This way you have the reference for your own tables to generate the proper foreign key relations and since you filter schemas it will only push your custom schemas (in this case public)

That's such a nice and simple way to handle this. Thanks, saved my day.

**Comment by aleksa-codes** [comment]
> If all you are looking for is a way to reference the auth tables for foreign key in your own schema this method seems to work:
> 
> For a quick example - extending the user table with a custom accounts table in the public schema:
> 
> **Schema (schema.ts):**
> 
> ```
> const authSchema = pgSchema('auth');
> 
> const users = authSchema.table('users', {
> 	id: uuid('id').primaryKey(),
> });
> 
> export const accounts = pgTable('accounts', {
> 	id: serial('id').primaryKey(),
> 	fullName: text('full_name').notNull(),
> 	user_id: uuid('user_id').references(() => users.id).notNull()
> });
> ```
> 
> **drizzle.config.ts:**
> 
> ```
> export default {
>   schemaFilter: ["public"],
>   //other config here
> } satisfies Config;
> ```
> 
> This way you have the reference for your own tables to generate the proper foreign key relations and since you filter schemas it will only push your custom schemas (in this case public)

Could someone please explain to me what does this part do? As I tried the implementation without it and I don't see anything wrong changed in my db. I thought maybe without this the default auth schema would change?

```javascript
export default {
  schemaFilter: ["public"],
  //other config here
} satisfies Config;
```

**Comment by ImamJanjua** [comment]
Do i have to create the schema for auth and and related user table or will drizzle kit handle that?:  

const authSchema = pgSchema("auth");

export const Users = authSchema.table("users", {
  id: uuid("id").primaryKey(),
});

**Comment by trevorpfiz** [comment]
use `import { authUsers } from "drizzle-orm/supabase"` now

**Comment by AurelianSpodarec** [comment]
Wow, thank you soo much trevor. Why is this not in the docs :d

**Comment by weisisheng** [comment]
Provides a few more trailheads --> https://orm.drizzle.team/docs/rls

**Comment by ben-xD** [comment]
> use `import { authUsers } from "drizzle-orm/supabase"` now

How do you reference the id column from `authUsers`? 

```typescript
import { pgTable, serial, text, uuid } from "drizzle-orm/pg-core";
import { authUsers } from "drizzle-orm/supabase"
// import { users } from "./supabaseAuth";

export const food = pgTable("food", {
  id: serial('id').primaryKey(),
  userId: uuid().references(() => authUsers.id, { onDelete: "cascade" }),
  // Works if i use my own table
  // userId: uuid().references(() => users.id, { onDelete: "cascade" }),
  name: text('name').notNull(),
});
```

Error:
```
Property 'config' is protected but type 'Column<T, TRuntimeConfig, TTypeConfig>' is not a class derived from 'Column<T, TRuntimeConfig, TTypeConfig>'.ts(2322)
```

**Comment by AurelianSpodarec** [comment]
> > use `import { authUsers } from "drizzle-orm/supabase"` now
> 
> How do you reference the id column from `authUsers`?
> 
> import { pgTable, serial, text, uuid } from "drizzle-orm/pg-core";
> import { authUsers } from "drizzle-orm/supabase"
> // import { users } from "./supabaseAuth";
> 
> export const food = pgTable("food", {
>   id: serial('id').primaryKey(),
>   userId: uuid().references(() => authUsers.id, { onDelete: "cascade" }),
>   // Works if i use my own table
>   // userId: uuid().references(() => users.id, { onDelete: "cascade" }),
>   name: text('name').notNull(),
> });
> Error:
> 
> ```
> Property 'config' is protected but type 'Column<T, TRuntimeConfig, TTypeConfig>' is not a class derived from 'Column<T, TRuntimeConfig, TTypeConfig>'.ts(2322)
> ```
> 
> ## Temporary solution
> I just copied the code from https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-orm/src/supabase/rls.ts into my project.

Interesting, so this:
```js
const auth = pgSchema('auth');

export const authUsers = auth.table('users', {
	id: uuid().primaryKey().notNull(),
	email: varchar({ length: 255 }),
	phone: text().unique(),
	emailConfirmedAt: timestamp('email_confirmed_at', { withTimezone: true }),
	phoneConfirmedAt: timestamp('phone_confirmed_at', { withTimezone: true }),
	lastSignInAt: timestamp('last_sign_in_at', { withTimezone: true }),
	createdAt: timestamp('created_at', { withTimezone: true }),
	updatedAt: timestamp('updated_at', { withTimezone: true }),
});
```
Works?

I was thinking how we can use drizzle methods on the auth table without using raw SQL - guess this will do it. Will try. Thanks for the suggestion. Well see if it works - maybe not today tho, doing the UI for my app :D

**Comment by RobRoseKnows** [comment]
> > use `import { authUsers } from "drizzle-orm/supabase"` now
> 
> How do you reference the id column from `authUsers`?
> 
> import { pgTable, serial, text, uuid } from "drizzle-orm/pg-core";
> import { authUsers } from "drizzle-orm/supabase"
> // import { users } from "./supabaseAuth";
> 
> export const food = pgTable("food", {
>   id: serial('id').primaryKey(),
>   userId: uuid().references(() => authUsers.id, { onDelete: "cascade" }),
>   // Works if i use my own table
>   // userId: uuid().references(() => users.id, { onDelete: "cascade" }),
>   name: text('name').notNull(),
> });
> Error:
> 
> ```
> Property 'config' is protected but type 'Column<T, TRuntimeConfig, TTypeConfig>' is not a class derived from 'Column<T, TRuntimeConfig, TTypeConfig>'.ts(2322)
> ```
> 
> ## Temporary solution
> I just copied the code from https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-orm/src/supabase/rls.ts into my project.

This error is I think just an eslint error that happens when you update a dep with the file open. Try restarting vscode.
