### ISSUE TITLE
supabase.com site not load , but when use VPN its load

### ISSUE THREAD

**Issue by Othman-Sami** [supabase/supabase#19893]
Hi 
thanks for your products in Supabase 
that help many developers to reach the level

I use supabase for 6 months 
Its all things ok 
but in couple days , the site not load 
When I use VPN its Work fine 

I'm afraid that our projects and account will be delete in future .
or middle east country will be band from servers of supabase

**Comment by encima** [comment]
Hi @Othman-Sami , some follow up questions:
- can you give more information about where you are accessing Supabase from (if possible)?
- is the issue consistent or can you sometimes access the site? 
- Have you filed an issue with your ISP?
- Which VPNs are you able to connect from?

Thanks for the additional info!

**Comment by Othman-Sami** [comment]
> Hi @Othman-Sami , some follow up questions:
> 
> * can you give more information about where you are accessing Supabase from (if possible)?
> * is the issue consistent or can you sometimes access the site?
> * Have you filed an issue with your ISP?
> * Which VPNs are you able to connect from?
> 
> Thanks for the additional info!

I live in iraq 
the issue is consisted

**Comment by brookbdt** [comment]
facing similar issue as well.

Accessing from Ethiopia
Issue is so consistent I would rather have VPN on at all times
Not field an issue with my ISP
I am able to connect through Nord, Cloudflare etc

**Comment by Hallidayo** [comment]
Hi all, does the site not load at all? Do you see any errors in the developer console in the browser?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by ohehelv** [comment]
same problem!
