### ISSUE TITLE
Saving SQL queries fails on self-hosted

### ISSUE THREAD

**Issue by yekta** [supabase/supabase#19935]
## Describe the bug

Saving SQL queries fails on Supabase self-hosted without much info. I couldn't find anything on why it fails, it just says "Failed to save". Is this the intended behaviour?

**Comment by Wafje** [comment]
I have the same issue.

**Comment by swabbass** [comment]
same issue

**Comment by yekta** [comment]
> Are you on the latest release @yekta and @Wafje ? This should be fixed.

Well error is gone, but it's still not working. There is no way to rename the query (the chevron that exists in the hosted version) and it's not persisted.

<img width="257" alt="Screenshot 2024-01-20 at 19 27 07" src="https://github.com/supabase/supabase/assets/40706601/bb0c9885-133e-434b-9617-df63c37bd9c0">

**Comment by saltcod** [comment]
Apologies all, I misread this issue initially. 
Snippets aren't saved with the project, so there's currently no way to save new snippets in a local or self-hosted environment. We need to fix the UI here to take this into account.

**Comment by saltcod** [comment]
Closing as a duplicate of https://github.com/supabase/supabase/issues/17941, which has more context.

**Comment by MoradFN** [comment]
I have the same issue.

**Comment by ishangirdhar** [comment]
I have the same issue. Any ETA if and when it will be fixed?

**Comment by Joonas12334** [comment]
Still an issue

**Comment by aantti** [comment]
Saving SQL snippets has been recently added to Studio for non-platform deployments, such as [local development & CLI](https://supabase.com/docs/guides/local-development) and [self-hosted Supabase](https://supabase.com/docs/guides/self-hosting). Check:

- https://github.com/supabase/supabase/issues/17941#issuecomment-3777707043
- https://github.com/supabase/supabase/blob/master/docker/CHANGELOG.md

You'll need to update Studio image and `docker-compose.yml`, though.
