### ISSUE TITLE
2024 | Lack of Essential Features in Supabase Open-Source Version: SSL and Multi-Project Management

### ISSUE THREAD

**Issue by miguelgargallo** [supabase/supabase#19949]
# Bug report

- [x] I love supabase but I feel disappointed ¿How I supose to use this "open source" project on production at home servers?
- [x] Supabase closed hundreds of times this kind of issues but never really solve it.
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs], well in fact does not include. (https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Introduction

My admiration for Supabase and its community is profound. This community, known for its dedication to creating guides and supporting features, has made Supabase more accessible and versatile. However, this approach raises concerns about the accessibility of key features to all users. Essential features should be natively supported in the core platform, ensuring an inclusive and user-friendly experience for everyone.

## The Concerning Trend

There's a worrying trend in treating Supabase as a ready-for-production open-source solution, based solely on the official guides. This approach is somewhat disingenuous and could be perceived as an insult to the community. Open-source projects should be transparent about their capabilities and limitations, especially in production environments.

## Unsound Practices

The deliberate exclusion of crucial features like domain SSL and multi-project management in the open-source version, pushing users towards the paid cloud variant, is an unsound practice. This contradicts the ethos of open-source software, which centers on inclusivity and community support.

## About Your Competitors: PocketBase

In contrast, PocketBase offers a streamlined approach to full-stack development, integrating backend and frontend functionalities seamlessly. Its open-source nature and clear, comprehensive documentation make it a valuable resource for developers.

## Bug Description

The open-source version of Supabase, as of 2024, lacks SSL support for domains and the ability to manage multiple projects effectively.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install the open-source version of Supabase.
2. Attempt to configure SSL for a domain.
3. Try to manage multiple projects within this setup.
4. Observe the absence of support for these features.

## Expected behavior

There should be built-in support for SSL in domains and efficient management of multiple projects in the open-source version of Supabase.

## Screenshots

Not applicable.

## System information

Any Docker deployment is relevant to this issue.

## Additional context

This limitation challenges the scalability and security of projects relying on the open-source version, raising questions about its feasibility for production environments.

**Comment by kiwicopple** [comment]
Hey @miguelgargallo - this is a great write up! 

> the ability to manage multiple projects effectively.

Supabase runs the exact same stack on our cloud that we offer for self-hosting. We spin up a server for every customer, just like I do here: https://www.youtube.com/watch?v=FqiQKRKsfZE

It should be trivial to use the images that we offer with your favourite orchestration engine: k8s, k3s, Terraform, Pulumi, Ansible ... you name it. 

Supabase is designed to be scalable. We've given you the simplest components that we can without reducing scalability. If self hosting the current stack is _not_ a trivial task for you, self-hosting might not be something you should consider, or you could choose something simpler. I agree, Pocketbase offers a great way to bundle everything into a single binary - this simply isn't possible with Postgres, PostgREST, GoTrue, Kong, and a Storage Engine.

> open-source version of Supabase, as of 2024, lacks SSL support

Kong supports SSL - I shared the solution with you on [twitter](https://x.com/kiwicopple/status/1733400765937377596?s=20) a couple of weeks ago. Did you try this?

> This community, known for its dedication to creating guides and supporting features, has made Supabase more accessible and versatile

I agree! We would love your help to contribute a guide for SSL with Kong. At the moment it's mostly [me](https://github.com/supabase/supabase/pull/16097) making these guides and I would really love more help with the guides

This is a great request, thanks for taking the time to write it up. If you have anything more specific that I can action feel free to open that in a trimmed-down issue which focuses specifically on a single issue. It's very hard to cover all the topics you've introduced here with a pull request but a discrete, actionable issue is always appreciated

**Comment by miguelgargallo** [comment]
Not true, here is my instance
![image](https://github.com/supabase/supabase/assets/5947268/c1d7694e-59c0-4d04-b7ab-4d4ab5803608)

**Comment by miguelgargallo** [comment]
This is a great request, but you decided to close instead of hard work and deliver this :(

**Comment by miguelgargallo** [comment]
> Hey @miguelgargallo - this is a great write up!
> 
> > the ability to manage multiple projects effectively.
> 
> Supabase runs the exact same stack on our cloud that we offer for self-hosting. We spin up a server for every customer, just like I do here: https://www.youtube.com/watch?v=FqiQKRKsfZE
> 
> It should be trivial to use the images that we offer with your favourite orchestration engine: k8s, k3s, Terraform, Pulumi, Ansible ... you name it.
> 
> Supabase is designed to be scalable. We've given you the simplest components that we can without reducing scalability. If self hosting the current stack is _not_ a trivial task for you, self-hosting might not be something you should consider, or you could choose something simpler. I agree, Pocketbase offers a great way to bundle everything into a single binary - this simply isn't possible with Postgres, PostgREST, GoTrue, Kong, and a Storage Engine.
> 
> > open-source version of Supabase, as of 2024, lacks SSL support
> 
> Kong supports SSL - I shared the solution with you on [twitter](https://x.com/kiwicopple/status/1733400765937377596?s=20) a couple of weeks ago. Did you try this?
> 
> > This community, known for its dedication to creating guides and supporting features, has made Supabase more accessible and versatile
> 
> I agree! We would love your help to contribute a guide for SSL with Kong. At the moment it's mostly [me](https://github.com/supabase/supabase/pull/16097) making these guides and I would really love more help with the guides
> 
> This is a great request, thanks for taking the time to write it up. If you have anything more specific that I can action feel free to open that in a trimmed-down issue which focuses specifically on a single issue. It's very hard to cover all the topics you've introduced here with a pull request but a discrete, actionable issue is always appreciated

Is this a serious response? Comparing the capabilities of the official Supabase deployment with a self-hosted instance reveals significant discrepancies. It's disheartening to see this issue closed without a commitment to address these fundamental features. Such a decision seems dismissive of the community's needs and expertise. This isn't just about a single request; it's about respecting the intelligence and contributions of the entire Supabase community. I'm not expressing anger here, rather a deep sense of disappointment. My affection for this project remains strong, but I can't help feeling let down by this development

![image](https://github.com/supabase/supabase/assets/5947268/154f2f0d-2e69-4090-808e-f81a44a3787f)

**Comment by anasfik** [comment]
I was in the same situation in May of this year, it was just a disappointment to see the self-hosted version of Supabase comparing it to their cloud version, especially for a project that claims the "open source Firebase alternative", I did open many issues like this without any single response that makes sense.

Even today, the same thing is still happening, Supabase is an FIrebase alternative, not an open-source one, both keep their main features private and none of them is 100% open-source,  Self-hosted Supabase is meant for testing or development, not for production.

My advice is if you need a Baas without a strong need for SQL or relations in databases, self-host Appwrite. if you want to use something non-stable but working (as I know and tried), self-host Pocket Base. if you want to use some cloud-based Baas, consider Supabase if you need Postgres in your database, otherwise just stick with Firebase.
