### ISSUE TITLE
ERROR: extension "vector" has no installation script nor update path for version "0.4.0"

### ISSUE THREAD

**Issue by devbydaniel** [supabase/supabase#19966]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I recently upgraded to the newest supabase version. Now when I run `npx supabase db pull`, I get the following error:

```
ERROR: extension "vector" has no installation script nor update path for version "0.4.0" (SQLSTATE 22023)
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```

I tried to change the statement in the migration from `create extension if not exists "vector" with schema "public" version '0.4.0'` to `create extension if not exists "vector";` and run `npx supabase db pull` again but that gives me the following error:

```
ERROR: extension "vector" has no update path from version "0.5.0" to version "0.4.0" (SQLSTATE 22023)
```
... which I guess is obvious because I receive a new miration statement `alter extension "vector" update to '0.4.0';` from remote.

Adding a new migration `alter extension "vector" update to '0.5.0';` gives me the following error

```
ERROR: extension "vector" has no update path from version "0.4.0" to version "0.5.0" (SQLSTATE 22023)
```

Both locally and in my remote project, I can see on the dashboard that the `vector 0.4.0` extension is installed. The error happened after I upgrade to supabase `1.123.4` and (not sure if relevant) I manually adjusted a vector function in the database function section of my remote project.

## To Reproduce

1. Update supabase to `1.123.4`
2. Include `create extension if not exists "vector" with schema "public" version '0.4.0'` in a migration
3. Run `npx supabase db pull`

## Expected behavior

`npx supabase db pull` succeeds without error

## System information

`"supabase": "^1.123.4"`

## Additional context

This blocks any new development of my app as I cannot update the database schema anymore. Any and all help would be greatly appreciated, including workarounds that will enable further development again.

**Comment by olirice** [comment]
The supabase platform only ever has 1 version of pgvector installed at a time so I'm not sure why you'd want a 
```
alter extension "vector" update to xxx;
```
statement in your migrations.

I suspect that statement was a no-op at the time it was written e.g.
```
alter extension "vector" update to '0.4.0';
```
when '0.4.0' was already installed. In that case, the statement will succeed.

Fortunately, pgvector has been great at maintaining backwards compatibility so you should be able to remove that statement entirely and it'll restore from the pg_dump the way you expect. That's a common pattern for upgrading extension versions across databases.

**Comment by devbydaniel** [comment]
Thank you for your quick response!

The statement

```
alter extension "vector" update to '0.4.0';
```
was only included after I tried fixing the initial error. Sorry if that wasn't clear. 

To give you everything in the order it happened:

The initial error, and the one I am stuck with right now, is that all of a sudden (or basically after upgrading supabase and adjusting a db function through supabase studio), the line

```
create extension if not exists "vector" with schema "public" version '0.4.0'
```

throws the error

```
ERROR: extension "vector" has no installation script nor update path for version "0.4.0" (SQLSTATE 22023)
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```

The version `0.5.0` only appeared after I changed the line

```
create extension if not exists "vector" with schema "public" version '0.4.0';
```
to
```
create extension if not exists "vector";
```
and then did a `npx supabase db push`.

(I did that because I thought that if the error is about a specific version, it might be solved by simply removing the version.)

But when I change the migration files back to their original state, I still get 

```
ERROR: extension "vector" has no installation script nor update path for version "0.4.0" (SQLSTATE 22023)
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```

**Comment by olirice** [comment]
got it, thank you

> (I did that because I thought that if the error is about a specific version, it might be solved by simply removing the version.

yes, this should be the case

I suspect what's happening is that your migration files aren't in sync locally and on the hosted environment because the error 

```
ERROR: extension "vector" has no installation script nor update path for version "0.4.0" (SQLSTATE 22023)
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```

still includes
```
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```
which is telling you that the `version '0.4.0'` clause is still being executed even after you attempted to change it

Since this is specific to your project the best thing to do is to open a [support ticket](https://supabase.com/support) with the "open ticket" button so you can approve the support team to take a look at your instance to see what's going on

**Comment by devbydaniel** [comment]
Makes sense, thanks for your response! I'm closing this issue and open a support ticket.
