### ISSUE TITLE
Flutter Android + Google OAuth2.0 not working on Android, ID Token is NULL

### ISSUE THREAD

**Issue by kausikMR** [supabase/supabase#19964]
I followed the tutorial provided for Google authentication with Flutter [https://supabase.com/blog/flutter-authentication]

I created Client ID for Web application from Google Cloud console and provided in my supabase dashboard.

<img width="563" alt="Screenshot 2023-12-22 at 3 09 11 PM" src="https://github.com/supabase/supabase/assets/74778433/1eff9622-744f-43cb-8a8c-3c2d2e7b3bd7">

Im getting the ID Token from the Google authentication as NULL. There are no video tutorial for configuring this, if you have any that would be great.

Below is my code which I use to Signin with google, it throws ID Token is NULL error which means the ID Token was NULL.

<img width="484" alt="Screenshot 2023-12-22 at 3 02 47 PM" src="https://github.com/supabase/supabase/assets/74778433/eb744e44-ac4d-4217-9344-ffa4d88c8eb0">

**Comment by kausikMR** [comment]
### Cause of the issue 🤷🏻‍♂️
Incorrect package name (com.example.app) in the Google Cloud console.

### Where I went wrong explained 👇
I was using flavours for building my app in two versions beta and stable, this caused the app to have a new package name after building like com.example.app.beta in beta and com.example.app.stable in the stable flavour builds, but the actual package name doesn't change in the project, this caused the issue. I was receiving the `ApiException 10 ` which means the configurations on the console is different from the app like in my case the package name. after fixing it it caused me another issue which I have posted here the IdToken was null, this was because I wasn't providing the web client id in the `GoogleSignIn(serverClientId: <WEB_CLIENT_ID>)` which I got from the GoogleCloud console.

### Steps for Google OAuth with flutter + android + supabase 🚀

1. Create a project in GoogleCloud console, and navigate to the OAuth consent screen and configure it.
2. In the credentials section click create credential and choose WebApplication to create a Web clientId(Yes you need web client id for the android integration) add your supabase api url in the Authorised JavaScript origins and your callback url which you will find in your Google auth provider in supabase and add it to your Authorised redirect URIs.
3. Now again create a credential and choose Android to create Android Client ID with your package name and sha-1 key, for creating sha-1 key for flutter project refer this https://stackoverflow.com/questions/51845559/generate-sha-1-for-flutter-react-native-android-native-app
4. Go to your supabase dashboard into your Google auth provider and  add the WebClientID in the OAuth ClientId and your client secret you will find in your Web client id created in your GoogleCloud console. no need to provide your Android Client id in supabase, but make sure you provide webclient id as I told above and leave the AuthorizedClientIDs section empty, webclient id is needed even for Android or iOS.
5. Finally don't forget to provide your WebClientId in your GoogleSignIn instance, like this `GoogleSignIn(serverClientId: <WEB_CLIENT_ID>)`

### Debugging guide 🐞

1. Google sign in failed `com.google.android.gms.common.api.ApiException: 10` - Check config in the Google Cloud console client IDs, app config doesn't match with the config given in GoogleCloud console.
2. ApiException: 2400
3. ID Token was null - provide your webClientId in your GoogleSignIn instance `GoogleSignIn(serverClientId: <WEB_CLIENT_ID>)`

**Comment by diego2097** [comment]
Awesome thanks!!

**Comment by sultanbalhareth** [comment]
Hi, is it working, guys

Thank you kausikMR.
