### ISSUE TITLE
Supabase client does not include body in POST request

### ISSUE THREAD

**Issue by alumezi** [supabase/supabase#19976]
I am trying to create a user from my react-native code in my users table in supabase:

```
  const { data: supaData, error: supaError } =
  await supabase.functions.invoke("rest/users", {
    method: "POST",
    body: JSON.stringify({
      data: { name: "aa", email: "test@gmail.com" },
    }),
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers":
        "authorization, x-client-info, apikey, content-type",
    },
  });
```
GET -ing users or any other resource works fine but this one does not, the request is a 400 Unexpected end of JSON input. Since I am in react-native the error returned on server: [FunctionsHttpError: Edge Function returned a non-2xx status code].

Again works perfectly if I just change the method to GET.
I added this bug report because this also works perfectly if I use curl. This is only happening for me in react-native.

**Comment by alumezi** [comment]
Removing headers worked, using cors headers as seen on the docs.

**Comment by zach-is-my-name** [comment]
Hey I'm still experiencing this in 2.45.1.  Removing headers works after burning a hole through Anthropic's cement floor and finally checking the Issues here
