### ISSUE TITLE
Email Auth with PKCE flow only working in production

### ISSUE THREAD

**Issue by probablykasper** [supabase/supabase#19980]
# Bug report

## Link

https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr?framework=sveltekit

## Describe the problem

I've followed [the "Email Auth with PKCE flow" guide](https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr?framework=sveltekit), and I figured out how to set the email URL templeate in production. But it wasn't clear to me how to do this in development, as there's no option for it in Studio.

## Describe the improvement

Studio could keep the page shown in development too, but instead show an explanation of where to set the options.
The guide could explain how to set the URL template this in both production and development

**Comment by stuffmattdoes** [comment]
I'm having the same issue. I'm using supabase & remix, but the flow is the same.

Unfortunately, I had to downgrade back to `@supabase/auth-helpers-remix`, as `@supabase/ssr` is still in beta and doesn't seem ready for local development just yet.

**Comment by silentworks** [comment]
There are guides in the docs showing how to update the email templates in your local Supabase here https://supabase.com/docs/guides/cli/customizing-email-templates

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
