### ISSUE TITLE
Can't drop any table 

### ISSUE THREAD

**Issue by ashemag** [supabase/supabase#19981]
In supabase console, I cannot drop any of my tables in staging. Requests drop out in UI or through API... 

```
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> </body> </html>
```

**Comment by GaryAustin1** [comment]
This is likely do to your table having foreign keys not indexed or some other thing like a delete trigger running.  Hard to know without any info.   I think you commented on Discord and I linked an older discussion there on fk's needing indexes. 
This will highly likely be a Postgres thing that you need to optimize and using searches on Postgres delete table timeout or similar might be helpful.

**Comment by saltcod** [comment]
Going to close this one for inactivity. Please reply with any more debugging info you have if the issue still persists.
