### ISSUE TITLE
Supabase storage bucket only takes max 199 items

### ISSUE THREAD

**Issue by jh0274** [supabase/supabase#19994]
- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

file uploads stop working  once storage bucket reaches 199 items (regardless of tier limit of 1GB) without warning from the upload API.

## To Reproduce

from supabase import create_client, Client

url="https://...supabase.co"
key=".."
BUCKET_URL="..."

supabase: Client = create_client(url, key)
supabase.storage.from_("folkieokr-files").upload(file=file, path=f'{docId}.txt')

once 199 items reached response remains 2023-12-24 12:15:21, POST https://....supabase.co/storage/v1/object/folkieokr-files/185527.txt "HTTP/1.1 200 OK":

even though additional items not getting added to the storage bucket

## Expected behavior

I expect the uploads to continue beyond 199 items until i hit my free tier limit of 1GB
## System information

macOS, 
python supabase client -  2.3.0
python 3.9

**Comment by jh0274** [comment]
Opened in error

**Comment by jh0274** [comment]
confirmed that this isn't due to any other libary. 

from supabase import create_client, Client

url="....supabase.co"
key="..."
BUCKET_URL="https://....supabase.co/storage/v1/object/public/folkieokr-files/"

supabase: Client = create_client(url, key)

def upload_docs():
    upload_docs.counter +=1
    try:
        file = open(f'test.txt', 'rb')
        supabase.storage.from_("folkieokr-files").upload(file=file, path=f'test{download_docs.counter}.txt')
        file.close
    except Exception as e:
        print("error uploading to supabase",e)
        file.close

upload_docs.counter = 0

for i in range(200):
    upload_docs()

**Comment by jh0274** [comment]
and using  :
results = supabase.storage.from_("folkieokr-files").list()
for result in results:
    print(result['name'])
    
  only returns 100 items..  when there are 199 shown via the dashboard in the Supabase web application

**Comment by jh0274** [comment]
should be opened in supabase.py client repo

**Comment by lukuser** [comment]
It's not that it doesn't take more items, it only can't display them in the web interface. This issue describes it and I confirmed this as well: https://github.com/orgs/supabase/discussions/16951

**Comment by dogukanakkaya** [comment]
> and using : results = supabase.storage.from_("folkieokr-files").list() for result in results: print(result['name'])
> 
> only returns 100 items.. when there are 199 shown via the dashboard in the Supabase web application

The issue itself is something else from this, but anyone having the issue of `list()` method returning 100 items and came across here. Just send limit in second parameter (example in JS SDK):
```js
const { data, error } = await supabaseAdmin
     .storage
     .from('<bucketName>')
     .list('<folderNameOrUndefined>', { limit: 1000 });
```
