### ISSUE TITLE
Supabase cli (1.123.4) cannot create folders in WSL2

### ISSUE THREAD

**Issue by peijenlin** [supabase/supabase#19990]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running `npx supabase init` I get the error cannot find `supabase/config.toml`, the error is resolved if I pre-create the `supabase` folder which suggest the error is related to not be able to create the folder or the process didn't create the folder.  This use to work with 1.50.x.

Similar error is encountered when I do `npx supabase start`.  The errors are cannot read `supabase/.temp/import_maps/{some_long_hex_string}.json` and cannot find `supabase/functions`.  Once I manually create the folders supabase is able to start without error locally.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Goto new project
2. Run npx supabase init

## Expected behavior

Init completes without error

## System information

- OS: WSL2 Debian
- Version of supabase-js: N/A
- Version of Node.js: 20.10.x

## Additional context

Similar issue when running npx supabase start.

**Comment by Hallidayo** [comment]
Hi @simonha9 - Thank you for confirming this works now for you, I'll close the issue.
