### ISSUE TITLE
RLS and Email Login documentation improvements

### ISSUE THREAD

**Issue by gfx687** [supabase/supabase#20006]
# Improve documentation

## Link 
Email Login - https://supabase.com/docs/guides/auth/auth-email
Row Level Security - https://supabase.com/docs/learn/auth-deep-dive/auth-row-level-security

## Describe the problem
**Email Login page**
Page includes information about `Sign Out` twice - first time right after `Sign Up` and second time as it's own list item (screenshot added below)

**Row Level Security page**
An error in `create policy` code snippet (closer to the end of the page, it is the only `create policy` snippet, so easy to find with search)

Snippet in question:
```sql
CREATE POLICY anon_read_leaderboard ON leaderboard
    FOR SELECT
    TO 'anon'
    USING (true);
```

Error: Using single quotes with the role name. Should either be double quotes or no quotes at all, single quote will throw an error.

## Describe the improvement
**Email Login page**
Remove duplicating info

**Row Level Security page**
Fix the query by replacing single quotes with either double quotes or nothing 

```sql
CREATE POLICY anon_read_leaderboard ON leaderboard
    FOR SELECT
    TO anon
    USING (true);
```

## Additional context
![image](https://github.com/supabase/supabase/assets/19519170/f7388975-f844-4750-a221-fac4f3b3bc3d)

**Comment by Arindam200** [comment]
Can I Work on this?

**Comment by gfx687** [comment]
@saltcod 

The issue described here is not fixed yet, PR linked above only solves one of the two listed problems. (Unless, of course, second part is being done in some other, unlinked PR)
