### ISSUE TITLE
Cannot sign up for new account.

### ISSUE THREAD

**Issue by safield** [supabase/supabase#20038]
I have tried to sign up for a new account and I get the error that "an account with that email already exists". I then proceed to use the "forgot password functionality", but no email ever arrives.

I assume that either Supabase incorrectly concludes that my email is already in use, or the "forgot password" functionality is broke.

**Comment by GaryAustin1** [comment]
If you used Github to signup then the email settings don't work.

**Comment by saltcod** [comment]
Very likely what Gary said. Closing this one, but feel free to reopen if that doesn't resolve things. You'll likely need to contact support if you can't get it resolved on your own.
