### ISSUE TITLE
Issue in Fetching Data from tables: NextJs14 with JS

### ISSUE THREAD

**Issue by greeenboi** [supabase/supabase#20030]
### Discussed in https://github.com/orgs/supabase/discussions/20029

<div type='discussions-op-text'>

<sup>Originally posted by **greeenboi** December 27, 2023</sup>
This seems to be a recurring issue in my project.

Below is the code that I use to fetch data from my table

```js
useEffect(() => {
    const fetchPosts = async () => {
      let { data: posts, error } = await supabase
        .from('posts')
        .select()
      console.log(posts)
      if(error) console.log(error) 
      else setBlogPosts(posts) && console.log(posts)
    }
    fetchPosts()
  
  }, [])
```

the response that i receive on the console is always an empty array.

I have:
- tried disabling rls 
- tried different browsers
- tried the same on a test ViteJs project 
- added policies to allow read and write to the public

I want to know how i can fix this issue.
The [Repository](https://github.com/greeenboi/sample_blog/tree/master) if you want to see it for reference.
</div>

**Comment by GaryAustin1** [comment]
I'm going to close this in favor of your discussion on same issue.  Next.js does caching in some cases based on the URL and this certainly can impact testing RLS as changes would not be reflected.   Empty array is almost always RLS.
