### ISSUE TITLE
supabase.auth.admin.deleteUser documentation for "shouldSoftDelete" does not describe the effect of the option

### ISSUE THREAD

**Issue by christopherreay** [supabase/supabase#20057]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-admin-deleteuser

## Describe the problem

there is no attempt to describe the effect of this option

shouldSoftDelete
Optional
boolean
If true, then the user will be soft-deleted from the auth schema. Defaults to false for backward compatibility. This function should only be called on a server. Never expose your `service_role` key in the browser.

## Describe the improvement

explain the effect of this option

## Additional context

n/a

**Comment by christopherreay** [comment]
hi :) well i feel validated :)

the fix is here ![Screenshot_20240324_102549.jpg](https://github.com/supabase/supabase/assets/239550/8d1f2760-32d7-46ac-ab29-f9ead8e01ab4)

and has been committed to some branch
but the website doesn't appear to have been updated yet.

**Comment by J0** [comment]
Hey all,

The site should be updated now. Thanks for the feedback!
