### ISSUE TITLE
the term "storage" has two distinct meanings. It is hard to find documentation on the auth.storage option for createClient

### ISSUE THREAD

**Issue by christopherreay** [supabase/supabase#20058]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/initializing

## Describe the problem

trying to google for "storage" in relation to the supabase-js client `auth.storage` option is difficult, since storage is one of the client's primary behaviours in terms of Storage on the supabase platform.

  I found at some point a definition of the `interface` for creating a storage provider for the `auth.storage` option, but Ive been looking for like half an hour, including into source code, and I just keep finding stuff about storage onto the platform.

## Describe the improvement

seems reasonable to put a link here to documentation about how to implement a storage. I can see there is reference to a react widget called AsyncStorage, so I guess I could look for that.

## Additional context

n/a

**Comment by christopherreay** [comment]
So Ive sort of emerged the understanding that what I want to search for is the "gotrue client supabase". maybe explain that or put a link to it? 

just because of the overlap of the embedding of "storage"

**Comment by burggraf** [comment]
@christopherreay can you describe exactly what you were trying to do when you were initially 

> trying to google for "storage" in relation to the supabase-js client auth.storage? 

It would help us to know what your intent was so we can update any documentation accordingly.  Thanks!

**Comment by christopherreay** [comment]
sorry i didn't reply, I've been travelling and i only just sorted proper internet.

i will answer later today

**Comment by christopherreay** [comment]
RIght, so.

I was trying to write a Storage for the supabase client for credentials storage... as in the GoTrue js client storage. The storage I write uses httpOnly cookies as storage right... which was my choice for server side control over expiry, etc.

until I realised I was looking for "gotrue storage" it was ... more or less impossible to find the documentation. does that make sense? Because of the google overload of "storage".

like "supabase client storage" is never gonna find you that.

I think it is worth putting in the time to do something about that (e.g. just a sort of wikipedia style disambiguation in the docs for storage)... but... i recognnise that it is a minimal use case.


cheers for the amazing software. you are changing the world tyty
