### ISSUE TITLE
[Edge Functions]

### ISSUE THREAD

**Issue by IsmailAlamKhan** [supabase/supabase#20075]
# Bug report

- [*] I confirm this is a bug with Supabase, not with my own application. 
- [*] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I was working with Supabase CLI v1.99 and functions were deploying properly but after upgrading to the latest version(1.127.3) I am not being able to publish and the error is probably somewhere in my configuration. Here is the error.
```
Failed to create a new Function on the Supabase project: {"message":"Cannot POST /v1/projects//functions?entrypoint_path=file%3A%2F%2F%2Fhome%2Fdeno%2Ffunctions%2Fpush_notification_fcm%2Findex.ts&import_map_path=file%3A%2F%2F%2Fhome%2Fdeno%2Fimport_map.json&name=push_notification_fcm&slug=push_notification_fcm&verify_jwt=false"}
```
As you can see it just does a request to /v1/projects//functions.... It doesn't contain my project id so what would be the solution to this issue. Please help

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialise a new supabase project using Supabase CLI(latest version 1.127.3)
2. Create a new function.
3. Deploy the function.

## Expected behavior

The function should get deployed perfectly fine

## Screenshots
![Screenshot 2023-12-31 at 12 46 58 PM](https://github.com/supabase/supabase/assets/67656229/988099bc-e853-4f7c-85bf-9ac89d120284)

## System information

- OS: MacOS Sonoma 14.1.2 (23B92) with M2 chip.
- Version of supabase-js: 1.127.3
- Version of Node.js: v21.1.0

## Additional context

None

**Comment by IsmailAlamKhan** [comment]
I have tried on my Windows 11 PC and surprisingly it worked with the exact same version and the same code. So whats the problem with MacOS? I mainly work on MacOS so I need it working there.

**Comment by laurencebedford** [comment]
I have just come onto to log the same issue. Im on Mac M1 and this isn't just relating to creating a new edge function it also involves even setting the env:

Im running:
`supabase secrets set --env-file ./supabase/functions/.env --debug`

And get the response:
<img width="769" alt="image" src="https://github.com/supabase/supabase/assets/69059597/c70becf3-b3fc-4074-b894-06c9007b2499">

**Comment by aadityabhusal** [comment]
Serving functions locally doesn't work too. Displays a message with "Database error occurred".

<img width="664" alt="image" src="https://github.com/supabase/supabase/assets/46737849/d962902b-7450-4773-b399-1cf679ad220e">

**Comment by devtayyab** [comment]
Try to deploy by passing project ref with command
supabase functions deploy function-name --project-ref XXXX
