### ISSUE TITLE
[Edge Functions] - Unexpected error {"message":"Cannot POST /v1/projects//"}

### ISSUE THREAD

**Issue by laurencebedford** [supabase/supabase#20080]
# Bug report

- [*] I confirm this is a bug with Supabase, not with my own application. 
- [*] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am working with supabase CLI and would like to deploy a function. When deploying anything to do with edge functions I run into an error regarding "cannot post". Here's an example when running the deploy function command:

`Failed to create a new Function on the Supabase project: {"message":"Cannot POST /v1/projects//functions?entrypoint_path=file%3A%2F%2F%2Fhome%2Fdeno%2Ffunctions%2Fmark-quiz%2Findex.ts&import_map_path=file%3A%2F%2F%2Fhome%2Fdeno%2Fimport_map.json&name=mark-quiz&slug=mark-quiz&verify_jwt=true"}`

The same error occurs if I try to set the env path:

`Unexpected error setting project secrets: {"message":"Cannot POST /v1/projects//secrets"}`

Correct me if im wrong but its looking like its not setting the URL correctly (/v1/projects//functions) - should it be /v1/projects/**MYPROJECT**/functions

I have tried re-linking my project, creating a brand new function and trying to deploy it and the same issues occur.

I have also tried:
<img width="818" alt="image" src="https://github.com/supabase/supabase/assets/69059597/c55b7aa9-3b87-489f-86f7-d9abd3337315">

But I am not sure whether I can post the full CLI response due to a lot of keys/info in there - I dont want to leak any project information.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialise a new supabase project using Supabase CLI(latest version 1.127.3)
2. Create a new function.
3. Set env using the command:
`supabase secrets set --env-file ./supabase/functions/.env`
4. Deploy the function using the command:
`supabase functions deploy function-name`

## Expected behavior

The function should be deployed smoothly along with its env path - with no errors.

## Screenshots

Deploy Error:
<img width="1050" alt="image" src="https://github.com/supabase/supabase/assets/69059597/b7369e71-b4d1-4ea8-b1da-78b120f9c1a5">

Env error:
<img width="772" alt="image" src="https://github.com/supabase/supabase/assets/69059597/2ba75583-d9f7-4c3c-a6dd-9ffb861623a9">

## System information

- OS: [macOS 4.0 with M1 Pro]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 1.127.3

## Additional context

I created a function fine earlier it just won't let me create any more since.

**Comment by quentin7b** [comment]
Ran in the same issue, looking at the docs, I specified the project ref

`supabase functions deploy function-name --project-ref XXXX` and it worked

**Comment by laurencebedford** [comment]
Perfect - I managed to work my way around it by uninstalling supabase cli and reinstalling however, if running that command worked - that is a quicker and more convenient work around. Thanks!
