### ISSUE TITLE
Migrated project not working as expected

### ISSUE THREAD

**Issue by vincenzon** [supabase/supabase#20089]
I cloned a project following [the instructions here](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#migrate-your-project).

When I use the URL + ANON key for the new project my node application does not work, if I use the original project it does.

Things that do not work: `supabase.auth.getSession` just returns null, `supabase.rpc` returns error: null. I can tell the calls are running from the logs, if I try to call a non-existant rpc it returns an error that the function does not exist.

I'm baffled at this point. I see the data / functions of the cloned project but I cannot access it from my app. I'm guessing I missed some crucial step in the migration process. Any help is appreciated.

**Comment by vincenzon** [comment]
I should add, the problems only happen when accessing the new project with the javascript client. All the backend code I have that accesses the new project using python via the project URI: postgresql://postgres:... work as expected.

**Comment by vincenzon** [comment]
More information. If I create a new function in the new project that runs select 1 as c1, that works. If I create a function that counts the rows of a table, select count(*) from t1, when I run it from the supabase console, that returns the correct number of rows. When I run it from my app, that returns 0.

I had set up the original project for local development, though I never accessed the local version. The new project has not been set up for local development, nor do I want it to be. Is it possible this is the source of the problem?

**Comment by vincenzon** [comment]
If I create a new table and populate it with data and write rpc calls against it, the supabase-js client runs these and they return correct answers. How is a table created via migration: 
```
psql 
  --single-transaction 
  --variable ON_ERROR_STOP=1 
  --file roles.sql 
  --file schema.sql 
  --command 'SET session_replication_role = replica' 
  --file data.sql 
  --dbname "$NEW_DB_URL"
```

different from one created in the supabase console?

**Comment by GaryAustin1** [comment]
Your direct database port and your SQL editor query both run as user Postgres and bypass any RLS you may have enabled.
You JS symptoms sound like you don't meet RLS policies.

**Comment by vincenzon** [comment]
I disabled RLS on the table and I still get no results.

**Comment by vincenzon** [comment]
The result from following that migration document really seems to be a project in a broken state. Here is another problem, in my `supabase.auth.onAuthStateChange` handler, when a session is received I invoke:

```
const {data, error} = await supabase.auth.getUser();
console.log(`Never see this log line`);
```

the function never returns, the console log line never runs. At this point I am just going to delete the project and use the `pg_dump` sql files to manually rebuild a copy of the project.

**Comment by GaryAustin1** [comment]
Your auth.getUser should not be done in the event handler.
https://supabase.com/docs/reference/javascript/auth-onauthstatechange

![image](https://github.com/supabase/supabase/assets/54564956/a2882c21-cd52-4307-bc42-c1f7759774dd)

**Comment by vincenzon** [comment]
Good to know, but that sequence works fine in the original project.

**Comment by vincenzon** [comment]
I ended up migrating the data manually.
