### ISSUE TITLE
How to send a message broadcast on a different component where the channel itself is not created

### ISSUE THREAD

**Issue by hsglc** [supabase/supabase#20086]
# Improve documentation

## Link 

[broadcast](https://supabase.com/docs/reference/javascript/broadcastmessage)

## Describe the problem

I'm using supabase with the next.js. I created a broadcast channel in a client component to listen any messages and then i want to send a message to this channel outside this component, I mean in a different component. Unfortunatelly I didn't handle it. There was not any specific description inside the doc.

## Describe the improvement

You can add a mini example of this usage if any exist?

## Additional context

```
Notification.tsx
const friendshipBroadcast = supabase.channel('notifications/friendship', {
		config: {
			broadcast: { self: true },
		},
	});
friendshipBroadcast
		.on('broadcast', { event: 'Friendship' }, (event: any) => {
			console.log('friendship event :', event);
		})
		.subscribe();
```

```

Friendship.tsx

const friendshipBroadcast = supabase.channel('notifications/friendship', {
		config: {
			broadcast: { self: true },
		},
	});
	
	friendshipBroadcast
		.on('broadcast', { event: 'Friendship' }, (event: any) => {
			console.log('friendship event :', event);
		})
		.subscribe();
const friendshipBroadcastHandler = () => {
		return friendshipBroadcast.send({
			type: 'broadcast',
			event: 'Friendship',
			payload: { isSuccess: true, message: 'Friendship request sent' },
		});
	};
```

when friendshipBroadcastHandler fires, notification does not aware of it.

**Comment by encima** [comment]
Hi @hsglc,

The component itself should not matter, what matters is that the connections are active, preserved and long-lived. You will probably find that the Notification code is not running while the other is (or something along those lines).

You can test the functionality by creating a file like `InitChannel.js` with 

```js
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'URL';
const supabaseKey = 'KEY';
const client = createClient(supabaseUrl, supabaseKey);

function createChannel(client, name) {
  return client.channel(name, {
    config: {
      broadcast: { self: true },
    }
  });
}

function messageReceived(payload, channelName) {
  console.log(`message to ${channelName}`)
  console.dir(payload)
  console.log("----------")
}

channelA = createChannel(client, 'A');

channelA.on(
  'broadcast',
  { event: 'test' },
  (payload) => messageReceived(payload, channel.topic)
)
.subscribe()
```

and another file, like `MsgSender.js` with:

```js
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'URL';
const supabaseKey = 'KEY';
const client = createClient(supabaseUrl, supabaseKey);

function createChannel(client, name) {
    return client.channel(name, {
        config: {
            broadcast: { self: true },
        }
    });
}

function sendMessage(channel, message) {

    channel.send({
        type: 'broadcast',
        event: 'test',
        payload: { message: message },
    })
}

const channelA = createChannel(client, 'A')
sendMessage(channelA, { content: 'Hello from subscriber to channel A!' });
```

If you run the first file and, while it is running, run the second, you will see that the second file sends a message, which is received by the first file and logged.

Hopefully this gives you some pointers to help debug your issue but please comment if you think more information is needed.

**Comment by hsglc** [comment]
Hi @encima ,thank you for your respond. There's a confusion that I cannot figure it out that is you're creating 2 different channel with 2 different file. Are they the same channel?

**Comment by encima** [comment]
Hi @hsglc ,

The channels are the same, yes, mine is `channelA`.

I am afraid I do not know the issue with yours as it is running in a framework so many other things will influence it. I would assume that the original code in Notification is not running when the other component is. You could move that subscription code to your root file on app creation to check.

**Comment by hsglc** [comment]
@encima, I'm using Next.js App Router, maybe it would trigger something that is broke my channel subscription.
All in all, thank you for your response. I'll dig into it.
