### ISSUE TITLE
Self-hosted storage error 500 "The file system does not support extended attributes or has the feature disabled."

### ISSUE THREAD

**Issue by ethicnology** [supabase/supabase#20096]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Trying to upload a file in a bucket result with errors

May be related to:
- #10977 
-  #14324 

**The solutions provided are related to macos VirtioFS which is not my case…**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Deploy self-hosted supabase following the official documentation
2. Create a bucket
3. Upload a file
4. Error 500
```json
{"statusCode":"500","error":"Error","message":"The file system does not support extended attributes or has the feature disabled."}
```

## Expected behavior

File uploaded in supabase storage

## Screenshots

<img width="368" alt="Screenshot 2024-01-01 at 6 48 41 PM" src="https://github.com/supabase/supabase/assets/25751709/0a3b2586-25c3-450d-b676-11125e955ee3">

## System information

- OS: Linux 6.1.0-10-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux
- Browser: chrome & firefox

## Additional context

<details><summary>Logs</summary>
<p>

supabase-storage                | {"level":30,"time":"2023-12-18T15:12:17.946Z","pid":1,"hostname":"499a4c8948ab","jodId":"","type":"event","event":"ObjectAdminDelete","payload":"{\"name\":\"Untitled.jpg\",\"bucketId\":\"test\",\"tenant\":{\"ref\":\"stub\",\"host\":\"localhost\"},\"version\":\"e7f8e9ac-ad0e-4313-9495-427374438526\",\"reqId\":\"req-y\",\"$version\":\"v1\"}","objectPath":"stub/test/Untitled.jpg","tenantId":"stub","project":"stub","reqId":"req-y","msg":"[Admin]: ObjectAdminDelete stub/test/Untitled.jpg"}
supabase-kong                   | 10.19.117.1 - - [18/Dec/2023:15:12:18 +0000] "POST /storage/v1/object/test/Untitled.jpg HTTP/1.1" 500 130 "http://localhost:8000/project/default/storage/buckets/test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"
supabase-storage                | {"level":30,"time":"2023-12-18T15:12:18.018Z","pid":1,"hostname":"499a4c8948ab","reqId":"req-y","tenantId":"stub","project":"stub","reqId":"req-y","type":"request","req":{"traceId":"req-y","method":"POST","url":"/object/test/Untitled.jpg","headers":{"host":"storage:5000","x_forwarded_proto":"http","x_forwarded_host":"localhost","x_forwarded_port":"8000","x_real_ip":"10.19.117.1","content_length":"5825","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0","accept":"*/*","referer":"http://localhost:8000/project/default/storage/buckets/test","x_client_info":"supabase-js-web/2.38.3","x_upsert":"false","content_type":"multipart/form-data; boundary=---------------------------84013450922543696563518664756"},"hostname":"storage:5000","remoteAddress":"172.20.0.7","remotePort":50720},"res":{"statusCode":500,"headers":{"content_type":"application/json; charset=utf-8","content_length":"130"}},"responseTime":340.11541399359703,"error":{"raw":"{\"name\":\"Error\",\"httpStatusCode\":500,\"userStatusCode\":500,\"originalError\":{\"code\":\"ENOTSUP\",\"errno\":95}}","name":"Error","message":"The file system does not support extended attributes or has the feature disabled.","stack":"Error: The file system does not support extended attributes or has the feature disabled.\n    at StorageBackendError.fromError (/app/dist/storage/errors.js:46:16)\n    at FileBackend.uploadObject (/app/dist/storage/backend/file.js:74:48)\n    at async Uploader.upload (/app/dist/storage/uploader.js:55:36)\n    at async ObjectStorage.uploadNewObject (/app/dist/storage/object.js:29:35)\n    at async Object.<anonymous> (/app/dist/http/routes/object/createObject.js:42:46)"},"msg":"stub | POST | 500 | 172.20.0.7 | req-y | /object/test/Untitled.jpg | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"}

</p>
</details>

**Comment by the-rich-piana** [comment]
Also getting this issue. At first I thought it was docker related but now I'm not sure. I'm on Ubuntu 22.04. And I'm trying to upload files pulled from an S3 bucket into my local supabase storage volume.

**Comment by ethicnology** [comment]
Any update ?

**Comment by the-rich-piana** [comment]
@Serlodh solutions seems to have worked. Not sure why mods didn't post a solution. They just closed the other tickets.

**Comment by ethicnology** [comment]
@Serlodh @the-rich-piana 

Did you configure anything to make it works ?

`dependency failed to start: container supabase-minio-1 is unhealthy`

```logs
minio-1                         | MinIO Object Storage Server
minio-1                         | Copyright: 2015-2024 MinIO, Inc.
minio-1                         | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-1                         | Version: RELEASE.2024-03-21T23-13-43Z (go1.21.8 linux/amd64)
minio-1                         | 
minio-1                         | API: http://172.25.0.4:9000  http://127.0.0.1:9000 
minio-1                         | WebUI: http://172.25.0.4:9001 http://127.0.0.1:9001 
minio-1                         | 
minio-1                         | Docs: https://min.io/docs/minio/linux/index.html
minio-1                         | Status:         1 Online, 0 Offline. 
minio-1                         | STARTUP WARNINGS:
minio-1                         | - The standard parity is set to 0. This can lead to data loss.
supabase-imgproxy               | INFO    [2024-03-26T02:00:48Z] Started /health  request_id=OLHxMX10tLF22brmNpwzW method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2024-03-26T02:00:48Z] Completed in 315.705µs /health  request_id=OLHxMX10tLF22brmNpwzW method=GET status=200 client_ip=127.0.0.1
supabase-vector                 | 2024-03-26T02:00:50.887409Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=e5247048fde9500949fd8af85daa7c1b09587ac223c4ab33c029cf2adc01b5d1
supabase-db                     | 
supabase-db                     | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db                     | 
supabase-vector                 | 2024-03-26T02:00:51.069929Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"upcase\" at (476:516): expected string, got null" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
supabase-vector                 | 2024-03-26T02:00:51.069972Z ERROR transform{component_kind="transform" component_id=db_logs component_type=remap component_name=db_logs}: vector::internal_events::remap: Internal log [Mapping failed with event.] is being rate limited.
supabase-vector                 | 2024-03-26T02:00:52.075907Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: dns error: failed to lookup address information: Name does not resolve error_type="request_failed" stage="processing" internal_log_rate_limit=true
supabase-vector                 | 2024-03-26T02:00:52.076017Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: dns error: failed to lookup address information: Name does not resolve internal_log_rate_limit=true
supabase-vector                 | 2024-03-26T02:00:53.079340Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}:http: vector::internal_events::http_client: Internal log [HTTP error.] is being rate limited.
supabase-vector                 | 2024-03-26T02:00:53.079487Z  WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}: vector::sinks::util::retries: Internal log [Retrying after error.] is being rate limited.
supabase-imgproxy               | INFO    [2024-03-26T02:00:53Z] Started /health  request_id=tLFpnMjRfrsYv1-0kcMd5 method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2024-03-26T02:00:53Z] Completed in 229.392µs /health  request_id=tLFpnMjRfrsYv1-0kcMd5 method=GET status=200 client_ip=127.0.0.1
supabase-analytics              | LOGFLARE_NODE_HOST is: 127.0.0.1
dependency failed to start: container supabase-minio-1 is unhealthy
```

**Comment by Hallidayo** [comment]
Hi @ethicnology - Just checking in here, did you get this working for you?

**Comment by ethicnology** [comment]
@Hallidayo I tried with a fresh environment and executed the command I mentionned earlier in this discussion and I obtained the same error also mentionned earlier.

`dependency failed to start: container supabase-minio-1 is unhealthy`

**Comment by ethicnology** [comment]
@Hallidayo 
`docker logs supabase-minio-1`
```sh
 You are running an older version of MinIO released 3 months before the latest release 
 Update: Run `mc admin update ALIAS` 

MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2024-03-21T23-13-43Z (go1.21.8 linux/amd64)

API: http://172.19.0.3:9000  http://127.0.0.1:9000 
WebUI: http://172.19.0.3:9001 http://127.0.0.1:9001 

Docs: https://min.io/docs/minio/linux/index.html
Status:         1 Online, 0 Offline. 
STARTUP WARNINGS:
- The standard parity is set to 0. This can lead to data loss.
```

**Comment by Hallidayo** [comment]
@ethicnology - thats strange, could you try running a fresh install if possible? This will also remove all data if you have any and start from scratch

Stop docker and remove volumes:
‘docker compose down -v’

Remove Postgres data:
‘rm -rf volumes/db/data’

**Comment by the-rich-piana** [comment]
@ethicnology not sure if related:
supabase-db-minio-createbucket-1:
```Added `supa-minio` successfully.
mc: <ERROR> Unable to make bucket `supa-minio/stub`. Your previous request to create the named bucket succeeded and you already own it.```

Otherwise, using minio worked for me, even with that "unhealthy" log.

**Comment by ethicnology** [comment]
@the-rich-piana 

I changed host, it was failing because of context, the whole supabase instance was running into a [multipass](https://multipass.run/) managed VM, in a new host directly on the bare dedicated server it seems to work (supabase-minio-1 is **now** healthy).

I didn't try to upload a document yet, but I suppose it's solved.

Shouldn't we add the command to the documentation ?

```sh
docker compose -f docker-compose.yml -f docker-compose.s3.yml up -d
```

**Comment by chang1134** [comment]
> > Any update ?
> 
> For some reason when you start supabase with the s3 compose: **docker compose -f docker-compose.yml -f docker-compose.s3.yml up** it magically works. I now have no errors when uploading any files.
> 
> Had the same error before

Thanks, it worked for me.

**Comment by sbmanolo** [comment]
> > Any update ?
> 
> For some reason when you start supabase with the s3 compose: **docker compose -f docker-compose.yml -f docker-compose.s3.yml up** it magically works. I now have no errors when uploading any files.
> 
> Had the same error before

So far, this is what has worked for me. I haven't had to restart/delete the database, I just ran it and added `-d --force-recreate`.
