### ISSUE TITLE
Unable to edit security policies

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#2010]
# Bug report

## Describe the bug

Trying to delete or save an edit to a row level security policy returns `error id is required` with an HTTP 500 status code.

## To Reproduce

1. Go to the Auth > Policies page
2. Click delete on an existing policy (or edit and then save)

**Comment by inian** [comment]
Hi @emschwartz, we have deployed a brand new policy editor which should fix this. Feel free to reopen if you see any issues. Thanks!

**Comment by emschwartz** [comment]
The new policy editor looks good. However, I am seeing the following error when I click `Review` (and the new policies are not saved):
![image](https://user-images.githubusercontent.com/3262610/122789775-a8d5cf80-d285-11eb-9e0c-479ac9d026de.png)

```
11:40:46.347 TypeError: E is undefined
    parseKey Tokenizer.js:191
    value Tokenizer.js:235
    value Tokenizer.js:187
    value Tokenizer.js:182
    value Tokenizer.js:127
    value Tokenizer.js:107
    value Formatter.js:87
    format sqlFormatter.js:74
    D PolicyReview.js:43
    React 12
    r helpers.js:72
    _wrapEventTarget trycatch.js:137
    h instrument.js:476
    React 22
    Webpack 16
instrument.js:109:45
```

**Comment by emschwartz** [comment]
(@inian it looks like I'm not allowed to reopen the issue but I'd appreciate if you would)

**Comment by joshenlim** [comment]
> The new policy editor looks good. However, I am seeing the following error when I click `Review` (and the new policies are not saved):
> ![image](https://user-images.githubusercontent.com/3262610/122789775-a8d5cf80-d285-11eb-9e0c-479ac9d026de.png)
> 
> ```
> 11:40:46.347 TypeError: E is undefined
>     parseKey Tokenizer.js:191
>     value Tokenizer.js:235
>     value Tokenizer.js:187
>     value Tokenizer.js:182
>     value Tokenizer.js:127
>     value Tokenizer.js:107
>     value Formatter.js:87
>     format sqlFormatter.js:74
>     D PolicyReview.js:43
>     React 12
>     r helpers.js:72
>     _wrapEventTarget trycatch.js:137
>     h instrument.js:476
>     React 22
>     Webpack 16
> instrument.js:109:45
> ```

hey there @emschwartz! if you don't mind could I check what was the definition and operation that you tried to enter when creating your policy before running into this issue?

**Comment by emschwartz** [comment]
The policy was a very simple one to disable reading so the definition was just `false` and it was for `select`

**Comment by joshenlim** [comment]
gotcha on this @emschwartz, thanks so much! will look into a fix :)

**Comment by inian** [comment]
Hey @emschwartz, this has been fixed and will be deployed by today.

**Comment by emschwartz** [comment]
@inian Has that fix already been deployed? I just tried saving the same simple `false` policy for `Select` and saw this again:
![image](https://user-images.githubusercontent.com/3262610/122976603-88c80e00-d362-11eb-93f0-70cc93945949.png)

**Comment by inian** [comment]
Hi @emschwartz its deployed now
