### ISSUE TITLE
GraphQL Schema Error: "Invalid or incomplete schema" 

### ISSUE THREAD

**Issue by felipenmoura** [supabase/supabase#20106]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

> I cannot ensure if this is caused by something I did, or a bug within supabase based only in the message

## Describe the bug

Out of the blue, the Supabase's Graphql interface tool can no longer retrieve the schema.
Instead, as soon as it opens, it shows the message:

```
Invalid or incomplete schema, unknown type: org_usersConnection. Ensure that a full introspection query is used in order to build a client schema.
```

I have a table named `org_users`, but I am not sure what that `org_usersConnection` is. Must be something created automatically.

I even tried to rebuild the schema, but failed for multiple reasons (including lack of permissions, functions that don't exist in graphql schema of database, etc).

This error makes the **documentation** in the API stop working, but the api itself still **works**.  
I can query the tables, I just can't see the docs, and the autocompletion will not show any options.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I am not sure...it simply started happening.
Those tables weren't even new ones, I've been using them for a while.

The only thing I think that might be related, is that the project was "archived" automatically (I hadn't worked on it for a few days) and I had to de-archive it (which took some minutes to finish).

## Expected behavior

The documentation in the API should be available.
Autocomplete should work.

## Screenshots

<img width="641" alt="image" src="https://github.com/supabase/supabase/assets/347387/ebd82d26-3c2b-46ce-88e7-6ccd3d7e96f3">

## System information

- OS: macOs
- Browser: Chrome, Arc
- Version of supabase-js: (on the webpage)

**Comment by felipenmoura** [comment]
I think that if this is due to something I did, there could be something in the docs warning to whatever I did and how to fix it, so other people can fix this quickly.
I am looking for this the whole day and can't find anything.

**Comment by olirice** [comment]
closing in favor of https://github.com/supabase/pg_graphql/issues/481
