### ISSUE TITLE
Nothing on the Query Performance page is useful because postgres role doesn't have permissions to select from pg_stat_statements

### ISSUE THREAD

**Issue by bpeck81** [supabase/supabase#20115]
# Bug report

⚠️ We receive a lot of bug reports which have already been solved or discussed. If you are looking for help, please try these first:

- Docs: https://docs.supabase.com
- Discussions: https://github.com/supabase/supabase/discussions
- Discord: https://discord.supabase.com

Before opening a bug report, please verify the following: 

-->

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I can't view inefficient queries because pg_stat_statements returns 'insufficient privilege'

## To Reproduce

Go to https://supabase.com/dashboard/project/<id>/reports/query-performance

Or execute any of these queries in the SQL Editor https://supabase.com/docs/guides/platform/performance#examining-query-performance

## Expected behavior

I can see the queries that need to be optimized

## Screenshots
![Screenshot 2024-01-02 at 4 23 02 PM](https://github.com/supabase/supabase/assets/7690994/eb35c81d-7c6e-4579-b745-60416fcf6e05)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
This was just posted in Troubleshooting.
https://github.com/orgs/supabase/discussions/20126
Going to close this as that likely solves it.
