### ISSUE TITLE
Migration to SSR instead of Auth-Helpers breaks sessions.

### ISSUE THREAD

**Issue by karthikjn01** [supabase/supabase#20141]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm running into an issue where the function `supabase.auth.getSession()` is returning `{ data: { session: null }, error: null }` after successful login. This issue is being experienced by other devs also however I didn't see an issue created with it in mind.

## To Reproduce

function to create supabase server client.
```
   const supabase = createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        {
            cookies: {
                get(name: string) {
                    return cookieStore.get(name)?.value
                },
                set(name: string, value: string, options: CookieOptions) {
                    cookieStore.set({ name, value, ...options })
                },
                remove(name: string, options: CookieOptions) {
                    cookieStore.set({ name, value: '', ...options })
                },
            },
        }
    );
```
 Function that'll auto reroute to login page if there is no session.
 ```
    const supabase = await ServersideSupabase({ redirect: false });

    const { data: { session: sesh } } = await supabase.auth.getSession();

    console.log("SESSION", sesh);

    if (!sesh) {
        redirect('/login?callbackUrl=' + callbackUrl);
    }
 ```
 Code to login:
 ```
 const { error, data } = await supabase.auth.signInWithPassword({
    email: cleanEmail,
    password,
  })
  ```
  
## Expected behavior

Session info should be returned successfully. 

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies) Chrome
- Version of supabase-js: ^2.39.2
- Version of Node.js: Running on edge runtime with CloudFlare workers and next-on-pages.

**Comment by yyassif** [comment]
I can confirm that the same is happening to me! two days now and still no luck :disappointed:

**Comment by charislam** [comment]
Can you tell me a bit more about your setup? It looks like you're running Next.js. Is that code snippet for `createServerClient` running in a Server Component or middleware?

Keep in mind that you [can't set cookies from a Server Component](https://nextjs.org/docs/app/api-reference/functions/cookies?ref=propelauth.com#cookiessetname-value-options), so you need [middleware](https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=middleware) to set the auth cookie.

**Comment by saltcod** [comment]
A barebones repo setup would help a lot @yyassif  and @karthikjn01

**Comment by simonh1000** [comment]
I think I have the same with svelte and was trying to debug with a simple(r) repro - https://github.com/simonh1000/supabase-auth
 
 The issue for is that in `/+layout.ts` we come back with `?code=abc` url and the timing at which point that becomes a session that i can use is unpredictable, so I have to have extra checks for `session` existing and ... ultimately this code does not work in my current dev environment

**Comment by Shaun-Regenbaum** [comment]
I fund an easier solution, just check if there is an existing session in data from layout before using getSession
```
export const load: LayoutLoad = async ({ fetch, data, depends }) => {
	depends('supabase:auth');
	depends('supabase:ssr');
	const supabase = createBrowserClient(
		PUBLIC_SUPABASE_URL,
		PUBLIC_SUPABASE_KEY,
		{
			global: {
				fetch,
			},
			cookies: {},
		}
	);
	let session = data.session;
        if (!session) {
		        if (isBrowser() && session) {
			        session = (await supabase.auth.getSession()).data.session;
		        }
	 return ( session:session
}

```

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity and also due to recent updates to `@supabase/ssr`. Please feel free to reopen if you’re still having issues here or open a new issue.
