### ISSUE TITLE
Real-time Broadcast Function Sending Message to Only First User 

### ISSUE THREAD

**Issue by GuysmoB** [supabase/supabase#20148]
Hi,

I've encountered a bug related to real-time functionality. When attempting to send a message to multiple users for a specific action, I wrapped the real-time broadcast function in a for loop. However, it seems that only the first user in the loop receives the message. Despite adding logs for each call, the message isn't being sent.

I've also attempted to split the for loop into multiple calls using different channel names, but the issue persists. Only the first channel successfully sends the message, despite all three logs being triggered. Even the listener in the realtime inspector isn't triggered for the other users.

This issue is present within a server action file, and the real-time listener is defined within a context that encapsulates my entire application. In these screenshots, only the browser with `rbrauge` receive `console.log('test', payload)`

Context.tsx
![image](https://github.com/supabase/supabase/assets/42407006/2ecbc3df-983e-49fb-9180-34a69f509996)

ServerAction.tsx
![image](https://github.com/supabase/supabase/assets/42407006/7a07d54d-2568-477c-85ad-5acbed8198b5)

logs :
```
status SUBSCRIBED
error undefined
user:559e7f65-60ab-4ca2-9315-78e3d9500d6b | rbrauge
status SUBSCRIBED
error undefined
user:19a197c4-0030-4e5b-961e-afb440b1a726 | myyopmail
status SUBSCRIBED
error undefined
user:cc788a91-5ff7-4f04-9e8b-2623f7418f59 | client
```

"@supabase/auth-helpers-nextjs": "^0.8.7",
"next": "^13.5.6",

Thanks for any help !

**Comment by encima** [comment]
Hi @GuysmoB,

To diagnose this further, it will be easier to set this as a minimal reproducible example as it is harder to debug

As an example:

```
function createChannel(client, name) {
  return client.channel(name, {
    config: {
      broadcast: { self: true },
    }
  });
}

const channels = []
channels.push(createChannel(client, 'A'))
channels.push(createChannel(client, 'B'))
channels.push(createChannel(client, 'C'))

function messageReceived(payload, channelName) {
  console.log(`message to ${channelName}`)
  console.dir(payload)
  console.log("----------")
}

channels.map((channel) => {
  channel.on(
    'broadcast',
    { event: 'test' },
    (payload) => messageReceived(payload, channel.topic)
  )
  .subscribe()
})
```

**Comment by simonha9** [comment]
Hi! Is this still needed? I can't seem to reproduce with copy-paste from the above ![image](https://github.com/supabase/supabase/assets/45949251/08d47543-8e00-474e-967a-4fca50311242)

But if it is still an issue I would love to take it!

**Comment by GuysmoB** [comment]
Hi,
My project changed but I'll use Supabase Broadcast very soon for a messaging feature.
I'll keep you in touch.
I'll close this thread if I can't reproduce it anymore.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
