### ISSUE TITLE
Sort policies alphabetically 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#20158]
Tables can have many policies, making individual ones hard to find.  We should sort these alphabetically to help. 

https://supabase.com/dashboard/project/_/auth/policies
https://supabase.com/dashboard/project/_/storage/policies

<img width="1192" alt="screenshot-2024-01-04-at-10 21 46" src="https://github.com/supabase/supabase/assets/105593/be48a44e-4f91-4106-8203-fe1c4fee7452">

**Comment by shishiro26** [comment]
@saltcod, I attempted to replicate this in my Supabase, but the items are being sorted alphabetically instead. 

![image](https://github.com/supabase/supabase/assets/113853868/f7d92a6d-34fe-46b5-b5f5-68917eeeeba9)
