### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by aimagination-dev** [supabase/supabase#20153]
# Keep getting this error with supabase even with latest dependencies installed

../node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
../node_modules/node-gyp-build/index.js
../node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/sender.js
./node_modules/ws/wrapper.mjs
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/auth-helpers-shared/dist/index.mjs
./node_modules/@supabase/auth-helpers-nextjs/dist/index.js

  "dependencies": {
    "@supabase/auth-helpers-nextjs": "^0.8.7",
    "@supabase/auth-ui-react": "^0.4.6",
    "@supabase/auth-ui-shared": "^0.1.8",
    "@supabase/realtime-js": "^2.9.1",
    "@supabase/supabase-js": "^2.39.2",

**Comment by GaryAustin1** [comment]
You might be better off asking this in discussions or Supabase Discord.  
Issues is mainly for reporting bugs/documentation and not clear you have a bug or just doing something wrong.
I don't use next.js though so can't help.

**Comment by encima** [comment]
@aimagination-dev can you provide a minimal working example and the setup steps you followed please? Also, what system are you running this on and how are the packages installed (npm, npx etc)?

**Comment by aimagination-dev** [comment]
@encima thanks for responding. I simply created a next js app with supabase using CLI "npx create-next-app -e with-supabase" and execute "npm run dev" to get the error. This was not the case couple of months ago.
Issue is reported by multiple folks. See one discussion below. I tried number of proposals but nothing helped me so far. 
https://github.com/supabase/realtime-js/issues/265#issuecomment-1820546931

If I clone another repo below then on the same macOS machine, I do not see any error. 
https://github.com/supabase-community/chatgpt-your-files

**Comment by nbarrow-inspire-labs** [comment]
I can confirm that I'm experiencing this issue with Next.js as well:
Next.js: 14.0.4
Supabase-js: 
```
    "@supabase/ssr": "^0.0.10",
    "@supabase/supabase-js": "^2.38.4",
```

**Comment by nbarrow-inspire-labs** [comment]
I opened this specifically under the @supabase/supabase-js repo for better visibility and issue tracking: https://github.com/supabase/supabase-js/issues/941.

**Comment by encima** [comment]
Thanks, @nbarrow-inspire-labs, as this issue is already open here, I will close the new one to focus the discussion.

I can also confirm that `npx create-next-app -e with-supabase` works on an m1 mac and an x86 linux pc with the packages you provided so I have a feeling this might be an issue with an IDE/linter/formatter.

1. Can you confirm this happens with `npx create-next-app -e with-supabase` from a terminal (not from the integrated terminal in vscode for example) and `npm run dev` is run without opening any files?

**Comment by aimagination-dev** [comment]
@encima I just tried the same from terminal outside VScode but still same error

npx create-next-app -e with-supabase
npm run dev

   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 2.7s
 ✓ Compiled /middleware in 311ms (133 modules)
 ○ Compiling / ...
 ⚠ ../node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
../node_modules/node-gyp-build/index.js
../node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/wrapper.mjs
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/ssr/dist/index.mjs
./utils/supabase/server.ts
./app/page.tsx

**Comment by encima** [comment]
thanks for trying it!

what OS are you running? and the node version also please (just in case!)

**Comment by aimagination-dev** [comment]
I am on MacOS 13.4 and node v20.4.0

**Comment by aimagination-dev** [comment]
Also tried with MacOS 14.2.1 but same error

**Comment by aimagination-dev** [comment]
@encima is this a critical error or can it be ignored?

**Comment by encima** [comment]
@aimagination-dev unsure without being able to reproduce. It looks like it will affect functionality of your app so it is right here with the messaging. 
Will try next week to reproduce.

**Comment by aimagination-dev** [comment]
@encima FYI: I just tried "npx create-next-app -e with-supabase" on my second Mac and do not see the error so something is really playing on my first Mac machine. Is there a way to clean up the machine?

**Comment by aimagination-dev** [comment]
Ok I managed to cleanup node and reinstall, error is gone. Looks like something was hanging with node

**Comment by nbarrow-inspire-labs** [comment]
@aimagination-dev can I ask how you solved it? I tried deleting my node_modules folder and .next folder but that didn't do it.

**Comment by aimagination-dev** [comment]
@nbarrow-inspire-labs if you are on MacOS simply do following to uninstall node
1. brew uninstall node
2. brew cleanup
If you still see version when doing "node -v" then check the path where your node (which node) and run sudo rm -rf 'path'. 

After cleanup reinstall node with brew install node
