### ISSUE TITLE
README.ko.md update

### ISSUE THREAD

**Issue by meengi07** [supabase/supabase#20165]
# Improve documentation

[## Link ](https://github.com/supabase/supabase/blob/master/i18n/README.ko.md)

Add a link to the page which needs improvement (if relevant)

Document is not latest version, 

Is the documentation missing? Or is it confusing? Why is it confusing?

AI + Vector/Embedding docs link is missing,
release status is not correct, 
and Badges is missing.

A clear and concise description of the improvement.

<img width="341" alt="스크린샷 2024-01-05 오전 12 32 47" src="https://github.com/supabase/supabase/assets/83638209/0cc6edb5-e91a-48b0-a44c-54eb9e30be02">
For example, this pickture is AI + Vector/Embedding docs link and text is missing

Add any other context or screenshots that help clarify your question.

**Comment by meengi07** [comment]
i have a problem.

remote: Permission to supabase/supabase.git denied to meengi07.
fatal: unable to access 'https://github.com/supabase/supabase.git/': The requested URL returned error: 403

how to push on my commit?

**Comment by charislam** [comment]
Hi @meengi07, are you trying to push directly from a branch of this repo? You'll need to fork the repo and make a PR from your fork

**Comment by meengi07** [comment]
> 안녕 @meengi07, 이 저장소의 분기에서 직접 푸시하려고 하시나요? 저장소를 포크하고 포크에서 PR을 만들어야 합니다.

thank you ! I solved the problem.
