### ISSUE TITLE
Autoformat for query text area fails on some operators

### ISSUE THREAD

**Issue by andreivreja** [supabase/supabase#2017]
# Bug report

## Describe the bug

Auto formatting (ALT+SHIFT+F) in the query builder (`project/PROJECT_ID/editor/sql`) wrongly formats some operators such as: `||`, `@>` and the likes. It's kinda rendering the feature useless if you're using these operators in a query.

## To Reproduce

Type the following query and try auto formatting

`SELECT * FROM foo WHERE bar @>'[{"id":2}]'`

## Expected behavior

Such operators shouldn't be split by a whitespace upon auto formatting.

**Comment by awalias** [comment]
hey @andreivreja, thanks a ton for the report! we'll take a look at what formatter is being used here and why it's incorrectly formatting these operators

**Comment by phamhieu** [comment]
Hi @andreivreja, I update the formatter to support more PostgreSQL operators. Let me know if you are still facing the issue.

**Comment by kiwicopple** [comment]
I'll close this for now, but if @andreivreja reports back any other errors we can reopen 👍
