### ISSUE TITLE
Modifying Enumerated Types Doesn't Reset the List

### ISSUE THREAD

**Issue by Angus-Moore-Dev** [supabase/supabase#20193]
# Bug report

## Describe the bug

When making changes to enumerated types, if you go to add a type, then don't type anything in and close it, then open it again and add another type, it will keep adding one more additional  *phantom* entry in, until you refresh. These phantom entries are also disabled, meaning I cannot edit them or delete them.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the Supabase Studio
2. Go to Databases
3. Go To Enumerated Types
4. Add a new type, but don't type anything in
5. Close the side panel
6. Open the same type again
7. Add a new type, it will spawn a phantom, un-editable type above it.

## Expected behavior

A single new type input field appears, not a rolling phantom list that increases based on the number of times you do it.

## Screenshots
Here are screenshots demonstrating the bug, replicating the steps 3 times to demonstrate the growing pattern.
![first picture](https://github.com/supabase/supabase/assets/99398403/af48a6c5-7e80-4ceb-b1bf-0bc25f2d62e1)
![second picture](https://github.com/supabase/supabase/assets/99398403/752ecfa5-a378-43b8-8503-75bceb68cc08)
![third picture](https://github.com/supabase/supabase/assets/99398403/8cc864f1-24e0-4bdb-bd8c-aa053811ee74)

## System information

- OS: Windows
- Browser Chromium

## Additional context
So within the app, there's the use of react-hook-form, which manages the list of enumerated types that are displayed, the editing of those types and deletion (and subsequent confirmation).
[Here's the file that manages the actual editing window for those changes](https://github.com/supabase/supabase/blob/master/apps/studio/components/interfaces/Database/EnumeratedTypes/EditEnumeratedTypeSidePanel.tsx#L39)

I have no knowledge of react-hook-form, but my guess is that when closing the sidebar, there is no form reset occurring to actually discard the empty ones, or there's a bug with tracking how many enumerated types to map out. I also ran into serious issues getting the Studio loaded on my machine (Windows Pro for Workstations doesn't seem to play well with Visual Studio build tools...).

Hopefully that has lead you close enough to the issue that it's clear what the actual problem is!

**Comment by lokeshvasnik** [comment]
I would like to work on this issue.

**Comment by tranhoangvuit** [comment]
Hi @lokeshvasnik , are you still working on this issue? If not, please let me know, and I will work on it.

**Comment by lokeshvasnik** [comment]
i have fixed the issue and raised a pr

**Comment by saltcod** [comment]
Thanks @lokeshvasnik — I see 2 commits, but no changes in your PR
<img width="721" alt="screenshot-2024-01-08-at-11 16 56" src="https://github.com/supabase/supabase/assets/105593/793f4aed-024f-4162-9000-ab25e5c80413">

**Comment by lokeshvasnik** [comment]
https://github.com/supabase/supabase/pull/20209/commits/2d1d9feb132c5335586dcf91403ae19e5e2bde51

Should i create a new pr

**Comment by saltcod** [comment]
Yeah maybe just paste that into a new PR @lokeshvasnik

**Comment by lokeshvasnik** [comment]
Make a new PR - fix Enumerated Types Doesn't Reset the List #20240

**Comment by encima** [comment]
Thanks for doing this, @lokeshvasnik, closing!
