### ISSUE TITLE
Rename/Delete query missing from query editor 

### ISSUE THREAD

**Issue by erkan80898** [supabase/supabase#20208]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

For one of my organizations, I have lost the ability to Delete/Rename my queries under the SQL Editor. The only options I have are "share query" and "download as migration file". This particular issue is only happening on one of my organization. It is happening regardless of the browser (tested on chrome and safari). However, another organization of mine is not having this issue. I am the owner of both.

<img width="255" alt="Screen Shot 2024-01-05 at 11 06 45 PM" src="https://github.com/supabase/supabase/assets/32151823/4c7b5b15-8afd-470a-83ae-a996db4e377e">

## To Reproduce

I can't say how this can be reproduced, given my _other_ organization is not having this issue. As follows: 
<img width="297" alt="Screen Shot 2024-01-05 at 11 32 00 PM" src="https://github.com/supabase/supabase/assets/32151823/5b122adc-7c58-42e1-879c-32f61cef5416">

## Expected behavior

I expect the rename and delete options to be there for all the queries under the "Your queries" in the SQL editor.

## System information

- OS: [linux, macOS, Windows]
- Browsers: Chrome, Safari

## Additional context

Both the organizations are hosted through the Supabase instance.

**Comment by nokia6290** [comment]
is this self-hosted?

I've setup my self-host supabase and dont see any options to edit/share/delete the query at all. If the query is bad I cannot even open it (directs to error page)

**Comment by erkan80898** [comment]
@nokia6290 No, its hosted on the supabase instance

**Comment by tranhoangvuit** [comment]
Hi @erkan80898, does it still happen? It's working fine on my Supabase instance. Is there anything special about your configuration or your query? If possible, could you take a full screenshot of your query and the dropdown menu?

**Comment by JulienLecoq** [comment]
@erkan80898 I confirm, I have the same issue in my instance hosted by Supabase.

**Comment by JulienLecoq** [comment]
@tranhoangvuit  the problem happens on every new query that you create from the SQL editor. Old queries created before a given date (I don't know which one) can be renamed.

**Comment by JulienLecoq** [comment]
@erkan80898 I hope this can be fixed quickly because I name all my queries manually to search for them later on, this is annoying :/

My queries from 2-3 weeks seems fine on my side. I can rename them.

**Comment by saltcod** [comment]
Is this a shared query? You can't delete queries you didn't create. Only the creator can delete them.

**Comment by erkan80898** [comment]
@saltcod No, it is not.

**Comment by JulienLecoq** [comment]
@saltcod Same, it’s not shared queries. That’s queries I created myself.

**Comment by erkan80898** [comment]
@JulienLecoq quick question, do you have users outside of where u created ur orgz from login to the account. Something like a foreign virtual assistant, or maybe through a vpn

**Comment by JulienLecoq** [comment]
@erkan80898 No none of that

**Comment by jgerard** [comment]
I just noticed this issue for me as well, I had the page open since yesterday. However, I did a refresh of the SQL Editor page and Rename and Delete options came back. 

It seems when a new query is created, rename and delete are not in the dropdown for it, but refreshing the page seems to make them appear.

**Comment by erkan80898** [comment]
@jgerard That used to not be the case, seems like some work is being done on it right now - thankfully.

**Comment by saltcod** [comment]
Hi all — a fix for this went out yesterday. Please report back if you still experience issues here. Thanks for the reports!

**Comment by devrobbey** [comment]
Happened to me now too - not for the first time. Supabase hosted. 
Query gone when opening it in the supabase dashboard. 
Could it have something to do with closing tabs where the query is edited inside? Is the it saved regularly or when modifying it?

**Comment by zajcomm** [comment]
just happened to me too.. cant delete queries or rename them
<img width="374" alt="image" src="https://github.com/user-attachments/assets/ac11802b-b026-4048-9a02-7a48e9051580">

**Comment by tyler6204** [comment]
Same thing here. All of a sudden...

![Screenshot 2024-10-09 at 4 40 16 PM](https://github.com/user-attachments/assets/351cfd46-1347-40ee-82ea-efe63dd01ee1)

**Comment by sidwarkd** [comment]
When I right click on a query I just get the native browser menu, no option to rename or delete.
