### ISSUE TITLE
storage RLS rejects on local. but not on remote server

### ISSUE THREAD

**Issue by matart15** [supabase/supabase#20214]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I get this error on local file upload `supabase_storage_admin@postgres ERROR:  new row violates row-level security policy for table "objects"`
Exact same code works just by changing .env to supabase.com remote server

## To Reproduce

1. create new project
2. create react native app
3. implement upload

## Expected behavior

- Storage can upload image on local
- OR Add Feature to Test + Debug Row Level Security Policies https://github.com/orgs/supabase/discussions/12269

## Screenshots

Exact same RLS. look at Browser url

![Screenshot 2024-01-07 at 0 24 38](https://github.com/supabase/supabase/assets/17027219/3b540350-847f-45de-8a08-287d9360f4e0)

![Screenshot 2024-01-07 at 0 25 28](https://github.com/supabase/supabase/assets/17027219/e5e81b36-d3c5-4e6f-9f02-7cf5efc8f87f)

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js:  "@supabase/supabase-js": "2.38.4",
- cli version : 1.106.1

## Additional context

- I tried removing RLS, chaing it into simply `(bucket_id = 'staff_public'::text)`. neither helps
- tried looking at supabase docker logs but it was not very helpful

```sh
docker ps -q | xargs -L 1 -P `docker ps | wc -l` docker logs --since 30s -f


2024/01/06 15:17:14 [warn] 1111#0: *13138 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/000000002
0, client: 192.168.65.1, server: kong, request: "POST /storage/v1/object/staff_public/7a0f01e4-1b8f-47ef-b2bb-c47ae1b3773c/staff_image/ce0
f469a-a7cc-4189-9ed5-505925aa2a90.jpg HTTP/1.1", host: "192.168.86.169:54321"
172.20.0.4 2024-01-06 15:17:14.734 UTC [4957] supabase_storage_admin@postgres ERROR:  new row violates row-level security policy for table
 "objects"
172.20.0.4 2024-01-06 15:17:14.734 UTC [4957] supabase_storage_admin@postgres STATEMENT:  insert into "objects" ("bucket_id", "metadata",
"name", "owner", "owner_id", "version") values ($1, DEFAULT, $2, $3, $4, $5) on conflict ("name", "bucket_id") do update set "version" = $
6,"owner" = $7,"owner_id" = $8 returning *
192.168.65.1 - - [06/Jan/2024:15:17:14 +0000] "POST /storage/v1/object/staff_public/7a0f01e4-1b8f-47ef-b2bb-c47ae1b3773c/staff_image/ce0f4
69a-a7cc-4189-9ed5-505925aa2a90.jpg HTTP/1.1" 400 98 "-" "Expo/2.29.6 CFNetwork/1474 Darwin/23.1.0"
{"level":30,"time":"2024-01-06T15:17:14.735Z","pid":1,"hostname":"8af2c8808fbc","reqId":"req-9h","tenantId":"stub","project":"stub","reqId
":"req-9h","type":"request","req":{"traceId":"req-9h","method":"POST","url":"/object/staff_public/7a0f01e4-1b8f-47ef-b2bb-c47ae1b3773c/sta
ff_image/ce0f469a-a7cc-4189-9ed5-505925aa2a90.jpg","headers":{"host":"supabase_storage_mykone:5000","x_forwarded_proto":"http","x_forwarde
d_host":"192.168.86.169","x_forwarded_port":"8000","x_real_ip":"192.168.65.1","content_length":"213759","x_upsert":"true","accept":"*/*","
content_type":"multipart/form-data; boundary=j.w-j_PFxqND6ydiKbodhfS5_CXsL4rrnKoS_hU1akXE_P5P3hf4DwBQH0zPN-GHfUh3Gm","user_agent":"Expo/2.
29.6 CFNetwork/1474 Darwin/23.1.0","x_client_info":"supabase-js-react-native/2.38.4"},"hostname":"supabase_storage_mykone:5000","remoteAdd
ress":"172.20.0.2","remotePort":36392},"res":{"statusCode":400,"headers":{"content_type":"application/json; charset=utf-8","content_length
":"98"}},"responseTime":29.38382500037551,"error":{"raw":"{\"statusCode\":403,\"error\":\"Unauthorized\",\"originalError\":{\"length\":130
,\"name\":\"error\",\"severity\":\"ERROR\",\"code\":\"42501\",\"file\":\"execMain.c\",\"line\":\"2143\",\"routine\":\"ExecWithCheckOptions
\"}}","name":"Error","message":"new row violates row-level security policy","stack":"Error: new row violates row-level security policy\n
  at DBError.fromDBError (/app/dist/storage/database/knex.js:443:16)\n    at Function.<anonymous> (/app/dist/storage/database/knex.js:25:3
9)\n    at Object.onceWrapper (node:events:632:26)\n    at Function.emit (node:events:517:28)\n    at Function.emit (node:domain:489:12)\n
    at Client_PG.<anonymous> (/app/node_modules/knex/lib/knex-builder/make-knex.js:299:10)\n    at Client_PG.emit (node:events:529:35)\n
  at Client_PG.emit (node:domain:489:12)\n    at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12\n    at process.
processTicksAndRejections (node:internal/process/task_queues:95:5)"},"owner":"7a0f01e4-1b8f-47ef-b2bb-c47ae1b3773c","msg":"stub | POST | 4
00 | 172.20.0.2 | req-9h | /object/staff_public/7a0f01e4-1b8f-47ef-b2bb-c47ae1b3773c/staff_image/ce0f469a-a7cc-4189-9ed5-505925aa2a90.jpg
| Expo/2.29.6 CFNetwork/1474 Darwin/23.1.0"}

```

Any Idea how to debug this?

**Comment by encima** [comment]
Hi @matart15 
we have information on debugging and testing RLS at the base of the [docs page](https://supabase.com/docs/guides/auth/row-level-security) if that helps.

To debug further, it might be worth confirming all casts work as expected and all paths are being formatted similarly. I.e. 
1. first add a policy to just confirm authenticated users can access all folders in the bucket
2. then hardcode the folder to match the user's uuid
3. then check the matching folder name

**Comment by matart15** [comment]
@encima 
Thank you I will try debugging

**Comment by encima** [comment]
Hi @matart15 
did you get any additional information for this issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
