### ISSUE TITLE
Expo Installation Documentation Link Misdirects to Incorrect GitHub Page

### ISSUE THREAD

**Issue by yossydev** [supabase/supabase#20228]
# Improve documentation

## Link 

[Login with Google](https://supabase.com/docs/guides/auth/social-login/auth-google?platform=react-native#using-native-sign-in-with-google-in-expo)

## Describe the problem

I don't think the link to [Expo installation docs](https://github.com/react-native-google-signin/google-signin#expo-installation) is appropriate. When I click the link, it redirects me to the [github](https://github.com/react-native-google-signin/google-signin) repository instead of the actual Expo installation documentation.

## Describe the improvement

Shouldn't it correctly direct to https://react-native-google-signin.github.io/docs/setting-up/expo?

## Additional context

**Comment by cmjw** [comment]
Hello- mind if I tackle this one as a first contribution to the project?
