### ISSUE TITLE
Supavisor Launch - Docs Update

### ISSUE THREAD

**Issue by encima** [supabase/supabase#20233]
# Improve documentation

Remove/update mentions of `pgbouncer` with `supavisor` for the upcoming switchover on Jan 15th

## Links, mentioned in

* [ ] apps/docs/pages/guides/database/connecting-to-postgres.mdx
* [ ] apps/docs/pages/guides/getting-started/architecture.mdx
* [ ] apps/docs/pages/guides/getting-started/quickstarts/redwoodjs.mdx
* [ ] apps/docs/pages/guides/platform/custom-postgres-config.mdx
* [ ] apps/docs/pages/guides/platform/network-restrictions.mdx
* [ ] apps/docs/pages/guides/platform/performance.mdx
* [ ] apps/docs/pages/guides/platform/ssl-enforcement.mdx
* [ ] apps/docs/pages/guides/platform/oauth-apps/oauth-scopes.mdx

## Describe the problem

Supavisor has been in public beta for a few months now and the official switchover date is Jan 15th 2024, when all projects will be using Supavisor as the default pooler

## Describe the improvement

This issue covers mentions of `pgbouncer` and the corresponding PR should update them to be accurate in their context

**Comment by ankiiisharma** [comment]
@encima Could you please assign the documentation update task to me? I'm ready to work on it.
