### ISSUE TITLE
Default Value for json columns does not save

### ISSUE THREAD

**Issue by gabrielsestrem** [supabase/supabase#2024]
# Bug report

## Describe the bug

Default value for Json type columns does not save. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Table editor
2. Click on any table
3. Add new column to this table
4. Type: Json
5. Set Default Value to any json format: ["Reason1", "Reason2"]
6. Save
7. Edit the new column
8. Default Value are empty 

## Expected behavior

A default value should persist in the column settings after saving

## Screenshots

![image](https://user-images.githubusercontent.com/26584189/122693510-433a1100-d28e-11eb-9e97-9573627155a5.png)

**Comment by gabrielsestrem** [comment]
My objective was to have a list of options as a default values. But I found a workaround using text type and defining as an array.

![image](https://user-images.githubusercontent.com/26584189/122693890-c27c1480-d28f-11eb-820f-c2df1246cf33.png)

**Comment by gabrielsestrem** [comment]
It turns out that the Default Value for Json type it's being saved properly, the only problem it's that it does not show in the dialog when you edit the column. But I could see the default value appearing when creating a new record

**Comment by joshenlim** [comment]
hey there @gabrielsestrem ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
