### ISSUE TITLE
Error when trying to update row within JSON type

### ISSUE THREAD

**Issue by putheng** [supabase/supabase#2026]
# Bug report

## Describe the bug

Error when trying to update row within JSON type

## To Reproduce

1. Go to 'table editor'
2. Right-click and click on 'edit row'
3. Click save
4. go to debug console on Chrome
5. See an error and loading spinner on save button keep loading

## Screenshots

![image](https://user-images.githubusercontent.com/19757130/122722337-ca41b600-d29b-11eb-9de5-04b1bbb344d1.png)

## System information

- OS: macOS
- Browser Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by joshenlim** [comment]
hey there @putheng ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
