### ISSUE TITLE
Can't upload files to storage

### ISSUE THREAD

**Issue by aldaprojects** [supabase/supabase#20290]
## Describe the bug

It's simple. I can't upload files to any bucket. I just create a new bucket, try to upload a file and i get an Internal Server Error.

## To Reproduce

1. Go to storage
2. Create a new bucket
3. Upload a file (drop or select)
![image](https://github.com/supabase/supabase/assets/57024621/e8fffe21-2384-49cb-a959-19b65b363392)

## Expected behavior

To upload a file correctly.

## Screenshots

![image](https://github.com/supabase/supabase/assets/57024621/2d4f4344-57a9-4696-aadc-26d849ebdbd4)

## Additional context

I created a new project and it was available to upload a file.

**Comment by saltcod** [comment]
@aldaprojects has this resolved?

What comes up for your storage status on your project home page?
 
![screenshot-2024-01-10-at-11 18 57](https://github.com/supabase/supabase/assets/105593/18f2c330-64cb-47df-9853-97a503773fe1)

**Comment by aldaprojects** [comment]
> @aldaprojects has this resolved?
> 
> What comes up for your storage status on your project home page?
> 
> ![screenshot-2024-01-10-at-11 18 57](https://private-user-images.githubusercontent.com/105593/295604906-18f2c330-64cb-47df-9853-97a503773fe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDU2NzUsIm5iZiI6MTcwNDkwNTM3NSwicGF0aCI6Ii8xMDU1OTMvMjk1NjA0OTA2LTE4ZjJjMzMwLTY0Y2ItNDdkZi05ODUzLTk3YTUwMzc3M2ZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNjQ5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzIyMDE0ZTIzZjM2MDQ1ZjYzNmRkMWUzNGQ3M2VlYjA5NjNkYTI1YzM0OGNjOGUzY2VmYTMxMWRhMTY4MGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZjohlGbDsZADgY-gl6AqhLxOy7nXlc_l9le-yaMH-_o)

@saltcod Not yet. Everything seems fine but I still can't upload a file.

![image](https://github.com/supabase/supabase/assets/57024621/7069a5bf-a123-4dec-94f3-988dadb50084)

**Comment by omar-abdul** [comment]
For anyone who is also experiencing this, it probably is the name of the file, if its too long it fails, at least that was my issue
