### ISSUE TITLE
Dashboard Strugles to Understand Composite Foriegn Keys

### ISSUE THREAD

**Issue by Geobot19** [supabase/supabase#20293]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I used a composite primary key on one of my tables, but when I had to make it a foreign key in other tables, I had to edit the table in the SQL editor.
Since I did that I have had an issue with the insert row function on the dashboard where discards chosen records for foreign keys after I select them and after I manually create the record and click "view referencing record" on the column it doesn't show the record, when I check the filter, it seems to have mistaken the column I wanted for the other part of the key
I would really like to use the composite foreign keys without having to reach for the SQL Editor

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a table with a composite primary key
2. create a table referencing it with a composite foreign key (requires SQL editor)
3. attempt to insert a row using the table editor or click "view referencing record" on a created row

## Expected behavior

when I select a record on one part of the key, the other part should fill in
when I select "view referencing record" it should show me the referenced row

## System information

- Browser: Firefox

## Additional context
N/A

**Comment by joshenlim** [comment]
Hey there @Geobot19! Happy to share that we've [updated](https://github.com/supabase/supabase/pull/21078) the way the dashboard handles foreign keys and it should solve the problem that you're running into :)
