### ISSUE TITLE
Client-side exception after trying to open a table's column configuration

### ISSUE THREAD

**Issue by gianniginom** [supabase/supabase#20294]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The bug happens when I click on the small dots next to a table to modify the columns :

![Capture d'écran 2024-01-10 à 07 47 01](https://github.com/supabase/supabase/assets/89346952/83a793aa-30bf-4b7a-b6a8-d36abf7e3190)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database -> Tables
2. Click on '…' and "Edit"
3. See error

![Capture d'écran 2024-01-10 à 07 43 21](https://github.com/supabase/supabase/assets/89346952/2b4c577e-62b9-43cf-9661-146fe041a926)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by alaister** [comment]
Thanks for the report!

Fixed in https://github.com/supabase/supabase/pull/20306
