### ISSUE TITLE
Apple Auth client secret generator does not work in Safari

### ISSUE THREAD

**Issue by enyo** [supabase/supabase#20301]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/social-login/auth-apple#configuration-web

## Describe the problem

When filling out the form and trying to generate the secret, there is an error **only in Safari**:

> Data provided to an operation does not meet requirements

This has cost me quite some time, because I thought something was wrong with my keys. Switching to Chrome worked.

The issue must be in [`AppleSecretGenerator.tsx`](https://github.com/supabase/supabase/blob/master/apps/docs/components/AppleSecretGenerator.tsx)

## Describe the improvement

Obviously this should just work in Safari.

But if it's difficult to fix, there should be a **warning** that it doesn't currently work in Safari.

**Comment by KevinBrolly** [comment]
Thanks for the suggestion @enyo 

PRs for this improvement from anyone viewing very welcome.

**Comment by charislam** [comment]
closed as fixed!

**Comment by adboio** [comment]
i just had the same issue - kept getting an error "Data provided to an operation does not meet requirements"

switching to chrome solved it

why was this closed? did i miss something in the docs?
