### ISSUE TITLE
Supabase Studio's `Select all X rows` followed by `Delete x rows` deletes entire table when in impersonating role for just 1 user

### ISSUE THREAD

**Issue by jacob-8** [supabase/supabase#20327]
# Bug report

## Describe the bug

This is a nasty one. Fortunately I only have my two users in the prod database. User A had about 13K rows in my word_updates table. User B had about 445 rows. User A is my actual vocab I'd like to keep. User B is just a test user and so I wanted to clear out those 445 bogus rows. I clicked "Select all 445 rows" since there were more rows than the initial 100 showed up, then I clicked "Delete 445 rows", after which all 13K+ were gone. The entire table, including all User A's vocab items.

## To Reproduce

1. create a table with rows belonging to two different users. Get enough rows for each user to go past the default 100 page length.
2. Impersonate one of the users
3. Select all X rows
4. Delete X rows
5. Remove impersonation role and see the entire table is wiped out.

## Expected behavior

I expected only the rows for the impersonated user to be deleted (especially since the delete button gave me the exact count for that user).

## Additional context

I would encourage some more testing around the impersonation role as regards deleting. I'm not going to file a bug right now, but I also was unable to delete individual rows when in the user impersonation mode. I would select 10 (one by one) and hit the delete button to have nothing happen.

**Comment by GaryAustin1** [comment]
What is your RLS on the tables?
If you have no RLS enabled or your policy is bad then impersonation likely would be irrelevant. 
BUT that is would be a quandary for the purpose of the role impersonation as it does not know anything about the underlying data unless the RLS is correct.  So if Supabase protects you from that case then impersonation is not working as the real case would.   Interesting....

**Comment by jacob-8** [comment]
> What is your RLS on the tables?

Users can only add and view their own. No delete option. So that explains why the delete didn't work for selecting just a couple. Some sort of UI feedback would have been nice in that case. But that doesn't explain my main bug, why selecting all 400+ of User B's rows would nuke the other users' data.

Here's my sql:

```sql
CREATE TABLE word_updates (
  id bigint primary key generated by default as identity,
  word text not null,
  "language" language not null,
  "status" int not null,
  views int not null,
  created_by uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE word_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users can add word updates"
ON word_updates FOR INSERT
TO authenticated
WITH CHECK ( auth.uid() = created_by );

CREATE POLICY "users can view status of their own words"
ON word_updates FOR SELECT
TO authenticated
USING ( auth.uid() = created_by );
```

**Comment by saltcod** [comment]
Thanks @jacob-8 investigating right now.

**Comment by saltcod** [comment]
Hi @jacob-8 thanks so much for the report on this one. We've just deployed a fix — should be out in the next few minutes. Please let us know if you spot anything else with this!
