### ISSUE TITLE
typo in CI github action code

### ISSUE THREAD

**Issue by fvermaut** [supabase/supabase#20322]
# Improve documentation

## Link 

https://supabase.com/docs/guides/cli/managing-environments

## Describe the problem

There's a missing "!" in the if expression or the "ci.yaml" github action code, highlighted below.  

<img width="969" alt="image" src="https://github.com/supabase/supabase/assets/43007270/94b115df-c0a6-4ef1-aaec-5b496f5ab915">

It should be:

`          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then`

As on [the example repo](https://github.com/supabase/supabase-action-example/blob/main/.github/workflows/ci.yaml).

**Comment by KhalidObaide** [comment]
Quick fix with this PR #20324 ( under review )
