### ISSUE TITLE
Magic Link sign-up is case sensitive

### ISSUE THREAD

**Issue by christiancito** [supabase/supabase#2034]
# Bug report

## Describe the bug

Signing up with the same email with different case variants causes Supabase to create 2 different user accounts. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add a user in any way via email (example: christian.cito@arthouse.is)
2. Add the same email with in different case (example: chRiSTIAn.cIto@arthouse.is)
3. 2 different users get created. I observed this via magic link sign up and when inviting users

## Expected behavior

Supabase should detect that the same email in different case belongs to the same user.

## Screenshots

<img width="1456" alt="LWScreenShot 2021-06-21 at 22 52 05" src="https://user-images.githubusercontent.com/30470476/122827361-86bf6a00-d2e4-11eb-9f8e-d60f76b75079.png">

## System information

- OS: macOS
- Browser Chrome

Thank your for your time!

**Comment by kiwicopple** [comment]
Hey @christiancito ! We're tracking this one here: https://github.com/supabase/gotrue/issues/89

Thanks for reporting this one - if you think it's unrelated to the bug above just let me know and I'll reopen
