### ISSUE TITLE
"http_request does not exist" Error in Tutorial

### ISSUE THREAD

**Issue by jayjay300** [supabase/supabase#20412]
## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-react

## Describe the problem
Apologies if I am doing something wrong myself, but working with this tutorial, everything works perfect, except if I enable the trigger that is built towards the end. If I run,  I get the error "http_request does not exist". I have tried possible solutions for all mentions of this, adding extensions to search path in both dashboard and function, enabling the http library, no dice!

## Describe the improvement

Is this a bug in the provided code or am I missing something?
If this is an issue with documentation, any ideas on a better implementation of that trigger?

**Comment by encima** [comment]
Thanks for opening, the section just before the trigger mentions enabling the 'http' extension to use that functionality. 
See the link here to enable it: https://supabase.com/dashboard/project/_/database/extensions

**Comment by jayjay300** [comment]
As mentioned above I confirmed I have HTTP enabled and the issue persists.

**Comment by encima** [comment]
@jayjay300 thanks for clarifying. Is this an issue with triggers only or do queries in the dashboard also fail to run?

**Comment by jayjay300** [comment]
It is with this specific trigger. All functionality of my database including other triggers I have in place are working as expected, however this demonstration code in the tutorial, when implemented in the DB, is not working.

Are you able to utilize that code in a demo project and confirm it works out of the box?

The issue I am running into is I do not believe that the error I am running into is actually correlated to that library (it may be, but unsure). I have noticed in other instances that the error message listed above tends to be a bit of a "catch all", where if anything fails the error incorrectly points to that library being the culprit. Again I may be incorrect there, but I spent a fair amount of time debugging this on my own and really came up empty handed when trying to pinpoint the root of the issue.

**Comment by jayjay300** [comment]
I took some more time tonight and figured it out-- for whatever reason my http extension ended up in my public schema and not the extensions schema the boilerplate code assumes it is found it. I must've installed it in public without checking. updating the references solved my issue. appreciate the help sorry for being annoying! :)

**Comment by encima** [comment]
@jayjay300 no apologies needed, thank you for following up with the resolution!
