### ISSUE TITLE
Issue with Supabase and StreamBuilder in Flutter

### ISSUE THREAD

**Issue by elbeekk** [supabase/supabase#20410]
### Discussed in https://github.com/orgs/supabase/discussions/20409

<div type='discussions-op-text'>

<sup>Originally posted by **elbeekk** January 14, 2024</sup>
My stream builder in Flutter not working properly, it listening data only one time, when widget tree is built, like a Future builder in flutter, I DO    NOT want Stream builder works as a Future builder, and i have seen previous discussions, that one guy enabled realtime after creating table, and he tried to delete table, and create new one with enabling realtime, and it worked fine for him, but in my case it is not helping.

I am using these VERSIONS:
supabase_flutter: ^2.2.0
flutter: 3.16.4

please do not ask any questions like  build.gradle, pubspec.yaml, info.plist and etc. files, all of them are working fine.

![photo_2024-01-14_02-22-40](https://github.com/supabase/supabase/assets/121304208/4ed09c3f-3dc5-49f2-828a-5cfbdfec4885)

I am printing the word 'chat stream is going on' to know, how many times it rebuilding UI and in terminal it is printing it once only, it means that stream builder is getting data from database only once when it built

I do not want building my Flutter app with subscribing to any channels, that supabase's features, I just want simple app with stream builder, and i do not want to rebuild my UI with Timer.

Developers of Supabase please fix this issue or give me a solution.

Please help me with this issue,</div>

**Comment by KevinBrolly** [comment]
Hey @elbeekk Github Issues are only for bugs/issues with Supabase itself, rather than issues with your application. The best place to get help is from the discussion you have already opened. I am going to close this issue in favour of the discussion.

**Comment by elbeekk** [comment]
> Hey @elbeekk Github Issues are only for bugs/issues with Supabase itself, rather than issues with your application. The best place to get help is from the discussion you have already opened. I am going to close this issue in favour of the discussion.

Ok
