### ISSUE TITLE
Supabase Pricing Question - Egres size

### ISSUE THREAD

**Issue by aaronlugo** [supabase/supabase#20464]
Hello, I have a small project and for some reason the Egres is extremely high, does anyone know why is this happening, my data base size is pretty small.
<img width="626" alt="Screenshot 2024-01-15 at 20 47 28" src="https://github.com/supabase/supabase/assets/24878290/fe080856-9873-4f65-b997-dc2bf641761c">

<img width="1044" alt="Screenshot 2024-01-15 at 20 47 47" src="https://github.com/supabase/supabase/assets/24878290/08707aa7-388c-4257-8397-bf4cbf095acb">

Thanks

**Comment by encima** [comment]
Hi @aaronlugo 
- This is more of a support issue, could you please open a [Support Ticket](https://supabase.com/support)
- Please check the [logs](https://supabase.com/docs/guides/platform/logs) section of the dashboard to get more insight into the usage pattern
