### ISSUE TITLE
Queries with periods (.) in the where clause do not return results

### ISSUE THREAD

**Issue by deividfernando** [supabase/supabase#20481]
### Discussed in https://github.com/orgs/supabase/discussions/20462

<div type='discussions-op-text'>

<sup>Originally posted by **deividfernando** January 15, 2024</sup>
Hello everybody!

I'm trying to do some queries, but I noticed that when the string has a . it doesn't return any results to me. How can I proceed?

I'm using python. Here's an example:

response = supabase.table('users').select('senha').eq('login', 'deivid.fernando').execute() # returns empty
response = supabase.table('users').select('senha').eq('login', 'deivid').execute() # returns values

I have both values on my table.

Thanks!!</div>

**Comment by encima** [comment]
Hello @deividfernando ,

Thanks for opening the Issue. In the future, please keep to either a Discussion OR an Issue. Doing both adds noise and makes it a bit harder to help and search for answers. 
Of course, you can always open an Issue if someone recommends it from a Discussion but it is best to wait for answers in the Discussion before opening here 🙏 

As for the issue, could you provide:
- Python client version
- System info (Unix, Windows etc)
- The API call made by the client (printed in the terminal usually)
- Is this consistent across all tables for records with a period?

Tested the library on OSX and Debian but I was unable to reproduce. Thanks!

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
