### ISSUE TITLE
Unable to resend code during password recovery process

### ISSUE THREAD

**Issue by mtalha101** [supabase/supabase#20485]
# Bug report

## Describe the bug

I am trying to enable user to resend the otp to their email address if they didn't receive it on the first attempt. The error I get when I try to resend the otp is `'package:gotrue/src/gotrue_client.dart': Failed assertion: line 561 pos 14: '[OtpType.signup, OtpType.emailChange].contains(type)': email must be provided for type recovery`. The problem is that, the OtpType that I'm using is `OtpType.recovery` and the assert statement doesn't acknowledge that.

## To Reproduce

You can use this code to reproduce the error:
```
Future<bool> resendOtp(String email) async {
    try {
      await sc.auth.resend(
        email: email,
        type: OtpType.recovery,
      );
      return true;
    } catch (e, s) {
      debugPrint("resendOtp: ${e.toString()}");
      return false;
    }
  }
```

## System information

- OS: iOS 16.4
- Version of supabase_flutter: ^2.0.2
- Flutter SDK: 3.16.4

**Comment by Hallidayo** [comment]
Hi @mtalha101 - Just checking are you still having this issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
