### ISSUE TITLE
Policy editor tries to create Insert policies with both USING and WITH CHECK clauses

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#2054]
# Bug report

## Describe the bug

In the policy editor, clicking on the `Insert` radio button switches the policy details box from editing the `USING` part of the statement to editing the `WITH CHECK` part. However, if you fill the form out from top to bottom, you will enter data into the text box before clicking on the radio button to select the action.

The behavior seems strange because clicking on the `Insert` radio button causes the text in the above text area to disappear, but then creating the policy also fails because the editor still tries to create the policy with the `USING` statement entered before `Insert` was selected.

## To Reproduce

1. Go to Authentication > Policies
2. Create a new policy
3. Type a policy into the editor (can be as simple as `false`)
4. Select the Insert option (and notice how the policy disappears)
5. Type the policy into the editor again
6. Click Review and then Save Policy

## Expected behavior

Either the user should select the action (`Insert`, `Select`, etc) before writing the details of the policy, or the details of the policy should be automatically applied to the correct part of the statement (`USING` vs `WITH CHECK`), depending on the radio button the user selects.

**Comment by kiwicopple** [comment]
Great feedback @emschwartz - we'll reorder this in the next 1/2 days
