### ISSUE TITLE
[typescript] Querying referenced table with count creates a `SelectQueryError` type error

### ISSUE THREAD

**Issue by f-elix** [supabase/supabase#20562]
## Describe the bug

Using the JavaScript Client Library with Typescript, a query like the following:

```ts
await supabase
  .from('countries')
  .select(`*, cities(count)`)
```

provokes a type error because the inferred type for `cities` is 

```ts
SelectQueryError<"Referencing missing column `count`">[] | undefined
```

The query returns the expected count, but Typescript is not aware of it.

## Expected behavior

The inferred type should be the count object returned from the query.

## System information

- OS: macOs
- Version of supabase-js: 2.39.3
- Version of Node.js: 20.6.0

**Comment by burggraf** [comment]
Do you have the proper FK relationship set up between countries and cities?

**Comment by f-elix** [comment]
Yes. I took the `countries` and `cities` from the docs examples, but my case is very similar. I have a table called `Album` and a table called `Media`. An album can have many media, but a media can only have one album, so I set up a FK relationship on the `Media` table, which is the album id. 

The type error occurs with my album query. 

This is what I do:

```ts
supabase.from('album').select(`
	id,
	date,
	title,
	description,
	media(
		id,
		type,
		filename,
		cloudinaryId,
		caption,
		width,
		height
	),
	mediaCount:media(count)
` );
``` 

At runtime, everything works fine, I get all the media fields and the `mediaCount`, as expected, but TS complains because the type generated for `mediaCount` is what I wrote in my previous comment:

```ts
SelectQueryError<"Referencing missing column `count`">[] | undefined
```

Does that make sense to you?

**Comment by encima** [comment]
Closing in favour of [existing issue in postgres-js repo](https://github.com/supabase/postgrest-js/issues/447). Linked open PR to this issue.

**Comment by kstolk** [comment]
This seems to be fixed on their repo. But I still have the same issue in mine.. I'm using their latest version (1.30.0 right now). Generated the types and still has the error saying 
SelectQueryError<"Referencing missing column `name`">[];

Even though the foreign key is existing and the object contains the name key and value correctly.

**Comment by hkleine** [comment]
Running into the same issue. Got the relation set up and the actual data that comes back also includes the proper count value. Yet the generated Type is SelectQueryError.
