### ISSUE TITLE
Uuid needs confirmation before change

### ISSUE THREAD

**Issue by mationai** [supabase/supabase#20598]
# Chore

## Describe the chore

Currently uuid is updated in the UI with a double click or click on the chevron icon to bring up the selection table and then just a simple click to make the selection without any confirmation. This is a poor design choice for the following reasons:

- the initial double click to bring up the selection table can trigger a click on the selection table, selecting the first one on the table without confirmation. This has happened to me 2 or more times.
- the action can not be undo.
- something as powerful as assigning the uuid to a different uuid needs confirmation, especially that without an undo.
- this is a big security concern due to the sessions table and other security related user tables using this UI functionality.
- Without confirmation or undo, the mistaken can not be reverted unless the admin remembers or knows the previous uuid value.

**Comment by GaryAustin1** [comment]
It might help if you explained a bit more on where you are doing this and show an example.

You don't have access to change the auth schema at all.  On public tables a uuid columns could be used for lots of things.  Also not sure why uuid is more critical than say an integer value used for a column.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
