### ISSUE TITLE
Cannot type in Policy Description input

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#206]
# Bug report

## Describe the bug

When focusing on the description input it automatically changes to the second input. 

## GIF

![Kapture 2020-09-19 at 14 11 59](https://user-images.githubusercontent.com/6392501/93686144-43e51300-fa82-11ea-94c3-46426e746955.gif)

**Comment by kiwicopple** [comment]
Ah we have a bug in our code editor - I'll release the fix today @zlwaterfield. Thanks for the headsup

**Comment by kiwicopple** [comment]
Shipped! 🚢
