### ISSUE TITLE
InvalidWorkerCreation due to missing /home/deno/functions mount

### ISSUE THREAD

**Issue by paolieri** [supabase/supabase#20602]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When following the [quickstart](https://supabase.com/docs/guides/functions/quickstart) on edge functions, functions are not served locally because their directory is not mounted in the `edge` Docker container.

## To Reproduce

```
$ mkdir hello
$ cd hello
hello$ supabase init
hello$ supabase functions new hello-world
hello$ supabase start
hello$ supabase functions serve
```

Then, trying to access the function:

```
$   curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/hello-world' \
    --header 'Authorization: Bearer JWT' \
    --header 'Content-Type: application/json' \
    --data '{"name":"Functions"}'

HTTP/1.1 503 Service Unavailable
Content-Type: application/json
Content-Length: 75
Connection: keep-alive
vary: Accept-Encoding
date: Sun, 21 Jan 2024 03:36:00 GMT
X-Kong-Upstream-Latency: 7
X-Kong-Proxy-Latency: 1
Via: kong/2.8.1

{"code":"BOOT_ERROR","message":"Worker failed to boot (please check logs)"}
```

The log shows:

```
$ supabase functions serve
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
serving the request with /home/deno/functions/hello-world
Is a directory (os error 21)
An error has occured
InvalidWorkerCreation: worker boot error
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:123:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:129:20)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerCreation"
}
```

Checking the edge container, I see that `/home/deno/functions` should be mounted but it appears empty:

```
$ docker ps | grep _edge_
1af228294ba5   public.ecr.aws/supabase/edge-runtime:v1.29.1      "sh -c 'mkdir -p /ho…"   10 minutes ago   Up 10 minutes             8081/tcp                                           supabase_edge_runtime_hello
$ docker exec 1af228294ba5 ls /home/deno/functions
$ docker exec 1af228294ba5 ls /home/deno
fallback_import_map.json
functions
main
$ docker inspect 1af228294ba5 | grep -A27 Mounts
        "Mounts": [
            {
                "Type": "volume",
                "Name": "supabase_edge_runtime_edge",
                "Source": "/var/lib/docker/volumes/supabase_edge_runtime_edge/_data",
                "Destination": "/root/.cache/deno",
                "Driver": "local",
                "Mode": "rw,z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/Users/myuser/hello/supabase/functions",
                "Destination": "/home/deno/functions",
                "Mode": "rw,z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/Users/myuser/hello/supabase/.temp/import_maps/23823e56fe696298179eb353d6ee00f331060a823054a521053b179dd8e10e07.json",
                "Destination": "/home/deno/fallback_import_map.json",
                "Mode": "ro,z",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```

## Expected behavior

The functions directory should be mounted and workers should boot correctly.

## System information

- OS: macOS Sonoma 14.2.1
- Version of supabase-js: Not used
- Version of Node.js: v21.6.0
- Supabase CLI: 1.131.5
- Docker Engine: 24.0.7
- Docker Desktop: 4.26.1
- Edge Docker container: `public.ecr.aws/supabase/edge-runtime:v1.29.1`

## Additional context

I've checked that `/Users/myuser/hello` is shared in `Settings > Resources > File Sharing` of Docker desktop.

I have another edge functions project created a couple of days ago, and it works.
Also, the project that doesn't work has a slightly different Docker bind for `fallback_import_map.json`:

```
		{
			"Type": "bind",
			"Source": "/host_mnt/Users/myuser/hello/supabase/.temp/import_maps/23823e56fe696298179eb353d6ee00f331060a823054a521053b179dd8e10e07.json",
			"Destination": "/home/deno/fallback_import_map.json",
			"Mode": "ro,z",
			"RW": false,
			"Propagation": "rprivate"
		}
	],
```

The other project (which works) simply binds `/host_mnt/Users/myuser/project/supabase/functions/import_map.json` instead of `/host_mnt/Users/myuser/hello/supabase/.temp/import_maps/...` (which is an existing file and should work too).

**Comment by AlexBa** [comment]
I have exactly the same issue:

```
serving the request with /home/deno/functions/yolo
Is a directory (os error 21)
DEBUG CPU time used: 0ms
An error has occured
InvalidWorkerCreation: worker boot error
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:147:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:129:20)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: [32m"InvalidWorkerCreation"[39m
}
```

**Comment by simpros** [comment]
@sweatybridge I hope you can help with that - that thing is quite a blocker 😢

**Comment by pdurasie** [comment]
Is there any workaround available? I don't see any way to serve or deploy any edge functions at the moment because of this error.

**Comment by pdurasie** [comment]
Hello, I can report that I tried again to follow the quickstart guide today and this error did not occur anymore.

**Comment by tranhoangvuit** [comment]
Hi guys, is this issue still happening? It works fine on my local with the latest version.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Feel free to reopen if you’re still having issues here.
