### ISSUE TITLE
Failed to enable dblink: failed to create pg.extensions: permission denied to create extension "dblink"

### ISSUE THREAD

**Issue by RafiulM** [supabase/supabase#20617]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to enable the dblink extension from the supabase dashboard and it's giving me this error

```sql
Failed to enable dblink: failed to create pg.extensions: permission denied to create extension "dblink"
```

## To Reproduce

Go to supabase project dashboard > database > extensions > dblink

## Expected behavior

The dblink extension should be enabled

## Screenshots

<img width="400" alt="Screenshot 2024-01-22 at 12 05 49" src="https://github.com/supabase/postgres/assets/39544732/ac598ff5-671a-4780-b433-e3f9bb6f8518">

## Additional context

I need dblink enabled to be able to connect to the remote db from my supabase local dev environment. Currently when I run `supase db push` it returns: 
```
ERROR: permission denied to create extension "dblink" (SQLSTATE 42501)          
At statement 2: create extension if not exists "dblink" with schema "extensions"
```

**Comment by GaryAustin1** [comment]
Just confirming it does not work.

**Comment by RafiulM** [comment]
I think this is related to my project being outdated. I made a new project and I was able to enable this extension and continue  executing other CLI commands. I've also tried this on other older projects I had and it was also throwing the same permissions error when enabling the dblink extension.

**Comment by GaryAustin1** [comment]
hmmm... I have a very new instance and it is not working.

**Comment by RafiulM** [comment]
Yea that's strange. This is pretty important because without it we wouldn't be able to do anything to sync between local and remote supabase instances...

**Comment by GaryAustin1** [comment]
Yep.  I just spun up a brand new instance and it works.  One from a week or two ago does not.

**Comment by GaryAustin1** [comment]
So upgrading your database on the failing instance might solve it.

**Comment by RafiulM** [comment]
Wow thanks for trying it out. How can I upgrade my db?

**Comment by GaryAustin1** [comment]
![image](https://github.com/supabase/supabase/assets/54564956/b738f45c-cedb-4c12-be09-2347be334bb2)

**Comment by RafiulM** [comment]
Not sure if this is caused by the current "technical issue". But I cannot upgrade my project. I'll try it at a different time and update you on this. Thank you so much!
<img width="1085" alt="Screenshot 2024-01-22 at 23 09 38" src="https://github.com/supabase/supabase/assets/39544732/19fcf860-69d1-4542-b8a1-1793f772d8b1">

**Comment by GaryAustin1** [comment]
Only new instances seem to work.  15.1.1.3 on two upgraded instances do not work.  2 new instances do.

**Comment by encima** [comment]
Some fixes to databases permissions have been made in the past week so this should be resolved. For it to fail on upgraded issues is a concern, if you can open a support ticket with the Project Refs then we can investigate.

**Comment by GaryAustin1** [comment]
I'm sending in a ticket with an upgraded instance that does not work.  Just upgraded again to 15.1.1.5.
