### ISSUE TITLE
The supabase-studio is always unhealth when Self-Hosting with Docker

### ISSUE THREAD

**Issue by echozyr2001** [supabase/supabase#20655]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I follow the [Self-Hosting with Docker](https://supabase.com/docs/guides/self-hosting/docker) suggestion. After I run `docker compose up -d`,the `supabase-studio` is always unhealthy.
```shell
CONTAINER ID   IMAGE                              COMMAND                   CREATED          STATUS                      PORTS                                                                NAMES
0c2979c89270   supabase/storage-api:v0.43.11      "docker-entrypoint.s…"    58 seconds ago   Up 21 seconds (healthy)     5000/tcp                                                             supabase-storage
6e995834f5ea   supabase/gotrue:v2.132.3           "auth"                    58 seconds ago   Up 22 seconds (healthy)                                                                          supabase-auth
7e27560791f1   postgrest/postgrest:v12.0.1        "postgrest"               58 seconds ago   Up 22 seconds               3000/tcp                                                             supabase-rest
dc37c5bffa5c   supabase/edge-runtime:v1.32.0      "edge-runtime start …"    58 seconds ago   Up 22 seconds                                                                                    supabase-edge-functions
b215e2d9fda5   supabase/studio:20240101-8e4a094   "docker-entrypoint.s…"    58 seconds ago   Up 22 seconds (unhealthy)   3000/tcp                                                             supabase-studio
5d232f0c7c82   kong:2.8.1                         "bash -c 'eval \"echo…"   58 seconds ago   Up 22 seconds (healthy)     0.0.0.0:8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, 8444/tcp   supabase-kong
5a7242e4ccfe   supabase/realtime:v2.25.50         "/usr/bin/tini -s -g…"    58 seconds ago   Up 22 seconds (healthy)                                                                          realtime-dev.supabase-realtime
b2a5c99bbcb8   supabase/postgres-meta:v0.75.0     "docker-entrypoint.s…"    58 seconds ago   Up 22 seconds (healthy)     8080/tcp                                                             supabase-meta
b0441e8fe2f4   supabase/logflare:1.4.0            "sh run.sh"               58 seconds ago   Up 39 seconds (healthy)     0.0.0.0:4000->4000/tcp                                               supabase-analytics
e7c1ddfb5c09   supabase/postgres:15.1.0.147       "docker-entrypoint.s…"    58 seconds ago   Up 50 seconds (healthy)     0.0.0.0:5432->5432/tcp                                               supabase-db
07c3359ac278   timberio/vector:0.28.1-alpine      "/usr/local/bin/vect…"    58 seconds ago   Up 56 seconds (healthy)                                                                          supabase-vector
e9dd356ed9d0   darthsim/imgproxy:v3.8.0           "imgproxy"                58 seconds ago   Up 56 seconds (healthy)     8080/tcp                                                             supabase-imgproxy
```

And I found that the error always occurs in Logs Explorer
![image](https://github.com/supabase/supabase/assets/115935108/51f0a734-204e-4a64-9c9a-d8366c557c05)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```shell
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Pull the latest images
docker compose pull

# Start the services (in detached mode)
docker compose up -d

# Check containers
docker ps -a
```

## Expected behavior

`supabase-studio` suould be healthy.

## System information

- OS: Ubuntu 22.04

**Comment by encima** [comment]
Thanks for opening, the unhealthy status is likely because the health check is failing. The logs is semi-related, can you confirm you read and followed the Self-Hosted Analytics guide [here](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started)?

**Comment by markm-io** [comment]
Facing the same issue

**Comment by Mortezanavidi** [comment]
any fix on this? because of this i can't get any api tokens

**Comment by Mortezanavidi** [comment]
@spurgeonbj i actually tried to change the ports by just changing the ports from within the containers using vscode dev containers, even after changing the port of supabase-studio to 5000, changing the health check to port 5000, make sure port 5000 is accessable through other containers in the same network and within container itself by exposing the port, the problem was still up there, health check would say it cant reach out to the ip:port, any idea what would be the other cause of the problem?

**Comment by Mortezanavidi** [comment]
@spurgeonbj i can't truely help with knowing the functionality of studio because i'm fairly new to supabase, but i know that because of supabase-studio, the functionality of the api side of the whole stack is gone, for example, if i want to connect to api with my python wrapper, i need the api key to authenticate, when i try to go get the key i get this page:
![img1](https://github.com/supabase/supabase/assets/40989337/61d5950c-ae32-4a5e-b0a5-a4162f2d8c1d)
and the reason for it is that from what i get to know, it's trying to get data from studio and it can't so it fails!

**Comment by lxbworld** [comment]
> Facing the same issue

+1

**Comment by derickongeri** [comment]
Has anyone found a work around this? I have had this problem in the last two weeks and I really need to get this working

**Comment by lxbxinwei** [comment]
> Has anyone found a work around this? I have had this problem in the last two weeks and I really need to get this working. I am following the [self-hosting guide](https://supabase.com/docs/guides/self-hosting/docker)

I followed [self-hosting guide](https://supabase.com/docs/guides/self-hosting/docker) and met the same error... (Ubuntu 18.04)

**Comment by derickongeri** [comment]
> I noticed it was running ok in between during setup of a trial iteration.
> 
> IMHO, its got to do with the password (most likely of postgres) and other variables in the .env file.
> 
> Guess, unlike other containers, studio container setup isnt able to handle certain characters in the password effectively.

Please explain this. I am quite new to supabase and I'd like to explore more. What charactors should I avoid? Were you able to get it working?

**Comment by lxbxinwei** [comment]
I fixed the error by this: #20985, you can have a try.

**Comment by encima** [comment]
I will close this as the issue linked by @lxbxinwei seems to work. Comment if the issue still occurs and we can re-open/re-investigate!

**Comment by garrettcam** [comment]
The heathcheck fails as inside the studio docker container the webserver does not bind to localhost.
A simple fix is to alter the heathcheck to use the hostname as provided by `process.env.HOSTNAME` instead of `localhost`.

 change https://github.com/supabase/supabase/blob/70c118df900e4cd334fd5975f005f9cbb823599e/docker/docker-compose.yml#L21

to 

`"require('http').get('http://' + process.env.HOSTNAME + ':3000/api/profile', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"
`

**Comment by woodmin** [comment]
Solution by [garrettcam](https://github.com/garrettcam) helped. But I also needed to increase healtcheck timeout (to 20s) for Supabase Studio.

**Comment by TBG-FR** [comment]
Works for me too with the following changes to `studio`, thanks everyone 🙏 
```diff
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
-          "require('http').get('http://localhost:3000/api/profile', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"
-        ]
-      timeout: 5s
+          "require('http').get('http://' + process.env.HOSTNAME + ':3000/api/profile', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"
+        ]
+      timeout: 20s
       interval: 5s
```

**Comment by TBG-FR** [comment]
@encima **I think these modifications should be made in the repo, to ensure Healthcheck always runs well.**

~~I can make a PR if needed~~ **Could you review this PR ?** #23300 😉
