### ISSUE TITLE
Incorrect error when leaving BOOL as the default option for the field type when creating a new column

### ISSUE THREAD

**Issue by libovness** [supabase/supabase#2065]
# Bug report

## Describe the bug
I add a new column to a table via the UI. I want that column to be a BOOL. I set 'false' or 'true' as the Default Value (this part doesn't really matter) and get `Error for input at Type: Field cannot be blank` even though the selected value is `bool`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Table Editor
2. Click on Add Column
3. Name the column
4. Set a default value (sort of tangential to the bug)
5. Click `Save`
(Note that it works if you select another field type and then select BOOL

## Expected behavior

New column should be added

## Screenshots

https://user-images.githubusercontent.com/612866/123115411-16146c80-d40e-11eb-90fd-94bd74fbed71.mov

## System information

- OS: macOS
- Browser (if applies) Chrome

## Additional context
The solution is either to have a NULL option in the Field Type select (in which case the error would make sense) or set the default values in the underlying JS to BOOL.

**Comment by phamhieu** [comment]
Hi @libovness, we updated dashboard app to fix this issue recently. Feel free to reopen if you are still facing the same issue.
