### ISSUE TITLE
[Auth Docs] Add TextLocal to Phone Login docs

### ISSUE THREAD

**Issue by encima** [supabase/supabase#20693]
# Improve documentation

## Link 

[Phone login](https://supabase.com/docs/guides/auth/phone-login)

## Describe the problem

Textlocal is a supported provider with `gotrue` and Supabase Auth but documentation has not yet been written.

## Describe the improvement

Documentation for Textlocal to match that of Vonage and MessageBird.

## Additional context

Related to issues like [this](https://github.com/supabase/postgrest-js/issues/465#issuecomment-1857527516) and questions like [this](https://stackoverflow.com/questions/77747639/textlocal-integration-for-otp-verification-is-not-working-with-supabase-and-flut)

**Comment by meherpanguluri** [comment]
I can take up this issue, can you assign it to me ?

**Comment by encima** [comment]
No need to assign, you can take it and open a PR against it @meherpanguluri 

Thank you!
