### ISSUE TITLE
Removing the "Powered by Supabase ⚡️" watermark

### ISSUE THREAD

**Issue by 128912891289** [supabase/supabase#20710]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi! 
I was wondering if there was any way to remove the "Powered by Supabase ⚡️" watermark at the bottom of emails. I'm already using my own SMTP. 

I'm all for encouraging other devs to use Supabase since I think it's a great product, but having an advertisement at the bottom of a signup email for some random website doesn't seem like the place to do it.  

Will this get removed when I upgrade from Free to Pro? Or is there currently a way that I can remove it? 

Thanks! 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Send an email verification to yourself 
2. See bottom of email 

## Expected behavior

An option to remove or modify the Supabase watermark at the bottom of emails for full customization. 

## Screenshots

<img width="143" alt="image" src="https://github.com/supabase/supabase/assets/63319015/91ffa669-173f-4f8a-849e-08d6d510ef65">

## System information

- OS: Windows
- Browser (if applies): Chrome
- Version of supabase-js: 6.0.2
- Version of Node.js: 10.10.0

## Additional context

If I can provide any other clarification feel free to say.

**Comment by GaryAustin1** [comment]
Yes as shown on the pricing page you have to be on the Pro plan or higher.

**Comment by sayem314** [comment]
@GaryAustin1 so in self hosted version it is not included?

**Comment by GaryAustin1** [comment]
@sayem314 good question.  I don't use self-hosting and don't know.  Seems odd it would have it.  Are you saying it does and asking how to remove or just asking?

**Comment by sayem314** [comment]
@GaryAustin1 no I am just asking. Started working with supabase recently and then after setting up auth found out about this. Now I am not sure if my project would make enough profits to pay 25 USD now and then don’t wanna also show this watermark to user inbox. Wish there was a 5 USD plan for just starting. I will probably self host with docker.

**Comment by GaryAustin1** [comment]
@sayem314 You can generate and send your own emails from a server.  https://supabase.com/docs/reference/javascript/auth-admin-generatelink gets you the links/tokens you need and then you format your own email and send it.  This bypasses the Supabase mailing infrastructure.

**Comment by sayem314** [comment]
@GaryAustin1 that’s great to know. Thanks, I will try that. Currently in supabase I am using mxroute smtp gateway to send emails.

**Comment by QaunainM** [comment]
Just connect your own email address from your domain via SMTP in the settings in the Supabase dashboard.

Then you don't suffer from the Supabase rate limits, the sender and reply email is one you own and that watermark footer is removed from the emails. It works on the free plan.
