### ISSUE TITLE
 must be superuser to alter replication roles or change replication attribute

### ISSUE THREAD

**Issue by psm-solution-group** [supabase/supabase#20724]
# Bug report

If I ran this query "ALTER USER postgres REPLICATION" then I get this error:

`ERROR:  42501: must be superuser to alter replication roles or change replication attribute`

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

**Comment by encima** [comment]
Hi @psm-solution-group 
This is correct and expected behaviour. Superuser is not given to instances. 

What are you trying to achieve? Logical replication can be set up using the `supautils` extension. Physical replication is only supported for our read replicas.

**Comment by pullmann4rent** [comment]
> Hi @psm-solution-group This is correct and expected behaviour. Superuser is not given to instances.
> 
> What are you trying to achieve? Logical replication can be set up using the `supautils` extension. Physical replication is only supported for our read replicas.

Hey, if I want to enable the extension then I got this error:

`Failed to enable supautils: failed to create pg.extensions: extension "supautils" has no installation script nor update path for version "0.1.0"`

**Comment by encima** [comment]
Hey there, no need to enable the extension (it is enabled on all instances by default)

Giving the replication privilege to roles is not allowed but you can use the [normal replication](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-REPLICATION) functions for this.

Postgres has the replication privilege so you just need to make sure you are on the latest version.
