### ISSUE TITLE
Unable to enable "Enforce single session per user"

### ISSUE THREAD

**Issue by sdr0x07b6** [supabase/supabase#20737]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Settings > Authentication > User Sessions > "Enforce single session per user" switch
Even if I enable this, it is disabled when I reload.
When I observe it in the Console, an error occurs when I enable it.
```
{
  "message": "Project <Project ID> is not allowed to set up custom domain; please contact Supabase support."
}
```

I don't understand what you mean.

To begin with, just by accessing this page, a large number of warnings and two errors occur.

`GET https://api.supabase.io/v1/projects/<Project ID>/custom-hostname`
```
{
  "message": "Project <Project ID> is not allowed to set up custom domain; please contact Supabase support."
}
```

`POST https://api.supabase.io/platform/telemetry/identify`
```
{
  message: "user.property disabled_features should not exist"
}
```

I'm getting a lot of warnings, so I can't decide if I'm not able to enable "Enforce single session per user" because I'm missing some conditions, or if it's just a glitch.
In the first place, when the "Enforce single session per user" switch is turned on and an error occurs, it is very unfriendly that there is no error message alert or anything.

There are so many warnings that I'm confused as to what to comment on, but for now the only thing I want to accomplish is to enable "Enforce single session per user".
Does anyone know?

## To Reproduce

Access the Settings > Authentication screen to open the Console.

## Expected behavior

- No warnings or errors should be displayed.
- The "Enforce single session per user" switch can be enabled, or a message will be displayed if there is a reason why it cannot be enabled.

## Screenshots

![Enforce single session per user](https://github.com/supabase/supabase/assets/1102138/eb1a027b-242c-4724-948c-755a96cd8d07)

Many warnings and errors occur even after just accessing this page
![Errors](https://github.com/supabase/supabase/assets/1102138/5330667d-0948-4a90-ba32-30b56e21587c)

![custom-hostname](https://github.com/supabase/supabase/assets/1102138/aad8e2f1-a16e-4ea8-8f02-8e9dd55590fb)

![identify](https://github.com/supabase/supabase/assets/1102138/19cd0c11-71de-4f5f-a3d7-7f485a3fa9e1)

## System information

- OS: macOS 14.3
- Browser (if applies)
  - Chrome 121.0.6167.85
  - Firefox 122.0

I am currently on the Pro plan

**Comment by GaryAustin1** [comment]
You don't mention, but just to confirm your project is currently Pro?  I assume as it does not have a banner above the User Session options saying you need to become Pro you are.  But just in case something glitched or your were Pro and now you are not and there is a bug in the UI.

**Comment by sdr0x07b6** [comment]
I am currently on the Pro plan.
I should have written that down. Thank you for pointing that out. I have added it to my first post.

**Comment by GaryAustin1** [comment]
This could be a general bug and then this is the correct spot, but the error message also might mean something went wrong in your instance (no inside knowledge of the error).
You should contact support if you have not.

**Comment by sdr0x07b6** [comment]
Thank you. I will wait for someone here to contact me and consider my inquiry at the same time!

**Comment by joshenlim** [comment]
Hey there @sdr0x07b6 can I check if this is still an issue? I can verify that this is not a general bug so it might be something specific to your project, in which as Gary mentioned I'd recommend reaching out to us via a support ticket

**Comment by sdr0x07b6** [comment]
In my environment, the reported situation remains unchanged.
I asked a team member on the same project to check, and he said that unlike my environment, the enabled switch does not revert after reloading. However, they are getting the same large number of warnings as in the screenshot I reported.

I will proceed with my consideration of contacting support as you have recommended.
Thanks for your concern.

**Comment by sdr0x07b6** [comment]
We will be inquiring individually, so this thread is closed. Thank you very much.
