### ISSUE TITLE
Expo React Native tutorial has some TypeScript compiler errors

### ISSUE THREAD

**Issue by NekodRider** [supabase/supabase#20764]
# Improve documentation

## Link 

[Build a User Management App with Expo React Native](https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native#create-an-upload-widget)

## Describe the problem

1. The code of `components/Avatar.tsx` has some TypeScript errors. 
2. I also encountered [this issue](https://github.com/rnmods/react-native-document-picker/issues/677) and in my own demo I used `expo-document-picker` instead.

## Describe the improvement

1. Add a check and some type conversions.
2. I'm not sure if I should replace `react-native-document-picker` or just wait for the official fix, so I will separate this into another commit.

## Additional context

![errors](https://github.com/supabase/supabase/assets/22171828/51eaa550-d2c8-4dba-89ad-af58a6e81532)

**Comment by encima** [comment]
Thanks for opening, please do open a PR against this when it is ready!
