### ISSUE TITLE
This is both a bug and documentation for Edge functions with Supabase auth examples

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#20771]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

https://supabase.com/docs/guides/functions/auth from documents shows using getUser() with no jwt after setting the header in the client with the user jwt.  getUser() relies on the session (which there is none) if you don't provide a jwt/access token.

This example (have not looked thru them all) https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/select-from-table-with-auth-rls/index.ts  is also incorrect.

## To Reproduce

Users are running the examples and getting Invalid JWT errors: 

https://discord.com/channels/839993398554656828/1200421727742738513

## Expected behavior

auth.getUser(jwt) needs to be called.
https://github.com/orgs/supabase/discussions/19621 user example of string manipulation to get token from header for getUser().
https://github.com/orgs/supabase/discussions/8371
`await supabaseClient.auth.api.getUser(req.headers.get('Authorization')!.replace('Bearer ', ''))`

## System information
v2 supabase-js

**Comment by simonha9** [comment]
Hey! Would love to take a look at this - if anyone is already working on this and wants to pair please let me know!
