### ISSUE TITLE
Edge Runtime runs out of memory really easily

### ISSUE THREAD

**Issue by samulik4** [supabase/supabase#20809]
# Bug report

Edge Runtime runs out of memory really easily.

## Describe the bug

I'm running Supabase locally on Mac with default settings.

I create one edge function as below.

I then call this edge function with a bash script. This is to simulate an application, where the edge function gets a lot of requests from the browser.

Supabase edge runtime runs out of memory in few minutes and crashes.

Could you please look at this? It is easy to reproduce.

You notice that there is sleep 0.1 in the bash script. It is to make the script to wait 100ms between requests. With this setting, the edge runtime runs out of memory quickly. You can see with 'docker stats' command, that the memory keeps going up. With sleep 0.5 memory usage goes up slower, but the edge runtime still crashes. When I make the script to sleep one second (sleep 1), it seems that the memory usage plateaus around 4Gb. 

Would you have advice how to prevent the OOM from happening?

## To Reproduce

Please implement edge function called 'oom-func' like so:

Deno.serve(async (req) => {
    return new Response(null, {
        status: 200,
        headers: { "Content-Type": "application/json" }
    });
})

Please implement following bash script:

#!/bin/bash
for i in {1..100000}
do
    echo "Making curl call number $i"
    curl --request POST 'http://localhost:54321/functions/v1/oom-func' \
        --header 'Authorization: Bearer < ANON_TOKEN >'
    sleep 0.1
    echo "\n"
done

## Expected behavior

The expectation is that edge function runtime keeps serving the request for months without any problems, just like a regular web server would.

What actually happens: Edge runtime runs out of memory in few minutes, and crashes.

## System information

- OS: macOS
- Supabase version: 1.131.5

## Screen shots

![Screenshot 2024-01-28 at 12 05 33 PM](https://github.com/supabase/supabase/assets/65631910/1e6856c0-5385-4b31-bd94-3ffaff41579e)
![Screenshot 2024-01-28 at 12 04 52 PM](https://github.com/supabase/supabase/assets/65631910/5e7a2919-a16c-43d5-83b1-73a126c544e7)

**Comment by encima** [comment]
hi @samulik4,

Your expectation is valid and I would recommend doing two things:
1. Deploy the function to Supabase cloud as that environment is optimised for this and confirm if you have the same issues
2. Increase the resource usage for your containers to allow them to use more than 4GB 
3. Increase your sleep time, 100ms for 100k requests is quite intense for your machine to handle. What is the runtime for each request, it might be worth trying to do sleep for the runtime of a request.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
