### ISSUE TITLE
Input field's count is not refreshed - Create Enumerated Types

### ISSUE THREAD

**Issue by SantoshPisini** [supabase/supabase#20802]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug & To Reproduce

On the dashboard, at Create Enumerated Types, when user clicks on 'add value' n times, and when the dialog is reopened those n inputs fields are being created after clicking on  'add value' for the next sidebar open. (Both 'cancel' & 'create type' of sidebar).

## Expected behavior

When 'add value' is clicked, only one input field must be added for all future sidebars is opened (i.e., when 'create type' of list page is clicked).

## Screenshot
![Screenshot 2024-01-28 at 5 47 32 PM](https://github.com/supabase/supabase/assets/39261271/6b82798e-3e50-4191-954d-a1cd506b3880)

**Comment by debugbybit** [comment]
Hey @SantoshPisini,

Could we possibly get a brief screen recording to provide more clarity on resolving the bug? It would be really helpful for troubleshooting within the PR.

Thanks!
