### ISSUE TITLE
Policy Editor: Unable to move SQL between check and using fields.

### ISSUE THREAD

**Issue by quicksnap** [supabase/supabase#2080]
# Bug report

## Describe the bug

If you have  an UPDATE policy where one of the fields is empty and try to move the SQL statement into the other field, you get a syntax error

## To Reproduce

See image for steps.

![2021-06-24 11 39 31](https://user-images.githubusercontent.com/1199742/123315816-fdc15200-d4e0-11eb-8163-dcfe463c9273.gif)

## Additional context

Workaround: Delete the policy and recreate it.

**Comment by inian** [comment]
Hi this should be fixed now. Please reopen if you still facing the issue, thanks!
