### ISSUE TITLE
Database Functions: Resolve Overflow Bug in 'Arguments' Column

### ISSUE THREAD

**Issue by Fynn** [supabase/supabase#20810]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

![Screenshot_1](https://github.com/supabase/supabase/assets/47244955/75d2859f-dbdd-4db8-8a41-045375ad563b)

## Expected behavior

Prevent line breaks and abbreviate with '...'. 
The arguments will still be visible in the 'Edit function' drawer. 

Perhaps also hide the 'DEFAULT ...' part.

## Additional context

Also check the other columns to see if a similar bug can occur there.

**Comment by Hallidayo** [comment]
I can take a look at this one.
