### ISSUE TITLE
Bug: "foreign key constraint "profiles_id_fkey" cannot be implemented"

### ISSUE THREAD

**Issue by Donny-H** [supabase/supabase#2083]
# Bug report

## Describe the bug

Trying to establish a 1:1 relationship between two tables. Have one table "profiles" (storing basic user info) and the other "services" (storing what services each user offers). Each table's primary key column is named "id" which is a uuid. When attempting to establish a foreign key relationship between them, I get the error in the title. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1) Go to profiles table
2) Click dropdown, edit column on "id"
3) click  add foreign key relation
4) select services as the table, id as the column, save
5) see message "The relation will be added to table services on column id"
6) click save
7) error popup "Error updating foreign key: foreign key constraint "profiles_id_fkey" cannot be implemented"

## Expected behavior

Some sort of success message and the relationship established (or just not an error)

## Screenshots

I don't think they're needed but happy to add if requested

## System information

Windows 10 on brave browser, using the Supabase UI

## Additional context

Need this mostly because I need to be able to get both the profile and services data in the same query as described here:

https://supabase.io/docs/reference/javascript/select#query-foreign-tables

But this won't work if I can't establish the relationship in the first place. A temporary fix is to just move the services data into profiles so it's all one table but it will be a large amount of columns if so (suboptimal)

**Comment by steve-chavez** [comment]
> "Error updating foreign key: foreign key constraint "profiles_id_fkey" cannot be implemented"

This is an error coming from PostgreSQL. Are you sure both columns of the wanted foreign key have the same type?

**Comment by Donny-H** [comment]
> > "Error updating foreign key: foreign key constraint "profiles_id_fkey" cannot be implemented"
> 
> This is an error coming from PostgreSQL. Are you sure both columns of the wanted foreign key have the same type?

noob move on my part, somehow one of them was a text type so this was exactly it. Cheers
