### ISSUE TITLE
The query references Indonesia but the data doesnt include Indonesia

### ISSUE THREAD

**Issue by marcusraty** [supabase/supabase#20852]
# Improve documentation

## Link 

https://supabase.com/docs/reference/swift/select?example=querying-foreign-table-with-inner-join

## Describe the problem

The query references Indonesia but the data doesnt include Indonesia

**Comment by encima** [comment]
great catch! feel free to open a PR for this

**Comment by ga1az** [comment]
I think the problem is bigger than just that Indonesia is not included in the data, the written code does not work.
```
struct City: Decodable {
  let name: String
  let countries: [Country]
}
```
A city only belongs to one country
