### ISSUE TITLE
Error reading/writing to buckets

### ISSUE THREAD

**Issue by SteevoMcCool** [supabase/supabase#20850]
# Report: Buckets and Infastructure

## Describe the bug

When i open Supabase storage, all previous buckets fail to load in. Additionally,  I cant create more buckets fail because "Tenant config for PROJECT_ID not found".

IN ADDITION, I cannot restart the project because it cannot find project service infastructure

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to project
2. Click on storage
3.  Click "create bucket"
4. It doesnt work

## Expected behavior

When I wanted to create the bucket, I kind of just expected the bucket to be created.

## Screenshots

![image](https://github.com/supabase/supabase/assets/96311500/534c41a2-7f0a-4e21-a5f3-d3509802b2f2)

![image](https://github.com/supabase/supabase/assets/96311500/f2ea5467-b2a6-4325-8bf1-35d4c8a43517)

## System information

- Windows, Chrome, latest version of  supabase website

**Comment by encima** [comment]
This is likely related to an [earlier incident](https://status.supabase.com/) with Storage. Please open a support ticket with your project reference for this.

**Comment by SteevoMcCool** [comment]
it's also affecting my past projects, which have worked before.
