### ISSUE TITLE
JS Client: Missing UPDATE RLS policy not throwing error

### ISSUE THREAD

**Issue by JorensM** [supabase/supabase#20867]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When calling `supabase.from().update()`, an error is not thrown telling me that I have a missing RLS policy. Considering that I do get an appropriate error message with other types of actions, I'd expect the `update` action to also throw an error telling me about the missing RLS policy

## To Reproduce

1. Create a table with RLS enabled but no policy for `UPDATE`
2. Try to run `supabase.from().update()` on the table

## Expected behavior

I'd expect the `update` action to throw an error with a message about a missing RLS policy instead of silently failing.

## System information

- OS: Windows 10
- Version of supabase-js: 2.39.3
- Version of Node.js: 20.8.0

**Comment by GaryAustin1** [comment]
This is not a bug and the way Postgres works.  Update will ignore rows it can't see (just like if you add a filter and it does not match).  RLS only reports errors if WITH CHECK fails for insert (and I believe Update if it is different than USING).

**Comment by GaryAustin1** [comment]
A quick hit I found discussing it: https://stackoverflow.com/questions/58521638/postgresql-row-level-security-does-not-throw-errors

**Comment by JorensM** [comment]
@GaryAustin1 Ah, that makes sense, thanks!
