### ISSUE TITLE
Issue with using PostGIS in RPC functions in self-hosted Supabase: “No Geometry” Returned

### ISSUE THREAD

**Issue by immocalcul** [supabase/supabase#20876]
Description

In a self-hosted Supabase environment, activating the PostGIS extension via Supabase Studio and creating an RPC function that utilizes PostGIS work correctly when executed via the SQL terminal. However, when calling the same RPC function from an external web application (e.g., developed with Node.js or Next.js), the function returns an error message indicating the absence of geometric data, as if the PostGIS extension was not activated (“No Geometry” or a similar message).

Interestingly, if the PostGIS extension is activated directly through the SQL terminal with CREATE EXTENSION postgis;, everything works as expected, and the RPC function returns geometric data without error when called from an external application.

Steps to Reproduce

	1.	In a self-hosted Supabase environment, activate the PostGIS extension via Supabase Studio.
	2.	Create an RPC function that utilizes PostGIS functions.
	3.	Confirm that the function works as expected when called via the SQL terminal.
	4.	Attempt to call the same RPC function from an external web application.
	5.	Observe the error message indicating the absence of geometric data (“No Geometry”).
	6.	Activate the PostGIS extension directly via the SQL terminal (CREATE EXTENSION postgis;).
	7.	Repeat the call to the RPC function from the external application, which then works correctly.

Expected Result

Regardless of the method of activating PostGIS (via Supabase Studio or directly via the SQL terminal), RPC functions using PostGIS should correctly return geometric data when called from external applications in a self-hosted Supabase environment.

Observed Result

When PostGIS is activated via Supabase Studio in a self-hosted environment, RPC functions called from external applications return an error message indicating the absence of geometric data, suggesting that PostGIS is not properly activated or accessible.

Environment
i use your last version supabase docker

**Comment by encima** [comment]
@immocalcul please check and confirm the points from @GaryAustin1

**Comment by immocalcul** [comment]
I am writing to inform you that, following our recent invoice of nearly $800 USD and the realization of the financial and technical constraints it imposed on us, we have already migrated our services away from Supabase. Given our location in Canada, the currency exchange significantly increased the financial burden on us. Despite our efforts to manage costs by reducing service usage, we quickly encountered the platform’s daily limits.

Additionally, the maximum threshold of 100,000 connections per month has proven to be a significant limitation for our operational requirements. This, coupled with the potential for monthly expenses to soar to around 2000 CAD for an upgraded plan, led us to explore alternative solutions. We have found that a dedicated server solution can meet our needs for enhanced power and scalability at approximately 200 CAD per month, without imposing such limitations.

While we have already completed the migration process, I wanted to take this opportunity to express our appreciation for the services provided by Supabase up until this point. It was a difficult decision to move our project, but one dictated by our specific needs and financial considerations.

We hope this feedback is valuable for your ongoing efforts to improve service offerings. Thank you for your understanding, and we remain open to potential future collaborations should our circumstances change.

Best regards,



Le 31 janv. 2024 à 04:05, Chris Gwilliams ***@***.***> a écrit :

﻿

@immocalcul<https://github.com/immocalcul> please check and confirm the points from @GaryAustin1<https://github.com/GaryAustin1>

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
