### ISSUE TITLE
Empty USING clause when editing INSERT RLS policy

### ISSUE THREAD

**Issue by d-mok** [supabase/supabase#2087]
# Bug report

## Describe the bug

When using the dashboard to edit an "INSERT" RLS policy, there is an empty USING clause which causes error.

## To Reproduce

1. Go to 'Authentication' --> 'Policies'
2. Create an INSERT policy
3. Edit that policy, change the WITH CHECK expression to something new
4. Click 'review', see the empty USING clause
5. Click 'save policy', see error `Error updating policy: syntax error at or near ")"`

## Expected behavior

No error.

## Screenshots

![image](https://user-images.githubusercontent.com/49301824/123375439-5b29d180-d5bb-11eb-9026-feaf2b9e0e74.png)
![image](https://user-images.githubusercontent.com/49301824/123375476-667cfd00-d5bb-11eb-92de-ff64bb874572.png)

## System information

- OS: Windows 10
- Browser (if applies) chrome

**Comment by kiwicopple** [comment]
Looks related to this one: https://github.com/supabase/supabase/issues/2080
