### ISSUE TITLE
Bug Report: Stripe Wrapper Not Working as Expected in Self-Hosted Supabase

### ISSUE THREAD

**Issue by immocalcul** [supabase/supabase#20891]
Whenstripe.accounts table

Error: SQL identifier cannot be null or undefined
This error prevents me from viewing or interacting with the stripe.accounts table data through the Supabase Studio UI.

Steps to Reproduce
Navigate to Supabase Studio in a web browser.
Log into my self-hosted Supabase instance.
Go to the "Table Editor" and select the stripe.accounts table.
The error message appears, and the table data fails to load.
Expected Behavior
I expect to be able to view and interact with the stripe.accounts table data without encountering client-side exceptions.

Docker Configuration
Here is the relevant output of docker ps, showing the Supabase-related containers in my setup:
Docker Version Number:
supabase/storage-api:v0.46.5
supabase/gotrue:v2.139.1
supabase/postgres-meta:v0.75.0
kong:2.8.1
supabase/studio:20240122-7845baf
supabase/realtime:v2.25.60
supabase/logflare:1.4.0
supabase/postgres:15.1.0.147
darthsim/imgproxy:v3.8.0
timberio/vector:0.28.1
`

**Comment by encima** [comment]
hi @immocalcul 
can you format the docker output to be more readable, please. Is there anything relevant in the output? Can you also provide the error message you and confirm if this also occurs on hosted Supabase? 

Thanks!

**Comment by immocalcul** [comment]
in fact the problem is only at the self hosting level and in the striped wrapper tables maybe the tutorial must be different from the cloud and it is not adapted to the self hosting level I don't know? here are my errors as well as docker readjust to see the version numbers:

Application error: a client-side exception has occurred (see the browser console for more information).

**console dev(**
Error: SQL identifier cannot be null or undefined
    at ident (_app-a9daf9fd19c30847.js:1:6908)
    at queryTable (_app-a9daf9fd19c30847.js:6:207908)
    at selectQuery (_app-a9daf9fd19c30847.js:6:205739)
    at QueryModifier.toSql (_app-a9daf9fd19c30847.js:6:208521)
    at getTableRowsSqlQuery (3778-b443308fdb8e593f.js:1:476454)
    at useTableRowsQuery (3778-b443308fdb8e593f.js:1:476718)
    at SupabaseGridLayout (3778-b443308fdb8e593f.js:1:48532)
    at Xh (framework-c7762d7648ee44ba.js:25:61226)
    at j (framework-c7762d7648ee44ba.js:25:119941)
    at Vk (framework-c7762d7648ee44ba.js:25:99511)

main-c802fc22b396f8be.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
**)**

**Docker Version Number:**
supabase/storage-api:v0.46.5
supabase/gotrue:v2.139.1 
supabase/postgres-meta:v0.75.0  
kong:2.8.1 
supabase/studio:20240122-7845baf 
supabase/realtime:v2.25.60
supabase/logflare:1.4.0
supabase/postgres:15.1.0.147
darthsim/imgproxy:v3.8.0
timberio/vector:0.28.1

**Comment by encima** [comment]
The implementation for self-hosted and cloud is largely the same so I would not think so, but maybe! 

Give me a few days to replicate this and report back @immocalcul 🙏

**Comment by immocalcul** [comment]
ok thanks encima 

> L'implémentation pour l'auto-hébergement et le cloud est en grande partie la même, donc je ne le pense pas, mais peut-être !
> 
> Donnez-moi quelques jours pour reproduire cela et faire rapport@immocalcul🙏

thank you I will wait for your return

**Comment by encima** [comment]
Hey @immocalcul ,

Thanks for reporting this, it sort of looks like a bug (or that the table is not created with the wrapper).

Can you try this:
1. Create a table for the wrapper that is not yet created
2. You should then see all of your tables in the Table Editor, does that happen?
3. Clicking on a table will give you a 'Client-Side error', does that happen?
4. Using the SQL Editor, you can query from these tables successfully, does that happen?

**Comment by immocalcul** [comment]
> Hey @immocalcul ,
> 
> 
> 
> Thanks for reporting this, it sort of looks like a bug (or that the table is not created with the wrapper).
> 
> 
> 
> Can you try this:
> 
> 1. Create a table for the wrapper that is not yet created
> 
> 2. You should then see all of your tables in the Table Editor, does that happen?
> 
> 3. Clicking on a table will give you a 'Client-Side error', does that happen?
> 
> 4. Using the SQL Editor, you can query from these tables successfully, does that happen?


thank you for the feedback, it’s actually exactly what’s going on

**Comment by GeneMyslinsky** [comment]
I was trying to implement a custom FDW while testing supabase and I found this github issue.
This is exactly what happens to me as well.

**Comment by Zemps** [comment]
> > Hey @immocalcul ,
> > Thanks for reporting this, it sort of looks like a bug (or that the table is not created with the wrapper).
> > Can you try this:
> > 
> > 1. Create a table for the wrapper that is not yet created
> > 2. You should then see all of your tables in the Table Editor, does that happen?
> > 3. Clicking on a table will give you a 'Client-Side error', does that happen?
> > 4. Using the SQL Editor, you can query from these tables successfully, does that happen?
> 
> thank you for the feedback, it’s actually exactly what’s going on

This exact thing is happening to me as well
