### ISSUE TITLE
Example: Todo app using CRA

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#209]
# Feature request

## Is your feature request related to a problem? Please describe.

New example use case

## Describe the solution you'd like

- Create a initial React app in `examples/todos-react` using [CRA](https://create-react-app.dev/docs/getting-started)
- Build a todo list app, using Supabase as the backend. Use the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example.
- Add a one-click deploy using Vercel deploy button

## Additional context

- We will create a Quick Start template in our Dashboard for this app
- Ant has done an example [here](https://github.com/supabase/supabase/tree/master/examples/todo), which is a good baseline
- I suggest this is done with pure JS, rather than TS
- We don't need auth in this one, just keep it simple
- This will be used by [swimm.io](https://swimm.io) to create a tutorial for Hacktoberfest
- Keep it as simple as possible - no additional libraries, minimal styling etc.

**Comment by LinkSake** [comment]
I'm interesting on helping on this issue! But a I've a question
How it should be different from the example given in point 2 of the additional context? It seems that it also used CRA, should it have user management?

**Comment by kiwicopple** [comment]
You're right @LinkSake - I will make a couple of adjustments to the initial spec: 

- ~~We don't need auth in this one, just keep it simple~~
- Should include logins + policies

and

- ~~Keep it as simple as possible - no additional libraries, minimal styling etc.~~
- Keep it as simple as possible - for styling we can use Tailwind

You can use the the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example of how to set up Policies + one-click deployments

**Comment by bharati-21** [comment]
Hello @kiwicopple, I am interested in this issue. If this issue has not been assigned would like to work on this! 
Also, please do inform me if there is a deadline to complete this.

Thanks and cheers.

**Comment by LinkSake** [comment]
@kiwicopple Alright, I'll get working on it!

**Comment by bharati-21** [comment]
Oh okay @LinkSake ! 
Happy Hacktoberfest!

**Comment by awalias** [comment]
@bharati-21 if you're interested, we could also start a new issue for a Supabase **Auth** example with CRA? A simple web app with login system + external providers (google, bitbucket, gitlab, github)

**Comment by bharati-21** [comment]
@awalias I would love that! If it's possible would like to take up the issue 😊

**Comment by LinkSake** [comment]
@bharati-21 Actually you can take this issue, due to health reasons I'll be no longer able to participate on this year's Hacktoberfest

I'm sorry for the inconvenience!

**Comment by steve-chavez** [comment]
@bharati-21 I've assigned you the issue :)

@LinkSake No problem. Get well!

**Comment by bharati-21** [comment]
@LinkSake, I am very sorry to hear that. Hope you are doing well. Please take care and be safe.

Thank you @steve-chavez for assigning the issue to me. I really appreciate it.

**Comment by bharati-21** [comment]
@kiwicopple  @steve-chavez can you please explain about login+policies? Thank you.

**Comment by steve-chavez** [comment]
@bharati-21 Sure. Keep in mind that there's already a baseline here: https://github.com/supabase/supabase/tree/master/examples/todo

That baseline has a limitation mentioned in the [warning](https://github.com/supabase/supabase/tree/master/examples/todo#warning):

> This demo doesn't provide any form of client-side authentication so please don't use it in production unless you're ok with all your tasks being publicly available

The task is to lift that limitation - allow users to have private todos and share todos with other users of their choosing.

General idea for how to do this:

- `logins`: Have a login React component that uses the supabase-js auth module. Instructions for using supabase-js auth can be seen on the "User Management" part on supabase.io. There are also some tests [here](https://github.com/supabase/supabase-js/blob/master/test/integration/testAuth.js).

- `policies`: There's also some [policies](https://github.com/supabase/supabase/blob/master/examples/todo/db/task_list_schema.sql#L16-L22) already on the baseline. You need to make sure these are followed on the frontend for all the users. Policies are transparent to the tables. If they are right, you should only need to do `supabase.from('tasks')` on the frontend after doing `supabase.auth.login(user, pass)`.

**Comment by kiwicopple** [comment]
Hey @bharati-21 we also have a quickstart template set up in the dashboard too:

![Screenshot 2020-10-14 at 11 44 10 AM](https://user-images.githubusercontent.com/10214025/96327051-a83ac880-1068-11eb-8faf-fec61e8f8c7a.png)


You can see it in use on the Next.js example: https://github.com/supabase/supabase/tree/master/examples/todo-next-js

**Comment by bharati-21** [comment]
Hey @kiwicopple  I was wondering if you'd let me work on this outside the scope of Hacktoberfest!

**Comment by kiwicopple** [comment]
Yes of course! We're about to release supabase-js@1.0.0, so it would be great to get your help building this with the updated library

**Comment by YashKandalkar** [comment]
hello, this is now done in examples as [react-todo-list](https://github.com/supabase/supabase/tree/master/examples/react-todo-list) right?

**Comment by kiwicopple** [comment]
Hi @YashKandalkar , there is a version there, although it doesn't work with the "Todo List Quickstart" and it doesn't have Auth yet. 

So the next steps are to make if work like the Next.js example

**Comment by YashKandalkar** [comment]
@kiwicopple oh got it.
Can I make a PR for this? 
If yes, then should the existing react-todo-list folder be modified or should I create a new folder?

**Comment by kiwicopple** [comment]
Yes of course :)

> should the existing react-todo-list folder be modified or should I create a new folder

Perhaps create it in a new folder - it will make your PR easier to read. Once we merge it I can rename the folder
