### ISSUE TITLE
KONG docker connects vector db docker -p 53328 from public url. LOCAL DEPLOY

### ISSUE THREAD

**Issue by myagizmaktav** [supabase/supabase#20931]
# Bug Report

- [x] I confirm that this is a bug with Supabase and not with my own application.
- [x] I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the Bug
Changing the port of the Vector DB container causes errors when restarting the Kong container. The error message indicates an issue with connecting to port 53328 publicly.

## To Reproduce
- Open the TOML settings and initiate Vector DB and CLI with `supabase start`.
- Change the Vector DB container port and recreate it.
- Restart the Kong container.
- Observe the encountered error.

## Expected Behavior
The Kong container should correctly find the linked Docker container named `supabase_vector_supabase:9000` instead of attempting to connect to a public URL.

**Comment by tranhoangvuit** [comment]
Hi @myagizmaktav ,  is the issue persistent? I tried and it worked normlly to me, I changed to port [54330](http://localhost:54330/)

**Comment by myagizmaktav** [comment]
Hi @tranhoangvuit 

I've not used Supabase for the last 1 Month so for this reason.
It should be fixed probably.

**Comment by tranhoangvuit** [comment]
So sorry for this inconvenience. Please let us know if you need any support. Can we close this issue?

**Comment by myagizmaktav** [comment]
If you tested it and it's now working well then please.

**Comment by Hallidayo** [comment]
Hi all - thank you for your help on this one, I'm going to close this now but feel free to re-open if the issue happens again.
