### ISSUE TITLE
After creating a new column from SQL editor the table columns doesn't get updated.

### ISSUE THREAD

**Issue by harshithpabbati** [supabase/supabase#2093]
# Bug report

## Describe the bug

When we create a new column in a table, and when we go back to the table, the columns don't get updated as the columns data in the local storage is not updated until we refresh the page again.

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Go to SQL editor in any project.
2. Open a particular table.
3. Click on 'create new column' and create a new column in that particular table.
4. Go back to that table.
5. Now you can see that the newly created column isn't added.

## Expected behavior

The new column should be added, when we go back to that particular table.

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by kiwicopple** [comment]
Hey @harshithpabbati - I couldn't replicated this one on Chrome. Here I am following your steps:


https://user-images.githubusercontent.com/10214025/123594500-5dda3000-d822-11eb-91f2-dcb91de4cb6e.mov


Is there something that I missed?

**Comment by harshithpabbati** [comment]
ah, really sorry my bad, I wrote the steps in the wrong way. Sorry, here are the correct steps.

1. Open a particular table.
2. Go to SQL editor in any project.
3. Click on 'create new column' and create a new column in that particular table using the SQL editor.
4. Go back to that table.
5. Now you can see that the newly created column isn't added.

**Comment by harshithpabbati** [comment]
https://user-images.githubusercontent.com/43822585/123665376-d9090980-d855-11eb-9533-d457cb102473.mov

@kiwicopple are you able to reproduce it?

**Comment by joshenlim** [comment]
hey there @harshithpabbati ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!
