### ISSUE TITLE
[Auth Docs] onAuthStateChange return value

### ISSUE THREAD

**Issue by galaxyblur** [supabase/supabase#20966]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-onauthstatechange

## Describe the problem

The return value for `onAuthStateChange` shows the variable as a direct reference to the `Subscription` object, in order to call `unsubscribe()` later. The return value is actually `{ data: { subscription } }`.

## Describe the improvement

Update code example to show the correct return value.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by Mohammed-Yasin-Mulla** [comment]
@galaxyblur ,
Just to clarify the correction to the docs is supposed to be like this? 
```typescript

const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
  console.log(event, session)
```

**Comment by galaxyblur** [comment]
Yes, from what I can tell, that's the return value. But don't take my word for it :P

**Comment by Mohammed-Yasin-Mulla** [comment]
@galaxyblur had a cross verifed the issue and also added the changes to the docs, please reffer to the PR raised I have added the details with the screen shorts.

**Comment by charislam** [comment]
Thanks for the PR!
