### ISSUE TITLE
Column with base64 text breaks table performance

### ISSUE THREAD

**Issue by nappalm** [supabase/supabase#20998]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am saving an image in base64, the column seems to have supabase become too slow when scrolling horizontally. You can see in the image that the row appears cut in half

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase web
2. Insert base64 text  in column table

## Expected behavior

Keep my table fluid even if I have a column with base64 text

## Screenshots
![Captura de pantalla 2024-02-04 132435](https://github.com/supabase/supabase/assets/35016608/34bacd3f-8622-44dc-acf1-3f22740c6194)

## System information

- OS: Windows
- Browser chrome

**Comment by encima** [comment]
That certainly seems like a bug, thanks for reporting!

As a side note: storing files directly in the database is not needed with Supabase and you can use the Storage API

**Comment by Mohammed-Yasin-Mulla** [comment]
@nappalm could you please give me some more detils on I can re-produce it. along with the data you added for testing.

**Comment by nappalm** [comment]
@Mohammed-Yasin-Mulla only insert a base64 in a column, you can use [base64-image](https://www.base64-image.de) to generate a test, that should affect the performance of the table, if not, try inserting several equal columns.

**Comment by Mohammed-Yasin-Mulla** [comment]
@nappalm, I tried to store a base64 image in the column and I do not seem to have any issues. There is a 1 MB limit for the input value.
Yes, the dashboard's performance reduces when you store such large data in a column.

If you could share what you stored and in which column type, I could replicate it.

**Comment by nappalm** [comment]
@Mohammed-Yasin-Mulla  You are right, now everything works correctly. 🤔 I don't know what happened then, I have several base64 and everything is fine. I hope the problem doesn't happen again and if it does I'll let you know.
