### ISSUE TITLE
supabaseClient.auth.getUser() - return null even if logged in

### ISSUE THREAD

**Issue by nicitaacom** [supabase/supabase#20993]
# Bug report

## To Reproduce
demo - https://friendly-adventure-q956xqw9vrw2xv99-3000.app.github.dev/

mvp - https://friendly-adventure-q956xqw9vrw2xv99.github.dev/

github - https://github.com/nicitaacom/acc2-auth-get-user-issue

1. Go to  [mvp]( https://friendly-adventure-q956xqw9vrw2xv99.github.dev/)
2. Run `pnpm dev` and go to [https://friendly-adventure-q956xqw9vrw2xv99-3000.app.github.dev/](demo)
3. See that user always null (you may create a new user and try to log in)

### Expected behavior

I'm expecting that `supabase.auth.getUser()` return info about user

### Current behaviour

`supabase.auth.getUser()` return null even if user authenticated (and auth-token in cookies)

## System information
```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09)
Binaries:
  Node: 20.0.0
  npm: 9.6.4
  Yarn: 1.22.21
  pnpm: 8.13.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

**Comment by Mohammed-Yasin-Mulla** [comment]
@nicitaacom ,
The links that you have shared are not working may because they are not made public.

If you could share a code snippet on how  you are exicuting `supabase.auth.getUser()`.

**Comment by nicitaacom** [comment]
> @nicitaacom , The links that you have shared are not working may because they are not made public.
> 
> If you could share a code snippet on how you are exicuting `supabase.auth.getUser()`.

Please check it one more time - https://friendly-adventure-q956xqw9vrw2xv99.github.dev/

**Comment by nicitaacom** [comment]
> If you could share a code snippet on how you are exicuting `supabase.auth.getUser()`.

Here is code
**app/page.tsx**
```tsx
import { LoginForm } from "./components/LoginForm"
import supabaseClient from "./libs/supabase/supabaseClient"

export default async function Home() {
  const {
    data: { user },
  } = await supabaseClient.auth.getUser()
  console.log(12, "user - ", user)

  return (
    <>
      <LoginForm />
      {JSON.stringify(user)}
    </>
  )
}
```


**app/components/LoginForm.tsx**
```tsx
"use client"

import supabaseClient from "@/libs/supabase/supabaseClient"
import { useState } from "react"

export function LoginForm() {
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  async function login(e: React.FormEvent) {
    e.preventDefault()
    await supabaseClient.auth.signInWithPassword({
      email: email,
      password: password,
    })
  }
  async function register() {
    await supabaseClient.auth.signUp({
      email: email,
      password: password,
    })
  }

  return (
    <form onSubmit={login}>
      <input
        className="px-4 py-2 bg-foreground border rounded "
        value={email}
        onChange={e => setEmail(e.target.value)}
        placeholder="Email"
      />
      <input
        className="px-4 py-2 bg-foreground border rounded"
        value={password}
        onChange={e => setPassword(e.target.value)}
        placeholder="Password"
        type="password"
      />
      <button className="px-4 py-2" type="submit">
        Login
      </button>
      <button className="px-4 py-2" onClick={register}>
        Register
      </button>
    </form>
  )
}
```

**Comment by Mohammed-Yasin-Mulla** [comment]
@nicitaacom from what I can understand you are using Next.js App router.
 could you please confim that you are importing the correct `supabaseClient` in `app/page.tsx`. (ie.`createServerClient`)
you can reffer the [docs](https://supabase.com/docs/guides/auth/server-side/nextjs) for more details.
![image](https://github.com/supabase/supabase/assets/55092280/df34e839-b2e1-4bb3-90f1-beeafbf6225b)

**Comment by nicitaacom** [comment]
> could you please confim that you are importing 

**app/libs/supabase/supabaseClient.ts**
```ts
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs"
import { Database } from "@/interfaces/types_db"

const supabaseClient = createClientComponentClient<Database>()

export default supabaseClient
```

**Comment by Mohammed-Yasin-Mulla** [comment]
@nicitaacom please use the `supabase ssr` package. [docs link](https://supabase.com/docs/reference/javascript/installing#install-as-package)

**Comment by nicitaacom** [comment]
> please use the `supabase ssr` package. docs link

What?
![image](https://github.com/supabase/supabase/assets/39565703/d8c2a2f9-30b5-4da7-8831-200aceccbc8a)


Please provide steps I need to do to fix issue

As I understand your solution is unclear - I mean you messaged me about it and now I have question and how to fix it? what I need to do? ` use the supabase ssr` - its how?

**Comment by Mohammed-Yasin-Mulla** [comment]
I am sorry @nicitaacom for not being clear.
Please refer to this docs [herer](https://supabase.com/docs/guides/auth/server-side/nextjs).
`supabase ssr` is the new library.

Note, the supabase client for server components is different from the client components

**Comment by nicitaacom** [comment]
> Please refer to this docs [herer](https://supabase.com/docs/guides/auth/server-

I don't understand the reason of using this `supabase/ssr` package
```ts
import { createBrowserClient } from "@supabase/ssr"

export function supabaseBrowserClient() {
  return createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
}
```



# Solution (how to fix this issue)

1. My mistake was that I used `supabaseClient` that takes no cookies and created for client components
2. My mistake was that I forgot to setup `middleware.ts`

## To fix

### 1. Create `supabaseServer`
**app/libs/supabase/supabaseServer.ts**
```ts
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import { Database } from "@/interfaces/types_db"

const supabaseServer = () => {
  cookies().getAll() // Keep cookies in the JS execution context for Next.js build
  return createServerComponentClient<Database>({ cookies })
}

export default supabaseServer
```

### 2. Use `supabaseServer` in server component
**app/page.tsx**
```tsx
import { LoginForm } from "./components/LoginForm"
import supabaseClient from "./libs/supabase/supabaseClient"
import supabaseServer from "./libs/supabase/supabaseServer"

export default async function Home() {
  const {
    data: { user },
  } = await supabaseServer().auth.getUser()
  console.log(12, "user - ", user)

  return (
    <>
      <LoginForm />
      {JSON.stringify(user)}
    </>
  )
}
```

### 3. Setup middleware to refresh auth token when session expires (on 02.2024 supabase don't provide 'Remember me' functionality where you can save session to be valid for some time e.g 30 days)
```ts
import { createMiddlewareClient } from "@supabase/auth-helpers-nextjs"
import { NextResponse } from "next/server"

import type { Database } from "@/interfaces/types_db"
import type { NextRequest } from "next/server"

export async function middleware(req: NextRequest) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient<Database>({ req, res })
  await supabase.auth.getSession()
  return res
}
```

**Comment by rishabhsxn** [comment]
Make sure you have "Confirm Email" setting in Supabase->Authentication->Providers->Email turned off.

As long as this setting is ON, the auth-token cookie won't be set unless the user confirms the email through the confirmation link received on mail

**Comment by nicitaacom** [comment]
> @nicitaacom from what I can understand you are using Next.js App router. could you please confim that you are importing the ...

I already fixed that

As I mentioned you jsut need to have cookies - you may try to create `supabaseClient` - but I just use `supabaseServer`
