### ISSUE TITLE
@supabase/ssr causing ReferenceError: __dirname is not defined in Next.js's middleware

### ISSUE THREAD

**Issue by meetyan** [supabase/supabase#21009]
# Bug report

- [*] I confirm this is a bug with Supabase, not with my own application. 
- [*] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using Next.js 14.1.0 and encounter an issue with @supabase/ssr complaining ReferenceError: __dirname with middle.ts on deploment.

When I follow the [article](https://supabase.com/docs/guides/auth/server-side/nextjs) about using @supabase/ssr, everything works fine. However, after I deploy the app to Vercel, it says the app has crashed and `ReferenceError: __dirname is not defined` in the log.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install Next.js 14
2. yarn add @supabase/supabase-js @supabase/ssr
3. Follow this article https://supabase.com/docs/guides/auth/server-side/nextjs
4. Copy and paste the code from middleware section (step 4)
5. Everything works fine except deployment on Vercel (the app crashed)
6. Check the log and you'll see the error

## Expected behavior

Deployment on Vercel works fine without crashes.

## Screenshots

<img width="1414" alt="Screenshot 2024-02-05 at 3 04 05 PM" src="https://github.com/supabase/supabase/assets/2163522/56409b17-69cb-4da8-b9df-abfab1df83fe">

## System information

- OS: macOS 14.0
- Browser: chrome
- Version of supabase-js: latest version
- Version of Node.js: v18

**Comment by meetyan** [comment]
Okay, after hours of searching, it is resolved by changing Project Settings in Vercel to `Next.js`. Vercel's default settings is `Other`.

**Comment by georgedrury** [comment]
> Okay, after hours of searching, it is resolved by changing Project Settings in Vercel to `Next.js`. Vercel's default settings is `Other`.

This just saved me, thank you!

**Comment by kavir10** [comment]
Why was this fix so simple when I spent hours trying to fix it 😓

**Comment by vmesel** [comment]
@kavir10 same here
