### ISSUE TITLE
SITE_URL not propagating properly to email templates in docker

### ISSUE THREAD

**Issue by kryptus36** [supabase/supabase#21030]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In my .env file I set SITE_URL to http://localhost:5173

When I receive the confirmation email from email signup the link is:

http://localhost/auth/confirm?token=pkce_c03293137aa3a613de4d54274d6f2a0f51f137417a0e75d3f7712d30&type=signup&redirect_to=http://localhost:5173

As you can see the correct port is indicated in the redirect_to param, but not the url itself.

Possibly related: https://github.com/supabase/supabase/issues/7768

## To Reproduce

1. clone the git repo.
2. cd supabase/docker
3. cp .env.example .env
4. Set SITE_URL to http://localhost:5173 (or presumably any port)
5. docker compose up -d
6. Trigger an email confirmation via GoTrue

## Expected behavior

The url should begin with the contents of SITE_URL

## System information

- OS: [e.g. macOS, Windows]

Docker, running in Linux

- Version of supabase-js: [e.g. 6.0.2]

Git

**Comment by encima** [comment]
See the [email template documentation](https://supabase.com/docs/guides/auth/auth-email-templates) for how to set the Site URL in templates (set in the studio under Auth settings); the frontend is not necessarily aware of all ENV variables (and the `SITE_URL` you mention is config for the Auth server, there is also `SUPABASE_PUBLIC_URL` to set).
