### ISSUE TITLE
Number of regions Edge Functions are deployed to

### ISSUE THREAD

**Issue by JeongJuhyeon** [supabase/supabase#21046]
# Improve documentation

## Link 

https://supabase.com/edge-functions (1)

https://supabase.com/docs/guides/functions/regional-invocation (2)

## Describe the problem

The marketing materials at (1) claim "Edge functions are deployed to 29 regions worldwide".
In the documentation at (2), there are 14 given regions that can be used in the x-region header.
Deno Deploy, which Edge Functions run on, have recently dropped from running on 35 regions to only 12 (https://docs.deno.com/deploy/manual/regions).

Which of these is true? 29 is more than twice as much as 14 (or 12), and it seems important that such a claimed feature accurately reflects the product.

**Comment by mansueli** [comment]
Sorry, this was missed during the migration off Deno Deploy to our Edge Runtime. 
Fixed here: https://github.com/supabase/supabase/pull/21064
