### ISSUE TITLE
Unable to use a single tenant application in azure with supabase 

### ISSUE THREAD

**Issue by hamishakl** [supabase/supabase#21070]
Hi

I'm experimenting with an application for internal use at my company, where only users from our existing AD should have access. For this I am using Azure as an OAuth provider, and have set the "Support account types" to "Single Tenant".

When performing the sign-in action I am sent to the MS sign-in dialog, I sign in, and afterwards am redirected back to my app.

However I assume I have made a mistake somewhere, as the URL parameters includes the following error:

```Application 'xxxxx' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.```

As mentioned I'm not interested in allowing users outside of my organisation to authenticate, so is there some configuration that needs to be done for this to work?

Thanks in advance for any help!

_Originally posted by @solvemon-vh in https://github.com/supabase/supabase/discussions/1071_

**Comment by encima** [comment]
This is likely an issue with the config for your App and `/common` is the default endpoint used by Supabase.
You can change `Azure Tenant URL` in the Auth provider settings in the Dashboard (see [here](https://supabase.com/docs/guides/auth/social-login/auth-azure#configure-a-tenant-url-optional))
