### ISSUE TITLE
Missing Logs

### ISSUE THREAD

**Issue by anshunjain** [supabase/supabase#21108]
# Bug report

- [ YES] I confirm this is a bug with Supabase, not with my own application. 
- [ YES] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I simply log in my supabase function routines, using RAISE LOG, the logs are not appearing in the logs explorer. This is quite random, and I see some logs and then I dont. I have raised a support ticket and it has been of no help. I suspect there might be a log file issue (may be log directory has a size limit or something, which when hit, the logs simply stop showing up) there is no explanation of why the logs are missing. 

## To Reproduce

1. Create a test function which only does RAISE LOG
2. Execute the function
3. Search for that log in recent logs in log viewer. 
4. Check again after several minutes and after an hour. The logs are forever missing. 

## Expected behavior

The logs should appear almost immediately within a minute on the log viewer. 

## Screenshots

https://www.youtube.com/watch?v=CSKOTjylJzI

## System information

- Browser (if applies) [e.g. chrome]

## Additional context

I strongly believe this is related to something in the backend failing in the writing of the logs. I have a system which is having most of its business logic coded in functions, and is logging a LOT. so my suspicion is this is hitting the case of heavy use of logging which you may not be expecting? or testing for?

**Comment by encima** [comment]
HI @anshunjain,
Thanks for raising. Can you share the support ticket number here so that we can investigate with the additional context?
If you would prefer not to, please let me know your project ref so we can look it up internally.

**Comment by anshunjain** [comment]
Project reference: yidfpudwllwxzkxgkreb
Organization slug: foaenrtxhkpvoqwbnuyt

I cannot really find the support ticket number, but hopefully this helps. 

The main things they asked me to do was to verify pgaudit was enabled and the log levels were set correctly, and i did all of that and also restarted dbs etc. But none of that mattered as you may see in the video. simply logging fails.

**Comment by encima** [comment]
Thank you, do I have your permission to access your project?

I will also replicate this in Staging

**Comment by anshunjain** [comment]
Sure. I am also available to chat and will be hanging out at https://meet.google.com/svw-rusz-ayk for the next 30 mins, if it helps you make faster progress on troubleshooting the issue.

**Comment by encima** [comment]
Hi @anshunjain,

Thanks for the additional info, no need to waste your time with a call but thanks for the offer.
I can replicate the issue and see the logs are not being exported for some reason, I can see the logs on the instance itself so the setup of `pgaudit` is correct. Let me raise this with the PG team to see if they have ideas.

**Comment by anshunjain** [comment]
Perfect. Thank you for this. You surely understand that in postgres development, logs are one of the most critical means of making progress with development, and our dev pace is majorly hampered by this bug. Its been almost 2 weeks since i raised this and support teams and analytics team could not help. Will appreciate a quick resolution and if nothing, a temporary workaround.

**Comment by encima** [comment]
@anshunjain A fix has been rolled out to the logs collector that might have impacted you. Can you try again and report back please?

**Comment by anshunjain** [comment]
@encima the situation is better than before, but still I just ran code which ran through successfully and several minutes in, not a single log yet.

**Comment by anshunjain** [comment]
by situation is better than before, I mean that i can see more of the functions whose logs are showing up, but still there are few unexplained scenarios of missing logs

**Comment by anshunjain** [comment]
give me a couple of days to monitor. I had moved to a hack of logging to my db as a stop gap, and just moved back code everywhere to log to the system. I will update you in a day or two

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
