### ISSUE TITLE
Delete a storage will not delete the policies linked to it

### ISSUE THREAD

**Issue by Etheonor** [supabase/supabase#2110]
**Description**:

When you delete a storage, the policies remain and therefore, if you trying to recreate the storage with the same policies from a SQL query, it will not work, saying that the policies already exist. 

**Steps to reproduce**:

1. Create a storage
2. Add policies on it
3. Delete the storage
4. Try to recreate the storage with the same policies from a SQL query

**Expected behavior**

If you delete a storage, it should delete the policies linked to it. I didn't test it with tables, but it may be the same.

**Comment by awalias** [comment]
thanks for the report @Etheonor ! We'll def take a look

**Comment by joshenlim** [comment]
Closing this as its a duplicate of the recent issue #4721
