### ISSUE TITLE
Tables not loading

### ISSUE THREAD

**Issue by KCgam3r** [supabase/supabase#2115]
Tables not loading

The tables for all projects are not loading for me

no matter what project I am on, none of my tables render they just keep loading and when I check the console it has a few errors that say exactly, "Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR" and it also has a couple "GET https://rzavcpnccldjsmwxvbye.supabase.co/rest/v1/ net::ERR_SSL_PROTOCOL_ERROR" type of errors. 

All I did was log in and then choose my project, any project. I even created a new github account just to see if it was my github account

Normally it just loads my tables and I can then edit and see my data in the database.

## Screenshots

![Screenshot 2021-06-27 at 5 52 12 PM](https://user-images.githubusercontent.com/86575165/123560505-9c171700-d770-11eb-93a1-fc08f6eb052e.png)

![Screenshot 2021-06-27 at 5 51 57 PM](https://user-images.githubusercontent.com/86575165/123560508-a0dbcb00-d770-11eb-855b-4cf35ad9d59d.png)

**Comment by inian** [comment]
Tracking the issue here https://github.com/supabase/supabase/issues/2096 @KCgam3r
