### ISSUE TITLE
Multiline log messages of Postgres are difficult to read in log browser

### ISSUE THREAD

**Issue by jaulz** [supabase/supabase#21157]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The Postgres logs are quite difficult to read if the log message spans mutliple lines since it reverses the order (as it's in chronological order) (see screenshots).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a cronjob with `pg_cron`:
````sql
SELECT cron.schedule('test', '* * * * *', $$
BEGIN
  RAISE NOTICE 'Just a test.';
END;
$$);
````
2. Wait a minute
4. Check logs in studio
5. See output like in the screenshots

## Screenshots

Studio:
![image](https://github.com/supabase/supabase/assets/5358638/3eee13f9-5937-4fba-8d1f-9f05aba3f3c8)

Docker logs:
![image](https://github.com/supabase/supabase/assets/5358638/c8d551af-e996-447b-a3e7-d9978d62e412)

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase/postgres: 15.1.0.147
- Version of supabase/studio: 20240101-8e4a094

## Additional context

I wonder if this regular expression needs to be adapted:
https://github.com/supabase/supabase/blob/59d64b9375b049d7593ea65421f851e631b3de85/docker/volumes/logs/vector.yml#L145

**Comment by arshkhatwani** [comment]
I think this is coming because logs are usually displayed in the latest-first order

**Comment by arshkhatwani** [comment]
I have opened a PR that would add a toggle for the display order of logs

https://github.com/supabase/supabase/pull/22511

**Comment by Ziinc** [comment]
Though the sort order improvement will help, it will not tackle the root cause, which is that multi-line logs are ingested on a per-line basis in the underlying csv that we tail, so logs will still be split. Multi-line log support will only land in pg15.

The team is well aware of this issue, and will be supporting it once our infra can support it.
