### ISSUE TITLE
hittin max client connections when migrating to ipv6 (supavisor=

### ISSUE THREAD

**Issue by Nicolasvegam** [supabase/supabase#21166]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm below the max connections I'm still getting the error:

```
Optional Params: ["error: Max client connections reached\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","ExceptionsHandler"]
Mensaje: Max client connections reached

```
<img width="1027" alt="image" src="https://github.com/supabase/supabase/assets/26209122/eb65cd56-78d3-4619-aef8-cb4a19f09c6d">

**Comment by encima** [comment]
Hi @Nicolasvegam 

Have you filed a support ticket for this? Also, have you read the [Supavisor announcement](https://github.com/orgs/supabase/discussions/17817) and confirmed the string is the right one?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
