### ISSUE TITLE
Dashboard isn't taking the full available window height

### ISSUE THREAD

**Issue by JulienLecoq** [supabase/supabase#21178]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The dashboard isn't taking the full available height of my screen.

Here's how the bottom looks like:

![dashboard_not_taking_full_available_space](https://github.com/supabase/supabase/assets/54070985/12e62c6d-683b-47b1-b768-0951abdfbed1)

As you can see, there is a big space at the bottom of the screen that is empty.

## To Reproduce

Just loading the dashboard on any project.

## Expected behavior

The dashboard shouldn't be cut, I should be able to see all my tables without scrolling in a "small div".

## System information

- OS: macOS
- Browser: safari

**Comment by Mohammed-Yasin-Mulla** [comment]
I think this [PR](https://github.com/supabase/supabase/pull/21069) has to do something to do with this. will have a look

**Comment by saltcod** [comment]
Marking this one as closed per https://github.com/supabase/supabase/pull/21210

**Comment by JulienLecoq** [comment]
Is it normal that this issue is closed? Because the problem is still present on Safari.
Btw, it also affect the SQL editor which gets the layout more or less broken when you have a lot of queries.

**Comment by RedChops** [comment]
#21210 Just references that this ticket was filed in response to something found there, not that that PR solves this issue. This ticket shouldn't have been closed

**Comment by joshenlim** [comment]
Hey guys - since the problem you're running into is specifically for Safari, i've created a new ticket here
https://github.com/supabase/supabase/issues/21356

let's continue the discussion there
