### ISSUE TITLE
Nit: found typo in laravel-postgres document

### ISSUE THREAD

**Issue by Kurogoma939** [supabase/supabase#21186]
# Improve documentation

## Link 

Here is Link

<https://supabase.com/blog/laravel-postgres>

## Describe the problem

![スクリーンショット 2024-02-12 8 58 00](https://github.com/supabase/supabase/assets/67848399/ac804bbf-1692-4105-84ae-46e3584452eb)

I suppose "navigate" was correct, not "nvaigate."

## Describe the improvement

- ー

## Additional context

- ー

**Comment by encima** [comment]
Thanks for reporting @Kurogoma939 and for opening a PR for this @Mohammed-Yasin-Mulla!

**Comment by Kurogoma939** [comment]
Thank you @encima 🎉
