### ISSUE TITLE
[bug] height issue in dashboard homepage

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#21193]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Homescreen side bar is not full height when content on right is smaller than screen height.

<img width="1659" alt="Screenshot 2024-02-12 at 11 08 47 AM" src="https://github.com/supabase/supabase/assets/8291514/1aac1b22-13a4-4ef2-9cc0-498322854edb">

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to homepage in dash
2. Make sure you only have a few projects

**Comment by jCabala** [comment]
Hi, could I work on this issue?

**Comment by encima** [comment]
@jCabala go for it, just open a PR and tag the issue (no need to ask in the future, we always welcome PRs!)
