### ISSUE TITLE
Intro docs for nextjs includes outdated package

### ISSUE THREAD

**Issue by buildWithSoul** [supabase/supabase#21207]
# Improve documentation

https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs#supabase-auth-helpers < supabase auth helpers has been replaced with supabase-ssr

Lmk if you need help with resolving this.

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by encima** [comment]
Hi @buildWithSoul 

yes please, feel free to open a PR! Thanks for reporting

**Comment by encima** [comment]
Thanks!

No need to assign, you can just open a PR and mention this issue :)

**Comment by madhav23bansal** [comment]
The [documentation](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) already includes a note indicating that the package has been replaced with @supabase/ssr. Additionally, there's a comprehensive guide available on how to utilize it [here](https://supabase.com/docs/guides/auth/server-side/nextjs).

**Comment by Hahlh** [comment]
> The [documentation](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) already includes a note indicating that the package has been replaced with @supabase/ssr. Additionally, there's a comprehensive guide available on how to utilize it [here](https://supabase.com/docs/guides/auth/server-side/nextjs).

But in a completely different place.

The web app example tutorial is highly visible as a starting point for Next.js and loads of users will implement it incorrectly due to it being outdated. 
There is no notice whatsoever in the tutorial itself that it is outdated and the notes in the auth documentation aren't accessible / visible in this parts of the docs.
