### ISSUE TITLE
app.settings.jwt_secret cleared on project pause/resume

### ISSUE THREAD

**Issue by rkistner** [supabase/supabase#21226]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When pausing and unpausing a free project, `app.settings.jwt_secret` is cleared. It is only recovered by resetting the secret.

## To Reproduce

1. Create new project - `SELECT current_setting('app.settings.jwt_secret')` works.
2. Pause and unpause project - `SELECT current_setting('app.settings.jwt_secret')` gives error `unrecognized configuration parameter "app.settings.jwt_secret"`.
3. Restart the project - still the same error.
4. Generate a new JWT secret - `SELECT current_setting('app.settings.jwt_secret')` works again.
5. Restart project - still works.

`show app.settings.jwt_secret` is exactly the same.

## Screenshot

![image](https://github.com/supabase/supabase/assets/94081/bcd7fb7e-892b-457a-85d1-0bdfd4f80015)

## Expected behavior

`SELECT current_setting('app.settings.jwt_secret')`  should always work and return the current secret.

## System information

N/A - reproduce directly on the Supabase dashboard.

## Additional context

The functionality is important for validating auth tokens - for example in Edge Functions or in other integrated software. We specifically use this for PowerSync to get seamless authentication with Supabase tokens.

**Comment by estubmo** [comment]
Are you self hosting by any chance?  And have you changed the name of the database?

I believe this is the issue: 
https://github.com/supabase/supabase/blob/6b3420a5fd2fefc56655e327283f1f03ebccb07e/docker/volumes/db/jwt.sql#L4
The database name isn't being set depending on the POSTGRES_DB env var.

**Comment by rkistner** [comment]
In my case it's the hosted service with the default `postgres` database, so not the same issue.

**Comment by kobiebotha** [comment]
Ran into this today too

**Comment by hysuki** [comment]
I was gain same error after restoring the database on supabase cloud.

**Comment by celikomer** [comment]
We are also having the same issue after restarting the DB on Supabase Cloud.

**Comment by rkistner** [comment]
The PR introducing the feature appears to explain the issue, at least for the self-hosted version:

https://github.com/supabase/supabase/pull/17033

> The only downside that this script runs only one time if there is no database data directory.
meaning that this script won't run for existing databases and if the user changed the secret in the .env file it won't be updated until this script in manually executed.

It is interesting though that resetting the secret in the hosted version _does_ update it, but the secret is missing after a pause + unpause.

**Comment by rkistner** [comment]
`current_setting('app.settings.jwt_secret')` is being completely removed by Supabase now, making this issue obsolete: https://github.com/orgs/supabase/discussions/30606

PowerSync now has the option to manually specify the secret, and we'll add support for [asymmetric keys](https://github.com/orgs/supabase/discussions/29289) when that is available.
