### ISSUE TITLE
Unable to enable replication for individual tables

### ISSUE THREAD

**Issue by cameronskene** [supabase/supabase#2123]
# Bug report

## Describe the bug

I am currently unable to turn on replication for realtime for an individual table. Interestingly the toggle to enable replication for all existing tables appears to work. 

## To Reproduce

Currently in the database > replication view, I click "source" and attempt to toggle active for any of my tables (both custom such as `public.file_names` and internal such as `storage.objects`) results in the error toast "relation `public.file_name` does not exist". 

## Expected behavior

I expect the toggle to enable replication for an individual table of my choosing.

## Screenshots
![Screenshot 2021-06-28 201017](https://user-images.githubusercontent.com/26770771/123619786-e1107b80-d84c-11eb-8acd-0729c6dd93c3.png)

## System information

- OS: Windows
- Browser:  Firefox Developer Edition

## Additional context
Let me know if I can help further, you guys are doing great work.

**Comment by jonthomp** [comment]
Bumped into this too, @cameronskene you can still enable individual tables via SQL `alter publication supabase_realtime add table TABLE_NAME;`

**Comment by w3b6x9** [comment]
@cameronskene thanks for reporting and @jonthomp thanks for bumping.

We'll fix this as soon as possible!

**Comment by w3b6x9** [comment]
@cameronskene @jonthomp just wanted to let you know that this has been fixed!
