### ISSUE TITLE
Column Level Security bug when table `public.users` references `auth.users`

### ISSUE THREAD

**Issue by FilipeMarch** [supabase/supabase#21244]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After changing the column level privileges of different columns of a table on supabase UI and clicking on `Apply Changes`, nothing happens.

https://github.com/supabase/supabase/assets/23220309/0a1e0439-c4e6-4195-b3d1-648b46445f4e

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a `public.users` table

These are the columns I created:

![image](https://github.com/supabase/supabase/assets/23220309/fdc36381-e294-498c-b432-03941df0dea8)

Foreign key:

![image](https://github.com/supabase/supabase/assets/23220309/642122e0-a6b0-4702-9de9-59b900015109)

## Expected behavior

I expected that Column Level Security would work on my `public.users` table. It works only if I rename it to `public.profiles`. Maybe the issue lies because I have two tables named `users` on both `auth` and `public`  schemas. But I wasn't expecting to have any problem with that. Changing `public.users` to `public.profiles` solved the problem.

## System information

- OS: Arch Linux 
- Browser (if applies): chrome

**Comment by Mohammed-Yasin-Mulla** [comment]
I was trying to look into the issue, by running it on the local repo but unable to get it working. Is there something that I have missed to get it working locally ?
![image](https://github.com/supabase/supabase/assets/55092280/eec7c094-23f7-462c-80c1-84e0422a60b8)

**Comment by FilipeMarch** [comment]
> @FilipeMarch  Can you check if you're having the same problem again? It's working for me on my supabase project. 
> 
> https://github.com/supabase/supabase/assets/55092280/f5a0aeec-dc23-48dd-80cb-a03f7a4a924b
> 
> 
> 
> 

Could you please rename your table to _users_ instead of _admin_users_?

**Comment by Mohammed-Yasin-Mulla** [comment]
@FilipeMarch Yes, the issue exists when the table is named `users`.
That's interesting 🤔

https://github.com/supabase/supabase/assets/55092280/7599df87-6f1e-434d-b37a-59854bddbbc0

**Comment by Mohammed-Yasin-Mulla** [comment]
@FilipeMarch maybe for a quick fix, you can use a different table name.
