### ISSUE TITLE
project has been in "restoring" state for several days

### ISSUE THREAD

**Issue by rohan-arthur** [supabase/supabase#21284]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My [project](https://supabase.com/dashboard/project/bebpfitoxxxyejebvdtf) has been in "restoring" state since the past several days. It had gotten paused due to inactivity - my team uses the app only once in a few weeks. When I tried to restore it, the project went into this state.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to my project: https://supabase.com/dashboard/project/bebpfitoxxxyejebvdtf
2. See that it is not active, but seems to be hung in restoring state

## Expected behavior

Project should get restored instantly

## Screenshots

![Screenshot 2024-02-15 at 14 00 02](https://github.com/supabase/supabase/assets/94514895/70d98257-3663-47c9-a1f7-58851277cc17)

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Please open a support ticket for this
