### ISSUE TITLE
Unable to use Google OAuth in production

### ISSUE THREAD

**Issue by saampotter** [supabase/supabase#2128]
# Bug report

## Describe the bug

To my understanding, when creating credentials in the Google Cloud console it's necessary to add the Supabase project URL as one of the authorized domains to allow for the redirect when authenticating a user. However, when it comes time to publish that Google project to production, the project needs to be verified by Google. A part of this process is verifying ownership of all the different domains involved, meaning that I would need to verify ownership of the supabase.co domain?

Perhaps I'm missing something in my understanding and doing it wrong? Any help to solve this would be greatly appreciated

Cheers

**Comment by awalias** [comment]
Hey @saampotter I did some digging and looks like It also seems that you need to be requesting restricted or sensitive scopes in order for them to show a warning for unverified apps, in which case you may also be limited to 100 users (there is an appeal form [here](https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162#verification))

even in that case we would probably come under this, but may need to apply for exemption:

![image](https://user-images.githubusercontent.com/458736/123992396-29bb6680-d9fe-11eb-881d-02f7f15c505d.png)

I _think_ that the default email login isn't classed as a restricted or sensitive scope, but feel free to reopen if you discover some issue related to this!

More useful reading here: https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162
