### ISSUE TITLE
Example: Todo app using Vue

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#213]
# Feature request

## Is your feature request related to a problem? Please describe.

New example use case

## Describe the solution you'd like

- Create a initial React app in `examples/todos-react` using Vue Js
- Build a todo list app, using Supabase as the backend. Use the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example.
- Should include logins + policies
- Add a one-click deploy using Vercel deploy button

## Additional context

- We will create a Quick Start template in our Dashboard for this app
- Ant has done an example [here](https://github.com/supabase/supabase/tree/master/examples/todo), which is a good baseline
- Keep it as simple as possible - for styling we can use Tailwind.

**Comment by SoldierCorp** [comment]
Hi,

I would like to help I am a VueJS dev, can you assign it to me please?

**Comment by kiwicopple** [comment]
Amazing @SoldierCorp - I won't need to assign it to you, you can just give it a go and create a PR whenever you're ready :). Have you used Postgres before? Do you need any help with the schema & policies?

**Comment by SoldierCorp** [comment]
Thank you  @kiwicopple!

I have used Postgres before just in one small project and regarding help with schema & policies, I think I will reach you after I set up all the things I need.

In summary:
- I have to create a Supabase in my account for this Todo Vue.js
- Create the Todo Vue.js project to be uploaded to `examples/todos-vue`
- Connect the example with Vercel for the deploy

Right?

**Comment by kiwicopple** [comment]
Yes that's pretty much it. I'd check out the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md). Here's a demo of how it works: https://www.youtube.com/watch?v=2oqIZW5S-lQ&t=1s

If you get stuck at any point though just message me here and I'll help out. If you keep a repo of all your code I could even jump in and add comments :)

**Comment by SoldierCorp** [comment]
Sounds good :)

**Comment by mariusa** [comment]
Please have this support auth too.

users should own lists.
tasks belong to lists (without an user_id column)

1. anybody authenticated can INSERT lists
2. anybody owning that list can
2.1. UPDATE/DELETE lists and
2.2. do anything on tasks belonging to that list

**Comment by SoldierCorp** [comment]
@mariusa Got it!

**Comment by SoldierCorp** [comment]
Hi @mariusa  

Before I submit my PR, could you please read the Update for the event please https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by kiwicopple** [comment]
Hi @SoldierCorp I think that you wanted to tag a Supabase admin, `mariusa` is a community member :) 

I've read the updates - if the PR is good, then we will merge it and it will still count

**Comment by SoldierCorp** [comment]
You right @kiwicopple, I thought `mariusa` was an admin member :)

Regarding the update, yes but the repo needs to have the `hacktoberfest` topic  in order to count all the PRs within the repo as valid.

![image](https://user-images.githubusercontent.com/1775881/95000789-8aaa3100-0589-11eb-86cb-e9c3378d77fb.png)

**Comment by SoldierCorp** [comment]
Hi @kiwicopple,

I created a demo connection and I wanted to know if I am in the right direction, please.

- I created a Supabase project for this Todo and I added a table with a couple of items.
- I created a repo in my GitHub account which contains the Todo app with Vue and is retrieving the items from Supabase
- I created a project in Vercel that deploys from my github repo and this is the url https://supabase-todo-vue.soldier.vercel.app/

So once I fully finished and tested the Todo, I will upload that Vue project from my account to this repo within `example/todo-vue` but the url of the demo will always point to the one I created.

Is that right?

**Comment by kiwicopple** [comment]
Hi @SoldierCorp - looks like you're on the right track. 

> I created a repo in my GitHub account 

Do you have the link to this repo? I can check out the code

> I will upload that Vue project from my account to this repo

The correct way to do it is to

1. Fork this repo to your own account
2. Add your code to `example/todo-vue`
3. Create a Pull Request. [This video](https://www.youtube.com/watch?v=jZtECuvNRiw) might help!

**Comment by SoldierCorp** [comment]
> Hi @SoldierCorp - looks like you're on the right track.

Awesome!


> Do you have the link to this repo? I can check out the code
> 
> >
Link to the repo https://github.com/SoldierCorp/supabase-todo-vue (still in progress, I just created it to make this demo connection)



> The correct way to do it is to
> 
> 1. Fork this repo to your own account
> 2. Add your code to `example/todo-vue`
> 3. Create a Pull Request. [This video](https://www.youtube.com/watch?v=jZtECuvNRiw) might help!

Oh hehe, I know how to create PRs but thank you for the video!
When I said "I will upload that Vue project from my account to this repo" I was referring to a PR 🙂

**Comment by kiwicopple** [comment]
> I know how to create PRs 

😂 sorry - didn't mean to be condescending. I never know with Hacktoberfest what level of developer we have coming in.

Your app looks like a great start - we actually have a "Todo list" quickstart in our editor now:

![Screenshot 2020-10-14 at 11 44 10 AM](https://user-images.githubusercontent.com/10214025/95941143-a5469a80-0e12-11eb-9040-3864fcac5884.png)


You could use this if you wanted. Here is an example of how it works with Next.js - https://github.com/supabase/supabase/blob/master/examples/todo-next-js/README.md

**Comment by SoldierCorp** [comment]
> 😂 sorry - didn't mean to be condescending. I never know with Hacktoberfest what level of developer we have coming in.

That's true and no worries 😄 


> Your app looks like a great start - we actually have a "Todo list" quickstart in our editor now:

Just perfect, thanks!

**Comment by chiubaca** [comment]
Hello is this still open for submissions? I'd like to have a go at this with vue 3, and possibly with Typescript too?

**Comment by kiwicopple** [comment]
That would be awesome @chiubaca  - not sure if SoldierCorp is still working on it. We have a Next.js example here which you can use as a baseline: https://github.com/supabase/supabase/blob/master/examples/todo-next-js/README.md

**Comment by chiubaca** [comment]
I had a look at @SoldierCorp repo and looks like he was using Vue 2 Options API.  I'll make a version with the new composition API so users can see the difference :)

**Comment by SoldierCorp** [comment]
Hi,

Yes I am still working on it, I had to stop any development activities due personal reasons but I am going to re-take it in a couple of days.

Sorry :/

**Comment by kiwicopple** [comment]
Of course @SoldierCorp  - take your time and let us know if you would like any help

**Comment by kiwicopple** [comment]
We now have an example being actively maintained :) 

https://github.com/supabase/supabase/tree/master/examples/vue3-ts-todo-list
