### ISSUE TITLE
public.ecr.aws/supabase/gotrue:2.142.0  not found: manifest unknown: Requested image not found - wrong version string?

### ISSUE THREAD

**Issue by stefan-girlich** [supabase/supabase#21300]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```
(base) ➜  supabase db pull
Connecting to remote database...
Setting up initial schema....
failed to pull docker image: Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.142.0 not found: manifest unknown: Requested image not found
Retrying after 4s: public.ecr.aws/supabase/gotrue:2.142.0
```
etc.

## To Reproduce

1. supabase init
2. supabase link ...
3. supabase db pull => succeeds
4. supabase db pull => fails, see error above

It seems that it should be "v2" instead of "2" here: public.ecr.aws/supabase/gotrue:2.142.0 => public.ecr.aws/supabase/gotrue:v2.142.0

## Expected behavior

no error

## System information

- OS: macOS

**Comment by florentpergoud** [comment]
I reproduce on a brand new project with only

```
npx supabase@latest link
npx supabase@latest start
```

Giving

```
Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.142.0 not found: manifest unknown: Requested image not found
Retrying after 4s: public.ecr.aws/supabase/gotrue:2.142.0
Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.142.0 not found: manifest unknown: Requested image not found
Retrying after 8s: public.ecr.aws/supabase/gotrue:2.142.0
Error response from daemon: manifest for public.ecr.aws/supabase/gotrue:2.142.0 not found: manifest unknown: Requested image not found
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by Mikodin** [comment]
@florentpergoud @stefan-girlich 
The fix can be found here, in the adjacent issue

https://github.com/supabase/cli/issues/1938#issuecomment-1947201037

**Comment by stefan-girlich** [comment]
Workaround: `echo -n "v2.142.0" > supabase/.temp/gotrue-version`

Also see other thread for more info.
