### ISSUE TITLE
Error discovery in Log Sources - logflare.app

### ISSUE THREAD

**Issue by vulrun** [supabase/supabase#21312]
### Discussed in https://github.com/orgs/supabase/discussions/21311

<div type='discussions-op-text'>

<sup>Originally posted by **vulrun** February 16, 2024</sup>
 I need to bring to your attention an issue I've encountered while exploring logs from our sources. Since this morning, I've been experiencing an unexpected error, which is hindering my ability to access and analyze the necessary data.

Given the importance of this task and the impact it may have on our operations, I kindly request that you look into this matter at your earliest convenience. Swift resolution is crucial to ensure that we can continue our work effectively and without interruption. Attaching a screenshot for your reference.

![Screenshot from 2024-02-14 21-21-36](https://github.com/supabase/supabase/assets/20625306/cd8bffa9-864f-4e1e-a123-c82aee934590)</div>

**Comment by encima** [comment]
Thanks for reporting, please make sure you contact the Logflare support email as well!

This is happening when viewing logs in the dashboard or when viewing them through logflare?

**Comment by vulrun** [comment]
Yes, I already contacted them. Yes while viewing the logs in dashboard.

**Comment by encima** [comment]
@vulrun Was this resolved via Support ticket or is this still occurring?

**Comment by vulrun** [comment]
No, issue is still there.

**Comment by encima** [comment]
@vulrun can you provide the Ticket Number that you opened so I can check the progress? 🙏

**Comment by vulrun** [comment]
@encima Support Ticket ID: 2374775362

**Comment by Ziinc** [comment]
This has since been resolved.
