### ISSUE TITLE
Max height with overflow scroll not respected for Safari browser specifically

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#21356]
Potentially something to do with the tailwind classes, or CSS being rendered differently by Safari
![image](https://github.com/supabase/supabase/assets/19742402/5a7ce732-0b72-4a48-a35b-8fdffe503be8)

Partially from this [PR](https://github.com/supabase/supabase/pull/21069)
The changes there helped to remove some magic numbers (which is great and we should strive for that) but seems like Safari is unhappy with it

Last checked on Safari 17.3

**Comment by Mohammed-Yasin-Mulla** [comment]
@joshenlim, have you tried using plain CSS to verify this is not a tailwind issue?

I wish I could do it myself, but I am not a Mac user

**Comment by joshenlim** [comment]
Yup! Its not a tailwind issue, it's a CSS issue for Safari specifically - perhaps needs some investigation whether we can circumvent this without resorting back to magic numbers for Safari

**Comment by joshenlim** [comment]
@Mohammed-Yasin-Mulla sorry what do you mean by updates on Safari?

**Comment by Mohammed-Yasin-Mulla** [comment]
@joshenlim sorry for not being clear, I mean do you have any updates pending for Safari. Like you have for for other browsers like Chrome, you get a notification mentioning that there is a new update available?

**Comment by Mohammed-Yasin-Mulla** [comment]
Have you tries using the console to adjust the CSS values in Safari, I think it would be a good place to start. You can test out plain CSS properties and see if something would work.

**Comment by joshenlim** [comment]
@Mohammed-Yasin-Mulla 

> get a notification mentioning that there is a new update available?
ohhhhh gotcha! no worries at all! 😄 I don't have a notification that indicates an available update for safari

> you can test out plain CSS properties 
yup - its the way safari renders certain css, in particular the flex ones
i'll see if i can investigate further into this one within this week or next but I can't guarantee unfortunately as we're working on other things at the same time too 🙏
