### ISSUE TITLE
Local edge functions runtime cannot be reached when requested through a local database webhook

### ISSUE THREAD

**Issue by divmgl** [supabase/supabase#21394]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Creating a database webhook locally that points to an edge function fails with "Couldn't connect to server".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an edge function named `test` with just `Deno.serve(() => {})`
2. Run `supabase start`, then `supabase functions server`.
3. Go to the dashboard and create a webhook that points to `http://127.0.0.1:54321/functions/v1/test`.
4. Trigger the webhook through a database operation.
5. Observe `net._http_response` `error_msg`: `Couldn't connect to server`
 
## Expected behavior

Supabase reaches the server.

## Screenshots

<img width="360" alt="Screenshot 2024-02-20 at 7 47 07 AM" src="https://github.com/supabase/supabase/assets/5452298/67d2f3d9-515d-4eb8-9e30-db08b4a919db">

## System information

- OS: macOS

**Comment by divmgl** [comment]
Confirmed this was a local networking issue, solution found here: https://discord.com/channels/839993398554656828/1209480074953359360/1209498009004417135 Closing!

**Comment by stefan-girlich** [comment]
@divmgl Do I understand correctly that you hardcoded `http://127.0.0.1:54321/functions/v1/test` for the webhook?
I'm currently looking for a way to use edge functions in webhooks locally ([ongoing discussion](https://github.com/supabase/cli/issues/1705))
