### ISSUE TITLE
Example: Todo app using Next.js

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#214]
# Feature request

## Is your feature request related to a problem? Please describe.

New example use case

## Describe the solution you'd like

- Create a initial React app in `examples/todos-nextjs` using Next.js
- Build a todo list app, using Supabase as the backend. Use the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example.
- Should include logins + policies
- Add a one-click deploy using Vercel deploy button

## Additional context

- Ant has done an example [here](https://github.com/supabase/supabase/tree/master/examples/todo), which is a good baseline
- I suggest this is done with pure JS, rather than TS
- Keep it as simple as possible - for styling we can use Tailwind

**Comment by bharati-21** [comment]
Hey @kiwicopple, I would like to work on this. I have worked with React but not Next.js. 
But would love to learn and work on this issue if it's okay! Would like to know more about policies and logins.
Thank you.

**Comment by thorwebdev** [comment]
@bharati-21 that would be great :) We're sussing out a central schema for all the TODO samples here: #223.

**Comment by devalnor** [comment]
Hi, I have started a setup of NextJS with an AuthManager component.
Out of this t-shirt things, do you expect a pull request when all the features requirement are complet or can we work on it progressively?

**Comment by kiwicopple** [comment]
Feel free to create a new issue/example if it's different from this @devalnor . You can definitely work on it progressively - the smaller the task the better really
