### ISSUE TITLE
Delete a foreign key relationship in a table from the dashboard deletes the entire list of foreign keys

### ISSUE THREAD

**Issue by HichamELBSI** [supabase/supabase#21409]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Clicking on delete a foreign key relationship in a table from the dashboard deletes the entire list of foreign keys in the table.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. From the dashboard, go to database and edit a table
2. Scroll down to foreign keys section and create multiple foreign keys
3. Click on the cross icon button to remove the first foreign key
4. All the foreign keys will be removed

## Expected behavior

I expect only the first key to be removed

## Screenshots

https://github.com/supabase/supabase/assets/7756284/a35fd9cc-ef63-4bfd-931a-3f2415d3f174

## System information

- OS: Mac OS
- Browser: Chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Mohammed-Yasin-Mulla** [comment]
@HichamELBSI ,
Tried reproducing this in the dev set-up but was unable to do so. 

[Screencast from 22-02-24 08:06:58 PM IST.webm](https://github.com/supabase/supabase/assets/55092280/5f5c7cdf-d7b9-4bd5-aca7-697bce5bfc1c)

Is there anything I have missed that I can try to re-produce the issue?

OS: Ubuntu
Browser: Chome

**Comment by Mohammed-Yasin-Mulla** [comment]
Just to re-confirm it, I also tested on  `supabase.com` as well. everything seems to work fine.
I wish I could share a video clip. but that would expose sensitive data

**Comment by faisalsaifii** [comment]
Not able to reproduce either

**Comment by HichamELBSI** [comment]
You're right, I can't reproduce it anymore either 🤔. I don't know why it happened to me several times that day. Thanks for the quick reply anyway 🙏🏽.
