### ISSUE TITLE
Issue with local file upload

### ISSUE THREAD

**Issue by trafargarlaw** [supabase/supabase#21417]
**Describe the bug**
I've updated supabase cli to the current version 1.145.4, and since then, when running supabase locally, I have a problem with file upload, when I upload a file manually or any other way, the GUI shows "uploading 1 file ..." It stays at 0%, nothing happens.

I tried many things to solve the problem, nothing helped, so I checked on another Mac, and It had the same issue.
I tried at some point to downgrade to the previous version  `1.142.2` and it **started working again**.

**To Reproduce**
1. Initialize an empty project with version 1.145.4 of supabase cli (its the latest one currently)  `supabase init`
2. Run `supabase start`
3. Open the studio default url is http://127.0.0.1:54323 
4. In the sidebar navigate to storage
5. Create a New Bucket
6. Click on the created bucket and click on upload files
7. And you can see that it will be loading infinitely 

**Expected behavior**
The loading to finish and the file to upload

**Screenshots**
![image](https://github.com/supabase/cli/assets/59838799/9aa7a72e-e177-4279-b713-31b65d513ccf)

**System information**
 - OS: macOS 14.0
 - Version of CLI: 1.145.4
 - Versions of services:
 supabase/postgres         15.1.0.147            
 supabase/gotrue           v2.132.3              
 postgrest/postgrest       v12.0.1               
 supabase/realtime         v2.25.50              
 supabase/storage-api      v0.46.4               
 supabase/edge-runtime     v1.36.1               
 supabase/studio           20240205-b145c86      
 supabase/postgres-meta    v0.77.2               
 supabase/logflare         1.4.0                 
 bitnami/pgbouncer         1.20.1-debian-11-r39  
 darthsim/imgproxy         v3.8.0   

**Additional context**
 - Version of Node.js v20.8.1

**Comment by giusdp** [comment]
I'm experiencing the same problem. Tried out the beta version and it's working with that. I guess it's already solved for the next release.

**Comment by johnconnorquigley** [comment]
Experiencing the same issue:

**System information**
OS: macOS 14.1
Version of CLI: 1.153.4
Services:
    supabase/postgres 15.1.1.22 
    supabase/gotrue v2.143.1     
    postgrest/postgrest v12.0.2           
    supabase/realtime v2.27.5        
    supabase/storage-api v0.48.2   
    supabase/edge-runtime v1.41.3      
    supabase/studio 20240326-5e5586d
    supabase/postgres-meta v0.80.0 
    supabase/logflare 1.4.0 
    bitnami/pgbouncer 1.20.1-debian-11-r39
    darthsim/imgproxy v3.8.0

**Comment by sdsd4564** [comment]
still same issue with #23143

**Comment by Hallidayo** [comment]
Hi all, just checking in here are you still experiencing the same issue on local versions?

**Comment by trafargarlaw** [comment]
Haven't got it since then personally

**Comment by Hallidayo** [comment]
@trafargarlaw - Thank you for confirming. I'll close this one for now, but if happens again please feel free to re-open.

**Comment by tomaddison** [comment]
This issue appears to have returned. Upon initiating a brand new local development project, I'm unable to upload files larger than 6MB to any given storage bucket.

System information
OS: macOS 14.5
Version of CLI: 1.226.3
Services:
supabase/postgres 15.6.1.139
supabase/gotrue v2.164.0
postgrest/postgrest v12.2.0
supabase/realtime v2.30.34
supabase/storage-api v1.6.8
supabase/edge-runtime v1.65.3
supabase/studio 20241106-f29003e
supabase/postgres-meta v0.84.2
supabase/logflare 1.4.0

**Comment by alfietapping** [comment]
experiencing same issue using dashboard to upload photos, seemingly anything over 500kb is being rejected even though i have a max 50mb allowance

**Comment by bulutyerli** [comment]
Currently I am having this issue after the latest update.

**Comment by nxnzesrc** [comment]
Same I started getting this issue now, it used to previously

**Comment by skeddles** [comment]
ive never used this tool before today, but I seem to be getting the same thing.
It looks like it's uploading and it says "Uploading 1 file..."
but after a few seconds that just disappears, and no file is uploaded.

you can upload to storage via the api, its just the gui that doesn't work

console:
<img width="1218" height="676" alt="Image" src="https://github.com/user-attachments/assets/ef732a57-8005-4fe4-974c-991120aabaff" />

**Comment by sleighsoft** [comment]
Having the same issue as @skeddles

**Comment by yanminthwin-i4b** [comment]
same issue. cannot upload any file to supabase storage locally.

**Comment by aoricci** [comment]
change de version of the studio image: supabase/studio:20250224-d10db0f

**Comment by DigitalSolomon** [comment]
This happens to me on the Supabase production website using Safari (Version 18.0 (20619.1.26.31.6)) on macOS (15.0 (24A335)) . Doesn't matter what I try to upload, it can be a small 50 kB image to a storage bucket, it hangs for at least a minute, and I usually see something like this in the log:

```
[Log] Total time taken for 1 files: 62.684 seconds (main-afaa34738bb85a34.js, line 18)
[Log]   ERR (main-afaa34738bb85a34.js, line 18)
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
write
(anonymous function) — _app-3db04461e9b5a71d.js:2:199227
r — main-afaa34738bb85a34.js:15:4317
```

**Comment by nasedd** [comment]
Same issue on the website describe by @DigitalSolomon .
Safari Version 18.5 (20621.2.5.11.8)
MacOS Sequoia Version 15.5 (24F74)

it works for pdf but not for image.jpg
