### ISSUE TITLE
Difference in used email template between hosted supabase and local environment when using signInWithOtp

### ISSUE THREAD

**Issue by eensander** [supabase/supabase#21421]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When the method `sb.auth.signInWithOtp` is called with an email-address that has not signed up before, there is a difference in the email template that is being used when we use the local development `API` and `ANON_KEY` vs. the by-supabase-hosted `API` and `ANON_KEY`:
- With the local environment, the *magic-link* template is used,
- With the hosted environment, the *confirmation* template is used. 

For subsequent calls to this method, the *magic-link* template is used for eighter service (as expected).

#### Minimal reproduction code:
  
`index.ts`:
```ts
import { createClient } from "@supabase/supabase-js"

const env_hosted = {
  URL: "https://<project-id>.supabase.co",
  ANON_KEY: "<copy from supabase.com>"
}

const env_local = {
  URL: "http://127.0.0.1:54321",
  ANON_KEY: "<copy from terminal>"
}

const email = "<your test-email>";

const env = env_hosted;
const sb = createClient(env.URL, env.ANON_KEY)

sb.auth.signInWithOtp({email})
  .then((res) => {
    console.log("Email sent", res);
  })
```

`package.json`:
```js
{
  "name": "test-confirm-email",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@supabase/supabase-js": "^2.39.7",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "supabase": "^1.145.4"
  }
}
```

#### Steps to scaffold:

1. Copy above to new folder
2. Install dependencies (`pnpm install`)
3. Init local supabase (`pnpm supabase init`)
4. Start local supabase container (`pnpm supabase start`)
5. Create project on supabase.com
6. Fill in all the placeholders in index.ts

#### Steps to reproduce:

1. Run with `const env = env_hosted`. 
    - In your regular inbox, you will receive an email with subject "Confirm Your Signup" (which indicates confirmation email template)
2. Run with `const env = env_local`.
    - In your inbucket inbox, you will receive an email with subject "Your Magic Link" (which indicates magic-link email template)

## Expected behavior

I expect both reproduction scenario's to use the same email template. It seems that the hosted behavior has changed. This new behavior seems to make sense, however it should be the same in the local installation.

## System information

- OS: Windows
- Version of "@supabase/supabase-js": "^2.39.7",
- Version of "supabase": "^1.145.4",
- Version of ts-node: v10.9.1

**Comment by Adityagaddhyan** [comment]
This is not a bug. You need to make changes in your env file. This env variable is used to store the subject for signup confirmation mail:
`GOTRUE_MAILER_SUBJECTS_CONFIRMATION` 
the `ConfirmationMail` in  `internal/mailer/template.go` in https://github.com/supabase/gotrue uses the m.Config.Mailer.Subjects.Confirmation to choose the subject of the mail.

**Comment by eensander** [comment]
@Adityagaddhyan Thanks you for your reply. I'm not sure whether I completely get your suggestion or you get my problem. I was using the difference in the subject being used as a basic indicator for the template being used. But to rephrase: 
- when using the `env_hosted`, and thus relying on the **hosted** supabase instance, the first email for a given email-address:
  - has subject **"Confirm Your Signup"**,
  - has contents **"Follow this link to confirm your user: Confirm your mail"**,
  - therefore, it can be inferred that it is using the `auth.email.template.confirmation` template
- when using the `env_local`, and thus relying on the **local** supabase instance, the first email for a given email-address:
  - has subject **"Magic Link"**,
  - has contents **"Follow this link to login: Log In\nAlternatively, enter the code: XXXXX"**,
  - therefore, it can be inferred that it is using the `auth.email.template.invite` template

Your response seems to simply suggest changing the subject of the confirmation email-template. However, the problem I'm experiencing is that for the same action we are seeing different behavior locally from the hosted supabase instance, namely: the template being used. Since we change the actual contents of the templates, this makes it difficult to test local and production variants because of a difference in behavior. 

@kangmingtay Can I ask why the issue is closed? In my test script I just updated supabase to `supabase 1.150.0` and re-ran the script and I still experience the described difference in behavior.

Perhaps something is wrong with my local setup or configuration, so it would be awesome if someone could test if this behavior is reproducible or merely an artifact of this test project and our real production project where we're found out about this problem.
