### ISSUE TITLE
edge functions cannot send a request

### ISSUE THREAD

**Issue by fudg1211** [supabase/supabase#21453]
# Bug report

`
const result = await fetch("https://api.dingtalk.com/v1.0/contact/users/me", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        "x-acs-dingtalk-access-token": accessToken,
      }
`

When i update supabase-edge-functions, then throw error.
Previously it was good.

`
[Error] TypeError: error sending request for url (https://apple.com/): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async Object.handler (file:///home/deno/functions/auth/index.ts:37:17)
    at async handleHttp (ext:sb_core_main_js/js/http.js:66:17)
`

**Comment by encima** [comment]
Thanks for reporting this, @fudg1211.

Do you have a minimal example to reproduce?
Is it only requests to apple.com or is it any domain?
Also, does this occur on Supabase Cloud as well as self-hosted?

**Comment by botxboom** [comment]
Hi @fudg1211 , are you still facing this issue ?
Could you provide repro steps ?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
