### ISSUE TITLE
Vault: Error adding encryption to column

### ISSUE THREAD

**Issue by zzev** [supabase/supabase#21465]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to add column encryption to one of my tables, but I'm failing miserably. For context, I'm doing it on localhost.

Based on an example I found on [this issue](https://github.com/orgs/supabase/discussions/13316) and [this article](https://supabase.com/blog/transparent-column-encryption-with-postgres), this is what I'm doing:

```
-- Activate the extension
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

-- Alter table users to hold a key_id (uuid) that references pgsodium.key.id
ALTER TABLE public.users
  ADD COLUMN key_id uuid NOT NULL REFERENCES pgsodium.key(id) DEFAULT (pgsodium.create_key()).id UNIQUE;

-- Add columns key_id (uuid) to table variables
ALTER TABLE public.variables ADD COLUMN key_id uuid REFERENCES users(key_id);

-- Add security label that encrypts 
SECURITY LABEL FOR pgsodium ON COLUMN
  variables.value IS 'ENCRYPT WITH KEY COLUMN key_id ASSOCIATED (user_id)';
```

The error I'm getting is:

```
ERROR:  syntax error at or near ","
LINE 7: ,       
        ^
QUERY:  
    DROP VIEW IF EXISTS public.decrypted_variables;
    CREATE VIEW public.decrypted_variables  AS SELECT 
                id,       
        name,       
        value,
,       
        environment_id,       
        created_at,       
        updated_at,       
        user_id,       
        key_id
    FROM public.environments_variables;
    ALTER VIEW public.decrypted_variables OWNER TO postgres;
    
CONTEXT:  PL/pgSQL function pgsodium.create_mask_view(oid,integer,boolean) line 38 at EXECUTE
SQL statement "SELECT pgsodium.create_mask_view(objoid, objsubid, debug)
    FROM pg_catalog.pg_seclabel sl
    WHERE sl.objoid = target
      AND sl.label ILIKE 'ENCRYPT%'
      AND sl.provider = 'pgsodium'"
PL/pgSQL function pgsodium.update_mask(oid,boolean) line 4 at PERFORM
SQL statement "SELECT pgsodium.update_mask(r.objid)"
PL/pgSQL function pgsodium.trg_mask_update() line 24 at PERFORM
```

## Expected behavior

I expect the view to be created correctly.

## System information

- OS: macOS

**Comment by GaryAustin1** [comment]
I'm closing this for now as you also have a discussion open and are really looking for help at this point based on what I see.
If this turns out to be a bug I'll reopen it.
