### ISSUE TITLE
Can't edit column contraints in Dashboard

### ISSUE THREAD

**Issue by dippa-1** [supabase/supabase#21473]
# Bug report

## Describe the bug

When trying to change the contraint on my column, I get an error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. In Supabase dashboard (not self-hosted), go to tables -> columns of a table
2. Create a new column 'test', type text, non-nullable, leave constraints empty
3. Edit column and change constraints from nothing to e.g. length 2000
4. It should work
5. Change the constraints to 2001 length
6. The error pops up

## Expected behavior

There should be no error. Maybe when editing the column the first time the constraint ID is different than expected later on?

## Screenshots

<img width="761" alt="image" src="https://github.com/supabase/supabase/assets/46935291/2ca979ce-0c8b-494f-b762-4e0822dd7d68">

## System information

- Hosted cloud version

**Comment by faisalsaifii** [comment]
@dippa-1 Unfortunately I'm unable to replicate this issue, could you please let me know whether I performed any step wrongly.
Attaching a series of screenshots:

1. Creation of column:
<img width="312" alt="Creation of column" src="https://github.com/supabase/supabase/assets/47176738/f70bdd64-676b-4c34-9544-a8d18315aa3d">

2. Adding constraint: 
<img width="316" alt="Adding constraint" src="https://github.com/supabase/supabase/assets/47176738/202f7b82-0b72-4855-8c09-fd6c45ff2850">

3. Editing constraint: 
<img width="315" alt="Editing constraint" src="https://github.com/supabase/supabase/assets/47176738/12696f98-2b3a-4e2b-9897-af1a13b70765">

**Comment by dippa-1** [comment]
That's weird. Did you hit save after each step?
If so, you can close it if it only happens in my project

**Comment by faisalsaifii** [comment]
Yes, saved at every step
