### ISSUE TITLE
Unable to make existing column unique in Studio

### ISSUE THREAD

**Issue by garmeeh** [supabase/supabase#21489]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On Studio I do not have an option to make a column unique. Example

![CleanShot 2024-02-23 at 14 17 50@2x](https://github.com/supabase/supabase/assets/13333582/856d58a9-afc9-4afb-889c-908d8f9303e7)

No issue when adding a new column:

![CleanShot 2024-02-23 at 14 16 27@2x](https://github.com/supabase/supabase/assets/13333582/6dcf30f9-031d-44bd-825d-8d1f884e62c6)

## System information

- OS: macOS
- Browser: Chrome

**Comment by GaryAustin1** [comment]
If you edit the column itself you have that option.

**Comment by GaryAustin1** [comment]
Not from edit table link on side panel.
![image](https://github.com/supabase/supabase/assets/54564956/37d89c04-4ee3-4340-965f-5e2171c094b8)

If you edit column the column directly from the column titles then you can.
![image](https://github.com/supabase/supabase/assets/54564956/fe3bf444-4acf-467b-bed9-a7d5de99762e)

**Comment by GaryAustin1** [comment]
![image](https://github.com/supabase/supabase/assets/54564956/76ad86f5-6db6-44db-b977-8e29a860da12)
You can see in this case it knows I set it to unique from the column mode.  But no option to toggle it.

**Comment by joshenlim** [comment]
^ gotcha on this! on it :)
