### ISSUE TITLE
timescaledb hypertable breaks realtime (supabase cloud)

### ISSUE THREAD

**Issue by bitnom** [supabase/supabase#21481]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

timescaledb hypertable breaks realtime, after a time.

## To Reproduce

- create a timescaledb hypertable
- enable realtime for the table via dashboard
- continuously insert rows to table until realtime no longer works

At that point, it is no longer possible to disable realtime for that table, and the table must be dropped and recreated to get realtime working again for that table. Restarting the database does not help. There is an associated error, which I forgot to copy when it happened. It should be reproducible. I have produced it twice. I will run a test today to see if I can get more related logs.

## Expected behavior

- Guardrails in tools (CLI/Dashboard) should be implemented to disallow replication on hypertables
- Realtime should not enable for hypertables

## System information

- supabase cloud
- the realtime client does not matter (js, python, and the realtime client in dashboard)

**Comment by encima** [comment]
I assume the error you see is something like `relation _hyper_X_X_chunk is not part of the publication`?

This is an issue for realtime/dashboard to disallow enabling realtime on hypertables as they do not replicate like "normal" PG tables.

**Comment by bitnom** [comment]
> I assume the error you see is something like `relation _hyper_X_X_chunk is not part of the publication`?
> 
> This is an issue for realtime/dashboard to disallow enabling realtime on hypertables as they do not [replicate](https://github.com/timescale/timescaledb/issues/1138) like "normal" PG tables.

I haven't had time to circle back to it and get the error, but you're saying we shouldn't be using realtime with hypertables anyway? That sucks, though tbh I think I'll be migrating to an alternative after this MVP. I read a doc (I think it was a supabase doc) explaining how Realtime isn't at all scalable. 

Super disappointing since Realtime really helped sell me on the service. I've thought about rolling my own realtime but idk enough about postgres internals to expect it to turn out any which way.

**Comment by encima** [comment]
That is a shame to hear, if you want to provide the link and/or plans of scaling then we can help here. 

Realtime itself does have limits in the hundreds of thousands with constant changes but there are many ways to handle this in order to scale further.

If you are expecting that scale, then it would make sense to implement a sort of queuing system to subscribe and pass messages on to all relevant clients.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
