### ISSUE TITLE
unable to proceed if supabase package not installed

### ISSUE THREAD

**Issue by noWarm** [supabase/supabase#21498]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

when i run `npx supabase gen types typescript --project-id <PID> > src/lib/supabase/database.types.ts`, the terminal keeps running forever because the instruction is written to the file not to the terminal log.
```bash
Need to install the following packages:
supabase@1.145.4
Ok to proceed? (y) 
```

## To Reproduce
1. setup npm project, but didn't install(update?) supabase package via `npm install` yet.
2. login to supabase cli
3. then run `npx supabase gen types typescript --project-id <PID> > src/lib/supabase/database.types.ts`
4. open the `src/lib/supabase/database.types.ts` file to see the instructions, while terminal freezes.

note: i'm not really sure why this happens, because I had already logged in via supabase cli a long time ago so I thought the supabase package should be in my node_modules already.

## Expected behavior

instructions are shown on terminal so users could proceed instead of getting written to the file itself.

## Screenshots

![image](https://github.com/supabase/supabase/assets/69838828/f24e60a3-e210-4c47-bf65-876d1ca7d25f)

## System information

- OS: [Windows]
- Version of supabase-js: [1.145.4]
- Version of Node.js: [20.9.0]

**Comment by safwanyp** [comment]
I'm not sure whether this will work on Windows as I haven't used one in a long time, but the problem is because of the way the `>` operator works. It redirects all std output to the specified location which is `src/lib/supabase/database.types.ts` in this case. 

You can try to do this instead:
```bash
npx supabase gen types typescript --project-id <PID> 2>&1 | tee src/lib/supabase/database.types.ts
```
Keep in mind that this might still cause your `database.types.ts` to have the prompt to install supabase. You can just delete it after.

**Comment by encima** [comment]
Thanks for opening this, this is an `npx` issue mostly I suppose. A few ways to resolve:
1. Use `npm`/`pnpm` etc to install the package on your system
2. Use [yes](https://linuxconfig.org/yes) with the command: `yes | npx ...`
