### ISSUE TITLE
Using PKCE flow messes with the refreshing of the provider token

### ISSUE THREAD

**Issue by joostwmd** [supabase/supabase#21490]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using Spotify as an oAuth provider in my app. I can sign in via the PKCE flow, but i am unable to refresh the spotify oAuth token, following the official spotify [documentation](https://developer.spotify.com/documentation/web-api/tutorials/refreshing-tokens). 

this is my implementation according to the spotify docs:

```
async function refreshToken() {
		if (!session?.provider_refresh_token) {
			throw new Error('no session found');
		}

		const client_id = 'my id';
		const client_secret = 'my secret';

		const body = new URLSearchParams({
			grant_type: 'refresh_token',
			refresh_token: session.provider_refresh_token,
			client_id
		});

		const response = await fetch('https://accounts.spotify.com/api/token', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded'
				//Authorization: 'Basic ' + btoa(client_id + ':' + client_secret)
			},
			body: body
		});
		if (response.ok) {
			const data = await response.json();
			console.log('Success:', data);
			return data;
		} else {
			// It's important to catch and handle errors properly
			const errorData = await response.json();
			console.error('Error:', errorData);
			throw errorData;
		}
	}
```

with this i am getting an error 400 along with an empty error message.

`"{error: 'invalid_request', error_description: ''}`

After a lot of playing around i found out that setting an Authorization header like this
`Authorization: 'Basic ' + btoa(client_id + ':' + client_secret)`
makes it possible to refresh the token. However, doing it like this exposes the client secret in the browser, but the idea behind the about PKCE flow is that you don't have to do that. The [spotify documentation](https://developer.spotify.com/documentation/web-api/tutorials/refreshing-tokens) also don't mention that you have to pass the client secret in the PKCE flow. **But it is required for the normal (no PKCE) Authorization Code flow.** This is where i started to suspect that supabase might not use the PKCE flow as intended. 

Then i decided to set up the pkce flow without supabase, to check if the error might be on Spotifys side. I cloned [this repo](https://github.com/tobika/spotify-auth-PKCE-example) and i was able to refresh the token without providing my client secret, so the Spotify API works.

That leaves only supabase in the equation. I think the issue is that when sining in via supabase oAuth, something happens under the hood, that makes the provider think you are not using the PKCE flow. At least that could explain, why i am forced to supply my client secret when refreshing the token later.   

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I tried it in both sveltekit and react native, both with the same results.

### SVELTEKIT

In sveltekit  i am initializing the supabase client like this: 

```
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';
import type { LayoutLoad } from './$types';
import { createBrowserClient, isBrowser, parse } from '@supabase/ssr';

export const load: LayoutLoad = async ({ fetch, data, depends }) => {
	depends('supabase:auth');

	const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		global: {
			fetch
		},
		cookies: {
			get(key) {
				if (!isBrowser()) {
					return JSON.stringify(data.session);
				}

				const cookie = parse(document.cookie);
				return cookie[key];
			}
		},
		auth: {
			flowType: 'pkce'
		}
	});

	const {
		data: { session }
	} = await supabase.auth.getSession();

	return { supabase, session };
};
```

here is the sign in function 

```
 export const signIn = async (supabaseClient: SupabaseClient) => {
	const PUBLIC_BASE_URL = dev ? 'http://localhost:5173' : 'https://onbeat.joostsworld.dev';
	const scopes = [
		'playlist-read-collaborative',
		'playlist-read-private',
		'playlist-modify-public',
		'playlist-modify-private',
		'user-read-email',
		'user-read-private',
		'user-read-playback-position',
		'user-top-read'
	];
	try {
		const { error, data } = await supabaseClient.auth.signInWithOAuth({
			provider: 'spotify',
			options: {
				redirectTo: `${PUBLIC_BASE_URL}/auth/callback`,
				scopes: scopes.join(' '),
			}
		});
		const code_challenge = new URL(data.url!).searchParams.get('code_challenge');
		if (error) {
			console.error(error);
			return { status: 500, message: 'Failed to sign in' };
		}
		return { status: 200, message: 'Successfully signed in' };
	} catch (err) {
		console.error(err);
		return { status: 500, message: 'An error occurred during sign in' };
	}
};
```

and here i am extracting the code from the callback url and exchanging it against a token

```
export const GET = async (event) => {
	//console.log('callback server', event);
	const {
		url,
		locals: { supabase }
	} = event;

	const code = url.searchParams.get('code') as string;

	console.log('code', code);

	if (code) {
		const { error } = await supabase.auth.exchangeCodeForSession(code);
		if (!error) {
			throw redirect(303, '/playlist');
		}
		throw redirect(303, '/playlist');
	}

	// return the user to an error page with instructions
	throw redirect(303, '/');
};
```

### React Native

In my React Native App i am initializing my supabase client like this:

```
import "react-native-url-polyfill/auto"
import { createClient } from "@supabase/supabase-js"
import { DeviceStorage } from "./DeviceStorage"

const url: string | undefined = process.env.EXPO_PUBLIC_SUPABASE_URL
const key: string | undefined = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY

export const supabase = createClient(url!, key!, {
  auth: {
    storage: DeviceStorage,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    persistSession: true,
    flowType: "pkce",
  },
})
```

here is the sign in function:

```
async function handleSocialSignIn(provider: Provider, scopes: string[]) {
    console.log("Initiating login with provider:", provider)

    const redirectTo = AuthSession.makeRedirectUri()

    try {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: provider,
        options: {
          redirectTo,
          scopes: scopes.join(" "),
          skipBrowserRedirect: true,
        },
      })

      if (data && data.url) {
        await WebBrowser.openBrowserAsync(data.url, {})
      }

      if (error) throw error
    } catch (error) {
      console.error("Login error:", error)
    }
  }

```

and here is how i handle the callback url and extract the code + exchange it for a session

```

  const handleRedirect = useCallback(async (event: any) => {
    const url = new URL(event.url)
    const code = url.searchParams.get("code")

    if (code) {
      const { data, error } = await supabase.auth.exchangeCodeForSession(code)

      if (error) throw error

      const provider_token = data.session?.provider_token
      const provider_refresh_token = data.session?.provider_refresh_token

      if (provider_token && provider_refresh_token) {
        console.log(
          "Storing provider tokens:",
          provider_token,
          provider_refresh_token
        )
        await storeProviderToken(provider_token)
        await storeProviderRefreshToken(provider_refresh_token)
        router.replace("/(protected)/profile")
      } else {
        console.log(
          "no provider tokens found in session response:",
          data.session
        )
      }
      WebBrowser.dismissBrowser()
    }
  }, [])

  useEffect(() => {
    const subscription = Linking.addEventListener("url", (event) =>
      handleRedirect(event)
    )
    return () => subscription.remove()
  }, [handleRedirect, provider])

```
This is not exactly the way it is shown in the docs, but this is intended.

The Sign In works as expected but calling the refreshToken function during an active session results in the error. I know that it isnt an error from wrong credentials like the client id or refresh token because this produces related error messages, but i am receiving an empty string. Also when adding the Authorizaiton header and changing nothing else, i can refresh the token, so wrong credentials are not the cause of this error

To reproduce the vanilla js PKCE flow, you can just clone [this repo](https://github.com/tobika/spotify-auth-PKCE-example) and use your client id and url

## Expected behavior

Being able to refresh the provider token after sining in via supabase using the PKCE flow

**Comment by encima** [comment]
Closing in favour of the issue on the [gotrue](https://github.com/supabase/gotrue/issues/1450) repo.

Thank you for the thorough reproduction and explanation of the issue. In future, please only open one issue per...issue. 🙏
