### ISSUE TITLE
I have deployed Supabase locally, but encountered errors when creating users and performing third-party authentication

### ISSUE THREAD

**Issue by qeuyee** [supabase/supabase#21502]
![image](https://github.com/supabase/supabase/assets/31116292/a48ae916-cd03-4045-b833-82ddc73aa221)
![image](https://github.com/supabase/supabase/assets/31116292/a8cab1ed-3773-4563-a8ca-30ce39203798)

**Comment by beardsleym** [comment]
![Screenshot 2024-02-23 at 9 51 04 PM](https://github.com/supabase/supabase/assets/6046506/8fa67d1e-ac41-414d-b0da-d749190af292)

Interesting, I have the same issue, haven't had a chance to look into it yet though.

**Comment by encima** [comment]
thanks for opening! this has been reported so closing in favour of the already open #21476
