### ISSUE TITLE
Cannot serve PDF from Supabase storage

### ISSUE THREAD

**Issue by arepp23** [supabase/supabase#21515]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a PDF which has been uploaded to Supabase storage. I can click download via the dashboard and can view my downloaded PDF locally or in chrome.

When I click Get Url or programmatically get the public URL, opening that in Chrome leads to an error with Error Failed to load PDF document. I'd like to be able to serve this PDF to my users in my Next.js app.

I have enabled an RLS policy on the bucket which allows everything for public, and the bucket itself is public. I can serve JPG images from this same bucket with no problems.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upload PDF file to storage
2. Click `Get URL` or programmatically get public URL.
3. Open URL in chrome

## Expected behavior

PDF should load from URL

## Screenshots

![image](https://github.com/supabase/supabase/assets/53490143/5d0f8a59-ade7-448e-962a-48d395f02184)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js:^2.39.6
- Version of Node.js: 18.17.0

## Additional context

File type shows as `text/plain` in the dashboard for this file
![image](https://github.com/supabase/supabase/assets/53490143/0c4bacd3-b831-4f24-9180-635e8c5766cc)

**Comment by GaryAustin1** [comment]
![image](https://github.com/supabase/supabase/assets/54564956/8262016c-6161-4f43-a7c5-a670906d66d4)
Seems like you have maybe an upload issue.  Try uploading from the UI and see if the file loads correctly.

**Comment by arepp23** [comment]
Turns out I had to use `contentType: "application/pdf"` in the `FileOptions` when uploading. Odd that it cannot infer the file type on its own from the file extension or file metadata, but it can via dashboard upload.

**Comment by GaryAustin1** [comment]
Going to close this as not sure it is a bug.
