### ISSUE TITLE
[DOCS] NextJS getting started docs should have a CTA in the end

### ISSUE THREAD

**Issue by Hahlh** [supabase/supabase#21517]
# Improve documentation

## Link 

[https://supabase.com/docs/guides/getting-started/quickstarts/nextjs](https://supabase.com/docs/guides/getting-started/quickstarts/nextjs)

## Describe the problem

After the successful completion of the main entry point tutorial for NextJS users (?) & the wonderful output of notes fetch, there isn't any "next step" hinted at.

## Describe the improvement

It would be very nice to be guided to the next step or multiple potential next steps. 

A more guided on-boarding flow with multiple steps is very useful both to the user and Supabase.

**Comment by Michael-Obele** [comment]
Hello, as an active Supabase user, I agree with this suggestion and would love to implement it.
Though, aside from the "Web App Tutorials" section for Next.js (and other frameworks), are there any other pages worth linking to? It would also be ideal if it were implemented across as many frameworks as possible.

**Comment by Hahlh** [comment]
Hey, @Michael-Obele !

I would actually say that the best approach would be to create a streamlined on-boarding flow for Next.js users and then ask the question were this one fits in. 

The web app tutorial is unfortunately currently outdated (#21207), so potentially an overview over the potential next steps might be best. 
E.g.:
Next steps: 
- Setup auth using `@supabase/ssr`
- Fetch data with Next.js server actions
- ..

**Comment by Michael-Obele** [comment]
Thank you for pointing this out, I didn't even notice the Next.js docs have depreciated that much (I haven't used them in a while).
The "next steps" approach, I believe it will be much clearer for users. I'll be working on creating a few relevant links for beginners and submitting a pull request shortly. I appreciate your guidance on this issue.

**Comment by Michael-Obele** [comment]
Hey @Hahlh, I just finished up a pull request, and I'd love to get your (or anyone else's on the team!) feedback on it. I'm eager to learn and improve, so any insights would be greatly appreciated! Thanks a bunch!
