### ISSUE TITLE
supabase start, Error: missing signature key for Pulling from public.ecr.aws/supabase/

### ISSUE THREAD

**Issue by itxProfessor** [supabase/supabase#21514]
Trying to pull repository public.ecr.aws/supabase/postgres ...
15.1.0.147: Pulling from public.ecr.aws/supabase/postgres
failed to display json stream: missing signature key
Retrying after 4s: public.ecr.aws/supabase/postgres:15.1.0.147
Trying to pull repository public.ecr.aws/supabase/postgres ...
15.1.0.147: Pulling from public.ecr.aws/supabase/postgres
failed to display json stream: missing signature key
Retrying after 8s: public.ecr.aws/supabase/postgres:15.1.0.147
Trying to pull repository public.ecr.aws/supabase/postgres ...
15.1.0.147: Pulling from public.ecr.aws/supabase/postgres
failed to display json stream: missing signature key
Try rerunning the command with --debug to troubleshoot the error.

**Comment by encima** [comment]
Thanks for reporting!

Can you confirm this is not an issue with your system (i.e. pull the image on an ec2 instance or similar)? Pulling the image should work for 64-bit systems.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
