### ISSUE TITLE
[DOCS] Next.js "Getting Started" / "Quickstart" tutorial & webapp tutorial seem disjointed & collide

### ISSUE THREAD

**Issue by Hahlh** [supabase/supabase#21519]
# Improve documentation

## Link 

[https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?database-method=sql&language=ts](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?database-method=sql&language=ts)

## Describe the problem

It seems that the Framework Quickstart for Next.js somewhat collides with the guide that most users likely will use after they have finished it, the web app guide. 

The Framework Quickstart guide creates a `supabase` folder with the files of `client.ts`, `middleware.ts`, and `server.ts`. 

`middleware.ts` contains the following content:

```typescript

import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { cookies } from "next/headers";

export const createClient = () => {
  const cookieStore = cookies();

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: "", ...options });
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    },
  );
};
``` 

The web app guide immediately afterwards instructs to create `middleware.ts` with the following contents:

```typescript


import { createMiddlewareClient } from '@supabase/auth-helpers-nextjs'
import { NextResponse } from 'next/server'

import type { NextRequest } from 'next/server'

export async function middleware(req: NextRequest) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient({ req, res })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  // if user is signed in and the current path is / redirect the user to /account
  if (user && req.nextUrl.pathname === '/') {
    return NextResponse.redirect(new URL('/account', req.url))
  }

  // if user is not signed in and the current path is not / redirect the user to /
  if (!user && req.nextUrl.pathname !== '/') {
    return NextResponse.redirect(new URL('/', req.url))
  }

  return res
}

export const config = {
  matcher: ['/', '/account'],
}

```

These two seem to be in conflict. It's also not outlined where the web app tutorial `middleware.ts` is supposed to be created.  
It also feels like the web app tutorial isn't really a guide to get started with Supabase & Next.js, but more like an example project.

If I want to get up & running with Supabase & Next.js now, I don't want to create a ton of publically readable `profiles` tables.
I want to get auth, data fetching on the server hand in hand with `useContext`, real-time subscriptions, and the security setup in a more general way going. 

I can likely pick all these parts together from these various disjointed tutorials & get it working, but for me at least it feels like a "Getting Started" / "Framework Specific Quickstart" section could be a little less specific & a bit more guided in terms of on-boarding. 

Take this please as my initial impression of the docs first time using Supabase and feeling a bit "lost". 
I think other users might feel the same, but of course n=1.  
Also, I am writing this as I just started with the tutorials (as this perspective might be the most useful to you). 
It very well may be that I should just work through the web app "example project 2" and disregard the Quickstart completely as a mere "minimal project example 1" or that there are other parts of the documentation that I could follow in a more linear fashion or that I should simply go for the various specific documentation parts and put it all together, but at a bare minimum I feel that the naming of these sections could be improved, I expected something else.

**It might just be that I expected a normal "getting on-boarded" path and found something else. (feel free to close whenever you want)** 

I hope that's somewhat useful to you and thank you very much for integrating that deeply with Next.js / providing that much docs & content about it! 

Firebase still hasn't much material around regarding Next.js server side data fetching & auth and it's nice to see you caring about having material about all these!

## Describe the improvement

A clear and concise path of getting up & running with Supabase & Next.js that is less "example project"

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by IcedTea2K** [comment]
Hi @Hahlh, have you got some work going for this already? I'd like to take a jab at this issue :)

Also, I agree with your points, but my impression is that the "web app guide" is a more in-depth introduction to what Supabase could do. Maybe, it could be renamed to something like "web app demos" for more clarification... And the project  should be re-structured such that it could be picked up from the "Quickstart" instead.

**Comment by Hahlh** [comment]
Hey @IcedTea2K , nice to see you around here in this issue as well :)

Please feel free to go ahead, I am mostly getting accustomed with Supabase at the moment and collecting improvement opportunities from the perspective of a completely new user.

**Comment by IcedTea2K** [comment]
After digging a bit more, the doc went out of sync because framework quickstart is using `@supabase/ssr` and the guide uses `@supabase/auth-helpers-nextjs`. The latter package should have been replaced by the former one instead (according to [this](https://supabase.com/docs/guides/auth/auth-helpers/nextjs))
