### ISSUE TITLE
UX for adding single-column FKs got worse

### ISSUE THREAD

**Issue by patrick-ryan** [supabase/supabase#21512]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

hello supabase team!

I submitted feedback on the UI but wanted to get others' opinions as well. Just noticed this update to move column-level FKs to the table-level:
https://github.com/supabase/supabase/pull/21078

I'm not sure if others are experiencing the same pain, but my previous flow for adding a FK column was this:
1. create a column, select the reference column it points to

so easy! it was amazing how supabase could automate so much of the tediousness that would be required for manually writing DDL. but now... I noticed that since this moved to the table-level, it is a huge pain to do this:
1. first, look up the data type of the target column to reference to, make a note of that data type for later
2. create a source table column with that data type
3. edit the table-level FKs to set up the relationship

If you get to 3 and realize it was the wrong data type, you have to effectively start everything over, that's a lot of frustration and clicking around for what used to be basically one field. Not only that, but when creating the source column it tells you to edit the table to access FKs, with a link to take you there!, which is particularly aggravating given that the source column does not exist yet!! So you click that link to edit the table-level FKs and simply cannot, you have to back out, AND your progress on creating the new column is GONE.

This UX was one of the worst evolutions I've seen. I get the motivations were to support single- and composite- column FKs in a single place of the UI, but the price is heavy for the single-column FK workflow. I hope we can find some way to get back to the previous level of usability, as one of the primary draws to supabase for me is the ease of maintaining an RDBMS, and adding non-composite FKs is a way more common maintenance activity for me than creating a composite one.

PS.
I'd also like to say how much I appreciate this project, I'm starting a project and supabase has helped me get running a lot faster than if I had done other hosting. really hoping I can help the community as a whole with this feedback, if sensible.

## To Reproduce

Go to Table Editor, try to create a single-column FK.

## Expected behavior

Go to Table Editor, when adding a column make it easy to FK it to another column without worrying about data type.

## System information

- OS: Linux
- Browser (if applies): vivaldi

**Comment by Psypher1** [comment]
I am not the only one having issues with this. I assumed it was some change they made that they would correct later. Because, yes the prior method was way more suscint.

**Comment by MildTomato** [comment]
hey @patrick-ryan - just wanted to say your feedback was heard.

Some thoughts from myself. 

_(apologies i'm writing this quite late at night, hope it makes sense)_

1. I think it's fair that we look into supporting creating a FK from a column edit/create view, even if there's no composite support. Maybe composite FK create/edit support is not supported in column edit/create views. I'm sure there is something we can do. We can look into it 🚀.

2. There's a few issues possibly in the table edit view as well. It's not easy to add a new column to the list and then immediately assign a FK to it, that could be easier with a bit less cognitive effort. It could also be better to visually show which of the columns have a FK, with an easy way to identify/scroll down/highlight which of the FKs in the FK list are related to that column.
