### ISSUE TITLE
Several example projects are archived

### ISSUE THREAD

**Issue by cassidoo** [supabase/supabase#21521]
As seen [here](https://github.com/supabase/supabase/blob/79d806ad22624baf086df7385827dc73e9a38316/apps/www/data/Examples.ts#L197) and in a few other spots in that file, there's several example projects that are linked but that are in an [archived example repo](https://github.com/supabase/examples-archive), and probably shouldn't be used for reference until they're updated!

**Comment by Hallidayo** [comment]
Hi @cassidoo - I've had a look and I can see the examples are referenced in the [auth](https://supabase.com/auth) page. Do you think its worth adding a archived badge onto each card where the repo is archived or removing completely?

**Comment by cassidoo** [comment]
I think so, yes! I made a new project and clicked on one of the examples that popped up on the project dashboard, and realized only a bit later that it was an out-of-date example, so I do think it's worth sharing upfront.

**Comment by Hallidayo** [comment]
Cool I'll have a look at this.

**Comment by cassidoo** [comment]
Thank you!!

**Comment by Hallidayo** [comment]
Hi @cassidoo - Just created a pull now for both the studio and site for the archived repos.

**Comment by cassidoo** [comment]
Awesome, thank you! Woo hoo!

**Comment by cassidoo** [comment]
Thanks y'all!
