### ISSUE TITLE
[DOCS] Next.js server side auth - updateSession import not available

### ISSUE THREAD

**Issue by Hahlh** [supabase/supabase#21529]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/server-side/nextjs

## Describe the problem

In the "hook up middleware" step, `updateSession` is imported and used:
`import { updateSession } from '@/utils/supabase/middleware'`

It is not clear where this is all of a sudden coming from and it is not referenced in the server auth docs besides in this section. 

Potentially it was introduced in some other tutorial? 
In any case, it is likely that people will start with server auth and there shouldn't be such a dependency on information that isn't available in the current doc context.

## Describe the improvement

Add the contents of `updateSession` in an additional code tab.

**Comment by IcedTea2K** [comment]
I started a new supabase project recently with with `npx create-next-app`, it was part of the boilerplate. There's a comment section explaining exactly what the `updateSession` does.
```ts
export const updateSession = async (request: NextRequest) => {
  try {
    // This `try/catch` block is only here for the interactive tutorial.
    // Feel free to remove once you have Supabase connected.
    const { supabase, response } = createClient(request);

    // This will refresh session if expired - required for Server Components
    // https://supabase.com/docs/guides/auth/server-side/nextjs
    await supabase.auth.getUser();

    return response;
  } catch (e) {
    // If you are here, a Supabase client could not be created!
    // This is likely because you have not set up environment variables.
    // Check out http://localhost:3000 for Next Steps.
    return NextResponse.next({
      request: {
        headers: request.headers,
      },
    });
  }
};```

**Comment by charislam** [comment]
Hey, just double-checked the link and it looks like the `updateSession` code is already in the tab next to the middleware code:

<img width="647" alt="image" src="https://github.com/supabase/supabase/assets/26616127/61c2e813-741d-49b4-b906-9bb6ef670553">

Closing this because it looks solved, but feel free to reopen if you're not seeing it.

**Comment by Hahlh** [comment]
> Hey, just double-checked the link and it looks like the `updateSession` code is already in the tab next to the middleware code:
> <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/26616127/307900703-61c2e813-741d-49b4-b906-9bb6ef670553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODIyNDMsIm5iZiI6MTcwODk4MTk0MywicGF0aCI6Ii8yNjYxNjEyNy8zMDc5MDA3MDMtNjFjMmU4MTMtNzQxZC00OWI0LWI5MDYtOWJiNmVmNjcwNTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIxMTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhY2Y2OTY3NzY0MDIxMmUyNGUzZjAyZmJmNTBkMzFlNmNmYWI5Y2YxNTNiZTZiMWNlYzlhZjkxNjc5MWI1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2tlAbIRo7UbXsSfux-tg8-sS2zIXlCJEVy_YlrIiad8">
> 
> Closing this because it looks solved, but feel free to reopen if you're not seeing it.

I must have missed it somehow (several times). 
Thanks you for the fast answer and pointer!

Also, thank you @IcedTea2K for getting the code in here, much appreciated!
