### ISSUE TITLE
Supabase edge function returns nothing with JS library however gets a response with postman bug.

### ISSUE THREAD

**Issue by laurencebedford** [supabase/supabase#21522]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I make a request to my edge function with the javascript client @supabase/supabase-js, I get a status code 200 however the request returns nothing - this is what I see in the network tab:

![image](https://github.com/supabase/supabase/assets/69059597/bae7e5a7-38cb-4968-879d-647ea485e26d)

However when I copy that request via curl and put it exactly into postman I get the expected response from the edge function which confirms its an issue with the supabase-js... 

This is happening in Supabase cloud - after I have deployed the function

## To Reproduce

Invoke an egde function via supabase-js

## Expected behavior

I should get my expected response from this code:

```
return new Response(JSON.stringify({ test: "This is a test response." }), {
  headers: { 'Content-Type': 'application/json' },
  status: 200,
});
```

## System information

- OS: [macOS]
- Browser (if applies) [chrome]
- Version of supabase-js: [2.39.7]
- Version of Node.js: [18.12.1]

## Additional info:
This is happening in Supabase cloud.

After shaping browser from Chrome to Safari and checking the logs in Safari - Safari has given more logs:
![image](https://github.com/supabase/supabase/assets/69059597/d3ff3b79-0a6c-47cb-ad7b-1516629494df)

client.js isn't my script - so im assuming its part of the Supabase library. Ive hovered over it to get the location:
![image](https://github.com/supabase/supabase/assets/69059597/c537718d-1537-4c74-b388-ee963f4d2265)

Here is the JS code calling the function - I have the exact same code calling another edge function of mine which works:
```
async edgeFunctionTest(testData) {
    try {
      const { data, error } = await this.supabase.functions.invoke('edge-test', {
        body: JSON.stringify({ testData }),
      });

      if (error) {
        throw error;
      }

      return data;
    } catch (error) {
      console.error('Error invoking edge function:', error);
      throw error;
    }
  }
```

**Comment by encima** [comment]
Hi @laurencebedford ,

thanks for reporting, can you:
- provide a minimal reproducible example (the edge function AND the JS file calling the function using the Supabase library)
- tell us whether this is happening locally or on Supabase cloud?

thanks!

**Comment by laurencebedford** [comment]
> Hi @laurencebedford ,
> 
> thanks for reporting, can you:
> 
> * provide a minimal reproducible example (the edge function AND the JS file calling the function using the Supabase library)
> * tell us whether this is happening locally or on Supabase cloud?
> 
> thanks!

Hi @encima, I have updated the post with the some screen shots of the logs and the code that invokes the function. I am more than happy to email my code to support - just not post it on a public forum since it is production ready code. The strange thing is the 'not allowed by access-control-allow-origin with a status code of 200 and the options request goes through fine.

**Comment by laurencebedford** [comment]
CLOSING - Turns our after numerous iterations of code I missed out this line when returning a response:
headers: { ...corsHeaders, 'Content-Type': 'application/json' }
 
 - All working smoothly now. Thanks for the help!
