### ISSUE TITLE
Change Theme Color Selection Placement

### ISSUE THREAD

**Issue by JBhrayn** [supabase/supabase#21524]
I would like to suggest a small improvement for enhanced user experience. Currently, the theme color selection is located at the bottom of the pages. It might be better to move it to the top just like the one on the [docs](https://supabase.com/docs) page for easier accessibility.

![image](https://github.com/supabase/supabase/assets/110586557/a4d1fed4-55d1-4993-a81c-0b0dfe7e43c1)

**Comment by fsansalvadore** [comment]
Hey @JBhrayn, thanks for the thoughtful suggestion! But we feel that the navbar is a very precious space and at the moment we would prefer to keep the essential there. Especially considering that users usually only ever use the theme toggle once to set the theme, and then forget about it.

We might eventually consider including a theme toggle in the navbar if we add a User dropdown if someone is logged in, but this needs a bit of design guidance from the team.

Closing this issue for now.
