### ISSUE TITLE
Auth RLS docs inconsistent with `auth.users` schema

### ISSUE THREAD

**Issue by kiptoomm** [supabase/supabase#21545]
# Improve documentation

## Link 

[Using Row Level Security with Supabase Auth.](https://supabase.com/docs/guides/auth/row-level-security)

## Describe the problem

The page mentions that `auth.jwt()`:
> Returns the JWT of the user making the request. Anything that you store in the user's app_metadata column or the user_metadata column will be accessible using this function

... and yet the actual table columns do not feature such-named columns. Instead, I see `raw_app_meta_data` and `raw_user_meta_data` columns on the database for a project that was created a week ago

## Describe the improvement

Rename the columns to match the docs or fix the docs

## Additional context

See the screenshots below of my `auth.users` columns:
![Screen Shot 2024-02-26 at 7 46 57 AM](https://github.com/supabase/supabase/assets/1447912/9939a974-448e-4fe5-91d2-ec9ab4e561a2)
![Screen Shot 2024-02-26 at 7 46 48 AM](https://github.com/supabase/supabase/assets/1447912/1dcf2e3f-ad88-4c86-92da-1a790b0082c4)

**Comment by encima** [comment]
Thanks for opening, this could definitely be more specific!

Feel free to open a PR to fix this also :D

**Comment by J0** [comment]
Hey @kiptoomm , 

Thanks for opening the issue, and nice to see you online. The fields on the JWT are named differently from what's in the DB. We'll add a note in addition to the linked PR to reflect this more clearly.

Let us know if there are any other questsions or concerns

**Comment by encima** [comment]
@kiptoomm It was not, some changes still needed to be made as the fields mentioned in the docs change were not correct. Feel free to open a new PR if you like!
