### ISSUE TITLE
Webhook not firing, Schema net does not exist

### ISSUE THREAD

**Issue by Moha-Mahdhour** [supabase/supabase#21580]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. Yes
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).  Yes

## Describe the bug

the webhooks do not fire, the api is up and I tested if it's not working but that's not the case. It shows me Schema net does not exist

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Don't know if there is a way to make sure that it doesn't exist

## Expected behavior

Should call the webhook and proceed from there

## System information

- OS: MacOS

**Comment by encima** [comment]
Thanks for opening, have you installed the `pg_net` extension? and does the `net` schema exist?

**Comment by Moha-Mahdhour** [comment]
Yes I did. I even enabled it and re-enabled it and still gives the same error

**Comment by encima** [comment]
Thanks for confirming, @Moha-Mahdhour. Can you show the full error please? 
You might need to add the schema to your API search path [here](https://supabase.com/dashboard/project/_/settings/api)

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
