### ISSUE TITLE
CORS issue Table Editor

### ISSUE THREAD

**Issue by alejomo** [supabase/supabase#2161]
# Bug report
## Describe the bug

I just created a project, and when click on the Table Editor icon, left bar, I get a CORS issue:

## To Reproduce

1. Create a new project.
2. Click on Table Editor
3. Tables doesn't load

## Screenshots

<img width="1385" alt="Screen Shot 2021-06-30 at 1 46 45 PM" src="https://user-images.githubusercontent.com/9441595/124008105-12eb2480-d9aa-11eb-997f-458cdad887b8.png">

## System information

- OS: macOS
- Browser: Chrome

**Comment by inian** [comment]
Hi the root issue has already been fixed but it takes time to propagate. You can bypass the issue by doing [this](https://github.com/supabase/supabase/issues/2096#issuecomment-869184128) and [this](https://github.com/supabase/supabase/issues/2096#issuecomment-869438174) is what we are doing to avoid it happening in the future
