### ISSUE TITLE
Not able to create user in local supabase 

### ISSUE THREAD

**Issue by jhkumaran** [supabase/supabase#21623]
I created a supabase project and followed the steps to get the supabase project in local. I am able to see the tables I created i my local server. But when I try to sign up a user in my app or try to create a user from dashboard, am getting an error saying 'Failed to create user: An error has occurred: Failed to fetch'
<img width="1279" alt="SupabaseError" src="https://github.com/supabase/cli/assets/79454083/9dfdd026-2361-4c0a-aa68-84f0d95b59fd">

**Comment by isotopeee** [comment]
I also experienced this issue. @chadfaurie Workaround saved me!

**Comment by encima** [comment]
This has now been fixed in the latest release of the CLI/Docker images. Please comment here if versions at v1.148.6 and above cause the same issues.

If you are not running v1.148.6, please update and test before commenting.

**Comment by samrose** [comment]
confirmed updating to `1.153.3` fixes this problem with no other action needed.

**Comment by Capsicum42** [comment]
I run supabase on an ubuntu24.04 (fresh installed, nothing else installed) and I have the above issue. I can not create an user.

The supabase-studio container is "unhealthy".

I cloned the latest version of the git-repro.

<img width="825" alt="image" src="https://github.com/user-attachments/assets/54922e7e-fe9e-4b1b-b548-6e940434658e">

What can I do ?

Regards
Holger

**Comment by anthonycmain** [comment]
I dont know if this issue has resurfaced or not, but I've ran up number local implementations and this error still occurs. 

Even explicitly making the api_url change in the toml file doesnt help.

I'm still getting a 400 error when creating a new user in the studio interface

**Comment by ghislaindemael** [comment]
Got to up this thread as I my projects act weirdly.

In project 1, using user management starter, my function is : 
```begin
  insert into public.users (id, username)
  values (new.id, new.raw_user_meta_data->>'username');
  return new;
end;```

**Comment by colinemondswieprecht** [comment]
Pretty sure you're on the wrong thread, mate. I can't see how this is at all related.
