### ISSUE TITLE
Realtime Postgre CDC Message

### ISSUE THREAD

**Issue by damien-schneider** [supabase/supabase#21660]
# Improve documentation

## Link 

https://supabase.com/docs/guides/realtime/protocol#postgres-cdc-message

## Describe the problem

The object type is not updated,

Here is an example of an object, which doesn't follow at all the old doc, instead of record, it's new, instead of old_record it's old, etc.

It is also missing the typescript type name which could be usefull

```typescript
// Example of payload received
{
    "schema": "modules",
    "table": "todolist",
    "commit_timestamp": "2024-02-29T09:27:40.150Z",
    "eventType": "UPDATE",
    "new": {
        "created_at": "2024-02-29T09:15:08.073574+00:00",
        "deleted_at": null,
        "id": "78b9aada-56f1-48de-9a13-ed2b8f022fae",
        "id_container": null,
        "id_module": "59e4fb0e-e7dc-4209-a0b5-4c1ba9415607",
        "is_done": true,
        "order": null,
        "title": "ca marche de fou",
        "updated_at": "2024-02-29T09:15:08.073574+00:00"
    },
    "old": {
        "id": "78b9aada-56f1-48de-9a13-ed2b8f022fae"
    },
    "errors": null
}
```

**Comment by IcedTea2K** [comment]
Is this the problem with the Postgres CDC message or the doc? Just wanting to know which one should be updated.

**Comment by IcedTea2K** [comment]
Okay, I'll have a go at it :D

**Comment by Hallidayo** [comment]
Hi everyone, A a pull request has been merged that fixes the issue I'm going to close this one now.
