### ISSUE TITLE
View stuck on loading

### ISSUE THREAD

**Issue by PMarco03** [supabase/supabase#21671]
I have a database used to store oils and oils attributes. I'm developing a VUE application to fetch it. 
I created a View with this query:

```
create view
  public.allinfo as
select
  oli.id,
  oli.name,
  oli.latin_name as latin_name,
  oli.description as description,
  nature.name as nature,
  colors.name as color,
  parts.name as part,
  notes.name as note,
  nature.id as nature_id,
  colors.id as color_id,
  parts.id as part_id,
  notes.id as note_id,
  json_agg(distinct diseases.name) filter (
    where
      diseases.name is not null
  ) as diseases,
  json_agg(distinct affinities.name) filter (
    where
      affinities.name is not null
  ) as affinities,
  json_agg(distinct applications.name) filter (
    where
      applications.name is not null
  ) as applications,
  json_agg(distinct actions.name) filter (
    where
      actions.name is not null
  ) as actions,
  json_agg(distinct contraindications.name) filter (
    where
      contraindications.name is not null
  ) as contraindications,
  json_agg(distinct functions.name) filter (
    where
      functions.name is not null
  ) as functions,
  json_agg(distinct flavors.name) filter (
    where
      flavors.name is not null
  ) as flavors,
  json_agg(distinct dosages.name) filter (
    where
      dosages.name is not null
  ) as dosages,
  json_agg(distinct others.name) filter (
    where
      others.name is not null
  ) as others
from
  oli
  left join oli_dosages on oli_dosages.olio_code = oli.id
  left join dosages on oli_dosages.attribute_code = dosages.id
  left join oli_diseases on oli_diseases.olio_code = oli.id
  left join diseases on oli_diseases.attribute_code = diseases.id
  left join oli_affinities on oli_affinities.olio_code = oli.id
  left join affinities on oli_affinities.attribute_code = affinities.id
  left join oli_applications on oli_applications.olio_code = oli.id
  left join applications on oli_applications.attribute_code = applications.id
  left join oli_actions on oli_actions.olio_code = oli.id
  left join actions on oli_actions.attribute_code = actions.id
  left join oli_contraindications on oli_contraindications.olio_code = oli.id
  left join contraindications on oli_contraindications.attribute_code = contraindications.id
  left join oli_functions on oli_functions.olio_code = oli.id
  left join functions on oli_functions.attribute_code = functions.id
  left join oli_flavors on oli_flavors.olio_code = oli.id
  left join flavors on oli_flavors.attribute_code = flavors.id
  left join oli_others on oli_others.olio_code = oli.id
  left join others on oli_others.attribute_code = others.id
  left join notes on oli.note_code = notes.id
  left join colors on oli.color_code = colors.id
  left join nature on oli.nature_code = nature.id
  left join parts on oli.part_code = parts.id
group by
  oli.id,
  nature.id,
  parts.id,
  colors.id,
  notes.id
order by
  oli.id;
```

The view alwais worked without any problems. after some days, it stopped working. i tried from the supabase query editor to execute the query without "create view" and it gets stuck on loading the results but It gets the number of rows and the column names, without displaying any errors. I tryed to fetch each single tables, and i didn't found any problems. 
If i open the console in the inspector tab on supabase while executing that query, i get those errors:

![image](https://github.com/supabase/supabase/assets/36517272/e5916b65-3c60-435f-8bea-6ac313546e3e)

**Comment by encima** [comment]
Hi @PMarco03 

This doesn't seem like a big, this seems like a good chance to do some query optimisation!

How big are the tables? Are you using indexes at all?

Joining across so many tables will notably impact performance, as well as using methods like "json_agg". 

Check out our documentation on these topics:
- https://supabase.com/docs/guides/database/query-optimization
- https://supabase.com/docs/guides/database/extensions/index_advisor
- https://supabase.com/docs/guides/database/debugging-performance

I'll close this as it is not an issue but feel free to comment and maybe we and the community can help you optimise

**Comment by encima** [comment]
The 544 error indicates that the query is timing out which is why you are not getting rows. To debug this, you could create a view with a more simple query and check that responds.
You can also try calling the view in the SQL editor (or using your own database client).

**Comment by PMarco03** [comment]
that is the first thing i tried. it gets stuck even on sql editor of supabase

**Comment by encima** [comment]
That does sound like the query itself is the issue (unless something has changed with the policies you use). If a simpler query works in the editor, then it is best to try and optimise that query.

**Comment by PMarco03** [comment]
i don't know. it stopped working without any intervents. after that supabase lost the autoincrement counter so i had to reset it. i don't know why

**Comment by encima** [comment]
I am afraid I do not know why either, I would suggest that you debug the query and try different variations.

**Comment by PMarco03** [comment]
is there a way to export the DB?

**Comment by encima** [comment]
Sure, you can use the CLI (or standard Postgres tools). See here:
https://supabase.com/docs/reference/cli/supabase-db-dump

**Comment by PMarco03** [comment]
i decided that i won't use view but i will fetch each table. thank you for support!
