### ISSUE TITLE
SASL_SIGNATURE_MISMATCH: The server did not return the correct signature

### ISSUE THREAD

**Issue by noook** [supabase/supabase#21690]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I recently switched from a local postgres database to supabase and using drizzle as the ORM.

This is the drizzle configuration (the app is a discord bot, so long-running)

```ts
import * as schema from '../schema';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from "postgres";

export const sql = postgres({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  max: 1,
})

export const db = drizzle(sql, { schema });
```

On the first request to the database I get the following:

```
app-1  | 33 |   return error
app-1  | 34 | }
app-1  | 35 | 
app-1  | 36 | function generic(code, message) {
app-1  | 37 |   const error = Object.assign(new Error(code + ': ' + message), { code })
app-1  | 38 |   Error.captureStackTrace(error, generic)
app-1  |              ^
app-1  | error: SASL_SIGNATURE_MISMATCH: The server did not return the correct signature
app-1  |  code: "SASL_SIGNATURE_MISMATCH"
app-1  | 
app-1  |       at generic (/usr/src/app/node_modules/postgres/src/errors.js:38:9)
app-1  |       at SASLFinal (/usr/src/app/node_modules/postgres/src/connection.js:721:19)
app-1  |       at /usr/src/app/node_modules/postgres/src/connection.js:14:16
app-1  |       at asyncFunctionResume (native:1:1)
app-1  |       at Authentication (/usr/src/app/node_modules/postgres/src/connection.js:9:1)
app-1  |       at handle (/usr/src/app/node_modules/postgres/src/connection.js:813:5)
app-1  |       at data (/usr/src/app/node_modules/postgres/src/connection.js:553:5)
app-1  |       at addChunk (native:1:1)
app-1  |       at readableAddChunk (native:1:1)
app-1  |       at data (native:1:1)
app-1  | error: script "start" exited with code 1
app-1 exited with code 1
```

However, if use a connection string with the exact same values (env variables joined in the format of the connection string) the connection works.

I'd prefer to use the object notation in the `postgres()` connection options

## To Reproduce

Source code can be found here <https://github.com/noook/discord-mbti>

## Expected behavior

Object notation should behave the same as the connection string

## Screenshots

Database connection on supabase dashboard
<img width="893" alt="image" src="https://github.com/supabase/supabase/assets/19751938/bb29b5fa-55f6-4e8b-8f2c-197ee4ed7a84">

## System information

- OS: Linux (docker)
- Version of supabase-js: not used
- bun 1.0.29

## Additional context

-

**Comment by encima** [comment]
Hi there, if it is working with the connection string but not the individual parameters, then there is likely some issue with the library.
I would recommend using the connection string when that works. 
If you do need to use the parameters, then you may need to add additional options, such as: 
```
ssl: { rejectUnauthorized: false}
```

**Comment by noook** [comment]
This option didn't help in my situation, so I sticked with the connection string.

**Comment by SumitBando** [comment]
Seeing the same issue, randomly, when using postgress.js without Drizzle

**Comment by vicvinc** [comment]
meet the same situation, here is my connection init code:
```ts
    const queryConnection = postgres(process.env.DATABASE_URL!, {
        ssl: { rejectUnauthorized: false },
        prepare: false
    });
```

**Comment by noook** [comment]
Actually, I cannot connect anymore, @encima  I don't know why.
Either with a connection string, with an object, with `ssl: { rejectUnauthorized: false }`, I am just getting 
`SASL_SIGNATURE_MISMATCH` or `SELF_SIGNED_CERT_IN_CHAIN` when using the following configuration (cert is the certificate provided by Supabase on the dashboard)

```ts
const client = postgres(import.meta.env.DATABASE_URL, {
  ssl: {
    rejectUnauthorized: false,
   },
})
// SASL_SIGNATURE_MISMATCH

const client = postgres(import.meta.env.DATABASE_URL, {
  ssl: {
    rejectUnauthorized: false,
    cert,
   },
})
// SASL_SIGNATURE_MISMATCH

const client = postgres(import.meta.env.DATABASE_URL, {
  ssl: { cert },
})
// SELF_SIGNED_CERT_IN_CHAIN
```

**Comment by encima** [comment]
@noook can you lost your project reference here? We can check this but it should be working with the self signed cert. 
Can you confirm the connection string is for your database and not for the connection pooler?

**Comment by binury** [comment]
sorry to necro your closed issue but since it was not really resolved with documentation i hope you wont mind.

for anyone else stumbling here during troubleshooting, I confirmed that this issue is likely caused by a version mismatch between the client's pg version(I tested 14) and the remote (v15 as of now).

I'm not sure why it isn't observed psql (which will warn about the outdated client and _does_ confirm TLS). So, it does seem to be an issue with either Drizzle or possibly [the database driver](https://github.com/porsager/postgres). You can, as @encima suggested, disable SSL as a workaround but in any case, it's ideal to upgrade your client if its outdated. (and resolve the SSL issues as a win-win…)


```sh
# Homebrew upgrade

# brew uninstall postgresql
brew update && brew install postgresql@16
pushd /usr/local/opt/postgresql@16/bin

# If you'd prefer not to modify your $PATH
# for file in *; do ln -s "$(pwd)/$file" /usr/local/bin/; done
popd
psql --version
```

**Comment by encima** [comment]
No need to apologise, this is useful troubleshooting advice! I'll add it to the docs tomorrow

**Comment by binury** [comment]
Ah, I see you are back coincidentally. Well, one last thing then: If you're still having trouble, I'd suggest trying a 'raw' connection with `psql` as a starting point for your troubleshooting rather than poking around in your ORM.

```sh
export DB_URL = 'postgres://postgres.ktmfkkjaiwfuauiwfh:[YOUR-PASSWORD]@aws-0-us-west-1.pooler.supabase.com:5432/postgres'
psql $DB_URL
```

GL

**Comment by noook** [comment]
Spent an hour debugging it, here is the result of my investigation

@encima Here is my project reference id: `wiowhiztwaqjqzlfqqsh`

I changed password a few times because when debugging I reached the pooler logs page and noticed logs such as: `ClientHandler: Exchange error: "Wrong password" when method :auth_query` immediately followed by `ClientHandler: socket closed with reason {:shutdown, :exchange_error}`
I guess the error that I see in the terminal is only the last one, when the real error was maybe a password issue.

I changed it multiple time and made sure it was correctly set (console.log in node app) to see how it was read from the .env file.

I tried a few ones, and finally made it by using a password with no special character. -> Might this be the issue ?

>  Can you confirm the connection string is for your database and not for the connection pooler?
I'm not sure I can tell the difference between the two. I'm using the connection string that I found under Project Settings > Database > Connection string.

It looks like this: `postgres://postgres.wiowhiztwaqjqzlfqqsh:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:5432/postgres`

The dashboard looks like this: 
<img width="1255" alt="image" src="https://github.com/supabase/supabase/assets/19751938/a2bae12d-7858-44a5-a79e-032dd35bf970">

Trying @binury connection with `psql`, it works correctly.

**Comment by binury** [comment]
check if `psql --version` is >=15

**Comment by binury** [comment]
check if `psql --version is >= 15`

also, since you are getting password issues, try:
```ts
export const sql = postgres({
  ⋮
  user: encodeURIComponent(process.env.DB_USER),
  password: encodeURIComponent(process.env.DB_PASSWORD),
  ⋮
})

```
(this is a Drizzle issue I have noticed. _Maybe_ you've run into it too if supabase happened to generate a password that has URI breaking characters which must be encoded.)

**Comment by noook** [comment]
When I ran the code (snippets in the original message of the issue) I adapted the situation in order to not use drizzle and not make it a factor in the equation. The issue might simply be in the connection string passed to the postgres client.

**Comment by encima** [comment]
OK, to summarise this:
1. When using postgres tools and libraries, ensure they are the same (or higher) than the version of your target database
2. When using special characters, be sure to [encode them](https://supabase.com/docs/guides/database/postgres/roles#special-symbols-in-passwords)

**Comment by vicvinc** [comment]
thank you all !!!
sounds stupid! I corrected this by removing the brackets in the database link URL for [password].🤦🤦🤦

**Comment by martinacostadev** [comment]
I had the same issue because my password start with $. After change my password, works fine with this setup:

```
// .env.local
NEXT_PUBLIC_SUPABASE_URL=postgres://postgres.jkjkkjkjkjk:PASSWORD@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
```

```
// db.ts
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

const connectionString = process.env.NEXT_PUBLIC_SUPABASE_URL!;

export const client = postgres(connectionString, { prepare: false });
export const db = drizzle(client);
```

**Comment by armannaj** [comment]
Confirming this. I had the same issue because my DB password contained $ and & in it. I reset it and it is working fine now.

> I had the same issue because my password start with $. After change my password, works fine with this setup:
> 
> ```
> // .env.local
> NEXT_PUBLIC_SUPABASE_URL=postgres://postgres.jkjkkjkjkjk:PASSWORD@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
> ```
> 
> ```
> // db.ts
> import { drizzle } from "drizzle-orm/postgres-js";
> import postgres from "postgres";
> 
> const connectionString = process.env.NEXT_PUBLIC_SUPABASE_URL!;
> 
> export const client = postgres(connectionString, { prepare: false });
> export const db = drizzle(client);
> ```

**Comment by gruckion** [comment]
> Confirming this. I had the same issue because my DB password contained $ and & in it. I reset it and it is working fine now.
> 
> > I had the same issue because my password start with $. After change my password, works fine with this setup:
> > ```
> > // .env.local
> > NEXT_PUBLIC_SUPABASE_URL=postgres://postgres.jkjkkjkjkjk:PASSWORD@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // db.ts
> > import { drizzle } from "drizzle-orm/postgres-js";
> > import postgres from "postgres";
> > 
> > const connectionString = process.env.NEXT_PUBLIC_SUPABASE_URL!;
> > 
> > export const client = postgres(connectionString, { prepare: false });
> > export const db = drizzle(client);
> > ```

Thank you :)

**Comment by igorBudimirDev** [comment]
One more thing guys, if you have @ symbol or #, watch out, @ symbol is what supabase/postgres uses to differentiate passwords and other info in the url. So in general I'd use only dashes or exclamation marks.

**Comment by ebinion** [comment]
Just wanted to confirm I ran into the same issue. I'd forgotten to replace "[PASSWORD]" in the database connection string.

**Comment by hosstay** [comment]
Also just had this issue. My password had a * and % in it, didn't work even when using encodeUriComponent. Just reset the database password and had Supabase generate the password for me and it's all alphanumeric and works.

**Comment by dikshantrajput** [comment]
Faced the same issue. Solved by using `psql` instead of `postgres` in prefix of connection string

**Comment by encima** [comment]
@dikshantrajput `psql` is the name of the command line program to connect to Postgres. `postgres` in the connection string is the name of the user.

You can copy the connection string directly from the studio under project settings. 

If we can document this further, let us know so we can prevent this pain and save valuable hours! Also, feel free to open a PR!

**Comment by szerintem** [comment]
I had the exact same issue so i did log into the postgres lib at this line:
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/crypto/sasl.js#L154

for me it said "e=Wrong password"
So I changed the db password to a new one manually - did not help
Then I changed the db password to a new one with the build in password generator - worked

**Comment by omesh845** [comment]
> I had the exact same issue so i did log into the postgres lib at this line: https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/crypto/sasl.js#L154
> 
> for me it said "e=Wrong password" So I changed the db password to a new one manually - did not help Then I changed the db password to a new one with the build in password generator - worked

thanks this worked for me too

**Comment by alvesvin** [comment]
Unbelievably it worked for me by wrapping my environment variable in double quotes in my .env!!
I'm using Strapi, there must be something wrong with their environment variable parsing function.

**Comment by Athar-Naveed** [comment]
> thank you all !!! sounds stupid! I corrected this by removing the brackets in the database link URL for [password].🤦🤦🤦

Thank You bro! Feeling dumb at this moment🙃e

**Comment by 9-max-6** [comment]
I has the same issue and these really helped. Gotta love the community

**Comment by Tyler-Hervey** [comment]
went through all of this, even upgraded local psql and after an hour or so something must of changes on the supabase side because I was able to migrate successfully

**Comment by ThomasStock** [comment]
I ran into this problem, and the cause was a small typo in my password while changing the connection string after creating a new supabase project.

So to people reading this: tripple check your password. Also consider if you need to use port 5432 instead of the 6543 that was mentioned in the supabase 'connect' dialog.

off topic: I wish there was an easier way to change region of a project, that does not involve creating a new project and a bunch of hassle.

**Comment by oxcabe** [comment]
> So to people reading this: tripple check your password. Also consider if you need to use port 5432 instead of the 6543 that was mentioned in the supabase 'connect' dialog.

Was struggling with `drizzle-kit pull` giving this error, got it fixed by changing the port from 6543 to 5432.

This should be mentioned in the "Connect to your project" > "ORMs" > "Drizzle" section, as it currently is on the "Prisma" section:

Drizzle section:

<img width="760" alt="Image" src="https://github.com/user-attachments/assets/f471739d-529e-4a98-808a-2cc719e86970" />

---

Prisma section (notice the port change):

<img width="760" alt="Image" src="https://github.com/user-attachments/assets/89c503ce-a441-462a-bf01-aaa229cdb973" />

**Comment by arslandevs** [comment]
> sorry to necro your closed issue but since it was not really resolved with documentation i hope you wont mind.
> 
> for anyone else stumbling here during troubleshooting, I confirmed that this issue is likely caused by a version mismatch between the client's pg version(I tested 14) and the remote (v15 as of now).
> 
> I'm not sure why it isn't observed in psql (which will warn about the outdated client and _does_ confirm TLS) or why so many people seem to be running into this at once. So, it does seem to be an issue with either Drizzle or possibly [the database driver](https://github.com/porsager/postgres). You can, as [@encima](https://github.com/encima) suggested, disable SSL as a workaround but in any case, it's ideal to upgrade your client if its outdated. (and resolve the SSL issues as a win-win…)
> 
> # Homebrew upgrade
> 
> # brew uninstall postgresql
> brew update && brew install postgresql@16
> pushd /usr/local/opt/postgresql@16/bin
> 
> # If you'd prefer not to modify your $PATH
> # for file in *; do ln -s "$(pwd)/$file" /usr/local/bin/; done
> popd
> psql --version

this was the core issue i was facing supabase i has version 14 

and supabase currently have version 15 client.

**Comment by LucasZNK** [comment]
Fixed using single quotes in the password instead of the double ones

DB+PASSWORD='password'

**Comment by LucasZNK** [comment]
In my project we fixed trying using single quotes in the password instead of double ones
SUPABASE_DB_PASSWORD='password'

**Comment by jsanchezba** [comment]
In my case I notice that after putting the password on the .env file a special character is removed from the url string. I had to scape the $ character with \$

**Comment by robbydooo** [comment]
I have just been dealing with this issue. What was strange was I had `Enforce SSL on incoming connections` disabled. Enabling this and then disabling it fixed the issue for me. Very odd!

**Comment by melodyclue** [comment]
I stored the SSL certificate in an environment variable and connected using it via the env config — it worked!

<img width="360" alt="Image" src="https://github.com/user-attachments/assets/5e9dfec9-66df-454d-8cd7-28f2ab91363e" />

**Comment by Srinath10X** [comment]
I don't know about others but just make sure that you shouldn't put your password in '[]' brackets it will also throw the error

**Comment by lmaslovs** [comment]
> I have just been dealing with this issue. What was strange was I had `Enforce SSL on incoming connections` disabled. Enabling this and then disabling it fixed the issue for me. Very odd!

Thank you!

**Comment by lmaslovs** [comment]
> I have just been dealing with this issue. What was strange was I had `Enforce SSL on incoming connections` disabled. Enabling this and then disabling it fixed the issue for me. Very odd!

@robbydooo Thank you!

**Comment by devdutt10** [comment]
Still getting this issue. I'm connecting to Supabase via the pooler from a cloudflare worker. I'm using Drizzle with the postgres.js client. 

Things I've tried:

1. Changing the password and restarting the DB.
2. Making sure the password doesn't contain characters or the square brackets that might break a parser somewhere.
3. Connecting from a local-machine node server (Works!).
4. Connecting from a local-machine CF worker using wrangler dev (Doesn't Work!).
5. Connecting from an actual CF worker (doesn't work).
6. Tried enabling and disabling the Enforce SSL on incoming connections property. When enabled, the error changed to "SERVER_ERROR:  PostgresError: SSL connection is required". But when I disabled it again, it went back to "SERVER_ERROR:  Error: SASL_SIGNATURE_MISMATCH: The server did not return the correct signature". So that didn't work either.

**Comment by jeevanpillay** [comment]
seems like mine was fixed when i generated password through supabase's "generated password" instead of custom password

**Comment by inducingchaos** [comment]
Creating a new password worked for me as well.

**Comment by GodoyMS** [comment]
> seems like mine was fixed when i generated password through supabase's "generated password" instead of custom password

It worked for me too. Thanks buddy

**Comment by btzo** [comment]
Ran into this problem while linking to Retool using the connection string: the connection kept failing until I noticed the Postgres URL from the dashboard contains the placeholder `YOUR-PASSWORD` instead of the real password. 

Based on this experience, I think the connection modal should highlight that the string omits the password (adding a “reveal actual password” toggle would prevent this confusion).

**Comment by molavec** [comment]
> seems like mine was fixed when i generated password through supabase's "generated password" instead of custom password

Damn! Same here, but I needed to change it twice! (Sometimes, unusual characters in the password can cause issues.)

Some context in my situation:

I tried to make a `drizzle-kit push`

In my .env, look at the port difference. I doubt it matters, but after many attempts, I'm skeptical.
```
DATABASE_DIRECT_URL="postgresql://postgres.xijocfpaedqchq:[PASSWORD]@aws-0-us-west-1.pooler.supabase.com:5432/postgres"
DATABASE_URL="postgresql://postgres.xijocfpaedqchq:[PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
```

And I using SSL, so append ssl required params in the DATABASE_URL

```typescript
import 'dotenv/config';
import { defineConfig } from 'drizzle-kit';
import * as fs from 'fs'

const caString = fs.readFileSync('./.supabase/certificates/prod-ca-2021.crt').toString()
// URL encode the certificate
const caStringEncoded = encodeURIComponent(caString)

// Construct the database URL with SSL parameters
const dbUrl = new URL(process.env.DATABASE_DIRECT_URL as string)
dbUrl.searchParams.append('sslmode', 'require')
dbUrl.searchParams.append('sslrootcert', caStringEncoded)
// dbUrl.searchParams.append('sslrootcert', './.supabase/certificates/prod-ca-2021.crt')

// console.log('process.env.DATABASE_DIRECT_URL:', process.env.DATABASE_DIRECT_URL);
// console.log('Database URL:', dbUrl.toString());


export default defineConfig({
  out: './drizzle',
  schema: './server/database/schema.ts',
  dialect: 'postgresql',
  dbCredentials: {
    url: dbUrl.toString()!,
  },
  verbose: true,
  // strict: true,
});
```

**Comment by iliyas-kiwimesh** [comment]
> > So to people reading this: tripple check your password. Also consider if you need to use port 5432 instead of the 6543 that was mentioned in the supabase 'connect' dialog.
> 
> Was struggling with `drizzle-kit pull` giving this error, got it fixed by changing the port from 6543 to 5432.
> 
> This should be mentioned in the "Connect to your project" > "ORMs" > "Drizzle" section, as it currently is on the "Prisma" section:
> 
> Drizzle section:
> 
> <img alt="Image" width="760" src="https://private-user-images.githubusercontent.com/25517190/406095381-f471739d-529e-4a98-808a-2cc719e86970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAwNTg3MjYsIm5iZiI6MTc1MDA1ODQyNiwicGF0aCI6Ii8yNTUxNzE5MC80MDYwOTUzODEtZjQ3MTczOWQtNTI5ZS00YTk4LTgwOGEtMmNjNzE5ZTg2OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE2VDA3MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMzBjMjM4MjcwMWE2ZGY4ZGQzMTQ0YTE5YWU4OTNlYTc0Y2Y4ZGU4ZGVhMjhlMGNmMmIzNDUxMDNjMjRiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z3p_eGiA_bhOmbSa63PQdZQpv1ATh5NpSyh6DARal6k">
> Prisma section (notice the port change):
> 
> <img alt="Image" width="760" src="https://private-user-images.githubusercontent.com/25517190/406094724-89c503ce-a441-462a-bf01-aaa229cdb973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAwNTg3MjYsIm5iZiI6MTc1MDA1ODQyNiwicGF0aCI6Ii8yNTUxNzE5MC80MDYwOTQ3MjQtODljNTAzY2UtYTQ0MS00NjJhLWJmMDEtYWFhMjI5Y2RiOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE2VDA3MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZjQzMWQ1ODQwZDcxNmRjYjZkYzNhYTkxYWQ5YjUyYzgyM2MyYzk4MGIwMGE5NjEwNmMwOTIzOGY1NmM4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E2D3A3avX84RPvTWqNico7RFOzL-gIYoY0b8Gz0gTIM">

This helped me. Thank you.

**Comment by BearToCode** [comment]
I got this error after resetting the db password. Tried multiple things but still not working remotely using Github Actions. However, **the following day the problem fixed itself**.

**Comment by GalacticaUA** [comment]
I was stuck with this Supabase PostgreSQL thing, but I figured it out thanks to this post, and now I want to help others. This is for total newbies, so don't judge me too much. 

**I used a Supabase account (or any other hosting service that you are using).**

- Go to Settings > Database > SSL Configuration in Supabase.

Find Reject non-SSL connections and switch it OFF. "This makes connecting easier while you’re figuring stuff out."

- In Settings > Database > SSL Configuration, download the .crt file.

**In "Connect", copy the Connection String. It looks like:** (Transaction pooler)
postgres://postgres.ktmfkkjaiwfuauiwfh:YOUR-PASSWORD@aws-0-us-west-1.pooler.supabase.com:5432/postgres

- Swap YOUR-PASSWORD with your actual Supabase password.

**And don't be surprised that I don't have any brackets _[YOUR-PASSWORD]_ (it turns out they aren't needed there)**

--------------------------------------------------------------------------------------------------------------------------------------------------

**Backend code**

Create a folder like **backend** and open it in VSCode.

I used Node.js, so I used this command to start a project:

- npm init -y

- npm install dotenv postgres

--------------------------------------------------------------------------------------------------------------------------------------------------

**Create a .env file in backend foldier**

DATABASE_URL=postgres://postgres.ktmfkkjaiwfuauiwfh:YOUR-PASSWORD@aws-0-us-west-1.pooler.supabase.com:5432/postgres
DB_CA_CERT=-----BEGIN CERTIFICATE-----\nYOUR_CERTIFICATE_CONTENT\n-----END CERTIFICATE-----

--------------------------------------------------------------------------------------------------------------------------------------------------

**Make a file called database.js and add this code:**

import dotenv from 'dotenv';
import postgres from 'postgres';

dotenv.config();

const sql = postgres(process.env.DATABASE_URL, {
  prepare: false,
  ssl: {
    rejectUnauthorized: true,
    ca: process.env.DB_CA_CERT,
  }
});

// Test if it works
(async () => {
  try {
    const res = await sql`SELECT NOW()`;
    console.log('Connected to the database at:', res[0].now);
  } catch (err) {
    console.error('Database connection failed:', err);
  }
})();

**_To test it out - run this in your terminal_**

- node database.js

**Comment by beesou777** [comment]
i fixed it by just turning off the Enforce SSL on incoming connections 

<img width="1259" height="408" alt="Image" src="https://github.com/user-attachments/assets/efe6e922-8284-4326-8e41-c7beff67996a" />

**Comment by GalacticaUA** [comment]
> i fixed it by just turning off the Enforce SSL on incoming connections
> 
> <img alt="Image" width="1259" height="408" src="https://private-user-images.githubusercontent.com/103716649/475988029-efe6e922-8284-4326-8e41-c7beff67996a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ2NTE5MDksIm5iZiI6MTc1NDY1MTYwOSwicGF0aCI6Ii8xMDM3MTY2NDkvNDc1OTg4MDI5LWVmZTZlOTIyLTgyODQtNDMyNi04ZTQxLWM3YmVmZjY3OTk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwOFQxMTEzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI3MWE0ZGI2YzliZTdiODUxMzgyOGFkODczMjA1MWY2MTEwMDgwZmU5ZTMwZmM1ZGQ0MGFiZmYyMmY5ZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pdg3XjbP-LicQ2HJe5xTQCzomveRl_R00KQb0VH9db0">

Yes, your method works as well, but it’s insecure and only suitable for quick testing. I was working on a big project and decided not to leave this thing unresolved in the end.

**Comment by amanv-heycoach** [comment]
> Spent an hour debugging it, here is the result of my investigation
> 
> [@encima](https://github.com/encima) Here is my project reference id: `wiowhiztwaqjqzlfqqsh`
> 
> I changed password a few times because when debugging I reached the pooler logs page and noticed logs such as: `ClientHandler: Exchange error: "Wrong password" when method :auth_query` immediately followed by `ClientHandler: socket closed with reason {:shutdown, :exchange_error}` I guess the error that I see in the terminal is only the last one, when the real error was maybe a password issue.
> 
> I changed it multiple time and made sure it was correctly set (console.log in node app) to see how it was read from the .env file.
> 
> I tried a few ones, and finally made it by using a password with no special character. -> Might this be the issue ?
> 
> > Can you confirm the connection string is for your database and not for the connection pooler?
> > I'm not sure I can tell the difference between the two. I'm using the connection string that I found under Project Settings > Database > Connection string.
> 
> It looks like this: `postgres://postgres.wiowhiztwaqjqzlfqqsh:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:5432/postgres`
> 
> The dashboard looks like this: <img alt="image" width="1255" src="https://private-user-images.githubusercontent.com/19751938/311521639-a2bae12d-7858-44a5-a79e-032dd35bf970.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc2MjgwMzIsIm5iZiI6MTc1NzYyNzczMiwicGF0aCI6Ii8xOTc1MTkzOC8zMTE1MjE2MzktYTJiYWUxMmQtNzg1OC00NGE1LWE3OWUtMDMyZGQzNWJmOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTExVDIxNTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZTlhMmUwODRiYzQ1MTE2NGQzNmY3MzM0NTM2NDcwOTdlNGU4OGMwMzk5ZjRjYzhhYzcxNTBmNWIzOTcyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bmgB0azrF6NFxd5dHh6GRaG10vHardLfFQkPX8XMALk">
> 
> Trying [@binury](https://github.com/binury) connection with `psql`, it works correctly.

Authentication Issue Resolution
I encountered a persistent authentication problem that was resolved by simplifying my database password. I had initially used a password with special characters (like test@123#), but the issue was completely resolved after switching to a plain text password without special characters. Thanks a Lot.

**Comment by CeamKrier** [comment]
> seems like mine was fixed when i generated password through supabase's "generated password" instead of custom password

this worked for me as well
