### ISSUE TITLE
Storage Upload Error: 413 Maximum size exceeded

### ISSUE THREAD

**Issue by rameez-s** [supabase/supabase#21704]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On trying to upload an image file to storage (20MB), I get a 413 Maximum size exceeded Error.

## To Reproduce

First I used this:
```
const { data, error } = await supabase
                .storage
                .from("parking_images")
                .upload(imagePath, formData.get("image"));
```
 in my next js api route handler to upload an image file received from client. Then I found [this Doc](https://supabase.com/docs/guides/storage/uploads/resumable-uploads) mentioning that for files over 6MB use resumable uploads.

Tried that too, only for it to fail at about 20% with the same error:
```
const image = await formData.get("image").arrayBuffer();
            const imageType = formData.get("image").type.split("/")[1];
            console.log("SIZE: ", formData.get("image").size);
            imagePath = `${parking_id}.${imageType}`
            const fileUploaded = await uploadFile(session, imagePath, image)


const tus = require('tus-js-client')
async function uploadFile(session: any, fileName: string, file: any) {
    const fileBuffer = Buffer.from(file)
    return new Promise((resolve, reject) => {
        var upload = new tus.Upload(fileBuffer, {
            endpoint: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/upload/resumable`,
            retryDelays: [0, 3000, 5000, 10000, 20000],
            headers: {
                authorization: `Bearer ${session.access_token}`,
                'x-upsert': 'true', // optionally set upsert to true to overwrite existing files
            },
            uploadDataDuringCreation: true,
            removeFingerprintOnSuccess: true, // Important if you want to allow re-uploading the same file https://github.com/tus/tus-js-client/blob/main/docs/api.md#removefingerprintonsuccess
            metadata: {
                bucketName: 'parking_images',
                objectName: fileName,
                cacheControl: 3600,
            },
            chunkSize: 6 * 1024 * 1024, // NOTE: it must be set to 6MB (for now) do not change it
            onError: function (error: any) {
                console.log('Failed because: ' + error)
                reject(error)
            },
            onProgress: function (bytesUploaded: number, bytesTotal: number) {
                var percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2)
                console.log(bytesUploaded, bytesTotal, percentage + '%')
            },
            onSuccess: function () {
                console.log('Download %s from %s', upload.file.name, upload.url)
                resolve(true)
            },
        })


        // Check if there are any previous uploads to continue.
        return upload.findPreviousUploads().then(function (previousUploads: any) {
            // Found previous uploads so we select the first one.
            if (previousUploads.length) {
                upload.resumeFromPreviousUpload(previousUploads[0])
            }

            // Start the upload
            upload.start()
        })
    })
}

```

I have also confirmed from Supabase Storage Settings that my upload limit is 50MB.

## Expected behavior

My image file to get uploaded and receive an upload object to get a signed_url

## System information

- OS: Windows WSL2
- Browser : Chrome
- Version of supabase-js: 2.39.3

**Comment by encima** [comment]
Hi @rameez-s ,

Thanks for reporting. To confirm, is this a hosted Supabase project? Is it updated to the latest version?

**Comment by rameez-s** [comment]
Yes and yes

**Comment by encima** [comment]
OK, cool. In the Dashboard are you able to upload the file?

**Comment by Chojecki** [comment]
Any update on this? Experience the same issue

**Comment by Chojecki** [comment]
Ok it was my bad. @rameez-s maybe you have the same issue like me.

So every bucket has own config with file limit default to 4MB. I had to increase this limit for my needs.

![Screenshot 2024-03-20 at 08 57 35](https://github.com/supabase/supabase/assets/20075941/de6e2742-32fc-45af-9046-14b3b54495c7)

**Comment by rameez-s** [comment]
Yes same! Thanks for updating the thread.

**Comment by plgingras88** [comment]
Crossed the same confusion, the doc should be clearer, thanks !
