### ISSUE TITLE
UI bug on supabase studio

### ISSUE THREAD

**Issue by SlavenDj** [supabase/supabase#21755]
I tried to create a view using AI on SQL editor inside supabase studio. When I tried to run the prompt, this error appears. I don't know the meaning of the error, but I think notification component should be limited to a maximum height of around 300 pixels and the dismiss button should be at the top corner. 

![image](https://github.com/supabase/supabase/assets/53652906/9e644afc-59b3-4195-985a-d5ced3b20ef7)

**Comment by saltcod** [comment]
Really strange @SlavenDj  — is it happening repeatedly? Are you able to run any queries there from the Assistant?

**Comment by Ritik008** [comment]
I've fixed this issue. Please review my pull request https://github.com/supabase/supabase/pull/21817 for details.

@SlavenDj , could you please take a look and provide your feedback? Thank you!

**Comment by Ritik008** [comment]
Toast is being opened twice upon clicking the button. I don't know the exact reason why this is happening.

**Comment by SlavenDj** [comment]
> Really strange @SlavenDj — is it happening repeatedly? Are you able to run any queries there from the Assistant?

No, i can run other queries from Assistant. I can not reproduce the error for so reason.

**Comment by saltcod** [comment]
Going to mark this as closed – please reopen if you're able to reproduce!
