### ISSUE TITLE
Example: use Supabase in a Webflow project

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#218]
# Build an example

## Is your feature request related to a problem? Please describe.

New example use-case

## Describe the solution you'd like

We've had a few people ask if they can use Supabase directly in their Webflow project. We don't know for sure, but we suspect you can if you're on Webflow's paid plan (so that you can add custom code). 

You can already use supabase on a static HTML page by importing it like this:

```html
<script src="https://unpkg.com/@supabase/supabase-js/umd/supabase.js"></script>

<script>
  // Initialize
  const supabaseUrl = 'https://chat-room.supabase.co'
  const supabaseKey = 'public-anon-key'
  const supabase = Supabase.createClient(supabaseUrl, supabaseKey)

  // Get public rooms and their messages
  supabase
    .from('rooms')
    .select(`
      name,
      messages ( text )
    `)
    .eq('public', true)
    .then(response => {
      // Do something with the response
    })
</script>
```

## Additional context

- This may not be possible, so even if it's not we'd love to know
- If it is possible, what other cool things could we do with Webflow + Supabase?

**Comment by mding5692** [comment]
@kiwicopple I can take a look into this if its ok, I'm currently using paid version of webflow and can sketch up a guide on it

**Comment by kiwicopple** [comment]
I'd love that @mding5692 - I tried briefly and couldn't figure out webflow. Hopefully any of these bundles will work:

- https://unpkg.com/@supabase/supabase-js
- jspm: https://jspm.dev/@supabase/supabase-js
- skypack: https://www.skypack.dev/view/@supabase/supabase-js

**Comment by awalias** [comment]
![image](https://user-images.githubusercontent.com/458736/101717818-fc977d00-3ada-11eb-8163-38e0d313ea96.png)

noticed this which means you can't preview scripted JS in the editor, and also that embeds aren't available on webflow free which is annoying,

but I think you'd already be paying for webflow if you were trying to do something serious with it - i.e. adding dynamic content, or user auth

**Comment by mding5692** [comment]
> ![image](https://user-images.githubusercontent.com/458736/101717818-fc977d00-3ada-11eb-8163-38e0d313ea96.png)
> 
> noticed this which means you can't preview scripted JS in the editor, and also that embeds aren't available on webflow free which is annoying,
> 
> but I think you'd already be paying for webflow if you were trying to do something serious with it - i.e. adding dynamic content, or user auth

Yep I have paid plan of webflow, am trying it out with the embed

They have some links on it which I'm referencing that can be also re-used for Supabase: 
https://university.webflow.com/lesson/custom-code-in-the-head-and-body-tags
https://university.webflow.com/lesson/custom-code-embed
https://forum.webflow.com/t/embed-simple-javascript-code/77975

**Comment by awalias** [comment]
pretty exciting if we can pull it off @mding5692 :D

**Comment by mding5692** [comment]
Another thing to do that can be done is to create a Webflow Supabase Integration so it appears on like a Webflow app marketplace, it will still need adding custom code, etc. like this: https://university.webflow.com/integrations/shopify but offers another place to put tutorials on how to add

See:
https://university.webflow.com/integrations
https://university.webflow.com/integrations-submission

**Comment by entbit** [comment]
Kinda off-topic but I've created an [example](https://codepen.io/entbit/pen/XWjjjbJ) on CodePen. Since it works there, it should work anywhere, as long as you can target your page's elements.

Didn't know if it's worth to open a new 'example' issue. Thoughts?

**Comment by awalias** [comment]
woowwww this is very cool @entbit !

will this run within the webflow environment? it should, right?

**Comment by awalias** [comment]
for this comment:

```
/*
Supabase Database structure
	id: int4, primary key, created with the table
	name: varchar, required
	message: text, required
	rate: int4, required
	created: date, required, default value now()
*/
```

maybe consider also adding the table name (supaviews)

**Comment by entbit** [comment]
> woowwww this is very cool @entbit !
> 
> will this run within the webflow environment? it should, right?

Haha thanks @awalias! Theoretically, it should work, as webflow has the 'embed' widget which allows you to paste in custom code. Sadly I don't have a paid subscription, so I can't try it out.

**Comment by supercreative-ben** [comment]
I have just chatted with Ant and he shared with me the following script which works on Webflow (I tried it with my pro account):

` <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js"></script>
<script>
let supabaseClient = null

$( document ).ready(async () => {
  const { createClient } = supabase
  supabaseClient = createClient(
    'supabaseurl', 
    'anonkey'
  )
  
  await fetchDataTable()
});

const fetchDataTable = async () => {
    const { data, error } = await supabaseClient
    .from('countries')
    .select('*')
    
   console.log(error)
   console.log(data)
}
</script> `

Just replace the supabaseurl and anon key with your own!
This is awesome :)

**Comment by AbinKumarPanda** [comment]
can you share a cloneable link of webfow with this embed.

**Comment by awalias** [comment]
spring cleaning: closing as stale, feel free to reopen as needed
