### ISSUE TITLE
No recovery email sent after sign up a second time after provider login

### ISSUE THREAD

**Issue by alexy-tractr** [supabase/supabase#21818]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I sign up a user using google provider and then try to sign up using the same email, I don't send recovery email as mentionned by Supabase CTO in https://github.com/supabase/auth/issues/1517 :

> a user who has forgotten that they have an account and is expecting a confirmation email, will receive an account recovery email - note: the developer can edit the template in supabase dashboard

I juste get in supabase auth logs :

{"auth_event":{"action":"user_repeated_signup","actor_id":"9977c7ec-af5a-41f9-a9da-0476e00eb5d9","actor_name":"X X","actor_username":"X@mail.net","actor_via_sso":false,"log_type":"user","traits":{"provider":"email"}},"component":"api","duration":5295026,"level":"info","method":"POST","msg":"request completed","path":"/signup","referer":"https://app.X.com/","remote_addr":"69.70.182.222","status":200,"time":"2024-03-05T20:25:22Z","timestamp":"2024-03-05T20:25:22Z"}

## To Reproduce

1. Login with Google
2. Sign up with same email
3. Don't receive recovery email

## Expected behavior

I would like to receive the recovery email or any other way to handle this behavior by sending email to user to recover email or giving information on how to generate a password (in this case user have to ask for forgotten password)

## System information

- OS: mac OS

Supabase Cloud (No self-hosted)

**Comment by ikbalarslann** [comment]
i can take this one

**Comment by kangmingtay** [comment]
@alexy-tractr 

> When I sign up a user using google provider and then try to sign up using the same email, I don't send recovery email as mentionned by Supabase CTO 

This doesn't seem possible. If you sign up a user through google and then use the same email to sign up again, you should be seeing a "User is already registered" error.

If you want to allow the user to add a password to their account, you can call the [updateUser](https://supabase.com/docs/reference/javascript/auth-updateuser) method.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
