### ISSUE TITLE
Sveltekit guide still uses the old packages

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#21851]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit

## Describe the problem

This guide is great, but it is using the old version of the auth helper package. It should use the new ``@supabase/ssr`` package instead.

## Describe the improvement

Edit the guide to make it compatible with the new package.

## Additional context

This issue has been reported on the Discord by olegpolin.

**Comment by charislam** [comment]
Closed as fixed
