### ISSUE TITLE
Not able to connect to supabase DB using connection string

### ISSUE THREAD

**Issue by dev1pavlo** [supabase/supabase#21850]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I try to connect to supabase db from Node.js. I use an ORM - TypeORM.
When I use `url` to connect - I get an error:  Unable to connect to the database. Error: getaddrinfo EAI_AGAIN
But when I use absolutely same values but splitted to parts, like `host`, `port`, `username`, `password`, `database` - everything is working!

## To Reproduce
Not working:
```js
const typeOrmModuleOptions: PostgresConnectionOptions = {
    type: 'postgres',
    url: 'postgres://postgres.abc:xyz@aws-0-us-west-1.pooler.supabase.com:5432/postgres'
}
```

Working:
```js
const typeOrmModuleOptions: PostgresConnectionOptions = {
    type: 'postgres',
    host: 'aws-0-us-west-1.pooler.supabase.com',
    port: 5432,
    username: 'postgres.abc',
    password: 'xyz',
    database: 'postgres'
}
```

## Expected behavior

Should be able to connect with connection string as well

## Screenshots

![image](https://github.com/supabase/supabase/assets/139326611/5f56ad22-944d-4a9c-91d0-6d88e9c4259f)

## System information

- OS: Ubuntu 20.04
- Version of supabase-js: 1.148.6
- Version of Node.js: 18

**Comment by GaryAustin1** [comment]
Does your password contain special characters that need to be URL encoded?

**Comment by dev1pavlo** [comment]
> Does your password contain special characters that need to be URL encoded?

Yes, there are symbols '@' and '#' in my password

**Comment by dev1pavlo** [comment]
I think I found a solution, thanks @GaryAustin1 
probably the connection string was not parsed correctly because of '@' in my password

I'm closing this

**Comment by GaryAustin1** [comment]
So you need to encode them to use them in a url string.
https://www.freecodecamp.org/news/url-encoded-characters-reference/
