### ISSUE TITLE
[DOCS] SITE_URL link is broken

### ISSUE THREAD

**Issue by hawkcookie** [supabase/supabase#21897]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-signup

and more...

## Describe the problem

the link (https://supabase.com/docs/reference/auth/config#site_url) set to SITE_URL is broken and redirects to 404.

## Describe the improvement

SITE_URL redirects to a correct page or remove the link set to SITE_URL

**Comment by encima** [comment]
Thanks for reporting, I missed your opened PR and fixed the links in the API and SDK specs as well. Feel free to update your PR to update those files and I will close mine.
