### ISSUE TITLE
  const { data, error } = await supabase.auth.getUser(); returning AuthApiError: invalid claim: missing sub claim

### ISSUE THREAD

**Issue by devDoubleH** [supabase/supabase#21921]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I am getting { user: null } even after authentication but the user is recorded in the supabase dashboard
AuthApiError: invalid claim: missing sub claim
    at handleError (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:93:9)
    at async _request (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/lib/fetch.js:73:18)
    at async eval (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:976:24)
    at async SupabaseAuthClient._useSession (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:886:20)
    at async SupabaseAuthClient._getUser (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:970:20)
    at async eval (webpack-internal:///(rsc)/./node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:958:20) {
  __isAuthError: true,
  status: 401
}
{ user: null }

I have done all the things mentioned [docs](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) . But having this issue.

**Comment by encima** [comment]
Related to #13095 

I know you mention checking the docs but, for troubleshooting, can you confirm:
- You have set the Site URL to your localhost site (with the correct port)
- You have enabled email as a provider under Auth
- You are using the `supabase/ssr` package
Thanks!

I am unable to replicate after running: `npx create-next-app -e with-supabase` and setting up the environment variables.

**Comment by Lekanjoy** [comment]
I am also facing this issue when running the `supabase.auth.getUser()` in my nextjs middleware file. When I run the same code in another component, I get the user object back but not in my middleware file. I am guessing, its an error in my middleware.

```
import { supabase } from "./supabase";
import { NextRequest, NextResponse } from "next/server";

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;
  const isLoginOrSignup =
    pathname.startsWith("/login") || pathname.startsWith("/signup");

  const {
    data: { user }, error
  } = await supabase.auth.getUser()

  console.log({user, error});  

  if (!isLoginOrSignup && !user) {
    return NextResponse.redirect(new URL("/login", req.url));
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/", '/member'],
};

```

**Comment by darshan-sr** [comment]
@Lekanjoy To get auth data in middleware make sure to use createServerClient function from the  latest ssr module


```
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

export async function middleware(request: NextRequest) {

const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value,
            ...options,
          });
          response.cookies.set({
            name,
            value,
            ...options,
          });
        },
        remove(name: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value: "",
            ...options,
          });
          response.cookies.set({
            name,
            value: "",
            ...options,
          });
        },
      },
    }
  );
  
  const { data: userData } = await supabase.auth.getUser();
  
  }
  
```

**Comment by sp88011** [comment]
I was running into the same issue in local development. When I changed `auth.site_url` from `http://127.0.0.1:3000` to `http://localhost:3000` it works. 

I don't really understand why.

**Comment by Lekanjoy** [comment]
@darshan-sr I followed the docs and using the ssr package, my middleware works fine now. Thank you.

If anyone is using Nextjs for SSR, you should follow the instructions in the docs [ here ](https://supabase.com/docs/guides/auth/server-side/nextjs)and that should work and don't forget to change your email templates - guides [here ](https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr) also.

**Comment by ItaiAxelrad** [comment]
Having the same issue. I set up everything according to the docs. The user is signed in successfully upon first sign up but once they log out they are unable to log back in. The error code is 403: invalid claim: missing sub claim.

**Comment by Lekanjoy** [comment]
@ItaiAxelrad I hope you have updated your email templates also.

**Comment by ItaiAxelrad** [comment]
> @ItaiAxelrad I hope you have updated your email templates also.

Yes, I have updated my email templates per the docs as well.

**Comment by ItaiAxelrad** [comment]
After some more troubleshooting, turns out the issue was with multiple accounts linked to the same email not merging.  Didn't realize this was not done by default like in Firebase and nothing in the docs mentions it.

**Comment by devDoubleH** [comment]
Hey guys I am closing the issue I just done auth but don't know how it is just working  thanks everyone,
