### ISSUE TITLE
Cannot connect to data base after upgrade to IPv6

### ISSUE THREAD

**Issue by ahmedabdelhafez** [supabase/supabase#21927]
Hello dears,

after supabase upgradefrom ipv4 tp v6 i have an application with nextjs , prisma and supabase and i want to pull database
to populate prisma schema and i get this error

![image](https://github.com/supabase/supabase/assets/25756993/2c717070-8744-49a3-b466-09335f360379)

**Comment by GaryAustin1** [comment]
This seems more like you are seeking help than reporting a bug.
You need to show your full connection string (masking instance and password) to see if that is correct.
You may need to reset the password.
You should check at bottom of database settings if your ip has been blocked for bad passwords.
And you should look thru the connection string settings here: https://supabase.com/partners/integrations/prisma

**Comment by encima** [comment]
As @GaryAustin1 has said, this is more of a support issue than an issue with the Supabase codebase. Can you please open a support ticket (either from the dashboard or using supabase.help).

I will close this now but, if the issue does turn out to be a bug, then the resolution will be posted here.
