### ISSUE TITLE
bug: unable to delete queries locally 

### ISSUE THREAD

**Issue by sean-brydon** [supabase/supabase#21928]
# Bug report
- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Created a fresh install of supabase locally - launched into dashboard and was doing some sql - created a few queries in the sql editor and got an error when trying to delete them. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to http://127.0.0.1:54323/project/default/sql/1
2. Click on delete…'
3. See error

Tested on superbase.com and the issue was not present. 

## Expected behavior
Delete happens without any errors

## Screenshots

![CleanShot 2024-03-10 at 18 15 38](https://github.com/supabase/supabase/assets/55134778/cbdfba4a-bbb2-4e76-bf26-8eb40a9f498c)

## System information

- OS: MacOS
- Browser (if applies) Arc
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

If someone can confirm this issue happy to work on this myself.  

If you can't replicate happy to record a birds eat bug.

**Comment by encima** [comment]
This is related to: https://github.com/supabase/supabase/issues/17941 and is something ongoing within the team. I will close this and redirect comments/feedback to there please.

**Comment by Klrfl** [comment]
I still have this bug when developing Supabase locally. The response always returns "Method DELETE not allowed".

```
XHRDELETE
http://localhost:54323/api/projects/default/content?ids=95d148ad-e6d9-46fa-a754-52430ff0a1bf
[HTTP/1.1 405 Method Not Allowed 13ms]
	
data	null
error	Object { message: "Method DELETE Not Allowed" }
```

**Comment by slhmy** [comment]
> This is related to: [#17941](https://github.com/supabase/supabase/issues/17941) and is something ongoing within the team. I will close this and redirect comments/feedback to there please.

@encima 

It's not a wise choice to close this ‘bug’ issue while the linked issue is a 'feature request' with enhancement labels (
Since the source issue is remaining unsolved for about 1 year, I suggest to reopen this issue. 

This is a high piority issue in my point of view, which makes local and self-hosting developent very confusing (I also cannot delete users in Authentication block).

**Comment by encima** [comment]
Noted, thank you for explaining the impact. 

However, queries are not able to be deleted locally because that feature request is not implemented. As such, this remains closed but please do comment on the source issue linked.
