### ISSUE TITLE
Studio - Enums can be created with the name of a data type and cause confusion in table editor etc

### ISSUE THREAD

**Issue by mozeryansky** [supabase/supabase#21938]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I created a custom enum named 'interval'. I had one of the values as '1day' and I noticed when it was being inserted it showed '{'days': 1}' and when I fetched the value it returned '1 day' (with a space). Changing the name resolves the issue.

## To Reproduce

Create an enum named 'interval'

## Proposed Fix

Implement logic in the Studio that prevents the use of Postgres data types in names for enumerated types.

**Comment by encima** [comment]
`interval` is a data type for postgres, see the docs [here](https://supabase.com/docs/guides/database/tables#data-types)

However, this does mean that we should have reserved words in the Studio that prevent you from creating enums with the name of a data type so I will update this issue to reflect that.

**Comment by mozeryansky** [comment]
Thanks, I didn't know there already was a list.

**Comment by Hallidayo** [comment]
I’ll have a look at this one
