### ISSUE TITLE
Password generation uses special characters and can cause issues for users trying to connect

### ISSUE THREAD

**Issue by binury** [supabase/supabase#21933]
After looking over https://github.com/supabase/supabase/issues/21690 I tested every node pg driver I know of:
- postgres-js
- node-postgres
- neon

and _ALL of these_ - every single one has the same issue : any (username or) password which contains disallowed symbols (e.g. `#`) causes an exception to be thrown and none of them have a strategy implemented to accommodate this. (Not to whether say they should or should not)

<img width="707" alt="ss 2024-03-10 at 22 42 21@2x" src="https://github.com/supabase/supabase/assets/1146921/62d3da58-ce37-4401-9473-b2edd25d0095">
<img width="639" alt="ss 2024-03-10 at 22 42 03@2x" src="https://github.com/supabase/supabase/assets/1146921/31528a35-0cb3-472c-b2c0-02905b8ad75e">
<img width="838" alt="ss 2024-03-10 at 22 41 51@2x" src="https://github.com/supabase/supabase/assets/1146921/f458583c-86d3-48fe-bae9-241f3a1acca7">

They are also basically implemented the same way and call URL to parse the parts into credentials and a connection address

https://github.com/porsager/postgres/issues/735

node-postres even has _an entire submodule repository_ for their connection string parser… it can't receive these either.

Notably, these exceptions are not straight-forward and are usually part of deep stack traces about certificate issues and 'authentication failure - wrong password' messages. probably not very encouraging.

SO. Considering that Supabase insists on having the password generator use 10 symbols and has chosen to include these well known unsafe symbols -in particular #-
would it be beneficial for `/dashboard/project/` to be updated to mention the encoding…?

Worst case scenario, I think it is really worth considering whether supabase might exempt the 3 characters and `#` from the pw symbol pool when generating random creds, as to avoid friction. Just an idea…  Small, low-hanging changes with tangible benefits.

Apologies for not being too succinct- bedtime here :)

**Comment by binury** [comment]
Unsafe:
   …
   The characters "<" and ">" are unsafe because they are used as the
   delimiters around URLs in free text; the quote mark (""") is used to
   delimit URLs in some systems.  The character "#" is unsafe and should
   always be encoded because it is used in World Wide Web and in other
   systems to delimit a URL from a fragment/anchor identifier that might
   follow it.  The character "%" is unsafe because it is used for
   encodings of other characters.  Other characters are unsafe because
   gateways and other transport agents are known to sometimes modify
   such characters. These characters are "{", "}", "|", "\", "^", "~",
   "[", "]", and "`".

   All unsafe characters must always be encoded within a URL. For
   example, the character "#" must be encoded within URLs even in
   systems that do not normally deal with fragment or anchor
   identifiers, so that if the URL is copied into another system that
   does use them, it will not be necessary to change the URL encoding.

**Comment by encima** [comment]
The encoding is mentioned in the docs [here](https://supabase.com/docs/guides/database/postgres/roles#special-symbols-in-passwords). You are also welcome to use your own password (or a password generated by your password manager).

I would close this but, as a few people have had issues, let's leave it open to find a resolution. How would you like to see this improved or raising the visibility of the existing documentation?

**Comment by binury** [comment]
I didn't mean for the PR to have a documentation tag— I think the template automatically applied it; sorry.

> use your own password

Well, as of Nov '22, the superuser role is not accessible for hosted sb which would prevent this, does it not? One _can_ -and some users do- generate passwords over and over through the 'studio' UI until they receive one without the disallowed characters so that they don't have to the URL.

I totally get that it's a silly problem- I do; it just seems like there is a very simple/easy change that can mitigate a lot of negative UX regardless of PEBKAC or not. I think would be a smart choice to exclude one[^1] bit of entropy (`#`) from  `possible_password_characters`. If it would help justify it, just add another character (20+1) to the length to compensate.

[^1]: Well, `1n` so… 20

**Comment by encima** [comment]
Not a silly problem at all and it's clear from the number of comments that this is an issue for many others. 

You are able to use your own password when creating a new project though, clicking "generate password" is an option but it is possible to provide your own password without special characters. 

As the documentation suggests, encoding the password does resolve the majority of issues encountered but you might be right that restricting the range of special characters could help a lot here.

**Comment by binury** [comment]
I just checked again and… I might be misremembering only being allowed to reset to pre-generated passwords 😕 (Is this ever the case? Do any non-owner admin roles allow changing it but only regeneration?)

I am able to set the password _and_ the generated ones don't contain any symbols… at all.

![ss 2024-03-12 at 16 39 36](https://github.com/supabase/supabase/assets/1146921/a6378eea-23a7-4654-a3b9-569facc920ab)
