### ISSUE TITLE
Support tool does not permit user creation -- users cannot file ticket with Supabase support

### ISSUE THREAD

**Issue by WilliamAGH** [supabase/supabase#21948]
## Describe the bug

There appears to be a larger issue right now where Supabase **support** systems cannot be accessed.

Creating a support account at supabase.green fails at the requirement to create a new account, including Github SSO user creation (if two factor auth present). One cannot join the Supabase Discord server currently, either.

## To Reproduce

**Supabase.green**: user must confirm their new account by clicking a [verification email hyperlink before proceeding](https://jmp.sh/KL0A9NII). This hyperlink does not properly activate the new account and the interface ignores the pathway used and asks the user to start again. 

_User also repeatedly receives a two-part captcha confirmation at every single page interaction._ 

**Supabase.green via github**: if a Github account is used to sign-in instead, it fails if the user has two factor authentication enabled on their account, not allowing the user to proceed.

**Supabase Discord server**: attempts to join the Discord server by visiting discord.supabase.com result [in this error](https://jmp.sh/sDXC6n9c). 

## System information

- OS: macOS
- Browser: Chrome

**Comment by WilliamAGH** [comment]
This is the [original link](https://supabase.green/dashboard/project/_/branches) that caused us to bump into this problem, linked from this [article](https://supabase.com/docs/guides/platform/branching).

**Comment by GaryAustin1** [comment]
I may be totally out of the loop but what is supabase.green?

The Discord server has had several people join the past few days.

**Comment by WilliamAGH** [comment]
> I may be totally out of the loop but what is supabase.green?
> 
> 
> 
> The Discord server has had several people join the past few days.

Thanks for the reply. So update:

Discord server join outage was short lived (unsure of the cause, but I was able to join a few hours later, but the issue/outage was present for a few hours).

As for supabase.green, upon further investigation, I believe supabase.green might be an internal application they erroneously linked to in a help doc.
