### ISSUE TITLE
Supabase fetch duplicate data from table

### ISSUE THREAD

**Issue by shiyuliu28** [supabase/supabase#21952]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am performing a simple operation to fetch all the data from a table, it is a larger table with 120k rows. Each row is strictly unique with unique uuid. While I did get 120k entries back from the result which is consistent with the size of my table, about 40k of the id occurred more than once. Even though I have double and triple checked that I have no duplicate id in my table. It is not our first time running this function to retrieve data from this table, this issue occurred only yesterday.

## To Reproduce

This is the code i ran with my own table name
```

def fetch_all_data(table_name):
    offset = 0
    limit = 1000  
    all_data = []

    while True:
        response = supabase.table(table_name).select(
            '*').limit(limit).offset(offset).execute()
        data = response.data
        if not data:
            break 
        all_data.extend(data)
        offset += limit

    return all_data
```
## Expected behavior

I expect all 120k unique entries to be returned without any duplicates. Running raw sql query to get the data does not return duplicate results. We were able to work around the issue by defining customized sql function. 

## System information

- OS: macOS Sonoma 14.1
- Version of supabase-js: supabase==2.0.3
- Version of python: 3.11.6

**Comment by encima** [comment]
I cannot duplicate this using the latest Python library. As you are getting the total row count of your table, are you sure the duplicates are not coming from another field (such as `user_id`)?

If you prefer, you can open a support ticket and ask for it to be assigned Chris on the Success team with the following:
- the exact Python code (including table name) 
- a text dump of the 120k rows 
- your `requirements.txt` or `Pipfile.lock`

**Comment by hawkcookie** [comment]
@shiyuliu28 
Isn't it because the order method is missing?

**Comment by pearlli98** [comment]
@shiyuliu28 's coworker here: we do this
```
def fetch_all_data(supabase, table_name):
  offset = 0
  limit = 30000  # Adjust if needed
  all_data = []

  while True:
    response = supabase.table(table_name).select(
        '*').eq('active', True).limit(limit).offset(offset).execute()
    data = response.data
    if not data:
      break  # Exit the loop if no more data is returned
    all_data.extend(data)
    offset += limit

  return all_data
```

where should we add the order method? why is it needed? we didn't run into issue before with the function above
