### ISSUE TITLE
Custom headers does not show up on the API Edge network logs

### ISSUE THREAD

**Issue by vlazdra** [supabase/supabase#21970]
**Describe the bug**

Hi, I'm experiencing a weird situation where adding custom headers doesn't work on the server side.

I can confirm on the client side in Flutter using the Supabase SDK, the headers are provided which is clearly visible in the Network tool in DartDev Tools, but when the API request arrives on the server side, the headers are not present in the request for some reason, as if they were overwritten somehow.

```dart
await Supabase.initialize(
  url: [url],
  anonKey: [key],
  headers: {
    'X-Device-Id': 'alksdklasdjasjkd',
  },
);
```

Also setting it via the setter function doesn't work as well:
```dart
Supabase.instance.client.headers = {
  'X-Device-Id': 'asjoajdiofjeiow',
  'X-User-Id': 'asdaskldkadmas',
};
```

And then when I look at the request headers in the logs on the Supabase end, there's nothing:
```json
"headers": [
{
  "accept": null,
  "cf_cache_status": null,
  "cf_connecting_ip": "111.111.111.111",
  "cf_ipcountry": "NN",
  "cf_ray": "34324323",
  "content_length": "12",
  "content_location": null,
  "content_range": null,
  "content_type": "application/json; charset=utf-8",
  "date": null,
  "host": "lnk",
  "prefer": "resolution=merge-duplicates",
  "range": null,
  "referer": null,
  "sb_gateway_mode": null,
  "sb_gateway_version": null,
  "user_agent": "Dart/3.3 (dart:io)",
  "x_client_info": "supabase-dart/2.0.8",
  "x_forwarded_proto": "https",
  "x_forwarded_user_agent": null,
  "x_kong_proxy_latency": null,
  "x_kong_upstream_latency": null,
  "x_real_ip": "111.111.111.111"
}
```

**To Reproduce**

n/a

**Expected behavior**
The header is present on the server side as well.

**Screenshots**
n/a

**Version (please complete the following information):**
├── supabase_flutter 2.3.4
│   ├── supabase 2.0.8
│   │   ├── functions_client 2.0.0
│   │   ├── gotrue 2.5.1
│   │   ├── postgrest 2.1.1
│   │   ├── realtime_client 2.0.1
│   │   ├── storage_client 2.0.1

**Additional context**
n/a

**Comment by devj3ns** [comment]
I am having the same issue, my custom headers are not showing up in the API Gateway logs.

I noticed that the Supabase flutter SDK sends a `x_client_info` header to the API. In my custom implementation which uses the REST API directly without the flutter SDK, I am trying to send a `x_client_app_version` which does not show up in the log explorer.

**Comment by kevcodez** [comment]
We recommend using the `user_agent` header for this and have just documented it: https://supabase.com/docs/guides/platform/logs#additional-request-metadata
