### ISSUE TITLE
ClerkJS Frontend API Key Name Change

### ISSUE THREAD

**Issue by morganpierson** [supabase/supabase#21980]
# Improve documentation

## Link 
[https://supabase.com/partners/integrations/clerk](url)

## Describe the problem
The ClerkJS integration documentation currently refers to the "Clerk Frontend API Key", which no longer exists

## Describe the improvement
Change the documentation to refer to the Clerk Frontend API Key as the "Clerk Publishable Key" as it is expressed in the ClerkJS documentation

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by encima** [comment]
Thanks for opening @morganpierson! Feel free to open a PR to update this

**Comment by Hallidayo** [comment]
This has been fixed by @fsansalvadore 🔥

**Comment by encima** [comment]
Nice, can you link the PR to this issue please?

**Comment by Hallidayo** [comment]
@encima - It was a change in the supabase backend so no PR to link.
