### ISSUE TITLE
Network Request Failed

### ISSUE THREAD

**Issue by conor-gaughan** [supabase/supabase#2198]
# Bug report

## Describe the bug

When accessing different areas of Supabase, I get a Network Request Failed message and the pages never load. Within the Supabase UI so far I've noticed the Table Editor and the API tab don't work. 

Outside of the UI, when I try to submit data to Supabase by following the Next starter, for example, I get the same Network Request failed error. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
**I have recorded a video of what I am experiencing: https://www.loom.com/share/f7336b6930184db7b802fc9d7c2291ad**

UI
1. Go to "New Project"
2. Fill out information and create project
3. The first page it brings you to is the table editor which will spin and spin never loading
4. Go to the API tab to see "Error connecting to API TypeError: Failed to fetch" error

**Repo: https://github.com/conor-gaughan/next-supabase-test**
**Deployed: https://thirsty-babbage-e066c8.netlify.app/**

Project

1. Whenever you try to submit something to Supabase you get a Network Request Failed error

## Expected behavior

I created a project in Supabase that was working before this. I went back into that project and noticed the same error and the website no longer working giving me "Network Request Failed" when trying to push data to Supabase. 

Table Editor should load once the project is ready to either build one manually or generate what was built with SQL

## Screenshots

I added a video but here are some screenshots:
<img width="571" alt="Screen Shot 2021-07-02 at 2 53 37 PM" src="https://user-images.githubusercontent.com/43390046/124319219-e79e3c00-db47-11eb-8d22-c9df4289f4e2.png">
<img width="1436" alt="Screen Shot 2021-07-02 at 2 45 53 PM" src="https://user-images.githubusercontent.com/43390046/124319221-e836d280-db47-11eb-83e6-364f810516d9.png">
<img width="1429" alt="Screen Shot 2021-07-02 at 2 45 32 PM" src="https://user-images.githubusercontent.com/43390046/124319223-e8cf6900-db47-11eb-9002-e694e99449c2.png">

## System information

- OS: [macOS]
- Browser [chrome] Version 91.0.4472.114 (Official Build) (x86_64)
- Version of supabase-js: [e.g. 6.0.2] - unsure how to see this but console says `2021.04.12.04`
- Version of Node.js: [e.g. 14.15.4]

## Additional context

Thank you for anything you can do to help!

**Comment by inian** [comment]
Lets continue the discussion here @conor-gaughan since that has more context https://github.com/supabase/supabase/issues/2096#issuecomment-872351970
