### ISSUE TITLE
custom header is not showing in auth hook 

### ISSUE THREAD

**Issue by raviranjan-uplabs** [supabase/supabase#21982]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

setting custom header in supabase client this way
 global:{
        headers: { 'organization_id': '1234' },
      },

Try to access same header on auth hook postgres function like below
 RAISE LOG 'test custom_access_token_hook org %', current_setting('request.headers', true)::json->>'organization_id';

Getting this at run time
test custom_access_token_hook org NULL

![Screenshot 2024-03-12 at 9 54 52 PM](https://github.com/supabase/supabase/assets/110083579/8e351a7f-263a-4628-b184-8b2a3e47a547)
![Screenshot 2024-03-12 at 9 52 34 PM](https://github.com/supabase/supabase/assets/110083579/a716176d-8663-427b-b951-9a02c72b4c5b)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Hi, 
Thanks for opening, it is reasonable to expect extraneous headers to be stripped. You can try prefixing with `X-`.

However, using headers here is not the recommended approach and we would suggest that you instead modify the metadata of the JWT using something like [custom claims](https://github.com/supabase-community/supabase-custom-claims).

**Comment by raviranjan-uplabs** [comment]
Hi,

We have use case to create token specific to url for example organization/1234/dashboard then create token only for organization=1234 therefore, i am passing organization id in header and wanted to get in auth hook function.

This can't be active with solution that your are proposing because in your solution, metadata need to set in users table and i can't modify for a request only based on url.

after prefixing x- or X-, still this is not working.

![image](https://github.com/supabase/supabase/assets/110083579/b7ddb20c-17c6-408c-bcc8-69518c1d5ed3)
![image](https://github.com/supabase/supabase/assets/110083579/12937d7b-a9db-431f-9030-196e0c3daa68)

**Comment by hubertoschusch** [comment]
Did you find a workaround for this?
