### ISSUE TITLE
CLI db pull not creating a migration file on first migration

### ISSUE THREAD

**Issue by Cheveniko** [supabase/supabase#21991]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

CLI command: supabase db pull not generating migration file on first migration from remote to local.

I did a fresh install of supabase local environment following every step on the docs: https://supabase.com/docs/guides/cli/local-development and got the following error trying to pull my database from my remote environment.

![Captura de pantalla 2024-03-13 a la(s) 04 13 39](https://github.com/supabase/supabase/assets/88566759/a43accd8-4f45-4e0f-8995-d7baa9276fec)

## To Reproduce

Fresh install of supabase local environment: https://supabase.com/docs/guides/cli/local-development

## Expected behavior

The generation of the migration.sql file on my remote database so I could run it on my local environment to have my tables on local.

## System information

- OS: macOS Sonoma 14.3.1
- Version of supabase CLI: 1.148.6
- Version of Node.js: v20.10.0

**Comment by encima** [comment]
Thanks for opening! Unable to reproduce on macOS with a fresh project and CLI v 1.151 (and the latest: v1.153). Could you:
- Run the command with `--debug` to check the output and see if there is more info?
- Update to the latest CLI release and confirm

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
