### ISSUE TITLE
Edge functions don't explicitly state any limits such as timeouts, max body size, concurrency limits, etc

### ISSUE THREAD

**Issue by ramikalai** [supabase/supabase#22002]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

https://supabase.com/docs/guides/functions

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?
The documentation is missing information on the limits of Supabase edge functions.
I need to know things like max body size, timeouts, etc before committing to using this product.

## Describe the improvement

A clear and concise description of the improvement.

There should be a dedicated page with limits laid out clearly.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by charislam** [comment]
Hello @ramikalai, we have some limitations documented here: https://supabase.com/docs/guides/functions/debugging#limitations

(I realize that's sort of buried, we'll look into moving it.) Does that answer your questions?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
