### ISSUE TITLE
Unable to create users locally

### ISSUE THREAD

**Issue by groksrc** [supabase/supabase#22009]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you start the local development stack with `supabase start` and then navigate to the UI endpoint at http://localhost:54323/project/default/auth/users try to create a user with "Create New User" from the menu. You will see an error in the UI: `Failed to create user: An error has occurred: Load failed`. This used to work as expected. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. From the terminal: `supabase start`
2. From the browser navigate to: http://localhost:54323/project/default/auth/users
3. Click `Add user`
4. Click `Create new user`
5. Fill the User Email and User Password textboxes and leave the Auto Confirm User? option checked.
6. Click `Create user`

## Expected behavior

A user is created. 

## Screenshots
<img width="1506" alt="Screenshot 2024-03-13 at 5 17 33 PM" src="https://github.com/supabase/supabase/assets/9099311/5599eace-ba47-4204-9658-d8248ed8c506">

## System information

- OS: macOS
- Browser: happens in Chrome 122 and Safari 17
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

If I open Chrome Dev Tools I find the following errors after clicking the `Create user` button:
```
_app-5e117e56c49dd8be.js:5 Refused to connect to 'http://127.0.0.1:54321/auth/v1/admin/users' because it violates the following Content Security Policy directive: "default-src 'self'  http://localhost:8000 http://localhost:8000 https://*.supabase.co wss://*.supabase.co https://*.hcaptcha.com https://cdn-global.configcat.com https://*.stripe.com https://*.stripe.network https://www.cloudflare.com https://1.1.1.1 https://*.vercel-insights.com https://api.github.com https://raw.githubusercontent.com". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
_app-5e117e56c49dd8be.js:5 Refused to connect to 'http://127.0.0.1:54321/auth/v1/admin/users' because it violates the document's Content Security Policy.
```

It appears that the CSP directive needs to be updated to include `http://127.0.0.1:54321`. I notice that `http://localhost:8000` is added twice, this may be another symptom of the bug.

Also, here is my local running stack:

```
$ supabase services                                                         


        SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.103           │ 15.1.0.103
    supabase/gotrue        │ v2.143.0             │ v2.143.0
    postgrest/postgrest    │ v11.1.0              │ v11.1.0
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.48.2              │ v0.48.2
    supabase/edge-runtime  │ v1.36.1              │ -
    supabase/studio        │ 20240205-b145c86     │ -
    supabase/postgres-meta │ v0.77.2              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

I suspect this change from Jan 22, 2024 was what broke it: https://github.com/supabase/supabase/commit/677f7aada5a4894d49af414125811300173645b2

**Comment by mendacium-a11y** [comment]
can i try to resolve this issue if it's alright?

**Comment by aleix10kst** [comment]
I'm having the same issue right now. 
I have run `npx supabase stop` followed by `npx supabase start` and it has let me add users. But once I apply a ne migration, it stops working.

**Comment by Hallidayo** [comment]
Hi all - Just checking in here, are you finding this issue is still happening for you?

**Comment by aleix10kst** [comment]
@Hallidayo Hi!
In my case, I found that the error was due to a Postgres error being thrown because I made a typo declaring a column type.

**Comment by alsherif-khalaf** [comment]
Same error

**Comment by Hallidayo** [comment]
Hi @alsherif-khalaf - Do you get any errors in the console or network requests? I tried this today locally and I was not able to get any errors.
