### ISSUE TITLE
After migration to a new project, querying relationships return error: "Could not find foreign keys between these entities. No relationship found between X and Y."

### ISSUE THREAD

**Issue by EdgarBarrantes** [supabase/supabase#2200]
# Bug report

## Describe the bug

Scenario: Using two projects (say: dev and staging). Both hosted by supabase. I'm migrating the schema like the [recomendation](https://supabase.io/docs/guides/database#migrating-between-projects), realtime disabled.

The issue: on dev environment, where I do everything by sql statements or interface I'm able to query relationships defined by foreign key. E.g.:
```typescript
const { data, error } = await supabase
    .from<IYEntity>("X")
    .select(`name, uuid, Y (key, is_valid)`)
    .eq("uuid", id)
    .limit(1);
```
When using the staging project, I get "Could not find foreign keys between these entities. No relationship found between X and Y." while running the same query. I reviewed both DBs and they appear to be identical. I dropped all tables on the staging environment and deleted on procedures. The migration runs, everything appears to be fine, but the query still throws the same error. 

## To Reproduce

1. Define a database with foreign key relationships. E.g.:
![image](https://user-images.githubusercontent.com/11295946/124339937-e9c7c100-db6e-11eb-94fc-7f5d2c0ce938.png)
2. Migrate the DB to a new project.
3. Try a query like the one shown.

## System information
 
- OS: Linux.
- Version of supabase-js: 1.15.1
- Version of Node.js: v15.11.0

## Additional context

The only think I can think is of restarting the postgrest container, I'd love to be able to do that from the supabase interface or any API. Is there such an option?

**Comment by steve-chavez** [comment]
Hey @EdgarBarrantes,

Try running this SQL and retry the postgrest-js request:

```sql
-- manually refresh postgrest foreign key metadata
NOTIFY ddl_command_end;
```

It's likely that when you did the migration, the event trigger that automatically reloaded postgrest metadata was lost. This can be checked with:

```sql
select evtname, evtevent from pg_event_trigger;
-- should show
-- api_restart ddl_command_end
```

If the event trigger is not there, you can create it with:

```sql
CREATE OR REPLACE FUNCTION extensions.notify_api_restart()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NOTIFY ddl_command_end;
END;
$$;
CREATE EVENT TRIGGER api_restart ON ddl_command_end
EXECUTE PROCEDURE extensions.notify_api_restart();
COMMENT ON FUNCTION extensions.notify_api_restart IS 'Sends a notification to the API to restart. If your database schema has changed, this is required so that Supabase can rebuild the relationships.';
```

---

Related to https://github.com/supabase/supabase/issues/1416#issuecomment-833683549

**Comment by EdgarBarrantes** [comment]
Brilliant! Yeah that was it.

Justed the migration again and indeed:
```
ERROR:  permission denied to create event trigger "api_restart"
HINT:  Must be superuser to create an event trigger.
ERROR:  must be owner of event trigger api_restart
```

I'll modify my migration script to run this after the schema is copied. 

Thank you so much!
