### ISSUE TITLE
Server role key does not bypass RLS rules when making raw sql queries

### ISSUE THREAD

**Issue by wliumelb** [supabase/supabase#22018]
```
const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

const query1 = await supabase.from('my_table').select();

const query2 = await supabase.rpc('select * from my_table');
```

if read policy of my_table is set to authenticated only:
query1 returns data as expected;
query2 returns null;

if read policy is removed:
both query1 and query2 return data;

**Comment by encima** [comment]
Your RPC runs without knowledge of the user so the behaviour may not be so clear but is expected.
Since PG15, you can set a view to run as the `invoker` (you calling the view) or the `definer` (you when you made the view), so something like this would be the approach:

```
CREATE VIEW get_my_table AS
SELECT * FROM my_table
WITH (security_invoker=true);
```
