### ISSUE TITLE
hybrid-search example for full_text subquery doesn't order correctly

### ISSUE THREAD

**Issue by anngbaum** [supabase/supabase#22027]
# Improve documentation

The subquery to find fts results indexes in a non-deterministic order...

query in question [here](https://github.com/supabase/supabase/blob/6e8538f95756153176dcf786c3c2387093b50826/apps/docs/content/guides/ai/hybrid-search.mdx#L96C1-L107C35)
```
  select
    id,
    row_number() over() as rank_ix
  from
    documents
  where
    fts @@ websearch_to_tsquery(query_text)
  order by
    -- Note: this is not indexable but will only rank matches of the where clause
    -- which shouldn't be too big
    ts_rank_cd(fts, websearch_to_tsquery(query_text)) desc
  limit least(match_count, 30) * 2
```

## Describe the problem
in my db, I found that the `order by` was not being performed before the row_number was being calculated. moving the `order by` into the `row_number` `over()` clause fixed this problem! see screenshots below.

broken example:
<img width="753" alt="Screenshot 2024-03-14 at 11 59 38 AM" src="https://github.com/supabase/supabase/assets/29735378/aa720800-599e-4d8b-8ed5-b1258fe0c99b">

fixed:
<img width="748" alt="Screenshot 2024-03-14 at 12 00 21 PM" src="https://github.com/supabase/supabase/assets/29735378/b78b77b8-b8bf-40a7-af03-857a64b66cce">

## Describe the improvement
update the documentation to:

```
  select
    id,
    -- Note: this is not indexable but will only rank matches of the where clause
    -- which shouldn't be too big
    row_number() over(order by ts_rank_cd(fts, websearch_to_tsquery(query_text)) desc) as rank_ix
  from
    documents
  where
    fts @@ websearch_to_tsquery(query_text)  
  limit least(match_count, 30) * 2
```

## Additional context

For whatever reason, I didn't have the same problem with the semantic_search! Might be worth correcting that as well just to be safe.

**Comment by ikunal-04** [comment]
hello, can i work upon this?

**Comment by charislam** [comment]
@ikunal-04, of course! feel free to open a pr

**Comment by gregnr** [comment]
This is a great find @anngbaum, thanks for taking the time to dig into it. Agreed - best to update the `row_number()` ordering for semantic search as well. We'll use @ikunal-04's branch/PR to get this merged 👍

**Comment by gregnr** [comment]
#22052 is now merged. Thanks again!
