### ISSUE TITLE
Error during authentication

### ISSUE THREAD

**Issue by noook** [supabase/supabase#22020]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When authenticating, the server responds with 502 `"An invalid response as received from the upstream server"`.

I saw the [linked discussion ](https://github.com/orgs/supabase/discussions/20722) and ran the query (works fine) but I'm confused as of why it happens now when others had the issue around end of january ?

## To Reproduce

I can't really tell, I'm just trying to authenticate

## Expected behavior

Successful authentication

## Logs

Project ID: `wiowhiztwaqjqzlfqqsh`

```json
[
  {
    "message": null,
    "timestamp": null,
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": null,
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "fatal",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "running db migrations: error executing migrations/20221208132122_backfill_email_last_sign_in_at.up.sql, sql: -- previous backfill migration left last_sign_in_at to be null, which broke some projects\n\ndo $$\nbegin\nupdate auth.identities\n  set last_sign_in_at = '2022-11-25'\n  where\n    last_sign_in_at is null and\n    created_at = '2022-11-25' and\n    updated_at = '2022-11-25' and\n    provider = 'email' and\n    id = user_id::text;\nend $$;\n: ERROR: operator does not exist: uuid = text (SQLSTATE 42883)",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-wiowhiztwaqjqzlfqqsh",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": null,
    "component": null,
    "project": null,
    "user_id": null,
    "auth_event": [],
    "args": [],
    "referer": null,
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": null,
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": null
  }
]
```

## System information

- OS: MacOS
- Browser Firefox
- Version of supabase-js: 2.39.7

**Comment by SalmanGits** [comment]
can you give more infromation

**Comment by encima** [comment]
The logs posted are an issue coming from comparing `uuid` type with `text`  but this is from a migration and not from authentication.

Without additional context (and relevant logs), I will close this and reopen if the info is added. Alternatively, you can always open a support ticket
