### ISSUE TITLE
Documentation of errors during auth that are provided to a redirect URL

### ISSUE THREAD

**Issue by tobico** [supabase/supabase#22036]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/concepts/redirect-urls and maybe https://supabase.com/docs/guides/auth/auth-email-templates

## Describe the problem

When authentication fails, the user is redirected to the provided redirect URL with an error code in the URL hash such as `#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`

This error is only in the URL and is not shown to the user, so it will not be clear to a user of the application that any error has occurred. There's nothing in the documentation describing this behavior or providing any example of how this error could be detected and displayed to the user.

## Describe the improvement

I suggest adding documentation describing this behavior, how the URL hash is formatted, and which possible codes can be returned. This should also include a JavaScript code example which demonstrates decoding the value and displaying it to the user in some simple way such as a `window.alert` popup.

**Comment by encima** [comment]
Thanks for opening, please do feel free to open a PR to add these code samples to the `redirect urls` page.

A starting point for anyone that wants to contribute would be:

```
const params = new URLSearchParams(window.location.hash.slice(1));
const errorDescription = hashParams.get('error_description');
```
