### ISSUE TITLE
Stripe Foreign Data Wrapper shows client side exception when running locally

### ISSUE THREAD

**Issue by MeesEgberts** [supabase/supabase#22038]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've created some foreign tables while following the [documentation](https://supabase.com/docs/guides/database/extensions/wrappers/stripe) while running Supabase locally. All goes well until I try to open the table in in Supabase studio. Then I get a full screen error saying: `Application error: a client-side exception has occurred (see the browser console for more information).`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the "SQL editor" in Supabase.
2. Execture the queries
```sql
create extension if not exists wrappers with schema extensions;

create foreign data wrapper stripe_wrapper
  handler stripe_fdw_handler
  validator stripe_fdw_validator;

-- Save your Stripe API key in Vault and retrieve the `key_id`
insert into vault.secrets (name, secret)
values (
  'stripe',
  'YOUR_SECRET'
)
returning key_id;
```
3. Connecting to Stripe:
```sql

create server stripe_server
  foreign data wrapper stripe_wrapper
  options (
    api_key_id '<key_ID>', -- The Key ID from above, required.
    api_url 'https://api.stripe.com/v1/'  -- Stripe API base URL, optional. Default is 'https://api.stripe.com/v1/'
  );
```

4. Create the foreign tables:
```sql

create schema stripe;

create foreign table stripe.customers (
  id text,
  email text,
  name text,
  description text,
  created timestamp,
  attrs jsonb
)
  server stripe_server
  options (
    object 'customers',
    rowid_column 'id'
  );
```

5. Go to the "Table Editor" in Supabase
6. Select the "stripe" schema in the top left of the screen that we've just created in step 4.
7. Click on the foreign table

## Expected behavior

Load and show the data in the foreign table.

## System information

- OS: macOS
- Browser Arc

**Comment by encima** [comment]
Thanks for reporting, can you provide any logs output in the Developer Console as well as anything that seems relevant from the containers themselves?

Have you tried other wrappers, such as S3?
