### ISSUE TITLE
Popover default width is incorrect

### ISSUE THREAD

**Issue by christianhubbard** [supabase/supabase#22047]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Popover components, including but not limited to the datepicker, do not correctly resize to fit their content. I believe the issue comes from an incorrect default prop on the `PopoverContent` component

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to reports/API in the supabase studio
2. Click on the date to open the datepicker
4. See error in datepicker UI

## Expected behavior
the popover component should resize to fit the width of it's content. 

## Screenshots
<img width="457" alt="Screenshot 2024-03-15 at 7 52 20 AM" src="https://github.com/supabase/supabase/assets/59040087/74734602-6b29-4908-b19e-34f57ec7b44c">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

the issue is a default prop on the popover component:
https://github.com/supabase/supabase/blob/b4fde9b3c79da5b2cbf44e259b39c1f2dc819724/packages/ui/src/components/shadcn/ui/popover.tsx#L28

I think `sameWidthAsTrigger` should default to false.

**Comment by ivasilov** [comment]
Fixed in https://github.com/supabase/supabase/pull/22053. Ty for your report!

**Comment by christianhubbard** [comment]
@ivasilov no problem! I tried to make the PR but didn't have access 🫡
