### ISSUE TITLE
Error when creating a table: conflicting NULL/NOT NULL declarations for column "id" of table

### ISSUE THREAD

**Issue by a21y** [supabase/supabase#2205]
# Bug report

## Describe the bug

When trying to create a new table (with default settings, besides the required name field) with an `id` primary key, the following 400 response is returned:

```
{"error":{"code":400,"message":"conflicting NULL/NOT NULL declarations for column \"id\" of table \"companies\""}}
```

The table is still created, despite the error thrown. So I tried to just add the id column manually, but the same error is returned.

I also started a completely fresh project and tried it and the same error arose.

## To Reproduce

1. Create a new Supabase project
2. Go to Table Editor
3. Click New Table
4. Enter a name in the Name field
5. Leave all other settings as is
6. Click Save

## Expected behavior

It should create a table with no errors.

## Screenshots

<img width="673" alt="Screenshot 2021-07-03 at 18 02 02" src="https://user-images.githubusercontent.com/687929/124360403-dded0500-dc29-11eb-9aa3-3923ae1c261f.png">
<img width="667" alt="Screenshot 2021-07-03 at 18 03 15" src="https://user-images.githubusercontent.com/687929/124360407-e34a4f80-dc29-11eb-8ae9-0e999a9bb1ae.png">

## System information

- OS: macOS 11.4
- Browser: Brave

**Comment by chaance** [comment]
I'm using `int4` for `id` (if that matters) but otherwise running into the same blocker.

![image](https://user-images.githubusercontent.com/3082153/124526770-1ae30400-ddb0-11eb-933b-f0d2c1eaa3ad.png)

**Comment by a21y** [comment]
If anyone else is stumbling on this while it's still an issue, the workaround is you can just use the SQL editor to create or update your tables. Go the SQL tab, and open the Welcome tab under Getting Started. Choose the Create Table under Scripts to get a starter script. The line you're looking for in this case is `id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`

**Comment by mcmx** [comment]
Experiencing the same, think for the time being using the SQL editor and creating table with it, is the best option.

**Comment by mcmx** [comment]
I created a new project in a new organization, tried creating a new table, now it's created correctly, went back to the original project created a another table with id as identity also worked correctly, let's say around 6 hours before it failed as before, maybe a fix was deployed?

**Comment by a21y** [comment]
Just tested this myself and looks like it is fixed. Closing.
