### ISSUE TITLE
Supabase Storage API doesn't support createdBy field

### ISSUE THREAD

**Issue by sagar-jani** [supabase/supabase#22051]
While using storage API, I can't find any metadata for the user who uploaded the file.

For example, below is the data given by Supabase,
```
{
    name: 'Test.pdf',
    id: 'cca87101-ef4c-441e-a60b-0711f3167cd4',
    updated_at: '2024-03-15T10:13:03.066Z',
    created_at: '2024-03-15T10:13:03.066Z',
    last_accessed_at: '2024-03-15T10:13:03.066Z',
    metadata: {
      eTag: '"1446bfcea02837e354be613c42e5890a-2"',
      size: 6279126,
      mimetype: 'application/pdf',
      cacheControl: 'max-age=3600',
      lastModified: '2024-03-15T10:13:03.000Z',
      contentLength: 6279126,
      httpStatusCode: 200
    }
```

**Comment by encima** [comment]
Thanks for opening this. This is not exactly a bug, but expected [behaviour](https://github.com/supabase/storage/issues/276). 

To get files for a specific user, you can do a few different things:

- Set [RLS policies](https://supabase.com/docs/guides/storage/security/access-control)
- Store files from users in a subfolder of a bucket with their ID as the name of the subfolder

I will close this but feel free to contribute to the discussions around this if it is a feature you want to see implemented differently (for example, #5479)
