### ISSUE TITLE
Permission denied to access property "getAttribute" - Client-side exception on supabase.com

### ISSUE THREAD

**Issue by sven-93** [supabase/supabase#22064]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I am on the table editor on my supabase project in my dashboard, and I use the three dots to try to edit my table, I get an error: ![error page](https://github.com/supabase/supabase/assets/85342284/ac766dfa-b2dd-4b5e-b065-a8d53632c122)
"Application error: a client-side exception has occurred (see the browser console for more information)."

The console shows these errors: ![errors](https://github.com/supabase/supabase/assets/85342284/4d9d2665-b5fe-409c-a91c-7f25d82f4578)
The ".../authorization" calls are all 404: ![are all 404](https://github.com/supabase/supabase/assets/85342284/ed6d53f6-6647-4fb4-99e8-401e4ad9e38b)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Table Editor' for your project.
2. Click on the '…' to try to edit your table
3. See error

## Expected behavior

To be able to edit your tables

## Screenshots

see above

## System information

- OS: Windows
- Browser firefox

## Additional context

-

**Comment by encima** [comment]
Thank you for opening! I can reproduce this locally but, on a second attempt this works. Can you confirm if this is the same for you if it is continuously 404ing? 🙏

**Comment by sven-93** [comment]
I can confirm, it still throws the same errors when trying to edit a table on the supabase.com table editor:
![image](https://github.com/supabase/supabase/assets/85342284/3ebb3b67-b542-4cc2-bb31-4534df3b32c1)

**Comment by sven-93** [comment]
I mean, I can't be the only one with this problem?
It is affecting supabase.com directly and I am unable to open the "three dot menu" whatsoever.
It immediately crashes. I am kind of relying on the dashboard functionality, as I am not yet fluent in writing it all out in the SQL editor...

**Comment by willnorris** [comment]
Not sure if it's relevant here, but we were debugging a similar issue on Tailscale and found this issue in a web search.  Turns out it was actually [a problem with the ProtonPass firefox extension described here](https://old.reddit.com/r/ProtonPass/comments/1bfe2zi/protonpass_firefox_addon_breaks_websites/).

**Comment by encima** [comment]
Thanks for that @willnorris! @sven-93, can you list the extensions you have installed or try in a fresh browser (like Edge or Chrome)?

**Comment by sven-93** [comment]
Turns out I do infact have the ProtonPass extension enabled.
What a weird coincidence that is. Disabling it fixed the issue for me, thanks @willnorris for that hint. I would have never guessed that was the issue...
