### ISSUE TITLE
Studio Container Unhealthy after start

### ISSUE THREAD

**Issue by dmbr0** [supabase/supabase#22079]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The studio container is in an unhealthy status after started and is inaccessible from localhost:3000

## To Reproduce

I follow the self hosted instructions.

# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Pull the latest images
docker compose pull

# Start the services (in detached mode)
docker compose up -d

## Expected behavior

I expect Studio to be accessible from http://localhost:3000

## System information

- OS: Debian Linux 12
- Browser chrome

**Comment by encima** [comment]
Closing this as it is related to https://github.com/supabase/supabase/issues/21616 

Please comment if you have tried the steps in previous issues and more information about the occurring issue

**Comment by dmbr0** [comment]
I have  tried changing that line in the docker-compose file with the suggestion from the previous issue and the line from PR #21276. The health check still does not pass.
