### ISSUE TITLE
Form content is out of the form

### ISSUE THREAD

**Issue by vvadymk** [supabase/supabase#22078]
# Bug report

## Describe the bug

When I open the modal for deleting the bucket I got such layout
The fields are out of the modal

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com/dashboard/project/[projectId]/storage/buckets/2[bucketName]'
2. Have a bucket with long id(for example: uuid)
3. Open modal for deleting
4. See Problem

## Expected behavior

The fields are in the modal window

## Screenshots

<img width="1728" alt="image" src="https://github.com/supabase/supabase/assets/47254934/c2ae1905-5c23-40e8-80f3-7f4e41a2114c">

## System information

- OS: macOS 14.4
- Browse: Brave

**Comment by saltcod** [comment]
I think this has been fixed already @MildTomato — looks fixed to me

![screenshot-2024-03-19-at-16 24 28](https://github.com/supabase/supabase/assets/105593/f2c75849-d709-42be-ba44-1e4ec119f748)

**Comment by joshenlim** [comment]
able to repro - happens when the bucket name is really long

**Comment by vvadymk** [comment]
As I mentioned it is reproducible with long names. In my case it was uid. @saltcod you used a very short name.
