### ISSUE TITLE
While using supabase with angular ssr cloudflare breaks

### ISSUE THREAD

**Issue by ajitsinghkaler** [supabase/supabase#22086]
# Bug report

    
    

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I use supabase in an angular app I cannot deploy it to cloudflare workers because of node fetch in supabase I get the following error 
```
✘ [ERROR] service core:user:worker: Uncaught Error: Dynamic require of "stream" is not supported

    at null.<anonymous> (lfjl6o3rx1.js:8:9)
    at null.<anonymous> (lfjl6o3rx1.js:20967:38) in node_modules/@supabase/node-fetch/lib/index.js
    at null.<anonymous> (lfjl6o3rx1.js:18185:55) in __require22
    at null.<anonymous> (lfjl6o3rx1.js:83092:33)
```
## To Reproduce

I have created a minimal reproduction at https://github.com/ajitsinghkaler/supabase-reproduction

When you down load this app and run `npm run start` you will see that it fails with the following error 
```
service core:user:worker: Uncaught Error: Dynamic require of "stream" is not supported

    at null.<anonymous> (lfjl6o3rx1.js:8:9)
    at null.<anonymous> (lfjl6o3rx1.js:20967:38) in node_modules/@supabase/node-fetch/lib/index.js
    at null.<anonymous> (lfjl6o3rx1.js:18185:55) in __require22
    at null.<anonymous> (lfjl6o3rx1.js:83092:33)
```
## Expected behavior

It should work and should not fail with the fetch library and should work with cloudflare workers. I think supabase should use fetch library

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. chrome]
- Version of supabase-js: [e.g. ^2.39.8]
- Version of Node.js: [e.g. v20.9.0]

**Comment by encima** [comment]
This issue is opened [here](https://github.com/supabase/supabase-js/issues/917) on the supabase-js repo so closing this one to track it in a single place
