### ISSUE TITLE
Row names are saved with whitespaces. There is no trimming.

### ISSUE THREAD

**Issue by onurusluca** [supabase/supabase#22089]
Saving a table with a whitespace in a row name is allowed. This causes a lot of confusion while trying to use that table and row, not realizing I accidentally put a space in  the name,

Is this intentional? If not, this looks like a bug.

Only tried via the UI.

**Comment by encima** [comment]
Hi @onurusluca, yes, this is expected behaviour. See the [SQL syntax](https://www.postgresql.org/docs/16/sql-syntax-lexical.html) docs for postgres

I see @Hallidayo has opened a PR to alert for this in the dashboard so that should help!

**Comment by joshenlim** [comment]
Hey there @onurusluca - just to follow up on this as what @encima mentioned, i'll go ahead to close this ticket but please do feel free to let us know if you're running into any other issues! 🙏

**Comment by joshenlim** [comment]
Sorry! I just only noticed there's an open PR on the issue - reopening
