### ISSUE TITLE
Error When Updating User Profile

### ISSUE THREAD

**Issue by ElvinKyungu** [supabase/supabase#22083]
Hello everyone,

I'm currently encountering an issue when updating user profiles in our system. Whenever I attempt to update a user profile, I receive an error message stating: "insert or update on table "users_profiles" violates foreign key constraint "public_users_profiles_user_uuid_fkey'".

I have attached a screenshot of the error for clarity.

**Steps to Reproduce:**
1. Log in to the system as an authorized user.
2. Access the user profile update section.
3. Try to update the profile information.
4. Observe the error "insert or update on table "users_profiles" violates foreign key constraint "public_users_profiles_user_uuid_fkey'".

**Screenshot:**
Screenshot error
![Capture d’écran du 2024-03-18 07-34-17](https://github.com/supabase/supabase/assets/85198945/e073cf40-9615-4c2f-9432-0da99c7f13e9)

My editProfil function
``` 
const editProfil = async () => {
  console.log(userEditProfile.value)
  try {
    const updates = {
      user_uuid: userStore.userID,
      name: userEditProfile.value.firstName,
      lastname: userEditProfile.value.lastName,
      email: userEditProfile.value.email,
      role: userEditProfile.value.role,
    }

    let { error } = await supabase.from('users_profiles').upsert(updates)

    if (error) {
      throw error
    }
  } catch (error) {
    console.log(error)
  }
}
```
**users_profiles structure**
![image](https://github.com/supabase/supabase/assets/85198945/0b28f0d0-ad33-4404-ae2f-9d1289507e17)

**Expected Behavior:**
The user profile update should be completed successfully without any error.

## System information

- OS: Linux, ubuntu
- Browser : chrome, firefox 
- Version of supabase-js: last version
- Version of Node.js: LTS version

**Additional Information:**

- This issue appears to be related to a foreign key constraint.
- The affected table is "users_profiles".
- Any assistance in resolving this issue would be greatly appreciated.

Thank you in advance for your help!

Best regards,
Elvin Kyungu

**Comment by encima** [comment]
The issue you are getting is because of the foreign key constraint, yep. This is because the user you are editing does not exist in the linked table so it cannot update.

**Comment by saltcod** [comment]
Going to mark this one as closed as it looks like @encima's answer should give you what you need to get this going. Please feel free to reopen if you discover an issue though!
