### ISSUE TITLE
[Feature request] 2FA

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#2209]
# Feature request

## Is your feature request related to a problem? Please describe.

Two factor authentication (2FA) is a well-known security feature. In my opinion, everyone should enable 2FA for every account. Many larger sites are even making 2FA mandatory (e.g., Twilio). At the very least, every website/app should support 2FA to give users the option.

This is especially important for sites built with Supabase that are not hobby projects.

## Describe the solution you'd like

2FA with authenticator apps are enough for me. While I'm sure some people would like allowing text message 2FA, that is typically less security and more expensive.

## Describe alternatives you've considered

It is entirely possible to handle this all myself, but directly implementing it inside of Supabase would make developer life much easier, and would likely lead to more apps using 2FA.

Alternatively, you could only allow for social logins, though this isn't the most user-friendly. Many users would rather use email/password.

## Additional context

Firebase doesn't support 2FA natively. This could be a differentiating feature for Supabase.

**Comment by kiwicopple** [comment]
Hey @Nick-Mazuk , we're tracking this in the Auth server :)

https://github.com/supabase/gotrue/issues/14
