### ISSUE TITLE
Dashboard allows enabling RLS on auth schema but not disabling

### ISSUE THREAD

**Issue by glib-0** [supabase/supabase#22110]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The dashboard lets me enable RLS for tables in the auth schema, but doesn't let me add policies or turn RLS off without going through the SQL Editor.

## To Reproduce

1. Go to Table Editor,  switch to auth and click Enable RLS

2. See lack of Disable RLS/New Policy buttons on Policies page.

3. Enable RLS button turns into Add New Policy button which just directs to the Policies page. 

## Expected behavior
1. Not possible to enable RLS on auth if it's not actually allowed through the dashboard.
2. Better UI would be for the Enable RLS button to turn into a Disable RLS button. Additional button appears to Add New Policy if enabled.

## Screenshots
![Screenshot 2024-03-19 081414](https://github.com/supabase/supabase/assets/112022846/17aa0672-c3b1-46c4-86b7-81c3ba3083c5)

![Screenshot 2024-03-19 081448](https://github.com/supabase/supabase/assets/112022846/35cd78fc-6d3a-43a2-a72c-59603eea43d3)

![Screenshot 2024-03-19 081507](https://github.com/supabase/supabase/assets/112022846/81a9bc70-e7a2-49eb-81ae-2660efc0a93c) 

## System information
N/A

**Comment by joshenlim** [comment]
hey there @glib-0 thank you so much for reporting this - and sorry about this too! The intended behaviour here is that certain schemas (specifically the ones that Supabase manages) are locked on the dashboard to prevent users from mutating them via the GUI as shown in this warning here
<img width="1198" alt="image" src="https://github.com/supabase/supabase/assets/19742402/9a4e66db-bb94-4276-b423-bb448ce4ed03">

You can still update data within those schemas, but you'll need to do so directly via the SQL editor instead 

I'll push up a fix to address this inconsistency!
