### ISSUE TITLE
Nextjs App initialization is a typo.

### ISSUE THREAD

**Issue by abhinav-anshul** [supabase/supabase#2211]
# Improve documentation
The documentation where the `Supabase` is integrated with `NextJS`, the CLI command is a typo.

## Link 
[https://supabase.io/docs/guides/with-nextjs](https://supabase.io/docs/guides/with-nextjs)

Add a link to the page which needs improvement (if relevant)

## Describe the problem
The documentation where the `Supabase` is integrated with `NextJS`, the CLI command is a typo.  `npx create-next-app supabase-nextjs` should be `npx create next-app supabase-nextjs`

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement
`create-next-app` to `create next-app`

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by nopol10** [comment]
`npx create-next-app` is correct as shown here: https://nextjs.org/docs/api-reference/create-next-app
`npx create next-app` does not work. That format only works for yarn: `yarn create next-app`
