### ISSUE TITLE
GitHub integration – unable to link with any repo

### ISSUE THREAD

**Issue by vonovak** [supabase/supabase#22112]
# Bug report

I'm trying to link my supabase project at `https://supabase.com/dashboard/project/abcde/settings/integrations` to a Github repo. I'm an owner in the organization I'm linking to.

However, even if I give permissions to the Supabase integration to access a repo, supabase won't see it. In fact, it doesn't see any repos that I give access to.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The linking between supabase and github does not work.

I tried different browsers and note that cache is disabled

## To Reproduce

see video. Sorry for the weird format

https://youtu.be/5mLWbhP-D6M

at the end, searching does not work

## Screenshots

At the end of the process, the `repositories` array is empty in devtools.

<img width="452" alt="Screenshot 2024-03-19 at 16 03 19" src="https://github.com/supabase/supabase/assets/1566403/dc66dfc3-308b-4aec-aaf6-b4e0158e5d33">

<img width="368" alt="Screenshot 2024-03-19 at 16 03 24" src="https://github.com/supabase/supabase/assets/1566403/d17b810b-f7d8-4056-8478-f157dfbd1be2">

## System information

- OS: macOS
- Browser (if applies) chrome, firefox

**Comment by alaister** [comment]
Hi @vonovak,

I'm sorry you're running into this. It does seem like this might be an issue with your specific project as I can't seem to replicate it myself.

Would you mind opening up a support ticket here: https://supabase.com/dashboard/support/new with your org ref / project ref, so I can follow up there with you?
