### ISSUE TITLE
signInWithOAuth has thrown "Internal server error"

### ISSUE THREAD

**Issue by kiuthy229** [supabase/supabase#22126]
### Discussed in https://github.com/orgs/supabase/discussions/22124

<div type='discussions-op-text'>

<sup>Originally posted by **kiuthy229** March 20, 2024</sup>
I tried to sign in with Supabase Google Authn but turned out it redirects to an empty page with error
```json
{"code":500,"msg":"Internal server error","error_id":"86732ced27223dab-SIN"}
```
<img width="896" alt="Screenshot 2024-03-20 at 12 09 30" src="https://github.com/supabase/supabase/assets/68453603/1dc1b582-cde0-49c1-a186-7ecf0fe4c9e5">

My code:
<img width="506" alt="Screenshot 2024-03-20 at 12 09 58" src="https://github.com/supabase/supabase/assets/68453603/060ebd2b-fd6b-47d9-9005-ffa9a906a164">

</div>

**Comment by encima** [comment]
As this is happening on a hosted instance, please can you open a support ticket with as much info about your setup as possible?

**Comment by encima** [comment]
If the issue appears to be a global bug then we will comment here. 🙏

**Comment by kiuthy229** [comment]
> If the issue appears to be a global bug then we will comment here. 🙏

Fixed, I think the problems come from the auth.users schema that is used for Authentication. I recreated these tables: 

> go to `Supabase Dashboard > Authentication > Providers`

Disable all Providers then Enable them again, so these tables are recreated
Then the error disappears
