### ISSUE TITLE
Missing Hyperlink in Connection Pooling Config

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [supabase/supabase#2214]
# Missing Hyperlink in Connection Pooling Config

## On https://app.supabase.io/project/[id]/database/pooling there is a missing hyperlink.

For the Pool Mode Option, you say "To find out the most suitable mode for your use case, click here", but there is no link at "click here".

## To Reproduce
1. Go to https://app.supabase.io/project/[id]/database/pooling

## Expected behavior

There should be a hyperlink to the docs that describes what the Pool Mode options is.

**Comment by sandypockets** [comment]
Hi @inian 👋 I'd like to submit a PR to fix this, but finding the correct file has been a bit challenging. Can you point me in the right direction or to a schema about how the repo is structured?

**Comment by inian** [comment]
Hi @sandypockets, the dashboard at app.supabase.io is not open source, so this bug has to be fixed internally. 

We are working on an open source version of the dashboard [here](https://github.com/supabase/supabase/pull/2281). If you can make the self hosted dashboard better, submit a PR based off that branch!

**Comment by kiwicopple** [comment]
The Dashboard is now open-source in case anyone wants to help with this

**Comment by harshcut** [comment]
@kiwicopple do you want the link to point to [*Connection Pooling*](https://supabase.com/docs/guides/database/connecting/connection-pooling) or [*Pool modes*](https://supabase.com/docs/guides/database/connecting/connection-pooling#pool-modes)?

**Comment by kiwicopple** [comment]
Connection Pooling please!

**Comment by harshcut** [comment]
`npm install` for studio currently fails for me on windows with node v14.18.2 and npm v6.14.15.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.71.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.71.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2021-12-29T04_11_21_177Z-debug.log
```

**Comment by Isaiah-Hamilton** [comment]
@harshcut are you still working on this?

**Comment by harshcut** [comment]
I am getting a `RangeError` with `Maximum call stack size exceeded`. It seems like a known ajiv (ajv-validator/ajv#802) issue.
