### ISSUE TITLE
Self hosted not working...

### ISSUE THREAD

**Issue by AmsellemJoseph** [supabase/supabase#22149]
Hey, I tried to deploy a fresh installation of your docker-compose, I followed every docs, but, analytics not working, like my old issue I posted here:
https://github.com/supabase/supabase/issues/17750#issuecomment-1988253318

Ai return me a 500 error with a big error on the right side, and for graphql, I cannot do any query, it always return me "Invalid credentials" even if i make Autorization in Header, and for more fun, basic auth always ask me to login on graphql.

Also I noticed we don't see any details about errors in the logs on the backend side, or a few with informations like error[]...

**Comment by encima** [comment]
Thanks for opening but it seems like there is an existing issue open

Closing this to continue the discussion in the existing open ticket #17750 

More information will always help here, please. Image versions, OS, architecture
