### ISSUE TITLE
GraphQL debugging tools for Apollo Client - Google Chrome extension

### ISSUE THREAD

**Issue by gHashTag** [supabase/supabase#22177]
### Description
I am experiencing an issue where the [Apollo Client debugging tools](https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm) are not appearing on my website, while they work correctly on the official site. I have followed the steps to enable the tools, but the "Apollo" tab does not show up on my site.

### To Reproduce
1. Go to the website.
2. Enable Apollo Client debugging tools.
3. Check if the "Apollo" tab appears.
4. Note that the tab is missing.

### Expected Behavior
I expected the "Apollo" tab to appear when enabling the debugging tools, as it does on the official site. Make sure to pass connectToDevTools: true in the ApolloClient constructor when creating the client. This will allow you to use the Apollo Client developer tools for debugging your GraphQL application in a production environment. If the "Apollo" tab does not appear in your browser's inspector, ensure that the global object window.__APOLLO_CLIENT__ exists in your application. If necessary, you can manually add the Apollo Client instance to window.__APOLLO_CLIENT__ or pass connectToDevTools: true in the ApolloClient constructor.

### System Information
OS: macOS
Browser: Chrome
Version of supabase-js: 2.39.7
Version of Node.js: 20.11.1

### Additional Context
I have verified that this issue is specific to my website and not a general problem with Supabase. I have also checked the documentation, GitHub discussions, and Discord for solutions before reporting this bug.

**Comment by encima** [comment]
Closing this as this is frontend issue unrelated to Supabase. Check the Apollo docs (or the error message) for the commands to pass to the client
