### ISSUE TITLE
Resumable upload never finishes when using uploadLengthDeferred and streams

### ISSUE THREAD

**Issue by gitnik** [supabase/supabase#22179]
## Describe the bug

When using TUS with Resumable Uploads and setting `uploadLengthDeferred` to true, the upload never finishes. No errors are being thrown in any part of the system. I'm having a hard time figuring out whether this is an issue in the supabase code system, or with the underlying tus implementation.
When I set the uploadSize manually and don't use uploadLengthDeferred, everything works. OnSuccess is called and the file is put into the bucket. But since I am using a stream, I can't know the size beforehand.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I have a bucket called `documents` which has public inserts enabled:
<img width="810" alt="Screenshot 2024-03-22 at 13 42 29" src="https://github.com/supabase/supabase/assets/996623/56bb289c-2b59-4fc1-9158-aeccc3ec07dc">

I have the following code, which setup-wise is copied from the official docs:
```typescript
return async ({ name, filename: fileName, contentType, data }: UploadHandlerPart) => {
    if (!fileName) {
      return null;
    }

    const stream = Readable.from(
      ReadableStream.from(data)
    );

    const objectPath = `${fileName}_${randomBytes(16).toString('hex')}`;

    const upload = new tus.Upload(stream, {
        endpoint: `${process.env.SUPABASE_URL}/storage/v1/upload/resumable`,
        metadata: {
            bucketName: 'documents',
            objectName: objectPath,
            contentType,
        },
        headers: {
          authorization: `Bearer ${process.env.SUPABASE_ANON_KEY}`,
        },
        uploadDataDuringCreation: true,
        uploadLengthDeferred: true,
        removeFingerprintOnSuccess: true,
        chunkSize: 6 * 1024 * 1024, // NOTE: it must be set to 6MB (for now) do not change it
        onChunkComplete: function (chunkSize, bytesUploaded, bytesTotal) {
          console.log('chunk complete', arguments);
        },
        onError: function (error) {
          console.log('error', error);
          onError(error);
        },
        onProgress: function (bytesUploaded, bytesTotal) {
          console.log('progress', arguments);
            if (onProgress) {
              onProgress({ fileName, objectPath, contentType, bytesUploaded, bytesTotal });
            }
        },
        onSuccess: function () {
          console.log('done', arguments, upload.url);
          if (onDone) {
            onDone({ fileName, objectPath, contentType });
          }
        },
    })


    // Check if there are any previous uploads to continue.
    return upload.findPreviousUploads().then((previousUploads) => {
      // Found previous uploads so we select the first one.

      if (previousUploads.length) {
          previousUploads.forEach(upload.resumeFromPreviousUpload);
          //upload.resumeFromPreviousUpload(previousUploads[0]);
      }

      // Start the upload
      upload.start();
      
      return JSON.stringify({ objectPath, fileName, contentType });
    });
  };
```

When I'm uploading a single file via this method, onSuccess is never called and the file never ends up in the bucket, but the entire function still finishes and returns.
`onProgress` and `onChunkComplete` both log the messages I would expect:
```
progress [Arguments] { '0': 0, '1': null }
progress [Arguments] { '0': 115, '1': null }
chunk complete [Arguments] { '0': 115, '1': 115, '2': null }
```

No part of the system throws any errors.

Here's the logs from kong, which look legit to me:
```
192.168.65.1 - - [22/Mar/2024:12:49:40 +0000] "POST /rest/v1/documents HTTP/1.1" 201 5 "-" "node-fetch"
192.168.65.1 - - [22/Mar/2024:12:49:40 +0000] "POST /storage/v1/upload/resumable HTTP/1.1" 201 0 "-" "-"
192.168.65.1 - - [22/Mar/2024:12:49:40 +0000] "HEAD /storage/v1/upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fNGU1ODI3MTQ5MjY2ODljNWQzYmE4NTY2MTNlNTA5NGEvZGM4MGRlZjctMDg3OS00ZDY0LWE5NzEtNzhkZjQwZDNlNTZj HTTP/1.1" 200 0 "-" "-"
192.168.65.1 - - [22/Mar/2024:12:49:40 +0000] "PATCH /storage/v1/upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fNGU1ODI3MTQ5MjY2ODljNWQzYmE4NTY2MTNlNTA5NGEvZGM4MGRlZjctMDg3OS00ZDY0LWE5NzEtNzhkZjQwZDNlNTZj HTTP/1.1" 204 0 "-" "-"
```

And the logs from the storage API, which also show no irregularities as far as I can tell:
```
{"level":30,"time":"2024-03-22T12:51:22.772Z","pid":1,"hostname":"3a23b29e889a","reqId":"req-gfm","tenantId":"stub","project":"stub","reqId":"req-gfm","type":"request","req":{"traceId":"req-gfm","method":"POST","url":"/upload/resumable","headers":{"host":"supabase_storage_remix-supabase-saas-kit-ls:5000","x_forwarded_proto":"http","x_forwarded_host":"localhost","x_forwarded_port":"8000","x_real_ip":"192.168.65.1","content_length":"0","tus_resumable":"1.0.0","upload_metadata":"bucketName ZG9jdW1lbnRz,objectName YnJ1bm8uanNvbl8xZDMxNmQ1YmY2OWQyZGUzNzI4MmM3N2RkNTA4ZTFiYw==,contentType YXBwbGljYXRpb24vanNvbg=="},"hostname":"supabase_storage_remix-supabase-saas-kit-ls:5000","remoteAddress":"172.20.0.3","remotePort":35942},"res":{"statusCode":201,"headers":{"tus_resumable":"1.0.0","content_length":0}},"responseTime":48.589708000421524,"msg":"stub | POST | 201 | 172.20.0.3 | req-gfm | /upload/resumable | undefined"}
{"level":30,"time":"2024-03-22T12:51:22.789Z","pid":1,"hostname":"3a23b29e889a","reqId":"req-gfn","tenantId":"stub","project":"stub","reqId":"req-gfn","type":"request","req":{"traceId":"req-gfn","method":"HEAD","url":"/upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fMWQzMTZkNWJmNjlkMmRlMzcyODJjNzdkZDUwOGUxYmMvNDM3NzQzYjItZGM5OS00NDA5LTgxODEtNTQ5ZTVkYTlhODU5","headers":{"host":"supabase_storage_remix-supabase-saas-kit-ls:5000","x_forwarded_proto":"http","x_forwarded_host":"127.0.0.1","x_forwarded_port":"8000","x_real_ip":"192.168.65.1","tus_resumable":"1.0.0"},"hostname":"supabase_storage_remix-supabase-saas-kit-ls:5000","remoteAddress":"172.20.0.3","remotePort":35942},"res":{"statusCode":200,"headers":{"tus_resumable":"1.0.0","upload_offset":0,"upload_metadata":"bucketName ZG9jdW1lbnRz,objectName YnJ1bm8uanNvbl8xZDMxNmQ1YmY2OWQyZGUzNzI4MmM3N2RkNTA4ZTFiYw==,contentType YXBwbGljYXRpb24vanNvbg==,cacheControl bm8tY2FjaGU="}},"responseTime":5.838209003210068,"msg":"stub | HEAD | 200 | 172.20.0.3 | req-gfn | /upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fMWQzMTZkNWJmNjlkMmRlMzcyODJjNzdkZDUwOGUxYmMvNDM3NzQzYjItZGM5OS00NDA5LTgxODEtNTQ5ZTVkYTlhODU5 | undefined"}
{"level":30,"time":"2024-03-22T12:51:22.802Z","pid":1,"hostname":"3a23b29e889a","reqId":"req-gfo","tenantId":"stub","project":"stub","reqId":"req-gfo","type":"request","req":{"traceId":"req-gfo","method":"PATCH","url":"/upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fMWQzMTZkNWJmNjlkMmRlMzcyODJjNzdkZDUwOGUxYmMvNDM3NzQzYjItZGM5OS00NDA5LTgxODEtNTQ5ZTVkYTlhODU5","headers":{"host":"supabase_storage_remix-supabase-saas-kit-ls:5000","x_forwarded_proto":"http","x_forwarded_host":"127.0.0.1","x_forwarded_port":"8000","x_real_ip":"192.168.65.1","content_length":"115","tus_resumable":"1.0.0","upload_offset":"0","content_type":"application/offset+octet-stream"},"hostname":"supabase_storage_remix-supabase-saas-kit-ls:5000","remoteAddress":"172.20.0.3","remotePort":35942},"res":{"statusCode":204,"headers":{"tus_resumable":"1.0.0","upload_offset":115}},"responseTime":9.394416987895966,"msg":"stub | PATCH | 204 | 172.20.0.3 | req-gfo | /upload/resumable/ZG9jdW1lbnRzL2JydW5vLmpzb25fMWQzMTZkNWJmNjlkMmRlMzcyODJjNzdkZDUwOGUxYmMvNDM3NzQzYjItZGM5OS00NDA5LTgxODEtNTQ5ZTVkYTlhODU5 | undefined"}
```

## Expected behavior

According to the TUS documentation, if a stream is supplied and uploadLengthDeferred is used, everything should just work. Again, I am not sure if this a shortcoming in supabase or the tus library.

## System information

- OS: Mac
- Version of supabase-js: 2.39.3
- Version of Node.js: v21.7.1

**Comment by gitnik** [comment]
The relevant issues/MRs I could find on the tus-node-server package are as follows:
https://github.com/tus/tus-node-server/issues/501
https://github.com/tus/tus-node-server/issues/503

I have a hunch those MRs might be what's causing my problem. Seeing how supabase maintains its own [fork of the tus-node-server](https://github.com/supabase/tus-node-server), should I file this bug there and ask for a version upgrade?

**Comment by encima** [comment]
Hi @gitnik ,

Thanks for opening, no need to transfer! We can always move them afterwards but it is often useful to track them in the monorepo.

Will raise thiis with the Storage team to investigate 🙏

**Comment by gitnik** [comment]
OK your remarks gave me some more hints as to where to look.

My `data` is of type `AsyncIterable<Uint8Array>`, which I forgot to mention in the original post.

I got it working by doing the following:

```ts
const stream = Readable.from(
  data, // ReadableStream.from(data) also works
  { objectMode: false }
);
```

When you create a new readable stream, `objectMode` defaults to `false`:
https://nodejs.org/api/stream.html#new-streamreadableoptions

However when using `Readable.from`,`objectMode` is set to `true`:
https://nodejs.org/api/stream.html#streamreadablefromiterable-options

So reverting back to the "default" behaviour makes it so that the stream is fully read and subsequently the `onSuccess ` message is called.

Thanks for your help help. Much appreciated!

See https://nodejs.org/api/stream.html#object-mode
> Object mode
> All streams created by Node.js APIs operate exclusively on strings and Buffer (or Uint8Array) objects. It is possible,
> however, for stream implementations to work with other types of JavaScript values (with the exception of null, which 
> serves a special purpose within streams). Such streams are considered to operate in "object mode".
>
> Stream instances are switched into object mode using the objectMode option when the stream is created. Attempting to switch an existing stream into object mode is not safe.

**Comment by fenos** [comment]
@gitnik Awesome! thanks a lot for detailed explanation! 
Glad you got it working! 🎉
