### ISSUE TITLE
Code generation not working

### ISSUE THREAD

**Issue by gHashTag** [supabase/supabase#22178]
I am facing an issue with code generation using [pg_graphql, Apollo, and GraphQL Code Generator](https://github.com/supabase/pg_graphql/blob/d11f9a0827786fc3cb5d6785efdce74af668c328/docs/usage_with_apollo.md?plain=1#L16)  in my Next.js application. I have followed the setup steps provided in the guide, but the code generation process is not working as expected.

### To Reproduce
1. Followed the setup steps for Apollo and GraphQL Code Generator as described in the guide.
2. Modified the codegen.ts file with the provided configuration.
3. Configured the Apollo Client as per the example provided.
4. Attempted to run the code generation process.
5. Observed that the code generation did not produce the expected output.

### Expected Behavior
I expected the code generation process to generate type-safe GraphQL queries based on the provided configuration. However, the code generation is not functioning correctly.

### Additional Information
I have verified that the setup steps were followed correctly and that the configurations are in place. The issue seems to be related to the code generation process itself. Any guidance or assistance in resolving this issue would be greatly appreciated.

### Code Snippets
I have included the relevant code snippets used for configuring GraphQL Code Generator and Apollo Client in my React application for reference.

```typescript
import type { CodegenConfig } from "@graphql-codegen/cli";
import { addTypenameSelectionDocumentTransform } from "@graphql-codegen/client-preset";

if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
  throw new Error("NEXT_PUBLIC_SUPABASE_URL is not set");
}

const config: CodegenConfig = {
  schema: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/graphql/v1`,
  documents: "src/**/*.tsx",
  overwrite: true,
  ignoreNoDocuments: true,
  generates: {
    "src/gql/": {
      preset: "client",
      documentTransforms: [addTypenameSelectionDocumentTransform],
      plugins: [],
      config: {
        scalars: {
          UUID: "string",
          Date: "string",
          Time: "string",
          Datetime: "string",
          JSON: "string",
          BigInt: "string",
          BigFloat: "string",
          Opaque: "any",
        },
      },
    },
  },
  hooks: {
    // afterAllFileWrite: ["pnpm run lint"],
  },
};

export default config;
```

### package.json

```json
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "generate": "NEXT_PUBLIC_SUPABASE_URL=https://MY_URL.supabase.co graphql-codegen --config ./src/apollo/codegen.ts"
  },
```

### Error
```bash
pnpm generate   
> alpha-huddle01@0.1.0 generate 
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to src/gql/
    ✖
      Failed to load schema from https://dmrooqbmxdhdyblqzswu.supabase.co/graphql/v1:
      Unexpected empty "data" and "errors" fields
      GraphQLError: Unexpected empty "data" and "errors" fields
      at createGraphQLError (/Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+uti…
      at /Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.…
      at Array.map (<anonymous>)
      at getSchemaFromIntrospection (/Users/playra/huddle01-start/node_modules/.pnpm/@graphql-t…
      at /Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.…
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async UrlLoader.load (/Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+u…
      at async /Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphq…
      at async Promise.all (index 5)
      at async loadFile (/Users/playra/huddle01-start/node_modules/.pnpm/@graphql-tools+load@8.…
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
 ELIFECYCLE  Command failed with exit code 1.
 ```

Thank you for your attention to this matter.

**Comment by encima** [comment]
Hey @gHashTag ,

Thanks for opening but this is likely an issue related to the GraphQL tools you are using.
You can confirm this by either:
- Calling the GraphQL endpoint  in curl
- Checking the [GraphQL API Docs page](https://supabase.com/dashboard/project/_/api/graphiql) in the Studio and it will show if there are any issues in the spec.

Will leave it open as we investigate!

**Comment by HuakunShen** [comment]
Same problem here. In documentation https://supabase.com/docs/guides/graphql/with-apollo the url used is localhost.

I am using a cloud supabase instance. Sending request works, but I can't retrieve the schema.

I guess this is because the graphql server doesn't enable introspection.

See apollo server doc https://www.apollographql.com/docs/apollo-server/api/apollo-server/#introspection

So is there a way to enable this feature?

**Comment by HuakunShen** [comment]
Just found out I need to add headers with the access token
```ts
schema: {
    "https://<project ref>.supabase.co/graphql/v1": {
      headers: {
        apiKey: z.string().parse(process.env.SUPABASE_SERVICE_ROLE_KEY),
      },
    },
  },
```

**Comment by Hallidayo** [comment]
Hi @gHashTag - Just checking in here are you still experiencing the same issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
