### ISSUE TITLE
Deploy failed Supabase in Azure Kubernetes Service

### ISSUE THREAD

**Issue by nguyenthanhtien** [supabase/supabase#22196]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I try using this repo to deploy supabase in K8S, but when deploy with this repo, can't deploy to K8S, 2 pod supabase-auth, supabase-rest show error:
https://github.com/supabase-community/supabase-kubernetes 

## To Reproduce

1. Clone git https://github.com/supabase-community/supabase-kubernetes 
2. cd supabase-kubernetes/charts/supabase/
3. # Create JWT secret
```
kubectl -n default create secret generic demo-supabase-jwt \
  --from-literal=anonKey='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjc1NDAwNDAwLAogICAgImV4cCI6IDE4MzMxNjY4MDAKfQ.ztuiBzjaVoFHmoljUXWmnuDN6QU2WgJICeqwyzyZO88' \
  --from-literal=serviceKey='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAic2VydmljZV9yb2xlIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NzU0MDA0MDAsCiAgICAiZXhwIjogMTgzMzE2NjgwMAp9.qNsmXzz4tG7eqJPh1Y58DbtIlJBauwpqx39UF-MwM8k' \
  --from-literal=secret='abcdefghijklmnopqrstuvwxyz123456'
```

4. Create SMTP secret
```
kubectl -n default create secret generic demo-supabase-smtp \
  --from-literal=username='your-mail@example.com' \
  --from-literal=password='example123456'
```

5. Create DB secret
```
kubectl -n default create secret generic demo-supabase-db \
  --from-literal=username='postgres' \
  --from-literal=password='example123456' 
```

6. Install the chart
`helm -n default install demo -f values.example.yaml .
`
## Screenshots

![image](https://github.com/supabase/supabase/assets/9321745/291d8fe5-89e6-4639-a85a-b4d524301dee)
![image](https://github.com/supabase/supabase/assets/9321745/10a1eec4-8014-4a45-9675-eae800c502e3)
![image](https://github.com/supabase/supabase/assets/9321745/051364aa-0092-4e66-b4b7-56db00508713)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Hello @nguyenthanhtien 
Thanks for opening. The kubernetes deployment is community maintained and support comes from the community.

Please open an issue under the https://github.com/supabase-community/supabase-kubernetes repo 🙏
