### ISSUE TITLE
Edge function fails every third execution, given the exact same input

### ISSUE THREAD

**Issue by melnikovkolya** [supabase/supabase#22202]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My edge function fails 1 in 3 times with the following error message:

```
event loop error: TypeError: First argument to respondWith must be a Response or a promise resolving to a Response.
    at Object.respondWith (ext:deno_http/01_http.js:219:15)
    at eventLoopTick (ext:core/01_core.js:64:7)
```

## To Reproduce

This function is not publically available.

## Expected behavior

The function should execute without errors on every execution.

## Screenshots
<img width="1267" alt="image" src="https://github.com/supabase/supabase/assets/1843046/3e8a2269-06bf-4186-8680-5c2f98538e34">

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. chrome, safari] N/A
- Version of supabase-js: [e.g. 6.0.2] 2.39.8
- Version of Node.js: [e.g. 10.10.0] N/A

Thank you very much.

**Comment by melnikovkolya** [comment]
Hi, I found out that the issue was with my function:

I wasn't returning the `Response` as the last statement.

Thank you very much and sorry to bother.

**Comment by encima** [comment]
Thank you for closing!

In the future, if you cannot share the code then it is better to open a support ticket. If we cannot reproduce the issue then we would need to close it.

**Comment by melnikovkolya** [comment]
Thank you @encima 

I will keep it in mind.

Thank you for a great product!
