### ISSUE TITLE
Connection error in `pg_dump`

### ISSUE THREAD

**Issue by gmourasilva** [supabase/supabase#22213]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am no longer able to connect to my db since the last couple of weeks.
My database connection is something like `postgres://postgres.USERNAME:PASSWORD@aws-0-us-east-1.pooler.supabase.com:6543/postgres`

## To Reproduce

```
pg_dump $DATABASE_URL --clean > db.sql

pg_dump: error: connection to server at "aws-0-us-east-1.pooler.supabase.com" (44.208.221.186), port 6543 failed: received invalid response to GSSAPI negotiation: S
```

## Expected behavior

A sql file should be created

## System information

- OS: macOS
- Version of supabase-js: NA
- Version of Node.js: 21

## Additional context

1. I can use the same url in Postico (Postgres client) and things work just fine
2. I double-checked any settings regarding IP blocking. Since Postico works fine, I don't think this is related
3. I was able to run the command above before (Mar 11)
4. I checked `pg_dump` version, 15 like Supabase
5. I also tried the instructions from the docs: https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-psql
6. Checked my DNS (tried 1.1.1.1, 8.8.8.8)

**Comment by encima** [comment]
For pg_dump, please use the direct connection string and not the pooler

**Comment by gmourasilva** [comment]
I have tried that: `DATABASE_URL="postgresql://postgres:[PASSWORD]@db.[PROJECT].supabase.co:5432/postgres"` and nope, getting `pg_dump: error: could not translate host name "db.[PROJECT].supabase.co" to address: nodename nor servname provided, or not known`

In their UI Supabase says "Direct database access via IPv4 and pgBouncer will be removed from January 26th 2024"

**Comment by encima** [comment]
See #17817 for info about IPv6 and IPv4 deprecation. You can enable the IPv4 addon or use tools to make sure your network supports IPv6

**Comment by gmourasilva** [comment]
Thanks @encima 

I was looking at the docs and I can get a similar dump using supabase (https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#backup-your-old-database) 

```
supabase db dump --db-url $DATABASE_URL -f roles.sql --role-only
supabase db dump --db-url $DATABASE_URL -f schema.sql
supabase db dump --db-url $DATABASE_URL -f data.sql --use-copy --data-only
```
