### ISSUE TITLE
supabase cli usage reference page showing 500 error

### ISSUE THREAD

**Issue by rookledookle** [supabase/supabase#22259]
# Improve documentation

## Link 

https://supabase.com/docs/reference/cli/usage

## Describe the problem

Page is throwing a 500 error

**Comment by charislam** [comment]
<img width="1508" alt="image" src="https://github.com/supabase/supabase/assets/26616127/c27e1eef-8de1-480f-8b54-81c1df67a846">
I can't seem to reproduce, is it still erroring for you?

**Comment by rookledookle** [comment]
its not now thank you!
