### ISSUE TITLE
Confirmation on row deletion in database dashboard.

### ISSUE THREAD

**Issue by JamesGarbaczewski** [supabase/supabase#2225]
# Feature request

## Is your feature request related to a problem? Please describe.

It is possible to accidentally delete more rows than planned.

## Describe the solution you'd like

When selecting multiple rows and clicking delete I believe there should be a confirmation with the count of the rows to be deleted.

## Additional context

I don't believe it needs anything more than a confirmation.  However, I was fairly surprised with the lack of a confirmation.

**Comment by FatumaA** [comment]
Hey @kiwicopple ,
This does not seem to be the case anymore?

https://user-images.githubusercontent.com/67555014/151615764-9a4ecb25-5d17-4123-b588-a5dc5ee5a235.mov

**Comment by Isaiah-Hamilton** [comment]
Thank you @FatumaA. Seem that this feature was added.
