### ISSUE TITLE
user todo template and policy

### ISSUE THREAD

**Issue by duncanhealy** [supabase/supabase#223]
# Feature request

## Is your feature request related to a problem? Please describe.

Add example template for user and list with nested todo
It should be able to restrict access to the user with fine grained permissions on the row level
It could be implented in different example projects (react,vue,svelte,ng, etc...)

## Describe the solution you'd like

Clear policy with secure implementation in mind

## Describe alternatives you've considered

seperate implentation and template per project

## Additional context

#209 #215

**Comment by mariusa** [comment]
Hi,

regarding the solution:

users should own lists.
tasks belong to lists.
There's no need to have tasks.user_id

anybody authenticated can INSERT lists
anybody owning a list can
2.1. UPDATE/DELETE that list and
2.2. do anything on tasks belonging to that list

**Comment by duncanhealy** [comment]
Hi @mariusa 

the limiting to a specific user is a simpler case - 
was looking to see if we could enable the more general case - allow multiple users to a specific list 
and enable a policy to cover the row security 

so users can have multiple lists 
lists can have multiple todos
todos can be assigned to a person

There are specific use cases for this (say a shared todo list like a shopping list between partners)

Have tried to create policy for a fk constraint to allow reads for shared list but it doesn't work

some of the failed examples below:
```sql
-- CREATE POLICY "Allow logged-in read access" on tasks FOR SELECT USING  ( select count(user_id) from (SELECT user_id from userlists where userlists.list_id=list_id ) > 0);
-- CREATE POLICY "Allow read access to shared lists" on tasks FOR SELECT USING (SELECT user_id from userlists where userlists.lists_id=lists_id );
-- ALTER TABLE tasks SET ROW SECURITY FOR  SELECT TO (SELECT users_id from userslists where userlists.lists_id=list_id);
-- CREATE POLICY "Allow logged in user to see items on their current list" on tasks FOR SELECT USING ( select list_id from public.users where public.users.list_id=list_id AND public.users.user_id=auth.uid() )

```

A workaround could be to add the list_id to the public.user and match on that 
or pg foo to get policy to work :)
or put into a json field and add a {uid: true} if they have access

**Comment by mariusa** [comment]
> was looking to see if we could enable the more general case - allow multiple users to a specific list
> and enable a policy to cover the row security

That would be interesting!

**Comment by duncanhealy** [comment]
the names of the policies etc need to be cleaned up and probably the names of the fields I put the extra s in the userlists fields to signify that they were many to many

**Comment by duncanhealy** [comment]
:beers: for @thorwebdev next time in Dublin :) 
I think before we merge this we get the svelte, react, ... and todo examples updated to this and make it easier to run the template!

**Comment by thorwebdev** [comment]
Thanks @duncanhealy. Let's wait for @kiwicopple to review. From https://github.com/supabase/supabase/issues/215#issuecomment-701872927 I understand that he wants to make this a quick start template on app.supabase.io, so all examples can use the same schema 👍

**Comment by kiwicopple** [comment]
Thanks for starting this issue @duncanhealy !

I think the primary goal of the quick-start templates should be simplicity. It needs to be approachable for people who are just starting out with Postgres.

I can imagine the schema you've created being used on something more like a `collaborative-todo` example. Perhaps we do 2 different files - one for a collaborative todo and another for just bare-bones beginners? Your original file was actually very good. If I was to add some modifications it might be like this:


```sql

create table lists (
  id            bigint generated by default as identity primary key,
  name          text not null,
  user_id       uuid REFERENCES public.users NOT NULL,
  inserted_at   timestamp with time zone DEFAULT timezone('utc' :: text, now()) NOT NULL
);

create table tasks (
  id            bigserial PRIMARY KEY,
  task_text     text NOT NULL,
  complete      boolean DEFAULT false,
  list_id       bigint REFERENCES lists NOT NULL,
  inserted_at   timestamp with time zone DEFAULT timezone('utc' :: text, now()) NOT NULL
);


alter table lists enable row level security;
alter table tasks enable row level security;


create policy "Individuals can create lists." 
  on lists for insert with check ( auth.uid() = user_id );

create policy "Individuals can view their own lists. " 
  on lists for select using ( auth.uid() = user_id );

create policy "Individuals can update their own lists." 
  on lists for update using ( auth.uid() = user_id );

create policy "Individuals can create tasks in their own lists." 
  on tasks for insert with check ( list_id in ( select id from lists where user_id = auth.uid() ) );

create policy "Individuals can view tasks that exist in one of their lists." 
  on tasks for select using ( list_id in ( select id from lists where user_id = auth.uid() ) );

create policy "Individuals can update their own tasks." 
  on tasks for update using ( list_id in ( select id from lists where user_id = auth.uid() ) );

```

I haven't tested this, but the concepts are there: users create lists, which contain tasks. The users can only insert tasks into lists which they have created. Let me know what you think.

**Comment by duncanhealy** [comment]
I'll test this over weekend and add some tests to #215

**Comment by kiwicopple** [comment]
Legend, thanks @duncanhealy 👍
