### ISSUE TITLE
Row lwl security errors

### ISSUE THREAD

**Issue by Jacob-CZ** [supabase/supabase#22323]
# Bug report

## Describe the bug

this an api issue and it may be because i set something stupid but,
i never get the row level security error when selecting rows and just get an empty array and spend an hour debugging.
What is the most confusing is that i believe that at the beginning  i used to get the rls error but now i dont. could something be done about that?

## Expected behavior

I would expect to get a rls error from the client when i break the policies or if no policies exist.

## System information

Irrelevant but :
- Garuda linux - hyprland

**Comment by GaryAustin1** [comment]
This is not a bug issue, but a help request.
Select operation will not return an error but instead act like the rows do not exist.

**Comment by Jacob-CZ** [comment]
The problem was that sometimes it returns a empty [] and sometime a ali error new row violate rls

**Comment by GaryAustin1** [comment]
Selects and updates will not error while reading.  You will get back [].
Inserts will error.
This is how Postgres works.
https://www.postgresql.org/docs/current/sql-createpolicy.html
![image](https://github.com/supabase/supabase/assets/54564956/2c97f1b6-884a-4880-a21e-8fddb4b6d9d7)
