### ISSUE TITLE
Im not able to create free project in PRO organization

### ISSUE THREAD

**Issue by Tananga** [supabase/supabase#22332]
Hello. I upgraded my organisation from FREE to PRO. Problem which I have is that I also need second free organisation because Im not able to create free projects in PRO organization. I created youtube video about that. Please take a look https://youtu.be/M1whUMhh2Hk?si=kZkxxesR7gMV1EZ2

**Comment by GaryAustin1** [comment]
Your free organizations need to be in their own orgs.

**Comment by GaryAustin1** [comment]
No it is the way it is designed.
![image](https://github.com/supabase/supabase/assets/54564956/1c4b961d-836d-4797-ab32-cc052b3f67e8)
https://supabase.com/docs/guides/platform/org-based-billing#how-billing-is-organized
