### ISSUE TITLE
 const session = supabase.auth.session()

### ISSUE THREAD

**Issue by KTayy** [supabase/supabase#22341]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/v1/auth-session

## Describe the problem

const session = supabase.auth.session()
it seems that this should not be a function? unless I am calling it wrong in my code. When I try to use 
const session = supabase.auth.session() I get an error telling me this is not a function.

I am new to supabase so I might be missing something and would appreciate being pointed in the right direction on how to properly retrieve session info. Thanks!

**Comment by adimankotia** [comment]
Are you using v1 of the library? In v2 the function is const { data, error } = await supabase.auth.getSession().

**Comment by KTayy** [comment]
Youre very right, I did not notice until this morning that I was looking at
old docs.


Sorry about that
