### ISSUE TITLE
Invitation email link is broken

### ISSUE THREAD

**Issue by alon710** [supabase/supabase#2235]
# Bug report

## Describe the bug

When I invite new user using the UI
![image](https://user-images.githubusercontent.com/35544532/124567167-6d71fe00-de4c-11eb-9d69-42e2a99a11ff.png)
The email that I receive contains a broken link:
![image](https://user-images.githubusercontent.com/35544532/124567299-8bd7f980-de4c-11eb-99b9-45bbbdeb9d2e.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.io/
2. Click on `Authentication`
3. Click the `invite` button on the top right corner
4. Send invitation email

## Expected behavior

The link that received should not be to localhost.

## Screenshots

Added above.

**Comment by kiwicopple** [comment]
Hey @alon710 - just to double check, did you create this project through the Vercel integration?

**Comment by alon710** [comment]
> Hey @alon710 - just to double check, did you create this project through the Vercel integration?

I'm not sure what do you mean, can you elaborate?

**Comment by Symasia** [comment]
Just throwing this out here, but shouldn't you change the Site URL and additional redirect URLs according to your project's domain? The email sends the link set as the site URL I think

**Comment by alon710** [comment]
> Just throwing this out here, but shouldn't you change the Site URL and additional redirect URLs according to your project's domain? The email sends the link set as the site URL I think

I've looked at my Supabase dashboard, under settings most URL inputs are correct 
Only under auth settings, the URL is localhost:

![image](https://user-images.githubusercontent.com/35544532/125246897-04cacb80-e2fb-11eb-871b-7711841be155.png)
 
Obviously, I can change it, but all other inputs have the correct URL out-of-the-box.

**Comment by kiwicopple** [comment]
This is correct @alon710  - you will need to update this URL to be the location that you wish to send the user to after they are authenticated.

> all other inputs have the correct URL out-of-the-box.

What is the correct URL in your case? We don't have a way to determine where we should send the user as you will be the one to decide where you host your website/app - so this input is for you to fill out

**Comment by alon710** [comment]
> This is correct @alon710 - you will need to update this URL to be the location that you wish to send the user to after they are authenticated.
> 
> > all other inputs have the correct URL out-of-the-box.
> 
> What is the correct URL in your case? We don't have a way to determine where we should send the user as you will be the one to decide where you host your website/app - so this input is for you to fill out

Maybe it should be part of the creation of a new organization \ project
