### ISSUE TITLE
Setting up Server-Side Auth for Next.js project does not work 

### ISSUE THREAD

**Issue by Kjazer004** [supabase/supabase#22357]
Nothing else to add, that project seems very half-assed to be fair, private route doesn't work, signup doesn't work properly. When I press sign up, it just redirects me to home page even tho new user is registered. When I login with that same user, it still doesn't work, can't get to any protected routes. Exact same thing is also with Build a User Management App with Next.js. On the other note, documentations are really not beginner friendly at all, I always have issues finding what I am looking for, and even if I did find it, the first time I'd miss it because it's just confusing to understand it.

**Comment by charislam** [comment]
Hey @Kjazer004! Sorry to hear about your frustrations with the tutorials.

I just tried to set up the server-side tutorial from scratch, and it's working for me, so let's see if we can't get to the bottom of this.

First, is your Supabase project in the cloud or run locally? (I.e., does your Supabase URL have the domain `https://xxx.supabase.co` or localhost?)

If it's in the cloud:

1. Did you change the email template for SSR as described in Step 6?
2. Are you getting the signup confirmation emails?

**Comment by Kjazer004** [comment]
Hello, @charislam , thanks for replying. I have resolved the issue, seems it was an issue on my part so I apologize, got it working now

**Comment by charislam** [comment]
Awesome! Glad to hear it worked! I'll close this issue then
