### ISSUE TITLE
bug: TypeError: fetch failed

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [supabase/supabase#22366]
# Bug report

`const client = createClient("https://hcxjcvedaxvkexjhvwik.supabase.co", SUPABASE_API_KEY)

// insert into supabase
const res = await client.from("documents").insert({
    content: "hi",
    embedding: embeddingsArr
})

console.log(res)`

sometime it works sometime i am getting error 

![image](https://github.com/supabase/supabase/assets/94217498/1f9eb055-5ef1-4048-bc66-fbe3ad4c1074)

**Comment by encima** [comment]
Thanks for opening! Can you confirm that you are using the latest version of supabase-js and the version of node that you are running?

**Comment by Shyam-Raghuwanshi** [comment]
@encima yes

**Comment by Mohammed-Yasin-Mulla** [comment]
@Shyam-Raghuwanshi could you please share the node version you are running?

Please correct me if I am wrong, I believe you are trying to log the inserted values correct? 
If so please follow the example code from the docs [here](https://supabase.com/docs/reference/javascript/insert?queryGroups=example&example=create-a-record-and-return-it)

You are supposed to add `.select()`  to  tell supabase client to return the inserted value

**Comment by mhle** [comment]
I'm getting this same error when running on aws lambda node 20 runtime
