### ISSUE TITLE
Admin must lose all previously created cron jobs just to create a new one

### ISSUE THREAD

**Issue by bitnom** [supabase/supabase#22389]
This is occuring in Supabase cloud/dashboard. Attempting to create a new pg_cron job results in a Permission Denied error. The only way to bypass it is disable and then re-enable the pg_cron extension, which results in all previous cron jobs being wiped.

Previous related issue: https://github.com/supabase/supabase/issues/19322

**Comment by encima** [comment]
Closing this one to continue discussion in original.
