### ISSUE TITLE
 Interval type values change when using table editor

### ISSUE THREAD

**Issue by kaelruland** [supabase/supabase#22388]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Interval type values change when using table editor

## To Reproduce

In a table with column type `interval`, the detailed row editor (right-click > edit row) will display the JSON representation of the interval, but does not save the interval correctly, or sometimes fails to save at all. For example a representation of `{"days":7}` will change the interval value to 7 seconds, regardless of whether input in the row editor was changed.

Interval literals entered in the editor like `1 year 2 seconds` will save properly, but not on subsequent saves when the value in the editor is converted to JSON representation.

## Expected behavior

Interval representation in the editor should reflect the value updated in the db row.

## System information

- OS: [Windows]
- Browser (if applies) [Firefox]

## Additional context

Personally I would not mind ISO 8601 format for editing intervals in the table editor.

**Comment by soedirgo** [comment]
Thanks for the report! This should be fixed now - `interval` columns are now displayed using its text representation.
