### ISSUE TITLE
Sidebar highlights wrong section in JavaScript SDK docs

### ISSUE THREAD

**Issue by mdwelsh** [supabase/supabase#22408]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/range

## Describe the problem

When clicking on an element in the sidebar, the *next* subsection is highlighted in green, not the currently-selected section.

I know this is minor. It has confused me a bunch of times, though, since when navigating the documentation I am often referencing the sidebar to see what else I can do, which has meant that I have sometimes missed the next subsection because it is currently highlighted (and I think that means I'm already looking at it).

## Describe the improvement

The highlighted section in the sidebar should be the same as the one currently selected.

## Additional context

In this screenshot, my mouse has clicked on and is hovering over the "Order the results" subsection, but the following one is highlighted.

![Screenshot 2024-04-02 at 9 13 58 AM](https://github.com/supabase/supabase/assets/996692/d95bc263-f99d-4b8e-ab32-8457a9fbc9e6)

**Comment by charislam** [comment]
Hmm this might be a UX problem, not a bug per se. For me, it looks like the _current section_ is highlighted in green, and the section you are hovering over is highlighted in white (or black in light mode). Which is certainly a contrast problem, but the thing getting highlighted is correct.

Is that not the case for you?

**Comment by encima** [comment]
I can sort of replicate (this could be due to monitor sizes and/or resolutions). The link provided gives a similar output (range is the section but it shows the section below as active):
 
<img width="1620" alt="image" src="https://github.com/supabase/supabase/assets/517923/1997f488-8b6d-4784-b037-907974f0f37b">

It also never highlights `range` as the current section so, when scrolling up, it skips the section entirely.

**Comment by Hallidayo** [comment]
Hi all - Is this still happening for everyone? I've just tried the link and it seems to highlight the correct section?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
