### ISSUE TITLE
Linked example does not use Supabase

### ISSUE THREAD

**Issue by LukeHosk** [supabase/supabase#22407]
# Improve documentation

## Link 

[supabase docs](https://supabase.com/docs/guides/database/connecting-to-postgres/serverless-drivers)
[github](https://github.com/supabase/supabase/blob/9be160a51faad089eb8bcd35baa14971d4be8505/apps/docs/content/guides/database/connecting-to-postgres/serverless-drivers.mdx?plain=1#L32)

## Describe the problem

The [linked Drizzle example](https://github.com/vercel/examples/tree/main/storage/postgres-drizzle) uses Vercel Postgres not Supabase, the Supabase docs should only link to examples that use Supabase.

## Describe the improvement

Either:
- Link to a different example that actually uses supabase
- Remove the link

**Comment by LukeHosk** [comment]
I think I may perhaps have been misunderstanding the example's purpose. It may just be that the part where it says it's a 'template that uses Supabase' should be changed.

**Comment by encima** [comment]
The template setup does integrate with Supabase and Github once clicked through, so it will set the env variables to the Supabase project you link with [Vercel](https://supabase.com/partners/integrations/vercel). Agreed that it is confusing, though, and the example could be updated/removed. PRs welcome!

**Comment by Sahil-kachhap** [comment]
@encima what change needs to be made here, can you state this thing in a more clear way. I am new to this repo, just wanted to know what change is required here.

Do I just need to make the example description of Drizzle example to:-  
description: "Simple Next.js template that uses Drizzle as the ORM." 
[on this line](https://github.com/supabase/supabase/blob/9be160a51faad089eb8bcd35baa14971d4be8505/apps/docs/content/guides/database/connecting-to-postgres/serverless-drivers.mdx?plain=1#L33C1-L34C1).

**Comment by LukeHosk** [comment]
I think the problem is that it doesn't explain how supabase is used in the example.

As far as I can tell it's using the Vercel-Supabase integration to use a Supabase hosted database with a generic Drizzle & Vercel codebase. But this isn't explained anywhere.

Ideally someone who actually understands this example can add enough context to make it more obvious to people searching through the docs.
