### ISSUE TITLE
Redirect URL is not associated with Twitter

### ISSUE THREAD

**Issue by rogersm-uwosh** [supabase/supabase#22435]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/guides/auth/social-login/auth-twitter)

## Describe the problem

The page says that the Redirect URL is found in Providers under Twitter, but the Redirect URL appears to be in a separate section titled URL Configuration

Is the documentation missing? Or is it confusing? Why is it confusing?

It is incorrect and therefore confusing.

## Describe the improvement

Find your callback URL

The next step requires a callback URL, which looks like this: https://<project-ref>.supabase.co/auth/v1/callback

Go to your [Supabase Project Dashboard](https://supabase.com/dashboard)
Click on the Authentication icon in the left sidebar
Click on [URL Configuration](https://supabase.com/dashboard/project/_/auth/?????) under the Configuration section
There you'll find your Redirect URL, you can click Copy to copy it to the clipboard

## Additional context

I tried to make a PR, but the actual lines above were linked to somewhere else and I couldn't get it to work, so I'm just writing this instead.

Previously the docs read as follows:

Find your callback URL
The next step requires a callback URL, which looks like this: https://<project-ref>.supabase.co/auth/v1/callback

Go to your [Supabase Project Dashboard](https://supabase.com/dashboard)
Click on the Authentication icon in the left sidebar
Click on [Providers](https://supabase.com/dashboard/project/_/auth/providers) under the Configuration section
Click on Twitter from the accordion list to expand and you'll find your Redirect URL, you can click Copy to copy it to the clipboard
Add any other context or screenshots that help clarify your question.

**Comment by encima** [comment]
thanks for this, it is certainly a type for `Callback URL` and it seems a PR has been opened so should be fixed soon

**Comment by Hallidayo** [comment]
Hi everyone, A a pull request has been merged that fixes the issue I'm going to close this one now.
