### ISSUE TITLE
Rename Table & Add FK Constraint at the same time

### ISSUE THREAD

**Issue by philbaker4** [supabase/supabase#2244]
# Bug report

## Describe the bug

When trying to rename a column and make that column a FK relation, I get the following error: 
"Error updating foreign key: column "[my new column name]" referenced in foreign key constraint does not exist"

## To Reproduce

Create TableOne with and id
Create TableTwo with column soonToBeRenamed
Edit soonToBeRenamed - set name to "renamed" and add foreign key relation to tableOne id
Attempt to save

## Expected behavior

I would expect the column to be renamed and for the FK relation to be added

## Screenshots

<img width="309" alt="Screen Shot 2021-07-06 at 10 52 37 AM" src="https://user-images.githubusercontent.com/17916326/124631098-ab6d2300-de48-11eb-8cb4-875b8878a2f2.png">

## System information

- OS: MacOS
- Browser: Chrome 91.0.4472.114

**Comment by philbaker4** [comment]
A simple workaround exists - if you update the column name & save before re-entering edit mode and adding the FK, you're able to get the desired table state

**Comment by joshenlim** [comment]
hey there @philbaker4 ! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!

**Comment by philbaker4** [comment]
Tested and works - thanks !
