### ISSUE TITLE
Custom Domain incorrectly shown in studio

### ISSUE THREAD

**Issue by ajayvignesh01** [supabase/supabase#22479]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

- Project API tab in Studio shows default supabase url even after adding a custom domain.
- When turning on the feature flag to show the new "Project API Documentation", it shows the custom domain but with an unnecessary subdirectory ```auth/v1/callback```. See attached screenshots.

## To Reproduce

1. Add a custom domain and open "Project API" tab in Studio to observe first bug from above.
2. Add a custom domain, turn on "Project API Documentation" feature flag, and open "Project API" tab in Studio to observe second bug from above.

## Expected behavior

- For bug 1, custom domain should be reflected in places mentioning supabase url when a custom domain is added.
- For bug 2, custom domain should be reflected without a subdirectory added, like "api.example.com" instead of the current "api.example.com/auth/v1/callback"

## Screenshots

<img width="1437" alt="Screenshot 2024-04-04 at 9 56 41 AM" src="https://github.com/supabase/supabase/assets/138313465/45636a57-6039-41f3-b7b3-cd5361e932f4">
<img width="1437" alt="Screenshot 2024-04-04 at 9 57 06 AM" src="https://github.com/supabase/supabase/assets/138313465/43931d8c-d6b3-46bb-9421-626f5e56c88b">

## System information

- OS: macOS 14.2.1
- Browser: Chrome 120.0.6099.199

**Comment by encima** [comment]
Thanks for opening this! Certainly makes sense and I have added the labels for the frontend team to triage
