### ISSUE TITLE
Replace "HonosJS" with "HonoJS" or "Hono"

### ISSUE THREAD

**Issue by shinaps** [supabase/supabase#22496]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/66fc6fa30a413f52f2527c589b5daea04c390c66/apps/docs/content/guides/resources/examples.mdx?plain=1#L153

## Describe the problem

It's mistakenly typed as `HonosJS` instead of `HonoJS`.

## Describe the improvement

The name of the framework is `Hono`, so it would be better to correct it from `HonosJS` to  `Hono`.

## Additional context

https://hono.dev/

**Comment by encima** [comment]
PRs welcome!

**Comment by nilayg99** [comment]
Please assign the task to me. #22496

**Comment by charislam** [comment]
Thanks for your interest! Closing because the fix was already merged
