### ISSUE TITLE
Not able to fetch Signed in user from Supabase after google Oauth Sign in

### ISSUE THREAD

**Issue by Xaid-vfx** [supabase/supabase#22493]
### Discussed in https://github.com/orgs/supabase/discussions/22492

<div type='discussions-op-text'>

<sup>Originally posted by **Xaid-vfx** April  5, 2024</sup>
I am using Supabase OAuth for google sign up in my project. Below is the code where I have specified the redirect URL:

```const signInWithGoogle = async () => {
        const { data, error } = await supabase.auth.signInWithOAuth({
            provider: 'google',
            options: {
                queryParams: {
                    access_type: 'offline',
                    prompt: 'consent',
                },
                redirectTo: currentUrl + '/complete_profile'
            },

        })
    }
```
The `'/complete_profile'` route is used to enter the user details and should be seen by the user only the first sign in. When the user signs in again he should be redirected to `'/all-jobs'` since he has already filled the details during first sign in.

The approach I am using for this is Supabase `getUser()` function which will get the current signed in user and check that user in the database, if a record exists the user will be redirected to `/all-jobs` 

getUser() Code:
```
import { createClientComponentClient, createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"

export default async function getUser() {
    cookies().getAll()
    const supabase = createServerComponentClient({ cookies })
    const { data: { user }, error } = await supabase.auth.getUser()
    console.log(user);
    console.log("error" + error);
    return user;
}
```
Complete Profile code (server component):
```
import LeftColomn from "@/components/SignUp/LeftColomn/LeftColomn";
import RightColumnSeeker from "@/components/SignUp/RightColomnSeeker/RightColomnSeeker";
import getUser from "@/lib/getUser/getUser";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

async function checkIfUserExists(id: string) {
    console.log("Inside function")
    console.log(id);
    cookies().getAll()
    const supabase = createServerComponentClient({ cookies })
    const { data, error } = await supabase
        .from('Seekers')
        .select()
        .eq('unique_id', id)
        .single()

    if (error) { console.log(error); }

    return data;
}

export default async function CompleteProfile() {
    const user = await getUser();
    const result = await checkIfUserExists(await user?.id)
    console.log(result);



    if (result?.unique_id) {
        redirect('/all-jobs')
    }
    else {
        return (
            <div className="flex h-screen">
                <LeftColomn />
                <RightColumnSeeker />
            </div>
        )
    }
}
```

**The Problem**

The `getUser()` function returns null and gives the following error:

    errorAuthApiError: invalid claim: missing sub claim

But `getUser()` function returns the expected user(and user is redirected as well) if I hit refresh on `/complete_profile` after being redirected from google sign in or if I visit the route `/complete_profile` by typing in search bar. This problem only exists when I am getting redirecting after google sign in.</div>

**Comment by Hallidayo** [comment]
Hi @Xaid-vfx - just checking in here, are you still having the issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
