### ISSUE TITLE
Client requests to Supabase take too much time occasionally.

### ISSUE THREAD

**Issue by mubashir-zenkoders** [supabase/supabase#22508]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The bug is, I am using Supabase in my nextjs project, on the server and client side, I am facing this issue that sometimes, any (small or long) queries to the DB take too much time to respond like minutes. And when, I refresh the page, to repeat the same req, it just works. I have verified that the issue is with supabase.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. As this happens occasionally, I don't have clear steps to reproduce this issue, but it happens when you use supabase js client to make requests to the db.
2. If you run those requests 20-sh times, you will see spikes in some requests.

## Expected behavior

Supabase queries to DB should respond quicker, under 100ms, not 1000s of ms.

## System information

- OS: Ubuntu 22 LTS
- Browser: Any browser, I tried in fire, chrome and ms edge
- Version of supabase-js: 2.3
- Version of Node.js: 20

## Additional context

I using the supabase js client in client component in nextjs v14 app router based project.

**Comment by mubashir-zenkoders** [comment]
My issue is exact match to this one, but this issue closed, that's why I created new one.

https://github.com/supabase/supabase/issues/937

**Comment by encima** [comment]
This can certainly happen, especially when Supabase is "just postgres" under the hood. 

What you can check:
- Use the [Logs Explorer](https://supabase.com/dashboard/project/_/logs/) and find out what queries are taking too long
- Check the [Query Performance](https://supabase.com/dashboard/project/_/database/query-performance) page in the dashboard
- Then check those queries with the [index advisor](https://supabase.com/docs/guides/database/extensions/index_advisor)
- Use the CLI to run [inspect](https://supabase.com/docs/reference/cli/supabase-inspect-db) commands against the DB
- Check the 

Information we would need:
- Are you querying from the same region as your project?
- Have you optimised your database at all?
- Is this from API calls or RPC or pure SQL?
- Are you connecting directly or through the pooler (Supavisor)?

**Comment by mubashir-zenkoders** [comment]
I am using Supabase js client to connect to the supabase.

```ts
supabase.from('someTable').select('*')
```

My database is new, just created a month, ago, no production users, only my testing data is there.

This is from the supabase js client from nextjs project. I am not connect to db directly neither I am using RPC.

I have generated this report for you, as you can see usage not ver high or even high.

![image](https://github.com/supabase/supabase/assets/153497498/2dc4bea2-82bc-47fb-bdbf-ffcb3adb2e8d)

**Comment by encima** [comment]
Thanks, this is a start, you would need to perform the other steps as well (index_advisor and `inspect` in the CLI to see index usage).

It could also be how the queries are made, do you have info from the `Network` panel in your browser to see the max time a query takes? Removing the application, you could also make the calls in the command line to try and narrow down the cause

**Comment by mubashir-zenkoders** [comment]
Ok, let me try and debug it in depth.

Thank you so much. I really appreciate your help. :tophat:

**Comment by encima** [comment]
Happy to help! Please feel free to post anything here if you want additional help, it will certainly help others and we can add any general advice into the docs.

**Comment by mubashir-zenkoders** [comment]
I am also getting a weird issue since the beginning when I started to use the supabase.

Somehow, supabase JS client on the browser side does not makes req to the supabase at all, but using the same code on the server side it works simply fine.

For example, in nextjs v14, on client side, following code sometimes requests the supabase backend, and sometimes doesn't make any requests at all, resulting in loading forever.

I have verified it using the network tab.

This exact same code works on the server side in the API.

This happens sometimes, sometimes, just refreshing page also fixes the issue.

```ts
useEffect(()=>{
const supabase = createClient(...)

// when added console.logs, code does not process further this statement.
const {data, error} = await supabase.from('posts').select('*').limit(20)

// handle data and error

}, [])
```

**Comment by encima** [comment]
Ah, that one we may not be able to fully help with as it is more about NextJS behaviour. Without seeing all the code (no need to provide it!), you could:
- make sure that this not async as [client components cannot be async](https://nextjs.org/docs/messages/no-async-client-component)
- try disabling strict mode to see if it helps with debugging

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by robertoandrade** [comment]
seeing the same in a react project. no one found the root cause for this?

**Comment by SAGAR-TAMANG** [comment]
Same issue.

**Comment by carmonasl** [comment]
Same issue

**Comment by KoolKat-Bytes** [comment]
Same issue here, response time of supabase postgres database is unpredictable.

My stack: React SPA + Nodejs backend via Prisma)

**Comment by deitrix** [comment]
Also seeing this with the supabase nextjs template. Sometimes, `proxy.ts` is taking over 5 seconds!
```
 GET /instruments 200 in 130ms (compile: 2ms, proxy.ts: 47ms, render: 81ms)
 GET /instruments 200 in 137ms (compile: 2ms, proxy.ts: 49ms, render: 85ms)
 GET /instruments 200 in 5.3s (compile: 3ms, proxy.ts: 5.2s, render: 143ms)
 GET /instruments 200 in 161ms (compile: 2ms, proxy.ts: 55ms, render: 104ms)
```

**Comment by ebbadullah** [comment]
I’m facing the same issue too.
When I log in to my Admin Panel, the data loads quickly at first. But if I stay on the admin panel for a while and then go to another page, the data doesn’t load and gets stuck.

The data only loads after I refresh or hard refresh the page.

This same issue is happening on all my pages where data comes from the  Supabase Db   its  my first Project on supabase .

Can someone help me resolve this issue?

<img width="609" height="604" alt="Image" src="https://github.com/user-attachments/assets/f5228a76-7c90-4d4f-a252-4c81c64e0174" />

**Comment by klembee** [comment]
Same issue
