### ISSUE TITLE
[bug][auth] magiclink auth.admin.generateLink occasionally fails to create a user when it does not exist

### ISSUE THREAD

**Issue by venkr** [supabase/supabase#22521]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We use magiclinks from `auth.admin.generateLink`, then send them to users via our own email provider, then verify the OTPs via `auth.verifyOtp`.

We often find that on the first login with a new email address (ie: a signup), `auth.verifyOtp` fails with a "user not found" error, ie:
`"error":"User not found","level":"info","method":"POST","msg":"403: Email link is invalid or has expired","path":"/verify"`

## To Reproduce

1. Generate a magicLink for a _new_ email address with `auth.admin.generateLink`
```
  const { data, error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'magiclink',
    email: email,
    options: {
      redirectTo: `${origin}/auth/confirm`,
    },
  })
```
2. Verify it via `auth.admin.verifyOtp`
```
  const verifyResponse = await supabaseAdmin.auth.verifyOtp({
    type: 'magiclink',
    token_hash: magicLinkResponse.data.tokenHash,
  })
```

## Expected behavior

Successful sign-in

## Additional context

We were able to successfully workaround by adding a `createUser` call before `generateLink`:
```
  const _ = await supabaseAdmin.auth.admin.createUser({
    email: email,
  })
```

However, the docs imply this should not be necessary.

**Comment by Hallidayo** [comment]
Hi @venkr - Just checking in here, are you still experiencing the above issue?

**Comment by hdoro** [comment]
@venkr this 403 happened to us and we found that some email clients were opening the links before the user clicked it to check for spam, invalidating the token before they could use it.

Our current solution is sending users to an intermediary page, where they then click on a button to finish their registration.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
