### ISSUE TITLE
Supabase main master branch CI/CD Github Actions Workflow failures

### ISSUE THREAD

**Issue by masaok** [supabase/supabase#22543]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

GitHub Actions Workflows are failing at an increasing rate.    5 of 9 success rate now.    9/11 a few days ago.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/supabase/supabase/commits/master/
2. Notice all red X marks.
3. Shouldn't all of these be passing?

## Expected behavior

All Github Action Workflows should pass with every commit on master branch.

## Screenshots

I noticed the CI/CD Github Actions Workflows success rate is getting worse in the past few days:

![image](https://github.com/supabase/supabase/assets/1320083/c185f684-3b24-495a-a54a-d15c34a5894f)

Specifically, I think this failure might be the same problem I'm having running the docs locally:

![image](https://github.com/supabase/supabase/assets/1320083/be802d6c-7b0a-4cff-b7ba-d06722b50a6d)

Specifically, this URL (my localhost dev server, but I'm pointing out the path specifically):

http://localhost:3000/docs/guides/database/overview

Shouldn't the CI/CD Github Workflows all pass all the time on the master branch?

## System information

- OS: Windows WSL Ubuntu
- Browser (if applies): Chrome
- Version of supabase-js: 2.40.0
- Version of Node.js: 19.8.1

## Additional context

Specifically, this commit is causing `dev:docs` to fail due to the `window` reference that Vercel does not like:

https://github.com/supabase/supabase/commit/fef87b78fb7eb054451c59df74a6e735866bad0b#diff-c73a1419c14b736cae981893edbd84c7bc4072e6849d1cd6fb4361e9e03ba09eR83

![image](https://github.com/supabase/supabase/assets/1320083/7c7aa564-4c13-4f02-991a-c24b401247ba)

**Comment by encima** [comment]
`dev:docs` is passing now. `Storybook` is a known issue and is being worked on. 100% clean build is always nice but not always achievable!
Closing for now as the tests are the responsibility of the team to fix but please do comment if the specific issue reoccurs
