### ISSUE TITLE
supabase.auth.admin.generateLink regression

### ISSUE THREAD

**Issue by SebasScript** [supabase/supabase#22562]
- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

there is a related issue but the encountered error seems to be different
[magiclink auth.admin.generateLink occasionally fails to create a user when it does not exist](https://github.com/supabase/supabase/issues/22521)
https://github.com/supabase/supabase/issues/22521

## Describe the bug

```
const inviteOptions = {
    redirectTo: `${deployUrl}/auth/callback?next=onboarding`,
    data: userMetaData,
  };

 const { data, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "invite",
      email,
      options: inviteOptions,
    });
```

 running this in a cloud function used to create an invite link that i could send to a user via email or whats app to create a new user in supabse. After updating my local development environment to the following:

```
        SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.137           │ 15.1.0.137
    supabase/gotrue        │ v2.145.0             │ v2.145.0
    postgrest/postgrest    │ v11.2.2              │ v11.2.2
    supabase/realtime      │ v2.27.5              │ -
    supabase/storage-api   │ v0.48.4              │ v0.48.4
    supabase/edge-runtime  │ v1.41.3              │ -
    supabase/studio        │ 20240326-5e5586d     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

this is not working anymore.  the generateLink call throws this error

```
AuthApiError: User with this email not found
    at we (https://esm.sh/v135/@supabase/auth-js@2.63.0/esnext/auth-js.mjs:2:6550)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async je (https://esm.sh/v135/@supabase/auth-js@2.63.0/esnext/auth-js.mjs:2:7425)
    at async h (https://esm.sh/v135/@supabase/auth-js@2.63.0/esnext/auth-js.mjs:2:7110)
    at async S.generateLink (https://esm.sh/v135/@supabase/auth-js@2.63.0/esnext/auth-js.mjs:2:9732)
    at async file:///home/deno/functions/invite-user/index.ts:56:29
    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:28:7)
    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:28:7)
    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:28:7)
    at async errorHandling (file:///home/deno/functions/_shared/middleware.ts:89:5) {
  __isAuthError: true,
  name: "AuthApiError",
  status: 404,
  code: "user_not_found"
```

The api call should create a new user, but its somehow checking if the user already exists, which it shouldn't (and also didn't do before).
If changing the type to 'magiclink'  the call works and a new user is generated as expected, which should be the same behaviour for 'invite'.
 
## To Reproduce
create a cloud function and use the service key to create the supabase client, than call the create link function

```
export const supabaseAdmin = createClient<Database>(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
  {
    auth: {
      persistSession: false,
    },
  }
);

 const { data, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "invite",
      email,
      options: {
            redirectTo: `${deployUrl}/auth/callback?next=onboarding`,
            data: {firstName: 'example name'}
         },
    });

```

## Expected behavior

a new user is created when calling generateLink as in previous versions of supabase.

## System information

- OS: windows 11, running supabase in local dev mode with docker
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 2.42.0
- Version of Node.js: 18.18.2

**Comment by iamchubko** [comment]
I am experiencing the same problem which started around the same time

**Comment by JasonColeyNZ** [comment]
I am also experiencing this issue, just started trying to use this feature in my app and it does not work. Doesn't work in local or production

**Comment by JasonColeyNZ** [comment]
I hope we get an answer on this soon, I wouldn't imagine it taking much time to analyse?

TBH, I have no idea how this wan't caught with internal testing as it appears its been broken with a few releases?!

**Comment by SebasScript** [comment]
I updated my local environment and the issue has been resolved, so closing this.

latest versions that are working again

 ```
       SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.137           │ 15.1.0.137
    supabase/gotrue        │ v2.148.0             │ v2.148.0
    postgrest/postgrest    │ v11.2.2              │ v11.2.2
    supabase/realtime      │ v2.28.23             │ -
    supabase/storage-api   │ v1.0.10              │ v1.0.10
    supabase/edge-runtime  │ v1.43.2              │ -
    supabase/studio        │ 20240408-6bf3b81     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```
