### ISSUE TITLE
Error when saving auth template with CDN links

### ISSUE THREAD

**Issue by GeneralTyres** [supabase/supabase#2256]
# Bug report

## Describe the bug

When adding the bootstrap CDN style link as provided below in an email template the server experiences an "Internal Server Error" when trying to save the template. When refreshing the page the template is updated though.

## To Reproduce

1. Go to the Authentication Templates page
2. Add the following element to one of the templates:
`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">`
3. Click save
4. There will either be an "internal server error" in the console or/and a notification would alert you that there was an error.

## Expected behavior

I expected the template to save successfully or indicate what the problem in the template was like "you can't add CDN links", "Your template can't be parsed/saved because it contains these letters" or just "invalid template". Something like that.

## Screenshots

![Screenshot from 2021-07-07 12-16-54](https://user-images.githubusercontent.com/12910792/124742776-564f1100-df1d-11eb-91af-88d1ef33e573.png)
![Screenshot from 2021-07-07 12-15-26](https://user-images.githubusercontent.com/12910792/124742810-5e0eb580-df1d-11eb-9de3-cb699dd11e36.png)
![Screenshot from 2021-07-07 12-15-47](https://user-images.githubusercontent.com/12910792/124742821-61a23c80-df1d-11eb-8b2e-9fd9080cb20b.png)
![Screenshot from 2021-07-07 12-16-12](https://user-images.githubusercontent.com/12910792/124742839-66ff8700-df1d-11eb-9777-e11d7a563e3b.png)

## System information

I am using the web interface on Chrome (Version 91.0.4472.114 (Official Build) (64-bit)) on a Linux computer

## Additional context

Don't know what else to add but hope this information will help. I guess the real question can we add CDN links like these in our template to help style the emails?

**Comment by MildTomato** [comment]
Hey @GeneralTyres - sorry for late response.

I just tested this just now and it seems to work now.

Please reopen this issue if your still experiencing the same problem
