### ISSUE TITLE
Supabase recreated my tables with deleted migrations :(

### ISSUE THREAD

**Issue by Tananga** [supabase/supabase#22593]
Hi. I had 3 migration files in my remote db. I deleted all migrations from my remote Supabase instance with SQL query:

`delete from supabase_migrations.schema_migrations;`

![Screenshot 2024-04-09 at 14 53 12](https://github.com/supabase/supabase/assets/44244477/e0a03602-626a-4acb-b50a-ff119551862f)

and now Im pressing "Restart project"

![Screenshot 2024-04-09 at 14 54 17](https://github.com/supabase/supabase/assets/44244477/eb77fb40-78c4-494d-868a-e143c3ff36a2)

And for some reason tables are recreated even if migrations are still empty :( 

![Screenshot 2024-04-09 at 14 58 15](https://github.com/supabase/supabase/assets/44244477/9f26dfca-41c1-4f3d-b72d-6307b34cf54a)

Is it normal? It looks like a bug. Local supabase cant recreate tables without migrations so why remote can?

**Comment by encima** [comment]
This may have happened because the project was restored from a backup but this might be better to open as a Support ticket so you can give the team permission to access your instance and check

**Comment by MeyerOppelt** [comment]
As far as I can tell, this looks like normal behavior.

Deleting the migrations table only deletes the index of the applied migrations on the database, just so the database can ignore your old old migrations. Deleting that table would only change the fact that when you run `supabase migrations up` again, every migration will be pushed, even if it was run in the past. 

Effectively this table functions as a history of migrations you have applied in the past, and by deleting it your database can no longer differentiate whether you have already pushed a migration.

Your other issue is that you are restarting the project. I am unsure of if you thought this would delete migrations or reset the database but the restart would only shut down the containers of postgres, gotrue, storage etc. and turn them back on. The main purpose of this is to try and fix issues in the runtime of the postgres instance.

Now if you are trying to reset the database to its original state, the best way is to use the cli and run `supabase db reset --linked`. This will reset the linked database back to its original state (with some exceptions) and reapply all the migrations in your migrations folder. Fair warning, this will delete all data currently store in your database. This shouldn’t even require a restart of the supabase project and would be available immediately.

If you don’t want your migrations to be reapplied when you run that command, you could try moving the migrations out of the folder, running the command and moving the migrations back. I haven’t tested this but I assume it will work. This would reset the database back to its initial condition without applying your migrations so you have a blank slate to work off of. After that, you can run `supabase migrations up` whenever you want to push the migrations into the database

**Comment by MeyerOppelt** [comment]
> Local supabase cant recreate tables without migrations so why remote can?

@Tananga 
Local supabase can’t recreate tables because it is not a direct clone of the cloud database. The migrations are run to make the local database a similar clone to the production database, so you can test and develop your system and migration locally before pushing it. 

This is why you can run the schema dump, so the first migration to your local database makes it exactly alike the cloud database

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue. Thank you.
