### ISSUE TITLE
Duplicate Table entries only duplicates up to 1000 entries (= Settings: Max Rows)

### ISSUE THREAD

**Issue by oliver3** [supabase/supabase#2259]
# Bug report

## Describe the bug

When I duplicate a table containing more than 1000 rows using the web interface, and I select the Duplicate Table entries option, the resulting table contains exactly 1000 rows

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Tables in the web interface
2. Click context menu for a table with more than 1000 entries
3. Select "Duplicate Table"
4. Check the "Duplicate table entries" option
5. "Save"

## Expected behavior

I expected all the entries to be there in the newly created table.

## Screenshots

I do not want to share my data online, if needed I can share privately. Please contact me at github.

## System information

- OS: mac
- Browser: firefox
- Version of supabase-js: n/a
- Version of Node.js: n/a

## Additional context

In Settings, the Max Rows is also set to 1000, coincidence?

**Comment by oliver3** [comment]
When I set my Max Rows in Settings to 1200, the duplicate table indeed now contains 1200 rows, so that's confirmed

**Comment by kiwicopple** [comment]
Looks like this is now fixed 👍
