### ISSUE TITLE
Cannot update when using python

### ISSUE THREAD

**Issue by AMakarov9** [supabase/supabase#22592]
![image](https://github.com/supabase/supabase/assets/143446995/f81c46c3-cc93-45ca-9d74-680722b77637)
![image](https://github.com/supabase/supabase/assets/143446995/c88e0b16-17c7-479a-b0cf-cf682f7bbd89)

Can't update the name for some reason?

**Comment by IcedTea2K** [comment]
I can't seem to reproduce it. Do you mind providing more context about the code? @AMakarov9 
```python3
res1 = supabase.table("notes").select("*").eq("column_id", "1").execute()
res2 = supabase.table("notes").update({"title": "abc"}).eq("column_id", "1").execute()
print(res1)
print(res2)
```
```
data=[{'column_id': 1, 'title': 'yummy', 'length': 'long'}] count=None
data=[{'column_id': 1, 'title': 'abc', 'length': 'long'}] count=None
```

**Comment by AMakarov9** [comment]
@IcedTea2K 
```python
dat3 = supabase.table('test').select('*').eq('id', '1').execute()
dat4 = supabase.table('test').update({'name': "newname"}).eq('id', '1').execute()

print(dat3)
print(dat4)
```


Still gives: 
{'data': [{'id': 1, 'name': 'test'}], 'status_code': 200}
{'data': {'code': 'PGRST102', 'details': None, 'hint': None, 'message': 'Empty or invalid json'}, 'status_code': 400}


This is the table: 
![image](https://github.com/supabase/supabase/assets/143446995/90d5db1f-4595-4f85-87b1-ffd4265117e7)

**Comment by AMakarov9** [comment]
![image](https://github.com/supabase/supabase/assets/143446995/4116b1e7-a7ae-4a47-b03a-fd8b5ea438ac)

I imported "create_client" from "supabase_py" and not "supabase" 😅. Works as intended after changing.
