### ISSUE TITLE
Firefox extension triggering unhandled client-side exception when inviting new team members when changing role

### ISSUE THREAD

**Issue by Hahlh** [supabase/supabase#22607]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the organization settings a client-side exception is currently triggered in Supabase production for the selection of the dropdown for the member role.

## Reproduce

While using Bitwarden and potentially similar extensions:

1. https://supabase.com/dashboard/org/[orgId]/team (add orgId)
2. Click invite
3. Select role dropdown
4. `Application error: a client-side exception has occurred (see the browser console for more information).`

In the browser console, potentially related: 

```js
Error: Permission denied to access property "getAttribute"
```

I think this might be triggered by the Bitwarden extension trying to work with the field.

Still, this might hint at the error handling needing to be improved here and / or autofilling being prevented here? 
I suppose that Bitwarden might not be the only extension triggering this unhandled error, since the input type is `email`.  

## Screenshots
[Screencast from 04-10-2024 01:14:06 AM.webm](https://github.com/supabase/supabase/assets/45669613/ee37eeaf-94be-471f-affb-e89c2e95d4fa)

## System information

- OS: Linux, Ubuntu 22.04
- Browser: Firefox

**Comment by encima** [comment]
I cannot reproduce this on Linux or Mac using Firefox Developer (125).

Potentially the error handling could be improved but this could also be a Bitwarden issue. For now, you could remove the supabase dashboard from the autofill settings in Bitwarden.

Leaving open in case others report it or if we are able to reproduce

**Comment by Hahlh** [comment]
Yes, agreed.

Precise version of Bitwarden:
**Version**: 2024.2.1
**Last Updated**: April 6, 2024

**Precise version of Firefox**:
123.0 (64-bit)

This issue should likely become easier to pinpoint & reproduce if other users report it as well including their system information.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue, thank you.
