### ISSUE TITLE
Studio Messed Up, missing Toggle Feature Preview Button

### ISSUE THREAD

**Issue by tecoad** [supabase/supabase#22623]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am running the Studio v 20240326-5e5586d on my localhost, And i can actually Toggle Feature Preview since the button that used to be on the bottom side is missing. It existed in 20240301-0942bfe, however its missing in 20240326-5e5586d.

## Expected behavior
I should be able to toggle feature preview.

![Screen Shot 2024-04-10 at 09 10 25](https://github.com/supabase/supabase/assets/2627749/e0be9b54-4d99-4bc1-a015-58d1995a46a8)

**Comment by encima** [comment]
Can verify the button is missing from the 20240326 image. @supabase/frontend will be the ones to know here!

**Comment by saltcod** [comment]
Hey there!

Are you still able to toggle it from the modal here?

![screenshot-2024-04-22-at-12 29 53](https://github.com/supabase/supabase/assets/105593/45bf49a1-4c70-472f-9be0-72f0c661cc8f)

**Comment by tecoad** [comment]
I am not sure, but I think not. But couldn't tell because I have to downgrade the cli to be able to user a older version of studio. I still have no upgraded because of this missing ui.

**Comment by Hallidayo** [comment]
Just ran the studio on `20240422-5cf8f30` and the features section does not appear on the menu.

@saltcod - Should the local version have the features preview?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
