### ISSUE TITLE
Branch setup failed error - PostGIS

### ISSUE THREAD

**Issue by Pierre-Saigot** [supabase/supabase#22646]
### Discussed in https://github.com/orgs/supabase/discussions/22645

<div type='discussions-op-text'>

<sup>Originally posted by **Pierre-Saigot** April 11, 2024</sup>
I have an issue when setting up a new branch on my Supabase project. This error is due to 'PostGIS' and 'pgaudit.' The problem is that pgaudit is not enabled in my extensions. Do you have any solutions? I'll attach a screenshot of my error.

![ScreenShot](https://github.com/supabase/supabase/assets/10871790/7b6a07fa-9dbf-4dcd-bc18-7d94b73df457)

`ERROR: PostGIS installation stopped: pgaudit.log is set to 'ddl'. Set pgaudit.log to 'none' before installing PostGIS. You may re-enable pgaudit after installation is complete. (SQLSTATE P0001)
At statement 17: CREATE EXTENSION IF NOT EXISTS "postgis" WITH SCHEMA "extensions"`
</div>

**Comment by encima** [comment]
Thanks for opening, just to confirm have you tried dropping pgaudit in case it was created elsewhere? 

`DROP EXTENSION IF EXISTS pgaudit`;

It could also be that, while it is not enabled, the setting is still set. In that case you can modify the pgaudit setting beforehand.

If that is the case, then you can change the [log setting](https://github.com/pgaudit/pgaudit/blob/master/README.md#settings) with `set pgaudit.log='none'`

**Comment by Pierre-Saigot** [comment]
> Thanks for opening, just to confirm have you tried dropping pgaudit in case it was created elsewhere?
> 
> `DROP EXTENSION IF EXISTS pgaudit`;
> 
> It could also be that, while it is not enabled, the setting is still set. In that case you can modify the pgaudit setting beforehand.
> 
> If that is the case, then you can change the [log setting](https://github.com/pgaudit/pgaudit/blob/master/README.md#settings) with `set pgaudit.log='none'`



I don't have the pgaudit extension on my databases. Just in case, I've executed the DROP EXTENSION command and the 'set pgaudit.log='none'' command, but it didn't work.

I specify that this is only on my 'preview/dev' branch, just after generating it, and that my main PostGIS branch is activated without any problem. And I've never activated pgaudit, it is indeed deactivated...

**Comment by sweatybridge** [comment]
I ran into similar problem before and resolved it by setting `pgaudit.log = 'none'` in the migration file before creating postgis extension. For eg.

```
SET pgaudit.log = 'none';

CREATE EXTENSION IF NOT EXISTS "postgis" WITH SCHEMA "extensions";
```

Here's the full working migration file: https://github.com/sweatybridge/cli-demo/blob/main/supabase/migrations/20230803025559_remote_commit.sql#L12

**Comment by Pierre-Saigot** [comment]
Indeed, it works! Thanks for the tip, it saves me!
