### ISSUE TITLE
UI doesn't update when you set google credentials for Google using local hosted Docker Supabase

### ISSUE THREAD

**Issue by brunolm** [supabase/supabase#22651]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Cannot enable Google login

This does not work: https://github.com/orgs/supabase/discussions/11855

## To Reproduce

1. add this config under supabase-auth in docker-compose.yml
```
      # Google Auth Google Login
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${ENABLE_GOOGLE_SIGNUP}
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:8000/auth/v1/callback
```
2. docker compose up
3. check dashboard, google is disabled

## Expected behavior

Google login to be enable with the config for client id and secret showing

## Screenshots

![image](https://github.com/supabase/supabase/assets/706078/2c2c1647-7106-44f4-87ea-f41c2dbf7f34)

![image](https://github.com/supabase/supabase/assets/706078/0b8dbfb5-bfc4-400e-93d3-cc6e67f1443e)

## System information

- OS: Windows 11 Pro
- Browser (if applies): Microsoft Edge
- Version of supabase-js: master branch as of 2024-04-11T17:23:00.000Z
- Version of Node.js: N/A

## Additional context

Providers page seems to be only accessible if you manually enter the URL: http://localhost:8000/project/default/auth/providers

**Comment by GaryAustin1** [comment]
The UI does not handle the auth settings in local hosted Docker.   The config files are the way. That is why you had to enter the URL, which does not do anything.
