### ISSUE TITLE
Download database backup is broken

### ISSUE THREAD

**Issue by moracabanas** [supabase/supabase#2266]
# Bug report

## Describe the bug
When you try to download a database backup it shows this error 

![image](https://user-images.githubusercontent.com/4382333/124818025-d2237a80-df6a-11eb-90b8-52f65dd0aa8c.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 

![image](https://user-images.githubusercontent.com/4382333/124818057-d8b1f200-df6a-11eb-8e90-e9ad74f8ce2e.png)

2. Click on any of the backups `Download` button

![image](https://user-images.githubusercontent.com/4382333/124818307-29294f80-df6b-11eb-94f0-2c7141093455.png)

## Expected behavior

You should be able to download the database backup file.

## System information

- OS: Windows
- Browser: Chrome, Edge (chromium)
- Version of supabase-js: Supabase Web

**Comment by dragarcia** [comment]
Hi @moracabanas 👋 

Thanks for pointing this out! We're on it with the fix. Will keep you updated once the fix is out!

**Comment by dragarcia** [comment]
Hi @moracabanas 👋 

The issue has been resolved and the changes have been deployed. Would you mind checking if everything is working once more on your side?

**Comment by moracabanas** [comment]
Well while backups should be working after the fix, I didn't expect to find this 😂😂
![image](https://user-images.githubusercontent.com/4382333/125119492-746d6a80-e0f1-11eb-8c43-a131565bb4a7.png)

I was using a free account so maybe there was a bug showing this secction for free users but disabled on the server. 

Thanks you for the fast fixing and the feedback!

**Comment by JamesGarbaczewski** [comment]
Came across the same thing.  I am OK with backups being a paid option but is there any easy way to download a copy?  Or even a 1 day backup for free users?
