### ISSUE TITLE
Studio dashboard not showing settings and user

### ISSUE THREAD

**Issue by hcdiekmann** [supabase/supabase#22685]
# Bug report
Docker image for the studio is unhealthy and the Studio dashboard does not load everything. Even though I set the organisation name, it shows default on the dashboard.

## To Reproduce
Follow the docker self-hosting guide from the official docs.

## Expected behavior

Studio image is healthy and shows all features in the dashboard at localhost:8000

## Screenshots

![image](https://github.com/supabase/supabase/assets/13176191/44cbc656-7d28-4f44-8b55-07413255ced6)

## System information

- OS: Windows
- Browser: Brave
- Version of Node.js: 20.11.1

**Comment by okxiaoliang4** [comment]
studio settings panel only for the platform mode

https://github.com/supabase/supabase/blob/6acb28ed56a1f0258cf6481c2acc772476804dcc/apps/studio/components/layouts/ProjectLayout/NavigationBar/NavigationBar.utils.tsx#L131-L144

**Comment by encima** [comment]
hey there, as @okxiaoliang4 said, the self-hosted version provides a single project to work with so the behaviour is expected there. #22867 is an existing issue for the healthy check so I will close this one
