### ISSUE TITLE
UI breaks when impersonating a user in Table Editor

### ISSUE THREAD

**Issue by rkhalil38** [supabase/supabase#22701]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the Table Editor, the 'Impersonate a User' section has overlapping UI components. These UI components display the available users to impersonate. Upon selecting a user, the 'role' UI component also exhibits overlap.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to table editor for a project
2. Click on a table
3. Click in top bar to change role
4. Click on authenticated role
5. See the overlapping UI components under 'Impersonate a User'
6. Click 'Impersonate' on a user
7. See UI overlapping in 'role' dropdown

## Expected behavior

The users should not overlap and list clearly. The role dropdown should display the user clearly and not overlap.

## Screenshots

<img width="604" alt="Screenshot 2024-04-13 at 3 35 27 PM" src="https://github.com/supabase/supabase/assets/148097264/3bf7f52d-4fca-491b-b9fc-e0f6e158c4fd">
<img width="626" alt="Screenshot 2024-04-13 at 3 37 26 PM" src="https://github.com/supabase/supabase/assets/148097264/aed4af74-3af6-40e1-874d-09cf6ab060f0">

## System information

- OS: macOS
- Firefox Developer Edition

**Comment by FatumaA** [comment]
I can't reproduce this, perhaps only happens when the user name is long?

I'd like to continue looking into it and send a fix

**Comment by rkhalil38** [comment]
> I can't reproduce this, perhaps only happens when the user name is long?
> 
> I'd like to continue looking into it and send a fix

I looked into it, and it seems to happen when a user uses a third-party provider to login, and in my case, it is mostly Google logins. For some reason, the profile image is not loading properly, and the alt text is being displayed instead, causing the overlay. 

**UserImpersonationSelector.tsx**

<img width="901" alt="Screenshot 2024-04-15 at 11 36 13 AM" src="https://github.com/supabase/supabase/assets/148097264/1635e10e-daad-42cf-9372-d60303c2ecaf">
