### ISSUE TITLE
ArgumentError on Sign Up

### ISSUE THREAD

**Issue by ShihanLi** [supabase/supabase#22720]
# Improve documentation

The auth documentation specifies this is the way to create a new user: 

final AuthResponse res = await supabase.auth.signUp(
  email: 'example@email.com',
  password: 'example-password',
);

https://supabase.com/docs/reference/dart/auth-signup?example=sign-up

When I used this code as is, I encountered this exception: ArgumentError (Invalid argument(s): No host specified in URI /auth/v1/signup?) 

There is very little doc that reveals what the root cause could be. Would appreciate any help on this, with documentation including the commonly encountered exceptions when using the client and how to handle it.

**Comment by encima** [comment]
Have you created the client? This error comes because the SDK does not where to make the API call (`No host specified in URI`) so it cannot find your Project ref.
