### ISSUE TITLE
Error in third-party login for notion

### ISSUE THREAD

**Issue by LucaRao** [supabase/supabase#22726]
Error in third-party login for notion:
“error=server_error&error_code=500&error_description=Error+getting+user+email+from+external+provider#error=server_error&error_code=500&error_description=Error+getting+user+email+from+external+provider”

What's the reason? Have you encountered it?

**Comment by encima** [comment]
As @FatumaA said, more info will be needed please @LucaRao  (or if you have solved it, let us know!).

Can you confirm that your Notion integration has been configured to "Read user information including email addresses" under `Capabilities`?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
