### ISSUE TITLE
Unclear Sentence in Architecture Document

### ISSUE THREAD

**Issue by JoeyH1** [supabase/supabase#22749]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/architecture#everything-is-portable

## Describe the problem

If a new standard emerges which competes with a "Supabase" approach, we will deprecate the approach in favor of the standard. **This forces us compete on experience.** We aim to be the best Postgres hosting service.

The bold section reads strange. I think it can be improved below.

## Describe the improvement

Change the bold section above to this:

This forces us to compete on user experience.

## Additional context

I hope you don't find this knit-picky, I really enjoyed this documentation and wanted to help improve it. I think documentation is something that is really undervalued and I am impressed at the context and content of the writing.

**Comment by charislam** [comment]
Yes, I definitely agree that your change is correct! Thanks for pointing it out, and feel free to open a PR if you'd like 😄
