### ISSUE TITLE
magic link doesn't work 

### ISSUE THREAD

**Issue by EmePin** [supabase/supabase#22765]
I was following this tutorial but the magic link does not work on the web or in the apk, the one on guthub does work.
[tutorial ](https://www.youtube.com/watch?v=8TZ6O1C8ujE&list=PL5S4mPUpp4OsrbRTx21k34aACOgpqQGlx&index=3&ab_channel=Supabase)

on web says this
Failed to load resource: the server responded with a status of 429 ()
fetch.ts:96  Uncaught (in promise) AuthApiError: For security purposes, you can only request this once every 60 seconds
    at handleError (fetch.ts:96:1)
    at async _handleRequest (fetch.ts:192:1)
    at async _request (fetch.ts:151:1)
    at async SupabaseAuthClient.signInWithOtp (GoTrueClient.ts:692:1)

and on android apk says nothing

**Comment by Sof2222** [comment]
Not supabase staff here but the magic links can be difficult to work with.
1) The link has to be sent in a way it won't prelink in the email client
2) The link has to be opened in the same browser as it was requested from

If those two conditions are not met, magic links won't work. I am not sure what your flow is here, but would need more info to see whether or not they 'work' or not.
It is easier (I found) to request the OTP as many will have an email client which scans for viruses (which will invalidate the link as it can only be used once) and many eg. use emails on their phones as opposed to on their computer (and want to log into the comp). (But as I said, I don't know what your flow is or if these two issues are even applicable here)
