### ISSUE TITLE
Data not loading for some tables

### ISSUE THREAD

**Issue by pygma-dev** [supabase/supabase#2277]
# Bug report

## Describe the bug

Data is loading only for some tables on the Supabase app, while for others an error is thrown with the following message: 

```
{
  msg: "operation is manually canceled"
  type: "cancelation"
}
```
## To Reproduce

1. Logged in
2. Clicked on one table, data loads
3. Clicked on another table, data doesn't load

## Expected behavior

Data loads for every table.

## System information

- macOS
- Brave, but same problem on Safari and Firefox

## Additional context

This error appeared about a week ago I think, no problems prior to that.

**Comment by kiwicopple** [comment]
closing this since it's quite stale. If there are any steps to replicate I'll be happy to reopen and investigate
