### ISSUE TITLE
locally deployed supabase studio unable to load tables

### ISSUE THREAD

**Issue by x-tropy** [supabase/supabase#22770]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Database is running for sure, I can query data with `psql` and connection string. This is a bug specific to supabase studio running at `http://localhost:8000/` (if you keep the default port).

## To Reproduce

Not sure how to reproduce.

## Expected behavior

The studio should load schemas and tables.

## Screenshots

We can see some network errors here in the screenshot, and it kept spinning in the table sections:

<img width="1277" alt="image" src="https://github.com/supabase/supabase/assets/5955526/7ef1360d-8327-475d-a2e5-587bc428eeb5">

## System information

- macOS
- vivaldi
- Version of supabase-js: [e.g. 6.0.2]
- node: 20

**Comment by encima** [comment]
Thanks for opening!

Can you run a healthcheck on the containers? It looks like the DB and Studio is starting but maybe pg-meta is not healthy?

**Comment by x-tropy** [comment]
After some investigation, I confirm that this is caused by inconsistency of database. New schema changes should be pushed to the containerized db to resolve this issue. Or wipe out the container and run a new instance.

**Comment by x-tropy** [comment]
> Thanks for opening!
> 
> Can you run a healthcheck on the containers? It looks like the DB and Studio is starting but maybe pg-meta is not healthy?

Just want to add: nearly all functionalities (which means other tabs and urls) with the studio is not functional under this state.
