### ISSUE TITLE
Update the links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by daklay** [supabase/supabase#22799]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md

## Describe the problem

The 'existing issues' link currently redirects users to the repository homepage instead of the dedicated issues page. Likewise, the 'good first issue' link redirects to the pull requests page rather than the issues page. These redirects may lead to confusion and hinder contributors' ability to find and address existing issues or beginner-friendly tasks effectively.

## Describe the improvement

The updated links should be:
- 'existing issues': ["https://github.com/supabase/supabase/issues"](https://github.com/supabase/supabase/issues)
- 'good first issue': ["https://github.com/supabase/supabase/labels/good%20first%20issue"](https://github.com/supabase/supabase/labels/good%20first%20issue)

**Comment by fahadshahbaz** [comment]
Can you assign it to me?

**Comment by fahadshahbaz** [comment]
I've submitted PR #22805 for issue #22799, fixing links in CONTRIBUTING.md. Your feedback is welcome.
