### ISSUE TITLE
Add phone authentication

### ISSUE THREAD

**Issue by sils** [supabase/supabase#2280]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to let my users login with just their phone number.

## Describe the solution you'd like

Add phone authentication as an auth provider :)

## Describe alternatives you've considered

Uhm... firebase?

**Comment by kangmingtay** [comment]
Hey @sils, great idea! We actually have a PR for it already. You can check it out [here](https://github.com/supabase/gotrue/pull/115) :)
