### ISSUE TITLE
Incorrect sql command for FTS

### ISSUE THREAD

**Issue by ronanfaheydev** [supabase/supabase#22868]
# Improve documentation

## Link 
[link](https://supabase.com/docs/guides/database/full-text-search?queryGroups=language&language=sql#extending-functionality-with-rpc)

## Describe the problem

SQL should read `returns setof` instead of `return setof`

## Describe the improvement

SQL should read `returns setof` instead of `return setof`

**Comment by simonha9** [comment]
Hi! I would love to help out with this ticket -- I have the changes [here](https://github.com/supabase/supabase/pull/22883): 

Please assign back to me if needed + review if anybody has a second :)

**Comment by nathandcarter21** [comment]
Looks like I beat you to it by a few minutes haha.
