### ISSUE TITLE
DEVELOPERS.md versions outdated

### ISSUE THREAD

**Issue by Hasse331** [supabase/supabase#22873]
# Improve documentation

## Problem

This documentation section in DEVELOPERS.md seems to be outdated:

### Install dependencies

You will need to install and configure the following dependencies on your machine to build [Supabase](https://supabase.com):

- [Git](http://git-scm.com/)
- [Node.js v18.x (LTS)](http://nodejs.org)
- [npm](https://www.npmjs.com/) version 9.x.x
- [Docker](https://docs.docker.com/get-docker/) (to run studio locally)

I changed the versions with nvm to mach the version in documentation and I got this:

```
npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: supabase@0.0.0
npm ERR! notsup Not compatible with your version of node/npm: supabase@0.0.0
npm ERR! notsup Required: {"npm":">=9.0.0","node":">=20.0.0"}
npm ERR! notsup Actual:   {"npm":"9.9.3","node":"v18.20.2"}
```

**Comment by ruru-m07** [comment]
@Hasse331 this change is ok?

---

- [Git](http://git-scm.com/)
- [Node.js v20.x (LTS)](http://nodejs.org/)
- [npm](https://www.npmjs.com/) version 10.x.x
- [Docker](https://docs.docker.com/get-docker/) (to run studio locally)

**Comment by Hasse331** [comment]
> @Hasse331 this change is ok?
> 
> * [Git](http://git-scm.com/)
> * [Node.js v20.x (LTS)](http://nodejs.org/)
> * [npm](https://www.npmjs.com/) version 10.x.x
> * [Docker](https://docs.docker.com/get-docker/) (to run studio locally)

npm version of 9 or higher should be okay based on my cli:
npm ERR! notsup Required: {"npm":">=9.0.0","node":">=20.0.0"}

I have this now in my pull request:

- [Git](http://git-scm.com/)
- [Node.js v20.x (LTS)](http://nodejs.org) or higher
- [npm](https://www.npmjs.com/) version 9.x.x or higher
- [Docker](https://docs.docker.com/get-docker/) (to run studio locally)

**Comment by ruru-m07** [comment]
@Hasse331 got it 👍
