### ISSUE TITLE
Failed to enable index_advisor: failed to create pg.extensions: permission denied to create extension "index_advisor"

### ISSUE THREAD

**Issue by thedevdavid** [supabase/supabase#22934]
Trying to enable index_advisor extension in dashboard but always getting this error: `Failed to enable index_advisor: failed to create pg.extensions: permission denied to create extension "index_advisor"`

**Comment by encima** [comment]
Thanks for opening this! Can you please open a support ticket so that a member of the team can confirm the permissions on your project.

**Comment by NiklasPor** [comment]
I'm running into the exact same issue with a local CLI project (1.167.4). @thedevdavid did you get any insights on fixing it?

**Comment by thedevdavid** [comment]
@NiklasPor I think I just installed the extensions from SQL editor.

```
create extension if not exists hypopg;
create extension index_advisor;
```

**Comment by NiklasPor** [comment]
Ah well, I'm getting the same error from the SQL editor (for the index-advisor) 😅

**Comment by seivad** [comment]
I am having the same problem, requires superuser to install index_advisor of a fresh setup of supabase cli and docker containers. What is the work around guys as this ticket has been open for a while now
