### ISSUE TITLE
Storage does not support upload file with Chinese filename.

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#22974]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I try to upload a file with chinese filename, e.g 填报指南.pdf, it complains `Failed to upload 填报指南.pdf: Invalid key: 填报指南.pdf`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Storage'
2. Click on 'Upload file'
3. Upload a file with chinese filename

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
This is a documented issue/enhancement request on storage already.
https://github.com/supabase/storage/issues/133
Going to close in favor of the one already in storage.  Feel free to add comments there.

**Comment by stefan-girlich** [comment]
@GaryAustin1 Sorry for tagging you here; couldn't tag you in https://github.com/supabase/storage/issues/133 
Would you be able to share (in #133) if and when this is going to be resolved? My application requires file downloads with the original file names. Right now, the only solution seems to be to store the original file names separately and route all downloads through a middleware.

**Comment by GaryAustin1** [comment]
Sorry I don't have access to Supabase plans other than looking in repositories like you.

**Comment by stefan-girlich** [comment]
Sorry - I wrongly assumed you were in touch with the core maintainers due to your numerous contributions. 
Thanks for your contributions and support; your comments have helped me out of confusing situations more than once :)
