### ISSUE TITLE
Some studio tables UI breaks when resizing browser window

### ISSUE THREAD

**Issue by PauAbellaMolina** [supabase/supabase#22979]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Tables on the studio /database/tables, /database/triggers and /database/functions pages (maybe other places too) break when making the page narrower. Looks like columns disappear.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the studio of a project, Database page.
2. Click on Tables/Triggers/Functions pages.
3. Resize your to see the tables break at certain points.

## Expected behavior

Table columns shouldn't disappear and the whole table should become horizontally scrollable, just like the tables on Authentication > Users for example.

## Screenshots

![Screenshot 2024-04-20 at 12 54 22](https://github.com/supabase/supabase/assets/62839680/d495212d-9374-43df-851c-25dd5c2833ce)
![Screenshot 2024-04-20 at 12 54 42](https://github.com/supabase/supabase/assets/62839680/3225a971-28e2-485e-9b26-7527d148c52d)
![Screenshot 2024-04-20 at 12 55 01](https://github.com/supabase/supabase/assets/62839680/53461bf0-ce22-4273-b170-eb2b65eb3191)

## System information

- OS: macOS
- Browser (if applies) Arc Browser

## Additional context

Supabase studio is obiously not intended to be used on small screens like mobile, but this happens when splitting screen on any standard monitor or laptop.

Thanks for the work, Supabase is awesome!

**Comment by liambirkin** [comment]
I'll take a look at this one
