### ISSUE TITLE
Add a section for Authorization and Policies

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#230]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

We've had a number of questions about using Policies. We should start a section in our Docs which give examples of how to use Policies.

## Details

Some examples:

```sql
create policy "Individuals can view their own posts" 
  on posts for select using ( auth.uid() = user_id ); 
```

Example of how to do a "related" table

```sql
create policy "Individuals can view post if the post is in a team they belong to" 
  on posts for select using ( 
    team_id in ( select team_id from teams where user_id = auth.uid() ) 
  ); 
```

We can just start this page, then add more as we go.

**Comment by duncanhealy** [comment]
. (full stop) in the policy name is disallowed by the web editor (but allowed when you create them via the run tab)

**Comment by kiwicopple** [comment]
Interesting, thanks for catching this @duncanhealy - I will modify the Policy Editor to allow for full stops and other alpha-numeric characters
