### ISSUE TITLE
[request]Self-Host

### ISSUE THREAD

**Issue by rafalohaki** [supabase/supabase#2306]
Self-Host option would be great.

**Comment by rafalohaki** [comment]
i meant script created for automatic install and ready to be functional

**Comment by ChronSyn** [comment]
Right now, there are resources to explain how to self-host: https://supabase.io/docs/guides/self-hosting

This doesn't include the Supabase dashboard as the one they currently have is linked heavily with some of the config for their infrastructure.

The team have also mentioned that they're looking at making the dashboard open source, and creating a standalone docker-compose that you can pull and it'll handle the setup for you. As far as I know, there's no timescales for this yet, but the team are definitely working on making it a reality.

**Comment by kiwicopple** [comment]
Thanks for jumping in here @ChronSyn 

@rafalohaki - let us know if there is anything you require beyond the guides that @ChronSyn has linked to.

We're working on the self-hosted Dashboard here: https://github.com/supabase/supabase/pull/2281
