### ISSUE TITLE
Run a query then got "function "handle_new_user" already exists with same argument types"

### ISSUE THREAD

**Issue by leadream** [supabase/supabase#2310]
# Bug report
Run a query then got an error

## Describe the bug
I wrote some query code in SQL editor then I ran it, it return success. But I got an error in test website so I changed something in SQL editor and ran again. Then I got this error.

![image](https://user-images.githubusercontent.com/12868055/125157960-7b9f8180-e1a0-11eb-9f93-133ecb98cdb7.png)

It seems like this trigger has already in `auth.users` but I can't find them. How can I rerun this SQL code?

**Comment by leadream** [comment]
Oh I resolved it. Just create another query then write code below to delete the function.

```SQL
drop function public.handle_new_user()
```

I think it would be better if we can see this functions in the dashboard.

**Comment by ChronSyn** [comment]
> Oh I resolved it. Just create another query then write code below to delete the function.
> 
> ```sql
> drop function public.handle_new_user()
> ```
> 
> I think it would be better if we can see this functions in the dashboard.

I'd recommend using a tool like pgAdmin for more advanced postgres features.

The SQL editor in the dashboard is fantastic, but pgAdmin sometimes provides hints at how to fix issues (this is one such scenario where it does that).

**Comment by leadream** [comment]
@ChronSyn Thanks, will try it.

**Comment by dovecancode** [comment]
> ```sql
> drop function public.handle_new_user()
> ```

I tried this but mine says
![image](https://github.com/supabase/supabase/assets/142895411/f2a43ec4-c589-4bfd-97eb-3d4fe6d08ba0)

my issue is I wont be able to delete the ``on_auth_user_created``  trigger
do you have any idea how I'm  going to get rid of that trigger?

**Comment by Purevdorj-Batgerel** [comment]
@dovecancode as the error message says `on_auth_user_created` trigger depends on `public.handle_new_user` function.

add `CASCADE` parameter after the query

```SQL
DROP FUNCTION public.handle_new_user() CASCADE
```
