### ISSUE TITLE
Supabase permission denied for TCE using pgsodium

### ISSUE THREAD

**Issue by ani-sha** [supabase/supabase#23131]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am implementing TCE on a table to encrypt some API keys but I am having issues while inserting any record into the table.
```
ERROR:  42501: permission denied for table key
CONTEXT:  SQL statement "SELECT *                     FROM pgsodium.decrypted_key v
  WHERE id = key_uuid AND key_type = 'aead-det'"
PL/pgSQL function pgsodium.crypto_aead_det_encrypt(bytea,bytea,uuid,bytea) line 5 at SQL statement
PL/pgSQL function api_encrypt_secret_api_key() line 3 at assignment
```
I tried following some discussions around permission issues https://github.com/supabase/supabase/issues/12952 to grant access to these functions.
```
GRANT EXECUTE ON FUNCTION pgsodium.crypto_aead_det_encrypt (bytea, bytea, uuid, bytea) TO authenticated;
GRANT EXECUTE ON FUNCTION pgsodium.crypto_aead_det_decrypt (bytea, bytea, uuid, bytea) TO authenticated;
```
This didn't work.

Then I tried following the simple TCE example to apply encryption on a table. But there are some permission issues which didn't resolve even after giving `GRANT`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable pgsodium extension in supabase
2. select * from pgsodium.create_key();
3. select * from pgsodium.crypto_aead_det_encrypt (
	'this is the message',  -- a message to encrypt
	'this is associated data',  -- some authenticated associated data
	'<generated-key-id>'::uuid -- key ID
); 

## Expected behavior

It should produce encrypted ciphertext using the aead-det algorithm.

## Screenshots

<img width="932" alt="Screenshot 2024-04-22 at 11 57 04 AM" src="https://github.com/supabase/supabase/assets/32862813/8bfdf39d-ca16-4c89-9f3b-3b3ef0a9590b">

## System information

- OS: macOs
- Browser (if applies): Chrome

**Comment by encima** [comment]
Hello @ani-sha 
Thanks for opening! I am not able to reproduce on Supabase Cloud (version 15.1.1.37)

Can you confirm the version you are running, please? It could be a permissions issue from a previous version and might need to be updated. If it is the latest version, then please open a Support Ticket so an engineer can check the issue.

**Comment by ani-sha** [comment]
Hi @encima, I recently upgraded to `15.1.1.41` last week because I was unable to enable the `pgsodium` on the earlier version. But that doesn't help either. I am having the same error.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
