### ISSUE TITLE
The project doesnt exist

### ISSUE THREAD

**Issue by abdulrahmanalaa123** [supabase/supabase#23163]
# Bug report
Accessing anything but the API DOCS results in opting out a "This project doesnt exist error" :

I've created a project using the central EU frankfurt eu-central-1

Postgress version : 15.1.1.19
postgrest version: 12.0.2
Gotrue version: 2.148.0

opening sql Viewer, the tables itself,  schema visualizer, my current project functions, or even the realtime storage anything database related i presume but the auth, storage, and the API Docs all works fine(the database with all its functions are inside the api docs) results in an error "this project doesnt exist" now I've left this project inactive for two weeks with all rows being public and minimizing row level security thats all i can think that may cause an issue I've also i created a new project connecting to the ireland server which results in the same error.

![image](https://github.com/supabase/supabase/assets/29045466/33252cb4-3e08-450e-9d2b-0998e6733bf3)

![image](https://github.com/supabase/supabase/assets/29045466/32e61dd9-c4ba-4b03-8aa5-07c55071658a)

Note:
everytime i try to open the tables tab or anything the usage on my database increase by 20 or so although I didnt use it within my project althought it's working for queries but i cant view to edit my table and my auth usage is increasing as well although im not using it and I havent made any of the keys public so im sure its not my fault of exposing keys and the usage is so small yet exists at random.

**Comment by encima** [comment]
Please open a Support ticket for this, it is hard to help here without potentially sharing private information. https://supabase.help/
