### ISSUE TITLE
Unable to add duplicate values to a previously unique constrained column

### ISSUE THREAD

**Issue by vidy01** [supabase/supabase#23179]
# Bug report

- [y ] I confirm this is a bug with Supabase, not with my own application. 
- [ y] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
On a table i had a unique key constraint. then i removed it. yet i am unable to add duplicate values to that column. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Remove unique key contraint from a column that was previously unique key constrained
2. Try to insert. row with a duplicate value for a column

## Expected behavior
Once i remove the unique key constraint, I should be able to add duplicate values to that [column.]
![Screenshot 2024-04-23 at 6 26 07 AM](https://github.com/supabase/supabase/assets/156584074/4219485f-5afc-4e41-b8d3-56e5be29f0ed)
![Screenshot 2024-04-23 at 6 26 29 AM](https://github.com/supabase/supabase/assets/156584074/3b5e8bca-cbe5-452a-8110-7d165b54d44a)

## System information

- OS: [e.g. macOS, Windows] 
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by simonha9** [comment]
I was unable to repro this on chrome/windows, had the table editor in another tab, my steps:

1. create table with unique column col1
2. insert row with col1 value 'test'
3. insert duplicate row - fails as col1 has unique constraint
4. remove unique constraint on col1 and click save
5. refresh table editor window
6. insert row with col1 value 'test'
7. ok

Even no refresh seems to be ok, can someone confirm?

**Comment by encima** [comment]
Also cannot reproduce on Mac (Arc) / Linux (Firefox)

Can you record this occurring so that we can see it in action @vidy01 ?

**Comment by vidy01** [comment]
I have no idea what is going on. After a restart it works.  I am on mac. on the Arc browser. Not sure what an OS has to do with a web application. You can see in my screenshots above that it wasn't letting me add.

This evening after a few hours when i went back, the column's "unique" property was checked. It wasn't checked in the morning. I double verified.

but oh well. This ticket can be closed.
