### ISSUE TITLE
Update Expo SDK Version and Fix Dependencies

### ISSUE THREAD

**Issue by katayama8000** [supabase/supabase#23187]
# Chore

## Describe the chore

The chore is to upgrade the Expo SDK version from 46 to 50.

## Additional context

Currently, the project relies on Expo SDK version 46. The goal is to upgrade to version 50 to leverage new features, improvements, and bug fixes provided by Expo.

**Comment by encima** [comment]
HI @katayama8000,

Thanks for opening the PR! No need to open an issue for a new PR unless there is an existing one :)
