### ISSUE TITLE
Loss of data configuration when updating branches on Supabase

### ISSUE THREAD

**Issue by Pierre-Saigot** [supabase/supabase#23211]
# Bug report

## Describe the bug

When updating branches **(only in dev branch)** on Supabase, configured data such as connection providers and the site URL lose their configuration and reset each time. Visually, the data appears to be present in Supabase, but their configuration is lost in the branch update process. For example, Google connection settings require deactivation and reactivation with each branch update to take effect. Additionally, the site URL reverts to "localhost" after each branch update, despite visually appearing correct in the interface.

## Environnement
- Supabase Hosted 
- Cloud provider : AWS | EU-CENTRAL-1
- GoTrue Version : 2.148.0
- PostgREST version : 12.0.2
- Postgres version : 15.1.1.41

## Ask 
We agree that my local directory 'supabse' containing 'config.yaml' is not used in the hosted version and is not used to configure my branches such as 'dev,' correct? Because I haven't added it to my gitignore. If Supabase uses this configuration file to set the parameters of my branch, that might be the issue. 
I haven't configured my information such as site_url or provider_google in this file at all.

**Comment by encima** [comment]
Hello @Pierre-Saigot ,
The branching [discussion](https://github.com/orgs/supabase/discussions/18937#discussioncomment-8549010) is the best place for the `ask` question (correct, the config file is not used)

As for the issue, thanks for opening! To summarise:
when updating a branch, the settings may show correctly in the dashboard but they are reset

is that right?

**Comment by Pierre-Saigot** [comment]
> Hello @Pierre-Saigot , The branching [discussion](https://github.com/orgs/supabase/discussions/18937#discussioncomment-8549010) is the best place for the `ask` question (correct, the config file is not used)
> 
> As for the issue, thanks for opening! To summarise: when updating a branch, the settings may show correctly in the dashboard but they are reset
> 
> is that right?

Yes, that's correct. Let's take the example of the "Site URL" configuration. On my master branch and on my dev branch, I have set it to "app.mysite.com". After pushing to my dev branch, I notice that the API responses return "localhost" instead of "app.mysite.com". However, when I check the Supabase interface, it correctly shows "app.mysite.com". So, I manually update the input by pressing "save", and then it works. The API returns the correct site URL again.

**Comment by encima** [comment]
Thanks! Will raise this to the branching team and feedback!

**Comment by sweatybridge** [comment]
This has been fixed on the platform side. Feel free to reopen if the config still doesn't persist after push.
