### ISSUE TITLE
[ BRANCHING ]  Supabase Github extension runs for over 1 hour without any result

### ISSUE THREAD

**Issue by Tananga** [supabase/supabase#23226]
Im testing Supabase Branching and Supabase Github Extension runs for over 1 hour without any result.  Please take a look on the screenshot. Can I cancel it manually? What should I do at this point?

![Screenshot 2024-04-24 at 16 03 30](https://github.com/supabase/supabase/assets/44244477/fb4695f6-236e-49bc-af31-edcca74eddf2)

**Comment by Tananga** [comment]
2 hours 40 minutes later Im still waiting for any result

![Screenshot 2024-04-24 at 17 33 53](https://github.com/supabase/supabase/assets/44244477/55748ea4-9b53-49cb-8c48-8e06cff2478f)

**Comment by Tananga** [comment]
@encima  how to do it?

**Comment by encima** [comment]
> @encima  how to do it?

head over to https://supabase.help and you can open the ticket there :)

**Comment by encima** [comment]
Closing this as it is better served as a Support ticket.
