### ISSUE TITLE
there is no sql language option when you want to create a new function

### ISSUE THREAD

**Issue by arieffajargemilang** [supabase/supabase#23221]
I can't find the SQL language here. there is only the plpgsql language

## Screenrecord

https://github.com/supabase/supabase/assets/53034733/35fbfb04-d8e7-42f5-b9ac-2de1f8ed055a

## System information

- macOS

**Comment by Mrinank-Bhowmick** [comment]
what are the languages supported to make functions other than plpgsql?

**Comment by arieffajargemilang** [comment]
On Supabase Local there is a SQL option when adding a new function, but on Supabase.com there isn't. Has SQL been deleted?


https://github.com/supabase/supabase/assets/53034733/ae6479a9-894b-473d-970d-bac2364314c5
