### ISSUE TITLE
[Feature Request] Angular example

### ISSUE THREAD

**Issue by geromegrignon** [supabase/supabase#2326]
# Feature request

## Is your feature request related to a problem? Please describe.

There is no frontend example using Angular.

## Describe the solution you'd like

I made a clone of the React implementation using Angular.
Here is the deployed app on vercel: https://supabase-todo-list-ajn5.vercel.app/auth

With your consent, I can create a PR to add it to the list of existing examples.
The PR would include : 
- the addition of the example into https://github.com/supabase/supabase/tree/master/examples
- the addition of a link into the docs here: https://supabase.io/docs/guides/examples
- (optional): I can create a CODEOWNERS file on the repo to add me as a reviewer on any PR regarding the scope of this example `/examples/angular-todo-list @geromegrignon`

Is the Dashboard (app.supabase.io) open sourced?

The Quick Start Todo List on the SQL page would have to be updated too (the expo example is missing too):

```
--
-- For use with: 
-- https://github.com/supabase/supabase/tree/master/examples/nextjs-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/react-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/sveltejs-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/vue3-ts-todo-list 
--
```

## Describe alternatives you've considered

None.

## Additional context

If it's fine with you, I made a custom icon for this example (mixing supabase and ngular logos) : 
![angular](https://user-images.githubusercontent.com/32737308/125245281-ac8ecc00-e2f0-11eb-8e7f-b0b75b1c06bc.png)

**Comment by kiwicopple** [comment]
Hey @geromegrignon - we'd love a contribution!

> Is the Dashboard (app.supabase.io) open sourced?

We're [working on that](https://github.com/supabase/supabase/pull/2281). Once the example is merged I can update the comment on this QuickStart schema.

**Comment by geromegrignon** [comment]
@kiwicopple Thanks for adding it.

I keep this issue open for the last task : the update of the QUickstart schema : 
To be changed to : 

```
--
-- For use with: 
-- https://github.com/supabase/supabase/tree/master/examples/nextjs-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/react-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/sveltejs-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/vue3-ts-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/expo-todo-list or
-- https://github.com/supabase/supabase/tree/master/examples/angular-todo-list
--

```
