### ISSUE TITLE
Real time Master table partitioned table !

### ISSUE THREAD

**Issue by azbub** [supabase/supabase#23347]
I partitioned a table in supabase and I have master table, I want to enable real time for it but the dahboard is not loading.
how can I enable it with an SQL query ?

**Comment by encima** [comment]
Hey there,

Thanks for opening! Partitioned tables have partial support in the dashboard currently.

As a workaround, to enable realtime, you can do this from the [Publications](https://supabase.com/dashboard/project/_/database/publications) section under `Database`.

<img width="1404" alt="image" src="https://github.com/supabase/supabase/assets/517923/c2788e8a-2ad4-4060-9162-4e869405e38d">

Click the `X tables` button and scroll to your partitioned parent table and enable it.

Let us know how it goes!
