### ISSUE TITLE
Proposal to Improve Documentation Clarity: Label Methods for Client or Server Usage

### ISSUE THREAD

**Issue by shaman-004** [supabase/supabase#23366]
# Improve documentation

Link:
[Link to the Supabase documentation page](https://supabase.com/docs/reference/javascript/select)

Describe the problem:
The documentation for the select method lacks clarity regarding whether it is intended for client-side usage, server-side usage, or both. This ambiguity can lead to confusion for developers, especially when working in environments like Next.js server actions.

Describe the improvement:
I propose adding labels to each method in the documentation indicating whether it is intended for client-side usage, server-side usage, or both. For example, adding @client, @server, or @both tags in JSDoc comments could help clarify the intended usage of each method.

Additional context:
This proposal is discussed in more detail in issue #22301.

**Comment by encima** [comment]
As this issue is already open in #22301, we will close this to prevent split discussions or duplicate effort.
