### ISSUE TITLE
After change the emails template, I can't use the database

### ISSUE THREAD

**Issue by damianpumar** [supabase/supabase#23377]
I change the invite template email, and click on save. After 1 minutes, I lost the database connection and I see the Auth status unable to connect, I'll attach the image.
I don't know if this an issue or not, but It's a bit critical, because I couldn't restore the previous state.
![Screenshot 2024-04-28 at 19 00 04](https://github.com/supabase/supabase/assets/7398909/07378724-bd12-4f7a-b0db-959a68db5b2b)

**Comment by damianpumar** [comment]
I found some issue after change the email template
![Screenshot 2024-04-28 at 19 14 31](https://github.com/supabase/supabase/assets/7398909/cf5bcf32-ddbd-40a3-857a-0f3c1d1e3adf)

**Comment by encima** [comment]
Hi @damianpumar 
Have you opened a [support](https://supabase.help) about this (if it is hosted)? Or is this running locally?

**Comment by damianpumar** [comment]
> Hi @damianpumar Have you opened a [support](https://supabase.help) about this (if it is hosted)? Or is this running locally?

Hello! the issue is in hosted version

**Comment by encima** [comment]
thanks @damianpumar, if this is hosted, please open a support ticket via the link above :) I will close this for now but, if it is a bug, we can reopen and track it here.

**Comment by damianpumar** [comment]
Is still happening, and also I opened the ticket, but not working!

**Comment by damianpumar** [comment]
I need to set up a new database each time... is frustrating...

**Comment by encima** [comment]
Hi @damianpumar ,

Please post in the ticket to request for updates (and also make sure to include the email template). I would recommend not setting the template in a new project until your issue has been resolved.

**Comment by Tananga** [comment]
I have the same issue 
![Screenshot 2024-05-13 at 14 42 30](https://github.com/supabase/supabase/assets/44244477/fff3e69a-308f-49e6-9f88-5aa0a7ad600a)
