### ISSUE TITLE
Images that are loaded with createSignedUrl always miss cache

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase#23406]
## Describe the bug
I am trying to load and cache images from a non-public bucket. This is the code:
```ts
  const { data, error: storageError } = await supabase.storage
    .from('thumbnails')
    .createSignedUrl(designItem.thumbnailPath, 60 * 60 * 24, {
      download: true,
    });
```
with this code, every image misses the cache as in the screenshot

When I change the bucket to public, it works. Am I doing something wrong or is this a bug?

## Expected behavior
I expected the images to be cached.

## Screenshots
<img width="483" alt="Bildschirmfoto 2024-04-29 um 15 29 26" src="https://github.com/supabase/supabase/assets/43343510/a5834aea-1f17-4fcd-a89f-6f96c117372b">

## System information
- Browser: chrome
- Version of supabase-js: 2.42.7
- Version of Node.js: 20

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

**Comment by encima** [comment]
Hi @Wizzel1 

Thanks for opening! Yes, this is expected behaviour. A signed URL is essentially a "secure" URL that is designed to be time-limited so it is not cached by CDNs
