### ISSUE TITLE
Existing enums are not visible in the editor 

### ISSUE THREAD

**Issue by yaronhb** [supabase/supabase#23417]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The studio UI does not show enums that exist after creation.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

All using the UI:
1. Create a schema named 'my_schema'
2. Go the database enum management and select the schema 
3. Create a new enum named 'MyEnum' with values 'test1' and 'test2'
4. See the create success message 
5. See that the UI does not display the newly created type
6. Verify that the enum does, in fact, exist via the following query:
```sql
select
  enumlabel
from
  pg_enum
where
  enumtypid = (
    select
      oid
    from
      pg_type
    where
      typname = 'MyEnum'
      and typnamespace = (
        select
          oid
        from
          pg_namespace
        where
          nspname = 'my_schema'
      )
  );
```

## Expected behavior

The enum type should appear in the UI.

## Screenshots

After enum creation
<img width="1313" alt="Screenshot 2024-04-29 at 6 01 41 PM" src="https://github.com/supabase/supabase/assets/41547784/66a862d7-7866-469d-9e42-7839bec6c2c4">

<img width="1313" alt="Screenshot 2024-04-29 at 6 22 37 PM" src="https://github.com/supabase/supabase/assets/41547784/c8f51cd8-3e95-4786-9999-f860dec2ff24">

## System information

- OS: [e.g. macOS, Windows]: macos using the supabase installer and docker desktop
- Browser (if applies): safari
- Version of supabase-cli: 1.163.2

**Comment by Hallidayo** [comment]
Hi @yaronhb - just tried creating some enums in a new schema name `omh_test` and I can see the following:

<img width="939" alt="Screenshot 2024-05-27 at 21 43 06" src="https://github.com/supabase/supabase/assets/22655069/9090e1c3-b58d-438c-97c6-f838384fd20a">

Have you tried the above since you created the issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by tecoad** [comment]
@yaronhb @Hallidayo i also have this problem. 
Did you figured out?

**Comment by yaronhb** [comment]
@tecoad I kind of stopped using supabase altogether so I have no idea if it’s fixed

**Comment by tecoad** [comment]
@Hallidayo can you help me on this issue? I am facing this, using latest CLI 1.207.9.

```
    SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.132       │ 15.6.1.132
    supabase/gotrue        │ v2.163.0         │ v2.163.2
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.14         │ v1.11.14
    supabase/edge-runtime  │ v1.59.0          │ -
    supabase/studio        │ 20241014-c083b3b │ -
    supabase/postgres-meta │ v0.84.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```
