### ISSUE TITLE
Remove ; character in json example

### ISSUE THREAD

**Issue by FACON-Nicolas** [supabase/supabase#23420]
# Improve documentation

## Link 

Click [here](https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/database/arrays.mdx) to see the file (/apps/docs/content/guides/database/arrays.mdx)

## Describe the problem

A JSON example is not correctly shown
```
;[
  {
    textarray: ['Harry', 'Larry', 'Moe'],
  },
]
```

## Describe the improvement

Remove the `;`

## Additional context

No more context

**Comment by Hallidayo** [comment]
Hi @FACON-Nicolas, thank you for the pull request! As the pull has been merged I'm going to close this one but again thank you for the contribution.
