### ISSUE TITLE
Email confirmation triggers confirm/route.js twice everytime

### ISSUE THREAD

**Issue by Taxeon** [supabase/supabase#23452]
# Bug report

- [ X ] I confirm this is a bug with Supabase, not with my own application.  This is a basically a copy and paste or YOUR auth confirm code example. Plus, the code works fine it is just getting executed twice every time a confirmation email link is clicked.
- [ X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Every time I click my confirmation email link sent to me via Auth signup the custom auth/confirm/route.js, which is a copy of the code you provide in your documentation, runs twice. The first pass successfully processes but since the second call is also running that one fails and often triggers the reroute to the error page before the first call can rerout to the success page.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Signup and wait for confirmation email
2. Click on on confirmation email link
3. track the auth/confirm page that is triggered 
4. See duplication as below

## Expected behavior
![Screenshot 2024-04-30 114157](https://github.com/supabase/supabase/assets/84356908/524297e1-4b2e-48e6-9830-fa2f09a0f5c5)

I expect it would only run once and not error.

## Screenshots
![image](https://github.com/supabase/supabase/assets/84356908/e1c0e305-3e1a-4330-9166-7f659420f838)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
I don't have any strictmode values set true

**Comment by charislam** [comment]
Thanks for the report, @Taxeon! Which instructions are you following? I just followed all the instructions from [this guide](https://supabase.com/docs/guides/auth/server-side/nextjs?queryGroups=router&router=app) exactly in a fresh Next project. Only addition was a console log to test how many times the GET endpoint runs, and I couldn't reproduce...

<img width="746" alt="Screenshot 2024-04-30 at 18 25 57" src="https://github.com/supabase/supabase/assets/26616127/232968ab-76ac-4435-9b18-3f781c7d9a45">

**Comment by Taxeon** [comment]
Setting up Server-Side Auth for Next.js | Supabase Docs<https://supabase.com/docs/guides/auth/server-side/nextjs>

My Route.js looks just like the one on this page as do my other files. It is not a new project because I am plugging it in but all other aspects work. Just this confirmation always runs twice.
________________________________

**Comment by charislam** [comment]
My advice would be to try reproducing in a fresh project to rule out any problems with the tutorial as-is, then start plugging in the rest of your code in batches to see what's breaking it. Hard to get more specific without seeing the surrounding code.

If you can come up with a minimal reproduction, I'd be happy to look at it.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue, Thank you.

**Comment by Taxeon** [comment]
No worries, turns out the issue seems to have something to do with Microsoft Mail Client on Windows. Seems if you click the link sent from Auth it for some reason calls the link twice. I figured this out when I copied the link to a browser before submitting and it stopped double executing.
________________________________
