### ISSUE TITLE
Missing Linux Download code.

### ISSUE THREAD

**Issue by yuvaraj-LR** [supabase/supabase#23462]
Hi there!

I discovered a bug on the Supabase website. When trying to install supabase-cli on Linux, the code provided in the Linux section is actually for macOS. Because of this, I'm unable to install supabase-cli on my Linux system.

To resolve this issue, it would be helpful to correct the installation instructions for Linux users. This will ensure that users like myself can successfully install supabase-cli on their Linux systems without any confusion. 

For more clarification, I have attach a screenshot below. 

Thank you for your attention to this matter.

#Website Link 
https://supabase.com/docs/guides/cli/getting-started?queryGroups=platform&platform=linux

#System Info

- OS: Linux
- Browser: All Browsers

![Screenshot from 2024-05-01 19-47-08](https://github.com/supabase/supabase/assets/99829922/65778377-7e81-4cbd-9803-200e300d52ac)

**Comment by encima** [comment]
Hi there, thanks for opening!

Homebrew is available for Linux and Mac both. The links below that are for the specific releases of Linux using `apk`, `dpkg` and `rpm` so, hopefully, this covers your Distro!

Alternatively, feel free to use `npx`, `bunx` etc if you don't want to install it on the system.
