### ISSUE TITLE
SSL Protocol error

### ISSUE THREAD

**Issue by lerichardson** [supabase/supabase#2349]
### Discussed in https://github.com/supabase/supabase/discussions/2348

<div type='discussions-op-text'>

<sup>Originally posted by **lerichardson** July 13, 2021</sup>
I created a supabase project about 15-20 minutes ago and the tables in the database were never loading. I look to the console for answers, and find these errors:
![image](https://user-images.githubusercontent.com/72626657/125521447-acb045e4-5a3c-4f17-84fc-f7e3357b254f.png)
Is this an ongoing issue? I've tried switching browsers, too, to no avail.</div>

**Comment by inian** [comment]
Hi more context in [this issue](https://github.com/supabase/supabase/issues/2096). Let me know if one of the workarounds in that issue works for you.
