### ISSUE TITLE
Dashboard - 'Open in SQL Editor' in RLS editor does not reflect presented query 

### ISSUE THREAD

**Issue by cyluss** [supabase/supabase#23614]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When updating RLS policy, SQL editor is populated with `CREATE POLICY` query. 'Open in SQL Editor' button in RLS editor does not reflect presented query. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open existing RLS policy
2. Click on 'Open in SQL Editor'
3. Examine the query in SQL Editor

## Expected behavior

When updating RLS policy, SQL editor is populated with `ALTER POLICY` query. 'Open in SQL Editor' button in RLS editor __must__ reflect presented query. 

## Screenshots

![327291663-2be82007-b3f6-4ee1-88c7-11b2d0492aa0](https://github.com/supabase/supabase/assets/41672371/67453241-e351-40ae-ae32-589b5f0b025a)

## System information

- Hosted supabase
- OS: Windows
- Browser (if applies) Chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

https://github.com/supabase/supabase/blob/e3a6f37d7fb5848b595b5428c88324bc6d68736a/apps/studio/components/interfaces/Auth/Policies/AIPolicyEditorPanel/LockedQuerySection.tsx#L44
https://github.com/supabase/supabase/blob/e3a6f37d7fb5848b595b5428c88324bc6d68736a/apps/studio/components/interfaces/Auth/Policies/AIPolicyEditorPanel/LockedQuerySection.tsx#L45
https://github.com/supabase/supabase/blob/e3a6f37d7fb5848b595b5428c88324bc6d68736a/apps/studio/components/interfaces/Auth/Policies/AIPolicyEditorPanel/LockedQuerySection.tsx#L58

1. There is ternary operator but then-operand and else-operand are switched. If editing policy, must generate alter query. Else (when adding policy) must generate create query
2. Unit test on RLS editor components would early catch such bugs in your development cycle

**Comment by Hallidayo** [comment]
Hi @cyluss - Just tried to re-create the above in the dashboard on some of the policies that I have but I am un-able to. Have you got a video of what is happening for you on your side?

**Comment by saltcod** [comment]
Hey @cyluss thanks for the report on this one – we've removed that button for the moment as there's actually a couple of things wrong with this one. Will try and get it back asap.

Thanks!

https://github.com/supabase/supabase/pull/23649

**Comment by cyluss** [comment]
@saltcod I see the changes, thank you for your work. Just out of curiosity, is there any version identifier for the hosted dashboard?

**Comment by saltcod** [comment]
like `supabase -v` you mean?

**Comment by cyluss** [comment]
Yes but please never mind, I just found `supabase services` cli command
