### ISSUE TITLE
idx.google.com supabase after the environment shutting down the db container could not be started [pgsodium_root.key: Permission denied][invalid secret key]

### ISSUE THREAD

**Issue by alexmazaltov** [supabase/supabase#23710]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am trying to spin up the supabase react template inside an idx.google.com IDE
I was able to adjust the environment management file to spin up the supabase related containers. But the next day when I tried to start docker containers inside idx I get an error: 
```
supabase-imgproxy               | WARNING [2024-05-03T08:41:28Z] Exposing root via IMGPROXY_LOCAL_FILESYSTEM_ROOT is unsafe 
supabase-imgproxy               | INFO    [2024-05-03T08:41:28Z] Starting server at :5001 
supabase-db                     | 
supabase-db                     | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db                     | 
supabase-db                     | cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
supabase-db                     |  2024-05-03 08:41:28.977 UTC [1] FATAL:  invalid secret key
supabase-db exited with code 0
supabase-db                     | 
supabase-db                     | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db                     | 
supabase-db                     | cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
supabase-db                     |  2024-05-03 08:41:30.178 UTC [1] FATAL:  invalid secret key
dependency failed to start: container supabase-db is unhealthy
supabase-react-2024-9770871:~/supabase_react_2024/infrastructure/!!_supabase/supabase/docker{master}$
```

## Additional context
Here is the supabase react template: https://github.com/alexmazaltov/supabase_react_2024
[READ](https://issuetracker.google.com/issues/338381319#comment2) the issue describing my experience with spinning up a Supabase+React project inside IDX.

**Comment by encima** [comment]
HI @alexmazaltov,

This looks like an issue with Google's IDE, can you report this with them please? The user in the container you have does not have access to the `/etc` directory (or any system directories, probably).

If the issue does turn out to be with Supabase then we can re-open. Feel free to link to your reported issue with Google here as well

**Comment by alexmazaltov** [comment]
I reported the [issue](https://issuetracker.google.com/issues/338624450) on google issue tracker for idx
