### ISSUE TITLE
Row level security

### ISSUE THREAD

**Issue by link-discord** [supabase/supabase#2378]
### Discussed in https://github.com/supabase/supabase/discussions/2377

<div type='discussions-op-text'>

<sup>Originally posted by **link-discord** July 15, 2021</sup>
I'm trying to insert a new user in my frontend but the row-level security denies it
I have used the policy template that only lets authenticated users insert new rows
but it still refuses to let me insert data even though in frontend it logs that I do have "authenticated" as the role

Any help on this?

![image](https://user-images.githubusercontent.com/50463727/125783758-9a0c134d-71e0-48ea-8fa6-953ad207e540.png)
![image](https://user-images.githubusercontent.com/50463727/125783826-6f583fea-fccf-4143-b9b8-8c836424b306.png)
![image](https://user-images.githubusercontent.com/50463727/125783849-bba69026-b1db-49a4-86d5-969efb752606.png)
![image](https://user-images.githubusercontent.com/50463727/125783877-cf8bbd19-af82-4a6c-a771-7b83b979a33a.png)

</div>

**Comment by jonlambert** [comment]
I ran into this - solved it by adding a similar policy for select, too. Not sure if this is expected behaviour.

**Comment by link-discord** [comment]
managed to solve it lol
