### ISSUE TITLE
Improve docs for the "updateUser" API, specially when updating a user's email.

### ISSUE THREAD

**Issue by pablocubico** [supabase/supabase#2381]
# Improve documentation

## Link 
https://supabase.io/docs/gotrue/client/api-updateuser

## Describe the problem
The docs don't explain the flow for updating a user's email (e.g.: the "Confirm Email Change" flow).

## Describe the improvement
I added notes to the `updateUser` part of the GoTrue docs, as the one present in the `resetPasswordForEmail`.

## Additional context
I created a PR here:
https://github.com/supabase/supabase/pull/2380

(Sorry, I read the contributing guidelines after creating the PR!).

I found this related discussion: https://github.com/supabase/supabase/discussions/1763

**Comment by kiwicopple** [comment]
THanks for the PR @pablocubico !

I think we should also add this as an example on this page: https://supabase.io/docs/reference/javascript/auth-update

(we need to update supabase.yml)

So I'll leave this open until we add the example

**Comment by kiwicopple** [comment]
Added here: https://supabase.com/docs/reference/javascript/auth-update#update-email-for-authenticated-user
