### ISSUE TITLE
Foreign key unwanted behavior

### ISSUE THREAD

**Issue by srealtchat** [supabase/supabase#2382]
# Bug report

## Describe the bug

Unwanted behavior on foreign keys

## To Reproduce, Expected Behavior and Screenshots

I want to create a messages table

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 11 26" src="https://user-images.githubusercontent.com/87483630/125803667-488e32dd-00ac-4d7d-8b64-33c9d9a20e3b.png">

I want to add a sender column to identify who sent the message

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 11 51" src="https://user-images.githubusercontent.com/87483630/125803789-42ca0191-a3c3-46f3-81ca-be7949cc343d.png">

I want to tell that sender is a foreign key referencing a user id. The users table isn't shown to me

<img width="1440" alt="Capture d’écran 2021-07-15 à 16 13 28" src="https://user-images.githubusercontent.com/87483630/125804109-1de736f4-2883-4846-bd02-3766b479814c.png">

No problem, I'll try to add it editing the column. But when I try to edit the foreign key of the column, I can't event type anything in the table name field

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 14 27" src="https://user-images.githubusercontent.com/87483630/125804207-78fd0425-4ef3-4df0-a6b0-42a87c94bf76.png">

So I went to Database section (instead of Tables section), I clicked on the columns button of the messages public table, and then edit the column sender.

<img width="1440" alt="Capture d’écran 2021-07-15 à 16 14 50" src="https://user-images.githubusercontent.com/87483630/125804553-73be6e0d-511f-439a-beb1-d143834ff7d4.png">

There is the table that I searched for, but surprisingly there isn't the messages table anymore. Anyway I added the auth.users.id column as a foreign key.

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 15 19" src="https://user-images.githubusercontent.com/87483630/125804903-c65d8a25-af49-4794-aea0-a31a934c1429.png">

Then I clicked save, and when I went back on editing the column, the foreign key disappeared.

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 15 30" src="https://user-images.githubusercontent.com/87483630/125805001-f3d9936a-cde5-4b00-8a80-183a93e2c98c.png">

I checked in the Tables section, but even there I found no foreign key.

<img width="1552" alt="Capture d’écran 2021-07-15 à 16 16 01" src="https://user-images.githubusercontent.com/87483630/125805087-888d2595-d1a4-4fcd-88d9-166123eca961.png">

Then I refreshed the page and the foreign key appeared only in the Tables section. I wanted to add a row, to test it. I just copy-pasted the UUID of a user I've just created. When I checked the foreign key using the little button on the right of the field, it shows me an error

<img width="967" alt="Capture d’écran 2021-07-15 à 16 30 30" src="https://user-images.githubusercontent.com/87483630/125805719-fed0c20a-8299-4fe6-9ac0-40c363396486.png">

And when I clicked on the little button on the right of the field, in the table view, it shows me nothing

<img width="967" alt="Capture d’écran 2021-07-15 à 16 30 43" src="https://user-images.githubusercontent.com/87483630/125805852-c0eee962-8ff7-4aea-92b6-7cba19a8b1a9.png">

Maybe I'm doing something wrong, but anyway it seems that there is unwanted behavior at some points.

## System information

- OS: macOS
- Browser : chrome

**Comment by awalias** [comment]
hey @srealtchat thanks for the in depth bug report!

it is true that `auth.users.id` is not available in the table view since it is only allowed to access data in the `public` schema and not the `auth` schema

for now you should be able to add these relations via the SQL editor and we will work on improving the experience of the table view editor.

I think it is correct that you cannot select any tables in the side panel as there is only currently one table in the public schema

I'll close for now as https://github.com/supabase/supabase/issues/1129 and https://github.com/supabase/supabase/issues/1129 will also solve your issue

**Comment by srealtchat** [comment]
What about the foreign key that appears only in the table editor, the need to refresh ?
What about the 4th screenshot where the foreign key editor doesn't work at all ?

**Comment by srealtchat** [comment]
@awalias

**Comment by joshenlim** [comment]
hey there @srealtchat! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!

Also you should now also be able to create relations to the `users` table in the `auth` schema too :)
