### ISSUE TITLE
is storage server down?

### ISSUE THREAD

**Issue by alexandregiordanelli** [supabase/supabase#2383]
My buckets disappeared

https://app.supabase.io/project/fttdipmtsfhnjcgijuot/storage/buckets

https://fttdipmtsfhnjcgijuot.supabase.co/storage/v1/object/cdn

No response.. The server apparently is down

**Comment by alexandregiordanelli** [comment]
{
  "message":"The upstream server is timing out"
}

**Comment by inian** [comment]
Hi @alexandregiordanelli, I see @w3b6x9 has reached out to you via our support channel. Let me know if this is still an issue.
