### ISSUE TITLE
Add Supabase UI for Managing RPC

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2389]
# Feature request
Add an ability to manage RPC via UI and not Raw SQL editor. **(Kinda like creating table, column or row)**

## Is your feature request related to a problem? Please describe.
**A developer experience problem.**
Writing `RPC` via `Raw SQL Editor` has some drawbacks even if you uses `PLV8`. It has still some learning curve going in for beginners and for others that are transitioning to SQL language.

Also its really **hard to maintain** a RPC via just raw sql editor because mainly most of the write operations are transactional by default we cant achieve that via client side SDK (so the solution is to use RPC)

## Describe the solution you'd like
1. View current list of `RPC` just like viewing the list of tables
2. Create a `RPC` like creating table, column, or row via `form`

**Lets see this 3 examples from the community:**

```sql
create or replace function vote(quote_id int, increment_num int)
return void as $$
  update my_table_name
  set which_field = which_field + increment_num
  where field_id = quote_id
$$ language sql volatile;
```

```sql
CREATE OR REPLACE FUNCTION public.topup(user text, amount integer)
RETURNS integer LANGUAGE 'plpgsql' AS $$
begin
  update users set balance = balance + amount;
  insert into "transactions" (user, amount, note) values (user, amount, 'top up');
  return 1;
end
$$;
```

```sql
create or replace function auth.uid()
returns uuid as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$ language sql stable;
```

**Common fields needed**
1. Function Name (vote, topup, auth.uid)
2. Function Params (param name & param type) = Just like adding table columns
3. Function Return type
4. Function body ($$ >here goes the sql body or PLV8< $$)
5. Language dropdown (SQL or PLV8) with some description display of what this does

Maybe we can make a Input form to this and a UI
Maybe after that we can also generate the RPC for Supabase Client for copy paste

**Comment by sandbox-apps** [comment]
After all theres no so much resource about RPC in Supabase docs. Which is kinda bad for those who are not familiar with RPC
But with this, I can do RPC all day

![image](https://user-images.githubusercontent.com/86398599/125885061-9d8a953f-413b-4841-af8b-3909d305ac28.png)

**Comment by sandbox-apps** [comment]
Same can be apply to supabase own example:
```sql
create function increment (row_id int) 
returns void as
$$
  update table_name 
  set field_name = field_name + 1
  where id = row_id;
$$ 
language sql volatile;

-- you can call the function from your browser with supabase-js
-- const { data, error } = await supabase.rpc('increment', { row_id: 2 })
```

Also I believe that the supabase policy has this feature for creating policies via UI

**Comment by awalias** [comment]
hey @sandbox-apps this is currently being worked on and should be available soon!

assigning @MildTomato who is working on it

**Comment by MildTomato** [comment]
Pretty good timing seeing this issue as the support for functions in postgres-meta was merged in just hours ago 😂 
https://github.com/supabase/postgres-meta/pull/118

**Comment by sandbox-apps** [comment]
That was fast! I love developer friendly products! Im excited :)

**Comment by kiwicopple** [comment]
This has been added (experimental) to the UI under Database > Functions 🚢
