### ISSUE TITLE
Error when logging in slack-clone example

### ISSUE THREAD

**Issue by gamedevsam** [supabase/supabase#239]
# Bug report

## Describe the bug

When logging in with a newly created account on the Slack demo app, I get the following error:

```
client.js:837 GET https://osksozjupnlzbbxrdwnv.supabase.co/rest/v1/users?select=id%2Cusername&username=eq.test@test.com 404
_app.js:33 error Error: {"hint":null,"details":null,"code":"42P01","message":"relation \"public.users\" does not exist"}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone slack example
2. Install dependencies
3. Run next dev server (npm run dev)
4. Create new account, for example test@test.com / test
5. Attempt to sign in with said account, notice error

## Expected behavior

The user should be able to sign in.

## System information

- OS: Windows 10
- Version of supabase-js: 0.36.5
- Version of Node.js: 14.10.0

## Additional context

I can see that my user was created in supabase, so it seems to be an issue with the client library.

**Comment by kiwicopple** [comment]
Hi @gamedevsam thatnks for reporting 

Can you please run this in the SQL editor and let me know the results?

```
SELECT * FROM pg_catalog.pg_tables where schemaname = 'public';
```

**Comment by gamedevsam** [comment]
![image](https://user-images.githubusercontent.com/420996/95406685-00473180-08e9-11eb-9698-f89ed06d4a3d.png)

**Comment by kiwicopple** [comment]
It looks like you may need to run the "Quick start" template first: 

<img width="1440" alt="Screenshot 2020-10-08 at 10 05 01 AM" src="https://user-images.githubusercontent.com/10214025/95406760-c9573700-094d-11eb-9855-4fdbbfa08e1c.png">

Let me know if it works after "Running" that script

**Comment by gamedevsam** [comment]
Ohh, I was under the assumption the DB was seeded from the app or something, might be a better idea to run this SQL via npm script to better reflect a more traditional approach. Thanks for your help.
