### ISSUE TITLE
Triggers (UI Management Editor)

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2403]
# Feature request
Trigger UI Management much like adding policies or RPC UI editor

## Describe the solution you'd like
Much like the issue describe here: https://github.com/supabase/supabase/issues/2389
Just a separate feature request.

**Comment by w3b6x9** [comment]
@sandbox-apps thanks for the feature request! @awalias's [comment](https://github.com/supabase/supabase/issues/2389#issuecomment-881282905) also applies to triggers as well. Coming soon!

**Comment by kiwicopple** [comment]
This has been added (experimental) to the UI under Database > Triggers 🚢
