### ISSUE TITLE
Add Auth/User Management to homepage

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#241]
I received a question this morning from someone asking if we did auth and third party logins since it's not mentioned on the homepage anywhere

since it's a large selling point we should probably make it a feature of the homepage

Suggestions include:

- add 'Auth' or 'User management' somewhere in the hero (tagline?)
- add a code example under 'For Developers' 
- add a whole new section
  - screen cap of users list and/or screen cap of login widget 
  - logos of third party providers

**Comment by kiwicopple** [comment]
I will create a page for our "Supabase Auth" launch. We can probably create a whole page for each of the features we have - at the moment just "Auth" and "Database"

**Comment by duncanhealy** [comment]
Should need an easy way to fill in the id and secret 
or at least link to the places to generate them

Some links below

- [ ] **google** [oath client](https://cloud.google.com/iap/docs/programmatic-oauth-clients)
- [ ] **github** [github create client](https://github.com/settings/applications/new)
- [ ] **bitbucket** [bitbucket create client](https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/)
- [ ] **gitlab** [gitlab add oath client](https://docs.gitlab.com/ee/integration/oauth_provider.html)
