### ISSUE TITLE
Database error finding user

### ISSUE THREAD

**Issue by dhaalac** [supabase/supabase#2431]
# Bug report

## Describe the bug
when i try to send invite link to a user this is what happens and i can't sign up my user 
Inviting user failed: Database error finding user
how can i restore auth.user table
i created auth.users table again and it's not working yet
## To Reproduce
i run this to get rid of some trigger i created earlier

DROP FUNCTION IF EXISTS handle_new_user();
DROP TABLE if exists users cascade;

Steps to reproduce the behavior, please provide code snippets or a repository:

1. DROP FUNCTION IF EXISTS handle_new_user();
DROP TABLE if exists users cascade;

## Expected behavior
normal auth working 

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by geromegrignon** [comment]
Hello @dhaalac,

Please fill the `Describe the bug`, `To reproduce`, and `Expected behavior` sections.
Otherwise, maintainers won't be able to identify the bug and the issue will more likely be closed.

**Comment by dhaalac** [comment]
Ok that's the problem
