### ISSUE TITLE
Supabase Dashboard projects page is stuck in the loading phase

### ISSUE THREAD

**Issue by demirelrecep** [supabase/supabase#24313]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The projects tab in the dashboard has not been opened for a few days. It's stuck in the loading phase.
I am using github for authentication

## To Reproduce

1. Go to [Dashboard Projects Page](https://supabase.com/dashboard/projects)
2. See error

## Screenshots

![Ekran Resmi 2024-05-05 19 54 17](https://github.com/supabase/supabase/assets/35351559/38ffaee9-b0dd-4798-92e7-d2f7bdf5d542)

## System information

- OS : MacOS
- Browser : Chrome

**Comment by encima** [comment]
Please try a hard refresh to confirm if this is still an issue.

**Comment by d-e-h-i-o** [comment]
I occasionally experience the same on Firefox. Hard refresh doesn't help, just completely wiping local storage etc. I mostly switch browser then, and return after a few days, when it starts working again.

**Comment by demirelrecep** [comment]
Hi, the problem resolved itself after 3-4 days. I'm not having any problems now
