### ISSUE TITLE
Corrupted account settings prevent normal functioning across the whole account

### ISSUE THREAD

**Issue by Armagedoom** [supabase/supabase#2432]
# Bug report

The  config associated to the only project in my account seems to be corrupt and is throwing several strange errors and preventing normal functioning.

## Describe the bug

There at least three impacts from this corrupted settings / Why I think this is a problem with the settings:

1. When going to my project -> Settings -> "Auth settings", I get logged out and get the message "Your session has timed out".

2. I think something is corrupted within the config of my account, because I can neither go to "Billing & usage" without getting the following error:

![image](https://user-images.githubusercontent.com/4046326/126066284-c8260a76-7955-4afb-aec6-e9a9a5a1f133.png)

3. Also, I [cant run SQL Queries ](https://github.com/supabase/supabase/discussions/2428#discussioncomment-1024052) and always get the message "SQL Query is empty" despite its not:

![image](https://user-images.githubusercontent.com/4046326/126066439-d63da6d8-e557-4b21-9ece-2ea4009706d8.png)

4. Also, can't create new projects because the new password says that I need a stronger password, despite making it incredibly complex (capitals, numbers, symbols, etc):

![image](https://user-images.githubusercontent.com/4046326/126070599-9af7f4cf-0a00-4a5f-b341-f60f9ffb9c41.png)

Many functionalities seem broken in this project (the only one I have) and in the account.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1 Go to "Settings" -> "Auth settings" in the only project that belongs to my Github account.
2: Get logged out:

![image](https://user-images.githubusercontent.com/4046326/126066369-03dc7ffb-ceb8-4414-934b-e73e28ef6aa4.png)

1 Go to "Settings" -> "Billing and usage". Get the error in the image:
![image](https://user-images.githubusercontent.com/4046326/126066284-c8260a76-7955-4afb-aec6-e9a9a5a1f133.png)

## Expected behavior

Not getting the error and being able to update the project URL / navigate settings in general

## System information

- OS: [Windows 10]
- Browser (if applies) [Firefox]
- Version of supabase-js: [Just installed everything, so it should be the latest]

**Comment by Armagedoom** [comment]
Also, if I try to update my name / surname in the profile:

![image](https://user-images.githubusercontent.com/4046326/126106735-bd5675dc-d174-40e0-921c-6030ccaa19c0.png)

**Comment by kiwicopple** [comment]
I think you may be encountering this issue @Armagedoom : https://github.com/supabase/supabase/issues/2096

We're working on a final fix now.

**Comment by Armagedoom** [comment]
After reading the issue referred, I still thing this is a sepparate one.
I can connect  normally to the database.
My errors happen when I try to edit my account config, which (as far as I understood) is not quite the same problem the guys in that error have.
I am over LAN (no wifi like most people on that post).

I am getting quite different error than the rest (one of them is this one for instance, when I get automatically logged out):

![image](https://user-images.githubusercontent.com/4046326/126349141-b9b32ab8-928c-4de8-8212-a8b00dd6bc64.png)

And when trying to change my name for instance:

![image](https://user-images.githubusercontent.com/4046326/126350185-d23cbdd5-2152-4f69-a1e7-9f1dc739fa93.png)

Just tried it with a new account, and for that account I can neither create new projects:

![image](https://user-images.githubusercontent.com/4046326/126350497-c8a0b617-4623-4971-a56d-f97588eb7a83.png)

The main reason why I still think it is a different bug is because I created my first account only 16 days ago, and I could create new projects (the one I am using right now) but now I cant create new projects in neither of them.
But the bug you linked to is more than 25 days old so I should have been affected from the start.

Anyhow maybe I am wrong.

**Comment by kiwicopple** [comment]
hmm, odd. Thanks for reporting this @Armagedoom. Can you please send message to beta@supabase.io with all your login details? We'll have a look at why this is happening - perhaps you're right about a corrupted account.

**Comment by Armagedoom** [comment]
I sent it a few days ago, just let me know if you didn't receive it or need more information, thanks.

**Comment by Armagedoom** [comment]
Turns out this was a problem caused by bitdefender.
I had to set an exception for supabase domain, then everything begun working!

**Comment by inian** [comment]
Hi @Armagedoom, glad the issue is resolved! Just curious which domain did you whitelist in Bitdefender - supabase.co or supabase.io?

**Comment by Armagedoom** [comment]
It was: app.supabase.io

**Comment by inian** [comment]
Oh that is very interesting, thanks for sharing!
