### ISSUE TITLE
PostgREST version

### ISSUE THREAD

**Issue by m0ast** [supabase/supabase#2434]
# Improve documentation

Hello,
I didn't want to pollute #1811  so I made a new one. Actually, it's pretty much the same issue, which is to provide an easy way to get the used PostgREST version.

**Comment by steve-chavez** [comment]
This can be obtained right now by doing an http request directly to PostgREST(check the bash API docs for examples). Basically:

```bash
curl -s -I 'https://<project>.supabase.co/rest/v1/' | grep server

server: postgrest/20210627 ## which is a nightly version
```

**Comment by m0ast** [comment]
> This can be obtained right now by doing an http request directly to PostgREST(check the bash API docs for examples). Basically:
> 
> ```shell
> curl -s -I 'https://<project>.supabase.co/rest/v1/' | grep server
> 
> server: postgrest/20210627 ## which is a nightly version
> ```

thank you steve
