### ISSUE TITLE
Unable to change column name of primary key column defined as 'Automatically generate as identity' and type of 'int8'

### ISSUE THREAD

**Issue by cadeluca** [supabase/supabase#2442]
# Bug report

## Describe the bug

Unable to edit the name of a column in a new or existing table when the column was created with type int8 and default value of "Automatically generate as identity". The error "Error for input at Default Value: Value type does not match specified column type" pops up, blocking save. Originally saw this on a table with multiple records, but following my reproduction steps got the same issue on an empty table.

For a workaround you can simply alter the column name via SQL. 

In efforts to get it to save / break further, I changed the type to int4 and was able to save, but any changes afterward were blocked with the error "Cannot read property 'accept-version' of undefined", potentially related to #2404.

## To Reproduce

1. Use an existing table's primary key column or create a new table with a primary key column, in either case using the defaults at time of filing this issue: type of in8, default value as "Automatically generate as identity", and the default name of "id" or anything you'd like, for example "bug_id". Your table may be empty or have records.
2. Click on the dropdown arrow for the column -> click "Edit column"
3. Only change the name, for example change "bug_id" to "bug_report_id"
4. See error "Error for input at Default Value: Value type does not match specified column type".

## Expected behavior

The edit to complete successfully, updating the primary key column name and updating the index associated with that column.

## Screenshots

![screenshot of Supabase column editor, showing an error pop up stating "Error for input at Default Value: Value type does not match specified column type".](https://user-images.githubusercontent.com/32560733/126149135-775265f1-69ca-4e1f-bc10-a3a405cedfc9.jpg)

## System information

- OS: Windows 10, also seen on Mac OS Big Sur
- Browser: Chrome (v91.0.4472.124)

**Comment by joshenlim** [comment]
hey there @louisbarclay! We've pushed out a couple of fixes and improvements to the side panels and this should now be resolved. I'll close the ticket for now but feel free to reopen if there are any other issues.

Also regarding the "accept-version" of undefined error - you're right! it's an existing issue that we're working on here at the moment: https://github.com/supabase/postgres-meta/issues/144
