### ISSUE TITLE
When updating avatar uploaded to Storage using `upsert: true`, the older file doesn't get deleted.

### ISSUE THREAD

**Issue by Karniej** [supabase/supabase#2443]
# Bug report
This is my 1st ever Github issue created I'm sorry if I butcher something. 
First of all , I don't think it's a bug, more like I'm not understanding something properly and I'm missing any documentation or description on how to correctly do this.

## Describe the bug

I followed your quiick start guide (React) and created an app in React Native that allows me to upload avatar files to Storage.
I want the user to be able to upload ,update and delete their own avatars and keep the storage clean, so the older avatar gets deleted.

## To Reproduce
Upload a file to storage with the `upsert:true` flag by the signed-in user. Then upload the file again and see there are 2 files inside the storage.

![image](https://user-images.githubusercontent.com/24280640/126161397-671798c0-8324-4559-849f-d13bcf732fb3.png)

```javascript        
      const { error, data } = await supabase.storage
          .from('avatars')
          .upload(fileName, parsedImage, {
            cacheControl: '3600',
            upsert: true,
          })
```

These are the Storage policies:

![image](https://user-images.githubusercontent.com/24280640/126161451-15f87053-b927-43ce-84bc-322e50da8643.png)

## Expected behavior

I would like to upload avatar and then be able to update it with the older file being deleted. I tried removing the file, but it didn't work too. (File was not found )

## System information

- OS: [macOS Big Sur 11.4)
- React Native Expo [42.0.0]
- Version of supabase-js: [1.13.1]
- Version of Node.js: [e.g. 16.3.0]

**Comment by inian** [comment]
How is the `filename` being generated @Karniej? Is it a different value each time? If the filename is same across both your API calls, then two files shouldn't get created and the object should get overwritten.

**Comment by Karniej** [comment]
> How is the `filename` being generated @Karniej? Is it a different value each time? If the filename is same across both your API calls, then two files shouldn't get created and the object should get overwritten.

@inian When I have the same file name I get this error `"message": "new row violates row-level security policy (USING expression) for table \"objects\"",`

**Comment by inian** [comment]
Hey Pawel, so looks like you are trying to keep the name of the file the same as the user id? You are comparing auth.uid and object id which wont be a match.

Remember to restrict the bucket_id in the policies too, else it will apply across all your buckets. 

Can you try with these policies?

```
create policy "Users can update their avatar."
  on storage.objects for update
  using ( auth.uid() = name and bucket_id = 'avatars' );

create policy "Users can delete their avatar."
  on storage.objects for delete
  using ( auth.uid() = name  and bucket_id = 'avatars' );

create policy "Users can select their avatar."
  on storage.objects for select
  using ( auth.uid() = name  and bucket_id = 'avatars');
```

**Comment by Karniej** [comment]
I tried with this sql query and I have a `operator does not exist: uuid = text` error.

**Comment by kiwicopple** [comment]
You can "cast" the UUID to text on the policies @Karniej - like this:

```sql
create policy "Users can update their avatar."
  on storage.objects for update
  using ( auth.uid()::text = name and bucket_id = 'avatars' );
```

take note of the `::text` which will cast the columns to be the same type

**Comment by ChristianDavis** [comment]
@Karniej in the above any file extension would cause the match to fail as well, or are you storing the images with no file extension in the name? All the example code I've seen is including the ext as part of the file name

**Comment by fkhadra** [comment]
@Karniej, this is how it's implemented on my side. Not sure if it's the best way though, but it works for now.
- create `avatars` bucket
- I've defined the policies below
<img width="853" alt="Screenshot 2021-08-20 at 11 16 49" src="https://user-images.githubusercontent.com/5574267/130210955-b966edad-f9e0-4b35-bc69-f18fdba74689.png">

```sql
create policy "Select avatar"
on storage.objects for select using (
    bucket_id = 'avatars'
);

create policy "Delete avatar"
on storage.objects for delete using (
    bucket_id = 'avatars'
    and (auth.role() = 'authenticated')
    and storage.filename(name) like concat(auth.uid()::text, '%')
);

create policy "Update avatar"
on storage.objects for update using (
    bucket_id = 'avatars'
    and (auth.role() = 'authenticated')
    and storage.filename(name) like concat(auth.uid()::text, '%')
);

create policy "Insert avatar"
on storage.objects for insert with check (
    bucket_id = 'avatars'
    and (auth.role() = 'authenticated')
    and storage.filename(name) like concat(auth.uid()::text, '%')
);
```
`storage.filename(name)` returns the filename with the extension, so I combine it  with a pattern matching
`like concat(auth.uid()::text, '%')`, think of it as match `uuid*`

- In my react-native app I do the following
```tsx
async saveAvatar(profileId: string, image: ImageInfo) {
    const ext = image.uri.substr(image.uri.lastIndexOf(".") + 1);
    const { data, error } = await supabase.storage
      .from("avatars")
      .upload(`${profileId}.${ext}`, decode(image.base64!), {
        contentType: `image/${ext}`,
        upsert: true,
      });

    if (error) throw error;

    return data!.Key;
  }
```

The implementation is not fully production-ready, getting the file extension from the file name is not the best but for now, it's enough for my use case.

Another approach that I've tried is to have one folder per user id. For example, `avatars/uuid/avatar.jpg` . The policy would look like 

```sql
create policy "Insert access for avatars."
on storage.objects for Insert with check (
     bucket_id = 'avatars'
     and (auth.role() = 'authenticated')
     -- match folder name with user uuid
     and (auth.uid()::text = (storage.foldername(name))[1])
 );

```

Hope it helps. Happy coding

**Comment by joshenlim** [comment]
hey there @Karniej! can i just check real quick to see if this issue is still happening for you? It does sound like this isn't an issue with the dashboard itself so i'll be removing the dashboard label, but please do feel free to advise otherwise if i missed anything!
