### ISSUE TITLE
401 errors in dashboard

### ISSUE THREAD

**Issue by churichard** [supabase/supabase#2449]
# Bug report

## Describe the bug

Whenever I try to update settings in the "Authentication" tab of the dashboard, I get a 401 error. Going into the "Policies" or "Templates" section, or the "API" tab, often shows "Error connecting to API SyntaxError: Unexpected token U in JSON at position 0".

When I try to delete a user, I get an error that says: "Deleting user failed: invalid input syntax for type uuid: "undefined"".

Also, sometimes the entire dashboard crashes with a blank page that says "An unexpected error has occurred." Or my session times out randomly.

If it helps, I was recently using server-side authentication in my own app as described in the [Next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-supabase-auth-realtime-db) and was running into 401 errors as well, so this is likely not a problem with the dashboard. I suspect there was a recent change with authentication that broke things.

I've noticed this happening since July 16th, and it means that I can't do anything in the Supabase Dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.io, log in, then click on Authentication -> Settings
2. Update a setting
3. Try to save
4. Witness a 401 error

There are many, many other ways to reproduce. Just try clicking around in the dashboard and making changes. You'll run into errors eventually.

## Expected behavior

Everything should work properly with no errors.

## Screenshots

Video: https://www.youtube.com/watch?v=TrK92KOr8Qo

## System information

- OS: Windows
- Browser (if applies): Chrome

**Comment by kiwicopple** [comment]
I think you may be encountering this issue @churichard  : https://github.com/supabase/supabase/issues/2096

We're working on a final fix now.

**Comment by churichard** [comment]
I think it's the same as https://github.com/supabase/supabase/issues/2432, but I have a feeling it's a separate issue from https://github.com/supabase/supabase/issues/2096. If it helps, I recorded a video to show just how broken the Supabase dashboard is for me right now: https://share.getcloudapp.com/5zuY61mN

**Comment by Armagedoom** [comment]
I just commented the exact same oppinion (before reading yours) on #2432  . 
Sadly I think they are sepparate issues.
I just created a new account and same things happen on that one.

**Comment by inian** [comment]
Possibly related https://github.com/supabase/supabase/discussions/2320

**Comment by churichard** [comment]
Been troubleshooting with the Supabase team over email and I think we've narrowed down the issue.

I tested the dashboard using 4G on my phone and everything seemed to work fine. So it might be due to my ISP, which is Verizon.

This means that sites built with Supabase that are accessed through Verizon might be breaking as well.

It would be great to get this fixed, but I guess in the meantime I can just use my phone to update stuff in the dashboard 😅

**Comment by Armagedoom** [comment]
I fixed my issue by setting an exception in bitdefender for supabase domain.
Seems like you also have trouble with some antivirus installed only in the computer where it does not work ;)

**Comment by churichard** [comment]
Thanks for letting me know! I do indeed have Bitdefender installed, and I can confirm that disabling it fixes the issue.

Adding the exclusion `app.supabase.io` doesn't seem to work, however - I still run into the same issues. I've also added `supabase.io` and `supabase.co` to the exclusion list too, and cleared my cookies/cache + restarted my computer.

Definitely not ideal, but I'm not sure if Supabase can do anything on their end. I guess I'll probably install another antivirus then 🤷‍♂️

**Comment by inian** [comment]
I submitted a false positive report to Bitdefender here - https://www.bitdefender.com/consumer/support/answer/40673/
They said they will look into it in 72 hours 🤞🏽

**Comment by churichard** [comment]
Awesome, thanks @inian!
