### ISSUE TITLE
logging for rest calls backend

### ISSUE THREAD

**Issue by duncanhealy** [supabase/supabase#245]
# Feature request

looking at the logging from postgres to track down an issue, cvslog is enabled, going to pg_log

## Is your feature request related to a problem? Please describe.

trying to track down why delete is failing silently
delete (rest) returns http status code 204

## Describe the solution you'd like

ability to see errors from postgres on app.supabase.io
? ability to set log_statement=all temporarily?

## Describe alternatives you've considered

tried to pull out errors from pg_log csvlog (this can be queried), 
changing log_statement=none (need superadmin to change this)

**Comment by steve-chavez** [comment]
To trigger an error when no delete is done, you could use `single()` from supabase-js:

```js
supabase.from('tasks').delete().eq('id', task_id).single()
```

I think exposing the logs won't reveal anything of value, what's happening essentially is:

```sql
-- assume there's no task with id 666
delete from tasks where id = 666;
-- DELETE 0
```

Which is actually a success(no error).

**Comment by duncanhealy** [comment]
using .single() I get a Status Code of 406 message back 

```"Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row"```

.select() rather than .delete() gives the record

**Comment by duncanhealy** [comment]
ok I see that is as expected - docs here http://postgrest.org/en/v7.0.0/api.html#singular-or-plural

delete statement inside the sql editor works fine, 
e.g.
```delete from tasks where id=1```

fails when called from api where a record with id = ```task_id``` exists

```supabase.from('tasks').delete().eq('id', task_id )```
or 
```supabase.from('tasks').delete().match({'id': task_id})```

**Comment by kiwicopple** [comment]
We've been using the `delete()` successfully here so it suggests it's not erroring at the library level: https://github.com/supabase/supabase/blob/4691063f8143a1d287c49c1d10cef7cec91644dc/examples/todo-nextjs/components/TodoList.js#L32

Could you please check the network request tab, and let us know what the URL/payload is when calling `supabase.from('tasks').delete().eq('id', task_id )` ?

**Comment by duncanhealy** [comment]
```
fetch("https://xx.supabase.co/rest/v1/tasks?id=eq.33", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US",
    "apikey": "x",
    "authorization": "Bearer x",
    "cache-control": "no-cache",
    "content-profile": "public",
    "content-type": "application/json",
    "pragma": "no-cache",
    "prefer": "return=representation",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:8080/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "DELETE",
  "mode": "cors"
});
```

**Comment by duncanhealy** [comment]
funny thing is the OPTIONS is going after the DELETE request - > I would expect the OPTIONS first ??
200 returned for both [] for the DELETE
```
fetch("https://xx.supabase.co/rest/v1/tasks?id=eq.33", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:8080/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "OPTIONS",
  "mode": "cors"
});
```

**Comment by kiwicopple** [comment]
I think I'll need to set this up to replicate it - this is happening on the `todo-sveltejs` app right @duncanhealy ?

**Comment by duncanhealy** [comment]
yea it should also show the problem with auth on the first go supabase/gotrue-js/issues/23

need to refresh to bring up the list + logout login if session token expired

**Comment by kiwicopple** [comment]
this is now completed :) You can query all your API logs via Settings > Logs > API ⚡
