### ISSUE TITLE
Updating column with foreign key in Supabase Table Editor fails

### ISSUE THREAD

**Issue by louisbarclay** [supabase/supabase#2452]
# Bug report

## Describe the bug

Updating foreign key in Supabase Table Editor fails, when foreign key = user uuid.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a user table
2. Create a table 'distributions' with a field 'user_id' where 'This column has a relation to table 'users' on column 'id''
3. Create a record on this table where the 'user_id' field matches a user record in the user table
4. Right-click 'Edit row'
5. Paste a different value from the users table into the 'user_id' field
6. Hit Save
7. Nothing happens
8. It looks like no request is sent immediately for this

No error is reported

## Screenshots

![image](https://user-images.githubusercontent.com/21208811/126194860-2c697948-53f8-4067-bb44-447baec3f8ad.png)

## System information

- OS: Windows
- Browser (if applies) Chrome

**Comment by joshenlim** [comment]
hey there @louisbarclay! We've pushed out a couple of fixes and improvements to the side panels and this should now be resolved. I'll close the ticket for now but feel free to reopen if there are any other issues
