### ISSUE TITLE
Prevent full-table updates or deletes

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2475]
Add extension security through https://github.com/eradman/pg-safeupdate

`safeupdate` is a simple extension to PostgreSQL that raises an error if UPDATE and DELETE are executed without specifying conditions. This extension was initially designed to protect data from accidental obliteration of data that is writable by PostgREST.

**Comment by dragarcia** [comment]
Hi @sandbox-apps 👋 

We do already have `safeupdate` installed in the underlying database. You can start using it by running the following in the `SQL` tab of the dashboard:
```
load 'safeupdate';
```

**Comment by sandbox-apps** [comment]
Thanks @dragarcia ! I will close this one. 💯

**Comment by sandbox-apps** [comment]
How can I know what are loadable extensions available to supabase?

**Comment by dragarcia** [comment]
You can check the loadable extensions over here:
https://supabase.io/docs/guides/database#full-list-of-extensions

Alternatively, the same list of extensions can be activated via your dashboard as well through:
`app.supabase.io/project/<insert_project_reference>/database/extensions`
