### ISSUE TITLE
No ability to create users or add storage items on self-hosted instance 

### ISSUE THREAD

**Issue by danielrosehill** [supabase/supabase#24902]
Installed Supabase onto a self-hosted instance (underlying server: Ubuntu Linux VPS, installation via Docker Compose).

**Behavior being experienced**

Not able to create any users or add storage. The create user screen hangs and the storage fails to upload.

**Attempted troubleshooting**

Checked access permissions on the main database and can verify that the following users have permissions on the `auth` schema in the main database (`postgres`):

-> `supabase_admin`
-> `supabase_auth_admin`
-> 'dashboard_user'

I also checked the `supabase-kong` container and verified that the following credentials have been configured as environment variables:

-> `DASHBOARD_USERNAME`
-> `DASHBOARD_PASSWORD`

**Comment by cyluss** [comment]
Are you using example .env file? If so you need to adjust `API_EXTERNAL_URL` and `SUPABASE_PUBLIC_URL` environment variables to your instance's ip address or hostname. URLs like `http://localhost:3000` will not work. This will solve storage upload failure.

I am not sure create user hang issue, but can you check out network tab in the devtools?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
