### ISSUE TITLE
Can't Select from Database CORS Blocked

### ISSUE THREAD

**Issue by 99freelancer** [supabase/supabase#2493]
Hello devs, I'm trying to select and fetch some sayings on my React App but I'm getting the following errors:

`Access to XMLHttpRequest at 'hhttps://mcubqowxrvpluqgzbcxi.supabase.co/rest/v1/saying?select=saying' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross-origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.` and, `browser-ponyfill.js:480 Uncaught (in promise) TypeError: Network request failed at XMLHttpRequest.xhr.onerror (browser-ponyfill.js:480)`

And this is the code:
```
import {useState, useEffect} from 'react';
import styled from 'styled-components';
import {supabase} from '../api/supabase';

const Container = styled.div`
height: 100vh;
display: flex;
justify-content: center;
align-items: center;`
const Quote = styled.h1`
width: 80%;
font-size: 3em;`

export default function Saying() {
    const [saying, setSaying] = useState();

    const get_new_quote = async () => {
        const data = await supabase
            .from('sayings')
            .select('saying')
        const random_saying = await data[Math.floor(Math.random() * data.length)];
        setSaying(random_saying.saying);
    };

    useEffect(() => {
        get_new_quote();
    }, []);

    return (
        <Container>
            <Quote>
                “{saying}”
            </Quote>
        </Container>
    )
}
```

**Comment by inian** [comment]
duplicate https://github.com/supabase/supabase/issues/2096
