### ISSUE TITLE
Light theme support for the code editor

### ISSUE THREAD

**Issue by elpnt** [supabase/supabase#2502]
# Feature request

Currently Supabase supports light and dark interface themes but the code editor only supports monokai (= dark).
It would be nice to be able to use a light theme such as Atom One Light for visibility and a more unified look.

**Monokai on light interface (Default)**
![Screenshot from 2021-07-23 14-59-43](https://user-images.githubusercontent.com/39664774/126743527-f26e4a93-90b8-48e5-bc93-b7d1c5081846.png)

**Atom One Light on light interface (Concept)**
![Screenshot from 2021-07-23 15-09-15](https://user-images.githubusercontent.com/39664774/126743717-cb0ad168-8103-40a9-a9c4-2611e2c9fbe7.png)

**Comment by arpitBhalla** [comment]
@Isaiah-Hamilton Can I work on this?

**Comment by Isaiah-Hamilton** [comment]
@arpitBhalla All yours!
