### ISSUE TITLE
Way to customize sender's name in the request new password

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#2506]
# Feature request

## Is your feature request related to a problem? Please describe.

If you request new password using Supabase authentication, the sender's name is coming from noreply. There is no way to edit it as needed. The issue here is that sometimes it's being considered as a spam or on our end, it can be considered as a phishing thing. 

## Describe the solution you'd like

It would be nice if the name will be coming from the organization or a real sounding name even if the email is noreply@mail.app.supabase.io.

## Describe alternatives you've considered

Just update the email body text to make it real or not a spammy or phishing email.

## Additional context

Here's what it looks like when we trigger a forget password:

![Screen Shot 2021-07-23 at 5 26 56 PM](https://user-images.githubusercontent.com/70461143/126763554-18cbbce3-62ca-4830-8f39-60b798f240be.png)

Thanks! 😊

**Comment by inian** [comment]
This should be configurable in the dashboard now @inbytesdevteam

**Comment by inbytesdevteam** [comment]
Thanks for this @inian. May I know where in the dashboard is it located? 

Currently looking at the Auth section of the project (general, users, policies, settings), there is no section to add 'Senders Name'?

**Comment by inian** [comment]
It is called SMTP senders name 
<img width="1081" alt="CleanShot 2021-08-08 at 20 19 41@2x" src="https://user-images.githubusercontent.com/2155545/128631747-3ca6d8b6-01de-4711-8d69-5b5b3bef71f9.png">

**Comment by inbytesdevteam** [comment]
Hi Inian, saw this. Thanks. 
I tried enabling custom SMTP and it seems like if we decided to use this, we need to add in our host, port, user, password. Not just changing the Sender's Name. Is this correct?

**Comment by kiwicopple** [comment]
That's correct @inbytesdevteam - you'd need to provide your own (complete) SMTP settings

**Comment by edwin177** [comment]
It looks like the SMTP Sender Name is being ignored. I just tried it with my Google account (custom domain) and the sender shows as:

`${email} <${email}>`
