### ISSUE TITLE
Copy User UID button not working

### ISSUE THREAD

**Issue by malliaridis** [supabase/supabase#2523]
# Bug report

## Describe the bug

When trying to copy the UID via the UI button "COPY" it does not copy the value in the clipboard.

## To Reproduce

1. Go to Project's Authentication -> Users (https://app.supabase.io/project/[PROJECT_ID]/auth/users
2. Click on "COPY" button on an existing user's UID
3. Try to paste the value somewhere

## Expected behavior

It is expected that the UID is successfully copied to the clipboard on click.

## Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/33470669/126869077-d6297d0e-ec22-4a4d-9b0e-5a94788772c5.jpg)

## System information

- OS: Windows 10
- Browser: Chrome
- Version of supabase-js: _(where to look this up?)
- Version of Node.js: (where to look this up?)

_P.s. the copy button is not aligned vertically in the center of the field._

**Comment by inian** [comment]
Hi @malliaridis, thank you for reporting this issue. 

We noticed this too and have fixed it internally and should be deployed by Monday. Please reopen if you are still facing the issue.
