### ISSUE TITLE
PostgREST endpoints DNS not resolving over ipv6

### ISSUE THREAD

**Issue by lukejgaskell** [supabase/supabase#2529]
# Bug report

## Describe the bug

When logging in or querying endpoints with the JavaScript SDK connections that only support ipv6 do not resolve. 

## To Reproduce

1. Connect via a network that only supports ipv6 (or fake it).
2. Try to use auth endpoints (sign in with google) or select queries via the JavaScript SDK.

## Expected behavior

I expect the requests to resolve the DNS.

## System information

- OS: IOS, Windows
- Browser: Chrome/ Safari
- Version of supabase-js: 1.18.1
- Version of Node.js: 14.x

**Comment by inian** [comment]
HI @lukejgaskell, that's right. We only publish A record for our project and not a AAAA record. May I ask what your usecase is? Are there networks which are not able to resolve IPv4 addresses? I am assuming majority of the internet would be broken in those networks
```
nslookup -type=AAAA amazon.com
Server:		192.0.2.42
Address:	192.0.2.42#53

Non-authoritative answer:
*** Can't find amazon.com: No answer
```

**Comment by lukejgaskell** [comment]
Hey @inian thanks for your response. After reading through some of the other issues you have out, I think this could also be related to the xfinity problem more than ipv6 only networks.
