### ISSUE TITLE
Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by ajoslin103** [supabase/supabase#2531]
Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections

intermittent this afternoon (7/24/21)

now nearly DOA

nothing shows up as a problem on your status page...

**Comment by kiwicopple** [comment]
Hey @ajoslin103 - this happens when you have too many open connections to your database. Are you using a Serverless environment that is opening too many connections? If so, can:

- Use our API, not a direct connections (our API has connection pooling)
- Use the Connection Pooler: https://supabase.io/docs/guides/database/connecting/connection-pooling

If those don't work, could you please share more about your setup to help us debug?

**Comment by ajoslin103** [comment]
Hi there & thanks for the info

I’m using the RedwoodJS jamstack so much of the heavy lifting is done for me

All I had to do was issue a cli command to use supabase for authentication and there you were for database too

https://redwoodjs.com/docs/authentication#supabase

It installed the PrismaClient and set it up like this:

export const db = new PrismaClient({
  log: emitLogLevels(['info', 'warn', 'error']),
})


And they configured schema.prisma like this 

datasource DS {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  binaryTargets   = "native"
  previewFeatures = ["selectRelationCount"]
}

it looks like supabase connection pooling is just arrived

https://redwoodjs.com/docs/connection-pooling.html <https://redwoodjs.com/docs/connection-pooling.html>

no, I’m not using pooling just yet — but I’ve put it on the punchlist

Thanks!

we can close this ticket

**Comment by kiwicopple** [comment]
Cool! Definitely use connection pooling with Redwood since it uses Serverless behind the scenes. Good luck building!

**Comment by kiwicopple** [comment]
There is a great article here which explains how/when to use the differnent connections with Prisma/RW:
https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505
