### ISSUE TITLE
Add delete multiple rows example with .delete().in()

### ISSUE THREAD

**Issue by damien-schneider** [supabase/supabase#25361]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/delete?queryGroups=example&example=delete-records

## Describe the problem

An example of how to delete multiple rows with one request is missing

## Describe the improvement

Adding an example with multiple row to delete with a filter in() for example would be a great documentation improvment as it is hard to find how to achieve it when you are starting with Supabase

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by ynnsuis** [comment]
Hi! @charislam, I am sossost, a new contributor. Can I solve this problem??

**Comment by charislam** [comment]
Yes @ynnsuis, of course! Would love your help. Here is where the examples are written: https://github.com/supabase/supabase/blob/master/apps/docs/spec/supabase_js_v2.yml

Let me know if you need anything!

**Comment by sossost** [comment]
@charislam oh! thank you @ynnsuis is my company account. so i'll solve this issue at this account.

**Comment by itz-salemm** [comment]
This issue should be closed since it has been solved and merged.
