### ISSUE TITLE
Weird Behaviour on Storage Dashboard

### ISSUE THREAD

**Issue by jyoo** [supabase/supabase#2537]
# Bug report

## Describe the bug

I have tried to move one file out of a directory in a bucket, but I have encountered this bug.

https://user-images.githubusercontent.com/37724247/126887547-6c7a5e99-dff4-4234-ad52-a4fdeb742a7f.mov

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
- Go to Storage on the dashboard
- (If you do not have any similar structure shown in the video) create a bucket, one directory inside of the bucket and upload one file inside of the folder
- Right click the file and press the move button
- Enter `/` as its destination path

## Expected behavior

Probably I entered the wrong path because I am new here, but I thought entering `/` as its destination path allowed me to move files from inside of a folder to the root of the bucket.

## Screenshots

It is attached above.

## System information

- OS: macOS
- Browser (if applies) Safari
- Version of supabase-js: Not applicable
- Version of Node.js: Not applicable

**Comment by joshenlim** [comment]
Hey there @jyoo! Great catch on this - to move your files to the root of the bucket, you'll just need to leave the field blank and hit "Move files".

On that note, I do realise that it's very unclear how to go about moving files to the root of the bucket - we'll push out a tweak to improve this UX!
