### ISSUE TITLE
An error occurred with your deployment and 'The upstream server is timing out'

### ISSUE THREAD

**Issue by 0hq** [supabase/supabase#2547]
### Discussed in https://github.com/supabase/supabase/discussions/2545

<div type='discussions-op-text'>

<sup>Originally posted by **0hq** July 25, 2021</sup>
Have a large DB (2.5 M rows) and trying to query by unique id and timestamp.
Any medium request creates An error occurred with your deployment in the SQL editor and 'The upstream server is timing out' from supabase-js.

Seems like a supabase error since query is formatted correctly and the request is what's failing. Queries work fine for other smaller tables.</div>

**Comment by kiwicopple** [comment]
Hey @0hq - are you:

1. trying to return all 2.5M rows at once? That could be an issue for the payload size.
2. or are you just querying the table to get a smaller set of rows?

If it's `1`, you can add pagination and return a smaller set
if it's `2`, make sure you have [indexes set up on](https://www.postgresqltutorial.com/postgresql-indexes/postgresql-multicolumn-indexes/) your tables. 

```
create index index_name
on table_name(id, some_timestamp);
```

**Comment by 0hq** [comment]
Was just an index issue - wasn't trying to query 2.5 m haha.
