### ISSUE TITLE
Connection pool database not found

### ISSUE THREAD

**Issue by mattpocock** [supabase/supabase#2560]
# Bug report

## Describe the bug

I can connect to my supabase postgres db via port 5432, but not port 6543. This _is_ working on another project of mine, but not on another. I have enabled connection pooling on both projects.

## To Reproduce

Unsure what is causing this. The project id is which is not working is `ascelcgzufjyvdzuplwo`. The one that is working is `owxhbmonbfrgnegwprcq`. Their setups are identical.

## System information

I'm connecting via Prisma - but I feel this is unlikely to be causing an issue as I'm able to connect OK to one project, but not another.

**Comment by dragarcia** [comment]
Hi @mattpocock 👋 

Looking into this!

**Comment by dragarcia** [comment]
@mattpocock I just restarted the PgBouncer service for your project with the ref `ascelcgzufjyvdzuplwo`. Would you mind trying to connect to it again via port `6543`?

**Comment by dragarcia** [comment]
Agreed. Glad it's working and thanks for the feedback!
