### ISSUE TITLE
Impossible auth to supabase dashboard

### ISSUE THREAD

**Issue by lucas-jacques** [supabase/supabase#2568]
# Bug report

## Description

I was working on an app with supabase backend. My session timed out so i tried to login again. But it's impossible. When i click on "Sign in"  it refresh the page and nothing more.

## To Reproduce

I don't no if you can reproduce this but :
1. Work on supabase Dashboard (app.supabase.io)
2. Be disconnected ("Your session has timed out.")
3. Never come back (it was impossible to come back for me)

Console: Failed to load resource: the server responded with a status of 401 ()

Remove all cookies change nothing.
I tried with another network (cellular) and another device but it doesn't change anything. Is it a problem with my github account authentication ?

**Comment by Fischer1122** [comment]
Exact same problem, tried on multiple browsers.

**Comment by 72L** [comment]
Same problem. Tried with incognito browser. Also tried with another account in another browser.

**Comment by inian** [comment]
We are looking into this now

**Comment by 72L** [comment]
I was able to log in using a VPN in Singapore. The only other country I tried was USA, and it did not work.

**Comment by kiwicopple** [comment]
We've isolated the problem to ECS. we're pulling up some alternative middleware to circumvent the issue. More udpates soon

**Comment by 72L** [comment]
Singapore no longer works for me. I've tried Hong Kong and New Zealand as well

**Comment by louisbarclay** [comment]
I also am hitting an issue logging in. 500 on the /api/profile endpoint.

![image](https://user-images.githubusercontent.com/21208811/127015932-3c56ac3d-a36a-4ee2-9d26-99f7f496eef9.png)

Response:

`{"message":"invalid json response body at https://readonly.supabase.io/rest/v1/users?select=id%2Cauth0_id%2Cprimary_email%2Cusername%2Cfirst_name%2Clast_name%2Cmobile%2Cis_alpha_user%2Corganizations%28id%2Cslug%2Cname%2Cbadge%2Cproject_limit%2Cstripe_customer_id%2Cbilling_email%2Cstripe_customer_object%2Cprojects%28id%2Cref%2Cname%2Cstatus%2Corganization_id%2Cinserted_at%2Csubscription_id%2Cdb_user_supabase%2Cdb_host%2Cdb_pass_supabase%2Cdb_ipv4%2Cdb_port%2Cdb_name%2Cdb_ssl%2Cinfrastructure_config-%3E%22cloud_provider%22%2Cinfrastructure_config-%3E%22region%22%2Cservices%28infrastructure%28app_versions%28version%29%29%29%29%29&auth0_id=eq.github%7C21208811&organizations.status=neq.REMOVED&organizations.projects.status=neq.GOING_DOWN&organizations.projects.status=neq.REMOVED&organizations.projects.services.status=neq.REMOVED&organizations.projects.services.infrastructure.status=neq.REMOVED reason: Unexpected token < in JSON at position 0","type":"invalid-json"}`

**Comment by inian** [comment]
Things should be back up now. We will post a more detailed update on our [status page](https://status.supabase.io/) later on.

**Comment by lucas-jacques** [comment]
There is a new issue: infinite loading.

![image](https://user-images.githubusercontent.com/79991728/127022511-c84caeae-2f45-4e43-bcbc-59b2db5c085a.png)

**Comment by GermainMichaud** [comment]
I have the exact same issue today. 
Same issue on different device and browser.

**Comment by Shivansh-yadav13** [comment]
@inian 
I'm facing the same issue, but when I'm on localhost it works but the deployed version does not work and I get 
`Failed to load resource: the server responded with a status of 401 ()`

**Comment by LucaPizzagalli** [comment]
@inian 
Same for me today. I'm trying to log-in (from Thailand) at https://supabase.com/dashboard/sign-in but all I get is `Failed to load resource: the server responded with a status of 401 ()` in the console
