### ISSUE TITLE
Allow import of existing data and autogenerated primary key in UI

### ISSUE THREAD

**Issue by jsjoeio** [supabase/supabase#2572]
# Feature request

## Is your feature request related to a problem? Please describe.

As a user, I would like to be able to import existing data into a spreadsheet and also have supabase autogenerate a primary key for that data. 

https://user-images.githubusercontent.com/3806031/126906529-799f3264-21ed-44e8-b7d5-9c266433032b.mp4

_Originally asked [on Twitter](https://twitter.com/jsjoeio/status/1419315208422453249?s=20), cross-posting here_

## Describe the solution you'd like

When I add existing data to a table from the UI, I should see an option to chose one of the existing data columns as the primary key OR have an option in that dropdown to select an autogenerated primary key (like you can when you don't import existing data).

## Describe alternatives you've considered

1. paste data (without ID)
2. add the column after using the SQL editor

```sql
alter table 
  table_name
add column id 
  serial primary key;
```

## Additional context

[Originally posted on GitHub Discussions](https://github.com/supabase/supabase/discussions/2543)

**Comment by joshenlim** [comment]
hey @jsjoeio! we've pushed out a couple of fixes and improvements to the table editor - you should now be able to have more control over the columns from your imported data.

After importing your data, the side panel will now allow you to individually configure the columns imported (except their names) as such:

<img src="https://user-images.githubusercontent.com/19742402/135040290-fdd052b3-a6d6-4431-9d25-7570d750100b.png" width="500" />
