### ISSUE TITLE
Converting Anonymous users to regular users isn't working

### ISSUE THREAD

**Issue by gitnik** [supabase/supabase#25787]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Converting anonymous users to full users as per the documentation (https://supabase.com/docs/guides/auth/auth-anonymous#convert-an-anonymous-user-to-a-permanent-user) is not working. Calling `signInAnonymously` does not seem to set a session resulting in an error when trying to "upgrade" the user by linking the identity (settting the email).

This doesn't work locally or on production so I don't think it's a config issue.

## To Reproduce

```ts
const { data: login, error: loginError } = await supabase.auth.signInAnonymously();

// this throws 'AuthSessionMissingError: Auth session missing!'
const { data: user, error: userError } = await supabase.auth.updateUser({ email: 'foo@bar.com' });
```

## Expected behavior

As per the documentation I would expect to get a regular user with that email.

## System information

- Version of supabase-js: 2.43.1
- Version of supabase: 1.165.0
- Version of Node.js: 20

**Comment by r-southworth** [comment]
Are you trying to update the user on your server vs on the client? I can get this error when I try the updateUser when I am on the server because the session is stored in localStorage.

**Comment by encima** [comment]
Thanks @r-southworth, the call you mention is by design as this existed before anonymous users and is used in other user update operations. The method in the docs is the way to create a user from anonymouse

**Comment by r-southworth** [comment]
Yes I know that. I was trying to troubleshoot where the user was having issues because I can't reproduce. I'm using anonymous users and update user works just fine - the only way I've managed to get the posted error is trying to call the method from the server which returns that error (as expected) since there isn't a session on the server.

**Comment by r-southworth** [comment]
@encima Sorry I think I mis-read your comment this morning are you saying `supabase.auth.admin.updateUserById` is not supposed to convert a user from Anonymous to Email if you assign an email with email_confirm = true? If so why is that the design? How can a user be converted from anonymous to email without sending a confirmation email and without turning off email confirmation completely?

**Comment by encima** [comment]
> @encima Sorry I think I mis-read your comment this morning are you saying `supabase.auth.admin.updateUserById` is not supposed to convert a user from Anonymous to Email if you assign an email with email_confirm = true? If so why is that the design? How can a user be converted from anonymous to email without sending a confirmation email and without turning off email confirmation completely? 

That might be a separate discussion :) 
Converting anonymous to user is done as you said, using the client side. The server side call is for generally updating a user (changing not just the email).

**Comment by r-southworth** [comment]
@encima new issue opened https://github.com/supabase/supabase/issues/25846#issue-2283752702 if you want to take a look.

**Comment by r-southworth** [comment]
@gitnik I can't reproduce with supabase-js 2.42.0 or 2.43.1

**Comment by gitnik** [comment]
If I execute the updateUser call on the client, it works as expected. This was not clear to me from the documentation.

**Comment by OmarGoubail** [comment]
I am running into an issue, that I am not sure is related or not, but I am using anonymous users on the server and they work as you'd expect, but I can't convert them to permanent user, using otp. The otp is always expired or is invalid, and i've made sure it's correct multiple times.

signing up normally works with otp.

Also I tried on the client and still have the same problem or is there something I am missing?

So far I am signing in anonymously on the server,  updating on client and verifying the token on the client using supabase ssr, I also tried with the supabase-js with no ssr but still doesn't work.

**Comment by r-southworth** [comment]
@OmarGoubail I think you might need to do something with linked identities to get Otp to work. Like sign up the user with otp then call a manual link method to combine that with the anonymous user - but that isn't really covered in the docs at this point so I am not entirely sure

**Comment by OmarGoubail** [comment]
@r-southworth Thanks for the quick reply, I wanted to to confirm all possible methods before replying. 

Manual linking doesn't work like that as far as I can tell, it need oAuth, and I am trying to authenticate using email only. 

My problem, which I am more confident now is a bug, is that otp is always expired or incorrect when using anonymous sign-ins. So far I've tried normal sign up in which otp works normally. I've tried using admin method to confirm email then re authenticating but otp is always expired. if I use {{ .ConfirmationURL }} with update user, then user is converted with no problems.

So I can't convert anonymous with otp in all cases I am aware of, I am hoping it's something am missing. So will open a detailed issue when I can.

**Comment by r-southworth** [comment]
Did you try a combo of signing up with otp then updateUser on the anonymous user with the same email? If I understand automatic linking correctly (which is dubious - but best guess anyway) then once the anonymous user confirms their email the otp user and the now not-anonymous user should get merged.

**Comment by OmarGoubail** [comment]
@r-southworth If I understand you correctly. First you sign-in anonymously then you sign up without pushing a cookie correct? then afterwards you just update the email with auth.updateUser(), and they will be automatically linked. But wouldn't that have the same problem because updating user requires an otp verification which will be also expired or incorrect?

**Comment by VValiente** [comment]
Hello, how should we convert an anonymous user to a permanent user with their password? 

At app launch, if no user is found, the app signs the user anonymously and I'm saving some onboarding data under their anonymous id. Then at the end part of the onboarding, the app asks them to create an account. If they choose to create an account with email and password, what should be the proper steps to link the email and password?

Calling 
```
let user = try await authClient.update(user: UserAttributes(email: email, password: password), redirectTo: nil)
```
throws the following error:
```
api(Auth.AuthError.APIError(msg: Optional("Updating password of an anonymous user is not possible"), code: Optional(422), error: nil, errorDescription: nil, weakPassword: nil))
```

I tried to first update just the email but the `user.isAnonymous` remains `true`. Please advise, because I can't find this info in the documentation about converting anonymous users.

I'm on Supabase 2.17.0 for iOS (https://github.com/supabase/supabase-swift.git)

**Comment by Chippd** [comment]
@OmarGoubail did you figure this out? Bumping into this myself. 

I authenticate anonymously initially, and then let the user enter an email to de-anonymise themselves. 

Clicking the link in the email works but the OTP flow fails every time with an expired/incorrect error. Just updated to `"@supabase/supabase-js": "^2.47.13",` but to no avail.

**Comment by OmarGoubail** [comment]
@Chippd I wish I could help, but I never figured this out actually and had to work around it.

**Comment by DanLang1** [comment]
I also ran into the issue of the verify OTP failing due to an expired error for anonymous users. For me just changing the type from 'email' to 'email_change' on the verifyOtp call fixed the issue.
