### ISSUE TITLE
Create Java or Kotlin Android Library ?

### ISSUE THREAD

**Issue by io-Karim-developer** [supabase/supabase#2580]
**Add Android sdk library** 
please help me 

- [ ] kotlin 
- [ ] java

or how I can use Supabase with  `Retorfit` https://square.github.io/retrofit/

**Comment by kiwicopple** [comment]
Hey @io-Karim-developer - we have a Discussion thread here where we're tracking votes for new client libraries.

https://github.com/supabase/supabase/discussions/5

I'll close this -  feel free to add your votes to any of the libs in that thread ✅
