### ISSUE TITLE
Missing client in Prisma docs

### ISSUE THREAD

**Issue by oasaleh** [supabase/supabase#25847]
I think these lines should be included

```prisma
generator client {
  provider = "prisma-client-js"
}
```

In here,
<img width="1007" alt="image" src="https://github.com/supabase/supabase/assets/56449814/2e8d39ad-5a25-40bc-a1b7-89a12af5b749">

**Comment by encima** [comment]
This is open to discussion for sure! Thanks for opening. 
The connection strings here are the core components needed to get started using those tools/frameworks.

The `generator` is often used but is not essential and some may not be using the prisma generator (i.e. community tools)

**Comment by oasaleh** [comment]
Interesting.. Can you elaborate more on how to use Prisma without the `generator`?

**Comment by encima** [comment]
Sure, the docs are [here](https://www.prisma.io/docs/orm/prisma-schema/overview/generators) so there are community generators.

**Comment by oasaleh** [comment]
No sure what that means. The docs say "one or more".

**Comment by encima** [comment]
Feel free to open a PR to include it if you feel it is needed for the majority of use cases!

**Comment by oasaleh** [comment]
Thank you. Here [it is](https://github.com/supabase/supabase/pull/26269).
