### ISSUE TITLE
Wrong URL in storage bucket guide

### ISSUE THREAD

**Issue by J3ykob** [supabase/supabase#25866]
# Improve documentation

## Link 

[Image Transformations - NextJs loader](https://supabase.com/docs/guides/storage/serving/image-transformations#nextjs-loader)

## Describe the problem

The URL in the code snippet is pointing to an old file storage url.

## Describe the improvement

it should be changed like so:
`https://${projectId}.supabase.co/storage/v1/render/image/public/${src}?width=${width}&quality=${
    quality || 75
  }`
to
`https://${projectId}.supabase.co/storage/v1/object/public/${src}?width=${width}&quality=${
      quality || 75
    }`

**Comment by uniqueeest** [comment]
hello @encima,  Can I solve this problem?

**Comment by encima** [comment]
Go for it, please open a PR and mention this issue :D
