### ISSUE TITLE
There is a problem with the steps of edge function deployment documentation

### ISSUE THREAD

**Issue by Wangtaofeng** [supabase/supabase#25870]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/guides/functions/deploy)

## Describe the problem

Execute `supabase link` before executing the `supabase projects list`  command, otherwise an error will occur.

## Describe the improvement

![image](https://github.com/supabase/supabase/assets/73595134/6b07988c-8394-4fca-ae34-49466f83e0e3)

**Comment by encima** [comment]
Hey there, thanks for opening!
No need to worry, this is not an error; just information that the current supabase project is not linked. The command itself still completes and this is added as info.
Would you prefer that this info was suppressed/not printed?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
