### ISSUE TITLE
Twitter external provider (Error getting user email)

### ISSUE THREAD

**Issue by Ahmed14z** [supabase/supabase#25874]
# Bug Report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The Twitter OAuth provider is not functioning correctly on both localhost and hosted environments. Similar to a previously documented issue where Twitter OAuth operates on hosted instances but fails on localhost, in my case, the provider fails in all environments.

## To Reproduce

1. Set up Twitter OAuth on local development server (e.g., http://localhost:8000).
2. Configure the `supabase.auth.signInWithOAuth` method.
3. Ensure the Twitter provider has the correct redirect URI configured in the Twitter developer portal.
4. Attempt to sign in using the `signInWithOAuth` method and observe the error on the redirect page: `error=server_error&error_code=500&error_description=Error+getting+user+email+from+external+provider#error=server_error&error_code=500&error_description=Error+getting+user+email+from+external+provider`.

## Expected behavior

I expect the Twitter OAuth provider to allow users to sign in successfully, creating a user session without issues, in both development and production environments.

## System information
- Version of supabase-js: `^2.39.3`
- Version of Node.js: `^10.9.2`

## Additional context

This issue appears on both local development and hosted setups, unlike the other issue where it was restricted to local development only.

**Comment by encima** [comment]
Hey there, 
thanks for opening!
Can you confirm that you are requesting emails from users in your app in Twitter/X? 
![image](https://github.com/supabase/supabase/assets/517923/bbb352d1-08af-4258-8b6a-db2d59808b80)

**Comment by simonha9** [comment]
Hi, I am unable to repro this, following the guide [here](https://supabase.com/docs/guides/auth/social-login/auth-twitter?queryGroups=environment&environment=server#overview) doing a full pkce flow,

**Comment by Ahmed14z** [comment]
Yes as @encima described it worked when i enabled it , thanks!
