### ISSUE TITLE
supabase-vector (vector.yml)

### ISSUE THREAD

**Issue by EasternIndustries-IT** [supabase/supabase#25905]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Setting up new supabase instance in ubuntu 22.04 using the most recent docker-compose I get an error
`supabase-vector                 | 2024-05-08T19:02:48.897393Z  INFO vector::app: Loading configs. paths=["etc/vector/vector.yml"]`
looking deeper it looks like it created a folder in /volumes/logs/vector.yml/ 
on my other docker instances in windows it creates a file vector.yml
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Clear docker containers, images , prune images, then run docker-compose up from a directory with only a compose file in it.

## Expected behavior

no errors

## Screenshots

![error1](https://github.com/supabase/supabase/assets/57259898/ce9a1701-dca5-4be1-96a8-355fa18fa0ae)

## System information

- OS: ubuntu 22.04

## Other information
Even if I can get it to work by copying a vector.yml from my other instance i get supabase_admin has no password assigned upon docker-compose up

**Comment by encima** [comment]
Hey there, this is a docker issue that seems to be getting more common!
Is your Ubuntu machine running on ARM or x86?

If you provide the valid path, I would also tear everything down, remove cached volumes and make sure you are starting from scratch. Let us know how that goes!

**Comment by EasternIndustries-IT** [comment]
> Hey there, this is a docker issue that seems to be getting more common! Is your Ubuntu machine running on ARM or x86?
> 
> If you provide the valid path, I would also tear everything down, remove cached volumes and make sure you are starting from scratch. Let us know how that goes!

I am using an ubuntu 22.04 x64 on and intel processor. Everything is updated to the latest as of 05.06.2024.

**Comment by encima** [comment]
yep, this will happen when you the processor is x64 as the build is different than the image architecture. You can use `buildx` to cross compile it as well if you like.

See this image [here](https://github.com/supabase/supabase/issues/23132) for the same.

**Comment by EasternIndustries-IT** [comment]
> yep, this will happen when you the processor is x64 as the build is different than the image architecture. You can use `buildx` to cross compile it as well if you like.
> 
> See this image [here](https://github.com/supabase/supabase/issues/23132) for the same.

 I am not quite sure on how to do that with a docker compose file. I tried adding a platform: linux/x86_64 but i still get the same issue. I'm also unsure of what platform this is built on.

**Comment by jasper-at-windswept** [comment]
I have the same issue running NixOS 24.05.

What doesn't make sense is i got this to work with no issues, but then I reinstalled my system and now I get this problem described at the top.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by PierreMesure** [comment]
Same issue with Ubuntu 22.04 and latest versions of Supabase.
