### ISSUE TITLE
[Storage RLS] the "name" variable is replaced by another table's "name" column

### ISSUE THREAD

**Issue by ouvreboite** [supabase/supabase#25992]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm building a image storage system, and I'm setting up a RLS. A user can only access images of a task if they have created the project containing the tasks. 

My tables look like that:
- **Projects**: id, created_by, ...
- **Tasks**: id, name, project_id, ...
My bucket looks like that:
- **tasks_images**:
  - /taskid1(one folder per task)
    - /file1
    - /file2
  - /taskid2 
    - /file3

My storage RLS
```sql
create policy "User must be the creator of the project to access a tasks images"
on "storage"."objects"
as permissive
for select
to public
using (
  bucket_id = 'tasks_images'
  AND auth.role() = 'authenticated'
  AND EXISTS (
    SELECT 1
    FROM tasks task JOIN project proj ON proj.id = task.project_id
    WHERE task.id::text = (storage.foldername(name))[1]
    AND proj.created_by = auth.uid()
  )
);
```

Here, I'm using  `WHERE task.id::text = (storage.foldername(name))[1]` as I'm creating a subfolder for each task.

The problem: when I create this RLS (either by applying a migration or using the studio), it gets **rewritten**. When I view it (or query directly pg_policies), the condition is changed to:

```sql
using (
  bucket_id = 'tasks_images'
  AND auth.role() = 'authenticated'
  AND EXISTS (
    SELECT 1
    FROM tasks task JOIN project proj ON proj.id = task.project_id
    WHERE task.id::text = (storage.foldername(task.name))[1] --🐛 task.name instead of name
    AND proj.created_by = auth.uid()
  )
);
```

I look like some optimization step is thinking "table Tasks has a 'name' column, so this 'name' variable must be that". 

## Expected behavior

- The 'name' variable in storage RLS should not be changed to match an existing table's column
- Is there a more strongly type alias for the 'name' variable ?

## System information
- supabase version: 1.165.0 (via npx)

**Comment by GaryAustin1** [comment]
It is reflecting what Postgres will do with your SQL.  As it is in a select all non table.column references are assumed to belong to the table being selected.  You need to  prefix it with objects.name I'm pretty sure.

**Comment by dikshantrajput** [comment]
@ouvreboite The name column is residing where? It is part of which table. You need to mention that i.e. `objects.name`

**Comment by ouvreboite** [comment]
I confirm that using explicitly `objects.name` work well :) 

It could be nice to update the policy examples in the [documentation](https://supabase.com/docs/guides/storage/security/access-control#policy-examples) to uses objects.name (or even to explicit that the fields from the `storage.objects` tables are accessibles during the evaluation of the RLS

**Comment by smaldd14** [comment]
> I confirm that using explicitly `objects.name` work well :)
> 
> It could be nice to update the policy examples in the [documentation](https://supabase.com/docs/guides/storage/security/access-control#policy-examples) to uses objects.name (or even to explicit that the fields from the `storage.objects` tables are accessibles during the evaluation of the RLS

I ran into this issue and using `objest.name` solved it for me aswell. After > 1 hour of trying to debug what was going on.

Docs should be updated to explicitly say that you must use objects.name if table in question already has a 'name' column
