### ISSUE TITLE
supabase-js: match().update() not a valid combination

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#26]
was expecting 
```javascript
      supabase
        .from('messages')
        .match({ id: 1 })
        .update({ message: 'updated message yo' })
        .then(console.log)
        .catch(console.error)
```
to update, but instead got:
```javascript
{
  body: null,
  status: 400,
  statusCode: 400,
  statusText: '.update() cannot be invoked without any filters.'
}
```

**Comment by kiwicopple** [comment]
@dragarcia Could you please look into this one?

**Comment by dragarcia** [comment]
### Reasoning
Based on [Superagent Documentation](https://github.com/visionmedia/superagent/blob/master/src/node/index.js), this.query has two different ways of processing the parameters; one for string and one for the rest. While all our other functions (.filter(), .order()) input a string as a parameter, .match() inputs an object. Decided to standardise everything and have all functions input a string.

**Comment by dragarcia** [comment]
Changes done in https://github.com/supabase/postgrest-js/commit/07557c62323bc1eccf15db645340c1bdc70dd093.
