### ISSUE TITLE
New project database password 

### ISSUE THREAD

**Issue by joaomcs** [supabase/supabase#2609]
# New project database password 

## Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/50199403/127317367-256c6272-adbc-4efd-b82a-65313c9be04c.jpg)

The password used was:  (6Pz3D-EG=>XSc(^XH}U

## System information

- Windows 10
- chrome, Edge

**Comment by inian** [comment]
Lets discuss here https://github.com/supabase/supabase/issues/2696
