### ISSUE TITLE
Can't add new custom queries in SQL Editor

### ISSUE THREAD

**Issue by amdervis** [supabase/supabase#26118]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On supabase self-hosted with docker on windows, when trying to create a new query in SQL Editor, it creates a new query called 'Untitled query', after trying to run the query I get 'Failed to generate title error'. 

[id]-d06633d21480ddeb.js:1 Uncaught (in promise) {code: 500, message: '<!DOCTYPE html><html lang="en"><head><meta charSet…[32757],"scriptLoader":[]}\x3C/script></body></html>', requestId: '9e9ed0fa-e5d7-4490-84e9-f0a0c760f818'}

I can't find anywhere to change the title from 'Untitled query'

Even when using templates or quickstarts, then the query runs fine but after reload the query goes away from 'Your Queries'.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'SQL Editor'
2. Click on 'New query'
3. Write some SQL query and click on 'Run' or CTRL + ENTER

## Expected behavior

I expected that I could have a bunch of custom SQL Queries saved and ready to reuse,.

## Screenshots

![image](https://github.com/supabase/supabase/assets/24221639/ddd9b46e-4fbc-4a58-8e4a-01c750bf7e79)

## System information

- OS: [Windows/Docker]
- Browser : Chrome
- Clean installed using your documentation on how to self host Supabase with Docker.

**Comment by encima** [comment]
Hey @amdervis , this issue is already being tracked here #17941 so I will close this one to keep the discussion there
