### ISSUE TITLE
No way to resend verification email

### ISSUE THREAD

**Issue by rphly** [supabase/supabase#2613]
# Bug report

## Describe the bug

Confirmation token expires, so will require a way to resend verification email. (I swear it was there before) but now it has disappeared.

![Screenshot 2021-07-28 at 8 44 53 PM](https://user-images.githubusercontent.com/23185489/127324197-2110d383-f353-4715-a03f-40c304b7765d.png)

**Comment by kiwicopple** [comment]
duplicate of https://github.com/supabase/gotrue/issues/312
