### ISSUE TITLE
Postgres user unable to alter tables created with the Dashboard

### ISSUE THREAD

**Issue by mcmx** [supabase/supabase#2618]
# Bug report

## Describe the bug

Unable to ALTER TABLE in the public schema when using the postgres user and a SQL client, the returned error is:

"ERROR:  must be owner of table {table_name_here}"

**This happens for tables created using the Dashboard**

## To Reproduce

1. Go to the Supabase dashboard and create a any table called **_test_table_** with id automatically increment.
2. Connect to your supabase database from psql in your computer or any other DB application, using the "Connection String" found in Settings / Database and the postgres password used to create the project.
3. In the SQL client type:

```
ALTER TABLE public.test_table 
ADD COLUMN phone VARCHAR;
```

4. See error similar to:

> ERROR:  must be owner of table test_table

## Expected behavior

The postgres user is able to alter tables in the public schema

## System information

This is system agnostic as this was tested using Beekeeper Studio and confirmed by luisfelipe in Discord using a SQL client.

## Additional context

I tested this with a new DB created today, I ignore if the same happens with older databases.

**Comment by TheCoinPerspective** [comment]
This is affecting us as well. I created some tables on Supabase via the dashboard, and can browse them fine on a GUI client (e.g. Postico), but cannot run any ALTER statements on any of them. Is there an official guidance on how to manage this or a query that can be run to re-assign ownership?

**Comment by kiwicopple** [comment]
There is a workaround here: https://github.com/supabase/supabase/discussions/2495 although this should be very temporary and only if you really need it.

We were a bit hasty with the security restrictions in the last Launch Week and are working on the correct permission model now. What we have now is safe, and we'll revise to ensure all of the functionality works

**Comment by mcmx** [comment]
Thanks @kiwicopple, mainly wanted this to have visibility to the team, due to how Supabase handles permissions having postgres as superuser, may have adverse effects on other parts of the system.

**Comment by victor-cano** [comment]
Thanks @kiwicopple , do you know if using that workaround you mentioned could cause an issue?

**Comment by GaryAustin1** [comment]
This should no longer apply with new instances and those with this security patch https://github.com/supabase/supabase/discussions/9314 as the postgres user is now used for both the dashboard/SQL editor and for 3rd party tools.
Please feel free to generate a new issue if there are problems with the new approach.
