### ISSUE TITLE
Schema Exposure is ignored in local Supabase / Local Dev / CLI

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#26194]
# Bug report

## Describe the bug

Change `[api].schemas` to be without `public`, same for `extra_search_path`.
After a completely fresh startup (deleted previous volume etc) it will not respect that setting and still expose the schema as part of running opening the REST API: `http://127.0.0.1:54321/rest/v1/`

## Expected behavior

When the `public` schema is removedfrom the exposed API schemas, REST API should not list data bout it anymore.

## Screenshots

<img width="558" alt="image" src="https://github.com/supabase/supabase/assets/9058762/6fea59e9-3b31-4162-a0bd-e474b8d8d7a6">

`/comments` shouldn't be here.

## System information

- macOS
- CLI Version 1.165.0

**Comment by encima** [comment]
Hi there, thanks for opening!

The docs here may not be super clear but the summary of this is:
- `public` and `storage` are [always](https://supabase.com/docs/guides/cli/config#api.schemas) included (even when the config is set)
- This config parameter is for exposing additional schemas

If you would like to open a PR to make this clearer in the docs, please do!
Or anyone can start a discussion to see if this is something we could support in the self-hosted version.
