### ISSUE TITLE
[auth] Additional Redirect URLs outside of Site URL not supported

### ISSUE THREAD

**Issue by mattpocock** [supabase/supabase#2623]
# Bug report

## Describe the bug

I'm trying to allow for testing auth both on localhost and my domain. When I log in via GitHub, I'm always redirected to the Site URL, not the redirect URL's I've allowed. I'm passing `redirectTo: window.location.href` into `auth.signIn()`

## To Reproduce

Let's say my domain is https://example.com.

Site URL: `https://example.com`
Additional Redirect URL's: `https://example.com, https://example.com/path-1, https://example.com/path-2, http://localhost:3000, http://localhost:3000/path-1, http://localhost:3000/path-2`

**Comment by andreivreja** [comment]
It works for me, should work perfectly as long as the url matches 100%.

**Comment by varna** [comment]
I can't make it redirect to `http://localhost:3000`

**Comment by kiwicopple** [comment]
> I'm passing redirectTo: window.location.href into auth.signIn()

This is not expected to work - you will need to add the _exact_ address you are redirecting to - eg, `http://example.com`

I'll close this for now, but if you are able to provide some steps to replicate (using the exact address) it's definitely a valid bug and I can reopen
