### ISSUE TITLE
Project status: Auth Unable to connect

### ISSUE THREAD

**Issue by Tananga** [supabase/supabase#26247]
![Screenshot 2024-05-13 at 14 42 30](https://github.com/supabase/supabase/assets/44244477/9012949b-58aa-462c-b843-31b8ec8aeb09)

![Screenshot 2024-05-13 at 14 54 27](https://github.com/supabase/supabase/assets/44244477/fd9de04f-af88-4df3-9339-fff9e7c1b3a6)

Restart dont fix it.

**Comment by GaryAustin1** [comment]
https://github.com/orgs/supabase/discussions/20722
Has the likely solution.

Note to Supabase this is happening to several users a day right now.

**Comment by kangmingtay** [comment]
closing since we have a github discussion for this
