### ISSUE TITLE
Reset Password is not being sent

### ISSUE THREAD

**Issue by 1337Impact** [supabase/supabase#26297]
I've been having this problem for a long time now. I forgot the password of my supabase account and to reset I clicked reset password. I get a notification that reset password email has been sent. but I don't get any email. I already checked spam and it's not there. I do the same process with another email (cause I usually forget my passwords) and I got the same problem.

**Comment by encima** [comment]
Thanks for opening! 
2 things to do, please:
1. Please open this as a support ticket: https://supabase.help 
2. Can you try signing up with a different email (potentially different provider) and resetting the password? (mention in the ticket the steps that you have tried)
