### ISSUE TITLE
Marketing text contents are being cut off

### ISSUE THREAD

**Issue by pasimuno-ako** [supabase/supabase#26392]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the Supabase website's Auth page, "Simple APIs" section, marketing text contents are being cut off based on screen size.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [Supabase Auth page](https://supabase.com/auth).
2. Scroll down to "Simple APIs" section
4. See error on screen widths greater than 1024px.

## Expected behavior

The marketing text should be fully visible.

## Screenshots

<img width="943" alt="Screenshot 2024-05-16 at 8 51 01 AM" src="https://github.com/supabase/supabase/assets/165913826/d6b8aa8e-3bc7-4522-8727-f6ec5512b0ce">

## System information

- OS: N/A
- Browser (if applies): Chrome (latest)
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

This line in the codebase:
https://github.com/supabase/supabase/blob/a25242e352234ffda738009ebb98efedc12afa67/apps/www/pages/auth/Auth.tsx#L140

Solution: Either remove the `-mb-48` or add a new class `sm:mb-0`.

**Comment by Hallidayo** [comment]
Hi @pasimuno-ako - Thank you for opening, feel free to open a PR for a fix.

**Comment by H0onnn** [comment]
@Hallidayo @pasimuno-ako Hello ! Can I solve this issue ?

**Comment by akar016012** [comment]
I have fixed this and opened a new PR

![image](https://github.com/supabase/supabase/assets/61394999/6dd4517c-976e-4b68-8903-1464eb972862)

https://github.com/supabase/supabase/pull/26495

**Comment by karlpablo** [comment]
@akar016012 Your solution works but is not ideal because adding the `mt-20` simply negates the `-mb-48` from the section above.

The ideal solution is to either remove the `-mb-48` or add a new class to that element `sm:mb-0` because the negative margin seems to be used on smaller screens.

**Comment by pasimuno-ako** [comment]
@akar016012 Your solution works but is not ideal because adding the `mt-20` simply negates the `-mb-48` from the section above.

The ideal solution is to either remove the `-mb-48` or add a new class to that element `sm:mb-0` because the negative margin seems to be used on smaller screens.

**Comment by pasimuno-ako** [comment]
> Or simple fix would be to just correct this type -mb-48 to mb-48.

No, because the negative margin is only used for small screens to achieve the effect of the code blocks being cut off by the next section's margin like this:

<img width="636" alt="Screenshot 2024-05-17 at 12 46 53 PM" src="https://github.com/supabase/supabase/assets/165913826/b64cd000-0629-4c72-9c45-b5b7cd1a059a">

Which are also done on other pages without issues like in the [Database](https://supabase.com/database) page:

<img width="625" alt="Screenshot 2024-05-17 at 12 49 01 PM" src="https://github.com/supabase/supabase/assets/165913826/92b24e9e-6cd7-4cdc-8fa7-a3a4be0a04e1">

**Comment by akar016012** [comment]
Yes, so I fixed the typos in two places and it makes the mobile view even better

Before:
![image](https://github.com/supabase/supabase/assets/61394999/5b7b9667-5dec-4ac1-abf2-cfa19c1e49e6)

After:
![image](https://github.com/supabase/supabase/assets/61394999/4a3cf860-fc09-405e-bd04-e90867048c19)

**Comment by pasimuno-ako** [comment]
Actually, looking at the other pages beyond Database and Auth, it looks like the website is not consistent with when the code blocks get cut off by the section divider, so your solution may be adequate.

**Comment by Muhammad-Owais-Warsi** [comment]
Can i work on this issue ??

**Comment by H0onnn** [comment]
@Muhammad-Owais-Warsi This issue has already been requested for PR
