### ISSUE TITLE
Login with LinkedIn : error 400

### ISSUE THREAD

**Issue by Kamsou** [supabase/supabase#26390]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using the new LinkedIn OIDC sign-in provider and encountering the following error:

`{"code":400,"error_code":"validation_failed","msg":"Unsupported provider: provider is not enabled"}`

## To Reproduce

Call this function in any apps:

```
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'linkedin',
      options: {
        redirectTo: '${baseUrlSupabase}/auth/v1/callback'
      }
    })
```

## Expected behavior

A redirect to the Linkedin authentication modal

## Screenshots

![Capture d’écran 2024-05-16 à 17 45 21](https://github.com/supabase/supabase/assets/41164034/81b439f6-d254-4ae1-8e79-c1dc8f7de303)
![Capture d’écran 2024-05-16 à 17 45 13](https://github.com/supabase/supabase/assets/41164034/80d566fc-0c77-479c-b5fe-bbafc37812c5)

## System information

- OS: macOS
- Browser Chrome
- Version of supabase-js: ^2.31.0

**Comment by encima** [comment]
Have you enabled the provider in the [Auth settings](https://supabase.com/dashboard/project/_/auth/providers)?

**Comment by Kamsou** [comment]
@encima Yes 
![Capture d’écran 2024-05-17 à 09 29 24](https://github.com/supabase/supabase/assets/41164034/1573456b-5bf2-497e-a0e7-8524273b0361)

**Comment by encima** [comment]
Excellent, then your provider should be:
`linkedin_oidc`

([docs](https://supabase.com/docs/guides/auth/social-login/auth-linkedin))

**Comment by Kamsou** [comment]
I used linkedin because I have a typing error with linkedin_oidc

```
Unable to assign type '“linkedin_oidc”' to type 'Provider'.ts(2322)
types.d.ts(426, 5): The expected type comes from the 'provider' property, which is declared here on the 'SignInWithOAuthCredentials' type
(property) provider: Provider
```

But even with linkedin_oidc I get error 400, so I don't think that's where it's coming from..

**Comment by encima** [comment]
Thanks for trying! `linkedin_oidc` is the one to use, we just need to fix your typing error

Please update to the latest version (you are on 2.31 and latest is 2.43). 

You may also need to ensure the latest [auth-js](https://github.com/supabase/auth-js/blob/4ecfdda65188b71322753e57622be8eafe97ed6b/src/lib/types.ts#L18) is being used by your supabase SDK

**Comment by Kamsou** [comment]
ok to have moved to 2.43 fixed the typing error, thanks.

ok things are progressing, I'm getting to a linkedin screen. But with a redirect_ui problem:

![Capture d’écran 2024-05-17 à 09 53 56](https://github.com/supabase/supabase/assets/41164034/417c9b48-5a35-4b1d-b57b-68d9dfb3a11e)

is my redirectTo disturbed?

**Comment by encima** [comment]
Nice, it is not disturbed, only the value you send is not matching what was saved in LinkedIn. If you check/update that, then I think you are good to go!

**Comment by Kamsou** [comment]
Oh okay yes mybad , "Authorized redirect URLs for your app" was empty

Its works now ! Thanks so much @encima 🫰
