### ISSUE TITLE
Can't remove an user from supabase dashboard  using firefox

### ISSUE THREAD

**Issue by lucas-jacques** [supabase/supabase#2640]
# Bug report

## Describe the bug
When i click on remove (an user), i confirm the remove but nothing is happening.
## To Reproduce

- Create a supabase project
- Create an user from the frontend or from supabase dashboard.
- Try to remove it

## System information

- Fedora
- Browser:  From Firefox ONLY
- Version of supabase-js:  last

**Comment by bhavik-multipl** [comment]
This thing is happening while doing Table deletion as well, I am also using Firefox on macOS Big Sur.

**Comment by ibhavikmakwana** [comment]
This thing is happening while doing Table deletion as well, I am also using Firefox on macOS Big Sur.

**Comment by bhavik-multipl** [comment]
A temp. work around, Try to inspect the page and you will be able to click on the Delete button 😄 
I do not wanted to use chrome so it leads me to this Jugaad(Patch/Temp. workaround)

**Comment by joshenlim** [comment]
this issue seems to now have been resolved - i'll go ahead to close this ticket but feel free to reopen if there's any other issues!
