### ISSUE TITLE
Export To CSV functionality missing

### ISSUE THREAD

**Issue by sebgie** [supabase/supabase#2641]
# Bug report

## Describe the bug

According to the website it is possible to export selected rows by downloading a CSV file. I was quite sure that I saw this functionality last week but I cannot find it anymore.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Supabase - Your Project - Table editor'
2. Select multiple rows
3. Button to "Export To CSV" does not exist

## Expected behavior

I would like to use the "Export To CSV" functionality.

## Screenshots

Feature shown on the website:
![Database___Open_source_SQL_Database](https://user-images.githubusercontent.com/539213/127614001-05aab1ed-70ab-46be-9d89-9615db8183bd.png)

What I see:
![storywww-v2-hype_und_Eingang_—_sg_storyblok_com_und_Neue_E-Mail](https://user-images.githubusercontent.com/539213/127614644-a0fb32e4-78c3-45c0-9cda-6b4df2da7d74.png)

## System information

- OS: macOS
- Browser Brave (Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64))
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by inian** [comment]
The button is a bit hidden I agree @sebgie. 
![CleanShot 2021-08-03 at 01 26 50](https://user-images.githubusercontent.com/2155545/127900613-ae18cbd9-bf05-4b50-a5ae-a4ead879eb7a.png)


Leaving the issue open so that @MildTomato can take a look

**Comment by Nazeeh21** [comment]
I would like to give a try to this issue.

**Comment by sebgie** [comment]
Oh wow, thank you 🙈. I did not find that. I would welcome a more prominent place for the button 👍 .

One more thing that I realized when using the button. It only exports the currently viewed 100 rows despite saying "Export all rows to CSV". But that's a nitpick probably ;-).

**Comment by Nazeeh21** [comment]
I forked *supabase* repo. I went through [these](https://supabase.io/docs/guides/self-hosting#running-locally) steps to run supabase locally and the docker container is running up successfully. 
![image](https://user-images.githubusercontent.com/56908732/128134050-dca7c357-9d3c-4c18-b5be-397e0bac47b4.png)

Now, do I need to run any other command to run supabase locally? Also, I am not able to figure out how to work with the UI in supabase. I request you to please help me with the same. 😅

**Comment by joshenlim** [comment]
hey @sebgie! a couple of fixes have been pushed out and we've made the export to csv / delete rows actions a bit more clearer, once you've selected a few rows as such:

![image](https://user-images.githubusercontent.com/19742402/135023936-55ed4978-9a3e-405a-adfa-396482307251.png)

hope this helps! :)

**Comment by phivk** [comment]
> One more thing that I realized when using the button. It only exports the currently viewed 100 rows despite saying "Export all rows to CSV". But that's a nitpick probably ;-).

I also missed this feature, but it's now possible 🎉 
After selecting all 100 rows on the first page, an option to select all other rows is presented:

<img width="467" alt="afbeelding" src="https://user-images.githubusercontent.com/902958/200301762-9f54c410-8617-47fb-b0cf-b66f8434d32a.png">
