### ISSUE TITLE
 supabase documentation is not responsive

### ISSUE THREAD

**Issue by zaidzebari** [supabase/supabase#2645]
# Improve documentation

## Link 

https://app.supabase.io/project/*/auth/users

## Describe the problem

Not Responsive

## Describe the improvement

I have to zoom out to 80% to my screen, to see the userID column

## Additional context

It is not responsive totally!

![problem 1](https://user-images.githubusercontent.com/54475819/127656476-b29fd035-bcd0-488a-b282-59b0d2b0e32a.PNG)

![problem 2](https://user-images.githubusercontent.com/54475819/127656490-67a616f3-7b4e-4fe7-b113-11601a0a4b16.PNG)

**Comment by kiwicopple** [comment]
Thanks for reporting this @zaidzebari - looks like it's a duplicate of https://github.com/supabase/supabase/issues/2633. I'll close this one and we can track it there
