### ISSUE TITLE
Fix Free Plan Explanation in "How billing works" documentation

### ISSUE THREAD

**Issue by aaronluannguyen** [supabase/supabase#26498]
# Improve documentation

## Link 

https://supabase.com/docs/guides/platform/org-based-billing#free-plan
https://supabase.com/docs/guides/platform/org-based-billing#multiple-free-plan-projects

## Describe the problem

The free plan's initial explanation is quoted as:
> Supabase provides two "Free organizations". Each organization can run a Nano instance for free. This is a great way to get started with Supabase and try out the platform.

What this indicated to me was that this equates to a **single** free project per free organization (limit of 2 free orgs).

However, as you scroll down to the billing example for multiple free plan projects, you'll see this documentation:
<img width="956" alt="Screenshot 2024-05-17 at 1 39 49 PM" src="https://github.com/supabase/supabase/assets/32144343/8c449096-672b-45be-8a0d-3bda8830f80b">

Where in the last row of the example, you get 1 free database per free org which is consistent with the initial free plan explanation highlighted above. 

But then the following sentence after the table, it reads:
> While we allow you to launch a total of two free projects, the quota applies to the entire organization, i.e. you can have a total of 4GB of database space.

There are two problems with this last sentence:
- It indicates that you get two free projects or 2 free databases per free organization while the earlier parts of the documentation indicates that you get just 1.
- The calculation of database space is incorrect as 500mb * 4 would just be 2GB. I suspect that this may be referring to storage space as the free limit is 1GB, so 1GB * 4 = 4GB.

## Describe the improvement

Will need clarification from the team on what the billing policy is when it comes to the number of free projects per free organization to update content to be consistent in reflecting said policy.

## Additional context

This search came from myself being a new user and exploring how to get a product off of the ground with separate stage and production environments. My initial approach was to set up the product as an org and then have a "stage" project along with a "prod" project. However, with billing only being refreshed every 24 hours, I can't quite tell if this will incur additional costs beyond the free plan, and the documentation made me question what the policy actually is 😅.

**Comment by charislam** [comment]
@kevcodez, you're the expert here. Could you check if the docs accurately describe the current billing model and see if there's a way to make them clearer?

**Comment by kevcodez** [comment]
I'll take care of clarifying the docs, but just to give you some more details:

The subscription plan is set on the organization level and you cannot mix paid a free plan projects inside a single organizations. We allow you to have two projects in total across all organizations where you're either an Owner or Administrator. So you could have two free orgs with one project each, or one free org with two projects. Paused projects don't count towards the limit.

If you launch two projects in a free plan organization, you will never be charged for anything.

If you want one project on the free plan and one project on the Pro plan, you'll have to create two separate organizations for that.

Paid plan comes with $10 in Compute Credits that will cover your first project on the default "Micro" Compute instance. Each project is a dedicated database and project. If you launch two projects (staging & prod) in a single Pro plan organizations, your monthly bill will be at least $35
- Pro Plan +$25
- Staging project on Micro Compute +$10
- Prod project on Micro Compute +$10
- Compute Credits -$10
- $35/m

Both projects would benefit from all Pro plan features such as automated backups and no pausing.
