### ISSUE TITLE
Generating TypeScript Types not possible without supabase init

### ISSUE THREAD

**Issue by kurtschambach** [supabase/supabase#26564]
# Improve documentation

## Link 

[Generating TypeScript Types](https://supabase.com/docs/guides/api/rest/generating-types)

## Describe the problem

It seems that it is not possible to create types without running `npx supabase init` before, 
and the instructions on the page don't mention that.

## Describe the improvement

The instructions should include this step...

**Comment by encima** [comment]
Thanks for this! Feel free to open a PR if you would like 🚀

**Comment by H0onnn** [comment]
@encima Hello ! I would like to solve this issue. Can you assign it to me ?
