### ISSUE TITLE
issue in backup of supabae storage data 

### ISSUE THREAD

**Issue by webdeveloper20213** [supabase/supabase#26576]
When I attempt to restore the supabase backup, the data is restored correctly, but the bucket files are corrupted—it does not match the content type. It always sets "application/octet-stream" as the content type. so it does't display correct data on the front end side? 

![image](https://github.com/supabase/supabase/assets/133633860/b8b24435-9e2c-4e0c-8aa6-dccff8f84827)

**Comment by saltcod** [comment]
hey @webdeveloper20213 are all the files in all the buckets messed up?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
