### ISSUE TITLE
Cannot test out SQL queries with `service_role` from SQL Editor

### ISSUE THREAD

**Issue by bombillazo** [supabase/supabase#26609]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We have no way of testing SQL queries from the SQL editor with the `service_role`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to SQL editor
2. Open role dropdown

## Expected behavior

We are able to select service role

## Screenshots

<img width="790" alt="image" src="https://github.com/supabase/supabase/assets/44002321/2e38dbcb-88b2-489d-be90-438cce3f6970">

## System information

- Version of supabase-js: 2.43.2

**Comment by encima** [comment]
Hi there,

Thanks for opening. This may not be clear but the `postgres` role has the same privilges as the `service_role` and can be considered the same thing. The description confirms this but let us know if this could be clearer in the Studio or the Docs!
