### ISSUE TITLE
Tenant Error

### ISSUE THREAD

**Issue by Akashrajark** [supabase/supabase#26622]
Failed to create bucket: Missing tenant config for tenant nqgmuqmfbhqqbavijyzq

**Comment by Hallidayo** [comment]
Hi @Akashrajark - Could you provide a bit more information on where you are getting this issue please?

**Comment by encima** [comment]
Closing the issue due to it being inactive. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
