### ISSUE TITLE
Planned migration failed causing production app to stop

### ISSUE THREAD

**Issue by ShJavokhir** [supabase/supabase#26621]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a project (mobile app written built with flutter) that has been working for more than 5 months with supabase. I only use auth in supabase, nothing else. Around 10 days ago I got notification about migration to v2 platform architecture for my supabase project. And today was the migration day, unfortunately supabase failed to migrate project. Auth completely stopped and api https://xxxxxx.supabase.co/auth//v1/token just returning empy 404 without any body. 

## To Reproduce

1. https://xxxxxx.supabase.co/auth//v1/token returning 404 with empty body (replace xxxxxx with project id )
2. Checked auth logs and found out migration was failed, see screenshot below

## Expected behavior

Need to be migrated succesfully and api https://xxxxxx.supabase.co/auth//v1/token should not return empty body with 404 status code. 

## Screenshots

<img width="2225" alt="image" src="https://github.com/supabase/supabase/assets/46817680/d2421a5e-2870-4c54-8894-d37d72ad8bf8">

## System information

- OS: [macOS]
- Browser [brave]
- Version of supabase_flutter : [^1.10.16]

**Comment by Hallidayo** [comment]
Hi @ShJavokhir - thank you for reporting this issue, is it possible you could contact support about this and we can get a engineer to look at this one for you? If you go to https://supabase.help/ and link this issue they can look into this for you.

**Comment by ShJavokhir** [comment]
> Hi @ShJavokhir - thank you for reporting this issue, is it possible you could contact support about this and we can get a engineer to look at this one for you? If you go to https://supabase.help/ and link this issue they can look into this for you.

Hi @Hallidayo yes contacted to support, havent' got response yet.

**Comment by Hallidayo** [comment]
Hi @ShJavokhir - Okay great, I'll keep this open and we'll give it 24 hours. I'll also send you a message on discord as I can see you have a thread open.

**Comment by Hallidayo** [comment]
Hi @ShJavokhir just checking is everything all okay your side now?

**Comment by ShJavokhir** [comment]
Realized something has changed in supabase side after their v2 architecture migration, here what my code looked like before solving this issue:

`await Supabase.initialize(
    url: "https://xxxxxxxx.supabase.co/",
    anonKey:
        "eyxxxxxxxxxx",
  );`

Here is how I solved it:

``await Supabase.initialize(
    url: "https://xxxxxxxx.supabase.co",
    anonKey:
        "eyxxxxxxxxxx",
  );``

Yeah just one slash after url caused problem all of a sudden. Had to update both apps on play store and appstore. 

Thanks @Hallidayo
