### ISSUE TITLE
Api now returning error. Something changed overnight on supabase end

### ISSUE THREAD

**Issue by Crypto69** [supabase/supabase#26647]
# Bug report
The supabase-js-web/2.43.1 API

That I've been calling for a long time stopped working this morning. No changes were made on the client but the server is now responding with a 400 error.

This is the rest API call

search": "?select=*&boat_id=eq.18&=eq.",
  "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/rest/v1/insurance?select=*&boat_id=eq.18&=eq."

Some optional filter parameters are passed in. sometimes there are two sometimes there are one.

This never caused issues before but overnight the syntax with an empty eq. is causing an error.

To get it working I have to remove the option equal at the end

https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/rest/v1/insurance?select=*&boat_id=eq.18

This now works but doesn't explain why overnight it was working and then stop working.

![Screenshot 2024-05-22 at 1 51 42 pm](https://github.com/supabase/supabase/assets/50306702/89fa03f4-c910-4362-9373-99f0cc1d2a52)

**Comment by encima** [comment]
Thanks for opening! It is likely that this was fixed behaviour in a recent [PostgREST release](https://github.com/PostgREST/postgrest/releases/tag/v12.0.3) that was applied to your project.

In this case, the behaviour is now right so thanks for dealing with the workaround before! If you modify your query building to only add parameters that are provided then you should be good to go.

**Comment by Crypto69** [comment]
Why did the error only start happening last night if fix in that release was applied two weeks ago ?

**Comment by encima** [comment]
The release was made 2 weeks ago, it was brought into the platform in the last week and rolled out to projects progressively

**Comment by Crypto69** [comment]
ok thanks for the clarification
