### ISSUE TITLE
Escaped quotes are being added around the email sender name

### ISSUE THREAD

**Issue by SDrinkwater** [supabase/supabase#26697]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have setup [resend](https://resend.com/) with my project and I have provided a sender name. When an email is sent, the sender name is wrapped in escaped quotes. These quotes show up around the name in the email (since they're escaped).

I have checked the request that is sent to resend and it looks like: `"from": "\"{sender_name}\" {sender_email}",`.

How can I remove these quotes as it makes the email look dubious.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create project
2. Connect to [Resend](https://resend.com/) and provide a sender name
3. Trigger email
4. Observe quote name

## Expected behavior

The name should come through exactly as it is entered in the input field within supabase.

## System information

NA

**Comment by Hallidayo** [comment]
Hi @SDrinkwater - Thank you for raising the issue, Could you give me the following information please:

- Which method is being used to trigger the email?
- Could you send over the template you are using?

**Comment by SDrinkwater** [comment]
Hey @Hallidayo, I don't think the method nor template have any affect here as I can reproduce the behaviour using the "Add user" button on the authentication dashboard which uses the default invite user template (I haven't changed it).

**Comment by encima** [comment]
Hey @SDrinkwater ,

We spoke with the Resend team and this seems to be an issue on their side. Please contact their support for more info.
