### ISSUE TITLE
Policy editor of storage is not displaying existing security policies. 

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#2670]
# Bug report

## Describe the bug

Hi, came across this issue while answering community discussions, so reporting it!

Policy editor at `https://app.supabase.io/project/[projectID]/storage/policies` is not displaying any of the storage related policies. I have also added a policy right now to test it, but the new policy that I added also did not show up. Also, there were no errors in the browser's console. 

<img width="1383" alt="Screen Shot 2021-08-01 at 11 58 36" src="https://user-images.githubusercontent.com/18113850/127757657-b5a1493a-9598-4356-8143-1a1e0fc68cec.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/[projectID]/storage/policies`

## Expected behavior

Storage related security policies should appear. 

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Came across this problem while trying to solve [this question](https://github.com/supabase/supabase/discussions/2666) from the community.

**Comment by leadream** [comment]
Yeah, Creating new policies will allow uploading but still doesn't show up here.

**Comment by joshenlim** [comment]
Gotcha on this! Have found the issue - will be pushing out a fix :)

**Comment by inian** [comment]
Hi Tyler, this fix will be deployed tonight or by tomorrow, thanks for reporting!
