### ISSUE TITLE
database not updating via table editor

### ISSUE THREAD

**Issue by hexaaagon** [supabase/supabase#26730]
### Discussed in https://github.com/orgs/supabase/discussions/26690

<div type='discussions-op-text'>

<sup>Originally posted by **hexaaagon** May 23, 2024</sup>
when I update the database data through the Table Editor, it doesn't seem to update it.

using role "postgres role"

before (editing the database)
![image](https://github.com/supabase/supabase/assets/128217934/47398537-c154-4741-89f0-20b3b1a05f5f)

after (clicking the enter button & view the database again)
![image](https://github.com/supabase/supabase/assets/128217934/84a22f4a-05b5-47d8-9bcc-bb43cdb78643)</div>

**Comment by encima** [comment]
Hi there,

Thanks for opening, can you provide the queries you ran to reproduce this, please?
