### ISSUE TITLE
Sign in with Apple (signInWithIdToken) : error 400

### ISSUE THREAD

**Issue by Kamsou** [supabase/supabase#26747]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to implement sign in with Apple. 
I want to have the popup so I use the `signInWithIdToken()`. 

I have `identityToken` in the result of `SignInWithApple.authorize(options)`

But I get this error:` {“__isAuthError”:true, “name”: “AuthApiError”, “status”:400}`

## To Reproduce

```
import {
  SignInWithApple,
  type SignInWithAppleResponse,
  type SignInWithAppleOptions
} from '@capacitor-community/apple-sign-in'

  const options: SignInWithAppleOptions = {
    clientId: '<clientId>',
    redirectURI: '<uri>',
    scopes: 'email name',
    state: '123456',
    nonce: 'nonce'
  }

  async function signInWithApple() {
    SignInWithApple.authorize(options)
      .then(async (result: SignInWithAppleResponse) => {
        const { identityToken } = result.response
        const { data, error } = await supabase.auth.signInWithIdToken({
          provider: 'apple',
          token: identityToken,
          nonce: 'nonce'
        })

        console.log(data, 'data')

        if (error) {
          console.log(error, 'error')
          return
        }
      })
      .catch((error) => {
        console.log(error, 'error')
      })
  }
```

## Expected behavior

data return data and not `{"user":null,"session":null}`

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: ^2.43.0

**Comment by encima** [comment]
Using the Dashboard, have you checked your logs for this to debug further? You can check your Auth logs.
Have you also tried listening for the event: `AppleIDSignInOnSuccess`?
Also, make sure you have followed the config steps in the [docs](https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=framework&framework=nextjs#configuration-apple-js) for using Apple JS

**Comment by Kamsou** [comment]
@encima 
Yes, Apple sends me back the identityToken. But Supabase send me error : {"__isAuthError":true,"name":"AuthApiError","status":400} error

**Comment by Kamsou** [comment]
Do you have an example of a code implementation that works?

**Comment by encima** [comment]
Sorry, the one in the docs works for me (the one using the Apple JS lib)

**Comment by Kamsou** [comment]
@encima do you use this function `signInWithIdToken()` ?

**Comment by encima** [comment]
Yes, I use this [example](https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=framework&framework=nextjs#using-sign-in-with-apple-js)

**Comment by valmnt** [comment]
> okay well I'll continue to use `signInWithOAuth` which works well with apple. thanks anyway @encima

I encountered this error because I forgot to set the client ID in the provider configuration. 

Generally, this error indicates that the Apple OAuth provider configuration is incorrect.
