### ISSUE TITLE
New column not recognized

### ISSUE THREAD

**Issue by pearlslugs** [supabase/supabase#26751]
After adding a new column, I am receiving a 500 error message saying the column does not exist.

![image](https://github.com/supabase/supabase/assets/61484145/36be5073-0004-4c23-b646-83c4fc8bca85)

![image](https://github.com/supabase/supabase/assets/61484145/a01163f8-f7e4-484b-bb9b-c397025963d6)

her we can see the column in the table, but it is not recognized when trying to add a value to it. the existing entries which show null were created before this column was added

**Comment by Hallidayo** [comment]
Hi @pearlslugs - Are you able to update the column using the SQL Editor? Also are you using a framework?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
