### ISSUE TITLE
Unable to Connect GitHub Repository to Multiple Supabase Accounts Using a Single GitHub Account

### ISSUE THREAD

**Issue by nyxb** [supabase/supabase#26762]
Hello Supabase Team,

I am experiencing an issue with the GitHub integration across different Supabase accounts. Here are the details:

Accounts Involved: I have both a private and a business Supabase account.
Current Configuration: My business Supabase account is successfully connected to my GitHub account. This integration works perfectly, and I can link repositories without any issues.
Issue Description: However, when I attempt to connect a GitHub repository to my private Supabase account using the same GitHub account, the process fails. Specifically, the browser attempts to connect but just reloads the page and continues to display "Connecting GitHub" without completing the action.
Troubleshooting Done: I tested connecting a different GitHub account to my private Supabase account, and this was successful. It appears the issue arises only when trying to use the same GitHub account to link repositories across different Supabase accounts.
From the above, it seems there might be a limitation or a bug preventing a single GitHub account from being used to connect repositories to multiple Supabase accounts. Could you please confirm if this is expected behavior or a potential oversight? Any guidance on how to resolve or work around this issue would be greatly appreciated.

Thank you for your assistance!

Best regards,
@nyxb

**Comment by Hallidayo** [comment]
Hi @nyxb - When you see the `Connecting GitHub` do you see any errors in the browser console?

**Comment by nyxb** [comment]
> Hi @nyxb - When you see the `Connecting GitHub` do you see any errors in the browser console?

Yes sry 

![NyxbShot-2024-05-27-at-23 35 59@2x](https://github.com/supabase/supabase/assets/98586665/389e1b7d-5464-48e9-8e9f-aed658ef6bfe)


https://github.com/supabase/supabase/assets/98586665/f585ff4e-febb-45ad-9643-5a8ec6c3808f

**Comment by Hallidayo** [comment]
Hi @nyxb - Odd one,  I've tried the same as you but on Chrome and I'm able to connect. Could you try on Chrome so we can rule out if its browser specific?

**Comment by nyxb** [comment]
> Hi @nyxb - Odd one,  I've tried the same as you but on Chrome and I'm able to connect. Could you try on Chrome so we can rule out if its browser specific? 

I have tested it with arc which is Chrome based and also with Chrome and still have the problem.

**Comment by nyxb** [comment]
> @nyxb it's a bug on our side. We had a unique constraint on not only Supabase user id, but also GitHub user id. There's no reason to do that though, and only constraint we need is to have a single authorization per Supabase user.
> 
> PR is already pending, should be deployed by tomorrow.

Ok I know, very good then it will work soon. Thanks for the info

**Comment by kamilogorek** [comment]
A fix has been deployed and verified in production. Should be working fine for you now. Thanks for reporting the issue!

**Comment by nyxb** [comment]
> A fix has been deployed and verified in production. Should be working fine for you now. Thanks for reporting the issue!

yes wonderfull now its work :)

**Comment by peribusmetro** [comment]
Not working for me :(
![Captura de pantalla 2024-07-05 120135](https://github.com/supabase/supabase/assets/168760569/0e7bdba1-5874-44b1-9891-9ed8eac1465d)
