### ISSUE TITLE
Auth Custom Claims Guide: Multiple roles per user?

### ISSUE THREAD

**Issue by tvogel** [supabase/supabase#26789]
If I understand correctly,

https://github.com/supabase/supabase/blob/dd7c1d19edee33aaa2552b58c89cdf5cfc0250c3/apps/docs/content/guides/database/postgres/custom-claims-and-role-based-access-control-rbac.mdx?plain=1#L42

would mean that each pair of user-id and role must be unique such that each role membership can be only listed once but this also means that in fact each `user_id` can be listed multiple times with different `role` entries. That also makes sense for many cases but it looks like 

https://github.com/supabase/supabase/blob/dd7c1d19edee33aaa2552b58c89cdf5cfc0250c3/apps/docs/content/guides/database/postgres/custom-claims-and-role-based-access-control-rbac.mdx?plain=1#L97

is actually not prepared to handle multiple role memberships.

So, I guess, either the first line should be changed to `unique (user_id)` or the hook and the `authorize()` should be extended to handle multiple roles per user.

**Comment by encima** [comment]
hey there, thanks for opening!

As you noted, the `unique` constraint ensures that the user does not have duplicate roles but does allow multiple roles per user.

The query you reference performs a `select into` which is sort of "copy the requested columns into a destination" and this destination is `user_role`.

So, if your user has the roles: `admin` and `supervisor` then the `select into` would create a sort of temporary table, called `user_role` that would contain the rows: `admin` and `supervisor`. The rest of the function then serializes those rows in a JSON object that contains role under the key `user_role` 

Give the guide a try and you can see it in action!

**Comment by tvogel** [comment]
I did and indeed, it does not work. Only the first role is reported, see this minimal example. plpgsql's `SELECT ... INTO` only takes the first row, see https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-SQL-ONEROW which later states "If multiple rows are returned, only the first will be assigned to the INTO variable(s). If no rows are returned, NULL is assigned to the INTO variable(s)." That's why there is a variant `SELECT ... INTO STRICT` which raises an exception if there are multiple or no rows.

```sql
CREATE TYPE app_role AS ENUM ('admin', 'moderator');

CREATE TABLE test_table (role app_role);
INSERT INTO test_table (role) VALUES ('admin'), ('moderator');
SELECT * FROM test_table;

CREATE FUNCTION test_multirow() RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
    result app_role;
BEGIN
    SELECT role INTO result FROM test_table;
    RETURN to_jsonb(result);
END;
$$;

SELECT test_multirow();
```

Output:
```
CREATE TYPE
CREATE TABLE
INSERT 0 2
   role    
-----------
 admin
 moderator
(2 rows)

CREATE FUNCTION
 test_multirow 
---------------
 "admin"
(1 row)
```
