### ISSUE TITLE
JWT secret should be generated client-side only

### ISSUE THREAD

**Issue by tvogel** [supabase/supabase#26802]
If I understand the HTTP network stream correctly, the JWT secret that is automatically generated here

https://github.com/supabase/supabase/blob/5e7817548b7972a72370dfa70550eda69a6664a1/apps/docs/components/JwtGenerator/JwtGenerator.tsx#L28

e.g. in context of https://supabase.com/docs/guides/self-hosting/docker#generate-api-keys, is actually generated on the server (SSR). I would prefer the JWT secret to be generated and visible to my local browser only. I am not a React dev (yet) but it seems using `dynamic()` for the `JwtGenerator` should do the trick.

**Comment by encima** [comment]
Thanks for opening and feel free to open a PR!

**Comment by Golu7667** [comment]
@tvogel @encima #26802
` const secret = [...Array(40)].map(() => Math.random().toString(36)[2]).join('')
  const [jwtSecret, setJwtSecret] = useState(secret)`
This secret key is generated on the client side, not on the server side. The implemented logic generates a random 40-character string on the client. so you can close this pr #26802.
