### ISSUE TITLE
SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing

### ISSUE THREAD

**Issue by rrr3da** [supabase/supabase#26800]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I can't connect to the database instance using Drizzle, nor Kysely, and not even with the basic `psql [connection string]` via terminal

## System information

- OS: macOS Sonoma 14.5
- Version of Node.js: 18.16.1

## Additional context

We are using Supabase in a Nuxt-based application flawlessly. We need to implement db transactions, so we wanted to try out some libraries that support them like Kysely.

We discovered we can't connect to the database pool by using any non-supabase js library, but the strange thing is that we get errors even if we try to connect to the database by using the `psql` cli command, as simple as `psql "postgres://postgres.rvmdtannwkkwdxzbadop:[YOUR-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"`

We tried to switch port 5432 with 6543, nothing changes.

We tried to reset database password from the dashboard (some issues were solved by choosing a simple password with no special chars to be encoded), nothing changes.

The project we try to connect to is `rvmdtannwkkwdxzbadop`; in the Settings/Database page we are seeing the `PgBouncer pending removal` badge, but I suppose this makes no real difference since I tried also on a fresh project (with no badge) and we can't connect to it either.

We cannot even connect by using the supabase cli, after inserting the right password (it worked some weeks ago):
`supabase link --project-ref rvmdtannwkkwdxzbadop --debug`

<img width="876" alt="Screenshot 2024-05-27 alle 17 56 15" src="https://github.com/supabase/supabase/assets/12610856/7fcce125-a05f-4e57-80f1-12d712a004d4">

Any help would be really appreciated, thank you

**Comment by encima** [comment]
Hello,

thanks for reporting. When it is an issue with your hosted Supabase, you are welcome to make an issue here but you can also open a [support ticket](https://supabase.help)

We ran a healthcheck on your project and can confirm connectivity via `psql`. Can you try connecting with the `direct connection` (uncheck `use connection pooler`) and confirm whether it is an issue with Supavisor (the connection pooler) or your project?

**Comment by rrr3da** [comment]
Hello @encima ,

Thank you for checking the status.
I am able to connect to it now, I probably made some mistakes with my brew packages during all the tests. I uninstalled everything and came back to a blank system status and everything worked as expected.

Thank you for your time,
