### ISSUE TITLE
Briefly describe Postgrest filters

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/supabase#2681]
# Improve documentation

## Link 

All the filter documentation pages, starting with https://supabase.io/docs/reference/javascript/using-filters. 

## Describe the problem

All the filter documentation pages are missing an actual description for what the operator does. For someone completely new to PostgreSQL and Postgrest, I have no idea, for example, what the `rangeAdjacent()` filter does and how differs from, for example, the `rangeGte()` filter. I can make an educated guess based on the function/filter names, but that's seriously no bueno.

## Describe the improvement

Instead of having to guess what a filter does, Supabase's documentation should include or (at the very least) link to [the Postgrest documentation](https://postgrest.org/en/stable/api.html#operators) that describes what each of the filter operators does and it's PostgreSQL equivalent. You could then even go a step further and include links to the PostgreSQL documentation (linking each filter with it's equivalent SQL syntax).

![image](https://user-images.githubusercontent.com/20798889/127908541-936c608f-6ab1-4fd5-a299-daa5d0cb0f09.png)

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by kiwicopple** [comment]
Hey @nicholaschiang - these descriptions exist at the top of the page here:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/10214025/147562083-69b9327e-d4a5-4979-8fa2-943a23bd3568.png">


Perhaps you want more detail added? I'll close this for now as I'm doing a spring-clean, but feel free to comment with more info and I can reopen
