### ISSUE TITLE
supabase functions deploy failure

### ISSUE THREAD

**Issue by mrsiano** [supabase/supabase#26830]
hi
im trying to deploy functions and I'm receiving this:
```
Bundling hello-world


#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
error running container: exit 139
```

with debug: 
Supabase CLI 1.167.4
Bundling hello-world
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:53 Recv First Byte
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Sent Header: Content-Length [297]
2024/05/28 14:48:53 Sent Header: Content-Type [application/json]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:53 Recv First Byte
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Sent Header: Content-Length [122]
2024/05/28 14:48:53 Sent Header: Content-Type [application/json]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:53 Recv First Byte
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Sent Header: Content-Length [2011]
2024/05/28 14:48:53 Sent Header: Content-Type [application/json]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:53 Recv First Byte
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Sent Header: Content-Length [0]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:53 Recv First Byte
2024/05/28 14:48:53 Sent Header: Host [api.moby.localhost]
2024/05/28 14:48:53 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2024/05/28 14:48:53 Send Done
2024/05/28 14:48:54 Recv First Byte

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffccfa258602024/05/28 14:48:54 Sent Header: Host [api.moby.localhost]
```

thanks

**Comment by mrsiano** [comment]
ok the problem was with my docker version, I've updated both docker cli and docker desktop and it works not

**Comment by TopIvanAbramov** [comment]
does not help, update docker via homebrew to version: Docker version 27.5.1, build 9f9e405

still the same error:
2025/03/04 23:29:29 Sent Header: Host [api.moby.localhost]
2025/03/04 23:29:29 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2025/03/04 23:29:29 Send Done
2025/03/04 23:29:29 Recv First Byte
error running container: exit 139

**Comment by TopIvanAbramov** [comment]
new version just broke everything, this works for me:


`npx supabase@2.13.3 functions deploy --use-api`
