### ISSUE TITLE
Role impersonation UI does not change role used in GraphiQL queries on local environment

### ISSUE THREAD

**Issue by vtsatskin** [supabase/supabase#26839]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Role Impersonation in GraphiQL in Supabase Studio running on a local development environment does not work as intended. It always sends requests using the service_role instead of using what is selected in the UI. This only occurs during local development, the Supabase Studio works correctly.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run Supabase on a local development machine
2. Go to API Docs -> GraphiQL
3. Setup a table with RLS policies which prevent anonymous access
4. Write a query accessing data in the table
5. Query the data as a "service_role" role, observe data is returned
6. Press "Role Impersonation" and switch to "anon role"
7. Run same query as step 5, observe data is incorrectly sent for selected role violating RLS policies.
8. Open dev tools and observe `X-Graphql-Authorization` header always uses service_role token, not the token associated to the user selected in the UI

## Expected behavior

When using the "Role Impersonation" feature in the GraphiQL tool on a local development environment, the correct access token is sent that is associated to the UI choice.

### Network Request from Service Role

<img width="1475" alt="image" src="https://github.com/supabase/supabase/assets/1301625/de483c00-3c83-426f-a64d-c5d518148f95">

### Network Request from Anon Role

**NOTE: Observe the same JWT (i.e. wrong) is sent**
<img width="1492" alt="image" src="https://github.com/supabase/supabase/assets/1301625/90bae54f-73d0-44e1-8d37-11b81a09b842">

## System information

- OS: macOS
- Browser: Chrome Version 125.0.6422.60 (Official Build) (arm64)
- Version of supabase: 1.169.8
- Version of Node.js: v20.10.0

## Additional context

I am not sure if this is relevant, but there are failed network requests whenever I change the role selected in the UI. Could this be at all related? Is there a misconfiguration on my local development environment that causes an error which is unhandled? Perhaps an error message should be shown in the UI that selecting a role to impersonate failed?

Role impersonation seems to work in the Table Editor.

<img width="866" alt="image" src="https://github.com/supabase/supabase/assets/1301625/c359f1ac-6abd-466a-b8f6-57006060962a">

**Comment by saltcod** [comment]
cc @alaister

**Comment by vtsatskin** [comment]
@alaister thank you very much for fixing this! I appreciate the timeliness. Once there's a new release available with these changes I'll confirm if this is fixed for me.
