### ISSUE TITLE
Table Editor doesn't work with "default expressions"

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#2684]
# Bug report

## To Reproduce

1. Create a table 

```
create table companies (
    id uuid primary key default gen_random_uuid(),
    name text
);
```

2. go to table editor and click insert row

![image](https://user-images.githubusercontent.com/10214025/127958738-d89c83a4-a392-4894-bace-7f50fe277cb6.png)

3. side panel will show the function in the ID textbox

![image](https://user-images.githubusercontent.com/10214025/127958608-45f418c6-de29-4ad4-b2f1-7010d3750766.png)

4. Remove the funciton and try to click save

![image](https://user-images.githubusercontent.com/10214025/127958648-ef3c0ffe-9542-435d-98e6-0473846e42f1.png)

## Expected behaviour.

1. UI should not show `gen_random_uuid()`
2. User should be able to create a row without specifying a value

**Comment by joshenlim** [comment]
There's been a couple of fixes and improvements pushed out for the side panels in general for the table editor - should be resolved now but feel free to reopen otherwise! :)
