### ISSUE TITLE
Allow hooks (and triggers) be declared on schemas other than public (such as auth and storage)

### ISSUE THREAD

**Issue by dthyresson** [supabase/supabase#2690]
# Feature request

Allow hooks (and triggers) be declared on schemas other than public (such as auth and storage)

For example, when a file is uploaded to storage or a user is updated?

Reason I ask is that within a RedwoodJS app, uploading and updating a user would likely be done using the Supabase client  (or maybe Postgrest) and not use a direct (pooled) connection to Postgres using Prisma.

Therefore, a webhook response back to the Redwood API (to a Serverless function that accepts an incoming Webhook) is super useful.

On the api side, one could then retrieve the updated records and handle that accordingly.

Common scenarios:

* User signup
* User profile (metadata) update
* File uploaded completed
* File updated in storage

And a simple feature would be for Redwood to send a crafted message to Slack (or something) with that webhook record content.

Currently only public schemas are available:

![image](https://user-images.githubusercontent.com/1051633/128027244-10e3d49a-e614-412d-bbdd-0b08c2268899.png)

![image](https://user-images.githubusercontent.com/1051633/128027277-ec06f653-303e-47b4-ad23-bba544f53308.png)

**Comment by dthyresson** [comment]
I happened to think about this issue again recently -- and I realized that records in non public schemas such as `auth` and `storage` likely have sensitive data in them. Therefore, either sensitive fields per schema either need to be redacted or masked "in some way" to prevent leaking of sensitive fields (like bucket info or hashes).

Alternatively, perhaps a table in public could be easily setup to mirror updates in the `auth` or `storage` schemas via Triggers -- with only the non-sensitive fields -- and hooks could be setup for those.

That might be a more sensible solution -- and one that combines both the trigger and hook. In fact, maybe when setting up a Trigger one could also allow a hook to be setup for the same events.

**Comment by hf** [comment]
I believe this is already possible.

**Comment by alecmerdler** [comment]
It would still be nice to be able to set up a webhook on the `storage` schema without having to mirror the table to `public`. The use case would be to build a lightweight cloud-based filesystem with a UI that updates in real-time when files are added/deleted.
