### ISSUE TITLE
TypeError: bind.callback is not a function when receiving broadcast 

### ISSUE THREAD

**Issue by churst12** [supabase/supabase#26913]
# Bug report

## Describe the bug

When receiving a broadcast, I get a `TypeError: bind.callback is not a function`.
I can make this error go away(but don't receive the broadcast) if I remove the event name. I have verified that the backend is actually making the broadcast via Realtime dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Make a broadcast and try to receive it

Page.tsx
```
const SupabaseClient = createClient(process.env.NEXT_PUBLIC_SUPABASE_API_URL || '', process.env.NEXT_PUBLIC_DATABASE_ANON || '')
...
  useEffect(() => {
    //doesnt work
    const channel = SupabaseClient.channel(game.id, { config: { broadcast: { self: true}}}).on('broadcast', { event: 'test'}).subscribe();
  }, []);
```

server
```
const broadCastTableUpdate = (table: string, gameId: string) => {
  const channel = SupabaseClient.channel(gameId);
  channel.subscribe((status: string) => {
    if(status !== 'SUBSCRIBED') {
      return null
    }
     // Send a message once the client is subscribed
    channel.send({
      type: 'broadcast',
      event: 'test',
      payload: { message: 'hello, world' },
    })
  });
};
```

## Screenshots

![asdfasdfasdf](https://github.com/supabase/supabase/assets/29928221/ea6f1616-3e38-4792-bb50-564a3c785bc1)

## System information

- OS: Windows
- Chrome
-  "@supabase/supabase-js": "^2.43.4"
- Node v20.12.2

**Comment by churst12** [comment]
I wasn't passing in enough parameters, and I guess I hadn't imported types correctly. Either way, this is a weird error to get in this case

**Comment by Domniea** [comment]
@churst12  what parameters did you add to solve the error?
