### ISSUE TITLE
Issues with Flutter Connection sample

### ISSUE THREAD

**Issue by MananGandhi1810** [supabase/supabase#26910]
# Bug report

When we try to get the sample code for connecting to supabase from Flutter app, the code sample is not readable, and the parameters to be pass, i.e. url and anonKey are not wrapped inside quotes (not marked as strings), causing them to cause syntax errors.
![image](https://github.com/supabase/supabase/assets/67302570/4a0028e8-428b-4d54-b19d-0048dc99dad3)

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The sample connection code is not properly formatted, and contains syntax errors.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Supabase project
2. Click on Connect Button on Project Home
3. Go to Mobile Frameworks tab
4. Select Flutter Framework

## Expected behavior

The code should be formatted, and must contain string quotes for initialization of connection.

## Screenshots

![image](https://github.com/supabase/supabase/assets/67302570/4cc528c8-bba9-4d96-b54e-d2e03652fa76)

## System information

- OS: [e.g. macOS, Windows]: MacOS
- Browser (if applies) [e.g. chrome, safari]: Brave

**Comment by MlNl-PEKKA** [comment]
Hey guys, I've raised a PR which resolves this issue.  
PR #26939
