### ISSUE TITLE
Updating JWT secret takes forever...

### ISSUE THREAD

**Issue by iwandejong** [supabase/supabase#26938]
# Bug report

## Describe the bug

When generating a new JWT secret in the Project Settings, the process takes hours instead of the expected few minutes.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Project Settings
2. Head to API and generate a new JWT secret.

## Expected behavior

Expected to regenerate the key and see a new key after a few minutes. Been taking hours ever since.

## Screenshots

<img width="1309" alt="image" src="https://github.com/supabase/supabase/assets/29703077/8dfe1b27-681f-4181-9e86-5b34fb725bc0">

## System information

- MacOS, Firefox Developer Edition

**Comment by Asin-Junior-Honore** [comment]
@iwandejong can this be assigned to me please 🤧🥲

**Comment by Hallidayo** [comment]
Hi @iwandejong - we don't have an assignment process. Feel free to open a PR though, thanks!

**Comment by Asin-Junior-Honore** [comment]
@iwandejong should I open a PR or you'll handle that yourself

**Comment by encima** [comment]
Hi @iwandejong 
Can you open a support ticket so the team can investigate please as this is likely to be specific to your project.
You can open one [here](https://supabase.help)

**Comment by iwandejong** [comment]
> @iwandejong should I open a PR or you'll handle that 

> Hi @iwandejong Can you open a support ticket so the team can investigate please as this is likely to be specific to your project. You can open one [here](https://supabase.help)

I'll do so thanks. Still seems to be updating the JWT token. I had a look at the audit logs and it gave a 200-status for updating the token.

**Comment by zhengyishen0** [comment]
Having the same issue here. 

What happens in my case:
- after clicking the regenerate the JWT token button, it stays at "updating ..." forever
- the project status says "unable to connect to Auth" and "unable to connect to PostgREST"
- the service itself works fine as usual
