### ISSUE TITLE
404 page (Twilio Phone Auth Guide)

### ISSUE THREAD

**Issue by flacial** [supabase/supabase#26947]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The [Twilio Auth Guide page](https://supabase.com/docs/guides/auth/phone-login/twilio) responds with 404 and it's referenced from pages like https://supabase.com/docs/reference/javascript/auth-signinwithotp

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/reference/javascript/auth-signinwithotp
2. Click on "See our [Twilio Phone Auth Guide](https://supabase.com/docs/guides/auth/phone-login/twilio) for details about configuring WhatsApp sign in."
3. Notice the "404 not found"

## Expected behavior

The Twilio Phone Auth Guide link should be of a working page.

## Screenshots

![image](https://github.com/supabase/supabase/assets/35906419/8d4f89dd-cdcf-4845-b1e2-3ee2cd9f6543)

**Comment by MlNl-PEKKA** [comment]
Can I get some information about the correct link ? Is it this?
https://supabase.com/docs/guides/auth/phone-login?showSmsProvider=Twilio

**Comment by Hallidayo** [comment]
Hi @MlNl-PEKKA - Yep thats the link, feel free to open a PR 👍

**Comment by Surjeet9700** [comment]
I've followed the reproduction steps and can verify the issue. I'm ready to investigate further and fix the broken link.

**Comment by Hallidayo** [comment]
Hi @Surjeet9700 - Feel free to open a PR 👍
