### ISSUE TITLE
RPC not working for my API route. 

### ISSUE THREAD

**Issue by antoineross** [supabase/supabase#26946]
- [ yes ] I confirm this is a bug with Supabase, not with my own application. 
- [ yes ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Increment function through supabase/js and rpc not working, but other types of update works. 

The way I interact with the app is through an embed.min.js file, from which interacts with the route of my app. 

## To Reproduce

To reproduce just 
1. Create a chatbot table with questions_counter, questions_limit , id, attach it to user_id in the public 
2. Create a user with user_id column 
3. Create an API route on Nextjs that calls the /chat route

Below is my RPC function: 
```
CREATE OR REPLACE FUNCTION increment_questions_counter(chatbot_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE chatbot
    SET questions_counter = questions_counter + 1
    WHERE id = chatbot_id;
END;
$$ LANGUAGE plpgsql;
```

and here is my Route:
```
import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';
import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { createClient } from '@supabase/supabase-js'


export async function POST(request: NextRequest, { params }) {
  const apiKey = "";
  const apiUrl = "";
  const { botId } = params;

  const supabase = createRouteHandlerClient({ cookies });

  const { data: botData, error: fetchError } = await supabase
    .from('chatbot')
    .select('questions_counter, questions_limit')
    .eq('id', botId)
    .single();

  if (fetchError) {
    console.error('Error fetching bot data:', fetchError);
    return new NextResponse(
      JSON.stringify({ error: "Error fetching bot data" }),
      { status: 500 },
    );
  }



  const { questions_counter, questions_limit } = botData;

  console.log("questions_counter:", questions_counter);
  console.log("questions_limit:", questions_limit);

  // Check if the questions_counter is less than the questions_limit
  if (questions_counter >= questions_limit) {
    return new NextResponse(
      JSON.stringify({ error: "Questions limit reached" }),
      { status: 403 },
    );
  }

  try {
    console.log("Bot ID", botId);
    const response = { data: { message: "Message sent" } };

    const { data: rpcData, error: rpcError } = await supabase.rpc('increment_questions_counter', {
      chatbot_id: botId
    });

    console.log("rpcData:", rpcData);

    if (rpcError) {
      console.error('Error updating questions_counter:', rpcError);
      return new NextResponse(
        JSON.stringify({ error: "Error updating questions_counter" }),
        { status: 500 },
      );
    }

    // const new_questions_counter = questions_counter + 1;

    // console.log("new_questions_counter:", new_questions_counter);

    //     // Increment the questions_counter directly
    // const { data: updateData, error: updateError } = await supabase
    //   .from('chatbot')
    //   .update({ 
    //     questions_counter: new_questions_counter 
    //   })
    //   .eq('id', botId);

    // console.log("updateData:", updateData);


    // if (updateError) {
    //   console.error('Error updating questions_counter:', updateError);
    //   return new NextResponse(
    //     JSON.stringify({ error: "Error updating questions_counter" }),
    //     { status: 500 },
    //   );
    // }


    return new Response(JSON.stringify(response.data), { status: 200 });
  } catch (error) {
    console.error('Error sending message:', error);
    return new Response(JSON.stringify({ error: 'Error sending message' }), {
      status: 500,
    });
  }
}
```

## Expected behavior

I'm not sure exactly where I'm doing this wrong... Because when I look at the logs it works and is status 200/204. Same with updating it directly, it seems like both of them hasn't incremented my questions_counter at all. 

I have tried using supabase admin to check if it is an RLS issue but it seems like that's not the case. 

I have been able to update the other columns of my table so I know this is the correct way to call it at least in my other columns but for this one...it just doesn't work and I'm confused. 

Can anyone help me understand where I'm wrong? 

Thank you. 

## Screenshots
![image](https://github.com/supabase/supabase/assets/126068928/35740bdd-a633-4aa3-b336-488163514dfd)

## System information

- OS: Mac
- Browser: Chrome
- Version of supabase-js: 2.39.7, @supabase/auth-helpers-nextjs: ^0.9.0
- Version of Node.js: ^18.0

**Comment by chiho13** [comment]
my rpc functions works fine in local but not in production. checked all the permissions. all fine

**Comment by antoineross** [comment]
As it turns out it does work. The problem lied in the fact that I was using an HTML file to interact with the public script of my app — completely unauthenticated. It was an RLS problem. 

I could get the other tables but I couldn't update. Fixed. Closing this now. Thanks.
