### ISSUE TITLE
Prisma freezes when migration is triggered

### ISSUE THREAD

**Issue by maciejfiglarz** [supabase/supabase#26953]
hello,
I have problem with supabase in prisma. When I trying make migration I have frozen like on the screen. I added DIRECT_URL and SHADOW_DATABASE_URL to another instance db from supabase, but nothing changed.

![image](https://github.com/supabase/supabase/assets/40183126/51f43bc3-5697-4aa6-b7f0-4f32a55f6ccd)

prisma/schema.prisma
![image](https://github.com/supabase/supabase/assets/40183126/18c9c562-d71b-49fd-8929-1c271a6f5325)

.env
![image](https://github.com/supabase/supabase/assets/40183126/ee2dffb3-d471-4334-b243-27914ab2948d)

 - @prisma/client: 5.13.0,
 - prisma: 5.14.0

**Comment by encima** [comment]
Hi @maciejfiglarz,

Please follow the instructions on our [Prisma guide](https://supabase.com/partners/integrations/prisma) when setting up

**Comment by fugudesign** [comment]
Hi,

Same issue here…
@encima, even on following the Prisma guide…
This is frozen with the --create-only tag too.

Has someone an explanation or resolution directions please?
@maciejfiglarz have you found a fix?

Thanks a lot.

**Comment by encima** [comment]
@fugudesign do you experience the same issue when using direct connections?

If using Supavisor, have you added the arguments as outlined in the guide?

**Comment by fugudesign** [comment]
@encima 
Thanks for your answer.

I'm sorry, i was wrong in my first post…

Actually, i'm in a RedwoodJS environment, and i cannot do the migrate work from Redwood.
I followed this tuto : https://supabase.com/docs/guides/getting-started/quickstarts/redwoodjs

But it is frozen on the `yarn rw prisma migrate dev` command.
So, to try to fix it, i decided to follow this prisma guide, but nothing change.
https://supabase.com/partners/integrations/prisma

However, i just tried to follow the prisma guide from scratch, and it works fine.

Have you some information about the Supabase/Redwood config to make it work please ?

Thanks in advance.
Vince

**Comment by fugudesign** [comment]
@encima 
I just found the solution!

In the Supabase guide (Redwood+Supabase), there is a mistake in the env configuration (i suppose).
I been able to fix it by inverting the name of the both env vars : 

DATABASE_URL is the one with the port 6543 and the params (pgbouncer=true&connection_limit=1).
DIRECT_URL is the on with the port 5432 and no params.

And that works!

To find it i recheck many times the configuration in the Prisma Guide that is working (https://supabase.com/partners/integrations/prisma)

Maybe a good idea to update the Redwood + Supabase guide!

**Comment by maciejfiglarz** [comment]
Unfortunately it still doesn't work for me.

This is my urls:
![image](https://github.com/supabase/supabase/assets/40183126/3539fddf-b8fb-42ae-b949-15b79b25fe6e)

Anyone have idea what is wrong here?

**Comment by fugudesign** [comment]
I'm not an expert but i think you should use the same account for the both urls. Here you clearly use two different accounts. 
Maybe you should try to use only one account.

**Comment by fugudesign** [comment]
And maybe you really should change your credentials now. 🤓
I think it's not a good idea to communicate them here... 😬

**Comment by maciejfiglarz** [comment]
@fugudesign  DATABASE_URL and DIRECT_URL should provide to the same database?
The configuration at the top started working.

**Comment by maciejfiglarz** [comment]
> And maybe you really should change your credentials now. 🤓 I think it's not a good idea to communicate them here... 😬

Credentials will not work. I've changed something there ;)

**Comment by fugudesign** [comment]
> @fugudesign DATABASE_URL and DIRECT_URL should provide to the same database? The configuration at the top started working.

Yes!
The guide explain why those both urls:

> We will use the pooler both in Transaction and Session mode. Transaction mode is used for application queries and Session mode is used for running migrations with Prisma.

So one of the urls will be used for the prisma migrations and the other for the queries, so obviously those both actions are about the same database, so obviously the both have to be connected to the same database.

**Comment by Hallidayo** [comment]
Hi everyone - just checking in here is this issue now working for you all?

**Comment by gschattenhofer** [comment]
> @encima I just found the solution!
> 
> In the Supabase guide (Redwood+Supabase), there is a mistake in the env configuration (i suppose). I been able to fix it by inverting the name of the both env vars :
> 
> DATABASE_URL is the one with the port 6543 and the params (pgbouncer=true&connection_limit=1). DIRECT_URL is the on with the port 5432 and no params.
> 
> And that works!
> 
> To find it i recheck many times the configuration in the Prisma Guide that is working (https://supabase.com/partners/integrations/prisma)
> 
> Maybe a good idea to update the Redwood + Supabase guide!

That is correct, we had the same issue mentioned and switching the urls fixed on our case. These two docs are inconsistent:

❌ Wrong documentation: https://supabase.com/docs/guides/getting-started/quickstarts/redwoodjs
```
# Transaction mode connection string used for migrations
DIRECT_URL="postgres://postgres.[project-ref]:[db-password]@xxx.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
# Session mode connection string — used by Prisma Client
DATABASE_URL="postgres://postgres.[project-ref]:[db-password]@xxx.pooler.supabase.com:5432/postgres"
```

✅Correct documentation: https://supabase.com/partners/integrations/prisma
```
DATABASE_URL="" # Set this to the Transaction connection pooler string you copied in Step 1
DIRECT_URL=""  # Set this to the Session connection pooler string you copied in Step 1
```

**Comment by encima** [comment]
PRs welcome!

**Comment by a4vg** [comment]
Will create a PR in a moment of that's okay.
