### ISSUE TITLE
[FEATURE REQUEST]: Set URLs for auth templates

### ISSUE THREAD

**Issue by jean-smaug** [supabase/supabase#2695]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like a high level of customization on auth templates (i18n, design...)

## Describe the solution you'd like

Instead addition of template, we could set an URL that must return an HTML that will be send for magic auth.

It could be a post request that send us all accessible informations and our endpoint have to answer with a valid HTML.

```
POST https://mydomain.com/templates/email-magic-link
{ "ConfirmationURL": "https://supabase.com/confirm?token..." }
```

## Describe alternatives you've considered

No alternative for the moment

## Additional context

![image](https://user-images.githubusercontent.com/22884251/128061509-58d8f78c-c95f-4ce7-97b6-eb6ddbf962cc.png)

**Comment by inian** [comment]
This is now possible @jean-smaug https://supabase.io/blog/2021/07/28/supabase-auth-passwordless-sms-login#generate-confirmation-links
