### ISSUE TITLE
Password is always too weak. Even with 2048 characters.

### ISSUE THREAD

**Issue by matfeinikolaev** [supabase/supabase#2696]
# Bug report

## Describe the bug
When creating a new project, the form doesn't accept any password for the Database password, saying "You need a stronger password". The "Create new project" button is hence disabled. I have tried all variants of passwords, with uppercase, lowercase letters, digits, symbols, in strings of up to 2048 characters. Nothing gets accepted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://app.supabase.io/'
2. Click on 'New project'
3. Choose your organization
4. Type in any password
5. See error
Quite possible that it occurs for some users.

## Expected behavior

It accepts the password and lets me create a project

## Screenshots

![image](https://user-images.githubusercontent.com/45239725/128062179-300e0057-ac46-443c-a421-d8b735ef2afc.png)

## System information

- Windows
- Chrome, Opera, Firefox, Edge

**Comment by darora** [comment]
Looks similar to #2609 . @matfeinikolaev can you check JS console for any errors, and the network traffic for any failed requests?

**Comment by inian** [comment]
From [this discussion](https://github.com/supabase/supabase/discussions/2620#discussioncomment-1123009), the payload _is_ sent correctly to the server, but it still says length of undefined error. 

Are you running any local antivirus like Bitdefender which might be interfering with network operations? We have had a few users report problems because of that

**Comment by IzMichael** [comment]
Woah! I just disabled my Bitdefender and it works!

**Comment by inian** [comment]
Gah..I have submitted a false negative report to them yesterday. 

Can you help submit the form here? https://www.bitdefender.com/consumer/support/answer/40673/ It might help if it is coming from actual bitdefender users. Mention app.supabase.io and supabase.co as the domains as false positives.
