### ISSUE TITLE
Questions and Issues Regarding Local Deployment of Supabase

### ISSUE THREAD

**Issue by huiali** [supabase/supabase#26960]
Hello Supabase Team,

I have been researching the local version of Supabase for the past two weeks, and I am very passionate about this project. However, I have encountered several issues and have some questions that I hope you can help clarify:

1、Single Organization and Project Limitation:
I found that the local version only allows for one organization and one project. Is there a way to enable support for multiple organizations and projects, or would this require significant customization on my part? Is there an existing platform version that supports this?

2、 Cloud Functions Support:
The local version does not support cloud functions. I tried changing the variable NEXT_PUBLIC_IS_PLATFORM=true to true, which led me to the login interface, but logging in results in an error. Is there a recommended way to enable cloud functions in the local version?

3、Support for Multiple Databases:
Does Supabase support multiple databases, such as sharing multiple instances across multiple projects? Is this managed automatically, or does it require manual configuration?

4、Authentication Integration with Casdoor:
I am using Casdoor for authentication in my local setup. How can I integrate Casdoor with Supabase, or is there a way to support custom authentication methods?

I would greatly appreciate any guidance or solutions you can provide regarding these issues. Thank you for your time and support.

Best regards,

**Comment by encima** [comment]
Hello @huiali 

Thanks for opening. I will try and address all of these and, where the documentation is lacking, please highlight them and we can get them in the docs.

1. **Single project** - Self-hosted Supabase does only allow a single project / single org and I am afraid it is not possible to modify as the local version runs without a management API/database to handle multiple projects. You can run multiple instances to allow for multiple projects
2. **Cloud functions** - Edge functions are supported in the self-hosted version. You can create them with `supabase functions new NAME`
3. **Support for multiple databases** - A database is unique to a project and cannot be shared. You can, however use wrappers to connect to other databases
4. **Auth** - Supabase has Auth built in, so it is easiest to use that. However, you can integrate with almost any Auth provider, here is an [example using Clerk](https://supabase.com/partners/integrations/clerk) and the steps are similar

**Comment by huiali** [comment]
Hello @encima,
﻿
Thank you for your prompt response and for addressing my initial queries. I appreciate the clarification provided. I have a couple of follow-up questions and an illustration regarding one of the points:

Cloud Functions Support:

Regarding cloud functions, I am particularly interested in enabling them in my local environment. I attempted to set the variable NEXT_PUBLIC_IS_PLATFORM=true, which led to the login interface, but I encountered errors upon logging in. Could you provide a detailed guide or recommended steps to enable cloud functions in the local version? Below is a screenshot of the error I encountered:

![image](https://github.com/supabase/supabase/assets/29728900/fc646013-aa91-48a9-8991-a6eef22f02fb)

Other Issues:

I am satisfied with the explanations provided for my other questions. My main focus now is on enabling cloud functions locally.
Thank you once again for your assistance and support.

Best regards,

**Comment by encima** [comment]
Hi @huiali 

Glad that it helped! A guide for hosting edge functions locally is [here](https://supabase.com/docs/reference/self-hosting-functions/introduction)
The creation and deployment is managed completely by the CLI so the dashboard does not include them.

For logs, you can use the CLI: `supabase functions serve` and logs will be streamed in the terminal

**Comment by huiali** [comment]
I am currently unable to render the cloud functions interface on the dashboard. Although I set the NEXT_PUBLIC_IS_PLATFORM=true variable, which made the menu visible, I encountered errors and was unable to access it. How can I properly configure this setting to render the cloud functions interface without errors?
﻿
Thank you for your help.

**Comment by encima** [comment]
That variable is for the Platform dashboard and is not available in self-hosted.

**Comment by huiali** [comment]
Hello @encima,
﻿
Thank you for your prompt response and for addressing my initial queries. I appreciate the detailed explanations provided.
﻿
However, I still have some questions regarding enabling the cloud functions interface on the dashboard and supporting platform functionalities in a self-hosted environment:
﻿
Cloud Functions Interface on the Dashboard:
I understand that the variable NEXT_PUBLIC_IS_PLATFORM=true is for the Platform dashboard and is not available in the self-hosted version. However, I really need to access and manage cloud functions via the dashboard for my local environment. Is there any way or workaround to enable this feature in the self-hosted version, or is it strictly limited to the hosted platform?
﻿
Platform Functionalities Support:
Given the limitations of the self-hosted version, such as single organization and project, and the absence of a management API/database for handling multiple projects, is there any plan to extend these features to the self-hosted version in the future? Alternatively, can you provide any guidance or resources on how to implement such customizations if we decide to pursue this on our own?
﻿
I am particularly interested in a solution that allows me to use the Supabase platform's full potential in a self-hosted setup, including multiple organizations, projects, and a fully functional dashboard for cloud functions.
﻿
Thank you for your assistance and support. I look forward to your guidance on these matters.
﻿
Best regards,

**Comment by encima** [comment]
Hi @huiali 

To address the questions in order:
1. Modifying the `PLATFORM` variable is not supported and not recommended, yes, you would need to use the hosted version, I am afraid. Functions can be created and deployed using the CLI, as normal, however and you can view logs from each call.
2. Currently, this is not possible and a single project, single org is the self-hosted version we offer. To my knowledge, there is no plan to modify this but I will raise it up internally for a more official response

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
