### ISSUE TITLE
Create new organization falls into a permanent loop.

### ISSUE THREAD

**Issue by matfeinikolaev** [supabase/supabase#2697]
# Bug report

## Describe the bug

After filling the name in the "Create new organization" form, it redirects to https://app.supabase.io/new/undefined and only displays a spinner forever. No new organization gets created.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://app.supabase.io/new'
2. Fill in the name field
3. Click "Create organization"

## Expected behavior

A new organization is created.

## Screenshots

![image](https://user-images.githubusercontent.com/45239725/128063912-17debc5b-fe48-48a9-aa14-716976aca0b8.png)

## System information

- OS: Windows
- Browser: chrome, opera, firefox, edge

**Comment by inian** [comment]
We think the underlying cause of this issue is the same as the other one you reported @matfeinikolaev https://github.com/supabase/supabase/issues/2696
