### ISSUE TITLE
Column does not exist (when loading json in dashboard)

### ISSUE THREAD

**Issue by Tammerabi** [supabase/supabase#27000]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Large json no longer automatically loads, and the manual load button doesn't work.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to row that has a jsonb column (with camelCase name) with a large blob in it.
2. Click to expand, the full blob no longer expands, but a button saying "Load full value" is shown
3. Click Load full value
4. See error that column <lowercased-column-name> doesn't exist

## Expected behavior

The full object used to be visible without having to click an additional load button. A return to that would be ideal. Failing that, at least having the "Load full value" button work would suffice. 

## Screenshots

![image](https://github.com/supabase/supabase/assets/4252546/362890b2-f0e5-4ac2-bd6e-e91bff9b5851)

## System information

- OS: [macOS]
- Browser (if applies) [chrome]

**Comment by monicakh** [comment]
We have a PR for this, it should get deployed to production once merged: https://github.com/supabase/supabase/pull/27036.
