### ISSUE TITLE
Cant use GraphQL introspection query after following tutorial for RBAC

### ISSUE THREAD

**Issue by michaelchiche** [supabase/supabase#27015]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I have 2 bugs in one. Please tell me if I should split them between 2 issues

- After following the tutorial for roles (https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac?queryGroups=language&language=plpgsql). When running the Introspection query, I get this error message: 
```json
{
  "errors": [
    {
      "message": "Names must only contain [_a-zA-Z0-9] but \"channels.delete\" does not.",
      "extensions": {},
      "stack": "a@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:67:10881\na@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:9729\ns@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:10021\n81489/eg/this._values<@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:21176\neg@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:21020\n56156/h/h</<@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:59289\n56156/h/h</<@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:59449\n56156/h/h<@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:59848\nr@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:80:704\nh@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:81:58501\n57518/s6/y</<@https://supabase.com/dashboard/_next/static/chunks/6729-beb9a519183d7ba7.js:36:4856\n"
    }
  ]
}  
```
- I also get an error `PGRST204`: "Column 'xxx' of relation 'yyy' does not exist", which seems to be related to this: https://github.com/PostgREST/postgrest/issues/3361 while using the supabasejs client, but it work no problem when using the GraphQL API on the web interface

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

- Introspection query should work after following a tutorial, so either update the tutorial, or update the code (which seems more logic to me, because the tutorial is not doing anything fancy)
- Be able to use the supabasejs/postgrest work as the GraphQL one

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Hi there, thanks for opening!

The tutorial does create a valid enum but, unfortunately, the GraphQL spec does not allow a `.` in the value (see [docs](https://supabase.github.io/pg_graphql/configuration/#enum-variant)).
To fix, you can follow the convention `channels_delete` and `channels_edit`

If you would like to add a note to the guide to mention this behaviour is different for GraphQL, please do open a PR and mention this issue!

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
