### ISSUE TITLE
Password is never strong enough

### ISSUE THREAD

**Issue by inian** [supabase/supabase#2706]
### Discussed in https://github.com/supabase/supabase/discussions/2620

<div type='discussions-op-text'>

<sup>Originally posted by **IzMichael** July 29, 2021</sup>
Hi! I'm trying to create my first database, but whatever password I use, it says it's not strong enough. I've tried using passwords like 'wzyijmX6ql$V7ghHCXWWtmi' and it's not strong enough apparently.</div>

**Comment by inian** [comment]
Our password check endpoint is failing with a 500 for some reason, even though the payload is being sent correclty

**Comment by darora** [comment]
Also #2696 and #2609

**Comment by inian** [comment]
Ah closing as duplicate
