### ISSUE TITLE
CloudFlare Workspace link points to Supabase in Docs vs CloudFlare.

### ISSUE THREAD

**Issue by sosensible** [supabase/supabase#27094]
# Improve documentation

## Link 

https://supabase.com/partners/integrations/cloudflare-workers

## Describe the problem

Your link to the CloudlFlare Dashboard needs to point at the domain, not just the routed folder. It tries to find a page on the Supabase site vs the actual CloudFlare Dashboard.

## Describe the improvement

My actual suggestion is open the docs to let us submit pull requests to such corrections. Without that, just put https:// in front of the link in the docs.

**Comment by Hallidayo** [comment]
Hi @sosensible - thank you for opening this issue, This part of the supabase website is only fixed by an internal team member. I'm going to mark this an internal and flag.

**Comment by fsansalvadore** [comment]
Thanks @sosensible, this has been fixed.

ps. we might make this integrations section editable from the community eventually, but it's not on the roadmap for the near future.
