### ISSUE TITLE
Adding South African region for deploying projects

### ISSUE THREAD

**Issue by fbele** [supabase/supabase#27090]
### Discussed in https://github.com/orgs/supabase/discussions/21429

<div type='discussions-op-text'>

<sup>Originally posted by **fbele** February 21, 2024</sup>
Hi there,

Since Supabase Cloud is using AWS to deploy projects on the cloud, and AWS does have does have Data Center in South Africa (Cape Town) region available to my knowledge, can it be expected that you (the Supabase masters) will also make this region available?

Because African region in general is the only one that is not covered at all and it's kind of shame, that such a great product isn't available there.</div>

**Comment by encima** [comment]
@fbele thanks for opening! I have moved your Discussion to a Feature Request so the team can track it. As it is already open there, I will close this one.

In future, please do only open either an Issue or a Discussion (not both) as it makes it harder to track these requests.
