### ISSUE TITLE
How to refresh token when we are using Google Oauth Provider?

### ISSUE THREAD

**Issue by harshithpabbati** [supabase/supabase#271]
We are using Google Oauth Provider which gives us access_token, refresh token but is there a URL endpoint to call for refreshing the token?

**Comment by soedirgo** [comment]
Hey @harshithpabbati!

Copying Ant's answer from Slack:

> Hey Harshith Pabbati ! You should be able to send the refresh token to `POST <your-ref>.supabase.co/auth/v1/token?grant_type=refresh_token` and with JSON body `{refresh_token:'the token'}`

> Docs here: https://github.com/supabase/gotrue#endpoints

Thanks for asking :)
