### ISSUE TITLE
Update example on github 

### ISSUE THREAD

**Issue by wojtekKrol** [supabase/supabase#27119]
# Improve documentation

## Link 
https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?queryGroups=language&language=ts

There should be included information about this part:
https://supabase.com/docs/guides/auth/server-side/nextjs

Add a link to the page which needs improvement (if relevant)

## Describe the problem
Docs point to https://github.com/supabase/supabase/tree/master/examples/user-management/nextjs-user-management as example, this is some old example, 

docs refer to `token_hash` and `type` 

## Describe the improvement

Update code example to match the one in docs, `signUp` methods return `code` and not `token_hash` and `type`

**Comment by siddheshJungade** [comment]
Hi there,

I'm new to open source and would love to contribute. Can I work on this issue?

Thanks!

**Comment by encima** [comment]
@wojtekKrol thanks for opening, this is indeed needed.

@siddheshJungade anyone is welcome to contribute, please do! Check out our guide on [contributing](https://github.com/supabase/supabase/blob/e8ca554beef72cb7ca61cf9e5570ea91f67a6ef7/CONTRIBUTING.md) here
