### ISSUE TITLE
Make email verification optional during email/password signups

### ISSUE THREAD

**Issue by Symasia** [supabase/supabase#2715]
# Feature request

Make email verification an optional factor, it shouldn't be just one of the two where you get it or not.

## Is your feature request related to a problem? Please describe.

Currently, for some reason email/password auth requires the user to have verified their email address for a session to be created. This is extremely frustrating, because in most cases you would add additional user data excluding just the email and password of the user and because I don't do any inserts on the client and only at a server-level I have to send the user's token to the backend, but because the session is null I don't have a token to send.

For some reason when you disable email confirmation on the dashboard, the user is automatically verified despite the docs talking about email verification like this:

"If "Email Confirmations" is turned off, both a user and a session will be returned", aka it does not say anything about the email being automatically verified.

Redirecting the user to a page where they can add in the additional user data is not ideal due to various UX concerns.

## Describe the solution you'd like

If email verification is optional, the email shouldn't be automatically verified. It should just be unverified, and a session should be created.

In fact I would expect disabling email verification to not just automatically consider it verified, I would expect it to be unverified so I can use `generateLink()` to send a verification email.

## Describe alternatives you've considered

Tried turning off email verification, but it just automatically verifies the email.

## Additional context

N/A

**Comment by subwaymatch** [comment]
+1 for this enhancement! As a reference, the passwordless email login flow with Firebase Auth doesn't require the user to confirm sign-up.

**Comment by kiwicopple** [comment]
Hey @subwaymatch @Symasia -I could be missing something here, but it looks like you just want to disable the confirmation emails? You just need to toggle `Disable email confirmations` in the Auth settings of your project - see the last toggle here:

![image](https://user-images.githubusercontent.com/10214025/129127777-6953ead6-88b0-4b74-b9e8-a6c6fc8d3d7a.png)

**Comment by subwaymatch** [comment]
@kiwicopple Sorry, I've deleted my previous response as I misread the OP's post.

Thanks!
