### ISSUE TITLE
Getting 502 error on "LOGS EXPLORER"

### ISSUE THREAD

**Issue by parthiban0661** [supabase/supabase#27177]
# Getting 502 error on "LOGS EXPLORER" using supabase cli

![image](https://github.com/supabase/supabase/assets/97081058/e52e10f5-ee3e-419a-9a36-745d1a8cef98)

Please help us to resolve this

**Comment by parthiban0661** [comment]
1) Supbase version 1.176.2
2)
docker ps -a
CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                   PORTS                                                                  NAMES
36e3324c6f0b   public.ecr.aws/supabase/studio:20240422-5cf8f30   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:54323->3000/tcp, :::54323->3000/tcp                            supab
ase_studio_ubuntu
9f53ca1f3103   public.ecr.aws/supabase/postgres-meta:v0.80.0     "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   8080/tcp                                                               supab
ase_pg_meta_ubuntu
3fd05f3518d6   public.ecr.aws/supabase/edge-runtime:v1.53.4      "sh -c 'cat <<'EOF' …"   2 minutes ago   Up 2 minutes             0.0.0.0:32768->8081/tcp, :::32768->8081/tcp                            supab
ase_edge_runtime_ubuntu
3e78c3127c27   public.ecr.aws/supabase/imgproxy:v3.8.0           "imgproxy"               3 minutes ago   Up 3 minutes (healthy)   8080/tcp                                                               supab
ase_imgproxy_ubuntu
8a89159caa72   public.ecr.aws/supabase/storage-api:v1.0.6        "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)   5000/tcp                                                               supab
ase_storage_ubuntu
122a911ca2a4   public.ecr.aws/supabase/postgrest:v12.0.1         "/bin/postgrest"         3 minutes ago   Up 3 minutes             3000/tcp                                                               supab
ase_rest_ubuntu
9a7031530770   public.ecr.aws/supabase/realtime:v2.28.32         "/usr/bin/tini -s -g…"   3 minutes ago   Up 3 minutes (healthy)   4000/tcp                                                               supab
ase_realtime_ubuntu
18e990526d1d   public.ecr.aws/supabase/inbucket:3.0.3            "/start-inbucket.sh …"   4 minutes ago   Up 4 minutes (healthy)   1100/tcp, 2500/tcp, 0.0.0.0:54324->9000/tcp, :::54324->9000/tcp        supab
ase_inbucket_ubuntu
be3bef38f002   public.ecr.aws/supabase/gotrue:v2.151.0           "auth"                   4 minutes ago   Up 4 minutes (healthy)   9999/tcp                                                               supab
ase_auth_ubuntu
ac8b616841c0   public.ecr.aws/supabase/kong:2.8.1                "sh -c 'cat <<'EOF' …"   4 minutes ago   Up 4 minutes (healthy)   8001/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp, :::54321->8000/tcp   supab
ase_kong_ubuntu
9ee6d3f3f636   public.ecr.aws/supabase/logflare:1.4.0            "sh -c 'cat <<'EOF' …"   4 minutes ago   Up 4 minutes (healthy)   0.0.0.0:54327->4000/tcp, :::54327->4000/tcp                            supab
ase_analytics_ubuntu
bd9381050a31   public.ecr.aws/supabase/postgres:15.1.1.41        "sh -c 'cat <<'EOF' …"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:54322->5432/tcp, :::54322->5432/tcp                            supab
ase_db_ubuntu
3eaf96e46a27   public.ecr.aws/supabase/vector:0.28.1-alpine      "sh -c 'cat <<'EOF' …"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:54328->9000/tcp, :::54328->9000/tcp                            supab
ase_vector_ubuntu


3) In console getting below error

{
  "code": 502,
  "errors": [],
  "message": "Something went wrong! Unknown error. If this continues please contact support.",
  "status": "UNKNOWN"
}

**Comment by parthiban0661** [comment]
above is the issue

**Comment by encima** [comment]
Same error is tracked in #26785 (possibly #18891) as well. Closing this one and please discuss in #26785 

@saltcod this seems to be an issue with the query the frontend uses, if you select `Postgres logs` and edit the query to only select `event_message` then it works.
