### ISSUE TITLE
！！！QQ mailbox registration verification link！！！

### ISSUE THREAD

**Issue by qifendev** [supabase/supabase#27186]
<img width="1235" alt="image" src="https://github.com/supabase/supabase/assets/45928182/16fa6e70-fdd9-46ce-9b94-73f13b50efb9">

<img width="1409" alt="image" src="https://github.com/supabase/supabase/assets/45928182/3c01bd04-0caf-4ed0-853c-7fb9c00da653">

I customized the QQ stmp mail service
This problem is not a problem in Google Mail

The email is sent to QQ mailbox. The link is problematic. The email cannot be verified after clicking the registration verification. Note that the link parameters have changed.

**Comment by encima** [comment]
This looks like an issue with the mail provider rather than Supabase itself. See the docs [here](https://supabase.com/docs/guides/auth/auth-email-templates#email-prefetching) on email prefetching.

You can also use a custom template and provide a button that redirects to the link
