### ISSUE TITLE
Charts failed to show empty data sometimes

### ISSUE THREAD

**Issue by alon710** [supabase/supabase#2718]
# Bug report

## Describe the bug

When I hover my chart bars, and there is no data, sometimes it shows 0 requests but sometimes it shows no data at all.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the main project page
2. Hover on the chart bar 
3. See the error

## Expected behavior

I think now data should always appear the same 

## Screenshots

https://user-images.githubusercontent.com/35544532/128176028-44e978f8-2de6-49da-ab1d-6f08adaa47e8.mp4

## System information

- OS: Fedora Linux
- Browser Chrome

Thanks!

**Comment by kiwicopple** [comment]
Hey @alon710  - sorry about that, it was a faulty data pipeline. This should be fixed now. If your data still isn't showing up feel free to comment here and we'll reopen this issue 👍

**Comment by alon710** [comment]
I think you misunderstood the bug, when I hover an empty column it shows inconsistent values.
For example (all for empty values as shown on screenshots):
- 0
- 0 bytes
- Nan undefined
- Empty value

Examples:

![1](https://user-images.githubusercontent.com/35544532/130577361-80710816-326e-4139-9ebb-7524d976d050.jpg)

![2](https://user-images.githubusercontent.com/35544532/130577375-c6d569cf-58ad-4d05-adcc-8c63a1aa0fb0.jpg)

![3](https://user-images.githubusercontent.com/35544532/130577419-f7d40812-c794-4d3e-a78b-32aeefc2ca89.jpg)

![4](https://user-images.githubusercontent.com/35544532/130577456-d64c3a87-afd6-4b7c-bff1-e0fad2895cb2.jpg)


@kiwicopple

**Comment by kiwicopple** [comment]
Got it, thanks for the screenshots !

Reopening so we can fix this

**Comment by joshenlim** [comment]
hey there @alon710! a couple of fixes have been pushed out - can i check if this is still happening for you?

**Comment by alon710** [comment]
> hey there @alon710! a couple of fixes have been pushed out - can i check if this is still happening for you?

Tried to check but I don't have traffic on my project so my charts are all empty.
sorry 👍🏽

**Comment by joshenlim** [comment]
No worries at all :) I'm going to go ahead and close the issue for now but feel free to reopen if this issue still persists!
