### ISSUE TITLE
Self Hosted Supabase throws 403 on schemas-list when behind CloudFlare/Access over HTTPS

### ISSUE THREAD

**Issue by sashman-jaspin** [supabase/supabase#27189]
## Describe the bug

We put a self hosted Supabase behind just CloudFlare with the hope of using Access for easy SSO and it works great, except for at least one API call.  /api/pg-meta/default/query?key=schemas-list is throwing a 403 behind the HTTPS proxy.  The error message is : {"error":{"message":"Method GET Not Allowed"}}  

## To Reproduce

Set up Supabase via Docker as described : https://www.youtube.com/watch?v=FqiQKRKsfZE
Change the SUPABASE_PUBLIC_URL in .env to point to a domain name with https.
Add a flexible DNS proxy on cloudflare that points to the public IP Supabase is listening to

## Expected behavior

I expect /api/pg-meta/default/query?key=schemas-list not to throw a 403 since basic auth was entered and nothing else is throwing 403s.

## Screenshots

![Capture_supabase](https://github.com/supabase/supabase/assets/1105217/056642c4-f2fa-4ca0-a11d-7b9b4341ea0e)

## System information

- OS: Ubuntu 22.04.3 LTS
- Browser : chrome, safari, firefox, edge,
- Version of supabase-js: Whatever is packaged in the curernt docker image
- Version of Node.js: Whatever is packaged in the current docker image

**Comment by encima** [comment]
Are you using Cloudflare Proxy or only DNS?

**Comment by sashman-jaspin** [comment]
Cloudflare proxy.

**Comment by encima** [comment]
Ah, that's the issue. This is unsupported I'm afraid. If you use DNS only then it should work. Let me know if that solves it!

**Comment by sashman-jaspin** [comment]
DNS only does work, but feel as though I'm going to hit the same issue with a reverse proxy nginx with lets encrypt.  Will report back if an issue.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
