### ISSUE TITLE
Certificate error.

### ISSUE THREAD

**Issue by luisfcofv** [supabase/supabase#27208]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

There seems to be a misconfiguration with the Supabase edge functions.

I’m encountering an error when using the fetch function from `npm:graphql-request@6.1.0`.

I have two Supabase instances (production and staging) running the same code. After deploying to staging recently, I started seeing this error. I’m concerned about deploying to production and encountering the same issue.

This was working fine yesterday. I’ll continue investigating and provide more information as I find it.

```
NotFound: path not found server/certs/prod-ca-2021.crt: readfile './server/certs/prod-ca-2021.crt'
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:832:10)
    at HttpsClientRequest._getClient (node:https:99:25)
    at HttpsClientRequest._writeHeader (node:http:393:25)
    at HttpsClientRequest._send (ext:deno_node/_http_outgoing.ts:405:12)
    at HttpsClientRequest.write_ (ext:deno_node/_http_outgoing.ts:316:16)
    at HttpsClientRequest.write (ext:deno_node/_http_outgoing.ts:293:17)
    at writeToStream (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/node-fetch/2.7.0/lib/index.js:654:8)
    at file:///tmp/sb-compile-edge-runtime/node_modules/localhost/node-fetch/2.7.0/lib/index.js:1726:3
    at new Promise (<anonymous>)
    at fetch (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/node-fetch/2.7.0/lib/index.js:1447:9) {
  name: "NotFound",
  code: "ENOENT"
}
```

## System information

- OS: macOS
- Version of supabase-js: 1.176.4

**Comment by encima** [comment]
Hi @luisfcofv ,

Thanks for opening, we will need more information here in order to help.

- This is in an edge function right? Can you post the code from the edge function?
- Is this the certificate for your Supabase app or for something else?
- Have you verified that the path exists and is valid?

**Comment by luisfcofv** [comment]
Yes, this is an edge function hosted by Supabase.

We haven't set any certificate at all. It looks like it's an internal Supabase certificate, maybe the SSL for the database (it has the same name).

**Comment by encima** [comment]
Possibly, but this looks to be within the `node-fetch` module, I do not think this is Supabase related but let's make sure.

- Can you verify the certificate for your staging edge function is valid?
- Are you using a custom domain?
- Is the error on deploy of a function or once it is called?

**Comment by luisfcofv** [comment]
I’ve found the issue, and it was my mistake.

While trying to set up Drizzle in the edge functions and enforce SSL, I set the environment variable `NODE_EXTRA_CA_CERTS` to a random path I found in a GitHub thread out of desperation. This caused issues with the node-fetch module, it seems.

I’m closing this ticket, but hat's off for the quick response.

On another note, it would be great if you could create a guide on setting up Drizzle with Supabase edge functions and enforcing SSL connections to the database. All the guides I’ve found don’t enforce SSL and work smoothly, but I couldn’t get it to work when enforcing SSL.

**Comment by encima** [comment]
Glad it was resolved :D 

Please feel free to open a new issue for the guide request and I will try to get something out next week!
