### ISSUE TITLE
Not working after upgrading from 1.11.11 to 2.2.1

### ISSUE THREAD

**Issue by zhushuihua** [supabase/supabase#27238]
Previously I was using Supabase 1.11.11. After upgrading to Supabase 2.2.1. The query stops working.
final result = await client.from('result_record').select().eq('homework_uuid', uuid);
Here the column homework_uuid is a **uuid** and a foreign key.

**Comment by encima** [comment]
Please can you:
- recreate this ticket and follow the issue template
- include the error you are receiving
- ensure your Supabase project is up to date
Thanks!
