### ISSUE TITLE
AuthRetryableFetchError when signing up with additional data

### ISSUE THREAD

**Issue by Chalwe19** [supabase/supabase#27239]
I am trying to sign up and create a profile following this tutorial: [https://supabase.com/docs/guides/auth/managing-user-data?language=dart](https://supabase.com/docs/guides/auth/managing-user-data?language=dart) but i keep getting 

> AuthRetryableFetchError  

on my flutter app. But when i remove remove the trigger everything is working properly i am able to sign up. what could be the issue?
my stackTrace
`I/flutter ( 7081): AuthException(message: AuthRetryableFetchError, statusCode: null)
I/flutter ( 7081): #0      GotrueFetch._handleError (package:gotrue/src/fetch.dart:39:7)
I/flutter ( 7081): #1      GotrueFetch._handleRequest (package:gotrue/src/fetch.dart:141:13)
I/flutter ( 7081): <asynchronous suspension>
I/flutter ( 7081): #2      GotrueFetch.request (package:gotrue/src/fetch.dart:88:12)
I/flutter ( 7081): <asynchronous suspension>
I/flutter ( 7081): #3      GoTrueClient.signUp (package:gotrue/src/gotrue_client.dart:214:18)
I/flutter ( 7081): <asynchronous suspension>`

**Comment by Hallidayo** [comment]
Hi @Chalwe19 - Is this a brand new Flutter app if so you could have a look at [this](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter) guide which has auth as part of the guide.

**Comment by Chalwe19** [comment]
Hi @Hallidayo , thank you I managed to figure it out, This was only occurring when i create my profiles table using the GUI but when i use the SQL editor it is working perfectly. What could be the reason behind this?
