### ISSUE TITLE
SUPABASE_PUBLIC_ANON_KEY undefined in local development

### ISSUE THREAD

**Issue by Fintasys** [supabase/supabase#27253]
# Bug report

## Describe the bug

SUPABASE_PUBLIC_ANON_KEY undefined in local development (deno)
SUPABASE_SERVICE_ROLE_KEY is defined

## To Reproduce

1. Create new instance with `supabase init`
2. Create a new edge function `supabase functions new test`
3. Edit the index.ts and add console prints to the top of the edge function
```
Deno.serve(async (req) => {

  console.info("anon_key", Deno.env.get("SUPABASE_PUBLIC_ANON_KEY"))
  console.info("role_key", Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"))
```
4. serve functions `supabase functions serve --no-verify-jwt`
5. call the endpoint `curl http://127.0.0.1:54321/functions/v1/test`

## Current behavior
serve console output displays
```
anon_key undefined
role_key ey....
```

## Expected behavior

serve console output displays
```
anon_key ey.....
role_key ey....
```

## Screenshots

<img width="366" alt="Screenshot 2024-06-14 at 2 23 48" src="https://github.com/supabase/supabase/assets/11667234/78fd41a2-e8b7-4293-b12a-cd059bc4aaed">

## System information

- OS: macOS

**Comment by charislam** [comment]
The default name of the variable is [`SUPABASE_ANON_KEY`](https://supabase.com/docs/guides/functions/secrets#default-secrets). Give that a try and feel free to reopen the issue if it still doesn't work!
