### ISSUE TITLE
Can't connect directly to postgres in powershell using psql

### ISSUE THREAD

**Issue by juliansommer** [supabase/supabase#27264]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

You cannot connect to postgres while using powershell. AM USING PSQL CONNECTION NOT URI. It will display wrong password (even though the password is correct). I switch to git bash and it works fine. I tried using transaction and session and neither worked. note: im using the same psql windows version in both its not like its a psql unix vs psql windows version bug or something just accessing it through different terminals.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database Settings
2. Switch connection string to PSQL
3. Copy
4. Paste command in powershell
5. Input password

## Expected behavior

PSQL in powershell should connect normally to the database as it does in git bash and i assume unix. unsure if this is a supabase or psql issue but it is so strange its saying the password is wrong, not a different error that would indicate its a windows problem.

## Screenshots

![image](https://github.com/supabase/supabase/assets/115516918/c0e04617-2f74-4116-bf7b-f60899b81ac3)
![image](https://github.com/supabase/supabase/assets/115516918/6c82abb2-c71e-4cef-be81-2c4ec8ca916c)

## System information

- OS: Windows

**Comment by encima** [comment]
Hey there, as the Warning prints, this is a Windows issue (due to different encodings) and, from there, it is a `psql` "issue".

You can check the `Notes for Windows Users` section towards the bottom of [this](https://www.postgresql.org/docs/current/app-psql.html) page for tips on rectifying.
