### ISSUE TITLE
Identity docs is deprecated regarding provider_id

### ISSUE THREAD

**Issue by Sangresz** [supabase/supabase#27277]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/identities

## Describe the problem

In this page the identity object definition is deprecated like explained in [this](https://github.com/supabase/supabase/issues/19620#issuecomment-1856418658) comment

## Describe the improvement

I would move the `id` attribute definition to the attribute `provider_id`

I can start working on a pr for a quick fix regarding this

<img width="869" alt="image" src="https://github.com/supabase/supabase/assets/96419810/2952cd60-9d07-4fa8-8349-5beae5f54397">

**Comment by Hallidayo** [comment]
Hi @Sangresz - thank you for opening this issue, feel free to open a pr for a fix 👍

**Comment by kmr-ankitt** [comment]
Can I fix this issue?

**Comment by Sangresz** [comment]
@kmr-ankitt i already made a pr regarding this, you can see it referenced above your commit
