### ISSUE TITLE
Database => Tables does not show all Tables (Auth etc.)

### ISSUE THREAD

**Issue by maxcodefaster** [supabase/supabase#2730]
# Bug report

## Describe the bug

Database => Tables does not show supabase tables like the auth tables. They are still present though as everything is running. They are just not visible to me in the interface. All other suer created tables are visible.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Go to 'Project => Database => Tables'

## Expected behavior

All tables should be visible and editable
## System information

- Browser Chrome

**Comment by kiwicopple** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/10214025/147562492-2007f731-9d74-492e-bc09-6eaf0920ee02.png">


You can now choose the schema from the Dashboard editor 🚢
