### ISSUE TITLE
Cannot create Database Functions from UI: `Failed to create database function: undefined`

### ISSUE THREAD

**Issue by davidfant** [supabase/supabase#27301]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

It's not possible to create functions from the Supabase UI. It always throws the error `Failed to create database function: undefined`. I've basically tried to create a function similar to the hello_world example from here https://supabase.com/docs/guides/database/functions but from the UI rather than through SQL

## To Reproduce

1. Add a new database function
2. Fill in the form in the same way as the screenshot below
3. Hit "Confirm"
4. 
## Expected behavior

A database function is created

## Screenshots

<img width="561" alt="image" src="https://github.com/supabase/supabase/assets/17096641/050da9e3-d0f0-489c-a057-9fd41bad172d">

## System information

- OS: macOS
- Browser (if applies) Arc
- Version of supabase-js: 2.43.4
- Version of Node.js: v21.1.0

## Additional context

It's possible to create the function through SQL, however then it's not possible to edit arguments, edit return type, etc through the UI

**Comment by encima** [comment]
Hi @davidfant 
Thanks for opening! Is this occurring in the self-hosted version of supabase or with the managed version?

**Comment by subhajitduttagupta** [comment]
Same problem, It is coming on self-hosted version

**Comment by truongnhatanh7** [comment]
same problem in local development

**Comment by davidfant** [comment]
> Hi @davidfant Thanks for opening! Is this occurring in the self-hosted version of supabase or with the managed version?

I'm running this locally on my computer

**Comment by brightidea** [comment]
Having same problem w/ self hosted supabase.

**Comment by AO19** [comment]
Same problem here, can't create functions and found this issue with the error description in the dashboard.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
