### ISSUE TITLE
Download CSV bug

### ISSUE THREAD

**Issue by LeDragunov** [supabase/supabase#2734]
# Bug report

## Describe the bug

"Export to csv" downloads a file without extension

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'SQL Editor'
2. Query data from any table
3. Click on "Results"
4. Download CSV
5. A file is downloaded without any file extension

## Expected behavior

 to download a file with .csv extension

## System information

- OS: [Windows]
- Browser [chrome]

## Additional context

I could solve the issue by renaming and adding .csv extension to the file.

**Comment by joshenlim** [comment]
hey @LeDragunov! a fix for this has been pushed out - do give it a spin and feel free to reopen this issue if you do run into any other issues for this

**Comment by Scott-Hickmann** [comment]
Hello, it seems like this issue is not yet fixed. We've been getting buggy formatting after exporting a CSV from a SQL query on the Supabase dashboard. We're unable to import the CSV file on tools like Google Sheet.
