### ISSUE TITLE
'click here' text in Supabase dashboard is missing link to docs

### ISSUE THREAD

**Issue by sandypockets** [supabase/supabase#2737]
# Bug report

## Describe the bug

The `click here` text should be a link to documentation, but it is not linked at all. 

## To Reproduce

It can be viewed while logged into Supabase, (at `https://app.supabase.io/project/<your-project-id>/database/pooling`), in the description of the `Pool Mode` section. 

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Login to Supabase, and go to **Database > Connection Pooling** (`https://app.supabase.io/project/<your-project-id>/database/pooling`)
2. Navigate to the **Configuration** section, near the top of the page. 
3. Within that section, scroll down to **Pool Mode**.
4. Note that the description below the text field is missing the link on words `click here`.

Text snippet:
```
Specify when a connection can be returned to the pool. To find out the most suitable mode for your use case, click here.
```

## Expected behavior
The words `click here` should lead to docs that can help the user learn which pool mode to choose. The document below is likely a good fit.

* [`https://supabase.io/docs/guides/database/connecting/connection-pooling`](https://supabase.io/docs/guides/database/connecting/connection-pooling)

## Screenshots

![https://i.imgur.com/USmhXIB.png](https://i.imgur.com/USmhXIB.png)

## System information

- macOS
- Chrome

## Additional context

N/A

**Comment by inian** [comment]
duplicate https://github.com/supabase/supabase/issues/2214
