### ISSUE TITLE
Supabase Wrapper > Firebase problem

### ISSUE THREAD

**Issue by AntDX316** [supabase/supabase#27375]
Supabase Wrapper > Firebase problem

So I got it linked successfully but I'm trying to query it with ChatGPT actions which works great for the other Tables I have but when I try to query the newly added Firebase Linked Tables, I get:

{
  "response_data": {
    "code": "42501",
    "details": null,
    "hint": null,
    "message": "permission denied for schema vault"
  },
  "status_code": 401,
  "action_id": "g-9f63ed13487c1764f30afad691d8416cab3de407"
}

Please fix. It should work like any other table.

The Supabase and Firebase are both mine. I want them open so they can work together.

**Comment by encima** [comment]
If this is hosted on Supabase, it might be better to open a support ticket to debug. The issue seems to be that the wrapper you are using does not have access to the credentials you saved in Vault.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. please send an email to [support@supabase.io](mailto:support@supabase.io) and we'll have a look at the above.
