### ISSUE TITLE
onAuthStateChange does not catch auth state changes across multiple windows

### ISSUE THREAD

**Issue by subwaymatch** [supabase/supabase#2739]
# Bug report

## Describe the bug

`supabaseClient.auth.onAuthStateChange()` does not work across multiple windows.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an `auth.onAuthStateChange()` listener with Supabase in a react app.

```
const { data: authListener } = supabaseClient.auth.onAuthStateChange(
      async (event, session) => {
        console.log(`UserContext.onAuthStateChange event=${event}`);
      }
);
```

2. Open two separate browser windows (where you haven't signed in yet in both windows)
3. Sign in from one of the two windows
4. The user will be signed in from that window. `SIGNED_IN` event will be fired in the window where you sign in, but the other browser window does not catch the `SIGNED_IN` event.

## Expected behavior

If the auth state changes in any of the windows, the change should be broadcasted to all windows. Firebase Auth broadcasts auth state changes to all windows. The current `onAuthStateChange()` listener requires a developer to poll auth state if a user has multiple windows open.

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of supabase-js: 1.21.0
 
## Additional context

The current `onAuthStateChange()` listener requires a developer to poll auth state if a user has multiple windows open. An example of this being an issue is if the user clicks on the magic link. This will sign in the user in a new window and leave the old window with a stale screen.

**Comment by KULTI1995** [comment]
I will send you a solution soon. it is quite simple, but requires some interference with the library.

**Comment by kiwicopple** [comment]
hey @KULTI1995 did you end up building this? It would be interesting if we can get this built into `gotrue-js`

**Comment by KULTI1995** [comment]
The solution was very simple.
I also partially solved native logging on React Native. A slight workaround, a small implementation and native logging will work, with SupaBase.

**Comment by subwaymatch** [comment]
@KULTI1995 Do you mind giving me a code snippet or a general direction on how to listen to auth state changes in multiple windows? 😀

Thanks!

**Comment by i-pip** [comment]
Hi @subwaymatch, you can fix this using a `window.onstorage` event listener and listening for an event with key `supabase.auth.token`. 

Here's a code snippet: 

```JavaScript
const [session, setSession] = useState(null);

  useEffect(() => {
    setSession(supabase.auth.session());
    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });
    window.onstorage = (e) => {
      if (e.key === "supabase.auth.token") {
        const newSession = JSON.parse(e.newValue);
        setSession(newSession?.currentSession);
      }
    };
  }, []); 
  ```
  
 This will work for both all auth change events

@kiwicopple, I'm working on adding this into `gotrue-js`

**Comment by kiwicopple** [comment]
this should now be working on the latest version of supabase-js 🎉 

https://github.com/supabase/gotrue-js/pull/184
