### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by WilliamFernsCodes** [supabase/supabase#27394]
# Improve documentation
![image](https://github.com/supabase/supabase/assets/172117888/17c11c82-2a13-4070-b620-d410aa7566f1)

## Link 
https://supabase.com/partners/integrations/clerk

**Comment by Hallidayo** [comment]
Hi @WilliamFernsCodes - thank you for opening the issue, this is one that can only be fixed internally and I will flag. Again thank you.

**Comment by Hallidayo** [comment]
We've just pushed an update for this issue and the image is now appearing:

<img width="1439" alt="Screenshot 2024-06-19 at 21 28 20" src="https://github.com/supabase/supabase/assets/22655069/ea49a224-8591-48eb-9450-7301d6a2fd7e">

Thank you for finding this issue @WilliamFernsCodes

**Comment by WilliamFernsCodes** [comment]
Great to see this was resolved. Thanks for closing this issue, it makes the world a better place.
