### ISSUE TITLE
 feat: Identify which email was verified during the two-step email update process

### ISSUE THREAD

**Issue by intercepted16** [supabase/supabase#27407]
### Discussed in https://github.com/orgs/supabase/discussions/27406

<div type='discussions-op-text'>

<sup>Originally posted by **intercepted16** June 20, 2024</sup>
On my current email confirmation page **for updating the emails**, users are prompted with a "please verify the other email" message, which can be vague and confusing. Additionally, attempting to determine which email (old or new) was verified based on URL parameters is not feasible, as changing the email address results in the user being logged out, making it difficult to access [`session.user.new_email`] for clarity.

**Proposed Solution**: 
Implement a feature or provide a utility that simplifies the process of identifying which email address (old or new) has been verified. This could involve:
- Enhancing the session management to retain the verification state even after the email change, preventing automatic logout.
- Providing a clear on the email confirmation page that specifies which email address has been verified, based on the verification process outcome.</div>

**Comment by encima** [comment]
Closing this as it is a discussion already. Please only open one or the other as it makes it harder to track answers and can duplicate work efforts
