### ISSUE TITLE
Confirmation Link Missing Port 8000

### ISSUE THREAD

**Issue by SpatialSymmetry** [supabase/supabase#27424]
Hi. When supabase sends the confirmation email, the link looks something like `http://<host>/auth/v1/verify?token=test&type=signup` which doesn't work. But when I manually add the port as `http://<host>:8000/auth/v1/verify?token=test&type=signup` confirmation goes ok. Is there any problems with my config? How can I solve this?

This has to do with how emails are generated by supabase and since users don't have control over that this may be a bug.

**Comment by j4w8n** [comment]
Have you set your site url in the supabase dashboard?

**Comment by SpatialSymmetry** [comment]
@j4w8n I should've mentioned that I'm running self-host supabase with docker. My configuration at `docker/.env` includes all necessary urls with ports. Everything else works, this seems simply an issue about how confirmation links are generated by supabase.

It's probably a misconfiguration from my part, but since I didn't find any documentation about link generations I had to open an issue.

**Comment by j4w8n** [comment]
@SpatialSymmetry, have you seen this old issue? There is also a link to an older issue on it that mentions another env var for docker.

https://github.com/supabase/supabase/issues/21030

**Comment by tranhoangvuit** [comment]
Hi @SpatialSymmetry, has @j4w8n's comment solved your issue? If not, can you let us know?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
