### ISSUE TITLE
Minor error in documentation for Prisma

### ISSUE THREAD

**Issue by luisjunco** [supabase/supabase#27438]
# Improve documentation

## Link 

https://supabase.com/partners//prisma

## Describe the problem

Session connection pooler string needs to include `?pgbouncer=true&connection_limit=1` after the database name.

**CURRENT VERSION:**

```
> To get the Session connection pooler string, change the port to 5432. If your database is Postgres 14 and above, it will look like this

postgres://[db-user].[project-ref]:[db-password]@aws-0-[aws-region].pooler.supabase.com:5432/[db-name]
```

**SHOULD BE:**

```
> To get the Session connection pooler string, change the port to 5432. If your database is Postgres 14 and above, it will look like this

postgres://[db-user].[project-ref]:[db-password]@aws-0-[aws-region].pooler.supabase.com:5432/[db-name]?pgbouncer=true&connection_limit=1
```

**Comment by kmr-ankitt** [comment]
I am working on this

**Comment by kmr-ankitt** [comment]
#27445 PR raised

**Comment by encima** [comment]
Hey hey,

Thanks for opening. The docs might not be so clear but those arguments are for `transaction` mode and not `session`. Session is more for direct database connections and does not need these parameters (see Prisma docs [here](https://www.prisma.io/docs/orm/overview/databases/supabase))
