### ISSUE TITLE
Email 

### ISSUE THREAD

**Issue by emiliawojnarowicz** [supabase/supabase#27444]
I am trying to change the type of emails that users receive, the preview shows the correct form of the letter, but in fact the user receives a broken letter, what could be the problem with this bug?

**Comment by encima** [comment]
Hey @emiliawojnarowicz , thanks for reporting!

Please reformat this issue using the New Issue template and providing as much information as possible, such as:
- what events for the emails
- what your template looks like
- what the users receive
- any errors or relevant logs
Thanks!
