### ISSUE TITLE
Restoration of archived projects takes more  than 12 hours

### ISSUE THREAD

**Issue by aevi82** [supabase/supabase#27441]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My Project LangueGO was archived and now I'm trying to restore it, however it takes more than 12 hours (ticket #2866265896). Would you please help me to restore the project?

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Hi there @aevi82 ,

I see the project is now available to you and the support ticket is closed. We will close this now.
