### ISSUE TITLE
getPublicUrl returns a different URL than the one in the dashboard and it returns a 403 error

### ISSUE THREAD

**Issue by s-kennedy** [supabase/supabase#2745]
# Bug report

## Describe the bug

I'm using supabase-js with Next and I want to upload an image to a public bucket and then display it on a website. Uploading the image works as expected. When I call `getPublicUrl`, the URL returned gives me a 403 error and I noticed that it's not the same as the URL I get from the dashboard. If I go to the bucket on my dashboard and click "Copy URL" on the object, I get a URL that works and displays the image. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

This is my function for getting the public URL, it's straight out of the supabase docs:

```
export const getPublicImageUrl = async (path, bucket="images") => {
  try {
    const { publicURL, error } = supabase
      .storage
      .from(bucket)
      .getPublicUrl(path)

    if (error) {
      throw error
    }

    return publicURL
  } catch (error) {
    return { error: error.message }
  }
}
```

This returns `https://instance-id.supabase.co/storage/v1/object/public/files/images/SM-2---Version-B.png` and opening that url returns a 403. 

Meanwhile if I go to https://app.supabase.io/project/instance-id/storage/buckets/images and click on the image then click on "Copy URL", the copied URL is `https://instance-id.supabase.in/storage/v1/object/public/images/SM-2---Version-B.png` and it works as expected. 

## Expected behavior

The public URL from the API should be the same as the public URL from the UI and they should both work. 

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of supabase-js: 1.21.0
- Version of Node.js: 12.16.1

**Comment by s-kennedy** [comment]
It was my mistake, turns out the bucket name is included in the path returned from `upload`, so I had to strip that out to get the right url from `getPublicUrl`. Found the answer in this thread: https://github.com/supabase/supabase/discussions/1146#discussioncomment-640379

**Comment by eunjae-lee** [comment]
Wow, thank you!
It took a lot for me to figure it out until seeing this issue.
It's totally weird that `Key` in the response includes the bucket name.
