### ISSUE TITLE
BUG FOUND in TYPES GENERATED BY SUPABASE: " Type instantiation is excessively deep and possibly infinite. "

### ISSUE THREAD

**Issue by eybel** [supabase/supabase#27450]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

So after implementing the TablesInsert<"table"> to my useForm() hook I was getting this error : **Type instantiation is excessively deep and possibly infinite.**  after lot of investigating I fount out that this is the problem:

the JSON its defined with its own JSON definition. This creates a loop, thus the error.
database.types.ts

```
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

I REPLACED IT WITH THIS MEANWHILE AND IT WORKS:

export type Json = Record<string, any>

```

Could you check this out?

**Comment by encima** [comment]
There is an issue open for this [here](https://github.com/supabase/supabase-js/issues/808), I will close this so we can track it in one place. 

Please take a look at the recommendations and add your thoughts also!

**Comment by eybel** [comment]
> There is an issue open for this [here](https://github.com/supabase/supabase-js/issues/808), I will close this so we can track it in one place.
> 
> Please take a look at the recommendations and add your thoughts also!

Ok perfect!
