### ISSUE TITLE
using cli commands with docker-compose setup?

### ISSUE THREAD

**Issue by terion-name** [supabase/supabase#27496]
# Improve documentation

## Link 
https://supabase.com/docs/guides/self-hosting/docker

## Describe the problem
Documentation describes how to launch supabase with self-managed docker-compose. But there is no information how to use cli tools with this setup, for example db diff `supabase db diff --use-migra initial_schema -f initial_schema`

## Describe the improvement
Please add a block about running commands such as `supabase db diff --use-migra initial_schema -f initial_schema` with compose setup

**Comment by encima** [comment]
Hi @terion-name 
Thanks for opening, this is described in the documentation for the [CLI](https://supabase.com/docs/reference/cli/supabase-db-diff) (you need to provide the `--db-url` to your self-hosted Supabase DB)

Let me know if that doesnt answer it for you and I will reopen / we can think about how to add it to the docs for self-hosting
