### ISSUE TITLE
public alpha signup is broken

### ISSUE THREAD

**Issue by cmmartin** [supabase/supabase#275]
`invalid_request (connection not found for the client)`

**Comment by kiwicopple** [comment]
Hey @cmmartin can you please help me to replicate this? What did you do to get this error? It may be related to a Cloudflare outage that happened when we were spinning up new instances, but we aren't certain. If you let us know your project reference (in the URL) that would be helpful too

**Comment by kiwicopple** [comment]
OK we found how to replicate. Looks like there was a bug with the `Sign up` button but not the `Getting started` button, so we couldn't find it. I've pushed a patch.

Thanks for letting us know @cmmartin
