### ISSUE TITLE
Table editor attempts to `count(*)` every row in the table

### ISSUE THREAD

**Issue by m-thomson** [supabase/supabase#27543]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
FWIW I'm using a Supabase paid plan.

I'm unable to browse a large  table (>100M rows) in the table editor due to timeout.  Supabase appears to be trying to `count(*)` all records when I'm just trying to view the first 100 or whatever. 

I understand that running the count query is helpful for pagination reasons but it makes it impossible to browse a large table with Supabase. I just want to see the first page of data (i.e. to see if an import or update looks correct).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1) Use the 'table editor' to browse a large table.
2) Observe that the table editor displays the message "Loading Records Count" at the bottom.
3) Notice that it takes a long while for the data to appear, or (as in my case) it just never loads at all.

## Expected behavior

I appreciate that for most tables, having the total number of records is helpful because (a) it's good to know and (b) makes the pagination more exact. But for large tables, this feature should be automatically disabled or there should be an option to turn it off. I'm happy with the UI displaying simply "Page 1 of (Unknown)" and not having the total number of records shown at all. At least then I can browse the data.

I should add - I realize that increasing the instance size will help but even on my own self-hosted PG instance with 64GB ram, it still takes 30-40 seconds to count all the records which makes browsing unusable.

## Screenshots

![Screencap2024 06 24 1611](https://github.com/supabase/supabase/assets/5273016/356be520-4c31-481d-9463-8040493fa1b6)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Tangentially related: https://github.com/supabase/supabase/issues/623

**Comment by khera** [comment]
A trick I've used many times is to use the estimate of number of rows. When the row count is big enough, this is a good enough answer.

https://wiki.postgresql.org/wiki/Count_estimate

I'll also note that a table that large starts to become inefficient in Postgres. I usually start partitioning my tables when they get near 15-20M records.

**Comment by m-thomson** [comment]
Support are looking into how best to handle this in the SB interface but I wanted to say thanks @khera for providing that link and explanation for how I can work around this in my own code. Very helpful!

**Comment by saltcod** [comment]
fixed by https://github.com/supabase/supabase/pull/27612
