### ISSUE TITLE
Supabase redirect links break Flutter apps using GoRouter

### ISSUE THREAD

**Issue by Mr-Pepe** [supabase/supabase#27554]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Deep links for Flutter apps with GoRouter look like `https://app.com/#/path?param`. It seems that Supabase does not handle the hashtag correctly when creating redirect links. 

A redirect link like `http://localhost:8000/#/settings?enableUserSignIn` turns into `http://localhost:8000/?code=abcdef2b-908a-4f09-be87-547030d3346d#/settings?enableUserSignIn`.

## To Reproduce

Use a redirect link like described above.

## Expected behavior

I'd expect the redirect link to become `localhost:8000/#/settings?enableUserSignIn&code=abcdef2b-908a-4f09-be87-547030d3346d`. The `code` parameter should not be inserted in front of the hashtag.

## System information

- OS: Arch Linux
- Browser: Firefox 127.0.1 (64-bit)

**Comment by Mr-Pepe** [comment]
It suddenly seems to work for some reason and GoRouter successfully parses the URL. I don't know why it didn't work when I created this issue, but it still makes me feel a bit uneasy about how Supabase modifies the URL. Just wanted to give more feedback.

**Comment by encima** [comment]
Note that this is not `go_router`, but Flutter behaviour and can be modified with a different URL strategy. See [here](https://docs.flutter.dev/ui/navigation/url-strategies)

Will close this now unless I am misunderstanding the state?

**Comment by Mr-Pepe** [comment]
Yes, you are right :+1: 

Nonetheless, the way Supabase modifies redirect URLs seems very wonky to me and I'd expect it to work with Flutter's default settings (using a hashtag in the path) out of the box. I hope that's going to get resolved via https://github.com/supabase/supabase/issues/27638.
