### ISSUE TITLE
isuue in login with auth provider 

### ISSUE THREAD

**Issue by nisarg2023** [supabase/supabase#27563]
when I try to log in with apple id is not work with other auth providers is work fine 
in login with Apple ID get an error like this 

`[
  {
    "message": null,
    "timestamp": null,
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "error",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "500: Unable to exchange external code: c2d77852fe3b84ed1b387c59aed6d9fb4.0.rtxy.LIEYlnQEZHxc8cmaHYtSwQ",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-aflvyuposwetugplejup",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": "899dec7bf71c402b-BOM",
    "CODE_LINE": null,
    "path": "/callback",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [],
    "args": [],
    "referer": "https://app.dyshez.com",
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": "103.215.158.90",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_client\"}"
  }
]`

in supabase auth table, the user is not created but is redirecting me to the provided callback URL

so this issue from supabase side or the apple account? I check all configuration is proper in Apple account

**Comment by someshfengde** [comment]
<img width="647" alt="image" src="https://github.com/supabase/supabase/assets/42097653/b7d33ce3-c6bb-412e-a14a-72a6017355f2">


facing the same issue for signing up user with any method ( tried with google, simple sign up )

**Comment by encima** [comment]
Hey @nisarg2023 ,

Are you using custom domains with your Supabase project? Did you provide Apple with a new key as it can take some time for them to accept it (~48 hrs)

---

@someshfengde I think you are facing a separate issue. Please open a separate issue or a support ticket.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
