### ISSUE TITLE
glitching ui animation on app.supabase.io website

### ISSUE THREAD

**Issue by norflin321** [supabase/supabase#2758]
# Bug report

## Describe the bug

Broken ui animation on app.supabase.io website

## To Reproduce

1. Go to https://app.supabase.io, log in if not
2. Open your project (https://app.supabase.io/project/ + your-project-id)
3. Click on "Table editor" in left menu
4. Click on "Insert row" green button
5. See error
6. Click on "View data" button
7. See similar error

## Expected behavior

Smooth animation
No blue line at the middle of screen

## Screenshots
<details>
  <summary>Video</summary>

  https://user-images.githubusercontent.com/33498670/128595893-a8c63fde-ebd4-45b8-a1bb-526040dad2e0.mov
</details>

## System information

- OS: macOS Big Sur 11.5.1, arm cpu
- Browser: safari 14.1.2

**Comment by kiwicopple** [comment]
wow that's odd - thanks for the awesome bug report @norflin321. The video + browser info is very helpful

**Comment by kiwicopple** [comment]
checked on the latest version of Studio and looks like this is fixed 🎉
