### ISSUE TITLE
Duplicated Project Labels

### ISSUE THREAD

**Issue by Kinfe123** [supabase/supabase#27585]
# Bug report

Idk this is done intentionally like having a unique ID for each project with the same org but i found that i can create a multiple same label also the same origin like eu-central to my project with the same org.

![image](https://github.com/supabase/supabase/assets/65047246/aac148c6-9987-4054-be43-469617c4fdf1)

**Comment by encima** [comment]
Hi there,
This is not an issue as the reference for your project will be unique. Thanks for checking, though!
