### ISSUE TITLE
NextJS User Management no longer builds

### ISSUE THREAD

**Issue by Gizmotronn** [supabase/supabase#27596]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When cloning the `supabase/supabase` repository and then navigating through to `examples/user-management/nextjs-user-management`, I get the following build error:

Type error: No overload matches this call.
  Overload 1 of 2, '(column: "id", value: string): PostgrestFilterBuilder<{ Tables: { profiles: { Row: { id: string; updated_at: string | null; username: string | null; full_name: string | null; avatar_url: string | null; website: string | null; }; Insert: { ...; }; Update: { ...; }; }; }; Views: {}; Functions: {}; Enums: {}; }, { ...; }, { ...; }[], "profiles", unknown>', gave the following error.
    Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 2, '(column: string, value: string): PostgrestFilterBuilder<{ Tables: { profiles: { Row: { id: string; updated_at: string | null; username: string | null; full_name: string | null; avatar_url: string | null; website: string | null; }; Insert: { ...; }; Update: { ...; }; }; }; Views: {}; Functions: {}; Enums: {}; }, { ...; }, { ...; }[], "profiles", unknown>', gave the following error.
    Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.

  21 |         .from('profiles')
  22 |         .select(`full_name, username, website, avatar_url`)
> 23 |         .eq('id', user?.id)
     |                   ^
  24 |         .single()
  25 | 
  26 |       if (error && status !== 406) {
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I found this issue when I was in my own project after migrating to the app router and tried to use supabase to grab user data in the same method as described in the documentation, the `account-form.tsx` file being the culprit again.

## Expected behavior

Expected behaviour would be that the build command runs correctly, and after running it I can interact with the user data.

## Screenshots

<img width="1089" alt="image" src="https://github.com/supabase/supabase/assets/31812229/964d22ff-6e9b-41ef-9f9c-ae0bdfd94dec">

## System information

- OS: macOS
- Browser: Arc (Chromium)
- Version of supabase-js:     
    "@supabase/auth-helpers-nextjs": "^0.7.1",
    "@supabase/supabase-js": "^2.26.0",
    "@supabase/auth-ui-react": "^0.4.2",
    "@supabase/auth-ui-shared": "^0.1.6",
- Version of Node.js: 20.14.0

**Comment by charislam** [comment]
We've made some updates to this. Just tested and successfully ran it on my local machine, if the problem persists for anyone else, feel free to reopen!

**Comment by Gizmotronn** [comment]
Thanks @charislam , appears good now!
