### ISSUE TITLE
Status 500 "Database error saving new user"

### ISSUE THREAD

**Issue by carlomigueldy** [supabase/supabase#2761]
# Bug report

## Describe the bug

I was building a trigger on auth.users and stored procedure to handle new users and save a new record to public.users

Then I am receiving a 500 status code with message that says "Database error saving new user"

## To Reproduce

Not sure about the instructions on how to let you reproduce the error. I guess you'll have to work with the database I am building with the triggers. Then attempt to create a new user from Supabase Auth `signUp` for email and password.

## Expected behavior

It should listen to the trigger event and insert a new record in public.users after a new record is created for auth.users

## Screenshots

![image](https://user-images.githubusercontent.com/45052332/128600065-653d129a-f2d5-4550-84ae-dd6e424c1ab5.png)

## System information

- OS: Windows 10 on WSL2
- Browser: Chrome
- Version of supabase-js: ^1.21.0
- Version of Node.js: v14.17.1

## Additional context

You can create a new Supabase project and use this in SQL Editor

```sql
CREATE TABLE public.users (
  id uuid PRIMARY KEY NOT NULL REFERENCES auth.users (id),
  first_name VARCHAR CHECK (first_name <> ''),
  last_name VARCHAR CHECK (last_name <> ''),
  email VARCHAR UNIQUE NOT NULL CHECK (email <> ''),
  username VARCHAR UNIQUE CHECK (username <> ''),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  deleted_at TIMESTAMP
);

-- Trigger to handle new registered user
DROP TRIGGER IF EXISTS on_auth_user_created_create_public_user_record ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN 
  INSERT INTO public.users (id, email) VALUES (new.id, new.email);

  return new;
END
$$;

CREATE TRIGGER on_auth_user_created_create_public_user_record
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE handle_new_user();
```

**Comment by carlomigueldy** [comment]
Got it resolved. Also there was a similar issue to this.

Closing it now.

**Comment by goudarziha** [comment]
@carlomigueldy I am running into this exact issue now. How did you resolve this issue?

**Comment by carlomigueldy** [comment]
@goudarziha 

I think I changed the data type for `email` field to TEXT from VARCHAR and made it nullable.

That's what I can remember at least.

**Comment by goudarziha** [comment]
Thank you for the super quick reply, unfortunately it's still not working for me :(

**Comment by lfcj** [comment]
Did someone solve it? Seeing it, although I do not have a users table, that is automatic in Supabase now. I am getting
```
{"component":"api","error":"500: Database error saving new user","level":"info","method":"POST","msg":"server_error: Internal Server Error","path":"/token","referer":"http://localhost:3000","remote_addr":"176.80.51.156","request_id":"8d31f90e366f384d-MAD","time":"2024-10-15T18:46:37Z"}

metadata:

[
  {
    "message": null,
    "timestamp": null,
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "info",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "server_error: Internal Server Error",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-teacjgdvmmzkalqkifky",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": "8d31f90e366f384d-MAD",
    "CODE_LINE": null,
    "path": "/token",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [],
    "args": [],
    "panic": null,
    "referer": "http://localhost:3000",
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "stack": null,
    "remote_addr": "176.80.51.156",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": "500: Database error saving new user"
  }
]
```

**Comment by SiddheshaB** [comment]
> Did someone solve it? Seeing it, although I do not have a users table, that is automatic in Supabase now. I am getting
> 
> ```
> {"component":"api","error":"500: Database error saving new user","level":"info","method":"POST","msg":"server_error: Internal Server Error","path":"/token","referer":"http://localhost:3000","remote_addr":"176.80.51.156","request_id":"8d31f90e366f384d-MAD","time":"2024-10-15T18:46:37Z"}
> 
> metadata:
> 
> [
>   {
>     "message": null,
>     "timestamp": null,
>     "__MONOTONIC_TIMESTAMP": null,
>     "CODE_FUNC": null,
>     "instance_id": null,
>     "status": null,
>     "_CMDLINE": null,
>     "method": "POST",
>     "_SYSTEMD_CGROUP": null,
>     "CODE_FILE": null,
>     "EXECUTABLE": null,
>     "_EXE": null,
>     "UNIT": null,
>     "level": "info",
>     "_COMM": null,
>     "duration": null,
>     "issuer": null,
>     "_LINE_BREAK": null,
>     "_SOURCE_REALTIME_TIMESTAMP": null,
>     "msg": "server_error: Internal Server Error",
>     "action": null,
>     "login_method": null,
>     "_UID": null,
>     "host": "db-teacjgdvmmzkalqkifky",
>     "PRIORITY": null,
>     "_CAP_EFFECTIVE": null,
>     "_PID": null,
>     "INVOCATION_ID": null,
>     "_SYSTEMD_UNIT": null,
>     "source_type": null,
>     "SYSLOG_FACILITY": null,
>     "request_id": "8d31f90e366f384d-MAD",
>     "CODE_LINE": null,
>     "path": "/token",
>     "component": "api",
>     "project": null,
>     "user_id": null,
>     "auth_event": [],
>     "args": [],
>     "panic": null,
>     "referer": "http://localhost:3000",
>     "factor_id": null,
>     "provider": null,
>     "client_id": null,
>     "stack": null,
>     "remote_addr": "176.80.51.156",
>     "_SYSTEMD_SLICE": null,
>     "_SYSTEMD_INVOCATION_ID": null,
>     "header": null,
>     "_MACHINE_ID": null,
>     "_AUDIT_LOGINUID": null,
>     "_TRANSPORT": null,
>     "_SELINUX_CONTEXT": null,
>     "MESSAGE_ID": null,
>     "__REALTIME_TIMESTAMP": null,
>     "metadata": [],
>     "_STREAM_ID": null,
>     "metering": null,
>     "time": null,
>     "_GID": null,
>     "_BOOT_ID": null,
>     "SYSLOG_IDENTIFIER": null,
>     "_AUDIT_SESSION": null,
>     "error": "500: Database error saving new user"
>   }
> ]
> ```
