### ISSUE TITLE
Following docs for server side auth for sveltekit produces unintended behaviour on page navigation using direct url

### ISSUE THREAD

**Issue by tarekfb** [supabase/supabase#27617]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When implementing the following:

`onMount(() => {
    const { data } = supabase.auth.onAuthStateChange((_, newSession) => {
      if (!newSession) {
        /**
         * Queue this as a task so the navigation won't prevent the
         * triggering function from completing
         */
        // setTimeout(() => {
        //   goto("/", { invalidateAll: true });
        // });
        setTimeout(() => {
          invalidateAll();
        });
      }
      if (newSession?.expires_at !== session?.expires_at) {
        invalidate("supabase:auth");
      }
    });

    return () => data.subscription.unsubscribe();
  });`

From the [supabase docs for server side auth for sveltekit produces unintended behaviour](https://supabase.com/docs/guides/auth/server-side/sveltekit).

There is an issue with navigation. On page navigation using direct url instead of button or anchor, user gets redirected to /, if the new session is falsy. Replacing the setTimeout with this:

`setTimeout(() => {
          invalidateAll();
        });`

resolves the issue and seems to not produce any other issues.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Implement step 6, Listen to Auth events, from [supabase docs for server side auth for sveltekit produces unintended behaviour](https://supabase.com/docs/guides/auth/server-side/sveltekit).
2. Navigate using direct url instead of button or anchor

## Expected behavior

No redirect.

## Screenshots

Not applicable.

## System information

- Chrome
- "supabase": "^1.163.6",
- "@supabase/auth-ui-svelte": "^0.2.2",
- "@supabase/ssr": "^0.3.0",
-  "@supabase/supabase-js": "^2.33.0",

## Additional context

No additional context.

**Comment by j4w8n** [comment]
What's the error?

**Comment by j4w8n** [comment]
I've never actually followed that new guide, but after doing so I assume you're talking about the fact that when you go to /auth, to try and signup or login, it redirects you back to /. This is definitely an issue with the guide.

**Comment by silentworks** [comment]
I've opened a PR to fix these guide https://github.com/supabase/supabase/pull/27641

**Comment by j4w8n** [comment]
> I've opened a PR to fix these guide #27641

Thanks!! This was greatly needed.
