### ISSUE TITLE
Interval data type changes to seconds upon row update

### ISSUE THREAD

**Issue by rookledookle** [supabase/supabase#27626]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Weird one - I have a table with a column that has an interval data type. When a row in this table updates, weirdly, the interval column changes from {"hours":8} to {"seconds":8}. I have disabled all triggers associated to this table `chart_configured_astro_data` and `chart_configured` (as you will see in the schema below) that could be updating the db (although in the code there isn't such a case). This started happening potentially yesterday, but definitely today I have been able to replicate it multiple times on both prod and staging dbs. 

I recently updated the database to postgres version 15.1.1.69, it wasn't happening before the upgrade but I don't know if this has any cause and effect. 

This is the schema:

```
create table
  public.charts (
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null,
    user_id uuid not null,
    id uuid not null default gen_random_uuid (),
    datetime timestamp with time zone null,
    location_name text null,
    lat double precision null,
    long double precision null,
    google_place_id text null,
    sun text null,
    moon text null,
    rising text null,
    objects_data jsonb null,
    houses_data jsonb null,
    timezone_offset interval null,
    chart_image text null,
    activated_at timestamp with time zone null,
    house_system text null,
    configured_at timestamp with time zone null,
    country_short_name text null,
    raw_data jsonb null,
    constraint charts_pkey primary key (id),
    constraint charts_id_key unique (id),
    constraint charts_house_system_fkey foreign key (house_system) references house_systems (name),
    constraint charts_user_id_fkey foreign key (user_id) references users (id) on delete cascade,
    constraint public_charts_sun_fkey foreign key (sun) references signs (name),
    constraint public_charts_moon_fkey foreign key (moon) references signs (name),
    constraint public_charts_rising_fkey foreign key (rising) references signs (name),
    constraint chk_datetime_timezone_offset check (
      (
        (datetime is null)
        or (timezone_offset is not null)
      )
    )
  ) tablespace pg_default;

create trigger chart_configured
after
update on charts for each row
execute function get_user_chart_image ();

create trigger chart_configured_astro_data
after
update on charts for each row
execute function get_chart_astro_data ();

create trigger handle_updated_at before
update on charts for each row
execute function extensions.moddatetime ('updated_at');
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. On the dashboard, go to charts table
2. Update the datetime column by one seconds
3. Row updates, but also changes the timezone_offset interval type column from hours to seconds

## Expected behavior
timezone_offset column does not change 

## System information

- OS: macOS
- Browser (if applies) Chrome
- Version of supabase-js: ^2.42.4
- Version of Node.js: v22.3.0

**Comment by kaelruland** [comment]
I believe this is the [same issue](https://github.com/supabase/supabase/issues/22388) I had.

**Comment by kaelruland** [comment]
No, unfortunately. But in the meantime entering intervals like `3 days` or `1 year 3 minutes` still works.

**Comment by encima** [comment]
Looks like this is a frontend issue and is being worked on
