### ISSUE TITLE
I am not receiving password reset emails for Supabase dashboard

### ISSUE THREAD

**Issue by bensinclair1** [supabase/supabase#27625]
I have tried resetting my password on my Microsoft email account and my gmail account, and on both i do not receive the password reset emails. Is there any alternative to reset my password?

**Comment by Hallidayo** [comment]
Hi @bensinclair1 - Thank you for opening the issue, Have you had a check of the auth logs (Logs > Auth) in the Supabase studio?

**Comment by encima** [comment]
I think we can close this as it is is likely related to your account. Please do open a [support ticket](https://supabase.help) if the issue is not resolved, though!

**Comment by raahimkhan** [comment]
I am having same issue.
