### ISSUE TITLE
"Connecting to your database" hyperlink broken.

### ISSUE THREAD

**Issue by AJR07** [supabase/supabase#27634]
# Improve documentation

## Describe the problem

Going to the [Supabase database documentation](https://supabase.com/docs/guides/database/overview), I clicked on the "Connecting to your database" hyperlink on the navbar. It redirects to [https://supabase.com/docs/docs/guides/database/connecting-to-postgres](https://supabase.com/docs/docs/guides/database/connecting-to-postgres), which returns a 404 Not Found.

## Describe the improvement

After a bit of googling, I think [https://supabase.com/docs/guides/database/connecting-to-postgres](https://supabase.com/docs/guides/database/connecting-to-postgres) is the correct hyperlink.

**Comment by nusr** [comment]
The problem is resolved.

**Comment by AJR07** [comment]
Alright, thanks!
