### ISSUE TITLE
Setting a new Site URL does not change magic link URL

### ISSUE THREAD

**Issue by sandypockets** [supabase/supabase#2768]
# Bug report

## Describe the bug

Setting a new `Site URL` in **Auth > Settings > General** does not change the URL sent in magic link for sign up or sign in. 

When I first set up Supabase, the `Site URL` was `http://localhost:3000`. I have changed it to `http://localhost:3000/app/`, but all the magic links still redirect to `http://localhost:3000/`. 

After adjusting the`Site URL`, the magic link URL I'm receiving by email is: 

`https://<URL>.supabase.co/auth/v1/verify?token=<TOKEN>&type=magiclink&redirect_to=http://localhost:3000/`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/[your-project-id]/auth/settings`
2. In the **General** section, navigate to `Site URL`
3. Modify the path of the `Site URL`, and save.
4. Send a new magic link (by signing up with a new email, or signing in).
5. Click the magic link in the email, note the redirect is still to the original URL, and not the new one. 

## Expected behavior

After saving the new `Site URL` with `http://localhost:3000/app/` I expected that when users log in or sign up via a magic link, they will be redirected to `http://localhost:3000/app/`. I would expect the magic link I receive by email to look like this: 

`https://<URL>.supabase.co/auth/v1/verify?token=<TOKEN>&type=magiclink&redirect_to=http://localhost:3000/app/`

## Screenshots

![https://i.imgur.com/UDGv9C2.png](https://i.imgur.com/UDGv9C2.png)

## System information

- OS: macOS
- Browser: Chrome
- Email clients: Gmail/G-Suite, iCloud
- Version of supabase-js: "^1.21.0"
- Version of Node.js: "14.17.0"

## Additional context

Seems a bit similar (in a way, opposite) to #2235. Could be unrelated, but worth linking.

**Comment by farzd** [comment]
i think i had a similar issue, see comments in this issues 
https://github.com/supabase/gotrue/issues/117

**Comment by sandypockets** [comment]
This issue is no longer occurring for me, closing the issue.
