### ISSUE TITLE
Function Editor cannot delete functions with parameters having DEFAULT value

### ISSUE THREAD

**Issue by LeDragunov** [supabase/supabase#2777]
# Bug report

## Describe the bug

the Function Editor (https://app.supabase.io/project/project_id/database/functions) cannot delete functions with parameters having DEFAULT value in the arguments (Even if one out of all params is DEFAULT, you receive same error)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a function with a parameter having a default value

example:
`create or replace function example_f (LOC_LAT int DEFAULT 123) 
	returns int
	language plpgsql
as $$
begin
select LOC_LAT;
end;$$`

2. Go to Database-->Functions
3. Try to delete the newly created function 'example_f'
4. See error `Deleting example_f failed: syntax error at or near "DEFAULT"`

## Expected behavior

To delete the function

**Comment by w3b6x9** [comment]
@LeDragunov thanks for reporting this issue! we'll be tackling this very soon.

**Comment by w3b6x9** [comment]
@LeDragunov this has been fixed!
