### ISSUE TITLE
error when adding new users after database restore using psql 

### ISSUE THREAD

**Issue by boyhax** [supabase/supabase#27782]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
im using managed supabase and selfhosted one all of them got the same error after i restore the database using dbeaver software and backup i made from selfhosted version.

note* the backup file format is .tar and that what only worked for me to backup public and auth schemas

the problem cause all auth functions  to not work properly even from js client app.

the error toast in studio 
"Failed to create user: upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111"

## To Reproduce

1-backup the database using dbeaver (only public and auth schemas)
2-use .tar format in options
3-restore the backup to any other supabase database
4-check auth functions (try to add user or send invite)

## Expected behavior

 auth functions to work again

**Comment by encima** [comment]
If you have not opened a Support ticket, it might be best to do that. Note that functions, user permissions etc would also need to be applied so just restoring those 2 schemas may not be enough (especially if the projects are running 2 different versions)

We would recommend using the [CLI](https://supabase.com/docs/reference/cli/supabase-db-dump) for this.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
