### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by WilliamFernsCodes** [supabase/supabase#27791]
# Improve documentation
![image](https://github.com/supabase/supabase/assets/172117888/4d95a6d8-57ab-4e34-ba1a-c77a977093a8)

## Link 
https://supabase.com/docs/guides/ai/python/indexes
Add a link to the page which needs improvement (if relevant)

## Describe the problem
It should be searching.

**Comment by kmr-ankitt** [comment]
I am fixing this

**Comment by Sudiptobhukta** [comment]
I am willing to do this work can I contribute?

**Comment by charislam** [comment]
Of course @Sudiptobhukta! Feel free to open a PR. Looks like those are the Python AI library docs, so the text might be in our `vecs` repo: https://github.com/supabase/vecs

**Comment by kmr-ankitt** [comment]
> I am willing to do this work can I contribute?
> 

already fixed brother

**Comment by charislam** [comment]
Ahh I forgot about that, thanks @kmr-ankitt!
