### ISSUE TITLE
Can't login with github account

### ISSUE THREAD

**Issue by Jaimitolol** [supabase/supabase#27817]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After login with github I get this url: https://supabase.com/dashboard/sign-in-mfa?error=server_error&error_description=sql%3A+Scan+error+on+column+index+14%2C+name+%22encrypted_password%22%3A+converting+NULL+to+string+is+unsupported#error=server_error&error_description=sql%253A+Scan+error+on+column+index+14%252C+name+%2522encrypted_password%2522%253A+converting+NULL+to+string+is+unsupported

## To Reproduce

1. Select login with github
2. Choose your github account
3. Wait to be redirected to error url

## Screenshots

This is the page I get redirected to:
![image](https://github.com/supabase/supabase/assets/174690445/35b3cd32-3a12-4786-b553-94e73672dcfc)

## System information

- OS: Ubuntu 22.04
- Browser: Firefox and Chromium

**Comment by saltcod** [comment]
Hey @Jaimitolol! 

Several of us just tried logging out and in with a few different browsers and things look ok. If this isn't already resolved for you, please send an email to [support@supabase.io](mailto:support@supabase.io) and we'll have a look!
