### ISSUE TITLE
NextJS: Password Reset - Auth session missing

### ISSUE THREAD

**Issue by alexnechifor** [supabase/supabase#27816]
# Bug report

## Describe the bug

The password reset flow does not work with NextJS 14 and Vercel. Locally, it works smoothly, but when deployed, I keep getting an "Auth Session Missing" error. I'm using the app directory. Both components are client components. In the URL, I see a code param. It used to work with this flow, rarely throwing this error, but now it always sends this error. Is there any workaround for this?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Invoke reset password for email, with redirectTo
2. Click the link
3. Update the password
4. Submit, then see error

## Expected behavior

To reset user's password.

## System information

- OS: [ Windows]
- Version of supabase-js: [e.g. 2.44.2]
- Version of Node.js: [e.g. 20.11.1]

## Additional context

I will attach code snippets.

This is for forgot password:

```ts
import { Database } from "@/supabase/types";
import { createBrowserClient } from "@supabase/ssr";

export const supabase = createBrowserClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
);

```

```ts
import { supabase } from "@/lib/supabase/client";

async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);

    const { error } = await supabase.auth.resetPasswordForEmail(values.email, {
      redirectTo: `${getURL()}login/password-update`,
    });
    if (error) {
      setIsLoading(false);
      return toast.error(error.message);
    }

    toast.success("Email sent successfully.");
    setIsLoading(false);
    setIsOpen(false);
  }
```

And this is for the actual reset:
```ts
  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);

    const { error } = await supabase.auth.updateUser({
      password: values.password,
    });
    
    if (error) {
      console.log(error);
      setIsLoading(false);
      return toast.error(error.message);
    }

    toast.success(
      "Password reset successfully! You will be redirected in 3 seconds..",
      {
        duration: 3000,
      },
    );
    setTimeout(() => {
      router.push("/");
    }, 3000);
    setIsLoading(false);
  }
```

**Comment by charislam** [comment]
Hey @alexnechifor! When the user is redirected to your `/login/password-update` page, does the PKCE code stick around in their URL? Usually what this means is that the page does not eagerly initiate the Supabase client, which means that it's not running to watch the URL and do the automatic exchange. (Often happens when switching to server-side rendering, which might explain why this worked for you before, if it used to be client-side rendered and the Supabase client was always initiated.)

You have two approaches:

1. Manually do the code exchange yourself.
2. Eagerly initialize Supabase on the password update page, so it will automatically handle the code exchange.

See the admonition here: https://supabase.com/docs/guides/auth/passwords?queryGroups=language&language=js&queryGroups=flow&flow=pkce#step-2-create-a-change-password-page

If you've already checked that and it still doesn't work, let us know!

**Comment by alexnechifor** [comment]
@charislam Thanks for your answer!

Sadly, I already tried that. I'm trying to see if the session has already been established, if not (and the code exist in params), exchange it for a session then set the session.

Even though code exist in params and the current session is null, I get this error:
`Uncaught (in promise) AuthApiError: invalid request: both auth code and code verifier should be non-empty`

This is the code snippet:
```ts
  useEffect(() => {
    const init = async () => {
      console.log(code);
      const { data } = await supabase.auth.getSession();
      console.log("SESSION DATA:", data.session);

      if (!data.session && code) {
        const { data: newSession, error: newSessionError } =
          await supabase.auth.exchangeCodeForSession(code);

        console.log("NEW SESSION DATA:", newSession.session);

        if (newSessionError) {
          console.log(newSessionError);
        }

        if (newSession.session) {
          await supabase.auth.setSession(newSession.session);
        }

        setIsLoading(false);
      }
    };

    init();
  }, [code]);
```

It is a client component.

**Comment by encima** [comment]
Thanks for the extra details. Does this occur locally and in production? Where is the client app hosted?

**Comment by alexnechifor** [comment]
Short update: tried to move the logic on server-side by using an API handler (basic logic), locally it works, on production it stops working. Same error: `eG [AuthApiError]: invalid request: both auth code and code verifier should be non-empty`

Code snippet:
```ts
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  const supabase = createClient();
  const { searchParams } = new URL(request.url);
  const code = searchParams.get("code");
  let error = searchParams.get("error_description");

  if (code && !error) {
    const { data: newSession, error: newSessionError } =
      await supabase.auth.exchangeCodeForSession(code);

    if (newSessionError) {
      error = "There was a problem. Please try again.";
    }

    if (newSession.session) {
      await supabase.auth.setSession({
        access_token: newSession.session.access_token,
        refresh_token: newSession.session.refresh_token,
      });
    }
  }

  if (error) {
    return redirect(`/login/password-update?error_description=${error}`);
  }

  redirect("/login/password-update");
}

```



> Thanks for the extra details. Does this occur locally and in production? Where is the client app hosted?

Only on production. The app is on Vercel.

**Comment by denisrudov** [comment]
for me the flow is a bit different 

I call the server action:

```typescript
const { error } = await auth.resetPasswordForEmail(email, options)
```
and I receive a mail with the link 

http://localhost:3000/recovery?token=pkce_a11ee98aa84e402722cb9ce9d0b0a86cb93baf93e35d05a4637b1fe6&type=recovery

and on the /recovery route I do next:

```typescript
const data = await supabase.auth.verifyOtp({
      type,
      token_hash: token,
    })

```
and data doesn't contain any error. it contains user 
but session doesn't exist anymore

those two packages work well
```
"@supabase/ssr": "^0.3.0",
 "@supabase/supabase-js": "^2.43.5",
```
and those two:
```
"@supabase/ssr": "^0.4.0",
"@supabase/supabase-js": "^2.44.2",
```
no. I had to rollback to the older ones :(

**Comment by alexnechifor** [comment]
@denisrudov so it looks like I'm not the only one facing this problem... I kept looking for a solution in the past days..

**Comment by charislam** [comment]
Hey @alexnechifor, I did some investigating and adapted some of your code to make a password recovery flow that worked for me on Vercel: https://github.com/charislam/supabase-test (not winning any awards for cleanliness here 😅 but works well enough as a demo)

Based on your code samples and error messages, I'd say the first places to look are:

1. Looks like you are using an old version of the `@supabase/ssr` API that had problems with some edge cases saving cookies. Try updating to the newest and adapting your `createClient` functions and middleware to the new API: https://supabase.com/docs/guides/auth/server-side/nextjs

2. Since your error message says that the code verifier is missing, I'd try keeping dev tools open when you are requesting the password reset and on the actual change password page (post-email link), to check if/when the code verifier cookie gets set/deleted. It should have the name `sb-[your-project-ref]-auth-token-code-verifier` or similar

**Comment by alexnechifor** [comment]
@charislam Thank you so much, it works!

Quick tip for anyone else facing this problem:

If you are trying it on a preview deployment, pay close attention to the actual URL. One of the problems was that the resetPasswordForEmail was called on a preview deployment from the branch URL. But the redirect was pointing to the deployment URL (the one that does not have the "git" keyword in it), so the cookie was stored on the branch URL and not the deployment URL. A bit confusing at first sight, but it makes total sense. The example provided by @charislam will redirect to the production URL. 

That's how you learn, by making mistakes ^_^ 

Thanks again for all the help! Appreciate it.

**Comment by RemyNtshaykolo** [comment]
I’ve spent a considerable amount of time troubleshooting this issue on React Native/Expo, and here’s the solution that finally worked for me. Basically this catch the supabase deeplink redirection and iniatiate a user session using the access token and refresh token included in the redirection url.
I found the solution here : https://blog.theodo.com/2023/03/supabase-reset-password-rn/

``` javascript
import * as Linking from "expo-linking";

Linking.addEventListener("url", async (event) => {
  const parseSupabaseUrl = (url: string) => {
    let parsedUrl = url;
    if (url.includes("#")) {
      parsedUrl = url.replace("#", "?");
    }
    return Linking.parse(parsedUrl);
  };
  const url = parseSupabaseUrl(event.url);

  console.log("parsed url", url);

  const { data: setSessionData, error: setSessionError } =
    await supabase.auth.setSession({
      access_token: url.queryParams.access_token,
      refresh_token: url.queryParams.refresh_token,
    });
  console.log("setSessionData", setSessionData);
  console.log("setSessionError", setSessionError);
});
```

**Comment by Flowsmooth** [comment]
Got it.


Sent from Yahoo Mail for iPhone


On Sunday, August 18, 2024, 8:22 AM, Rémy Ntshaykolo ***@***.***> wrote:




I’ve spent a considerable amount of time troubleshooting this issue on React Native/Expo, and here’s the solution that finally worked for me. Basically this catch the supabase deeplink redirection and iniatiate a user session using the access token and refresh token included in the redirection url.
I found the solution here : https://blog.theodo.com/2023/03/supabase-reset-password-rn/
import * as Linking from "expo-linking";

Linking.addEventListener("url", async (event) => {
  const parseSupabaseUrl = (url: string) => {
    let parsedUrl = url;
    if (url.includes("#")) {
      parsedUrl = url.replace("#", "?");
    }
    return Linking.parse(parsedUrl);
  };
  const url = parseSupabaseUrl(event.url);

  console.log("parsed url", url);

  const { data: setSessionData, error: setSessionError } =
    await supabase.auth.setSession({
      access_token: url.queryParams.access_token,
      refresh_token: url.queryParams.refresh_token,
    });
  console.log("setSessionData", setSessionData);
  console.log("setSessionError", setSessionError);
});
