### ISSUE TITLE
403 Forbidden updating a field containing a URL if entering localhost

### ISSUE THREAD

**Issue by castortech** [supabase/supabase#27830]
# Getting 403 when trying to update record field containing a URL (self hosted)

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

So I have a table with a field called base_url. Right now the field has a value like: 'http://xyz.chat,api.internal:3100' and I am trying to change it to: 'http://localhost:3100'

From the application I get a 403 preceded by a CORS error.

Then I go to the studio and try (as Postgres) to update from the table editor and I get a 403  with an html like message. 

So I decide to do it directly in the SQL editor, same 403 again.

Since I really needed to make the change, I created a function and got the 403 while creating the function (not running it).

Finally, I edited to function to:
```
update my_table
set base_url = 'http' || '://' || 'localhost' || ':3100'
where id = 'xxxxxx';
```

and that finally worked

BTW changing it back after to the previous value gave no error, neither changing the port number or any other field.

What is going on here?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @castortech - Thank you for opening the issue. I've tried the following but I do not seem to be getting any errors:

- Created a test table with a varchar column of `base_url`.
- Added a new row with the `base_url` set to `http://xyz.chat,api.internal:3100/` and saved.
- Updated the column `base_url` with a value of `http://localhost:3100/` and saved.

Have you got a video of what happens when you do the above in the studio?

**Comment by castortech** [comment]
Sorry it took so long. Here is the link to the [video](https://www.loom.com/share/5bcfec3af9674aab8a1783bad7610d0d?sid=117dc8f0-0c4c-401e-b1e2-3810be3c1c72)

**Comment by castortech** [comment]
I finally found out that the issue was that the request was being blocked by rules on our AWS WAF. We were protected against ourselves.

**Comment by Hallidayo** [comment]
Hi @castortech - that's great that its working for you, if you get the same issue feel free to reopen. Thanks again!
