### ISSUE TITLE
Storage Dashboard file upload changes hyphens in file name to underscore

### ISSUE THREAD

**Issue by clch** [supabase/supabase#27842]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Uploading files in the dashboard UI changes the hyphen in filenames to underscores.

## To Reproduce

1. Go to the storage page in dashboard.
2. Upload a file with hyphen in its name.
3. After the upload is complete, the hyphen becomes underscore.

## Expected behavior

The filename stays the same.

## System information

- Browser: Google Chrome

## Additional context

Renaming the file to have hyphens still works. Old files with hyphens are unchanged.

**Comment by Hallidayo** [comment]
Hi @clch - Thank you for the pull requests, it seems like hyphens are removed on upload due to the following regex: `/[^\w.-\/()]/g`, I'm just going to confirm why this is the case.

**Comment by saltcod** [comment]
fixed in https://github.com/supabase/supabase/pull/28030 and https://github.com/supabase/supabase/pull/26022
