### ISSUE TITLE
Cannot Create/Sign-up user with OTP

### ISSUE THREAD

**Issue by Blickwinkel1107** [supabase/supabase#27848]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Cannot create new user with email OTP verification

## To Reproduce

I'm using supabase-py. However I assume the issue relates to auth endpoint.

1. Sign in with OTP (automatic create a new user)
```
supabase.auth.sign_in_with_otp(
            {"email": user.email, "options": {"should_create_user": True}}
        )
```
2. verify OTP to sign up
```
supabase.auth.verify_otp(
            {
                "email": user.email,
                "token": user.otp,
                "type": (
                    "signUp"
                ),
            }
        )
```
3. Hit the error
```
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://******.supabase.co/auth/v1/verify'
```

## System information

- OS: Linux

**Comment by Blickwinkel1107** [comment]
I'm able to reproduce via cURL
I'm sure my token wasn't expired.

```
$ curl --request POST \                                                                                                                                                                         --url *******/auth/v1/verify \
--header 'Content-Type: application/json' \
--header 'apikey: ****' \                                                                                                                                                             
--data '{                                                                                                                                                                                              "type": "signUp",                                                                                                                                                                          
"email": "yuex1107@gmail.com",                                                                                                                                                                         "token": "083174"                                                                                                                                                                        
}'                                
                                                                                                                                                               {"code":403,"error_code":"otp_expired","msg":"Token has expired or is invalid"}
```

**Comment by GaryAustin1** [comment]
I don't know about Python, but `signup` all lower case was the JS method.  Now you use `email` for all the email type tokens.

**Comment by GaryAustin1** [comment]
![image](https://github.com/supabase/supabase/assets/54564956/e1635daa-b133-4e46-9cbe-e8c23781e3c8)

**Comment by Blickwinkel1107** [comment]
@GaryAustin1 Thanks for helping out! After looking at your post, I realize there might be some parameter update, so I upgraded gotrue package, the parameter signup is all lowercase now. And the issue resolved.
![image](https://github.com/supabase/supabase/assets/31503784/64f06013-798a-42c5-ae66-b3c43114e0f7)
Thanks again for your helping out!

**Comment by Blickwinkel1107** [comment]
However, I personally suggest that auth endpoint adjust the response of invalid parameter. 
I thought it was the token expiration and it turns out parameter outdated.
