### ISSUE TITLE
Cannot edit email templates

### ISSUE THREAD

**Issue by marosseleng** [supabase/supabase#27850]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On a hosted instance, I am unable to change email templates. I tried to edit the "Reset password" template and got the following error:
>Failed to update auth configuration: Auth Hooks can only be configured on Teams or Enterprise plans.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Have a hosted instance with free tier.
2. Click on Authentication -> Email templates.
3. Select "Reset password" template.
4. Add a word to the existing template.
5. Hit save.

## Expected behavior

I'd expect the template to be saved. Or if it isn't a feature supported in my plan then I'd like to have a clearer message shown to me and this behavior mentioned in the [docs](https://supabase.com/docs/guides/auth/auth-email-templates).

**Comment by marosseleng** [comment]
Hi @encima Thanks for a quick reply!

Regarding versions:
> auth version: 2.152.1
> PostgREST version: 11.1.0
> Postgres version: 15.1.0.103 (I see a button with available upgrade to 15.1.1.73, which I'm to upgrade now)

Regarding previous modifications to the template - I think there was none previously - I am using the default template:

```
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}">Reset Password</a></p>
```

**Comment by encima** [comment]
OK, if you can upgrade and let us know if the issue persists (it might also be worth hard refreshing the Supabase dashboard).

**Comment by marosseleng** [comment]
@encima the update seems to have done the trick. Edititng the templates now works fine. Thanks for pointing me in the right direction!

**Comment by jack2684** [comment]
I have the same issue here. @marosseleng where can I find the version?

<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/a2351930-0d5b-46fd-a5df-ce53a1bd2dbf" />
