### ISSUE TITLE
File can't uploaded into Storage Bucket

### ISSUE THREAD

**Issue by andriansandi** [supabase/supabase#27875]
Hi, 

I just try supabase on my local ubuntu using docker, the table function working properly but Storage cannot uploaded. I'm using command 
`docker compose up -f docker-compose.yml -f docker-compose.s3.yml up -d`

![Screenshot from 2024-07-09 15-55-35](https://github.com/supabase/supabase/assets/596269/902345b2-79b7-4718-bf5c-1c65d4464c3c)

Is any steps that I'm missing out?

Thank you

**Comment by cyluss** [comment]
Let me check if Supabase public URL is configured correctly for your deployment scenario

1. What URL do you connect to Supabase, like http://localhost:8000?
2. What is your `SUPABASE_PUBLIC_URL` in your .env file?
3. Please take and upload devtools screenshot, which should be devtools open first and try uploading second.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
