### ISSUE TITLE
The AI assistant is broken in the local environment. [Video]

### ISSUE THREAD

**Issue by erdemdev** [supabase/supabase#27884]
## To Reproduce

1. Spin up docker containers via Supabase CLI.
2. Go to the 'SQL Editor'.
3. Try chatting with AI.

[1720546308.webm](https://github.com/supabase/supabase/assets/38112087/746e50ae-7e58-4392-a587-33e13111815b)

## Expected behavior

The .env file at the root of my project with this configuration was working fine.

![1720546138](https://github.com/supabase/supabase/assets/38112087/7732a516-f125-4e63-9095-86cea76e7eb9)
![1720546173](https://github.com/supabase/supabase/assets/38112087/62d84988-e476-4fec-9582-91860be2e4b1)

## System information

- OS: Windows 10
- Browser: Brave, Chrome
- Supabase CLI: v1.183.5
- Go True: v2.152.1
- Postgres: 15.1.1.41
- Rest: v12.0.2

**Comment by Hallidayo** [comment]
HI @erdemdev - Thank you for opening the issue, Do you see any errors in the console?

**Comment by erdemdev** [comment]
> HI @erdemdev - Thank you for opening the issue, Do you see any errors in the console?

[1720782778.webm](https://github.com/user-attachments/assets/ed1c96ae-3e00-40ea-9159-ca9053227f0c)

I am receiving an internal server error.

**Comment by abeisleem** [comment]
Same issue here. I have the same setup as @erdemdev. This was working for me before upgrading from 1.176.11 to 1.183.5

**Comment by abeisleem** [comment]
@erdemdev, see the mentioned PR with fix above. The fix has been pushed to supabase@1.186.3. So you can change your start command to `npx supabase@1.186.3 start` and it will work.

**Comment by erdemdev** [comment]
Thank you, @abeisleem. I am closing the issue.

**Comment by cjlryan** [comment]
Experiencing this exact issue on the latest version (1.192.5). Same console logs. It would be helpful if there were a useful console error explaining why. Should I raise as another issue?

**Comment by abeisleem** [comment]
@cjlryan I just tested with version 1.192.5 and it seems to be working. The way I inspect this issue is by looking at the dev console (Console & Network) to determine what the issue is. Open it up, ask the Assistant, and see what you get back. Also, ensure you have the right setup. There should be a .env file in the root of your project with `OPENAI_API_KEY` key.
