### ISSUE TITLE
Triggers on auth.users are removed when updating local Supabase version

### ISSUE THREAD

**Issue by kainbryanjones** [supabase/supabase#27897]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When updating the supabase cli following [these instructions](https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli)(but using npm instead of brew). Everything updates and data is reset. However as a result all of the triggers I have after insert on the auth.users table are removed and I have to reapply them.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli
2. Follow the instructions but update with npm (I replaced the version number in package.json and ran npm i)

## Expected behavior

It should update. Schemas should persist but data reset.

## System information

- OS: macOS
- Browser: Firefox 
- Version of supabase-js: (what ever the latest was as of 9th of July 2024)
- Version of Node.js: Not sure. I'm not at my computer right now, but I can check later if requested.

## Additional context

Also why do I have to use the SQL editor to put triggers on auth.users? I know it's a protected table, but triggers are read actions and thus don't violate this. It would be a lot more pleasant if I could do this through the dashboard.

**Comment by silentworks** [comment]
You should use migrations to keep your database table schemas, triggers, functions on each upgrade of the CLI. This would be something hard for the CLI to keep persist for all upgrades, if something should go wrong in docker that data would be lost. Using migrations is what I'd recommend.

**Comment by encima** [comment]
Hey @kainbryanjones ,

Thanks for opening! As @silentworks said, this is a difficult thing to persist and [migrations](https://supabase.com/docs/reference/cli/supabase-migration) are likely the best approach. Alternatively, you can take a backup and restore that once upgraded.

Closing this for now as it is not really a CLI issue but please do comment if you have a suggestion on better ways to address (or document) this.
