### ISSUE TITLE
I'm not able to add new rows to database via supabase GUI(website)?

### ISSUE THREAD

**Issue by yaten2302** [supabase/supabase#27893]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Whenever I try to add a new row to supabase database via the website, I'm not able to do so.

![image](https://github.com/supabase/supabase/assets/129659514/5b93d53e-ae2e-4049-8b3e-b49ece36e4a0)

But, in the table the "hello2" value, which I just added is not being shown.

![image](https://github.com/supabase/supabase/assets/129659514/96eee830-78ec-4c09-b5e3-a5926ff6791b)

The value "teacher1", which is being shown here, was already present, ig I added that before adding the RLS policies(not really sure about that)? Is this error due to the RLS policies, which I've added to this table?

![image](https://github.com/supabase/supabase/assets/129659514/888e3e9e-f40d-43b0-8d66-7393e81ff4ab)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase table editor.
2. Pick any table and try to insert some data manually(by clicking on the insert option and then clicking on insert a row).
3. After that when the menu is opened add some data and click on save.
4. The data will not be added and the same screen will be shown(the menu will still be visible).

## Expected behavior

The data should be added easily without any issue.

## System information

- OS: Windows 10
- Browser Chrome
- Version of supabase-js: v1.24.05
- Version of Node.js: v20.9.0

## Additional context

Also, I've noticed that whenever I try to add the data without RLS policies, it gets added easily. I'm not sure about this, but I tried to remove the RLS policies in another table and then add the data in that table, it was getting added?

**Comment by GaryAustin1** [comment]
Are you running with impersonation mode on when using the table UI?  If so you have to meet RLS policies.  Looks like the first two letters of your impersonation setting is `po`, if so I assume that is postgres role which should not look at RLS. 

I'm assuming you are not getting a popup with error?
Try a different browser to see if you do get an error popping up.

**Comment by yaten2302** [comment]
Hey @GaryAustin1 , thanks for your response. Actually, there was a problem from my side. Actually, there was some issue in the filter option and that's why it was showing only 1 record i.e. of "teacher1". Now the records are being added correctly 👍 

But, I'm facing an issue, that whenever a new column is being added, after 2 it's showing 39, 40, 41, 42...<br>
![image](https://github.com/supabase/supabase/assets/129659514/66a6d468-00ad-49f0-b6bd-5120f3172de5)
<br>
I've set the "teacher_id" column to auto increment as well. Could you please guide that why it's not showing from 3, 4, 5...?
Actually, I clicked on the save button more than once, is this issue arising because of that? Do I've to delete this table and create a new one to eliminate this issue?
