### ISSUE TITLE
React Native and Fetch via Server API in nextjs - 401 Unauthorized error

### ISSUE THREAD

**Issue by heyfromapp** [supabase/supabase#27909]
# Bug report

## Describe the bug

I am trying to route my table entry and update via server api and including access_token in the header. And access_token, I am getting it from auth.getSession(). But getting 401 error. In the app, I can see the session with access_token.

What is the right approach to do this?

`const response = await fetch( "https://mydomain.com/api/seller/ext_order", { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: Bearer ${access_token}, }, body: JSON.stringify(data), }, );`

I have done my login using library. does that make any difference?

` const {data, error} = await supabase.auth.signInWithOtp({ phone: phone_number, });`

P.S

In the nextjs app route, I am able to see the header with  Bearer token.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Use access_token from auth.getSession() and send the request to server API.

## Expected behavior

access_token should allow the user to perform authed activities in the backend.

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: latest
- Version of Node.js: 18.17.0

**Comment by jovan-sremacki** [comment]
Hello, can I take a look at this one?

**Comment by Hallidayo** [comment]
Hi, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
