### ISSUE TITLE
Checkbox in Light theme

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#27914]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Checkboxes style is all black in table editor when set theme with light.
<img width="426" alt="image" src="https://github.com/supabase/supabase/assets/1522494/1c011bc7-13bc-4af6-a00b-71658d1a9895">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set theme to Light
2. Click on a table on Table Editor
3. Click checkbox in first column.

## Expected behavior

Background color of checkbox should  always be white when background-image is black.

Also, it would be better to unify the appearance of checkbox acorss studio. I notice another style:

<img width="751" alt="image" src="https://github.com/supabase/supabase/assets/1522494/e75a43c4-d9b6-4e9c-9eb4-b6e83a02c8d0">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Jaishree2310** [comment]
Hey @jingsam can you please assign this issue to me?
Thanks!!

**Comment by Hallidayo** [comment]
Hi @Jaishree2310 - no assignment process so feel free to open a pull request 👍

**Comment by harshsbhat** [comment]
this issue is fixed. Can you guys close this so it doesn't create a confusion?
