### ISSUE TITLE
Select rows is incorrect when switch pages in Table editor

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#27921]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Select some rows in Table editor, then go to next page, the selected rows is incorrect.

For example, I select one row with id = 1

<img width="548" alt="image" src="https://github.com/supabase/supabase/assets/1522494/819aa068-916d-44ba-ae52-186fd9b5b641">

Then I go to next page, as you see, the id=101 is selected.

<img width="365" alt="image" src="https://github.com/supabase/supabase/assets/1522494/25c2e473-e259-48d9-a795-553621ca9e68">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by saltcod** [comment]
Ideally, we'd deselect any selected rows on page change.

**Comment by harshsbhat** [comment]
This issue is already fixed. Can someone close this
