### ISSUE TITLE
Editing/Removing fk is very buggy - doesnt work

### ISSUE THREAD

**Issue by farzd** [supabase/supabase#2793]
-Removing does not work,
-Changing FK to different table does not work

it keeps FK the same

i'm unable to delete a column because of this, i emptied the table too to see if it would make a difference. 

![image](https://user-images.githubusercontent.com/1423413/128883564-3d1e86d0-89ed-47fc-ad72-971e73d019fa.png)

**Comment by joshenlim** [comment]
hey there @farzd! we've recently pushed a couple of updates to the column side panel editor - would you mind giving this a go again and see if the bug is still present?

**Comment by farzd** [comment]
@joshenlim i was able to remove the fk association but unable to delete the column or the table

![image](https://user-images.githubusercontent.com/1423413/133433804-c84b79bd-e19e-45fb-bc33-a9412eda94c9.png)

**Comment by joshenlim** [comment]
@farzd ahh sorry for getting back late on this one. This error probably means you have another table that's referencing the column `prizeId` of your `quizzes` table - hence why you're unable to drop the column. You might need to check which other table has columns that are referencing to `prizeId`

**Comment by farzd** [comment]
this was happening because i had a VIEW using that table. oops
