### ISSUE TITLE
Issue logging into supabase website with github creds

### ISSUE THREAD

**Issue by aaa3334** [supabase/supabase#27942]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi! Since yesterday I have been logged out of my superbase account and have been unable to log onto it with github credentials. It just keeps taking me back to the 'login' page.
Before yesterday it was working fine, however since yesterday it does not.

I have tried clearing the cache etc. but it has not worked.

Does anyone else have the same issue?

(Note this is not with the sdk or anything but the supabase website itself - supabase.com)

## To Reproduce

Go to sign in
Select github
Authorise
-- > Redirected back to sign in and are not logged in

## Expected behavior

Be able to log into supabase with github credentials

## Screenshots
na

## System information

- OS: [e.g. macOS, Windows] - mac
- Browser (if applies) [e.g. chrome, safari] - safari
- Version of supabase-js: [e.g. 6.0.2] na
- Version of Node.js: [e.g. 10.10.0] na

**Comment by Hallidayo** [comment]
Hi @aaa3334 - I think this maybe a local issue, please send an email to [support@supabase.io](mailto:support@supabase.io) and we'll have a look!
