### ISSUE TITLE
Supabase logo overlap with menu

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#27965]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The supabase logo is overlaps with menu item when scrolling:

https://github.com/user-attachments/assets/45b73f15-c8a1-41a4-a207-417bd3398949

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @jingsam - Thank you for opening this issue, It looks like we've got a couple of issues open with this same issue e.g [issue](https://github.com/supabase/supabase/issues/26763) and also some pulls open to fix this issue. I'm going to close this one but again thank you for taking the time to open!
