### ISSUE TITLE
  413 Payload Too Large

### ISSUE THREAD

**Issue by renjiali** [supabase/supabase#27964]
I use this for private storage, involving videos, but uploading 413 Payload Too Large , my videos Max 300M

 How do I lift this restriction?

**Comment by Hallidayo** [comment]
Hi @renjiali - Thank you for opening this issue. Just a couple of questions
- How are you uploading the file/s? 
- Are you doing uploads via the studio?

Their is also [this](https://supabase.com/docs/guides/storage/uploads/file-limits) documentation on the site which should help.

**Comment by lacvapps** [comment]
We are experiencing this same problem with self hosted. We can upload files under 5mb but not over even when updating the docker compose to allow for 500mb + it will still throw a 513

**Comment by renjiali** [comment]
> 你好@renjiali- 感谢您打开这个问题。我有几个问题
> 
> * 您如何上传文件？
> * 您是通过工作室上传的吗？
> 
> 网站上还有可以帮助的[文档。](https://supabase.com/docs/guides/storage/uploads/file-limits)

Sorry, you can close this issue directly, but my nignx configuration limits upload files to 50M

**Comment by Hallidayo** [comment]
Hi @Hallidayo - Thank you for coming back to confirm everything is okay for you now. Feel free to re-open if still an issue.
