### ISSUE TITLE
[Self Hosting] supabase-analytics is unhealthy, Monotonic time stepped backwards.

### ISSUE THREAD

**Issue by SaekiRaku** [supabase/supabase#27997]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Failed to start: container supabase-analytics is unhealthy.

Inspect the logs by `docker logs supabase-analytics`, got: 

```
LOGFLARE_NODE_HOST is: 127.0.0.1
Monotonic time stepped backwards!
Previous time: 1033435464
Current time:  1033305156
Aborted
Monotonic time stepped backwards!
Previous time: 1033539097
Current time:  1032852602
Aborted
LOGFLARE_NODE_HOST is: 127.0.0.1
Monotonic time stepped backwards!
Previous time: 1033854234
Current time:  1033848136
Aborted
Monotonic time stepped backwards!
Previous time: 1044701847
Current time:  1044636841
Aborted
```

## To Reproduce

use General steps to start up:

```
git clone --depth 1 https://github.com/supabase/supabase
cd supabase/docker
cp .env.example .env
docker compose pull
docker compose up -d
```

## Expected behavior

To start up

## Screenshots

<img width="817" alt="图片" src="https://github.com/user-attachments/assets/e4ac14ad-a979-4225-8538-8a9ee060af68">

## System information

- OS: macOS

## Additional context

-

**Comment by encima** [comment]
Hi there,
thanks for reporting. I am unable to reproduce this with the latest commit on `master`.
![image](https://github.com/user-attachments/assets/9853c793-4402-4b2e-961f-428946af2a98)

Can you:
- Compare the image versions and confirm they are the latest
- Let us know if this is using Docker or Orbstack or something else on Mac?
- Which version of OSX and which architecture?
- Can you also check `Date and Time` in your system settings to ensure the time is being set automatically via time.apple.com

**Comment by SaekiRaku** [comment]
@encima Hi, thank you. After I restart the OrbStack, it's successfully running.

I'm not sure what is change in the end, I'm guessing maybe because I turned off the VPN, so that `Date and Time` can sync with time.apple.com. But while I run the `docker compose up -d`, the system date seems is right.
