### ISSUE TITLE
Logs are not working properly | Getting 502 errors

### ISSUE THREAD

**Issue by raman04-byte** [supabase/supabase#27990]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The Postgres, API Gateway, and Query are not working in the Logs section

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Logs'
2. Click on 'API Gateway'
3. See error

## Expected behavior

The Logs and the query shouldn't have 502 error

## Screenshots

<img width="1650" alt="image" src="https://github.com/user-attachments/assets/8dda16ef-9170-453f-8e78-591cb5710f10">
<img width="1649" alt="image" src="https://github.com/user-attachments/assets/dd6f6604-7437-4588-bc54-15c4a32a9423">
<img width="1648" alt="image" src="https://github.com/user-attachments/assets/6b52a542-b067-4d63-a690-32fa42c3d572">

## System information

- OS: macOS, windows
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

I am not using CLI to run this locally I am cloning the repo and then following the steps and hence it's not working. 
I have tried to change to a .toml file and enable the analytics but still no benefits and also have looked into the docs multiple times and still no solution to the problem.

**Comment by encima** [comment]
Thanks for opening, this is being tracked [here](https://github.com/supabase/supabase/issues/27329) (and affects both CLI and repo clones)

**Comment by raman04-byte** [comment]
So is it solved now?

**Comment by encima** [comment]
A fix is incoming, see this [comment](https://github.com/supabase/supabase/issues/26785#issuecomment-2227119475)

Please track all in the linked issue.
