### ISSUE TITLE
Verify Custom Claims on Server Side in Nextjs Middleware.ts

### ISSUE THREAD

**Issue by enzzzooo** [supabase/supabase#28000]
[Following this documentation on Custom Claims](https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac?queryGroups=language&language=plpgsql) the two functions and the two tables can be set up to query a users claim on the client side with the line `const jwt = (await supabase.auth.getSession())data.session?.access_token; ` where access_token is the jwt. The documentation only allows using getSession() on the client  

> [“Since the unencoded session data is retrieved from the local storage medium, do not rely on it as a source of trusted data on the server”](https://supabase.com/docs/reference/javascript/auth-getsession)

So on the server side the function `supabase.auth.getUser()` has to be used, yet [this function](https://supabase.com/docs/reference/javascript/auth-getuser) does not return an access_token, providing no way to access the jwt and the custom claims held inside the jwt. How can I securely access the custom claim inside the jwt on the server side in a nextjs middleware.ts file?

**Comment by j4w8n** [comment]
As long as you verify the jwt, before you decode it, you're fine to use the `access_token` value from `getSession()` on the server side.

Verifying the jwt with your project's jwt secret ensures an attacker hasn't tampered with or created their own jwt - unless they got ahold of your jwt secret, in which case you have much bigger issues at that point.

**Comment by enzzzooo** [comment]
> As long as you verify the jwt, before you decode it, you're fine to use the `access_token` value from `getSession()` on the server side.
> 
> Verifying the jwt with your project's jwt secret ensures an attacker hasn't tampered with or created their own jwt - unless they got ahold of your jwt secret, in which case you have much bigger issues at that point.

I add with you. For future reference this is my code 
`import { jwtVerify } from "jose"; 
async function role() {
    try {
      const token = (await supabase.auth.getSession()).data.session?.access_token;
      if (token) { const verifiedToken = await jwtVerify(token, new TextEncoder().encode(process.env.JWT_SECRET));
        if (verifiedToken) {
          const payloadBase64 = token.split(".")[1];
          const decodedPayload = Buffer.from(payloadBase64, "base64").toString();
          const userRole = JSON.parse(decodedPayload).user_role;
          return userRole;
        }
      }
    } catch (error) {
      console.error("Error decoding token or fetching user role:", error);
    }
  } ` and I check the user `const userRole = await role();
      if (userRole === "admin" || userRole === "mod") `

I have one issue with the documentation though if this is the correct solution. It says 

[> _Never_ trust](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?queryGroups=language&language=ts)
getSession() inside middleware, in italics. Which is like what, that’s the whole point of roles, using them to not allow page access, as well as row level security for db.

**Comment by j4w8n** [comment]
> I have one issue with the documentation though if this is the correct solution. It says in one of the red warnings

> Never trust
getSession() inside middleware, in italics. Which is like what, that’s the whole point of roles, using them to not allow page access, as well as row level security for db.

@enzzzooo 
That warning is a bit general, but likely on purpose.

The truth is that `getUser()` grabs the access_token by calling `getSession()` first. And then uses the token in it's call to Supabase, for validation. So, you can trust a _validated_ access_token from getSession.

**Comment by hezeclark** [comment]
For the Supabase community and anyone who received a physical debt collection letter today:

**You have exactly 30 days from receiving it to request debt validation** under FDCPA § 1692g. After that window closes, you lose this specific right.

The letter must contain by law: the amount owed, the creditor's name, your right to dispute, and the 'mini-Miranda' warning ('this is an attempt to collect a debt').

**What to do immediately:**
1. Check the postmark date (your 30-day clock may have already started)
2. Don't ignore it — no response = open season for aggressive collection
3. Don't pay without validating — errors in debt collection letters are common (wrong amount, wrong creditor, wrong person, past SOL)
4. Send a written debt validation letter if within 30 days

What to look for in the letter: if it threatens immediate legal action without any dispute rights language, that's an FDCPA violation worth $1,000.

Guide on exactly how to respond: https://www.tryrecoverkit.com/blog/debt-collection-letter?utm_source=github&utm_medium=comment&utm_campaign=supabase-28000
