### ISSUE TITLE
SvelteKit: VerifyOTP not saving session

### ISSUE THREAD

**Issue by jameswoodley** [supabase/supabase#28027]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

SvelteKit:

When calling verifyOTP from the reset password flow using a link such as `{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=recovery&next=/auth/update-password` the verifyOTP call returns the correct user, but it is not persisted in a session. So when the update password page is loaded, the session is null, and the call errors stating `The Auth Session is missing`.

It seems when using the login flow with a lnk such as: `{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=email` the session is correctly persisted

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Call `await supabase.auth.resetPasswordForEmail(email);`
2. Browse to link sent in email
3. Call `const { error, data } = await supabase.auth.verifyOtp({ type, token_hash });`
4. Note `data` is populated
5. Call `await supabase.auth.updateUser({ password: request.password });` 
6. Error `The Auth Session is missing`

## Expected behavior

Session is persisted and password update is successful

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js:
  - "@supabase/ssr": "^0.4.0",
  - "@supabase/supabase-js": "^2.44.2",
- Version of SvelteKit: "2.0.0"

**Comment by encima** [comment]
Hey there,

thanks for opening! This issue has appeared a bit recently for both Svelte and Next apps. Can you confirm you have followed the guide [here](https://supabase.com/docs/guides/auth/server-side/sveltekit)?

Could you also provide a small reproducible repo (or sample code) and tell us how you are running your app (localhost, cloudflare pages etc)?

**Comment by jameswoodley** [comment]
Hi, thanks for the response.- yes I believe I've followed all the steps in the guide.. I've uploaded to a git repo for you to take a look at here: https://github.com/1dentityuk/app - and currently running localhost, but I'll also upload to vercel now and give it a try there too

**Comment by jameswoodley** [comment]
> Hi, thanks for the response.- yes I believe I've followed all the steps in the guide.. I've uploaded to a git repo for you to take a look at here: https://github.com/1dentityuk/app - and currently running localhost, but I'll also upload to vercel now and give it a try there too

Vercel is working either weirder - seems to log the user directly in when clicking Forgotten Password, which all that should do (and does do locally), is load a different component!

**Comment by gnswork** [comment]
I think I can reproduce it with latest official code:
https://github.com/supabase/supabase/tree/master/examples/user-management/sveltekit-user-management
After click the magic link user is redirected to login page instead of account page.

**Comment by jameswoodley** [comment]
> Hi, thanks for the response.- yes I believe I've followed all the steps in the guide.. I've uploaded to a git repo for you to take a look at here: https://github.com/1dentityuk/app - and currently running localhost, but I'll also upload to vercel now and give it a try there too

Yup same on vercel - clicking the link in the email just takes you to the auth page again, because there is no session so cannot access a protected route

**Comment by ChangJun2019** [comment]
@jameswoodley Hi, I had the same issue. It's now resolved. You can try upgrading @supabase/ssr to v0.4.1. In this version, someone has already fixed the related issues.

https://github.com/supabase/ssr/releases/tag/v0.4.1

**Comment by jameswoodley** [comment]
> @jameswoodley Hi, I had the same issue. It's now resolved. You can try upgrading @supabase/ssr to v0.4.1. In this version, someone has already fixed the related issues.
> 
> https://github.com/supabase/ssr/releases/tag/v0.4.1

Unfortunately not, same behaviour is occurring with 0.4.1. When visiting the /confirm endpoint, the OTP is validated, but the session is not persisted. I've put some logging in to track what both are doing:
<img width="176" alt="image" src="https://github.com/user-attachments/assets/67c26dfb-09cb-438f-96a7-27d65ec9fa6f">

The OTP validates, we get a session with an expiry, but the Auth Guard in the hooks.server.ts still doesn't have the session available from the `event.locals.getSafeSession` function

**Comment by jameswoodley** [comment]
Actually @ChangJun2019 it seems you are correct and I can confirm 0.4.1 DOES work. Thank you for the hint. Previously I had `^0.4.1` in my package.json, I ran `pnpm update --latest` assuming it would update, but it actually didn't. A hard coding of `^0.4.1` into my package.json did actually update it and I can confirm it now works

@encima I think we can call this closed, but perhaps a call out on the reset password PKCE flow pages that @supabase/ssr must be at a minimum 0.4.1 to work would be a good idea

**Comment by sanozie** [comment]
Perhaps this issue has been re-introduced in the latest SSR package. I've only installed Supabase SSR a week ago, (v5.0.2), and I'm having the exact same error doing the exact same flow (resetting password via SvelteKit & OTP)

**Comment by thedewpoint** [comment]
> Perhaps this issue has been re-introduced in the latest SSR package. I've only installed Supabase SSR a week ago, (v5.0.2), and I'm having the exact same error doing the exact same flow (resetting password via SvelteKit & OTP)

any luck resolving this?
