### ISSUE TITLE
Could not create new items

### ISSUE THREAD

**Issue by Sukkoth** [supabase/supabase#28022]
I had a table which had records in it (let's say 3). I then imported some other data (let's say 10) using csv and they all had their ID's generated automatically when they are added to the table. 

I have 13 records and they have id f 1rom to 13. I have deleted some records since I was working on delete feature of my project. let's say a record with ID of 6, 7 are deleted.

Now, when I start working on add feature, it tries to generate a record with ID of 4 (since this was the one it should add before I imported records from csv.). and when I try again, it tried with 5 and failed. I tried again and it worked since I have deleted a record with that ID (6). and then when I add another, it worked because 7 was deleted. and when I add another now, it tries to add the record with ID of 8 and gives duplicate ID error, it tries to increment the ID until it finds the correct ID. since ID of 13 is taken, I have to just retry until it reaches 14 to get the correct ID.   It works properly after that. I hope am not going to be told to generate ID for myself. (I have already turned on autogenerate ID field for the table)

here is the error, (I tried two times and it's just incrementing the ID and try)

`{
  code: '23505',
  details: 'Key (id)=(10) already exists.',
  hint: null,
  message: 'duplicate key value violates unique constraint "bookings_pkey"'
}
 ⨯ app\_lib\actions.js (117:11) @ createBooking
 ⨯ Error: Booking could not be created
    at createBooking (./app/_lib/actions.js:101:15)
digest: "432108719"
  115 |   if (error) {
  116 |     console.error(error);
> 117 |     throw new Error("Booking could not be created");
      |           ^
  118 |   }
  119 | }
  120 |
 POST /cabins/19 500 in 688ms
 GET /cabins/19 200 in 3517ms
{
  code: '23505',
  details: 'Key (id)=(11) already exists.',
  hint: null,
  message: 'duplicate key value violates unique constraint "bookings_pkey"'
}
 ⨯ app\_lib\actions.js (117:11) @ createBooking
 ⨯ Error: Booking could not be created
    at createBooking (./app/_lib/actions.js:101:15)
digest: "432108719"
  115 |   if (error) {
  116 |     console.error(error);
> 117 |     throw new Error("Booking could not be created");
      |           ^
  118 |   }
  119 | }
  120 |`

**Comment by encima** [comment]
Hi there,

Thanks for opening! Can you provide your table definition? This error looks like it is coming from your application where it is trying to generate an ID but does not know about the database state.

Using incrementing IDs is not always a bad idea but it is better to use an auto generating UUID on the table and let Postgres handle the ID on insert.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
