### ISSUE TITLE
In the docs, deno guide page shows Not Found due to 404 error

### ISSUE THREAD

**Issue by huisso97** [supabase/supabase#28028]
# Bug report

## Describe the bug
While reading docs, when I click the `deno guide` anchor, the page shows Not Found like the screenshot.
the reason is the request is failed due to 404 to `https://docs.deno.com/manual/getting_started/setup_your_environment`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/functions/local-development
2. Click on 'Deno guide'
3. See error

## Expected behavior
I can see the document of deno guide.

## Screenshots
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/d49b99c7-c6ce-4232-828b-5bf81af76782">

**Comment by charislam** [comment]
Thanks for opening the issue, @huisso97! I just tested and haven't been able to reproduce.

Are you able to open the Deno guide when you navigate directly via this link: https://docs.deno.com/runtime/manual/getting_started/setup_your_environment/?

**Comment by huisso97** [comment]
I can see the document well, thank you for checking the issue 👍
