### ISSUE TITLE
200 status after update, but nothing is updated (from the context of a lambda)

### ISSUE THREAD

**Issue by andrewgwardwell** [supabase/supabase#28041]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Update to row returns a 200 status code when nothing is updated.

## To Reproduce

I am trying to update an already existing row in a Lambda script. I am using the service_role key. API logs record a 200 status code in response to the PATCH. I have two RLS policies on the table, neither is attached to Update action (Insert and Delete). Confirmed that the data I am sending is correct (via logging in the lambda). 

```
 const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
    const { data, error } = await supabase
      .from('chapters')
      .update(updateData)
      .eq('id', chapterId)
      .select();
```

No error. Or Data is returned. I have confirmed that the chapterId === the id. Update data is a single text value for a text field.

## Expected behavior

Row is updated or Status code doesn't give me a 200.

## System information

- OS: AWS Lambda
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 2.44.3
- Version of Node.js: 20

**Comment by andrewgwardwell** [comment]
I have disabled my RLS policy for this table temporarily. This has solved the update issue. However, I don't want to leave this without RLS enabled. I don't understand why the policies I have attached are not allowing the update of my row. Maybe someone has a pointer?

```
[
  {
    "policy_name": "Enable insert for users based on user_id",
    "command": "a",
    "policy_using": null,
    "policy_check": "(( SELECT auth.uid() AS uid) = user_id)"
  },
  {
    "policy_name": "Enable read access for all users",
    "command": "r",
    "policy_using": "true",
    "policy_check": null
  },
  {
    "policy_name": "Update Chapter By Service Role",
    "command": "w",
    "policy_using": "true",
    "policy_check": null
  }
]
```

**Comment by Hallidayo** [comment]
Hi @andrewgwardwell - Thankyou for opening the issue. Is your first policy just for `INSERTS`? or is the policy for both `INSERTS` and `UPDATES`?

**Comment by andrewgwardwell** [comment]
@Hallidayo thanks for getting back to me. I am a relative postgres newbie, but I think that polcmd == 'a' is INSERT? Via the Supabase UI it is only listed for INSERT.

![Screen Shot 2024-07-17 at 9 41 03 PM](https://github.com/user-attachments/assets/b854ebe9-8d9e-47a0-94d8-bea12d590edc)

**Comment by encima** [comment]
Hi @andrewgwardwell 

As @Hallidayo alluded in his message, since you are `updating` (or `upserting`), the RLS policy needs to exist for both `insert` and `update`.

Try that and let us know how it goes!

**Comment by andrewgwardwell** [comment]
@encima @Hallidayo ok, I apologize for my confusion here. And thanks for taking a look! I am doing everything via the Javascript SDK. I am explicitly using the .update() method and chaining to an .eq that is matching a confirmed 'id' of my row. Are you saying that because I have an INSERT policy it is also effecting update actions?

What I am more confused about is the service_role key I am using for the update. I read the documentation here: [API KEYS](https://supabase.com/docs/guides/api/api-keys#the-servicerole-key). I think I misunderstood "It can bypass Row Level Security..." to mean that it does? Is there any documentation you can point me to that describes RLS that needs to be in place for a 'update' that uses the service_role key (since the one I have in place doesn't seem to work)?

**Comment by GaryAustin1** [comment]
I've seen this when your service role client gets a user token loaded in by the session.   Typically this is when one uses an SSR/auth-helpers client to create a service role client.  That will not work as it gets a user session in it.

The exact symptoms are as you describe.  You think you are service_role, but if you turn off RLS and it works it means you are not.

**Comment by andrewgwardwell** [comment]
@encima @Hallidayo @GaryAustin1 that sounds right. The user creates the db row (with access token but server side), and then I send the info off to an SQS, a lambda is triggered does some long tasks (TTS for instance). Once a file is dumped in my bucket I have another lambda that is triggered this is the one that updates the row that the user just created (but there is no access token available so the service role is used). 

Do you know how Supabase ties the sessions together? Is it IP or some combination of things? If I remove my RLS policy for update maybe it will bypass this issue? Or perhaps there is an RLS policy that disallows updates from user, but allows them from service role?

Thanks for all the help.

**Comment by GaryAustin1** [comment]
Service_role bypasses RLS.  If you have RLS enabled and no policy for instance service role will have access.
Please triple check you are using service role and not anon role.  The only way I know to share would be on the same server or same browser.  Every request to the Supabase server is separate and not related to any other.

You could also change your RLS to be TO anon and authenticated, with a policy of TRUE.  If that works with your "service_role" client (versus using TO service_role) then you have either a signed in user jwt or anon key in your client.

**Comment by andrewgwardwell** [comment]
I have resolved this. For whatever reason, my configured RLS policies and the service_role key where conflicting somewhere along chain of things. Removing the rls policies seemed to fix my issue.

@GaryAustin1 @encima @Hallidayo thank you for your help!

**Comment by CuongGuti** [comment]
Hello,
I got the same issue.
>> 200 status after update, but nothing is updated!!!

I changed to use ALL, and it works. However, I need UPDATE to work as well.

**Comment by Arunkumar-webzenith** [comment]
i am getting this same problem in multiple places like updated ,inserts ,via webhook events,and creation it give 200 but nothing is updated or inserted and it is random like some times it is inserting some times not i dont know why
