### ISSUE TITLE
Docs include `count` named option for every function call

### ISSUE THREAD

**Issue by Stokestack** [supabase/supabase#28078]
# Improve documentation

## Link 
https://supabase.com/docs/reference/javascript/update

## Describe the problem
The documentation for the JavaScript update method includes an option that controls how affected rows will be calculated on all functions, including those that do not use/require it

## Additional context
![noCountReturned](https://github.com/user-attachments/assets/fa986984-c652-405d-b759-21bacaf63c11)

**Comment by encima** [comment]
Thanks for opening!

In the first code sample, this purely updates the table and only returns an error so nothing would be returned.

That said, the `count` option is a named option for all calls so it is included for each function and this seems like a bug. I will edit this issue to reflect that.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
