### ISSUE TITLE
Vercel environment variables aren't marked as `sensitive` in preview

### ISSUE THREAD

**Issue by quick007** [supabase/supabase#28171]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The integration with Vercel automatically imports environment variables for use in production (which is very convenient, thank you). It also marks things like the JWT key and service key as sensitive, like so:
![image](https://github.com/user-attachments/assets/89d7b65c-85bb-4263-89fa-0102fd6998ed)

However, when adding keys to development and preview environments, they aren't marked as sensitive:
![image](https://github.com/user-attachments/assets/be7dd479-2581-4e56-ba2a-c7a7900a5ba4)

I have a feeling it also has to do with this error message: 
![image](https://github.com/user-attachments/assets/b61e6625-122d-4f71-9f68-b07edb86e20c)

(for reference, those are the keys that should be marked sensitive)

## To Reproduce

1. Deploy smth on vercel, then add the supabase integration to your project
2. Enable all environments via the settings on supabase:
![image](https://github.com/user-attachments/assets/5d0a32dd-91d1-49bf-937d-02acc0772a69)
3. See error when you navigate back to vercel and select the `preview` or `development` environment
4. You can also try clicking `resync enviroment errors` on supabase, which yields the error above

## Expected behavior

The keys should be marked as sensitive in all enviroments

## Screenshots

See above

## System information

Not relevant

**Comment by quick007** [comment]
*Vercel doesn't allow users to create sensitive environment variables in development, but this still applies to preview

**Comment by encima** [comment]
Hi there,

Thanks for opening! This is covered in Vercel's [docs](https://vercel.com/docs/projects/environment-variables/sensitive-environment-variables#sensitive-environment-variables)

If you would like the variable to be `sensitive`, then you would need to only use it in `Preview` and/or `Production.

Using a development Supabase project for your `Development` is recommended here
