### ISSUE TITLE
Display rate limit in Official Next + Supabase Quick Start

### ISSUE THREAD

**Issue by 3willows** [supabase/supabase#28200]
# Improve documentation

## Link 

Supabase Starter: https://vercel.com/templates/next.js/supabase
Demo of Supabase Starter: https://demo-nextjs-with-supabase.vercel.app/
YoutTube tutorial: https://www.youtube.com/watch?v=WdA6b0jPNv4 

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

As elaborated in [this blogpost](https://3willows.github.io/2024-07-25-display-rate-limit/), it is very easy for the new developer to exceed the email rate limit for signing up in the "FASTEST way to get started with Next.js and Supabase in 2024".

In fact, even the [demo](https://demo-nextjs-with-supabase.vercel.app/login?message=Could%20not%20authenticate%20user) deployed on Vercel failed when I attempted to sign up two users in a row.

## Describe the improvement

A clear and concise description of the improvement.

Option #1: as per the title, display rate limit on the Sign Up/ Sign In page.
Option #2: display toaster message to stop anyone signing in when there are 0 users.
Option #3: if there are no users, do not even display the Sign In option.

## Additional context

Add any other context or screenshots that help clarify your question.

I do not think the tutorial is open sourced, otherwise I would be happy to make a PR along the lines of one of the three options above.

**Comment by 3willows** [comment]
Thanks.  It seems the actual code lives on a [subdirectory](https://github.com/vercel/next.js/blob/canary/examples/with-supabase/README.md#demo) maintained by Vercel.  I will see if I can round up some contributors to work on this together.

**Comment by Hallidayo** [comment]
Hi all - I've just had a check of the most recent version of the Next JS Supabase quickstart and when you navigate to the sign up page a warning is now in place:

<img width="790" alt="Screenshot 2024-09-09 at 20 35 44" src="https://github.com/user-attachments/assets/9743b53f-9b60-44fb-a975-6c1694d39086">

I'm going to close this one but thank you all for your help!
