### ISSUE TITLE
Bug: types.gen generated without any modification in database because view references twice same table

### ISSUE THREAD

**Issue by littleannie** [supabase/supabase#28212]
# Bug report

- [ X] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi there,

We have been experiencing a recurring issue since updating to Supabase version 1.183.5, specifically when generating the types.gen.ts file.

We have a view that references the same table twice but points to different records. Consequently, we have two distinct references.

When generating the types.gen.ts file, differences are created even though we have not made any modifications to our database schema.

We do not understand why the order is generated differently in a seemingly random manner. As a result, we are encountering numerous issues with our GitHub CI.

Please feel free to reach out if you need more information.

## To Reproduce

1. create a view referencing twice the same table 
2. Commit 
3. generate types.gen many times without any db schema modification 

## Expected behavior

The types.gen should not be edited if no modification made on the db 

## Screenshots
<img width="962" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/b85b38d5-b92b-40bd-a5b2-0c8334f67724">

## System information

- OS: [e.g. macOS, Windows] : macOS
- Browser (if applies) [e.g. chrome, safari] : Chrome
- Version of supabase-js: [e.g. 6.0.2] : ^2.44.4
- Version of Node.js: [e.g. 10.10.0] : 20.16.0

**Comment by encima** [comment]
Hi there,

thanks for reporting this! Could you provide a small reproducible example please?

Also, can you confirm that the order does not change in CLI versions before `1.183.5`?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by littleannie** [comment]
Hi, 

Sorry for the delay in response. 
We still have the same concern and it becomes more and more restrictive on a daily basis.

The order changes in CLI versions before 1.183.5. 

I will come back to you with a a small reproducible example
