### ISSUE TITLE
Adding new policy modal has overlapping buttons

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [supabase/supabase#28226]
![Screenshot from 2024-07-27 17-54-12](https://github.com/user-attachments/assets/d3c55f8c-4be8-41fa-bdfc-c27a9f44fd4d)

**Comment by Mohammed-Yasin-Mulla** [comment]
PR Link : #28225

**Comment by MrBlackGhostt** [comment]
if this is not solve i like to work on it

**Comment by Mohammed-Yasin-Mulla** [comment]
@MrBlackGhostt You can always give it a shot. Who knows your solution might be better than mine 🙂

**Comment by Mohammed-Yasin-Mulla** [comment]
@encima a gentle reminder, I have my PR open 🙂 .

**Comment by encima** [comment]
@Mohammed-Yasin-Mulla thanks, I see that @saltcod has been reviewing it so I will let them review. It needs approval from a member of the frontend team.
