### ISSUE TITLE
supabase sign up error :  Could not authenticate user

### ISSUE THREAD

**Issue by zuhairmd7** [supabase/supabase#28229]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @zuhairmd7 - thank you for opening the issue. Just a couple of questions for you:

- Where are you getting this error? Is it in the Supabase console or through one of the libraries?

- Have you got a screenshot or video of where you are getting the issue?

**Comment by Hallidayo** [comment]
Hi @zuhairmd7 , We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
