### ISSUE TITLE
How to setup debugger for supabase in VSCode

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#28235]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

Hello! I am a newly supabase developer and have contributed a few PRs to fix some minor issues. I am trying to setup debugger for supabase in VSCode, to solve more complex issues. I followed with Next.js office [docs](https://www.nextjs.cn/docs/advanced-features/debugging) on Debugging but with no success. I can't add breakpoints in the source code. VScode always complains 'Unbounded breakpoints'. How are supabase teams debug the source code? I think adding some tips on debugging with VSCode in `CONTRIBUTING.md` is quite usefull for newly contributors like me.

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by Mohammed-Yasin-Mulla** [comment]
@jingsam to help you with your question it would be best if you could post your query at https://github.com/orgs/supabase/discussions, where the community would be more than happy to help you.

Asking questions on the issues panel would not help much 🙂
