### ISSUE TITLE
Database Tables should list views in selected schema, not list all views.

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#28253]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

At `Database -> Database  Tables`, views other than the selected schema show in the list.
<img width="977" alt="image" src="https://github.com/user-attachments/assets/c1613008-e8a8-4307-bc38-c801c7e0b194">

This issue only affects the self-host or local devlopement environments, not platform version, as they request different apis.

I have tracked this bug.  I believe it's caused by not pass `include_schemas` query parameter to `pg-meta`

https://github.com/supabase/supabase/blob/f9751c2e13976a9cf5d4227908e009a8868afde5/apps/studio/pages/api/pg-meta/%5Bref%5D/views.ts#L24-L33

To fix this issue, we could reuse the code of `tables list`

https://github.com/supabase/supabase/blob/f9751c2e13976a9cf5d4227908e009a8868afde5/apps/studio/pages/api/pg-meta/%5Bref%5D/tables.ts#L29-L55

I guess `foreign table` and `material view` will cause the same issue.

I can send a PR to fix this issue if this issue is confirmed by the supabase team.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by saltcod** [comment]
Yup I think that's it. A PR would be great @jingsam, thank you!
