### ISSUE TITLE
Swift Facebook auth error invalid nonce description: Nonces mismatch

### ISSUE THREAD

**Issue by superClown** [supabase/supabase#28252]
# Bug report

## Describe the bug
Swift Facebook auth error invalid nonce description: Nonces mismatch

## To Reproduce
When I successfully login with facebook, I get the FBSDKLoginKit.LoginManagerLoginResult data. When I use the following mapping relationship:
OpenIDConnectCredentials.provider       -> .facebook
OpenIDConnectCredentials.idToken        -> FBSDKLoginKit.LoginManagerLoginResult.authenticationToken.tokenString
OpenIDConnectCredentials.nonce          -> FBSDKLoginKit.LoginManagerLoginResult.authenticationToken.nonce
OpenIDConnectCredentials.accessToken    -> FBSDKLoginKit.LoginManagerLoginResult.token.tokenString

Calling SupabaseClient.auth.signInWithIdToken(credentials:), I got the following error message:
▿ AuthError
  ▿ api : APIError
    - msg : nil
    - code : nil
    ▿ error : Optional<String>
      - some : "invalid nonce"
    ▿ errorDescription : Optional<String>
      - some : "Nonces mismatch"
    - weakPassword : nil

## Expected behavior
How do I configure it to authenticate successfully?

## System information

- OS: [iOS 17.2 (Simulator)]
- Version of Supabase-Swift: [2.14.3]
- Version of Facebook: [17.0.2]

**Comment by encima** [comment]
Hi there, this is related to [this React Native issue](https://github.com/react-native-google-signin/google-signin/issues/1176#issuecomment-2082523850) and we are waiting for that fix as well.
We do have the `SKIP NONCE` argument that can be used in these situations, until the fix is delivered however.

Let us know if you have issues or that is not suitable and we can re-open!

**Comment by superClown** [comment]
> Hi there, this is related to [this React Native issue](https://github.com/react-native-google-signin/google-signin/issues/1176#issuecomment-2082523850) and we are waiting for that fix as well. We do have the `SKIP NONCE` argument that can be used in these situations, until the fix is delivered however.
> 
> Let us know if you have issues or that is not suitable and we can re-open!

Thanks. 
By the way, I know Google can enable `SKIP NONCE` on the Providers, how do I set it up on Facebook?
