### ISSUE TITLE
Small typo in Realtime Inspector

### ISSUE THREAD

**Issue by aufarijaal** [supabase/supabase#28275]
Code:
https://github.com/supabase/supabase/blob/a389866b5d8e5bc5ec5b6fff49953d1a16dc4036/apps/studio/components/interfaces/Realtime/Inspector/MessageSelection.tsx#L62

Screenshot
![2024-07-30_16-07](https://github.com/user-attachments/assets/6245c884-e019-46ce-8903-1e0b5bb82022)

it says "Select an message" instead of "Select a message"

**Comment by harshsbhat** [comment]
Done

**Comment by harshsbhat** [comment]
why did you close this issue? The PR is not merged yet

**Comment by aufarijaal** [comment]
>  why did you close this issue? The PR is not merged yet
> 

I am sorry. I still learning how the flow works. I have reopened the issue.

**Comment by harshsbhat** [comment]
Not an issue
