### ISSUE TITLE
Could not locate an example named "with-supabase"

### ISSUE THREAD

**Issue by grantspilsbury** [supabase/supabase#28286]
In the Vercel Supabase template https://vercel.com/templates/next.js/supabase
I tried to run `npx create-next-app -e with-supabase` and got the error:
`Could not locate an example named "with-supabase".`

**Comment by encima** [comment]
Hey there,
Thanks for opening, the [with-supabase](https://github.com/vercel/next.js/tree/canary/examples/with-supabase) is here.

If you cannot find it, I am afraid you would need to open an issue with next.js repository as it is not related to us, directly. Sorry about that!

As a sidenote, I just tried the command on my machine and was able to create the example so it could be related to the version of the package you have or network connection
