### ISSUE TITLE
Missing Page: Github Integration Docs

### ISSUE THREAD

**Issue by rpie3** [supabase/supabase#28284]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/not-found?page=platform%2Fgithub-integration)

## Describe the problem

All the links to obtain more information on the Supabase Preview in Github bring you to a 404

## Describe the improvement

They should link to a page that exists.

## Additional context
![Screenshot 2024-07-30 at 4 03 40 PM](https://github.com/user-attachments/assets/1f5fc60b-485f-4f7a-9b9c-1b4b86debe36)
![Screenshot 2024-07-30 at 4 01 42 PM](https://github.com/user-attachments/assets/3fc7514c-c557-4f95-bc16-b7fdec377955)

**Comment by encima** [comment]
Hey @rpie3 
Thanks for this! The page is indeed missing and it seems like it is not in the docs as a single page (should be [this](https://supabase.com/docs/guides/cli/managing-environments#configure-github-actions) I think). Let me ping the @supabase/integrations team and see where this should be linking to

**Comment by kamilogorek** [comment]
Thanks, updated.
