### ISSUE TITLE
Unable to use parenthesis to work with arguments in database functions for table names 

### ISSUE THREAD

**Issue by customputing** [supabase/supabase#28315]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to create a table using a Database Function I am unable to use the function_name.argument_name format because the format has the script looking for schema.table, the syntax check will not allow me to use parenthesis for that spot either as you can see in this screenshot it errors. I can get this to work fine as a value for a column, but not for a table name in creation or using ALTER either.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Database Functions in Supabase console
2. Create a function to create new table using an argument as the table name
3. Try with and without parenthesis

## Expected behavior

1. Able to use argument as the name of a table

## Screenshots

![image](https://github.com/user-attachments/assets/436cce4f-ba7d-45ac-8e62-fd420cc06d63)

## System information

- OS: [Windows]
- Browser (if applies) [e.g. chrome, safari]
- Javascript/React-Native

**Comment by GaryAustin1** [comment]
That does not look like valid SQL at all.
Normally to create tables in a function (which is considered a bad idea) you have to use execute and build the SQL in that.

https://stackoverflow.com/questions/40435864/create-function-to-create-table-postgresql
https://stackoverflow.com/questions/73369116/how-to-create-table-with-its-columns-based-from-the-parameter-passed-from-functi

The code you are showing is not Supabase's but is Postgres SQL.

**Comment by customputing** [comment]
I did have the format above working with modifying values no problem so figured it should work for the table name also. Swapping the language to plpgsql did pull it off. Thanks.  
![image](https://github.com/user-attachments/assets/533bedfc-1c20-4099-b0d5-a15a296e5dff)
