### ISSUE TITLE
Copy/Paste problem in the auth error codes documentation

### ISSUE THREAD

**Issue by TheFoxan12** [supabase/supabase#28320]
# Improve documentation

## Link 

https://supabase.com/docs/reference/dart/auth-error-codes

## Describe the problem

The documentation describes the way AuthError works for the javascript client, and not for other clients. It's just a copy/paste of the javascript description. This is confusing because the names aren't the same, and the way it works seems to be different too.
For example, it is said that the error class "AuthError" would wrap all different errors, but in dart the class is not "AuthError" but "AuthException".
Also, i can't find the error code in the exception class, or the "isAuthApiError" function, for example.

## Describe the improvement

An improvement would be to document the way error management works for each type of client.

**Comment by charislam** [comment]
@dshukertjr could you take a look at this one? 🙏🏼

**Comment by dshukertjr** [comment]
Yeah, we haven't added error codes support yet on Flutter. We can hide this section until we add it.

**Comment by TheFoxan12** [comment]
Is there any way i can access the error code when I make an auth request ? Because without it I don't see how to manage the auth errors.
