### ISSUE TITLE
Site URL and Redirect URLs not saving when adding in the URL Configuration section

### ISSUE THREAD

**Issue by jaydeepw** [supabase/supabase#28344]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When I goto URL Configuration and add the Site URL and Redirect URL and click save in the UI. They dont get saved.

When I goto URL Configuration and add the Site URL and Redirect URL and click save in the UI. They dont get saved.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/dashboard/project/ancxcrsffnwdtmdbnqbm/auth/url-configuration
2. In the Site URL input box, enter a url
3. Click Save.
4. Reload
5. The saved data is not seen

## Expected behavior
The saved url should be seen even when reloading.

Uploading Screen Recording 2024-08-02 at 8.51.28 PM.mov…

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @jaydeepw - thank you for opening the issue, I've just tried the steps and I seem to be able to change the URL value and then when I refresh the value saves:


https://github.com/user-attachments/assets/db18f60f-4eee-4340-8fa5-9b59fa99702a

Is it possible you could try again and report back if you are still experiencing the same issue?

**Comment by jaydeepw** [comment]
Sorry the problem was with my browser. This is working.
