### ISSUE TITLE
Password recovery does not work

### ISSUE THREAD

**Issue by JulienCertain** [supabase/supabase#28450]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I can't reset my password for the sign in. I've tried it with 2 different accounts and I'm not receiving any email. Both accounts use different email providers.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/dashboard/forgot-password
2. Enter email
3. Click "Send Reset Email"
4. Not receiving any email

## Expected behavior

I should receive an email with a link for resetting my password

## Screenshots

-

## System information

- OS: Windows
- Browser: 128.0.3
- Version of supabase-js: IDK
- Version of Node.js: -

**Comment by encima** [comment]
Please open a support ticket at https://supabase.help (you may need to create a new account for this) or email support@supabase.io
