### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by hemanthkb97** [supabase/supabase#2846]
# Bug report

## Describe the bug

when I click the email confirmation link, I get the site can't be reached but it confirms email.

I'm new to supabase 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots

![signal-2021-08-16-120514](https://user-images.githubusercontent.com/62005727/129524421-e7b957f0-0bdc-41c5-adb7-5db577d21c4a.jpg)

## System information

- OS: windows
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by gpaw** [comment]
Did you start your local server? e.g. `npm run dev`

**Comment by hemanthkb97** [comment]
@gpaw  no i did't, im using flutter.
