### ISSUE TITLE
Forgot password issue

### ISSUE THREAD

**Issue by dotmaker619** [supabase/supabase#28485]
# Bug report
Hi community.
Currently, I'm working on Next.js project with supabase, and got some troubles for forgot password implementation with suabase.
I've used the following function for it.
```
const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
  redirectTo: 'https://example.com/update-password',
})
```
But it doesn't work, and get 500 error now.
This is supabase auth logs on my end.
![image](https://github.com/user-attachments/assets/5a2443a1-be7a-4d35-a75c-6c9026b78bcc)
As you can see there, 2 same requests are sent at once, one is failed and other one is completed.
But the status is 500 even though the request is completed, and can't receive any emails.
And this is an error I got in the first request(Failed request on the above image).
![image](https://github.com/user-attachments/assets/aed76a24-4d7d-4558-9c14-df5b563d2729)
I'm not sure why sending requests twice at once, and what the issue is. 
Please teach me how to fix it.

Thanks.

**Comment by encima** [comment]
Hi there, thanks for opening!
As you are redirecting to this URL, do you have any code/hooks that are automatically calling the `/recover` endpoint on load?

If you can provide a reproducible example, this would be very useful. Thanks!

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by theodufort** [comment]
Im having the same issue where all the steps complete successfully but the event is not triggered when i do:
` useEffect(() => {
    supabase.auth.onAuthStateChange(async (event, session) => {
      if (event == "PASSWORD_RECOVERY") {
        window.alert("jesus");
        const newPassword = prompt(
          "What would you like your new password to be?"
        );
        const { data, error } = await supabase.auth.updateUser({
          password: newPassword,
        });

        if (data) alert("Password updated successfully!");
        if (error) alert("There was an error updating your password.");
      }
    });
  }, []);` even if the logs show everything is successfull and i get a code in the url: 
![image](https://github.com/user-attachments/assets/b2c3d272-37f2-4dfe-9420-a16fa49cd3cc)
