### ISSUE TITLE
Function Search Path Mutable (Security Advisor) issue with pgvector

### ISSUE THREAD

**Issue by teamclouday** [supabase/supabase#28507]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The security advisor on supabase project website is giving me warning of "Function Search Path Mutable" on my rpc function which uses pgvector operator `<=>` to compute similarity. It's asking me to set `search_path` to empty string. If I set it to empty string, it will throw an error of "operator does not exist" when the function is called. Similar issue can be found in this [discussion](https://github.com/orgs/supabase/discussions/23207). 

I was able to resolve the issue by `SET search_path = public, extensions`. I think the warning on the website security advisor is a bit misleading. Is there any way to turn it off for functions that uses pgvector operators? Or any way to set empty search path but still able to use the operator?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Step to reproduce the error code:
```sql
-- Debug search_path with pgvector
CREATE TABLE
    public.test_table (
        id uuid PRIMARY KEY DEFAULT uuid_generate_v4 () UNIQUE,
        embedding vector (4)
    );

-- Insert some data
INSERT INTO
    public.test_table (embedding)
VALUES
    ('[1, 2, 3, 4]'),
    ('[2, 3, 4, 5]'),
    ('[3, 4, 5, 6]'),
    ('[4, 5, 6, 7]');

-- Create query function
CREATE
OR REPLACE FUNCTION search_test_table (query_embedding vector (4)) RETURNS SETOF public.test_table LANGUAGE plpgsql
SET
    search_path = '' AS $$
BEGIN
    RETURN QUERY
        SELECT *
        FROM public.test_table t
        WHERE t.embedding <=> search_test_table.query_embedding < 0.001;
END;
$$;

-- Query
SELECT
    *
FROM
    search_test_table ('[1, 2, 3, 4]');

-- Clean up
DROP TABLE public.test_table CASCADE;
```

Replace with a non-empty `search_path` works:
```sql
-- Create query function
CREATE
OR REPLACE FUNCTION search_test_table (query_embedding vector (4)) RETURNS SETOF public.test_table LANGUAGE plpgsql
SET
    search_path = public, extensions AS $$
BEGIN
    RETURN QUERY
        SELECT *
        FROM public.test_table t
        WHERE t.embedding <=> search_test_table.query_embedding < 0.1;
END;
$$;
```

## System information

- Postgres version: 15.1.1.54

**Comment by charislam** [comment]
You can qualify operator search paths using the Postgres operator function: https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH

**Comment by teamclouday** [comment]
Thank you! So in my case I had to replace `<=>` to `OPERATOR(extensions.<=>)`
