### ISSUE TITLE
Unable to import CSV, even though the file is correct

### ISSUE THREAD

**Issue by ilhamgum** [supabase/supabase#28502]
### Discussed in https://github.com/orgs/supabase/discussions/28501

<div type='discussions-op-text'>

<sup>Originally posted by **ilhamgum** August  9, 2024</sup>
So, I have this CSV file that I want to import, done checked the header and even the data inside of it, all of them.

![Screenshot 2024-08-09 141229](https://github.com/user-attachments/assets/3457dfe6-110e-4aa7-822d-007f164e79db)

Also, no error given on supabase, but after click "Import data", it gives me this error

`The data that you are trying to import is incompatible with your table structure`
![Screenshot 2024-08-09 141334](https://github.com/user-attachments/assets/5923d20c-1a44-41b0-8dee-921450bad501)

What should I do next? I have re-checked it several times, and ensure it does not contain any error on the data
</div>

**Comment by encima** [comment]
Closing as it is resolved in the linked Discussion.
