### ISSUE TITLE
Unsupported email provider

### ISSUE THREAD

**Issue by gpaw** [supabase/supabase#2851]
# Bug report

## Describe the bug

Unable to login to user after creating user, via localhost
Unable to send password recovery using app.supabase.io web console
Unable to obtain user details via supabase-py

Error message given: Unsupported email provider

![image](https://user-images.githubusercontent.com/39247918/129577599-f02a9e3f-3832-406f-bbd8-e6c744fee59a.png)

![image](https://user-images.githubusercontent.com/39247918/129577671-9ffa9227-ddb5-4c98-98af-2192e4b4201b.png)

![image](https://user-images.githubusercontent.com/39247918/129577854-e425e86e-451b-4934-89e6-8fd8fd3a8289.png)

## To Reproduce

1. Create a new database
2. Rebuild app in vercel, update environmental variables
3. invite user, change password (successfully)
4. Log out user
5. send user recovery password (failed)

For some reason, this only happens after the app has been built on Vercel.

## Expected behavior

1. Able to obtain user recovery password email
2. Able to login

## System information

- OS: macOS 10.15
- Version of supabase-js: 1.11.8
- Version of Node.js: 14.17.3
- supabase-ui: 0.6.1
- Supabase-py: supabase-py==0.0.2

## Additional context

Deleting database and recreate allows sending recovery password
But after the vercel app has been built, and the first user logs on, it starts failing from there on.

Restarting server does not help

### LOGS

time="2021-08-16T14:52:40Z" level=info msg="400: Unsupported email provider" component=api error="400: Unsupported email provider" method=POST path=/token referer="https://WEBAPPURL/" remote_addr="IP_ADDRESS" request_id=14bbdd59-e798-4c09-b174-xxxxxxx

**Comment by kiwicopple** [comment]
> Rebuild app in vercel, update environmental variables

Hey @gpaw - Is the user's email corrupted?  I'm trying to figure out what could be changing here to cause this - is this app open source?

**Comment by denneralex** [comment]
hey there @kiwicopple! I've been getting this same message on a similar issue so I thought I'd comment here first before opening a new issue. It may also give some clue to help debugging and finding this. Here's my issue:

When I disable both signup and Email signup toggles on the Auth settings dashboard and then try to login using magic link with an existing user I get this same error message: "Unsupported email provider". But what's funny is that I was doing the same thing last week and it was working fine, I was able to login with an existing user and would get an error if I tried to login/signup a new user (which I think should be the expected behavior in this case?). So definitely something changed there in the last few days as I haven't changed anything on my app.

**Comment by gpaw** [comment]
@kiwicopple 
The user's email is not corrupted, everything was working a few days ago.
I am using Supabase web portal

I don't know if you have changed something or I did. But basically I had to delete my entire project (thankfully I haven't launch the app yet) and start over. I also clear all my environmental variables in vercel and started over.

So far it is working for me. Fingers crossed it stays this way!

**Comment by darora** [comment]
Hey @gpaw , @denneralex - looking through the gotrue code, the only reason this error message would be returned is if Email auth was _disabled_ in the config - it is completely non-dependent on the user's email address or any other request data. e.g. https://github.com/supabase/gotrue/blob/master/api/signup.go#L64-L66

Any chance you were playing with the auth settings at https://app.supabase.io/project/{ref}/auth/settings and accidentally disabled email logins?

@denneralex - if you email us at support@ with your project ref, I can look into this further for you.

**Comment by LyMc** [comment]
I had a similar issue with the google provider. Users have to login again after the token expires, as the refresh token call failed with 400 "Unsupported email provider". I played with auth settings, as @denneralex said, and found that the combo `Disable Signup: true` & `Enable Email Signup: false` is the cause of the issue.

All other combo is working:
`Disable Signup: false` & `Enable Email Signup: true`
`Disable Signup: true` & `Enable Email Signup: true`
`Disable Signup: false` & `Enable Email Signup: false`

**Comment by darora** [comment]
@LyMc that seems to be a different failure scenario; I've created https://github.com/supabase/gotrue/issues/193 to track that
