### ISSUE TITLE
count with rpc does not work as expected

### ISSUE THREAD

**Issue by e0** [supabase/supabase#2852]
# Bug report

## Describe the bug

In the [documentation](https://supabase.io/docs/postgrest/client/rpc#with-count-option), the following example does not work because it [sets the `params` object](https://github.com/supabase/postgrest-js/blob/master/src/lib/PostgrestRpcBuilder.ts#L19) instead.

```javascript
const { data, error, count } = await postgrest
  .rpc('hello_world', { count: 'exact' })
}
```

A workaround is to provide `undefined` as the second argument to `rpc`, for example: `.rpc('hello_world', undefined, { count: 'exact' })`. I'm not sure if this is the intended behavior though so I filed as a bug report instead of docs improvement.

## To Reproduce

You can add the following tests to `/test/basic.ts`. The 1st case fails and the 2nd one passes.

```javascript
test("stored procedure with count but no params (1): 'exact'", async () => {
  const res = await postgrest.rpc('void_func', { count: 'exact' })
  expect(res.count).toBe(1)
})

test("stored procedure with count but no params (2): 'exact'", async () => {
  const res = await postgrest.rpc('void_func', undefined, { count: 'exact' })
  expect(res.count).toBe(1)
})
```

## Expected behavior

According to the documentation, using `rpc('hello_world', { count: 'exact' })` should return an object with `count` in it. I'm not sure what the optimal solution to this problem would be since both the `params` and `{ count: '...' }` are optional.

## System information

- OS: macOS
- Version of supabase-js: 1.21.0
- Version of Node.js: v16.4.2

## Additional context

A related problem is: in `supabase/supabase.js`, when using `const supabase = createClient()`, the `{ count: 'exact' }` never works because it is [never passed to `postgrest-js`](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L99-L102). 

I think I should file this issue in `supabase/supabase.js` instead.

**Comment by e0** [comment]
> You're right, that particular example in the docs is not correct - you'd need to pass either `undefined` or, preferably, an empty object as the second parameter for `count` to work. This is intended behavior though, so I'll file this as a bug in the docs.

Thanks for clarifying. Personally I would prefer something like `rpc({ name: 'hello', params: 'world', headers: { count: 'exact' }})` for handling optional params. I understand if it's not desirable though since it would be inconsistent in style with the rest of the API.

**Comment by kiwicopple** [comment]
@soedirgo - I've add the fix to the docs, will let you approve/merge 🙏

**Comment by PatoDeVille** [comment]
I have a situation where in my rpc I pass something like
```
const {data, error, count} = await supabase.rpc('rpc name',{...Some parameters },{count: exact});

```
and I receive count NULL every time (i have 77 elements).. I dont know if its because i need to add the Count() function on my rpc or how to solve this.

**Comment by soedirgo** [comment]
@PatoDeVille can you file a new issue in the supabase/postgrest-js repo about this? Would be helpful if you can provide the function definition as well.
