### ISSUE TITLE
 "Operation is manually canceled" Error in Supabase

### ISSUE THREAD

**Issue by NuriaAgbasi** [supabase/supabase#28538]
I am unable to view my tables in Supabase. The interface remains stuck on the loading screen indefinitely without displaying the tables. Below is a screenshot of the error message I encountered in the console:
```

msg: "operation is manually canceled"
type: "cancelation"
__sentry_captured__: true
```
### Steps to Reproduce:

1. Attempt to view tables in Supabase.
2. Observe that the interface continues to load without displaying any tables.

### Expected Behavior:

The tables should load and be displayed within a reasonable time frame.

### Actual Behavior:

The loading spinner keeps running indefinitely, and the tables do not appear.

### Internet Connection Details:

Download Speed: 17.9 Mbps
Upload Speed: 16.7 Mbps
Latency: 5 ms
Server: Lagos
The speed test indicates that my internet connection is fast and should be able to handle multiple devices streaming HD videos simultaneously.

### Screenshots:
<img width="1280" alt="Screenshot 2024-08-11 at 21 39 13" src="https://github.com/user-attachments/assets/e44a8bae-337b-4061-84e1-d775e268fe1c">
<img width="1280" alt="Screenshot 2024-08-11 at 21 40 47" src="https://github.com/user-attachments/assets/43dcc522-6a62-4d78-8565-43210ffe6697">
<img width="1280" alt="Screenshot 2024-08-11 at 21 44 57" src="https://github.com/user-attachments/assets/f0212436-36b9-477f-9a6f-655fc0a91b6d">

**Comment by encima** [comment]
Hi there,
Thanks for opening. This seems like an issue related to your hosted project so could you open a support ticket at https://supabase.help
