### ISSUE TITLE
State Parameter for PKCE OAuth flow

### ISSUE THREAD

**Issue by Kysetopher** [supabase/supabase#28530]
### Discussed in https://github.com/orgs/supabase/discussions/28520

<div type='discussions-op-text'>

<sup>Originally posted by **Kysetopher** August  9, 2024</sup>
Hello I am using google sign in. I have successfully setup a PKCE workflow. This flow is working properly and the associated code is listed below. I have also added the state parameter to my initiation. 

It seems that I am being redirected to both supabase and my callback endpoint also included below. however the state parameter is only included in the redirect to supabase. 
Its possible that supabase is handling the state parameter. however I am not sure if I need to verify this on my end as well in the callback by reading the state parameter stored in my cookies. If I do need to verify this im not sure how to read the state parameter when its not being sent to my endpoint. 
login.js endpoint:
import { generatePkcePair } from '../../../utils/pkce';
import { setCookie } from 'nookies';
import { ServerClient } from '../../../utils/supabase/server';
import crypto from 'crypto';

export default async function handler(req, res) {
  try {
    const { codeVerifier, codeChallenge } = await generatePkcePair();

    const state = crypto.randomBytes(16).toString('hex'); 

    setCookie({ res }, 'xxxxxxx-auth-token-code-verifier', codeVerifier, {
      path: '/',
      maxAge: 60 * 10,
      secure: true,
      httpOnly: true,
    });

    setCookie({ res }, xxxxxxx-auth-state', state, {
      path: '/',
      maxAge: 60 * 10,
      secure: true,
      httpOnly: true,
    });

    const supabase = ServerClient(req, res);

    const redirectToUrl = process.env.NODE_ENV === 'production'
      ? 'https://www.l33tbox.ai/api/auth/callback'
      : 'http://localhost:3000/api/auth/callback';

      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo: redirectToUrl,
          scopes: 'email profile',
          codeChallenge,
          codeChallengeMethod: 'S256',
          state: JSON.stringify({ flow_state_id: state }), // Embed state in a JSON object
        },
      });
      
      
      

    if (error) {
      console.error('Supabase OAuth error:', error.message);
      return res.status(500).json({ error: error.message });
    }
    await new Promise(resolve => setTimeout(resolve, 1000));
    console.log('Redirecting to:', data.url);
    return res.redirect(302, data.url);
  } catch (error) {
    console.error('Error during OAuth login:', error.message);
    return res.status(500).json({ error: error.message });
  }
}

callback.js endpoint:
import { parseCookies, setCookie} from 'nookies';
import { ServerClient } from '../../../utils/supabase/server';

export default async function handler(req, res) {
  try {
    const { code } = req.query;
    const cookies = parseCookies({ req });
    const codeVerifier = cookies['xxxxxxxxxx-auth-token-code-verifier'];

    if (!code || !codeVerifier) {
      throw new Error('Code and code verifier must be non-empty');
    }

    const supabase = ServerClient(req, res);
    const { data, error } = await supabase.auth.exchangeCodeForSession(code, codeVerifier);

    if (error) {
      console.error('Error exchanging code for session:', error);
      throw error;
    }

    const { session } = data;
    if (!session || !session.access_token || !session.refresh_token) {
      throw new Error('Invalid session data');
    }

    setCookie({ res }, 'xxxxxxxx-auth-token', session.access_token, {
      path: '/',
      maxAge: 60 * 60 * 24 * 7, // 1 week
      secure: process.env.NODE_ENV === 'production', // Ensure secure flag is set in production
      httpOnly: true,
      sameSite: 'Strict',
    });

    setCookie({ res }, 'sb-refresh-token', session.refresh_token, {
      path: '/',
      maxAge: 60 * 60 * 24 * 7, // 1 week
      secure: process.env.NODE_ENV === 'production', // Ensure secure flag is set in production
      httpOnly: true,
      sameSite: 'Strict',
    });

    await new Promise(resolve => setTimeout(resolve, 1000));
    console.log('PKCE Oauth flow complete, cookies set, redirecting...');

    res.redirect('/');
  } catch (error) {
    console.error('Error during OAuth redirect handling:', error);
    res.status(500).send(`Error during OAuth redirect handling: ${error.message}`);
  }
}
here are my requests that appear in the broswer:

Request URL:
https://xxxxxxxxxx.supabase.co/auth/v1/callback?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjMyNDA2NDUsInNpdGVfdXJsIjoiaHR0cHM6Ly93d3cubDMzdGJveC5haSIsImlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiZnVuY3Rpb25faG9va3MiOm51bGwsInByb3ZpZGVyIjoiZ29vZ2xlIiwicmVmZXJyZXIiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvYXBpL2F1dGgvY2FsbGJhY2siLCJmbG93X3N0YXRlX2lkIjoiYzA5YTZmNWUtZDg1ZS00NjdjLWEzZjctOTc3MzFjZjdlNjU1In0.O86Q7-mkQ_33tjMxArUpOtWy8RHAich9tXm_o71P42w&code=4%2F0AcvDMrDnyQuV6OVtkrGcATftX5Lpb1R_WP8YFfifbzc1Ge9PvT2jSThf-52ATq9F9xQwAQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none

Request URL:
http://localhost:3000/api/auth/callback?code=ebfc2d2b-1318-472d-b4eb-691c3</div>

**Comment by encima** [comment]
Hello,
Please only an open either an Issue OR a Discussion. Opening both can increase efforts and uses time when trying to triage.
I will close this issue and people can continue in the discussion

**Comment by Kysetopher** [comment]
Hello i would like to understand why there is a create issue from disussion
button. If this is undesirable why is it there? Very confusing

**Comment by Kysetopher** [comment]
Hello Chris,
Like I said before I used the button in the discussion to create an issue.
This is because I actually really need help from your team to solve this
issue because I cannot find documetation that clearly answers my questions.
Can you confirm that your team is actively working on assisting me with the
discussion and that I do not need to create an issue. Additionally, if I am
not supposed to create an issue from a discussion why is this here? Thats
some very confusing customer support practices.

So that I can better work with your team could you please let me know: If i
want to have a community discussion to get help from users and get support
from your team, should I create an issue or a discussion and what is the
proper link to do that through? Also for your own sake please remove the
button. I'm sure this happens all the time?
[image: img.PNG]

**Comment by encima** [comment]
Hi @Kysetopher 
The button is there to create Issues from Discussions when there has been an issue identified.
For example, if I create a Discussion around something like: "Does Supabase support Authentication with X?" and the Discussions reveals that it does not, I would create an Issue for that support to be implemented.

Creating a Discussion and then immediately making an Issue simply creates duplicates and makes it hard for the team (and the community) to triage issues.

If there is a verifiable bug or unexpected behaviour: please open an Issue.
If you would like to ask about a feature, some behaviour or similar: please open a Discussion.
When you choose either of these options, templates are provided to help you format them.

I hope that clarifies it and a member of the team (or community) will respond in the Discussion

**Comment by Kysetopher** [comment]
Hello,
Thank you for your response. That is very clear i appreciate it
