### ISSUE TITLE
UPDATE RLS policy requires SELECT RLS policy too

### ISSUE THREAD

**Issue by abishekmuthian** [supabase/supabase#28559]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/database/postgres/row-level-security.mdx#update-policies

## Describe the problem

UPDATE RLS policy doesn't mention that  it also needs a SELECT POLICY even for update action from client without chaining select .

e.g. Following code from the client will work on the RLS enabled `profiles` table only when there are both UPDATE and SELECT POLICIES.

```
    await supabase
        .from('profiles')
        .update({'name': "test"}).eq('id', userId);
```

```
--RLS POLICY TO ALLOW THE USERS TO UPDATE THEIR ROWS
create policy "Users can update their own profile."
on profiles for update
to authenticated                    -- the Postgres Role (recommended)
using ( (select auth.uid()) = id )       -- checks if the existing row complies with the policy expression
with check ( (select auth.uid()) = id ); -- checks if the new row complies with the policy expression
```

```
--RLS POLICY TO ALLOW THE USERS TO SELECT THEIR ROWS
create policy "Users can select their own profile."
on profiles for select
to authenticated                    -- the Postgres Role (recommended)
using ( (select auth.uid()) = id )       -- checks if the existing row complies with the policy expression
```

Without the aforementioned SELECT policy, Update policy wouldn't work but the documentation seems to suggest that just the UPDATE policy is needed. Many supabase users have faced the [issue](https://community.weweb.io/t/supabase-does-not-update-despite-success/6286/18) of UPDATE not working after setting requisite RLS policy.

## Describe the improvement

Add a note and example  to the UPDATE policy for the relevant SELECT policy to go along with it.

## Additional context

Right now there is a separate SELECT policy example in the documentation but its not relevant to the UPDATE policy.

Add any other context or screenshots that help clarify your question.

**Comment by encima** [comment]
Thanks for opening @abishekmuthian 
PRs welcome for the docs!
