### ISSUE TITLE
Incorrect Enpoint in the JS Refences for getting users by ID it should have been /admin/users NOT /admin/user

### ISSUE THREAD

**Issue by Ramz001** [supabase/supabase#28580]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

An incorrect endpoint on the docs.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to References
2. See error on get user by id

## Expected behavior

Correct Endpoint

**Comment by encima** [comment]
Hi, thanks for opening. Please provide a link and/or a screenshot to the docs

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
