### ISSUE TITLE
The placeholder in "CHECK Constraint" input is not suggesting the correct example

### ISSUE THREAD

**Issue by sokhuong-uon** [supabase/supabase#28590]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I created a table with the `duration_min` field as `int4`.
This is what I see in the check constraint
![image](https://github.com/user-attachments/assets/05deb4ae-807e-4b2b-8cfe-b63baac7624b)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table which include a `duration_min` field. Set `duration_min` to `int4`.
2. Click save. So the table is created now.
3. Click to view the newly created table.
4. Click on the dropdown menu of the `duration_min` column
5. Click "Edit Column"
6. Scroll down and see
![image](https://github.com/user-attachments/assets/05deb4ae-807e-4b2b-8cfe-b63baac7624b)
7. Follow the suggestion will lead to error.

## Expected behavior

Show `e.g duration_min > 0` or something correct.

## System information

- OS: Ubuntu
- Browser Chrome

## Additional context

I use supabase.com in the browser.

**Comment by sokhuong-uon** [comment]
Clarification:

The type of the field is `int4`.
I want the placeholder to be something like:
- `duration_min > 0`
- `duration_min < 0`
- `duration_min < -100` (doesn't make sense but it's ok because we don't understand the semantic of the field name)

I think that checking the length of an integer doesn't seems right.
In fact, we will get a postgresql error if we follow the suggestion in placeholder.

**Comment by major-winter** [comment]
Hi @sokhuong-uon , this issue occurs with other types like `int2, int8,...` as well. Do I understand correctly that you want a dynamic placeholder that can adjust to match the selected data type?

**Comment by sokhuong-uon** [comment]
yes, you're right.

**Comment by major-winter** [comment]
Great, I'm working on it and will be creating a PR soon.

**Comment by praniket01** [comment]
Is anyone working on this currently ?

**Comment by major-winter** [comment]
> Is anyone working on this currently ?
> 
> 

There's an open PR for this issue. It's awaiting approval.
