### ISSUE TITLE
The delete + filter example does not work with VueJS + Vuetify + NuxtJS

### ISSUE THREAD

**Issue by oussamabonnor1** [supabase/supabase#286]
# Bug report

## Describe the bug

When trying to apply the following example:

`const { data, error } = await supabase.from('cities').delete().filter({'name', 'eq', 'Paris'})`

Found here [docs.](https://supabase.io/docs/client/filter#with-delete)

While checking out the node modules code for @supabase in posgtres-js/PostgresFilterBuilder, I found this function:

`filter(column, operator, value) {
        this.url.searchParams.append(`${column}`, `${operator}.${value}`);
        return this;
    }`

**Which does not support an object but rather 3 values.**

## Screenshots
![image](https://user-images.githubusercontent.com/17766221/99090497-0490f980-25cf-11eb-8cc5-0905c9944aa5.png)

If the filter could be updated to handle multiple operations inside an object, that would be nice!

**Comment by soedirgo** [comment]
Hey @oussamabonnor1, thanks for the report! You're right, these should've been `filter('name', 'eq', 'Paris')`, we'll update the docs soon.

You can chain the filter methods to do complex filters, like so:

```js
const { error, data } = await supabase
    .from('cities')
    .delete()
    .eq('name', 'Paris')
    .gt('id', 10)
    .is('exists', true)
```

**Comment by oussamabonnor1** [comment]
My case here is a bit special, I wanted to apply filters based on their existence or not (multiple filters that can be applied or not based on the user's wishes) which means I'll have multiple ".eq()" calls to handle (which is not very pretty).
I have found that the function ".match()" is exactly what I was looking for, thanks for the reply!

**Comment by kiwicopple** [comment]
Hey @oussamabonnor1 - docs are updated and it looks like you've found some success using the `match()` method so I'll close this one for now. Feel free to reopen if there's anything else!
