### ISSUE TITLE
Delete User Error If Bucket Contains Files Uploaded By User

### ISSUE THREAD

**Issue by mcewen87** [supabase/supabase#2860]
## Describe the bug

I'm trying to use the Supabase dashboard to delete a user, but I receive this error: 

Deleting user failed: update or delete on table "users" violates foreign key constraint "objects_owner_fkey" on table "objects"

No related tables exist. 

On a hunch, I deleted every file uploaded by the user from a storage bucket in Supabase, and that did the trick. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create a user and upload files to a bucket with that user, then attempt to delete the user. 

I have added two policies to "Policies under storage.buckets" section. 

1. allow public access to bucket
2. allow only auth user to upload 

## Expected behavior

I would expect that uploading images to a bucket doesn't create a fk constraint and I could delete a user without first having to delete their file uploads

**Comment by inian** [comment]
Duplicate https://github.com/supabase/storage-api/issues/65
