### ISSUE TITLE
OAuth Error: Chrome may soon delete state for intermediate websites in a recent navigation chain

### ISSUE THREAD

**Issue by CBell045** [supabase/supabase#28617]
# OAuth Error with Chrome

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using Supabase OAuth, Chrome deletes session, preventing login. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Followed OAuth directions from here: https://supabase.com/docs/reference/javascript/auth-signinwithoauth
2. Followed React Context to manage Session state from here: https://supabase.com/docs/reference/javascript/auth-onauthstatechange

## Expected behavior

On Safari and Firefox, OAuth works as expected (tested with Google and Azure OAuth).  

## Screenshots

<img width="629" alt="Screenshot 2024-08-13 at 9 01 33 PM" src="https://github.com/user-attachments/assets/4d0b3f45-266e-44c8-869c-a11ae95d92de">

## System information

- OS: macOS
- Browser: Chrome (Version 127.0.6533.120 (Official Build) (arm64))
- Version of supabase-js: 2.45.1

## Additional context

Thanks for any help on this!

**Comment by CBell045** [comment]
I was able to fix the issue by setting a loading flag in my context provider! Thanks.

**Comment by neuberfran** [comment]
@CBell045 Pls I have this issue here in this project https://medium.com/google-developers/smart-home-cloud-services-with-google-part-2-3901ab39c39c (when I try to remake it using current technologies). Pls. Tell-me more about this: I was able to fix the issue by setting a loading flag in my context provider!

**Comment by CBell045** [comment]
Here's a random example I found: https://github.com/onmyway133/blog/issues/942#:~:text=const%20%5Bloading%2C%20setLoading%5D%20%3D%20useState%3Cboolean%3E(true)

**Comment by neuberfran** [comment]
@CBell045 Thank you but. Excuse me for insisting because in the solution you mentioned you mentioned a flag. On the site you mentioned I didn't see anything about SameSite=none and Secure=true and (but this is not entirely the case) but my problem is using Angular
