### ISSUE TITLE
Auth issue on self-hosted Supabase [401 JWSError JWSInvalidSignature]

### ISSUE THREAD

**Issue by hrynkodev** [supabase/supabase#28611]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

I'm trying to run edge-functions on self-hosted Supabase, but every time I perform a query to database, I'm getting an 401 status code with following error:

```
[Error] {
  code: "PGRST301",
  details: null,
  hint: null,
  message: "JWSError JWSInvalidSignature"
} 
```

## To Reproduce

I'm using following code to fetch data from db, according to the docs.

```
const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
)

const getUserByEmail = async (email: string) => {
    const {data: [userId], error} = await supabase
        .rpc('get_user_id_by_email', {'email_str': email})

    if (error) {
        throw new Error(error.message)
    }

    return userId
}
```

## Expected behavior

Data is avalibale to fetch via supabase client in edge runtime hosted by docker compose. 

## System information

- OS: Ubuntu 20.04
- Edge Runtime
- Version of supabase-edge-runtime image : v1.56.0

## Additional context

I have to mention, that when I'm running supabase services via CLI, everything works smooth, but If I start these services via docker compose I'm getting above error. Also, I've noticed that If I start supabase via docker and calling same kong endpoint from Postman with `apikey` header and no auth headers, I also getting correct result without errors, I've tried to reproduce this in supabase client via adding this header and suppressing auth settings, but result was still same.

**Comment by hrynkodev** [comment]
I've also referred to [this](https://github.com/supabase/supabase/issues/17164) issue, tried with 128 chars length secret key, but result is still the same

**Comment by null1s** [comment]
+1, I have the same error when I try to make a db query to check if username already exists in my database.

**Comment by null1s** [comment]
UPDATE! Making such script for myself worked out and its working now. [Solution](https://github.com/supabase/supabase/issues/17164#issuecomment-2280835849)

**Comment by encima** [comment]
To confirm:
- This does not occur with Supabase CLI (local dev)?
- This does occur when using docker-compose (self-hosting)?

If yes, you should see logs for the edge runtime and for the postgres instance. Do they log any errors? Equally, are there any networking or connectivity issues?

**Comment by null1s** [comment]
Hey, @encima, sorry for late response.
I hadn't tested local dev at all so can't give more information on that. The problem was occurring on self-hosted docker container. I have no idea how or why, but generating those new keys **not from supabase "settings"** solved the issue for me. I tried generating countless times with Supabase's tool with no luck.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
