### ISSUE TITLE
Support for JSON view an alternative to Table view

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2863]
I think it is also a good idea to have a JSON view as table can get quickly pretty large. The problem is you cant view or its hard to view the whole table schema and data because it cant just fit to the screen.

Some examples are:

![image](https://user-images.githubusercontent.com/86398599/129675348-3b315123-98f7-4d87-bec6-12f04ac37d11.png)
![image](https://user-images.githubusercontent.com/86398599/129675341-48c7e8c9-0217-4b6b-ab37-004c91e84a8c.png)

**Comment by MildTomato** [comment]
Hey @sandbox-apps - there's already a rudimentary JSON viewer that is sort of hidden away in the row edit side panel in the table editor page.

If you edit a row, and then click 'View data' you should be able to see something like the below.

<img width="879" alt="Screenshot 2021-08-17 at 15 59 45" src="https://user-images.githubusercontent.com/8291514/129687536-e43516d9-12d7-44ac-8ba5-ff9956591bcb.png">

There's obviously a lot of improvements we can make here but is there anything in particular anyone would like to see support for.

**Comment by sandbox-apps** [comment]
Oh wow! Nice! Honestly this will work for me.

But in addition maybe we can get a literal json? with those curly braces that we can copy/paste then syntax highlight for key/value per data type

Should i close this? and create new issue for the mentioned additional?

**Comment by kiwicopple** [comment]
Hey @sandbox-apps - if you click the "edit" toggle at the top it will change to a raw JSON doc, so you should be able to copy that.

I'll close this one for now but if that isn't exactly what you wanted then just comment again and we can reopen :)
