### ISSUE TITLE
Special Characters in Database Password Cause Connection Error in Rails Setup 

### ISSUE THREAD

**Issue by PankajNk** [supabase/supabase#28648]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/quickstarts/ruby-on-rails

## Describe the problem
When following the Ruby on Rails quick start guide, users may encounter an issue where using special characters in the database password results in the following error:
`ActiveRecord::ConnectionNotEstablished: could not translate host name "12345aws-0-ap-south-1.pooler.supabase.com" to address: Name or service not known
`
This error occurs because the numeric portion of the password (e.g., 12345 in rails@12345$) gets mistakenly attached to the service hostname, leading to a DNS resolution failure. This prevents the Rails application from connecting to the database.

## Describe the improvement

Add a note in the documentation advising users to avoid using special characters in the database password during setup. This will help prevent the connection error and ensure a smoother setup process for users.

**Comment by encima** [comment]
Hi there,

thanks for opening. This is included in the docs [here](https://supabase.com/docs/guides/database/postgres/roles#special-symbols-in-passwords).

If you would like to include it elsewhere, please do open a PR and link to that section 🙏

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
