### ISSUE TITLE
 Special Characters in Database Password Cause ActiveRecord::ConnectionNotEstablished Error in Rails Setup

### ISSUE THREAD

**Issue by PankajNk** [supabase/supabase#28646]
# Bug report

I encountered an issue while following the quick guide to set up Supabase in a Rails application. The error message I received was:
`ActiveRecord::ConnectionNotEstablished: could not translate host name "12345aws-0-ap-south-1.pooler.supabase.com" to address: Name or service not known
`

### Steps to Reproduce:

1. Follow the Supabase setup guide for a [Rails application](https://supabase.com/docs/guides/getting-started/quickstarts/ruby-on-rails).
2. Create a database with a password that includes special characters, e.g., rails@12345$.
3. Attempt to connect to the database using the provided configuration.

###  Observed Behavior:
The application fails to establish a connection to the database, resulting in the above error.

###  Root Cause:
It appears that when the password contains special characters, the numeric portion (12345) gets incorrectly interpreted and attached to the service hostname, leading to DNS resolution failure.

###  Solution:
Avoid using special characters in the database password to prevent this issue. A password without special characters works as expected, and the connection is successfully established.

**Comment by encima** [comment]
Solution can be to avoid using special chars or you can encode the connection string, see [docs](https://supabase.com/docs/guides/database/postgres/roles#special-symbols-in-passwords)

I will close this but feel free to open a PR in case you want to link to it elsewhere
