### ISSUE TITLE
supabase/studio: Failed to generate title and Failed to delete queries in SQL Editor

### ISSUE THREAD

**Issue by alialnaghmoush** [supabase/supabase#28661]
# Bug report

Failed to generate title in SQL Editor and
Failed to delete queries: API error happened while trying to communicate with the server.

<img width="1792" alt="Screenshot 2024-08-15 at 11 55 20 AM" src="https://github.com/user-attachments/assets/a9ac6d3b-3f2c-45e2-9abe-a9b7a69c75b5">
<img width="1792" alt="Screenshot 2024-08-15 at 11 54 36 AM" src="https://github.com/user-attachments/assets/202da8eb-eb1a-413e-815b-56b84fd079aa">
---
<img width="1762" alt="Screenshot 2024-08-15 at 12 01 34 PM" src="https://github.com/user-attachments/assets/07150c44-a181-4073-b0a4-167e07ef393a">
---
Logs for unhealthy
<img width="1769" alt="Screenshot 2024-08-15 at 12 03 07 PM" src="https://github.com/user-attachments/assets/d8c29921-5f6a-4031-b1f8-52a4becd3a66">

**Comment by alialnaghmoush** [comment]
I add OPENAI_API_KEY to studio in docker-compose.yml, but also Failed to generate title

<img width="1792" alt="Screenshot 2024-08-15 at 12 09 29 PM" src="https://github.com/user-attachments/assets/913300a5-dce8-4fec-8093-4205cc5502f7">

**Comment by alialnaghmoush** [comment]
I add 5$ to my openai account After seeing studio logs -> it now generated the title

- Create Secret Key from openai account
- Add OPENAI_API_KEY to studio in docker-compose.yml and Secret Key to .env
- Add some money to your openai account
- And it is work
---
<img width="1768" alt="Screenshot 2024-08-15 at 12 31 45 PM" src="https://github.com/user-attachments/assets/01df276c-069b-4b34-aa7f-1c0b73a64576">
---
<img width="1792" alt="Screenshot 2024-08-15 at 12 34 55 PM" src="https://github.com/user-attachments/assets/a51440a7-f1e8-46c6-9bfb-37e9e166c5dd">

**Comment by alialnaghmoush** [comment]
New problem when refreshed the page my queries It does not appear, but when called upon when adding new data, it works
How do we solve the problem of queries not appearing in SQL Editor?

when create the querie
<img width="1792" alt="Screenshot 2024-08-15 at 12 34 55 PM" src="https://github.com/user-attachments/assets/3379a14a-9633-4ce4-ae59-892e9e5d3bd8">

after refresh the page
<img width="1792" alt="Screenshot 2024-08-15 at 12 43 29 PM" src="https://github.com/user-attachments/assets/90852ca1-3335-4236-bd91-f22ef031b3e4">

**Comment by encima** [comment]
Hi there, 
thanks for opening, this is because local queries are not saved in the self-hosted version. 

We will link this to the issue #17941 and close this one. Please continue the discussions in that one as we work on it.
