### ISSUE TITLE
Supabase Reports: not showing data for some days

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2867]
1. Login to supabase dashboard
2. Hover over the dashboard reports like database/auth/storage
3. Notice some has value but no colored bar appear
4. Hover another request bar, notice some value are 0 other bar dont show any value at all

**Comment by w3b6x9** [comment]
@sandbox-apps can please check again? I believe we have fixed this issue so I'm going to close. If you're still missing data please reopen.
