### ISSUE TITLE
The cursor jumping  to the end of the sentence after the first backspace press in the search input field of supabase docs

### ISSUE THREAD

**Issue by sanjeevmurmu** [supabase/supabase#28685]
# Improve documentation

## Link 
https://supabase.com/docs

## Describe the problem

When editing text on the search input field of the supabase docs, the backspace key shows unexpectedly behavoiour. Specifically:

When I am trying to search for a long word or a sentence in the supabase docs but then I see I have made a spelling error I will move the cursor to the part of the query where i want to rectify it then the following things happen.

Initial Backspace Press: When I press backspace for the first time, it correctly deletes the character to the left of the cursor.

Cursor Movement:  But immediately after the first deletion, the cursor jumps to the end of the sentence.

Subsequent Backspace Presses: Any further presses of the backspace key delete characters from the end of the sentence instead of the cursor’s original position when i first started changing my input.

## Describe the improvement

The cursor should remain in its original position after the first backspace press, allowing for continuous deletion from the middle of the sentence.

## Additional context
Steps to Reproduce:

Type a sentence in the search input field.
Place the cursor in the middle of the sentence.
Press the backspace key once (observe the character deletion and cursor movement).
Press the backspace key again (the deletion happens from the end of the sentence).

**Comment by encima** [comment]
Thanks for opening and thanks for opening a PR to address this!
