### ISSUE TITLE
Slack Clone example broken

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#287]
on login or signup there is an error `TypeError: l.body is undefined`

it may be using the latest supabase-js (1.0.x) but according to package.json it shouldn't be (^0.35.x)

**Comment by awalias** [comment]
we should probably just bump to the latest supabase-js

**Comment by duncanhealy** [comment]
Note to self - check recent prs before coding - 

![image](https://user-images.githubusercontent.com/2788605/99191920-d135a280-2767-11eb-911e-b17738a919b3.png)
also 
```next dev``` was not working for me for some reason

**Comment by kiwicopple** [comment]
This repo was actually created before we had Auth, which is why there is a weird "setContext" to handle auth. I'll update it now

**Comment by kiwicopple** [comment]
I've reverted all the changes and put the supabase-js library back to `0.36`. I think it will be easier to start from scratch using the todo list as an example.
