### ISSUE TITLE
Function hook throws an error about bytea

### ISSUE THREAD

**Issue by imagitama** [supabase/supabase#2871]
# Bug report

## Describe the bug

When I UPDATE my Postgres table that has a function hook that does a POST I get this SQL error:

```
ERROR:  invalid input syntax for type bytea
CONTEXT:  SQL statement "insert into net.http_request_queue(method, url, headers, body, timeout_milliseconds)
    values (
        'POST',
        net._encode_url_with_params_array(url, params_array),
        headers,
        body::text::bytea,
        timeout_milliseconds
    )
    returning id"
PL/pgSQL function net.http_post(text,jsonb,jsonb,jsonb,integer) line 42 at SQL statement
```

## To Reproduce

1. Go to Supabase console
2. Go to Database page
3. Go to Function Hooks
4. Create a new hook:

- enter a name
- enter a table (using a pretty standard table with no species policies/roles)
- event is Update
- HTTP request
- method POST
- URL is to my own webserver (something like http://128.1.1.1:5000/my-endpoint)
- HTTP headers I added my own: "x-custom-api-key: abc"
- HTTP params none

5. Click Confirm
6. Update a record in the table and get that error

## Expected behavior

The trigger sends a POST to my endpoint instead of throwing an error

## Screenshots

N/A

## System information

N/A

**Comment by darora** [comment]
Thanks for the report @imagitama - this issue has been fixed in https://github.com/supabase/pg_net/pull/38 but hasn't been rolled out yet.
For an immediate fix, you can execute the relevant SQL from that repo on your project to replace the `net.http_post` function with the fixed code.

**Comment by imagitama** [comment]
I can't seem to do that as I am not the owner of the function

![image](https://user-images.githubusercontent.com/1967342/129698883-7b860b67-1917-4aca-b30a-e24665db22e7.png)

**Comment by imagitama** [comment]
Hi is there an update for this? I created a new Supabase project and it was sending requests perfectly fine but suddenly I am getting the error again:

```
UPDATE mytable SET somecol = 'Foo' WHERE id = '03EJGpvtJS1bZoqlNEVg';
```

```
ERROR:  invalid input syntax for type bytea
CONTEXT:  SQL statement "insert into net.http_request_queue(method, url, headers, body, timeout_milliseconds)
    values (
        'POST',
        net._encode_url_with_params_array(url, params_array),
        headers,
        body::text::bytea,
        timeout_milliseconds
    )
    returning id"
PL/pgSQL function http_post(text,jsonb,jsonb,jsonb,integer) line 42 at SQL statement
SQL statement "SELECT http_post                 FROM net.http_post(
              url,
              payload,
              params,
              headers,
              timeout_ms
            )"
PL/pgSQL function http_request() line 54 at SQL statement */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 0 of 2 queries: 0.000 sec. */
```
