### ISSUE TITLE
Manually created Postgres role not able to connect to DB after project is paused and restored

### ISSUE THREAD

**Issue by laurihy** [supabase/supabase#28731]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Manually created Postgres role/user can't connect to the database *after the project has been paused and restored*. When connecting, I get `SSL connection has been closed unexpectedly` error.

```
psql -h aws-0-eu-central-1.pooler.supabase.com -p 6543 -d postgres -U test_user.<project_id>
psql: error: connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.145.223), port 6543 failed: SSL connection has been closed unexpectedly
```

In the Pooler logs (in the project Dashboard) I see an error:

```
{
  "event_message": "ClientHandler: Exchange error: \"Unexpected message in receive_next/2 {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.209954395>, :tls_connection, [session_id_tracker: #PID<0.3577.0>]}, [#PID<0.7197.1014>, #PID<0.31304.2646>]}}\" when method :auth_query",
  "id": "3e070ff3-7b70-4560-8502-49bb57e88167",
  "metadata": [
    {
      "ansi_color": null,
      "callers": [],
      "context": [
        {
          "application": "supavisor",
          "domain": [
            "elixir"
          ],
          "file": "lib/supavisor/client_handler.ex",
          "function": "handle_event/4",
          "gl": "<0.2724.0>",
          "line": 273,
          "mfa": [
            "Elixir.Supavisor.ClientHandler",
            "handle_event",
            "4"
          ],
          "module": "Elixir.Supavisor.ClientHandler",
          "pid": "<0.30131.2023>",
          "registered_name": null,
          "time": 1724049350799111,
          "vm": [
            {
              "node": "supavisor@ip-10-105-36-180.eu-central-1.compute.internal"
            }
          ]
        }
      ],
      "db_name": "postgres",
      "depth": null,
      "error_logger": [],
      "formatter_error_params": [],
      "instance_id": "i-0b01ab30402d15015",
      "internal_log_event": null,
      "level": "error",
      "mode": "transaction",
      "project": "<project_id>",
      "region": "eu-central-1",
      "request_id": null,
      "stacktrace": [],
      "type": "single",
      "user": "postgres"
    }
  ],
  "timestamp": 1724049350799000
}
```

Before pausing, the user was able to connect perfectly fine. Also _after_ pausing and restoring, the default `postgres` user can still connect. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Manually create a new Postgres user in https://supabase.com/dashboard/project/_/database/roles
2. Verify you can connect to the database with that user (e.g. `psql -h aws-0-eu-central-1.pooler.supabase.com -p 6543 -d postgres -U test_user.<project_id>`
3. Pause the project in https://supabase.com/dashboard/project/_/settings/general
4. Restore the project
5. Try to connect with that user to the database, `psql -h aws-0-eu-central-1.pooler.supabase.com -p 6543 -d postgres -U test_user.<project_id>`
6. You get an error `psql: error: connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.145.223), port 6543 failed: SSL connection has been closed unexpectedly`

## Expected behavior

Even after pausing and restoring, it should be possible to connect to the database as that user.

## Screenshots

Not applicable.

## System information

- `psql` version `14.12`

**Comment by encima** [comment]
Hey there,

thanks for opening. Can you confirm the user still exists upon restore? You can do this by connecting with `psql` and running `\du`
It is possible that the database was paused and restored from a backup before that user existed.

**Comment by laurihy** [comment]
Thanks for the quick follow up!

I can confirm that the user itself still exists in the database. `\du` shows it correctly, it's visible in the dashboard, and I believe if the user itself wouldn't exist, the error message would be different.

**Comment by encima** [comment]
If the user exists, can you connect directly to the instance and not the pooler (to rule out any issue there)

**Comment by laurihy** [comment]
I tried connecting directly to the instance, and this time it was the password authentication that failed.

```
psql -h db.yfvxcipsikdlkfeeupnr.supabase.co -p 5432 -d postgres -U test_user
Password for user test_user: 
psql: error: connection to server at "db.<project_id>.supabase.co" (2a05:d014:1c06:5f0e:92a7:fd41:aed4:b552), port 5432 failed: FATAL:  password authentication failed for user "test_user"
connection to server at "db.<project_id>.supabase.co" (2a05:d014:1c06:5f0e:92a7:fd41:aed4:b552), port 5432 failed: FATAL:  password authentication failed for user "test_user"
```

I triple checked, and I did not mistype the password. 

I also discovered, that logging in as the `postgres` user and running `ALTER USER test_user WITH PASSWORD <new_password>;` seems to also fix both connecting directly as well as via the pooler. I also tried after that again pausing and restoring the project, which also restores the problem.

**Comment by encima** [comment]
To confirm:
The password is the issue? 

If you:
- Create a new user 
- pause the project 
- restore
- attempt to login with credentials for the new user?

Do you consistently experience this issue?

**Comment by laurihy** [comment]
It does indeed seem like the issue is with the passwords. 

> If you:
> - Create a new user
> - pause the project
> - restore
> - attempt to login with credentials for the new user?
> Do you consistently experience this issue?

Yep, this happens consistently.

**After a bit more digging, it seems like pausing and restoring the project empties (?) the password for those roles.** After (but not before) pause and restore, `select rolpassword from pg_authid where rolname = 'test_user'` (and similar from `pg_shadow`) returns an empty column. 

So for whatever reason, pausing and restoring a project empties the password for those manually created roles / users?

**Comment by encima** [comment]
Hi @laurihy 
Thanks for reporting and clarifying. I can reproduce this using the steps outlined and have informed the Infra and Postgres teams.
Will report back when there is an update!

**Comment by encima** [comment]
Hi @laurihy 
Spoke with the Infra team and this is actually expected behaviour that is [documented](https://supabase.com/docs/guides/platform/backups#daily-backups) (which was also news to me!). 
I have opened a [PR](https://github.com/supabase/supabase/pull/28760) to link to the docs in all relevant places and we can close this when it is merged.
However, if you think the behaviour should be different, please do comment and we can measure interest in changing the behaviour

**Comment by laurihy** [comment]
Hi @encima,

Thanks, much appreciated! Now that I read that part of the documentation, I guess the behavior (at least sort of) does make sense. The updated docs in the Roles-section in the PR definitely would've helped me, so looking good!

I think part of my confusion was due to the fact, that I hadn't considered that behind-the-scenes, pausing and restoring a project involves the database backup. I had assumed that it's just "some kind of hibernation state", and maybe (but just maybe) if in the UI there would've been mentions of backups etc, it would've been easier to reason about the password behavior. Or furthermore, I guess the UI could have a warning about passwords in case there are custom roles?

By the way, are there other operations that behind the scenes trigger a recovery from the backup, and thus lose the passwords?

**Comment by encima** [comment]
Hi @laurihy 
Thanks for the feedback, all of the points mentioned are good ones. Custom checks on databases are non trivial (warning if there are custom roles) but we certainly could make this information more front and centre.

The PR mostly links docs pages to other relevant docs pages but we could link [this](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#pause--restore) in the dashboard in the `restore` dialog. What do you think?

Aside from initiating a PITR restore, there are not other operations that I am aware of, no.

**Comment by laurihy** [comment]
Thanks, much appreciated! 

> The PR mostly links docs pages to other relevant docs pages but we could link [this](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#pause--restore) in the dashboard in the restore dialog. What do you think?

No strong opinions on this one. I think the updates to the documentation in the linked PR probably already clarify the behavior well enough.

**Comment by ndamulelonemakh** [comment]
For any else experiencing this, according to the [docs](https://supabase.com/docs/guides/platform/backups#daily-backups), you will need to update the password of your role again after you restore a paused project. For example:

`ALTER ROLE my_user WITH PASSWORD 'strongPass';`
