### ISSUE TITLE
Some versions of docs are being indexed by browsers

### ISSUE THREAD

**Issue by pablodz** [supabase/supabase#28753]
# Improve documentation

![image](https://github.com/user-attachments/assets/fa38b40b-c009-46b1-88c6-f8c434dafc48)

https://docs-rog1zs1kv-supabase.vercel.app/docs/guides/getting-started/tutorials/with-vue-3

docs page

## Describe the problem

Some deploys with temporal subdomains are being indexed by browsers that can lead to old docs

## Describe the improvement

Avoid temporal subdomains being indexed by robots or somthing like that

**Comment by encima** [comment]
Thanks for opening, this is not ideal and should be managed by Vercel. We can [modify the docs site](https://vercel.com/guides/are-vercel-preview-deployment-indexed-by-search-engines) to handle this but I think it should be done by default.
