### ISSUE TITLE
Layout Issue: Show More Tweets Button Misaligns Tweets on Firefox

### ISSUE THREAD

**Issue by Sama-004** [supabase/supabase#28772]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When viewing the `Join Community` section on the [Supabase](https://supabase.com/) website in Firefox, the tweets displayed properly in rows and columns before clicking `Show More`. However, after clicking the `Show More` button, the layout breaks, and all the newly loaded are stacked in a single column on the right side of the page. This behavior does not occur in Chrome, where the tweets remain correctly aligned in rows and columns even after clicking `Show More`.

## To Reproduce

1. Go to 'https://supabase.com/' in Firefox.
2. Scroll down to the "Join Community" section.
3. Click on 'Show More' under the `Join Community` section.
4. Observe the layout of the tweets.
5. Try the same on chrome and it works fine 

## Expected behavior
The tweets should continue to be displayed in rows and columns, as they do on Chrome, even after clicking `Show More`.

## Screen Recording for firefox
https://github.com/user-attachments/assets/52d8eb85-6194-4ef6-8aa1-a42aed1fe276

### This is how it should work on firefox too

https://github.com/user-attachments/assets/0c1b6909-ca7c-4168-a85d-c3b4f99d3896

## Screen Recording for firefox-developer-edition

https://github.com/user-attachments/assets/58c1851c-0402-4519-9734-fc4a6fad37d7

## System information

- OS: Arch Linux
- Firefox Browser 129.0 (64-bit)
- Chromium Version 127.0.6533.99 (Official Build)
- Firefox Developer edition 130.0b3 (64-bit)

**Comment by FatumaA** [comment]
Hi,
This works fine on my end, could you confirm this?


Uploading supa testimonial.mp4…

**Comment by FatumaA** [comment]
Hi,
This works fine on my end, could you confirm this?


https://github.com/user-attachments/assets/b5286485-1a51-47a2-bbba-8e9a240e3949

**Comment by Sama-004** [comment]
> Hi, This works fine on my end, could you confirm this?
> supa-testimonial.mp4

maybe this is a version specific issue

**Comment by FatumaA** [comment]
I'm on this version: 129.0.2

**Comment by fsansalvadore** [comment]
The layout has changed and this issue is no longer relevant, thanks anyway!
