### ISSUE TITLE
Unable to run `supabase start` locally, ulimit error

### ISSUE THREAD

**Issue by rznsid** [supabase/supabase#28775]
# Bug report

- [ x I confirm this is a bug with Supabase, not with my own application. 
- [ x  I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running `supabase start` locally, the containers stop.  Using `--debug` show the following:
```
+ ulimit -n
+ '[' '!' -z 10000 ']'
+ echo 'Setting RLIMIT_NOFILE to 10000'
+ ulimit -Sn 10000
/app/run.sh: line 8: ulimit: open files: cannot modify limit: Invalid argument
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `pnpx supabase init`, accepting default values.
2. Run `pnpx supabase start`.

## Expected behavior

Supabase starts locally.

## System information

- OS: Linux Fedora 39
- Browser (if applies) [e.g. chrome, safari]: NA
- Version of supabase-js: 1.190.0
- Version of Node.js: 20.16.0

## Additional context

Problem also visible if using `npm`/`npx`.

**Comment by Mohammed-Yasin-Mulla** [comment]
@rznsid ,
was your docker desktop running locally when you executed the command?

**Comment by encima** [comment]
This is a linux issue and can be resolved by increasing the ulimit (`limit -n 4096` or similar). Will close this one as it is not an issue with Supabase or the CLI

**Comment by TheEgghead27** [comment]
For future users with this issue (despite having sufficiently high host ulimits), one potential solution is to manually set a higher (hard) nofile limit using [the ulimits option under a service](https://docs.docker.com/reference/compose-file/services/#ulimits).
