### ISSUE TITLE
Contradictory instructions for creating SSR client in SvelteKit

### ISSUE THREAD

**Issue by jesse-a-reilly** [supabase/supabase#28803]
# Improve documentation

## Link

[https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=environment&environment=layout-server&queryGroups=framework&framework=sveltekit](https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=environment&environment=layout-server&queryGroups=framework&framework=sveltekit)

[https://supabase.com/docs/guides/auth/server-side/sveltekit](https://supabase.com/docs/guides/auth/server-side/sveltekit)

## Describe the problem

The code snippet for adding auth to Sveltekit's +layout.server.ts file differs between the `SSR/Sveltekit` guide, and the `SSR/Creating a Client` guide.

**SSR/Sveltekit**
```
import type { LayoutServerLoad } from './$types'

export const load: LayoutServerLoad = async ({ locals: { session }, cookies }) => {
  return {
    session,
    cookies: cookies.getAll(),
  }
}
```
**SSR/Creating a Client**
```
import type { LayoutServerLoad } from './$types'

export const load: LayoutServerLoad = async ({ locals: { safeGetSession }, cookies }) => {
  const { session, user } = await safeGetSession()

  return {
    session,
    user,
    cookies: cookies.getAll(),
  }
}
```

The former gets the `session` object from Locals , while the latter gets the `safeGetSession()` function, and uses the function to return the session.

## Describe the improvement

Pick one convention, and use it in both sets of documentation.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by 0xsonu** [comment]
I want to work on it.
