### ISSUE TITLE
API closes socket with error `worker_connections are not enough, reusing connections` when lots of concurrent requests are made

### ISSUE THREAD

**Issue by davidfant** [supabase/supabase#28804]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When doing lots of concurrent requests in local development, the Supabase API closes the socket. This is what I'm seeing in the logs using the supabase-js SDK (e.g. `await supabase.rpc("myFunction")`:
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at runTransitionTrigger (/Users/fant/repos/ai/petridish/supabase/dist/run/runTransitionTrigger.js:217:9) {
  cause: SocketError: other side closed
      at Socket.<anonymous> (/Users/fant/repos/ai/petridish-examples/petridish-github-stargazer-researcher/node_modules/undici/lib/dispatcher/client-h1.js:681:24)
      at Socket.emit (node:events:527:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '::1',
      localPort: 56143,
      remoteAddress: '::1',
      remotePort: 54321,
      remoteFamily: 'IPv6',
      timeout: undefined,
      bytesWritten: 1043,
      bytesRead: 0
    }
  }
}
```

In the Supabase Kong Docker container logs I'm seeing the following when running `docker logs --tail 3000 supabase_kong_supabase | grep warn`:
```
2024/08/22 01:46:27 [warn] 1112#0: *103034 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000791, client: 172.18.0.1, server: kong, request: "POST /rest/v1/token?columns=%22id%22%2C%22placeId%22%2C%22versionId%22%2C%22data%22%2C%22json%22%2C%22silent%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:27 [warn] 1112#0: *103034 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000792, client: 172.18.0.1, server: kong, request: "POST /rest/v1/token?columns=%22id%22%2C%22placeId%22%2C%22versionId%22%2C%22data%22%2C%22json%22%2C%22silent%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:27 [warn] 1112#0: *103034 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000793, client: 172.18.0.1, server: kong, request: "POST /rest/v1/token?columns=%22id%22%2C%22placeId%22%2C%22versionId%22%2C%22data%22%2C%22json%22%2C%22silent%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:27 [warn] 1112#0: *103035 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000794, client: 172.18.0.1, server: kong, request: "POST /rest/v1/token?columns=%22id%22%2C%22placeId%22%2C%22versionId%22%2C%22data%22%2C%22json%22%2C%22silent%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:28 [warn] 1112#0: *103035 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000795, client: 172.18.0.1, server: kong, request: "POST /rest/v1/token?columns=%22id%22%2C%22placeId%22%2C%22versionId%22%2C%22data%22%2C%22json%22%2C%22silent%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:28 [warn] 1112#0: *103034 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000796, client: 172.18.0.1, server: kong, request: "POST /rest/v1/triggerToken?columns=%22triggerId%22%2C%22tokenId%22%2C%22arcId%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:35 [warn] 1112#0: *103390 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000797, client: 172.18.0.1, server: kong, request: "POST /rest/v1/triggerToken?columns=%22triggerId%22%2C%22tokenId%22%2C%22arcId%22 HTTP/1.1", host: "localhost:54321"
2024/08/22 01:46:35 [warn] 1112#0: 512 worker_connections are not enough, reusing connections
```

Note that `worker_connections are not enough, reusing connections` seems to show a few seconds before the supabase-js SDK errors appear.

## To Reproduce

1. Have some table with 100s of rows
2. Run the below code to run lots of concurrent reqs
```ts
    await Promise.all(
      Array.from({ length: 1000 }).map(() =>
        supabase.from("trigger").select("id").throwOnError()
      )
    );
```

When I run this with e.g. limit 200 everything is fine and I don't see the Kong `worker_connections are not enough, reusing connections` error, but once I hit the error that error shows, so I'm pretty sure the problem is related to `worker_connections`

For me the issue happens when limit is around 230-250

## Expected behavior

No socket hangup

## System information

- OS: macOS
- Browser: N/A
- Version of supabase-js: 2.43.4
- Version of Node.js: 21.1.0

## Additional context

Is there a way to play around with the Kong Nginx config? For example I'd want to try increasing `worker_connections` and/or keepalive config

**Comment by encima** [comment]
Hi there, 

Thanks for opening. These values are set but certainly editable within the files. Doing that is unsupported, however, though you are welcome to do this yourself!

In hosted environments, these values will vary based on the resources of your instance. 

Note that if you increase this value in Kong, you may still hit connection count limits or worker process limits within Postgres so it may need quite a bit of tweaking.

I will close this as it is not something we want to support directly (as far as I am aware) but please do ask in Discord and see what others may be doing here!

**Comment by davidfant** [comment]
@encima got it - thx! Could you give me any pointers to where and how I'd configure Kong when running locally?

**Comment by encima** [comment]
@davidfant nothing beyond the docs for their container and services but I am sure you have checked those?
