### ISSUE TITLE
File storage does not support Chinese names

### ISSUE THREAD

**Issue by renjiali** [supabase/supabase#28811]
File storage does not support Chinese names, if used
1.api calls, will be garbled, a bunch of black fast
2.When the panel is changed to Chinese, an error message is displayed indicating Failed to rename file: API error happened while trying to communicate with the server.

**Comment by GaryAustin1** [comment]
This is an open issue in storage for awhile...
https://github.com/supabase/storage/issues/133

**Comment by renjiali** [comment]
> This is an open issue in storage for awhile... [supabase/storage#133](https://github.com/supabase/storage/issues/133)

This is so much fun. Since this is a bug, and has been for so long, the problem has never been fixed. So what is the significance of this?

**Comment by GaryAustin1** [comment]
You can add to the open issue.  They must not consider it that important, or for the way they do things it is a difficult fix.

**Comment by renjiali** [comment]
> This is an open issue in storage for awhile... [supabase/storage#133](https://github.com/supabase/storage/issues/133)



supabase really should study the products from China, this is the product using supabase, but solved the problem of file name. How supabase was unable to solve the problem. Then request and copy it! The address is https://memfiredb.com/
