### ISSUE TITLE
TS type generation does not give output in terminal, has remains in output file after running the script

### ISSUE THREAD

**Issue by stefansurkamp** [supabase/supabase#28863]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I was following the instructions on https://supabase.com/docs/guides/api/rest/generating-types to create types. However, when running `npx supabase gen types --lang=typescript --schema public > database.types.ts` in my terminal, I do not receive further outputs. All I can see is that there is a new file, `database.types.ts`, but its contents are what should probably be displayed in the terminal:

```
[?25l
    Select a project:                                                                           
                                                                                                
  >  1. [my project id] [name: [my project name], org: [my project org], region: [my region]]
                                                                                                
                                                                                                
    ↑/k up • ↓/j down • / filter • q quit • ? more                                              
                                                                                                [0D
```

As described above, there is no visible output in my terminal, I can type 1 and press ENTER however, and the type creation progress starts. All types are then appended to the code snippet above. I manually have to remove these parts to end up with a valid TS file.

I am using iTerm build 3.5.4, with ohmyzsh.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open a terminal
2. Navigate to your project directory
3. Run `npx supabase gen types --lang=typescript --schema public > database.types.ts`

## Expected behavior

1. There should be proper output in the terminal.
2. After selecting a project, the initial file contents should be removed and only the proper TS types should remain.

## System information

- OS: macOS Sonoma 14.5 (23F79)
- Version of supabase: 1.190.0
- Version of @supabase/supabase-js: 2.45.1
- Version of Node.js: v20.11.0

**Comment by encima** [comment]
Hello,

thanks for opening. As you ran the command with `> file` then the terminal output is redirected to that file.

If you want it in the terminal and a file then you can run it as:  `npx supabase gen types --lang=typescript --schema public | tee database.types.ts`
