### ISSUE TITLE
Support `schema.prisma` migration/deployment

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#2892]
I want to deploy my database schema via my `schema.prisma` file.

one of my favorite feature of prisma is their declarative model.
As seen in this example `posts` and `author` field will not be save into database. But look how easy to visualize this model about their relationship. Think about how if it is a complex relationship or deeply nested relationship.

```graphql
model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id       Int  @id @default(autoincrement())
  author   User @relation(fields: [authorId], references: [id])
  authorId Int // relation scalar field  (used in the `@relation` attribute above)
}
```

So thats why i build my schema first using Prisma.
After all Prisma uses code generation tool thats why I cant leave prisma right now.
Imagine Im creating a Flutter app and React App. I get a free code generated model for dart and ts by just creating my database schema.

This would speed up development both server side and client side.

**Comment by sandbox-apps** [comment]
Im seeing it as I can paste and edit my `schema.prisma` file inside supabase then click `save` or `migrate` to reflect it on postgres database.

One good thing is also open source and support other database (as i have seen your thread about what to support after postgres)

**Comment by kiwicopple** [comment]
There is a full guide for Prisma + Supabase here:

https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505/

I'll close this as I don't know if it's really a bug in Supabase. 

(one thing to be very aware of when using Prisma is that you need to use the Connection Pool on deployment, but the Direct connection for migrations)
