### ISSUE TITLE
possible bug in dashboard view of database metadata

### ISSUE THREAD

**Issue by anngbaum** [supabase/supabase#28949]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

question about the metadata in https://supabase.com/dashboard/project/PROJECT_ID/database/tables – how is that row estimate calculated? the row count data showing up for me (for certain tables) is off by an order of magnitude.

for a quick example, I was checking the table ingredient_text_metadata. in the table editor view, the estimated row count is 1.1M which sounds correct. the table editor exact row count (very cool feature, btw) confirms this at 1,153,358 rows.

in the /databases/table view, however the estimated row count is 36,200 (see screenshot). 

what's a little confusing is that other tables seem spot on – in the same screenshot you can see grocery_list shows an estimate of 79,091, which correctly aligned with the estimate in the table editor and actually the confirmed exact count.

is there possibly a bug with large estimations in this view?

## To Reproduce

possibly only impacting large tables?

## Expected behavior

correct row count estimation

## Screenshots
/databases/table view:
<img width="665" alt="Screenshot 2024-08-28 at 10 29 42 AM" src="https://github.com/user-attachments/assets/b64e4815-d08e-4b44-8a6f-8caf6452c5e1">

table editor:
<img width="320" alt="Screenshot 2024-08-28 at 10 44 34 AM" src="https://github.com/user-attachments/assets/14f517cc-0faf-49c7-9ffc-62ff1512ec41">

## System information

n/a

## Additional context

feel free to DM if helpful to access my project

**Comment by encima** [comment]
Hi there,

Thanks for reporting! This is expected behaviour for large tables and this is used because it helps improve the performance of the dashboard with larger tables. See this information in the [API docs](https://supabase.com/docs/reference/javascript/select) for details: 
![image](https://github.com/user-attachments/assets/44bf3618-7a3d-454d-a568-2529bc4cd3f6)

You can also ensure your statistics are up to date to be sure that the row count is more accurate
