### ISSUE TITLE
SvelteKit: Connect to your project guide

### ISSUE THREAD

**Issue by JR-G** [supabase/supabase#28943]
# Improve documentation

## Link 
On the https://supabase.com/dashboard/project/xxxx page, in the "Connect to your project" window that appears and with SvelteKit selected.

## Describe the problem
I encountered:
```
[vite] Error when evaluating SSR module /src/lib/supabaseClient.js:
|- Error: supabaseUrl is required.
```
Whilst following the "Connect to your project" setup instructions.
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/8792dc5d-3dee-42d0-a61d-6e37f83a15f8">

## Describe the improvement

Making the following changes fixed the error and enabled me to proceed with the setup.

In `.env.local`:
Prefixing with `VITE_`
```
VITE_SUPABASE_URL=xxxx
VITE_SUPABASE_ANON_KEY=xxxx
```

In `src/lib/supabaseClient.js`:
Using `import.meta.env` instead of `process.env`
```
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseKey);
```

**Comment by JR-G** [comment]
@encima I'm happy to open a PR for this

**Comment by encima** [comment]
> @encima I'm happy to open a PR for this

Please do!

**Comment by adityaraute** [comment]
This issue should be closed.
