### ISSUE TITLE
update flutter-user-management with latest supabase-flutter version

### ISSUE THREAD

**Issue by StevePhuc** [supabase/supabase#2895]
# Feature request
update [flutter-user-management ](https://github.com/supabase/supabase/tree/master/examples/flutter-user-management)with latest supabase-flutter version 

## Is your feature request related to a problem? Please describe.
when ran the flutter-user-management with latest supabase-flutter version  0.21, there are many errors related with hive and supabasePersistSessionKey

**Comment by StevePhuc** [comment]
@phamhieu can you have a look

**Comment by phamhieu** [comment]
Hi @StevePhuc, i updated the example to use the latest packages
