### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by jingsam** [supabase/supabase#29029]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/92ce9f87-f577-45b4-a09c-e3ecc433f8e1">

![image](https://github.com/user-attachments/assets/9ec956a3-1218-4728-a80a-2a71daef8aca)

## To Reproduce
1. git check out the latest supabase code at master branch
2. npm install && npm run dev:studio
3. go to Table editor or Tables in Database

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

I check the error, maybe this issue is related to Loader2 component.

**Comment by major-winter** [comment]
I don't encounter the error using the reproduce steps. By the way, the version of node should be `20.0.0` instead of `10.10`
![image](https://github.com/user-attachments/assets/89066d32-56b0-4b48-93b1-a7cff068cb3d)

**Comment by Hallidayo** [comment]
Hi @jingsam - I've just tried the above but I'm not getting the hydration issue. I'm going to close this one but if are you still experiencing the issue please feel free to reach out.
