### ISSUE TITLE
Unable to create users from dashboard

### ISSUE THREAD

**Issue by WayneUong** [supabase/supabase#29024]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Specific project unable to create users from dashboard with following error. Other projects work fine.

```
Failed to create user: upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots

![Screenshot 2024-09-01 at 12 05 38 AM](https://github.com/user-attachments/assets/f88a276b-929d-4ce2-a51b-fc17ffcb00b8)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by deezeddd** [comment]
Hi, I couldn't reproduce this. could you try again and see if the issue still persists?

**Comment by WayneUong** [comment]
@deezeddd The issue still persists for `hzozfzzeabvbuwqoefaz`. It works fine for other projects though.

![Screenshot 2024-09-02 at 1 46 28 PM](https://github.com/user-attachments/assets/f20e162b-390c-420e-885b-f629dd944376)

**Comment by Hallidayo** [comment]
Hi @WayneUong - Thank you for opening the issue, I've just tried to recreate my end and I am also unable to. This seems like it may be just effecting your one project. 

please send an email to [support@supabase.io](mailto:support@supabase.io) and we'll have a look!

**Comment by GaryAustin1** [comment]
Also do you have any auth.user trigger functions?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
