### ISSUE TITLE
The Drizzle connection documentation is inacurate

### ISSUE THREAD

**Issue by shiddy** [supabase/supabase#29076]
# Improve documentation

Currently, the documentation for Drizzle says that you only need a database URL, which is not accurate, at least with the current self-hosted supabase docker compose setup.

## Link 
https://github.com/supabase/supabase/blob/3f34ca978cb163eb395055e9c1229b7a2bd9dc3c/apps/docs/content/guides/database/connecting-to-postgres.mdx?plain=1#L165

## Describe the problem

If I understand correctly and we are using postgres with a supabase install, we either need to disable RLS entirely before we are able to run a Drizzle Migration, which I don't think is possible. (I'm brand-new to JS and all this so I reserve my right to be completely wrong here)

What I ended up doing was using the second option defined here: https://orm.drizzle.team/kit-docs/config-reference#dbcredentials and just provided the values from my .env for supabase and guessed on the username since it was not provided

```
export default defineConfig({
  schema: './db/schema.ts',
  out: './db/supabase/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    host: "127.0.0.1",
    port: "5432",
    user: "postgres",
    password: "your-super-secret-and-long-postgres-password",
    database: "postgres"
  },
});
```

I don't think is is the best way... but I don't think that the docs are accurate to what currently is deployed when running a self-hosted Supabase instance.

## Describe the improvement

Update the docs on the defineConfig() call so that it's able to run on a fresh install of SupaBase. I am not sure if there is another key or secret that needs to be provided to the defineConfig but I also don't think that's something you guys are in charge of maintaining.

**Comment by encima** [comment]
The postgres user (unless overridden), is not impacted by RLS policies so the document is right in that you only need a connection string for the `postgres` user.

For example:
`postgres://postgres:PWD@127.0.0.1:5432/postgres`

If there are issues with the Drizzle docs, feel free to open issues with them. Reviewing the Supabase [docs](https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-drizzle), the current recommendations are correct.

Thanks!
