### ISSUE TITLE
Make supabase kotlin library using retrofit 

### ISSUE THREAD

**Issue by io-Karim-developer** [supabase/supabase#2907]
#or update postgrest-kt library or gotrue-kt

**Comment by kiwicopple** [comment]
Hi @io-Karim-developer - can you please explain a bit more? You're looking for Kotlin support right?

If yes, some progress has been made by the community here: 
https://github.com/supabase/?q=-kt&type=&language=&sort=

We're also tracking demand for the different languages/frameworks here:
https://github.com/supabase/supabase/discussions/5

I'll close this, but feel free to comment again if I misunderstood your issue and we can reopen this 👍
