### ISSUE TITLE
Type of Query result with left join doesn't match inferred type

### ISSUE THREAD

**Issue by castortech** [supabase/supabase#29086]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have the following query:
```
  const { data: models, error } = await supabase
    .from("models")
    .select(`
      *, 
      providers!left(internal_name)
    `)
    .eq("provider_id", providerId)
```

which infers the type of models to be (notice the providers is showing an array of providers):
```
const models: {
    api_key: string | null;
    base_url: string | null;
    context_length: number;
    created_at: string;
    deprecated: boolean;
    description: string;
    id: string;
    max_temperature: number;
    min_temperature: number;
    model_id: string;
    name: string;
    owning_tenant: string | null;
    pricing_currency: string;
    pricing_image: number;
    pricing_input: number;
    pricing_output: number;
    pricing_request: number;
    pricing_unit: string;
    provider_id: string | null;
    removed: boolean;
    replaced_by_id: string | null;
    sharing: string;
    supports_images: boolean;
    supports_tools: boolean;
    token_output_length: number;
    updated_at: string | null;
    user_id: string;
    providers: {
        internal_name: string;
    }[];
}[] | null
```

But when running the query, returned type for the left join (providers) is not an array. It is just an object:
```
{internal_name: 'mistral'}
```
and if I debug with `Array.isArray(models[10].providers)` it returns false.

## To Reproduce

Here is the table definition part covering the provider_id:
```
ALTER TABLE models
     --this identifies a built-in (non custom model)
    ADD COLUMN IF NOT EXISTS provider_id UUID REFERENCES providers(id),
```

## Expected behavior

The inferred type must match the results at run time. Either the inferred type is wrong (which I believe is the case since this is a 0-1 cardinality) or the returned type is wrong. But they surely can't be different.

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/supabase/supabase
