### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by LukaHarambasic** [supabase/supabase#2908]
# Bug report

## Describe the bug

I have a public storage bucket. When I get the public URL via `getPublicUrl()` I get a URL, but this URL returns a 404. When I get the URL via the UI (right click on the file) I get a working URL.

```
{
  "statusCode": "404",
  "error": "Not found",
  "message": "The resource was not found"
}
```

- URL from `getPublicUrl()`: https://gkjykehhfdcaojaumiru.supabase.co/storage/v1/object/public/public-bucket/media/demo-1629406304569.mov
- URL via the UI: https://gkjykehhfdcaojaumiru.supabase.in/storage/v1/object/public/media/demo-1629406304569.mov

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upload a new file (s. https://github.com/LukaHarambasic/prilog/commit/ea2e486b4c1af0fcbd4254907667d53334bad38d#diff-13589dcf5f82cd4e3b1b590127f1a6fb75e8a8c72603136a8235ad631f2d42c4R82)
2. Use https://supabase.io/docs/reference/javascript/storage-from-getpublicurl
3. Try to open URL

Commit with the change: https://github.com/LukaHarambasic/prilog/commit/ea2e486b4c1af0fcbd4254907667d53334bad38d

## Expected behavior

I get a working URL.

## Screenshots

![image](https://user-images.githubusercontent.com/22857823/130143128-3909ff13-b94f-40b4-b686-e99160c136da.png)

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of supabase-js: 1.21.1
- Version of Node.js: 16.3.0

**Comment by mblog** [comment]
Are you using the linked code?
You upload the new file to the media bucket, but create a Public Url for a file in another bucket (public-bucket).

You need to create the public Url for the media bucket.

**Comment by darora** [comment]
@LukaHarambasic let us know if you're still facing this issue after implementing @mblog 's suggestion

**Comment by inian** [comment]
Hi @LukaHarambasic, i couldnt find an object called `undefineddemo-1630574594757.mov` in your project. But I found another object and access it via a public url works fine - https://gkjykehhfdcaojaumiru.supabase.co/storage/v1/object/public/media/avataaars-1630590281844.png

**Comment by LukaHarambasic** [comment]
@inian yes I cleaned up my test files:
![image](https://user-images.githubusercontent.com/22857823/132130102-b2e9ca03-9dcf-44ec-8c3a-49869fe177d6.png)
