### ISSUE TITLE
Supabase GraphQL Playground Docs errors

### ISSUE THREAD

**Issue by webtwitter** [supabase/supabase#29084]
Suddenly, the documentation for GraphQL on Supabase Playground is not working anymore.
I've deleted caching, logged out, hard refresh but nothing helps.
This happens for a week now.

I'm not sure if this is something I'm doing wrong or if it a bug from your side.

Let me know if you need more details.

Thanks a lot!

PS: That request with profiles is valid and returning results 
![errs](https://github.com/user-attachments/assets/9c47294b-b1b0-41c1-bc22-066b3100ccf9)

**Comment by HeyRintu** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by webtwitter** [comment]
Damn! you're right! Thanks for clarifying. So at least we know is not a bug from your side :))
Have am amazing day!
