### ISSUE TITLE
Supabase Website ui breaks

### ISSUE THREAD

**Issue by MrFarhan** [supabase/supabase#29093]
This issue is to bring supabase attention regarding UI management at their website.

When I enter the wrong URL the UI doesn't look good at the configure URL screen, below is the video recording of the same.

https://github.com/user-attachments/assets/a9b00587-18de-456e-b101-b8afa8a5ff30

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/facebook/react

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/supabase/supabase

**Comment by charislam** [comment]
Fixed in https://github.com/supabase/supabase/pull/29100
