### ISSUE TITLE
Supabase needs a Microsoft provider for External Entra ID (EEID)

### ISSUE THREAD

**Issue by JeremyQtweb** [supabase/supabase#29098]
### Discussed in https://github.com/orgs/supabase/discussions/28755

<div type='discussions-op-text'>

<sup>Originally posted by **JeremyQtweb** August 20, 2024</sup>
Hey team,

We've been testing the new Microsoft Entra External ID (EEID) service, their replacement for Azure AD B2C.

Presumably the Supabase Auth - Microsoft Provider is one of those services.

Can I confirm with someone if that is true, and which one the Microsoft Provider is using?
</div>

Microsoft Entra ID is not just a rebrand of Azure AD.
Microsoft re-engineered the auth process and released a new service called External Entra ID (or EEID).
The current Microsoft provider in Supabase is using the old Azure AD B2C service which is incompatible with users trying to sign-in whom belong to a EEID tenant.
The most significant issue is that MFA does not work.

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/facebook/react

**Comment by encima** [comment]
Hi @JeremyQtweb ,

As this is a Discussion with active contribution, I will close this. Please only create one or the other when submitting as it can cause issues. 
As EEID is technically a new feature, it may be best to move your discussion to a feature request
