### ISSUE TITLE
Supabase Web UI shows false when value is actually NULL if column default value is NULL

### ISSUE THREAD

**Issue by sophiabk** [supabase/supabase#2919]
# Bug report
Supabase Web UI shows false when value is actually NULL if column default value is NULL

## Describe the bug

If a column is set to "bool" with the default value as NULL, the UI will show "false" even though the actual value of the column is NULL.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new table
2. Add a column with type "bool" and set default value to NULL
3. Add a new item (without a value for that column)
4. See that the column is blank and then on refresh it will be "false"
5. Look up that table > column > row via the supabase API and see that the actual value is NULL

## Expected behavior

Value should show as NULL in the column rather than false.

## Screenshots

<img width="692" alt="Screen Shot 2021-08-20 at 2 34 35 PM" src="https://user-images.githubusercontent.com/1304174/130296040-852e4c42-fe03-4e24-8d6b-5d0cfe6987e8.png">
<img width="538" alt="Screen Shot 2021-08-20 at 2 35 13 PM" src="https://user-images.githubusercontent.com/1304174/130296043-592452cc-9ac9-4b80-9782-03deb8f0a706.png">
<img width="400" alt="Screen Shot 2021-08-20 at 2 30 46 PM" src="https://user-images.githubusercontent.com/1304174/130296054-adafde12-b681-406a-b20a-bd1f44532841.png">

## System information

- OS: Mac
- Browser (if applies) Chrome

**Comment by kiwicopple** [comment]
fixed!
