### ISSUE TITLE
Word 'compute' is there twice on Pricing & Fees page

### ISSUE THREAD

**Issue by SlamJam4** [supabase/supabase#29192]
# Typo correction

In the Select the best compute size for you section, there's a sentence where compute is said twice: 'Select the compute compute size that fits your needs.'  ![image](https://github.com/user-attachments/assets/38abbc7c-e305-4fef-bf99-7307a0e87844)

**Comment by r0ld3x** [comment]
twice? where?

**Comment by r0ld3x** [comment]
can I fix it? haha so easy

**Comment by charislam** [comment]
@r0ld3x of course! ❤️
