### ISSUE TITLE
"Database error granting user" only on user signup

### ISSUE THREAD

**Issue by goudarziha** [supabase/supabase#2920]
# Bug report

## Describe the bug

I am having issues currently only trying to sign in new users. I had gone through the [docs](https://supabase.io/docs/guides/auth/managing-user-data) I was able to get one user signed in, but not able to after 1st user. I went through the policies to make sure nothing was blocking, as well as any other functions/triggers that were preventing me from creating a new user. I have seen other issues solved for a very similar case, but none of those solutions had worked for me.

Currently getting back a 500 error with message below.
`level=error msg="500: Database error saving new user"`

`time="2021-08-21T13:10:53Z" level=error msg="500: Database error saving new user" component=api error="failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: relation \"public.users\" does not exist (SQLSTATE 42P01)" method=POST path=/signup referer="http://localhost:3001/" remote_addr="73.180.230.171:41884" request_id=0ff2e228-715d-4b7f-9454-5b1fe4551fc1`

## Screenshots
![dsfdsfds](https://user-images.githubusercontent.com/5420796/130305596-f77370ab-a5e4-4194-9fd7-84bebe6cb198.JPG)

**Comment by w3b6x9** [comment]
@goudarziha assuming you have the table `public.users`, did you set up any references to the `auth.users` table? What does that look like?

**Comment by w3b6x9** [comment]
@@goudarziha i'm going to close this issue for now. Please reopen if your issues remain.
