### ISSUE TITLE
Unable to Connect to Supabase PostgreSQL via Sequelize: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing

### ISSUE THREAD

**Issue by ryzxxn** [supabase/supabase#29257]
I’m using Sequelize to connect to various PostgreSQL databases. The connection works for some instances but fails when trying to connect to Supabase with the following connection string:

```
postgresql://postgres.zzoqmftgxxbtuztxklxi:[PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
```

I receive the following error:
```
Unable to connect to the database: SequelizeConnectionError: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
```

Steps to Reproduce:
Code: Here is the Sequelize instance creation code I'm using:
```
const { Sequelize } = require('sequelize');

function createSequelizeInstance(connectionURI) {
  return new Sequelize(connectionURI, {
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false,  // Tried both true and false here
      },
    },
  });
}
```
Working connectionUri:
```
postgresql://vmkathe:[PASSWORD]@ep-damp-sun-a1vvdcup-pooler.ap-southeast-1.aws.neon.tech/anyname?sslmode=require
```
this db  is provided by NeonDb

Expected Behavior:
Sequelize should successfully authenticate with Supabase PostgreSQL using the provided connection string.

Actual Behavior:
Authentication fails with the error SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing.

Questions:
Is there any specific configuration required to authenticate with Supabase PostgreSQL when using Sequelize?
Is this error related to Supabase’s authentication mechanism, or is it a bug/limitation in Sequelize’s handling of SASL/SCRAM authentication?

Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by aldegoeij** [comment]
also occuring here with Retool -> Supabase

**Comment by ryzxxn** [comment]
> also occuring here with Retool -> Supabase

yeah what iam assuming is that supbasew is using scram which is not supported by sequlize library

**Comment by ssudaraka** [comment]
Hi @aldegoeij,

I created a Retool account and tried to test the connection to Supabase DB as a Postgres resource and ran into this error. 

However, when I saved the resource anyway, and tried again, it worked for me. I feel like this is a weird bug in Retool. Have you tried saving the resource anyway and trying it at a later time? 

Also, please validate that your credentials are correct.

**Comment by ryzxxn** [comment]
update : 

i used Typeorm instead of sequelize and iam getting same erro except this time its:
```
Unable to connect to the database: Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
```

**Comment by awalias** [comment]
hey @ryzxxn ! 

>this db is provided by NeonDb
just to clarify, is your database Supabase or Neon? It looks from the connection string that it's neon

**Comment by ryzxxn** [comment]
postgresql://postgres.zzoqmftgxxbtuztxklxi:[PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
hey sorry if i missed some details out initially,
the above string is giving me the issue not the one from neon DB

**Comment by monicakh** [comment]
hey @ryzxxn, can you try to connect to Sequelize using the 5432 port and let us know if you still have this issue? The transaction port 6543 is typically used for short-lived connections in serverless environments to execute a sequence of SQL commands as a single unit of work. For standard database connections like Sequelize, port 5432 should be used.

Also, checking your project logs there's the following error: `Exchange error: "Wrong password" when method: auth_query`. Can you double-check your credentials to make sure they’re correct?

**Comment by ryzxxn** [comment]
![image](https://github.com/user-attachments/assets/8d30d1f5-f05d-48c4-a623-aac43f2e4d7f)
i have switched to port 5432,

**server.js**
```
const express = require('express');
const cors = require('cors');
const { Sequelize } = require('sequelize');
const bodyParser = require('body-parser');

const app = express();
const port = 6767;
app.use(cors());
app.use(bodyParser.json());

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Create a function to create a new Sequelize instance
function createSequelizeInstance(connectionURI, database_name, username, password, hostname, dialect, port) {
  if (connectionURI) {
    return new Sequelize(connectionURI,{
      ssl: { rejectUnauthorized: false}
  });
  } else {
    return new Sequelize(database_name ?? '', username ?? '', password ?? '', {
      host: hostname ?? 'localhost',
      dialect: dialect ?? 'mysql',
      port: port ?? 3306,
    });
  }
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Define a route handler for testing the database connection
app.post('/connect', (req, res) => {
  const { connectionURI, hostname, password, username, database_name, dialect, port } = req.body;
  const sequelize = createSequelizeInstance(connectionURI, database_name, username, password, hostname, dialect, port);

  // Test the connection
  sequelize.authenticate()
    .then(() => {
      console.log('Connection has been established successfully.');
      res.sendStatus(200);
    })
    .catch(err => {
      console.error('Unable to connect to the database:', err);
      res.sendStatus(400);
    });
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
```
if you want i can also share the connection string with the password if that would help.

> hey @ryzxxn, can you try to connect to Sequelize using the 5432 port and let us know if you still have this issue? The transaction port 6543 is typically used for short-lived connections in serverless environments to execute a sequence of SQL commands as a single unit of work. For standard database connections like Sequelize, port 5432 should be used.
> 
> Also, checking your project logs there's the following error: `Exchange error: "Wrong password" when method: auth_query`. Can you double-check your credentials to make sure they’re correct?

there was an instance where i was using the wrong password

thanks a lot.

**Comment by monicakh** [comment]
@ryzxxn Thanks for the additional information. I'll get our pooler team to investigate this issue.

**Comment by abc3** [comment]
Hey @ryzxxn, did you remove the password after ":" for the screenshot? Did you try connecting with another PG client like psql?
<img width="215" alt="Screenshot 2024-09-16 at 16 08 25" src="https://github.com/user-attachments/assets/4418a765-176d-42cc-b80b-71188e043087">

**Comment by ryzxxn** [comment]
> Hey @ryzxxn, did you remove the password after ":" for the screenshot? Did you try connecting with another PG client like psql? <img alt="Screenshot 2024-09-16 at 16 08 25" width="215" src="https://private-user-images.githubusercontent.com/1172600/367790747-4418a765-176d-42cc-b80b-71188e043087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTY1NzcsIm5iZiI6MTcyNjQ5NjI3NywicGF0aCI6Ii8xMTcyNjAwLzM2Nzc5MDc0Ny00NDE4YTc2NS0xNzZkLTQyY2MtYjgwYi03MTE4OGUwNDMwODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTQxNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgzYmUyNmViOTk5MGY3ZTAwMGQ4NDNlZjZlZWE0YTk4NzkwMWQ3ZWYzOGU5MjAzZjFkMDFlOTYzNzk4NjhiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5FKrdc0q9GbhyhNtpPIVQtEtyJIl4HTkYgmdY1Si6nE">

yes i have removed the password in that screenshot

**Comment by abc3** [comment]
@ryzxxn could you opensource your example so I can try to fully reproduce the issue?

**Comment by ryzxxn** [comment]
![as](https://github.com/user-attachments/assets/d7b7d6cd-eaf2-413b-ad44-40d5acdf3ad4)
hi i tried to connect on my linux machine with psql and a diffrent connection string and it worked, in terminal as well as in my app.
which leads me to belive there was some error in my connection string. 
i also re installed all the packages and all connection methods seems to work as intended

new connection string i tested with
```
postgresql://postgres.fwmbpflhidkdwmpxrdgf:[password]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
```
thank you  all for your help i really appreciate it, also if any additional information is needed please let me  know ill be more then happy to provide it.


> @ryzxxn could you opensource your example so I can try to fully reproduce the issue?

[https://github.com/ryzxxn/Leafsync/tree/orm-based](url)

**Comment by thewiredbear** [comment]
had a similar issue - trying to connect supabase to make.com via generic postgres connection. Changing the port from 6543 to 5432, solved the issue for me. Interesting how I couldn't find this solution anywhere in the official documentations. Thanks for saving my day!

**Comment by bubuuble** [comment]
hey, have u solved this problem? because now i exprienced same problem

**Comment by Oumar224** [comment]
i have also the same issue but i use typeorm 
![image](https://github.com/user-attachments/assets/84c70467-7cf4-45b0-9b34-115c5b12a62e)

**Comment by Oumar224** [comment]
thi issue helped to solve it:
https://github.com/supabase/supabase/issues/21690

**Comment by thiagoprazeres** [comment]
Use port 5432 instead of 6543 which works.

**Comment by jektvik** [comment]
This is absurd but that exact message was throwing me for the last couple hours 

-> when i reset the password to one without bushy characters it suddenly started working (use the reset password feature on the web platform dashboard under settings -> database).  Keep all else by the book and use the pooler connection string.

I imagine i had generated the original password with some external password generator.

**Comment by hdittmar** [comment]
For anyone passing by here looking for a solution, _**double check your db password is entered correctly**_! This error also occurs when the password is wrong.

**Comment by aigahon** [comment]
@hdittmar thank you, saved me a couple of debug hours!
