### ISSUE TITLE
Example from docs is not possible

### ISSUE THREAD

**Issue by Skrekliam** [supabase/supabase#29323]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/server-side/nextjs 
Step 3.

## Describe the problem

In line 2 we have 
`import { cookies } from 'next/headers'`
and line 4 is
`export function createClient() {`

here nextjs argues because next/headers works only on server
![image](https://github.com/user-attachments/assets/30a3a585-7958-40ec-90d7-acf6cdecfed9)

when i add "use server" I got an error that use server actions must be async
![image](https://github.com/user-attachments/assets/716ca773-036e-472b-b6cf-94c0d1fd2786)

then all usages of supabase.auth or anything else fails
![image](https://github.com/user-attachments/assets/f28f5a92-c53b-4be3-9d03-18ad2866568c)
![image](https://github.com/user-attachments/assets/fc406c77-77ee-4155-a032-0ff8e1c02dda)
and suggest next fixes:
`const supabase = await createClient()`
or
`  const { data: user, error } = await (await supabase).auth.getUser(); `

## Describe the improvement

I dont know how to help here

## Additional context

This issue happened after migrating from auth helpers

**Comment by charislam** [comment]
Thanks for opening the issue @Skrekliam! Where is this component that uses `createClient` being run? If it is a client component, it needs to use the browser version of the client (import from `@/utils/supabase/client`), not the server version

**Comment by Skrekliam** [comment]
> Thanks for opening the issue @Skrekliam! Where is this component that uses `createClient` being run? If it is a client component, it needs to use the browser version of the client (import from `@/utils/supabase/client`), not the server version

Hey, thanks for answering. As you can see in my example I run it inside layout which is exported async function

**Comment by charislam** [comment]
Ahh I see you have an error message about Server Components not being supported in the pages directory. Is this layout also being imported in the pages directory accidentally?

![image](https://github.com/user-attachments/assets/7db35832-06f0-487b-b71f-c5534b9df2b6)

**Comment by charislam** [comment]
Do you have a pages directory at all in your app? (not just using that layout but in general)

I just tested the instructions against a fresh install of Next.js, and they worked for me, so I'm wondering what it is about your setup that's erroring. If you also try the [instructions](https://supabase.com/docs/guides/auth/server-side/nextjs?queryGroups=router&router=app) in a fresh Next.js app, do they work?

**Comment by Skrekliam** [comment]
Wow, I just had a stupid mistake in my code. I've used `createClient` from `server` with `use client`. 
Thanks for your time!

**Comment by charislam** [comment]
Happens to the best of us 😄 Glad you found the bug!
