### ISSUE TITLE
Cannot display images on Supabase storage

### ISSUE THREAD

**Issue by manel00** [supabase/supabase#29348]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
async function uploadImage(file) {
    console.log(file)
    const fileExt = file[0].filename.split('.').pop();
    const fileName = `${Date.now()}.${fileExt}`;
    const { error } = await supabase
      .storage
      .from('test') // Nombre del bucket
      // .upload(fileName, file[0], {
      .upload(fileName, file[0].buffer, {
          contentType: file[0].mimetype
        });
  
    if (error) {
      console.error('Error uploading image:', error);
      return null;
    }
  
    const { publicURL, error: urlError } = supabase
      .storage
      .from('test')
      .getPublicUrl(fileName);
    console.log(publicURL)
    if (urlError) {
      console.error('Error getting public URL:', urlError);
      return null;
    }
  
    return publicURL;
  }
```

## Expected behavior

Upload the picture properly

## Screenshots

![image](https://github.com/user-attachments/assets/48688678-532c-4bad-a4e5-f2b8f9f50c34)

## System information

- OS: Ubuntu 24
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]
- NextJS 14

**Comment by Hallidayo** [comment]
Hi @manel00 - Thank you for opening the issue! Just a couple of questions:

- Do you get any network/console errors when you are uploading images?
- Do you have any policies set on the bucket?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
