### ISSUE TITLE
Custom Domains don't work with Edge Functions 

### ISSUE THREAD

**Issue by valscholz** [supabase/supabase#29354]
### Discussed in https://github.com/orgs/supabase/discussions/13371

@inian I've set up custom domain on my Supabase project, but the environment variables for supabase_url are still going on the old supabase domain. This breaks my web app as publicUrls generated in the edge function link to the wrong domain. How can we update the environment variables for edge functions after activating the custom domain in Supabase?

<div type='discussions-op-text'>

<sup>Originally posted by **leekuo** April  2, 2023</sup>
I saw this link: https://supabase.com/docs/guides/platform/custom-domains#limitations

"Edge functions do not honor the custom domain or the vanity subdomain setting and they still have to be invoked via the foobarbaz.supabase.co domain."

I have created several edge functions but I want to use my own custom domain.  As there are many clients still pointing at my own domain, I don't have the option of switching them all over.  Is there anyway to enable custom domains for edge functions somehow?  Or if not, is there somewhere else to host these deno functions where I can do so?</div>

**Comment by inian** [comment]
After you set up custom domains, functions should be accessible via both the existing domain (projectref.supabase.co) and your custom domains. The environment variables are not updated inside your function, but the function should still be available without going over the custom domain. 

The limitation you mentioned is no longer applicable and the docs don't mention it any longer.

**Comment by encima** [comment]
We will close this as the issue does not seem to be relevant. If you still experience this, please let us know here or open a support ticket!
