### ISSUE TITLE
updateUser on Anonymous Sign in Automatically Verifies Email

### ISSUE THREAD

**Issue by mauricelandersiii** [supabase/supabase#29350]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

According to the [docs](https://supabase.com/docs/guides/auth/auth-anonymous?queryGroups=language&language=js#link-an-email--phone-identity) linking an email should link the email but `is_anonymous` should still be `true` and in the db `email_confirmed_at` should be empty until the user confirms by magic link or OTP. However currently `is_anonymous` is false and `email_confirmed_at` automatically has a value.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable Anonymous Sign In
2. Link any email to anonymous account using updateUser
3. See that they are immediately un anonymously signed in with a verified email.

## Expected behavior

`is_anonymous` should still be `true` and in the db `email_confirmed_at` should be empty until the user confirms by magic link or OTP.

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 2.45.4
- Version of Node.js: [e.g. 10.10.0]

**Comment by AlexBThomsen** [comment]
I can confirm this locally as well any update on this?
