### ISSUE TITLE
Cursor jumps to the end of the input field in "Ask Supabase AI"

### ISSUE THREAD

**Issue by denkasyanov** [supabase/supabase#29379]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Weird editing input field behavior
Cursor jumps to the end of the input field

## To Reproduce

1. On any docs page open search (for example here https://supabase.com/docs/guides/auth ) OR ⌘K
2. Click on "Ask Supabase AI"
3. In the focused field enter "first second third"
4. Move cursor to the end of "second"
5. Try to delete exactly the word "second"

## Expected behavior

I am able to delete the second word without cursor jumping to the end of the input field

## Demonstration

https://github.com/user-attachments/assets/82908a23-b707-47ff-bd6e-fd78a9d0f121

**Comment by charislam** [comment]
Can reproduce! Thanks for flagging @denkasyanov!
