### ISSUE TITLE
regression: The API URL is now below the keys

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#2941]
# Chore

## Describe the chore

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/10214025/130607926-c64356b1-edd8-4746-ae65-52bb75f8c458.png">

The API URL was previously at the top of the page. I assume this was a mistake? It's the first thing we ask the user to find, so it should be up the top

## Additional context

Perhaps we can consider putting the URL in the same panel as the Keys (but at the top). The JWT secret is a bit more generic - we could even move it to the "General Settings (it's also used for Auth).

**Comment by MildTomato** [comment]
Sorry, i forgot about this - buried in our issues.
Added to this weeks workload

**Comment by saltcod** [comment]
Hey @kiwicopple @MildTomato  — how we feeling about this?  (before on the left, after on the right)

<img width="1646" alt="CleanShot 2022-05-04 at 07 00 40@2x" src="https://user-images.githubusercontent.com/105593/166656202-841b162f-3adc-413f-a721-78576f0f53c2.png">

**Comment by MildTomato** [comment]
nice! I like the right one.

i would argue we should pack the JWT and API keys together.
they also all get reset together.
