### ISSUE TITLE
Update logo from PNG to SVG for sharpness on Desktop

### ISSUE THREAD

**Issue by kwconrad** [supabase/supabase#2943]
Loving the platform. And want it to look as good as it can.

On the website, the logo is blurry on desktop on Chrome.

If you changed the logo from a png to an svg I think it would help, as the PNG is not preserving its sharpness when being scaled down in the navbar.

**Comment by kwconrad** [comment]
Thanks for building this you guys! Looking forward to watching the company grow.

**Comment by AnirudhPanda** [comment]
> Thanks @kwconrad 👍
> 
> I'll mark this one as a good first issue and see if anyone wants to pick it up.
> Brand assets are here: https://supabase.io/brand-assets

Would love to work on this

**Comment by proismailshah** [comment]
I want to contribute to open source would love to work on that...

**Comment by thefool76** [comment]
@kiwicopple can you tell me the file's path where you wanted to add svg ?

**Comment by karan316** [comment]
I've made a [PR](https://github.com/supabase/supabase/pull/3094). There seems to be some issue. Please check it out.

**Comment by Rohithgilla12** [comment]
#3094 should close this issue @kiwicopple
