### ISSUE TITLE
Support aarch64 for the Compose setup

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#2954]
# Feature request

## Is your feature request related to a problem? Please describe.

The Compose setup currently works for amd64, but not all images are available for linux/arm64.

## Describe the solution you'd like

Add linux/arm64 images on Docker Hub.

- [x] supabase/postgres
- [x] PostgREST
  - https://github.com/PostgREST/postgrest/pull/1901
- [X] Realtime
- [x] GoTrue
- [X] Kong
- [x] storage-api
  - https://github.com/supabase/storage-api/issues/71
- [X] pg-meta
- [X] studio

## Describe alternatives you've considered

n/a.

**Comment by Yonben** [comment]
Would love to see that enhancement happen, any update?
If there's any way to help feel free to ping ;)

**Comment by soedirgo** [comment]
@Yonben All images should now be available on `linux/arm64`, though I saw some are having issues deploying on RPi (https://github.com/supabase/supabase/issues/4887). Can you try it out on your end? https://supabase.com/docs/guides/hosting/docker

**Comment by Yonben** [comment]
I'm using the supabase CLI, maybe that's what causes my issue?
I'm getting the following error:
```
➜  backend git:(test) ✗ supabase start
Error: Error response from daemon: Container 8285361cb0eece695ad8de6d9228d112411e2a40bbd99a972d88549054810ffa is restarting, wait until the container is running
➜  backend git:(test) ✗ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS                        PORTS     NAMES
8285361cb0ee   supabase/postgres:14.1.0   "docker-entrypoint.s…"   8 seconds ago   Restarting (1) 1 second ago             supabase_db_backend
➜  backend git:(test) ✗ docker logs supabase_db_backend
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
➜  backend git:(test) ✗
``

**Comment by soedirgo** [comment]
Hmm, it does seem like the `linux/arm64` image is actually running `linux/amd64`:

```
❯ docker run --rm -it --platform=linux/arm64 -e POSTGRES_PASSWORD=postgres supabase/postgres:14.1.0 uname -a
Linux 8078c697fa14 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 x86_64 GNU/Linux
```

I'm surprised it works at all on M1 Mac. This is being tracked on https://github.com/supabase/postgres/issues/143

**Comment by Yonben** [comment]
I see, so for now do I have any alternative?

**Comment by soedirgo** [comment]
Unfortunately no, the image would have to be fixed first 😕

**Comment by Yonben** [comment]
Ok, thanks a lot for the quick answers and the support :)

**Comment by micahburnside** [comment]
I'm having a similar issue. 

I have a Raspberry Pi 4 loaded with arm64 version of Raspberry Pi OS and am issuing CLI commands via SSH. When I issue the command "sudo docker-compose up" or "docker-compose up", my terminal window beings a never ending loop of a very long string of failure responses and error messages from all the supabase APIs. I am able to navigate to http://localhost:3000 to see supabase studio and successfully navigate to "Default Project". 

All the APIs return the following error when I click on the icons in the studio side menu:
Error: [500] an error has occured: request http://meta.8080/tables failed, reason getaddrinfo ENOTFOUND meta

The API Tab says Error: [401] Invalid authentication credentials

I am unable to submit a support request from the studio GUI. 

My terminal window produces a never ending loop of API errors, sample screenshot shows each api exiting with an error code of 1 or 0
<img width="1728" alt="Screen Shot 2022-03-23 at 6 11 14 PM" src="https://user-images.githubusercontent.com/37281536/159804785-99eecdc6-f904-41f2-9322-4d3593a378d0.png">

**Comment by soedirgo** [comment]
@micahburnside yeah, I think the root cause is the same - most of these containers require db connection to work.

**Comment by micahburnside** [comment]
> @micahburnside yeah, I think the root cause is the same - most of these containers require db connection to work.

Pardon my ignorance as I’m still trying to understand all the steps. What did I miss if I don’t have a db connection? I thought that supabase is the database. How do I connect a database? What database?

**Comment by soedirgo** [comment]
Yeah sorry, the whole picture isn't very clear right now. Some of the services e.g. the auth server (GoTrue) needs a db connection because it stores the users table etc. in the db. The dashboard (Studio) requires a db connection for the SQL editor to work, since the queries go to the db. Same thing with the REST server (PostgREST).

Supabase is the database, but to be specific the database is just Postgres, which in the Compose setup is the container using the `supabase/postgres` image.

**Comment by saendu** [comment]
What is the current state here? I can see on https://hub.docker.com/r/supabase/postgres/tags that there was shortly a version 14.1.0.15 that was supporting arm64. But the most recent version only supports amd64 architecture. @kiwicopple any news on that part? What dependency is causing the issue of not being able to build on arm64? 

I can see that the following images support arm64: 
- [x] supabase/realtime
- [x] supabase/gotrue
- [x] supabase/postgres-meta
- [x] supabase/studio
- [x] supabase/storage-api

Not supported is only:

- [ ] supabase/postgres

**Comment by soedirgo** [comment]
@saendu your list above looks right - we had to temporarily remove linux/arm64 support for supabase/postgres because the builds were prohibitively slow in GitHub Actions. linux/arm64 images for earlier versions were actually linux/amd64 that got mislabelled: they work on M1 Macs (because it's emulated) but not on ARM64 Linux machines.

We're working on adding back linux/arm64 supabase/postgres images built using self-hosted runners.

**Comment by david-plugge** [comment]
Any updates on this?

**Comment by saendu** [comment]
@soedirgo any updates on this yet? What is the issue of not being able to create a supabase/postgres arm64 image? I think postgres has arm64 images since 9.0.0. Are there any dependencies that are not yet available on arm64. Could we maybe disable them if they are extensions? (e.g. some extensions are not yet working on arm64 like raspberry).

**Comment by saendu** [comment]
Are you using GitHub Actions for building your images? Probably sounds stupid to you, but couldn't we use another build environment? Or am I missing something?

**Comment by soedirgo** [comment]
Yeah, we use GitHub Actions to build our images. Open to alternatives for linux/arm64 images.

**Comment by saendu** [comment]
I don't have an alternative solution ready for the project, but maybe someone could do a build and provide it to the community until a stable solution with Github Actions is ready. I could maybe help out with my raspberry pi cluster.

**Comment by david-plugge** [comment]
I´ve been building a supabase-postgres image on an oracle-free-tier arm instance using a selfhosted gitlab runner.
[Here is the project](https://gitlab.com/david-plugge/supabase-postgres)

registry.gitlab.com/david-plugge/supabase-postgres

The image is already in use for a a few days now and there are no issues yet.

**Comment by saendu** [comment]
> I´ve been building a supabase-postgres image on an oracle-free-tier arm instance using a selfhosted gitlab runner.
> 
> [Here is the project](https://gitlab.com/david-plugge/supabase-postgres)
> 
> 
> 
> registry.gitlab.com/david-plugge/supabase-postgres
> 
> 
> 
> The image is already in use for a a few days now and there are no issues yet.

Thanks David I will have a go. 🙏

**Comment by david-plugge** [comment]
I´ve updated the ci to also tag the image with the `docker-version` in `docker.vars.json`

**Comment by lab-bone-Max** [comment]
There does not seem to have been a arm64 tagged build on DockerHub for over 5 months. Apple Silicon has been out for more than 2 years and while not a deal breaker, it is only Sonos and Supabase that still don't still don't have an  aarch64 build. I build a Docker image myself to confirm that the Postgres upstream is not the problem and I had no issues but a one-off build is not integrated into the release stream. 

From the thread this looks like a resource issue but Supabase has also bragged about huge 8 digit series B funding since the last post. I'm happy to pay for an AWS build instance if Supabase can't afford it.

**Comment by soedirgo** [comment]
It took a while, but we now have an [arm64 build](https://hub.docker.com/r/supabase/postgres/tags) for supabase/postgres! 🎉

**Comment by iMonZ** [comment]
> It took a while, but we now have an [arm64 build](https://hub.docker.com/r/supabase/postgres/tags) for supabase/postgres! 🎉

Does it work. Has somebody tested it out?
