### ISSUE TITLE
Auth0 icon is not visible when using light mode

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [supabase/supabase#29570]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)
- https://supabase.com/docs
## Describe the problem
The Auth0 icon is not visible when viewed in light mode
<img width="289" alt="image" src="https://github.com/user-attachments/assets/43cf990b-7c27-43de-8eff-a3952dfd713b">

Is the documentation missing? Or is it confusing? Why is it confusing?
- None
## Describe the improvement

- Add a separate icon for light mode

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by MuditxRajput** [comment]
can i add a new icon for light mode?
