### ISSUE TITLE
replace type any with interface CSSProperties

### ISSUE THREAD

**Issue by JoyShaheb** [supabase/supabase#29576]
# Chore
I've noticed that in some places where css is used as props, there is a usage of type "any". We can clearly replace this with usage of interface "CSSProperties" from "react"

## Describe the chore

Replace all instances of type "any" with interface "CSSProperties" where css is used as props.

## Additional context

Take a look at this before, after code example:
![image](https://github.com/user-attachments/assets/5fa95c32-b1d6-4d6f-b990-e6ed856c006f)

**Comment by sahilpatel342** [comment]
Hello @JoyShaheb, I would love to work on this, fairly new to open source but feel this is a great opportunity.

**Comment by JoyShaheb** [comment]
@sahilpatel342 sure, all the best wishes 👏

**Comment by alinagarib** [comment]
i would also like to be assigned to this issue

**Comment by anasdevv** [comment]
Hey @fsansalvadore , I saw joy is interested in this, but I’d love to jump in too if it’s still open! I’m new to open source and think it’d be a great opportunity. Let me know what you think!

**Comment by arnav0805** [comment]
@JoyShaheb 
here is the corrected code
![Corrected code](https://github.com/user-attachments/assets/ee397435-0c87-4110-80ef-424590b059bc)
and if my code is correct plz accept in the pull request and it is not accepting my pull request due to some problems.

**Comment by Sumitmore161** [comment]
I would like to contribute in these issue can I do it ?
