### ISSUE TITLE
Cannot update "Email Auth" auth settings without setting a custom SMTP

### ISSUE THREAD

**Issue by subwaymatch** [supabase/supabase#2959]
# Bug report

## Describe the bug

In the authentication settings page of Supabase's dashboard (app.supabase.io/project/myproject/auth/settings), no option in Email Auth section can be changed without enabling custom SMTP. The `SMTP_ADMIN_EMAIL` field is set as required regardless of whether a user enables custom SMTP or not.

![image](https://user-images.githubusercontent.com/1064036/130940564-ea0139e6-e97e-4b86-8ab6-be3ca4785905.png)

![image](https://user-images.githubusercontent.com/1064036/130940640-5bef4c9e-579f-409b-8759-124fa0f771fc.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a project's Authentication settings page (app.supabase.io/project/myproject/auth/settings)
2. Change any of the options in Email Auth without enabling custom SMTP
3. Save changes

## Expected behavior

Changes are updated - the `SMTP_ADMIN_EMAIL` field must only be required if a user enables the custom SMTP option.

## Current Behavior

Nothing happens on the UI - no error message is displayed (other than the error message on the console).

## System information

- OS: Windows 10
- Browser Chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by kiyadotdev** [comment]
same sentiment here - love supabase! i'm also facing this issue for a project im workin on. 

@subwaymatch this may be super hacky and not recommended but a workaround i did was to take a look at the network call when the configs are loaded. i was able to find the following parameter: `MAILER_AUTOCONFIRM: false`

so what i did was inspect what kind of network call is made when changing a config. I found that `Enable Phone Signup` was working just fine. while inspecting the call, i saw it wa making a `PATCH` request to: `https://app.supabase.io/api/auth/<your db name>/config` with a body of `{"EXTERNAL_PHONE_ENABLED":false}`

I edited this call in my network tab and changed the body to: `MAILER_AUTOCONFIRM: true` and sent the request. the request was successful. when i refreshed my authentication settings on the dashboard, the `Enable email confirmations` was toggled off.

**Comment by estevanjantsk** [comment]
Yep, this one is kinda critical =)

**Comment by AsafAgranat** [comment]
Same here. But in my case I can't seem to save any of the settings in that section, regardless of the SMTP toggle. The 'Save' button just isn't doing anything.

**Comment by Nick-Mazuk** [comment]
> in my case I can't seem to save any of the settings in that section, regardless of the SMTP toggle. The 'Save' button just isn't doing anything.

I'm seeing that, too

**Comment by w3b6x9** [comment]
hello everyone, this has been fixed!
