### ISSUE TITLE
Failed to retrieve account information Error: User's profile not found  Try refreshing your browser, but if the issue persists, please reach out to us via support.

### ISSUE THREAD

**Issue by Thakshara2** [supabase/supabase#29778]
![{BE11F352-D923-412A-907A-097EE9E5F2BE}](https://github.com/user-attachments/assets/ed2f5422-1585-4865-b4e4-5032a881fc3e)

**Comment by Hallidayo** [comment]
Hi @Thakshara2 - I've just tried this my end and I seem to be able to load my profile without the error in your screen shot.

This looks like an issue that support can help you outwith, please send an email to [support@supabase.io](mailto:support@supabase.io) and we'll have a look! 

Thank you for opening the issue!
