### ISSUE TITLE
Failed to retrieve account information Error: User's profile not found

### ISSUE THREAD

**Issue by dzurrahman** [supabase/supabase#29779]
Failed to retrieve account information
Error: User's profile not found

![image](https://github.com/user-attachments/assets/3d996f72-07ba-4be3-b54c-672b080c95c5)

can't send report to

![image](https://github.com/user-attachments/assets/a271f73a-c14d-4a2b-8dcc-e6fb550b2590)

username : dzurrahman.ibrahim@greatdayhr.com

**Comment by ryankontos** [comment]
Also experiencing this. Tried multiple new accounts, same issue.

**Comment by winsonloh** [comment]
I can't create any organization too

**Comment by solema247** [comment]
Same

**Comment by marcmarq** [comment]
> I can't create any organization too

me too

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by ByteGG** [comment]
Hey I have the same issue how I can solve that? This makes zero sense!
