### ISSUE TITLE
Cannot create organization ( infinite loop)

### ISSUE THREAD

**Issue by HassanMehdi03** [supabase/supabase#29786]
<img width="960" alt="supabse issue" src="https://github.com/user-attachments/assets/4344233c-6a7f-46f7-abfe-05ba92b9224e">

**Comment by DavidBadura** [comment]
I have exactly the same problem. I can see in the console that my profile cannot be found. I also see this message in the account overview. I am instructed to create a ticket if the problem still exists, but when I create the ticket I have to specify an organization that I don't have.

**Comment by HassanMehdi03** [comment]
> I've faced this problem, too. I think I made a mistake in creating my account. I selected "sign in" and "Continue with GitHub" but I should have selected "sign up " and "Continue with GitHub".

Did not work for me

**Comment by HassanMehdi03** [comment]
> I have exactly the same problem. I can see in the console that my profile cannot be found. I also see this message in the account overview. I am instructed to create a ticket if the problem still exists, but when I create the ticket I have to specify an organization that I don't have.

Have you found any solution ?

**Comment by DavidBadura** [comment]
No, I wanted to try supabase. But after seeing how many issues exist only in this github repo that the service is not available, I decided not to use it.

**Comment by HassanMehdi03** [comment]
> No, I wanted to try supabase. But after seeing how many issues exist only in this github repo that the service is not available, I decided not to use it.

Do you know any other alternative ? I wanted to use this as an alternative of Google Firebase but this one also did not work for me

**Comment by Decryptus007** [comment]
I'm experiencing the same issue, any help?

**Comment by HassanMehdi03** [comment]
> I'm experiencing the same issue, any help?

Not yet.

**Comment by Decryptus007** [comment]
Alright, i hope the devs resolve this quickly

**Comment by GaryAustin1** [comment]
https://status.supabase.com/incidents/f6rzxqqvxcpk

**Comment by HassanMehdi03** [comment]
> Hey,
> 
> Thanks for flagging. A fix has been put out - could we trouble y'all to try again and let us know if there are issues?

Thanks. Everything is working fine now....

**Comment by solema247** [comment]
> Hey,
> 
> Thanks for flagging. A fix has been put out - could we trouble y'all to try again and let us know if there are issues?

Still seeing same issue unfortunately

**Comment by HassanMehdi03** [comment]
> I'm still seeing the same issue

I’m not sure how, but I tried signing up from my mobile browser, and it worked.

**Comment by saltcod** [comment]
If you're still seeing this @solema247 could you try a hard refresh / incognito window? 
If still seeing an issue, could you screenshot any console/network errors please?

**Comment by saltcod** [comment]
Closing as this should be addressed now.
