### ISSUE TITLE
Failed to create user: Database error creating new user

### ISSUE THREAD

**Issue by HassanMehdi03** [supabase/supabase#29815]
![Screenshot (4)](https://github.com/user-attachments/assets/c878b111-a0b4-487c-8b4e-27aa07ea19d4)

**Comment by Sumitmore161** [comment]
I think I can work on it, please assign me this issue

**Comment by HassanMehdi03** [comment]
> I think I can work on it, please assign me this issue

Sorry, bro, I just give up on this database. I'm switching back to Firebase.
