### ISSUE TITLE
Missing documentation for local config

### ISSUE THREAD

**Issue by vm273** [supabase/supabase#29821]
# Improve documentation

## Link 

[## Link ](https://supabase.com/docs/guides/local-development/cli/customizing-email-templates)

## Describe the problem

The documentation for customizing email templates is missing (there is a link to it on this page: https://supabase.com/docs/guides/auth/auth-email-templates)

## Describe the improvement

I think that page should exist :)

## Additional context

![image](https://github.com/user-attachments/assets/5fa4a921-9f87-4dcb-8c7f-73b93832fe9a)

**Comment by charislam** [comment]
Thanks for the catch! Forgot a redirect there. Correct page is https://supabase.com/docs/guides/local-development/customizing-email-templates
