### ISSUE TITLE
Magic Link Error - AWS account has been paused

### ISSUE THREAD

**Issue by sandypockets** [supabase/supabase#2983]
# Bug report

## Describe the bug

Magic link email does not send, and returns an error in the logs, stating the AWS account has been paused. 

Checking the logs in the Supabase dashboard (**Authentication > Settings > Logs**), there is an error message that reads:

`time="2021-08-29T00:21:24Z" level=error msg="500: Error sending magic link" component=api error="Error sending magic link email: gomail: could not send email 1: 554 Message rejected: Sending paused for this account. For more information, please check the inbox of the email address associated with your AWS account." method=POST path=/magiclink referer="http://localhost:3000/" remote_addr=XXXXXXXXX request_id=c88db66d-18a5-4786-aa5a-314a2b33b547`

It seems this might be related directly to Supabase's AWS account, and not my specific Supabase account.

## To Reproduce

My Supabase Infrastructure settings are:
* AWS
* us-east-1

The snippet I have been using for login is:

```javascript
  const handleLogin = async (email) => {
    try {
      setLoading(true)
      const { error } = await supabase.auth.signIn({ email })
      if (error) throw error
      alert('Check your email for the login link!')
    } catch (error) {
      alert(error.error_description || error.message)
    } finally {
      setLoading(false)
    }
  }
```

The alert in the catch fires, and reads: `Error sending magic link`

1. Try to login or sign up using a magic link. 
2. Click submit to send the magic link.
3. Note the magic link is not sent
4. Check logs in **Authentication > Settings > Logs**, note failure message

## Expected behavior

The magic sign up link will be emailed, and a success message with be displayed instead of the error message. 

## Screenshots

![](https://i.imgur.com/are6ZZv.png)

## System information

- OS: mac OS
- Chrome, Safari
- Version of supabase-js: 1.21.0
- Version of Node.js: 14.17.0

**Comment by Aast12** [comment]
Also happening to me in all email sign ups with email confirmation + disabling email confirmation toggle from the dashboard is broken.

**Comment by DiegoJRR** [comment]
Also happening to me

**Comment by tinjaw** [comment]
me2
subscribing to issue

**Comment by w3b6x9** [comment]
Thank you everyone for bringing this to our attention!

We are actively trying to sort this out and will post an update here as soon we bring our email server back online. In the meantime, you can use mailgun/sendgrid/third party provider, go to https://app.supabase.io/project/[YOUR_PROJECT_REF]/auth/settings, and set it under `Enable Custom SMTP`.

**Comment by tinjaw** [comment]
> In the meantime, you can use mailgun/sendgrid/third party provider, go to [https://app.supabase.io/project/[YOUR_PROJECT_REF]/auth/settings](https://app.supabase.io/project/%5BYOUR_PROJECT_REF%5D/auth/settings), and set it under `Enable Custom SMTP` to continue sending auth-related emails.


Glass half-full !! This was the impetus I needed to finally get my mailgun account set up properly.

**Comment by kodewilliams** [comment]
Made use of Sendgrid [verified senders](https://app.sendgrid.com/settings/sender_auth/senders) with the SMTP settings as follows:

- Host: smtp.sendgrid.net
- Port: 465
- User: apikey
- Password: <API key>
- SMTP Sender Name: <Some display name>

Thanks for the tip!

**Comment by inian** [comment]
Hi everyone, sorry about this. The incident has been resolved on our side now. Please reopen the issue if there are any further problems.

**Comment by ETMitch21** [comment]
I just signed up, followed the Angular getting started guide and sent one email. Now any further magic links I am trying to send is providing me this error.
