### ISSUE TITLE
Unable to create foreign key on user auth table

### ISSUE THREAD

**Issue by kiyadotdev** [supabase/supabase#2984]
# Bug report

## Describe the bug

I'm trying to run a DB migration. When running the following query in the SQL editor on my supabase dashboard, it works with no issues:

```sql
CREATE TABLE "admins" (
  "id" bigserial PRIMARY KEY,
  "email" varchar,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "admins" ADD FOREIGN KEY ("email") REFERENCES "users" ("email");
```

When I run the same query via a migration i get the following error:

```
Error: pq: relation "users" does not exist
```

I began to look for the name of the users authentication table that supabase gives out of the box (love this) and was able to find this: https://github.com/supabase/supabase/blob/master/docker/dockerfiles/postgres/auth-schema.sql#L5

```sql
-- auth.users definition
CREATE TABLE auth.users (
...
}
```

So I tried replacing my foreign key entry to:

```sql
ALTER TABLE "admins" ADD FOREIGN KEY ("email") REFERENCES "auth.users" ("email");
```

But was still seeing the error. Is there a correct way to reference this table outside of the dashboard? 

Another thought I had was I'm connecting to my database with the postgres user and password. Then i thought maybe the possible the postgres user doesn't have access to the auth schema but saw the following line:

```sql
GRANT ALL PRIVILEGES ON SCHEMA auth TO postgres;
```

Any assistance here would be super appreciated!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use https://github.com/amacneil/dbmate as a db migration tool
2. run `dbmate new init` to generate a new migration file
3. Insert the query above to the migration file
4. Run `dbmate -u <supabase connection string> up`
5. See error

## Expected behavior

The expected behavior is to see the migration run successfully. When taking out the foreign keys referencing the users auth table, the migration runs successfully and I'm able to see my table in my supabase dashboard.

## System information

- OS: macOS

## Additional context

N/A

**Comment by w3b6x9** [comment]
@kiyadotdev 

> Another thought I had was I'm connecting to my database with the postgres user and password.

Just wanted to confirm that you did try the migration with `postgres` user and it still wasn't working?

I believe every Supabase project's database grants `postgres` role privileges on the `auth` schema and all the tables in the `auth` schema so running your migration with `postgres` user and password should work.

**Comment by kiyadotdev** [comment]
@w3b6x9 thanks for the quick response! yes - i connected with the postgres user and password made when first creating the db. this didn't work unfortunately:/

I'm currently trying to do a pg_dump to see if the auth table is possibly named differently? although i find that unlikely since the migration works just fine in the supabase dashboard

**Comment by w3b6x9** [comment]
@kiyadotdev `auth` is not set in `postgres` role's `search_path`, while it is set in the Supabase dashboard's SQL editor role, so you'll have to properly format the auth table (`"auth.users"` -> `"auth"."users"`).

Try the following with the correct schema-qualified table format:

`ALTER TABLE "admins" ADD FOREIGN KEY ("email") REFERENCES "auth"."users" ("email");`

**Comment by kiyadotdev** [comment]
@w3b6x9 That worked! thanks a lot! 💯 🚀

**Comment by w3b6x9** [comment]
@kiyadotdev you got it!
