### ISSUE TITLE
Storage > Files > Create(Upload) cannot be operated unless you have administrative privileges or higher.

### ISSUE THREAD

**Issue by abe-tk** [supabase/supabase#29912]
# Improve documentation

Storage > Files > Create(Upload) cannot be operated unless you have administrative privileges or higher.

## Link 

* [Supabase Platform Access Control: Project Permissions Breaking Changes on October 15, 2024 ](https://github.com/orgs/supabase/discussions/29494)

## Describe the problem

I didn't see “Storage” > “Files” in the table of the above link, is this change correct?

## Describe the improvement

If there has been a change in storage access privileges, I'd like the table in the link to be updated.
If there has been no change, make Storage > Files > Create(Upload) operable with developer privileges.

## Additional context

“Upload files” is inactive with developer permissions.

<img width="471" alt="スクリーンショット 2024-10-16 17 59 27" src="https://github.com/user-attachments/assets/145e061c-67d7-46e0-8d4b-00f446e25d50">

**Comment by GaryAustin1** [comment]
Maybe this fix coming: https://github.com/supabase/supabase/pull/29937

**Comment by abe-tk** [comment]
@GaryAustin1 
Thank you for your support!
I've confirmed that I can perform the operations with developer privileges, so I will close this issue.
