### ISSUE TITLE
Supabase guide on self hosting couldn't find that page

### ISSUE THREAD

**Issue by Shinon2023** [supabase/supabase#29949]
# Improve documentation

## Link 

[Supabase guide on self hosting](https://supabase.com/docs/docs/guides/self-hosting/docker#running-supabase)

## Problem

404: We couldn't find that page
Sorry, we couldn't find that page. It might be missing, or we had a temporary error generating it.

**Comment by charislam** [comment]
Thanks for the report, @Shinon2023! Do you happen to remember where you clicked the link from? The correct one should be https://supabase.com/docs/guides/self-hosting/docker

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to not being able to find the link in the codebase. Please feel free to reopen if you’re still having issues here or open a new issue.
