### ISSUE TITLE
SQL Query Editor - Output panel not scrollable

### ISSUE THREAD

**Issue by onmax** [supabase/supabase#30002]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The output of the query panel is not scrollable when an error is shown

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a function that contains an error super long

## Expected behavior

I want to see the whole error

## Screenshots

<details><summary>Before</summary>
<p>

![image](https://github.com/user-attachments/assets/397fc5cd-83d2-43c0-b2fc-0bedb79f1585)

</p>
</details> 

Applying the following classes should fix the problem (not sure if the container is being used somewhere else):

1. `bg-table-header-light [[data-theme*=dark]_&]:bg-table-header-dark`: Add `h-full`
2. The direct child of that element with class `flex flex-row justify-between items-start py-4 px-6 gap-x-4`, add `h-full overflow-y-auto`

<details><summary>After</summary>
<p>

![image](https://github.com/user-attachments/assets/4775be94-e51c-4502-9782-cdd76086e4e6)

</p>
</details> 
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

Thanks!

**Comment by saltcod** [comment]
Thanks for the report — going to close this one as we're about to release a new version of this entire editor.
