### ISSUE TITLE
100% CPU problem

### ISSUE THREAD

**Issue by IRediTOTO** [supabase/supabase#3001]
# Bug report
hi, I am running into a 100% CPU problem, now I am still on dev. Everything is running fine, but this could be a problem in the future.
## Describe the bug
I am using NextJS and Prisma, I have config to connect Prisma like this which use Supabase pooling connection 
`postgresql://postgres:xxx@db.xxx.supabase.co:5432/postgres?pgbouncer=true`
![image](https://user-images.githubusercontent.com/15695252/131279966-e5a8f7de-8f8f-45ce-8907-d6f290373ae0.png)

```
let prm: PrismaClient

if (process.env.NODE_ENV === 'production' && typeof window === 'undefined') {
    prm = new PrismaClient()
    prm.$use(transformUpdateAt)
} else {
    if (!global.prisma && typeof window === 'undefined') {
        global.prisma = new PrismaClient()
    }
    global.prisma.$use(transformUpdateAt)

    prm = global.prisma
}
export default prm
```
I want to use Supabase official pack, but It can't be good as Prisma for now. I just don't know why CPU 100%, I just run on localhost now, even nothing run, CPU still 100%. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository.
My database is still very small and simple design now :\ I don't think that is a problem with query SQL. performance

I don't know why, just normal code. I just tried to call 1 query, nothing much.

## Expected behavior

CPU run normal not 100%
## Screenshots
![image](https://user-images.githubusercontent.com/15695252/131276659-4c11ed47-35fe-4a55-b224-50117f1c5d4e.png)
![image](https://user-images.githubusercontent.com/15695252/131279577-b9defbe9-d76d-4e83-9721-3f519b853da1.png)

## System information

- OS: win 10
- Browser (if applies) Edge
- Version of supabase-js: newest
- Version of Node.js: 14.x
-

**Comment by darora** [comment]
@IRediTOTO can you email support@supabase.io with your project ref?

**Comment by darora** [comment]
Also, note that using that connstring does _not_ go through pgbouncer - you have to use the connstring on the https://app.supabase.io/project/{ref}/database/pooling page to do that (port 6543).

For prisma specifically, you'll still need the `?pgbouncer=true` at the end - we're in the process of adding this to our docs right now.

**Comment by IRediTOTO** [comment]
> Also, note that using that connstring does _not_ go through pgbouncer - you have to use the connstring on the [https://app.supabase.io/project/{ref}/database/pooling](https://app.supabase.io/project/%7Bref%7D/database/pooling) page to do that (port 6543).
> 
> For prisma specifically, you'll still need the `?pgbouncer=true` at the end - we're in the process of adding this to our docs right now.
I am using this db url 
```
postgresql://postgres:xxx@db.xxx.supabase.co:5432/postgres?pgbouncer=true
```

**Comment by kiwicopple** [comment]
for anyone visiting this, the string should be

`postgresql://postgres:xxx@db.xxx.supabase.co:6543/postgres?pgbouncer=true`

Note that the port is `6543` not `5432` for pgbouncer
