### ISSUE TITLE
new asynchronous `cookies()` in `nextjs 15`

### ISSUE THREAD

**Issue by rafadlis** [supabase/supabase#30021]
# Improve documentation

## Link 

- [Setting up Server-Side Auth for Next.js](https://supabase.com/docs/guides/auth/server-side/nextjs)

## Describe the problem

Since [`cookies()` in Next.js 15 is now asynchronous](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#cookies), the code must be written with the asynchronous `await cookies()`. I've tried changing the function to `async` and using `await cookies()`, but it doesn't work. I'm not an expert in `cookies` or `auth`, so I'm unsure how to resolve this. Could anyone help or guide me? I'm eager to use new Next.js 15 with supabase

## Describe the improvement

Perhaps you could consider adding a badge or button labeled `asynchronous cookies()`, or create a new tab next to the `App Router` tab at mentioned page (see in my ss).

## Additional context

![image](https://github.com/user-attachments/assets/f66a9f71-5b13-4c6c-aaea-b5c66a2fc05b)
![image](https://github.com/user-attachments/assets/5a6827a7-6780-4ca9-81e2-0ec4320e01b6)

**Comment by world1dan** [comment]
I fixed it by making supabase/server.ts `createClient()` function async and awaiting `cookies()`: 
```typescript
import { cookies } from 'next/headers'
import { createServerClient } from '@supabase/ssr'

export async function createClient() {
    const cookieStore = await cookies()
```

It will require you to await all createClient() calls on the server, but it's not a big deal since all of server components/actions are already async functions:

```typescript
import { createClient } from '@/utils/supabase/server'

export default async function ServerComponent() {
    const client = await createClient()
}
```

**Comment by zdarin** [comment]
> I fixed it by making supabase/server.ts `createClient()` function async and awaiting `cookies()`:
> 
> ```ts
> import { cookies } from 'next/headers'
> import { createServerClient } from '@supabase/ssr'
> 
> export async function createClient() {
>     const cookieStore = await cookies()
> ```
> 
> It will require you to await all createClient() calls on the server, but it's not a big deal since all server-side pages/actions are already async functions:
> 
> ```ts
> import { createClient } from '@/utils/supabase/server'
> 
> export default async function ServerComponent() {
>     const client = await createClient()
> }
> ```

Its right answer for NextJS 15 no errors

**Comment by Hallidayo** [comment]
Hi all - This recent pull request should help you out or give you steps to help with migrating to next.js 15: 

https://github.com/vercel/next.js/pull/71631

The with supabase example now has the above changes in so should be working with next.js 15.

**Comment by rafadlis** [comment]
> Hi all - This recent pull request should help you out or give you steps to help with migrating to next.js 15:
> 
> [vercel/next.js#71631](https://github.com/vercel/next.js/pull/71631)
> 
> The with supabase example now has the above changes in so should be working with next.js 15.

Thank you for the reference. I have reviewed the details provided in the [issue](https://github.com/vercel/next.js/pull/71631/files#diff-6a8269cbbac6bae651d255b582a7e9ff9bbe5b6996aa8a92b73abcd570820c36). Nextjs Official using same solution like @world1dan example. I hope Supabase update the docs

**Comment by charislam** [comment]
Thanks for raising the issue! The docs are updated now.

**Comment by RVP97** [comment]
How about the middleware that Supabase proposes for SSR, I have that setup with nextjs 15 and the cookies do not seem to be setting at all.

**Comment by rishimohan** [comment]
This setup works for me(notice the awaits for cookieStore):


`supabase/middleware.js`:
```
import { createServerClient } from "@supabase/ssr";
import { NextResponse } from "next/server";

export async function updateSession(request) {
  let supabaseResponse = NextResponse.next({
    request,
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        async getAll() {
          return (await request.cookies).getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(
            async ({ name, value }) => await request.cookies.set(name, value)
          );
          supabaseResponse = NextResponse.next({
            request,
          });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  // refreshing the auth token
  await supabase.auth.getUser();

  return supabaseResponse;
}
```

`supabase/server.js`:
```
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

export function createClient() {
  const cookieStore = cookies();

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        async getAll() {
          return (await cookieStore).getAll();
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(async ({ name, value, options }) =>
              (await cookieStore).set(name, value, options)
            );
          } catch {
            // The `setAll` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );
}

```
