### ISSUE TITLE
Next.js 15 not working with Supabase 

### ISSUE THREAD

**Issue by franckadil** [supabase/supabase#30030]
Issue: 

Dynamic APIs (cookies(), headers() and draftMode() from next/headers) are now asynchronous to be properly awaited or wrapped with React.use() if applicable. Supabase Next.js helpers are not yet compatible with Nextjs 15. 

### Dynamic APIs are:

The params and searchParams props that get provided to pages, layouts, metadata APIs, and route handlers.

- cookies(), draftMode(), and headers() from next/headers
- In Next 15, these APIs have been made asynchronous. 

### Error:

````console
[ Server ]  Error:  In route /test a cookie property was accessed directly with `cookies().get('supabase-auth-token')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
````

### For example:

```javascript
import { cookies, headers } from 'next/headers'
const token = cookies().get('token')
 
function useToken() {
  const token = cookies().get('token')
  return token
}
 
export default function Page() {
  const name = cookies().get('name')
}
 
function getHeader() {
  return headers().get('x-foo')
}

```

### Should transform into:

```javascript
import { use } from 'react'
import { cookies, headers, type UnsafeUnwrappedCookies } from 'next/headers'
 
const token = (await cookies()).get('token')
 
function useToken() {
  const token = use(cookies()).get('token')
  return token
}
 
export default function Page() {
  const name = (await cookies()).get('name')
}
 
function getHeader() {
  return (headers() as UnsafeUnwrappedCookies).get('x-foo')
}


```

**Comment by thallysondias** [comment]
same problem here

**Comment by rafadlis** [comment]
same problem, I just made issue to #30021

**Comment by franckadil** [comment]
Supbase Auth helpers package is in maintenance, and won't be improved. Supbase have transitioned to SSR instead. 

Just migrated from Supbase Auth-helper to the SSR package.

This will allow me to use Next.js dynamic APIs in my  auth/callback and confirm as well as in my Middleware.

Now Waiting for next.js 15 stability patches.

**Comment by Hallidayo** [comment]
Hi all - This recent pull request should help you out or give you steps to help with migrating to next.js 15: 

https://github.com/vercel/next.js/pull/71631

The with supabase example now has the above changes in so should be working with next.js 15.

**Comment by saltcod** [comment]
Closing as @Hallidayo has provided the right instructions. Thank you!

**Comment by Lemirq** [comment]
Thanks a lot @Hallidayo
