### ISSUE TITLE
cron job management page no longer works

### ISSUE THREAD

**Issue by penngrove** [supabase/supabase#30066]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I used to manage my cron jobs from this page linked from the pg_cron extension, but it no longer works. https://supabase.com/dashboard/project/[projectid]/database/cron-jobs

## To Reproduce

1. Go to https://supabase.com/dashboard/project/[projectid]/database/cron-jobs
2. You get the 404 page

## Expected behavior

There was a page to manage the cron jobs

## Screenshots

N/A

## System information

- OS: macOS
- Browser: chrome

## Additional context

N/A

**Comment by saltcod** [comment]
in the meantime @penngrove if you want early access, send us a support ticket with this url and I can add you!

**Comment by CodeWithAlamin** [comment]
I have noticed the same thing. Any solution yet?
