### ISSUE TITLE
Failed to enable vector: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by goranculibrk** [supabase/supabase#30073]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On a fresh installation, I can't enable vector extension. It happens in both studio and via psql. 

I've also tried both docker version and via supabase-cli. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open Studio
2. Go to Database -> Extensions
3. Find Vector. Try to enable on any schema (extensions, public, custom)
4. Receive error: **Failed to enable vector: Connection terminated unexpectedly**

Alternative:
1. Connect via PGAdmin or psql
2. Run CREATE EXTENSION vector;

The application has lost the database connection:
⁃ If the connection was idle it may have been forcibly disconnected.
⁃ The application server or database server may have been restarted.
⁃ The user session may have timed out.
Do you want to continue and establish a new session

## Logs
PostgreSQL Database directory appears to contain a database; Skipping initialization

172.18.0.5 2024-10-24 11:40:49.709 UTC [152] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:49.716 UTC [153] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.6 2024-10-24 11:40:49.824 UTC [157] authenticator@postgres FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:49.825 UTC [158] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:49.832 UTC [159] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:49.845 UTC [161] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:49.845 UTC [162] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:49.945 UTC [163] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:50.154 UTC [164] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:50.463 UTC [165] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.6 2024-10-24 11:40:50.838 UTC [166] authenticator@postgres FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:50.873 UTC [167] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.012 UTC [179] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.012 UTC [178] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.012 UTC [177] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.017 UTC [180] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.026 UTC [181] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.034 UTC [182] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.046 UTC [184] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.046 UTC [183] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.052 UTC [185] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.5 2024-10-24 11:40:51.101 UTC [186] supabase_admin@_supabase FATAL:  the database system is in recovery mode
172.18.0.13 2024-10-24 11:40:51.389 UTC [187] supabase_storage_admin@postgres FATAL:  the database system is in recovery mode
172.18.0.10 2024-10-24 11:40:51.530 UTC [193] supabase_admin@postgres FATAL:  the database system is not accepting connections
172.18.0.10 2024-10-24 11:40:51.530 UTC [193] supabase_admin@postgres DETAIL:  Hot standby mode is disabled.
172.18.0.10 2024-10-24 11:40:51.534 UTC [195] supabase_admin@postgres FATAL:  the database system is not accepting connections
172.18.0.10 2024-10-24 11:40:51.534 UTC [195] supabase_admin@postgres DETAIL:  Hot standby mode is disabled.
172.18.0.10 2024-10-24 11:40:51.537 UTC [194] supabase_admin@postgres FATAL:  the database system is not accepting connections
172.18.0.10 2024-10-24 11:40:51.537 UTC [194] supabase_admin@postgres DETAIL:  Hot standby mode is disabled.
172.18.0.10 2024-10-24 11:40:51.547 UTC [196] supabase_admin@postgres FATAL:  the database system is not accepting connections
172.18.0.10 2024-10-24 11:40:51.547 UTC [196] supabase_admin@postgres DETAIL:  Hot standby mode is disabled.
172.18.0.10 2024-10-24 11:40:51.549 UTC [197] supabase_admin@postgres FATAL:  the database system is not accepting connections
172.18.0.10 2024-10-24 11:40:51.549 UTC [197] supabase_admin@postgres DETAIL:  Hot standby mode is disabled.

## Expected behavior

As in previous versions, I expect to enable pgvector extension without problems.

## Screenshots
<img width="1369" alt="Screenshot 2024-10-24 at 13 35 07" src="https://github.com/user-attachments/assets/3f1841c7-30f5-4a71-86b3-34421b9d240f">

## System information

- OS: Ubuntu 24.04 server
- Latest version of docker-compose.yml

**Comment by encima** [comment]
Hi there,
Thanks for opening! The issue here seems to be unrelated to `vector` and is more about your database.
Are you running this locally or on supabase.com?

If using the hosted version, then please open a support ticket. Otherwise, we will need to find out why your database is in recovery mode. As long as that happens, it will be unable to accept writes or make changes.

**Comment by goranculibrk** [comment]
Hi @encima thanks for getting back to me. 

So, I think I figured it out earlier today. 

I'm running it locally. I set up a fresh Ubuntu 24.04 server, installed docker, and tried to run Supabase via docker-compose. As soon as I tried to do anything with db, it would go to recovery. 

Then I tried to run it using supabase-cli. And I got the same thing. Everything would be complete without errors; containers would be up and running, first interaction with DB would cause fatal errors.

And here comes the change.  

I was running docker and supabase-cli with `sudo`. And it would fail all the time. 

When I switched to the `root` user, everything ran okay. Why? I'm not sure. 

So I don't know if it's a bug or not.

**Comment by encima** [comment]
That is odd, thanks for reporting the fix. 

sudo means superuser do so running any command with that prefix will run it under the root user. Potentially there is some docker or unix bug that didn't apply to that a directory or some bind mount, I don't know. 

Glad you got it fixed though! We will close this one now. 

Also note that root is not a requirement to running containers, although it might be the default install when installing on ubuntu. Postman and rootless docker also exist, though they do need a bit more config.
