### ISSUE TITLE
PGSodium constraint causes local data dump to fail. 

### ISSUE THREAD

**Issue by YashNaj** [supabase/supabase#30087]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Getting a unique constraint error on a table with no table mentioned in the error message .

Upon inspection of the table I notice that it is pgsodium that is causing this (see screenshots)

## To Reproduce

1. supabase init 
2. supabase link --project-ref [ref# with pgsodium active] 
3. supabase db pull 
4. supabase db dump --local --data-only > supabase/seed.sql

## Expected behavior

Create a seed file with all data from my remote db.

## Screenshots

<img width="947" alt="Screenshot 2024-10-24 at 7 06 26 PM" src="https://github.com/user-attachments/assets/3909684c-c75b-45f7-be12-191a8f0a0127">

<img width="642" alt="Screenshot 2024-10-24 at 6 56 49 PM" src="https://github.com/user-attachments/assets/d153efcc-e33a-48ae-904c-ae1bad06bbba">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Thanks for this, pgsodium is being assessed as an extension. However, the error can be ignored and should create the data dump as expected.
Let us know if you have issues restoring it or using it as a seed file and we can re-open and investigate!
