### ISSUE TITLE
Unable to Use CURL APIs "405 Method Not Allowed"

### ISSUE THREAD

**Issue by dapomeranz** [supabase/supabase#30104]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I go to my projects API docs and copy the CURL request with my public anon key.

```
curl -X POST '[retracted].supabase.co/auth/v1/signup' \
-H "apikey: [retracted but public api key]" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "kZPMcgVvHOfzUQMuqDOD"
}'
```

I replicate to Postman and Bruno and get the same error. "405 Method Not Allowed"

```
< 405 Method Not Allowed
< date: Fri, 25 Oct 2024 16:51:58 GMT
< content-length: 0
< connection: keep-alive
< cf-ray: 8d83b6df88c21f46-DEN
< cf-cache-status: DYNAMIC
< allow: POST
< strict-transport-security: max-age=31536000; includeSubDomains
< vary: Origin, Accept-Encoding
< sb-gateway-version: 1
< x-envoy-attempt-count: 1
< x-envoy-upstream-service-time: 0
< server: cloudflare
< alt-svc: h3=":443"; ma=86400
```

I paste in my terminal and get a weird HTML response.

```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

I have also tried using an email on the domain from which the project is registered.

**Comment by Hallidayo** [comment]
Hi all - Where in the dashboard are you seeing the incorrect URL?

**Comment by GaryAustin1** [comment]
Looks like this had a PR done:  https://github.com/supabase/supabase/pull/30136

**Comment by GaryAustin1** [comment]
And I confirm fixed in my dashboard.
