### ISSUE TITLE
Broken ui on api api docs section

### ISSUE THREAD

**Issue by amanpoddar-dev12** [supabase/supabase#30119]
![Screenshot 2024-10-26 220247](https://github.com/user-attachments/assets/944f07af-fda0-4a10-8946-e7c6a7531e3b)
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by amanpoddar-dev12** [comment]
i was woking in supabase  when i go to api docs  it shows me incomplete ui and without any npm command and api url.

**Comment by Hallidayo** [comment]
Hi @amanpoddar-dev12 - Just coming back to this one. 

This was removed to be more concise, but there’s also the main api docs and the feature preview version as well. This [PR](https://github.com/supabase/supabase/pull/14275) is related. I'm going to close this now but thank you again for opening.
