### ISSUE TITLE
Unclear on how to get $PROJECT_ID

### ISSUE THREAD

**Issue by crowne** [supabase/supabase#30130]
# Improve documentation

## Link 

[Managing Environments](https://supabase.com/docs/guides/deployment/managing-environments)

## Describe the problem

The page seems to use a circular reference :

> You can get your $PROJECT_ID from your project's dashboard URL:
> `https://supabase.com/dashboard/project/<project-id>`

This implies that you need to know the project-id in order to find it.

Also I suspect that there is an inconsistent language being used,
when I go to the project dashboard I don't see PROJECT_ID, I do see PROJECT_URL and API_KEY.

If I select the Project Settings I see "Reference Id" ... is this the $PROJECT_ID which is being refferred to?

## Describe the improvement

Use consistent language, don't flip between PROJECT_ID and "Reference Id".
Provide a way to get the required variable tat does not depend on already knowing the variables value.

**Comment by Hallidayo** [comment]
Hi @crowne - Thank you for opening this issue, I can see the in-consistent naming in some areas. Personally I think Project ID should be used instead of Reference ID.  I'll flag it up and see what the best wording is come back to you 👍

**Comment by charislam** [comment]
Thanks for flagging @crowne! I can see how the wording is confusing, but what this means is that:

When you are on the Supabase dashboard and have selected your project, look at the URL, which will have the format `https://supabase.com/dashboard/project/abcdefghijklmnopqrst/...`

`abcdefghijklmnoopqrst` is then your project ID.

**Comment by Hallidayo** [comment]
@charislam - Is it worth changing Reference ID to Project ID in the project settings? If so I'm happy to open a PR.

**Comment by charislam** [comment]
@Hallidayo, I think that would be a good idea (as far as I know we usually refer to it as ProjectID anyway). Thank you! 🙏🏼

**Comment by dashpacket** [comment]
My Supabase project not finding. How to find? I am unable to see in my Supabase folder as I have not created any project.
