### ISSUE TITLE
Setting up server side auth for Next.js may be out of date for Next.js 15

### ISSUE THREAD

**Issue by richleach** [supabase/supabase#30176]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)]https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs?queryGroups=language&language=ts

## Describe the problem

This documentation may need attention, as I have followed the instructions to implement server side authentication for the new version of Nextjs 15 and can not get authentication to work as expected. I receive 307 status codes and troubleshooting is yielding inconsistent results. See below for details.

## Describe the improvement

I guess I'll just start with a question, do any of the steps listed in this documentation need updating for Next.js 15? And has anyone implemented this functionality with Nextjs 15 yet? I have successfully implemented this documentation several times with Next version 14 but can't get it to run on version 15....

Specifically I created a new database project in Supabase successfully.  I then followed the steps in the documentation and  created / copied the components into my application as they exist in the docs. The site runs with "npm run dev" and the pages pull up "localhost:3000/login" just fine. On the login page when I enter a new email and password and then click the Sign Up button and while I get the email requesting that I confirm the sign up, I get the app displaying "Sorry, something went wrong" with this message being reported in the console: "GET /auth/confirm?token_hash=pkce_83bed768ecf36646b4c209ca6b95757f010563b52b592b292e73f37c&type=email 307 in 670ms"

I'm happy to continue debugging this but just wanted to make sure the docs didn't need an update before I go pulling cookies out of my browser, etc....

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by charislam** [comment]
Hi @richleach, there were some breaking changes in Next.js 15. We've already adapted some of our guides and are in the process of adapting others (including the one you had trouble with).

The main change is that `cookies()` is now asynchronous, so you will need to adapt your server-side `createClient` accordingly. If you need help, you can take a look at [this guide](https://supabase.com/docs/guides/auth/server-side/nextjs), which we've already updated.
