### ISSUE TITLE
Update docs to emphasise that service_key should only be used on server-side

### ISSUE THREAD

**Issue by kangmingtay** [supabase/supabase#3018]
# Improve documentation
If a user wants to perform delete-user requests (https://supabase.io/docs/reference/javascript/delete-user) using supabase-auth, the request must be made from the server side so that the service_key is not exposed.

**Comment by kiwicopple** [comment]
For anyone who would like to contribute, the resolution to this is to update this block of code:

https://github.com/supabase/gotrue-js/blob/819c3d2e5b4262aae76c38af69a13986fa6c42a3/src/GoTrueApi.ts#L348

to 
```
/**
   * Delete an user. Requires a `service_role` key. 
   * 
   * This function should only be called on a server. Never expose your `service_role` key in the browser. 
   * 
   * @param uid The user uid you want to remove.
   * @param jwt A valid JWT. Must be a full-access API key (e.g. service_role key).
   */
```

**Comment by masihtamsoy** [comment]
Hi, want to pick this up.

**Comment by karan316** [comment]
I've created a [PR](https://github.com/supabase/gotrue-js/pull/139/files). @kiwicopple please check out.

**Comment by kiwicopple** [comment]
Thanks again @karan316 ! You're getting through all the issues 

I've merged your PR and will close this issue - the docs will auto-update the next time gotrue-js is released
