### ISSUE TITLE
Delete does not throw an error when RLS is enabled and there is no delete policy

### ISSUE THREAD

**Issue by sarthakgupta072** [supabase/supabase#30190]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I enabled RLS for one of my tables say "profiles".

When I execute this code 
```
const { error: deleteError, data } = await supabase
      .from("profiles")
      .delete()
      .eq("user_id", userId)
```

As expected, nothing gets deleted from my DB due to RLS enabled and no policy for delete. But, I also don't see any error in `deleteError` variable. I was expecting it to throw error something like "Error in deleting items due to RLS"

Is this expected?

## To Reproduce

Mentioned above

## Expected behavior

I was expecting it to throw error something like "Error in deleting items due to RLS".

## System information

- OS: MacOS
- Browser: Brave
- Version of supabase-js: 2.45.3
- Version of Node.js: 18.20.4

**Comment by GaryAustin1** [comment]
This is not a bug.  Postgres does not error on delete/update if it can't see the row.
