### ISSUE TITLE
Supabase Not pulling all data or ignoring data

### ISSUE THREAD

**Issue by EasternIndustries-IT** [supabase/supabase#30200]
## Describe the bug
I have a few parts in a table called stock_part_numbers. It pull majority of the parts
I'm using nextjs framework for the front end type script. When running the command in the sql editor I get the part or parts like "18-216" 
 
but if I run the command from nextjs I get an empty array
This is the full function 
```
export async function GetAllStock(page: number, pageSize: number, searchTerm: string = "18-",selectedCategories: string[] ) {
  const supabase = createClient();

  let query = supabase
    .from('stock_part_number')
    .select('*')
    .ilike('id', `%${searchTerm}%`) // Use ilike for case-insensitive search
    .range(page * pageSize, (page + 1) * pageSize - 1); // Adjust range for pagination


  // Add category filter if selectedCategories is not empty
    if (selectedCategories.length > 0) {
      query = query.in('category_id', selectedCategories); // Filter by selected categories
    }

    const { data, error } = await query;
console.log(searchTerm)
console.log(data)
  if (error) SupabaseDBError(error);
  return data;
}
```

but if I narrow it down and just search for what i'm looking for its still blank
![image](https://github.com/user-attachments/assets/529d5d8f-9647-418e-a573-42ed2e1cff5b)

```
export async function GetAllStock(page: number, pageSize: number, searchTerm: string = "18-",selectedCategories: string[] ) {
  const supabase = createClient();

  let query = supabase
    .from('stock_part_number')
    .select('*')
    .ilike('id', `18-216`)

    const { data, error } = await query;
  if (error) SupabaseDBError(error);
  return data;
}
```

 I should get results like the image below but I don't receive anything 
![image](https://github.com/user-attachments/assets/a783f25b-b732-40ee-90d6-fcff75eccecf)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

dataset is around 6,788 records which there are other tables I need with lots more

## Expected behavior
Pull all data

- OS:
PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
- Version of supabase-js docker images used
- supabase/studio:20240923-2e3e90c
- kong:2.8.1
- postgrest/postgrest:v12.2.0
- supabase/storage-api:v1.10.1
- supabase/gotrue:v2.158.1
- darthsim/imgproxy:v3.8.0
- supabase/postgres-meta:v0.83.2
- supabase/edge-runtime:v1.58.3
- supabase/logflare:1.4.0
- supabase/postgres:15.1.1.78
- timberio/vector:0.28.1-alpine
- supabase/supavisor:1.1.56
- Version of Next.js: [14.2.13]

**Comment by GaryAustin1** [comment]
This is common when you have RLS enabled and don't meet your select policy.
This seems like would be more appropriate as a discussion or Discord topic for users to help you as it is unlikely a but.

**Comment by EasternIndustries-IT** [comment]
Its not. I disabled RLS and i still get no results to a row i know is in there.

**Comment by GaryAustin1** [comment]
This test has no wild cards...
![image](https://github.com/user-attachments/assets/91e4c9ef-5a8e-4b4f-bcfe-1b75c1b9802c)

Do you get rows if you you just do .select('*') with no filter?

**Comment by EasternIndustries-IT** [comment]
Turns out the issues is the offset using .range
