### ISSUE TITLE
Theme blinking from classic-dark to classic and back

### ISSUE THREAD

**Issue by shahsuvarli** [supabase/supabase#30222]
# Bug report

When I switch the web ui theme from light to classic dark, it keeps switiching from dark to classic-dark and back. you can check the video attached as well

https://github.com/user-attachments/assets/9b027fdc-1954-44be-a8f5-cd1c76afc583

**Comment by Hallidayo** [comment]
Hi @shahsuvarli - Thank you for opening this issue. Are you still experiencing this switching of the theme? I've been trying to recreate over the last couple of days but I have been unable to? Do you know what browser/version that you are using?

**Comment by Hallidayo** [comment]
Hi, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by varun-it25** [comment]
Its happening again.

**Comment by kvog001** [comment]
I am experiencing the same issue on Safari, Version 26.0.1 (21622.1.22.11.15).

https://github.com/user-attachments/assets/633f8c34-0e64-4c0b-879f-74ea254d9687

**Comment by wvha** [comment]
I am having the same issue on Safari Version 18.6 (20621.3.11.11.3)
