### ISSUE TITLE
Domain cookie option does not set with SSO

### ISSUE THREAD

**Issue by kmalloy24** [supabase/supabase#30279]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a Sveltekit project set up with Supabase SSR following [the guide in the docs](https://supabase.com/docs/guides/auth/server-side/sveltekit). I'm trying to setup cross-origin auth with an Astro project at a subdomain. 

## To Reproduce

I've modified the `hooks.server.ts` to include the domain within `setAll` when creating the server client.

```ts
event.locals.supabase = createServerClient(
    PUBLIC_SUPABASE_URL,
    PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        getAll: () => event.cookies.getAll(),
        setAll: (cookiesToSet) => {
          cookiesToSet.forEach(({ name, value, options }) => {
            event.cookies.set(name, value, {
              ...options,
              path: "/",
              domain: ".app.localhost", // added this
            });
          });
        },
      },
    },
```

I'm calling the logins from actions in a `+page.server.ts`

```ts
// IMPORTS
import { error, redirect } from "@sveltejs/kit";
import type { Actions } from "./$types";

// ACTIONS
export const actions: Actions = {
  // PASSWORD LOGIN
  adminLogin: async ({ request, locals: { supabase } }) => {
    const formData = await request.formData();
    const email = formData.get("email") as string;
    const password = formData.get("password") as string;

    const { error: adminError } = await supabase.auth.signInWithPassword({
      email,
      password,
    });
    if (adminError) {
      error(500, "Error with password login");
    } else {
      redirect(303, "/");
    }
  },

  // SSO LOGIN
  ssoLogin: async ({ locals: { supabase } }) => {
    const { data, error: ssoError } = await supabase.auth.signInWithSSO({
      domain: "example.com",
      options: {
        redirectTo: "http://app.localhost:5173",
      },
    });

    if (ssoError) {
      error(500, "Error logging you in with SSO");
    }

    // Redirect the user to the identity provider's authentication flow
    if (data?.url) {
      redirect(302, data.url);
    }

    // Fallback in case no redirect happened
    redirect(303, "/");
  },
};
```

## Expected behavior

When I call `signInWithPassword` everything works as expected.

![382839154-ca7b3c45-93a0-407a-a16a-577a71af39e9](https://github.com/user-attachments/assets/3cff5806-5e28-4438-aaa1-3d0360933225)

## Actual behavior

But when I call `signInWithSSO` I get back:

![382839195-23bd3acc-7665-4dc2-9ab6-4ac04911bc92](https://github.com/user-attachments/assets/850d2087-e67a-4509-8473-f4d462047ceb)

I wouldn't get the `token-code-verifier` back when it was only doing same-origin auth before, just the split `auth-token`. Also, my `signOut` call doesn't clear the cookies anymore. It seems to clear the user, but not the session. I have it set up in a `+server.ts`.

```ts
import { error, redirect } from "@sveltejs/kit";
import type { RequestHandler } from "./$types";

export const POST: RequestHandler = async (event) => {
  const { error: logoutError } = await event.locals.supabase.auth.signOut();

  if (logoutError) {
    error(500, "Error logging you out. Please try again.");
  }

  redirect(302, "/");
};
```

## Redirects

I have the following set in the Supabase Dashboard and have read through the [redirects page in the docs](https://supabase.com/docs/guides/auth/redirect-urls).

```text
http://app.localhost:5173
```
## Hostnames

I have the following in my hosts file on windows. 

```text 
# Sveltekit app
127.0.0.1       app.localhost
# Astro app
127.0.0.1       sub.app.localhost
```
## System info

```
OS: Windows 11
Runtime: Node 20.18
Browser: Chrome

"@supabase/ssr": "^0.5.1",
"@supabase/supabase-js": "^2.46.1",
```

## Additional Context

I've tested in production at the live URL and the results are the same so it doesn't seem like an http issue or anything with the local setup. 

Any help would be very very much appreciated 🙏. This has been driving me nuts for weeks and is bottlenecking everything.

**Comment by hf** [comment]
One thing I'm noticing here which I didn't before is that your app is hosted on HTTPS and HTTP. Please only use *one protocol* -- HTTPS especially with SSO.

The code verifier cookie has the Secure attribute set, meaning it will not be sent to your app served over HTTP.

**Comment by kmalloy24** [comment]
I thought the same thing, so I tried it at my production link over HTTPS, but got the same result.

I did find a solution though by digging around in the network tab in chrome dev tools. 

The issue seems to be in the token exchange response on the redirect back from the IdP. 

1. Initial SSO Request:
`POST http://app.localhost:5173/?/ssoLogin`

- Sets `code_verifier` cookie on `.app.localhost`
- Successfully redirects to IdP

2. SAML Response:
`POST https://<project-id>.supabase.co/auth/v1/sso/saml/acs`

- Processes SAML response from IdP
- Redirects back with auth code

3.  Code Exchange:
`GET http://app.localhost:5173?code=<auth-code>`

- Tries to exchange auth code for tokens
- Cookie domain mismatch occurs because:
	- `code_verifier` is on `.app.localhost`
	- auth tokens try to set on `app.localhost`

The issue is that the initial SSO request correctly sets the code verifier cookie on `.app.localhost` (with dot prefix), but when Supabase tries to set the auth tokens, it's using `app.localhost` (without dot prefix), causing a domain mismatch.

By using a callback route for the redirect I'm able to get it to work even over HTTP with the Secure attribute set.

```ts
import { error, redirect } from "@sveltejs/kit";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async ({ url, locals }) => {
    const code = url.searchParams.get("code");

    if (!code) {
        error(400, "No authorization code provided");
    }

    const { error: tokenExchangeError } = await locals.supabase.auth
        .exchangeCodeForSession(code);

    if (tokenExchangeError) {
        error(400, "Failed to exchange authorization code for session");
    }

    redirect(303, "/");
};
```

Since `signInWithSSO` works as expected when the Domain attribute is unchanged, I'm not sure if this is a bug with `supabase-js` or `ssr`, or if the need for a callback should just be documented somewhere.

Even before trying to change the Domain attribute I was having an issue with the session not coming back with the SSO redirect until I triggered a full page reload, and this callback also fixed that issue.
