### ISSUE TITLE
Rate-limiting API access

### ISSUE THREAD

**Issue by Nectres** [supabase/supabase#3028]
# Feature request

I was about to use Rate-limiting in my App. I looked into Kong's Documentation and tried to connect to the mentioned Admin API. It sent back a 404 - No matching routes found. When I searched a little more, I stumbled across this repo: [Supabase Admin API](https://github.com/supabase/supabase-admin-api) which was a perfect for me. But again, I received 404 for routes in the repo's readme. After talking to some people in Supabase's Discord server, I learnt that it was just for self-hosted Supabase?? ( Or am I missing something? ) 

## Is your feature request related to a problem? Please describe.

No, but I can't configure any of the services and implement features like rate-limiting in Kong if I decide to go with the hosted solution. This would make Supabase a lot more configurable for folks who want it.

## Describe the solution you'd like

[Supabase Admin API](https://github.com/supabase/supabase-admin-api) being bundled together with Supabase

## Describe the alternatives you have considered
Maybe allow installing it like an addon with something like "Allow Admin API" button in the Settings.

**Comment by darora** [comment]
Hey @Nectres - we currently don't allow access to the Admin API on our hosted offering for security reasons. However, we're going to be looking into offering support for rate-limiting at some point in the next few months. I don't have a concrete timeline for it, though.

**Comment by Nectres** [comment]
Hmm alright then, hopefully soon!

**Comment by regtm** [comment]
Are there any plans to implement access to rate limiting yet?
