### ISSUE TITLE
`signIn` with just an email creates new auth.users account

### ISSUE THREAD

**Issue by richcorbs** [supabase/supabase#3033]
With signUp enabled or disabled, calling `signIn` with just an email address creates a new `auth.users` account and sends the confirmation email or magic link depending on the email confirmation setting.

## To Reproduce

1. With signUp enabled or disabled.
2. Call `supabase.auth.signIn` with just an email address that doesn't already exist in auth.users table.
3. Go to the dashboard Authentication > Users.
4. Note that there is a new user "waiting for confirmation".

## Expected behavior

I would expect either:

(1) There to be a setting to opt out of having magiclink create a new auth.user automatically if one doesn't exist.

OR

(2) That signIn NEVER creates a new auth.users account. That's what signUp is for. Right?

**Comment by MaxAst** [comment]
I believe this issue is already open, see #1176

**Comment by richcorbs** [comment]
Thanks @MaxAst! Don't know how I didn't find that in my searching.

Duplicate of #1176. Closing
