### ISSUE TITLE
cannot signin with phone number and password 

### ISSUE THREAD

**Issue by cuongnv-dev** [supabase/supabase#3034]
I'm using phone number for authentication.
The signup method requires phone number and password. I have signup successfully with phone verification via Twilio SMS. But I cannot signin using phone and password. It throw error message: **'Unsupported email provider'**
`let { user, error } = await supabase.auth.signIn({ phone, password })`

**Comment by zernonia** [comment]
I believe you watch [SMS Login with Supabase Auth and Twilio](https://www.youtube.com/watch?v=akScoPO01bc) want found out this signIn using phone and password method. 

I've encountered the same problem with phone auth as well, but I've forgotten how I solved it. Try:
1.  Go to your Authentication settings
2.  Set Enable Email Signup to `allow`. 
3. Login using phone and password again.
