### ISSUE TITLE
Website not accessible 

### ISSUE THREAD

**Issue by Princewil** [supabase/supabase#30395]
I cant access the Supabase website.

**Comment by skdishansachin** [comment]
Please provide more information regarding your visit to the website. For example, did you encounter any error messages from your browser, such as "the site cannot be reached"?

According to the Supabase status page, all services are functioning well at the moment. You can check it out here - https://status.supabase.com/.

**Comment by Princewil** [comment]
<img width="1552" alt="Screenshot 2024-11-10 at 22 37 22" src="https://github.com/user-attachments/assets/9cfb6134-1b5e-441d-8e9e-4e6795980958">


Had to use a vpn to access my account

**Comment by encima** [comment]
Hey there, this seems to be a client side issue. Possibly blocking or some Firewall settings.

We will close this issue as it is not Supabase related but please do report if this issue is fixed for you or not!
