### ISSUE TITLE
Table editor modal does not resize on small screens

### ISSUE THREAD

**Issue by iacopo-schianchi** [supabase/supabase#30448]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On a small screen, the "Table Editor" modal in the editor page does not resize to fit the available width and overflows instead.

## To Reproduce

1. Go to `supabase.com/dashboard/project/.../editor`
2. Resize browser width until modal overflows.
3. See error

## Expected behavior

The modal is expected to resize its width instead of overflowing.

## Screenshots

<img src="https://github.com/user-attachments/assets/672c7b5f-23df-4e46-bea0-2946f64e3d24" alt="Screenshot of bug" width="400px">

## System information

- OS: Windows
- Browser: Google Chrome, Microsoft Edge

**Comment by Hallidayo** [comment]
Hi @iacopo-schianchi - Thank you for opening this one! At the moment the studio is only being targeted at desktop rather than mobile but may be looked at in the future. But again thank you opening this!
