### ISSUE TITLE
User not found error in offical Vue 3 example

### ISSUE THREAD

**Issue by talhabw** [supabase/supabase#3047]
# Bug report

## Describe the bug

I was trying to understand how auth works in Supabase. So I cloned the [Vue 3 example](https://github.com/zernonia/supabase-vue-3). But when I can't sign in. It sends magic link mail. But when I open this link, it redirects me to `http://localhost:3000/#error_code=404&error_description=User+not+found`. I can see the user in the database but I am still getting this error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the  [offical Vue 3 example](https://github.com/zernonia/supabase-vue-3)
2. Create a .env file
3. create VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY env variables
4. run `yarn dev`
5. go to localhost:3000
6. try to sign in
7. click the magic link in your inbox
8. see the error in redirect URL

## Expected behavior

I was expecting to sign in without error.

## System information

- OS: Windows
- Browser: Firefox
- Version of supabase-js: latest
- Version of Node.js: latest

## Additional context
Log of one of the sign in requests:
`time="2021-09-02T04:18:47Z" level=error msg="User not found" component=api method=GET path=/verify referer= remote_addr="8.39.214.15:39482" request_id=eac3f866-5e72-4d04-a241-4fc670314426`

**Comment by zernonia** [comment]
hi @talhabw , I'm the author of the Vue 3 Tutorial. Did you change any settings on the `Supabase Dashboard > Authentication`?

I've tested with supabase-js ^1.22.4 (latest), everything still works fine. Could you provide a some screenshot for this bug? Perhaps screenshot of `Devtools > Network`?

**Comment by talhabw** [comment]
Hi again. Apparently, it was my fault. I accidentally skipped the `Run User Management Starter` step. Sorry for inconvience.
