### ISSUE TITLE
deleteUser not fire `USER_DELETED` event in `onAuthStateChange`

### ISSUE THREAD

**Issue by ralphilius** [supabase/supabase#3049]
# Bug report

## Describe the bug

`USER_DELETED` AuthChangeEvent was not fired when user was successfully deleted

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Implemente `onAuthStateChange` method using NextJS
2. Delete the user with `supabase.auth.api.deleteUser`

## Expected behavior

`USER_DELETED` AuthChangeEvent to fire so that UI can be updated.

## System information

- OS: MacOS
- Browser (if applies): Chrome
- Version of supabase-js: ^1.22.3
- Version of Node.js: v14.17.4

**Comment by kiwicopple** [comment]
Hey @ralphilius - there is no `USER_DELETED` change event:
https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/lib/types.ts#L15

If you need this one, I can recommend adding a trigger to your `auth.users` table to trigger events on DELETE.

**Comment by ralphilius** [comment]
@kiwicopple is just a few lines below your reference 

https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/lib/types.ts#L21

**Comment by kav** [comment]
@kiwicopple any chance we can reopen this? Tripped over it myself just now. Given the USER_DELETED AuthChangeEvent exists it's easy to do

**Comment by kiwicopple** [comment]
Hey @kav - can you please create a new issue for this? It's cleaner than reopening old issues

**Comment by kav** [comment]
Done! https://github.com/supabase/supabase/issues/10309
