### ISSUE TITLE
Trying to create a Function Hook with no tables causes an "unexpected error"

### ISSUE THREAD

**Issue by 06kellyjac** [supabase/supabase#3050]
# Bug report

## Describe the bug

Trying to create a Function Hook with no tables causes an "unexpected error"

> An unexpected error has occurred.

```
 TypeError: r[0] is undefined
    G Listbox2.js:70
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new project, don't touch the tables
2. Try create a Function Hook
3. An unexpected error has occurred

## Expected behavior

Nicer error handling

**Comment by w3b6x9** [comment]
@06kellyjac

> Nicer error handling

Got it, thanks for the feedback!

**Comment by kiwicopple** [comment]
👍 fixed!
