### ISSUE TITLE
Wrong parsing of schedule expressions in cron jobs

### ISSUE THREAD

**Issue by L3g7** [supabase/supabase#30529]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The cron expression `0 */2 * * * *` is displayed as `Every 2 minutes` (in the cron job overview; is correct), but the job runs every 2 hours.
When omitting the seconds (`*/2 * * * *`), the expression is still displayed as `Every 2 minutes` but now really runs every 2 minutes.

## To Reproduce

1. Go to a project dashboard -> Integrations -> Cron Jobs
2. Click on Create a new cron job
3. Enter `0 */2 * * * *` in the Schedule input
4. Create cron job
5. Wait
6. View previous runs

## Expected behavior

The job should run every 2 minutes, as per the expression and displayed schedule.

**Comment by saltcod** [comment]
Thanks for the report @L3g7  

Going to mark this one as closed, as we addressed it before we launched.  We now expect either standard cron syntax (with (5 *s) or seconds captured with syntax "n seconds"
