### ISSUE TITLE
Cron job creation tool generates wrong command

### ISSUE THREAD

**Issue by L3g7** [supabase/supabase#30528]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating a cron job using the [Create a new cron job]-Button in Dashboard -> Integrations -> Cron-jobs that invokes an edge function via HTTP GET, the generated net.http_get contains a `body` argument which it should not have, resulting in the following error:
```
ERROR:  function net.http_get(url => unknown, headers => jsonb, body => jsonb, timeout_milliseconds => integer) does not exist
LINE 3:       net.http_get(
              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

## To Reproduce

1. Go to a project dashboard -> Integrations -> Cron Jobs
4. Click on Create a new cron job
5. Select Type = Supabase Edge Function and Method = Get
6. Create cron job
7. See wrong command

## Expected behavior

I expected the `body` argument to be omitted.

**Comment by GaryAustin1** [comment]
I worked with this user and confirm this is a bug.

**Comment by GaryAustin1** [comment]
@saltcod This should be fixed before launch...

**Comment by saltcod** [comment]
Yup thanks @GaryAustin1 on the radar.

**Comment by saltcod** [comment]
Marking this one as closed per https://github.com/supabase/supabase/pull/30721

thanks for the report!
