### ISSUE TITLE
Row level security for subscribe / real time

### ISSUE THREAD

**Issue by mike-wax** [supabase/supabase#3053]
I want to be able to stream data for changes for just the auth'd user. e.g. I have a table `cards` that has a `user_id` and team associated with each `card`. The user should only get changes for cards that belong to their team.

**Comment by w3b6x9** [comment]
@mike-wax this is in the works!

**Comment by mike-wax** [comment]
@w3b6x9 👍 

I think the docs should have a better security warning in the meantime. If you turn this on, you're basically streaming all your data changes to all your users. Something that risky should be in "flashing red lights".

**Comment by w3b6x9** [comment]
@mike-wax that's a great point! We already have a warning at https://supabase.io/docs/guides/auth#disable-realtime-for-private-tables but it can be hard to find. I'll add an additional warning to https://supabase.io/docs/guides/database#realtime as well.

**Comment by w3b6x9** [comment]
Just wanted to give everyone a heads up that we have a project codenamed **WALRUS** that will broadcast **Realtime** changes with respect to RLS. See [here](https://supabase.io/blog/2021/09/10/supabase-beta-august-2021#realtime-security-codename-walrus) for more context.

**Comment by mike-wax** [comment]
@w3b6x9 nice, thanks!

**Comment by w3b6x9** [comment]
@mike-wax gonna close this issue b/c i added the additional warning here: https://supabase.io/docs/guides/database#realtime.
