### ISSUE TITLE
Gmail reporting Supabase subdomains as suspicious links

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase#3055]
# Bug report

## Describe the bug

Started to receive then message when clicking Supabase confirm and magic password links in Gmail:

![image](https://user-images.githubusercontent.com/65471523/131934509-f7c328b5-9a42-40d4-a995-aadd09029376.png)

I suspect it's due to the length and randomness of the subdomain that their AI is flagging. 

Recommendation would be to implement a [compound word generator](https://www.npmjs.com/package/namor) rather than complex long string.

## To Reproduce

May be hard to reproduce if the filter is semi-dynamic, but seems to be affecting new URLs recently created.
 
 

## System information

- App: Gmail
- Browser (if applies): Edge
- Version of supabase-js:  Hosted version

**Comment by inian** [comment]
Are you using a custom email template @prescience-data? Can you change the email template to see if it fixes the issue?

**Comment by prescience-data** [comment]
No only change to the default one is adding our app name to the email title.

**Comment by TannerGabriel** [comment]
I experienced the same problem today with the default email template.

**Comment by kiwicopple** [comment]
this should now be solved 👍
