### ISSUE TITLE
Why is there a # instead of a ? in the password reset URL?

### ISSUE THREAD

**Issue by mike-wax** [supabase/supabase#3064]
https://supabase.io/docs/reference/javascript/reset-password-email

`<SITE_URL>#access_token=x&refresh_token=y&expires_in=z&token_type=bearer&type=recovery`

**Comment by roseMix** [comment]
Query strings become part of the `request` , `#` don't, so it does,t even get to the server it just gets stored in the browser. See more here:
https://stackoverflow.com/questions/3664257/why-is-the-hash-part-of-the-url-not-available-on-the-server-side

**Comment by mike-wax** [comment]
got it, thanks for the quick reply!
