### ISSUE TITLE
Unable to run self-hosted Supabase on Raspberry Pi OS (64-bit)

### ISSUE THREAD

**Issue by nns52k** [supabase/supabase#30640]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On Raspberry Pi OS (64-bit) running on Raspberry Pi 5, `docker compose up --detach` fails to start supabase-db.

## To Reproduce

1. Run `git clone --depth 1 https://github.com/supabase/supabase.git` to get a copy of self-hosted Supabase.
2. Change working directory to `supabase/docker/`.
3. Copy file `.env.example` to `.env`.
4. Run `docker compose up --detach` in a terminal.

## Expected behavior

1. All required docker images are downloaded automatically.
2. Supabase is up and running.

## Screenshots

![supabase-db bug-screenshot](https://github.com/user-attachments/assets/9ef00533-0ac4-4513-a373-cbe315ad1bf9)

## System information

- OS: Respberry Pi OS (64-bit)
- Version of supabase: commit d9a1a615f5e19f57ee7e8f829fb278d971409e17 (Date: Fri Nov 22 15:22:05 2024 -0500)

## Additional context

The same installation steps mentioned above works without any problem on my MX Linux box, but it doesn't work on Raspberry Pi OS (64-bit).

I've followed the instructions provided by [rjbrown99](https://github.com/supabase/supabase/issues/18815#issuecomment-2170638770) to change system page size to 4096, it does have supabase-vector work. I also have tried to remove anything about supabase-vector in file `docker-compose.yml`. Before I update my self-hosted Supabase, these 2 workarounds do work, but after updating, supabase-db become a new problem. In short, I believe it has nothing to do with supabase-vector. We can either change page size to 4096 or disable supabase-vector, so that everything works in older version of self-hosted Supabase.

**Comment by nns52k** [comment]
I deleted the anonymous volume used by Supabase, reinstalled a new Supabase and the problem went away. The guess is that an extension is causing the problem. Sorry for the noise.

**Comment by nns52k** [comment]
I deleted the anonymous volume used by Supabase, reinstalled a new Supabase and the problem went away. The guess is that an extension is causing the problem. Sorry for the noise.

**Comment by RightHandedMonkey** [comment]
@nns52k are you having luck running the self hosted superbase on a raspberry pi on the latest builds? I'm unable to start the supabase-vector module. I'm running a raspberry pi 5 with 4GB ram.

**Comment by nns52k** [comment]
@RightHandedMonkey I don't use Supabase any more, but this is likely to still work on the latest build:
To run Supabase on Pi 5, we have to either disable supabase-vector module, or set the page size to 4k.

I followed the link you provide too. It works for me.
