### ISSUE TITLE
Sponsor icons are squished on certain screens

### ISSUE THREAD

**Issue by Maxson52** [supabase/supabase#3068]
# Bug report

## Describe the bug

On certain screen sizes (where multiple columns are present), sponsor icons width is messed up (likely due to the length of certain usernames)
![image](https://user-images.githubusercontent.com/42156015/132048229-e79524ac-b370-4bf9-ae81-0faead364498.png)

## To Reproduce

1. Go to https://supabase.io/docs/handbook/contributing
2. Adjust zoom/screen size until reproduced

## Expected behavior

Icons are all displayed at an constant width (`2rem` or `var(--ifm-avatar-photo-size-sm)`)

## System information

- Browser: Chrome (Windows laptop)

## Additional context

I believe the problem is caused by the fact that there are always 4 sponsor names per row, no overflow control, meaning the sponsors with longer names have their profile picture width modified to fit.

**Comment by Maxson52** [comment]
This problem is not reproducible at [supabase.io/oss](https://supabase.io/oss), only on the docs page. The docs page does have a table of contents on the right side, which may be the reason behind this.

**Comment by code3z** [comment]
@Maxson52 It happens at the breakpoint `(min-width: 997px) and (max-width: 1320px)` which applies `max-width: calc(var(--ifm-container-width) - var(--doc-sidebar-width) - var(--ifm-spacing-horizontal)*2);`. Do you want to have this breakpoint? It seems to be a waste of space. Also, I can't find this in the code, so maybe it's part of docusaurus.
