### ISSUE TITLE
supabase/supavisor:1.1.56 keep restarting in self-hosting in ubuntu

### ISSUE THREAD

**Issue by govind0471** [supabase/supabase#30696]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The Supavisor pooler in my self-hosted Supabase setup keeps restarting.

## To Reproduce

Steps to reproduce the behavior,

1. Go through the self-host setup from Supabase.

## Expected behavior

It should run without restarting

## Screenshots

![image](https://github.com/user-attachments/assets/b5a1cb3c-8e59-4d03-9220-258f368f4753)

## System information

- OS: Ubuntu 22.04.5(as wsl)

**Comment by kaelshawn** [comment]
in the docker-compose.yaml file, edit the "DATABASE_URL" env of service "supavisor",
from "ecto://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/_supabase" to "ecto://supabase_admin:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/_supabase" .

![image](https://github.com/user-attachments/assets/42893be4-f152-482e-be66-4f1c5b67412a)

**Comment by kaelshawn** [comment]
this pr [fix(self-hosted): self hosted docker compose](https://github.com/supabase/supabase/pull/30674) will fix this issue. @govind0471 @iamv13

**Comment by iamv13** [comment]
Thanks you @kaelshawn It's work. 😆

**Comment by govind0471** [comment]
Thank you @kaelshawn it worked.
