### ISSUE TITLE
Bucket not accessible

### ISSUE THREAD

**Issue by mircozamprogno** [supabase/supabase#30709]
Hi, 

I have a couple of buckets in my project that I am not able to access, honestly I do not remember how I created them at the beginning of my supabase journey and now I would like to delete them.
As soon as I select the bucket I receive this error:

Failed to retrieve folder contents from "images/profiles/avatars": id must match /^(\w|!|-|\.|\*|'|\(|\)| |&|\$|@|=|;|:|\+|,|\?)*$/ regular expression

Failed to retrieve folder contents from "avatars": id must match /^(\w|!|-|\.|\*|'|\(|\)| |&|\$|@|=|;|:|\+|,|\?)*$/ regular expression

Could you suggest me please a way to delete them?

Thanks for your help:
![Screenshot 2024-11-28 at 07 15 00](https://github.com/user-attachments/assets/a5240ff3-1697-4bc8-bc26-262e354e8a53)

Mirco

**Comment by Hallidayo** [comment]
Hi @mircozamprogno - It may be best if you contact [support](https://supabase.com/dashboard/support/new) on this one as they can delete the old buckets.

**Comment by saltcod** [comment]
going to mark this as closed in favour of a support ticket.
