### ISSUE TITLE
"Restoring..." hangs forever

### ISSUE THREAD

**Issue by tocteman** [supabase/supabase#3071]
Cannot use any of the UI after what seems like a failed backup restoration.

I attempted to restore a backup file directly through the UI. It appeared that nothing had happened for some minutes. I restarted the server some minutes later and got this "Restoring..." message. Thing is, it never went away. This is problematic not only because I've lost access to most of the pages through the UI, but also to the backup files list. Everything else seems to be working fine (that is, in "unrestored" state) in our webapp and through direct sql queries. How can this restoration be cancelled? And in the meantime, how can I download the latest backup file without interacting with the UI? 

Thanks a lot.

![restore](https://user-images.githubusercontent.com/945580/132067740-587a8b3f-3211-444c-878d-2d71cc004ff5.png)

**Comment by dragarcia** [comment]
Hi @tocteman 👋 

We've taken a look at your project via the support ticket you've sent us and have resolved the issue. Your project should be fully restored now.

> how can I download the latest backup file without interacting with the UI

This is not possible at the moment unfortunately. We did however find the bug that caused your restoration to be delayed and are now working on getting the fix into production. Once that's fixed, restorations should no longer take as long (dependent as well on the size of one's database).

**Comment by tocteman** [comment]
Thanks a lot!

Best

jf

**Comment by jtkeyva** [comment]
I am having the same issue and have reported tickets but no resolution. This is happening for all of my projects I've tried to restore. Please help. 
Thanks
