### ISSUE TITLE
Add recommendation to avoid symbols in password when creating a new project

### ISSUE THREAD

**Issue by hugo-cardenas** [supabase/supabase#3076]
# Improve documentation

## Link 

https://app.supabase.io/new/*

## Describe the problem

When creating a new project, it does not advise against using symbols in the password. (If using symbols, then the password in the connection string needs to be URL encoded).

<img width="680" alt="Screenshot 2021-09-04 at 14 29 04" src="https://user-images.githubusercontent.com/1535759/132092886-fa14efd1-c77e-4e07-aaad-6b77cbba6489.png">

But this advise is later found in the [documentation regarding Connection Strings](https://supabase.io/docs/reference/postgres/connection-strings#notes).

<img width="564" alt="Screenshot 2021-09-04 at 14 28 10" src="https://user-images.githubusercontent.com/1535759/132092859-45d50943-7e12-400a-8092-32fb2d055739.png">

## Describe the improvement

It would be nice to get this tip at the time of creating the password for a new project, to avoid using symbols, so there's no need to apply URL encoding later when using for the connection string.

**Comment by awalias** [comment]
hey @hugo-cardenas this is a mistake in the docs. You should _absolutely_ use special charterers, I will remove this warning now from the docs.

as with any URL, you should user percent encoding to encode special characters when using the postgres connection string

see postgres docs here:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/458736/132982093-0f8bc1cc-d6d7-4b61-9dab-86c3a097dbc1.png">
