### ISSUE TITLE
Critical : Stripe Wrapper Data Not Displaying

### ISSUE THREAD

**Issue by br0wsa** [supabase/supabase#30832]
### Discussed in https://github.com/orgs/supabase/discussions/30831

<div type='discussions-op-text'>

<sup>Originally posted by **br0wsa** December  3, 2024</sup>
# Critical Issue: Stripe Wrapper Data Not Displaying on Supabase

## Description
I am experiencing an issue with the Stripe wrapper in my Supabase database. The data from the wrapper is not displaying, including for all associated foreign tables.

## Details
- **Database**: Supabase
- **Infrastructure**: AWS | eu-west-1
- **Issues encountered**:
  - Unable to delete the wrapper.
  - Unable to add or remove tables from this wrapper.
  - There seems to be a timeout with the API Gateway.

## Questions
Is anyone else experiencing the same issue?

Thank you in advance for your help!

![Screenshot from 2024-12-02 14-09-57](https://github.com/user-attachments/assets/7167fc16-03c5-4e3d-9904-cf78884b0bef)
![Screenshot from 2024-12-02 14-10-09](https://github.com/user-attachments/assets/b4243afb-e9d8-41cb-94cf-11e3e65145f6)
</div>

**Comment by burmecia** [comment]
This has been resolved in https://github.com/supabase/wrappers/issues/376.
