### ISSUE TITLE
Recommended SSR strategy doesn't allow for SSRing with expired access token but with valid refresh token

### ISSUE THREAD

**Issue by Andarist** [supabase/supabase#3085]
## Describe the issue

The recommended strategy can be seen here: https://github.com/supabase/supabase/tree/f4181775337e6807be9f9476c4f8a2287988d68c/examples/nextjs-with-supabase-auth

Because access tokens are refreshed on the client side it is not unlikely that a user visits a page when the access token is already expired. This might very easily fail SSR attempt and there is not much one can do about it - nor there is any recommendation on how this should be handled.

A very similar problem can arise when logging through an external provider - one lands on a page after redirects but the SSRing of this page cannot utilize the received token because the token is received in the URL's hash and `@supabase/gotrue-js` just couldn't possibly set a cookie by that moment.

I would consider those 2 serious problems with the design of this recommended approach. To the best of my knowledge - this is not an easy fix. This would, at least, require exposing new methods/options in the `supabase/gotrue` that would make this easier. I think that it should be possible to **easily** authenticate a user with an external provider on a backend and keep refresh tokens and such in HTTP only cookies. This would improve the security of the proposed approach while fixing both of the mentioned problems by design - as the server would be able to refresh the access tokens.

**Comment by alaister** [comment]
I'd also like to see this issue fixed.

I was thinking of ways to implement a server side token refresh but I think there's actually a simpler solution.

`getUserByCookie` currently always makes a request to Supabase to retrieve the user, so why not have `setAuthCookie` set a good old session id cookie that doesn't expire. This would solve the problem of keeping the server and client JWTs in sync.

If refresh tokens were also linked to a session, It would also have the side benefit of allowing developers to store extra data on a session, for example a `currentTeamId`, which could be added to the JWT.

When a user logged out, the session would be deleted, as would all related refresh tokens.

I'm not sure how easy it would be to add this functionality in to gotrue, but I'm happy to give it a go and submit a PR if someone from the Supabase team provides feedback.

As for @Andarist's oauth issue, the URL hash is never sent to the server so perhaps gotrue needs to allow for different oauth flows (maybe authorization code), where the developers own server / function is responsible for finishing the flow and setting the session id cookie at the same time. This may be an even bigger task than adding sessions to gotrue!

Please let me know what you think.

**Comment by jvorcak** [comment]
@alaister I've experienced the same issue. I don't really have time to prototype something proper, but what you're saying with increasing the cookie lifetime could work, at least till I figure out something better.

Here's how you can do it https://github.com/supabase/supabase/discussions/3198#discussioncomment-1323047

**Comment by hf** [comment]
Hey everyone. We're working hard on making first-class support for SSR. In the mean time, please read our official [Server-Side Rendering](https://supabase.com/docs/guides/auth/server-side-rendering) doc to understand how the flows work at this time.
