### ISSUE TITLE
Persistence on preview branches

### ISSUE THREAD

**Issue by dramsay1996** [supabase/supabase#30863]
Hi all, I'm relatively new to supabase (~2 months) and just started using branching a couple of weeks ago.

Our team has been maintaining both a production and a development environment in the cloud and I've been trying to use supabase branching for this.

With supabase branching, when a preview branch is merged with a production branch, that preview is automatically deleted. This means we need to re-create our development environment each time. Some of this can be done automatically with migrations, seed.sql, and config.toml, but there are still aspects that require manual work. The most frustrating thing is having developers redefine their environment variables to connect to the fresh dev instance.

Is there any existing way or a plan in the future to have a more permanent "staging" or "development" branch type that isn't deleted after merging with the production branch? Has anyone else struggled with this?

**Comment by charislam** [comment]
Thanks for opening the issue @dramsay1996!

Have you tried [persistent branches](https://supabase.com/docs/guides/deployment/branching#persistent-branches)? From what you describe, they seem to fit your use case.

**Comment by dramsay1996** [comment]
Thanks @charislam! This was exactly what I was looking for, thanks for pointing that feature out.

Closing the issue.
