### ISSUE TITLE
UI Bug - Modals clear based on mouse up position

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase#3086]
# Bug report

## Describe the bug

Within the Supabase UI, when selecting text within a modal - if the mouse has been dragged horizontally outside the modal (very easy to do given the small surface area of the modal), the dismiss event seems to trigger based on the position of the mouse at the _end_ of the click, rather than the start _(which would be expected behaviour)_.

(Also related, the `Enter` key doesn't submit the form within a modal, requires a mouse click which makes accessibility tricky.)

## To Reproduce

1. Go to supabase.io UI app.
2. Click on `'Queries'`.
3. Select `'Rename Query'` from the context menu on an existing query.
4. Select the text using the mouse, starting at the end of the existing text and ending outside the modal.
5. Release mouse.
6. Modal dismisses before editing can occur.

## Expected behaviour

Expect the UI to detect a mouse event commenced either:
a) within the modal, blocking dismissal, regardless of mouse position at `mouseUp`, or;
b) if there is some intentional UX design that requires the above to not be feasible, then detect if the click originated within an `input` field and block dismissal.

## Screenshots

![image](https://user-images.githubusercontent.com/65471523/132146751-e70fb74c-62ef-453d-a80f-1cb32a653889.png)

![image](https://user-images.githubusercontent.com/65471523/132146768-2c2b1ef7-7f17-4954-a401-d28210d0324e.png)

![image](https://user-images.githubusercontent.com/65471523/132146824-37991fed-e38e-48b4-be84-a201a9e94661.png)

![image](https://user-images.githubusercontent.com/65471523/132146836-0509ed36-9044-4a9e-95cd-d49d3f64934f.png)

**Comment by MildTomato** [comment]
I've added my comment on here about this.
https://github.com/supabase/ui/pull/278#issuecomment-922689481

My preference for this:
Dialog/modal traps the focus and the first input element should auto focus.
This way we are following best accessibility best practise.

**Comment by kiwicopple** [comment]
Fixed 👍 https://github.com/supabase/ui/pull/278#issuecomment-922689481
