### ISSUE TITLE
Supabase Dashboard table editor

### ISSUE THREAD

**Issue by kimurayu45z** [supabase/supabase#30896]
# Bug report

When I tried to create a table in `public` schema, somehow the table has been created in `auth` schema and I can't delete it.
It must be a bug of Supabase Dashboard web app.

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Hallidayo** [comment]
Hi @kimurayu45z - Thank you for reporting the issue. I've tried the above on my project but I am unable to recreate and I can create a table in the `public` schema. Have you got a video of what is happening?
