### ISSUE TITLE
AI assistant remains open after leaving SQL editor tab

### ISSUE THREAD

**Issue by guillaumeduhan** [supabase/supabase#30915]
### **Bug Report**

![Screenshot 2024-12-05 at 08 35 19](https://github.com/user-attachments/assets/b243133f-0ee6-4e33-ab5c-191a41af1374)

#### **Describe the bug**  
After leaving the SQL editor in the Supabase online cloud platform, the AI assistant remains open on the interface, even though it should automatically close or disappear.

---

#### **Steps to reproduce**  
1. Navigate to the SQL editor on the Supabase platform.  
2. Interact with the AI assistant in the SQL editor.  
3. Leave the SQL editor (e.g., by switching tabs or returning to the dashboard).  
4. Observe that the AI assistant remains open on the screen, even when it’s no longer relevant to the current view.

---

#### **Expected behavior**  
The AI assistant should automatically close or minimize when the user exits the SQL editor, ensuring a clean and distraction-free interface.

---

#### **Screenshots**  
(Add screenshots to show how the assistant remains open after exiting the SQL editor, if necessary.)

---

#### **System Information**  
- **OS:** macOS  
- **Browser:** Chrome  
- **Supabase Platform Version:** (Provide if known)  

---

#### **Additional Context**  
This behavior disrupts workflow by unnecessarily occupying screen space in views where the assistant is irrelevant.

---

Would you like any further refinements?

**Comment by guillaumeduhan** [comment]
It's probably not a bug — assistant is now available everywhere but do we want to keep it open all the time?

**Comment by saltcod** [comment]
Thanks @guillaumeduhan — going to mark this as closed as this is currently the expected behaviour.
