### ISSUE TITLE
Make DEVELOPMENT.md more visible

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#3095]
https://github.com/supabase/supabase/discussions/3084

**Comment by LuluNwenyi** [comment]
Hi @soedirgo, 
When you say more visible, what do you mean?

**Comment by LuluNwenyi** [comment]
I’d love to work on this. Can I be assigned to this?😅

**Comment by soedirgo** [comment]
Sure, thanks!

**Comment by bariqhibat** [comment]
Hey @soedirgo, has this issue been resolved already by @LuluNwenyi? If not, can I help out on this?

**Comment by soedirgo** [comment]
This is still open, but I'd wait a bit for Lulu's reply.

**Comment by LuluNwenyi** [comment]
Hi @soedirgo @bariqhibat I'm working on it and I'll open a Pr for it soon.

**Comment by LuluNwenyi** [comment]
Hi @soedirgo
I've opened a PR for this issue. Although, I was hoping you could help clarify how I can add it to the /web.

**Comment by soedirgo** [comment]
Resolved in https://github.com/supabase/supabase/pull/3411.
