### ISSUE TITLE
Studio UI fails to load storage objects

### ISSUE THREAD

**Issue by veloware** [supabase/supabase#31020]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using local development, I have uploaded a PDF file to storage.  I am able to successfully load the file in the browser by going to the URL - 

http://localhost:54321/storage/v1/object/public/event-images/1733733618196-invoice-0000000049.pdf

and I can see it in the storage.objects table - 
<img width="832" alt="image" src="https://github.com/user-attachments/assets/5ca5148e-df04-4d26-be1e-162460d0d16a">

However when going to the storage section in the Studio UI, I get this error - 

<img width="837" alt="image" src="https://github.com/user-attachments/assets/2d690af1-1410-4aaa-a18e-efec8832d451">

No errors in any of the logs.

**Edit**
This error actually seems to occur after simply creating a bucket and trying to view the (empty) contents.

## To Reproduce

In local development - 

-  either in the Studio UI or config.toml, create a bucket
- go to the bucket in Studio UI
- error toasts appear in the top right.

## Expected behavior

Object details should be displayed

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 2.46.1
- Version of Node.js: 20.12.2

**Comment by veloware** [comment]
closing, updating supabase and running `supabase db reset` seems to have fixed something

**Comment by LuisReinoso** [comment]
I have this issue even I have run supabase db reset
`supabase/studio        │ 20241202-71e5240`
```
![imagen](https://github.com/user-attachments/assets/39c569ef-699e-4fd7-b36a-a8766ce7fcb4)

```
