### ISSUE TITLE
use correct imports in flutter example

### ISSUE THREAD

**Issue by synchronisator** [supabase/supabase#3103]
# Improve documentation

## Link 

https://supabase.io/docs/guides/with-flutter

## Describe the problem

in "Initialize a Flutter app" the code "flutter create supabase_quickstart" creates a package called supabase_quickstart.
The following code examples use imports from 
"import 'package:supabase_flutter_guide/components/auth_state.dart';"
see "Setup Splash Screen"
Because of this the copy/pasted code does not work.

## Describe the improvement

change all "import 'package:supabase_flutter_guide.*" to "import 'package:supabase_quickstar.*"

**Comment by dshukertjr** [comment]
@synchronisator 
Thank you so much for reporting this issue. This should be fixed now!
