### ISSUE TITLE
Missing auth docs

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#3108]
### Discussed in https://github.com/supabase/supabase/discussions/3102

<div type='discussions-op-text'>

<sup>Originally posted by **howesteve** September  6, 2021</sup>
So in https://supabase.io/docs/guides/auth we have:

"When users sign up, Supabase assigns them a unique ID. You can reference this ID anywhere in your database. For example, you might create a profiles table referencing the user using a user_id field." - and no other info available.

It took me a good time to guess those infos are on a separate auth schema:

select * from auth.users;

Please, this should be documented.
</div>

**Comment by handlerda** [comment]
This is the worst part of superbase. Not very counterintuitive. The user table should mirror by default or at least make it easy to set this up out of the box.

**Comment by darora** [comment]
Ought to make it easier to discover, but described in:

https://supabase.io/docs/guides/auth#how-it-works
https://supabase.io/docs/guides/auth#managing-user-data
