### ISSUE TITLE
Reset Password documented flow out of date?

### ISSUE THREAD

**Issue by wiverson** [supabase/supabase#3109]
# Bug report

From https://supabase.io/docs/reference/dart/reset-password-email

"When the user clicks the reset link in the email they will be forwarded to:

<SITE_URL>#access_token=x&refresh_token=y&expires_in=z&token_type=bearer&type=recovery"

The # character is only intended for client side references. To be a proper query parameter this should be a ? instead.

<SITE_URL>?access_token=x&refresh_token=y&expires_in=z&token_type=bearer&type=recovery

## Describe the bug

Using a # character instead of a ? makes it much more difficult to parse the incoming request.

## To Reproduce

It's in the docs, but you can see the behavior by requesting a password reset.

## Expected behavior

Should be a ? instead of a #

**Comment by wiverson** [comment]
This appears to be a documentation bug. Apparently this flow is now handled by the Supabase.js client with a PASSWORD_RECOVERY event sent along.

This snippet:

```javascript
supabase.auth.onAuthStateChange((event, session) => {
    console.log(event, session);
}
```  

Generates the log as shown. The payload for the event (the session param) appears to be identical for both the SIGNED_IN event and the PASSWORD_RECOVERY event. 

<img width="721" alt="Screen Shot 2021-09-07 at 2 44 36 PM" src="https://user-images.githubusercontent.com/873850/132414907-3384c6d9-81da-4713-93f3-d2ec90cd4106.png">

I'm going to try using the following fragment from the supabase docs to try updating the password:

```javascript
const { error, data } = await supabase.auth.api
      .updateUser(access_token, { password : new_password })
```

...and see if that works.

**Comment by dcruz1990** [comment]
I have a same issue, i don't know why, after clicking the recovery link and calling the update, i end whit logged in user and no password is changed, like if it was a magic link. In the docs its very confusing because it says that after clicking in recovery link from the email, you have to provide a change password form or something like that, but it doesnt work that way.

**Comment by mryechkin** [comment]
I agree the behaviour is quite confusing, if it is in fact intended. It would be nice to get more clarification on this in the docs.

**Comment by kiwicopple** [comment]
> Using a # character instead of a ? makes it much more difficult to parse the incoming request.

URL fragments are part of the OAuth spec, rather than params (i believe they are deemed safer).

I'll close this for now, but if there is something that we can safely change or improve here.
