### ISSUE TITLE
Token disapears after page refresh 

### ISSUE THREAD

**Issue by MariuzM** [supabase/supabase#31127]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When i do auth with Vite/React i get token all good there, but once i click browser refresh button that token disapears. I think 2 days ago it was working fine. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots

This is the token that gets added but then disapears after page refresh

<img width="555" alt="SCR-20241213-uhsp" src="https://github.com/user-attachments/assets/fb1fdb04-0139-470c-9e1e-667baebdd338" />

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by MariuzM** [comment]
Just before disapearing it flash with this extra token but then both gone 
<img width="609" alt="image" src="https://github.com/user-attachments/assets/f27097fe-a142-46ef-8b89-d6ab821b7bae" />

**Comment by InvixGG** [comment]
Same issue for me. Worked fine yesterday, but now on refresh it breaks.

**Comment by InvixGG** [comment]
After rolling back my package.json and pnpm-lock.yaml it worked again. @MariuzM

**Comment by GaryAustin1** [comment]
https://github.com/supabase/auth-js/issues/995

Reported in auth-js and dev reverted auth-js. 

Closing this here in favor of that.

**Comment by MariuzM** [comment]
@InvixGG what version did you downgrade to?
