### ISSUE TITLE
@supbase/ssr - createServerClient - https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=environment&environment=server

### ISSUE THREAD

**Issue by nicitaacom** [supabase/supabase#31352]
# Improve documentation

## Link  - https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=environment&environment=server

Add a link to the page which needs improvement (if relevant)

## Describe the problem
I followed docs
Expected that I get latest something but I got deprecated something
![image](https://github.com/user-attachments/assets/69509edb-d9d2-494f-916d-fa4808fafb90)

Please update docs so I use all latest and up to date :)

**Comment by nicitaacom** [comment]
also
Parameter 'cookiesToSet' implicitly has an 'any' type.ts(7006)
![image](https://github.com/user-attachments/assets/748c7f84-581e-4714-b2ce-33186c98177c)

**Comment by j4w8n** [comment]
Regarding your first screenshot: it looks like you're not adding the supabase url and supabase key at the beginning? I can't quite tell because of the deprecation popup.

**Comment by nicitaacom** [comment]
I'm adding supbase url and key (by key I mean NEXT_PUBLIC_SUPABASE_ANON_KEY)

![image](https://github.com/user-attachments/assets/8a2ae460-0bee-4960-a26e-47d584c7f42c)

**Comment by j4w8n** [comment]
> I'm adding supbase url and key (by key I mean NEXT_PUBLIC_SUPABASE_ANON_KEY)
> 
> ![image](https://github.com/user-attachments/assets/8a2ae460-0bee-4960-a26e-47d584c7f42c)
> 

But those should be the first two arguments, and it seems like they're part of the 2nd? Still difficult to tell.

**Comment by nicitaacom** [comment]
I created mvp codesandbox - https://codesandbox.io/p/devbox/8fr5ky?file=%2FREADME.md%3A3%2C1

Right now it works
