### ISSUE TITLE
Pricing FAQ missing the word "no"

### ISSUE THREAD

**Issue by raghavjain3** [supabase/supabase#3137]
# Bug report

## Describe the bug

https://github.com/supabase/supabase/blob/master/www/data/PricingFAQ.json#L24 missing "no" in this sentence:
"If you do not respond, or do want to move up a tier and continue to exceed your limits then we may have to limit your projects consumption."

**Comment by w3b6x9** [comment]
@raghavjain3 thank you for point this out! we have fixed it: https://github.com/supabase/supabase/blob/ad306b1d4f7a853c3c5df3b41069a449e28e0dc1/www/data/PricingFAQ.json#L24
