### ISSUE TITLE
Horizontal scroll reset when clicking timestamp cells on the Dashboard

### ISSUE THREAD

**Issue by hawkcookie** [supabase/supabase#31623]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Horizontal scroll reset when clicking timestamp cells on the Dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1.Add enough columns so that the created_at column is out of the initial visible area.
2.Use the horizontal scroll bar to navigate to the created_at column.
3.Click or select the created_at cell.
4.Observe that the horizontal scroll position resets to the lef

## Expected behavior

The scroll position should remain on the created_at column, instead of resetting to the left.

## System information

- OS: macOS
- Version of supabase-js: [e.g. 2.44.3]
- Version of Node.js: [e.g. 20.15.0]

**Comment by ivasilov** [comment]
I just replicated this, seems like it's still an issue. Testing the linked PR.
