### ISSUE TITLE
Clunky charts in dashboard

### ISSUE THREAD

**Issue by Dhaiwat10** [supabase/supabase#3176]
# Bug report

## Describe the bug

The charts in the project dashboard keep resizing in a weird way, making the UX crap.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a project's dashboard
2. Hover over any chart which has some empty values

## Expected behavior

Should work nicely and not resize like crazy.

## Screenshots

https://user-images.githubusercontent.com/39617427/133003164-f5fd8b13-01b9-4c4e-91a6-5145ea0e5060.mov

## System information

- OS: macOS
- Browser: Chrome

**Comment by kiwicopple** [comment]
fix going out soon @Dhaiwat10 - thanks for the bug report!
