### ISSUE TITLE
Duplicated bucket name in `publicURL` 

### ISSUE THREAD

**Issue by gr-qft** [supabase/supabase#3177]
# Bug Report

First of, thanks you guys for the awesome work! I love supabase! 

This concerns supabase Storage. When you have a bucket, say 'bucket', and you put files in there, and you write 

```js
supabase.storage.from('bucket').getPublicUrl(foldername)
```

you would get back something like "...bucket/bucket/folder_name/..." which I think is not correct. 

Thanks!

**Comment by kiwicopple** [comment]
> thanks you guys for the awesome work

Thanks @gr-qft ! Appreciate the kind words :)

> get back something like "...bucket/bucket/folder_name/..." which I think is not correct

Any reason why this is not correct? It's probably better not to name your buckets "bucket". Might be better to use something more descriptive

**Comment by gr-qft** [comment]
Hey, thanks!

First, `bucket` was just an example :)

Second, it's not correct because that url cannot be used to access the file (the bucket is public), but if I remove one `bucket` in the returned url then it's accessible. 

i.e. see the following url fragment: 

```
supabase.co/storage/v1/object/public/bucket/bucket/folder/file
```

**Comment by joshenlim** [comment]
hey there @gr-qft! could i check real quick what your `foldername` is? I'm presuming you have the bucket name as part of the `foldername`?

**Comment by gr-qft** [comment]
@joshenlim Hey there, thanks! The folder name is not the same as the bucket name. 

The problem is precisely when I write e.g. `supabase.storage.from('bucket').getPublicUrl('folder1/folder2/popcat.png')` 
I got back `.../public/bucket/bucket/folder1/folder2/...`. This is why I said it's not correct.

**Comment by inian** [comment]
What version of supabase-js are you on @gr-qft ?

**Comment by gr-qft** [comment]
Hey @inian  ! It's  "@supabase/supabase-js": "^1.21.2"

**Comment by joshenlim** [comment]
@gr-qft could try updating your supabase-js library to the latest version (1.22.6) and see if this bug still happens?

**Comment by gr-qft** [comment]
@joshenlim Thanks! Let me try it and I'll get back to you very soon!

**Comment by gr-qft** [comment]
@joshenlim I just tested it in version 1.22.6, it's still generating the wrong url. 

What's going on?

**Comment by joshenlim** [comment]
@gr-qft hmm i'm trying to reproduce the issue that you're facing but am unable to too.

Can i check exactly how you're invoking `.getPublicUrl` by pasting your code snippet and adding some relevant screenshots? Or if you don't mind, could you create a REPL to reproduce this issue you're facing - that'd be best.

**Comment by gr-qft** [comment]
@joshenlim Oh.... I see where I'm making a mistake. I upload a file using `storage.from.upload` and then using the `Key` from the returned data, and this is making the bucket name duplicated (`Key` includes the full path, which contains the bucket name). 

Thanks so much for trying to help with this issue! I love supabase and your team!

**Comment by joshenlim** [comment]
@gr-qft all good! :) happy hacking!

**Comment by gr-qft** [comment]
> @gr-qft all good! :) happy hacking!

👍 💯  !
