### ISSUE TITLE
Being able to set the user session duration

### ISSUE THREAD

**Issue by stoico** [supabase/supabase#319]
# Feature request
By default user sessions currently last 1 hour (3600s). 

To save time and effort to the user, it would make sense for us to be able to configure the session duration.

**Comment by kiwicopple** [comment]
Hey everyone I completely missed this one somehow (i think becuase it was on our Beta Launch). 

I've added this to the dashboard - it should appear tomorrow. I'll reopen this issue until it appears

**Comment by kiwicopple** [comment]
![Screenshot 2021-03-04 at 2 46 43 PM](https://user-images.githubusercontent.com/10214025/109922577-8761cf80-7cf8-11eb-95d7-d49aca70ccad.png)

**Comment by libovness** [comment]
is there some kind of upper bound on the expiry? every time I punch in a number above ~32000 I get an `Unexpected end of JSON output` error

**Comment by tomsoderlund** [comment]
What if I want a user session JWT to last forever/indefinitely?

**Comment by Chriztiaan** [comment]
Love lived sessions would be preferred.

**Comment by EskelCz** [comment]
@kiwicopple Can the duration be extended? At least a month would be sensible imo.

**Comment by cguagenti** [comment]
+1 for longer session

**Comment by marcus-sa** [comment]
Are longer sessions ever gonna be supported..?

**Comment by kiwicopple** [comment]
Sessions are already _indefinite_. See this answer/issue for a detailed answer:

https://github.com/supabase/supabase/issues/11014#issuecomment-1359305465
