### ISSUE TITLE
Can't save Email auth settings

### ISSUE THREAD

**Issue by leadream** [supabase/supabase#3192]
I can't save these settings. It has no response after clicking the save button.

![image](https://user-images.githubusercontent.com/12868055/133176876-42dc64ea-2495-4e2e-9baa-a148f1eb67f9.png)

**Comment by MildTomato** [comment]
cc @awalias @kangmingtay 

probably need a security discussion around this

**Comment by MildTomato** [comment]
hey @leadream - currently it is required that all the fields in that form have a value for it to be able to save.

(ps. apologies about the bad UX on this though, we should have more clear error messaging / styling. something we'll work on)

**Comment by kangmingtay** [comment]
@MildTomato i think we should make the "SMTP Sender Name" field independent from the rest of the custom SMTP config. Meaning one should be able to set it without having to set the rest of the fields. If no smtp host, port, user, password is provided, it should default to using the supabase smtp server.

**Comment by MildTomato** [comment]
Sounds good to me. @awalias also confirmed it should be ok.

Something for future consideration might be to have a sender name per email template, rather than a generic one.
I think this is how firebase do it - not sure wether having anything other than 'noreply' might be harmful for inbox spam filters.

**Comment by kangmingtay** [comment]
> Something for future consideration might be to have a sender name per email template, rather than a generic one.
I think this is how firebase do it.

i like this actually, it's alot more intuitive for the user than having to navigate to the auth settings page to set it.

**Comment by MildTomato** [comment]
@kangmingtay just pinging you to keep this issue alive.

Should we do this? Have a sender name per template?

**Comment by kangmingtay** [comment]
Hmm currently gotrue doesn't allow setting a sender name for each template. The sender name will be applied to all templates. But i'm in favour of moving the SMTP config (which includes the sender name) to the email template section for better visibility.

**Comment by leadream** [comment]
Hi all, is there any progress now? At least supabase should allow me to change the sender name for all templates without my own SMTP setup.

**Comment by burmecia** [comment]
I can see the `Sender name` is now available in `Email Templates`, @leadream can you see if this still an issue?

**Comment by leadream** [comment]
Hi @burmecia yes, I can see it, but I want to change sender name without custom STMP enabled. Is that possible?

**Comment by burmecia** [comment]
hi @leadream , sorry that is not possible atm and the fix probably won't anytime soon. I will close this ticket for now and feel free to open a new one if needed.

**Comment by BenGlasser** [comment]
I have this issue and all fields are filled out

**Comment by 7ttp** [comment]
> I have this issue and all fields are filled out

what issue are u facing specifically?
can u create a new issue regarding it!
