### ISSUE TITLE
Column Level Security

### ISSUE THREAD

**Issue by mehmetuken** [supabase/supabase#3195]
Column level security select update insert rules.

**Comment by kiwicopple** [comment]
Hi @mehmetuken - I believe I understand your request, but perhaps you can add some more details - perhaps what exactly _you_ want to achieve in your system. It's good for everyone when the issues are well spec'd out

Thanks!

**Comment by mehmetuken** [comment]
We find solution on this thread. PostgreSQL grant revoke we try but not working. If you want detail follow this discussion. https://github.com/supabase/supabase/discussions/3158

**Comment by mehmetuken** [comment]
I think supabase need good permission management system from auth.

**Comment by ericwooley** [comment]
I'm not sure exactly what the original author was thinking, but it might be nice to have some guided UI to handle granting on a column level, for insert, select, update etc...
 
 I haven't tried to mess with this in the supabase enviornment yet, but something like this: https://stackoverflow.com/questions/14462353/grant-alter-on-only-one-column-in-table would be nice to have easily implementable, for each role.
 
 EG: disable update created_at for authorized users.

**Comment by Donnerstagnacht** [comment]
Would also love to see this feature. Is there a current workarround?

**Comment by selbyk** [comment]
@mehmetuken Did you try the solution by ericwooley?

**Comment by mehmetuken** [comment]
> @mehmetuken Did you try the solution by ericwooley?

hi, you can check here https://github.com/supabase/supabase/discussions/3158#discussion-3566351

**Comment by johannessjoberg** [comment]
I solved this with workaround: https://github.com/supabase/supabase/discussions/3158#discussioncomment-4450408

**Comment by hf** [comment]
PostgreSQL does not have such a system built in. If you want to prevent users from updating certain columns on rows you can define functions that do the `UPDATE` commands, or structure your database schema using other PostgreSQL features like table inheritance.

I don't think it's possible to support such a system without changing a lot inside PostgreSQL.

**Comment by GaryAustin1** [comment]
Closing this as there are suggested options and it is really something that would need to be done by Postgres.

**Comment by Simbaclaws** [comment]
Can I leave this here as a suggested workaround?

This will REVOKE all permissions except SELECT for all users except the supabase_admin on one or multiple columns.
Causing column1 and column2 to be read only for all users except the administrator.

```sql
REVOKE ALL (column1, column2) ON tablename FROM PUBLIC;
GRANT SELECT (column1, column2) ON tablename FROM PUBLIC;
GRANT ALL (column1, column2) ON tablename FROM supabase_admin;
```
