### ISSUE TITLE
SQL Editor executes previous command instead of code that is currently displayed

### ISSUE THREAD

**Issue by kennethcassel** [supabase/supabase#3200]
# Bug report

The in browser sql editor runs the previous command instead of the current code when clicking 'RUN'

## Describe the bug

When using the in-browser sql editor, the editor is running the previous command instead of the command that is currently in the sql editor. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.io/project/<project-id>/editor/sql
2. Click " + New query
3. Enter a sql command in the editor (i.e. `select count(*) from purchases`)
4. Click RUN
5. See error. Results show "SQL query is empty"
6. Click RUN again
7. Expected SQL Result is returned.

## Expected behavior

When clicking RUN, a user would expect the code that currently appears on the screen to be executed. 

## Screenshots
![image](https://user-images.githubusercontent.com/22961671/133284059-780a73c5-ff80-490b-b4d9-aa6bb6406edf.png)
![image](https://user-images.githubusercontent.com/22961671/133284080-98b333d3-c58e-42a3-9ed6-0b5dd1938210.png)

## System information

- OS: macOS
- Browser:  93.0.4577.63 (Official Build) (arm64)
- Version of supabase-js: N/A happens in browser
- Version of Node.js: N/A happens in browser

**Comment by awalias** [comment]
fixed now! should show up in prod momentarily
