### ISSUE TITLE
COPY large dataset into supabase not showing any data

### ISSUE THREAD

**Issue by joeybellerose** [supabase/supabase#3202]
# Bug report

## Describe the bug

I am using the psql copy command to copy a ~40M record csv into supabase.  The csv is ~2GB in size.  The transfer completes with no errors but no data is showing up in supabase table.

## To Reproduce

Here's the SQL used to check table size:

`select table_name, pg_table_size(quote_ident(table_name))
from information_schema.tables
where table_schema = 'public'
order by 2 desc
`

## Screenshots

![df_pricing](https://user-images.githubusercontent.com/28072958/133307293-ea8df814-f647-420e-a16b-cc6fe617ceb6.png)

![df_pricing_size](https://user-images.githubusercontent.com/28072958/133307634-c91f0922-a6fe-414d-a276-47006428632d.png)
## System information

- OS: Linux
- Browser: Brave
- Version of supabase-js: hosted
- Version of Node.js: N/A

**Comment by darora** [comment]
@joeybellerose one possibility is that the copy failed, but was not reflected in the UI for some reason. Could you try running a vacuum on the table in question?

If that doesn't work, could you email support@supabase.io with your project ref and any other details?

**Comment by joeybellerose** [comment]
@darora So I vacuumed the table in question and that significantly reduced the size.  I also tried using the same COPY insturctions but with a subset of the data (100K rows vs 40M rows) and that had no issues at all.  I'm going to send an email to support@supabase.io to see if they can help. Thanks so much for your help!

**Comment by joeybellerose** [comment]
This ended up being a memory issue with postgres....more meomory solved the problem!
