### ISSUE TITLE
Today i saw supabase is promoting paid course. How shameful that a campany doing back door things for making money that too from documentaion. Looks like that supabase policy is not reliable. They are in early stage , no campany would like to promote paid documentation course. You claim you are alternative of firebase , how many times you see firebase promoting paid course for documentation. They themselves put video, and prepare advance documentation for every aspect. "The day firebase launch postgress.... u guys are doomed"

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#3209]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by soedirgo** [comment]
Replied here: https://github.com/supabase/supabase/discussions/3211
