### ISSUE TITLE
Add auth.users table as choice of tables when creating foreign key relationship from console

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#3212]
# Feature request

## Is your feature request related to a problem? Please describe.

Thanks to the new Supabase console, when creating a new table you can easily create a foreign key relationship. 

Maybe this was a design decision, but would adding `auth.users` table to the list of selection make sense? 

<img width="1382" alt="Screen Shot 2021-09-15 at 20 57 56" src="https://user-images.githubusercontent.com/18113850/133429555-76b1127d-35b9-49d3-a7ae-352a6e2fab89.png">

## Describe the solution you'd like

When selecting the table to reference to set a foreign key relationship, `auth.users` table should appear as a choice. 

## Describe alternatives you've considered

Currently creating a foreign key relationship is possible though writing SQL. 

## Additional context

N/A

**Comment by MildTomato** [comment]
This is being actively worked on 😄 
cc @joshenlim @phamhieu

**Comment by joshenlim** [comment]
Hey all! This feature is now ready and has been pushed out! :) We now allow creating foreign keys with tables from other schemas outside of `public` as shown below

![image](https://user-images.githubusercontent.com/19742402/135021215-52bebdf4-4beb-4627-9a13-1668c3862751.png)
