### ISSUE TITLE
Can not save complete object in a table with foreign key.

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#3228]
For example you have two related object 

```
type Post = {
    id: number,
    created_at: string,
    updated_at: string,
    post: string,
    subheading_id:Subheading
};`
```
```
type Subheading = {
    id: number,
    created_at?: string,
    updated_at?: string,
    topic?: string,
    main_topic_id?:string
  };
```
and you try to do something like this
`const { data, error } = await supabase.from<Post>("posts").insert([{ post: content, subheading_id: {"id":1,"created_at":"2021","updated_at":"2021","topic":"sociology","main_topic_id":"5"} }]);`

It will not work  and shows error
`{"hint":null,"message":"invalid input syntax for type bigint: \"{\"id\":1}\"","code":"22P02","details":null}`

If you pass `subheading_id `as `Int` then it will work. but  `subheading_id` is not a `number `but `object `of type `Subheading `. in all other technology **(java+hibernate)** **_you pass full object and it will automatically extract Id of foreign object and save as foreign key._**

If we try to design our object as `subheading_id:number` then it will **unlink** each object and effect data integrity on client side and **prevent autocompletion** if we fetch data from database.

**Comment by awalias** [comment]
thanks for opening the issue, @roker15 I believe @MildTomato is already working with you on this issue in discussions so can stick to a single thread 👍 https://github.com/supabase/supabase/discussions/3227

**Comment by roker15** [comment]
> thanks for opening the issue, @roker15 I believe @MildTomato is already working with you on this issue in discussions so can stick to a single thread 👍 #3227
why bug is closed? Solution offered is just a workaround and not proper solution.
