### ISSUE TITLE
UUID as Primary Key results in error

### ISSUE THREAD

**Issue by juanzgc** [supabase/supabase#3236]
# Bug report

## Describe the bug

Creating a table with the id as type `uuid` results in an error:
```
Error: identity column type must be smallint, integer, or bigint
```

![image](https://user-images.githubusercontent.com/24414523/133732780-29442f65-36bd-4e98-8703-549cfb51dc8b.png)

![image](https://user-images.githubusercontent.com/24414523/133732815-6999392a-4f1a-4631-b4f8-eca1e3d28a50.png)

## To Reproduce

Create a new table and set the `id` type to `uuid`. Set the `id` to be a Primary Key.

## Expected behavior

`uuid` should be allowed as an identity column considering it is a `universally unique identifier`.

## System information

- OS: macOS
- Browser: Chrome

**Comment by Wekananda** [comment]
Same, i got this error when use UUID as primary key

**Comment by clystian** [comment]
creating table with default field (id, created_at, updated_at) id is uuid, so table creation fails
but sometimes create table empty (no fields)
if table is created, it's possible create new field like id tieh type uuid and field creations results OK

**Comment by joshenlim** [comment]
hey all! a fix for this has now been pushed out - do give it a go and see if you guys still run into any issues around this

separately, @juanzgc a `uuid` should not be allowed as an identity column as identity columns implies that automatically assign a unique *number* to the column for each row. `uuid` types are not numbers and hence cannot be given the identity constraint [[ref]](https://www.postgresqltutorial.com/postgresql-identity-column/)
