### ISSUE TITLE
Doc Search should show the language name besides it

### ISSUE THREAD

**Issue by codeiotic** [supabase/supabase#3240]
# Feature request
The Doc Search should show the programming language name, for example: `Javascript` or `Dart` besides the search results

## Is your feature request related to a problem? Please describe.
When ever I search for a function, suppose `update`, I get some same results but belonging to different programming languages and I am unable to know which result belongs to which programming language.

I want the programming language to be shown besides every search result so that the user doesn't get confused between two similar search results.

## Describe the solution you'd like
A solution that comes to my mind is to get the programming language from the url's that each search result has.

## Additional context

![2021-09-17 (24)](https://user-images.githubusercontent.com/73734376/133805936-6b34ab6c-c86b-40ba-a754-1e9ad08502d3.png)
In the above screenshot, there are two similar results for `auth.update()`, but they both belong to two different programming languages and the user is unable to know which result belongs to which language.

**Comment by kiwicopple** [comment]
thanks @Hallidayo !
