### ISSUE TITLE
Include UNIQUE constraint in Edit Column Modal

### ISSUE THREAD

**Issue by juanzgc** [supabase/supabase#3241]
# Feature request

## Is your feature request related to a problem? Please describe.

Once you create a column - you are no longer able to add or remove a unique key constraint from the UI.

## Describe the solution you'd like

Add the `UNIQUE` constraint toggle item to the Edit Column view.

Currently, the toggle is **only in** the Create a Column view.

Edit Column View:
![image](https://user-images.githubusercontent.com/24414523/133848597-03280268-ebd3-4a99-a409-c9dafdccbcf0.png)

Create Column View:
![image](https://user-images.githubusercontent.com/24414523/133848652-f78f0fc0-0b45-4f47-8794-6b8431bc0e1d.png)

**Comment by awalias** [comment]
thanks @juanzgc I'll loop the front end team in on this

**Comment by joshenlim** [comment]
Gotcha on this - this one's dependent on an API chore here: https://github.com/supabase/postgres-meta/pull/151

**Comment by Zegoverno** [comment]
Hi anyway to add unique constraint based on two columns
