### ISSUE TITLE
Error sending confirmation mail

### ISSUE THREAD

**Issue by wbrijesh** [supabase/supabase#3253]
# Bug report

## Describe the bug

I followed the next.js guide from supabase docs, and when i try to send magic login link i get a window.alert saying Error sending confirmation mail

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Followed tutorial on https://supabase.io/docs/guides/with-nextjs
4. Unable to send magic link

## Expected behavior

Receive magic link via email to email address entered

## Screenshots

<img width="1680" alt="Screenshot 2021-09-19 at 1 43 30 PM" src="https://user-images.githubusercontent.com/28498071/133920411-a11721c6-6188-4ead-9801-b5b7a9679a1d.png">

## System information

- OS: macOS
- Browser Firefox Developer Edition
- "@supabase/supabase-js": "^1.22.6"
- "next": "11.1.2"

**Comment by inian** [comment]
Hi thanks for reporting. We are aware of this, we will be posting updates here and on [our status page](https://status.supabase.io/)

**Comment by inian** [comment]
Update: The issue has been fixed and we are monitoring the situation now.

**Comment by kiwicopple** [comment]
I'll close this for now, but if anyone else experiences issues feel free to message and I'll reopen

**Comment by AJamesPhillips** [comment]
Hi @kiwicopple I'm not certain but I don't think I'm getting signup / password reset emails at the moment.  Perhaps it's just a lag / or something I'm doing wrong but I clicked "send password reset" button in management console and haven't got anything yet.

**Comment by AJamesPhillips** [comment]
Ah, I just tried again now and they're coming through.  Perhaps there was a minor hiccup.

**Comment by emileond** [comment]
Hi, some of the users of my app have recently reported this issue when they create a new account, any workaround I can implement on my end? (fyi, I'm using supabase-js v2)

![image](https://user-images.githubusercontent.com/29111636/204703905-605db931-978b-4996-a7ff-8a2a7478464b.png)

**Comment by fayizqureshii** [comment]
> I'll close this for now, but if anyone else experiences issues feel free to message and I'll reopen

I m facing the same issue

**Comment by dsl400** [comment]
In my  opinion "error sending confirmation email" should not result in 50x being sent to the client.
The user registration process should be decoupled from the email sending process.

**Comment by yarikbratashchuk** [comment]
same issue: ""Error sending confirmation mail"

**Comment by michalkow** [comment]
We have that problem quite often.

**Comment by guiyumin** [comment]
i am having this error right now

is it common ?

**Comment by michalkow** [comment]
@guiyumin it happened once last week for us, but considering we had only 6 signups, I would say it is too common ;)

**Comment by Shawns2759** [comment]
I am having a similar issue.
