### ISSUE TITLE
"Can't find primary key" error from attempting to delete row in management UI

### ISSUE THREAD

**Issue by AJamesPhillips** [supabase/supabase#3258]
# Bug report

## Describe the bug
Tried to delete a row in a table created without a primary key will give an error about not being able to find a primary key:

![DataCurator](https://user-images.githubusercontent.com/526509/133938614-b8acf1b2-6efb-4319-943a-702888a1148b.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table without a primary key.  e.g.:
```sql
CREATE TABLE your_table2 (
  id uuid NOT NULL DEFAULT uuid_generate_v4()
);
```
2. Select a row and try to delete it.

## Expected behavior

Should delete or UI should not let you select a row without table having a primary key.

**Comment by AJamesPhillips** [comment]
If you add another field like "title" of type text and allow it to be nullable, and then just press save it also errors in the same way.  But if you give it a title like "a" then it works fine

https://user-images.githubusercontent.com/526509/133939272-4c86cadd-7059-4f21-a9c8-32474f3ae212.mov

.

**Comment by kiwicopple** [comment]
This is correct behaviour @AJamesPhillips - it would be too dangerous for us to attempt to delete a row without being certain which row is supposed to be deleted

we could hide the "Delete" button, but then people would wonder how to delete a row - it's better to show them the delete, then tell them why it will fail

> not let you select a row without table having a primary key
this is useful for other operations (download etc)

**Comment by AJamesPhillips** [comment]
@kiwicopple yes both my suggestions are incorrect.  Perhaps the delete button could be disabled and a help message like: "Please add a primary key to enable delete"?  Perhaps it could be presented when hovering over the button and or hovering over a warning triangle :warning: / help ⓘ icon next to the disabled button?

Or perhaps the current error could be extended to read: "Can't find primary key.  Add a primary key to your table to enable deleting."

I'll let you decide if you want to close this issue.

**Comment by kiwicopple** [comment]
Fixed! 
<img width="381" alt="image" src="https://user-images.githubusercontent.com/10214025/147582287-3975ce79-faff-4e60-875d-f65216f7a06b.png">

**Comment by todeit02** [comment]
I have a combined unique constraint on multiple rows like
```
CREATE TABLE IF NOT EXISTS public.my_table (
  a uuid NOT NULL,
  b my_enum NOT NULL,
  c text NULL,
  CONSTRAINT my_table_a_b_unique UNIQUE (
    a,
    b
  )
);
```

Should this not be sufficient for being able to unambiguously delete a row, even with just a single non-null unique field?
