### ISSUE TITLE
Syntax error at or near ")"

### ISSUE THREAD

**Issue by AJamesPhillips** [supabase/supabase#3259]
# Bug report

## Describe the bug

Admin UI errors when inserting a new row.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new table using:
```
CREATE TABLE IF NOT EXISTS some_table2 (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY
);
```
2. Open up the table editor and click "Insert row"
3. See error

## Expected behavior

Inserts row

## Screenshots

![DataCurator](https://user-images.githubusercontent.com/526509/133939057-f1131293-326c-4f87-bf0a-2e434e7dba6a.png)

## Additional context

Works fine if you manually copy and paste a valid UUID into the id form field.

**Comment by AJamesPhillips** [comment]
If you add another field like "title" of type text and allow it to be nullable, and then just press save it also errors in the same way.  But if you give it a title like "a" then it works fine

https://user-images.githubusercontent.com/526509/133939272-4c86cadd-7059-4f21-a9c8-32474f3ae212.mov

**Comment by joshenlim** [comment]
the fix for this is now ready on our dashboard! :)
