### ISSUE TITLE
Fine grained access roles for organization team members

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#3261]
# Feature request

Currently all users in a organisation are admin users. We need more fine grained access roles for collaborators within an organisation.

To start off with, we can have something basic like

* admin access
* read only access
* billing access

For the community: please add additional access controls that would be useful for you below.

**Comment by ramonbrugman** [comment]
In the organisation dashboard u can assign special handle roles! So u can choose who can see what and where. Its a pain in tne ass to assign all individuals 1by 1

**Comment by roryw10** [comment]
I have had some folks who are working with contractors and only want to give them permissions to access certain aspects of their project. For example access to a specific table or restricting access to a specific table, or to have / not have permissions to make changes to the APIs and auth etc.

**Comment by gascenciom1998** [comment]
Additionally our org could use different permissions for different projects. e.g. I'd like to give most of my team members full access to our staging db, but only read access to our prod db

**Comment by dwelle** [comment]
> In the organisation dashboard u can assign special handle roles! So u can choose who can see what and where. Its a pain in tne ass to assign all individuals 1by 1

@ramonbrugman what are you referring to specifically? I couldn't find anything other than member roles (owner, admin, developer), which does not allow any fine grain control at all.

**Comment by kiwicopple** [comment]
closing this since it was released during the last Launch Week - under your Organization's settings (under the "Team" tab) 🎉

**Comment by gascenciom1998** [comment]
@kiwicopple I only see Developer, Owner and Administrator roles. This thread is about fine-grained control con who has read and write access. I.e. giving a specific developer write access while the rest dont have write access.
