### ISSUE TITLE
Error loading data Unexpected token A in JSON at position 0 when open project in dashboard

### ISSUE THREAD

**Issue by zgramming** [supabase/supabase#3264]
https://user-images.githubusercontent.com/38829404/133990507-4a0209b6-3541-4d9f-a4c2-00c954928e10.mp4

I just realized, just today it happened that my project dashboard page couldn't be opened, before there was no problem.

I thought the first time it might be due to internet problems. But after I test speed, there is no problem with my internet.

Then to make sure again, I created a new project. Turns out it can be opened properly.

It's problem with the server ?

For testing, i open 2 browser side by side for comparison. Left side is **chrome** and right side **Edge**.

**Comment by zgramming** [comment]
![image](https://user-images.githubusercontent.com/38829404/133993239-7cfc579d-975b-48a0-a8c5-4d3c160123e9.png)

Server return **504** indicate request timeout.

**Comment by kiwicopple** [comment]
this should now be fixed! If you're still having issues feel free to comment and I'll reopen
