### ISSUE TITLE
"Create new credentials" for Apple Auth can be improved

### ISSUE THREAD

**Issue by mikob** [supabase/supabase#3266]
# Bug report
On https://app.supabase.io/project/[project-id]/auth/settings
Currently the apple "Create new credentials" link goes to: https://developer.apple.com/account/ios/certificate

## Expected behavior

It should link to https://developer.apple.com/account/resources/identifiers/add/bundleId
instead. The first step is to add a bundle id, according to the docs: https://supabase.io/docs/guides/auth/auth-apple (also would be convenient to have these docs linked to somewhere in the UI in my screenshot below)

## Screenshots

![image](https://user-images.githubusercontent.com/492864/134083088-8e5f4a35-5441-4307-8376-6bd2232c0468.png)

Happily would open a PR for this, but it seems there's no GH repo for the Supabase webapp?

**Comment by awalias** [comment]
hey @mikob thanks for opening the issue and the clear description, we'll check it out

**Comment by awalias** [comment]
hey @mikob this has been patched and will be deployed to the prod dashboard soon, thanks again
