### ISSUE TITLE
Unable to delete user from authentication

### ISSUE THREAD

**Issue by josh4500** [supabase/supabase#3283]
# Bug report

## Describe the bug

Error Deleting user failed: update or delete on table "users" violates foreign key constraint "objects_owner_fkey" on table "objects"

I have a table "users" which I can't delete and didn't use any of the value from Authentication.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Authentication'
2. Click on 'more (...)'
3.  Click on ' Delete user'

## Expected behavior
User should be removed from the table.

## Screenshots
Authentication 
![Screenshot 2021-09-22 090840](https://user-images.githubusercontent.com/61246632/134306590-bec694db-2f8b-4c55-8767-a26cf7a2ab0f.jpg)

User table
![Screenshot 2021-09-22 091118](https://user-images.githubusercontent.com/61246632/134306923-db9c7eb9-f1ec-4303-b8d1-732927333b39.jpg)

## System information

- Browser : Chrome

**Comment by bnjmnt4n** [comment]
See https://github.com/supabase/storage-api/issues/65.

**Comment by kiwicopple** [comment]
Hi @bnjmnt4n - it looks like you are "referencing" the user from another place in your database - maybe in one of your `public` tables. You would need to delete that data first before you can remove the user, or you can use [cascade deletes](https://stackoverflow.com/questions/11504699/postgresql-on-delete-cascade).

This is less of a bug, and more of a Postgres functionality. I'll move this to a discussion!
