### ISSUE TITLE
Database error saving new user

### ISSUE THREAD

**Issue by Flowko** [supabase/supabase#3292]
# Bug report

## Describe the bug

I cant register new users, the signup service keeps on returning 'Database error saving new user'

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Try to register new users by sending email and password to supabase.auth.signUp()

## Expected behavior

Register users, and receive confirmation email

## Screenshots

![image](https://user-images.githubusercontent.com/35883748/134406058-3811876f-54c5-43e8-a285-267cd63512ca.png)

## System information

- OS: Windows
- Browser: chrome
- Version of supabase-js: 1.22.3
- Version of Node.js: v14.16.1

**Comment by kiwicopple** [comment]
Hi @Flowko, have you attached any triggers to your User table which could be blocking the insert of new users? Are you seeing the same behavior using the same code on a new project?

**Comment by Flowko** [comment]
thanks for replying @kiwicopple, yes totaly forgot to mention that, ive created a view to merge between users from auth and public table, idk if thats the issue here, if yes, is there another way to get the same results without resulting in the same issue as above ?

**Comment by Flowko** [comment]
@kiwicopple so ive dropped that view, but still facing the same issue, plus i dont have any triggers attached to my users table 
![image](https://user-images.githubusercontent.com/35883748/134488911-2e25a53c-4bb0-4056-8907-7f02d0c61436.png)

**Comment by Flowko** [comment]
ah found it, it was realted to the public users table, i removed a column, and forgot to remove it from the function that copies the userfrom auth to public users table

**Comment by kiwicopple** [comment]
all good!

**Comment by joewinke** [comment]
Future debuggers, look here: https://github.com/orgs/supabase/discussions/5289#discussioncomment-4598998
