### ISSUE TITLE
Ability to resend a follow up invitation/confirmation link in auth dashboard aside from magic link

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase#3329]
Aside from magic link, add ability to resend confirmation link after a day or two to follow up user that didn't continue to verify their email that leads to customer churns.

**Comment by saltcod** [comment]
Hey @sandbox-apps! 

Just checked on this one and looks like you are able to re-send the login link! Not sure when this one was added. 

Going to mark this issue as closed, thanks for filing it!

<img width="301" alt="CleanShot 2022-09-26 at 17 00 40@2x" src="https://user-images.githubusercontent.com/105593/192363596-264070c7-8c5a-4817-bb22-9601a4c2a968.png">
