### ISSUE TITLE
Blog post layout broken by links on mobile

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/supabase#3347]
# Bug report

## Describe the bug

In blog posts, links don't wrap and create a white column at the right of the page because of overflow on mobile.

## To Reproduce

Go to https://supabase.io/blog/2021/09/28/supabase-hacktoberfest-hackathon-2021

## Screenshots

![Screenshot_20210928-165905_Brave.jpg](https://user-images.githubusercontent.com/69633530/135113546-712d8550-d485-4a07-97c1-a8f4e1ba0ca3.jpg)

## System information

- OS: Android 10
- Browser: Twitter embedded webview using Brave

**Comment by kiwicopple** [comment]
Nice catch @florian-lefebvre - we should fix this asap

**Comment by kiwicopple** [comment]
Looks like this was fixed here: https://github.com/supabase/supabase/pull/3352

**Comment by florian-lefebvre** [comment]
Yes !
