### ISSUE TITLE
autogenerated default value for uuid columns

### ISSUE THREAD

**Issue by lIIIIIIIIIIIIIIIIIIIII** [supabase/supabase#338]
# Bug report

## Describe the bug

unable to set default value `uuid_generate_v4()` for column from user interface

## To Reproduce

Steps to reproduce the behavior.

1. Edit table with column of type uuid
2. Enter default value  `uuid_generate_v4()`
3. Save
4. Leads to Error Notification with Message. `JSON parse Errror .....`

## Expected behavior

Would have expected, that default value had been applied to column. Equal to,
 `ALTER TABLE <table> alter column <column> set DEFAULT uuid_generate_v4();`

or some sort of other input possibilities.

## Screenshots
![grafik](https://user-images.githubusercontent.com/55026679/101268086-c4e9a780-375f-11eb-9330-c192f71de8f7.png)

**Comment by kiwicopple** [comment]
Hi @lIIIIIIIIIIIIIIIIIIIII , can I check that you can run that in the SQL editor? Perhaps the `uuid` extension is in the `extensions` schema, which would require it to be:

`ALTER TABLE <table> alter column <column> set DEFAULT extensions.uuid_generate_v4();` 

?

**Comment by lIIIIIIIIIIIIIIIIIIIII** [comment]
hi @kiwicopple , feel free to do so. There is nothing you can break.

**Comment by lIIIIIIIIIIIIIIIIIIIII** [comment]
to avoid misunderstandings, a small screen capture. Btw thx for the reply :)

`ALTER TABLE <table> alter column <column> set DEFAULT extensions.uuid_generate_v4();` works fine and gets the job done.

![cap](https://user-images.githubusercontent.com/55026679/101339546-dd9caf00-387e-11eb-9386-5136c72264ae.gif)

**Comment by soedirgo** [comment]
Omitting `extensions.` should work fine as well, the problem was the default value is treated as a literal string. The error message is a known issue and is unrelated to uuid columns.

We'll fix this soon - thanks for reporting @lIIIIIIIIIIIIIIIIIIIII!

**Comment by TheTrainor** [comment]
Also ran into this error when working from DataGrip. Adding the 'extensions' prefix solved the issue.

**Comment by lIIIIIIIIIIIIIIIIIIIII** [comment]
> 
> 
> Omitting `extensions.` should work fine as well, the problem was the default value is treated as a literal string. The error message is a known issue and is unrelated to uuid columns.
> 
> We'll fix this soon - thanks for reporting @lIIIIIIIIIIIIIIIIIIIII!

thx for the effort

**Comment by soedirgo** [comment]
@TheTrainor Sorry, looks like you still need the prefix outside the SQL editor because you're connecting as `postgres` instead of `supabase_admin`. @kiwicopple should we change the `search_path` for the `postgres` role as well?

**Comment by kiwicopple** [comment]
@soedirgo good idea to add it to the search path

**Comment by sturmenta** [comment]
any updates of this?

https://user-images.githubusercontent.com/30802967/157813005-045ec173-31f2-45d2-82db-e581bf9bfb45.mov

**Comment by sturmenta** [comment]
using SQL Editor

https://user-images.githubusercontent.com/30802967/157814480-c203a0e3-0d27-4a0c-ad69-d410682fad56.mov

**Comment by sturmenta** [comment]
solved by 
 
 1) deleting the current column (type = int8)
 2) create a new column with the type = `uuid` & the default value = `uuid_generate_v4()`
 
 https://user-images.githubusercontent.com/30802967/157815381-8d4eb772-5ae3-4008-b020-58668f9e1ffe.mov

<img width="662" alt="Screen Shot 2022-03-11 at 03 35 31" src="https://user-images.githubusercontent.com/30802967/157815598-f79a9b29-ccb3-40a0-8a74-3f00298810ee.png">

**Comment by paradise-point** [comment]
Since the upgrade to 13.3, `gen_random_uuid()` works for me.

**Comment by StanDC** [comment]
This issue seems to be back. 
Using SQL, a row can be inserted and the default function generated value is inserted.  
However through the GUI,  an error is displayed. 
Trying to type in words such as: Default, Null or even gen_random_uuid()   displays the same error with the attempted word.

![image](https://github.com/user-attachments/assets/95e6904d-3841-4505-a42f-8f395b9fc513)
