### ISSUE TITLE
Managing User Data

### ISSUE THREAD

**Issue by pmauchle** [supabase/supabase#3390]
# Improve documentation

## Link 
https://supabase.io/docs/guides/auth/managing-user-data

## Describe the problem

The documentation isn't wrong on this one, just a little confusing. First, it's all about the profiles table and then in the end there's a trigger on `public.users` instead of `public.profiles`

If you follow the steps you get a broken authentification.

## Describe the improvement

Switch the trigger example from `public.users` to `public.profiles`

**Comment by kiwicopple** [comment]
Thanks @pmauchle - i've made the changes based on your recommendation. As soon as it's approved I'll merge it in
