### ISSUE TITLE
Generate magic link with JWT to get access token

### ISSUE THREAD

**Issue by viperfx** [supabase/supabase#341]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the login method can be used to generate a magic link that is sent via email. I would like to generate a JWT access token so it can be used to login users via a magic link.

Ideally, I would like to have an API key and Secret or similar, that's generated per Team, or Account for security. So external can use it to sign the JWT and generate their own access token.

## Describe the solution you'd like

On my app I would like to generate an API key and secret, or just an API key. Then using a JWT library, sign the token with data to authenticate users.

```
var jwt = require('jsonwebtoken');

var PrivateKey = '35216f3b-9ce1-335a-955b-3a6d8f1a6504'; // from my web  app given to the user

function createToken(user) {
  var userData = {
    email: user.email,
    id: user.id,
    name: user.name,
  };
  return jwt.sign(userData, PrivateKey, {algorithm: 'HS256'});
}
```

With this I can hopefully do SSO so users can login via a magic link or silently authenticate them.

**Comment by kiwicopple** [comment]
Hi @viperfx. Sorry for the delays - I think you sent this as we were hitting beta. Busy time.

I am not too sure I follow your use-case, so bear with me. Perhaps you can use the `supabase.auth.api.refreshAccessToken()` method?

Usage: https://supabase.io/docs/gotrue/client/api-refreshaccesstoken

You would generate a user, which will give back a token and a refreshToken. You can then use the `refreshToken` to generate access tokens for your users.

Would that work? Or maybe the `sendMagicLink` method? https://supabase.io/docs/gotrue/client/api-sendmagiclinkemail

**Comment by awalias** [comment]
Hey @viperfx I can't think of an easy way to enable multiple role based JWT secrets in a secure (and fast) way today

the solution that springs to mind here is [SAML SSO](https://yyhh.org/blog/2020/04/how-to-enable-saml-sso-with-self-hosted-gotrue-and-git-gateway/) which is already supported by our [auth server](https://github.com/supabase/gotrue) but not yet implemented on the supabase dashboard - if it's useful then we can look at adding this to the roadmap

**Comment by viperfx** [comment]
No worries. I understand it may be out of scope for now. Since this use case was important for me, i did switch to firebase auth. Feel free to close this if you need.
