### ISSUE TITLE
Local postgres database not created on init?

### ISSUE THREAD

**Issue by ianstormtaylor** [supabase/supabase#3414]
### Describe the bug

After running the steps listed in the [Local Development](https://supabase.io/docs/guides/local-development) docs…

```bash
$ supabase init
✔ Port for Supabase URL: · 8000
✔ Port for PostgreSQL database: · 5432
✔ Port for email testing interface: · 9000
✔ Project initialized.
Supabase URL: http://localhost:8000
Supabase Key (anon, public): ...
Supabase Key (service_role, private): ...
Database URL: postgres://postgres:postgres@localhost:5432/postgres
Email testing interface URL: http://localhost:9000

Run supabase start to start local Supabase.
```
```bash
$ supabase start
✔ Started local Supabase.
```

…I expected to be able to do…

```bash
$ psql postgres
psql: error: FATAL:  database "postgres" does not exist
```

…to connect to the local database that would have been created by init, but no database was created. (Even though the `DATABASE_URL` points to one.)

### Expected behavior

The database should have been created and setup with the `auth.*` schema.

Am I missing something?

**Comment by soedirgo** [comment]
Hey @ianstormtaylor, the Node.js CLI is being deprecated - I need to update that page. Can you see if [this](https://github.com/supabase/cli/tree/new/examples/tour) works for you?

**Comment by kiwicopple** [comment]
This should be fixed now with the new Go CLI. Closing this issue, but feel free to comment here if you're still experiencing the issue @ianstormtaylor and I'll reopen
