### ISSUE TITLE
The `postgres` role doesn't have access to newly created tables?

### ISSUE THREAD

**Issue by ianstormtaylor** [supabase/supabase#3415]
### Describe the bug

Confused by this, but if I create a new table in the UI, and then try to `SELECT` or `INSERT` into it with the "Connection Pooling" connection (using the `postgres` role) I get the following error:

```
error: permission denied for table test
```

This happens even without enabling row-level access control.

### Expected behavior

I thought the `postgres` role would have permissions to all objects by default? (Especially ones created through the dashboard.)

None of the creating tables examples have any extra permissions-granting steps. When I first created the database I restored some data from a previous backup, might that have messed up permissions somehow? Very unclear.

Am I doing something wrong?

**Comment by kiwicopple** [comment]
> I thought the postgres role would have permissions to all objects by default? 

Yes, that's correct.

> to SELECT or INSERT into it with the "Connection Pooling" connection 

Which tool you're using to connect to the DB when running these queries? Is there a reason you're using the Pool? (not that it should matter, will just help to debug)

> When I first created the database I restored some data from a previous backup, might that have messed up permissions somehow? Very unclear.

That's possible. If I can't replicate the problem using the dashboard I'll figure out if I can replicate using this method

> Am I doing something wrong?

No you're not doing anything wrong. Let me double check that we haven't had any regression on the dashboard

**Comment by ianstormtaylor** [comment]
@kiwicopple thanks for the quick reply.

> Which tool you're using to connect to the DB when running these queries? Is there a reason you're using the Pool? (not that it should matter, will just help to debug)

I'm using the NPM `pg` package to connect, with the connection string copied from **Database > Settings > Connection Pooling > Connection string**. I'm using the pool because it's from a Next.js API route lambda function.

**Comment by ianstormtaylor** [comment]
A bit more information for you. If I run the following SQL to check privileges:

```sql
select *
from information_schema.table_privileges
where table_name = 'test'
```

The only role I see in the `grantee` column for the table created via the UI is `supabase_admin`. (This isn't true for other tables in the `public` schema which were created from the restore process.)

**Comment by kiwicopple** [comment]
Thanks for the extra info - that helps. As a workaround, you can do:

```sql
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
```

I tested with a new project and it seemed fine, so you're probably right - likely to be a problem with a restore from dump. 

> When I first created the database I restored some data from a previous backup, might that have messed up permissions somehow?

Are you using `psql` to restore the database (with the settings under Settings > Database)? Or is it restoring from a "paused" project?


----

FYI my successful attempt:

1. create a new project
2. create a table `test_table` from the Table Editor
3. inserted 2 rows
4. ran this code in a [repl](https://replit.com/join/lsxbgdpfkg-kiwicopple)


```js
const { Client } = require('pg')

const client = new Client({
  user: 'postgres',
  host: 'db.project_ref.supabase.co',
  database: 'postgres',
  password: 'password',
  port: 6543,
})
client.connect()

const cb = (err, res) => {
  if (err)  console.log(err.stack)
  else console.log(res.rows[0])
  client.end()
}

client.query('SELECT * from public.test_table;', cb)
```

**Comment by ianstormtaylor** [comment]
Thank you, that's helpful!

I think you're right that it was due to the restore. What I did was pipe `pg_dump | psql` originally to load ~50 large tables from a previous database provider I was using into Supabase when I created the project. But there might have been some logic in the dump that changed how `public` schema permissions were setup.

I looked over the existing grants:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/311752/135899249-036f8bd8-8abe-4f2a-8b0e-ce89f42938bf.png">

And it does seem like all the imported tables didn't get permissions extended to anyone but `postgres`—which would likely be a problem as soon as I start trying to use the PostgREST API I'd assume.

And I found [this file](https://github.com/supabase/supabase/blob/master/docker/volumes/db/init/00-initial-schema.sql) too which was helpful. I think specifically these lines might restore the default behavior for the future:

https://github.com/supabase/supabase/blob/d1d6278913f5a752253a3d47a0d4adabd3bfaf7a/docker/volumes/db/init/00-initial-schema.sql#L37-L43

I think the biggest thing that would have helped me (not knowing much about granting privileges in PG before running into this) was a page in the docs describing each of the roles that Supabase uses. I found reference in different places to many different names:

- `anon`
- `authenticated`
- `service_role`
- `postgres`
- `supabase_admin`
- `supabase_auth_admin`
- `supabase_storage_admin`
- `dashboard_user`
- `pgbouncer`
- `authenticator`

Explaining what they are for, and what permissions they need to have to work properly. (Also potentially eliminating some of them, because it feels like a lot, but obviously that's not my call.)

---

**Follow up question:** Do I need to grant those `tables`, `functions`, `sequences` privileges to all of these grantees: `anon`, `authenticated`, `dashboard_user`, `postgres`, `service_role`, `supabase_admin`?

**Comment by soedirgo** [comment]
> I think the biggest thing that would have helped me (not knowing much about granting privileges in PG before running into this) was a page in the docs describing each of the roles that Supabase uses.

Agreed, we're still figuring out the best way to model the roles/permissions ourselves 😅

> Do I need to grant those tables, functions, sequences privileges to all of these grantees: anon, authenticated, dashboard_user, postgres, service_role, supabase_admin?

I think using the SQL in the setup you linked is sufficient - you probably don't want to grant access to private schemas to `anon` for example.

Btw, note that `GRANT ... TO ...` as Copple mentioned is necessary for already existing stuff, while `ALTER DEFAULT PRIVILEGES ...` in the linked SQL is for stuff created in the future. You'll need both.

**Comment by kiwicopple** [comment]
> Also potentially eliminating some of them, because it feels like a lot, but obviously that's not my call.

We're debating this internally, it would be a lot easier for anyone who wants to use Supabase as a "DBaaS", although each does serve a specific purpose.

In the meantime, I'll document each role and detail what purpose it has 👍

**Comment by ydennisy** [comment]
Hey @kiwicopple I was wondering if you had a chance to add more docs for resetting permissions?

**Comment by ludovv** [comment]
> 

I fixed it doing this, but also giving permissions to anon, authenticated and service_role, works like a charm!

**Comment by huy-qn** [comment]
I stumble upon this same problems today. Is there any documentation about it yet?

![CleanShot 2022-03-12 at 16 10 55@2x](https://user-images.githubusercontent.com/2289071/158036801-28654b9b-bb7c-441c-8e80-65f846f439e5.png)

**Comment by ariccb** [comment]
just stumbled across this issue myself as well. Earlier it was mentioned to run this: 

`GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;`

which fixed it for me

**Comment by burmecia** [comment]
This issue has been resolved so to close it, feel free to open a new one if this is still an issue.

**Comment by kiptoomm** [comment]
> Just an FYI - I added some notes on the roles in this PR: #3450
> 
> I'll add some more docs in another PR for migrating and resetting permissions

hey @kiwicopple is there now a way to reset permissions? i too had the experience of losing privileges on my tables after running the pause & restart option on my project. unfortunately i had to delete that project and start anew as i deemed the permissions too corrupted to continue building on it
