### ISSUE TITLE
Critical README example update needed. How can I open a PR? 

### ISSUE THREAD

**Issue by seenickcode** [supabase/supabase#3426]
# Improve documentation

## Link 

Please see my PR https://github.com/supabase/supabase-flutter/pull/32

## Describe the problem

See the PR above.

## Describe the improvement

Do you all allow external PRs? If not, can you update the docs?

**Comment by darora** [comment]
Hey @seenickcode - thanks for the PR. The one you put up on the flutter repo[^1] should suffice; I'll let @phamhieu or @dshukertjr accept it as the most active contributors on that repository.

Looks like the quickstart[^2] already uses an await, so it should just be the readme that you've updated.

I'm going to close this issue as the PR is sufficient by itself.

[^1]: supabase/supabase-flutter#32
[^2]: https://supabase.io/docs/guides/with-flutter#main-function

**Comment by seenickcode** [comment]
Thank you, @darora

**Comment by seenickcode** [comment]
Thank you guys!
