### ISSUE TITLE
SSL error when using Flutter + Supabase

### ISSUE THREAD

**Issue by takenoto** [supabase/supabase#3427]
# Bug report

I'm developing a flutter app using supabase. Everything was working normal last week (I didn't test it for like ~5 days). Yesterday I was doing some debug and feature development and it all started: the Flutter plugin can't find a secure connection with the server, so it doesnt allow me to use it.

I printed data, error and error message properties of ".execute()" answer.
They are:

**data**
null

**error?.message**
HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))

I don't know what am I doing wrong. Someone can help? I'm filling this as a bug because it was working previously...

## To Reproduce

(This is in Dart)
```
final answer = await client.from('lbcs_free').select('*').execute();
     
  print(answer.data);
   
   print(answer.error);
   
    print(answer.error?.message);
```
Where lbcs_free is my table name

Output:

> I/flutter ( 5562): null
> I/flutter ( 5562): Instance of 'PostgrestError'
> I/flutter ( 5562): HandshakeException: Handshake error in client (OS Error:
> I/flutter ( 5562): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))
> 

## Expected behavior
I was expecting an array of rows as usual. The data is empty/null.

## System information

- Flutter (Channel stable, 2.2.3,)
- O.S.: Android 6.0.1, Samsung Galaxy On7

## Additional context

The web dashboard is working fine. It doesn't work when running on my device.

-

My english is kind of rusky but I hope you can understand it 👍

**Comment by kiwicopple** [comment]
Hi @takenoto , can you please send your project details through to support@supabase.io? We'll check this asap

**Comment by darora** [comment]
Consolidating to https://github.com/supabase/supabase-dart/issues/54 as this is a dart specific issue.
