### ISSUE TITLE
Clicking on autosuggest in table setup (database) does not work

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#3465]
# Bug report

## Describe the bug

When clicking the autosuggest items in the table creation: nothing happens.

## To Reproduce

1. Go to Database UI
2. Click "create new table"
3. Add a column e.g. `hash`
4. Choose `uuid` as type
5. Click inside value field
6. Click auto suggested `uuid_generate_v4()`
7. See that clicking the autosuggest does not work

## Expected behavior

When clicking the auto-suggested value it must fill the field respectively (in this case: `uuid_generate_v4()`

## Screenshots

https://user-images.githubusercontent.com/9058762/136651377-4eaad189-57eb-4cb8-997e-c064eecc7eb7.mp4

## System information

- OS: macOS
- Browser (if applies): Firefox 93.0

**Comment by kiwicopple** [comment]
this seems to be fixed now - tested on Mac + FF. Let me know if you're still having issues and I can reopen
