### ISSUE TITLE
Landing page logo should redirect to / and not /new

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#3512]
# Bug report

## Describe the bug
If you hover over the icon of the top nav bar as such:
![image](https://user-images.githubusercontent.com/19742402/137180878-e5378e8a-bfe6-4099-8988-4e9223774173.png)

You'll notice that the url is pointing towards supabase.io/new instead of supabase.io - it should be pointing towards the latter

Separately, going to /new seems to be redirecting multiple times
![image](https://user-images.githubusercontent.com/19742402/137180980-ec4b88b8-5d35-4e82-aade-4b16074504e2.png)

**Comment by Darshank2002** [comment]
can I work on this?

**Comment by Isaiah-Hamilton** [comment]
Any News?

**Comment by Darshank2002** [comment]
Sorry for late response ! 
But I'm not able to reproduce this scenario locally.
I'm getting 404 on localhost:3000/ but localhost:3000/new takes me to the homepage

**Comment by inian** [comment]
We moved to a [new setup](https://github.com/supabase/supabase/pull/3691) today and that should fix this issue
