### ISSUE TITLE
Cannot Enable Email Signup Authentication option and disable "Enable email confirmations"

### ISSUE THREAD

**Issue by Aniruddhax** [supabase/supabase#3516]
# Bug report

## Describe the bug
Bug is appearing after Enabling "Enable Email Signup" in dashboard.
and also during disabling "Enable email confirmations"

Error Message
`Update config failed: Stripe: Argument "subscriptionExposedId" must be a string, but got: null (on API request to `GET /subscriptions/{subscriptionExposedId}`)`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Dashboard'
2. Click on 'Enable Email Signup'
3. Click on 'Enable email confirmations'
4. The error will appear in top right corner of the Window
5. See error

## Screenshots
![Error](https://user-images.githubusercontent.com/88134275/137194945-4fd4b971-9dc5-42cc-a7b2-adbf6ea9ae67.PNG)

**Comment by kiwicopple** [comment]
this should now be fixed!
