### ISSUE TITLE
`postgres` does not have permission on `auth` schema

### ISSUE THREAD

**Issue by clouedoc** [supabase/supabase#3517]
# Bug report

## Describe the bug

When trying to back up the `auth` schema of my PostgreSQL database, I found out that `postgres` does not have permission to `SELECT` on the `auth.refresh_tokens_id_seq` sequence.

See error:

```bash
$ pg_dump $POSTGRES_CONN_STR --data-only -n public -n auth > ./backup/supabase_data.sql
pg_dump: error: query failed: ERROR:  permission denied for sequence refresh_tokens_id_seq
pg_dump: error: query was: SELECT last_value, is_called FROM auth.refresh_tokens_id_seq
```

## To Reproduce

```bash
$ pg_dump $POSTGRES_CONN_STR --data-only -n public -n auth > ./backup/supabase_data.sql
# will result in the error pasted above
$ psql $POSTGRES_CONN_STR
postgres=> GRANT USAGE, SELECT ON SEQUENCE auth.refresh_tokens_id_seq TO postgres;
ERROR:  permission denied for sequence refresh_tokens_id_seq
# ^ we can't grant permissions
postgres=> SET ROLE supabase_admin;
ERROR:  permission denied to set role "supabase_admin"
# we can't log in as superuser either
```

## Expected behavior

`postgres` should have permission to access everything in the `postgres` database.

## Additional context

Project ID can be communicated privately if needed. Our RLS is a bit messed up right now so I'm afraid of posting it publicly 😄.

This issue might be related to #3415

**Comment by soedirgo** [comment]
Glad it worked 👍
