### ISSUE TITLE
no postgis column-types in table-editor with enabled postgis-extension

### ISSUE THREAD

**Issue by ffischer1984** [supabase/supabase#361]
# Bug report
no geometry-column-type found 

## Describe the bug
can't find geometry-type despite enabled postgis-extension

## To Reproduce

1. enabled the postgis-extension:
![image](https://user-images.githubusercontent.com/8037710/101839185-33ed4480-3b42-11eb-91d1-970bb613b051.png)

2. no postgis-column-geometry-type in the table-editor (in Add new column part):
![image](https://user-images.githubusercontent.com/8037710/101839351-862e6580-3b42-11eb-91e7-5ed2f8338d20.png)

## Expected behavior

1. After enabling an extension automatically execute an "CREATE EXTENSION <<extension-name>>;"-command.
2. Check if the installation was successfully with display the extension-version. In postgis this will happen with:
SELECT postgis_version()

## Screenshots

![image](https://user-images.githubusercontent.com/8037710/101839185-33ed4480-3b42-11eb-91d1-970bb613b051.png)
![image](https://user-images.githubusercontent.com/8037710/101839351-862e6580-3b42-11eb-91e7-5ed2f8338d20.png)

## System information

- Windows
- chrome
- probably  the alpha one (6.0.2?) which is on https://app.supabase.io/

**Comment by kiwicopple** [comment]
Yeah our table editor at the moment only supports very basic types. We need to figure out a good way to support PostGIS, but also all other extension types. We'll look into this @ffischer1984 

J&J FYI! @joshenlim @MildTomato

**Comment by manqobasukati** [comment]
Related to postgis, How do I execute PostGIS related queries which include `ST_CONTAIN`?

**Comment by kiwicopple** [comment]
For the API, I'm in the process of exposing some of the PostgREST config in the API settings, specifically [db-extra-search-path](https://postgrest.org/en/v7.0.0/configuration.html#db-extra-search-path), and then you will be able to add schemas to the API to access these functions

![image](https://user-images.githubusercontent.com/10214025/108845070-ebf59e00-7617-11eb-8252-274995ca83ce.png)

Should be done by the end of the week 👍 

For the table editor UI, we will need a bit more time

**Comment by varna** [comment]
You can add it manually for now:
<img width="675" alt="CleanShot 2021-12-29 at 15 14 16@2x" src="https://user-images.githubusercontent.com/6717694/147666157-4cf1f2ef-fddf-4ca0-a632-779791b75150.png">

```SQL
ALTER TABLE table_name
ADD COLUMN geom geometry;
```

**Comment by panchicore** [comment]
Dears, 3 days ago the extension types were appearing, I was able to create a geometry field:

![Captura de Pantalla 2022-05-25 a la(s) 12 17 54 p  m](https://user-images.githubusercontent.com/108517/170324457-ef9efaed-df5f-4627-bb4c-eb6c307af93d.png)

But today the dropdown is rendering "pg data types" options only:

![Captura de Pantalla 2022-05-25 a la(s) 12 17 09 p  m](https://user-images.githubusercontent.com/108517/170324633-af7cde14-c808-4585-b553-09b47dbdfed9.png)

Please restore back the options to the dropdown to make this more no-code friendly 🐹

**Comment by burmecia** [comment]
As a workaround, you can use SQL Editor to add postgis column directly, like this page did https://geoexamples.com/svelte/2021/07/18/svelte-supabase-maps.html/

**Comment by alphanumericaracters** [comment]
Anyone has an answer to store coordinates on a column that can be reading by Google Maps?

Im doing an app (flutterflow) with 10 year old kids, that catch the Lat and Long of their actual markers, to store the location of their climate sensors. 

Then values are send to supabase (like: -89.123456 -98.654321) but Gmaps doesn't accept Float, Int, Text for their Markers. i try sending separated and coma separated in all formats supported, but nothing works.

Even activating "Gis" Extension doesn't apear "coordinate" or "point" type column (A week from activating the extension)

**Comment by alphanumericaracters** [comment]
> As a workaround, you can use SQL Editor to add postgis column directly, like this page did https://geoexamples.com/svelte/2021/07/18/svelte-supabase-maps.html/

This is the actual link: https://geoexamples.com/svelte/2021-08-08-svelte-supabase-tracking/

**Comment by GaryAustin1** [comment]
I'm going to close this as it appears the dashboard is leaning towards users using SQL for more complex column types.  If you know how to use an extension with a "special" data type, you should be able to add it in the SQL editor.   Plus extensions keep getting added and supported extra column types for all of them would be complex.

**Comment by alphanumericaracters** [comment]
Ok Gary i understand. I know to write SQL code, functions, etc. 

But in Argentina... Some 10 year old kids They even know how to write well on paper, my question was to make their lives easier (I had to teach math and English from scratch). 

My idea was to introduce them to code next year, to give them time to reinforce math and programming logic (with ESP32, sensors and C++) and not get them stuck with programming languages, algorithms and data structure.

I did some client-side functions and others in the DB with some triggers to make them work. Even so...  _**(IN CASE ANYONE IS INTERESTED)**_

in NoCode tools, it's best to use Firebase Collections (It is native to Google MAPS) for that specific type of tables and columns, especially when they're large lists of points, geometries, etc.

**Comment by GaryAustin1** [comment]
Just adding a note:  The dashboard UI seems to pickup extension types if they are installed in public schema.   Now whether your extension can/should be installed in public schema versus extensions schema you would have to investigate.
