### ISSUE TITLE
Connection terminated unexpectedly when altering table

### ISSUE THREAD

**Issue by haydn** [supabase/supabase#3688]
# Bug report

## Describe the bug

The Postgres connection gets terminated (I see a "Connection terminated unexpectedly" error) when I try execute the flowing code in a migration script (using Knex.js):

```js
exports.up = function (knex) {
  return knex.schema.renameTable("employees", "people");
};
```

Here's the SQL generated by Knex.js:

```sql
alter table "employees" rename to "people"
```

I also see a similar issue error if I jump into DBeaver and try to run that same SQL:

![image](https://user-images.githubusercontent.com/27211/139156905-aae1ef7a-f4f0-4a75-9f92-b3a243a4977a.png)

However, I do not see this problem if I rename a table in the Supabase dashboard (either using the UI or writing SQL).

## To Reproduce

1.  Create a fresh Supabase project
2.  Connect to the database with an SQL client
3.  Create a new table from either the SQL client or the Supabase dashboard (`CREATE TABLE example ();`)
4.  Attempt to rename the table from the SQL client (`ALTER TABLE example RENAME TO example_renamed;`)

## Expected behavior

The table should get renamed.

## System information

I've seen this problem happen in a variety of environments:

- Running Knex.js migrations in Node v14 on Vercel
- Running Knex.js migrations in Node v14 on my local machine (macOS)
- Executing raw SQL from DBeaver on my local machine (macOS)

## Additional context

A few other people on Discord have reported seeing this problem too (using DataGrip and PHPSTORM):

- https://discord.com/channels/839993398554656828/843999948717555735/902862502323445791
- https://discord.com/channels/839993398554656828/902772250791542785/903056602666508328

**Comment by whalesync-ryder** [comment]
I encountered this on `ALTER TYPE`, and burned a bunch of cycles tracking it down, so for future searchers, here's a search hit for `ALTER TYPE`.

**Comment by kiwicopple** [comment]
This was possibly some platform instability, but since there has been no further comments for nearly a year I'm going to close this.

Feel free to comment if you're experiencing this and we'll jump back into it 👍
