### ISSUE TITLE
Add link to Discord server in footer

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#3716]
# Feature request

Adds an icon that links to the Discord server in the footer. Also, any other links that may need to be added.
<img width="1280" alt="Screen Shot 2021-10-29 at 8 17 38 PM" src="https://user-images.githubusercontent.com/70828596/139513375-ee578718-457a-4e40-ad5b-a842558e9dca.png">

**Comment by yeganathan18** [comment]
Hi @Isaiah-Hamilton ,
I couldn't assign the issue myself, would mind assigning the issue for me?

**Comment by Isaiah-Hamilton** [comment]
@yeganathan18 Sorry I can't. I don't have the access￼ to assign you to this issue. I already have the code ready just need to make a PR
