### ISSUE TITLE
Improvement: Align wording "Sign in" & "Log in" in app.supabase.io (when logged out)

### ISSUE THREAD

**Issue by madebyfabian** [supabase/supabase#3717]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, when visiting app.supabase.io when I am logged out, I am getting to see this page:
<img width="1704" alt="Bildschirmfoto 2021-10-30 um 08 49 13" src="https://user-images.githubusercontent.com/32813692/139523506-247c441b-cef3-44f0-96e6-7b94e4b15698.png">

Which has inconsistent naming of actions. In the header, it says "Log in", the button says "Sign in". 
It's a very subtle thing, but it tends to confuse me everytime I get to see this screen (which happens often, since i get logged out of supabase every 1-2 days.

## Describe the solution you'd like

Aligning the wordings "Sign up", "Sign in", "Login", "Log out", "Sign out", "Register" etc. to be consistent.

**Comment by Isaiah-Hamilton** [comment]
@madebyfabian wouldn't this be considered a bug?

**Comment by Isaiah-Hamilton** [comment]
@madebyfabian this issue has been fixed.
