### ISSUE TITLE
Authenticate with Supabase Anonymously

### ISSUE THREAD

**Issue by crushingCodes** [supabase/supabase#3722]
# Feature request

## Is your feature request related to a problem? Please describe.

I was hoping for a way to allow authentication to users annomously, and then later they can choose to use email if they want to access from another device. If the signin flow allowed for username signup, that would also work. 

Firebase comes with this feature, more info in the link.
[Authenticate with Firebase Anonymously Using JavaScript](https://firebase.google.com/docs/auth/web/anonymous-auth)

## Describe the solution you'd like
Anonymous signin/signup flow supported by Auth in Supabase.

## Describe alternatives you've considered

I considered using advice from this guide:
[Sign In With Usernames Using Supabase Auth + Serverless](https://lawrencelin.me/posts/supabase-auth)
But that adds additional overhead

## Additional context

The motivation behind this, is that I dont want to collect user personal info just to provide access to my web app. In my case, security is not going to be an issue since there is no personal data, just storing progress for a learning app.

**Comment by kiwicopple** [comment]
Hey @crushingCodes - we're tracking this one in our auth server here: https://github.com/supabase/gotrue/issues/68

Thanks for creating this - it's  a great idea it just requires a bit of refactoring in the auth system

**Comment by crushingCodes** [comment]
@kiwicopple Thankyou, its good to know that its in the pipeline, Ill just use the normal flow until then
