### ISSUE TITLE
Component in dark mode after switched to light mode

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#3727]
# Bug report

Component still in dark mode after switched to light mode.

## To Reproduce

1. Go to Footer on Landing Page
2. Change to light mode
3. Then go up and see the component is still in dark mode

## Expected behavior

To change the background color and text color on theme change for that component.

## Screenshots

<img width="1392" alt="Screen Shot 2021-10-31 at 12 10 48 PM" src="https://user-images.githubusercontent.com/70828596/139592571-9e47eb24-7cf0-45df-8b1d-5a47ac6ae07f.png">

## System information

- OS: macOS v11.6.1
- Browser FireFox v93.0
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Unless this was intentional this should be fixed.

**Comment by prathonit** [comment]
If you mean the "Build in a weekend, scale to million" banner component, then I think it is supposed to have a dark background both in light and dark mode.

**Comment by Isaiah-Hamilton** [comment]
@prathonit Thank you, I was just making sure that it was intended.
