### ISSUE TITLE
Todo example: empty input after successful insert

### ISSUE THREAD

**Issue by gazdagergo** [supabase/supabase#3738]
# Feature request

## Is your feature request related to a problem? Please describe.

After adding a todo item in https://supabase-nextjs-todo-list.vercel.app/ app the input field keeps its value.

## Describe the solution you'd like

I'd expect that the input field will be reseted to empty after the successful insert.

**Comment by kiwicopple** [comment]
Thanks @gazdagergo - this one is just an example of how to use Supabase inside a Nextjs app. You're welcome to submit a PR for this if you want but it's probably not something that we'll fix as it's just a demo :)

thanks for taking the time to create the issue though!
