### ISSUE TITLE
auth guides has 404 in video playback

### ISSUE THREAD

**Issue by Deep-Codes** [supabase/supabase#3739]
# Bug report

## Describe the bug

404 url in video , hence it doesn't play

## To Reproduce

Visit https://supabase.io/docs/guides/auth

Try to play one of the video after the YT embed

## Expected behavior

it should play

<img width="1429" alt="Screenshot 2021-11-02 at 2 34 09 PM" src="https://user-images.githubusercontent.com/61158210/139817209-e61e3259-53e1-4c59-831b-ab04a02068d1.png">

<img width="1433" alt="Screenshot 2021-11-02 at 2 34 48 PM" src="https://user-images.githubusercontent.com/61158210/139817302-a3be6f6e-13da-4ad7-97e5-f764ddea9633.png">

**Comment by kiwicopple** [comment]
thanks for this @Deep-Codes - fixing asap
