### ISSUE TITLE
Multiple broken links on marketing pages

### ISSUE THREAD

**Issue by MarcMogdanz** [supabase/supabase#3743]
# Bug report

## Describe the bug

Multiple `404 Not Found` pages on the marketing page

## To Reproduce

Visit the following links:
- [https://supabase.io/humans.txt](https://supabase.io/humans.txt) (linked from the footer on the [main page](https://supabase.io/) + "Want to work with us?" when [creating a new issue on GitHub](https://github.com/supabase/supabase/issues/new/choose))
- [https://supabase.io/lawyers.txt](https://supabase.io/lawyers.txt) (linked from the footer on the main page)
- [https://supabase.io/.well-known/security.txt](https://supabase.io/.well-known/security.txt) (linked from the footer on the main page + [security policy on GitHub](https://github.com/supabase/supabase/security/policy))
- [https://supabase.io/feed.xml](https://supabase.io/feed.xml) (linked from code on the main page `<link rel="alternate" type="application/rss+xml" href="/feed.xml"/>`)
- [https://supabase.io/rss.xml](https://supabase.io/rss.xml) (linked from the footer on the [about page](https://about.supabase.com/))

## Expected behavior

No `404 Not Found` page or remove the links to the non-existing pages

**Comment by kiwicopple** [comment]
Thanks for this one @MarcMogdanz - will fix asap
