### ISSUE TITLE
Error: cannot read property 'table' of undefined when trying to delete a column

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#375]
# Bug report

## To Reproduce
1. Go to Database > Tables > some table > Hover a column > Delete
2. Column is not deleted and in the bottom right corner the message appears: Error: cannot read property 'table' of undefined

Unfortunately I don't remember what was special about this column. Maybe it was unique, maybe of type uuid, but not sure.

## Expected behavior
The column is deleted without any errors, maybe with a warning / prompt to confirm

## System information
- OS: Ubuntu Desktop 20.04
- Browser: Chromium

**Comment by inian** [comment]
Hi @peachp the fix for this has been deployed. Can you check if this problem is solved? Thanks!

**Comment by peachp** [comment]
Seems to work now! Thought I didn't have the original column anymore where I had this error, so I just created a new one and deleted it.
