### ISSUE TITLE
New Project Page not Scrollable

### ISSUE THREAD

**Issue by rajan-kz** [supabase/supabase#3752]
Next button does not appear while creating a new project, if resolution is zoomed in.

I have a small screen. I was created a new project and I did not find next button to proceed. I have done it before, it used to work. I have tried different browsers also. The next button is not visible in the window.

## To Reproduce
1. Set system zoom to 150% on Full HD screen
2. Create new project
3. next buttom does not apprear

## Expected behavior
Next button to be visible in any resolution

## Screenshots
![image](https://user-images.githubusercontent.com/39906424/139900994-2388730e-64b1-4471-8dde-904e2e2690a8.png)

**Comment by MildTomato** [comment]
fixed in next dashboard release today 🚀
