### ISSUE TITLE
Wrong error message when trying to set a PK column to "Allow emtpy"

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#376]
# Bug report

## Describe the bug
This totally makes sense, but the error message could be better.

## To Reproduce
1. Go to Database > Tables > A table
2. Hover a PK (unique) column > Click Edit
3. Try to tick "Allow empty"
4. Error: unexpected end of JSON input

## Expected behavior
Either hide the "Allow empty" on PK columns, or disable it and show a hint why it can't be ticked on PK columns

## System information
- OS: Ubuntu Desktop 20.04
- Browser: chromium

**Comment by kiwicopple** [comment]
@joshenlim - I agree with @peachp 's suggestion here to hide the "Allow empty" on PK. Perhaps you can add this to your open PR?

**Comment by kiwicopple** [comment]
Forgot to check back in on this one - we no longer show this checkbox on PK fields 👍 

Thanks @peachp
