### ISSUE TITLE
Insert and other rows code samples: include returned data / error

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#377]
# Improve documentation

## Link 
API > TABLES AND VIEWS > A table > Insert rows and other except Select

## Describe the problem
Maybe would be good to update other API code sample to be similar like select, with data and error. My first attempt to call insert just run quietly. I had to guess that it also returns data and error

## Describe the improvement
```
let { data: table_x, error } = await supabase
  .from('table_x')
  .insert...
```

**Comment by kiwicopple** [comment]
Agreed @peachp ! I've updated this and it should go out in the next release
