### ISSUE TITLE
Supabase self hosting through docker lacks the postgres-meta image 



### ISSUE THREAD

**Issue by rushilchugh01** [supabase/supabase#3774]
Following the steps here https://supabase.io/docs/guides/hosting/docker bring up everything perfectly but lacks the postgres-meta image. 

The image seems to be missing from docker-compose.yml

I'm not sure if it was intentional or just an oversight ? In case it was an oversight, I can happily raise a PR.

**Comment by soedirgo** [comment]
This is related to https://github.com/supabase/supabase/pull/3521. This is mostly relevant to the WIP OSS dashboard as none of the existing images use it.

**Comment by rushilchugh01** [comment]
Alright, thanks
