### ISSUE TITLE
Can't find my storage buckets. Error  http://localhost:3000/buckets?select=id%2Cname%2Cpublic%2Cowner%2Ccreated_at%2Cupdated_at failed, reason: connect ECONNREFUSED 127.0.0.1:300

### ISSUE THREAD

**Issue by hillkim** [supabase/supabase#3776]
# Bug report

## Describe the bug

When I navigate to the  storage buckets in the dashboard, I cant see my buckets and then the error  
 `http://localhost:3000/buckets?select=id%2Cname%2Cpublic%2Cowner%2Ccreated_at%2Cupdated_at failed, reason: connect ECONNREFUSED 127.0.0.1:300` shows up.
This also happens when trying to create a new bucket or storage folder.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase project dashboard
2. Click on storage icon
3. Wait for the buckets to load 

## Expected behavior

I should be able to access my buckets and also be able to create new folders and buckets.

## Screenshots
![image](https://user-images.githubusercontent.com/25987730/140236380-abb7f619-60bb-4f8b-a7a2-9c98ee7dc5c6.png)

## System information

- OS:  macOS
- Browser  firefox developer edition
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

I have tried to restart the server and it doesn't fix the problem as well

**Comment by thebengeu** [comment]
Thanks for the report! Could you email your project ID to support@supabase.io please?

**Comment by kiwicopple** [comment]
for anyone encountering errors specific to your project, you can also use https://app.supabase.io/support/new (you can find the link in the bottom-left of the Dashboard). This will make it easier for our devs to figure out which project you're having issue with.

I'll close this for now, but feel free to comment if you need me to reopen
