### ISSUE TITLE
Supabase web console - storage management - displays stale (cached) versions of images

### ISSUE THREAD

**Issue by jamesallchin** [supabase/supabase#3784]
# Bug report

## Describe the bug

Supabase web console - storage management - displays stale (cached) versions of images

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the supabase web console
2. Go to Storage
3. Visit a bucket
4. Navigate to an image file
5. Use the supabase API to replace the image with a new image (upsert)
6. Start a new tab - repeat the above steps (except step 5)
7. The supabase web console continues to show the old image

## Expected behavior

Supabase console should show the new version of the image 

Recommendation - the supabase console should always cache bust the image URL

## System information

- OS: Mac OS 
- Browser (if applies) Chrome

**Comment by thebengeu** [comment]
Thanks for the report! I tried to reproduce on MacOS Chrome, but get the newly uploaded image every time.

One thing to note is that the default `Cache-Control` HTTP header if not specified for [upload()](https://supabase.io/docs/reference/javascript/storage-from-upload) is [max-age=3600](https://github.com/supabase/storage-js/blob/72c8bf131601ceb19d4b816d629340503b29be19/src/lib/StorageFileApi.ts#L16).

However, the Supabase dashboard should be creating a new signed URL e.g. `https://*.supabase.in/storage/v1/object/sign/test/test.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0ZXN0L3Rlc3QuanBnIiwiaWF0IjoxNjM2MDkxMTc5LCJleHAiOjE5NTE0NTExNzl9.jE8avBpk4y4Pk3Ri-cJA18pYwmzpPbIAiHC7zpM9mNQ` every time, so I'm not sure why you're observing this behaviour. Could you confirm in Chrome DevTools whether the signed URL for the image is different when you start a new tab?

Also, are you using the `{upsert: true}` option for `upload()`?

**Comment by ichbinedgar** [comment]
I also see this behavior, even if I copy the image url from supabase ui and then past it on a new tab.

**Comment by ichbinedgar** [comment]
However, I solved it by adding random url parameters like `?xyz=h`

**Comment by joshenlim** [comment]
@inian just to follow up from #4395 - i realised that the dashboard is currently already doing cache busting when the user clicks on the item to view the preview, in which we then append a random query string to the end of the URL
![image](https://user-images.githubusercontent.com/19742402/167547672-d1f6b549-ef6b-45d7-9292-aa24b5b79f6f.png)


but if the user selects copy URL directly without opening the file for preview like this
![image](https://user-images.githubusercontent.com/19742402/167547620-675daae1-6f63-4517-b74f-e38227f3165b.png)

that's where the cache-busting logic was missing, will fix that
