### ISSUE TITLE
Request magic link, close app, and click link in E-Mail does not trigger onAuthenticated() 

### ISSUE THREAD

**Issue by christianfl** [supabase/supabase#3789]
# Bug report

## Describe the bug

I used the [Flutter Quickstart guide](https://supabase.io/docs/guides/with-flutter) to integrate supabase with a new mobile app. When the magic sign in link is requested and the app is closed (via Android open app overview) and then the magic link is clicked within the E-Mail, the app gets opened but does not redirect to the page according to onAuthenticated(). Closing and reopening the app after that does trigger the redirect so the session is there and valid!

However, when the magic link is requested and the app just pushed to background (not closed), it works as expected. There is an instant redirect. I am fairly sure I setup my app according to the Flutter Quickstart example.

## To Reproduce

Build an Android app with Flutter using the [Flutter Quickstart guide](https://supabase.io/docs/guides/with-flutter) 

1. Run the app
2. Request sign in via magic link
3. Close the app via app overview swipe gesture
4. Open your mail app and click the magic link
5. The app gets opened but it seems onAuthenticated() does not get triggered. There is no redirect to the desired page.

## Expected behavior

The app should redirect to the page stated in onAuthenticated()

## System information

- OS: Android 11 (GrapheneOS)
- Version of supabase: supabase_flutter 0.2.8

Help is appreciated. Thanks in advance.

**Comment by ZeroPaul123** [comment]
Its a listener. So it will trigger when something happens. This is clientsided so it cant work if the page is closed.

**Comment by christianfl** [comment]
@ZeroPaul123 I guess you are right but on the other hand - this is nevertheless unexpected behaviour, isn't it? Is there maybe some other way to do the redirection after clicking on the magic link with a previously closed app?

**Comment by J0** [comment]
Transferring to the `GoTrue-dart` repo so we can best track this

cc: @dshukertjr

**Comment by dshukertjr** [comment]
Hi @christianfl,

Thanks for reporting this one. Actually, we are about to bring a [new breaking update](https://github.com/supabase-community/supabase-flutter/pull/124) to the supabase-flutter library, which will remove `onAuthenticated`. I will revise the quickstarter guide, but the new update should go live sometime this week. Would it be okay to just way for the update?

**Comment by christianfl** [comment]
@dshukertjr Yes, of course, thanks! We will publish an app using Supabase as the backend to beta at the end of this month. I am curious how this will improve the experience!

**Comment by dshukertjr** [comment]
I would like to close this issue as `onAuthenticated` has been deprecated, and [supabase-flutter v1.0](https://pub.dev/packages/supabase_flutter) has been released.
