### ISSUE TITLE
OSS page returning 404

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#3797]
# Bug report

## Describe the bug

The team might be already aware of this, but opening this issue just in case.
[Supabase OSS page](https://supabase.io/oss) is returning 404. 

Related discussion https://github.com/supabase/supabase/discussions/3751

## To Reproduce

Access https://supabase.io/oss 

## Expected behavior

OSS page should be shown.

**Comment by bnjmnt4n** [comment]
For reference, the OSS page is accessible at https://supabase.io/docs/oss after the recent multi-zone revamp. Maybe a redirect can be made to the new URL, or the team might also want to shift the page back to the main route.

**Comment by dshukertjr** [comment]
@bnjmnt4n Ah, thanks for the note! I was accessing the OSS page from the footer of the top page and that's why I couldn't access it 😂

**Comment by Isaiah-Hamilton** [comment]
#3803 same issue

**Comment by dshukertjr** [comment]
With [this](https://github.com/supabase/supabase/pull/3809) PR, the page no longer returns 404, but `Page Not Found` is still displayed.

**Comment by kiwicopple** [comment]
I think this section

```
      {
        source: '/oss',
        destination: `${process.env.NEXT_PUBLIC_DOCS_URL}/oss`,
      },
```

should be in redirects, rather than rewrites?

Alternatively we could move the OSS page to the main website - that's probably a better option so then we can keep it on the root (not `/docs`), and it's using Nextjs so we can make it look a bit better. I'll keep this issue open if anyone wants to help with this

**Comment by dshukertjr** [comment]
@kiwicopple My attempt of moving the rewrites to redirect was [this](https://github.com/supabase/supabase/pull/3799) PR, but I like the idea of moving OSS page to the root website!
