### ISSUE TITLE
Duplicating table doesn't work

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#380]
# Bug report

## Describe the bug
Doesn't work with or w/o "Duplicate table entries as well" option. Messages were shown that columns were duplicated, but the table is empty (no column, no data)

## To Reproduce
In table editor, right click on the table tame, Duplicate table

## System information
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by awalias** [comment]
Thanks for reporting, will look into it 👌

**Comment by joshenlim** [comment]
Hey there @peachp! Could you share with us the table that you were trying to duplicate? Perhaps you can export the table to CSV through the editor and drop the CSV file here.

**Comment by peachp** [comment]
@joshenlim unfortunately the data is sensitive. Below is the table definition, hope it helps:
![image](https://user-images.githubusercontent.com/47209189/102021824-96c92080-3d7a-11eb-821f-02180838d0b5.png)

**Comment by joshenlim** [comment]
No worries at all! Thanks so much for this too :) We'll look into this!

**Comment by joshenlim** [comment]
Hey @peachp! We found where the error is - nothing to do with your data :) Will be pushing out a fix shortly

**Comment by peachp** [comment]
Cool, thanks!

**Comment by inian** [comment]
Hi @peachp the fix for this has been deployed. Can you check if this is working now?

**Comment by peachp** [comment]
Yes, looking good!
