### ISSUE TITLE
Dropdown for foreign keys

### ISSUE THREAD

**Issue by fuzenco** [supabase/supabase#3801]
I know Supabase isn’t necessarily a full-on admin, but it would be incredible if we could have dropdowns within the row editor when referencing a column in another table. This would be incredible and allow me to focus on the front-end.

**Comment by kiwicopple** [comment]
Hey @fuzenco - could you share a bit more about what you're looking for?

> within the row editor

Is this in the panel that slides out?

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/10214025/140717835-acee191d-279b-4a96-8505-18e3a5568358.png">

**Comment by Korayem** [comment]
@kiwicopple he means for FK columns, the editor should show a dropdown list to select a new value from existing rows on the other table

Example
Product > FK > Category

When editing Product.Category, it will show me a list of Category names

**Comment by fuzenco** [comment]
Correct. Sorry for the delay in replying.
