### ISSUE TITLE
Broken footer links on the website

### ISSUE THREAD

**Issue by yeganathan18** [supabase/supabase#3803]
# Bug report

## Describe the bug

Three links that are mentioned in the footer part of the website are broken.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase website](https://supabase.io)
2. Scroll down to the footer of the page
3. Click either of the three links such as Humans.txt, Lawyers.txt & Security.txt
4. See the Error

## Expected behavior

It should take us to the appropriate pages of the links mentioned

## Screenshots

Attached screen recording from Brave

![screen-rec](https://user-images.githubusercontent.com/63534555/140574422-fb6812f6-4b5a-4bda-a964-6ec70edaefbf.mov)

## System information

- OS: macOS Monterey
- Browser: Brave

## Additional context

Nothing much about the problem, other than mentioned above.

**Comment by Isaiah-Hamilton** [comment]
There is one more links that is broken, and its the open source link.

**Comment by Isaiah-Hamilton** [comment]
This issue was fixed #3809.
