### ISSUE TITLE
Enable Gzip in supaabase kong

### ISSUE THREAD

**Issue by Manuelbaun** [supabase/supabase#3804]
Hi guys, 

I am trying to figure out where I can activate gip in the kongs Nginx conf. Unfortunately, I have not found the nginx.conf somewhere. Can somebody point me in the right direction?

**Comment by kiwicopple** [comment]
Hey @Manuelbaun - is this for self-hosted, or for the Supabase platform? We don't support this on the platform right now, but we will be adding a lot more configuration items in the coming months. 

If this is for self-hosted let me know and I'll see if I can find it in the Kong docs

**Comment by Manuelbaun** [comment]
Hey @kiwicopple , 

it is for a self-hosted project on mine. You could also point me in the right direction. I just could not figure out, how kong uses the ngnix.conf in the context of supabase.

**Comment by kiwicopple** [comment]
Got it! In that case it shouldn't be too difficult - you just need to provide a [custom nginx config](https://docs.konghq.com/gateway-oss/0.9.x/configuration/#custom-nginx-configuration) for your Kong instance.

See a configuration example [here](https://github.com/Kong/kong/issues/409#issuecomment-262352131)

I'll close this one, but if you have any issues feel free to comment again and I can reopen
