### ISSUE TITLE
UX: no feedback for starting / running backup

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#381]
# Bug report

## Describe the bug
When clicking "Backup now", nothing happens (almost made me click twice). Only after 2-4 seconds a new line with backup appears.
It is also not obvious that it is not finished as soon as the new line appears, but is in process for some time. Hard to notice, esp. on big screens.

## To Reproduce
Database > Backups > Back up now

## Expected behavior
When clicking "Backup up now", immediately feed back to the user that something is happening, for example by adding the new backup entry and showing a spinning wheel or simply In progress in brackets after the time and remove it as soon as it is finished

## System information
- OS: Ubuntu Desktop 20.04
- Browser: Chromium

## Additional context
It's backups, so it should be super clear what going on, i.e. when / that a backup was completed successfully

**Comment by awalias** [comment]
I think we have this on a branch @dragarcia ?

**Comment by dragarcia** [comment]
yeap - it's in another branch and should be good to go. We'll just need to merge it in and deploy the changes.

**Comment by inian** [comment]
Hi @peachp, this enhancement has been deployed. Does this make the backup UX better?

**Comment by peachp** [comment]
there is still a delay of 3-4 seconds between clicking on "Backup now" and displaying the loading wheel. I guess it is a bit better and will do for now, but during these 3-4 seconds where nothing happens, I'm asking myself "...have I miss-clicked? ...do I need to click harder? ...is it broken? ...oh, here we go!"

**Comment by dragarcia** [comment]
Hi @peachp, thanks for the feedback! We've since deployed a fix that should solve the delay.
