### ISSUE TITLE
Im getting an internal server error out of the nowhere 

### ISSUE THREAD

**Issue by bit-burger** [supabase/supabase#3814]
# Bug report

## Describe the bug

I can't sign up a user in Supabase, it gives me a "Internal server error"

## To Reproduce

```dart
Future<SupabaseClient> getConfiguredSupabaseClient() async {
  final configData = await File(".env").readAsString();
  dotenv.testLoad(fileInput: configData);

  final supabaseUrl = dotenv.env["SUPABASE_URL"]!;
  final supabaseAnonKey = dotenv.env["SUPABASE_ANON_KEY"]!;

  return SupabaseClient(
    supabaseUrl,
    supabaseAnonKey,
  );
}

void main() {   
    final supabaseClient = await getConfiguredSupabaseClient();
    final password = faker.internet.password(length: 8);
    final email = faker.internet.email();
    final response = await supabaseClient.auth.signUp(email, password);

    if(response.error != null) {
      throw Exception("Error on signup: ${response.error!.message}"); // this is where it fails
    }
}
```

## Expected behaviour

I expected to get a logged in Supabase Client

## System information

- OS: macOS

## Additional context

This is run inside of tests, so far the tests have created around and worked all the time 900 users, but now it appears to be broken as I can't create any new users (I also deleted the 900 users, but it still didn't work

**Comment by kiwicopple** [comment]
Hey @bit-burger - can you please submit your project details? You can use https://app.supabase.io/support/new and then we will be able to look at this asap

**Comment by kiwicopple** [comment]
hey @bit-burger - just another follow up on this one. If there's any way we can help let us know. I'll close this, but feel free to comment here and I can reopen
