### ISSUE TITLE
Inseting many records via editor fails / takes too long

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#382]
# Bug report

## Describe the bug
First tried with few dozens: worked instantly.
Then pasted about 11k INSERTs, waited for about 5min, lost patience and wanted to check if something happens by opening Table editor with Ctrl+click in new tab, but it opened in the same tab and by the looks of it, no new records were inserted.

Second attempt: now only around 1k records. Gave up after 15min (no records inserted).

## To Reproduce
See above

## Expected behavior
Insert all records within 5min or show some indication how long it will take.
Or if the SQL editor is not designed for that, set a limit of chars / lines etc.

## System information
- OS: Ubuntu Desktop 20.04
- Browser: Chromium

## Additional context
Or provide a proper import tool for such volumes of data.

**Comment by awalias** [comment]
The recommended approach here is to use COPY (it's a lot faster) https://www.postgresql.org/docs/12/sql-copy.html

And for larger datasets it's also advisable to run it directly from your machine using psql https://stackoverflow.com/a/33945136

Your DB connection string is available in the settings > DB page on the supabase dashboard
