### ISSUE TITLE
Storage does not work with Next.js image optimization ("url" parameter is valid but upstream response is invalid)

### ISSUE THREAD

**Issue by bennettdams** [supabase/supabase#3821]
# Bug report

## Describe the bug

Next.js provides a convenient way to handle [image optimization](https://nextjs.org/docs/basic-features/image-optimization).
This also works for [remote images](https://nextjs.org/docs/basic-features/image-optimization#remote-images).
Unfortunately, Supabase Storage does not work with it at the moment.

When trying to use it, the response from Next.js will respond with `"url" parameter is valid but upstream response is invalid`.

## To Reproduce

1. Create a fresh Next.js project: `npx create-next-app --use-npm`
3. Add a `next.config.js` in project root to add your Supabase project as a [domain the Next.js will use for images](https://nextjs.org/docs/basic-features/image-optimization#domains):
```js
module.exports = {
  images: {
    domains: ['your-app-id.supabase.co'],
  },
}

```
`your-app-id` is the one where the image is hosted in the Supabase Storage.

3. Add an image component somewhere in your app:
```jsx
import Image from 'next/image'
...
<Image
  src="https://your-app-id.supabase.co/storage/v1/object/avatars/public/your-file-name.jpg"
  alt="alt"
  width={500}
  height={500}
/>
```
For `src`, use the full path of the image. In my case, I use the `getPublicUrl` from the Storage API.

4. `npm run build`
5. `npm run start`

Looking at your browser's dev tools, you can see the request for the image responds with status code 400 and `"url" parameter is valid but upstream response is invalid`.

## Expected behavior

[This error message is not unkown to Next.js](https://github.com/vercel/next.js/issues/27973), but it was fixed already. As other providers (you can e.g. try out an Imgur image) work fine, I assume this has something to do with how Supabase Storage handles these requests.

### Request
![image](https://user-images.githubusercontent.com/29319414/140627460-df596c6b-4a4f-40c4-a4a8-26f7a1df189c.png)
### Response
![image](https://user-images.githubusercontent.com/29319414/140627465-d210c840-f987-43ac-8fbd-e859a833dcec.png)

## System information

- Version of @supabase/supabase-js: 1.25.1
- Version of Next.js: 11.1.2

**Comment by kiwicopple** [comment]
thanks for the comprehensive bug report @bennettdams - we'll look into it

**Comment by thebengeu** [comment]
@bennettdams is the bucket public? Maybe this is a tad unintuitive but the bucket needs to be public for public URLs to work.

**Comment by bennettdams** [comment]
@thebengeu Could you be more specific? What exactly has to be public?

These are my policies:

![image](https://user-images.githubusercontent.com/29319414/140910208-e85a9932-d925-498e-b6b3-b266e717b2f1.png)

![image](https://user-images.githubusercontent.com/29319414/140910262-0a8a4216-09f9-4418-bdb7-0f3128f6d55b.png)

**Comment by bnjmnt4n** [comment]
@bennettdams From the sidebar, you can hover over the bucket name, click the overflow menu and choose the item "Make public".

**Comment by bennettdams** [comment]
@thebengeu @bnjmnt4n That was it! I had to make the bucket public via the UI.

I find it counter-intuitive that
- even though the policy of the bucket allows public `SELECT`
- and I use `getPublicURL` via an instanciated Supabase client (on the server)

...still was not enough for the image being available. Maybe this could be added to [the API of `getPublicURL`](https://supabase.io/docs/reference/javascript/storage-from-getpublicurl)?

**Comment by thebengeu** [comment]
@bennettdams Thanks for the suggestion! I agree that it's counter-intuitive, added a note to the API of getPublicUrl().

**Comment by subhranshudas** [comment]
I dunno why but i am following the straight forward guide in the docs but i get 400 bad request error for the image.

1) My curl Request from the browser - 
`
curl 'https://bsmcqplghysxwniajxbp.supabase.co/storage/v1/object/avatars/https://bsmcqplghysxwniajxbp.supabase.co/storage/v1/object/public/avatars/b7cee1eb-721b-444d-a73d-0902ce600312-0.06600565756712773.jpg' \
  -H 'authority: bsmcqplghysxwniajxbp.supabase.co' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbWNxcGxnaHlzeHduaWFqeGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDUyOTU4ODUsImV4cCI6MjAyMDg3MTg4NX0.4batLA9C0ww9CYBQ4hSiyyYDvNafJN4334Ai6uiOfTs' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlBlZTgxUnpobzM2L21hM0UiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzA1NjA1NjYyLCJpYXQiOjE3MDU2MDIwNjIsImlzcyI6Imh0dHBzOi8vYnNtY3FwbGdoeXN4d25pYWp4YnAuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6ImI3Y2VlMWViLTcyMWItNDQ0ZC1hNzNkLTA5MDJjZTYwMDMxMiIsImVtYWlsIjoic3ViaHJhbnNodS5vcHRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MDU2MDIwNjJ9XSwic2Vzc2lvbl9pZCI6IjYzNjNlMWVmLWFiYTktNGM3YS1hYjU5LTNhNzkwMWFkNTk1NSJ9.MCqY4KT4mpYjAvdU7i-97Y7fJX0HRcUIQewQJeJt-AM' \
  -H 'origin: http://localhost:3000' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
  -H 'x-client-info: supabase-ssr/0.0.10' \
  --compressed
`

2) From the Browser console - 
```
fetch.js:23     GET https://bsmcqplghysxwniajxbp.supabase.co/storage/v1/object/avatars/https://bsmcqplghysxwniajxbp.supabase.co/storage/v1/object/public/avatars/b7cee1eb-721b-444d-a73d-0902ce600312-0.06600565756712773.jpg 400 (Bad Request)
.
.
image-uploader.tsx:40 Error downloading image:  StorageApiError: Object not found
```
image-uploader.tsx:40 - 
```
  useEffect(() => {
    async function downloadImage(path: string) {
      try {
        const { data, error } = await supabase.storage.from('avatars').download(path)
        if (error) {
          throw error
        }

        const url = URL.createObjectURL(data)
        setAvatarUrl(url)
      } catch (error) {
        console.log('Error downloading image: ', error)
      }
    }

    if (url) downloadImage(url)
  }, [url, supabase])
```

But surprisingly the image is showing on the image uploader component's image tag. also the bucket "avatars" is public.
