### ISSUE TITLE
[SEO] Add title and descriptions to pages

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#3828]
# Chore

## Describe the chore

There is basic titles and descriptions missing from many pages in www and web.

folders for these sites are:
`www`
`web`

## an example of how we can improve 

the supabase.io/support page has the following:
<img width="1178" alt="Screenshot 2021-11-08 at 15 45 55" src="https://user-images.githubusercontent.com/8291514/140702956-ef7a3b26-717a-410c-a3cf-491f77d878b1.png">

instead we could have something like:
<img width="1176" alt="Screenshot 2021-11-08 at 15 47 29" src="https://user-images.githubusercontent.com/8291514/140703144-c1cd4096-b6c1-42f2-942e-ecb58fa0ec0e.png">

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by Isaiah-Hamilton** [comment]
Can I be assigned to this? Also, Is there any specific way that I should write the Titles and the descriptions?

**Comment by kiwicopple** [comment]
I think it will depend on the page @Isaiah-Hamilton - perhaps you can add a few and then we can comment on the PR with more direction ? (or no comments if you nail it :) )
