### ISSUE TITLE
In the vue3-ts-todo-list example, authentication still has a few problems

### ISSUE THREAD

**Issue by ykdojo** [supabase/supabase#383]
1. When a user logs in and refreshes the page, the user is logged out again.
2. When I click "Forgot your password?", I seem to get a magic login link, and not a way to change/reset my password.

**Comment by ykdojo** [comment]
I made #384 to fix the first one. I haven't taken a closer look at the second one yet.

**Comment by kiwicopple** [comment]
Ah, @thorwebdev just did this fix - would that also help for `1`? 

https://github.com/supabase/gotrue-js/commit/5de6b7f6e4b94e57d2a589757c10d02a3592d030


- `2` seems odd - is the Network Request going to the `/recover` endpoint?

**Comment by ykdojo** [comment]
> Ah, @thorwebdev just did this fix - would that also help for 1?
Yes, actually updating @supabase/supabase-js fixed it. I should've tried updating it first.. (#390)

Anyway, I'll take a look at the second issue again.

**Comment by ykdojo** [comment]
> 2 seems odd - is the Network Request going to the /recover endpoint?

Yes it is going to the /recover endpoint.

**Comment by ykdojo** [comment]
The email looks like how it's supposed to look, too:

![image](https://user-images.githubusercontent.com/1811651/102137089-25877d00-3e0f-11eb-8719-7bcd54809355.png)

**Comment by ykdojo** [comment]
It looks like the URL that's sent in a password reset email is the same as the one that's sent in a magic login email.
From magic login email: https://<myurl>.supabase.co/auth/v1/verify?token=FNWLEcyMvj2-mksPMFl3JA&type=recovery
From password reset email: https://<myurl>.supabase.co/auth/v1/verify?token=KZ_DXRNK_ftn8uJT0BjXpw&type=recovery

**Comment by awalias** [comment]
for 2. this is the expected behavior - the idea is the user is temporarily logged in, during which time the app should present a password reset form (the app can detect that a password reset has just taken place by checking for `#type=recovery` in the fragment

see [here](https://github.com/supabase/gotrue#get-verify) for the full docs

**Comment by ykdojo** [comment]
@awalias got it, thanks. I think I'll update the frontend so that it'll be able to handle it.

**Comment by ykdojo** [comment]
The strangest thing to me is how this email looks like a magic link email, but it contains the fragment type=recovery:
![image](https://user-images.githubusercontent.com/1811651/102541426-40532f00-4065-11eb-96ca-6981539ae4d1.png)

**Comment by awalias** [comment]
hey @ykdojo this one (`type=magiclink`) is now fixed in prod
