### ISSUE TITLE
 supabase.io/oss page is a 404

### ISSUE THREAD

**Issue by inian** [supabase/supabase#3831]
### Discussed in https://github.com/supabase/supabase/discussions/3751

<div type='discussions-op-text'>

<sup>Originally posted by **rmontgomery429** November  2, 2021</sup>
I was curious about sponsorship and noticed the [supabase.io/oss](supabase.io/oss) page is 404ing right now. Is sponsorship via Github still desirable? If so, is the [supabase.io/oss](supabase.io/oss) page going to come back? Also, how is support and feature request feedback facilitated? Github issues? Slack?</div>

**Comment by soedirgo** [comment]
Seems like this is now on supabase.io/docs/oss? But the data looks outdated.
