### ISSUE TITLE
Hover effect in the buttons are not perfect

### ISSUE THREAD

**Issue by yeganathan18** [supabase/supabase#3835]
# Bug report

## Describe the bug

Hovering over buttons when the site is in light mode, there is no visual changes and are not consistent with the design.

## To Reproduce

1. Go to Supabase
2. Scroll down to the footer section
3. Turn on light mode
4. Hover on over the button on the right side of the navbar
5. Notice the hover effect

## Expected behavior

Hovering over buttons should be consistent with the overall UI

## Screenshots

Attached screenshot,

<img width="1792" alt="Screenshot 2021-11-08 at 8 15 39 PM" src="https://user-images.githubusercontent.com/63534555/140795717-b976bb9c-1154-4b69-953b-f2d322082411.png">

## System information

- OS: macOS
- Browser: Brave

## Additional context

Nothing other than mentioned above!

**Comment by yeganathan18** [comment]
btw, this is an enhancement and not a bug.

Ps: I couldn't add an enhancement label for the issue

**Comment by Aakash-Jakhmola** [comment]
can i take this up @kiwicopple

**Comment by joshenlim** [comment]
@Aakash-Jakhmola sure thing definitely :) 

just to check real quick - @MildTomato is this something that should be fixed from the UI library or the marketing website?

**Comment by Isaiah-Hamilton** [comment]
Currently updating `www` to the lastest version of [supabase ui](https://github.com/supabase/ui) and will fix this issue.
