### ISSUE TITLE
Google sign in shows null user

### ISSUE THREAD

**Issue by dhruvbhatia7** [supabase/supabase#3837]
# Bug report

## I'm signing in with Google and the currentUser and currentSession fields are both null

<img width="293" alt="supabase image" src="https://user-images.githubusercontent.com/943803/140846190-d9dc09a3-2b0b-4140-9f71-2e1953e3fdfd.png">

**Comment by kiwicopple** [comment]
Hey @dhruvbhatia7 - hope we can help here. can you please provide a few more steps to replicate this issue?
