### ISSUE TITLE
supabase init thows error about missing docker-compose

### ISSUE THREAD

**Issue by Seanmclem** [supabase/supabase#3845]
# Bug report

## Describe the bug

I'm on an M1 Mac.

Step 2 of Getting Started
https://supabase.io/docs/reference/cli/supabase-init

I run `supabase init`
And I get `Cannot find docker-compose executable in PATH.`... It seems like I should maybe install docker-compose, or fix the PATH. However, the doc makes no mention of needing to install or configure docker-compose. Did I do something wrong? OR I need to do something more?

Either, this probably shouldn't happen, or there should be a mention of the need to manually do, whatever it is I need to do, in certain scenarios

## System information

- OS: M1 MacOS Big Sur 11.5.2

**Comment by soedirgo** [comment]
Hmm, that part of the docs needs to be updated. Can you follow the instructions in https://supabase.io/docs/guides/local-development instead?

**Comment by Seanmclem** [comment]
> Hmm, that part of the docs needs to be updated. Can you follow the instructions in https://supabase.io/docs/guides/local-development instead?

Thanks, this is definitely the doc I needed. Maybe the other one can link or forward to it somehow? Made a PR: https://github.com/supabase/supabase/pull/3846

I just installed docker from https://docs.docker.com/desktop/mac/install/ and that seemed to do it, but I'll follow along with this doc from here. Thanks again

**Comment by soedirgo** [comment]
Cool! Let us know if you have other problems :+1:

**Comment by Seanmclem** [comment]
> Cool! Let us know if you have other problems 👍

Ok, last thing. How is initializing via `supabase init` fundamentally different from using the `app.supabase.io` website? Can I access my project created from the CLI in the website? OR the other way around? Why would I do one over the other?
