### ISSUE TITLE
Docs and guides barely mention normal email-login

### ISSUE THREAD

**Issue by Seanmclem** [supabase/supabase#3849]
# Improve documentation

A page like [this one](https://supabase.io/docs/guides/auth/intro), and [this one](https://supabase.io/docs/guides/auth) should probably have a section about email-auth but I couldn't find but a small mention. Some pages describe an email-link-login, but not really a typical email-auth, besides [this one](https://supabase.io/auth), a little bit.

I feel like docs / guides could include some detailed sections on Email & password auth

I guess there's [this](https://supabase.io/docs/reference/javascript/auth-signup), but other auth seems so prominently mentioned in those other areas. Maybe a link here

**Comment by kiwicopple** [comment]
Agree - would love some docs for this. Probably 2 pages actually:

- email login
- magic links

I'll mark this as a good first issue and see if anyone would like to contribute. free swag for anyone who does :)
