### ISSUE TITLE
(Show + Edit) trigger activation time in UI Editor

### ISSUE THREAD

**Issue by zakaria-chahboun** [supabase/supabase#3857]
It will be better to show us the trigger activation time: *after* & *before* in the UI editor
Also it will be better to let us edit the *timing* + the *event* too!
 
![image](https://user-images.githubusercontent.com/18173275/141166530-daa03db7-b0c4-4741-b74b-af623e8cadc7.png)

Thanks!

**Comment by kiwicopple** [comment]
While this one is an older issue, it's a great one for newcomers

Basically, the `INSERT` tag should instead be `AFTER INSERT` or `BEFORE INSERT`. Likewise for the other events:

- `INSERT` -> `AFTER INSERT` or `BEFORE INSERT`
- `UPDATE` -> `AFTER UPDATE` or `BEFORE UPDATE`
- `DELETE` -> `AFTER DELETE` or `BEFORE DELETE`

**Comment by ishaanbedi** [comment]
Hi there!
I'd like to work on this. Can you please assign it to me?
