### ISSUE TITLE
Improve documentation for local development

### ISSUE THREAD

**Issue by yeganathan18** [supabase/supabase#3860]
Documentation for setting up and running the supabase website & doc locally should be a little bit clear, few instructions seem to be outdated and couldn't set up the local development.

Ps: I was facing difficulty while setting up the local development initially, in order to contribute.

**Comment by Isaiah-Hamilton** [comment]
> Documentation for setting up and running the supabase website & doc locally should be a little bit clear, few instructions seem to be outdated and couldn't set up the local development.
> 
> Ps: I was facing difficulty while setting up the local development initially, in order to contribute.

The difficulty that was faced was solved is this [discussion](https://github.com/supabase/supabase/discussions/3719#discussioncomment-1598257). I think that the docs should be updated to the answer from that [discussion](https://github.com/supabase/supabase/discussions/3719#discussioncomment-1598257) or updated in a different way.

**Comment by Isaiah-Hamilton** [comment]
Sorry linked the wrong issue
