### ISSUE TITLE
Bypass Row level Security

### ISSUE THREAD

**Issue by Hannes1** [supabase/supabase#3861]
# Bug report

## Describe the bug

Hi, so stated in the documents I can use the service_role key to bypass row level security (in my server), but at the moment this is not working, the table is not being update and no errors are thrown

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialise with the service key
```
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
```
2. Normal supabse call to RLS protected table:
```
    const { user,error } = await supabase
      .from('profiles')
      .update({
        first_name: 'Testing',
        last_name: 'Bypass'
      })
      .eq('user_id', '0fcd924a-d90b-48a2-af43-f7e7df4ca2a8');
```

## Expected behavior

The users first and last name should be changed by the server even with the policies set as (uid() = user_id), but at the moment the table is not being updated..

## System information

- Version of supabase-js: 1.25.2
- Version of Node.js:12#3824 

## Additional

Also opened the issue on [supabase-js](https://github.com/supabase/supabase-js/issues/300#issue-1050736067)

**Comment by kiwicopple** [comment]
This looks fine @Hannes1 - what bug are you facing? is there an error returned?

**Comment by Hannes1** [comment]
@kiwicopple   No error but the user is not being updated user is returned undefined ? But I'm sure the id is correct because when I'm authenticated on my app (with the public key) this function works and updates the first and lastname for example

**Comment by kiwicopple** [comment]
hey @Hannes1 - I wasn't able to replicated this issue. I'll close this, because I suspect it's not really a bug but something to do with your code?

If you can provide some steps to replicated it on my end then I will reopen!

**Comment by shafkathullah** [comment]
@kiwicopple this could be reproducible, once an user logs in, as role then changes from `service_role` to `authenticated`, and if there is no proper RLS for `authenticated` role it will fail like this.

I am having a long support email conversation from last week, but nothing worked still. I am using new `ssr` lib.

<img width="960" alt="Screenshot 2023-11-22 at 6 05 50 PM" src="https://github.com/supabase/supabase/assets/15883435/73898af6-05d9-4948-9bf2-9a9e7624efb6">

See the `Note` in above image, thats something I want to overcome.

As someone intending to use supabase client entirely on server, I feel it will be safe to use `service_role` key to initialise the client(_even safer when using non `NEXT_PUBLIC_*` env name prefix, as Next.js guarantees its exposure strictly only to server_ ). But it breaks once role change to `authenticated` ie, when a login happens.

I understand above stated behaviour is a security feature given that `supabase-js` are made to be isomorphic solution and its risky to give such an access to browser. Even then the new `createServerClient` methods from new `ssr` lib could be an exception to this rule.

Also I understand `RLS` being heavily endorsed by supabase for very good reasons, but at same time I feel there should be 
options for those who want to use `supabase` client libs and not use `RLS`.

I hope the explains issue we are facing and looks forward to hear your solution or clarification if this is rooted from any misconception regarding auth, roles etc.

**Comment by shafkathullah** [comment]
Yes, finally adding a custom Authorization header solved my issue!
```
global: {
      headers: {
           Authorization: `Bearer ${process.env.SERVICE_KEY}`,
      },
},
```
