### ISSUE TITLE
Import pg_dump tables missing auto generated api docs

### ISSUE THREAD

**Issue by simonbarker** [supabase/supabase#3871]
# Bug report

## Describe the bug

I followed the docs to do a pg_dump from one project and then an import in to another, the tables in the new project don't have auto generated api docs.

## To Reproduce

Follow the docs to pg_dump and then import that into another empty project. Go to api page in new project and see there are not auto generated api docs.

## Expected behavior

Auto generated api docs like when manually creating a table.

## Screenshots

N/A

## System information

- OS: Mac OS Catalina
- Browser N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

N/A

**Comment by kiwicopple** [comment]
very strange - the docs are generated from the API (which is auto-generated from the tables). The only thing I can think:

- You've restored to a schema which isn't attached to the API. Did you restore to the `public` schema?
- The API server needs to refresh/restart to pick up the tables.
- There was something cached, and it needs time to pick up changes.

Can you please check again @simonbarker - is it still missing the tables?

**Comment by simonbarker** [comment]
Thanks. Sorry for the delay, I have double checked and it's still not there. To answer your questions:

1. Not sure, I followed the pg_dump export/import process from here https://supabase.io/docs/guides/database from my local terminal
2. I'm not self hosted, this is a pair of projects at app.supabase.io
3. It's been 6 days so probably enough time by now.

What do you recon is the next step? I can interact with the DB fine through the API, just no docs.

**Comment by kiwicopple** [comment]
can you please send your project details here? https://app.supabase.io/support/new

We'll investigate!
