### ISSUE TITLE
Subapase NextJs Small redirect to auth and back

### ISSUE THREAD

**Issue by ZeroPaul123** [supabase/supabase#3888]
# Bug report

## Describe the bug
Hey there. Im using the supabase nextjs tailwind example. For some reason if im reloading the page manually the RequireAuth function always redirects the user to the auth page which then instantly redirects to the original page. It creates a really bad looking flash on the screen.

## To Reproduce

Use the example (https://github.com/supabase/supabase/tree/master/examples/nextjs-auth-tailwind)
I changed the layout but that should change anything and refresh on the profile page.

## Expected behavior

Dont redirect 

## Screenshots

I made console log statements in the AuthRedirect and RequireAuth functions. The AuthRedirect is only called in auth.js and RequireAuth is only called on profile.js

You can see the result here
https://i.imgur.com/eHnXciN.png

## System information

Running on a Linxu Server
Node v16.13.0

## Additional context

If anyone has a solution for this issue please let me know.

**Comment by ZeroPaul123** [comment]
Additional to the flash. If I want to use a href to a page like /settings that causes the page to reload → the user gets redirected to auth which then redirects back to profile. So, all pages apart from profile are completely inaccessible

**Comment by kiwicopple** [comment]
Hey @ZeroPaul123 - this one should be solved now by our Auth Helpers: https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/README.md

Sorry for the (very) slow reply here - sometimes these get lost in the backlog a bit. We're doing a big cleanup this week
