### ISSUE TITLE
Type "http_request" does not exist when using pgsql-http extension

### ISSUE THREAD

**Issue by miro-ur** [supabase/supabase#389]
# Bug report

## Describe the bug

When trying to use the **pgsql-http** extension within the managed Postgres instance of Supabase I get an error : 
**SQL Error [42704]: ERROR: type "http_request" does not exist  Where: SQL function "http_get" during inlining**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Activate http extension in postgres via Supabase UI
2. Try to execute http_get function using the newly activated extension: `SELECT * FROM extensions.http_get('http://httpbin.org/ip');`

## Expected behavior

Return a successful get response with ip address

## Screenshots

Successful response on other Postgres instance:

![screen_capture_20201214_002](https://user-images.githubusercontent.com/20729127/102108779-53fe5b80-3e01-11eb-8752-64bf718d436d.png)

Response when using Supabase Postgres instance:

![screen_capture_20201214_003](https://user-images.githubusercontent.com/20729127/102108522-0b46a280-3e01-11eb-914f-84527b905c43.png)

## Additional context

I have tried to reproduce this on a separate, clean instance of Postgres (via docker) with pgsql-http 1.3.1 extension installed but I was not able to - extension seems to work fine.

[pg.Dockerfile.txt](https://github.com/supabase/supabase/files/5690244/pg.Dockerfile.txt)

**Comment by steve-chavez** [comment]
Hey @miro-ur,

> type "http_request" does not exist 

This could be a `search_path` issue. Try adding `extensions` to the `search_path`.

**Comment by miro-ur** [comment]
Hey @steve-chavez, that was it. I should have thought of that.
Would it make sense to add 'extension' to search_path after spinning up the db as default to make sure extensions will work "out of the box"?

Thanks !

**Comment by kiwicopple** [comment]
We're doing this now @miro-ur - will release this week 👍
