### ISSUE TITLE
SingOut From Serverside

### ISSUE THREAD

**Issue by zakaria-chahboun** [supabase/supabase#3910]
Hi Supabasers!

I have an SSR Web project *(SvelteKit)*.
I did signout like this:
#### from client side:
```js
await supabase.auth.signOut();
```
#### from server side:
I sent an HTTP POST request with `SIGNED_OUT` event to the serverside.
I removed the session cookie and i signed out with `token` like this:
```js
const { error } = await supabase.auth.api.signOut(request.locals.token);
console.log(error): // always { error: null }
```

The problem is the Supabase in the serverside doesn't logged out!
It must logged out when The Session expired or When the user send `singout` request!

**Comment by kiwicopple** [comment]
Did you set a cookie in your serverside route? If so, you'd need to remove/expire the cookie. What code are you using to create the cookie?

**Comment by zakaria-chahboun** [comment]
Also should `supabase.auth.api.signOut();` do the job without the `token` parameter!

**Comment by zakaria-chahboun** [comment]
@kiwicopple 
In supabase auth setting i set the `JWT Expiry` to 1 week.
In my code, The first time i used `supabase.auth.api.setAuthCookie(req, res)` but the session expired after some hours!
So because of that i decided to create a custom cookie session!
Like That:
```js
// SvelteKit hooks
	if (request.method == 'POST' && request.path === '/auth.json') {
		const { session, event } = request.body;
		// Login/SignIn Case:
		if (event == 'SIGNED_IN') {
			const tokenExpires = new Date(Date.now() + session.expires_in * 1000);
			const cookieOptions = { httpOnly: true, secure: false, sameSite: 'LAX' };
			const cookie_session = cookie.serialize('sb:token', session.access_token, { expires: tokenExpires, ...cookieOptions });
			response.headers['set-cookie'] = [cookie_session];
		}
		// Logout case
		else if (event == 'SIGNED_OUT') {
			const cookieOptions = { httpOnly: true, secure: false, sameSite: 'LAX' };
			const cookie_session = cookie.serialize('sb:token', '', { expires: 0, ...cookieOptions });
			response.headers['set-cookie'] = [cookie_session];
			await supabase.auth.api.signOut(request.locals.token);
		}
	}
```

**Comment by zakaria-chahboun** [comment]
@kiwicopple
I found it!
I removed the condition:
```js
if (request.locals.token) {
     supabase.auth.setAuth(request.locals.token);
}
```
And just replaced with *directly*:
```js
supabase.auth.setAuth(request.locals.token);
```

Whatever the `token` is: *null* or a valid token!
When the token == `null`, The user is logged out automatically from the serverside.
