### ISSUE TITLE
Allow users to set the `host` etc for Postgrest endpoints

### ISSUE THREAD

**Issue by chasers** [supabase/supabase#3913]
Let self-hosted users set the `host` etc for Postgrest in a config:

https://postgrest.org/en/v8.0/configuration.html#openapi-server-proxy-uri

**Comment by kiwicopple** [comment]
This is doable in the self-hosted config by adding it to the docker-compose environment variable here:

https://github.com/supabase/supabase/blob/f81feb48a8f1f8b8386c970d36256882873fcbcd/docker/docker-compose.yml#L87

⚡
