### ISSUE TITLE
Select a category is stuck in light on Blog Page

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#3924]
# Bug report

## Describe the bug

`Select a category` is in light mode even when you are in dark mode. This makes the text unreadable.
<img width="1280" alt="Screen Shot 2021-11-16 at 7 46 14 PM" src="https://user-images.githubusercontent.com/70828596/142089824-8875bc3f-8bcf-4535-be6b-c7a8d3cab4ef.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Make sure that you are in dark mode
2. Go to '[Supabase Blog](https://supabase.io/blogs)'
2. Scroll down to 'Select a category'
2. Click on 'Select a category'

## Expected behavior

`Select a category` should be in dark mode.

## Screenshots

Dark Mode:
<img width="1280" alt="Screen Shot 2021-11-16 at 7 46 14 PM" src="https://user-images.githubusercontent.com/70828596/142089824-8875bc3f-8bcf-4535-be6b-c7a8d3cab4ef.png">

Light Mode:
<img width="1280" alt="Screen Shot 2021-11-16 at 7 46 45 PM" src="https://user-images.githubusercontent.com/70828596/142090041-b1a81884-c19b-42d9-b57b-bbab8970ea02.png">

As you can see light mode works just fine, but dark mode needs some work.

## System information

- OS: macOS
- Browser FireFox
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by kiwicopple** [comment]
we can probably make this one a dropdown? http://ui.supabase.com/components/dropdown
