### ISSUE TITLE
deleteUser account

### ISSUE THREAD

**Issue by zakaria-chahboun** [supabase/supabase#3930]
Hi everyone!

I want the user to delete his account so, I did like the documentation said:
```js
// my server side
const { user, error } = await supabase.auth.api.deleteUser(
  userID,
  MY_SERVICE_ROLE_KEY
)
```
I got this error message:
```js
{ message: 'Database error deleting user', status: 500 }
```
knowing that i have already the `ON DELETE CASCADE` on my `public.users` table
And i have also the `ON DELETE CASCADE` on all tables that has a foreign key from my `public.users` table.

#### PROVE 
Like the image bellow, When i delete manually the user from `auth` section, All the data of this user is removed without any error message!
![image](https://user-images.githubusercontent.com/18173275/142286053-8bb77007-cd5d-41ca-9565-f451c62a9341.png)

**Comment by kiwicopple** [comment]
Hey @zakaria-chahboun - I suspect this might be an issue with row level security. 

Can you please share some more details? Perhaps some SQL so that we can reproduce the issue?

**Comment by edelah** [comment]
Same problem using "@supabase/supabase-js": "^1.28.0".

`import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://eemwleknacuzazgnmcoh.supabase.co',
  'XXXXX'
);
const { data } = await supabase.auth.api.createUser({
  email: 'example7@example.com',
});
console.log('data id:', data.id);
const { error } = await supabase.auth.api.deleteUser(
  data.id,
  'XXXXX'
);
console.log('error:', error);`

Console
=========
data id: 441f383e-9cec-4a37-815c-23144a1474e1
error: { message: 'Database error deleting user', status: 500 }

**Comment by zakaria-chahboun** [comment]
@kiwicopple 

Something like that:
![image](https://user-images.githubusercontent.com/18173275/143484139-d7449c9d-397e-4c5a-be95-e89952c37244.png)

As i said when i remove the user account manually from the `auth.users`, All the data of this user is removed successfully.
   
But when i use this method to remove it `await supabase.auth.api.deleteUser`, The error is happens. But happens only if the data is exist in the `table1, table1 and table3`, If no data exist, Then the deletion process is successful!

**Comment by zakaria-chahboun** [comment]
@kiwicopple 
I'm sorry it was my mistake! I already have a trigger to delete all the data of the `table1 2 3`, So i think it cause the trouble between it and the *ON DELETE CASCADE*.

So when i removed the trigger! All things is working fine now!

**Comment by kiwicopple** [comment]
no probs @zakaria-chahboun - thanks for following up! 

We need to make it much clearer where there are triggers attached to the table - we're working on something for this :)

**Comment by zakaria-chahboun** [comment]
@kiwicopple still the same behaviour!

**Comment by kiwicopple** [comment]
Hey @zakaria-chahboun - I'm wondering what solution you're thinking for this? This is default Postgres behaviour - did you want a different error meesage?

**Comment by zakaria-chahboun** [comment]
Oh! that is the default PostgreSQL behavior!

mmm, is there any solution to keep triggers working when we have also the `ON DELETE/UPDATE CASCADE`?

**Comment by kiwicopple** [comment]
I don't know what your triggers are doing, but I am guessing that technically they are "working", and that you have some logic which causes an error.

Can you please share the code for all of your triggers?

**Comment by GaryAustin1** [comment]
@zakaria-chahboun this is the perfect type discussion to have in the Supabase Discord channel.  It is much easier to interact in close to realtime and figure out what your trigger is doing.   Having a delete trigger can definitely be tricky if it is depending on relations that are also being deleted in the cascades.  All depends on what your function is doing.

**Comment by GaryAustin1** [comment]
Going to close this is does not appear to be a bug.  This is probably best solved in Discord if it is still an issue.
