### ISSUE TITLE
Fix images in our Auth Blog post

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#3935]
# Bug report

## Describe the bug

https://supabase.io/blog/2020/08/05/supabase-auth

Some of the images in our Auth blog post aren't loading

<img width="716" alt="image" src="https://user-images.githubusercontent.com/10214025/142351505-0013bae0-2309-46be-a856-5a082d8c48e9.png">

**Comment by yeganathan18** [comment]
@kiwicopple Videos are also not loading it seems

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple When I was checking the code, I couldn't find the video file that the video src was pointing to. Maybe the file got deleted or was moved.
```
<video width="99%" autoPlay="autoplay" loop muted playsInline controls={true}>
  <source src="/videos/auth-zoom2.mp4" type="video/mp4" loop muted playsInline />
</video>
```

**Comment by kiwicopple** [comment]
Looks like the PR above didn't work. The correct URL should be:

```
<video width="99%" autoPlay="autoplay" loop muted playsInline controls={true}>
  <source src="/docs/videos/auth-zoom2.mp4" type="video/mp4" loop muted playsInline />
</video>
```

**Comment by aar2dee2** [comment]
hey, have corrected the links in another PR.

**Comment by kiwicopple** [comment]
thanks @aar2dee2 🙏 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/10214025/142854030-bfde225a-f05c-4b20-8133-c11ce753eccc.png">

**Comment by aar2dee2** [comment]
So the cover image is still not loading.

I added `/docs/img/supabase-auth-cover.png` as the url and https://supabase.com/docs/img/supabase-auth-cover.png resolves correctly.

Similar issue with the other PRs I pushed as well.

**Comment by Isaiah-Hamilton** [comment]
A solution that might work is by putting the videos on something like youtube. Then making the video unlisted so people won't be able to see it on youtube, but be able to use it in the blog post. For example just like the basic demo video on the landing page.
<p align="center">
<img width="800" alt="Screen Shot 2021-11-22 at 12 02 55 PM" src="https://user-images.githubusercontent.com/70828596/142903813-8ec2c167-3aee-481c-907e-4cce3cde627c.png">
</p>
