### ISSUE TITLE
Port typo in the local development docs

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/supabase#3943]
# Feature request

I'm using Supabase (just realized how awesome it is yesterday!!) together with Prisma. I like the DX in prisma - especially the typesafe client.

## Is your feature request related to a problem? Please describe.

I like that you can spin up everything by simply running `supabase start` - that's great. In Prisma I have `prisma migrate reset --force` command that I use to reset all tables and seed the database from a ts file. The issue is that I can't do these command through the `pgBouncer` container but needs to be directly targeted at the `postgres` container, right?

Unfortunately the postgres container doesn't forward any ports so it can't be accessed through localhost.

## Describe the solution you'd like

I'd like postgres to be available on some port on localhost.

## Describe alternatives you've considered

Currently I can work around it by finding the container IP address with the following command

```
docker inspect supabase_db_osv | grep IPAddress
```

but that's cumbersome to do everytime

**Comment by kiwicopple** [comment]
Fixed in the docs!

<img width="536" alt="image" src="https://user-images.githubusercontent.com/10214025/147585823-f5e73b59-ef6e-4388-9426-3714013dd360.png">
