### ISSUE TITLE
Documentation of authentication email variables needed to compose custom templates

### ISSUE THREAD

**Issue by dthyresson** [supabase/supabase#3944]
# Improve documentation

The current Auth docs section seen here:

![Screen Shot 2021-11-18 at 7 08 07 AM](https://user-images.githubusercontent.com/1051633/142413533-86030b65-2e84-4ad6-8251-d93dcf62e895.png)

does not document how to compose a custom email template nor the variable token replacements (ConfirmationURL, SiteURL, etc) available when authoring -- and the rules for enclosing them in double braces.

## Link 

Auth Sign Up section: https://supabase.io/docs/reference/javascript/auth-signup

## Describe the problem

It was found that if

* the replacement branches are improper (ie, using three {{{)
* or, the variable name isn't one of the allowed values

the custom template will not load and emails will be sent with the default template content.

Note: there is no UI help or warning on save if the template is invalid. This will be a separate issue.

## Describe the improvement

* Add section for how to compose templates their rules and variables
* Much of this content is in the GoTrue docs here: https://github.com/supabase/supabase/blob/master/web/docs/gotrue/server/about.md

```
`MAILER_TEMPLATES_CONFIRMATION` - `string`

URL path to an email template to use when confirming a signup.
`SiteURL`, `Email`, and `ConfirmationURL` variables are available.

Default Content (if template is unavailable):

```html
<h2>Confirm your signup</h2>

<p>Follow this link to confirm your user:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm your mail</a></p>
```

`MAILER_TEMPLATES_RECOVERY` - `string`

URL path to an email template to use when resetting a password.
`SiteURL`, `Email`, and `ConfirmationURL` variables are available.

Default Content (if template is unavailable):

```html
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}">Reset Password</a></p>
```

`MAILER_TEMPLATES_MAGIC_LINK` - `string`

URL path to an email template to use when sending magic link.
`SiteURL`, `Email`, and `ConfirmationURL` variables are available.

Default Content (if template is unavailable):

```html
<h2>Magic Link</h2>

<p>Follow this link to login:</p>
<p><a href="{{ .ConfirmationURL }}">Log In</a></p>
```

`MAILER_TEMPLATES_EMAIL_CHANGE` - `string`

URL path to an email template to use when confirming the change of an email address.
`SiteURL`, `Email`, `NewEmail`, and `ConfirmationURL` variables are available.

Default Content (if template is unavailable):

```html
<h2>Confirm Change of Email</h2>

<p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
<p><a href="{{ .ConfirmationURL }}">Change Email</a></p>
```

* Which I found if I searched for the docs https://supabase.io/docs/gotrue/server/about
* So maybe this content is linked or merged "in some way"

## Additional context

See issue and comment: https://github.com/supabase/gotrue/issues/278#issuecomment-971122395

**Comment by luizcieslak** [comment]
Hi! Even though we have a better email template editor now (thank you for that), it seems it's not displaying all the available variables for each one of them.

Here's a quick example;
![image](https://user-images.githubusercontent.com/14146176/184975883-e82cef4e-8be9-4374-9afc-0b9fc1f5e718.png)

You can see that not only `{{ .ConfirmationURL }}` can be used but also `{{ .Email }}` and `{{ .NewEmail }}`.

Another example is the `{{ .Token }}` in the Magic Link email as described in https://github.com/supabase/gotrue/issues/264.

How/where could I report this "issue"?
