### ISSUE TITLE
When configuring custom authentication email templates, ensure template content is valid when saving

### ISSUE THREAD

**Issue by dthyresson** [supabase/supabase#3945]
# Feature request

When setting up a custom authentication email template as seen here:

![Screen Shot 2021-11-18 at 7 08 23 AM](https://user-images.githubusercontent.com/1051633/142415178-adc96e41-d058-4828-92e3-e2743e9f7066.png)

there isn't any information about what variable token replacements are allowed in each email.

While there is some dev documentation in [GoTrue available](https://supabase.io/docs/gotrue/server/about) it sin't easy to reference.

For example:

```
`MAILER_TEMPLATES_CONFIRMATION` - `string`

URL path to an email template to use when confirming a signup.
`SiteURL`, `Email`, and `ConfirmationURL` variables are available.
```

Only those three variables are allowed.

However, the user may still save the template even if it is invalid due to improper formatting or using invalid variables.

![Screen Shot 2021-11-18 at 7 24 37 AM](https://user-images.githubusercontent.com/1051633/142416368-5a2b3a90-a8d1-4b21-b0dc-80491df27973.png)

There was a case where a user added a replacements `<img alt={{{preheater}}}` when in fact the wanted `<image class="preheader"> and what happens is the template is saved, but when GoTrue fetches the template to send outgoing email, if fails to parse and the default template content is used. See: https://github.com/supabase/supabase/blob/master/web/docs/gotrue/server/about.md

## Describe the solution you'd like

* Perhaps ad help or some info for what variables are permitted per template
* Template validation on save to ensure template is ok to be used when actually sending mail.
* Validation incudes syntax for the variable replacement (ie enclosed in double braces) and properly recognized variable names
* Show a preview with mocked data
* Send a preview email with mocked data

## Describe alternatives you've considered

* Validate in Studio app
* Validate via a new GoTrue endpoint

This possible test case in [Netlify's `mailme` which GoTrue](https://github.com/netlify/mailme) uses to fetch and cache the template raises the error if the template is invalid

```
package mailme

import (
	"html/template"
	"testing"

	"github.com/sirupsen/logrus"
)

func TestGet(t *testing.T) {
    var logger = logrus.New()
    
    var cache = &TemplateCache{
        templates: map[string]*MailTemplate{},
        funcMap: map[string]interface{}{},
        logger: logger,
    }

    var temp *template.Template

    data, err := cache.Get("https://app.supabase.io/api/auth/<YOUR_PROJECT_ID>/templates/magic-link")

    if temp != nil {
        logger.Info(data)
    }

    if err != nil {
        logger.Error(err)
        t.Fail()
    }
}
```

## Additional context

See also https://github.com/supabase/supabase/issues/3944 and https://github.com/supabase/gotrue/issues/278#issuecomment-971122395

**Comment by MildTomato** [comment]
> Perhaps ad help or some info for what variables are permitted per template
> Template validation on save to ensure template is ok to be used when actually sending mail.
> Validation incudes syntax for the variable replacement (ie enclosed in double braces) and properly recognized variable names
> Show a preview with mocked data
> Send a preview email with mocked data
> 

This is probably worth splitting up into smaller tasks.

Maybe we concentrate on just trying to validate the template before submitting first.

I've got a design task for auth config to try and re-iterate these pages/forms to improve them based on all the feedback we have, so might be worth completing the design task first before doing any of the rest above.

**Comment by J0** [comment]
to revisit after introduction of Monaco editor for email templates

**Comment by J0** [comment]
Should be fixed with our new email set up -- variables that can be used are clearly displayed at the top.

Feel free to re-open if still unclear though.
Thanks!
