### ISSUE TITLE
Error sending confirmation mail - us-east-1

### ISSUE THREAD

**Issue by johndpope** [supabase/supabase#3948]
# Bug report

org: fundfi/ fundfi

demo here - 
https://signup.covershot.app/

was all working fine up until an hour ago.

<img width="1251" alt="Screen Shot 2021-11-19 at 11 06 33 am" src="https://user-images.githubusercontent.com/289994/142516133-3cb51163-810f-4ec1-8e12-42844682e924.png">

invitations are failing too.
<img width="460" alt="Screen Shot 2021-11-19 at 11 06 38 am" src="https://user-images.githubusercontent.com/289994/142516127-85e132fe-80a1-4998-a13e-b7adb2c9777e.png">

**Comment by haydn** [comment]
Yeah, I'm getting unexpected "Error inviting user" responses from the backend too.

I'm guessing it's related to this incident:

https://status.supabase.io/incidents/lqr0skzn17bd

**Comment by inian** [comment]
Hi everyone, we are aware of this issue and working on getting the systems back up soon.

**Comment by johndpope** [comment]
Thanks / all good.
