### ISSUE TITLE
Search table

### ISSUE THREAD

**Issue by Annie-khalid** [supabase/supabase#3952]
# Feature request

## Is your feature request related to a problem? Please describe.

I have a profile table with multiple fields like name ,email ,location and skills. I want to search profile with name, location and email.
 
## Describe the solution you'd like

I have a search box and if i type any **city name** it should return profiles with matching city and if i type **name** it should return Profiles with matched names.. It is simple if i have 3 search boxes each for name ,email and location but i want to search profiles with single search box. So What i want is, it should search whole table before returning any profile in result.

**Comment by liaujianjie** [comment]
Have you tried [full text search](https://supabase.com/docs/guides/database/full-text-search)? That is, write a Postgres `before insert or update` trigger to update a `ts_vector` column whenever the `name`, `email`, `location`, and `skills` columns change. Then perform full text search on that column.

**Comment by Annie-khalid** [comment]
Thanks ... i found solution for above problem .
Is that possible to compare values of object? For example i have a column **_location_** that have data in the form of object i.e. 
{"value":"Pakistan","dial_code":"+92","code":"PK","label":"Pakistan"} and i want to check if any location is America /Pakistan. I used **_or_** filter 
Here is my code
var { data, error } = await supabase.from('user_profiles').select().or("location.eq.Pakistan); 
but it is not working. Thanks in advance.

**Comment by kiwicopple** [comment]
Hey @Annie-khalid - looks like you need to use the `ilike()` filter: https://supabase.com/docs/reference/javascript/ilike

```js
 var { data, error } = await supabase
   .from('user_profiles')
   .select()
   .ilike('location', 'Pakistan')
 ```
 
 I'll close this one now, but if you need help with any coding questions like this feel free to jump into our [Discussions](https://github.com/supabase/supabase/discussions) or discord: discord.supabase.com
