### ISSUE TITLE
Possible logo bug at https://supabase.com/auth

### ISSUE THREAD

**Issue by IAFahim** [supabase/supabase#3962]
This angular logo is above the content makes look like it's indicating which framework it was created in, but in actual it's not. I got confused but love the project showcase.

![here](https://user-images.githubusercontent.com/63500913/142678959-85ae3c8e-a5c0-4334-a944-deb0fb8025b6.png)

![Screenshot 2021-11-20 at 01-09-41 Auth Built-in user management](https://user-images.githubusercontent.com/63500913/142678384-39fb8cfb-3247-439a-adf7-14ab18d02a74.png)

![Screenshot 2021-11-20 at 01-10-04 Auth Built-in user management](https://user-images.githubusercontent.com/63500913/142678419-74673d22-bbc3-401a-966f-81ece7e1a700.png)

**Comment by Isaiah-Hamilton** [comment]
@IAFahim I can see how this might be confusing at first look. This might be a good first issue for people to work on.
