### ISSUE TITLE
Failing to connect Supabase as Vercel integration

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#3982]
# Bug report

## Describe the bug
I am trying to use Vercel dashboard to connect Supabase as an integration.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://vercel.com/integrations/supabase
2. Click on Add Integration
3. Select scope and project.
4. Click Add Integration
5. Redirects to Supabase integration page, with an error slide-in saying "Retrieve vercel token failed" (screenshot attached)

## Screenshots
<img width="1618" alt="Screenshot 2021-11-21 at 16 38 22" src="https://user-images.githubusercontent.com/725324/142768732-3716ffe8-03d4-49c4-a6ce-6769bf3fbcb2.png">

**Comment by emilioschepis** [comment]
I am experiencing the same issue. Let us know if there are more info we can provide to debug this problem!

**Comment by kiwicopple** [comment]
I think this must have been caused with the migration from supabase.io to supabase.com. Thanks for letting us know!

**Comment by ttariq7** [comment]
+1 Trying to start my project by adding supabase as an integration for this https://github.com/vercel/nextjs-subscription-payments

If there is a temporary workaround. Please let us know. Thank you!

**Comment by emilioschepis** [comment]
If you need a workaround I believe you could just manually add the three environment variables directly to the Vercel settings of your project. I think the integration doesn't do much more than that currently.

**Comment by carlosstenzel** [comment]
![Screen Shot 2021-11-24 at 09 53 56](https://user-images.githubusercontent.com/3890516/143242334-0464e237-7e23-4981-84d0-ba8982945584.png)

@kiwicopple the problem is in URL

**Comment by emilioschepis** [comment]
There might have been some changes, it seems to work for me now! 👍🏻

**Comment by MildTomato** [comment]
We have deployed some changes that should have resolved some issues.
Feel free to reopen this ticket if anyone experiences the same issue.

**Comment by Polyterative** [comment]
My vercel project list is always empty even if I have a project.

![image](https://user-images.githubusercontent.com/16295552/147418976-93ddea80-c578-47a5-a9c7-83301da22ca9.png)

**Comment by M0R155** [comment]
Got the same problem on the same project, trying to connect supabase and vercel gives me this error: 
![supabase](https://github.com/supabase/supabase/assets/5452806/61bb72c2-4658-4512-bebd-40b866a98edd)

https://github.com/vercel/nextjs-subscription-payments
^
Vercel Deploy Button
