### ISSUE TITLE
Generating types for text array is creating the type unknown[]

### ISSUE THREAD

**Issue by mclean25** [supabase/supabase#3983]
# Bug report

## Describe the bug

The types being generated for a postgresql column of `text` array is not being created correctly. I would imagine a text array in PG should map directly to a `string[]`?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with a column of type `text`, and select "define as array"
2. Generate the types for this project from the command line
3. Inspect the type of the column you created. You'll see `unknown[]`

## Expected behavior

Type for generated column above should be `string[]`

## System information

- OS: macOS 12.0.1
- Version of supabase-js: `1.25.2`
- Version of Node.js: `v14.17.4`

**Comment by blaynem** [comment]
Bumping this because i'm running into the same thing and it's a little difficult to use the types in my db when they're `unknown`. Haha

**Comment by kiwicopple** [comment]
We've released a v2 RC, and we've build custom type generators: 
https://supabase.com/docs/reference/javascript/next/typescript-support

Sorry for the delay here - the previous type generators were actually a third-party tool. Now that we do it ourselves we can increase the accuracy of all typing 👍

**Comment by tom-at-pixel** [comment]
I'm seeing the same result in Supabase CLI v1.60.2.

Source Postgresql type:
```sql
CREATE TYPE example_type AS (
  my_text_array text[]
);
```

Generated TypeScript type:
```ts
example_type: {
  my_text_array: unknown
}
```

Am I doing something wrong?
