### ISSUE TITLE
No way to get back to homepage

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#3985]
# Feature request

## Is your feature request related to a problem? Please describe.

When I was signing up to get notified when functions are ready. I noticed that there was no way for someone to back to the home page unless they retype the URL.

## Describe the solution you'd like

A link back to the homepage inside of the Supabase logo or just a back arrow.

## Additional context

This nothing major but something to think about.
<img width="1392" alt="Screen Shot 2021-11-21 at 1 01 41 PM" src="https://user-images.githubusercontent.com/70828596/142773909-bbe142e2-e45d-4e7a-a54e-0115ed7c84aa.png">

**Comment by marpit19** [comment]
> # Feature request
> ## Is your feature request related to a problem? Please describe.
> When I was signing up to get notified when functions are ready. I noticed that there was no way for someone to back to the home page unless they retype the URL.
> 
> ## Describe the solution you'd like
> A link back to the homepage inside of the Supabase logo or just a back arrow.
> 
> ## Additional context
> This nothing major but something to think about. <img alt="Screen Shot 2021-11-21 at 1 01 41 PM" width="1392" src="https://user-images.githubusercontent.com/70828596/142773909-bbe142e2-e45d-4e7a-a54e-0115ed7c84aa.png">

I think adding a link to the logo would be enough

**Comment by luca400** [comment]
Is somebody working on this or can I do it? I'm first time contributor and something easy like this is hard to find.

**Comment by Isaiah-Hamilton** [comment]
@luca400 no one is working on this, and you can work on it.

**Comment by Isaiah-Hamilton** [comment]
@luca400 you can work on it, but a Supabase maintainer or team member would have to open source the code.

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple I clicked on Functions in the product navbar.

<img width="1392" alt="Screen Shot 2021-11-30 at 9 27 01 PM" src="https://user-images.githubusercontent.com/70828596/144160960-cfdc95ec-1eeb-447c-97fd-83b8461ed72b.png">

**Comment by Pulkit3234** [comment]
@kiwicopple Can i work on this issue if nobody is currently working on it?

**Comment by Isaiah-Hamilton** [comment]
@Pulkit3234 Would be awesome for you to work on this but the code is not open sourced yet.

**Comment by Pulkit3234** [comment]
@Isaiah-Hamilton Yes, no problem in that case.
