### ISSUE TITLE
Vote for Connectors

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#4]
This issue is for tracking requests/demand for connectors. Give a comment a thumbs up if you want the connector built. 

Please refrain from adding comments unless you are adding a connector which isn't already listed.

**Comment by kiwicopple** [comment]
Kafka

**Comment by kiwicopple** [comment]
SQS

**Comment by kiwicopple** [comment]
RabbitMQ

**Comment by MrFabio** [comment]
Pub/Sub

**Comment by kiwicopple** [comment]
Webhook
