### ISSUE TITLE
https://app.supabase.io/api/login redirects to a 404

### ISSUE THREAD

**Issue by zevzoldan** [supabase/supabase#4002]
# Bug report

## Describe the bug

Hitting `Start Your Project` (https://app.supabase.io/api/login) on the top right of the home screen directs to a 404 page.  

## To Reproduce

1. Go to [Home](https://supabase.com/)
2. Click on Start Your Project
3. Opens https://app.supabase.io/api/login

## Expected behavior

Looking to start a project!

## Screenshots

![image](https://user-images.githubusercontent.com/15254219/142885911-bd771fac-94d7-4a5b-bbe5-e94382575bce.png)

**Comment by chasers** [comment]
Seems to be working for me.  Can you clear your cache, cookies etc and give it another go?
