### ISSUE TITLE
404 : This page could not be found on supabase dashboard

### ISSUE THREAD

**Issue by Krish-Nerkar** [supabase/supabase#4009]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com/
2. Click on 'Start Project'

## Expected behavior

Open supabase dashboard

## Screenshots

![image](https://user-images.githubusercontent.com/49949733/142982419-d4932680-caae-4de6-8da5-7cfacdbfd293.png)

## System information

- OS:  Windows 11
- Browser : Brave

**Comment by bnjmnt4n** [comment]
This is fixed by https://github.com/supabase/supabase/pull/4008.

**Comment by Isaiah-Hamilton** [comment]
Same issue as #4002.
