### ISSUE TITLE
Allow defining extra search path for triggers

### ISSUE THREAD

**Issue by chipilov** [supabase/supabase#4037]
# Feature request

## Is your feature request related to a problem? Please describe.

PostgREST documentation suggests to split the database into a public and private schema in order to enforce some encapsulation between the public API and the internal implementation (https://postgrest.org/en/v8.0/schema_structure.html).

At the same time, any trigger functions (regardless of whether they are defined in a public or private schema) cannot take advantage of the Extra Search Path setting (in the Supabase dashboard, go to Settings -> API -> Extra search path).

This means that the code in trigger functions needs to explicitly qualify any references to objects in the non-public schema.

## Describe the solution you'd like

It would be great if the Extra search path which can be specified for functions defined in the public schema (i.e. the settings that is available in the Settings -> API dashboard) can also be used for trigger functions.

## Describe alternatives you've considered

I tried defining the trigger functions in the public schema but they still could NOT take advantage of the extra search path.

**Comment by steve-chavez** [comment]
Hm, can you confirm the extra search path is indeed working for functions? It might not be working for triggers functions or regular functions.

(Maybe create a function in your `private` schema and use it on a function in the `public` schema)

**Comment by chipilov** [comment]
Yep, I checked that - the extra search patch is definitely working for functions. 

I added an unqualified reference to a private table inside my function (I also tried with a reference to a private function, the result was the same). Without adding the private schema in the extra search path I get this error:

```
{"message":"relation \"my_table\" does not exist","code":"42P01","hint":null,"details":null}
```
As soon as I add the private schema to the extra search path, the call succeeds.

**Comment by steve-chavez** [comment]
Thanks @chipilov.

Hm, it's weird it doesn't work on triggers. The `Extra Search Path` in the UI corresponds to PostgREST's [db-extra-search-path](https://postgrest.org/en/v8.0/configuration.html#db-extra-search-path).

Could you try reproducing with just PostgREST?

**Comment by steve-chavez** [comment]
> Could you try reproducing with just PostgREST?

@chipilov Or maybe just share a reproducible example here(the DDL) and I'll check if it indeed trigger functions don't work with db-extra-search-path.

**Comment by chipilov** [comment]
@steve-chavez I don't have access to the config file for PostgREST - I don't have Supabase setup locally yet.

I have an additional schema named "private" and inside I have a table called "runtime_log" where I store logs. Here is a reproducible example with that setup (I define all schema objects with the postgres role):

```
CREATE OR REPLACE FUNCTION private.test_trigger_function()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO runtime_log(level, message)
  VALUES ('INFO', 'Inserted new user');

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS test_trigger_function_after_user_insert ON auth.users;
CREATE TRIGGER test_trigger_function_after_user_insert
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION private.test_trigger_function();
```
This makes the sign-up call fail with the following response (note that the insert into the ```runtime_log``` table does NOT explicitly qualify the table):

```
{"code":500,"msg":"Database error saving new user","error_id":"679ed001-27b1-4fa1-8e6c-463b568bb6b8"}
```

As soon as I qualify the the insert statement to refer to ```private.runtime_log```, it works.

The I've set the Extra search path setting in the Supabase dashboard to ```public, private, extensions```.

Let me know if you need more info.

**Comment by steve-chavez** [comment]
> This makes the sign-up call fail with the following response 

Oh, what's the `sign-up` call? Calling the [supabase.auth.signUp](https://supabase.com/docs/reference/javascript/auth-signup) js function?

If that's the case, then that would explain why `Extra search path` doesn't work - the `supabase.auth` functions pass through https://github.com/supabase/gotrue and here that setting is not considered.

**Comment by chipilov** [comment]
Yep, it's exactly ```supabase.auth.signUp()```.

So I guess the feature request should be to allow adding Extra search path to GoTrue calls? Do you know if that's even possible? Do you have any suggestion about how to workaround this (other than explicitly qualifying objects in triggers)?

**Comment by steve-chavez** [comment]
> So I guess the feature request should be to allow adding Extra search path to GoTrue calls? Do you know if that's even possible?

Yes, should be possible. I'd suggest asking on https://github.com/supabase/gotrue/issues.

> Do you have any suggestion about how to workaround this (other than explicitly qualifying objects in triggers)?

Hm, that's the best workaround I'd say. I'm not sure what postgres role gotrue uses for its queries(something that could be asked on its repo as well), but it should also be possible to include your schema in its search path like: `ALTER ROLE <role> SET search_path TO one, two..`, this would need a gotrue restart(db reconnection) for it to work.

**Comment by kiwicopple** [comment]
Hey @chipilov - perhaps you could also include the search path in the function

```
CREATE OR REPLACE FUNCTION private.test_trigger_function()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private -- this line here
AS $$
BEGIN
  INSERT INTO runtime_log(level, message)
  VALUES ('INFO', 'Inserted new user');

  RETURN NEW;
END;
$$;
```

This is recommended anyhow - see "Writing SECURITY DEFINER Functions Safely" in these docs: https://www.postgresql.org/docs/current/sql-createfunction.html

That being said, you're giving "security definer" access to a private schema - so you might want to consider any security risks. In this case I can't see any problems, I just want to make you're aware of the risks:

> a SECURITY DEFINER function is executed with the privileges of the user that owns it

**Comment by chipilov** [comment]
Thanks for the tips, @kiwicopple!

I didn't know about pg_temp, so I will most likely follow your advice and set the search path on the trigger function definition.

With regards to accessing a private schema from a SECURITY DEFINER function - I think I understand the risks and have a reason for doing this, but I will start another thread in the discussions section to make sure I am not missing something.

Finally, I opened a separate issue in the GoTrue repo as suggested by @steve-chavez: https://github.com/supabase/gotrue/issues/293
