### ISSUE TITLE
Optimize blog post images

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#4090]
# Chore

## Describe the chore

Help us to optimize the size of the images in these posts:

- https://supabase.com/blog/2021/11/26/supabase-launch-week-the-trilogy
- https://supabase.com/blog/2021/11/26/supabase-how-we-launch

## Additional context

We were very tired, forgive us for the sloppy work 😴

**Comment by FatumaA** [comment]
working on this

**Comment by Isaiah-Hamilton** [comment]
Was this issue fixed with #4091?

**Comment by Dev-TT** [comment]
I see the images are 4800x3200 
whats the required optimized size you need?

**Comment by kiwicopple** [comment]
Not fixed yet! I think anything around 1000px is great 👍
