### ISSUE TITLE
Migrate schema and data

### ISSUE THREAD

**Issue by schonert** [supabase/supabase#4092]
# Improve documentation

I have hard time imagining how to migrate the schema and data. Can't really find any documentation about this and I can't see how I would effectively manage the evolving schema without migrations. 

What am I missing? 🤓

**Comment by elhe26** [comment]
Me too. I have 2 envs (dev/prod) and I want to duplicate everything. I can't find any info regarding that.

**Comment by elhe26** [comment]
hey @schonert, I found a way to manipulate all schemas.

I'm using Pycharm Professional with database tools (you could use something else).

# Step 1 - Connect to Supabase using JDBC connector

### Go to `settings/Database`. 

![image](https://user-images.githubusercontent.com/16799511/143662586-98ed47c8-6cab-4e86-8853-45ee237abe55.png)


### Copy the JDBC connection string
_*Optional*: Download the SSL cert. if you want to prevent snooping_ 


# Step 2 - Configuring the SQL viewer
_ Using Pycharm with Database Tools_


### Creating connection
![image](https://user-images.githubusercontent.com/16799511/143662510-26be2f88-453c-4463-aeb7-28e52f3b4fc2.png)


### Adding JDBC connection string
![image](https://user-images.githubusercontent.com/16799511/143662617-738a38e9-a73e-4d16-b876-fdf9f74a78bb.png)


### Optional - Change project password

To change the project password, you need to go to SQL Editor from supabase:
![image](https://user-images.githubusercontent.com/16799511/143662663-1a23097f-a183-47f8-beb7-50c6d2706c09.png)

Add the following query:
sql```
alter user postgres with password 'new_password';
```

Now we can modify and export all schemas.

**Comment by elhe26** [comment]
@schonert If this solves your inquiry, please feel free to close the issue. 

Regards,

**Comment by J0** [comment]
Going to take the liberty to close this in view of the time that has lapsed + @elhe26 's solution.

Please feel free to re-open if you are still facing issues though -- we'd be happy to help. Alternatively, feel free to shoot us a mail at support@supabase.io.

Thanks!
Joel
