### ISSUE TITLE
Studio startup failed

### ISSUE THREAD

**Issue by Mozzior** [supabase/supabase#4099]
# Bug report

## Describe the bug
In studio
When executing the [npm run dev] command, a [FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory] error is displayed
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

In studio-> npm install -> npm run dev

## Screenshots
![WeChatccad5a7b590e172d8e75903a37aa61e1](https://user-images.githubusercontent.com/24466320/143670154-6395d5e6-ba87-45e1-b2e2-235dfb2dde9e.png)

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js:^1.27.0
- Version of Node.js: 14.18.1

**Comment by Isaiah-Hamilton** [comment]
@Mozzior have you tried updating `node.js` to the latest version?

**Comment by Mozzior** [comment]
>

**Comment by Mozzior** [comment]
> @Mozzior have you tried updating `node.js` to the latest version?

I updated node.js to 17.1.0, but the problem was not solved

**Comment by Isaiah-Hamilton** [comment]
@Mozzior What has worked for me is using `yarn`. Try uninstalling your `package-lock.json` files and try again but using `yarn`.
