### ISSUE TITLE
`ctrl` + `a` in organization name modal is broken

### ISSUE THREAD

**Issue by KonradLinkowski** [supabase/supabase#414]
# Bug report

## Describe the bug

`ctrl` + `a` key combination should select all text and than pressing any key should replace that text
what happens instead is text is selected, but isn't replaced and writing additional characters is broken after that

## To Reproduce

1. Go to https://app.supabase.io/new
2. Create new organization
3. Write something
4. Press `ctrl` + `a`
5. Type something
6. Go to step 4 or 5 randomly multiple times
7. Text isn't replaced and sometimes new character doesn't appear

## Expected behavior

`ctrl` + `a` should select whole text and than clicking any key should replace the selected text with that key

## Screenshots

Video https://streamable.com/4n7nn4

## System information

- OS: Windows 10
- Browser: chrome
- Version of supabase-js: https://app.supabase.io/
- Version of Node.js: https://app.supabase.io/

**Comment by awalias** [comment]
thanks for reporting @KonradLinkowski , will figure it out 👍
