### ISSUE TITLE
columns of text[] type broken for Web Dashboard

### ISSUE THREAD

**Issue by anngbaum** [supabase/supabase#4150]
# Bug report

## Describe the bug
Not able to edit the metadata of a text[] column using web dashboard UI

For columns of Type = text with the "Define as Array" = true, I'm getting an error from the web UI every time I try to modify any other metadata for that column.

However, I'm able to use the table and make edits to the column using direct SQL ALTER TABLE commands, so it seems like it's just a UI issue (to the best of my knowledge?)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to any Table Editor
2. Click 'Edit Column' for any column within a table
3. Change the column to type = text and Define as Array = true
4. Try to save changes
5. see error

## Expected behavior

I assume that text[] columns are still supported, and I should be able to save and make other changes to the column.

## Screenshots

![Screen Shot 2021-11-29 at 12 56 37 PM](https://user-images.githubusercontent.com/29735378/143919071-faa6828b-b4c2-4cde-a11e-e8f3a7841bcc.png)

## System information

- OS: macOS

**Comment by wickedmom** [comment]
+1

This bug broke a part of my web app.

**Comment by Grymse** [comment]
+1
Not able to edit any type if they're an array. I have tried with all integeres. This is a recent bug, as only two-three weeks ago I was able to :)

**Comment by rutikwankhade** [comment]
I am stuck with this issue. did anyone found a work around for it?

**Comment by DanMossa** [comment]
Having this issue as well today. Deleting and recreating column works

**Comment by nilooy** [comment]
It seems like it has been fixed.

https://user-images.githubusercontent.com/32486682/182973037-d6e55b19-2d19-4afb-8888-68ecfdc90965.mov
