### ISSUE TITLE
Can not sign up a new  user

### ISSUE THREAD

**Issue by logan-anderson** [supabase/supabase#4155]
# Bug report

## Describe the bug

When trying to sign in a new user I get the following error
```
(node:77103) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://kgexnaylsgbctfxszkcx.supabase.co/auth/v1/signup reason: Unexpected token < in JSON at position 0
    at /Users/logananderson-forestry-mac/dev/personal/testing-remix/disc-golf/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## To Reproduce

Using a simple nodejs script I should be able to sign up a user but I receive an error.
```js
const supa = require("@supabase/supabase-js");
const client = supa.createClient(
  "https://***.supabase.co",
  "***"
);
client.auth.signUp({ email: "test@gmail.com", password: "test" });
```
When running this I get the error above

## Expected behavior

I should be able to sign up a new user

## System information
Mac os and all of the latest versions

**Comment by Etheonor** [comment]
Also have this issue, my website is litteraly unusable for all my users right now :(

**Comment by kiwicopple** [comment]
@Etheonor - can you please add a support ticket here so that have all your details: https://app.supabase.io/support/new

**Comment by Etheonor** [comment]
@kiwicopple Thank you for your answer and yes I already created a ticket. I also sent a screenshot of the issue on your Discord (#help) and it seem that other users had this issue and it was fixed by migrate their instance. 

Thanks

**Comment by awalias** [comment]
@logan-anderson I tried your signup endpoint and it seems to be working correctly now

I _think_ the error you're seeing is because cloudflare is erroring for some reason and returning a HTML error page which our client library is not parsing correctly (it is expecting json error payloads)

let us know [here](https://app.supabase.io/support/new) if it's still an issue and we can dig in deeper

**Comment by logan-anderson** [comment]
Yup is is working correctly for me now as well! Thank you
