### ISSUE TITLE
New !inner join not working: "Could not find a relationship between trips and bookings in the schema cache"

### ISSUE THREAD

**Issue by mbalslow** [supabase/supabase#4170]
# Bug report

## Describe the bug

I follow the syntax explained here: https://postgrest.org/en/v9.0/api.html#embedding-with-top-level-filtering

I am attempting to utilize the new inner join functionality. I attempt to perform a simple query. If I leave out "!inner" it works well, however, with "!inner", I get an error:

```
{
    "hint": "If a new foreign key between these entities was created in the database, try reloading the schema cache.",
    "message": "Could not find a relationship between trips and bookings in the schema cache"
}
```

Example:
- Works = https://__.supabase.co/rest/v1/trips?select=bookings(id)
- Does not works = https://__.supabase.co/rest/v1/trips?select=bookings!inner(id)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Try similar queries as above

## Expected behavior

I would expect, when not giving any filters to the query, to get the exact same response as if not including "!inner" in the query.

## System information

- Happens both using the Javascript SDK and through direct REST calls in Postman

## Additional context

- I have tried with multiple different relations in our setup. All of them behave the same.
- I have attempted to restart our Supabase server in the cloud dashboard but that made zero difference.

**Comment by steve-chavez** [comment]
I think you don't have the PostgREST 9 version enabled in your instance.

Unfortunately there's no direct way to check the version for now(as Cloudflare is overriding the `Server` header coming from PostgREST), but you could do:

```js
GET https://__.supabase.co/rest/v1/trips?id=is.anything
```

If it replies with an error like:

```js
{
 "hint":null,
 "message":"syntax error at or near \"'anything'\"",
 "code":"42601",
 "details":null
}
```

Then you're not on PostgREST 9 as this version replies with a more descriptive error message instead:

```js
{
  "details":"unexpected \"a\" expecting null or trilean value (unknown, true, false)",
  "message":"\"failed to parse filter (is.anything)\" (line 1, column 4)"
}
```

**Comment by mbalslow** [comment]
@steve-chavez thanks, I will get back to you after testing this asap. My follow-up question is that in case it is not version 9, how could this be since it is stated in the release notes that all existing project have been upgraded? Is it then just a matter of time before it is upgraded or have I misunderstood the release notes and do I need to do something to get on version 9?

**Comment by mbalslow** [comment]
@steve-chavez it seems that it is not on version 9 based on my test

![image](https://user-images.githubusercontent.com/49169557/144139722-b7b8a499-5143-438e-ba54-3fed3d4873fd.png)

**Comment by steve-chavez** [comment]
> Is it then just a matter of time before it is upgraded 

@mbalslow Yes, PostgREST 9 is still being rolled out to all instances. It should be a matter of hours.

**Comment by mbalslow** [comment]
@steve-chavez I can confirm that it now works so it was simply a matter of time until the instance was upgraded

**Comment by mgm1313** [comment]
I've got exactly the same issue as described in the original post, but different from https://github.com/supabase/supabase/issues/4170#issuecomment-983084077 I can confirm I'm already on PostgREST 9.
What else could I do @steve-chavez to debug this issue?  

My query is: `https://__.supabase.co/rest/v1/courses?select=age_category!inner(id)`

The error is:
```json
  "error": {
    "message": "Could not find a relationship between course and age_category in the schema cache",
    "hint": "If a new foreign key between these entities was created in the database, try reloading the schema cache."
  },
```

Running the code suggested in https://github.com/supabase/supabase/discussions/2579#discussioncomment-1060046 returned
```mysql
SELECT
    tc.table_schema, 
    tc.constraint_name, 
    tc.table_name, 
    kcu.column_name, 
    ccu.table_schema AS foreign_table_schema,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name 
FROM 
    information_schema.table_constraints AS tc 
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name IN ('course', 'age_category');
```
```markdown
| table_schema | constraint_name             | table_name   | column_name     | foreign_table_schema | foreign_table_name | foreign_column_name |
| ------------ | --------------------------- | ------------ | --------------- | -------------------- | ------------------ | ------------------- |
| public       | fk_ageCategory              | course       | age_category_id | public               | age_category       | id                  |
```

**Comment by steve-chavez** [comment]
@mgm1313 According to your query results, the table is named `course`(note the singular) and not `courses`, so it should be like:

```
https://__.supabase.co/rest/v1/course?select=age_category!inner(id)
```

**Comment by mgm1313** [comment]
> @mgm1313 According to your query results, the table is named `course`(note the singular) and not `courses`, so it should be like:
> 
> ```
> https://__.supabase.co/rest/v1/course?select=age_category!inner(id)
> ```

Ah stupid mistake while retyping from my other computer, sorry! I now copied the actually query:
`https://__.supabase.co/rest/v1/course?select=*,age_category!inside(*)`
Omitting the `!inside` results in a valid response.

**Comment by mbalslow** [comment]
@steve-chavez I am experiencing some unexpected behavior. Maybe this is on purpose but it should be clearly clarified in the documentation, I think - maybe it is, but I cannot find it anywhere.

In a simple one-to-one relationship, where the given relationship might be null (foreign key is nullable), using the "!inner" excludes any records without a relationship even though that is not specified as a filter.

I have attempted to make a minimal way of reproducing what I mean:

1. I have a "owner" and a "dog" table. One owner may or may not have a dog ("dog_id" column is nullable)

![Dog table](https://user-images.githubusercontent.com/49169557/145256556-838bbcd5-769b-4e61-a64c-20e63c1218a8.JPG)

![Owner table](https://user-images.githubusercontent.com/49169557/145256570-32c0087e-1b07-4c05-a91b-1e25c5027ede.JPG)

2. Querying this data without the use of "!inner", I get both records:

![Request without inner](https://user-images.githubusercontent.com/49169557/145256681-b991f784-58cc-46f6-8ec2-45598b14e57e.JPG)

3. Querying this data with the use of "!inner", I only get the one with a dog, even though I have not filtered in any way. 

**I would expect to always get all "owners" if I use no filters.**

![Request with inner](https://user-images.githubusercontent.com/49169557/145256836-4cb1f108-d915-4d20-a43a-5263d60f9a5b.JPG)

Is this the intended behavior of "!inner", or?

**Comment by steve-chavez** [comment]
@mbalslow Yes, that's intended behavior - does an INNER JOIN under the hood - it excludes top-level rows without an explicit filter(actually it contains an implicit filter, the ON clause of the INNER JOIN).

> Maybe this is on purpose but it should be clearly clarified in the documentation

True. Actually on the PostgREST side we are thinking of adding an alternative way to specify this operation, which would enable doing:

```http
GET /countries?select=name,cities(name)&cities=exists.true
```

Or through `postgrest-js`:

```js
const { data, error } = await supabase
  .from('countries')
  .select(`
    *,
    cities (*)
  `)
  .exists('cities', true)
```

I think that would make the filtering more explicit.
