### ISSUE TITLE
crypt does not work on trigger functions

### ISSUE THREAD

**Issue by ichbinedgar** [supabase/supabase#4174]
# Bug report

## Describe the bug
For some reason `crypt` does not work on trigger functions. I tried other functions like md5 and it works. The plugin is enabled, and I'm able to run the function on the SQL section.

## To Reproduce

this works:

 ```

begin

  insert into public."Users" (id, email , name, phone_1, phone_2, id_condo, address, birthday, password  )
  values (
  new.id, 
  new.email, 
  new.raw_user_meta_data->>'name', 
  new.raw_user_meta_data->>'phone_1', 
  new.raw_user_meta_data->>'phone_2',
  (new.raw_user_meta_data->>'id_condo'::text)::uuid,
   new.raw_user_meta_data->'address',
    CAST (new.raw_user_meta_data->>'birthday' as DATE),
    md5( new.raw_user_meta_data->>'password')
  );
  return new;
end;

 ```

but this does not work

```
begin

  insert into public."Users" (id, email , name, phone_1, phone_2, id_condo, address, birthday, password  )
  values (
  new.id, 
  new.email, 
  new.raw_user_meta_data->>'name', 
  new.raw_user_meta_data->>'phone_1', 
  new.raw_user_meta_data->>'phone_2',
  (new.raw_user_meta_data->>'id_condo'::text)::uuid,
   new.raw_user_meta_data->'address',
    CAST (new.raw_user_meta_data->>'birthday' as DATE),
    crypt( new.raw_user_meta_data->>'password', gen_salt('bf', 8))
  );
  return new;
end;
```

## Expected behavior

crypt should work , so the password should be encrypted

## Actual behavior

the trigger functions throws an error

## Image

<img width="654" alt="Screen Shot 2021-11-30 at 11 25 13" src="https://user-images.githubusercontent.com/5431012/144096971-d617168e-d972-4356-92be-1e45a12f2439.png">

## System information

- OS: macOS
- Browser chrome 96.0.4664.55 (Build oficial) (x86_64)
- Version of supabase-js: 1.28.1
- Version of Node.js: v12.20.0

**Comment by GaryAustin1** [comment]
md5 is a standard postgres function.  When you install crypt thru pgcrypto extension it likely was installed in the extension schema.  You need your search path to point to that schema.  Adding "security definer" to the function might fix it if the the user that created the function has that in their path.  Otherwise you may need to add the path or specify the schema.  Obviously guessing since you don't have the error.

**Comment by ichbinedgar** [comment]
Got it! however, the function it's almost a copy paste of the function used as an example to insert a new user on a custom public table when a new user is created on auth.user table. So in theory, the "security definer" line was already added. But let met try again (I'm not sure if that configuration is lost when a function is edited).

**Comment by ichbinedgar** [comment]
also, it would be great if the supabase team can provide the DB error, because for me it's also hard to guess what was the error.

**Comment by GaryAustin1** [comment]
I agree trigger function errors are the worst without access to a log.  
I have crypto working in an rpc function, but another user in the discussion forums is having problems.  My SQL superbase_user includes extensions and I created the function there (I don't remember if it was there by default or I added when I installed the http extension.   
The discussion:  https://github.com/supabase/supabase/discussions/4042  he does not have it working yet though.  I guess it is possible a different version of postgres or pgcrypto is running for different people and causing the issue, but skeptical on that.

**Comment by ichbinedgar** [comment]
@GaryAustin1 can I see an example of your  rpc function? I may use it as workaround. Thanks in advanced!

**Comment by GaryAustin1** [comment]
So I see you created it in the function editor.  I think, but am not sure that user does not have full privileges like the sql editor user (I don't use it).  
Add set search_path = "$user", public, auth, extensions; to your function and see if that helps.
I just copied the function from the discussion I linked above and it works for me.

**Comment by ichbinedgar** [comment]
@GaryAustin1 you were right! I needed to drop the function and trigger (because I'm not sure how to alter the function definer values). So I used this new script:

```
create function public.handle_new_user() 
returns trigger 
language plpgsql 
security definer set search_path = public,extensions
as $$
begin
  insert into public."Users" (id, email , name, phone_1, phone_2, id_condo, address, birthday, password  )
  values (
  new.id, 
  new.email, 
  new.raw_user_meta_data->>'name', 
  new.raw_user_meta_data->>'phone_1', 
  new.raw_user_meta_data->>'phone_2',
  (new.raw_user_meta_data->>'id_condo'::text)::uuid,
   new.raw_user_meta_data->'address',
    CAST (new.raw_user_meta_data->>'birthday' as DATE),
    crypt( new.raw_user_meta_data->>'password',gen_salt('bf', 8))
  );
  return new;
end;
$$;
```

so this works now! :D

**Comment by kiwicopple** [comment]
Thanks for jumping in to help @GaryAustin1 🙏 .

@ichbinedgar - looks like this is working for you now so I'll close this, but feel free to comment if you need me to reopen
