### ISSUE TITLE
auth.uid() check not working on insert when using another user's uuid

### ISSUE THREAD

**Issue by patcito** [supabase/supabase#418]
# Bug report

When adding a policy to check that authenticated user uuid is equal to a table uuid, it still accepts the insert if I use another user's uuid.

## To Reproduce

1. Create a table Post (id, uuid)
2. Create a policy:
  `create policy "users can insert only own posts"
  on public.posts
  for insert
  with check (auth.uid() = uuid);`
3. execute the following on the client:
  ` await supabase.from('posts').insert([
      {
        uuid: `&lt;another user uid&gt;,
      },
    ])

## Expected behavior

The post should not be created as auth.uid() != uuid
But it does get created.

## System information

- OS: Ubuntu
- Version of supabase-js: latest
- Version of Node.js: nextjs 10.3

**Comment by awalias** [comment]
Hey @patcito thanks for reporting will check it out

**Comment by patcito** [comment]
> Hey @patcito thanks for reporting will check it out

Thanks @awalias, I'm not sure if I'm doing it right. What I want to enforce is that the uuid of the post being inserted is the same as the uid of authenticated from auth.users. Is this possible and am I doing it right? Thanks.

**Comment by awalias** [comment]
just to confirm: are you using the `anon` key in your supabase-js client?

**Comment by patcito** [comment]
> just to confirm: are you using the `anon` key in your supabase-js client?

yes, I'm using anon key

**Comment by awalias** [comment]
did you do `ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;` ?

**Comment by patcito** [comment]
> did you do `ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;` ?

when I do this, I get "new row violates row-level security policy for table \"posts\""

This is the policy I used:

`create policy "users can insert only own posts"
  on public.deposits
  for insert
  with check (auth.uid() = posts.uuid);`

**Comment by patcito** [comment]
Nevermind, it works now. Thanks for the help.

**Comment by awalias** [comment]
great news, anything else let us know!

**Comment by pradeepknowstocode** [comment]
How did it work @patcito ?
Doesn't work for me 
```
create policy "INSERT ROLE" 
on profile_role
for insert WITH CHECK (
  auth.uid in (Select profile_id from profile_role where role = 'ADMIN')
)
```

**Comment by wyozi** [comment]
In case someone else stumbles upon this thread and has some issue as @pradeepknowstocode, the table you're joining from (in this case `profile_role`) must also be readable according to RLS rules. Took me a while to figure out I forgot to add read permissions for my users table :)
