### ISSUE TITLE
Chore: Change supabase.io to supabase.com on github repo

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4181]
# Chore

## Describe the chore

Change the link on the Github repo to [supabse.com](https://supabase.com)

## Additional context

<img width="1392" alt="Screen Shot 2021-11-30 at 5 19 23 PM" src="https://user-images.githubusercontent.com/70828596/144137532-6dffa05f-1914-4016-a04e-5724a6935f56.png">

**Comment by kiwicopple** [comment]
well spotted @Isaiah-Hamilton 🙏
