### ISSUE TITLE
Hide Vercel IDs from Workflow files.

### ISSUE THREAD

**Issue by Siddhant-K-code** [supabase/supabase#4186]
# Chore

## Describe the chore

It is very good practice to not show the `vercel-org-id` & `vercel-project-id` directly in the files.

## Fix

This Can be fixed easily by just putting those IDs in GitHub Secrets. and Just Import it as `${{ secrets.SECRET_NAME_OF_THAT_ID }}`

Files: 

* [Prod YML File](https://github.com/supabase/supabase/blob/master/.github/workflows/deploy_vercel_prod.yml#L20-L21
)
* [Stage YML File](https://github.com/supabase/supabase/blob/master/.github/workflows/deploy_vercel_staging.yml#L20-L21)

**Comment by kiwicopple** [comment]
thanks @Siddhant-K-code ! Looks like this one is fixed now
