### ISSUE TITLE
Deeplink token issue 

### ISSUE THREAD

**Issue by riderx** [supabase/supabase#4188]
## Describe the bug

i use supabase in my vue 3, capacitor app and I got issue with deeplinking.
When email is send after first step register, I click on the link and I'm redirect to my webapp with the deeplink config.
then I'm redirected to the app, but when I get in the app I see my token is not valid anymore.
When I check in the dashboard, I see the new users did login.

After few research I found that:
during the sort time of website redirect to mobile app supabase is able to login and close the page, so when the same token is receive by the app, it was already used.

## To Reproduce
Not really easy to reproduce, my app is not open source, not that one .

## Expected behavior

Be able to use multiple time token, or be able to disable auto login.
I'm thinking to disable auto login for 300ms and if the page is still open activate it to login if user didn't have the app.

## System information

- OS: ios 15 
- Browser safari
- Version of supabase-js: 1.28.0
- Version of Node.js: 14

**Comment by riderx** [comment]
found a solution by desactivate auto login system in supabase

**Comment by J0** [comment]
Hey @riderx 

Glad you managed to find a solution -- we're looking into better support for mobile deep links and generally storing refresh/oauth tokens within a session.

Closing for now but let us know if you still face issues

**Comment by riderx** [comment]
Yes good for me, i just share my solution if needed:
The config needed in supabase:
https://github.com/Cap-go/capgo/blob/686d1917f5a04334f38a8ca86c702486aab31d80/src/services/supabase.ts#L13
The manual way to get the token:
https://github.com/Cap-go/capgo/blob/686d1917f5a04334f38a8ca86c702486aab31d80/src/services/supabase.ts#L37
call this method in the page where you redirect users.
