### ISSUE TITLE
Improve row level subscription documentation

### ISSUE THREAD

**Issue by tbillington** [supabase/supabase#4195]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/subscribe#listening-to-row-level-changes

## Describe the problem

The documentation specifies the ability to listen on "individual rows", giving the example of listening to a "country" by it's "id".

I assume "id" is a primary/unique key in this case.

The documentation isn't clear on whether this "eq" syntax is an exact row match on a primary/unique key, or more of a "filter" that will match any row that equals a certain value.

For example, I want to know if I can use this to listen on "todos" with a foreign key column of "user_id" to be notified of all "todos" of a user that update, not a single/ "individual row".

 Is this possible? It's not clear from the documentation, and is why I'm writing this issue.

## Describe the improvement

Specify that the eq only works for primary keys or specify whether it's a filter (albeit limited) that can return events that "match" the "filter".

**Comment by codiini** [comment]
@tbillington Can I take up this issue?

**Comment by Sonichigo** [comment]
Can i take this up @kiwicopple ? Any heads up on issue?

**Comment by kylerummens** [comment]
Any update to this?

**Comment by Sonichigo** [comment]
Hey @maskeynihal , no there isn't yet, wanted a headsup like couldn't find at what all eq works. Also waiting for some one to clarify this once

**Comment by kylerummens** [comment]
From the simple tests I've done, it looks like the `col` parameter in the `{table}:{col}=eq.{val}` syntax doesn't have to be a primary/unique key. So it looks like it can be used to listen to all todos by user_id, for example. But it only seems to allow for integers. I've tried a couple different ways to get it to accept a uuid, but nothing worked.

**Comment by Sonichigo** [comment]
Seems like ``eq`` is just for integers then and not strings maybe. Thanks for this, I'll make the PR by EOD. Or you can take this up if you want! Either works

**Comment by Sonichigo** [comment]
Thanks for sorting this out. Will make the necessary changes!!

**Comment by kylerummens** [comment]
> > But it only seems to allow for integers. I've tried a couple different ways to get it to accept a uuid, but nothing worked.
> 
> @kylerummens what does your setup look like?
> 
> I just did a quick test with the `countries` example and was able to listen to the `name` column (`text`) and receive changes.
> 
> Just to clarify, `eq` filter should work with all database types b/c under the hood, it's casting both the filter value (what you want to listen to) and the database value (data that was inserted/updated) to the correct type and then comparing them.

I don't know what I did different this time, but it worked.

```
const user_id = 'test_user_id';

supabase.client.from(`todos:user_id=eq.${user_id}`).on('*', payload => {
  console.log(payload);
}).subscribe();
```

**Comment by kylerummens** [comment]
Is there also support for multiple filters?

Something like:
```
const user_id = 'test_user_id';
const status = 'incomplete';

supabase.from(`todos:user_id=eq.${user_id};status=eq.${status}`).on('*', payload => {
  console.log(payload);
}).subscribe();
```

**Comment by w3b6x9** [comment]
> Is there also support for multiple filters?
> 
> Something like:
> 
> ```
> const user_id = 'test_user_id';
> const status = 'incomplete';
> 
> supabase.from(`todos:user_id=eq.${user_id};status=eq.${status}`).on('*', payload => {
>   console.log(payload);
> }).subscribe();
> ```

@kylerummens not at the moment but we are discussing it internally.

**Comment by jfreyberg** [comment]
@w3b6x9 Any updates on this matter? Being able to listen to filtered updates seems a very broad use case to me.
