### ISSUE TITLE
Adding column: An unexpected error has occurred.

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#420]
# Bug report

## Describe the bug
Database > a table > New (column, left from Filter input) > entire GUI is replaced with empty page with error in the middle "An unexpected error has occurred."

**Comment by inian** [comment]
Hi @peachp, this has been fixed too in our recent release. Can you please check?

**Comment by ykdojo** [comment]
@inian I think I'm going to close this issue since it's been inactive for 10 days. @peachp, please feel free to reopen it if you encounter something similar again.

**Comment by peachp** [comment]
Seems to work now!
