### ISSUE TITLE
Realtime Row Level security broken for database-wide subscriptions on PG12

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#4201]
# Bug report

## Describe the bug

**Affects**

- PG12
- PG14 (although these will only be new use-cases, so nobody should be experiencing the bug)

**Unaffected**

- PG13 users.  If you are experiencing problems with PG13, it is probably because your Policies are not allowing access (whereas previously Policies weren't applied). This is intended behaviour - your database security is working properly

**Description**

We're discovered an issue as a result of our Row-Level Security Realtime updates for that affects any database-wide publications. (eg `CREATE PUBLICATION supabase_realtime FOR ALL TABLES;`)

## To Reproduce

Realtime subscription may have stopped you are on PG12 and you have a Publication in your database set up like

<img width="1467" alt="Screenshot 2021-12-01 at 7 49 05 PM" src="https://user-images.githubusercontent.com/10214025/144230037-9539750e-7092-40f3-9487-f3eeac582ed9.png">

## Workaround

Disable the `FULL` publication (red) and enable each table individually (green)
<img width="1467" alt="Screenshot 2021-12-01 at 7 50 51 PM" src="https://user-images.githubusercontent.com/10214025/144229745-0747d54e-dc4e-4a5a-a286-a63e0cfdfd0b.png">

**Comment by kiwicopple** [comment]
Initial investigation seems to be that the wal2json extension is handling the list of tables differently

Specifically, if we [pass it](https://github.com/supabase/realtime/blob/acfc3daf1852e9781a8069dfe8c079b6e0b20610/server/lib/realtime/rls/replications.ex#L91) an empty string of tables in one version then it assumes "all tables" and in another version it assume "no tables". 

We determine the list of table that should be passed [here](https://github.com/supabase/realtime/blob/acfc3daf1852e9781a8069dfe8c079b6e0b20610/server/lib/realtime/rls/replications.ex#L49). If the publication has been set up for all tables (eg: `CREATE PUBLICATION supabase_realtime FOR ALL TABLES;`) then this will return an empty string

**Comment by inian** [comment]
Hi @batuhanbilginn, can you send your project ref to support@supabase.io Thanks

**Comment by batuhanbilginn** [comment]
> 

I've created a support ticket just now. I hope it works for you.

**Comment by batuhanbilginn** [comment]
The issue might be related to RLS and authentication flow. I've enabled RLS with a policy of "only authenticated", I couldn't make any CRUD operation. If you guys enabled RLS on all real-time tables by default since the morning that might cause this error.
![Screenshot 2021-12-01 at 17 48 48](https://user-images.githubusercontent.com/86785488/144256049-95be0c12-d2fa-4252-9a5c-0ea21ae50ce2.png)

**Comment by kiwicopple** [comment]
Hey @batuhanbilginn - yes it looks like your issue is related to your RLS Policies. Take note of this part in the description above:

>  If you are experiencing problems with PG13, it is probably because your Policies are not allowing access (whereas previously Policies weren't applied). This is intended behaviour - your database security is working properly

**Comment by batuhanbilginn** [comment]
Yeah, now I'm sure it's related to RLS. When I subscribe to the table directly it works however if I subscribe to a specific row by using a filter it doesn't work anymore. Also, RLS disabled on those tables. I think there is some kind of bug in my project :(

**Comment by clouedoc** [comment]
It looks like a permission issue is blocking `pg_dump` on our side:

```console
pg_dump: error: query failed: ERROR:  permission denied for table schema_migrations
11
pg_dump: error: query was: LOCK TABLE realtime.schema_migrations IN ACCESS SHARE MODE
```

**Comment by w3b6x9** [comment]
> It looks like a permission issue is blocking `pg_dump` on our side:
> 
> ```
> pg_dump: error: query failed: ERROR:  permission denied for table schema_migrations
> 11
> pg_dump: error: query was: LOCK TABLE realtime.schema_migrations IN ACCESS SHARE MODE
> ```
> 
> Granting privileges to the table **using the online SQL editor** solved the issue:
> 
> ```sql
> GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA realtime TO postgres;
> GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA realtime TO postgres;
> ```

@clouedoc Thanks for reporting and sharing your workaround! We're already aware of this issue and will be deploying a fix to all projects soon.

**Comment by daemswibowo** [comment]
Hi! I'm facing this issue on PG13, i've policies on `comments` table for `select` using `auth.role()='authenticated'` and for insert with check `auth.role()='authenticated'` too.

I already enable realtime for `comments` table
`alter publication supabase_realtime add table comments;`
![image](https://user-images.githubusercontent.com/9953444/144361012-0b1780e4-c55d-463f-9bf1-3370b58d33b2.png)

When I'm trying to subscribe realtime with this code:
```js
supabase.from('comments').on('INSERT', (payload) => {
  console.log('incoming comment', payload);
}).subscribe();
```
the new comment does not appear on the `console.log`

**Comment by kiwicopple** [comment]
@daemswibowo - which version of supabase-js are you using?

**Comment by kk21** [comment]
I am on postgresql 13 and using supabase-js v1.28.3.
RLS also did not work for me, after giving all access to the policy and adding table to replication.

**Comment by kiwicopple** [comment]
Just to confirm, are your RLS policies working on the RESTful API? eg: `supabase.from('comments').select()`

**Comment by kk21** [comment]
Yes, I could select the records...but listening to "UPDATE" did not return anything when I changed my record.

**Comment by daemswibowo** [comment]
> @daemswibowo - which version of supabase-js are you using?

v1.28.3.

when I get the comments via api there is no problem with that, only on realtime

**Comment by inian** [comment]
@daemswibowo @kk21 can you comment with your project references or send them to support@supabase.io with a link to this issue? Thanks

**Comment by kk21** [comment]
My project is
https://app.supabase.io/project/gcsrhrqyyiviugatrldv

**Comment by w3b6x9** [comment]
@kk21 there's currently an issue with listening to tables with `uuid` as primary key. we're in the process of putting in a fix and will report back here once it's deployed.

**Comment by batuhanbilginn** [comment]
> @kk21 there's currently an issue with listening to tables with `uuid` as primary key. we're in the process of putting in a fix and will report back here once it's deployed.

Are you sure about that? I've just changed the primary key to int8 from uuid and realtime doesn't work anymore :(

**Comment by GaryAustin1** [comment]
So it seems now that some heartbeat issues were resolved on postgres 13, my first subscription works using an uuid primary key on a non RLS table.  My other subscriptions though on a different notRLS table using (:eq.id=int) are no longer working.  I've not had time yet to see if removing the first subscribe lets the next work, or modifying the the multiple row subscriptions on the 2nd table down to one impact things.  I'm 90% sure I have not touched this code since it was last working.  I'll dig more into tomorrow.

**Comment by inian** [comment]
Thanks a lot for reporting these issues everyone. We have a few fixes coming in the next day or two. 

If there your workload is affected, send us a support ticket and we will revert your project to an earlier version.

**Comment by w3b6x9** [comment]
@batuhanbilginn @GaryAustin1 I just merged in a fix that addresses certain types for primary keys not working as well as filtering not working for types like `int`. We'll be rolling out the changes to all projects as soon as possible.

Thanks for reporting these issues!

**Comment by w3b6x9** [comment]
### UPDATE

We're currently rolling out the fixes to all projects, and some projects may have already been fixed depending on your project's region.

**Comment by GaryAustin1** [comment]
@w3b6x9 
As of 16 hours after your comment, the filter on int id realtime does not work on non RLS table. (uuid on another non RLS table works) and removing filter works.  I did reset server.  (PG13 1.28.5)
ALSO after 1 hour when the token change occurs all subscriptions start getting SUBSCRIPTION_ERROR status again and a browser refresh is only fix, I thought that had been fixed on 1.28.4, but may have missed it, or 1.28.5 or other change broke it again.

**Comment by kachar** [comment]
@GaryAustin1 I've got it working by turning off and on again the replication for the project.

![image](https://user-images.githubusercontent.com/893608/144717075-65f64e7a-758b-4181-9a06-1631817709fc.png)

Thanks for the fix @w3b6x9 :raised_hands:

**Comment by GaryAustin1** [comment]
@kachar @w3b6x9 
I had reset server, and turned the tables on and off.  Did not try those.  It works again cycling insert/update!  Now wait for an hour and see if the other issue goes ### away....

**Comment by michaelketzer** [comment]
I think I experience the same issue.

I am using supabase.io and I am not getting any realtime updates with my service key.

I use RLS and I can select rows with supabase-js.
My primary keys are mainly uuid's.
I followed any advice in this thread including updating supabase-js to the latest version without any luck

Is the update on all regions deployed? Or are there still some scheduled?
For reference, I am on `eu-central-1` with the project key `mzgcvkiamhhpeqomyvme`.

**Comment by w3b6x9** [comment]
> I think I experience the same issue.
> 
> I am using supabase.io and I am not getting any realtime updates with my service role key.
> 
> I use RLS and I can select rows with supabase-js. My primary keys are mainly uuid's. I followed any advice in this thread including updating supabase-js to the latest version without any luck
> 
> Is the update on all regions deployed? Or are there still some scheduled? For reference, I am on `eu-central-1` with the project key `mzgcvkiamhhpeqomyvme`.

@michaelketzer I think you're experiencing a different issue.

Realtime RLS currently only works with the `authenticated` role (in the case that RLS is enabled for a table), and we're working hard to make it compatible with other roles like `service_role`.

Also, we do not recommend using the `service_role` key when creating clients with `supabase-js`. `service_role` role is designed to bypass RLS, which is a security concern if exposed on the client. Please refer to [Never use a service key on the client](https://supabase.com/docs/guides/auth/row-level-security#never-use-a-service-key-on-the-client) for best practices.

You can use your `anon` key to connect to the client via `supabase-js`, and if you and/or your users are signed in, then Realtime RLS tracks the authenticated users after they've subscribed to topic sand determines whether or not they should receive changes to a database table based on your RLS policies.

**Comment by w3b6x9** [comment]
### UPDATE

We have rolled out the fixes to all projects. If you're still experiencing Realtime issues then please email support@supabase.io with your project ref and we'll investigate. Thanks!

**Comment by michaelketzer** [comment]
@w3b6x9 

That does make sense, thank you for the detailed explanation!

I didn't mention that i am using it for server side implementations only 😬 There is nothing exposed to the client and I want to bypass the RLS there as my apps are working with all rows.

I guess, I will switch to polling for now.

Thank you again 🙏

**Comment by w3b6x9** [comment]
> @w3b6x9
> 
> That does make sense, thank you for the detailed explanation!
> 
> I didn't mention that i am using it for server side implementations only 😬 There is nothing exposed to the client and I want to bypass the RLS there as my apps are working with all rows.
> 
> I guess, I will switch to polling for now.
> 
> Thank you again 🙏

@michaelketzer ah, apologies for making the assumption that you were using it client-side! If you send an email to support@supabase.io with a link to your [comment](https://github.com/supabase/supabase/issues/4201#issuecomment-986068337) then I can follow up and inform you when `service_role` role is available in Realtime RLS. We're sorry it isn't working for your use case today!

**Comment by juanantoniosantanamedina** [comment]
Morning.

I'm afraid it is still not working for me.

My project id is ykrxgyvolgibksnsrghd

Thanks

**Comment by kachar** [comment]
> Realtime RLS currently only works with the `authenticated` role (in the case that RLS is enabled for a table), and we're working hard to make it compatible with other roles like `service_role`.

@w3b6x9 Are you guys planning to support the `anon` role as well as the `authenticated` role as both of these are valid regarding the usage of RLS?

In our apps, we've got policies for both anonymous and logged-in users and currently, the real-time updates work only for authenticated.

```sql
create policy "Anyone can create public mood." on moods
for insert with check (auth.role() = 'anon');
```

If this feature is out of the roadmap, we'll need to make changes to our app flow, so it's good to know in advance. :bowing_man:

**Comment by kiwicopple** [comment]
We will support this @kachar - a fix should be available early this week

**Comment by w3b6x9** [comment]
> Morning.
> 
> I'm afraid it is still not working for me.
> 
> My project id is ykrxgyvolgibksnsrghd
> 
> Thanks

@juanantoniosantanamedina your issue is completely separate from everyone else's. Can you please email support@supabase.io with a link to your [comment](https://github.com/supabase/supabase/issues/4201#issuecomment-986210142) and your project ref. We'll investigate further. Thanks!

**Comment by GaryAustin1** [comment]
I've noticed a new issue with realtime RLS that I don't recall happening on the non RLS version.  If I am signed in as a user on my desktop and then go and signin as the same user on my notebook, after the next token refresh (the hourly one) the desktop starts having subscription errors.  Without logging into the notebook the desktop would keep the subscription running over night.  

This is a common use case for my app where the user takes notes in the field and then returns to his computer to manage things.  I will proceed to try and renew the subscription on SUBSCRIPTION_ERROR status, but just wanted to get this out there while the RLS realtime is getting focus.

**Comment by w3b6x9** [comment]
> I've noticed a new issue with realtime RLS that I don't recall happening on the non RLS version. If I am signed in as a user on my desktop and then go and signin as the same user on my notebook, after the next token refresh (the hourly one) the desktop starts having subscription errors. Without logging into the notebook the desktop would keep the subscription running over night.
> 
> This is a common use case for my app where the user takes notes in the field and then returns to his computer to manage things. I will proceed to try and renew the subscription on SUBSCRIPTION_ERROR status, but just wanted to get this out there while the RLS realtime is getting focus.
> 
> edit: more info "event":"phx_reply","payload":{"response":{"reason":"user token is invalid"},"status":"error"}, is on the websocket (as expected). Edit: I finally got the reason message back with .subscribe((e,status)=>{}) so might be able to use that info to decide what to do with the "broken" connection.
> 
> edit: Almost seems like for my case, watching a non RLS public status table, would be better off without the level of token protection that now seems required.

@GaryAustin1 the only time that client would get back `"reason":"user token is invalid"` is when trying to subscribe to the topic (see this [error reason in `join` function](https://github.com/supabase/realtime/blob/8815245b51af8e4fa31f3962f5c14142dee868cc/server/lib/realtime_web/channels/realtime_channel.ex#L47)).

We haven't changed the core functionality of allowing the same user to listen to database changes on separate devices.

I have reviewed your Realtime RLS logs and there's no indication that this is related to token refresh. One explanation, given the error reply you provided, is that your desktop experienced some sort of issue (perhaps network-related), and it failed to re-subscribe to the topic when your desktop recovered.

If this is ongoing, please email support@supabase.io with a link to your [comment](https://github.com/supabase/supabase/issues/4201#issuecomment-986880366) and your project ref. We can then investigate further.

**Comment by GaryAustin1** [comment]
I sent an email.  It is always after a 2nd client signs in the other client will drop realtime on it's next token refresh.  AND the websocket is showing constant loop trying to JOIN again.  My subscribes though are not rerunning (console.log right before setups not firing) so I suspect realtime.js is doing the looping joins...

**Comment by shinypb** [comment]
I'm having problems as well; realtime just stopped working for me entirely.

- I'm not using RLS anywhere
- I've updated to the latest version of `@supabase/supabase-js` (1.28.05)
- I've only got realtime enabled for a handful of specific tables
- I have tried toggling realtime off and on again for said tables

I'm at a loss for what else I can try at this point. Any suggestions?

**Comment by GaryAustin1** [comment]
Did you toggle the update, insert, delete swithes?

**Comment by w3b6x9** [comment]
> I'm having problems as well; realtime just stopped working for me entirely.
> 
> * I'm not using RLS anywhere
> * I've updated to the latest version of `@supabase/supabase-js` (1.28.05)
> * I've only got realtime enabled for a handful of specific tables
> * I have tried toggling realtime off and on again for said tables
> 
> I'm at a loss for what else I can try at this point. Any suggestions?

@shinypb can please email support@supabase.io with a link to your [comment](https://github.com/supabase/supabase/issues/4201#issuecomment-988366165) and your project ref? We can investigate!

**Comment by shinypb** [comment]
@GaryAustin1 Thank you for that suggestion; unfortunately, it still doesn't work.
@w3b6x9 Thanks for the recommendation; I just emailed them.

Here's hoping for a solution! 🤞

**Comment by w3b6x9** [comment]
If you have other issues with Realtime please create a new issue or email support@supabase.io (please include your project ref).

**Comment by LivioGama** [comment]
That was not it, I decided to write a whole medium post for avoiding you waste time in the future: https://liviogamassia.medium.com/using-supabase-rls-with-firebase-auth-custom-auth-provider-357eaad9c70f
