### ISSUE TITLE
Sudently relation between tables "does not exist"

### ISSUE THREAD

**Issue by tavoohoh** [supabase/supabase#4205]
# Bug report

## Describe the bug

I Have the following query:
```
  id,
  user (
    first_name,
    last_name
  ),
  created_at,
  appointments:appointments.specialist (count),
  account (
    balance
  )
```

It was working since the 17 of september of 2021 until this morning, no changes were made to this code since that date. And the request is responding "column specialists.appointments does not exist". 

Here's the CURL generated by the frontend:
```
curl '.../specialists?select=id%2Cuser%28first_name%2Clast_name%29%2Ccreated_at%2Cappointments%3Aappointments.specialist%28count%29%2Caccount%28balance%29&deleted=eq.false&offset=0&limit=5'
```

Using the supabase-js library:
```
  supabase
    .from('specialists')
    .select(
       `
          id,
          user (
            first_name,
            last_name
          ),
          created_at,
          appointments:appointments.specialist (count),
          account (
            balance
          )
       `).eq('deleted', false)
```

If this "`appointments:appointments.specialist(count)`" is eliminated the query works

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table called "specialists" or whatever you want
2. Create a second table called "appointments" or whatever you want and add a releation between this table and the first one. It can be "specialist -> specialists.id"
3. Fetch the table "specialist" and join with "appointments.

## Expected behavior

A success request as it was before

## Screenshots

The curl request from insomnia:
<img width="1173" alt="imagen" src="https://user-images.githubusercontent.com/37514022/144273836-b69499b1-c347-41ce-af18-9c2d6c5a4367.png">

The relation in "appointments":
<img width="642" alt="imagen" src="https://user-images.githubusercontent.com/37514022/144275252-2b7e042c-6225-46be-a284-1a065eb78087.png">

## System information

- macOS and Windows
- chrome, firefox
- Version of supabase-js: ^1.22.4
- Version of Node.js: v14.17.5

**Comment by willopez** [comment]
Can confirm that I am also experiencing this issue.

**Comment by steve-chavez** [comment]
@tavoohoh Can you change `appointments.specialist` to `appointments!specialist`? As in:

```js
  supabase
    .from('specialists')
    .select(
       `
          id,
          user (
            first_name,
            last_name
          ),
          created_at,
          appointments:appointments!specialist(count),
          account (
            balance
          )
       `).eq('deleted', false)
```

**Comment by steve-chavez** [comment]
@willopez What error message are you getting? The solution should be similar to the above.

This is likely due to the 3rd item in this list: https://postgrest.org/en/v9.0/releases/v9.0.0.html#breaking-changes

**Comment by willopez** [comment]
My issue is a bit different, I am not able to successfully create a table reference in the UI. I create a reference to another table, but it is not persisted. See recording below.
![supabase_bug](https://user-images.githubusercontent.com/486340/144435201-e176d518-bdd9-40c8-80b8-d236fc83a704.gif)

**Comment by steve-chavez** [comment]
@willopez I see, that's totally different because the Table Editor is its independent from the JS library. Could you create another issue for that one?

**Comment by tavoohoh** [comment]
@steve-chavez it did work!! So the issue was related with the new version of postgrest.

Thank you

**Comment by willopez** [comment]
@steve-chavez  issues created here: https://github.com/supabase/supabase/issues/4249
