### ISSUE TITLE
Realtime Blog Post 12/1/2021 has very bad chart

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#4207]
# Improve documentation

## Link 

https://supabase.com/blog/2021/12/01/realtime-row-level-security-in-postgresql

## Describe the problem
I was quite scared when I saw this graph....
https://supabase.com/images/blog/launch-week-three/realtime-row-level-security-in-postgresql/supabase-realtime-processing-per-subscription.png

## Describe the improvement

Swap the X and Y axis labels  (hopefully...)

![supabase-realtime-processing-per-subscription](https://user-images.githubusercontent.com/54564956/144278427-dd24e4ff-0c8e-48d9-aec7-5f62beef0314.png)

**Comment by w3b6x9** [comment]
@GaryAustin1 haha thanks for pointing this out! We'll get this fixed.
