### ISSUE TITLE
Change the way the Slack clone example handles localStorage

### ISSUE THREAD

**Issue by ykdojo** [supabase/supabase#421]
I'm mostly looking at these two lines:
- https://github.com/supabase/supabase/blob/559f909cb7fa57e8df091d7bb50bbdfca13636d6/examples/nextjs-slack-clone/pages/_app.js#L15
- https://github.com/supabase/supabase/blob/559f909cb7fa57e8df091d7bb50bbdfca13636d6/examples/nextjs-slack-clone/pages/_app.js#L28

Rather than manually manipulating local storage, it should use [supabase-js/gotrue-js's built-in functionality](https://github.com/supabase/gotrue-js/blob/dc6cf10dcac016ba4831efdb9b8683bda109dab0/src/GoTrueClient.ts#L330) for it (when the client is loaded, it already automatically loads the user session from local storage) and use supabase.auth.onAuthStateChange to listen for the user session being loaded onto the client.

To do this, I should probably build a custom hook. I think @thorwebdev's code here might be a good example of how to do it: https://github.com/supabase/gotrue-js/blob/59d4f0b01dd6a52c8f4b85ee22b376d26e800402/example/next/utils/useAuth.js

**Comment by thorwebdev** [comment]
Yes, the slack clone needs a refactor and update. I think someone was working on that. @kiwicopple do you remember who?

Regarding useAuth hook, I think this React context approach is the best solution: https://github.com/thorwebdev/nextjs-subscription-payments/blob/main/components/UserContext.js. I need to update the nextjs auth example with that.

**Comment by ykdojo** [comment]
#433 fixes this issue. I ended up not really using either a custom hook or the user context approach, but it fixes it. If we want to improve it, maybe we can refactor it in future PRs/commits.
