### ISSUE TITLE
realtime subscription fails after 1 hour on non rls table.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#4223]
# Bug report
realtime subscribe on a non rls/public table now fails after about an hour of idle browser.  I don't recall it doing that before because I also used the status of that to determine "online" status to Supabase.  I assume this has something to do with the new rls code being added.  Making other calls after that to the database work, but subscription continues to fail.
The console continually logs a connection error in subscribe status every few seconds, but I did not time it.

I'm sure I can detect the failure and resubscribe, but don't know if this is intended with the new changes.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

 let mySubscription = supabase
        .from('status:uid=eq.'+user.id)
        .on('*', payload => {
            console.log('Change received!', payload)
        })
        .subscribe((status)=>{
            console.log('subscribe',status);
            if (status==='SUBSCRIBED') online.set(true);
            else online.set(false)
        })

## Expected behavior

subscription works as before.

## System information
Postgres 13 on the Supabase server

**Comment by w3b6x9** [comment]
@GaryAustin1 thanks for reporting!

This is a known issue and will be fixed as soon as [fix: improve auth for realtime row level security #303](https://github.com/supabase/supabase-js/pull/303) is merged and released.

> I'm sure I can detect the failure and resubscribe

I think this is the workaround for now.

**Comment by kiwicopple** [comment]
Just released this fix @GaryAustin1 : https://github.com/supabase/supabase-js/releases/tag/v1.28.4

Let us know if you experience any problems after upgrading!

**Comment by GaryAustin1** [comment]
Using 1.28.4 and things are better, but still acting strange.  Once again non RLS tables no changes from last week.
Now every 60 seconds both subscriptions return status of SUBSCRIPTION_ERROR and then after a second or so return SUBSCRIBED.  Process repeats sitting in open browser window idle.  
I don't know if during the second or so break in connection if the table had a change would it be lost, or if it would just get reported on reconnect.  That is fine then for getting payload, but it does mean I can't reliable use connection status to determing "online" to Supabase as I do a bunch of stuff if connection breaks.

**Comment by GaryAustin1** [comment]
@kiwicopple 
Well it is not any better after all.  Also see previous reply.   After some period of time  get authchange TOKEN_REFRESHED message and then the rt connections all start failing every few seconds with SUBSCRIPTION_ERROR and no SUBSCRIBED.  

Refreshing page puts it back in the 60 second loop mode above, I imagine until the next token refresh.

**Comment by w3b6x9** [comment]
@GaryAustin1 can you please email support@supabase.io with a link to this issue and your project ref? I'll investigate!

**Comment by GaryAustin1** [comment]
Sent
