### ISSUE TITLE
Nextjs ssr data fetching

### ISSUE THREAD

**Issue by mtergel** [supabase/supabase#4241]
# Bug report

## Describe the bug
Hello. I'm trying to fetch data using match filter. But sometimes it works and sometimes it doesn't work. It errors out even though i gave it the right parameter. Response: message: 'invalid input syntax for type uuid: ""', code: "22P02". 

## To Reproduce
Code: 
```javascript
export const getServerSideProps: GetServerSideProps<UserPageProps> = async (
  context
) => {
  const params = context.params; // params.username
  const client = supabase;

  const res = await client
    .from<definitions["profiles"]>("profiles")
    .select(`id, username, avatar_url, display_name, bio`)
    .eq("username", params!.username as string)
    .single();

  if (res.data) {
    console.log(res.data.id);
    const articlesRes = await client
      .from<definitions["posts"]>("posts")
      .select(
        `
        *,
        tags!post_tag (*),
        user:user_id (*)
        `,
        { count: "estimated" }
      )
      .match({
        user_id: res.data.id,
        published: true,
        post_type: "article",
      })
      .range(0, 23)
      .order("created_at", { ascending: false });

    console.log(articlesRes);

    return {
      props: {
        profile: res.data,
        articles: {
          articles: (articlesRes.data as PostsJoins[]) ?? [],
          count: articlesRes.count ?? 0,
        },
      },
    };
  }
  return {
    notFound: true,
  };
};
```
Failed response:
```
10aa457d-5c2c-4e7b-b5de-eb6f63589a2f <- user_id
{
  error: {
    message: 'invalid input syntax for type uuid: ""',
    code: '22P02',
    hint: null,
    details: null
  },
  data: null,
  count: null,
  status: 400,
  statusText: 'Bad Request',
  body: null
}
```

## Expected behavior

To fetch data properly

## System information

- OS: macOS
- Browser (if applies) Firefox
- Version of @supabase/supabase-js: 1.28.4
- Version of Next: 12.0.3
- Version of React: 17.0.2

## Additional context

It works completely fine on client side.
And also the tables have public read access.

**Comment by phamhieu** [comment]
your code looks ok to me. Can you try this and let me know the result
```
// instead of 
user_id: res.data.id

// change to this
user_id: '10aa457d-5c2c-4e7b-b5de-eb6f63589a2f'

```

**Comment by mtergel** [comment]
@phamhieu 
Still same :cry:

**Comment by kiwicopple** [comment]
could you also try to convert the `match()` to a sequence of equalities?

```js
.eq('user_id', res.data.id)
.eq('published', true)
.eq('post_type', 'article')
```

**Comment by mtergel** [comment]
@kiwicopple 
Errors out almost all the time now. Like works once in every 10 attempts.
```
{
  error: {
    message: 'invalid input syntax for type uuid: ""',
    code: '22P02',
    hint: null,
    details: null
  },
  data: null,
  count: null,
  status: 400,
  statusText: 'Bad Request',
  body: null
}
```

**Comment by mtergel** [comment]
@phamhieu 
of course, I just updated it today so the latest version i guess.

 "@supabase/supabase-js": "^1.28.4",

**Comment by bnjmnt4n** [comment]
Hey @mtergel I noticed this seems pretty much like the issue I was facing at https://github.com/supabase/supabase/issues/4244. The fix there might be helpful to you!

**Comment by kiwicopple** [comment]
thanks for this @bnjmnt4n 🙏
