### ISSUE TITLE
Potential issue with new `auth.uid()` function

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/supabase#4244]
# Bug report

## Describe the bug

Following the upgrade to PostgREST 9 and the [updates to the `auth.uid()` function](https://github.com/supabase/supabase/pull/3988/files#diff-966f18f6feaf0bfe4d397b1d3fc31b1b31d1d0ffd19a16470bb6691c77362d15), we've been experiencing some issues with casting of `auth.uid()` into a UUID, which have been difficult to diagnose accurately.

We started seeing this error in production: `invalid input syntax for type uuid: ""`. Since there has not been any change to our schemas/policies recently, we suspected it had to do with the new PostgREST update.

## To Reproduce

I managed to reproduce some similar behaviour locally. The gist is that after any connection switches to the `authenticated` role, a following switch to the `anon` role will lead to the `auth.uid()` returning a string which cannot be cast to a UUID. I'm not very sure whether this is a Postgres bug or not, but there is a quick workaround using `NULLIF`.

1. I ran a local Postgres server using a backup dump from a Supabase instance. This dump was before the new updates to the `auth.uid()` function.
2. I ran the following code to upgrade to the new `auth.uid` function.

    ```
    ❯ PGDATA=$PWD/postgres_data PGHOST=$PWD/postgres LOG_PATH=$PWD/postgres/LOG PGDATABASE=postgres DATABASE_URL="postgresql:///postgres?host=$PGHOST" psql -U supabase_admin
    psql (12.8)
    Type "help" for help.
    
    postgres=# create or replace function auth.uid()
    returns uuid
    language sql stable
    as $$
      select
      coalesce(
        current_setting('request.jwt.claim.sub', true),
        (current_setting('request.jwt.claims', true)::jsonb ->> 'sub')
      )::uuid
    $$;
    CREATE FUNCTION
    postgres=# \q
    ```

3. Here's where the issue lies: after switching to the authenticated role within a transaction, the following switch to the `anon` role leads to the error. Here, the `users` table just has a single column `id`, with a single RLS policy for select: `id = auth.uid()`.
    ```
    ❯ PGDATA=$PWD/postgres_data PGHOST=$PWD/postgres LOG_PATH=$PWD/postgres/LOG PGDATABASE=postgres DATABASE_URL="postgresql:///postgres?host=$PGHOST" psql -U supabase_admin
    psql (12.8)
    Type "help" for help.
    
    postgres=# begin; set local role anon; set local "request.jwt.claim.role" to 'anon';
    BEGIN
    SET
    SET
    postgres=> select * from users;
     id
    ----
    (0 rows)
    
    postgres=> rollback;
    ROLLBACK
    postgres=# begin; set local role authenticated; set local "request.jwt.claim.role" to 'authenticated'; set local "request.jwt.claim.sub" to 'bd217c6e-27e3-490d-8108-db481d88581b';
    BEGIN
    SET
    SET
    SET
    postgres=> select * from users;
     id
    ----
    (0 rows)
    
    postgres=> rollback;
    ROLLBACK
    postgres=# begin; set local role anon; set local "request.jwt.claim.role" to 'anon';
    BEGIN
    SET
    SET
    postgres=> select * from users;
    ERROR:  invalid input syntax for type uuid: ""
    postgres=# rollback;
    ROLLBACK
    postgres=# \q
    ```

## Potential fix

I'm guessing this might be a Postgres bug, but switching to the following version of `auth.uid()` seems to fix the issue:

```sql
create or replace function auth.uid()
returns uuid
language sql stable
as $$
  select
  nullif(
    coalesce(
      current_setting('request.jwt.claim.sub', true),
      (current_setting('request.jwt.claims', true)::jsonb ->> 'sub')
    ),
    ''
  )::uuid
$$;
```

```
❯ PGDATA=$PWD/postgres_data PGHOST=$PWD/postgres LOG_PATH=$PWD/postgres/LOG PGDATABASE=postgres DATABASE_URL="postgresql:///postgres?host=$PGHOST" psql -U supabase_admin
psql (12.8)
Type "help" for help.

postgres=# begin; set local role anon; set local "request.jwt.claim.role" to 'anon';
BEGIN
SET
SET
postgres=> select * from users;
 id
----
(0 rows)

postgres=> rollback;
ROLLBACK
postgres=# begin; set local role authenticated; set local "request.jwt.claim.role" to 'authenticated'; set local "request.jwt.claim.sub" to 'bd217c6e-27e3-490d-8108-db481d88581b';
BEGIN
SET
SET
SET
postgres=> select * from users;
 id
----
(0 rows)

postgres=> rollback;
ROLLBACK
postgres=# begin; set local role anon; set local "request.jwt.claim.role" to 'anon';
BEGIN
SET
SET
postgres=> select * from users;
 id
----
(0 rows)

postgres=> rollback;
ROLLBACK
postgres=# \q
```

We have updated our Supabase instance to use this version of the `auth.uid()` function which fixes this issue.

## System information

- OS: Windows (Ubuntu on WSL 2)
- Version of Postgres: Tested on 12.8, 14.0

**Comment by liaujianjie** [comment]
Let's just wait for https://github.com/supabase/gotrue/pull/295.
