### ISSUE TITLE
Cannot create a table reference using the Table editor

### ISSUE THREAD

**Issue by willopez** [supabase/supabase#4249]
# Bug report

## Describe the bug

When attempting to create a reference to another table the process fails. For example, I have a table `lesson` and another table `bonus_content` and want to reference the `id` in the `lesson` table from the `bonus_content` table it's currently not possible via the UI. See reproduction stops in the attached GIF.

## To Reproduce

![supabase_bug](https://user-images.githubusercontent.com/486340/144435201-e176d518-bdd9-40c8-80b8-d236fc83a704.gif)

## Expected behavior

When a reference is created via the UI, it will be persisted in the DB

## System information

- OS: macOS
- Browser: Chrome

**Comment by kharix5** [comment]
This code is not available. 
2 bugs

**Comment by phamhieu** [comment]
@willopez your `bonus_content` table should has:
- id: as primary key
- lesson_id: as foreign key to lesson table

**Comment by phamhieu** [comment]
> This code is not available.
2 bugs

What do you mean? @kharix5

**Comment by willopez** [comment]
@phamhieu Correct, I implemented that using the SQL editor by executing a query, however, this was possible before in the Table editor, and now it's not and therefore this bug report. I believe, the other comment on this thread is from a bot.

**Comment by phamhieu** [comment]
Thank you for the detailed explanation @willopez. 

FYI @joshenlim
