### ISSUE TITLE
Error: connect ECONNREFUSED to my database

### ISSUE THREAD

**Issue by mtimofiiv** [supabase/supabase#4250]
# Bug report

## Describe the bug

Earlier today, my database suddenly stopped receiving connections, both from my app, but also from my SQL program, and also the Supabase dashboard.

Here's what I get when I try to open the database in Supabase dashboard:

<img width="662" alt="Screenshot 2021-12-02 at 11 21 48" src="https://user-images.githubusercontent.com/428948/144488845-2c716d7f-00d3-43b2-a34b-9e36af309711.png">

And when I navigate over to the "Settings" for the db, I can see that at a certain point in the last 2 hours, the db suddenly dropped from 69% to 27% memory usage, as well as about 10% CPU load down to <1%.

<img width="1028" alt="Screenshot 2021-12-02 at 11 22 45" src="https://user-images.githubusercontent.com/428948/144488985-9c3f68e2-7f0b-43aa-b14a-c72220d439fd.png">

Additionally, trying to run SQL from the Supabase dashboard on that database appears broken. Here I am trying to run the basic "Show extensions" query:

<img width="1133" alt="Screenshot 2021-12-02 at 11 26 20" src="https://user-images.githubusercontent.com/428948/144489536-8be0ccdd-83f5-463d-b055-89afedb8c914.png">

## To Reproduce

There seems to be another user in Discord with this problem. Others seem unaffected.

## Expected behavior

Normal performance of both connecting to the db via my app, via SQLPro Studio, and also to be able to access it from the Supabase dashboard.

## Additional context

Obviously it would be great to know how to get my db back online, but I'm also posting this here so that if this occurs to anyone else, there's at least some clear info on the problem. I was unable to find anything.

It appears this is some kind of infastructure issue, as the database has been functioning perfectly for several months.

**Comment by kiwicopple** [comment]
hi @mtimofiiv - can you please create a support ticket here: https://app.supabase.io/support/new

We'll investigate your instance

I'll close this one unless we can investigate and determine if it's a problem affecting multiple users

**Comment by max-programming** [comment]
@kiwicopple I have the same issue.
@mtimofiiv  Did you find any solution???

**Comment by mtimofiiv** [comment]
@max-programming there's no fix, unfortunately. You have to contact support, and they will fix it for you for that one instance.

**Comment by max-programming** [comment]
@mtimofiiv Okay. I have opened a support ticket. Any idea how long does it take?
