### ISSUE TITLE
Storage getPublicUrl() naming inconsistency

### ISSUE THREAD

**Issue by kelly** [supabase/supabase#4256]
# Bug report

## Describe the bug

The getPublicUrl() function returns an object with the key 'publicURL'

## Expected behavior

This URL vs Url is inconsistent. I would expect the function and response to follow a similar naming format.

**Comment by kiwicopple** [comment]
Thanks @kelly - this one is perhaps better for a [Discussion](https://github.com/supabase/supabase/discussions). Perhaps you can add it there?
