### ISSUE TITLE
Email Confirmation Bug

### ISSUE THREAD

**Issue by batuhanbilginn** [supabase/supabase#4268]
# Bug report

## Describe the bug

Although I've disabled Email Confirmation, supabase forces users to confirm their email address. (I create users on the server with supabase.auth.api.createUser)
<img width="1331" alt="Screenshot 2021-12-03 at 14 21 52" src="https://user-images.githubusercontent.com/86785488/144594733-0664c8ad-3d68-4f6c-8c28-28d3258b210d.png">
<img width="1330" alt="Screenshot 2021-12-03 at 14 22 06" src="https://user-images.githubusercontent.com/86785488/144594791-75255d10-8f98-4e9e-9347-0c84362e019a.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Auth > Setting > Email Confirmation'
2. Click on 'Disabled'
3. Try to create a user.

## System information

- OS: macOS
- Version of supabase-js: Latest
- Version of Node.js: 14...

**Comment by kangmingtay** [comment]
Hey @batuhanbilginn, thanks for pointing this out! We'll make the fix on gotrue-js soon!

**Comment by edelah** [comment]
Same bug on email change; an email is sent for confirmation even if my settings are the same as the original poster.

**Comment by ekrresa** [comment]
I just came across this bug.

**Comment by kangmingtay** [comment]
Hey @edelah, @ekrresa 

We recently updated the `createUser` method in gotrue-js (https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueApi.ts#L448) to include the email_confirm and phone_confirm fields. The createUser method doesn't confirm the user by default. 

Hope this helps!

**Comment by ekrresa** [comment]
It works now! Thanks a lot.

The types need an update though. The attributes parameter of the `createUser` method uses `UserAttributes` interface instead of `AdminUserAttributes`.
<img width="1235" alt="Screenshot 2022-01-01 at 09 34 16" src="https://user-images.githubusercontent.com/20543629/147847106-e176e5b6-81f4-4cb6-b03a-cc9746b5a658.png">

**Comment by kangmingtay** [comment]
Hmm, we actually updated it already though (check out the link i sent previously above), the UserAttribute doesn't contain those fields. Perhaps you need to refresh your editor to see the updated changes in gotrue-js?

**Comment by ekrresa** [comment]
It doesn't seem to be updated in the `@supabase/supabase-js` library.

**Comment by rphlmr** [comment]
The type is not updated on 1.29.1 but it works with `email_confirm`, thanks !

```js
 const { data } = await supabase.auth.api.createUser({
      email,
      password,
      email_confirm: true,
    });
```

**Comment by J0** [comment]
Hey this issue seems to have gone stale.

Going to close for now but let us know if you are still facing issues.

Thanks!
