### ISSUE TITLE
Live slack clone sign-up not working

### ISSUE THREAD

**Issue by ulysset** [supabase/supabase#427]
# Bug report
In the repo example https://github.com/supabase/supabase/tree/master/examples/nextjs-slack-clone the live example hosted doesn't work.
## Describe the bug
When I try to sign up in the live demo hosted at this url http://supabase-slack-clone.supabase.vercel.app/ 
```
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```
## To Reproduce
1. Go to http://supabase-slack-clone.supabase.vercel.app/ 
2. Enter valid email and password
3. Click on 'Sign up
4. See error alert with message displayed above

## Expected behavior
I expected the sign up form to work.
## System information

- OS: macOS
- Browser : chrome

**Comment by kiwicopple** [comment]
Possibly related to this one: https://github.com/supabase/supabase/issues/421

YK is improving the codebase for the Slack clone now, so we can address this in one fell swoop :)

**Comment by ykdojo** [comment]
@kiwicopple yes I think it's related. I'm just going to assign this issue to myself.

**Comment by ykdojo** [comment]
I hope #433 fixes it, but I believe I don't have access to the Vercel team (so that I can update the link) yet? @kiwicopple

**Comment by kiwicopple** [comment]
@ykdojo let's merge your branch in then we can test. I think there is also a problem where the vercel deployment is pointing to a delete database now

**Comment by ykdojo** [comment]
I tried signing up again, and I got this error:
![image](https://user-images.githubusercontent.com/1811651/103319499-f2381700-49e6-11eb-9543-aea88f81ac97.png)

Here's the error on my Chrome console:
![image](https://user-images.githubusercontent.com/1811651/103319582-2c091d80-49e7-11eb-9f12-9be1d93423bf.png)

It looks like it's still pointing to a deleted database? @kiwicopple
