### ISSUE TITLE
Funtion Hooks - Http params [Object Object]

### ISSUE THREAD

**Issue by eduardocampo** [supabase/supabase#4273]
# Bug report
The first input returns Object Object. The second if you let enter the value

![image](https://user-images.githubusercontent.com/43253539/144676497-737384de-515c-468f-9fc5-be7e9ca61bc3.png)

![image](https://user-images.githubusercontent.com/43253539/144676694-d6217976-fb2f-47c9-8963-3550da887281.png)

**Comment by codingforfoodllc** [comment]
I am seeing this as well.

**Comment by burmecia** [comment]
This issue has been fixed, note the `Function Hooks` has been renamed to `Database Webhooks`.

**Comment by eduardocampo** [comment]
ok! thanks 💚
