### ISSUE TITLE
Add a section to javascript API documentation on conditionally building queries.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#4274]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/using-filters

supabase/web/spec/supabase.yml in repository.

## Describe the problem

Several of us have been asked/answered in Discord on how to deal with conditional filters.  For instance having option to search several different columns, but only use the ones filled in by the user.  It is not obvious you can build up the query and then execute it with await or .then() from any Supabase examples I'm familiar with. 

## Describe the improvement

I suggest adding this to the end of the using filter 'page'.  I've attempted to write it in the format of the yaml file, but I'm not familiar with it.  OF COURSE THE CODE BLOCK HERE ATE the "3 backticks" JS at start and "3 backticks" at end of the js example....

`
###Conditionally Chaining Filters

Filters can be built up one step at a time and then executed.

```js
const filterByName = null
const filterPopLow = 1000
const filterPopHigh = 10000

let query = supabase
	.from('cities')
	.select('name, country_id')
	
if (filterByName) {query = query.eq('name',filterByName)}
if (filterPopLow) {query = query.gte('population', filterPopLow)}
if (filterPopHigh) {query = query.lt('population', filterPopHigh)}

const { data, error } = await query
```
`

## Additional context

I'm very new to Github repositories and don't feel comfortable experimenting on a pull request here myself.

**Comment by kiwicopple** [comment]
good idea @GaryAustin1 - this would be a great addition to the docs

**Comment by vluna** [comment]
@kiwicopple I can implement @GaryAustin1 request and submit the PR if possible.

**Comment by kiwicopple** [comment]
That would be amazing @vluna - thank you!

**Comment by vluna** [comment]
@kiwicopple Here is the PR #4361. Let me know if any change is required.

**Comment by kiwicopple** [comment]
love it @vluna - thanks for the contribution!

**Comment by Hazem172002** [comment]
> Collaborator

thank you bro

**Comment by k0ncode** [comment]
It would be nice to have the same kind of documentation on the Flutter API. I first struggled with building conditional queries in Flutter, because there was no documentation.
