### ISSUE TITLE
Supabase + Flutter Android + Google Oauth2 = NOT WORKING

### ISSUE THREAD

**Issue by iansama** [supabase/supabase#4295]
I am using Flutter to make an Android App. I am following this tutorial: https://supabase.com/docs/guides/auth/auth-google

However, Google shows an error when I try to authenticate: `error 400 redirect_uri_mismatch`
This is a mobile screenshot of the google error: https://imgur.com/a/FBUlCAF

This is a screenshot of the settings for google "Client ID for Web application" as per the tutorial's instruction even tho, I am making an android app, not a web app: https://imgur.com/a/wBknYQV

This is how I am calling the provider:
```
  googleAuth() {
    Supabase.instance.client.auth.signInWithProvider(
      Provider.google,
    );
  }
```

NOTE: The tutorial says:
> **Enter your callback URI in the `Valid OAuth Redirect URIs` box.** 

but I can't find this setting in Google, it does not exist. Either, I am doing something wrong or supabase's tutorial is out of date. Do I need a custom domain or something special to make `supabase + google Oauth` function correctly?

If you need more info, let me know and I will add it

**Comment by dshukertjr** [comment]
Hi @iansama!

Your setting on GCP looks correct to me. `Valid OAuth Redirect URIs box` is the `Authorized redirect URIs` text box you have filled out at the bottom. I would double check if you have configured the google login credentials in the right Supabase project. If it is for sure configured on the right Supabase project, it might be helpful to see screenshots of your configuration within the Supabase project also. 

Also, not directly related to this error, but if you are using Flutter, you need to configure deep links in order for the users to be able to come right back to the app upon signing in. 

You can follow the step described [here](https://supabase.com/docs/guides/with-flutter#setup-deep-links) to set up deeplink in your Flutter project. 

Also, you need to pass the deeplink as the parameter of `signInWithProvider()` like this:
```dart
Supabase.instance.client.auth.signInWithProvider(
  supabase.Provider.github,
  options: supabase.AuthOptions(redirectTo: 'io.supabase.flutterdemo://login-callback'),
);
```

Also, in case it is helpful, [here](https://github.com/phamhieu/supabase-flutter-demo) is an example Flutter & Supabase app that logs users in with Github.

**Comment by iansama** [comment]
Hey @dshukertjr Firstly, before I can apply your recommendation, what is that `supabase` in lower caps? I can't find `.Provider` or `.AuthOptions`. I tried  `SupabaseClient supabase = SupabaseClient(supabaseUrl, supabaseKey)` but didn't work

Currently, I am coding the app with deeplink active, I am using the email signing method and it has been working fine so far. After I click the link in my email, it takes me back to my app. That's a good sign I am guessing, that deeplink is working up to that point.

This is the setting in my supabase panel, 
https://imgur.com/a/SoYeSXC

**Comment by dshukertjr** [comment]
@iansama 
Sorry for the confusion. `supabase` in lower case was me importing `supabase` like the following, so it is the same exact thing as the code you provided. I have edited my code above. 

```dart
import 'package:supabase/supabase.dart' as supabase;
```

This may or may not be related to this issue, but your client secret seems longer than mine. Mine was 24 characters (I'm not a GCP expert, so maybe some client secrets are longer than others). I would double check if the correct client secret is provided. 

<img width="1364" alt="Screen Shot 2021-12-05 at 11 01 09" src="https://user-images.githubusercontent.com/18113850/144768575-f629d874-73b2-492d-a48d-060df681170d.png">

**Comment by seenickcode** [comment]
Is this still an issue? Someone taking my course may be having a similar issue.

**Comment by Shiba-Kar** [comment]
@seenickcode its fixed in latest version.

**Comment by dshukertjr** [comment]
Will close this one because it is fixed! Thanks guys!
