### ISSUE TITLE
"function hooks (alpha)" has disappeared from the docs

### ISSUE THREAD

**Issue by zevaverbach** [supabase/supabase#4317]
# Improve documentation

## Link 

https://supabase.com/docs/blog/2021/07/30/supabase-functions-updates#function-hooks-alpha

## Describe the problem

That page is missing, even though it shows up in the search results. 

## Describe the improvement

Recover/restore it, or remove it from the search results.

## Additional context

It might be good to link to this doc once it's back up from [the blog post announcing the feature's alpha](https://supabase.com/blog/2021/07/30/supabase-functions-updates#function-hooks-alpha).

**Comment by zevaverbach** [comment]
Ah, I just realized it may only be a problem with slightly differing URLs. 

The functioning one:

https://supabase.com/blog/2021/07/30/supabase-functions-updates#function-hooks-alpha

The non-functioning one:

https://supabase.com/docs/blog/2021/07/30/supabase-functions-updates#function-hooks-alpha

I'd be happy to create a PR fixing this. Just let me know what the correct change is: Is it 

a) creating/copying the "/blog" version to the "/docs/blog" one or
b) changing whatever entry is coming up in search such that it only brings up the "/blog" version?

**Comment by kiwicopple** [comment]
not sure where `/docs/blog/` is coming from 🤔 

The correct link should be https://supabase.com/blog/2021/07/30/supabase-functions-updates#function-hooks-alpha

We could also add a redirect if we can't find the link (in [here](https://github.com/supabase/supabase/blob/master/www/next.config.js))

**Comment by bnjmnt4n** [comment]
> not sure where `/docs/blog/` is coming from 🤔

I believe this is coming from the search menu in the top right: all search results from blog posts link to `/docs/blog/` instead of `/blog`.

**Comment by inian** [comment]
should be fixed by https://github.com/algolia/docsearch-configs/pull/4914

**Comment by burmecia** [comment]
This issue isn't relevant anymore as doc search is working now.
