### ISSUE TITLE
Improve Auth emails

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4324]
# Feature request

From Copple:

## Describe the chore

Our Auth emails are very basic. We should improve them by:

- Creating a _very_ simple html template
- Adding "Powered by Supabase" in the footer

## Additional context

Right now the template editor is just a Text area, so people will be able to remove the footer, but that's fine

From Joshen:
- Think this one perhaps require some simple email design to make it more pretty

**Comment by prajzwol7** [comment]
@joshenlim can you elaborate on this on whether to make changes on auth fields or overall change in design of auth email?

**Comment by joshenlim** [comment]
hey there @prajzwol7 - this one's a bit of a large tasks and it involves:
- introducing an HTML editor for auth email templates
- Improving the default auth emails designs

This probably needs to go through some design iteration internally (cc @MildTomato) so I'd say it's not exactly ready to be worked on at the moment

**Comment by joshenlim** [comment]
hey there @prajzwol7 - this one's a bit of a large tasks and it involves:
- introducing an HTML editor for auth email templates
- Improving the default auth emails designs

This probably needs to go through some design iteration internally (cc @MildTomato) so I'd say it's not exactly ready to be worked on at the moment

**Comment by joshenlim** [comment]
going to be closing this as we've done a round of design iteration over the auth email settings
this ticket is a little too broad for our community to contribute meaningfully imo, so if we do want to further improve the auth emails again in the future, we'll be more specific what's needed! 🙏

**Comment by 413n** [comment]
@joshenlim How could I remove "Powered by Supabase" text from the footer? Do people need to have a project subscription to remove it?

**Comment by kiwicopple** [comment]
Hey @413n - yes, you can remove this one by upgrading to the Pro tier
