### ISSUE TITLE
Add better helper text and callback url

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4325]
# Chore

## Describe the chore

improve auth settings page by adding some more meaningful helper text and a callback url.

All the forms are currently using schema to populate labels, but it would also be good to try and update form labels to show the correct labelling per social provider. For example, facebook call secret id, 'App secret' and google call it 'Web client secret'

## Additional context

facebook.
'App ID'
'App Secret'

google
'Web client ID'
'Web client secret'

twitter
'API key'
'API secret'

Github
'Client ID'
'Client Secret'

Bitbucket
'Client ID'
'Client secret'

Add any other context or screenshots that help clarify the task

examples from firebase showing callback url in settings

facebook
![Screenshot 2021-04-26 at 11 00 32](https://user-images.githubusercontent.com/8291514/116023454-b3595b80-a67e-11eb-9ad1-6ea13bb4438a.png)
twitter
![Screenshot 2021-04-26 at 10 59 55](https://user-images.githubusercontent.com/8291514/116023458-b5bbb580-a67e-11eb-816b-2633beaddb50.png)
google
![Screenshot 2021-04-26 at 10 59 48](https://user-images.githubusercontent.com/8291514/116023464-b7857900-a67e-11eb-8a88-a759a4783c62.png)
github
![Screenshot 2021-04-26 at 11 01 39](https://user-images.githubusercontent.com/8291514/116023496-c8ce8580-a67e-11eb-8dff-a0aca9bd818b.png)

**Comment by saltcod** [comment]
Closing this one as not super relevant anymore. Jonny has redone these auth forms.
