### ISSUE TITLE
Light mode JSON viewer 

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4328]
Constrast is not great

![image](https://user-images.githubusercontent.com/19742402/144803549-86f1d51b-15b5-4c3d-8676-e37f004991c5.png)

Hover and selected state is odd

![image](https://user-images.githubusercontent.com/19742402/144803586-f6d6b516-be86-4a4d-99b3-28bdd4465202.png)

**Comment by w0wka91** [comment]
Hey there. Can I work on this one?

**Comment by joshenlim** [comment]
@w0wka91 sure thing! Go ahead :) just tag myself, @MildTomato and @phamhieu in your PR

**Comment by phamhieu** [comment]
> Can I fix this within this issue or should I just open another one?

It's better to open new PR for each fix. Thank you @w0wka91, great work!!!

> The editor to view the JSON Data is always in dark mode. Is that the way it is meant to be?

You can fix the grid editor theme [here](https://github.com/supabase/grid/blob/3a0a708db43278e15e84ce20b148d18766bec02a/src/SupabaseGrid.tsx#L40-L53)
