### ISSUE TITLE
Add system default option for theme choice

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4329]
# Chore

Currently only has dark and light:
![image](https://user-images.githubusercontent.com/19742402/144803880-190e142b-46c7-48ff-a3a9-038e12ffd450.png)

see
https://stackoverflow.com/a/57795518

```
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    // dark mode
}
```

Note that the theme choice selection should sync as well in the menu bar:
![image](https://user-images.githubusercontent.com/19742402/144803966-8edcaa14-f5db-4e8c-993b-587cbdce619d.png)

Behaviour:
- User preference page will have a third option to listen to system
- In the menu bar, the toggle should reflect if its currently dark or light
- toggling the theme in the menu bar will set it to dark or light (no longer system)

**Comment by harshcut** [comment]
Hey, can I work on this issue?

**Comment by joshenlim** [comment]
@harshcut sure thing! :) thanks man
