### ISSUE TITLE
Feat: show total of files in bucket

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4331]
# Feature request

## Is your feature request related to a problem? Please describe.

Seems like a reasonable request.

**"Would be awesome to see total items, thanks for fixing the issue with uploading large data."**
`/project/[project-ref]/storage`

## Describe the solution you'd like

Show a total of items on storage explorer.
this could be at the bottom like the table view.

Note: probably requires some design input as well on where to show this number

**Comment by diegonyc** [comment]
Is this working @MildTomato? Because in my case, the explorer says I have 199 items but I have way more than that.

<img width="385" alt="Screen Shot 2022-07-21 at 2 58 55 PM" src="https://user-images.githubusercontent.com/36611253/180219237-e1844bdd-3d52-4170-b2f1-33b559ca780b.png">
