### ISSUE TITLE
Merge pooling and database config settings

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4332]
Ref https://github.com/supabase/infrastructure/issues/1254#issuecomment-867250992

What do you think of merging both the settings into one panel like this since most of the settings are the same except for the port. We can split it up into two separate sections if the config between direct and pgbouncer connections diverge more

This section will be in the Database Settings page. Pooling connection settings will be removed from connection pooling settings in `/project/ref/database/pooling` and I will add a link to the database settings page instead for getting the connection info.

![image](https://user-images.githubusercontent.com/2155545/124426679-f598ca80-dd9c-11eb-957b-18c4d054dc54.png)

**Comment by joshenlim** [comment]
From Copple:
Great idea @inian - one potential improvement on the names - just make them:

- Port (Direct)
- Port (Connection Pool)

Then add the longer text as Help Text. I've started some docs [here](https://github.com/supabase/supabase/pull/2229) which we can link to as soon as I tidy them up

**Comment by RyKilleen** [comment]
Some documentation around needing to add `?pgbouncer=true` to the end of the connection string would help go a long way as well! 

I need to use it with Prisma, and had to do some decent searching to find the solution.

**Comment by saltcod** [comment]
Closing:  https://github.com/supabase/supabase/pull/6889
