### ISSUE TITLE
Add postgres version number in project settings dashboard

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4333]
# Chore

## Describe the chore

Add postgres version in dashboard.
also add in some helper/description text explaining any caveats / issues for users to look out for regarding postgres version - maybe compatibility with other services etc.

related to https://github.com/supabase/infrastructure/issues/1210

**Comment by kiwicopple** [comment]
We also discussed adding some sort of Supabase Metadata table/schema for all the various versions of the tools (gotrue etc)

some options:

- Add to the extensions schema (cleaner)
- Create a new schema (more extensible, could add other metadata here in the future)

**Comment by joshenlim** [comment]
hey there @aayushdura - this issue requires some changes on our backend and is not ready to be worked on unforunately.

I'd suggest taking a look the issues labelled "good first issue" if you're looking to get started around our repository :)

**Comment by saltcod** [comment]
Going to close this one as its something we need to implement on our end. We'll track it internally. Thanks all!
