### ISSUE TITLE
Function hooks http params UI first field is broken

### ISSUE THREAD

**Issue by gabrielperales** [supabase/supabase#4341]
# Bug report
When you try to edit the HTTP param for a hook of HTTP Request type it shows `[Object object]` as value, and it doesn't allow you  edit it. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to database
2. Click on Function Hooks
3. Click on create a new Function Hook
4. Scroll to Http params
5. Click on Add a new param
6. Edit the param value

## Expected behavior

It should allow you to edit the field.

## Screenshots

https://user-images.githubusercontent.com/1859128/144883889-4c856a8c-d452-4b42-922c-23d2c0b7c4f4.mp4

**Comment by inian** [comment]
Duplicate https://github.com/supabase/supabase/issues/4273
