### ISSUE TITLE
Auth Reset For Email is not working.

### ISSUE THREAD

**Issue by iampopal** [supabase/supabase#4357]
# Reset code for Email

I have my own website host at supabase settings page, when I reset password supabase send me an email.  When I click on the email Reset Password link for the first time for every new email it works fine, but for the second or 3rd time when I send a reset link to the email and click on the link sent to the email I get an error as 

https://myHost.com/#error_code=404&error_description=User+not+found

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a supabase project and disable email conformation
2. Create a simple app with 2 Button 1) Sign Up and 2) Forget password
2. on 1st Button Sign up call this:  auth.signIn(email: email, password: password)
3. on the 2nd button Forget the password call this:  auth.api.resetPasswordForEmail(email)
4. For the first time forget the password will work. on the second and 3rd time, it will not work.

**Comment by iampopal** [comment]
We urgently need a solution for email reset code because we are using supabase as our backend and most users have alredy signed up with there email.

**Comment by iampopal** [comment]
We urgently need a solution for email reset code because we are using supabase as our backend and most users have already signed up with their email.

**Comment by bnjmnt4n** [comment]
I think this is working as intended. The reset password link should only work once, and any subsequent use should be invalid. In this case the error message could probably be reworked to indicate that the link has expired, instead of the vague "user not found" message.

**Comment by kangmingtay** [comment]
Hey @iampopal, just to clarify, are you trying to click on the reset password link multiple times? If so, then @bnjmnt4n's response is right, the reset password link should only work once.

Based on your question, it seems that subsequent reset password emails being sent do not work for you. Is that the error you're facing? It would also help if you email support@supabase.io with your project ref so we can investigate the issue further.

**Comment by iampopal** [comment]
In mobile, when I first click on a reset link 
The link open in chrome browser 
After verifying the link 
The link open android app 

And when it open android app using deep linking, the app the link say user not found.

**Comment by iampopal** [comment]
The error have to change to something like, link expired if it's double clicked

**Comment by faizi2504** [comment]
@iampopal Same issue is occurring on my side. Did you find any fix for that?

**Comment by iampopal** [comment]
@faizi2504 I have fix this issue by creating a static website and initializing supabase project there 

Now when users visit myside.com/forget they see a forget password page 
And after the email is send to them 

And they click on that link. The link redirect to myside.com/forget/?token 
Using the token in a static website forgetting user password is the best way because that website link can be used 
In android, ios, web and desktop

**Comment by iampopal** [comment]
@faizi2504 I have fix this issue by creating a static website and initializing supabase project there

Now when users visit myside.com/forget they see a forget password page
And after the email is send to them

And they click on that link. The link redirect to myside.com/forget/?token
Using the token in a static website forgetting user password is the best way because that website link can be used
In android, ios, web and desktop
