### ISSUE TITLE
Problem with Vercel previews

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#4375]
e.g. https://github.com/supabase/supabase/pull/4374
<img width="2032" alt="Screen Shot 2021-12-08 at 4 11 52 PM" src="https://user-images.githubusercontent.com/31685197/145172403-f370f872-1e90-49a7-bcaf-7415ec51ddb9.png">

**Comment by MildTomato** [comment]
It looks like we are probably going to be moving to nextjs for docs site, so it's probably not worth fixing this anymore.
