### ISSUE TITLE
Custom domains for Storage Buckets

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#4386]
# Feature request

## Is your feature request related to a problem? Please describe.

I think it's important for nearly every website/webapp to have "brandable" and permanent public urls not only to pages, but also to picture assets (and other static assets). Currently Supabase does not offer a possibility to customize Storage Bucket public urls.

## Describe the solution you'd like

Storage Buckets should allow custom domain addresses, so for example, I could have a image at: `https://mydomain.com/logos/primary-logo.png` instead of currently `https://aosibqrvsopgfgnolphf.supabase.in/storage/v1/object/public/logos/primary-logo.png`

## Describe alternatives you've considered

Currently I am not using Storage Buckets for this reason and I had to configure my own S3 bucket with CloudFront and custom subdomain. The image paths on my root domain acts as proxy and masks the destination path (making it appear the user hasn't changed their location on the site).

**Comment by tttp** [comment]
similar to the issue for oauth providers?

https://github.com/supabase/supabase/issues/4386

**Comment by hjaber** [comment]
Supabase appears to be currently using AWS S3 for storage with Cloudfare CDN. 

Custom domains are possible on Cloudfare CDN.

**Comment by tttp** [comment]
Hi, 

how did you manage? I tried putting a CNAME (on cloudflare) between the asset domain I want and the supabase one, and cloudflare rejected it

**Comment by hjaber** [comment]
> Hi, 
> 
> how did you manage? I tried putting a CNAME (on cloudflare) between the asset domain I want and the supabase one, and cloudflare rejected it

There isn't a way to do this on supabase today as far as I know. 

I mean in general this is possible since Cloudfare CDN supports it on their platform

**Comment by inian** [comment]
Hi, this feature is coming soon. Please email [growth@supabase.io](mailto:growth@supabase.io) if you want to be on the waitlist when this launches.

**Comment by kiwicopple** [comment]
I'm going to close this one if favour of https://github.com/supabase/supabase/issues/7808

It has a bit more conversation - I realise that this is specific to "Storage", but the solution we come up with should be generic across all services, so it's better to consolidate the discussion into one issue.

(I'll edit the title of #7808 to include "Storage")
