### ISSUE TITLE
Assets cached in storage explorer

### ISSUE THREAD

**Issue by inian** [supabase/supabase#4395]
### To reproduce

I have 'myImage.jpg' in my storage bucket and I upload a new version of 'myImage.jpg', the new version is named 'myImage(1).jpg'. If I then delete the old version and rename the new version to 'myImage.jpg' the old image appears via the URL. 

@joshenlim we had logic to prevent this already right? If we are cache busting (via a query string), that should bypass both the browser and the CDN cache

Freshdesk issue 3875

**Comment by dominik-bsr** [comment]
This happened to me as well. Getting old files although I have uploaded updates versions through the Supabase Dashboard.
I even get this behaviour when I update the file with supabase-js.

**Comment by inian** [comment]
Realising we have an earlier issue here https://github.com/supabase/supabase/issues/3784
Closing as duplicate
