### ISSUE TITLE
Ability to upsert

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#44]
- [ ] Add an `upsert: true` option to `insert()` options
- [ ] Update documentation on website

It should be noted that upserts only work with Primary Keys (according to the docs: http://postgrest.org/en/v6.0/api.html#upsert)

We will need to add a "PUT" call if upsert is true

**Comment by dragarcia** [comment]
Codebase changes done in [supabase/postgrest-js](https://github.com/supabase/postgrest-js).
