### ISSUE TITLE
Row Level Security for INSERT authenticated isn't working

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#4406]
# Bug report

## Describe the bug

Activating the Row Level Security for INSERT authenticated only and then trying to insert data into the specific table using supabasejs library return:

`new row violates row-level security policy for table \"channel_messages\"`

## To Reproduce

1. Create a table
2. Activate RLS by Supabase Studio on the table created
3. Create a new policy for insert from the template: "Enable insert access for authenticated users only"
4. With an javascript file execute the signIn using : `supabase.auth.signIn()`
5. Then try to insert data using `supabase.from('<table_name>').insert([{<data>]>) `

Consideration:
The table is allowed in Replication for the Realtime

## System information

- OS: Linux
- Browser: Chrome
- Version of supabase-js: ^1.28.5
- Version of Node.js: 16.0.0

## Additional context

Executing the query: `select * from pg_policies` I see correctly the policy

Searching the function auth.role() on DB I found it and this is the current (not modified, so is the function generated at moment of docker up)

`CREATE OR REPLACE FUNCTION auth.role()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  select 
  	coalesce(
		current_setting('request.jwt.claim.role', true),
		(current_setting('request.jwt.claims', true)::jsonb ->> 'role')
	)::text
$function$
;`

Checking the request header I see correctly the apikey and authorization, authorization key is equal to the user access_token

![image](https://user-images.githubusercontent.com/36926081/145381716-d4fd6876-2e0c-4e9f-a7cb-60bd279dab10.png)

**Comment by bnjmnt4n** [comment]
The Supabase client will by default return the data inserted, which means you need to add a `SELECT` policy which permits returning of the newly inserted data as well, otherwise the RLS policies will be violated. Otherwise, you can try adding `{ returning: "minimal" }` which doesn't return the data and hence doesn't require the `SELECT` policy. See https://supabase.com/docs/reference/javascript/insert#notes.

**Comment by WilliamFalci** [comment]
> The Supabase client will by default return the data inserted, which means you need to add a `SELECT` policy which permits returning of the newly inserted data as well, otherwise the RLS policies will be violated. Otherwise, you can try adding `{ returning: "minimal" }` which doesn't return the data and hence doesn't require the `SELECT` policy. See https://supabase.com/docs/reference/javascript/insert#notes.

Yeah, Im sorry, I wasn't updating an column required into the SELECT policy, my fault, anyway thank you!
