### ISSUE TITLE
Illegal Invocation error message - Cloudflare Worker

### ISSUE THREAD

**Issue by lukesnider** [supabase/supabase#4417]
### Discussed in https://github.com/supabase/supabase/discussions/4408

<div type='discussions-op-text'>

<sup>Originally posted by **lukesnider** December  9, 2021</sup>
I am attempting to create a basic cloudflare worker that will utilize the supabase postgrest client. I am simply testing with a public table and I keep getting the same error message no matter what I try. 

```
TypeError: Illegal invocation at line 0, col -2
{
  "exceptionDetails": {
    "columnNumber": -2,
    "exception": {
      "className": "TypeError",
      "description": "TypeError: Illegal invocation",
      "preview": null,
      "subtype": "error",
      "type": "object",
      "value": null
    },
    "lineNumber": 0,
    "text": "Uncaught (in response)",
    "url": "undefined"
  },
  "timestamp": 1639069176994
}
```
And here is the code block in question.
```
import { PostgrestClient } from '@supabase/postgrest-js'
   
 const postgrest = new PostgrestClient(SB_URL, { fetch: fetch })
    const { data, error } = await postgrest
    .from('test')
    .select()
```

I'm sure I'm missing something simple here.</div>

**Comment by soedirgo** [comment]
Hey @lukesnider, you'll need a little more setup to use a Supabase endpoint with postgrest-js instead of supabase-js. Try this:
```js
const { PostgrestClient } = require('@supabase/postgrest-js')
const postgrest = new PostgrestClient(
    'https://<...>.supabase.co/rest/v1',
    {
        headers: {
            apikey: '<your API key>',
            Authorization: 'Bearer <your API key>'
    }
})
const { data, error } = await postgrest
    .from('t')
    .select()
```

**Comment by bnjmnt4n** [comment]
The illegal invocation is likely because `fetch` is called with the wrong context. You might want to try `fetch.bind(globalThis)`, as mentioned here: https://supabase.com/docs/reference/javascript/initializing#custom-fetch-implementation.

**Comment by rhadu** [comment]
i tested with @bnjmnt4n solution and can confirm it works.
```js
const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key', { 
  fetch: fetch.bind(globalThis) 
})
```

should be the same for the `PostgrestClient` client

**Comment by lukesnider** [comment]
This is amazing, thank you all so much for the help!
