### ISSUE TITLE
need help implementing password recovery || no route matched with those values Error

### ISSUE THREAD

**Issue by R3HP** [supabase/supabase#4438]
### Discussed in https://github.com/supabase/supabase/discussions/4411

<div type='discussions-op-text'>

<sup>Originally posted by **R3HP** December  9, 2021</sup>
hello .
i am trying to implement supabase password recovey for a client . sadly i was unable thus far.

i followed guides provided in web site on this [page](https://supabase.com/docs/reference/dart/reset-password-email)

then i take a look at guides provided at this [repo ](https://github.com/phamhieu/supabase-flutter-demo)

but i was unable to make it work . 

here is my supabase auth settings 
![supabase auth setting,ong](https://user-images.githubusercontent.com/41432455/145456117-ad476094-6303-4003-96ef-26678b7cd78a.PNG)

and here is my supabase and supabaseAuth initialization 

 ```
void main() async {
  
  WidgetsFlutterBinding.ensureInitialized();
  
  await Supabase.initialize(
    url: 'SITEURL',
    anonKey:
        'ANONKEY',
        authCallbackUrlHostname: 'ADDITIONAL AUTH CALLBACK REDIRECT'
  );
  //initializing supabaseAuth we use it for password recovery
  await SupabaseAuth.initialize(
    authCallbackUrlHostname: 'ADDITIONAL AUTH CALLBACK REDIRECT ',

  );
  //runnig the app
  runApp(const MyApp());
}
```

note that by ADDITIONAL AUTH CALLBACK REDIRECT i mean the full (SITEURL + ://reset-callback)

here is my androidManifest.xml  intent 
```
<intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <!-- Accepts URIs that begin with YOUR_SCHEME://YOUR_HOST -->
              <data
                android:scheme="SITEURL"
                android:host="//reset-callback" />
            </intent-filter>
```

in the app i first navigate to a page called AuthPage where there is a button that takes the user to a ResetPage where user enters his email and call resetpassword method 

```
Future<void> resetPassword(String email) async {
    try {
      final response =
          await Supabase.instance.client.auth.api.resetPasswordForEmail(
        'email',
        options: supabase.AuthOptions(
          redirectTo: 'Additional Auth Callback Redirect'
        )
      );
      
      debugPrint('reset response ${response}');
    } catch (error) {
      message = error.toString();
      debugPrint(message);
    }
  }
```

which takes the user back to AuthPage in Auth Page i have StreamBuilder which listens to SupabaseAuth.onAuthStateChange and if the chage is passwordRecover it shows a TextField and a button for the user to reset his password implemented like below 

```
StreamBuilder(
          stream: SupabaseAuth.instance.onAuthChange,
          builder: (context, AsyncSnapshot<AuthChangeEvent> snapshot) {
            print('snap shot auth state changed to ${snapshot.data.toString()}');
            if (snapshot.data == AuthChangeEvent.passwordRecovery) {
              return Column(
                children: [
                  const Text('Set New Password'),
                  TextField(
                    controller: controller,
                    decoration: const InputDecoration(
                      filled: true,
                    ),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      if (controller.text.isEmpty ||
                          controller.text.length < 8) {
                        return;
                      }
                      Supabase.instance.client.auth
                          .update(
                              UserAttributes(password: controller.text.trim()))
                          .catchError((error) {
                            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('ERROR : $error')));
                          })
                          .then((value) => Navigator.of(context)
                              .pushReplacement(MaterialPageRoute(
                                  builder: (ctx) => const AuthScreen())));
                    },
                    child: const Text('Submit'),
                  ),
                ],
              );
            } else {
              SomeOtherWidget(),
            }
          })
```

having done all that problem arises when the i put in my email and when the recovery link is emailed to me it show nothing i opened the link both in my desktop browser and in my emulator browser and even my real phone the response is like below 
![response_browser](https://user-images.githubusercontent.com/41432455/145458493-59382fc0-fa5a-4daa-a3e9-411f73293d65.png)

![response_emulator](https://user-images.githubusercontent.com/41432455/145458523-6bf4a6cb-369b-44b8-bc9f-17f0249d8a6c.png)

i am sure that user exist as it is shown in users section in supabase 

 i dont know what i am doing wrong and i dont know how to proceed with app recognizing type=recovery parameter in url . any help would be much appreciated .</div>

**Comment by R3HP** [comment]
i cloned the repo mentioned above 
created a demo project with user_managment_demo 

![demo_supabase_setting](https://user-images.githubusercontent.com/41432455/145669046-08d9a9eb-870b-4079-9c98-b076cddbdf7c.png)

and configured the flutter project 

```
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await configureApp();
  runApp(MyApp());
}
```

```
Future configureApp() async {
  // init Supabase singleton
  await Supabase.initialize(
    url: supabaseUrl,
    anonKey: supabaseAnnonKey,
    authCallbackUrlHostname: 'login-callback',
    debug: true,
    localStorage: SecureLocalStorage(),
  );
}
```

```
/// TODO: update with your custom SCHEME and HOSTNAME
const myAuthRedirectUri = 'https://izwqdpmcdixbonxjnzfx.supabase.co://login-callback';

/// TODO: Add your SUPABASE_URL / SUPABASE_KEY here
const supabaseUrl = 'https://izwqdpmcdixbonxjnzfx.supabase.co';
const supabaseAnnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYzOTIwNjg0MCwiZXhwIjoxOTU0NzgyODQwfQ.8IOtIQv3cgJ4aXqu-wBHRewl5zRGN7hwLa1vwOGnkCs';

```

results were the same . can please some one tell what am i doing wrong??

**Comment by kiwicopple** [comment]
It looks like you are sending the users to this URL `https://izwqdpmcdixbonxjnzfx.supabase.co://login-callback`. As the error says, this route doesn't exist on your project.

We have a quickstart here, which shows how to link to use deeplinks in Flutter: https://supabase.com/docs/guides/with-flutter#setup-deep-links

perhaps you can update the redirect URL to `io.supabase.flutterquickstart://login-callback/`

I'll close this for now, but if you're still stuck perhaps you can open a GitHub Discussion?
