### ISSUE TITLE
bug: can't prisma migrate dev; pg-bouncer issue

### ISSUE THREAD

**Issue by Vandivier** [supabase/supabase#4443]
# Bug report

## Describe the bug

I try to `prisma migrate dev` with a basic connection string and receive:
```
Error: db error: FATAL: unexpected response from login query
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
...
```

## To Reproduce

1. create a new blitz app. I'm using 0.44.3 but this isn't version-sensitive. it's not even sensitive to using blitz that's just a quick way to get started.
2. create new supabase db and set secrets properly - connection pooling is enabled by default
3. `blitz prisma migrate dev`
4. notice that if you disable connection pooling then you get a different error so this seems to be [related to connection pooling authorization](https://stackoverflow.com/questions/67666667/pgbouncer-closing-because-unexpected-response-from-login-query)

## Expected behavior

1. I should get a success message, then see my prisma schema reflected in supabase GUI or through `prisma studio` GUI.

## System information

- Windows OS, node@v16.2.0, supabase@ not sure? whatever is current in PROD as of today. I don't see the info on settings page.

## Additional context

Connection works on port :5432 (non-pg-bouncer) but fails on :6543 (the port using pg-bouncer)

**Comment by kiwicopple** [comment]
I believe this is an issue with Prisma migrate, not so much the pooler on our side.

There is a documented workaround here: https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505/

I'll close this, but feel free to comment if you need us to revisit this
