### ISSUE TITLE
Additional Signup Confirmation Code

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#4455]
# Feature request

## Is your feature request related to a problem? Please describe.

Current Sign up with email as password flow is a bit distracting from the main user flow, because:

- In first browser tab user starts the signup process
- Signup verification url is sent to email, and this link opens up another tab.
- User ends up with 2 open tabs (which clutters the signup flow).

## Describe the solution you'd like

I believe it could be an option to generate an additional 6 symbol code (e.g. `e3as12`) which is sent to a user as a confirmation email. The Signup flow is simplified to only 1 browser tab:
- In first browser tab user starts the signup process
- Signup verification code is sent to email
- Copy paste the code to an input and done.

## Additional context

I got an inspiration for this feature from https://coolors.co/generate - this is the smoothest email signup experience I've ever seen.

**Comment by kiwicopple** [comment]
Thanks for the feature request @edgarasben - I'll close this one in favor of this issue: 
https://github.com/supabase/gotrue/issues/264

**Comment by edgarasben** [comment]
Oh didn't find it. Thanks!
