### ISSUE TITLE
Support some form of pagination in table editor

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4459]
# Chore

We have users running into issues when their database has a large number of tables or schemas
The dashboard currently doesnt support any form of pagination for these entities atm.

Requires changes in the internal API as well but just saving the issue here for tracking

**Comment by nnaemekaibe** [comment]
Hello @joshenlim Is this ready to be picked up?

**Comment by kiwicopple** [comment]
this is now fixed 👍 

<img width="454" alt="image" src="https://user-images.githubusercontent.com/10214025/192359502-9d6601ca-21f1-414e-b008-6057829b5f73.png">
