### ISSUE TITLE
"The resource was not found" on createSignedUrl

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#4465]
# Bug report

## Describe the bug

Trying to generate signed url of a file uploaded the response 400 give the message "The resource was not found"

## To Reproduce

1. Create a bucket named "conversation_files" public: false
2. By the SQL Editor launch this query: 
`create policy "Enable upload to only authenticated" on storage.objects for insert with check ( bucket_id = 'conversation_files' and auth.role() = 'authenticated')` this query will allow the upload to authenticated user for the bucket 'conversation_files'
3. Upload a file setting the folder like "channel_1/fileloaded.png"
4. Using supabasejs library try to generate the signed url using supabase.storage.from('conversation_files').createSignedUrl('channel_1/fileloaded.png',1440)
5. See error

## Expected behavior

What Im trying to realize is a private chat system where user can upload the files into conversation, for this reason the bucket is private and files are provided by signedUrls

## Screenshots

generation of signedUrl:
![image](https://user-images.githubusercontent.com/36926081/145857600-7596f426-42a6-4c13-9b0a-f2cb6741bbd2.png)

file previously uploaded:
![image](https://user-images.githubusercontent.com/36926081/145857709-cd404e8f-463c-4568-a79a-7066a6d776b9.png)

file stored into supbase/storage-api docker container:
![image](https://user-images.githubusercontent.com/36926081/145857879-2bdae695-78b0-48be-b221-8ac640861a46.png)

response of createSignedUrl:
![image](https://user-images.githubusercontent.com/36926081/145858366-8bc9cb53-4b21-4061-97d5-03d2b2d21e99.png)
![image](https://user-images.githubusercontent.com/36926081/145858419-f7c1a183-955b-44d8-b810-c716b1273cce.png)

supabase-kong and supabase-storage server request's elaboration:
![image](https://user-images.githubusercontent.com/36926081/145859085-afe8bc91-e50b-4f46-873c-55ab9762a769.png)

## System information

- OS: Linux  - Ubuntu
- Browser: Chrome
- Version of supabase-js: ^1.28.5
- Version of Node.js: 16.0.0

**Comment by WilliamFalci** [comment]
My error, was missing the Select Row Policy

**Comment by bcherny** [comment]
Just ran into this same issue. Could be a nice usability improvement to give a better error message for this case, rather than the catch-all "The resource was not found".
