### ISSUE TITLE
option to use questDB for tmeseries datasets

### ISSUE THREAD

**Issue by tera-josegoverno** [supabase/supabase#4468]
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by Isaiah-Hamilton** [comment]
Can you give more information

**Comment by kiwicopple** [comment]
Get @tera-josegoverno - you can vote for new databases in this discussion:
https://github.com/supabase/supabase/discussions/6

Take note of my comment here though: 
https://github.com/supabase/supabase/discussions/6#discussioncomment-80177
