### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by CiriousJoker** [supabase/supabase#448]
# Feature request

## Is your feature request related to a problem? Please describe.

An app for employees accessing a database "in the wild" where internet access is sparse (Germany is a third world country in that regard).

## Describe the solution you'd like

Ideally there would be the same functionality as with Firestore. Modify database locally, syncs back to server once a connection is available. Querying cached data should work out of the box with no client side code necessary. Should be enabled by default.

## Describe alternatives you've considered

Currently considering CouchDB, Parse, Kuzzle, SapphireDB and Appwrite. Using Firebase directly isn't possible for this project due to Open Source requirements and GDPR requirements.

## Additional context

Firebase offers Firestore with really good offline-first support and data sync. Since this project is supposed to be a Firebase alternative, will this ever be supported? I couldn't find anything in the documentation regarding this.

**Comment by kiwicopple** [comment]
Hey @CiriousJoker thanks for the message - this is something we're working on (although it will take a bit of time). We have a discussion here : https://github.com/supabase/supabase/discussions/357

Should we move this conversation there? Thanks

**Comment by CiriousJoker** [comment]
Oh, I must have overlooked that issue. I'd suggest continuing here though instead of there, because this one is more detailed.

**Comment by kiwicopple** [comment]
In order to keep our repository clean, we're keeping long-running enhancements in the discussions. If you want I can convert this to it's own discussion, or you can copy your text to the existing discussion. There's not much point having an issue and a discussion - it will be confusing and harder to maintain

**Comment by CiriousJoker** [comment]
I agree, I'll add it to the discussion
