### ISSUE TITLE
"main" and "postgres" databases in local dev server.

### ISSUE THREAD

**Issue by ozum** [supabase/supabase#4480]
# Bug report

## Describe the bug

Postgres in the development server seem to have two databases: "main" and "postgres". When I tried to connect "main" database, I got "No such database: main" error. 

## To Reproduce

1. Start docker development server using `supabase start`
2. Open "pgAdmin" and try to connect main@localhost:54322

## Expected behavior

Either no "main" database in the database list or we can connect the "main" database. If this is the intended behavior, could you please add docs about why there is a "main" database and why we cannot connect it?

## Screenshots

pgAdmin reports there is no "main" database:

![image](https://user-images.githubusercontent.com/1497060/145960632-7fde0bfa-3618-445a-935b-12f54b420ee8.png)

DataGrip reports, it is trying to connect "postgres", but it is connected to "main". This is really confusing.

![image](https://user-images.githubusercontent.com/1497060/145960694-c2b896bf-db1a-46c6-a99c-9ca8c465f9a1.png)

## System information

- macOS 11.6
- supabase server 0.15.8

Thanks for the nice product and help.

**Comment by soedirgo** [comment]
Hey @ozum, the connection string provided by the CLI goes to pgbouncer which routes it to a specific database (`main` by default). So you can really only connect to one database at a time.

**Comment by ozum** [comment]
Ah, I see. @soedirgo, thanks for the quick response. It will be good to describe it in dev server docs. I didn't think that there is a pool in dev server.
