### ISSUE TITLE
Parent folder is deleted when deleting empty sub folder 

### ISSUE THREAD

**Issue by oliviercperrier** [supabase/supabase#4493]
# Bug report

## Describe the bug

The .emptyFolderPlaceholder that is created when creating a new "folder" gets deleted when an other item is added.

But there is a problem is a create multiple empty subfolders.

Lets say i want to upload a file to my `Avatar` bucket in the following location: `/users/images/userAvatar.jpg`

I will create a folder `user` which will contain the `.emptyFolderPlaceholder` until i create the `images` and finally upload the `userAvatar.jpg`.

I currently have something like this:

Avatar
     /users
            /images
                   /userAvatar.jpg

Here is the problem, if i delete `userAvatar.jpg`, `images` and `users` folders will be deleted because the do not contain the `.emptyFolderPlaceholder` anymore.

## Expected behavior

We should do the same `.emptyFolderPlaceholder` logic, but backward when deleting an item in a folder.

Meaning that if i delete an item in a folder and this item is the last item, a `.emptyFolderPlaceholder` should be added because deleting the file.

**Comment by phamhieu** [comment]
cc @joshenlim

**Comment by oliviercperrier** [comment]
@joshenlim Hey! Thx for the fix, but i realize that the same bug appen also when using the API.

Using my previous example, if a run something like this:

`await supabase.storage.from("avatar").remove(["users/images/userAvatar.jpg"])`

`users` and `images` folder gets deleted.
