### ISSUE TITLE
Beta page theme

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4505]
# Bug report

## Describe the bug

Not sure if this was intentional or not but the beta page when switched to the light theme, the hero and the section below doesn't change to light theme.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/beta](https://supabase.com/beta)
2. Click on `Theme Toggle in footer`
3. Scroll up to `hero`

## Expected behavior

To be in light theme

## Screenshots

https://user-images.githubusercontent.com/70828596/146305318-3975d11b-ff77-4d1f-96c8-712c98f80072.mov

## System information

- OS: macOS
- Browser FireFox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

again I don't know if this was intentional or not.

**Comment by kiwicopple** [comment]
I think it was intentional at the time - but I happy to see an implementation where it's all light if you think it can be improved :)

**Comment by subhaschnadraBodaki** [comment]
I used azure external oauth provider to log in 

Redirect url used is ------ https://aomnqngcqjdcvqovmjjn.supabase.co/auth/v1/callback

It is redirecting me to -------- http://localhost:3000/?error=server_error&error_description=Unable+to+exchange+external+code%3A+0.AVYATe-lM3aaxE2G3zQy-ilZg3WsJb7sWJpBnTQLR_-RJx1WAEU.AQABAAIAAAD--DLA3VO7QrddgJg7Wevrpsz8QdQCyeSynIokYb7cJhztFsxBEpVABWWdpY29U2QtxQtwbiXzdtFS-UnW5EFzSAKiJZIp8gTarIR2YW_jE70aT71TvQ_4-v3JXZi_S_pKYBKF_12fPYks1OuJVDItxEc6MHyOd8iI7HZtwzO-44hAMDBOGvvyw9rszE7Mg-Y6heN9_DuPS8lTgTavwYG5ekyW2W4121LXl8HH0qTF9kCusbVQfLPo8OUOnXX-LwgOfvIuuZm1UmGGSEjddSDa5PCRplKbu9168odz9oywD33p_dw2bQLmWDWHqJd7Q6NWJ1zsEQB396Y_dwABGnKfnNVOPQ3r0XhaDWMkGS2iFLAzUUBSwJtMR7yoGs8MjutNKZhjosPQp_79c86dIvKbzg3E_yKfiEFyZGwK7WALHnVDnmzz1m4FaMHMYPi-rQTNhVoWFFkqsdiQxciUmHOUK6Ul_RgYj-Vx7F4h1dq7N3BZFJEcKaxo9rBMv8I6oSPzCkd9vTbNVXRr96F3uI9ZJIS23ajsy_a2oTb_v3xDgu77V5-GJ6-NuEIvaq0q59Qj7bONwM2d11cZmZrnR5jpNi9ha99DqSMhWgU3HDZeiPwKqrbd3Mrk5x-jxeBbZPopBdYAit21sp7HSHPlp2exIAA#


When i tried it with google it is working fine 
I checked the space also there is no space while entering client id and secret

Can You pls look at this
after Logging i am reflected to login page again
![Screenshot (3)](https://user-images.githubusercontent.com/85378633/147224096-cb78f6e8-9757-4cef-9070-fc01cdcc4d5c.png)
