### ISSUE TITLE
Chore: update Github org description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4513]
# Chore

## Describe the chore

update Github org description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com). There are also other places around the Github org that need to be changed to [supabase.com](https://supabase.com). Didn't know where to put this chore, so it's here.

<img width="1392" alt="Screen Shot 2021-12-16 at 3 38 31 PM" src="https://user-images.githubusercontent.com/70828596/146445874-31ec659b-88ff-48cf-aa17-382ee54a694c.png">

**Comment by kiwicopple** [comment]
good one ! 

> Didn't know where to put this chore, so it's here.

perfect 👌
