### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4517]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, when clicking the supabase logo in the footer the scrolling is very jagged. The feature is adding smooth scrolling to the land page.

## Describe the solution you'd like

Add smooth scrolling.

## Describe alternatives you've considered

Let me know if you have any ideas.

## Additional context

Good for first time contributors.

**Comment by yusiflinurlan** [comment]
Hi ! I can use Js's window.scrollTo with a smooth behavior! I think it's an effective solution for now.

**Comment by Isaiah-Hamilton** [comment]
Additional information, the feature for smooth scrolling will be global instead of just for the landing page since this is happening globally.
