### ISSUE TITLE
The ToolTip of the sidebar icon is missing

### ISSUE THREAD

**Issue by pluwen** [supabase/supabase#4518]
# Bug report

## Describe the bug

No tooltip are displayed when the mouse passes over the icons in the left sidebar.

## Expected behavior

Show the ToolTip.

## Screenshots

![image](https://user-images.githubusercontent.com/555720/146480152-4499b419-9019-4e6b-b4a5-3dbbfe00de8e.png)

## System information

- OS: macOS
- Browser: Edge

**Comment by kiwicopple** [comment]
👍 - we'll add this with a Radix tooltip : https://www.radix-ui.com/docs/primitives/components/tooltip

**Comment by yeganathan18** [comment]
Shall I take the issue? @kiwicopple

**Comment by kiwicopple** [comment]
You're welcome to @yeganathan18 - I think this might also require some changes to our UI libarary too: ui.supabase.com

**Comment by kiwicopple** [comment]
Scratch that - this is now fixed 🎉 https://github.com/supabase/supabase/issues/4595

**Comment by pluwen** [comment]
Cool
