### ISSUE TITLE
Auth email search is case sensitive

### ISSUE THREAD

**Issue by julionav** [supabase/supabase#452]
# Bug report

## Describe the bug

When signing in, email search is case sensitive

## To Reproduce

1. Signup with a new email e.g julio@gmail.com
2. Try to signin with that email but change the case of any character: e.g Julio@gmail.com

Sign in will fail because the search is case sensitive

## System information

- macOS
- Chrome
- Version of supabase-js: 1.1.2

## Additional context

Email search being case insensitive is the standard.

**Comment by carlosstenzel** [comment]
why don't you make a filter first, converting everything to tiny?

**Comment by kiwicopple** [comment]
Thanks for the bug report @julionav - fixing now. Should go out in a few days

**Comment by siffogh** [comment]
Hello, this is still an issue.

**Comment by inian** [comment]
Follow the issue here https://github.com/supabase/gotrue/issues/89 @siffogh
