### ISSUE TITLE
Database error saving new user when change auth.user role column to enum

### ISSUE THREAD

**Issue by ckypper** [supabase/supabase#4529]
I change role column in auth.user to enum
Then sign up function throw this error "Database error saving new user"
![image](https://user-images.githubusercontent.com/33152373/146527682-c73d1d72-a478-4732-a96b-7493209014c9.png)

**Comment by joshenlim** [comment]
hey @ckypper - this is probably an issue whereby the dashboard was allowing you to edit something which shouldn't be able to be editted

for context you can only edit data inside the public schema at this stage - all other schemas are read-only

as of now you shouldn't be able to reach this UI state on the dashboard so i'll go ahead to close this issue, but feel free to reopen! 🙏
