### ISSUE TITLE
Dashboard crashes when drilling into related data

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#4531]
# Bug report

## Describe the bug

Dashboard crashes when drilling into related data

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a column that has relationship and click Edit Column
2. Click on Edit Foreign Key
3. Click the drop down, click out, then close the sidepanels
4. Drill into some data
5. App crashes

## Screenshots

https://user-images.githubusercontent.com/10214025/146530998-770f7b8f-b4bb-4663-8b7a-f99a48967bbe.mp4

## Additional context

Reported on Discord: https://discord.com/channels/839993398554656828/843999948717555735/921346600893288499

**Comment by DukeManh** [comment]
I think this issue was fixed in https://github.com/supabase/grid/pull/114#issuecomment-1035883023 😉. The problem was the foreign entry contains JSON data that needed to be stringified.

**Comment by joshenlim** [comment]
you're right there @DukeManh! :) i'll go ahead to close this issue
