### ISSUE TITLE
Update `Reference > Auth (Server Only)` section

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#4532]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-api-createuser

## Describe the problem

See https://github.com/supabase/cli/issues/110

## Describe the improvement

Update docs according to updated API here: https://supabase.github.io/gotrue-js/classes/GoTrueApi.html

**Comment by imskr** [comment]
I've created a PR for this #4776
