### ISSUE TITLE
An unexpected error has occured when following examples/vue3-ts-todo-list instructions

### ISSUE THREAD

**Issue by dazzag24** [supabase/supabase#4534]
Hi,

I'm following the instructions [here](https://github.com/dazzag24/supabase/tree/master/examples/vue3-ts-todo-list) and when deploying the app in both Github or Gitlab I get this error in Vercel

`An unexpected error occured. Our team has already been notified and are working to resolve the issue, please try again shortly.`

![image](https://user-images.githubusercontent.com/1055831/146579443-56c57085-cf3a-4ba4-9609-a6c61faa4f7e.png)

it creates an new empty repo but thats all.

Any idea what I could be doing wrong?  or is some aspect of the deploy to Vercel functionality broken?

Thanks

**Comment by navtojchahal** [comment]
+1

**Comment by gonsalomon** [comment]
+2

**Comment by codeshenyoujun** [comment]
+3

**Comment by needquit** [comment]
+4,how to solve it ？wait?

**Comment by Hallidayo** [comment]
Hi everyone,

I've just walked through the [vue3-to-do-list](https://github.com/supabase/supabase/tree/master/examples/todo-list/vue3-ts-todo-list) example in the main branch of the Supabase repo following the instructions and I've managed to deploy via Vercel as per the instructions with no errors appearing.

Are you deploying via the main branch on the repo or a forked version?

**Comment by needquit** [comment]
> +4,how to solve it ？wait?
I know the answer ,the cloning path isn't right...

**Comment by thorwebdev** [comment]
Closing out as stale. Please reopen if you're still running into this. Thanks.

**Comment by visions88** [comment]
im still having this issue

**Comment by niklonskyi** [comment]
+1 having the issue

**Comment by zarifRahman** [comment]
i am having this issue

**Comment by Rnreck** [comment]
i am having this issue

**Comment by dawood8080** [comment]
I faced that issue
I Solved it by going to "Import a different Git repository" on the left, and then you can import the repositories that you have or have forked, and you can continue from there.
