### ISSUE TITLE
Max rows in API Settings doesn't working

### ISSUE THREAD

**Issue by Kyoij** [supabase/supabase#4544]
# Bug report
Max rows in API Settings doesn't working
## Describe the bug
I changed Max rows setting but it doesn't seem to work
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'API Settings'
2. Change Max Rows to 10000
3. select table with limit 10000

## Expected behavior
the request has to return 10000 rows
## Screenshots
![image](https://user-images.githubusercontent.com/61374202/146639588-11844e61-a156-4d0f-9a32-4dcb55cb55ce.png)
![image](https://user-images.githubusercontent.com/61374202/146639523-f4e263f4-def2-410a-b1fc-d2319e59a61a.png)
![image](https://user-images.githubusercontent.com/61374202/146639515-09c87489-650c-4766-b693-46dfbf3668fd.png)

**Comment by liechtym** [comment]
Same problem for me.

**Comment by MorrisonWill** [comment]
Same problem. Max rows won't go beyond 1000.

**Comment by ijaspreetsinghh** [comment]
same issue, but can get the total items for a specific scenario and then paginate the list or table?

**Comment by huy8856** [comment]
I have the same problem, even though I set max row larger than my existing records in the table (my current records are over 3000, and I set my limit above it), nothing is happening, every time I request, I only get 1000 records returned to my front-end.

**Comment by steve-chavez** [comment]
Does this only happen on the Table Editor UI? Or also when using a client library like supabase-js?

**Comment by huy8856** [comment]
I think it only happens when using a client library like supabase-js.  When I pulled data from supabase to fill into my front-end, it's only show 1000 items even though I have increased the limit inside my supabase.

**Comment by ijaspreetsinghh** [comment]
@steve-chavez for me, it's not how m reading the data, whether I'm looking in supabase table or fetching data for the frontend, it's always a max of 1000 rows. I'm using https://pub.dev/packages/supabase for fetching data for flutter. though i have max rows limit set to 5000 it's still 1000 max: each time.

**Comment by Ic3m4n34** [comment]
Same problem here

**Comment by joshenlim** [comment]
hey everyone! sorry for the late response for this but we've found the issue and are working on getting a fix out for this, will keep this ticket updated!

**Comment by joshenlim** [comment]
hey all! this issue has been fixed - do let us know nonetheless if anyone's still facing it

**Comment by ShawnToubeau** [comment]
Hey @joshenlim, I'm seeing this issue when using the Supabase client in a Next.js server component. I have my `Max rows` set above `1000` and I tested with a component that looks like this:

```tsx
import { createClient } from "@supabase/supabase-js";

export default function Page() {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL as string,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string
  );

  supabase
    .from("some_table")
    .select("*")
    .then((res) => console.log("Num rows returned: ", res.data?.length));

  return null;
}
```
In my console I'm seeing results capped at 1000:

<img width="652" alt="Screenshot 2023-04-04 at 7 51 46 PM" src="https://user-images.githubusercontent.com/22332636/229946967-8cebfd1b-583f-4919-bbc2-ae0c4211c769.png">

If I then add the `'use client'` directive to the top of my component, the output is what I expect it to be:

<img width="933" alt="Screenshot 2023-04-04 at 7 53 35 PM" src="https://user-images.githubusercontent.com/22332636/229947165-c4586667-509d-4548-9782-bb5ed079e42a.png">

Any ideas what could be causing this? Thanks!

**Comment by serhanguney** [comment]
@ShawnToubeau  try increasing the number of max rows in the Dashboard by going to Project Settings > API > Max rows

<img width="1436" alt="Screenshot 2023-04-24 at 22 51 30" src="https://user-images.githubusercontent.com/67260021/234114123-71ce7f0e-71ca-41e0-a284-f76aa8961549.png">

**Comment by ShawnToubeau** [comment]
@serhanguney I did increase the max rows value within my dashboard. As I mentioned, the value I set is reflected within a Next.js client component but not a Next.js server component.

**Comment by luckyguy73** [comment]
@ShawnToubeau it's because it already cached it at 1000.  I had the same thing on my server component and then set revalidate = 0 and now it gives me expected results and console shows `(cache: MISS)` instead of `(cache: HIT)` which i was getting previously with the 1000 rows

**Comment by saulo-marchi-cb** [comment]
Is there any way of setting the max rows by table instead of the whole API?

**Comment by plfmoura-redraw** [comment]
same here...

**Comment by Lonli-Lokli** [comment]
@ShawnToubeau did you understand why it happens and how to fix? Having same NextJS server problem

**Comment by GaryAustin1** [comment]
This is likely next-js caching the request from before the row limit was adjusted.
