### ISSUE TITLE
Studio API endpoint error

### ISSUE THREAD

**Issue by TannerGabriel** [supabase/supabase#4550]
# Bug report

## Describe the bug

When clicking on the API information button (URL: ` /project/default/api`) inside of Supabase studio the page does not display any API information and shows the following error message.

![supabase studio error message](https://user-images.githubusercontent.com/40315960/146653852-862fbee6-5269-4e8b-9a45-6cd54b33f76a.png)

The container logs also to not log anything:

```
docker logs supabase-studio

> studio@0.0.5 start /usr/src/app
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /usr/src/app/.env
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start self-hosted instance using [this guide](https://supabase.com/docs/guides/hosting/docker)
2. Go to `/project/default/api`

## Expected behavior

The API information is shown when visiting the Endpoint similar to using the managed Supabase service.

## System information

- OS: [e.g. PopOS]
- Browser (if applies) [e.g. chrome, brave]

**Comment by zlever01** [comment]
I'm having the same issue.

**Comment by phamhieu** [comment]
Hi @TannerGabriel @zlever01, the issue should be fixed by [this commit](https://github.com/supabase/supabase/commit/d2845b5c4b57a4833e44dcb93a542516a4776a55).

can you pull the latest code and try again.

**Comment by kiwicopple** [comment]
I'll close this one for now, but feel free to comment again and we can reopen if there is still an error

**Comment by lesliesibanda** [comment]
I/m also having the same issue using the Docker.

I've pulled the latest image but it seems to be an issue [](http://localhost:8000/rest/v1/?apikey=) being hardcoded and not using the .env variables. Using my SITE_URL:8000/rest/v1/?apikey works fine on the browser.

this is what i get `{"swagger":"2.0","info":{"version":"9.0.0","title":"PostgREST API","description":"standard public schema"},"host":"0.0.0.0:3000","basePath":"/","schemes":["http"],"consumes":["application/json","application/vnd.pgrst.object+json","text/csv"],"produces":["application/json","application/vnd.pgrst.object+json","text/csv"],"paths":{"/":{"get":{"tags":["Introspection"],"summary":"OpenAPI description (this document)","produces":["application/openapi+json","application/json"],"responses":{"200":{"description":"OK"}}}}},"parameters":{"preferParams":{"name":"Prefer","description":"Preference","required":false,"in":"header","type":"string","enum":["params=single-object"]},"preferReturn":{"name":"Prefer","description":"Preference","required":false,"in":"header","type":"string","enum":["return=representation","return=minimal","return=none"]},"preferCount":{"name":"Prefer","description":"Preference","required":false,"in":"header","type":"string","enum":["count=none"]},"select":{"name":"select","description":"Filtering Columns","required":false,"in":"query","type":"string"},"on_conflict":{"name":"on_conflict","description":"On Conflict","required":false,"in":"query","type":"string"},"order":{"name":"order","description":"Ordering","required":false,"in":"query","type":"string"},"range":{"name":"Range","description":"Limiting and Pagination","required":false,"in":"header","type":"string"},"rangeUnit":{"name":"Range-Unit","description":"Limiting and Pagination","required":false,"default":"items","in":"header","type":"string"},"offset":{"name":"offset","description":"Limiting and Pagination","required":false,"in":"query","type":"string"},"limit":{"name":"limit","description":"Limiting and Pagination","required":false,"in":"query","type":"string"}},"externalDocs":{"url":"https://postgrest.org/en/v9.0/api.html","description":"PostgREST Documentation"}}`

**Comment by vfpointer** [comment]
did anyone find a solution? 
In my case apikey-request goes to localhost, 
but the request sould go the url site from .env

**Comment by phamhieu** [comment]
@lesliesibanda @vfpointer can you create new issues with related information. Your problems seem to be different with the one on this issue

**Comment by TannerGabriel** [comment]
@phamhieu @kiwicopple Sorry for the late response. I just tested the newest version and am still getting an error. It seems that the browser is trying to access a local Docker service and cannot resolve the address because of that.

```
GET http://kong:8000/rest/v1/?apikey=KEY 
net::ERR_NAME_NOT_RESOLVED
```

**Comment by robin-whg** [comment]
Got exactly the same problem as @TannerGabriel

**Comment by TannerGabriel** [comment]
@phamhieu @kiwicopple Any updates here?

**Comment by TannerGabriel** [comment]
After changing the `KONG_URL` to the IP-Address instead of the `http://kong:8000`I receive the following error:

```
GET http://IP:8000/rest/v1/?apikey=KEY 401 (Unauthorized)

Error: [401] Invalid authentication credentials
```

Is this already a know issue? @phamhieu @kiwicopple

**Comment by phamhieu** [comment]
> Is this already a known issue

You need to provide `apiKey` in the request headers instead.

**Comment by TannerGabriel** [comment]
@phamhieu I only used `KEY` as a placeholder since I did not want to reveal my real key. I have just generated a new pair of `anon` and `service` keys and it still does not work.

**Comment by m2scared** [comment]
> Got exactly the same problem as @TannerGabriel ...so the issue should be open.

Me to. Same issue as @TannerGabriel in a fresh install.

**Comment by m2scared** [comment]
I believe I may have found the issue. @TannerGabriel and @robin-whg can you try to update https://github.com/supabase/supabase/blob/master/docker/volumes/api/kong.yml#L8-L12 with your keys?

At least now I can see the screen.

![image](https://user-images.githubusercontent.com/93332316/153050527-021602e8-c51d-4d8e-a680-ee9a31b6f6d3.png)

**Comment by TannerGabriel** [comment]
@m2scared Yes, it seems that I forgot to change these two variables after generating the new key.

**Comment by m2scared** [comment]
> @m2scared Yes, it seems that I forgot to change these two variables after generating the new key.

I am not sure if the doc says to do so. I hit that by coincidence.

**Comment by phamhieu** [comment]
Hi @m2scared, we already covered this in the docs https://supabase.com/docs/guides/hosting/docker#generate-api-keys

**Comment by m2scared** [comment]
> Hi @m2scared, we already covered this in the docs https://supabase.com/docs/guides/hosting/docker#generate-api-keys

Hi @phamhieu. Thanks! I missed that.
