### ISSUE TITLE
Blog images don't fit on smaller screens

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4556]
# Bug report

## Describe the bug

The blog images don't fit on smaller screens and need to be resized.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [blog page](https://supabase.com/blog)
3. Scroll down to an image that doesn't fit

## Expected behavior

The images on the blog page fit on smaller screens.

## Screenshots

<img width="797" alt="Screen Shot 2021-12-19 at 12 46 15 AM" src="https://user-images.githubusercontent.com/70828596/146665459-88b85aed-56eb-47a2-b791-55dda6d3a84c.png">

## System information

- OS: macOS
- Browser FireFox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Good for first time contributors.

**Comment by kiwicopple** [comment]
Looks like we might need to upade these OG images to be a bit more centered-friendly. Just need a good designer to go through some of the older posts :)
