### ISSUE TITLE
Bug: Can't login into app.supabase.io

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4571]
# Bug report

## Describe the bug

Redirects to the SignIn page after signing in.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [app.supabase.io](https://app.supabase.io)
2. Click on `SignIn with Github`

## Expected behavior

Able to SignIn

## Screenshots

https://user-images.githubusercontent.com/70828596/146715789-75588acb-f2b5-410e-856c-48603c6774b3.mov

## System information

- OS: macOS
- Browser FireFox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

similar to #4448

**Comment by liuqian1996** [comment]
me too

**Comment by ManishSavaliya890** [comment]
me too

**Comment by kiwicopple** [comment]
we're just switching the Dashboard logins over to Supabase Auth now (previously it was on Auth0). If you are experiencing issues, some ideas:

- clear all cookies + localstorage 
- check that you have verified your email on GitHub. If not, please verify your email then try to login again

**Comment by liuqian1996** [comment]
I can login resumed just now

**Comment by alexrabin** [comment]
I'm getting this issue.
