### ISSUE TITLE
Update docs for `.select()`

### ISSUE THREAD

**Issue by EndBug** [supabase/supabase#4587]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/select#parameters

## Describe the problem

The parameters docs say that the `column` parameter is required, but the first example in the page shows that it's not.

## Describe the improvement

The parameter should not be marked as required.

**Comment by pri1311** [comment]
Seems like a good issue to begin with :)
Could I take this up?

**Comment by EndBug** [comment]
Sure!
