### ISSUE TITLE
Bucket Policy Doesn't Delete

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#4600]
# Bug report
Bucket Policy doesn't delete
## Describe the bug
I deleted all buckets and database tables. I ran the UserManagement Starter SQL query and got this error
policy "Anyone can upload an avatar." for table "objects" already exists

## To Reproduce
Delete the avatars bucket. Run the User Management Starter SQL

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

Create a "new" bucket called avatars with all policies in place

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by jtkeyva** [comment]
Update:
I recreated the "avatars" bucket manually and the policies were there. I deleted the policies manually, then deleted the bucket. When I ran the User Management Starter SQL again, it worked.

**Comment by jtkeyva** [comment]
Sorry, didn't mean to close. I believe this is still a bug, but with a workaround.

**Comment by eMeRiKa13** [comment]
I just had exactly the same bug.

**Comment by joshenlim** [comment]
Related to https://github.com/supabase/supabase/issues/2110#event-5821988514

**Comment by joshenlim** [comment]
hey @jtkeyva - you're right! there's an issue in the dashboard that we aren't clearing policies related to the bucket when the bucket itself is deleted. The current workaround is exactly what you did to clear the policies manually. For those who are facing the same issue, here's how you can go along doing this:

Check all of your policies from storage.objects
`select * from pg_policies where schemaname = 'storage' and tablename = 'objects';`

Delete the policies which are related to your bucket
`DROP POLICY "{name}" ON storage.objects;`

**Comment by Hum4n01d** [comment]
Looks like this issue was closed but I just encountered this exact bug
