### ISSUE TITLE
Change highlight color to supabase brand color

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4612]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the highlight color is the default blue. The feature is to change the highlight colors to supabase brand color.

## Describe the solution you'd like

change the global highlight color to supabase branded color.

## Additional context

This might be a little too much green so make sure to let me know and to add some screenshots. Also, good for time contributors.

**Comment by nishit-g** [comment]
Hey I would love to take a shot at this !

**Comment by Isaiah-Hamilton** [comment]
> Hey I would love to take a shot at this !

@nishit-g you got this! 🚀

**Comment by nishit-g** [comment]
Hey @Isaiah-Hamilton , have a look 

```css
::selection {
  @apply bg-green-400;
  color: #333 !important;
}
```

<img width="1440" alt="supabase_highlight_color" src="https://user-images.githubusercontent.com/32142878/147271250-937e2da3-0474-4962-af64-c7e2f810a5b2.png">

<img width="1440" alt="Screenshot 2021-12-23 at 10 32 24 PM" src="https://user-images.githubusercontent.com/32142878/147271422-8de17556-25ed-4f69-b9a3-1f141b82df83.png">

**Comment by Isaiah-Hamilton** [comment]
@nishit-g can you try a lighter color?

**Comment by nishit-g** [comment]
What about this ?  


<img width="1440" alt="Screenshot 2021-12-23 at 10 37 30 PM" src="https://user-images.githubusercontent.com/32142878/147271963-cca6c1d1-1ec0-42e3-87b1-87a40f332dec.png">

<img width="1440" alt="Screenshot 2021-12-23 at 10 37 51 PM" src="https://user-images.githubusercontent.com/32142878/147272009-fc76b7a4-b953-42f9-abec-c76a84f1ec36.png">
