### ISSUE TITLE
Can't call extension function from a stored function

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#462]
# Bug report

I'm trying to create a stored function that uses the `http` extension. However, when I try to call one of the `http` functions, it produces errors like `function http_post(character varying, character varying, character varying) does not exist`.

I also tried calling `extensions.http_post(...` but that raises the error: `permission denied for schema extensions`.

Disclaimer: I'm a plpgsql noob so it's possible I'm just trying to call the function incorrectly.

## To Reproduce

1. Enable the `http` extension
2. Run the following from the SQL Editor:
```sql
CREATE OR REPLACE FUNCTION public.http_test() RETURNS integer AS $$
DECLARE status integer;
BEGIN
SELECT status INTO status FROM http_get('http://httpbin.org/ip');
RETURN status;
END;
$$ LANGUAGE plpgsql;
```
3. Call `http_test`

## Expected behavior

I would expect the stored function to be able to call extension functions.

**Comment by kiwicopple** [comment]
Hi @emschwartz  - I think the user calling the function cannot access the `extensions` schema.

Can you try adding `security definer` to the end, which will run the function as the user who *created* the funciton:

 `$$ LANGUAGE plpgsql security definer;` 
 
 That should help us debug the error. Also check out "Writing SECURITY DEFINER Functions Safely" in the docs: https://www.postgresql.org/docs/current/sql-createfunction.html
 
 It is recommended to add the `extensions` search path.

**Comment by emschwartz** [comment]
Adding the `security definer` as you described, along with setting the search path worked. (Without setting the search path, it was able to call `extensions.http_post` but then raised the exception `type "http_request" does not exist`)

Thanks for the help!
