### ISSUE TITLE
Can no longer log in?

### ISSUE THREAD

**Issue by Jakemangan** [supabase/supabase#4632]
# Bug report

## Describe the bug

I'm no longer able to log in to the Supabase portal. Whenever I try to I get to the "Sign in with Github" screen (which I've already done, I have an active project), and then clicking that button produces an error message "Please verify your email on Github first, then reach out to us at support@supabase.io to log into the dashboard".

If I go to Developer Settings on Github there's no mention of Supabase anywhere, there's nothing to verify. No email to verify either. 

I've cleared all cache, cookies, etc. Tried incognito, nothing helps.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Attempt to login to Supabase.
2. Can't.

**Comment by Jakemangan** [comment]
I can confirm that my github email is verified and is the primary email.

I've also tried revoking Supabase's access from Github and re-allowing, but that produces the same result.

**Comment by inian** [comment]
Duplicate https://github.com/supabase/supabase/issues/4448 and responded in the support ticket
