### ISSUE TITLE
Randomly getting kicked out

### ISSUE THREAD

**Issue by IvanCodeslol** [supabase/supabase#4635]
# Bug report

## Describe the bug
Every 2 minutes or so I get kicked out from the Supabase panel (see screenshots)

## To Reproduce

You don't have to do anything to get this, just being in the panel does it. 

## Expected behavior

I don't get kicked out.

## Screenshots

https://imgur.com/a/qyRAGhH

## System information

- OS: Linux 
- Browser: Mozilla Firefox 95.0
- Version of supabase-js: This is a panel bug
- Version of Node.js: This is a panel bug

**Comment by kiwicopple** [comment]
It seems that your session isn't refreshing correctly here @IvanCodeslol - although I'm not sure why that would be. 

Do you have anything blocking localstorage functionality on your Firefox browser? If you clear all the application cache and try again, do you still experience the issue?

**Comment by IvanCodeslol** [comment]
I don't get kicked out anymore, didn't have to clear my cookies. Also I did not have an extension blocking localstorage functionality and the supabase website could read/write to my localstorage.
