### ISSUE TITLE
Add support for 2factor.in 

### ISSUE THREAD

**Issue by nickwithlove** [supabase/supabase#4649]
# Feature request

## Is your feature request related to a problem? Please describe.
Add support for 2factor.in or Text Local

A clear and concise description of what you want and what your use case is.
Need an Indian service that meets indian TRAI guidlines.

## Describe the solution you'd like
Integrate 2factor API with Supabase

**Comment by kiwicopple** [comment]
thanks for the FR @nickwithlove - we're tracking this one here!

https://github.com/supabase/gotrue/issues/14
