### ISSUE TITLE
Parent folder is deleted when deleting empty sub folder

### ISSUE THREAD

**Issue by oliviercperrier** [supabase/supabase#4671]
# Relates to issue [https://github.com/supabase/supabase/issues/4493](url)

# Bug report

## Describe the bug

@joshenlim Hey! Thx for the fix, but i realize that the same bug appen also when using the API.

The .emptyFolderPlaceholder that is created when creating a new "folder" gets deleted when an other item is added.

But there is a problem is a create multiple empty subfolders.

Lets say i want to upload a file to my `Avatar` bucket in the following location: `/users/images/userAvatar.jpg`

I will create a folder `user` which will contain the `.emptyFolderPlaceholder` until i create the `images` and finally upload the `userAvatar.jpg`.

I currently have something like this:

Avatar
     /users
            /images
                   /userAvatar.jpg

Here is the problem, if i delete `userAvatar.jpg` using the API like this 
````
await supabase.storage.from("avatar").remove(["users/images/userAvatar.jpg"])
````
, `images` and `users` folders will be deleted because the do not contain the `.emptyFolderPlaceholder` anymore.

## Expected behavior

We should do the same `.emptyFolderPlaceholder` logic, but backward when deleting an item in a folder.

Meaning that if i delete an item in a folder using the API and this item is the last item, a `.emptyFolderPlaceholder` should be added because deleting the file.

**Comment by joshenlim** [comment]
Hey there @oliviercperrier! This is the correct behaviour of our storage API - the existence of `.emptyFolderPlaceholder` is specific to only our dashboard as we're displaying your storage objects as a folder hierarchy.

Supabase storage follows S3 in which there are actually no tangible concept of "folders" but more of prefixes (e.g 'folder1/folder2/cats.png') - its just a flat file structure. Hence why if you refer to the docs on uploading, one of the parameters is a path to upload your file to.

If you upload a file to lets say under the prefix 'folderA/folderB/dogs.png' for example, then the "folders" folderA and folderB are implicitly created, but there aren't really any folders.

Hope this helps!

**Comment by oliviercperrier** [comment]
> Hey there @oliviercperrier! This is the correct behaviour of our storage API - the existence of `.emptyFolderPlaceholder` is specific to only our dashboard as we're displaying your storage objects as a folder hierarchy.
> 
> Supabase storage follows S3 in which there are actually no tangible concept of "folders" but more of prefixes (e.g 'folder1/folder2/cats.png') - its just a flat file structure. Hence why if you refer to the docs on uploading, one of the parameters is a path to upload your file to.
> 
> If you upload a file to lets say under the prefix 'folderA/folderB/dogs.png' for example, then the "folders" folderA and folderB are implicitly created, but there aren't really any folders.
> 
> Hope this helps! Feel free to open a discussion about this if you still need any other clarification - happy to chime in

Hey!

Yes, i understand how S3 works and when i think about it, you are right. The actual behaviour is correct. Thanks for the reply.
