### ISSUE TITLE
Realtime broken when policy use custom SQL functions

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#4683]
# Bug report

Applying custom SQL function in RLS broke the realtime but db queries work always

## To Reproduce

Create an SQL function:

```
CREATE FUNCTION is_member_of(_user_email text, _channel_id int8) RETURNS bool AS $$
SELECT EXISTS (
  SELECT 1
  FROM channel_users cu
  WHERE cu.channel_id::int8 = _channel_id::int8
  AND cu.user_mail::text = _user_email::text
);
$$ LANGUAGE sql SECURITY DEFINER;

```
(I tested with and without SECURITY DEFINES as well, bug persist)

then I created a policy for the table channel_users on SELECT using:

`is_member_of(auth.email(), channel_id)
`

then I created another policy always for the same table on UPDATE:

`(auth.email() = (user_mail)::text)
`

the result I expect is:

Im able to update all channel_users rows contain my email
Im able to select all channel_users rows contain an channel_id where Im in

but... into reality... I select, I update, but at moment to set an realtime taks on UPDATE

```
this.supabase
      .from(`channel_users:channel_id=eq.${this.data.channelID}`)
      .on('UPDATE', payload => {
        console.log(payload)
        if (payload.new.user_mail !== this.data.user_loged.user.email) {
          this.data.responderIsTyping = payload.new.is_typing
        }
      })
      .subscribe()

```

He never trigger it (yes replication is enable), if I change the Select policy from 
`is_member_of(auth.email(), channel_id)` 
to 
`true
`

## Expected behavior

Im expecting the RLS work applying the function "is_member_of" to determinate if the user can access or not to the data

## System information

- OS: Linux - Ubuntu
- Browser: Chrome
- Version of supabase-js: ^1.28.5
- Version of Node.js: 16.0.0

## Additional context

Another user reported a similar issue, you can find it in: [This Ticket](https://github.com/supabase/realtime/issues/213)

**Comment by tconroy** [comment]
Just adding a +1 to this issue, as I am encountering the same problem. It seems that RLS policies that call through to custom postgres functions do not work as expected. 

Is it possible that postgres is silently swallowing an error? If so, would be great if we could surface that in some way since right now it just doesn't work without giving any feedback to the developer.

**Comment by w3b6x9** [comment]
see comment here: https://github.com/supabase/realtime/issues/213#issuecomment-1001707881

**Comment by WilliamFalci** [comment]
> see comment here: [supabase/realtime#213 (comment)](https://github.com/supabase/realtime/issues/213#issuecomment-1001707881)

I confirm specifing the schema name before the table name fix the issue
