### ISSUE TITLE
Error: Out of Memory when scrolling table horizontally

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#470]
# Bug report
When scrolling table horizontally to see other columns, web application crashes with console log: "Error: Out of Memory". (See screenshot below).

## Describe the bug
When scrolling table horizontally to see other columns, web application crashes with console log: "Error: Out of Memory". (See screenshot below).

## To Reproduce

1. Create a new table that has fields more than the screen allows
2. Add a column with data type text[]
3. Add a value to the column with the data type text[].
4. Scroll past the screen width and application crashes with Error: Out of Memory

## Expected behavior

Screen should horizontally scroll without any issues

## Screenshots

![Screen Shot 2021-01-05 at 12 08 07 AM](https://user-images.githubusercontent.com/70461143/103555005-c5a26480-4eea-11eb-94da-58a9c336f519.png)

## System information

- OS: macOS catalina
- Browser: Safari
- Version of supabase-js: 2020.11.03.04
- Version of Node.js: v12.18.2

**Comment by joshenlim** [comment]
Hey there @inbytesdevteam! Could I check real quick which version of Safari you are using?

**Comment by inbytesdevteam** [comment]
Hi @joshenlim - Version 13.1.2 (15609.3.5.1.3)
Btw, tried it with Chrome and it has the same issues too.

**Comment by joshenlim** [comment]
Ahh gotcha on this that's a great catch @inbytesdevteam - thanks so much! Just to clarify the steps to reproduce the error:

- Create a column of text array type
- Add a row with an array of text
- Bug occurs

Gotcha on the second bug you mentioned as well! We noticed this a while back too and have pushed a fix for that!

**Comment by inbytesdevteam** [comment]
Hi @joshenlim! Yes! :)
Thanks in advance for the fix! 👍

**Comment by joshenlim** [comment]
Hey @inbytesdevteam so i'm trying out the creation of text array type column to reproduce the bug as such:

![image](https://user-images.githubusercontent.com/19742402/103732421-47e17480-5022-11eb-9768-d98c6ec4f079.png)

But the error doesn't seem to occur for me. So sorry to inconvenience you but would you mind dropping a screen recording to cover the steps for reproducing the error?

I did notice a bug when creating a column of an array type, that it forces you to enter a default value - will have that fixed but for now you could just enter `{}` in the default value field

**Comment by inbytesdevteam** [comment]
Hi @joshenlim! I just tried it out now and no more errors are occuring. Must have been fixed from the patches today. :) Thank you! :)

**Comment by joshenlim** [comment]
Ahh perfect haha thanks so much for confirming, really appreciate it! 🙏
