### ISSUE TITLE
Create a React Native example and Quickstart

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#4702]
# Chore

## Describe the chore

We already have an Expo guide here: 

And an example here: https://github.com/supabase/supabase/blob/master/examples/expo-todo-list

It would be great to have something similar for React Native. The code will be mostly the same, but it will be helpful for anyone who is new to RN and doesn't know how to translate the Expo examples to RN.

Todo:

- [x] example: https://github.com/supabase/supabase/pull/4733
- [ ] quickstart

**Comment by vasudeveloper001** [comment]
Let me do it. I am a beginner in pretty much all things here.

**Comment by kiwicopple** [comment]
thanks @vasudeveloper001 ! I'm sure if you start a small PR then everyone here can help give some comments

**Comment by vasudeveloper001** [comment]
> thanks @vasudeveloper001 ! I'm sure if you start a small PR then everyone here can help give some comments

Thanks. I will set up react native inside example folder first thing tomorrow morning and will create a initial pull request. Or can I be assigned to this task so that other people don't spend needless time in it? @kiwicopple

**Comment by Isaiah-Hamilton** [comment]
Working on a React Native quick start.

**Comment by thorwebdev** [comment]
Some other helpful resources
- https://supabase.com/docs/guides/with-expo
- https://github.com/supabase/supabase/tree/master/examples/expo-user-management
- https://github.com/supabase-community/expo-stripe-payments-with-supabase-functions
