### ISSUE TITLE
Kong Error : No Api key found in request

### ISSUE THREAD

**Issue by dukesx** [supabase/supabase#4716]
# Bug report

## Describe the bug

I am trying to use flutter client of supabase to send a password reset link, however i am using "redirect to" param to redirect the user to my app, where i show my user the reset form. When the user clicks on reset link received in email, the user receives the error 

Which Link Do i receive ? 
```
https://[hidden-project-id].supabase.co/auth/v1/verify?token=zBhzNsGKt2ICKpaD6-zlrw&type=recovery&redirect_to=com.mobile.app://reset-callback/
```

Where does the above link redirect to (when clicked) ?

```
https://[hidden-project-id].supabase.co/auth/v1/com.mobile.app://reset-callback/#error_code=404&error_description=User+not+found
```

Client reports no error and so far the user exists in the Dashboard > Auth > Users with the email.

**Note: I have already added the "redirect url" in my additional redirect urls, seperated by comma (since there are two) and i have also added the deep links**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use Supabase Flutter
2. have a user registered using email
3. reset password using .**resetPasswordForEmail**() function with redirect url as "com.app_name.etc://reset-callback"
4. Receive the email
4. Click the email link
5. See Kong Error

## Expected behavior

Link should redirect user to my app's deep link (as entered in redirect url param) 

## Screenshots

![Untitled](https://user-images.githubusercontent.com/5988991/147595606-6035d94c-c088-42ae-8ce0-42a415d2a46e.png)

Url that causes this: 
```
https://[hidden-project-id].supabase.co/auth/v1/com.mobile.app://reset-callback/#error_code=404&error_description=User+not+found
```

## System information

- OS: Android 11
- Browser (Noop)
- Version of supabase_flutter (^0.2.9)

**Comment by kiwicopple** [comment]
Hmm, looks kike that URL isn't right. Would you mind opening this one in the Dart repo @dukesx ?

https://github.com/supabase-community/supabase-dart

**Comment by dukesx** [comment]
@kiwicopple I have now opened there as well. I did update my issue , please refresh and check for additional debugging details

**Comment by kiwicopple** [comment]
let's track over there!

https://github.com/supabase-community/supabase-dart/issues/76
