### ISSUE TITLE
Failure adding Supabase integration to Vercel

### ISSUE THREAD

**Issue by gustavobigardi** [supabase/supabase#4717]
# Bug report

## Describe the bug

Failure adding Supabase integration to Vercel. When the modal screen with the supabase page to integrate a Vercel project to Supabase project is opened, an error "Retrieve vercel projects failed. An error has occured: 401" appears.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a integration marketplace on Vercel
2. Find the Supabase integration (https://vercel.com/integrations/supabase) and click on Add Integration
2. Select a scope from Vercel (in my case, gustavobigardi)
3. Select All projects or some specific projects, the error occurrs with both scenarios, and click on Add Iintegration.
4. In the new window that opens, the error will be displayed and the list of Vercel projects will be empty.

## Expected behavior

I need to select a project from Vercel to integrate with a Supabase project.

## Screenshots

- Error:
![Screenshot from 2021-12-28 17-08-15](https://user-images.githubusercontent.com/8357566/147603316-6fa80dab-4786-42db-a829-c5948809abcd.png)

- Empty project list:
![Screenshot from 2021-12-28 17-08-56](https://user-images.githubusercontent.com/8357566/147603339-3dd2b027-13c6-4d26-b037-3141e9e94e0b.png)

## System information

- OS: Arch Linux; Build ID: rolling
- Browser: Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by alexdkaminski** [comment]
+1 Having the exact same issue on Chrome and Windows 10

**Comment by joshenlim** [comment]
Hey everyone! Can I check real quick if this is still happening for anyone?
