### ISSUE TITLE
Rollback + transactions

### ISSUE THREAD

**Issue by rickysullivan** [supabase/supabase#472]
Is there anyway to perform multiple insert commands that can be rolled back if any error?

**Comment by steve-chavez** [comment]
@rickysullivan Yes, that can be done with functions. Check this example on https://github.com/supabase/supabase-js/issues/87#issuecomment-739537955

**Comment by swkeever** [comment]
It'd be cool if we could do transactions directly in the application code. Maybe something like this?

```js
const tx = supabase.begin()
tx.from('cities').update({ name: 'Middle Earth' }).match({ name: 'Auckland' })
tx.from('cities').delete().match({ id: 666 })
const {data, error} = await tx.commit()
if (error) {
  tx.rollback()
}
```

**Comment by avin-kavish** [comment]
> It'd be cool if we could do transactions directly in the application code. Maybe something like this?
> 
> ```js
> const tx = supabase.begin()
> tx.from('cities').update({ name: 'Middle Earth' }).match({ name: 'Auckland' })
> tx.from('cities').delete().match({ id: 666 })
> const {data, error} = await tx.commit()
> ```

Is this technically possible? transactions work at the db connection level. Can't be held open across a REST interface.

**Comment by kiwicopple** [comment]
it is technically possible, but something we are unlikely to do within the client libraries since it could cause a lock on a table if the transaction fails due to a network error. We could add timeouts, but it's much safer to just write a Postgres Function and call it with an `rpc()` request.

**Comment by steve-chavez** [comment]
> Is there anyway to perform multiple insert commands that can be rolled back if any error?

Just wanted to clarify the original question: our [bulk insert](https://supabase.com/docs/reference/javascript/insert#bulk-create) already rolls back if there's an error.

> Is this technically possible? transactions work at the db connection level. Can't be held open across a REST interface.

Yeah, I don't think [long-running transactions](https://github.com/supabase/postgrest-js/issues/219) will ever be safe on the client side. For now, https://github.com/supabase/postgrest-js/issues/240 is the path forward for more complex mutations.

**Comment by avin-kavish** [comment]
Client initiated transactions aren't just used for complex mutations. They are used for coupling with other operations on the client-side. Like,

```
  Begin transaction
  Send 3rd Party API request
  Do DB Insert
  Send Email
  End transaction
```

**Comment by kiwicopple** [comment]
> Send 3rd Party API request

It would be extremely hard for us to "rollback" anything which isn't directly controlled by Supabase (for example, add Stripe customer, insert into Postgres database (fail), roll-back stripe customer creation).

Perhaps a good tool to investigate for this sort of asynchronous transaction workflow would be [Temporal](https://temporal.io/). Note the level of engineering they are doing to ensure the type of transaction-level safety across distributed systems, it's not an easy problem!

**Comment by swkeever** [comment]
I don't have context on the implementation of the client library or PostgREST, but my assumption was that
```js
const tx = supabase.begin()
```
would instantiate a string builder, and each insert/update you do would add to the state of that builder.

Then, the only time a network call is made is when you call `tx.commit()`. At that time, the state of the builder (i.e. the transaction command) is sent to PostgREST. My assumption is this would be similar to issuing an `rpc` command.

Of course, there would still be limitations as you guys pointed out i.e. Stripe rollbacks, send emails, etc.

**Comment by kiwicopple** [comment]
> the only time a network call is made is when you call tx.commit(). 

That's an interesting concept! We would probably need to add a bunch of functionality for handling "return values" throughout the transaction (for example, the ID of a newly-inserted record). 

I guess the main question is why we would need this over an `rpc()` call or our \*_cough cough_\* upcoming Functions. It might be a bit of a burden (and security hole) coding this sort of functionality into a client side library (especially as we add more supported languages).

Still - of all the ideas so far, this sounds the most appealing

**Comment by swkeever** [comment]
> the main question is why we would need this over an rpc()

I guess the main reason is developer experience. In my opinion, I like to keep my business logic in the application code, all in one place, rather than setting up Postgres functions, etc.

I guess I should also mention I only ever use the Supabase Postgres client from the server. Theoretically, I could use another Postgres client, but I like the API you guys expose. Hopefully, I'm not getting too off-topic, but maybe one day there could be a Supabase Admin client (kind of like [Firebase Admin](https://firebase.google.com/docs/admin/setup)) that directly connects to Postgres, unlocking the full potential of the database.

**Comment by dnguyenlearning** [comment]
very tired to write complex logic in rpc... please consider to push this request at high priority. You have awesome client sdk. make it more valuable for JS developer.

**Comment by steve-chavez** [comment]
> very tired to write complex logic in rpc

@dnguyenlearning Could you share an example of the complex logic you do? I'd like to know if the proposal for the interface on https://github.com/supabase/postgrest-js/issues/219#issuecomment-1228699296 would be enough to cover your use case.
