### ISSUE TITLE
Universal Login - Share login session between different subdomains.

### ISSUE THREAD

**Issue by lightsound** [supabase/supabase#473]
# Feature request

Universal Login. I'd like to share the login session between different subdomains.

## Describe the solution you'd like

I don't know much about that, but I've heard there are two general ways.

1. Using cookies like [SuperTokens](https://supertokens.io).
2. Local Storage + iframe like [Auth0](https://auth0.com).

If there are other alternatives, I'd like to know about them.

## Describe alternatives you've considered

The problem is the relationship between Authentication and Project is one-to-one. This is also the case in firebase. If we want to implement Universal Login, we have to take another option.

Supabase is really useful and has great potential. With Universal Login, Supabase will be able to handle more use cases.

**Comment by carlosstenzel** [comment]
Could you create a project just to authenticate

**Comment by romshiri** [comment]
Did you find any solution/workaround for this? Facing the same issue..

**Comment by J0** [comment]
Hey @lightsound and @romshiri 

Wanted to check if y'all managed to try out @kiwicopple 's solution? Do let us know if you are still facing issues and we'd be happy to jump in.

Thanks!

**Comment by kiwicopple** [comment]
closing this one for now, but feel free to comment if there's any problems and we can re-open 👍

**Comment by jtiulentino** [comment]
hey @J0 and @kiwicopple, I tried to add in wildcard subdomains in the dashboard (per your suggestion above), but the shared login session still isn't working... any way you can help? thanks in advance 🙏

**Comment by J0** [comment]
@jtiulentino  sure thing, could we trouble you to shoot us a support ticket at support@supabase.io with a screenshot of your wildcard configuration settings and a description of the expected behavior you are trying to produce?

**Comment by jtiulentino** [comment]
will do - many thanks! we really appreciate it.

**Comment by mayone-du** [comment]
@J0 @jtiulentino 

Hi, do you have any additional information?

I am facing the same problem.

1. set `additional_redirect_urls` in config.toml as follows.

`additional_redirect_urls = ["http://localhost:3000", "http://*.localhost:3000"]`.

2. after logging in at localhost:3000, access hoge.localhost:3000.

3. I cannot share the login session.

If anyone has a solution, please let me know.

**Comment by hf** [comment]
Hey @mayone-du I'm not sure on how you plan to use iframe and postMessage, I believe it's doable that way but it's a fairly complex way to do it.

I've just answered [this discussion](https://github.com/supabase/supabase/discussions/5742) which may be helpful.

Regarding what @kiwicopple is talking about with the Additional Redirect URLs: This is a protection mechanism that specifies _what URLs_ signed-in users can be taken to securely; it does not mean that cookies or access and refresh tokens will be shared with all of the URLs in that list.

Let me know if you have further questions!

**Comment by jtkeyva** [comment]
@hf @kiwicopple @mayone-du any success on this? would love to share universal login through different apps

**Comment by logemann** [comment]
> finally in supabase dashboard -> auth -> url-configuration
> set Site URL -> http://id.localhost.com
> add Redirect URLs -> http://cp.localhost.com

So this is only for the auth config in "id" project. What to do in the "cp" project?
