### ISSUE TITLE
Use alpine based images instead of default

### ISSUE THREAD

**Issue by quentincaffeino** [supabase/supabase#4736]
# Chore

## Describe the chore

Title is pretty self explanatory. I want to believe that this is one of the cases where rule less is more is perfectly applicable especially when you don't loose anything.

I want to know what do you think about this? Was it a deliberate choice to go with debian based image or as it mostly is because it was made to ship product as fast as possible?

**Comment by J0** [comment]
Seems like we have decided to go with node-14 slim instead of alpine. Closing this for now but feel free to re-open if there are still concerns
