### ISSUE TITLE
[Website, UX] Confusingly named "login" button

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase#4739]
# Bug report

## Describe the bug

On the Supabase website, what is effectively the "login" button is named "Start your project" which can be confusing / dissonant when unconsciously [Thin Slicing](https://en.wikipedia.org/wiki/Thin-slicing) upon page load and expecting to see some derivation of the common `[Login] [Sign up!]` top-right button pattern. _(In this case "Sign up!" being "Start your project")_

### Current screenshot
<img width="762" alt="image" src="https://user-images.githubusercontent.com/65471523/147717427-5625139a-182a-4840-aca2-567484f3ae3c.png">

Naturally, from a technical perspective given Supabase uses GitHub OAuth, both buttons end up at the same place, but from a UX perspective having a named "Login" button would reduce the dissonance.

The "Star us on Github" button is currently occupying this space and several times I've accidently clicked it when navigating quickly as I've unconsciously pattern matched it as the "Login" button. 

## Suggestion 

To retain the prominence of the "Star us on Github" button, it could be subordinated to the left and restyled with 
```html
<button class="sbui-btn sbui-btn-text sbui-btn--medium py-3 sbui-btn--text-align-center">...</button>
```

<img width="892" alt="image" src="https://user-images.githubusercontent.com/65471523/147718072-96e9e5a7-8cec-4b15-ac45-f39ebe3b44e2.png">

 

## System information

- OS: Windows + OSX
- Browser (if applies) Any browser using a desktop display resolution. 

 
## Edit
_edit: upon the last five minutes of reflection, this is by far the most autistic issue / rant I've ever written so absolutely close if this is not a priority._ 🤦🏻‍♂️😂

**Comment by MayankVir** [comment]
Hi @kiwicopple, Can I make the changes according to the above UI?

**Comment by kiwicopple** [comment]
cc @MildTomato you OK with this change?

**Comment by MildTomato** [comment]
Yea it's ok :) 

I'm going to change it to use 'Sign in' as the label though so we are consistent with Supabase Studio auth labeling style.

As a note going forward, we will perhaps start supporting auth cookies across all our websites so we can show more personalized nav depending on whether a user is logged in or not, although that requires a bit more discussion before we look into that - especially regarding the security of cookies and wether, we want to expose it on more than just a subdomain of supabase.com.

**Comment by MayankVir** [comment]
Thanks, @MildTomato, I am gonna do the changes asap according to the above UI with 3 buttons finally. ( Star, Login, Start ). Does this sound good?

**Comment by MayankVir** [comment]
Hi @kiwicopple, Please review the changes in the PR #4821

**Comment by prescience-data** [comment]
closed with https://github.com/supabase/supabase/pull/4821
