### ISSUE TITLE
customers cannot update their billing email address

### ISSUE THREAD

**Issue by roryw10** [supabase/supabase#4748]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the dashboard general settings
2. Try to update billing email
3. Hit save
4. See 401 error

## Expected behavior

Billing email should update

**Comment by Isaiah-Hamilton** [comment]
This issue seems to be solved!

https://user-images.githubusercontent.com/70828596/152094324-96302df1-7c43-4c0a-9e7c-6dcb66a5e9b4.mov
