### ISSUE TITLE
Supabase app website doesn't refresh auth token

### ISSUE THREAD

**Issue by vabatta** [supabase/supabase#4756]
# Bug report

## Describe the bug

When the auth token expires while using the app, it won't refresh and returns the error `Unauthorized: Invalid token: token is expired by <x>m<y>s` while running queries, then the app crashes to "an unexpected error happened" on a page refresh. This will require to go on the homepage and going through the login flow to get back in the app.

## To Reproduce

1. Go to app.supabase.com
2. Login
3. Stay idle for the token to expire
4. Try to run a SQL query
5. Refresh the page

## Expected behavior

I would expect the token to be refreshed silenty in the background.

## System information

- OS: macOS
- Browser (if applies) chrome latest version (01.01.2022)
- Version of supabase-js: -
- Version of Node.js: -

**Comment by kiwicopple** [comment]
This was likely due to our transition from Auth0 to Supabase Auth. Sorry about that - it should be fixed now

Also sorry for the (extremely) slow response. This one seems to have been lost in the backlog
