### ISSUE TITLE
Bug: Auth UI component error

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4780]
# Bug report

## Describe the bug

When using the button on the auth UI component sends you to an error page.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [auth page](https://supabase.com/auth)
2. Click on any button social button

## Expected behavior

To not be sent to an error page.

## Screenshots

https://user-images.githubusercontent.com/70828596/147972699-36f12f36-eedb-4f02-b19f-e31346b0e981.mov

## System information

- OS: macOS
- Browser: Firefox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Maybe when someone clicks the buttons a toast pops up and says that it's just a demo.

**Comment by kiwicopple** [comment]
> toast pops up and says that it's just a demo

Agreed! Or we can take them to the Auth pages (eg https://supabase.com/docs/guides/auth/auth-github)

**Comment by Sahil-kachhap** [comment]
> # Bug report
> ## Describe the bug
> When using the button on the auth UI component sends you to an error page.
> 
> ## To Reproduce
> Steps to reproduce the behavior, please provide code snippets or a repository:
> 
> 1. Go to [auth page](https://supabase.com/auth)
> 2. Click on any button social button
> 3. See error
> 
> ## Expected behavior
> To not be sent to an error page.
> 
> ## Screenshots
>  Screen.Recording.2022-01-03.at.2.37.00.PM.mov 
> ## System information
> * OS: macOS
> * Browser: Firefox
> * Version of supabase-js: N/A
> * Version of Node.js: N/A
> 
> ## Additional context
> Maybe when someone clicks the buttons a toast pops up and says that it's just a demo.

Hey Isaiah, Are those buttons really for demo purpose. Since currently the Facebook social login button is working but other buttons are still showing that bug.

**Comment by yeganathan18** [comment]
Is the issue already taken? or shall I?

**Comment by Sahil-kachhap** [comment]
> Is the issue already taken? or shall I?

Actually I am currently working on this issue

**Comment by Sahil-kachhap** [comment]
@kiwicopple I have added a badge to show that it is a demo for auth services. So that at least for now users would have an idea that it's a demo. But the redirect issue still persists. Can you tell me where does all redirect kinds of stuff are getting handled?
![supabase screenshot](https://user-images.githubusercontent.com/54017876/148381445-d04732e7-a214-4f49-bc08-3129c6dd8cd2.png)

**Comment by FatumaA** [comment]
> 1. auth page

It seems from the discussions above, you can have the button click on the icons show a toast/.pop up with a message showing users it's a demo instead of the redirect it is currently doing
