### ISSUE TITLE
Auth functions like auth.uid() do NOT handle empty strings

### ISSUE THREAD

**Issue by chipilov** [supabase/supabase#4794]
# Bug report

## Describe the bug

Auth functions like auth.uid() use the 'request.jwt.claims' configuration parameter in order to extract the uid/email/role for the user of the current request.

However, these functions fail if the 'request.jwt.claims' configuration parameter is the empty string because the conversion to jsonb fails.

Handling empty strings for this parameter is important because one can mock different users by setting the parameter for the current transaction, however, it is NOT possible to remove the parameter AFTER the transaction is over - instead, the parameter remains as empty string (as explained here: https://stackoverflow.com/a/50929568/2606261

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Connect to a Supabase PostgreSQL instance using any SQL client;
2. Mock a particular use for a single transaction like this:
```
begin;
set local "request.jwt.claims" to '{ "sub": "d0d4b028-2f87-523b-a580-0f3e85e6ff33", "email": "my@email.com" }';
select auth.uid();
commit;
``` 
3. Try to invoke the auth.uid() again now that the transaction is completed:
```
select auth.uid();
```

## Expected behavior

The second invocation of auth.uid() should return NULL;

## Actual behavior
The second invocation of auth.uid() throw an exception because the empty string cannot be converted to jsonb;

**Comment by kiwicopple** [comment]
Yes, I think you're right - previously we had `nullif` wrapper that was removed as part of the upgrade to postgrest 9:

https://github.com/supabase/supabase/commit/614faed4e47060bbc3b9947315d99d2fa117628a#diff-966f18f6feaf0bfe4d397b1d3fc31b1b31d1d0ffd19a16470bb6691c77362d15

**Comment by chipilov** [comment]
Unless I misunderstand what you mean, I don't think ```nullif``` would resolve the issue - the problem is that when evaluating the second argument to coalesce (```(current_setting('request.jwt.claims', true)::jsonb ->> 'sub')```), you get an exception because the empty string cannot be converted to jsonb.

So even if you wrap the coalesce around a nullif, the exception will take place before ```nullif``` can do anything. I think ```(current_setting('request.jwt.claims', true)::jsonb ->> 'sub')``` should invoked ONLY if the current value of the config parameter is NOT empty.

NOTE: in my Supabase instance, the uid() function has the nullif wrapper (unlike role() and email(), not sure how that has happened), and I still get the error. Here it is:
```
CREATE OR REPLACE FUNCTION auth.uid()
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  select
  nullif(
    coalesce(
      current_setting('request.jwt.claim.sub', true),
      (current_setting('request.jwt.claims', true)::jsonb ->> 'sub')
    ),
    ''
  )::uuid
$function$
```

**Comment by steve-chavez** [comment]
Maybe the `nullif` could be applied like this:

```sql
create or replace function auth.uid() 
returns uuid 
language sql stable
as $$
  select 
  	coalesce(
		nullif(current_setting('request.jwt.claim.sub', true), ''),
		(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
	)::uuid
$$;
```

That way the `::jsonb` casting won't fail, just tested it:

```sql
select nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub';
-- NULL

set request.jwt.claims to '{"sub": "bla"}';
select nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub';
-- bla

set request.jwt.claims to '';
select nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub';
-- NULL
```

**Comment by imskr** [comment]
Can I work on this issue?

**Comment by kiwicopple** [comment]
yes pelase @imskr !
