### ISSUE TITLE
UPDATE RLS with custom header not work

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#4797]
# Bug report

## Describe the bug

Using custom header SELECT and INSERT RLS work perfectly, but UPDATE RLS not work

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. set a custom header paramenter like: "x-hid: x-hid-value"
2. set UPDATE RLS like:
`(((current_setting('request.headers'::text, true))::json ->> 'x-hid'::text) = (hid)::text)`
3. Try to update like:
`supabase.from('guest').update({hid: newHID}).eq('hid',oldHID)`

## Expected behavior

I expect to update the HID

## Screenshots

![image](https://user-images.githubusercontent.com/36926081/148130104-3d41262e-4fd8-4632-a306-05b9a5e0f607.png)
![image](https://user-images.githubusercontent.com/36926081/148130256-e7989018-1699-46cf-83c1-8dca7d874fd0.png)
![image](https://user-images.githubusercontent.com/36926081/148130275-6c59382c-4d84-48f0-8d75-e53fc95a3e2b.png)

## System information

- OS: [Windows 11]
- Browser (if applies) [Opera GX]
- Version of supabase-js: ^1.28.5
- Version of Node.js: v14.17.5

**Comment by WilliamFalci** [comment]
> @WilliamFalci, I also answered in your discussion. Update RLS checks against both the old record and new record. Your header is the the value you are checking against, but you are changing it. You need to pass the existing hid in the header (which you appear to do) and have the “using” part of the policy check that. You need to have the “with check” part of the policy just set to true or at least not include hid in it as it will not match the header.

![image](https://user-images.githubusercontent.com/36926081/148277875-2de2baee-0a1e-4692-8783-31863b3af0f8.png)
![image](https://user-images.githubusercontent.com/36926081/148277966-ff81f8b2-6176-40f7-9811-fac897860de4.png)


I tried both, not work

**Comment by GaryAustin1** [comment]
I think you also need to set returning to minimal...  It is trying to read the table to send you back updated data, which it can't do since you changed the hid and it now violates the read RLS (select)...
So try update({hid: newHID}, {returning:'minimal'} ).eq('hid',oldHID) in addition to your 2nd RLS example.

**Comment by Yusuf-Munir** [comment]
I have this same issue where SELECT With Using cannot read my custom header:

`
(bucket_id = 'images'::text)
AND (
  EXISTS (
    SELECT
      1
    FROM
      private.group_device_members gdm
    WHERE
      (
        (
          gdm.device_id = (
            (current_setting('request.headers'::text, true))::json ->> 'x-device-id'::text
          )
        )
        AND (
          gdm.group_id = (storage.foldername (objects.name)) [1]
        )
      )
  )
)
`

My INSERT with the exact same code works fine
