### ISSUE TITLE
Client-side exception after leaving window open

### ISSUE THREAD

**Issue by glowdex** [supabase/supabase#4802]
# Bug report

## Describe the bug

After leaving the supabase UI open for a while (not sure how long), I get the message "Application error: a client-side exception has occurred (see the browser console for more information)". I'm on Firefox 95.0.2. 

## To Reproduce

1. Go to https://app.supabase.io/project/[project-id]
2. Leave browser window open

## Expected behavior

No exception

## Screenshots

<img width="1227" alt="Screen Shot 2022-01-04 at 11 14 28 PM" src="https://user-images.githubusercontent.com/72667807/148164799-5ec016f7-0185-4988-b3a9-74b128d3339c.png">

<img width="1248" alt="Screen Shot 2022-01-04 at 11 14 49 PM" src="https://user-images.githubusercontent.com/72667807/148164792-856a700b-0b50-4cbf-842c-e90c3c7a6206.png">

## System information

- OS: macOS
- Browser: Firefox 95.0.2
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by kiwicopple** [comment]
I think this one should be fixed now! 
https://github.com/supabase/supabase/pull/4800

Can you let us know if you're still experiencing this?

**Comment by glowdex** [comment]
Just happened again unfortunately :( left window open and clicked on another page. Got the client side error, but this time it was fixed after I refreshed!

**Comment by kiwicopple** [comment]
> but this time it was fixed after I refreshed!

OK - I will close this for now, but if you see it again feel free to comment and we can dig into it
