### ISSUE TITLE
SSL Certificate Expiry

### ISSUE THREAD

**Issue by phxtho** [supabase/supabase#4807]
# Bug report

## Describe the bug

The SSL certificate for *.supabase.co expired on 30 December 2021 and is causing failures when making requests to PostgREST and GoTrue

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Attempt sign-up
```js
const { user, session, error } = await supabase.auth.signUp({
  email: 'example@email.com',
  password: 'example-password',
})
```
> GoTrue Error: The SSL connection could not be established, see inner exception

## Expected behavior

Successful sign up

## Screenshots

![Screenshot from 2022-01-05 10-38-14](https://user-images.githubusercontent.com/37331563/148198197-1a565b3f-1274-411e-a263-1922d91d5b0a.png)

**Comment by inian** [comment]
Hi @phxtho, can you create a support ticket https://app.supabase.io/support/new with your project reference?
