### ISSUE TITLE
Auth — not able to create custom Confirm Signup message via template 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#4809]
# Bug report

1. Go to /auth/templates
2. Create a custom message in the "Confirm Signup" field
3. Send yourself a signup email
4. Your custom template doesn't match the email you receive 
 
![CleanShot 2022-01-05 at 10 58 53@2x](https://user-images.githubusercontent.com/105593/148234295-aef4eaa9-7a7a-4f4e-981b-0df2c998ae5b.png)

Thanks all!

**Comment by kiwicopple** [comment]
It seems that your settings didnt save to the auth server - could you try updating the template again, saving, then try again?

**Comment by saltcod** [comment]
That worked! Thanks @kiwicopple !
