### ISSUE TITLE
CSS wrapping issue on generated API docs

### ISSUE THREAD

**Issue by zdb999** [supabase/supabase#481]
# Bug report

## Describe the bug

The titles on the API doc sections do not wrap properly, and extend into the code side of the screen.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the API docs on a database.
2. Zoom in, and possibly narrow the browser window if you are using a large monitor.
3. See that the section titles extend over the dividing line and do not wrap.

## Expected behavior

The section titles should wrap if necessary.

## System information

- OS: Ubuntu 20,04
- Browser: Brave (Chromium based)

**Comment by carlosstenzel** [comment]
![Screen Shot 2021-01-05 at 19 59 35](https://user-images.githubusercontent.com/3890516/103709263-ed4c0800-4f90-11eb-8b07-183510bf3c18.png)

solution

![Screen Shot 2021-01-05 at 20 00 12](https://user-images.githubusercontent.com/3890516/103709307-06ed4f80-4f91-11eb-88eb-20354093a628.png)

Move h2 e add background:none in class doc-heading

```
<div class="doc-section">
<article class="text ">
<h2 class="doc-heading" style="background: none;">GraphQL <span class="lowercase">vs</span> Supabase</h2>
  <p>If you have a GraphQL background, you might be wondering if you can fetch your data in a single round-trip. The answer is yes!</p>
....
</article>
</div>
```

**Comment by kiwicopple** [comment]
Fixed! Thanks for reporting @zdb999 , and thanks for the suggestions @carlosstenzel
