### ISSUE TITLE
Allow me to invite users to my team even if they aren't registered with Supabase

### ISSUE THREAD

**Issue by brendanfalk** [supabase/supabase#4814]
# Feature request

## Is your feature request related to a problem? Please describe.

If I want to add someone to my Supabase team, they have to already have an account. If they don't have a supabase account, I get this error message:

<img width="1436" alt="CleanShot 2022-01-05 at 11 08 37@2x" src="https://user-images.githubusercontent.com/4949076/148274612-b110503a-48ab-4173-a968-3f1d17221348.png">

This is annoying because now I have to go to my teammate, ask them to sign up to supabase, give me the email they signed up with, then I have to go back and add them. This is very slow. I just want to be able to invite and then forget about it.

## Describe the solution you'd like

Three potential solutions:
1. You let me invite them even though they don't have a supabase acount
2. You give me a custom invite link that I can share with the teammate(s) that they can use at any time to auto join the team
3. You let me associate a domain name (in our case, fig.io) with our team. This would mean that anyone with a fig.io email gets automatically added to our team upon signing up to supabase.

**Comment by kiwicopple** [comment]
Hey @brendanfalk 👋 

Agreed. I think we should go with `1` as I can see us scattering "invites" to many other parts of the app

**Comment by MildTomato** [comment]
update - we will soon be releasing this feature 😄

**Comment by joshenlim** [comment]
Hey there! We've just released this out - you should now be able to invite team members via their emails :) Feel free to give that a go!

**Comment by jledbet** [comment]
Hi - Is there an event raised, e.g. PASSWORD_RECOVERY, when they are invited? How can we detect that we're in this auth state so they can accept the invite and set a password?
