### ISSUE TITLE
Update latest announcements in navbar

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4817]
# Feature request

## Is your feature request related to a problem? Please describe.

Update latest announcements in navbar.

## Additional context

Good for first time contributors

<img width="1392" alt="Screen Shot 2022-01-05 at 11 09 35 PM" src="https://user-images.githubusercontent.com/70828596/148327069-724be3ff-13cc-4926-9d3e-fc8c12348fcf.png">

**Comment by kiwicopple** [comment]
Nice - maybe we can link to 

- Launch Week 3
- Series A fundraise

?
