### ISSUE TITLE
not working - where uuid

### ISSUE THREAD

**Issue by carlosstenzel** [supabase/supabase#482]
Do not select by id.
Code:

```
select * from auth.users where id = "ID"
```
return

```
Error: Run query failed (column "ID" does not exist)
```

**Comment by soedirgo** [comment]
Hey @carlosstenzel, can you try enclosing ID with single-quotes? Postgres treats the thing in `"` as identifiers (i.e. columns, tables, etc.).

**Comment by carlosstenzel** [comment]
@soedirgo  return = Error: Run query failed (invalid input syntax for type uuid: "ID")

**Comment by soedirgo** [comment]
UUIDs have a [well-defined format](https://www.uuidtools.com/what-is-uuid), so the query fails. Can you tell me what specifically you're trying to do? I might be able to help more directly that way.

**Comment by kiwicopple** [comment]
Hey @carlosstenzel , here is a query which should work:

```
select * 
from auth.users 
where id = 'fffba244-8cf9-4a91-9202-3d103e63f3b4';
```

You will have to use a User ID of an actual user in your database (`select id from auth.users`). Feel free to reopen this if you have any problems!
