### ISSUE TITLE
On the database view `databases/table` one cannot distinguish tables via UI with big screens

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#4829]
# Chore

## Underlying problem description with proposal

On my screen (it's not even that wide) the table view e.g. looks like this with a lot of tables above and below
![image](https://user-images.githubusercontent.com/9058762/148381973-7733c6b9-9435-4a8f-a19c-1c8c1b4cc2ff.png)

From a viewpoint of Accessibility and Usability not only the icon buttons to edit are small but they are also visually not grouped to the name. On top of that there is no visual marker telling me that I am currently hovering the correct table.

My proposal:

Provide a clear contrastful hover on the table rows
+ Move the action buttons to the left such that they are grouped with the name.

**Comment by Hallidayo** [comment]
@saltcod - Can I take this one?

**Comment by w3b6x9** [comment]
@Hallidayo please do!
