### ISSUE TITLE
batch delete

### ISSUE THREAD

**Issue by pryme0** [supabase/supabase#4832]
### Discussed in https://github.com/supabase/supabase/discussions/4831

<div type='discussions-op-text'>

<sup>Originally posted by **pryme0** January  6, 2022</sup>
Is there a way to do batch delete with supbase?
Like i pass in an array containing id's of records i want to delete  and it runs the operation for me</div>

**Comment by kiwicopple** [comment]
definitely:

```js
const { data, error } = await supabase
  .from('cities')
  .delete()
  .in('id', ['1', '2'])
```

**Comment by 24jr** [comment]
I have a join table using multiple fields as a primary id. For simplicity say user_colors. Perhaps I first add 4 user_colors `supabase.from('user_colors').upsert([ {user_id: 'bill', color_id: 'red'},  {user_id: 'bill', color_id: 'green'}, {user_id: 'bill', color_id: 'blue'}])` and I now want to delete the ones with user_id as bill and colors red and green and keep blue

How does this look in that case?

**Comment by steve-chavez** [comment]
@24jr Can you ask that one in a new discussion? https://github.com/supabase/supabase/discussions

**Comment by aiibe** [comment]
With filter `in` aren’t we limited to the size of url params ? When we have lots of items to delete with long string ids, for instance.
