### ISSUE TITLE
Grant CONNECT permission to authenticator, supabase_storage_admin and supabase_auth_admin roles explicitly so it does NOT rely on default permissions of the PUBLIC role

### ISSUE THREAD

**Issue by chipilov** [supabase/supabase#4833]
# Chore

## Describe the chore

In order to tighten the security of a PostgreSQL instance, some suggest to revoke the permissions for the database and 'public' from the PUBLIC role and only grant privileges to specific roles (e.g. see https://wiki.postgresql.org/images/d/d1/Managing_rights_in_postgresql.pdf,  '6.9 Securing the default installation').

However, in the instances provided by Supabase, revoking the permissions from PUBLIC on the database and the 'public' schema breaks the PostgREST flow, because the 'authenticator' role no longer has the right to connect to the database.

It is still possible to simply GRANT CONNECTION permission to authetnicator, but it seems that it would be better if the default Supabase instances did that instead of relying on the permissions of the PUBLIC role. That way, Supabase will work regardless of whether someone tries to revoke the permissions from PUBLIC or not.

**Comment by kiwicopple** [comment]
Thanks for the suggestion

> but it seems that it would be better if the default Supabase instances did that instead of relying on the permissions of the PUBLIC role

i.e. `GRANT CONNECT ON DATABASE postgres TO anon;`

right?

**Comment by kiwicopple** [comment]
btw - thanks for all these issues you're creating. They are very high-quality suggestions

**Comment by chipilov** [comment]
> GRANT CONNECT ON DATABASE postgres TO anon;

Actually, I think it should be this (at least that's what worked for me when I revoked PUBLIC's permission for the DB):

```
GRANT CONNECT ON DATABASE postgres TO authenticator;
```

I assume that the ```anon``` and ```authenticated``` do NOT need explicit permissions to connect to the db, because the connection from PostgREST is actually executed with the ```authenticator``` role and then it just switches to ```anon``` or ```authenticated``` once it's already connected.

**Comment by kiwicopple** [comment]
ah yes - you're 100% correct. Thanks for catching that.

We'll add this to the platform and roll it out across the fleet 👍

**Comment by chipilov** [comment]
It seems that an explicit grant also needs to be given to the ```supabase_auth_admin``` role, otherwise ```signUp```/```singIn``` methods fail - I assume ```supabase_auth_admin``` is used by GoTrue to talk to the db.

**Comment by KevinBrolly** [comment]
This issue is now two years old, and in that time we have made extensive changes to permissions. It is very likely that this issue is now resolved.

I am going to close this issue as stale. If there is reason we should still consider this please reopen with further comments.
