### ISSUE TITLE
Supabase Studio - Delete user from UI not work

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#4841]
# Bug report

## Describe the bug

(Docker Self-Hosted)
Clicking delete user on UI an success toast appear, the datatable delete the proper row, but, at refreshing of the page is always there

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase Studio
2. Click on Delete User
![image](https://user-images.githubusercontent.com/36926081/148452178-88967f5c-7d77-4e7d-8538-1c637a5b9df1.png)
3. Confirm
![image](https://user-images.githubusercontent.com/36926081/148452235-20b33af3-e8c0-429b-81d1-ff9e52f6707e.png)
4. Refresh

## Screenshots

![image](https://user-images.githubusercontent.com/36926081/148452327-6348711f-5b8d-4185-9067-41ca0aefa95b.png)
![image](https://user-images.githubusercontent.com/36926081/148452357-fa6d023e-97d0-4e14-940f-02dffd368f2e.png)

## System information

- OS: [Windows 11]
- Browser (if applies) [Opera GX]
- Version of supabase-js: ^1.28.5
- Version of Node.js: v14.17.5

**Comment by Johnrobmiller** [comment]
this is still a bug, please reopen

**Comment by gregnr** [comment]
@Johnrobmiller do you mind providing some steps you used that I can try to reproduce?

**Comment by Johnrobmiller** [comment]
> @Johnrobmiller do you mind providing some steps you used that I can try to reproduce?

Sadly, this bug does not reliably reproduce. However, perhaps you could try making a new table and adding maybe 2 rows, then trying to delete them. If it does not replicate, then that is very unfortunate. There might be a race condition that some people are "losing", while others will never "lose" that race. Sorry I cannot help further.
