### ISSUE TITLE
Realtime Row Level Security Requires PostgREST 9 Variable Access Syntax on PG12 and PG13

### ISSUE THREAD

**Issue by w3b6x9** [supabase/supabase#4842]
# Feature request

Currently, Realtime RLS only supports the `authenticated` role and user `id` (`sub`) and `email`.

Soon, Realtime RLS will enable anyone to use any role (e.g. `authenticated`, `anon`) and any field in JWT claims in their RLS policies. However, Realtime RLS is only compatible with PostgREST 9's syntax of accessing variables in JWT.

If you have a project using PostgreSQL 12 or PostgreSQL 13 and you're currently accessing PostgREST variables like this:

```sql
current_setting('request.jwt.claim.email', true)
```

then you will have to update to something like this:

```sql
coalesce(
  current_setting('request.jwt.claim.email', true),
  (current_setting('request.jwt.claims', true)::jsonb ->> 'email')
)
```

Essentially, Realtime RLS requires accessing `request.jwt.claims`, casting to `json`, and using JSON operators to fetch the data you want.

This will ensure that your project continues to function properly with both PostgREST and Realtime RLS.

If you're already on a PostgreSQL 14 project then there's nothing you have to do as you're already using the new syntax.

## Additional context

- All Supabase projects were recently upgraded to PostgREST 9 but the config `db-use-legacy-gucs` was set to `true` to ensure that your PostgREST didn't break when using the old syntax (e.g. `current_setting('request.jwt.claim.email', true)`). However, PostgreSQL 14 ignores the `db-use-legacy-gucs` parameter. See https://postgrest.org/en/stable/configuration.html#db-use-legacy-gucs for more information.

- Please refer to [Accessing Request Headers, Cookies and JWT claims](https://postgrest.org/en/stable/api.html#accessing-request-headers-cookies-and-jwt-claims) in PostgREST 9 docs for more information.

**Comment by TomasHubelbauer** [comment]
@w3b6x9 how do I tell what sort of Postgres version is my Supabase project using?

**Comment by olirice** [comment]
> how do I tell what sort of Postgres version is my Supabase project using?

on a sql prompt you can run 
```sql
show server_version
```
to get the postgres major and minor version

**Comment by kachar** [comment]
Just tested the given scenario on PG 13.3 and it looks that if the claims are used via `auth.uid()`, `auth.email()` or `auth.role()` functions then nothing more is expected as they wrap the `current_setting()` accordingly.

https://github.com/supabase/supabase/blob/9777ddea2e1d4ac9f35004a7ab83f4868cd92cd5/docker/volumes/db/init/01-auth-schema.sql#L92-L123

Thanks for the update on this topic.
