### ISSUE TITLE
Supabase Storage Error: 'column buckets.public does not exist'

### ISSUE THREAD

**Issue by sreekeshiyer** [supabase/supabase#4850]
# Bug report

## Describe the bug

When I click on _Storage_ in Supabase Dashboard i.e. get to the /storage/buckets route, I get a prompt on the top right that says `column buckets.public does not exist`.

When I try to create a bucket using the UI, I get a similar error.

With some help thanks to ktosiek#7697 in the Supabase Discord Server, I checked the **Storage** Schema in the Table Editor and found out that there was no public column.

## To Reproduce

I'm not sure how to 'reproduce' this bug since I have other Supabase projects which work perfectly fine, but here are some specifics about this particular project - 

- I have Users set up in my Auth.
- I have a normal Postgres Function attached to a Trigger which creates a Profiles table on every user sign up.
- I have a messages table with real-time enabled.

PS: I have not tampered with anything in the Storage Schema.

## Expected behaviour

I wanted to create a new Storage Bucket.

## Screenshots

![image](https://user-images.githubusercontent.com/67017933/148524751-a8ca4ffe-8234-4cf6-8ce6-10e1213f0887.png)
When I open up the Storage Page

![image](https://user-images.githubusercontent.com/67017933/148523793-638c227e-bfd9-4455-bda4-f6804ced24d5.png)
When I try to create a bucket

![image](https://user-images.githubusercontent.com/67017933/148525006-3f4a7d38-5157-409b-b7cd-82f03cfd9b9e.png)
Storage Schema, Table Buckets

## System information

- OS: Windows
- Brave Browser
- Version of supabase-js: Latest

Thank you :)

**Comment by awalias** [comment]
hey @sreekeshiyer thanks for the detailed write up, can you please submit a support ticket at https://app.supabase.io/support/new and reference this issue - this one seems specific to your project

can you also put in the ticket some info about whether your project was ever paused/restored?

will close in favor of support ticket 👍

**Comment by yaojiach** [comment]
I'm seeing the same issue in my project. Will submit a support ticket but wondering if this could be a common issue.

**Comment by Metaphysics0** [comment]
Same issue here
