### ISSUE TITLE
Supabase web app crashes (on related entry modal open)

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#4859]
# Bug report

## Describe the bug

Supabase web client crashes when trying to open a related table entry modal.

## To Reproduce

1. Open `subscriptions` table
2. Click on one of the related user IDs (referencing `user_details` table): ![image](https://user-images.githubusercontent.com/725324/148557462-ef61691b-1070-49d0-b6b0-581aab009b48.png)
3. A modal tries to open for a split second: 
![image](https://user-images.githubusercontent.com/725324/148557611-60b038d1-e751-465b-bd98-46d15d677aa2.png)
4. Who Supabase web client crashes: 
![image](https://user-images.githubusercontent.com/725324/148557662-7a4bc06e-b237-4d9a-8243-c7f7faad3ba2.png)

## System information

- OS: macOS
- Browser: Brave (chromium)

**Comment by edgarasben** [comment]
Also reported this via email support. This is being worked on right now.

**Comment by joshenlim** [comment]
Duplicate issue: https://github.com/supabase/supabase/issues/4531
This should now be fixed :) but please do feel free to reopen if its still happening! 🙏
