### ISSUE TITLE
Create functions that returns an array

### ISSUE THREAD

**Issue by yustarandomname** [supabase/supabase#4865]
# Feature request

## Is your feature request related to a problem? Please describe.

Today I was trying to write a postgres function with the supabase function editor, but discovered that it is currently not possible to return an array.

## Describe the solution you'd like

Add a toggle button labeled something like: `is array`. 
Like the toggle button for creating a new column in the table editor:
<img width="649" alt="Screenshot 2022-01-07 at 18 41 54" src="https://user-images.githubusercontent.com/25432790/148584519-69706e16-5527-4af7-b9eb-d006d39ab253.png">

## Additional context

This is the current dropdown of return types:
<img width="640" alt="Screenshot 2022-01-07 at 18 38 33" src="https://user-images.githubusercontent.com/25432790/148584682-812661b3-272e-4fa6-b808-a3761192d0a9.png">

**Comment by vinyll** [comment]
Is this somehow related to #4248?

**Comment by prajzwol7** [comment]
@kiwicopple function section is not available in development version.

**Comment by kiwicopple** [comment]
> that it is currently not possible to return an array

I assume that you would like to return a set of rows right @vinyll ?

This is definitely possible! https://supabase.com/docs/guides/database/functions#returning-data-sets

Did you try this one yet?

Take note that in Postgres the "array type" is different from returning a "set of rows". If you call the database function using the RPC supabase-js: https://supabase.com/docs/reference/javascript/rpc

> Is this somehow related to https://github.com/supabase/supabase/issues/4248?

This could be the case - for now you will need to use the SQL editor to write your Postgres function

**Comment by kiwicopple** [comment]
I'll close this one for now, but feel free to comment here if it's still an issue and we can re-open

**Comment by nyeu** [comment]
reopening this as it's still not possible to return an array of objects through the frontend. I managed to made it before and my return type was `SETOF place` but now it's not possible anymore. Any idea? 
The function is made with SQL rather than `plpgsql`
