### ISSUE TITLE
Cross error when update Data  

### ISSUE THREAD

**Issue by nitinr010** [supabase/supabase#4870]
Cross error when update Data  

when we want to update data in supabase then we facing cross error

![image](https://user-images.githubusercontent.com/93132632/148631120-0b3980f4-89d1-4d74-a0f3-7ecd2c047a46.png)

**Comment by joshenlim** [comment]
this may have been a one off thing so I'm gonna go ahead to close this ticket - but please do feel free to reopen if you're still running / do run into this issue again! 🙏
