### ISSUE TITLE
Defining a Function in SQL view and executing it leads to empty result (plv8 language)

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#4873]
# Bug report

## Describe the bug

When you use the SQL Editor View and define a function via `create or replace...` to test if a function works properly and then immediately execute the function via SELECT it will say "no rows returned" although this might be completely false. Probably it is somehow only taking the result of the first statement (function definition).

Note: I am using plv8 language (pgsql extension) but I am pretty sure it works with all languages like this since it doesn't look like a language-related problem.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the SQL Editor
2. Type in something like ():
```
create or replace function foobar() 
returns smallint as $$

    var rows = plv8.execute(
        'SELECT COUNT(id) as c FROM whatever_table'
    );

    return rows[0].c;
$$ language plv8;

SELECT foobar()
```
3. Click `RUN` to execute the sql

## Expected behavior

It should return the row with the count

## Actual Behaviour

Returns no rows.

**Comment by burmecia** [comment]
I think that's multi-statement queries, pg-meta hasn't supported it yet, but there is already an issue about it https://github.com/supabase/postgres-meta/issues/143

**Comment by activenode** [comment]
Hey @burmecia . I'd rather close the related issue or rephrase it. Normally an issue should contain proper description which supabase/postgres-meta#143 does not. But yeah, probably related.

**Comment by burmecia** [comment]
This issue has been fixed. For example, run below SQL in SQL Editor,

```sql
create or replace function foobar() 
returns smallint as $$

    var rows = plv8.execute(
        'SELECT 42 as c'
    );

    return rows[0].c;
$$ language plv8;

SELECT foobar()
```

Got result:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/19306324/213951696-8ed73714-b751-4105-9094-1e93be557a14.png">

**Comment by activenode** [comment]
Works.
