### ISSUE TITLE
Permissions denied for table using API but works with SupabaseClient

### ISSUE THREAD

**Issue by jperestrelo** [supabase/supabase#4883]
# Bug report

## Describe the bug

When trying to access data from some API endpoints, like this: /rest/v1/leads?select=* I get this error:
```
{
    "message": "permission denied for table leads",
    "code": "42501",
    "hint": null,
    "details": null
}
```

when doing the same using JS client like this:
```
const { data, error } = await supabase
            .from('leads')
            .select()

```
I successfully get the data. **Although enabling or disabling RLS has no impact.**

I'm using the same anon API key in both situations.

## To Reproduce

I am creating these tables using the following function:

```
BEGIN
EXECUTE format('
      CREATE TABLE IF NOT EXISTS %I (
       id serial PRIMARY KEY,
       created_at date default current_timestamp
      )', my_table);

EXECUTE format('
      ALTER TABLE %I ENABLE ROW LEVEL SECURITY;
', my_table);    

END
```

I tried to enable and disable RLS from UI and from SQL editor but didn't change anything.
I also tried to use the service role KEY when using API, but the same error above showed.

When creating the tables from the UI, everything seems to work as intended.

## Expected behavior

I was expecting to be able to create tables programmatically from the client-side so I'm trying to do it using functions.
I'm using the function like this:
```
 const { data, error } = await supabase
            .rpc('create_table', { my_table: table_name })
```

Am I missing something?

**Comment by jperestrelo** [comment]
**Update**
I think I understand what's going on... when creating from the admin UI it creates a set of privileges on the table. While my function is not doing it.

So I'm guessing that there is a lot going on under the hood when creating a table from the UI. There is any recommended way that I can create a table using functions and maintain the same functionalities as if it was being created in the UI?

Thanks

**Comment by stephanbogner** [comment]
**I am not sure if my issue is related:**
Even if I disable RLS I can't update a row on a certain table. On other tables it works perfectly.

**I am using:**
```
const { data, error } = await supabase
  .from(tableName)
  .update(newRowData)
  .eq(columnName, columnValueAtRow)
  
  if (error) {
      console.error(error);
  }
  return { data, error }
```

**I always get:**
`{message: 'permission denied for table http_request_queue', code: '42501', hint: null, details: null}`

**The weird thing is:**
I am pretty sure it worked before the holidays. In the meantime my instance got paused due to inactivity, but not sure if that causes the issue.

Before I was using `1.2.1` but with `1.29.1` it's the same result.

**Comment by stephanbogner** [comment]
**Ok ... very weird. I even get this error if I try to edit the data in the UI:**

<img width="740" alt="Screenshot 2022-01-11 at 16 14 35" src="https://user-images.githubusercontent.com/7897006/148969239-4bf0ea69-6366-4fb6-8874-8c891a7d28d5.png">

<img width="700" alt="Screenshot 2022-01-11 at 16 13 32" src="https://user-images.githubusercontent.com/7897006/148969130-e5c9296e-b789-45e4-a5ae-8c9c8e6f3942.png">

**Comment by tilmann** [comment]
I ran in the same error. (permission denied for table http_request_queue)

**My finding**: It seems to be connected with the functions hooks ALPHA. After removing the hooks for the table that throws the error an insert was possible again.

Adding the hook again leads to the same error.

My instance was paused due to the holidays as well. 

Any ideas except setting up a new instance?

**Comment by dragarcia** [comment]
Hi guys 👋 

If you guys haven't, would you mind sending over a ticket specifying the affected project over at https://app.supabase.io/support/new, and we'll take a closer look at each one from there.

Thanks!

**Comment by stephanbogner** [comment]
> I ran in the same error. (permission denied for table http_request_queue)
> 
> **My finding**: It seems to be connected with the functions hooks ALPHA. After removing the hooks for the table that throws the error an insert was possible again.
> 
> Adding the hook again leads to the same error.
> 
> My instance was paused due to the holidays as well.
> 
> Any ideas except setting up a new instance?

Ahhh! Why didn't I think of that?! **I can confirm the behaviour:**
If I delete the function hook (which is a post-request on insert and update) then I can edit values in the table again. But if I re-add the hook it won't work. Exactly as @tilmann described.

**Comment by supabase-automated-user** [comment]
Hey folks-as a quick update: we've isolated the cause of the issue as an unfortunate interaction between the pause/restore and the mechanism used to enable function hooks via pg_net. We'll be working on both fixing this for the future, and posting a retroactive fix that you will be able to apply to your projects.

**Comment by supabase-automated-user** [comment]
Hey folks-as a quick update: we've isolated the cause of the issue as an unfortunate interaction between the pause/restore and the mechanism used to enable function hooks via pg_net. We'll be working on both fixing this for the future, and posting a retroactive fix that you will be able to apply to your projects.

**Comment by darora** [comment]
Hey folks-as a quick update: we've isolated the cause of the issue as an unfortunate interaction between the pause/restore and the mechanism used to enable function hooks via pg_net. We'll be working on both fixing this for the future, and posting a retroactive fix that you will be able to apply to your projects.

**Comment by stephanbogner** [comment]
@darora 
Thanks for the update and your investigation! 👍

**Comment by w3b6x9** [comment]
hello everyone!

> posting a retroactive fix that you will be able to apply to your projects

if you're currently blocked please run the following in your Supabase SQL editor:

```sql
GRANT USAGE ON SCHEMA net TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;

ALTER function net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;
ALTER function net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;
ALTER function net.http_collect_response(request_id bigint, async boolean) SECURITY DEFINER;

REVOKE ALL ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION net.http_collect_response(request_id bigint, async boolean) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
GRANT EXECUTE ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
GRANT EXECUTE ON FUNCTION net.http_collect_response(request_id bigint, async boolean) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
```

**Comment by tilmann** [comment]
🙏 Thanks. That solved the problem for me!

**Comment by stephanbogner** [comment]
Looks good on my end too 🎉 
Thanks ❤️

**Comment by jdahdah** [comment]
@w3b6x9 Thank you, this solved the issue for me. FYI this happened somewhere along following the lessons in your [Egghead course](https://egghead.io/courses/build-a-saas-product-with-next-js-supabase-and-stripe-61f2bc20). In lesson 24 I decided to delete the test user and signing up again was no longer possible. But my project has been paused twice since I started the course so I guess it's more related to that than something instructed in the course?

**Comment by dstroot** [comment]
1. @[w3b6x9](https://github.com/w3b6x9) your fix works! Kudos.
2. This definitely happens after your project is paused (and you have hooks in place I think)

**Comment by w3b6x9** [comment]
> @w3b6x9 Thank you, this solved the issue for me. FYI this happened somewhere along following the lessons in your [Egghead course](https://egghead.io/courses/build-a-saas-product-with-next-js-supabase-and-stripe-61f2bc20). In lesson 24 I decided to delete the test user and signing up again was no longer possible. But my project has been paused once since I started the course so I guess it's more related to that than something instructed in the course?

@jdahdah Sorry, completely missed your comment. I'll have the team look into this and report back here1

**Comment by jwright04** [comment]
The comment left by @w3b6x9 solved the issue for me although I still see errors when logging in/out specifically
`TypeError: destroy is not a function`.  If I refresh the page and login again, i still see the error, but i'm redirect back to my success page.  It's worth noting this is happening on my localhost, I haven't tried deploying yet.

**Comment by GaryAustin1** [comment]
@oalbacha If you are creating users again, then you are on to some other issues in your code/setup.  Probably best to ask in Discord or Github/discussions here with details.

**Comment by julandev** [comment]
> hello everyone!
> 
> > posting a retroactive fix that you will be able to apply to your projects
> 
> if you're currently blocked please run the following in your Supabase SQL editor:
> 
> ```sql
> GRANT USAGE ON SCHEMA net TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
> 
> ALTER function net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;
> ALTER function net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) SECURITY DEFINER;
> ALTER function net.http_collect_response(request_id bigint, async boolean) SECURITY DEFINER;
> 
> REVOKE ALL ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;
> REVOKE ALL ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) FROM PUBLIC;
> REVOKE ALL ON FUNCTION net.http_collect_response(request_id bigint, async boolean) FROM PUBLIC;
> 
> GRANT EXECUTE ON FUNCTION net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
> GRANT EXECUTE ON FUNCTION net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
> GRANT EXECUTE ON FUNCTION net.http_collect_response(request_id bigint, async boolean) TO supabase_functions_admin, postgres, anon, authenticated, service_role, dashboard_user;
> ```

I ran this code in the editor and since then, I have been unable to create new users. Also, I keep getting a type error: destroy is not a function. 

As I do not know how to rollback the code , I deleted my projects and organizations and created new ones hoping it would make a difference. It didnt.

Then I created a new supabase account and I am still getting the errors. Is there any other thing I can do?

**Comment by rrakso** [comment]
Every time I try to make a request `POST 'https://<id>.supabase.co/rest/v1/<table_name>'` I get `permission denied for table <table_name>` (the state of the _RLS_ doesn't matter, always the same result...), but **once I created a whole new project, then I was able to create new records**.

Does anyone know what could be the cause of this strange behavior?

---

PS
The problem persists even when I create the new table using UI (website) (the rest of the tables are created using SQL queries).

**Comment by Maikpwwq** [comment]
This help me solve that error, In my supabase table config I visit `View Policies`
![Captura desde 2023-08-25 01-34-43](https://github.com/supabase/supabase/assets/34326347/ca9cfb69-9b20-42fc-b76d-634e4287c35f)
Then I added two instances of `New Policy`, for the `Select` and `Insert` methods respectively
![Captura desde 2023-08-25 01-35-40](https://github.com/supabase/supabase/assets/34326347/24996829-395f-4707-8fda-62fdd5cdd0c4)

**Comment by prithvi2k2** [comment]
> This help me solve that error, In my supabase table config I visit `View Policies` ![Captura desde 2023-08-25 01-34-43](https://user-images.githubusercontent.com/34326347/263187333-ca9cfb69-9b20-42fc-b76d-634e4287c35f.png) Then I added two instances of `New Policy`, for the `Select` and `Insert` methods respectively ![Captura desde 2023-08-25 01-35-40](https://user-images.githubusercontent.com/34326347/263187338-24996829-395f-4707-8fda-62fdd5cdd0c4.png)

Is this secure - what does give access to public exactly mean, like anyone without supabase keys/urls can access the db?

**Comment by johnsimeroth** [comment]
> #### lastEDIT
> I found it! The cause of my problem... Maybe someone will find my "discovery" as useful. So while developing, **I cleared the Postgres with SQL query from this [response](https://stackoverflow.com/a/61221726/)**, and then I filled "public schema" with proper data - so everything was working EXCEPT the JS library and REST requests. So with "fresh" project REST/client are working fine! After dropping all the data 😐 it breaks - and if I want to fix it back, then (I think) the only solution is to create a new project.
> 
> SQL query used to drop all :)
> ```sql
> DROP SCHEMA public CASCADE;
> CREATE SCHEMA public;
> 
> GRANT ALL ON SCHEMA public TO postgres;
> GRANT ALL ON SCHEMA public TO public;
> ```

This was it for me as well. Thank you for sharing. New project solved it. Would love to know if there's an alternative that doesn't require a new project in the future!

**Comment by nahtnam** [comment]
The SQL queries in this thread did not help, but turning the `pg_net` extension off and on fixed it for me

**Comment by HanLok420** [comment]
> The SQL queries in this thread did not help, but turning the `pg_net` extension off and on fixed it for me

How did you do this?

**Comment by nahtnam** [comment]
> > The SQL queries in this thread did not help, but turning the `pg_net` extension off and on fixed it for me
> 
> How did you do this?

In the left menu bar, go to database, then extensions, then look for `pg_net`

**Comment by HanLok420** [comment]
Thank you, that did not work for me either. :(
The support is on it hopefully they find a way to solve it soon. I'll let you know.

**Comment by HanLok420** [comment]
> > > The SQL queries in this thread did not help, but turning the `pg_net` extension off and on fixed it for me
> > 
> > 
> > How did you do this?
> 
> In the left menu bar, go to database, then extensions, then look for `pg_net`

Thank you, that did not work for me either. :(
The support is on it hopefully they find a way to solve it soon. I'll let you know.

**Comment by emileond** [comment]
> The SQL queries in this thread did not help, but turning the `pg_net` extension off and on fixed it for me

Thanks, this worked for me. I got the issue after upgrading postgresql version from the admin UI.

**Comment by stanifert** [comment]
> Just got this after updating from 15.1.1.9 to 15.1.1.13 via the Admin UI. Disabling and reenabling the pg_net solved it.

Ditto!

**Comment by caipicoder** [comment]
same here:

> got this after updating via the Admin UI. 
> Disabling and reenabling the pg_net solved it

Thanks a lot @nahtnam !

**Comment by james-carlson** [comment]
I had this same error, but I didn't have pg_net enabled on my project. My workaround was to duplicate the table, point to the new one, and then delete the old and rename the duplicate. Seems to have worked out so far.

**Comment by EricStrohmaier** [comment]
> Just got this after updating from 15.1.1.9 to 15.1.1.13 via the Admin UI. Disabling and reenabling the pg_net solved it.

how did you update the version via Admin Ui?? cant find that option

**Comment by GaryAustin1** [comment]
@EricStrohmaier Go to the infrastructure tab in settings.

**Comment by 5Heinzelmann** [comment]
turning the pg_net extension off and on wont fix it for me. i dont even need the pg_net extension in my setup. also the queries did not help. i'm waiting for support.

**Comment by alexlixuin** [comment]
anyone fixed the issue?

  code: '42501',
  details: null,
  hint: null,
  message: 'permission denied for table users'

**Comment by fabianosafe** [comment]
> anyone fixed the issue?
> 
> code: '42501', details: null, hint: null, message: 'permission denied for table users'

GRANT SELECT ON TABLE public.name_table TO public;

**Comment by aheruz** [comment]
I'm gonna left the official [Troubleshooting Guide](https://supabase.com/docs/guides/troubleshooting) here ; )

If you're currently blocked by the above error, run the following in your Supabase SQL editor:

Check `select * from net.http_request_queue` and make sure it's empty.
Try `drop extension pg_net; create extension pg_net schema extensions;`
If that doesn't work (e.g. because some objects depend on it), then [contact support](https://supabase.com/support).

**Comment by raphox** [comment]
I had this problem creating an [application-level testing](https://supabase.com/docs/guides/local-development/testing/overview#application-level-testing) using the environment 'happy-dom' in my Vitest settings (https://vitest.dev/guide/environment).

I believe the problem relates to the `fetch` method that [@supabase-js](https://github.com/supabase/supabase-js/tree/master) uses to consume the API. In the 'node' environment, it passes the `Authorization` header correctly, but in the 'happy-dom' environment, it omits the `Authorization` header.

You have two options:

1. Change your global environment:

```diff
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  server: {
    port: 3000,
  },
  test: {
--    environment: 'happy-dom',
++    environment: 'node',
    globals: true,
...
```

2. Override the environment in your file:

```diff
++ // @vitest-environment node

import { createClient } from '@supabase/supabase-js';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
...
```
