### ISSUE TITLE
Supabase dashboard UI does not notice being logged out

### ISSUE THREAD

**Issue by wiesson** [supabase/supabase#4888]
# Bug report

## Describe the bug

It looks like that the dashboard UI is not aware if an access token has been expired. It happens multiple times a day to me that the token expires and I only notice it because the links aren't working and the page is not responsible. 

I also asked in the supabase Discord and it looks like other people have this issue as well.

## To Reproduce

1. Create a new project
2. Wait 1-2 hours, but keep the tab open
3. Come back to the tab and try to continue working

## Expected behavior

Token will be refreshed if possible, otherwise show the login screen immediately

## System information

- OS: macOS
- Browser (if applies) - latest chrome
- Version of supabase-js: - current hosted version

**Comment by jjromary** [comment]
Can I take over this issue?

**Comment by jjromary** [comment]
I followed the steps and the same doesn't happen to me... @wiesson  Do you know if this implementation was done?

**Comment by wiesson** [comment]
I haven't followed this topic. Maybe it was fixed

**Comment by kiwicopple** [comment]
we made a few changes to our Auth - this should be fixed now!
