### ISSUE TITLE
Database Functions: plv8 Language is missing when creating Function in UI

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#4892]
# Bug report

When going to Database -> Add a new Function (https://app.supabase.io/project/YOUR_PROJECT/database/functions) then you can select between the languages `[sql, pgsql]`. However if there are other languages isntalled via Extension such as `plv8` they are not listed.

![image](https://user-images.githubusercontent.com/9058762/148689558-78a9622c-ba18-4b4e-a16b-944bfb8dea2f.png)

**Comment by kiwicopple** [comment]
Adding this to the "Contributors" board if anyone wants to help. Ideally plv8 should only show up if it's enabled (or we can have a dropdown where it is "greyed out" when plv8 is disabled)

**Comment by FatumaA** [comment]
Can I try this one @kiwicopple if no one is on it already?

**Comment by kiwicopple** [comment]
go for it @FatumaA ! Nice to see you in our repos
