### ISSUE TITLE
Allow to regenerate secrets

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#4893]
# Feature request

## The Problem: Security

Security is a crucial point for Supabase to become an industry leading Firebase alternative. Now without the possibility to regenerate secrets Supabase can be considered partially _unsafe_ .

Reason: There is many use-cases but a simple one would be accidentally clicking on the reveal button e.g. in a Video Tutorial or whatever and suddenly your secret is revealed without the possibility to do anything against potential attacks.

## Describe the solution you'd like

A simple button to regenerate secrets.

**Comment by kiwicopple** [comment]
Coming soon!

**Comment by burmecia** [comment]
This feature has been implemented, please find it in 'Settings' -> 'API' -> 'Generate a new secret'.

**Comment by burmecia** [comment]
Yes, you can open a new ticket about it.
