### ISSUE TITLE
Realtime DELETE updates not being fired

### ISSUE THREAD

**Issue by rotemrevivo91** [supabase/supabase#4905]
# Bug report

## Describe the bug

listening to DELETE events:
```js
const bp = await this.$supabase
  .from("blogPosts")
  .on("DELETE", (payload) => {
    console.log(payload)
  })
  .subscribe()
```
Deleting a row in the 'blogPosts' table (manually from the Supabase Studio) doesn't fire a DELETE event in the frontend.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a DELETE listener for a table
2. Go to the Supabase Studio
3. Delete a row from the table
4. No DELETE event is fired as expected

## Expected behavior

A DELETE event is fired and is shown in the console (console.log)

## System information

- OS: macOs
- Browser: chrome
- Version of supabase-js: 1.29.1
- Version of Node.js: 16.13.0

## Additional context

* Running locally (docker self-hosted)
* Listening to other events (UPDATE, INSERT) work as expected

**Comment by w3b6x9** [comment]
@rotemrevivo91 did you add the table to your Database Replication in Supabase Studio?

**Comment by rotemrevivo91** [comment]
@w3b6x9 Yes, and all operations are enabled as well. 

Also, when listening to all events:
```js
const bp = await this.$supabase
  .from("blogPosts")
  .on("*", (payload) => {
    console.log(payload)
  })
  .subscribe()
```
The same is happening.
I still didn't try to INSERT/DELETE from a table programmatically (using supabase-js) but I will test that soon.

**Comment by rotemrevivo91** [comment]
https://user-images.githubusercontent.com/25552777/148919196-3409a76e-efe4-4c92-a099-3ed0161b2ee9.mov

A short screen capture of what's happening.

**Comment by w3b6x9** [comment]
@rotemrevivo91 this is most likely specific to your project. Can you please email support@supabase.io with your Supabase project ref? I can investigate.

**Comment by rotemrevivo91** [comment]
Hi @w3b6x9 i'm running a local docker test deployment. I can try and re-build the image and test it again. Or is there a way you could still help me with a local deployment? Thanks!

**Comment by kiwicopple** [comment]
> running a local docker test deployment

hey @rotemrevivo91 - is this code public? That would be very helpful for us so that we can help you to debug it

**Comment by w3b6x9** [comment]
@rotemrevivo91 

> i'm running a local docker test deployment

I see. Like @kiwicopple mentioned, please share your code if it's public. Can you please share your configuration variables for your local docker deployment?

**Comment by rotemrevivo91** [comment]
I can create a codesandbox project of my frontend tomorrow (I'm on EU time). But, basically it's just a fresh install of Nuxtjs.
For my docker deployment, i just pulled the repository (it's up-to-date) and changed the default port of the studio and the default postgres password:

```yml
# Secrets 
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION

POSTGRES_PASSWORD=MYPOSTGRESQLPASSWORD
JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
ANON_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyNzIwODU0MCwiZXhwIjoxOTc0MzYzNzQwfQ.zcaQfHd3VA7XgJmdGfmV86OLVJT9s2MTmSy-e69BpUY
SERVICE_ROLE_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjI3MjA4NTQwLCJleHAiOjE5NzQzNjM3NDB9.pkT3PNpO4DtO45Ac5HK_TKCx8sGLgNtV__pr_ZrRSAU

# Auth

## General
SITE_URL=http://localhost:8888
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false

## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender

## Phone auth
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

# Ports

## Studio port
STUDIO_PORT=8888

## API endpoint ports
KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443

## DB port
POSTGRES_PORT=5432
```

Thanks a lot for the help @w3b6x9  @kiwicopple

**Comment by inian** [comment]
Can you set your table replica identity to full as mentioned [here](https://supabase.com/docs/guides/database#realtime) @rotemrevivo91?

**Comment by w3b6x9** [comment]
@rotemrevivo91 hmm, everything looks good so this is an odd one. might be related to https://github.com/supabase/realtime/issues/213 in some way. since you're running it locally can you try the latest realtime image: `supabase/realtime:v0.20.2`. we might have fixed the issue already.

**Comment by rotemrevivo91** [comment]
I can confirm that after i re-cloned the repo today the issue was gone and i could listen to DELETE events today.
realtime image version: `image: supabase/realtime:v0.19.3`.

@w3b6x9 i'm not really sure why the issue is solved but i guess that you guys fixed it behind the scenes. Although, it might just have been a weird bug on my end and i just needed to start from fresh again). Anyways, thanks a lot to everyone who pitched in and helped!

The issue can be closed, unless you guys wants to further investigate what was going on.

**Comment by chipseater** [comment]
Hey, I am having the same issue, and I posted it on stackoverflow before seeing this issue [(my stackoverflow post)](https://stackoverflow.com/questions/72327433/supabase-realtime-subscription-are-working-for-every-event-type-but-for-delete).
Can you reopen the issue please ?

**Comment by chipseater** [comment]
Hi, I had the same issue with DELETE events not being fired and I fixed it with the SQL query : `ALTER TABLE your_table REPLICA IDENTITY FULL`. I hope it helps !

**Comment by w3b6x9** [comment]
@chipseater just wanted to confirm: did you have a primary key on your table prior to setting replica identity to full?

**Comment by spencercap** [comment]
> Hi, I had the same issue with DELETE events not being fired and I fixed it with the SQL query : `ALTER TABLE your_table REPLICA IDENTITY FULL`. I hope it helps !

amazing 👏

**Comment by w3b6x9** [comment]
Just want to reiterate these important notes:

- Row level security is not applied to delete statements
- The key/value pairs displayed in the old_record field include the table's identity columns for the record being updated/deleted. To display all values in old_record set the replica identity for the table to full
- When a delete occurs, the contents of old_record will be broadcast to all subscribers to that table so ensure that each table's replica identity only contains information that is safe to expose publicly

Source: https://github.com/supabase/walrus/blob/11cac967615be9122479c1f6bbad2a6225d83710/README.md

**Comment by clajps0n** [comment]
> Hi, I had the same issue with DELETE events not being fired and I fixed it with the SQL query : `ALTER TABLE your_table REPLICA IDENTITY FULL`. I hope it helps !

I love you!

**Comment by Monu18765** [comment]
Hello @kiwicopple  and @w3b6x9, I am facing the same issue. I am receiving events for `UPDATE` and `INSERT` but not receiving events for `DELETE`. Earlier, it used to work, but suddenly, DELETE eventType stopped working for real-time listeners.

https://github.com/user-attachments/assets/1fe3a7e6-e02a-4781-a77a-74de47ba5b2f

My Event Listener Code-
```
useEffect(() => {
  const cards = supabase
    .channel('card-all-channel')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'cards',
        filter: `board_id=eq.${params.id}`
      },
      (payload) => {
        console.log('Card Change received!', payload)
        if (payload.eventType === 'UPDATE') {
          setCards((prevData) => {
            const newData: CardRow[] = []
            prevData.forEach((list) => {
              if (list.id === payload.new.id) {
                newData.push(payload.new as CardRow)
              } else {
                newData.push(list)
              }
            })
            return newData
          })
        } else if (payload.eventType === 'INSERT') {
          setCards((prevData) => {
            return [...prevData, payload.new as CardRow]
          })
        } else if (payload.eventType === 'DELETE') {
          setCards((prevData) => {
            const newData = prevData.filter(
              (list) => list.id !== payload.old.id
            )
            return newData
          })
        }
      }
    )
    .subscribe()

  return () => {
    cards
      .unsubscribe()
      .then((message) =>
        console.log(`${message} - Card realtime listener removed.`)
      )
  }
}, [])
```

**Comment by rogaha** [comment]
Having issues with my notifications  as well. I'm only receiving `DELETE` events.

**Comment by Akash187** [comment]
Supabase realtime has a pitfall. "Delete events are not filterable". 
Check the docs link - [Delete events are not filterable](https://supabase.com/docs/guides/realtime/postgres-changes#delete-events-are-not-filterable)
