### ISSUE TITLE
Add psql command to connection strings section in database settings

### ISSUE THREAD

**Issue by nkotlyarov** [supabase/supabase#4910]
We show Postgres URI as "PSQL connection string".
It is possible to connect from psql using URI, but:

1. This psql connection option is not documented so many users may not know about it.
2. It makes a password visible when you paste it.
3. It does not work for some passwords (I have just accidentally discovered that).

I would like to have a copiable psql command like the following:

`psql -h db.[PROJECT_REF].supabase.co -p 5432 -d postgres -U postgres`

So we may consider adding separate sections with PSQL command and URI like the following:
```
psql:
    psql -h db.{PROJECT_REF}.supabase.co -p 5432 -d postgres -U postgres
URI:
    postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT_REF].supabase.co:5432/postgres
Golang:
    ...
JDBC:
    ...
...
```

Database settings page:
https://app.supabase.io/project/[PROJECT_REF]/settings/database

**Comment by kiwicopple** [comment]
👍 

to be added as a new tab in this section

![image](https://user-images.githubusercontent.com/10214025/148788191-8dd74407-d61e-4e9c-b434-e11eb5edd1d4.png)

**Comment by imskr** [comment]
Can I take this up @kiwicopple ?

**Comment by kiwicopple** [comment]
yes please @imskr !

**Comment by imskr** [comment]
I can't see `Settings` here when running studio `http://localhost:8082/project/default` inside default project @kiwicopple 

![Screenshot_20220119_171046](https://user-images.githubusercontent.com/42062622/150123178-861a7345-aec6-40d7-9ca0-7820bd424774.png)

**Comment by imskr** [comment]
@kiwicopple I am not able to run this locally to check. Can you help me or point me to some steps?

**Comment by Isaiah-Hamilton** [comment]
@imskr you have to type the link manually to get to the settings page that you want for local development.
[Link for general settings](http://localhost:8082/project/default/settings/general).

**Comment by imskr** [comment]
Thanks @Isaiah-Hamilton

**Comment by imskr** [comment]
@Isaiah-Hamilton when I go to `http://localhost:8082/project/default/settings/general` it's redirecting me to `http://localhost:8082/project/default`

**Comment by Isaiah-Hamilton** [comment]
That's weird, usually works. maybe @Ziinc or @kiwicopple would know how to get you to the page that you are looking for.

**Comment by imskr** [comment]
Thanks @Ziinc

**Comment by georgekrax** [comment]
I tried to connect with `psql` with 2 ways, but I hadn't any success with it.
```bash
psql -h https://tqdeafmbufukbtgqwqan.supabase.co -p 5432 postgres -U postgres
```
or
```
psql postgres://postgres:[MY_PASSWORD]@db.tqdeafmbufukbtgqwqan.supabase.co:5432/postgres
```

*My password doesn't contain any special characters*

When either of these commands I wait for some minutes, and then the process is terminated saying it couldn't connect to the database.
