### ISSUE TITLE
update custom schema docs with permissions SQL

### ISSUE THREAD

**Issue by soedirgo** [supabase/supabase#4916]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/initializing#api-schemas

## Describe the problem

Currently we have a section for querying custom schemas, but we also need the proper permissions set up so that PostgREST can access it.

## Describe the improvement

Add a note to run the following:
```sql
GRANT USAGE ON SCHEMA other_schema TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA other_schema TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA other_schema TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA other_schema TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA other_schema GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA other_schema GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA other_schema GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
```

**Comment by chasers** [comment]
How does this look with the actual endpoint URLs?  

This should happen automatically for you.  We should also have the docs autogenerate for different custom schemas.  Can do this in a separate issue.

**Comment by soedirgo** [comment]
The endpoint URLs should be the same, but you'd send an [HTTP header](https://postgrest.org/en/stable/api.html#switching-schemas) to specify the schema.

Doing it automatically might not be desirable for users with schemas they don't want PostgREST to access (is there a valid use case for this?). I do think the DX could be improved though.

**Comment by stlbucket** [comment]
Is the above sql still correct?  I am getting an error:
```
Failed to run sql query: must be member of role "supabase_admin"
```
on this line:
```
ALTER DEFAULT PRIVILEGES FOR ROLE postgres, supabase_admin IN SCHEMA app GRANT ALL ON TABLES TO anon, authenticated, service_role;
```

**Comment by stlbucket** [comment]
Maybe this is no longer relevant?  I found this open bug:  https://github.com/supabase/supabase/issues/13538

I found this issue before finding the bug, which is related to what I assume is the feature that makes this issue moot?

**Comment by soedirgo** [comment]
@stlbucket you do still need to run the SQL, though it was a bit outdated - I've updated the query to remove `supabase_admin`.

**Comment by stlbucket** [comment]
@soedirgo - I can't seem to get this to work no matter what I try.

Am I missing something here?  

I would expect the below script to give me todo and create_todo in my API, but there is nothing.  

I have double-checked my exposed schemas.

```

drop schema if exists todo cascade;
create schema todo;
------------------------------------------------------
create extension if not exists citext;
----------------------------------------------------------------------------------------------
create type todo.todo_status as enum (
  'incomplete'
  ,'complete'
  ,'archived'
);
----------------------------------------------------------------------------------------------
  create table if not exists todo.todo (
  id uuid NOT NULL DEFAULT gen_random_uuid() primary key
  ,created_at timestamptz not null default current_timestamp
  ,updated_at timestamptz not null default current_timestamp
  ,name citext not null
  ,description citext
  ,status todo.todo_status not null default 'incomplete'
);  
----------------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION todo.create_todo(_name citext)
  RETURNS todo.todo
  LANGUAGE plpgsql
  VOLATILE
  SECURITY INVOKER
  AS $$
  DECLARE
    _retval todo.todo;
  BEGIN
    insert into todo.todo(name) values(_name) returning * into _retval;
    return _retval;
  end;
  $$;
----------------------------------------------------------------------------------------------
GRANT USAGE ON SCHEMA todo TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA todo TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA todo TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA todo TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA todo GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA todo GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA todo GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
----------------------------------------------------------------------------------------------
ALTER TABLE todo.todo ENABLE ROW LEVEL SECURITY;
----------------------------------------------------------------------------------------------
create policy "Anyone can access"
    on todo.todo for all
    using ( 1 = 1 );
----------------------------------------------------------------------------------------------
-- not sure if this is needed, but it doesn't help
grant execute on function todo.create_todo(citext) to authenticated;
```

**Comment by stlbucket** [comment]
https://www.section.io/docs/tutorials/distributed-apis/distributed-postgraphile-supabase/

I built a quick postgraphile server and connected - it discovers everything as I would expect.  fwiw.

**Comment by stlbucket** [comment]
@soedirgo - any idea on this?  i cannot get other schemas outside of public to expose through the api - i must be doing something wrong, but I don't see where I'm deviating from what you said above

**Comment by stlbucket** [comment]
is this something that is maybe not available on the free plan?

**Comment by stlbucket** [comment]
Follow-up:

curl <SUPABASE_API_URL>/rest/v1/todo -H "Accept-Profile: todo" -H "apikey: <SUPABASE_ANON_KEY>" -H "Authorization: Bearer <SUPABASE_ANON_KEY>"

Through support email, I was told to check with this approach. What I am doing above is correct.

To be clear - schemas other than public do not show up in auto-generated api documentation or in the graphql playground.

But the data can be accessed via curl and (I hope, still TBD) through supabase-js.

**Comment by archraziel88** [comment]
> To be clear - schemas other than public do not show up in auto-generated api documentation or in the graphql playground.

afaik if you mean use custom schemas in client and ssr client, you just use the options: {db:{schema: schema-name}} in client creation:

this my hooks in svelte 
```ts
event.locals.supabase = createSupabaseServerClient({
		supabaseUrl: PUBLIC_SUPABASE_URL,
		supabaseKey: PUBLIC_SUPABASE_ANON_KEY,
		event,

		options: {
			db: {
				schema: 'my-custom-schema'
			}
		}
	});
```

**Comment by soedirgo** [comment]
Thanks @archraziel88! Yes, you'd need to set `options.db.schema = 'todo'`. For the autogenerated API, I think it only shows the public schema right now, but this is something we can fix (you can retrieve the OpenAPI version by querying `/rest/v1/` with `Accept-Profile: my-custom-schema`).

**Comment by archraziel88** [comment]
would love to see autogenerated docs in studio able to reach custom schemas in selfhosted 🥲
