### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#492]
Hi 👋🏻 

**Spoiler alert:** the documentation is great. Supabase's documentation is really good, and we learn a lot of things using it. **BUT**, a lot of stuff is missing in, creating confusions like in #437.

So, I decided to create a thread about a lot of questions I got myself when using Supabase (and ``supabase-js``):

1) What is a SupabaseClient in fact? Is it just a way to link Supabase and the project I did? Or is it a real client (1 client/user), and I need to create another one each time there is a new user?
2) The ``SupabaseClient.auth#signOut`` method from the ``supabase-js`` lib is really confusing me: "Signs out the current user, if there is a logged in user". But if we're using Supabase in a NodeJs backend like I do, what is exactly the current user? Because there is more than 1 user in this case.
3) Same for the ``SupabaseClient.auth#user`` method: "Get the JSON object for the logged in user."
4) How do I logout a specific user? I guess it's not implemented yet, so this one becomes a suggestion.
5) How do JWT tokens work? Like after each request I get one, nice, but how am I supposed to do? Is there any way to link my backend request object to the ``supabase-js`` lib?
6) "For security purposes, the auth schema is not exposed on the auto-generated API", well it's kinda annoying if I need to get some data using my backend, how am I supposed to do? :/

Anyway, thanks a lot for your work, Supabase is really great and I'm starting to use it a lot to give the most feedback I can :p

_Originally posted by @Olyno in https://github.com/supabase/supabase/discussions/438_

**Comment by kiwicopple** [comment]
@ykdojo thoughts on this one? My current thoughts:

### 1. What is a SupabaseClient in fact? 

we should update the [JS Docs](https://github.com/supabase/supabase-js/blob/a5dc5d252a1ec7c9c2c2a5682dd77868fe2c3a97/src/SupabaseClient.ts#L20) on `supabase-js` client

### 2 & 3  - serverside auth

We need to think how we do "server side" and "client side" docs. Perhaps with Thor's GoTrue updates?

### 4. How do I logout a specific user?` 

 The joys of JWT. You can't really invalidate the token. I guess we could document that? We would have to move to session-based auth to get this functionality. Or there maybe something that I'm missing on GoTrue which allows this?

### 5. How do JWT tokens work? 

Big topic :) Perhaps we can just link to some existing content for now, but this could be a "JWT in 30 mins" type post eventually?

### 6. "For security purposes, the auth schema is not exposed on the auto-generated API"

The correct answer to this one right now is to write an `rpc()` function. Perhaps another thing to document (where?)

**Comment by ykdojo** [comment]
@kiwicopple thanks for this. I feel like this type of feedback on documentation is really helpful - it lets us know where to focus our attention.

I'll take a look at these points one by one, and add a comment here and on the original discussion as I resolve them.
