### ISSUE TITLE
Reset password link=> error: User Not found

### ISSUE THREAD

**Issue by edelah** [supabase/supabase#4931]
# Bug report

## Describe the bug
When I click for the first time on the Reset password link, I am redirected to the correct URL but with  a fragment parameter, error_description=User+not+found, instead of an access_token and type=recovery.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1) I received this link at me email adress:

https://eemwleknacuzazgnmcoh.supabase.co/auth/v1/verify?token=xSAL_m5086vFURaGdUEtHg&type=recovery&redirect_to=http://localhost:3000/passwordreset

2) I copy and pasted that link in Insomnia to send the request and look at the response

3) In the response the 302 redirect is http://localhost:3000/passwordreset#error_code=404&error_description=User+not+found
 
Here the full timeline:

*** Preparing request to https://eemwleknacuzazgnmcoh.supabase.co/auth/v1/verify?token=xSAL_m5086vFURaGdUEtHg&type=recovery&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Fpasswordreset
* Current time is 2022-01-12T02:09:06.058Z
* Using libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Too old connection (412 seconds), disconnect it
* Connection 7 seems to be dead!
* Closing connection 7
* TLSv1.3 (OUT), TLS alert, close notify (256):
* Too old connection (411 seconds), disconnect it
* Connection 8 seems to be dead!
* Closing connection 8
* Hostname in DNS cache was stale, zapped
*   Trying 104.18.26.135:443...
* Connected to eemwleknacuzazgnmcoh.supabase.co (104.18.26.135) port 443 (#9)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: C:\Users\edela\AppData\Local\Temp\insomnia_2021.7.2\ca-certs.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Oct 21 00:00:00 2021 GMT
*  expire date: Oct 20 23:59:59 2022 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x2195fb9c050)**

> GET /auth/v1/verify?token=xSAL_m5086vFURaGdUEtHg&type=recovery&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Fpasswordreset HTTP/2
> Host: eemwleknacuzazgnmcoh.supabase.co
> user-agent: insomnia/2021.7.2
> accept: */*

* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!

< HTTP/2 302 
< date: Wed, 12 Jan 2022 02:09:06 GMT
< content-type: text/html; charset=utf-8
< content-length: 110
< location: http://localhost:3000/passwordreset#error_code=404&error_description=User+not+found
< cf-ray: 6cc2d73c5bd6085b-CDG
< access-control-allow-origin: *
< vary: Origin, Origin
< via: kong/2.2.1
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< x-kong-proxy-latency: 1
< x-kong-upstream-latency: 1.0000591278076
< server: cloudflare
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400

* Ignoring the response-body
* Received 110 B chunk
* Connection #9 to host eemwleknacuzazgnmcoh.supabase.co left intact
* Issue another request to this URL: 'http://localhost:3000/passwordreset#error_code=404&error_description=User+not+found'
*   Trying ::1:3000...
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#10)

> GET /passwordreset HTTP/1.1
> Host: localhost:3000
> User-Agent: insomnia/2021.7.2
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Cache-Control: no-store, must-revalidate
< X-Powered-By: Next.js
< ETag: "f66-ERfihGl+brA3i6tvFGlQREY4ytI"
< Content-Type: text/html; charset=utf-8
< Content-Length: 3942
< Vary: Accept-Encoding
< Date: Wed, 12 Jan 2022 02:09:07 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5

* Received 3.8 KB chunk
* Connection #10 to host localhost left intact

## Expected behavior

The response sould contain 2 query parameters:

- type=recovery
- access_token=xSAL_m5086vFURaGdUEtHg

**Comment by edelah** [comment]
Seems the access_token is send in a fragment, not a query parameter. I close this issue.

**Comment by Wimpert** [comment]
@edelah I am facing the samen issue. But it is not 100% clear to me how to solve it. 

What exactly am I doing wrong?

**Comment by MediaFormIT** [comment]
This is happening to me too, how can it be solved?
