### ISSUE TITLE
Adding emojis to headings to make the landing page attractive 

### ISSUE THREAD

**Issue by Shubh28698** [supabase/supabase#4944]
# Improve documentation
 
link to the page which needs improvement : https://github.com/supabase/supabase

Currently on the landing page there is only text, so we can improve it by adding emojis to the headings.

## Describe the improvement
we can improve it by adding emojis to the headings, so that it looks great and attractive and interactive

for eg: documentation ->> documentation📄

let me know if you like this feature, i am having it ready with me so that i can open a pull request

Thanks!

![emojis](https://user-images.githubusercontent.com/39756589/149159776-4825379c-cb08-4089-a235-5a4809bf43a3.PNG)

**Comment by kiwicopple** [comment]
Hey @Shubh28698 - this one is a matter of preference. While I do appreciate emojis, I think they are generally better outside of documentation (and great in comments 😄 )

I'll close this, but if we decide to add them in the future I'll make sure we credit you :)
