### ISSUE TITLE
Framework Tutorials

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#495]
# Improve documentation

## "Examples" kaizen

We have a (very basic) examples section here: https://supabase.io/docs/guides/examples

I think we can kaizen a bit on this by making it a "Frameworks Tutorials" section. Then we can do a very simple example of how to use Supabase with XXX framework. For example:

- Supabase with Next.js
- Supabase with React
- Supabase with Redwood
- Supabase with Svelte
- Supabase with Vue

etc. When we have backend libraries we can add them too - Supabase with Django, Supabase with Gin etc.

Each one will step the user through a _very basic_ example, which will also live in our [examples](https://github.com/supabase/supabase/tree/master/examples) folder.

Note from YK

> you suggested a todo app, but I was wondering if there are any other options for it. I feel something that could show SB's real-time capability could be more interesting? I was thinking maybe something like:
> - Multiplayer tic tac toe (kind of like a continuation of the react tutorial)
> - Some kind of chat app - kind of like the Slack example we have, but maybe with some kind of twist to make it more interesting?
>
> I'm thinking if we could come up with an example that's both simple and interesting, while maybe showing the real-time capabilities, it would be ideal. Any thoughts? 

Definitely would love to show off the realtime functionality. I think the slack clone is a bit advanced though - adding a UserContext and shared state. If we had to do this for every framework it could be a bit tedious. Maybe we can instead make the todo list collaborative? Or we can just add realtime functionality to the existing one, then inside the tutorial we can get the user to "duplicate" a row from the dashboard, which would appear in their app?

**Comment by ykdojo** [comment]
> Definitely would love to show off the realtime functionality. I think the slack clone is a bit advanced though - adding a UserContext and shared state. If we had to do this for every framework it could be a bit tedious. Maybe we can instead make the todo list collaborative? Or we can just add realtime functionality to the existing one, then inside the tutorial we can get the user to "duplicate" a row from the dashboard, which would appear in their app?

This sounds good!

**Comment by ykdojo** [comment]
I'm thinking, @awalias's [this article on building a to-do app](https://dev.to/awalias/howto-build-collaborative-realtime-task-lists-in-react-4k52) might be a good starting point. Maybe I can go through it again and rewrite it / integrate it into our docs?

Also, in a comment to that article, someone suggested making a second part on auth - and got a few likes. It might be a good idea since it's kind of hard to get it right. Thoughts?

**Comment by kiwicopple** [comment]
It's a good baseline although his was multi-list and collaborative (and we never had auth when he first wrote that)

The new ones are a lot more basic - just a login page and then a page for managing your own todos.

I haven't looked at all of them but I know the Next.js one is quite up-to-date. Perhaps sketch up an outline on a branch? Or I can sketch the draft if you prefer. I think ideally they can all follow the same "format", so it's easy to compare between the tutorials.

**Comment by ykdojo** [comment]
Okay got it. I'll see if I can make a simpler version of his that's more up-to-date, then.

I'll think about if it should be a single article or two separate ones - the second one would be for auth.

I'll probably start with an outline or a rough draft as you suggested.

**Comment by klutchdev** [comment]
I have some neat ideas I could toss into the mix using GatsbyJS if you want!

1. Simple chat/messenger
2. Quick rendition of the Google T-Rex game (maybe? lol) with a realtime scoreboard of player high scores
3. A scrolling text marquee powered by string/text data from the database

**Comment by awalias** [comment]
@klutchdev haha the T-Rex game sounds epic
