### ISSUE TITLE
Doc search sometimes link to non-existnent pages

### ISSUE THREAD

**Issue by iAmWillShepherd** [supabase/supabase#4957]
# Improve documentation

## Link 

https://supabase.com/docs/blog/2021/12/01/realtime-row-level-security-in-postgresql#realtime-design

## Describe the problem

I was searching for how to use the real-time API live, on stream, when I ran into this. The doc is missing; it may be a blocker, but I figured I'd raise the issue before trying to find a workaround. 

## Describe the improvement

Create the page, so it exists or remove the page from the search index. 

## Additional context

![2022-01-12 16 06 42](https://user-images.githubusercontent.com/1715082/149230833-c4f3574d-058e-4e43-b8d2-f033e50e8f93.gif)

### Other pages that don't work
* https://supabase.com/docs/blog/2021/09/10/supabase-beta-august-2021#realtime-security-codename-walrus
* https://supabase.com/docs/blog/2021/12/15/beta-november-2021-launch-week-recap#realtime-row-level-security
* https://supabase.com/docs/blog/2021/12/17/holiday-hackdays-winners-2021#best-realtime-project

I'm sure that there are others, but I'm sure y'all can find more simply by searching and testing if the link leads to a doc that exists.

**Comment by inian** [comment]
Duplicate https://github.com/supabase/supabase/issues/4317
