### ISSUE TITLE
Improve docs for enabling extensions

### ISSUE THREAD

**Issue by chipilov** [supabase/supabase#4968]
# Improve documentation

## Link 

[Extensions](https://supabase.com/docs/guides/database/extensions)

## Describe the problem

The documentation provides an example of how to enable extensions via SQL: ```create extension pgtap;```

However, there seem to be 2 issues with this example:
 - In order to ensure that the extension is installed in the ```extensions``` schema, the statement should be ```create extension pgtap with schema extensions```;
 - Enabling some extensions using the statement above leads to permission issues (e.g. ```dblink```, ```http```, ```pg_cron```). More specifically:
    - The extensions CANNOT be enabled with the ```postgres``` users, because this leads to the following error:```
Query 1: ERROR:  permission denied to create extension "plpgsql_check"
HINT:  Must be superuser to create this extension.```

    - If the extensions are enabled via the Dashboard query editor (which uses the supabase_admin role), the enabling succeeds, however, other roles (e.g. ```postgres```) cannot use the extensions;
    - NOTE: this does NOT seem to be a problem with all extensions. For example ```pgtap``` can be installed with the ```postgres``` user (which, unlike the extensions listed above as problematic, has NO native code as far as I know);

## Describe the improvement

I think there need to be 2 improvements addressing both issues above:
- specify the extensions schema in the example;
- document which users to use when enabling extensions OR specify how to enable extensions with supabase_admin and still allow other roles to have access to extensions;

**Comment by ratika-12** [comment]
@kiwicopple I want to work on this.

**Comment by ratika-12** [comment]
@chipilov I want to work on this

**Comment by Isaiah-Hamilton** [comment]
@ratika-12 I don't know if you still want to work on it but it's open for you to work on.

**Comment by yeganathan18** [comment]
Issue still up?

**Comment by Isaiah-Hamilton** [comment]
> Issue still up?

@yeganathan18 yes

**Comment by yeganathan18** [comment]
Cool, let me fix it 🛠

**Comment by Isaiah-Hamilton** [comment]
@yeganathan18 go for it 🚀

**Comment by yeganathan18** [comment]
> Enabling some extensions using the statement above leads to permission issues (e.g. dblink, http, pg_cron)

@chipilov is this means the one in the doc already? or the one you suggested?

**Comment by chipilov** [comment]
@yeganathan18 I am afraid I don't really understand the question.

All the extensions I have given as examples in this issue are part of the official documentation and can be enabled via the toggles in the Dashboard UI.

The problem arises when you try to enable SOME of them using SQL statements (as opposed to the Dashboard UI).

Does that answer your question?

**Comment by yeganathan18** [comment]
@chipilov thanks for your help! I have made the required changes in the doc now.

**Comment by chipilov** [comment]
@yeganathan18 Added a couple of comments to the patch.

**Comment by christopheragnus** [comment]
https://supabase.com/docs/guides/database/extensions/postgis

Why the heck isn't the schema option added to the docs yet?

**Comment by gregnr** [comment]
Hey @christopheragnus! Can you explain what you mean? The `postgis` docs mention the `extensions` schema:
```sql
create extension postgis with schema extensions;
```

**Comment by christopheragnus** [comment]
@gregnr I meant its not clear in the docs that there is a modal that popups asking you which schema to select. Looks like default is `extensions`.

**Comment by gregnr** [comment]
@christopheragnus got it, thanks for clarifying. Would you be interested in creating a PR to add this to the docs?
