### ISSUE TITLE
SQL is under documented in general but especially for advanced functions

### ISSUE THREAD

**Issue by FurkanToprak** [supabase/supabase#4977]
# Improve documentation
Increase documentation for wrappers of more complex SQL queries (e.g. count)
## Link 
https://supabase.com/docs/reference/javascript/select
Add a link to the page which needs improvement (if relevant)

## Describe the problem
Not enough database query schema information.
Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement
There should be more advanced schemas of returned payloads, especially for optional headers like `count`, an example of would be the fact that count would be returned like
```
const { count } = await supabaseClient.from('user_followers')
    .select('*', {count: 'exact'}).eq('follower_id', userData.id);
``` 
A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by kiwicopple** [comment]
Hey @FurkanToprak - that looks pretty similar to the `count` example here:
https://supabase.com/docs/reference/javascript/select#querying-with-count-option

Can you clarify what was confusing? Was it not obvious that you can combine `count` with filters like `eq()`?

**Comment by FurkanToprak** [comment]
Hey @kiwicopple, I guess I wasn't looking carefully. Closed!
