### ISSUE TITLE
Enable RLS by default for new tables

### ISSUE THREAD

**Issue by inian** [supabase/supabase#4991]
For tables created from the dashboard, RLS is disabled by default. 

![image](https://user-images.githubusercontent.com/2155545/149487648-fb68b680-5970-4e22-93eb-aef391390bb9.png)

Enabling it by default will improve security. We need to balance this with users forgetting to add a RLS policy and not getting any data back from the API. A good compromise would be to have an easy way to create a select policy for anon users when creating the table.

**Comment by activenode** [comment]
I was about to write  the exact same ticket. This is super-crucial. Was just discussing this with a colleague. It should be Zero-Trust first. 

Users that are new to Supabase might try out and have - uknowingly - open tables at first which I find weird as a default. The default should be that RLS is enabled and only if someone wants to we could have a checkbox like "No RLS for this table -> Everyone can read and write on this table"
