### ISSUE TITLE
Client Libraries

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#5]
This issue is for tracking requests/demand for client libraries. Give a comment a thumbs up if you want the connector built.

Please refrain from adding comments unless you are adding a language which isn't already listed.

**Comment by kiwicopple** [comment]
Python

**Comment by kiwicopple** [comment]
Rust

**Comment by pdavidow** [comment]
Haskell

**Comment by fadhlirahim** [comment]
Swift

**Comment by fadhlirahim** [comment]
Kotlin

**Comment by dukex** [comment]
Ruby

**Comment by rmznrddn** [comment]
Go

**Comment by antosubash** [comment]
C#

**Comment by WXSoftware** [comment]
Dart

**Comment by ianmyles** [comment]
Python

**Comment by elangora** [comment]
Java

**Comment by elangora** [comment]
Java

**Comment by ImreSamu** [comment]
<a name="logo"/>
<div align="center">
<a href="https://julialang.org/" target="_blank">
<img src="https://julialang.org/images/logo_hires.png" alt="Julia Logo" width="210" height="142"></img>
</a>
</div>

**Comment by Immortalin** [comment]
@elangora @fadhlirahim I think Java and Kotlin can be merged under the same umbrella.

**Comment by aridwiprayogo** [comment]
@Immortalin nope, kotlin have a feature that java doesn't like coroutine, extension function, lazy property, data class, etc

_Sent from my ZenFone Max Pro (M1) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by noahlh** [comment]
[Crystal](https://crystal-lang.org)

**Comment by Immortalin** [comment]
Lua

**Comment by Immortalin** [comment]
F#

**Comment by Immortalin** [comment]
Clojure

**Comment by Immortalin** [comment]
[V](https://github.com/vlang/v)

**Comment by JCKodel** [comment]
Flutter (Dart): I have a 3 million download app that I'm rewriting. Currently, I use a framework for MSSQL I've created (basically, RPC for Stored Procedures and offline-first sync SQLite <-> MSSQL). I will use Supabase, so I can help writting and/or testing a client for Flutter.

**Comment by mandarvaze** [comment]
Elixir

**Comment by SUPERTEMPO** [comment]
JavaScript

**Comment by orcchg** [comment]
Android SDK (written in Kotlin in a way compatible with Java)

**Comment by kiwicopple** [comment]
Hey @SUPERTEMPO we have Javascript! 

Docs are here: https://supabase.io/docs/library/getting-started
Repo is here: https://github.com/supabase/supabase-js

**Comment by ethanpil** [comment]
PHP

**Comment by helenamerk** [comment]
React Native

**Comment by AbhigyanKumar** [comment]
# C++

**Comment by AbhigyanKumar** [comment]
# Microsoft .NET framework
