### ISSUE TITLE
Can you guys take out the refresh button until it fully works 😆 

### ISSUE THREAD

**Issue by magiusdarrigo** [supabase/supabase#5002]
# Bug report
This button:

<img width="189" alt="Screen Shot 2022-01-14 at 10 31 55 PM" src="https://user-images.githubusercontent.com/43056803/149608913-9c4dbbd6-8f13-4b66-8fe4-8a92efa9130a.png">

does not update my table's values.

## Describe the bug
It sometimes causes me to think a value is true to what I see.

## To Reproduce
1. Change a value in the DB through the console GUI.
2. Press the refresh button.
3. Watch your value not update.

## Expected behavior
To update without needing to manually refresh the page.

## System information

- OS: macOS
- Browser chrome
- chrome Version 97.0.4692.71 (Official Build) (arm64)

## Additional context
Thanks!

**Comment by joshenlim** [comment]
Hey there! I just gave this a try but the issue seems to be fixed now - the refresh button does work as expected
As for automatic refreshing - this is a feature that we're still looking into but won't be available soon

I'll go ahead to close this ticket but feel free to reopen if i'm wrong! 🙏
