### ISSUE TITLE
Realtime Subscriptions don't work with Row Level Security

### ISSUE THREAD

**Issue by FurkanToprak** [supabase/supabase#5009]
# Bug report

## Describe the bug
I won't receive any subscriptions when row level security is enabled.  
## To Reproduce

Create a subscription to any realtime-enabled database. Enable row level security and the socket does not work.

## Expected behavior
I expect the rows that are allowed for row-level access to be returned by the subscription when inserted, deleted, or updated.

## System information

- OS:  Ubuntu 20.04
- Firefox
- Version of supabase-js: 
```
"@supabase/supabase-js": "^1.29.1",
```
- Version of Node.js: 16.13.1

**Comment by w3b6x9** [comment]
@FurkanToprak can you please email support@supabase.io with the ref of the project you're having Realtime issues with?

**Comment by FurkanToprak** [comment]
Hey @w3b6x9, where would I find this ref?

**Comment by kiwicopple** [comment]
this one is in the URL - it might be easier to use this form: https://app.supabase.io/support/new

**Comment by FurkanToprak** [comment]
I want to reopen this issue, no one has addressed it.

**Comment by w3b6x9** [comment]
@FurkanToprak please fill out this form (https://app.supabase.io/support/new) or email support@supabase.io and we can address your issue(s).

**Comment by w3b6x9** [comment]
@FurkanToprak also, if you check again you shouldn't have this issue anymore.

**Comment by jalexy12** [comment]
not particularly helpful to direct people to internal channels on github issues -- one of the main perks of github is that other people can reference fixes etc later.

**Comment by w3b6x9** [comment]
@jalexy12 you're right, it's advantageous to resolve issues in public and we only direct folks to submit a support ticket when we have to take a closer look at their project while protecting their privacy.
