### ISSUE TITLE
JSON column updates don't work

### ISSUE THREAD

**Issue by songololo** [supabase/supabase#5015]
# Bug report

## Describe the bug

It doesn't appear possible to update JSON columns.

## To Reproduce

```js
const { data, error } = await this.supabase
        .from('my_table')
        .update({ json_col: { test: 10 } })
        .eq('uid', this.user.id)
      if (error) {
        console.error(error)
      } else if (data) {
        console.info(data)
      }
```

## Expected behavior

The JSON column will be updated with the new value.

This line is returned as an error:
```
PATCH https://<url>/rest/v1/<table>?uid=<uid> 404
```
And an empty error message is returned on the next line.

I've not been able to find the source of the issue but it seems that something is getting lost in translation in the process of wrapping the queries and parameters in nested layers of JSON?

I've tried a variety of approaches but none seem to work.
e.g.
```js
// something similar to the docs page
.update(`{ json_col: { test: 10 } }`)
// else
.update({ json_col: JSON.stringify({ test: 10 }) })
// etc...
```

I suppose a workaround would be to just use a TEXT column and stringify the data, but thought I'd check in case there is a workable approach to use JSON columns?

## System information

- OS: macOS
- Version of supabase-js: 1.29.1
- Version of Node.js: 17.3.0

**Comment by GaryAustin1** [comment]
404 error sounds like you don't have access because of RLS to update.  
Do you have RLS on?  Does another field update besides the json one?
If RLS is on you need a using (or using and with check) policy for update to pass RLS.

**Comment by songololo** [comment]
Thanks.

I only had `UPDATE` operations enabled for RLS (I'm only pushing updates to this table) and it appears that this was hindering `supabase` from doing its thing.

I've now enabled `SELECT` operations and the `supabase` operations are now able to complete successfully (presumably some `SELECT` operations happening along the way?)

**Comment by GaryAustin1** [comment]
Just to follow up.  Do you actually have a "using" policy for your update?  That is for the read part of the update.  "with check" in the update is assumed to be the same if you don't add a separate "with check"
The reason I ask is I thought Supabase only did a separate select (optional with setting to turn off) for insert.
You should be able to allow insert/update without access to read/select.

**Comment by GaryAustin1** [comment]
I see that update also has the option:
returning minimal
If you set that then it won't do a separate select.  I missed that update had that option also.

**Comment by songololo** [comment]
This is how I've formatted the `UPDATE` RLS:
```sql
CREATE POLICY
    "Restricts table UPDATEs to UID."
    ON public.my_table FOR UPDATE
    USING (auth.uid() = uid);
```

Thanks for the hint on returning minimal.

I see that the Postgres docs have a `SELECT FOR UPDATE` option on creating policies...
