### ISSUE TITLE
New Table: CSV upload/paste not showing data in Content Preview, HTML element squished

### ISSUE THREAD

**Issue by ErikGraciosa** [supabase/supabase#5016]
# Bug report

## Describe the bug

New Table: CSV upload/paste not showing data in Content Preview, HTML element squished

When creating a new table using 'Import data via spreadsheet', using either 'Upload CSV' or 'Paste text',
After clicking 'Save',
'Content Preview' is squished and not visible and no rows shown, columns are present.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Table Editor>New Table>Import data via spreadsheet>Upload CSV>Save'
2. Click on ''Save from Import data via spreadsheet'
3. No error

## Expected behavior

Expecting to see scrollable window with data present

## Screenshots

Original
![image](https://user-images.githubusercontent.com/70562690/149676083-82467d7b-25c9-4463-895a-ea2e5907ee7a.png)

After editing height
![image](https://user-images.githubusercontent.com/70562690/149676092-4bbc9867-fd8f-480c-9945-d55cfea95b10.png)

## System information

- OS: Windows 11
- Browser (if applies) Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by pablocubico** [comment]
Hey @ErikGraciosa and @kiwicopple , I made a fix here: https://github.com/supabase/supabase/pull/5399

Let me know if that works for you. Tested locally.

Cheers!

**Comment by saltcod** [comment]
This is merged and This looks right to me. Marking as closed. Thanks all!
