### ISSUE TITLE
Postgresql.csv log consumes all disk space

### ISSUE THREAD

**Issue by Manuelbaun** [supabase/supabase#5023]
# Bug report

## Describe the bug

When running supabase, the docker overlay 2 runs full. I could track it down to the postgresql.csv logs under `var/lib/docker/overlay2/**/diff/var/log/postgresql`. It seems that logs don't have an upper limit.

## Expected behavior

I would expect, that the logs won't grow indefinitely. At least, there most be some settings to specify the upper size.

## Screenshots

My LXC container had 15GB diskspace and the csv file contained 6.4 GB.

## System information

- OS: Ubuntu 20.10 Server in an LXC Container

**Comment by kiwicopple** [comment]
Hey @Manuelbaun - this one is probably not a bug. It's up to you to manage the configuration of your Postgres instance to suit your particular use-case.

You could check out the `log_rotation_size` config option (https://postgresqlco.nf/doc/en/param/log_rotation_size/) and possibly dig into a logrotate solution like https://vector.dev (which is very good!)

**Comment by captainR0bbo** [comment]
@Manuelbaun I think this could also be my issue. I don't think I had this problem on an earlier supabase docker image. It was Postgres 13. Now on Postgres 14 I do have this issue. 

I see how log rotation can fix it. but to modify the postgresql.conf file, don't we need to modify the supabase/postgres image?

**Comment by Manuelbaun** [comment]
@captainR0bbo 
I also only noticed it with Postgres version 14. Now I changed the `log_rotation_size`  setting in the postgres.conf file. I will now observe, if this fixes it.

**Comment by Manuelbaun** [comment]
somehow, the logrotation does not work properly. I think its best, when supabase use some sort of config to manage it.

i've set the below log rotation configs, but it still eats up all my disk space. Does anybody have a suggestion?

```conf
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'	# log file name pattern,
					# can include strftime() escapes
#log_file_mode = 0600			# creation mode for log files,
					# begin with 0 to use octal notation
log_rotation_age = 1d			# Automatic rotation of logfiles will
					# happen after that time.  0 disables.
log_rotation_size = 100MB		# Automatic rotation of logfiles will
					# happen after that much log output.
					# 0 disables.
log_truncate_on_rotation = on		# If on, an existing log file with the
					# same name as the new log file will be
					# truncated rather than appended to.
					# But such truncation only occurs on
					# time-driven rotation, not on restarts
					# or size-driven rotation.  Default is
					# off, meaning append to existing files
					# in all cases.
```

**Comment by captainR0bbo** [comment]
Did you make those configs in a directory that you have mapped as a docker volume? Otherwise you configs get wiped out with each container restart. 

I turned the log collector off for now. 

Also had to set a max log file size for docker logs as those also grew infinitely

**Comment by Manuelbaun** [comment]
yes, I set the configs in the postgres.conf file, that is mounted and not directly in the docker container itself. After restart, I checked the configs inside the docker container and there were identical. 

Is it possible that another file or some sort of settings somewhere override my conf somehow?

**Comment by Manuelbaun** [comment]
supabase still eatsup all the diskspace. What i did now, is I mount the postgres a local conf into the docker, where I disable completely logging. For some reason, limiting does not work.

also a docker *-log.json in /var/lib/docker/overlay2 keeps growing over 3 gb in 4 hours. I have no idea how to prevent that.

**Comment by captainR0bbo** [comment]
Yes checkout my last comment about setting the max log file size for docker. That was a docker config change on the server/computer running docker. Not the container. Should be an easy Google search. It was a long time ago so I don't recall where specifically

**Comment by Manuelbaun** [comment]
ok, I have set the logsize in the daemon.json. lets see if this solves the final issue.

**Comment by captainR0bbo** [comment]
Yes, the fix was to create a postgressql.conf file, setting the log collector to off or set the log rotation parameters to manage number and size of the log files.

put that file in your /volumes/db/pgconfig, which is mounted to /etc/postgresql in the docker compose:

- ./volumes/db/pgconfig:/etc/postgresql

**Comment by amexcompliance** [comment]
Before I do , can I manually delete this huge postgresql.csv file?

**Comment by amexcompliance** [comment]
created a file called postgresql.conf which has a single entry 
log_collector=off 
 moved it to under ./volumes/db/pgconfig (pgconfig did not exist , had to create it) and docker-compose up throws errors, unable to connect to the db

**Comment by ymilhahn** [comment]
Seems like https://github.com/supabase/supabase/commit/4a70284e47f9ef00d1ff7f65096e4319e25333fd fixes this issue in a better way? It's excluding just the realtime polling queries, which seem to be the cause of fast growing log files in the first place?

Can be closed?
