### ISSUE TITLE
Missing metadata In Flutter storage.list

### ISSUE THREAD

**Issue by wwawrzy** [supabase/supabase#5024]
# Bug report

## Describe the bug

Metadata in Flutter dart is missing. After:

```
StorageResponse<List<FileObject>> result =
       await supabase.storage.from(from).list(searchOptions: SearchOptions(limit: 10000, offset: 0, sortBy: SortBy(column: 'created_at', order: "desc")));
```

Objects _FileObject_ in list does not contain any metadata. 

In debug we can see that metadata are obtained in _storage_file_api.dart_ file but are skipped during _fromJson()_ conversion:

```
class Metadata {
  const Metadata({required this.name});

  Metadata.fromJson(dynamic json) : name = json['name'] as String?;

  final String? name;
}
```

## Expected behavior
Add size, mimetype, cacheControl in Metadata 

## Screenshots
Example of _FileObject_ in debug mode:
![image](https://user-images.githubusercontent.com/91059830/149737233-8c9d2a3a-bae1-4c98-9108-dfba74ca04ba.png)

Example of response which contains desired metadata in debug mode (but missing in FileObject):
![image](https://user-images.githubusercontent.com/91059830/149737316-b2824991-e6a0-4a4c-a734-fe63040d2de8.png)

## System information

- OS: [Windows]
- Desktop app
- Dart supabase: ^0.2.13

**Comment by wwawrzy** [comment]
Here is a patch that allow to return metadata from json to Metadata (from storage_client 0.0.6+2)

```
// TODO: need to check for metadata props. The api swagger doesnt have.
class Metadata {
  const Metadata({required this.name, required this.size, required this.mimetype, required this.cacheControl});

  Metadata.fromJson(dynamic json)
      : name = json['name'] as String?,
        size = json['size'] as int?,
        mimeType = json['mimetype'] as String?,
        cacheControl = json['cacheControl'] as String?;

  final String? name;
  final int? size;
  final String? mimetype;
  final String? cacheControl;
}
```

I'm not sure if it is ok but seems to works.

**Comment by kiwicopple** [comment]
Hey @wwawrzy - would you mind opening this issue in this repo? https://github.com/supabase-community/storage-dart

Unfortunately I can't transfer it becuase it's in the community org
