### ISSUE TITLE
Validate max length for DB password at project creation and DB password reset

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#5025]
Related: https://github.com/supabase/infrastructure/issues/3675

A user brought up that a very long password was used when creating project, but was unable to access the DB using the same password. Seems like there's a 99 character limit for postgresql passwords?
ref: https://stackoverflow.com/questions/19499058/pgsql-character-limitations

need to enforce that on the UI at project creation endpoint and db password reset pages
- /[slug]/new
- settings/database

probably can do that at password strength component?

**Comment by FatumaA** [comment]
Hey, 
I've looked a little bit at this: 
Seems you can't make new project locally?
Also, @joshenlim is it to restrict the length of the password only as a separate check such that the user gets an error message if p/word is too long?

**Comment by CodeOnnnn** [comment]
Hey,
Yes, we can get it right by throwing an error if the user enters the password string more than a specified number.
After reading the documentation of pgAdmin4 and searching for this issue,  @joshenlim I believe this requires some changes in the config.py file: Platform

File Location

Linux

/etc/pgadmin/config_system.py

macOS

/Library/Preferences/pgadmin/config_system.py

Windows

%CommonProgramFiles%\pgadmin\config_system.py

![image](https://user-images.githubusercontent.com/72307451/149960843-43bd9292-fb70-4444-b2f7-91dcb6ce934e.png)

**Comment by joshenlim** [comment]
@FatumaA 
> Seems you can't make new project locally?

Yeah you're right! The self-hosted version of supabase does not include any project management scope, it's solely for the database only

> to restrict the length of the password only as a separate check such that the user gets an error message if p/word is too long?

there won't be any errors thrown back if the password is too long, at least based on Supabase's internals - this password length check is solely on the client side, with a max of 99 characters

@CodeOnnnn 
Can i clarify real quick what do you mean by the need the update the config.py file? This issue should only require a frontend change on our dashboard

**Comment by FatumaA** [comment]
In that case, we won't be able to test changes to the affected components locally unless I'm missing something
