### ISSUE TITLE
Queries to table don't work

### ISSUE THREAD

**Issue by poutingemoji** [supabase/supabase#5026]
# Bug report

## Describe the bug
I can't query any columns from my table 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

users Table
![unknown](https://user-images.githubusercontent.com/67280672/149751678-5bbf7bdb-f7d0-4883-90ed-9a3a3a4a8c4a.png)

user_cards Table
![unknown](https://user-images.githubusercontent.com/67280672/149751895-1608bae0-1ee1-4be8-a3ed-082f81d82231.png)

![unknown](https://user-images.githubusercontent.com/67280672/149751745-301ad9f5-2c5a-4edd-b80c-c7ecb7f470b8.png)
![unknown](https://user-images.githubusercontent.com/67280672/149751756-1a792d10-2bae-4b11-bc51-0b70c05eb2fd.png)

my foreign table queries aren't working anymore. they were working before. the only significant change i can think of that ive made between  then is enabling replication for inserts on my user_cards table. is this a glitch or am i misunderstanding something about related tables?

I've also tried just querying for my location_id column in my users table

**Comment by kiwicopple** [comment]
hey @poutingemoji 

> my foreign table queries aren't working anymore. they were working before

Can you share some more details? What is getting returned? Is there an error?

**Comment by poutingemoji** [comment]
> hey @poutingemoji
> 
> > my foreign table queries aren't working anymore. they were working before
> 
> Can you share some more details? What is getting returned? Is there an error?

ah, my bad. the error was `Error while retrieving user: column users.exp does not exist`. Nothing gets returned since it errored. I think the foreign key relationships in my database got messed up. Sometimes it allows me to query to foreign tables and sometimes it just tells me that the columns don't exist.

**Comment by poutingemoji** [comment]
```js
`
cards: user_cards (
  exp,
  data: cards (
    name,
    rarity: rarities (
      emoji
    ),
    type: types (
      emoji
    ), <-- this comma
  ),
  abilities: user_card_abilities (
    name,
    data: card_abilities (
      is_hidden,
      chance
    )
)`
```
The issue was an extra comma in my query. I knew trailing commas would mess up the query but it fell off my mind when I was focusing on other things. Hope this helps anyone else who makes this silly mistake!
