### ISSUE TITLE
doc improvements / bugs

### ISSUE THREAD

**Issue by laurentS** [supabase/supabase#503]
# Improve documentation

(sorry, I'm gonna break the template as I have a couple of bugs to report)

- https://supabase.io/docs/client/auth-user  the example shows that `supabase.auth.user()` returns a user object, but from what I'm seeing, it's giving me a promise. `await` missing?
- https://supabase.io/docs/client/auth-signup the return value seems to put the useful stuff under `data` not `user`.

Generally speaking it'd be cool to see what the return types look like.

Good luck!

**Comment by laurentS** [comment]
(sorry, just realised that maybe this belongs in the `supabase-js` repo?)

**Comment by kiwicopple** [comment]
All good @laurentS - you can report these here and we can shift them around if they belong somewhere else.

Thanks for reporting - I'll fix these two bullet points soon. 

> Generally speaking it'd be cool to see what the return types look like.

Yeah you're right. That one might take more time as we generate these docs from the TSDoc (and so I'll have to figure out how to parse the return types). Good idea though - I'll create a separate issue for it.

**Comment by kiwicopple** [comment]
hey @laurentS 

> the return value seems to put the useful stuff under data not user.

https://github.com/supabase/gotrue-js/blob/57001d54cc2ef65b7fdca41d60e7510f62afa952/src/GoTrueClient.ts#L103

It looks like you are wanting all of the session data? We put the actual user under `user`, but we expose the `data` for legacy reasons (we'll probably phase it out)

**Comment by laurentS** [comment]
@kiwicopple I'm not actually. I just need the user_id at this point. I will double check my code, maybe I got confused by some errors.
