### ISSUE TITLE
Supabase Self-Hosted not load correctly postgres schema

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#5044]
# Bug report

## Describe the bug

I have those functions:

```
-- Set up is_member_of function
CREATE FUNCTION is_member_of(_user_email text, _channel_id int8) RETURNS bool AS $$
SELECT EXISTS (
  SELECT 1
  FROM public.channel_users cu
  WHERE cu.channel_id::int8 = _channel_id::int8
  AND cu.user_mail::text = _user_email::text
);
$$ LANGUAGE sql SECURITY DEFINER;

-- Set up is_admin function
CREATE FUNCTION is_admin(_user_email text) RETURNS bool AS $$
SELECT EXISTS (
  SELECT 1
  FROM auth.users u
  WHERE u.email::text = _user_email
  AND u.raw_user_meta_data->>'role' = 'admin'
);
$$ LANGUAGE sql SECURITY DEFINER;

-- Set up get_channel_list function
CREATE FUNCTION public.get_channel_list(mail text)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, starter_email character varying, shop_id bigint, logo character varying, name character varying, total_message bigint, last_message_read bigint, to_read bigint)
 LANGUAGE plpgsql
AS $function$
begin
	return query
	select init.id,init.created_at,init.starter_mail,init.shop_id,init.logo,init.name,init.total_messages,
		(case when init.last_message_read > 0 then init.last_message_read else 0 end) as last_message_read,
		(select count(cm2.id) from public.channel_messages cm2 where cm2.id > init.last_message_read) to_read
	from 
	(
		select *,
		(select count(cm.id) from public.channel_messages cm where cm.channel_id = c.id ) as total_messages,
		(select cu.last_message_read from public.channel_users cu where cu.channel_id = c.id and cu.user_mail = mail ) as last_message_read 
		from public.channel as c
	) as init
	order by init.shop_id asc, to_read desc, init.total_messages desc;
end
$function$
;

-- Set up get_channel_list_shop function
CREATE FUNCTION public.get_channel_list_shop(mail text, shopID int8)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, starter_email character varying, shop_id bigint, logo character varying, name character varying, total_message bigint, last_message_read bigint, to_read bigint)
 LANGUAGE plpgsql
AS $function$
begin
	return query
	select init.id,init.created_at,init.starter_mail,init.shop_id,init.logo,init.name,init.total_messages,
		(case when init.last_message_read > 0 then init.last_message_read else 0 end) as last_message_read,
		(select count(cm2.id) from public.channel_messages cm2 where cm2.id > init.last_message_read) to_read
	from 
	(
		select *,
		(select count(cm.id) from public.channel_messages cm where cm.channel_id = c.id ) as total_messages,
		(select cu.last_message_read from public.channel_users cu where cu.channel_id = c.id and cu.user_mail = mail ) as last_message_read 
		from public.channel as c
		where c.shop_id = shopID
	) as init
	order by init.shop_id asc, to_read desc, init.total_messages desc;
end
$function$
;

-- Set up get_channel_list_user function
CREATE FUNCTION public.get_channel_list_user(mail text)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, starter_email character varying, shop_id bigint, logo character varying, name character varying, total_message bigint, last_message_read bigint, to_read bigint)
 LANGUAGE plpgsql
AS $function$
begin
	return query
	select init.id,init.created_at,init.starter_mail,init.shop_id,init.logo,init.name,init.total_messages,
		(case when init.last_message_read > 0 then init.last_message_read else 0 end) as last_message_read,
		(select count(cm2.id) from public.channel_messages cm2 where cm2.id > init.last_message_read) to_read
	from 
	(
		select *,
		(select count(cm.id) from public.channel_messages cm where cm.channel_id = c.id ) as total_messages,
		(select cu.last_message_read from public.channel_users cu where cu.channel_id = c.id and cu.user_mail = mail ) as last_message_read 
		from public.channel as c
		where c.starter_mail = mail
	) as init
	order by init.shop_id asc, to_read desc, init.total_messages desc;
end
$function$
;

-- Set up get_specific_channel_data function
CREATE FUNCTION public.get_specific_channel_data(mail text, cid int8)
 RETURNS TABLE(id bigint, created_at timestamp with time zone, starter_email character varying, shop_id bigint, logo character varying, name character varying, total_message bigint, last_message_read bigint, to_read bigint)
 LANGUAGE plpgsql
AS $function$
begin
	return query
	select init.id,init.created_at,init.starter_mail,init.shop_id,init.logo,init.name,init.total_messages,
		(case when init.last_message_read > 0 then init.last_message_read else 0 end) as last_message_read,
		(select count(cm2.id) from public.channel_messages cm2 where cm2.id > init.last_message_read) to_read
	from 
	(
		select *,
		(select count(cm.id) from public.channel_messages cm where cm.channel_id = c.id ) as total_messages,
		(select cu.last_message_read from public.channel_users cu where cu.channel_id = c.id and cu.user_mail = mail ) as last_message_read 
		from public.channel as c
		where c.id = cid
	) as init
	order by init.shop_id asc, to_read desc, init.total_messages desc;
end
$function$
;
```

But supabase load only three: `get_channel_list, is_admin, is_member_of`

![image](https://user-images.githubusercontent.com/36926081/149970374-6a156796-2b77-485d-a818-48b6c6b7d75e.png)

Of course all functions exist into postgres and work perfectly if runned by SQL editor on postgres, checking the permission ect are equal of all the three loaded by supabase-studio

## To Reproduce

1. Execute the create function queries
2. Reload the supabase-db container using: "[sudo] docker-compose restart supabase-db"
3. Connect to supabase studio and go to API section

## Expected behavior

I need execute those function via supabase-js using supabase.rpc function

## System information

- OS: Linux
- Browser: Chrome
- Version of supabase-js: ^1.28.5
- Version of Node.js: 16.0.0

**Comment by WilliamFalci** [comment]
**UPDATE:**

Looking the urgent I have on make this work I tried this:

`sudo docker-compose down`

then I make a new sql file, named: `04-custom.sql` inside `supabase/docker/volumes/db`

I pasted into `04-custom.sql` all the various queries to create tables, functions, buckets, alter query for the realtime ect. With only a difference, I renamed the functions:

- get_channel_list
- get_channel_list_shop
- get_channel_list_user
- get_specific_channel_data

in

- channels_admin
- channels_shop
- channels_user
- channel_data

then I runned `sudo docker-compose up`

**Result:**

Everything as been created /altered properly:

![image](https://user-images.githubusercontent.com/36926081/149982559-7aae0e89-348d-4ffa-b3a2-059970d56400.png)


But supabase is still loading the old schema:

![image](https://user-images.githubusercontent.com/36926081/149982686-4c74d809-84d1-4c90-b843-5657fb461473.png)


This is pretty annoying because I deleted all test data to make "work" I think are some cache issue with supabase or something like this, someone can help me or fix the issue?

**Comment by GaryAustin1** [comment]
You might need to clear out the schema cache. 
https://postgrest.org/en/latest/schema_cache.html#the-stale-schema-cache

**Comment by WilliamFalci** [comment]
> You might need to clear out the schema cache. https://postgrest.org/en/latest/schema_cache.html#the-stale-schema-cache

Already tested all the ways:

`sudo docker kill -s SIGUSR1 supabase-db` -> then -> `sudo docker restart supabase-db` -> nothing happened
`NOTIFY pgrst, 'reload schema'` runned on sql of postgress -> then -> `sudo docker restart supabase-db` -> nothing happened

```
-- Create an event trigger function
CREATE OR REPLACE FUNCTION public.pgrst_watch() RETURNS event_trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  NOTIFY pgrst, 'reload schema';
END;
$$;

-- This event trigger will fire after every ddl_command_end event
CREATE EVENT TRIGGER pgrst_watch
  ON ddl_command_end
  EXECUTE PROCEDURE public.pgrst_watch();
```

added to `04-custom.sql` before everything, nothing happened

and with `sudo docker-compose down` all volumes of all containers of supabase are deleted, this mean at moment of `sudo docker-compose up` the cache would be clear... theorically...

but how u can see from the previous message... not work

**Comment by WilliamFalci** [comment]
The only wayt to make it work has been prune all docker configuration, clone project again and run it again

**Comment by dbmikus** [comment]
I'm running into this issue and it really cripples local development for me.

**Comment by WilliamFalci** [comment]
> I'm running into this issue and it really cripples local development for me.

Hi dbmikus,

personally I fixed in this way:

1. Create a sql file into: docker/volumes/api/db/init - for example in my case I make `04-custom.sql`
2. Then copy the following code:
```
-- watch create and alter
CREATE OR REPLACE FUNCTION pgrst_ddl_watch() RETURNS event_trigger AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN SELECT * FROM pg_event_trigger_ddl_commands()
  LOOP
    IF cmd.command_tag IN (
      'CREATE SCHEMA', 'ALTER SCHEMA'
    , 'CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO', 'ALTER TABLE'
    , 'CREATE FOREIGN TABLE', 'ALTER FOREIGN TABLE'
    , 'CREATE VIEW', 'ALTER VIEW'
    , 'CREATE MATERIALIZED VIEW', 'ALTER MATERIALIZED VIEW'
    , 'CREATE FUNCTION', 'ALTER FUNCTION'
    , 'CREATE TRIGGER'
    , 'CREATE TYPE'
    , 'CREATE RULE'
    , 'COMMENT'
    )
    -- don't notify in case of CREATE TEMP table or other objects created on pg_temp
    AND cmd.schema_name is distinct from 'pg_temp'
    THEN
      NOTIFY pgrst, 'reload schema';
    END IF;
  END LOOP;
END; $$ LANGUAGE plpgsql;

-- watch drop
CREATE OR REPLACE FUNCTION pgrst_drop_watch() RETURNS event_trigger AS $$
DECLARE
  obj record;
BEGIN
  FOR obj IN SELECT * FROM pg_event_trigger_dropped_objects()
  LOOP
    IF obj.object_type IN (
      'schema'
    , 'table'
    , 'foreign table'
    , 'view'
    , 'materialized view'
    , 'function'
    , 'trigger'
    , 'type'
    , 'rule'
    )
    AND obj.is_temporary IS false -- no pg_temp objects
    THEN
      NOTIFY pgrst, 'reload schema';
    END IF;
  END LOOP;
END; $$ LANGUAGE plpgsql;

CREATE EVENT TRIGGER pgrst_ddl_watch
  ON ddl_command_end
  EXECUTE PROCEDURE pgrst_ddl_watch();

CREATE EVENT TRIGGER pgrst_drop_watch
  ON sql_drop
  EXECUTE PROCEDURE pgrst_drop_watch();
```

This SQL will create a function to watch schema changes and force the cache to reload schemas + the various triggers on it, for more info this is the documentation: [https://postgrest.org/en/latest/schema_cache.html](https://postgrest.org/en/latest/schema_cache.html)

Probably you will need rebuild the containers pruning the volumes

**Comment by vbylen** [comment]
@WilliamFalci I must be really dumb, but how do I navigate into the docker/volumes/api/db/init directory and create a sql file?

**Comment by dbmikus** [comment]
@vbylen I did this

```
cat <<EOF > .supabase/docker/postgres/10-postgrest-cache-automatic-reload.sql
CREATE SCHEMA IF NOT EXISTS util;

-- Create an event trigger function
CREATE OR REPLACE FUNCTION util.pgrst_watch() RETURNS event_trigger
  LANGUAGE plpgsql
  AS \$\$
BEGIN
  RAISE NOTICE 'reloading the schema';
  NOTIFY pgrst, 'reload schema';
END;
\$\$;


-- This event trigger will fire after every ddl_command_end event
CREATE EVENT TRIGGER pgrst_watch
  ON ddl_command_end
  EXECUTE PROCEDURE util.pgrst_watch();
EOF
```

Wherever you set up Supabase locally, you should have a `.supabase/` directory.

**Comment by WilliamFalci** [comment]
> @WilliamFalci I must be really dumb, but how do I navigate into the docker/volumes/api/db/init directory and create a sql file?

Ops sorry, I fixed the path.

The correct path is docker/volumes/db/init (so from the root of this repository after the cloning you will have the folder Docker ect)

**Comment by dbmikus** [comment]
Please ignore my comment above above the filepath. I was using an old version of the Supabase CLI.

**Comment by sweatybridge** [comment]
I cannot reproduce this locally on latest version of self hosted. I ran the query in the original post through the dashboard's SQL editor and all functions are listed as expected.

![Screenshot 2023-01-20 at 11 02 02 AM](https://user-images.githubusercontent.com/1639722/213609226-3bf91c70-d74f-47cf-af48-50b67e3d1438.png)

Feel free to re-open if anyone has something new to add.
