### ISSUE TITLE
Index search

### ISSUE THREAD

**Issue by Annie-khalid** [supabase/supabase#5051]
# Bug report

## Describe the bug

After index is created ,let's suppose 
'anim':7 'bigger':6 'littl':10 'poki':9 'puppi':1,11 'slower':3

but now if i pass "ani" in my search bar it will return nothing

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

I want it to return results after partial match

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by kiwicopple** [comment]
Hey @Annie-khalid - would you please be able to provide some steps to replicate? I'll close this one for now but if you can update the description and comment here I will reopen 👍
