### ISSUE TITLE
Invite Email does not use updated template

### ISSUE THREAD

**Issue by rain2o** [supabase/supabase#5059]
# Bug report

## Describe the bug

When sending an invite to a user, the email uses the original plain template, even after updating the template to something new.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Auth -> Templates -> Invite User.
2. Change the template to something noticeably different.
3. Invite a new user.
4. See email in original format.

## Expected behavior

The email should be sent using the template provided in the Invite User template section.

## Screenshots

<img width="1423" alt="Screen Shot 2022-01-19 at 19 12 17" src="https://user-images.githubusercontent.com/4626224/150189526-9f8e30a7-0882-4a66-8c4b-f8fa090a204b.png">
<img width="614" alt="Screen Shot 2022-01-19 at 19 12 32" src="https://user-images.githubusercontent.com/4626224/150189532-358f064a-1a1b-4485-bd9e-c35ba8c94863.png">

## System information

- OS: macOS
- Browser (if applies) Firefox
- Version of supabase-js: N/A (using interface only for testing)
- Version of Node.js: N/A

## Additional context

I have updated all other email templates and each of them are sending with the appropriate template. Invite User is the only one that doesn't seem to be working.

Just to make sure it wasn't a cache or otherwise time issue, I waited 1 day after originally changing and testing it to confirm it still is not using the proper template.

**Comment by imskr** [comment]
I am not able to reproduce it @rain2o I actually edited the user template and it's sending me the invite as expected.

**Comment by rain2o** [comment]
@imskr I did some more testing, and it looks like I had some sort of invalid value in my template, which caused it to use the default template instead of mine. I didn't catch this before because I was using the same template on all the emails, and only this one failed. I guess one of the variables I tried to use from the documentation was maybe invalid or wrong.

Sorry for the false bug! It's working for me now.

**Comment by gauravkumar065** [comment]
> @imskr I did some more testing, and it looks like I had some sort of invalid value in my template, which caused it to use the default template instead of mine. I didn't catch this before because I was using the same template on all the emails, and only this one failed. I guess one of the variables I tried to use from the documentation was maybe invalid or wrong.
> 
> Sorry for the false bug! It's working for me now.

No, there is a bug related to this. I also get this error when i updated the email template, btw where is default template?

**Comment by DanisJa** [comment]
> @imskr I did some more testing, and it looks like I had some sort of invalid value in my template, which caused it to use the default template instead of mine. I didn't catch this before because I was using the same template on all the emails, and only this one failed. I guess one of the variables I tried to use from the documentation was maybe invalid or wrong.
> 
> Sorry for the false bug! It's working for me now.

Do you mind sharing the invalid values with others? What did you do for it to work? What was the exact variable? From which documentation?

I have the same error.

**Comment by PixsaOJ** [comment]
Your problem is `{{ email }}`

**Comment by coren-frankel** [comment]
I had just experienced this "bug" and upon checking my use of the variables I found a typo in my custom template. 
Works as expected now.
