### ISSUE TITLE
Add return types to the docs

### ISSUE THREAD

**Issue by yuank1983** [supabase/supabase#506]
All good @laurentS - you can report these here and we can shift them around if they belong somewhere else.

Thanks for reporting - I'll fix these two bullet points soon. 

> Generally speaking it'd be cool to see what the return types look like.

Yeah you're right. That one might take more time as we generate these docs from the TSDoc (and so I'll have to figure out how to parse the return types). Good idea though - I'll create a separate issue for it.

_Originally posted by @kiwicopple in https://github.com/supabase/supabase/issues/503#issuecomment-757613536_

**Comment by ImBIOS** [comment]
@kiwicopple I think this issue should also be closed like the #7895 closed.
It's already become a stale issue.
