### ISSUE TITLE
tables schema filter bug

### ISSUE THREAD

**Issue by phamhieu** [supabase/supabase#5068]
# Bug report

## Describe the bug

> We do not have any tables in the public schema but we do have an **app** schema which we pretty much control and have tables in. I was able to see it before but I cannot seem to see it now.

- project/[ref]/database/tables: only show public schema 
  - filter base on `Schema` settings
  - need a schema selection dropdown like table editor

- project/[ref]/auth/policies: only show public schema 
  - filter base on `Schema` settings
  - need a schema selection dropdown like table editor

![Screenshot 2022-01-20 at 3 04 49 PM](https://user-images.githubusercontent.com/689843/150297808-1b50906c-21f4-4386-957b-14446f32fb24.png)

**Note**: We use postgREST to interact with the tables. To see tables on these pages, its schema need to be included on `Schema` settings

**Comment by olirice** [comment]
> need a schema selection dropdown like table editor

+1

Currently to add a new schema you click any of the existing schemas to present a drop down list. Selecting one of the entries in the dropdown adds it to the `Schema` list.

It took a little trial and error to figure out. I agree that a dropdown multi-select would be more intuitive

**Comment by joshenlim** [comment]
update on this - i'm improving the multiselect input in the API settings as part of the policy editor roles update, should be able to get it in within this week

**Comment by joshenlim** [comment]
Hey all! Sorry forgot to update this ticket - this has now been fixed. So you can click on the entire input field and it'll drop down a searchable dropdown where you can find your schema! Feel free to reopen if anyone might feel like the issue has not been resolved

![image](https://user-images.githubusercontent.com/19742402/171131256-d098bbf2-92fd-4c1f-9302-fe453a85d161.png)
