### ISSUE TITLE
Supabase query data based on uid does not work

### ISSUE THREAD

**Issue by SergejSachs** [supabase/supabase#5074]
I created the table and policy via UI and I always get an emtpy list. If my expression is just true I get all my rows.

![image](https://user-images.githubusercontent.com/26410357/150381750-7b02d46a-17f5-4a3d-8961-7187bd34f099.png)

![image](https://user-images.githubusercontent.com/26410357/150381850-da9ea129-9a8b-4465-9ed4-3bc42ac0bf16.png)

```
var response = await supabaseClient.from('portfolios').select().execute();
    if (response.error == null) {
      final results = response.data as List<dynamic>;
      return results.map((e) => Portfolio.fromMap(e)).toList();
    }
    throw Exception("Error while fetching portfolios");
```

I tried as well everything via script:

```
CREATE TABLE portfolios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  user_id uuid references users (id)
);

alter table portfolios
  enable row level security;
```

`create policy "Read own portfolios" ON public.portfolios for select USING ((auth.uid() = portfolios.user_id));`

**Comment by kiwicopple** [comment]
hey @SergejSachs 

is that with the JS client? The query should be :

```js
var response = await supabaseClient.from('portfolios').select()
```
eg, no `.execute()`

Also - are you should the user is logged in before executing the request? if you log `supabase.auth.user()` what does it return?

**Comment by SergejSachs** [comment]
> hey @SergejSachs
> 
> is that with the JS client? The query should be :
> 
> ```js
> var response = await supabaseClient.from('portfolios').select()
> ```
> 
> eg, no `.execute()`
> 
> Also - are you should the user is logged in before executing the request? if you log `supabase.auth.user()` what does it return?

Its the flutter client: https://pub.dev/packages/supabase and it calls execute as well.
I get the user right before the save portfolio call and pass the userid from the auth response.



```
var user = supabaseClient.auth.currentUser;

static Portfolio fromMap(Map<String, dynamic> data) {
    return Portfolio(
      id: data['id'],
      userId: data['user_id'],
      name: data['name'],
    );
  }
```

**Comment by kiwicopple** [comment]
I don't know if this is possible, but in Dart are you able to see the Network requests? If so, can you inspect the request and send me the Bearer token in the `Authorization` header? If we decode that it should show the user_id that is making the request.

> but still empty array.

This usually means that the RLS is working properly, and there is a problem either with the Policy (which doesnt seem to be the case) or the network request

**Comment by SergejSachs** [comment]
> I don't know if this is possible, but in Dart are you able to see the Network requests? If so, can you inspect the request and send me the Bearer token in the `Authorization` header? If we decode that it should show the user_id that is making the request.
> 
> > but still empty array.
> 
> This usually means that the RLS is working properly, and there is a problem either with the Policy (which doesnt seem to be the case) or the network request

![image](https://user-images.githubusercontent.com/26410357/150565715-5b30fb68-7439-4d18-ba87-d124b404b20d.png)

[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQyNjc3OTA2LCJleHAiOjE5NTgyNTM5MDZ9.sdX8-VU6MxHt4Tx1fePtpqBvNJu-MrzdAVt6IjfhZWQ]

The reseponse is [];

**Comment by awalias** [comment]
hey @SergejSachs the token being sent is the default anon api key and not the user's key, so it makes sense that it is not returning any user data

<img width="995" alt="image" src="https://user-images.githubusercontent.com/458736/150566406-f4a1ce43-c8b4-420f-b82d-c201a3e4faa5.png">

so my assumption is that this is an issue with the client or usage, I'll transfer this issue to the dart repo, the folks there should be able to help

**Comment by SergejSachs** [comment]
@awalias thanks, maybe someone had the same issue there.

Yes true, maybe its because I dont use it as a singleton. 
I will try that.

**Comment by awalias** [comment]
> maybe its because I dont use it as a singleton

yes this will be the issue. you should use the same client for auth and CRUD, if you want it to automatically pass the user's `access_token` with each request. In JS there is a `set_auth()` method which you can use to manually set the session, perhaps there is something similar in dart lib

**Comment by SergejSachs** [comment]
> > maybe its because I dont use it as a singleton
> 
> yes this will be the issue. you should use the same client for auth and CRUD, if you want it to automatically pass the user's `access_token` with each request. In JS there is a `set_auth()` method which you can use to manually set the session, perhaps there is something similar in dart lib

Ah thanks. I will take a loot at it and use a singleton probably and close the issue if fixed.

**Comment by awalias** [comment]
oh I can't transfer between orgs, but the repo is here: https://github.com/supabase-community/supabase-dart

**Comment by SergejSachs** [comment]
> oh I can't transfer between orgs, but the repo is here: https://github.com/supabase-community/supabase-dart

Should I reopen there If needed?

**Comment by kiwicopple** [comment]
> Should I reopen there If needed?

yes please!

**Comment by SergejSachs** [comment]
It was the singleton/no token in header issue. Thanks for your help!
