### ISSUE TITLE
Improve INSERT and UPDATE response bodies for REST APIs

### ISSUE THREAD

**Issue by fenix-hub** [supabase/supabase#508]
# Feature request
Return meaningful response bodies for successful `INSERT` and `UPDATE` queries on REST API calls `POST` and `PATCH`.

## Is your feature request related to a problem? Please describe.
Successful `POST` and `PATCH` HTTP requests will return an empty (`{ }`) response body giving no useful informations.
Even though this could be considered as OK (everything is OK as far as it is not an error), the response body could instead be used to give meaningful information about the request result.
This feature could improve the usability of Database REST APIs themselves, considering the case where a table consists of one (or more) auto generated values, or just a single autogenerated value as primary key, instead of being explicitely provided (90% of the cases could end up in a violation of the unique constraint).  

Considering the "Todo List" example, the main `todos` table consists of a structure such as the follwing:
|:key: id|user_id|task|is_complete|inserted_at|
|-|-|-|-|-|

Assume a `POST` request to insert a new row in a newly created databse, giving the following body:
```
{ "user_id": "{user.id}", "task": "{task}", "is_complete":"false" }
```
will eventually end up adding the row to the database with an auto generated `id` (primary key) and a `inserted_at` correspnding to the server insertion time, that may differ from the client issued one.
Server side, we could end up having something like this:
|:key: id|user_id|task|is_complete|inserted_at|
|:-:|:-:|:-:|:-:|:-:|
|1|{user.id}|{task}|false|yyyy-mm-dd...|  

Client side, the response will just consist of a `{ }` body, giving no information about `id` and `inserted_at` values.

For sure we could anyway build up our environment client-side **expecting** to follow a sequencial structure... with two additional insertions, we could end up in something like (extract):
|:key: id|
|:------:|
|1|
|2|
|3|

Upon 3rd insertion, let's now `DELETE` it.
|:key: id|
|:------:|
|1|
|2|

And let's add a new one, again.
Server side:
|:key: id|
|:------:|
|1|
|2|
|4|

But if the client had not internal memory about what happened (ex. the client disconnects after the 3rd row deletion), with a previous `GET` and a sequential logic, its `id` should be: 
```
int new_row_id = last_row_id + 1 (= 3, not 4)
```
which is an inconsistent orphan entity.

If the client was able in the first place to retrieve *even just* the genereted `id` value from a successful `POST` response, a **callback logic** could be applied in order to create client-side entities in more consistent way. 

ex.
```
1. var new_entity_body = { "user_id":"{user.id}", "task":"{task}", "is_complete":false }
2. HTTPClient -> `POST` new_entity_body
3. var response = HTTPClient.response
4. add_entity(response.id, new_entity_body)
```

## Describe the solution you'd like

The most used solution (generally speaking) is to give as the response body the whole row's values:
```
{ "id":"{id}", "user_id":"{user_id}", ... }
```

Considering the ability to request multiple insertion with just one http request:
```
POST 
{ [ 
{"task":"task_1"}, 
{"task":"task_2"} 
] }
```
A response schema could be:
```
{ [
{row 1},
{row 2}
] }
```
To simplify the response, this could be shortened to contain only generated values and key values
```
{ [
{"id":"1"},
{"id":2"}
] }
```

## Describe alternatives you've considered

- Making a `GET` request each time rows are added/updated could be avoided
- Using Realtime REST APIs won't be necessary (thus they are not available)

**Comment by soedirgo** [comment]
That's odd, the client should be returning the inserted/updated/deleted rows (though you can disable this). So:

```js
const { createClient } = require('@supabase/supabase-js')
const supabase = createClient('https://foo.supabase.co', 'bar');

(async () => {
    const { error, data } = await supabase
        .from('todos')
        .insert({})

    console.log('Error:', error)
    console.log('Data:', data)
})()
```

Should return:
```js
Error: null
Data: [ { id: ..., user_id: null, task: null, is_complete: null, inserted_at: ... } ]
```

**Comment by fenix-hub** [comment]
Hi and thank you for answering.
Here's what happens on my client (developed in gdscript with Godot, but I'll post the results obtained with Postman which are the same)

**Sign In Request**
![P5SmsXFZm1](https://user-images.githubusercontent.com/45271396/104291286-a2178500-54bb-11eb-9991-106ca0a7cc6e.png)

curl equivalent:
```
curl --location --request POST 'https://{mysupabasebackend}.supabase.co/auth/v1/token?grant_type=password' \
--header 'Content-Type: application/json' \
--header 'apiKey: {myapikey}' \
--header 'Cookie: __cfduid=d98f4bfafccb130eaf192cfd4923e5d511610440436' \
--data-raw '{
    "email":"user@usermail.mail",
    "password":"usermailpassword"
}'
```
---> Correct non-empty response

**Insert Row Request**  
![iSc9oQ7pc9](https://user-images.githubusercontent.com/45271396/104291295-a5ab0c00-54bb-11eb-90c9-d088890ac89e.png)

curl equivalent:
```
curl --location --request POST 'https://{mysupabasebackend}.supabase.co/rest/v1/todos' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {userapikey}' \
--header 'apiKey:  {myapikey}' \
--header 'Cookie: __cfduid=d98f4bfafccb130eaf192cfd4923e5d511610440436' \
--data-raw '
[
    {
        "task": "Postman task",
        "user_id": "6d78e4b0-8d35-4c2c-9f69-4a77a33b8f0c",
        "is_complete": false
    }
]
'
```
---> Row added correctly but empty response
![msedge_UZ6iahSxp6](https://user-images.githubusercontent.com/45271396/104291814-4ef20200-54bc-11eb-8b76-85efcc81076e.png)


Unless the returning row response is not automatically disabled on Database REST endpoints, I didn't diasble anything. 
Eventually could you tell me where's the setting please? Couldn't find it myself.
Thank you!

**Comment by soedirgo** [comment]
Ah, I see. I can only speak for the `/rest` endpoint, which we use PostgREST for under the hood. To obtain the response body, you need to [pass a header](https://postgrest.org/en/v7.0.0/api.html#insertions-updates) to PostgREST. This is done by default in the supabase-js client.

We're focusing on the JS client for now, but we plan support [other languages](https://github.com/supabase/supabase/discussions/5) in the future. (I saw that you worked on [GodotFirebase](https://github.com/WolfgangSenff/GodotFirebase) - really cool!)

So you can interact with the endpoints directly as a workaround for now, but let us know if you have similar problems :)

**Comment by fenix-hub** [comment]
`Prefer: return=representation` in Header works as a charm.
![msedge_NT9dwHMhaK](https://user-images.githubusercontent.com/45271396/104300440-c4fb6680-54c6-11eb-98c1-7f5cd1b5a988.png)

Thank you very much, at this point I think that this should just be documented for noobs like me :)
![msedge_HhEjQKEaap](https://user-images.githubusercontent.com/45271396/104301832-62a36580-54c8-11eb-8b00-c184f904a38d.png)

I'll update my code and demos for sure.
By the way, you can find it [here](https://github.com/fenix-hub/godot-engine.supabase).

Thank you for your help!

**Comment by kiwicopple** [comment]
Nice, great idea @fenix-hub . I added the header to the docs (will go out in the next deployment)

**Comment by io-Karim-developer** [comment]
{
    "hint": null,
    "details": null,
    "code": "42501",
    "message": "new row violates row-level security policy for table \"profiles\""
}
how i can solve this

**Comment by GhostLabs94** [comment]
I read this 

> Nice, great idea @fenix-hub . I added the header to the docs (will go out in the next deployment)

This is not in the docs as of today.

I was longtime searching for this little line :D
