### ISSUE TITLE
Cannot login anymore via Github

### ISSUE THREAD

**Issue by leandertolksdorf** [supabase/supabase#5084]
# Bug report

## Describe the bug

I just tried logging into https://app.supabase.io via Github after a while. I was redirected to GitHub, logged in and authorized the application, which seems strange because I already have an account with working projects on Supabase. 

Then I got redirected to this URL: `https://app.supabase.io/#error=unauthorized_client&error_code=401&error_description=Unverified+email+with+github` 

and received multiple emails asking to confirm my email. The link in the email `https://alt.supabase.io/?token=xxx&type=signup&redirect_to=https://app.supabase.io/` leads to this error:

```
{"message":"no Route matched with those values"}
```

I've been using Supabase for a while and have projects running that are also accessible via the client without issues.

## To Reproduce

As described

## Expected behavior

Working login

## System information

- Mac OS
- Firefox and Chrome

**Comment by Isaiah-Hamilton** [comment]
@leandertolksdorf with supabase you now need to verify your Github account email to be able to log into supabase. you can verify your Github account email [here](https://github.com/settings/emails).

**Comment by kiwicopple** [comment]
If you still have issues with this after verifying @leandertolksdorf , can you please send a message to support@supabase.io? thanks!
