### ISSUE TITLE
Invalid Refresh Token on sessionRestore

### ISSUE THREAD

**Issue by SergejSachs** [supabase/supabase#5110]
Hi. I have an issue where I have to sign in again after the expiration duration, configured at Supabase UI, has passed.

**Steps to reproduce**
- Set expiration time to 2 min (Supabase UI, access token expiration?)
- Login & Persist Session e.g. local storage
- Quit app and wait 3 min
- Start app and call restoreSession

**Result**
"Invalid Refresh Token" gets returned from restoreSession

**Expected Behavior**
Fetches new access token and updates SupabaseClient state.

**Singleton Wrapper**
```
abstract class ISupabaseClientService {
  SupabaseClient get();
}

class SupabaseClientService implements ISupabaseClientService {
  final supabaseClient = SupabaseClient(
    EnvironmentService().supabaseUrl,
    EnvironmentService().supabaseKey,
  );

  @override
  SupabaseClient get() {
    return supabaseClient;
  }
}
```

**AuthService**

**SignIn**
```
@override
  Future<AppUser> signInWithEmail(String email, String password) async {
    var result = await _supabaseClientService.get().auth.signIn(email: email, password: password);

    await _saveSession();

    return AppUser( result.user?.id,  result.user.email,  result.user.email);
  }
```

**Called on app start**
```
@override
  Future<AppUser> getCurrentUser() async {
    var user = _supabaseClientService.get().auth.currentUser;

    if (user == null) {
      var session = await _getSession();
      var response = await _supabaseClientService.get().auth.recoverSession(session);

      if (response.error == null) await _saveSession();
      user = response.user;
    }

    return AppUser(
      user?.id,
      user?.email,
      user?.email,
    );
  }
```
**Private methods**
```
Future<void> _saveSession() async {
    final session = _supabaseClientService.get().auth.session();
    final SharedPreferences prefs = await _prefs;
    await prefs.setString('session', session.persistSessionString);
  }

  Future<String> _getSession() async {
    final SharedPreferences prefs = await _prefs;
    var session = (prefs.getString('session') ?? '');
    return session;
  }

  Future<void> _removeSession() async {
    final SharedPreferences prefs = await _prefs;
    await prefs.remove('session');
  }
```

**Persisted Session for restoreSession**
That's my token with the Invalid Refresh token error on my dev environment, not that critical to share.
`"{"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQyODA1ODIwLCJzdWIiOiIzMDc4ZjY2NS1jNjFiLTQ0Y2UtYjY3ZS1kNzIyOTNjMWFjMmMiLCJlbWFpbCI6InNlcmdlai5zYWNoc0BnbXguZGUiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.QQaZpPDTy1urjbZNoMf88I15HIIHIoGRPJN152ht06U","expires_in":120,"refresh_token":"ybqC0YdCNlYxByvlQh5WQA","token_type":"bearer","provider_token":null,"user":{"id":"3078f665-c61b-44ce-b67e-d72293c1ac2c","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"anymail@provider.com","created_at":"2022-01-20T12:12:57.382314Z","confirmed_at":"2022-01-20T12:12:57.387309Z","last_sign_in_at":"2022-01-21T22:55:00.788920397Z","role":"authenticated","updated_at":"2022-01-21T22:55:00.790273Z"}},"expiresAt":1642805820}"`

**RestoreSession works within that configured duration but else it returns that error.**

**Comment by kiwicopple** [comment]
Hi @SergejSachs - I see you also opened an issue here: https://github.com/supabase/supabase/issues/5096

Is this one a bug or a documentation issue? It seems that you are using the Dart libs - did you try opening the issue within the Dart repo too? (could be a valid bug in the refresh logic)

**Comment by SergejSachs** [comment]
Hi @kiwicopple - Looks like its a bug, assumed the refresh token should/never expires.
I opened a bug on the dart repo as well but without any traction for now.

https://github.com/supabase-community/supabase-dart/issues/91

**Comment by osaxma** [comment]
I believe this is an issue with `gotrue-dart`. When refreshing the token, the apiKey is used as an Authorization header instead of the JWT from the session to be refreshed/recovered. 

I tested the server manually using the REST API and refreshing an expired JWT token works fine. 

I filed an issue here:
- https://github.com/supabase-community/gotrue-dart/issues/52

**Comment by SergejSachs** [comment]
Seems like the "gotrue" client got a fix in version 2.3.9.
Now we just need a supabase dart dependency update.

**Comment by colt005** [comment]
When will supabase update the dependencies? Until then, Is there any other work around for this?

**Comment by jnorris441** [comment]
I've seen this on the Javascript client just now...sending the apiKey as the Authorization header token to `/auth/v1/token?grant_type=refresh_token` endpoint? 

Is that a bug also?

**Comment by kiwicopple** [comment]
Hey everyone, the Dart library is currently community-driven, but we just hired someone to look after them fulltime. They will be able to look into this as soon as they join (if not before)

**Comment by dshukertjr** [comment]
@SergejSachs 
Just wanted to check in here to see if you had the chance to test everything out with after the fix on gotrue-dart. Please let me know if you are still getting signed out after the token expires.

**Comment by SergejSachs** [comment]
> @SergejSachs Just wanted to check in here to see if you had the chance to test everything out with after the fix on gotrue-dart. Please let me know if you are still getting signed out after the token expires.

It looks fixed. I put my dev Supabase project token expiration on one hour and I was still signed in after 3 days and another dev build.

The issue that exists is that if you are running the app for 1 hour and don't restart it but that's on my side. 
I should check for status and call the refresh like an startup probably.

**Comment by dshukertjr** [comment]
@SergejSachs Thanks for confirming that it works! 

Yeah, you can certainly call token refresh manually or you can use [supabase_flutter](https://pub.dev/packages/supabase_flutter) package, which will take care of token refresh automatically!

I am going to close this issue, but feel free to open another issue anytime you encounter one!

**Comment by maurovitale** [comment]
Hi @dshukertjr, supabase_flutter seems that is not working as you described. There is an option 'autoRefreshToken' in SupabaseClient constructor that has 'true' as default value, but it is not able to refresh the token automatically. 

I'm using the 3.0.3 version of supabase_flutter. 

I also tried the option of trying to recover the session but I'm receiving the message described on this discussion 'Invalid refresh token'. My code is very simple :

`
     String? persistSessionString = prefs.getString('persistSessionString');

     var recoverSession = await supabaseRepository.client.auth.recoverSession(persistSessionString!);
     await supabaseRepository.client.auth.refreshSession();  // <----- tried also this line as suggested above
`
Is still anyone facing the same issue?

**Comment by dshukertjr** [comment]
Hi @maurovitale,

In order to persist the session using supabase-flutter package currently, you need to include a `SupabaseAuthState` or `SupabaseAuthRequiredState` somewhere in your widget tree and call `recoverSupabaseSession()` method upon initialization. 

Note that all of the above will be obsolete with an update that will be launched next Monday, and the auth state will truly be automatically persisted by only initializing Supabase in your main function so keep an eye out for the update! 👀 There are some exciting things happening in supabase-flutter SDK!
