### ISSUE TITLE
Using the Storage JS API download returns older file after update

### ISSUE THREAD

**Issue by babymechanic** [supabase/supabase#5119]
# Bug report

## Describe the bug

After uploading a new image we should get the new image using the JS API. 
It still downloads the old file.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upload an image using `supabase.storage.from(bucket).upload(filename, oldContent)`
2. Update an image using `supabase.storage.from(bucket).update(filename, newContent)`
3. Download an image using `supabase.storage.from(bucket).download(filename)`

## Expected behavior

We should get the new content but we end up getting the old content.

## System information

- OS: Windows
- Browser Firefox
- Version of supabase-js: 1.21.7
- Version of Node.js: v16.13.0

## Additional context

I noticed that supabase web UI does show the correct image.
Also noticed that  even if you delete the entry in `storage.objects` table using the supabase ui, the file still downloads on when using download.

**Comment by inian** [comment]
Can you see if the update call in step2 suceeded @babymechanic? Supabase Objects by default are cached for 1 hour by the browser. So if you update an object, you need to cache bust it in your web application (by adding a query parameter for example) which is what the Supabase Studio does. 

Or you can set a lower `cacheControl` time when uploading / updating the object, though that will be bad for performance.

**Comment by babymechanic** [comment]
thanks @inian I was able to add a random query string part to cache bust it when required.
