### ISSUE TITLE
Cannot signup new user

### ISSUE THREAD

**Issue by kndnya** [supabase/supabase#5120]
# Bug report

## Describe the bug
Not sure if this is the right place. But not able to make any signup/singin requests to the `supabase-js` client

Running on localhost with initial NextJS setup 
Getting the following error on trying to sign up a user.

```
Unhandled Runtime Error
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

## To Reproduce
My code on `pages/login.js`
```
async function loginHandler(e) {
    e.preventDefault();
    const email = emailRef.current.value
    const password = passRef.current.value

    const { user, session, error } = await supabase.auth.signUp({
      email, password
    });
  }
```

## Expected behavior

`{user, session, error}` but getting a JSON.parse error instead

## System information

Windows. 
All packages up-to-date

**Comment by sadiki-o** [comment]
here is my custom createUser.js file where i import it whenever i want to create a new user and call it by giving an email parameter and a password

```import { supabase } from "../../../initSupabase"

//create new user function
export const createUser = async (email, password) => {
    let { user, error } = await supabase.auth.signUp({
        aud: 'authenticated',
        role: 'authenticated',
        password,
        email,
        confirmation_sent_at: formatTime(),
        app_metadata: { provider: 'email' },
        user_metadata: {},
        created_at: formatTime(),
        updated_at: formatTime()
    })

    return {user, error}
}

function formatTime(){
    return new Date(Date.now()+(1000*60*(-(new Date()).getTimezoneOffset()))).toISOString().replace('T',' ').replace('Z','');
}```

**Comment by sadiki-o** [comment]
Also make sure to configure the supabase client file and enable signups in the supabase dashboard settings

**Comment by kndnya** [comment]
> //create new user function
> export const createUser = async (email, password) => {
>     let { user, error } = await supabase.auth.signUp({
>         aud: 'authenticated',
>         role: 'authenticated',
>         password,
>         email,
>         confirmation_sent_at: formatTime(),
>         app_metadata: { provider: 'email' },
>         user_metadata: {},
>         created_at: formatTime(),
>         updated_at: formatTime()
>     })
> 
>     return {user, error}
> }
> 
> function formatTime(){
>     return new Date(Date.now()+(1000*60*(-(new Date()).getTimezoneOffset()))).toISOString().replace('T',' ').replace('Z','');
> }```  

Getting the same error using this too.  

![Error](https://i.imgur.com/qLv7PX2.png)
