### ISSUE TITLE
whenever i run the signup function the created user auto signin ?

### ISSUE THREAD

**Issue by sadiki-o** [supabase/supabase#5123]
Hey i wanna create an admin dashboard for my project where admin can create and delete users but when i run signup function, if there is an account logged it got signed out and the new created account is signed in instead, and when nobody is connected to the app the new created user sign in? 
is there any ideas how to prevent this behavior because i don't want the admin to log out and have to log in back, otherwise please suggest me a solution that might work

**Comment by kiwicopple** [comment]
Hey @sadiki-o - I'm not 100% sure I follow with the title + description. Could you please add some steps to replicate the issue you are facing? (or you can ask in the Discussions for more general help)

**Comment by kiwicopple** [comment]
The Auth server definitely allows multiple sessions with the same user. 

Can you share your code? Is it on github ? A small example will help us to help you ! At the moment I can't help you debug because you are describing a bug which doesn't exist - it's slightly more likely that there is a bug in your code

**Comment by sadiki-o** [comment]
Basically this is the function that create the new user : 
```
import { supabase } from "../../../initSupabase"

//create new user function
export const createUser = async (email, password) => {
    let { user, error } = await supabase.auth.signUp({
        aud: 'authenticated',
        role: 'authenticated',
        password,
        email,
        confirmation_sent_at: formatTime(),
        app_metadata: { provider: 'email' },
        user_metadata: {},
        created_at: formatTime(),
        updated_at: formatTime()
    })

    return {user, error}
}

function formatTime(){
    return new Date(Date.now()+(1000*60*(-(new Date()).getTimezoneOffset()))).toISOString().replace('T',' ').replace('Z','');
}
```

i tested out this function in a useEffect with [] argument just to see if it works but yes when it runs it drops the current user out and sign in the new created user .

**Comment by sadiki-o** [comment]
i tried to do the same just know just to confirm the behavior, i set a click event to a button which should run the function and the current user signed out automatically and the new one take place

**Comment by sadiki-o** [comment]
Sorry if i confused u at first with my explanation  :smile:

**Comment by kiwicopple** [comment]
```
aud: 'authenticated',
        role: 'authenticated',
        password,
        email,
        confirmation_sent_at: formatTime(),
        app_metadata: { provider: 'email' },
        user_metadata: {},
        created_at: formatTime(),
        updated_at: formatTime()
```

There should only be an email and password added here: https://supabase.com/docs/reference/javascript/auth-signin

> i tested out this function in a useEffect with

Perhaps you would like to use the signIn() method after they are created?

**Comment by mutiuoyekunle** [comment]
@kiwicopple  , yes exactly , i want to sign up user without returning that user session or automatically logging in the user.

**Comment by fazuniga** [comment]
It seems to me that @sadiki-o is trying to create users as an admin, so they can log in later.

Take a look at: https://supabase.com/docs/reference/javascript/auth-admin-createuser

**Comment by KatayR** [comment]
> It seems to me that @sadiki-o is trying to create users as an admin, so they can log in later.
> 
> Take a look at: https://supabase.com/docs/reference/javascript/auth-admin-createuser

This is not easy tho. Since you shouldn't use your service role key in your app, I tried to create an Edge Function, wrote the code below but it keeps giving "Status code: 546 - "code":"WORKER_LIMIT","message":"Worker failed to respond due to an error or resource limit (please check logs)" error.


```
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { verify } from 'https://deno.land/x/djwt@v3.0.1/mod.ts';

const supabaseUrl = Deno.env.get('SUPABASE_URL');
const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const jwtKey = Deno.env.get('JWT_SECRET_KEY'); // Use an environment variable for the JWT key

const supabaseAdmin = createClient(supabaseUrl, supabaseKey);

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest(request: Request) {
  if (request.method !== 'POST') {
    return new Response('Only POST requests are allowed', { status: 405 });
  }

  const authHeader = request.headers.get('Authorization');
  if (!authHeader) {
    return new Response('Authorization header is missing', { status: 401 });
  }
  const token = authHeader.replace('Bearer ', '');

console.log("Verifying JWT token");
  const isTokenValid = await verifyJwt(token, jwtKey);
  if (!isTokenValid) {
    return new Response('Invalid JWT token', { status: 401 });
  }

  const requestData = await request.json();
  const { email, password } = requestData;

  const { data, error } = await createUser(email, password);
  if (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  return new Response(JSON.stringify({ message: 'User created successfully', data: data }), {
    headers: { 'Content-Type': 'application/json' },
  });
}

async function createUser(email: string, password: string) {
  const { data, error } = await supabaseAdmin.auth.api.createUser({
    email: email,
    password: password,
  });

  if (error) {
    console.error('Error creating user:', error);
    return { error };
  }

  return { data };
}

async function verifyJwt(token: string, key: string): Promise<boolean> {
  try {
    const payload = await verify(token, key);
    console.log("JWT payload:", payload);
    return true;
  } catch (error) {
    console.error('JWT verification error:', error);
    return false;
  }
}
```

 When you check the logs, there are no errors and it says "Event message
Event loop completed".

When you check the "Invocations" tab, you see Error 546 but the info next to it doesnt help at all:
```
Log ID
b7580ced-a817-4a7e-b2c0-1364e3299eb1

Log Timestamp (UTC)
2023-11-11T14:00:11.101Z

Log Event Message
POST | 546 | https://gjisevsmqbjkhpxuemgi.supabase.co/functions/v1/create-user

Log Metadata
[
  {
    "deployment_id": "gjisevsmqbjkhpxuemgi_451b3aad-bc51-4644-8cba-6941361d7980_13",
    "execution_time_ms": 245,
    "function_id": "451b3aad-bc51-4644-8cba-6941361d7980",
    "project_ref": "gjisevsmqbjkhpxuemgi",
    "request": [
      {
        "headers": [
          {
            "accept": null,
            "accept_encoding": "gzip",
            "connection": "Keep-Alive",
            "content_length": "47",
            "cookie": null,
            "host": "gjisevsmqbjkhpxuemgi.supabase.co",
            "user_agent": "Dart/3.1 (dart:io)"
          }
        ],
        "host": "gjisevsmqbjkhpxuemgi.supabase.co",
        "method": "POST",
        "pathname": "/functions/v1/create-user",
        "port": null,
        "protocol": "https:",
        "search": null,
        "url": "https://gjisevsmqbjkhpxuemgi.supabase.co/functions/v1/create-user"
      }
    ],
    "response": [
      {
        "headers": [
          {
            "content_length": "126",
            "content_type": "application/json",
            "date": "Sat, 11 Nov 2023 14:00:11 GMT",
            "server": "cloudflare",
            "vary": "Accept-Encoding",
            "x_sb_edge_region": "eu-central-1",
            "x_served_by": "supabase-edge-runtime"
          }
        ],
        "status_code": 546
      }
    ],
    "version": "13"
  }
]
```

**Comment by fazuniga** [comment]
I've done it on some NextJS projects, on a protected API route

**Comment by sarmad-m** [comment]
Hi, did you find a solution to this behaviour of automatic admin logout  after creating new account ?

**Comment by KatayR** [comment]
> Hi, did you find a solution to this behaviour of automatic admin logout after creating new account ?

I had to use a "dirty" solution:

```
await supabase.auth.signUp(
        email: newUserEmail,
        password: newUserPassword,
      );

      // logout supabase
      await supabase.auth.signOut();

      // login again with supabase
      // get admin "email" and "password" from shared preferences
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? email = prefs.getString('email');
      String? password = prefs.getString('password');

      final AuthResponse res = await supabase.auth.signInWithPassword(
        email: email,
        password: password!,
      );
```

**Comment by williamGarcia99x** [comment]
I'm having a similar problem. When I call auth.signUp, the session gets updated with that user's data meaning they get automatically signed in. What I want to do is to redirect users to login after they sign up. I do this with the function below. The problem is that the Navigation bar which has a Logout button that renders when the session != null renders for brief second after calling signUp but before calling signOut. Is there a way to prevent the default behavior of the session data getting returned after signUp? 

RegistrationForm.jsx
`async function handleRegister(event) {
    event.preventDefault();

    //If either of these attributes is blank then don't proceed
    if (!email || !password || !role || !user_name || !organization_name)
      return;
    try {
      dispatch({ type: "SET_LOADING", payload: true });
      const userData = {
        email,
        password,
        options: {
          data: {
            role,
            user_name,
            organization_name,
          },
        },
      };
      const { error } = await signUp(userData);

      if (error) {
        throw new Error(error.error_description || error.message);
      } else {
        //if successfully logged in, then ...

        //supabase logs in a user when they finish registering an account. If we are forcing the user to login after registering an account, then they must be signed out
        await signOut();

        alert("Successfully Registered an Account!");

        navigate("/login");
      }
    } catch (message) {
      alert(message);
    } finally {
      dispatch({ type: "SET_LOADING", payload: false });
    }
  }`
  
  useAuth.jsx
  `
  export function useAuth() {
  const [session, setSession] = useState(null);
  //important to initialize loadingSessionData to true since the session data is fetched after the component mounts.
  const [loadingSessionData, setLoadingSessionData] = useState(true);

  useEffect(() => {
    //When the App component mounts, it's possible that there is an already existing session. Check with supabase and initalize the React sesion state with result of auth.getSession(). This behavior ensures that the user's authentication status persists across page refreshes and accross browser sessions (e.g. users closes tab or browser and opens it again)
    supabase.auth.getSession().then(function (responseObj) {
      const {
        data: { session },
      } = responseObj;
      setSession(session);

      setLoadingSessionData(false);
    });

    //Sets up an even listener that listens for changes to authentication state. auth.onAuthStateChange will trigger the execution of the callback function whenever supabase detects a change in the user's authentication state. This is a type of user subscription
    const { data } = supabase.auth.onAuthStateChange((_event, session) => {
      console.log(_event);
      setSession(session);
    });

    // call unsubscribe to make sure authentication event listener doesn't keep running after unmount
    return () => data.subscription.unsubscribe();
  }, []);

  return [session, loadingSessionData];
}
  `
