### ISSUE TITLE
Update Auth0 documentation 

### ISSUE THREAD

**Issue by mrchristophy** [supabase/supabase#5127]
Hi, I've been trying to get Auth0 integration working following this guide: 
https://supabase.com/docs/guides/integrations/auth0

It all goes well until I enable the RLS. I have added the function and the policy multiple times, but for fetching I always get an empty array, and for posting I get a 401 error. The user id is populated in the column, and I'm not sure how I can debug where the problem lies.

I've noticed that when I save the policy the code changes from "auth.user_id() = user.id" to "(user_id() = user.id)" - is this normal?

If I disable RLS then I can fetch all the todos, and inserting works as well which includes the user_id from Auth0 - so in general it works, but seems like the policy part of it is not working somehow.

Thanks for any help!

**Comment by GaryAustin1** [comment]
That article seems outdated without doing much research.  
Postgrest now requires a different format for getting info from headers as of 9.x.
https://postgrest.org/en/stable/api.html#http-context shows the new jwt format.

**Comment by mrchristophy** [comment]
@GaryAustin1 wow I changed "claim" to "claims" and it works! Thanks!
