### ISSUE TITLE
Write examples for all Postgrest API methods

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#513]
such as: https://supabase.io/docs/postgrest/client/from

including all filters:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/458736/104444906-dff6d500-55b1-11eb-8b4c-15ae14aea152.png">

**Comment by DanielChuDC** [comment]
Hi @awalias , I would like to help this issue.

Can I commit multiple filter documentation instead of all of them ?

**Comment by awalias** [comment]
Hi @DanielChuDC help would be greatly appreciated, just to clarify the task,

we need to add examples to [postgrest.yml ](https://github.com/supabase/supabase/blob/master/web/spec/postgrest.yml)

Here's an example of the format from gotrue.yml: https://github.com/supabase/supabase/blob/67cb034987622153513b129896e285e018756097/web/spec/gotrue.yml#L68

Then run [`npm run gen:postgrest`](https://github.com/supabase/supabase/blob/67cb034987622153513b129896e285e018756097/web/package.json#L11) from within the [web dir](https://github.com/supabase/supabase/tree/master/web). This will autogenerate the markdown files 👍

**Comment by kiwicopple** [comment]
Also you should be able to use a lot of the example from the [supabase.yml](https://github.com/supabase/supabase/blob/master/web/spec/supabase.yml) file!

**Comment by DanielChuDC** [comment]
Thanks @awalias and @kiwicopple! I found out from the [wiki](https://github.com/supabase/postgrest-js/wiki/07.-General-Filters), it is full of examples in js. Should I make a transfer from there?

- example
### neq()
Not equal.
```js



let { body: countries } = await client
    .from('countries')
    .neq('name', 'New Zealand')
    .select('*')


```

**Comment by kiwicopple** [comment]
Oops that wiki is from pre-1.0 so the code isn't correct. The best way is to copy the relevant code from `supabase.yml` to `postgrest.yml`, but change "supabase" to "postgrest". For example this line:

https://github.com/supabase/supabase/blob/fc691e5c0e86fcba6cd10da75a79726dafeb3c6b/web/spec/supabase.yml#L425

```js
          const { data, error } = await supabase
            .from('countries')
            .select(`
              name,
              cities (
                name
              )
            `)
```

would be 


```js
          const { data, error } = await postgrest
            .from('countries')
            .select(`
              name,
              cities (
                name
              )
            `)
```

The supabase-js library just wraps postgrest-js, so the functions are the same

**Comment by DanielChuDC** [comment]
@awalias @kiwicopple Please let me know if anything need to improve on! The API `from`, `fts`, `plfts`, `phfts` and `wfts` I did not touch it.

**Comment by kiwicopple** [comment]
Hi @DanielChuDC you did an amazing job: https://supabase.io/docs/postgrest/client/postgrest-client

Thanks for your contribution 🔥

**Comment by awalias** [comment]
wow epic work @DanielChuDC thanks

**Comment by DanielChuDC** [comment]
Happy to help!
