### ISSUE TITLE
Querying a the database using rpc to call a function returns empty array

### ISSUE THREAD

**Issue by rxmii4269** [supabase/supabase#5137]
### Discussed in https://github.com/supabase/supabase/discussions/5136

<div type='discussions-op-text'>

<sup>Originally posted by **rxmii4269** January 24, 2022</sup>
I created a function on postgresql and when querying this function using rpc() an empty array is returned even when data is there. Calling the function in the SQL editor does indeed return data, so it is confirmed that the function works as it should.
Any help is much appreciated.

`CREATE OR REPLACE FUNCTION public.tweets_of_who_i_follow(uid uuid) RETURNS TABLE(id bigint, user_id uuid, created_at timestamp with time zone, description text, has_photo boolean, photo_name character varying, visibility character varying) AS $$
 BEGIN
	RETURN QUERY
	SELECT tweets.*
 	FROM tweets  
 	INNER JOIN followers ON tweets.user_id = followers.user_id
 	WHERE followers.user_id = uid;
	END;	
$$ LANGUAGE plpgsql;`
![image](https://user-images.githubusercontent.com/49266906/150813567-0264272c-d432-474e-81e1-5324a6e921af.png)
</div>

**Comment by WesleyBLDC** [comment]
Have you fixed this problem? If yes, whats the solution?

**Comment by PatrickMogensen** [comment]
Hello i have the same issue. Any suggestions?

**Comment by grandalf6** [comment]
I have the same issue.

**Comment by knkp** [comment]
Should this issue be closed? I'm having the same issue and it only works when RLS is disabled on all tables as suggested above.
