### ISSUE TITLE
CSS not properly applied for sidebar categories

### ISSUE THREAD

**Issue by ptrhck** [supabase/supabase#5138]
# Bug report

## Describe the bug

The sidebar categories are displayed wrong.

## To Reproduce

I have cloned the repo and run the production build as described in `/web`

## Expected behavior

On https://supabase.com/docs/ all categories (Overview, Quickstarts,...) look different and are not collapsable.

## Screenshots

![image](https://user-images.githubusercontent.com/26689889/150818493-7105f15c-54de-4e0f-afd5-db540752418c.png)

## Additional context

Can someone reproduce this?

**Comment by Isaiah-Hamilton** [comment]
@ptrhck Is supabase on local machine update to date with supabase origin, because I don't seem to have this problem, and can't reproduce it.

**Comment by ptrhck** [comment]
@Isaiah-Hamilton Sorry, I made a small mistake and was running on the latest docusaurus version `2.0.0-beta.14`, where this bug would exist. It might be related to this [change](https://github.com/facebook/docusaurus/pull/5642), but I could not figure out what needs to be changed in custom.css to run it with the latest docusaurus version. Any idea?

**Comment by Isaiah-Hamilton** [comment]
@ptrhck I can't seem to replicate this bug that you are talking about. I updated to docusaurus version `2.0.0-beta.14` just like you and the site built fine, and see no difference. I would try recloning the supabase repo and downloading the npm packages without updating.

**Comment by ptrhck** [comment]
That is what I did. Clone and install as is, works fine. Only updated docusaurus, nothing else changed and then this bug occured.

**Comment by ptrhck** [comment]
I have rebuild the container I was using and then it worked. It still looks a bit strange as occured again. I have created a test [repository ](https://github.com/ptrhck/docusaurus-supabase) using the [latest ](https://docusaurus.io/docs/next#fast-track) docusaurus version and only changed the `custom.css` to the one this repo uses. Here, the bug still exists. Is there any other configuration except the `custom.css` that adds the styling to the categories?
