### ISSUE TITLE
Delete project modal doesn't submit on enter in Studio

### ISSUE THREAD

**Issue by leerob** [supabase/supabase#5139]
# Bug report

## Describe the bug

When I press enter to submit the delete project form, it does not work.

## To Reproduce

<img width="550" alt="CleanShot 2022-01-24 at 11 11 04@2x" src="https://user-images.githubusercontent.com/9113740/150831010-637acfd4-70b4-4188-adc7-2be5c18e510e.png">

## Expected behavior

The form to submit on enter 😄

**Comment by kiwicopple** [comment]
dark patterns to keep you hooked @leerob

**Comment by FatumaA** [comment]
yes @kiwicopple I noticed this too. Can I attempt this one?

**Comment by leerob** [comment]
You could either:

1. Wrap this section in a `form` and change this button to `type="submit"`
2. Handle `onKeyPress` and look at the key pressed to check for enter

1 is probably easier. [Here's the code](https://github.com/supabase/supabase/blob/636f17dff6e946fa3f058772579d36f1912ba463/studio/pages/project/%5Bref%5D/settings/general.tsx#L235).

**Comment by kiwicopple** [comment]
would love your help @FatumaA ! I think @MildTomato might have some ideas here too (it should probably be build directly into the modal https://ui.supabase.com)

**Comment by MildTomato** [comment]
Yep, we've got a Form component in Supabase UI now.
Although I've already started work on updating all our Modals to use the new Form component.
It's not built 'in the modal' but we wrap the contents of the Modal with the Form component.

It's quite a big branch with a lot of changes in, it might take a while to get into prod. Hopefully by end of this week.

In the meantime, @FatumaA feel free to PR any quick fixes though while I'm working on the refactor.

**Comment by FatumaA** [comment]
@MildTomato Hey, 
It seems you can't delete the default project and you can't create a new project on the local set up. I'm not sure how to test locally in this case. I did see that the delete project function fired  as was but gave me a 404 error in console. This fired as well when I wrapped the modal contents in a form like so: 
`<Modal
        visible={isOpen}
        onCancel={toggle}
        title={'Are you absolutely sure?'}
        icon={<IconAlertCircle background={'red'} />}
        hideFooter
        size="medium"
        closable
      >
        <form onSubmit={handleDeleteProject}>
        <Typography.Text>
          <p className="text-sm">
            This action <Typography.Text strong>cannot</Typography.Text> be undone. This will
            permanently delete the <Typography.Text strong>{project?.name}</Typography.Text> project
            and all of its data.
          </p>
          <p className="text-sm">
            Please type <Typography.Text strong>{project?.name}</Typography.Text> to confirm.
          </p>
        </Typography.Text>
        <Input
          onChange={(e) => setValue(e.target.value)}
          value={value}
          className="w-full"
          placeholder="Type the project name in here "
        />
        <Button
          htmlType='submit'
          // onClick={handleDeleteProject}
          loading={loading}
          disabled={project?.name !== value || loading}
          size="small"
          block
          danger
        >
          I understand, delete this project
        </Button>
        </form>
      </Modal>`
But did not give any error and did not seem to delete the default proectj either - prob because It can't be deleted? 😁 
Any idea how to go about this given the restrictions?

**Comment by MildTomato** [comment]
@FatumaA ah yes, it's because it's a 'hosted' only feature. Some of the infrastructure required to run it locally is only available to the supabase team.

I'll pick this one up soon, we've been meaning to move a lot of our modals over to using @supabase/ui Form component as well.

**Comment by MildTomato** [comment]
Our org deletion modal has the correct setup for this to follow along to. 

It also has validation on the input with an error message

![Screenshot 2022-05-05 at 12 33 33 PM](https://user-images.githubusercontent.com/8291514/166864016-ab8aa8b1-99ef-4a48-b276-2ad37d204742.png)
