### ISSUE TITLE
Cannot delete user in Authentication panel, violates foreign key constraint "users_id_fkey"

### ISSUE THREAD

**Issue by ctjlewis** [supabase/supabase#516]
## Describe the bug
I am unable to delete a user.

## Steps to reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `Authentication > Users`
2. For any user, go tap `... > Delete`, confirm deletion
3. See error

## Expected behavior

The user to be deleted.

## Screenshots
![image](https://user-images.githubusercontent.com/1657236/104553235-ef047400-55ff-11eb-90d3-b11eccd089a7.png)

## System information
Chrome on Ubuntu 20.04

**Comment by YashKandalkar** [comment]
Do you have any public tables which has a column referencing the id from auth.users table?
If you do then try deleting that user from the public tables first (Table editor) and then from the auth.users table.

**Comment by ctjlewis** [comment]
There was a `users` table that contained a reference to a user. I thought the `Authentication > Users` panel just used a GUI to display the `users` table but they were separate.

Closing since this is not really a bug.
