### ISSUE TITLE
Improve DEVELOPERS.md

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#5160]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/DEVELOPERS.md

## Describe the problem

The docs on getting started with contributing to supabase are very basic and need some work.

## Describe the improvement

Add links to docs, improve getting started docs, add links to where people can ask for help, etc.

**Comment by yeganathan18** [comment]
What kind of improvements? a bit more information would be super helpful.

**Comment by Isaiah-Hamilton** [comment]
@yeganathan18 For example, things like how to open Issues, Pull Request. Give a better description / explain further [development setup](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#development-setup), [installing dependencies](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#installing-dependencies), [choosing directory](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#choosing-directory), etc. Link to the [supabase discord](https://discord.supabase.com) and [Github discussions](https://github.com/supabase/supabase/discussions). There are other things that can be improved, but for now this is a great start to improving `DEVELOPERS.md`.

**Comment by yeganathan18** [comment]
@Isaiah-Hamilton Cool will work on it 👍🏻
