### ISSUE TITLE
Self-hosting (docker) + ngrok + OAuth

### ISSUE THREAD

**Issue by richardwu** [supabase/supabase#5163]
# Bug report

## Describe the bug

I am currently self-hosting Supabase via Docker, with a NextJS app. 

I have implemented [Google OAuth](https://supabase.com/docs/guides/auth/auth-google) and I have confirmed everything works properly while using `localhost`.

Here are how the services are mapped to ports:
```
Kong: localhost:8000 (default)
Studio: localhost:3000 (default)
NextJS app: localhost:3001 
```

I have set my callback URLs to `localhost:8000/auth/v1/callback`. I then call
```
const { user, session, error } = await supabase.auth.signIn({ provider: 'google' });
```
in NextJS.

I would like to enable a public URL via `ngrok` such that my NextJS app runs at `https://<subdomain>.ngrok.io`. When I attempt to sign-in from `https://<subdomain>.ngrok.io`, a callback is indeed made to `localhost:8000/auth/v1/callback`, but Kong redirects back to `localhost:3000` (Studio) instead of `https://<subdomain>.ngrok.io`. I have also set `ADDITIONAL_REDIRECT_URLS=https://<subdomain>.ngrok.io` in  [`docker-compose.yml`](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) and tried to explicitly pass in `redirectTo`:
```js
const { user, session, error } = await supabase.auth.signIn({ provider }, {redirectTo: "https://<subdomain>.ngrok.io"});
```
to no avail.

## To Reproduce

See above.

## Expected behavior

I expect Kong to redirect back to `https://<subdomain>.ngrok.io` where OAuth was initiated.

## Screenshots

n/a

## System information

- OS: Windows (WSL)
- Browser (if applies): chrome
- Version of supabase-js: 1.29.3
- Version of Node.js: 16.13.0

**Comment by kangmingtay** [comment]
Hey @richardwu, I'm unable to reproduce the example above. As a sanity check, did you try visiting `http://localhost:8000/auth/v1/authorize?provider=google&redirect_to="https://<subdomain>.ngrok.io"` and check if the redirection succeeds?

**Comment by richardwu** [comment]
Hey @kangmingtay, it seems to be working now, I must have forgotten to restart the docker containers when I updated `ADDITIONAL_REDIRECT_URLS`!
