### ISSUE TITLE
Unable to edit email templates when using the Local version of Studio

### ISSUE THREAD

**Issue by scopethis** [supabase/supabase#5188]
# Bug report
Unable to edit email templates when using the Local version of Studio

## Describe the bug
When looking at the templates page, all `textarea` fields do not respond to input in the same way as the online version of Studio. The markup shows each field set to `readonly`. I don't know if this is by design or something i've done (not done).

## To Reproduce

- Include studio and port number in your config.json file
- stop/start supabase
- visit the studio url: localhost:3000/54321 (whatever yours is)
- Go to the auth/templates page
- Click into any field
- Adding/editing text is not possible

## Expected behavior
Adding/editing text should be possible

## System information

OS: macOS. M1 Chip. 16GB ram
Browser n/a
Version of supabase-cli: 0.16.0
Version of studio: latest (pulled down on Jan 26 )

## Additional context

As mentioned above, I don't know if they're locked down for a reason, if they are could someone tell me why please?
I have already created a [discussion about it](https://github.com/supabase/supabase/discussions/5179), but not sure if that will get looked at by anyone.

Thanks.

**Comment by scopethis** [comment]
Am I right in assuming it's disabled because:

> It is not intended for managing the deployment and administration of projects - that's out of scope.

and

>As such, the features exposed on Studio for existing deployments are limited to those which manage your database:
- Table & SQL editors
    - Saved queries are unavailable
- Database management
    - Policies, roles, extensions, replication
- API documentation

Should this list also include "editing auth email templates"?

**Comment by scopethis** [comment]
So it looks like this is intentional as it's being blocked (for the moment?)

https://github.com/supabase/supabase/blob/5c52401734d056b2abd021dfd17d8d47815f28d1/studio/components/interfaces/Authentication/Templates.tsx#L67

Will email templates ever be editable outside of the hosted version?

**Comment by kiwicopple** [comment]
Hey @scopethis - correct. At the moment the way to edit these templates it so add them as [env vars](https://github.com/supabase/supabase/blob/3aabe4f97dbbf59ed7b4c1e498f9e88a198a85ae/docker/docker-compose.yml#L44)

You can see all the config params available to you here: https://github.com/supabase/gotrue

I'll close this one for now, but feel free to drop comments (or jump into the Discusssions)
