### ISSUE TITLE
Bugged email verification URL

### ISSUE THREAD

**Issue by arpitdalal** [supabase/supabase#5213]
# Bug report

## Describe the bug
After signing up with an email and password, a verification URL is sent to the email address, and when clicking on the link provided in that verification email, it redirects to `http://localhost:3000/?#access_token=...` and I am trying to parse that URL to access the `access_token` and `refresh_token` to use them to create a user session. And this all happens in the server and as the redirected URL mentioned before has a `#` in it after the `?`, the parsed URL doesn't have `access_token` and `refresh_token` in the `searchParams` and the worse thing is that if I access the URL using `request.url`, the part after `#` is not even present, otherwise, I could've replaced `?#` with just `?`.
I have set `http://localhost:3000/?` as my `Site URL` and `Additional Redirect URLs` in the auths settings panel in Supabase admin.

## To Reproduce
I tried using one of the examples to test if this is the behavior that every app has or just mine. I tried the [auth-js example](https://auth-vanilla-js.vercel.app/) and it also has the same behavior, after signing up, I clicked on the verification URL and it took me to `https://facebook.com/#access_token...`, see the `#`, I think it should be `?` instead.

## Expected behavior
Can get the URL parameters. Maybe `#` should be replaced with `?`

## Screenshots
![ss4](https://user-images.githubusercontent.com/61059807/151629928-b697fc24-c270-4e3a-8d61-186238c63d03.png)

## System information

- OS: Ubuntu 20.04
- Browser (if applies) chrome
- Version of supabase-js: 1.29.1
- Version of Node.js: 14.17.4

## Additional context
I am using [remix](https://remix.run) here. And doing everything on the server-side.

**Comment by GaryAustin1** [comment]
Not a bug...
Many reports and answers on this.
https://github.com/supabase/supabase/issues/1698

**Comment by arpitdalal** [comment]
Ah okay! Thanks @GaryAustin1 
I tried to find this in the closed issues but was looking for the `#` symbol and not for its synonyms.

**Comment by GaryAustin1** [comment]
Yeah, I knew there would be some, and lucked out and picked "hash" first time to get you an example...
