### ISSUE TITLE
Unable to expose "auth" schema

### ISSUE THREAD

**Issue by Timonzimm** [supabase/supabase#5249]
# Bug report

## Describe the bug

I want to expose my `auth` schema to Supabase Javascript client but I am not able to do so. I get the following error: `The schema must be one of the following: public, storage`

I follow this procedure, unsucessfuly: https://supabase.com/docs/reference/javascript/initializing#api-schemas

The bug is that `auth` is not selectable  in "Settings > API > Schema".

See hereafter:
![image](https://user-images.githubusercontent.com/5808319/151813528-5af05483-2f01-4a3f-9cf0-fb89fc3c6295.png)

As you can see, I even tried to add it to "Extra search path", also unsuccesful.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to "Settings > API > Schema"
2. Unable to add `auth` next to `public` and `storage`

## Expected behavior

Being able to add `auth` to that list so I can then:
```javascript
const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key', { 
  schema: 'auth' 
})
```

## Screenshots

![image](https://user-images.githubusercontent.com/5808319/151813528-5af05483-2f01-4a3f-9cf0-fb89fc3c6295.png)

## System information

- OS:Ubuntu
- Browser: Chrome (also buggy on Firefox)

## Additional context

I tried two things:
- Restart my server (multiple times)
- Run the following SQL query:
```sql
NOTIFY pgrst, 'reload schema';
```

**Comment by GaryAustin1** [comment]
Not something Supabase wants done for security reasons.
You should use an rpc function (with security definer if need be) to do want you want, or make a copy of auth data you want in a public table (covered in the Supabase docs).

**Comment by kiwicopple** [comment]
Thanks for answering this one @GaryAustin1 🙏 

@Timonzimm - I will close this one but feel free to comment or open a Discussion if you need more info
