### ISSUE TITLE
Search Funtionality , Some Results doesn't have single page and return 404 Page Not Found Error

### ISSUE THREAD

**Issue by Ali-A-Koye** [supabase/supabase#5267]
# Bug report
on the website of supabase.com , if you try to search for "know-how-to-secure-their-database-permissions-at-the-table-column-row-level" , you will see a result but when you click on it ->> its 404 and not found 

## Describe the bug
the website  search functiality seems to have some caching process that even deleted Sections of the website are in the result of the search

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to supabase.com
2. Click on Search button and search for "know-how-to-secure-their-database-permissions-at-the-table-column-row-level"
3. Click on the only result

## Expected behavior
it should open the single page instead of throwing 404 error

## Screenshots
![image](https://user-images.githubusercontent.com/66186390/151982461-996fd57f-a56c-438e-b4c7-1281ceb63ee3.png)

## System information

- OS:Windows 10
- Browser chrome

**Comment by kiwicopple** [comment]
this is a valid bug, but we also have this one: https://github.com/supabase/supabase/issues/4317

I'll close in favor of the original 👍
