### ISSUE TITLE
Timestamp editor handles input poorly

### ISSUE THREAD

**Issue by Kilian** [supabase/supabase#5270]
# Bug report

## Describe the bug

The timestamp editor is very quick to clear out the values while you're typing
video:  https://user-images.githubusercontent.com/41970/152002120-685d9f93-4171-4771-9d60-2ed683464735.mp4

## To Reproduce

see video

## Expected behavior

I can edit the timestamp and it doesn't reset the entire timestamp.

## Screenshots

n/a

## System information

- OS: Ubuntu 18.04
- Browser: Firefox 96
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by kiwicopple** [comment]
I think this could be related to : https://github.com/supabase/grid/issues/92

We could probably move this over to the grid repo, but I'll leave it here for a bit so that it gets some visibilty. We'd love help with the Grid library in case anyone wants to contribute

**Comment by joshenlim** [comment]
update: this is currently being worked on!

**Comment by joshenlim** [comment]
hey all! this should now be fixed by https://github.com/supabase/supabase/pull/6766

will close this ticket but feel free to open if the issue still persists! 🙏
