### ISSUE TITLE
Upsert a file

### ISSUE THREAD

**Issue by PaulRosset** [supabase/supabase#5292]
# Bug report

## Describe the bug

I'm trying to upsert a file through the storage API provided by `"@supabase/supabase-js": "^1.29.4",`.

However, when I try to upload with the `upsert` option set to true, I get an error coming from the server.

I'm using the update/upload method that way:

```js
supabase.storage
.from("test")
.update("avatar", file, {
   cacheControl: "3600",
   upsert: true,
 });
```

or

```js
supabase.storage
.from("test")
.upload("avatar", file, {
   cacheControl: "3600",
   upsert: true,
});
```

## To Reproduce

I created a repository when I explain the different commands I run here:

https://github.com/PaulRosset/supabase-repro-update-storage

## Expected behavior

I expect that the file get uploaded and replaced if it exists on the remote server.

## System information

- OS: Ubuntu
- Browser (if applies): All
- Version of supabase-js: 1.29.4
- Version of Node.js: 14

**Comment by GaryAustin1** [comment]
Your update policy needs a using and with check or just a using.

create policy "UPDATE OBJECT"
  on storage.objects for update
  with check ( true );

needs to be
using (true); for both object and bucket.

**Comment by PaulRosset** [comment]
Thank you for your answer.

From what I've done and if I understand correctly, I'm already doing it, right?

here:
https://github.com/PaulRosset/supabase-repro-update-storage/blob/main/transaction.sql

**Comment by PaulRosset** [comment]
Thanks a lot! It actually works!
