### ISSUE TITLE
Allow redirecting to subdomains

### ISSUE THREAD

**Issue by quinnj** [supabase/supabase#5294]
I'm trying to structure my app to utilize subdomains for specific customers (google.myapp.com, facebook.myapp.com, etc.), but I'm finding that doesn't scale with the current redirect functionality in the email signup, magic links, password reset, etc.

A couple of ideas:
  * allow programmatically updating the exact redirect list, so I can add new allowed subdomains when they sign up
  * Checkbox to allow any subdomain of allowed redirect urls
 
I thought I might be able to work-around this by using the `generateLink` functionality, but it turns out that's just the underlying functionality of the signUp/resetPassword/magicLink flows. So one other idea is exposing a `generateJWT` function for the Auth server where I could generate an access token, return to the frontend and use setAuth to login a user. I'm aware I can probably already do this myself using the JWT secret available in the dashboard, but then I have to go remember how to generate JWTs in node and make sure that's all working correctly. It'd be handy if there was a builtin server function for this.

**Comment by quinnj** [comment]
Ok, so chatted with a friend who suggested a pretty good solution that works currently. Instead of trying to redirect to the subdomain directly, I can pass something like `redirectTo: 'https://localhost:3000/recovery?instance=testsubdomain'` to the various `signUp`/`resetPassword` supabase client calls. Then in my application, I have a router set up at the highest level that detects the `instance=testsubdomain` and redirect the location to `https://testsubdomain.localhost:3000/recovery`. Coincidentally, this ends up being useful while integrating with Stripe, which has similar "allowed redirect url" as a part of their api.

Feel free to close this, since I'm satisfied with this solution on my end.

**Comment by awalias** [comment]
will be solved by https://github.com/supabase/supabase/issues/4808 as well 👍
