### ISSUE TITLE
supabase image on auth page not changing from dark to light

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#5297]
# Bug report

## Describe the bug

On the auth page, the supabase image doesn't change from light to dark.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/auth](https://supabase.com/auth)
3. Scroll down to React Auth / Auth component
4. switch to light mode

## Expected behavior

The supabase image change to light and dark.

## Screenshots

https://user-images.githubusercontent.com/70828596/152271218-6e1d4a3b-4d0c-430e-b1e0-ef7e49bc6d2d.mov

## System information

- OS: macOS
- Browser (if applies) Firefox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Anyone can take this issue.

**Comment by arpitBhalla** [comment]
@Isaiah-Hamilton I can work on it

**Comment by Isaiah-Hamilton** [comment]
@arpitBhalla all yours

**Comment by Sync271** [comment]
This seems to be more of a 'flow of props' issue than just wrong SVG implementation.
Here, darkMode is received as a prop and if that is undefined, it always ends up being false so you end up getting dark-themed logo no matter what.
https://github.com/supabase/supabase/blob/90c11c79522d759b14dc46eed1cd48f12a8a061b/www/components/AuthWidget/AuthComponentExample.tsx#L93-L97

**Comment by Anikets08** [comment]
is the issue solved

**Comment by Isaiah-Hamilton** [comment]
> is the issue solved

not yet

**Comment by zainabmirkar** [comment]
Hello!! can I help in solving this issue ???  I have no prior experience but I am eager to contribute

**Comment by Isaiah-Hamilton** [comment]
@zainabmirkar Go for it 🚀

**Comment by rksingh2001** [comment]
Can i take up this issue if no one is currently working on it @Isaiah-Hamilton ?

**Comment by louis-27** [comment]
Hi @Isaiah-Hamilton 👋, I just made a PR to help solve this light mode issue. Maybe you can take a look at it?

**Comment by rksingh2001** [comment]
@louis-27 I was working on this issue, you should have asked before :|

**Comment by louis-27** [comment]
my bad, sorry @rksingh2001 forgot to ask if anybody is still working on this issue
