### ISSUE TITLE
Dart Inner Join Filter

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#5298]
# Feature request
I feel it's a basic need to be able to filter an inner join. In the words of your documentation:
If you want to filter a table based on a child table's values you can use the !inner() function. For example, if you wanted to select all rows in a message table which belong to a user with the username "Jane":

## Is your feature request related to a problem? Please describe.
Your Documentation says not yet implemented
https://supabase.com/docs/reference/dart/select#filtering-with-inner-joins

## Describe the solution you'd like

To implement this feature.

## Describe alternatives you've considered

GraphQL

## Additional context

This seems like a must have feature and surprised it's not available. Having it in the documentation as a teaser stings because there is no mention of when it will be implemented.

**Comment by kiwicopple** [comment]
hey @jtkeyva - perhaps you can open this one [here](https://github.com/supabase-community/postgrest-dart) for visibilty with the Dart maintainers?

**Comment by jtkeyva** [comment]
@kiwicopple sure will do
