### ISSUE TITLE
Noisy studio tests

### ISSUE THREAD

**Issue by Ziinc** [supabase/supabase#5301]
# Chore
To reduce warnings/logs emitted during studio tests.

## Describe the chore

This error is related to the radix setup for missing apis in jsdom, can be found in `studio/setup.radix.ts`, and it is emitted as recharts is attempting to determine the size of the container (but it is zero because of jsdom). Need to mock the missing apis.
```
 console.warn
      The width(0) and height(0) of chart should be greater than 0,
             please check the style of container, or the props width(100%) and height(100%),
             or add a minWidth(undefined) or minHeight(undefined) or use aspect(undefined) to control the
             height and width.

      at warn (node_modules/recharts/lib/util/LogUtils.js:26:17)
      at renderChart (node_modules/recharts/lib/component/ResponsiveContainer.js:139:24)
      at node_modules/recharts/lib/component/ResponsiveContainer.js:176:7
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:17044:20)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19098:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23940:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)

```

This error is due to incorrect implementation of a Dropdown component, related to this issue https://github.com/supabase/ui/issues/309

```
 console.error
      Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
          at button
          at RenderedButton (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/ui/dist/cjs/components/Button/Button2.js:96:5)
          at span
          at /Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/ui/dist/cjs/components/Button/Button2.js:14:5
```

**Comment by Isaiah-Hamilton** [comment]
> This error is due to incorrect implementation of a Dropdown component, related to this issue [supabase/ui#309](https://github.com/supabase/ui/issues/309)
> 
> ```
>  console.error
>       Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
>           at button
>           at RenderedButton (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/ui/dist/cjs/components/Button/Button2.js:96:5)
>           at span
>           at /Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/ui/dist/cjs/components/Button/Button2.js:14:5
> ```

@Ziinc Do you know where this is located, I can't seem to find it?

**Comment by MildTomato** [comment]
You need to use Dropdown like this...

```js
<Dropdown {...props}>
  <Button as="span">...</Button>
</Dropdown>
```

Dropdown already providers the button tag with correct aria labels, so if you use a `<Button>` for the trigger, you need to set `as` to something like `"span"`
