### ISSUE TITLE
Files with long names dont fit in storage dashboard

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#5308]
# Bug report

## Describe the bug

Files with long names don't fit in the storage dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [app.supabase.io/project/[ref]/storage/buckets](https://app.supabase.io/project/[ref]/storage/buckets)
2. Click on create new bucket
3. Add a new file with a long filename

## Expected behavior

to have the file name be scrollable or something better.

## Screenshots

<img width="1280" alt="Screen Shot 2022-02-03 at 7 42 09 PM" src="https://user-images.githubusercontent.com/70828596/152453666-773be0ad-5c71-40a7-be7b-ff84d81e8aa3.png">

## System information

- OS: macOS
- Browser: Firefox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

cc/ @joshenlim @Ziinc sorry to mention you but I can't work on it.

**Comment by yousefakiba** [comment]
I wouldn't mind working on this, I can recreate the bug on Windows with Firefox. Is making the name scrollable the way I should handle this?

Also just want to confirm, its this page right? 

[https://github.com/supabase/supabase/blob/94fdf5cff2751f61993a7df4daf7090d535b6b02/studio/components/to-be-cleaned/Storage/StorageExplorer/PreviewPane.js](url)

**Comment by Ziinc** [comment]
thanks @yousefakiba , would be appreciated. Yes it is the PreviewPane component. I'll let @joshenlim give his inputs on design, but imo would make more sense have it copy-able, as no one in their right mind is going to memorize the string and scan their bucket for it. Clipping the overflow and having a copy-paste button next to it might work. Or having it as a Input with `copy` prop.

**Comment by Ziinc** [comment]
you can check the `developers.md` file and the `studio/readme.md`

**Comment by Isaiah-Hamilton** [comment]
@saltcod this issue can only be fixed by someone with accuse to the infrastructure repo (Supabase team only).
