### ISSUE TITLE
Make the OAuth Redirect URI easily copyable

### ISSUE THREAD

**Issue by sritampatnaik** [supabase/supabase#5322]
# Feature request

## Is your feature request related to a problem? Please describe.

Not a problem. But while implementing Google, Apple and a bunch of other auth providers. I have to:
- Copy my `API URL` from the Settings page
- Go to the auth provider and paste the `API URL`
- Come back to the Supabase docs 
- Drag and copy `/auth/v1/callback` or memorise it 
- Go to the auth provider and paste it or type it out

## Describe the solution you'd like

In the Settings page below the config/URL have an easily copyable callback URL like this.

<img width="905" alt="Screenshot 2022-02-04 at 4 19 08 PM" src="https://user-images.githubusercontent.com/7572262/152604498-f1a18088-0ebf-40eb-bbae-ccd8cc8b43fb.png">

_PS: I manually injected that HTML. It is not the current state of the page_

## Additional context

This is good to have and will save users a few seconds switching between different tabs to figure out what to do.

**Comment by J0** [comment]
Hey @sritampatnaik 

Thanks for the feedback -- this is now available on the dashboard courtesy of our designer, @MildTomato  and the frontend team.

<img width="841" alt="CleanShot 2022-07-18 at 15 47 19@2x" src="https://user-images.githubusercontent.com/8011761/179466615-570a771b-7fff-4bc4-b4eb-79797d68f1aa.png">

Let us know if there are still issues!
