### ISSUE TITLE
Additional Redirect URL : Update config failed: An error has occured: Failed to fetch

### ISSUE THREAD

**Issue by KathirvelChandrasekaran** [supabase/supabase#5327]
# Bug report

## Update config failed: An error has occured: Failed to fetch

Not able to add additional **Additional Redirect URLs**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Go to 'Settings -> Auth Settings -> Additional Redirect URLs'

## Expected behavior

Want to add additional redirect URL. For example, Website developed using NextJS is deployed in Vercel and when the user login then he/she must be redirected to the URL which was given by Vercel not the localhost.

## Screenshots

<img width="456" alt="image" src="https://user-images.githubusercontent.com/22406448/152666178-510fc0b3-1d26-4fa8-afb8-41cc8f39cba0.png">

**Comment by inian** [comment]
This is a project specific issue @KathirvelChandrasekaran. Can you create a support ticket at https://app.supabase.io/support/new and we will take a look.
