### ISSUE TITLE
Live tracker map example currently broken

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#533]
Tracker map example: https://github.com/supabase/supabase/tree/master/examples/nextjs-live-tracker-map

Note that this app was written pre-gotrue-js so the auth bits may benefit from being upgraded to use the latest [gotrue-js](https://github.com/supabase/gotrue-js) 

Also this app does not support email confirmations yet so this must first be disabled in the dashboard here:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/458736/104757924-16ca1800-5777-11eb-965c-8e064312724b.png">

I was trying to quickly patch the issues but only got so far...

1) First error seems to be: [`.signUp`](https://github.com/supabase/supabase/blob/af99c593bc2a86368d395173beaf51afe4600b05/examples/nextjs-live-tracker-map/pages/api/auth/signup.js#L7) should actually be `.signup`

2) Second error is `Cannot read property 'access_token' of undefined`, which is solved by changing [`authBody.data.access_token`](https://github.com/supabase/supabase/blob/af99c593bc2a86368d395173beaf51afe4600b05/examples/nextjs-live-tracker-map/pages/api/auth/login.js#L9) to just `authBody.access_token`

3) Third error is on the backend: `Error: Gotrue-js: Failed to parse tokenResponse claims:`
which is actually a mistaken error message, the real error is: `ReferenceError: window is not defined` from [here](https://github.com/supabase/supabase/blob/af99c593bc2a86368d395173beaf51afe4600b05/examples/nextjs-live-tracker-map/lib/gotrue/user.js#L217), since this function seems to be running on the backend

If you add a line
`const atob = a => Buffer.from(a, 'base64').toString('binary')`

then you can remove [`window.atob`](https://github.com/supabase/supabase/blob/af99c593bc2a86368d395173beaf51afe4600b05/examples/nextjs-live-tracker-map/lib/gotrue/user.js#L217) for just `atob`

Now auth seems to work ok, but when I sign up and log in, the map does not display it just stays on the login form. Something must be failing silently somewhere, I don't know whether it may be easier to just refactor with [gotrue-js]

**Comment by kiwicopple** [comment]
This one is archived, so I'm closing this (for now)
