### ISSUE TITLE
Change column from `text` to `text[]` array not work

### ISSUE THREAD

**Issue by EryouHao** [supabase/supabase#5330]
# Bug report

## Describe the bug

I create a table column type is text, saved, change to array not work.

## To Reproduce

1. create a table from studio
2. create a column `images` type is `text`
3. save
4. edit table column `images` type to `array`
5. save

## Expected behavior

the column `images` type is `text[]`

## Screenshots

![image](https://user-images.githubusercontent.com/17328747/152672864-f709f5bc-96ae-4fcc-ba87-9bc5059486d1.png)

**Comment by DukeManh** [comment]
The same error happens with others data types as well.

**Comment by DukeManh** [comment]
I've been testing and using Supabase recently and want to contribute.
Can I take this issue?

**Comment by kiwicopple** [comment]
Hey @DukeManh - we'd love some help if you want to take it!

**Comment by DukeManh** [comment]
@kiwicopple thanks, it looks like it's an error in the  PostgREST-meta package.

**Comment by DukeManh** [comment]
Potentially close by https://github.com/supabase/postgres-meta/pull/181

**Comment by gerzarko** [comment]
Hi I know this issue is close but on my project I'm getting this same issue with no description of what is the error on why I can update the column, is this fix by supabase?
