### ISSUE TITLE
Table editor crashes when viewing foreign key row from the grid itself

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#5350]
# Bug report

https://support.supabase.org/a/tickets/4626

User mentioned that the linked row has a JSON field - could that be the issue? requires more investigation

https://user-images.githubusercontent.com/19742402/152754303-0119daed-1fc3-440c-b8c1-c1cd4bbb3a18.mov

**Comment by DukeManh** [comment]
@joshenlim, I'd like to work on this. The hard part is probably locating where the JSON is rendered and we could `Object.stringify` it?

**Comment by joshenlim** [comment]
@DukeManh hey there! sure thing :) ahh the component here is rendered through the library sorry
https://github.com/supabase/grid - our table editor is kept in a separate repository so this might be a good place to start looking? @phamhieu might be able to help give some pointers too

**Comment by phamhieu** [comment]
Something's wrong with Github issue transfer. @DukeManh you are welcome to work on the issue here https://github.com/supabase/grid/issues/113

I will close this.
