### ISSUE TITLE
SQL editor snippets save are conflicting when opened in separate browser tabs

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#5353]
# Bug report

https://support.supabase.org/a/tickets/4724

From the user:
> About the SQL Editor bug, I've retrospected what I did differently that day and I think I've found the answer. I've had the SQL Editor open in 2 tabs. You are realtime saving the editor and possibly even storing some data locally. The important thing is: If you have more than 1 tab open with the SQL Editor, even if you edit only in 1 tab and use the other tabs only to read, your editor will always get corrupted.

This isn't just tab specific but I'm guessing the issue will also occur if 2 users are editing the same SQL snippet at once

There are multiple solutions to this imo
- Do not save snippet edits automatically, but rather through an explicit action (button / cmd + s etc) (as mentioned by the user)
  -  Lowest hanging fruit, not the best DX
  - Still needs syncing across tabs or at least some conflict resolution
- Snippets need to be real-time synced, such that saving on one browser tab should reflect the updates on another

**Comment by JulienLecoq** [comment]
That's a really annoying issue. I hope it get solve quickly because it drives me crazy haha

**Comment by saltcod** [comment]
Closing as outdated with recent changes to how we manage snippets.

**Comment by JulienLecoq** [comment]
> Closing as outdated with recent changes to how we manage snippets.

Just to be sure, you mean that this problem should not happen anymore? It is solved by the recent changes to how you manage snippets?
