### ISSUE TITLE
Improve Connection pooling with Supabase guide with connection recommendations to Prisma and Lambdas

### ISSUE THREAD

**Issue by dthyresson** [supabase/supabase#5359]
# Improve documentation

Improve Connection pooling with Supabase guide with connection recommendations to Prisma and Lambdas
## Link 

Connection pooling with Supabase

https://supabase.com/docs/guides/integrations/prisma#connection-pooling-with-supabase

## Describe the problem

Lambdas with Prisma can exhaust connections quickly unless configured appropriately.

Prisma recommends setting the connection string to 1 connection per.

## Describe the improvement

From https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505

Why connection pooling?

Serverless is awesome, and crazy scalable - suddenly getting a 1000+ people hitting your servers? No problem - your provider will spin up a whole bunch of lambdas to deal with the demand. But hold on, your database isn’t infinitely scalable the same way, and those lambdas that spun up? They don’t necessarily let go of the database connections.

As a result, you start running out of connections to your DB, and Prisma will start throwing errors.

Construct your DATABASE_URL Using this and adding a few more params:

`sslmode=require`
`pgbouncer=true`
A
nd if you’re finding you’re still running out of connections, you can try limiting the connection limit per lambda:

`connection_limit=1`

Also remember to replace the password!

`DATABASE_URL="<CONNECTION_STRING_WITH_PASSWORD>?sslmode=require&pgbouncer=true&connection_limit=1`

Add this environment variable to your project as DATABASE_URL, and once you deploy you’ll have a much more resilient connection to your DB! Supabase puts pgbouncer in front of your Postgres DB, which helps manage the connections for you, so you don’t have to worry about running out too quickly.

Then need to explain how to work around migrations.

## Additional context

Useful references

* The world's worst pool party: Connection management with Prisma - Martina Welander | Prisma Day 2021 - https://www.youtube.com/watch?v=SmKJnITMQZw
* Migrations under pgBouncer https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505
* Prisma Connection Management https://www.prisma.io/docs/guides/performance-and-optimization/connection-management

**Comment by burmecia** [comment]
I think the doc has been improved in https://github.com/supabase/supabase/pull/6871, so close this issue.
