### ISSUE TITLE
API is not working 

### ISSUE THREAD

**Issue by noskovvkirill** [supabase/supabase#5364]
# Bug report
Hi guys! I previously submitted this issue which was resolved #4464 
I face the same issue with API again, but it's legible rn with expanded logs. 

## Describe the bug
API is not working. 

I cleaned up the logs a little bit for clarity, but this is what I see: 
`error fetch { 
 message:  What happened?  The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed. What can I do? If you're a visitor of this website: Please try again in a few minutes. If you're the owner of this website: Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. Additional troubleshooting information here
}`

The other thing that I've realized is that my database size is way over the free plan (1795 MB rn on 500 MB free plan allowance 😅). I don't have that many records (few thousand) + it accumulates very quickly. I thought it might be connected with the error message _' something on your server is hogging resources'_ 

## To Reproduce
I'm not sure if this is the reason, but the last two times issue appeared right after I've duplicated the table 

## Expected behavior
Working API 

Thanks!

**Comment by kiwicopple** [comment]
hey @noskovvkirill - can you please submit a ticket here so that we can get your Project ID: https://app.supabase.io/support/new

**Comment by awalias** [comment]
closing in favour of the support ticket. Feel free to reopen as needed

**Comment by give-my-certificate** [comment]
@awalias Hi, 

I am getting the same issue, after looking at logs I found that Cloudflare is giving frequent 522 and 524 errors. I tried connecting with your support by raising a ticket on the above-provided link but doesn't get any useful reply. Then I tried replying to that mail but as usual, does not get any response.
