### ISSUE TITLE
Next.js todo example: the Code Sandbox page seems broken

### ISSUE THREAD

**Issue by ykdojo** [supabase/supabase#537]
When visiting [the code sandbox page](https://codesandbox.io/s/github/supabase/supabase/tree/master/examples/nextjs-todo-list), it shows the error: globalThis is not defined:

![image](https://user-images.githubusercontent.com/1811651/104780701-05145080-5736-11eb-93a3-562d177e7060.png)

**Comment by ykdojo** [comment]
As a temporary solution, I removed the link from the README: https://github.com/supabase/supabase/commit/68d3bb47fbc783a078ec1ec5fc5ac313eedc72e1#diff-c820d126208eba5eb3646c5ce51da15deb4289133b1cda2972ae0b2ba6590d2b

I'll put it back once it's fixed.

**Comment by kiwicopple** [comment]
related: https://github.com/supabase/gotrue-js/pull/42

**Comment by kiwicopple** [comment]
Closing this one - I don't think CodeSandbox is very friendly with our JS library. We'll look into a better solution in the future
