### ISSUE TITLE
Docs link in the dashboard is dead

### ISSUE THREAD

**Issue by prabin-acharya** [supabase/supabase#5409]
# Bug report
Docs link in the studio dashboard is dead

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://app.supabase.io/'
2. Click on 'Help > Docs'
3. See error

## Screenshots
![Supabase](https://user-images.githubusercontent.com/71175492/153366031-5cc3cb75-c7b4-4363-a3b5-b63b37ae8981.png)
![Screenshot from 2022-02-10 14-05-07](https://user-images.githubusercontent.com/71175492/153366324-2124dc88-e0ba-4714-a30b-fde65d3284da.png)

## Additional context
https://twitter.com/supabase/status/1491678406223798276

**Comment by Isaiah-Hamilton** [comment]
fixed with #5397
