### ISSUE TITLE
Malformed redirectTo URL list silently dropped / ignored

### ISSUE THREAD

**Issue by kaspnilsson** [supabase/supabase#5416]
URLs listed in "Additional Redirect URLs" in `/project/${RPJECT_ID/auth/settings` will (seemingly?) silently be ignored / dropped when the string is invalid in some way. In my case, I added the URLs with an individual whitespace paste artifact at the beginning, and it took me an entire day to troubleshoot why my app redirect was not working.

Could we consider either adding an error state to this input (and ones like it) or sanitizing the string(s)?

![Screen Shot 2022-02-10 at 2 04 26 PM](https://user-images.githubusercontent.com/5749398/153504687-8a5f6d49-b1ba-4299-b914-313e8ab20fef.png)

**Comment by occidens** [comment]
I had the same issue today, with ordinary spaces after the commas. This caused email auth to silently fall back on the primary site URL.

**Comment by J0** [comment]
Hey all,

Thanks for your patience. We recently did a dashboard redesign and additional whitespace should be cleaned up with a delimiter `.`

Feel free to reopen if there are still issues though
