### ISSUE TITLE
Organizations team role add multiple owner

### ISSUE THREAD

**Issue by nkeat12** [supabase/supabase#5419]
### Discussed in https://github.com/supabase/supabase/discussions/486

<div type='discussions-op-text'>

<sup>Originally posted by **productdevbook** January  6, 2021</sup>
More than one manager cannot be added at the moment. Only one person can be a manager. It would be nice to increase this number.</div>

**Comment by kiwicopple** [comment]
This is is now available on the Enterprise plan (and we our upcoming "Team" plan will probably support this too)

If this is something that you need, feel free to reach out directly to through support for the Enterprise plan. Our Team plan should land in a few months (and it will be self-service so you don't need to talk to anyone)
