### ISSUE TITLE
Custom email links

### ISSUE THREAD

**Issue by edgarasben** [supabase/supabase#5424]
# Feature request

When I invite a user to signup they receive an invitation link. This link is within the supabase.co domain. I would like to customize this link masking it with my own domain. This should increase the trust for visitors clicking on a link with a familiar domain name<img width="457" alt="image" src="https://user-images.githubusercontent.com/725324/153567052-7498141f-03d9-4f65-b565-a985a9cb7ea0.png">

**Comment by burmecia** [comment]
This feature has been added, go to Dashboard -> Authentication -> Settings, and then change `Site URL` and `Additional redirect URLs`.
