### ISSUE TITLE
UI/Studio new table editor generates "invalid query" on table save if table name field is entered after defining a foreign key link.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#5429]
# Bug report

## Describe the bug

If you do not enter table name, and do intermediate operations like defining foreign key links, then update the table name, the SQL gets formatted incorrectly without a table name and will generate "invalid query" on save.  The error and why it is occurring is not clear to the user.  You either have to redo all your links after you fill in table name, or you cancel and redo things with the table name filled in first.

It appears the table editor code saves foreign key column parameters in an object, including source table info when column is generated/saved.  These objects do not get updated on source table name change.  Then on table save, column with foreign key generation is used to alter the table with stale data.

It is possible this also occurs on other table field definitions besides attaching a foreign key to the table, if the UI code pre-generates the SQL code, or saves source table info for later without a table name.

You also get an error if you enter a table name but then change it after doing links. This error is a bit more informative… “ relation public.table does not exist”

EDIT WORST ISSUE -> If you accidentally enter an existing table name, that has the same named column you link, and then change the table name either before or after table save error you get no error and NO LINK. It actually ADDS THE LINK TO THE OTHER EXISTING TABLE!

## To Reproduce

Create a table "test" with the two default fields.  Save.
Create a second table, but leave table name field blank.
Add a 3rd column "link_id" int8.  Link this field with the "link" icon to table test field id.
Add table name at top, save get "invalid query" error.  Be lost.

If you also attempt to save the table without a name and get missing name error, fill it in, same occurs.

## Expected behavior

Need to either require table before moving on to field definitions, or change SQL generation to wait until final Save.

## Screenshots

![linkadded](https://user-images.githubusercontent.com/54564956/153691346-de316e28-f00e-4a2c-b31c-f4a000a296fd.JPG)
![nameerror](https://user-images.githubusercontent.com/54564956/153691399-a3e0c58f-e288-4066-8fb7-ddfcfe3d2616.JPG)
![error](https://user-images.githubusercontent.com/54564956/153691405-19ea3167-32a0-405d-bdbc-bb535dfaabfb.JPG)
This is from Silentworks who confirmed the error (different table names):
![image](https://user-images.githubusercontent.com/54564956/153691463-24a583dd-056c-408d-8034-535844664a8c.png)
Note the missing table name.

## System information

Current UI

## Additional context

Problem was reported on Discord as a foreign link issue by sockenguy, debugging went on with Silentworks with no duplication,  I had encountered something like it before randomly, played around with it again and found the name order issue, and Silentworks confirmed the result and has a better log than I could get.

UI code which saves the foreign key data for use later on save table.
https://github.com/supabase/supabase/blob/f5a0c943071d9c9e781d6f76e935155432e8f71a/studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/ColumnManagement.tsx#L59

This is where the actual table alter occurs with the stale data:
https://github.com/supabase/supabase/blob/43f464d2d55377f7e658acd62dd69a1573f89522/studio/stores/pgmeta/MetaStore.ts#L220

**Comment by kiwicopple** [comment]
thanks for the detailed report @GaryAustin1 🥇 this is great.
