### ISSUE TITLE
Storage: Upsert Issue

### ISSUE THREAD

**Issue by j314h** [supabase/supabase#5430]
### Discussed in https://github.com/supabase/supabase/discussions/2889

<div type='discussions-op-text'>

<sup>Originally posted by **dommarr** August 18, 2021</sup>
Hi,

I'm attempting to upload or replace an existing image. The initial upload works, but the replace after does not. I get the following error: 

```node
statusCode: "23505", error: "", message: "duplicate key value violates unique constraint \"bucketid_objname\""

```

```js
let path = `${user.id}/share_page_image.png`;

const { data, error } = await supabase.storage
.from("user-images")
.upload(path, file, {
      upsert: true,
    });

```</div>

**Comment by j314h** [comment]
hello,

I have the same problem, but I have my file except that when I download another image, I have no error but my image has not been modified (I still have the old image )

Have you ever had this problem ?,

**Comment by GaryAustin1** [comment]
The images are cached by the browser based on cache time you set or I think default of 1 hour.

**Comment by j314h** [comment]
> The images are cached by the browser based on cache time you set or I think default of 1 hour.

yeah, i'm closed this, thank you for answer
