### ISSUE TITLE
Add flutter sample todo application to the example project

### ISSUE THREAD

**Issue by tanmoy27112000** [supabase/supabase#5440]
## Describe the problem

In the example project, there is no flutter application that shows the integration of supabase with flutter.

## Describe the improvement

Let's add a sample project that shows the flutter integration

**Comment by tanmoy27112000** [comment]
I can create the application

**Comment by FatumaA** [comment]
> I can create the application

If you want you can use this as a starter and adopt it: https://github.com/FatumaA/flutter-http-package-playground
It's a todo app using json placeholder and the http package.

**Comment by RaghavBhat02** [comment]
Can I take this issue?

**Comment by Anikets08** [comment]
Hey can i take the issue if anyone not working into it

**Comment by Isaiah-Hamilton** [comment]
@Anikets08 all yours!

**Comment by Anikets08** [comment]
Here's the link https://drive.google.com/file/d/1mlIXDKOm-_u8TgQxdAwTvCatJjCsdqYM/view?usp=sharing

**Comment by Anikets08** [comment]
Hey now you can find the folder as I've removed .git file

**Comment by Anikets08** [comment]
@kiwicopple can you please check once
