### ISSUE TITLE
Show page you dont have acess to the project

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#5443]
# Feature request

## Is your feature request related to a problem? Please describe.

When I was trying to view a project that I don't have access to, it showed this. It would be better if we showed something like a page saying that they dont have acuess to the page or redirect to another page.

<img width="1280" alt="Screen Shot 2022-02-13 at 12 33 54 PM" src="https://user-images.githubusercontent.com/70828596/153769664-c7935c96-7e7c-4259-be89-70d6b467a629.png">

## Describe the solution you'd like

To show a page that says "you don't have access to this project, try contacting the project owner to gain access." or something like that.

## Describe alternatives you've considered

or any other way of showing that they don't have access.

**Comment by joshenlim** [comment]
adding for context if anyone's able to jump on this
- this happens specifically on auth/templates page
- anywhere else it should redirect back to the home page properly with a message "This project doesn't exist"

![image](https://user-images.githubusercontent.com/19742402/153787024-646bc835-a852-4940-9020-aeb41ee7f37b.png)

**Comment by FatumaA** [comment]
Hi, 
I've looked at this and, at least on localhost, I can get the redirect to happen after fixing the typeError but it takes a few reloads to trigger it

**Comment by Hallidayo** [comment]
Hi @Isaiah-Hamilton,

I can't seem to recreate this? When I go to a project I don't have access to I just get redirected now onto my own dashboard and do not get an application error?

**Comment by saltcod** [comment]
Same @Hallidayo these get redirected now. Going to mark this as closed. Thanks all.
