### ISSUE TITLE
eq not working on `apikey` column

### ISSUE THREAD

**Issue by skwasan** [supabase/supabase#5465]
# Bug report
Supabase eq not working

## Describe the bug
```
 const { data, error } = await supabase
    .from('userdetails')
    .select()
    .eq('apikey', 'no-apikey-in-db') //This returns all the rows in table which is not correct as apikey is not in db

```

My data for select is 

```
data: [
{
id: "e23222a4-b061-4ca1-8a2a-99ec3674a9c9",
username: "sdf sdfds",
email: "sddsf@gmsil.com",
apikey: "dde7ceb7d7dc4e569f56b1300d9c267b",
updated_at: null,
created_at: "2022-02-15T03:54:54.490956+00:00",
config: null
},
{
id: "e52304a3-05f1-4d46-b491-da61a12726ee",
username: "abc",
email: "abc@gmail.com",
apikey: "1f6156a4abc8483085a3d208e25a209e",
updated_at: "2022-02-15T05:24:58.324911+00:00",
created_at: "2022-02-15T03:30:20.634416+00:00",
config: {..}]
```

This is how I created the table

```
create table userdetails (
  id uuid references auth.users not null,
  username text,
  email text,
  apikey VARCHAR DEFAULT REPLACE(uuid_generate_v4()::text, '-', '' ),
  updated_at TIMESTAMP WITH TIME ZONE,
  primary key (id)
);
```

It's working for all the other keys but not apikey say `email.`

```
 const { data, error } = await supabase
    .from('userdetails')
    .select()
    .eq('email', 'no-apikey-in-db') //This returns 0 rows which is correct

```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Please create above table and add data give above

## Expected behavior

0 Rows should be returned as no rows in db matches `no-apikey-db`. But `eq` returns all the rows

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by steve-chavez** [comment]
I think this happens because the Kong gateway(reached before PostgREST on Supabase instances) uses the `apikey` query parameter, likely it's not passing `apikey` to PostgREST.

Not ideal, but a workaround could be renaming your `apikey` column to something else, like `user_apikey`.

**Comment by skwasan** [comment]
Thanks, It resolved but its really bad. I spent so much time banging my head to wall 😁

**Comment by awalias** [comment]
I've documented it for now, eventually we will move `apikey` out of the query params for the api gateway, we still need it for now because the realtime server can't yet receive it via headers
