### ISSUE TITLE
CSV File Import creates column names with double quotes 

### ISSUE THREAD

**Issue by iporollo** [supabase/supabase#5482]
# Bug report

## Describe the bug

During the table creation flow through a CSV file, the importer auto-detects the column names. When the table is then created from the CSV file, the actual column names are created with double quotes e.g. `"ID"`.  This prevents queries from being run on table columns unless they are in double quotes e.g. 

```
SELECT "ID" FROM bus_breakdowns;
```

Related StackOverflow post [https://stackoverflow.com/a/55297938/6084966](https://stackoverflow.com/a/55297938/6084966)

## To Reproduce

1. Log in to Supabase cloud
2. Click on a project
3. Go to table editor
4. Create new table
5. Click on `Import data via spreadsheet` button
6. Upload CSV (can link example if necessary)
7. Create table from CSV
8. Navigate to SQL editor
9. Try to query column name from table without double quotes around name
10. See error `column does not exist`

## Expected behavior

Upon import of the CSV file, create the table columns without double quotes such that the table columns can be queried in a SQL editor with out double quotes. 

## Screenshots
<img width="1431" alt="Screen Shot 2022-02-15 at 3 51 05 PM" src="https://user-images.githubusercontent.com/14094284/154171495-c0dfa7df-cf16-462d-baf1-4bcd1a28f54b.png">
<img width="1425" alt="Screen Shot 2022-02-15 at 3 51 28 PM" src="https://user-images.githubusercontent.com/14094284/154171506-2ca5dbb5-60be-44cb-bfa0-1b89ff103ee3.png">
<img width="1436" alt="Screen Shot 2022-02-15 at 3 49 00 PM" src="https://user-images.githubusercontent.com/14094284/154171512-491f7f0b-93aa-4e01-b7fe-84b4fc59edfd.png">
<img width="1430" alt="Screen Shot 2022-02-15 at 3 50 12 PM" src="https://user-images.githubusercontent.com/14094284/154171526-1c8e4d27-4c16-46d1-9c5b-85e9af6b956e.png">
<img width="1428" alt="Screen Shot 2022-02-15 at 3 50 28 PM" src="https://user-images.githubusercontent.com/14094284/154171562-678fb5f4-853f-4d51-ae1a-6fc568648c3a.png">

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of Supabase: Cloud

## Additional context

This may be an intentional implementation to account for spaces in column names when detection happens from the CSV file. That said, it was still a bit confusing to figure out why I couldn't query imported data. Maybe if there was a way to edit the column names from the imported CSV file that could potentially solve the problem.

**Comment by awalias** [comment]
this seems to be because your column headers are in uppercase - postgres itself requires that you query uppercase table or columns with double quotes

suggest that you export your original data to lowercase headings or manually edit the csvs if you don't want to require double quotes
