### ISSUE TITLE
Dashboard organisation /project switch upgrade

### ISSUE THREAD

**Issue by riderx** [supabase/supabase#5491]
Change project or organization is a bit painful in the UI.

See below the video

https://user-images.githubusercontent.com/4084527/154340303-e4b557e1-a809-4dfa-aec1-27bb373feb75.mov

When you hit the or button, you go in organization settings instead of project list.

Firebase navigation can be copied on that :

https://user-images.githubusercontent.com/4084527/154340522-a7ae0f0c-481a-4c38-94b4-6b2caa651a24.mov

In firebase the selector let you choose in all project from all organization, no need to go back in different page.

**Comment by Hallidayo** [comment]
@saltcod - Hi Saltcod, I think this one can be closed?

**Comment by kiwicopple** [comment]
thanks for the flag here @Hallidayo - I think you're right. We're working on a updated navigation, and I'll tag this issue in the project as it's great feedback

**Comment by riderx** [comment]
@kiwicopple "the project" is something we cannot see right ?
Thanks for working on it <3
