### ISSUE TITLE
DELETE realtime event not being triggered with RLS subscription

### ISSUE THREAD

**Issue by ize8** [supabase/supabase#5495]
# Bug report
when subscribing for Realtime Updates + listening to row-level changes, then the DELETE event won't get emitted

## Describe the bug

when listening to row-level changes, DELETE event won't be emitted on row delete. Probably because the relevant record won't satisfy the row-level filter as it is being removed.

## To Reproduce
```javascript
const mySubscription = supabase
  .from('foods:cook_id=eq.200')
  .on('*', handleRecordChanged)
  .subscribe()
```

INSERT and UPDATE will trigger the callback as expected when changing any food that has cook_id = 200, but upon deleting a record DELETE won't get triggered. Probably because the record does not satisfy the filtering criteria (cook_id=200) anymore as it is being deleted.

## Expected behavior

DELETE event to be triggered as expected before row gets removed

**Comment by w3b6x9** [comment]
@ize8 can you try setting the replica identity on your `foods` table to full?

```sql
alter table food replica identity full;
```

**Comment by ize8** [comment]
@w3b6x9  ahh, silly me! 谢谢！It's working now as expected!

**Comment by w3b6x9** [comment]
@ize8 别客气! glad it's working!
