### ISSUE TITLE
Incorrect Email for alpha@superbase.io - Alpha program message

### ISSUE THREAD

**Issue by lukethacoder** [supabase/supabase#55]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Just a super small text change. The email address looks to be incorrect 

Ref: https://app.supabase.io/account/me

![image](https://user-images.githubusercontent.com/13529535/79410362-855d2800-7fe3-11ea-9e3e-2905959b0fcf.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kiwicopple** [comment]
Keen eyes, thanks @lukethacoder .

In our next release we will have a free tier for everyone, so we'll remove this message then and I'll update here once we've released it

**Comment by kiwicopple** [comment]
@lukethacoder I'm deploying this fix out now. Thanks a lot for the bug report 👍

**Comment by kiwicopple** [comment]
btw @lukethacoder I checked out your website. awesome design

**Comment by lukethacoder** [comment]
@kiwicopple ah thanks man. been wanting to rebuild it but other projects keep popping up.
