### ISSUE TITLE
PostgreSQL Logs over 100GB - Need set properly the logs

### ISSUE THREAD

**Issue by WilliamFalci** [supabase/supabase#5505]
# Bug report

## Describe the bug

Today I wasn't able to connect to our Test Server with VS, after investigation we found the issue, the issue was the disk space, 100% used.. then we found the issue was on Supabase Postgress, the file `postgresql.csv` was over 100GB, located in `diff/var/log/postgresql`

## To Reproduce

Just keep docker up for various days and run operations

## Expected behavior

Keep logs is good pratice but need configure properly the amout of days to keep track and size

## Screenshots

![image](https://user-images.githubusercontent.com/36926081/154455812-528d70fa-4cb4-4ddd-beea-83170680ef34.png)

## System information

- OS: Linux Ubuntu
- DB Image: supabase/postgres:14.1.0

**Comment by w3b6x9** [comment]
+1 to what @grschafer wrote. try turning logs off completely b/c realtime rls is really noisy.
