### ISSUE TITLE
Migration failed. Reason: column "public" of relation "buckets" already exists

### ISSUE THREAD

**Issue by y0zong** [supabase/supabase#5507]
# Bug report

## Describe the bug

can't do any action to storage now

## To Reproduce

just open storage page and the error shows

## Screenshots

<img width="1342" alt="Screen Shot 2022-02-17 at 6 45 41 PM" src="https://user-images.githubusercontent.com/86962713/154460151-b953c0ad-a287-4afb-a540-9c05e85e8eef.png">

## System information

- OS: macOS
- Browser safari
- Version of supabase-js: use supabase cloud
- Version of Node.js: use supabase cloud

**Comment by inian** [comment]
Hi @y0zong, this is an issue specific to your project. Can you create a support ticket at https://app.supabase.io/support/new and we will follow up there. Thanks.
