### ISSUE TITLE
Next.js auth example: login page flashes when reloading

### ISSUE THREAD

**Issue by mrkldshv** [supabase/supabase#553]
# Bug report

## Describe the bug

When I log in and refresh any page, I can see flash and screen for not logged in user.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log in
2. Refresh
3. See screen for not logged in user for a second

## Expected behavior

Show view for logged in user without flash.

## Additional context

This might be related to the line: https://github.com/supabase/supabase/blob/31aa8c0cc028beaf3b5c11d2cd76a717fbd6eb29/examples/nextjs-with-supabase-auth/pages/index.js#L39
Most likely user is `null` on initial render.

**Comment by kiwicopple** [comment]
@thorwebdev I think another reason to move to syncronous init on gotrue: https://github.com/supabase/gotrue-js/issues/36#issuecomment-761746018 ?

**Comment by thorwebdev** [comment]
@kiwicopple on web it is a synchronous request currently already. The problem here is that React hydrates from the server and only then runs the `useEffect` hook, meaning you either have to suppress the hydration warning, introduce a loading state that hides all content initially, or live with the potential initial flicker.

**Comment by carlosstenzel** [comment]
I use it this way, it works

```
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useUser } from '@/hooks/UserContext';

export const useRequireAuth = () => {
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user === false || user == null) {
      router.push('/Sign-in');
    }
  }, [user, router]);

  return user;
};

export const useIsAuth = () => {
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push('/dashboard');
    }
  }, [user, router]);

  return null;
};

```

page for authenticated user

```
...
const DashBoardPage: React.FC = () => {
  const user = useRequireAuth();
 
   if (!user) return null;
   // or if (!user) return <AreaSecure />;

  return (
    ... dashboard
  )
}

```
checks if authenticated

```
...
const auth = useIsAuth();
...
```

**Comment by atnegrete** [comment]
Facing similar issue on flutter with dart https://github.com/supabase/gotrue-dart/pull/10 
I'm exposing _recoverSession to get around it

Would it be possible to move the clients' initialization to an asynchronous method, away from the constructor? The flicker on mobile applications is not acceptable on mobile apps imo

**Comment by raghavaro** [comment]
Ideally, this should be handled on the server side. Sample code below:

```
import nextCookie from 'next-cookies'

.
.
.

export async function getServerSideProps(context) {
  
    const { token } = nextCookie(context)
    
    if (!token) {
        return {
            redirect: {
                permanent: false,
              destination: "/"
            }
        }
    }
    
    const data = getDataFromToken(token)
    
    return {
        props: data
    }
}
```

**Comment by awalias** [comment]
spring cleaning: closing as stale, feel free to poke/reopen if still relevant

**Comment by eetzkorn** [comment]
Was this ever fixed I'm confused. I still get the flicker using Supabase's recommended code

**Comment by thorwebdev** [comment]
Can you try with https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md please?

**Comment by matt-j-stevenson** [comment]
Was this ever re-addressed?
I've used this implementation posted [above](https://supabase.com/docs/guides/auth/auth-helpers/nextjs), and I still get an authenticated "flash" on SSG Next.js pages, is there a "loading" value provided from the hooks?

**Comment by jeremyisatrecharm** [comment]
I'm also seeing  similar behavior. 

I suspect the issue is:
```useUser();``` takes a moment / is async, it's not possible to tell the difference between not being logged in and `useUser()` fetching, so components assume the user isn't logged in briefly. When `useUser` updates, this triggers quick re-render.

Having a `loading` status from `useUser` would help me resolve it.

**Comment by nicksinai** [comment]
still an issue when going through [this](https://supabase.com/docs/guides/getting-started/tutorials/with-react) tutorial today

**Comment by nicksinai** [comment]
still an issue when going through [this](https://supabase.com/docs/guides/getting-started/tutorials/with-react) tutorial today
