### ISSUE TITLE
The column which is defined as array can't be updated from supabase UI

### ISSUE THREAD

**Issue by hi629** [supabase/supabase#5533]
# Bug report

## Describe the bug

After creating a column which is defined as array and tried to update the column, there is an error.
The error says `type "int2[]" does not exist` . The type should be updated is in the error message.

## To Reproduce

1. Go to 'Table editor'
2. Check the checkbox of Define as array and create a new column
3. Update the column you created
4. See the error

## Expected behavior

The column is updated

## Screenshots

https://user-images.githubusercontent.com/28013909/154682625-b13c08b9-7e6f-4c26-ab42-857aeaaf5c41.mov

## System information

- OS: macOS
- Browser chrome
- Version of supabase-js: cloud dashboard

**Comment by joshenlim** [comment]
Hey there! I just checked on this on our dashboard and followed through your reproduction steps as shown in the video you attached (thank you so much for that!) - the issue seems to have been fixed

I'll go ahead to close this ticket but feel free to reopen if I'm wrong! 🙏
