### ISSUE TITLE
Accessing API tab on self hosted instance results in CORS error.

### ISSUE THREAD

**Issue by Hergeirs** [supabase/supabase#5540]
# Bug report

## Describe the bug

Self hosting Supabase following the guide in https://supabase.com/docs/guides/hosting/docker results in a CORS error when accessing the API tab in the studio.
I've done no changes to anything. Not even created a table. I have tried creating a table as well and it made no difference.

## To Reproduce

Follow the guide in https://supabase.com/docs/guides/hosting/docker

```
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Start
docker-compose up
```

go to localhost:3000 with a browser and click the API tab on the left

Get an error:
![image](https://user-images.githubusercontent.com/20126436/154744281-5871f799-068e-4efe-8276-d98387b25599.png)

Opening dev tools shows these errors:

![image](https://user-images.githubusercontent.com/20126436/154744572-3c3fd2d4-440d-4b25-bda5-12812c41d2ca.png)

In text form:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://kong:8000/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE. (Reason: CORS request did not succeed). Status code: (null).

load e.message An error has occured: NetworkError when attempting to fetch resource. [_app-6e0e1cfab749f6b0e74d.js:1:1030291](http://localhost:3000/_next/static/chunks/pages/_app-6e0e1cfab749f6b0e74d.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://kong:8000/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE. (Reason: CORS request did not succeed). Status code: (null).

```

## Expected behavior

Showing the expected API tab.

## System information

- OS: archlinux
- Browser: Firefox 97.0 (64-bit)

## Additional context

None relevant.

**Comment by kiwicopple** [comment]
Does this fix your issue @Hergeirs ? 
https://github.com/supabase/supabase/pull/5402

**Comment by Hergeirs** [comment]
It did. 
I should have seen that myself instead of blindly copying the .env.examples file. 
Thank you.

**Comment by ryanfiller** [comment]
I'm having this exact issue, I can't figure out what the fix from [#5402](https://github.com/supabase/supabase/pull/5402) is supposed to be. Help?

**Comment by Hergeirs** [comment]
The "fix" in my case was changing the line ```KONG_URL=http://kong:8000``` to ```KONG_URL=http://localhost:8000``` in the .env file.

**Comment by ryanfiller** [comment]
I've deleted my project and started over fresh, following the install steps outline above (`git clone --depth 1 https://github.com/supabase/supabase`, etc, etc...) and I'm not even seeing a `KONG_URL` set in the entire project.

Am I missing something incredibly obvious here?

**Comment by unusec** [comment]
@ryanfiller in the .env file, if you run supabase on another machine in your lan make sure to use the LAN IP for the PUBLIC_REST_URL and SITE_URL, I had a similar issue with a supabase install on my NAS
