### ISSUE TITLE
Default created_at value changes after trying to edit column, resulting in syntax error

### ISSUE THREAD

**Issue by bradybellini** [supabase/supabase#5545]
# Bug report

## Describe the bug
After editing the default `created_at` value of `(now() at time zone 'utc')`, the UI shows a different string, `now() at time zone 'utc`, resulting in a syntax error when trying to save.

## To Reproduce

1. Create a new table with a `created_at` column with a type of either timestamp or timestampz
2. As the default value select `(now() at time zone 'utc')`
3. Go to the table and select the edit column for the `created_at` column
4. The Default value will now have a syntax error and show `now() at time zone 'utc`, instead of `(now() at time zone 'utc')`

## Expected behavior

The default value should show `(now() at time zone 'utc')`

## Screenshots
What it should look like
![image](https://user-images.githubusercontent.com/47389606/154788383-7b40b2fa-71a0-4de5-9503-ff8e8eba5200.png)

What is showing
![image](https://user-images.githubusercontent.com/47389606/154788392-071cab11-caff-4a8e-98b6-a01a348d6f15.png)

## System information

Windows 10, Brave (chromium)

**Comment by kiwicopple** [comment]
hey @bradybellini - I'm not sure this is a bug, it's just the way that Postgres represents the value - even if you create it with `()` it gets "saved" without the brackets. Is it causing you any issues?

**Comment by bradybellini** [comment]
Thanks for the response! If not the brackets, I do get a syntax error still when trying to save without the closing quote, which is what it defaults to when trying to edit. And even with the closing quote, I also get a syntax error. It is not until I add in the brackets and closing quote that it will allow me to save without a syntax error. It isn't causing any blockage, just have to edit the default value if I want to edit anything else in that column and save without error.

Without closing quote
![image](https://user-images.githubusercontent.com/47389606/155028535-43443c5e-ffad-40b9-991d-f264daef71ed.png)

With closing quote
![image](https://user-images.githubusercontent.com/47389606/155029207-1f8c7840-206b-4955-a17f-7dfc46ec0027.png)
