### ISSUE TITLE
renaming table does not rename the pkey constraint

### ISSUE THREAD

**Issue by jnorris441** [supabase/supabase#5549]
# Bug report

## Describe the bug

After renaming a table, the _pkey constraint uses the old table name. This causes a problem if you try to change the primary key field. 

For example, a table originally named "reporttype_report" was renamed to "report_reporttype".

When trying to change the primary key, It gives an error "constraint "report_reporttype_pkey" of relation "report_reporttype" does not exist" because the constraint is still named "reporttype_report_pkey"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a table
2. rename it
3. add a new column 
4. try to change the new column to the primary key

## Expected behavior

Should succeed

## System information

- OS: macOS
- Browser: Chrome

**Comment by marcinkoziej** [comment]
You can use direct access to PSQL database (using psql command) to rename the constraint.

**Comment by jnorris441** [comment]
@marcinkoziej does the postgres user have permission to rename a constraint? I think I got an error

**Comment by burmecia** [comment]
This issue seems has been fixed. Feel free to reopen if it is still an issue.

**Comment by jnorris441** [comment]
Came back to Supabase today, renamed a table, still have the same issue. The constraint has the old name, many-to-many join fails. Have to manually go and find the name then alter the table via SQL.
