### ISSUE TITLE
Allow auth.users table to be referenced as foreign key

### ISSUE THREAD

**Issue by realPrimoh** [supabase/supabase#555]
# Feature request

Allow auth.users table to be referenced as foreign key

## Describe the solution you'd like

Currently, I am creating a `user_id` foreign key column to the `auth.users` table using SQL. Ideally, I would love to be able to simply create the column using the GUI and have `auth.users` be a table that I can make foreign keys to.

(I want to stay away from SQL as much as possible!)

**Comment by kiwicopple** [comment]
Hi @realPrimoh - we security reasons we don't want to allow this, however there is a very simple way to "duplicate" your users into your public schema: https://supabase.io/docs/guides/auth#create-a-publicusers-table

You only have to run this once, and then you can reference `public.users`
