### ISSUE TITLE
Cloudflare Workers example no longer needs patching

### ISSUE THREAD

**Issue by unsafecreds** [supabase/supabase#5557]
# Improve documentation

## Link 

Hey, I was trying out Supabase with Cloudflare Workers, and found this example:
https://github.com/supabase/supabase/tree/master/examples/with-cloudflare-workers

## Describe the problem

1. The `patch-package` workaround described is no longer necessary
2. The version of `@supabase/supabase-js` is pretty old.

## Describe the improvement

I came across https://github.com/supabase/supabase/issues/4417, and discovered that the solution described in your docs [here](https://supabase.com/docs/reference/javascript/initializing#custom-fetch-implementation) makes the patch workaround obsolete.

## Additional context

I'm happy to submit a PR if you want :)

**Comment by kiwicopple** [comment]
🎉 that's great news 

> I'm happy to submit a PR if you want :)

Yes please! We can probably remove/update this one too: https://github.com/supabase/supabase/tree/master/examples/with-cloudflare-workers

**Comment by unsafecreds** [comment]
Awesome! That's the example I was talking about. Here's the PR: https://github.com/supabase/supabase/pull/5585, let me know if you'd like me to make changes!

**Comment by kiwicopple** [comment]
fixed by https://github.com/supabase/supabase/pull/5585
