### ISSUE TITLE
Allow filter, order when using realtime feature

### ISSUE THREAD

**Issue by naptestdev** [supabase/supabase#5559]
# Feature request

I'm using @supabase/supabase-js and I want to be able to filter, order when subscribe to realtime data.

## Describe alternatives you've considered

Firebase (firestore) can do that.... why not supabase?

**Comment by kiwicopple** [comment]
You can definitely filter realtime changes: https://supabase.com/docs/reference/javascript/subscribe#listening-to-row-level-changes

Is there a particular filter on Firebase that's missing on Supabase?

Ordering probably makes more sense on the client - Supabase just sends events as they happen, so the order is basically "on change"
