### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by chendelin1982** [supabase/supabase#5561]
# Feature request

## Is your feature request related to a problem? Please describe.

When I use supabase to replace Contentful, I find that Column i18n is very import for CMS, it can help me maintenance one table for multiply language. 

## Describe the solution you'd like

You can see sreenshot of Contentful below

![image](https://user-images.githubusercontent.com/16741975/154885598-4c3498b9-3bd7-40f7-8b2e-495ab04868ed.png)

![image](https://user-images.githubusercontent.com/16741975/154885647-96537afc-6d86-4a66-b86f-de317d2d1044.png)

**Comment by kiwicopple** [comment]
Hey @chendelin1982 - this can definitely be done already within postgres - you would either:

- create another column. eg if you had `post`, you might create `post_en` to store english
- create a JSONB column with unstructured data. eg, if you had `post` you might create `post_i18n` to store all translations
- create a translations table. eg, if you had a table `posts`, you might create a table `posts_i18n` and store all the translations in that table

There is full-flexibility. No answer is right or wrong - it really depends on your preference. In the past I have used the `jsonb` approach and I personally feel its a good way to do it, although if the text is very long, it could be smart to create a separate table

**Comment by chendelin1982** [comment]
@kiwicopple

> Hey @chendelin1982 - this can definitely be done already within postgres - you would either:
> 
> * create another column. eg if you had `post`, you might create `post_en` to store english
> * create a JSONB column with unstructured data. eg, if you had `post` you might create `post_i18n` to store all translations
> * create a translations table. eg, if you had a table `posts`, you might create a table `posts_i18n` and store all the translations in that table
> 
> There is full-flexibility. No answer is right or wrong - it really depends on your preference. In the past I have used the `jsonb` approach and I personally feel its a good way to do it, although if the text is very long, it could be smart to create a separate table

Hi Kiwicopple, thank for your suggestion
