### ISSUE TITLE
Add examples for `count`

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#558]
# Improve documentation

## Link 

- `select`, `rpc`

## Describe the problem

We now have `count` functionality - we should add this to the docs

https://github.com/supabase/postgrest-js/issues/94#event-4210564301

**Comment by dshukertjr** [comment]
If no one has started working on this, could I do this? 

Pretty much adding descriptions here
https://github.com/supabase/supabase/blob/master/web/spec/supabase.yml
and here
https://github.com/supabase/supabase/edit/master/web/spec/supabase.yml
right?

**Comment by kiwicopple** [comment]
THanks @dshukertjr ! It's a few steps:

- cd `/web/spec/supabase.yml`
- run `make` which will pull the latest TSDoc with your updates
- add your comments to `supabase.yml` 
- then run `npm run gen:supabase` inside the `/specs` folder which will generate the Docusaurus types.

Let us know if you get stuck!

**Comment by dshukertjr** [comment]
I guess this issue can now be closed as the above PR has merged! 🚀

**Comment by kiwicopple** [comment]
Thanks for all your help @dshukertjr 🚢
