### ISSUE TITLE
Bug: redirectTo is broken

### ISSUE THREAD

**Issue by iamclaytonray** [supabase/supabase#5589]
# Bug report

## Describe the bug

`redirectTo` is broken. It's not respected at all.

## To Reproduce
Add two URLs to your redirects. Only one will be respected. This is a known issue.

## Expected behavior

Should redirect to the place in which I instruct from where the email link is generated.

## Screenshots

N/A

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

[Add any other context about the problem here.](https://github.com/supabase/supabase/issues/3191)

**Comment by iamclaytonray** [comment]
I know there's another issue semi-tracking this. We have our CMS on `admin.x.com`. Users who sign into `x.com` are being redirected to `admin.x.com`. This **_really_** needs a fix, and that part of the code is not open source, so I can't even fix it myself.

**Comment by bnjmnt4n** [comment]
@iamclaytonray could we get a code sample of usage for which `redirectTo` doesn't work? I presume that you've set up the site URL and additional redirect URLs correctly given that you've linked to https://github.com/supabase/supabase/issues/3191.

**Comment by iamclaytonray** [comment]
```ts
const login = useCallback(
    async (email: string) => {
      await supabase.auth.signIn(
        {
          email,
        },
        { redirectTo: window.location.origin },
      );
    },
    [],
  );
```

**Comment by iamclaytonray** [comment]
If I need to throw $500 at this to get priority support, tell me where to pay. I've been waiting for some type of resolution for a week.

**Comment by MildTomato** [comment]
@iamclaytonray I think we deployed some changes to our backend API so that the Redirect URI gets cleaned (removes whitespace) before it is inserted.

We'll do more improvements though, especially the front end UI so that it's easier to add in URLs, and we will also properly validate anything before it is sent to the API.

**Comment by iamclaytonray** [comment]
Cool. Apologize for the very obvious frustration. I had just refactored off of magic.link because email delivery was super intermittent and/or delayed, so coming into Supabase with the redirectTo issue was stressing me out a lot

**Comment by MildTomato** [comment]
@iamclaytonray no need for the apology 👍 😄 I understand the frustration completely. we should have fixed it sooner really.

**Comment by obetomuniz** [comment]
Hey, I was figuring the same problem. 

I have a dynamic URL, which is `https://mysite.com/users/123`. 

Adding `https://mysite.com/users` to `Additional Redirect URIs`, I am able to redirect to `https://mysite.com/users` using the `redirectTo` option on magic links, but as you can see, I need to redirect to a specific user (e.g. An user with ID number equals to `123`). 

How can I add dynamic URIs as `Additional Redirect URIs` to allow such redirections?
