### ISSUE TITLE
Add new table row hangs with empty UUID field

### ISSUE THREAD

**Issue by darrenbarklie** [supabase/supabase#561]
# Bug report

## Describe the bug

Add a new row. Exclude content from any field. Click Save button. UI hangs in following state:

![image](https://user-images.githubusercontent.com/3026261/104971254-171c1a80-59e6-11eb-9d21-121baf4e8726.png)

## Expected behavior

Row show be added, with empty field.

## Workaround

Add a number to the intended-empty field, use `CMD` + `Return` to force "Invalid syntax" error.  Delete content from field.  Press Save CTA for expected behaviour of row added with unpopulated fields.

## System information

- Supabase GUI

**Comment by kiwicopple** [comment]
Thanks for the report @darrenbarklie 

@joshenlim FYI

**Comment by kiwicopple** [comment]
Tested again with a similar table structure and it looks like it's working now 👍 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/10214025/114697043-00206680-9d50-11eb-8f2e-9693c91507ec.png">
