### ISSUE TITLE
Public URLs for storage in local development doesn't work

### ISSUE THREAD

**Issue by statico** [supabase/supabase#5637]
# Bug report

## Describe the bug

It appears that, when using local development with `supabase start`, `supabase.storage.from().getPublicUrl()` doesn't seem to return a valid URL. However, `.download()` works fine.

## To Reproduce

1. Start Supabase locally with `supabase start`
2. Upload an image with `supabase.storage.from("test").upload(path, file)` (I guess you don't need to initialize buckets locally? There's nothing in the web interface)
3. Try `supabase.storage.from("test").download(path)` -- you'll get valid data
4. Try `supabase.storage.from("test").getPublicUrl(path)` -- you'll get a URL like `http://localhost:54321/storage/v1/object/public/test/0.33763726009346384.jpg` but that returns a 404 with `{"statusCode":"404","error":"Not found","message":"The resource was not found"}`

## Expected behavior

I would expect the URL from `getPublicURL()` to return a 200 with the image.

## Screenshots

n/a

## System information

- OS: macOS 12.2
- Browser: Chrome latest
- Version of supabase-js: 0.18.1
- Version of Node.js: v16.13.0

**Comment by inian** [comment]
Hmm I do see that the upload code doenst check if the bucket exists first, will create an issue for this. If you create a bucket first and set the bucket to public, `getPublicURL` should then work. Buckets are private by default (and in this weird case where the bucket doesn't actually exist, the code assumes its a private bucket)

**Comment by vbylen** [comment]
@inian how would I make this a public bucket using the SQL below?

```sql
insert into storage.buckets (id, name)
values ('avatars', 'avatars');
```

**Comment by RJayE** [comment]
Is this fixed? If a bucket's policies would require authentication from the users to use it then getPublicUrl isnt the option. Should've a method called getAuthenticatedUrl/getPrivateUrl instead of getPublicUrl? 

Or just atleast return the whole URL like what I get when copying the URL from an uploaded from the bucket. Because that URL works.

**Comment by 0xj0hn** [comment]
Same issue

**Comment by AC40** [comment]
I noticed that when getting the public URL from the local supabase dashboard, it gives the same url created by the supabase-js client, but with the file extension ('.png' or '.jpeg' in my case). Adding the file extension manually in the web inspector makes the image appear, but the client for some reason does not do this. On hosted supabase, it does not need a file extension.
