### ISSUE TITLE
Feat: Allow redirecTo use dynamic URIs

### ISSUE THREAD

**Issue by obetomuniz** [supabase/supabase#5658]
# Feature request

## Is your feature request related to a problem? Please describe.

Yes, I have a dynamic URL, which is `https://mysite.com/users/123`. 

Adding `https://mysite.com/users` to `Additional Redirect URIs`, I am able to redirect to `https://mysite.com/users` using the `redirectTo` option when trying to use magic links, but as you can see, I need to redirect to a specific user (e.g. An user with ID equals to `123`). 

For now, I can't redirect to the user directly to the page profile using Magic Links on signIn.

## Describe the solution you'd like

Be able to add dynamic URIs on `Additional Redirect URIs`

## Describe alternatives you've considered

Created a special page for it to deal it on the client-side, but it also created multiple redirects to the user, breaking the "magic" of magic links UX to redirect the user directly to the page that the user needs to see as soon as the user reaches the website.

**Comment by J0** [comment]
Hey!

This should now be supported via wildcard [redirect URIs](https://mobile.twitter.com/supabase/status/1539561445414805506) so you should be able to  add the following:

`https://mysite.com/users/*`

and redirect to `https://mysite.com/users/123`

Let me know if there are still issues or anything that I've missed.

Thanks!
