### ISSUE TITLE
redirectTo on signIn/signUp not working (for email + password, Google & GitHub)

### ISSUE THREAD

**Issue by joe-ashwell** [supabase/supabase#5663]
# Bug report
As the title suggests, redirectTo is not working for any of my auth methods.

## To Reproduce
1. Correct base URL is set up in Supabase auth settings
2. Add the redirectTo option to signIn methods, e.g.:
await supabase.auth.signIn(
      {
        provider: "google",
      },
      { redirectTo: "https://example.com/app" }
    );

3. User can successfully sign in/up, they're just not redirected.

## Expected behavior
After sign in, user is redirected to the stated page

## System information
- MacOS
- Firefox & Chrome
- Version of supabase-js: 1.30.6
- Version of Node.js: v14.17.1
- Version of supabase/gotrue-js: 1.22.2

## Additional context
I've read some other issues raised related to this and understand it may be more of an issue with gotrue(?). But I've followed every suggestion so far on issues i've found related to this and have had no success as of yet.

As a side note, I just wanted to say, that overall I love the product. This one issue is just driving me mad! I'm currently using a useEffect hook as a work around, but it's really not ideal.

**Comment by bnjmnt4n** [comment]
Can you confirm that your `redirectTo` URL is either: a URL path with the same origin and hostname as the site URL, or an exact match of one of the additional redirect URLs?

**Comment by joe-ashwell** [comment]
Hey, @bnjmnt4n sorry for the delayed response - I didn't see the notification for this pop up. Yes, I confirm that the redirectTo has the same origin as the hostname url in supabase settings.

**Comment by emschwartz** [comment]
I am seeing this same issue. For me, the redirect works with email sign-ins but not with Google.

**Comment by reedrosenbluth** [comment]
I'm also seeing this issue. Redirect not working with email sign ins

**Comment by olefirenko** [comment]
I am also having the same issue

**Comment by 10000multiplier** [comment]
same here

**Comment by awalias** [comment]
hey @joe-ashwell (and also anyone else experiencing the issue) could you confirm the values you have for:

1. `redirectTo` option
2. `Site URL` in the auth settings page
3. `Additional redirect URIs` in the auth settings page 

if not comfortable sharing publicly the exact values, feel free to share via: https://app.supabase.io/support/new

**Comment by kangmingtay** [comment]
Hey everyone, just a heads up, the `redirect_to` param only works for oauth logins and not password-based / magiclink / phone otp sign-ins. This is because for password-based / magiclink / phone otp sign-ins, we make a POST request to gotrue and redirecting the response would change it to a GET request, which means that the response body would be lost.

**Comment by kiwicopple** [comment]
Thanks @kangmingtay - I have added a note in the docs in these PRs: 

- https://github.com/supabase/supabase/pull/5999
- https://github.com/supabase/gotrue-js/pull/253

**Comment by fanclubfm** [comment]
@kangmingtay @kiwicopple I don't think it is true that redirectTo is only used for OAuth flow.  
await supabase.auth.api.resetPasswordForEmail("email@example.com") without redirect to will give reset let you recover your email and redirect you to localhost:3000 for example .
If you provide redirectTo, it will redirect you to that specific page when you click the link in the email.
await supabase.auth.api.resetPasswordForEmail("email@example.com",{
        redirectTo: `${window.location.origin}/recovery/`,
      } )

The same seems to hold true for signUp with email+password.  I am successfully using redirectTo to send back user to page where they came from.  For example if they use my login component and they are on localhost:3000/examplepage , if that url is in redirectTo , clicking confirm email link will redirect back to that page.  Without redirect it will just send you to rool.

**Comment by 10000multiplier** [comment]
It would also be nice if a `Site URL` like mymobileapp:// to redirect to a mobile app worked.

Using supabase for a password based auth flow on mobile is just not possible otherwise.

**Comment by kangmingtay** [comment]
hey @fanclubfm, this is because both cases you mentioned are GET requests already so we can redirect the user. 

We return the tokens in the response body of the POST request (see `POST /token?grant_type=password` in gotrue). If we attempt to redirect the POST request, it will get converted into a GET and the response body (which contains the tokens) will be dropped.

**Comment by emschwartz** [comment]
For me, this is what's working / not working:

| Base Url | Path | Auth Provider | `redirectTo` Works |
|---|---|---|---|
| Site URL | Root | Google | ✅ |
| Site URL | Root | Email | ✅ |
| Site URL | Non-Root | Google | ❌ |
| Site URL | Non-Root | Email | ✅ |
| Additional URL | Root | Google | ✅  |
| Additional URL | Root | Email | ✅  |
| Additional URL | Non-Root | Google | ❌ (redirected to Site URL root) |
| Additional URL | Non-Root | Email | ❌ (redirected to Site URL root) |

I know that the additional URLs only work if they exactly match the `redirectTo`, which I think is undesirable behavior but not as much of a blocker for me as Google sign-in not working properly with the Base URL.

I can share the exact URLs via the link @awalias shared if that would be helpful.

I'm using supabase-js and the `supabase.auth.signIn` method.

**Comment by joe-ashwell** [comment]
Hey all, apologies @awalias I didn't see the notification.

I confirm that I did indeed have all those values populated with the correct info. I finally got to the root of the issue.

I was protecting the page via serverside props and for some reason this just stops redirectTo from working (I have no idea why). As soon as I stripped the following out of the page, redirectTo worked perfectly as expected.

// Protect the route for users only
```
export const getServerSideProps = async ({ req }) => {
  const { user } = await supabase.auth.api.getUserByCookie(req);

   if (!user) {
     return {
       redirect: {
         permanent: false,
         destination: "/",
      },
       props: {},
     };
   } else {
     return { props: {} };
   }
 };
```

**Comment by geordidearns** [comment]
> Hey all, apologies @awalias I didn't see the notification.
> 
> I confirm that I did indeed have all those values populated with the correct info. I finally got to the root of the issue.
> 
> I was protecting the page via serverside props and for some reason this just stops redirectTo from working. As soon as I stripped the following out of the page, redirectTo worked perfectly as expected.
> 
> // Protect the route for users only
> 
> ```
> export const getServerSideProps = async ({ req }) => {
>   const { user } = await supabase.auth.api.getUserByCookie(req);
> 
>    if (!user) {
>      return {
>        redirect: {
>          permanent: false,
>          destination: "/",
>       },
>        props: {},
>      };
>    } else {
>      return { props: {} };
>    }
>  };
> ```

I'm having this issue also. My use is is similar, but wanting to automatically redirect if a logged-in user lands on a index route. Seems to be the server side props in next.js

**Comment by Ghandus** [comment]
I'm having the same issue where using the google provider and the redirect option, it does not properly redirect to anything I specify in the redirectTo parameter.

currently running locally i have my Site URL set to http://localhost:8100
and also Additional redirect URLs to all my routes.

I tried putting lots of different urls in the redirect parameter, even external ones, yet it gets completely ignored.

Any update on this topic maybe?

**Comment by vpicone** [comment]
I found that using the window origin helps ensure the URL matches perfectly in dev and prod. Once the URL origin matched my Site URL exactly, the redirectTo property started to work.

```
    const { data, error } = await supabaseClient.auth.api.resetPasswordForEmail(
      email,
      {
        redirectTo: `${window.location.origin}/account/password-recovery`
      }
    );
    ```

**Comment by kangmingtay** [comment]
hey @Ghandus and @vpicone, please refer to our documentation on how to correctly configure your redirect urls [here](https://supabase.com/docs/reference/tools/reference-auth#uri_allow_list). We now support wildcards in the redirect urls which should reduce the number of redirect urls you need to whitelist if they have a similar path / domain.

There is an ongoing issue where if you add a trailing slash the the end of the redirect url, the pattern matching would fail because it detects the slash as a separator. We are putting out a fix for this soon but as a sanity check, you'd wanna ensure that the `redirectTo` url does not include trailing slashes.

**Comment by Ghandus** [comment]
@vpicone, @kangmingtay thanks for your inputs.
I'm still not sure I'm doing something wrong:
My Site URL in supabase is set to my localhost (http://localhost:8100)
As redirect URLs I added: 'http://localhost:8100/*' using the wildcard.
When I call 
`const { session, error } = await this.supabase.auth.signIn(
        {provider: 'google'},
        { redirectTo: `${window.location.origin}` } // http://localhost:8100
      );`
from this URL: 'http://localhost:8100/login', I would expect to be redirected to that URL (http://localhost:8100).
Yet I am still redirected to 'http://localhost:8100/login', the URL where I came from.

Sorry if that is something obvious that I am missing here 🤔

**Comment by Ghandus** [comment]
@kangmingtay 
I think I figured out what the issue was in my case:
On my Login Page I have the following code:
```javascript
async loadUser() {
    const user = await this.supabase.auth.user();

    if (user) {
      this.currentUser$.next(user);
    } else {
      this.currentUser$.next(false);
    }
  }
```

where 
```javascript
private currentUser$: BehaviorSubject<User | boolean> = new BehaviorSubject(
    null
  );
```

The problem I noticed is, that the call `this.supabase.auth.user()` is not actually async and will not immediately return the user object. This caused my redirect to fail, because it thought no user was actually signed in.

If I wait some time
```javascript
async loadUser() {
    const user = await this.supabase.auth.user();

    setTimeout(() => {
      if (user) {
        this.currentUser$.next(user);
      } else {
        this.currentUser$.next(false);
      }
    }, 200);
  }
```

Supabase has time to actually return the user and will populate it properly.
There seems to be something wrong on supabase site still though, because if you believe the the function, it _should_ return the user instantly.

**Comment by fnoyanisi** [comment]
In my case, (during the development), replacing `localhost:9000` with `window.location.origin` has solved the issue.

My code looks like

```
    getRedirectUrl() {
      var url = window.location.origin + "/redirect?path=" + this.$route.path.substring(1)

      if (this.$route.path == "/detail") {
        url = url + "&address=" + this.$route.params.address
      }

      return url
    }

    async handleLoginSp(provider) {
      try {
        const params = {
          provider: provider,
          redirectTo: this.getRedirectUrl()
        }
        await loginWithSocialProvider(params)
      } catch (error) {
        alert(error.message);
      }
    }

  const loginWithSocialProvider = async (params) => {
    const { user, error } = await supabase.auth.signInWithOAuth({
      provider: params.provider,
      options: {
        redirectTo: params.redirectTo
      }
    });
    if (error) throw error;
    return user;
  }
```

I could not see Supabase spitting any error messages and (I think) the `redirectTo` target was silently ignored. Upon successful login, the user is redirected to a component (I use Vue) whose only work is to `this.$router.push()` the last page the user was on, i.e. the page the user attempted to sign in.

I did not enter any *Redirect URLs* in Supabase > Authentication > URL Configuration page.

**Comment by ilianherzi** [comment]
I'm still running into this issue. Essentially, I cannot redirect to an arbitrary website (or any for that matter).
I'm also noticing that the promise is finishing before authentication is finished. Is this behavior expected?
```javascript
const {data, error} = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: "https://duckduckgo.com/",
        scopes:
          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
      },
    })
throw Error()
```

**Comment by kangmingtay** [comment]
hey @ilianherzi, have you ensured that you have added the `redirectTo` url to the allow list in the dashboard? you should be able to find the allow list [here](https://app.supabase.com/project/_/auth/url-configuration)

> I'm also noticing that the promise is finishing before authentication is finished. Is this behavior expected?

Yes, this is expected because the `signInWithOAuth` method merely redirects you to the oauth provider's website to authenticate. Once the user has authenticated with the oauth provider, the oauth provider will make a request to the callback endpoint on gotrue. If the callback endpoint is successful, gotrue will redirect the user to the `redirectTo` url specified in the `signInWithOAuth` method. This is part of the OAuth2.0 flow.

**Comment by jasonwilmot** [comment]
If it helps anyone, at least with Google Auth, when redirecting to root ( e.g. http://localhost:3000 ) , put a forward slash in redirectTo ( e.g. `${window.location.origin}/` ) as well as one of the Redirect URLs ( e.g. http://localhost:3000/ ).  Without the forward slash, it kept redirecting to my Site URL

**Comment by mibacode** [comment]
My issue was that I only had only configured my redirect URL's starting with `http`, and not `https`.

**Comment by joshsmith** [comment]
> My issue was that I only had only configured my redirect URL's starting with `http`, and not `https`.

This was also my issue, even using `http://localhost:3000` as the site URL and the same in the callback. I'm guessing that they automatically change this internally to `https`.

**Comment by joshsmith** [comment]
Actually, this looks to be terribly broken. With an `http://localhost` I can only `redirectTo` `https://localhost:3000` and vice versa. No idea how this is remotely possible.

**Comment by kangmingtay** [comment]
@joshsmith that shouldn't be the case, can you create a support ticket through https://supabase.help so we can take a look at your project?

**Comment by jonathanlal** [comment]
im slightly confused by this too. What's the point of emailRedirectTo if the email templates override it? Works locally but not in prod. Js client .signUp() function

**Comment by piotr-jura-udemy** [comment]
Sorry to say, but this is TERRIBLY broken. 

Email template:
```
<h2>Magic Link</h2>

<p>Follow this link to login:</p>
<p><a href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=magiclink">Log In</a></p>
```

No matter what I set in URL Configuration and what I use in `emailRedirectTo`, it's always using the Site URL.

**Comment by camstuart** [comment]
Some great info here. For me I am using the `auth-ui-react` (and `auth-ui-shared`) which means adding `redirectTo` to the props:

```
<Auth
          supabaseClient={supabase}
          appearance={{ theme: ThemeSupa }}
          providers={["google"]}
          redirectTo={window.location.origin + '/dashboard/'}
        />
```

Once I added that, it worked perfectly

**Comment by ryanleecode** [comment]
> Sorry to say, but this is TERRIBLY broken.
> 
> Email template:
> 
> ```
> <h2>Magic Link</h2>
> 
> <p>Follow this link to login:</p>
> <p><a href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=magiclink">Log In</a></p>
> ```
> 
> No matter what I set in URL Configuration and what I use in `emailRedirectTo`, it's always using the Site URL.

Im still getting this

**Comment by tomaspozo** [comment]
Hey @awalias can we please re open this? Is not working with the `emailRedirectTo` param on sign up. It always get replaced by the site url set up in the dashboard.

**Comment by albertocubeddu** [comment]
+ 1; I'm not able to have the { .SiteURL } being replaced by the redirectTo.

# Environment
Vercel + NextJS 

# Code Example
Code: 

`<Auth
                                supabaseClient={ supabase }
                                view="magic_link"
                                appearance={ {
                                    theme: ThemeSupa,
                                    variables: {
                                        default: {
                                            colors: {
                                                brand: '#6D28D9',
                                                brandAccent: '#6D28D9',
                                                inputText: '#FFF'
                                            },
                                        },
                                    },
                                } }
                                showLinks={ false }
                                providers={ [] }
                                redirectTo={ getBaseUrl() + "/auth/callback" }
                            />`

Where getBaseUrl()

`  export function getBaseUrl() {
  // Assuming VERCEL_ENV and VERCEL_URL are set correctly by Vercel or manually.
  if (process.env.NEXT_PUBLIC_VERCEL_ENV === "production") {
    // If we are in production, return the production URL
    return `https://mywebsite.com.au`;
  } else if (process.env.NEXT_PUBLIC_VERCEL_URL) {
    // For previews and development deployments on Vercel, prefix VERCEL_URL with https://
    return `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`;
  } else {
    // Fallback for local development
    return `http://localhost:3000`;
  }
}
`

# Supabase side 
Authentication -> URL Configuration
Site URL:  http://mywebsite.com
Redirect: https://**vercel.app/*/*
https://*-xxx.vercel.app/**
https://my-web-ps0epxemi-xxx.vercel.app

## Email Templates 
`
<h2>Magic Link</h2>

<p>Follow this link to login:</p>
<p><a href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=magiclink&next=/dashboard">Log In</a></p>
`


The {{ .SiteURL }} on the email template is NEVER replaced by the "redirecto" 
https://supabase.com/docs/guides/auth/concepts/redirect-urls#overview

Therefore the only way i can use the Vercel Preview, is to copy paste the vercel preview deployment onto the SITE URL.

**Comment by kangmingtay** [comment]
hey @albertocubeddu, the `{{ .SiteURL }}` never gets replaced by the `redirectTo` value at all - that is expected. However, we do provide a `{{ .RedirectTo }}` param in the email template which will use the `redirectTo` value if it's added to the allow list

this is the full list of email template variables that you can include (see `{{ .RedirectTo }}` at the bottom)
![image](https://github.com/supabase/supabase/assets/28647601/2fa09794-671f-47d6-bc71-c0a30ea3644f)

**Comment by albertocubeddu** [comment]
You're a lifesaver 🥇 
 I've got stuck with this introduction and I supposed that the SiteURL would change based on the configuration: 

"By default, the user will be redirected to the [SITE_URL](https://supabase.com/docs/guides/auth/concepts/redirect-urls) but you can modify the SITE_URL or add additional redirect URLs to the [allow list](https://supabase.com/dashboard/project/_/auth/url-configuration). Once you've added necessary URLs to the allow list, you can specify the URL you want the user to be redirected to in the redirectTo parameter."

I'm adding a pull request to update the documentation: https://github.com/supabase/supabase/pull/22608

Hopefully, it will assist others who share (wrongly) the same supposition.

**Comment by vyas-meet** [comment]
While developing locally in next.js server actions, using headers().get("origin") which results in https://localhost:3000/ does not work. 

using 127.0.0.1:3000 works instead.

![Code_mKetv4wS8V](https://github.com/supabase/supabase/assets/58567268/1a73a470-d292-4554-a9aa-622d9b8b4db3)

**Comment by Bogzzz** [comment]
Having issues with my redirectTo not working. I see that i send it but in my google email the link shows up some random stuff which does not even open. Any ideas ?

**Comment by Ziinc** [comment]
Please open a new issue with the necessary debugging details instead of reviving old closed ones, thanks.
