### ISSUE TITLE
Update the icon of dark mode - light mode icon of sidebar

### ISSUE THREAD

**Issue by adarshajit** [supabase/supabase#5675]
## Update the icon of `dark-mode/light-mode` in the sidebar

Observe the last icon in the sidebar. This is a dark mode - light mode toggle. The icon is misleading

## Screenshot
![Screenshot from 2022-02-26 14-39-37](https://user-images.githubusercontent.com/50659234/155845542-dacbcef5-6735-4684-b727-51e967f4c71c.png)

Instead of a user icon, it would be best if it's a sun icon and moon icon based on the theme applied

![Screenshot from 2022-03-06 15-23-04](https://user-images.githubusercontent.com/50659234/156918440-c6f77331-0eb9-43bb-a9cf-d138a38809c0.png)

**Comment by yeganathan18** [comment]
Can please provide a bit more information? I don't get the icon part. Do you mean when we select dark, it's showing white as icon near to it and vice versa?

**Comment by adarshajit** [comment]
@yeganathan18 Please take a look as I have updated my issue. I would like to take this up but I'm relatively new to this codebase. I would appreciate it if you could point out the exact file the above-mentioned changes should be made. Thanks.

**Comment by MildTomato** [comment]
Just in case some people reading this are unaware, when self-hosting the Studio dashboard, the popover menu only has the theme option, whereas the hosted version of the app has additional items.

The Popover was probably added in as a way to avoid adding in an account page for self hosting at the time. We can improve on this now, there's probably no reason we couldn't have a self hosted account page as there's possibly other options for self hosted we can add now.

**Comment by Hallidayo** [comment]
@MildTomato - I can show the profile section on the local builds so this issue can be closed? by default the user is John Doe:

<img width="1155" alt="Screenshot 2022-06-29 at 11 45 54" src="https://user-images.githubusercontent.com/22655069/176418646-75563a38-5a53-4b57-a694-bf9c45127382.png">

**Comment by jalalbmnf** [comment]
Hi, there is a problem, when I change Dark mode to System or light mode, the icon does not change also there is no gap between icon and text

https://github.com/supabase/supabase/assets/53921355/307d4b6a-5fd8-41dc-b2a8-910702015ee3
