### ISSUE TITLE
Prisma migration with Quoted Types breaks realtime.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#5685]
# Bug report

I apologize for not understanding the details of Prisma and migrations and their impact on Supabase in general (I've seen general issues with permissions).
A user in Discord had an issue with Realtime subscribing correctly using the service role key, but not getting any updates. After a bit of back and forth they mentioned Prisma.  They then created a clean Supabase instance, and realtime worked.  Then they "added" Prisma and "pushed" and realtime worked.   Then they did a "migrate" and realtime stopped sending updates on successful subscriptions.

I'm putting this here for someone with more knowledge of Prisma and its compatibility with Supabase, in particular migrations, to classify as appropriate.

Not sure if this is a Prisma issue in general, or a specific issue with realtime and Prisma.

## To Reproduce

Long discord discussion trying to narrow issue:
https://discord.com/channels/839993398554656828/947271562623610920
Edit:
A second discord user had similar issue with no response from realtime, and just confirmed they were using Prisma too....
https://discord.com/channels/839993398554656828/869406062036529193/944933974751461396

## Expected behavior

Just raising this to at a minimum flag Prisma/realtime users.  Not sure if this is just info, or a bug.

**Comment by ShooTeX** [comment]
the access privileges for tables look different if prisma creates them, could that be a problem?

table created by prisma:
```
 Schema |    Name    | Type  |       Access privileges        | Column privileges | Policies
--------+------------+-------+--------------------------------+-------------------+----------
 public | Tournament | table | postgres=arwdDxt/postgres     +|                   |
        |            |       | anon=arwdDxt/postgres         +|                   |
        |            |       | authenticated=arwdDxt/postgres+|                   |
        |            |       | service_role=arwdDxt/postgres  |                   |
```

table created in dashboard in a new project:
```
 Schema | Name | Type  |           Access privileges           | Column privileges | Policies
--------+------+-------+---------------------------------------+-------------------+----------
 public | test | table | postgres=arwdDxt/supabase_admin      +|                   |
        |      |       | supabase_admin=arwdDxt/supabase_admin+|                   |
        |      |       | anon=arwdDxt/supabase_admin          +|                   |
        |      |       | authenticated=arwdDxt/supabase_admin +|                   |
        |      |       | service_role=arwdDxt/supabase_admin   |                   |
```

**Comment by ShooTeX** [comment]
so, I somehow got it to work, I don't know which step was the problem, I'll just describe what I did:

1. create two projects/databases, one for [prismas shadow database](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database), one for your data (main)
2. link both databases with prisma as described in prismas docs
3. create a dev migration `prisma migrate dev`
4. delete the main project
5. create new main project and deploy migration `prisma migrate deploy`

i don't know which of those steps where necessary to make it work, could be the missing shadow database or something weird is happening with `prisma migrate dev` which breaks realtime. I didn't test `prisma migrate dev` again, but I will update if it breaks again.

**Comment by w3b6x9** [comment]
There is a known issue where Realtime doesn't work with quoted custom types and I think Prisma automatically generates quoted types. We are in the process of fixing the issue but the workaround right now is to rename types to exclude quotation marks.

**Comment by w3b6x9** [comment]
I'll post an update here when it's fixed.

**Comment by ShooTeX** [comment]
not using type names starting with capital letters in the prisma schema works, I finally get subscription events 🎉

**Comment by GaryAustin1** [comment]
Sort of puzzled how your intermediate step of pushing worked… did it not have same types?   I’m going to change title reflect type issue for others.

**Comment by Arcrueid** [comment]
@ShooTeX any example?

Using `@@map` would it work?
```
model Post {
  id                   Int      @id @default(autoincrement())
  title                String
  createdAt            DateTime @default(now()) @map("created_at")

  @@map("posts")
}
```

or should it be like this
```
model post {
  id                   Int      @id @default(autoincrement())
  title                String
  created_at           DateTime @default(now()) 

  @@map("posts")
}
```

I have had this problem for months and I have managed only with `prisma db push`

**Comment by ShooTeX** [comment]
> @ShooTeX any example?
> 
> Using `@@map` would it work?
> 
> ```
> model Post {
>   id                   Int      @id @default(autoincrement())
>   title                String
>   createdAt            DateTime @default(now()) @map("created_at")
> 
>   @@map("posts")
> }
> ```
> 
> or should it be like this
> 
> ```
> model post {
>   id                   Int      @id @default(autoincrement())
>   title                String
>   created_at           DateTime @default(now()) 
> 
>   @@map("posts")
> }
> ```
> 
> I have had this problem for months and I have managed only with `prisma db push`

models shouldn't be a problem. My problem was that I had an enum starting with a capital, that was used in a model. `@@map` should probably work. I'm not completely sure, but I think I also had to delete the database with broken subscriptions and create a new one, just renaming and migrating it didn't work.

**Comment by w3b6x9** [comment]
I want to give an update on this.

We added instructions on how to get unblocked on this issue in the short term: https://supabase.com/docs/guides/integrations/prisma#confirming-realtime-functionality

We have a fix on the way and we'll try and deploy it to all existing projects as soon as we can.

Thanks to everyone for your patience!

**Comment by Uninen** [comment]
It would be helpful to link this ticket to the docs; it's currently not easy to find the status of this issue.

**Comment by Hallidayo** [comment]
@Uninen I can add a link for this issue under the [Confirming Realtime Functionality](https://supabase.com/docs/guides/integrations/prisma#confirming-realtime-functionality) section of the documentation.

**Comment by w3b6x9** [comment]
> @Uninen I can add a link for this issue under the [Confirming Realtime Functionality](https://supabase.com/docs/guides/integrations/prisma#confirming-realtime-functionality) section of the documentation.

@Hallidayo thanks for contributing! approved your pr and merged.

**Comment by janpio** [comment]
> There is a known issue where Realtime doesn't work with quoted custom types and I think Prisma automatically generates quoted types.

Is this something Prisma is doing _wrong_ and could fix? If so, I would love to have a minimal reproduction example (either here or as an issue in the Prisma repo) so we can take a deeper look.

**Comment by w3b6x9** [comment]
> Is this something Prisma is doing wrong and could fix?

@janpio nope, this is an issue on Realtime's end and we have a fix for it. We're just waiting to deploy.

**Comment by janpio** [comment]
@w3b6x9 Ok, then I just misunderstood the docs section 👍

**Comment by w3b6x9** [comment]
@janpio appreciate you checking in!

**Comment by janpio** [comment]
(Feel free to ping me for technical problems with Prisma ORM any time.)

**Comment by jfeiwell** [comment]
> > Is this something Prisma is doing wrong and could fix?
> 
> @janpio nope, this is an issue on Realtime's end and we have a fix for it. We're just waiting to deploy.

have you deployed yet?

**Comment by w3b6x9** [comment]
Update: The fix has been deployed to all Supabase projects. No further actions required on your part. It should just work now.

**Comment by LivioGama** [comment]
That was not it, I decided to write a whole medium post for avoiding you waste time in the future: https://liviogamassia.medium.com/using-supabase-rls-with-firebase-auth-custom-auth-provider-357eaad9c70f
