### ISSUE TITLE
API page does not load on web instance

### ISSUE THREAD

**Issue by TurtleKwitty** [supabase/supabase#5687]
# Bug report

## Describe the bug

I saw there was a similar, but not same, bug reported a couple days ago about the same issue in a self-hosted setup, however this is happening in the supabase hosted setup as well. 
I am getting the same errors when trying to call on the supabase js functions something very wrong is going on, but this only happens with supabase-js and the API page as far as I could tell, every other api and webpage works correctly including loading my tables for the same project in the web interface

## To Reproduce

Start a new supabase project from the web interface, go to API page

## Expected behavior

For the page to load without displaying an error. 
**Firefox**
 "Error: [500] An error has occured: NetworkError when attempting to fetch resource." on the webpage
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [supabase url here]. (Reason: CORS request did not succeed). Status code: (null)."

**Chromium**
 "Error: [500] An error has occured: Failed to fetch" on the webpage
"GET [supabase url here] net::ERR_NAME_NOT_RESOLVED" in console

## Screenshots

![Screenshot from 2022-02-27 01-55-21](https://user-images.githubusercontent.com/5491534/155871886-44d139a1-6093-46d4-9713-b7f03bfa8aed.png)

## System information

- OS: Ubuntu LTS 20.04
- Browser: Firefox 97.0 & Chromium 98.0.4758.102

## Additional context

In case it might be relevant my project id is gbqbzyynoyzlacameiwf and this has been happening since the creation of the project but I had assumed it was caused by the project not being entirely spun at first

**Comment by kiwicopple** [comment]
Can you please try to "restart" your instance (Settings > General > Restart)? I think there must be something wrong with your API server

If that doesn't work, could you please reach out to support? https://app.supabase.io/support/new

**Comment by kiwicopple** [comment]
Closing this for now, but feel free to comment here if you're still experiencsing the error @TurtleKwitty

**Comment by laleet-avaiya** [comment]
same issue I am Also facing.
I also did restart but that doesn't help.

<img width="746" height="128" alt="Image" src="https://github.com/user-attachments/assets/0809d8c4-043e-4bac-8d62-729c6a071303" />

<img width="1412" height="625" alt="Image" src="https://github.com/user-attachments/assets/d84ed99f-48b9-45cf-99cb-6bd8febe727c" />
