### ISSUE TITLE
Raspberry Pi - “docker-compose up”: command not found

### ISSUE THREAD

**Issue by micahburnside** [supabase/supabase#5698]
# Bug report

## Describe the bug

In terminal, running the command ‘docker-compose up’ results in “command not found”

## To Reproduce

Get the code
git clone --depth 1 https://github.com/supabase/supabase

Go to the docker folder
cd supabase/docker

Copy the fake env vars
cp .env.example .env

Start
docker-compose up

## Expected behavior

I expected a successful command. LocalHost is 404’d.

## System information

- OS: [Raspbian GNU / Linux 10 (buster)]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: latest
- Version of Node.js: latest

## Additional context

I’m using a Raspberry Pi 4 and docker does work with other docker images.

**Comment by darora** [comment]
You need docker-compose to be installed https://supabase.com/docs/guides/hosting/docker#before-you-begin

**Comment by darora** [comment]
https://github.com/supabase/supabase/pull/5700 adds an explicit link to the installation page

**Comment by micahburnside** [comment]
I already have docker-compose installed.

**Comment by micahburnside** [comment]
> You need docker-compose to be installed https://supabase.com/docs/guides/hosting/docker#before-you-begin

I have docker-compose installed.

**Comment by bnjmnt4n** [comment]
@micahburnside in that case there's probably an issue with your installation somewhere: a failure to run the `docker-compose up` command in your terminal isn't directly related to Supabase or its docker setup. You might need to check if your docker binaries are in the PATH.

**Comment by micahburnside** [comment]
You are correct. 

There’s a specific arm7 installation for docker-compose. It just worked after installing using the correct curl command.

sudo curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose
