### ISSUE TITLE
Raspberry Pi ‘docker-compose up’ command not found

### ISSUE THREAD

**Issue by micahburnside** [supabase/supabase#5702]
#Bug report

Describe the bug

In terminal, running the command ‘docker-compose up’ results in “command not found”

To Reproduce

install Git, Docker, docker-compose

Get the code
git clone --depth 1 https://github.com/supabase/supabase

Go to the docker folder
cd supabase/docker

Copy the fake env vars
cp .env.example .env

Start
docker-compose up

Expected behavior

I expected a successful command. LocalHost is 404’d.

System information

OS: [Raspbian GNU / Linux 10 (buster)]
Browser (if applies) [e.g. chrome, safari]
Version of supabase-js: latest
Version of Node.js: latest
Additional context

I’m using a Raspberry Pi 4 and docker does work with other docker images.

**Comment by kiwicopple** [comment]
Looks like this was resolved: https://github.com/supabase/supabase/issues/5698#issuecomment-1053854154

I'll close this but feel free to drop a comment here again if it's still an issue 👍
