### ISSUE TITLE
Mistakes in updateUserById() documentation

### ISSUE THREAD

**Issue by stuartkumar0630** [supabase/supabase#5712]
# Bug report

## Describe the bug

There are a couple of syntax errors in the documentation for the `updateUserById()` method [here](https://supabase.com/docs/reference/javascript/auth-api-updateuserbyid).

- An extra brace on line 3 in `{ email: 'new@email.com' } }`
- All the parameters in the example are wrapped in braces as `updateUserById({ uid: ..., attributes: ....})`, but the method declaration in [go true](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L722)  indicates that only the attributes should be passed in as an object.

Note these problems apply to all usages of the `updateUserById()` method on its documentation page.
## To Reproduce

See syntax and API errors when running example code from [docs](https://supabase.com/docs/reference/javascript/auth-api-updateuserbyid).

## Expected behavior

I believe the example should be given as something like
`    const { data: user, error } = await supabase.auth.api.updateUserById(
        user_id,
        { email: 'new@email.com'}
    );
`
## Screenshots
![Screenshot 2022-02-28 at 09 26 49](https://user-images.githubusercontent.com/16143994/155958255-e34666d9-89ae-4568-9635-9ac3e7b558c0.png)

**Comment by devnamrits** [comment]
Hi @kiwicopple, I've raised PR for this.
[https://github.com/supabase/supabase/pull/5823](url)

Please review and approve it and merge it.

cc: @stuartkumar0630

**Comment by kiwicopple** [comment]
Fixed by @devnamrits https://github.com/supabase/supabase/pull/5823

🚀
