### ISSUE TITLE
resetPasswordForEmail acting in an unexpected way

### ISSUE THREAD

**Issue by charlesline** [supabase/supabase#5729]
# Bug report

## Describe the bug

When executing resetPasswordForEmail a password reset email is sent to the intended recipient twice, with different tokens in each. In my tests, the first appears to be a valid token but the second one the redirect contains the message "#error_code=404&error_description=User+not+found". 

## To Reproduce

Steps to reproduce:

1. use the api with "const {data, error}  = supabase.auth.api.resetPasswordForEmail('registered_user@email.address')
2. Watch the emails arrive

## Expected behavior

I expect the user email address to receive one email with a valid token

**Comment by charlesline** [comment]
Update: Latest usage just now does not exhibit the same behaviour.

**Comment by davideluque** [comment]
I believe this happens when you click the link you get via email twice.

My guess is that when supabase redirects you to your website, the token is invalidated.
