### ISSUE TITLE
Full text indexing for search

### ISSUE THREAD

**Issue by arashz** [supabase/supabase#574]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently Firebase users are required to use outside services such as Elastic search or Algolia. Supabase could add this as a differentiating feature since the existing Postgres backend allows for this natively.

## Describe the solution you'd like

User friendly and visual way to create full text index on tables

**Comment by kiwicopple** [comment]
Hey @arashz - agreed. We're thinking about renaming some of our filters to make this even clearer:

https://github.com/supabase/supabase/discussions/534

Once we have done that we'll do a full write up + docs.

> User friendly and visual way to create full text index on tables

Note that you can run FTS dynamically against documents like this:

```sql
select *
from table
where to_tsvector('fat cats ate fat rats') @@ tsquery('fat & rat'); -- returns true
```

and the equivelent using the supabase libs:

```js
const { data, error } = supabase
  .from(table)
  .select()
  .fts('fat cats ate fat rats', 'fat & rat') // returns true
```

So I'm guessing that the solution you would like to see is some way to add indexes within the interface for preprocessing?

If you have any ideas what this should look like feel free to add suggestions here and we'll incorporate them into the dashboard
