### ISSUE TITLE
Docs Server Build Error - algolia.appId is required

### ISSUE THREAD

**Issue by Hallidayo** [supabase/supabase#5762]
# Bug report

## Describe the bug

I've recently forked supabase to work on an issue. I've cloned the repository to my local system and followed [this](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md) guide. When I run `yarn build` for the docs development server I get the following error in my terminal:

<img width="569" alt="Screenshot 2022-03-02 at 15 20 48" src="https://user-images.githubusercontent.com/22655069/156393498-a9ae5f50-6d11-4f1f-87b1-9b5aea94e128.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow [this](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md) guide up until Start a Development Server
2. Go to the Supabase Docs Development Server section
3. Run the `yarn build` command
4. The error I am experiencing should appear

## Expected behavior

The development server should build and then the command `yarn start` is ran which should start the development server.

## Screenshots
<img width="569" alt="Screenshot 2022-03-02 at 15 20 48" src="https://user-images.githubusercontent.com/22655069/156393467-bcd9aae9-e6f9-47e4-92a0-e3062c84e378.png">

## System information

- OS: macOS
- Version of Node.js: 16.4.0 LTS

**Comment by MildTomato** [comment]
I'm not sure anyone on the team is using yarn at the moment with these sites, so I can't really confirm if there's any issue with that.

@Hallidayo have you followed these steps yet?

**Comment by Hallidayo** [comment]
@MildTomato - Thank you for the reply.

> https://github.com/supabase/supabase/blob/master/web/README.md
@Hallidayo have you followed these steps yet?

I've just done the above now and then tried `yarn build` but again the same error is appearing for me.

I've also tried with npm as well but same error as with yarn.

Error I am getting: `[ERROR] ValidationError: "algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration`

Is their an Algolia appId that I could try?

**Comment by Isaiah-Hamilton** [comment]
The problem seems to be that we upgraded the docSreach but forgot to add `appId` to the `docusaurus.config.js` file.

The `docusaurus.config.js` file should look like this:
```js
algolia: {
      appId: '<NEW_APP_ID>',
      apiKey: '<NEW_SEARCH_API_KEY>',
},
```

But currently we have it like this:
```js
algolia: {
      apiKey: '766d56f13dd1e82f43253559b7c86636',
      indexName: 'supabase',
},
```

There is more information in the [docusaurus docs](https://docusaurus.io/pt-BR/blog/2021/11/21/algolia-docsearch-migration).

**Comment by Hallidayo** [comment]
Hi Guys,

Is this still being looked into?

**Comment by kiwicopple** [comment]
You're welcome to help here @Hallidayo - I don't know what the `appId` should be in this case - perhaps just `supabase`?

**Comment by Isaiah-Hamilton** [comment]
Issue closed with https://github.com/supabase/supabase/pull/5989
