### ISSUE TITLE
Extension titles overflow their container

### ISSUE THREAD

**Issue by illright** [supabase/supabase#5763]
# Bug report

## Describe the bug

Database extension names are long strings without spaces. Sometimes it leads to the name overflowing the container and pushing the on/off switch out of the card (see screenshots).

## To Reproduce

1. Go to `https://app.supabase.io/project/<some-project-id>/database/extensions` from a 1280px-wide browser window
2. Scroll down to Extensions
3. See the name `ADDRESS_STANDARDIZER_DATA_US` overflow its container and push out the switch

## Expected behavior

The name of the extension and the switch remain within the card

## Screenshots

<img width="452" alt="two cards for database extensions, the text overflows in one of them" src="https://user-images.githubusercontent.com/15035286/156396219-00b124f6-67b8-4696-84de-76437046bf4d.png">

## System information

- OS: Windows
- Browser (if applies): Chrome 98.0.4758.102

**Comment by MildTomato** [comment]
Thanks @illright !

**Comment by adkood** [comment]
please assign it to me

**Comment by MildTomato** [comment]
@adkood go for it 😄

**Comment by MildTomato** [comment]
@adkood similar issue here as well if you want it #5779

**Comment by adkood** [comment]
Sorry I am having difficulties in understanding the task here can you please explain can you please elaborate more.

**Comment by MildTomato** [comment]
@adkood it's ok, I've added PR #5818 that fixes this, it was mostly just adding a [tailwind class`.truncate`](https://tailwindcss.com/docs/text-overflow#truncate) to the label
