### ISSUE TITLE
Type 'T[] | undefined' is not an array type

### ISSUE THREAD

**Issue by mtsdalmolin** [supabase/supabase#5767]
# Type 'T[] | undefined' is not an array type

## Describe the bug
I'm developing a small app with Typescript, NextJS and Supabase and I'm getting trouble when querying data.
I couldn't find anything that clarify that to me, so that's why I'm creating this issue.

The code I'm querying the data is the following:
```ts

type DBItem = {
  id: number
  image_url?: string
  set_bonus?: string
  options: Array<string>
  stats: Array<string>
  harmony_options: Array<string>
  set_pieces?: Array<string>
  class_requirements: Array<string>
  set_name?: string
  level: number
  lifeOptionLevel: number
  name: string
  type: string
  category: string
  luck: boolean
}

type Character = {
  id: number
  nickname: string
  user_id: number
  items: Array<DBItem | Item>
}

export async function getServerSideProps() {
  const { data: characters } = await supabase
    .from<Character>('characters')
    .select(`
      id,
      nickname,
      items(*)
    `)
    .eq('user_id', 1)

  return {
    props: {
      characters: [
        ...characters?.map(character => character)
      ]
    }
  }
}
```

I'm mapping characters because there are some fields that I want to modify before getting it as a prop inside the component. In this example, I made it as simple as possible, that's why I'm just returning `character` in map.

The line ` ...characters?.map(character => character)` throws me an error saying:
```diff
! Type 'Character[] | undefined' is not an array type. ts(2461)
```

The strange thing is that if I log `typeof characters`, it gives me `object`, but in the end, it works with `.map` method.
Maybe there's some typechecking mistake here or I'm just typing it the wrong way.

## System information

- node: 16.14.0
- supabase-js: ^1.30.7
- typescript: 4.5.5
- next: 12.1.0

**Comment by Symasia** [comment]
This isn't a bug with Supabase, you seem to understand this fact too. It has to do with this line:

```js
characters: [...characters?.map(character => character)]
```

You're using the optional chaining operator `?`, in other words, you're telling typescript that `characters` can be `undefined`, so the type of characters is `Character[] | undefined` which is not the type of an array.

**Comment by mtsdalmolin** [comment]
@Symasia Makes sense, but removing it, it throws me the `Object is possibly 'null'.ts(2531)` error instead.

Is there a way that I certify typescript that the value won't be nullish?

**Comment by gzoug** [comment]
@mtsdalmolin does 
characters: [...(characters?.map(character => character) ?? []) ]  
work for you?

**Comment by mtsdalmolin** [comment]
I guess I have to use something like that, @gzoug. I opted for the following version:
```js
characters: (characters ?? []).map(parseCharacterItems)
```

I thought I could do something more typewise. Anyway, thanks for giving me support @gzoug @Symasia.
