### ISSUE TITLE
The docs on storage have a broken link to the blog post

### ISSUE THREAD

**Issue by illright** [supabase/supabase#5769]
# Improve documentation

## Link 

https://supabase.com/docs/guides/storage#next-steps

## Describe the problem

One of the bullet points in the linked section is this:

> Read more about storage in our [blog post](https://supabase.com/docs/blog/2021/03/30/supabase-storage).

However, the link to this blog post is broken — perhaps, the blog post was deleted at some point

## Describe the improvement

Find the blog post and fix the link or remove the link altogether

**Comment by mayanhavoc** [comment]
Could I be assigned this issue? Should I just remove that part?

**Comment by Isaiah-Hamilton** [comment]
@mayanhavoc I already fixed this issue and have a pull request opened.
