### ISSUE TITLE
empty column name state in FK adder [minor]

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#5778]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/458736/155491495-27cd0868-db18-4b7f-ac9e-2f41c644438d.png">

and on the left side of the arrow here:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/458736/155491570-1dddba54-0118-4468-b83f-3084206e2cd6.png">

**Comment by phamhieu** [comment]
There are 2 errors on Column sidepanel:
- adding FK before entering the new column name will result in 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/458736/155491570-1dddba54-0118-4468-b83f-3084206e2cd6.png">
- Then if you edit the newly added FK, it will result in this
<img width="452" alt="image" src="https://user-images.githubusercontent.com/458736/155491495-27cd0868-db18-4b7f-ac9e-2f41c644438d.png">

cc @joshenlim
