### ISSUE TITLE
Studio: RLS policies which overflow the container length cause overflow menu to be hidden

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/supabase#5779]
# Bug report

## Describe the bug

Studio: RLS policies which overflow the container length cause overflow menu to be hidden.

## To Reproduce

1. Add a RLS policy with a long name and SQL check
2. The overflow menu with "Edit"/"Delete" buttons is hidden, and cannot be accessed

## Expected behavior

The overflow menu should be accessible.

## System information

- OS: Windows
- Browser (if applies): Firefox

**Comment by MildTomato** [comment]
The RLS policy name and also the definition both need to be truncated
