### ISSUE TITLE
Using "signIn" API call creates users in Auth.users table

### ISSUE THREAD

**Issue by ksnyde** [supabase/supabase#578]
I am running some unit tests and one of them was to try logging into the database with an invalid email and password. I did this and to my surprise, this invalid users started showing up in the web UI as users:

## Test script
![image](https://user-images.githubusercontent.com/980757/105436979-0dc4c500-5c15-11eb-9442-901291f035d0.png)

## Supabase Web UI
![image](https://user-images.githubusercontent.com/980757/105437034-2b922a00-5c15-11eb-90b7-5fa62e268952.png)

> Note: I'm using wallabyJS test runner so I got partial completions on the email as I typed them in (wallaby runs test in real time).

## Summary

This should be quite easy to produce and unless I'm mistaken, a call to `signIn()` should NOT add users to this table, only a call to `signUp()`, right?

**Comment by awalias** [comment]
thanks for reporting @ksnyde looking into this now

**Comment by awalias** [comment]
I can't reproduce with the raw http endpoint:

```
curl -X POST 'https://tqfdyljhkqylveukuhsy.supabase.net/auth/v1/token?grant_type=password' \
-H "apikey: <ANON_KEY>" \
-H "Content-Type: application/json" \
-d '{
  "email": "someonee@email.com", 
  "password": "IRIqBTFoyfIERXoQthIT"
}'
{"error":"invalid_grant","error_description":"No user found with that email, or password invalid."}

```


so perhaps it has something to do with the logic [here](https://github.com/supabase/gotrue-js/blob/8b61cc39df22cf9e1d546df7e1d06e9b27c51556/src/GoTrueClient.ts#L136)

**Comment by awalias** [comment]
do any of these tests send an email but no password? Because in that case it is expected behavior to register a user with a passwordless login and send a magic link

**Comment by awalias** [comment]
also can't reproduce with supabase-js I get the correct response: `error: Error: No user found with that email, or password invalid.`

perhaps it is only happening in the cases with no password (or null or undefined)?

**Comment by ksnyde** [comment]
Hey @awalias, right before I went to bed last night I cleaned up the auth table and then retried running the unit tests and was surprised to see that that the errors I was getting had changed to what you saw above. My setup is a single table and outside my unit tests nothing is going against it so I'd have thought it would be a pretty controlled environment but maybe my claim that this would be easy to reproduce was false. :( 

Let me have my morning meetings and I'll have another look.

**Comment by ksnyde** [comment]
Your idea that maybe it only happens with no password IS something I will test as what you saw from my screenshots was the unit test getting run over and over in tight succession while I typed and quite possibly the entries all came from _before_ I had typed in the ENV variable for the password into the test.

**Comment by kiwicopple** [comment]
Hey @ksnyde - hopefully it's just a race condition from your test script. If it's not, let us know and we will make sure the server is behaving securely.

Thought: is it the differnce between having "auto confirm" on/off on GoTrue?
