### ISSUE TITLE
self hosted rest api returns always 404

### ISSUE THREAD

**Issue by samuel-bach** [supabase/supabase#5798]
# Bug report

## Describe the bug

While self hosting I get 404 "We couldn't find the page you're looking for" on all rest api endpoints.

## To Reproduce

1. Setup locally using docker-compose: https://supabase.com/docs/guides/hosting/docker
2. `cp .env.example .env`
3. `docker-compose up`
4. run sql `create table foo (bar text);`
5. run:
```
curl -v 'http://localhost:3000/rest/v1/foo?select=*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q' \
  -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q' 
```

## Expected behavior

Should give the proper output to the query. Instead it looks like the request does not even reach the rest service but is 404ed by (probably) supabase-studio.

**Comment by Daniel199438** [comment]
I have the same error

**Comment by burmecia** [comment]
The default Kong API port number is **8000**, not 3000. Port 3000 is for browser to view Studio web page. You can use `docker ps` to view all the ports mapping used by different components.

**Comment by Daniel199438** [comment]
![tmp_247](https://user-images.githubusercontent.com/16019073/156887744-760cd13d-97ec-4ddd-964d-190d91a8196e.png)

That's my url configuration.

**Comment by burmecia** [comment]
That configuration in your `.env` file is just an example, you need to change it to meet your environment. I'm assuming you're doing local development, so the configuration should be:

```
## General
SITE_URL=http://localhost:3000
KONG_URL=http://localhost:8000
META_URL=http://localhost:8080
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
``` 

We're going to improve the `.env.example` file so it will make more sense.

**Comment by Daniel199438** [comment]
Yeah ok, I understand. But what if I deploy it later on my server with a specific domain? What do I have to change there?

**Comment by burmecia** [comment]
That depends on how you structure your prod environment. That could be many scenarios, I just listed some common ones below:

1. everything runs on a single machine, and no outside API access

This deployment is same as your local deployment, no need to change anything. Probably set up some NATs to let Studio access public.

2. everything runs on a single machine, but need access API from outside

Same as local deployment, but need set NAT to let Kong port 8000 accessible from outside.

3. each component runs on different machine without outside access

This you need to set up a VPC, and change the .env file to point to each machine in your private network and open firewall to outside on some ports you need to access.
