### ISSUE TITLE
Cannot use supabase on Expo project

### ISSUE THREAD

**Issue by ChrisNg02655332** [supabase/supabase#58]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi there, I tried to install and using supabase libary in my project. Unfortunately, I got an error

```
The package at "node_modules/@supabase/realtime-js/src/socket.js" attempted to import the Node standard library module "querystring". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
The package at "node_modules/@supabase/realtime-js/src/socket.js" attempted to import the Node standard library module "querystring". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
```

<img width="644" alt="Screen Shot 2020-04-24 at 15 43 03" src="https://user-images.githubusercontent.com/51181802/80193021-4ada3780-8642-11ea-9622-ab1c078483e8.png">

**Comment by awalias** [comment]
@kiwicopple `querystring` only used here: https://github.com/supabase/realtime/blob/29b4a3fb9997da4cab242b13a98a41784f0b5371/client/realtime-js/src/socket.js#L93

I assume there is some expo friendly way of stringifying query params

**Comment by awalias** [comment]
could potentially replace the offending lib with https://www.npmjs.com/package/query-string

**Comment by kiwicopple** [comment]
so strange. It looks like it was there in the original fork:

https://github.com/mcampa/phoenix-channels/blob/master/src/socket.js

And I am pretty sure `phoenix-channels` was working on expo since we were using at Nimbus. I will investigate

**Comment by kiwicopple** [comment]
@dragarcia could you please check this one? I'm not sure why this has started since we were using `phoenix-channels` just fine

**Comment by dragarcia** [comment]
From what I observed, what we used in the past for Expo applications was [Phoenix](https://www.npmjs.com/package/phoenix) and not [phoenix-channels](https://www.npmjs.com/package/phoenix-channels). I tried using phoenix-channels on a fresh Expo application and it returned me the same error as above.

Solution implemented is what @awalias suggested above. Regression testing has been done on both `@supabase/realtime-js` and `@supabase/supabase-js` to ensure that no other errors arose after making the change. Both have been bumped to their latest versions to reflect this change (versions **0.1.31** & **0.1.8** respectively).

I have tested out the `@supabase/supabase-js` package on a fresh Expo application and everything seems to be in order after making the change, both in terms of realtime and rest. Will be leaving this issue open until the problem has been solved in @ChrisNg02655332 side.

**Comment by kiwicopple** [comment]
Amazing work once again @dragarcia - I'll follow up with Dung

**Comment by ChrisNg02655332** [comment]
Hi @dragarcia, I tried to update ```@supabase/supabase-js: 0.1.31``` and also install ```@supabase/realtime-js: 0.1.8```. But the error still appears.

**Comment by ChrisNg02655332** [comment]
Hi, just confirm it worked. Thank you
