### ISSUE TITLE
Fix padding on mobile menu

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#580]
# Bug report

## Describe the bug

Our mobile menu needs a bit of padding:

![image](https://user-images.githubusercontent.com/10214025/105477561-fcdf8680-5cdc-11eb-8152-c7fef3e4ede3.png)

## Additional context

The padding was probably overridden to work nicely on desktop, so we likely need some [media queries](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) around some of the padding rules

**Comment by mrkldshv** [comment]
@kiwicopple I would be glad to help with fixing this one.

**Comment by w3b6x9** [comment]
Closing this issue because [fix: Add padding on mobile menu #581](https://github.com/supabase/supabase/pull/581) has been merged into master.
