### ISSUE TITLE
Remove coming soon label for cdn

### ISSUE THREAD

**Issue by inian** [supabase/supabase#5808]
In the storage page https://supabase.com/storage since it has already launched

<img width="267" alt="CleanShot 2022-03-05@2x" src="https://user-images.githubusercontent.com/2155545/156868211-79816859-aff7-44a0-ab16-8f601c6d1484.png">

**Comment by MarkCarbajal** [comment]
Hello I would like to work on this issue. Can you assign it to me? Just to make sure, all you want is to get rid of the "Coming soon" label?

**Comment by MildTomato** [comment]
@MarkCarbajal yep just delete it, should be some JSX in Storage.tsx page

**Comment by losito105** [comment]
PR submitted for this issue here: https://github.com/supabase/supabase/pull/5821

**Comment by MarkCarbajal** [comment]
@MildTomato Thank you for the clarification, I have submitted the PR. The issue is #5822
