### ISSUE TITLE
RLS policy empty state is confusing

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#5812]
# Bug report

## Describe the bug

Empty state for RLS policies does not indicate that you need tables in public schema

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new project
2. Go to auth > policies

## Expected behavior

A clear and concise CTA to create a table in public schema, rather than the generic "Hmm, we couldn't find any results that matches your query. Try another?"

## Screenshots
<img width="2056" alt="Screenshot 2022-03-05 at 1 42 57 PM" src="https://user-images.githubusercontent.com/8291514/156885959-26cb16f8-5344-4f09-9611-7f9313734066.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by louis-27** [comment]
Hi @MildTomato , can I be assigned to this? I would like to help work on this

**Comment by Isaiah-Hamilton** [comment]
Hey @louis-27 I assigned you to this issue, and if you need any help just let me know. The file is located here [`studio/components/to-be-cleaned/NoSearchResults.tsx`](https://github.com/supabase/supabase/blob/master/studio/components/to-be-cleaned/NoSearchResults.tsx).

**Comment by louis-27** [comment]
Hi @Isaiah-Hamilton , I added another conditional to render a cta for users with no public tables yet. I didn't change the NoSearchResults component as it would be used for table filtering.

https://user-images.githubusercontent.com/48682663/157069535-1e5c148a-13f8-430a-9f21-58b960269d0a.mov

**Comment by MildTomato** [comment]
@louis-27 looking great!

1. Would it be ok to link to /editor instead of /database from that empty state CTA?

2. Possibly better text in the box could be

```
No public tables found

A public schema table is required before you can create a row-level security policy"
```

Feel free to pull request and we can get this merged in pretty quick.

**Comment by louis-27** [comment]
@MildTomato just made the PR! Forgot to add a request review 😅
