### ISSUE TITLE
getPublicURL adds extra \n

### ISSUE THREAD

**Issue by zhihengGet** [supabase/supabase#5819]
# Bug report

## Describe the bug

getPublicURL adds extra `\n` between   supbase.co and remaining parts of URL

doesnt happen in local dev only in production at vercel .... idk why , i had to add a replaceAll("\n","") to the url 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
    const { publicURL, error: getURLError } = supabase.storage
      .from(bucket)
      .getPublicUrl(filePath);
    console.log("upload image successful ?", publicURL, getURLError);
```

## Screenshots

actual console.log output
```
upload image successful ? https://bddjkcgkmdtfmhmvypwl.supabase.co
/storage/v1/object/public/book-covers/db57e5e8-89dd-4770-bb1d-5d9d3934addc/7.png null
```

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
You likely have a /n in the supabase URL you are passing in to createClient.
That URL is used to build the storage URL and then getPublicURL just builds the URL using the storage URL (which are all based on what you passed in).  There are no calls made from getPublicURL to the net.

**Comment by zhihengGet** [comment]
yeah,  i forgot to update vercel environment variable!!!  it is updated locally but not vercel... bummer
