### ISSUE TITLE
Long query names prevent the user from accessing the overflow menu

### ISSUE THREAD

**Issue by illright** [supabase/supabase#5837]
# Bug report

## Describe the bug

In the SQL editor, queries with long names cannot be renamed or deleted because the button that brings up the overflow menu with these actions is pushed outside of the container

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/<project-id>/sql`
2. Click on "New Query"
3. Create a query with a name "This query deliberately has a long name to be descriptive"
4. Try to rename it

## Expected behavior

The overflow menu button should remain visible and accessible, no matter how long the query name is.
It would also be helpful to set a `title` attribute to allow the user to see the full name of the query on long hover.

## Screenshots

<details><summary>Click to see</summary>

![long-query-name-full-page](https://user-images.githubusercontent.com/15035286/156997192-49f9c4f5-598a-44a9-b1e0-8c9e90dea333.jpg)
![long-query-name-inspected](https://user-images.githubusercontent.com/15035286/156997198-6ee4bc4e-97e0-49de-b68f-3e5b78fa1f82.jpg)

</details>

## System information

- OS: Windows
- Browser (if applies): Latest Chrome
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by Isaiah-Hamilton** [comment]
Closed with https://github.com/supabase/supabase/pull/5818

**Comment by illright** [comment]
@Isaiah-Hamilton are you sure? The issue persists and I didn't see any commits in #5818 that addressed this

**Comment by Isaiah-Hamilton** [comment]
Sorry about that, I will reopen this issue.

**Comment by sharath29** [comment]
I would like to work on this one, may I pick this up @Isaiah-Hamilton @illright ?

**Comment by kiwicopple** [comment]
go for it @sharath29 !

**Comment by sharath29** [comment]
@kiwicopple how can I test my changes in local as option for adding new query is not showing up when I run the studio supabase build locally.

**Comment by kiwicopple** [comment]
I see - I think this one may still be pending the migration into Studio, which means it will need to be fixed internally. I'll let the Frontend team know!

**Comment by sharath29** [comment]
@kiwicopple got it, btw the fix which I was thinking of testing is as below:

```
                        <div className="flex justify-between">
                          <Typography.Text className="truncate" small>
                            {query.name}
                          </Typography.Text>
```

while playing with these components locally I found that directly adding bootstrap to Typography.Text does not add the effect, I think adding to the parent div will do the trick here:

```
                        <div className="flex justify-between truncate">
                          <Typography.Text small>
                            {query.name}
                          </Typography.Text>
```

**Comment by MildTomato** [comment]
@sharath29 you don't need to use <Typography> component any more. it's being Deprecated

**Comment by joshenlim** [comment]
hey there - i think this has been fixed already? just checking on the dashboard
![image](https://user-images.githubusercontent.com/19742402/167868423-b99a134a-abf1-4b10-b59f-0e991044836c.png)

but i'll add the fix for title prop as you mentioned
