### ISSUE TITLE
The query description isn't stored

### ISSUE THREAD

**Issue by illright** [supabase/supabase#5838]
# Bug report

## Describe the bug

The modal window for renaming queries provides a way to add a description to the query. However, not only is that description not shown anywhere in the UI, but it's not even persisted, as the user can observe by attempting to modify it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/<project-id>/sql`
2. Create a new query
3. Rename the query and give it a description
4. Try to find the description anywhere in the UI
5. Try to modify the description by renaming the query again

## Expected behavior

The query description is prominently displayed in the UI and persisted across renames.

## Screenshots

Here's the modal dialog in question:

<img width="310" alt="rename query dialog" src="https://user-images.githubusercontent.com/15035286/156998665-ed4022fd-3301-4217-82c6-3d0a9ad481f1.png">

## System information

- OS: Windows
- Browser (if applies): Latest Chrome

**Comment by MildTomato** [comment]
Looks like description is getting saved. It is also in the response from `/content` 

Looks like this is a problem at form level, just need to populate the description input with the snippets description if one is already present

**Comment by MildTomato** [comment]
I take your point as well @illright that the description should be visible somewhere. Not just in an edit form 😄
