### ISSUE TITLE
Migrate docs to clsx library

### ISSUE THREAD

**Issue by mrkldshv** [supabase/supabase#584]
# Chore

## Describe the chore

Migrate from [classnames](https://www.npmjs.com/package/classnames) to [clsx](https://www.npmjs.com/package/clsx) library in Supabase docs.

## Additional context

I have noticed that both `classnames` and `clsx` libraries are used in docs package, which are actually meant for the same purpose. I'm wondering if there is any reason for using both?
`clsx` is faster and smaller alternative to `classnames` library. 
I'll be happy to help migrating to one of these, if that's possible!

What do you guys think?

**Comment by kiwicopple** [comment]
That would be great @mrkldshv - always nice to remove a dependency :)

**Comment by kiwicopple** [comment]
Closed by `mrkldshv` 🚢  https://github.com/supabase/supabase/pull/591
