### ISSUE TITLE
Incorrect width in sidebar menu items on mobile devices

### ISSUE THREAD

**Issue by ftonato** [supabase/supabase#585]
# Bug report

## Describe the bug

Our mobile menu (sidebar) needs some adjustments.

In the list of items (links), each item is 100% wide, but has no visual indication of it.

This generates strange behaviour, because if the user clicks 20px away (to the right or left) from the github icon, for example, he will be redirected.

I added a border to the image below so that the size of the link can be easily seen.

Another small gap is, the first item has `margin-top: calc(var(--ifm-spacing-vertical)*1.5);` but the last item has zero `0` as margin-bottom. We can add the same value to be consistent.

<img width="342" alt="supabase" src="https://user-images.githubusercontent.com/5417662/105522100-bab24700-5cd4-11eb-81d8-d0ad69968784.png">

## To Reproduce

1. Go to [https://supabase.io/docs/client/supabase-client](https://supabase.io/docs/client/supabase-client)
2. Use a viewport of `320px x 476px`

## Additional context

We likely need some [media queries](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) around some of the padding rules.

**Comment by sethburtonhall** [comment]
@ftonato Can I take this one?

I also have thoughts on how to improve this (add hover states, cursor pointer, caret dropdown on Tools to stay consistent with larger screens, etc...) to make a bit more user friendly

**Comment by ftonato** [comment]
Hey @sethburtonhall,

Thank you for care about it, please go ahead.
Any questions you have, just let me know :)

**Comment by awalias** [comment]
fixed
