### ISSUE TITLE
Table Editor error while inserting 5000 rows via API

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#586]
# Bug report
I tried to insert 5000 records via API (see below) while I had the **Table editor** open in background. As soon as I executed the insert below, the entire editor area disappeared (only the left hand panel and the breadcrumbs on top remained), with "Error" in the middle of the area.

It worked when inserting 1000 records though.

Switching between areas didn't help. Only after reloading the page the editor appeared again, showing the expected total number of records in the bottom left corner.

```
const { data, error } = await supabase
    .from('mytable')
    .insert(new5000Records)
```

**Comment by kiwicopple** [comment]
Thanks for this @peachp - we added a debounce to the Table Editor to prevent this
