### ISSUE TITLE
Realtime Doesn't work even without RLS

### ISSUE THREAD

**Issue by billypap1** [supabase/supabase#5876]
# Bug report

## Describe the bug

I use Supabase JS SDK v.1.31.1 and I have not set any RLS rule in my database. All tables are open.

My code to listen for live events: 

```
 const mySubscription = supabase
    .from('*')
    .on('*', message => {
      console.log('New message!', message)
    })
    .subscribe()
```

I tried with the other package @supabase/realtime-js v.1.3.6 but no luck. 

```
  var databaseChanges = client.channel('realtime:public:*')
      databaseChanges.on('*', (e) => console.log(e))
      databaseChanges.subscribe()
```

I can connect successfully to supabase - update/insert/delete etc. but I can't receive live events. 

## To Reproduce

In order to reproduce just add the above coding block.

## Expected behavior

-

## Screenshots

-

## System information

- OS: MacOS
- Browser (if applies): Chrome
- Version of supabase-js: v.1.31.1
- Version of Node.js: Latest

## Additional context

-

**Comment by GaryAustin1** [comment]
Did you turn on replication for any tables in the UI database section?

**Comment by billypap1** [comment]
@GaryAustin1 Yes I have turned on replication on all tables

**Comment by w3b6x9** [comment]
@billypap1 have you turned switched on replication events like `INSERT` in Studio?

Can you please create a support ticket here? https://app.supabase.io/support/new

**Comment by billypap1** [comment]
@w3b6x9 Yes I have followed exactly the guides

**Comment by billypap1** [comment]
Okay issue fixed, I don't know why but now I receive realtime updates. I didn't change anything.

**Comment by w3b6x9** [comment]
@billypap1 like I mentioned in my response to your support ticket it was a temporary network issue with your database.
