### ISSUE TITLE
Table Editor side row editor does not display timestamp (no z) column.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#5877]
# Bug report
As seen here timestamp is not handled correctly as far as reading current value for timestamp.
![image](https://user-images.githubusercontent.com/54564956/157551216-b2cf30e2-3f53-48c3-9be1-4867d8bc53b8.png)

Being reported by Discord user Kilian on Firefox and confirmed on multiple browsers by me.

It is a moderate issue because you can still enter a time, but worry it may be part of some of the other issues with timestamp being reported.  I could not find this one in the issue list.

##Steps to reproduce the behavior, please provide code snippets or a repository:

Create a timestamp column.
Enter time. 
Save
Edit Row.

## System information

All major browsers.

## Additional context
Not sure if this code might be related to the issue (or value is already gone at this point).  But dayjs is only being passed a DATE_FORMAT for timestampz:

https://github.com/supabase/supabase/blob/94fdf5cff2751f61993a7df4daf7090d535b6b02/studio/components/interfaces/TableGridEditor/SidePanelEditor/RowEditor/DateTimeInput/DateTimeInput.utils.ts#L8
```
  if (!value || value.length == 0) return ''

  switch (inputType) {
    case 'datetime-local': {
      return dayjs(value, DATE_FORMAT).format('YYYY-MM-DDTHH:mm:ss')
    }
```
elsewhere:
```export const DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ssZ'```

**Comment by joshenlim** [comment]
hey there @GaryAustin1! In the editor you see here, we're using the vanilla HTML input with type "datetime-local"
which does not have any context of timezones. instead we convert them to either local timezone or keep it as UTC depending on whether the column's type is declared with timezone or not

**Comment by joshenlim** [comment]
i'll go ahead to close this issue first since its not really a bug but please do feel free to reopen if you feel otherwise! 🙏  although i think this could be more into our discussions - we could explore into the possibility of using a library perhaps instead of vanilla HTML component

**Comment by MildTomato** [comment]
Reopening this. Does look like an issue with inputs not rendering dates correctly

**Comment by joshenlim** [comment]
sorry i think i jumped the gun here - the issue at hand is that columns of time `timestamp` are getting incorrectly formatted by local time zones, when it should be UTC
