### ISSUE TITLE
Save button stuck in loading state on error

### ISSUE THREAD

**Issue by EvonuX** [supabase/supabase#593]
# Bug report

## Describe the bug
When updating a column in the database and I receive an error the "Save" button keeps being disabled and the sidebar has to be closed and opened again in order for it to be clickable again.

## To Reproduce

1. Edit an existing column in the database to cause an error intentionally
2. Save the changes
3. See mentioned error

## Expected behavior

The button should not be disabled after a user receives an error.

## Screenshots

[Screenshot](https://prnt.sc/xi8ftp)

[Loom Video](https://www.loom.com/share/71b6136781a74e48b4c2ca3491c32c27)

## System information

- OS: Windows 10 (Latest)
- Browser: Chrome (Latest)
- Version of supabase-js: 1.3.2
- Version of Node.js: 12.18.3

**Comment by inian** [comment]
Thank you for reporting the issue @EvonuX. We have fixed it in our latest release!

**Comment by Pavan-Rajesh** [comment]
This is again repeated please fix it I cant add any row to mytable in the editor
