### ISSUE TITLE
Nextjs icon not visable in light mode

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#5931]
# Bug report

## Describe the bug

The Nextjs icon in the studio is not visible in light mode.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [app.supabase.io/project/ref](https://app.supabase.io/project/ref)
2. Click on theme toggle
3. Scroll down to Example projects

## Expected behavior

The nextjs icon is visible.

## Screenshots

<img width="1215" alt="Screen Shot 2022-03-14 at 8 41 09 PM" src="https://user-images.githubusercontent.com/70828596/158474432-b0534b7d-7326-43fd-b6b9-8dab9c399711.png">
<img width="1215" alt="Screen Shot 2022-03-14 at 8 41 22 PM" src="https://user-images.githubusercontent.com/70828596/158474433-6a5b820c-acfd-4de1-8322-8b9f844b2e79.png">

## System information

- OS: Any
- Browser: Any
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

The same could be said for the expo icon.

**Comment by devnamrits** [comment]
Hi @Isaiah-Hamilton, I would love to pick this up?
Can you please assign me?

**Comment by Isaiah-Hamilton** [comment]
All yours @devnamrits, let me know if you have any questions.

**Comment by devnamrits** [comment]
@Isaiah-Hamilton NextJS images are there but they are of light-colored theme that's why it seems to be not visible.

**Comment by devnamrits** [comment]
Hi @Isaiah-Hamilton, I tried few things and came up with these:
1. We can change nextjs-svg icon itself.
2. I tried to theme-based switching between nextjs images but it worked on page refresh. i.e., for example, I'm in light mode, and the black colored nextjs image is there then if we switch to dark mode, the images don't change as the images changes are not modified in state changes while changing the theme as shown below:
<img width="1424" alt="Screenshot 2022-03-18 at 12 54 54 AM" src="https://user-images.githubusercontent.com/54183698/158880279-e93ea03f-dedd-4195-b804-a13d1b013ad3.png">
<img width="1420" alt="Screenshot 2022-03-18 at 12 55 10 AM" src="https://user-images.githubusercontent.com/54183698/158880330-c5fd178e-44ee-4a6c-a1fb-8e9ad74732df.png">

So what should I go for?? Just change the nextjs svg as shown in above images or try to manage image in state and change the values while switching.

**Comment by devnamrits** [comment]
@Isaiah-Hamilton Any update??

**Comment by Isaiah-Hamilton** [comment]
Sorry for the delay. The first option seems to be the best option.

**Comment by devnamrits** [comment]
Hi @Isaiah-Hamilton, Raised PR for this issue. Please review and merge.

**Comment by MildTomato** [comment]
With SVGs, you could possibly set the 'fill' to "inherit" in the svg itself.
And then set the 'fill' with CSS with whatever it is contained in. 
Not sure if it would work but might be a good solution for this, if it's 1 color and it needs to change for light and dark mode.
