### ISSUE TITLE
Flutter windows google and social authentication

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase#5942]
# Feature request

## Is your feature request related to a problem? Please describe.

- Server starts on localhost and listens for calls
- User selects google account in browser and redirects to app
- The requests arrives but the URL is cut and I cant get the session out of it

## Describe the solution you'd like

I'm not sure why the URL is cut but is it maybe because of Supabase redirect URL configs doesn't support that?

```
final url = Uri.https(EnvironmentHelper.authUrl, {  'provider': 'google', 'redirect_to': "http://localhost:3000/myapp"});

    final String callbackUri = await FlutterWebAuth.authenticate(
             url: url.toString(), 
             callbackUrlScheme: "http://localhost:3000/myapp");

    final session = await _supabaseClientService.get().auth.getSessionFromUrl(Uri.parse(callbackUri));
    final user = session.user;
```

Maybe its related to the current experimental implementation of the 3rd party package but this functionality would be great in this package.

https://github.com/LinusU/flutter_web_auth/issues/22

**Comment by dshukertjr** [comment]
Hi @SergejSachs !

Thank you for opening this issue. Just to clarify, you are trying to sign into a web app and not a windows app, correct?

**Comment by SergejSachs** [comment]
> Hi @SergejSachs !
> 
> Thank you for opening this issue. Just to clarify, you are trying to sign into a web app and not a windows app, correct?

Its a flutter app compiled to the windows platform. Im using the supabase dart SDK.

**Comment by Sesa1988** [comment]
Its pretty bad to release a cross platform app if Google and Apple sign in is required at the stores but your Windows and macOS dont support that. Thats my issue currently @dshukertjr

**Comment by dshukertjr** [comment]
@Sesa1988 I am so sorry for the delayed reply here. 

I am not 100% certain, but I think as you have suspected, the URL being cut off issue might be on flutter_web_auth's end, and not on supabase's side.

**Comment by Sesa1988** [comment]
> @Sesa1988 I am so sorry for the delayed reply here. 
> 
> I am not 100% certain, but I think as you have suspected, the URL being cut off issue might be on flutter_web_auth's end, and not on supabase's side. 

Yes thats probably true, I dont know ether but this would be a great feature for the dart and even flutter library if you choose it because you want to go cross platform.

Currently its not possible.

**Comment by dshukertjr** [comment]
@Sesa1988 Thanks for your suggestion. This is definitely in our queues, but have not been able to get to it yet unfortunately.

**Comment by Sesa1988** [comment]
> @Sesa1988 Thanks for your suggestion. This is definitely in our queues, but have not been able to get to it yet unfortunately. 

Thats great, hope this will be available at some point because thats a big deal in a world where you app has to run basically everywere.

**Comment by dshukertjr** [comment]
We have an issue [here](https://github.com/supabase-community/supabase-flutter/issues/106) to track desktop support for supabase-flutter. Closing this one.
