### ISSUE TITLE
Missing details in the Supabase Expo tutorial

### ISSUE THREAD

**Issue by Verzach3** [supabase/supabase#5950]
# Improve documentation

## Link 

[Supabase Expo Guide](https://supabase.com/docs/guides/with-expo)

## Describe the problem

The documentation is missing a detail in the creation of  `lib/supabase.js` because before we create a client we need to install the Async Storage module and then set it in the localstorage option of the `createClient` function, as in [this example](https://github.com/supabase/supabase/blob/master/examples/expo-todo-list/lib/initSupabase.ts).

## Describe the improvement

Add those details to the documentation, so that people don't run into the error generated by not configuring the createClient correctly.

**Comment by Hallidayo** [comment]
@Isaiah-Hamilton - Can I take this one?

**Comment by Isaiah-Hamilton** [comment]
Go for it @Hallidayo! 🚀

**Comment by Hallidayo** [comment]
@Isaiah-Hamilton - I've created a [pull request](https://github.com/supabase/supabase/pull/6001) with changes.

As I have mentioned in the pr the guide may need looking into a bit more but I don't know if you want to do this in another issue or pull request?
