### ISSUE TITLE
Syntax error in documentation

### ISSUE THREAD

**Issue by 0xDebabrata** [supabase/supabase#5957]
# Improve documentation

## Link 

[setAuth() | Supabase](https://supabase.com/docs/reference/javascript/auth-setauth)

## Describe the problem

Express code example in the page linked above has a syntax error. A comma is missing after the `Content-Type` attribute of headers object of the fetch request.

## Describe the improvement

Add a `comma (,)` after `Content-Type` attribute of headers object.

## Additional context

![Screenshot 2022-03-19 at 2 51 31 PM](https://user-images.githubusercontent.com/37393381/159115436-f70c3b67-4924-466e-9c2d-e1f2abbaa79d.png)

**Comment by 0xDebabrata** [comment]
If it's alright, I can quickly push a fix.

**Comment by Isaiah-Hamilton** [comment]
@0xDebabrata of course, all yours 🚀
