### ISSUE TITLE
Database error saving new user when sign up with trigger enabled

### ISSUE THREAD

**Issue by wendycuan** [supabase/supabase#5969]
# Bug report

## Describe the bug

When I try to sign up with trigger enabled, I always get 500 error, the trigger will copy user into public.users from auth.users. I have read the docs, every single related issues, and trying every possible combination of trigger query.

This is the last trigger query I run:
```sql
CREATE OR REPLACE FUNCTION public.signup_copy_to_users_table() RETURNS TRIGGER AS $$ BEGIN
INSERT INTO public.users (id, email)
VALUES(new.id, new.email);
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS signup_copy on auth.users;
CREATE TRIGGER signup_copy
AFTER
INSERT ON auth.users FOR EACH ROW EXECUTE PROCEDURE signup_copy_to_users_table();
```

My public.users schema look like this:
```
model User {
  id    String  @id
  email String? @unique

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map(name: "users")
}
```

Any help would be greatly appreciated.

## To Reproduce

1. Enable trigger on auth.users insert
2. Signup

## Expected behavior

Signup should work fine.

## System information

- OS:  Linux
- Version of supabase-js: 1.31.1
- Version of Node.js: 14

**Comment by GaryAustin1** [comment]
At a minimum you are trying to write a uuid to a string.  Try casting it as new.id::text.
Also it is better to not have your security definer functions in the public schema as that function could be called on your API or with an rpc call directly.

**Comment by wendycuan** [comment]
I have already tried to cast it before creating this post, sadly it still not work.
Did you mean "AFTER " as the second part?
![cast](https://user-images.githubusercontent.com/101050332/159172775-b1673dda-5d4c-4882-8ef8-907e4a68e7cb.png)

**Comment by wendycuan** [comment]
> At a minimum you are trying to write a uuid to a string. Try casting it as new.id::text. Edit: removed a 2nd part as not applicable to trigger function.

I have just converted it to uuid, still have the same error.

```sql
model User {
  id    String  @id @db.Uuid
  email String? @unique

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map(name: "users")
}
```

**Comment by GaryAustin1** [comment]
You might be able to see more detail in the database log at the bottom of settings page.
How was your table created?  Can you do an insert on it on from sql editor?

**Comment by GaryAustin1** [comment]
You are also missing your begin/end in your sql create of the function.  Which are you using the UI or the SQL you showed?

**Comment by wendycuan** [comment]
> Edit: Begin/End issue in sql. Sorry on this one too. Missed your Begin at the end of the first line.

It's alright. I just solved the problem, turn out I need to give default value for updatedAt otherwise it will be null. I hope this helps everyone who have the same problem as me. Thank you so much for trying to help me.

```
model User {
  id    String @id @db.Uuid
  email String @unique

  createdAt DateTime @default(now())
  updatedAt DateTime @default(now()) @updatedAt

  @@map(name: "users")
}
```
