### ISSUE TITLE
Cannot Delete Image from bucket

### ISSUE THREAD

**Issue by ahmedabdelhafez** [supabase/supabase#5974]
i have long time searching for a way to delete image from bucket and image not deleted,
i was trying multiple ways to do it and here is my code:

`  deleteImage(bucket: string, imageId: string) {
        return this.supabaseConfig
            .getSupabaseClient()
            .storage.from(bucket)
            .remove([`${imageId}`]);
    }`

is this code is right

**Comment by GaryAustin1** [comment]
As long at your variables generate something like this:
```
const { data, error } = await supabase
  .storage
  .from('avatars')
  .remove(['folder/avatar1.png'])
```
with bucket name and a path to the image strings.

Are you getting an error?
Do you have select and delete policies set?
Do you have a signed in user if you have policies on that?

**Comment by ahmedabdelhafez** [comment]
> As long at your variables generate something like this:
> ```
> const { data, error } = await supabase
>   .storage
>   .from('avatars')
>   .remove(['folder/avatar1.png'])
> ```
> with bucket name and a path to the image strings.
> 
> Are you getting an error?
> Do you have select and delete policies set?
> Do you have a signed in user if you have policies on that?
> 

Hi gary
Yes I do all steps you pointed above and but I will try to add the folder name before the image name

**Comment by GaryAustin1** [comment]
If you want more help you will need to provide your actual policies, and any error returned.  If you can see the network request and response, posting the response might be helpful.

**Comment by ahmedabdelhafez** [comment]
> If you want more help you will need to provide your actual policies, and any error returned. If you can see the network request and response, posting the response might be helpful.

hello @GaryAustin1 
here is the list of polices granted to images bucket
![image](https://user-images.githubusercontent.com/25756993/159366576-7e46aa2a-0431-4bf4-a360-e06cd5019ade.png)
===========
an here is the bucket
![image](https://user-images.githubusercontent.com/25756993/159371654-9f147442-7e79-4b4c-860c-f0b0fcf776d7.png)
it's contain the image and all is right and when i download the image give me status: 400 Not Found
===================
and the request header
![image](https://user-images.githubusercontent.com/25756993/159371758-c2cde4b2-ed07-46ac-8d0a-1565f05774af.png)

=========
and finally the response
![image](https://user-images.githubusercontent.com/25756993/159371815-3fe5ee71-080d-41c8-a73b-614286de28e8.png)

**Comment by GaryAustin1** [comment]
OK, You said Delete did not work, Now you show downloading/Select also does not work.

You have a lot of policies, I normally have 1 policy per operation and put OR statements in for multiple conditions.  I'm not sure multiple policies on the same operation work or not.... I'll have to check.

Showing the name of your policies is not going to help, need to see the actual policy, probably good to start with just select and get that to work.

Your URL looks correct so it is almost certainly a policy issue if you allow anon to read .jpg files.  Note you show policies that allow anon to also upload and delete files?  You sure you want that?

**Comment by GaryAustin1** [comment]
I can confirm multiple polices on same operation (ex. select) works as OR operation in storage.

**Comment by ahmedabdelhafez** [comment]
can you send me the policies you add to the bucket for delete operation

**Comment by GaryAustin1** [comment]
Well, I don't actually let users delete files directly, they are linked to notes and I delete them with a trigger routine and call to storage when the note is deleted.... but here is what I think would be a common delete policy:
((bucket_id = 'test'::text) AND (uid() = owner))
The docs also say you need a valid select policy to do a delete.
