### ISSUE TITLE
Auth headers not synced across sub-clients

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#5990]
# Bug report

## Describe the bug

Currently sub-clients like postgrest and storage are created on method/getter invocation, e.g.

- Postgrest: `supabase.from('table')`: https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L107
- Storage: `supabase.storage`: https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L96

This means that their auth headers are set to the JWT value in the auth session at that point in time, meaning if someone shorthands these 

- `const table = supabase.from('table')` and then uses `table.select()`
- `const storage = supabase.storage` and then uses `storage.getBucket()`

The auth headers will not be updated when someone signs in or out.

## Expected behavior

When the auth state changes, all auth headers across all sub-clients need to be updated to the corresponding JWT.

### Postgrest-js

- [ ] Mark `auth` method as deprecated.
- [ ] Add `setAuth` method.

### Storage-js

- [ ] Add `setAuth` method

### Supabase-js

- [ ] Call `setAuth()` for all sub-clients in `_handleTokenChanged` https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L288

### Community clients

- [ ] Need to figure out how to update the long-tail of community clients cc @dshukertjr @J0

**Comment by kiwicopple** [comment]
> The auth headers will not be updated when someone signs in or out.

I don't know if this is accurate @thorwebdev - I think this is handled here by listening to Auth events: 

https://github.com/supabase/supabase-js/blob/da2b0ba818723b55d82ce3c400e9a5e876148057/src/SupabaseClient.ts#L288

(it should also work across browser tabs)

**Comment by thorwebdev** [comment]
@kiwicopple it's only handled for realtime. Not for postgrest or storage.

**Comment by hf** [comment]
From what I can tell, this is fixed given that both PostgREST and Storage use `fetchWithAuth` as the `fetch` implementation -- which does fetch the latest auth access token on each request.
