### ISSUE TITLE
Search broken in docs

### ISSUE THREAD

**Issue by whalesync-ryder** [supabase/supabase#6007]
# Bug report

## Describe the bug

Looks like searching documentation is broken!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://supabase.com/docs/reference/javascript/auth-session
2. Click on the Search box
3. Type anything in the search box

## Expected behavior
Results

## Actual behavior
The UI says I'm offline, the console is full of net::ERR_NAME_NOT_RESOLVED

## Screenshots
![Screen Shot 2022-03-22 at 11 04 08 AM](https://user-images.githubusercontent.com/93688278/159546755-34f5d6d5-6446-4dff-b1ce-eb960273cf44.png)

## System information
Mac, Chrome

**Comment by Hallidayo** [comment]
@kiwicopple @Isaiah-Hamilton - I think this is related to #5762.

Looking at the Docusaurus [docs](https://docusaurus.io/docs/search#connecting-algolia) the `appId` has to be the `The application ID provided by Algolia` at the moment the appId is :

`appId: 'supabase'`

**Comment by Hallidayo** [comment]
@kiwicopple - I've tried the new details but I'm getting an error `Index supabase does not exist` when doing any search on the documentation:

<img width="477" alt="Screenshot 2022-03-24 at 15 06 46" src="https://user-images.githubusercontent.com/22655069/159947162-7b05835d-d4f0-4342-9a11-dcc24b02421a.png">

<img width="341" alt="Screenshot 2022-03-24 at 15 07 37" src="https://user-images.githubusercontent.com/22655069/159947321-77fb244c-78af-40fa-b33c-b8a2a6ff0ded.png">

**Comment by kiwicopple** [comment]
OK I just created an index called `supabase`. Let's hope that's the final step!

**Comment by Hallidayo** [comment]
Ran a build locally and I'm getting no errors in the console now. Shall I create a pull request so you guys can test your end?

**Comment by Isaiah-Hamilton** [comment]
@Hallidayo it would be great if you could open a pull request.

**Comment by rustamd** [comment]
Any progress on search still not working?

**Comment by burmecia** [comment]
Yes we're still working on this issue, a support ticket has already been sent to Algolia.

**Comment by MildTomato** [comment]
reopening - see screenshot https://github.com/supabase/supabase/pull/6711#issuecomment-1120737715

**Comment by Isaiah-Hamilton** [comment]
We're back, The docs search is working again!

![image](https://user-images.githubusercontent.com/70828596/167533095-03489f06-b061-4030-9f69-91a458d1d5b4.png)
