### ISSUE TITLE
Unable to upload CSV from a Windows OS

### ISSUE THREAD

**Issue by monicakh** [supabase/supabase#6012]
# Bug report
Error when uploading a CSV file to Supabase dashboard.

## Describe the bug
Tried it on a Windows OS, on 3 different browsers (Chrome, Edge, Firefox) got the same error.
It might be something related to the OS since its working on MAC.

## To Reproduce
1. Go to 'Database'
2. Click on 'New'
3. Click on 'Import data via spreadsheet'
4. Import the CSV file 
5. See error

## Expected behavior
To be able to upload a CSV file without errors.

## Screenshots
![image](https://user-images.githubusercontent.com/99693443/159580411-dec5e477-29f2-48a9-8ff2-1c655676b4e4.png)

## System information
- OS: [Windows]
- Browser [Chrome, Firefox, Edge]

Linked ticket : https://support.supabase.org/a/tickets/5456

**Comment by GaryAustin1** [comment]
The problem is windows default filetype is not text/csv which is what Supabase code looks for.  Seems to restrictive.
Discussion here: https://github.com/supabase/supabase/discussions/5953
