### ISSUE TITLE
Copying cell contents from the DB yields the wrong result

### ISSUE THREAD

**Issue by mclean25** [supabase/supabase#6015]
# Bug report

## Describe the bug
Surprised to not see another bug reported for this as it's been happening to me since late 2021, but copying the cell contents in the table editor will copy the wrong cells contents. Maybe a key issue or something? 

## To Reproduce
<a href="https://www.loom.com/share/15dfb2b2d1c9421f9ea83581fa33779e">
    <p>Notes - New Note - 22 March 2022 - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/15dfb2b2d1c9421f9ea83581fa33779e-with-play.gif">
  </a>

## System information

- OS: macOS
- Version of Supabase CLI: 0.18.2

## Additional context
The video above is from the locally run Supabase table editor

**Comment by saltcod** [comment]
Hi @mclean25!   Thanks for the report, I'll have a look at this. 

Way, way more importantly:  what is the song in the background of your video?!

**Comment by saltcod** [comment]
Really strange @mclean25  — is this still happening for you? 

I just checked this table locally and on production and it doesn't happen for me.  Any other customizations or details there you can think of?

**Comment by kiwicopple** [comment]
Closing this for now - will reopen if anyone can reproduce!

**Comment by mclean25** [comment]
Sorry for the late response. This still does happen to me locally even though I'm on the latest CLI version [v0.32.2](https://github.com/supabase/cli/releases/tag/v0.32.2). It doesn't happen to me in prod though, so I wonder if it's just something that's lingering in my state somewhere.
