### ISSUE TITLE
Allow multiple authors on blog

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#6046]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently a blog post can only have a single author

## Describe the solution you'd like

Allow either:

- a single author (string, for backwards compatibility)
- multiple authors (array)

## Additional context

Often our blog posts are co-authored. It would be good to show all the people involved. Vercel do something [similar](https://vercel.com/blog/vercel-funding-series-d-and-valuation)

**Comment by MildTomato** [comment]
@Isaiah-Hamilton hey, if you want to work on this, could you do it on the `chore/www-supabase-ui-migrate` branch?

**Comment by MildTomato** [comment]
`author_url` probably doesn't need to be in the frontmatter in the blog mdx files 🤔 

could probably get them from the `authors.json`. 

then you could add all the authors URLs for the blog post into NextSeo authors list

<img width="541" alt="Screenshot 2022-03-24 at 3 11 04 PM" src="https://user-images.githubusercontent.com/8291514/159934982-8e615118-cf62-4a78-b537-2c171954f010.png">

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple @MildTomato all done. Its backwards compatibility and on `chore/www-supabase-ui-migrate` branch. Might need to change the UI of we will have more than 2 authors. For example [vercel blog](https://vercel.com/blog) or [vercel blog post](https://vercel.com/blog/vercel-funding-series-d-and-valuation)
<img width="1280" alt="Screen Shot 2022-03-25 at 10 00 49 PM" src="https://user-images.githubusercontent.com/70828596/160220810-494da99e-f0ce-4d91-b380-e5f18c102fef.png">
<img width="1280" alt="Screen Shot 2022-03-25 at 10 01 10 PM" src="https://user-images.githubusercontent.com/70828596/160220811-873e5f6b-7376-4f80-ac78-867abda1ae2a.png">
<img width="1280" alt="Screen Shot 2022-03-25 at 10 01 41 PM" src="https://user-images.githubusercontent.com/70828596/160220812-1ded4ae8-21aa-4fd3-8d1e-4fc64d37b7bc.png">

**Comment by MildTomato** [comment]
@Isaiah-Hamilton do reckon we should show the authors below the thumbnails like the screenshot below if there are multiple authors

<img width="96" alt="Screenshot 2022-03-26 at 3 33 58 PM" src="https://user-images.githubusercontent.com/8291514/160244193-691f8be3-5b95-4160-bf15-f4f412b79211.png">
