### ISSUE TITLE
Creating new table assigns owner to supabase_admin and not postgres user

### ISSUE THREAD

**Issue by rickywid** [supabase/supabase#6071]
# Bug report

## Describe the bug

When I create a new table using the Supabase dashboard, the table owner is being assigned to `supabase_admin` instead of `postgres` user. I've tested in 2 of my supabase projects and it's the same thing.

## To Reproduce

1. Create empty table called "test" with default columns.
2. In PSQL type `\dt public.test`

 Schema | Name | Type  |     Owner      
--------+------+-------+----------------
 public | test | table | supabase_admin
(1 row)

I tried doing 
```
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
```
as mentioned here https://github.com/supabase/supabase/issues/3415#issuecomment-933710018 with no luck.

## Expected behavior

Table owner should be `postgres`.

## System information

- OS: Linux Fedora 34
- Browser Chrome/Firefox

**Comment by kiwicopple** [comment]
thanks @rickywid - we're working on this one 👍

**Comment by apecollector** [comment]
I have the same issue, I need to add multiple column constraints.

**Comment by ferpintado** [comment]
+1 This also makes me unable to do `supabase db push`

**Comment by jgeurts** [comment]
> I have the same issue, I need to add multiple column constraints.

fwiw, I was able to add an index using the supabase sql editor. It's not ideal, but it worked 🤷

**Comment by apecollector** [comment]
@jgeurts I wasn't, I didn't have permission to modify the table. I ended up creating the tables in a postgres client directly using my own user instead of through the supabase UI and that solved my problem.

**Comment by mario7746** [comment]
Has there been any progress on a fix for this issue?

**Comment by crushingCodes** [comment]
After checking the other open issues I found the temporary solution here [#2495](https://github.com/supabase/supabase/discussions/2495#discussion-3472859)

**Comment by kiwicopple** [comment]
hey all, this should now be resolved through this update last month:

https://github.com/supabase/supabase/discussions/9314

Feel free to comment if you're still having issues and we can reopen this

**Comment by lukas-moertl** [comment]
Hey,

I am having a similar problem, tables created via the Supabase-UI suddenly became owned by supabase_admin instead of postgres.
When they were created on two days ago, they worked fine, now I cannot edit the tables or set policies.

`select * from pg_tables where schemaname='public'`

<img width="1052" alt="image" src="https://github.com/supabase/supabase/assets/5183071/159fee43-dd7b-4e78-91c6-720c5ac94264">

**Comment by asharejaz1** [comment]
The same exact problem is happening with me as well.

It automatically assigns some tables to 'supabase_admin' and then i am barely able to change/modify anything in the table. 

![Screen Shot 2023-09-09 at 2 09 23 AM (2)](https://github.com/supabase/supabase/assets/111202025/dc2053f3-0678-4cd8-9770-e7eb06d0ce7c)

**Comment by lukas-moertl** [comment]
> The same exact problem is happening with me as well.
> 
> It automatically assigns some tables to 'supabase_admin' and then i am barely able to change/modify anything in the table. ![WhatsApp Image 2023-09-09 at 2 10 01 AM](https://user-images.githubusercontent.com/111202025/266740149-e7e5842e-3fdd-4410-ab89-9f71af53b651.jpeg)

My quick fix btw was to grab the table definition from the table editor (see image below) for all affected table, than delete all tables and just run the create statements over the SQL-Editor. Did not have any relevant data in yet, so I did not need to deal with inserts.

<img width="1088" alt="image" src="https://github.com/supabase/supabase/assets/5183071/9da9ea9a-b6c0-4baf-b659-565270452b9d">
