### ISSUE TITLE
Console shows 800+ counting errors, and site dosnt load

### ISSUE THREAD

**Issue by yobretyo** [supabase/supabase#6079]
![image](https://user-images.githubusercontent.com/62178428/160220217-5599c309-2793-4ac1-8518-465fae9a32d1.jpeg)# Bug report

The site app.supabase.io is a blank screen, and the terminal shows a continuous increasing of errors

## Describe the bug

On one Mac, it loads fine, but my 2 other Macs, running Mojave, the website dosnt load, it's a grey blank screen that dosnt load anything. I open the web inspector, and it's a forever increasing ERROR, somethings about colors.... not loading. 
The site, slows down my Mac, and then I exit out of it. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]

DOES NOT WORK ON
Mac: macOS Catalina 10.15.5

WORKS ON: 
Mac: macOS Mojave
Safari 14.0.1

- Browser (if applies) [e.g. chrome, safari]
SAFARI 13.1.1 (errors)

- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by ChronSyn** [comment]
You should probably consider adding information to the system information section.

What browser are you using? What version of the browser? What specific version of Mojave?

**Comment by yobretyo** [comment]
> You should probably consider adding information to the system information section.
> 
> 
> 
> What browser are you using? What version of the browser? What specific version of Mojave?

I updated it

**Comment by GaryAustin1** [comment]
So I was looking at this with the poster on Discord and there is another (maybe related discussion https://github.com/supabase/supabase/discussions/6078) that came up within hours.

It appears in Jan. the code was change to use .addEventListener to window.matchMedia,
But for Safari this appears to not be support before ver. 14

![image](https://user-images.githubusercontent.com/54564956/160220439-db370ac2-8b41-4aea-b849-f167d9d761d9.png)

The code was changed here: https://github.com/supabase/supabase/commit/64e5116fe67ef855873f73314a78fc0777383490

![image](https://user-images.githubusercontent.com/54564956/160220566-0719e708-8e22-4db4-88be-40331b146dfc.png)

No idea why just today two issues show up (if the other one is even related).

**Comment by yobretyo** [comment]
Thank you! Well.... what fixes that? 
> So I was looking at this with the poster on Discord and there is another (maybe related discussion https://github.com/supabase/supabase/discussions/6078) that came up within hours.
> 
> 
> 
> It appears in Jan. the code was change to use .addEventListener to window.matchMedia,
> 
> But for Safari this appears to not be support before ver. 14 (it uses .addListener before that)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/54564956/160220439-db370ac2-8b41-4aea-b849-f167d9d761d9.png)
> 
> 
> 
> The code was changed here in Jan: https://github.com/supabase/supabase/commit/64e5116fe67ef855873f73314a78fc0777383490
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/54564956/160220566-0719e708-8e22-4db4-88be-40331b146dfc.png)
> 
> 
> 
> No idea why just today two issues show up (if the other one is even related).

**Comment by GaryAustin1** [comment]
I hope you are not the same poster in 3 in three different places using 3 different names and pretending to be two people with the same problem.....
I have no idea what happens next, I'm just trying to help out with the forums and my guesses on the issue (and it's impact on the user base) may or may not be even correct, up to Supabase if this is an older browser issue.

**Comment by yobretyo** [comment]
Well, that helps.

**Comment by yobretyo** [comment]
They fixed it, it was a support issue for safari
