### ISSUE TITLE
Minor fix needed to the with-expo App.tsx example

### ISSUE THREAD

**Issue by gavinharris-dev** [supabase/supabase#6081]
# Minor fix needed to the with-expo App.tsx example

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/guides/with-expo)

## Describe the problem

The code example in the `with-expo` `App.tsx` file looks a little wrong. 

## Describe the improvement

The line:
`const [session, setSession] = (useState < Session) | (null > null)`
Should probably read:
`  const [session, setSession] = useState <Session | null> (null)`

**Comment by kiwicopple** [comment]
fixed by https://github.com/supabase/supabase/pull/6082
