### ISSUE TITLE
Table editor errors when updating rows with a generated column

### ISSUE THREAD

**Issue by alaister** [supabase/supabase#6091]
# Bug report

## Describe the bug

When trying to update any column in a table that contains a generated column, it fails with the error: `column "x" can only be updated to DEFAULT`. I believe this is due to the table editor trying to save every column in the given row, including the generated column.
Additionally, generated columns should not be editable.

## To Reproduce

1. Create a table with a generated column
```
create table example(
  id serial primary key,
  first_name text not null,
  last_name text not null,
  full_name text generated always as (first_name || ' ' || last_name) stored
);
```
3. Insert a row
4. Try to update the first `last_name` column in the table editor
5. Get the error

## Screenshots

<img width="1731" alt="Screen Shot 2022-03-26 at 6 58 12 pm" src="https://user-images.githubusercontent.com/10985857/160251690-863db1a6-11aa-496c-a9fe-079da135aa8b.png">

## Potential fix

I'm not yet super familiar with the studio codebase; however, taking a guess, I'd say we need to update [generateUpdateRowPayload](https://github.com/supabase/supabase/blob/ebfd338f361723063bd5b6a120f61a97eecc2342/studio/components/interfaces/TableGridEditor/SidePanelEditor/RowEditor/RowEditor.utils.ts#L249-L261) to be aware of which columns are generated and not include them in the payload.

**Comment by GaryAustin1** [comment]
Hmmm,
Table UI gives error with a generated column on changes to other columns.  https://github.com/supabase/supabase/issues/5718

**Comment by burmecia** [comment]
The fix has been merged into main branch, but hasn't been merged into v2.5.0 alpha branch yet. @phamhieu maybe able to give more details?

**Comment by joshenlim** [comment]
Hey there! this fix should have been deployed to production now - could I check real quick if you might still be facing this issue? @GaryAustin1

**Comment by joshenlim** [comment]
@GaryAustin1 i'm gonna go ahead to close this issue first - but feel free to reopen if this problem still happens for you!
