### ISSUE TITLE
Self-hosted supabase/postgres container fails at start

### ISSUE THREAD

**Issue by KainAlive** [supabase/supabase#6105]
# Bug report

## Describe the bug

When following the self-hosting instructions and running the containers, the database service (supabase/postgres) exits with the following error:
```
supabase-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db | 
supabase-db | 2022-03-27 19:42:26.804 GMT [1] LOG:  could not open configuration file "/etc/postgresql-custom/generated-optimizations.conf": No such file or directory
supabase-db | 2022-03-27 19:42:26.804 GMT [1] LOG:  could not open configuration file "/etc/postgresql-custom/custom-overrides.conf": No such file or directory
supabase-db | 2022-03-27 19:42:26.804 GMT [1] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
supabase-db exited with code 1
```

This leads to all services failing because they cannot connect to the DB.

## To Reproduce

Follow the [instructions ](https://supabase.com/docs/guides/hosting/docker#get-the-code) in the supabase docs.
```bash
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Start
docker-compose up
```

## System information

- OS: [Linux: Fedora33 running in a vagrant VM]
- Docker [version 19.03.13, build 4484c46]
- docker-compose [version 1.29.2, build 5becea4c]

**Comment by KainAlive** [comment]
Running the docker-compose file on a different machine works without any problems, so I guess it's a problem with my VM / setup.

**Comment by reyesmfabian** [comment]
I have the same problem and I have tried on 2 different computers with the same error.

**Comment by mpldr** [comment]
Dear person who comes here after me: I managed to fix it by running 
```
# docker compose run db cat /etc/postgresql/postgresql.conf > postgresql.conf
```
and then mounting the output .conf over the original path. Why that is, is beyond me, but it worked for some miraculous reason.

**Comment by TonyGiorgio** [comment]
> Dear person who comes here after me: I managed to fix it by running
> 
> ```
> # docker compose run db cat /etc/postgresql/postgresql.conf > postgresql.conf
> ```
> 
> and then mounting the output .conf over the original path. Why that is, is beyond me, but it worked for some miraculous reason.

I tried this, still doesn't work. Giving up on supabase, it's impossible to self host.

**Comment by NicksonYap** [comment]
Relating to the error `FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors`

Apparently, the named volume `db-config` must be used
