### ISSUE TITLE
Snippets are being overwritten

### ISSUE THREAD

**Issue by davideluque** [supabase/supabase#6124]
# Bug report

## Describe the bug

**Supabase Admin UI.**

I have two snippets and whenever I change from one to another or sometimes refresh the browser, my snippets are overwritten.

## To Reproduce

Not sure exactly how it is reproduced but sometimes I am in one snippet and then i change to the other, refresh the browser thinking maybe it's a UI problem and the snippet did not load, then my snippet is overwritten!

## Expected behavior

Snippets are not overwritten.

## System information

- OS: macOS
- Browser: Safari

**Comment by saltcod** [comment]
Hey @davideluque !   Thanks for the report. 

I've tried to reproduce this in Safari, but it seems to be working for me. To make sure we're on the same page, you're looking at the SQL snippets in the sidebar on `https://app.supabase.io/project/your-project-id/sql` ? 

I'm able to successfully:  
1. Create a new snippet
2. Navigate to a different snippet
3. Navigate back to the new snippet 

Is this still occurring? Any console errors or any other notes on how you're doing this?

Thanks!

**Comment by davideluque** [comment]
Hey, I'm gonna try to record a video and attach it here

**Comment by davideluque** [comment]
This is not the actual issue that I have experienced but not sure why my snippets flipped?

I was able to reproduce it by refreshing the browser but could not reproduce it again 

https://user-images.githubusercontent.com/10492210/166638580-694887cf-4ef9-46bf-9b89-636f458c2f0e.mov

**Comment by saltcod** [comment]
Thanks @davideluque!  The flipping must be a re-sorting. 

I'm going to mark this as closed, but if you experience it again please let us know!  Appreciate the screen captures.
