### ISSUE TITLE
Table in docs is scrolling horizontally 

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#6152]
https://supabase.com/docs/reference/javascript/supabase-client

would be nice if the table scaled to fit, or was allowed to stretch out horizontally instead of scrolling

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/458736/160711242-359d4572-4a3b-474c-adb1-dba347e2ed89.png">

**Comment by nnaemekaibe** [comment]
@awalias I would like to pick this up. cc @Isaiah-Hamilton.

**Comment by Isaiah-Hamilton** [comment]
@nnaemekaibe go for it.
