### ISSUE TITLE
Add dart to authentication docs

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#6157]
# Improve documentation

## Describe the problem

Currently, the authentication docs only have javascript. It would be cool if we add dart just like [Login With Email](https://supabase.com/docs/guides/auth/auth-email) and [Login With Magic Link](https://supabase.com/docs/guides/auth/auth-magic-link).

## Describe the improvement

Add dart into the docs just like [Login With Email](https://supabase.com/docs/guides/auth/auth-email) and [Login With Magic Link](https://supabase.com/docs/guides/auth/auth-magic-link).

**Comment by BhavikJain07** [comment]
I  would like to work on this issue, should I add dart code for all the methods?

**Comment by Isaiah-Hamilton** [comment]
@BhavikJain07 if you still want to work on this, then yes that would be great.

**Comment by jaysoni-ash42** [comment]
@Isaiah-Hamilton  i want to work on this issue.

**Comment by ImBIOS** [comment]
@kiwicopple I think this one is stale.

**Comment by kiwicopple** [comment]
thanks @ImBIOS !
