### ISSUE TITLE
Logs: unable to filter query in search bar

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/supabase#6202]
# Bug report

## Describe the bug

Failure when trying to filter the logs via the search bar in the top left of the logs page.

## To Reproduce

1. Go to the logs page
2. Click on last hour
3. Enter a query in the search bar and press enter

## Expected behavior

The filtering should work.

## Screenshots

![image](https://user-images.githubusercontent.com/813865/161043467-6fee24ee-4eee-4512-8e29-a5e3ed587276.png)

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

```
GET | https://api.supabase.io/platform/projects/XXXXXXXXX/analytics/endpoints/logs.all?project=XXXXXXXXX&sql=SELECT count(*) as count FROM postgres_logs&rawSql=select postgres_logs.timestamp, id, event_message, metadata, metadataparsed.error_severity from postgres_logs  cross join unnest(metadata) as m  cross join unnest(m.parsed) as metadataparsed  where REGEXP_CONTAINS(event_message, 'users')     and  limit 100 &period_start=2022-03-31T11:14:22.347Z
```

I found this in the devtools network tab: I guess the `and limit 100` is where the query trips up due to that being invalid SQL syntax.

**Comment by Ziinc** [comment]
This has been fixed in latest logs explorer refactor

<img width="795" alt="image" src="https://user-images.githubusercontent.com/22714384/163183217-c7de17ae-6fa9-4647-b373-37a246709fde.png">
