### ISSUE TITLE
Edge Function Guide shows different deploy method than Dashboard

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#6230]
# Improve documentation

## Link 

[Edge Deploy Guide](https://supabase.com/docs/guides/functions#deploy-to-production)

## Describe the problem

Guide says:
`supabase functions deploy hello-world`

Dashboard Function page says:
`supabase functions deploy hello --project-ref ugccqefilvseqbseypbq`

## Describe the improvement

They should be the same and which ever method is correct.  ( I can't tell which is correct because of a CLI windows bug at the moment)

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by GaryAustin1** [comment]
Now that I can test it... It looks like either works...   If not there the CLI seems to still use default settings to upload with the project reference.

**Comment by kiwicopple** [comment]
we should update the `Dashboard Function page` to be `hello-world` - this helps devs to understand that it's good practice to use hyphens

**Comment by Hallidayo** [comment]
@kiwicopple - Can I be assigned to this one? Also is the correct [page](https://github.com/supabase/supabase/blob/master/studio/pages/project/%5Bref%5D/functions/index.tsx)

**Comment by Isaiah-Hamilton** [comment]
All yours @Hallidayo, and yes that's the correct page.

**Comment by Hallidayo** [comment]
I've created a [pr](https://github.com/supabase/supabase/pull/6381) for this.
