### ISSUE TITLE
Edge Functions blog post: bad link for Deno testing

### ISSUE THREAD

**Issue by mfulton26** [supabase/supabase#6236]
# Improve documentation

## Link 

https://supabase.com/blog/2022/03/31/supabase-edge-functions

## Describe the problem

Links to https://deno.land/manual/tools/testing which results in a 404.

## Describe the improvement

I think it should link to https://deno.land/manual/testing instead.

## Additional context

Super exciting to see a partnership between Supabase and Demo Deploy!

**Comment by Hallidayo** [comment]
[Pull request](https://github.com/supabase/supabase/pull/6242) created for this.

**Comment by kiwicopple** [comment]
thank you! 🙏
