### ISSUE TITLE
Extension request - is_jsonb_valid

### ISSUE THREAD

**Issue by Vadorequest** [supabase/supabase#624]
# Feature request

https://github.com/furstenheim/is_jsonb_valid seems useful for enforcing JSON schemas in columns using the `JSON` type.

It's not in the Database > Extensions yet, I suggest it is added.

It seems to be more performant than its https://github.com/gavinwahl/postgres-json-schema counterpart. (from the author)

**Comment by kiwicopple** [comment]
thanks for the request @Vadorequest . Perhaps you can add this one here? 

https://github.com/supabase/supabase/issues/624

**Comment by Vadorequest** [comment]
I'm not sure I understand what you mean.

**Comment by kiwicopple** [comment]
Oops sorry about that, I linked to the wrong place. Perhaps you can add your extension request to this Discussion:

[Vote for Postgres extensions](https://github.com/supabase/supabase/discussions/679)
