### ISSUE TITLE
Edge functions should support outgoing connections to SMTP ports 25, 465, and 587.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#6255]
# Feature request

From the Edge Function guide, and another user's first attempt with the edge functions, it appears ports 25,465,587 do not work in Supabase deploy of Deno functions.  

If this is true then the ability to handle email tasks from an edge function are not possible.

## Describe the solution you'd like

If this is a correct interpretation of the limitation, is this a short term limitation?

Support of ability to send emails seems a common requirement for "serverless" functions.

## Describe alternatives you've considered

I currently use Firebase cloud functions to generate a pdf from database data and send via email as attachment at request of client code.  I also have a function to send email invites to chat rooms, also at the request of the user.  I want to move these functions over to my Supabase environment.

**Comment by GaryAustin1** [comment]
I lucked out the email provider I've been using with Google Cloud functions with SMTP has a full API.  Just used Fetch in Deno and am in business.

**Comment by wcooperscott** [comment]
Any solution? I've been messing with it for hours, just now realizing port 255, 465, & 587 do not work 😅

**Comment by NobodyExceptHim** [comment]
Yeah, still nothing :)))) Why is this even a thing

**Comment by laktek** [comment]
This is a known limitation in edge functions deployed to Supabase. https://supabase.com/docs/guides/functions#limitations

Check with your email service if they support an alternate port or an HTTP API for sending email.

**Comment by bpeck81** [comment]
@laktek  It's confusing to me that this is a known limitation, yet you have an example of being able to send emails from edge functions. What other ports would most email services allow us to use?
https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/send-email-smtp/index.ts

**Comment by GaryAustin1** [comment]
It turns out some providers allow non-standard ports like 2525 and 2587.  
The Supabase example shows using 2587 in the env file, but no provider.
Searching on those I do see some support.

I'm still just using my providers API.

**Comment by GaryAustin1** [comment]
https://developers.sendinblue.com/reference/sendtransacemail

I've seen other providers with API's.
