### ISSUE TITLE
Realtime Subscriptions No Longer Working Locally With Custom JWT

### ISSUE THREAD

**Issue by Marviel** [supabase/supabase#6290]
# Bug report

## Describe the bug

Local subscriptions are not working with the provided "self-hosted" `docker-compose.yml`, even though replication is enabled on all tables.

## To Reproduce

1. Clone this repo
2. Run the local docker-compose setup as is described in the documentation, including ENV var setup
3. Realtime subscriptions (from js client) succeed -- but are not broadcasted.

## Expected behavior

Realtime subscriptions should broadcast correctly.

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: "@supabase/supabase-js": "^1.33.3",
- Version of Node.js: 16.7.0

## Additional context

- I dug through the logs for realtime, and was able to confirm that it was *trying* to subscribe to the things I was asking it for from the frontend.
- I couldn't see any evidence of failures in the Realtime logs. However, I also wasn't able to see any evidence of successful subscriptions at the postgres-level when I audited the postgres database using techniques here: https://dba.stackexchange.com/questions/224490/using-postgresql-logical-replication-how-do-you-know-that-the-subscriber-is-cau

**Comment by w3b6x9** [comment]
@Marviel Thanks for reporting this issue! I'll investigate shortly and post here with my findings.

**Comment by w3b6x9** [comment]
@Marviel I spun up `docker-compose` and everything worked for me.

- Did you set a JWT secret and pass in a JWT signed by that secret when joining the subscription? Can you check your local database's `realtime.replication` table and see if there are any records?
- You mentioned "replication is enabled on all tables." How were you able to do this? If you check your database publication tables, what do you get? You can check by running `select * from pg_publication_tables;`.

**Comment by Marviel** [comment]
Okay, thanks for the followup... good sanity check to let me know I'm doing something wrong.

I do have a JWT Secret, and I'm generating a JWT using that secret.  I know I'm signing correctly because I'm able to make normal requests fine... it's just the realtime stuff that isn't working. I'll investigate more here though and ensure I'm not doing anything silly.

**Comment by Marviel** [comment]
Well, that might be part of my problem. I tried to make this happen the naive way, which may have messed up my subscriptions:


```
begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication, enable for all tables.
  CREATE PUBLICATION supabase_realtime FOR ALL TABLES;
commit;
```

Playing with this piece now, but will probably be a few days before I can get back to confirm it's the culprit.

**Comment by w3b6x9** [comment]
@Marviel that does look correct. what do you get when you query `select * from pg_publication_tables;`?

**Comment by w3b6x9** [comment]
@Marviel what does your client code look like? are you calling `.subscribe()`?

**Comment by Marviel** [comment]
Sorry this took so long, I get this back: 

![Screen Shot 2022-04-16 at 9 21 22 PM](https://user-images.githubusercontent.com/2037165/163696263-ac32bb88-3624-400d-8985-8e6c5ee14214.png)

**Comment by Marviel** [comment]
Client code:

```
const organization = supabase
                            .from('organization')
                            .on('*', payload => {
                                console.log('Change received!', payload)
                            })
                            .subscribe()
```

**Comment by Marviel** [comment]
If it helps, I also get these logs from the realtime container:

```
2022-04-17 17:31:13.381 [info] Running RealtimeWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)

2022-04-17 17:31:13.381 [info] Access RealtimeWeb.Endpoint at http://localhost:4000

2022-04-17 17:31:13.850 [info] CONNECTED TO RealtimeWeb.UserSocket in 373µs

  Transport: :websocket

  Serializer: Phoenix.Socket.V1.JSONSerializer

  Parameters: %{"apikey" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs", "vsn" => "1.0.0"}

2022-04-17 17:31:17.794 [info] JOINED realtime:public:organization in 5ms

  Parameters: %{"user_token" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJnb29nbGUtb2F1dGgyfDEwMjU3NDY0MjI5NDc5MTIzMjg1OSIsImV4cCI6MTY1MDI1MjQ1NywiaWF0IjoxNjUwMjE2NDc2fQ.ZY-hhY_ai-eckH5PpvDN7Q7ilyJGd0rr3uMT_s9LoRk"}

2022-04-17 17:32:27.109 [info] CONNECTED TO RealtimeWeb.UserSocket in 356µs

  Transport: :websocket

  Serializer: Phoenix.Socket.V1.JSONSerializer

  Parameters: %{"apikey" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs", "vsn" => "1.0.0"}

2022-04-17 17:32:27.131 [info] JOINED realtime:public:organization in 8ms

  Parameters: %{"user_token" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJnb29nbGUtb2F1dGgyfDEwMjU3NDY0MjI5NDc5MTIzMjg1OSIsImV4cCI6MTY1MDI1MjQ1NywiaWF0IjoxNjUwMjE2NzQ2fQ.ZVh5tIBIVKQHp2hvbOApD53fHYeQMZOtTePYjKD4gMA"}
  ```

**Comment by Marviel** [comment]
This is also the case in the CLI. After some debugging I'm narrowing in on the issue.

Assuming this had something to do with JWTs I was signing myself, I removed all RLS from my table, and I disabled the following line, whre I was setting up my auth token with supabase:

```
// When this is disabled, subscriptions work.
// const {user, error} = supabase.auth.setAuth(supabaseToken);
```

**In this case, the subscriptions started to work!**

However, I also need my subscriptions to work with JWTs that I have signed myself.

I have experimented with different JWT signature secrets, and I am confident that I have the right one.

So now I'm just confused why _specifically realtime_ appears to have issues with the JWTs I am generating -- but the REST api seems to be doing just fine.

**Comment by w3b6x9** [comment]
@Marviel thanks, i'll take a look today.

**Comment by w3b6x9** [comment]
> I need it to work with JWTs that I have signed myself -- not the default auth offering.

@Marviel Ah, this might be the issue. You mentioned that you were calling `supabase.auth.setAuth(supabaseToken)` before but there seems to be an inherent issue with `gotrue-js` `setAuth` method. 

Can you try:

1.  `supabase.auth.setAuth(supabaseToken)`
2.  `supabase.auth.stateChangeEmitters.forEach((x) => x.callback('TOKEN_REFRESHED', supabase.auth.currentSession))`

My hypothesis is that `setAuth` is missing a call to `this._notifyAllSubscribers('TOKEN_REFRESHED')`. If that doesn't work I can keep digging.

**Comment by Marviel** [comment]
@w3b6x9 yeah, after some digging the callback doesn't seem to be working... and I see your PR! Thanks for the fix, will be very helpful.

**Comment by w3b6x9** [comment]
@Marviel Oh, you’re saying it’s still not working?

Hm, so the custom token you’re signing is with the same secret that was passed to the Realtime server right? When you subscribe to Realtime can you see any records in realtime.subscription table of the database?

**Comment by Marviel** [comment]
@w3b6x9 Yeah, still not working unfortunately. I did have to ts-ignore that change because it was complaining about both the `stateChangeEmitters` and `state.auth.currentSession` being protected.

1. I don't see any entries in the `subscription` table of the database
2. I've turned off RLS for the table entirely for debugging purposes.

**Comment by w3b6x9** [comment]
> If it helps, I also get these logs from the realtime container:
> 
> ```
> 2022-04-17 17:31:13.381 [info] Running RealtimeWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
> 
> 2022-04-17 17:31:13.381 [info] Access RealtimeWeb.Endpoint at http://localhost:4000
> 
> 2022-04-17 17:31:13.850 [info] CONNECTED TO RealtimeWeb.UserSocket in 373µs
> 
>   Transport: :websocket
> 
>   Serializer: Phoenix.Socket.V1.JSONSerializer
> 
>   Parameters: %{"apikey" => "REDACTED", "vsn" => "1.0.0"}
> 
> 2022-04-17 17:31:17.794 [info] JOINED realtime:public:organization in 5ms
> 
>   Parameters: %{"user_token" => "REDACTED"}
> 
> 2022-04-17 17:32:27.109 [info] CONNECTED TO RealtimeWeb.UserSocket in 356µs
> 
>   Transport: :websocket
> 
>   Serializer: Phoenix.Socket.V1.JSONSerializer
> 
>   Parameters: %{"apikey" => "REDACTED", "vsn" => "1.0.0"}
> 
> 2022-04-17 17:32:27.131 [info] JOINED realtime:public:organization in 8ms
> 
>   Parameters: %{"user_token" => "REDACTED"}
> ```

@Marviel it's strange that your logs show that you successfully joined yet there are no records in your `realtime.subscription` table.

Can you please confirm that your env variables are the same as the following:

```
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
```

> Assuming this had something to do with JWTs I was signing myself, I did the following:
> 
> Removed all RLS from my table
> disabled the following line, where I was setting up my auth token with supabase:
> // When this is DISABLED, subscriptions work.
> // const {user, error} = supabase.auth.setAuth(supabaseToken);
> In this case, the subscriptions started to work!

Just to confirm that you disabled RLS on your table and Realtime began giving back changes? Can you run try this again and check your `realtime.subscription` table? If you can get changes and there's no record in `realtime.subscription` then I don't think you're using Realtime RLS (the second version of Realtime) and instead using the first version that doesn't rely on `realtime.subscription` table.

**Comment by w3b6x9** [comment]
@Marviel here's a list of the all the checks to make sure we're on the same page:

- Env vars

```bash
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
```

- JWT

Your custom token was signed with secret you set in `JWT_SECRET` and has at least a `role` in JWT `claims` plus whatever else you need to satisfy your RLS policies.

- Slot is active

```sql
select * from pg_replication_slots;
```

And check that there's a `supabase_realtime_rls` slot.

- Publication and publication tables exist and are enabled.

```sql
select * from pg_publication;
```

Find `supabase_realtime` publication with `puballtables` set to `true`.

```sql
select * from pg_publication_tables;
```

The table you're trying to listen to exists after making that query.

- Creating client subscription

After subscribing from the client, and seeing something like

```bash
2022-04-17 17:31:17.794 [info] JOINED realtime:public:organization in 5ms

  Parameters: %{"user_token" => "REDACTED"}
```

Confirm that JOINED subscription has a record in `realtime.subscription`.

**Comment by Marviel** [comment]
Ah, finally -- did not realize the importance of the role field. Makes perfect sense in retrospect.

>  **_and has at least a role in JWT claims_** plus whatever else you need to satisfy your RLS policies.

Thanks *so much* for your help / patience.

**Comment by w3b6x9** [comment]
@Marviel You're very welcome!

**Comment by tg44** [comment]
@w3b6x9 I have a similar issue, could be from different things...

 - I have a custom jwt, it has a field: "serverId".
 - I have a working RLS with 
   ```sql
   create policy "Messages viewable by server members."
    on messages for select
          using (
            ((server_id)::text = ((current_setting('request.jwt.claims'::text, true))::json ->> 'serverId'::text))
          );
    ```
  - I can query the tables correctly with this RLS, getting back only the needed rows
  - when I start realtime, the websocket opens up, and I see a `topic,payload/user_token` message which seems to be correct, getting back an ack with a ref, but after this, the client sends a  heartbeat and a separate topic message, but only get acks for the heartbeat (this could be fine but strange)
  - when I insert into the table, I get no messages back

Possible problems could be;
 - I migrated the db with prisma, which is messing up the roles, but I have a script to fix them... this topic was the only which helps to check things, but still could be a missing role/trigger/function problem
 - the jwt part with realtime is not working as it should (but I can't debug it bcs I don't get auth errors back from realtime)
 
 I checked that the table has all roles granted to `postgres, anon, authenticated, service_role, supabase_admin`.
 Also, I went through on your checklist, and everything seems ok (I didn't have puballtables=true, but I manually set it to true just in case, still no messages).

Can you help me with any ideas how I can debug this? (This is on the supabase cloud infra rn, but I can probably try this out in local too if that helps.)

**Comment by w3b6x9** [comment]
@tg44 I think your issue could be related to Prisma. Take a look at https://supabase.com/docs/guides/integrations/prisma#confirming-realtime-functionality.

**Comment by tg44** [comment]
I don't have enum types.

**Comment by w3b6x9** [comment]
> Your custom token was signed with secret you set in JWT_SECRET and has at least a role in JWT claims plus whatever else you need to satisfy your RLS policies.

@tg44 make sure your custom JWT has a `role`.

**Comment by tg44** [comment]
Okay, this solved it!

Users from the future;
 - in the supabase admin, check the realtime schema subscription table, if your subscription is not there, there is a jwt/auth problem
 - if you create your jwt by hand, you should add a `role: "anon"` field to it at least

Thanks! (I will add a PR to the docs too.)

**Comment by nbarrow-inspire-labs** [comment]
I know this is not the exact same issue as described by OP, but I just wanted to document it here just in case anyone stumbles across the similar issue described, but the solutions don't work: 

I was on all of the latest versions of the CLI, javascript client, etc., with replications and realtime enabled on all tables (including ones without any RLS, just for debugging this) and realtime was only failing locally (my cloud Supabase project, which is an exact replica schema-wise, worked perfectly). Based on @tg44 's advice ("check the realtime schema subscription table"), I went to locate this table, and for some reason, my local supabase `realtime` schema had no tables. Running `supabase db reset` did nothing to solve the issue; stopping (`supabase stop`) and then re-starting (`supabase start`) the local instance did not help either. 

Ultimately, I stopped the running local supabase in the project that I was in (`supabase stop`) and moved to a completely empty directory, fired off `supabase init` and then `supabase start`. I noticed that after doing this, now with a completely blank project, the `realtime` schema was no longer empty and had the `subscription` table (as it should). The really odd thing is that I returned to the old project where this bug was occurring, and everything works like normal again, including realtime. 

In case anyone stumbles across this thread while chasing down the rabbit hole, ^ helped me to solve the issue. I think the hard reset must have fixed things.

**Comment by LivioGama** [comment]
I decided to write a whole medium post for avoiding you waste time in the future: https://liviogamassia.medium.com/using-supabase-rls-with-firebase-auth-custom-auth-provider-357eaad9c70f

**Comment by bigbizze** [comment]
> I know this is not the exact same issue as described by OP, but I just wanted to document it here just in case anyone stumbles across the similar issue described, but the solutions don't work:
> 
> I was on all of the latest versions of the CLI, javascript client, etc., with replications and realtime enabled on all tables (including ones without any RLS, just for debugging this) and realtime was only failing locally (my cloud Supabase project, which is an exact replica schema-wise, worked perfectly). Based on @tg44 's advice ("check the realtime schema subscription table"), I went to locate this table, and for some reason, my local supabase `realtime` schema had no tables. Running `supabase db reset` did nothing to solve the issue; stopping (`supabase stop`) and then re-starting (`supabase start`) the local instance did not help either.
> 
> Ultimately, I stopped the running local supabase in the project that I was in (`supabase stop`) and moved to a completely empty directory, fired off `supabase init` and then `supabase start`. I noticed that after doing this, now with a completely blank project, the `realtime` schema was no longer empty and had the `subscription` table (as it should). The really odd thing is that I returned to the old project where this bug was occurring, and everything works like normal again, including realtime.
> 
> In case anyone stumbles across this thread while chasing down the rabbit hole, ^ helped me to solve the issue. I think the hard reset must have fixed things.

Using your knowledge here I was able to cobble together a bash script which seems to fix the issue for me, even if it's an extremely ghetto hack.

```bash
#!/bin/bash

# Drop the realtime schema and recreate it so that the realtime container
# is forced to reinitialize everything in the schema.
psql "postgresql://supabase_admin:postgres@localhost:54322/postgres" <<EOF
  DROP SCHEMA IF EXISTS realtime CASCADE;
  CREATE SCHEMA realtime;
EOF

if [ $? -ne 0 ]; then
  echo "Error: Failed to fix local realtime schema."
  exit 1
fi

# Find container ID with name containing "realtime"
container_id=$(docker ps --filter "name=realtime*" --format "{{.ID}}")

# Check if a container was found
if [ -z "$container_id" ]; then
  echo "No Docker container with name containing 'realtime' found."
  exit 1
fi

docker restart "$container_id"
```

I am running this after the local supabase environment is created

**Comment by flogy** [comment]
For me it was that my custom JWT did not include the `aud` and `exp` fields.

Make sure the custom JWT contains those fields or else the realtime subscription will not work:
- `role` (e.g. `anon`)
- `aud` (e.g. `anon`)
- `exp`

**Comment by goodacres** [comment]
Came across something similar but in our case it was not JWT related, rather our code depended on realtime being enabled on multiple database tables. We had one table where it wasn't enabled that seemed to cause an exception that blocked updates for other tables.
