### ISSUE TITLE
Egde Function deploy returns a 500 error

### ISSUE THREAD

**Issue by adriengibrat** [supabase/supabase#6298]
# Bug report

Unable to deploy edge function due to cli error

## Describe the bug

Error 500 "Unexpected error fetching a function" while trying to deploy edge function (with supabase cli on linux).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1.  ✅ `supabase functions new hello`
2.  ✅ `supabase functions serve hello`
3. ❌ `supabase functions deploy hello --project-ref XXX`
4. > Bundling hello
Error: Unexpected error deploying Function: error message: Unexpected error fetching a function
error code: 500
error id: 8ea388a5-154f-4b30-a4da-87b78a4b48d7

## Expected behavior

Deploy success

## Screenshots

![image](https://user-images.githubusercontent.com/62407/161698088-d831c98b-9c8d-4589-a184-ff7dbf725e3d.png)

## System information

- OS: Pop OS 21.10 linux (kernel 5.16.15-76051615-generic)
- ~Browser (if applies) [e.g. chrome, safari]~
- ~Version of supabase-js: [e.g. 6.0.2]~
- Version of Node.js: 16.6.0
- Version of supabase cli: 0.24.0

## Additional context

It's fresh install of supabase on linux via brew, with updated supabase cli. No other cli error encoutered.

**Comment by phamhieu** [comment]
Hi @adriengibrat, your project functions metadata is invalid. I already clean it up. 
Can you try again and let me know if the still issue persists. Thank you.

**Comment by laktek** [comment]
Closing this issue since there hasn't been any activity.
