### ISSUE TITLE
Auth Policy Docs Improvement

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#631]
a lot of people getting confused by the gif here: https://supabase.io/docs/guides/auth#policies

everyone uses `auth.role() <> 'authenticated'` but I don’t think they grasp the <> nor the difference between PERMISSIVE and RESTRICTIVE

**Comment by awalias** [comment]
best thing is to probably add two written examples of policies - one using `auth.role() = 'authenticated'` and one where `auth.uid() = id`

**Comment by jdcauley** [comment]
I would like to upvote this because row level policies have me banking my head into my desk.

**Comment by kiwicopple** [comment]
We're working on this now! 

As a stop-gap, I have added a few examples here @jdcauley :  https://supabase.io/docs/guides/auth#policy-examples

Also note that if you're using some sort of middleware already [you don't *have* to use policies](https://supabase.io/docs/guides/auth#you-dont-have-to-use-policies)

**Comment by jdcauley** [comment]
@kiwicopple, I found an example that unlocked things for me: https://github.com/joshnuss/supabase-kanban/blob/master/setup.sql

The mistake I made was trying to use the Table GUI, where I really really needed to use the SQL commands.

**Comment by kiwicopple** [comment]
Yeah, our Policy GUI needs some UX effort. Glad you managed to solve it @jdcauley

**Comment by kiwicopple** [comment]
Closing this since we added a few examples in the docs (and it will be an ongoing effort to add more)
