### ISSUE TITLE
Supabase logo is weird on /beta route

### ISSUE THREAD

**Issue by Hamaad-Siddiqui** [supabase/supabase#6330]
[It is set to 20 x 20px for some reason](https://supabase.com/beta)
![image](https://user-images.githubusercontent.com/62789084/162005000-53ce1cfb-519a-4d02-ab9c-f73112c92d13.png)

**Comment by Hallidayo** [comment]
[PR](https://github.com/supabase/supabase/pull/6335) created for this.
