### ISSUE TITLE
Auth copy contrast issue

### ISSUE THREAD

**Issue by qw-in** [supabase/supabase#6331]
# Bug report

https://github.com/supabase/supabase/blob/master/www/pages/auth/Auth.tsx#L134-L138

![Screenshot_2022-04-06-09-10-31-88_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/19194187/162020544-f51cb224-a460-4a12-bdd1-9899e5a5a29f.jpg)

**Comment by Hallidayo** [comment]
I've created a [pull request](https://github.com/supabase/supabase/pull/6334) for this.
