### ISSUE TITLE
Client side auth

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#64]
## Current state

At the moment we are providing key auth using an API key on each request. For the REST requests, this is passed as a header. For the sockets, this is necessarily passed as a URL parameter because most browsers strip the headers for Sockets. 

This is not ideal. It is only considered safe on serverside where there is less chance of discovering the key.

Even if we allowed multiple keys, this doesn't solve *authorization*. Once a user is provided access, how do we ensure they aren't accessing other people's data? This is especially tricky for our realtime server, where we would need to run some logic for every change request to know if the change is relevant for *each connected user*. 

## Solution 0: Custom auth

This is a non-starter. We don't want to add our own auth system. We can integrate with others, but we don't want to force our opinionated systems on others. We should provide general solutions which work for everyone - even legacy systems.

## Solution 1: RLS

We could leverage Postgres' Row level security, roles and users. This is very attractive since the level of security it provides is amazing. We would delegate much of this work to the tools which we use:

- [PostgREST Auth](http://postgrest.org/en/v7.0.0/auth.html)
- [Postgraphile Auth](https://www.graphile.org/postgraphile/security/) - we don't use this, but will probably offer GraphQL in the future so it makes sense to investigate their model. Also there is good feedback about their approach on [HackerNews](https://news.ycombinator.com/item?id=22437271).

It would look something like this:

![image](https://user-images.githubusercontent.com/10214025/81171967-f20a8780-8fcf-11ea-9f26-0d4d1a904261.png)

*Pros*

- Definitely solves authentication
- Extremely secure

*Cons*:

-  we rely on the customer to start modifying their schema. This is not ideal as the many people won't want to pollute their DB (I probably wouldn't).
- authorization requests hammering the database. DDOS hell

## Solution 2: Global API proxy

We can provide them with one API proxy per-project(database):

![image](https://user-images.githubusercontent.com/10214025/81172774-7d384d00-8fd1-11ea-8914-49514fa06149.png)

This proxy would need to run serverless functions so that the user can add their own logic. When we deploy a new server for them, we can add some basic rules (like we already have), and then it is up to them to add any advanced rules. We can offer plugins and templates to make this simple 

*Pros*

- Authorization at the edge. Keep the servers in a secure VPC
- Very flexible. They create their own logic and can integrate with any service.
- Adds a layer for "business logic": one of the complaints about PostgREST is that it's just CRUD, so you have to write business logic into the database (functions). This gives the user another place to deploy that logic (serverless functions).  

*Cons* 

- Moves us away from a Postgres platform
- A bit unclear if the system ties together... Do we have one Gateway per database? One per org? How does it look in the Dashboard? Might be very confusing to the customer.

**Comment by kiwicopple** [comment]
We may end up needing some mixture of these too. For example, we need rate-limiting. This should be done before hitting the DB, so we still need a global proxy (or some sort of API proxy in the stack).

**Comment by kiwicopple** [comment]
For the Global Proxy, I thought a very simple solution is that we could run Caddy on Cloudflare Workers (WASM), and the JSON config could be stored in Cloudflare KV. This way we don't actually need to manage infra, and it's running on the edge.

I don't think Kong will work so well on workers. If we do this setup, it's also easy enough to replicate on a local machine - we don't have to mock out Workers, we just use a single caddy instance in our docker image

**Comment by tomlarkworthy** [comment]
Worth a look https://opensource.google/projects/cel

**Comment by kiwicopple** [comment]
Nice one @tomlarkworthy. I just had a very quick skim so doing a brain-dump here to loop back on later).

- Intro: https://github.com/google/cel-spec/blob/master/doc/intro.md
- Looks most useful for AuthZ - pros/cons over PG RLS?
- From this intro, it looks like it's built for Protobuf. Will need to verify and then see if/how that could fit with PostgREST+Realtime (convert data). 
- Cross referencing our realtime issue on transaction filtering so that we can consider this on both realtime and REST - https://github.com/supabase/realtime/issues/47 
- Since this is used in Firebase, we should verify it isn't subject to the same limitations ([no inequality checks](https://stackoverflow.com/questions/47251919/firestore-how-to-perform-a-query-with-inequality-not-equals))

**Comment by kiwicopple** [comment]
This is now fixed and released. Look out for the updates in the latest blog post & newsletter
