### ISSUE TITLE
Site URL path not respected on localhost with third-party provider

### ISSUE THREAD

**Issue by mcsdevv** [supabase/supabase#640]
# Bug report

## Describe the bug

The path provided in the 'Site URL' is not respected when the host provided is `localhost`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Project > Authentication > Settings (tab)
2. Edit the Site URL to be `localhost:3000/[path]`.
3. Perform login via third-party provider with `auth.signIn`.
4. The path will not be included in the URL upon redirect to the application, only the hash will be present.

Repeat the above steps with a public URL and the `path` specified **will** be included.

## Expected behavior

The redirect URL back to the application includes the `path` specified in the Site URL field.

## System information

- Big Sur
- Latest Chrome

**EDIT:** I'm getting inconsistent results when using a public URL as well now, sometimes it redirects with just the hash, sometimes it includes the path.

**Comment by w3b6x9** [comment]
Related discussion: #664

**Comment by awalias** [comment]
is your test app running on `localhost:3000` @mcsdevv ? Could you check whether the `referrer` is being set on the auth request? I will try and repro this on my side now

this could be due to the intelligent `referrer` behavior linked [here](https://github.com/supabase/gotrue/issues/62#issuecomment-774867811) @kiwicopple 

gotrue may be ignoring `SITE_URL` and directing back to the original referrer

**Comment by awalias** [comment]
ok can confirm that we can customize redirect by setting `referrer` header on the `/authorize` request, as long as the origin is the same

currently this is being set to the current page which explains the buggy behavior you were seeing @mcsdevv

**Comment by mcsdevv** [comment]
Hi @awalias, thanks for confirming. Is it possible to just explicitly set this? Relying on `referrer`, while often a good option, seems like a sure-fire way to bring painful debugging experiences about. Documenting it will of course help, but I'd wager it'll be easily forgotten often.

**Comment by awalias** [comment]
yes, agree - being more explicit is better, no black magic

**Comment by kiwicopple** [comment]
Progress can be followed here: https://github.com/supabase/gotrue/issues/62#issuecomment-776717577

We will combine a `redirectTo` param with a whitelist of URLs, which should cover all use-cases.

**Comment by mcsdevv** [comment]
> Progress can be followed here: [supabase/gotrue#62 (comment)](https://github.com/supabase/gotrue/issues/62#issuecomment-776717577)
> 
> We will combine a `redirectTo` param with a whitelist of URLs, which should cover all use-cases.

Thanks for the update, agreed that this is the right solution here.

**Comment by AronBe** [comment]
@kiwicopple would it be also possible to allow deep links for mobile devs? currently there is validation on the input field that does not allow them

![image](https://user-images.githubusercontent.com/32416348/107788916-3c841600-6d51-11eb-8e81-435f30c95fda.png)

**Comment by kiwicopple** [comment]
Hey @AronBe - we will support mobile too 👍 

https://github.com/supabase/gotrue/issues/63

**Comment by awalias** [comment]
[`redirect_to`](https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect) query param is now the primary source of redirects, and we also added Additional Allowed Urls in the dashboard for mobile urls and different envs 

![image](https://user-images.githubusercontent.com/458736/119627729-0c174200-be3f-11eb-853f-02df94334c15.png)

**Comment by alexandregiordanelli** [comment]
I tried everything with no success.

<img width="798" alt="Captura de Tela 2021-08-28 às 16 13 42" src="https://user-images.githubusercontent.com/1518223/131228477-71a7600b-6a08-4c89-9342-92d59a8f6f9f.png">

<img width="795" alt="Captura de Tela 2021-08-28 às 16 13 27" src="https://user-images.githubusercontent.com/1518223/131228492-d9b155fc-72f6-4239-8509-58d377b03fa5.png">

```js
    const href = window.location.href.split("#")[0]
    supabase.auth.signIn(
      {
        provider: 'google',
      },
      {
        redirectTo: href,
        
      }
    )
```

**Comment by alexandregiordanelli** [comment]
Sorry, I got. The problem was that it is necessary to be identical to the redirectTo. If you have 5 millions of pages, I will need to put 5 millions of URLs separeted by comma.. I think it is better do a wildcard or something like that.

**Comment by multiplehats** [comment]
> Sorry, I got. The problem was that it is necessary to be identical to the redirectTo. If you have 5 millions of pages, I will need to put 5 millions of URLs separeted by comma.. I think it is better do a wildcard or something like that.

Agreed, we should be able to do a wild card. I have many auth guarded routes and adding them all in a small input field is a pain and not DRY at all.

**Comment by RubenMateus** [comment]
> > Sorry, I got. The problem was that it is necessary to be identical to the redirectTo. If you have 5 millions of pages, I will need to put 5 millions of URLs separeted by comma.. I think it is better do a wildcard or something like that.
> 
> Agreed, we should be able to do a wild card. I have many auth guarded routes and adding them all in a small input field is a pain and not DRY at all.

any updates on this? can we do like.
example:
`*.vercel.app` <- for testing purposes

**Comment by eMeRiKa13** [comment]
> any updates on this? can we do like. example: `*.vercel.app` <- for testing purposes

It would be awesome!

**Comment by simonh1000** [comment]
Yes, here is an example of a netlify preview url `https://6224790c45550f0007015694--my-site.netlify.app/`
I want to be able to redirect to urls like this during development

**Comment by fforres** [comment]
Has there been any updates on this? 
Is this something supabase is considering?

**Comment by multiplehats** [comment]
> Has there been any updates on this? 
> 
> Is this something supabase is considering?

https://github.com/supabase/supabase/issues/4808

**Comment by aquaductape** [comment]
Any updates on wildcard option?
