### ISSUE TITLE
Edge-Functions - Terminal Overflow

### ISSUE THREAD

**Issue by Hallidayo** [supabase/supabase#6401]
# Bug report

## Describe the bug

On the [edge-functions](https://supabase.com/edge-functions) page on the section 'Anatomy of an Edge Function', the terminal overflows horizontally.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. go to [edge-functions](https://supabase.com/edge-functions) page
2. Go down to 'Anatomy of an Edge Function'
3. You'll see the terminal to the right overflowing

## Expected behavior

It appears the gap seems too big. If `gap: 4rem; / gap-16` is applied then the overflow seems to align better.

## Screenshots

Current page:

<img width="1412" alt="Screenshot 2022-04-10 at 17 34 53" src="https://user-images.githubusercontent.com/22655069/162723771-40622a41-7199-4b15-9b1a-7c8184308147.png">

Proposed change:

<img width="1438" alt="Screenshot 2022-04-11 at 11 36 08" src="https://user-images.githubusercontent.com/22655069/162723800-2c9e7c90-4588-4059-946b-b0a30ef2f95c.png">

## System information

- OS: MacOS
- Browser: Chrome

## Additional context

I'll create a pull request for this.

**Comment by ganeshmani** [comment]
@kiwicopple i would like to work on this issue :-)

**Comment by kiwicopple** [comment]
It looks like @Hallidayo already has an open PR - just need @MildTomato to review and check if there are any necessary changes

**Comment by MildTomato** [comment]
@Hallidayo could you just move your changes to /apps/www for us?

**Comment by Hallidayo** [comment]
@MildTomato - Just created a new pull request #6631.
