### ISSUE TITLE
SQL editor: last opened query tab empty

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#642]
# Bug report
Logging back in / reloading Supabase dashboard next day > SQL editor > Favorited query tab is opened and focused, showing "Loading..." > "Loading" disappears, the query editor remains empty.

Switching to "Welcome" and back to the query tab shows the SQL code now.

Minor, but a bit annoying. Could also be a bit dangerous making me think I've deleted all the SQL code last time and writing it again.

UPDATE 2021-02-02: noticed same behavior when adding new query via the + button: after "Loading.." disappears, the editor textarea is empty, no cursor, no line numbers. 

![image](https://user-images.githubusercontent.com/47209189/106381411-65e78e00-63b0-11eb-8e65-2cefa1da7799.png)

**Comment by kiwicopple** [comment]
Hey @peachp - this one should be fixed as we upgraded Monaco editor. You may have to clear your local storage to make sure.

I'll close this, but if it's still an issue feel free to reopen.
