### ISSUE TITLE
SQL editor: feedback for repeating "Success. No rows returned"

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#643]
# Feature request
When running same script again successfully, there is no verbal or visual feedback whether it run. Yes, one can assume that if there is no error message appearing in place of previous "Success. No rows returned", then it was OK, but it is still strange.

This is esp. relevant when executing the script with the keyboard shortcut, as opposed to clicking on RUN where the spinning wheel appears briefly.

Maybe you could add a date/time stamp left from the message something like:
2021-01-31 16:06:12: Success. No rows returned

Maybe additionally add some animation / flash / fading etc. to visually make it clear that the script executed successful, so you don't have to compare the time

**Comment by kiwicopple** [comment]
Hey @peachp - I added a `Running ...` indicator. It should appear tomorrow 👍
