### ISSUE TITLE
big databases log file  60g+

### ISSUE THREAD

**Issue by au-top** [supabase/supabase#6432]
# Bug report

## Describe the bug

I set up a local supabase. I noticed that after I ran for a period of time (a few weeks), a large storage log file (60 +) g appeared. When I deleted the file I lost all my data

I think he should be a log from the database

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. running it has been running for some time

## System information

- OS: Linux Debian

**Comment by au-top** [comment]
#https://github.com/supabase/cli/pull/245

**Comment by kiwicopple** [comment]
> set up a local supabase

Were you using the CLI, or the docker-compose?

**Comment by au-top** [comment]
> > set up a local supabase
> 
> Were you using the CLI, or the docker-compose?

docker-compose

**Comment by au-top** [comment]
i find big  file info 




`/var/lib/docker/overlay2/11c158c9ae1e24008fc7fac6078e5d7e77e0dd3d06967448139c55fd21c4015b/merged/var/log/postgresql/postgresql.csv`

```
root@VM-16-14-debian:/var/lib/docker/overlay2/11c158c9ae1e24008fc7fac6078e5d7e77e0dd3d06967448139c55fd21c4015b/merged/var/log/postgresql# ls -alh
total 12G
drwxrwxr-t 1 root             systemd-coredump 4.0K Apr 13 15:14 .
drwxr-xr-x 1 root             root             4.0K Dec  3 07:24 ..
-rw-r----- 1 systemd-coredump systemd-coredump  12G Apr 17 17:52 postgresql.csv
-rw-r----- 1 systemd-coredump systemd-coredump  596 Apr 17 14:05 postgresql.log

```


`/var/lib/docker/overlay2/11c158c9ae1e24008fc7fac6078e5d7e77e0dd3d06967448139c55fd21c4015b/diff/var/log/postgresql/postgresql.csv`


```
root@VM-16-14-debian:/var/lib/docker/overlay2/11c158c9ae1e24008fc7fac6078e5d7e77e0dd3d06967448139c55fd21c4015b/diff/var/log/postgresql# ls -alh
total 12G
drwxrwxr-t 2 root             systemd-coredump 4.0K Apr 13 15:14 .
drwxr-xr-x 3 root             root             4.0K Dec  3 07:24 ..
-rw-r----- 1 systemd-coredump systemd-coredump  12G Apr 17 17:54 postgresql.csv
-rw-r----- 1 systemd-coredump systemd-coredump  596 Apr 17 14:05 postgresql.log
```

**Comment by au-top** [comment]
help me

**Comment by kiwicopple** [comment]
Hey @au-top - did you see these notes in our docs?

https://supabase.com/docs/guides/hosting/overview#managing-your-database

> It is recommended that you decouple your database from the middleware so that you can upgrade the middleware without any downtime. The "middleware" is everything except Postgres, and it should work with any Postgres provider (such as AWS RDS), or your own Postgres cluster.

https://supabase.com/docs/guides/hosting/docker#configuration

> We strongly [recommend](https://supabase.com/docs/guides/hosting/overview#managing-your-database) that you decouple your database before deploying.

Running the database inside a docker image, in production is not recommend. You should definitely use an external Postgres server. Either way, you will want to ensure that you have configured Postgres for log rotation (https://dba.stackexchange.com/questions/142760/postgresql-log-rotation). This will limit the size of the logs.

I'll close this one for now, but feel free to comment. I would be happy to convert this to a Discussion too
