### ISSUE TITLE
Project cannot be deleted, showing error code 500

### ISSUE THREAD

**Issue by rohandebsarkar** [supabase/supabase#6438]
# Bug report

## Describe the bug

I want to delete a project, but it's showing some error.

## Expected behavior

The project should be deleted.

## Screenshots

![Screenshot from 2022-04-14 09-40-35](https://user-images.githubusercontent.com/50144004/163312652-890303d4-617f-4e98-8c6a-ee0a01e80b16.png)

## System information

- OS: Archlinux
- Browser: Firefox-99.0.1

**Comment by MildTomato** [comment]
We're having some issues with syncing some of our details from our payment provider (Stripe).
This is also affecting some other issues, which we'll investigate.

**Comment by MildTomato** [comment]
@rohandebsarkar could you email support@supabase.io with your project ref?

the project ref is the long id in the URL when your inside the project
for example `http://app.supabase.io/project/bayqmkbpbdmptzbzmuud` <— this

**Comment by MildTomato** [comment]
Looks like this issue has been resolved @rohandebsarkar 

Please reopen this issue or send a support ticket to us if you have any more issues.
