### ISSUE TITLE
Cannot save auth settings in Studio in self-hosted/cli environments

### ISSUE THREAD

**Issue by Flambe** [supabase/supabase#6439]
# Bug report

## Describe the bug

When trying to update the auth email settings in Studio, I get an error saying that "Method PATCH Not Allowed". This only happens on self-hosted/cli instances of Supabase Studio.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `/project/default/auth/settings` page on a project in Supabase Studio in a self-hosted/cli environment
2. Attempt to change a setting with emails (e.g. disabled email confirmations or adding a custom SMTP server and click save)
3. See error "Method PATCH Not Allowed"

## Expected behavior

The new settings are saved.

## Screenshots

![image](https://user-images.githubusercontent.com/2080851/163372312-07f2ec8a-1e71-4f6e-b015-5be8c19af57a.png)

## System information

- OS: Ubuntu/Docker
- Browser: chrome
- Version of supabase cli: 0.24.3
- Version of supabase-js: n/a
- Version of Node.js: n/a

## Additional context

I tried looking into the studio source and I found [`studio/pages/api/auth/[ref]/config.ts`](https://github.com/supabase/supabase/blob/master/studio/pages/api/auth/%5Bref%5D/config.ts) which appears to be a proxy/placeholder for the API? I added handling for PATCH here which did fix the UI issue, but as far as I can tell the settings still don't actually save and I haven't been able to figure out where to look next.

Split from #6180

**Comment by kiwicopple** [comment]
You should not be able to update these settings on self-hosted/CLI, because they are provided as env vars. You can instead update the config files provided.

I'll leave this open however - we will need to fix Studio to make this more apparent

**Comment by Flambe** [comment]
@kiwicopple Ah that makes sense.

I think another solution is to make the docs more self-hosted friendly. (For example [the email settings docs](https://supabase.com/docs/guides/auth/auth-email) only caters to apps deployed on the SaaS version). This was part of my confusion as to why the page wasn't working as I didn't think to look for the env and got way too much tunnel vision into the settings page.

But my stuff is working in the mean time, so thank you for the help :)

**Comment by kiwicopple** [comment]
Yup, you're right. We definitely need to make that clearer. Thanks @Flambe
