### ISSUE TITLE
Table editor: values not shown Update side panel

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#644]
# Bug report
The values are shown OK in the grid view, but not in the Update side panel on the right hand side. See below.
SQL select shows the value OK too.

![image](https://user-images.githubusercontent.com/47209189/106390663-5cc2e500-63e1-11eb-8084-742cf72f25bf.png)

![image](https://user-images.githubusercontent.com/47209189/106390674-68161080-63e1-11eb-887f-c5715bdb5ae4.png)

**Comment by phamhieu** [comment]
hm.. `LinkMultiFld`, `LinkSingleFld` are Arrray(varchar) type. But the table grid show as a dictionary with `{... }`

Maybe issue with array parsing again. @joshenlim what do you think?

**Comment by peachp** [comment]
It seems like it only happens for arrays.
Btw, it is also not possible to create Array fields vi GUI, but it's not really a bug I guess.

**Comment by kiwicopple** [comment]
Hey @peachp - this one should be fixed! Let us know if it still isn't working for you
