### ISSUE TITLE
supabase.js/gotrue.js token refresh does not work on mobile devices going in and out of "sleep" mode.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#6464]
# Bug report

## Describe the bug

supabase.js and gotrue.js have a token refresh timer that does not work in sleep mode on mobile devices.  

Testing on Android/Chrome and ios/Safari shows that if the jwt token expires during the sleep period the app will no longer be able to do authenticated requests upon return (sometimes the timer will start running again but this could be many minutes).  There are no errors until a call is made to the server that requires a valid token.  Refreshing the browser is often required to recover.

There are several issues reported that are likely related to this.  Some I found quickly.

One reported yesterday that does not mention mobile: https://github.com/supabase/supabase/issues/6452
Token fails silently: https://github.com/supabase/gotrue-js/issues/226
Proposed solution 2 months ago: https://github.com/supabase/gotrue-js/pull/227

I show code below to highlight the issue and include 2 options for working around the issue until there is (hopefully) a fix from Supabase.

Option 1) Creates a function called SUPAbase that takes a supabase client call as a parameter and checks token nearing or past expiration and refreshes the session with the client, then patches the call authorization header with valid token.  You use this shell function when you know the SB operation needs a valid token.
Option 2) Refreshes an expiring token when the window visibility handler returns visible, before going back to the app. 

I have done limited testing of the solutions so far, and not examined the impact on realtime yet.

## To Reproduce
Start a supabase app on a mobile device, sign in, put device to sleep, wait more than the token expire period, come out of sleep mode and attempt an operation that needs a valid token.  Setting token expire period on server to minutes helps debug time.

I have been working on a test platform for this and some work arounds shown below.

## Expected behavior
supabase.js and gotrue.js should work together to detect a token is about to expire and refresh the token before any call requiring a valid token.  This could be optional like with the autoRefreshToken flag.

Devs using Supabase should not be forced to deal with device, browser issues and token details for basic operation of the client code in normal situations including mobile devices pausing/sleeping.  Having a client maintain session without external browser state handlers, error handlers or adhoc wrappers around the Supabase code makes adoption harder, or worse flawed when rolled out in production.  As a competitor to Firebase, a seamless client session and realtime experience (which has similar issues on mobile devices) would be highly desirable.  

## Screenshots
Failing with test platform:
![ipad failing](https://user-images.githubusercontent.com/54564956/163691107-56469326-bb64-4cab-bc5f-1101c03e98ca.PNG)
![android chrom not working](https://user-images.githubusercontent.com/54564956/163691109-43e8433a-55a1-4ee2-8e69-208ed588936b.jpg)

Working with either a supabase shell refresh function, or a visibility handler refresh function
![Android with visibility refresh](https://user-images.githubusercontent.com/54564956/163691138-34adbbf1-1766-4cca-9def-5921b3f28396.jpg)
![ipad - working with shell](https://user-images.githubusercontent.com/54564956/163691142-68fe1672-c3a8-4354-8ef8-6c2a5885656c.png)

## System information
Tested on Android/Chrome battery mode, ios/Safari powered mode (iPad and iPhone current versions)

## Additional context
Two ways to work around the issue:
Option 1:  a function "wrapper" to check for expiring token and refresh if needed before making a supabase call.  
              note option 1 will not keep realtime.js token refreshed before a call to the function is made.
Option 2:  a handler on visibility that checks need for refresh of token and refreshes, before continuing with app.

Simple javascript code for both I ran on my server so mobile devices could easily access and show results.  Set token period to minutes for quicker testing.
```
var supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY)

//Option 1, shell to call if you will need valid token... there are probably "nicer" ways to implement this...
var SUPAbase = async function (sb) {
    if (await checkSession() ==='expired') {
        let session = supabase.auth.session();
        sb.headers.Authorization = `Bearer ${session.access_token}`  //besides session reset, need to change authorization header in this active call
    }
    return (await sb)
}

async function checkSession () {
    let session1 = supabase.auth.session()
    let expiresIn = session1.expires_at - Math.round(Date.now() / 1000)
    htmlLog('session expires in: ' + expiresIn)
    if (expiresIn < 10) {    //10 is used for shell refresh, 61 is probably correct value for visibility handler refresh
        const {session:session2,error} = await supabase.auth.setSession(session1.refresh_token)
        let expiresIn = session2.expires_at - Math.round(Date.now() / 1000)
        htmlLog('new session expires in: ' + expiresIn)
        return 'expired'
    }
    return ''
}

async function app () {
    const inputElement = document.getElementById("login");
    inputElement.addEventListener("click", login, false);
    supabase.auth.onAuthStateChange((event, session) => {
        htmlLog('auth change: '+event)
        if (event === 'SIGNED_IN') {
            let session = supabase.auth.session()
            let expiresIn = session.expires_at - Math.round(Date.now() / 1000)
            htmlLog('new signin token expires in: '+expiresIn)
        }
    })
    async function doStuff() {
        const {data,error} = await SUPAbase(supabase.from('messages').select('*').eq('id',7))  //this way for option 1
        //const {data,error} = await supabase.from('messages').select('*').eq('id',7)     //this way for option 2
        console.log(data,error)
        if (error) {
            htmlLog('I tried to fetch RLS data and got: '+ error.message)
        }
        else {
            htmlLog('I fetched RLS data: ' + data[0].message)
        }
    }
    async function login() {
        const {user} = await supabase.auth.signIn({
            email: 'xxx',
            password: 'testpass'
        })
    }
    async function restart () {
        htmlLog('visibility handler: ' + document.visibilityState)
        console.log('vis hand: ' + document.visibilityState)
        if (document.visibilityState === "visible" ) {
            //await checkSession()   //Remove this comment for visibility handler refresh
            await doStuff()
        }
    }
    this.addEventListener('visibilitychange', restart)  //used in both options for test, but only in option 2 for handler refresh

}
function htmlLog(message) {
    const date = new Date();
    const log = document.getElementById('log');
    log.innerHTML += date.toISOString().substr(11,8) +' '+ message + '<br>'
}
document.addEventListener("DOMContentLoaded", function(event) {
    app()
})
```
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Supabase Realtime Realworld</title>
    <script src="https://unpkg.com/@supabase/supabase-js"></script>
    <!--<script type='text/javascript' src='config.js'></script>
    -->
    <script src="./app.js"></script>
</head>
<body>
<div id="log">
    Log:</br>
</div>

<input type="button" id="login" value="login"/>
</body>
</html>
```

**Comment by julianpoma** [comment]
This happens on desktop also if you put your computer to sleep/hibernate. It also happened to me if I left the tab in the background for a period of time.

**Comment by GaryAustin1** [comment]
@julianpoma what OS/browser on the background tab stuff?  I have issues with chrome/edge in windows on desktop with realtime because background tabs throttle timers, but could not reproduce this token error with that environment.  I sort of expected an issue but did not see it the one time I tried.

**Comment by julianpoma** [comment]
I have experienced it with Chrome on both MacOS and Windows, and my coworkers reported the same issue with Safari MacOS.
