### ISSUE TITLE
Passwordless Login

### ISSUE THREAD

**Issue by quick007** [supabase/supabase#6471]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to add passwordless login to my app, but as far as I know, you can't do that with Supabase. [See below](#additional-context) for more info on what this entails. Stytch is a billion-dollar company because they did this, so I think it would be very great to have it implemented in more places. But, right now, they're proposing essentially an upheaval of the web where everyone uses them, which is bad for competition. I also don't need users to download another app when they may already have Authy or one of the many other auth apps. It seems like it wouldn't be that hard to implement on Supabases end (because you already have magic links) and would be great to not require a password as well!

## Describe the solution you'd like

A solution would be to add [passwordless login](#additional-context) to Supabase.

## Describe alternatives you've considered

Not using it? Like adding normal auth.

## Additional context

How it works:

When you create an account, you type in an email and have no password. Just like normal, you get a magic link (or you can use an auth app of your choice). 

Next time you log back in, you use the magic link (or auth app) *again*. 

Easy!

**Comment by Isaiah-Hamilton** [comment]
@quick007 supabase already has passwordless login https://supabase.com/docs/guides/auth/auth-magic-link

**Comment by quick007** [comment]
Does supabase have a plan to support auth apps?

**Comment by kiwicopple** [comment]
> support auth apps

Hey @quick007 - can you share a bit more about what you're looking for here? Perhaps you want OAuth logins? Check out the providers we support here: https://supabase.com/docs/guides/auth#providers
