### ISSUE TITLE
MetaMask for authentication

### ISSUE THREAD

**Issue by techronin** [supabase/supabase#6474]
# Feature request

MetaMask for authentication

## Is your feature request related to a problem? Please describe.

it’s not related to a problem. It is a suggestion to enhance the existing product. It would be useful to be able to authenticate users with MetaMask wallet. 

A clear and concise description of what you want and what your use case is.

A token gated community is an emerging “Web3” business model. An NFT can act as identity, and provide access to a product, service, or an experience. However there are few tools that bridge both the “web2” and “web3” worlds. I believe that with a “simple” integration of a popular wallet like MetaMask. Supabase would provide a strong foundation for engineers to experiment and create new products, services, and experiences that leverage web3 concepts.

## Describe the solution you'd like

allow users to such their wallet and authorize themselves, in a similar way to what you already have with exiting Auth providers. 

I would like to try to create this feature for the community. Perhaps we could make a solution and have it reviewed by the Supabase team?

## Describe alternatives you've considered

There are few options that are ready made, or that could be widely used.

A friend I met recently has already created a complimentary solution and he’s looking for partners to work with. He’s created a way to validate the ownership of an NFT through two different wallet providers.

**Comment by Isaiah-Hamilton** [comment]
Sounds good. I'll move this issue to our authentication repository.

**Comment by kiwicopple** [comment]
Hi @techronin we have a PR for this open here: 
https://github.com/supabase/gotrue/pull/282

So I'll close this one in favour of the PR :)

We still need to investigate more though since the EIP for ethereum logins is still in draft and we don't want to compromise the security of existing Authentication method
