### ISSUE TITLE
bug/web: Styling of warning alert boxes has low contrast.

### ISSUE THREAD

**Issue by Ziinc** [supabase/supabase#6486]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/22714384/163817463-1b0cb52e-65b7-4c74-ab2c-965a9034e81d.png">

```
:::warning

Large projects may run into a `400 ORDER BY` memory limit error when querying with many unnested rows across large date ranges. If experiencing this error, consider reducing the number of unnested joins, or by reducing the queried date range.
:::

cc @MildTomato @joshenlim 

```

**Comment by Isaiah-Hamilton** [comment]
That's weird, it seems to look just fine for me. What browser are you using?
<img width="550" alt="Screen Shot 2022-04-18 at 7 07 04 PM" src="https://user-images.githubusercontent.com/70828596/163890994-dbaa5ee1-0a53-4b72-8a8b-91c1eb511c34.png">

**Comment by kiwicopple** [comment]
I think it's because Zinc is using a `warning`. @Ziinc - do you need that? I only added styles for `caution` and `note`

**Comment by MildTomato** [comment]
Closing this in favour of just using 'caution' and 'note'.
