### ISSUE TITLE
Favicon not appearing correctly on Safari

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#649]
# Bug report

## Describe the bug

![image](https://user-images.githubusercontent.com/10214025/106535640-a7537700-6531-11eb-9c0c-fc175cff2991.png)

## System information

- OS: mac
- Browser safari Version 14.0.1 (15610.2.11.51.10, 15610)

**Comment by soedirgo** [comment]
🤔

<img width="364" alt="Screenshot 2021-02-02 at 2 22 52 PM" src="https://user-images.githubusercontent.com/31685197/106560605-3bd5cd80-6562-11eb-8c84-efcae084ccaa.png">

**Comment by kiwicopple** [comment]
Looks like you're on `app.supabase.io`? Try https://supabase.io

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/10214025/106565482-d685da80-6569-11eb-9aac-7f92e4be1929.png">


Separate issue, what's up with that tagline? Perhaps they can be solved together

<img width="648" alt="image" src="https://user-images.githubusercontent.com/10214025/106565515-e6052380-6569-11eb-9844-0d891bfb8410.png">

**Comment by MildTomato** [comment]
Yea they have 2 different setups.
I'll take a look at this.

**Comment by MildTomato** [comment]
not sure what's going on here, updated all the favicons and still not appearing in the tab bar.
although all the other favicons are working for search bar and bookmarks.

![Screenshot 2021-02-02 at 19 47 30](https://user-images.githubusercontent.com/8291514/106596136-8faadb80-658f-11eb-84f8-d3faba57a1ac.png)

![Screenshot 2021-02-02 at 19 47 23](https://user-images.githubusercontent.com/8291514/106596132-8de11800-658f-11eb-9fc7-bd459fedcb20.png)

**Comment by inian** [comment]
@MildTomato this is because of the mask icon color [here](https://github.com/supabase/supabase/blob/master/www/components/Meta.tsx#L27). Commenting that line fixes the issue. Can you put in a suitable color there instead? Looks like it is a [good idea](https://developer.yoast.com/blog/safari-pinned-tab-icon-mask-icon/) to have it.

**Comment by MildTomato** [comment]
@inian nice! i was looking at the same page before - weird

**Comment by inian** [comment]
Adding a different mask icon color did not seem to fix it. So I commented that line out and at least the favicon shows properly now.
