### ISSUE TITLE
Prism theme not working for some users

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#651]
# Bug report

## Describe the bug

Dashboard:

![image](https://user-images.githubusercontent.com/10214025/103539918-2bfe9700-4e99-11eb-8f4a-fa534aba2d4b.png)

Docs:

![image](https://user-images.githubusercontent.com/10214025/103539898-1f7a3e80-4e99-11eb-8791-2a13ed49e339.png)

## To Reproduce

Very hard to figure out. 

- This user is using Chrome Version 87.0.4280.88 (Official Build) (x86_64) on MacOS BigSur.
- They disabled all ad blockers 
- no blocked requests
- I tried with this Chrome (but not BigSur), and it didn't replicate
- I've seen other users complain with Firefox

<img width="621" alt="104815039-23b93b00-584d-11eb-9bfc-673ae4a2148d" src="https://user-images.githubusercontent.com/10214025/106549885-e80cb980-654c-11eb-80f4-82c5ee7a09d6.png">

https://twitter.com/supabase_io/status/1350442091449442308

**Comment by kiwicopple** [comment]
Looks like jeroen has the root issue:

![image](https://user-images.githubusercontent.com/10214025/110266231-546d5380-7ff8-11eb-80ae-773be824429a.png)

I'm not sure now how to solve it, but finally some progress 💯

**Comment by MildTomato** [comment]
Might be wrong here, but we don't seem to import this font into the dashboard- which probably explains why it broke, it will just be relying on what is installed locally.

**Comment by kiwicopple** [comment]
Will need to double-check the docs too, because it was a problem there as well:

![image](https://user-images.githubusercontent.com/10214025/110267567-0e65bf00-7ffb-11eb-8788-646974e5cbca.png)

**Comment by MildTomato** [comment]
Alright, not a problem - i'll take a look
