### ISSUE TITLE
SQL editor: show breadcrumbs

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#655]
# Feature request
Like on other screens, show breadcrumbs like Orga1 > Project1.
This is to reassure that the script will be executed against the right DB.

Unless this was by design, e.g. because I can run scripts against any DB, even outside the current project, which I personally I wouldn't want to be able to do in first place.

**Comment by kiwicopple** [comment]
Agreed @peachp 

We originally removed this to give a larger editing experience to the SQL editor, but I think it's quite important. I've added it back - it will be in the next release

**Comment by peachp** [comment]
@kiwicopple thanks! ...yeah I found myself going back a few times to make sure I'm executing the SQL against the right DB
