### ISSUE TITLE
Backup spinning wheel hanging

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#657]
# Bug report
After clicking on "Backup now", the wheel keeps spinning now for over 5, probably 10mins.
The DB only has one table with 17k rows.
Tried to reload the screen (in hope it is a GUI issue only): the wheel is no longer spinning, but there is also no new backup entry.

![image](https://user-images.githubusercontent.com/47209189/106603655-7d607b80-6556-11eb-994d-53a5a2d34ef0.png)

**Comment by inian** [comment]
Hey @peachp, will investigate this

**Comment by dragarcia** [comment]
Hi @peachp, thanks for the feedback! The `Backup now` button and manually initiated backups altogether should no longer have this behavior in the GUI. 😄
