### ISSUE TITLE
Docusaurus build error: Unable to build website for locale en. | ValidationError: colorMode.switchConfig is deprecated.

### ISSUE THREAD

**Issue by ingokpp** [supabase/supabase#6570]
# Bug report

## Describe the bug

I've setted up a fresh fork of the supabase repository using a MacBook Air + M1 Chip.
Firstly I installed the dependencies in the `web` folder using `yarn install`. (It doesn't matter if I am using yarn or npm).
After successfully installing the dependencies i tried to run `yarn build`, which fails and shows the following output:

`
...
...
Saved:  docs/reference/cli/supabase-functions-new.mdx
Saved:  docs/reference/cli/supabase-db-push.mdx
Saved:  docs/reference/cli/supabase-secrets-unset.mdx
Saved:  docs/reference/cli/supabase-login.mdx
Saved:  docs/reference/cli/config-reference.mdx
Saved:  docs/reference/cli/supabase-secrets-set.mdx
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: colorMode.switchConfig is deprecated. If you want to customize the icons for light and dark mode, swizzle IconLightMode, IconDarkMode, or ColorModeToggle instead.
`

## To Reproduce

1. fork/clone a fresh copy of the supabase repository.
2. cd into the web folder
3. run `npm install` or `yarn install`
4. run `yarn build`

## Screenshots

![log output](https://user-images.githubusercontent.com/32964262/165305117-0d53f5cf-181b-4dc1-8f24-71dacbcc8b8d.png)

## System information

- OS: macOs Monterey 12.3.1. | Apple M1
- Version of Node:  v18.0.0
- Version of NPM: 8.7.0

**Comment by Hallidayo** [comment]
Looking at the Docusaurus [repository](https://github.com/facebook/docusaurus/pull/6771) it seems that `colorMode.switchConfig` is now depreciated. 

On my local fork if I remove the `switchConfig` object and then run `yarn build` then the build succeeds. By doing this the dark mode toggle switch is then removed and icons are now displayed instead in the header:


https://user-images.githubusercontent.com/22655069/165341573-f90a1fe6-93ca-434b-b862-459d9d25cac2.mov

Shall I create a PR for this change or is the toggle switch preferred instead of icons?

**Comment by ingokpp** [comment]
> Looking at the Docusaurus [repository](https://github.com/facebook/docusaurus/pull/6771) it seems that `colorMode.switchConfig` is now depreciated.
> 
> On my local fork if I remove the `switchConfig` object and then run `yarn build` then the build succeeds. By doing this the dark mode toggle switch is then removed and icons are now displayed instead in the header:
> 
>  Screen.Recording.2022-04-26.at.16.48.40.mov 
> Shall I create a PR for this change or is the toggle switch preferred instead of icons?

Thank you for help, @Hallidayo 💪. I also tested the same thing and [already created a PR](https://github.com/supabase/supabase/pull/6575). 🤗

**Comment by MildTomato** [comment]
What version of docusaurus are you running ?

@ingokpp @Hallidayo

**Comment by Hallidayo** [comment]
@MildTomato - I'm running `"@docusaurus/core": "^2.0.0-beta.6"`

**Comment by burmecia** [comment]
I think this issue has been fixed, so will close it. Feel free to create a new one if this is still an issue.
