### ISSUE TITLE
Missing .env documentation

### ISSUE THREAD

**Issue by ingokpp** [supabase/supabase#6571]
# Improve documentation

## Describe the problem

The README-file of the  `www` folder is missing documentation about a relevant .env file which includes the variable `NEXT_PUBLIC_DOCS_URL`. This variable is used by the next.config.js and should **locally** be equal to "http://localhost:3005", i guess?

## Describe the improvement
Better flow of repository setup.

**Comment by MildTomato** [comment]
@ingokpp maybe this is a better solution, we'll just add the env file in for this app
PR added above.

**Comment by ingokpp** [comment]
Yep, seems like a hoof solution. Would approve if I could 🤗
