### ISSUE TITLE
Broken pricing link

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#6574]
pricing link is outdated here: https://supabase.com/docs/faq

should point to https://supabase.com/pricing

**Comment by Hallidayo** [comment]
@awalias - I can see that has already been assigned, but could I take this one?

**Comment by awalias** [comment]
@Hallidayo yea go for it!

**Comment by Hallidayo** [comment]
@awalias - Thankyou, Just created a [pull](https://github.com/supabase/supabase/pull/6593) for this.

**Comment by awalias** [comment]
Thanks!
