### ISSUE TITLE
Broken link to example app in storage doc page

### ISSUE THREAD

**Issue by alexander-mart** [supabase/supabase#6590]
# Improve documentation

## Link 

https://supabase.com/docs/guides/storage#getting-started

## Describe the problem

Broken link (404) to `nextjs-ts-user-management`:
https://github.com/supabase/supabase/edit/master/examples/nextjs-ts-user-management

```
Find a full [example application in GitHub](https://github.com/supabase/supabase/edit/master/examples/nextjs-ts-user-management),
```

## Describe the improvement

Find working link or remove example from docs.

**Comment by Hallidayo** [comment]
I've created a [pull request](https://github.com/supabase/supabase/pull/6599) for this one.

**Comment by JoeyFenny** [comment]
Same issue for Next.js Realtime Chat App example:
https://github.com/supabase/supabase/tree/master/examples/nextjs-slack-clone

**Comment by Hallidayo** [comment]
@JoeyFenny - does the example link into the docs?

**Comment by kiwicopple** [comment]
@Hallidayo - I think they may be talking about a few links here:
https://supabase.com/docs/guides/examples

Perhaps you could help correct these one too?

**Comment by Hallidayo** [comment]
@kiwicopple - cool no problem I’ll take a look.

**Comment by Hallidayo** [comment]
@kiwicopple - I've created a pull request for the links.

I also did notice that in the Libraries section that their is a link for Kotlin:

<img width="314" alt="Screenshot 2022-05-02 at 19 01 56" src="https://user-images.githubusercontent.com/22655069/166300458-5239cbdc-7466-4e46-88df-f2871e0cd80d.png">

But I can not find any libraries by supabase for Kotlin:

<img width="923" alt="Screenshot 2022-05-02 at 19 03 28" src="https://user-images.githubusercontent.com/22655069/166300621-273eec67-294f-4778-bf69-7394b5f0302e.png">

Shall I remove the Kotlin line all together or just the Github link?

**Comment by kiwicopple** [comment]
looks like the kotlin libs are here! 

https://github.com/supabase-community/postgrest-kt

**Comment by Hallidayo** [comment]
I've created a pr for this: #6691

**Comment by aminamos** [comment]
> Same issue for Next.js Realtime Chat App example: https://github.com/supabase/supabase/tree/master/examples/nextjs-slack-clone

@JoeyFenny This is addressed in https://github.com/supabase/supabase/pull/6729

**Comment by Hallidayo** [comment]
Hi @saltcod, yeah I believe so as the links should be working now.
