### ISSUE TITLE
Table editor: no indication / feedback that the data is being loaded

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#660]
# Bug report
When opening the Table editor with a large table (in my case > 10k rows), there is no indication whether anything is being loaded. The data then suddenly appears after 3-7 seconds. This makes me thing whether I really have no data, or maybe it is not shown due to Filters.

## Possible solution
Show a spinning wheel next to the table name, or even in the centre of the area where the rows will appear. Same could be done for when applying Filters / Sorting (yes, there is a wheel in the right top corner, but it is covered by the panel at the time of clicking "Apply" and when the panel slides away, the eyes are already somewhere else.)

**Comment by awalias** [comment]
fixed
