### ISSUE TITLE
Python realtime client support ?

### ISSUE THREAD

**Issue by luc-languagetools** [supabase/supabase#6601]
When can we expect official python support for realtime updates ? I see here https://supabase.com/docs/guides/client-libraries it says "not yet implemented".

**Comment by Garett-MacGowan** [comment]
There's an unofficial client library for python in the community repo that may be worth looking into. I'm in the process of trying to implement it into my project.

https://github.com/supabase-community/realtime-py

**Comment by MildTomato** [comment]
I'm going to close this as python library is already in development
