### ISSUE TITLE
Note says realtime only works on the public schema which is not (no longer) accurate.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#6606]
# Improve documentation

https://supabase.com/docs/guides/api#realtime-api-1

![image](https://user-images.githubusercontent.com/54564956/165872853-1fc9cf8a-7391-4307-b7d9-e9e96fe1b6e8.png)

## Describe the problem

Although it is complicated, realtime does work on tables in other schemas.

![image](https://user-images.githubusercontent.com/54564956/165872771-bec8da69-a107-4556-95e9-7a9c3cea4056.png)

I suggest just deleting this note.  Implementing the grants for other schema and tables,  setting the client to use the schema, adding the schema to the API is complicated enough that anyone able to do that should understand realtime will work.  This is especially true since realtime standalone docs show schemas and replication UI shows tables in other schemas.

BUT the note will cause (has caused) users to not try based on the note saying it won't work.

**Comment by kiwicopple** [comment]
> I suggest just deleting this note.

I agree, good suggestion @GaryAustin1

**Comment by MildTomato** [comment]
I think I mentioned this to @w3b6x9 

Supabase can maybe move towards 'always on' realtime for any schema exposed via api?
Especially since RLS is working for it now.
