### ISSUE TITLE
Error Getting User Email From External Provider (DISCORD AUTH)

### ISSUE THREAD

**Issue by MATTIRG** [supabase/supabase#6625]
# Bug report

## Describe the bug

So I have been working on this side project that uses discord auth. Everything has been working since I started (About a month). I went to power up the website and login today, and when I have logged in, and get redirected to my website, and the URL looks as follows:
http://localhost:8080/?error=server_error&error_description=Error+getting+user+email+from+external+provider

## To Reproduce
This bug happens when I use the login function described in the docs.

## Expected behavior
I would expect to be redirected back to my site, and be logged in, with the user in local storage, as has happened for the last month.

## System information

- OS: Windows 10
- Browser: Brave
- Version of supabase-js: 1.35.2
- Version of Node.js: v16.14.0

## Errors:
No errors are being produced from my site, as far as I can see.

**Comment by PhaxeNor** [comment]
This was recently pushed https://github.com/supabase/gotrue/pull/462 and a deploy is happening on it too https://github.com/supabase/gotrue/actions/runs/2246639610

Don't know if this will resolve this though.

**Comment by kangmingtay** [comment]
Hi, we're working on a fix for this now, it should be addressed by https://github.com/supabase/gotrue/pull/462 and we're rolling it out to all projects now

**Comment by kangmingtay** [comment]
This fix should be rolled out to all projects already - but feel free to reach out to our support channel (https://app.supabase.io/support/new) if you're still facing any issues, happy hacking!

**Comment by Spikeysanju** [comment]
@kiwicopple is there any update on this. Please let me know. Thanks in advance!

**Comment by kangmingtay** [comment]
Hey @Spikeysanju, this issue has been closed but if you are still facing issues with discord logins, please reach out to support@supabase.io

**Comment by Swiip** [comment]
Hey, I hit the very same error just recently so this doesn't seems solved to me.

But I was able to investigate with my users and get the explanation. This happens when the Discord account of the user is missing either the email address or the phone number. If one of them is missing then the login fail that way. Once the Discord account filled up, it passes.

Still, I think that the Supabase Discord connected would better to allow that kind of situations that just happen in real life.
