### ISSUE TITLE
Sending magic link failed: Database error finding user

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#663]
# Bug report

## Describe the bug

When attempting to send a magic link, I'm seeing the error `Sending magic link failed: Database error finding user`. This happens when it's triggered from code (the POST request returns a 500 status code) and from the supabase UI. I've also tried it with and without custom SMTP settings.

Since I can't see any more details of the error, it's hard to provide more info about it or figure out whether it has something to do with my table setup or the supabase-created auth table.

Any idea if there's something else I should try to diagnose this problem?

Thanks!

**Comment by erkeen** [comment]
You might dropped the auth.users table. Please check your authentication and there should be auth related table with columns, if there is no table with columns, you have to restore the auth.users table.

**Comment by emschwartz** [comment]
This turned out to be related to a runaway log file (on Supabase's end) filling up the server. As soon as that was fixed, the email sending started working again.

**Comment by dhaalac** [comment]
> You might dropped the auth.users table. Please check your authentication and there should be auth related table with columns, if there is no table with columns, you have to restore the auth.users table.

how can i restore the auth.users table.

**Comment by christopheragnus** [comment]
Hey  - how do you restore the auth.users table? I looked at my tables and looks like it already exists?

**Comment by tonymckendry** [comment]
I ran into this issue because Prisma wiped out my auth schema when I was experimenting - I was able to fix it by going into Supabase and toggling email authentication off and then back on in the authentication provider settings - that seemed to create a bunch of tables in my auth schema that were not there previously (due to being eliminated by Prisma).

**Comment by jackfriks** [comment]
> This turned out to be related to a runaway log file (on Supabase's end) filling up the server. As soon as that was fixed, the email sending started working again.

hey! how did you go about doing this? i think im having the same issue with 11,000 users now and running into a similar error where it shows the user in my users table but links arent being sent "Error sending magic link" despite it working fine for 2 months
