### ISSUE TITLE
Difficulty adding new schema to API settings.

### ISSUE THREAD

**Issue by Garett-MacGowan** [supabase/supabase#6630]
# Feature request

## Is your feature request related to a problem? Please describe.

When trying to add a new schema to the API settings, there is no clear button to show the available schema(s) to add. I spent a long time trying to figure out if schemas other than public schema were available for PostgREST. Surrounding design makes it seem like the whole section is temporarily locked down.

## Describe the solution you'd like

A clear button indicating the opportunity to select from available schema(s).

## Related tickets (alternative schema setup for API needs some love)

https://github.com/supabase/supabase/issues/6606
https://github.com/supabase/supabase/issues/4916

The clickable region is shown approximately in red in the image below:

![Untitled](https://user-images.githubusercontent.com/24864607/166069902-54e30d76-6798-4fd0-af46-6d01e92b0406.png)

**Comment by MildTomato** [comment]
Oh yes, this was badly implemented, we should fix this.
