### ISSUE TITLE
Server updates userMetadata using UpdateUserById, doesnot fire onAuthStateChange

### ISSUE THREAD

**Issue by abdalla-nayer** [supabase/supabase#6632]
# Bug report

## Describe the bug

1- After user successfully logs in.
2- based on certain actions, Server C# updates userMetadata using UpdateUserById.
3- onAuthStateChange does not fire on the frontend react application

"@supabase/supabase-js": "1.35.2",
node version: 16.13.2

Expected:
onAuthStateChange should fire on the FE

**Comment by kiwicopple** [comment]
> Server C# updates

I think this one might be better here @abdalla-nayer : https://github.com/supabase-community/gotrue-csharp

**Comment by abdallanayer** [comment]
@kiwicopple thank you, will open it there

**Comment by abdalla-nayer** [comment]
@kiwicopple thank you, will open it there
