### ISSUE TITLE
Access Tokens has no search results

### ISSUE THREAD

**Issue by Vandivier** [supabase/supabase#6634]
# Improve documentation

## Describe the problem

1. I generated an access token, then used it as a DB password to connect to a DB and it failed, yielding `Error querying the database: db error: FATAL: SASL authentication failed`
2. Then I thought "Maybe this is not what Access Tokens are used for" so I searched the docs and found no results for "Access Tokens"
3. The search overlay itself has a link that says `Believe this query should return results? Let us know` and the link on that text is broken.

**Comment by saltcod** [comment]
Thanks @Vandivier  looks like this one is related to this broader issue with the Algolia integration in the docs:
https://github.com/supabase/supabase/issues/6007

Hoping to get that fixed asap. 

Appreciate the report!
