### ISSUE TITLE
Can't set column default to empty string, and editing always resets all columns to remove the default

### ISSUE THREAD

**Issue by mozeryansky** [supabase/supabase#6636]
# Bug report

## Describe the bug

I want to have columns with a default value of an empty string. I don't see a way to do it in the studio. However, I am able to create the table using the SQL editor. Then there's 2 issue:
1. When I go to edit the table, even if I make no changes, all the columns are set back to have no default value.
2. I can't insert rows without specifying a value as the form says "Please assign a value for this field"

## To Reproduce

1. Use the SQL editor:
```
CREATE TABLE public.profiles (
    user_id uuid NOT NULL,
    name text DEFAULT '' NOT NULL,
);
```
2. Edit table, make no changes, click save
3. Use pg_dump or use PgAdmin to view CREATE statement

Result:
```
CREATE TABLE public.profiles (
    user_id uuid NOT NULL,
    name text NOT NULL,
);
```

## Expected behavior

1. Allow empty string as the default when creating a table
2. Don't reset empty string default when editing table
3. Allow using empty string default in the add row form

**Comment by mozeryansky** [comment]
For more context, when using a null default I get react warnings:
```Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.```

So I manually default the values to empty string using
```
const emptyProfile: Profile = {
  user_id: '',
  name: '',
}

const { data, error } = await supabase
    .from('profiles')
    .select()
    .eq('user_id', user.id)
    .single()

const profile = {
   ...emptyProfile,
   ...data
}
```

And I rather not need to do that.

**Comment by GaryAustin1** [comment]
You can set a default of empty string with format('') in the column editor.

**Comment by mozeryansky** [comment]
> You can set a default of empty string with `format('')` in the column editor.

That seems like more of a trick and also doesn't work. Did you test this and did it work for you?

---

Using `DEFAULT '' NOT NULL` should be all what's needed.  Supabase does not handle it properly and using a function does not make it work either. While Postgres handles empty string or using a function for default fine, it's Supabase that doesn't handle this properly and causes the table SQL to revert to a broken state.

My original issue still produces the same error. But here's the steps with your solution:
1. 
```
CREATE TABLE public.test (
    name text DEFAULT format('') NOT NULL
);
```
2. View generated SQL:
```
CREATE TABLE IF NOT EXISTS public.test
(
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT format(''::text)
)
```
3. Click edit in Supabase, make NO changes, click save. In supabase the default is converted into a broken string, instead of reverting back to null, so using a function is worse here.
<img width="218" alt="Screen Shot 2022-05-22 at 3 07 32 PM" src="https://user-images.githubusercontent.com/3287719/169713837-7a60a20c-c3a3-4046-9eeb-0afbc893ca17.png">

```
CREATE TABLE IF NOT EXISTS public.test
(
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ormat('''::text
)
```

**Comment by GaryAustin1** [comment]
Yeah, definitely strangeness going on.  It does seem to work in the column UI and keep working in that the string gets set to empty in the UI, but that was the level I had tested it a ways back.  I do see it messed up in the side editor, but editing and adding rows seems to work.

**Comment by GaryAustin1** [comment]
Just to follow up... This is what I get with datagrip on the table:
![image](https://user-images.githubusercontent.com/54564956/169714724-8fac3a58-cfdd-4102-9d03-3b3856d521d1.png)
Which seems correct.

**Comment by mozeryansky** [comment]
@GaryAustin1 What happens when you press edit in Supabase then press save?

**Comment by GaryAustin1** [comment]
If I edit the column settings and save then it is loses it, so would have to reset it again.  Worse if I edit the whole table structure and save it fails to.   Never edited the columns after the change.  I actually don't use the UI much for table structure and prefer sql or Datagrip.

So it is a pretty bad hack.

**Comment by joshenlim** [comment]
hey guys! sorry for taking such a long time to get to this - finally managed to do up a fix here
https://github.com/supabase/supabase/pull/6955

**Comment by mozeryansky** [comment]
@joshenlim Thank you!
