### ISSUE TITLE
Missing class on paragraph at the auth page

### ISSUE THREAD

**Issue by ardasoyturk** [supabase/supabase#6638]
# Bug report

## Describe the bug

Description about the social providers' color is different than other descriptions the grid. I also checked the source code and I couldn't see a difference on the source code side (they're the same). Screenshots are given below. In short, the first paragraph doesn't have the "p text-base" classes on production. But I saw the classes on the [source code](https://github.com/supabase/supabase/blob/d4d3d37a7de1f0484473ffe70f59d10ec8a64cc7/apps/www/pages/auth/Auth.tsx#L135).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/auth
2. Scroll down to 'All the social providers' section
4. See the difference on the paragraph colors

## Expected behavior

The paragraph colors are supposed to be same, gray. Not black.

## Screenshots
The current version:
![current version](https://user-images.githubusercontent.com/33841775/166135772-950eeab3-ec64-46c5-9b5d-94bc98b62b0a.png)
Fixed version:
![fixed version](https://user-images.githubusercontent.com/33841775/166135796-a49385ad-f362-4c40-a290-6f407457166a.png)

## System information

- OS: Windows
- Browser: Microsoft Edge - `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44'`

**Comment by saltcod** [comment]
I think this one will be fixed when this gets merged:

https://github.com/supabase/supabase/pull/6420

**Comment by ardasoyturk** [comment]
Oh I see, I'm closing the issue then. Thanks for your help.
