### ISSUE TITLE
API: dont relay headers from request to subsequent requests

### ISSUE THREAD

**Issue by inian** [supabase/supabase#6653]
We are relaying headers from the client request on to other middleware requests blindly [here](https://github.com/supabase/supabase/blob/9373f69220201962f669af8f977b5d39f1460927/studio/lib/api/apiHelpers.ts#L9). 

This leads to bugs (a recent one where the client host name is passed on to middleware ref https://github.com/supabase/supabase/pull/6652) and also no reason why we should be passing stuff like useragent and referrer to the middleware when the request is being made from the next.js API.

**Comment by MildTomato** [comment]
Added you @phamhieu - even though it's in studio, figured you might still want to look after the functions in studio?

**Comment by phamhieu** [comment]
Good catch!!! we should pick required header like 'apikey', 'authorization'... instead of copy all.

**Comment by MildTomato** [comment]
I think it might just be the connection-string that needs forwarding on @phamhieu
