### ISSUE TITLE
Fix Broken Link in Quickstart: React

### ISSUE THREAD

**Issue by adrianmurage** [supabase/supabase#6668]
# Improve documentation

## Link 

[Initialize a react app](https://supabase.com/docs/guides/with-react#initialize-a-react-app)

## Describe the problem

"And one optional step is to update the CSS file src/index.css to make the app look nice. You can find the full contents of this file [here](https://raw.githubusercontent.com/supabase/supabase/master/examples/react-user-management/src/index.css)."

The link to the CSS file above is broken. 

## Describe the improvement

The link should be updated to: https://raw.githubusercontent.com/supabase/supabase/master/examples/user-management/react-user-management/src/index.css

## Additional context

I can submit a PR that corrects this issue : )

**Comment by Hallidayo** [comment]
@adrianmurage - I found that also the Next JS Quickstart had the same problem so I've created a [pull](https://github.com/supabase/supabase/pull/6669)
