### ISSUE TITLE
Is there any plan to add Logs Explorer to self-hosted supabase?

### ISSUE THREAD

**Issue by ImSingee** [supabase/supabase#6674]
Just like https://app.supabase.io/project/[project-id]/logs-explorer

**Comment by Ziinc** [comment]
Hi @ImSingee , yes there are plans to provide a self-hostable backend for the logs explorer. If you would like to follow our progress, you can keep an eye on the [Logflare github](https://github.com/Logflare/logflare/issues) for now.
