### ISSUE TITLE
Update hero and tag line

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#67]
![image](https://user-images.githubusercontent.com/458736/81635104-f35e0900-9442-11ea-8cc8-2839b208ed56.png)

maybe just remove "existing"

**Comment by kiwicopple** [comment]
Also need to update the OG graph image. I thought I did it the other day but it hasn't worked
https://github.com/supabase/supabase/commit/f81760cab2cc0f7a171fb4ec31dcad46b38df973

**Comment by kiwicopple** [comment]
fixed the tagline, although the OG image probably still not working - task for another day
