### ISSUE TITLE
OpenAPI spec shows optional for all fields in a view 

### ISSUE THREAD

**Issue by mozeryansky** [supabase/supabase#6708]
## Describe the bug

I have a view in postgres based off another table, all the fields should be non-optional. The definitions being returned do not mark those fields are 'required' so `openapi-typescript` generates all the properties in the type as optional.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create table using only non-null
2. Create view
3. https://supabase.com/docs/reference/javascript/generating-types

## Expected behavior

The fields should be marked 'required' so `openapi-typescript` generates the proper type.

---

For now I am wrapping the type in `Required<...>`

**Comment by kiwicopple** [comment]
Our v2 JS libs now support type generation, see the docs here: https://supabase.com/docs/reference/javascript/typescript-support

I'll close this one in favour of our v2 approach - thanks for the bug report @mozeryansky 👍
