### ISSUE TITLE
Session is still null after SignIn

### ISSUE THREAD

**Issue by raccoman** [supabase/supabase#6764]
I'm looking to redirect users from all pages to the login page unless they are already signed in. I've built a ProtectedRoute component that checks if there is a user logged in and whether the path is protected, and will router.push to /login accordingly.

The issue im having is that after `await supabase.signIn()` is called, I’m being sent back to my login page. What I think is happening is that after signin I'm redirected to my homepage, but after the redirect  `supabase.auth.user()` is still null, and my ProtectedRoute component is then redirecting back to /login because of this. If I enter the url to go to the home (or other) page again, it won’t redirect me back to login, `user` is no longer null and they are signed in. 

In other posts I saw `onAuthStateChange` suggested to be used. But I am already using an AuthProvider similar to the examples that utilise `onAuthStateChange`. I think in my case it may be that the change in path is triggering a redirect before the user state is changed (also perhaps before the cookie is set?). But I'm not sure how to fix this.

I see in a few examples people redirect with getServerSideProps. But if I did this, all of my pages would go from client side rendering to SSR, and I’m not sure if that would benefit me since I'm not interested in SEO. Although I’m not a fan of the loading page flash that occurs when a protected route is being client side redirected to the login page.

_Originally posted by @joshiain in https://github.com/supabase/supabase/discussions/2842_

**Comment by lack-of-gravitas** [comment]
Same / similar problem. 

I've tried the following implementations and used variations without success auth-helpers-nextjs. **None of the instructions provided work for a simple Magic Link only implementation I started from scratch on localhost**. Session variable isnt available or preserved with the minimal example from the official pages OR the other implementation.

I'd love to look at a properly working end to end repo as I've spent several days on this now.

Email notification works, link routes back to locahost:3000/#***** with ** being the token and a redirect parameter back to http://localhost:3000/

Attempts
1 -- Supabase Auth Quickstart with magic link example -- https://supabase.com/docs/guides/with-nextjs
For this one navigation to page where Account / Auth components are used the error is also thrown with session as null.
![image](https://user-images.githubusercontent.com/10094964/180590981-e4807adf-f900-499c-9668-aecb6504faab.png)

2 -- Supabase example NextJS with Supabase Auth -- https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth

3 -- NextJS Subscription Example -- https://github.com/vercel/nextjs-subscription-payments -- **their deployment on vercel works but cloning repository locally for use with my Supabase instance with env vars etc doesnt**. Since local doesnt work I havent bothered to deploying to PROD in Vercel

5 -- older Nader Dabit video and implementation https://github.com/dabit3/supabase-nextjs-auth and https://www.youtube.com/watch?v=oXWImFqsQF4&t=1277s

**Comment by jjrise** [comment]
any updates here? I'm having the same issue of having a null session directly after logging in.

**Comment by lack-of-gravitas** [comment]
@jjrise I used the nextjs-auth example located in the examples folder/sub-folder for the supbase repo which seems to have resolved my issue. YMMV

https://github.com/supabase/supabase/tree/master/examples/auth/nextjs-auth

**Comment by wobsoriano** [comment]
Is this fixed in v2?

**Comment by GaryAustin1** [comment]
This is a pretty old issue and all v1 code as far as I can tell.
If you still have issues it might make sense to open a new issue and in particular report using v2 code as v1 is no longer getting general fixes.

**Comment by hudanazy** [comment]
This solved the issue for me
Before:
`useEffect(() => {
  
    const session = supabase.auth.getSession();
    setSession(session);
    setUser(session?.user ?? null);
    setLoading(false);


    // Listen for changes on auth state (logged in, signed out, etc.)
   
    const { data: listener } = supabase.auth.onAuthStateChange(async (event, session) => {
     setSession(session);
      setUser(session?.user ?? null);
      setLoading(false)
    })
 

    return () => {
      listener?.subscription.unsubscribe()
    }

  }, [])`
After:
  `  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
       setUser(session?.user ?? null);
    setLoading(false);
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
       setUser(session?.user ?? null);
    setLoading(false);
    })
    
    

  }, [])`

**Comment by Har1s-Akbar** [comment]
I am currently working on an application and i have implemented supabase auth with nextjs. I was facing the same issue that "session was null even after successfully signing in the user".
This issue is happening because the user you are trying to sign in has not verified his email from the email supabase has sent him.
when you sign up a user with supabase. Supabase sends an email to the user confirming if user provided email is real. When user verifies it's email the session is populated and when the email is not verified the session null is shown.

**Comment by hmtcelik** [comment]
i was have the same problem and i used createServerClient instead of browserClient from supabase/ssr, and its gone, i used the createServerClient in both of them (for signin and getSession)

**Comment by nicitaacom** [comment]
I fixed it - https://github.com/supabase/supabase/issues/20993





<br/>
<br/>



# Solution (how to fix this issue)

1. My mistake was that I used `supabaseClient` that takes no cookies and created for client components
2. My mistake was that I forgot to setup `middleware.ts`

## To fix

### 1. Create `supabaseServer`
**app/libs/supabase/supabaseServer.ts**
```ts
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import { Database } from "@/interfaces/types_db"

const supabaseServer = () => {
  cookies().getAll() // Keep cookies in the JS execution context for Next.js build
  return createServerComponentClient<Database>({ cookies })
}

export default supabaseServer
```

### 2. Use `supabaseServer` in server component
**app/page.tsx**
```tsx
import { LoginForm } from "./components/LoginForm"
import supabaseClient from "./libs/supabase/supabaseClient"
import supabaseServer from "./libs/supabase/supabaseServer"

export default async function Home() {
  const {
    data: { user },
  } = await supabaseServer().auth.getUser()
  console.log(12, "user - ", user)

  return (
    <>
      <LoginForm />
      {JSON.stringify(user)}
    </>
  )
}
```

### 3. Setup middleware to refresh auth token when session expires 
(on 02.2024 supabase don't provide 'Remember me' functionality where you can save session to be valid for some time e.g 30 days)
**middleware.ts**
```ts
import { createMiddlewareClient } from "@supabase/auth-helpers-nextjs"
import { NextResponse } from "next/server"

import type { Database } from "@/interfaces/types_db"
import type { NextRequest } from "next/server"

export async function middleware(req: NextRequest) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient<Database>({ req, res })
  await supabase.auth.getSession()
  return res
}
```

**Comment by rahul-singhania223** [comment]
User  "createServerClient" instead of "createBrowserClient"

import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";

function createClient() {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        set(key, value, options) {
          cookies().set(key, value, options);
        },
        get(key: string) {
          return cookies().get(key)?.value;
        },
      },
    }
  );
}

export { createClient };

**Comment by nicitaacom** [comment]
Please use formatting

**Comment by mascanho** [comment]
> import { createServerClient } from "@supabase/ssr";
> import { cookies } from "next/headers";
> 
> function createClient() {
>   return createServerClient(
>     process.env.NEXT_PUBLIC_SUPABASE_URL!,
>     process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
>     {
>       cookies: {
>         set(key, value, options) {
>           cookies().set(key, value, options);
>         },
>         get(key: string) {
>           return cookies().get(key)?.value;
>         },
>       },
>     }
>   );
> }
> 
> export { createClient };

This worked for me!!!
The docs are so confusing.... tks mate!!!

**Comment by Ve2s4** [comment]
**Problem**
The server-side client successfully retrieves user details, but the browser client returns a null user. As a result, I am unable to display user details on the client side and must instead depend on server components at the top of the component hierarchy.

I followed [this](https://github.com/vercel/nextjs-subscription-payments) example starter guide.

**Following logs the user as null**

```
import {createClient} from "@/utils/supabase/client";

export default async function AccountPage() {

    const supabase = createClient();

    const {data} = await supabase.auth.getUser()

    console.log("data", data)


    return <div>Account page</div>;
}

```

**While this works**


```
"use server";

import {createClient} from '@/utils/supabase/server';
import {getUser} from "@/utils/supabase/queries";

export default async function AccountPage() {

    const supabase = createClient();

    const user = await getUser(supabase);

    console.log("user", user)

    return <div>Account page</div>;
}
```


### Server Side Client

```
import {type CookieOptions, createServerClient} from '@supabase/ssr';
import {cookies} from 'next/headers';

// Define a function to create a Supabase client for server-side operations
// The function takes a cookie store created with next/headers cookies as an argument
export const createClient = () => {
    const cookieStore = cookies();

    return createServerClient(
        // Pass Supabase URL and anonymous key from the environment to the client
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,

        // Define a cookies object with methods for interacting with the cookie store and pass it to the client
        {
            cookies: {
                // The get method is used to retrieve a cookie by its name
                get(name: string) {
                    return cookieStore.get(name)?.value;
                },
                // The set method is used to set a cookie with a given name, value, and options
                set(name: string, value: string, options: CookieOptions) {
                    try {
                        cookieStore.set({name, value, ...options});
                    } catch (error) {
                        // If the set method is called from a Server Component, an error may occur
                        // This can be ignored if there is middleware refreshing user sessions
                    }
                },
                // The remove method is used to delete a cookie by its name
                remove(name: string, options: CookieOptions) {
                    try {
                        cookieStore.set({name, value: '', ...options});
                    } catch (error) {
                        // If the remove method is called from a Server Component, an error may occur
                        // This can be ignored if there is middleware refreshing user sessions
                    }
                }
            }
        }
    );
};
```

### Client Side Client

```
import {createBrowserClient} from '@supabase/ssr';

// Define a function to create a Supabase client for client-side operations
export const createClient = () =>
    createBrowserClient(
        // Pass Supabase URL and anonymous key from the environment to the client
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);
```

**Comment by dhruv1710** [comment]
Before

`import { createClient } from '@supabase/supabase-js';`

After

`import { createBrowserClient } from '@supabase/ssr';`

And it solved all the issues for me!
