### ISSUE TITLE
Sms Provider dropdown text-color is same as background-color in /auth/settings page

### ISSUE THREAD

**Issue by ChristianLutzCL** [supabase/supabase#6768]
# Bug report

## Describe the bug

Phone Auth: SMS Provider Dropdown text is same color as background.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://app.supabase.io/project/[PROJECTID]/auth/settings'
2. Scroll down to 'Phone Auth'
3. Click on 'Sms provider' Dropdown

## Expected behavior

The Sms Providers should be shown in white color without the need to hover over it.

## Screenshots

![2022-05-11 07_19_09-Clipboard](https://user-images.githubusercontent.com/30475783/167776151-50b0965b-ceb8-473f-801e-befcb88c8cc9.png)

## System information

- OS: Windows 10
- Browser: Google Chrome Version 101.0.4951.54

**Comment by MildTomato** [comment]
@saltcod yep 😄

**Comment by joshenlim** [comment]
just fyi this is potentially something specific to your browser @ChristianLutzCL, any chance you might have some chrome extension related to dark mode? The component here uses a native browser dropdown component as well so it should work out of the box afaik

on production this is how it looks like for me
![image](https://user-images.githubusercontent.com/19742402/173784022-17c4c08d-cfee-4bbb-8bcf-5e45d1a55d28.png)

@MildTomato's fix here will be a separate thing, but I'm gonna go ahead to close this ticket first. Please do feel free to reach out if you might still be hitting this

**Comment by ChristianLutzCL** [comment]
@joshenlim Really strange.
It can't be any extension, because I have the same problem with Chrome on other computers at work. By the way, the problem is also present in incognito mode and even in "light mode".

If I deactivate the color in "select options" in DevTools, the error would be solved.
![image](https://user-images.githubusercontent.com/30475783/173790673-0731883a-647e-4910-94a5-6595395c3a35.png)

**Comment by joshenlim** [comment]
@ChristianLutzCL ahh okay gotcha, thanks so much for this! i'll reopen this ticket and investigate further to see what else I can find :)

**Comment by joshenlim** [comment]
@ChristianLutzCL i threw in a quick style fix in this PR here:
https://github.com/supabase/supabase/pull/7295

the fix should go out in prod in a bit - could you check if this might have resolved the problem for you?

**Comment by ChristianLutzCL** [comment]
It works 👍
Thank you.

![image](https://user-images.githubusercontent.com/30475783/174058865-3add61b4-6e22-47bd-981c-0102009ee6e2.png)
