### ISSUE TITLE
Unable to connect to database locally

### ISSUE THREAD

**Issue by simplismio** [supabase/supabase#6772]
Followed the exact steps in: https://supabase.com/docs/guides/local-development

Setting up client in Flutter with 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/91443226/167793648-4e749fde-bb06-40d4-8a83-891d0a8eae30.png">

Credentials shared by terminal: 
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/91443226/167793755-3be2fa62-7452-4e32-9f8b-bd3c35286947.png">

Error:
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/91443226/167793823-817c6e8a-066d-4213-9f48-fc9428457191.png">

Tried the credentials in many different ways. Unable to connect to database.

**Comment by simplismio** [comment]
Was caused by MacOs sandbox issue, Supabase worked fine

**Comment by acurrieclark** [comment]
@simplismio mind if I ask how you resolved this issue?

Many thanks

**Comment by simplismio** [comment]
@acurrieclark, yes, after setting the sandbox info.plist settings for Flutter MacOS it worked fine

**Comment by acurrieclark** [comment]
Understood. Thanks for your help.
