### ISSUE TITLE
Validation rules of custom JWT secret

### ISSUE THREAD

**Issue by darora** [supabase/supabase#6805]
(placeholder issue to be fleshed out)

Certain character sequences are treated as illegal by Postgrest (and possibly other services). We should have validation rules in the dashboard preventing such sequences from being included in the JWT secret.

**Comment by joshenlim** [comment]
@darora can i check real quick what are the illegal sequences we should be avoiding? can look into this

**Comment by darora** [comment]
That's a good question - @steve-chavez do you happen to know before I go digging?

Honestly it might be OK to just restrict to e.g. alphanumeric + a small set of special chars `-_` and call it a day?

**Comment by steve-chavez** [comment]
> Certain character sequences are treated as illegal by Postgrest (and possibly other services).

Hm, @darora why character sequences you found were illegal(also what was the error)? The only restrictions are the 32 chars minimum and if the string starts with `@`, postgREST will try to find an external file - which I guess could cause errors. 

Docs: https://postgrest.org/en/stable/configuration.html#jwt-secret

**Comment by darora** [comment]
Capturing off-thread conversation: let's disallow `$` and `@` characters in the JWT secrets.
@joshenlim anything else you need?

**Comment by joshenlim** [comment]
@darora okay gotcha so just min 32 chars and disallow `$` `@` characters yeah? Will update Terry's PR!

**Comment by darora** [comment]
Yup
