### ISSUE TITLE
Undefined response from updating row - but did update

### ISSUE THREAD

**Issue by jellohouse** [supabase/supabase#6813]
# Bug report

## Describe the bug

Out of the blue, when I do an update to a row, nothing is returned from Supabase API response (no data & no error).

## To Reproduce

```js
const { data, error } = await supabase
  .from('Submissions')
  .update({ other_column: 'otherValue' })
  .eq('some_column', 'someValue')
```
Both data & error are undefined.
However looking in the DB dashboard, the record did update as expected.

## Expected behavior
It should return an error if there was an error.
Or should return the replaced values for UPDATE. (which it does not for some reason)

## System information

- OS: [macOS]
- supabase npm: ^1.35.3

**Comment by aminamos** [comment]
Above `const { data, error } = await supabase` could you add `console.log(supabase) and confirm your url / API key are present in the object?

**Comment by jellohouse** [comment]
Ok just did `console.log(supabase)` - Yes I confirm the `supabaseUrl` and `supabaseKey` are present and correct.
---
Also please have a look at https://github.com/supabase/supabase/issues/6839 it seems to be related to this.

**Comment by steve-chavez** [comment]
@jellohouse Did you catch the http status of this error? If it's a 522 or 524 then #6839 is for sure linked.

If it's #6839, then what happened is that the db UPDATE succeeded but it took longer than the Cloudflare timeout.

If you have high UPDATE traffic, keep in mind that upgrading your instance memory will allow you to handle more UPDATEs per second. There are some numbers on https://github.com/supabase/benchmarks/issues/2#issuecomment-738870014.

**Comment by steve-chavez** [comment]
> Ok I found my error was somewhere else (unrelated).

Oh, could you elaborate on that? Would like to know in case another user runs into the same issue.

**Comment by jellohouse** [comment]
I didn't wanna say cause it's so embarrassing 😅

But ok - just a silly mistake I made... 
I wrote something like:
`const { responseData, responseError } = await supabase...`
instead of:
`const { data, error } = await supabase...`

Obviously the response object has `data` and `error` parameters, but not whatever else that I wrote..

**Comment by steve-chavez** [comment]
No worries, it happens ;). Thanks for sharing!

**Comment by jellohouse** [comment]
Close
