### ISSUE TITLE
Table editor: Default value of json is incorrectly formatted when editing the default value

### ISSUE THREAD

**Issue by jacktho** [supabase/supabase#6814]
# Bug report

## Describe the bug

The value of json or jsonb default value edit fields is broken. The resulting mutated json is not valid json.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Table editor' and create a new table
2. Add a new column named test with type json and a default value of { "test": "foo" }
3. Select "Edit table" for the newly created table
4. Note the default value for test in the edit field has been converted into a broken array

## Expected behavior

The default value should not change when editing.
## Screenshots

![image](https://user-images.githubusercontent.com/8503272/168150722-2f55f16d-2e3c-4ff6-a005-0f5a2045f603.png)
![image](https://user-images.githubusercontent.com/8503272/168150915-6eaa8649-d003-47a3-bc71-8cfb43da7c57.png)
![image](https://user-images.githubusercontent.com/8503272/168151638-c7f0cf5d-7513-4c6b-a54f-ef6b677c3c21.png)

## System information

- OS: Linux
- Browser (if applies): I tested in Brave and Firefox

**Comment by joshenlim** [comment]
hey there! this should be resolved by https://github.com/supabase/supabase/pull/6899 - we're planning to do a deployment on monday to get the fix out so hang tight :)

**Comment by joshenlim** [comment]
hey there @jacktho - the fix has been deployed to production, i'll go ahead to close this ticket first but feel free to reopen if its still happening!
