### ISSUE TITLE
UX bug: the theme icons are falsely display diverting from the UX flow

### ISSUE THREAD

**Issue by 1337-ishaan** [supabase/supabase#6815]
In light mode, the icon should display moon,
<img width="385" alt="Screenshot 2022-05-13 at 1 54 15 AM" src="https://user-images.githubusercontent.com/64636222/168161725-ccc9f7aa-9066-4e2c-bb5f-8ed5ce997e89.png">

In dark mode, the icon should display sun
<img width="368" alt="Screenshot 2022-05-13 at 1 54 24 AM" src="https://user-images.githubusercontent.com/64636222/168161746-d7c8a02d-3d1b-4be3-823f-3c60b4f34d98.png">

**Comment by 1337-ishaan** [comment]
I would like to work on this issue!

**Comment by joshenlim** [comment]
hey there @1337-ishaan! thanks so much for this report! However, I do think that this behaviour is correct - the icons should reflect the current theme at which the page is toggled for

**Comment by 1337-ishaan** [comment]
Depends, on person to person, but recently I created the same PR for @ethereum-org-website

https://ethereum.org/

So they also thought it should be the other way round, rest totally depends on you, however you feel like
