### ISSUE TITLE
npm/Yarn example tabs

### ISSUE THREAD

**Issue by Hallidayo** [supabase/supabase#6826]
# Improve documentation

## Describe the problem

I've noticed that on the quickstart examples their seems to be some guides that use npm and some that use yarn:

[npm example](https://supabase.com/docs/guides/with-nextjs#initialize-a-nextjs-app)
[Yarn example](https://supabase.com/docs/guides/with-expo#initialize-a-react-native-app)

I think that their should be a tabbed component in place where you can switch between viewing the npm command or yarn command on the examples where applicable. 

## Describe the improvement

I've done a example on my local branch which could look like the below:

https://user-images.githubusercontent.com/22655069/168262451-15d5e6c2-d081-4ef0-b3b9-90e004e56dcb.mov

## Additional context

If people think this will be a good improvement then I will add these tab components onto the example guides but first I want to get this approved. 

@kiwicopple @MildTomato

**Comment by Flowsmooth** [comment]
Yea
