### ISSUE TITLE
Secret missing in function

### ISSUE THREAD

**Issue by riderx** [supabase/supabase#6829]
# Bug report

## Describe the bug

When listing secret from cli the `SUPABASE_URL` default is missing
```
supabase secrets list   

  
              NAME            │              DIGEST
  ────────────────────────────┼───────────────────────────────────
    SUPABASE_SERVICE_ROLE_KEY │ ***
    SUPABASE_DB_URL           │ ***
    SUPABASE_ANON_KEY         │ ***

```

## To Reproduce

i have this issue only on one project not other so maybe check on mine `rjbponxxtdelwzdetefy`

## Expected behavior

All 4 default env var should be present.
Before reset the JTW the `SUPABASE_ANON_KEY` was also missing

**Comment by burggraf** [comment]
When you migrate to a new project, you will get new values for:
URL
ANON KEY
SERVICE KEY
JWT
These can be found in the Dashboard under Settings / API.

**Comment by burggraf** [comment]
Nothing changed on our side, no.  After moving to the new project, did you link your command line to the new project-ref?

**Comment by riderx** [comment]
@burggraf yes i did, and i was able to reproduce 2 times the issue with 2 project, i totally deleted one because the secret where missigns.

**Comment by burggraf** [comment]
Have you looked for the secrets in the dashboard under Settings, API?

**Comment by riderx** [comment]
@burggraf yes but that was not the issue, it was missing only on functions.
i try to reset the JWT from the dash board and then some came back but one was still missing that why i had to delete.
but anyway it's working now

**Comment by Akash187** [comment]
I am getting a similar issue on `supabase secrets list`. Only showing 2 keys. Getting error missing SUPABASE_URL.
supabase secrets list   
  
              NAME            │              DIGEST
    SUPABASE_SERVICE_ROLE_KEY │ ***
    SUPABASE_ANON_KEY         │ ***
