### ISSUE TITLE
Can't delete user from Users table

### ISSUE THREAD

**Issue by orisa** [supabase/supabase#6863]
### Discussed in https://github.com/supabase/supabase/discussions/6852

<div type='discussions-op-text'>

<sup>Originally posted by **orisa** May 16, 2022</sup>
Hi Supabase team. I've been trying to delete a user from the Authentication Users table. I used the "Delete user" button from the dropdown in the UI but I got the following error. 
<img width="375" alt="Screen Shot 2022-05-16 at 4 17 56 PM" src="https://user-images.githubusercontent.com/16691625/168630534-6d7d3cbb-128a-4bf2-a16d-8010d1f7a641.png">
 
I've checked the Postgres Logs but no error was logged there. How do I resolve this. Thanks</div>

**Comment by burmecia** [comment]
Hi @orisa, are you able to open developer console in browser and let us know if you can see any error logs? We just want to reproduce the issue, thanks.

**Comment by orisa** [comment]
@burmecia It seems to be a CORS error. A browser extension was blocking app.supabase.io. I've fixed it due to your suggestion. Thanks.
