### ISSUE TITLE
Placeholder text on input fields for dates don't have enough contrast 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#6886]
Happens anywhere in the table grid view, in dark mode. Need to up the contrast of that placeholder text.

<img width="311" alt="CleanShot 2022-05-19 at 06 51 50@2x" src="https://user-images.githubusercontent.com/105593/169260149-80b56986-ba84-414a-88a1-e3b1c0e90090.png">

**Comment by joshenlim** [comment]
this is an issue within the grid repo - supabase/grid
mentioned here https://github.com/supabase/grid/issues/138

i'll close this ticket as duplicate if that's alright
