### ISSUE TITLE
Table editor fails to load if the database is really huge

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#6900]
Tracking this issue here on Github publicly, this change will require some updates on the backend as well.

Mainly happening because the client is fetching all the table information at the pg-meta `/tables` endpoint,
which returns _every_ information about the table, including the columns etc, resulting in a really huge payload that either
1. takes a really long time to return, resulting in a timeout
2. payload is too huge to return

**Comment by joshenlim** [comment]
Shifting this to blocked as we this is dependent on pg-meta first reducing the amount of information being returned
need to eventually also be able to paginate this

**Comment by MildTomato** [comment]
Think this is solved now. @joshenlim just reopen if i got this wrong
