### ISSUE TITLE
Docs: Update dashboard images

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#6926]
# Improve documentation

## Link 

Not just this Link, This should be done through out the whole docs.
https://supabase.com/docs/guides/auth

## Describe the problem

Supabase dashboard in videos and images are outdated and need to be updated for better ease of use.

## Describe the improvement

Update the videos and images from the old dashboard to the new dashboard.

**Comment by dglitxh** [comment]
Can  I take this?

**Comment by Isaiah-Hamilton** [comment]
@dglitxh all yours. if you need any help just let me know.

**Comment by dglitxh** [comment]
@Isaiah-Hamilton so I basically have to update the media from the static file folder?

**Comment by Isaiah-Hamilton** [comment]
@dglitxh Yes

**Comment by dglitxh** [comment]
@Isaiah-Hamilton  #6987
