### ISSUE TITLE
Unable to login to supabase

### ISSUE THREAD

**Issue by jeromepui** [supabase/supabase#6951]
# Bug report

## Describe the bug

Unable to login to supabase with github

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Reproduced by logging in using github

## Expected behavior

Press "Sign in with GitHub"
Redirected and failed to login

## Screenshots

https://app.supabase.io/?error=server_error&error_description=failed+to+connect+to+%60host%3Dprod-2.c7y43uscdbtq.ap-southeast-1.rds.amazonaws.com+user%3Dauth_admin+database%3Dpostgres%60%3A+server+error+%28FATAL%3A+remaining+connection+slots+are+reserved+for+non-replication+superuser+and+rds_superuser+connections+%28SQLSTATE+53300%29%29

## System information

- OS: Windows
- Browser: Chrome

**Comment by bidlinj** [comment]
I'm also facing the same issue
