### ISSUE TITLE
Policies Editor goes out of the screen

### ISSUE THREAD

**Issue by alabhyajindal** [supabase/supabase#6954]
# Bug report

The policies editor under Auth -> New Policy -> For Full Customization goes out of the screen. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/52493077/169972746-c23e84f8-eb90-4fc9-8c35-555a997f03a1.png">

## To Reproduce

1. Click on 'the Authentication icon'
2. Click on 'New Policy'
3. Click on 'For Full Customization'

## Expected behavior

The size of the Policy Editor should be so that all the contents can be seen correctly. Or the scrollbar should allow user to navigate up and down.

## System information

- Windows 11
- Chrome 101

**Comment by MildTomato** [comment]
[fixing here](https://github.com/supabase/ui/commit/cdb5d3a8b94a9b4ca62076e92038234cf18dfa4a)
