### ISSUE TITLE
Foreign keys aren't saving because of default value

### ISSUE THREAD

**Issue by julienisbet** [supabase/supabase#6971]
# Bug report

## Describe the bug

When I try to add a new foreign key relation to a table using the UI, I'm getting an error `Invalid syntax for type bigint: ""` 
It looks like its defaulting to an empty string which is an invalid value for a foreign key. Its fine if I pick a random default value but it should be nullable. Using `NULL` as a default didn't work either.

## To Reproduce

0. Have at least one existing table
1. Add a new table and try to add a foreign key relation to your existing table -- leave the default value as empty
2. Save

## Expected behavior

You should be able to add a foreign key with a null default value

## Screenshots
<img width="518" alt="Screen Shot 2022-05-24 at 11 04 12 AM" src="https://user-images.githubusercontent.com/3282364/170103235-769dd8ee-b048-47b1-a24a-43495bb751b2.png">

<img width="765" alt="Screen Shot 2022-05-24 at 11 04 50 AM" src="https://user-images.githubusercontent.com/3282364/170103248-ae0b2de8-b076-41f5-8e4b-e118e0026a49.png">

## System information

- OS: macOS
- Browser: Brave
- Version of supabase-js: n/a
- Version of Node.js: n/a

## Additional context
This worked fine yesterday -- I'm teaching a class and it started causing problems for students who were making their tables today.

**Comment by DillonB07** [comment]
This happened to me as well! This really needs to be fixed. I'm using macOS Catalina in Firefox if it makes a difference.

**Comment by anthonyko** [comment]
Having a similar issue, but I am just adding a new column to a table and a not foreign key. Seems the "Allow Nullable" option is being ignored. I can add a new column to my table if the default value is not empty.

<img width="618" alt="CleanShot 2022-05-24 at 12 20 05@2x" src="https://user-images.githubusercontent.com/4150464/170115496-a903eae5-03aa-4c6c-99a4-c922ba25fcd2.png">

OS: macOS
Browser: Edge

**Comment by joshenlim** [comment]
hey all! all be taking a look at this today - hang tight

**Comment by lukaskf** [comment]
I had this same issue, decided to give the SQL Queries a try. It worked!

This is a nice resource I found to help build queries: https://supabase-sql.vercel.app/

**Comment by joshenlim** [comment]
hey all! the fix should now be up - apologies once again for this disruption 🙏

**Comment by julienisbet** [comment]
thanks for the quick turnaround @joshenlim!

**Comment by richard457** [comment]
We are getting this issue once again
{
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for type uuid: \"\""
} the biggest issues is also hint and details are always null

**Comment by alaister** [comment]
Hi @richard457,

Can I check where you're seeing this error? Is it in our table editor or your application?

Any extra info you can provide such as screenshots or code snippets would be helpful with debugging.
