### ISSUE TITLE
Redirect user after auth to native app

### ISSUE THREAD

**Issue by OceanTechnic** [supabase/supabase#6972]
# Bug report

## Describe the bug

When user is trying to login with Spotify,
Supabase will automatically redirect user to desired URL,
Which is auth.example.com on this page client sided js will try to find if user is on IOS or web,
If user is using IOS We will redirect him to `myApp://#access_token..` else `https://example.com#access_token..`
But Supabase client will not detect this `myApp://#access_token..` and the auth will fail

## To Reproduce
1. Create simple HTML page with "Routing" js which will force IOS users to open the app with `window.location.hash`
2. Try to login from IOS App
3. The hash inside the url will not work

## Expected behavior
Supabasejs on IOS when using capacitorjs will fail auth.

## System information
- OS: IOS / MacOS
- Capacitorjs / Angular
- Version of supabase-js: ^1.35.3
- Version of Node.js: v16.15.0

**Comment by OceanTechnic** [comment]
Btw It was mentioned here: https://github.com/supabase/supabase/discussions/5793

**Comment by kiwicopple** [comment]
Hey @OceanTechnic - you just need to explicitly add the redirect as a parameter in the API call. In the JS client it would be like this: https://supabase.com/docs/reference/javascript/auth-signin#sign-in-with-redirect

```js
const { user, session, error } = await supabase.auth.signIn({
  provider: 'github'
}, {
  redirectTo: 'https://example.com/welcome'
})
```
