### ISSUE TITLE
Docker Compose, DB is not ready?

### ISSUE THREAD

**Issue by azukaar** [supabase/supabase#6975]
# Bug report

## Describe the bug

When I start the docker-compose, I get a whole bunch of error because of a fail migration. It seems in particular to stop there (see full log here : https://pastebin.com/CMQGV2pU): 

```
"running db migrations: Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to `host=db user=postgres database=postgres`: dial error (dial tcp 172.21.0.3:5432: connect: connection refused)"
```

And then the rest of the log (https://pastebin.com/CMQGV2pU) is just a bunch of failling migrations.

## To Reproduce

 * clone the repo and extracted the docker folder
 * docker compose up

## System information

- OS: Windows 10
- Docker 4.7.1 

## Additional context

I tried cleaning up my docker space with `docker rm -f (docker ps -a -q)` and `docker volume rm (docker volume ls -q)` but not helping

**Comment by jjromary** [comment]
Hi, @azukaar. Yesterday I came across an error similar to this. Have you started Docker on your Windows?

**Comment by azukaar** [comment]
Yes I am using Docker for windows as the server on windows 10

**Comment by J0** [comment]
Hey @azukaar,

Can I check if the issue still persists? Just attempted to replicate but wasn't too successful -- that said I'm on a Mac though.

Let me know!
Joel

**Comment by J0** [comment]
Hey all,

Going to close this for now since it seems like the issue has gone stale but feel free to re-open if it is still troubling you.

Thanks!
Joel
