### ISSUE TITLE
Update company page

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#6977]
# Chore

## Describe the chore

https://supabase.com/company

This page says that we have raised $36M:

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/10214025/170153959-1966e373-5856-48e7-9ef0-e86e37aab549.png">

We need to :

- [ ] Update the number to $116 M
- [ ] Add Felicis to the logos

**Comment by jjromary** [comment]
can i get this issue?

**Comment by w3b6x9** [comment]
@jjromary sure, take it away!

@kiwicopple does it matter where Felicis' logo appears?

**Comment by jjromary** [comment]
@w3b6x9 Do you know the directory of this page? I'm having trouble finding it

**Comment by w3b6x9** [comment]
> @w3b6x9 Do you know the directory of this page? I'm having trouble finding it

@jjromary nice, looks like you found it.

**Comment by w3b6x9** [comment]
> @kiwicopple, can you explain this point in more detail?
> 
> * [ ]   Add Felicis to the logos

@jjromary I think this has already been done and is currently up on `master`: https://github.com/supabase/supabase/pull/6878

**Comment by Anikets08** [comment]
Hey is this issue fixed

**Comment by w3b6x9** [comment]
I'm only aware of this closed PR (https://github.com/supabase/supabase/pull/6981) so I don't think this has been resolved yet.

@jjromary are you still working on this or should I give this to someone else?

**Comment by rohandebsarkar** [comment]
@w3b6x9, I opened a PR #7081 to resolve this.

**Comment by w3b6x9** [comment]
@rohandebsarkar nice, thanks!
