### ISSUE TITLE
Can't Scroll When Editing the Column Types in Development Environment

### ISSUE THREAD

**Issue by ARMATAV** [supabase/supabase#6988]
# Bug report

## Describe the bug

I might be crazy, but you cannot scroll vertically in this box. You can mouse close to the upper and lower edges and it will glitchy-scroll a little, but otherwise I should be able to scroll with my trackpad.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `http://localhost:54323/`
2. Click on any table
3. Edit a column type
4. Attempt to scroll

## Expected behavior

It scrolls up and down

## Screenshots

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/2433203/170185289-d09caa50-1582-40c4-ba29-b405275cc84c.png">

## System information

- OS: macOS
- Browser (if applies) Chrome
- Version of supabase CLI: 0.26.0

**Comment by ARMATAV** [comment]
What can I say bro; I'm on a mac on Chrome - maybe that's it, maybe it's not. All I know is it's a fresh install.

**Comment by saltcod** [comment]
Hey @ARMATAV !  Thanks for this report. We pushed out a fix for this last week. Could you confirm that it's fixed for you as well? If not, please let us know and we'll dig into it again!

**Comment by ARMATAV** [comment]
> Hey @ARMATAV ! Thanks for this report. We pushed out a fix for this last week. Could you confirm that it's fixed for you as well? If not, please let us know and we'll dig into it again!

Hm - the upgrade path here is to re-run `supabase start` or `brew upgrade supabase`?

**Comment by saltcod** [comment]
You'd just need to pull the latest changes from master inside supabase/supabase/studio.  @ARMATAV

**Comment by joshenlim** [comment]
Hey all! I'm gonna close this issue for now as the fix for this has been out for awhile, but anyone who might be facing this issue still please feel free to reopen this ticket! Will be glad to help out wherever we can 🙏
