### ISSUE TITLE
Tables in new database not reflected on Supabase

### ISSUE THREAD

**Issue by thepandaguitar** [supabase/supabase#701]
Hi,

I am connected to the postgres db using TablePlus, I create a new DB in addition to postgres/template0/template1. However, the tables are not reflected on the Supabase dashboard.

- Does Supabase dashboard/features only work on the postgres db?
- Is there a way to point Supabase to a new DB?

**Comment by kiwicopple** [comment]
Hey @thepandaguitar,

I assume that you created an entirely new database other than the default `postgres` database (eg, inside the cluster we have provided you)? 

In this case it's not supported (yet) - we still are building features for a single database. The best way to support multiple databases right now is to create multiple projects.

Would love to know your use-case? If it's applicable to the rest of our users we can add it to the priority list (you're the first who has asked for this so far).

**Comment by kiwicopple** [comment]
Hey @thepandaguitar - I'll close this one for now, but feel free to reopen if i didn't answer your question or start a Discussion:

https://github.com/supabase/supabase/discussions
