### ISSUE TITLE
Edge function deploy failed after delete once

### ISSUE THREAD

**Issue by y0zong** [supabase/supabase#7027]
# Bug report

## Describe the bug

edge function can't be deploy

## To Reproduce

I can't find the way to update a `Published function` so I delete it and re-deploy it, after this I can't deploy any function any more, always failed with `Error: exit status 1` 

1. supabase functions new some_fn
2. supabase functions deploy some_fn
3. supabase functions delete some_fn
4. supabase functions new some_fn2
5. supabase functions deploy some_fn2
6. `Error: exit status 1`

## Screenshots

<img width="397" alt="Screen Shot 2022-05-27 at 12 41 17" src="https://user-images.githubusercontent.com/86962713/170630333-5dc07e7a-5059-4f18-bcda-bc0d499acccc.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by aar2dee2** [comment]
Can you share the database logs for this?
Here's how to access them:

https://user-images.githubusercontent.com/85004512/170977585-5682e295-35e1-4899-a676-cd1995a0426a.mov


Note: If you're not using Supabase pro, database logs are deleted after 24 hours. You will need to rerun the function deployment to reproduce the error.

**Comment by y0zong** [comment]
sorry logs is gone, but just use **cURL** to deploy my functions it seems to work, it maybe `supabase-cli` bug not `supabase`, I close this issue.

**Comment by BrunoIshikawa** [comment]
Hi, I think I might be having the same bug but can't find anything relevant on the logs

**Comment by aar2dee2** [comment]
Can you share the error message and which action throws the error?

**Comment by paulogomes** [comment]
I had the same error and fix that just deleting the ~/.supabase folder. Probably is a cache issue
