### ISSUE TITLE
Enable public slack integration on https://status.subabase.com

### ISSUE THREAD

**Issue by kav** [supabase/supabase#7035]
I have a low pri but easy "feature" request . Can someone at Supabase who has access to the Atlassian Statuspage configuration for https://status.supabase.com/ enable the public slack integration so we can subscribe to it? https://community.atlassian.com/t5/Statuspage-articles/New-feature-Slack-notifications-for-Statuspage/ba-p/1510473

**Comment by liaujianjie** [comment]
Enabling subscription via emails would be great too!

**Comment by kav** [comment]
Thanks so much for taking care of that @kiwicopple ! Any chance you could just check the slack and sounds like maybe email box as well? Seems like that should just be checking some boxes per https://support.atlassian.com/statuspage/docs/enable-slack-subscriptions/ No real reason to jump through the RSS hoop when it's already built into the platform unless you all have a blocker that prevents that.

**Comment by kav** [comment]
@kiwicopple any chance you can check the additional boxes? I'm down the integrate rss if needed but they are built in so it feels a bit silly

**Comment by kiwicopple** [comment]
we're on the hobby tier @kav - so we don't have the slack option

**Comment by kav** [comment]
Ha got it. No worries at all then. We all know how that goes ;)

**Comment by gprieto** [comment]
Reviving this issue, with the current outage - this has become a clear need for companies like ours relying on Supabase as an infrastructure backbone.
