### ISSUE TITLE
Improve docs around backups

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#7044]
We don't have a backups section, would be good to create a dedicated section with reference to:
- how often Supabase takes backups on the platform
- how these can be restored
- how to take your own backups using pg_dump / pg_restore
- what is PITR and how to get it on the platform
- etc.

**Comment by cmantsch** [comment]
Does supabase actually create backups automatically? Always thought you need to take care of that yourself.

Still a +1 from me, Backup and Disaster recovery is something that is really needed to be well documented, especially since there are so many schemas in the db

**Comment by burmecia** [comment]
We already have dedicated backup sections in docs: https://supabase.com/docs/guides/platform/backups.
