### ISSUE TITLE
Write docs for connecting via SSL

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#7046]
you can connect to your postgres instance by downloading the SSL cert from the dashboard, we should add a guide for this.

**Comment by kiwicopple** [comment]
> add a guide

let's just update this guide to include the instructions: 
https://supabase.com/docs/guides/database/connecting-to-postgres

**Comment by Sonichigo** [comment]
Can I take this up?

**Comment by kutovoy** [comment]
I wonder if this is relevant but project settings are not available in local docker installation so obtaining ssl certificate is still an issue

**Comment by OmarVector** [comment]
Actually, I'm stuck in that stage, I cannot issue SSL to docker image , I'm self hosted supabase and exposed it using No-IP and everything working just fine, generating SSL to the domain, still cant make the docker image replicate the changes
