### ISSUE TITLE
docs: heading spacing is off

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#7056]
# Bug report

## Describe the bug

The spacing in the heading is a bit off:

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/10214025/170972082-0fbb8126-c988-4adc-a161-8ab6bc989b3c.png">

<img width="1161" alt="Screenshot 2022-05-30 at 8 22 00 PM" src="https://user-images.githubusercontent.com/10214025/170972703-c4616a11-3293-4da8-9cf7-d2a39ab33bd4.png">

I think it could be due to a dependency upgrade here: https://github.com/supabase/supabase/pull/7049. Possibly the navbar image is bigger than it was previously?

**Comment by MildTomato** [comment]
also an issue with mobile, fixing in same PR

<img width="561" alt="Screenshot 2022-05-31 at 4 57 24 PM" src="https://user-images.githubusercontent.com/8291514/171134830-6bdd5eea-3885-4e99-aecb-f33c31f8000e.png">
