### ISSUE TITLE
Auth users table should show the same amount of information irregardless of viewport width

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#7058]
At the moment we show more and more information as the viewport width gets larger but as suggested by a community member we could just have a table that's scrollable instead

**Comment by MildTomato** [comment]
been refactoring Table component recently in Auth users view, which should fix this issue.
not sure about the scrollable content though since it will render the 'action dropdown' a bit useless as it'll be off screen, but I'll see what we can do.

**Comment by saltcod** [comment]
Addressed. Closing.
