### ISSUE TITLE
Auth providers randomly redirect to "Additional redirects URL" or "Site URL"

### ISSUE THREAD

**Issue by Jaarson** [supabase/supabase#7087]
# Bug report

## Describe the bug

Auth provider (only tested with Google) randomly redirects to "Additional redirects URL" or "Site URL" (which are set up in Dashboard under Authentication/Settings)

## To Reproduce

1. Set up Google as auth provider
2. Set different URLs for "Additional redirects URL" or "Site URL" 
3. Signup with Google

## Expected behavior

Always redirect to "Additional redirects URL"
The wording "Additional" is a bit confusing as there is no primary or main redirect URL field

**Comment by Jaarson** [comment]
Yes, "multi-redirects URL" sounds better, although I don't fully understand the use case for having multiple and not one URL. Are you able to explain it?

**Comment by kiwicopple** [comment]
This sounds more like a docs issue.

>  I don't fully understand the use case for having multiple

The use-case is to ensure that your Auth server isn't being used as a "man in the middle" for bad-actors. You can specifiy the URLs which are "allowed" to use your auth service, and they you can specify the redirect when the user signs in:

https://supabase.com/docs/reference/javascript/auth-signin#sign-in-with-redirect

**Comment by silentworks** [comment]
I'm wondering if this would be better if it was called **Allowed URLs** since they are used as an allowed list?

**Comment by J0** [comment]
Hey all,

We've had a revamp on our dashboard which should hopefully make the difference between Site URL and Redirect URL clearer. Going to close this issue for now but feel free to re-open if it is still unclear.

cc: @MildTomato
