### ISSUE TITLE
Bug: Storage background not fully getting dark

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#7090]
# Bug report

## Describe the bug

The storage navbar doesn't get with the rest of the background when deleting a bucket.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `Dashboard`
2. Go to `Storage`
3. Click on `delete bucket`
4. See bug

## Expected behavior

For the storage navbar to also get darker with the rest of the background.

## Screenshots

https://user-images.githubusercontent.com/70828596/171269980-ea0745a4-8c0c-4961-8763-dd33adc62b85.mp4

## System information

- OS: macOS 12.4
- Browser: Firefox, Safari, Chrome
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by tulusibrahim** [comment]
Hey, can I work on this one?

**Comment by saltcod** [comment]
Hey @tulusibrahim that would be awesome! Much appreciated. Let us know if you need any help on our end!

**Comment by tulusibrahim** [comment]
Hi, Im trying to run the project on my local machine but the project keeps give me loading screen like this
![image](https://user-images.githubusercontent.com/70683601/171974393-cfa396ed-6f79-43e0-a2f1-eca7cf553af4.png)

In the console I keep getting error:

Failed to load resource: net::ERR_CONNECTION_REFUSED
or
HEAD http://localhost:8000/rest/v1/ net::ERR_CONNECTION_REFUSED

I already followed the step in developers.md such as:

1. Fork the project
2. Clone the project
3. cd supabase
4. cd studio
5. run npm install
6. run npm run dev

My machine is on:
Node: 16.15.1
Npm: 8.12.1
Git installed

Is there any step I missed?

**Comment by Isaiah-Hamilton** [comment]
@tulusibrahim you need to run docker. Follow these steps https://supabase.com/docs/guides/hosting/docker
