### ISSUE TITLE
I can't create an access token for supabase cli.

### ISSUE THREAD

**Issue by dutsik** [supabase/supabase#7124]
### Discussed in https://github.com/supabase/supabase/discussions/7123

<div type='discussions-op-text'>

<sup>Originally posted by **dutsik** June  2, 2022</sup>
Hello. 

On page https://app.supabase.com/account/tokens when i enter a token name in "generate token" popup and click "geenrate token" i receive an error: "Failed to create token: Unauthorized"

What am i missing?

Thanks.
</div>

**Comment by dutsik** [comment]
I also cannot submit a support ticket. Receive 'Unauthorized" response too.

**Comment by saltcod** [comment]
That's weird @dutsik!    Was your token expired maybe? Have you tried logging out and back in and retrying?

**Comment by dutsik** [comment]
@saltcod  For some unknown reason after several hours i tried it once again. and it did worked as expected. I believe there was an issue with supabase dashboard or one of underlying services.

I am closing the issue.
