### ISSUE TITLE
Issue with rendering JSON data in grid FK modal

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#7148]
# Bug report

## Describe the bug

Example: Happens when you click on the "External Link" icon on the record_id column here:
![image](https://user-images.githubusercontent.com/19742402/158565624-e5f07fa5-2a17-4795-a851-9a1003e79e45.png)

This is the corresponding row - seems to have issues rendering something like `{ p: 0.62, si: 2108....}`
![image](https://user-images.githubusercontent.com/19742402/158565727-7a43d003-2cb6-445f-8c6d-8473d9bdd362.png)

**Comment by jjromary** [comment]
@joshenlim How can I manage to reproduce this bug? How can I insert this external link in the column header?

**Comment by joshenlim** [comment]
hey there @jjromary! apologies for lack of details on this ticket - i'm trying to reproduce this issue but can no longer do so, might have been fixed in one of our previous commits. I'm gonna close this ticket for now unless anyone else runs into this issue 🙏
