### ISSUE TITLE
hyperlink from supacell

### ISSUE THREAD

**Issue by johndpope** [supabase/supabase#7152]
# Feature request

## Is your feature request related to a problem? Please describe.
is it possible to do this? 

## Describe the solution you'd like
I want to click a link from inside a cell - or somehow link to stuff.....

## Additional context

I have a list of stocks - GOOG - I want to give user option to navigate to webpage by clicking inside the cell.

THIS hyperlink icon would be perfect - how to do this using bespoke data?

![Screen Shot 2022-01-06 at 16 37 43](https://user-images.githubusercontent.com/289994/148334105-17b326a7-2940-47e2-942c-78f016f7887b.png)

**Comment by saltcod** [comment]
Hi there — thanks for the idea on this one. And sorry for the delay. 

Discussed this one internally and while we think it would be great for this use case, it's entering into an area of customization that we're not ready to move forward with in this area.

Thanks again — appreciate the suggestion!
