### ISSUE TITLE
Display timestamp microseconds in UI

### ISSUE THREAD

**Issue by AJamesPhillips** [supabase/supabase#7154]
# Feature request

## Is your feature request related to a problem? Please describe.

I was trying to match an exact timestamp value and [was confused for quite some time](https://stackoverflow.com/questions/69354017/match-potsgresql-timestamptz-by-exact-value) until I realised timestamps are being stored with microsecond precision but that this is not reflected in the UI.

## Describe the solution you'd like

I appreciate Javascript's native Date object does not contain microseconds so I'm not sure what the best approach is.  Either a warning, or perhaps rendering ??? in place of the microseconds like: 2021-09-27T20:55:25.625 ***???*** Z

## Describe alternatives you've considered

n/a

## Additional context

```sql
CREATE TABLE IF NOT EXISTS knowledge_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  modified_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

SELECT modified_at as original, cast(extract(epoch from modified_at) * 1000000 as bigint) FROM knowledge_views;
```

The default representation does not hint that there are microseconds.  In this case 535 microseconds.

![image](https://user-images.githubusercontent.com/526509/135043219-2d5cc793-7dae-4a82-b841-b708d00ff0b0.png)

** edit **

I think this is more related to data types in PostgreSQL but if you just extract an epoch without the cast then the value displayed in the UI also loses precision:

```sql
SELECT
  modified_at,
  extract(epoch from modified_at),
  extract(epoch from modified_at) * 1000000 as d_1000000,
  cast(extract(epoch from modified_at) * 1000000 as bigint) as d_bigint
FROM knowledge_views;
```
![image](https://user-images.githubusercontent.com/526509/135050036-9835dc3b-e9ad-46eb-a218-02a34b24a84c.png)

**Comment by joshenlim** [comment]
hey there @AJamesPhillips - sorry getting back on this super late! but can I check real quick regarding this issue, did you face the difficulty in the table editor? im guessing through the filters?

**Comment by AJamesPhillips** [comment]
Hey @joshenlim , yes I was trying to filter a table to a specific value.  But the representation in the table is not what's actually in the DB.  So you can copy a value verbatim from the table and try to match it exactly and it won't work (because there is a 999/1000 chance that the microseconds is not 000).

**Comment by joshenlim** [comment]
ahh okay gotcha on this - just to check though, the table editor should be able to display the exact timestamp value as such, we currently don't do any specific JS formatting for the data that's shown in the grid. I'm also able to filter down to the microsecond level here - wondering if i might be missing anything?

https://user-images.githubusercontent.com/19742402/193214660-a94abc33-c983-4459-822d-5d996fa9af97.mov

If you don't mind, could you perhaps share a recording of what you're trying to do so I can get a clearer picture of what needs to be fixed here 🙏

**Comment by AJamesPhillips** [comment]
Right, I haven't checked it in a while but looks like microseconds are now displayed in the frontend, so will close.  Thanks!

<img width="938" alt="image" src="https://user-images.githubusercontent.com/526509/193264109-529ff5d2-e321-45a7-8282-266976957ec6.png">

As an aside for anyone else, I found it useful for my javascript code (in the front end) which doesn't natively support microsecond precision to drop the microseconds on table creation using:

```sql
CREATE TABLE IF NOT EXISTS debugging_timestamps (
  -- limit timestamp to 3 decimal places to accommodate javascript Date object that lacks microseconds
  timestamp_no_micro timestamp(3) without time zone DEFAULT now() NOT NULL
);
```
