### ISSUE TITLE
Generated tsvector breaks table editor

### ISSUE THREAD

**Issue by saendu** [supabase/supabase#7155]
# Bug report

## Describe the bug

Creating a generated column of type tsvector breaks insert row of table editor on https://app.supabase.io/. 

## To Reproduce

1. Create table
2. Create a generated column like so:
```
ALTER TABLE tablename
    ADD COLUMN fts tsvector
               GENERATED ALWAYS AS (to_tsvector('english', "columnname")) STORED;
```
3. Go to table editor on https://app.supabase.io/ and try to insert new row.
4. Error message: ``cannot insert into column "fts"``

Table editor shows: ``to_tsvector('english'::regconfig, fts)`` as default value. Removing it results in same error message as above. 

## Expected behavior 

No default value is show in tsvecor generated column. 
Insert works leaving column fts empty.

## System information

- OS: macOS
- Browser: Chrome

**Comment by kiwicopple** [comment]
(Note to FE team): This is now fixed in pg-meta, so we just need to make the relevant changes to the Grid to solve this

**Comment by burmecia** [comment]
This issue has been fixed.
