### ISSUE TITLE
Feat: be able to add new row 

### ISSUE THREAD

**Issue by phamhieu** [supabase/supabase#7157]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the grid only supports a callback to trigger add new row feature (mainly for Supabase dashboard).
It will be great if we can support an UI to add new row directly from this library. 

## Describe the solution you'd like

Add new row UI needs to support:
- detect for required/optional fields
- support different field types: json, foreignkey, date, time... (can we re-use the grid editors?)
- should be in a modal view (mainly because of pagination, we can't just add a new row at the bottom)

**Comment by saltcod** [comment]
@phamhieu is this one still relevant?

**Comment by joshenlim** [comment]
closing this one as no longer relevant

we've moved the grid library to within studio as its scoped to the requirements of studio
