### ISSUE TITLE
docs: update text and vidoe on `Finding the connection pool config`

### ISSUE THREAD

**Issue by burmecia** [supabase/supabase#7172]
# Improve documentation

## Link 

[Finding the connection pool config](https://supabase.com/docs/guides/database/connecting-to-postgres#finding-the-connection-pool-config)

## Describe the problem

The description and video on 'Finding the connection pool config' is outdated with latest dashboard UI.

## Describe the improvement

The connection pool config is now at `https://app.supabase.com/project/_/settings/database`, the text and video needs to be updated.

## Additional context

N/A

**Comment by jjromary** [comment]
can i take this issue?

**Comment by burmecia** [comment]
sure you can, thank you @jjromary !

**Comment by jjromary** [comment]
The code is undergoing review and soon the PR will be done
