### ISSUE TITLE
two "all" tags on the blog

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#7182]
in https://supabase.com/blog

![image](https://user-images.githubusercontent.com/458736/172166038-12f7f1dc-a15c-457f-846f-b30561843209.png)

not sure where it's coming from

**Comment by jjromary** [comment]
Can I take over this issue?

**Comment by Isaiah-Hamilton** [comment]
@awalias are you talking about production or locally because I don't see duplicate `all` tags in production. But I do know that when running locally and the site hot refreshes, it makes duplicate `all` tags. If that's what you are talking about?

**Comment by awalias** [comment]
ahh maybe I was not on the prod site, closing thanks!
