### ISSUE TITLE
Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.

### ISSUE THREAD

**Issue by jjromary** [supabase/supabase#7184]
# Bug report

When I try to load the data that is in my table, I get this error message "Error: Too many re-renders. React limits the number of renders to prevent an infinite loop." This is happening after the Grid is inserted into the Supabase project.

* Data was entered through the Supabase Studio interface
![image](https://user-images.githubusercontent.com/37199044/172243784-e933f20c-5378-447f-be69-8461e1f35b98.png)

**Comment by saltcod** [comment]
Hey @jjromary thanks for the report.  

How were you loading data into the table? What did the table look like? What did the file you were importing look like? Any details to help us reproduce this one would be great. 

Thanks!

**Comment by jjromary** [comment]
Sorry, really missing details that I forgot to mention.

1. First I access the subase/docker directory and run the command docker-compose up.
2. Access the supase/studio directory and run npm run dev.
3. Access my default project and enter the Table session.
4. I create the table with any name and insert test data through the studio's own graphical interface.

At this point the error occurs.

**Comment by saltcod** [comment]
Humm that's weird! Did you run `npm install` in /studio/ after this change?

**Comment by jjromary** [comment]
I'm not really sure, but I can run npm install. A doubt, do I pass the command in the /supbase or subase/studio folder?

**Comment by jjromary** [comment]
Yes, I did. The terminal displayed an error that the package was missing in lottie-react. I did the installation, but the error persisted....

**Comment by jjromary** [comment]
Managed to solve this problem. A block of my code was responsible for this infinite loop. I refactored that code block and the error stopped occurring.
