### ISSUE TITLE
Row with non nullable integer cannot be saved if 0 is set as value

### ISSUE THREAD

**Issue by chrichrichri** [supabase/supabase#7185]
# Bug report

## Describe the bug

A row cannot be modified if a non-nullable Integer is set to 0 (zero).

## To Reproduce

1) Create any table with a non-nullable integer column
2) Create a valid row in this table. Important: Non-nullable integer value has to be set to 0 (zero)
3) Edit this row by with right-click + "Edit Row"
4) Do not change anything simply go to 5
5) Click "Save"
--> Error "Please assign a value for this field" is shown

## Expected behavior

Value 0 should be accepted.

## System information

- OS: tested on Mac + Ubuntu
- Browser: Safari + Firefox + Chrome
- Version of supabase-js: No idea- current hosted version by supabase
- Version of Node.js: No idea- current hosted version by supabase

**Comment by udasitharani** [comment]
I would like to work on this one.
