### ISSUE TITLE
Cannot create a Supabase Postgres DigitalOcean Droplet following the official documentation

### ISSUE THREAD

**Issue by subwaymatch** [supabase/supabase#7189]
# Bug report

## Describe the bug

A Supabase Droplet using the [Supbase Postgres Hosting](https://marketplace.digitalocean.com/apps/supabase-postgres) image on DigitalOcean Marketplace cannot be created. The image does not show up.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [https://supabase.com/docs/postgres/server/digitalocean](https://supabase.com/docs/postgres/server/digitalocean) and click on the "listing" link.

![image](https://user-images.githubusercontent.com/1064036/172290536-323df074-ba25-4a5b-ae17-5c7686caf04a.png)

2. Click on the "Create Supabase Droplet" button.

![image](https://user-images.githubusercontent.com/1064036/172290617-9353deeb-f0ef-48c7-96f7-a957533a69e6.png)

3. This takes you to the "Create Droplets" page. However, the Supabase Postgres image is NOT selected.

![image](https://user-images.githubusercontent.com/1064036/172290913-5a6c7700-930a-4990-834b-4f49f4865f6d.png)

4. Trying to find the "Supabase Postgres Hosting" image manually in the marketplace won't work. Searching for "Supabase" only shows "Supabase Realtime", NOT "Supabase Postgres Hosting".

![image](https://user-images.githubusercontent.com/1064036/172291076-3d7d0825-d0f4-4f59-ae0a-969e8169202d.png)

Here is also another similar report from another user on Discord.

![image](https://user-images.githubusercontent.com/1064036/172291446-9f748a97-22c7-4e0e-b88a-22d29896e9a3.png)

## Expected behavior

When clicking on the "Create Supabase Postgres Droplet", a valid image should be selected.

As an example, clicking on the [Wordpress 1-Click Droplet Link](https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=92582848&image=wordpress-20-04&activation_redirect=%2Fdroplets%2Fnew%3FappId%3D92582848%26image%3Dwordpress-20-04) on [https://marketplace.digitalocean.com/](https://marketplace.digitalocean.com/) will successfully take a user to the "Create Droplets" page with a valid "Wordpress on Ubuntu" image.

![image](https://user-images.githubusercontent.com/1064036/172291635-53e75e54-0306-44ed-91c8-cba3e64d341a.png)

![image](https://user-images.githubusercontent.com/1064036/172291828-489445cb-3598-478b-807b-25d00751ab85.png)

## System information

- OS: Windows
- Browser (if applies) Chrome Version 102.0.5005.63
- Version of supabase-js:
![image](https://user-images.githubusercontent.com/1064036/172291976-44c3df02-1185-464c-8ff5-276f8fdcd2c5.png)
- Version of Node.js: N/A

## Additional context

I tried to create a Postgres Droplet about a month ago and experienced the same issue. I thought it was a temporary version issue and thought the image would be updated at some point.

Thank you for a great product!

**Comment by burmecia** [comment]
This issue is also related https://github.com/supabase/postgres/issues/200

**Comment by subwaymatch** [comment]
Thank you for the update @dragarcia! I will use the Docker setup.

Park

**Comment by ctwhome** [comment]
Hi @dragarcia please improve the self host docuemntation because it is still very difficult to follow. It seems like using the CLI eject doesn't include supabase studio, but if you download the supabase repo and run the docker-compose then yes... It seems to me like inconsistencies about self-hosting everywhere.
