### ISSUE TITLE
Add functions to README

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#7218]
three bits to update in the README:

- the main diagram is missing functions API
- the list below is missing functions
- the client library grid is missing functions-js and equivalents (maybe there's more to update?) see: https://github.com/supabase-community/#client-libraries

![image](https://user-images.githubusercontent.com/458736/172605839-2a74075f-b1ff-4682-bb95-5417b8ec73ed.png)

**Comment by J0** [comment]
Oh yup we have [Functions-py](https://github.com/J0/functions-py) but I'd like to test it and refactor some portions first before transferring over.  Should be able to do it on one of the evenings or weekends but ping me if it's needed earlier.

**Comment by J0** [comment]
Just transferred [functions-py](https://github.com/supabase-community/functions-py)

**Comment by Isaiah-Hamilton** [comment]
@awalias do we have the original image source file? would be a lot easier to add if we do, also fine if we don't.

**Comment by kiwicopple** [comment]
I have it @Isaiah-Hamilton - it's in Excalidraw.
