### ISSUE TITLE
Overlapping backer images on supabase website

### ISSUE THREAD

**Issue by noahsb** [supabase/supabase#722]
# Bug report

## Describe the bug

On the homepage of the supabase website, the images of backers overlap on mobile views (see below for screenshots)

## To Reproduce

1. Go to https://supabase.io/ on a mobile device
2. Scroll down to 'backed by'
3. See backer images overlapping

## Expected behavior

Backer images to be displayed side-by-side as seen in desktop view

## Screenshots

Desktop view:
![image](https://user-images.githubusercontent.com/49932437/107978298-25783a80-6f82-11eb-8e9c-92855e48e2e9.png)
Mobile view:
![image](https://user-images.githubusercontent.com/49932437/107978358-3fb21880-6f82-11eb-949d-8e45a62b6d75.png)

## System information

- OS: Windows
- Browser: chrome

## Additional context

I'd be happy to submit a PR to address this issue. While I recognize it's a very minor issue, I want to ensure all users have a great experience with supabase.

**Comment by kiwicopple** [comment]
Hey @noahsb - good catch, I just added the Coatue image yesterday and forgot to check Coatue. I have commented out the image now

> I'd be happy to submit a PR to address this issue.

That would be amazing 🙏

**Comment by noahsb** [comment]
This issue has been resolved via above so I'll close this. Thank you both for the feedback :fire: @MildTomato @kiwicopple
