### ISSUE TITLE
onAuthStateChange (SIGNED_IN event) Fired everytime I change Chrome Tab or refocus on tab .

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#7250]
**Whenever i focus to another tab (Chrome) and come back to supabase application tab , onAuthStateChange  fires SIGN_IN event.**
Even though i am already signed in , whenever i refocus on supabase application tab, again SIGN_IN event is fired.
I am using following version
```
 "next": "^12.1.6",
 "react": "^18.1.0",
"@supabase/supabase-js": "^1.35.3",
```

**--- This causes me to navigate to landing page each time i focus on tab.**

Also it should be noted that two days ago this was working alright. This started only when i started `route `Api. 
But Now even though i removed all `route `, still this is happening.

**Comment by GaryAustin1** [comment]
This is do to a recent change in token refreshing.  I assume you are pulling latest gotrue.js code now, versus older version before.

https://github.com/supabase/gotrue-js/pull/274#issuecomment-1105207806

**Comment by roker15** [comment]
> . I assume you are pulling latest gotrue.js code now,

How to pull latest gotrue? My project has supabase dependency and i am using latest supabase.

**Comment by GaryAustin1** [comment]
The latest supabase-js has the latest gotrue-js in it.  Just saying you likely upgraded and that is why you are getting the new method of refreshing tokens.

**Comment by roker15** [comment]
> The latest supabase-js has the latest gotrue-js in it. Just saying you likely upgraded and that is why you are getting the new method of refreshing tokens.

Is there way to fix it?

**Comment by GaryAustin1** [comment]
You could set your version of supabase-js to 1.35.2 or older for the time being.  At some point though, unless SB decides this is a bug, you will need to adjust your code to deal with the extra events.  

Even if they fix the SIGNED_IN event on every tab visibility event to just when the token actually needs refreshing, you will still get a TOKEN_REFRESHED and SIGNED_IN event if the token had expired while you were on another tab.

**Comment by roker15** [comment]
> You could set your version of supabase-js to 1.35.2

You are right i am using 1.35.2 now and everything is working just fine. But still i consider it as bug. Lets see how supabase deal with this.

**Comment by GaryAustin1** [comment]
Are you sure you downgraded?  I backed up to 1.35.2 and the SIGNED_IN event on tab change goes away.
You can check this header in your calls to see:
![image](https://user-images.githubusercontent.com/54564956/173206645-656fa004-7492-4b78-8454-586c82952681.png)

**Comment by roker15** [comment]
> Are you sure you downgraded? I backed up to 1.35.2 and the SIGNED_IN event on tab change goes away. You can check this header in your calls to see: ![image](https://user-images.githubusercontent.com/54564956/173206645-656fa004-7492-4b78-8454-586c82952681.png)

yes i checked as you said 
x-client-info : supabase-js/1.30.2

**Comment by silentworks** [comment]
This is the expected behaviour. Do note to downgrade properly, you will probably need to delete your `node_modules` directory and be sure that the version number you are downgrading to is exact in your package.json file.

**Comment by noty-nick** [comment]
@roker15 

Downgrading can work in short term, but you can also create a wrapper for `onAuthStateChange` to filter out undesired events

Here is an example https://github.com/supabase/gotrue-js/issues/284#issuecomment-1141402174

**Comment by noty-nick** [comment]
@silentworks If this is expected - I guest [this issue](https://github.com/supabase/gotrue-js/issues/284) should be closed? take a look

**Comment by zakaria-chahboun** [comment]
also on Firefox
it's seems they use
```js
window.addEventListener("focus", () => {
    // ...
});
```

**Comment by hf** [comment]
This is intentional behavior since tabs can be forgotten for a very long time in certain cases, and when you come back to the tab the user is effectively "signed-in" again.

**Comment by ToniRV** [comment]
It may be intentional but it is a horrible experience for our users.
At the very least, it should be possible for the developers to switch off, time out, or change that behavior...

What can we do right now to stop all components from refreshing because of this (poor) supabase decision?

**Comment by silentworks** [comment]
@ToniRV I believe you only get this behavior if you are trying to render something based on listening to the state inside of the `onAuthStateChange` listener. This is something the app developer has full control over, you can write your code in a way so it doesn't listen to all state changes in that listener or even not write any code to listen to changes in there at all.

**Comment by oduncan** [comment]
I'm finding that using this subscription in a user context provider that wraps the entire app (per the docs) forces the entire tree from the server all the way up to render every time you refocus the page (tab away and tab back in or alt tab to another application and then alt tab back to the browser) 

This is counterintuitive and potentially undesirable behavior in browser apps. I understand the consideration for mobile but it's such a core component that it should be optional/skippable or at least given a delay you can set like x mins.

**Comment by oduncan** [comment]
> ```js
> if (session?.user?.id == currentSession?.user?.id) return;
> ```

I tried that but I never have currentSession when the tab is refocused. Where is your currentSession stored? mine would be in useState within the same context provider and every time I alt tab it's set back to null, is your current session stored in a provider up the tree?

**Comment by imageck** [comment]
> @ToniRV I believe you only get this behavior if you are trying to render something based on listening to the state inside of the `onAuthStateChange` listener. This is something the app developer has full control over, you can write your code in a way so it doesn't listen to all state changes in that listener or even not write any code to listen to changes in there at all.

Wrong. `auth-helpers-react` depends on this event. Obviously the change to the GoTrue client also broke the helpers. Now all consumers of SessionContext are constantly re-rendered.

**Comment by silentworks** [comment]
> > @ToniRV I believe you only get this behavior if you are trying to render something based on listening to the state inside of the `onAuthStateChange` listener. This is something the app developer has full control over, you can write your code in a way so it doesn't listen to all state changes in that listener or even not write any code to listen to changes in there at all.
> 
> Wrong. `auth-helpers-react` depends on this event. Obviously the change to the GoTrue client also broke the helpers. Now all consumers of SessionContext are constantly re-rendered.

You are mixing two separate issues. The auth-helpers-react is optional and not mandatory. If the behaviour of the auth-helpers-react is not the desirable you can opt-out of it.

**Comment by d9k** [comment]
[Solved it in react code](https://github.com/d9k/citations-supabase-demo/commit/154ec020fe1e8c25924b2a602ff3e35cd987b7dc#diff-b9c0662b29ec34de906bd924753156f8ef70f81e86451240926ffea98eb5ef14) by adding `useRef` and comparing `JSON.stringify()` of new session and copy:

```ts
  const [session, setSessionRaw] = useState<Session | null | false>(false);

  const sessionRef = useRef(session);

  const setSession = useCallback((newSession: Session | null) => {
    /**
     * Prevent forced redraw on tab focus:
     * [onAuthStateChange (SIGNED\_IN event) Fired everytime I change Chrome Tab or refocus on tab . · Issue #7250 · supabase/supabase](https://github.com/supabase/supabase/issues/7250)
     */
    if (JSON.stringify(sessionRef.current) === JSON.stringify(newSession)) {
      console.debug('SupabaseBrowserAuthManager: no update, the same');
      return;
    }

    console.debug('SupabaseBrowserAuthManager: update, new session');

    sessionRef.current = newSession;
    setSession(newSession);
  }, [setSessionRaw]);

  const { data, error } = useQuery({
    queryKey: ['SupabaseBrowserAuthManager_' + queryKeyUniqueSuffix],
    queryFn: () => createSupabaseSession(supabase),
  });

  useEffect(() => {
    console.log('SupabaseBrowserAuthManager: useEffect on data changed');

    const newSession = data?.data?.session || null;
    if (newSession) {
      browserCookiesSetOnSupabaseAuth(newSession);
    }
    setSession(newSession);

    if (supabase) {
      supabase.auth.onAuthStateChange((event, newSession) => {
        console.log(
          'SupabaseBrowserAuthManager: App: onAuthStateChange: session:',
          newSession,
          event,
        );

        // singularSupabaseSession = session;

        /** @see https://supabase.com/docs/guides/auth/server-side-rendering#bringing-it-together */
        if (event === 'SIGNED_OUT' || (event as string) === 'USER_DELETED') {
          browserCookiesDeleteOnSupabaseSignOut();
        } else if (
          (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') && newSession
        ) {
          browserCookiesSetOnSupabaseAuth(newSession);
        }

        setSession(newSession);
      });
    }
  }, [data]);
```

**Comment by jacobbroughton** [comment]
This seems to work for me, but it may introduce new issues. If anyone has some insight, i'd appreciate it!
`  useEffect(() => {
    setTimeout(() => {
      const {
        data: { subscription },
      } = onAuthStateChange((event, session) => {
        console.log(event);

        return () => {
          subscription.unsubscribe();
        };
      });
    }, 0);
  }, []);`

**Comment by jacobbroughton** [comment]
This worked for me, unsure if it has introduced new bugs...
https://github.com/nuxt-modules/supabase/issues/273#issuecomment-2051932773

**Comment by DKasi634** [comment]
It is 2025, and I'm still facing the same issue, I understand the whole 'token refresh' thing , but still ,this is quite a poor behavior cause you only want this listener to trigger when you auth state changes for real (like with Firebase as far as I've noticed) , now  I've looked for a fix and I can't find any that is clearly explained so far.

**Comment by colecanning** [comment]
same issue, huge shame

**Comment by mjy78** [comment]
Same issue here. Have implemented a workaround to track a `userInitiatedLogin` state variable on "real" user sign in from the login screen, then in onAuthStateChange I ignore the "SIGNED_IN" events unless it was user initiated.

**Comment by coxato** [comment]
same issue here
and we are in 2025 June now

**Comment by Hamza-js** [comment]
Same issue in 2025

**Comment by Massea0** [comment]
hey guys 
Sorry For the comments in french😭
For me, the main issue was that onAuthStateChange fired too frequently, especially with Vite's HMR, causing unnecessary profile re-fetches that would time out. The solution involves using a useRef to store the ID of the last successfully loaded user profile, and then skipping subsequent profile fetches if the auth event is for the same, already loaded user.
`// src/context/AuthContext.tsx
import React, {
    createContext,
    useContext,
    useState,
    useEffect,
    useRef, // Importé pour mémoriser l'état entre les rendus sans provoquer de re-rendu
} from 'react';
import { User, LoginCredentials, AuthContextType } from '@/types/auth';
import { supabase } from '@/lib/supabaseClient';
import { PostgrestBuilder, Session } from '@supabase/supabase-js'; // Types Supabase

// Création du contexte d'authentification
const AuthContext = createContext<AuthContextType | undefined>(undefined);

// Délai d'expiration pour les requêtes Supabase, pour éviter un blocage indéfini.
const SUPABASE_REQUEST_TIMEOUT = 15000; // 15 secondes

/**
 * Encapsule un appel API Supabase (via son constructeur de requête) avec un timeout.
 * Si la promesse Supabase ne se résout pas dans le délai imparti, elle est rejetée.
 * @param builderFn Fonction qui retourne le PostgrestBuilder (ex: () => supabase.from(...).select(...))
 * @param timeoutMs Délai d'expiration en millisecondes.
 * @returns Une promesse qui se résout avec la réponse de Supabase ou est rejetée.
 */
async function supabaseRequestWithTimeout<T>(
    builderFn: () => PostgrestBuilder<T | T[] | null>,
    timeoutMs: number = SUPABASE_REQUEST_TIMEOUT
): Promise<{ data: T | T[] | null; error: any; status?: number; count?: number }> {
    return new Promise((resolve, reject) => {
        const timeoutId = setTimeout(() => {
            console.error(
                `[AuthContext] Supabase request timed out after ${timeoutMs}ms`
            );
            reject(new Error(`Supabase request timed out after ${timeoutMs}ms`));
        }, timeoutMs);

        try {
            // Exécute la fonction pour obtenir le builder et chaîner .then() et .catch()
            builderFn()
                .then((response) => {
                    clearTimeout(timeoutId); // Annuler le timeout si la promesse se résout
                    resolve(response);
                })
                .catch((error) => {
                    clearTimeout(timeoutId); // Annuler le timeout si la promesse est rejetée
                    console.error('[AuthContext] Supabase promise rejected:', error);
                    reject(error);
                });
        } catch (e) {
            // Gérer les erreurs synchrones potentielles lors de l'exécution de builderFn
            clearTimeout(timeoutId);
            console.error(
                '[AuthContext] Error executing Supabase builder function:',
                e
            );
            reject(e);
        }
    });
}

/**
 * Fournisseur du contexte d'authentification.
 * Gère l'état de l'utilisateur, le chargement, les erreurs, et la logique de connexion/déconnexion.
 */
export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({
                                                                          children,
                                                                      }) => {
    // État pour l'utilisateur authentifié (profil complet de l'application)
    const [user, setUser] = useState<User | null>(null);
    // État pour indiquer si une opération d'authentification ou de chargement de profil est en cours
    const [isLoading, setIsLoading] = useState(true);
    // État pour stocker les messages d'erreur liés à l'authentification
    const [error, setError] = useState('');

    // Ref pour mémoriser l'ID de l'utilisateur dont le profil a été chargé avec succès pour la dernière fois.
    // Crucial pour éviter les re-fetch inutiles sur les événements "bruyants" de onAuthStateChange.
    const lastSuccessfullyFetchedUserIdRef = useRef<string | null>(null);
    // Ref pour stocker la dernière session brute reçue de onAuthStateChange.
    // Utilisé par initializeSession pour déterminer si onAuthStateChange a déjà pu s'exécuter.
    const activeSupabaseSessionRef = useRef<Session | null>(null);

    /**
     * Récupère le nom de l'entreprise à partir de son ID.
     * @param companyId L'ID de l'entreprise.
     * @returns Le nom de l'entreprise ou undefined si non trouvé ou en cas d'erreur.
     */
    const fetchCompanyName = async (
        companyId: string
    ): Promise<string | undefined> => {
        console.log(
            '[AuthContext] fetchCompanyName: Fetching for companyId:',
            companyId
        );
        if (!companyId) {
            console.warn('[AuthContext] fetchCompanyName: No companyId provided.');
            return undefined;
        }
        try {
            const { data, error: companyError } = await supabaseRequestWithTimeout<
                { name: string }
            >(() =>
                supabase.from('companies').select('name').eq('id', companyId).single()
            );

            if (companyError) {
                console.error(
                    '[AuthContext] fetchCompanyName: Error fetching company name. Error:',
                    companyError
                );
                return undefined;
            }
            if (Array.isArray(data)) {
                // Ne devrait pas arriver avec .single()
                console.warn(
                    '[AuthContext] fetchCompanyName: Expected single object but got array for companyId:',
                    companyId
                );
                return undefined;
            }
            if (!data) {
                console.warn(
                    '[AuthContext] fetchCompanyName: No data returned for companyId:',
                    companyId
                );
                return undefined;
            }
            console.log(
                '[AuthContext] fetchCompanyName: Success, company name:',
                data.name
            );
            return data.name;
        } catch (e) {
            console.error(
                '[AuthContext] fetchCompanyName: Exception during fetch (possibly timeout):',
                e
            );
            return undefined;
        }
    };

    /**
     * Récupère le profil utilisateur complet (depuis la table 'users')
     * et le nom de l'entreprise si applicable.
     * @param sessionUser L'objet utilisateur de la session Supabase.
     * @returns L'objet User complet de l'application ou null.
     */
    const fetchFullUserProfile = async (
        sessionUser: Session['user'] // Type plus précis pour sessionUser
    ): Promise<User | null> => {
        console.log(
            '[AuthContext] fetchFullUserProfile: Fetching profile for user ID:',
            sessionUser.id
        );
        try {
            // Type pour la structure des données de la table 'users'
            type UserProfileDb = {
                id: string;
                email: string;
                first_name: string;
                last_name: string;
                role: 'client' | 'admin';
                company_id?: string;
                phone?: string;
            };

            const { data: userProfile, error: profileError } =
                await supabaseRequestWithTimeout<UserProfileDb>(() =>
                    supabase.from('users').select('*').eq('id', sessionUser.id).single()
                );

            if (profileError) {
                console.error(
                    '[AuthContext] fetchFullUserProfile: Error fetching user profile:',
                    profileError
                );
                return null;
            }
            if (Array.isArray(userProfile)) {
                console.warn(
                    '[AuthContext] fetchFullUserProfile: Expected single object but got array for user ID:',
                    sessionUser.id
                );
                return null;
            }

            if (userProfile) {
                console.log(
                    '[AuthContext] fetchFullUserProfile: Profile fetched:',
                    userProfile
                );
                let companyName: string | undefined = undefined;
                if (userProfile.company_id) {
                    console.log(
                        '[AuthContext] fetchFullUserProfile: company_id found, attempting to fetch company name for ID:',
                        userProfile.company_id
                    );
                    companyName = await fetchCompanyName(userProfile.company_id);
                    console.log(
                        '[AuthContext] fetchFullUserProfile: Company name fetched:',
                        companyName
                    );
                } else {
                    console.log(
                        '[AuthContext] fetchFullUserProfile: No company_id in profile.'
                    );
                }

                const fullUser: User = {
                    id: sessionUser.id,
                    email: userProfile.email || sessionUser.email || '', // Prioriser l'email du profil, puis de la session
                    firstName: userProfile.first_name,
                    lastName: userProfile.last_name,
                    role: userProfile.role,
                    companyId: userProfile.company_id,
                    phone: userProfile.phone,
                    companyName: companyName,
                };
                console.log(
                    '[AuthContext] fetchFullUserProfile: Constructed fullUser:',
                    fullUser
                );
                return fullUser;
            } else {
                console.warn(
                    '[AuthContext] fetchFullUserProfile: User profile not found for ID:',
                    sessionUser.id
                );
                return null;
            }
        } catch (e) {
            console.error(
                '[AuthContext] fetchFullUserProfile: Exception during profile fetch (possibly timeout):',
                e
            );
            return null;
        }
    };

    // Effet principal pour gérer les changements d'état d'authentification
    useEffect(() => {
        console.log(
            '[AuthContext] Initializing AuthProvider, setting initial isLoading to true.'
        );
        setIsLoading(true);
        activeSupabaseSessionRef.current = undefined; // `undefined` indique que onAuthStateChange n'a pas encore tiré
        lastSuccessfullyFetchedUserIdRef.current = null;

        // Abonnement aux changements d'état d'authentification de Supabase
        const { data: authListener } = supabase.auth.onAuthStateChange(
            async (event, currentSupabaseSession) => {
                // Toujours mettre à jour la ref avec la session la plus récente de Supabase
                activeSupabaseSessionRef.current = currentSupabaseSession;

                console.log(
                    '[AuthContext] onAuthStateChange triggered. Event:',
                    event,
                    'New Session User ID:',
                    currentSupabaseSession?.user?.id,
                    'Current local user state ID (can be stale in callback):', // Le `user` ici est celui de la closure de useEffect
                    user?.id,
                    'Last successfully fetched user ID (ref):',
                    lastSuccessfullyFetchedUserIdRef.current
                );

                if (event === 'SIGNED_OUT') {
                    console.log('[AuthContext] Event: SIGNED_OUT. Clearing user data.');
                    setUser(null);
                    lastSuccessfullyFetchedUserIdRef.current = null;
                    setIsLoading(false);
                    return; // Sortir tôt pour SIGNED_OUT
                }

                if (event === 'PASSWORD_RECOVERY') {
                    console.log(
                        '[AuthContext] Event: PASSWORD_RECOVERY. No user change expected, ensuring isLoading is false.'
                    );
                    if (isLoading) setIsLoading(false);
                    return; // Sortir tôt
                }

                // Si une session Supabase avec un utilisateur existe
                if (currentSupabaseSession?.user) {
                    const supabaseUserId = currentSupabaseSession.user.id;
                    let shouldFetchProfile = false;

                    // Logique pour déterminer si le profil doit être (re)chargé
                    if (event === 'INITIAL_SESSION') {
                        console.log(
                            `[AuthContext] Event: ${event}. Will fetch profile for ${supabaseUserId}.`
                        );
                        shouldFetchProfile = true;
                    } else if (event === 'USER_UPDATED') {
                        // Événement indiquant que les métadonnées utilisateur ont changé côté Supabase
                        console.log(
                            `[AuthContext] Event: ${event}. User data explicitly updated by Supabase for ${supabaseUserId}. Will re-fetch profile.`
                        );
                        shouldFetchProfile = true;
                    } else if (
                        lastSuccessfullyFetchedUserIdRef.current !== supabaseUserId
                    ) {
                        // Si l'ID de l'utilisateur de la session actuelle est différent du dernier chargé avec succès,
                        // ou si aucun profil n'a encore été chargé (la ref est null, typique après un HMR).
                        console.log(
                            `[AuthContext] Event: ${event}. User ID ${supabaseUserId} is new or different from last fetched (${lastSuccessfullyFetchedUserIdRef.current}). Will fetch profile.`
                        );
                        shouldFetchProfile = true;
                    } else if (
                        (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') &&
                        lastSuccessfullyFetchedUserIdRef.current === supabaseUserId
                    ) {
                        // C'est un événement "bruyant" (SIGNED_IN sur focus, TOKEN_REFRESHED) pour un utilisateur
                        // dont le profil a DÉJÀ été chargé avec succès. On saute la récupération du profil.
                        console.log(
                            `[AuthContext] Event: ${event}. User ID ${supabaseUserId} is same as last successfully fetched. Skipping profile re-fetch.`
                        );
                        shouldFetchProfile = false;
                        // S'assurer que isLoading est false si on saute la récupération.
                        if (isLoading) setIsLoading(false);
                    } else {
                        // Cas par défaut : si aucune condition spécifique n'est remplie mais qu'on a un utilisateur de session,
                        // il est plus sûr de supposer qu'on pourrait avoir besoin de vérifier/récupérer.
                        console.log(
                            `[AuthContext] Event: ${event}. Fallback condition for user ${supabaseUserId}. Deciding to fetch profile.`
                        );
                        shouldFetchProfile = true;
                    }

                    if (shouldFetchProfile) {
                        console.log(
                            `[AuthContext] Fetching profile for user ID: ${supabaseUserId} due to event: ${event}.`
                        );
                        setIsLoading(true); // Indiquer le début du chargement du profil
                        try {
                            const fetchedUser = await fetchFullUserProfile(
                                currentSupabaseSession.user
                            );
                            if (fetchedUser) {
                                console.log(
                                    `[AuthContext] ${event}: Successfully fetched and setting user state for ${supabaseUserId}:`,
                                    fetchedUser
                                );
                                setUser(fetchedUser);
                                // Mettre à jour la ref APRÈS avoir réussi à charger et définir l'utilisateur
                                lastSuccessfullyFetchedUserIdRef.current = supabaseUserId;
                            } else {
                                console.warn(
                                    `[AuthContext] ${event}: Failed to fetch full user profile for ${supabaseUserId} or profile not found. Setting user to null.`
                                );
                                setUser(null);
                                // Ne pas effacer lastSuccessfullyFetchedUserIdRef ici. Si la session est toujours valide
                                // mais que la récupération du profil échoue (ex: timeout), on ne veut pas
                                // retenter immédiatement si un autre événement bruyant arrive.
                                // La ref sera effacée sur SIGNED_OUT ou si un autre utilisateur se connecte.
                            }
                        } catch (e) {
                            console.error(
                                `[AuthContext] ${event}: Exception during profile fetch for ${supabaseUserId}. Setting user to null. Error:`,
                                e
                            );
                            setUser(null);
                        } finally {
                            console.log(
                                `[AuthContext] ${event}: Finished profile fetch attempt for ${supabaseUserId}, setting isLoading to false.`
                            );
                            setIsLoading(false); // Assurer que isLoading est false après la tentative
                        }
                    }
                } else {
                    // Pas d'utilisateur dans currentSupabaseSession (ex: INITIAL_SESSION sans session active)
                    console.log(
                        `[AuthContext] Event: ${event}. No user in Supabase session. Clearing user data.`
                    );
                    setUser(null);
                    lastSuccessfullyFetchedUserIdRef.current = null;
                    setIsLoading(false);
                }
            }
        );

        // Vérification manuelle de la session au montage, comme filet de sécurité
        // si onAuthStateChange est lent pour l'événement INITIAL_SESSION.
        const initializeSession = async () => {
            console.log(
                '[AuthContext] initializeSession: Manually checking session on mount.'
            );
            try {
                // Vérifier si onAuthStateChange a déjà eu une chance de s'exécuter
                if (activeSupabaseSessionRef.current === undefined) {
                    const {
                        data: { session },
                        error: sessionError,
                    } = await supabase.auth.getSession();
                    if (sessionError) {
                        console.error(
                            '[AuthContext] initializeSession: Error getting session:',
                            sessionError
                        );
                    }
                    console.log(
                        '[AuthContext] initializeSession: getSession() result:',
                        session
                    );

                    if (!session && !user && isLoading) {
                        console.log(
                            '[AuthContext] initializeSession: No active session from getSession and no user in state, setting isLoading to false.'
                        );
                        setIsLoading(false);
                        lastSuccessfullyFetchedUserIdRef.current = null;
                    } else if (session && (!user || user.id !== session.user.id) && isLoading) {
                        // Si getSession trouve une session, onAuthStateChange devrait la gérer.
                        // Ce check est surtout pour le cas "pas de session".
                        console.log(
                            '[AuthContext] initializeSession: Session found by getSession(), onAuthStateChange should handle it.'
                        );
                    } else if (!session && user && isLoading) {
                        // État incohérent : utilisateur local mais pas de session Supabase.
                        console.warn(
                            '[AuthContext] initializeSession: Local user exists but no Supabase session. Clearing local user.'
                        );
                        setUser(null);
                        lastSuccessfullyFetchedUserIdRef.current = null;
                        setIsLoading(false);
                    }
                } else {
                    console.log(
                        '[AuthContext] initializeSession: onAuthStateChange likely already handled initial state, skipping manual getSession.'
                    );
                }
            } catch (e) {
                console.error(
                    '[AuthContext] initializeSession: Exception checking session:',
                    e
                );
                if (isLoading) setIsLoading(false);
            }
        };

        // Timer pour exécuter initializeSession après un court délai,
        // donnant à onAuthStateChange une chance de s'exécuter en premier.
        const initTimer = setTimeout(() => {
            if (isLoading && !user && activeSupabaseSessionRef.current === undefined) {
                // Si toujours en chargement, sans utilisateur, et que onAuthStateChange n'a pas encore tiré.
                initializeSession();
            } else if (isLoading) {
                // Si toujours en chargement après ce délai, mais que l'utilisateur existe ou que onAuthStateChange a tiré,
                // quelque chose maintient isLoading à true. C'est un filet de sécurité.
                console.warn(
                    '[AuthContext] initializeSession timeout: Still loading, but conditions for manual check not met or onAuthStateChange fired. Forcing isLoading to false.'
                );
                setIsLoading(false);
            }
        }, 500); // Délai légèrement augmenté

        // Nettoyage : désabonnement du listener lors du démontage du composant
        return () => {
            console.log('[AuthContext] Unsubscribing from onAuthStateChange.');
            authListener?.subscription.unsubscribe();
            clearTimeout(initTimer); // Nettoyer le timer
        };
    }, []); // Le tableau de dépendances vide est crucial ici pour une exécution unique.

    /**
     * Gère la connexion de l'utilisateur.
     * @param credentials Email et mot de passe.
     */
    const login = async (credentials: LoginCredentials) => {
        console.log(
            '[AuthContext] login: Attempting login for email:',
            credentials.email
        );
        setIsLoading(true);
        setError('');
        try {
            const { data: signInData, error: signInError } =
                await supabase.auth.signInWithPassword({
                    email: credentials.email,
                    password: credentials.password,
                });

            if (signInError) {
                console.error('[AuthContext] login: Supabase signInError:', signInError);
                setUser(null);
                lastSuccessfullyFetchedUserIdRef.current = null;
                setError(signInError.message || 'Login failed');
                setIsLoading(false); // Arrêter le chargement en cas d'erreur de connexion
                throw signInError;
            }
            console.log(
                '[AuthContext] login: Sign-in successful. User ID:',
                signInData.user?.id
            );
            // onAuthStateChange (avec l'événement SIGNED_IN) se chargera de récupérer le profil
            // et de mettre à jour isLoading.
        } catch (error: any) {
            console.error(
                '[AuthContext] login: Catching error during login process:',
                error
            );
            // S'assurer que l'état est nettoyé si ce n'est pas déjà géré par le bloc signInError
            if (
                !error.message?.includes('Invalid login credentials') &&
                !error.message?.includes('AuthApiError') // Pour les erreurs génériques d'API d'auth Supabase
            ) {
                setUser(null);
                lastSuccessfullyFetchedUserIdRef.current = null;
                setError(error.message || 'Login failed');
            }
            // S'assurer que isLoading est false s'il a été mis à true au début de login
            if (isLoading) setIsLoading(false);
            throw error; // Relancer l'erreur pour que le composant LoginForm puisse la gérer
        }
    };

    /**
     * Gère la déconnexion de l'utilisateur.
     */
    const logout = async () => {
        console.log('[AuthContext] logout: Attempting to sign out.');
        setIsLoading(true);
        try {
            const { error: signOutError } = await supabase.auth.signOut();
            if (signOutError) {
                console.error('[AuthContext] logout: Supabase signOutError:', signOutError);
            }
            // onAuthStateChange avec l'événement 'SIGNED_OUT' devrait gérer
            // setUser(null) et setIsLoading(false).
            // Le bloc finally ci-dessous le fait explicitement pour une réactivité immédiate.
        } catch (e) {
            console.error('[AuthContext] logout: Exception during sign out:', e);
        } finally {
            // Assurer que l'état est nettoyé immédiatement, indépendamment du timing de onAuthStateChange.
            console.log(
                '[AuthContext] logout: Explicitly setting user to null and isLoading to false in finally.'
            );
            setUser(null);
            lastSuccessfullyFetchedUserIdRef.current = null;
            setIsLoading(false);
        }
    };

    // Fournir les valeurs du contexte aux composants enfants
    return (
        <AuthContext.Provider value={{ user, login, logout, isLoading, error }}>
            {children}
        </AuthContext.Provider>
    );
};

/**
 * Hook personnalisé pour accéder facilement au contexte d'authentification.
 * @returns L'objet AuthContextType.
 * @throws Error si utilisé en dehors d'un AuthProvider.
 */
export const useAuth = () => {
    const context = useContext(AuthContext);
    if (context === undefined) {
        throw new Error('useAuth must be used within an AuthProvider');
    }
    return context;
};`

**Comment by JD10NN3** [comment]
Same

**Comment by feralfaroh** [comment]
Same Issue

**Comment by Nishanth-Gobi** [comment]
Same issue

**Comment by RubyBit** [comment]
Similar issue
