### ISSUE TITLE
Upload of ArrayBuffer ends up corrupted

### ISSUE THREAD

**Issue by eliranbenishai** [supabase/supabase#7252]
# Bug report

## Describe the bug

My environment is deployed to Vercel so no file uploads are possible (to my knowledge). So I'm sending a cropped image (using `react-cropper`) in base64 to the api route, where the image is then converted to an ArrayBuffer (using `base64-arraybuffer`, just like in the docs) and then uploaded it to the storage using the appropriate mime type (extracted from the file). The file that ends up being uploaded is corrupted and can't be displayed anywhere.

I've tried several image formats and not using react-cropper but keep getting the same result. I checked the encoded file in the browser and it checks out. Something in the upload of an ArrayBuffer could be the culprit?

## To Reproduce

The function used to send the encoded image - 
```
        const image = cropperRef.current.cropper.getCroppedCanvas().toDataURL('image/jpeg')

        fetch('/api/avatar', {
            body: JSON.stringify({
                image,
                slug,
                type,
            }),
            method: 'POST',
        })
```

The function used on the backend to decode and upload the file - 
```
const { image, slug, type } = JSON.parse(req.body)
        const { data, error } = await supabase
            .storage
            .from('sic')
            .upload(`${slug}.${mime.extension(type)}`, decode(image), {
                contentType: type,
                upsert: true
            })
```

## Expected behavior

The file that appears in the bucket would be a readable image.

## System information

- Version of supabase-js: 1.35.3
- Version of Node.js: 16.13.0

**Comment by ndom91** [comment]
Having the same issue, ending up with simply a small white square when viewing the image URL (ACL = anon public viewing).

I've tried all of the following:
- Blob
- Buffer
- ArrayBuffer
- Simply a base64 string

<img width="441" alt="image" src="https://user-images.githubusercontent.com/7415984/174311055-b5601eb8-b6fc-40b3-8216-5a9ecefa5a22.png">

Where the `body` is something like `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/4g...` (this image can be viewed successfully when pasting the base64 string into https://jaredwinick.github.io/base64-image-viewer/, for example.

And always end up with this:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/7415984/174311358-58b560ea-05d3-4879-ae20-968691433277.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/7415984/174311539-dc09f5d7-6efe-445d-a4eb-1c744e065e17.png">


I feel like I've got to be doing someting wrong, but can't figure out what it is 🤔

**Comment by steve-chavez** [comment]
Please check if the error persists, it might have been fixed by https://github.com/supabase/supabase/issues/7293

**Comment by ndom91** [comment]
@steve-chavez so I was able now to at least retrieve images that I've uploaded manually, they seem to not load as a little white square anymore. However, I still cannot upload images from base64. When accessed, I still only get a little white square, like in the screenshot above. Also downloading from the supabase storage web ui manually, preview.app also tells me the image file is corrupted.

`upload` apparently takes a `Blob`, `Buffer`, and `string`, among a few others, right?

Shouldn't the following work then theoretically?

```
const bodyString = 'data:image/jpeg;base64,/9j/4AA....

const { data, error } = await supabase
  .storage
  .from('bookmark-imgs')
  .upload({
    'customerId/filename.jpg',
    new Buffer(bodyString, 'base64').toString(), // Buffer
    {
      contentType: 'image/jpeg'
    }
  })

// Or instead of "new Buffer(bodyString...":

import { decode } from 'base64-arraybuffer'

decode(bodyString) // Array Buffer

// Or simply the base64 string by itself? i.e. the 'bodyString' passed directly as the second argument to upload()?
```

How would you recommend uploading somethign that starts out as a base64 encoded image dataUrl?

**Comment by eliranbenishai** [comment]
I tried every permutation I could think of using base 64. What I ended up doing was to use `sharp` to decode the base64 string, resize the image and use the `toBuffer` method to export the final result to, well, a buffer. That buffer was then accepted by Supabase and the image is perfectly fine. Oh I did need to trim the base64 header from the string so that `sharp` could decode it properly. Here's some code - 

```
const { image, slug, type } = JSON.parse(req.body)
        const resized = await sharp(Buffer.from(image.split(';base64,').pop(), 'base64'))
            .resize(400, 400)
            .toFormat('jpg')
            .toBuffer()

        const { data, error } = await supabase
            .storage
            .from('sic')
            .upload(`avatar/${slug}-${generateString(4)}.${mime.extension(type)}`, resized, {
                contentType: type,
                upsert: true
            })
```
Hope it'll help.

**Comment by ndom91** [comment]
Thanks for the tip @eliranbenishai!

For anyone else coming across this issue, I was finally able to solve it as well with this:

```js
let { data, error } = await supabase.storage
  .from('bookmark-imgs')
  .upload(
    `${session.user?.userId}/${fileName}.jpg`,
    Buffer.from(prepareBase64DataUrl(body), 'base64'),
    {
      contentType: 'image/jpeg',
      upsert: true,
    }
  )
```

Where `prepareBase64DataUrl` is:

```js
const prepareBase64DataUrl = (base64) =>
  base64
    .replace('data:image/jpeg;', 'data:image/jpeg;charset=utf-8;')
    .replace(/^.+,/, '')
```

Still every once in a great while an image ends up returned from supabase storage as just a small white square, but I assume it was just too long of a base64 URL to be sending as a `PUT` body or something like that. Somethign is causing it to be corrupted still for some web pages.

**Comment by burmecia** [comment]
To upload binary data using supabase js library, you need to use correct type of input otherwise supabase won't be able to recognise your binary data. I think there might be two common scenario: 

1. upload binary file from local, so you can directly pass `Buffer` in the api.

```js
// an example which runs locally with node.js
const file = fs.readFileSync('./your_local_file.png');  // file is `Buffer` type
const { data, error } = await supabase
    .storage
    .from('test')
    .upload('sample.png',
      file, {
        contentType: 'image/png',  // make sure this content type matches your local file
        upsert: true,
      }
    );
```

2. upload binary file using [base64 encoded data URI](https://en.wikipedia.org/wiki/Data_URI_scheme#Syntax). Supabase doesn't recognise data URI at this moment, so you need to make sure pass correct base64 string to the api like @ndom91 did above. For example,

```js
const { image, slug, type } = JSON.parse(req.body);

// `image` here is a base64 encoded data URI, it is NOT a base64 string, so we need to extract
// the real base64 string from it.
// Check the syntax here: https://en.wikipedia.org/wiki/Data_URI_scheme#Syntax
const imageBase64Str = image.replace(/^.+,/, '');

// then covert it Buffer, because Supabase cannot distinguish normal string and base64 string,
// if you use `imageBase64Str`, Supabase will take it as a normal string not binary.
const buf = Buffer.from(imageBase64Str, 'base64');

// now you can call the api with the binary Buffer
const { data, error } = await supabase
    .storage
    .from('test')
    .upload('sample.png',
      buf, {
        contentType: type,
        upsert: true,
      }
    );
```

**Comment by ndom91** [comment]
So my screenshot uploading function seems to work most of the time now, however, the retrieval still seems to be corrupted :/ 

i.e. this is what it looks like in the Supabase UI - clearly the image loads:

![image](https://user-images.githubusercontent.com/7415984/177842208-1af5c6ee-e86d-4875-971e-4e6e9998c893.png)

However, if I copy the URL and try to open it via that (https://exjtybpqdtxkznbmllfi.supabase.co/storage/v1/object/public/bookmark-imgs/cl4gz8n0h000823bqdl0j2f4o/next-auth.js.org.jpg) - I just get a small white square. 

Same thing when I try to "Download" it directly out of the Supabase UI and open it locally :thinking: 

Something definitely still seems off here

**Comment by burmecia** [comment]
Did you try upload/download with a new file and name? I suspect it might be cached somewhere.

**Comment by ndom91** [comment]
@burmecia yeah could very well have been cache as well, it was in fact the same filename / path actually

**Comment by gk258007** [comment]
> 

Whats the body for the prepareBase64DataUrl argument you passed?

**Comment by ndom91** [comment]
> Whats the body for the prepareBase64DataUrl argument you passed?

If I remember correctly, that's the base64 encoded image. Something like: 

``` 
const buf = Buffer.from(imageBase64Str, 'base64'); 
``` 

See `2.` here: https://github.com/supabase/supabase/issues/7252#issuecomment-1168396996

**Comment by animadesign** [comment]
Hello all,

I ran into this issue when trying to upload the image on the clientside in a Wails application. Because the node buffer library isn't available client side, I tried following the guidance in Supabases' documentation to upload the file as an array buffer and decode. I couldn't get the darn thing working until I encoded and decoded the array buffer before sending it to Supabase for upload. It's dumb, but it works.

    // Client side form submission
    const file = photoField.files[0];
    const reader = new FileReader();
    
    reader.onload = async function(e) {
        const fileData = e.target?.result;
        const fileName = "filename.png"
        await uploadSupabaseFile(fileData, fileName)
    };

    // Only client side reader that seems to work with supabase
    reader.readAsArrayBuffer(file);


    async function uploadSupabaseFile(data, fileName) {
      // Encode so the data can be handled by Supabase upload API
      const base64String = encode(data);

      const {data, error} = await supabase.storage.from('library').upload(fileName, decode(base64String), {
          contentType: 'image/png',
          upsert: true,
      })
    }
