### ISSUE TITLE
Flutter call to stored procedure has the error code: 42809

### ISSUE THREAD

**Issue by ozdeozgu** [supabase/supabase#7282]
# Bug report
PostgrestError(message: public.pe_sp_deneme(p_in => character varying) is a procedure, code: 42809, details: null, hint: To call a procedure, use CALL.)

## Describe the bug
I am using postgrest: ^0.1.10+1 in my Flutter project.
I can get data from views of my postgresql local server but when I rpc stored procedure, I got error of  "code: 42809, details: null, hint: To call a procedure, use CALL."

## To Reproduce

This is working:
`    final PostgrestResponse response = await client.from('pe_vw_products').select().execute();`
But this is not working:
  ` final PostgrestResponse response =   await client.rpc('pe_sp_deneme', params: { 'p_in': 'deneme'  }).execute();`
   

## Expected behavior

I want to rpc postgresql storede procedure from my Flutter desktop and web app

## Screenshots

nothing

## System information

- OS: Windows 10, 64 bit
- Android Studio
- FLutter Windows desktop application
- postgrest package: ^0.1.10+1 (from pub.dev)
- postgresql 14
- postgrest.exe ( size: 46049 KB. I don't know the version of it)

## Additional context

nothing

**Comment by steve-chavez** [comment]
As a workaround, try changing your PROCEDURE to a FUNCTION.
