### ISSUE TITLE
Insert causes select policy violation due to select occuring before all insert triggers are finished

### ISSUE THREAD

**Issue by milesingrams** [supabase/supabase#7289]
# Bug report

## Description of issue

Supabase (Or PostgREST)  is performing a select operation during row insertion, which throws a select policy violation. However the conditions of the select policy should be valid if the select operation waited until all triggers on the insert were completed. Here is a more in depth explanation of what my setup is:

### The setup

I have tables `page` and `user` where a `user` has access to a `page` via a join table `page_user`.

```sql
create table page (
  id uuid primary key
);

create table user (
  id uuid primary key
);

create table page_user (
  page_id uuid references page,
  user_id uuid references user,
  primary key (page_id, user_id)
);
```

I have an RLS policy that restrict select on a `page` to any `user` with a matching `page_user` entry.
```sql
create policy "page select" on page
  for select
  using (
   exists (
     select 1 from page_user where user_id = auth.uid() and page_id = id
    )
  );

create policy "page insert" on page
  for insert
  with check (
    true
  );
```

I have a trigger on `page after insert` that automatically inserts a `page_user` entry for the `page` and `user` that is creating the page.

```sql
create function page_after_insert()
  returns trigger as
  $$
    begin      
      insert into page_user (page_id, user_id) values (NEW.id, auth.uid());
      return NEW;
    end;
  $$ language plpgsql security definer;

create trigger page_after_insert after insert on page
  for each row execute procedure page_after_insert();
```

### The problem

When I use Supabase (via PostgREST) to insert a new page I get a violation on the "page select" policy. This is because PostgREST uses a `select` to send the new `page` id to the client after a successful insert, which I want. However it seems like this `select` query is being run before the "page_after_insert" trigger is run so the `page_user` entry doesn't exist yet. I can fix this by running the trigger before insert with a deferred reference constraint on the `page_id` column, but this seems like a hack. Ideally the full insert with triggers and transactions would be fulfilled before postgrest performs the `select`.

Does this make sense? Is this an expected behavior? I always thought that triggers are performed as part of a transaction so I could expect the `page_user` insert to happen before a subsequent select.

Hope someone can look into this. Thank you for taking a look when you get a chance!

**Comment by steve-chavez** [comment]
> Supabase (Or PostgREST) is performing a select operation during row insertion, which throws a select policy violation.

Can you provide an snippet of the request you're making and the exact error message you get?

**Comment by GaryAustin1** [comment]
Just a quick glance, but is this right?
select 1 from page_user where user_id = auth.uid() and page_id = **page.page_id**
page table does not have page_id column in your table definitions...

**Comment by milesingrams** [comment]
> Just a quick glance, but is this right? select 1 from page_user where user_id = auth.uid() and page_id = **page.page_id** Page table does not have page_id column in your table definitions...

You're right! I fixed it. This is a minimal representation of the code I'm actually running, otherwise there would be a lot of unnecessary columns etc... Might have a few typos/mistakes.

**Comment by milesingrams** [comment]
> Can you provide an snippet of the request you're making and the exact error message you get?

The Javascript request I'm making is:
```javascript
const { data } = await supabase.from('page').insert().single()
```

And the error I get is a 403
```
code: "42501"
details: null
hint: null
message: "new row violates row-level security policy for table \"page\""
```


I found an article that suggested that the error is coming from the `select` policy:
https://nikofischer.com/supabase-error-row-level-security-policy

I validated this by setting the `page select` policy to `using (true)` and it worked. However it should also work with the current code because the `page after insert` trigger should create a `page_user` row BEFORE the select is made by PostgREST since all triggers happen in the same transaction.

**Comment by GaryAustin1** [comment]
@steve-chavez  will be the expert on this.  But all you did by setting select policy to true is prove either SB has an issue with the select running too soon (your reporting issue) OR your policy is not working as you have it.  **How do you know your policy is correct?**  Do you have policies on page_user select?  Is the policy you are showing now all of your select policy on page table select?
Not trying to be a pain, just can't think of how postgrest could run a select before the insert (and it's triggers) have finished as an after trigger can abort the insert.

**Comment by milesingrams** [comment]
Changing the select policy to true makes the insert work so clearly the select policy is triggering during insert.
Additionally leaving the select policy as-is and changing the trigger to 'before insert' instead of 'after insert' also works. The caveat being that I need to make the 'page_id' foreign key constraint on 'page_user' deferred so that it doesn't throw.

But the fact that it works when moving the trigger to before insert seems evidence enough that the policy works if the page_user exists before the check is made. 

I also tested the select policy with standalone select statements and it works as intended.

**Comment by steve-chavez** [comment]
> Supabase (Or PostgREST) is performing a select operation during row insertion
> https://nikofischer.com/supabase-error-row-level-security-policy

Have you tried using `returning=minimal`?

```js
await supabase.from('sample').insert({ key: 'value' }, { returning: 'minimal' })
```

> I'm not quite sure what the order of operations is behind the scenes.

Here's a sample generated query. Using the below:

```
create table page (
  id int primary key,
  name text
);

const { data } = await supabase.from('page').insert({ "id": 1, "name": "page-1" });
```

This is generated:

```sql
WITH pgrst_source AS (
  WITH 
  pgrst_payload AS (SELECT $1::json AS json_data), 
  pgrst_body AS ( SELECT CASE WHEN json_typeof(json_data) = 'array' THEN json_data ELSE json_build_array(json_data) END AS val FROM pgrst_payload) 
  INSERT INTO "test"."page"("id", "name") SELECT "id", "name" FROM json_populate_recordset (null::"test"."page", (SELECT val FROM pgrst_body)) _  
  RETURNING "test"."page".*
) ;
```

**Comment by GaryAustin1** [comment]
@steve-chavez So just to clarify for my understanding.   There is no actual select statement.  The returning is part of the insert, which has to meet select policy during the insert operation.  An after trigger occurs after both the insert of data to the db and the returning operation.

**Comment by milesingrams** [comment]
Thanks so much for the clarification and detailed introspection of the generated SQL!

I tried using `{ returning: 'minimal' }` and it worked, but it stops me from having access to the ID of the new page on the frontend which I would need that to redirect the user to a new URL.

It makes sense that there is no SELECT statement since that would be inefficient, but it seems like Postgres inherently needs SELECT access for an INSERT...RETURNING query which means I would need to have the `page_user` added in the BEFORE INSERT trigger and use a deferred reference constraint.

Due to other security challenges I ran into I've decided that I'm gonna try to go for the route of using RLS only for SELECT access, and Security Definer RPC functions to handle all Insert/Update/Delete access. This allows me much more fine-grained security logic for data modification (ie. Different security checks depending on which column is being updated), while still having the ease and power of RLS on the SELECTS. It also means the read access is still secured even when using Supabase realtime due to the amazing recent addition of SELECT RLS on the realtime stream.

Do you think this is a decent approach? I know I have to craft the security definer RPC functions carefully to avoid any holes.

Thank you again for looking into this. It's really cool to learn how to have database level security without the complexity and risk of an additional API layer.

**Comment by steve-chavez** [comment]
I think this is related to 

[Postgres Trigger side-effect is occurring out of order with row-level security select policy](https://stackoverflow.com/questions/52565720/postgres-trigger-side-effect-is-occurring-out-of-order-with-row-level-security-s)

> Do you think this is a decent approach? I know I have to craft the security definer RPC functions carefully to avoid any holes.

Yeah, security definers would be good. Sorry for the late reply here.

**Comment by GaryAustin1** [comment]
Closing this as this is the way Postgres works per the discussion.

**Comment by adamlamaa** [comment]
If anybody else stumbles on this issue looking for a solution, here is what I ended up doing to resolve this when doing graphql mutations, that gave a similar error:

* Add a `created_by` column to your table.
* Add a trigger that sets the created_by, something like this:
```
CREATE OR REPLACE FUNCTION public.set_created_by() RETURNS trigger AS $$
BEGIN
    NEW.created_by := auth.uid();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
```
* Attach the trigger to your table
```
CREATE TRIGGER insert_created_by
BEFORE INSERT ON public.table_name_here
FOR EACH ROW
EXECUTE PROCEDURE public.set_created_by();
```
* Update your policy
```
create policy "Members can read"
on public.table_name_here
as permissive
for select
to authenticated
using (auth.uid() = created_by or user_is_group_member(group_id));
```

This will allow access to the user creating the data.

**Comment by EugeneHerasymchuk** [comment]
@adamlamaa, but your solution is more like a "fallback", because there might be much more complicated logic in the policy itself, where you're making fallback for created_by value only

**Comment by adamlamaa** [comment]
>  @adamlamaa, but your solution is more like a "fallback", because there might be much more complicated logic in the policy itself, where you're making fallback for created_by value only

Completly agree that it is a fallback. Would prefer not to have to do this, but works for my usecase.
