### ISSUE TITLE
Got an error PGRST102: Error in $: not enough input when inserting the data using supabase js

### ISSUE THREAD

**Issue by phuochau** [supabase/supabase#7293]
# Bug report

We got a 400 error with Postgres error code `PGRST102` and `message: "Error in $: not enough input"` for a simple inserting call by using `supabase-js`. But after that, we check the supabase, we can see the new record. 

## To Reproduce

I have a `simple_test` table which uses to reproduce the bug with the structure below

```sql
create table simple_test (
  id uuid DEFAULT uuid_generate_v4(),
  name varchar(512) not null,

  primary key (id)
);
```

In the next.js site, it uses supabase to insert data

```js
supabase.from('simple_test').insert({ name: 'sample' })
```

After that, I use the Network tab in Chrome to see the request, it returns an error:

```
message: "Error in $: not enough input"
```

I tried to set up another supabase project, and the response is the same but including the code `PGRST102`.

Not sure how to fix this bug because seem it's a simple call. Please help to point to me what I should do, thank you

## Expected behavior

The data was inserted successfully so the response should have an HTTP code should be 200 and include the inserted data.

## System information

- OS: macOS 12.4
- Browser: Chrome 102.0.5005.115 
- Version of supabase-js: 1.35.3
- Version of Node.js: 16.14.2

## Additional context

Thank you so much!

**Comment by phuochau** [comment]
Now I got the same issue with any inserting calls in my project

**Comment by phuochau** [comment]
I tried some tests:

- If I request as a guest, it will be successful.
- If I request as a user (logged in by Github), it will be failed.
- If I request as a user (using a magic link), it will be successful.

Any thoughts?

**Comment by perhp** [comment]
I get the same error logged in with facebook (havent tried others). This issue causes serious problems within our platform, and seems to be a supabase issue, as we haven't made changes to the part that started failing.

**Comment by steve-chavez** [comment]
@phuochau Can you share your project ref to steve@supabase.io?

> message: "Error in $: not enough input"

That error only happens when the insert body is empty. I can't reproduce locally so I'd like to check your project.

**Comment by steve-chavez** [comment]
@perhp Can you share your enviroment(next.js?) and a snippet too?

**Comment by phuochau** [comment]
@steve-chavez Thank your so much for your reply, just sent you an email that includes information that you can reproduce the issue. 

I made some tests and I see:
* If I create a new supabase project with the same Github account, the error is still there. (right now, we only can sign up Supabase by Github account).
* If I sign up supabase by a new Github account, and create a new supabase project, the error is not happening.

I hope those results can help you with more information. Thank you!

**Comment by farzd** [comment]
i'm having multiple errors, one of them is the same as this, but another is for POST
https://github.com/supabase/supabase/discussions/7319

**Comment by steve-chavez** [comment]
Hey everyone. Just to let you know that we've isolated the error to a bad processing of the JWT in our Cloudflare workers. We're working on a fix.

**Comment by perhp** [comment]
Awesome! Thanks alot.

**Comment by steve-chavez** [comment]
We've deployed a fix. Can everyone please check if that cleared the error?

**Comment by perhp** [comment]
Yep, seems to be fixed! 🥳

**Comment by farzd** [comment]
This has fixed it for me too, any chance this can happen again? caused lot of a pain for me in production

**Comment by phuochau** [comment]
I can confirm the issue was fixed. Thank you @steve-chavez and the supabase team.

**Comment by steve-chavez** [comment]
> This has fixed it for me too, any chance this can happen again? caused lot of a pain for me in production

@farzd Sorry for any trouble caused. The infra team is now adding regression tests to ensure this doesn't happen again for the Cloudflare workers.

To clarify, this happened because an exception during the JWT decoding caused cloudflare workers to resend the request without a body(hence the error message mentioned [above](https://github.com/supabase/supabase/issues/7293#issuecomment-1158051205)). More details [here](https://stackoverflow.com/questions/63472642/event-passthroughonexception-sends-requests-to-origin-but-without-post-data).

---

The REST service is [thoroughly tested](https://github.com/PostgREST/postgrest/blob/main/nix/README.md#testing) and these kind of errors wouldn't make a stable release or even a pre-release.

**Comment by steve-chavez** [comment]
Not familiar with bubble.io, can you share the JS snippets you use? 

As I [mentioned above](https://github.com/supabase/supabase/issues/7293#issuecomment-1158051205), this error message only happens when the insert/upsert body you send is empty.

**Comment by himanshu311099** [comment]
I am not using any js snippet, in bubble.io, we can set up API calls using API connector, all we need is the curl URL, headers and data required for the call. 
I am passing data for some columns of the table to insert a row and not keeping the body empty

**Comment by himanshu311099** [comment]
For your reference, this is the error I am getting for insert calls 
"Raw response for the API 
Status code 400
{"code":"PGRST102","details":null,"hint":null,"message":"Error in $: not enough input"}"

**Comment by himanshu311099** [comment]
I can but how should I do that

**Comment by himanshu311099** [comment]
Hey @GaryAustin1 did you get something that might help me with this, I am stuck here for last few days and tried everything.

**Comment by GaryAustin1** [comment]
There is not enough info to help you.  Can you show a screen shot of your bubble.io page where you set up the request?
As Steve said this error is that the body is empty when it gets to the server.

**Comment by eRuaro** [comment]
I'm still getting the same error using Python and `requests` library @GaryAustin1 .
```
def get_document_from_supabase(document_title: str):
    try:
        supabase_url = os.environ.get("SUPABASE_URL")
        supabase_key = os.environ.get("SUPABASE_KEY")
        response = requests.post(
            url=supabase_url + f"/rest/v1/document?select=document&document_title=eq.{document_title}",
            headers={
                "apikey": supabase_key,
                "Authorization": f"Bearer {supabase_key}",
            }
        )

        print(response.json())
```

Printed output to stdout:
```
{'code': 'PGRST102', 'details': None, 'hint': None, 'message': 'Error in $: not enough input'}
```

**Comment by Bobbyjsx** [comment]
i am having this same error.
![Screenshot 2023-06-30 at 4 19 55 PM](https://github.com/supabase/supabase/assets/104563882/d8004b86-cc76-4375-9806-a3b8970b584d)
![Screenshot 2023-06-30 at 4 20 12 PM](https://github.com/supabase/supabase/assets/104563882/55366ff6-32f5-403d-9c3c-6c76016c5c08)

**Comment by Ahrarhussain** [comment]
This is what worked for me when connecting express with Supabase, while making calls from Vue3 frontend.

- I placed try and catch in the backend, where I was handling my api.

- From the error displayed, I realised that the data I had entered for one of the datatypes was not matching the data definition in supabase. I had initially put varchar type data, e.g "String123" where it was expecting varchar [] array type data e.g : "{String}".

**Comment by Marvy101** [comment]
Having the same error:
Was working fine a few days ago no change made and now it doesn't work. 

Is it the same cloudflare error?

Error inserting into Supabase: {'code': '22P02', 'details': 'Token "<" is invalid.', 'hint': None, 'message': 'invalid input syntax for type json'}

**Comment by Marvy101** [comment]
This is what I am trying to insert:
{"user_id": "dada", "api_key": "oca_v4qOpkDF44hssY9mnGQb4cL"}

and here's the schema of the table:
<img width="918" alt="image" src="https://github.com/supabase/supabase/assets/91634699/86733716-3c3b-4e37-9329-4cb9adf3ba1e">

So we should not be having any kind of problems.

**Comment by GaryAustin1** [comment]
Not sure without more info, but always better to start a new post unless you have an absolute similar error with an older post or use Discord to ask for help.

You have not mentioned what framework you are using or how you are doing this insert, or shown any code.

**Comment by Marvy101** [comment]
Thank you, will ask on discord then make a post!
