### ISSUE TITLE
self-hosting supabase with docker on ubuntu 22

### ISSUE THREAD

**Issue by NarmerTheFirst** [supabase/supabase#7306]
supabase-studio keeps connecting to server 

404 not found on http://localhost:3000/api/projects/default/subscription
401 Head http://localhost:8000/rest/v1 

## To Reproduce

1. go to self hosting with docker using official docs
2. keeps reconnecting 
3. inspect page
4. 404 not found on
 http://localhost:3000/api/projects/default/subscription

401 Head http://localhost:8000/rest/v1

## Expected behavior

A working supabase instance where i dont have to change anything in docker-compose.yml to make it work other then secret key , anon, service key

- OS: [linux:ubuntu]
- Browser  [firefox]
- Version of supabase-js: [latest]

**Comment by NarmerTheFirst** [comment]
never mind u guys i fixed it 
all i had to do is delete everything and move on

**Comment by silentworks** [comment]
Happy to hear you got this fixed.

**Comment by NarmerTheFirst** [comment]
oh no i couldnt fix it but this guy didhttps://github.com/christopher-talke/docker-cli-supabase.gitSent from my Galaxy
-------- Original message --------From: Andrew Smith ***@***.***> Date: 18/06/2022  11:59 pm  (GMT+02:00) To: supabase/supabase ***@***.***> Cc: NarmerTheFirst ***@***.***>, Author ***@***.***> Subject: Re: [supabase/supabase] self-hosting supabase with docker on ubuntu 22 (Issue #7306) 
Happy to hear you got this fixed.
