### ISSUE TITLE
weird link behaviour in docs

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#7309]
using latest Firefox inside https://supabase.com/docs/guides/client-libraries

if I click the links to "supabase client" the redirect doesn't work

<img width="771" alt="image" src="https://user-images.githubusercontent.com/458736/174115905-51eb94d8-6b8d-4d12-ba53-5ac8c4d10c16.png">

only if I "Open in new tab" it goes on a redirect to https://supabase.com/docs/reference (which is the desired behavior)

how to get the page to redirect on link click?

**Comment by silentworks** [comment]
Same behaviour in Brave Browser.

**Comment by burmecia** [comment]
same behaviour in Chrome and Safari on MacOS.
