### ISSUE TITLE
Env Setup & Database migrations

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase#7312]
# Feature request

It would be nice if you could define your migrations.

A migration contains a number and one or multiple scripts that should be executed. 

Since we dont have a service that starts this migrations it could be a dashboard module where you can drag your migration files or a zip containing this files in. 

This way you can setup your live environment exactly like your dev ones. 

This could be an even bigger feature where you could configure other settings like auth.

**Comment by kiwicopple** [comment]
Hey @Sesa1988 , we already have this! 

See here: https://supabase.com/docs/guides/local-development#database-migrations

Let me know if I mis-understood, and I can reopen this

**Comment by Sesa1988** [comment]
> Hey @Sesa1988 , we already have this! 
> 
> See here: https://supabase.com/docs/guides/local-development#database-migrations
> 
> Let me know if I mis-understood, and I can reopen this

Oh I didnt know that. Thats exactly that, thx.
