### ISSUE TITLE
.contains() not working in Flutter

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#7315]
# Bug report

## Describe the bug

I'm trying to get data that contains some text. Specifically from an array column, but it doesn't work in a standard text column either.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

.contains doesn't work:
```dart
              final res = await supabase
                  .from('places')
                  .select('name')
                  .contains('name', 'Park')
                  .execute();

              final data = res.data;
              print(data); // returns null
              print(data.toString()); // returns null
```

.eq works:
```dart
              final res = await supabase
                  .from('places')
                  .select('name')
                  .eq('name', 'Beach Park')
                  .execute();

              final data = res.data;
              print(data.toString()); // returns Beach Park
```
## Expected behavior

Return data that contains "park"

## System information

- OS: iOs
-supabase_flutter: ^0.3.1
- Flutter 3

**Comment by GaryAustin1** [comment]
I don't use Dart, but .contains works with an array column type and an array variable for the input to the filter (even if one word).
It compares the input array to the array column and returns the row if all the terms in the input array are in the column for that row.  An example would be a tag array column and wanting to find rows with one or more tags.

In the document example main_exports is a text array column.  https://supabase.com/docs/reference/dart/contains

Partial text searches would use .ilike, .like or textSearch.

**Comment by jtkeyva** [comment]
Thanks! The docs are pretty sparse and don't mention anything about "all of the terms". I just tried to do a query that had all of the terms in the array column and it still came back null.

I tried the .like and it works for text columns, but not for text array columns.

How can I search for 1 item... say a tag in an array column?

**Comment by GaryAustin1** [comment]
.ilike,.like only search a text type column, not text array and they search for partial matches with some special characters: https://www.tutorialspoint.com/postgresql/postgresql_like_clause.htm

If you have an array column for example a column of text[] named animals, where a row has ['cat','dog','horse'] in it. then you can do 
.contains('animals',['cat',dog']) and you will get that row.  You not get a row that was ['cat','bird','horse'].
If you did .contains('animals',['cat']) then you would get both the former rows.

Note that if your rows contain ['cats']  or ['Cat'] or ['pretty cat'] it would not find those.  It does not do partial text and needs an exact match.

Warning:  I've not used Dart and I assume the format works like the js library and the documentation for this simple case. 

For completeness .contains actually does more than arrays and deals with ranges, but what you are looking at does not involve those.

**Comment by jtkeyva** [comment]
Thank you for the thorough response. I tried your .contains('animals',['cat',dog']) example and still coming up null. Yeah I would assume it works the same as Dart and .js but this seems to not be working. Hopefully we can get someone using Dart to test this and document it.

**Comment by jtkeyva** [comment]
Aha thanks @GaryAustin1 you got it!

This worked:
.contains('types','{"restaurant"}')

How do we suggest an update for the Dart Docs?

**Comment by GaryAustin1** [comment]
Issue in supabase/supabase is docs.

**Comment by GaryAustin1** [comment]
I thought this was familiar....  I mentioned .contains did not look right, but was doing a PR for mainly JS docs...https://github.com/supabase-community/postgrest-dart/issues/64

**Comment by jtkeyva** [comment]
awesome

**Comment by GaryAustin1** [comment]
Well except they closed it out and did not address .contains it appears...

**Comment by jtkeyva** [comment]
I'm sure @dshukertjr and his team can help with the docs in the mean time ;)

**Comment by dshukertjr** [comment]
@jtkeyva Thanks for pointing this out! Will edit the docs later to clarify some of the confusion here!

**Comment by maheshmnj** [comment]
@dshukertjr How to query based on logical `AND` or `OR` from multiple columns?

I did try something like this
```dart
 final response = await _supabase
        .from(tableName)
        .select()
        .ilike('$columnName1', "%$columnValue%")
        .or(
          '$columnName2.ilike = %$columnValue%',
        )
        .execute();
```

**Comment by dshukertjr** [comment]
@maheshmnj Would you be able to post this question on [discussion](https://github.com/orgs/supabase/discussions)? If you could also add the SQL format of what you want to achieve, that would be helpful.

**Comment by maheshmnj** [comment]
@dshukertjr Posted here https://github.com/orgs/supabase/discussions/15989

**Comment by ViktorKirjanov** [comment]
still not working
