### ISSUE TITLE
Not displayed a created function at Database Functions page

### ISSUE THREAD

**Issue by tell-y** [supabase/supabase#7321]
# Bug report

## Describe the bug

After created a function at here (https://app.supabase.com/project/PROJECT_ID/database/functions), the created function is not displayed.
If you create a new trigger at trigger page, you can see the created function in Select UI.

## To Reproduce

1. Create new function (I did https://github.com/supabase/supabase/issues/6228#issuecomment-1095235706 )
2. Then not displayed it at the functions page

## System information

- OS: macOS
- Browser: chrome

**Comment by silentworks** [comment]
I'm unable to reproduce this issue, can you open a support ticket instead so we can get more detail about your project and look into this more. https://app.supabase.io/support/new

**Comment by tell-y** [comment]
Okay, I did it.

Additional info.
In the dev-tool of the chrome at the network tab, I can see my created function in the requested results, `GET: https://api.supabase.io/platform/pg-meta/PROJECT_ID/functions`

**Comment by saltcod** [comment]
Hey @tell-y  Are you able to see any other functions you create or is this the only one that doesn't show?

**Comment by tell-y** [comment]
I created a function below:
![スクリーンショット 2022-06-20 22 51 49](https://user-images.githubusercontent.com/6883692/174616977-e18a86e8-fe3b-47e3-83b7-6371342ffa72.png)
![スクリーンショット 2022-06-20 22 50 59](https://user-images.githubusercontent.com/6883692/174616780-3c39a071-3aa4-4886-876f-9e89f343c820.png)

I can see it.

**Comment by dshukertjr** [comment]
@tell-y BTW, if you ran this SQL to create the function, it will create it on `public` schema and not `auth` schema. 

```sql
create function check_user()
returns trigger
language plpgsql
as $$
begin
  if right(new.email, 11) = '@domain.com' then
    return new;
  else
    return null;
  end if;
end;
$$;
```

@saltcod I think I saw this bug the other day around the same time as well. I cannot reproduce now, but I created a function under public schema with return type of trigger, and it was not showing up on the list of functions on the dashboard. I can confirm that this is no longer the case, as I see all of the functions. 

@tell-y Are you still not seeing the function that you created?

**Comment by Chogster** [comment]
Just to add to this issue, I was just able to reproduce the issue. I changed an existing function from schema public to auth and the function has completely disappeared from my dashboard. It is still possible to see the function definition from trigger page.

**Comment by tell-y** [comment]
Hi @dshukertjr
Thank you for your comment. I received the same advice from the support team.
My understanding has been that the function should be in auth schema because it's related to the user table.
I will re-create it in the public schema to edit the function code if I have to.

> Could you check if you still cannot see the function you created?

No I cannot see it yet.

**Comment by kiwicopple** [comment]
I believe that we hide the functions in the auth schema, mainly because it shouldn't be created there as it would create some difficulties for us to manage your auth system (upgrades etc).

Perhaps for now, you can add it to the `public` schema, and make sure it has `security invoker`, and not `security definer`?

We are about to bring out 3 different schemas with different permissions models, where you can go crazy creating functions, and over time we will lock the auth schema completely (to avoid situations like this)

**Comment by tell-y** [comment]
It seems that my understanding of the schema might be lacking.
I assumed that we must create a function as auth schema for handling "auth.users".

Thank you all for advising and support.

> We are about to bring out 3 different schemas with different permissions models, where you can go crazy creating functions, and over time we will lock the auth schema completely (to avoid situations like this)

So I close this issue.
