### ISSUE TITLE
Can't create columns with default value to null

### ISSUE THREAD

**Issue by madsbuch** [supabase/supabase#7322]
# Bug report
It is not possible to create new columns where the default value is null. In particular, this means that it is not possible to set up foreign keys.

## To Reproduce
Try to create a column of the UUID type that has an FK constraint to another table.

## Expected behavior
That is would success

## Screenshots
![Screenshot from 2022-06-17 11-33-08](https://user-images.githubusercontent.com/1612807/174271858-9f802b7f-caa3-4bec-a6ee-58cd3a8d0cd9.png)

## System information

- OS: PopOS
- Browser: Chrome
- Version of supabase-cli: 0.26.0

**Comment by silentworks** [comment]
I tested this on one of my projects and I'm unable to reproduce the error you are having. Maybe there is another constraint on that table that is causing the issue you are having. Here is a video showing it working in my Supabase project

https://user-images.githubusercontent.com/79497/174456450-747a22ac-8d12-48eb-99d0-31f53317a9ed.mov

I also noticed in your **To reproduce** step you make mention of creating a column, but in your screenshot, it shows updating a column. I did try creating a new column too on this same table and didn't get an error.

**Comment by madsbuch** [comment]
@silentworks I am not able t reproduce your video.

Have you tried setting the column type to UUID before adding the FK relation?

Also, it appears you can have your default value to be NULL for your UUID column, I am not able to do that. I can either have it as empty string (as shown in the screen shot) or `generate_uuid_v4()`

**Comment by joshenlim** [comment]
@madsbuch hey there can i just check real quick if you're still facing this issue? i'm not able to reproduce this either on my end

**Comment by joshenlim** [comment]
@madsbuch i'm gonna go ahead to close this issue due to inactivity but please feel free to reopen if you're still running into this - do attach a screen recording of your reproduction of the bug as well

**Comment by joshenlim** [comment]
@madsbuch i'm gonna go ahead to close this issue due to inactivity but please feel free to reopen if you're still running into this - do attach a screen recording of your reproduction of the bug as well
