### ISSUE TITLE
Storage error: Migration failed

### ISSUE THREAD

**Issue by JStet** [supabase/supabase#7325]
# Bug report

## Describe the bug

500: internal server error

"Migration failed. Reason: An error occurred running 'add-trigger-to-auto-update-updated_at-column'. Rolled back this migration. No further migrations were run. Reason: permission denied for table objects"

Also, my bucket was deleted (although i have to admit i am not sure whether i did it or not)

## To Reproduce

Error happens in the GUI when I go to Storage or when I try to create a bucket.

But also when I make a request inside of my app with supabase js to /v1/object/list/bucket_name.

## Expected behavior

Successful creation of bucket/successful request.

## Screenshots

![2022-06-17_12-55](https://user-images.githubusercontent.com/67161972/174284987-a00da9be-34fe-43a7-9874-f74ac942446e.png)

## System information

- OS: Arch
- Browser: Firefox

## Additional context

I tried to solve the error my deleting all policies, but that did not work.

**Comment by GaryAustin1** [comment]
Possibly this:  https://status.supabase.com/incidents/mfz0jh87pd7z

**Comment by JStet** [comment]
this error is still happening

**Comment by darora** [comment]
This is usually an indication that the permissions required by the Storage Service within your DB have been manually altered. ( https://supabase.com/docs/guides/platform/permissions )

Restoring them back should fix this for your project. Based on the screenshot, in this case it looks like at least the table `storage.objects` will need its ownership reassigned.

If re-assigning ownership per the link above does not work, please create a support ticket for your project via the Supabase dashboard.
