### ISSUE TITLE
RPC calls not working with supabase-js and supabase-flutter.

### ISSUE THREAD

**Issue by shoxadomokai** [supabase/supabase#7327]
# Bug report

## Describe the bug

RPC calls to any function in Postgres schema using supabase-js and supabase-flutter both return the error;

`{
"hint": "If a new function was created in the database with this name and parameters, try reloading the schema cache."
"message": "Could not find the "public.functionName()" function or the "public.functionName" function with a single unnamed json or jsonb parameter in the schema cache"
}`

Reloading the schema cache did not solve the problem, I tried: `NOTIFY pgrst, 'reload schema'` and restarting the server from the Supabase UI

## To Reproduce

Making any Postgres function call using `supabase.rpc()` .

## Expected behaviour

For the RPC call to resolve as normal and return results.

## System information

- OS: Windows
- Browser: Chrome, FireFox
- Version of supabase-js: 1.29.1
- Version of supabase-flutter: 0.3.1
- Version of Node.js: 16.13.1

## Additional context

POSTMAN calls were previously returning the same error but stopped after about 30 minutes.

I have also tried changing the input variable names to include quotation marks (" ").

**Comment by steve-chavez** [comment]
> RPC calls to any function in Postgres schema using supabase-js and supabase-flutter both return the error;

Can you provide a js snippet of the request?

**Comment by shoxadomokai** [comment]
@steve-chavez sure. Here it is;

```
const { error, data } = await supabase
      .rpc(
        'get_nearby_places', {
          lat: '6.423838487154486',
          lng: '3.464159954320333',
        })
      .eq('published', true)
      .lt('distance', 200)
      .select('*')

    console.log(error, data)
```

This is one of many functions but it's the same error regardless of which.

**Comment by steve-chavez** [comment]
@shoxadomokai Could you send me your project ref at steve@supabase.io? I'll need to look at your instance.

**Comment by shoxadomokai** [comment]
@steve-chavez everything seems to be okay now. Thanks a bunch.

**Comment by abz121** [comment]
I have the exact same error. @shoxadomokai what was the solution that worked for you?
