### ISSUE TITLE
Unauthorized requests are responded in plain text

### ISSUE THREAD

**Issue by sei0o** [supabase/supabase#7342]
# Bug report

## Describe the bug

As mentioned in the [PostgREST documentation](https://postgrest.org/en/stable/api.html#raise-errors-with-http-status-codes), errors should be  returned in JSON format. However, when I tried to access the tables on supabase without the appropriate API key, supabase made a response with a status code `401` and a `text/plain` body: `Missing or invalid credentials.`

This inconsistent behavior confuses some community libraries. For example, [postgrest-go](https://github.com/supabase-community/postgrest-go) assumes all the responses are in JSON and tries to parse (`json.Unmarshal`) the response. Thus, the plain text message `Missing or invalid credentials.` ends up in an error: `invalid character 'M' looking for beginning of value`. Not knowing the original message, it can be tough to realize they are using invalid credentials. 

## To Reproduce

1. Create a PostgREST client without the `apikey` header.
2. Observe the response.

## Expected behavior

The response should be in JSON format like `{"message":"Missing or invalid credentials.","code":"42P??","details":null,"hint":null}`

## Screenshots

Not available

## System information

- OS: Manjaro Linux
- postgrest-go: 0.0.7

**Comment by bivekdev** [comment]
I'd like to work on this issue. Thank You.

**Comment by sei0o** [comment]
Great, ask me anytime if you found any missing information (I'm not sure this is really an issue as no contributors has given a comment though).

**Comment by kiwicopple** [comment]
This one must be in the reverse proxy, rather than PostgREST. I'll let the team know!

**Comment by v1b3m** [comment]
Hey @sei0o Mind sharing the exact API request you made 😃 ?(Want to replicate this but I can't seem to wrap my mind around this)

**Comment by sei0o** [comment]
I have found this in Go, but the minimum reproduce in cURL would be:

```shell
$ curl 'https://XXXXXXXX.supabase.co/rest/v1/tokens' \
              -H 'apikey: foo'
Missing or invalid credentials.⏎
```

Or in JavaScript: 

```js
import { createClient } from '@supabase/supabase-js'

const supabase = createClient('https://XXXXXXXX.supabase.co/rest/v1', '', {shouldThrowOnError: true}) // we don't  give them a key here

console.log("Created a client")

const { data, err } = await supabase.from('tokens').insert([ { foo: 'bar' }])

console.log("data:" + data)
console.log("error: " + err)
```

Note that `supabase-js` [warns](https://github.com/supabase/supabase-js/blob/70870f253d51038e30b976b594e1a88e1b4ae63b/src/SupabaseClient.ts#L72) us when the `supabaseKey` is empty. Removing this guard (or giving random keys) causes an exception: 

```js
$ node --trace-warnings index.js
Created a client
(node:20874) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at a
ny time
    at emitExperimentalWarning (node:internal/util:224:11)
    at fetch (node:internal/bootstrap/pre_execution:195:5)
    at PostgrestBuilder.fetch (/home/sei0o/sandbox/bar/node_modules/@supabase/postgrest-js/dist/main/lib/t
ypes.js:45:35)
    at PostgrestBuilder.fetch (/home/sei0o/sandbox/bar/node_modules/@supabase/postgrest-js/dist/main/lib/t
ypes.js:45:35)
    at PostgrestFilterBuilder.then (/home/sei0o/sandbox/bar/node_modules/@supabase/postgrest-js/dist/main/
lib/types.js:76:24)

node:internal/process/esm_loader:91
    internalBinding('errors').triggerUncaughtException(
                              ^
{ message: 'Missing or invalid credentials.' }

Node.js v18.3.0
```

**Comment by steve-chavez** [comment]
AFAICT this was already solved, so I'll close.

Please reopen if the issue persists.
