### ISSUE TITLE
Could no find a relationship between 'Class' and 'ChildAccount' in the schema cache

### ISSUE THREAD

**Issue by BrijEduTech** [supabase/supabase#7347]
# Bug report

## Describe the bug

I think the postgrest schema cache is somehow not being updated when the supabase free tier account is put to sleep then restored

My supabase account was put to sleep, then restored, but my test cases which were previously passing are now failing with the following error:

Could not find a relationship between 'Class' and 'ChildAccount' in the schema cache

`const allDetails = wrap(
      await supabase
        .from("Class")
        .select("*,ChildAccount(*),TeacherAccount(*),TimeSlot(*),Level(*)")
        .match({ id: this.class.id })
    );
`

![image](https://user-images.githubusercontent.com/102703288/174543847-08816e50-c11c-4a17-b84d-eec23e0bfadd.png)

However, there is a many-to-many join table with the above relationship 
![image](https://user-images.githubusercontent.com/102703288/174543809-42e05cae-5dfd-4686-80af-01a784adeb14.png)

I have tried reloading the schema cache with `NOTIFY pgrst, 'reload schema'` but it didn't seem to help

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2] "^1.33.2"
- Version of Node.js: [e.g. 10.10.0] "v16.15.0"

**Comment by kiwicopple** [comment]
Hey @BrijEduTech. Would you mind "restarting" your instance from the Settings? If that doesn't work, could you please start a support ticket - https://app.supabase.com/support/new
