### ISSUE TITLE
"redirectTo" Does not working with string literal , I am using google Auth.

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#7353]
I have following code, Not working code has been commented out

```
let { user, error } = await supabaseClient.auth.signIn(
      {
        provider: "google",
      },
      {
        // redirectTo: `${BASE_URL}/questionBanks`, // this does not work BASE_URL = "http://localhost:3000"

        redirectTo: 'http://localhost:3000/questionBanks', // This is working
      }
    );
```

**Comment by gracebir** [comment]
@roker15 , I am going to work on it

**Comment by silentworks** [comment]
Can you please provide full context of the file you have this in?

**Comment by gracebir** [comment]
@roker15 , on my side i can reach out `signUpUser`  function, could you please give the `file path`

**Comment by silentworks** [comment]
@roker15 this isn't full context as I can't see where you've imported the constant.ts into your auth.ts file.

**Comment by roker15** [comment]
> @roker15 , on my side i can reach out `signUpUser` function, could you please give the `file path`

Ok i got the reason. in Supabase redirect setting i have included `www` but in BASE_URL `www `is missing . if i do `BASE_URL = "http://www.localhost:3000"` it works. 
But still i baffle why it should differentiate `http://www.localhost:3000` and `http://localhost:3000` when both does the same thing?

**Comment by gracebir** [comment]
@roker15 , means we have to add `BASE_URL` in `constant.ts` file and replace `http://localhost:3000` with `BASE_URL`?
