### ISSUE TITLE
Missing instructions: Dart rpc / Stored Procedures / Postgres Functions

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#7388]
# Improve documentation

## Link 

https://supabase.com/docs/reference/dart/rpc
https://supabase.com/docs/reference/javascript/rpc

## Describe the problem

Dart documentation doesn't explain how to create an rpc on the server. The JS docs do.

Also, the page title's are different for JS and Dart: Is it called Stored Procedure or Postgres Functions?

## Describe the improvement

Add this to Dart (as you see it in JS docs):

`create or replace function hello_world() returns text as $$
  select 'Hello world';
$$ language sql;`

## Additional context

I think it would help a lot to show a real world use case such as an insert (or multiple insert) with arguments/parameters/variables.

**Comment by jaysoni-ash42** [comment]
@Isaiah-Hamilton  can you just enlight the changes for the title to be stored Procedure or Postgres Function? so i can work on this issue

**Comment by J0** [comment]
Hey @jtkeyva,

Thanks for raising the issue - seems like there's an `rpc` tab on the reference docs now - https://supabase.com/docs/reference/dart/contains

let me know if this resolves your issue. 
Thanks!
Jo

**Comment by J0** [comment]
Closing since it might no longer be relevant but feel free to let me know and re-open otherwise.

Thanks!
