### ISSUE TITLE
Cannot connect to supabase database

### ISSUE THREAD

**Issue by Darren120** [supabase/supabase#7396]
```
P1001: Can't reach database server at `db.xxxxx.supabase.co`:`5432`

Please make sure your database server is running at `db.xxxxxx.supabase.co`:`5432`.

```

Tried connecting via prisma JS.

When trying to connect via Adminer UI I also get similar error 

`SQLSTATE[08006] [7] connection to server at "db.xxxxx.supabase.co" (xxxxx), port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections?`

Can you guys restart the db for me plz or something is wrong.

**Comment by Darren120** [comment]
looks like its fixed itself after 1 hr... xd wot...

**Comment by engelzero** [comment]
I'm having this error too
