### ISSUE TITLE
Edge Functions returns Internal Server Error 500

### ISSUE THREAD

**Issue by rbkayz** [supabase/supabase#7415]
# Bug report

## Describe the bug

Tried to deploy the example edge function in https://supabase.com/docs/guides/functions. However, I've received a 500 internal error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow steps as laid out in https://supabase.com/docs/guides/functions
2. Call the function
curl --request POST 'https://<project_ref>.functions.supabase.co/hello-world' \
  --header 'Authorization: Bearer ANON_KEY' \
  --header 'Content-Type: application/json' \
  --data '{ "name":"Functions" }'
4. See error in the console

## Expected behavior

Expected to see the response { "message":"Hello Functions!" }.

## Screenshots

![image](https://user-images.githubusercontent.com/62215539/175552104-b48c73c2-4c61-4204-841d-913a2b1dcd6e.png)

**Comment by burmecia** [comment]
Hi @rbkayz , can you double check if this issue still exists? I followed the steps but cannot reproduce this issue, maybe this is just an interim issue?

**Comment by rbkayz** [comment]
Hi @burmecia, Still the same issue unfortunately with the example hello-world function. Still receiveing a 500 internal server error

However, if I remove passing of the body, then it works fine. See the code below that works well with a 200 response. Any idea why this may be happening?

`
import {serve} from "https://deno.land/std@0.131.0/http/server.ts"

console.log("Hello 2!")

serve(async () => {
  const data = {
    message: `Hello from Bharat!`,
  }

  return new Response(
    JSON.stringify(data),
    { headers: { "Content-Type": "application/json" } },
  )
})`

**Comment by burmecia** [comment]
Did you change anything in the original generated index.ts file? It should be something like below:

```
import { serve } from "https://deno.land/std@0.131.0/http/server.ts"

console.log("Hello from Functions!")

serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  return new Response(
    JSON.stringify(data),
    { headers: { "Content-Type": "application/json" } },
  )
})
```

Can you use the above code and try again?

**Comment by rbkayz** [comment]
Hey Bo, no change made. Used the exact code. Still same error

A couple of points to note:
1. There is a lint under the "https://deno.land/std@0.131.0/http/server.ts". It says _An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std@0.131.0/http/server.js' instead._
2. There is a lint under req. It says _Parameter 'req' implicitly has an 'any' type._

**Comment by burmecia** [comment]
The lints shouldn't be a problem. I checked your function logs and found there are multiple versions, some versions work fine but some not, not sure if this is the cause. As I still cannot reproduce this issue, could you try this function with minimum modification in another project and let us know how it goes? Thanks.

**Comment by rbkayz** [comment]
Hey Bo, This is working now. 

For some reason, the error was happening when I was calling the function from the command line using curl. I'm not sure what it was but from the logs, it seems like the body passed to the request caused an error when parsed.

Works completely fine when I'm using Postman, or the invoke method on JS. Thanks a lot for your help
