### ISSUE TITLE
Password Reset Flow

### ISSUE THREAD

**Issue by jacob-buscher** [supabase/supabase#7416]
### Discussed in https://github.com/supabase/supabase/discussions/3360

<p>Sorry if this isn't the right place for this, this doesn't seem to be a bug exactly but it definitely isn't clear in the docs.</p>

<div type='discussions-op-text'>

<sup>Originally posted by **kohbongchoi** September 29, 2021</sup>
Is the documentation out of date? It seems to be.

I'm using Vue.

Upon clicking the reset password link in the email, it redirects and I briefly see the # escaped fragment in the url, then it disappears. I have a function that allows user to update their password, it seems like supabase auth is automatically detecting the temporary access token cause I haven't done any parsing of it.

Like everything works correctly, I'm just wondering if that's some new "magic" in the supabase library.

Love what you guys are doing but you definitely need to get better with documentation, since your start it's been a weak point of the project.

    const setPassword = async() => {
      const { user, error } = await supabase.auth.update(access_token, {
        password: vm.password,
      })

      console.log(user)
      return user
      
    }</div>

**Comment by kiwicopple** [comment]
> you definitely need to get better with documentation

😓 we just hired a Technical Writer, hopefully we can deliver on expectations

I'm just digging through that discussion now - looks like we have some docs here:

https://supabase.com/docs/reference/javascript/auth-api-resetpasswordforemail#notes

But I agree they aren't clear. Let me tidy them up after I have discussed some of the points with the team

**Comment by jacob-buscher** [comment]
Once I found the ref docs about how to send a reset link I was able to deduce that clicking the reset link signed the user in, enabling them to reset their password, there really just needs to be a more complete 'User Management' guide that follows the whole user management lifecycle (Password Reset/Email Change/Etc).

I don't think there's anything wrong in the docs for how to initiate a reset, the issue is largely just how to complete the reset after you've clicked the link.

It's also non typical that the URL fragment is seperated by 'localhost:3000#params=value' instead of the more typical 'localhost:3000?params=value'

The query params appeared briefly and then were cleared out which was a bit of a head scratcher until I realized that Supabase was stripping and clearing the params, this also doesn't appear to be mentioned in the docs.

This is ultimately what I did and it seems to be working.
```
  useEffect(() => {
    supabase.auth.onAuthStateChange((event, session) => {
      if (event == "PASSWORD_RECOVERY") {
        console.log("PASSWORD_RECOVERY", session);
        const newPass = prompt("What would you like your new password to be?");
        supabase.auth
          .update({ password: newPass })
          .then(() => {
            alert("Password updated successfully!");
          })
          .catch((err) => {
            console.error(err);
            alert("There was an error updating your password.");
          });
      }
      console.log(event);
    });
  }, []);
```

Thank you for all your hardwork on Supabase, we have multiple prod firebase apps and are evaluating Supabase for a new project and we're loving the query power of postgres + lack of infrastructure management.

**Comment by kiwicopple** [comment]
Thanks for the snippet @jacob-buscher ! I've added it to the docs in this PR: https://github.com/supabase/supabase/pull/7443

> query params appeared briefly and then were cleared out which was a bit of a head scratcher until I realized that Supabase was stripping and clearing the params

It looks like we must have changed the auth library at some point and not realised that it affected this reset flow. Very sorry about that - I completely understand the confusion in the Discussion now. 

> Thank you for all your hardwork on Supabase, we have multiple prod firebase apps and are evaluating Supabase

Thank you for considering us!

**Comment by milovangudelj** [comment]
Hi, I'm using `Next.js` and having the hashtag instead of the more common `?` for separating the URL fragment makes it so that you can't really access those parameters on server side since the `#` doesn't get sent in the HTTP request. (see this old issue https://github.com/vercel/next.js/issues/779#issuecomment-272723910)
You also can't access them on client side using `next/router` cause it expects a `?` as the delimiter. There are workarounds but they're finicky and not ideal.
