### ISSUE TITLE
Chore: Reduce repo size

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#7445]
I just cloned this repo again and it's huge! (>0.5Gb)

<img width="515" alt="image" src="https://user-images.githubusercontent.com/10214025/175838307-bc613384-4414-4ade-9c7e-18da58385a4f.png">

I takes a long time to clone, which makes life hard for first time contributors

I checked the git history using the script described [here](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history):

```bash
git rev-list --objects --all |
git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
sed -n 's/^blob //p' |
grep -vF --file=<(git ls-tree -r HEAD | awk '{print $3}') |
awk '$2 >= 2^20' |
sort --numeric-sort --key=2 |
cut -c 1-12,41- |
$(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

And I found the culprits:

```
079117d450bc  2.2MiB www/public/videos/hero.mp4
3e5e3dc2a2d9  2.2MiB www/public/images/blog/launch-week-three/arnie.png
8b7e3e533bf0  2.4MiB web/spec/combined.json
1d16c29ceaab  2.4MiB web/spec/combined.json
f083ba5e5cc8  2.4MiB web/spec/combined.json
6644a8b67eae  2.4MiB web/spec/combined.json
0f9e493abc63  2.4MiB web/spec/combined.json
eba4d016fc03  2.5MiB web/spec/combined.json
f4e30b577b93  2.5MiB web/spec/combined.json
02d926a7d222  2.6MiB web/spec/combined.json
a22d00ffb1db  4.0MiB www/public/images/blog/launch-week-three/communityday.png
aa102e6dbf88  5.9MiB www/public/videos/blog/launch-week-storage-2/directory-uploads.mp4
ef66057fa17e  6.3MiB www/public/videos/blog/launch-week-storage-2/nyan-cat.mp4
b1134cc4a9d4  7.8MiB www/public/images/blog/launch-week-4/friday-supabrew/antines.jpg
ebe35931afb0   12MiB www/public/images/blog/launch-week-4/friday-supabrew/ines_swing.jpg
9786496ebb68   12MiB www/public/images/blog/launch-week-4/friday-supabrew/productShot1.jpg
f9b8e0b33db7   25MiB www/public/images/blog/launch-week-4/friday-supabrew/productShot1.png
```

"git blame @awalias" for those supabrew images

### Next steps

What's the best way to cleanse the history without clobbering anything important ?

**Comment by burmecia** [comment]
I’ve tried bfg (https://rtyley.github.io/bfg-repo-cleaner/) to remove file size > 2M using below command:
```
java -jar bfg-1.14.0.jar --strip-blobs-bigger-than 2M supabase
```
It doesn’t clean too much but saved some space, the .git folder was 552M before and 460M after.

**Comment by kiwicopple** [comment]
Ok, in that case it doesn't seem worth the risk. Let's close and then figure out how to split out the large files in the future. Once that's done we can return to this task
