### ISSUE TITLE
Fix outline on Docs callouts

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#7480]
# Chore

## Describe the chore

We have some "Notes" callouts in our docs (see [here](https://supabase.com/docs/guides/auth/auth-email#configure-email-settings)) which look good in light mode:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/10214025/176325246-6d8eb8f4-ab1f-4341-be38-28c957cbe53a.png">

But not great in dark mode because the left edge is the same color as the background:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/10214025/176325202-1c44229e-0099-4145-9322-5f1b2aa24376.png">

We just need to make the left edge a darker color, and it will look better 👍

**Comment by yeganathan18** [comment]
I will take up the issue!

**Comment by kiwicopple** [comment]
thanks @yeganathan18 🙏
