### ISSUE TITLE
Wrong port displayed

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#7494]
# Bug report

## Describe the bug

On the dashboard, it shows us the port ``6543``, but the right one is ``5432``.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup a new Supabase project in free tier
2. Go to https://app.supabase.com/project/jkbvidevzfytwmzmzeel/settings/database
3. Scroll down to the port section

## Expected behavior

The port should be ``5432`` and not ``6543``.

## Screenshots

![image](https://user-images.githubusercontent.com/25107942/176538454-40ccc404-a52e-4c1e-9f7b-78aec863004c.png)

## System information

- OS: ``Linux (Deepin)``
- Browser (if applies): ``Firefox``
- Version of supabase-js: ``^1.35.4``
- Version of Node.js: ``v16.15.1``

## Additional context

/

**Comment by kiwicopple** [comment]
Hey @Olyno - that one is in the "Connection Pooling" section, which is actually port `6543` 

- Standard Postgres connecitons = `5432`
- Connection Pool (pgbouncer) = `6543`

Perhaps we need to make that clearer somehow?
