### ISSUE TITLE
Make contents of the table's "Description" field visible in Table Editor

### ISSUE THREAD

**Issue by betterthanever2** [supabase/supabase#7508]
# Feature request

## Is your feature request related to a problem? Please describe.

Each table has a non-required "Description" field. Right now, to see the contents of that field, you need to click `Edit table`. It would be nice to have that text shown in the Table Editor UI.

## Describe the solution you'd like

An additional block right above the table (provided that the field 'Description' is not empty) showing the text by default.

## Describe alternatives you've considered

Alternatively: an icon or a button on the same line as filters and `insert` buttons, which would show the text on hover.

**Comment by saltcod** [comment]
Thanks @betterthanever2 !  Good suggestions. 

You can see the table description here: (https://app.supabase.com/project/-/database/tables)

<img width="1392" alt="CleanShot 2022-06-30 at 10 39 02@2x" src="https://user-images.githubusercontent.com/105593/176685263-18ff0697-b578-4602-b3d6-04d66a3ca6a9.png">

But you're right, you can't see it from the table editor interface. Adding it as the hover text for these buttons might be a quick win here:
![CleanShot 2022-06-30 at 10 47 43@2x](https://user-images.githubusercontent.com/105593/176687220-9d07537d-d907-4d62-89d7-ea5bffb12ed0.png)

**Comment by Hallidayo** [comment]
@saltcod can I take this one?

**Comment by aayushdura** [comment]
@saltcod Can I take this one?

**Comment by kiwicopple** [comment]
looks like @Hallidayo jumped in first - feel free to create a PR when you can (or you can hand it off to @aayushdura :) ). Thanks team!

**Comment by Hallidayo** [comment]
Cool thanks @kiwicopple

**Comment by gitstart** [comment]
[Here's](https://github.com/supabase/supabase/pull/7795) @aayushdura's PR
