### ISSUE TITLE
Navbar links 'Guides' and 'Reference' are both higlighted in green at the same time

### ISSUE THREAD

**Issue by ChristianLutzCL** [supabase/supabase#7530]
# Bug report

## Describe the bug

If you access the documentation via the start page or directly via 'https://supabase.com/docs', and then go to the "Reference" page, the "Guides" and "Reference" links are highlighted in green.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com'
2. Click on 'Developers'
3. Click on 'Documentation'
4. Click on 'Reference'
5. See error

or

1. Go to 'https://supabase.com/docs'
2. Select 'Reference'
3. See error

## Expected behavior

The link to "Guides" should actually no longer be highlighted in green when you have accessed the "Reference" page.

## Screenshots

![chrome-capture-2022-6-2](https://user-images.githubusercontent.com/30475783/176995484-b76bf68d-f68b-4842-a1b9-01cbecd0a188.gif)

## System information

- OS: Windows 10
- Browser: Google Chrome

## Additional context

If you access "https://supabase.com/docs/reference" directly, then switch back to "Guides", and then again to "Reference", this error does not occur.

**Comment by nerdjfpb** [comment]
Hi @Isaiah-Hamilton I am interested to take this.. Is anoyone else is working on this issue already?

**Comment by silentworks** [comment]
@nerdjfpb If there are no PRs on the issue then it's open for all.

**Comment by justinduplain** [comment]
@ChristianLutzCL I could be wrong, but looks like this is already corrected on the current dev build?

**Comment by ronakmistrydev** [comment]
@ChristianLutzCL
After spending enough time found out that it's an issue from `docusaurus`.
Code location - [click here](https://github.com/supabase/supabase/blob/master/web/docusaurus.config.js#L66)

**Comment by ChristianLutzCL** [comment]
@justinduplain I can't verify it, haven't cloned the repository. Or is there a dev build that can be accessed online?

**Comment by hkaur008** [comment]
I would love to give it a try. Can I handle this ?

**Comment by saltcod** [comment]
Hey all! This looks fixed with a bunch of changes we made this week. Marking as closed, but please let me know if this is still an issue. Thanks all!

**Comment by saltcod** [comment]
@hkaur008 if you're looking for something to work on, I'd be happy to help you find something. I'm saltcod (0824) on Discord.
