### ISSUE TITLE
Email in Invitation of Team Members is Case Sensitive.

### ISSUE THREAD

**Issue by peetzweg** [supabase/supabase#7550]
# Bug report

## Describe the bug

I just invited a bunch of team members to my supabase organisation, myself included. It seems I had used some capital letters when I signed up to GitHub. So the invitation of the all lowercase email arrived me but it did not match the email supabase expected, `invited_email != github_email`.

## To Reproduce

Invite a user into your supbase team and use some capital letters in place the user hasn't used in his GitHub account sign up mail.

## Expected behavior

Invited email address should be case insensitve.

## Screenshots

<img width="474" alt="Screenshot 2022-07-04 at 09 30 11" src="https://user-images.githubusercontent.com/839848/177105505-b88a5b41-3cee-4aeb-9adf-d1d646c34add.png">

<img width="574" alt="Screenshot 2022-07-04 at 09 33 42" src="https://user-images.githubusercontent.com/839848/177105477-b97ee44d-a2a4-4e28-9055-c3c4ef7036fe.png">

**Comment by jaysoni-ash42** [comment]
@kiwicopple 
this change should resolve the issue Bug 
<img width="844" alt="Screen Shot 2022-07-05 at 10 58 42" src="https://user-images.githubusercontent.com/68722497/177254308-32b831a1-1e13-4102-841b-90e239e28465.png">
any suggestion on that

**Comment by MildTomato** [comment]
@jaysoni-ash42 @peetzweg 

Yep, makes sense to lowercase all the inserted invited member emails.
We also need to do some backend changes to make sure they match properly.

feel free to PR that change above if you want to @jaysoni-ash42 🚀
