### ISSUE TITLE
[Feature] Prevent direct access to tables via REST but allow from functions

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase#7563]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to limit the amount a user can create based on his purchase status. 
I have to call another REST interface to get his status and for this I need to use PostgreSQL functions or Edge Functions since RSL Rules can't do http calls as far as I know.
 
My issue is someone could just call the PostgreSQL API directly and create as much as he wants.

I could create a PostgreSQL function with "superuser" rights but that feels like a workaround. I don't know if someone could abuse this even if I check for the passed user id there. We are getting the user id from the provided token right?

## Describe the solution you'd like

A setting for each table that prevents direct calls but allow calls from PostgreSQL functions or Edge Functions with the same configured RSL Rules applied.

There is no other way currently right? Is there a security concern with that PostgreSQL function and super user solution described above?

**Comment by w3b6x9** [comment]
@Sesa1988 if your users are `authenticated` then you can create RLS policies where you can query based on the `authenticated` user claims and check if that user has authorization to create.

Also, you mention RSL Rules a few times. What are RSL Rules?

**Comment by steve-chavez** [comment]
> My issue is someone could just call the PostgreSQL API directly and create as much as he wants.
> Prevent direct access to tables via REST but allow from functions

You can create a `private` schema and have your tables there and then only create functions in the `public` schema(here you can refer to tables in the `private` schema). You can see more details about this pattern [here](https://postgrest.org/en/stable/schema_structure.html#schema-isolation).

**Comment by Sesa1988** [comment]
> > My issue is someone could just call the PostgreSQL API directly and create as much as he wants.
> > Prevent direct access to tables via REST but allow from functions
> 
> You can create a `private` schema and have your tables there and then only create functions in the `public` schema(here you can refer to tables in the `private` schema). You can see more details about this pattern [here](https://postgrest.org/en/stable/schema_structure.html#schema-isolation).

Thats exactly what I need, thx.
