### ISSUE TITLE
Update specific filters' documentation to provide context to meanings and sample data

### ISSUE THREAD

**Issue by vincentjflorio** [supabase/supabase#7583]
Per: https://discord.com/channels/839993398554656828/993889903546998824

# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/contains
https://supabase.com/docs/reference/javascript/containedby

## Describe the problem

The current examples in the filter documentation seem to make assumptions about our knowledge of the nonexistence table they reference with their sample data/names. 

The topicality can be inferred somewhat, it's currently unclear what precisely the correlation is between the data being obtained from a column, and the column's relationship to that same data.

Additional confusion arises with specific filters like  "contains" and "containedBy"; they read as if they're opposites conceptually, but in the writing out of the function the placement of both the column and data to be filtered is (necessarily, for construction's sake) the same.

## Describe the improvement

I propose adding a visual frame of reference. If the non-existent table exists, I could see the data relationships and understand how each piece of data is acted upon, and/or how it is compartmentalized.

## Additional context

The PostgreSQL documentation has examples pages where they say in plain language how sidedness is handled when listing out different kinds of operations.  It may be useful, for the API functionality, to open each filter doc being abundantly clear in the same manner, i.e. "Contains takes the data and sees if the column contains it."

**Comment by charislam** [comment]
Hey @vincentjflorio, is this still a problem? I'm seeing the data source and response tabs, which I think contain the information you're looking for:

<img width="563" alt="image" src="https://github.com/supabase/supabase/assets/26616127/19b5a8c6-3ca2-40dc-ad8d-ac3f9ab8a197">

**Comment by vincentjflorio** [comment]
@charislam This was before that last major documentation update which provided a wealth of examples perfectly in line with what I was hoping to see. I apologize as I didn't realize this was still open. Please feel free to close and thanks for the effort and for checking in on it!
