### ISSUE TITLE
chore: color of hyper text should be different from normal text

### ISSUE THREAD

**Issue by yeganathan18** [supabase/supabase#7593]
# Bug report

## Describe the bug

The hyper text links on the supabase website aren't differentiable from the rest of the text in the line. We should consider changing the color of hyper text links so that it actually looks like a link. This would improve the UI as well as makes it easy to identify hypertext links vs normal text.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase's pricing page](https://supabase.com/pricing)
2. Scroll down to FAQs
3. Expand **Can I self-host supabase for free?** question
4. We can see a hypertext link, in the end of the sentence.

## Expected behavior

Hyper text link color should be different from normal text color.

## Screenshots

Dark mode:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63534555/177519542-dd5eddec-aa55-458a-8ab4-164abf85a3fb.png">

Light mode:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63534555/177519587-8bcb8f94-3d27-413e-8459-5dc487bccff7.png">

## System information

- OS: macOS
- Browser: Firefox

**Comment by Hallidayo** [comment]
This should have been fixed by #7247 but I can not see the `prose` class in the `master`. I can create another PR for this though?

**Comment by yeganathan18** [comment]
@Hallidayo, but still the issue persist 🤔
