### ISSUE TITLE
Chore: update the rest of the monorepo to use common assets

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#7599]
# Chore

## Describe the chore

Update the rest of the monorepo to use common assets.

## Tasks

- [ ] Find away to get favicons working fully
- [ ] Update the rest of the monorepo

**Comment by gracebir** [comment]
@Isaiah-Hamilton , what do you mean by `monorepo`? or can you list up the steps to reproduce please?

**Comment by arindam324** [comment]
if I'm not wrong you want to use assets from packages/common in all your apps in the ``monorepo``  correct ?

**Comment by Isaiah-Hamilton** [comment]
@arindam324 yes.
