### ISSUE TITLE
Dart SDK

### ISSUE THREAD

**Issue by sashvoncurtis** [supabase/supabase#76]
Congrats on the launch.🚀

Wanted to ask about what's on the horizon for future SDK's, especially for Dart/Flutter who use native Kotlin/Java and Swift/Obj-C apis.

**Comment by kiwicopple** [comment]
Thanks @sashvoncurtis 

We have a single thread for voting on client libraries here: https://github.com/supabase/supabase/issues/5

Dart is on there so I'll close this issue. Before I do:

> what's on the horizon for future SDK's

We let the crowd sway us! We don't internally have any techies who are familiar with Dart, but if there is enough interest, we can figure it out 👍

**Comment by phamhieu** [comment]
https://pub.dev/packages/postgrest

@sashvoncurtis you're welcome to try the new `postgrest` client written in Dart. You can use it with Supabase api

```dart
import 'package:postgrest/postgrest.dart';

var client = PostgrestClient("SUPABASE_API_ENDPOINT/rest/v1", {
  'headers': { 
    'apikey': 'SUPABSE_API_KEY',
  },
  'schema': 'public'
});

final response = await client.from('countries').select('*').order('name', true).end();
if (response['statusCode'] == 200) {
  print('Countries List: ${response['body']}.');
} else {
  print('Request failed with status: ${response['statusCode']}.');
}
```

**Comment by sashvoncurtis** [comment]
@phamhieu this is  awesome!  Will give it a try. Thanks  :)
