### ISSUE TITLE
void functions can no longer be invoked via `SupabaseClient.rpc()`

### ISSUE THREAD

**Issue by kopi-cloud** [supabase/supabase#762]
My `store_sentry_event` function used to be defined like this:
```
create or replace function public.store_sentry_event(json_content jsonb)
  returns void security definer
  language sql
as $$
  insert into private.sentry_event (received, content)
  values(transaction_timestamp(), json_content);
$$;
```

But I noticed that my code that calls that function directly via `SupbaseClient.rpc()` started failing with error:
```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

To get the code working, I've redefined my function like this:
```
create or replace function public.store_sentry_event(json_content jsonb)
  returns text security definer
  language sql
as $$
insert into private.sentry_event (received, content)
values(transaction_timestamp(), json_content);

select '';
$$
;
```

The code that calls the function via `rpc()` is here: https://github.com/kopi-cloud/cabbage/blob/main/app/src/Api/CabbageApi.ts#L140

Note also, that my direct REST API call that stored events was still working fine - so the problem seems to be a regression in the SupabaseClient code somewhere.

**Comment by kiwicopple** [comment]
Hey @kopi-cloud - this was fixed on `postgrest-js` v0.24.4: https://github.com/supabase/postgrest-js/pull/156

I Just released it on `supabase-js`:

https://github.com/supabase/supabase-js/releases/tag/v1.4.2
