### ISSUE TITLE
Bug: Dropdown menu in "Add a new function" is unreadable

### ISSUE THREAD

**Issue by Sulomus** [supabase/supabase#7620]
# Bug report

## Describe the bug
In the Supabase UI when configuring a new RPC function the dropdown menus are unreadable due to the bad color choice.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Supabase project
2. Click on Database
2. Click on Create new function

## Screenshots
![image](https://user-images.githubusercontent.com/49107150/177943553-fa7755ee-a360-486f-afea-a9dd63a9b202.png)

**Comment by aayushdura** [comment]
I'll Try to solve this

**Comment by pucho** [comment]
We can't reproduce this currently. Will reopen if this issue surfaces again.
