### ISSUE TITLE
DOCS: Tools doc links are broken on reference home page

### ISSUE THREAD

**Issue by burmecia** [supabase/supabase#7639]
# Improve documentation

The 2 Tool links for Auth and Connection Pool are broken on reference home page https://supabase.com/docs/reference.

## Describe the problem

![image](https://user-images.githubusercontent.com/19306324/178166676-b3d57a41-ce31-49ba-8663-55f548724474.png)

Those 2 links are Page not Found.

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/19306324/178166719-dbea572b-28b2-4656-ac40-e4cec6c8ab0a.png">

## Describe the improvement

Those 2 links should be correct.

## Additional context

Tested in both latest version of Chrome and Firefox.

**Comment by burmecia** [comment]
this issue is happening, not sure why it is still there.

**Comment by kiwicopple** [comment]
cc @burmecia - fixed above if you want to merge
