### ISSUE TITLE
unable to connect to the default project

### ISSUE THREAD

**Issue by nithinp02** [supabase/supabase#7641]
# Bug report

Unable to connect to the default project from the studio URL. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Using docker compose file, I am able to enable the studio and the related containers. I have updated the .env file as per the documentation.

I am unable to connect to the default project from studio URL. It showing as a loading page.

1. https://localhost:3000 
2. Click on default project
3. It showing as loading page. 

## System information

- OS: Linux
- Browser : chrome

**Comment by Hallidayo** [comment]
Hi @nithinp02,

Do you get any error logs? 

If you follow [this](https://blog.hijabicoder.dev/how-to-contribute-to-open-source-supabase-edition) great guide by @FatumaA and go to the 'Supabase Dashboard' section this should help you set up a local build of Supabase.

**Comment by kiwicopple** [comment]
Hey @nithinp02 - I wasn't able to duplicate this error. Here's what I did (from here https://supabase.com/docs/guides/hosting/docker):

```bash
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Start
docker-compose up
```

Then everything worked. Perhaps you have an old version of the `.env.sample` ? I'll close this one for now, but feel free to comment again if you have any problems

**Comment by quangtd95** [comment]
hi @kiwicopple , could you please provide your newest `.env.example`? I did the same thing https://supabase.com/docs/guides/hosting/docker but still got the same issue with @nithinp02

**Comment by kiwicopple** [comment]
sure, it's just this one: https://github.com/supabase/supabase/blob/master/docker/.env.example

**Comment by quangtd95** [comment]
yep, thanks @kiwicopple , I also used that .env file
This issue has been fixed by https://github.com/supabase/supabase/pull/7824. 
what I need to do is to run `docker-compose pull` again. (to get the latest studio image)
