### ISSUE TITLE
Multiple unique constrain UI bug

### ISSUE THREAD

**Issue by joseg157** [supabase/supabase#7653]
# Bug report

## Describe the bug
Tables do not display multiple unique constraints seems like there is a UI problem. 

## To Reproduce

// UI bug
CREATE TABLE example (
    a integer,
    b integer,
    c integer,
    UNIQUE (a, c)
);

## Expected behavior

Doesn't seem the unique constraint is checked for the table example.
 
## Screenshots

![image](https://user-images.githubusercontent.com/49816028/178391554-848cd467-f36c-4c23-b33e-caa678563137.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

Note: The UNIQUE constraints do work as expected when attempting to insert values for the table examples.

**Comment by kiwicopple** [comment]
This one is related: https://github.com/supabase/supabase/issues/7560

So I will close this in favor of that one!
