### ISSUE TITLE
Deleting table: confirm by typing table name

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#767]
# Feature request
When deleting a table, prompt to type the table name to delete it. Not sure if you want to make it really strict by disallowing copy&paste.
Other things you could do:
- make button and/or title of the dialog red
- rename "OK" to more explicit "Delete"
![image](https://user-images.githubusercontent.com/47209189/108827277-53cacb00-75bd-11eb-8037-358e270132af.png)

UPDATE: relates to another point where IMHO it would be better to keep the Table editor purely for editing data and allow DDL only under Database. The above still applies though.

**Comment by MildTomato** [comment]
@peachp great suggestion.

**Comment by awalias** [comment]
the button is now bright red, marking as fixed, reopen as needed
