### ISSUE TITLE
Support for bun.js runtime

### ISSUE THREAD

**Issue by luquitared** [supabase/supabase#7672]
Hi! It would be awesome if supabase supported this new speedy runtime. 

I've attempted to see if it will run, but it does not. 

My file is basic:
``` javascript
import { createClient } from "@supabase/supabase-js"

const supabaseUrl = process.env.SUPABASE_URL
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
```

After, I ran and received this:
``` bash
➜  myproject git:(main) ✗ bun run test.ts
[0.06ms] ".env"
1 | // constants.ts
2 | import { version } from './version';
   ^
 ReferenceError: Can't find variable: require
at ..../node_modules/@supabase/supabase-js/dist/module/lib/constants.js:2:0
```

cheers

**Comment by kiwicopple** [comment]
hmm, perhaps this is a bun issue, rather than a supabase issue? If there is a (non-breaking) change that we can make, then we'd happy to consider it

I'll close this for now, but feel free to comment and I can re-open 👍

**Comment by plgingras88** [comment]
Now that Bun has reached its stable 1.0 release, I'm pondering its relevance. Given the numerous benefits Bun offers compared to the challenges posed by Deno, it might be worth considering. 

While the situations might not be directly comparable, it's noteworthy that Vercel began supporting Bun just a day after the community expressed the need. Notably, it became their most popular open issue on record, which likely expedited their response. I believe Supabase could potentially leverage this hype, as it aligns with their core philosophy.

**Comment by retticle** [comment]
I would love to use Bun for edge functions!

**Comment by this-is-allan** [comment]
GO BUN

**Comment by Geczy** [comment]
wait i can't use supabase with bun? noooo i just finished migrating

im getting undefined errors in my app when subscribing to realtime

**Comment by nicolaswehmeyer** [comment]
+1 on this one. Just testing the migration of a Nuxt3 based app from Node to Bun and it has been flawless so far. Unfortunately, the app breaks as soon as I load Supabase.

```500
Cannot find module './lib/websocket' Require stack: - /Users/user/Developments/my-app/websocket
at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
at Module._load (node:internal/modules/cjs/loader:905:27)
at Module.require (node:internal/modules/cjs/loader:1127:19)
at require (node:internal/modules/helpers:112:18)
at ./websocket:1:18
at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:341:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:197:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:231:12)
at async ./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js:1:31```

**Comment by DevDengChao** [comment]
@kiwicopple Can you re-open this issue now ?

**Comment by mannyyang** [comment]
Getting the same error as well

**Comment by ovidb** [comment]
@kiwicopple small nudge in case you missed the above 😅

We use Bun quite extensively and we would love to see it being supported in Supabase. There are so many good things in Bun I wouldn't even know where would I start an argumentation of why it would be a a good idea to support it but probably the best one I could make is the small memory footprint and speed of execution, which at the end of the day it means getting more done with less $ => happy users!

**Comment by KazimirPodolski** [comment]
I had a small week-long project in Supabase (which has been running for the client for months), but I'm going to advice my current company **against Supabase** in the future:
* Deno literally has negative productivity creating even more problems than Node with few questionable improvements. Supabase is locked-in with Deno
* Supabase team is unresponsive to it's community, as illustrated in this issue (and others)

**Comment by C0DE-IN** [comment]
is there any  update for bun suppot ?

**Comment by lafllamme** [comment]
knock knock?

**Comment by Geczy** [comment]
bunjs ded

**Comment by KazimirPodolski** [comment]
@Geczy what you mean?

**Comment by Geczy** [comment]
this requires https://github.com/oven-sh/bun/issues/6080 to be solved but it goes without any comment

https://github.com/oven-sh/bun/pull/5972#commits-pushed-3bc265f

**Comment by Jarred-Sumner** [comment]
I think it's likely that supabase works?

Here is a (correct) error which means it was able to send requests as expected:
```js
4 | class AuthError extends Error {
  5 |     constructor(message, status, code) {
  6 |         super(message);
              ^
  AuthApiError: Anonymous sign-ins are disabled
   code: "anonymous_provider_disabled"
  
        at new AuthError (/Users/jarred/Desktop/node_modules/@supabase/auth-js/dist/main/lib/errors.js:6:9)
        at new AuthApiError (/Users/jarred/Desktop/node_modules/@supabase/auth-js/dist/main/lib/errors.js:20:9)
        at /Users/jarred/Desktop/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:63:11
  ,
  }
```
For the following code:
```ts
import { createClient } from "@supabase/supabase-js";

const url = "<redacted>";
const secret = "<redacted>";

export const supabase = createClient(url, anon);

const user = await supabase.auth.signInAnonymously({});
console.log(user);
```
