### ISSUE TITLE
GUI inputs for editing a table column name break after value is a specific length

### ISSUE THREAD

**Issue by blumenthaler** [supabase/supabase#7673]
# Bug report

## Describe the bug
When attempting to add a longer Column name to a Table in the Supabase GUI, you are no longer able to see your full input value, nor the last trailing characters of that value.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a Supabase project
2. Click on 'Table Editor' -> 'New table'
3. Click on 'Add column'
4. Type in a long column name
5. See error

## Expected behavior

On input focus, you should be able to see the end of your input, as well as your caret. 

## Screenshots

https://user-images.githubusercontent.com/66443006/178773488-8a35e08c-881b-489d-937e-8986afde6341.mov

## System information

- OS: macOS
- Browser: chrome

**Comment by Hallidayo** [comment]
Can I be assigned to this one please?

**Comment by mansueli** [comment]
CC @supabase/frontend-team

**Comment by kiwicopple** [comment]
yes please @Hallidayo !
