### ISSUE TITLE
Table editor and Database stuck at "Loading tables..." after duplicating a table

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#768]
# Bug report
In Table editor, duplicated a table without rows, "Loading tables..." appeared and after a while (1min or so) changed to "Error".
In Database section also showed "Loading tables..." but changed to "Error loading tables undefined" after a while.

Tried to reload, drop the duplicated table, re-login, no luck. Then, after a while I reloaded again and it looks OK now.

Tried to replicate, but haven't managed to.

**Comment by kiwicopple** [comment]
Likely this was caused by this issue: https://github.com/supabase/realtime/issues/125

Wenbo just fixed it though, and we'll roll it out this week
