### ISSUE TITLE
domainRegex does not support symbols or wildcards

### ISSUE THREAD

**Issue by jchekanoff** [supabase/supabase#7691]
# Bug report

## Describe the bug

The [Auth.constants.ts](https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Auth/Auth.constants.ts) file has `domainRegex`, which doesn't allow for `*` or `-`, two common symbols used for Vercel and wildcard domains.

## To Reproduce

Visit the new interface for adding Redirect urls and attempt to add, for example: `https://my-test.com`. It will be rejected, as well as `https://my*.test.com`

## Expected behavior

Both values should be accepted.

## Screenshots

<img width="516" alt="image" src="https://user-images.githubusercontent.com/28504852/179013240-0746fe11-69df-4168-abeb-22271d47647d.png">

**Comment by sebastianpennino** [comment]
I'm having the same issue. Just commenting to be notified of any progress.

**Comment by MildTomato** [comment]
Fix on the way

**Comment by MildTomato** [comment]
fix on the way to prod
