### ISSUE TITLE
Can't submit a help request to the support team

### ISSUE THREAD

**Issue by sebastianpennino** [supabase/supabase#7696]
# Bug report

## Describe the bug

**Users can't submit a help request to the support team.**

## To Reproduce

Steps to reproduce

1- Log in to your supabase account,
2- Go to the "Help Button" > "Contact support"  (see screenshot below)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1806825/179100806-08aa84ad-de86-48e5-a85c-cca30879b20c.png">

Then fill out the report, and hit the "Sent support request"

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1806825/179100931-d5c2a95c-ed8a-4ce6-a812-ad833a7a38f4.png">

**It doesn't work.**

## Expected behavior

I should be able to contact support

## System information

- OS: macOS,
- Browser (if applies) chrome

## Additional context

I wanted to report another bug and I found this bug while doing it so.

**Comment by MildTomato** [comment]
we've just fixed this, fix already in staging.
fix going into prod shortly. closing this for now.

**Comment by MildTomato** [comment]
thanks for @sebastianpennino reporting 💯
