### ISSUE TITLE
Specify that a column should be unique

### ISSUE THREAD

**Issue by churichard** [supabase/supabase#770]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to have the ability to specify that a column should be unique. This is a standard feature of Postgres, but I don't see a way to do this in Supabase Admin.

## Describe the solution you'd like

When adding or editing a column in Supabase, there should be a checkbox that allows you to specify whether the column should be unique or not.

**Comment by kiwicopple** [comment]
good one @churichard - starting an issue here: https://github.com/supabase/postgres-meta/issues/100

Once this is done we can add it to the dashboard

**Comment by joshenlim** [comment]
Super late update to this issue, but we've got support on the dashboard to opt for a column to be unique!
![image](https://user-images.githubusercontent.com/19742402/166671780-a751222e-816c-4c61-b03f-ac0c870a0435.png)

**Comment by jdgamble555** [comment]
The `is Unique` option is not available when you go to edit the Table under `Database`, but it is available when you create a table or when you edit a table in `Table Editor` individually for some reason.

J

**Comment by Tanktiger** [comment]
I've found the Is Unique checkmark under Database -> Tables -> "Press Edit on Column". Thanks to @jdgamble555 I've checked the Database menu point because I did not find the option in the table editor

**Comment by Falci** [comment]
And how to make 2 columns unique?

**Comment by emillinden** [comment]
> And how to make 2 columns unique?

This is missing from the UI as far as I'm aware.
Use this query instead:
```sql
ALTER TABLE table_name
ADD UNIQUE (column_name_1, column_name_2)
```

**Comment by shahsuvarli** [comment]
> > And how to make 2 columns unique?
> 
> This is missing from the UI as far as I'm aware. I used this instead:
> 
> ```sql
> ALTER TABLE table_name
> ADD UNIQUE (column_name_1, column_name_2)
> 
> -- OR
> 
> CREATE UNIQUE INDEX index_name
> ON table_name(column_name_1, column_name_2);
> ```

Where did you use this code? I mean can we reach to the initial code and modify it?

**Comment by gerazenobi** [comment]
If it helps anyone: you can use the SQL editor like so:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/f9caacc2-7b92-4f26-b577-0c3bf08864dc" />

I arrived there from the create indexes view which does allow to create multi column indexes:

<img width="1438" alt="Image" src="https://github.com/user-attachments/assets/b28e2b94-98bd-4726-9590-52cc16fc6d50" />
