### ISSUE TITLE
www README.md out of date. 

### ISSUE THREAD

**Issue by Keoooo** [supabase/supabase#7715]
# Improve documentation

## Link 

[README.md](https://github.com/supabase/supabase/tree/master/apps/www)

## Describe the problem

-Documentation on getting supabase www localhost running is out of date.
-npm run dev needs to be run at the root repo now.
-Also the link "Developers Guide" in the README.md goes to a 404

## Describe the improvement

Update the README.md on how to get www running on local 
Add a new link 

<img width="1080" alt="Screenshot 2022-07-16 at 09 43 30" src="https://user-images.githubusercontent.com/33136365/179324983-383589ff-c8c3-4f96-80e7-ba767a4b2152.png">

**Comment by Keoooo** [comment]
if anyone has the new link location I can make a pr to correct this issue :Da

**Comment by Keoooo** [comment]
> if anyone has the new "Developers Guide" location. I can make a pr to correct this issue 😄.

DM Found the file

**Comment by kiwicopple** [comment]
fixed by @Keoooo here! https://github.com/supabase/supabase/pull/7716
