### ISSUE TITLE
Error: Migration failed. Reason: An error occurred running 'pathtoken-column'.

### ISSUE THREAD

**Issue by koetjeengdjalanan** [supabase/supabase#7736]
I am trying to deploy supabase on my private server but **supabase-storage** image is failed to build. This cause other three image to failed alongside in my side.

This is the result of docker image logs for:

- supabase-storage
```
running migrations
(node:6) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: schema "storage" does not exist
    at /snapshot/storage-api/node_modules/postgres-migrations/dist/migrate.js:63:27
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /snapshot/storage-api/node_modules/postgres-migrations/dist/with-lock.js:25:28
(Use `storage-api-x86_64 --trace-warnings ...` to show where the warning was created)

```

- supabase-auth
```
time="2022-07-12T14:34:19Z" level=fatal msg="running db migrations: Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to `host=db user=postgres database=postgres`: dial error (dial tcp 172.22.0.2:5432: connect: connection refused)"
[POP] 2022/07/12 14:34:19 info - 0.0294 seconds
[POP] 2022/07/12 14:34:20 info - 0.0442 seconds
time="2022-07-12T14:34:20Z" level=fatal msg="running db migrations: Migrator: problem creating schema migrations: CREATE TABLE \"schema_migrations\" (\n\"version\" VARCHAR (14) NOT NULL\n);\nCREATE UNIQUE INDEX \"schema_migrations_version_idx\" ON \"schema_migrations\" (version);: ERROR: no schema has been selected to create in (SQLSTATE 3F000)"

```

- supabase-realtime
```
2022-07-12 14:34:21.858 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :realtime, Realtime.RLS.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "realtime" does not exist
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
```

- supabase-kong
```
2022/07/12 14:34:18 [warn] 1#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
2022/07/12 14:34:18 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:490: error parsing declarative config file /var/lib/kong/kong.yml:
/var/lib/kong/kong.yml: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:490: in function 'init'
	init_by_lua:3: in main chunk

```

And here I think i already do all from wiki as it's written. Can someone help me? .env file is as closely as the example.

**Comment by Antony-Jia** [comment]
> Hey @koetjeengdjalanan - I'm not able to replicate this one. could you share a few steps on how we can reproduce this error?

I met same questions. By docker-compose.yml like this.
`version: "3.8"

services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:latest
    restart: unless-stopped
    ports:
      - ${STUDIO_PORT}:3000/tcp
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      SUPABASE_URL: http://kong:8000
      SUPABASE_REST_URL: ${PUBLIC_REST_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}

  kong:
    container_name: supabase-kong
    image: kong:2.1
    restart: unless-stopped
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
    volumes:
      - ./volumes/api:/var/lib/kong

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.10.0
    depends_on:
      - db # Disable this if you are using an external Postgres database
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?search_path=auth

      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}

      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE}

      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v9.0.0
    depends_on:
      - db # Disable this if you are using an external Postgres database
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"

  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v0.22.4
    depends_on:
      - db # Disable this if you are using an external Postgres database
    restart: unless-stopped
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v0.10.0
    depends_on:
      - db # Disable this if you are using an external Postgres database
      - rest
    restart: unless-stopped
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGOPTIONS: -c search_path=storage,public
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      # TODO: https://github.com/supabase/storage-api/issues/55
      REGION: stub
      GLOBAL_S3_BUCKET: stub
    volumes:
      - ./volumes/storage:/var/lib/storage

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.29.0
    depends_on:
      - db # Disable this if you are using an external Postgres database
    restart: unless-stopped
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: ${POSTGRES_HOST}
      PG_META_DB_PORT: ${POSTGRES_PORT}
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: ${POSTGRES_USER}
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  # Comment out everything below this point if you are using an external Postgres database
  #db:
  #  container_name: supabase-db
  #  image: supabase/postgres:14.1.0.21
  #  command: postgres -c config_file=/etc/postgresql/postgresql.conf
  #  restart: unless-stopped
  #  ports:
  #    - ${POSTGRES_PORT}:5432
  #  environment:
  #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #  volumes:
  #    # - ./volumes/db/data:/var/lib/postgresql/data
  #    - ./volumes/db/init:/docker-entrypoint-initdb.d

  db:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/init:/docker-entrypoint-initdb.d`

**Comment by Antony-Jia** [comment]
My postgresql contianer is lack of someting. I just do like this:
1.modify localhost VM address
2.modify POSTGRES_HOST TimescaleDB(my postgresql) address
3.add extension pgjwt
4.sudo apt-get install postgresql-14-wal2json in my postgresql

**Comment by Antony-Jia** [comment]
I find https://github.com/supabase/realtime/issues/231 and it's OK

**Comment by yusuf-khamis** [comment]
Am currently encountering this, pretty frustrating to know you've done everything right, followed the wiki to the latter and still having some errors poping up, did you manage to figure this one out?

**Comment by kiwicopple** [comment]
It looks like @Antony-Jia disabled logging like this:

https://stackoverflow.com/questions/66215102/disable-logging-of-logical-replication-statements-in-postgres-13-1

Let us know if that helps

**Comment by itisnajim** [comment]
@Antony-Jia what you did exactly, can u share the steps please ?

**Comment by Antony-Jia** [comment]
> @Antony-Jia what you did exactly, can u share the steps please ?

Whe you use self-host postgresql ( like timescaledb ) with supabase, if you met some error like lack of pgjwt, you can install it in you self-host envirment.
if you just hate the lots of logs, you can set log_min_messages = fatal in postgresql.conf.
It's better to disable realtime function and log will not show.
You can see more detail #231 (Bug: postgresql.conf is full of queries)

**Comment by itisnajim** [comment]
No realtime = No(t a) Firebase alternative,
i'll try limits the logs as describing in your post.

**Comment by sweatybridge** [comment]
I will close this issue as fixed. If you are using custom postgres images like `timescale/timescaledb-ha:pg14-latest`, remember to run migrations to setup initial schemas. These are open sourced in our [postgres repo](https://github.com/supabase/postgres/tree/develop/migrations).

The realtime logs are now suppressed by default https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L197.

**Comment by BonsoirDiep** [comment]
in my case: 
```bash
sudo nano /var/lib/docker/overlay2/<...>/diff/usr/local/etc/auth/migrations/20221208132122_backfill_email_last_sign_in_at.up.sql
```

change
```sql
-- previous backfill migration left last_sign_in_at to be null, which broke some projects

update {{ index .Options "Namespace" }}.identities
  set last_sign_in_at = '2022-11-25'
  where
    last_sign_in_at is null and
    created_at = '2022-11-25' and
    updated_at = '2022-11-25' and
    provider = 'email' and
    id= user_id::text;
```
to:
```sql
-- previous backfill migration left last_sign_in_at to be null, which broke some projects

update {{ index .Options "Namespace" }}.identities
  set last_sign_in_at = '2022-11-25'
  where
    last_sign_in_at is null and
    created_at = '2022-11-25' and
    updated_at = '2022-11-25' and
    provider = 'email' and
    id::text = user_id::text;
``
