### ISSUE TITLE
Policy Editor will not allow removal of role.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#7740]
# Bug report

## Describe the bug

If you create a policy using the new role input field and then later edit the policy and set the role to none (for all roles) an error occurs.

![image](https://user-images.githubusercontent.com/54564956/179422002-061a5e24-8b7e-4c88-94a7-ffdfbd4f24fd.png)

## To Reproduce

Create a policy with anon as role and true as expression. 
Save policy.
Edit the policy and check the x next to anon to go back to default role setting of none selected.
Review and attempt to save.
Error occurs.

## Expected behavior

Should be able to set roles back to default of all.

## Additional context

Work around is to delete the policy and start over.

**Comment by plasmatech8** [comment]
```sql
BEGIN;
  ALTER POLICY "Enable read access for all users" ON "public"."smoothies" TO public;
COMMIT;
```
Missing the `USING (true)` block?
