### ISSUE TITLE
No way to change settings during local development

### ISSUE THREAD

**Issue by ARMATAV** [supabase/supabase#7741]
# Bug report

## Describe the bug

No way to change the local settings when developing with `supabase start` in Docker.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `supabase start`
2. Navigate to http://localhost:54323/project/default/settings/general
3. You're bumped back to the homepage

## Expected behavior

You should be able to modify the settings like you are able to in production. Otherwise, you can't expose extra schemas/change JWT expiration time etc.

## Screenshots

`local`
<img width="464" alt="image" src="https://user-images.githubusercontent.com/2433203/179424218-e014e0d1-a209-403f-8041-5298ee9083e6.png">
`hosted`
<img width="314" alt="image" src="https://user-images.githubusercontent.com/2433203/179424257-b1f0b676-734a-4207-acc1-abb73acb95b3.png">

**Comment by MildTomato** [comment]
I think we had a similar issue raised.
@kiwicopple responded to it [here](https://github.com/supabase/supabase/issues/7665#issuecomment-1185783680)

**Comment by ARMATAV** [comment]
Maybe I'm missing something in that link and the sublinks - but there are Supabase-specific configurations that are not available to modify via envars passed to the container, thinks like the available schemas to generate the API documentation from - or am I just missing it?

**Comment by kiwicopple** [comment]
Hey @ARMATAV - I think you're looking for this one? https://github.com/supabase/supabase/blob/97b0e4653256c37415a523839f6ee7bd7671722d/docker/docker-compose.yml#L88


All of the tools settings exist, we just haven't added everything to the `.env` file. If you want to add even more env vars for the API to the docker-compose file, you can find all of the available options here: https://postgrest.org/en/stable/configuration.html

**Comment by kiwicopple** [comment]
I'll close this one for now, but feel free to comment if you get stuck! In general, I think we need to add all the configuration options to our own docs so that this is more discoverable for developers like yourself - I will keep the other issue open so that we can track that task

**Comment by ARMATAV** [comment]
> I'll close this one for now, but feel free to comment if you get stuck! In general, I think we need to add all the configuration options to our own docs so that this is more discoverable for developers like yourself - I will keep the other issue open so that we can track that task

Hey @kiwicopple - do I need to clone the repo and then manually add in `SMTP_USER=` and `SMTP_PASS=` in order to get the email verification to fire off locally? Or is there a way to pass in an override via the `supabase start` command, kind of like how `docker-compose` takes overrides?

https://github.com/supabase/supabase/issues/4656

**Comment by ARMATAV** [comment]
Oh well, nevermind - I just didn't realize my CLI was outdated, that issue was fixed at https://github.com/supabase/cli/commit/2ce0956457486ffb08a0bd65502bc3e2e7f5f3ae
