### ISSUE TITLE
Names must be lower case in SQL editor

### ISSUE THREAD

**Issue by Program4GitHub** [supabase/supabase#776]
I have a column with the name of 'gameID'.
When I write in the SQL editor (that is inside the client at [app.supabase.io](url)) the following query:
`SELECT gameID FROM table`
I get the following error:
> Error: Run query failed (column "gameid" does not exist)

The same happens if I create a table with upper case letters (for instance, 'Games').

**Comment by kiwicopple** [comment]
Hey @Program4GitHub can you try `SELECT "gameID" FROM table` with double-quotes?

This is specific to postgresql - you need to include quotes if you use uppercase

**Comment by Program4GitHub** [comment]
Thank You very much. It worked! 😄
