### ISSUE TITLE
supabase subscriptions not working

### ISSUE THREAD

**Issue by shini-tm** [supabase/supabase#7771]
# Bug report

## Describe the bug

Whilst running a script that is "subscribed" to the table. On inserting values directly into the table through app.supabase the event is not shown.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create project -> create new table -> set "Enable Realtime"
2. Copy project url and project api key (anon public) from settings > api
3. Here is simple script that creates subscription:
```
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = "...supabase.co" //project_url
const supabaseAnonKey = "xxx.xxx.xx-xxx" //project api key (anon public)
const supabase = createClient(supabaseUrl, supabaseAnonKey)

const mySubscription = supabase
  .from('*')
  .on('*', payload => {
    console.log('Change received!', payload)})
  .subscribe()

```
4. run script (`node test.js`)
5. insert new row into table
## Expected behavior

I would expect to see a print statement consisting of the newly inserted value into the table.

## System information

- OS: Windows
- Browser (if applies): firefox
- Version of @supabase/supabase-js: ^1.35.4 (?)
- Version of Node.js: v17.8.0

## Additional context

I'm sure the client is connecting because i can pull all the data using:
```
async function seeAllData(){
  const { data: sales_data } = await supabase.from("test-table").select("*")
  console.log("SALES DATA:", sales_data)
}

```
RLS is disabled. And looking at the replication section in databases, everything is toggled on. 
I feel like theres something simple I'm overlooking but I can't figure out what.

**Comment by mdibaiee** [comment]
We are experiencing the same issue. Subscriptions are not working today specifically, they have been working until yesterday as our graphs show:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/2807772/179780065-00c345c0-1981-45e4-86a8-59b4e0d1a6fa.png">

**Comment by shini-tm** [comment]
It seems to be working so I shall close the issue. It'd be cool to know what to troubleshoot to figure out if the same issue might happen be the cause in the future.

**Comment by shini-tm** [comment]
🤔 seems to only run from my javascript file. If I try to use the code snippet in a fresh nextjs project I don't receive any updates:

```
import supabase from '../utils/supabaseClient'

export default function Home() {
  //fetch updates
  useEffect(() => {
    const mySubscription = supabase
      .from('*')
      .on('*', (payload) => {
        console.log('Change received!', payload);
      })
      .subscribe();
  }, []);

  return (
    <div>...</div>
  )
}

```

**Comment by w3b6x9** [comment]
> @shini-tm Unfortunately this does not appear to be working. It's quite serious, as it's breaking a major workflow through our app.
> 
> When attempting to subscribe, I see the following in the browser's websocket connection logs:
> 
> ```json
> {"event":"phx_reply","payload":{"response":{"reason":"join crashed"},"status":"error"},"ref":"1","topic":"realtime:public:discovers:draft_id=eq.06:c7:cd:01:f6:f0:34:00"}
> ```
> 
> It looks like there should be logs of the crash reason somewhere, but I won't have access to those. https://github.com/phoenixframework/phoenix/blob/1636787952c736816312387222347770c9228f38/lib/phoenix/channel/server.ex#L42-L49
> 
> This is quickly reproducible on our side when using Supabase Cloud, but not when running Supabase locally.
> 
> We are using subscriptions with RLS, so we thought it might be related to [supabase/realtime#265](https://github.com/supabase/realtime/issues/265), but it appears that our schema is up to date with what is discussed in that thread.

@saterus I think you reached out via support ticket and we resolved it for you. There's an issue in the latest Realtime version (multi-tenancy) where we're splitting by `:` which obviously broke based on your filter value.

**Comment by shini-tm** [comment]
Nicely done. I guess its a seperate issue then. From the websocket connection logs I am seeing the events:
`{"event":"INSERT","payload":{"columns":[{"name":"id","type":"int8"},{"name":"last_fetched_timestamp","type":"text"},{"name":"listing_price","type":"float8"},{"name":"listing_timestamp","type":"text"}],"commit_timestamp":"2022-07-19T17:01:27Z","errors":null,"record":{"id":41,"last_fetched_timestamp":null,"listing_price":null,"listing_timestamp":null},"schema":"public","table":"feet-and-eyes-guys","type":"INSERT"},"ref":null,"topic":"realtime:public"}`
but its not printing in the console nor can i assign it to anything.

**Comment by shini-tm** [comment]
Turning off strict mode in react/nextjs appears to fix the issue. thanks to "Recognized" and @GaryAustin1 on the supabase discord

**Comment by GaryAustin1** [comment]
Just to clarify on the strict mode...  What I think several users have encountered with react useEffect, where they subscribe and unsubscribe on cleanup, is that running the useEffect a second time causes a timing issue.  The subscribe starts up correctly then the useEffect gets called again so launches the cleanup routine and sends a close subscription to the server, meanwhile the "new" subscription starts up, but sees the close coming back from the server from the first subscription and closes everything on realtime-js side.

**Comment by Jannchie** [comment]
> Turning off strict mode in react/nextjs appears to fix the issue. thanks to "Recognized" and @GaryAustin1 on the supabase discord

@shini-tm Thanks for your information. It is helpful.

I think this issue should not be close, because turning off strict mode is not a elegant solution.

**Comment by shini-tm** [comment]
It was working for a good few hours, but now that I run the tests again, it seems to have stopped working.

**Comment by shini-tm** [comment]
> > Turning off strict mode in react/nextjs appears to fix the issue. thanks to "Recognized" and @GaryAustin1 on the supabase discord
> 
> @shini-tm Thanks for your information. It is helpful.
> 
> I think this issue should not be close, because turning off strict mode is not a elegant solution.

Happy to help :D Yeah thats true, i closed it because the ticket wasn't really specific to nextjs and the script did seem to run after the fact. well until now anyway

**Comment by shini-tm** [comment]
@Jannchie are you using a VPN by any chance. I think that might have something to do with it. Idky but re-enabling reactStrictMode but disabling my VPN appears to work.

**Comment by shini-tm** [comment]
> @Jannchie are you using a VPN by any chance. I think that might have something to do with it. Idky but re-enabling reactStrictMode but disabling my VPN appears to work.

actually i think it was support team that switched off:
![image](https://user-images.githubusercontent.com/31591116/180078135-022ec417-b6fa-444c-b25d-6d29ea14444f.png)
![image](https://user-images.githubusercontent.com/31591116/180078198-7784ce13-7945-4019-b940-fe4d759dff9e.png)

**Comment by TuanManhCao** [comment]
> Strict mode causes the useEffect to run twice, similar to a former issue where the user switched pages each with the same useEffect subscription a month or so ago.

This help me save a ton of time. I also feel that current document is a bit of lacking. 

Thanks so much!

**Comment by kandros** [comment]
This is definitely not fixed

**Comment by GaryAustin1** [comment]
This is another issues with the solution mentioned...
https://github.com/supabase/realtime-js/issues/169
The fix appears only to be in v2 client code.
