### ISSUE TITLE
Upload CSV (144k records) server response error

### ISSUE THREAD

**Issue by gomflo** [supabase/supabase#778]
Im trying to upload a csv with 144k records but im getting the following error:

![image](https://user-images.githubusercontent.com/141670/109339018-a3fb9480-782c-11eb-90d5-19a65bfa9ae4.png)

![image](https://user-images.githubusercontent.com/141670/109339433-44ea4f80-782d-11eb-9aaa-205d45291f93.png)

**Comment by kiwicopple** [comment]
Thanks for the bug report @gomflo - we'll have to try replicate this with a similar size file. Question: can you tell us how large this is (in Mb)?

I'm guessing the API didn't like ingesting that much data - I'll have to double-check we're handling it in a single transaction

**Comment by gomflo** [comment]
> Thanks for the bug report @gomflo - we'll have to try replicate this with a similar size file. Question: can you tell us how large this is (in Mb)?
> 
> I'm guessing the API didn't like ingesting that much data - I'll have to double-check we're handling it in a single transaction

Around 70mb its a file with many columns.

**Comment by arredond** [comment]
Hey there! Any news on this one? I'm having a similar problem with a similar number of rows (~130k) but smaller in size, just under 10 MB (only 6 columns).

I've tried monitoring the POST request in the network tab but the error is just as succinct as in the website: "An invalid response was received from the upstream server".

On a related note, is there a recommended way of uploading larger amounts of data? The file I'm testing with is actually just a chunk of my full CSV, which is about 200 MB but totals 2 million rows.

I'm not sure how the upload process is implemented but, just for reference, my previous employer had a similar process of uploading CSVs into Postgres tables and reached a pretty efficient solution (files of over 1GB were allowed): https://carto.com/blog/sql-api-copy/

**Comment by arredond** [comment]
Lil' update/workaround: I was able to upload the data directly using the DB connection info found in the Settings > Database page (awesome detail, btw). In my case, I wanted to upload data I already had in a Pandas DataFrame in Python so it was just as simple as:

```python
conn_string = 'postgresql://postgres:...'
engine = create_engine(conn_string)

df.to_sql('my_table', engine, if_exists='append', method=psql_insert_copy)
```

This was pretty fast, especially due to the fact that it was using Postgres' built-in COPY FROM functionality (see [here](https://pandas.pydata.org/docs/user_guide/io.html#io-sql-method) for more details on the `psql_insert_copy` part). It took about 5 minutes to upload all 2M+ records which wasmore than good enough :)

**Comment by gomflo** [comment]
Ended up using TablePlus -> Import CSV and it works pretty well.

**Comment by joshenlim** [comment]
hey everyone! we've improved the CSV import [last month](https://supabase.io/blog/2021/09/10/supabase-beta-august-2021) and should be able to handle huge files now :) Do give it a go and let us know if you do run into any issues. I'll be closing the ticket for now but feel free to reopen.
