### ISSUE TITLE
Dismiss error toast upon clicking "close" button instead of automatically dismissing it

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#779]
# Feature request

## Is your feature request related to a problem? Please describe.

<img width="1382" alt="Screen Shot 2021-02-27 at 7 41 29" src="https://user-images.githubusercontent.com/18113850/109363340-af53cc00-78cf-11eb-997d-f905fb3942f6.png">

This error toast dismiss pretty quickly often before I fully read and understand the error. People might want to copy and paste the error to google it. 

## Describe the solution you'd like

I think it would be better to either make the visible time longer, or make it so that it would stick around until the user manually dismiss it. 

## Additional context

I would like to hear other people's opinion around this!

**Comment by kiwicopple** [comment]
Agreed on this one @dshukertjr  - I think we will build some toasts into https://github.com/supabase/ui

**Comment by awalias** [comment]
the toasts now stay around for much longer, marking as fixed, reopen as needed
