### ISSUE TITLE
Unable to create or invite new user | "relation "public.users" does not exist"

### ISSUE THREAD

**Issue by ChristianLutzCL** [supabase/supabase#7834]
# Bug report

## Describe the bug

As of today, it is no longer possible to create a new user. No matter if via API or by 'invite' in the authentication dashboard.
The postgres logs shows the following error, which I interpret as if the actual table 'auth.users' is searched in 'public'.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Authentication'
2. Click on ' Invite'
3. Add email
4. Click on 'Invite user'
5. See error

## Expected behavior

New User will be created.

## Screenshots

![2](https://user-images.githubusercontent.com/30475783/180215507-21ff996d-db9a-47f7-8c51-27f3dcd5f473.PNG)
![3](https://user-images.githubusercontent.com/30475783/180215581-31246b03-75ea-456a-9f99-8f842f288d7e.PNG)

## System information

- OS: Windows
- Browser: Chrome

**Comment by ChristianLutzCL** [comment]
I have now tested it briefly in a second project.
There the error does not occur.

Is there a workaround for this error?

**Comment by GaryAustin1** [comment]
Do you have a trigger function on your auth.users table?  The error is complaining about a public.users table....

**Comment by ChristianLutzCL** [comment]
@GaryAustin1 

Can you give me a little more context?
I don't know how to find out if there is a trigger function in the auth.users table or what exactly you mean by 'path config'.

Thanks in advance.

**Comment by GaryAustin1** [comment]
You would have written a trigger function on the auth.users table.  Fairly common to do that to set up a public.users table when users signup.  You would have a trigger function showing in the dashboard, database, functions list if so.

You can go to the sql window and type  `show search_path ;`
It should show something like this:
`| "$user", public, auth, extensions |`
main thing is auth in there.

**Comment by ChristianLutzCL** [comment]
@GaryAustin1 

I'm not quite sure I understood you correctly. I don't see a trigger function anywhere.

The search revealed that:
![Unbenannt](https://user-images.githubusercontent.com/30475783/180250054-d413a9f4-358b-4e2a-aff5-47c046f48307.PNG)

**Comment by GaryAustin1** [comment]
Unless someone else added a function to your database you would know if you added a trigger function.
I was just trying to guess at issues that could cause what you see.  My instances don't have an issue, so something more specific to your instance or code.

**Comment by GaryAustin1** [comment]
You do have a trigger function?  handle_new_public_user.   That is broken for some reason.

**Comment by GaryAustin1** [comment]
Are all the other functions yours?
I don't have a function or trigger like that on my instances, except one where I set it up (and wrote it) to populate a public.users table with copies of info from auth.users.

Could you have run some sql accidentally or some sort of starter template?

**Comment by ChristianLutzCL** [comment]
So the cron functions I have created. All the others are not really known to me, but it could be that they come from a starter template.

Thanks for the tip with the triggers.
I wouldn't have thought of it without you.

Case closed ;)
