### ISSUE TITLE
Editing rows in studio using Safari time and date of timestamptz fields are incorrect and not clearable.

### ISSUE THREAD

**Issue by gorbypark** [supabase/supabase#7862]
# Bug report

## Describe the bug

When editing a row in Safari, fields that are a timestamptz (possibly other date types) have a default value that is always today at 12:30PM.  In Chrome, the default value is whatever the field was already set to.  There is no way to "clear" the selected value and just not update that field.  Attempting to update with the today at 12:30PM time throws an error, which is likely because it's in the past.  Moving the date manually to some time in the future works, but obviously is not ideal.  The field is completely just the default suggested created_at field, nothing changed on that end.

## To Reproduce

Steps to reproduce the behaviour:

1. Edit a row using Safari
2. See timestamptz field is set to today's date at 12:30PM
3. Hit save

## Expected behavior

It should behaves like Chrome and have the current value as a "placeholder", which would allow you to edit other fields without being forced to edit the timestamptz field.

## Screenshots
![Screen Shot 2022-07-23 at 5 12 06 PM](https://user-images.githubusercontent.com/19569469/180614115-736866ff-6289-4c7b-8bed-55217d4e36d0.png)

## System information

- OS: macOS 12.5 (latest)
- Browser: Safari 15.6 (latest)
- Version of supabase-js: n/a (It's the hosted studio)
- Version of Node.js: n/a

**Comment by prajzwol7** [comment]
@gorbypark is this issue you've faced only in safari? As far as in chrome its possible to edit the timestampz and doesn't throw any error.

**Comment by gorbypark** [comment]
Yeah, Safari only.  The issue isn’t editing, but not editing.  The existing
time stamp values are not being shown, it always shows today’s date a
12:30PM.  When trying to save but not edit the time stamp, it throws the
error.  It is possible to edit the time stamp to make the date sometime in
the future and everything works.

I’m assuming that it’s a Safari intl issue, as the time/date picker
components work as expected in other contexts in studio.  I’ll see if I can
dig into the code and find out where along the prop chain the date is
coming from and why safari doesn’t like the format.

**Comment by prajzwol7** [comment]
@gorbypark I guess its only issue with the safari ,it might be helpful to look after how date and time components are rendered in safari. As far as its concern with chrome today's date shows the exact date alongside time when you created the respective row and can be edited and saved successfully.

**Comment by saltcod** [comment]
Thanks for the report @gorbypark. I think this old issue has been fixed in the time since last update here. The issue with Safari's date picker not being blank when you open it still persists however. We've not found a way around that with our datepicker component. Going to mark this one as closed as the erroring issue is resolved. 

Feel free to reopen if you continue to have issues with it though.
