### ISSUE TITLE
Edge functions break when Stripe is added

### ISSUE THREAD

**Issue by fredguest** [supabase/supabase#7878]
# Bug report

## Describe the bug

It is not currently possible to use Stripe in an edge function.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone git@github.com:supabase/supabase.git`
2. `cd supabase/examples/edge-functions/app`
3. `npm install --legacy-peer-deps` (running `npm install` fails without the flag because of conflicting React dependencies)
4. Link project, set function secrets, and deploy “browser-with-cors” function as described here: https://github.com/supabase/supabase/tree/master/examples/edge-functions#deploy
5. `npm start` the React app
6. In the browser, select the “browser-with-cors” function from the drop down and click “Invoke Function”
7. Everything works as expected, OPTIONS response contains Access-Control headers (see first screenshot)
8. Insert the following 5 lines of code at line 7 of the function “browser-with-cors” https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/browser-with-cors/index.ts#L7
```
import Stripe from 'https://esm.sh/stripe@9.6.0?target=deno&no-check'

const stripe = Stripe(Deno.env.get('STRIPE_API_KEY'), {
  httpClient: Stripe.createFetchHttpClient()
})
```
9. Redeploy “browser-with-cors” function
10. Restart the React app and rerun the “browser-with-cors” function from the browser
11. The function fails and the OPTIONS response is missing the Access-Control headers (see second screenshot)

## Expected behavior

The “browser-with-cors” function should run successfully, just as it did before the Stripe import was added.

## Screenshots

The “browser-with-cors” function OPTIONS response before adding the Stripe import

![Screen Shot 2022-07-24 at 9 05 09 PM](https://user-images.githubusercontent.com/1145624/180684130-635bba4c-cb50-4660-b2f7-35e80d657d70.jpg)

The “browser-with-cors” function OPTIONS response after adding the Stripe import

![Screen Shot 2022-07-24 at 9 19 46 PM](https://user-images.githubusercontent.com/1145624/180684339-f1a45d98-9842-4df5-aa91-3e4c856ffd47.jpg)

## Additional context

I confirmed that `Deno.env.get('STRIPE_API_KEY')` returned the key as expected prior to testing, and the Stripe import and initialization code is pretty straightforward so I don't think there's any user error happening. Not sure why adding Stripe would blow up an otherwise working edge function. It's presenting as a CORS error, but the CORS headers that worked before Stripe was added are still present in the source code after Stripe was added, so there is probably some other underlying issue that is causing a downstream CORS error.

**Comment by fredguest** [comment]
@inian do you know what Deno version is currently in use by Supabase edge functions? In this issue on the Stripe repo https://github.com/stripe/stripe-node/issues/1428 they've said that upgrading Deno from 1.21.3 to 1.22.0 fixed an issue with Stripe.

**Comment by thorwebdev** [comment]
@fredguest just a quick note that I'm able to reproduce the issue here: https://github.com/supabase/supabase/blob/chore/stripe-issue/examples/edge-functions/supabase/functions/browser-with-cors/index.ts and that we're currently investigating this.

**Comment by fredguest** [comment]
@thorwebdev awesome, thanks for the heads up.

**Comment by thorwebdev** [comment]
@fredguest we identified the issue and are working with the Deno team to get it resolved: https://github.com/denoland/deno/issues/15368

We'll keep you posted here. Sorry for the inconvenience!

**Comment by riderx** [comment]
@thorwebdev can we be allowed to check somewhere our deno version ?
like Deno.version in console log fail for now .
or just in the dashboard, that seems important to know :)

**Comment by fredguest** [comment]
The update to the Supabase CLI does indeed fix the bug. Stripe is running smoothly in Edge Functions now. Thanks for the quick turnaround @thorwebdev 🙌

**Comment by thorwebdev** [comment]
> @thorwebdev can we be allowed to check somewhere our deno version ? like Deno.version in console log fail for now . or just in the dashboard, that seems important to know :)

@riderx you can find a detailed explanation of why `Deno.version` is undefined in your deployed functions here: https://github.com/supabase/supabase/discussions/8006 .

**Comment by riderx** [comment]
@thorwebdev in a perfect world "This works because the runtime is always backwards compatible (it never contains changes that will break existing deployed code)." this is true.

but as seen in the stripe issue, it is not, forcing the version object to be undefined prevent us to debug and understand our issue.

 if that always compatible what's the issue to have conditional logic on version then ?

i totally understand why you choosed to do so, but it seems that still not the best approach.

**Comment by fredguest** [comment]
I kind of agree that this strategy, while it makes perfect sense in theory, is going to be difficult to implement in a way that actually guarantees a perfectly backwards compatible runtime. Maybe doable with an extremely thorough set of regression tests for the most imported libraries.

Personally, it wasn't an issue in this case as our app is not live yet, and Edge Functions are still being advertised as experimental anyway, but certainly once Edge Functions are advertised as production ready, something as business critical as Stripe can never be allowed to break in production due to a runtime migration that we don't control.

**Comment by leonardofficial** [comment]
Hi we are running into a similar issue:

```
import Stripe from 'https://esm.sh/stripe@13.3.0?target=deno&deno-std=0.132.0';

export const stripe = new Stripe(Deno.env.get('STRIPE_SECRET_KEY') as string, {
    apiVersion: '2023-08-16',
    httpClient: Stripe.createFetchHttpClient(),
});

const handler = async (req: Request): Promise<Response> => {
const body = await req.json();

 await stripe.customers.update(stripeCustomerId, {
        invoice_settings: {
            default_payment_method: body?.paymentMethodId
        }
    })

[...]

};

serve(handler);
```
Note: the above code is shortened. Our function also includes Cors and proper error handling. The same code is used in other functions without stripe and works fine.

As you can see we are trying to update a customer's default Payment. But this issue also occurs when e.g. creating subscriptions etc.

Serving this will make the function fail sometimes (often works on the first try, but calling the same function shortly after will fail) with the following error:
```
502: Bad Gateway (CONNECTION_BROKEN)
The deployment failed while serving the request.
```

**Comment by riderx** [comment]
It seems the Deno implementation is not well tested on stripe side, so i personally switched to their rest API
