### ISSUE TITLE
Prepared Parameters

### ISSUE THREAD

**Issue by XanManZA** [supabase/supabase#79]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hey guys
Just a question if the insert functionality is using prepared statements?

**Comment by kiwicopple** [comment]
Hey @XanManZA just a quick clarification, are you wondering if you have to create the prepared statements? Or are you asking for security purposes?

Our REST apis are built with PostgREST: https://github.com/PostgREST/postgrest

You don't have to prepare anything, you just update your schema and the API will update too. Let me know if that answers your question 👍

**Comment by XanManZA** [comment]
Hi @kiwicopple 
I'm asking for security purposes.
I'm then assuming if you say we don't have to prepare anything that you guys or PostgREST does that. Couldn't find documentation for that in PostgREST.
Thank you.
