### ISSUE TITLE
Can we use RLS to send email invitations to new users ?

### ISSUE THREAD

**Issue by chipseater** [supabase/supabase#7928]
# Feature request

## We must have `service_role` to use `inviteUserByEmail()`, which is unsafe to keep in the browser

If we want to invite some user in our website, this is convenient to use the client's UI to send email invitations. But it is required to have the `service_role` key, which is unsafe to serve to the browser. So if we want to use `inviteUserByEmail` in our website, we must call an rpc function. But there is no way to write a Postgres procedure to do the job.

## A postgres function might be great to do the job

Postgres functions are very convenient to do some job server-side, what about extending it to auth management ? 

## The dashboard can serve this purpose

The admin can send invitations through the dashboard, but it's a bit unconvenient.

**Comment by GaryAustin1** [comment]
I'm going to move this issue to discussion as maybe someone has workaround for this.
Using an rpc function it is likely possible to use the http extension to make this particular auth call.
It is also now possible to use edge functions for this kind of task.
As the gotrue server is a separate server from the database, some means to communicate between them has to be used.
