### ISSUE TITLE
Edge Functions throws error when deployed

### ISSUE THREAD

**Issue by rbkayz** [supabase/supabase#7930]
# Bug report

## Describe the bug
Edge functions are failing when deploying with the supabase client (works fine when there's no supabase)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new function using 'supabase functions new test-func'
2. Add the supabase JS client and make any call e.g. supabase.auth.user
4. See error - "Error: Failed to update an existing Function's body on the Supabase project: {"message":"Internal Server Error","errorEventId":"ef18ad353c9e4863a62509ba04ce8c16"}"

## Expected behavior

Function should have updated

## Screenshots

![image](https://user-images.githubusercontent.com/62215539/181489260-2fc8af71-5c21-4943-b0a5-f17058b64026.png)

## System information

- OS: Windows
- Browser (if applies) NA
- Version of supabase-js: 0.26.2
- Version of Node.js: 16.13.1

**Comment by vincenzodomina** [comment]
I have the same error on macOS Monterey 12.3

Also when I delete the function and redeploy, or when I create a new function with same code and then deploy, I get the same Error.

**Comment by s-graber** [comment]
Same here on macOS 12.4

**Comment by prag-matt-ic** [comment]
I'm getting the same

**Comment by riderx** [comment]
Same Error on my mac and CI here https://github.com/Cap-go/capgo/runs/7563772945?check_suite_focus=true

**Comment by GaryAustin1** [comment]
All, There are several reports on discord and in discussion on this also over the past 2 hours.

**Comment by GaryAustin1** [comment]
Support is asking that you do submit support tickets.

**Comment by riderx** [comment]
i did it on my side

**Comment by inian** [comment]
Hi, this was a regression in our API and it has been fixed now. Sorry about this!

**Comment by riderx** [comment]
i confirm, thanks a lot
