### ISSUE TITLE
How to can I edit postgresql.conf in Supabase Docker file?

### ISSUE THREAD

**Issue by billypap1** [supabase/supabase#7932]
Hello, I have created 2 instances of Supabase and I want to connect the internal databases and set them to master-slave. Is there any way to do this? Where can I find the postgresql.conf that comes with default Supabase docker installation?

**Comment by sweatybridge** [comment]
You can find [postgresql.conf](https://github.com/supabase/postgres/blob/develop/ansible/files/postgresql_config/postgresql.conf.j2) defined in our postgres repo. You can edit it inside docker by overriding `/var/lib/postgresql/data/postgresql.conf` via volume mount.
