### ISSUE TITLE
Miscolouring of input

### ISSUE THREAD

**Issue by aetinx** [supabase/supabase#7961]
# Bug report

## Describe the bug

Input on the table editor doesn't match the theme.

## To Reproduce

1. Go to 'Table editor'
2. Look at the bottom bar
3. Oh, there it is!
4. Attempt to read the low-contrast input's content

## Expected behaviour

Match the theme.

## Screenshots

![image](https://user-images.githubusercontent.com/65425469/181994643-33e531b2-c42e-4faf-8f91-24a69d4a1069.png)

## System information

- OS: Windows 11 Home 22H2 Build 22622.440
- Browser (if applies): Chrome Version 103.0.5060.134 (Official Build) (64-bit)

**Comment by Hallidayo** [comment]
This looks like a fix is in this pull request: #7906

**Comment by J0** [comment]
Closing since #7906 has been merged -- feel free to reopen if otherwise.

Thanks!
