### ISSUE TITLE
auth.uid() policy fails when user_id is a an Auth0 string id

### ISSUE THREAD

**Issue by mderrick** [supabase/supabase#7962]
Applying the following Policy template:
```
CREATE POLICY "Enable delete for users based on user_id" ON "public"."users"
AS PERMISSIVE FOR DELETE
TO public
USING (auth.uid() = user_id)
```

Fails with error: `Error adding policy: failed to create pg.policies: operator does not exist: uuid = text` when using a custom user_id that is not a UUID (Auth0) as per [this](https://auth0.com/blog/using-nextjs-and-auth0-with-supabase/) article.

**Comment by Hallidayo** [comment]
@mderrick - I wasn't using Auth0 but had a similar problem but I had this issue recently I had to change the column which I was entering the user_id to a uuid type instead of a type of text in order for the policy to run.

**Comment by GaryAustin1** [comment]
SB is trying to clean up some of these older inactive issues.

I'm going to close this, as several internal tables use UUID for the jwt sub claim, and if you are using an alternate string sub you can write an equivalent function to auth.uid to carry those out.

Changing the underlying auth, storage and realtime tables and code to handle strings is a far bigger task than just worrying about a function that can be replaced by the user.

Please feel free to open a more comprehensive issue if more than auth.uid() is being suggested or request this to be reopened if I missed the point.
Thanks
