### ISSUE TITLE
Unable to login using magic link

### ISSUE THREAD

**Issue by DeltsDev** [supabase/supabase#7968]
I don't know why it's not working, please help me
![Screenshot_2022-07-31-12-42-26-257_com android chrome](https://user-images.githubusercontent.com/105105597/182010978-31d23216-cf5c-4b68-85a0-472249ff1446.jpg)
![image](https://user-images.githubusercontent.com/105105597/182010986-2f02d385-d22c-4a9e-991a-c73825de6c24.png)
 
![image](https://user-images.githubusercontent.com/105105597/182010992-c3f9ba05-8fc3-4f94-a18f-3bdfb352f133.png)

**Comment by Hallidayo** [comment]
Hi @DeltsDev,

I think it might have something to do with your `Site URL` in `User Session`. You have the `https` protocol used instead of `http`, Could you change the `Site URL and then retry?

**Comment by DeltsDev** [comment]
![image](https://user-images.githubusercontent.com/105105597/182288853-ffa60103-62f1-49fd-996c-66a7d7624c46.png)

HI @Hallidayo still not working

**Comment by J0** [comment]
Hey @Hallidayo,


Thanks for jumping in! 

Hey @DeltsDev,

Quick check: do you have an application running on localhost:3000 on your device?

(not sure what device it is but it seems like a tablet/mobile phone)

**Comment by DeltsDev** [comment]
@Hallidayo yes on mobile, even on web it's not working

**Comment by J0** [comment]
I see, sorry to hear that it's not working as expected. Do you mind double checking your set-up against [the docs](https://supabase.com/docs/guides/auth/auth-magic-link) and if that doesn't work can you shoot over an email to support@supabase.io with replication instructions for web?

Thanks

**Comment by DeltsDev** [comment]
Thank you, I'm checking it again

**Comment by JPM84** [comment]
Suddenly having the same problem 🧐.
The mobile redirect is not respected. E-Mail Links, even if manipulated for mobile, always land on the Site URL.

**Comment by Sserra90** [comment]
The same here, suddenly stopped working, can't login to the app now, no redirect is done.

**Comment by alancoppin** [comment]
I have a similar issue. 

I can see using the magic link, the cookie's domain is the Supabase domain instead of being `localhost:3000` in my case... 
![Screenshot 2022-08-05 at 5 17 32 PM](https://user-images.githubusercontent.com/22746959/183006616-99abcb7b-8fc8-4508-b1cc-d5a105c9ee5f.png)

When manually change that domain to set `localhost:3000`, it's working fine

**Comment by DeltsDev** [comment]
Seems to be working now

**Comment by J0** [comment]
Glad to hear that it worked out! Closing now, feel free to let us know  if there are further issues
