### ISSUE TITLE
Add docs on Testing + Debugging Postgres Functions

### ISSUE THREAD

**Issue by Lior539** [supabase/supabase#7971]
Note this is a similar request to [#7311](https://github.com/supabase/supabase/issues/7311)
## Context

I'm getting a postgres error for a function that is triggered whenever a new auth user is created

## The issue
I'm finding it frustrating to debug the issue. Currently it's very difficult to debug postgres function when things go wrong. The current Postgres Logs tell what the error was, but besides from that it's a guessing game when it comes to debugging in.

It's also quite painful to debug, since you need to manually trigger the event. In my case, since the trigger is whenever a new auth user is insert, I need to manually complete my sign up flow for this (I'm using signin via Slack)

To be honest this is enough to make me stop using Supabase. I really like Supabase and want to use it, but I'm already struggling to make a simple app. I shudder to think what would happen when things get more complex.

**Comment by chipilov** [comment]
I think enhancements in this area would be great. Until they arrive, there are a few things that can help even today:
  - Supabase supports the PLPGSQL_CHECK extension, which is basically a linter for PL/pgSQL - you can run it to catch issues before even running the code;
  - Supabase supports the PGTAP extension, which allows writing unit tests for PL/pgSQL code (or just plain SQL code);
  - Supabase supports the DBLINK extension, which means you can roll your own basic logging infrastructure. The point of the DBLINK extension is to ensure that the logs will get written to your custom logs table even if the transaction fails (i.e. the statements which inserts in the logs table is execute via a ```dblink_exec``` call to ensure that it succeeds even if the transaction from which it was called gets rolled back)

**Comment by Lior539** [comment]
Thanks @chipilov. It's good to know. I wasn't aware of any of these extensions. With this in mind, it would be a good idea to include an article on debugging tips/extensions on the Supabase site for those less familiar with postgres

**Comment by Vinzent03** [comment]
There's now documentation on how to get started with pgTAP 
https://supabase.com/docs/guides/database/testing
https://supabase.com/docs/guides/database/extensions/pgtap
