### ISSUE TITLE
Downloading CSV file doesn't have .csv extension

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#800]
# Bug report

## Describe the bug
If you download a csv file, it's just a file name, no extension and you need to add .csv in order for it to be converted to csv.

## To Reproduce

1. Choose a table
2. Select the rows you want to include in your csv file
3. Select the 3-dotted icon on the right side
4. Choose Export to CSV
5. A file will be downloaded without any file extension

## Expected behavior

File downloaded should have an extension of '.csv'

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by phamhieu** [comment]
This bug is fixed now
