### ISSUE TITLE
Supabase Projects can't be updated

### ISSUE THREAD

**Issue by alQaisi** [supabase/supabase#8044]
### Discussed in https://github.com/supabase/supabase/discussions/8043

<div type='discussions-op-text'>

<sup>Originally posted by **alQaisi** August  3, 2022</sup>
I can't update any of my project's settings, I got a confirmation that my project has been updated successfully, but when I refresh the page all of my changes disappear and the default settings return.
I've noticed an error with 403 code in the console.
anyone has the same issue here?</div>

**Comment by golishchev** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/6458645/182574550-4c5aab53-510e-4150-9d6b-3691e2ca7a5d.png)

**Comment by Hallidayo** [comment]
I believe their is an issue with the dashboard: [Status](https://status.supabase.com/)

**Comment by alQaisi** [comment]
They fixed :)
supabase is up again.
