### ISSUE TITLE
Auth settings don't update after saving

### ISSUE THREAD

**Issue by TheOnlyTails** [supabase/supabase#8063]
# Bug report

## Describe the bug
I tried enabling Discord auth for my brand new Supabase project, and after entering the info and saving, it still marked Discord auth as disabled. Even trying to simply switch out the user session site URL doesn't work. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to auth settings in a supabase project
2. Enable Discord auth and enter the required info.
3. See nothing happen.

## Expected behavior
The settings should've been saved and updated.

## System information

- OS: Fedora 36
- Browser (if applies): Firefox 102
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by saltcod** [comment]
Hey @TheOnlyTails 

Just tested this on production and was able to enable Discord integration and save it.  I was also able to save the User Sessions url.  

Is this still happening for you?  

Restarting your server might be a good next step: 
https://app.supabase.com/project/-/settings/general

If it's still not working — could you check for any Console or Network errors and pass those along? 

Thanks!

**Comment by TheOnlyTails** [comment]
Restarting the server didn't work.
The only error I'm seeing in the console is marked as blocked by uOrigin.

**Comment by GaryAustin1** [comment]
There was a dashboard issue overnight reported here: https://status.supabase.com/

Most users who were reporting trouble overnight in the SB discord are now running (similar issue to yours).  

But there is your report and another one on Discord in the past few hours for new instances with same issue.
You probably should contact support thru the help button in your dashboard (assuming it is working).

**Comment by TheOnlyTails** [comment]
I talked to support, and it looks like it's been fixed!
