### ISSUE TITLE
Broken image in Supabase Studio blog post

### ISSUE THREAD

**Issue by dannykng** [supabase/supabase#8069]
# Bug report

The Product Hunt image at the end of the [Supabase Studio blog post](https://supabase.com/blog/2021/11/30/supabase-studio) is broken:

![Screen Shot 2022-08-03 at 5 08 54 PM](https://user-images.githubusercontent.com/7026076/182736024-54dd7ef2-4b07-498d-a3db-803d949058ff.png)

Part of the fix is to add `api.producthunt.com` as an allowable image domain in [next.config.js](https://github.com/supabase/supabase/blob/master/apps/www/next.config.js#L8-L19). However, the image is also an SVG which produces this error:
```
The requested resource "https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=321226&theme=light" has type "image/svg+xml" but dangerouslyAllowSVG is disabled
```

**Comment by saltcod** [comment]
Broken here as well: https://supabase.com/blog/product-hunt-golden-kitty-awards-2021

**Comment by saltcod** [comment]
https://github.com/supabase/supabase/pull/8194
