### ISSUE TITLE
Adding Redirect URLs in auth settings not working

### ISSUE THREAD

**Issue by MobileMon** [supabase/supabase#8070]
![Screen Shot 2022-08-03 at 10 19 52 PM](https://user-images.githubusercontent.com/2768159/182748927-d18df4cc-17bd-4079-98bd-cb1e53ce7d32.png)

**Comment by igdmitrov** [comment]
I tested it on Safari and Google Chrome. It works. 
Can you please test it on another browser?
Maybe you have some extensions as an ad blocker?

Related with your Stackoverflow question:
https://stackoverflow.com/questions/73222064/supabase-add-additional-redirect-url-not-working

**Comment by J0** [comment]
Hey @MobileMon,

We rolled out a patch recently to fix this -- could you check and see if you're still facing the issue?

Thanks

**Comment by visualjerk** [comment]
Not sure if it is related, but I am facing similar issues starting around 4 hours ago. Github Auth with Supabase always redirects to localhost instead of the prod url that is set as allowed redirect urls.

**Comment by J0** [comment]
Closing for now, feel free to let us know if there are still issues

**Comment by Loa212** [comment]
### Facing the same issue.

This is the situation:

![Frame 423](https://user-images.githubusercontent.com/62069101/183725669-b835a3f5-63fe-40a7-a020-314890679b5f.png)

![Group 330](https://user-images.githubusercontent.com/62069101/183725701-00e2c236-7d02-4130-b658-48a14a2926d0.png)

 I am using this to signIn:
 


`
const signInWithGoogle = async () => {
    const redirectTo = window.location.origin + "/Dashboard";
    const { user, session, error } = await supabase.auth.signIn(
      {
        provider: "google",
      },
      { redirectTo: redirectTo }
      );
    };
`

**Comment by kirbby** [comment]
Maybe a hint because I tripped over this twice now in 3 days. Make sure you have a slash at the end of the URL in the additional Redirect URLs and check the API call sent to supabase to compare.
My problem was that the first localhost address works, but the second doesn't because of the missing slash:
![image](https://user-images.githubusercontent.com/31236846/191829879-b1b0e83c-0abf-409f-a429-b57a59404ade.png)
