### ISSUE TITLE
Scrolling a table to the ends in SS is janky

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#8122]
# Bug report

## Describe the bug

When scrolling to the end of a table, the last couple rows don't show. You have to try scrolling a few times once you reach the bottom to really see the end rows.

This also happens when trying to scroll back up to the top. This makes it very unnecessarily frustrating to delete records at the end of the table. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a table with about 75 records in SS
2. Try scrolling to the last record and it will get stuck.
3. Scroll some more a few times until it finally "pops" up from the bottom.
4. Same thing on the way back up...you can't see the Delete buttons etc.

## Expected behavior

Smooth scrolling to the bottom and top.

## Screenshots

![image](https://user-images.githubusercontent.com/2954865/183226627-e005e28e-424b-42fd-81a9-5a8c9a7dd651.png)

![image](https://user-images.githubusercontent.com/2954865/183226655-5335bbb0-e704-4c1d-bb5d-17fcfc6e03f4.png)

## System information

- OS: macOS
- Browser Safari

**Comment by saltcod** [comment]
Confirmed in Safari. Looks related to the calculation of 100% of the parent's height.

**Comment by Hallidayo** [comment]
@saltcod @jtkeyva - have you guys got a video of the issue? I’ve tried to recreate but I haven’t been able to

**Comment by jtkeyva** [comment]
sure, here you go:
https://huyvqbrousenwplhnqcp.supabase.co/storage/v1/object/public/testmedia/supabase%20table%20jank.mov?t=2022-08-13T03%3A58%3A48.724Z

**Comment by saltcod** [comment]
@Hallidayo can you see it in Safari?

**Comment by 874anthony** [comment]
Hey everyone, just want to give this a try. I'm reading the Development Setup to lean how to contribute and help fix this issue.

**Comment by saltcod** [comment]
@Hallidayo to reproduce, try:

1. In Safari, go to the SQL editor, use the `countries` Quick Start. This will create a nice long table. 
![CleanShot 2022-08-25 at 15 01 13@2x](https://user-images.githubusercontent.com/105593/186731441-a3df1b87-aa4d-41e2-aa08-601fa4388e35.png)

2. Open the countries table that you just created, you should see this at the bottom of the window:

<img width="1271" alt="CleanShot 2022-08-25 at 15 02 39@2x" src="https://user-images.githubusercontent.com/105593/186731669-f6fa9487-ae6f-478f-a3f1-9ee68bf3c3ce.png">

To see the pagination, you need to scroll down a few times at the bottom: 

<img width="1310" alt="CleanShot 2022-08-25 at 15 03 18@2x" src="https://user-images.githubusercontent.com/105593/186731777-fa8d102e-d58e-4d5f-9411-040fa063a6b3.png">

**Comment by Hallidayo** [comment]
@saltcod - This is really odd I can't seem to recreate this on Safari using the countries test data?

Here is a video of what happens for me, I always see the footer/pagination:


https://user-images.githubusercontent.com/22655069/186743491-e7289c6c-233a-431a-864a-02a9decc1b5f.mov

For reference my Safari version is: Version 15.6.1 (17613.3.9.1.16)

**Comment by saltcod** [comment]
Thanks @Hallidayo — yeah that is weird you're not seeing it!

**Comment by joshenlim** [comment]
Hey everyone - i'm unable to reproduce this issue as well actually, i'm on the same version of safari as @Hallidayo. It may possibly be an issue for older version of safari perhaps? For those who are facing this could you try updating your safari version to see if that resolves the issue?

**Comment by saltcod** [comment]
Hey all. Also confirmed this working properly when I updated to the latest version of MacOS / Safari. Going to mark this one as closed.
