### ISSUE TITLE
Examples in Supabase-Flutter pub.dev Package

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#8123]
# Feature request

## Is your feature request related to a problem? Please describe.

Almost every single package on pub.dev has an example which let's you download it and take it for a spin. It's always frustrating when you find a package with no example because you expect to quickly test it out.

Packages without examples don't feel buttoned up and I know Supabase is buttoned up. Firebase has several examples from what I remember that includes login, upload etc.

## Describe the solution you'd like

Incluide a basic example with a login functionality and perhaps upload functionality with the package. Perhaps just the profile tutorial example from your website.

## Describe alternatives you've considered

Switching to Firebase. Ha j/k.

## Additional context

@dshukertjr seems like you can slip one of your many examples in there?

**Comment by dshukertjr** [comment]
Great call! Creating a simple example app right now!

**Comment by jtkeyva** [comment]
Awesome work and great quick response :)
