### ISSUE TITLE
Login with Twitter documentation is outdated

### ISSUE THREAD

**Issue by samjmck** [supabase/supabase#8127]
# Improve documentation

## Link 

[https://supabase.com/docs/guides/auth/auth-twitter](https://supabase.com/docs/guides/auth/auth-twitter)

## Describe the problem

Following the current documentation on "Login with Twitter" results in a nonfunctional Supabase app with users receiving a "Error getting user email from external provider" error. This is because the Twitter project requires "elevated access" to be able to access email addresses. Elevated access means submitting a brief description of the project to Twitter and waiting for them to review it. However, none of this is mentioned in the documentation. Some parts of the documentation such as "Enable 3-legged OAuth" seem to have been removed from the Twitter developers dashboard.

## Describe the improvement

Update the documentation to clarify that elevated access is required for Supabase and remove outdated parts such as "Enable 3-legged OAuth". Maybe also clarify that OAuth 2.0 is not required.

**Comment by madeleineostoja** [comment]
Related: https://github.com/supabase/gotrue/issues/214

**Comment by unnimona** [comment]
yes got confused with this documentation

**Comment by pratik-codes** [comment]
Is this open can i pick this up?

**Comment by samjmck** [comment]
> Is anyone working on this or can I pick this up? @samjmck 

It's open. I am not working on it.

**Comment by pratik-codes** [comment]
I am trying to push to a branch I created. I don't have access to push what should I do in that case? @samjmck @J0

**Comment by royderks** [comment]
@pratik-codes could you link your branch here so others can try it? Currently stuck on this too...

**Comment by pratik-codes** [comment]
@royderks I have created a branch locally from master but as i am not able to push it to remote you wont be able to see it as well. `remote: Permission to supabase/supabase.git denied to pratik-codes.` i do not have the permissons

**Comment by Hallidayo** [comment]
Hi @pratik-codes - Did you manage to push your local branch?

**Comment by pratik-codes** [comment]
Not yet @Hallidayo

**Comment by pratik-codes** [comment]
Have pushed the fix and this is the PR for it - https://github.com/supabase/supabase/pull/11224 @samjmck

**Comment by pratik-codes** [comment]
@samjmck this is fixed and merged.
