### ISSUE TITLE
Importing web3 in edge function results to "No 'Access-Control-Allow-Origin' header is present" error on preflight request

### ISSUE THREAD

**Issue by kimkarau** [supabase/supabase#8130]
# Bug report

## Describe the bug

When I import web3 in edge function the function does not run but throws "No 'Access-Control-Allow-Origin' header is present" error in developer console, 502 error in invocations tab in supabase app and no logs at all. When I comment out the web3 code, the function runs normally.

## To Reproduce

1. Deploy the following function
    
    ```TypeScript
    import { serve } from "https://deno.land/std@0.131.0/http/server.ts";
    import { corsHeaders } from "../_shared/cors.ts";
    import Web3 from "https://deno.land/x/web3@v0.11.1/mod.ts";
    
    console.log("Hello from Functions!");
    
    serve(async (req) => {
      if (req.method === "OPTIONS") {
        return new Response(
          "ok",
          {
            headers: {
              "Content-Type": "application/json",
              ...corsHeaders,
            },
          },
        );
      }
    
      const { address } = await req.json();
      const data = {
        message: `Address ${address}!`,
      };
    
      new Web3();
    
      return new Response(
        JSON.stringify(data),
        {
          headers: {
            "Content-Type": "application/json",
            ...corsHeaders,
          },
        },
      );
    });
    ```

    cors.ts is
    
      ```TypeScript
      export const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, Content-Type,'
      }
      ```

3. Invoke the function from client as

    ```JavaScript
   var { data, error } = await supabase.functions.invoke('verify', {
      body: JSON.stringify({
        address: "0x12345...",
        signature: "0x67890..."
      }),
      headers: {
        "Content-Type": "application/json",
      }
    });
   ```

5. See cors error in developer console, 502 error on invocations tab in supabase app and no logs in the logs tab
6. Comment out the `new Web3();` line in the function
7. Save the file and redeploy 
8. Invoke the function again
9. See no error
10. Have tried with ethers js library and had the same results
11. Have also tried imports from esm.sh, skypack and mini js latest versions, none has worked

## Expected behavior

When the function is invoked the preflight should return code 200 with all the headers and POST should return the address with all the headers present.

## Screenshots

Here is the developer console
![image](https://user-images.githubusercontent.com/33596477/183249677-56bff5bb-8a1e-4a45-9d8b-9a0943e54feb.png)

Here is the invocation tab 
![image](https://user-images.githubusercontent.com/33596477/183248963-002ce61c-3813-4229-9669-401320cb1216.png)

## System information

- OS:  Windows 10 21H2
- Browser: Brave v1.42.86 and Opera v89.0.4447.71
- Version of supabase-js: 1.35.4
- Version of Node.js: v16.15.1

**Comment by FinnRG** [comment]
You're probably hitting the free edge functions script limit (take a look at the [pricing table](https://supabase.com/pricing)).

**Comment by JoleMile** [comment]
Try wrapping your logic in a try/catch. Then return a custom 400 response with cors headers and you will see what is the real error. If you don't do this, any error in your function will result in a "cors looking" error in your browser.
You can find an example of it here https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/browser-with-cors/index.ts.

You can also use curl to avoid cors errors.

**Comment by GaryAustin1** [comment]
There have been a couple of suggestions here and no response from the op.
@kimkarau did you move past this?

**Comment by KevinBrolly** [comment]
This issue is quite old and has now become stale, I am going to close it. If this issue is still relevant please let us know.
