### ISSUE TITLE
Prisma PG connection error: `db error: FATAL: SASL authentication failed`

### ISSUE THREAD

**Issue by Vandivier** [supabase/supabase#8132]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

while attempting to perform an initial db migration using Prisma and the pooled connection DB URL, I get an uninformative error that says:
```
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.mlnegqzorthfebbzrxhs.supabase.co:6543"
Error: Migration engine error:
db error: FATAL: SASL authentication failed
```

I see no information on the supabase side about what might cause or resolve SASL auth failure

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by NanoCode012** [comment]
Hello,

> perform an initial db migration using Prisma and the pooled connection DB URL

As I understand, you should use the non-pooled URL for db migration. The below is said on the doc: 

> When running migrations you need to use the non pooled connection URL (like the one we used in step 4)

**Comment by GaryAustin1** [comment]
Closing this as potentially solved with need to use the non-pooling port and inactivity for 7 months.

**Comment by itsmartashub** [comment]
Exactly the same error for me when trying to run: `npx prisma db push` using the Nuxt 3 (`localhost`, not Vercel, Netlify and etc.)
- Right Credentials, Environment Variables, Supabase and Prisma Configurations ✅
- Right Network Configuration (No blocking firewalls, no VPN, also tried with VPN. Tried few different DNS resolvers) ✅
- Tried [Connection pooling with Supabase](https://supabase.com/docs/guides/integrations/prisma#connection-pooling-with-supabase) suggested by @NanoCode012 ✅ - doesn't work for me ❌

Versions:
- **prisma**: `^4.10.1`
- **nuxtjs/supabase**: `^0.3.1`
- **nuxt**: `3.1.2`
- **OS**: `Windows 11`
