### ISSUE TITLE
Templates Stripping Href Attributes

### ISSUE THREAD

**Issue by AndrewTelkamp** [supabase/supabase#8137]
# Bug report

## Describe the bug

It appears templates are stripping the `href` attributes which don't have an `http://`, `https://` or `www.` prefix. I have a mobile application and no intentions of also spinning up a web application. On mobile, deep links are traditionally defined via the app name and `://`, like `app://reset-password`. When I try to use this link however, the email I get has the `<a />` element and its content, but the `href` attribute has been removed.

## To Reproduce

Add a non-prefixed href attribute to a template

## Expected behavior

The email should preserve non-prefixed href attributes

## Screenshots

Email service working fine with `"https://google.com"`

<img width="1421" alt="Screen Shot 2022-08-07 at 1 20 21 PM" src="https://user-images.githubusercontent.com/20894667/183307656-f9ab8c2c-ad1b-4ea8-b96f-c3a5c94718b3.png">

<img width="1161" alt="Screen Shot 2022-08-07 at 1 21 43 PM" src="https://user-images.githubusercontent.com/20894667/183307672-e4b08654-b38e-4646-afb9-5d271aa7e420.png">

Email service stripping `href` attribute with non-prefixed href (`"exampleApp://reset-password"`)

<img width="1414" alt="Screen Shot 2022-08-07 at 1 20 05 PM" src="https://user-images.githubusercontent.com/20894667/183307680-b4d7344d-abd1-4269-811b-96819f989c09.png">

<img width="1158" alt="Screen Shot 2022-08-07 at 1 18 59 PM" src="https://user-images.githubusercontent.com/20894667/183307683-6793c4c1-58ec-48e5-9c88-aca7d2ddcffe.png">

**Comment by GaryAustin1** [comment]
Are you sure this is not being stripped my your email provider or SMTP provider?
I changes a template and added `<a href = "exampleapp://reset-password">Reset</a>`

Thunderbird email client works:

![image](https://user-images.githubusercontent.com/54564956/183314613-7de2d521-5fc8-4531-9500-a665262a3046.png)

Gmail email client does not work:

![image](https://user-images.githubusercontent.com/54564956/183314645-52b11e09-56fd-479e-b920-ada1e3183200.png)

**Comment by sweatybridge** [comment]
I believe this was an issue with an old version of self-hosted studio. The `Templates` page is no longer shown and you need to use `GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE` to configure a url to the email template.
