### ISSUE TITLE
Newline characters are not saved when editing a row column from table view

### ISSUE THREAD

**Issue by huntzinger92** [supabase/supabase#8152]
# Bug report

## Describe the bug

When editing a text field table column from the **table view** (screenshot included), new line characters (entered by hitting enter, NOT escaped new line characters like `\n`) don't seem to save correctly. New lines visible from the Supabase UI will not be visible when the text is rendered in the browser.

A workaround is adding these new line characters from the **row editor view**, which does seem to save them correctly.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with a text field in Supabase's UI
2. With the Enter key, edit the text field from the **table view** within the UI to include a new line between trivial alphanumeric characters
3. Query for this field from a browser and render it
4. The new line is not rendered

Workaround:

1. Create a table with a text field in Supabase's UI
2. With the Enter key, edit the text field from the **row editor view** within the UI to include a new line between trivial alphanumeric characters
3. Query for this field from a browser and render it
4. The new line is rendered

## Expected behavior

I expected the new line to be saved and rendered by the browser when adding a new line from the table view.

## Screenshots

By table view, I mean:

![Screenshot (240)](https://user-images.githubusercontent.com/42256116/183514040-d0edb445-901c-43a8-ad79-25ed5ddd36b7.png)

By row editor view, I mean:

![Screenshot (241)](https://user-images.githubusercontent.com/42256116/183513600-9bfcc354-7ab9-4df2-8d9e-966904594a33.png)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: 1.35.4

## Additional context

Thanks for Supabase, have found it very useful.

**Comment by joshenlim** [comment]
hey there @huntzinger92! i'm trying to reproduce your issue but cant seem to do so - could I double check if I might be missing something? Perhaps you can record yourself reproducing the issue as well

https://user-images.githubusercontent.com/19742402/192251172-37e699d9-23a4-4756-9bdf-8ad714e78bdd.mov
