### ISSUE TITLE
Query Editor can execute query while modal is open

### ISSUE THREAD

**Issue by gaurangrshah** [supabase/supabase#816]
# Bug report

## Describe the bug
In the query editor view, while I have the "rename query" modal window open, I attempted to intuitively use the <kbd>cmd</kbd> + <kbd>enter</kbd> shortcut to save, and instead my query which was open in the background actually executes, luckily it wasn't anything malicious, but this may be something work considering. 

## To Reproduce
1. click on the sql editor icon in the sidebar
2. open any query in an editor window (preferrably something non-malicious)
3. right-click on the query title bar 
4. select "rename query"
5. make a change to the query name, (even simply removing a character and adding it back).
6. now press <kbd>cmd</kbd> + <kbd>enter</kbd> 
7. witness your query has now executed! 

## Expected behavior

Should save query name.

 ## Screenshots
![Screen Shot 2021-03-05 at 6 42 13 PM (2)](https://user-images.githubusercontent.com/1086269/110186645-ee0fe780-7de3-11eb-8f72-cef3f56f7b9d.png)

![supabase-issue](https://user-images.githubusercontent.com/1086269/110186622-dd5f7180-7de3-11eb-9c02-d6234992b7b8.gif)

**Comment by kiwicopple** [comment]
Defintiely a bug! - perhaps something we introduced when we added the sidebars. Thanks @gaurangrshah !

Also, awesome bug report. The gifs, the use of `<kbd>`. 👌

**Comment by gaurangrshah** [comment]
@kiwicopple I appreciate that, you should see my PRs lol, in either case I'm absolutely loving the dx with supabase 👏 so bravo to you and the team!

**Comment by phamhieu** [comment]
fixed on latest dashboard app.
