### ISSUE TITLE
Existing column not found when adding new policy

### ISSUE THREAD

**Issue by BartoszRak** [supabase/supabase#817]
# Bug report

## Describe the bug

An issue with adding policies caused by not found column even when column exists.
Related to: https://app.supabase.io/

## To Reproduce

1. Create any table named for example `X` with a field named for example `userId`.
2. Try to add `INSERT` policy `(auth.uid() = userId)` for this table
3. You cannot because errors say there is no such column
4. Change your `userId` column name in table `X` into `user_id`
5. Try to add again `INSERT` policy `(auth.uid() = user_id)` for this table for field `user_id`
6. Everything works

*Maybe that is important but - when u use policy `(auth.uid() = userId)` with name `userId` then request with `userId` is sent but response contains error with `userid` (lowercase)

## Expected behavior

The adding policy should work properly for camel-case named columns.

## Screenshots
1. 
![image](https://user-images.githubusercontent.com/49698017/110193456-4078f480-7e34-11eb-8f76-771b5c3aab42.png)
2. 
![image](https://user-images.githubusercontent.com/49698017/110193461-4cfd4d00-7e34-11eb-8a3f-f6c502c367d6.png)
3.
![image](https://user-images.githubusercontent.com/49698017/110193476-6900ee80-7e34-11eb-8490-822db20ef33a.png)

## System information

- OS: [e.g. macOS, Windows]: `Windows 10`
- Browser (if applies) [e.g. chrome, safari]: `Chrome`
- Version of supabase-js: [e.g. 6.0.2]: `Doesn't apply`
- Version of Node.js: [e.g. 10.10.0]: `Doesn't apply`

## Additional context

---

**Comment by inian** [comment]
Can you try doublequoting userId @BartoszRak? Capital letters in postgres column names need to be used in quotes. If not, they are assumed to be lowercase.

**Comment by kiwicopple** [comment]
I'll close this one for now, but feel free to re-open if you have any issues @BartoszRak 👍
