### ISSUE TITLE
Android studio connection 

### ISSUE THREAD

**Issue by sathishkumaranbu** [supabase/supabase#8176]
Hi team,

I would like to connect my android studio project to supabase, and would like to check if these is any possibility to connect to it using jave.

Thanks and regards,
Sathish Kumar k

**Comment by hf** [comment]
Hey @sathishkumaranbu. There are some libraries maintained by the [supabase-community](https://github.com/supabase-community) which can be used on Android, however we have nothing official at this time.

We do have official [Flutter](https://github.com/supabase/supabase-flutter) support.
