### ISSUE TITLE
User can log in again by clicking back button

### ISSUE THREAD

**Issue by wave-light** [supabase/supabase#8178]
# Bug report

## Describe the bug

The user can log in again after signing out, by clicking the back button then refreshing the page.

## To Reproduce

- Checkout the supabase repo `https://github.com/supabase/supabase`
- Navigate to the NextJS with Supabase Auth folder `examples/nextjs-with-supabase-auth`
- Run `yarn`
- Add `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY` to `.env.local`
- Run `yarn dev`
- Open browser at http://localhost:3000
- Login with an existing user
- Click the `Sign out` button (you should now see the login form again)
- Click the browser back button once
- Refresh the page using the browser page refresh button
- You will now be logged in again

## Expected behavior

The user should not be able to log in again without entering their credentials

**Comment by piyushpradhan** [comment]
Can I work on this one ?

**Comment by pixtron** [comment]
seems to be related to supabase/gotrue-js/issues/302

**Comment by hf** [comment]
Was fixed with: https://github.com/supabase/gotrue-js/pull/574
