### ISSUE TITLE
Support function overloads in documentation

### ISSUE THREAD

**Issue by snorremd** [supabase/supabase#8188]
# Bug report

## Describe the bug

When defining two overloaded functions in the database schema only one will be listed in the Studio API documentation.

For example:

```
create function always_true(date_start date, date_end date)
    returns boolean
    language sql
    as $$
        select true;
    $$;

create function always_true(date_start date, duration interval)
    returns boolean
    language sql
    as $$
        select true;
    $$;
```

## To Reproduce

1. Clone [Repository reproducing issue](https://github.com/snorremd/supabase-overloaded-functions-missing-docs).
2. Run `supabase start`
3. Go to [API -> Stored Procedures -> Always true](http://localhost:54323/project/default/api?rpc=always_true)
4. See only one function overload is documented

## Expected behavior

Expected both function overloads to be documented.

## Screenshots

![Screenshot from 2022-08-10 12-19-46](https://user-images.githubusercontent.com/781014/183878784-97f40887-ed26-46c1-949c-6bc7433f1b39.png)

## System information

Latest version of development environment

- OS: Ubuntu 22.10 (but not relevant)
- Supabase CLI: 0.38.3
- Supabase Studio: latest (sha256:50d189ac8716d91f5f738d0020a2a8f96fc07b62a3558ab9e97c16dee0682816)
- Supabase Postgres-meta:v0.42.1
- Postgrest: v9.0.1.20220802
- Postgres: 14.1.0.34

## Additional context

Function overloads are great when you want to provide multiple ways of passing relevant parameters. While they do work in practice it would be hard for people to use the functions without reading the SQL migration files.

**Comment by KevinBrolly** [comment]
This issue is now quite old and has become stale. I am going to close it.

If this is still relevant and should be reopened please do let us know.
