### ISSUE TITLE
Search tables input needs padding

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#8196]
# Bug report

In the table editor sidebar, where you search your list of tables, the X button to clear the input box needs padding.

![CleanShot 2022-08-10 at 15 37 25@2x](https://user-images.githubusercontent.com/105593/183985514-cb81eef8-574f-49a4-9874-4fd736181f4d.png)

The hover state for more clarity:  
![CleanShot 2022-08-10 at 15 38 48@2x](https://user-images.githubusercontent.com/105593/183985599-591a0dd1-1541-4beb-b5d9-becf5c9a895a.png)

**Comment by joshenlim** [comment]
This has now been resolved
