### ISSUE TITLE
RSS feed does not validate

### ISSUE THREAD

**Issue by ntns** [supabase/supabase#8209]
# Bug report

## Describe the bug

The RSS feed does not validate according to W3's validator. Feeds that don't validate don't work on Thunderbird.

## To Reproduce

Check https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsupabase.com%2Frss.xml

## Expected behavior

Rss feed passes validation

## Additional context

The feed was working until August, 9th.

**Comment by ntns** [comment]
FYI the feed started working again in Thunderbird. Still has some errors in the validator though.

**Comment by MildTomato** [comment]
ahh we have some conflicts with blog urls @RamiroND

**Comment by Isaiah-Hamilton** [comment]
on problem is that `<guid>https://supabase.com/blog/community-day</guid>` is duplicated which is not allowed. I think that might have to do with the rss file being outdated. so [this pr](https://github.com/supabase/supabase/pull/8453) updates the rss file.

**Comment by ntns** [comment]
also, the following is incorrect:

`      <atom:link href="https://supabase.com/blog/rss.xml" rel="self" type="application/rss+xml"/>`

the correct url is `https://supabase.com/rss.xml` (without the `/blog`)
