### ISSUE TITLE
is it possible to migrate existing RDS tables to supabase? 

### ISSUE THREAD

**Issue by chakpongchung** [supabase/supabase#823]
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by kiwicopple** [comment]
Hi @chakpongchung yes it's very easy using `pgdump`. Here are a few discussions which might help:

- https://github.com/supabase/supabase/discussions/773
- https://github.com/supabase/supabase/discussions/666
- https://github.com/supabase/supabase/discussions/708
