### ISSUE TITLE
Can't delete with client js library

### ISSUE THREAD

**Issue by JSmithOner** [supabase/supabase#8285]
# Bug report

## Describe the bug

records won't delete using `delete()`, request returns me a 200 status response with empty array of data.

I ran this line of code:

```
  deleteNode ( path:string, key:string, uids:string[] ) {

    return ( this.supabase.from( path ).delete({returning:'representation'}).match( { ...this.primaryKeys} ).in( key, uids ) )

  }
```

no problem with `path` it is correct
primary keys are non exhaustive it's `project_uid` and `user_uid` and they both match with the records.
the `in` filter contains a set of path. At least one is correct ( I verified ).

## Expected behavior

This should delete all records that match `project_uid` and `user_uid` with the values passed to the `in` filter.

## System information

MAC M1 Monterey
Chrome
"@supabase/supabase-js": "^1.35.4",

**Comment by GaryAustin1** [comment]
The result you get is exactly what will happen if you have RLS on and don't meet both the delete and select policies.

**Comment by JSmithOner** [comment]
@GaryAustin1 Many thanks for your answer. But my policy is set to only `auth.uid() = user_uid` and for the moment there is only one user wit projects in the database. So if you have any ideas. On my side I'll continue investigating. Thanks again

**Comment by GaryAustin1** [comment]
Well, I would do a select with all the same table and filter settings and see if that works.  
I also assume key contains a column name and that column is not an array type.

**Comment by JSmithOner** [comment]
@GaryAustin1 you are totally right while the filtering works my columns is not of array type. Do I need to cast it? I didn't found it mentionned anywhere in the doc (maybe I've read it to quickly). Also I get an error when trying to convert it. Any idea?

**Comment by GaryAustin1** [comment]
My comment was just to make sure your .in column was not an array.  That probably would have returned an error anyway.
Does a select with the same filters work?  If not, then with RLS you are not filtering like you think you are.
You could also possibly show the actual url sent out to see if it looks correct.

**Comment by JSmithOner** [comment]
I've added back rls and replaced `delete()` by `select()` and it retrieved the records. Also I'm performing 4 requests in a row ( 4 different tables ) here is the url of one of them:

`https://${myprojectId}`.supabase.co/rest/v1/editor_scripts?project_uid=eq.y-4EgJU0fc-xfekyF8GoD&user_uid=eq.aacb8bbb-4cb9-4bdd-a175-21bc6630a666&path=in.%28n0Ryu7%7Cyw4QHK%7CcJko2s%7Cvpzq08%2Cn0Ryu7%7Cyw4QHK%7CcJko2s%7CBX1shw%2Cn0Ryu7%7Cyw4QHK%7CcJko2s%7CzblAbQ%2Cn0Ryu7%7Cyw4QHK%7CcJko2s%7CAsIEpp%2Cn0Ryu7%7Cyw4QHK%7CcJko2s%7C3eDs9X%2Cn0Ryu7%7Cyw4QHK%7CHKenGK%7CxaeG5v%2Cn0Ryu7%7Cyw4QHK%7Cs19QKz%2Cn0Ryu7%7Cyw4QHK%7CDCH3pf%2Cn0Ryu7%7Cyw4QHK%7CJVr_HQ%2Cn0Ryu7%7Cyw4QHK%7C61WBZ_%2Cn0Ryu7%7Cf7a9-W%7CVkgMp1%7CGTLIvP%2Cn0Ryu7%7Cf7a9-W%7CVkgMp1%7CuG01P4%2Cn0Ryu7%7Cf7a9-W%7CVkgMp1%7CShIqbh%2Cn0Ryu7%7Cf7a9-W%7CVkgMp1%7C19MBkT%2Cn0Ryu7%7Cf7a9-W%7CVkgMp1%7CjVobZb%2Cn0Ryu7%7Cf7a9-W%7COqAvH4%7Cg0ffWd%2Cn0Ryu7%7Cf7a9-W%7CDEV2SA%2Cn0Ryu7%7Cf7a9-W%7CsA6y3b%2Cn0Ryu7%7Cf7a9-W%7CI1joEo%2Cn0Ryu7%7Cf7a9-W%7CfZ1DuR%29`

there are two request for one deletion one `POST` and one `DELETE`

**Comment by GaryAustin1** [comment]
Assuming your project_uid is either not a uuid column, or you obscured the uuid (the format is odd), then that looks correct.
I'm out of ideas, it is acting like your filters are not finding, or your RLS is blocking.
If select works with the exact same filters, and values, as the delete with RLS OFF, then your filters seems fine.

**Comment by JSmithOner** [comment]
@GaryAustin1 Thank you again for your time. in fact the `path` column is a path of short UIDs ( type: text ) separated by a `|` character. just like a url. Btw I've tried `select()` with rls activated is this a problem?

**Comment by GaryAustin1** [comment]
The two key tests are select AND delete with exact same filter AND NO RLS for the delete (the select with RLS off won't change anything)   If select works and delete does not then I have no ideas, unless you have a delete trigger or something done to your postgres grants (which would not be normal).
The typical case I see for your symptom is RLS policy not met for Delete and Select in order for delete to work, then filters.  I've never run into anyone with another type of delete not working without error.

**Comment by JSmithOner** [comment]
@GaryAustin1 Ok, again thanks. I'll try deleting my RLS and creating a new one see if it changes anything. :)

**Comment by JSmithOner** [comment]
@GaryAustin1 Okay sorry for this but I've finally found out I was using functions with triggers that returns `NEW` instead of `OLD` for deletion, so records kept reappearing even when `DELETE` operations returned success.
I guess you can close this ticket.

**Comment by GaryAustin1** [comment]
You need to close the ticket, I'm not an employee.
