### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mbaneshi** [supabase/supabase#8298]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)
https://supabase.com/blog/blog/slack-consolidate-slackbot-to-consolidate-messages
## Describe the problem
Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by mbaneshi** [comment]
![Screenshot_20220815-031909_Chrome.jpg](https://user-images.githubusercontent.com/21130612/184557715-ec40a798-a15b-4295-a522-c789d3b49a5b.jpg)

**Comment by burmecia** [comment]
Hi @mbaneshi , not sure on which page you see this broken link, but I find it is okay on https://supabase.com/blog.

**Comment by J0** [comment]
Yup, agree with @burmecia  seems to work when using the `/blog` prefix.

**Comment by J0** [comment]
Closing for now but feel free to re-open if issue persists

**Comment by mbaneshi** [comment]
Hi 
go to this link 
https://supabase.com/blog/visualizing-supabase-data-using-metabase
find line that match this string "More Python and Supabase resources"
under this line there are 3 link 
second link is broken .

link with this string 
[Slack Consolidate: a slackbot built with Python and Supabase](https://supabase.com/blog/blog/slack-consolidate-slackbot-to-consolidate-messages)
