### ISSUE TITLE
All queries are gone from the dashboard. Creating a new one , refresh , gone

### ISSUE THREAD

**Issue by msevestre** [supabase/supabase#8347]
# Bug report

## Describe the bug
Some updates happened today (or in the last two days) on the dashboard it seems. It works fine last Friday.
All the user-defined queries are gone
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1041237/184688959-a82af69c-2b24-4d62-bf00-882897e429ca.png">

## To Reproduce

You can easily reproduce by creating a new query, then going to the database tab and back to the query sections. It will be gone.
Fav a query etc.. does not help. It's all gone. Hopefully not forever because we had crafted some nice queries here ...

## Expected behavior

Userdefined queries are persisted.
## Screenshots
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1041237/184689146-2c5138c4-924c-4041-8274-f52eb3a7d50b.png">

## System information

- OS: macOS
- Browser : Chrome

**Comment by saltcod** [comment]
Thanks for the report @msevestre 

In your network tab on that page, do you have a `content` request?  Should look like this, unless its failing:

![CleanShot 2022-08-16 at 13 55 25@2x](https://user-images.githubusercontent.com/105593/184930481-6c5a7fc7-4e88-40b5-b1cc-9fcc040aceb4.png)

**Comment by aar2dee2** [comment]
@msevestre 
Hi,
I'm able to see queries that were created earlier, as well as any new ones I create. Are the queries still not showing for you?

**Comment by msevestre** [comment]
Sorry I was away. I just checked and they are back....so some weird intermediate states .... closing for now
