### ISSUE TITLE
Publish docker images to ECR Public too.

### ISSUE THREAD

**Issue by mats16** [supabase/supabase#8355]
# Chore

## Describe the chore

Publish docker images to [ECR Public](https://gallery.ecr.aws/) too.

Docker hub has low rate limit, so docker official images are stored in ECR Public now.
FYI: [Docker Official Images now available on Amazon Elastic Container Registry Public](https://aws.amazon.com/jp/blogs/containers/docker-official-images-now-available-on-amazon-elastic-container-registry-public/)

It  is highly recommended to get alias for registry such as “supabase”.

## Additional context

Kong is already in [ECR Public](https://gallery.ecr.aws/docker/library/kong).

**Comment by burmecia** [comment]
Supabase docker images are already available on ECR: https://gallery.ecr.aws/supabase.
