### ISSUE TITLE
Quickstart: Next.js is not working and returning TypeError: _src_lib_supabase_supabaseClient__WEBPACK_IMPORTED_MODULE_3__.supabase.auth.getSession is not a function

### ISSUE THREAD

**Issue by bennik88** [supabase/supabase#8395]
# Bug report

## Describe the bug

I'm trying to follow the docs on the Next.js Quickstart but when setting up the `index.js` page I get the below describes error message. I checked my API keys and recopied the code multiple times to avoid issues with the API keys or typos.

## To Reproduce
1. Follow the "Quickstart: Next.js" on https://supabase.com/docs/guides/with-nextjs
2. Create a project
3. Set up the database schema
4. Create a next js app
5. Set up Login component
6. Setup Account page 
Everything works till here. After
7. Add `pages/index.js` Launch
After here I get the error Message:
```
Unhandled Runtime Error
TypeError: _src_lib_supabase_supabaseClient__WEBPACK_IMPORTED_MODULE_3__.supabase.auth.getSession is not a function

Source
pages/supabase.tsx (17:16) @ _callee$

  15 |       const {
  16 |         data: { session },
> 17 |       } = await supabase.auth.getSession();
     |                ^
  18 | 
  19 |       // only update the react state if the component is still mounted
  20 |       if (mounted) {
```

## Expected behavior
The docs example to work without the given error message when creating a user by passwordless email authentication.

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js:  "@supabase/supabase-js": "^1.35.6",
- Next: "next": "12.2.4",
- React: "react": "18.2.0",

**Comment by saltcod** [comment]
Hey @bennik88 – try grabbing supabase-js v2  (https://supabase.com/blog/supabase-js-v2)

Via: 
`npm i @supabase/supabase-js@rc`

I'll update that guide — thanks for the head's up!

**Comment by bennik88** [comment]
Hi @saltcod - thank you a lot for your reply. I see if this is related to the newer version of supabase probably consider updating the docs in the how to install page see here https://supabase.com/docs/reference/javascript/next/installing as it's showing to install `npm install @supabase/supabase-js` instead of the from you mentioned `npm i @supabase/supabase-js@rc`.
An additional question why is it called "v2" in most of your articles and in the reference guide it's called "next"?

**Comment by krsnaa** [comment]
@saltcod - after grabbing `supabase-js v2`, the error goes away and the Magic Link is received. However, the Magic Link points to https://nextjs-supabase-alpha-five.vercel.app/# - and does not redirect back to localhost:3000. Refreshing the localhost:3000 page still shows the session object as null and continues to render the Auth component and not the Account component!

What am I missing?

**Comment by aar2dee2** [comment]
opened a PR to update the guide for the bugs mentioned here.

**Comment by saltcod** [comment]
Going to close this one. Thanks for the feedback all — glad things got resolved!
