### ISSUE TITLE
Can't use supabase with Svelte rollup

### ISSUE THREAD

**Issue by KoreyPeters** [supabase/supabase#84]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
supabase will not compile with Svelte.

I run:
```
npx degit sveltejs/template test1
npm install
npm install --save @supabase/supabase-js
npm run dev
```
Finally, in my App.svelte file I put:
```
import { createClient } from '@supabase/supabase-js'

// Create a single supabase client for interacting with your database
const supabase = createClient("https://xyzcompany.supabase.co", "1a2b-3c4d-5e6f-7g8h");
```

And I get the following error message:
```
> svelte-app@1.0.0 dev C:\PycharmProjects\test1
> rollup -c -w

rollup v2.11.2
bundles src/main.js → public\build\bundle.js...
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON
files)
node_modules\websocket\package.json (2:9)
1: {
2:   "_from": "websocket@^1.0.31",
            ^
3:   "_id": "websocket@1.0.31",
4:   "_inBundle": false,
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON file
s)
    at error (C:\PycharmProjects\test1\node_modules\rollup\dist\shared\rollup.js:217:30)
    at Module.error (C:\PycharmProjects\test1\node_modules\rollup\dist\shared\rollup.js:15145:16)
    at tryParse (C:\PycharmProjects\test1\node_modules\rollup\dist\shared\rollup.js:15034:23)
    at Module.setSource (C:\PycharmProjects\test1\node_modules\rollup\dist\shared\rollup.js:15436:30)
    at ModuleLoader.addModuleSource (C:\PycharmProjects\test1\node_modules\rollup\dist\shared\rollup.js:17430:20)
```

If I remove the lines from my App.svelte file, `npm run dev` works fine.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
The error message suggests the problem is a lack of "@rollup/plugin-json", so I ran the following:
`npm install @rollup/plugin-json --save-dev`
...but it didn't help. Same exact error.
I'm not a Javascript genius, so I may be doing something wrong, but I'm open to suggestions.

**Comment by soedirgo** [comment]
Hi! Not a JavaScript genius either, but will try to help.

Seems you also need to [import the plugin](https://github.com/rollup/plugins/tree/master/packages/json#usage) after npm-installing it (hence the persistent error).

**Comment by kiwicopple** [comment]
Thanks for jumping on this one @soedirgo 

@KoreyPeters if that works (or doesn't) let us know. It will be good to add a basic implementation to our [examples folder](https://github.com/supabase/supabase/tree/master/examples)

Perhaps we can use your project as a baseline

**Comment by KoreyPeters** [comment]
Thanks for your help everyone,
After investigating the links provided, I modified the default rollup.config.js file generated by Svelte to the following:
```import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';

// I added the line below:
import json from '@rollup/plugin-json';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file - better for performance
			css: css => {
				css.write('public/build/bundle.css');
			}
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser(),

                // I added a comma at the end of the previous line and the line below.
		json()
	],
	watch: {
		clearScreen: false
	}
};

function serve() {
	let started = false;

	return {
		writeBundle() {
			if (!started) {
				started = true;

				require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
					stdio: ['ignore', 'inherit', 'inherit'],
					shell: true
				});
			}
		}
	};
}
```
I only modified the two lines, and was able to get the sample project running, the console showed that the listener had connected, and when I created some models in my Django database I saw the updates arrive!

I'm very pleased with this. I'm a Django man for better or worse and I've only admired Firebase from afar, wishing that it could be in Postgres, so this project is a bit of a dream come true for me. Thanks!

**Comment by kiwicopple** [comment]
> so this project is a bit of a dream come true for me

thanks @KoreyPeters, it's always pleasant to get nice feedback in github issues

If your repo is small and public, please do share - I'd love to add it to the examples folder for future svelte users

**Comment by KoreyPeters** [comment]
I'll consider that. It's not much of anything yet and I don't know what it will become... But i intend to be active in this community. As I said, this is a product I've been wanting for a long time.
