### ISSUE TITLE
Wrong method used

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#8414]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/next/auth-signinwithotp#sign-in-with-sms-otp

## Describe the problem

The method used is ``signInWithPassword``, but the docs talks about ``signInWithOtp``.

## Describe the improvement

Update the method, or be more clear about this change.

## Additional context

/

**Comment by Dhruv-Gajjar** [comment]
i see no assignees, I would like to work on this issue.

**Comment by Dhruv-Gajjar** [comment]
Hey @Olyno the changes I make cannot seem to reflect on the docs it doesn't change anything on the local server, Can you help me with that.?

**Comment by pixtron** [comment]
@Dhruv-Gajjar have a look at #8401, that probably helps you to get started with this issue.

**Comment by Dhruv-Gajjar** [comment]
@pixtron Thank you, i am actually updating the yaml file itself but when i save, build, and run again nothing changes on the docs it doesn't update. I am updating the same file mentioned in this reference above.

**Comment by pixtron** [comment]
@Dhruv-Gajjar there seems to be a step that isn't documented (yet).

```bash
$ cd packages/generator
$ npm install
$ npm run supabase-js:v2
```

This updates the mdx files in `apps/reference`. After they are updated, you can `npm run build && npm start` in `apps/reference` and you will see your changes. Looking at #8401 it seems you only have to commit the yaml file and not the generated mdx files.

**Comment by Dhruv-Gajjar** [comment]
@pixtron Thank you, I am contributing for the first time, kinda newbie. to this project, it was a great help.
