### ISSUE TITLE
Configure choice between otp and magiclink

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#8415]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/next/auth-signinwithotp#notes

## Describe the problem

In the docs, it is saying:
> If you're using an email, you can configure whether you want the user to receive a magiclink or an otp.
If you're using phone, you can configure whether you want the user to receive a magiclink or an otp.

But how can i choose between magiclink or otp? There are no properties to choose between both.I also looked in the Auth/Settings email provider settings, and i can't find anything about it.

## Describe the improvement

Have an explanation on how to choose between otp and magiclink.

## Additional context

![image](https://user-images.githubusercontent.com/25107942/185054998-d5c35d5d-5a46-47ba-b933-5abbdba57d66.png)

**Comment by RyanTippsTX** [comment]
agreed, docs do not explain how to specify (or if its currently possible)

**Comment by Olyno** [comment]
Actually, you can. To do that, you simply need to add the ``{{ .Token }}`` variable in your email templates. In this way, users will get their code. I think it would be better to add it to the docs.

**Comment by saltcod** [comment]
Yep thanks @Olyno — we need to add that to the docs and also to that part of the ui. I've got an internal note going!

**Comment by hf** [comment]
Docs are updated, should be clearer this way.
