### ISSUE TITLE
JWT generator in self-hosted docs is broken - cannot connect to default project.

### ISSUE THREAD

**Issue by fundef1** [supabase/supabase#8443]
### Discussed in https://github.com/supabase/supabase/discussions/8402

(I removed the original discussion, all the bug hunting was irrelevant)
I think the JWT token generator in the self-hosted docs is broken.
tokens generated by it are not accepted and lead to "cannot connect to default project"

AFAICT it comes down to iss being set to supabase instead of supabase-demo.

copy pasting a generated token into jwt.io changing the iss (and the secret) and pasting that into .env / kong.yml seems to work.

**Comment by hf** [comment]
@joshxyzhimself Unlikely.

**Comment by hf** [comment]
Let's continue in the discussion since I'm not able to identify that this is really the underlying issue that needs fixing.
