### ISSUE TITLE
Getting an error when trying to update a webhook

### ISSUE THREAD

**Issue by VincentAudette** [supabase/supabase#8463]
# Bug report

## Describe the bug

Not able to update a webhook.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.com/project/<PROJECT_ID>/database/hooks
2. Click on Create a webhook
3. Enter the fields
4. Click submit
5. Try to edit
6. See the error in the screenshot

## Expected behavior

Being able to update hook fields

## Screenshots
<img width="1680" alt="Screen Shot 2022-08-18 at 12 36 50 AM" src="https://user-images.githubusercontent.com/36488653/185295612-a1b9d12b-189d-42e4-bd21-71f5870b5def.png">

## System information

- OS: macOS
- Browser chrome

## Additional context

I know this is Alpha, great job on the project it's great

**Comment by Hallidayo** [comment]
Hi @VincentAudette - I've just tried to recreate the same error you were getting but I'm not able to.

Are you still experiencing the same issue?

**Comment by VincentAudette** [comment]
The first one still has the error but new ones are not affected so this doesn't need more investigation. Thanks.
