### ISSUE TITLE
URL.hostname is not implemented

### ISSUE THREAD

**Issue by vbylen** [supabase/supabase#8464]
# Bug report

## Describe the bug

Just upgraded to `supabase v2.0.0-rc.1 ` and getting a `URL.hostname is not implemented` error.

This is a React Native/Expo app.

## To Reproduce

Do the following in an expo app:

```jsx
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
})
```
## Screenshot

<img width="388" alt="image" src="https://user-images.githubusercontent.com/57633368/185299634-90910da3-3b1e-47df-bca9-8c4ad82f610a.png">

## Additional context

Never had problems in v1, so this is related to the latest update.

**Comment by vbylen** [comment]
@monicakh can you move this issue to https://github.com/supabase/supabase-js ?

**Comment by vbylen** [comment]
error disappeared after importing this polyfill in the same file where I was importing the client:

```jsx
import 'react-native-url-polyfill/auto'

import { createClient } from '@supabase/supabase-js'
```

**Comment by monicakh** [comment]
@vbylen Should we close this issue ?

**Comment by javierguzman** [comment]
Hello! I just got this error as well and I do not understand why this was closed @monicakh; The solution by @vbylen is more a workaround than anything else

**Comment by ski043** [comment]
Same problem led me this way. Should definitely be mentioned in the quick start guide!

**Comment by grestonian** [comment]
Any resolutions to this error? I'm still getting this.

**Comment by Eronred** [comment]
This one works fine rn.  
https://github.com/supabase/supabase/issues/8464#issuecomment-1221448428
https://www.npmjs.com/package/react-native-url-polyfill

> Any resolutions to this error? I'm still getting this.

**Comment by armannaj** [comment]
I can confirm the issue still exists with supabase 2.4.0, react 18.1.0 and react-native 0.70.5.

The workaround works, but I guess a fix is still needed.

**Comment by ildaneta** [comment]
I'm here to confirm that this error still happening:

```ts
"@supabase/supabase-js": "^2.7.0",
"expo": "~47.0.12"
```

Both Android and iOS:
<img width="857" alt="Screenshot 2023-02-04 at 10 49 42" src="https://user-images.githubusercontent.com/21963291/216760645-c759891e-acaa-4c8f-afca-7a9ee7d4d0eb.png">

**Comment by mrlambchop** [comment]
Error happening here on expo sdk 47 and top of tree.

**Comment by ReevMich** [comment]
yep im getting this error as well, react native 0.69.6, expo 46.0.19

**Comment by kindr3** [comment]
Tks https://github.com/supabase/supabase/issues/8464#issuecomment-1221448428

**Comment by Garabed96** [comment]
May 2023, this is still an issue. 
"@supabase/supabase-js": "^2.21.0"
"expo": "~48.0.11"
"react-native": "0.71.7"

import 'react-native-url-polyfill/auto' fixes it
as @vbylen said works, why not add it to the documentation?

**Comment by darkfoxdev** [comment]
I'm having this issue as of May 25, 2023. I added `import 'react-native-url-polyfill/auto'`, which solved the URL.hostname error, but now I just get the error "Undefined is not an object (evaluating 's.ucs2.decode'.

**Comment by gregnr** [comment]
You're right @ski043 @ildaneta @Garabed96, the docs needed to be updated. Ideally for RN `supabase-js` wouldn't need to depend on `hostname()` (or have its own implementation), but in the mean time `react-native-url-polyfill/auto` is the best solution.

Docs have been updated as of https://github.com/supabase/supabase/pull/14207, thank you again @faizanraso.

**Comment by faizanraso** [comment]
It was my pleasure @gregnr !

**Comment by lucaliebenberg** [comment]
Hi @ Garabed96, when importing `react-native-url-polyfill/auto`, you should import it into your index file. I hope this helps

**Comment by kyungjoongo77777** [comment]
Use the connection code in the session pooler instead of direct connection.
