### ISSUE TITLE
 Exporting CSV (or markdown) exports jsonb as `[object Object]`

### ISSUE THREAD

**Issue by msdrigg** [supabase/supabase#8489]
# Bug report

## Describe the bug

Exporting rows from a table with jsonb columns, exports those as a JavaScript `[object Object]`

## To Reproduce

1. Go to [https://app.supabase.com/project/\<your project id\>/sql](https://app.supabase.com) (The "Sql query" tab in your project dashboard).
2. Click on "New Query" and enter `select * from auth.users;`
3. Run the query
4. Notice how the `raw_app_metadata` shows up as a nice json string in the table (expected behavior)
5. Click on the "Results" dropdown and click "Download CSV".
6. Inspect the csv and notice how `raw_app_metadata` shows `[Object object]` instead of the actual metadata **(not expected)**

## Expected behavior

The exported csv would show the same json string that the ui does

## System information

- Browser: Firefox

## Additional context

Also a problem with the markdown exporter

Previously reported here https://github.com/supabase/supabase/issues/1764

**Comment by antonioprudenzano** [comment]
Hi, i can see the problem you described, i am looking to fix this and then create a PR.

**Comment by gefgu** [comment]
I would like to work on this issue :)

**Comment by Gautam-Arora24** [comment]
I would like to work on this issue. Can anyone assign me?

**Comment by j4w8n** [comment]
@Gautam-Arora24 

You are welcome to submit a PR. I don't have any repo powers; I'm just a contributor.

**Comment by Gautam-Arora24** [comment]
Sure :0

**Comment by Gautam-Arora24** [comment]
@msdrigg Can you confirm if it's working fine or not now? I have tried adding `jsonb` data and it seems to be working fine after downloading CSV. Attaching SS for reference.
<img width="1109" alt="Screenshot 2022-12-06 at 9 01 59 PM" src="https://user-images.githubusercontent.com/53913514/205954614-7fc4b52f-a8e1-4914-afa9-53b8efc57e6c.png">

<img width="957" alt="Screenshot 2022-12-06 at 9 02 20 PM" src="https://user-images.githubusercontent.com/53913514/205954681-1b4c0b1f-714c-461e-8789-e5a022c25c05.png">

**Comment by Gautam-Arora24** [comment]
Yes, I saw that I expected.
Can you share the data you are adding in your table? Maybe it's data specific.

**Comment by msdrigg** [comment]
`select * from auth.users;`

I am referencing the `auth.users` table here because it should be the same for anyone who is using Supabase.

**Comment by msdrigg** [comment]
Just for your reference, what should be in the `raw_app_meta_data` column for my specific query is this json: `{"provider":"email","providers":["email"]}`

**Comment by Gautam-Arora24** [comment]
Yes @msdrigg! It indeed shows as `[object Object]` in the downloaded CSV. Looking into it.

**Comment by masa5714** [comment]
[ For those who want CSV immediately ]

---

The following method solved the problem.

Example:
- Table Name -> all_patterns
- Column Name -> shipping_fee_patterns

```sql
select REGEXP_REPLACE(REGEXP_REPLACE(jsonb_pretty(shipping_fee_patterns), '\r|\n|\r\n| ', '','g'), '"', '""', 'g') as shipping_fee_patterns from all_patterns;
```

Please let me know if there is a smarter way to write this.

---

I would wait for a fundamental solution. 
But if you want CSV immediately, try this method.

In my case, I had the same problem with the JSON type.
Sorry if this is not helpful since it is not jsonb.

Before :

![0e3fcb72cc0f39ee3e2b57c9d4db2d28](https://user-images.githubusercontent.com/7102373/206918102-0b853430-516b-4e3f-90ce-2844c53ba285.png)

After :

![7f557ed00be28739fee1b292c6c017ce](https://user-images.githubusercontent.com/7102373/206918156-55677526-d62f-46c9-a74b-5df340ea2b1e.png)

**Comment by masa5714** [comment]
I ran the CSV export today and it seems to have solved this problem 🎉

The following method, which we previously mentioned, is now not recommended as it causes data corruption.
https://github.com/supabase/supabase/issues/8489#issuecomment-1345611466

Thanks!

**Comment by joshenlim** [comment]
hey there @masa5714! ahh yes - we did push a fix out for this a couple of weeks ago but didn't realise about this open issue. I'll go ahead to close this issue for now then - but please feel free to reach out if there are any other problems with the export CSV 😄

**Comment by Chippd** [comment]
Found this issue as I'm now facing this problem - jsonb displays correctly in the dashboard when running a query but when exporting CSV or "copy as markdown" I'm seeing [object Object]. Shall I open a new issue?

**Comment by jhay-25** [comment]
> Found this issue as I'm now facing this problem - jsonb displays correctly in the dashboard when running a query but when exporting CSV or "copy as markdown" I'm seeing [object Object]. Shall I open a new issue?

yeah, this should still be an active issue
