### ISSUE TITLE
setAuth() function missing in supabase-js v2

### ISSUE THREAD

**Issue by dragonsnapx** [supabase/supabase#8490]
# Bug report

`setAuth()` function is missing in the supabase-js v2 RC.

## Describe the bug

`setAuth()` function is missing in the supabase-js v2 RC.

## To Reproduce

Going through the functions & docs, there are no mentions of this function being removed. It throws an error because it's not a defined function.

## Expected behavior

Expecting that `supabaseClient.auth.setAuth(cookie)` to be an available function.

## System information

- OS: macOS
- Version of supabase-js: 2.0.0@rc
- Version of Node.js: 17.2

## Additional context

This function is necessary since it can be used to perform SSR pre-fetching with the user's credentials.

**Comment by iolyd** [comment]
The function has been deprecated: https://supabase.com/docs/reference/javascript/next/release-notes#deprecated-setauth.

There have been a few discussions/issues on the matter (ex.: https://github.com/supabase/supabase-js/issues/514). You should be able to find solutions there and in the docs of `supabase-js v2`.

**Comment by dragonsnapx** [comment]
Thanks for the solution. Closing.

**Comment by bhvngt** [comment]
I have been using `setAuth` in my test suite. This change has broken quiet a few of my test cases. While I could substitute `setAuth` with `global Authorization header` for some of my test cases, there are cases that I could not fix it.

- previously `setAuth` would typically trigger `onAuthStateChange` handler with `TOKEN_REFRESH` event. With current solution of creating `createClient` with `global Authorization header`, such events does not appear to be getting triggered.

- How does one set `realtime client` with `authorization token`.  As per my limited understanding, `realtime` auth gets [triggered](https://github.com/supabase/supabase-js/blob/18b7022232b63bc72176e54d455b49649cce09d0/src/SupabaseClient.ts#L323) on `authStateChange` event. However, [setAuth](https://github.com/supabase/realtime-js/blob/10228a3d7cb87897751952dfd2f39d0a09f4cdac/src/RealtimeClient.ts#L346) expects channels to be already added to the channel list. So does that mean that I need to subscribe to the channels before I authenticate users. In such a scenario how does one deal with node-side testing of `realtime-client` RLS test cases

**Comment by catlan** [comment]
> ```ts
>         Authotization: `Bearer ${accessToken}`,
> ```

There is a typo, should be Authorization.

**Comment by leadream** [comment]
In my case, I need to change auth role to do different things to control access. how can I handle this for now?

```js
  uploadFile = async (ctx: Context): Promise<Response> => {
    const { request, supabase, env } = ctx
    const accessToken = await request.headers.get('Authorization')
    const {userid } = await request.json<any>()

    // Switch to server role, check if user is a paid member
    supabase.auth.setAuth(env.SERVICE_ROLE_KEY)
    const { data, error } = await supabase
      .from('profiles')
      .select()
      .eq('id', userid)
      .single()

    if (data.isMember) {
      // Switch to user role
      supabase.auth..setAuth(accessToken)
      const { data, error } = await supabase.storage
        .from('avatars')
        .upload(file.name, file)
    }

  }
```

**Comment by bhvngt** [comment]
@leadream I have been using this [solution](https://github.com/supabase/gotrue-js/pull/340#issuecomment-1261285310) with good success on the server side. You may want to check that out for your problem.

**Comment by leadream** [comment]
@bhvngt Thanks,  I'll try it.
