### ISSUE TITLE
Studio: App crashes when cloning repo and using yarn

### ISSUE THREAD

**Issue by tendersej** [supabase/supabase#8491]
# Bug report

## Describe the bug

Cloning the repo and installing dependencies with yarn sees studio app crashing upon running 'yarn dev'.

## To Reproduce

- clone supabase repo
- `cd studio`
- `yarn`
- `yarn dev`
- the app crashes
- notice ERR_REQUIRE_ESM error:

error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/src/index.js
require() of ES modules is not supported.
require() of /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/src/index.js from /Users/tendersej/Code/supabase/studio/node_modules/recharts/lib/shape/Symbols.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/src/index.js
require() of ES modules is not supported.
require() of /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/src/index.js from /Users/tendersej/Code/supabase/studio/node_modules/recharts/lib/shape/Symbols.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/tendersej/Code/supabase/studio/node_modules/d3-shape/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/tendersej/Code/supabase/studio/node_modules/recharts/lib/shape/Symbols.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
## Expected behavior

The app should run. 

## Screenshots

<img width="1002" alt="Screenshot 2022-08-18 at 19 49 27" src="https://user-images.githubusercontent.com/7692650/185461256-9c647377-40cd-445b-abd0-af54fe93ab9d.png">

## System information

- OS: [macOS]
- Browser: Not Applicable
- Version of supabase-js: Not Applicable
- Version of Node.js: v14.20.0
- Commit 6ada19a96f3e86d57a9bc1cacb150f7e5ba064b5

## Additional context

As evidence by the error trace, the issue is linked to library recharts. This [issue on the recharts repo](https://github.com/recharts/recharts/issues/2658) explains the issue (d3 packages switched to modules)

**Comment by tendersej** [comment]
I created PR #8494 to pin recharts dep to exact 2.1.6 version. recharts 2.1.12 works as well.

**Comment by Ziinc** [comment]
As per comment https://github.com/supabase/supabase/pull/8494#issuecomment-1222538249 , we are unable to replicate this issue as per the development environment as stated in `studio/README.md`. Please use npm for future contributions, thanks.
