### ISSUE TITLE
Possible to self-host?

### ISSUE THREAD

**Issue by tycrek** [supabase/supabase#85]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [x] question about how to use this project

* **Summary**

I maintain a [Degoogle guide](https://github.com/tycrek/degoogle) and Supabase is [under consideration](https://github.com/tycrek/degoogle/issues/135) to be added as a Firebase alternative. Is it possible to self-host Supabase, or will it be possible in the future? If not, what country/ies are your hosting servers located in?

Thank you!

**Comment by awalias** [comment]
Hey @tycrek thanks for getting in touch. First of all your project is incredible, thank you for considering us!

Yes it is possible to self host Supabase today. The component breakdown is:

- Postgres, we provide an easy-to-install version [here](https://github.com/supabase/postgres), this is the same install we use on our own platform
- Our Realtime API - https://github.com/supabase/realtime , which will pump changes into your application over websockets
- The RESTful API - https://github.com/PostgREST/postgrest , which provides the CRUD operations
- And the client library (more languages in the works): [Javascript](https://www.npmjs.com/package/@supabase/supabase-js)

But more importantly we have packaged this all up into a [single docker image](https://hub.docker.com/r/supabase/supabase-dev) which you can deploy straight away

As for the hosted version - we will soon be adding deployment options in:
-  New York City, United States.
-  Amsterdam, the Netherlands.
-  San Francisco, United States.
-  Singapore.
-  London, United Kingdom.
-  Frankfurt, Germany.
-  Toronto, Canada.
-  Bangalore, India.

Right now all VMs are deployed in Singapore by default

**Comment by tycrek** [comment]
Thank you for the quick response!

**Comment by kiwicopple** [comment]
Thanks for the backlink @tycrek. Once we've built up some robust docs on self-hosting I'll jump into your repo with a PR.

Doubling up on @awalias 's comment - your project is amazing

**Comment by jnpantall** [comment]
Hey @kiwicopple, @awalias,
Checking out Supabase.io and it looks super promising! We've been searching for a Firebase alternative for a long time, since Firebase didn't quite fit our needs for a realtime database.

We'd be highly interested in a self-hosted version of supabase.io as privacy is a top consideration.

Couple of questions for you:

1. Should we still use the [docker image you mentioned above]("https://hub.docker.com/r/supabase/supabase-dev") or is there a more up-to-date version?
2. Do you have any published or unpublished self-hosting guides you could point us to?
3. In the self-hosted solution, is it possible to utilize the web-ui you all have built?
4. In the future, do you plan to offer a self-hosted solution as a pricing tier option?

Thanks!
Jonathan

**Comment by kiwicopple** [comment]
Hey @jnpantall 

> Should we still use the docker image you mentioned above or is there a more up-to-date version?

That one is out of date, as we added so many systems we found it hard to stuff into a single docker. Here is something we are working on now: https://github.com/supabase/supabase/discussions/219#discussioncomment-134676

> Do you have any published or unpublished self-hosting guides you could point us to?
> In the self-hosted solution, is it possible to utilize the web-ui you all have built?

Not yet, but more people are asking for it so if you start a Discussison, I can outline the steps to get all the systems up and running. It won't have the Dashboard yet, but we'll open that up in the future.

> In the future, do you plan to offer a self-hosted solution as a pricing tier option?

Yes - we will in the future. We're yet to offer any pricing tiers though 😂 . We're really focused on the hosted platform so we can ship faster.

**Comment by danny-laa** [comment]
@kiwicopple Will the dashboard GUI be open sourced in the future?

**Comment by kiwicopple** [comment]
Probably the part which manages the data (but not the org/project management part). We still haven't put much thought into that part yet as it's a lot of internal co-ordination tooling. Hopefully I will have more info for you in ~6 months once we have finished building the main Firebase features

**Comment by Taha-Firoz** [comment]
> @kiwicopple Will the dashboard GUI be open sourced in the future?

This would be a god send, because sometimes clients want on premises deployments and firebase or any other cloud deployment just won't cut it. ISTG Supabases UI/Dashboard is so good and crisp I wouldn't be surprised if they decide to not open source it.

**Comment by ogtayhuseynov0** [comment]
any update?

**Comment by DavraYoung** [comment]
Will the GUI part be opensource in near future?

**Comment by inian** [comment]
Hi everyone, we have been posting updates in [this thread](https://github.com/supabase/supabase/discussions/1001#discussioncomment-558696)
