### ISSUE TITLE
Allow account creation with email

### ISSUE THREAD

**Issue by jlubeck** [supabase/supabase#853]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, when you try to create a new account on supabase, you are prompted to connect your GitHub account. I would like to be able to use an email that is not associated with GitHub in any way.

## Describe the solution you'd like

Keep GitHub as an option, but also allow accounts to be created with email / password

**Comment by kiwicopple** [comment]
Hey @jlubeck - we will probably allow this at some time in the future, but for now the github login is a very useful filter for us. We aren't ready to start accepting non-techies (the Dashboard UX isn't good enough yet), so we are sticking with GitHub logins until we're ready.

Some time this year!
