### ISSUE TITLE
Add Int2 column type

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#856]
Looking at the [Postgres docs](https://www.postgresql.org/docs/9.1/datatype-numeric.html), Postgres has a small integer datatype that's just 2 bytes long.

Is there a way to add this datatype in Supabase? Currently, I only see options for `Int 4` and `Int 8`.

<img width="607" alt="Screen Shot 2021-03-08 at 4 56 23 PM" src="https://user-images.githubusercontent.com/5659171/110401849-38d16f80-802f-11eb-83a1-4c79a8f15201.png">

_Originally posted by @Nick-Mazuk in https://github.com/supabase/supabase/discussions/839_

**Comment by phamhieu** [comment]
`int2` is available on latest dashboard app.
