### ISSUE TITLE
Cannot signin

### ISSUE THREAD

**Issue by softmarshmallow** [supabase/supabase#8560]
1. Hit signin on supabase.com
2. Redirects to app.supabse.com
3. Hit github login

Gets..

```
https://app.supabase.com/?error=server_error&error_description=For+security+purposes%2C+you+can+only+request+this+once+every+minute
```

with no any visual change
<img width="1301" alt="Screen Shot 2022-08-21 at 12 41 15 AM" src="https://user-images.githubusercontent.com/16307013/185755193-b2dff3b1-e50b-4a89-8791-4025d3dd0053.png">

**Comment by saltcod** [comment]
Hey @softmarshmallow do you get to the Github login page or not even that far? Have you tried in an incognito window?

**Comment by ppborah** [comment]
Supabase login is working fine for me, could you please try it again @softmarshmallow ?

**Comment by softmarshmallow** [comment]
Yeah I made it work. Don't know how. Thank you

**Comment by saltcod** [comment]
Glad you got it worked out. I'll close this one, but please let us know if you run into issues we can help with!
