### ISSUE TITLE
Query editor fails if table uses mixed case

### ISSUE THREAD

**Issue by sroussey** [supabase/supabase#859]
# Bug report

## Describe the bug

Query editor fails if table columns uses mixed case. The query editor forces lowercase and then that does not match the table definition.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Via the UI, create a table call `sample` and make a column called `sampleID` type uuid as PK.

In the query editor, `select * from sample where sampleID = '284d9057-c58c-486f-aff2-eb83125c8d59'`. Instead of zero rows, you get an error:

`column "sampleid" does not exist`

## Expected behavior

No error, zero rows.

## System information

hosted version

**Comment by steve-chavez** [comment]
You need to double quote the identifiers if they use uppercase chars. Like:

```sql
select * from sample where "sampleID" = '284d9057-c58c-486f-aff2-eb83125c8d59'
```

Previously discussed on: https://github.com/supabase/supabase/discussions/619#discussioncomment-315474

This is a PostgreSQL thing. The only way to fix it is at the frontend level: automatically quote identifiers(not sure if it can be done easily).

**Comment by phamhieu** [comment]
I can update auto-complete to detect for uppercase table name and return it with double quote on auto-complete panel.

**Comment by sroussey** [comment]
Great idea!

This is my first time using CamelCase + PostgreSQL combo.

Steven Roussey
