### ISSUE TITLE
Minor, clarifying, language change in auth documentation

### ISSUE THREAD

**Issue by ClarkAulden** [supabase/supabase#8603]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth

## Describe the problem

On the auth documentation page(linked above), the text underneath the heading "Simple interface" uses language that could be considered confusing specifically the phrase "third-providers". 

## Describe the improvement

The phrase "third-party providers" is likely more quickly understood than "third-providers" and so could benefit from being changed.

## Additional context
The issue submitter humbly acknowledges their lack of cutting edge lingo familiarity and the possibility  that this language choice is fully intentional.

**Comment by saltcod** [comment]
Thanks @ClarkAulden !
