### ISSUE TITLE
Change References to supabase-js Next to Release Candidate

### ISSUE THREAD

**Issue by w3b6x9** [supabase/supabase#8611]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/next

## Describe the problem

We're referencing `Next` when we should be calling it `Release Candidate` or `RC` for clarity.

Not sure where else we've called it `Next` but this should be swapped out completely.

**Comment by GaryAustin1** [comment]
The naming of the supabase-js releases for v2 has been confusing.
Currently you need supabase-js@rc for realtime v2.  
At one time v2 was supabase-js@next. 
It is unclear currently what is in the -next chain (v1 or v2).  2.0.0-rc.6 is pretty clear...

 `You can access the supabase-js pre-release, including the new interface by running npm install @supabase/supabase-js@next.`
 Is still in the blog.  https://supabase.com/blog/launch-week-5-hackathon
