### ISSUE TITLE
The generateLink() docs (version Next) needs updated

### ISSUE THREAD

**Issue by t-bowersox** [supabase/supabase#8636]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/next/auth-admin-generatelink

## Describe the problem

I was recently using `generateLink()` in an edge function and noticed that the function signature in the docs doesn't match the implementation in `@supabase/supabase-js@2.0.0-rc.6`. It now accepts a `GenerateLinkParams` object as the only parameter. (And that is actually a union type, so the properties you need to provide vary based on the type of link you're generating.)

## Describe the improvement

I would suggest updating the code snippet at the top of the page to:

```ts
const { data, error } = await supabase.auth.admin.generateLink({
  type: 'signup',
  email: 'email@example.com',
  password: 'secret',
  options: {
    redirectTo: 'http://localhost:3000'
  },
})
```

For the Parameters section, I feel like it would be helpful if there were subsections, one each for each of the `GenerateLinkparams` union types:

- GenerateSignupLinkParams
- GenerateInviteOrMagiclinkParams
- GenerateRecoveryLinkParams
- GenerateEmailChangeLinkParams

That way you can cover the different properties required for each one.

The examples would need rejiggered, too. If it's helpful, here's a new example using the `email_change_current` type (since I was working with it) that you could throw in:

```ts
const { data, error } = await supabase.auth.admin.generateLink({
  type: 'email_change_current',
  email: 'old.email@example.com',
  newEmail: 'new.email@example.com'
})
```

## Additional context

Nope, I think that about covers it. 😄

**Comment by Nike682631** [comment]
@t-bowersox  Is this issue available to work on?

**Comment by t-bowersox** [comment]
@Nike682631 -- yes, I haven't start working on it yet (was waiting to see if the maintainers had any comments).
