### ISSUE TITLE
SQL examples in docs are hidden by default

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#864]
# Bug report

## Describe the bug

On the docs pages for [Database Passwords](https://supabase.io/docs/reference/postgres/database-passwords) and [Creating Tables](https://supabase.io/docs/client/limit), the SQL examples are closed by default. This led me to believe that the examples were empty and unfinished (see earlier versions of this issue).

This is the screenshot of the Database Passwords page's entire contents:

<img width="790" alt="Screen Shot 2021-03-12 at 9 14 03 AM" src="https://user-images.githubusercontent.com/5659171/110974350-4b8bc300-8313-11eb-89e1-40dc17dee38e.png">

It also isn't obvious that the `SQL` text is even a button. The Creating Tables page looks identicle.

## Steps to reproduce

1. On Chrome, open an incognito window
2. Visit the [Database Passwords](https://supabase.io/docs/reference/postgres/database-passwords) and [Creating Tables](https://supabase.io/docs/client/limit) pages

**Note**: It seems like the open/close state of the examples is saved in either local storage or session storage. So you need to use incognito to see the page as a first-time visitor would.

## Metadata

Tested on:
- Safari: 14.0.3
- Brave: 1.21.74 using Chromium: 89.0.4389.72

_P.S. Skipping the rest of the bug report template only because I believe this already covers everything._

**Comment by kiwicopple** [comment]
Wow, you noticed that very fast @Nick-Mazuk . I only pushed that code 8 hours ago

I'm not sure why Docusaurus is closing these by default. I think it's because the Javascript language is "selected" by default, and so then the SQL tabs are closed. 

Thanks for the bug reports
