### ISSUE TITLE
psql slash commands

### ISSUE THREAD

**Issue by sreenik250** [supabase/supabase#8657]
I want to import a table from my local machine to "https://zgyaeycymojyrwunbodq.supabase.co"

\copy NP_MONEY_CONTROL_CONS_QTR FROM 'C:\AShares\NP_MONEY_CONTROL_CONS_QTR_TMP.csv' DELIMITER ',' CSV HEADER;

The above command runs in my local postgresql. I would like to execute in my above link. I am new to supabase.

**Comment by J0** [comment]
Hey @sreenik250 ,

You can do this by making use of the connection string and then going to Settings > Database> Scroll to bottom and find connection string.

Then, you can run `psql -Atx <connection_string>` and then run what you want to run.

Hope this helps! Let me know if you face further issues.

**Comment by sreenik250** [comment]
![psql wrong db](https://user-images.githubusercontent.com/105705010/187840158-5b480f6c-d8ea-44ae-9329-15f08326819d.JPG)

psql -Atx postgres://postgres:Dc89EwSf8eso@db.zgyaeycymojyrwunbodq.supabase.co:6543/postgres
Not connecting to required db.  After giving the above command from local db it is showing local database only.  I am new to Supabase.  Still facing issue.

**Comment by J0** [comment]
Looking into replicating right now but would also like to highlight that we do support importing from CSV. Click on create a new table and the option should show up in the top right

**Comment by J0** [comment]
Unfortunately, I can't seem to replicate the issue -- do you mind running the following command and pasting the output? `\dt auth.*`

**Comment by sreenik250** [comment]
![psql wrong db2 dt](https://user-images.githubusercontent.com/105705010/187844111-4d5c6809-fb3f-4153-a2b8-d1c37b5570b6.JPG)

The above command is run on my local machine

**Comment by J0** [comment]
That's unfortunate,  I've also realised that we do have a guide for copying data:

https://supabase.com/docs/guides/database/tables#bulk-data-loading

Could you follow the instructions here and let us know if the issue still persists?

Thanks

**Comment by sreenik250** [comment]
> 

this worked for me

**Comment by sreenik250** [comment]
https://github.com/supabase/supabase/issues/8657#issuecomment-1233772033

This worked for me

**Comment by sreenik250** [comment]
Looking into replicating right now but would also like to highlight that we do support importing from CSV. Click on create a new table and the option should show up in the top right

The above technique worked for me.  
But the below did not work.  I tried using the sql editor of https://app.supabase.com/project/zgyaeycymojyrwunbodq/sql
and through my local machine also.

![psql wrong db2 copy](https://user-images.githubusercontent.com/105705010/187851423-89b7d66a-28ae-43c2-b3f3-d129b7fb3a3f.JPG)

**Comment by sreenik250** [comment]
Connected directly through DBeaver and imported.  Thank you all.

**Comment by J0** [comment]
@sreenik250 Glad it worked!  Going to close for now but feel free to reach out again if there are further issues.

Thanks!
