### ISSUE TITLE
User Management Starter SQL Snippet doesn't produce public bucket

### ISSUE THREAD

**Issue by HankG** [supabase/supabase#8666]
# Bug report

Following the quick start guide and trying to execute the avatar bonus section I noticed that the uploaded image wasn't retrievable. It uses the "User Management Starter" snippet which includes code on how to setup an "avatars" bucket that should be public. In debugging the problem it doesn't appear that that snippet actually makes a public bucket though.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Execute the "Setup storage" segment of the SQL snippet from the "User Management Starter" :
```sql
insert into storage.buckets (id, name)
  values ('avatars', 'avatars');

create policy "Avatar images are publicly accessible." on storage.objects
  for select using (bucket_id = 'avatars');

create policy "Anyone can upload an avatar." on storage.objects
  for insert with check (bucket_id = 'avatars');

create policy "Anyone can update an avatar." on storage.objects
  for update with check (bucket_id = 'avatars');
```
2. Go into the storage console and confirm that the new bucket does not have the "Public" flag on it.

## Expected behavior

According to the code policy comments the bucket should be public after the first policy line.

## Additional context

Perhaps that is a documentation misnomer and the only way to set it is through an external API call or through the UI (how I overcame this problem).

**Comment by Hallidayo** [comment]
Hi @HankG, have you got a link to the guide you are using?

**Comment by HankG** [comment]
> Hi @HankG, have you got a link to the guide you are using?

The guide is the Flutter quickstart guide: https://supabase.com/docs/guides/with-flutter

But it is telling you to just go to the regular SQL Snippets in the dashboard under the "Quick start" section on the Welcome screen

**Comment by GaryAustin1** [comment]
Going to close this.  It appears the examples (at least currently) do not use getPublicUrl and rely on the bucket being public.   The  current policies in the starter allow download to any user and the examples seem to use download.
