### ISSUE TITLE
Configurable "This is a Production Environment" big-scary-red indicator in Dashboard.

### ISSUE THREAD

**Issue by Marviel** [supabase/supabase#8681]
# Feature request

## Is your feature request related to a problem? Please describe.

It is very easy to get confused when managing multiple environments. As such, it should be possible to configure a "Prod Indicator" for a given database, that indicates it is intended to be a production environment.

This is a VERY UGLY image of what I imagine this would look like:

<img width="897" alt="Screen Shot 2022-08-27 at 12 49 13 PM" src="https://user-images.githubusercontent.com/2037165/187040319-863d73b7-5227-45d2-ba02-6cf22e6168a1.png">

**Comment by MildTomato** [comment]
hi @Marviel - sorry for the radio silence. 

we are actively discussing internally about environment management.

Perhaps what will be best is we share our RFC publicly as it is becoming quite obtuse and the solution is probably now bigger than simply adding arbitrary labels to the dashboard like this.

--

In the meantime, are you able to share your experiences with us? What are you currently doing to mitigate against accidentally making changes to Prod project?

**Comment by saltcod** [comment]
Closing as this is pretty outdated now with environment management about to roll out.
