### ISSUE TITLE
Deep Linking not working / Docs outdated

### ISSUE THREAD

**Issue by Myzel394** [supabase/supabase#8699]
# Bug report

## Describe the bug

I'm following the documentations for setting up Deep Linking on Flutter (https://supabase.com/docs/guides/with-flutter#setup-deep-links), but whenever I click on the link in the email confirmation link I'm greeted with the following message:

```json
{"message": "No API key found in request"}
```

I'm also kind of confused how to setup it correctly, some things are outdated (for example settings up redirect URLs) and there is no clear documentation on how to handle the callback.

## To Reproduce

1. Create auth
2. Sign up 
3. Click on link 

## Expected behavior

No error response & you should be redirected to the app correctly

## System information

- OS: Android, Linux
- Browser: Firefox
- Version of supabase_flutter: 0.3.3

**Comment by xjeventures** [comment]
Is there any update on this on how to get it working?

Also having the same issue in a vue3, nuxt, ionic capacitor setup: "{"message": "No API key found in request"}"

Link seems to do its job (i.e. validating users email) but redirect does not work.

**Comment by dariocast** [comment]
Is there any update on this?

**Comment by dshukertjr** [comment]
@Myzel394 
>and there is no clear documentation on how to handle the callback.

Which callback are you referring to?

@dariocast 
The Flutter quick start guide have been updated to use supabase-flutter v1 with screenshots from the current dashboard. Are you still having trouble signing into your app using magic links?

**Comment by dariocast** [comment]
> @Myzel394 
> >and there is no clear documentation on how to handle the callback.
> 
> Which callback are you referring to?
> 
> @dariocast 
> The Flutter quick start guide have been updated to use supabase-flutter v1 with screenshots from the current dashboard. Are you still having trouble signing into your app using magic links?

Yes, I still receive that apikey not found in request or query param (but a _Token_ is present in query)

**Comment by dshukertjr** [comment]
@dariocast 
What platform are you using, iOS, Android? Also, when you click on the confirmation link in your magic link email, are you presented with the login page again, or are you taken to the Account page?

**Comment by dariocast** [comment]
> @dariocast 
> What platform are you using, iOS, Android? Also, when you click on the confirmation link in your magic link email, are you presented with the login page again, or are you taken to the Account page?

I'm using Android. The link in the email shows the Jason response inside the Gmail  in app WebView, same as if I directly open the link in a browser, without any redirect to app. Testing with adb the deep link works.

**Comment by dshukertjr** [comment]
@dariocast 
Could you upgrade your supabase-flutter version to 1.2.0 and retry?

**Comment by javierguzman** [comment]
Hello @dshukertjr,

I believe indeed something is wrong with deep linking because last month I asked about it on Discussions https://github.com/supabase/supabase/discussions/10754#discussioncomment-4692081 and more people appeared to have the same problem.

Please, let me know if you wish me to create a separate issue.

Thanks in advance

**Comment by dshukertjr** [comment]
@javierguzman 
I recently encountered a user who was having the same problem. https://github.com/supabase/supabase-flutter/issues/327#issuecomment-1379715830 Could you be doing the same thing? You need to enter the full URL on `Site URL` or `Redirect URLs`

**Comment by javierguzman** [comment]
Thanks @dshukertjr  for the quick response. In my particular case, I am creating a React Native app with Expo so my url looks like exp://myip:19000 so I would say is a full URL because exp:// would be similar to write down https://blabla. Does it make sense?

**Comment by hf** [comment]
@javierguzman You are allowed to write down `exp://...` in the redirect URLs.

**Comment by javierguzman** [comment]
Thanks @hf. So I really believe there might be something fishy as I am not the only one who had to implement a workaround to get deep linking working.

**Comment by tarkanlar** [comment]
I am also having the same problem on expo react native

**Comment by tarkanlar** [comment]
I fixed it by adding the full URL  of the deep link in the supabse auth/url-configuration

**Comment by J0** [comment]
Hey  all,

Thanks for the quick feedback. It sounds like a fix has been found so I'm going to go ahead and close this issue.

Let me know if there are still queries.

Thanks!

**Comment by tomelliot** [comment]
I ran into a similar problem (the magic link would return "No API key found in request").

The issue was the supabase auth URL would try to redirect, but would get stuck and return this instead.

Changing the "Redirect URL" in the Web dashboard under Supabase Project > Authentication > URL Configuration to include the https:// at the front fixed it.

As suggested here: https://github.com/supabase/supabase-flutter/issues/327#issuecomment-1379715830
