### ISSUE TITLE
Manifest for docker not found

### ISSUE THREAD

**Issue by Cmarenburg** [supabase/supabase#87]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Hi there, just tried installing via docker with the following docker-compose file

version: '3'

services:
  supabase:
    image: supabase/supabase-dev:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_SCHEMA: public
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

when running `docker-compose up -d` I get error `ERROR: manifest for supabase/supabase-dev:latest not found: manifest unknown: manifest unknown` I can't seem to find a repository more related to docker image. 

All the best

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by awalias** [comment]
hi @Cmarenburg looks like the `latest` tag is missing from our dockerhub repo 

for a quick fix change 
`image: supabase/supabase-dev:latest`
to
`image: supabase/supabase-dev:0.1.9`

and I will work on correcting the tags for future

thanks for catching this

**Comment by awalias** [comment]
@Cmarenburg i've now pushed the `latest` tag: https://hub.docker.com/layers/supabase/supabase-dev/latest/images/sha256-5d84a1c145f4a2049680807b55379d5044b07783ecc38f63a18d7c1d32e03312?context=repo

it should work now
