### ISSUE TITLE
Trigger on 'auth.users' fails if calling other functions

### ISSUE THREAD

**Issue by YukiAttano** [supabase/supabase#8719]
# Bug report

My goal is to, after every registration of a user, create a schema for a new user.

## Describe the bug

A trigger performed after inserting new data into the auth.users table fails if a trigger calls any other function.

Also, supabase stops performing his own actions like inserting or updating a user.

## To Reproduce

I am using the code below which gets triggered after a user is added via 'Supabase - Authentication - Users - Invite' and after accepting his invitation.

I also tried to use 'PERFORM create_user_schema()' or even just call 'CREATE SCHEMA uuid' but nothing works.

I also tried to call a function wich does simply nothing, returning void, didn't work.

```sql
CREATE OR REPLACE FUNCTION user_setup() RETURNS trigger AS $user_setup$
    DECLARE
      s_name uuid := NEW.id;
    BEGIN
        -- cutout content that works so far

        SELECT create_user_schema(CAST(s_name AS TEXT));
        RETURN NULL;
    END;
$user_setup$ LANGUAGE plpgsql;

CREATE TRIGGER user_setup AFTER INSERT OR UPDATE ON auth.users
    FOR EACH ROW EXECUTE FUNCTION user_setup();

CREATE OR REPLACE FUNCTION create_user_schema(s_name text) RETURNS void AS $$
    BEGIN
        EXECUTE 'CREATE SCHEMA ' || quote_ident(s_name);
    END;
$$ LANGUAGE plpgsql;
```

## Expected behavior

I am expecting that the auth.users table still gets filled with its data and a new schema named after the uuid of the user is created.

## Screenshots

![grafik](https://user-images.githubusercontent.com/85680862/187438605-02998fc3-8785-4345-8f03-89553c68255a.png)

## System information

current supabase version.

**Comment by mansueli** [comment]
Have you tried to create the schema following the answer here?
https://stackoverflow.com/questions/63425129/cannot-create-schema-in-function-procedure-in-psql
​
e.g:
​
```
CREATE OR REPLACE PROCEDURE public.create_user_schema(s_name text)
 LANGUAGE plpgsql
AS $procedure$
    BEGIN
        EXECUTE format('CREATE SCHEMA %I', ​s_name);
    END;
$procedure$
```

**Comment by YukiAttano** [comment]
@mansueli Well the function call 'create_user_schema()' works and is not the problem here.
i already tried to call a function that does simply nothing and even this aborted the function trigger.

But nevertheless i tried using this with a procedure, still not working.

Also i tried defining the function without a namespace and within the namespace 'auth'

**Comment by GaryAustin1** [comment]
I had to do 3 things to get it to work:
1) use "security definer" on the trigger function
2) set search_path (or use public.function names)
3) for a void function use perform not select

```
begin
set search_path to auth,public;
raise log 'level1';
perform testlog();
return new;
end;
```
Where testlog is a void returning function.

Note if you go to database/postgres logs you can see the errors being generated.

**Comment by YukiAttano** [comment]
@GaryAustin1 thank you, it finally works.
i think it was just a security problem.
I've put my function in the 'auth' schema and removed the intermediate step.

**Comment by pru10t** [comment]
@GaryAustin1  life saver
