### ISSUE TITLE
Adding non-nullable columns to a table fails silently

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#8740]
# Bug report
Adding non-nullable columns to a table via the 'Edit Table' dropdown selection if that table already has rows, will fail silently.

![CleanShot 2022-08-31 at 07 52 54@2x](https://user-images.githubusercontent.com/105593/187657196-d7fbcea6-cdf7-4019-9249-192528f2e72e.png)

If you have rows in your table, this action will give you a success message, but will actually fail:
![CleanShot 2022-08-31 at 07 53 29@2x](https://user-images.githubusercontent.com/105593/187657329-04a96c7b-115f-44d4-8e13-4d729b95f0ff.png)

**Comment by Hallidayo** [comment]
Hi @saltcod,

When I try this I seem to get a toast/notification:

<img width="367" alt="Screenshot 2022-09-09 at 15 47 31" src="https://user-images.githubusercontent.com/22655069/189378175-77df8e6f-1259-4c6d-89c0-738367f9d385.png">

Is that the expected behaviour?

**Comment by saltcod** [comment]
ooh nice!  Yup. Must have gotten fixed somewhere else. Thanks @Hallidayo
