### ISSUE TITLE
Filter embedded resources not working as expected

### ISSUE THREAD

**Issue by urbanorigins** [supabase/supabase#875]
# Bug report

## Describe the bug

Filtering of embedded resources as in the last example of https://supabase.io/docs/client/filter does not output the correct set of results, but instead returns null as the value for the embedded resource key in the data object.

## To Reproduce

1. Basically the last example (Filter embedded resources) of https://supabase.io/docs/client/filter as mentioned.
2. returns ```[{name: 'Paris', countries: {name: 'France'}}, {name: 'London', countries: null}]```
3. As you can, results matching filter condition return an object with embedded resource but results not matching filter condition are not filtered out and have ```null``` for embedded resource.

## Expected behavior

Should return only results for which countries.name is equal to France.

## System information

- OS: macOs
- Version of supabase-js: v1.6.0
- Version of Node.js: v14.4.0

**Comment by steve-chavez** [comment]
True. This is a pending enhancement on: https://github.com/PostgREST/postgrest/issues/1075.

Right now I'm working on the supabase CLI. Once I'm done with that, I'll come back to fix this issue.

A workaround would be to filter the nulls on client side.

**Comment by kiwicopple** [comment]
Closing this, because it's been fixed for a while :)

https://supabase.com/docs/reference/javascript/filter#filter-embedded-resources

**Comment by cvincentcoleman** [comment]
It looks like this isn't working again :/ 

when running this query I am getting null for Businesses but am still being returned all values
```
    const result = await supabase
    .from('InterviewTemplate')
    .select(`
      *,
      Businesses (
        creator_user_id
      )
    `)
    .filter('Businesses.creator_user_id', 'eq', user?.id!)
```

**Comment by 72L** [comment]
I'm seeing the same issue

**Comment by steve-chavez** [comment]
You need to add `!inner`

```
    const result = await supabase
    .from('InterviewTemplate')
    .select(`
      *,
      Businesses!inner (
        creator_user_id
      )
    `)
    .filter('Businesses.creator_user_id', 'eq', user?.id!)
```
