### ISSUE TITLE
 supabase.auth.api method doesn't exist in rc v2

### ISSUE THREAD

**Issue by SatouKuzuma1** [supabase/supabase#8751]
# Bug report
` supabase.auth.api` method doesn't exist in rc v2
## Describe the bug
api method missing

## To Reproduce
use supabase.auth.api.

## System information

OS: macOS
Version of supabase-js: 2.0.0@rc
Version of Node.js: 17.2

## Additional context
I used the`getUserByCockie()` method to get the session before but now is missing and I couldn't find anything in the docs about this function being deprecated. What would be the alternative to this? `getUser()` maybe? I don't know.

**Comment by J0** [comment]
Hey @SatouKuzuma1 Thanks for the query -- we have indeed deprecated `supabase.auth.api`. It is now addressed as. `supabase.auth.admin`

**Comment by SatouKuzuma1** [comment]
@J0  is there any difference between those two methods? `getUserByCokie()` and `getSession()`

**Comment by J0** [comment]
Hey @SatouKuzuma1,

We've removed `getUserByCookie()` in  Supabase version 2 -- would generally  advise you to use `getSession()` to retrieve the session

**Comment by J0** [comment]
Hey @SatouKuzuma1 ,

Going to close this for now but feel free to re-open if you are still facing issues.

Thanks!
