### ISSUE TITLE
On Safari, the Table Editor forces a value for optional timestamp fields

### ISSUE THREAD

**Issue by tanoabeleyra** [supabase/supabase#8753]
# Bug report

## Describe the bug

On Safari, when inserting a new row through the Table Editor, the user is forced to enter a date for fields that are optional/nullable.
I have tried the same in Chrome and this does not happen.

## To Reproduce

Having a table with an optional date field,

1. Go to "Table Editor"
2. Click on "Insert Row"
3. A date is already entered for the optional field and there is no way to clear it

## Expected behavior

If a timestamp field is optional, there should be a way to clear the field when a date is entered. Moreover, if the default is `NULL`, the field should be blank by default.

## Screenshots
<img width="656" alt="image" src="https://user-images.githubusercontent.com/6851095/187909784-5360ba9e-a50a-42ca-81a1-f3ec1c666d4e.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/6851095/187911295-d70f6200-1d1d-4cf1-9d18-950d2da15170.png">

## System information

- OS: macOS Monterey
- Browser: Safari 15.4

**Comment by saltcod** [comment]
Going to close this one. There's sadly not much we can do with Safari in this instance, minus rewriting our datepicker, which isn't in the near-term plans. In the meantime, the PR noted below fixes the issue where Safari didn't like the date being null.
