### ISSUE TITLE
Connecting to default project won't finish

### ISSUE THREAD

**Issue by gehoida** [supabase/supabase#8755]
# Bug report

## Describe the bug

I used the docker-compose file provided in this repo to start supabase. When I connect to the site, it keeps on saying 'Connecting to Default Project'

Here is my call and the log from the containers. The docker-compose-file is only changed in 2 places where i changed the ports because they are in use elsewhere.

sudo docker-compose up
Starting supabase-kong     ... done
Starting supabase-studio ... done
Starting supabase-db     ... done
Starting supabase-realtime ... done
Starting supabase-meta     ... done
Starting supabase-auth     ... done
Starting supabase-rest     ... done
Starting supabase-storage  ... done
Attaching to supabase-studio, supabase-db, supabase-kong, supabase-meta, supabase-auth, supabase-realtime, supabase-rest, supabase-storage
supabase-auth | time="2022-09-01T14:46:49Z" level=info msg="GoTrue migrations applied successfully"
supabase-auth | [POP] 2022/09/01 14:46:49 info - Migrations already up to date, nothing to apply
supabase-auth | [POP] 2022/09/01 14:46:49 info - 0.0522 seconds
supabase-auth | {"level":"info","msg":"GoTrue API started on: 0.0.0.0:9999"}
supabase-db | 
supabase-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db | 
supabase-db |  2022-09-01 14:46:47.362 UTC [1] LOG:  pgaudit extension initialized
supabase-db |  2022-09-01 14:46:47.462 UTC [1] LOG:  redirecting log output to logging collector process
supabase-db |  2022-09-01 14:46:47.462 UTC [1] HINT:  Future log output will appear in directory "/var/log/postgresql".
supabase-kong | 2022/09/01 14:46:47 [warn] 1#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
supabase-kong | nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: using the "epoll" event method
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: openresty/1.15.8.3
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: built by gcc 9.3.0 (Alpine 9.3.0) 
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: OS: Linux 5.15.0-46-generic
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: start worker processes
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: start worker process 21
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: start worker process 22
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: start worker process 23
supabase-kong | 2022/09/01 14:46:48 [notice] 1#0: start worker process 24
supabase-kong | 2022/09/01 14:46:48 [notice] 22#0: *4 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
supabase-kong | 2022/09/01 14:46:48 [notice] 22#0: *4 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
supabase-kong | 2022/09/01 14:46:48 [notice] 22#0: *4 [kong] init.lua:329 declarative config loaded from /var/lib/kong/kong.yml, context: init_worker_by_lua*
supabase-meta | {"level":30,"time":1662043610846,"pid":1,"hostname":"b76b9ffd5bb1","msg":"Server listening at http://0.0.0.0:8015"}
supabase-meta | {"level":30,"time":1662043610847,"pid":1,"hostname":"b76b9ffd5bb1","msg":"App started on port 8015"}
supabase-rest | 01/Sep/2022:14:46:49 +0000: Attempting to connect to the database...
supabase-rest | 01/Sep/2022:14:46:49 +0000: Connection successful
supabase-rest | 01/Sep/2022:14:46:49 +0000: Listening on port 3000
supabase-rest | 01/Sep/2022:14:46:49 +0000: Config re-loaded
supabase-rest | 01/Sep/2022:14:46:49 +0000: Listening for notifications on the pgrst channel
supabase-rest | 01/Sep/2022:14:46:49 +0000: Schema cache loaded
supabase-studio | 
supabase-studio | > studio@0.0.9 start /usr/src/app
supabase-studio | > next start
supabase-studio | 
supabase-studio | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
supabase-studio | info  - Loaded env from /usr/src/app/.env
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:46:51 +0000] "OPTIONS /rest/v1/%20 HTTP/1.1" 200 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:46:51 +0000] "HEAD /rest/v1/%20 HTTP/1.1" 404 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-storage | running migrations
supabase-storage | finished migrations
supabase-storage | [1662043612039] INFO (7 on 702a809780f8): Server listening at http://0.0.0.0:5000
supabase-storage | Server listening at http://0.0.0.0:5000
supabase-realtime | 2022-09-01 14:46:52.846 [info] Migrations already up
supabase-rest | 01/Sep/2022:14:46:52 +0000: Schema cache loaded
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:46:55 +0000] "HEAD /rest/v1/%20 HTTP/1.1" 404 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:46:59 +0000] "OPTIONS /rest/v1/%20 HTTP/1.1" 200 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:46:59 +0000] "HEAD /rest/v1/%20 HTTP/1.1" 404 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-kong | 192.168.2.3 - - [01/Sep/2022:14:47:02 +0000] "HEAD /rest/v1/%20 HTTP/1.1" 404 0 "http://my.host.com:3000/project/default/editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
supabase-realtime | 2022-09-01 14:47:08.140 [info] Running RealtimeWeb.Endpoint with cowboy 2.8.0 at :::4001 (http)
supabase-realtime | 2022-09-01 14:47:08.140 [info] Access RealtimeWeb.Endpoint at http://localhost:4001

## System information

- Ubuntu
- Chrome

How can i fix that?

**Comment by gehoida** [comment]
It seems to be an issue with other docker container. One used the same port. and some issues with localhost instead if the IP

**Comment by creazy231** [comment]
Can you tell me how you solved this? Have the same problem on a fresh project.

**Comment by gehoida** [comment]
Sure. I ensured, that i did not use any port that is already uses by another docker container. Port 4000 in my case was occupied.

And i changed all localhost strings with the correct domain name.

That was is.
