### ISSUE TITLE
Browser Search/Find Doesn't Work in Studio Table Editor

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#8769]
# Bug report

## Describe the bug

Cmd + F aka Find/Seach doesn't work when viewing tables.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the table editor in studio
2. Click on a table that contains 50+ rows (or enough that you have to scroll)
3. Hit Cmd + F
4. Type in a word or letters you know is in the database (even ones you can see on screen)
5. Results show found items but if you use the arrows or hit enter it negates the results and says 0 found
6.You can't just quickly shuffle through them like any other page 
7. Cry
## Expected behavior

To find in the table on the current page the item you are looking for and go to previous/next found result. This is a critical, as everybody understands the importance of quickly looking for items in a database table.

## System information

- OS: Mac(Daddy)
- Browser (Ra)Safari

## Additional context

Seems maybe the in place cell editor may be overriding?

**Comment by saltcod** [comment]
Hey @jtkeyva !

I just tried this in Safari and it seems to be working for me. 
I did trip up on this contains/begins with dropdown though. Do you have Contains selected there? 

<img width="168" alt="CleanShot 2022-09-06 at 09 48 09@2x" src="https://user-images.githubusercontent.com/105593/188633139-b60479c4-c82a-45d0-bb72-38bf8226b1cf.png">

 
<img width="567" alt="CleanShot 2022-09-06 at 09 47 28@2x" src="https://user-images.githubusercontent.com/105593/188633041-a6e1f0b8-009e-4fd9-8b4e-5ad648e86cd7.png">

**Comment by jtkeyva** [comment]
@saltcod thanks for trying. yes i had contains in the dropdown. i should have mentioned, it happens when there are a lot of rows...looks like you only have a few. can you try on one with 50-100 rows?

**Comment by joshenlim** [comment]
Hey there @jtkeyva - this is because we're using virtualization to render the table editor in the UI, so the rows in the table editor gets dynamically rendered as they come into view, hence why a Ctrl + F wouldn't work if you're trying to search for a row that's outside of the current view.

It'll be best that you use the Filter function for the table editor to search for what you need
![image](https://user-images.githubusercontent.com/19742402/192992036-1f9db065-11d2-4316-92cd-055c95fdacee.png)

Hope this helps!

**Comment by jtkeyva** [comment]
Interesting thanks. It makes it quite more difficult to find a record. Also, partial matches in the filter don't seem to be working. It shouldn't be, but it's faster and easier just to use a 3rd party tool like Hasura...

**Comment by GaryAustin1** [comment]
I believe this issue has been resolved.  Ctrl-F finds values and scrolls the table for 100's of entries.
There is also an ilike/like filter set that takes %iddl% and finds middle.
I'm going to close this, but feel free to comment if I am mistaken on this still being an issue.
