### ISSUE TITLE
Navigation issue between docs and main site

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#881]
# Bug report

## Describe the bug

https://user-images.githubusercontent.com/10214025/111274870-7efe8280-8670-11eb-8d72-da31bcdab96c.mov

## To Reproduce

1. Go to the main website
2. Click on the dropdown to go to the docs
3. Navigate around the docs
4. Click on the logo to go to the main site
5. Hit back <-nothing happens, but URL is updated
6. Hit forward <- nothing happens but URL is now `/new`

## Additional context

This is due to our monorepo setup. It would be interesting to see if this is the same for all vercel monorepos: https://vercel.com/blog/monorepos

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple This issue might already be fixed. I tried to reproduce this issue but I saw no problems.

https://user-images.githubusercontent.com/70828596/142091569-ab88a913-9a3c-43ec-916d-8f2840fc34d8.mov

**Comment by inian** [comment]
Hi @Isaiah-Hamilton, yup this should be fixed now. Thanks for confirming!
