### ISSUE TITLE
accept-profile header ignored when calling a function via REST API

### ISSUE THREAD

**Issue by ian4uia** [supabase/supabase#8850]
# Bug report

## Describe the bug

I have created a function in my application schema and I cannot execute it via the REST API. The error message suggests that Supabase is looking for the function in the public schema even though I have specified the schema in the accept-profile header.  If I create the function in the public schema then I can execute it as expected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the user, schema and a table and test from console.
```
-- Bug reproduction script
-- This script was created from DBeaver logged in as postgres
-- 1. Create user / role which will own access our schema
CREATE ROLE test_app WITH 
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  LOGIN
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT -1;
-- 2. Grant permissions part one. 
GRANT test_app TO postgres;
-- We also need to grant to authenticator but this needs to be done as a superuser so do at the end.
-- 3. Create test Schema
CREATE SCHEMA app_api AUTHORIZATION test_app;
-- 4. Create a table we can use to test schema and access tokens.
CREATE TABLE app_api.my_table (
  id int8 NOT NULL,
  user_name text NOT NULL,
  CONSTRAINT my_table_pk PRIMARY KEY (id)
);
INSERT INTO app_api.my_table (id, user_name) VALUES (1, 'IanJ');
-- 5. Grant privs
GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA app_api TO test_app;
GRANT USAGE ON SCHEMA app_api TO test_app;

-- 6. Test from console. One row returned.
SELECT * FROM app_api.my_table;
```
2. Go to Supabase dashboard and configure API
2.1. From SQL Editor:
`grant test_app to authenticator;`
2.2. Go to Settings -> API and:
2.2.1 Add app_api to Exposed schemas
2.2.2 Add app_api to Extra search paths

3. Generate Auth token for new role and test API
```
curl -H "accept-profile: app_api" \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dmhkdmdjY3B1d3Rrd25kbnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjIzODU3MzYsImV4cCI6MTk3Nzk2MTczNn0.dukZBlxP7CSN9sGrAQzFNQNg6tqIVvgaWfQzV7M2WZQ" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dmhkdmdjY3B1d3Rrd25kbnRxIiwicm9sZSI6InRlc3RfYXBwIiwiaWF0IjoxNjYyMzg1NzM2LCJleHAiOjE5Nzc5NjE3MzZ9.Rx5nGirqpW3WuPXOEaByRDmSbP6JK3C0FdrQekfm3Tw" \
-v https://ayvhdvgccpuwtkwndntq.supabase.co/rest/v1/my_table
```
4. Now our schema is setup and working we can create a function
```
CREATE OR REPLACE FUNCTION app_api.say_hi(p_json_args json)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
declare
begin
  return format('{"status_code":200, "result":{"hello":"%s"}}', p_json_args->>'name')::json;
exception
  when others then
    return format('{"status_code":500, "error":{"message":"%s"}}', replace(SQLERRM,'"','\"'));
end
$function$
;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app_api TO test_app;
-- Test it from console.
select app_api.say_hi('{"name":"Ian"}'::json)
```
5. Now try to execute function from API
```
curl -X POST \
-H "Content-Type: application/json" \
-H "accept-profile: app_api" \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dmhkdmdjY3B1d3Rrd25kbnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjIzODU3MzYsImV4cCI6MTk3Nzk2MTczNn0.dukZBlxP7CSN9sGrAQzFNQNg6tqIVvgaWfQzV7M2WZQ" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dmhkdmdjY3B1d3Rrd25kbnRxIiwicm9sZSI6InRlc3RfYXBwIiwiaWF0IjoxNjYyMzg1NzM2LCJleHAiOjE5Nzc5NjE3MzZ9.Rx5nGirqpW3WuPXOEaByRDmSbP6JK3C0FdrQekfm3Tw" \
-H "Prefer: params=single-object" \
-d '{"name":"Ian"}' \
https://ayvhdvgccpuwtkwndntq.supabase.co/rest/v1/rpc/say_hi
```
6. See error!
`{"code":"PGRST202","details":null,"hint":"If a new function was created in the database with this name and parameters, try reloading the schema cache.","message":"Could not find the public.say_hi function with a single json or jsonb parameter in the schema cache"}`

## Expected behavior
The function should return the result:
`{"status_code":200, "result":{"hello":"Ian"}}`

## Screenshots
N/A

## System information

- OS: [CentOS-7]
- Browser (if applies) [N/A]
- Version of supabase-js: [ How do I find out the version of https://app.supabase.com/ ?]
- Version of Node.js: [N/A]

## Additional context

If I create an identical function in the public schema then the curl command in point 5 returns the correct response.

**Comment by GaryAustin1** [comment]
I have used the accept-profile header before and it works...
`if (schema) requestInit.headers['Accept-Profile'] = schema`

You likely need to grant test-app to authenticated and/or anon roles as they will be the ones running the function.

**Comment by GaryAustin1** [comment]
Going to close this.  If this is still an issue it can be reopened.
