### ISSUE TITLE
Add Stackshare link to our footer

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#89]
We were somehow picked up by Stackshare, so we should add the link to our footer in the "Community" section: https://stackshare.io/supabase

(While we're at it, we should add the Product Hunt link).

**Comment by Exploringtechnologies** [comment]
i want to work in this issue

**Comment by kiwicopple** [comment]
Go for it @Exploringtechnologies ! you can just add the link here: https://github.com/supabase/supabase/blob/e7ca3063ec6e9028c91384547bd8ed75831bf981/web/docusaurus.config.js#L143
