### ISSUE TITLE
Installing Logflare for Slack integration 404 Result

### ISSUE THREAD

**Issue by aldoyh** [supabase/supabase#8902]
Fastest way to explain is with a video:

https://www.dropbox.com/s/iufiqi9tqeqyzbi/svid_20220911_192932_1.mp4?dl=0

https://user-images.githubusercontent.com/5215449/189539419-40d87b4b-9921-4e7a-a60e-b78e7123a44e.mp4

Thank you for all the wonders you opened to us 💝

**Comment by Ziinc** [comment]
Thanks @aldoyh for reporting this, this has been fixed in the main Logflare repo,  PR [here](https://github.com/Logflare/logflare/pull/1355)
