### ISSUE TITLE
resetPasswordForEmail() Example does not work.

### ISSUE THREAD

**Issue by bennik88** [supabase/supabase#8903]
# Improve documentation

## Link 
[Docs Link](https://supabase.com/docs/reference/javascript/next/auth-resetpasswordforemail)

## Describe the problem
The `resetPasswordForEmail()` code example in the docs has `options` as an argument passed down to the function which can't work as `options: { redirectTo: "" }` is no valid object without curly brackets. Like so `{ options: { redirectTo: "" }}`. After looking deeper at this issue I found out to skip the option key completely. So the docs should be improved like written below under **Describe the improvement**.

Also, I don't understand the security behind `resetPasswordForEmail` as it seems the user is always able to just use 
```js
const { error, data } = await supabase.auth.updateUser({
  password: new_password,
})
```
even without calling `resetPasswordForEmail` before that. The update function and change rights are always working without needing to invoke the `resetPasswordForEmail` function. Shouldn't `resetPasswordForEmail` not prevent the password from being changed without verifying the user before it? 

Current docs:
```js
const { error, data } = await supabase.auth.resetPasswordForEmail(email, options: {
  redirectTo: 'https://example.com/update-password',
})
```

## Describe the improvement
Remove the `options:` key. from args. To prevent users from debugging and looking for the actual object to pass.
Improvement of example:
```js
const { error, data } = await supabase.auth.resetPasswordForEmail(email, {
  redirectTo: 'https://example.com/update-password',
})
```

**Comment by pencilcheck** [comment]
Already using the new way of doing things, still doesn't work and not respected
