### ISSUE TITLE
Can't create a new bucket using Supabase UI

### ISSUE THREAD

**Issue by Mau-MD** [supabase/supabase#8909]
# Bug report

## Describe the bug

When I'm trying to create a new bucket using Supabase UI, it shows a toast with the following error `relation "public.buckets" does not exist`. Tried to create the bucket multiple times with different names but it's not working.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to any supabase project
3. Click on storage button on the left navbar
4. Try to create a bucket using the modal form
5. See error

## Expected behavior

Be able to create a bucket 

## Screenshots

![image](https://user-images.githubusercontent.com/74751751/189565282-20a60341-75d2-4f9d-bc1f-816e637c890e.png)

## System information

- OS: Windows with WSL 2
- Browser (if applies) Microsoft Edge Version 105.0.1343.33 (Official build) (64-bit)
- Version of supabase-js: 2.0.0-rc.10
- Version of Node.js: 16.17.0

**Comment by inian** [comment]
Hi this issue has been resolved and we are monitoring the fix now. Please follow our [status page](https://status.supabase.io/) for updates.
