### ISSUE TITLE
Broken footer link on home page

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/supabase#892]
# Bug report

## Describe the bug

The [Case Studies](https://supabase.io/blog/tags/case-study) link in the footer is broken at https://supabase.io.

## To Reproduce

Just go to the footer and click on the link.

**Comment by kiwicopple** [comment]
Ah, looks like we missed this when migrating our blog from Docusaurus to next.js. We need to set up a new route for tags.

Thanks for the bug report @florian-lefebvre - we'll get to this shortly (unless someone gets to it before us)

**Comment by thakkaryash94** [comment]
Hey @kiwicopple , I am working on this. I have created same route `/blog/tags/[tag].tsx` and created static pages using getAllCategories() and getSortedPosts(limit, tag). I want to ask few questions listed below.

1. how we are planning to show the blog list? I mean in the grid, like we are doing on the blog home page with featured blog or like list, that we have on the blog home page with category filter dropdown section.
2. how do we want the header of the tag-based filter blog page? Like keeping the same as blog home page and keeping the title as "${tag} blogs"?

Thanks

**Comment by kiwicopple** [comment]
legend, thanks @thakkaryash94 !

> how we are planning to show the blog list? 

I think like you say: like we are doing on the blog home page. But we don't need the featured items at the top, we just need the list

> keeping the same as blog home page and keeping the title as "${tag} blogs"?

Yeah! but perhaps "${tag} posts" (instead of "blogs").

Thanks a lot @thakkaryash94 - this would be an awesome contribution

**Comment by thakkaryash94** [comment]
@kiwicopple I have completed the changes. Waiting for the feedback.
