### ISSUE TITLE
Cascade delete checkbox when adding foreign keys relations

### ISSUE THREAD

**Issue by Jaaneek** [supabase/supabase#8975]
# Feature request
Add possibility to enable cascade delete when working with supabase dashboard
## Is your feature request related to a problem? Please describe.
You need to manually write SQL to add cascade delete, it's very repetitive.
A clear and concise description of what you want and what your use case is.
I would like to delete all user data from database, when you try to do it without cascade you will get an error.

## Describe the solution you'd like
Simple checkbox when creating foreign relations
I want users to be able to delete all of their data.
## Describe alternatives you've considered
I do not have any other alternatives in mind

<img width="428" alt="image" src="https://user-images.githubusercontent.com/25470423/190236492-e433de38-9216-43a5-bb0f-b5f304972971.png">

**Comment by saltcod** [comment]
Hi there! Cascade deletes are on our hopefully-very-soon roadmap! Going to close this issue, but we're hoping to get rolling on it in the next month or so. Thanks!
