### ISSUE TITLE
Error querying the database: db error: FATAL: no more connections allowed (max_client_conn)

### ISSUE THREAD

**Issue by icecreamwebdev** [supabase/supabase#8985]
# Bug report

I'm still getting max_client_conn when using prisma with supabase. 

i've added pgbouncer to the database string like so:

`postgres://postgres:blank@db.blank.supabase.co:1234/postgres?sslmode=require&pgbouncer=true&pool_timeout=45`

I've ensured i'm only generating one prisma client as per their docs in 

But still get the following error:

`ERROR	PrismaClientInitializationError: Error querying the database: db error: FATAL: no more connections allowed (max_client_conn)`

I'm not sure if this is on prisma, or supabase's side so opened a ticket in both as per suggestion.

**Comment by thesquaredD** [comment]
Hi! Have you found any solutions?

**Comment by GaryAustin1** [comment]
This is an extremely stale issue, was this ever resolved.  
The current Supabase guide is for the string to look like this:
`postgres://postgres:[YOUR-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:6543/postgres?pgbouncer=true&connection_limit=1"`
https://supabase.com/docs/guides/integrations/prisma
I'm going to close this.  Please feel free to open a new issue with more information if needed.
Thanks

**Comment by relferreira** [comment]
Unfortunately I still get this error:

The log from PGBouncer is:
```
Event Message
C-0xaaaaf95c0f70: (nodb)/(nouser)@54.151.33.111:57534 closing because: no more connections allowed (max_client_conn) (age=0s)
```

I'm already using the recommended connection string:
```
postgres://postgres:XXXXXXXX@db.rttbvfqddsmvpgbdwejd.supabase.co:6543/postgres?pgbouncer=true&connection_limit=1
```

I'm using Nextjs + prisma
Deployed on Vercel
