### ISSUE TITLE
Mac M1 supabase start error : No such image: public.ecr.aws/t3w2s2c9/postgres:14.1.0.66

### ISSUE THREAD

**Issue by jymen** [supabase/supabase#8993]
# Bug report
On Mac M1 macOS 12.5.1
## Describe the bug
Running supabase start (after successfully running login and init ) 
Fails after downloading successfully some packages  with message :
Error: Error response from daemon: No such image: public.ecr.aws/t3w2s2c9/postgres:14.1.0.66

## To Reproduce
just rue supabase start on mac M1
Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: Macosx M1 12.5.1

**Comment by martinboksa** [comment]
Same on `Mac 2.4 GHz 8-Core Intel Core i9`

**Comment by ZetiMente** [comment]
I have MacOS m.1 12.4 and had the same issue. The solution was to install Docker Desktop. If Docker isn't running, it will say it can't find the image, instead of saying it's not running. https://docs.docker.com/desktop/install/mac-install/

**Comment by burmecia** [comment]
Did you upgrade to latest supabase CLI? It all work fine on my laptop, I am using supabase CLI v1.4.6 and Mac M1.

**Comment by martinboksa** [comment]
> I have MacOS m.1 12.4 and had the same issue. The solution was to install Docker Desktop. If Docker isn't running, it will say it can't find the image, instead of saying it's not running. https://docs.docker.com/desktop/install/mac-install/
I have a desktop version; even I tried to reinstall but it didn't help


> Did you upgrade to latest supabase CLI? It all work fine on my laptop, I am using supabase CLI v1.4.6 and Mac M1.
ye, 1.4.6

![Screenshot 2022-09-19 at 09 25 58](https://user-images.githubusercontent.com/4490694/190968402-a5effc61-99c7-45b8-98f1-3d11322dffe5.png)

**Comment by BarakChamo** [comment]
Having the exact same problem with supabase CLI `1.4.9` and Docker Desktop `4.12.0` on an M2 Mac.

**Comment by jiyelileona** [comment]
<img width="807" alt="Screen Shot 2022-09-30 at 11 04 39 AM" src="https://user-images.githubusercontent.com/71301404/193311325-8fcc9940-fa03-4440-affc-95461f8017ea.png">
same here, new Mac M2, everything is the latest version

**Comment by burmecia** [comment]
Can you try run below command to make sure Docker can pull the correct image? For example,
```
docker pull public.ecr.aws/t3w2s2c9/kong:2.8.1
```

And then check it using command,
```
docker images -a public.ecr.aws/t3w2s2c9/kong:2.8.1
```

It should output something like below,
```
REPOSITORY                     TAG       IMAGE ID       CREATED       SIZE
public.ecr.aws/t3w2s2c9/kong   2.8.1     ef17c5908a08   8 weeks ago   149MB
```

This is to make sure Docker can work properly before we run `supabase` CLI.

**Comment by martinboksa** [comment]
I tried to pull only postgre image (`docker pull public.ecr.aws/t3w2s2c9/postgres:14.1.0.71`) and it showed me some docker error `no space left` so I fixed this error and vuala it works now! 🚀

**Comment by burmecia** [comment]
That's great, I will then close this ticket, feel free to reopen if this is still an issue.
