### ISSUE TITLE
Project dashboard unusable on mobile 

### ISSUE THREAD

**Issue by fedorish** [supabase/supabase#9018]
# Bug report

## Describe the bug

When browsing the app dashboard on a mobile (iPhone 12 iOS 16.1), the level 2 menu takes up most of the screen without the ability to close/minimize it. Which makes it pretty much unusable on mobile/iPhone, not a common use case perhaps but could be nice have a smooth experience on mobile if needed. 

## To Reproduce

1. Go to a project dashboard on (any mobile?) an iPhone 12 with iOS 16.1
2. Navigate through different menu items

## Expected behavior
Smoother experience using mobile, e.g. ability to minimise level 2 menu.

## Screenshots
![supabase_ui](https://user-images.githubusercontent.com/22777727/190876781-086e20ff-158d-4379-8983-5c4962294ded.jpeg)

## System information

- iPhone 12
- OS: iOS 16.1
- Safari / Brave / Firefox

**Comment by saltcod** [comment]
Hey @fedorish thanks for the report. 

Quoting our CEO:
`At the moment we don't plan to support mobile - there is too much work involved to make a dashboard application like ours work on such a small device, and it would really slow down our development.
`

https://github.com/supabase/supabase/pull/9129#issuecomment-1258122771
