### ISSUE TITLE
Failed to toggle PGSODIUM: failed to create pg.extensions: relation "pgsodium.key" does not exist

### ISSUE THREAD

**Issue by ZetiMente** [supabase/supabase#9020]
# Bug report
Failed to toggle PGSODIUM: failed to create pg.extensions: relation "pgsodium.key" does not exist
## Describe the bug
Having trouble syncing my local database to remote because of the error in issue supabase/cli#477. So tried to toggle off the extension in the dashboard just to get the database to reset. However, this failed as well with the error: Error: ERROR: role "pgsodium_keyiduser" does not exist (SQLSTATE 42704). So when to turn the extension back on in the dashboard, this is the error message that appears and can not turn pgSodium back on. 

So pgSodium is broken when doing the migration with db reset and it's broken when attempting to toggle back on after turning it off. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Dashboard - Extension
2. Click on PGSODIUM
3. TOGGLE IT OFF
4. ATTEMPT TO TOGGLE IT ON

## Expected behavior

Able To Toggle Back On. 

## Screenshots

<img width="372" alt="Screen Shot 2022-09-17 at 8 53 42 PM" src="https://user-images.githubusercontent.com/76985631/190882320-be5d2230-8c06-4401-aa87-2f91b10007b0.png">

## System information

- Browser Chrome

**Comment by ZetiMente** [comment]
This bug is annoying too bc it's a UI page. :/

**Comment by sweatybridge** [comment]
Hi @ZetiMente , I tried to reproduce this issue on a fresh project and realised that you need to select the `pgsodium` schema instead of the default `extensions` schema when turning the extension back on.
![Screenshot 2022-09-27 at 12 22 58 AM](https://user-images.githubusercontent.com/1639722/192329965-b8f89f12-0de0-4769-84cd-a1609cdc8a33.png)

Let me know if it works for you.

**Comment by ZetiMente** [comment]
@sweatybridge Hey! That did the trick ! Maybe a good idea to set "pgsodium" as the default for people in the future but this worked so I'll close the issue.
