### ISSUE TITLE
Edge Function: TypeError Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Mechse** [supabase/supabase#9021]
# Bug report

## Following error occurred while developing an edge function:

```
TypeError: Class extends value undefined is not a constructor or null
    at file:///src/main.ts:40003:33
``` 

## I tracked it down to using this in my edge function:

```ts
const decoder = new TextDecoder();
```

The script works when testing outside the supabase ecosystem.

## System information

- OS: macOS
- Version of supabase-js: [e.g. 6.0.2]
- deno 1.25.2 (release, x86_64-apple-darwin)
   v8 10.6.194.5
- typescript 4.7.4

Had anyone a similar error?

**Comment by burmecia** [comment]
Hi @Mechse , thanks for reporting this issue. Would you mind share your code which has the error or can you provide more reproduce steps? That will help us to identify this root cause, thanks.

**Comment by laktek** [comment]
Closing this ticket due to inactivity.
