### ISSUE TITLE
Unable to enable Vault in database

### ISSUE THREAD

**Issue by thestepafter** [supabase/supabase#9023]
### Discussed in https://github.com/supabase/supabase/discussions/9022

<div type='discussions-op-text'>

<sup>Originally posted by **thestepafter** September 17, 2022</sup>
I am following this documentation [https://supabase.com/blog/supabase-vault](https://supabase.com/blog/supabase-vault).

but the command:

`create extension vault with schema vault;`

is throwing the following error:

**[58P01] ERROR: could not open extension control file "/var/lib/postgresql/extension/vault.control": No such file or directory**

I haven't been able to find any other documentation on enabling Vault and I don't see it on the database extensions page in the UI.</div>

**Comment by darora** [comment]
Closing as [answered on the discussion](https://github.com/supabase/supabase/discussions/9022#discussioncomment-3673679); there'll be an announcement when it's available on the hosted platform.
