### ISSUE TITLE
Allow VARCHAR to fulfill it's original usage with limitation: VARCHAR(limit)

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#9024]
# Feature request

## Problem description

Originally VARCHAR was used to specifically put limits on a Text such as VARCHAR(250).
This makes sense to constrain data.

However in the UI this is not possible:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/9058762/190897630-ec22fd2b-2ae5-48c9-ba47-7f40096460c2.png">

You see that you can only choose VARCHAR without params which probably is an unlimited VARCHAR (or else: if not then it's even more confusing)

## Describe the solution you'd like

Provide a possibility to either parametrize VARCHAR or remove it completely from the select menu as otherwise it's extremely confusing.

**Comment by GaryAustin1** [comment]
Selecting varchar now has a warning against use in the UI...
![image](https://user-images.githubusercontent.com/54564956/217982444-7090f659-d23a-4932-b470-5abca7f501c1.png)
Going to close this based on that change.

**Comment by activenode** [comment]
Fair enough, thanks!

**Comment by activenode** [comment]
I've read the docs again for that recommendation. And it isn't really that VARCHAR is not recommended. Rather it is not recommended when it doesn't make sense.

But say you wanted to have a table and you know right away the fields not gonna get bigger than `VARCHAR(20)` then having varchar + additional field to set the maxlength would be very helpful actually.

**Comment by GaryAustin1** [comment]
You can certainly use the SQL editor.  There are other column types also not supported in the UI.
