### ISSUE TITLE
Remove auto submit on filter keypress in tables in the dashboard

### ISSUE THREAD

**Issue by crushingCodes** [supabase/supabase#9035]
# Feature request

## Is your feature request related to a problem? Please describe.
When typing in foreign languages such as Japanese, you need a chance to select your characters based on what you type. Currently it automatically applies as soon as you type, and you dont get a chance to select the correct characters.

In the screenshot i want to select 五 but it cuts me off and submits ご.
![Screen Shot 2022-09-19 at 5 24 15 pm](https://user-images.githubusercontent.com/26400289/190978071-76a83836-e386-4178-a6a8-fe7cc26b07de.png)

This is the panel I should be able to choose from before submitting.
![Screen Shot 2022-09-19 at 5 28 39 pm](https://user-images.githubusercontent.com/26400289/190978264-905420e0-d2e6-46fb-a7a7-6b3d50716d23.png)

## Describe the solution you'd like
Remove auto apply, add apply button, or possibly waiting until Enter is pressed would be fine

## Describe alternatives you've considered

I have to type the japanese in another app such as notes and copy and paste to supabase

**Comment by saltcod** [comment]
Thanks @crushingCodes — totally agree. 
Going to track this here: 
https://github.com/supabase/supabase/issues/9301
