### ISSUE TITLE
Can't create organization...so can't create project

### ISSUE THREAD

**Issue by jake-chambers** [supabase/supabase#9046]
# Bug report

## Describe the bug

- Cannot create organization, which means I can't create project

## To Reproduce

- Click new project then try to create an organization

## Expected behavior

- Can get past the Create organization page

## Screenshots
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/23714923/191165765-999ba548-4065-469d-a200-2f8b55b3e5f6.png">

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/23714923/191166123-4f81fdaa-2b3b-4fcb-9460-cb2c6d2688a9.png">

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: web
- Version of Node.js: N/A

**Comment by semistatic** [comment]
Experiencing the same issue - Mac OS, Edge

**Comment by darora** [comment]
We're working on a fix for this issue ; https://status.supabase.com/incidents/snv02y60gg4m

**Comment by darora** [comment]
We've deployed a fix - things should be working again.
