### ISSUE TITLE
Create "signInByToken" method

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#906]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently there isn't a way to perform requests as a user given their access token. This limits how you can use Supabase on a server.

Take, for instance, server side rendering. If you have auth policies preventing certain users from accessing certain pieces of data, then you cannot use server side rendering with Supabase. It is possible to replicate the same functionality by placing limits on the query. But this will not be kept up-to-date with the auth policies.

### Example

Let's look at a simple example. While this specific example has a trivial solution, hopefully it will help make everything clear.

Assume you have a `posts` schema, and you want to SSR a dashboard page with all the posts. You have an auth policy in place to ensure users only view their own posts (`auth.uid() = uid`). On the front end, you can simply get all the posts and Postgres's row level security will filter everything out.

```js
const { data, error } = await supabase.from('posts').select('*')
```

However, you want to use SSR. This means row-level security won't be applied since you are an admin (or superuser, or whatever it's called in Postgres). So you have to filter out the posts manually. Additionally, you also need to validate the token manually.

```js
import { verify } from 'jsonwebtoken'

const decodedToken = verify(token, process.env.SUPABASE_JWT_SECRET)
const { data, error } = await supabase.from('posts').select('*').match({ uid: decodedToken.id })
```

Now this is not too complicated, but for every auth policy you have, you need to replicate that in your server side code. This is ripe for future security/privacy bugs. Because as you update your auth policies, you need to update every piece of server side code.

## Describe the solution you'd like

**Ideal**: add another option for signing in via an access token.

```js
const { user, session, error } = await supabase.auth.signIn({
  accessToken: accessToken,
})
```

**Less ideal**: This will work, but it's not as future proof. If Supabase adds a new feature (e.g., storage) that allows for auth policies, this solution will not apply the authentication without also implementing it in the new feature.

```js
const { data, error } = await supabase.from('posts').select('*').asUser(accessToken)
```

**Comment by kiwicopple** [comment]
Hey @Nick-Mazuk , I think you're looking for this method:

https://github.com/supabase/gotrue-js/blob/1076cb3afb6d58bc0f50ecca84b0a9e0587346ba/src/GoTrueApi.ts#L210

```js
const { user, error } = await supabase.auth.api
  .getUser(access_token)
```

I'll close this, but feel free to reopen if I've misunderstood

**Comment by erikash** [comment]
@kiwicopple isn't `supabase.auth.getSession()` is enough for validating the current session?

`getUser` does an http request to fetch the user details which is redundant...

Or am I missing something?
