### ISSUE TITLE
Add an example of using GitHub actions to keep type definitions up-to-date

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#907]
# Improve documentation

## Link 

https://supabase.io/docs/client/generating-types

## Describe the problem

Generating TypeScript types with Supabase is great. The only problem? They can get out of date.

## Describe the improvement

To fix this, I created a GitHub action that automatically updates the TypeScript definitions on a schedule. I think other Supabase users could find it helpful.

So I'd like to add a section to the "Generating Types" page on how to set this up.

If this sounds like something you'd like an improvement you'd like to the docs, let me know and I'll create a PR.

**Comment by kiwicopple** [comment]
Sure we'd love that!
