### ISSUE TITLE
Cannot read properties of undefined (reading 'session')

### ISSUE THREAD

**Issue by bhargavAtgithub** [supabase/supabase#9083]
# Bug report
Cannot read properties of undefined (reading 'session') after using supabase.auth.session();
on Next.js 

## Describe the bug
I'm trying to follow this official link by supabase. [https://supabase.com/docs/guides/with-nextjs](https://supabase.com/docs/guides/with-nextjs)
I've tried
supabase.auth.session()
```
   useEffect(() => {
          getProfile();
   }, []);


const getProfile = async () => {
        try {
            console.log('getProfile');
            const user = await getCurrentUser();
            console.log(user);

            let { data, error, status } = await supabase
                .from('profiles')
                .select()
                .eq('id', user.id)
                .single();

            if (error && status !== 406) {
                throw error;
            }

            if (data) {
                setUser({ ...data, email: user.email });
                setSession(true);
            }
        } catch (error) {
            console.log(error);
        }
    };

 const getCurrentUser = async () => {
        try {
            console.log('getCurrentUser');
            const {
                data: { session },
                error,
            } = await supabase.auth.session();

            console.log(session, error);

            if (error) {
                throw error;
            }

            if (!session?.user) {
                throw 'USER_NOT_SIGNED_IN';
            }
            setSession(true);
            return session.user;
        } catch (error) {
            console.log(error);
        }
    };

```
throws me error
```
TypeError: Cannot read properties of undefined (reading 'session')
```

Also tried with getSession

```
    const {
        data: { session },
      } = await supabase.auth.getSession()

```
but that gives me error
```
TypeError: _config_supabaseClient__WEBPACK_IMPORTED_MODULE_2__.supabase.auth.getSession is not a function
```
using in 
 "next": "12.3.0"

## System information
- OS: [e.g. macOS(m1)]
- Browser - chrome
- "@supabase/supabase-js": "1.35.6",

**Comment by GaryAustin1** [comment]
The guide says it is using RC/V2.  You are using 1.35.6.
session() in version 1 returns session.
getSession in version 2 returns data object with session in it.
You would need to use supabase-js v2.0.0

**Comment by bhargavAtgithub** [comment]
I've tried both session and getSession, two different errors. I've mentioned both.

**Comment by GaryAustin1** [comment]
Yes, but you are on v1 code "@supabase/supabase-js": "1.35.6", and getSession won't work (which uses the return variable data).
Then you use session which works with v1 but you are using the wrong return value as it returns a variable session not data.
So you need to use both the same return variable and call for which ever version you want to work on.

**Comment by bhargavAtgithub** [comment]
yes, you are right. It worked.
