### ISSUE TITLE
How to replicate throwOnError() in V2

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#9089]
`.throwOnError()` has been removed in V2, but library like `SWR `needs to throw error to work properly.  

Example
`const { data, error } = useSWR('/api/user', fetcher)`
Here `error `is thrown by `fetcher`.

Where fetcher is 

```
  const fetcher = async () =>
                        await supabaseClient .from("books_articles")
                          // .throwOnError()
                         .eq("created_by", user?.id);
```

**Comment by chrisb2244** [comment]
Isn't it possible to write something like
```
const fetcher = async () => {
    const { data, error } = await supabaseClient.from("books_articles").eq("created_by", user?.id);
    if (error) throw error;
    return data;
```
?

**Comment by roker15** [comment]
> Isn't it possible to write something like
> 
> ```
> const fetcher = async (key: string) => {
>     // maybe get userId from the key
>     const { data, error } = await supabaseClient.from("books_articles").eq("created_by", user?.id);
>     if (error) throw error;
>     return data;
> }
> ```
> 
> ? (also, I guess user has to be defined somewhere, and maybe the fetcher has a key?)

Yes but we have replaced a single word with multiple lines.. `.throwOnError()` was better experience.

**Comment by chrisb2244** [comment]
Didn't I just replace one line with another?
I mean, I'm not against having a ThrowOnError method, and you might be against `if (error) throw error` without braces or line breaks (guess you could add braces and still be just one line...), but as a workaround I think they should be the same (and approximately the same length?)

**Comment by kiwicopple** [comment]
Hey @roker15 - we mentioned this in our [release notes](https://supabase.com/docs/reference/javascript/release-notes#all-changes) for v2, but we removed this until it's properly supported across all libraries (because we consider it unsafe to offer it if not _all_ errors are thrown

For now you can use the snippe that @chrisb2244 suggested - that's what the library was doing under the hood :)
