### ISSUE TITLE
Incorrect tags for release 0.22.03 and 0.21.11.30

### ISSUE THREAD

**Issue by sstopkin** [supabase/supabase#9092]
At that moment tags for  [0.21.11.30](https://github.com/supabase/supabase/tree/0.21.11.30) and [0.22.03](https://github.com/supabase/supabase/tree/0.22.03) are pointed to the same commit hash https://github.com/supabase/supabase/commit/af436bfcd930a551b9596c039d88f2459a65df5f. It looks like an issue.

Also [0.20.11.30](https://github.com/supabase/supabase/releases/tag/0.20.11.30) tag has been released in 2021 but has a version related 2020. It has a same release date with [0.21.11.30](https://github.com/supabase/supabase/releases/tag/0.21.11.30), so it seems like 0.20.11.30 has been released by mistake and should be deleted.

**Comment by kiwicopple** [comment]
> [0.20.11.30](https://github.com/supabase/supabase/releases/tag/0.20.11.30) tag has been released in 2021 but has a version related 2020

Agreed, deleted

> At that moment tags for [0.21.11.30](https://github.com/supabase/supabase/tree/0.21.11.30) and [0.22.03](https://github.com/supabase/supabase/tree/0.22.03) are pointed to the same commit hash

I think that's becuase [this release](https://github.com/supabase/supabase/releases/tag/0.21.11.30) accidently had "add a tag" checked, whereas it was probably better just as an informative release. For now I think I will leave it - i'm concerned that if I delete the tag it could affect the github Release history

Thanks for this @sstopkin - I'll close the issue
