### ISSUE TITLE
Table Editor doesn't allow default values like `CURRENT_DATE`

### ISSUE THREAD

**Issue by b2m9** [supabase/supabase#9096]
# Bug report

## Describe the bug

The Table Editor in Studio doesn't allow default values like `CURRENT_DATE`. However, it works as expected when done via SQL (both creating and altering a table).

## To Reproduce

1. Create a new table:

```sql
CREATE TABLE testdate (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL
);
```

2. Go to Table Editor and add default value `CURRENT_DATE` to column `date`.

This results in the notification: Failed to update column "date": failed to update pg.columns with the given ID: invalid input syntax for type date: "CURRENT_DATE"

## Expected behavior

When using SQL directly, you can set the default value and it works as expected:

```sql
ALTER TABLE testdate ALTER COLUMN date SET DEFAULT CURRENT_DATE;
```

I expect that the Table Editor supports values like `CURRENT_DATE`. (I have not tested `CURRENT_TIME` and similar, but expect the same behavior)

**Comment by saltcod** [comment]
Hey @b2m9 thanks for the report. 

When you create a new table, there's a `created_at` field there by default. It uses these fields as the default value:

<img width="310" alt="CleanShot 2022-09-22 at 09 11 37@2x" src="https://user-images.githubusercontent.com/105593/191737652-27cc446f-959f-4ede-a9f0-7e525e1174f6.png">

Does this help?

**Comment by Thuglife9** [comment]
Thanks so much for the help

**Comment by b2m9** [comment]
@saltcod I'm aware of Supabase's support for `now`, but it doesn't really solve my naive expectation that Studio should accept standard Postgres functions. For me, `CURRENT_DATE` is handy if I just want, well, the current date. `now` gives me a timestamp, not a date.

**Comment by Thuglife9** [comment]
But we can built something together

**Comment by Thuglife9** [comment]
We just need to put our brain together and do something very different and special

**Comment by joshenlim** [comment]
@soedirgo this is probably something for pg-meta as well i think, the following screenshot is what the dashboard is sending

![image](https://user-images.githubusercontent.com/19742402/192448099-96a139c4-ca3d-4146-a426-9f51b76b8c8e.png)

**Comment by soedirgo** [comment]
This is one of the cases where `defaultValueFormat` needs to be `"expression"` I think - otherwise `"CURRENT_DATE"` will be treated (and escaped) as a string literal.

**Comment by joshenlim** [comment]
ahhhh okay gotcha on this. hmm tbh i think the fix here is really to let the user be able to select whether the default value is a literal or expression by themselves. the dashboard can _try_ to interpret it but the user should be able to make the final choice. will look into this!

**Comment by soedirgo** [comment]
I _think_ when fetching from pg-meta you can basically treat it as `expression`, as long as we don't unquote it.

E.g. for a text column with default value `now()` as a `"literal"`, inserting new rows should give `'now()'` instead of a timestamp.

**Comment by joshenlim** [comment]
> basically treat it as `expression`

hmm but this wouldn't be right on the UI. esp if a user saved their default value as a literal, and they open the editor again and it shows that Is a SQL expression is toggled true

**Comment by MrVibe** [comment]
Instead of now() or CURRENT_DATE, use : 

**date(now())**
