### ISSUE TITLE
createdAt reset to null when editing row

### ISSUE THREAD

**Issue by abhay187** [supabase/supabase#9117]
### Bug report

created_at reset to null when editing row

### Describe the bug

I have a `lesson` table. Where `createdAt` has default value of `now()`.

I just realize that while updating a row `createdAt` reset to null and can't update the row if the date and time are not provided.

### To Reproduce

1. Try editing any row in the editor

### Expected behavior

`created_at` should stay the same.

### Additional context
Below Screenshot and recording
<img width="673" alt="Screenshot 2022-09-23 at 4 46 51 AM" src="https://user-images.githubusercontent.com/61496865/191868189-d1b794da-6a3e-4ebf-a07d-a546a6354c7e.png">

https://user-images.githubusercontent.com/61496865/192110336-cf2353d8-1ab6-4c63-a9e1-a2338eb213e2.mov

**Comment by abhay187** [comment]
Adding a screen recording for better understanding.

https://user-images.githubusercontent.com/61496865/191868553-dde90a99-928a-4095-8d4c-eb55a65ba148.mov

**Comment by abhay187** [comment]
@kiwicopple  @RandalSchwartz any info on why  I am facing this issue?

**Comment by abhay187** [comment]
Hey, @saltcod sadly the 

https://user-images.githubusercontent.com/61496865/193295745-05530146-1dc7-4c00-aebc-8ca6de365239.mov

problem still exists. Just for your information I am using firefox browser.

**Comment by activenode** [comment]
Same for me, I can confirm this.
