### ISSUE TITLE
docs: upsert with RLS

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#9159]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/upsert#notes

## Describe the problem

You might want to add a little bit to upsert if you are using RLS. If the table is restricted to row 'owners' you need to include the column that the auth.id matches when doing bulk upserts when only a select number of the columns are changing.

## Describe the improvement

Add a note about this requirement in upsert docs

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by ishaanbedi** [comment]
Hi! I'd like to work on this.
Can you please assign it to me?

**Comment by ishaanbedi** [comment]
<img width="1440" alt="Screenshot 2022-10-07 at 12 15 48 PM" src="https://user-images.githubusercontent.com/39641326/194484717-732161ea-1ed2-431d-b8de-6bbb8a1d977a.png">
Hi @thorwebdev , can you please have a look at the updated docs for the issue?

Once you confirm these updates, I'll raise a pull request for the same!

**Comment by ishaanbedi** [comment]
> <img alt="Screenshot 2022-10-07 at 12 15 48 PM" width="1440" src="https://user-images.githubusercontent.com/39641326/194484717-732161ea-1ed2-431d-b8de-6bbb8a1d977a.png">
> 
> Hi @thorwebdev , can you please have a look at the updated docs for the issue?
> Once you confirm these updates, I'll raise a pull request for the same!

@Isaiah-Hamilton Can you please help me out with this issue?

**Comment by Isaiah-Hamilton** [comment]
@ishaanbedi yeah no problem. Can you raise that pull request now, its much easier to keep track on what changes in the pull request.

**Comment by ishaanbedi** [comment]
> @ishaanbedi yeah no problem. Can you raise that pull request now, its much easier to keep track on what changes in the pull request.

Hey @Isaiah-Hamilton , I've raised a PR for the same, can you please have a look at the same?

**Comment by kiwicopple** [comment]
> If the table is restricted to row 'owners' you need to include the column that the auth.id matches when doing bulk upserts

@thorwebdev can you clarify this sentence a bit?

**Comment by thorwebdev** [comment]
Ah sorry, this was clarified by bobbie here: https://github.com/supabase/supabase/pull/9522#issuecomment-1278600121
