### ISSUE TITLE
The function size exceeds the allowable limit

### ISSUE THREAD

**Issue by JSmithOner** [supabase/supabase#9172]
# Bug report

## Describe the bug

I can't deploy a new function on my project and get

`Error: Failed to create a new Function on the Supabase project: {"message":"The function size exceeds the allowable limit"}`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

run : `supabase functions new subscribe-free-plan`
copy/paste:

```
import { serve } from "https://deno.land/std@0.131.0/http/server.ts";
import Stripe from "https://esm.sh/stripe?target=deno";
import { createClient } from "https://esm.sh/@supabase/supabase-js@1.35.5";

const stripe = Stripe(Deno.env.get("STRIPE_KEY")!, {
  httpClient: Stripe.createFetchHttpClient(),
});

const supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
);

serve(async (req) => {

  if (req.method === "OPTIONS") {
    
    return new Response(null, {
      
      headers: {
      
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "apikey, X-Client-Info, Authorization",
      
      },
    
    } );

  }

  const token = req.headers.get("Authorization")!.replace("Bearer ", "");
  const { user } = await supabase.auth.api.getUser(token);

  if (!user) {

    throw new Error("User not found");
  
  }

  const {
    data: { stripe_customer_id },
  } = await supabase
    .from("stripe")
    .select("stripe_user_uid")
    .match({ user_uid: user.id })
    .single();

  const subscription = await stripe.subscriptions.create({
    
    customer: stripe_customer_id,
    items: [ {
      price: 'price_1LhhXRGpLo3W9MX8jcZRvQUb'
    } ],

  });

  return new Response(JSON.stringify({ success:true }), {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "apikey, X-Client-Info, Authorization",
    },
  });
});
```

run: `supabase functions deploy subscribe-free-plan`

## Expected behavior

function should be deployed as I've recently deployed a function which is pretty similar and with more lines.

## System information

- OS: MacOS Monterey

## Additional context

I'm using a free plan for the moment and haven't exceeded the limit of 10 deployed functions/project.

**Comment by laktek** [comment]
@JSmithOner It looks like script size for your function with Stripe as a dependency was above 1mb. We have decided to bump the max script size for free plans to 2mb. If you give a try with the full module it should work now.
