### ISSUE TITLE
Inconsistent behaviour of auth in Supabase Client between tab/popup and service-worker

### ISSUE THREAD

**Issue by gprieto** [supabase/supabase#9173]
# Bug report

## Describe the bug

I am developing a chrome extension with auth using an external provider.

1. I log in my users from the `popup`, works fine: the session is stored in `chrome.local.storage`.
2. BUT in the `service-worker` script, `supabase.auth.session()` returns `null`

**Is there another way to implement this that I am not seeing?** 

`supabase.ts:`
```javascript
import { createClient, type SupportedStorage } from '@supabase/supabase-js';
export type { Session } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

const chromeStorageInterface: SupportedStorage = {
	async getItem(key: string): Promise<string | null> {
		const storage = await chrome.storage.local.get(key);
		return storage?.[key];
	},
	async setItem(key: string, value: string): Promise<void> {
		await chrome.storage.local.set({
			[key]: JSON.parse(value)
		});
	},
	async removeItem(key: string): Promise<void> {
		await chrome.storage.local.remove(key);
	}
};

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
	multiTab: true,
	localStorage: chromeStorageInterface,
        persistSession: true,
});
```
Also both the `popup` and the `service-worker` implement the `onAuthListener`.

## Expected behavior

As both the `popup` and the `service-worker` supabase clients share the same storage, they should both have the same session.

## Additionnal information

I have tried manually singing in from the `service-worker` with the following snippet:
```javascript
const setSession = async (config:ChromeConfig) => {
	if (config['supabase.auth.token']?.currentSession.refresh_token) {
		console.log('Logging in to Supabase using localstorage session');
		const {error} = await supabase.auth
			.signIn({
				provider: 'notion',
				refreshToken: config['supabase.auth.token'].currentSession.refresh_token
			})
		if (error) throw new Error(error.message)
	}
};
```
The sign in works and then the `refresh_token` becomes invalid but the updated `refresh_token` is not persisted back to `chrome.storage.local` so once the `token`expires the user is logged out.

**Comment by akoskm** [comment]
I've run into the same problem, and after looking at the TS definitions of `SupabaseClientOptions`, it looks like the right key to override the storage is inside `auth.storage`:

```
export const supabase = createClient(supabaseUrl!, supabaseAnonKey!, {
  auth: {
    storage: {
      async getItem(key: string): Promise<string | null> {
        // @ts-ignore
        const storage = await chrome.storage.local.get(key);
        return storage?.[key];
      },
      async setItem(key: string, value: string): Promise<void> {
        // @ts-ignore
        await chrome.storage.local.set({
          [key]: JSON.parse(value)
        });
      },
      async removeItem(key: string): Promise<void> {
        // @ts-ignore
        await chrome.storage.local.remove(key);
      }
    }
  }
})
```
With this, the superbase session is persisted across page reloads/tab closes/browser close/reopens.

When I inspect the service worker, I cannot see the session in the localStorage, so I have no clue where it is saved, but it's saved. 😄

**Comment by GaryAustin1** [comment]
Are either of you still looking for anything on this older issue?
This also looks like v1 code and no further dev is being done on that.
If so some follow up info and debugging on your side is likely needed using v2.
I'm going to close this for now.
