### ISSUE TITLE
Anyone bothers updating docs or examples provided on landing page

### ISSUE THREAD

**Issue by secretgspot** [supabase/supabase#9183]
# Bug report

## Describe the bug

Everything is broken, broken I tell ya! 
- open link <https://supabase.com/docs/guides/auth/auth-helpers/sveltekit>
- start following steps reading very carefully
- get to step two with __layout.svelte, doesn't work, realize sveltekit now uses +layout.svelte
- ERROR 500, SERVER CRASHED!

## Expected behavior

It should be first thing updated if you want product to be taken seriously especially when following official docs.  Not a single working example on the whole of github or internet. Sad, just sad I tell ya.

please for the love all of all that is holy, update your docs, make it work, I'm struggling here

**Comment by Isaiah-Hamilton** [comment]
Currently being worked on https://github.com/supabase/supabase/pull/9222

**Comment by silentworks** [comment]
The docs has been updated and so has the auth-helpers-sveltekit library.
