### ISSUE TITLE
Postgres connection url to connect with BI tools

### ISSUE THREAD

**Issue by vikasr111** [supabase/supabase#92]
* **I'm submitting a ...**
[ ] question about how to use this project

* **Summary**
Where can I access the Postgres connection URL to connect the Db with Metabase or PowerBI in order to analyze the data easily?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kiwicopple** [comment]
You can definitely do this - it's just a Postgres instance underneath.

Simply go to the settings icon here:

![image](https://user-images.githubusercontent.com/10214025/83993041-d9054580-a984-11ea-8504-57d2129a48bd.png)


Then "Database" in the sidemenu:

![image](https://user-images.githubusercontent.com/10214025/83993066-e7ebf800-a984-11ea-9b02-3630fbd6e202.png)
