### ISSUE TITLE
authListener.unsubscribe is not a function

### ISSUE THREAD

**Issue by jsonpreet** [supabase/supabase#9217]
# Bug report

Getting Error: TypeError: authListener.unsubscribe is not a function

## Describe the bug

Here's my _app.js file code

```
import '@styles/globals.css';
import '@styles/app.scss';
import NextNProgress from 'nextjs-progressbar';
import { ThemeProvider } from "next-themes";
import { supabase } from "@lib/supabaseClient"
import { useEffect } from 'react';
import { supabaseClient } from '@supabase/auth-helpers-nextjs'
import { UserProvider } from '@supabase/auth-helpers-react'


function MyApp({ Component, pageProps }) {
  return (
    <>
      <NextNProgress color="#cb0038" showOnShallow={true} />
      <ThemeProvider enableSystem={true} attribute="class">
        <UserProvider supabaseClient={supabaseClient}>
          <Component {...pageProps} />
        </UserProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp
```

![image](https://user-images.githubusercontent.com/26606638/192872681-6f182fd3-acc6-4e94-8a3b-22819de900ed.png)

I followed everything from 
https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari] : Chrome
- Version of supabase-js: ^2.0.0-rc.10
- Version of Node.js: v16.16.0
- @supabase/auth-helpers-nextjs: "^0.2.9"
- @supabase/auth-helpers-react: "^0.2.4"

**Comment by soedirgo** [comment]
`@supabase/auth-helpers-*` packages are still on supabase-js v1 I believe. It will be updated to use supabase-js v2, but for now you need to `npm install @supabase/supabase-js@1`.
