### ISSUE TITLE
Supabase Studio 404

### ISSUE THREAD

**Issue by joshxyzhimself** [supabase/supabase#9278]
# Bug report

## Describe the bug

![image](https://user-images.githubusercontent.com/60829711/193446172-59a8e46c-f5c6-4b54-8906-b9f7f0ec5675.png)

```
http://localhost:3000/undefined/auth/v1/token?grant_type=refresh_token
```

## To Reproduce

- https://supabase.com/docs/guides/hosting/docker

```
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Start
docker-compose up
```

## Expected behavior

It should work, right?

**Comment by silentworks** [comment]
This generally happens when this step is missed https://supabase.com/docs/guides/hosting/docker#generate-api-keys, you need to generate your API keys and add them to the .env file otherwise you will get undefined in the url as above.
