### ISSUE TITLE
'New Project' wizard does not complete project setup

### ISSUE THREAD

**Issue by reverylabadmin** [supabase/supabase#928]
# Bug report

## Describe the bug
The 'New Project' wizard - https://app.supabase.io/new - ends after the 'Create an organization' step. At this point there is no new project and further actions the user can take.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Login to supabase.io account
2. Click 'New Project' and then 'New organization'
3. Type in organization name and click next
4. See error - blank project with nothing but breadcrumb navigation

## Expected behavior

I assume should be additional steps to set up the project, database or team members.

## System information

- OS: Mac OS Big Sur
- Browser: Chrome 89.0.4389.90

**Comment by kiwicopple** [comment]
Thanks for the bug report @reverylabadmin - checking now

**Comment by kiwicopple** [comment]
Hey @reverylabadmin, this is now fixed! Thanks for taking the time to make the report
