### ISSUE TITLE
Move table filters and sorting to an "Apply" workflow

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#9301]
# Bug report

Move table filters and sorting to an "Apply" workflow rather than the current live-update one. 

Currently, the table filters (and the url updates) as you change the column, operator or value in a filter row. We'd like to instead have it so you can create some filters and then apply them. 

<img width="571" alt="CleanShot 2022-10-03 at 12 25 23@2x" src="https://user-images.githubusercontent.com/105593/193608978-c2bbefbd-08de-4cd5-a39c-8e6993c4648d.png">

**Additional Notes**
1. The Apply Filters / Apply Sorting should always be showing, but only be active when the state is "dirty" (ie: when there are changes to apply) 
2. The url should change to reflect the current filters/sorts when you hit Apply.
3. On the sorting view, we should reverse the position of the remove X icons and the drag icons to the. That will keep the position of the remove icons consistent in the sorting and filtering dropdowns

**Comment by saltcod** [comment]
Related: 
https://github.com/supabase/supabase/issues/9035

**Comment by gitstart** [comment]
Working on resolving this one.
