### ISSUE TITLE
Table editor deleting / pagination bug

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#9305]
# Bug report

Deleting 100 rows in the table leaves the table in a weird state, requiring a refresh.  At first, it looks like you've deleted all of your rows, not just the 100 you selected. 

**To reproduce**

Create a new table with a lot of rows:

1. Go to the SQL editor → Welcome page → Quick start section → Countries to quickly create a table with a lot of entries
2. Go to that new countries table
3. Select all rows at the top, then Delete 100 rows
 
![CleanShot 2022-10-03 at 13 07 32@2x](https://user-images.githubusercontent.com/105593/193620752-1b0fbcc8-b3a5-4919-a672-4f805596b35c.png)
4. Notice that your table empty. It looks like the entire table content has been deleted, but that's not the case. 
![CleanShot 2022-10-03 at 13 18 02@2x](https://user-images.githubusercontent.com/105593/193621162-28f9c00b-02d3-429c-8dae-e9e46a34c1bd.png)

**Comment by alaister** [comment]
The issue was that the react-query queries were not invalidated properly after deleting rows. This is now fixed.
