### ISSUE TITLE
Cannot Create table under selected schema

### ISSUE THREAD

**Issue by ahmedabdelhafez** [supabase/supabase#9325]
Hello Dears,
i was created a new schema called financial and when select it from dropdown like the one in the image and create new table 
tthe table go under the public like this image
but when go to sql editior and creat table with the schema name before the table name it's created well please check the bug
![image](https://user-images.githubusercontent.com/25756993/193792083-983aba8a-61bd-439d-8850-2a68c9a6b532.png)

**Comment by saltcod** [comment]
Hey @ahmedabdelhafez 

Thanks for the report. Could you post the SQL you ran to generate your schema? 

Also, are you able to create this table from the table editor page? 

<img width="435" alt="CleanShot 2022-10-04 at 12 07 10@2x" src="https://user-images.githubusercontent.com/105593/193848650-44d59f6e-82e6-4d6d-b1c3-e70add7bf695.png">

**Comment by ahmedabdelhafez** [comment]
@saltcod yes I do it from table editor already , but for the future if me or any one try to use it from the current screen that have issue 
But thanks for help and replying

**Comment by saltcod** [comment]
Aha!  Yep, I'm able to reproduce this one. 
This is a bug in the [project-ref]/database/tables interface. 
![CleanShot 2022-10-04 at 12 11 13@2x](https://user-images.githubusercontent.com/105593/193849754-01987551-18e2-4230-b505-9f66a18cc4b8.png)


In the meantime, you should be able to create a table under your custom schema from the table editor → new table flow.

**Comment by saltcod** [comment]
Reopening @ahmedabdelhafez as there's still a bug here. Thanks!
