### ISSUE TITLE
client requests to supabase.co can sometimes take minutes to complete

### ISSUE THREAD

**Issue by city41** [supabase/supabase#937]
# Bug report

## Describe the bug

As I write this, one of my Supabase backed sites is taking minutes to finish a request to its supabase.co url. 

The request just finished with a time of 4.5 minutes.

## To Reproduce

There are no reliable repro steps, unfortunately. But I have experienced this from time to time throughout my time using Supabase.

## Expected behavior

Requests should resolve in preferably a few seconds at most.

## Screenshots

![image](https://user-images.githubusercontent.com/141159/112365803-716b7d00-8cae-11eb-9515-f35d5e1fbc6c.png)

## System information

- OS:  Ubuntu
- Browser Chrome 89.0.4389.82
- Version of supabase-js: 1.5.1

## Additional context

My Supabase project is deployed to US East (Virginia). Here is the url of the above request

https://cfmypkasixjnpkxfpylf.supabase.co/rest/v1/users?select=id%2Cusername&id=eq.317d84a9-54fc-4109-8844-b1c211ab1c26

The request started at about Wed Mar 24 2021 14:34:00 GMT-0400 (Eastern Daylight Time). That is a rough time.

I don't have long response times like this from any other requests, making me think it is not my internet connection.

Here is the client code that causes the request

```javascript
	const { data: userData, error: userError } = await client
		.from<User>('users')
		.select('id, username')
		.eq('id', id)
		.single();
```

**Comment by kiwicopple** [comment]
> Requests should resolve in preferably a few seconds at most.

This query should resolve in milliseconds, even with millions of rows. I have a few questions which can help us rule out if its a Postgres issue or a middleware issue:

- Is this query consistently slow? If you refresh the page 10 times is it >100ms each time? 
- Can you please share the structure of your `users` table, and how you created it? (including any indexes)
- can you please run this on your database and send us the results:

```sql
explain analyze 
select id, username
from users 
where id = 'some-user-uuid'
limit 1;
```

**Comment by city41** [comment]
Sorry, I probably wasn't as clear as I should have been. This query is only intermittently slow. The vast majority of the time it's lightning fast (about 20ms for the entire network request). But I have noticed occasionally this happens where a request to supabase.co can take a long time. I don't think it's query specific. This database is virtually empty (the users table has 1 row in it), and the sql that creates it is very simple. [Here are the migrations that created the db](https://github.com/city41/smaghetti/tree/main/database/migrations).  
  
I can't give solid numbers on how often it is slow, I've anecdotally noticed it a few times now, and so finally decided I'd file an issue.

**Comment by city41** [comment]
Also, the project I am using Supabase with is a side project and doesn't have any sensitive data or anything, so if giving Supabase employees access to it would be helpful, happy to do that.

**Comment by city41** [comment]
Just now this request took 3 minutes. But also noticed the preflight request took 10 seconds

![image](https://user-images.githubusercontent.com/141159/112484513-65d09280-8d50-11eb-9291-a53892ea7bee.png)

interesting that as of late, it seems to mostly be this users request that lags.

**Comment by inian** [comment]
Hi @city41, I plotted the max server timings in 30 second buckets for the project `cfmypkasixjnpkxfpylf` and looks like all requests were processed within 500ms in the worst case. So it looks like the delay was before reaching the kong layer.

Even the preflight request taking 1 min is extremely weird since those requests don't even touch the database and kong responds to them directly. This also supports the hypothesis is that the delay is caused before the server gets the request 🤔

![image](https://user-images.githubusercontent.com/2155545/112487956-28492500-8da3-11eb-8be4-7100ad4f37b7.png)

**Comment by city41** [comment]
That's good news. I'd rather it be something on my side than in Supabase. Especially if I'm the only one to have reported this.

I'll keep an eye on it and see if I can repro say on another machine with a different ISP for example.

**Comment by inian** [comment]
Cool, that will help further diagnose the issue Matt!

**Comment by kiwicopple** [comment]
Looks like there has been no movement on this one for ~8 months. I'll close but happy to reopen if we can come up with some steps to replicate

**Comment by mubashir-zenkoders** [comment]
I am having this exact same issue. This matches my problem 110%. Queries resolve way quicker generally, but sometimes, it feels like Supabase is hang, and when refreshing page to make a new req, and it just works.

**Comment by Alloco225** [comment]
I'm having the same issue. The queries are quick most of the time but occasionally (like 4/10 times) super slow. And when I refresh the page it gets back to working

**Comment by robertoandrade** [comment]
Seeing the same thing in a react project here and notice indeed some times the queries get stuck for minutes, like 4.5 exactly like some report! but it doesn't seem like it's waiting for a server response... it may be getting stuck in the browser queue for multiple requests or some sort of concurrency lock that gets out of wack!

**Comment by SAGAR-TAMANG** [comment]
Same issue here with React Project. It's just stuck.

**Comment by lukenguyen-me** [comment]
Same issue here. My case is with the auth request, it takes 1 minute and a half.

<img width="600" height="183" alt="Image" src="https://github.com/user-attachments/assets/dfdbe0a3-a8dc-49f1-a9f8-37d7611e26c0" />
<img width="614" height="400" alt="Image" src="https://github.com/user-attachments/assets/da5a2f79-dc36-45bf-a415-50ed8420629b" />
