### ISSUE TITLE
Set CORS headers for Edge Functions 401 response

### ISSUE THREAD

**Issue by acurrieclark** [supabase/supabase#9373]
# Bug report

## Describe the bug

When attempting to call an edge function with a **bad token**, the function rightly issues a 401 response. However, while CORS headers appear to be set for the preflight OPTIONS request, they are not for the subsequent POST request, resulting in the browser seeing a failed fetch rather than the 401 response.

## To Reproduce

```ts
fetch(
    import.meta.env.SUPABASE_FUNCTION_URL,
  {
    method: "POST",
    headers: {
      Authorization: "Bearer bad-token",
      "Content-Type": "application/json",
    },
  }
)
  .then((res) => {
    console.log(res);
  })
  .catch((error) => {
    console.log(error);
  });
```

When CORS is enabled in the browser, an error is caught. With CORS disabled (in the browser), the response is properly logged.

## Expected behavior

The response should have appropriate CORS headers set.

## System information

- OS: OS X 12.5.1
- Browser: Brave (also confirmed in Chrome)

**Comment by acurrieclark** [comment]
I have a CORS check in my function. What I am saying is that if I hit the endpoint with a bad token, it never hits the endpoint and the 401 response (which I have no control over) doesn’t include CORS headers.
In this case, my function code is not touched, as the request is automatically rejected.

**Comment by laktek** [comment]
Sorry misunderstood your question. Looks like this is a bug in our end. Will post a fix for it this week.

**Comment by laktek** [comment]
We've deployed a fix for this issue. Can you check if the error statuses are returned correctly on your functions?

**Comment by acurrieclark** [comment]
Works as expected locally. Will close for now and reopen if it doesn't work in production.

Thanks so much for the quick turnaround.

**Comment by GaryAustin1** [comment]
@acurrieclark 
Is this still an issue for you, or did it get resolved.  Not much info in your last post and getting stale.

**Comment by acurrieclark** [comment]
Hi @GaryAustin1, good point. Not checked in a while. Will update to the latest version of CLI and test for you now.

**Comment by KevinBrolly** [comment]
Hey @acurrieclark - in the last year we have made lots of changes around Edge Functions, are you still seeing this issue now?

Since it has been so long and we are not seeing other/wider reports of the issue I will close it as stale. However, if you are still experiencing this issue let us know and we can open it up again no problem.

**Comment by shraey96** [comment]
@KevinBrolly 
I'm still getting this error with an invalid / expired token. it never reaches the function and the status code is only returned. how do i handle it in my frontend?

**Comment by toonwelk** [comment]
@KevinBrolly I am also experiencing this issue, supabase CLI v2.33.9
