### ISSUE TITLE
Empty spaces in webhooks HTTP request block insert and update on the table linked with the webhook

### ISSUE THREAD

**Issue by cdedreuille** [supabase/supabase#9390]
# Bug report

## Describe the bug
When creating a webhook, if by mistake you add an empty space on the HTTP request, this will block the associated table. Every time you try to add or update a row you'll get this message:
```
Failed to run sql query: URL using bad/illegal format or missing URL
``` 

## To Reproduce

1. Create a table (default settings)
2. Create an edge function
3. Create a webhook to watch insert and update on this table
4. Copy your edge function url
5. Paste the URL into the HTTP request of the webhook - This is where the mistake happen as there was an empty space before that I could not see.
6. Try adding a row on the new table
7. Error - "Failed to run sql query: URL using bad/illegal format or missing URL"
8. Remove the webhook
9. Try adding a row on the table again
10. It's now working.

## Expected behavior

To avoid having this mistake in the future a very simple fix could be to remove all spaces automatically when creating the webhook. Also perhaps there might be a better way to present the error as this one was really hard to track as it was not related to the table but to a webhook.

## Screenshots
<img width="896" alt="CleanShot_2022-10-07_at_12 38 192x" src="https://user-images.githubusercontent.com/1540635/194549444-e13ceeca-cc91-45d7-a62f-6e177e737dc5.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by egor-romanov** [comment]
Thank you for creating it!
