### ISSUE TITLE
ERROR: function uuid_generate_v4() does not exist on `db reset`

### ISSUE THREAD

**Issue by danielchalef** [supabase/supabase#9399]
### Discussed in https://github.com/supabase/supabase/discussions/9382

Developing with a local installation of supabase. I have `uuid` columns with default values populated by `uuid_generate_v4()`. The `uuid-ossp` extension is installed and I am able to:

```
postgres=# select uuid_generate_v4();
           uuid_generate_v4
--------------------------------------
 aaa9d6b0-1c8d-4188-b110-75c541602522
```

Running a `db reset` to execute a local migration fails with:
```
Resetting database...
Initialising schema...
Applying migration 20221004182316_remote_commit.sql...
Applying migration 20221007015222_remote_commit.sql...
Error: ERROR: function uuid_generate_v4() does not exist (SQLSTATE 42883)
```

I've seen other issues where the `uuid_generate_v4` function hasn't been created. This doesn't appear to be the case here.

## System information
- OS: macOS 12.6 / M1 Pro
- Version of supabase cli: 1.6
- Version of Node.js: v16.17.1
- containers: 
postgres-meta:v0.45.0
pgadmin-schema-diff:cli-0.0.5

**Comment by danielchalef** [comment]
As noted in https://github.com/supabase/supabase/discussions/9251, extensions need to be called explicitly. Replace `uuid_generate_v4()` with `extensions.uuid_generate_v4()` allowed me to successfully `reset` the database.

`db commit` needs to generate migration scripts that explicitly call extensions.

**Comment by jacinto-joao** [comment]
For anyone that still facing this issue in 2024, please do the following:

Login to your **Postgres** instance:

`psql dbUsername`

# Select the current DB

`\c dbName`

`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`

Quit the db;
`\q`

If you're using NestJs with **typeorm**
Make sure your _dataSource_ config has the following extension enabled:

`{
   ...,
   uuidExtension: 'pgcrypto'
}`

**Comment by brijmcq** [comment]
I was using `uuid_generate_v4()` but encountered some errors, so I replaced it with `gen_random_uuid()` to resolve them.

**Comment by darul75** [comment]
> As noted in #9251, extensions need to be called explicitly. Replacing `uuid_generate_v4()` with `extensions.uuid_generate_v4()` allowed me to successfully `reset` the database.
> 
> `db remote commit` needs to generate migration scripts that explicitly call extensions.

lost hours on this, thank you
