### ISSUE TITLE
Improve sveltejs-todo-list example

### ISSUE THREAD

**Issue by stefandesu** [supabase/supabase#940]
# Improve documentation

## Link 

https://github.com/supabase/supabase/tree/master/examples/sveltejs-todo-list

## Describe the problem

The documentation seems incomplete. Under step 3, it says "run db/task_list_schema.sql", but how do I run it and where is that file? I eventually found a file named `todo_list_schema.sql` inside a different example, but it only created two of the three tables to pass step 4.

I progressed anyway and got database access working. However, when I ran the application, there were several more problems:
- When running `npm run start`, the browser console shows this error: "Uncaught SyntaxError: The requested module './Items.js' does not provide an export named 'default'".
  - Adding `export default { getLists, getItems, itemsAllAtOnce, items, subscription }` to `src/items.js` circumvents the issue.
- After fixing the previous issue, the interface works and I was able to log in with the user I created. But when I tried to create a list, the browser console shows the following errors:
  - "POST https://vqpuqgdgkpnohulwbmmb.supabase.co/rest/v1/lists 400"
  - "error TypeError: Cannot read property '0' of null at createList (store.js:51)"

I'm suspecting that the second error happens because I didn't run the correct SQL, thus being an issue of documentation (or rather, a missing file).

## Describe the improvement

Well, the improvement would be to fix the documentation as well as the example itself so that it works after going through the described steps. I'm willing to help, but I'm just starting with Supabase and Svelte (normally I use Vue). 

## Additional context

Using Node.js v14.15.3.

Thanks!

**Comment by kiwicopple** [comment]
We now have a Svelte guide in the docs! https://supabase.io/docs/guides/with-svelte

**Comment by nivoc** [comment]
"Svelte guide in the docs"

But that does not solve the sevelt-todo example-issues. And the not working Example from the Repo is still metioned as starting point if someone creates a new projekt.

Should be removed or example-issues fixed.
