### ISSUE TITLE
Supabase api/auth 500 error on Vercel

### ISSUE THREAD

**Issue by jsonpreet** [supabase/supabase#9402]
# Bug report
https://emotion-seven.vercel.app/
Getting 500 internal error and in console it show api error
https://emotion-seven.vercel.app/api/auth/user
## Describe the bug

Github url: https://github.com/jsonpreet/emotionCards

## Screenshots
![image](https://user-images.githubusercontent.com/26606638/194640449-d25b3ad0-8e5d-4273-b5f5-39d0e48371fe.png)

## System information

- OS: Windows
- Browser: FireFox
- Version of supabase-js: 2.0.0-rc.10
- Version of Node.js: 16.16.0

## Additional context

@supabase/supabase-auth-helpers: "^1.4.2",
@supabase/auth-helpers-nextjs: "^0.4.0-next.3", 
@supabase/auth-helpers-react: "^0.3.0-next.2",

**Comment by jsonpreet** [comment]
It's working fine on localhost

**Comment by jsonpreet** [comment]
No respone?

**Comment by saltcod** [comment]
Hey @jsonpreet 

Could you provide some more details about what's happening with this one?  The repo link above isn't working for me. Anything like what stack you're using, what you're trying to achieve, etc would be great. 

Thanks!

**Comment by jsonpreet** [comment]
Here's Repo Link

https://github.com/jsonpreet/emotionCards1

I just want non-logged-in users to redirect to the login page if they visit the root domain. and if the user logged in it show the dashboard

**Comment by Shevly** [comment]
I too have a similar error on local dev server, where when a user sign-in the auth-cookies aren't getting set in the browser plus, I get this error on the console...

````js
{
  data: { user: null },
  error: AuthApiError: Internal server error
      at C:\Users\Riot\Documents\Project\node_modules\@supabase\gotrue-js\dist\main\lib\fetch.js:41:20
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    __isAuthError: true,
    status: 500
  }
}
````
Since this next-auth-helpers aren't working either...


Additional Info
```
    "@supabase/auth-helpers-nextjs": "^0.4.0-next.4",
    "@supabase/auth-helpers-react": "^0.3.0-next.4",
    "@supabase/supabase-js": "^2.0.0-rc.13",
```

**Comment by jsonpreet** [comment]
No Response?
