### ISSUE TITLE
Viewing Storage in Studio UI results in migrations error: `column "path_tokens" of relation "objects" already exists`

### ISSUE THREAD

**Issue by danielchalef** [supabase/supabase#9413]
# Bug report

## Describe the bug

Viewing Storage in the Studio UI generates an error notification: `Migration failed. Reason: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: column "path_tokens" of relation "objects" already exists`

## To Reproduce

In the `app.supabase.com` Studio UI, click on `Storage`

## Expected behavior

No error

## System information

- OS: macOS
- Browser (if applies): Chrome

**Comment by sarkarology** [comment]
I recently cloned my project using the Database Migration guide and I am facing the same issue in the newly cloned project.

**Comment by siahgoodwork** [comment]
We are experiencing the exact same issue: 
Trying to do anything in the Storage dashboard, including listing or creating a bucket, fails with the same error message: 
> Migration failed. Reason: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: column "path_tokens" of relation "objects" already exists

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/83395882/199142020-437a065a-4b19-4913-a5b7-de9c80417b43.png">

**Comment by GaryAustin1** [comment]
This is a very old issue and seems like it was related to a change in storage or the UI at the time.  I see no other hits on this since then.  I'm going to close this.

If it needs to be reopened please add a comment.
Thanks
