### ISSUE TITLE
Symbolic error codes

### ISSUE THREAD

**Issue by tlbtlbtlb** [supabase/supabase#9534]
# Improve documentation

## Describe the problem

I want to handle certain error codes specially, for instance when inserting a storage object that already exists. It returns something like:
```json
{
  statusCode: '23505',
  error: 'Key (bucket_id, name)=(blobs, blobs/zblob.63480a014b560000.data) already exists.',
  message: 'duplicate key value violates unique constraint "bucketid_objname"'
}
```

As far as I can see, those `statusCode`s aren't documented anywhere. And the other elements don't seem safe to compare.

It would be useful to document the common error codes, and to provide some symbolic constants to test against. Like I have this:
```
    }).then(({data, error}) => {
      if (error.statusCode === '23505') {
        return; // key exists, no problem, continue
      }
     throw new Error(error.message); // actual problem
```
and would prefer
```
    }).then(({data, error}) => {
      if (error.statusCode === supabase.EEXISTS) {
        return; // exists, no problem, continue
      }
```

## Describe the improvement

Provide symbolic error codes for common errors and document them.

## Additional context

The codes above are from `supabase.storage.from(...).upload()`

**Comment by iamchubko** [comment]
Wanted to implement similar logic, facing the same issue

**Comment by charislam** [comment]
Closing as these error codes are [documented by Postgres](https://www.postgresql.org/docs/current/errcodes-appendix.html)
