### ISSUE TITLE
Linkedin auth does not work for specific user profiles

### ISSUE THREAD

**Issue by taras-yakymiuk** [supabase/supabase#9543]
# Bug report

## Describe the bug
When the user is trying to signIn using Linkedin account and the Linkedin profile does not have profile img/avatar then the login flow fails.

## To Reproduce

1. Create a project with LinkedIn auth
2. Use LinkedIn account that does not have profile IMG 
3. You are redirected to your app with an error in the URL (which get's replaced in a moment) with error in QS params: 
4. See error: `?error=server_error&error_description=Unable+to+exchange+external+code%3A+AQQcwhaK4Q2zwl5p_uevx88g_DuM_u8cFyR4-Vw35iWSeKdRxewaPkC6y8CM-v8AFXJcGAniR_4wUVaTlRhmB1o0GS92xTS_0rnUTn_ZqiyTKefztCKYlwNcUtabRRIVV2xY9bPjsuzFyyonzMi9szpFJaMPDoOVSGGXzpj8yMUywAhxY0rQHRfmKzL6S0wPpGBAT0GY0FEHIRVwBTI`

## Expected behavior

Looks like it's not an issue on LinkedIn side since I'm able to login to other resources using the same LinkedIn account (without profile IMG)

## System information
    "@supabase/supabase-js": "^2.0.0",
the issue was present in older package versions as well

P.S. I don't know where this issue lives, so I created same issue in other repos, pls remove them if they are redundant
https://github.com/supabase/gotrue-js/issues/488
https://github.com/supabase/auth-helpers/issues/309

**Comment by soedirgo** [comment]
:+1: Closing in favor of the client lib issue
