### ISSUE TITLE
can't access Kong Admin 8001 after adding it to docker container

### ISSUE THREAD

**Issue by j2l** [supabase/supabase#9562]
## Describe the bug
Added the 8001:8001 port to the Kong container, then kong-admin-ui project (new local docker container), but I can't connect to Kong.
In postman and browser `http://localhost:8001` is not returning anything useful. Various errors are turning around.
Weird enough and maybe not related `http://localhost:8000/auth/v1/verify` (using Bearer service_token) is returning a web page.

## Expected behavior
Access to Kong for administration, using GUI

Maybe there's another working solution I didn't see?? :smile: 

- OS: Ubuntu 22.04

**Comment by GaryAustin1** [comment]
@j2l 
Did you ever resolve this?

**Comment by j2l** [comment]
Nope, I don't remember all I tried sorry.

**Comment by GaryAustin1** [comment]
I'm going to go ahead an close this for now.
If you are still trying to get this to work then please feel free to open a new issue with more information, or add on here and I'll reopen.  I can't add any help to the actual issue itself, but it has gone pretty stale.

**Comment by j2l** [comment]
Well it went stale because it never got any attention :smile: 
What should have I add?

**Comment by GaryAustin1** [comment]
I'm not denying that.  I'm just helping out Supabase go thru issues to classify and cleanup old.
I will reopen, but is so old not sure when a Supabase employee or other user will get back this far.  

This also is probably more a discussion or topic for Supabase Discord so that other users doing local dev might offer suggestions. Many users are running docker, so likely a setup or environment issue.  I don't do local dev, so have no advice.

**Comment by j2l** [comment]
Thanks @GaryAustin1 
AFAIK, supabase-kong is part of the supabase docker suite and ports are 8443, 8000 and 8001. None of them seem to produce expected results, so, AFAIU, it's a bug.

**Comment by j2l** [comment]
Sorry @kiwicopple it was Oct 2022, I don't remember.

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. 
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
