### ISSUE TITLE
calling edge function - react native 

### ISSUE THREAD

**Issue by strimbob** [supabase/supabase#9588]
# Bug report

when calling an edge function from react native in android I get a 
**TypeError: Network request failed**

## Describe the bug

there is something going wrong inside
supabase.functions.invoke 

when i call 

    const {data, error} = await supabase.functions.invoke('maps', {
      body: JSON.stringify(body),
    });

i get this error back

TypeError: Network request failed
    at fetch.umd.js:535:18
    at JSTimers.js:214:18
    at _callTimer (JSTimers.js:112:7)
    at Object.callTimers (JSTimers.js:357:7)
    at MessageQueue.__callFunction (MessageQueue.js:423:27)
    at MessageQueue.js:113:12
    at MessageQueue.__guard (MessageQueue.js:367:9)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:112:10)
    at debuggerWorker.js:69:58 

as i understand it - this is generic fetch react native error 

## To Reproduce

call an edge function from react native  

## Expected behavior

the same invoke function works in my react web app with no errors.
So i can rule out a problem with my edge function. 
I send the same body in both cases  
I would expected both to behave the same way 

I can call supabase.storage and get data back so it is not a network issue 

## System information

- OS: android - API 33_arm64-v8a
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: 1.35.7
- Version of Node.js: v14.18.3

thanks Supabase team i really like supabase - i hope this is solvable!!

**Comment by KevinBrolly** [comment]
Hey there,

It is likely this was a tranisent network error, and now so much time has passed that this issue has become stale.

I am going to close this issue, however if you do still have a problem that you feel is a bug please do let us know and we can re-open.
