### ISSUE TITLE
[dashboard] Allow copying from Results table section of SQL Editor

### ISSUE THREAD

**Issue by anngbaum** [supabase/supabase#9630]
# Feature request
Allow copying from Results section of SQL Editor

## Is your feature request related to a problem? Please describe.
Using the dashboard SQL Editor is super convenient and useful for quick one-off issues.

Very frequently, however, I want to copy a value from the results somewhere else, but in Google Chrome and Firefox on Mac, the Results table is not copy-able (I assume the JS is doing something to prevent default in the context menu like in the other table editors, but not actually showing a copy menu here).

## Describe the solution you'd like
Make the Results cells from the SQL Editor able to be copied.

## Describe alternatives you've considered
I copy the entire Results as markdown and extract the value I want, or I inspect the element on the page and pull it from the HTML. Not the end of the world, just annoying.

## Additional context
This is from usage on a Mac, and reproduces on both Google Chrome Version 106 and Firefox 104. Screenshots of the right-click menu below (first is Chrome, second is Firefox).

<img width="837" alt="Screen Shot 2022-10-17 at 5 21 38 PM" src="https://user-images.githubusercontent.com/29735378/196288556-de7ae20e-370f-49ac-b0d7-a3c2fc50bc64.png">
<img width="998" alt="Screen Shot 2022-10-17 at 5 30 54 PM" src="https://user-images.githubusercontent.com/29735378/196288569-1d69fa9a-16c5-4821-9b79-bb9d4587d013.png">

**Comment by saltcod** [comment]
Hey @anngbaum !  Great suggestion. That's actually in progress over here: 
https://github.com/supabase/supabase/pull/9538

Hope to get this in soon.

**Comment by anngbaum** [comment]
oh that's great – thank you @saltcod !!
