### ISSUE TITLE
Flutter/Dart - authentication state and user not saved 

### ISSUE THREAD

**Issue by globemediaofficial** [supabase/supabase#9636]
# Bug report

## Describe the bug

When a user logs in, closes the app, and opens it again, they are asked to sign in again. I'm not sure if the user and authentication state is not saved locally but it is an issue on all platforms. It has become standard for users to not need to sign in every time they open an app so I'm sure this is a bug and not intentional.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add supabase to `pubspec.yaml`
2. Use provided snippet (with real email and password)
```
final response = await client
      .auth
      .signUp('email', 'password');
```
3. Close the app once authenticated 
4. Open the app again
5. It will ask you to sign in
6. I even added `await Supabase.auth.refreshSession();` to the main function but that did not fix it

## Expected behavior

When a user logs in, their data and authentication state should be saved locally, so they can close and re-open the app without needing to login again.

## System information

All platforms that Flutter supports (Web, iOS, Android, macOS, Windows, Linux)

**Comment by globemediaofficial** [comment]
Solution: use “supabase_flutter” package instead of “supabase”. I don’t understand why there are 2 packages and it doesn’t say anywhere which one saves users. The “supabase” package should weighed be removed or replaced by “supabase_flutter”.

**Comment by burmecia** [comment]
Thank you reporting this issue, @dshukertjr could you have a look at this?

**Comment by dshukertjr** [comment]
@globemediaofficial 
Thanks for the feedback. We do have some notes in [our official documentation](https://supabase.com/docs/reference/dart) about it, but I will add some notes in the readme.md of `supabase` package to redirect users to use `supabase-flutter` for Flutter applications!
