### ISSUE TITLE
Unable to compile angular app using @supabase/supabase-js

### ISSUE THREAD

**Issue by ArcangeloD** [supabase/supabase#9660]
I followed the steps in the quickstart to user supabase with angular, but I can't compile any of the code using the module. Every time I try to run the app or build the app while importing supabase-js, even withouth calling it, I get the following error during compilation : 

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   3.15 MB |
polyfills.js          | polyfills     |   1.15 MB |
styles.css, styles.js | styles        | 490.01 kB |
scripts.js            | scripts       |  78.65 kB |
main.js               | main          |  23.94 kB |
runtime.js            | runtime       |   6.52 kB |

Initial Total |   4.88 MB

Build at: 2022-10-18T23:57:51.319Z - Hash: 46a7ef83f377e892 - Time: 8517ms

Error: node_modules/@supabase/supabase-js/dist/module/SupabaseClient.d.ts:57:126 - error TS2314: Generic type 'PostgrestQueryBuilder<Schema, Relation>' requires 2 type argument(s).

57     from<TableName extends string & keyof Schema['Tables'], Table extends Schema['Tables'][TableName]>(relation: TableName): PostgrestQueryBuilder<Table>;
                                                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@supabase/supabase-js/dist/module/SupabaseClient.d.ts:58:120 - error TS2314: Generic type 'PostgrestQueryBuilder<Schema, Relation>' requires 2 type argument(s).

58     from<ViewName extends string & keyof Schema['Views'], View extends Schema['Views'][ViewName]>(relation: ViewName): PostgrestQueryBuilder<View>;
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@supabase/supabase-js/dist/module/SupabaseClient.d.ts:59:29 - error TS2314: Generic type 'PostgrestQueryBuilder<Schema, Relation>' requires 2 type argument(s).

59     from(relation: string): PostgrestQueryBuilder<any>;
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@supabase/supabase-js/dist/module/SupabaseClient.d.ts:72:9 - error TS2314: Generic type 'PostgrestFilterBuilder<Schema, Row, Result>' requires 3 type argument(s).

72     }): PostgrestFilterBuilder<Function_['Returns'] extends any[] ? Function_['Returns'][number] extends Record<string, unknown> ? Function_['Returns'][number] : never : never, Function_['Returns']>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

× Failed to compile.

## System information

- OS: Windows
- Version of supabase-js: 2.0.1
- Version of Node.js: 16.18.0 (also tried on older and newer build)
- Version of Angular: 14.2.0

**Comment by rbogdy** [comment]
You have to update supabase-js to 2.0.2. There was a bump for postgrest-js and this is fixed

**Comment by ArcangeloD** [comment]
Thanks for your answer. It's working now.
