### ISSUE TITLE
jwt secret of 36 chars not working with docker

### ISSUE THREAD

**Issue by ganganimaulik** [supabase/supabase#9666]
# Bug report

## Describe the bug
when using following JWT_SECRET in /docker/.env file -> it keeps connecting as per screenshot
![image](https://user-images.githubusercontent.com/10296400/196603215-bf08be2d-2fc5-4b4b-aa1a-15545ba30837.png)
`JWT_SECRET=7dxxx5f1-xxxx-xxxx-xxxx-f6xxx27aa398`

issue is related with size of jwt_secret. it works good on using default jwt_secret provided in /docker/.env.example. Also note that value for jwt_secret I am using is 36 chars so it is > 32. so basically it won't allow any similar key with any other chars which is of this length.

## To Reproduce

1. change /docker/.env file to following: (I have only changed JWT_SECRET)
```
############
# Secrets 
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION
############

POSTGRES_PASSWORD=your-super-secret-and-long-postgres-password
JWT_SECRET=7dxxx5f1-xxxx-xxxx-xxxx-f6xxx27aa398
ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q


############
# Database - You can change these to any PostgreSQL database that has logical replication enabled.
############

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PORT=5432


############
# API Proxy - Configuration for the Kong Reverse proxy.
############

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443


############
# API - Configuration for PostgREST.
############

PGRST_DB_SCHEMAS=public,storage,graphql_public


############
# Auth - Configuration for the GoTrue authentication server.
############

## General
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
API_EXTERNAL_URL=http://localhost:8000

## Mailer Config
MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender

## Phone auth
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true


############
# Studio - Configuration for the Dashboard
############

STUDIO_ORGANIZATION_NAME=Default Organization
STUDIO_PROJECT_NAME=Default Project

STUDIO_PORT=3000
PUBLIC_REST_URL=http://localhost:8000/rest/v1/ # replace if you intend to use Studio outside of localhost

```
2. run `docker-compose up`
3. goto http://localhost:3000 & select default project
4. it keeps loading.....

## Expected behavior

it should load the project. Please allow shorter jwt_secret so we can use secrets generated by supabase cloud locally. 
 

## System information

- windows 11
- latest chrome
- master branch latest
- not relevant as I am using docker

**Comment by merabtenei** [comment]
Did you forget to update the kong.yml file ? That happened to me when I updated the .env file but not the kong.yml file
```
volumes/api/kong.yml
anon - replace with an anon key
service_role - replace with a service key
```

**Comment by ganganimaulik** [comment]
> 2\. docker-compose up

I clone supabase project and just change jwt key.

anon key + service keys are not changed and are same in both .env + kong.yml by default

**Comment by ganganimaulik** [comment]
> Did you forget to update the kong.yml file ? That happened to me when I updated the .env file but not the kong.yml file
> 
> ```
> volumes/api/kong.yml
> anon - replace with the same anon key in .env
> service_role - replace with the same service key in .env
> ```

I clone supabase project and just change jwt key.

anon key + service keys are not changed and are same in both .env + kong.yml by default

**Comment by ganganimaulik** [comment]
> Did you forget to update the kong.yml file ? That happened to me when I updated the .env file but not the kong.yml file
> 
> ```
> volumes/api/kong.yml
> anon - replace with the same anon key in .env
> service_role - replace with the same service key in .env
> ```

I only change jwt secret. I also need to generate anon+service key. thanks for helping

**Comment by merabtenei** [comment]
@ganganimaulik Exactely, you need to use the tool in the documentation to generate both anon and service_role from your new jwt key and put them in both .env and kong.yml
