### ISSUE TITLE
Invalid refresh token error when logging into app after a couple of days

### ISSUE THREAD

**Issue by alexreyes** [supabase/supabase#9668]
# Bug report

If I don't open my app for an extended period (a couple of days or more), it will log me out. This is the same bug as the one mentioned in [this issue.](https://github.com/supabase/supabase-js/issues/254)

I am experiencing this bug on iOS with React Native.

## Describe the bug

Before signing me out, the following error got printed in the console: ```Invalid Refresh Token```. 

I did some additional digging using console.logs() so hopefully these details are also helpful: 

1) [This line in _refreshAccessToken seems to be what is raising the error](https://github.com/supabase/gotrue-js/blob/2cba416b266a8c55f58fd58eb5d6bcde5b39a9e1/src/GoTrueClient.ts#L763)
2) There was an existing session saved in localstorage that was retrieved, and it contained a ```refreshToken```
3) The session in localstorage had an expiry time of: ```Sunday, October 16, 2022 5:55:09 PM```. 
     - The time when I opened the app (rougly) was: ```October 18, 2022 at 11:30 pm```. A little more than 2 days later
     - ```expires_in``` was set to 3600 (I was testing another bug at the time so the low expiry was for testing)

## To Reproduce

There are two options: 

1) Create a sample project with Supabase auth, log in, and then wait a couple of days and retry logging in

OR

2) Make a request to the Supabase go-true server at this endpoint: ```/token?grant_type=refresh_token``` using a refreshToken that *was* valid a couple of days ago. 
    - I think this would give the same error, but I personally have not tried it. I've only experienced method #.1

## Expected behavior

I stay logged in unless I sign out

## Screenshots

N/A (happy to send specific session variable logs upon request)

## System information

- OS: macOS
- Browser (if applies): React Native iOS
- Version of supabase-js: 2.0.0
- Version of Node.js: v16.13.1

## Additional context

This has been happening for a while (months) across multiple projects where I use Supabase auth. This has been true across Supabase v1 and v2.

**Comment by hf** [comment]
Hey @alexreyes do you by any chance happen to use server-side rendering in your project?

**Comment by hf** [comment]
A refresh token can only be used once. Do you maybe have some retry behavior that is refreshing the same token twice?

**Comment by GaryAustin1** [comment]
Also if that user signs out out any device, all other refresh tokens are invalidated.

**Comment by alexreyes** [comment]
@GaryAustin1 Hmmm... that might be the cause of this refreshToken expiring. I had the same account logged into my device as I was using for testing on my laptop. That could be it. 

That being said, the problem of the app signing people out after a time still happens to others. I'll keep trying to repro it

@hf no, I don't have any retries on here.

**Comment by alexreyes** [comment]
@hf Is there any part of goTrue that makes users log out after a certain amount of time? Say a week, or a couple of days? I've noticed even supabase.com will sign me out periodically

**Comment by j4w8n** [comment]
@alexreyes as far as I know, gotrue will not logout a user unless `signOut()` is called. Other than that, only the tokens expiring would cause that type of behavior (if your app is programmed to logout without a valid access token).

**Comment by sebasbeleno** [comment]
Same behavior here :/

**Comment by kangmingtay** [comment]
Hi @sebasbeleno, this is a known issue with supabase-js v1 and we have fixed in v2. We recommend that you upgrade to the latest version of supabase-js and you can follow this migration guide to get started: https://supabase.com/docs/reference/javascript/v1/upgrade-guide

> The refresh token expires after a long time (2 or 3 days).

Also, just FYI, the refresh token doesn't have an expiry date. However, it can only be used once and subsequent attempts to reuse it will invalidate refresh tokens in the current session.

**Comment by GaryAustin1** [comment]
Closing as fixed in version 2 supabase-js.
