### ISSUE TITLE
Need to update documentation: --from-stdin is no longer supported

### ISSUE THREAD

**Issue by EshaanAgg** [supabase/supabase#9684]
# Bug report

## Describe the bug
In the documentation in the README.md of `https://github.com/supabase/supabase/tree/master/examples/edge-functions`, we can see that the the command `supabase secrets set --from-stdin < .env` is provided, which is no longer supported.
![image](https://user-images.githubusercontent.com/96648934/196757253-cfe3ea5f-78ca-4168-b379-94ba294172bb.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone any example from `supabase/edge-functions`.
2. Try running the aforementioned command (`supabase secrets set --from-stdin < .env` ).

## Possible Fixes
Use `--env-file` flag instead.
I would like to work on this issue of updating the respective README.md.

**Comment by burmecia** [comment]
Thanks @EshaanAgg !
