### ISSUE TITLE
new sveltekit example is unsafe

### ISSUE THREAD

**Issue by j2l** [supabase/supabase#9698]
# Bug report
## Describe the bug

Thank you for recently adding the [sveltekit-user-management](https://github.com/supabase/supabase/tree/master/examples/user-management/sveltekit-user-management) example :+1: 
Despite the presence of `+layout.server.ts`, since there are no `+page.server.ts` to manage the lib and POST, `supabase url`, `anon key` and user data are visible within the client page, like in a svelte SPA, ruining the benefit of sveltekit.

`supabase url` and `anon key` shouldn't be visible, because you can easily grab all the db schema using openapi, then it turns the supabase server prone to attacks.

Additionally, data should be filtered on the server before being sent to the client, to only keep what you plan to expose to the client.

## To Reproduce
- `npm i` then (node adapter) `npm build` `npm preview` the example above
- FF > Debugger > (index) > PUBLIC_SUPABASE_ANON_KEY: ...
- Add var to watchlist and a breakpoint to catch the full user data (more than in the profile page).

## Expected behavior
Only data exposed to the client should be present in the client JS.

Please, please correct this example before it spreads out.
I'm trying to fix it but I fail because I don't totally get the whys and hows of the structure, if I find something I'll PR. 
But I'm sure you're more clever than me cause your example is working great (but is temporarily unsafe). :kiss:

**Comment by GaryAustin1** [comment]
I think Supabase would disagree with your assessment that using the anon key and the url on a browser client are unsafe.
I'm pretty sure every guide and the major uses of auth(gotrue) all require the anon key and url to run on the client at least for login with redirects.

From the main docs: 
```
In Supabase we issue JWTs for three different purposes:
    anon key: This key is used to bypass the Supabase API gateway and can be used in your client-side code.
    ....
 ```
And
```
Securing Your Tables
In Supabase, you can access your data directly from the client (often the web browser), you do this by passing your Supabase URL and Anon key to supabase-js like so:
...
```

I'll think you find just about all of Supabase's guides and example code make use of the client in someway using the anon key and url.

Maybe an issue requesting/suggesting a server side only approach is appropriate, but "unsafe" is not likely to get much movement.  In my opinion.

**Comment by j2l** [comment]
Thanks Gary
As I [explained here and there](https://github.com/supabase/cli/issues/539), being able to get all your db structure using openapi with the anon key (http://<url>/rest/v1/?apikey=<key>) is facilitating a hacker's job, so it's unsafe.
We need an anon key for visitors to be able to login and this can be done using server code in sveltekit. If you want to use browser for this, svelte is enough.

**Comment by j2l** [comment]
Thank you @GaryAustin1 
blocking openapi fixes this issue.
Yeah, I understand the Supabase stance for ease of use. 
I think it should be better explained in any example since anon key + openapi, by default, doesn't fully secure your work.
