### ISSUE TITLE
Changelog page overflow on mobile

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#9718]
# Bug report

## Describe the bug

When viewing the Changelog page on a mobile screen, the page overflows.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/changelog](https://supabase.com/changelog) on a small screen
2. See error

## Expected behavior

For the page to fit the screen.

## Screenshots

<img height="800" src="https://user-images.githubusercontent.com/70828596/197073432-60a963aa-263a-448e-9e22-42039c1d1f37.jpeg">

<img height="800" src="https://user-images.githubusercontent.com/70828596/197073431-1c2d3637-f5b9-4f2a-8bcd-8d905b44c04a.jpeg">

## System information

- OS: Any
- Browser: Any
- Version of supabase-js: n/a
- Version of Node.js: n/a

## Additional context

Yes I know I need to charge my phone.

**Comment by timothee-durand** [comment]
i can do it if you want

**Comment by hkaur008** [comment]
I would love to give it a try. Can I handle this ?

**Comment by Isaiah-Hamilton** [comment]
Sorry for the late response. @timothee-durand if you are still interested go ahead. if not, @hkaur008 you can take this if your still interested.

**Comment by timothee-durand** [comment]
Sorry, I didn't follow up but I've not managed to run supabase ok my computer so I give up, go ahead @hkaur008

**Comment by hkaur008** [comment]
![image](https://user-images.githubusercontent.com/56452820/198316032-567bd9bc-379b-41f5-98f3-51a8eb768664.png)
![image](https://user-images.githubusercontent.com/56452820/198316179-65798515-695f-420c-89d3-e31f178cf4af.png)

working fine now!
