### ISSUE TITLE
404 regarding reflection doc blog post related to pg-graphql

### ISSUE THREAD

**Issue by stavares843** [supabase/supabase#9745]
# Improve documentation

## Link 

https://supabase.com/blog/pg-graphql

## Describe the problem

Link returning 404 

## Describe the improvement

STR:
- Go to https://supabase.com/blog/pg-graphql
- Click on the reflection doc URL

<img width="862" alt="Captura de ecrã 2022-10-21, às 17 59 13" src="https://user-images.githubusercontent.com/29093946/197249517-b2ca951c-dcc2-4617-92b8-74ac832e4784.png">

- Goes to https://supabase.github.io/pg_graphql/reflection and returns 404

<img width="826" alt="Captura de ecrã 2022-10-21, às 18 00 02" src="https://user-images.githubusercontent.com/29093946/197249653-78108423-0db3-45c5-896f-b5306432a145.png">

## Additional context

I can open a PR if you let me know which URL is the correct one 🔨

**Comment by Hallidayo** [comment]
Hi @olirice - I've had a look the [pg_graphql](https://github.com/supabase/pg_graphql/) repo and it seems [this commit](https://github.com/supabase/pg_graphql/commit/36a79031e5897ce288aad4c595294125add243f9) removed the `reflection.md` file.

Should the following paragraph in the blog be removed:

<img width="514" alt="Screenshot 2022-10-25 at 20 54 34" src="https://user-images.githubusercontent.com/22655069/197846853-4a815c3a-e804-4f30-8ff9-727f9916d0b1.png">
