### ISSUE TITLE
Id field - sequence not in order

### ISSUE THREAD

**Issue by jorgemndoza** [supabase/supabase#975]
## Describe the bug

I have a table were the is sequence is incrementing by 2 instead of 1. I am doing a basic insert to a table of users. I noticed I was missing a few ids in the sequence.

## Expected behavior

I am expecting the id to follow a sequence incremented by 1

## Screenshots

![image](https://user-images.githubusercontent.com/13603927/112874250-502cd700-9088-11eb-88b5-f2d3a78c1478.png)

**Comment by steve-chavez** [comment]
I assume the transaction was rolled back(an error occurred, maybe a constraint failure) when inserting 3040, 3052, 3058.

Sequences work like that on postgres, the sequence is guaranteed to be ever-increasing but not that there will be no gaps. A sequence number is discarded when there's an error.

**Comment by jorgemndoza** [comment]
Thanks @steve-chavez makes sense. Is there a way to check the logs to find the failed transaction?

**Comment by steve-chavez** [comment]
@jorgemndoza Not currently, but we'll enable a logs view for the db on the settings page(after launch week).
