### ISSUE TITLE
Returning data sets requires further instruction

### ISSUE THREAD

**Issue by jesper-bylund** [supabase/supabase#9762]
# Returning data sets is not debuggable?

## Link 
https://supabase.com/docs/guides/database/functions#returning-data-sets

## Describe the problem

The current example leads to the following problem when I try to use it on my own dbs:
"return type mismatch in function declared to return posts"

The problem is that this makes sense. In the example it looks like the db is defined as a type. But this isn't done in the example, so there's no way to follow this. I can't even find a way to test what the datatype of my return value is when it's in a set?

## Describe the improvement
Either define what datatype is used and how. Or how to debug this error.

This is my example code that creates the error.
```
CREATE OR REPLACE FUNCTION list_unique_domains()
returns setof posts
language sql
as $$
  SELECT domain
  FROM posts
  GROUP BY domain;
$$;
```

**Comment by Hallidayo** [comment]
Hi @jesper-bylund are you having an issue with this one still?

If so you can change the return type to a defined table e.g :


```
CREATE
OR REPLACE FUNCTION list_unique_domains () returns table (domain varchar) language sql as $$
  SELECT domain
  FROM posts
  GROUP BY domain;
$$;
```

**Comment by jesper-bylund** [comment]
Hi @Hallidayo ,
I solved my specific use case, just forgot to close the issue. :) But how to debug this is still really hard to understand, would be great if there was an output that showed type, or documentation on how to debug it. 

I realise this is a bit of out-of-scope for Supabase, but since SQL is such a core use case, I think it would make sense to help users find information on this. :)
