### ISSUE TITLE
Database usage showing error

### ISSUE THREAD

**Issue by mashrurbd** [supabase/supabase#9765]
# Bug report
Database usage is showing error.

## Describe the bug

Please clarify this:

I have a table in the database and its only 32KB in size.

So why it is showing a Database Space Usage under Settings > Database page as 30 MB out of 512 MB?

Why it is taking upto 30MB of my 512 MB? I have no such datas in my database. 

Also please let me know if this thing resets or not.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by mashrurbd** [comment]
![Screenshot_20221022-161808](https://user-images.githubusercontent.com/12530291/197333980-05fc1351-02cc-4ec2-99ba-5b10e6ded5f9.png)
![Screenshot_20221022-161738](https://user-images.githubusercontent.com/12530291/197333983-38f538f5-7b57-4b6a-9106-8e9caacf06df.png)

**Comment by saltcod** [comment]
Hey @mashrurbd thanks for reporting this. Would you mind submitting a ticket via the dashboard so we can investigate that for you? That definitely doesn't look right.

Thanks!
![CleanShot 2022-10-28 at 09 29 24@2x](https://user-images.githubusercontent.com/105593/198582092-1f4ce86a-acc9-4828-819f-37fd9585b2d3.png)

**Comment by mashrurbd** [comment]
I already did, but your team says that should be fine. I don't know why
these takes up too much space in database.

Your team says to use Vacuum all. But this doesn't work out for me.

FYI: Support Ticket ID: 1177700511
