### ISSUE TITLE
Flutter logo in the studio home page is not shown

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#9769]
# Bug report

## Describe the bug

Could not get to the cause after a quick glance, but the Flutter logo in the home page of the studio (e.g. https://app.supabase.com/project/nlbsnpoablmsxwkdbmer) is not shown.

## Screenshots

<img width="1298" alt="Screen Shot 2022-10-22 at 23 11 06" src="https://user-images.githubusercontent.com/18113850/197343742-015f6781-735f-4919-a42b-fb7e14923c69.png">

**Comment by Hallidayo** [comment]
Hi @dshukertjr - I think once #9797 has been merged this will be resolved?
