### ISSUE TITLE
Hide the settings page on self-hosted / CLI

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#9775]
_Originally posted by @kiwicopple in https://github.com/supabase/supabase/issues/8721#issuecomment-1287867693_

The config pages shouldn't be appearing on the Studio if you are using the CLI or selfhosting

**Comment by beeman** [comment]
> I'll mark this one for the frontend to hide this page on self-hosted so that there is no confusion

For reference, this API Settings pages is linked through this page http://localhost:54323/project/default/api?page=users
