### ISSUE TITLE
Sponsors not being displayed

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase#979]
# Bug report

## Describe the bug

The list of sponsors are not being displayed, and it is sad, because it looks like Supabase doesn't have any supporters when actually you guys do a lot. 
https://supabase.io/oss

## Proposal

The cause is this logic here. 
https://github.com/supabase/supabase/blob/2268fd531beea3a49867994dcb64fd5cc6f58608/web/src/pages/oss.js#L21

To fix it, we need to update the [sponsors.json](https://github.com/supabase/supabase/blob/master/web/src/data/sponsors.json) or update the logic pointed out above. 

I am willing to fix this issue if someone could point me to the right direction. Should we fix the logic or should we update the json? 

Obviously, if we decide to go the json method, we would need to do it every month. 
If we choose to update the logic, then I would appreciate to have rough direction of how we would want to do it.

**Comment by kiwicopple** [comment]
Thanks for opening this one @dshukertjr . We definitely need to fix this - the main issue is that I couldn't find an API method for the sponsors (when I first implemented this), and so I had to download the sponsors as a JSON file (every month...)

Do you know if there is an API method now?

> I am willing to fix this issue

Would love your help with this. If you want, we can also move this page from the doc website (`web` folder) to the new website (`www` folder). 

We also need to decide whether we show all the sponsors, or only the sponsors who are "currently" active. If it's all of the sponsors then it's actually quite easy, but note that some sponsors were once on the "enterprise" tier, and now are on a lesser tier. 

Perhaps we add  a sections - one for current sponsors, and one for past sponsors? Really up for any ideas here - it was a long time ago when we built this page

**Comment by dshukertjr** [comment]
Thanks for a quick response @kiwicopple !

> Do you know if there is an API method now?

There might be one, but it is my first time actually interacting with GitHub's graphQL, so let me take some time to explore it a bit more. 

> Would love your help with this. If you want, we can also move this page from the doc website (web folder) to the new website (www folder).

I am definitely not up to speed here, but what would be the benefit of this?

> Perhaps we add a sections - one for current sponsors, and one for past sponsors? Really up for any ideas here - it was a long time ago when we built this page

I like this idea. Let me explore in this direction!

**Comment by thakkaryash94** [comment]
I think using the below API, we can fetch the organization sponsors. But currently, it is throwing the below error for me.

query:
```bash
{
  organization(login: "supabase") {
    id
    sponsorsListing {
      name
      tiers {
        nodes {
          name
        }
      }
    }
  }
}
```

response:
```json
{
  "data": {
    "organization": {
      "id": "MDEyOk9yZ2FuaXphdGlvbjU0NDY5Nzk2",
      "sponsorsListing": null
    }
  },
  "errors": [
    {
      "type": "FORBIDDEN",
      "path": [
        "organization",
        "sponsorsListing"
      ],
      "extensions": {
        "saml_failure": false
      },
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "message": "Although you appear to have the correct authorization credentials, the `supabase` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/"
    }
  ]
}
```

**Comment by kiwicopple** [comment]
nice @thakkaryash94 - do you have this full code snippet? I can try it with one of my keys

**Comment by thakkaryash94** [comment]
@kiwicopple You can use https://docs.github.com/en/graphql/overview/explorer, run the above query and fetch required data as well. You can read about it https://docs.github.com/en/graphql/reference/objects#sponsorslisting

**Comment by kiwicopple** [comment]
![image](https://user-images.githubusercontent.com/10214025/115205640-5a447180-a12c-11eb-8bf1-e9695e3cf0ef.png)

this query gives us the sponsorship tiers.

I also tried getting the data from these three:

![image](https://user-images.githubusercontent.com/10214025/115205792-7fd17b00-a12c-11eb-97a6-3c932a52e653.png)

and still couldn't get the data (they all returned empty nodes) 🤔

**Comment by dshukertjr** [comment]
I played around with the API's and was not able to retrieve list of active sponsors either.

**Comment by thakkaryash94** [comment]
I found this https://github.com/filiptronicek/gh-sponsors-api repo, which provides this endpoint https://sponsors.trnck.dev/supabase/sponsors with JSON. There is an open issue on community. https://github.community/t/api-for-sponsorship/14424

**Comment by rahul3v** [comment]
@kiwicopple well you can use directly https://github.com/sponsors/supabase/sponsors_partial?page={pageNum} link to grab all your sponsors and  print as you wish, grab till the **pageNum** output returns 0

**Comment by kiwicopple** [comment]
This is useful, thanks @rahul3v 👍

**Comment by rahul3v** [comment]
@kiwicopple  
Well, You can use a Cron Job  that can store all sponsors into a file every 24hr (change as per need), and you just access that file as an API into your code, that will work,

Just extract all important info as need and return a final json object inside a file or JSON fIle that you can use for your api

**Comment by kiwicopple** [comment]
Hey all - i have fixed this one to query from the GraphQL endpoint: https://supabase.io/oss

I am in the process of over-hauling this page too. We will create a larger and more up-to-date "open source" section in our site somewhere where we outline some of our philosophies and also update the maintainers list to include everybody who has contributed
