### ISSUE TITLE
Supabse Realtime: Error occurred when joining <channel>

### ISSUE THREAD

**Issue by Donnerstagnacht** [supabase/supabase#9798]
# Bug report
## Describe the bug
After updating my project to @supabase/supabase-js v2, subscribing to a Realtime Channel creates a WebSockets error:
`error occurred when joining realtime:public<table_name>`

**In Detail:**
Angular component calls a Supabase Realtime Channel and subscribes to it. 

```
`  getRealTimeChangesCounters(uuid: string): RealtimeChannel {
    const subscription = this.supabaseClient
    .channel(`public:profiles_counters`)
    .on('postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'profiles_counters'
      },
      payload => {
        console.log(payload)
      }
    )
    .subscribe()
    return subscription;`
```

**In chrome developer tools, I can observe the following web-sockets messages:**
![Screenshot 2022-10-24 142919](https://user-images.githubusercontent.com/35246325/197526921-8309dc4a-80e0-41dd-9fd4-ad7b85334958.jpg)
![Screenshot 2022-10-24 143011](https://user-images.githubusercontent.com/35246325/197527011-d98c33c8-ce49-4433-ab96-7058e7bcfcf1.jpg)
![Screenshot 2022-10-24 143055](https://user-images.githubusercontent.com/35246325/197527024-80fce6c2-3358-447d-b93c-612d0d9c959e.jpg)
![Screenshot 2022-10-24 143138](https://user-images.githubusercontent.com/35246325/197527042-e525ff17-00e9-4ca9-bb83-3e9c591691b8.jpg)
![Screenshot 2022-10-24 143226](https://user-images.githubusercontent.com/35246325/197527061-7bea42d1-6729-4dba-99d3-edb59ff19a96.jpg)

**And what I think might cause the error:**
![Screenshot 2022-10-24 143406](https://user-images.githubusercontent.com/35246325/197527088-76367555-da50-4f3c-bc08-2e4b8bab3fb0.jpg)

## Describe the bug

1. Go to https://github.com/Donnerstagnacht/polity
2. Clone the repo
3. Install dependencies
4. Init local supabase development
5. Serve Angular
6. Login with test user email: 4@test.com, password: 12345678
7. Navigate to: http://localhost:4200/search
8. Search for 'Tobias', press enter
9. Click the 'Follow' button
10. Open chrome developers' network tools

## Expected behavior
I expect a console.log() statement, logging the incremented counter number.
Instead, the above-described error is shown.

The issue seems to be related to this issue:
https://github.com/supabase/realtime/issues/295

I also found a similar issue: https://github.com/supabase/realtime/issues/217
However, as far as I understand the issue was related to RLS and RLS is disabled in my case.

## System information

- OS: Windows
- Browser: chrome, edge
- Local supabase development setup with Docker version 20.10.17, build 100c701
- Version of supabase-js stated by package.json:     "@supabase/supabase-js": "^2.0.4"
- Version of supabase: 1.11.0
- Package-lock.json:
```
    "node_modules/@supabase/postgrest-js": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/@supabase/postgrest-js/-/postgrest-js-1.1.0.tgz",
      "integrity": "sha512-qkY8TqIu5sJuae8gjeDPjEqPrefzcTraW9PNSVJQHq4TEv98ZmwaXGwBGz0bVL63bqrGA5hqREbQHkANUTXrvA==",
      "dependencies": {
        "cross-fetch": "^3.1.5"
      }
    },
    "node_modules/@supabase/realtime-js": {
      "version": "2.1.0",
      "resolved": "https://registry.npmjs.org/@supabase/realtime-js/-/realtime-js-2.1.0.tgz",
      "integrity": "sha512-iplLCofTeYjnx9FIOsIwHLhMp0+7UVyiA4/sCeq40VdOgN9eTIhjEno9Tgh4dJARi4aaXoKfRX1DTxgZaOpPAw==",
      "dependencies": {
        "@types/phoenix": "^1.5.4",
        "websocket": "^1.0.34"
      }
```
File links: 
Profile component: https://github.com/Donnerstagnacht/polity/blob/master/src/app/profile/profile/profile.component.ts
Profile service: https://github.com/Donnerstagnacht/polity/blob/master/src/app/profile/state/profile.service.ts
Table definition: https://github.com/Donnerstagnacht/polity/blob/master/supabase/migrations/101_profiles_table.sql
Enable Realtime: https://github.com/Donnerstagnacht/polity/blob/master/supabase/migrations/901_realtime.sql
Disable RLS: https://github.com/Donnerstagnacht/polity/blob/master/supabase/migrations/902_disable_row_level_security_for_testing.sql

Environment data: https://github.com/Donnerstagnacht/polity/blob/master/src/environments/environment.ts
package-lock.json: https://github.com/Donnerstagnacht/polity/blob/master/package-lock.json
package.json: https://github.com/Donnerstagnacht/polity/blob/master/package.json

## Additional context
I upgraded on Sunday 23.October 2022 to supabase-js v2. Before, all my real-time subscriptions worked. Now, **none** of the realtime subscription works anymore.

What is the error reason? How is it fixable?
Do I have to send an authorization header?

PS: It is my first time opening an issue, constructive feedback is very welcome!

**Comment by w3b6x9** [comment]
@Donnerstagnacht I have updated Realtime development so that it matches with hosted Realtime in your Supabase project. This shouldn't be an issue anymore.
