### ISSUE TITLE
Kong.yml has swapped anon key and service_role key when they are not manually set

### ISSUE THREAD

**Issue by globemediaofficial** [supabase/supabase#9815]
# Bug report

## Describe the bug

If you don't manually input your keys in `kong.yml`, they are added, but switched.

## To Reproduce

1. Create a pull of supabase
2. Put your anon key and service_role key in the `.env` file
3. Don't put them in `kong.yml`
4. Run `docker-compose up`
5. Look in `kong.yml` it will have the 2 keys but they will be switched 

## Expected behavior

The keys should be put in the correct places.

**Comment by jimmyruann** [comment]
I am encountering this problem too. Assuming that the OP mean anon key and service_role key in `kong.yml` are set manually and is not using the environment variables `ANON_KEY` and `SERVICE_ROLE_KEY`. Would be great that we could set this dynamically.

My current workaround now is to use `envsubstr` and modify `kong.yml`.
