### ISSUE TITLE
Specify that `data` object can be `null`

### ISSUE THREAD

**Issue by hyunbinseo** [supabase/supabase#9817]
# Improve documentation

## Link 

[Typescript Support](https://supabase.com/docs/reference/javascript/typescript-support#type-hints)

> `supabase-js` always returns a `data` object (for success), and an `error` response (for unsuccessful requests).

## Describe the problem

`Prefer: return=minimal` is set by default now.

- https://github.com/supabase/postgrest-js/pull/276

Therefore, if `.select()` is not chained, successful requests return `null` for both `data` and `error`.

## Describe the improvement

Current documentation is technically correct - successful requests do return `data` object of `null` or an array.

However, being more explicit would not hurt.

> `supabase-js` always returns a `data` array (for successful requests with `.select()` chained) …

## Additional context

The following code will always throw an error for both successful and unsuccessful requests.

```javascript
const { data, error } = await supabase
  .from('countries')
  .insert({ id: 1, name: 'Denmark' });

if (!data || error) throw new Error();
```

Successful responses used to return an `data` array, so the above code was valid in `v1`.

- https://github.com/supabase/supabase-js/issues/32

**Comment by GaryAustin1** [comment]
I believe in the case of .maybeSingle a .select() will also return null for 0 rows matched.

**Comment by charislam** [comment]
Closing as the Typescript support documentation has changed significantly and typing support should be better now
