### ISSUE TITLE
Would be great to have a detailed React demo for the auth

### ISSUE THREAD

**Issue by MatthewPosgate** [supabase/supabase#9819]
Including email/password sign up with otps and captchas.

**Comment by kiwicopple** [comment]
Hey @MatthewPosgate - this demo includes email/password:

https://supabase.com/docs/guides/with-react#building-the-app

Is that what you're looking for? Admittedly it doesn't include hcaptcha

**Comment by MatthewPosgate** [comment]
Hi, thanks for the tip. In actual fact it's the hcaptcha that wouldn't work for me on the verifyOtp.

**Comment by J0** [comment]
Hey @MatthewPosgate,

Do check out the following guide -https://supabase.com/docs/guides/auth/auth-captcha it's not an exact example but should walk you through how to get set up.

Let me know if there are still issues

**Comment by kiwicopple** [comment]
I'll close this one for now - it's hard to support every combination of feature + framework 😓 

If there are any specific questions, let us know @MatthewPosgate !
