### ISSUE TITLE
Schema for supabase client is wrong

### ISSUE THREAD

**Issue by pencilcheck** [supabase/supabase#9826]
# Improve documentation

## Link 

`https://supabase.com/docs/reference/javascript/initializing`

Add a link to the page which needs improvement (if relevant)

## Describe the problem

What's in API schemas is wrong, the syntax that worked for me is
```
import { createClient } from '@supabase/supabase-js'

// Provide a custom schema. Defaults to "public".
const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key', {
  schema: 'other_schema'
})
```

If I used the one in the doc, it doesn't seem to use the schema specified.

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

```
import { createClient } from '@supabase/supabase-js'

// Provide a custom schema. Defaults to "public".
const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key', {
  schema: 'other_schema'
})
```

A clear and concise description of the improvement.

## Additional context

The reason I know the syntax was wrong is because I created a new local empty schema on supabase, but somehow I still get data from the public schema and somehow I got no expected grants error (since the new schema has no grants).

The moment I use the correct syntax I get no access error, which is expected.

**Comment by GaryAustin1** [comment]
You are using Supabase-js v1.  If you select v1 at top of reference page you will see the syntax you are using. Or use Supabase-js v2 code with the v2 docs.

**Comment by kiwicopple** [comment]
screenshot to make this clearer!

<img width="570" alt="image" src="https://user-images.githubusercontent.com/10214025/198074656-7eb07146-b814-4741-8b10-4f0cad0ec880.png">

Also a direct link: https://supabase.com/docs/reference/javascript/v1/
