### ISSUE TITLE
Supabase GUI keeps crashing, CORS request Error

### ISSUE THREAD

**Issue by barsketis** [supabase/supabase#9840]
# Bug report

## Describe the bug
I consistently get kicked out of the online Supabase GUI, the console shows its due to CORS request failing.
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at XX. (Reason: CORS request did not succeed). Status code: (null)."

I will get brought back to the login screen despite remaining signed in. 

I also get this error editing tables, it will get stuck after editing and eventually throw the error ""An error has occured: NetworkError when attempting to fetch resource."

## To Reproduce
Use Firefox on Ubuntu, and navigate around the portal, it happens on practically every page.

## Expected behavior

To be able to navigate in the portal without constantly being kicked out and asked to login again.

## Screenshots
![Screenshot from 2022-10-25 11-46-49](https://user-images.githubusercontent.com/7006807/197834458-075e6790-71db-46e1-8bb4-0e1605670427.png)

## System information

- OS: Ubuntu 22.04.1 LTS 64-bit
- Browser (if applies): Firefox - vanilla installation, standard protection tracking, also happens on Chrome in incognito mode
- Version of supabase-js: N/A online portal
- Version of Node.js: N/A online portal

## Additional context
This has been happening to me for over a month. I have tried multiple web browsers, I tried reinstalling Ubuntu, I also tried this on multiple machines.

**Comment by awalias** [comment]
>standard protection tracking, also happens on Chrome in incognito mode
could it be the browsers aren't allowing the app to store the session locally?

**Comment by barsketis** [comment]
It is possible, I don't see why it would sometimes work however if the session isn't being stored after logging in. I would suspect the portal should work in default browser configurations. I used chrome incognito just as an example with no extensions enabled or cookies that could be interfering, my default chrome browser has the same issues.

**Comment by alaister** [comment]
Hi @barsketis,

Is this still an issue for you?

**Comment by barsketis** [comment]
I am traveling currently and dont have access to my linux desktop, but as of two weeks ago this issue still persist for me. The issue does not happen on my Macbook, I believe the issue is related to Ubuntu running firefox or chrome. 

I will check back after the holidays to see if there have been any improvements recently.

**Comment by barsketis** [comment]
This issue appears to have been resolved, I am not longer crashing in the GUI.

Thank you
