### ISSUE TITLE
Can't refresh session

### ISSUE THREAD

**Issue by Lewitje** [supabase/supabase#9847]
# Bug report
My session has expired and I can't logout / login or setSession to get a new token

## Describe the bug
When calling anything in the API I get the error: [AuthApiError: Invalid token: token is expired by 54m48s]
When calling setSession to get a new one it says: "error": [AuthSessionMissingError: Auth session missing!]

## To Reproduce
1. Login
2. Wait for token to expire
3. When token has expired try calling anything in the API

## Expected behavior
The docs say when the token expires I should use this call to get a new one, but the call doesn't work when provided with the refresh_token
https://supabase.com/docs/reference/javascript/auth-setsession 

## System information

- OS: Android (Emulator)
- Version of supabase-js: 2.04
- Version of Node.js: 16.17.0

**Comment by j4w8n** [comment]
The `setSession` docs are outdated.

You can either do this:
`const { data, error } = supabase.auth.setSession({ access_token, refresh_token })`

Or use the new `refreshSession` method:
`const { data, error } = supabase.auth.refreshSession({ refresh_token })`

I have a PR to add the docs for refreshSession, and someone else has another to update docs for setSession.
