### ISSUE TITLE
AuthApiError: Error logging out user

### ISSUE THREAD

**Issue by brykov** [supabase/supabase#9852]
# Bug report

I am getting `AuthApiError: Error logging out user` when attempting to invoke a `signOut()` method

## Describe the bug

Here is a snippet of the code I'm running:
```
                  <Menu.Item
                    onClick={async () => {
                      if (ctx) {
                        const { error } = await ctx.supabase.auth.signOut();
                        if (error) {
                          console.log(error);
                        } else {
                          document.location.assign(routes.signIn);
                        }
                      }
                    }}
                  >
                    <Text>Sign out</Text>
                  </Menu.Item>
```

This is a menu item that invokes `supabase.auth.signOut()`. It worked before. But recently it started producing an error:
![image](https://user-images.githubusercontent.com/476516/197912727-00a86d4a-3143-46b8-a7d5-c3dfbf35387d.png)

## To Reproduce

Use `supabase.auth.signOut()` and observe 500s in the network tab.

## Expected behavior

It should sign the user out.

## System information

MacOS 12.5.1, Chrome 105.0.5195.125

**Comment by brykov** [comment]
I updated my Chrome to 107.0.5304.62, but the problem persists.

**Comment by brykov** [comment]
I also tried to clean all my local browser data, and sign in back again, but sign out is still broken

**Comment by saltcod** [comment]
Hey @brykov — what version of supabase-js are you using?

**Comment by awalias** [comment]
seems to be coming from here: https://github.com/supabase/gotrue/blob/41668b77c23003296ef642f7565fb97375b4fef2/api/logout.go#L31

**Comment by brykov** [comment]
> Hey @brykov — what version of supabase-js are you using? 

2.0.4

**Comment by brykov** [comment]
Resolved!
