### ISSUE TITLE
GUI populates timestampz even if Default value is NULL and Allow empty is true

### ISSUE THREAD

**Issue by peachp** [supabase/supabase#986]
# Bug report
Not sure if this might be a feature, but IMHO if I explicitly set **Default Value** to `NULL` and tick **Allow empty**, it shouldn't pre-populate the field when adding a row via GUI or otherwise. And even when I click the field and empty the date and the time and click Update, it says **Invalid Date** (but this is separate issue I guess).
![image](https://user-images.githubusercontent.com/47209189/113037136-fcf07c80-918c-11eb-9414-36c37f1a05b9.png)
![image](https://user-images.githubusercontent.com/47209189/113037248-198cb480-918d-11eb-8f59-87f9355f34d1.png)

**Comment by awalias** [comment]
thanks @peachp will check it out

**Comment by kiwicopple** [comment]
this is now fixed 👍

**Comment by joshenlim** [comment]
hey there @peachip! we've been pushing out fixes and improvements for the side panels and this issue should be resolved now. I'm going to close the ticket for now but feel free to reopen if you do run into any other issues!

**Comment by peachp** [comment]
@joshenlim thanks, will check it out next time
