### ISSUE TITLE
inconsistent naming for `const supabase = createClient()`

### ISSUE THREAD

**Issue by Dustin-dusTir** [supabase/supabase#9864]
# Improve documentation
In most of the documentation the supabaseClient Instance is named just `supabase`.    
All tutorials I have seen use the name `supabase`   

based on a search in the repository, there are 22 occasions where it says `const supabaseClient = createClient()`   

As a new user of supabase this has confused me.  
**Is there a good reason for the different naming conventions?**

## Link 

![image](https://user-images.githubusercontent.com/49081477/198039553-c06674b9-1c3f-4589-879f-be0357da0dad.png)

## Describe the improvement

I propose a careful search and replace with VSCode Regular expression in all .mdx files:   
search: `supabaseClient`  
replace: `supabase`  

## Additional context

Things to watch out when search and replacing: 
- the file in which createClient is usually invoked is called supabaseClient.[js, ts, jsx]; we don't want to change that.
- some other exceptions

the `const supabaseClient = createClient()` naming is also used in some examples in .tsx files visible at https://supabase.com/edge-functions

**I would be happy to make a pull request.**

**Comment by saltcod** [comment]
Thanks for flagging this @Dustin-dusTir — excellent suggestion.  cc @dannykng to keep in the back of your mind.

**Comment by dannykng** [comment]
@silentworks @thorwebdev thoughts on this? Are there any blockers or can we just make these consistent?

**Comment by thorwebdev** [comment]
This is sometimes used to distinguish between a browser client and a server client etc, but I think for the docs we can be consistent with using `const supabase = createClient()` 👍

**Comment by Dustin-dusTir** [comment]
I can offer to make a Pull Request for this Issue sometime this week if you want to.

I would carefully read over the affected .mdx files and make sure, that I also change all the references to the renamed object.

**Comment by dannykng** [comment]
That'd be great @Dustin-dusTir, thank you!
