### ISSUE TITLE
Confirm email switch dashboard UI bug

### ISSUE THREAD

**Issue by agalbenus** [supabase/supabase#9897]
# Bug report

## Describe the bug

There is a visual bug in the UI Dashboard for the Authentication Settings / Auth Providers / Email / Confirm email switch. The switch visually updates its state only after page refresh but not on save.

## To Reproduce

Go to Authentication Settings / Auth Providers / Email, turn on or off the Confirm email switch and click the Save button. 
The state of the switch in the UI will only remain saved after page refresh, but not on save

**Comment by agalbenus** [comment]
I guess the issue comes from here: https://github.com/supabase/supabase/blob/f016160539a8cad99c9d9e257c91f3adb357e09b/studio/components/interfaces/Auth/AuthProvidersForm/ProviderForm.tsx#L49

**Comment by ShaneMaglangit** [comment]
I would like to work on this issue so I did some initial investigation on the issue.

It seems like the payload returned by `https://api.supabase.io/platform/auth/<project>/config` returns the opposite value for `MAILER_AUTOCONFIRM` than what it was set on. Thus, every time any change is saved, the switch loads with the opposite state.

Is `api.supase.io/platform` open source? I can't seem to find the directory nor the repository responsible for this endpoint.

**Comment by GaryAustin1** [comment]
I believe this has been fixed.  I don't see any issues after toggling or saving the setting.  
Maybe more complex to replicate.
Going to close this.   Please comment if I am mistaken or you believe it still exists, possibly with more info.
