### ISSUE TITLE
Old & new blog

### ISSUE THREAD

**Issue by AlfonzAlfonz** [supabase/supabase#990]
# Bug report

## Describe the bug

Link in the footer of https://supabase.io/docs open an old version of blog but opening it in the new tab open different version of the blog.

## To Reproduce

- Go to https://supabase.io/docs
- Scroll down to the footer
- Open blog in the new tab
- Open blog

## Expected behavior

Both actions should open a same page.

**Comment by kiwicopple** [comment]
Thanks for this report @AlfonzAlfonz . Fix going live now
