### ISSUE TITLE
With the newest release table names are cut off / cannot resize

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#9910]
# Bug report

## Describe the bug

With the newest Release (probably same one that introduced RLS by default?) the table names are cut off when too long and there is no indicator in terms of ellipsis nor can I resize anymore.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9058762/198372688-82a07313-d7bd-42a6-bb72-9f94bc5a03ae.png">

## To Reproduce

Create table with name `host_assignment_image_paths` 

Go to table view: See it is cut off.

## Expected behavior

- Can resize again
- Indicates it being too long instead of being cut off

**Comment by saltcod** [comment]
Thanks @activenode 
You can still see the full name by the title when you hover. Agreed we could make this a little neater. 

<img width="252" alt="CleanShot 2022-10-28 at 09 26 56@2x" src="https://user-images.githubusercontent.com/105593/198581706-0a7208de-4591-447d-abc6-636b4593c7f2.png">

**Comment by saltcod** [comment]
Going to mark this as closed as well. It's possible to reveal the full name by hovering the truncated name there, and we have no immediate plans for allowing expanding of the sidebar there in the layout. Appreciate the report.
