### ISSUE TITLE
TypeScript in JavaScript example 

### ISSUE THREAD

**Issue by stieludv** [supabase/supabase#9922]
# Improve documentation

## Link 

[supabase.com/docs/guides/with-nextjs#launch](https://supabase.com/docs/guides/with-nextjs#launch)

## Describe the problem

There is TypeScript in the JavaScript example.

## Describe the improvement

Removal of `import type { NextPage } from 'next'` and modification of `const Home: NextPage = () => {
` to `const Home = () => {`

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by stieludv** [comment]
Proposed fix: https://github.com/supabase/supabase/pull/9923

**Comment by saltcod** [comment]
Nice. Thanks @stieludv !
