### ISSUE TITLE
Edge Functions: using puppeteer throws error: {"name":"PermissionDenied"}

### ISSUE THREAD

**Issue by JoleMile** [supabase/supabase#9924]
# Bug report

## Describe the bug

I'm trying to run Puppeteer https://deno.land/x/puppeteer@16.2.0 in the Deno edge function.
When running it, I get the {"name":"PermissionDenied"} error, probably due to lack of read/write permissions.

## To Reproduce

Deploy the following function and try making a request. (Sorry about the formatting)

-----------------------------------------------

import { serve } from 'https://deno.land/std@0.131.0/http/server.ts';
import puppeteer from 'https://deno.land/x/puppeteer@16.2.0/mod.ts';

export const corsHeaders = {
	'Access-Control-Allow-Origin': '*',
	'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey',
};

serve(async (req) => {
	if (req.method === 'OPTIONS') {
		return new Response('ok', { headers: corsHeaders });
	}

	try {
		const browser = await puppeteer.launch();

		return new Response(JSON.stringify({}), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
	} catch (error) {
		return new Response(JSON.stringify(error), {
			headers: { ...corsHeaders, 'Content-Type': 'application/json' },
			status: 400,
		});
	}
});

-----------------------------------------------

## Expected behavior

The function should run normally just as it runs locally.

## Screenshots

<img width="376" alt="Screen Shot 2022-10-28 at 11 06 01 PM" src="https://user-images.githubusercontent.com/9325716/198562713-7d3adac6-9deb-4594-9ed0-e4f3dd1d1e1f.png">

## Additional context

Is there maybe a way to provide all permissions to the function. Like how we can pass -A/--allow-all to deno when running it locally?

**Comment by JoleMile** [comment]
@laktek thanks for the update.
FYI, it is possible to run the puppeteer on serverless functions. I got it working on Netlify and it was working well.
Here is a "tutorial" for it, although it might need a few tweaks (must use matching lib versions, etc.): https://bitsofco.de/how-to-use-puppeteer-in-a-netlify-aws-lambda-function

**Comment by laktek** [comment]
@JoleMile Thanks for sharing the link. Although this tutorial is for Serverless functions (AWS Lambda), not Edge functions (Deno Deploy). It's bit confusing since since Netlify offer two flavors of functions, Supabase functions are only Edge functions.
