### ISSUE TITLE
Typo in the generated API documentation

### ISSUE THREAD

**Issue by thalkz** [supabase/supabase#994]
# Fix a typo in the generated API documentation

## Link 

https://app.supabase.io/project/<project_id>/api/default?resource=users

## Describe the problem

I have created a users table in a Supabase project and a code snippet on the page "API > Tables and View > users" contains a typo. This code does not work :
![image](https://user-images.githubusercontent.com/16003829/113061969-418f0e80-91b3-11eb-8677-2a6b77337897.png)

## Describe the improvement

Replace `.from('users:column_name.eq.someValue')` with `.from('users:column_name=eq.someValue')` in the docs.

**Comment by awalias** [comment]
ah! good catch @thalkz fixing now!

**Comment by kiwicopple** [comment]
Fixed :) going out in the next deploy
