### ISSUE TITLE
Adding Columns to Table

### ISSUE THREAD

**Issue by AngeloAnolin** [supabase/supabase#997]
# Bug report

## Describe the bug

When a new column is added, the new column does not appear right away. This could lead users to think that the column they've added was not successful.

## To Reproduce

1. Navigate to the Database section.
2. Click on the Tables.
3. On the top right hand side of the table columns display, click on the `+New` button.
4. Add the column required as necessary.
5. Click `Save`. Notice the column is not displayed unless you refresh the page.

## Expected behavior

Column added should be displayed on the list once after saving.

## Screenshots
![image](https://user-images.githubusercontent.com/1944084/113073744-f4954300-9186-11eb-8f7f-975e1591d193.png)

![image](https://user-images.githubusercontent.com/1944084/113073803-0e368a80-9187-11eb-8107-e47dc08c3f12.png)

![image](https://user-images.githubusercontent.com/1944084/113073852-24dce180-9187-11eb-938f-4007f096fafb.png)

Notice that test_column added did not display.

## System information

- OS: Windows10
- Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

## Additional context
Refreshing the page will display the newly added column.

**Comment by awalias** [comment]
hey @AngeloAnolin thanks a ton for filing the bug, will look into it and figure out a solution

**Comment by kiwicopple** [comment]
this is now fixed 👍
